### ISSUE TITLE
[SMTChecker] Try to solve the deposit contract loop

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#10007]
The `assert(false)` in https://github.com/axic/eth2-deposit-contract/blob/master/deposit_contract.sol#L158 should be unreachable. It is currently not solvable with the SMTChecker.

I wrote a direct CHC version of it in https://gist.github.com/leonardoalt/d9a000dc03fd7cba90e4bcf472549d79, but z3/Spacer is unable to solve it.

We could try to solve it first directly as CHC before trying to solve it with the SMTChecker.

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by hrkrshnn** [comment]
@GeorgeSheridan no.

**Comment by leonardoalt** [comment]
As explained in https://github.com/ethereum/solidity/issues/9806, we can't really expect to solve the loop, aka proving that `assert(false)` is not reachable, due to it needing a nonlinear inductive invariant which we can't expect to be found.
