### ISSUE TITLE
[SMTChecker] ICE in indexOrMemberAssignment() when assigning to a storage variable qualified with contract name

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10011]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
	uint a;
	constructor(uint x) {
	(C.a = 0);
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1233): Throw in function void solidity::frontend::SMTEncoder::indexOrMemberAssignment(const solidity::frontend::Expression &, const smtutil::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.4-develop.2020.10.12+commit.bc97c3e1.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by cameel** [comment]
Looks fresh. 0.7.2 broke it. Also, works without the `SMTChecker pragma`.

@agroce Could you also indicate if the error is a blocker for your fuzzer when reporting (or add a label, but I'm not sure if github lets you do that)? I'm assuming that most of these bugs are but that might not be true :)

### Slightly simpler repro
```solidity
pragma experimental SMTChecker;

contract C {
    uint a;

    function foo() public {
        C.a = 0;
    }
}
```

### Warnings on 0.7.1 (for the simpler repro)
```
Warning: Assertion checker does not yet implement such assignments.
 --> /tmp/test.sol:7:9:
  |
7 |         C.a = 0;
  |         ^^^^^^^
```

**Comment by agroce** [comment]
@cameel with AFL, few bugs are blockers per se, though anything it finds frequently is going to hurt fuzzing throughput, I suspect.  Unfortunately, github doesn't let me put on labels.  I'd say this one is not really a blocker at all, it takes forever to find, though the fuzzer instance that found it is probably going to eventually lose some time in producing it again.  This is less of a problem for my fuzzing, really -- there are a few really easy to hit bugs, but the mutation-based improvement to AFL I'm using has a nice side effect of reducing bug duplication.

**Comment by cameel** [comment]
Thanks for the explanation. I don't think we have to be very strict with that label, I think it was created primarily to help prioritizing stuff so applying it to bugs that significantly hurt fuzzing throughput should be fine too. Anyway, if you think any specific bug qualifies just put that in the description and I'll apply the label :)

**Comment by bshastry** [comment]
Not sure if this is somewhat similar to https://github.com/ethereum/solidity/issues/9742

**Comment by cameel** [comment]
Yeah, I think this is the same bug. In both cases removing the contract name fixes it.

**Comment by leonardoalt** [comment]
Fixed by https://github.com/ethereum/solidity/pull/10111
