### ISSUE TITLE
Limit enums to 256 possible values so the contract storage size is fixed at 8 bits

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10035]
This was originally a part of #9986.

Arguments for adding the limit:
- Having more than 256 values seems like a very rare case. Does it even happen in practice?
- We're not even sure if all tools support enums bigger than 1 byte properly. Enums always taking up just one byte might be a common assumption.
- ~It's a potential blocker for allowing enums to be extended (#9986, if we decide to implement that feature).~

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by cameel** [comment]
Oh, interesting.

Yeah, it's a simple change and it might be a good first issue but it's already solved. Here's the PR #10035 (currently going through review).

**Comment by chriseth** [comment]
@GeorgeSheridan this is very interesting indeed! Could you identify other issues in this repository to be potentially labelled GFI?

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/10247

**Comment by George-Sheridan** [comment]
Yeah, we just selected some issues from this repository to make predictions. This tool can also be used on other issues and will be available in the future.
