### ISSUE TITLE
ICE in void solidity::frontend::CompilerUtils::popAndJump

### ISSUE THREAD

**Issue by gitpushOmnik** [ethereum/solidity#10042]
## Description

Solidity Compiler reports the following ICE when compiling the contract given below with ABIEncoderV2

## Steps to Reproduce

Contract : 

    pragma experimental ABIEncoderV2;

    contract Fudge 
    {
        function accept (bytes[] memory acc1, uint[] memory acc2) public returns(string calldata)
        {
             return "";
        }
        function parser(bytes[] memory var1, uint[] memory var2) external returns(uint)
        {
            string memory y = accept(var1,var2);
            return 0;
        }
    }

Compile with :  

    solc test.sol

Throws the following ICE : 

    /Solidity/libsolidity/codegen/CompilerUtils.cpp(1372): Throw in function void 
    solidity::frontend::CompilerUtils::popAndJump(unsigned int, const evmasm::AssemblyItem &)
    Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
    std::exception::what: 
    [solidity::util::tag_comment*] = 

Failing at : 

    solAssert(m_context.stackHeight() >= _toHeight, "");

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):-
- Framework/IDE (e.g. Truffle or Remix):-
- EVM execution environment / backend / blockchain client:-
- Operating system:-

**Comment by cameel** [comment]
Thanks for the report!

This is already fixed though. It's been reported in #9803 and fixed in #9822 (which was released in 0.7.2) so I'm going to close it.
