### ISSUE TITLE
Unexpected require argument expression execution

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#10089]
## Description

I would expect `require(condition, revertReason)` construction to not perform `revertReason` expression. For example, it could contain some parsing of previously happened revert reason:

```solidity
(bool success, bytes memory result) = address(target).call(data);
require(success, RevertReasonParser.parse(result, "Call failed: "));
```

Right now `require` construction behavior [described in docs in a wrong way](https://solidity.readthedocs.io/en/latest/control-structures.html#revert) – two options are not equivalent:

![telegram-cloud-photo-size-2-5226429365179494300-y](https://user-images.githubusercontent.com/702124/96749016-f63a2e00-13d2-11eb-9d31-ca817200fbba.jpg)

## Environment

- Compiler version: 0.5.x, 0.6.x, 0.7.x

## Steps to Reproduce

1. Try to deploy code with argument `x` equal to `0`:

    ```solidity
    // SPDX-License-Identifier: MIT

    pragma solidity ^0.6.0;


    contract BadRequire {
        constructor(uint256 x) public {
            require(true, f(x));
        }
        
        function f(uint256 x) public pure returns(string memory)  {
            if (x == 0) {
                revert("Ooops");
            }
            return "Some reason";
        }
    }
    ```

2. I expected this tx to succeed, but it will be reverted with reason "Ooops"

**Comment by leonardoalt** [comment]
@k06a why do you expect it to succeed? You're explicitly making it revert

**Comment by chriseth** [comment]
Thanks, we should update the documentation to state that it still is just a regular function call that evaluates all its arguments.

**Comment by k06a** [comment]
@leonardoalt I expected `f()` call would not have been happened at all, since the first arg was `true`

**Comment by k06a** [comment]
@chriseth are you sure it is better to keep it as it is, instead of making it behave differently?

**Comment by leonardoalt** [comment]
@k06a right, so you'd expect the call to shortcut and *not* visit the second argument if the first is true

**Comment by k06a** [comment]
@leonardoalt true, I wish to avoid prev revert parsing in my example in case of call succeeded:
```solidity
(bool success, bytes memory result) = address(target).call(data);
require(success, RevertReasonParser.parse(result, "Call failed: "));
```

**Comment by k06a** [comment]
@leonardoalt I wish these statements in the doc to become true:
>The two syntax options are equivalent, it’s developer preference which to use.

**Comment by leonardoalt** [comment]
@k06a Sorry, but I still don't get how they're different. You can also do this:
```
contract C {
    function f() public pure {
        revert(r());
    }
    function r() internal pure returns (string memory) {
        revert("oops");
        return "require";
    }
}
```
This reverts with "oops"

**Comment by k06a** [comment]
I want two following versions of code to be equivalent:
```solidity
(bool success, bytes memory result) = address(target).call(data);
require(success, RevertReasonParser.parse(result, "Call failed: "));
```
and
```solidity
(bool success, bytes memory result) = address(target).call(data);
if (!success) {
    revert(RevertReasonParser.parse(result, "Call failed: "));
}
```

They are not equivalent right now, since first version evaluates argument even when `success == true`. I wish to avoid execution of `RevertReasonParser.parse(result, "Call failed: ")` in case of the first argument is true.

**Comment by leonardoalt** [comment]
Ok, I see now.
I disagree that they should be equivalent.
`require` is a function call and making it shortcut when the first argument is `true` would be inconsistent with other function calls.
