### ISSUE TITLE
[SMTChecker] CHC engine does not detect assertion violation

### ISSUE THREAD

**Issue by blishko** [ethereum/solidity#10087]
CHC engine of the SMT checker does not detect assertion violation in the following example with same modifier applied twice and an assertion inside the modifier. BMC engine correctly detects that the assertion will be violated for the outer modifier.
```
pragma experimental SMTChecker;
contract C
{
    uint x;

    modifier m {
         require(x == 0);
        _;
        x = x + 1;
        assert(x <= 2);
    }

    function f() m m public {
        x = x + 1;
    }
}
```

**Comment by leonardoalt** [comment]
@blishko in the current develop neither BMC nor CHC reports here, I'm wondering why

**Comment by blishko** [comment]
@leonardoalt I still get assertion violation when only BMC is run, but no report when only CHC or both are run (I think CHC incorrectly passes to BMC the information that this target is safe).

**Comment by leonardoalt** [comment]
@blishko On latest develop? I get no reports also when running BMC only.

**Comment by blishko** [comment]
Yes, even in latest develop. Not sure the problem could be. I have just realized that I have not put pragma in the snippet in this issue, so just double-check that?

**Comment by blishko** [comment]
I have edited the original snippet to include the pragma.

**Comment by leonardoalt** [comment]
Haha true, sorry about that. I also forgot about it, now BMC does report it.

**Comment by leonardoalt** [comment]
Fixed by https://github.com/ethereum/solidity/pull/10149
