### ISSUE TITLE
Change mutability of chainid opcode from pure to view

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10090]
Prompted by https://github.com/ethereum/solidity/issues/8854#issuecomment-629436203.

The `chainid` opcode in inline assembly blocks is considered as `pure`. A longer response from the issue:
> (Note: The `stateMutability` setting is not necessarily reflecting how EOAs interact with contracts (e.g. code run on client side or on chain), rather it is only reflecting whether a given function needs to read the state or needs to modify the state.)
> 
> I think we need to look at this from two angles:
> 1) Can it be calculated on client side.
> 2) Does it need any state access.
> 
> Let me answer 1) first as it is simpler: it can be calculated client side. See EIP-695 and EIP-1193 how a "modern" client should behave. Based on that I think nothing would stop a client from being capable to run it, without submitting it to the network.
> 
> And 2) is a bit more tricky, because chainid is not part of the state (or block), only part of client configuration. IIRC this was a debate at the time the EIP was added and made in such a way to avoid making forking simple. In this sense using `block.chainid` isn't the best, but I don't think there's any better option if we don't want another global function.
> 
> If we look at properly pure functions, then chainid should not be allowed, because that is an external variable (but as we know Solidity pure functions can depend on memory 😕).

The proposal is to change it to `view`.

**Comment by axic** [comment]
@nventuro since this was raised by you, can you chime in please? We discussed this on the last design call and we were only somewhat in favour as one could view both options as valid. If there's more confirmation from auditors and tools, that should tilt the decision.

**Comment by nventuro** [comment]
My views remain the same as [expressed here](https://github.com/ethereum/solidity/issues/8854#issuecomment-683306084):

>I'm not familiar however with clients that compure pure results without ever hitting a node (are there any?), it'd be good to check against those.

If the difference between `pure` and `view` is how clients interact with those, then their behavior is a good starting point to look at.

The other comment is about developer expectations. I would asumme a `pure` function depends exclusively on its arguments, and always returns the same value givne those (which, granted, does _not_ reflect how `pure` works with regards to e.g. `memory`). If we think this intuition is correct and want to steer things into that direction, going for a `view` `chainid` makes sense.

**Comment by axic** [comment]
> The other comment is about developer expectations. I would asumme a pure function depends exclusively on its arguments, and always returns the same value givne those (which, granted, does not reflect how pure works with regards to e.g. memory). If we think this intuition is correct and want to steer things into that direction, going for a view chainid makes sense.

If the transaction is signed with the EIP-155 format, then the `chainid` should always match. If it is signed pre-EIP-155 format (which is still valid), there can be a discrepancy. So in practice it is pure, but technically it is not as `chainid` is still dependent on execution time.

**Comment by axic** [comment]
To summarise: change the mutability of the `chainid` opcode to `view`. This means a change in the `ViewPureChecker` and tests.
