### ISSUE TITLE
[SMTChecker] ICE in SMTEncoder's function `SMTEncoder::bitwiseOperation` due to bitwise operation in the function 

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10106]
```
pragma experimental SMTChecker;
contract C {
	function f() public {
		fixed x;
		x>>>6;
	}
}
```

throws

https://github.com/ethereum/solidity/blob/07e3f60ffc3072de2c108ca2f8038a921bbdb1d1/libsolidity/formal/SMTEncoder.cpp#L1630

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by bshastry** [comment]
@leonardoalt I moved this to the SMT checker MVP project to save you a few clicks. Please let me know if I should not do this by default.

**Comment by leonardoalt** [comment]
@bshastry sure, thanks!
