### ISSUE TITLE
4 Internal Compiler Errors in compiler version 0.7.4 

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#10104]
Hello everyone , I want to report 4 cases of Internal Compiler error. 

## Description

1) Contract :

pragma experimental SMTChecker;
	function f( int y,int x)pure {}

reports an internal compiler error :

Internal compiler error during compilation:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/formal/SMTEncoder.cpp(708): Throw in function void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition&)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

2) Contract :

pragma experimental SMTChecker;
contract C {
	uint[] a;
	function f() public {
		a.push()=
		a.push();
if (0<1){}
if (0==1){}
	}
}

reports internal compiler error :

Internal compiler error during compilation:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/formal/SMTEncoder.cpp(1783): Throw in function void solidity::frontend::SMTEncoder::assignment(const solidity::frontend::Expression&, const solidity::smtutil::Expression&, const solidity::frontend::Type* const&)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

3) Contract :

pragma experimental SMTChecker;

contract C {
	uint[] a;
	function f() public {
		a.push()=
		a.length;
	}
}

reports internal compiler error :

Internal compiler error during compilation:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/formal/SMTEncoder.cpp(1783): Throw in function void solidity::frontend::SMTEncoder::assignment(const solidity::frontend::Expression&, const solidity::smtutil::Expression&, const solidity::frontend::Type* const&)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

4) Contract :

pragma experimental SMTChecker;    
function f(bool x)pure {       assert(x);}

internal compiler error :

Internal compiler error during compilation:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/formal/SMTEncoder.cpp(708): Throw in function void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition&)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

## Environment

- Compiler version: 0.7.4_+
- Target EVM version (as per compiler settings): 0.7.4+commit.3f05b770.Linux.g++
- Framework/IDE (e.g. Truffle or Remix): verified in Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 16.04 Bionic

## Steps to Reproduce

Run solfuzzer with our own fork of AFL (will be published soon)

**Comment by bshastry** [comment]
Thank you for reporting the issues @CHM1993 . To me (2) and (3) seem to be duplicates of https://github.com/ethereum/solidity/issues/9743

(1) and (4) seem to be duplicates of https://github.com/ethereum/solidity/issues/9654

Since fuzzing is done both internally and externally by at least one other person, bug collisions are likely. Please let me know if the bugs reported here are different.

**Comment by axic** [comment]
To me it seems 1 and 4 are due to the SMTChecker does not yet supporting "free functions", see #9636. The other two likely are duplicates according to @bshastry.

@CHM1993 thank your for the reports! Let us know once you publish your fuzzer and any other issues are welcome too. I'm going to close this in order to reduce the number of open issues.

**Comment by chamitro** [comment]
yes thats true, contract 1 and 4 trigger the solAssert(m_currentContract, ""); of the initFunction in SMTSolver.cpp, while Contracts 2 and 3 make the solAssert(false, ""); crash in SMTassigment again in SMTSolver.cpp.
Thats some issues that I think should be fixed.
Thank you.
