### ISSUE TITLE
[SMTChecker] ICE in SMTEncoder::identifierToVariable function

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10107]
```
pragma experimental SMTChecker;
uint constant b = 0;
uint constant d = b;
```

throws

https://github.com/ethereum/solidity/blob/07e3f60ffc3072de2c108ca2f8038a921bbdb1d1/libsolidity/formal/SMTEncoder.cpp#L2296

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by leonardoalt** [comment]
Similarly to free functions, this will be fixed with https://github.com/ethereum/solidity/issues/10109 (hopefully). Should we keep both open or close this?
@bshastry

**Comment by bshastry** [comment]
Thanks @leonardoalt closing this as a duplicate
