### ISSUE TITLE
can not compile some contract to Ewasm

### ISSUE THREAD

**Issue by q871795224** [ethereum/solidity#10100]
## Description

We are working on the version migration of a contract (from 0.4.x to 0.7.x) for detecting the vulnerability of the smart contract on EWasm, but an error occurred when using the --ewasm function of solc.

## Environment

- Compiler version: 0.7.4+commit.3f05b770.Linux.g++
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04

## Steps to Reproduce

Because the number of lines of contract code involved is too long, so I put it in the [network disk](https://drive.google.com/drive/folders/1tYu8QYt3gO7nX3-kXYWD9H3hIrZiDqNs?usp=sharing). The corresponding error message can be seen as follows.

The command I used is as follows:

```
solc --ewasm [contract]
```

There are the following types of errors:
error1:
```
Internal compiler error during compilation:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/codegen/YulUtilFunctions.cpp(1968): Throw in function std::__cxx11::string solidity::frontend::YulUtilFunctions::readFromStorageDynamic(const solidity::frontend::Type&, bool)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] =
```
error2:
```
Unimplemented feature:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/codegen/YulUtilFunctions.cpp(2023): Throw in function std::__cxx11::string solidity::frontend::YulUtilFunctions::readFromStorageReferenceType(const solidity::frontend::Type&)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::UnimplementedFeatureError>
std::exception::what: 
[solidity::util::tag_comment*] =
```
error3:
```
Internal compiler error during compilation:
/build/solc-0s1t3A/solc-0.7.4/libsolidity/interface/CompilerStack.cpp(1257): Throw in function void solidity::frontend::CompilerStack::generateEwasm(const solidity::frontend::ContractDefinition&)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] =
```
error4:
```
Unknown exception during compilation: map::at
```
error5:
```
Error: Function not found.
            stop()
            ^--^
```

**Comment by chriseth** [comment]
Compiling to ewasm is - as ewasm itself - still a work in progress. What exactly do you plan to do with an ewasm version of our contract?

**Comment by q871795224** [comment]
We plan to use the ewasm version of contract to detect vulnerabilities in smart contracts.

**Comment by chriseth** [comment]
Which ewasm specification do you use for that?

**Comment by cameel** [comment]
As @chriseth said, this wasm code generation is still experimental and some of these crashes are caused by unimplemented features rather than bugs. Some do look like bugs to me though.

Anyway, it's all stuff that needs to be fixed/implemented eventually so I checked each of your files to see what specifically is broken or missing and reported each one as a separate issue. I added them all to implementation backlog:
- Strings in public storage variables: #10115
- Initializing a string storage variable: #10118
- Fallback function: #10116
- Abstract contracts: #9993
- Constructors with parameters: #10117

### Which problem affects which file
- error1
    - `message.sol`: strings in public storage variables
    - `AnyContract.sol`: strings in public storage variables
    - `SGCC.sol`: strings in public storage variables, fallback function
- error2
    - `Apuestas2018.sol`: strings in public storage variables, fallback function
    - `MyEtherTellerEntityDB.sol`: strings in public storage variables, fallback function
- error3
    - `ERC721_token.sol`: strings in public storage variables, abstract contract
    - `ERH.sol`: abstract contract, fallback function, constructor with parameters
    - `ETHLightToken.sol`: strings in public storage variables, abstract contract, fallback function
    - `GGPCToken.sol`: strings in public storage variables, abstract contract, fallback function, initializing a string storage variable
    - `Hotc.sol`: public storage variables, abstract contract, fallback function, constructor with parameters, initializing a string storage variable
- error4
    - `C2.sol`: constructor with parameters
- error5
    - `msgdata.sol`: fallback function
    - `REALLotteryWheel.sol`: fallback function
    - `Saaa.sol`: fallback function
    - `SpecialWallet.sol`: fallback function

**Comment by axic** [comment]
I suggest we close this since @cameel has created issues for the underlying problems.
