### ISSUE TITLE
Add support for create with bytecode

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#10101]
## Abstract

Allow a contract to create a new one based on bytecode passed as arguments. 

## Motivation

Currently is only possible to create a contract if the contract is specified in solidity code. However, there are some use cases, like factory contracts, which use bytecode coming from function calldata.
Currently we need to use assembly to achieve this:
```solidity
assembly {
    createdContract := create2(0, add(_initCode, 0x20), mload(_initCode), _salt)
} 
```

## Specification
```solidity
    function deploy(bytes memory _initCode, bytes32 _salt)
        public
        returns (address payable createdContract)
    {
        createdContract = new type.Contract{salt: _salt}(_initCode)
    }
```
## Backwards Compatibility

No issues

**Comment by chriseth** [comment]
Since such a feature breaks of out the type system, I would prefer to leave this accessible via inline assembly only. What is the problem with using inline assembly for that?

**Comment by 3esmit** [comment]
Technically there is no problem, however the tools keep warning about using inline assembly. 
If solidity implements this feature, it can also incorporate some checks like revert if create2 address returned zero. 

My suggestion about "type.Contract(bytecode)" might not be the best way, maybe you could add some better design to it for implementing it on Solidity. 

Personally I am OK using assembly, but I think would be nice to have this feature.

**Comment by chriseth** [comment]
Inline assembly is totally fine and safe if used properly. Tools should warn if inline assembly is used in user-written code but not when used in vetted and audited helper code.

**Comment by 3esmit** [comment]
I failed using inline assembly for this use-case.
My code is
```
    function deploy(bytes memory _initCode, bytes32 _salt)
        public
        returns (address payable createdContract)
    {
        assembly {
            createdContract := create2(0, add(_initCode, 0x20), mload(_initCode), _salt)
        }
    }
```
What is wrong with it?
Actually nothing, it works just fine - as programmed, except that `eth_estimateGas` always returns too low gas for executing create2 because it can't know that create2 failed!
So it is missing a check `require(createdContract != address(0), "Create2 failed")` so the outer transaction also fails when create2 is failing.
