### ISSUE TITLE
Array Bounds Checking Is Sometimes Unnecessary 

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#10103]
When looping through an array using the array length as the max bound, it is unnecessary to pay the gas for array bounds checking.

For example:
```
uint sum;
for (uint i; i < myarray.length; i++) {
  sum += myarray[i]
}
```

I see there is an issue about it here #9117 but no recent update.

Is it possible for the optimizer to optimize away the bounds access?  A manual way to turn it off? New range loop? What's the plan and timeline for this now?

In loops with many iterations, or many array index accesses, or nested loops this might really matter. I don't like paying gas for unneeded checking, which is most of the time I'm using arrays.

**Comment by axic** [comment]
Please avoid opening duplicate issues when you are aware of one. Just leave your commnets on the other issue.

**Comment by mudgen** [comment]
Okay. Understood.
