### ISSUE TITLE
[Sol->Yul] Implement readFromStorage for array types

### ISSUE THREAD

**Issue by mijovic** [ethereum/solidity#10128]
It will allow defining public state variables of array types.
For example in #9714 there is `address[] public owners` which fails because of missing this feature.

**Comment by chriseth** [comment]
Are you sure this is because of the getter? It should not try to read full arrays.

**Comment by mijovic** [comment]
> Are you sure this is because of the getter? It should not try to read full arrays.

I'll check once more and update

**Comment by mijovic** [comment]
It actually fails in `readFromStorage` for `bytes` Array which is inside of struct 
```
struct Transaction {
    address destination;
    uint value;
    bytes data;
    bool executed;
}
```
when generating getter for `mapping (uint => Transaction) public transactions;`

**Comment by mijovic** [comment]
Works on latest develop.
