### ISSUE TITLE
Replace YulString by plain string

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#10134]
We had the suspicion that the performance gains of YulString are not that big when compared to regular ``std::string``.

I made some experiments, replacing `YulString` by a thin wrapper around ``std::string`` and around ``std::shared_ptr<std::string>>`` - the latter because in existing code e copy `YulString` a lot.

Here are the numbers when running ``time isoltest  --no-smt``:

plain string:

Summary: 4049/4071 tests successful (22 tests skipped).

real	3m13.850s
user	3m13.546s
sys	0m0.229s

shared ptr:

real	3m28.839s
user	3m28.489s
sys	0m0.209s

develop (YulString):

real	2m55.716s
user	2m55.367s
sys	0m0.293s

----

Summary: YulString has a small but measurable benefit.

**Comment by chriseth** [comment]
@ekpyron this might interest you

**Comment by ekpyron** [comment]
Intersting, indeed! It might make sense to measure how much time it spends hashing - fnv is fast and simple, but e.g. xxhash is still faster, sometimes by as much as a factor of 10 supposedly. Well possible that it would not help enough for measurable gains - but it should be quick to check to be sure.

**Comment by chriseth** [comment]
Do you think hashing really takes that much time? I think I remember from the profiler that `operator<` is the function that takes most of the execution time.

**Comment by ekpyron** [comment]
I'm not sure - I wouldn't be surprised if it didn't help, but it might be nice to check - I'm also not sure if hash collisions tend to happen or not - probably not that often (I don't remember if we checked), but if they do xxhash might also help with that, since it avalanches better...

**Comment by chriseth** [comment]
I changed the hash function to operate on full 64 bit chunks, which should reduce the number of multiplications and xor operations. The test run got 10 seconds slower. Maybe we should use a proper profiler...

**Comment by ekpyron** [comment]
For the record: I just quickly tried replacing FNV by xxhash and got no measurable effect. Which is not too surprising - xxhash only becomes really significantly faster for larger inputs (for inputs <5 bytes it's actually slower than FNV, even though it gets faster quickly after that, ref: https://user-images.githubusercontent.com/750081/61976089-aedeab00-af9f-11e9-9239-e5375d6c080f.png).
