### ISSUE TITLE
Super Definition In Solidity Docs Error?

### ISSUE THREAD

**Issue by cjd9s** [ethereum/solidity#10131]
In the inheritance section in Solidity docs, I note the following:
>“It is possible to call functions further up in the inheritance hierarchy internally by … using super.functionName() if you want to call the function one level higher up in the flattened inheritance hierarchy (see below).”

So, if I’m reading this right, it says that super can be used to call a function one level higher up in the inheritance hierarchy. However, it seems to work at least two levels up (see example that I successfully tried in Remix below). Am I reading this wrong, do I not understand the specific order in the directed acyclic graph (DAG) of base contracts, or is Solidity Docs wrong?

```solidity
/* SPDX-License-Identifier: UNLICENSED */

pragma solidity ^0.7.0;

contract SuperGrandparent {
    
    uint public x;

    function setNumber ()
    public
    virtual
    {
        x = 1;
    }
}

contract SuperParent is SuperGrandparent{}

contract SuperChild is SuperParent{
 
    constructor()
    {
    x = 32;
    } 
    
    function setNumber ()
    public
    override
    virtual
    {
        super.setNumber();
    }
}
```

**Comment by hrkrshnn** [comment]
The function `setNumber()` is a member of the contract `SuperParent`, i.e., `SuperParent.setNumber()` is well defined. So there is nothing wrong with the call `super.setNumber()`. The keyword `super` is mainly useful when multiple base classes implement the same function type.
