### ISSUE TITLE
[ewasm] Support loadimmutable/storeimmutable

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10148]
The following code
```solidity
contract C {
  address immutable private owner;
  constructor() {
    owner = msg.sender;
  }
  function getOwner() public returns (address) {
    return owner;
  }
}
```

generates the following issue:
```
[solidity::util::tag_comment*] = Invalid code generated after EVM to wasm translation.
Note that the source locations in the errors below will reference the original, not the translated code.
Translated code:
----------------------------------
[...]
}----------------------------------
:15:9: Error: Function not found.
        setimmutable("2", _1)
        ^----------^
```

**Comment by chriseth** [comment]
This should be possible to implement in principle. One problem I see is the variable-length encoding. Maybe we have to add some nops to add the required padding.

**Comment by axic** [comment]
Actually it is not a problem anymore as leb128 allows padding and wasm doesn't require a canonical shortest encoding anymore. So we can just leave those consts padded. We can also put them as immutable globals and pad the const once.

**Comment by NunoFilipeSantos** [comment]
We're closing all wasm issues for now.
