### ISSUE TITLE
[SMTChecker] Track simple branches better

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10142]
In the following SafeMath code (from zeppelin) the knowledge of the `if (a == 0)` branch is not kept without introducing a `require` statement (commented out):
```solidity
contract SafeMath {
    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
        // benefit is lost if 'b' is also tested.
        // See: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/522
        if (a == 0) {
            return 0;
        }

        // Adding this require statement re-introduces the fact and the code passes.
        // require(a != 0);

        uint256 c = a * b;
        require(c / a == b, "SafeMath: multiplication overflow");

        return c;
    }
}
```

CHC would fail:
```
Warning: CHC: Division by zero happens here.
  --> safemath_mul.sol:14:17:
   |
14 |         require(c / a == b, "SafeMath: multiplication overflow");
   |                 ^^^^^
```

**Comment by leonardoalt** [comment]
Implemented in https://github.com/ethereum/solidity/pull/9543 for CHC and https://github.com/ethereum/solidity/pull/10316 for BMC.

**Comment by axic** [comment]
Does the above example pass then without complaints?

**Comment by blishko** [comment]
SMTChecker verifies that division by 0 *cannot* happen.
But CHC reports an overflow for the expression `uint256 c = a * b;`.

**Comment by leonardoalt** [comment]
This is the case now because we report targets as they're seen. If we run only BMC it will complain about the same.
