### ISSUE TITLE
Replace _ with body in modifiers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1015]
To make the code a bit less cryptic:

```
modifier owneronly {
    if (address != msg.sender) {
        throw;
    }

    body;
}
```

(Follow up of #535)

**Comment by redsquirrel** [comment]
So 'body' will be a keyword?

**Comment by obscuren** [comment]
How about "yield"? It's a common used keyword and generally well understood.

**Comment by chriseth** [comment]
I don't think `yield` matches this use-case. Furthermore, I think we should stay with using a symbol. Admittedly, `_` is not really "visible" (depending on your font), but words do not stand out as well, I would say.

The proper way to do this would be:

```
modifier owneronly[f] {
     if (address != msg.sender) {
        throw;
    }
    f();
}
```

and this also allows us to do

```
modifier owneronly[body] {
     if (address != msg.sender) {
        throw;
    }
    body();
}
```

and `modifier owneronly` would be identical to `modifier owneronly[_]` at which point we could even achieve backwards-compatibility.

(in all cases, the fact whether `()` should or has to be specified is debatable)

**Comment by axic** [comment]
@obscuren I like `yield` but it could mislead into thinking that coroutines are supported.

**Comment by axic** [comment]
@chriseth your proposal is nice, but how many people would actually use it? The default behaviour should reduce the possibility of errors.

**Comment by chriseth** [comment]
@axic we can report a warning if `[]` is not used.

**Comment by VoR0220** [comment]
I still say there's nothing wrong with the `_`.

**Comment by axic** [comment]
> @axic we can report a warning if [] is not used.

I think it could be an acceptable way to go this way. Though we could start issuing a warning for `_` and switch to `body` in the next breaking.

**Comment by VoR0220** [comment]
How would it look with param arguments with modifiers in this proposed schema?

**Comment by axic** [comment]
I would like to revive this discussion.

**Comment by leonardoalt** [comment]
> I don't think `yield` matches this use-case. Furthermore, I think we should stay with using a symbol. Admittedly, `_` is not really "visible" (depending on your font), but words do not stand out as well, I would say.
> 
> The proper way to do this would be:
> 
> ```
> modifier owneronly[f] {
>      if (address != msg.sender) {
>         throw;
>     }
>     f();
> }
> ```

Instead of making the modifier explicitly mention the function, how about the other way around? That is, a modifier states a condition, and the function decides how to use it, for example as a pre or post condition.

```
modifier owneronly {
  require(owner == msg.sender);
}
modifier magic(uint x) {
    require(x == 0xcafe)
}
function f(uint x) pre[[owneronly, magic(x)]] public view {...}
```

This starts to get mixed up with invariants though...

**Comment by chriseth** [comment]
Before we had require, modifiers were used in a very different way. We should collect the current use-cases for modifiers and then maybe restrict the syntax to "pre-conditions, potentially with side-effects" only.

**Comment by leonardoalt** [comment]
Agree!
