### ISSUE TITLE
Turn on SMTChecker by default, but set model-checker-engine to none

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10166]
Discussion prompted by https://github.com/ethereum/solidity/pull/10036#discussion_r507145108.

The proposal here is to remove the `pragma experimental SMTChecker`, but turn it on by default. At the same time set the `model-checker-engine` to `none`, which ultimately means the SMT checker is not run. (But perhaps the AST traversing is conducted, @leonardoalt?)

Since we already have the setting exposed via standard JSON and solc, this step would remove complexity of having the extra pragma.

However one downside it has, that with the pragma it is possible to enable checking per-file.

**Comment by rainbreak** [comment]
@cameel would you then aim to provide a solc-static-linux binary with z3 statically linked?

**Comment by cameel** [comment]
I think we should. But it's not decided yet. Depends on the feedback we receive.

The main reason for not doing it is that it makes the binary almost least 3 times as big as it is now. But we have already added static Z3 to emscripten and macOS builds and in my opinion not having it consistent between platforms is not a good thing.

By the way, looks like the Windows build does not include statically linked Z3 either (though it does not disable it like the Linux one): https://github.com/ethereum/solidity/blob/v0.7.5/.circleci/build_win.ps1#L13

**Comment by cameel** [comment]
I have created a separate issue to discuss the static builds: #10420.

**Comment by axic** [comment]
> However one downside it has, that with the pragma it is possible to enable checking per-file.

@leonardoalt Is this a valid reason to keep the pragma?

**Comment by cameel** [comment]
We could add some kind of filter option where you can specify the files to be checked (or skipped). That would be equivalent to the pragma but without the need to alter the source code.

SMT checker does not affect the bytecode (or does it?), it just provides some extra info for the programmer, so a command-line option seems like a better mechanism to me.

**Comment by leonardoalt** [comment]
Call decision:

If `pragma experimental SMTChecker;` is used:
  - targets in files that do not have the pragma should also be checked
  - issue a deprecation warning
  - use default engine and targets = all

If pragma not used:
  - default engine = none
  - all files should be checked
