### ISSUE TITLE
Out of storage slots should be an error

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#10160]
## Description

Creating a contract that uses too much storage creates undefined behavior and should be disallowed.

## Environment

- Compiler version: 7.0.4

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: MIT
pragma solidity >=0.7.0;
pragma experimental ABIEncoderV2; // Required for Diamond Standard

contract Bursting {
    uint[2^256] public mammoth;
    uint public flea;
}

contract Bursting2 {
    uint[2^255] public mammoth;
    uint[2^255] public mammoth2;
    uint[2^255] public mammoth3;
    uint public flea;
}

contract Bursting3 {
    uint[2^257] public mammoth;
}
```

## Discussion

Each of these must certainly be an error.

## Follow on work

Also, I think it is a good idea to mark any fixed-length array with length > 2^128 as a warning. That attack is well-known and easy for the compiler to detect.

**Comment by axic** [comment]
There are already warnings for these. I think you came across this annoying thing that `^` means XOR and `**` means raising to the power in Solidity :wink:

I think your examples should trigger the warning with e.g. `2**257`.

**Comment by fulldecent** [comment]
Whupps, my bad on that! :-p

Thanks for the fix.
