### ISSUE TITLE
Extra bytes returned on revert("")

### ISSUE THREAD

**Issue by ZumZoom** [ethereum/solidity#10170]
## Description

Calling `revert(string)` should return abi-encoded string as if it were a call to `Error(string)` function ([docs](https://solidity.readthedocs.io/en/latest/control-structures.html#revert)).

Therefore when calling revert with empty string `revert("")` I expect to receive correct abi-encoded `Error("")`: 
```
0x08c379a0                                                          <- Error(string) selector
0000000000000000000000000000000000000000000000000000000000000020    <- string offset = 32
0000000000000000000000000000000000000000000000000000000000000000    <- string length = 0
```

In fact Solidity appends extra 32 bytes of zeroes in that case so returned bytes are
```
0x08c379a0                                                          <- Error(string) selector
0000000000000000000000000000000000000000000000000000000000000020    <- string offset = 32
0000000000000000000000000000000000000000000000000000000000000000    <- string length = 0
0000000000000000000000000000000000000000000000000000000000000000    <- unexpected extra 32 bytes
```

## Environment

- Compiler version: 0.6.12, 0.7.4
- Target EVM version: compiler default (Istanbul)
- Framework/IDE: Remix
- EVM: mainnet, ropsten, ganache-cli, ethereumjs-vm

## Steps to Reproduce

```solidity
contract RevertReasonParserTest {
    function emptyStringRevert() external pure  {
        revert("");
    }

    function test() external view returns(bytes memory, uint256) {
        try this.emptyStringRevert() {
        } catch (bytes memory reason) {
            return (reason, reason.length);
        }
    }
}
```

[Ropsten example](https://ropsten.etherscan.io/address/0xfdd9aa7ae91e966ae3d8aa708d5fe42f82ab746c)

[Mainnet example](https://etherscan.io/address/0x3a428d3ca52251fa40e4841e4556e13481893b83)

**Comment by axic** [comment]
As mentioned in https://github.com/trufflesuite/ganache-cli/issues/800#issuecomment-720129628 this is confirmed to be happening.

Tried adding a test for it, but we have another bug in `soltest`/`isoltest`:
```solidity
contract C {
        function f() public {
                revert(""); 
        }
}
// ====
// EVMVersion: >=byzantium
// compileViaYul: also
// revertStrings: debug
// ----
// f() -> FAILURE, hex"08c379a0", 0x20, 0, ""
```

The `""` field is not recognized and is replaced with `"string"`, but that doesn't matches the value 😬

**Comment by ZumZoom** [comment]
Also just found out that contract compiled with `pragma experimental ABIEncoderV2;` behaves correctly.

[Ropsten example](https://ropsten.etherscan.io/address/0x4e6dbc0f3e7f0f256bef092bd45ca661dd8ffcdd)
