### ISSUE TITLE
[yul] Support special/priority objects in object format

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10179]
The "contract metadata" is expected to be the trailing bytes in the bytecode.

While the Yul object format allows for code and data sections, there is no clarity whether those sections must be laid out the same order in the binary as they were defined in the text format, and in fact, the implementation considers the objects in a hashmap so their order depends on their names.

In order to support metadata (at least in the EVM output), we have a couple of options:
a) Introduce defined ordering
b) Consider a special field as the last (such as `metadata` or `contractMetadata`)
c) Introduce a new field for metadata in the object format
d) Introduce a special call in the implementation to set the metadata (outside of the object format)

And perhaps other options.

Part of #10152.

**Comment by chriseth** [comment]
subObjects is actually a vector, so the order is retained. Unless the assembler re-arranges them, defining the metadata to be last should "just work".

**Comment by axic** [comment]
You're right it is a vector in the AST, but the assemblers may do their own thing. However under "Introduce defined ordering" I also mean to explicitly state that for the text representation of Yul so that an IR file can be compiled correctly.

**Comment by axic** [comment]
@ekpyron any opinion on this one?

**Comment by ekpyron** [comment]
I'd not give the order in the sources a special meaning - I'd consider the yul object files like a generic object file format like an ELF object that just defines some section - what we're doing when compiling to bytecode is basically creating something like an old ``COM`` binary, which does have a fixed internal layout, but I'd say making sure that's the way it's supposed to is the job of the assembler/linker in the end. We should have the compiler output the layout of yul objects in the bytecode, though, if requested.

In general I don't think the metadata should be defined as data parts in the yul objects at all. Similarly to the "section order" thing, I'd say this is something specific to the EVM bytecode format that's independent of Yul and job of the linker only.

But I only thought about it for 5 minutes, so don't put too much weight on what I just said :-).

**Comment by chriseth** [comment]
Putting this up for discussion for tomorrow.

**Comment by axic** [comment]
> I'd not give the order in the sources a special meaning - I'd consider the yul object files like a generic object file format like an ELF object that just defines some section - what we're doing when compiling to bytecode is basically creating something like an old COM binary, which does have a fixed internal layout, but I'd say making sure that's the way it's supposed to is the job of the assembler/linker in the end. We should have the compiler output the layout of yul objects in the bytecode, though, if requested.

I agree Yul object format is pretty similar to ELF (and WebAssembly) in intent and purposes. I disagree with your assessment though, given ELF specifically has metadata sections, which are demarcated properly (prefixed with `.` mostly).

> In general I don't think the metadata should be defined as data parts in the yul objects at all. Similarly to the "section order" thing, I'd say this is something specific to the EVM bytecode format that's independent of Yul and job of the linker only.

This may have its merit, but it seems that metadata is a bit more closely coupled currently.

On today's call we have agreed to go with something like `@metadata` or `.metadata` as the object name, but also place the metadata as the last.
