### ISSUE TITLE
ICE in convertType() when calling functions bound to structs and arrays with calldata parameters

### ISSUE THREAD

**Issue by gitpusha** [ethereum/solidity#10186]
Env: `hardhat`
Compiler: `0.7.4` 

Try to compile this code with `0.7.4` . 

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.7.4;
pragma experimental ABIEncoderV2;

struct Task {
    address[] actions;
}

struct TaskReceipt {
    uint256 index;
    Task[] tasks;
}

library GelatoTaskReceipt {
    function task(TaskReceipt calldata _taskReceipt)
        internal
        pure
        returns (Task memory)
    {
        return _taskReceipt.tasks[_taskReceipt.index];
    }
}

contract Example {
    using GelatoTaskReceipt for TaskReceipt;

    function exec(TaskReceipt calldata _taskReceipt) external pure {
        for (uint256 i = 0; i < _taskReceipt.task().actions.length; i++) {}
    }
}
```

Accessing fields on the `Task memory` returned from `GelatoTaskReceipt.task` seems to be the issue.

```solidity
for (uint256 i = 0; i < _taskReceipt.task().actions.length; i++) {}
```

`InternalCompilerError: Internal compiler error (/Users/distiller/project/libsolidity/codegen/CompilerUtils.cpp:1057)`

The problem seems to go away if you use `memory` data location instead.

In a previous compiler version (e.g. **0.6.12**) using `calldata` for the same code did **compile** **without** **error** by the way.

**Comment by gitpusha** [comment]
The problem seems to go away if you use `memory` data location instead. 

In a previous compiler version (e.g. `0.6.12`) using `calldata` for the same code did compile with error by the way.

**Comment by chriseth** [comment]
The bound function seems to be the issue.

**Comment by gitpusha** [comment]
> The bound function seems to be the issue.

`bound` function and `calldata`. This might be unrelated but I reported a different bug for solc `0.6.9` that also had to do with bound function and `calldata` before: https://github.com/ethereum/solidity/issues/9172

**Comment by cameel** [comment]
Yeah, looks like it's both. Below is the smallest repro I could find. It stops happening if I change the location to `memory`, remove `using` or use a type different than a struct.

It works in 0.6.9. In all the later versions it triggers an ICE.

```solidity
pragma experimental ABIEncoderV2;

struct S {
    uint x;
}

library L {
    function f(S calldata) internal pure {}
}

contract C {
    using L for S;

    function run(S calldata _s) external pure {
        _s.f();
    }
}
```
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/CompilerUtils.cpp(1055): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type&, const solidity::frontend::Type&, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

Using an array (either static or dynamic, but not `string` or `bytes`) triggers a different assertion in the same function. This also started happening in 0.6.10.
```solidity
pragma experimental ABIEncoderV2;

library L {
    function f(uint[1] calldata) internal pure {}
}

contract C {
    using L for uint[1];

    function run(uint[1] calldata _s) external pure {
        _s.f();
    }
}
```
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/CompilerUtils.cpp(1024): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type&, const solidity::frontend::Type&, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Invalid conversion to calldata type.
[solidity::util::tag_comment*] = Invalid conversion to calldata type.
```

The example from the issue description works on 0.6.8 and fails in the same way since 0.6.10. On 0.6.9 it triggers `UnimplementedFeatureError` because the struct contains a dynamic array.

**Comment by cameel** [comment]
@chriseth I investigated it and the direct cause of the ICE is that it goes into the `calldata` -> `calldata` conversion branches for structs and arrays in `convertType()` and these branches are forbidden with an assertion. I have created semantic tests cases for the repro above and just removing the assertion makes them pass and produce correct values.

But I suspect that just removing it is not the right solution. After all the ICE does not happen for an equivalent non-bound call. The difference between these two cases is that the non-bound call runs `convertType()` on arguments with `_cleanupNeeded = false` and `convertType()` short-circuits on this condition:
```c++
	if (_typeOnStack == _targetType && !_cleanupNeeded)
		return;
```
For bound calls, `convertType()` gets `_cleanupNeeded = true` so the condition fails and the function continues past it.

So the question is - is `_cleanupNeeded = true` for the bound parameter a bug? Or is there actually something going on with the bound parameter that does require cleanup?

**Comment by chriseth** [comment]
You mean cleanup is forced for the self type? I think it's totally fine to change the assertion to not fail if the types are the same. Can you give a pointer to where `_cleanupNeeded = true` is set? I would assume it mostly does not matter.

**Comment by cameel** [comment]
It's in `ExpressionCompiler::visit(MemberAccess)`:

https://github.com/ethereum/solidity/blob/44493ad42813f700cbee3cfd5389be105ff3e5d9/libsolidity/codegen/ExpressionCompiler.cpp#L1315-L1317

The last argument is `_cleanupNeeded`.

**Comment by chriseth** [comment]
I don't know why cleanup is forced here, but I think converting calldata values from one type to the same type and forcing cleanup should be supported by codegen.
