### ISSUE TITLE
Access to bytes type from inline assembly to have .offset/.size

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10184]
Similar to storage offset/slot and the proposed calldata offset/slot (#8917) it would be nice to have `.offset` and `.size` properties.

While `.offset` is easily replaced with `add(b, 32)` and `.size` with `mload(b)`, it could be nice to follow the same logic as for storage/calldata.

**Comment by chriseth** [comment]
I don't think this is a good idea. We should expose as little as needed.
