### ISSUE TITLE
[isoltest] Change isoltest to execute tests with each valid evmVersion unless specified

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10191]
Currently isoltest only runs with the latest evmVersion and would ignore a given file if the version rule specified within rejects it.

I think it would make life much easier if isoltest would execute tests with each valid evmVersion which satisfies the optionally present rule.  If however the `--evm-version` argument is present that overrides the selection and only runs it for that version.

**Comment by chriseth** [comment]
Can you describe what the use-case would be? How would you use the feature when run locally and how would you use it when run in CI?

**Comment by axic** [comment]
You would use the same way both locally and on CI: `isoltest`. It runs each file for every evm version (adhering to the `evmVersion:` rules in the files). That's it. Could also extend to do it with optim vs no-optim, unless a setting is specified on cli.

**Comment by cameel** [comment]
Maybe something like `--evm-version all`? It could also be the default.

**Comment by axic** [comment]
I think the main difference compared to today would be that the different version/optim configurations are run in succession on each file as opposed to rerunning the entire tool with each config.

**Comment by cameel** [comment]
I think we should implement this. Especially for the `--optimize` option. Currently you have to run isoltest twice (with and without the option) to fully update the gas costs. It would be much more convenient if you could do it in one run.

It might also let us parallelize soltest better. Currently we manually split it into runs with various options in `soltest_all.sh`. The split is not even and we also cannot easily be more granular than one full run. There was an idea to be able to tell it to split tests into N batches and tell it to run i-th batch (#12388). The split would be more uniform if we could have just one call with all option combinations and let it freely distribute the cases among batches.

**Comment by cameel** [comment]
By the way, if we do this, we will actually need some way not to rerun specific tests on multiple EVM versions For example there's no point in re-running the `@nooptions` tests on every EVM.
