### ISSUE TITLE
[ewasm] Change dataoffset/datasize to return i32

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10243]
Currently `dataoffset`/`datasize` return i64, however the wasm memory model is 32-bit currently and the Ewasm `codecopy`/`extcodecopy`/etc host functions also deal with 32-bits.

**Comment by chriseth** [comment]
Please do it!

**Comment by ShakaibKhan** [comment]
If no one else minds I would like to try making a PR to address this

**Comment by cameel** [comment]
Are you looking for an issue to work on or are you specifically interested in fixing this because you want to use the ewasm target?

**Comment by ShakaibKhan** [comment]
more so looking for an issue to work on (not necessarily the ewasm target) but asked for this issue as it is labeled g.f.i.

**Comment by cameel** [comment]
We're currently not actively working on the ewasm backend so if you want to contribute, I'd recommend a different issue. Here are some suggestions:
- https://github.com/ethereum/solidity/issues/9601
- https://github.com/ethereum/solidity/issues/9627
- https://github.com/ethereum/solidity/issues/10210
- https://github.com/ethereum/solidity/issues/12244
- https://github.com/ethereum/solidity/issues/10812
