### ISSUE TITLE
formal verification: support mapping as a state variable

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1025]
This issue keeps track of implementing the Why3 translation of state variables that are mappings.

```
$ cat token.sol 
contract Token
{
        mapping (address => uint256) balance;
}
$ ../../solidity/build-develop/solc/solc token.sol --formal
token.sol:1:1: Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.3.6;".
contract Token
^
Spanning multiple lines.
token.sol:3:2: Error: Type not supported for state variable.
        mapping (address => uint256) balance;
        ^----------------------------------^
```

**Comment by pirapira** [comment]
I choose

```
mutable balance: array uint256
```

as the translation for the above example.  As long as the key of the mapping is an unsigned, array is a good translation.

**Comment by pirapira** [comment]
Actually array indices can be negative in Why3, so as long as the key is an `IntegerType`, `array` is a sound translation.

**Comment by pirapira** [comment]
Mappings to mappings will be dealt with in #1053.

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
