### ISSUE TITLE
[TypeChecker] Null dereference during explicit cast of hex literal to address type

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10257]
## Description

```
function t() pure {
        address(0x11223345567aaaaaaaaaaaaaaaaaaaaaaaaaaaaa0112233445566778899001122);
}
```

dereferences a nullptr here

https://github.com/ethereum/solidity/blob/141277dadfe4a75e250fd2abfed89d98fb694d4a/libsolidity/ast/Types.cpp#L976

in the call to `integerType()->numBits()` because `integerType()` returns a nullptr.

## Environment

- Compiler version: latest breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
Closed by https://github.com/ethereum/solidity/pull/10582
