### ISSUE TITLE
[Typechecker] Bad cast during negation of fixed point type variable in contract function

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10256]
## Description

```
contract C {
        function f() public pure {
                fixed x;
                -x;
        }
}
```

throws a `std::bad_cast` here

https://github.com/ethereum/solidity/blob/141277dadfe4a75e250fd2abfed89d98fb694d4a/libsolidity/codegen/YulUtilFunctions.cpp#L3401

because `fixed` and `integer` types are unrelated by inheritance. Surprisingly, free functions do not demonstrate this bug e.g., `function f() pure { fixed x; -x; }`

## Environment

- Compiler version: latest breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by axic** [comment]
Still happening on breaking.
