### ISSUE TITLE
notion of constant expression should include immutable

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/solidity#10261]
On solidity 0.7.1, I get

```
 TypeError: Invalid array length, expected integer literal or constant expression.
        ExchangeRate[sized][] memory matrix = new ExchangeRate[][](size_used);
```
where sized defined as `uint256 immutable sized` 

so it seems that something around here in `DeclarationTypeChecker.cpp` could be more accommodating of immutable based expressions. 

```cpp
	solAssert(baseType->storageBytes() != 0, "Illegal base type of storage size zero for array.");
	if (Expression const* length = _typeName.length())
	{
		TypePointer& lengthTypeGeneric = length->annotation().type;

		if (!lengthTypeGeneric)
			lengthTypeGeneric = ConstantEvaluator(m_errorReporter).evaluate(*length);
		RationalNumberType const* lengthType = dynamic_cast<RationalNumberType const*>(lengthTypeGeneric);
		u256 lengthValue = 0;
		if (!lengthType || !lengthType->mobileType())
			m_errorReporter.typeError(
				5462_error,
				length->location(),
				"Invalid array length, expected integer literal or constant expression."
			);
```

**Comment by chriseth** [comment]
The value of an immutable variable is (in general) a runtime value. You cannot generate code for statically-sized arrays whose length depends on a runtime value:
```
contract c {
  uint immutable x = block.timestamp;
  uint[x] data;
}
```

Is it really a runtime variable for you or can you just as well use `constant`?

**Comment by fxfactorial** [comment]
How is it runtime? as I understood - the immutable are placed in right after constructor args - or its runtime wrt what the compiler can do at that moment ?

**Comment by fxfactorial** [comment]
ah - just reread your code example - makes sense now
