### ISSUE TITLE
formal verification: support explicit fallback functions

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1026]
Currently `solc --formal` on

```
contract C
{
        uint256 balance;
        function () {}
}
```

yields an error message
`Error: Fallback functions not supported.`

This issue keeps track of enabling the Why3 translation of explicit fallback functions (fallback functions exist by default but that is treated in a separate issue).

**Comment by chriseth** [comment]
Note that the behaviour changes with version 0.4.0: No fallback function means the call is reverted.

**Comment by pirapira** [comment]
That sounds safer.

**Comment by pirapira** [comment]
(... or maybe not, we'll see)

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
