### ISSUE TITLE
[Docs] Add goals and design rationale of Solidity to intro section of the docs

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#10260]
It would be nice to have a general goals and high level design rationale section in the introductory section of the Solidity docs.

### Examples

Something around the lines of: 
- This [C++ FAQ section](https://isocpp.org/wiki/faq/big-picture#what-is-cpp)
- This [Rust doc introduction](https://doc.rust-lang.org/book/ch00-00-introduction.html#who-rust-is-for)
- This general introduction in the [Go documentation](https://golang.org/doc/)

**Comment by KishkinJ10** [comment]
i am a beginner can i work on this please?

**Comment by KishkinJ10** [comment]
can you tell me where this file is located , is it in the docs folder in grammar section??

**Comment by franzihei** [comment]
Hi @KishkinJ10, Thank you for offering your help! Please note that in order to write this section you would have to be familiar with Solidity and be able to crisply and precisely define what Solidity is about (the high level design rationale and goals of the language). If you feel like to have enough knowledge to do that, feel free to give it a shot. My assumption is that this issue would be easier solvable by a Solidity core team member.

It might make sense for you to check issues that are marked with ``good first issue`` to get started. :)

With regards to your question, the additional text should go into the intro section of the docs (that's the `index` file of the docs folder).

**Comment by KishkinJ10** [comment]
Thank You sir :)

**Comment by franzihei** [comment]
Adding a bit more context to this section. I think it would be nice to cover the following aspects in the intro section of the docs:

**1. What is Solidity?** 
```
Solidity is an object-oriented, high-level language for implementing smart contracts. Smart contracts are programs which govern the behaviour of accounts within the Ethereum state.

Solidity is a curly-bracket language. It is influenced by C++, Python and JavaScript, and is designed to target the Ethereum Virtual Machine (EVM). You can find more details about which languages Solidity has been inspired by in the language influences section.

Solidity is statically typed, supports inheritance, libraries and complex user-defined types among other features.
```
**2. Why Solidity?**

Here we should list aspects that make Solidity a great language.

**3.  _[optional]_ Who/what is Solidity for?**

Here we could list who the target group for using Solidity is and what you can do with it.

Stuff that would already fit in this section:

```
With Solidity you can create contracts for uses such as voting, crowdfunding, blind auctions,
and multi-signature wallets.
```

**4. Which design principles are followed/considered when developing Solidity language?**

Here we could briefly list which aspects are most important to us when we do language design and prioritise them.
