### ISSUE TITLE
[CLI] Add an option which considers warnings as errors (and aborts accordingly)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10277]
This was brought up in https://github.com/ethereum/solc-js/issues/169

**Comment by cameel** [comment]
On the call today we decided to move this to the Icebox for now. It was requested but it could open a whole can of worms so we don't want to do it right now but we'll consider it if there's more demand.

**Comment by fkirc** [comment]
I would like to add my support for this feature.
My problem with raw warnings is that they are not really actionable in an automated way.
Either I want to selectively ignore a warning, or I want to fix a warning.
To do so, warnings as errors would be a helpful cornerstone.

**Comment by cameel** [comment]
@fkirc  Are you using a framework, IDE or just the compiler directly?

**Comment by fkirc** [comment]
I am using Truffle, but I believe that this would be a good flag for the compiler directly.

**Comment by ekpyron** [comment]
I don't see us doing this in the compiler - and frameworks are free to consider our warnings as errors. So I'm closing this as part of our issue maintenance pass. Feel free to reopen, if you disagree.
