### ISSUE TITLE
formal verification: include implicit fallback function in Why3 output

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1027]
Currently, the output of `solc --formal` does not contain any code for the implicit default fallback function.

This issue keeps track of adding the implicit default fallback function to the Why3 translation, when there are no explicit fallback functions.
- [ ] determine the EVM code for the default fallback function
- [ ] determine the Solidity documentation that specifies the default fallback function
- [ ] implementing the Why3 translation

**Comment by chriseth** [comment]
Note that the behaviour changes with version 0.4.0: No fallback function means the call is reverted, so I think this story is not needed.

**Comment by pirapira** [comment]
OK.  Then I close it.
