### ISSUE TITLE
[CLI] Expose all settings present in standard-json to the cli

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10274]
(This issue is splitting up #8847.)

> Some options available to the standard-json format do not seem to be available as CLI flags. I'm missing in particular source mappings for yul which was introduced only for the json options in #8378. It would be nice if feature parity between CLI flags and json opts was pursued as a general rule.

**Comment by cameel** [comment]
CLI has no equivalent for `evm.bytecode.linkReferences` and `evm.deployedBytecode.immutableReferences` outputs from Standard JSON.

**Comment by cameel** [comment]
Another thing are all the outputs available in assembly mode in Standard JSON. #12074 allows selecting outputs in assembly mode but does not add anything beyond what compiler was already printing.

**Comment by cameel** [comment]
I think this is something we still want to (or at least should) do. Reopening.

**Comment by ekpyron** [comment]
This is an obvious part of rewriting CLI backed by standard-json. Do we really need a separate issue for this? We won't do it before that and without that - and with that, we can do it right away...

**Comment by cameel** [comment]
I'm not sure it's an obvious part. You could very well rewrite it keeping the features it has currently without adding parity.

**Comment by ekpyron** [comment]
We'll achieve parity by just allowing the CLI to generically amend the standard-json it generates while deprecating. It's part of the rewrite, I'm closing this :-).
