### ISSUE TITLE
[Docs] Unclear description of valid struct initialization on previous solidity versions

### ISSUE THREAD

**Issue by Jaime-Iglesias** [ethereum/solidity#10284]
Going through the docs, particulary the struct [section](https://solidity.readthedocs.io/en/v0.7.4/types.html#structs),  there's this particular code snippet:

```solidity
    function newCampaign(address payable beneficiary, uint goal) public returns (uint campaignID) {
        campaignID = numCampaigns++; // campaignID is return variable
        // We cannot use "campaigns[campaignID] = Campaign(beneficiary, goal, 0, 0)"
        // because the RHS creates a memory-struct "Campaign" that contains a mapping.
        Campaign storage c = campaigns[campaignID];
        c.beneficiary = beneficiary;
        c.fundingGoal = goal;
    }
```

This snippet, **in my interpretation**, hints that a struct cannot be created in-memory if the struct type contains a mapping. This seems reasonable since the next section of the docs, [mapping types](https://solidity.readthedocs.io/en/v0.7.4/types.html#mapping-types),  explictly says that the only data location available for mappings is storage - So basically, adding these two pieces together, I think it's reasonable  for the reader to jump to the following conclusion "It's not possible to initialize an struct in-memory if the struct type has a mapping" and the reader could also jump into the conclusion that "A struct can only be in-memory if all it's underlying member types are allowed to be in-memory".

So far, I think the docs make this very clear.

My problem is that there is multiple version of solidity and we can see code in production in many of those versions. I think that, usually, the docs make an extra effort to add notes (which I find very helpful) so the reader is aware of some things that were allowed in the past and are no longer allowed, like seen in the array members [section](https://solidity.readthedocs.io/en/v0.7.4/types.html#array-members).

So, getting to the point, I think that adding a **note** to the section explaining that the compiler, in previous versions, omitted the types that were not valid outside of storage to allow in-memory intialization, would be great addition to make seeing old code less confusing; because the following code is valid in `0.6` and `0.5` and IMHO can lead to confusion when reading the latest docs.

```solidity
contract Test {
    struct Foo {
        uint256 a;
        mapping(uint => address) b;
    }
    
    Foo public foo;
    
    function createFoo() external {
        Foo memory newFoo = Foo({ a: 1 });
        
        foo = newFoo;
    }
}
```

Apologies if this is not the correct venue to raise this question/problem.

**Comment by cszcli** [comment]
Hi Jamie,

Your conclusion is great! But I have a question about the sentence "because the RHS creates a memory-struct".
Would you please tell me what is RHS short for?

Best Regards!

**Comment by Jaime-Iglesias** [comment]
> Hi Jamie,
> 
> Your conclusion is great! But I have a question about the sentence "because the RHS creates a memory-struct".
> Would you please tell me what is RHS short for?
> 
> Best Regards!

Hey, I think the docs mean "Right Hand Side" As in referring to the right part of the statement `campaigns[campaignID] = Campaign(beneficiary, goal, 0, 0)` i.e They are saying that `Campaign(beneficiary, goal, 0, 0)` is creating a struct in-memory.

This is my interpretation though, maybe RHS is short for something else (hard to tell).

**Comment by cszcli** [comment]
Hi Jamie,

I think that's correct. Thanks very much for your help!

Best Regards!

**Comment by cameel** [comment]
> This is my interpretation though, maybe RHS is short for something else (hard to tell).

Yes. that's exactly what it means. "right hand side" and "left hand side" are used a lot in some contexts so RHS and LHS are common shortcuts. But I see that it's used only once on that page. I think it would be fine expand it to avoid confusing people unfamiliar with it.

> I think that, usually, the docs make an extra effort to add notes (which I find very helpful) so the reader is aware of some things that were allowed in the past and are no longer allowed

I agree. It would be a useful piece of information here.

@Jaime-Iglesias Would you like to submit a PR with that change? Good contributions to the docs are always welcome even if they're just small tweaks.

**Comment by Jaime-Iglesias** [comment]
> @Jaime-Iglesias Would you like to submit a PR with that change? Good contributions to the docs are always welcome even if they're just small tweaks.

@cameel Sure, I think I will have some spare time this weekend - Is there any sort of "guide" that I should take a look before contributing ? Like, how the docs are generated, etc...

**Comment by cameel** [comment]
@Jaime-Iglesias Great! There's a [short style guide in the docs](https://docs.soliditylang.org/en/latest/contributing.html#documentation-style-guide).

To build/re-build it you just run `scripts/docs.sh`. You of course need to check out a copy of the repo and it might be a good idea to create a virtualenv for the libraries if you don't want to install them globally. Here's a snippet I'm usually using to build it myself (on Linux):
```bash
git clone git@github.com:ethereum/solidity.git
cd solidity/

python -m venv /tmp/solidity-docs-virtualenv/
source /tmp/solidity-docs-virtualenv/bin/activate

scripts/docs.sh
xdg-open docs/_build/html/index.html
```
This assumes you have Python 3 and git installed in your system.

After changing anything, you just need to rerun the `scripts/docs.sh` command to see the rendered changes.

The markup used in the docs [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html).
