### ISSUE TITLE
Replace custom shellcheck script with CircleCI shellcheck orb

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10280]
This was previously attempted in #9448.

```shell
git ls-files '*.sh' | xargs shellcheck
```

It lists a lot of issues, even a bunch of unused variables or misused things, but most of the warnings are for not quoting things.

**Comment by cameel** [comment]
Shellcheck is already hooked up into the CI (#8558). I think you specifically mean the CircleCI shellcheck orb?

**Comment by axic** [comment]
Now, it was meant for shellcheck itself. At the time I created this issue I ran it on Solidity and it showed all the issues you have been fixing with the recent PRs.

It seems that #8558 indeed was merged, but it has a very long ignore list, so I reckon it did not do much in the first place.
