### ISSUE TITLE
[CLI] Unqualified library name in --libraries option matches any qualified link reference with the same library name

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10298]
As reported in #10290, `LinkerObject` contains a [workaround for old-style link references in `LinkerObject`](https://github.com/ethereum/solidity/blob/v0.7.4/libevmasm/LinkerObject.cpp#L78-L85) that strips file names from the link references found in the code if an exact match does not work.

The consequence is that omitting the file name in library identifiers passed to the linker (e.g. `--library Log:0x123...`) results in the library file names being completely ignored. The same address will be used not only for bare `Log` without file name but also e.g. for `math.sol:Log` and `error.sol:Log`.

### Steps to reproduce
`math.sol`:
```solidity
library Log {
    function log10() external {}
}
```

`error.sol`:
```solidity
library Log {
    function print() external {}
}
```

`contract1.sol`:
```solidity
import "error.sol";

contract C {
    function foo() public {
        Log.print();
    }
}
```

`contract2.sol`:
```solidity
import "math.sol";

contract C {
    function foo() public {
        Log.log10();
    }
}
```
```
solc contract1.sol contract2.sol --libraries "Log:0x7777777777777777777777777777777777777777" --bin
```

Output
```
======= contract1.sol:C =======
Binary:
608060405234801561001057600080fd5b5060c78061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063c298557814602d575b600080fd5b60336035565b005b7377777777777777777777777777777777777777776313bdfacd6040518163ffffffff1660e01b815260040160006040518083038186803b158015607857600080fd5b505af4158015608b573d6000803e3d6000fd5b5050505056fea2646970667358221220c0280f7ef9d1b2ba1184ec8e799afc473ea8df12e2b9e204ea4785cfdfade0d064736f6c63430007040033

======= contract2.sol:C =======
Binary:
608060405234801561001057600080fd5b5060c78061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063c298557814602d575b600080fd5b60336035565b005b73777777777777777777777777777777777777777763452348166040518163ffffffff1660e01b815260040160006040518083038186803b158015607857600080fd5b505af4158015608b573d6000803e3d6000fd5b5050505056fea2646970667358221220d135b215d67b4d4fbfaf7676035f21cbd1f121e1fdac65f267663e51e10cce4764736f6c63430007040033

======= error.sol:Log =======
Binary:
6084610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806313bdfacd146038575b600080fd5b818015604357600080fd5b50604a604c565b005b56fea264697066735822122059c366c03fc74e5ecfb1420b581cd2dc6fd828f60e3b226ed273c9bbf49952ad64736f6c63430007040033

======= math.sol:Log =======
Binary:
6084610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806345234816146038575b600080fd5b818015604357600080fd5b50604a604c565b005b56fea26469706673582212206f5b0dd0a8ba813f39f4879e5e8b73ce5d62afb1e8e597a3a28afd42e713cca364736f6c63430007040033
```

Both references were resolved to address `0x7777777777777777777777777777777777777777` without the compiler complaining about it even though they are supposed to be different libraries.

**Comment by cameel** [comment]
The fix is simply to remove the offending lines. The problem is that this makes a lot of tests fail because they tend to omit the library file name. Fixing that will be tedious.

**Comment by leonardoalt** [comment]
That sounds rather serious, doesn't it?

**Comment by cameel** [comment]
Maybe? I don't think it's even documented that you can do that. The docs say you have to use `--libraries file.sol:L` and in that case the problem won't happen. But yeah, skipping the file name is an easy mistake to make so it's not a reason not to fix it :)

#10290 more serious because there's no workaround.

**Comment by soroosh-sdi** [comment]
this is a bug, so it is more important than others you suggested.
please assign this issue to me. @cameel
