### ISSUE TITLE
[Codegen] ICE in ContractCompiler::appendModifierOrFunctionCode

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10303]
## Description

```
contract C{modifier m{_;}function f()public C.m{} }
```

throws

https://github.com/ethereum/solidity/blob/14ed67ac4bdfa540c405fc292c2b2293bca51fdf/libsolidity/codegen/ContractCompiler.cpp#L1304

## Environment

- Compiler version: latest breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/10307
