### ISSUE TITLE
[CLI] Replace colon with equal sign for --libraries

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10305]
_Originally posted in https://github.com/ethereum/solidity/pull/10292#discussion_r524202385_

```
Linker Mode Options:
  --libraries libs     Direct string or file containing library addresses. 
                       Syntax: <libraryName>:<address> [, or whitespace] ...
                       Address is interpreted as a hex string optionally 
                       prefixed by 0x.
```

Currently the libraries option separates library name and address with a colon. However library name contains a colon too to separate the filename from the library name.

I think it would make sense to replace that colon separating the address with an equal sign, such that we would be using it as:
```
--libraries library1.sol:L1=0x1234...
```

Since we are making a few changes in 0.8.0 already it may be a good time to do this.

**Comment by axic** [comment]
> Address is interpreted as a hex string optionally prefixed by 0x

I would also propose making this more strict and only allowing `0x` prefixed addresses.

**Comment by ityuhui** [comment]
May I take this ticket ?

**Comment by cameel** [comment]
Sure.

**Comment by ityuhui** [comment]
This ticket is implemented by the PR https://github.com/ethereum/solidity/pull/10707.

I think it can be closed and removed the label of "breaking change".

**Comment by chriseth** [comment]
Thanks!
