### ISSUE TITLE
formal verification: constructors should establish invariants even from a state without the invariant

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1030]
Currently, the `--formal` output assumes that the invariants hold even before the constructor runs.  This does not match the reality.  This issue keeps track of changing the Why3 output so that the constructor is just expected to establish the invariants as postconditions.

Example `initialization.sol`

```
/// @why3 invariant { to_int this.storage.balance = 150 }
contract C
{
        uint256 balance;

        function C()
        {
                balance = 150;
        }
}
```

`solc --formal initialization.sol` yields a long output containing

```
        let rec _C (this: account):
                        ()
                invariant { to_int this.storage.balance = 150 }
                writes { this }
                =
```

where the `invariant` clause states that whenever the constructor starts when the invariant holds, the constructor leaves the state where the invariant holds.

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
