### ISSUE TITLE
[CLI] Rewrite solc --link to use LinkerObject

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10308]
Extracted from https://github.com/ethereum/solidity/pull/10297#discussion_r524260360:

@axic
> Why do we have this messy code here and why isn't this part of `LinkerObject`? Also `solc-js` has this messy code duplicated.

> I would prefer a clear way of adding a `LinkerObject::parse(bytes)` feature and unit testing, and using `LinkerObject::parse(bin).link(addresses)` in the cli.

> You can take inspiration from https://github.com/ethereum/solc-js/blob/master/linker.js (see `findLinkReferences`).

**Comment by Uttam-Singhh** [comment]
Is this issue solved or I can work on it??

**Comment by cameel** [comment]
No, no one is working on it right now so if you want to try, feel free :)

**Comment by Uttam-Singhh** [comment]
Hey, @cameel I am new to this.
It would be great if you can guide me on how to get started and what I exactly have to do!

**Comment by cameel** [comment]
Great! Not sure how familiar you are with linking and library addresses in Solidity. If it's a new topic for you, I'd suggest to start by reading the [Library Linking](https://docs.soliditylang.org/en/latest/using-the-compiler.html#library-linking) section and the chapter on [Libraries](https://docs.soliditylang.org/en/latest/contracts.html#libraries) in the docs.

Here's a general rundown of everything you need for this particular task:
- First, to get an idea what this is all about, try to compile a contract that uses a library and see the resulting bytecode. For example
    ```bash
    solc test/libsolidity/semanticTests/libraries/stub.sol --bin
    ```
    ```
    ======= test/libsolidity/semanticTests/libraries/stub.sol:C =======
    Binary:
    608060405234801561001057600080fd5b50610217806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063e420264a14610030575b600080fd5b61004a6004803603810190610045919061011a565b610060565b60405161005791906101a5565b60405180910390f35b600073__$b3157e226f2c4dddae135e6cab4ed4e747$__63b3de648b836040518263ffffffff1660e01b8152600401610099919061018a565b60206040518083038186803b1580156100b157600080fd5b505af41580156100c5573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100e99190610143565b9050919050565b6000813590506100ff816101ca565b92915050565b600081519050610114816101ca565b92915050565b60006020828403121561012c57600080fd5b600061013a848285016100f0565b91505092915050565b60006020828403121561015557600080fd5b600061016384828501610105565b91505092915050565b610175816101c0565b82525050565b610184816101c0565b82525050565b600060208201905061019f600083018461017b565b92915050565b60006020820190506101ba600083018461016c565b92915050565b6000819050919050565b6101d3816101c0565b81146101de57600080fd5b5056fea264697066735822122020a8bc2e01963760c213821310bc9bea51a3cfcc7dc46771171a6028adddb66b64736f6c63430008040033

    // $b3157e226f2c4dddae135e6cab4ed4e747$ -> test/libsolidity/semanticTests/libraries/stub.sol:L

    ======= test/libsolidity/semanticTests/libraries/stub.sol:L =======
    Binary:
    6101d4610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100355760003560e01c8063b3de648b1461003a575b600080fd5b81801561004657600080fd5b50610061600480360381019061005c91906100a1565b610077565b60405161006e91906100d9565b60405180910390f35b6000818261008591906100f4565b9050919050565b60008135905061009b81610187565b92915050565b6000602082840312156100b357600080fd5b60006100c18482850161008c565b91505092915050565b6100d38161014e565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b60006100ff8261014e565b915061010a8361014e565b9250817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff048311821515161561014357610142610158565b5b828202905092915050565b6000819050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6101908161014e565b811461019b57600080fd5b5056fea26469706673582212203a397998c84d74f23a1af49ff538f5a353039460fe00aa622d24ba9035d8743664736f6c63430008040033
    ```
    - Note the `__$b3157e226f2c4dddae135e6cab4ed4e747$__` part inside `C`'s bytecode (you need to scroll to see it above). It's a placeholder for a library address. Linking in Solidity simply means inserting an actual library address in that spot. It takes up exactly 40 characters in the hex encoding that represent 20 bytes in the decoded bytecode.
    - To make this more apparent the compiler lists all the placeholders below the bytecode, which tells you the exact name of the library and the file.
- Try telling the compiler where that library has been deployed on the blockchain:
    ```bash
    solc test/libsolidity/semanticTests/libraries/stub.sol --bin --libraries test/libsolidity/semanticTests/libraries/stub.sol:L=0x1234567890123456789012345678901234567890
    ```
    - This way you told the compiler to build and immediately link the contract (all in one operation).
    - Note that that the placeholder has disappeared from the produced bytecode. It has been replaced with the address you gave.
- You can also perform linking on an already compiled binary using the `--link` option:
    ```bash
    solc test/libsolidity/semanticTests/libraries/stub.sol --bin > bytecode.bin
    solc bytecode.bin --link --libraries test/libsolidity/semanticTests/libraries/stub.sol:L=0x1234567890123456789012345678901234567890
    ```
    - Note that in the `--link` mode the compiler modifies the bytecode in place. To see the result you need to open `bytecode.bin`.
- The issue here is that these two methods are implemented separately.
    - The first one uses `LinkerObject::link()`. See [LinkerObject.h](https://github.com/ethereum/solidity/blob/develop/libevmasm/LinkerObject.h)/[LinkerObject.cpp](https://github.com/ethereum/solidity/blob/develop/libevmasm/LinkerObject.cpp).
    - The second uses `CommandLineInterface::link()`. See [CommandLineInterface.cpp](https://github.com/ethereum/solidity/blob/develop/solc/CommandLineInterface.cpp).
- The goal is to rewrite `CommandLineInterface::link()` to use `LinkerObject::link()` internally.
- Note an important detail: `LinkerObject` operates on binary bytecode (that's what `LinkerObject::bytecode` stores) while the binary `CommandLineInterface::link()` gets as input is hex-encoded - except for the placeholders. So you need to detect the placeholders and decode everything except them. Only then you can create a `LinkerObject` and use its `link()` method.

If you run into problems with the the implementation, please drop by on the [solidity-dev](https://gitter.im/ethereum/solidity-dev) channel. During the week you can find me and other developers there (though note that this Monday is a holiday so probably best to try on Tuesday :)).

**Comment by Uttam-Singhh** [comment]
Thank you! so much @cameel!
I will start working on this as soon as possible...

**Comment by cameel** [comment]
@Uttam-Singhh Are you still working on this issue? Do you need any help?

**Comment by Uttam-Singhh** [comment]
Hey @cameel 
Sorry, I was not able to work on this, I tried to learn the concepts but I think so I need to learn more to work on this.
I am unassigning myself. Sorry for the inconvenience!
Looking forward to working on more issues in the future.
Thank you so much for you guidance @cameel!

**Comment by cameel** [comment]
No worries! If you want, you could try a different task, maybe it'll be easier for a start. Here are some possibilities:
- #10812 - this is a simple tool that consists of a single `.cpp` file. Should be pretty easy.
- #11629 - in this there are will probably be a lot of changes but they should be all simple (just adding checks and printing errors) and you can also just do them one at a time to make PRs simpler.
- #10275
- #7578

**Comment by Uttam-Singhh** [comment]
Thank you so much @cameel. I will have a look at them!

**Comment by ryzheboka** [comment]
Hi, can I work on this issue? Can you please check my understanding of the changes? I would need to rewrite CommandLineInterface::link(), so it reuses code from LinkerObject::link() for linking already compiled code. The code in LinkerObject::link() is already used for linking with the option  --libraries. What do I do with the placeholders while translating the hex-encoded input of CommandLineInterface into binary?

**Comment by cameel** [comment]
Please take a look at https://github.com/ethereum/solidity/issues/10308#issuecomment-846609226. It describes in detail what needs to be done.

> What do I do with the placeholders while translating the hex-encoded input of CommandLineInterface into binary?

It does not matter all that much because `LinkerObject` does not really look at them and instead uses the `linkReferences` map to find the right place in the bytecode to overwrite. You need to find them and fill the `linkReferences` map but after that you can just replace them with anything that will not cause an error during hex decoding.

One thing to keep in mind though is that after linking there might still remain some unlinked references if they were not given in `--libraries`. When that's the case, you will need to restore them to what they originally were.

**Comment by ryzheboka** [comment]
I'm sorry, I won't be able to work on the issue. I had problems building solidity on my computer, and I could't resolve them.

**Comment by cameel** [comment]
Recently a user requested that we add config for one of the online IDEs, claiming that it would be a good way for contributors to easily get a working environment. It was #12112. I haven't personally tried that IDE so I can't say if it would work but maybe you'd like to try? It might let you work on this without having to fight with the build system. And I'd be interesting to know if it's really something we could recommend to contributors.

**Comment by ryzheboka** [comment]
Yes, I will gladly try using the online IDE.

**Comment by cameel** [comment]
Great. Let me know if you need any help. Maybe @nickytonline would be able to chime in too since he's using that IDE.

**Comment by nickytonline** [comment]
@ryzheboka, I'm new to the Solidity project, but am pretty familiar with Gitpod, so if you have questions, don't hesitate.

**Comment by ryzheboka** [comment]
Building on Gitpod with the config from #12112 worked! I need to get more comfortable with Gitpod, and I will work on the issue from there.

**Comment by ryzheboka** [comment]
Could please help me with a question about creating a LinkerObject from CommandLineInterface::link(). Do I need to iterate through the hex-encoded bytecode in m_fileReader.sourceCodes() to create the map of offsets of the placeholders (linkReferences)? Or is it already implemented in solidity, so I just need to call the right function?

**Comment by cameel** [comment]
Yeah, you need to iterate over it. That's basically what CLI is doing right now, it just replaces the placeholders instead of creating a map.

I don't think we have this implemented anywhere because normally we don't have to look for these references. We store their locations when we append instructions to the binary while it's being created.

**Comment by ryzheboka** [comment]
CommandLineInterface implements linking by iterating over all source code files, but a linker object only has one bytecode. Do I need to create a linker Object for every file? If my questions are too much, the issue might still be too hard for me.

**Comment by cameel** [comment]
> CommandLineInterface implements linking by iterating over all source code files, but a linker object only has one bytecode. Do I need to create a linker Object for every file?

Yes. `LinkerObject` represents bytecode of a single contract and the `--link` option expects one contract per file.

> If my questions are too much, the issue might still be too hard for me.

Not a problem at all. Ask for as much detail as you need. If there's something that needs more back and forth discussion, you might want to drop in on the gitter channel instead :)

But if you'd like to try something easier as a warmup, maybe something from #12011 would be good? You don't have to cover all the options listed there - a small PR just for one would be enough too.

**Comment by cameel** [comment]
> But if you'd like to try something easier as a warmup, maybe something from #12011 would be good? You don't have to cover all the options listed there - a small PR just for one would be enough too.

Actually, looks like #12179 covers the whole PR. Before reviewing it I thought it only did part of the options. In that case you might want to try #5474 or #11917 instead.

**Comment by ryzheboka** [comment]
Thanks for your answers :) 

I will try to finish rewriting the CommandLineInterface::link() method. I have an idea how it could be done. I need to create a LinkerObject for each file by iterating through the code and saving the offsets (difference between current pointer and the begin of the current file) into the linkReferences map. Then, I convert the content of the file from string to hex integer to bytes. This will be the bytecode of the LinkerObject. Then, I call LinkerObject::link() with the libraries as parameter.  Then, I call the LinkerObject::toHex() that swaps the code at the offsets in linkReferences back to placeholders. I replace the source code by the return value of the method toHex. 

If it doesn't work out, I will gladly try  #12011.

**Comment by cameel** [comment]
Actually, a small clarification: there can be more than one `LinkerObject` per file. The solution must involve detecting bytecode in the input file. I'd suggest the following heuristic:
- Bytecode takes the whole line, no stray chars or whitespace allowed at the beginning or end.
- It can contain only the following chars: `0-9`, `a-f`, `_`, `$`.
- Two pieces of bytecode must be separated by at least one line that does not contain bytecode.

So you should find all chunks satisfying these conditions in the file, convert each one into `LinkerObject`, try to link it and then replace the original text with the result of linking.

This should be easy to do with a regex.

**Comment by ryzheboka** [comment]
The current solution in CommandLineInterface takes up less code than the one using LinkerObject would take. It also seems more readable/understandable, because it just replaces the placeholders without parsing anything else. Should I still continue to implement the other solution?

**Comment by cameel** [comment]
Yeah, we still want it. The reason we do this change is to avoid having linking implemented independently in two different places. Until very recently for example the `LinkerObject` supported unqualified library names while `--link` option did not. It was ultimately [removed](https://github.com/ethereum/solidity/pull/12073/commits/816d8021e4f57b1b32eb3ce1fbfa421a585a0f0f#diff-4c2eb24107a9f3181c181c24abaad7b6c9a71c99a895bcc4a1146567d87e1b5c) and the code in `LinkerObject` is simpler now. We also had bugs that affected one but not the other. The point is that we want the logic from `LinkerObject` to be used in all places that do linking, even if it means that the code is a bit more verbose.

You can also place the parts of the code that are generic enough in `LinkerObject`. For example I think that the part that gets bytecode with placeholders and constructs the map with location could be added as a function there. This will preserve some readability and will make the code easier to reuse.

**Comment by ryzheboka** [comment]
Thanks for the explanation about placing the parts of code in LinkerObject :)

Is it ok if I use the option -DUSE_Z3=OFF to build and test solidity for this issue? Or do I need to change the configuration in Gitpod? I get the following error without using  -DUSE_Z3=OFF:

 -- Found Z3: /usr/lib/x86_64-linux-gnu/libz3.so (found version "0.0.0") 
CMake Error at CMakeLists.txt:83 (message):
  Solidity requires Z3 4.8.0 or newer.  You can also use -DUSE_Z3=OFF to
  build without Z3.

**Comment by cameel** [comment]
Yeah, it's completely fine. This PR has nothing to do with SMTChecker so Z3 should not make any difference. And in the very unlikely case that it does, CI checks will catch it so no worries :)

I mean, the GitPod config should use Z3 but that's a separate matter and hopefully it will be resolved in #12146. For this PR not having will not cause any trouble.

**Comment by ryzheboka** [comment]
@nickytonline, could you please help me with Gitpod? Yesterday, I could start building solidity, but somehow it doesn't work today anymore. The gitpod.yml has been run when I start the project, and it seems to install Boost. However, today, I get the following error after running cmake in the build directory: 
"CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.21.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem
  unit_test_framework program_options system) (Required is at least version
  "1.65.0")
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.21.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.21.3/share/cmake/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
  cmake/EthDependencies.cmake:40 (find_package)
  CMakeLists.txt:43 (include)

-- Configuring incomplete, errors occurred!"

**Comment by nickytonline** [comment]
> Yeah, it's completely fine. This PR has nothing to do with SMTChecker so Z3 should not make any difference. And in the very unlikely case that it does, CI checks will catch it so no worries :)
> 
> I mean, the GitPod config should use Z3 but that's a separate matter and hopefully it will be resolved in #12146. For this PR not having will not cause any trouble.

I'm still sorting that out. Got pulled on other stuff.

> @nickytonline, could you please help me with Gitpod? Yesterday, I could start building solidity, but somehow it doesn't work today anymore. The gitpod.yml has been run when I start the project, and it seems to install Boost. However, today, I get the following error after running cmake in the build directory:

@ryzheboka, I'm going to take a look at that as I'm going to get back on that PR.

**Comment by nickytonline** [comment]
@ryzheboka, I've updated my branch to include the Ethereuem PPA and when I loaded up Gitpod today, it seems all good. Let me know if you still have issues.

**Comment by ryzheboka** [comment]
Thanks @nickytonline, it worked with the new gitpod.yml!  (Still only with -DUSE_Z3=OFF)
Now, I have the following problem with testing, that seems to be configuration related: 
"./scripts/../test/cmdlineTests.sh: line 185: /dev/stdin: Permission denied
Incorrect output on stderr received. Expected:
"file_not_found.sol" is not found.
But got:

When running /workspace/solidity/build/solc/solc file_not_found.sol </dev/stdin"

**Comment by cameel** [comment]
The script asks you to update the file if expectations do not match. If should just fail if there's no terminal - that's how it works in our CI. If that's not the case, you could try to explicitly take away its input stream with something like this:
```bash
cmdlineTests.sh < /dev/null
```

Of if you call it via `tests.sh`, you could add `< /dev/null` to that script invocation instead.

**Comment by nickytonline** [comment]
> Thanks @nickytonline, it worked with the new gitpod.yml! (Still only with -DUSE_Z3=OFF) Now, I have the following problem with testing, that seems to be configuration related: "./scripts/../test/cmdlineTests.sh: line 185: /dev/stdin: Permission denied Incorrect output on stderr received. Expected: "file_not_found.sol" is not found. But got:
> 
> When running /workspace/solidity/build/solc/solc file_not_found.sol </dev/stdin"

z3 should be the correct version now if you grab latest of my branch.

**Comment by ryzheboka** [comment]
Z3 works now, I forgot to save the changed .yml file in gitpod. < /dev/null helped too. Could you please help with the following message?

"Error loading VM from libevmone.so:
libevmone.so: cannot open shared object file: No such file or directory
Unable to find libevmone.so. Please disable semantics tests with --no-semantic-tests or provide a path using --vm <path>."

I tried running the tests with --no-smt, but got the same message. It was not possible to run tests.sh with the argument "-no-semantic-tests". All the tests till the message run successfully.

**Comment by cameel** [comment]
The `--no-semantic-tests` flag is supported by the `soltest` and `isoltest` executables but probably not by `scripts/tests.sh`. For your task, again semantic tests are not relevant but they are very important overall so I'd recommend installing `evmone` anyway so that you can run them.

So to solve this, please check if you can install a package called `evmone` or `libevmone`. If not, you can download pre-built binary from https://github.com/ethereum/evmone/releases/ and then put under `deps/lib/` in the repository so that `soltest` can find it. See also [Contributing > Running the Tests](https://docs.soliditylang.org/en/latest/contributing.html#running-the-tests) if you need more info.

**Comment by ryzheboka** [comment]
Thanks, semantic tests run successfully. The documentation says "Running Ewasm tests is disabled by default", however, I get the following error:

Error loading VM from libhera.so:
libhera.so: cannot open shared object file: No such file or directory
Unable to find libhera.so. 

Should I repeat the steps for evmone for hera too?

**Comment by cameel** [comment]
Yeah, it's disabled by default but seems that `tests.sh` tries to be comprehensive and does an ewasm run as well:
https://github.com/ethereum/solidity/blob/7334420423e026d65d2a48a2d0569fb19b3a2b40/scripts/tests.sh#L140

You don't really need it in this task so I recommend disabling it. The easiest way to do this would be to just locally comment out that line in your branch. If you want you can also submit a PR that adds a `--no-ewasm` option to the script. It already supports `--no-smt` and the new option would be pretty similar. It would also not hurt to have `--no-semantic-tests` there to have a full set.

**Comment by ryzheboka** [comment]
Next weeks will be very full and stressful for me. I probably won't be able to finish the testing, at least not in next weeks. I'm very sorry!

**Comment by cameel** [comment]
No worries. Take your time. There is no deadline for this task so if you want to just come back to it later when you have more time that's not a problem for us :)

**Comment by bmoore01** [comment]
I've created a PR that hopefully resolves this issue https://github.com/ethereum/solidity/pull/12756

**Comment by cameel** [comment]
@bmoo0 Thanks! I'm going to reassign the issue to you then.

**Comment by Marenz** [comment]
Current status is that there is a PR implementing this but it needs some cleanup work
