### ISSUE TITLE
During "enforce yul" mode, different return value should be a hard error

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#10313]
In isoltest, when we are running in "enforce yul" mode, it should be a hard error if the yul version works but returns something else. Currently, this problem is silently skipped.

**Comment by mijovic** [comment]
I started doing this. Since we still have such tests that are failing due to different results, should I add a flag in expectations that marks such tests?

**Comment by chriseth** [comment]
No, let's just disable them for now. There are more such situations in https://github.com/ethereum/solidity/pull/10235 already.

**Comment by axic** [comment]
This was my collection of all the issues of this kind: https://github.com/ethereum/solidity/issues/10390#issuecomment-734333155
