### ISSUE TITLE
wasm binary for 0.5.17 is missing in solc-bin

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10329]
We only have asm.js build for 0.5.17 so it's not present in [solc-bin/wasm](https://github.com/ethereum/solc-bin/tree/gh-pages/wasm). Looks like wasm rebuilds did not include it because they were done before that version was released.

**Comment by cameel** [comment]
I originally thought that we just need a symlink and wanted to add it now but it turns out we need to actually rebuild it. I'm reporting it to get back to it later.

**Comment by cameel** [comment]
When this is built, remember to submit a PR in remix to mark 0.5.17 as a wasm build (see https://github.com/ethereum/remix-project/pull/1133).

**Comment by blitz-1306** [comment]
Hello there. Is there any blocker for adding missing build to [solc-bin WASM distributions](https://binaries.soliditylang.org/wasm/list.json)? There is [a published version in the NPM](https://www.npmjs.com/package/solc/v/0.5.17) that actually bundles `soljson.js` file in the package. Could somebody check if it fits to the distribution and if so, add it?

**Comment by blitz-1306** [comment]
@chriseth sorry for pinging and applying necromancy to an old issue discussion. Still, would it be possible to do anything with the missing 0.5.17 WASM release in historical builds archive?

**Comment by cameel** [comment]
> Hello there. Is there any blocker for adding missing build to [solc-bin WASM distributions](https://binaries.soliditylang.org/wasm/list.json)?

Mostly a matter of time and lack of urgency. Last time I did mass rebuilds it took some fiddling to get stuff below 0.6.0 to build. 

There is an asm.js binary available in [bin/soljson-v0.5.17+commit.d19bba13.js](https://github.com/ethereum/solc-bin/blob/gh-pages/bin/soljson-v0.5.17%2Bcommit.d19bba13.js). Wasm binaries are faster but asm.js are still fully usable. If you're downloading the compiler in a script, you should really have a fallback to `bin/` if you don't find a specific version in `wasm/`.

> There is [a published version in the NPM](https://www.npmjs.com/package/solc/v/0.5.17) that actually bundles `soljson.js` file in the package. Could somebody check if it fits to the distribution and if so, add it?

It's the asm.js binary I mentioned above.

> Still, would it be possible to do anything with the missing 0.5.17 WASM release in historcal builds archive?

I talked with @chriseth and we decided to try to rebuild it now. So it'll become available soon unless it turns out it needs some wild workarounds to build.

**Comment by cameel** [comment]
Rebuilt binary is ready: https://github.com/ethereum/solc-bin/pull/112. It will become available at binaries.soliditylang.org once the PR is reviewed and merged.
