### ISSUE TITLE
Inherited modifier contract prefix

### ISSUE THREAD

**Issue by thegostep** [ethereum/solidity#10331]
## Abstract

Recent changes to the language have made the language much more explicit. The ability to specify the source contract from which a modifier is called seems to be missing.

## Motivation

```solidity
contract Ownable {
    address private _owner;

    modifier onlyOwner() {
        require(_owner == msg.sender, "Ownable: caller is not the owner");
        _;
    }
}

contract CurrentBehavior is Ownable {
    function someAction() external onlyOwner { } 
}

contract DesiredBehavior is Ownable {
    function someAction() external Ownable.onlyOwner { } 
}
```

## Specification

See above

## Backwards Compatibility

None

**Comment by cameel** [comment]
Thanks for feedback!

This is actually already implemented in #10307. The change was merged into `breaking` branch yesterday so it will be released in 0.8.0.
