### ISSUE TITLE
In Sol->Yul, the code depends on AST IDs

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#10342]
In Sol->Yul, internal function IDs are the IDs of the AST node of the function definition. This means that re-compiling with a slightly different AST results in different code being generated. Furthermore, function IDs could be needlessly large. We should find a different way to allocate these IDs.

**Comment by aarlt** [comment]
Is it correct that this refers to the generation of internal dispatch functions defined in `libsolidity/codegen/ir/IRGenerator.cpp` @ `IRGenerator::generateInternalDispatchFunctions()`? 

Don't we have the same problem with the generation of getters `IRGenerator::generateGetter` and immutables `IRGenerator::deployCode`?
