### ISSUE TITLE
[solc 0.5.16] Compilation succeeds, but output dir is empty.

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/solidity#10344]
With https://github.com/tellor-io/TellorCore/tree/V2.5.0

Running 
```
solc0.5.16 --allow-paths . tellorlegacy=./node_modules/tellorlegacy contracts/TellorMaster.sol -o ./compile
```
returns
```
Compiler run successful. Artifact(s) can be found in directory ./compile.
```
but the directory is empty

**Comment by chriseth** [comment]
You did not specify any output to be created. There should be a message about that from the compiler, though.

**Comment by krasi-georgiev** [comment]
what about the `-o ./compile` flag?

**Comment by krasi-georgiev** [comment]
I just tried moving the flag at the beginning, but no change
```
solc0.5.16 -o compiled --allow-paths . tellorlegacy=./node_modules/tellorlegacy contracts/TellorMaster.sol
```

**Comment by chriseth** [comment]
The '-o' just tells where to put "stuff", but you need to select stuff to be generated, like '--bin'.

**Comment by krasi-georgiev** [comment]
yes apologies, user mistake, Thanks for the prompt reply!
