### ISSUE TITLE
Allow accessing stack slots of external function pointers in Solidity assembly

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#10358]
## Abstract

Yul within Solidity is mostly able to work with Solidity variables.  Local variables mostly refer to an individual stack slot, which Yul is able to handle.  Storage variables are manipulable with `x.slot` and `x.offset`.  (I'll ignore `immutable` variables, which are their own problem.)  However there's the problem of using Solidity variables that take up two stack slots.  There are two sorts of these: calldata variables of dynamically-sized type, and external function pointers.  The former can now be used within assembly due to #10208, with the two stack slots accessible as `x.offset` and `x.length`.  However there's still no way to use the latter.

## Motivation

My suggestion is that, just as #10208 introduced `x.offset` and `x.length`, Solidity variables of `function external` type should have their two stack slots exposed in Yul via `x.address` and `x.selector`.

Note: I discussed this earlier in #8917.

## Specification

If `x` is a Solidity local variable of `function external` type, that is within scope within a give `assembly` (Yul) block, then `x.address` should refer to the lower of its two stack slots, and `x.selector` should refer to the upper of its two stack slots, in accordance with how `x` is stored on the stack.

## Backwards Compatibility

This change would be entirely backwards compatible.

**Comment by axic** [comment]
Seems straightforward, at least for reading, but I'm curious: have you seen anyone use function pointers in the wild?

**Comment by haltman-at** [comment]
I haven't myself, but @gnidan has told me of examples... unfortunately he seems to have lost them!  But hopefully we can find them again...

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/12016
