### ISSUE TITLE
formal verification: specify evaluagion order of f(g(), h())

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1037]
In an expression `f(g(), h())`, which stance does Solidity take?  There are several possibilities:
1. all side effects of `g()` happens before all side effects of `h()`
2. all side effects of `h()` happens before all side effects of `g()`
3. at the compilation time 1. or 2. is chosen
4. at runtime 1. or 2. is chosen
5. ordering is not guaranteed but all side effects of `h()` and `g()` happen
6. at most one of `g()` and `h()` can have side effects, otherwise there is no guarantee about the behavior

Similar questions can be asked for struct formation and pair formation.

This issue keeps track of:
- [ ] make sure the choice is documented, and
- [x] make sure the choice is implemented

**Comment by chriseth** [comment]
It is documented as option 5

**Comment by pirapira** [comment]
@chriseth Ah yes, that's why the [comment](https://github.com/ethereum/solidity/blob/2e70f6bfd180630d41cfc493975b04f39f5d7ab1/libsolidity/formal/Why3Translator.h#L39) to limit the number of side-effects.

**Comment by pirapira** [comment]
So I created [an issue](#1043) to limit the number of side-effects.
