### ISSUE TITLE
Add SHA-256 hashes to file lists in solc-bin

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10379]
Proposed by @axic in https://github.com/ethereum/solidity/pull/10352#discussion_r527268367.

> Hmm, didn't we also had a sh256 hash next to this? That is way more useful for anyone downloading a static compiler from here and trying to verify it on CI (as that works with shasum -a 256 <file>).

After doing this the example in solc-bin docs should be updated to include such a hash too.

**Comment by rainbreak** [comment]
Yes please, it's way easier to deal with sha256. In particular, NixOS requires a sha256 when fetching a url and can't accept keccak256, so I have to manually calculate the sha256.

**Comment by axic** [comment]
Finally found that I actually did this years ago, that's why I was confused in the opening comment why it wasn't done: https://github.com/ethereum/solc-bin/pull/19 (commit [dcbf73d](https://github.com/ethereum/solc-bin/pull/19/commits/dcbf73d6794de6e44d80e8ac84b2d6b1bce0aa13))
