### ISSUE TITLE
formal verification: specify evaluation order of arr[i++] = i

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1038]
The effect of the expression `arr[i++] = i` is different depending on the evaluation order of the index `i++` and the right hand side `i`.  If the index is evaluated before the right hand side, an incremented value is assigned.

This issue keeps track of
- [ ] making sure that the choice is documented
- [ ] making sure that the choice is implemented

**Comment by chriseth** [comment]
This is similar to #1037 . I think whatever we document, it would be best to catch such cases and report them as a warning, but I fear that we need a formal verification engine to do this.

**Comment by pirapira** [comment]
OK.  For now I'm fine with disallowing multiple side-effects in an expression.

Let me think about how to detect these.
