### ISSUE TITLE
feature discussion: batched delegatecalls and the msg.value problem

### ISSUE THREAD

**Issue by gitpusha** [ethereum/solidity#10382]
Referencing the discussion that started here: #10317 

@gitpusha 
> make it so that when batch delegatecalling targets from a contract, not all of them have to be payable functions in order for there to be a non-zero msg.value property (probably impossible to implement due to EVM restriction? )

@chriseth 
> Yes, this is an EVM restriction. Solidity library functions actually do not have a check for msg.value for exactly this purpose. Maybe we could find another way to specify "this is a delegatecall target function"? Or maybe we should modify libraries so that they can be more easily used like that?

One example where such batched delegatecalls takes place and where, if you want to use `msg.value` with the call invoking the batched delegatecalls ( `cast() external payable` ), you have to make sure all `_targets` are `payable` functions, is [InstaDapps smart wallets ](https://github.com/InstaDApp/dsa-contracts/blob/7e70b926cb33263783f621612157f49f785daa0a/contracts/account.sol#L91)cast function.

```solidity
    function spell(address _target, bytes memory _data) internal {
        require(_target != address(0), "target-invalid");
        assembly {
            let succeeded := delegatecall(gas(), _target, add(_data, 0x20), mload(_data), 0, 0)

            switch iszero(succeeded)
                case 1 {
                    // throw if delegatecall failed
                    let size := returndatasize()
                    returndatacopy(0x00, 0x00, size)
                    revert(0x00, size)
                }
        }
    }

    function cast(
        address[] calldata _targets,
        bytes[] calldata _datas,
        address _origin
    )
        external
        payable
    {
        require(isAuth(msg.sender) || msg.sender == instaIndex, "permission-denied");
        require(_targets.length == _datas.length , "array-length-invalid");
        IndexInterface indexContract = IndexInterface(instaIndex);
        bool isShield = shield;
        if (!isShield) {
            require(ConnectorsInterface(indexContract.connectors(version)).isConnector(_targets), "not-connector");
        } else {
            require(ConnectorsInterface(indexContract.connectors(version)).isStaticConnector(_targets), "not-static-connector");
        }
        for (uint i = 0; i < _targets.length; i++) {
            spell(_targets[i], _datas[i]);
        }
        address _check = indexContract.check(version);
        if (_check != address(0) && !isShield) require(CheckInterface(_check).isOk(), "not-ok");
        emit LogCast(_origin, msg.sender, msg.value);
    }
```

Sometimes you might want to send some ETH to `cast` and make use of it in a `target` delegatecall, like for example depositing new ETH somewhere. This however means that if you want to batch any other delegatecalls with that payable call to `cast`, all of their target functions must be `payable` too, even if they shouldnt be, in order for their to be no call-value revert.

**Comment by gitpusha** [comment]
Talking about solutions: 

> Solidity library functions actually do not have a check for msg.value for exactly this purpose. Maybe we could find another way to specify "this is a delegatecall target function"? Or maybe we should modify libraries so that they can be more easily used like that?

Can you call `library` methods directly with a low-level delegatecall without linking them in your contract code? If so, I guess one possible solution would be to write and deploy all `targets` that are not `payable` as `libraries` instead of `contracts` and thus let them bypass the call-value restriction?

**Comment by chriseth** [comment]
Oh of course, If you use `delegatecall`, then libraries are a better target, because they are built for that purpose. Why would you use them only for non-payable functions?

**Comment by gitpusha** [comment]
> Why would you use them only for non-payable functions? 

Not sure. I think I wrongly assumed library methods shouldnt be `payable` which was a misconception. 

I think I am happy with this solution to circumvent the call-value restriction for these use cases. I will close the issue. Thanks for your help!
