### ISSUE TITLE
formal verification: make readonly Solidity functions available in the specification

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1039]
Currently in the specification (like `///@why3 invariant { ... }`), it's impossible to use contract functions even when they are write-effect-free.   This issue keeps track of allowing it.

**Comment by chriseth** [comment]
Which kind of functions are you referring to? Smart contract methods or pure why3 functions?

**Comment by pirapira** [comment]
Smart contract methods.  I'll change the description.

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
