### ISSUE TITLE
Optimize the IR generation process

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10405]
Currently the codepath through the IR generator takes >15x time on the average case, and >25x in some other cases.

- Most of the time is spent within the Yul optimizer, more specifically within `DataFlowAnalyzer`.
- While the time spent in `IRGenerate` in comparison is small, 50% of `IRGenerate` time is spent in Whiskers. Which is mostly what it does, but perhaps we can look at the `replace` function.
- Another time consumer is running the Yul optimizer again when compiling the IR to EVM -- perhaps this can be skipped?

**Comment by chriseth** [comment]
We could check if the DataFlowAnalyzer is needed in all the steps. We might also switch off some of its functionality depending on who uses it.

**Comment by chriseth** [comment]
Another idea to improve the performance of the DataFlowAnalyzer:
Currently, it always represents the state of all variables. It might be more efficient to instead just store the processes that modify the states of variables (assignments, etc). And then only determine the value of a variable upon request by analyzing the processes.

**Comment by axic** [comment]
This seems to be behaving better now:

```sh
$ time solc/solc --ir --optimize uniswap-v2-core/contracts/UniswapV2Pair.sol
real    0m3.576s
$ time solc/solc --experimental-via-ir --optimize uniswap-v2-core/contracts/UniswapV2Pair.sol
real    0m3.789s
$ time solc/solc --optimize uniswap-v2-core/contracts/UniswapV2Pair.sol
real    0m1.470s
```

```sh
$ time solc/solc --experimental-via-ir --optimize circles-contracts/contracts/Token.sol 
real    0m3.326s
$ time solc/solc --optimize circles-contracts/contracts/Token.sol 
real    0m0.596s
```

**Comment by axic** [comment]
Closing for now.
