### ISSUE TITLE
Update solAsserts with a message

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1042]
Currently there are 184 `solAsserts` with a message and 171 without. They don't really provide any meaningful output.

I understand that in many cases it would be useless, but there are many where they are. At least when finding a bug, one doesn't need to run a debugger to know where it stopped, but could grep for the message.

**Comment by chriseth** [comment]
solAssert throws a boost exception and should report the line number. Nobody should be forced to grep for a message ;-)

**Comment by axic** [comment]
Didn't notice, that should help :)

Nonetheless, in many cases a message could be added. I agree that in some cases it could be superfluous.

**Comment by axic** [comment]
Now we have 568 cases in `libsolidity` alone. Quite a bit more than the 171 back in 2016.

**Comment by chriseth** [comment]
I still don't see the real need...

**Comment by leonardoalt** [comment]
I also don't see the real need since the exception should not happen and it shows the line and file anyway.
@chriseth @axic can we close this?
