### ISSUE TITLE
New modifier for reentrancy-safe functions which denies CALL and DELEGATECALL instructions

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#10422]
## Abstract

Add new modifier for functions which are allowed to make STATICCALLs and SSTORE, but denied to make CALLs and DELEGATECALLs. This modifier would allow having compile-time protection similar to `nonReentrant` modifier functionality for 0 gas cost.

## Motivation

Reentrancy is such a terrific attack surface for smart contracts that many developers add `nonReentrant`, `_lock_` and even [`_viewlock_`](https://github.com/balancer-labs/balancer-core/blob/master/contracts/BPool.sol#L131) modifiers to all the methods. It would be great to have 0 gas cost compile-time check that some method is not vulnerable to reentrancy because do not produce any non-view externals call.

## Specification

Use keyword `writeonly` or `reentracySafe` or any other for this modificator.

## Backwards Compatibility

Fully compatible since restricts the only subset of non-view functions.

**Comment by cameel** [comment]
So this would basically be a new mutability level called `writeonly` (or `reentrancySafe` but this does not really fit the current set of names) that would sit between `view` and the current default where the state is completely mutable? 

What do you think about @axic's proposal from https://github.com/ethereum/solidity/issues/9248#issuecomment-713884387 that would introduce a `state()` modifier that would allow more granular control than the current set of mutability levels. If we combined it with your proposal, it could include a `call` permission and then you would have to explicitly define a function like this if you wanted to allow reentrancy:
```solidity
function f() state(read, write, call) {}
```

**Comment by k06a** [comment]
@cameel this would work if we would have permissions:
- read
- write
- call
- viewcall
- delegatecall
- codecall
- create

**Comment by chriseth** [comment]
@k06a isn't your list a bit too fine-grained? Shouldn't the following be sufficient:
 - direct state modification (via sstore)
 - indirect state modification (via call, delegatecall, create, ...)
 - send ether
