### ISSUE TITLE
Separating builtin modifier and remove function keyword

### ISSUE THREAD

**Issue by chiro-hiro** [ethereum/solidity#10434]
## Abstract

I think, Solidity should learn something from TypeScript and new ECMAScript. Especially its modifier and function definition in contract.

## Motivation

- Help the code more clean and realizable 
- Separate builtin modifiers: `public`, `external`, `private`, `internal`, `virtual`, `pure`, `view` and self-defined modifiers
- Remove `function` keyword 

## Specification

Method in contract could be define following this syntax:

```
<visible> [mutable] [override] <methodName>([params]) returns([results])
```

- visible: `public`, `private`, `internal`, `external`
- mutable: `view`, `pure`
- override: `virtual`

E.g:

```
contract TestContract {
    internal view virtual getAddress(uint256 index) returns(address newAddresss) {}
    external pure calcuateRate() onlyWhitelisted returns(uint256) {}
}
```

Solidity wasn't allowed functional programming , so keyword `function` won't be defined outside of `contract {}`, `interface {}`. That make no sense to keep `function` keyword meanwhile visible is the most important thing and builtin modifiers should to be separated from self-defined modifiers.

## Backwards Compatibility

No backward compatible

**Comment by axic** [comment]
> Solidity wasn't allowed functional programming , so keyword function won't be defined outside of contract {}, interface {}. 

Since a handful of releases functions outside of contracts are actually allowed.

**Comment by chiro-hiro** [comment]
How about rearrange modifiers and remove function keyword in contract body?. Does it worth to be considered?.

**Comment by axic** [comment]
I think it definitely makes sense to consider it, but needs input from more people.

I suggest to also give a look to https://github.com/ethereum/solidity/issues/9248#issuecomment-713884387, which is a different proposal hopefully improving the visibility of these specifiers.
