### ISSUE TITLE
[codegen] ICE in StackHeightChecker::check

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10438]
## Description

```
contract C{function f()public{super(0);}}
```

throws

https://github.com/ethereum/solidity/blob/656cb810a446e68d4c275d5900c9553e172740a6/libsolidity/codegen/ContractCompiler.cpp#L79-L82

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
Oh actually I think this will be fixed by https://github.com/ethereum/solidity/pull/10456

**Comment by hrkrshnn** [comment]
Closed in https://github.com/ethereum/solidity/pull/10456
