### ISSUE TITLE
[Codegen/Breaking] Null ptr dereference in ExpressionCompiler::visit(MemberAccess const&)

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10435]
## Description

```
contract C {
    function f() public {
        type(super).name;
    }
}
```

throws null ptr deref here

https://github.com/ethereum/solidity/blob/45307a24d6f0de99454c52d85f9131881cce250c/libsolidity/codegen/ExpressionCompiler.cpp#L1604

and

https://github.com/ethereum/solidity/blob/45307a24d6f0de99454c52d85f9131881cce250c/libsolidity/ast/AST.h#L252

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
The issue here is that `super` does not exist. Do we really want to support `type(super).name` or was that just an omission in the super change?
