### ISSUE TITLE
formal verification: diallow multiple side-effects in a sentence

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1043]
This is a temporary mitigation for ambiguous side-effect ordering like #1037 and #1038.  This task is originally documented in [a todo comment](https://github.com/ethereum/solidity/blob/2e70f6bfd180630d41cfc493975b04f39f5d7ab1/libsolidity/formal/Why3Translator.h#L39).

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
