### ISSUE TITLE
[FixedHash] Segmentation fault in operator <

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10436]
## Description

```
pragma experimental SMTChecker;
contract A {
        mapping(string=>uint) map;
        function f(string memory s, uint x) public {
                map[s] - x;
        }
}
```

throws a segmentation fault due to out-of-bounds read

https://github.com/ethereum/solidity/blob/a5a560e163c25044412b7ed6c867a8bd5cfb26f6/libsolutil/FixedHash.h#L117

It looks like `_c.m_data[i]` is responsible for the out-of-bounds read.

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

preferably with valgrind/ASan

**Comment by axic** [comment]
This is actually not crashing for me on develop/breaking. It also seems `operator<` won't compile when comparing differently sized FixedHashes so not sure how would an overread happen.

**Comment by bshastry** [comment]
@axic That's strange, it still seg faults for me locally. Created a draft PR with the test to see what happens upstream. You can view it here https://github.com/ethereum/solidity/pull/10452

**Comment by ekpyron** [comment]
I think @leonardoalt @cameel and I are just hitting this in various situations.
I think it's present in ``Release`` or ``RelWithDebInfo`` builds that don't link against z3 nor cvc4. Maybe only statically linked once,  that's what looked at so far, but not yet sure. That includes ~~https://github.com/ethereum/solidity/releases/download/v0.7.4/solc-static-linux~~ https://github.com/ethereum/solidity/releases/download/v0.7.5/solc-static-linux, that is the static linux release for ~~0.7.4~~ 0.7.5 and is still present on develop.
EDIT: I actually meant 0.7.5, in fact it **doesn't** happen on 0.7.4, as https://github.com/ethereum/solidity/issues/10436#issuecomment-738314748 points out.

**Comment by leonardoalt** [comment]
It also includes 0.7.5.

**Comment by axic** [comment]
I have a large set of changes to FixedHash locally, but the first step #10448 is waiting for reviews.

**Comment by ekpyron** [comment]
Pretty sure https://github.com/ethereum/solidity/pull/10494 fixes this (so it's rather unrelated to FixedHash itself).

**Comment by axic** [comment]
@leonardoalt Don't we need to merge #10452 now?

**Comment by leonardoalt** [comment]
Sure, we can merge that. The segfault wasn't related to that test specifically though, it was more general

**Comment by ekpyron** [comment]
What we definitely still need (and why the answer to https://github.com/ethereum/solidity/pull/10452#issuecomment-738995612 would be "no" ;-)), is changing our test runs, s.t. smt checker tests are at least compiled somewhere where there are no solvers available (instead of just being skipped entirely in such cases).
