### ISSUE TITLE
[TypeChecker] ICE in ContractType::nativeMembers

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10437]
## Description

```
contract C{function f(){super().x;}}
```

throws

https://github.com/ethereum/solidity/blob/656cb810a446e68d4c275d5900c9553e172740a6/libsolidity/ast/Types.cpp#L2161

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by hrkrshnn** [comment]
Closed in https://github.com/ethereum/solidity/pull/10456
