### ISSUE TITLE
Run external tests on all platforms

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10446]
Requested in https://github.com/ethereum/solidity/pull/10441#discussion_r532678397. Related to #10397.

Currently external tests use the emscripten binary. We should be running them on macOS and Linux executables too. Also Windows if that's not too much hassle.

**Comment by chriseth** [comment]
Which benefit do you see?

**Comment by cameel** [comment]
It would add some coverage for how tools interact with `solc` (rather than `soljson.js`) when compiling contracts. Though for that doing only compilation would suffice. Not sure it's worth actually running the test suites...

Also, @axic originally requested macOS tests. Maybe going for all platforms is an overkill after all.

**Comment by axic** [comment]
> Also, @axic originally requested macOS tests.

The point was that many scripts are Linux-specific and hence anyone using macOS relies on the CI to tell problems. If we ensure that every script works on macOS this becomes a non-problem.

**Comment by cameel** [comment]
I'm going to close this after all. After spending much more time with these tests, I don't see much benefit in running them on multiple platforms. Knowing that it works on all of them and that our binaries pass bytecode comparison tests between these platforms already gives us high confidence that we'll catch platform-specific bugs.

Also, being constrained to shell syntax that is portable to both Linux and macOS would make them much more painful to write and maintain. If we want portability, we should rewrite them in Python instead.
