### ISSUE TITLE
Specialized checked exponentation when exponent is a literal

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10443]
We already have a specialized checked exponentiation when the base is a literal and exponent can only be known at compile time.

Implement the case where exponent is a literal and base is only known at compile time. Vyper already has this: https://github.com/vyperlang/vyper/pull/2072

**Comment by axic** [comment]
Don't we have a rulelist entry for this in libevmasm?

**Comment by hrkrshnn** [comment]
What I mean is the following.

A code of the form `x**literal` should generate yul similar to this: `x**literal < 2**256` iff `x < e**(256 . ln(x) / ln(literal))` (you compute the upper bound using binary-search)

```
    if gt(x, upper-limit) {
       panic(Overflow)
    }
    ret :=  exp(x, literal)
```

Currently, the above code will undergo checked exponentiation by squaring.

We can have some rule list entries for special cases (such as `exp(x, 2)` into `mul(x, x)`), but that's not what this is about.

**Comment by hrkrshnn** [comment]
Already implemented.
