### ISSUE TITLE
[codegen] ICE due to compiled contract not found

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10457]
## Description

```
function f() {
        new D();
}
contract D {
        constructor() {
                f;
        }
}
```

throws

https://github.com/ethereum/solidity/blob/8279d90ba26576ece14fee9d32471fa20172a701/libsolidity/codegen/CompilerContext.cpp#L257

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
This is a known issue and fixed by a pr in progress from @marenz
