### ISSUE TITLE
Dpulls to manage dependent PRs

### ISSUE THREAD

**Issue by wberr** [ethereum/solidity#10469]
Hey there :wave:,

First of all, I'm really sorry if this is not the appropriate way to share something that is not directly related to the solidity language. Maybe another place would fit better, in such case, just let me know :)

I'm walid, the creator of [Dpulls](https://www.dpulls.com/), a Github app that helps you manage you dependent PRs.

I noticed that this PR https://github.com/ethereum/solidity/pull/10466 has another one as dependency on it (https://github.com/ethereum/solidity/pull/10429). After some research, I've also noticed that several other PRs depend on other ones so I thought maybe you'd be interested to try this service that I launched couple months ago. 
Basically, it **prevents a PR from being merged before its dependencies**.

**Example**:
![dependency (1)](https://user-images.githubusercontent.com/75340150/100807072-f433a800-3431-11eb-86b1-35f9bd108578.png)

Here is some of [Dpulls](https://www.dpulls.com/) features :rocket::

- Cross-repository referencing.
- Cross-organization referencing.
- No configuration required from you side. One click [setup](https://github.com/marketplace/dpulls).
- Just write **Depends on #pr** or **Depends on owner/repo#pr** and you are good to go :ok_hand:.  
- Already +2000 Github projects trusted us and are using Dpulls :rocket:.

:bulb:  If you want to try it, you can install it from the official [website](https://www.dpulls.com/) or the Github [marketplace](https://github.com/marketplace/dpulls).

I would really love to hear what you think about it and see whether or not it is something that can benefit you :relaxed:.

:warning: If you are not interested, feel free to just close this issue and sorry for the inconvenience.

**Comment by chriseth** [comment]
Thanks a lot for the offer, but I think we manage quite fine without it.
