### ISSUE TITLE
[SMTChecker] ICE in solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10461]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
	function f() view {}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(722): Throw in function void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

This is similar to some older initFunction crashes that required more complex inputs.  Must be some newly introduced issue that lacks a detecting test for this simple a variant.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by axic** [comment]
I think this is just because of #9636.

**Comment by agroce** [comment]
Aha.  OK.  Should I ignore all initFunction crashes of this general form from now on?

**Comment by axic** [comment]
May be it is better to do so. @leonardoalt do you have an eta when free functions would be supported?

I think this is the 3rd or 4th reported issue, I hope the lack of support won't cause too much trouble for fuzzing?

**Comment by leonardoalt** [comment]
Supporting that will cause quite a few changes in the CHC code, so I'm trying to bundle some other features that are similar and should change before that refactoring.

**Comment by agroce** [comment]
If the blanket rule of "ignore initFunction" works, then it's not a big burden on fuzzing.  might give us some missed bugs, but my ad hoc triage code's pretty good about handing me just one of any "signature."  Right now, fuzzing is not producing a ton of things, we're pretty clean on AFL runs, other than long-standing stuff like this and FixedPointType being an ICE

**Comment by agroce** [comment]
I imagine that when @rvantonder gets Comby to generate more sophisticated mutants and we throw that at solc, the pace may pick up and the triage burden grow, but I'm not sure when that's on the table.
