### ISSUE TITLE
[isoltest] Add a way to query gas usage

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10474]
As discussed on today's call, a potential way is to have a line similar to `storage:` called `gasUsed: <value>`. This line would refer to the gas usage of the preceding call (including the explicit constructor call).

If there is not preceding call, that is a misformatted expectation. If it is the very first line, would that however count as the constructor cost?

**Comment by ekpyron** [comment]
If it's easier, then checking constructor costs could also only be allowed if there's an explicit ``constructor()`` call in the implementation. [by the way: nice: I hadn't seen the `storage:` thing until now :-)]

**Comment by chriseth** [comment]
approval

**Comment by mijovic** [comment]
What about gas usage in different runs (with IR and with old codegen)?

**Comment by axic** [comment]
> What about gas usage in different runs (with IR and with old codegen)?

I think one needs to duplicate files and explicitly disable specific options, e.g. `compileViaYul: false` is a file for old codegen.

At the start we do not want to run gas tests for every single semantic tests, but rather have a bunch of larger examples which we use.

**Comment by chriseth** [comment]
It might be better to have multiple fields for the different runs, so they can also be compared. It could be multiple lines.

**Comment by mijovic** [comment]
I would prefer it to be in a single file, as we don't need to change enfoce-via-yul feature. We can write two lines in expectations, one for gas usage for old codegen, and one via IR.

**Comment by axic** [comment]
> It might be better to have multiple fields for the different runs, so they can also be compared. It could be multiple lines.

I'd argue if we do that, then we should also consider doing the same for the other flags...

One option could be grouping expectations for different flags, e.g.:
```
// ===
// compileViaYul: false
// ----
// f() -> 0
// gasUsed: 11

// ===
// compileViaYul: true
// ----
// f() -> 0
// gasUsed: 1
```

**Comment by mijovic** [comment]
@axic
That would make sense, as we will also have features that will be supported by both runs, and give different results.

One example is `constructor_inheritance_init_order.sol` from `semanticTests` (returns 0 in old codegen and 42 with new codegen, and both are correct). That way we can also track differences in two implementations in a better way than now.

But than, this should be done in two steps: 
1. splitting expectations and refactoring enforce via yul feature
2. Implementing gasUsed

**Comment by chriseth** [comment]
```
// gas YulOptimized: 11
// gas Yul: 200
// gas Legacy: 20
// gas LegacyOptimized: 900
```

**Comment by mijovic** [comment]
I would start working on this, I can report gas usage as @chriseth suggested, and we can change it later

**Comment by axic** [comment]
In my opinion that is a bad direction and https://github.com/ethereum/solidity/issues/10474#issuecomment-737273506 is a better one to take.

**Comment by ekpyron** [comment]
I was about to argue against https://github.com/ethereum/solidity/issues/10474#issuecomment-737273506 by saying that there are options that don't affect gas costs... but in fact the only option for semantic tests that's generally independent of gas costs is ``allowNonExistingFunctions`` and that's a rarely used exotic one...
``evmVersion`` doesn't fit exaclty either (e.g. gas cost can differ depending on SHL being available), but one could just not use larger sets of evm versions, but restrict to only one evm version per settings block to mitigate that.

So given that, the main drawback of https://github.com/ethereum/solidity/issues/10474#issuecomment-737273506 is the need to repeat the calls, which is not so nice for complex signatures...
I'm not sure myself, though.

In any case: the fact that the selected evm version affects the gas cost will come up using https://github.com/ethereum/solidity/issues/10474#issuecomment-738114865 as is only...

**Comment by axic** [comment]
My proposal is not only useful for this particular use case, but for numerous other settings we have: IR/wasm/evmVersion/abiversion/etc.

Currently we are duplicating files for these.

**Comment by ekpyron** [comment]
Your proposal has been a plan for a while... there's an issue for it I'm sure...

**Comment by ekpyron** [comment]
Maybe not, strange, I was sure... the idea at some point was to also add syntax warnings to semantic tests as one such expectation block...

**Comment by chriseth** [comment]
I would still prefer adding a filter to the gas cost statement instead of repeating all calls.
