### ISSUE TITLE
[SMTChecker] Verify tests counterexamples

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#10478]
Go through all counterexamples added by https://github.com/ethereum/solidity/pull/10477 and check whether they're correct. Open issues for the buggy ones.

**Comment by pgebal** [comment]
This one looks invalid: https://github.com/ethereum/solidity/blob/92f383d8733440688905e2b9201565a8faeaf376/test/libsolidity/smtCheckerTests/control_flow/short_circuit_or_fail.sol#L19
Transaction trace indicates that internal function `f` is called twice and that's not the case.

**Comment by pgebal** [comment]
In `types/enum_explicit_values_2.sol`  test, the counterexample message is valid but a bit misleading. In the output enums are converted to integers.

**Comment by pgebal** [comment]
In `types/string_1.sol` the counterexample doesn't make sense.

```
contract C
{
	function f(string memory s1, string memory s2) public pure {
		assert(bytes(s1).length == bytes(s2).length);
	}
}
// ====
// SMTEngine: all
// ----
// Warning 6328: (77-121): CHC: Assertion violation happens here.\nCounterexample:\n\n\nTransaction trace:\nC.constructor()\nC.f(s1, s2)
```

**Comment by pgebal** [comment]
Rest of the tests are fine, but what caught my attention is that current SMTChecker prints much less counter examples. Looks like we lost >90% of them.

**Comment by pgebal** [comment]
I opened 2 issues:
- https://github.com/ethereum/solidity/issues/14750
- https://github.com/ethereum/solidity/issues/14751
