### ISSUE TITLE
Fix standard-json before it is too late.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#10470]
Maybe a bit of an exaggeration as an issue title ;-), but IMHO we introduced a few inconsistencies in the standard-json interface lately, most prominently https://github.com/ethereum/solidity/pull/10064#issuecomment-737117081.
I think we should either revert https://github.com/ethereum/solidity/pull/10064, since I think the "metadata" argument behind it doesn't actually justify it, or come up with a plan to actually move standard-json towards something for which the metadata argument does hold (i.e. move everything that doesn't end up in metadata ``settings`` out of standard-json ``settings`` e.g. into ``options`` as suggested in https://github.com/ethereum/solidity/pull/10064#issuecomment-737122018).

Related: https://github.com/ethereum/solidity/issues/9583#issuecomment-737102636

**Comment by chriseth** [comment]
All keys in `settings` are related to metadata in the way that they influence the metadata. The property that we absolutely want is that the metadata only contains keys that are necessary to reproduce the same binary and it also contains all such keys. In that way, we could also move it back.

**Comment by ekpyron** [comment]
Neither ``outputSelection``, nor ``stopAfter`` really influence metadata (well, the latter or arguably both maybe in that there *won't* be metadata, if stopped early, but that's a bit of a stretch). So I'd say for consistency we'd either need to move those *out* of ``settings`` or we should move ``modelCheckerSettings`` back in. I'd actually even prefer moving all of it out to ``options`` (@leonardoalt also seems to like that, ref https://github.com/ethereum/solidity/pull/10064#issuecomment-737135890) - but for that we'd probably need to introduce some deprecation mechanism now and only remove the legacy way later - resp. it would be more breaking than just moving the newly added one, that's the main concern about that idea...

**Comment by leonardoalt** [comment]
Having both `options` and `settings` does sound redundant though

**Comment by ekpyron** [comment]
The idea was ``settings`` would be anything that actually affects bytecode, i.e. exactly what would end up in ``metadata``, and ``options`` would be anything else. At least as a goal, but it'd probably have to transition there via deprecation, etc...
