### ISSUE TITLE
[SMTChecker] ICE in compound assignment handler

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10473]
## Description

```
pragma experimental SMTChecker;
contract C {
        function f() public returns (int x) {
                x >>= tx.gasprice;
        }
}
```

throws

https://github.com/ethereum/solidity/blob/afe500e399e76ce88c9dadfd04b616bd5df47c37/libsolidity/formal/SMTEncoder.cpp#L1918

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by leonardoalt** [comment]
@blishko I think this could be related to the latest `assignment` changes. Could you maybe take a look?
