### ISSUE TITLE
[isoltest] Add option to refer external files as sources

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10475]
Currently the test format supports single or multiple files, but they all the sources have to be included in a literal form.

This idea came up on today's call: how about supporting a case pointing to a separate file. This would allow including larger external projects **and** still having the expectations visible, without the need to scroll down thousands of lines.

**Comment by axic** [comment]
The current format is:
```
==== Source: A ====
contract A {}
==== Source: B ====
contract B is A {}
```

How about we make this extremely simple:
```
==== ExternalSource: someDirectory/someFile.sol ====
==== Source: B ====
contract B is A {}
```

The `ExternalSource` points to a relative directory, but rejects any path escaping the current directory (e.g. can descend to sub directories, but cannot go to parents).

**Comment by ekpyron** [comment]
The main problem I see here is: currently isoltest and the boost tests just traverse the entire directories consuming every single file as test file. Would those separate files we point to also be run as their own isolated tests? If not, how would we distinguish them? Placing them into an entirely different directory structure will make it very hard to figure things out... a special file name prefix/suffix/extension? Not sure...

**Comment by axic** [comment]
> Would those separate files we point to also be run as their own isolated tests? If not, how would we distinguish them? 

Those files have no expectations in them so one could ignore such files?

**Comment by ekpyron** [comment]
Having no expectations at the moment still means they have to compile... we could however change that or have some comment-marker in them, indicating that they should not be run as individual test, yes.
(I expect not all of them will even be compilable on their own)

**Comment by chriseth** [comment]
we can add a special comment in the first line of a file to be imported so it is ignored

**Comment by axic** [comment]
> Having no expectations at the moment still means they have to compile...  [...] (I expect not all of them will even be compilable on their own)

That definitely would be the case as they frequently import files.

> we can add a special comment in the first line of a file to be imported so it is ignored

Sounds good.

**Comment by axic** [comment]
Should we allow remappings?
```
==== ExternalSource: ../zeppelin/SafeMath.sol=someDirectory/someFile.sol ====
==== Source: A ====
import "../zeppelin/SafeMath.sol";
contract B is A {}
```

**Comment by axic** [comment]
@aarlt this is the issue we discussed regarding the next priority for isoltest
