### ISSUE TITLE
Force fallback method to be external

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1048]
I wonder which visibility modifiers make sense for the fallback method, because right now it accepts any of them.

It is only executed externally (and cannot be easily called from the contract), so it should default to `external`. Probably it shouldn't allow any modifiers.

Perhaps somehow `internal` could make sense, when a child contract implements the fallback and calls the parent fallback.

**Comment by chriseth** [comment]
There is no way to call the parent fallback from the child. I see no real reason to mark it anything apart from external.

**Comment by axic** [comment]
By force also mean to raise an error if any other visibility modifier is added.

Should we just outright disallow any modifier?
