### ISSUE TITLE
2 Compiler Errors in solc 0.7.5 version, triggered by three contracts

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#10502]
## Description

Hello to everyone, I found 2 unique crashes, triggered by four solidity contracts in solc compiler version 0.7.5 that Superion, AFL and Mopt could not found .

1. Internal Compiler error in :

https://github.com/ethereum/solidity/blob/afe500e399e76ce88c9dadfd04b616bd5df47c37/libsolidity/formal/SMTEncoder.cpp#L722

"Triggered" by contracts (a), (b), (c) :

(a)
pragma experimental SMTChecker;	function f()pure {
		ufixed a = uint64(1) + ufixed(2);
}

(b)
pragma experimental SMTChecker;

contract K {}
	function f() pure {
		(abi.encode, "");
}

(c)

pragma experimental SMTChecker;
contract C {
	function f(bytes calldata x, uint y) external pure {
		x[8][0];
		x[8][5*y];
	}
}

2. Internal Compiler Error :
Unknown exception during compilation: stoul, out of range.

"Triggered" by contract :

pragma experimental SMTChecker;
contract C {
	function f(bytes calldata x, uint y) external pure {
		x[8][0];
		x[8][5*y];
	}
}

## Environment

- Compiler version: 0.7.5
- Target EVM version (as per compiler settings): 0.7.5+commit.eb77ed08
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 16.04 Xenial

## Steps to Reproduce

solc <contract_number>

**Comment by axic** [comment]
Crash 1.a and 1.b are well known, due to #9636.

1.c and 2 seems to be the same contract?

**Comment by chamitro** [comment]
Yes sorry, 1c and 2 are the same.

**Comment by axic** [comment]
Crash 2 seems like a good find! It is happening within z3. Perhaps we send a ill-formatted query, but it still shouldn't crash.

**Comment by chamitro** [comment]
1c is the contract below:

pragma experimental SMTChecker;  function f( ){}

Again triggering 
https://github.com/ethereum/solidity/blob/afe500e399e76ce88c9dadfd04b616bd5df47c37/libsolidity/formal/SMTEncoder.cpp#L722

**Comment by blishko** [comment]
The contract 2 does not crash anymore. Fixed as part of #10510, the problem was in processing the model from Z3 to create the counter-example report.

**Comment by axic** [comment]
@blishko should have added a (previously) crashing test case -- can you do that?

With that in place I'd close this issue, as issue 1 is essentially a "duplicate" of #9636.

**Comment by blishko** [comment]
@axic , I can do that. The crash occurred already in the test suite we have, after I had extended the CEX computation to structs. I only later checked that the source of crash in the example from this issue was the same.
