### ISSUE TITLE
[Constant evaluator] Segmentation fault in convertType()

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10505]
## Description

```
int[L] constant L= 6;
```

leads to an invalid read here

https://github.com/ethereum/solidity/blob/06bca652225fe8b12f6ce7b72bb525d6dbad603a/libsolidity/analysis/ConstantEvaluator.cpp#L232

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
This is wild.
