### ISSUE TITLE
Run SMT (or all) tests in absence of solvers to check the smtlib interface.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#10519]
Doing so would have caught https://github.com/ethereum/solidity/issues/10436, resp. https://github.com/ethereum/solidity/pull/10494

We can either add some special run for this or we can just not skip the tests entirely if there is no solver, but just ignore the expectations.

(ping @leonardoalt for additional comments, if any)

**Comment by ekpyron** [comment]
We could actually run *all* our test files in general with the smtlib engine - it should be fast enough and would catch ICEs in the encoding part at least.

**Comment by cameel** [comment]
Running it on all tests will also be much easier when we replace the pragma with a command-line flag.

**Comment by cameel** [comment]
Should we reopen this? Seems simple enough, we already have the CLI flag and also it's an SMT issue (and we wanted to exclude these, though most of them are not labeled).

**Comment by ekpyron** [comment]
Stop trying to rescue issues :-).
