### ISSUE TITLE
formal verification: reconsider `mutable` in `mutable var : array T`

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1051]
In Why3, `array` contents are already mutable without the `mutable` keyword, so `mutable var : array T` makes sense only when the length of the array is changed at runtime.  If the array contents are changed but the array length is not changed, `var : array T` is enough.

This issue keeps track of cleaning the `mutable` keyword when the length is known (when the Why3 array appears as a translation of `mapping (address => _)` in Solidity; or deciding not to do that.

**Comment by axic** [comment]
There's no keyword in Solidity yet to disallow the extension of an array. Unless we introduce one (`immutable` / `constant` / `fixed` arrays), Why3 always needs the `mutable` keyword.

**Comment by pirapira** [comment]
@axic When I translate a `mapping (address => X)` (in Solidity) into an `array X` (in Why3), the length of the array can be fixed at `2 ** 160`.

**Comment by pirapira** [comment]
I realized I didn't mention the `mapping` thing in the description.  I updated it.

**Comment by axic** [comment]
@pirapira well in that case, regular arrays should have the upper limit of `uint256` `(2 ** 256)`.

**Comment by pirapira** [comment]
@axic If we do that, Why3 will not check out-of-bounds access for regular arrays.  For regular arrays, I want to keep the same array length in Solidity and in Why3.

**Comment by axic** [comment]
@pirapira do you maintain the length field in a similar way as in the EVM bytecode?

**Comment by pirapira** [comment]
@axic I think yes.  A Why3 array maintains a length field before the array contents.  The array contents are by default declared mutable, but the length field is not.

**Comment by axic** [comment]
@pirapira yes, actually we do have fixed arrays, where the length is defined upfront and is immutable. I wonder if the Why3 code works properly for dynamic arrays too (where the length field is mutable)?

**Comment by pirapira** [comment]
@axic Yes, in Why3, if you say `mutable arr : array byte`, the length of `arr` can be changed during execution.  If you drop `mutable` and say  `arr : array byte`, the length is fixed, but the array content can still be changed during execution.

**Comment by pirapira** [comment]
Currently array types like `uint []` cannot be translated into WhyML, so I created #1054 about it.

**Comment by chriseth** [comment]
memory arrays (the only ones implemented for why3) cannot change their lengths in solidity after they have been constructed.

storage arrays cannot be translated to why3 yet.

**Comment by pirapira** [comment]
Thank you for the information.

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
