### ISSUE TITLE
[SMTChecker] ICE in const solidity::frontend::VariableDeclaration *solidity::frontend::SMTEncoder::identifierToVariable(const solidity::frontend::Expression &) const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10521]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
uint256 constant x = 56;
enum ActionChoices {GoLeft, GoRight, GoStraight, Sit}
ActionChoices constant choices = ActionChoices.GoRight;
bytes32 constant st = "abc\x00\xff__";
contract C {
    function i() public returns (uint, ActionChoices, bytes32) {
	return (x, choices, st);
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(2386): Throw in function const solidity::frontend::VariableDeclaration *solidity::frontend::SMTEncoder::identifierToVariable(const solidity::frontend::Expression &) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

```

when compiled with solc.

On master, using AFL fuzzing.  **Another discovery using https://github.com/agroce/afl-compiler-fuzzer,  a bit indirectly:  I took every test in my corpus I use to start fuzzing, and add the SMT checker pragma to any that lacked it, then ran triage and minimized the tests (so they aren't exactly the corpus tests + SMT checker pragma).  I think I have quite a few bugs to report here, and it might be a good idea to add something to automatically do this to tests!**

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by agroce** [comment]
See the bold part -- this is a result of systematically injecting "pragma experimental SMTChecker;" in the existing tests, where not present.  I'm triaging a number of others that found.  I noticed several fuzzer finds were just inserting the SMTChecker pragma.

**Comment by leonardoalt** [comment]
Thanks @agroce ! Which tests do you mean by `in the existing tests`?

**Comment by agroce** [comment]
Oh, sorry.  For me, this means specifically every .sol file under the "solidity/test/libsolidity" hierarchy.  I crawl and grab those for every fuzzer start on a new version of solc.

**Comment by leonardoalt** [comment]
Right, that's also what I assumed.
I often do the same, and last time I did that I only caught exceptions from free functions. I assume this one is because of the global constant.
