### ISSUE TITLE
[SMTChecker] ICE in const solidity::frontend::Block &solidity::frontend::ModifierDefinition::body() const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10523]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
abstract contract A {
    function f() public mod returns (bool r) {
    }
    modifier mod virtual;
}
contract C is A {
    modifier mod override {
        if (false) _;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/AST.h(1031): Throw in function const solidity::frontend::Block &solidity::frontend::ModifierDefinition::body() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer,  a bit indirectly:  I took every test in my corpus I use to start fuzzing, and add the SMT checker pragma to any that lacked it, then ran triage and minimized the tests (so they aren't exactly the corpus tests + SMT checker pragma).

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
A smaller repro

```
pragma experimental SMTChecker;
abstract contract A {
  function f() public mod {}
  modifier mod virtual;
}
```

I think the issue here is the assumption that modifiers have a body coming from here (for this test case)

https://github.com/ethereum/solidity/blob/6fe3e0116c71b344f191bd684d20f70506684af0/libsolidity/formal/SMTEncoder.cpp#L2567
