### ISSUE TITLE
[SMTChecker] Segmentation fault for solc and solfuzzer in solidity::frontend::CHC::internalFunctionCall

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10526]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    uint[] data;
    function f(uint x, uint[] calldata input) public returns (uint, uint) {
        (uint a, uint[] calldata b) = fun(input, data);
    }
}
function fun(uint[] calldata _x, uint[] storage _y) view  returns (uint, uint[] calldata) {
	return (_y[0], _x);
}
```

produces:

```
Segmentation fault
```

gdb claims it's here:
```
Program received signal SIGSEGV, Segmentation fault.
solidity::frontend::CHC::internalFunctionCall (this=0x7ffe15cd9be0, _funCall=...) at /home/user/solidity/libsolidity/formal/CHC.cpp:561
561			if (contract->isLibrary())
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  Again, indirectly via adding SMTChecker pragmas to existing tests, then triaging/reducing.

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for reporting the issue @agroce !

**Comment by bshastry** [comment]
@leonardoalt turns out that CHC assumes internal function calls to always belong to a contract

https://github.com/ethereum/solidity/blob/6fe3e0116c71b344f191bd684d20f70506684af0/libsolidity/formal/CHC.cpp#L576

Here, the internal function called is actually a free function and hence `contract` pointer is null. So in some ways this could be a sub issue of https://github.com/ethereum/solidity/issues/9636

**Comment by bshastry** [comment]
Please note that this could be reproduced via a much simpler test case like so

```
pragma experimental SMTChecker;
contract C {
  function g() external {
    f();
  }
}
function f() {}
```

If the free function were to be declared before the contract, it would trigger #9636 , so perhaps a temporary fix would be to not perform analysis if a free function is present anywhere in source?

**Comment by leonardoalt** [comment]
@bshastry Yes, free functions are not supported at all, an this used to be a correct assumption.

**Comment by leonardoalt** [comment]
That could be a quick fix, but would that be better?

**Comment by bshastry** [comment]
> That could be a quick fix, but would that be better?

Better only in the sense that it would save the time spent on triaging known issues. But of course I'm not really sure if the "temporary fix" of ignoring free functions is actually a good suggestion. Perhaps throw a warning that free functions are not supported?

**Comment by axic** [comment]
@leonardoalt as a quick fix can you add an assertion and lump this under #9636?

And move this test case to #9636.

**Comment by leonardoalt** [comment]
@axic why would an assertion help? I think if anything @bshastry 's idea to just detect free functions/constants and abort then with a warning.

**Comment by axic** [comment]
A warning is of course nicer, but I thought you did not want to do that, since you didn't in the past 2-3 months since all these free function issues started to appear :wink:

**Comment by leonardoalt** [comment]
Now it started to be too annoying :p
And blocking fuzzers
