### ISSUE TITLE
[SMTChecker] ICE in smtutil::Expression solidity::frontend::SMTEncoder::compoundAssignment(const solidity::frontend::Assignment &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10522]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function f(int256 a, uint256 b) public returns (int256) {
        a >>= b;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1918): Throw in function smtutil::Expression solidity::frontend::SMTEncoder::compoundAssignment(const solidity::frontend::Assignment &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer,  a bit indirectly:  I took every test in my corpus I use to start fuzzing, and add the SMT checker pragma to any that lacked it, then ran triage and minimized the tests (so they aren't exactly the corpus tests + SMT checker pragma).

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
This looks like a duplicate of #10473
