### ISSUE TITLE
formal verification: Why3 error message on mappings to mappings

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1053]
In #1045 the translation of `mapping (address => uint256) balance;` is designed to be

```
mutable balance: array uint256
```

Then naturally `mapping (address => mapping (address => uint256)) allowance` would be translated to

```
mutable allowance: array (array uint256)
```

When I try this Why3 syntax, I get an error message `Cannot update values of type (map int (array <rho> uint256))` at the signature of `external_call`.

```
$ cat solidity.mlw
module UInt256
    use import mach.int.Unsigned
    type uint256
    constant max_uint256: int = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    clone export mach.int.Unsigned with
        type t = uint256,
        constant max = max_uint256
end

module Contract_Token
    use import int.Int
    use import ref.Ref
    use import map.Map
    use import array.Array
    use import int.ComputerDivision
    use import mach.int.Unsigned
    use import UInt256
    exception Revert
    exception Return
    type state = {
        mutable _balance: array (array uint256)
    }
    type account = {
        mutable balance: uint256;
        storage: state
    }
    val external_call (this: account): bool
        ensures { result = false -> this = (old this) }
        writes { this }
end
$ why3 ide solidity.mlw
Error while opening session:
File "solidity/../solidity.mlw", line 29, characters 1-109:
Cannot update values of type (map int (array <rho> uint256))
$ why3 $ why3 --version
Why3 platform, version 0.87.2
```

This issue keeps track of what this error message is telling, and how to solve the problem.

@chriseth This is one example where extraction to WhyML is harder than to EVM.  WhyML has more constraints than EVM, so it's a harder translation target.

**Comment by chriseth** [comment]
Just a hunch, but perhaps it would help to define a struct with a mutable member:
`type array_internal = { mutable data: array uint256 }`
and then use `mutable allowance: array array_internal`

**Comment by mrsmkl** [comment]
Supposedly arrays of arrays won't work to prevent aliasing: https://lists.gforge.inria.fr/pipermail/why3-club/2012-September/000394.html

**Comment by pirapira** [comment]
Thank you for the insight.  For C++ programmers, the problem is here is, might be multiple pointers pointing to the same array and a single assignment might appear to change multiple arrays at the same time. Then
- a) intermediate structs will not solve the problem,
- b) immutable arrays might be nestable (though that complicates the Why3 translation of `set` operations; we'll need something like lenses).

The link above suggests (c) defining a `Matrix` type, but that approach can become arbitrarily complicated.  For instance, translation of arrays containing structs containing arrays, would be a bit involved.

**Comment by pirapira** [comment]
d) Another solution is to move closer to EVM because EVM has only one-dimensional arrays (memory and storage).  In this case, we need to model the assumption about hash collision (because currently `solc` uses a hash function to encode nested arrays into a one-dimensional array).

**Comment by pirapira** [comment]
e) Yet another solution is to model the notion of lvalues.  The state would be modeled as a mapping from `lvalue` to `values`.  `arr[0][1]` would be an `lvalue`, and the associated `value` can be `Uint256 40`.

**Comment by pirapira** [comment]
F\* does not out-right reject types that might cause aliasing, but try to infer about it (see 10.2 of [F\* Tutorial](https://www.fstar-lang.org/tutorial/)).

**Comment by pirapira** [comment]
At least F\* does not complain about

```
module MapMap

type t = Map.t int (ref (Map.t int (ref int)))
```

**Comment by axic** [comment]
Obsoleted by #2195.

**Comment by axic** [comment]
@pirapira can we close this?

**Comment by pirapira** [comment]
Yes.
