### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1055]
We've discussed this on Gitter and I thought it is useful summarising it here.

Currently the nightly version after a release doesn't change the version number, only the prerelease tag.

I propose the versioning to be the following:
- 1) after a release, the version is bumped a patch level (i.e. 0.3.6 release -> 0.3.7 nightly), because we assume only patch level (non-breaking, non-feature) changes follow
- 2) when changes are merged, the version changes according to semver rules (i.e. breaking change, 0.3.7 -> 0.4.0)
- 3) a release is made with the current version of the nightly

This means that accordingly to nightly builds, one might see version numbers which never will be released (in the above case 0.3.7).

This is also aligned with the version pragma.

**Comment by chriseth** [comment]
Agreed. Do you want to put this into the documentation somewhere, so we can close this issue?
