### ISSUE TITLE
Fixed size array is not fixed  

### ISSUE THREAD

**Issue by EmanHerawy** [ethereum/solidity#10559]
## Description

Fixed-size array should be fixed not dynamic.  in the below code I can change the size after deploying the contract.

- Compiler version:
- Target EVM version (as per compiler settings): tested on 0.5, 0.6 & 0.7
- Framework/IDE (e.g. Truffle or Remix): Remix 
- Operating system: Ubuntu

## Steps to Reproduce

```solidity
pragma solidity ^0.7.5;

contract FixedSizeArray{
    

    // referance type
   
    uint256[] public myFixedArray = new uint256[](3); // or uint [] balance = [1, 2, 3];



    function addToArray(uint256 val) public {
     myFixedArray.push(val);
    }

       function removeToArray() public {
     myFixedArray.pop();
    }
    function addToArrayByIndex(uint256 val, uint index) public {
     myFixedArray[index]=val;
    }

   
    
}

**Comment by chriseth** [comment]
Solidity only offers two kinds of storage arrays:
 - arrays whose size is known and fixed at compile time
 - arrays whose size can be changed

Are you proposing to add a new array type whose size is not fixed at compile time, but cannot be changed after it has been assigned for the first time? Would you also allow changes to the values of the array?

**Comment by EmanHerawy** [comment]
Thanks, @chriseth for your decent reply.
I'm proposing the opposite, If I have declared a fixed-size array at compile-time, this size can't be changed after that ( like what we have in c# for example)  or at least a way to make it fixed if I want by adding a reserved keyword or so

**Comment by chriseth** [comment]
@EmanHerawy `uint256[3] public myFIxedArray;' does not suit you?

**Comment by EmanHerawy** [comment]
@chriseth  I can change the size on runtime; I can add/remove more items on runtime.  so it's no longer fixed " it's dynamic on runtime"

**Comment by chriseth** [comment]
If you use `uint256[3]`, then you cannot change the size.

**Comment by EmanHerawy** [comment]
@chriseth oh, sorry I got it wrong I was using  
`  uint256[] public myFixedArray = new uint256[](3);`
not 
`uint256[3],`
Sorry for my confusion and thanks for your help :)
