### ISSUE TITLE
[fuzzing] Build fuzzers only on b_ossfuzz and clean them up

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10573]
Some fuzzers are built on every CI run, while others only on `b_ossfuzz`. Because of this the libfuzzer headers are not available and we have to resort to manual prototypes. Would be nice to only build all the fuzzers on `b_ossfuzz` and clean them up from warnings (such as `-Wno-sign-conversion`, etc).

_Originally posted by @axic in https://github.com/ethereum/solidity/pull/10537#discussion_r540467310_

**Comment by ekpyron** [comment]
We could by the way also enable all the warnings for the fuzzing builds, if we used cmake's mechanism to declare declare the offending generated headers as ``SYSTEM`` headers, for which warnings will be ignored.

**Comment by axic** [comment]
Copying this message by @bshastry from #9370:
> There may be things that may be redundant in the ossfuzz cmake file e.g., include directive. See https://github.com/ethereum/solidity/pull/8305#discussion_r452083965 for context
