### ISSUE TITLE
Using this in the constructor should be an error

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1057]
Since `this` is 0 in the constructor, there's little point using it. It should be a straight error condition.

**Comment by chriseth** [comment]
`this` is the address of the contract, it is usable, especially to set up callbacks. We should report an error if someone attempts to call a function of the contract being created, but there is an issue for that.

**Comment by axic** [comment]
True, even with the new address generation it should be available upfront.

The warning issue is this: #583.
