### ISSUE TITLE
[testing] Replace init_unit_test_suite with (global) fixture

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10574]
It seems to be obsolete: https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/boost_test/adv_scenarios/obsolete_init_func.html

And (global) fixtures is one suggested option: https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/boost_test/tests_organization/fixtures/global.html

_Originally posted by @ekpyron in https://github.com/ethereum/solidity/pull/10537#discussion_r540108689_

**Comment by ekpyron** [comment]
Or alternatively: replace boost tests entirely with something simpler ;-).

**Comment by axic** [comment]
Duplicate of #4730.
