### ISSUE TITLE
[SMTChecker] ICE in void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10600]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function g(bool b) public pure returns (uint, uint) {
    }
    function f(bool b) public returns (uint x, uint y, bytes memory txt) {
	if (0==1)
            try this.g(b) returns (uint a, uint b) {} catch (bytes memory s) {
		txt = s;
            }
    }
}
```

produces:

```
Internal compiler error during compilation:
/solidity/libsolidity/formal/SMTEncoder.cpp(2266): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.12.14+commit.e21be30d.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for reporting the issue @agroce . At first glance, this looks like a variant of https://github.com/ethereum/solidity/issues/8817 only in that the failing assertions are similar.

Minimised test case

```
pragma experimental SMTChecker;
contract C {
  function g(bool b) public {}
  function f(bool b) public returns (bytes memory txt) {
    if (0==1)
      try this.g(b) {}
      catch (bytes memory s) {
        txt = s;
      }
  }
}
```

**Comment by leonardoalt** [comment]
My guess is that this is because `try/catch` blocks are not visited which cases the SSA indices to be different at the end of the blocks.
