### ISSUE TITLE
[ewasm] Revise `internal_to_i32ptr` polyfill

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#10634]
As of now `internal_to_i32ptr` is implemented as:
```
function to_internal_i32ptr(x1, x2, x3, x4) -> r:i32 {
	let p:i32 := u256_to_i32ptr(x1, x2, x3, x4)
	r := i32.add(p, 64:i32)
	if i32.lt_u(r, p) { invalid() }
}
```
This function is adding an offset of `0x40` to the supplied address.  It is used everywhere where the "user" interacts with memory. 

It is probably a bit confusing, especially if the memory is viewed by external tools like debuggers. For the "user" the memory operations are transparent: `mstore(0, ..)` and `mload(0)` will refer to the same address in memory. But if external tools are used, an `mstore(0, ..)` will result in a write to address `0x40`. This may confuse users, especially because there is not such offset in place in the `evm` case.

**Comment by chriseth** [comment]
How would you do it differently? We need some scratch space to put the arguments for the external interface calls.

**Comment by axic** [comment]
It could do save/restore, such as:
```
let saved1 = i64.load(<addr>)
let saved2 = i64.load(<addr + 8>)
let saved3 = i64.load(<addr + 16>)
let saved4= i64.load(<addr + 24>)
// clobber [addr, addr + 32]
i64.store(<addr>, saved1)
i64.store(<addr + 8>, saved2)
i64.store(<addr + 16>, saved3)
i64.store(<addr + 24>, saved4)
```

Not sure if the optimiser could deal with this, but seems like quite a bit of overhead.

**Comment by NunoFilipeSantos** [comment]
We're closing all wasm issues for now.
