### ISSUE TITLE
Implicit and "free" casting for like-types

### ISSUE THREAD

**Issue by deluca-mike** [ethereum/solidity#10649]
## Abstract

Implicitly casting of `bytes32` to `uint256`, and vice versa, ~~without the compiler doing any (if currently the case) bitwise operations, like AND-masking against 256 one's.~~ (this was incorrect)

## Motivation

Would be nice to handle and pass around arrays of bytes32 (i.e. for merkle trees and whatnot) but be able to cleanly handle the underlying data as numbers.
Consider a Merkle Tree library that works with `bytes32` elements (i.e. `bytes32[] memory elements`), where all of most elements are actually meant to be (or best) interpreted as numbers by the underlying contract/application.

Also, would be nice to reuse `bytes32` and `uint256` values as a mechanism to avoid `STACK TOO DEEP` errors, within a function, without having to cast back and forth. ~~If I am not mistaken, casting between `bytes32` and `uint256` incurs a slight cost, despite it not needing to.~~ (I was incorrect)

## Specification

Consider this, albeit convoluted, example.

This:

```
function get_a(uint256) returns (bytes32);
function get_b(uint256) returns (uint256);
function get_c(bytes32) returns (uint256);
function get_d(bytes32) returns (bytes32);

function foo(bytes32[] memory elements) returns (uint256 unique_id) {
    bytes32 a = get_a(elements.length);
    uint256 b = get_b(a);
    bytes32 c = get_c(b);

    for (uint256 i; i < elements.length; ++i) {
        elements[i] |= (a ** i) | (b * i) ^ (c + i) & (get_d(i) ^ i);
    }

    return get_merkle_root(elements);
}
```

Rather than this:

```
function get_a(uint256) returns (bytes32);
function get_b(uint256) returns (uint256);
function get_c(bytes32) returns (uint256);
function get_d(bytes32) returns (bytes32);

function foo(bytes32[] memory elements) returns (uint256 unique_id) {
    uint256 a = uint256(get_a(elements.length));
    uint256 b = get_b(a);
    uint256 c = get_c(bytes32(b));

    for (uint256 i; i < elements.length; ++i) {
        elements[i] = bytes32(uint256(elements[i]) (a ** i) | (b * i) ^ (c + i) & (uint256(get_d(bytes32(i))) ^ i));
    }

    return uint256(get_merkle_root(elements));
}
```

## Backwards Compatibility

This would be backwards compatible as its a relaxation of the rules. Perhaps just a warning of info when implicit casting is detected?

**Comment by chriseth** [comment]
If I understand you correctly, you are saying that `bytes32(x)` (for `x` being of `uint256` type) generates an `and` instruction, even though it is not necessary. Is that correct?

Is the `and` operation removed when you activate the optimizer?

**Comment by deluca-mike** [comment]
Let me do some tests and report back shortly.

To be clear, at least half the feature request is about code readability via implicit casting of types that are the exact same size/bits on the stack. This is especially useful in a "world" where you can only access the last 16 stack slots, allowing you to reuse like-type variables without ugly casting, as per my above example.

**Comment by deluca-mike** [comment]
Ok, did some tests, and gas differences are not attributed to casting "like-types". So I guess this feature request is now just about implicit casting for cleaner code.

**Comment by chriseth** [comment]
Ok, then going back to the other part of the issue: You would like all operators available to uint to also be available to bytes32 and vice-versa? I think this would create too much confusion. `x * 2` for `x` being `bytes32` for example could mean to concatenate `x` with itself. Furthermore, I think your code does quite some unusual things where it is good to add some warning signs in the form of explicit type conversions.

**Comment by deluca-mike** [comment]
👍
