### ISSUE TITLE
formal verification: introduction of @why3-header pragma

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1064]
In `develop`, `/// @why3 ...` comments in the beginning of `.sol` files are used for describing the invariants of the following contract.  As a result, `solc --formal --output-dir tmp` translates these comments into somewhere in the middle of the generated `tmp/solidity.mlw` file.

Sometimes, a user wishes to have a prefix in `.mlw` files, like library imports and custom lemmata.  For this purpose, this issue prposes a new pragma `/// @why3-header ...`.

The lines beginning with `/// @why3-header` are collected in order, and reproduced in the generated `.mlw` file.

**Comment by chriseth** [comment]
Another possibility would be to have the generic format of `/// @why3 <keyword> <rest>` and the keyword might be a direct why3 keyword like `ensures` and so on, or a custom addition like `header` or `contract-invariant`.

**Comment by pirapira** [comment]
Then I'll design something in the frame of `/// @why3 <keyword> <rest>`.

**Comment by pirapira** [comment]
I'm thinking about an annotation scheme like:

```
/** @why3 file-prelude

(* Someting to be placed at the top of token.mlw. *)

 */

/// @why3 contract-state invariant { to_int self.storage._balance[0] = 3 }
/// @why3 contract-state (* applies to [type state] *)

/// @why3 contract-members ensure  { true }  (* applies to every member function *)
/// @why3 contract-members require { false } (* applies to every member function *)
contract Token
{
    mapping (address => uint256) balance;

    ///@why3 next-member ensure { to_int self.storage.length = max_address + 1 }
    ///@why3 next-member (* applies to the member element immediately below *)
    function transfer(address _from, address _to, uint256 _val)
    {
        if (balance[_from] < _val)
            throw;
        /// @why3 here assert { balance[_from] >= _val };
        /// @why3 here (* printed as soon as seen. *)
        balance[_to] += _val;
        balance[_from] -= _val;
    }
}
```

**Comment by pirapira** [comment]
I'm not following this path personally.  Removed my assignment.
