### ISSUE TITLE
[SMTChecker] SMT logic error in std::string solidity::smtutil::SMTLib2Interface::toSmtLibSort(const solidity::smtutil::Sort &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10658]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    uint[3] sarr;
    function f() view public {
        uint[3] memory arr;
        bytes32 h = keccak256(abi.encodePacked(this.f, arr, sarr));
    }
}
```

produces:

```
SMT logic error during analysis:
/solidity/libsmtutil/SMTLib2Interface.cpp(248): Throw in function std::string solidity::smtutil::SMTLib2Interface::toSmtLibSort(const solidity::smtutil::Sort &)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Invalid SMT sort
[solidity::util::tag_comment*] = Invalid SMT sort
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.1-develop.2020.12.18+commit.72efdd3e.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thanks for reporting the issue @agroce 

Another variant for the same assertion failure is

```
pragma experimental SMTChecker;
contract C {
        function f() public {
                (abi.encode(this.f));
        }
}
```
