### ISSUE TITLE
[codegen] ICE because function item stored but target not equal to source

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10667]
## Description

```
contract C {
  function()[] x;
  function f() public {
    function() view[] memory xmem;
    x = xmem;
  }
}
```

throws

https://github.com/ethereum/solidity/blob/67712d50ba2de411fe781e7f6385ad1ceee155d5/libsolidity/codegen/LValue.cpp#L305

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by axic** [comment]
Still happens on develop.
