### ISSUE TITLE
formal verification: allow write access to mapping[idx]

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1066]
After PRs #1045, #1047 and #1063, when a Solidity program writes into a mapping by index notation, --formal option fails. This issue keeps track of translating the mapping access in a reasonable way so that it works on the following example.

Example:

```
$ cat index_write.sol 
contract IndexAccess
{
        mapping (address => uint256) balance;

        function write(address _addr)
        {
                balance[_addr] = 4;
        }
}
$ ./build-develop/solc/solc --formal index_access.sol 
index_access.sol:7:10: Error: Index access only supported for arrays.
                return balance[_addr];
                       ^------------^
```

**Comment by pirapira** [comment]
This is working in a [branch](https://github.com/pirapira/solidity/tree/token_head), but the PR for this will not appear until #1045 and so on is merged.

**Comment by pirapira** [comment]
I'm not following this path personally.  Removing my assignment.

**Comment by chriseth** [comment]
I think those stories can all be closed.
