### ISSUE TITLE
Make `this` behave more closely to how it behaves in all other languages.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#10674]
## Abstract
Change the semantics of `this` to match other object oriented languages.  `this.member` would reference a storage slot of the current contract and `this.function` would do an internal call of the given function.  If one wants to force an external call of a member function then typecasts can be used like:
```sol
contract Apple {
	function banana() {}
	function cherry() {
		Apple(address(this)).banana();
	}
}
```

## Motivation
Currently, `this.member` doesn't work and `this.function` works but has a surprising behavior of calling `function` externally.  This is confusing for new users since this behavior doesn't align with other languages the user is likely familiar with.  It also causes problems because there is no way to differentiate between a local variable and a member variable like in the following example:
```sol
contract Apple {
	address owner;
	constructor(address owner) {
		owner = owner;
	}
}
```
It is very rare that someone intentionally wants to force an external call of a member function because doing so comes with significantly increased costs.  Rather than having such functionality be the surprising default, instead doing such things should require extra effort (like casting).

## Specification
`this.member` compiles to the same thing as `member`.
`this.function(...)` compiles to the same thing as `function(...)`.

## Backwards Compatibility
This is a breaking change that will cause contracts that were previously using `this.` to force external function calls to no longer have the same behavior.  Thus, this change should occur as part of a major version bump.  Alternatively, `this.` could be deprecated now, and then in one or more major versions in the future it can be re-introduced with the new semantics.

**Comment by chriseth** [comment]
I do see the confusion with other languages, but what you are essentially suggesting is a second way of accessing items that are already accessible directly. Note that local variables and state variables can already be disambiguated:
```
contract Apple {
	address owner;
	constructor(address owner) {
		Apple.owner = owner;
	}
}
```

`this` is indeed used almost never for external function calls, but I think that the type of `this` would be naturally expected to be `Apple`.

So to summarize: The confusion stems from the distinction between internal and external calls, and maybe we should solve that in a completely different way?

**Comment by MicahZoltu** [comment]
I did not know that you could reference members like that!  Given that information, perhaps the right solution is to just remove the `this.` functionality entirely for now and create some new mechanism for forcing external calls?  I personally think they are rare enough that `Apple(address(this)).banana()` is acceptable, but if others disagree I'm not opposed to something like `externalThis.banana()` or `external.banana()`.  The goal is that it is abundantly clear that you are making an external call.

I *still* stand by my claim that most users of Solidity will expect `this.owner` and `this.banana()` to work, but given that there is already a way to achieve that, I can appreciate being in no hurry to change the behavior of `this` on users.

**Comment by leonardoalt** [comment]
I do relate to the feeling that new users would expect `this.owner` and `this.banana()` to work as what we call `internal calls`, but I don't see a new way that is clearly better than the current way right now.
In my opinion, the non-`this` cases are very clear currently:
- If you use a typename in a state var access or function call, it's an internal read/call. Examples: `B.x`, `B.f()`
- If you use a contract *instance* in a function call, it's an external call. Examples: `C c = new C(); c.f()`
Since `this` is an `instance` of the contract, I'd say the current way is precise. This of course doesn't solve the initial problem of people being confused. Therefore I would also be fine with removing the word `this` entirely and adding some other way of calling the contract itself externally, which is not very common but exists.
