### ISSUE TITLE
Convert certain `and(mul(a, b), mask)` and `and(add(a, b), mask)` into `mulmod(a, b, x)` and `addmod(a, b, y)`

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10687]
For example the following solidity snippet

```solidity
uint160 a, b;
unchecked { a + b }
```

would be converted into (by the optimizer)

```
let _1 := sub(shl(160, 1), 1)
let value := and(mul(a, b), _2)
```

Here `_1` is a shorter representation of the constant.

Instead the more optimized version would be
```
let _1 := shl(160, 1)
let value := mulmod(a, b, _1)
```

It is shorter and avoids a `sub`. `and + mul` has the same gas as `mulmod`.

Similarly, for `addmod`, but `add + and` is `6`, and `addmod` is `8`. We save a `sub`. So total saving of `2` gas and shorter deploy code.

---------

It maybe easier to implement this as a rule `and(mul(X, Y), A) -> mulmod(X, Y, 2**N)` where `A = 2**N - 1`. Similarly, for the other?

**Comment by chriseth** [comment]
This sounds good in general, but I'm a bit concerned about this transform destroying some other potential opportunities.

**Comment by AnandK-2024** [comment]
sound looks interesting, I will want to take this issue.  please guide me.

**Comment by pv2k** [comment]
Hey, can I work on this one?

**Comment by chriseth** [comment]
@pv2k I'm still not sure if this is a good idea. If you want a similar issue, maybe https://github.com/ethereum/solidity/issues/5810 could be good to work on.
