### ISSUE TITLE
Convert certain mod(mul(X, Y), A) into mulmod(X, Y, A)

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10688]
If `A` is a constant that divides `2**256` (so basically of the form `2**N`), then the two expressions should be the same. `mod(mul(X, Y), A)` costs 10 and `mulmod(X, Y, A)` costs `8` (excluding the shorter deploy code.)

**Comment by hrkrshnn** [comment]
May also be worth considering converting `mod(add(X, Y), A)` into `addmod(X, Y, A)` where `A` divides `2**256`. Also if we can prove that `add(X, Y)` does not overflow, then the both expressions would be the same for any `A` (doesn't have to divide `2**256`)

**Comment by KyleSmith19091** [comment]
Hi I have been looking at this issue for a while now, where would this be added or changed? I am guessing it is in the optimiser package?

**Comment by hrkrshnn** [comment]
@sKorpion19091 It should be in libevmasm/RuleList.h. Feel free to ask in https://gitter.im/ethereum/solidity-dev if you have questions.

**Comment by KyleSmith19091** [comment]
Awesome thank you, I will take a look!

**Comment by hrkrshnn** [comment]
Please note the condition on `A`.

Here are some examples of how similar things were done previously:
- https://github.com/ethereum/solidity/pull/9546
- https://github.com/ethereum/solidity/pull/9566

**Comment by axic** [comment]
What would be interesting is to consider the gas costs in the optimiser. Currently as you have identified, gas wise the above step makes a lot of sense. It may not make sense anymore however if opcodes are repriced. There is indication [here](https://notes.ethereum.org/@poemm/evm384-update5#EVM-Repricing) that repricing may be possible in the future.

**Comment by hrkrshnn** [comment]
@axic Is that relevant for `mulmod` and `addmod`?  Is there a plan to change the cost of these specific opcodes?

I do agree with you in general, that our simplification rules need to be re-looked after any repricing.

**Comment by axic** [comment]
> Is that relevant for mulmod and addmod? Is there a plan to change the cost of these specific opcodes?

Relevant for all opcodes, especially arithmetic opcodes. If any repricing is going to happen, it won't happen for at least 2 hard forks (1 year) I would say, but still good to keep in mind.
