### ISSUE TITLE
[Optimizer] Redundant mstore remover

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10690]
The more `mload`, that we can resolve, it becomes important to remove mstores that are never acessesed. 

In the proxy example (optimized code of proxy.yul from https://github.com/ethereum/solidity/pull/10681/files#diff-a543663ab8a611118fb129bbe24b2def1b3c4c8f79948d42cd61b0d8122d3015)

The two `mstore(64, ...)` is redundant.

```yul
{
    {
        let _1 := 128
        // write to 64, but this is redundant
        mstore(64, _1)
        if callvalue() { revert(0, 0) }
        let _2 := 0
        // does not write to location 64
        calldatacopy(_1, _2, calldatasize())
        // does not write to location 64
        mstore(add(_1, calldatasize()), _2)
        // does not write to location 64
        pop(delegatecall(gas(), 25, _1, calldatasize(), _2, _2))
        let data := _2
        switch returndatasize()
        case 0 { data := 96 }
        default {
            let newFreePtr := add(_1, and(add(returndatasize(), 63), not(31)))
            if or(gt(newFreePtr, 0xffffffffffffffff), lt(newFreePtr, _1))
            {
                // this block does not read or write from 64
                mstore(_2, shl(224, 0x4e487b71))
                mstore(4, 0x41)
                revert(_2, 0x24)
            }
            // modifies 64; but this is redundant
            mstore(64, newFreePtr)
            data := _1
            // does not modify or read memory location 64
            mstore(_1, returndatasize())
            // does not modify or read memory location 64
            returndatacopy(160, _2, returndatasize())
        }
        return(add(data, 0x20), mload(data))
    }
}
```

**Comment by hrkrshnn** [comment]
A solver based approach may work for this. A rough idea is the following

1. We encode all `mstore(x, y)`.
2. We encode an expression that reads from memory (similar to https://github.com/ethereum/solidity/pull/10681). By using a solver, we try to prove if it doesn't read from `x`, if the solver can't prove it we assume it reads from `x`.
3. If none of the expressions reads from the memory `x`, we can safely remove `mstore(x, y)` (provided `y` is side effect free.)

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/pull/10479
