### ISSUE TITLE
missing constraints on block.timestamp in SMTChecker

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#10693]
In the following code:
```
pragma experimental SMTChecker;

contract C { 
    function f() public returns (uint) {
        uint b = block.timestamp;
        uint a = b + 0;
        return a;
    }
}
```
Compiling with `0.7.6`, both bmc and chc reports that `b + 0` results in an overflow when `b = 2**256`. However, this is not a possible value for `block.timestamp`. Here's the error message from bmc:
```
Warning: BMC: Overflow (resulting value larger than 2**256 - 1) happens here.
 --> ~/c.sol:6:18:
  |
6 |         uint a = b + 0;
  |                  ^^^^^
Note: Counterexample:
   = 0
  <result> = 2**256
  a = 0
  b = 2**256
```

I'm also confused by the loose hanging `= 0`, I think maybe `block.timestamp` isn't pretty printed properly...

**Comment by axic** [comment]
Since the opcodes don't define any limits currently, assuming 256-bit is somewhat correct for all these variables. However, there's #9810 to change it.

And the missing name is something which should be fixed anyway :)

**Comment by leonardoalt** [comment]
@axic that's correct, but I think @MrChico 's point is that it's suggesting a value above that (2**256 itself), which is wrong

**Comment by leonardoalt** [comment]
> I'm also confused by the loose hanging = 0

I think that should be your function's return variable

**Comment by MrChico** [comment]
> > I'm also confused by the loose hanging = 0
> 
> I think that should be your function's return variable

Isn't that `<result>`?

**Comment by leonardoalt** [comment]
<result> should be the operation that caused the overflow, in this case `b + 0`. Return variables always exist as actual variables, even if unnamed. `= 0` is just the return variable value, but since it's unnamed it shows like this

**Comment by leonardoalt** [comment]
Both of course could/should obviously be improved
