### ISSUE TITLE
Pad 0s in front of Hexadecimal representation in opcode generation

### ISSUE THREAD

**Issue by channgo2203** [ethereum/solidity#1071]
This is the simple contract:
//pragma solidity ^0.4.0;

contract SimpleStorage {
  mapping (uint => uint) nameRegistry; // state variable on the contract storage

  function nameRegister(uint key, uint value) {
    if (nameRegistry[key] == 0)
    nameRegistry[key] = value;
  }
}

The binary code:
6060604052609b8060106000396000f360606040526000357c0100000000000000000000000000000000000000000000000000000000900480632fbff5f3146037576035565b005b605460048080359060200190919080359060200190919050506056565b005b6000600060005060008481526020019081526020016000206000505414156096578060006000506000848152602001908152602001600020600050819055505b5b505056

The Opcode:
PUSH1 0x60 PUSH1 0x40 MSTORE PUSH1 0x9B DUP1 PUSH1 0x10 PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN PUSH1 0x60 PUSH1 0x40 MSTORE PUSH1 0x0 CALLDATALOAD PUSH29 0x100000000000000000000000000000000000000000000000000000000 SWAP1 DIV DUP1 PUSH4 0x2FBFF5F3 EQ PUSH1 0x37 JUMPI PUSH1 0x35 JUMP JUMPDEST STOP JUMPDEST PUSH1 0x54 PUSH1 0x4 DUP1 DUP1 CALLDATALOAD SWAP1 PUSH1 0x20 ADD SWAP1 SWAP2 SWAP1 DUP1 CALLDATALOAD SWAP1 PUSH1 0x20 ADD SWAP1 SWAP2 SWAP1 POP POP PUSH1 0x56 JUMP JUMPDEST STOP JUMPDEST PUSH1 0x0 PUSH1 0x0 PUSH1 0x0 POP PUSH1 0x0 DUP5 DUP2 MSTORE PUSH1 0x20 ADD SWAP1 DUP2 MSTORE PUSH1 0x20 ADD PUSH1 0x0 SHA3 PUSH1 0x0 POP SLOAD EQ ISZERO PUSH1 0x96 JUMPI DUP1 PUSH1 0x0 PUSH1 0x0 POP PUSH1 0x0 DUP5 DUP2 MSTORE PUSH1 0x20 ADD SWAP1 DUP2 MSTORE PUSH1 0x20 ADD PUSH1 0x0 SHA3 PUSH1 0x0 POP DUP2 SWAP1 SSTORE POP JUMPDEST JUMPDEST POP POP JUMP

Maybe the generation for PUSH instruction has a bug. Here, in binary the PUSH29
7c0100000000000000000000000000000000000000000000000000000000

However in Opcode:
PUSH29 0x100000000000000000000000000000000000000000000000000000000

**Comment by pirapira** [comment]
I'm not seeing the problem.  I think the opcode and the bytecode push the same number.  If I align them:

```
PUSH29 0x100000000000000000000000000000000000000000000000000000000
      7c0100000000000000000000000000000000000000000000000000000000
```

**Comment by pirapira** [comment]
I think `7c` is the opcode for `PUSH29`.

**Comment by channgo2203** [comment]
Of course 0x7c is the bytecode of the instruction PUSH29. The problem is the first byte of 29bytes after the PUSH29. In the binary they are 0x01 00 ... 00. But in the opcode they are 0x10 00 ... 00.

I've been developing a very precise formal model of EVM in Coq (https://github.com/channgo2203/fevm), when I load the above binary code, and use Coq to generate back the opcode. It should be:
PUSH29 0x01 00 ...00

**Comment by pirapira** [comment]
Let me try to understand you; if I followed you correctly, `PUSH1 0x0` should be `PUSH1 0x00` as well.

By the way, I forked `fevm`.

**Comment by channgo2203** [comment]
Ok, I see, I counted wrongly the number of hex digits here, for all zeros most significant digits, they are cut off. They are equal. However, I think I should prefer to pad zero digits to make the representation more elegant. 

I should close the issue.
Thanks!

**Comment by pirapira** [comment]
@channgo2203 actually that's my preference to pad zeros.  If we do that, it's easier to see when a program uses too big PUSH.  Say, when we want to push 0x3 but we use `PUSH_3`, we will see `0x000003`, and immediately we know the instruction is for bigger numbers.

**Comment by pirapira** [comment]
@channgo2203 Let's see what others say, though, do you mind changing the title to something like "pad 0s in front of the pushed immediate value when...".

**Comment by channgo2203** [comment]
I think it's good idea ;)

**Comment by pirapira** [comment]
@channgo2203 I sent you a message in Gitter about `fevm`.

**Comment by axic** [comment]
We had a very similar discussion here: https://github.com/ethereum/solidity/issues/564#issuecomment-235040678

**Comment by pirapira** [comment]
@axic I see. Now I see [the code](https://github.com/ethereum/solidity/pull/926/files) resulting from that discussion, I'm fine with the current implementation.  Thanks for pointing out.

@channgo2203 It's unlikely we will ever see a `0x00...` from [this](https://github.com/ethereum/solidity/pull/926/files) generation, even if we pad zeros.

**Comment by pirapira** [comment]
Now I'm inclined to close this.
