### ISSUE TITLE
How can i  install Solidity 0.4.9 on my ubuntu?

### ISSUE THREAD

**Issue by chusanchen** [ethereum/solidity#10711]
HI , 
I'm a new learner of Ethereum。which file should i download and how can i  install?
wish you have a good day.

**Comment by hrkrshnn** [comment]
If you are a new learner, it is recommended to use a more recent version. 0.8.0 or 0.7.x. On installation see https://docs.soliditylang.org/en/v0.8.0/installing-solidity.html Also please use https://gitter.im/ethereum/solidity for such questions in the future.
