### ISSUE TITLE
The reserved name `cout` should not be redefined using the macro system.

### ISSUE THREAD

**Issue by ViralTaco** [ethereum/solidity#10725]
Hi.
https://github.com/ethereum/solidity/blob/5241b7b761f304af3f49e6b2f5dfe330a7cb508d/solc/CommandLineInterface.cpp#L112
This is undefined behavior. Meaning it's not a program. It may behave as one. But it doesn't have to. And the day it doesn't that's gonna be a 'dumb' waste of time. 
It could be a struct `Logger` which would be a bit more idiomatic. None of the code really has to change, it just needs some scotch tape and some paint. 
I can try and make a pull request if you care (after I'm done looking at the code).

**Comment by leonardoalt** [comment]
> I can try and make a pull request if you care (after I'm done looking at the code).

That would be great, thanks!

**Comment by ekpyron** [comment]
What makes you say it's undefined behaviour? I agree that it's rather horrible (it's there to prevent directly using ``cout`` instead of ``sout()``, which in itself is horrible) - just like that entire file is horrible ;-). But I still think as it stands it's well-defined.

**Comment by ViralTaco** [comment]
> What makes you say it's undefined behavior?

[It being undefined behavior](http://eel.is/c++draft/reserved.names#general-2). You are redefining a [predefined object](http://eel.is/c++draft/iostream.objects#narrow.stream.objects). Any part of the [standard library can rely on it](http://eel.is/c++draft/reserved.names#macro.names-1).

**Comment by ekpyron** [comment]
http://eel.is/c++draft/reserved.names#general-2 - ``cout`` is neither a macro, nor a global name, nor a name with external linkage, it's a qualified name in the ``std`` namespace only...
But this still probably actually indeed falls under http://eel.is/c++draft/reserved.names#macro.names-1
In any case, the whole file needs a rewrite in general, getting rid of this and all the other oddities in there.

**Comment by ViralTaco** [comment]
> http://eel.is/c++draft/reserved.names#general-2 - `cout` is neither a macro, nor a global name, nor a name with external linkage, it's a qualified name in the `std` namespace only...
> But this still probably actually indeed falls under http://eel.is/c++draft/reserved.names#macro.names-1
> In any case, the whole file needs a rewrite in general, getting rid of this and all the other oddities in there.

Right… It's an OBJECT not a name. It's NOT a marco. AND it is part of the `std` namespace. Those are only 3 ways how it's undefined behavior. If you have a definition for it point it out. (Don't) It's not there, it's ill-formed. 
I'm not here to argue. I've given you the information. You can read the standard on your own time.

**Comment by ViralTaco** [comment]
I've looked more into… And errrr. I think, it's ok. Like we don't need the code to be valid. Let's just fork the standard, it's faster and probably won't break as much code. 😥
