### ISSUE TITLE
Allow explicit conversions between address and bytes20

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#10729]

**Comment by hrkrshnn** [comment]
Actually, not sure what is missing here

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;
contract C {
    function f() public pure {
        address a = address(0);
        bytes20 b = 0;
        
        b = bytes20(a);
        a = address(b);
    }
}
```
Compiles fine.

However, explicit conversion `address payable <=> bytes20` is not allowed though.

**Comment by hrkrshnn** [comment]
I checked the tweet (https://twitter.com/NCyotee/status/1347253801653309443?s=20) and it was about `bytes32 <=> address`.

**Comment by chriseth** [comment]
Weird - not sure why I thought it would not be possible.
