### ISSUE TITLE
[Optimizer] Loop Invariant Code Motion for storage and memory writes that are invariant

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10720]
Writes that are invariant in the for loop can be moved outside the loop as long as it's inside an `if` statement with the same statement as the `for` loop.

For example,

```
let i := 0
for {} lt(i, 10) {i := add(i, 1) }
{
   sstore(0, 1)
   // more things that does not modify storage
}
```

The above code can be converted into

```
let i := 0
if lt(i, 10) { sstore(0, 1) }
for {} lt(i, 10) {i := add(i, 1) }
{
  // rest of the code
}
```

**Comment by chriseth** [comment]
The perfect way to deal with this would be to optimize
```
for { let i := 0 } lt(i, sload(0)) { i := add(i, 1) } {
  sstore(1, i)
  sstore(add(2, i), i)
}
```
to
```
let x := sload(0)
if x { sstore(1, sub(x, 1)) } // "compute" the final value stored in 1
for { let i := 0 } lt(i, x) { i := add(i, 1) } {
  sstore(add(2, i), i)
}
```
How can we achieve this?

**Comment by ekpyron** [comment]
Optimistic loop unrolling and backtracking :-)?

**Comment by chriseth** [comment]
I would say it's more like detecting linear dependencies. At some point, I would also like to do the optimization from slide 24 to 25 here: https://chriseth.github.io/notes/talks/solidity_optimizer_devcon4/#/24

**Comment by ekpyron** [comment]
Well... that's hard in general... but in general it still works by unrolling first and simplifying. And then comparing the result with the original loop body. If you can then detect that symbolically dividing yields a constant you have solved that particular case...
