### ISSUE TITLE
Yul Optimizer: remove unnecessary ``leave``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#10726]
I just saw this: https://github.com/ethereum/solidity/blob/5241b7b761f304af3f49e6b2f5dfe330a7cb508d/test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner.yul#L32

I.e. ``function f() { if cond { leave } }`` is left by the optimizer.
We should remove ``leave``, if there no more statements afterwards anyways, i.e. this should first reduce to
``function f() { if cond { } }`` which would ultimately reduce to ``function f() { }`` (or ``function f() { pop(cond) }`` if ``cond`` had side-effects).

**Comment by axic** [comment]
In some cases code like this is generated:
```
            function fun_addr_44() -> vloc__30 {
                let zero_value_for_type_t_bool_1 := zero_value_for_split_t_bool()
                vloc__30 := zero_value_for_type_t_bool_1

                let expr_36 := convert_t_type$_t_contract$_L_$27_$_to_t_address(expr_35_address)
                let expr_39 := 0x00
                let expr_40 := convert_t_rational_0_by_1_to_t_address(expr_39)
                let expr_41 := eq(cleanup_t_address(expr_36), cleanup_t_address(expr_40))
                vloc__30 := expr_41
                leave

            }
```

It would be nice to remove trailing `leave`s.

**Comment by chriseth** [comment]
Since `leave` prevents a function from being inlined, we could also think about employing heavier machinery to remove it, even if it is not the last statement:
```
function f(x) {
  a()
  if x {
    b()
    leave
  }
  c()
}
->
function f(x) {
  a()
  switch x
  case 0 {
    c()
  }
  default {
    b()
  }
}

```

**Comment by chriseth** [comment]
Although, to keep things simple, these could be two steps (maybe combined in one actual named step): "Rotate" code such that the leave statement is at the end of the function and then remove all leave statements at ends of functions.
