### ISSUE TITLE
Compilation doesn't terminate for contract

### ISSUE THREAD

**Issue by rvantonder** [ethereum/solidity#10732]
## Description

`solc` doesn't terminate when compiling this small contract (I let it run for ~2 mins then `Ctrl-c`'d):

```solidity
contract C { 
    bytes32 constant x = x;
    function f() public pure returns (uint t) {
        assembly {
            t := x
        }
    }
}
```

Without the assembly block, this contract causes a cyclical dependency in the `x = x` statement. Looks like the cycle detection trips up with a variable use or assignment in the assembly block.

Found on master, part of the fuzzing project https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version: Version: 0.8.1-develop.2021.1.8+commit.d11cf15d.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04.5 LTS

## Steps to Reproduce

This command doesn't terminate:

```bash
cat <<EOF | solc - 
contract C { 
    bytes32 constant x = x;
    function f() public pure returns (uint t) {
        assembly {
            t := x
        }
    }
}
EOF
```

**Comment by agroce** [comment]
@bshastry note this is from an offshoot of my ongoing AFL-based fuzzing effort; we're hoping to have some new things by using more sophisticated mutation generation.  @rvantonder is the brains behind the comby tool that can give the fancy mutation

**Comment by Hellobloc** [comment]
Is this problem still present in 0.8.0?
