### ISSUE TITLE
Replace loops by range-v3 loops where applicable.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#10738]
After https://github.com/ethereum/solidity/pull/10737 we should be able to replace nearly all non-range-based for loops by range-based loops using appropriate ranges.

**Comment by chriseth** [comment]
oh yes!

**Comment by axic** [comment]
And also replace the `boost::algorithm::reverse` iterator? I think ranges-v3 has some functionality for that?

**Comment by ekpyron** [comment]
Especially if there is a ``ranges::cpp20::*`` version of any boost range algorithm or boost range adaptor, it'd make sense to switch to the ranges-v3 version.

**Comment by cameel** [comment]
Two things that should be easy to find and replace are uses of `boost::adaptors::map_keys` and `boost::adaptors::map_values`. That would be `views::keys` and `views::values` now.

**Comment by ekpyron** [comment]
Also to be clear in case any external contributor wants to take this: there's no need to find all cases where this can be done at once. We'll gladly accept PRs that change one or two for loops at a time.

**Comment by ekpyron** [comment]
``vector_ref``, resp. ``bytesRef`` should also be replaced by ``ranges::span``.

**Comment by axic** [comment]
> vector_ref, resp. bytesRef should also be replaced by ranges::span.

So I did this work but using `std::basic_string_view<uint8_t>`. It is quite a few changes, but simplifies a lot of things. Withheld those PRs are people were saturated with "technical debt" PRs after the "remove u160" thing :wink:

**Comment by ekpyron** [comment]
> > vector_ref, resp. bytesRef should also be replaced by ranges::span.
> 
> So I did this work but using `std::basic_string_view<uint8_t>`. It is quite a few changes, but simplifies a lot of things. Withheld those PRs are people were saturated with "technical debt" PRs after the "remove u160" thing wink

That's immutable, though, isn't it? So while this may work for ``bytesConstRef`` it won't for ``bytesRef``, will it?
``ranges::span``, which will become C++20 ``std::span`` is the better choice in any case... and it'll work in the mutable and immutable case.

**Comment by axic** [comment]
Yes, but we didn't actually need mutability in most of the places.

**Comment by anurag-git** [comment]
Fixed following issues in #11193 
Replaced boost::adaptors::map_keys with ranges::views::keys and boost::adaptors::map_values with ranges::views::values.
Replaced boost::adaptors::reverse with ranges::views::reverse.

**Comment by axic** [comment]
The cases remaining:
```
liblangutil/ErrorReporter.h:#include <boost/range/adaptor/filtered.hpp>
libsolidity/analysis/PostTypeChecker.cpp:#include <boost/range/adaptor/map.hpp>
libsolidity/analysis/ControlFlowAnalyzer.cpp:#include <boost/range/algorithm/sort.hpp>
libsolidity/analysis/TypeChecker.cpp:#include <boost/range/adaptor/reversed.hpp>
libsolidity/formal/SMTEncoder.cpp:#include <boost/range/adaptors.hpp>
libsolidity/ast/Types.cpp:#include <boost/range/adaptor/sliced.hpp>
libsolidity/ast/Types.cpp:#include <boost/range/algorithm/copy.hpp>
libsolidity/ast/ASTJsonConverter.cpp:#include <boost/range/algorithm/sort.hpp>
libsolidity/parsing/DocStringParser.cpp:#include <boost/range/algorithm/find_first_of.hpp>
libsolidity/parsing/DocStringParser.cpp:#include <boost/range/irange.hpp>
libyul/AsmAnalysis.cpp:#include <boost/range/adaptor/reversed.hpp>
test/libyul/Inliner.cpp:#include <boost/range/adaptors.hpp>
test/libsolidity/util/ContractABIUtils.cpp:#include <boost/range/algorithm_ext/for_each.hpp>
```

**Comment by anurag-git** [comment]
@chriseth, @axic , any suggestion for replacing make_pair in `libsolidity/parsing/DocStringParser.cpp` for replacing find_first_of. Tried couple of things but doesn't work.

**Comment by chriseth** [comment]
I think DocStringParser should in general be rewritten to replace pairs of iterators by something else. Maybe string_view would be the right choice.

**Comment by vowchick** [comment]
> The cases remaining:
> 
> ```
> liblangutil/ErrorReporter.h:#include <boost/range/adaptor/filtered.hpp>
> libsolidity/analysis/PostTypeChecker.cpp:#include <boost/range/adaptor/map.hpp>
> libsolidity/analysis/ControlFlowAnalyzer.cpp:#include <boost/range/algorithm/sort.hpp>
> libsolidity/analysis/TypeChecker.cpp:#include <boost/range/adaptor/reversed.hpp>
> libsolidity/formal/SMTEncoder.cpp:#include <boost/range/adaptors.hpp>
> libsolidity/ast/Types.cpp:#include <boost/range/adaptor/sliced.hpp>
> libsolidity/ast/Types.cpp:#include <boost/range/algorithm/copy.hpp>
> libsolidity/ast/ASTJsonConverter.cpp:#include <boost/range/algorithm/sort.hpp>
> libsolidity/parsing/DocStringParser.cpp:#include <boost/range/algorithm/find_first_of.hpp>
> libsolidity/parsing/DocStringParser.cpp:#include <boost/range/irange.hpp>
> libyul/AsmAnalysis.cpp:#include <boost/range/adaptor/reversed.hpp>
> test/libyul/Inliner.cpp:#include <boost/range/adaptors.hpp>
> test/libsolidity/util/ContractABIUtils.cpp:#include <boost/range/algorithm_ext/for_each.hpp>
> ```

There is only one instance left from that list:
test/libsolidity/util/ContractABIUtils.cpp:#include <boost/range/algorithm_ext/for_each.hpp>
And simply changing boost::for_each to std::for_each doesn't compile, so i don't know if we can get rid of it now

**Comment by cameel** [comment]
How about changing it to an ordinary loop that iterates over the result of `ranges::views::zip()`?

**Comment by axic** [comment]
The only two remaining items are:
```
liblangutil//ErrorReporter.h:#include <boost/range/adaptor/filtered.hpp>
solc/CommandLineInterface.cpp:#include <boost/range/adaptor/filtered.hpp>
```
