### ISSUE TITLE
Bump emscripten in the build system

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10747]
We agreed a while to periodically upgrade emscripten to avoid irregular large bumps.

Last we upgraded to emscripten 1.39.15 in solidity 0.6.9. Since then there has been 5 releases in 1.39x/1.40.x, and 13 releases in a new major version 2.x.y.

It would be useful to check the changelog and upgrade: https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md

**Comment by ekpyron** [comment]
Well, I'll just build a docker image locally and see if I get soljson.js to build and if it looks OK. If so, I'll push a PR that'll build and push such a docker image and another PR that builds soljson.js and we can stress-test it a bit to see if it works before merging either. But yeah, we should also make sure to read the changelog line by line...

**Comment by ekpyron** [comment]
I think it "just" (with only a handful of build system modifications that is) works.

**Comment by ekpyron** [comment]
Do we by the way plan to support split js and wasm files for loading at some point :-)? And asynchronous, maybe even streaming loading? That way we could even give dynamically loading z3 on demand only a try - it sounds like this should work these days...

**Comment by axic** [comment]
In 1.40 or so they changed the entire thing to be a promise. So we may need to adjust solc-js, and if we do, we could support the split files. Wasn't the async behaviour the issue with wasm version? But the combined version was resolving that promise so we had no changes needed in solc-js.

**Comment by ekpyron** [comment]
I think what you're talking about only applies to ``MODULARIZE=1`` which we don't (yet) do, so the current build I have seems to work with solc-js (and in remix/firefox and remix/chrome) without any solc-js change.

Also we explicitly disable asynchronous wasm compilation, etc. - we basically went out of our way to *not* have to change solc-js too much :-). But maybe at some point we could reconsider that... of course split files go against our current binary distribution setup, etc. - but I wouldn't be surprised if loading would be significantly faster, if we didn't need the base64 stuff, allowed asynchronous compilation, enabled streaming compilation, etc.

**Comment by ekpyron** [comment]
On the other hand doing any of this is not unlikely to end up in something we'd have to consider a breaking change, so it'd probably only go into 0.9.0 anyways - but if we want to explore that, we should still start early, otherwise we won't have enough time in the end to do it properly ;-).

**Comment by ekpyron** [comment]
If we're very lucky, there'll finally be some progress on WebAssembly Exceptions in the foreseeable future, though...
https://bugs.chromium.org/p/v8/issues/detail?id=8091 actually doesn't sound too bad and I at least read rumors about Firefox having an almost complete implementation of the second proposal, even though I haven't found any issue tracking it or any mention of it...

**Comment by cameel** [comment]
Maybe we should have a nightly CI job that greps the changelog to find the latest released version, compares with the one we use and annoys us on gitter until we upgrade? :)
