### ISSUE TITLE
External calls with "view: true" attribute

### ISSUE THREAD

**Issue by vporton** [ethereum/solidity#10743]
## Abstract

In existing Solidity there is no way to make an external call from a view function (when the external function is also view), except of using `staticcall` feature. It should be doable without using this hard to use feature.

## Specification

It should be added new `view` boolean parameter to external calls to be used like:

`who.f{view: true}(...);`

`view` could be only the constant `false` or `true` (not an arbitrary boolean value).

If `view` is `true` then the external call to be considered as a read-only operation.

**Comment by chriseth** [comment]
>  In existing Solidity there is no way to make an external call from a view function (when the external function is also view), 

I'm not sure this is true. The following code is valid:

```
contract C {
    function retrieve() public view returns (uint256){
        return this.retrieve();
    }
}
```

Are you saying you want to force the use of `staticcall` even on functions that are not view functions?

**Comment by vporton** [comment]
I've realized that there was an error in my report. Ignore it, closing the issue.
