### ISSUE TITLE
[Optimizer] Remove redundant mstores assigning zero values to locations that are already zero

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10755]
The following contract:

```solidity
  struct MyStruct {
	  uint x;
	  uint y;
	  uint z;
  }

  contract C {
	  function f() public {
		  MyStruct memory s;
	  }
  }
```

produces the optimized-ir

```
let _1 := 0
if eq(0x26121ff0, shr(224, calldataload(_1)))
{
    if callvalue() { revert(_1, _1) }
    if slt(add(calldatasize(), not(3)), _1) { revert(_1, _1) }
    let memPtr := allocateMemory(96)
    mstore(memPtr, _1)
    mstore(add(memPtr, 32), _1)
    mstore(add(memPtr, 64), _1)
    return(allocateMemory(_1), _1))
}
```
We should be able to avoid the three `mstores`, which are zero-ing out the struct values in memory. Possibly related to https://github.com/ethereum/solidity/issues/10690

**Comment by chriseth** [comment]
Is this the "assume memory is initially zero" issue? Note that we cannot assume that the allocator returns "fresh" memory.

**Comment by hrkrshnn** [comment]
> Note that we cannot assume that the allocator returns "fresh" memory.

What do you mean? Is this because of inline assembly, or can it happen with regular code?

**Comment by chriseth** [comment]
It can happen with regular code. There are some routines that only need temporary memory - they don't increment the free memory pointer afterwards.

**Comment by hrkrshnn** [comment]
https://hackmd.io/kPdGgEUORtSDtoDt5Nv8dw some examples and notes on how to deal with this.
