### ISSUE TITLE
Library functions cannot be called from payable functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1075]
The `msg.value` protection has to be removed from all library functions, because they will see the value provided to the calling function if called via delegatecall.

If we do not have it already, we should also add a test to check that non-payable public functions can be called from payable functions.

**Comment by chriseth** [comment]
@axic do you have time to handle this? At best, we could add protection against sending money to a library via a call, but I'm not sure it is possible to detect that.

**Comment by axic** [comment]
@chriseth not before devcon
