### ISSUE TITLE
[SMTChecker] Hang - Contract Never Compiles in version 0.7.6

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#10798]
## Description

Hello everyone,
the contract below in compiler's version 0.7.6, is never compiled and sometimes remix slow down:

```solidity
pragma experimental SMTChecker;

contract C
{
	function f(int c, address a) public pure {
		assert(address(c) == a);
        }
}
```

Found by Fuzzing solc compiler.

## Environment

- Compiler version: 0.7.6+
- Target EVM version (as per compiler settings): 0.7.6+commit.7338295f.Linux.g++
-  Framework/IDE (e.g. Truffle or Remix): verified in Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 16.04 Bionic

## Steps to Reproduce

As shown above.

**Comment by leonardoalt** [comment]
I can't reproduce it in 0.8.0.
It doesn't compile (type error), so I changed it to
```
pragma experimental SMTChecker;

contract C
{
    function f(int c, address a) public pure {
        assert(address(uint160(int160(c))) == a);
    } 
}
```
which doesn't hang.
Since we only backport critical bugfixes, I'm closing this one. Please reopen if needed.
