### ISSUE TITLE
Windows Static Binaries point to nightly instead of stable

### ISSUE THREAD

**Issue by arlenner** [ethereum/solidity#10799]
Hello, it appears the solc-bin project doesn't accept issues, so I decided I should post it here. Currently, when downloading the latest stable version under the windows-amd-64 folder from the solc-bin repository, I get a nightly build when I check my version from within the containing folder.

**Comment by cameel** [comment]
> Hello, it appears the solc-bin project doesn't accept issues, so I decided I should post it here.

Thanks for the report! This is the right place.

> Currently, when downloading the latest stable version under the windows-amd-64 folder from the solc-bin repository, I get a nightly build when I check my version from within the containing folder.

I just checked 0.8.0, 0.7.6, 0.7.2 and 0.7.1 and none of them identifies itself as a nightly build. For example:

``` cmd
cd \tmp
curl --location https://binaries.soliditylang.org/windows-amd64/solc-windows-amd64-v0.8.0+commit.c7dfd78e.exe --remote-name
solc-windows-amd64-v0.8.0+commit.c7dfd78e.exe --version
```
```
solc, the solidity compiler commandline interface
Version: 0.8.0+commit.c7dfd78e.Windows.msvc
```

Could you give me a link to the specific file you're checking and show me how you're determining it's a nightly?

By the way, the only platform we do nightly builds for is emscripten, though there's of course a chance that one of the Windows files is a non-release build by mistake.

**Comment by cameel** [comment]
@arlenner Could you provide more details to help us track down the bad binary?

By the way, there is an older issue about 0.4.15 being a nightly on Windows (#9545) and that's still not fixed unfortunately. Maybe you hit that one?

**Comment by arlenner** [comment]
My apologies, I misunderstood the error message I was getting because it
said something about nightly but it turns out it was irrelevant

**Comment by cameel** [comment]
No problem. Thanks for the update! I'm closing this in that case.
