### ISSUE TITLE
[Inline Assembly] Hang - Contract Never Compile

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#10800]
Hello everyone,
another contract that is never compiled is the contract below

```
contract C {
    bytes32 constant x = keccak256("abc");
    bytes32 constant y = y;
    function f() public pure returns (uint t) {
        assembly {
            t := y
        }
    }
}
```

Found by Fuzzing solc compiler.
Environment

    Compiler version: 0.7.6+
    Target EVM version (as per compiler settings): 0.7.6+commit.7338295f.Linux.g++
    Framework/IDE (e.g. Truffle or Remix): verified in Remix
    EVM execution environment / backend / blockchain client:
    Operating system: Ubuntu 16.04 Bionic

Steps to Reproduce

As shown above.

**Comment by hrkrshnn** [comment]
This is equivalent to https://github.com/ethereum/solidity/issues/10732. The PR https://github.com/ethereum/solidity/pull/10783 will fix both of them.

The issue is that the check that `bytes32 y = y` is circular is not done before trying to access its value during type checking phase.

**Comment by hrkrshnn** [comment]
Thanks for the issue, it's a nice catch.
