### ISSUE TITLE
[isoltest] Add way to inspect generated code

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10820]
Certain `SolidityEndToEndTest`s check the generated bytecode. Similarly in some cases CLI tests are used for the same.

In https://github.com/ethereum/solidity/pull/10807/files#r559757068 such a case came up and it could not be moved to semantic tests given this limitation.

The semantic tests could be extended to have a way assert on generated code: the line `bytecode: <pattern>` would match the constructor code, and `deployedBytecode: <pattern>` would match the runtime code. The pattern could be some limited form of regular expressions.

**Comment by chriseth** [comment]
I'm not sure if this is worth it. How many of these do we have?

**Comment by axic** [comment]
I think it would not be a big deal, but would allow us to remove these random weird tests we have scattered around, like doing something like this in the CLI tests. The CLI tests should be only about the CLI and not a bunch of other random things.

**Comment by leonardoalt** [comment]
If it would also lead to more tests being extracted, I think it's a good idea.

**Comment by cameel** [comment]
We might want to keep it open. We even had a PR for it (#11424). We closed it because it got stale but we could at least keep the issue to go back to it eventually.

**Comment by ekpyron** [comment]
We can also keep it closed and if anyone actually needs this reconsider it :-).
