### ISSUE TITLE
Docs: "Layout of State Variables in Storage" "Mappings and Dynamic Arrays" paragraph incredibly confusing and poorly written

### ISSUE THREAD

**Issue by relyt29** [ethereum/solidity#10859]
## Description

The paragraph "Mappings and Dynamic Arrays" under the "Layout of State Variables in Storage" is incredibly frustrating to understand, it needs to be rewritten to be clearer: right now I'm sitting here playing guess and check with web3.getStorageAt and web3.keccak, trying to figure out what the original author of the paragraph meant.

## Environment

Irrelevant, this is me asking someone to update the docs so that people can better understand how to access storage directly

## Steps to Reproduce

Here is the paragraph text reproduced below:

> Due to their unpredictable size, mapping and dynamically-sized array types use a Keccak-256 hash computation to find the starting position of the value or the array data. These starting positions are always full stack slots.
> 
> The mapping or the dynamic array itself occupies a slot in storage at some position `p` according to the above rule (or by recursively applying this rule for mappings of mappings or arrays of arrays). For dynamic arrays, this slot stores the number of elements in the array (byte arrays and strings are an exception, see below). For mappings, the slot is unused (but it is needed so that two equal mappings after each other will use a different hash distribution). Array data is located at `keccak256(p)` and the value corresponding to a mapping key `k` located at `keccak256(k . p)` where `.` is concatenation. If the value is again a non-elementary type, the positions are found by adding an offset of `keccak256(k . p)`.
> 

"These starting positions are always full stack slots" - should probably be changed to indicate that a full stack slot is a 32 byte slot, as is mentioned in the previous section.

"The mapping ... according to above rule" *WHAT ABOVE RULE?!?!?!* I went back as far back as to commit 0.4.23 to see if maybe this was referring to a sentence that was previously written but then deleted and not updated but did not see any such sentence. Perhaps it's referring to the last sentence of the previous section? Here's that sentence: 

> "The elements of structs and arrays are stored after each other, just as if they were given explicitly."

even that doesn't make sense in the context of talking about this `p` variable that is concatenated with the key and then stuffed into keccak. 

But ok, it's pretty clear that you take some stuff, concatenate it with your key, and then that yields you some keccak which you then interpret as an integer pointer you can pass to something like web3.getStorageAt to get the array in memory somewhere in this magical storage land where the actual data lives. Ok

"For dynamic arrays ... number of elements in the array" - ok this part makes sense, though it does leave a bit of ambiguity. Am I to take it that once I find my magical keccak pointer into memory/storage where the array lives, the 0th index in the array tells me the length of the array, and then starting at position 1 into the array is the actual data? That's what it sounds like, but, unclear.

"For mappings, the slot is unused (but it is needed so that two equal mappings after each other will use a different hash distribution)" so what happens here? Does that mean I should expect there to be an empty 0x0 value in the index of 0 of the mapping where my magical keccak pointer lives? Also, how does that ensure different hash distribution, at all? What?

The example then produced is useful and helpful, as it shows the recursion of multidimensional arrays/mappings, BUT completely unclear in other ways, namely: 

> So for the following contract snippet the position of `data[4][9].b` is at `keccak256(uint256(9) . keccak256(uint256(4) . uint256(1))) + 1`:
> ```pragma solidity ^0.4.0;
> 
> contract C {
>   struct s { uint a; uint b; }
>   uint x;
>   mapping(uint => mapping(uint => s)) data;
> } 

why is the inner, second dimension of the array, i.e. 9, the outer keccak? The paragraph makes no mention of this ordering and if the example wasn't there I would immediately have gotten it backwards and assumed that it would be `keccak(uint(4) . keccak(uint(9) . p) )` (like, you know, how most C-like low level languages index arrays in memory) I don't care about what the order is but it should probably at least be explained a bit in verbiage before the example is just thrown at you. But the p thing is totally unclear and there is no explanation of why, in this example, p is equal to 1. I am stuck trying to debug my own contract with a different structure because I don't understand this `p` dynamic. Presumably the outer plus 1 is because uint b is in the second, i.e. 1th index storage slot for the struct. Or is that represented inside the keccak computation? Who knows...

Can someone update this paragraph with a bit more verbiage to make it more clear what is going on here, please?

Edit: I forgot to add, there's no discussion around paddings for the values that go into the keccak. Presumably any index into a mapping should probably be padded to 32 bytes (e.g. 20 byte addresses), but that's not made clear either.

**Comment by relyt29** [comment]
https://ethdebug.github.io/solidity-data-representation/#user-content-locations-in-detail-memory-in-detail-pointers-to-memory

section "Storage: Lookup types" might be a good reference for rewriting this section. Explanation of p is much clearer there

**Comment by chriseth** [comment]
The section is a bit condensed, I give you that and it makes some mistakes in wording ("stack slot" should be "storage slot"). I'll try to update it. To "above rules" refer to the rules at the beginning of the section "Layout of State Variables in Storage".

**Comment by chriseth** [comment]
Please check if https://github.com/ethereum/solidity/pull/10860 helps you understand the concept better. It would be nice if you could comment on the PR if there are still clarifications needed.
