### ISSUE TITLE
New builtin `literalbytecode`

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#10869]
For specific features on other chains, it might  be useful to allow a special Yul builtin that can be used to inject raw bytecode into the binary. In particular, the optimism project would need this to inject a known sequence of opcodes that is an exception to the on-chain pureness checker.

This bytecode can not use any features of the assembler (for example no jump labels).
If it is not stack-height-neutral, subsequent variable access can fail.
The optimizer should ignore the sequence.

A first implementation could define a new AssemblyItem type that holds the full sequence. I think this would directly lead to the optimizer avoiding it.

@ben-chain

**Comment by ekpyron** [comment]
I guess "ignoring the sequence" entails assuming worst possible side-effects?

**Comment by axic** [comment]
There has been similar discussions in the past, mostly revolved around introducing new user-defined opcodes (#3215). (Additionally at the time we did not have dialect, but perhaps with dialect it is a more delicate question?)

I think the capability is interesting to be discussed, but not sure which is the better approach: inserting verbatim data vs. capability to define new opcodes.

For this specific issue, I think something like `verbatimdata` would be a more fitting name, but not sure.

**Comment by chriseth** [comment]
Thank you for linking the old issue again, @axic - I was not aware that there could be a unified solution.
So something like this could actually work - not sure if we want to make it stand out more:
```
function myNewOpcode(a, b, c) -> d, e, f = 0x1234567844
```
It essentially say that it takes three items from the stack and puts three items on the stack. It promises that the stack underneath is unmodified, but that cannot be checked by the compiler (since it has no concept of the meaning of the opcodes represented by the byte values). Such an opcode is assumed to have worst side-effects and the sequence of bytes should not be touched by any stage of the assembly-items based optimizer. Any call to such a function arranges the stack such that the arguments copied to the top and then inserts the byte sequence.

Another option, if we do not want to modify the syntax of yul is to use a builtin:
```
let d, e := verbatim(2, 0x1234567844, a, b, c)
```
The first parameter is the number of stack slots returned, then there is a hex sequence of actual code emitted, followed by a variable number of input arguments.

**Comment by ekpyron** [comment]
As a crazy proposal: yul is supposed to be a universal assembly language and all - what about having a generic mechanism for producing bytecode in yul similar to let's say contract creation? E.g.
```
opcode nameOfOpcode(a, b) -> c {
  mstore(0, 0xE0)
  return(0, 1)
}
```
Would introduce an opcode 0xE0 expected to take two arguments and return one.

We'd then just interpret this as yul reading the bytecode to be generated from returndata...
It could even have a mechanism to supply some typed literal arguments that can be read from simulated calldata, or something like that - or alternatively special builtins for reading literals and outputting bytecode from within an ``opcode ...`` definition...

For example
```
opcode newOpcode(a:literalUint256, b, c) -> c {
  if gt(a, 7) {
    raise("Invalid argument to newOpcode")
    // or revert with a message instead or sth
  }
  emitBytecode(add(0xE0, a))
}
```
Having ``let result := newOpcode(1, a, b)`` with two arguments on stack yielding one return value on stack with opcode 0xE1?

In fact a special case of this could be ``verbatim``:

```
opcode verbatim(x:literalString) {
  let v := literalSize(x)
  for { let i := 0 } lt(i, v) { i := add(i, 1) } {
    let x := and(literalValue(x, i), 0xFF)
    emitBytecode(x)
  }
}
```

EDIT: maybe we could even have it specify it's side-effects actually... like ``invalidateMemory()``, etc....

**Comment by axic** [comment]
I'm still not fully clear how this functionality would help Optimism, @ben-chain if you could explain? My understanding is that Optimism replaces state access opcodes with a call to the manager (which equals to the sender), e.g. `balance` would be replaced with `call(sender(), ..., <encoded query>)`.

The way this is accomplished is by changing the codegen of Solidity. How would a functionality like `literbytecode` help here? Isn't the better solution just using what the `--ir` emits? Couldn't one just replace calls like `balance` with `call()` and run the resulting yul file via the assembler? The `--experimental-via-ir` feature does the very same thing, gets the output of `--ir` and passes it to the assembler.

**Comment by axic** [comment]
@chriseth in your proposal how do the stack items get encoded?

**Comment by chriseth** [comment]
@axic all you say can be used - as far as I know, the problem is that the on-chain validator has to verify that the bytecode has been produced using the above procedure, since other ways to call into the manager and especially use its returned data destroy certain promises (failures have to bubble up, for example). The way this is currently done is that the validator only allows a certain sequence of bytes to violate pureness (the one that calls the manager). This mechanism only works as long as the optimizer does not destroy this sequence of bytes, so it can be found again.

What do you mean by encoding stack items?
```
d, e := verbatim(2, 0x1234567844, a, b, c)
```
is translated into:
- copy c to stack top
- copy b to stack top
- copy a to stack top
- 0x1234567844
- assume stack height has been reduced by one (len('a', 'b', 'c') - len('d', 'e'))
- move stack top into `d`'s stack slot
- move stack top into `e`'s stack slot

**Comment by ben-chain** [comment]
Thanks you guys for opening this!  This is a super important feature for us to have.  

@chriseth is correct that the difficulty comes from requiring on-chain enforcement that bytecode conforms to this manager interface.  It is straightforward enough to modify the Yul IR to call out to the manager, but we must also enforce that contracts are *only* accessing stateful opcodes to query the manager contract.  We allow two rules:
1. The contract is permitted to call the identity precompile.
2. The contract is permitted to call the `msg.sender`, but if that results in an exception, the contract must also revert with the same data.
[Here](https://github.com/ethereum-optimism/contracts-v2/blob/13b7deef60f773241723ea874fc6e81b4003b164/contracts/optimistic-ethereum/OVM/execution/OVM_SafetyChecker.sol#L123-L130) is the core logic which checks the bytecode follows those rules. 

For gas performance reasons, enforcing these rules requires specific literals in the code, and the `CALLER` opcode is always used to indicate the start of one of the literals.  (This is why you will see `CALLER POP` in the identity precompile case.  This is already a problem for us; getting the optimizer to play nice with this required disabling peephole optimization if the op is `CALLER`, but we only really need to avoid if it is within this literal).

Additionally, the safety check is much harder if the logic is position dependent.  To get around this, we use `PC` to make the literal be position independent.  This introduces further complexity--the compiler/optimizer really doesn't like unlabelled jumpdests.  Currently, I define a different literal which the optimizer doesn't touch, but is the same length and causes the same stack difference, and then find-and-replace in the raw bytecode once compilation is complete.  Not pretty!

So @axic I think your confusion comes from two layers that are going on here.  There's the part in the compiler of generating the right calldata to the manager, which can and should be handled by modifying the Yul IR.  Separately, the reason we need this feature is to enforce that the calldata payload is delivered following the above logic and post-call behavior.

Hope that makes sense!

**Comment by axic** [comment]
> What do you mean by encoding stack items?

So basically this definition provides no possibility to encode immediates or to build opcodes. In that sense @ekpyron's proposal is much better.

**Comment by ekpyron** [comment]
> > What do you mean by encoding stack items?
> 
> So basically this definition provides no possibility to encode immediates or to build opcodes. In that sense @ekpyron's proposal is much better.

Well, more flexible definitely, but also orders of magnitude more complicated, of course. (Especially since it's pretty much impossible to make the optimizer aware of the opcodes that way, so whatever is generated would have to be annotated explicitly... not to speak of having to define a dialect and execution schema for it, pulling in the interpreter to production code, etc., etc. - if the simpler approach is enough, maybe more than it is overkill.)

**Comment by chriseth** [comment]
@axic what do you mean by "build opcodes"?

**Comment by axic** [comment]
So if I understand correctly, you want to have a code such as `CALL <jumploc> JUMPI 0 0 REVERT JUMPDEST` inserted and ensure the optimiser never changes this sequence.

With the above `verbatim` suggestion it is not possible to change the `jumploc` because the entire sequence would be a literal.

That's why the `PC` is mentioned so that one could write something like `CALL <size of the revert branch> PC ADD JUMPI 0 0 REVERT JUMPDEST`.

**Comment by axic** [comment]
> what do you mean by "build opcodes"?

I meant to concatenate the bytecode to include immediate arguments. Such as `0xC0` + a (where a is treated as big endian shortest representation, just how PUSH is encoded). This is not possible if the code is a literal.

There are various proposals requiring immediate encoding, none of them (apart from `PUSHnn`) are part of the EVM and likely it will take a bit for them to be approved, but it would be nice to plan for that functionality.

Also as mentioned in the previous comment, if the code is literal, it is not possible to construct it.

**Comment by axic** [comment]
A side note. One could define helpers such as
```
function addmod384_v6(a, b, out, m) {
    verbatim(0, 0xc0, a, b, out, m)
}

function addmod384_v7(packed_offsets) {
    verbatim(0, 0xc0, packed_offsets)
}
```

I wonder if these would be inlined properly by the optimiser, worth trying out.

@SergioDemianLerner you have proposed a similar construct to what is discussed here in #3215. Would `verbatim` as described in https://github.com/ethereum/solidity/issues/10869#issuecomment-773628951 be useful to accomplish your goals?

To take your `erase` example, it could be implemented as
```
function erase(a, b, r) {
  r := verbatim(1, 0xaf, a, b)
}
```

**Comment by ekpyron** [comment]
> I meant to concatenate the bytecode to include immediate arguments. Such as `0xC0` + a (where a is treated as big endian shortest representation, just how PUSH is encoded). This is not possible if the code is a literal.
> 
> There are various proposals requiring immediate encoding, none of them (apart from `PUSHnn`) are part of the EVM and likely it will take a bit for them to be approved, but it would be nice to plan for that functionality.
> 
> Also as mentioned in the previous comment, if the code is literal, it is not possible to construct it.

Yeah... I mean with the generative approach I had before one could even generate jumpdests and jumps with fixed offsets referring to those jumpdests within the verbatim block, since one could just make the base offset at which the opcodes will be generated available as a builtin in the generating code... but I didn't bring that approach up in the call again myself, because I myself think it's most probably overkill and a huge effort in comparison, so there'd need to be very good reasons to go for anything in that direction.

**Comment by axic** [comment]
Re-reading #3215 I realised that @federicobond practically had the same suggestion as `verbatim`, with the difference of automatically deriving how many stack items are returned by the number of assignment of the result: https://github.com/ethereum/solidity/issues/3215#issuecomment-345469490

While this looks nice, it would fail to work if the builtin is not used part of an assignment statement.
