### ISSUE TITLE
[codegen] bad cast during pop of storage array

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10870]
## Description

```
contract C {
  int[] data;
  function f() public { (data.pop)(); }
}
```

throws

https://github.com/ethereum/solidity/blob/c7dfd78e57c5ad7abd485dc1cc13d8f0ab09d431/libsolidity/codegen/ExpressionCompiler.cpp#L1020

I suspect something is wrong with parsing `data.pop` (minus the parentheses)

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
I think the best fix here would be to retrieve the type of the array from the function type instead of the expression. This means the array type needs to be stored with the function type - that probably needs another field in the function type.
