### ISSUE TITLE
[PostTypeChecker] Null deref because declaration referenced in the override specifier has unset type

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10874]
## Description

```
contract A {
  function f() public virtual {}
}
contract B {
  function g() public {}
}
contract C is A,B {
  function f() public override (g) {}
}
```

references a nullptr here

https://github.com/ethereum/solidity/blob/dde6353c5d490009a8ec13978462190e4f7a1528/libsolidity/analysis/PostTypeChecker.cpp#L234

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by chriseth** [comment]
The TypeChecker shuold result in an error here and thus the PostTypeChecker should not run.

**Comment by chriseth** [comment]
@marenz do you want to take this?

**Comment by Marenz** [comment]
Sure, I'll take it.

**Comment by Marenz** [comment]
Though, I am not sure it should already error in the TypeChecker.. the PostTypeChecker is doing the type checker here and it just seems to assume too much about the type.. or do you think we should have an extra visitor for `OverrideSpecifiers` in TypeChecker? Do we have all the type information at that point already?

**Comment by chriseth** [comment]
The problem is that the post type checker is run at all even though there was a problem during type checking.
