### ISSUE TITLE
Arithmetic overflow for sdiv

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#1087]
I was very surprised to learn DIV does not generate VM-level exceptions. I do see division by 0 is handled by the compiler now.

The "subleties" document only outlines the division by 0 case for SDIV:

https://github.com/ethereum/wiki/wiki/Subtleties

> DIV, SDIV, MOD and SMOD with dividend (second argument) equal to 0 push 0 to the stack.

So what happens with `SDIV(MININT, -1)`? If I'm seeing this right, this behavior should absolutely be handled by the compiler as it is far less intuitive than the 0 case - nobody expects over/underflows for division like they do for multiplication.

Here's a test that works in latest browser-solidity. The result of these two functions is the same, and now the only time SDIV returns an incorrect (arbitrarily un-undefined) signed division value.

```
pragma solidity ^0.4.0;
contract test {
        function minInt() returns (int) {
            return -2**255;
        }
        function testSDIV() returns (int) {
        int minus1 = -1;
        int result = minInt() / minus1;
        return result;
    }
}
```

**Comment by chriseth** [comment]
Thanks for catching this!

**Comment by chriseth** [comment]
Having thought a bit more about this, I would actually say that this falls into the "throw on arithmetic overflow" category and not into the "throw on division by zero" category.

**Comment by pirapira** [comment]
Yes, because `-(minInt)` is too big.

**Comment by axic** [comment]
Should we close this issue and consider it part of the big umbrella issue #796 ?
