### ISSUE TITLE
[SMTChecker] False positive for ternary expressions in chc engine

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#10876]
Compiling the following contract:
```
contract C {
  function f(uint x) public returns (uint) {
    return x > 0 ? x - 1 : 0;
  }
}
```
with solc-0.8.1
```
solc ~/C.sol --model-checker-engine all --model-checker-targets underflow
```
reports:
```
Warning: CHC: Underflow (resulting value less than 0) happens here.
Counterexample:

x = 0
 = 0

Transaction trace:
C.constructor()
C.f(0)
  --> C.sol:34:20:
   |
34 |     return x > 0 ? x - 1 : 0;
   |                    ^^^^^
```
Despite the fact that `x` is constrained to be larger than 0 in this path.
Translating the ternary to an if expression makes the error disappear.

**Comment by leonardoalt** [comment]
I guess we do need the `currentPathConditions` in the CHC targets, because the ternary operator is implemented using `visitBranch` and not blocks. But I'm not sure that would work, because the expressions given by `currentPathConditions()` might not fit what's in the current predicate
