### ISSUE TITLE
[Sol->Yul] Calldata string<->bytes conversion not implemented

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#10887]
## Description

```bash
$ solc --ir forwarder.sol

Internal compiler error during compilation:
/Users/distiller/project/libsolidity/codegen/YulUtilFunctions.cpp(2274): Throw in function std::__1::string solidity::frontend::YulUtilFunctions::readFromStorageDynamic(const solidity::frontend::Type &, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

compiling to "bin" or "asm" works correctly. only "--ir" fails.

## Environment

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.7.6+commit.7338295f.Darwin.appleclang
```

(verified that the same bug appears in 0.8 too)

## Steps to Reproduce

Attached [forwarder.zip](https://github.com/ethereum/solidity/files/5918806/forwarder.zip)

Genereated with:
```
git clone git@github.com:opengsn/gsn.git
cd gsn
yarn (for dependencies)
flat contracts/forwarder/Forwarder.sol > forwarder.sol
```

Its really tricky to find the minimal source to reproduce, since the crash doesn't provide any source line reference.
I could confirm that its not the external ECDSA library (can comment out the `openzeppelin`,`ECDSA`,`recover` lines and get same error)

Probably the cause is the usage of **abi coder v2**

**Comment by axic** [comment]
> compiling to "bin" or "asm" works correctly. only "--ir" fails.

`--ir` is a modifier, i.e. `--ir --bin` will return the bytecode after the IR, while `--bin` will return the bytecode through the legacy codegen.

> Probably the cause is the usage of abi coder v2

Please note that the `--ir` always uses abi coder v2 and the manual setting to v1 is ignored. It will also display a warning to that effect.

> Version: 0.7.6+commit.7338295f.Darwin.appleclang
> (verified that the same bug appears in 0.8 too)

I checked with `develop` and it still appears, albeit need to remove the pragmas in your example. Please note that while `--ir` was added a while back, it is only now by 0.8.1 when all the missing features we tracked were implemented.

It seems however this one slipped through:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp(3394): Throw in function std::__1::string solidity::frontend::YulUtilFunctions::arrayConversionFunction(const solidity::frontend::ArrayType &, const solidity::frontend::ArrayType &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

This seems to be some missing conversion implementation for converting calldata arrays. @mijovic is there a pending PR for this?

**Comment by axic** [comment]
Here's the minimal example:
```
contract C {
    function f(string calldata s) public {
        bytes(s);
    }
}
```

**Comment by chriseth** [comment]
Is it only for string <-> bytes conversion? should be a no-op.

**Comment by chriseth** [comment]
I guess that's also why we did not have a test.

**Comment by axic** [comment]
Yes it is a no-op, but should have a test :)
