### ISSUE TITLE
Solidity compiler error NatSpec multiple return value for struct in interface

### ISSUE THREAD

**Issue by moodysalem** [ethereum/solidity#10881]
## Description

Compiler throws error parsing multiple NatSpec `@return` annotations on an interface that documents the return values of what is implemented as a struct

```
Internal exception in StandardCompiler::compile: /Users/distiller/project/libsolidity/interface/Natspec.cpp(149): Throw in function static Json::Value solidity::frontend::Natspec::devDocumentation(const solidity::frontend::ContractDefinition &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

## Environment

- Compiler version: 0.7.6, 0.8.0, 0.8.1
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: solidity/hardhat 2.0
- Operating system: mac os

## Steps to Reproduce
This code reproduces the issue in remix.ethereum.org

```solidity
pragma solidity =0.7.6;

interface IThing {
    /// @return x a number
    /// @return y another number
    function value() external view returns (uint128 x, uint128 y);
}

contract Thing is IThing {
    struct Value {
        uint128 x;
        uint128 y;
    }

    Value public override value;
}
```

Related, moving the annotations to the override

```
DocstringParsingError: Documentation tag "@return" is only allowed once on state-variables. /// @return x a number ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by leonardoalt** [comment]
I *think* multiple `@return` tags are not allowed for the same item. Of course it should fail more gracefully than that if that's the case.
One way to make your code work is:
```
interface IThing {
    /// @return x a number, y another number
    function value() external view returns (uint128 x, uint128 y);
}
```

**Comment by moodysalem** [comment]
> I _think_ multiple `@return` tags are not allowed for the same item. Of course it should fail more gracefully than that if that's the case.

They are allowed for other functions (and this is explicitly documented to be how you handle multiple return variables) they just break here because of the implementation being a public struct state variable

> One way to make your code work is:

This gets it to compile but doesn't output equivalent docs

**Comment by hrkrshnn** [comment]
Tagging @Marenz

**Comment by moodysalem** [comment]
IMO the best solution to this removes the natspec generation from the solidity compiler. It's really rough that the compilation breaks due to this. Just break it out into its own tool or scrap it and let third parties build it

**Comment by hrkrshnn** [comment]
@moodysalem Which that sounds like a good idea, NatSpec, in its current state would be hard to implement externally. For example, it has to understand inheritance hierarchies; this is significantly easier to do it during the full compilation.
