### ISSUE TITLE
[Sol->Yul] ICE due to left shift being applied on non integer/fixed bytes type

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10895]
## Description

```
contract c{ function f() public{ fixed a; a <<4;}}
```

throws

https://github.com/ethereum/solidity/blob/7405dc5b7fa511626946591595d53c4bb0b28d41/libsolidity/codegen/YulUtilFunctions.cpp#L390

Shouldn't it throw unimplemented assertion instead because fixed point type is not yet implemented?

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by bshastry** [comment]
Reopening because

```
contract C{function f()public{fixed x;(x>>0);}}
```

when ```solc --ir test.sol``` throws 

https://github.com/ethereum/solidity/blob/7405dc5b7fa511626946591595d53c4bb0b28d41/libsolidity/codegen/YulUtilFunctions.cpp#L413

**Comment by bshastry** [comment]
Oops, looks like `fixed` type shift amount also leads to a different failure

```
contract c{function f()public{fixed a;a<<a;}}
```

throws

https://github.com/ethereum/solidity/blob/43319574e79ec2664cc3e547e11b7d635f25ca0f/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L2753

**Comment by hrkrshnn** [comment]
These fixed point failures are just annoying. All they need is adding another assert.

Maybe the fuzzer can be configured to ignore fixed point declarations somehow, at least until fixedpoint type is properly implemented?

**Comment by bshastry** [comment]
> These fixed point failures are just annoying. All they need is adding another assert.
> 
> Maybe the fuzzer can be configured to ignore fixed point declarations somehow, at least until fixedpoint type is properly implemented?

They can be selectively ignored if they throw a specialized assertion. However, current fuzzers don't have a notion of fixed point type. Grammar based fuzzing is in the works but it is going to take a while :(

**Comment by mijovic** [comment]
Created another PR, checked for both left and right shift
Hope this time it will fix it finally :)
