### ISSUE TITLE
[Docs] Avoid search results showing docs of old Solidity versions instead of newer ones

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#10898]
It seems that by adding a ``robot.txt`` file in the documentation folder we can specify which versions should be ignored by search engines for indexing, means we can disallow ranking old versions in the search results instead of new versions. 

Resources:
- This is how python does it (as an example): https://docs.python.org/robots.txt
- [How to use a robot.txt file in the readthedocs docs](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file)
- [Readthedocs "How can I avoid search results having a deprecated version of my docs?"](https://docs.readthedocs.io/en/stable/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs)

**Comment by axic** [comment]
Interesting. What would we consider deprecated? Anything older than 3 breaking releases? A decision based on the user survey?

**Comment by franzihei** [comment]
I'd deprecate everything older than 0.6.0.

Edit: Or, actually, if we wanted to promote updating more, we should consider "deprecating" everything that's older than 0.7.x. It will just mean the results won't be shown in Google search. People can still browse the Solidity docs for all versions.

<img width="943" alt="SolidityVersion" src="https://user-images.githubusercontent.com/41991517/107752295-cff02380-6d1e-11eb-9244-e93328f237ec.png">

**Comment by chriseth** [comment]
Sounds good!

**Comment by axic** [comment]
Implemented by #10972 and #11199.

@chriseth @franzihei Right now it seems that only 0.8.0 shows up for me on the top. I think a weird side effect we are getting is that while previously a lot of various versions popped up on the first page of results, the majority of the links went to docs.soliditylang.org. Compared to that, now the first link is docs.soliditylang.org and the rest is random others.

**Comment by cameel** [comment]
I'm going to reopen this since the correct `robots.txt` is currently not being served (#11666 fixes it) and so far we still have not achieved the ultimate goal of this issue - search engines have not droped the older versions from their index yet.
