### ISSUE TITLE
[soltoyul] ICE due to invalid use of selector function

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10891]
## Description

```
contract B {
  function g() public {}
}
contract C is B {
  function h() public { g.selector; }
}
```

throws

https://github.com/ethereum/solidity/blob/8a4e6acdac8d11ee671f084d96d82de63f684812/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L1699

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc --ir test.sol
```

**Comment by hrkrshnn** [comment]
I don't know why we allow the above code to be compiled in the old codegen. I think we should only allow the usage of `this.g.selector`.

**Comment by hrkrshnn** [comment]
@ekpyron Just saw that this was allowed in https://github.com/ethereum/solidity/pull/8137/files#diff-5cc133bfc337e9ca7fe7ee9842d5ddfa492fa559149cf8acec4a7d9ede50c9aaR2980

Is there a reason why we allow `g.selector` despite being an internal function call?

**Comment by cameel** [comment]
@hrkrshnn It's even worse. Rules are different for `.address` and `.selector` and there are more factors that affect what is allowed and what is not. The rules seem pretty random to me. I think this is a separate issue so reported as #10905 (see the example I included there). For the ICE here I think it's best to assume that if it passes on the old codegen, it should work with IR too.

**Comment by ekpyron** [comment]
As mentioned in the issue: it does make sense that the rules for ``.address`` and ``.selector`` are different...
We could of course disallow ``.selector`` for functions unless they are explicitly referred to in external calling context. But why would we?

So as to:

> @ekpyron Just saw that this was allowed in https://github.com/ethereum/solidity/pull/8137/files#diff-5cc133bfc337e9ca7fe7ee9842d5ddfa492fa559149cf8acec4a7d9ede50c9aaR2980
> 
> Is there a reason why we allow `g.selector` despite being an internal function call?

I would ask the contrary: is there any particular reason for *not* allowing it :-)? Those are functions that *can* be used externally, so all of them do have selectors. I'd be fine with disallowing to query them unless explicitly used in external calling context, but I also don't see a really good reason why one necessarily should.

**Comment by ekpyron** [comment]
I mean you say ``g`` being an internal function, whereas ``this.g`` is an external function... if you look at it that way, probably only the latter should get ``.selector``.
But you can also look at ``g`` being a *public* function (that's how it's declared) - so it generally has a ``.selector`` member. Just ``g(...)`` vs ``this.g(...)`` are ways to *call* this one *public* function internally or externally...

On the other hand we also only allow ``function() external x = this.g;`` not ``function() external x = g;``...

But yeah: the reason for allowing it was that we do have the information to produce a selector on ``g``, so we *can* allow it :-). But as I said, I'd also be fine with disallowing it - note that that's a breaking change, though, strictly speaking.

**Comment by ekpyron** [comment]
So maybe best just to implement it for sol->yul for now and we can keep an issue about disallowing it, if we want to do that.

**Comment by hrkrshnn** [comment]
My main issue is that

``` 
  contract C {
	  function f() public {
	  }
	  function g() public {
		  f.selector;
	  }
  }
```
produces
```
 Error: Member "selector" not found or not visible after argument-dependent lookup in function ().
 --> <stdin>:5:3:
  |
5 | 		f.selector;
  | 		^^^^^^^^^^
```

whereas

```
  contract D {
	  function f() public {
	  }
  }
  contract C is D {
	  function g() public {
		  f.selector;
	  }
  }
```
compiles fine.

If we are allowing `f.selector`, just because we can compute the selector, then I think both cases should be allowed.

**Comment by chriseth** [comment]
Both cases should be disallowed, internal functions do not have selectors. So to me, this is an issue with inheritance and we should check if there is any deeper problem.

**Comment by ekpyron** [comment]
In the end I think the reason this is allowed is since we wanted to be able to globally access the selector via the contract name, i.e.
```
contract B {
  function f() external {}
  function g() public {}
}
contract C {
  function h() public {
     B.f.selector;
     B.g.selector;
  }
}
```

Even or especially if ``C`` does *not* inherit from ``B``.
But then it would be weird, if changing this to having ``C`` inherit from ``B`` were to change this, so we wanted to allow it for that case, too. But, unfortunately, in that case ``B.g`` internally has the same type as ``g``, so it so happens that allowing ``B.g.selector`` meant to also allow ``g.selector``.

The alternative was basically https://github.com/ethereum/solidity/pull/8137/files#r367386872, i.e. to introduce one or even two more function type kinds to distinguish these... or we'd need to typecheck our way out of it, disallowing the ``g.selector`` on pain of it not being a member access via contract name...

In any case I'd still say this should be implemented in Sol->Yul (it's not like that would be hard to do) - and then we can decide whether we want to introduce more complexity to disallow the rather weird artifact cases.

**Comment by ekpyron** [comment]
Note that
```
pragma experimental SMTChecker;

contract B {
  function f() external {}
  function g() public {}
}

contract C is B {
    function h() public {
        B.f.selector; B.g.selector;
    }
}
```
also throws in Sol->Yul for the same reason, while removing ``is B`` does not. And at least this should work, independently of what we should do about ``g.selector``.
