### ISSUE TITLE
[soltoyul] ICE in IR generator due to invalid yul code generation

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10890]
## Description

This is a meta-issue for all Sol->Yul code gen failures

- [x] https://github.com/ethereum/solidity/issues/10916
- [x] https://github.com/ethereum/solidity/issues/10917
- [x] https://github.com/ethereum/solidity/issues/10918
- [x] https://github.com/ethereum/solidity/issues/10919
- [x] https://github.com/ethereum/solidity/issues/10920

**Comment by bshastry** [comment]
Another (different) test case that leads to the same ICE but looks like a different issue at first glance

```
contract C { function() external  x;function f() public {delete x; }}
```

**Comment by bshastry** [comment]
One more test case that fails with the same ICE

```
contract C {
  function() external returns (int) x;
  function f() public { delete x; }
}
```

**Comment by bshastry** [comment]
Another one

```
contract D {
  constructor(function() external returns (uint)) {}
}
```

**Comment by hrkrshnn** [comment]
The first two are about switch statements and the last two are about mismatch in function arguments. [Here](https://gist.github.com/hrkrshnn/331a7447477238cf6c6375f54ed634ea) is the output. I'll take another look later.

**Comment by bshastry** [comment]
> The first two are about switch statements and the last two are about mismatch in function arguments. [Here](https://gist.github.com/hrkrshnn/331a7447477238cf6c6375f54ed634ea) is the output. I'll take another look later.

Thanks for the gist. It looks like the problem is function `modifier_A_10` is not generated but called.

**Comment by bshastry** [comment]
Another example with new codegen against spuriousdragon

```
contract C {
function f() public returns (bool success) {
    (success, ) = (address(0)).call{value: 30}("");
}
}
```

To reproduce

```
$ solc --evm-version spuriousDragon --ir test.sol
```

**Comment by axic** [comment]
All the linked issues seem to be working now. @bshastry please reopen if you think this should be kept open.
