### ISSUE TITLE
Bob has no permissions to solidity repo :-(

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#1089]
I cannot even merge PRs or commit, let alone access Settings (though I don't think I need to do anything with keys which would required that access right now).    Might be needed for PPAs, though.

**Comment by axic** [comment]
You have been hit with the same thing I'm and others' are getting :(

**Comment by bobsummerwill** [comment]
Yep.   @chriseth had a quick look, and tried to add me manually, but it didn't help.

My issue is **only** for the solidity repo, as far as I can see.    You, @axic?

**Comment by axic** [comment]
@bobsummerwill well I cannot merge anything now (not that I did that before), and occasionally I cannot even add labels or push to PRs.

**Comment by bobsummerwill** [comment]
Just for this one repo, right?   `evmjit` works just fine for you?

**Comment by axic** [comment]
`evmjit`, `browser-solidity`, `solc-js` seem to work.

**Comment by chriseth** [comment]
Sent a mail to the github team.

**Comment by axic** [comment]
Thanks @chriseth

**Comment by chriseth** [comment]
@bobsummerwill is this fixed?

**Comment by bobsummerwill** [comment]
I can't tell, because the Merge button on all the PRs for Solidity is greyed out because of the new protected-branch "automation must pass" blocker.   I don't have an override option.

So ... I don't know, because there is nothing in a state where I am would have the option to merge.

If any of the Solidity PRs get to the stage where they go green, I will check there.
