### ISSUE TITLE
warnings going to stdout

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#109]
I highly doubt you intended for the output of `solc` to be a bunch of warning text followed by the --combined-json text. Anything that parsed json from solc output is broken now

I guess warnings should go to stderr instead? Or at least give us the option to turn off the warnings

**Comment by chriseth** [comment]
Thanks for your report! Of course, warnings should certainly go to stderr and not to stdout and on my system they also do.
How do you run solc and on which system? Are you sure you do not combine both streams at some point?
Here is the relevant line in the source: https://github.com/ethereum/solidity/blob/develop/solc/CommandLineInterface.cpp#L497

**Comment by nmushegian** [comment]
I'm not sure but on second thought you are right this is probably us merging them somewhere
