### ISSUE TITLE
[Improving documentation] Why was solidity created?

### ISSUE THREAD

**Issue by akshithg** [ethereum/solidity#1090]
- What were the reasons that led to formulating Solidity (a new language from scratch)?
- Why wasn't an existing language used?

I have not been able to find answers to the above. Hence the issue.

**Comment by jonathanbmorley** [comment]
Hi, askshithg.

http://ethdocs.org/en/latest/contracts-and-transactions/contracts.html has a nice write-up: "Contracts live on the blockchain in an Ethereum-specific binary format (EVM bytecode) that is executed by the Ethereum Virtual Machine (EVM). However, contracts are typically written in a higher level language and then compiled using the EVM compiler into byte code to be deployed to the blockchain."

**Comment by jonathanbmorley** [comment]
Also see the FAQ section: http://solidity.readthedocs.io/en/latest/frequently-asked-questions.html

"Solidity is the DEV-created (i.e. Ethereum Foundation-created), Javascript-inspired language that can be used to create smart contracts on the Ethereum blockchain. There are other languages you can use as well (LLL, Serpent, etc). The main points in favour of Solidity is that it is statically typed and offers many advanced features like inheritance, libraries, complex user-defined types and a bytecode optimizer."
