### ISSUE TITLE
Multiple copies of imported contracts compiled into bytecode

### ISSUE THREAD

**Issue by area** [ethereum/solidity#1092]
Is this expected behaviour?

```
pragma solidity ^0.4.1;
import "SomeLargeContract.sol";

contract Test{

    address x;
    function test1(){
        x = new SomeLargeContract();
    }

}
```

Cost to deploy: ~900000 gas

```
pragma solidity ^0.4.1;
import "SomeLargeContract.sol";

contract Test{

    address x;
    function test1(){
        x = new SomeLargeContract();
    }
    function test2(){
        x = new SomeLargeContract();
    }
}
```

Cost to deploy: ~1800000

I definitely would have expected SomeLargeContract to have been included once, and then accessed by some reference in the bytecode in each instance, but based on the gas costs that's clearly not happening.

**Comment by axic** [comment]
A simpler example:

```
pragma solidity ^0.4.1;

contract SomeLargeContract {
}

contract Test{
    function test1(){
        new SomeLargeContract();
    }
    function test2(){
        new SomeLargeContract();
    }
}
```

In the bytecode each `new contract` becomes an included block. It should optimise out if they are the same contracts.
