### ISSUE TITLE
Codegen runs into invalid swap request (17)

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/solidity#10931]
I'm working off of 

```
Version: 0.8.2-develop.2021.2.5+commit.2fb27884.Linux.g++
```
and don't know what caused this error but now i can't get away from it 

```
CompileError: Exception during compilation: /solidity/libevmasm/Instruction.h(267): Throw in function solidity::evmasm::Instruction solidity::evmasm::swapInstruction(unsigned int)
Dynamic exception type: boost::wrapexcept<solidity::evmasm::InvalidOpcode>
std::exception::what: InvalidOpcode
[solidity::util::tag_comment*] = Invalid SWAP instruction requested (17).
```

**Comment by axic** [comment]
This seems to be some code generation error on the regular EVM path (note `libevmasm`).

Can you post the source code please?

**Comment by axic** [comment]
@fxfactorial can you share the offending source code? It is hard to figure out what is going on without it.

**Comment by fxfactorial** [comment]
Sorry friends, I since lost this code and fixed it in another way, now don't have it. 

sorry for the noise/distraction
