### ISSUE TITLE
Add interface generator to "tools" section

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1093]
This is a script that takes the ABI and generates contract interfaces from it:

https://gist.github.com/chriseth/8f533d133fa0c15b0d6eaf3ec502c82b

This should be useful as a standalone commandline tool and as a "refactoring tool" inside browser-solidity.

**Comment by ChrisChinchilla** [comment]
@chriseth I tested the script, and it seems to still work and be valid, might be nice in the long run to break this out into a repo with basic docs etc. In the meantime, I'll create a PR.
