### ISSUE TITLE
[Yul Opti] Consider changing the inline heuristic to allow inlining into bigger functions

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10938]
We can consider changing the heuristics for inlining. Say, increase the size limit of "really, really tiny functions." 

https://github.com/ethereum/solidity/blob/develop/libyul/optimiser/FullInliner.cpp#L174-L184

This would be especially important inlining unchecked arithmetic function calls (maybe even checked?)

An example of a function that is currently not inlined and may actually be inlined would be: https://gist.github.com/hrkrshnn/95451bd4579d69177051777ade557795#file-beforefunctionspecializer-yul-L211 (call site: https://gist.github.com/hrkrshnn/95451bd4579d69177051777ade557795#file-beforefunctionspecializer-yul-L30)

**Comment by chriseth** [comment]
This is true. Originally, this was not done due to fear of increased stack pressure. Since we do optimized stack slot allocation, inlining functions should actually not increase stack pressure at all, rather the opposite.

**Comment by chriseth** [comment]
Ah ok, this is actually not totally true: In a function call, arguments are brought up to the top of the stack, so the "working variables" are closer to the stack top than they would be in the inlined version.

**Comment by ekpyron** [comment]
Ideally, we wouldn't rely on that happening due to the function call, but just have an algorithm recognize the minimum amount of ideal places at which to shuffle variables, s.t. stack problems are avoided... still not sure how easy that is, though...

**Comment by chriseth** [comment]
I think this issue here is caused by too much inlining: https://github.com/ethereum/solidity/issues/10930

**Comment by ekpyron** [comment]
> I think this issue here is caused by too much inlining: #10930

Yeah, at a quick glance I think that's an instance of the prototypical example of the most common abiv2 related stack height issues we currently have...
