### ISSUE TITLE
Solc 0.4.1 throws an exception on a library compilation

### ISSUE THREAD

**Issue by asinyagin** [ethereum/solidity#1094]
Hi,

I have a library:

```
library ConvertLib{
    function convert(uint amount,uint conversionRate) returns (uint convertedAmount)
    {
        return amount * conversionRate;
    }
}
```

And solc fails if I try to compile the library:

```
root@ce27cd0e9bf7:~/workspace/my-truffle-project/contracts# solc ConvertLib.sol 
Internal compiler error during compilation:
/build/solc-24Vd54/solc-0.4.1/libsolidity/interface/Version.cpp(68): Throw in function dev::bytes dev::solidity::binaryVersion()
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = 
```

Solc version:

```
root@ce27cd0e9bf7:~/workspace/my-truffle-project/contracts# solc --version
solc, the solidity compiler commandline interface
Version: 0.4.1+commit.4fc6fc2.Linux.g++
```

**Comment by chriseth** [comment]
Hm, this was supposed to be fixed for 0.4.1. Where did you get the compiler from?
Ah, the reason might be that there is a hex digit missing in the commit hash.

**Comment by asinyagin** [comment]
From the ethereum ppa (stable one).

**Comment by axic** [comment]
> Ah, the reason might be that there is a hex digit missing in the commit hash.

The short git hash is 7 digits for some weird reason.

**Comment by pipermerriam** [comment]
I'm getting the same error.  `solc` installed via brew

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.1+commit.4fc6fc2.Darwin.appleclang
```

**Comment by axic** [comment]
I've tried the same version in browser-solidity, there it works. Can you try also? It maybe some weird issue not present in the JSONCompiler.

**Comment by chriseth** [comment]
Browser-solidity is compiled in a different way. The ppa is not compiled with a `.git` directory present, so the way to tell cmake what the current commit hash is different.

**Comment by madvas** [comment]
I have exactly the same problem. 

my version: 

```
solc, the solidity compiler commandline interface
Version: 0.4.1+commit.4fc6fc2.Darwin.appleclang
```

**Comment by chriseth** [comment]
Fear not, the fix is on its way. The problem is that most of us are on our way to shanghai now. Still, I hope we can make a new release before devcon starts.
