### ISSUE TITLE
[Sol->Yul] Consistently fail on fixed point types

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10941]
Meta issue for Sol->Yul fixed point failures could be signaled as such

- [x] https://github.com/ethereum/solidity/issues/10939
- [x] https://github.com/ethereum/solidity/issues/10940

**Comment by mijovic** [comment]
There might be some other places where it still happens, but since the two which are listed are solved, I'm closing this one now.
We can reopen with new cases if needed
