### ISSUE TITLE
[yul] Long run time of reasoning based simplifier against tests with nested expressions

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10954]
## Description

The following test case hogs memory and does not complete for over several minutes. Tagged as fuzz blocker because this test input exhausts memory allocated to fuzzing process, crashing it in the process and/or takes too long to complete.

```
{
        let x_0 := sdiv(
                0x800000000000000000000000000000000000000,
                sdiv(
                        sdiv(
                                0x8000000000000000000000000000000000000000,
                                0x80000000000000000000000000000000000000000
                        ),
                        sdiv(
                                0x800000000000000000000000000000000000000000,
                                sdiv(
                                        sdiv(
                                                0x8000000000000000000000000000000000000000000,
                                                0x80000000000000000000000000000000000000000000
                                        ),
                                        0x800000000000000000000000000000000000000000000
                                 )
                          )
                )
        )
}
// ====
// EVMVersion: >=constantinople
// ----
// step: reasoningBasedSimplifier
```

## Environment

- Compiler version: latest develop
- Operating system: Ubuntu x86_64 focal, 

## Steps to Reproduce

```
// Copy test case to a file called test/libyul/yulOptimizerTests/reasoningBasedSimplifier/test.yul
$ isoltest -t yulOptimizerTests/reasoningBasedSimplifier/test
```

**Comment by cameel** [comment]
I have also noticed that `ReasoningBasedSimplifier` is orders of magnitude slower than any other step while running yul-phaser. Especially on longer input like `test/libyul/yulOptimizerTests/fullSuite/aztec.yul` it takes minutes per round compared to less than a second when this step is disabled (see https://github.com/ethereum/solidity/pull/10080#discussion_r571105586).

**Comment by hrkrshnn** [comment]
This is not that surprising.

`sdiv` is encoded as

```
smtutil::Expression::ite(
			arguments.at(1) == constantValue(0),
			constantValue(0),
			// No `wrap()` needed here, because -2**255 / -1 results
			// in 2**255 which is "converted" to its two's complement
			// representation 2**255 in `signedToUnsigned`
			signedToUnsigned(smtutil::signedDivisionEVM(
				unsignedToSigned(arguments.at(0)),
				unsignedToSigned(arguments.at(1))
			))
```

`unsignedToSigned` and `signedToUnsigned` is encoded as another `ite` (if then else) statement. `signedDivisionEVM` is encoded by `ite(..., ite(...), ite(...))`. 



Each `ite` would introduce two branches. In the end, there is just too much branching even just for one `smod`.

Maybe the model checker settings for z3 should also apply for the optimizer and then we could set a timeout for z3.

**Comment by hrkrshnn** [comment]
On second thought, the expression can be evaluated right away. So not sure if it really needs so much branching. It turns out that we don't even call the `Z3Interface::check(..)` function which would be the most expensive, solving part. Not sure what's really happening here.

**Comment by chriseth** [comment]
The component is deactivated for a reason, but we should indeed investigate what takes that much time.

**Comment by bshastry** [comment]
Another test case that drains memory

```
object "object0" {
code {
{
let x_0 := 0x100001
let x_2 := shl(x_0,sdiv(0x1001,shr(sdiv(x_0,smod(sdiv(x_0,datasize("object0")),0x101)),x_0)))
let x_5 := datasize("object0")
}
}
data "datablock" hex"1f"
}
// ----
// step: reasoningBasedSimplifier
```
