### ISSUE TITLE
[libyul] ICE due to assignment statement not having variable type

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10975]
## Description

```
contract C{function f() {assembly{function f() {} f := 1}}}
```

throws

https://github.com/ethereum/solidity/blob/c812d928fd5adfdadc6a4ccbf03e5af916598a11/libyul/AsmAnalysis.cpp#L535

Probably related to https://github.com/ethereum/solidity/pull/10964

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by hrkrshnn** [comment]
Interesting how quickly the fuzzer was able to find this bug.
