### ISSUE TITLE
ICE in solidity/libsolidity/ast/AST.cpp

### ISSUE THREAD

**Issue by rvantonder** [ethereum/solidity#10988]
## Description

`solc` crashes on this program:

```solidity
abstract contract D {
    function gsf() public {}
    function tgeo() public {}
}
contract C {
    D d;
    function g() public returns (uint) {
        d.d;
    }
}
```

with

```
Internal compiler error during compilation:
/solidity/libsolidity/ast/AST.cpp(103): Throw in function map<util::FixedHash<4>, solidity::frontend::FunctionTypePointer> solidity::frontend::ContractDefinition::interfaceFunctions(bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Hash collision at Function Definition Hash calculation
[solidity::util::tag_comment*] = Hash collision at Function Definition Hash calculation
```

Found on master @ 055c4b4d44874fa13ab163054a5d717cd78417b2

Part of the fuzzing project https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version: Version: 0.8.1-develop.2021.1.19+commit.055c4b4d.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: 18.04.5 LTS

## Steps to Reproduce

```bash
cat <<EOF | solc - 
abstract contract D {
    function gsf() public {}
    function tgeo() public {}
}
contract C {
    D d;
    function g() public returns (uint) {
        d.d;
    }
}
EOF
```

**Comment by bshastry** [comment]
Thank you for reporting this issue @rvantonder 

For what it's worth, this minimal example reports the correct (better) error

```
abstract contract D {
  function gsf() {}
  function tgeo() public {}
//  D d;
  function g(){ }  //d.d; }
}
```

Uncomment to reproduce the crash. Since correct error reporting path exists, I suspect that something is going wrong while type checking the commented statement/function.

**Comment by hrkrshnn** [comment]
This is because, even though `noErrors` is false after `contractLevelChecker`, we still do the `DocStringAnalyser` and `TypeChecker`. 

See:
https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/CompilerStack.cpp#L382

There are two ways around this. Either we wrap the `TypeChecker` inside an `if (noErrors) { ... }`. Or we change the hash collision error into a `fatalTypeError`, which would immediately throw. I wonder why we didn't implement the former in the first place?
