### ISSUE TITLE
Compiler flag to set bytecode size limit

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10981]
From https://github.com/ethereum/solidity/issues/2691#issuecomment-752231692

Custom chains may allow deploying contracts bigger than 24 kB but the limit is currently hard-coded in the compiler and exceeding it triggers a warning that can't be suppressed. In #2691 it was proposed that the solution might be to introduce a compiler flag that allows the user to change the limit to an arbitrary value and avoid the warning.

**Comment by axic** [comment]
During today's design meeting we have discussed two alternative approaches:  #11006/#11008 and #11010. It seems we are leaning towards #11006 and having filtering in frameworks (such as hardhat and truffle).

As a trivia, this warning was added as per discussions on #2100.

**Comment by cameel** [comment]
I wonder if it might be better to offload this check to frameworks after all. In Hardhat, Truffle and Brownie (and likely most others) you define a list of networks, each with specific settings like gas limit. [Hardhat's network settings](https://hardhat.org/config/#hardhat-network) even have `allowUnlimitedContractSize` which looks like a flag made specifically to ignore this warning :) These network settings rather than the compiler are the best place to configure something like that in my opinion.

Maybe just removing the warning and coordinating with frameworks to add a check there (with a good default) would be best?

**Comment by axic** [comment]
> I wonder if it might be better to offload this check to frameworks after all.

To be fair the warning was [encouraged by hardhat](https://github.com/ethereum/solidity/issues/2100#issuecomment-565460466):
> I know this could be implemented in each tool (e.g. truffle, remix, embark, buidler, etc), but I think implementing it as a solc warning would be the simplest path to improve the situation for most users.

Perhaps @alcuadrado changed his mind since?

However @cameel, on the other hand I think that frameworks which have a setting like `allowUnlimitedContractSize`, when set, could also just filter out the warning based on the error code (a la #11006).

**Comment by cameel** [comment]
True. They could. @gorgos, are using the compiler directly or via a framework?

> To be fair the warning was [encouraged by hardhat](https://github.com/ethereum/solidity/issues/2100#issuecomment-565460466)

Yeah, that's what I actually referring to. It was encouraged back then but maybe it would be better to talk it over again given that we're now discovering that we don't really have enough info in the compiler to decide if it's warranted or not (at least with adding extra flags for the user to provide that info).

**Comment by gorgos** [comment]
@cameel Via framework, both Truffle and Hardhat.

**Comment by cameel** [comment]
Looks like we'll probably address this problem in a different way: #11508.
