### ISSUE TITLE
[SMTChecker] ICE in toZ3Expr for homestead, spuriousdragon, and tangerineWhistle

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10985]
## Description

```
pragma experimental SMTChecker;
contract C {
  struct S {
    string a;
    uint256 y;
  }
  S public s;
  function g() public returns (uint256) {
    this.s();
  }
}
```

throws

https://github.com/ethereum/solidity/blob/6fd5ea01d1c943b7b40afbc72fcb60be3bb2a78a/libsmtutil/Z3Interface.cpp#L270

## Environment

- Compiler version: 6fd5ea01d
- Target EVM version (as per compiler settings): homestead/spurious dragon
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc --evm-version homestead test.sol
```

**Comment by cameel** [comment]
The error I'm getting here (tested on 0.8.1) is the same as the one in #10986 that I have just reported:

```
SMT logic error during analysis:
/solidity/libsmtutil/Z3Interface.cpp(270): Throw in function z3::expr solidity::smtutil::Z3Interface::toZ3Expr(const solidity::smtutil::Expression&)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Sorts Int and bytes_tuple are incompatible
[solidity::util::tag_comment*] = Sorts Int and bytes_tuple are incompatible
```

**Comment by bshastry** [comment]
> The error I'm getting here (tested on 0.8.1) is the same as the one in #10986 that I have just reported:
> 
> ```
> SMT logic error during analysis:
> /solidity/libsmtutil/Z3Interface.cpp(270): Throw in function z3::expr solidity::smtutil::Z3Interface::toZ3Expr(const solidity::smtutil::Expression&)
> Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
> std::exception::what: Sorts Int and bytes_tuple are incompatible
> [solidity::util::tag_comment*] = Sorts Int and bytes_tuple are incompatible
> ```

Are you able to reproduce it against EVM versions other than homestead and spuriousDragon?

**Comment by cameel** [comment]
Yeah, `tangerineWhistle`.

`tangerineWhistle`, `homestead` and `spuriousDragon`: ICE.
`byzantium`, `constantinople`, `petersburg`, `istanbul` and `berlin`: OK.

I think that's all of them.

**Comment by bshastry** [comment]
> Yeah, `tangerineWhistle`.
> 
> `tangerineWhistle`, `homestead` and `spuriousDragon`: ICE.
> `byzantium`, `constantinople`, `petersburg`, `istanbul` and `berlin`: OK.
> 
> I think that's all of them.

Thank you. I'm wondering if version specific issues may have a different root cause, or if it's better to just move this to #10986 Wdyt?

**Comment by cameel** [comment]
I'm not sure. They could be caused by different things that just trigger the same generic message at a higher layer. The error here seems to be related to returndata not being available in these EVM versions (we have a public getter that returns a struct). #10986 on the other hand consistently fails regardless of EVM version (I just checked them all).

**Comment by bshastry** [comment]
Another ICE for the specific evm versions in this issue

```
pragma experimental SMTChecker;
contract C{function f()public returns(bool[]memory){this.f();}}
```

throws

https://github.com/ethereum/solidity/blob/093ea4612bd2f2d99807fa3a12e8e45365e581ee/libsmtutil/SolverInterface.h#L263
