### ISSUE TITLE
[Sol->Yul] ICE because "No code generated for function even though it is not a constructor."

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11007]
## Description

```
contract B {
  function g() public {}
}
contract C is B {
  bytes4 constant s2 = B.g.selector;
}
```

throws

https://github.com/ethereum/solidity/blob/2d48052ae50017bc41d8c85f1628b97352e73dcb/libsolidity/codegen/ir/IRGenerator.cpp#L67-L70

when compiled via new code gen `solc --ir test.sol`

Probably related to https://github.com/ethereum/solidity/pull/10973

**Comment by bshastry** [comment]
The issue is related to referencing the selector via base contract i.e., `B.g.selector`. If we do `this.g.selector` instead, the ICE goes away.

**Comment by bshastry** [comment]
Also, the issue is related to `public` functions. For external functions, the ICE does not reproduce (see below)

```
contract B {
  function g() external {}
}
contract C is B {
  bytes4 constant s2 = B.g.selector;
}
```

**Comment by chriseth** [comment]
It's really good to have the fuzzer! This is related to the callgraph PR.
