### ISSUE TITLE
[CLI] Add a way to filter error codes

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11008]
If we have #11006, that means framework can filter warnings/errors based on error codes. If we advocate/allow that, then we may want to consider adding a way to filter error codes on the command line, i.e. `--ignore-errors <comma separated error codes>`.

**Comment by axic** [comment]
I am personally not fully sold on having this, but created the issue for completeness and a way to discuss this.

**Comment by chriseth** [comment]
I'm also not fully sold. For casually calling `solc *.sol`, this is not required. If you do anything more fancy, then you probably use a framework that has a project settings file which can contain any filtering instructions the framework can do.
