### ISSUE TITLE
msg.data cannot be used inside a receive() function

### ISSUE THREAD

**Issue by sirhill** [ethereum/solidity#11002]
I am migrating from 0.6.12 to 0.8.1 and I am now having this error message:
`CompileError: TypeError: "msg.data" cannot be used inside of "receive" function.`

However, if I move the `msg.data` reference inside a sub function called directly from inside the receive() function it can still work. This is somehow confusing.

I can understand the intent, but all transactions in Ethereum have a `msg.data` even if this one is expected to be null from the receive() context. I do think that it is still relevant to use semantically `msg.data`.

Furthermore, I was unable to find it documented somewhere.

**Comment by hrkrshnn** [comment]
I find it weird that `msg.data` cannot be accessed inside `receive()`, but it can call an internal function that can access `msg.data`. Even though, `msg.data` would be empty. Maybe we should also disallow it for consistency?

**Comment by chriseth** [comment]
This is a warning that prevents you from making the invalid assumption that `msg.data` contains useful information inside a `receive` function. As often, most warnings are tailored towards the "regular user" who does not write proxy contracts or anything deeply involved and will hopefully be thankful about such a warning.

**Comment by sirhill** [comment]
It is not a warning but a compilation error.

Your intent was interesting and very valuable.
However, it can also be confusing for a regular user that it can't use `msg.data` (which he will trivially - I think - understand it's null if he is interested to use `receive()` in the first place).

**Comment by sirhill** [comment]
I think that you are also maybe assuming that `msg.data` should not be null and that it should be considered harmful to use it when it's null. Depending of the use case, it can also be a perfectly reasonable value, such as an `if test` checking for the presence or not of such `msg.data`.

**Comment by cameel** [comment]
Maybe we should change it form error to warning then?

**Comment by sirhill** [comment]
If so, I think that maybe, it should rather be a solhint rule as it is quite an opiniated choice.

**Comment by droconnel22** [comment]
I am running into this very compiler error* for upgrading a legacy contract from 0.5.14. to 0.8.2. Is it best practice to remove/refactor the usage of `msg.data` or to even refactor from `receive` to `fallback`? I am not comfortable with just changing the solhint error to a warning.

**Comment by droconnel22** [comment]
Update: I was able to change the lines:




     receive () payable external {

       // throws solhint error 

       (bool success, ) = myImplContract.delegatecall(msg.data);

       ...


to


    receive () payable external {
        bool success = _mySubfuc();
        ....
    }
 
     function _mySubfuc() private returns(bool) {
          (bool success, ) = myImplContract.delegatecall(msg.data);
          return success;
      }


What is the logic/ justification for allowing this pattern?

**Comment by cameel** [comment]
@droconnel22 `msg.data` is empty in `receive`. Why do you want to pass it to the `delegatecall()`?

If you meant to use a payable `fallback` rather than receive then this is exactly the situation this warning is about. You do not get it when use `msg.data` in a function you call because that function might be called also from places other than `receive` that do have non-empty `msg.data`.

**Comment by bshastry** [comment]
This is an error. Perhaps, we can make it a warning?

```
contract C {
  receive() payable external { msg.data; }
}
```

**Comment by chriseth** [comment]
I would like to see some examples first where you cannot just use an empty calldata byte array instead.

**Comment by axic** [comment]
The `receive` function is supposed to be for non-data payment transactions (i.e. regular eth transfers).

Any other payable function is for received value with `msg.data`.

And for the generic case (proxies, etc.) there is the payable `fallback` function.
