### ISSUE TITLE
[SMTChecker] Unknown exception during compilation: map::at

### ISSUE THREAD

**Issue by vporton** [ethereum/solidity#11022]
## Description

https://github.com/vporton/sol-8.0.1-crash demonstrates a Solidity compiler bug:

```
yarn
...
yarn build
...
Unknown exception during compilation: map::at
Error HH600: Compilation failed
```

## Environment

- Compiler version: 8.0.1
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): HardHat
- Operating system: Ubuntu

```solidity
// Token.sol
pragma solidity ^0.8.0;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract Token is ERC721 {
    constructor() ERC721("Token", "TKN") { }
}

// Controller.sol
pragma solidity ^0.8.0;
pragma experimental SMTChecker;

import {Token} from "./Token.sol";

contract Controller {
    function initialize(Token _parcelToken) public { }
}
```

**Comment by leonardoalt** [comment]
Thanks for reporting!
The bug is triggered by the SMTChecker analysis (`pragma experimental SMTChecker;`), but I still haven't checked what exactly causes it.

**Comment by blishko** [comment]
I reproduced this crash in `0.8.1`, got a different crash in `0.8.2`, but no crash in `develop`.
There has been several fixes regarding crashes in SMTChecker recently
It looks like some of them fixed also this issue.

**Comment by leonardoalt** [comment]
@vporton please reopen if needed
