### ISSUE TITLE
Compiler ignores files located under the base path in Standard JSON

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11038]
Related to #11036.

## Description
With `--standard-json` the compiler does respect `--base-path` in imports but not in the Standard JSON itself. Even if a file is present under the base path in the virtual filesystem, the compiler won't use it. It will read it from disk if available though.

`input.json`
```json
{
    "language": "Solidity",
    "sources": {
        "/tmp/x/y/a.sol": {"content": "import \"b.sol\";"},
        "/tmp/b.sol":     {"content": "contract B {}"}
    },
    "settings": {"outputSelection": {"*": { "*": []}}
    }
}
```

```bash
solc --standard-json input.json --base-path /tmp | jq --indent 4
```
```json
{
    [
        ...
        {
            "component": "general",
            "errorCode": "6275",
            "formattedMessage": "ParserError: Source \"b.sol\" not found: File not found.\n --> /tmp/x/y/a.sol:1:1:\n  |\n1 | import \"b.sol\";\n  | ^^^^^^^^^^^^^^^\n\n",
            "message": "Source \"b.sol\" not found: File not found.",
            "severity": "error",
            "sourceLocation": {
                "end": 15,
                "file": "/tmp/x/y/a.sol",
                "start": 0
            },
            "type": "ParserError"
        }
    ],
    ...
}
```
## Environment
- Compiler version: 0.8.1

**Comment by cameel** [comment]
I'm assuming that the fact that the compiler reads from the filesystem even with `--standard-json` is what it's supposed to do when a file is not found in the JSON. Or is it a bug too?

**Comment by chriseth** [comment]
The path provided in the input standard-json is always the internal path, never the filesystem path. So I would say if you use it in connection with `--base-path`, the json-path should be appended to the base path when looking for additional files, but it should not be removed from the path given in the standard-json input.

This is different for the commandline interface, I would say, where we the argument are filesystem paths to begin with, because it is a shell command.

**Comment by cameel** [comment]
In that case what do you think about this example:

```json
{
    "language": "Solidity",
    "sources": {
        "/tmp/x/y/a.sol": {"content": "import \"b.sol\";"},
        "/tmp/x/y/c.sol": {"content": "import \"/tmp/d.sol\";"},
        "/tmp/b.sol":     {"content": "contract B {}"},
        "/tmp/d.sol":     {"content": "contract D {}"}
    },
    "settings": {"outputSelection": {"*": { "*": []}}
    }
}
```
```bash
solc --standard-json input.json --base-path /tmp
```

This won't work in JSON but it would work just fine if you used these paths on disk and compiled via CLI. Is this not a problem for tools? A tool wanting to construct JSON input from files on disk would have to scan the imports, notice that `b.sol` is relative and put it under `b.sol` (rather than `/tmp/b.sol`) based on that. For `d.sol` it would have to know that it's the opposite - `/tmp/d.sol` is the right path. And what if `d.sol` is imported in different files in different ways?

**Comment by chriseth** [comment]
I firmly believe that import resolution (translation of import statements to paths in the compiler-internal filesystem) and lookup on the host filesystem should stay separated. This is imperative for being able to recompile on different systems.

If you reference paths in the CLI they reference actual files present in the current shell instance. You have a "current working directory", you have symlinks and all the wonders of the host filesystem. Standard-json does not have a host filesystem. It needs to be easily translatable from metadata. There is one tiny detail and that is allowing the commandline interface to auto-discover files even in standard-json mode.

Note that when you use `solc --base-path /tmp/ /tmp/x/y/a.sol ...`, then the metadata will (or should) not contain a file named `/tmp/x./y/a.sol` but instead a file called `x/y/a.sol`.

**Comment by cameel** [comment]
I'm closing this since the behavior is by design rather than due to an error. When I submitted this my understanding of how `--base-path` is supposed to work was very incomplete. For anyone who runs into this in the future, I documented the whole path behavior in #11442 and I recommend reading it first.
