### ISSUE TITLE
OOG when contract calls another contract's function that returns `type[4]` (or more)

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/solidity#1103]
When calling `fooInstance.a(<address of B>)`, this code breaks with an "out of gas" error. Tested on both browser-solidity and on testrpc.

```
pragma solidity ^0.4;

contract Foo  {
    function a(Bar bar) {
        bar.b();
    }
}

contract Bar {
    function b() returns (uint[4] i) {}
}
```

If you change the `uint[4]` to `uint[3]`, the code runs as you would expect. It also appears to happen with any type of array, not just `uint`s.

This seems to be a regression that occurred in 0.4.0, because this problem does not occur on 0.3.5 or 0.3.6.

**Comment by axic** [comment]
I think this is the same issue as #1083 or at least related.

**Comment by redsquirrel** [comment]
Yes, they seem related.

**Comment by chriseth** [comment]
Confirmed as duplicate.
