### ISSUE TITLE
Compiling in Yul mode doesn't produce sources output

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#11043]
## Description

When you use solc to compile Yul, you get `contracts` output but no `sources` output (with source IDs and ASTs).

Now, strictly speaking, one could say that, since Yul only supports compiling individual files (at least for now), source IDs aren't necessary.  But having this information would allow treating the compiler output in a more uniform manner without having to write special cases.

Also, it would be nice to have ASTs.  These exist when Yul is used in an assembly block inside Solidity, and in `generatedSources`, but we don't get them here.  It would be nice to have these for debugging purposes... e.g., Truffle Debugger relies on these to track variables.  It's been able to track Yul variables for some time now, but it wouldn't be able to do it for standalone Yul if there are no ASTs.

So, I would like to see `sources` added to the output when using Yul.

Context: I was working on finally adding [Yul support into Truffle](https://github.com/trufflesuite/truffle/issues/1906) and this came up as one of the problems I encountered.  There will be one more of these issues in a bit. :)

## Environment

- Compiler version: 0.8.1

**Comment by axic** [comment]
Since we do prepare an AST of inline assembly for the Solidity AST output, technically it should be possible to create a similar JSON output for Yul. We are lacking it right now and given we have seen some reluctance changing the Solidity AST, I would be careful making this output well "designed".

As a side-note I am not sure it currently would cover Yul objects.

Do you depend on this for Yul support? Would it be okay if we say this feature is planned in the medium-term?

**Comment by haltman-at** [comment]
Well, it depends on how much support you want and how much we're willing to special-case things to get it to work.

So we can distinguish between multiple things here: The presence of `sources` at all (along with `id`), and the presence of `ast` in those sources.  (So possibly I should split this into two separate issues?)

So, let's start with `sources` and `id`.  Is this *necessary* for support?  Hm... well, I thought we needed it to avoid having to mess up our code a bunch, but on checking I don't think that's the case and I think we can handle it without doing that.  It would still be nice but I think things should still work without it.  Just to check -- all versions of Yul include source maps, right?  If not I'll have to make some additional alterations.

As for how necessary are ASTs, well, this is where the question comes up of, what do you mean by support?  They're not necessary for compilation or most other purposes; they only really affect the debugger.  And (thanks to some recent changes made to support Vyper) they should no longer even be necessary for stepping through with the debugger.  However they will be necessary if you want to be able to see the values of assembly variables with the debugger.  That's basically what we'd need them for.

So, yes, I think it's fine if this isn't any sort of immediate priority.

**Comment by axic** [comment]
Thanks, having a nicer introspection support in the debugger for Yul does sound intriguing tough!

So are you saying that not even sources with id is necessary (what can one use it for without the ast though?), but to reap the benefits we should have sources with id and ast?

**Comment by haltman-at** [comment]
Yeah I think not even sources with IDs is necessary -- I mean it was never really *necessary* per se, the question was just how much we were willing to muck up our code to support it.  I thought it might be more than would be a good idea.  As it turns out the amount of that required is pretty minimal so I think it's fine.  (I'll probably want to discuss this with some other Truffle people to be sure though, it could possibly have some unintended consequences later, I don't think it's a big deal but I want to be sure.)

Yeah just in case you weren't aware, we added support for inspecting assembly variables within Solidity (including in generated sources) a while back, so it would be somewhat disappointing to be unable to do it in standalone Yul. :)

**Comment by haltman-at** [comment]
Hm OK I've mostly gotten stuff working but there may be more of an issue than I thought with the lack of `sources` -- not in terms of breaking things but in terms of making sure things are arranged sensibly for the future... I'll have to talk about it with other Truffle people, so we'll see what happens there.

Also I'm noticing some possible problems with the Yul source maps, but I guess I'll open a separate issue for that.  (Edit: Opened that as #11068.)

**Comment by axic** [comment]
Actually for having the AST we have the issue #9590.

**Comment by haltman-at** [comment]
Oh, I missed that, thanks!
