### ISSUE TITLE
Improve Yul function collector with additional interfaces for createFunction

### ISSUE THREAD

**Issue by mijovic** [ethereum/solidity#11049]
Raised in https://github.com/ethereum/solidity/pull/10768#discussion_r587380456

Possible functions to add:
```
std::string createFunction(
	std::string const& _name, 
	std::function<std::string(std::string&, std::string&, std::string&)> const& _creator
);
```
`_creator` function should have arguments represent function arguments, return values and function body.

than some of our yul util functions should be much simpler, for example (`copyStructToStorageFunction`):
Instead of:
```
string functionName =
	"copy_struct_to_storage_from_" +
	_from.identifier() +
	"_to_" +
	_to.identifier();

return m_functionCollector.createFunction(functionName, [&]() {
	Whiskers templ(R"(
		function <functionName>(slot, value) {
		...
		}
	)");
	templ("functionName", functionName);
```
would be:
```
string functionName =
	"copy_struct_to_storage_from_" +
	_from.identifier() +
	"_to_" +
	_to.identifier();

return m_functionCollector.createFunction(functionName, [&](auto& _args, auto& _retValues, auto& body) {
	_args = "slot, value";
	Whiskers templ(R"(
		...
	)");
	_body = templ.render();
```

**Comment by chriseth** [comment]
Sounds very useful!

**Comment by chriseth** [comment]
If `_retValues` is non-empty, it adds `-> _retValues`, otherwise not.

**Comment by chriseth** [comment]
Once we have that, we could also implement `callYulFunction` to count the number of commas in the arguments and return values and use that for the parameters that currently have to be provided manually.

**Comment by ghost** [comment]
Closed worka after next years
