### ISSUE TITLE
Compiling Yul doesn't produce immutableReferences even when setimmutable/loadimmutable is used

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#11044]
## Description

Compiling Yul that uses `linkersymbol` will produce link references in the compiler output, but compiling Yul that uses `setimmutable`/`loadimmutable` doesn't produce immutable references in the compiler output.

So, for why this is relevant -- this goes along with #11043 as one of the issues I encountered when trying to add [Yul support into Truffle](https://github.com/trufflesuite/truffle/issues/1906).

Why is this an issue?  It's for performing bytecode matching; there are a number of contexts where we're given a piece of externally-obtained bytecode and we want to know what contract class it is (so we can get an appropriate source mpa, etc).   In order to do this, we need to know which parts of any given compiled bytecode may possibly vary, so that when we attempt to match other bytecode against it, we don't get a false negative.  To do this we rely on both link references and immutable references (and knowledge of the delegatecall guard) to say, hey, these parts of the bytecode are allowed to vary.  So, the lack of immutable references would be a problem in that we wouldn't be able to recognize instances of Yul contracts that made use of `setimmutable`/`loadimmutable`.

So, this would be useful to have.  There is the problem that they couldn't be keyed by AST ID like with Solidity, since Yul ASTs don't have node IDs, but maybe they could just use the immutable name or something (which would be unambiguous in this context).  This probably wouldn't be used for decoding in the debugger or anything, but we'd want to have some way of knowing which places in the code might vary for bytecode matching.

(I mean technically since it's Yul *anywhere* in the code might vary, so obviously this couldn't be done with full reliability, but we'd still like to handle the cases that we can.)

## Environment

- Compiler version: 0.8.1

## Steps to Reproduce

```yul
object "YulTest" {
  code {
    let size := datasize("runtime")
    datacopy(0, dataoffset("runtime"), size)
    setimmutable(0, "test", 1)
    return(0, size)
  }
  object "runtime" {
    code {
      mstore(0, loadimmutable("test"))
      return(0, 0x20)
    }
  }
}
```

**Comment by Marenz** [comment]
Here is a suggestion of how the output could look:

```

              "deployedBytecode": {
                /* ..., */ // The same layout as above.
                "immutableReferences": {
                  // There are two references to the immutable with AST ID 3, both 32 bytes long. One is
                  // at bytecode offset 42, the other at bytecode offset 80.
                  "3": [{ "start": 42, "length": 32 }, { "start": 80, "length": 32 }]
                }
                "immutableReferencesYul": {
                  "test": { 
                    "value": "0x01",
                    "offsets": [16, 32, 44]  
                  }
                }
              }
```

**Comment by ekpyron** [comment]
@Marenz What's ``value``? Also why not stick to the layout of ``deployedBytecode.immutableReferences``?
I'm actually wondering if we could just reuse the very same fields and just use the name instead of the AST ID, in case we don't have an AST ID... although that'd of course potentially raise backwards compatibility concerns...

**Comment by Marenz** [comment]
`value` would be the actual value of the immutable that way it also provides the length as well.
I thought about reusing the existing one, but it felt very dirty to mix completely different identifiers together (ast ids and names used in yul when calling `setimmutable`)

Also notice how the length repeats needlessly for the old fields, when you'd only need it once...

**Comment by Marenz** [comment]
I wanted to include the `value` because while with the ASTs you can print the AST tree and get the actual value of the immutable, you can't do the same with the yul code (short of printing the yulcode itself  of course) so this would provide a JSON-specifc way to get that value, removing the need to do any extra parsing to get the same information as you'd get with the AST immutables.

**Comment by ekpyron** [comment]
I'm still not sure what value you're talking about... in general, you don't know the value the immutable will get.

**Comment by Marenz** [comment]
Why wouldn't I know it? Isn't it given in the function call `setimmutable(0, "name", value)`?

**Comment by ekpyron** [comment]
But you don't know the value of ``value``, it can depend on anything, e.g. on constructor arguments. Or did you want to include the expression? Not sure that would be overly helpful.

**Comment by Marenz** [comment]
Ah, true. I guess `length` has to be enough in that case.

**Comment by ekpyron** [comment]
Given that the AST ID is also the actual string used in the immutable pseudo-opcodes in Yul, I'd actually say we can just reuse ``deployedBytecode.immutableReferences`` and just use whatever string is used for the immutables in Yul as keys in there.

**Comment by ekpyron** [comment]
Given that the AST ID is also the actual string used in the immutable pseudo-opcodes in Yul, I'd actually say we can just reuse ``deployedBytecode.immutableReferences`` and just use whatever string is used for the immutables in Yul as keys in there.
