### ISSUE TITLE
[SMTChecker] ICE on public getter for array of structs

### ISSUE THREAD

**Issue by blishko** [ethereum/solidity#11056]
## Description
SMTChecker crashes on mismatched SMT sorts when analyzing public getter of a state variable that is an array of structs.

Example reported in https://github.com/ethereum/solidity/issues/10986#issuecomment-783345346
```
pragma abicoder v1;
pragma experimental SMTChecker;
struct Item {
	uint x;
	uint y;
}

contract D {
	Item[][][] public items;

	function test() public view returns (uint) {
		(uint a, uint b) = this.items(1, 2, 3);
	}
}
```

Another example that checks also structs with members that are ignored by public getter.
```
pragma abicoder v1;
pragma experimental SMTChecker;

struct Item {
	uint x;
	uint y;
	uint[] arr;
}

contract D {
	Item[] public item;

	function test() public view returns (uint) {
		(uint a, uint b) = this.item(0);
	}
}
```

**Comment by m1cm1c** [comment]
The second problem needs https://github.com/ethereum/solidity/issues/11067 to be fixed.

**Comment by leonardoalt** [comment]
@m1cm1c the issue you linked doesn't have a connection to this. The issue here is about the SMTChecker.
