### ISSUE TITLE
Following contract events freeze browser

### ISSUE THREAD

**Issue by madvas** [ethereum/solidity#1105]
See contract below. When I try to listen on those 3 events via Web3 API, CPU starts running on full power, page freezes, can't even refresh page. Something is definitely very wrong here, because when I remove `uint16[] b` parameter from `onLogArr`, it works ok. I've noticed very strange behaviour of events before, like overwriting random storage variables with their parameters. This is just one example. 

```
pragma solidity ^0.4.1;

contract Test {
    event onStart(address a);
    event onLogArr(uint16[] a, uint16[] b);
    event onLogStr(string something);

    function Test() {
        onLogStr("some log message");
        uint16[] memory arr = new uint16[](20);
        for(uint8 i = 0; i < 20; i++){
             arr[i] = 100;
         }

        onStart(msg.sender);
        onLogArr(arr, arr);
    }
}
```

I'm using:
`EthereumJS TestRPC v2.2.7`
`web3.js 0.16.0 or 0.17.0-beta`

```
solc, the solidity compiler commandline interface
Version: 0.4.2-develop.2016.9.16+commit.6a80511f.Darwin.appleclang
```

(happened in older compiler also, that's why I updated to latest version)

**Comment by chriseth** [comment]
This does not sound like a bug in the compiler. Please check if the cpu usage is due to the browser or due to the testrpc and file a bug in the relevant repository. Thanks!
