### ISSUE TITLE
RFC: export EIP-712 signature definitions in the ABI

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#11054]
EIP-712 defines a typed signature scheme in which a `messageStruct` and a `domainStruct` are defined, and a hashing scheme that combines the names, types, and values of these into a bytestring that is then sent to the wallet to be signed.

This is becoming an increasingly common way to interact with contracts, with two prominent examples being `permit` (EIP-2612) and Gnosis Safe.

While generating EIP-712 signatures is straight forward enough given a particular pair of message and domainstruct, it is harder to generate for arbitrary contracts, as the structures are not exposed in the ABI. This means that 712-style signatures need to special cased for each contract, and cannot be discovered or interacted with via generalized uis that interface directly with the contract ABI, such as remix or etherscan.

I'm wondering if it might be a good idea to let 712 structures be exposed in the ABI, maybe through a special keyword on structs. For example, here I am decorating the two structs required to form a `Mail` example from the 712 spec with the `eip712` keyword.

```solidity
struct EIP712Domain eip712 {
    string name;
    string version;
    uint256 chainId;
    address verifyingContract;
}

struct Mail eip712 {
    address from;
    address to;
    string contents;
}
```

This would expose the following json for the Mail struct to the ABI:
```
  eip712Types: {
      EIP712Domain: [
          { name: 'name', type: 'string' },
          { name: 'version', type: 'string' },
          { name: 'chainId', type: 'uint256' },
          { name: 'verifyingContract', type: 'address' },
      ],
    Mail: [
          { name: 'from', type: 'address' }, 
          { name: 'to' type: 'address' },
          { name: 'contents', type: 'string' }
      ],
  }
```

Which, given values for `name`, `version`, `chainId`, `verifyingContract`, `from`, `to` and `contents` can easily be used for generating a EIP-712 style signature.

**Comment by axic** [comment]
Can this be solved with a widely approved naming scheme for these structs, such as `EIP712_Mail`, and then just having a mechanism to export the name of structs in the ABI? I think we may already do that too.

**Comment by axic** [comment]
```solidity
struct EIP712_Mail {
    address from;
    address to;
    string contents;
}

contract C {
    function validate(EIP712_Mail calldata mail) external {
    }
}
```

Produces:
```json
[
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "to",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "contents",
            "type": "string"
          }
        ],
        "internalType": "struct EIP712_Mail",
        "name": "mail",
        "type": "tuple"
      }
    ],
    "name": "validate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
]
```

See the `internalType` part.

**Comment by MrChico** [comment]
That is a good point. It seems like what is mainly missing is the convention, more so than a lack of ABI.
Closing this.

**Comment by recmo** [comment]
AFAIK, the encoding used by ABI can not support recursive data structures, whereas the one in the EIP712 spec can. So you'd loose some functionality.
