### ISSUE TITLE
[Yul] Optimised code containing for loop(s) consumes more gas than unoptimised code

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11062]
## Description

```
{
	for { let i_0 := 0 } lt(i_0, 0x60) { i_0 := add(i_0, 0x20) } {
		for { let i_1 := 0 } lt(i_1, 0x60) { i_1 := add(i_1, 0x20) } {
			mstore8("", 0x8000000000000000000000)
			mstore8("", 0x80000000000000000000000)
		}
	}
}
```

is optimised to

```
{
     let i := 0
     let i_1 := i
     for { } true { i_1 := add(i_1, 0x20) }
     {
         let _1 := 0x60
         if iszero(lt(i_1, _1)) { break }
         let i_2 := i
         for { } lt(i_2, _1) { i_2 := add(i_2, 0x20) }
         {
             let _2 := ""
             mstore8(_2, 0x8000000000000000000000)
             mstore8(_2, 0x80000000000000000000000)
         }
     }
}
```

On evmone gas consumption difference between optimised and unoptimised code is +172 gas i.e., optimised code consumes more gas.

## Environment

- Compiler version: 093ea4612
- Target EVM version (as per compiler settings): NA
- EVM execution environment / backend / blockchain client: evmone v0.4.0

## Steps to Reproduce

TBD.

**Comment by bshastry** [comment]
I think one of the things that is sub optimal is that literal constants get "optimised" to variable references that resolve to a literal expression.

```
let _2 := ""
mstore8(_2, 0x8000000000000000000000)
mstore8(_2, 0x80000000000000000000000)
```

leads to byte code like so

```
PUSH1 0x0
PUSH11 0x8000000000000000000000
DUP2
MSTORE8
```

as against the unoptimised sequence such as

```
PUSH1 0x0
PUSH11 0x8000000000000000000000
MSTORE8
```

This leads to two additional `DUP2` per iteration in the innermost loop. Something similar happens with the following optimised snippet

```
let _1 := 0x60
...
let i_2 := i
for { } lt(i_2, _1) { i_2 := add(i_2, 0x20) }
```


Here, there are two variable references `_1` (that would otherwise assemble to `PUSH1 0x60`) assembling to `PUSH1 0x60` and `DUPX` and the `let i_2 := i` assembling to a combination of `PUSH` and `DUP` instead of `PUSH` alone.


The other issue seems to stem from loop condition of the outermost loop entering its body (see #7424 and #7409).

**Comment by bshastry** [comment]
This test (from `../test/libyul/yulInterpreterTests/recursive_function_for_loop.yul`) consumes 84 additional gas when optimised.

```
{
        {
            let a := foo_0(calldataload(0))
            sstore(0, a)
        }
        function foo_0(x) -> y
        {
            y := 1
            mstore8(1, 1)
            for { } slt(1, keccak256(1, msize())) { let x_1 := foo_0(x) }
            {
                y := add(y, 1)
                continue
            }
        }
}
// ----
// Trace:
// Memory dump:
//      0: 0001000000000000000000000000000000000000000000000000000000000000
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 0000000000000000000000000000000000000000000000000000000000000002
```

optimised to

```
{
   sstore(0, foo(calldataload(0)))
   function foo(x) -> y {
    y := 1
    mstore8(y, y)
    for { } true { pop(foo(x)) }
    {
        if iszero(slt(1, keccak256(1, msize()))) { break }
        y := add(y, 1)
        continue
    }
}
```

**Comment by bshastry** [comment]
Excess gas consumption = Excess gas consumption per code unit * frequency of code unit

Example

```
/// Gas cost increase by delta
function f() {
   for { let i := 0 } lt(i, 3) { i := add(i, 1) }
   {
      continue
   }
}

/// Total gas increase = delta x 3
for { let i := 0 } lt(i, 3) { i := add(i, 1) }
{
   f()
}
```

This is probably obvious, just wanted to document that it is not necessary that gas cost increase only be due to nested for loops. A frequently called function (that contains a loop) may increase gas cost of optimised code substantially.

**Comment by chriseth** [comment]
This is a known issue and I would think that we should focus on optimizing existing code first and only then look at generated examples. Is this part of you general fuzzing efforts?

**Comment by bshastry** [comment]
> This is a known issue and I would think that we should focus on optimizing existing code first and only then look at generated examples.

Not sure I follow. Does existing code mean unit tests we currently have?

> Is this part of you general fuzzing efforts?

Yes. If it is of interest, I could create a PR for specifically targeting gas usage.

**Comment by chriseth** [comment]
Sorry, I meant "real world code" instead of "existing code". The optimizer has several steps that result in worse code, which are performed in the hope that other steps can make better use of the code. At some point we might fuzz this, but I think we are not at that stage yet.
