### ISSUE TITLE
Implement support for Berlin

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11060]
While [Berlin](https://eips.ethereum.org/EIPS/eip-2070) has a couple of EIPs, I think only three of them affect us:
- [EIP-2565](https://eips.ethereum.org/EIPS/eip-2565)
- [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929)
- [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930)

2565 actually does not affect us, as we do not have the modexp precompile implemented (and also see #11057).

2929 introduces a lot of repricing of state operations, which could be important for optimisation steps, the gas estimator, and gas tests.

2930 introduces a way to pass access lists in a transaction, in order to prepay for account access, reducing the costs of 2929. We could implement this in isoltest for completeness, but not sure yet if we actually need it.

**Comment by axic** [comment]
We are blocked on evmc + evmone releasing support. It will come with a breaking ABI (evmc 8.0.0).

**Comment by chriseth** [comment]
For the gas accounting in both the optimizer and in testing I would actually propose to always assume "warm state".

**Comment by axic** [comment]
Why?

**Comment by chriseth** [comment]
Why not?

**Comment by axic** [comment]
At least for external tests (like deposit contract, uniswap, etc.) it is a much more compelling use case to consider them predominantly executed via transactions and collect gas statistics that way. Reason is that is how they are mostly going to be used on chain.

Once we see an uptick on access lists in transactions (i.e. metamask having it by default), then I agree we should move on to the warm account (but not sure about warm storage slot) because that is the pricing most people will observe.

**Comment by axic** [comment]
> Once we see an uptick on access lists in transactions (i.e. metamask having it by default), then I agree we should move on to the warm account (but not sure about warm storage slot) because that is the pricing most people will observe.

So `tx.to` is considered implicitly part of the access list, this was properly added in #11286. This means that account will be "warm" by default.

However it seems that access lists will not be widely used anytime soon (outside of cases where it is required due to quirky contracts), since it charges for `tx.to` which diminishes its cost benefit. See [EIP-3521](https://eips.ethereum.org/EIPS/eip-3521) explaining it.

**Comment by axic** [comment]
This was implemented by #11244.
