### ISSUE TITLE
[SMTChecker] Remove tx data automatically if possible

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#11074]
Currently the CHC encoding adds tx data, for example the first 4 bytes of msg.data = function selector for public functions.
We could automatically detect if those things are used, and if they're not we can actually not add the constraints.

**Comment by blishko** [comment]
I am wondering how to detect, for example, that `msg.data` is not used. It is not enough to check that it is not accessed in the public function being analyzed, but we also need to know that is it not accessed anywhere in the internal functions that could be called from the public function, no?

We could approximate and just check if it is accessed anywhere in the contract (or base contracts) and do not add the constraints only if there is no access anywhere in the contract.

**Comment by leonardoalt** [comment]
Yes, we'd have to check the internally called functions as well, but that can be done on the syntax level only

**Comment by leonardoalt** [comment]
I'm not sure anymore this actually makes sense.
