### ISSUE TITLE
Static calls to known (or known-pure) precompiles should be considered pure rather than just view

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#11078]
## Abstract

So, since Solidity isn't adding any new precompiles (see #3165), I tried actually implementing a precompiles library as described in that issue.  But I encountered the problem that, unless I was going to use assembly, all the functions had to be marked `view` rather than `pure`, because Solidity currently has no way of knowing that `x.staticcall(...)` won't alter the state when `x` is the address of a precompile.  Doing calls in assembly is a pain (or at least is for my purposes), so it would be nice if this could be done without resorting to assembly.  So, ideally, Solidity would consider static calls to known precompiles as pure.  (This is related to #6558, except I'm asking about the Solidity rather than assembly equivalent, because I'm trying to avoid using assembly.)

(Note that #6558 says "known-pure" precompiles; I've abbreviated that to "known precompiles", as all known precompiles, at least currently, are known-pure.  However the distinction can of course be kept in mind if for some reason that ever changes.)

(Possibly this could be expanded to cover all zero-value calls, rather than just static calls, but that seems more complicated.)

## Specification

As mentioned, static calls to known-pure precompiles should be considered pure.  Obviously, this feature would have to be restricted to calls whose address can be known at compile-time; so `address(5).staticcall(...)` should work, but a more general `x.staticcall(...)` would never be considered `pure` no matter the value of `x`.  (I mean, obviously, as `pure` is a compile-time notion, but just to be clear.)

Similarly, if this were to be expanded to all zero-value calls, it would have to only be calls which could be known to be zero-value at compile time.

The question then is, what's a known precompile?  I think there are two possible approaches here:
1. The list of known precompiles depends on the hardfork; 1-4 as of Frontier, 1-8 as of Byzantium, 1-9 as of Istanbul.
2. Just assume [EIP-1352](https://eips.ethereum.org/EIPS/eip-1352), or something similar, even though it's still a draft.  (If a particular precompile, such as 0, doesn't currently exist... well, then it's the "always returns empty" precompile. :P )

Obviously, (2) is quite a bit simpler here.

## Backwards Compatibility

There should be no backwards compatibility issues.

**Comment by hrkrshnn** [comment]
> Obviously, this feature would have to be restricted to calls whose address can be known at compile-time; so address(5).staticcall(...) should work

Why should `address(5)` work? How can solidity know that the staticcall to contract at address `5` is pure?

**Comment by hrkrshnn** [comment]
Can you share how you do it in inline assembly? I think `staticcall` in inline assembly should be reported as `view`, rather than `pure`.

**Comment by haltman-at** [comment]
Any chance this could be reopened?
