### ISSUE TITLE
Add some support for PGO (profile-guided optimization)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11085]
See https://en.wikipedia.org/wiki/Profile-guided_optimization. (This was [discussed on gitter](https://gitter.im/ethereum/solidity-dev?at=60412acbd71b6554cd203312).)

Guiding the compiler with usage data could help determining which code paths matter and could prefer those for cost. This could also make proposals like #4858, #6234 or #8186 moot.

One potential idea is to have a new input to standard json consisting of a map of AST id and number of hits. The code paths touching those AST ids would be prioritised. This map must be included in the metadata as well for reproducibility. Creating this map would not be the responsibility of the compiler, rather frameworks could run various test cases, record the execution trace, and submit the map.

Obviously this is not a concrete proposal yet, just a rough outline.

**Comment by chriseth** [comment]
Instead of AST ids we could also use the names of yul functions or IR code line numbers before optimization.

**Comment by zamazan4ik** [comment]
Any updates on this? [Here](https://github.com/zamazan4ik/awesome-pgo) I collected much more articles and benchmarks regarding applying to different kinds of applications (including many compilers).
