### ISSUE TITLE
Testing docker images and CI runs for Debian stable

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#11096]
Motivation: Our docs claim that we are compatible with gcc 8, but since ubuntu 20.04 already ships gcc 9 this was actually untested and we broke things (see https://github.com/ethereum/solidity/pull/11095).

The main reason we kept the requirement at GCC 8, I think, was that it's what Debian stable (buster) ships.

I'd say generally supporting the latest stable Debian release is a reasonable compromise between always being cutting edge and being backwards-compatible.

But if we put up such claims, we should of course have them verified in CI.

So I propose we add a testing docker image for debian buster and at least a CI build run for it, maybe also a test run (doesn't hurt).

Note that while the default versions of GCC and CMake work on buster, the default boost version 1.67 is not sufficient, but there are explicit libboost*1.74*dev packages, so the docker image will have to pull in those explicitly.

Debian buster only has Z3 4.4, so I'd suggest to just skip it and use a no-smt build.

Quote @cameel from gitter:
> Well, I could try it next week then. Unless maybe @aarlt (Alexander Arlt) wants to take it? He's been working on these images not so long ago so he'd probably make a quicker job of it.

**Comment by cameel** [comment]
I think it would still be useful.

Maybe we should even also have another job that runs the oldest supported versions of everything. Linux runners are relatively cheap on CircleCI (compared to macOS and Windows) so we could have a bunch more of them.
