### ISSUE TITLE
Build Request: minimize dependencies

### ISSUE THREAD

**Issue by nejucomo** [ethereum/solidity#111]
I would like to be able to install `solc` with minimal dependencies. When I try this:

``` bash
$ git clone 'https://github.com/ethereum/solidity`
$ mkdir -p solidity/build
$ cd solidity/build
$ cmake ..
```

-then this fails because I need `webthree-helpers`, and that, in turn, depends on many things like `leveldb`, `opencl`, etc...

I don't see why `solc` would require leveldb, since I expect it just compiles source files to asts or bytecode. It would be nice if building only `solc` did not require excessive dependencies.

(BTW, is this the right approach to building `solc`? I had some trouble finding clear documentation, so I filed #110 separately.)

**Comment by chriseth** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/65 .
