### ISSUE TITLE
core dumped when testing

### ISSUE THREAD

**Issue by jiangshangqifeng** [ethereum/solidity#11100]
## Description
when I try to test the solc, the isoltest core dumped

## Environment

- Compiler version:v0.8.2
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):isoltest 
- EVM execution environment / backend / blockchain client: isoltest 
- Operating system:
  Description:    Ubuntu 20.10
  Release:        20.10
  Codename:       groovy
- gcc: 10.2.0
- cmake: 3.16.3
- Z3 version: 4.8.11 - 64 bit
- cvc4:1.8 [git HEAD 52479010]

## Steps to Reproduce

1. compile the source code and it's OK
2. run shell `$REPO_DIR/scripts/isoltest.sh`

then `Segmentation fault` occurred:
```
smtCheckerTests/modifiers/modifier_multi.sol: Segmentation fault (core dumped)
```
backtrace:

```
(gdb) bt
#0  0x00007f1f56aaf824 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#1  0x00007f1f56ab78e4 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#2  0x00007f1f56ab7e81 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#3  0x00007f1f56ab9782 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#4  0x00007f1f5779c0e2 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#5  0x00007f1f5779d32a in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#6  0x00007f1f576f6675 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#7  0x00007f1f577046e9 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#8  0x00007f1f57714089 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#9  0x00007f1f5754acf5 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#10 0x00007f1f57891577 in Z3_fixedpoint_get_answer () from /lib/x86_64-linux-gnu/libz3.so.4
#11 0x000055970ccf1039 in solidity::smtutil::Z3CHCInterface::query(solidity::smtutil::Expression const&) ()
#12 0x000055970c95c6a6 in solidity::frontend::CHC::query(solidity::smtutil::Expression const&, solidity::langutil::SourceLocation const&) ()
#13 0x000055970c965211 in solidity::frontend::CHC::checkAndReportTarget(solidity::frontend::CHC::CHCVerificationTarget const&, solidity::langutil::ErrorId, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#14 0x000055970c96e9a7 in solidity::frontend::CHC::checkVerificationTargets() ()
#15 0x000055970c9705d5 in solidity::frontend::CHC::analyze(solidity::frontend::SourceUnit const&) ()
#16 0x000055970c68bdfa in solidity::frontend::ModelChecker::analyze(solidity::frontend::SourceUnit const&) ()
#17 0x000055970c70bb95 in solidity::frontend::CompilerStack::analyze() ()
#18 0x000055970c5b50b0 in solidity::frontend::test::SyntaxTest::parseAndAnalyze() ()
#19 0x000055970c5d96f7 in solidity::frontend::test::SMTCheckerTest::run(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#20 0x000055970c53d482 in TestTool::process() ()
#21 0x000055970c53e2b8 in TestTool::processPath(std::unique_ptr<solidity::frontend::test::TestCase, std::default_delete<solidity::frontend::test::TestCase> > (*)(solidity::frontend::test::TestCase::Config const&), solidity::test::IsolTestOptions const&, boost::filesystem::path const&, boost::filesystem::path const&) ()
#22 0x000055970c520e95 in main ()
```

**Comment by jiangshangqifeng** [comment]
and run with `./scripts/tests.sh` also failed with error:

```
Testing soljson via the fuzzer...
xargs: /home/jht/eth-solidity/build/test/tools/solfuzzer: terminated by signal 11
Commandline tests FAILED
```

**Comment by cameel** [comment]
@jiangshangqifeng Are you building code from `v0.8.2` tag or the latest revision from `develop`? I just tried on my local build and I could not reproduce it. But my build is a bit behind `develop` right now so the problem might just be something more recent.

Also, have you tried building with Z3 4.8.10? Latest Z3 should still of course work but we're usually using 4.8.10 for development so I wonder if this might be caused by some recent changes in Z3.

**Comment by jiangshangqifeng** [comment]
> @jiangshangqifeng Are you building code from `v0.8.2` tag or the latest revision from `develop`? I just tried on my local build and I could not reproduce it. But my build is a bit behind `develop` right now so the problem might just be something more recent.
> 
> Also, have you tried building with Z3 4.8.10? Latest Z3 should still of course work but we're usually using 4.8.10 for development so I wonder if this might be caused by some recent changes in Z3.

thank you for your replying.
Yes I built code from tag  v0.8.2 (661d11035b871aa1624bf568e3d476ef1bf25895)
I have tried Z3 with v4.8.10(517d907567f4283ad8b48ff9c2a3f6dce838569e) and  the `Segmentation fault` still
shall I have to use gcc 9.3?  it's said that this version work well with that

**Comment by leonardoalt** [comment]
I'm also on gcc 10.2.0, z3 4.8.10 (release) and can't reproduce it. That's weird.

**Comment by leonardoalt** [comment]
@jiangshangqifeng Is the problem still happening? I'm closing for lack of reproducibility and activity. Please reopen if needed.
