### ISSUE TITLE
error: ‘list’ in namespace ‘std’ does not name a template type

### ISSUE THREAD

**Issue by ucwong** [ethereum/solidity#11103]
![image](https://user-images.githubusercontent.com/22344498/111155574-96d1fa00-85cf-11eb-91ff-d1844560a4cf.png)
```
cmake version 3.20.0-rc4
g++ (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
```

**Comment by ekpyron** [comment]
https://github.com/ethereum/solidity/pull/11104 should fix the issue - but I wonder:
``Ubuntu 10.1.0-2ubuntu1~18.04`` looks to me like you're running ubuntu 18.04 bionic, right? Where did you get the gcc 10 build for that? Judging from https://packages.ubuntu.com/focal/gcc-10 and https://packages.ubuntu.com/bionic-updates/gcc I didn't think it was available for ubuntu 18.04.

**Comment by ekpyron** [comment]
I'm a bit surprised that this does not happen in any of our CI runs... we do have CI runs against gcc  9.3 and against gcc 10.2, but didn't get that error there. In any case, the header should be fixed, so #11104 should be merged regardless.

**Comment by ucwong** [comment]
@ekpyron just install by ```apt install gcc-10 ```

**Comment by ekpyron** [comment]
> @ekpyron just install by `apt install gcc-10 `

Curious... but it is ubuntu 18.04 bionic?
In a ubuntu 18.04 docker image I get
```
# apt install gcc-10
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gcc-10
```

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/111157643-15c83200-85d2-11eb-9938-fcedf72eaac0.png)
Yes , curious
Should  I switch to gcc-9 and try again ?

**Comment by ekpyron** [comment]
Actually, I do not have gcc-9 available in bionic either :-). In the ``ubuntu:bionic`` docker image I do get:
```
root@c302ff0a728d:~# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
root@c302ff0a728d:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
root@c302ff0a728d:~# apt install gcc-9
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gcc-9
```
So I'm not sure what's happening here... Do you have anything special in ``/etc/apt/sources.list`` or the like?

If nothing else works, you can also just add the header to the respective file (i.e. what https://github.com/ethereum/solidity/pull/11104 does), that should fix the issue (in case you build from the git tree, you have to be careful about the compiler producing different metadata due to changing the source, though - but an explicit ``commit_hash.txt`` should prevent that).

**Comment by ucwong** [comment]
@ekpyron Thank you but https://github.com/ethereum/solidity/pull/11104 has not been merged yet

**Comment by ekpyron** [comment]
> @ekpyron Thank you but #11104 has not been merged yet

Now it has ;-). Please reopen the issue, in case the problem remains for some reason!
