### ISSUE TITLE
[Question] Error While Compiling (Solidity 0.8.2)

### ISSUE THREAD

**Issue by GaudiestTooth17** [ethereum/solidity#11115]
I was following this [guide](https://guides.github.com/features/mastering-markdown/), but whenever I execute `make .. && cmake` from within the build directory, compilation gets 56% of the way done and then stops with this error:
`/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::dir_itr_close(void*&, void*&): error: undefined reference to 'boost::system::system_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::create_directory_symlink(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::system_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::create_directory_symlink(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::system_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::create_directory_symlink(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::system_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::generic_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::generic_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::generic_category()'
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o):function boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*): error: undefined reference to 'boost::system::generic_category()'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/solidity-upgrade.dir/build.make:187: recipe for target 'tools/solidity-upgrade' failed
make[2]: *** [tools/solidity-upgrade] Error 1
CMakeFiles/Makefile2:647: recipe for target 'tools/CMakeFiles/solidity-upgrade.dir/all' failed
make[1]: *** [tools/CMakeFiles/solidity-upgrade.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2`

I am running Ubuntu 18 with Boost 1.7.5 in /usr/local/boost_1_75_0/

**Comment by hrkrshnn** [comment]
For questions like these, a better location would be https://gitter.im/ethereum/solidity or equivalently the matrix channel https://app.element.io/#/room/#ethereum_solidity:gitter.im

Also, the link you mentioned seems to be broken. My guess would be that you are missing the compiled libs. Can you try `sudo apt-get install libboost-all-dev` and repeat?

I'm closing this now. Please follow up on gitter or matrix.

**Comment by GaudiestTooth17** [comment]
I figured out the problem. I had inadvertently skipped the steps in the Boost installation where the header files would go into `/usr/include` and where the .so files would go into `/usr/lib/x86_64-linux-gnu`.
