### ISSUE TITLE
Error Presentation Specification

### ISSUE THREAD

**Issue by h3ph4est7s** [ethereum/solidity#1111]
Greetings,
by writing code for a linter i have noticed that errors printed by solc have not a specific syntax.
Dew to that fact implementing a linter for solidity is not straightforward, especially due to changes of the error output during the development life cycle resulting in different error formats across the code.
I strongly suggest to implement an error format specification for reporting.

**Comment by chriseth** [comment]
Which part of the errors would you like to formalize?

**Comment by axic** [comment]
I think #1387 fixes this.

**Comment by axic** [comment]
With #1387 the specification is in place. (Needs to be implemented too.)
