### ISSUE TITLE
How to check size of calldata

### ISSUE THREAD

**Issue by AndonMitev** [ethereum/solidity#11111]
How to check the maximum size of the calldata, i have a function which looks like this:
```
function inputData(address[] calldata addresses) external {}
```

If i call this function with 2000 addresses is ok but when i try to call with 20000 throw error oversized data, my question is how i can check what is the maximum accepted size before this error is thrown

**Comment by hrkrshnn** [comment]
Please use the gitter channel for these questions: https://gitter.im/ethereum/solidity

You could either user `addresses.length` or `calldatasize()` in inline assembly. `2**32` is a reasonable upperbound for `calldatasize()`.
