### ISSUE TITLE
Disable safety checks on individual statements for gas efficiency

### ISSUE THREAD

**Issue by gakonst** [ethereum/solidity#11125]
## Motivation

When writing Solidity, the developer oftentimes has written code which makes assumptions that the compiler cannot know. An example would be the existence of a contract such as a Uniswap pool or an ERC20 token. If I know that contract exists, I should not need to pay additional gas to check that it exists!

A simple example, is a dev having to write the following (h/t @moodysalem):

```solidity
// fetch the token balance of an address without triggering an EXTCODESIZE
function balanceOf(address token, address owner) internal view returns (uint256) {
        (bool success, bytes memory data) =
            token.staticcall(abi.encodeWithSelector(IERC20.balanceOf.selector, owner));
        require(success && data.length == 32);
        return abi.decode(data, (uint256));
}
```

## Specification

There should be an option in the solc compiler (a la Rust’s #[cfg(feature = "...") directive) allowing you to skip some kinds of "standard" checks w/o having to do it manually (e.g. writing a addreor dropping to assembly, e.g. skipping an EXTCODESIZE when *CALLING to a contract you know exists.

Example:
```solidity
IERC20 token = IERC20(...)


#[cfg(contract_exists)]
token.balanceOf(address(this))
````

The above should skip generating the EXTCODESIZE part of the bytecode.

This is similar to the `unsafe` keyword, but a bit more specialized to disable specific safety checks than everything. We would need to figure out which categories of commonly-done optimizations exist.

* Existence Checks
* Overflow Checks
* ..what else?

## Backwards Compatibility

This should be fully backwards compatible.

**Comment by cameel** [comment]
For overflow checks we already have the `unchecked` blocks (with feature requests for various flavors of it: #10698, #10706). There's also a request for unchecked array access (#9117).

We could probably extend the `unchecked` block syntax to cover some or all of them, e.g.
```solidity
unchecked: math arrays calls {
    ...
}
```
though I'm not sure if it's a good direction. The sentiment in the team currently is that these superfluous checks should be detected by the optimizer and removed when it's safe to do so. Unfortunately that's probably not that easy for `extcodesize` - we can't know at compilation time if the contract is actually there. And even if it is, it could potentially self-destruct at any moment.

> ..what else?

The compiler performs many other checks under the hood (see [`Panic` via `assert` and `Error` via `require`](https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require) in the docs for the list of situations that can result in a `Panic` or `Error`), though I don't think it's a good idea to allow disabling all of them.

**Comment by gakonst** [comment]
Thanks for the response!

>  The sentiment in the team currently is that these superfluous checks should be detected by the optimizer and removed when it's safe to do so. Unfortunately that's probably not that easy for extcodesize - we can't know at compilation time if the contract is actually there. And even if it is, it could potentially self-destruct at any moment.

Agreed, hence my point was that this feature should be developer controlled since it seems impossible to do at the optimizer level in many cases.

**Comment by axic** [comment]
@cameel the original idea for extending `unchecked` was `unckecked "something" {}`, similarly to how `assembly "evmasm" {}` works.

**Comment by axic** [comment]
> An example would be the existence of a contract such as a Uniswap pool or an ERC20 token.

For this particular case, I think we could utilise some require statement, which is "understood" by both the optimiser and the smtchecker.

As an example, `require(address(...).isContract())` could work like that, because the generated code could be deduplicated with the one generated by any call.

**Comment by cameel** [comment]
> the original idea for extending `unchecked` was `unckecked "something" {}`

Interesting. I didn't know that.

> As an example, `require(address(...).isContract())` could work like that, because the generated code could be deduplicated with the one generated by any call.

That would still result in an `EXTCODESIZE` check though, right? It would just move it into `require()` so it would still be a runtime check and you would not save any gas.

Here's a different idea. There are two things the check guards against: no contract at the address yet (either because you have wrong address or contract has not been deployed yet) or contract destroyed. And given that `SELFDESTRUCT` will likely be removed in the future, the former is much more important. How about we let users declare dependencies - contract addresses that must already be occupied at deployment time. We generate constructor code to check them once and after that we know these contracts exist so we can skip `EXTCODESIZE` on external calls to such addresses.

**Comment by axic** [comment]
> > As an example, require(address(...).isContract()) could work like that, because the generated code could be deduplicated with the one generated by any call.
>
> That would still result in an EXTCODESIZE check though, right? It would just move it into require() so it would still be a runtime check and you would not save any gas.

Yes but you can extend this with the "invariant" idea (~~there must be an issue somewhere for invariant syntax~~ #4991, #8146, #8433), and so would be enforced once at creation time. I think in general going towards constructs like require and invariants gives better overall longterm results compared to adding features for unchecked.

**Comment by moodysalem** [comment]
I think I would prefer something like `IERC20(address).transfer{checkExists: false}(...)`

But also, it is strange to me that this check happens for methods that have return data when you can check that the `returndatasize` is as at least what is expected, which was my expectation because of [this tweet](https://twitter.com/bantg/status/1365755857284325378?s=21)

**Comment by hrkrshnn** [comment]
About `extcodesize`: see https://github.com/ethereum/solidity/issues/12204 for a middle ground.
