### ISSUE TITLE
For lengthy contracts, variable in the contract are not getting assigned but the events in the constructor function are getting triggered.

### ISSUE THREAD

**Issue by akshay111meher** [ethereum/solidity#1112]
contract Employee{

  string public name;
  string public location;
  string public doj;
  uint public empno;
  uint public role;
  address public hr;
  address public billing;
  address public projectAddress;
  address mc;
  uint public onshore;
  uint public effortsPerDay;
  mapping (uint => SenderArray) effortsMap;
  event addEmployee(address indexed masterContract, uint indexed empNo, address indexed Hr);
  event submitEffort(address indexed masterContract, uint indexed empNo, address indexed project, uint efforts,uint timestamp);
  event movement(address indexed masterContract, uint indexed empNo, address indexed nextProj, address prevProj);

  struct Sender {
    address addr;
    uint efforts;
  }

  struct SenderArray{
    Sender[] allSends;
  }
  function Employee(string Name,string Location,string Doj,uint Empno,uint Role,address Hr,address Billing,address master){
    name = Name;
    location = Location;
    doj = Doj;
    empno = Empno;
    role = Role;
    hr = Hr;
    billing = Billing;
    mc = master;
    onshore = 0;
    effortsPerDay = 9000000000000000000;
    addEmployee(master,Empno,Hr);
  }

  function removeEmployee() returns (bool status){
    if(msg.sender == hr){
      role = 10000000;
    }
  }

  function setEffortsPerDay(uint efforts) returns (bool status){
    if(msg.sender == hr){
      effortsPerDay = efforts;
    }
  }

  function setLocation(string newLocation, uint newOnshore) returns (bool status){
    if(msg.sender == hr){
      location = newLocation;
      onshore = newOnshore;
      return true;
    }
    else{
      return false;
    }
  }

  function setHr(address newHr) returns (bool status){
    if(msg.sender == hr){
      hr = newHr;
      return true;
    }
    else{
      return false;
    }
  }

  function setFree() returns (bool status){
    if(msg.sender == hr){
      projectAddress == billing;
    }
    else{
      return false;
    }
  }

  function setProject(address newProject) returns (bool status){
    if(msg.sender == hr){
      movement(mc,empno,newProject,projectAddress);
      projectAddress = newProject;
      return true;
    }
    else{
      return false;
    }
  }

  function sendEfforts(uint efforts,uint timestamp) returns (bool status){
    if(msg.sender == billing){
      projectAddress.send(efforts);
      submitEffort(mc,empno,projectAddress,efforts,timestamp);
      return true;
    }
    else{
      return false;
    }
  }

}
###### 

The above is the contract that i have written. can someone please run it and find why variables in the contract are not getting assigned. Whereas the events in the constructor function are getting triggered.

**Comment by axic** [comment]
Can you please provide a short example and description of the problem?

**Comment by akshay111meher** [comment]
i have written down the contract above. please try adding it t test network. if length of contract exceeds, it variables in the contract are not getting assigned

**Comment by chriseth** [comment]
I tried this in browser-solidity, but the names get assigned for me. Which environment do you use? Perhaps the encoding of the strings is incorrect?

**Comment by axic** [comment]
@akshay111meher please reopen and add more details if the issue persists.
