### ISSUE TITLE
Should `token.sol` be an abstract contract?

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#1114]
It looks like the contract in [`token.sol`](/ethereum/solidity/blob/develop/std/Token.sol) would be better represented without the empty curly-braces, in the form of an abstract contract. That would enable better checking for method-set completion in the compiler, right?

I'm not actually sure yet what the compiler promises in terms of implementation for abstract contracts, so correct me if this would accomplish nothing, right now.

**Comment by axic** [comment]
I think it makes sense making it abstract.

**Comment by chriseth** [comment]
@cathalgarvey good catch! Do you want to implement this change?

**Comment by ghost** [comment]
Sure, will have a PR in a few minutes then. :)
