### ISSUE TITLE
AST never contains ModifierInvocation.kind = "baseConstructorSpecifier"

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#11147]
In the latest 0.8.3 there is supposed to be a `kind = "baseConstructorSpecifier` property when a modifier invocation corresponds to a constructor call. This is never actually seen in the AST, I think due to the following bug:

https://github.com/ethereum/solidity/blob/e3ea5c631e9c3614ed6b2bff4806a670f769c682/libsolidity/ast/ASTJsonConverter.cpp#L464-L466

The referencedDeclaration of the name of a modifier invocation is actually the ContractDefinition node and not the constructor FunctionDefinition, so `function->isConstructor()` is never true (and `function` doesn't even point to a function).

Also notice that the tests introduced in https://github.com/ethereum/solidity/pull/11091 only contain instances of `kind = modifierInvocation`.

**Comment by chriseth** [comment]
Oh this is embarassing! It worked in the first version of the PR but after the introduction of the `if`, I just auto-updated the expectation without checking again...
Thanks for reporting!
