### ISSUE TITLE
Allow to disable warning for shadowed inline assembly, and/or give the warning more discriminately

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#11150]
## Abstract
Requesting either a way to disable the `shadowed in inline assembly` warning in a function or in the file, and/or for it not to print the warning if no shadowed variables are used.

## Motivation

I see the warning `Variable is shadowed in inline assembly by an instruction of the same name` but I see no way to disable it.
I am not using the shadowed opcodes or the involved variable and so I do not want to hear about it.

## Specification
First, if the shadowed variable is not referenced in the inline assembly, no warning should be printed.

Second, the warning can be disabled similarly to other warnings, with warning name `no-shadowed-inline-assembly`

## Backwards Compatibility
When switching between newer and earlier versions of the compiler some tools may expect this warning. So I propose this change goes in a minor revision (eg 0.9), to catch `^`.

**Comment by wjmelements** [comment]
The warning is currently emitted by `warnVariablesNamedLikeInstructions`

**Comment by chriseth** [comment]
This is fixed in the latest version of the compiler, the warning does not exist anymore.

**Comment by wjmelements** [comment]
Sorry, I had pulled the wrong remote when checking this.
