### ISSUE TITLE
@custom: documentation tag causes error

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#11152]
## Description

Changelogs states that, since version 0.8.2, the @custom tag [is documented as being supported](https://docs.soliditylang.org/en/v0.8.2/natspec-format.html). The documentation states that "context: everywhere".

I wanted to see how such documentation entries appear in the AST.

However, trying to use it gives me errors from the DocstringParsingError:

## Environment

- Compiler version: 0.8.2 and 0.8.3
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): testet in hardhat & remix
- EVM execution environment / backend / blockchain client: N/A
- Operating system: archlinux is you really care to know

## Steps to Reproduce

Try compiling the following contract
```solidity
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.2;

/// @custom: natspec for contract-definition
contract Test {
    /// @custom: natspec for storage-definition
    uint256 public x = 0;
    /// @custom: natspec for event-definition
    event Incremented();
    /// @custom: natspec for function-definition
    function incr() external returns (uint256) {
        /// @custom: natspec for event
        emit Incremented();
        /// @custom: natspec for variable-assignement
        return ++x;
    }
}
```

Errors:
```
DocstringParsingError: Documentation tag @custom: not valid for contracts.
DocstringParsingError: Documentation tag @custom: not valid for public state variables.
DocstringParsingError: Documentation tag @custom: not valid for events.
DocstringParsingError: Documentation tag @custom: not valid for functions.
```

**Comment by chriseth** [comment]
You should not use a space after the `:`. @christianparpart can you please add an example about how to use the custem tag into the contract that is already on that documentation page? Thanks.

**Comment by Amxx** [comment]
Thank you for your quick answer. I second that an example in the doc would be great!

**Comment by axic** [comment]
Shouldn't we have a proper error message on `@custom:` i.e. the actual tag missing?
