### ISSUE TITLE
[Z3] Failed assertion for test with abi.encode()

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11161]
## Description

```
pragma experimental SMTChecker;
contract C {
  function f() public { abi.encode(); }
}
```

throws

```
solc: /usr/local/include/z3++.h:1835: z3::expr z3::cast_ast<z3::expr>::operator()(z3::context &, Z3_ast): Assertion `Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST || Z3_get_ast_kind(c, a) == Z3_APP_AST || Z3_get_ast_kind(c, a) == Z3_QUANTIFIER_AST || Z3_get_ast_kind(c, a) == Z3_VAR_AST' failed.
Aborted (core dumped)
```

during compilation `solc test.sol`

Not sure if we should report this upstream instead.

**Comment by bshastry** [comment]
Perhaps this has to do with the Z3 installed on my laptop (`4.4.0`)

**Comment by axic** [comment]
Happens for me on 4.8.9 too.

**Comment by leonardoalt** [comment]
> Perhaps this has to do with the Z3 installed on my laptop (`4.4.0`)

That shouldn't even compile though

**Comment by axic** [comment]
Why not?

```
Warning: Statement has no effect.
 --> 11161.sol:3:25:
  |
3 |   function f() public { abi.encode(); }
  |                         ^^^^^^^^^^^^
```

I guess one could argue we should restrict this at some point?

**Comment by leonardoalt** [comment]
I mean the compiler won't compile with z3 4.4.0.
And the dynamic linking should fail if it's not 4.8.X

**Comment by axic** [comment]
I do get the same crash with 4.8.9, so whether 4.4.0 should work or not, this problem still exists.

**Comment by leonardoalt** [comment]
Sure, I'm just still wondering how it also happened with 4.4.0.

**Comment by bshastry** [comment]
> > Perhaps this has to do with the Z3 installed on my laptop (`4.4.0`)
> 
> That shouldn't even compile though

I think I'm wrong. Let me check again. What is the preferred way of checking which z3 library, the solc binary links against? `ldd solc`?

**Comment by blishko** [comment]
I got a crash on this example also with Z3 4.8.10.

**Comment by leonardoalt** [comment]
@bshastry yep `ldd` should work

**Comment by axic** [comment]
`abi.encodePacked()` crashes too. `abi.encodeWithSelector(0)`/`abi.encodeWithSignature("")` does not.
