### ISSUE TITLE
[SMTChecker] Add option to choose contracts to be analyzed

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#11168]
Currently all non abstract contracts are analyzed, but most of the time most contracts are used rather as parents of the "most derived contract" which is what the developer actually cares about.
This would be similar to the `outputSelection` JSON option.
CLI: `solc --model-checker-contracts FileA:ContractA,FileA:LibraryL`
JSON: `modelChecker.contracts="FileA:ContractA,FileA:LibraryL"`
Keep it as a string in the JSON input as well makes it possible to re-use code for both, but a JSON array would also be fine.

**Comment by axic** [comment]
#11030 proposes a natspec annotation for excluding certain unsolveable functions. Would it make sense considering it here under an "exclude list" option instead?

**Comment by leonardoalt** [comment]
I think those are different things. One is not really removing some functions, but rather abstracting them. The other is not considering contracts as the most derived at all.

From a usability point a view, when analyzing a contract, I think most other contracts present (in the same SourceUnit or imported) would not be analyzed as "the most derived", similar to how bytecode is not generated for most contracts, but usually just for the "most derived" which will be deployed. Because of that, I see this more like an "include list", and would prefer having a compiler option for it, instead of marking most contracts as "do not analyze".

**Comment by leonardoalt** [comment]
Decision from call:
Keep this as a cli/json option.

**Comment by axic** [comment]
We still need to define the format for the standard JSON.

An idea:
```
modelChecker: {
    targetContacts: [
        { "path": "@/dir1/file1.sol", "contract": "MyContract", "verificationTargets": [ "overflow", "underflow" ] }
    ]
}
```

or following the syntax of the `libraries` setting:
```
modelChecker: {
    targetContacts: {
        "@/dir1/file1.sol": {
            "MyContract": { "verificationTargets": [ "overflow", "underflow" ] }
         }
    }
}
```

**Comment by leonardoalt** [comment]
Why not keep the targets outside?

**Comment by axic** [comment]
Is there a use case one wants to check different properties for different contracts?

**Comment by leonardoalt** [comment]
Not necessarily. But I feel like that's a setting that's independent from which contract you're verifying
