### ISSUE TITLE
[Yul] ICE when assembling: `Cannot push and assign immutables in the same assembly subroutine`

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#11174]
## Description

This Yul file:

```
{
    setimmutable(0, "abc", loadimmutable("abc"))
}
```

```
root@ba087edf5361:~/solidity/test# ../build/solc/solc t.yul --strict-assembly --optimize
Warning: Yul is still experimental. Please use the output with care.

======= t.yul (EVM) =======

Pretty printed source:
object "object" {
    code {
        {
            setimmutable(0, "abc", loadimmutable("abc"))
        }
    }
}

Exception while assembling: /solidity/libevmasm/Assembly.cpp(585): Throw in function const solidity::evmasm::LinkerObject &solidity::evmasm::Assembly::assemble() const
Dynamic exception type: boost::wrapexcept<solidity::evmasm::AssemblyException>
std::exception::what: Cannot push and assign immutables in the same assembly subroutine.
[solidity::util::tag_comment*] = Cannot push and assign immutables in the same assembly subroutine.
```

Not sure really relevant, again, since it's an assembly failure, but I'll report all these for triaging.  Doesn't matter if there's an --optimize or not, since this one doesn't optimize away.

On master, using AFL fuzzing of yul inputs via '--strict-assembly'.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.4-develop.2021.3.25+commit.d75a132f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04.1 LTS in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by axic** [comment]
I guess we need to improve the analyzer to issue a nicer warning. That may be difficult though as we do not maintain yet such contextual information about builtins, i.e. what is used already and any dependencies/exclusions.

Probably the solution would be having an optional analyzer step exposed by the dialect, which could deal with such complex scenarios.

These builtins are only available in the "yul with objects", which is not the one exposed in inline assembly, so at least it is less likely anyone is running into this.
