### ISSUE TITLE
Compiler opton: target EVM version

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1117]
I think we should add an option to select the target EVM version (frontier, homestead, metropolis, etc.)

Maybe this isn't such a big issue anymore for Frontier as everyone moved on to Homestead, but by the time we move on to Metropolis, Homestead will have a much bigger user base.

Key differences:
- Homestead:
  - delegatecall
- Metropolis
  - new gas costs (https://github.com/ethereum/EIPs/issues/150)
  - new opcodes (e.g. https://github.com/ethereum/EIPs/issues/145)
  - new behaviour (e.g. https://github.com/ethereum/EIPs/issues/8)

Alternatively we might put this into a `pragma` instead of a compiler option.

**Comment by axic** [comment]
Probably we would need both:
- the actual target version used in the compiler
- pragma for defining the requirement in a given source code (that covers what inline assembly instructions are valid for that file and what the user expects in terms of gas usage; if the pragma is lacking, it accepts any version defined by the compiler):

`pragma evm homestead;`
`pragma evm metropolis;`

Then, we have two options:
- reject compilation if different evm versions are requested
- use the highest common denominator (I see this as a no go, as it is hard to decide what changes are compatible)

**Comment by axic** [comment]
I think we should have the following components:
1. target EVM version as a compiler flag
2. target gas table (referred to by hardfork names) as a compiler flag
3. required EVM version as a pragma following semver

EVM versioning is simple if we follow https://github.com/ethereum/EIPs/issues/178 as the current semver handler can be reused:

```
pragma evm ^1.1; // to select homestead
pragma evm ^2.0; // to select EIP150
```

**Comment by chriseth** [comment]
I would say the default should be to target the EVM that is active on the mainnet. Pragmas can revert specific features to older EVM versions.

**Comment by axic** [comment]
Latest discussion have lead to considering `pragma target byzantium`, but eventually it turned out that due `pragma` being `SourceUnit`-local that would cause a headache during inheritance for users.

It seems to be a much better option to have a compiler option instead.

This should be presented to the user as:
- `--evm-version byzantium` on the the commandline
- `settings: { evmVersion: "byzantium" }` in jsonio

The evm versions are lowercase and we define `homestead` and  `byzantium` as the two options for now. We default to `byzantium`.

The `evmVersion` must also be present in the settings in the metadata.

**Comment by chriseth** [comment]
Added the "annoys users" label because this makes it impossible to use `returndatacopy` and others without warning.
