### ISSUE TITLE
[yul] ICE in `Object::pathToSubObject()` when accessing data of a subobject

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#11175]
## Description

This Yul file:

```
object "t" {
	code {
		datacopy(not(datasize("object4.datablock")), 0, 0)
	}
	object "object4" {
				code{}
				data "datablock" ""
			}
}
```

```
root@ba087edf5361:~/solidity/test# ../build/solc/solc q.yul --strict-assembly
Warning: Yul is still experimental. Please use the output with care.

======= q.yul (EVM) =======

Pretty printed source:
object "t" {
    code {
        datacopy(not(datasize("object4.datablock")), 0, 0)
    }
    object "object4" {
        code { }
        data "datablock" hex""
    }
}

Exception while assembling: /solidity/libyul/Object.cpp(110): Throw in function vector<size_t> solidity::yul::Object::pathToSubObject(solidity::yul::YulString) const
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what: Assembly object <object4.datablock> not found or does not contain code.
[solidity::util::tag_comment*] = Assembly object <object4.datablock> not found or does not contain code.
```

Not sure really relevant, again, since it's an assembly failure, but I'll report all these for triaging.  Doesn't matter if there's an --optimize or not, since this one doesn't optimize away.

On master, using AFL fuzzing of yul inputs via '--strict-assembly'.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.4-develop.2021.3.25+commit.d75a132f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04.1 LTS in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by axic** [comment]
I think `object4.datablock` should be reachable, so the issue must be that it is empty.

**Comment by bshastry** [comment]
May be a duplicate https://github.com/ethereum/solidity/issues/9470

**Comment by agroce** [comment]
Yeah, I bet this is the fuzzer pruning out parts of #9470, if it made it into the libyul tests?  Though sort of weird if it made it into corpus without being caught, since AFL will yell if a corpus input fails.  But the code looks like a direct slice of that code.

**Comment by agroce** [comment]
While not a fuzz-blocker per se, if it's possible to get reasons for --strict-assembly to bomb out during assembly down to ones that are Actual Serious Bad Things, and die more gracefully otherwise, it would definitely ease fuzzer triage on Yul.  It piles up a lot of these assembly failures.  Or, alternatively, if we think assembly failures are almost always "the front end never does this anyway" I can probably ignore them?

**Comment by axic** [comment]
I think this particular issue is a bug, or at least I am unclear why we consider empty objects an issue.

**Comment by axic** [comment]
Possibly duplicate of #9470

**Comment by axic** [comment]
Extended tests and it seems this problem only shows up when accessing nested data objects. It is not related to being empty, but rather accessing nested data is not working.

**Comment by chriseth** [comment]
Even if code is non-empty, accessing data fields in other objects is just not supported by the code currently.

**Comment by cameel** [comment]
I don't think this is caused by the code being empty. Something like this reproduces the code as well (on 0.8.17, unoptimized):

```yul
object "C_27" {
    code {
        pop(datasize("C_27_deployed.datablock"))
        sstore(0, calldataload(0))
    }
    object "C_27_deployed" {
        code {
            sstore(1, calldataload(0))
        }

        data "datablock" hex"a264697066735822"
    }
}
```

It looks like a general problem with accessing the data of subobjects.

**Comment by cameel** [comment]
Closing in favor of #9470.
