### ISSUE TITLE
Add new natspec tags to pygments-lexer-solidity

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11171]
https://github.com/veox/pygments-lexer-solidity is used by our documentation for syntax highlighting. @veox the repository does not have issues enabled, so opening this here.

![Screenshot](https://user-images.githubusercontent.com/20340/112486848-2ae05600-8d74-11eb-856b-75f4a7de1cce.png)

`@inheritdoc` and `@custom:..` is not highlighted.

**Comment by veox** [comment]
> @veox the repository does not have issues enabled (...)

That's because the repo is actually on gitlab:

https://gitlab.com/veox/pygments-lexer-solidity

**Comment by veox** [comment]
Regex `custom:[a-zA-Z_]\w*` should be fine for the `@custom:..`, right?..

-----

Ah, from https://github.com/ethereum/solidity/blob/ecf7f21d55f72a567e5a3f9cd89610f5ea67f564/docs/natspec-format.rst:

> Custom tags start with `@custom:` and can contain lowercase characters and hyphens following that.

**Comment by axic** [comment]
It is actually `@custom:[a-z][a-z-]*`. The documentation is being updated in #11170.

**Comment by axic** [comment]
We may want to update keywords too. Should I submit a PR?

It seems at least the following could be added:
- `bytes.concat`
- `pragma abicoder`
- `catch Panic([^)])`
- `unchecked`

**Comment by veox** [comment]
I've not gone through the release notes since Solidity v0.6, says the README file.

A PR (MR on gitlab) is great, sure.

-----

The NatSpec I've just done, BTW.

**Comment by veox** [comment]
https://pypi.org/project/pygments-lexer-solidity/0.6/

v0.6 has been pushed to PyPI with the two new NatSpec keywords.

**Comment by axic** [comment]
@veox thanks! Just pushed the keyword changes: https://gitlab.com/veox/pygments-lexer-solidity/-/merge_requests/5

**Comment by axic** [comment]
And also the SPDX identifier, I'm not sure this should be merged or not: https://gitlab.com/veox/pygments-lexer-solidity/-/merge_requests/6

The compiler uses it in a special way, hence highlighting it may be useful.

**Comment by veox** [comment]
> The compiler uses it in a special way, hence highlighting it may be useful.

Then definitely worth inclusion.

Merged both, released as v0.7:

https://pypi.org/project/pygments-lexer-solidity/0.7.0/

**Comment by axic** [comment]
Thanks! I'll create a PR updating our docs now.
