### ISSUE TITLE
Extend ConstantEvaluator to interpret type(XXX).max

### ISSUE THREAD

**Issue by hoytech** [ethereum/solidity#11183]
Tried with solc 0.8.3:

```solidity
pragma solidity ^0.8.0;

contract Test {
    uint[type(uint16).max] test;
}
```

And got this:

```
$ solc-0.8.3 Test.sol
Error: Invalid array length, expected integer literal or constant expression.
 --> Test.sol:4:10:
  |
4 |     uint[type(uint16).max] test;
  |          ^^^^^^^^^^^^^^^^
```

**Comment by chriseth** [comment]
I actually find it quite intuitive that `type(X).max` is of type `X`, so I don't think we should change that. What we could change, though, is adding this as a feature to the constant evaluator used for these purposes.

**Comment by hoytech** [comment]
Thank you for your reply!

I have no issue with the type of `type().max`. It's just like the template in C++ `std::numeric_limits`.

Actually my ideal use case would be like this, which I left out to simplify the description:

    uint private constant MAX_VAL = uint(type(uint16_t).max);
    uint[MAX_VAL + 1] test;

**Comment by ekpyron** [comment]
Closing this as being subsumed under https://github.com/ethereum/solidity/issues/13318, which is a roadmap item.
