### ISSUE TITLE
Make the formal specification of the ABI encoding easier to understand

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11191]
[Formal Specification of the Encoding](https://docs.soliditylang.org/en/v0.8.3/abi-spec.html#formal-specification-of-the-encoding) is precise but pretty dense which makes understanding it hard for people who are not already intimately familiar with the ABI. Even explaining it can sometimes be hard without tediously going through concrete examples, see for example [this discussion on gitter](https://gitter.im/ethereum/solidity-dev?at=60546a023b9278255bbc90a5). The examples that are already available in the spec help but are not enough on their own.

We should rewrite this section to make it easier to digest. Or at least expand it and add a diagram. I think that visualizing the layout and nesting would be the best way to make it easy to understand.

**Comment by chriseth** [comment]
I think it is important to keep the specification itself concise, but we should add more examples and explain it a bit better either before or afterwards.

**Comment by cameel** [comment]
I've heard people complain about the current spec being hard to understand several times so I think we should really do this. Reopening.

**Comment by ekpyron** [comment]
I'm disagreeing, our main job is to provide the spec, everything else is optional and this is too low priority to keep an issue about, unless it's actively opened by somebody other than us.
