### ISSUE TITLE
Automate updates of robots.txt

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11199]
From https://github.com/ethereum/solidity/pull/10972#issuecomment-782226746

After merging #10972 we will need to manually update `robots.txt` on every release to disable indexing of the previous version. It would be more convenient to have a simple script that regenerates it automatically.

We could have a small Python script that reads versions from the existing `robots.txt` (or, alternatively, fetches tags from github API), compares with the output of `get_version.sh` and spits out a new file. The script could also be executed as a part of `scripts/docs.sh`.

**Comment by cxxboy** [comment]
@cameel I can work on this, Does the updated version gets prefixed by `#Disallow` and the deprecated ones gets prefixed by `Disallow`?
In other words, If we need to allow a certain version, let's call it `v0.8.5` for example and deprecate `v0.8.4`, Do we need to change the `robots.txt` from
```
(removed)
#Disallow: /en/v0.8.4/
```
to
```
(removed)
Disallow: /en/v0.8.4/
#Disallow: /en/v0.8.5/
```
Is this what supposed to happen(by comparing the outputs of `get_version.sh`)? Or I'm missing something, if so can you point in right direction?

**Comment by cameel** [comment]
@cxxboy Yeah, that's basically it. In #10972 there's still some discussion about which version to allow and which to block, but if you're just updating the existing file rather than regenerating it from scratch, it should not matter.
