### ISSUE TITLE
Inline assembly: rename non-function-style instructions to upper case

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1119]
Right now it can get confusing to mix both styles of instructions. I think it makes sense keeping function-style instructions lower case (with parentheses), while having non-function-style instructions match the usual assembly representation (i.e. uppercase only).

```
assembly {
  let a := add(3, 2)
}
```

```
assembly {
  3
  2
  ADD
}
```

**Comment by VoR0220** [comment]
I approve of this change.

**Comment by chriseth** [comment]
What is the problem you are trying to solve here? functional-style and instruction-style opcodes can already be easily distinguished by the parentheses. It might be that there is a more fundamental problem below that you are trying to tackle.

**Comment by axic** [comment]
The problem was making a harsh distinction between `Instruction` and `FunctionalInstruction` (now `FunctionCall`).

With recent changes, such as replacing instructions with builtins in Julia this can be considered sorted.
