### ISSUE TITLE
Behaviour with multiple different SPDX licenses

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11204]
`I.sol`:
```
// SPDX-License-Identifier: GPL-2.0-or-later

interface I {
  function f() external;
}
```

`C.sol`:
```
// SPDX-License-Identifier: GPL-3.0

import "I.sol";

contract C is I {
  function f() override external {
  }
}
```

The above seems to result in the following metadata:
```
{"compiler":{"version":"0.8.4-develop.2021.3.26+commit.d75a132f"},"language":"Solidity","output":{"abi":[{"inputs":[],"name":"f","outputs":[],"stateMutability":"nonpayable","type":"function"}],"devdoc":{"kind":"dev","methods":{},"version":1},"userdoc":{"kind":"user","methods":{},"version":1}},"settings":{"compilationTarget":{"I.sol":"I"},"evmVersion":"istanbul","libraries":{},"metadata":{"bytecodeHash":"ipfs"},"optimizer":{"enabled":false,"runs":200},"remappings":[]},"sources":{"I.sol":{"keccak256":"0x84ec0dd55f9ee2668d9bd815128fc50341da0f95dc61daae52b5ce0c150324b9","license":"GPL-2.0-or-later","urls":["bzz-raw://d0745f91aebb069a887426c9252c7e87c9b3847a1d3ee931757fba606a1fc8fd","dweb:/ipfs/QmerypZr5nJaJqJx4ja2cpkJ4a6Jpr463UGXLQoKjXxL2H"]}},"version":1}
```

Notice that it decided to use the value of the first encountered SPDX license tag.

Some potential options we could do:
a) Omit the license field if there are multiple different licenses
b) Change the `license` field to be an array, and list all
c) Issue an error(warning) if this happens

Probably c) is a non-runner, and b) seems to be the most sane to me.

(Noticed this while checking out [uniswap-v3-core](https://github.com/Uniswap/uniswap-v3-core) as it has some interfaces licensed as `GPL-2.0-or-later`, but the main contracts are `BUSL-1.1`.)

**Comment by axic** [comment]
Sorry, looked at the wrong generated output. The compiler properly generates the `GPL-2.0-or-later` metadata for the interface and `GPL-3.0` metadata for the contract.

However, I think this behaviour is wrong, because it only outputs the license of the top level file used for compilation, but it should really list all the licenses present in every imported file. (Checking whether anything from those files is used does not matter, they are "used" as long as the file is imported.)

**Comment by chriseth** [comment]
The metadata includes all sources required to compile the contract and for each source it includes the license. There is no "top level file".

**Comment by axic** [comment]
The "top level file" is the sourceunit in which the currently compiled contract is defined. I think it is misleading (and not very useful) we only include the license of that, and not a list of every single one included in the import chain.

**Comment by chriseth** [comment]
In your example, I see one license tag per file and all files that are needed are included. Can you please explain what you are seeing?
