### ISSUE TITLE
Transaction reverts if tx.gasprice is used IN ANY WAY in transfer/send/call's value

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [ethereum/solidity#11219]
## Description
Solidity contract compiled in 0.6.2, 0.7.0, 0.7.4 and even 0.8.0 reverts with `OUT_OF_GAS` if `tx.gasprice` is used in any way for transferring `ETH` on `Ropsten` and `Goerli` networks!

The issue is reproduced when using `send` or `call` as-well

The same contract call is working fine on the local ganache or hardhat node.

Example:
```Solidity
pragma solidity 0.8.0;

contract Test {

    // reverts
    function test() external {
        address payable addr = payable(msg.sender);
        addr.transfer(tx.gasprice);
    }
    // works
    function test1() external {
        address payable addr = payable(msg.sender);
        addr.transfer(1000000000); // 1gwei
    }

    receive() external payable {}
}
```
Expectation:
The transaction call not to revert and the msg sender to be refunded with the correct amount.

## Environment

- Compiler version: `0.6.2`, `0.7.0`, `0.7.4`, `0.8.0`
- Target EVM version (as per compiler settings): 
- Framework/IDE (e.g. Truffle or Remix): `Hardhat`
- EVM execution environment / backend / blockchain client: Infura
- Operating system: MacOS BigSur 11.2.1

## Steps to Reproduce

1. Deploy the provided source code on Ropsten/Goerli
2. Send 1 ETH to the contract
3. Call the `test` function

Example TX:
`test` -> https://ropsten.etherscan.io/tx/0x89c74a6951116783aa1568d1c3d79d71d1a6aee3b027fc58144c5103377dddc8
`test1` -> https://ropsten.etherscan.io/tx/0x4fa187cb9c3cfcaaa79f199db8cbabeea2956faab2b962911f0fd76871486b75

**Comment by Daniel-K-Ivanov** [comment]
Closing this issue, since it turns out that the automated `estimateGas` functionality is providing invalid number. I hardcoded a big `gasLimit` and the same transaction went through:
https://ropsten.etherscan.io/tx/0x813b34273ac699ed0294f32c1a86a4172eb808577ceff893ef04d1482beb8bf5

**Comment by lopezdp** [comment]
im seeing that today too. I tested `tx.gasprice` on its own today and it just returns 0... I need this guy!

I get the same out of gas error in Koran too:

https://kovan.etherscan.io/tx/0x82d562f100e866a9ac9a913c7d95a4d5c4b330e51fa5291bc63a6669bf3121f1

**Comment by zakrad** [comment]
I get 0 for tx.gasprice on mainnet and fork

> im seeing that today too. I tested `tx.gasprice` on its own today and it just returns 0... I need this guy!
> 
> I get the same out of gas error in Koran too:
> 
> https://kovan.etherscan.io/tx/0x82d562f100e866a9ac9a913c7d95a4d5c4b330e51fa5291bc63a6669bf3121f1
