### ISSUE TITLE
how can I solve ax^2 + bx + c = 0 equation in solidity?

### ISSUE THREAD

**Issue by huahuayu** [ethereum/solidity#11223]
hi, we know that `ax^2 + bx + c = 0` equation solution is 

![image](https://user-images.githubusercontent.com/1725060/113962223-d4861380-9859-11eb-80bd-6868692186c6.png)

we can simply write below code: 

```sol
pragma solidity 0.6.6;
contract Cal {
    // solve equation: ax^2 + bx + c = 0, 
    // if no real number solution, return 0
    function solution(int256 a, int256 b, int256 c) pure external returns (int256,int256){
        if (b*b < 4*a*c){
            return (0,0);
        }
        int256 numerator1 = -b + sqrt(b*b - 4*a*c);
        int256 numerator2 = -b - sqrt(b*b - 4*a*c);
        return (numerator1 / (2*a), numerator2 / (2*a));
    }
    
    function sqrt(int256 x) internal pure returns (int256 y) {
        int256 z = (x + 1) / 2;
        y = x;
        while (z < y) {
            y = z;
            z = (x / z + z) / 2;
        }
    }
}
```

**Problem1:** sqrt will produce float number, and it will be truncated (say 3.99 -> 3), the result is not accurate, how to make it more accurate is a problem.

**Problem2:** if a,b,c is a very big number (let's say, it's eth balance in wei), b^2 or a*c will overflow, actually need an int512 to store int256 * int256 value. But there is no int512 type, int256 is the biggest.

if it can't be (or hard to) solve in solidity, may vyper make it easier to implement?

**Comment by hrkrshnn** [comment]
Please ask such questions in Solidity gitter or matrix channel.

https://gitter.im/ethereum/solidity
