### ISSUE TITLE
[yul] Divergence in behavior between optimized and un-optimized yul

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#11227]
## Description

This Yul file:

```
{
    sstore(0, 123213)
for {let x := 1 let y} lt(x, sload(0)) { x := add(x, 1)} {y := add(x, y) }
}
```

```
optimized yul:
object "object" {
    code {
        {
            let _1 := 123213
            sstore(0, _1)
            let x := 1
            let x_1 := x
            let y := 0
            for { } lt(x_1, _1) { x_1 := add(x_1, x) }
            { y := add(x_1, y) }
        }
    }
}

optimized trace:
Trace:
Memory dump:
Storage dump:
  0000000000000000000000000000000000000000000000000000000000000000: 000000000000000000000000000000000000000000000000000000000001e14d

un-optimized yul:
object "object" {
    code {
        sstore(0, 123213)
        for {
            let x := 1
            let y
        }
        lt(x, sload(0))
        { x := add(x, 1) }
        { y := add(x, y) }
    }
}

un-optimized trace:
Killed
```

Probably just an infinite loop the optimizer gets rid of, and the un-optimized Yul locks up on, but wanted to check since this is the only non-stack/unimplemented operations result in a week of fuzzing, and I'm not 100% sure what should happen here, since the loop does contain variables not erased, and doesn't just go away.

On master, using AFL fuzzing of yul inputs via '--strict-assembly'.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.4-develop.2021.4.8+commit.a364e935.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04.1 LTS in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by hrkrshnn** [comment]
I don't see how the unoptimized code is an infinite loop. How did you execute the unoptimized code? The loop alone would cost around 100 million gas. The optimized loop would be cheaper.

**Comment by agroce** [comment]
Ok, it's just a cheaper loop/timeout, then, confirmed.  Closing.
