### ISSUE TITLE
Accepts Invalid code: events invocation accepted without "emit" keyword

### ISSUE THREAD

**Issue by Aleione** [ethereum/solidity#11226]
## Description

In the below contracts, if you remove emit from the first event invocation it doesn't compile, if you switch the order of invocation it does not compile.
In this case it compiles despite missing of `emit` keyword for second event invocation.

## Environment

- Compiler version: 0.6.12, 0.7.0, 0.8.0 with or without optimizer enabled
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix/Truffle/Hardhat
- EVM execution environment / backend / blockchain client: any
- Operating system: any

## Steps to Reproduce

Compile either of these contracts:

```solidity
pragma solidity ^0.8.0;
 contract test {
    
    event SetFirstElem(uint indexed elem);
    
    event SetSecondElem(uint indexed elem);
    
    function setVal() external  {
        emit SetFirstElem(0);
    }

    function setValX() external  {
        SetFirstElem(1); //This should not compile
    }
}
```

```solidity
pragma solidity ^0.8.0;
 contract test2 {
    
    event SetFirstElem(uint indexed elem);
    
    event SetSecondElem(uint indexed elem);
    
    function setVal() external  {
        emit SetFirstElem(0);
    }

    function setValX() external  {
        SetSecondElem(1);  //This should not compile
    }
}
```

**Comment by hrkrshnn** [comment]
The reason is that `m_insideEmitStatement` is never reset to `false`. https://github.com/ethereum/solidity/blob/b04b189959cc4571f39269a8252a5a61ae9b14a6/libsolidity/analysis/PostTypeChecker.cpp#L297. The bug was accidentally fixed when implementing custom errors!

I'll add a changelog entry and close this in develop.

**Comment by hrkrshnn** [comment]
@Aleione Thanks for the issue. It was a really nice find.
