### ISSUE TITLE
Solidity repository (mis)tagging

### ISSUE THREAD

**Issue by 5chdn** [ethereum/solidity#1123]
Copy and pasted from gitter as requested by @bobsummerwill / also affects the cpp-ethereum repository where I'm going to crosspost this, also as suggested by bob.

> Hi, could we talk about git tags for the cpp-ethereum and solidity repositories? cpp-ethereum is tagged with `untagged-1d50...` and solidity shows `untagged-0ce6...` aswell as `1.0.704`. Another issue is the _pre_-pending of the develop string regarding the sorting of tags. cpp-ethereum has for example `develop-v1.3.0.401`. Since I'm providing builds not only for stable but also intermediate releases, this is causing me some trouble. I would like to suggest the following and I'm open for discussion / feedback:
> - avoid `untagged` tags.
> - append a version string rather than prepending it, e.g. `v1.3.0.401-dev` rather than `develop-v1.3.0.401`
> - don't switch between version strings with `v` and without
> - if you use a dedicated `release` branch to tag stable releases, please merge the tags back into `develop`
> 
> Thanks for your time.

**Comment by 5chdn** [comment]
ref https://github.com/ethereum/cpp-ethereum/issues/3319

**Comment by chriseth** [comment]
@bobsummerwill please disable any automated tag generation, as discussed, this is both too inflexible and too cumbersome with regards to race conditions. I would suggest the following workflow:
- workers in CI infrastructure (travis / azure / ...) generate binaries and upload them to some place
- cron job in central server generates release and attaches binaries

**Comment by chriseth** [comment]
We can now always merge back into develop, so closing this.
