### ISSUE TITLE
solc-windows.exe not installing the compiler

### ISSUE THREAD

**Issue by waytoashutosh** [ethereum/solidity#11232]
## Description
The solc-windows.exe version is not able to install the compiler. A cmd pops up, does few stuff and then closes.

## Environment

- Compiler version: 0.8.3
- Operating system:Windows

## Steps to Reproduce
1. Download the solc-windows.exe and run.

**Comment by cameel** [comment]
It's a stand-alone command-line binary. It's not supposed to install anything.

It has no GUI. You need to open a CMD or PowerShell session to interact with it.

**Comment by alvissraghnall** [comment]
> It's a stand-alone command-line binary. It's not supposed to install anything.
> 
> It has no GUI. You need to open a CMD or PowerShell session to interact with it.

How then do I use it to compile a smart contract, say in some other folder? Apologies as this could be a trivial question, but i'm kinda slow..

**Comment by cameel** [comment]
Something like this:
```
solc.exe C:\your\project\dir\contracts\file.sol --base-path C:\your\project\dir
```
And you only really need `--base-path` if you're not in the main project dir.
