### ISSUE TITLE
Doc fix about accessors automatically generated

### ISSUE THREAD

**Issue by chevdor** [ethereum/solidity#1124]
The doc mentions:

> Accessor Functions
> The compiler automatically **creates accessor functions for all public state variables**. For the contract given below, the compiler will generate a function called data that does not take any arguments and returns a uint, the value of the state variable data. The initialization of state variables can be done at declaration.

It sounds important to me to mention that the generated accessor functions are only the **getters** and not any **setters** for public state variables.

**Comment by redsquirrel** [comment]
I think it would also be good to show an example of how array getters are generated. The initial assumption is that the getter would return the entire array, but it actually requires an index and returns the element at that index.

**Comment by chriseth** [comment]
These are two different issues, but they can be solved in one go.
