### ISSUE TITLE
Dynamic Memory Arrays Compile

### ISSUE THREAD

**Issue by AlphaSerpentis** [ethereum/solidity#11251]
## Description

Creating a dynamic memory array compiles, but expect it to not compile since the EVM throws an invalid OPCODE.

## Environment

- Compiler version: 0.6.10 and 0.8.3 individually
- Target EVM version (as per compiler settings): Muir Glacier
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix's JavaScript VM
- Operating system: Windows 10 Home

## Steps to Reproduce

```solidity
pragma solidity 0.8.3;

contract Test {
    function thisShouldNotWork() external {
        uint256[] memory test; // Create dynamic memory array of any type
        
        for(uint256 i; i < 10; i++) {
            test[i] = i;
        }
    }
}
```

**Comment by ekpyron** [comment]
To actually create allocate a dynamic memory array you have to use ``new``.
I.e. in your code ``test`` refers to a a dynamic memory array of size zero, so any access to it will be out-of-bounds and revert.
It's near impossible to detect out-of-bounds accesses at compile-time in all cases, so the best we can do is to revert on runtime.

If you want your snippet to work and not to revert, you can change it to this:
```solidity
contract Test {
    function thisShouldNotWork() external {
        uint256[] memory test = new uint256[](10); // Create dynamic memory array of size 10.
        
        for(uint256 i; i < 10; i++) {
            test[i] = i;
        }
    }
}
```

**Comment by ekpyron** [comment]
I hope this answered the issue, so I'm closing it, but please feel free to reopen, if you think otherwise!
