### ISSUE TITLE
Unnecessary compiler warning 'Unnamed return variable can remain unassigned'

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#11265]
## Description

Solc emits:
```
Warning: Unnamed return variable can remain unassigned.
Add an explicit return with value to all non-reverting code paths or name the variable.
```
For a **reverting** code path.

## Environment

- Compiler version: 0.8.3
- Framework/IDE: Truffle
- Operating system: MacOS

## Steps to Reproduce

Compile this:
```
   function func(uint256 x) internal view returns (uint256) {
        if (x < 42)
            return x;
        require(false);
    }
```

**Comment by chriseth** [comment]
The compiler currently does not analyze boolean expressions for this warning. If we start doing this, we have to define a point to stop the analysis, which will probably result in more problems than not doing it at all.

Would changing your code to a `revert()` be a solution for you?

**Comment by barakman** [comment]
Sure, I didn't give it a try because I figured that it wouldn't make any difference.
I'll give it a try now, but note that this solution would not support `require(false, msg)`, which is more informative than `revert`.

**Comment by chriseth** [comment]
What about `revert(msg)`?

**Comment by barakman** [comment]
Oh heck, how could I have been so dumb?
Please ignore; thanks.
