### ISSUE TITLE
Choose between why3 and F*

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1127]

**Comment by pirapira** [comment]
The current focus is how well each tool can handle the mappings of mappings.

I'll try to translate the following contract manually into Why3, F\* .

```
contract Token {
  mapping (address => mapping (address => uint)) allowance;

  function approve(address _delegate, uint _value) returns (uint)
  {
    allowance[msg.sender][_delegate] = _value;
    return 1;
  }

  function sendFrom(address _from, address _to, uint _value) returns (uint)
  {
    if (_value > allowance[_from][msg.sender])
      throw;
    allowance[_from][msg.sender] = allowance[_from][msg.sender] - _value;
    return 1;
  }
}
```

I think I should compare the bytecode level approach at the same time, so I will take the compiled bytecode and write a proof that no underflow happens, assuming no hash collision.

**Comment by pirapira** [comment]
My current judgment is to use neither Why3 or F*.  See Path a and Path b in https://github.com/pirapira/ethereum-formal-verification-overview/blob/master/README.md#formal-verification-of-ethereum-contracts-yoichis-attempts
