### ISSUE TITLE
[SMTChecker] Map out of key exception in CHC.cpp

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11280]
## Description

```
==== Source:s1.sol====
function f() {}
contract C {
  function g() public virtual returns (uint) {}
}
==== Source:====
import "s1.sol" as M;
function f() returns (int) {}
contract D is M.C {
  function g() public override returns (uint) { f(); }
}
```

throws

https://github.com/ethereum/solidity/blob/c3f639b355ef94b4db43998f3e305369f6a49b45/libsolidity/formal/CHC.cpp#L1353

To reproduce, copy the test to `syntaxTests` and run with isoltest with SMTChecker enabled.

**Comment by leonardoalt** [comment]
I guess it's time to support modules

**Comment by leonardoalt** [comment]
I think this was actually caused by the free functions. I cannot reproduce the bug with latest develop, so closing.
