### ISSUE TITLE
Define bytecode-level assertion language

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1128]

**Comment by pirapira** [comment]
There is a relevant discussion going on in #1178.

**Comment by pirapira** [comment]
This comment https://github.com/ethereum/solidity/issues/1178#issuecomment-252871327 defines an assertion language.  I think this is good enough for safety properties.

**Comment by pirapira** [comment]
I think this defines it https://github.com/pirapira/eth-isabelle/blob/7bcb6113dd7d1723ee13102b04970d66456f491a/Hoare.thy#L9
although I still want to change it a bit, https://github.com/pirapira/eth-isabelle/issues/153

**Comment by chriseth** [comment]
Basic functionality is available through the assert function or the invalid opcode.
