### ISSUE TITLE
[Docs] Clarify initialisation value of state variables

### ISSUE THREAD

**Issue by ra-phael** [ethereum/solidity#11299]
In [Inheritance > Constructors](https://docs.soliditylang.org/en/latest/contracts.html#constructors) the documentation states:

> Before the constructor code is executed, state variables are initialised to their specified value if you initialise them inline, or zero if you do not.

Isn't that true only if the type of said variable is `uint` or `int`? For a `bool` for example, the value will be `false` (even though its byte-representation is all zeros).

Maybe that sentence could be changed to: "Before the constructor code is executed, state variables are initialised to their specified value if you initialise them inline, or their [default value](https://docs.soliditylang.org/en/latest/control-structures.html#default-value) if you do not."

I am happy to open a PR as well.

**Comment by leonardoalt** [comment]
@ra-phael that's correct, good catch. It would be great if you opened a PR, thanks!
