### ISSUE TITLE
Minor error in the 0.7.0-breaking-changes documentation

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#11297]
## Description

From [the 0.7.0-breaking-changes documentation](https://github.com/ethereum/solidity/blob/develop/docs/070-breaking-changes.rst#functions-and-events):

> Visibility (`public` / `external`) is not needed for constructors anymore: To prevent a contract from being created, it can be marked `abstract`. This makes the visibility concept for constructors obsolete.

It should be "`public` / `internal`" of course.

**Comment by cameel** [comment]
Yeah, looks like a mistake. Fixed in #11298. Thanks for reporting!
