### ISSUE TITLE
Include "review checklist" as part of security considerations

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11300]
This here: https://ethereum.stackexchange.com/questions/8551/security-review-checklist-for-a-smart-contract/8593#8593

(Found via https://forum.soliditylang.org/t/key-points-while-conducting-a-security-audit-of-nft-smart-contract/217/2 by @franzihei)

**Comment by cameel** [comment]
Do we just want to link to it or add a similar (possibly expanded) list in our docs instead?

**Comment by axic** [comment]
Include an expanded version in the documentation itself.
