### ISSUE TITLE
Implement rotate (and define syntax)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1132]
(Split off #33.)

We have a well defined syntax for shifts (<< and >>), but not many languages define a syntax for rotation.

One simple approach is to use an inline function `rotate_left(value, n)`, where `n` is the number of bits to rotate. The type of `value` would determine the width for rotation.

Naming proposal:
- `rotate_left` and `rotate_right`
- `rotl` and `rotr`

Usual implementation in C: http://stackoverflow.com/questions/2835469/how-to-perform-rotate-shift-in-c#answer-2835503

Any ideas for a better syntax?

**Comment by chriseth** [comment]
I strongly disagree. The usual smart contract has no use for this and you can very easily write an internal function for a library to do this. The reason we included shifts was just that we already have operands for shifts and there is an accepted notation for them.

**Comment by axic** [comment]
@chriseth I agree it is not used widely.

It could become a library function, but for that we really need inline functions. Internal still produces a jump. With jumps the overhead is just too big - consider the rotations part of internal loops of hashing functions. It is really suboptimal jumping out of the loop constantly.

**Comment by chriseth** [comment]
I agree, and that is a job for the optimizer. It is for better to have this efficiency for all small snippets and not only manually optimize those we think are more or less widely used.

**Comment by axic** [comment]
Depends on #1256 if we want to implement this as a library.
