### ISSUE TITLE
Use bumpversion to simplify the release process

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11322]
@axic has recently suggested using [bumpversion](https://pypi.org/project/bumpversion/) to handle updating version in files where it is hard-coded. Here's the [`bumpversion` config used in EVMC](https://github.com/ethereum/evmc/blob/master/.bumpversion.cfg) for example.

Looks like the original project is unmaintained, so we should use one of the forks instead. Maybe [bump2version](https://pypi.org/project/bump2version/)?

Currently I see that we have version hard-coded in the following places:
- [`PROJECT_VERSION` in the main `CMakeLists.txt`](https://github.com/ethereum/solidity/blob/v0.8.4/CMakeLists.txt#L24).
- `robots.txt` (see #11317)
- Changelog (should we automate the creation of the new `(unreleased)` section at the top?)
- The release checklist (though we probably do not want to update this one).

Before closing please make sure these are the only ones.

**Comment by cameel** [comment]
I thought we had version hard-coded in more places. Now i wonder if we actually want it if `robots.txt` will be automatically updated by `docs.sh`.

**Comment by chriseth** [comment]
There is exactly one location that specifies the version and it can be read by `version.sh`, so I don't think we need something like `bumpversion`.

**Comment by cameel** [comment]
Yeah. Let's close it then. We can always reopen if we get more of them.

**Comment by axic** [comment]
The idea behind bumpversion was that it could update `robots.txt` at the same time we wouldn't need an extra script.

**Comment by chriseth** [comment]
What is 'bumpversion' if not an extra script?

**Comment by axic** [comment]
You really just dislike bumpversion? :)
