### ISSUE TITLE
Inline assembly: address not available

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1134]
We have the following in the documentation:

> address:      address of the current contract / execution context

However it doesn't work: 

```
Untitled4:4:22: Error: Expected elementary inline assembly operation.
            let a := address
```

**Comment by chriseth** [comment]
_sigh_ why did we miss this? `address` is a keyword and thus parsed differently. We have a similar situation for `return` and `byte` already, so this has to be handled in the same way as `byte` and `return` are handled inside `AsmParser.cpp`.
