### ISSUE TITLE
provide straightforward way to leverage solc from Go

### ISSUE THREAD

**Issue by tmc** [ethereum/solidity#11346]
Lots of parts of the ethereum ecosystem are written in Go, solc being a standout exception. This detracts from the ability to rely on signature-verified toolchains for reproducible builds.

I think this project should offer go support for a lightly wrapped solc binary.

This could be implemented several ways, perhaps the most straightforward being a small wrapper that downloads and caches the appropriate solc binary (along with some signature verification).

**Comment by axic** [comment]
I think the most prominent example you are referring to is go-ethereum (and perhaps turbogeth), but I am not really aware of any popular smart contract tooling written in Go. The market leaders (Truffle, Remix, and Hardhat -- see [our survey](https://blog.soliditylang.org/2021/01/26/solidity-developer-survey-2020-results/)) are written in Typescript/Javascript.

Do you have an example of popular a Go-based framework? Or can you explain what process do you imagine where some end-to-end verification can take place while staying within the the Go ecosystem?

**Comment by tmc** [comment]
Yes I'm using go-ethereum. The abigen tool will use solc to generate the solidity abi from sol source files but this would be the first important tool that would be managed outside the go toolchain (e.g. go modules).

I prototyped an example of how the solidity compiler might be wrapped up with the go tooling ecosystem to provide a convenient and reproducible means of relying on a particular version of the solc compiler.

**Comment by tmc** [comment]
Here's a prototype of making solc work with the go ecosystem: https://github.com/ethereum/solidity/compare/develop...tmc:tmc-add-go-get-support

**Comment by tmc** [comment]
Perhaps it would be most appropriate to have this type of integration/interface over in the go-ethereum project. From a maintenance perspective, given that the release engineering steps are carried out between this and the solc-bin repositories, having something closer to these repos may make the most sense.

**Comment by chriseth** [comment]
I'm sorry, but we consider this out of scope. It is true that go-ethereum is written in go, but I don't think this justifies providing a wrapper as part of our core repository.
