### ISSUE TITLE
published binaries should be signed and have published checksums available

### ISSUE THREAD

**Issue by tmc** [ethereum/solidity#11347]
Currently, it appears as though the solc binaries that are published neither have checksums released alongside them nor are they signed. Both of these techniques help build confidence that released artifacts have not been compromised or otherwise tampered with.

**Comment by axic** [comment]
I think your impression is based on the Github releases page. The release notes on Github used to contain the SHA2-256 hashes of the binaries, but it seems we may have omitted them for some reason lately -- not that the Github release page has any strong defences.

We actually recognised that we may not have been explaining this well enough, but the hashes of every single build (for any of the platforms) is part of the official release repository: https://github.com/ethereum/solc-bin. While the repository has had the hashes for several years ([1](https://github.com/ethereum/solc-bin/pull/15): keccak256 starting Dec 2016, and [2](https://github.com/ethereum/solc-bin/pull/82): sha256 starting February this year), we actually starting writing a blog post last week explaining it.

And for proper authentication, please see #628.

**Comment by axic** [comment]
Also please note that the preferred source of binaries is binaries.soliditylang.org / solc-bin.ethereum.org (see the README in solc-bin), which will be explained in the blog post.

@chriseth Perhaps we could consider removing their uploads from the release page and adding direct links (in the release text) to the correct path within binaries.soliditylang.org?

There's also #2238 we haven't touched for a while.

**Comment by tmc** [comment]
Ah yes, I had missed the solc-bin repository that appears to contain historical releases.
