### ISSUE TITLE
[FunctionCallGraph] Stack use-after-scope reported by Address sanitizer

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11343]
Likely introduced by 

See https://github.com/ethereum/solidity/pull/10973#discussion_r580926054 and https://github.com/google/oss-fuzz/pull/5701/checks?check_run_id=2492467934#step:8:21763

The fuzzer build is failing due to this.

**Comment by cameel** [comment]
I've been meaning to get back to this one when I have a bit more time to dig deeper. I thought this was low priority but if it's actually a fuzz blocker then my suggestion would be just to create a local and use it instead of a temporary in `valueOrDefault()`.
