### ISSUE TITLE
[Boost] Update upstream server from where boost binaries are fetched

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11342]
[Bintray](https://lists.boost.org/Archives/boost/2021/04/251458.php) that used to host boost binaries has shut down. Boost binaries are now hosted at: https://boostorg.jfrog.io/artifactory/main/release/

This issue tracks support for updating the relevant links in the Solidity repo.

**Comment by cameel** [comment]
This was actually fixed by #11370.
