### ISSUE TITLE
ICE: Throw in function virtual bool solidity::frontend::TypeChecker::visit(const solidity::frontend::VariableDeclaration &)

### ISSUE THREAD

**Issue by chengniansun** [ethereum/solidity#11356]
## Environment

- Compiler version: Version: 0.8.5-develop.2021.5.7+commit.518629a8.Linux.clang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux 5.4.0-66-generic x86_64 GNU/Linux

#### Test program: small.sol
```solidity
abstract contract A {
constructor ( mapping ( uint => uint ) [ ] storage ) { }
}
```
#### Compiler Command
```bash
solc-trunk-asan_ubsan  small.sol
```
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/analysis/TypeChecker.cpp(595): Throw in function virtual bool solidity::frontend::TypeChecker::visit(const solidity::frontend::VariableDeclaration &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

**Comment by chriseth** [comment]
Probably related to https://github.com/ethereum/solidity/issues/11353

**Comment by chriseth** [comment]
Although in contrast to #11353, this code should compile, because the contract is abstract.

**Comment by chengniansun** [comment]
An irrelevant question here, I have found several programs trigging the following ICE. Is it a bug, and should I report it? 

Thanks.

```
Internal compiler error during compilation:

/solidity/libsolidity/analysis/TypeChecker.cpp(797): Throw in function auto solidity::frontend::TypeChecker::visit(const solidity::frontend::InlineAssembly &)::(anonymous class)::operator()(const yul::Identifier &, yul::IdentifierContext, bool) const

Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>

std::exception::what: FixedPointType not implemented.

[solidity::util::tag_comment*] = FixedPointType not implemented.
```

**Comment by chriseth** [comment]
Fixed point types are not finished yet, so please do not open an issue, we are still working on it.
