### ISSUE TITLE
calldata is said to be non-modifiable in docs, but inside function it is editable.

### ISSUE THREAD

**Issue by remedcu** [ethereum/solidity#11354]
## Description

According to documentation:

> Calldata is a non-modifiable, non-persistent area where function arguments are stored, and behaves mostly like memory.

Source: https://docs.soliditylang.org/en/v0.5.17/types.html?highlight=Calldata#data-location

## Environment

- Compiler version: 0.5.17 & 0.8.1 (Tested on both these versions)
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: 
- Operating system: MacOS

## Steps to Reproduce

Code I used to check the same:

```
pragma solidity 0.8.1;

contract Test {
    event checkValue(uint256 value, uint256 amount);
    
    function testFunc(uint256 amount) public {
        uint256 value = amount;
        amount = 10;
        emit checkValue(value, amount);
    }
}
```

Input Value: testFunc(50)

Log: `"event": "checkValue", "args": { "0": "50", "1": "10", "value": "50", "amount": "10" }`

As you can see, the call data was 50, which can be seen in `value`, while the actual calldata `amount` was modifiable.

**Comment by chriseth** [comment]
Your code makes no mention of calldata. Please do not confuse the low-level EVM concept of call data and the more abstract notion of function call arguments. `uint256` is a [value type](https://docs.soliditylang.org/en/v0.8.4/types.html#integers) and thus stored on the stack, which is modifiable.
