### ISSUE TITLE
Docs: NatSpec and/or style guide should specify how multi-line NatSpec works

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#11359]
Regarding: https://docs.soliditylang.org/en/v0.8.4/natspec-format.html

Many people choose to limit source code line lengths to 79 characters wrap (or some other number). This is an identified best practice in the Solidity Style Guide. And comments can (SHOULD!) be more than just several characters. So...

Let's specify how longer comments should work:

```solidity
//------10--------20--------30--------40--------50--------60--------70--------80

// Is this preferred❓ (align to tags)

/// @notice You can use this to instantiate a complete circus, including some
///         animals that dance, sing and jump.
/// @dev    Animals are instantiated only once each
contract Circus {
}

// Or this❓ (align to tags and params)

/// @notice You can use this to instantiate a complete circus, including some
///         animals that dance, sing and jump.
/// @dev    Animals are instantiated only once each
/// @param  a       the amount of stuff
/// @param  tokenID which token to operate on
function doThing(uint256 a, uint tokenID b) {
}

// Or this❓ (no indent)

/// @notice You can use this to instantiate a complete circus, including some
/// animals that dance, sing and jump.
/// @dev Animals are instantiated only once each
contract Circus {
}

// Or this❓ (indent to tag-end column)

/// @notice You can use this to instantiate a complete circus, including some
///         animals that dance, sing and jump.
/// @dev Animals are instantiated only once each
contract Circus {
}

// Or this❓ (four-space indent)

/// @notice You can use this to instantiate a complete circus, including some
///     animals that dance, sing and jump.
/// @dev Animals are instantiated only once each
contract Circus {
}

// Or this❓ (repeat tag name) (⚠️ this may be ambiguous for @return and others)

/// @notice You can use this to instantiate a complete circus, including some
/// @notice animals that dance, sing and jump.
/// @dev Animals are instantiated only once each
contract Circus {
}
```

# References

- For source code, four-space indenting [is preferred](https://docs.soliditylang.org/en/v0.8.4/style-guide.html?highlight=natspec).

# Discussion

- Align-to-tags should be most familiar to people with experience using Doxygen on various platforms.
- Align-to-tags indentation also has utility in lining up your `@param`s.
- We should specify that any extra indentation spaces will be surpassed from the JSON output.

# Recommended work plan:

- [ ] Choose our preferred style (recommend align-to-tags-and-params).
- [ ] Update all examples in Solidity documentation to use that style.
- [ ] Decide if this should be a public recommendation
  - E.g. the `///` format is listed before `/**` in the NatSpec, and all examples use `///`, not `/**`, but we do NOT publicly recommend `///` over `/**`.
- [ ] If there is indentation, show in the JSON output how it is truncated. And specify in text how whitespace is truncated in natspec-format.rst.
  - I.e. "/// @notice Hello\n///      world" is "Hello world", not "Hello      world" or "Hello\nworld".

**Comment by 404-P4rziv4L** [comment]
Hey @cameel, I would like to work on this issue if it isn't resolved yet. Could I be assigned?

**Comment by cameel** [comment]
Sure, just be aware that this is a task that requires some discusion and making a decision on which style we should recommend (and if we should recommend a single style  at all). I think that submitting a draft PR with a particular proposal is a good way to get that discussion started though so you can go ahead if you want to try. Just be prepared that there might be some going back and forth in the PR before we agree on a final version :)

I'd suggest to start with just describing the style and only updating all the examples when it's clear which style we want (though updating one or two examples might also be a good way to show off the style you choose).

It would also be good to check if there's one clearly preferred style used in contracts found in the wild. Or what existing linters already recommend - I see that for example solhint does not lint natspec yet and there's a very recent feature request from @fulldecent to add support for it: https://github.com/protofire/solhint/issues/298.

**Comment by fulldecent** [comment]
Thank you for your interest.

Also want to note my main interest in this issue. Overall my goal is that all Solidity functions should be commented, consistently (no dog shedding), by default, and complained loudly when missing, and have consistent/specified interpretation. And when that happens we might hope that a browser-based web3 wallet will make this information available to you every time you sign something.

**Comment by AndriianChestnykh** [comment]
@fulldecent, is there any progress on the task or it is deprecated now?

**Comment by jtakalai** [comment]
I think it's not just "style guide" thing; also the compiler should generate correct multi-line spec with the suggested multi-lining!

**Comment by hcheng826** [comment]
is there any best practices recommendation for this case?

**Comment by fulldecent** [comment]
My personal recommendation is still align with tags and params. 

But can't say this is universally recognized.
