### ISSUE TITLE
ICE due to `calldataEncodedSize()` not being implemented for `MappingType`

### ISSUE THREAD

**Issue by chengniansun** [ethereum/solidity#11353]
## Environment

- Compiler version: Version: 0.8.5-develop.2021.5.5+commit.1d1175c2.Linux.clang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux 5.4.0-66-generic x86_64 GNU/Linux

#### Test program: small.sol
```solidity
contract C {
event E ( mapping ( uint => uint ) [ 2 ] ) ;
}
```
#### Compiler Command
```bash
solc-trunk-asan_ubsan  small.sol
```
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/Types.h(228): Throw in function virtual unsigned int solidity::frontend::Type::calldataEncodedSize(bool) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] =
```

**Comment by chengniansun** [comment]
I am new here. Could someone advise what CXX flags I should use so that the `std::exception::what:` will not be empty. 

Thanks.

**Comment by hrkrshnn** [comment]
@chengniansun Thanks for the bug report. The empty `std::exception::what` is expected. An assert (https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.h#L228) fails, because that function is not expected to be called.

**Comment by YiwenDong98** [comment]
We also found something similar. 
#### Code
```solidity
contract C {
	mapping ( string => address ) [ 8_4E1] immutable d;
}
```
#### Environment
- Compiler version: Version: 0.8.4+commit.c7e474f2.Linux.g++
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- OS: docker image ethereum/solc:0.8.4

#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/Types.h(228): Throw in function virtual unsigned int solidity::frontend::Type::calldataEncodedSize(bool) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

**Comment by cameel** [comment]
> ```solidity
> contract C {
> event E ( mapping ( uint => uint ) [ 2 ] ) ;
> }
> ```

This should result in `Error: Type containing a (nested) mapping is not allowed as event parameter type.`

> ```solidity
> contract C {
> 	mapping ( string => address ) [ 8_4E1] immutable d;
> }
> ```

And this should be `Error: Immutable variables cannot have a non-value type.`

Both cases are disallowed for different reasons but both seem to trigger the same error. The problem is that `MappingType` does not override `calldataEncodedSize()` apparently with the assumption that it's never needed. That turns out not to be the case.

This is slightly related to #8382, though it's not the same problem.

**Comment by chriseth** [comment]
I think whenever you call `calldataEncodedSize` on mapping, it should be an error, because the concept does not exist. When this assertion is triggered, it means a non-fatal error should be turned into a fatal error or the caller should first check if the type is valid in calldata.
