### ISSUE TITLE
Undefined behavior for blockhash

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#11364]
The documentation https://docs.soliditylang.org/en/v0.8.4/units-and-global-variables.html?highlight=block.number#block-and-transaction-properties states:

> blockhash(uint blockNumber) returns (bytes32): hash of the given block - only works for 256 most recent, excluding current, blocks

Here, "only works" is undefined behavior. Please specify if this will return zero (like the Yellow Paper says for the corresponding `BLOCKHASH` opcode, or if it will throw, or if it my toaster will grow arms and slap me.

**Comment by hrkrshnn** [comment]
@fulldecent Thanks for noticing this. Your proposal sounds good. Would you like to submit a PR?

**Comment by fulldecent** [comment]
Yes, thank you for the invitation.

---

First, I'd like to verify the current actual behavior.

Test case:

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

contract Blockhash {
    event GotHash(bytes32 hash);
    function do_blockhash(uint256 blockNum) external {
        emit GotHash(blockhash(blockNum));
    }
}
```

Deployed to Ropsten at: https://ropsten.etherscan.io/address/0x02678f4d10e24c58a583c6d55b4a33b10ff3dfee#code

Then I have run it with an input of 888. And Ropsten has more than 888+256 blocks already.

Transaction: https://ropsten.etherscan.io/tx/0x88ddbfe096bd161198f1065c7c1d1466d0c9bb0a2ebddc099291a3890e6e0827

Result:

The outcome is that with an input earlier than 256 blocks ago, `blockhash(x)` did not throw, and it simply returned zero.

---

PR: https://github.com/ethereum/solidity/pull/11376
