### ISSUE TITLE
Unused parameter warning is unnecessary when the parameter is used in a virtual function's NatSpec

### ISSUE THREAD

**Issue by aybehrouz** [ethereum/solidity#11362]
When a function parameter is not used, Solidity compiler gives a warning. This warning can be suppressed by removing the variable name, but if this variable is used in the function's NatSpec, that will produce an Error:
```
DocstringParsingError: Documented parameter "token" not found in the parameter list of the function.
```
For a virtual function which is supposed to be overridden its quite normal to have unused parameters which is also included in the NatSpec documentation.

**Comment by chriseth** [comment]
Thanks for submitting this issue! Can you please provide example code to clarify any misunderstandings? For example, do you think it is makes a difference if the virtual function has a body or not?

**Comment by aybehrouz** [comment]
This is the code:
https://github.com/aybehrouz/ADAGs/blob/main/contracts/utils/Administered.sol
It's a utility contract which is used for adding the ability to recover trapped tokens in a contract. The default implementation for `canControl` function is retruning `false` which does not use the function's parameter.

At the end, I used an empty  ` `` ` to prevent the NatSpec related error. But the NatSpec description looks a bit awkward now.

**Comment by chriseth** [comment]
This is a tricky problem, since we do want the warning if the parameter is just used via natspec but not in the code.
Maybe adding code that does `address(_contract);` can be used to disable the warning?

**Comment by aybehrouz** [comment]
something like this?
```solidity
    function canControl(IERC20 _contract) public view virtual returns (bool) {
        address(_contract);
        return false;
    }
```

**Comment by aybehrouz** [comment]
I should add that the current source code does not produce any errors or warnings. I think the empty ` `` ` is a better work around maybe.

**Comment by frangio** [comment]
> we do want the warning if the parameter is just used via natspec but not in the code

Why is this?

Here's a real world example:

```solidity
/**
 * @param token The token to be flash loaned.
 */
function _flashFeeReceiver(address token) internal view virtual returns (address) {
    return address(0);
}
```

We're forced to introduce a statement like `token;` in the function body to silence the warning. Removing the variable name is not an option because then you can't provide NatSpec for it.

If the function is virtual I think the warning should be silenced, particularly if there is an `@param` for it, because the workaround is hacky and requires a comment explaining why it's there.

**Comment by bmarcot** [comment]
For the record you can suppress both compiler and natspec warnings with `{...}` in the natpec `@param` line:

```
    /**
     * @notice ...
     * @param {_from} The address from which tokens are being transferred.
     * @param _to The address to which tokens are being transferred.
     * @param {_amount} The amount of tokens being transferred.
     */
    function _beforeTokenTransfer(address, address _to, uint256) internal view override {
        if (SANCTIONS_LIST.isSanctioned(_to)) revert SanctionedAddress();
    }
```

**Comment by steven2308** [comment]
> For the record you can suppress both compiler and natspec warnings with `{...}` in the natpec `@param` line:
> 
> ```
>     /**
>      * @notice ...
>      * @param {_from} The address from which tokens are being transferred.
>      * @param _to The address to which tokens are being transferred.
>      * @param {_amount} The amount of tokens being transferred.
>      */
>     function _beforeTokenTransfer(address, address _to, uint256) internal view override {
>         if (SANCTIONS_LIST.isSanctioned(_to)) revert SanctionedAddress();
>     }
> ```

This effectively solves the warning, but `dodoc`  won't recognize the name of the parameter anymore :disappointed:
