### ISSUE TITLE
I request for basic operations with decimal numbers

### ISSUE THREAD

**Issue by JTorresConsulta** [ethereum/solidity#11379]
Hi! I am an advocate for ethereum but some of my projects with Solidity are abandoned because I can't do basic operations with decimals.
I need it to move forward and I would love to be able to launch my projects on the Ethereum network and not on others that allow programming smart contracts that handle decimals.

When do you plan to implement it?

Thank you for the support and the great job.

**Comment by axic** [comment]
You can track the progress in #409. In lieu of language support, you can also use some of the existing fixed-point libraries, many of them are listed in this [forum post](https://forum.openzeppelin.com/t/designing-fixed-point-math-in-openzeppelin-contracts/2499).
