### ISSUE TITLE
Add selector for custom errors in compiler output

### ISSUE THREAD

**Issue by fvictorio** [ethereum/solidity#11387]
## Abstract

Add the selector of a custom error to the `sources.contract.ast` entry of the compiler output, similar to how functions have a `functionSelector` property.

## Motivation

To detect which custom error was thrown, you need to inspect the return data of a revert and check the first four bytes to see which signature they match. If a tool wants to use the compiler output to detect this automatically (like Hardhat does), right now you'll need to manually build the signature and hash it. For simple types this is not that hard, but if the signature includes nested data with arrays and or structs, things get way harder. 

## Specification

I'm not sure about this part. I guess `errorSelector` would work, analog to the `functionSelector` one. I also wonder if it would make sense to have an `errorIdentifiers` entry, similar to the current `methodIdentifiers`.

Also, and maybe unrelated to this issue: the same thing happens with events. Since as far as I know custom errors are somewhat modeled after events, maybe it would make sense to include them as part of this change. We don't need that right now, but I think they should be in the output too. (If that would make more sense as a separate issue, please let me know and I'll submit it).

## Backwards Compatibility

I think adding a new property in the compiler output is backwards compatible.

**Comment by chriseth** [comment]
Notes for implementation: For functions, the `functionSelector` property is added in `bool ASTJsonConverter::visit(FunctionDefinition const& _node)`. For ErrorDefinition, you can get the selector through `_node.functionType(true)->externalIdentifierHex()`

and I agree that it would be good to also have this for events.
