### ISSUE TITLE
getting multiple return values / returning structs in external functions

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#114]
We need it to detect VM failures when we also need to return 0. The original solution is to `function get() returns (bytes32 value, bool ok)`. The workaround is to make a type like: `struct nullable_word { bytes32 word, bool ok }`. Except now there's a separate issue preventing the use of structs in external functions which blocked that option too

High priority?

**Comment by chriseth** [comment]
The story does have high priority, and the simplest use case which is hopefully sufficient for your needs will probably be implemented in the next days.

**Comment by chriseth** [comment]
First usable implementation just got merged: https://chriseth.github.io/browser-solidity?gist=2fcff0db6e8843107a9b

**Comment by nmushegian** [comment]
Woohoo!

**Comment by lsseckman** [comment]
Hey the link from above is no longer working, is there an updated reference?

**Comment by chriseth** [comment]
https://solidity.readthedocs.org/en/latest/control-structures.html#destructuring-assignments-and-returning-multiple-values

**Comment by lsseckman** [comment]
thank you!

**Comment by rjl493456442** [comment]
Is there anyway i can return a struct from an external function?
If can't, it can be really troublesome. which means i need to return each value in struct and reassemble in the caller function.

**Comment by Moejoe90** [comment]
I think currently you still have to return every element of a structure as a separate variable and reassemble again
