### ISSUE TITLE
Provide variable annotation to receive outside information whenever variable is accessed

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1140]
This is a very vague idea, but its essence is to allow outside actors to provide additional information to be used together when storing / accessing a variable. This information is usually hard to compute on chain but easy to verify (array index to insert at, encrypted value, ...).

**Comment by axic** [comment]
@chriseth can you expand on this a bit?

**Comment by chriseth** [comment]
I think this is too vague. It was related to witnesses etc, i.e. finding an element in a sorted array.
