### ISSUE TITLE
[SMTChecker] SMT logic error in solidity::smtutil::Expression solidity::smtutil::operator==(solidity::smtutil::Expression, solidity::smtutil::Expression)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#11404]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function fromSlice(bytes calldata c) external returns (bytes32) {
        return bytes32(c[0:33]);
    }
}
```

produces:

```
SMT logic error during analysis:
/solidity/libsmtutil/SolverInterface.h(262): Throw in function solidity::smtutil::Expression solidity::smtutil::operator==(solidity::smtutil::Expression, solidity::smtutil::Expression)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Trying to create an 'equal' expression with different sorts
[solidity::util::tag_comment*] = Trying to create an 'equal' expression with different sorts
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

This is quite similar to #11389 but with a different failure symptom for the different size for some reason.

## Environment

- Compiler version:  0.8.5-develop.2021.5.17+commit.21af5408.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by leonardoalt** [comment]
Thanks @agroce !

Just an fyi, we are in the process of deprecating `pragma experimental SMTChecker;`. It will still work before 0.9.0, but will be removed then. The new way to activate the SMTChecker is via the CLI option `--model-checker-engine {all,bmc,chc}` or the JSON option `settings.modelChecker.engine={all,bmc,chc}`.

**Comment by agroce** [comment]
@leonardoalt any chance solfuzzer will try it by default?

**Comment by agroce** [comment]
(presumably without the backend, since actually running z3 would slow down fuzzing throughput too much, I'm guessing, and mostly be z3 errors, not solc errors)

**Comment by leonardoalt** [comment]
@agroce try the pragma by default? I think @bshastry did some work replacing the pragma by the compiler option, but I'm not sure now

**Comment by agroce** [comment]
I was thinking have solfuzzer run the input under various --model-checker-engine options, at least the front end.  it's a bug-rich environment, and without any back-end, I would imagine the cost wouldn't be too bad

**Comment by agroce** [comment]
if solfuzzer is already doing this, I should redo my setup, since I'm producing pragma'd versions of the test corpus as an initial stage

**Comment by agroce** [comment]
(actually, I guess it can't be:  there are test inputs that I include in the corpus that I know fail if you add pragma SMTChecker)

**Comment by leonardoalt** [comment]
@agroce sorry, I don't think I fully got what you meant.

> (actually, I guess it can't be: there are test inputs that I include in the corpus that I know fail if you add pragma SMTChecker)

The pragma still works for now, so it's fine to keep including it until 0.9.0.

I'm not sure whether solfuzzer is currently using the pragma or compiler option.

**Comment by agroce** [comment]
I'm pretty sure the pragma right now.
