### ISSUE TITLE
Improve error message for missing data location in `catch Error(string reason)`

### ISSUE THREAD

**Issue by fvictorio** [ethereum/solidity#11405]
## Abstract

The solidity compiler should show a better error for the `catch Error(string reason)` fragment.

## Motivation

If you compile this code:

```solidity
contract Foo {
  function test() public {
    try this.f() {}
    catch Error(string reason) {}
  }

  function f() public {
  }
}
```

the error message is:

```
TypeError: Data location must be "storage" or "memory" for parameter in function, but none was given.
 --> contracts/Greeter.sol:7:17:
  |
7 |     catch Error(string reason) {}
  |                 ^^^^^^^^^^^^^
```

This is misleading since in this case only `memory` is a valid data location. I guess this is happening due to some code reuse, but since this is a special syntactic construct, it should be possible to detect it and give a better error message, shouldn't it?

## Specification

I don't know which exact message would work here. I guess something like: `Data location must be "memory" for this catch clause, but none was given.`

## Backwards Compatibility

100%?

**Comment by hrkrshnn** [comment]
It seems like this is just a bug:

Removing the following line should fix it.

https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/AST.cpp#L700

**Comment by chriseth** [comment]
Looks like the right fix, please create a PR, @hrkrshnn
