### ISSUE TITLE
Allow specifying parameter name in public mappings

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#11407]
## Abstract

```solidity
contract Temp {
    mapping(address => uint256) public balanceOf;
}

// the above code produces the following ABI
[
  {
    inputs: [
      {
        internalType: 'address',
        name: '', // this is empty
        type: 'address',
      },
    ],
    name: 'balanceOf',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
```

Since there is no param name, tools like typechain by default fill the param as `arg${i}`

```ts
// typescript
// an example of typing generated by typechain ethers v5 target
balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
```

I understand it's not a big deal, but it'd be great to have a relevant param name like `userAddress` instead of `arg0` here. In cases where there are nested mappings (multiple inputs), parameter names can show up when hovered on the method, it can quickly help to understand which parameter is what.

```solidity
// solidity
mapping(address => mapping(address => uint256)) public allowance;

// typescript
// generated typing
allowance(arg0: string, arg1: string, overrides?: CallOverrides): Promise<BigNumber>;

// would be great to instead have
allowance(spender: string, owner: string, overrides?: CallOverrides): Promise<BigNumber>;
// edit: I just noticed I wrote the above order incorrectly xD
```

## Motivation

If solidity allows to somehow specify parameter names, through some syntax. For e.g.:

```solidity
mapping(address userAddress => uint256) public balanceOf;

// can also specify name for output
mapping(address userAddress => uint256 balance) public balanceOf;
```

This syntax is very similar to other elements in solidity that take input parameters:

```solidity
event Transfer(address, address, uint256);
function balanceOf(address) external view returns (uint256);

// with parameter names
event Transfer(address from, address to, uint256 value);
function balanceOf(address userAddress) external view returns (uint256 balance);
```

## Specification

In a mapping declaration, if there is a word between a data type and `=>` or `)`, then use that word as a name for that type.

## Backwards Compatibility

There is no backward compatibility as existing code will function the same. And adding parameters should not change bytecode as well, since it only fills the respective `name` parameters in the ABI.

**Comment by axic** [comment]
It actually involves a bit more than that. The ABI of the generated accessors (in case the `public` visibility) should also keep the name.

Would that cause any issue to tools, or only improvement?

e.g.
```solidity
mapping (address => uint256) public balances;
```
generates
```json
[
  {
    "type": "function"
    "name": "balances",
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
  }
]
```

The `name` fields there would also be filled out.

**Comment by axic** [comment]
I think this is a good idea and do not see any syntactical issue yet.

However, I wonder regarding strictness:
1) Allow no names (backwards compatibility)
2) Allow names in any location and assume empty name where unspecified
3) If a name is present at one location, require if for all entires

I guess we want to have 1) the very least in the short term, but since we allow unnamed parameters in functions, I do not see any reason to disallow it here. Likewise based on the function example 3) seems to be not in line with that.

**Comment by cameel** [comment]
Just a note to anyone implementing this in the future: remember about shadowing (#9231).

**Comment by hrkrshnn** [comment]
@zemse We just discussed this in the call. We think it's reasonable, do you want to start with an implementation?
