### ISSUE TITLE
[Sol->Yul] Reverts due to underflow because of evaluation order

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11414]
```
contract C {
  function f() external returns (bool) {
    uint zero;
    return zero-- != zero++;
  }
}
// ====
// compileViaYul: also
// ----
// f() -> true
```

This test fails via Yul because of a change in evaluation order, the post decrement is evaluated first by the new code generator and because this results in an underflow/wraparound, the call reverts. The old code generator (due to eval being the other way round) does not revert and successfully executes through as expected.

I suppose this is another way of exposing different evaluation orders between the old and new code generators, but filed this issue so more people can comment.

**Comment by bshastry** [comment]
The way to make the divergence between old and new code gens go away would be wrapping the return statement in an unchecked block so the underflow would not revert

```
contract C {
  function f() external returns (bool) {
    uint zero;
    unchecked { return zero-- != zero++; }
  }
}
// ====
// compileViaYul: also
// ----
// f() -> true
```

**Comment by chriseth** [comment]
The evaluation order inside expression is documented to be unspecified for the old code generator and it is documented that there can be differences between the old and the new code generator. In my opinion, it is also very bad coding practice to rely on the evaluation order. In my opinion, this issue can just be closed, I don't think we can or should do anything about it, unless you have an idea.

**Comment by bshastry** [comment]
Yes, this is documented behavior. I created this issue because I didn't expect code that runs on one code gen to revert on another. I had assumed that such behavior is indicative of a bug but clearly other things can cause it as well. I am fine with closing this issue.

At the moment, I am thinking how to filter out false positives like this generated by the fuzzer. I don't have a solution yet.

**Comment by bshastry** [comment]
Closing issue since the consensus is on finding a way to filter out bug reports that are due to difference in evaluation order between old and new code gens.
