### ISSUE TITLE
[Docs] Implement code examples to be opened/importable in Remix 

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#11415]
It would be nice to be able to directly open the code examples in the Solidity documentation in Remix (e.g. by clicking "open in Remix").

We need to find out how that would be possible in Remix.

**Comment by cameel** [comment]
We already have a script that extracts all the snippets from the docs and I see that Remix can load files from various sources (gists, github repos, IPFS, Swarm) so we would just have to create a CI job that uploads the extracted snippets somewhere on new release.

Then the problem is how to link to them directly. Looks like you can tell Remix to load a specific gist, e.g. https://remix.ethereum.org/#gist=1b737742a93f9035baefc074ac2979ca. Not sure about github, IPFS or other options.

Unfortunately you have to click the file on the list to see it - it shows the start page by default. [There are some URL parameters for hiding panels](https://remix-ide.readthedocs.io/en/latest/locations.html) but I don't see anything that would make it switch to the editor immediately.

**Comment by cameel** [comment]
We would also need something to automatically insert links to individual snippets next to them in the docs. I did a quick search but I could not find any tool that would do it for us out of the box. I'm afraid we might have to create a custom Sphinx plugin to do that. I found one that might serve as a base: [sphinxawesome-codelinter](https://github.com/kai687/sphinxawesome-codelinter). It's a linter that finds and processes all the code snippets. We would need to modify it to not only traverse the doctree but also insert the generated links.

**Comment by franzihei** [comment]
Just talked to Yann about this. He said the easiest way would be to write a script to do the following:
1. Take the Solidity code
2. Encode it (https://www.base64encode.org/)
3. Go to ``remix.ethereum.org/?code=[encoded code here]``

We could probably write some automation to do this, or?

**Comment by franzihei** [comment]
> Unfortunately you have to click the file on the list to see it - it shows the start page by default.

This is solved with the encoded code option, where you land directly in the editor, e.g. see: https://remix.ethereum.org/?code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IEdQTC0zLjAKcHJhZ21hIHNvbGlkaXR5ID49MC40LjE2IDwwLjkuMDsKCmNvbnRyYWN0IFNpbXBsZVN0b3JhZ2UgewogICAgdWludCBzdG9yZWREYXRhOwoKICAgIGZ1bmN0aW9uIHNldCh1aW50IHgpIHB1YmxpYyB7CiAgICAgICAgc3RvcmVkRGF0YSA9IHg7CiAgICB9CgogICAgZnVuY3Rpb24gZ2V0KCkgcHVibGljIHZpZXcgcmV0dXJucyAodWludCkgewogICAgICAgIHJldHVybiBzdG9yZWREYXRhOwogICAgfQp9

**Comment by cameel** [comment]
> 3. Go to `remix.ethereum.org/?code=[encoded code here]`

Oh, I did not know it can do that. This seems to be an undocumented query parameter. I originally wanted to suggest something like that (e.g. https://godbolt.org has something similar for C++) but I thought this feature does not exist in Remix. If it does then great.

**Comment by chriseth** [comment]
Oh nice! New we only need to find out how to add the appropriate buttons / links to the documentation.

**Comment by cameel** [comment]
@hrkrshnn's suggestion from https://github.com/ethereum/solidity/pull/11605#issuecomment-872404437 might be useful for finding these snippets:

> Was wondering if there was a sphinx extension that could help here. Found https://www.enricozini.org/blog/2020/python/checking-sphinx-code-blocks/

We still need a way to append to them though. In the worst case we can just rewrite the .rst files but would be better if it could be done via the Sphinx API.

**Comment by cameel** [comment]
I found an extension that adds "copy" buttons to all code snippets: [sphinx_copybutton](https://github.com/choldgraf/sphinx-copybutton). That's very close to what we need here (just replace the button with a link) and the implementation is very short (see [`__init__.py`](https://github.com/choldgraf/sphinx-copybutton/blob/master/sphinx_copybutton/__init__.py)) so it should be pretty easy to make a a custom extension based on it. I just implemented one in #11666 so I can try to do this one too at some point.

**Comment by cameel** [comment]
Note from @chriseth:
> when you do that, please check that the pdf and epub rendering still works

**Comment by cameel** [comment]
@franzihei 
> Just talked to Yann about this. He said the easiest way would be to write a script to do the following:
> 
> 1. Take the Solidity code
> 2. Encode it (https://www.base64encode.org/)
> 3. Go to `remix.ethereum.org/?code=[encoded code here]`

Do you know if there's a way to do that for Yul snippets? I see in the URLs that there are parameters for optimizer settings, version, evm, etc. but I don't see one for language (even though you can set it to Yul in the compiler sidebar). I tried `lang=yul` and `language=yul` but no luck. Adding links for Yul snippets in #11697 would be very easy so if Remix supports that, it would be nice to have it too.

Tagging @yann300. Maybe we can get an answer from him directly?

**Comment by yann300** [comment]
I think there's no url parameters for lang, can you create an issue in the remix-project repo?
Thanks

**Comment by cameel** [comment]
@yann300 Sure! I've been off last week but now I have created an issue for this and also for two more things that would be useful here:
- https://github.com/ethereum/remix-project/issues/1489
- https://github.com/ethereum/remix-project/issues/1490
- https://github.com/ethereum/remix-project/issues/1491

**Comment by hrkrshnn** [comment]
OpenZeppelin seems to have already implemented an "open in remix" button.

https://wizard.openzeppelin.com/

**Comment by cameel** [comment]
So looks like they do not care about the recommended URL length limit of 2000 bytes. The longest link I managed to create using that wizard has 4830 chars.

@axic Should we relax the limit in https://github.com/ethereum/solidity/pull/11697#discussion_r676836714 too?

**Comment by yann300** [comment]
@cameel 
you can also specify an `url` parameter in the URL which point to any kind of url (raw, github, ipfs,...) or a gistid ( but I think that you already know)

**Comment by cameel** [comment]
@yann300 Thanks! I actually didn't know that. This does not seem to be documented in [Remix URLs & Links with Parameters](https://remix-ide.readthedocs.io/en/latest/locations.html). I only see the `gist` parameter there.

But anyway, I'd still be in favor of just using a higher limit. Having to deploy code snippets somewhere when docs are built would complicate docs build process. All of our code examples currently fit under 8000 chars which is still something most browsers can deal with. I think going for separately hosted snippets would only be worth it if we really had tons of very long examples.
