### ISSUE TITLE
Optimizer details does not allow `inliner` flag

### ISSUE THREAD

**Issue by dileepfrog** [ethereum/solidity#11418]
## Description

The JSON input [documentation]( https://docs.soliditylang.org/en/v0.8.4/using-the-compiler.html#input-description ) shows a boolean flag `inliner` under `settings.optimizer.details`. However setting this flag causes the error `CompileError: Unknown key "inliner"`. A cursory glance at the code shows that it is indeed not included in the keys [here](https://github.com/ethereum/solidity/blob/9d156b52c465b82df43fb871fd5a80fadce10478/libsolidity/interface/StandardCompiler.cpp#L452) though it does get parsed [here](https://github.com/ethereum/solidity/blob/9d156b52c465b82df43fb871fd5a80fadce10478/libsolidity/interface/StandardCompiler.cpp#L586).

Potentially related to https://github.com/ethereum/solidity/issues/10354 (stripping coverage instrumentation)

## Environment

- Compiler version: 0.8.4
- Target EVM version (as per compiler settings): berlin
- Framework/IDE (e.g. Truffle or Remix): Truffle
- EVM execution environment / backend / blockchain client: Ganache
- Operating system: macOS 10.15.7

**Comment by axic** [comment]
Good catch!
