### ISSUE TITLE
Make use of inline assembly dialect for memory safety

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11417]
**Background**

When the inline assembly statement was created, we reserved a string literal whose purpose it was to specify a dialect for the inline assembly. Currently, only leaving it out or using `"evmasm"` is valid, everything else will lead to an error:

```
assembly "evmasm" { revert(0, 0) }
```

**Problem that This Issue wants to Solve**

When compiling via yul, we often use more local Yul variables and thus the stack pressure is higher. Because of that, we want to have the ability to move stack variables to memory. The current approach assumes that functions are not recursive and computes the amount of memory slots needed for such variables throughout the full call graph. It then initializes the free memory pointer to a certain (compile-time constant) value to make space for these variables.

If all code properly uses allocations through the free memory pointer, it should not touch the memory areas used by these variables. If code touches that area, it could overwrite a local variable through a memory operation which could lead to weird behaviour.

We can ensure that the Yul code that is generated from Solidity properly uses memory allocations, but we cannot do that for inline assembly. Because of that, moving stack variables to memory is disabled as soon as there is inline assembly.

A common way to violate the memory access restrictions is to use
```
calldatacopy(0, 0, calldatasize())
call(...)
```

There are some uses of such code in inline assembly, but most of the "internal" snippets out in the wild use memory properly.

**How to Solve the Problem**

For some cases, the compiler can detect that for example memory is not used at all or that all writes go to a "safe" location, but this will not work in general.

Because of that, the idea is to use the dialect strict as a claim from the developer to the compiler that memory is properly used in the given snippet, even if the compiler cannot verify this property.

**Backwards Compatibility**

Since we want this to be a deliberate statement, it cannot be the default. We could use `assembly "evmasm" { ... }` to make the claim for "memory-safety", which would have the benefit that such code can also compile for older compiler versions. If we introduce a new string, this will not be valid code for older compilers.

**Comment by chriseth** [comment]
@axic mentioned that there could be other values for the dialect string for other uses.

**Comment by chriseth** [comment]
I'm more and more convinced that due to the fact that this is not backwards-compatible, we cannot use this.

Another option would be to use a natspec annotation:

```
function f() pure {
  /// @memorysafe-assembly
  assembly { mstore(0, 2) }
}
```

**Comment by hrkrshnn** [comment]
Why is backwards compatibility important here?

**Comment by chriseth** [comment]
Because inline assembly is usually used in libraries, which are likely to be used across multiple versions of solidity.

**Comment by maurelian** [comment]
This would only apply to pre
Hmmm.. in a situation where 
I'm a dev, I'm using solidity 0.8.1. 
I'm using an OZ lib written in solidity 0.8.10 with the new feature in it.

**Comment by maurelian** [comment]
I'd like to advocate for something cleaner like `assembly memsafe {}`. Considering that comments have never (AFAIK) impacted on compiler output, it feels like this is optimizing for a tiny corner case at the cost of baking in a pretty ugly bit of syntax.

I see the following scenarios (assuming that this feature is to be added in `0.8.z`, and then gets utilized in [OZ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol) or [Solmate](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC20.sol)[^1])

1. For a codebase in `0.7.x` or earlier, it seems quite unlikely that they would be actively incorporating brand new 3rd party libs (but you will have more context on this than me, maybe I'm wrong).
2. For a codebase in `0.8.x` (where x < z), it should be pretty trivial to upgrade to `0.8.z` right? 

Admittedly this breaks the [semver scheme](https://docs.soliditylang.org/en/latest/installing-solidity.html?highlight=versioning#versioning) you've committed to, so rightfully this feature (with my suggested syntax) would go into `0.9.0`... which then puts the `0.8.x` codebases in the same situation as the `0.7.x` ones above, but at least it keeps things clean.

---

[^1]: Doesn't look like [dappsys](https://github.com/dapphub/dappsys) is being updated actively.

**Comment by ekpyron** [comment]
@maurelian For the record: we did actually implement this with https://github.com/ethereum/solidity/pull/12620 and https://github.com/ethereum/solidity/pull/12663 (not released yet, though).

So what's currently on ``develop`` is the following:

We allow both:
```
/// @solidity memory-safe-assembly
assembly { ... }
```
and
```
assembly ("memory-safe") { ... }
```

with the plan to remove the former either directly in 0.9.0 or the breaking release after.

We're aware that using a comment for this is ugly and it's an extreme effect for a comment, but the decision so far was to accept that to allow faster adoption. But until our next release there would still be time to reconsider this...

**Comment by ekpyron** [comment]
Note that introducing ``assembly ("memory-safe") { ... }`` is non-breaking, so it's fine to add it in 0.8.13.

So the reasoning is rather that the comment is supposed to only be used by libraries that want to be compatible with the full ``0.8`` series...i.e. if a library uses the comment, it can still be used with ``0.8.0``, but using it with ``0.8.13+`` can still benefit from the memory-safety information.

In theory, a library could just use ``assembly ("memory-safe")`` directly and drop support for ``<0.8.13``... but we're afraid there will be hesitance on that - that's why we went for also adding the comment version for now...

**Comment by maurelian** [comment]
> We allow both... with the plan to remove the former either directly in 0.9.0 or the breaking release after.

Ah, OK. That sounds like a reasonable compromise thanks for explaining.

**Comment by ekpyron** [comment]
Ok, then I'm closing this, since it was closed by https://github.com/ethereum/solidity/pull/12620 resp. https://github.com/ethereum/solidity/pull/12663
