### ISSUE TITLE
Detect platform-dependent paths in default file loader (path spec v3)

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11412]
Related to #6608 and https://github.com/nomiclabs/hardhat/issues/538.
Part of a set of issues that replaces #11138.

## Abstract
Currently the default file loader interprets the source unit names it receives as platform-dependent paths. For example on case-insensitive filesystems it resolves file names in a case-insensitive way and on Windows it recognizes backslashes as valid path separators. This may lead to users unwittingly creating contracts that compile only on their platform.

The file loader should prevent this by recognizing and reporting situations that may result in such problems.

## Motivation
Here's an example of an import that will result in completely different files being expected on different platforms if the default file loader is involved:
```solidity
import "C:\\project\\lib\\token.sol"; // source unit name: C:\project\lib\token.sol
```

On Windows `C:` is seen as the root directory and backslashes as directory separators. On Linux it's all just one weird long file name.

## Specification
The default file loader should report a problem when:
- The canonical path of the file to be loaded matches the requested path only in a case-insensitive way.
- The underlying system allows backslashes as directory separators and the requested path contains one or more such slashes.
    - Or, better, when a source unit name contains backslashes at all.
- The requested path does not start with a forward slash but despite this is recognized as an absolute path.
- (Optional) The path contains characters known to be disallowed in paths on some platforms. E.g. `<` or `>` on Windows or `\0` characters on Linux.

If any of these are detected, at least warn the user about consequences. We should also consider disallowing them completely. That's what Hardhat did already: https://github.com/nomiclabs/hardhat/issues/538#issuecomment-843170204.

Note that this should be done at the file loader level. All of these are perfectly fine as long as they're only used in compiler's virtual filesystem. It's only when the actual filesystem is involved that they can cause problems.

## Backwards Compatibility
It's only a warning so it's fully backwards-compatible. Making it an error would make the change backwards-incompatible for any contract that uses such platform-dependent paths.

**Comment by chriseth** [comment]
Maybe we should just disallow `\\` in import statements (or warn about them)?

**Comment by chriseth** [comment]
About the case, I'm not so sure, it could create problems with recompilation on a case-insensitive file system.

**Comment by cameel** [comment]
> About the case, I'm not so sure, it could create problems with recompilation on a case-insensitive file system.

AFAIK the most commonly used case-insensitive filesystems are at least [case-preserving](https://en.wikipedia.org/wiki/Case_preservation). So user would not get this warning just by checking out code in git. He would have to e.g. use one case to name the file and a different case in the import. And then wonder why the code does not compile on Linux.

I think that the biggest argument for this is that frameworks already report this a a problem (e.g. Hardhat reports an error as mentioned in https://github.com/nomiclabs/hardhat/issues/538#issuecomment-843170204) and I can see how this might be good for reducing support requests from confused users.

> Maybe we should just disallow `\\` in import statements (or warn about them)?

That sounds like a good idea. I'll add it to the description.

Not sure whether to disallow or just warn. Personally I'd rather ban all of these but the downside is that the change becomes breaking. Maybe we could discuss it on the call.

**Comment by cameel** [comment]
We decided to put off work on this for now. We want to deal with #11408, #11409 and #11410 first and go back to this once that's done and working.
