### ISSUE TITLE
Violate Style Guide in Example Code 

### ISSUE THREAD

**Issue by tlatkdgus1** [ethereum/solidity#11425]
## Page

[Style Guide](https://docs.soliditylang.org/en/v0.7.4/style-guide.html)

## Abstract
Violate Style Guide in Example Code 
Docs version: under 0.7.5

Docs notice use mixedCasein modifier, but Example code use not mixedCase
   
>  [Function Declaration](https://docs.soliditylang.org/en/v0.7.4/style-guide.html#function-declaration)
```
  function balance(uint from) public view override returns (uint)  {
      return balanceOf[from];
  }
  
  function shutdown() public onlyowner {
      selfdestruct(owner);
  }
```

**Comment by cameel** [comment]
Thanks for reporting! This has already been fixed though: #10169. You're linking to the old docs (0.7.4) from before that change. We do not update documentation for old compiler versions.
