### ISSUE TITLE
[isoltest] Support comments between expectations

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11427]
This would increase readability in bigger tests, such as those in `semanticTests/externalContracts`.

```
// -- Double reserve
// account: 1
// reserve(string), 69 ether: 0x20, 3, "abc" ->
// owner(string): 0x20, 3, "abc" -> 0x1212121212121212121212121212120000000012
// account: 0
// -- Transfer
// setContent(string,bytes32): 0x40, 0, 3, "abc" ->
// transfer(string,address): 0x40, 555, 3, "abc" ->
// owner(string): 0x20, 3, "abc" ->
// content(string): 0x20, 3, "abc" ->
```

The proposed syntax is `-- text`. Note that there is already `# test #` as a syntax which works at some places and not others. It would be fine making that work properly on new lines too.

**Comment by cameel** [comment]
`--` looks good to me. Something like `#` or `##` would look more like a comment but stands out less:

```
// ## Double reserve
// account: 1
// reserve(string), 69 ether: 0x20, 3, "abc" ->
// owner(string): 0x20, 3, "abc" -> 0x1212121212121212121212121212120000000012
// account: 0
// ## Transfer
// setContent(string,bytes32): 0x40, 0, 3, "abc" ->
// transfer(string,address): 0x40, 555, 3, "abc" ->
// owner(string): 0x20, 3, "abc" ->
// content(string): 0x20, 3, "abc" ->
```

Something that would help even more would be ability to add empty lines:
```
// -- Double reserve
// account: 1
// reserve(string), 69 ether: 0x20, 3, "abc" ->
// owner(string): 0x20, 3, "abc" -> 0x1212121212121212121212121212120000000012
// account: 0
//
// -- Transfer
// setContent(string,bytes32): 0x40, 0, 3, "abc" ->
// transfer(string,address): 0x40, 555, 3, "abc" ->
// owner(string): 0x20, 3, "abc" ->
// content(string): 0x20, 3, "abc" ->
```

**Comment by axic** [comment]
Yes, in my example branch (#11426) I used empty lines, but removed them since.

**Comment by cameel** [comment]
Having just reviewed it, I think it would have been easier with those empty lines :)

**Comment by axic** [comment]
My motivation exactly 😅  It is a pain dealing with that currently.

**Comment by dumbledorep** [comment]
Cameel that's a good catch with the empty lines...the empty lines actually helps. It makes it easier and a lot more readable.

**Comment by axic** [comment]
Regarding ease of implementation, I think `// @: "My comment"` could be very easily supported with the hook system by @aarlt, but actual empty lines is a much bigger change in both the parser and printer.
