### ISSUE TITLE
[Yul] Add the ability to escape machine language instructions

### ISSUE THREAD

**Issue by qbzzt** [ethereum/solidity#11430]
## Abstract

It would be very helpful for testing if we could add arbitrary machine language code to a Yul contract. This is important because we need to make sure that even code that is invalid is handled the same by all clients to preserve consensus.

## Motivation

In the tests repository (https://github.com/ethereum/tests) we have to test code that:

1. Contains invalid machine language (to make sure it is properly reverted). Currently we can only use Yul to test invalid machine language with `invalid()`, which translates to `0xFE`. We cannot check that other invalid opcodes are handled the same way unless we use either raw machine language for the contract or LLL.

or

2. Contains new opcodes that aren't implemented yet in Yul, such as `BASEFEE` (https://eips.ethereum.org/EIPS/eip-3198). Currrently to use Yul we need a workaround, for example to call a small contract written in raw machine language that runs the opcode, writes the result to memory, and then returns it.

## Specification

Have a function called `raw` that takes two parameters:

1. The code to execute as a number
2. The expected number of entries pushed into the stack.

Treat it as a function that returns multiple values. For example, this line defines two variables, sets the first one to the base fee and the second one to the priority fee. The variables are filled right to left so left to right will be the order in which they are calculated.

```
let base, tip := raw(0x48483A03, 2)
```

The comments should include an explanation:

| Opcode | Name        | Stack after execution |
| ----------  | -------------  | -----------------------       |
| 0x48      | BASEFEE | [basefee]                    |
| 0x48      | BASEFEE | [basefee, basefee]                    |
| 0x3A      | GASPRICE | [gasprice, basefee basefee] |
| 0x03      | SUB            | [gasprice-basefee, basefee] |

Code with jumps would be a lot harder to add, so it is not worth the effort, IMAO.

## Backwards Compatibility

This would break any Yul code that has a `raw` function. I recommend that if such a function is defined the compiler emit a warning and use the defined function as `raw` to

**Comment by axic** [comment]
This is covered by #10869 and will be in the next release. Only for Yul and not inline assembly. The syntax for basefee would be `verbatim_0i_1o(hex"48")` and you could write a complete code as:
```
{
  let a:= verbatim_0i_1o(hex"48")
  let b:= sub(gasprice(), verbatim_0i_1o(hex"48"))
}
```
or if you wish to encode the entire bytecode:
```
{
  let base, tip := vebratim_0i_2o(hex"48483a03")
}
```

Also `basefee` will be added in #11390, though that is no help in the general case.
