### ISSUE TITLE
Support namehash at compile-time

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11436]
In order to at least somewhat support ENS (we cannot fully support it because that creates issues with source verification), we could have compile-time evaluation of the namehash function on string literals.

```bytse32 node = namehash("abc.def.eth");```

Some pointers:
 - https://twitter.com/nicksdjohnson/status/1397012527511334913
 - https://github.com/danfinlay/eth-ens-namehash/blob/master/index.js
 - https://github.com/ethers-io/ethers.js/blob/master/packages/strings/src.ts/idna.ts

**Comment by axic** [comment]
Duplicate of #6956 ?

**Comment by chriseth** [comment]
Maybe duplicate, but could also be sub-issue.

**Comment by axic** [comment]
Suggestion: implement UTF normalization as a compiler builtin and implement namehash in the standard library.

Pro: This would allow us to gain experience with the standard library.
Con: Unless we actually have compile-time evaluation of pure functions, this would still generate some runtime code (which hopefully would be optimised, i.e. the recent keccak256 optimiser steps).

**Comment by axic** [comment]
The alternative to this is #1650 and have namehash supplied via JSON.
