### ISSUE TITLE
Source map jumps back to function definition after bare block

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#11440]
## Description

This is an issue with source mapping.  Suppose you have a block inside of a function, and this block declares some local variables.  After the block is finished, these variables need to be popped off the stack.  But the way the resulting `POP` instructions get mapped is a little messed-up.

If the block is an `if`, `while`, or `do` block, then these `POP`s get mapped to `if`, `while` or `do` statement that the block is a part of.  This isn't a problem.  However, if the block is simply a bare block, not part of a larger control structure, these `POP`s will be mapped to the function definition node.  This is confusing.

I would suggest that as an alternative, these `POP`s could be mapped to the block node itself.

(Context: I noticed this behavior while investigating [this Truffle issue](https://github.com/trufflesuite/truffle/issues/4055) that resulted from it.  I've fixed the problem with Truffle Debugger, so this should no longer cause problems there, but sourcemapping things this way still seems like a bug so I thought I'd file an issue for it.)

## Environment

- Compiler version: 0.8.4 (but exists as far back as at least 0.5.0...)
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle

## Steps to Reproduce

I'll use code of the sort that was used in reporting the original Truffle issue:

```solidity
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;
contract Example {
  event Something(uint);
  function run(uint x) public {
    {
      uint something = 3;
      emit Something(something);
    }
    emit Something(x);
  }
}
```

**Comment by chriseth** [comment]
It looks like the source location of a bare block is never set... Thanks for reporting!
