### ISSUE TITLE
Allow to share memory array between smart contracts

### ISSUE THREAD

**Issue by lcswillems** [ethereum/solidity#11461]
## Abstract

I have something like this:

```solidity
contract A {
  function exec(address b) {
    uint[] memory values = new uint[](10);
    b.delegatecall(abi.encodeWithSignature("exec(uint256[])", values));
  }
}

contract B {
  function exec(uint[] memory values) {
    // If I modify `values` here, `values` in `A.exec` doesn't change.
  }
}
```

If I modifiy `values` in `B.exec`, it currently doesn't change `values` in `A.exec`. It is because `values` seemed to be copied.

I would not want `values` to be copied and be able to modify `values` in `A.exec` from `B.exec` in order to save gas.

I did a ton of researches and looked at the inline assembly. It doesn't seem to be possible currently.

**Comment by chriseth** [comment]
The EVM disallows such things, it's not something we can change from the language side, so I'm closing this issue. If you want data to be shared like that, you have to use storage.

**Comment by lcswillems** [comment]
And is there a way to do it with Inline Assembly?

**Comment by cameel** [comment]
There isn't. It's a limitation of how contracts are executed by the EVM. You're performing an external call (`DELEGATECALL` in this case), which works more like running a separate process on the computer than calling a function inside the same program. The contracts do not share memory, stack, etc. In case of a `CALL` they don't even share storage, though `DELEGATECALL` is different in that regard. They way they communicate is that one serializes the arguments into an area in its own memory and then the other can see that area of memory as calldata and deserialize input from it, following the ABI rules. Calldata is readonly in EVM so you cannot write anything back to it.

**Comment by lcswillems** [comment]
Thank you @cameel for all these explanations!!
