### ISSUE TITLE
Interacting with contracts that are not instantiated in the blockchain

### ISSUE THREAD

**Issue by vasconx** [ethereum/solidity#11486]
I have a question about how EVM and Solidity work. In this example on the official Solidity website, there are two contracts ( Caller, C ). What happens and I didn't know is that I can host the "Caller" contract and still interact with the "C" contract even though it's not instantiated in the blockchain. Just so I understand, does "Caller" host under the hood the "C" contract with you? Because I'm imagining that if I wanted to create a contract that offered several services I would do it just like that, it's much better than passing instance of related contracts in the blockchain. Or is there something I don't understand?

The source code is in ( Getter Functions - https://docs.soliditylang.org/en/v0.8.4/contracts.html )

```
contract C {
    uint public data = 42;
}

contract Caller {
    C c = new C();
    function f() public view returns (uint) {
        return c.data();
    }
}
```

**Comment by cameel** [comment]
Hello! That's a good question but the bug tracker is not really a good place for questions like this. We could discuss it on the [Solidity forum](https://forum.soliditylang.org/) though so feel free to repost it there :)

**Comment by nastari** [comment]
I'm sorry, i'm delete this!

**Comment by vasconx** [comment]
I'm sorry for this! Just answering my questions, the contract "C" does enter the blockchain, it's just the address I don't return so I don't know it beforehand. It was my confusion. Thanks and sorry! Until!

**Comment by cameel** [comment]
Don't worry, it's closed so it's fine now. The forum is just a much better place to find people interested in having an open-ended discussion about stuff like this and answering questions. The bug tracker is for tracking bug fixes and new language features so we don't want to keep threads open when there's no work to be done :).

As for the question itself - yeah, for `new C` to work your contract has to have a copy of its bytecode included.
