### ISSUE TITLE
NameSimplifier sometimes produces invalid Yul code by leaving a trailing dot at the end of an identifier

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11496]
```
{
  function f() -> u,Q {
    let j, r._ := f()
  }
  {
    let d, g := f()
  }
}
```

throws

https://github.com/ethereum/solidity/blob/7d8a4e63d84f548dbb3409f761fb2e92936c9057/libyul/AsmAnalysis.cpp#L93

To reproduce

```
$ solc --strict-assembly --optimize test.yul
```

**Comment by hrkrshnn** [comment]
Interesting! I think name simplifier simplifies the name `r._` to `r.`. And Yul doesn't allow names to end with dot.

**Comment by hrkrshnn** [comment]
This is the rule causing the issue: https://github.com/ethereum/solidity/blob/develop/libyul/optimiser/NameSimplifier.cpp#L100

Other rules that changes string to empty can also lead to this problem. For example, `r._fromStack` can also lead to this.

Maybe we should reconsider dot as an identifier name in Yul.

**Comment by chriseth** [comment]
Would it be bad if the identifier ended in a dot?

**Comment by hrkrshnn** [comment]
Perhaps, if dot at the end is invalid, then dot anywhere should similarly be invalid. But, generally I'm indifferent about what to do about dots in Yul identifier.

Perhaps @axic has something to say? Context: https://github.com/ethereum/solidity/pull/9306

**Comment by chriseth** [comment]
Actually wait a second - shouldn't `NameDispenser::illegalName` just check that it does not start or end in a dot?

**Comment by chriseth** [comment]
And `yul::isRestrictedIdentifier` should also check for the dot.

**Comment by chriseth** [comment]
Actually it suffices to only change `isRestrictedIdentifier`

**Comment by bshastry** [comment]
Smaller variant

```
{
  function e(_._) {
    e(0)
  }
  e(2)
}
```

**Comment by bshastry** [comment]
Optimization is not required to trigger this ICE, simply 

```
solc --strict-assembly test.yul
```

where test.yul is the test case in the original post
