### ISSUE TITLE
solc-bin: soljson.js should point to the latest release (and not build)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1149]
This applies to `bin/soljson-latest.js` too.

@chriseth any reason to keep it at nightly?

It could also be made more explicit:
- `bin/soljson-latest-nightly.js`
- `bin/soljson-latest-release.js`
- and phasing out `soljson.js` + `bin/soljson-latest.js`

**Comment by chriseth** [comment]
Yep, let's have `latest` point to the latest release and perhaps add `soljson-nightly.js` to point to the latest nightly (I would say `latest-nightly` is overly complicated)

**Comment by axic** [comment]
- `bin/soljson-latest.js` ⇒ latest release
- `bin/soljson-nightly.js` ⇒ latest nightly
- `soljson.js` ⇒ ?

**Comment by chriseth** [comment]
soljson should point to latest release.

**Comment by axic** [comment]
Depends on https://github.com/ethereum/solc-bin/pull/8.
