### ISSUE TITLE
Add `notice` severity to "error messages"

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11508]
Currently the severity is restricted to `warning` and `error`. Most tools treat both of them as errors and this is a frequently discussed topic. It could be nice to have `notice` for messages which do not need to be addressed (but can be).

Suggested use cases:
- SPDX license message
- Contract code size message (#10981)
- Reporting messages from the SMTChecker (for example #10787)

The ranking would be then:
- `notice`: the issue MAY/CAN be addressed
- `warning`: the issue SHOULD be addressed
- `error`: the issue MUST be addressed

**Comment by ekpyron** [comment]
Another example might be ``had to move variables from stack to memory, consider reducing the amount of variables``.

**Comment by axic** [comment]
Alternatively naming this `info` could remove any "negative" connotations?

**Comment by ekpyron** [comment]
Another example (I think originally brought up by @hrkrshnn): ``This state variable is never assigned outside the constructor. Consider making it immutable.``

**Comment by chriseth** [comment]
These are all very good examples!

**Comment by cameel** [comment]
Should `Function state mutability can be restricted to pure` also be a notice? Or the warning about deprecated constructor visibility? Or are they better off as warnings?

**Comment by cameel** [comment]
We discussed #11540 today and the case of assigning external function pointers in the constructor might be another good candidate for a notice:
```
Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
```

Also, we talked a bit about notices in general and one idea I liked was that notice should not necessarily be about severity but about how much confidence we have that it's not a false-positive. We want tools to provide easy way for users to filter out notices so if a certain suggestion has a reasonable chance of being unnecessary, it could be turned into a notice and users could be encouraged to review notices but not assume that valid code never produces them.

**Comment by leonardoalt** [comment]
@yann300 @gnidan @haltman-at @fvictorio summoning you to get some feedback here re tools:
- would this break anything?
- would this be helpful as in users can filter out `notice`s they're not interested in and would hopefully take warnings more seriously?
Thanks!

**Comment by haltman-at** [comment]
As for the first question: Yes, we'd have to make some code changes to handle this.  Our current code does assume there are only warnings and errors.  Shouldn't be anything major though.  You can see the relevant code [here](https://github.com/trufflesuite/truffle/blob/develop/packages/compile-solidity/run.js#L236), if you're curious.

As for the second: No idea, but maybe @gnidan could say something more there.

**Comment by yann300** [comment]
We would have to adapt a bit but not a big deal.
> would this be helpful as in users can filter out notices they're not interested in and would hopefully take warnings more seriously

indeed that'd be helpful for that.

**Comment by fvictorio** [comment]
> would this break anything?

I'm not 100% sure, but I believe this wouldn't break anything on our side. We would have to update some code so that these notices aren't shown in yellow, but it's a small change.

> would this be helpful as in users can filter out `notice`s they're not interested in and would hopefully take warnings more seriously?

Yes, I think this is a good idea. Having "real" warnings mixed with things that can be safely ignored causes users to just ignore all warnings.

cc @alcuadrado

**Comment by alcuadrado** [comment]
I don't think this would break anything in Hardhat, specially since we now print a warning if a user tries to use a version of solc that we haven't tested and integrated yet.

> would this be helpful as in users can filter out notices they're not interested in and would hopefully take warnings more seriously?

How would this look like? Will you have some kind of code name/number per notice?

**Comment by leonardoalt** [comment]
Thanks everyone for the feedback!

@alcuadrado I think pretty much same as warning/error, with a specific code, and the type (if using the JSON interface) would be either {notice, error, warning}.

**Comment by fvictorio** [comment]
> How would this look like? Will you have some kind of code name/number per notice?

There are error codes for each kind of error/warning in the json output, at least in solc 0.8.2 (I'm not sure when were they introduced), so I'm gonna guess notices will have codes too.

**Comment by axic** [comment]
@yann300 @haltman-at @gnidan @alcuadrado @fvictorio would a Solidity emscripten test build which always outputs a `notice` help in easily testing this and getting support out faster?

**Comment by christianparpart** [comment]
> Should `Function state mutability can be restricted to pure` also be a notice? Or the warning about deprecated constructor visibility? Or are they better off as warnings?

reading it like that it feels more like a `hint` than `notice`. `info` is too general. `hint` (or `tip` tbh) sounds like some constructive feedback  by the compiler. :)

**Comment by axic** [comment]
Hm, `hint` may be a good option too for naming. @christianparpart are there any recommended severity levels in LSP?

**Comment by christianparpart** [comment]
> Hm, `hint` may be a good option too for naming. @christianparpart are there any recommended severity levels in LSP?

sorry for the late reply, it's {Error, Warning, Information, Hint}.

**Comment by axic** [comment]
Decision: we'll go `info` as that is neutral.

**Comment by alcuadrado** [comment]
Have you considered adding a way to disable this with a comment? 

For example, in js, most linters support things like this:

```
// lintername-disable-next-line no-unused-var
const definedButNeverUsed = 123;
```

**Comment by frangio** [comment]
I don't think this is going to solve the frequently discussed problem of warnings in the way it's been proposed.

I'm not aware of any tool that treats warnings as errors. It's users who treat them as errors, because they don't want to see any console output when they compile. I don't see how this new severity level would fix that, unless these notices are hidden by default. The most reliable way to make them hidden by default would be to make a new separate compiler output that can be opted-in, as opposed to making them part of the same errors list where warnings are found now, where they will just get printed to the console in mostly the same way.

**Comment by leonardoalt** [comment]
It could help to solve it. People complain about opinionated warnings that might not be helpful. These could all be lifted to `info`.
They're in the same list, but they can be easily filtered out from the JSON output if tools are ok with giving the users an option for that, without removing warnings that might be important.

**Comment by christianparpart** [comment]
> It could help to solve it. People complain about opinionated warnings that might not be helpful. These could all be lifted to `info`.
> They're in the same list, but they can be easily filtered out from the JSON output if tools are ok with giving the users an option for that, without removing warnings that might be important.

@leonardoalt What about explicitly enabling/disabling warnings? Just like GCC `-Wno-foobar` so people can selectively disable warnings (in our case we could accept a list of warning IDs that are not to be reported.

**Comment by axic** [comment]
> so people can selectively disable warnings (in our case we could accept a list of warning IDs that are not to be reported.

One of the reasons we output a JSON structure with `severity` and `errorCode` is that frameworks can sort and filter it.  Compilers like GCC/clang do not output warnings/errors in such a fashion (and least that is not their regular interface), so there it makes sense to disable errors via configuration options.

**Comment by leonardoalt** [comment]
@yann300 @haltman-at @fvictorio @alcuadrado @frangio 
Here's a [soljson.js](https://820823-40892817-gh.circle-artifacts.com/0/soljson.js) which outputs the non-existing-SPDX-line as `info` instead of `warning`. It would be great to get some feedback on whether this is a problem for the tools or if it could be easily supported.

**Comment by haltman-at** [comment]
I mean, as I've already mentioned, it would be a problem for current versions of Truffle, but it wouldn't be too hard to make the necessary changes.

**Comment by yann300** [comment]
it would only require slight changes in the UI, so that's something easy to do.
Could you let us know when it lands in production?

**Comment by fvictorio** [comment]
@leonardoalt it doesn't seem to break anything in Hardhat :+1:

**Comment by axic** [comment]
I think we're pretty set that this will land and will use `info` (https://github.com/ethereum/solidity/issues/11508#issuecomment-871362272), so perhaps consider doing the changes as time permits?

**Comment by leonardoalt** [comment]
@axic is this breaking? I see arguments in both directions, but I'll stick with no. It would be nice to get this merged (without the license warning change) to also merge https://github.com/ethereum/solidity/pull/11451 for example.

**Comment by leonardoalt** [comment]
Decided in call: this is not breaking.
