### ISSUE TITLE
[NatSpec] ICE in extractReturnParameterDocs due to lack of return parameter name

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11514]
```
interface IThing {
  ///@return
  function value(uint) external returns (uint128,uint128);
}

contract g is IThing {
  struct Value {
    uint128 x;
    uint128 A;
  }
  mapping(uint=>Value) public override value;
}
```

throws

https://github.com/ethereum/solidity/blob/98e7b61a378467116bd5dfdd8d1455a60ef26d2e/libsolidity/interface/Natspec.cpp#L201

To reproduce

```
$ solc test.sol
```

**Comment by bshastry** [comment]
Looks similar to https://github.com/ethereum/solidity/issues/9947 in that the thrown exception is identical

**Comment by chriseth** [comment]
The PR just adds a test, did it really fix the issue?

**Comment by Marenz** [comment]
The fix was in https://github.com/ethereum/solidity/pull/12544 though it referenced a different issue, that's also the main reason we added a test explicitly for this case

**Comment by chriseth** [comment]
ok!
