### ISSUE TITLE
Extend the constant optimizer to optimizer sub-expressions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11513]
The constant optimizer should not only consider PUSH opcodes (stand-alone constants) but also PUSH opcodes in combination with other opcodes:

`C SUB` -> `(~C+1) ADD`

`C ADD` -> `~(C-1) SUB`

**Comment by hrkrshnn** [comment]
I think we can have a separate rule list for doing constant optimizations.

The transformation can look like

`ADD(A, X) -> SUB(X, 2**256 - A)` if `2**256 - A` is shorter than `A`.

**Comment by chriseth** [comment]
Ah, I haven't thought of that: It is difficult to do it at the opcode level (at least for the add -> sub part), because the transformation would be
```
... A ADD
->
... ~(A-1) SWAP1 SUB
```

This means the transformation is not really much cheaper than what we already have, which is replacing `A` by `~A NOT`.
