### ISSUE TITLE
"Unreachable code" warning in 0.8.5 but not 0.8.4

### ISSUE THREAD

**Issue by lhoenig** [ethereum/solidity#11522]
## Description

After trying out 0.8.5 on our code, we got a lot of strange warnings about "unreachable code". The warning seems to have to do with library functions marked as `internal`.

## Environment

- Compiler version: 0.8.5
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: No execution, compliation problem
- Operating system: macOS 11.4

## Steps to Reproduce

`A.sol`:
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity =0.8.5;

import './B.sol';

contract Test is Bar {}
```

`B.sol`:
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity =0.8.5;

library Foo {
    // no warning if visibility "public"
    function nop() internal {}
}

contract Bar {
    function example() public returns (uint256) {
        foo();
        return 0;
    }

    function foo() public {
        Foo.nop();
    }
}
```

Compilation output:
```
➜  contracts  hh compile --force
Solidity 0.8.5 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support"

Compiling 2 files with 0.8.5
Warning: Unreachable code.
  --> contracts/B.sol:11:9:
   |
11 |         return 0;
   |         ^^^^^^^^


Compilation finished successfully
```

**Comment by cameel** [comment]
I played with the example a bit and here are some observations:
- It seems to require that fairly specific base combination: contract that inherits from a contract imported from another file which has a function that calls a function that calls an internal library function.
- It does not happen with free functions. Only internal library functions.
- Putting the contracts in the same file, removing inheritance or removing one of the functions in the chain makes the error go away.
- Once the you have that basic pattern in the code (functions, calls, contracts, etc.), adding more stuff does not seem to affect it much.

This must be related to the control flow graph PRs that went in this release so pinging @Marenz.

**Comment by Philogy** [comment]
I also got this bug in my code. Switching back to `0.8.4` gets rid of the warning.

**Comment by adriandelgg** [comment]
I've also received this bug. I've been using 0.8.4 because of it. I've heard of others experiencing the same issue as well.

**Comment by chriseth** [comment]
We will release a bugfix release this week or the beginning of next week.

**Comment by frangio** [comment]
Just to be sure, could this bug have had any consequence in code generation? Could any of these lines of code that were considered unreachable have been removed from the final contract?

**Comment by ekpyron** [comment]
> Just to be sure, could this bug have had any consequence in code generation? Could any of these lines of code that were considered unreachable have been removed from the final contract?

No, it's just incorrect warnings during analysis. Code generation will not be affected in any way.

**Comment by cameel** [comment]
Just to add some data points on whether the issue is very widespread. I saw it reported by users independently in various places so unfortunately it probably is:
- https://github.com/juanfranblanco/vscode-solidity/issues/256
- https://forum.openzeppelin.com/t/unreachable-code-warnings-in-initialize/10527

**Comment by johnfawole** [comment]
> We will release a bugfix release this week or the beginning of next week.

Hi, I am using v 0.8.17 and it is still bringing this error. Lol.

**Comment by cameel** [comment]
@johnfawole Can you post a snippet that reproduces it?

Also are you 100% sure you're using 0.8.17? How are you installing the compiler? Can you reproduce it with a binary from the [0.8.17 release](https://github.com/ethereum/solidity/releases/tag/v0.8.17)?
