### ISSUE TITLE
[solutil] Length error while resizing string during parsing ExternalSource header

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11528]
```
==== ExternalSource://====
```

throws here

https://github.com/ethereum/solidity/blob/2fefd27acf6cb813f627e39f8283724856222d86/libsolutil/CommonIO.cpp#L58

Repro

```
$ isoltest -t test
```

**Comment by cameel** [comment]
A test like this is invalid. The target of an external source must be a regular file. Directories are not allowed. In #11579 I made it return a more appropriate error but it's still an error.

I think the actual fix should be to make fuzzer either not generate this kind of test or detect that an error is the expected result here.

**Comment by bshastry** [comment]
Closing since this should no longer be a problem thanks to#11579
