### ISSUE TITLE
Different optimizer settings in Standard JSON when `optimizer` dict is empty

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11521]
## Description
In Standard JSON an empty `optimizer` dict has a different effect than one with explicitly enabled or disabled optimization:
- `"settings": {"optimizer": {"enabled": false}}` uses [`OptimiserSettings::minimal()`](https://github.com/ethereum/solidity/blob/v0.8.5/libsolidity/interface/OptimiserSettings.h#L68-L74).
- `"settings": {"optimizer": {"enabled": true}}`  uses [`OptimiserSettings::standard()`](https://github.com/ethereum/solidity/blob/v0.8.5/libsolidity/interface/OptimiserSettings.h#L76-L90).
- `"settings": {"optimizer": {}}` uses [`OptimiserSettings::none()`](https://github.com/ethereum/solidity/blob/v0.8.5/libsolidity/interface/OptimiserSettings.h#L63-L66).

This might be intentional - using `none()` when the dict is empty makes sense in a way. The problem is that this is not at all obvious to the user. One might reasonably assume that not including `enabled` at all would be equivalent to `"enabled": false`, especially given that non-JSON interface does not even provide any third choice.

This has already resulted in a bug in solc-js (https://github.com/ethereum/solc-js/issues/527) where the lack of `--optimize` flag has a different result than in solc.

I think that minimal settings should be used when `enabled` is missing. Alternatively, we could replace the boolean with an explicit choice of optimization level if we want it to be still possible to select `OptimiserSettings::none()`.

For reference, here's the code in `StandardCompiler` that handles the flag: https://github.com/ethereum/solidity/blob/a4f2e591fe55900f86ab72fad37d03af7dfa638e/libsolidity/interface/StandardCompiler.cpp#L561-L569

**Comment by chriseth** [comment]
Empty dict and no setting at all should both be the same as `enabled: false`.

**Comment by hrkrshnn** [comment]
> - `"settings": {"optimizer": {"enabled": true}}` uses [`OptimiserSettings::minimal()`](https://github.com/ethereum/solidity/blob/v0.8.5/libsolidity/interface/OptimiserSettings.h#L68-L74).
> - `"settings": {"optimizer": {"enabled": false}}`  uses [`OptimiserSettings::standard()`](https://github.com/ethereum/solidity/blob/v0.8.5/libsolidity/interface/OptimiserSettings.h#L76-L90).

@cameel Should be the other way around, right?

**Comment by cameel** [comment]
@hrkrshnn Thanks! You're completely right, sorry for the mixup. Fixed.
