### ISSUE TITLE
Do not warn about `this` used in constructor if not used to call a function

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11540]
`this` is sometimes necessary to clarify that a function of the current contract is being accessed as an external one. The compiler currently warns about every use of it in a constructor, which drives users away from using it in even innocuous constructs like simply getting a function selector:

```solidity
contract C {
    function ext() external {}
    function pub() public {}

    constructor() {
        this.ext.selector;
        this.pub.selector;
    }
}
```
```
Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
 --> test.sol:6:9:
  |
6 |         this.ext.selector;
  |         ^^^^

Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
 --> test.sol:7:9:
  |
7 |         this.pub.selector;
  |
```

This is actually the "correct" way to get the selector (#10905). Sometimes it's also possible to get the selector via unqualified access or via contract name but it does not work in all situations. I think that the compiler should not warn when it's just the selector that's being accessed. 

I think that it might be better to also omit the warning in any case where the function is not being directly called. For example when it's only assigned to a pointer. There are valid situations where such a pointer is only called at runtime so the warning is a bit overzealous:

```solidity
contract C {
    function () external handler;

    constructor(bool useA) {
        if (useA)
            handler = this.a;
        else
            handler = this.b;
    }

    function a() external {}
    function b() external {}

    function test() public {
        handler();
    }
}
```

## Environment

- Compiler version: 0.8.5

**Comment by chriseth** [comment]
Can't we just add `selector` to `C.pub`?

**Comment by cameel** [comment]
We could. @nventuro would probably appreciate that.

But even if we do this, isn't the warning about `this` in `this.C.pub` undesirable?

**Comment by cameel** [comment]
We talked about this on today's call.
- We're going to suppress the warning when `this` is used to access the selector.
- We should make selector available on public methods even when not accessed through `this`.
- We'll leave the general case of function pointers as is (i.e. with a warning).

**Comment by k06a** [comment]
Found a way to avoid this issue by using `C(address(0)).ext.selector`

**Comment by k06a** [comment]
I am also not allowed to touch internal function pointer in constructor, which uses `immutable` inside itself. Even if I am not calling this internal function pointer.

**Comment by ekpyron** [comment]
Marking this as "high effort" and "needs design", since doing this *properly* is hard. E.g. as an extension of the second case in the issue description consider:
```
interface I { function f() external; }

contract C is I {
        function () external handlerA;
        function () external handlerB;
        constructor(I x, bool flag) {
                if (flag) {
                        handlerA = this.f;
                        handlerB = x.f;
                } else {
                        handlerA = x.f;  
                        handlerB = this.f;
                }

                if (flag) {
                        handlerB();
                } else {
                        handlerA();
                }
        }
        function f() external override {}
}
```

This is technically a fine use of ``this``, but we most definitely don't want to go out of our way to determine that.

So defining the precise subset of cases that are fine to accept is the tricky part here.

We could restrict to *only* ``this.f.selector``, but that's also weird special-casing without also accepting ``(this).f.selector``... and then it continues to the question of ``(f ? this : this).f.selector``...

**Comment by cameel** [comment]
I think we should just do the selector case.
