### ISSUE TITLE
Investigate solidity-by-example.org site for inspiration

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11556]
https://solidity-by-example.org has a lot of example contracts we may want to include in the main documentation or in #11509

**Comment by aaroosh-07** [comment]
To solve this issue do we add a hyperlink to the above website in the resources section of our documentation or create a different page by name of solidity tutorials

**Comment by v-sreekesh** [comment]
Hi i have raised a pull request [https://github.com/ethereum/solidity/pull/11766](url) and included solidity-by-example.org in the documentation
