### ISSUE TITLE
[CLI] Different source hashes when source is passed via standard input and via command line parameter

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11553]
## Description
The content of the file passed to standard input does not pass through unmodified and its content hash stored in metadata (note: I do not mean the metadata hash itself) is different than when the file name is given as an argument.

The problem is caused by our function for reading standard input, which replaces all newlines with `\n` and also adds a newline after the last line, even if originally there wasn't one.

In practice the consequences of this are probably minor because even if the source hashes end up being the same, metadata won't be - due to different file names (unless the file is called `<stdin>` which is unlikely). Still, I think that this behavior is unexpected by users and should be changed. It looks intentional though and might be a workaround for something so we should discuss it first.

## Environment

- Compiler version: 0.8.5
- Operating system: Arch Linux

## Steps to Reproduce
```bash
echo "contract C {}" > '<stdin>'
solc '<stdin>' --metadata
```
`sources` key from metadata output:
```json
    "sources": {
        "<stdin>": {
            "keccak256": "0xbe86d3681a198587296ad6d4a834606197e1a8f8944922c501631b04e21eeba2",
            "urls": [
                "bzz-raw://7ef32f5b5f3b1ebe447f46969c01ce0e9190d0b90241cbc228255866326be8be",
                "dweb:/ipfs/QmZRepHCmeSSTfxZvKU5KS7pebBYT4khWhTnqh6GzBFU3M"
            ]
        }
    },
```
```bash
cat contract.sol | solc - --metadata
```
`sources` key from metadata output:
```json
    "sources": {
        "<stdin>": {
            "keccak256": "0xec5627577fc5b8010229a1036827ef0739fb21bb05b7bf259947acdded145877",
            "urls": [
                "bzz-raw://2363616d36c4824b30b1698ffa5bc3443635a4d68eb4a93c7126b30b7716f0a1",
                "dweb:/ipfs/QmYENep2eioJEAMKZWozLW3fb2BHjNxCXSszbDzz2kfWJu"
            ]
        }
    },
```

**Comment by chriseth** [comment]
Do we need the processing?

**Comment by chriseth** [comment]
Reading the source, I cannot imagine this being intentional.

**Comment by cameel** [comment]
I don't think we need it.

It looked like intentional to me because I can't see why else one would read a file line by line but still return the content. The only reason I can think of is to replace the line endings.

**Comment by chriseth** [comment]
I think this is because it is the most convenient way to read a file.

**Comment by TerranCivilian** [comment]
Can you assign this to me? I can try to tackle this tomorrow and report back.

**Comment by cameel** [comment]
@TerranCivilian You might want to start by looking at the function that reads data from standard input:
https://github.com/ethereum/solidity/blob/cbf1c3ae6969781e5ce050adb82129b4d9379fa8/libsolutil/CommonIO.cpp#L70-L82

**Comment by TerranCivilian** [comment]
Thanks for the excellent writeup. After many hours of research and benchmarking, I believe I've produced an optimal solution (as seen here https://github.com/ethereum/solidity/pull/11584).

**Comment by TerranCivilian** [comment]
Still working on this, mostly on weekends. Hope to wrap it up this weekend.
