### ISSUE TITLE
There are different 384 charactors at the end of bin file, what are they?

### ISSUE THREAD

**Issue by Shirley-Ji** [ethereum/solidity#11554]
I wrote a bytecode verifier and when doing comparison between the on-chain bytecode and the bytecode generated by myself, there are always different 384 charactors at the end of the bytecode for a swapFactory contract. These different 384 charactors begin from "4d494e544544", and at the middle of the 384 charactors, there are 2*64 charactors are always exactly same.

What does "4d494e544544" mean? MINTED? I've searched the EVM bytecode standard, found the bytecode contains "bytecode","constructor params","auxdata". But I didn't find any pattern like "4d494e544544". Once I removed these 384 charactors, the left parts of the bytecode are same.

So how to understand "4d494e544544"? Can I remove these 384 charactors when comparing?

the on-chain bytecode:
**4d494e544544**a265627a7a72315820a9491d76ec56377fec9dc0e32a15078a0f
78064987c1e979085f566eba40e14064736f6c63430005100032454950373132
**446f6d61696e28737472696e67206e616d652c737472696e672076657273696f**
**6e2c75696e7432353620636861696e49642c6164647265737320766572696679**
696e67436f6e747261637429a265627a7a72315820938b3c3c6830e6026fdad6
e34e2e24cf1cbf0933dc66221bb2918327429cf8ba64736f6c63430005100032

what I compiled:
**4d494e544544**a265627a7a7231582001df7b333f5e97fcf5b071b42706264458
7b251219796a6c9dd57ec4cc89d06d64736f6c63430005100032454950373132
**446f6d61696e28737472696e67206e616d652c737472696e672076657273696f**
**6e2c75696e7432353620636861696e49642c6164647265737320766572696679**
696e67436f6e747261637429a265627a7a72315820b3b41184cb60b5a17357e3
3fe6a35fc9d85d1bb8c84f56e9e86de9632fb5eaa064736f6c63430005100032

**Comment by cameel** [comment]
The extra data at the end contains hashes of the contract metadata. See [Encoding of the Metadata Hash in the Bytecode](https://docs.soliditylang.org/en/latest/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode) in the docs.

It's cut off in your example but you can see some of the markers there: `736f6c63` (`solc` in ASCII) followed by `0x43` and then `000510` (version 0.5.10).

Overall, if you want to see what gets into the binary, it might be easier to look at the `--asm` output: [Analysing the Compiler Output](https://docs.soliditylang.org/en/latest/analysing-compilation-output.html).

**Comment by cameel** [comment]
Anyway, the metadata hashes are clearly different so your local setup must be different from how the contract was originally built. For example paths could be different, the deployed contract could have been flattened, files might have extra comments, different newlines, etc. Metadata contains hashes of all source files so if the files are not identical byte for byte, you will not get the exact same bytecode.

It would be best to compare the output of `solc --metadata` for  both versions.

**Comment by Shirley-Ji** [comment]
Thanks, @cameel . 

I checked it, if I use 0.5.10 to compile, the auxdata shows like "bzz", if I change to use 0.6.12, the auxdata shows like "ipfs". Thanks for your help. I can compare them now.

Am I right? any other types of output of auxdata?

**Comment by cameel** [comment]
`bzzr` is a Swarm hash. `ipfs` is an IPFS one. Currently there are no others but some might be added in the future. It has already chagned in the past as you can see.
