### ISSUE TITLE
Invalid function calls in the bytes truncation example in 0.8.5 announcement on the blog

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#11561]
## Page

https://blog.soliditylang.org/2021/06/10/solidity-0.8.5-release-announcement/

## Abstract

The coding example for the new *Bytes Conversion* feature in your 0.8.5 release notes is erroneous.

## Details

Quoting from the release notes linked above:

```
function f(bytes calldata c) public view returns (bytes8) {
	// If c is longer than 8 bytes, truncation happens
	return bytes8(c); 
}
```

> Calling `f("12345678")` will return `"12345678"`, as will calling it as `f("1234567890")`. If the array is shorter than the target fixed type, it will be padded with zeros at the end, so calling `f("1234")` will return `"1234"`.

---

It is not clear whether one should issue these function calls on-chain or off-chain (i.e., from a contract or from a script).

On-chain, they all yield compilation errors, for example:

> TypeError: Invalid type for argument in function call. Invalid implicit conversion from literal_string "12345678" to bytes calldata requested.

Off-chain, using web3.js v1.3.5, `f("1234567890")` gives a runtime error:

> Error: invalid arrayify value (argument="value", value="1234567890", code=INVALID_ARGUMENT, version=bytes/5.0.5)

Minor: in the declaration of `function f` itself, you can reduce `view` to `pure` (a compilation warning is issued otherwise).

Thanks

**Comment by cameel** [comment]
I think that these calls were meant to show only the general concept rather than be something to paste directly into your code. Still, you're right, they would not compile as is so maybe it would be better to adjust them to avoid confusing people.

> On-chain, they all yield compilation errors, for example:

It's because of the `calldata` parameter in `f()`. If it was `memory`, it would compile.

> Off-chain, using web3.js v1.3.5, f("1234567890") gives a runtime error:

I think web3 expects a hex string with ASCII codes for bytes. `0x31323334353637383930` should work instead. At least it works in Remix which produces the same error message.

**Comment by barakman** [comment]
@cameel:

IMO, if choosing to post a coding example, then it should be a working one.

Regarding your off-chain call suggestion - yes, it works from web3.js as well.

I previously considered trying it but wasn't really sure what to input.

I understand that with `"0x31323334353637383930"`, you tried to pass the ASCII representation of `"12345678980"`, but since web3.js returns the same "kind" of ASCII representation, I believe that passing `"0x11223344556677889900"` would serve the purpose better (as web3.js also returns an hex string rather than its ASCII interpretation).

Thanks

**Comment by cameel** [comment]
@barakman Here's a fix: https://github.com/ethereum/solidity-blog/pull/143. Feel free to review and suggest adjustments if necessary.
