### ISSUE TITLE
Solc 0.8.5 issues redundant 'Unreachable code' compilation warnings

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#11562]
## Description

Going from solc 0.8.4 to solc 0.8.5, I am getting multiple compilation warnings for unreachable code.

## Environment

- Compiler version: 0.8.5
- Operating system: MacOS

## Steps to Reproduce

File TestLibrary.sol:
```solidity
// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity 0.8.5;

library TestLibrary {
    function func3() internal pure returns (uint256) {
        return 0;
    }
}
```

File TestContract.sol:
```solidity

// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity 0.8.5;

import "./TestLibrary.sol";

contract TestContract {
    function func() public pure returns (uint256, uint256) {
        return (func2(), 1);
    }
    function func2() private pure returns (uint256) {
        return TestLibrary.func3();
    }
}
```

I believe that these redundant warnings are the result of one of the 'Control Flow Graph' or 'Function Call Graph' fixes (described as part of solc 0.8.5 [release notes](https://github.com/ethereum/solidity/releases)), because these warnings can be resolved by even slightly minimizing the code above.

For example, by implementing the library in the same file as the contract (instead of in a separate file).

Or for example, by returning a single uint value in the contract's public function (instead of two uint values).

Or for example, by reducing the contract code to:
```solidity
    function func() public pure returns (uint256, uint256) {
        return (TestLibrary.func3(), 1);
    }
}
```

Thanks

**Comment by cameel** [comment]
Thanks for reporting. This is a known issue and has already been fixed (https://github.com/ethereum/solidity/issues/11522). Version 0.8.6 with a fix will be released soon.

**Comment by barakman** [comment]
Thanks, that was the fastest response I ever got for an issue :)
