### ISSUE TITLE
Disallow zero literals as arguments to `bytes.concat()`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11588]
Related to #11580 and #11582.

## Description
Currently `bytes.concat()` accepts zero literals because they're implicitly convertible to fixed bytes. After my fix in #11580 they're treated as `bytes1` but user might just as well expect `bytes32` or any other width. This introduces ambiguity and I don't see much use for zero literals in practice so we should disallow this.

As far as I can tell zero is the only exception. Other integers are not implicitly convertible and thus not accepted.

## Backwards-compatibility
Normally this would be a breaking change but this use case was broken and only fixed in 0.8.6 (#11580) so as long as we do it in the same release it can't break any valid code.

**Comment by chriseth** [comment]
Sounds good, let's do it!

**Comment by cameel** [comment]
While working on this I discovered that the situation is more complex than I thought:
- `bytes.concat()` is actually broken for 32-byte fixed bytes literals. Fails on an assert in codegen because the type checker lets them through while codegen does not handle them properly. So that's another bug similar to #11580 and #11581.
- Zero is not the only literal implicitly convertible to fixed bytes after all. Hex literals (e.g. 0x12345678) are convertible fixed bytes of the same length so 32-bytes ones should work too.
    - So we do not want to disallow `0x0000000000000000000000000000000000000000000000000000000000000000` even if we disallow `0`.
    - My fix in #11580 "broke" `bytes.concat(0x0000000000000000000000000000000000000000000000000000000000000000)` by making the codegen use `bytes1`. It did not matter much though because, as I said above, codegen was not handling that case correctly anyway (would try to use `bytes` if the assertion was not there).

**Comment by cameel** [comment]
Done in #11590. It disallows only plain `0` but not `0x0000000000000000000000000000000000000000000000000000000000000000` and fixes the 32-byte hex literals.

**Comment by cameel** [comment]
We decided to change the solution to disallowing all numeric literals in `bytes.concat()` because `abi.encodePacked()` does not support them either. See https://github.com/ethereum/solidity/pull/11590#discussion_r660535182 for details.
