### ISSUE TITLE
Disallow implicit conversion from weird zero literals to fixed bytes

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11582]
Originally pointed out by @axic in https://github.com/ethereum/solidity/pull/11580#discussion_r658959661.

We currently provide an implicit conversion from various "weird" zero literals to fixed bytes, which means this is a perfectly valid call:
```solidity
bytes.concat(0, -0, 0.0, -0.0, 0e10, 0e-10, 0x00, hex"00");
```

Of those all the fixed-point zeros should probably be disallowed. Not sure about `-0` (does it count as a special literal or an expression?) but if it's a distinct literal, maybe it makes sense to disallow it too.

**Comment by axic** [comment]
I'd also argue that `0e10` may not have its place as a literal for a bytes type, however IIRC that is parsed in the scanner, so can't do much about it.

**Comment by chriseth** [comment]
I think `bytes3 x = 0` should still be valid.

**Comment by cameel** [comment]
That one sure. The issue is not about disallowing it. What about `bytes3 x = 0.0` though?

**Comment by cameel** [comment]
Also, consider this irregularity:
- `0x0000000000000000000000000000000000000000000000000000000000000000`: implicitly convertible to any fixed bytes.
- `-0x0000000000000000000000000000000000000000000000000000000000000000`: implicitly convertible to any fixed bytes.
- `0x0000000000000000000000000000000000000000000000000000000000000001`: implicitly convertible to `bytes32`.
- `-0x0000000000000000000000000000000000000000000000000000000000000001`: not implicitly convertible to fixed bytes.

**Comment by chriseth** [comment]
The third one is fine (I assume it has 32 hex bytes), the first one is, too. So I think there are only cases left that write zero either as negative or as fractional or using scientific notation. If it's too difficult to implement, I would leave it. This is really not such a big deal.

**Comment by cameel** [comment]
Sounds good to me. Seems in line with that @axic wanted so I'm going to move this to implementation backlog.

Do you think it would be a `good first issue`? Especially given that it's fine to give up if it turns out to be difficult?

**Comment by chriseth** [comment]
Please check the code to see what has to be done without doing it. If it is easy, then it can be a good first issue.
