### ISSUE TITLE
[SMTChecker] Out-of-range exception

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11587]
```
==== Source: s1.sol ====
pragma experimental SMTChecker;
function f() {
  (ecrecover("1234", 1, "0", abi.decode("", (bytes2))));
}
==== Source: s2.sol ====
contract C {}
```

Reproduction

- Copy test contents to a file called `test/libsolidity/syntaxTests/test.sol`

```
$ isoltest -t syntaxTests/test
```

I have not been able to reproduce it without the SMT pragma and hence the title.

**Comment by cameel** [comment]
Looks like it started in 0.8.4. The error is:
```
Unknown exception during compilation: map::at
```

Reproducing it does require two separate files. It does not fail without the one containing `contract C {}`. It's probably related to the pragma deprecation and the switch to global SMT settings.

**Comment by hrkrshnn** [comment]
> Unknown exception during compilation: map::at

Coincidentally enough the same issue trying to use SMTChecker on 0.8.6 in a hardhat project. It didn't have any `pragma experimental smtchecker.

**Comment by cameel** [comment]
I just found a different crash while playing with this example. Not sure if the cause is the same or not. Started on 0.8.4 as well.

- `a.sol`
    ```solidity
    pragma experimental SMTChecker;

    function f() {
        ecrecover("", 1, "", "");
    }
    ```
- `s1.sol`
    ```solidity
    contract C {}
    ```

```
SMT logic error during analysis:
/solidity/libsmtutil/Z3Interface.cpp(270): Throw in function z3::expr solidity::smtutil::Z3Interface::toZ3Expr(const solidity::smtutil::Expression&)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Sort mismatch at argument #1 for function (declare-fun ecrecover_input_type (Int Int Int Int) ecrecover_input_type) supplied sort is bytes_tuple
[solidity::util::tag_comment*] = Sort mismatch at argument #1 for function (declare-fun ecrecover_input_type (Int Int Int Int) ecrecover_input_type) supplied sort is bytes_tuple
```

**Comment by leonardoalt** [comment]
Yea it should be the same. I'll add it to the PR to see.
