### ISSUE TITLE
SMTLogicException - Crash/Hang

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#11603]
## Description

Hello everyone,

The Contract below :

pragma experimental SMTChecker;
  contract C {
    struct S {
      int a;
      bytes5 b;
    }
    function f() public pure {   assert(S({a:2, b:""}).b == bytes5(0)); // should hold
  if (0<1)
  if (0==1){}
  while(1==1)
      assert(S({a:2, b:""}).a == 0); // should fail
    }
}

produces the following crash in version 0.8.4 :

SMTLogic Error : Trying to create an 'equal' expression with different sorts.

While there seems to be a hang(compilation time is slow) for some seconds in the same contract in versions 0.8.5, 0.8.6

## Environment

- Compiler version: 0.8.4, 0.8.5, 0.8.6
- Target EVM version (as per compiler settings): 
- Framework/IDE (e.g. Truffle or Remix): remix
- EVM execution environment / backend / blockchain client:
- Operating system: ubuntu 18.0.4

## Steps to Reproduce

compile the contract above

**Comment by leonardoalt** [comment]
Thanks for the report!
The bug seems to be fixed on latest develop though (and probably in the latest release).
Locally I get
```
Warning: CHC: Assertion violation happens here.
Counterexample:


Transaction trace:
C.constructor()
C.f()
 --> bug.sol:8:3:
  |
8 | 		assert(S({a:2, b:""}).a == 0); // should fail
  | 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Closing because already fixed.
