### ISSUE TITLE
[isoltest] Bug in auto update for gas in constructor case

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11600]
Take the following semantic test:

```solidity
contract C {
    uint public x = 1;
}
// ====
// compileViaYul: also
// ----
// constructor()
// gas irOptimized: 1
// gas legacy: 1
// gas legacyOptimized: 1
// x() -> 1
// gas irOptimized: 1
// gas legacy: 1
// gas legacyOptimized: 1
```

Running isoltest will automatically update the gas costs for `x()`, however the constructor call doesn't seem to get updated.

(Or only updated for `legacy`, which was the case https://github.com/ethereum/solidity/pull/11598/files#r661433855)

**Comment by ekpyron** [comment]
For me this correctly updates ``legacy`` on an ``isoltest`` run and ``legacyOptimized`` on an ``isoltest --optimize`` run, as I would expect...

**Comment by ekpyron** [comment]
Or actually, something really weird is going on... if I start from the test case and run ``isoltest`` and then ``isoltest --optimize``, then it updates everything correctly... if I then change ``legacyOptimized`` to ``1`` in the constructor, it ignores it... if I also change ``legacyOptimized`` to ``1`` for ``x()`` though, it updates again...
