### ISSUE TITLE
IPFS has issues with metadata and bytecode

### ISSUE THREAD

**Issue by alysak6075** [ethereum/solidity#11601]
Hello, 

I am trying to retrieve the IPFS hash/file that is at the bottom of the Contract tab

https://etherscan.io/address/0xbbd3c0c794f40c4f993b03f65343acc6fcfcb2e2#code

This is the link:
ipfs://62c1e84b5f1f3effe1c0e4adbbd785ad950c738ea87a7aaef091add4452a9cbd

from my understanding and from the solidity docs this is the IPFS hash of the file but IPFS responds with:
Error: invalid path "/ipfs/62c1e84b5f1f3effe1c0e4adbbd785ad950c738ea87a7aaef091add4452a9cbd": invalid CID: selected encoding not supported

What encoding is missing? what needs to be converted?
Please help?

**Comment by alysak6075** [comment]
it looks like i need to base58 encode this:
122062c1e84b5f1f3effe1c0e4adbbd785ad950c738ea87a7aaef091add4452a9cbd

which gives me this:
QmUzAA35NGHkSs5nMDXh9HgvbNWwmiQ24xQTx3Ppedfeip

which LOOKS like a valid hash for ipfs.
but it hangs and never receives anything.
if someone could point me in the right direction?

**Comment by chriseth** [comment]
This seems to be an issue with etherscan, they do not format the binary data. In general, IPFS is not guaranteed to keep the data available, there is not even a guarantee that the data has been uploaded at all.
