### ISSUE TITLE
Unknown exception during compilation: array::at: __n (which is 4294967295) >= _Nm (which is 32)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#11608]
## Description

This contract:
```solidity
contract C {
    bytes s = "bcdef";
    function f(bytes memory a) public pure returns (bytes memory) {
        return bytes.concat(a, "bcdef"); }
    function k(bytes calldata a, string memory b) public pure returns (bytes memory) {
        return bytes.concat(a, "", bytes(b));
    }
    function fixedBytesParam(bytes16 b1, bytes15 b2, bytes31 b3) public returns (
        bytes memory
    ) {}
    function fixedBytesParam2(bytes calldata c, bytes6 b1, bytes6 b2) public view returns (bytes memory, bytes memory) {
        return (
            bytes.concat(s, b1, c),
            bytes.concat(c, b1, b2)
        );
    }
}
```

produces:

```
Unknown exception during compilation: array::at: __n (which is 4294967295) >= _Nm (which is 32)
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

## Environment

- Compiler version:  0.8.5-develop.2021.6.12+commit.a4f2e591.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by cameel** [comment]
Thanks for the report! Looks like this time I was faster and it's already fixed: #11581 :)

The problem is the empty string literal:

```solidity
bytes.concat(a, "", bytes(b));
```

There were also two related bugs regarding zero literal (#11580) and `bytes32` literals #11590 so please ignore them if you encounter them - they're fixed too.
