### ISSUE TITLE
When I try to link the bytecode of the keccak256 of the library name it doesn't equal the hash placeholder of the compiled library name

### ISSUE THREAD

**Issue by zhiwenh** [ethereum/solidity#11619]
For example when compiling a library with the name A, the hash return as the placeholder for the library address is 5e7663a41168bba34828be1c13ebf43086, But when I run the keccak256 of the library name A it returns 03783fac2efed8fbc9ad443e592ee30e61. Does anyone know how to fix this issue?

**Comment by chriseth** [comment]
The name of a library does not have to be unique across a compilation run: There can be two libraries with the same name in different files and they can both be used when renaming them during imports. Because of that, the hash includes the file name of the library.
