### ISSUE TITLE
ICE: Throw in function void (anonymous namespace)::StackHeightChecker::check(): I sense a disturbance in the stack: 4 vs 3

### ISSUE THREAD

**Issue by Cancelll** [ethereum/solidity#11611]
## Environment

- Compiler version: Version: 0.8.7-develop.2021.7.4+commit.f6cb933f.Linux.clang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux 5.4.0-77-generic x86_64 GNU/Linux

#### Test program: small.sol
```solidity
contract C {
    function f (address) external returns (bool) {
        this.f{gas: 42}.address;
    }
}
```
#### Compiler Command
```bash
solc-trunk-asan_ubsan --optimize small.sol
```
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ContractCompiler.cpp(82): Throw in function void (anonymous namespace)::StackHeightChecker::check()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: I sense a disturbance in the stack: 4 vs 3
[solidity::util::tag_comment*] = I sense a disturbance in the stack: 4 vs 3
```

**Comment by hrkrshnn** [comment]
Thanks for the report. Was this obtained via fuzzing @Cancelll?

**Comment by hrkrshnn** [comment]
I'm not sure if this should type check. Probably we should have a check that `.selector` and `.address` should be only for external calls without the `gas` or `value` set.

**Comment by Cancelll** [comment]
> Thanks for the report. Was this obtained via fuzzing @Cancelll?

Yes, it's found by a work-in-progress compiler testing tool named Kira.

**Comment by chriseth** [comment]
I think this is valid code. We should properly query the stack size everywhere. If it is too much work, we can consider disabling it.
