### ISSUE TITLE
[SMTChecker] Add full name of SMT in the document

### ISSUE THREAD

**Issue by simontianx** [ethereum/solidity#11612]
## Page

https://docs.soliditylang.org/en/latest/smtchecker.html

## Abstract

It would be nice to explicitly write down that SMT in SMTChecker stands for `Satisfiability Modulo Theories`. Viewers can have the certainty that what they later find on Google or Wikipedia is the right link to SMT.

**Comment by hrkrshnn** [comment]
Sounds good. Would you like to submit a PR?

The file that needs to be modified is: https://github.com/ethereum/solidity/blob/develop/docs/smtchecker.rst
