### ISSUE TITLE
ICE in `StructType::isDynamicallyEncoded()` when a function has a `calldata` struct argument with an internal type inside

### ISSUE THREAD

**Issue by Cancelll** [ethereum/solidity#11610]
## Environment

- Compiler version: Version: 0.8.7-develop.2021.7.4+commit.f6cb933f.Linux.clang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux 5.4.0-77-generic x86_64 GNU/Linux

#### Test program: small.sol
```solidity
contract C {
  struct S {
    function() a;
  }
  function f(S[2] calldata) {}
}
```
#### Compiler Command
```bash
solc-trunk-asan_ubsan --optimize small.sol
```
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/Types.cpp(2149): Throw in function virtual bool solidity::frontend::StructType::isDynamicallyEncoded() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] =
```

**Comment by cameel** [comment]
This is very similar to #10516, just for `calldata` rather than `memory`. Weird that the fix there did not cover this.
