### ISSUE TITLE
Optimize `if (a && b)`

### ISSUE THREAD

**Issue by fluidsonic** [ethereum/solidity#11640]
## Abstract

The following code examples basically do the same thing but have different gas usage.
In my project the former costs me 26 more gas than the latter according to `hardhat-gas-reporter`.

```sol
if (a && b) { … }
```

```sol
if (a) { if (b) { … } }
```

Solidity 0.8.6

## Motivation

Lower gas use = good

## Specification

I have no idea how the optimizer works but I guess that can be optimized.

## Backwards Compatibility

Shouldn't be an issue.

**Comment by hrkrshnn** [comment]
In your example, is `b` an expression?

Note that ~solidity~ Yul doesn't have short-circuiting for boolean expressions, so the conversion `if (expr1 && expr2) ... -> if (expr1) { if (expr2) ... }` will break the semantics in general. We could do this if the expressions doesn't have side effects, or if they are identifiers.

In the case where it's an identifier, I don't see it making much difference in runtime gas. Note that the two `if`, in general would have higher deploy time cost.

**Comment by fluidsonic** [comment]
@hrkrshnn I guess it was an expression. I can make some tests later to see if it happens when only using variables.

Solidity [does have short-circuiting](https://docs.soliditylang.org/en/v0.8.6/control-structures.html#order-of-evaluation-of-expressions) and I would be shocked if not.
> The evaluation order of expressions is not specified (more formally, the order in which the children of one node in the expression tree are evaluated is not specified, but they are of course evaluated before the node itself). **It is only guaranteed that statements are executed in order and short-circuiting for boolean expressions is done.**

**Comment by hrkrshnn** [comment]
@fluidsonic Ah, yes. Solidity does have short-circuiting. I mixed up solidity and Yul. 

Generally, such optimizations would be done at the Yul level, so, the argument about short-circuiting for  `if and(expr1, expr2) { ... }` would still be true. Regardless, I would be interested in seeing the results of your tests.

----
At the solidity level, changing `if (a && b)` to `if(a) { if (b) ...}`, even for identifiers, would make a difference.

For the former case, the Yul code would look like

```
                        let value0 := a
                        let value1 := b
                        let expr := value0
                        if value0 { expr := value1 }
                        if expr
                        {
                            ...
                        }
```
 
In the latter case, it would look like:

```
                        let value0 := a
                        let value1 := b
                        if value0
                        {
                            if value1
                            {
                               ...
                            }
                        }
```

So if the `if` condition is not met, you would save one `jumpi` and some checks for it.

Maybe we can think about combining `if` statements at the Yul level, somehow.

**Comment by chriseth** [comment]
Please not ethat @fluidsonic is probably using the "legacy" code generator, and not the yul code generator, so optimizer steps at the yul level do not help for this particular issue.

**Comment by fluidsonic** [comment]
I've tested it with Hardhat on a mainnet fork.

- Scenario 1: `a` and `b` are `bool` function parameters.
- Scenario 2: `a` and `b` are `.isNative()` called on `IERC20` function parameters.
    That's a `internal pure` Library function that basically checks `token == address(0)`.
- In both scenarios the statement `c` is `return 0`.

| Scenario | Runs        | Idiomatic code     | Optimized code        | ±Gas | ±Deployment gas |
|----------|-------------|--------------------|-----------------------|------|-----------------|
| 1        | 200         | `if (a && b) c;`   | `if (a) if (b) c;`    | -20  | -636 ❗️          |
| 1        | 200         | `if (a \|\| b) c;` | `if (a) c; if (b) c;` | -2   | +1,291          |
| 1        | 200,000,000 | `if (a && b) c;`   | `if (a) if (b) c;`    | -20  | -636 ❗️          |
| 1        | 200,000,000 | `if (a \|\| b) c;` | `if (a) c; if (b) c;` | -2   | +1,296          |
| 2        | 200         | `if (a && b) c;`   | `if (a) if (b) c;`    | -26  | -1,512 ❗️        |
| 2        | 200         | `if (a \|\| b) c;` | `if (a) c; if (b) c;` | -14  | +408            |
| 2        | 200,000,000 | `if (a && b) c;`   | `if (a) if (b) c;`    | -26  | -1,532 ❗️        |
| 2        | 200,000,000 | `if (a \|\| b) c;` | `if (a) c; if (b) c;` | -14  | +444            |

The savings in deployment gas are confusing me.

@chriseth what is the YUL code generator? Is that the experimental `viaIR` flag?
I've just tried it for the first time and didn't get too far:
> YulException: Variable param_3 is 2 slot(s) too deep inside the stack.

**Comment by chriseth** [comment]
The gas values are very weird indeed. Can you maybe post the assembly code somewhere?

Yes, I was talking about the generator that is activated using `viaIR`.

**Comment by fluidsonic** [comment]
This is for the first row of the table above (-20 gas, -636 deployment gas, `if (a && b)` -> `if (a) if (b)`).
The contract with the optimized code is 6 bytes smaller.

Idiomatic code:
```asm
    /*  function test(bool a, bool b) private view returns (uint) {... */
tag_126:
    /*  uint */
  0x00
    /*  a */
  dup3
    /*  a && b */
  dup1
  iszero
  tag_219
  jumpi
  pop
    /*  b */
  dup2
    /*  a && b */
tag_219:
    /*  if (a && b)... */
  iszero
  tag_220
  jumpi
  pop
    /*  0 */
  0x00
    /*  return 0 */
  jump(tag_104)
    /*  if (a && b)... */
tag_220:
  pop
    /*  1 */
  0x01
    /*  function test(bool a, bool b) private view returns (uint) {... */
  swap3
  swap2
  pop
  pop
  jump	// out
```

Optimized code:
```asm
    /*  function test(bool a, bool b) private view returns (uint) {... */
tag_126:
    /*  uint */
  0x00
    /*  a */
  dup3
    /*  if (a) if (b)... */
  iszero
  tag_220
  jumpi
    /*  b */
  dup2
    /*  if (b)... */
  iszero
  tag_220
  jumpi
  pop
    /*  0 */
  0x00
    /*  return 0 */
  jump(tag_104)
    /*  if (b)... */
tag_220:
  pop
    /*  1 */
  0x01
    /*  function test(bool a, bool b) private view returns (uint) {... */
  swap3
  swap2
  pop
  pop
  jump	// out
```

Diff:
```diff
@@ -4,17 +4,13 @@
   0x00
     /*  a */
   dup3
-    /*  a && b */
-  dup1
+    /*  if (a) if (b)... */
   iszero
-  tag_219
+  tag_220
   jumpi
-  pop
     /*  b */
   dup2
-    /*  a && b */
-tag_219:
-    /*  if (a && b)... */
+    /*  if (b)... */
   iszero
   tag_220
   jumpi
@@ -23,7 +19,7 @@
   0x00
     /*  return 0 */
   jump(tag_104)
-    /*  if (a && b)... */
+    /*  if (b)... */
 tag_220:
   pop
     /*  1 */
```

No other differences in the contract apart from `auxdata`.
