### ISSUE TITLE
[solidity-upgrade] Input file processing is out of sync with solc

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11651]
Looks like `soldity-upgrade` has input file processing logic duplicated from `CommandLineInterface.cpp`. Especially [`readInputFiles()` and file reader callback in `SourceUpgrade.cpp`](https://github.com/ethereum/solidity/blob/v0.8.6/tools/solidityUpgrade/SourceUpgrade.cpp#L417-L527). This logic in `CommandLineInterface` has recently been refactored in PRs like #11113, #11518. After #11545/#11617 will actually become functionally different so `solidity-upgrade` will be unable to resolve imports exactly the same way `solc` does so projects that depend on `--base-path` being set properly might no longer compile.

Logic needs to be unified in both places. Both should use `FileReader` and its callback. Preferably the input processing inside `readInputFiles()` itself should be shared between the two executables. I think that `solidity-upgrade` also needs `--base-path` option.

**Comment by siddharth1704** [comment]
Can you assign me on this issue i am new to open source i might need some help but i will complete the given task

**Comment by cameel** [comment]
Sure. You might want to start by trying out the `solidity-upgrade` tool and seeing how it works on the command line compared to `solc`.

If you start a PR, it's best to do it on top of #11545 (which is in review right now) because it touches that code.

Drop by at the `#solidity-dev` [Matrix](https://app.element.io/#/room/#ethereum_solidity-dev:gitter.im)/[Gitter](https://gitter.im/ethereum/solidity-dev) channel if you need more help.

**Comment by siddharth1704** [comment]
ok i will genrate the PR on top of it

**Comment by cameel** [comment]
Closing due to our plans to remove solidity-upgrade from the compiler in the near future (#13715).
