### ISSUE TITLE
Retain source location annotations across the optimizer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11669]
When using `solc --experimental-via-ir --asm file.sol`, the source locations are wrong, even with all pending pull requests in that area merged. The problem is that the yul->evm codegen in CompilerStack uses the optimized IR even when the optimizer is switched off. Still, the optiimzed IR is not the same as the non-optimized IR in that case: In `IRGenerator::run`, the AssemblyStack is used to parse the non-optimized IR, create a Yul AST from it, perform no operations on it (because the optimizer is disabled) and print it again. This printing loses all annotation comments, so the solution is to re-print the annotations in the AsmPrinter.

Required changes:

### Introduce struct `ObjectDebugData` in the `Object` class to include the source mappings.

Currently, the ObjectParser only stores the source index to source name mapping temporarily during parsing. It should just store it in the Object's debug data so it can be printed again.

### Change AsmPrinter to print both `@use-src` and `@src`

 - `Object::toString` should be changed to print `@use-src` from the object's debug data
 - `AsmPrinter` should be changed to print the `@src` annotations (being passed in the source name to source number mapping from Object::toString).

Of course, the AsmPrinter should only print the `@src` tag if it has changed since the last AST node.
For now, it is probably best to always use `/** ... */` instead of `///` because the logic about when to introduce a newline could be a bit tricky.

**Comment by christianparpart** [comment]
I think this is now all done and merged, right?
