### ISSUE TITLE
Document arithmetic expressions

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1166]
The documentation should have a section explaining issues around arithmetic expressions, such as,
- ~which arithmetic operators throw an exception on overflow~
- ~what happens when an operator takes two different types (e.g. `int + uint = ?`)~
- ~whether shifts automatically enlarge the type (e.g. `int3 << int3 = int256?`)~
- ~how the operators `mod` `/` `<<` and `>>` behave with negatives or zeros~
- ~implicit conversions between types~
- ~explicit conversions between types~

**Comment by ChrisChinchilla** [comment]
Point 2

> * what happens when an operator takes two different types (e.g. `int + uint = ?`)

Is mostly covered, even though the information is a little disparate and spread out, discussions on conversion generally is a little buried in various places.

**Comment by ChrisChinchilla** [comment]
In my opinion, these are all mostly handled throughout the docs now.
