### ISSUE TITLE
ICE in `CompilerUtils::convertType()` when converting a calldata slice of `bytes` or `string`

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#11677]
## Description

Hello all,

in the contract below, there seem to be an internal compiler error in solc 0.8.6 version.

contract C {
	function f(string calldata data) external pure returns (bytes memory) {
		return abi.encode(bytes(data[:32]));
	}
}

## Environment

- Compiler version: solc 0.8.6
- Target EVM version (as per compiler settings):0.8.6
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:0.8.6+commit.11564f7e
- Operating system: Ubuntu 16.04 LTS

**Comment by cameel** [comment]
Thanks!

Looks like it has started in 0.8.5 so it must be related to the new `bytes` conversions introduced there.

Smaller repro:
```solidity
contract C {
    function f(string calldata data) external pure {
        bytes(data[:32]);
    }
}
```
Works fine if `bytes` is used in place of `string`.

The reverse conversion also fails the same way:
```solidity
contract C {
    function f(bytes calldata data) external pure {
        string(data[:32]);
    }
}
```

**Comment by bshastry** [comment]
Just wanted to mention that this is also a problem with Sol->Yul. The following assertion fails when `solc --experimental-via-ir test.sol`

https://github.com/ethereum/solidity/blob/72c5f4caca7e1b0b28ea14dabb93dfdc897554ff/libsolidity/codegen/YulUtilFunctions.cpp#L3211

**Comment by Marenz** [comment]
It seems at this point this is _only_ a problem with the yul backend.
The old codegen doesn't seem to call `fromType.isImplicitlyConvertibleTo(targetType)` like the new one.
