### ISSUE TITLE
Provide 32-bit Windows binaries

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [ethereum/solidity#11681]
windows binaries should be 32bit...

**Comment by cameel** [comment]
32-bit Windows is all but irrelevant by now. Even Microsoft is soon going to [stop offering it on new PCs](https://www.zdnet.com/article/microsoft-takes-a-step-toward-phasing-out-32-bit-pc-support-for-windows-10/). Most hardware it currently runs on is actually 64-bit anyway and fully capable of running a 64-bit OS.

We do not think this is worth the extra maintenance burden. We provide native builds for the most popular platforms (including 64-bit Windows) and on others you can still use the universal emscripten (wasm) binaries. It should also still be possible to build a 32-bit Windows binary from source if you really need it.

**Comment by MyTDT-Mysoft** [comment]
thats a sad reason to not do 64bit... when they only do that because ignorant people allow by not using 32bit software that is superior to all that 64bit crap... either way it will just not provide it as OEM, you can still install... it... and no matter what i wouldnt degrade my i5 using a 64bit OS... but even for a 64bit OS, theres still more benefits to have apps as 32bit... but yes you all use overbloated useles tools to have compatibility and then refuse to have compatibility.... do you understand on how many levels that is retarded? but ok... thanks for the discrimination...

**Comment by chriseth** [comment]
Feel free to compile the binaries yourself. If anything goes wrong, we welcome pull requests.
