### ISSUE TITLE
ICE when assigning to calldata structs and static arrays using inline assembly + `FixedPointType not implemented` error

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#11680]
## Description

In the contract below there seems to be an Internal Compiler Error without a specific message:

pragma abicoder v2;
contract C {
    struct S {
        uint16[] m;
    }
    function f(S calldata s) public pure returns (bool correct) {
        int8 x = int8(int16(s.m[0]));
        uint r;
        assembly {
            s := x
        }
        correct = r == 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80;
    }
}

while in the contract :

pragma abicoder               v2;
contract C {
    function f(fixed a, int16 b, address c, bytes3 d, bool e)
            public pure returns (uint v, uint w, uint x, uint y, uint z) {
        assembly { v := a  w := b x := c y := d z := e}
    }
}

there is the internal compiler error FixedPointType not implemented.

## Environment

- Compiler version: 0.8.6
- Target EVM version (as per compiler settings): 0.8.6+commit11564f7e
- Framework/IDE (e.g. Truffle or Remix): Remic
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 16.04 LTS

**Comment by axic** [comment]
In the first I believe `s := x` must be the culprit (assigning to calldata variable). The second, fixed point types, is an unimplemented feature.

**Comment by cameel** [comment]
Regarding the first one: looks like it's specifically because the codegen assumes that structs and static arrays in calldata won't pass analysis but they actually do:

https://github.com/ethereum/solidity/blob/d655a3c91b02ab571e344b1f02c8e6b8981b374f/libsolidity/codegen/ContractCompiler.cpp#L864-L875

Smaller repro:
```solidity
contract C {
    struct S {
        uint m;
    }

    function f(S calldata s) public pure returns (uint r) {
        assembly {
            s := r
        }
    }
}
```

And for static arrays:
```solidity
contract C {
    function f(uint[3] calldata s) public pure returns (uint r) {
        assembly {
            s := r
        }
    }
}
```
Output in both cases:
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ContractCompiler.cpp(867): Throw in function solidity::frontend::ContractCompiler::visit(const solidity::frontend::InlineAssembly&)::<lambda(const solidity::yul::Identifier&, solidity::yul::IdentifierContext, solidity::yul::AbstractAssembly&)>
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

This started failing in 0.7.5. On 0.7.4 these snippets compile without errors (the first one of course needs the `ABIEncoderV2` pragma).

**Comment by chriseth** [comment]
Is this because you should use `s.offset := r`?
