### ISSUE TITLE
[Codegen] ICE because dynamically sized calldata array's base type is dynamically encoded

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11699]
```
contract C {
  function f(bytes calldata i) external {
    this.f(bytes(string(i[:2])));
  }
}
```

throws

https://github.com/ethereum/solidity/blob/f97fe813ec14edb8580061f0082f30b73affc04d/libsolidity/codegen/CompilerUtils.cpp#L1117-L1122

**Comment by cameel** [comment]
The same bug has already been reported in #11677.
