### ISSUE TITLE
DocStringParsingError in solc version 0.8.6

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#11696]
## Description

In the contract below there seems to be an DocStringParsing Error : "Documentation tag @author not valid for functions". Should this contract be compiled without any errors?

```solidity
contract C {
    /// @author author
    function iHaveAuthor() public pure {}
}
```

## Environment

- Compiler version: 0.8.6
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu LTS 16.04

**Comment by hrkrshnn** [comment]
This is the documented behaviour: https://docs.soliditylang.org/en/v0.8.6/natspec-format.html?highlight=natspec#tags

Closing for now. Feel free to reply.
