### ISSUE TITLE
[Codegen] Legacy codegen does not check for freememptr overflow (beyond UINT64_MAX), Sol->Yul does

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11709]
```
pragma abicoder v2;
contract C {
function f() public {
    uint[][] memory arr = new uint[][](1);
    // This allocation overflows the freememptr
    // which makes Sol->Yul panic with code 0x41.
    arr[0] = new uint[](18446744073709551612);
}
}
// ====
// compileViaYul: also
// ----
// f() -> FAILURE
```

Legacy failure is due to out-of-gas, Sol->Yul is a revert with a modest amount of gas consumed ~21k.

**Comment by bshastry** [comment]
Clubbing a somewhat similar report

```
function exp(uint base, uint exponent) pure returns (uint power) {
if (exponent == 0)
    return 1;
power = exp(base, exponent / 2);
power *= power;
if (exponent & 1 == 1)
    power *= base;
}

contract C {
  function g(uint base, uint exponent) public pure returns (uint) {
  return exp(base, exponent);
  }
}
// ====
// compileViaYul: also
// ----
// g(uint256, uint256): 55558612478609019528521988286241949159871555179327291270583879839857001820084,15045494086288292508913825510347384281681719338099058151627027489948519117802 -> FAILURE
```

passes but with different EVMC status codes

Legacy: Stack underflow
Sol->Yul: Revert

**Comment by axic** [comment]
> passes but with different EVMC status codes
>
> Legacy: Stack underflow
> Sol->Yul: Revert

Hm perhaps it would be a good reason for us to extend isoltest to output `FAILURE (<evmc code>)`.  While the "evmc code" does not matter for mainnet, it is a useful tool to show if the two codegen implementations differ. In some cases we want them to differ, but in others we may not anticipate it.

In this particular case, the "stack underflow" error in the legacy is a bit worrying.

**Comment by bshastry** [comment]
I think the first test case in this thread (out-of-gas vs revert) is due to Sol->Yul inserting a `panic(0x41)` for freememptr overflow that happens due to a very large memory allocation. This panic is part of `finalize_allocation` Yul function. I assume that the legacy code gen does not factor freememptr overflow into account in this scenario.

**Comment by bshastry** [comment]
> Clubbing a somewhat similar report
> 
> ```
> function exp(uint base, uint exponent) pure returns (uint power) {
> if (exponent == 0)
>     return 1;
> power = exp(base, exponent / 2);
> power *= power;
> if (exponent & 1 == 1)
>     power *= base;
> }
> 
> contract C {
>   function g(uint base, uint exponent) public pure returns (uint) {
>   return exp(base, exponent);
>   }
> }
> // ====
> // compileViaYul: also
> // ----
> // g(uint256, uint256): 55558612478609019528521988286241949159871555179327291270583879839857001820084,15045494086288292508913825510347384281681719338099058151627027489948519117802 -> FAILURE
> ```
> 
> passes but with different EVMC status codes
> 
> Legacy: Stack underflow
> Sol->Yul: Revert

Created a new issue for this (see https://github.com/ethereum/solidity/issues/11715) since it is most likely unrelated to free memory pointer overflow that this issue tracks (to be fixed by the linked PR).
