### ISSUE TITLE
[Legacy/Sol->Yul] No compilation mode except optimized Sol->Yul issues a revert due to arithmetic overflow for exponentiation of very large numbers via a simple recursive algorithm

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11715]
```
function exp(uint base, uint exponent) pure returns (uint power) {
  if (exponent == 0)
    return 1;
  power = exp(base, exponent / 2);
  power *= power;
  if (exponent & 1 == 1)
    power *= base;
}

contract C {
  function g(uint base, uint exponent) public pure returns (uint) {
    return exp(base, exponent);
  }
}
// ====
// compileViaYul: also
// ----
// g(uint256, uint256): 55558612478609019528521988286241949159871555179327291270583879839857001820084,15045494086288292508913825510347384281681719338099058151627027489948519117802 -> FAILURE
```

passes but with different EVMC status codes

Legacy: Stack underflow
Sol->Yul: Revert

Edit:

Reproduction

```
$ cp test.sol test/libsolidity/semanticTests/testStackUnderflow.sol
$ isoltest --optimize --show-messages -t semanticTests/testStackUnderflow
```

Ideally, legacy optimizer should also revert for this large exponentiation operation but it does not. Also note that the gas consumption in the legacy optimized call is unusually large (ideally, revert due to arithmetic overflow should occur in an earlier recursion call frame).

Gas table

| Gas consumption | Legacy optimized call | Sol->Yul optimized call |
| --- | --- | --- |
|  | 9223372036854775807  | 34583 |

_Originally posted by @bshastry in https://github.com/ethereum/solidity/issues/11709#issuecomment-887795572_

**Comment by bshastry** [comment]
I'm not able to reproduce this issue independently of the fuzzer. Will reopen if I find a way to. Until then, treating this as a false positive.

**Comment by bshastry** [comment]
Reopening this since it is reproducible via isoltest's `--optimize` flag. See edited OP.

**Comment by bshastry** [comment]
Here's a summary of outcomes for legacy/Sol->Yul with/without opt

| Configuration | Gas cost | EVMC status code (Description) |
| --- | --- | --- |
| Legacy without optimizer | 9223372036854775807  | 6 (Stack underflow) |
| Sol->Yul without optimizer | 9223372036854775807  | 6 (Stack underflow) |
| Legacy with optimizer | 9223372036854775807  | 6 (Stack underflow) |
| Sol->Yul with optimizer | 34583  | 2 (Revert, panic code 0x11) |

So essentially a public facing contract implemented like in original post and compiled with or without optimization (legacy) is vulnerable to gas exhaustion.

Note that the following input pairs revert as expected in all modes: `2, 256` (`2 ** 256`), `3, 256` (`3 ** 256`)

**Comment by hrkrshnn** [comment]
It's probably worth checking how the stack size grows in legacy and ir-optimized. Could you perhaps try to run a debugger and check why the growth is different?

**Comment by bshastry** [comment]
> Could you perhaps try to run a debugger and check why the growth is different?

Remix seems to be a bad idea (browser tab crashes). IR optimized via Remix not possible it seems. I took a shot at reading assembly but the problem is that via IR assembly loses source location to original Solidity code as far as I understood, so it becomes hard to compare.

Optimized legacy asm: https://gist.github.com/bshastry/88fb411affe10ae8b922dab0f67e8e5e

Optimized IR asm: https://gist.github.com/bshastry/02111006987b419a3b39382722914103

**Comment by bshastry** [comment]
Minor update:

Optimized legacy debugging shows that:
  - each level of recursion consumes 4 stack slots on average, 9 slots per frame is the maximum
  - stack frame values follow the following pattern for exp(2, 256)
    - 0x100, 0x02, <callsite_return>, 0x00
    - the last `0x00` is presumably an empty stack slot reserved for return value
  - if `exponent > exp(2, 253)`, worst case stack consumption is `1024 = 253 * 4 + 9 + 3` where `4` is stack slots consumed per recursion, `9` is the max stack consumption for the 254th recursion, and `3` is stack slots for the top-most call `g(base, exponent)`

tl;dr For optimized legacy code, greater than 253 recursions can trigger stack-underflow (out-of-stack).

**Comment by bshastry** [comment]
| Configuration | Reverts upto (base = 2, exp = 2^p) where 0 <= p <= 255 |
| --- | --- |
| Legacy without optimizer | 251 |
| Sol->Yul without optimizer | 250 |
| Legacy with optimizer | 251 |
| Sol->Yul with optimizer | 253 |

So, it looks like maximum recursion depth before out-of-stack is only marginally different across configurations. One hypothesis is that average stack allocation per recursive call does not differ significantly between these configurations. However, worst-case stack consumption does and this is the reason some configurations run out of stack sooner than others.

**Comment by bshastry** [comment]
Here's the most recursive test case currently only passed (returns successfully) by optimized IR.

```
function exp(uint base, uint exponent) pure returns (uint power) {
  if (exponent == 0)
    return 1;
  power = exp(base, exponent / 2);
  power *= power;
  if (exponent & 1 == 1)
    power *= base;
}

contract C {
  function g(uint base, uint exponent) public pure returns (uint) {
    return exp(base, exponent);
  }
}
// ====
// compileViaYul: true
// ----
// g(uint256,uint256): 0x1, 0x2000000000000000000000000000000000000000000000000000000000000000 -> 1
```

**Comment by bshastry** [comment]
Summary before closing because this issue turned out to be a minor difference in stack allocation that affects different configurations slightly differently.

- Different configurations run out of stack at different levels of recursion
- Best case (most number of recursive calls) is optimized IR (solves `1 ** (2 ** 253)` i.e., 1 to the power of 2 to the power 253)
- Second best are optimized and unoptimized legacy (solves `1 ** (2 ** 251)`)
- Last is unoptimized IR (solves `1 ** (2 ** 250)`)

**Comment by hrkrshnn** [comment]
> each level of recursion consumes 4 stack slots on average, 9 slots per frame is the maximum

@bshastry Do you know how the stack grows in legacy v/s ir? I'm interested in knowing by how many elements the stack grows on each recursive call.

**Comment by bshastry** [comment]
> > each level of recursion consumes 4 stack slots on average, 9 slots per frame is the maximum
> 
> @bshastry Do you know how the stack grows in legacy v/s ir? I'm interested in knowing by how many elements the stack grows on each recursive call.

Legacy grows by 4 slots per recursive call. I don't know about IR though. But my guess is that it grows about the same (see table above: https://github.com/ethereum/solidity/issues/11715#issuecomment-891727099). If optimized IR were to take one slot fewer per recursive call, it would easily return the output of `1 ** (2 ** 255)` but the fact that it doesn't makes me believe that it is actually a matter of a handful of stack slots difference and definitely not an order of magnitude.
