### ISSUE TITLE
[CLI] Make more settings optional in `CommandLineOptions`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11727]
Continuation of the refactor from #11518.

## Abstract
Many options in `CommandLineOptions` have a value even if they are not specified on the command line. In some cases the default value is intentional, in others it's simply left at that because the value is irrelevant. Sometimes there's a special value use to indicate that the setting is not initialized.

1) The main task here is to use `optional<>` for settings that have no meaningful value if not initialized:
    - `input.basePath`
    - `output.dir`
    - `compiler.outputs`
    - `modelChecker.settings` (and `modelChecker.initialize` should be removed)
2) There are also some enums that do not make sense in all input modes. I'd make them optional too but I think it would be best to use `nullopt` for them only if they are irrelevant (and require them not to be specified in that case: #11629). I'd have `CommandLineParser` still initialize them with a default if they are relevant but were not specified:
    - `output.revertStrings`
    - `output.stopAfter`
    - `assembly.targetMachine`
    - `assembly.inputLanguage`
    - `metadata.hash`

    Alternatively maybe just the whole structs like `assembly` or `metadata` should be optional here. I think that's preferable at least for `assembly` and `metadata` structs.

The list of fields given above is not exhaustive and might not be up to date - please take a look at the `CommandLineOptions` struct before starting this task and see if there's anything more to add.

**Comment by v-sreekesh** [comment]
Hi @cameel i would like to work on this issue could you let me know where i can find the resources

**Comment by cameel** [comment]
Hello, sorry for a late response, I was off last week. Do you mean the source code? These settings are defined in [`solc/CommandLineParser.h`](https://github.com/ethereum/solidity/blob/develop/solc/CommandLineParser.h). And overall most of your changes will probably be in [`solc/`](https://github.com/ethereum/solidity/tree/develop/solc).
