### ISSUE TITLE
Allow unchecked increments of for loops indexes

### ISSUE THREAD

**Issue by The-3D** [ethereum/solidity#11721]
## Abstract

After the (welcomed) introduction of the checked math operators in solidity 0.8.x, developers can allow safe unchecked operations by wrapping them in a `unchecked {}` block. Safety checks of course apply to pre and post increment/decrement operators (++/--) which are commonly used to increase indexes in for loops; unfortunately the safety checks in this case are enabled by default, and there is no way of disabling it in a developer friendly way. This may force to refactor the for loop in a while, or change the for increment in an unnatural way. Not doing it can get (very) expensive.

## Motivation

Loops are in most cases bounded by definition (the bounding is represented by the exit condition). Therefore in the vast majority of cases, checking for overflows is really not needed, and can get very gas expensive. Consider the following examples:

```
pragma solidity ^0.8.0;

contract Test1 {
    
    
    function loop() public pure {
        
        for(uint256 i = 0; i < 100; i++) {
        }
        
    }
}
```
```
pragma solidity ^0.8.0;

contract Test {
    
    
    function loop() public pure {
        
        for(uint256 i = 0; i < 100;) {
            
            unchecked {
                i++;
            }
        }
        
    }
}
```
`loop()` in Test1 costs more than 31K gas, vs 25.5K gas for `loop()` in Test2

## Specification

allow to specify unchecked increments in for loops as follows

`for(uint256 i = 0; i < 100; unchecked i++)`

**Comment by hrkrshnn** [comment]
This has been proposed and discussed in https://github.com/ethereum/solidity/issues/10698 and https://github.com/ethereum/solidity/issues/10695

**Comment by chriseth** [comment]
The solution for now is to define a function `function uncheckedInc(uint x) pure returns (uint) { unchecked { return x + 1; } }` and use it as
```
 for(uint256 i = 0; i < 100; i = uncheckedInc(i) {
    ...
  }
```
