### ISSUE TITLE
Mutation testing support for Solidity

### ISSUE THREAD

**Issue by ameten** [ethereum/solidity#1172]
With the failure of TheDAO, it became evident that writing even a relatively simple smart contract correctly is a challenging task even for the most experienced developers. We should write unit tests and a formal specification to verify the smart contract code, but unit tests do not cover all the code sometimes and the formal specification can be as complicated as the implementation itself. How can we be sure that the unit tests check everything in the code and that the formal specification fully defines the code? The answer is mutation testing.

We create a mutated smart contract, namely a smart contract where one operation is changed comparing to the original one. We run all the unit tests against the mutant. If all unit tests pass then they certainly do not check the place we have changed in the mutant. We formally verify the mutant using the formal specification. If the mutant passes the formal verification, it means that the specification is not good enough.

We cannot directly mutate a smart contract already compiled into EVM instructions since it is not evident how we can separate instructions implementing business logic from instructions implementing language constructions like methods, blocks. We don't want mutationally test Solidity compiler, we want to test business logic of a smart contract.

Therefore, we need that Solidity compiler produces mutants changing primitive operations at the moment when EVM code is generated.

Tasks:
- Add new option to Solidity compiler so that it produces a list of mutants instead of code for the original contract.
- Add debug information about mutants, namely what operation was mutated and where.
- Add mutations like changing arithmetic or logic operation.

Discussions:
To keep the first iteration of development feasible, we can concentrate on mutants of the first order, i.e. only one place in a smart contract is mutated, and on very primitive mutations.

This issue implements the following idea: https://hack.ether.camp/idea/mutation-testing-for-solidity

**Comment by pirapira** [comment]
I think it's a good idea to mutate the code so that we can evaluate and strengthen the unit tests.  Tasks are also clear.

Is this issue still open for anyone to implement?

**Comment by ameten** [comment]
I am looking to build a team to implement it as part of the online hackathon on hack.ether.camp. but if anybody just implement it outside of the hackathon, I would not mind.

**Comment by pirapira** [comment]
I see.  This is indeed a good target for a hackathon.

**Comment by ameten** [comment]
Join the team :)

**Comment by chriseth** [comment]
@ameten nice idea! Did you already think about at which lever you want the mutations to take place?
I'm actually using [libfuzzer](http://llvm.org/docs/LibFuzzer.html) to do something similar with the compiler itself. Libfuzzer operates cleverly on the actual source code byte representation. For this task, mutations still have to compile correctly, which is a certain challange.

**Comment by pirapira** [comment]
@chriseth the mutations would be done in the AST level, not on the source text.  There are low-hanging fruits like negating `if` conditions, swapping `<` and `<=`, etc.

**Comment by ameten** [comment]
Hi @chriseth, if it was not an item for Solidity compiler, souce code manipulation would be an option. Just replace one operator with another and use the manipulated source as input for the Solidity compiler. It is similar to the approach for test coverage: https://blog.colony.io/code-coverage-for-solidity-eecfa88668c2#.vx9uuc5ra . But we still need to do some scanning and parsing to be able to manipulate the source code. Why would we need to implement it separately, if we should have it already in the compiler? Also, support from tools like Truffle is not evident with such approach.

So, I agree with @pirapira that mutation should be done closer to generation of EVM code. I am not sure what information is stored into AST in the Solidity compiler, but we shall need not only syntax information, but semantic, too, to know what type of operator we are observing and select relevant list of possible mutations.

On the other hand, we cannot loose all information about source code itself, since we need to provide a clue about a mutant back to developer. At least line number and column where mutation was applied and what kind of mutation.

**Comment by pirapira** [comment]
@ameten The AST nodes are equipped with the line and column information.

**Comment by chriseth** [comment]
I agree that you should re-use the existing tools inside the solidity compiler and since the AST inside the compiler is not meant to be modified, probably the best way is to create the full AST, analyze it, find a place and way to modify, but perform the modification to the source code itself. If you find it too hard to do the changes to the compiler itself, you can also use its json ast output. There are some tools in the [remix repository](https://github.com/ethereum/remix) to do AST analysis.

**Comment by axic** [comment]
If possible, we should encourage using the JSON AST output. If that means it should be fixed, extended or be more stable, so be it. It will be beneficial in the long term I think.

**Comment by ameten** [comment]
@pirapira, @chriseth, @axic! I have implemented the most simple mutations!

**Comment by agroce** [comment]
As an alternative, https://github.com/agroce/universalmutator will mutate .sol files, creating source variants, and use solc to check "trivial compiler equivalence" -- that is, any mutants that create equivalent bytecode to the original file, or to each other, are removed so you get a set of valid, different, mutants.  The solidity-specific mutators are limited (but easily extended), but the generic "any language" and "C-like" mutators handle a lot of what you would want.

**Comment by axic** [comment]
@chriseth @bshastry can we consider the protobuf based buffer is somewhat accomplishing this? Do we need to keep this issue? @bshastry can you get some inspiration from these comments?

**Comment by chriseth** [comment]
I don't think this is related to what we do now with protobuf.

**Comment by bshastry** [comment]
Some notes
  - The AST mutation seems to be targeted at Solidity contracts, not the compiler itself. I am not sure how this infrastructure could be reused to test the compiler.
  - As noted in #1406 the protobuf spec currently targets yul/strict assembly and not solidity
  - We may want to try this https://github.com/agroce/universalmutator 
     - it generates mutants A and B (solidity programs) that are semantically equivalent
     - the compiler generated bytecode for A and B must leave the same trace, otherwise there's a bug in the compiler, assuming the mutation logic itself is not buggy

**Comment by agroce** [comment]
> Some notes
> 
> * The AST mutation seems to be targeted at Solidity contracts, not the compiler itself. I am not sure how this infrastructure could be reused to test the compiler.
> * As noted in #1406 the protobuf spec currently targets yul/strict assembly and not solidity
> * We may want to try this https://github.com/agroce/universalmutator
>   
>   * it generates mutants A and B (solidity programs) that are semantically equivalent
>   * the compiler generated bytecode for A and B must leave the same trace, otherwise there's a bug in the compiler, assuming the mutation logic itself is not buggy

Not sure what you mean... the universalmutator won't usually produce semantically equivalent mutants, and when it does this is tough to know.  I guess given compiler version X that compiles A and B to same bytecode, you could check if Y also does.  But the answer might be hard to interpret...  I suppose if (1) Y does so, and (2) the bytecodes can behave different, then either X or Y is buggy...

**Comment by bshastry** [comment]
> Not sure what you mean... the universalmutator won't usually produce semantically equivalent mutants, and when it does this is tough to know.

Okay, I don't know why I assumed mutants would be semantically equivalent, my bad.

> I guess given compiler version X that compiles A and B to same bytecode, you could check if Y also does. But the answer might be hard to interpret... I suppose if (1) Y does so, and (2) the bytecodes can behave different, then either X or Y is buggy...

Hmm... this is not in our threat model at the moment but it could be at a later point. I think we are presently only interested in generating semantically equivalent test cases for a fixed compiler version. CC @chriseth

**Comment by agroce** [comment]
Yeah, we actually try to filter out all the equivalent mutants!  It might be an interesting task though, and you could write rules in the regexp-defined style universalmutator uses, and just apply that rule file...

**Comment by agroce** [comment]
Do you have in mind transformations that preserve semantics of interest?  Peppering all numeric literals with +0 is not very interesting.

**Comment by bshastry** [comment]
> Yeah, we actually try to filter out all the equivalent mutants! It might be an interesting task though, and you could write rules in the regexp-defined style universalmutator uses, and just apply that rule file...

Nice, although I'm not sure if regexp is well-suited to create interesting semantically equivalent filters. As you said, `+0` is not very interesting.

Type casts [1] are an interesting pattern worth investigating. Perhaps it is better suited for writing a regexp rule even.

[1] https://github.com/ethereum/solidity/issues/4893

**Comment by chriseth** [comment]
This can now be accomplished by external tools through the ast export / import.
