### ISSUE TITLE
solc dosent have use command

### ISSUE THREAD

**Issue by shawnwbts** [ethereum/solidity#11722]
Use the following installation command to install solc on Linux server:
**sudo add-apt-repository ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install solc**

and I installed solc-select  
Why is there no  **solc use** command to convert the version of solc now?

**Comment by hrkrshnn** [comment]
Maybe this question is more appropriate at https://github.com/crytic/solc-select?

**Comment by hrkrshnn** [comment]
I'm closing this for now. Feel free to ask in https://app.element.io/#/room/#ethereum_solidity:gitter.im or  https://gitter.im/ethereum/solidity if you need more help.

**Comment by chriseth** [comment]
We do not support mulitple versions on ubuntu, since the ppa system is not designed to support multiple versions of the same software.
