### ISSUE TITLE
[Gas usage] Legacy try-catch recursive call with limited gas succeeds while Sol->Yul does not

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11724]
```
contract C {
function g() public returns (bool) {
    try this.g{gas: 20000}() {
        return true;
    } catch {
        return false;
    }
}
}
// ====
// compileViaYul: also
// ----
// g() -> true
```

This may be a false positive because of gas requirement for the recursive function changing across legacy/Sol->Yul but filing it since I'm not sure of this hypothesis.

**Comment by bshastry** [comment]
| Gas consumption | Legacy call | Sol->Yul call |
| --- | --- | --- |
|  | 41994 | 42278 |

**Comment by hrkrshnn** [comment]
I think it's simply that non-optimized Yul code takes more than 20000 gas. So the first `this.g{gas: ...}()` call fails in the non-optimized Yul case.

**Comment by bshastry** [comment]
> I think it's simply that non-optimized Yul code takes more than 20000 gas.

Oh, I thought isoltest runs optimized Yul mode if `compileViaYul` is true. Hmm... I could reproduce this even on optimized Sol->Yul code on the fuzzer harness though.

**Comment by hrkrshnn** [comment]
For isoltest run with `--optimize`, I'm not able to reproduce this.

**Comment by bshastry** [comment]
> For isoltest run with `--optimize`, I'm not able to reproduce this.

You are right, I was not aware of the `--optimize` option. With `--optimize`, it's actually flipped (legacy optimized -> false, Sol->Yul optimized true) which is a good thing I suppose (i.e., Sol->Yul optimization requires lesser gas to complete the call).

```
contract C {
  function g() public returns (bool) {
    try this.g{gas: 7000}() {
      return true;
    }
    catch {
      return false;
    }
  }
}
// ====
// compileViaYul: also
// ----
// g() -> false
```

Edit:

Gas table

| Gas consumption | Legacy call | Sol->Yul call |
| --- | --- | --- |
|  | 28609 | 28758 |

**Comment by bshastry** [comment]
Closing since this is a gas throttling issue.
