### ISSUE TITLE
[CLI] Consolidate exception handlers in `CommandLineInterface`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11732]
Related to #10295 and #11731.

Currently there are lots of independent `try`/`catch` statements inside various functions of `CommandLineInterface`. In most (if not all) cases they just print the error message and exit. In some cases this results in exceptions being silenced too eagerly, in others exceptions are not caught at all and can terminate the application without a sensible error message.

There should really be just a single error handler of this kind and it should reside at the very top-level of the hierarchy where printing and exiting is the default action for stuff that was not handled at lower levels. At lower levels the exceptions should be free to escape and interrupt the processing. Most `try`/`catch` blocks should only perform cleanup (if any is necessary at all) and then rethrow the exception so that the top-level handler can deal with it.

The top-level handler should be placed inside `main()` (like in #10295).

**Comment by s0sharma** [comment]
Hi, I would like to work on this, can you suggest me ways to get started?

**Comment by cameel** [comment]
Great!

- Take a look at [`CommandLineInterface.cpp`](https://github.com/ethereum/solidity/blob/develop/solc/CommandLineInterface.cpp). There are lots of `catch` handlers there.
- Find and remove all the generic handlers for things like `...`, `std::exception`, `util::Exception` or `InternalCompilerError`.
    - If a handler is doing more than just printing (e.g. it modifies a variable) remember to preserve it and just rethrow the exception.
- Leave the more specific handlers ones like `Error`, `CompilerError` or `UnimplementedFeature` alone. You could still reduce the scope of their `try` block though - `try` blocks for those should cover as little code as possible.
- Add a `try`/`catch` block in [`main.cpp`](https://github.com/ethereum/solidity/blob/develop/solc/main.cpp). You can take that part from #10295. Handle all these generic cases there by printing a message and any diagnostic info you can find.
- There might be some cases that need to handled specially but don't worry about that. If you miss any, we'll sort that out in the review of the PR.
- Make sure tests pass.
    - This code is covered mostly by command-line tests that you can run with `test/cmdlineTests.sh` script.

**Comment by s0sharma** [comment]
Thanks for your reply I will be working on this.

**Comment by s0sharma** [comment]
While testing file I am getting errors, so where can I ask for help or communicate with other members of the community?

**Comment by cameel** [comment]
You can find us on the #solidity-dev channel ([Element](https://app.element.io/#/room/#ethereum_solidity-dev:gitter.im), [Gitter](https://gitter.im/ethereum/solidity-dev)).

**Comment by s0sharma** [comment]
I have made the changes, please review the [code]. (https://github.com/ethereum/solidity/pull/11762)
