### ISSUE TITLE
[CLI] Separate control flow from error reporting in `CommandLineParser`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11731]
This is a continuation of the CLI refactor from #11518. Getting rid of `exit()` was suggested in the review.

Currently [`CommandLineParser`](https://github.com/ethereum/solidity/blob/develop/solc/CommandLineParser.h) uses the mechanism inherited from `CommandLineInterface` to report errors - it prints a message to the error stream and returns `false`.

- This is too inflexible in some situations - for example it can't return a value that will make the application exit without reporting an error so when it wants ro do so, it just calls `exit()` which terminates the application.
- Sometimes errors are returned in nested calls and the return value has to be bubbled up, which is error prone (see for example https://github.com/ethereum/solidity/pull/11544#discussion_r669767594).
- It also makes the code overly verbose - returning an error takes several lines of code (braces, printing to `serr()`, returning). Throwing exceptions would be more concise.

Here's my proposal on how to refactor this:

1) Modify `CommandLineInterface` so that the return value from the parser only indicates whether it should continue processing (`true`) or immediately exit without error (`false`).
    - Modify the functions that print version and license info in `CommandLineParser` to make them not use `exit()`.
    - Consider moving all of the printing logic to `CommandLineInterface`. The parser should only signal that printing was requested on the command line, not perform the action. This would be more in line with the purpose of the class and would let us get rid of the `sout()` stream form it.
2) Define an exception type that represents a command line validation error.
    - Replace all the code that prints to `serr()` and returns `false` with throwing that exception.
        - Remember to use `BOOST_THROW_EXCEPTION` macro.
    - Remove the `serr()` stream from the parser.
    - Consider defining a whole exception hierarchy and moving message formatting to specific exception classes. The parser could then be leaner and simply pass in the raw info needed to construct the message (file names, option names, option values, etc).
3) Catch the validation error in `CommandLineInterface` and handle it by printing the message to stderr and exiting with an error code.
    - Move the existing handler for `boost::program_options::error` from `CommandLineParser::parse()` to `CommandLineInterface` too. They're the same kind of error and should really be handled the same way.

**Comment by Midhun07** [comment]
Hi @cameel. I would like to work on this issue.

**Comment by cameel** [comment]
@Midhun07 This one is actually taken. @spiyer99 is working in it and has already submitted a PR (still work in progress though). I tried to assign him earlier to make this apparent but github won't let me - I think I can only do that if someone has commented in the issue.
