### ISSUE TITLE
Inline assembly: throw keyword or ErrorTag as a jump label (new feature)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1174]
Option 1: introduce a new keyword, which is a jump to the errortag:

```
assembly {
  throw
}
```

Option 2: expose the `ErrorTag` as a jump label to inline assembly:

```
assembly {
  jump(ErrorTag)
}
```

**Comment by chriseth** [comment]
`define throw() { jump(invalidLabel) }`

**Comment by chriseth** [comment]
As we will have functions soon, this can be closed. Inline assembly should have as few built-in features as possible to remain as flexible as possible.
