### ISSUE TITLE
Do not create empty superfluous `err`, `output` and `exit` files when auto-updating command-line test expectations

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11753]
This came up in https://github.com/ethereum/solidity/pull/11738#discussion_r684159827

When the [`cmdlineTests.sh`](https://github.com/ethereum/solidity/blob/develop/test/cmdlineTests.sh) script gets no output from the compiler, it accepts both an empty `output` file as well as the file not being there at all. Same with stderr and the `err` file. In case of `exit` file, it not being present is equivalent with expecting a return code of `0`.

If the compiler output does not match the expectations, the script can update the content of these files but then it always creates them even if they are empty. It would be better if instead it did not and if it deleted them if they already exist.

Command-line tests can be found in [test/cmdlineTests/](https://github.com/ethereum/solidity/tree/develop/test/cmdlineTests).

**Comment by priyansh786** [comment]
Hi I'd like to work on this issue.

**Comment by cameel** [comment]
Great! If you need help with the task please drop by at the `#solidity-dev` [Matrix](https://app.element.io/#/room/#ethereum_solidity-dev:gitter.im)/[Gitter](https://gitter.im/ethereum/solidity-dev) channel.
