### ISSUE TITLE
[DOCS] Use calldata whenever that is sufficient in solidity-by-example section

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11767]
```solidity
    /// Reveal your blinded bids. You will get a refund for all
    /// correctly blinded invalid bids and for all bids except for
    /// the totally highest.
    function reveal(
        uint[] memory _values,
        bool[] memory _fake,
        bytes32[] memory _secret
    )
```

Changing `memory` to `calldata` for this example is better.

Unless the code explicitly requires the argument to be in memory, and doesn't modify the argument, keeping it in calldata is more efficient gas wise. 

There are a couple of other places in the documentation that could use this change.

**Comment by v-sreekesh** [comment]
Hi @hrkrshnn could you link me to the location of the file i would like to help with this issue

**Comment by hrkrshnn** [comment]
@v-sreekesh https://docs.soliditylang.org/en/latest/solidity-by-example.html#id2

**Comment by v-sreekesh** [comment]
Hi @hrkrshnn i have made the changes could you review and let me know thanks

**Comment by hrkrshnn** [comment]
Other examples


 `constructor(bytes32[] memory proposalNames) `

Functions in `contract ReceiverPays` and `contract SimplePaymentChannel` can also be changed. But this requires some knowledge about how data is encoded in calldata, so probably out of scope for a "good first issue"

**Comment by v-sreekesh** [comment]
> Other examples
> 
> `constructor(bytes32[] memory proposalNames) `
> 
> Functions in `contract ReceiverPays` and `contract SimplePaymentChannel` can also be changed. But this requires some knowledge about how data is encoded in calldata, so probably out of scope for a "good first issue"

Can I refer some resources online for further understanding to fix this issue

**Comment by hrkrshnn** [comment]
@v-sreekesh Maybe https://docs.soliditylang.org/en/v0.8.7/types.html?highlight=calldata#data-location?

I would recommend running the example in remix, and seeing how the gas changes when `memory` is replaced by `calldata. If you are keen, you can try to run the debugger on and see the differences.

**Comment by v-sreekesh** [comment]
> @v-sreekesh Maybe https://docs.soliditylang.org/en/v0.8.7/types.html?highlight=calldata#data-location?
> 
> I would recommend running the example in remix, and seeing how the gas changes when `memory` is replaced by `calldata. If you are keen, you can try to run the debugger on and see the differences.

Will check and compare the difference in remix for gas consumption

**Comment by hrkrshnn** [comment]
Mostly done in https://github.com/ethereum/solidity/pull/11772. So closing
