### ISSUE TITLE
Include grammar.txt in the documentation

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1176]
This issue is a spin-off of @chriseth's [comment](https://github.com/ethereum/solidity/issues/315#issuecomment-242554903).  The proposal is to include grammar.txt in the documentation and to list the reserved keywords in the same section.

**Comment by axic** [comment]
Cannot we just add a link to grammar.txt in the documentation? Seems to make more sense to me as the data is not duplicated.
