### ISSUE TITLE
[DOCS] Change examples from public to external whenever possible

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11768]
To start with, https://docs.soliditylang.org/en/latest/solidity-by-example.html contains the most important examples.

Unless a function is called from within the contract, there is no need for it to be `public`. Changing it to external is clearer and should be recommended to the users.

**Comment by v-sreekesh** [comment]
Hi @hrkrshnn I would like to work with this issue

**Comment by hrkrshnn** [comment]
@v-sreekesh Great. I'll assign you now. Feel free to ask here or on https://app.element.io/#/room/#ethereum_solidity-dev:gitter.im (or the equivalent gitter channel) if you have questions.

**Comment by alice-dfi** [comment]
What does it need to be taken off public ?

**Comment by v-sreekesh** [comment]
Hi @hrkrshnn I have made the changes for the remaining examples and used the same branch and also fixed https://github.com/ethereum/solidity/issues/11767 as well could you have a look and let me know the changes to be made if any?
