### ISSUE TITLE
When basefee is supported?

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#11778]
London is out, but there is no compiler to write code to use the new `basefee` opcode.

When is 0.8.7 released ?

**Comment by hrkrshnn** [comment]
Hopefully today!

**Comment by hrkrshnn** [comment]
If you *really* want to use basefee immediately, then the section "Verbatim in Yul" in https://blog.soliditylang.org/2021/06/10/solidity-0.8.5-release-announcement/ shows how to do it. Note that it's only available in pure Yul, i.e., not via inline assembly.

Closing this. Feel free to reply if you have questions.

**Comment by drortirosh** [comment]
Verbatim yul is not an option, but I'll be happy to wait one more day..
