### ISSUE TITLE
Why3: pragma not supported

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1177]
```
Untitled:1:1: Error: Code not supported for formal verification.
pragma solidity ^0.4.0;
^---------------------^
```

**Comment by axic** [comment]
@pirapira @chriseth I think this should be fixed for the next release.

**Comment by pirapira** [comment]
Yes.  I think I can silently drop these errors for pragmas.

**Comment by axic** [comment]
This also triggers the comment: we should have basic tests for the why3 output, so that such breaking changes won't be left unnoticed.

**Comment by pirapira** [comment]
#1180 for the basic tests.
