### ISSUE TITLE
EVM: annotated opcode output

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1178]
We've discussed a possible annotated opcode output with @pirapira and the idea is to have a simple text format:
- each opcode is on a single line and no whitespaces are allowed around opcodes
- empty lines are allowed
- comments are denoted by a line starting with `;;` 
- the format starts with `;; annotated_evm_output`
- assertions for verification are stored as `;; assert:`
- multiple assertion lines between opcodes are joined with logical conjunction

Format within assertions:
- conjunction is represented as `/\`
- disjunction is represented as `\/`
- parentheses are allowed to group statements
- (syntax of statements to be described by @pirapira after an experiment https://github.com/pirapira/evmverif/issues/5)

```
;; annotated_evm_output
PUSH1 0x60
PUSH1 0x40
PUSH1 0x60
PUSH1 0x40

;; we know the stack height here
;; assert: length stack > 3

;; we know the top element must be one of these
;; assert: (stack 0 = caller) \/ (stack 0 = balance)
MUL
```

**Comment by axic** [comment]
I wonder if this could be merged with the assembly output, but that has other syntax elements:
- tags
- offset within data "segment"
- several different push statements:
  - `PUSH [$00000000…00000000]` - offset of data segment 0
  - `PUSH #[$00000000…00000000]` - length of data segment 0
  - `PUSH [tag1]` - tag offset
  - `PUSH [ErrorTag]` - special hardcoded errortag (not present in the assembly output)
  - `PUSHLIB A` - placeholder for library A
- annotated jump statment:
  - `JUMP   [out]`

**Comment by pirapira** [comment]
@axic Yes, this kind of information is useful for many tools.  I would add this as additional comments, even when they seem redundant.

I prefer a line

```
PUSH 0x2 ;; PUSH [ErrorTag]
```

rather than just

```
PUSH [ErrorTag]
```

In other words, when we strip away the comments and redundant whitespaces from the rich opcodes, we should get the plain simple `--opcode` output.  In this way, we can make sure what's analyzed = what's deployed.

**Comment by chriseth** [comment]
I think defining a new language will rather slow us down, we should strive for embedding existing languages as annotations (coq might  be a choice as @pirapira mentioned). Furthemore, all examples you gave are human-readable output, although I think this should be mainly machine-readable. The question is also how to get from Solidity to annotated assembly - we need a way to specify those annotations in the high level code. If we only allow annotating assembly itself, we will not get very far.

Note that things like `PUSH [ErrorTag]` is actual assembly - the value of the error tag is not know before the assembly stage.

**Comment by pirapira** [comment]
The design of this language is covered by #1128.  The current issue looks bigger, containing the implementation.

**Comment by pirapira** [comment]
@chriseth I need the value of `[ErrorTag]` in the bytecode verification.  So, the assembly is not useful I guess.  I need the annotated bytecode for the bytecode verification, but a sequence of opcodes are also fine.

**Comment by pirapira** [comment]
@chriseth `get from Solidity to annotated assembly` yes, we will need a way to translate annotations in the source code into annotations in the bytecode.

I will translate annotations after I can deal with annotated bytecodes.  Currently, verification of bytecode takes much more time than writing bytecode by hand.  So, the cost of writing the bytecode by hand is not relevant at this point.  Most of the labor is currently spent on writing the proofs, and I need to reduce that first.

**Comment by pirapira** [comment]
I think I pick Isabelle/HOL not Coq.  In Coq a proof [takes 300 lines](https://github.com/pirapira/evmverif/blob/master/coq/example/call_but_fail_on_reentrance.v#L121) while in Isabelle/HOL just [40 lines](https://github.com/pirapira/eth-isabelle/blob/master/example/FailOnReentrance.thy#L102).  The Isabelle/HOL proof looks much easier to automate because it's very repetitive.

**Comment by pirapira** [comment]
In Isabelle/HOL, this kind of assertions can now be discharged automatically.

```
  Stack (PUSH_N [0]) #
  Stack (PUSH_N [0]) #
  Storage SSTORE #
  Annotation (λ aenv. aenv_storage aenv 0 = 0)
```

**Comment by pirapira** [comment]
Here is the design.  An Isabelle/HOL assertion

```
SSTORE
;; isabelle_assert: <line 1>
;; isabelle_assert: <line 2> ...
STOP
```

should produce a valid Isabelle/HOL theory file when they are thrown into this template

```
theory Dummy
imports Main "~~/src/HOL/Word/Word"
begin

type_synonym uint = "256 word"
type_synonym address = "160 word"
type_synonym byte = "8 word"

type_synonym memory = "uint ⇒ byte"
type_synonym storage = "uint ⇒ uint"

(* The environment visible for annotations *)
record aenv =
  aenv_stack :: "uint list"
  aenv_memory :: memory
  aenv_storage :: storage
  aenv_balance :: "address ⇒ uint"
  aenv_caller :: address
  aenv_value_sent :: uint
  aenv_data_sent :: "byte list"
  aenv_storage_at_call :: storage
  aenv_balance_at_call :: "address ⇒ uint"
  aenv_this :: address

definition dummy :: "aenv => bool"
where
"dummy aenv =
<line 1>
<line 2>
"
```

**Comment by pirapira** [comment]
@chriseth says it's easier to produce a string that can be copied and pasted into Isabelle/HOL.

**Comment by chriseth** [comment]
I'm just saying that we own the compiler, so we can modify its output to our liking and even create a new output class, just as we did for why3.

**Comment by pirapira** [comment]
OK, then "it's easier" was just my thought.

**Comment by pirapira** [comment]
- [ ] output in Isabelle/HOL format #1222
- [ ] automatically produce bytecode annotations that prevent overflows
- [ ] translate user annotations into bytecode annotations

**Comment by chriseth** [comment]
@pirapira is this still relevant?

**Comment by pirapira** [comment]
Maybe not.  We've found a cleverer solution with the invalid opcode.
