### ISSUE TITLE
Nested brackets in optimizer sequences

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11809]
Requested in https://github.com/ethereum/solidity/pull/11794#issuecomment-898255073

Yul optimizer has a setting that determines the sequence of [steps](https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-steps) to run on the code. Each step is represented by a single character and the sequence can contain brackets. The bracketed part is repeated until the optimized code stops changing.

For example this command:
```bash
solc --optimize --ir-optimized --yul-optimizations 'dhfoD[xarrscLMcCTU]uljmul'
```
will make the optimizer first execute `dhfoD` once, then `xarrscLMcCTU` in a loop, and finally `uljmul` once.

Currently nested brackets are not allowed so something like `dhfoD[x[arr[s][cL]McCT]U]ul[jm[ul]]` is not a valid sequence. The goal of this task is to allow brackets to be arbitrarily nested.

### Implementation notes
[The code responsible for validating and executing the sequence is in `Suite.cpp`](https://github.com/ethereum/solidity/blob/v0.8.7/libyul/optimiser/Suite.cpp#L270-L342). The task involves rewriting it to use a stack or making it recursive. No significant changes should be required outside that part other than maybe adjusting some tests.

**Comment by v-sreekesh** [comment]
Hi @cameel i would like to work on this issue could you pls assign me

**Comment by Tanya1999-cmyk** [comment]
Hi, I'd like to work on this issue.

**Comment by cameel** [comment]
@Tanya1999-cmyk There's already a PR for this issue by @v-sreekesh and he's actively working on it.

Maybe you'd like to try #9627, which is another small task related to the optimizer sequences?
