### ISSUE TITLE
[LoadResolver] Invalid gas tier for instruction CREATE

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11801]
```
{
  for {} addmod(keccak256(0x0,create(0x0, 0x0, 0x0)), 0x0, 0x0) {} {}
}
// ----
// step: loadResolver
//
```

throws

https://github.com/ethereum/solidity/blob/1a68228c28e4e7f7a62e32cb310bce6377565aac/libevmasm/GasMeter.cpp#L272

**Comment by bshastry** [comment]
```
for {} addmod(keccak256(sload(0x0),0x0), 0x0, 0x0) {} {}
```

throws the same assertion for `sload`.

**Comment by chriseth** [comment]
Essentially duplicate of https://github.com/ethereum/solidity/issues/11803
