### ISSUE TITLE
dataoffset is unimplemented in GasMeter

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11803]
```
object "object0"
{
  code {
    for {} addmod(keccak256(dataoffset("object0"),0x0), 0x0, 0x0) {} {}
  }
}
// ----
// step: loadResolver
//
```

throws

https://github.com/ethereum/solidity/blob/c0a9578979db59667eb8ae31814547c86ba95453/libyul/backends/evm/EVMMetrics.cpp#L86

**Comment by chriseth** [comment]
I think this class was never meant to cover all possible code (please re-check). @hrkrshnn can you check if you need the gas meter to really implement the evaluation of the arguments to `keccak` or is it really just about the length of the keccak operation? (cf. `LoadResolver::tryEvaluateKeccak` )

**Comment by hrkrshnn** [comment]
> can you check if you need the gas meter to really implement the evaluation of the arguments to keccak

This wasn't exactly intentional. I can fix this by moving the check before computing gas https://github.com/ethereum/solidity/blob/develop/libyul/optimiser/LoadResolver.cpp#L126
