### ISSUE TITLE
XOR operator not compatible with types bool and bool

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#11814]
## Abstract

The XOR operator (`^` and `^=`) is essentially a boolean operator.

Although it is typically used as a bit-wise operator on integer operands, there shouldn't be any reason for it not to be applicable over boolean operands.

## Motivation

As far as I'm aware of, every strongly-typed language supports XOR between boolean operands.

And this is despite the fact that `a ^ b` is technically equivalent to `a != b`.

However, compiling the following code (with solc 0.7.6):
```
bool private prevState;

function getState(bool currState) external view returns (bool) {
    return prevState ^ currState;
}

function setState(bool currState) external {
    prevState ^= currState;
}
```
Gives the following errors:
```
TypeError: Operator ^ not compatible with types bool and bool
        return prevState ^ currState;
               ^-------------------^

TypeError: Operator ^= not compatible with types bool and bool
        prevState ^= currState;
        ^--------------------^
```

Thank you :)

**Comment by chriseth** [comment]
I think it makes sense to keep a strong separation between bitwise and boolean operators. `&` and `&&` are also not the same. As you say, for boolean types there is `!=`.

**Comment by barakman** [comment]
Yup, operator `^` for boolean operands doesn't really contribute anything that isn't already supported.

Operator `^=` does contribute a little bit, but it's negligible.

The only thing is, all other strongly-typed languages support it.

But I guess that it is possibly a pretty weak factor to consider here.

Thanks
