### ISSUE TITLE
‘list’ in namespace ‘std’ does not name a template type

### ISSUE THREAD

**Issue by marcelo-gonzalez** [ethereum/solidity#11811]
## Description

Build failure due to missing include

## Environment

- Compiler version: g++ Debian 8.3.0-6, CMake 3.13.4
- Operating system: Debian

## Steps to Reproduce

This looks like the exact same thing as in https://github.com/ethereum/solidity/issues/11103 but I figured I would make a new issue since it's a different file. Feel free to close and just use that issue if that's better

At least on my system,

```
$ git clone --recursive https://github.com/ethereum/solidity.git
$ git checkout v0.8.7
$ mkdir build && cd build
$ cmake .. && make
```

I get the following output:
![image](https://user-images.githubusercontent.com/37846884/129738139-90864f7b-af58-49c6-8ff6-8460e4155701.png)

**Comment by ekpyron** [comment]
Can you confirm that https://github.com/ethereum/solidity/pull/11812 fixes the issue?

**Comment by marcelo-gonzalez** [comment]
Ah yup, that fixes it
