### ISSUE TITLE
Suppress "unused variable" warning

### ISSUE THREAD

**Issue by marceljay** [ethereum/solidity#11816]
In reference to https://github.com/ethereum/solidity/issues/4081

If a function does not make use of a parameter, the following warning is issued by the compiler:
> Warning: Unused function parameter. Remove or comment out the variable name to silence this warning

However, in some instances, the variable cannot be commented out or removed because it is required by the selector/signature. 
Thus it would be benefical to have a feature to manually suppress the warning.

**Comment by chriseth** [comment]
Can you give an example?

**Comment by marceljay** [comment]
For example receive hooks, like `onERC721Received(operator, from, tokenId, data)`

https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#IERC721Receiver

To elaborate:
In my case, the `operator` does not matter, there shall be no change in the logic if the operator is an approved smart contract or an EOA, so only the original owner `from` is the used.

**Comment by chriseth** [comment]
Can you paste a self-contained example here where you can do neither of the following?
 - comment out the name of the variable
 - not implement the function body

**Comment by marceljay** [comment]
Mind the following example, I tried to reduce onReceive flow of the ERC721 standard. 

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
  
contract ReceiverContract {
        uint[] numbers;

        // commenting out any parameter will produce an error on `sendNumbers(...)`
        function onReceive(uint num1, uint num2) 
            external 
            returns (bytes4) 
            {
            numbers.push(num1);
            // not using `num2` will cause a warning
            return this.onReceive.selector;
        }
}

interface IReceiverContract {
    function onReceive(uint num1, uint num2) external returns (bytes4);
}


contract OriginatingContract {
    ReceiverContract callee = new ReceiverContract();

    function sendNumbers(uint num1, uint num2) public {
        require(checkCompatible(num1, num2));
    }

    function checkCompatible(uint num1, uint num2) private returns (bool) {
            try IReceiverContract(address(callee)).onReceive(num1, num2) returns (bytes4 retval) {
                return retval == IReceiverContract(address(callee)).onReceive.selector;
            } catch  {
                 revert("Error: Non implementer");
            }
    }

}
```

**Comment by aspiers** [comment]
I think it is not 100% clear that "remove [...] the variable name" means removing *just* the variable name, while keeping the typing.  Also, "comment out the variable name" would require `/* ... */` rather than `// ...` if there are other arguments following it on the same line, and again this is not 100% clear.  So maybe this warning text can be improved somehow.

**Comment by marceljay** [comment]
Yeah it did not occur to me, that you can have parameters without variable names. 

Thanks, the issue is solved and can be closed.

**Comment by hazardland** [comment]
Variable name remove means only removing variable name and not variable type:

```solidity
    function onERC1155BatchReceived(
        address operator,
        address from,
        uint256[] calldata ids,
        uint256[] calldata values,
        bytes calldata // Here variable name removed
    ) external view returns (bytes4) {
        require (operator==address(this));
        for (uint256 i=0; i<ids.length; i++) {
            require (listings[ids[i]].player==from && listings[ids[i]].count==values[i]);
        }
        return this.onERC1155BatchReceived.selector;
    }    
```

**Comment by dotwilbert** [comment]
@hazardland Thanks for the explicit example. From the preceding text it was hard to quickly extract the needed information. The variable type placeholder was the solution for me. The function is still compliant with the interface definition and the warning is gone.

👍👍
