### ISSUE TITLE
User-Defined Value Types as means for Generics

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#11827]
We could consider an extension of https://github.com/ethereum/solidity/issues/11531 as means to implement a specific kind of templates/generics.

The idea is to allow defining abstract types that initially have no operations, members or properties of any kind. Then those abstract types can be enriched explicitly with operations of fixed signatures (potentially depending on further abstract argument types) that do not have an implementation (but can be fully specified - we could even have dedicated syntax for specifying pre- and post-conditions for them to be used by e.g. SMTChecker).

Relative to those abstract types, generic routines can be written that act on those types. Those generic routines can be fully type-checked relative to the operations defined to the abstract types.

Then this generic routine can be invoked for any type that implements the requirements of the involved abstract types.

In this construction there can never be unexpected or weird behaviour. If the generic routine type-checks on the abstract type, then it will *always* work for *all* suitable concrete types. It will *always* call the exact routines matched during "type unification".
It can thereby also be *audited* once and be assured to work for any type that satisfies the specification of an abstract type.

This concept is commonly present in (often functional) languages with strong ties to e.g. Church's Simple Type Theory or Category Theory, e.g. ML or Haskell and has extensive (and complex) theoretical background - but none of it is required for using it and, if we implement it correctly, it would pretty much "just work" everywhere safely.

Syntactically, there are several options. Usually, the concept involves "type variables" that use specially marked identifiers. We could reproduce that, or we could introduce e.g. ``abstract type`` declarations. (EDIT: maybe we do need proper type variables and maybe even a full system of type classes/sorts to allow more advanced constructions)

The basic version without being able to enrich abstract types is straightforward, but rather useless.
```
abstract type genericType;
function f(genericType a, genericType b)
{
  // can do nothing with a and b, since they are not even comparable or have any other means of acting upon
}
```

Enriching the abstract type with members and operations immediately makes them useful, though (syntactic details subject to extensive refinement):

```
abstract type addableType with { function(addableType, addableType) pure returns(addableType) as + };

function f(addableType a, addableType b) pure returns (addableType)
{
  return a + b;
}
function g()
{
  uint256 x = 1; uint256 y = 2;
  assert(f(x,y) == 3); // will match ``addableType`` as ``uint`` and check that ``+`` on uint has signature ``function(uint, uint) pure returns(uint)`` and replace ``+`` in ``f`` with ``uint``'s ``+``.
}
```

Similarly to operators, members or any other properties of types can be specified for the abstract type.
This will already cover a large amount of use cases.
But it can be extended further to allow abstract types to depend on further abstract types:
```
abstract type combinableType(combineResultType) with { function(combinableType, combinableType) pure returns(combineResultType) as combine };

function combineImpl(uint8 a, uint8 b) pure returns (uint16) {
  return (uint16(a) << 8 | uint16(b));
}

using { combineImpl as combine } for uint8;

function combineArray(combinableType(combineResultType)[] memory a, combinableType(combineResultType)[] memory b)
returns (combineResultType[] memory r)
{
   require(a.length == b.length);
   r = new combineResultType[](a.length);
   for (uint256 i = 0; i < r.length; i++)
     r[i] = a[i].combine(b[i]);
}

```
Based on which this can even be taken higher order in theory:
```
using { combineArray(combinableType) as combine } for combinableType[];
```

To allow generics to depend on literals, literals are usually be lifted to the type system, which sounds weird, but in its application is rather natural. The main thing to do is to allow literals as types with some means to retrieve their literal value. (Details here will need more care, though, so don't take this at face-value)

```
abstract type literal(type) with { function() pure returns(type) as value }; // could be internal/std library

function addmod(type x, type y, literal(type) m) returns (type)
{
  return (x + y) % m.value();
}

function f()
{
  assert(addmod(3, 4, 2) == 1); // The type of the literal is rational(2) which we would give a .value function returning 2.
}
```
Although that's only one way to do this and there's multiple options for that. (Type return type of the rational .value function here would arguably either be sth like ``uint256`` or an abstract rational type...).

Implementation-wise the main thing required is a type unification mechanism, but that's always just first-order matching, so it's easy to do. The ability of the type-system to handle all of this could probably pretty much be inherited from concrete user-defined types.

**Comment by ekpyron** [comment]
Usually, this method would involve introducing a system of type classes or sorts on top of the type system, which, for the more advanced constructions, we'd probably need to reproduce internally, but could mostly hide away in practice to keep things easy to use.

**Comment by ekpyron** [comment]
The literal part in the description above is maybe a bit vague and ill-conceived... and I'd need to think through it in more detail myself. I'm not sure if this can be done without proper type variables and if those can be introduced without proper syntax... But I'd probably want to end up with something like these examples:
```
abstract type Type(type); // probably internally defined
abstract type /* sort? */  lessComparable(type) with { function(type, type) pure returns (type) as < };
abstract type  /* sort? */ incrementable(type) with { function(type) pure returns (type) as ++. };
// type::... would be sort constraints on the type... maybe this needs a proper distinction between types and sorts to be sound...
abstract type  /* sort? */ IntegerLiteralType(type::{incrementable, lessComparable}) with { function() pure returns(type) as value };

function iota(Type(baseType) base, IntegerLiteralType(literalType) literal)
  returns (type[literalType.value()] memory result) // either we need a construct stronger than "pure function" to be used above for ``value`` or we need to allow pure functions in compile-time constant context.
{
  // note that I could have skipped ``base`` and ``literal``, since I only require their types.
  result = new type[literalType.value()];
  for (literalType i = 0; i < literalType.value(); ++i)
    result[i] = i;
}

function f()
{
  uint[5] memory x = iota(uint256, 5);
  // the type of ``uint256`` is ``Type(uint256)``. The type of ``5`` is a rational type ``RationalNumber(5)`` that satisfies the IntegerLiteralType sort (which we'd provide internally and have rational numbers satisfy internally)
}

```

Hm... this is probably not quite right, without actually properly distinguishing types from sorts...
Moving to a full sort system, e.g. generic fixed point multiplication could probably look something like:

```
type FixedPointType(type::ArithmeticType, exponentType::IntegerLiteralType(type)) is type;

function fixedPointMul(
    FixedPointType(type, exponentType) lhs, // sort constraints as defined in the type definition
    FixedPointType(type, exponentType) rhs,
) pure returns (FixedPointType(type, exponentType))
{
  return type(lhs) * type(rhs) / (10**exponentType.value());
}

using { fixedPointMul as * } for FixedPointType;

type_alias ufixed256x18 = FixedPointType(uint256, 18);

```

**Comment by ekpyron** [comment]
Well, in any case: the concept above is not yet refined and not quite right, I'm mainly throwing out the idea so far. Planning this properly *will* need care, but the result should be nice, extensible and safe, if done right.

I hope I'll get around writing this up more properly than above in the foreseeable future.

**Comment by chriseth** [comment]
This really needs the shorthand function type notation https://github.com/ethereum/solidity/issues/1349

**Comment by ekpyron** [comment]
> This really needs the shorthand function type notation #1349

Yeah, definitely, that would be beautiful.

**Comment by tied2token** [comment]
How can I fi  it

**Comment by tied2token** [comment]
I thank you all... and am sorry but most of that went way over my head... iam very new to all of this and and self learning. All the different programs and functions terms and acronyms with  no  context is truly over whelming.. i don't think I even know what iam building and am just trying to keep up and tag along. This really started with me trying to understand why etherscan was telling me i had transactions and tokens and and pools that are linked to me I still don't even totally understand what this did.. so please forgive my lack of understanding my ignorance is in no way meant to cause harm and I guess I didn't Ihink could. And not having a networkable computer has ben hard

**Comment by hrkrshnn** [comment]
If we want to have operators, then I think we need a mechanism to distinguish between operators in checked and unchecked blocks.

**Comment by ekpyron** [comment]
I'd introduce a generic mechanism to define context blocks, which have a distinct "using"-context, i.e. a separate set of operator definitions (with an easy way to inherit parts of the top-level context).

**Comment by ekpyron** [comment]
As far as I'm concerned the more "fixed-function" mechanisms we can replace by something generic, the better. In the long term that could include almost everything: context blocks like ``unchecked``, complex types like sized integers, arrays, structs, even top-level constructs like contracts - if we do it right, we can *define* all of that quite easily. But we can of course do it incrementally and start with easy stuff. At some point we'll *at least* additionally need proper compile-time pure expression evaluation and for the more involved things, a way to define the ABI string for defined types, a way to define its storage and ABI encoding and decoding procedures, etc. pp. - but it will still only be a handful of concepts like that we'd need, which are not actually hard to do once we have generics and a proper system of algebraic types - and this would then decrease the maintenance burden of the compiler by orders of magnitude, while increasing the flexibility by an almost infinite amount.

**Comment by axic** [comment]
How about a `wrap`/`unwrap` function as follows (this is based on ideas by @ekpyron and me):
```
function wrap<T>(T.underlying a) returns (T b)
{
    assembly { b := a }
}

function unwrap<T>(T a) returns (T.underlying b)
{
    assembly { b := a }
}
```

**Comment by ekpyron** [comment]
I'm linking this to https://github.com/ethereum/solidity/issues/13321, but there's not too much gain in keeping it open as a separate issue.
