### ISSUE TITLE
I accidentaly sent Alix tokens to the Alix contract!

### ISSUE THREAD

**Issue by Silentgil1** [ethereum/solidity#11838]
Please I need help with this. I sent 8248 alix to the contract by mistake for avoiding a scam.
I spoke to the devs since the token is the same currency of the contract but they told me they "can't do nothing about it. "
It seems not fair since they could just return the tokens back to me. 

I've researched and there is an option to re-transfer back the tokens to my wallet but only the owners can do this.
Also, as I've seen here https://github.com/ethereum/solidity/issues/10616 . My tokens are the same as the contract ones!

Please help! the red is BSC

**Comment by leonardoalt** [comment]
@Silentgil1 sorry to hear about your issue, but this space is reserved for compiler related discussions/reports.
You might get more help on Reddit for example.

**Comment by Silentgil1** [comment]
Thanks for answering Leo, i just saw the https://github.com/ethereum/solidity/issues/10616 issue and thought i could write it here. Sorry
