### ISSUE TITLE
Properly generate release tarballs.

### ISSUE THREAD

**Issue by MathyV** [ethereum/solidity#1183]
Hi,

I was writing an .ebuild to include solidity as a package in the Gentoo distribution and noticed 2 issues while compiling. I pull the release tarball from GitHub but it does not contain:
- a commit_hash.txt with the commit version of the release (which stops the compilation)
- an empty prerelease.txt file (which results in the develop-string added to the version string)

Is it possible to add these to future release tarballs?

**Comment by chriseth** [comment]
I added an empty `prerelease.txt` file to the release branch, but I'm actually not sure whether this is the correct fix. The proper fix would be to not rely on the tarballs generated by github. Is it possible to change your build scripts to just build tagged commits on the release branch directly from git?

**Comment by MathyV** [comment]
Using the git tags would require extra maintenance (the .ebuild script needs to be updated every release) plus the person installing solidity needs to have git installed on their PC. In general these kind of .ebuilds are only reserved for very unstable releases and would probably be rejected by the Gentoo devs.

Besides, even if I would do that, the prelease.txt is still missing from those branches ;-)

The file must be added somewhere during your release process too, so can't you create source tarballs yourself during that process if I "shouldn't rely on github generated tarballs".?

**Comment by chriseth** [comment]
Yes, we might extract this tarball generation from our ppa release scripts.
