### ISSUE TITLE
[BREAKING] Make basfee as a reserved identifier in 0.9.0

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11836]
Effectively revert the commit https://github.com/ethereum/solidity/commit/7f1a2be0fee99531b5e9c0eca7dc1c70b9ffcaa0 in breaking.

**Comment by v-sreekesh** [comment]
@hrkrshnn can i create a PR with this commit reverted?

**Comment by hrkrshnn** [comment]
For doing this,

- revert the commit in the breaking branch (there should be a git command to do this specifically).
- run tests using isoltest (see contributing page in the documentation).
- add a description in the changelog.
- write something similar in the (rst) file 0.9.0 breaking changes.
- make a PR that targets breaking branch.

The breaking branch may not be upto date with develop. I'll check and fix this now.

**Comment by v-sreekesh** [comment]
ok will refer the git commands for doing this and follow your instructions thanks for providing the instructions

**Comment by v-sreekesh** [comment]
@hrkrshnn Raised a PR https://github.com/ethereum/solidity/pull/11842 could you check and let me know if any further changes are needed

**Comment by cameel** [comment]
This was done in #11842.
