### ISSUE TITLE
Require latest Z3 in soltest

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11845]
Extracted from https://github.com/ethereum/solidity/pull/11844#discussion_r696541700

We support linking with a range of versions of Z3 (the minimum is currently Z3 4.8.0) but our SMTChecker tests are only guaranteed to pass with the latest one (currently 4.8.12). This is because different versions of Z3 sometimes give different (but still valid) results and it's hard to create a test harness that could account for these differences. Instead we compare results verbatim. Because of this we sometimes get reports about broken tests when people build from source and use older Z3.

We don't want to raise the minimum version for `solc` but we could improve the situation by doing it for `soltest` and `isoltest`. Then anyone wanting to use them would have to have the latest Z3 or none at all (if an older version is installed it can always be disabled by passing `-DUSE_Z3=OFF` to cmake).

**Comment by soroosh-sdi** [comment]
I dig in this issue, and recreated the problem, this is what I've found:
- In `scripts/tests.sh` , we have comandline tests that actually run solc with an input file and expect specific output. these test are created by looping over all folders in `test/cmdlineTests/`. when we don't have any model checker OR z3's version < 4.8.12 we should ignore `/test/cmdlineTests/*model_checker*` in that loop. unfortunately we cannot do something about them in CMake.
- Also, in the tessuite we have `SMTCheckerTest` which should be disabled if we don't have any model checker OR z3's version < 4.8.12; fortunately we can do something about it in Cmake
- I compiled project with `-DUSE_Z3=OFF` but both of above issues exist.

for the first issue I should recognize SMT is disabled  and if it's enabled what version of Z3 solc is using; maybe we could add an option to solc to print this info. what do you  think @cameel ? 
 for the second issue I could implement something in CMake.

**Comment by leonardoalt** [comment]
@soroosh-sdi the problem with recognizing it (for the first issue) is that `solc` can also use z3 dynamically even if it's not compiled with it. So you'd need to query that part as well. Should be doable anyway, just more work

**Comment by cameel** [comment]
@leonardoalt Do you mean automatically disabling these commandline tests when Z3 is not available? We do not do that in `soltest` and `--no-smt` is required instead. I think we should just add support for this flag in `cmdlineTests.sh` as well (and, by extension, in `tests.sh`) and require user to explicitly disable them.

@soroosh-sdi 
> - Also, in the tessuite we have `SMTCheckerTest` which should be disabled if we don't have any model checker OR z3's version < 4.8.12; fortunately we can do something about it in Cmake

I don't think it should be disabled automatically. We do not want tests to be skipped silently by accident. We've been through that with semantic tests already (see https://github.com/ethereum/solidity/pull/11374#issuecomment-839588979). We want them skipped only if the `--no-smt` flag is used.

I think we should focus on the simple case where `soltest` is built with older Z3. A build error should give the user enough clue that Z3 needs to be updated.

The case where someone has older Z3 and actively disables it with `-DUSE_Z3=OFF` is trickier. All SMT tests are expected to fail in that case and we expect user to use the `--no-smt` flag. Perhaps some warning would be appropriate in this case after all?

**Comment by leonardoalt** [comment]
@cameel I agree with the `--no-smt` flag for the cli tests.

I agree with your other points as well.

**Comment by soroosh-sdi** [comment]
I see this issue, I use `-DBUS_Z3=OFF`
```
../scripts/../build/test/soltest --show-progress -- --ewasm --testpath ../scripts/../test  --evm-version byzantium --no-smt
Running 6213 test cases...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****************************************unknown location(0): fatal error: in "semanticTests/cleanup/exp_cleanup": memory access violation at address: 0x00000000: no mapping at fault address
../test/libsolidity/SolidityExecutionFramework.cpp(116): last checkpoint
************************************************************************************************************************
*** 1 failure is detected in the test module "SolidityTests"

```

**Comment by cameel** [comment]
Looks like an unrelated bug. Could you report it as a separate issue? But first please make sure it's reproducible - i.e. get a clean checkout of current `develop`, start with a clean `build/` directory and clean ccache (if you're using it). Sometimes these problems are just caused by some glitch in the cache or by stuff like updating system libraries without clearing the cache.

**Comment by soroosh-sdi** [comment]
> Looks like an unrelated bug. Could you report it as a separate issue? But first please make sure it's reproducible - i.e. get a clean checkout of current `develop`, start with a clean `build/` directory and clean ccache (if you're using it). Sometimes these problems are just caused by some glitch in the cache or by stuff like updating system libraries without clearing the cache.

checked it again, fortunately I can't reproduce it in a clean build :)

**Comment by soroosh-sdi** [comment]
I don't know how to move this issue to 'in-review' column :)
maybe I don't have permission.

**Comment by cameel** [comment]
There was some discussion in the PR about whether this should be an error: https://github.com/ethereum/solidity/pull/11873#discussion_r706342315

So #11873 covers the build-time check and the `--no-smt` flag. The last part will be the runtime check in `soltest`/`isoltest`. Here are some pointers on the implementation:
- I'd put the check in [`CommonOptions::validate()`](https://github.com/ethereum/solidity/blob/dea1b9ec7995ff7f16cdee7925a5858c5ce33982/test/Common.cpp#L112-L137).
    - There should be an error if Z3 version is not the latest one and `--no-smt` is not used.
    - There should be a warning if Z3 is not available at all and `--no-smt` is not used.
- You'll need to add a method for checking Z3 version to [`Z3Interface`](https://github.com/ethereum/solidity/blob/develop/libsmtutil/Z3Interface.cpp).
    - If Z3 has been loaded dynamically, version can be obtained from `Z3_get_version()` (see how [`Z3Loader::available()`](https://github.com/ethereum/solidity/blob/dea1b9ec7995ff7f16cdee7925a5858c5ce33982/libsmtutil/Z3Loader.cpp#L48-L58) does it).
    -  If it's static, you can use the `Z3_XXX_VERSION` constants.
- We can't perform this check in `cmdlineTests.sh` without something like #6228. I think it's not a big problem because it's unlikely that someone will run just the command-line tests and ignore `soltest`.
    - One thing we should change though would be to run `soltest` before `cmdlineTests.sh` in [`scripts/tests.sh`](https://github.com/ethereum/solidity/blob/develop/scripts/tests.sh).

@ekpyron Does `Z3Loader::available()` also cover the static Z3 or do we need a separate check for that case?

**Comment by ekpyron** [comment]
> But I think it would be better to add a new method in Z3Loader for returning it instead of calling Z3_get_version() directly.

Note that ``Z3Loader`` is only compiled and available if ``-DUSE_Z3_DLOPEN=ON`` is used. The best place to add this is probably a static function in ``Z3Interface`` next to ``Z3Interface::available()``.
``test/libsolidity/SMTCheckerTest.cpp:L47`` is where tests that require Z3 are disabled, if no Z3 is available at all.
It might also be fine to just add another check after that along the lines of ``if (m_modelCheckerSettings.solvers.z3 && <queried z3 version is not latest>) { /* raise error or just print warning and */ m_modelCheckerSettings.solvers.z3 = false; }``.

> @ekpyron Does Z3Loader::available() also cover the static Z3 or do we need a separate check for that case?

Ah, yeah, just saw the question now. I think it's better to have it next to ``Z3Interface::available()`` - Z3Loader is only the dynamic-loading case (see also the implementation of  ``Z3Interface::available()``).

**Comment by cameel** [comment]
Right. `Z3Interface` generally looks like a better place for this. Comment updated.

**Comment by soroosh-sdi** [comment]
Could you move this issue to `Done`?
@cameel

**Comment by cameel** [comment]
It's not done though :) We still need the runtime check I mentioned in https://github.com/ethereum/solidity/issues/11845#issuecomment-917089296.
