### ISSUE TITLE
Simplify and deduplicate CircleCI config

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11846]
This came up in #11823.

Our [.circleci/config.yml](https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml) file is pretty long. I went through the file and here's a bunch of changes that we could do to improve it.

Deduplication:
- [x] `t_archlinux_soltest`, `t_ubu_soltest_enforce_yul`, `t_ubu_ubsan_clang` and `t_ubu_ubsan_clang_cli` could use `run_soltest_steps`.
    - Note that `run_soltest_steps` cannot be added to an existing list of steps but it you could probably embed inside a step by using a [`when` parameter of a `run` step](https://circleci.com/docs/2.0/configuration-reference/#run).
- Some jobs look very similar. Perhaps they could be replaced by a single job with parameters (see `t_ems_ext` job for an example; also [Reusable Config Reference Guide](https://circleci.com/docs/2.0/reusing-config/)). If not, it might at least be possible to extract reusable steps from them:
    - [ ] `b_ubu_clang`, `b_ubu_asan_clang` and `b_ubu_ubsan_clang`.
    - [ ] `t_osx_soltest` and `t_osx_cli`.
    - [ ] `b_bytecode_ubu`, `b_bytecode_osx` and `b_bytecode_win`. 
- [x] Many jobs set the `TERM` variable to `xterm`. I think it would not hurt to just have it set once, globally, so that we do not have to worry about it.
    - EDIT: This probably does not have a good solution (see https://github.com/ethereum/solidity/pull/11868#discussion_r699430288) but I'm leaving it open. Maybe someone will figure out something.
    - EDIT2: I found a good compromise in #12173 - now the variable is defined in the `base_` templates.
- [ ] Jobs that differ only by one or two steps could be simplified by [passing these steps as arguments](https://circleci.com/docs/2.0/reusing-config/#steps).

Refactors:
- [x] All the `test_` templates (e.g. `test_ubuntu1604_clang` or `t_ubu_soltest`) seem a bit pointless because their steps are almost always overwritten. And when they're not, they're misleading because it's not apparent which steps they run just from their name. For example `test_ubuntu2004` runs `soltest_all` while `test_ubuntu2004_clang` runs only `soltest`. And after https://github.com/ethereum/solidity/pull/11823#discussion_r692403300 it's easy to explicitly specify their steps directly in the job anyway. I think that a better system would be to convert these templates into base dicts that just set the base docker image (maybe also `parallelism` and resource class). I'd remove steps from them (move them to jobs). I'd use `image_` or `base_` prefix instead of `test_` and rename the section. EDIT: Done in #12173.
- [ ] Our `steps_` templates should be rewritten as [reusable commands](https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands). This would make their use less verbose because we would no longer need to use the `when` hack I described above to merge them with existing step lists.
    - [ ] Check if steps of some existing jobs could also be converted into commands. One candidate would be for example package installation with `apt-get`. Another might be the stuff we do in bytecode comparison.

Cleanup:
- [x] I think we do not need to run the nightly workflow on the `develop_060` branch. Do we even still have that branch? We're already at 0.8.x.
- [x] There are some dicts like `run_soltest_all_steps` that actually contain `steps:` key rather than `run:`. They should be renamed to start with `steps_`. E.g. `steps_soltest_all`
- [x] All the `run_` steps should be moved to the `Build Templates` section.
- [x] `b_ubu_asan` should be moved next to `b_ubu_asan_clang`.

**Comment by cameel** [comment]
Great! Which one you'd like to try? I think it would be best to do it step by step, with small focused PRs, instead of creating a big one fixing it all in one go. I expect this will require some trial and error and a full CI run takes about 1h.

**Comment by mspaansen** [comment]
😀

**Comment by sneznaj** [comment]
.

**Comment by cameel** [comment]
While working on CI tasks today I realized that it's possible to pass step lists as parameters and that step lists can be wrapped into reusable commands. This could be used to further simplify the configuration. I added new items to the list in the description.

**Comment by super1ha1** [comment]
@cameel thanks for your suggestion, after reading through the code, 
it seem b_bytecode_ubu, b_bytecode_osx can be reused with some common steps.


I have created a pull request here

[12923](https://github.com/ethereum/solidity/pull/12923)

Can you help to take a look? 

Thanks you!

**Comment by cameel** [comment]
@super1ha1 Sure. See https://github.com/ethereum/solidity/pull/12923#issuecomment-1097060497.
