### ISSUE TITLE
Print code snippets next to source locations in IR

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11858]
With `--asm` option the compiler prints not only source locations but also small snippets of the Solidity code from those locations. For example:

```
tag_5:
    /* "test.sol":111:117  uint x */
  0x00
    /* "test.sol":120:121  1 */
  0x01
    /* "test.sol":111:121  uint x = 1 */
  swap1
  pop
    /* "test.sol":101:128  {... */
  pop
    /* "test.sol":81:128  function f() public {... */
  jump      // out
```

In IR we only get locations:
```yul
/// @src 0:81:128
function fun_f_21() {

    /// @src 0:120:121
    let expr_18 := 0x01
    /// @src 0:111:121
    let var_x_17 := convert_t_rational_1_by_1_to_t_uint256(expr_18)

}
/// @src 0:0:130

function identity(value) -> ret {
    ret := value
}
```

`AsmPrinter` should be extended to add snippets in IR too.

**Comment by cameel** [comment]
Also, there should be a command-line flag for selecting debug info format:
> there should be at least three modes: no debug info comments in the IR, regular debug info (as we have it now), debug info with source snippets

**Comment by cameel** [comment]
@chriseth What do you think about calling the new option `--inline-debug-info`? Or `--debug-tags`?

It would have three values for now:
- `--inline-debug-info=disabled`
- `--inline-debug-info=location`
- `--inline-debug-info=location,snippet`

This could map to either an enum or to a struct with a set of `bool` flags. For now I'm making it an enum. Not sure where to put it though - if I create a single enum for both `libyul::AsmPrinter` and for `libevmasm::Assembly` it will create a dependency between them. But having two separate enums does not sound all that good either.

**Comment by chriseth** [comment]
Why "inline"? Maybe `--ir-debug=...` with the following options: `astid` (future PR), `src` (the snippet), `loc` (the location)

`--ir-debug-info` would also be fine for me

**Comment by cameel** [comment]
> Why "inline"?

Well, I wanted to distinguish it from the full debug info that could be printed by the compiler when requested as its own artifact but I guess these comments are the only way to output any debug info for now? In that case `--ir-debug` sounds ok.

Should I allow `--ir-debug=src` (i.e just the snippet without location)? Currently the `loc` part in the parser is not optional. Not sure if I should make it optional or just disallow this combination. Does printing only snippets sound like a useful feature?

**Comment by cameel** [comment]
In the end I called it `--debug-info`, because it affects EVM assembly too. And I have forbidden `src` without `loc`.

I just now realized that you wanted short names for values though. In my PR I called them `location`, `snippet` and `ast-id`. I can easily change them though if you think shorter names are better.

**Comment by chriseth** [comment]
long names are fine!
