### ISSUE TITLE
Add `--optimize-runs` parameter to `solcjs`

### ISSUE THREAD

**Issue by thanhnguyennguyen** [ethereum/solidity#11857]
https://github.com/ethereum/solc-js/blob/250c85b88a7ebcdcba7e19c4b9781540f32ea1ed/solcjs#L132

Do we support optimizer with run parameter (200 as default) ?
Like this 
![image](https://user-images.githubusercontent.com/17243442/131282644-ad2783b0-1ddb-444d-b8d1-6240cc005d19.png)

**Comment by thanhnguyennguyen** [comment]
I think it's really helpful parameter ` --optimize-runs`
Right now, without ` --optimize-runs` we can't get exact bytecode of contract to proceed verify smart contract code (if contract owner deployed their contract with Optimized enable)

**Comment by cameel** [comment]
For verification I'd strongly recommend using `--standard-json`. Otherwise it's very easy to get slightly mismatched metadata due to paths, especially if you are compiling on multiple platforms.

**Comment by thanhnguyennguyen** [comment]
Hi @cameel 
can you guide me how to put standard-json to setting

```        const input = {
            language: 'Solidity',
            sources: sources,
            settings: {
                optimizer: {
                    enabled: optimization
                },
                outputSelection: {
                    '*': {
                        '*': ['*']
                    }
                }
            }
        }
        var output = JSON.parse(solcSnapshot.compile(JSON.stringify(input)))

**Comment by cameel** [comment]
The whole JSON structure is documented in [Compiler Input and Output JSON Description](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description).

The `--optimize-runs` option is called `runs` there:
```json

"optimizer": {
    "enabled": true,
    "runs": 200
}
```
