### ISSUE TITLE
Importing an aliased import results in unusable symbol

### ISSUE THREAD

**Issue by chanhosuh** [ethereum/solidity#11855]
## Description

An aliased import can be imported into other files but subsequently is not available for use.  I find this confusing.  Either the import should fail or it should succeed, with the symbol being available for use.

## Environment

- Compiler version: 0.6.11
- Target EVM version (as per compiler settings): London
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client:  N/A
- Operating system: OS X

## Steps to Reproduce

Here are three contracts:

1. a dummy contract to refer to
2. a file that imports the dummy contract with an alias
3. another file that imports the alias from the previous file and tries to use it

```solidity
// Dummy.sol
pragma solidity 0.6.11;

contract Dummy {
    string public constant FOO = "FOO";
}

// HasAlias.sol
pragma solidity 0.6.11;

import {Dummy as AliasedDummy} from "./Dummy.sol";

// UseAlias.sol
pragma solidity 0.6.11;

import {AliasedDummy} from "./HasAlias.sol";

contract TestAlias is AliasedDummy {}
```

Output:
```
contracts/UseAlias.sol:5:23: DeclarationError: Identifier not found or not unique.
contract TestAlias is AliasedDummy {}
                      ^----------^

Error HH600: Compilation failed
```

**Note:** removing line 5 of `UseAlias.sol` results in successful compilation!

## Expected Result and Discussion

I expect the identifier `AliasedDummy` to be found, as compilation succeeds without line 5 in `UseAlias.sol`.  The resulting behavior seems to be that the alias can be imported without error but cannot be used.  This is confusing.  Either the symbol doesn't exist in `UseAlias.sol` so it can't be imported, or it does exist and can be imported for use.  There should not be an "in-between" state of being able to import symbols that are then unavailable for use.  (this is somewhat reminiscent of Javascript, but even the case of Javascript, the imported symbol exists with the value of `undefined`).

**Comment by cameel** [comment]
Not sure it it's accidental or by design but I agree that this is not the behavior I would expect as a user. In my opinion `Dummy` should not to be importable from `HasAlias.sol` at all (currently it is) and `AliasedDummy` should be importable and usable without errors.

Having `Dummy` importable and `AliasedDummy` non-importable would be consistent too, though less intuitive.

**Comment by chriseth** [comment]
Indeed, this is a bug: The example above should compile fine while importing `Dummy` from `HasAlias` should fail.
