### ISSUE TITLE
error evaluating order of operations with parenthesis 

### ISSUE THREAD

**Issue by mesozoic-technology** [ethereum/solidity#11871]
## Description
I have this code with parenthesis that is giving me the wrong computation.

Initially, I was getting an integer underflow when running it. The subtraction definitely doesn't underflow so it leads me to think it is some bug with evaluation parenthesis, which according to the docs should be the first thing evaluated. 

This code gives an overflow error:
```
            uint _timeDiff = ( _atOrAfter.time - _beforeOrAt.time ) * 1e10;
```

This code gives the wrong value:
```
            uint _timeDiff;
            unchecked {
                _timeDiff = ( _atOrAfter.time - _beforeOrAt.time ) * 1e10;
            }
```

And this code works correctly:
```
            uint _timeDiff;
            _timeDiff = _atOrAfter.time - _beforeOrAt.time;
            _timeDiff = _timeDiff * 1e10;
```

I'm worried what to make about this. In the meantime will probably just play it safe and use the more verbose expression..

## Environment

- Compiler version: 0.8.7
- Target EVM version (as per compiler settings): London
- Framework/IDE (e.g. Truffle or Remix): brownie
- EVM execution environment / backend / blockchain client: ganache
- Operating system: macos

## Steps to Reproduce

Hopefully this reproduces the bug? I found this in my code which has a lot more before and after. 

```solidity
// Some *minimal* Solidity source code to reproduce the bug.
// ...

Struct MyStruct {
   uint32 time;
}

MyStruct _beforeOrAt = MyStruct(12000);
MyStruct _atOrAfter = MyStruct(18000);

uint _timeDiff = ( beforeOrAt.time - _atOrAfter.time ) * 1e10;

```

**Comment by cameel** [comment]
It's an overflow because the computation happens within `uint32` type.
 `(18000 - 12000) * 1e10` is 6 * 10^13, which is way out of range of this type (2^32-1).

**Comment by mesozoic-technology** [comment]
Aha thanks, I hadn't taken that into account because they're being assigned to a `uint` and I thought solc 0.8.* was more stringent on typecasting, so it would have complained

**Comment by cameel** [comment]
It is stringent but there's no conversion to `uint` here - at least not during the multiplication. You are multiplying by a literal and literals have their own special type with unlimited precision. When a literal is multiplied by an integer type, the computation is preformed within that integer type. The conversion to `uint` is only perforemed after that and it's a pretty safe conversion (width is not decreased, signedness is not changed, type is still integer) so the compiler has nothing to complain about :)
