### ISSUE TITLE
Include enums in the ABI

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11872]
For a while internal types are exposed in the ABI, which can be used to do type checking stricter than the encoding allows. 

Such an example when enums are used in an interface (see #595):
```json
      {
        "indexed": false,
        "internalType": "enum I.MyEnum",
        "name": "b",
        "type": "uint8"
      }
```

The proposal is to include a new entry in the ABI for enums:
```json
{
  "type": "enum",
  "name": "MyEnum",
  "min": 0,
  "max": max
}
```

The `min` is hardcoded at 0 as enums are encoded as `uint8` currently, but leaving the field for future compatibility.

**Comment by chriseth** [comment]
I think we should use the `type` field only for things that also appear in the signature. If you want to look up additional information for the type, I think you should use the AST instead.
