### ISSUE TITLE
Always include `--experimental-via-ir` flag in metadata generated from IR

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11876]
Part of #11494.

Currently the metadata embedded in Yul sources generated with `--ir` or `--ir-optimized` is the same as the one that goes into the binary. This means that if you do not use the `--experimental-via-ir` but use `--ir` or `--ir-optimized` to get the output from the new codegen, printed Yul sources  have metadata that is not marked as generated using the experimental pipeline even though it was.

Change this so that the metadata in printed Yul code always looks as if the `--experimental-via-ir` option was used.

**Comment by cameel** [comment]
@chriseth While implementing #11931 I realized that there's an additional problem here: there's currently no way for the user to obtain the metadata when doing the two-step compilation. On the CLI the `--metadata` option does not work in assembly mode (just like other output options: #3870) and in Standard JSON the `metadata` output does not produce metadata either.

Before #11931 it always matched the metadata for EVM so it was not a problem - you could get it from the first step - but now that it's different, there's no way to obtain it other than doing the single-step compilation.

Another problem is that metadata always comes from the first step. So for example if the user passes the `--libraries` option only to the assembly step, metadata will not reflect that properly.

**Comment by chriseth** [comment]
It is not possible to obtain the metadata just from the yul code, because it's not there - I think this is fine.

What you are saying is that `--metadata --ir` will result in the metadata json not matching the metadata hash in the IR, right? I think this is fine for now - I don't see a proper way to "fix" this.

The metadata will match the hash when we use `--metadata --ir --experimental-via-ir`, though, right?

**Comment by cameel** [comment]
> The metadata will match the hash when we use `--metadata --ir --experimental-via-ir`, though, right?

Yes.

> What you are saying is that `--metadata --ir` will result in the metadata json not matching the metadata hash in the IR, right? I think this is fine for now - I don't see a proper way to "fix" this.

Also yes. One way would be to allow printing this metadata in the first step.

But now that I think about it, maybe making this metadata unavailable (and unpublishable) is actually a good thing? I think that the primary use case for two-step compilation is to allow the user to modify the assembly and in that case metadata is likely to be misleading anyway (i.e. the bytecode does not necessarily match the one produced from sources whose hashes are stored in metadata).
