### ISSUE TITLE
[SMTChecker] Support abi.decode completely

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11884]
For
```solidity
require(abi.decode(returndata, (bool)), "SafeERC20: ERC20 operation did not succeed");
```
the SMTChecker reports `Warning: Assertion checker does not yet implement type type(bool)`.

**Comment by leonardoalt** [comment]
Yea we shouldn't report these here. This actually *is* supported as an uninterpreted function, so we shouldn't report this warning on expressions of type type inside abi calls.
