### ISSUE TITLE
Non-deterministic source maps for the same contract when other contract imports it

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum/solidity#11898]
## Description

Solidity generates slightly different source maps when:

1. The contract is not imported by any other contract in the code base.
2. The exact same contract is imported by other contract in the code base, which is compiled as well.

In the second case, there is an extra semicolon in the source maps. As per the [docs](https://docs.soliditylang.org/en/v0.8.7/internals/source_mappings.html), this *should* refer to an additional assembly instruction in the contract. But there is no such instruction, thus this may be a bug. I expected the source maps to be identical between the two circumstances, given that all else is equal (compiler settings, source code, whitespaces, etc).

Here are two GitHub Gists with the different source maps:

- [1st case](https://gist.github.com/paulrberg/b250fbb6d5aa92ae27381071aa1a8e61)
- [2nd case](https://gist.github.com/paulrberg/7f70bf4415d7ffd51645507fbba63e93)

If you run these on [text-compare.com](https://text-compare.com), you will notice that there are more diffs than just an extra semicolon. But you can ignore all of them, except the semicolon, because they refer to the different file ids that get assigned to `PRBProxy` and `#utility.yul` by Solidity. Check out characters 317-320th; in the 1st case, you find `4;;;2`, and in the 2nd case `8;;;;`.

## Environment

- Compiler version: solc-macosx-amd64-v0.8.7+commit.e28d00a7
- Target EVM version (as per compiler settings): Compiler default (London)
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: Hardhat Network (hardhat@2.6.2)
- Operating system: macOS@11.5.2

## Steps to Reproduce

1. Git clone [prb-proxy](https://github.com/paulrberg/prb-proxy/commit/93d337b3fa66fe03ccf3e355b5da490bf5bba273) at commit `93d337b` 
2. Install dependencies with `yarn install`
3. Fill a `.env` file as shown by the `.env.example` file
4. Generate the TypeChain bindings with `yarn typechain`
5. Run the tests with `yarn test --verbose`

You should get the following error:

```
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: This shouldn't happen: a call trace has no functionJumpdest but has already jumped into a function
    at ErrorInferrer._getEntryBeforeFailureInModifier (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:1476:13)
    at ErrorInferrer._checkRevertOrInvalidOpcode (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:370:16)
    at ErrorInferrer._checkLastInstruction (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:554:44)
    at ErrorInferrer.inferAfterTracing (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:162:12)
    at SolidityTracer._rawTraceEvmExecution (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:211:61)
    at SolidityTracer._traceEvmExecution (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:56:19)
    at HardhatNode._manageErrors (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1705:41)
    at HardhatNode.estimateGas (/Users/paulrberg/workspace/pad/prb-proxy-clone/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:661:27)
```

## Implications

This is likely what causes https://github.com/nomiclabs/hardhat/issues/1185. The error above is the same as the one reported by everyone else there.

## More Details

I spent three days debugging this. What I know thus far:

- The issue goes away when I manually remove the extra semicolon the source maps
- The issue goes away when I delete the `PRBProxyFactory.sol` and `PRBProxyRegistry.sol` contracts and compile just `PRBProxy.sol` and its dependencies
- The issue goes away when I rename the `execute` function to something else, such as `fooBarBaz`
- The issue goes away when I turn off the compiler optimizer
- Seems this has something to do with the modifier (`onlyOwnable`) and the `JUMPTDEST` opcode

**Comment by PaulRBerg** [comment]
Cc-ing @alcuadrado and @fvictorio, they might be able to help. I tracked the error in the Hardhat source code. This is what I found:

1. [Line 1477](https://github.com/nomiclabs/hardhat/blob/deaa288a44f133204392464c7a9257b56c99f4df/packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts#L1477) in `stack-traces.ts` gets executed because `functionJumpdests` is empty.
2. `functionJumpdests` is empty because [line 191](https://github.com/nomiclabs/hardhat/blob/deaa288a44f133204392464c7a9257b56c99f4df/packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidityTracer.ts#L191) gets executed in `solidityTracer.ts`. I suspect that this is correct, the issue being the flawed source maps.

I also looked at [source-maps.ts](https://github.com/nomiclabs/hardhat/blob/deaa288a44f133204392464c7a9257b56c99f4df/packages/hardhat-core/src/internal/hardhat-network/stack-traces/source-maps.ts) but nothing caught my attention, except for https://github.com/nomiclabs/hardhat/pull/1857. But even after fixing the `hasPart3` line, the tests kept failing. Thus I conjectured that this may be a bug in Solidity .. and I went down the rabbit hole and ended up opening this issue.

**Comment by chriseth** [comment]
The fact that the source maps have different lengths sounds like the bytecode is also different, which would be far more alarming. Can you please provide the assembly and the bytecode output of both ways to compile the contract?

**Comment by PaulRBerg** [comment]
The bytecodes and the opcodes were the same. I triple checked this while debugging.

I am on my phone now but I will follow up later with the exact bytecodes/ opcodes I got.

**Comment by chriseth** [comment]
Thanks! And could you please also provide the sources and the metadata file, so I can try to reproduce it locally?

**Comment by PaulRBerg** [comment]
> Can you please provide the assembly and the bytecode output of both ways to compile the contract?

I updated the GitHub Gists I shared in the first post:

1. [src-maps-bug-1st-case.json ](https://gist.github.com/paulrberg/b250fbb6d5aa92ae27381071aa1a8e61)
2. [src-maps-bug-2nd-case.json](https://gist.github.com/paulrberg/7f70bf4415d7ffd51645507fbba63e93)

They are JSONs which with `deployedBytecode`, `opcodes` and `sourceMaps` entries.

> And could you please also provide the sources and the metadata file, so I can try to reproduce it locally?

The sources are in the [prb-proxy](https://github.com/paulrberg/prb-proxy) repository, at commit [93d337b](https://github.com/paulrberg/prb-proxy/commit/93d337b3fa66fe03ccf3e355b5da490bf5bba273). To reproduce the 1st case results, run Hardhat over the repo as is. You have instructions in the first post; the specific command is `yarn compile`. To reproduce the 2nd case results, delete the `PRBProxyFactory.sol`, `IPRBProxyFactory.sol`, `PRBProxyRegistry.sol` and `IPRBProxyRegistry.sol` files, and run Hardhat again.

In the 1st case, the name of the file under `artifacts/build-info` should be `313bad6d3bea2ff85dd80179204ba658.json`. In the 2nd, it should be `e0c925ee78a287a14868de7d4f5c3c00.json`.

Regarding the "metadata file", I have no such thing. All the compiler settings are defined in [hardhat.config.ts](https://github.com/paulrberg/prb-proxy/blob/93d337b3fa66fe03ccf3e355b5da490bf5bba273/hardhat.config.ts). For what it's worth, I [disabled](https://github.com/paulrberg/prb-proxy/blob/93d337b3fa66fe03ccf3e355b5da490bf5bba273/hardhat.config.ts#L75) the metadata hash.

**Comment by PaulRBerg** [comment]
More data points:

- I tried switching Hardhat versions, same result. I tried v2.5.0, 2.6.0, v2.6.1 and v2.6.2.
- I tried switching Solidity versions, same result. I tried all v0.8.x releases.

**Comment by chriseth** [comment]
It's really a pity that hardhat makes it so complicated to get the metadata file - it is the one thing that abstracts the framework away from compiler invocation. I'll try to reproduce nevertheless.

~~One thing that strikes me: The source maps contain 1030 / 1031 entries while the deployed bytecode is 1578 bytes long.~~
Edit: This not remarkable since the source maps are opcode- and not byte-based

**Comment by chriseth** [comment]
Ok, got it reproduced. Just some bits of documentation:
```
git clone https://github.com/paulrberg/prb-proxy
git checkout 93d337b
npm install # or maybe "npx yarn install"?
mv node_modules/@paulrberg .
# first version:
solc  contracts/* --optimize --allow-paths . --combined-json bin,srcmap,srcmap-runtime | jq '.contracts["contracts/PRBProxy.sol:PRBProxy"]["srcmap-runtime"]'
# second version:
solc  contracts/*Proxy.sol --optimize --allow-paths . --combined-json bin,srcmap,srcmap-runtime | jq '.contracts["contracts/PRBProxy.sol:PRBProxy"]["srcmap-runtime"]'
```

**Comment by PaulRBerg** [comment]
> npm install # or maybe "npx yarn install"?

It should be `npx yarn install` because there is a `yarn.lock` file committed in version control.

---

~~Re your other commands - they look good. I compiled the same sets of contracts but via Hardhat directly.~~

**Update**: the optimizer should be run 800 times, and the metadata hash should be disabled. I don't see these in your commands, though if you reproduced the issue it should be ok.

**Comment by chriseth** [comment]
What is weird is that if I request the assembly output, I get different assemblies (some redundant swaps and dups that do not matter because `and` is commutative), but the bytecode is actually the same.

**Comment by chriseth** [comment]
Ok, this was a tough one: The reason is that the factory contains the proxy as a sub-object and somehow, the optimizer is run again on the proxy resulting in slightly different bytecode than on the first run - usually the optimizer runs as long as there are changes, so it should not be a problem to run it a second time. The actual bytecode is the same, because it has been stored already before the second run of the optimizer.

**Comment by PaulRBerg** [comment]
Thank you for the quick turnaround, ser!

I look forward to v0.8.8 so I can remove the ".skip" flags in my tests :D
