### ISSUE TITLE
DOCS: Adjust rdt-theme colors by adding a "Solidity style" custom CSS file

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#11900]
# Problem Statement
The current docs theme we are using is the plain readthedocs sphinx theme. Some colors are hard to read (e.g. the search highlights). Additionally, it would be nice if the docs would reflect the overall Solidity brand identity.

# To Do

- [x] Add custom CSS file called "Solidity light mode" with the color changes described blow ([docs](https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html))
- [x] In the dark mode CSS file, adjust the search highlight color to be soft red: #F0978B (yellow is currently not readable)
- [x] [optional] Add Solidity logo in the menu bar and delete logo from the index page
- [ ] [optional] Adjust font to Work Sans to be consistent with the font across blog, portal and docs

**Proposed color changes:**
- Make code block background Solidity light grey: #E5E5E5
- Make titles / highlights Solidity light blue: #65AFFF
- Make hyperlinks Solidity electric blue: #002fa7
- Make highlights for searched words warmer yellow: #EAC545

**Rough sketch of how it would look with the proposed colors:**

![image](https://user-images.githubusercontent.com/41991517/132236639-27d544d6-9602-433e-a0bd-3e78b527fe94.png)

**Comment by 4molybdenum2** [comment]
Hi, I made a PR for this issue. Can you please review? @franzihei

**Comment by cameel** [comment]
> Make code block background Solidity light grey: #E5E5E5

I think I liked the green code blocks a bit more than the gray ones. They were not perfect so changing them is probably a good idea (for example green and light blue text does not stand out enough on that background) but the new ones look a bit dull:

### Before
![yul-stand-alone-usage-green](https://user-images.githubusercontent.com/137030/133292176-d1cc5f83-8354-4814-8fe3-c3459be9aff7.png)

### After
![yul-stand-alone-usage-gray](https://user-images.githubusercontent.com/137030/133292343-e651ae4f-5b6a-477e-b79e-49032531af95.png)

**Comment by axic** [comment]
@franzihei @cameel Could something like a thin border around the box with a different colour work?

**Comment by cameel** [comment]
Maybe? Highlighted code looks good on white background but I think that the block itself does not stand out enough.

![yul-stand-alone-usage-white](https://user-images.githubusercontent.com/137030/133293948-c0246a6d-76b2-4a21-9837-6f48c0275dde.png)

**Comment by axic** [comment]
I think this looks pretty good, but I'd try thickening the border.

**Comment by cameel** [comment]
ok, I posted that in the PR.

**Comment by franzihei** [comment]
I'm not sure why the sudden changes of color occured re. the background of code blocks, but here were my reasonings for grey:
- The current green/yellow-ish is a really "not nice for the eyes" toxic color, which does not fit our Solidity brand colors
- To make it look more consistent with the blog, I thought grey would look nice and clean. There's enough color happening in the syntax highlights, so no need for more color in the background.
- I chose a darker grey since I thought a bit of contrast would benefit (contrast between the actual background and the background of the code boxes)

That being said, if we want it to come even closer to how code examples are presented on the blog, we should consider a lighter grey (#FAFAFA) with a darker grey outline.

![image](https://user-images.githubusercontent.com/41991517/134383392-7e1082da-ae44-45f3-9034-2e97e4fb4548.png)

**Comment by axic** [comment]
I think both https://github.com/ethereum/solidity/issues/11900#issuecomment-919297759 and https://github.com/ethereum/solidity/issues/11900#issuecomment-925089250 are good. I do prefer slightly lighter, and definitely not the darkness in https://github.com/ethereum/solidity/issues/11900#issuecomment-919288976

**Comment by franzihei** [comment]
We can probably close this for now and re-open in case we want to also change the font at a later point in time.
