### ISSUE TITLE
Inline assembly: documentation should be improved

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1190]
1. accepted external identifiers
   `identifiers (externals, labels or assembly-local variables), e.g. jump(name), 3 x add` should explain that functions and libraries can also be pushed to the stack.
2. mention that `assembly "evmasm" { }` is a valid syntax
3. at the end of the assembly block, the stack should be balanced (unless intentionally required otherwise)

**Comment by chriseth** [comment]
I don't want to mention 2 until we have a second value for that string and 3 is already done, right?

**Comment by axic** [comment]
I don't think any of this is documented, but there's a warning for 3.

**Comment by nebojsa94** [comment]
Hey, current documentation says that you can access external function in inline assembly, can you add some examples?

**Comment by chriseth** [comment]
Sorry, but I fear this is being phased out.
