### ISSUE TITLE
[soltest] Command-line validation errors should not look like an ICE

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11917]
Currently validation errors are reported as if they were internal compiler errors which makes it look like as if a bug in the compiler was triggered. A nicely formatted message should be printed instead.

For example the error caused by using `--testpath` with an empty value looks like this:
```bash
soltest -- --testpath
```
```
Test setup error: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::program_options::invalid_command_line_syntax>
std::exception::what: the required argument for option '--testpath' is missing
```

**Comment by ezioishan** [comment]
Hey, I would like to work on this issue. Can you explain me how to reproduce it and what message to be displayed on such an error

**Comment by cameel** [comment]
Great! The instructions to reproduce are in the description - just built the compiler and run `soltest` executable (you'll find it in `build/test/soltest` with the parameters I have shown. You'll see the error I'm showing above.

In this particular case it would be enough for it to print something like:
```
ERROR: The required argument for option '--testpath' is missing.
```

The code that validates it is in [`CommonOptions::validate()`](https://github.com/ethereum/solidity/blob/3e2e3d1baa79a8761577eacc0d4b3476bd13cade/test/Common.cpp#L112-L137).

We can catch the `ConfigException` it raises but if `boost::program_options` provides a better mechanism to report an error from a validation we could use that too.

**Comment by cameel** [comment]
Also note that the validations in `CommonOptions::validate()` are not the only ones. For example invalid options trigger a similar error:

```bash
soltest -- --adsfasf
```
```
Test setup error: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::program_options::unknown_option>
std::exception::what: unrecognised option '--adsfasf'
```

So after implementing it please make sure there are no obvious cases that still trigger errors looking like these.

**Comment by ezioishan** [comment]
Hey, regarding building the compiler, I'm on windows and want to build it without using Visual Studio. Is it possible? If yes, then what commands to follow. (I have already installed the dependencies & pre-requisites to build according to the documentation)

**Comment by ezioishan** [comment]
I don't think I'll be able to build this. Please un-assign me from the task

**Comment by cameel** [comment]
@ezioishan Unfortunately we only have the build steps for MSVC documented. Building with other compilers should be possible but it would probably require some changes to CMake configuration. If someone wanted to try, we'd accept patches to make it build but we only run MSVC in CI so it would likely break over time unless someone is also willing to maintain it long-term. The team is mostly on macOS and Linux so to be honest even supporting the MSVC build is sometimes problematic.

Maybe building a Linux version using [WSL](https://docs.microsoft.com/en-us/windows/wsl) would be a viable option for you?
