### ISSUE TITLE
[Codegen] ICE in ContractCompiler visit of inline assembly

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11929]
```
contract C{
  struct S{int m;}
  function f(S calldata s) public returns(int r) {assembly{s:=r} }
}
```

throws

https://github.com/ethereum/solidity/blob/dea1b9ec7995ff7f16cdee7925a5858c5ce33982/libsolidity/codegen/ContractCompiler.cpp#L864-L867

```
$ solc test.sol
```

**Comment by cameel** [comment]
Duplicate of #11680.

And it affects not only structs. There's a repro for static arrays too in that issue.
