### ISSUE TITLE
ICE when the file name in `@use-src` annotation does not match the name of the file passed to `--strict-assembly`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11932]
## Description
If you try to assemble a file using a different name than the one included in the `@use-src` annotation, the compiler crashes. 

There must be some additional factors involved because it only happens in specific circumstances. For example in the example below the problem goes away if I remove any of the annotation or if I do not use `calldataload(0)`.

## Steps to Reproduce
- `input.yul`
    ```yul
    /// @use-src 0:"input.sol"
    object "C" {
        code {
            /// @src 0:0:0
            calldataload(0)
        }
    }
    ```
```bash
solc --strict-assembly input.yul
```
```
Warning: Yul is still experimental. Please use the output with care.
terminate called after throwing an instance of 'boost::wrapexcept<solidity::yul::YulAssertion>'
  what():
Aborted (core dumped)
```
Note that we don't have a handler for `InternalCompilerError`s in assembly mode. #11732 should fix that.

The assertion failure happens at https://github.com/ethereum/solidity/blob/e28d00a76daa0747f00ffe47cea17862bca55771/libyul/AssemblyStack.cpp#L94

## Environment
- Compiler version: Happens both on 0.8.7 and on the latest code from `develop`.

**Comment by cameel** [comment]
Example updated. Looks like the `pop()` around `calldataload(0)` makes it not crash. Same if I assign the value to a variable - so this must have something to do with unused stuff remaining on the stack.

**Comment by chriseth** [comment]
I'm unassigning myself again. My initial assessment is that AssemblyStack always assumes that the SourceLocations inside the Yul AST point to the Yul source of AssemblyStack. I think we have to determine inside AssemblyStack if the YulObject has a `@use-src` or not and change its behaviour respectively.

**Comment by cameel** [comment]
The problem is that when `@use-src` is present,  `DebugData::location` stores Solidity locations and we don't have Yul locations at all. `AssemblyStack` reports errors at Solidity locations and I think this is a bug. But it does not have the Yul location available. I think we need a separate field in `DebugData` for each of these locations.

**Comment by cameel** [comment]
Note how some errors are missing locations even in cases where there's no crash.

It's not all of them though so apparently the Yul locations are still stored somewhere.
EDIT: apparently this is because the second error in the first example happens at the parsing stage (in `ParserBase.cpp`). Interestingly the first error is missing location despite coming from `AsmParser.cpp`. It's probably because of the location override? I'm adding a second example with an error reported in `AsmAnalysis.cpp`.

### Example: error in the parser
```yul
/// @use-src 0:"input.sol"
object "C" {
    code {
        xyz
    }
}
```
Output on 0.8.6:
```
Error: Call or assignment expected.
 --> /tmp/input.yul:5:5:
  |
5 |     }
  |     ^

Error: Expected end of source but got '}'
 --> /tmp/input.yul:6:1:
  |
6 | }
  | ^
```
Output on 0.8.7:
```
Error: Call or assignment expected.

Error: Expected end of source but got '}'
 --> /tmp/input.yul:6:1:
  |
6 | }
  | ^
```

### Example: error in `AsmAnalysis.cpp`
```yul
/// @use-src 0:"input.sol"
object "C" {
    code {
        let a, b := 1
    }
}
```

Output on 0.8.6:
```
Error: Variable count mismatch for declaration of "a, b": 2 variables and 1 values.
 --> /tmp/input.yul:4:9:
  |
4 |         let a, b := 1
  |         ^^^^^^^^^^^^^
```
Output on 0.8.7:
```
Error: Variable count mismatch for declaration of "a, b": 2 variables and 1 values.
```
