### ISSUE TITLE
(Disallow?) `using for` to bind internal functions to interfaces

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11952]
Interfaces only allow defining external functions. This means that if `I` is an interface, one can expect `I(addr).functionCall()` to correspond to an external function call. However, `using for` breaks this by allowing one to bind an internal function to interfaces. One typical example is the following:

```solidity
/// From OZ
library SafeERC20 {
    function safeTransferFrom(
        IERC20 token,
        address from,
        address to,
        uint256 value
    ) internal {
        _callOptionalReturn(token, abi.encodeWithSelector(token.transferFrom.selector, from, to, value));
    }
}

using SafeERC20 for IERC20;

IERC20(_token).safeTransferFrom(...);
```

This pattern decreases readability of contracts (because it's obvious that `safeTransferFrom` is not in the ERC20 standard and this makes it look like an incorrect interface implementation) and unfortunately is very prevalant: [list of etherscan verified contracts with with this behaviour](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/tintinweb/smart-contract-sanctuary+lang:Solidity+content:%22I*%5C%5C%28*%5C%5C%29%5C%5C.safeTransferFrom%22++&patternType=regexp&case=yes). 

You can make this even worse by defining an external library function and making `I(addr).functionCall()` to be a `delegatecall` instead of `call`.

A controversial suggestion to fix this is to disallow `using for` for interfaces. However, I think this might be impractical citing the widespread usage.

**Comment by cameel** [comment]
If it made its way into OpenZeppelin then it might be a bit too late for disallowing this. `SafeERC20` seems to have been introduced in 2017 (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/413, around the time of Solidity 0.4.11). The fact that it's still there and even has a comment suggesting `using SafeERC20 for IERC20` indicates that at least OZ team embraces it as a pattern as worth supporting. We should at least discuss this with them. Maybe opening a topic on the OZ forum to gather some feedback would be a good idea?

I think that one reason for this pattern is convenience - repeating the library name makes the statement longer - so maybe replacing it with a free function would be a viable alternative.

Another might be that users are often familiar with other interfaces that do have `safeTransferFrom()` and using this method on also on `IERC20` may seem natural to them. This one might be a harder sell as a free function. On the other hand I'm not sure if this similarity is actually a good thing. After all `SafeERC20.safeTransferFrom()` makes the call is "safe" in a different sense than e.g. `IERC721.safeTransferFrom()` does. So this pattern probably steers less experienced users towards these alternative functions but on the other hand might muddle things up for more experienced users.

**Comment by chriseth** [comment]
I don't see this as a problem.

**Comment by hrkrshnn** [comment]
To put this in more context, one of them is an external call to a contract, the other one is an internal function call:

```solidity
    function _withdrawToken(address _token, uint _amount, bool _IsSafeTransfer) internal returns (bool) {
        require(_amount > 0);
        require (tokenUserAmountOf[_token][msg.sender] >= _amount);

        tokenUserAmountOf[_token][msg.sender] = tokenUserAmountOf[_token][msg.sender].sub(_amount);
        if (_IsSafeTransfer) {  
            IERC20(_token).safeTransfer(msg.sender, _amount);       
        }
        else {
            IERC20(_token).transfer(msg.sender, _amount);           
        }

        emit OnWithdraw(_token, msg.sender, _amount, tokenUserAmountOf[_token][msg.sender]);
        return true;
    } 
```

[source](https://github.com/tintinweb/smart-contract-sanctuary/blob/master/contracts_tronscan/mainnet/TU/TUKDvWbgE86LDBL4EmGzx3EQ4RnkycWyAB_KiaToken.sol#L390)

**Comment by ekpyron** [comment]
I wonder how much overlap this pattern has with
```
abstract contract SafeERC20 is IERC20
{
    function safeTransferFrom(...) internal { ... }
}
```
(can't be used on plain contracts implementing IERC20 only, but if you cast from ``address`` anyways, you might as well cast to this one)
