### ISSUE TITLE
Clean up the helpers around errors

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11959]
For severity some places use strings, while others the enum.

Apparently it's also indirectly used by other places in the compiler, like CommandLineInterface.cpp, that do not adhere to the severity standard:
```
solc/CommandLineInterface.cpp:		formatter.printExceptionInformation(_exception, "Compiler error");
printExceptionInformation(SourceReferenceExtractor::extract(m_charStreamProvider, _exception, _severity));
```

_Originally posted by @leonardoalt in https://github.com/ethereum/solidity/pull/11606#discussion_r704815675_

**Comment by cameel** [comment]
For anyone who will be implementing it: a good way to find places that use severity values other than `error`, `warning` or `info` is to assert in `SourceReferenceFormatter::printExceptionInformation()` that it must be one of these three values, then run command-line tests.

**Comment by YashAtwal** [comment]
I would like to resolve this issue
