### ISSUE TITLE
Function to convert integer to string

### ISSUE THREAD

**Issue by kailash360** [ethereum/solidity#11950]
It would be very useful to add some functions converting different data types to strings. It will definitely increase the reach of solidity in fields other than Ethereum Blockchain.

**Comment by hrkrshnn** [comment]
IMO, this should be done by libraries. For one, there is no clear way to do this; so there isn't a strong reason to have this in the language. For example, for `uint256 -> string`, should it be in hex, decimals or binary? Should it have zero padding, etc?

Regardless, I would be curious to know what kind of conversions that you think should belong to the language.
