### ISSUE TITLE
[Yul Optimizer] Improve loop variables

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11964]
We just had an issue where we did a manual optimization in loop code in the ABI decoder. The optimizer should actually handle that on its own. What are the conditions for such an optimization?

Original code:
```
let offset := x
for { let i := 0 } lt(i, length) { i := add(i, 1) } {
  ... // no mention of i
  offset := add(offset, something)
}
```
replaced by
```
let offset := x
let end := mul(something, length)
for { } lt(offset, end) { offset := add(offset, something) } {
  ...
}
```
Of course, this only works if we know that `mul(something, length)` does not overflow. Can we at least go a small way in the direction?

**Comment by hrkrshnn** [comment]
I guess the replacement should look like
```
let offset := x
let offset := add(offset, mul(length, something))
for { let i := 0 } lt(i, length) { i := add(i, 1) } {
   ... // the rest of the loop
}
```

Even when `mul(...)` overflows, I think the values are the same as the overflow from `add`.

Maybe a generic way to solve this is to have a rule that converts:
```
let X := ...
for {let I := A} lt(I, B) { I := add(I, 1)) {
    X := add(X, S)
}
```
into 
```
let X := ...
X := add(X, mul(B, S))
for {let I := A} lt(I, B) { I := add(I, 1)) {
}
```

Something like this also came up in https://github.com/ethereum/solidity/issues/11586

**Comment by chriseth** [comment]
I don't understand - the initial optimization was getting rid of the index variable itself and instead does the loop via a variable derived from the index (implicitly by incrementing it at each loop iteration).

**Comment by chriseth** [comment]
Oh sorry: `offset` is used in the loop body, only `i` is not.
