### ISSUE TITLE
Warnings should not be coloured red on the console

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11961]
> I just noticed that `solc` formats both warnings and errors in red. Is that intentional? I saw the initial mockup in #3046 and there warnings were proposed to be yellow. But then #5511 had them all red for some reason and that's how it went in.

_Originally posted by @cameel in https://github.com/ethereum/solidity/issues/11507#issuecomment-919550891_

**Comment by axic** [comment]
@cameel @leonardoalt what colour does `info` gets?

**Comment by cameel** [comment]
Looks like you beat me to it :) #11962.
I proposed white because they are not meant to stand out.

**Comment by cameel** [comment]
I'm going to close this one since my issue covers the same thing and has a more detailed description.
