### ISSUE TITLE
Errors, warnings and infos should have different colors in terminal output

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11962]
Came up in https://github.com/ethereum/solidity/issues/11507#issuecomment-919550891.

## Description

Currently both `Error` and `Warning` are displayed in red in the terminal so errors do not stand out and warnings are not easy to discern from errors. I haven't checked, but I suspect that the info messages added in #11606 are red too.

The output would be more readable if warnings and infos had different colors. My proposal is to use yellow for warnings and white for infos. Infos will blend with the background that way but they are not meant to stand out anyway.

## Current Behavior
Here's a sample contract with a few bugs (`C.sol`):
```solidity
contract C {
    function f() public {}
}

contract D is C {
    function f() internal
    override {}
}
```

This is what the output of `solc C.sol --color` looks like currently:
![solc-compiler-errors](https://user-images.githubusercontent.com/137030/133339180-eb132c51-2557-4d87-8d1e-2593612c5708.png)

## Backwards Compatibility
Fully backwards-compatible. We do not provide any backwards-compatibility guarantees for ANSI sequences used in the terminal. Any tools that depend on the format of terminal output are expected to either use the `--no-color` flag or be able to deal with arbitrary colors.

**Comment by DeviousLab** [comment]
For anyone picking this up I'd wager this is the file you'd want to look at: https://github.com/ethereum/solidity/blob/develop/liblangutil/SourceReferenceFormatter.cpp
```
void SourceReferenceFormatter::printExceptionInformation(SourceReferenceExtractor::Message const& _msg)
{
	// exception header line
	errorColored() << _msg.severity;
	if (m_withErrorIds && _msg.errorId.has_value())
		errorColored() << " (" << _msg.errorId.value().error << ")";
	messageColored() << ": " << _msg.primary.message << '\n';

	printSourceLocation(_msg.primary);

	for (auto const& secondary: _msg.secondary)
	{
		secondaryColored() << "Note";
		messageColored() << ":" << (secondary.message.empty() ? "" : (" " + secondary.message)) << '\n';
		printSourceLocation(secondary);
	}

	m_stream << '\n';
}
```

**Comment by ekpyron** [comment]
We need to be careful to keep things readable both on light-on-dark and on dark-on-light terminals, etc. But thinking of the "white" for info as "uncolored" and due to the fact that we use yellow/orange already anyways, it should be fine for this.
