### ISSUE TITLE
LLL: consider moving wei/szabo/finney/ether from parser to builtins

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1197]
They are defined here: https://github.com/ethereum/solidity/blob/develop/liblll/Parser.cpp#L109 

@zigguratt would this be possible with LLL?

**Comment by zigguratt** [comment]
I'll take a look.

**Comment by zigguratt** [comment]
Defining wei/szabo/finney/ether as built-in macros would be straightforward. But they're used in `Parser.cpp` to populate `multiplier`, which is then used in the next line to define `quantity`. Without the preceding line defining `multiplier`, compilation fails.

Unless I'm missing the point entirely.

**Comment by axic** [comment]
They are used to define `1 finney` as a literal. Is that useful? How is that matching lisp? I would think they could be equally useful as a macro.

Removing them from the parser is easy though.

**Comment by zigguratt** [comment]
That could definitely be useful. As I said, defining a built-in macro for each denomination would be straightforward - as simple as, for example,

```
(def 'szabo (* 1000000000 1000))
```

similar to how "szabo" is defined in `Parser.cpp`. Or even more simply,

```
(def 'szabo 1000000000000)
```

saving a multiplication at runtime. For me it's less obvious how to remove those definitions from `Parser.cpp`! :)
