### ISSUE TITLE
Make type(x).max a constant expression

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#11978]
I was trying to write this piece of code

```
contract SomeContractNameYouDontCareAbout {
    mapping(uint256 => bool[type(uint8).max]) private _myPrivateMapping;
}
```

I get an error saying that `type(uint8).max` is not an integer literal or a constant expression.

I believe it should be a constant expression.

**Comment by cameel** [comment]
This has already been requested in https://github.com/ethereum/solidity/issues/11183. I'm closing this as a duplicate.
