### ISSUE TITLE
Allow casting to bool

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1200]
```
pragma solidity ^0.4.0;

contract BoolCast {

    function foo() {

        bool a;
        int b;
        uint c;
        address d;
        bytes32 e;

        a = b != 0;     // a = bool(b);
        a = c != 0;     // a = bool(c);
        a = d != 0;     // a = bool(d);
        a = e != 0;     // a = bool(e);
    }

}
```

It's very easy to cast to bool by comparing to 0. Why can't bool() me made to do this?

**Comment by chriseth** [comment]
I think you already answered your question :-)
The expression `b != 0` explains much better what happens. In general, solidity tries not to make as few assumptions about the encoding of values as possible and explicit type conversions work with these encodings.

**Comment by ethernomad** [comment]
Fair enough!
