### ISSUE TITLE
Reporting unused library references

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12008]
## Abstract
Currently the compiler does not report an error if you supply library addresses that do not match any library referenced in the compiled sources. I think the compiler should warn user about with a message at 'info' severity.

## Motivation
The current behavior is convenient for tools, which can simply pass in the list of all deployed libraries, without worrying whether they are actually used by the contracts being compiled or not. This is the case especially for incremental compilation where only a subset of contracts is being recompiled.

On the other hand this means that supplying a bad name does not result in an error. This does not make it easy for users to determine when they are doing it wrong.

## Specification
When a list of libraries is passed to the compiler using either `--libraries` option (on the CLI) or in `settings.libraries` (in Standard JSON), the compiler should check if all of them are present in the sources. Any that do not should be reported. The message should have 'info' severity and the compilation/linking should still succeed.

In assembly and linker modes the source of the library is not available. In that case the error should be based on whether the library address was actually used to replace a link reference in the bytecode.

### Example 1
- `contract.sol`:
    ```solidity
    library L {
        function f() public {}
    }
    contract C {
        function f() public { L.f(); }
    }
    ```
When compiled with:
```bash
solc contract.sol \
    --libraries "contract.sol:X=0x1111111111111111111111111111111111111111" \
    --libraries "test.sol:L=0x2222222222222222222222222222222222222222" \
    --libraries "contract.sol:L=0x3333333333333333333333333333333333333333"
```
this should result in the following messages:
```
Unused link reference: 'contract.sol:X'. Library not found.
Unused link reference: 'test.sol:L'. Library not found.
```
The compiler should continue despite the messages.

### Example 2
- `contract.sol`:
    ```solidity
    contract C {}
    ```
this should result in the following messages:
```
Unused link reference: 'contract.sol:L'. Library not found.
Unused link reference: 'contract.sol:X'. Library not found.
Unused link reference: 'test.sol:L'. Library not found.
```

### Example 3
This example should report the same messages as example 1. `contract.sol:L` should **not** be reported as unused despite not being referenced by `C` because the library does exist:
- `contract.sol`:
    ```solidity
    library L {}
    contract C {}
    ```

### Example 4
- `contract.yul`:
    ```yul
    {
        mstore(0x100, linkersymbol("contract.sol:L"))
    }
    ```
When compiled with:
```bash
solc --strict-assembly contract.yul \
    --libraries "contract.sol:X=0x1111111111111111111111111111111111111111" \
    --libraries "test.sol:L=0x2222222222222222222222222222222222222222" \
    --libraries "contract.sol:L=0x3333333333333333333333333333333333333333"
```
this should result in the following messages:
```
Unused link reference: 'contract.sol:X'. Library not found.
Unused link reference: 'test.sol:L'. Library not found.
```

### Example 5
- `contract.bin`:
    ```
    608060405234801561001057600080fd5b5060c78061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806326121ff014602d575b600080fd5b60336035565b005b73__$a83509b47300fb2872e107211bec0983bd$__6326121ff06040518163ffffffff1660e01b815260040160006040518083038186803b158015607857600080fd5b505af4158015608b573d6000803e3d6000fd5b5050505056fea2646970667358221220c2f72d183b0908ff6e63a38057ad4b11b727aad99e02b5e656f123d4fa91e36864736f6c63430008070033

    // $a83509b47300fb2872e107211bec0983bd$ -> contract.sol:L
    ```

When linked with:
```bash
solc --link contract.bin \
    --libraries "contract.sol:X=0x1111111111111111111111111111111111111111" \
    --libraries "test.sol:L=0x2222222222222222222222222222222222222222" \
    --libraries "contract.sol:L=0x3333333333333333333333333333333333333333"
```
this should result in the following messages:
```
Unused link reference: 'contract.sol:X'. Library not found.
Unused link reference: 'test.sol:L'. Library not found.
```

## Backwards Compatibility
The change is backwards-compatible because reporting a message at an info level does not interrupt the compilation.

**Comment by cameel** [comment]
Related: #12009.

**Comment by soroosh-sdi** [comment]
this issue sounds interesting, Can you assign it to me?

**Comment by cameel** [comment]
This would be a better one but I got some feedback on the #solc-tooling channel that perhaps just reporting unlinked references would be a better way to go about it. So we need to discuss this first. I'm going to add it to design backlog for now.

See https://github.com/ethereum/solidity/issues/12014#issuecomment-926517874 for some issues that would be useful to solve right now.

**Comment by axic** [comment]
I think this is fine at the info severity.

**Comment by chriseth** [comment]
This is kind of a feature, where the idea is that you have a set of libraries in your project and you compile all contracts supplying all libraries, whether the contract needs the library or not. If we want to restrict it, you first need to find out which contract needs which library. Info severity might be OK, but we should check with tooling to see if this is any problem to them

**Comment by cameel** [comment]
The feature was originally discussed on the tooling channel and no one protested so - do you think I should ask more directly?

The problem with it being so permissive is that this also makes it harder to notice that you did something wrong. For example dapp-tools has been using undocumened syntax that stopped working at some point and no one noticed for quite a while. And especially in manual usage case linking is pretty error prone.

Alternative idea: how about requiring a special marker to tell the compiler that the reference might be unused? E.g. adding `?` at the beginning? Tools could use that while by default an unused reference would be a warning.

Yet another way to do this check might be to treat unlinked references as errors/warnings  if `--libraries` option is used at all. I.e  you have to either not specify any libraries (you want to do manual linking or don't have any libraries) or specify them all.

**Comment by cameel** [comment]
We discussed it on the call today and decided that it's ok to implement it at info severity.

But overall this issue has a very low priority. I'm moving it to icebox in case someone wants to work on it but otherwise we probably won't implement it in the near future.

**Comment by cameel** [comment]
Looks like hardhat-preprocessor relies on being able to pass in unused references to some extent. As reported by @kuzdogan:
> There's this `"libraries":{"__CACHE_BREAKER__":"0x00000000d41867734bbee4c6863d9255b2b06ac1"}`, everywhere. I could track it into [hardhat-preprocessor](https://github.com/wighawag/hardhat-preprocessor/blob/dac6c715ce1fa5af83441302d655d8922cfc4880/src/index.ts#L179) and seems to be intended for what the name suggests. I guess this does not have any implications.

**Comment by kuzdogan** [comment]
Pinging @wighawag for `__CACHE_BREAKER__` if this is still needed as I see in most of the Sourcify verified contracts this field is `0x00000000d41867734bbee4c6863d9255b2b06ac1` and not a different value as expected from a cache breaker. The context is, I checked for the metadata of verified contracts and a lot of them had `"libraries":{"__CACHE_BREAKER__":"0x00000000d41867734bbee4c6863d9255b2b06ac1"` and I was able to trace it to hardhat-preprocessor

**Comment by wighawag** [comment]
The __CACHE_BREAKER__ is needed because hardhat did not have full proof cache management (though it might have improved since then, I did not check)

as for `0x00000000d41867734bbee4c6863d9255b2b06ac1` this is the hash of a config so if 2 user or 2 different source use the same config the cache breaker will still work as the source will differ and hardhat will handle that
