### ISSUE TITLE
Do not whitelist remapping targets

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12014]
Originally requested in https://github.com/ethereum/solidity/pull/11688#discussion_r714703117.

## Abstract
Normally, importing files from arbitrary directories requires whitelisting those directories using `--allow-paths`. That's not the case when the import contains a remapping. This automatic whitelisting should be removed.

### Example
This causes an error:
```bash
mkdir /tmp/{dir,anotherdir}
touch /tmp/anotherdir/contract.sol
cd /tmp/dir/
echo "import '/tmp/anotherdir/contract.sol';" | solc -
```
```
Error: Source "/tmp/anotherdir/contract.sol" not found: File outside of allowed directories.
 --> <stdin>:1:1:
  |
1 | import '/tmp/anotherdir/contract.sol';
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

While this does not:
```bash
echo "import '/tmp/dir/contract.sol';" | solc - /tmp/dir/=/tmp/anotherdir/
```

This is especially weird when the remapping does not really do anything:
```bash
echo "import '/tmp/anotherdir/contract.sol';" | solc - /tmp/anotherdir/=/tmp/anotherdir/
```

## Specification
Remapping prefixes, targets and contexts should not be added to allowed paths.

## Backwards Compatibility
The change is not backwards-compatible. Users relying on this behavior will have to start adding `--allowed-paths` to their commands.

**Comment by soroosh-sdi** [comment]
I like to try this issue, if it's not urgent

**Comment by soroosh-sdi** [comment]
I think we also need a new test case; I don't know you add tests for this kind of issues or not. a downside comes to my mind is that adding tests for such small issues could make running our tests so time consuming after couple of years.
EDIT: we have lots of tests in `CommandLineParser.cpp` which tests this feature implicitly.

**Comment by cameel** [comment]
It's not urgent but this is not the best moment to start working on this because #11688 and #12007 have not been merged yet and they change a lot regarding `--allow-paths`. In particular #11688 adds a complete suite of tests so testing this should no longer be a problem.

It's also a breaking change so it should be based on `breaking` rather than `develop` branch and will only be released in 0.9.0, some time in the future.

**Comment by cameel** [comment]
@soroosh-sdi If you're looking for a task, how about one of these?:
- #10298
- #9627
- #10308
- #11959
- #11870
- #7665

**Comment by soroosh-sdi** [comment]
please move this issue to `Done`, after merging #12021.

**Comment by cameel** [comment]
Sure. Move to "review in progress" now. It will get moved to "done" automatically when the issue is closed.

Merging needs to wait for #12150 unfortunately.
