### ISSUE TITLE
Dynamic tuple ABI encoding documentation is ambiguous?

### ISSUE THREAD

**Issue by JosephDenman** [ethereum/solidity#12010]
## Page

https://docs.soliditylang.org/en/v0.8.7/abi-spec.html#formal-specification-of-the-encoding

## Abstract

In the tuple encoding portion of the specification specification seems ambiguous, specifically the portion that describes how to encode dynamic tuples

"otherwise, i.e. if Ti is dynamic: ```head(X(i)) = enc(len( head(X(1)) ... head(X(k)) tail(X(1)) ... tail(X(i-1)) )) tail(X(i)) = enc(X(i))```"

Doesn't `head(X(i))` appear in its own definition? Can someone clarify this for me?

**Comment by cameel** [comment]
Well, it does but it does not mean you cannot compute it. That's what the note below refers to:

> Note that in the dynamic case, `head(X(i))` is well-defined since the lengths of the head parts only depend on the types and not the values.

The head of a tuple element is just a 256-bit number that represents the offset to the location where the dynamic data is stored. To compute that offset you only need to know `len(head(X(i)))` and for that you don't need to know the value of `head(X(i))`, only its type.

But in general I agree that these definitions are kinda dense and hard to process. We already have an issue about that (#11191) so I'm going to close this one.

By the way, any contributions are welcome. If you get through it and think you can propose something better (i.e. still concise but easier to read), feel free to submit a PR! Does not even need to be a full rewrite. Even just small tweaks that seem helpful to you might be ok as long as they fit in with the rest of the text.
