### ISSUE TITLE
[YulOpti] Induction variable loop optimizations

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12015]
[Context](https://matrix.to/#/!vVfTacneThsGqrLLFd:gitter.im/$PfU0mbPIG1VucTGbt4RWmkwIw8l4AzoEvQGwnhgJ4Y8?via=gitter.im&via=matrix.org&via=t2bot.io)
```solidity
struct Deposit {
    uint16 assetId;
    uint240 balance;
    uint priceInEth;
}
contract C {
    function f(Deposit[] calldata deposits) external {
        uint sum;
        for (uint i = 0; i < deposits.length; ++i) {
            sum += deposits[i].priceInEth;
        }
    }
}
```

generates the for loop: 
```
                let var_sum := 0
                let var_i := var_sum
                for { }
                lt(var_i, var_deposits_length)
                {
                    if eq(var_i, not(0)) { panic_error_0x11() }
                    var_i := add(var_i, 1)
                }
                {
                    let value := calldataload(add(add(var_deposits_offset, mul(var_i, 96)), 64))
                    if gt(var_sum, not(value)) { panic_error_0x11() }
                    var_sum := add(var_sum, value)
                }
```

The offset computation `add(add(var_deposits_offset, mul(var_i, 96)), 64))` can be improved:

```
                  let var_sum := 0
                  let var_i := var_sum
                  let var_offset := add(var_deposits_offset, 64)
                  for { }
                  lt(var_i, var_deposits_length)
                  {
                      var_i := add(var_i, 1)
                      var_offset := add(var_offset, 96)
                  }
                  {
                      let value := calldataload(var_offset)
                      if gt(var_sum, not(value)) { panic_error_0x11() }
                      var_sum := add(var_sum, value)
                  }
```

**Comment by chriseth** [comment]
Maybe to summarize: Whenever a variable (expression) has a linear dependency on the loop variable, we might consider computing that variable during loop increments itself.

In particular, if we have:
 - pre loop: `i := i0`
 - some expression/invariant inside loop body: `k * i + x0` (`x` and `x0` do not change inside the loop)
 - between loop iterations: `i'post = i + idelta`
 - `k` is a multiple of `idelta` (or `idelta` is `1`)
 - the expression is evaluated in each loop iteration (this is only a gas cost condition, not correctness)
then we can introduce a new variable `x` with the following added to the loop init:
  `let x := k * i0 + x0`
the following in the loop post:
  `x := add(x, k/idelta)`
and replace the expression by `x`

(something like that)

**Comment by hrkrshnn** [comment]
Relevant: https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/ive/
