### ISSUE TITLE
can support function name (4 bitys hash ) of another contract as arg of a function ?

### ISSUE THREAD

**Issue by pureland** [ethereum/solidity#1201]
actually I can do it  as follow 

```
contract add {
    function addf(uint a,uint b)constant returns(uint){
        return a+b;
    }
}
contract test{
    function add_(address a,uint funname, uint a,uint b )constant returns(uint){
            assembly {
                   mstore(0x0,funname)
                   mstore(0x20,a)
                   mstore(0x40,b)
                   call(sub(gas,0x32),a,callvalue,0x1c,0x44,0x60,0x20)
                   return(0x60,0x20)
            }        
    }
}
```

but it is not easy to calculate the mem offsize of input/output, I dont know if it would cover other memory for complicated function, because I don`t know the current memsize  
so if solidity support use function name as argument of another function in other contract directly.

**Comment by chriseth** [comment]
I think what you need is actually passing a function as an argument to another function. We are currently working on this and it should be finished soon: https://github.com/ethereum/solidity/pull/1122

**Comment by axic** [comment]
Function types were implemented since.
