### ISSUE TITLE
Support for BLS12 based signature verification

### ISSUE THREAD

**Issue by sudesh-supraoracles** [ethereum/solidity#12031]
Hi Team!

Since many protocols are putting BLS12 to use for digital signatures.
I want to verify BLS 12 based signature from Etherium smart contract.

Hoping for some positive inputs/response on this.

**Comment by hrkrshnn** [comment]
How do you want the compiler to support this? Can you show an example use-case?

**Comment by axic** [comment]
This cannot be supported without support from the underlying network. Implementing this purely in EVM assembly is not feasible.

There are multiple proposals to solve this on the network level, but they have been postponed. Proposals include [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) and [evm384](https://ethereum-magicians.org/t/evm384-feedback-and-discussion/4533). 

I'm going to close this as I do not think this is relevant for this repository.
