### ISSUE TITLE
Add a warning if a functional-style assembly expression leaves elements on the stack

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1204]
The following inline assembly code should generate a warning:

```
assembly {
sload(0)
}
```

While this one should not:

```
assembly {
let x := sload(0)
}
```

and this one is also fine:

```
assembly {
pop(sload(0))
}
```

In general, I think the rule should be: A maximally large functional-style expression should either return zero elements onto the stack or it should be used as part of a FunctionalAssignment

**Comment by axic** [comment]
Fixed by #1224.
