### ISSUE TITLE
Fix the documentation around the inline assembly

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1205]
In `./docs/control-structures.rst`, there is a table of mnemonics available in the inline assembly.
- `pop` is marked `*` for no good reasons
- `sload` is marked `-` though it pushes the result to the stack
- `pop` should be `pop(x)` and the description should be updated.

**Comment by axic** [comment]
There's already an issue for inline assembly: #1190.

**Comment by pirapira** [comment]
Yes, the titles look very similar.  Now I can close this one because its contents are already captured in #1217.
