### ISSUE TITLE
Move the content of grammar.txt into `docs` directory

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1206]
This issue discusses moving the content of `grammar.txt` into the documentation.

@chriseth:
The file `grammar.txt` is currently linked from the documentation. Instead, it should be included verbatim (and the grammar file deleted), i.e. there should be a block of text that is the grammar.

**Comment by axic** [comment]
It cannot be included verbatim, because RST doesn't seem to support verbatim includes. The closest is putting it into a block quote, which requires each line to be spaced:

```
Langauge Grammar
::

  This is
  the grammar
  text block
```

**Comment by pirapira** [comment]
@axic it is @chriseth who specified the verbatim style.  The description was edited heavily.   Personally I don't care if it's a text file or another format.

**Comment by axic** [comment]
Here's the RST docs: http://docutils.sourceforge.net/docs/user/rst/quickref.html#literal-blocks

**Comment by chriseth** [comment]
@axic sorry, I did not mean the technical term "verbatim", instead I meant it should be readable directly on the documentation website and the generated pdf.

**Comment by axic** [comment]
How about this: http://www.sphinx-doc.org/en/1.4.8/markup/code.html#includes

**Comment by pirapira** [comment]
Sounds perfect to me.
