### ISSUE TITLE
[Legacy codegen] Error code missing on revert

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12064]
The following contract reverts via both legacy and IR but only IR reports an overflow via a designated panic code, legacy does not.

It looks like there's something more than evaluation order at play here because legacy (due to left-to-right evaluation order) should panic on an overflow on evaluating the left-hand-expression (multiplication of the two max integer literals). But because legacy reverts without a panic, it must be doing so for a reason other than an arithmetic overflow. Out of gas is ruled out because that is a different EVMC status code (3).

```
contract C {
   function f() external returns (uint64) {
     (type(uint32).max * type(uint16).max) & this.f();
   }
}
// ====
// compileViaYul: also
// ----
// f() -> FAILURE, hex"4e487b71", 0x11
// gas legacy: 261895
// gas legacyOptimized: 267328
```

**Comment by chriseth** [comment]
I'm pretty sure this is only evaluation order: If you evaluate `this.f()` first, you will end up with out of gas eventually, but that will be propagated up the stack as "external call failed", which is a regular revert without error code.

If you evaluate the multiplication first, you will get a revert with "overflow" error code.

**Comment by chriseth** [comment]
Do you think it makes sense to create a branch that  changes the evaluation order? Or we could add a 'pragma' to switch old codegen to new codegen behaviour (at least as much as possible).

**Comment by bshastry** [comment]
> I'm pretty sure this is only evaluation order: If you evaluate `this.f()` first, you will end up with out of gas eventually, but that will be propagated up the stack as "external call failed", which is a regular revert without error code.
> 
> If you evaluate the multiplication first, you will get a revert with "overflow" error code.

That's the thing, one would expect an "overflow" error code for legacy (because left-to-right evaluation) and external call failed for IR, but it is actually the other way round which is what confused me.

**Comment by hrkrshnn** [comment]
I looked at the assembly. The optimized-yul code completely removes the function call. The IR does the operation before the call. The asm does the recursive call before the operations. 

But not sure if the order is valid behaviour. But just leaving the observation here.

**Comment by hrkrshnn** [comment]
For the legacy, the recursive call will eventually run out of gas because of the 63/64 rule. But there won't be any returndata in the last `call` that fails. Since `returndata` will be cascaded back, the result would be equivalent to `revert(0, 0)`.

That is, `f()` is same as:
```
function f() {
    revert(0, 0)
}
```

I think that explains the behaviour.

**Comment by bshastry** [comment]
This issue is a false positive that was wrongly filed by me because I mistook the legacy expression evaluation order to be left to right and not the other way round.

> Do you think it makes sense to create a branch that changes the evaluation order? Or we could add a 'pragma' to switch old codegen to new codegen behaviour (at least as much as possible).

This would be great! :-) Right now, I manually examine test cases to filter out false positives but errors happen (like this one).

**Comment by hrkrshnn** [comment]
@bshastry I think such a branch should already exist. @ekpyron had a PR that switched it. Let me find it.

**Comment by hrkrshnn** [comment]
Ah, https://github.com/ethereum/solidity/pull/11537 is the one I was referring to. You do already use this, don't you?

**Comment by bshastry** [comment]
Closing because false positive
