### ISSUE TITLE
Style guide: specify order of storage variable visibility versus immutability

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12072]
## Page

https://docs.soliditylang.org/en/v0.8.9/contracts.html?highlight=immutable#constant-and-immutable-state-variables

## Abstract

Should we prefer:

```
public immutable
```

Over

```
immutable public
```

**Comment by devtooligan** [comment]
I think we should go with the style guide's existing [recommendation for function modifiers](https://docs.soliditylang.org/en/v0.8.12/style-guide.html#function-declaration).  
![Screen Shot 2022-02-22 at 10 03 20 AM](https://user-images.githubusercontent.com/71567643/155192387-452d4d6d-9c1c-48f7-8705-15f94fde011f.png)

**Comment by cameel** [comment]
`immutable` does not fit into any category on that list though. It's a data location like `storage`, `memory` or `calldata` and you cannot have these on functions so they're not listed.

**Comment by devtooligan** [comment]
haha I was thinking `mutability` but I realize now that's different

still think we keep visibility first in line with functions !  😄
