### ISSUE TITLE
Document remappings in the --help output

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1207]
The concept of remappings is explained in the documentation, but it is not shown at all in the `--help` output.

**Comment by seancyw** [comment]
Hi, I would like to contribute. Can you explain further? It's my first time contribute for open source :)

**Comment by chriseth** [comment]
@seancyw thanks a lot! It's probably better to discuss this realtime in https://gitter.im/ethereum/solidity but in general, this is about condensing the information about remappings from https://solidity.readthedocs.io/en/develop/miscellaneous.html#using-the-commandline-compiler and adding it to the function `CommandLineInterface::parseArguments`. A good place is probably right before the example.
