### ISSUE TITLE
[Out of gas] External contract call runs out of gas via legacy codegen without optimization but not via IR

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12086]
```
type T0 is bool;
contract C0 {
  address  s1;
  constructor() {
    s1 = address(this);
  }
  function f1(T0[2] calldata i0) external returns(C0[2] memory o0) {
    assembly {
      o0 := slt(extcodesize(9), sub(mload(6), calldataload(mod(calldataload(mod(codesize(), calldatasize())), calldatasize()))))
      o0 := sload(o0)
    }
  }
}
// ====
// compileViaYul: also
// ----
// constructor() ->
// f1(bool[2]): true, false -> FAILURE
```

To reproduce run `isoltest -t test --show-messages`. With Optimization on, both legacy and IR run out of gas.

**Comment by hrkrshnn** [comment]
I think it accesses a large memory offset, going out of gas. If you replace `C0[2] memory o0` by `uint256 o0`, I think you should get a value larger than `2**32`.

**Comment by hrkrshnn** [comment]
Hmm, the `oO := sload(oO)` is weird though. So `oO` should be zero?

**Comment by bshastry** [comment]
Could reduce the test to the following

```
type T0 is bool;
contract C0 {
  address  s1;
  constructor() {
    s1 = address(this);
  }
  function f1(T0[2] calldata i0) external returns(C0[2] memory o0) {
    assembly {
      o0 := slt(0, sub(mload(6), calldataload(0)))
      o0 := sload(o0)
    }
  }
}
// ====
// compileViaYul: also
// ----
// constructor() ->
// gas legacy: 196801
// f1(bool[2]): true, false -> FAILURE,
```

Edit: Wrong reduction. The test case above does not fail.

**Comment by bshastry** [comment]
Closing because the most likely explanation for this is that `codesize()` affects the value of the `slt` operation in such a way that one codegen results in an `sload(0)` (a large number) and the other in `sload(1)` (zero). This in turn effects which memory location was dereferenced and can potentially lead to out-of-gas.
