### ISSUE TITLE
[Optimizer] Missed optimization opportunity in legacy optimizer

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12088]
Edit:

This issue is about missed legacy optimizer opportunities. Examples follow. All of the following get optimized out via IR but not legacy optimizer (latter runs out of gas) 

```
contract C {
  function f() external
  {
    // Legacy optimizer: o0 could be optimized out but isn't
    uint o0;
    assembly
    {
      if keccak256(1, not(0))
      {
        o0 := 1
      }
      stop()
    }
  }
}
// ====
// compileViaYul: also
// ----
// f() -> FAILURE
```

```
type T0 is address;
contract C {
  function f() external {
    // Legacy optimizer: l0 could be optimized out but isn't
    T0 l0 = T0.wrap(address(0x1Ea7bdE3C));
    assembly {
      l0 := mload(mod(keccak256(l0, signextend(0, 9)), 2))
    }
    T0[2] memory l2;
  }
}
// ====
// compileViaYul: also
// ----
// f() -> FAILURE
```

fails via legacy optimizer but not IR.

Repro

```
$ isoltest -t semanticTests/test --optimize --show-messages
```

**Comment by bshastry** [comment]
This may actually be a non-issue thanks to https://github.com/ethereum/solidity/pull/11026

Will wait for a confirmation.

**Comment by chriseth** [comment]
Yes, the keccak call is optimized out in the new code generator.

**Comment by chriseth** [comment]
Although the reason might not be that `keccak256` is evaluated, but rather that `l0` is unused.

**Comment by chriseth** [comment]
It is not removed in old codegen because a jump hides the fact that the value is unused. On the other hand, I cannot see why the jump is not optimized out - so maybe we should still investigate this a bit on that ground.

**Comment by hrkrshnn** [comment]
This `keccak` will not be evaluated, it's `keccak256(0x1Ea7bdE3C, 9)` and the optimizer doesn't know about memory at `0x1Ea7bdE3C`. What happens is that, since `l0` is unused, the `mload` and subsequently, the `keccak256` gets removed.

**Comment by hrkrshnn** [comment]
For old codegen, I think it's not getting inlined because the inlinable block is too large. We could of course tweak that parameter if we want.

**Comment by bshastry** [comment]
Ah I see. Just want to add that this (legacy out-of-gas and IR optimization) does not happen too frequently to stall fuzzing but something that is churned out by the fuzzer every once in a while. I'm not sure if such code reflects real-world coding patterns.

**Comment by hrkrshnn** [comment]
>  I'm not sure if such code reflects real-world coding patterns.

At least for these cases, where the actual code is supposed to access a very high memory index, likely wouldn't happen in practice. But it's still good to test against them; it's not something that we generally consider in our tests.

**Comment by hrkrshnn** [comment]
@bshastry we can close this, can't we?

**Comment by bshastry** [comment]
Looks okay to be closed to me but @chriseth feels

> On the other hand, I cannot see why the jump is not optimized out - so maybe we should still investigate this a bit on that ground.

**Comment by bshastry** [comment]
Edited issue. Summary: This is about missed optimization (by legacy optimizer) when a local Solidity variable is defined inside inline assembly but never used.

**Comment by chriseth** [comment]
I think this can still be closed.
