### ISSUE TITLE
[Docs] Mismatched Yul optimizer steps lists

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12081]
Looking at the list of Yul transformations in the documentation, I noticed a few slight differences between the list at https://docs.soliditylang.org/en/latest/yul.html#optimization-step-sequence and the list at https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-steps:

- [ ] In the second list, change FunctionalInliner to ExpressionInliner, just like in the first list.
- [ ] In the second list, change FullFunctionInliner to FullInliner, just like in the first list.
- [ ] Add UnusedFunctionParamterPruner to the first list.

Reported by @acoglio

**Comment by mau211** [comment]
Hey, I would Like to take up this issue

**Comment by mau211** [comment]
Hi For:  Add UnusedFunctionParamterPruner to the first list. The first list reference has 

> Abbreviation | Full name
What would be the abbreviation for UnusedFunctionParamterPruner.

**Comment by hrkrshnn** [comment]
@mau211 it's 'p'. You can find it listed in the following file:
https://github.com/ethereum/solidity/blob/b343e13244dacacf6e0b249e562ad4c44f0dcbc2/libyul/optimiser/Suite.cpp#L251
