### ISSUE TITLE
Library interfaces as a means for high level delegatecalls

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12096]
**Problem**: Solidity currently does not offer a way to do a high level delegatecall.

For example, to mimic a high level delegatecall to the following interface:

```solidity
interface I {
    function f(uint) external (uint);
}
```

one has to do the following:

```solidity
I impl = I(0x...);
require(address(impl).code.length > 0);
(bool sucess, bytes memory ret) = address(impl).delegatecall(abi.encodeWithSelector(I.f.selector, (...));
require(success);
uint ret_value = abi.decode(ret, (uint256));
```

----

**Proposal**: Library interfaces.

```solidity
library interface I {
    function g(uint) external returns(uint);
}
```

Now, the following is a high level `delegatecall`, that behaves exactly like the above code:
```solidity
uint ret_value = I(0x...).g(...);
```

Effectively the main difference between interfaces and library interfaces are that the former does a `call` or `staticcall`, whereas the latter does a `delegatecall`.

---

Inheritance: should we allow libraries to inherit from library interfaces? 

```solidity
library interface I {
    function f() external;
}

library L is I {
    function f() external {
        // the actual implementation
    }
}
```

---

They can be used as types and variables similar to how interfaces are used. This should cover applications mentioned in https://github.com/ethereum/solidity/issues/11695 (except for `new`).

For example:

```solidity
library interface I {
    function f() external;
}

library interface J {
   function g() external;
}

contract C {
    I immutable impl1;
    J impl2
    // Dynamic linking
    constructor(I _impl1, J _impl2) {
        impl1 = _impl1;
        impl2 = impl2;
    }

    // Now impl1.f() and impl2.g() are high level delegate calls.

    // some upgradability features
    function update_impl2(J _impl2) {
         impl2 = _impl2;
    }
}
```

**Comment by chriseth** [comment]
I don't see why a library should not be able to automatically be a library interface.

I think libraries should be able to inherit from (multiple) library interfaces so that you can ensure that the interface conforms to the interface.

**Comment by chriseth** [comment]
Another feature that people would maybe want to use (not sure we should add it) is to forward calls to unknown functions:
```
fallback() {
  impl1.__delegatecall(msg.data);
}
```
But maybe we can resort to low-level calls in this case.

**Comment by hrkrshnn** [comment]
> I don't see why a library should not be able to automatically be a library interface.

I think the two paradigms in this code `L.f()` and `l.f()` does not belong together. If we allow `l.f()`, then `L.f()` should be disallowed. I'm somewhat in favour of keeping `L.f()` because static linking is more efficient than using immutable.

```solidity
library L {
   function f() external {
       // ...
   }
}

contract C {
    L l = L(0x...);
    function example() external {
        L.f();
        l.f();
    }
}
```

**Comment by hrkrshnn** [comment]
Decided to talk with users of libraries and collect a bunch of questions to ask them.
