### ISSUE TITLE
`Duplicate tag position` when compiling Yul code defining multiple functions with the same name

### ISSUE THREAD

**Issue by d-xo** [ethereum/solidity#12090]
## Description

While updating dapptools to solc0.8.9 we noticed that the following yul program now produces a c++ exception when compiling with 0.8.9 (it was fine with 0.8.7).

```
> solc-0.8.9 --strict-assembly hi.yul
Warning: Yul is still experimental. Please use the output with care.

======= hi.yul (EVM) =======

Pretty printed source:
object "object" {
    code {
        calldatacopy(0, 0, 1024)
        {
            function z() -> x
            { x := y() }
            function y() -> x
            { x := z() }
        }
        {
            function z() -> x
            { x := y() }
            function y() -> x
            { x := z() }
        }
    }
}

Exception while assembling: /solidity/libevmasm/Assembly.cpp(720): Throw in function const solidity::evmasm::LinkerObject& solidity::evmasm::Assembly::assemble() const
Dynamic exception type: boost::wrapexcept<solidity::evmasm::AssemblyException>
std::exception::what: Duplicate tag position.
[solidity::util::tag_comment*] = Duplicate tag position.
```

## Environment

- Compiler version: 0.8.9
- Target EVM version (as per compiler settings): london
- Framework/IDE (e.g. Truffle or Remix): none
- EVM execution environment / backend / blockchain client: none
- Operating system: linux

**Comment by chriseth** [comment]
Thanks for reporting! My first hunch is that a workaround could be to rename the functions so that the names are unique, but of course, this should also compile as is.

**Comment by cameel** [comment]
I found a case that triggers an assertion at a different position in the same file on 0.8.9. Seems to be related to this issue - it's caused by Yul functions with the same name and different returns defined in different Solidity functions:

`contract.sol`:
``` solidity
contract C {
    function f() external {
        assembly {
            function x(i) -> a {}
        }
    }
    function g() external {
        assembly {
            function x(i) {}
        }
    }
}
```
```bash
solc --bin --experimental-via-ir contract.sol
```
```
Exception during compilation: /solidity/libevmasm/Assembly.cpp(350): Throw in function solidity::evmasm::AssemblyItem solidity::evmasm::Assembly::namedTag(const string&, size_t, size_t, std::optional<long unsigned int>)
Dynamic exception type: boost::wrapexcept<solidity::evmasm::AssemblyException>
std::exception::what:
[solidity::util::tag_comment*] =
```

EDIT: The example above is actually inline assembly while this issue is about Yul but I think the cause might be the same and #12139 might be a fix too.

**Comment by cameel** [comment]
I decided to report this case as a separate issue after all (#12158) because maybe for inline assembly solution should be different (we don't necessarily have to disable named labels) and because it can't be triggered by only giving the functions the same name.
