### ISSUE TITLE
Security hole in "Introduction to Smart Contracts" example

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#12101]
## Page

https://github.com/ethereum/solidity/blob/develop/docs/introduction-to-smart-contracts.rst

## Abstract

There's a huge gaping security hole in the second example you show under "Introduction to Smart Contracts". Not good form!

A user can send a negative amount to another address, stealing money from that other address.

Also the negative value can be so negative that after the transfer, the "recipient"'s account balance could go negative, and the "sender"'s account balance could be arbitrarily large. If there was a way to cash out of the system, e.g. via DeFi, an attacker could steal the entire order book's worth of currency.

`requires(amount > 0);` is what is missing.

## Pull request

https://github.com/ethereum/solidity/pull/12100

**Comment by lukehutch** [comment]
In fact I didn't add this to the pull request, but there needs to be a discussion of security in this introductory page, using this `requires` statement as an example. Solidity programmers need to think about security right from the beginning.

**Comment by hrkrshnn** [comment]
As explained in https://github.com/ethereum/solidity/pull/12100#pullrequestreview-773572898, the negative part is a non-issue.

What is the problem with the event?

**Comment by lukehutch** [comment]
I see, it is a `uint`. Sorry that I didn't notice that!

(I deleted the comment about `event` because it was incorrect -- please ignore.)
