### ISSUE TITLE
No way to reference struct members from assembly

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#12104]
If I have a struct variable, assembly code can only find the offset of the struct itself, and not of its members.

(This issue was found when trying to workaround the [excessive gas usage to access calldata](https://github.com/ethereum/solidity/issues/12103))

e.g.
the code below is doable, but error-prone.
```solidity
struct Struct {
   address a;
   uint xyz;
}

Struct calldata s;
assembly {
  let sender := calldataload(s) //first item
  let xyz := calldataload(add(s,32))
}

```

**Comment by chriseth** [comment]
Do you have an idea about how to solve it? Note that if we do that, we should provide a similar mechanism for memory and storage.

**Comment by drortirosh** [comment]
you do have `name.offset`. need something like `name.field.offset`. its merely a naming issue...

**Comment by haltman-at** [comment]
Thought: If you're going to do this, then in addition to providing the *actual* offsets (or for storage, offsets and slots), it might make sense to also offer the *relative* offsets (or for storage, relative slots), which could be accessible via the type itself.

(Or perhaps that should be "instead"?  In the context of state variables, it seems to me that both make sense; but in the calldata context, it might make more sense to just provide the relative information, as calldata variables actually live on the stack, after all, and therefore can't have precomputed actual offsets like state variables can.)

**Comment by haltman-at** [comment]
Hi!  Could this be reopened?

**Comment by drortirosh** [comment]
I also think this should be re opened.
It is a syntactic issue.
The syntax "varname.xxx" was hijacked at used only with reserved words "offset" and "length", and thus "varname.field" can't be used.
The problem would exist if we ever try to reference in assembly struct members named "offset" and "length"
My suggestion: use JavaScript notation, where obj.member and obj["member"] are semantically the same.
The 2nd syntax is required only took access members that are reserved words (in js, they are used it the field is not a single word)

**Comment by 0xdapper** [comment]
This should be reopened imo too. Would be really nice to get relative slot and offset of a given `struct` in storage instead of having to hardcode and risk it going out of sync from the storage layout itself.
