### ISSUE TITLE
doc: explain that contracts are types

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1211]
`types.rst` currently does not explain that a contract is a type.  In Solidity, it is possible to define a local variable that points to a contract.  This is used usually together with `new` keyword.

```
D d = new D(4);
```

We should also explain that contract types inherit from the address type.

**Comment by pirapira** [comment]
I guess libraries are not types.

**Comment by chriseth** [comment]
The type documentation is not exhaustive. Everything has a type but most types cannot be named in the source code.

**Comment by pirapira** [comment]
There should be some documentation about what has types and what does not.  I don't believe all types have types in Solidity.  There should be a name for those types that can be named in the source code.

**Comment by chriseth** [comment]
Most of them are called "type names"
