### ISSUE TITLE
[Legacy vs IR] Bitwise not of smaller width uint results in value that is uint256 in legacy vs smaller width uint in IR

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12111]
The following test passes via legacy but fails via IR. The `address` public state variable is of the same value (`~1` truncated to 160 bits or 20 bytes) via legacy and IR. However, the `uint` public state variable value differs. The latter is truncated to 184 bits via IR but not via legacy (untruncated).

```
contract C {
  address public s1;
  uint public s2;
  modifier m(uint184 i0) {
    assembly {
      let al0 := i0
      sstore(s1.slot, al0)
      sstore(s2.slot, al0)
    }
    _;
  }
  function f() external m ((~(uint184(1)))) {}
}
// ====
// compileViaYul: also
// ----
// f() ->
// s1() -> 0xfffffffffffffffffffffffffffffffffffffffe
// s2() -> -2
```

**Comment by bshastry** [comment]
Some evidence that dirty bits are only accessible via inline assembly (`s3()` returns the same value via legacy and IR). It is a bit weird that dirty bits are cleaned up for assignment to address type even inside inline assembly but the same does not happen for higher width uint.

```
contract C {
  address public s1;
  uint public s2;
  uint public s3;
  modifier m(uint184 i0) {
    s3 = i0;
    assembly {
      sstore(s1.slot, i0)
      sstore(s2.slot, i0)
    }
    _;
  }
  function f() external m ((~(uint184(1)))) {}
}
// ====
// compileViaYul: also
// ----
// f() ->
// s1() -> 0xfffffffffffffffffffffffffffffffffffffffe
// s2() -> -2
// s3() -> 0xfffffffffffffffffffffffffffffffffffffffffffffe
```

**Comment by chriseth** [comment]
I would say this is fine: The `uint184` value is cleaned after the `~` via IR, but it is not cleaned in the legacy codegen. Going through storage is not required for this to trigger.

**Comment by bshastry** [comment]
The difference to the signed immutables bug (https://github.com/ethereum/solidity/pull/12050/files) is that there a Solidity assignment statement does not already clean up (signextend properly) until the value is read in a non-inline-assembly operation.

Here, the truncation happens if the function argument is assigned to an intermediate Solidity variable that is then read via inline assembly i.e., 

```
contract C {
  function g(uint184 _i0) public returns (uint r)
  {
    uint r1 = _i0;
    assembly {
      r := r1
    }
  }
  function f() external returns (uint) {
    return g(~uint184(1));
  }
}
// ====
// compileViaYul: false
// ----
// f() -> 0xfffffffffffffffffffffffffffffffffffffffffffffe
```

Even if this is not considered a bug, I would document this behavior somewhere (or add a test case) before closing the issue.

**Comment by chriseth** [comment]
It is documented: https://docs.soliditylang.org/en/v0.8.9/assembly.html#conventions-in-solidity

**Comment by bshastry** [comment]
Another example that came up during fuzzing

```
contract C0 {
  function revertZeroToNBytes(uint8 _n) internal
  {
    assembly
    {
      revert(0, _n)
    }
  }
  function f() external
  {
    revertZeroToNBytes(uint8(type(uint16).max));
  }
}
```

Legacy returns 65535 bytes, IR returns 255 bytes. The difference is because IR cleans up the function argument before the call is made but legacy does not.
