### ISSUE TITLE
Re-check if the identity precompile should be used for memcopy

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#12127]
Since london, it could be cheaper again to use the identity precompile than mload / mstore in a loop to copy memory.

**Comment by axic** [comment]
I think only Berlin's EIP-2929 affects it, and nothing in London does.

However if the saving is not significant, then to avoid the potential for future repricing adversely affecting it, I would not enable it.

**Comment by cameel** [comment]
Some relevant discussion from the chat:

@hrkrshnn 
> A random idea: about this: https://github.com/ethereum/solidity/issues/12127. I think we should do it, a rough calculation is that a precompile staticcall should cost  about the same in case of  copying 2 words and get cheaper for more than 2 words.
> 
> Related to that, we should probably add a new built-in to Yul called `memcopy(in, insize, out)` that gets translated to `staticcall(gas(), 4, in, insize, out, insize)`. I think having a specific built-in in Yul should help us easily reason about redundant memory copies.

@cameel
> Regarding a new builtin - I'm not sure if it would help all that much, at least with the upcoming optimization steps.
> [RedundantStoreEliminator](https://github.com/ethereum/solidity/pull/11352) can already deal with memory read and written by `staticcall()` just as if it was a pair of `mload()`/`mstore()` and it does not really care about the content being read/written.
> [EqualStoreEliminator](https://github.com/ethereum/solidity/pull/12272) on the other hand only deals with simple single-slot store operations.
>
> Oh, one thing it might help with is that currently for `staticcall` we have to assume that arbitrary storage reads are possible during the call. So using it for memory copy in between two overlapping stores would prevent `RedundantStoreEliminator` from removing the redundant one.
I guess that with the builtin we could just assume that the precompile does not read or write any storage?

@hrkrshnn 
> Yeah, there are two things here. Loops are hard to work with. So if we can replace a for loop doing `mstore` by `memcopy`, analysis becomes easier. The other thing as you said is if you replace the loop by `staticcal(gas(), 4, ...)`, we'll need to start modelling `staticall` opcode's side-effects based on the address it calls.

**Comment by axic** [comment]
I'm in favour of having a built in yul, especially if it can be also used in inline assembly. Though we may want to consider making this more generic.

**Comment by cameel** [comment]
Marking as breaking since the way we will probably implement it (i.e. as a new Yul builtin) seems to be breaking.

**Comment by hrkrshnn** [comment]
> way we will probably implement it (i.e. as a new Yul builtin) seems to be breaking

I think it should be possible to implement it in a way that's not breaking. We did this when `basefee` was introduced. Alternatively, this can be an annotation similar to "memory safe", but for selecting the Yul dialect.

**Comment by ekpyron** [comment]
You mean, introduce the new builtin, but still allow to shadow it with user-defined functions (emitting a warning or so)? Yeah, always possible, never really nice, though... we could actually consider that for ``prevrandao``, though.

**Comment by cameel** [comment]
ok, if we have that option then I guess I'll remove the label since whether it's breaking or not will simply depend on whether we decide to do it in 0.9.0 or before.

**Comment by ekpyron** [comment]
Didn't we have a PR about this? Just because IIRC recently we changed our evmc/evmone integration to properly account for precompile gas, so now that PR should actually properly account for the gas difference.

**Comment by cameel** [comment]
We did: #12556.

@hrkrshnn wanna try again? :)

**Comment by hrkrshnn** [comment]
I have a feeling it's better to wait for https://eips.ethereum.org/EIPS/eip-5656 (memcpy) for this. There are some edge cases with the identity, when not enough gas is provided: https://github.com/ProjectOpenSea/seaport/blob/4f2210b59aefa119769a154a12e55d9b77ca64eb/contracts/helpers/PointerLibraries.sol#L226, and we should try to push for `memcpy` in Cancun or something very soon.

**Comment by ekpyron** [comment]
Well, if we do that, we may as well close this with the answer to the question raised in the issue being "no".
