### ISSUE TITLE
contribute to translating this documentation into the Persian language #translations 🌍

### ISSUE THREAD

**Issue by sarabavifard** [ethereum/solidity#12122]
{
 "name": "Persian",
 "code": "fa",
 "maintainers": ["saracodic", "firildax"]
}
@franzihei

**Comment by franzihei** [comment]
Hi @saracodic, 
Please refer to the solidity-docs org (https://github.com/solidity-docs) for all community translations related work.
If you want to add a new language, start by opening a PR to add your lang.json in here: https://github.com/solidity-docs/translation-guide/tree/main/langs.
Thanks!
