### ISSUE TITLE
[Documentation] Document the semantics of an inline assembly return in the context of a constructor

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12130]
The following contract does not initialize storage variable `s` as intended i.e., to 42. Strangely, the function call `g()` does not return anything, not even `0`.

```
function f() returns (bytes memory) { assembly { return(0,0) } }
contract C3 {
  uint public s;
  constructor() {
    s = 42;
    bytes memory ununsedVar = f();
  }
  function g() external returns (uint) {
    return s;
  }
}
// ====
// compileViaYul: also
// ----
// constructor() ->
// gas legacyOptimized: 93975
// g() ->
```

**Comment by hrkrshnn** [comment]
> The following contract does not initialize storage variable s as intended

I think it does. The `sstore` is still there, but the getters would not work. You can verify this by deploying the contract and then using a [`getStorageAt`](https://infura.io/docs/ethereum/json-rpc/eth-getStorageAt) call.

**Comment by bshastry** [comment]
> I think it does. The `sstore` is still there, but the getters would not work.

The sstore is there in legacy optimized code but not in IR optimized, sorry for not mentioning that detail earlier. It would be great if you could confirm this. I have a feeling this is because of a missed optimization opportunity (see https://github.com/ethereum/solidity/issues/12088).

> You can verify this by deploying the contract and then using a getStorageAt call.

Ah nice! Is it easy to onboard to infura for deploying/running compared to Remix? The reason I ask is that I've not used Infura and find Remix easy as a noob. But ofcourse if it's worth the effort, I wouldn't mind spending time on other platforms :-)

**Comment by hrkrshnn** [comment]
It doesn't really have to be infura, any eth node would work. You can, for example, deploy it locally in hardhat, and do something like (see https://hardhat.org/hardhat-network/reference/)
```js
await hre.network.provider.send("eth_getStorageAt", [
  "0x123...",
  "0x0"
]);
```

---

I see the `sstore` in both legacy and ir optimized.

**Comment by chriseth** [comment]
I cannot confirm that `sstore` is removed via ir:
```
    code {
        {
            mstore(64, 128)
            if callvalue() { revert(0, 0) }
            sstore(0x00, 0x2a)
            return(0x00, 0x00)
        }
    }
```

**Comment by bshastry** [comment]
> I cannot confirm that `sstore` is removed via ir:
> 
> ```
>     code {
>         {
>             mstore(64, 128)
>             if callvalue() { revert(0, 0) }
>             sstore(0x00, 0x2a)
>             return(0x00, 0x00)
>         }
>     }
> ```

Sorry, I mixed up test cases in the process of reducing them.

Here's the test case with one fewer sstore in IR but that's probably because of the order in which state variables in legacy and IR are initialized (inline and then constructor vs constructor and then inline assignment in IR)

```
function f() {
  assembly {
    return(0,0)
  }
}
contract C {
  uint public s = 1337; // Only legacy contains this sstore
  constructor() { s = 1; f(); } // IR and legacy contain this sstore
}
```

**Comment by chriseth** [comment]
Ok, right, I can confirm. The yul optimizer cannot remove the sstore (yet) but the opcode-based optimizer afterwards can. I believe this is because the callvalue check (the constructor is not payable) happens at different times.
