### ISSUE TITLE
[Codegen] Create2 not executed in legacy optimized code

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12147]
```
library L {
  function invalidCreate2() external returns (address addr) {
    assembly {
      addr := create2(0, 0, 1024, 0)
      invalid()
    }
  }
}
contract C {
  constructor() {
    try L.invalidCreate2() {
    }
    catch {
    }
  }
}
```

If one were to record calls made by EVM Host (see https://github.com/ethereum/solidity/blob/1e630fc5840bb12ad9bca2dcf1f6c534c9ba8d31/test/EVMHost.cpp#L857-L876), legacy optimized bytecode seems to not issue the `create2` call whereas IR optimized bytecode does.

**Comment by chriseth** [comment]
This is weird because I see `create2` is both assembly outputs. Can you re-check, please?

**Comment by bshastry** [comment]
Closing because I am no longer able to reproduce this.
