### ISSUE TITLE
ICE in UserDefinedValueType::underlyingType() when the the type is used before it is declared

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#12159]
## Description

This contract:
```solidity
contract C {
    Left[] pu1;
}
type Left is bytes2;
contract C {
}
```

produces:

```
Internal compiler error:
/solidity/libsolidity/ast/Types.cpp(2539): Throw in function const solidity::frontend::Type &solidity::frontend::UserDefinedValueType::underlyingType() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer

## Environment

- Compiler version:  0.8.10-develop.2021.10.14+commit.1e630fc5.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by agroce** [comment]
Fails on 0.8.10-develop.2021.10.18+commit.f50dcd45.Linux.clang too

**Comment by bshastry** [comment]
Thank you for reporting the issue! Smaller repro

```
contract C {
    Left[] pu1;
}
type Left is bytes2;
```

**Comment by agroce** [comment]
BTW, either solc is getting less buggy over time, or is being fuzzed pretty aggressively; my fuzzer instances don't come up with anything new very often now, though there is a minor sticking point that they report many instances of crashes due to `FixedPointType not implemented.` or solfuzzer hitting a stack limit in json parsing.
