### ISSUE TITLE
Allow multiple events with the same name (aka event overloading)

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#1215]
``` javascript
pragma solidity ^0.4.0;


contract TestIt {
    event A();
    event A(uint i);
}
```

Trying to compile this contract produces the following error.

``` shell
$ solc tmp/EventTest.sol --bin
tmp/EventTest.sol:6:5: Error: Identifier already declared.
    event A(uint i);
    ^--------------^
The previous declaration is here: tmp/EventTest.sol:5:5:
    event A();
    ^--------^
```

While these two events share a name, their topics are different and I believe should be allowed (the same way that duplicate function names are allowed as long as their argument types differ).

**Comment by axic** [comment]
Solidity properly encodes the signature whether the argument is present or not, so it should definitely work.

**Comment by mrdavey** [comment]
Is this still working in 0.5.0? I seem to be getting some errors related to this, where the wrong overloaded event is being emitted... 🤔

**Comment by chriseth** [comment]
@mrdavey please create a new issue with example code.
