### ISSUE TITLE
Generalized `FlagSet` class

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12152]
Related to https://github.com/ethereum/solidity/pull/11944#discussion_r711333725.

In #11944 we added the [`DebugInfoSelection`](https://github.com/ethereum/solidity/blob/develop/liblangutil/DebugInfoSelection.h) class that represents a set of flags for selecting various debug info components. It provides helpers for parsing these flags from CLI and Standard JSON input and allows iterating over the flags so that they do not have to be repeated every time (which is very error-prone).

The task here is to implement a generalized class representing such sets of flags and then refactor `DebugInfoSelection` and other classes that work in a similar way to use it:
- [`SolverChoice`](https://github.com/ethereum/solidity/blob/v0.8.7/libsmtutil/SolverInterface.h#L39-L107)
- [`ModelCheckerEngine`](https://github.com/ethereum/solidity/blob/v0.8.7/libsolidity/formal/ModelCheckerSettings.h#L115-L142)
- [`ModelCheckerTargets`](https://github.com/ethereum/solidity/blob/v0.8.7/libsolidity/formal/ModelCheckerSettings.h#L92-L113)
- [`CombinedJsonRequests`](https://github.com/ethereum/solidity/blob/v0.8.7/solc/CommandLineParser.h#L76-L98)
- [`CompilerOutputs`](https://github.com/ethereum/solidity/blob/v0.8.7/solc/CommandLineParser.h#L54-L74)
- [`OptimiserSettings`](https://github.com/ethereum/solidity/blob/v0.8.10/libsolidity/interface/OptimiserSettings.h) (this one has some non-boolean fields so it might not be a perfect fit for this).
- [`FunctionType::Options`](https://github.com/ethereum/solidity/blob/v0.8.13/libsolidity/ast/Types.h#L1259-L1289)

### Implementation notes.
I think that the best way to accomplish this is to make the class a template and have each specific set of flags derive from it. Only the fields themselves and the function that enumerates them would need to be defined in the derived class.

Another approach would be to make it a variadic template and define fields via template parameters. I'm not sure if this is doable though.

**Comment by axic** [comment]
There's also `OptimiserSettings` 😅

**Comment by cameel** [comment]
Added to the description.

**Comment by cameel** [comment]
Added `FunctionType::Options` to the list. This one does not really need parsing but is essentially a set of flags and could use other methods from such a class.
