### ISSUE TITLE
Document assembly-mode outputs and make them all available on the CLI

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12154]
Depends on #3870/#12074.
Part of #10274.

Currently the only outputs available in assembler mode on the CLI are: ``--asm``, ``--bin``, ``--ir-optimized`` and ``--ewasm``. `settings.outputSelection` in Standard JSON actually provides more (see [`StandardCompiler::compileYul()`](https://github.com/ethereum/solidity/blob/1e630fc5840bb12ad9bca2dcf1f6c534c9ba8d31/libsolidity/interface/StandardCompiler.cpp#L1343-L1484)). They should be selectable on the CLI too.

Also, `--ewasm` on the CLI currently includes the output of EVM->Ewasm translation. I think we need to define a new output for it, both on the CLI and in Standard JSON.

Finally, the outputs available in the assembler mode in Standard JSON are not documented. They should be listed in [Using the compiler > Input description](https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description).

## Backwards Compatibility
Adding new options on the CLI and in Standard JSON is a backwards-compatible change.

The only potentially incompatible part is the removal of the translation output from `--ewasm` but since the output selection on the CLI  was introduced very recently (not even merged yet: #12074), I think we should not consider this change breaking.

**Comment by KukretiShubham** [comment]
Can I be assigned?

**Comment by cameel** [comment]
This is probably not the best moment to take this task because it depends on #12074 which is still in review.

In the meantime, maybe you'd like to take one of these?
- #10275 (this one might be good as an easy warm-up for this task)
- #12119
- #11917
- #9601

**Comment by KukretiShubham** [comment]
Sure. Would like to work on #10275

**Comment by cameel** [comment]
#12074 has been merged to now this is fine to work on.
