### ISSUE TITLE
[Testing] Library deployment fails due to optimization error in an unrelated contract in a separate source file

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12161]
```
==== Source: su0.sol ====
pragma solidity >= 0.0.0;
contract C {
  bool immutable flag;
  constructor() {
    flag = true;
    // Add deploy infinite loop
    do {}
    while (true);
  }
  function getFlag() external returns (bool)
  {
    return flag;
  }
}
==== Source: su1.sol ====
pragma solidity >= 0.0.0;
library L0 {
}
// ====
// compileViaYul: false
// ----
// library: L0
```

fails during optimization. To reproduce,

```
$ cp test.sol test/libsolidity/semanticTests
$ isoltest -t semanticTests/test --optimize
```

Not sure why errors in contract should affect library deployment.

**Comment by chriseth** [comment]
isoltest always compiles all contracts - why shouldn't it?

**Comment by bshastry** [comment]
> isoltest always compiles all contracts - why shouldn't it?

Okay, I suppose it is fine. I'll close this issue because this is expected behavior and the root cause of the failed deployment is well-known (see https://github.com/ethereum/solidity/issues/11642)
