### ISSUE TITLE
Compile time constants in contracts not correctly analyzed

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12185]
I was hoping the following would work but it doesn't

```
contract C {
  uint public constant c = 3;
}
contract D {
  C c = new C();
  uint constant d = c.c() + 1;
}
```

```
$ solc test.sol
Error: Initial value for constant variable has to be compile-time constant.
 --> /tmp/t:6:21:
  |                                                                            
6 |   uint constant d = c.c() + 1;    
  |                     ^^^^^^^^^
```

Perhaps, it's a matter of maintaining the knowledge of constants in getter functions?

**Comment by hrkrshnn** [comment]
I don't think this should work. There should be no difference between `C` and an interface to `C`. In that respect, `c.c()` should always be an external call. So the compiler should not replace it with `3`.

**Comment by chriseth** [comment]
I agree. You don't really know what happens when you call `c.c()` - if you want the actual constant you should use `C.c` - I think that could work. In general, if you want constants to be available outside of contracts or in other contracts, put them outside contracts.

**Comment by bshastry** [comment]
> - if you want the actual constant you should use `C.c` - I think that could work.

afaik, `C.c` does not work at the moment at least not when it is assigned to another like typed constant.

Please let me know, if you prefer closing this issue or renaming it `make C.c accessible` or something. I'm fine closing it.

**Comment by chriseth** [comment]
Right, it only works for libraries. I think it's fine as it is, at least nobody has complained so far, and requiring constants to be at file level is fine I think.
