### ISSUE TITLE
"assert" example is a poor example

### ISSUE THREAD

**Issue by abliss** [ethereum/solidity#12189]
## Page

https://docs.soliditylang.org/en/v0.6.2/control-structures.html?highlight=assert#id4
## Abstract

The page describes "assert" saying that it "should only be used to test for internal errors, and to check invariants. Properly functioning code should never reach a failing assert statement; if this happens there is a bug in your contract which you should fix." By contrast, "The require function should be used to ensure valid conditions that cannot be detected until execution time. This includes conditions on inputs or return values from calls to external contracts." 

It then gives this example:
```solidity
pragma solidity >=0.5.0 <0.7.0;

contract Sharer {
    function sendHalf(address payable addr) public payable returns (uint balance) {
        require(msg.value % 2 == 0, "Even value required.");
        uint balanceBeforeTransfer = address(this).balance;
        addr.transfer(msg.value / 2);
        // Since transfer throws an exception on failure and
        // cannot call back here, there should be no way for us to
        // still have half of the money.
        assert(address(this).balance == balanceBeforeTransfer - msg.value / 2);
        return address(this).balance;
    }
} 
```

However, I believe the `assert` in this contract can indeed fail, if the passed argument `addr` is a contract whose `receive()` sends some money back to the Sharer before returning. (I don't know why the comment says that transfer "cannot call back here".)

## Suggested fix
Perhaps the `==` in the assert could be replaced with a `>=`?

**Comment by hrkrshnn** [comment]
> However, I believe the assert in this contract can indeed fail, if the passed argument addr is a contract whose receive() sends some money back to the Sharer before returning. (I don't know why the comment says that transfer "cannot call back here".)

Transfer currently only forwards at most 2300 gas. A value transferring call needs at least 9000 gas. Therefore, a callback cannot forward ETH. Callbacks can happen, though; but cannot transfer ETH or modify state in other ways.

Closing this for now. Feel free to comment if you have questions.
