### ISSUE TITLE
Documentation: merge the FAQ in the appropriate sections

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1219]
There are a lot of pieces of information which would be better to be merged at the appropriate locations. A lot is already duplicated. Many of the examples refer to outdated features (e.g. `import "mortal";`).

**Comment by chriseth** [comment]
Wohoo!

**Comment by axic** [comment]
Can we remove the chapter?

**Comment by ChrisChinchilla** [comment]
@axic The chapter? You mean the page?

**Comment by axic** [comment]
Well the chapter is a single page right now, but yeah, removing the entire thing.
