### ISSUE TITLE
Remove the extcodesize check for external calls that expect returndata

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12204]
Currently, a high-level call `C.f(...)` does an `extcodesize` check before the `call`  and reverts if the address has empty code. However, this check can be avoided for function calls that are expected to return data. Because such calls are followed up by abi decoding the return data, which has a check for `returndatasize` is being at least a non-zero number. So for empty contracts, they would always revert in the end.

**Proposal**: remove the `extcodesize` check for high-level calls, if such functions have return variables.

Note: because of EIP-2929, this saves 100 gas.

Example

```solidity
interface I {
    function f() external;
    function g() external returns (bool);
}
contract C {
    I immutable i = I(address(0x1234));
    function test() external {
        // Skip extcodesize check in this case.
        // Becuase when ABI decoding the return data of the call
        // it checks if the return data is at least 32 (?) bytes.
        // Note: it does not matter if `i.g()` is assigned to a value
        // the return data is always checked.
        bool b = i.g();
        // Do not skip extcodesize check in this case.
        i.f();
    }
}
```

**Comment by chriseth** [comment]
Both abi decoders use
```
	size_t encodedSize = 0;
	for (auto const& t: _typeParameters)
		encodedSize += t->decodingType()->calldataHeadSize();
```
and then check that the return size is at least encoded size. This means we can remove the extcodesize check if `encodedSize` is nonzero (we should not rely on the number of return parameters).
Also, we can only do this if
 - we have an evm version that supports returndatasize and
 - revert strings are disabled (the extcodesize check has a different message)
