### ISSUE TITLE
call(encodeWithSelector) is too expensive

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#12217]
the construct
```solidity
address(target).call(encodeWithSelector(Target.myMethod.selector));
```

Should be equivalent to:
```solidity
target.myMethod();
```

However, it is far more expensive - ~400 gas more.
(the actual waste is even larger, considering that normal call performs check of the address before the call, and checks for revert afterwards, while address.call does no extra checks)

The difference is even larger if parameters are also encoded.

following is a sample code to test in remix

```solidity

// SPDX-License-Identifier: GPL-3.0-only
pragma solidity ^0.8;

contract TestCall {
    Z atest = new Z();

    //takes 26302 gas
    function runNormal() external {
        atest.test();
    }
    
    // takes 26676 gas
    function runWithCall() external {
        address(atest).call(abi.encodeWithSelector(Z.test.selector));
    }
}

contract Z {
    function test() external {
       emit Debug(msg.data);
    }   
    event Debug(bytes data);
}
```

**Comment by hrkrshnn** [comment]
I think the overhead is because of extra memory copies.

**Comment by drortirosh** [comment]
probably. but the question why there are those extra memory copies?

**Comment by chriseth** [comment]
The Solidity optimizer currently does not have a concept of lifetime of memory objects. Because of that, the `bytes` created in `abi.encodeWithSelector(Z.test.selector)` is persistently allocated while in `atest.test();` is it allocated only temporarily.

I'm closing this since we are very aware of this optimization opportunity.
