### ISSUE TITLE
Why is struct_copy.sol so badly optimized?

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#12211]
Most of the `mstore` calls in https://gist.github.com/chriseth/05075e7706c8ea3f1ac628a28be486f7 are redundant and also the `keccak` call should only be evaluated once. Why does it perform so badly?

**Comment by chriseth** [comment]
The example here is
```
    mstore(_1, var_k)
    mstore(0x20, _1)
    sstore(keccak256(_1, 0x40), 0x01)
    mstore(_1, var_k)
    mstore(0x20, _1)
```

The optimizer performs so badly because the redundant store eliminator ( #11352 ) only removes stores if they are not read from. What is needed here is removing stores that store the same data that is already present at that location.

**Comment by chriseth** [comment]
The `mstores` are removed by https://github.com/ethereum/solidity/pull/12272 so this is nice, but we still need to replace the keccak calls to a stored local variable, i.e.
```
let x := keccak256(a, b)
let y := mload(c)
let y := keccak256(a, b)
```
should be optimized to
```
let x := keccak256(a, b)
let y := mload(c)
let y := x
```

**Comment by cameel** [comment]
After the recently introduced optimizer steps, is it now good enough? Or is there more easy work we can do on that?
