### ISSUE TITLE
--formal to output runtime opcodes in Isabelle/HOL code

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1222]
This issue keeping track of feeding an input to Isabelle/HOL.  The scope of this issue is just to print runtime opcodes in the Isabelle/HOL format in a binary search tree.

Due to performance reasons(*), the opcodes are prefixed with some category.  Since it takes about 10 minutes to convert a 500-element list into a binary search tree in Isabelle/HOL, the format is already in a binary search tree.

```
⟨Suc (Suc 0), ⟨ Suc 0, ⟨⟩, (0, Stack (PUSH_N [0])), ⟨⟩⟩,
        (1, Unknown 0), ⟨Suc 0, ⟨⟩, (2, Pc JUMP), ⟨⟩⟩⟩
```

Here `Suc 0` and `Suc (Suc 0)` denote the depth of the tree.  This one is an AVL-tree but the input does not need to conform the AVL invariants.  It just needs to be somehow balanced.

(*) In Isabelle/HOL, defining an inductive type of `n`-elements take `O(n^2)` time.  This is because inductive types need to be translated into first-order formulae, where statements like "the first element ≠ the second element", "the second element ≠ the fifth element" and so on need to be stated.

**Comment by pirapira** [comment]
(Now I can parse the hexcode in Isabelle/HOL.  So this one is not urgent.)

**Comment by pirapira** [comment]
Parsing in Isabelle/HOL takes time, so this issue is eventually necessary.

Moreover, parsing a list in Isabelle/HOL takes time (as a result, analysis of one instruction took  a few minutes at one point).  Instead, when the program is stored in a binary search tree (from program counters to opcodes), the analysis is more than 30 times faster.  I need to change the description of this issue so that it contains the binary search tree format.

**Comment by pirapira** [comment]
I updated the topmost description with a binary tree example.

**Comment by axic** [comment]
Is this still needed? Would be quite easy to output it from Julia.

**Comment by pirapira** [comment]
I don't think so.  Meanwhile I wrote a bytecode parser in Ruby, that emits Isabelle/HOL.
