### ISSUE TITLE
[SMTChecker] ICE in void solidity::frontend::CHC::externalFunctionCall(const solidity::frontend::FunctionCall &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#12222]
## Description

Compiling:

```
pragma experimental SMTChecker;
library L {
       function f() public {
        (bool success, ) = address(10).staticcall{gas: 3}("");
    }
}
```

```
Internal compiler error:
/solidity/libsolidity/formal/CHC.cpp(794): Throw in function void solidity::frontend::CHC::externalFunctionCall(const solidity::frontend::FunctionCall &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer

## Environment

- Compiler version:  0.8.10-develop.2021.11.2+commit.a7b13782.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by agroce** [comment]
Conceivably related to #11341, but I'm basing that on the symptom alone, really.

**Comment by leonardoalt** [comment]
Thanks!
