### ISSUE TITLE
Fix gas expectations in the semantics tests

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12225]
In https://github.com/ethereum/solidity/pull/11974 I noticed that the tests seem to pass no matter what ``legacyOptimized`` gas costs were used for the deposit contract.
The expectation only got handled correctly with a value for ``--enforce-gas-cost-min-value 1`` in ``isoltest`` and also ``soltest`` doesn't seem to fail on wrong expectation.

**Comment by hrkrshnn** [comment]
Maybe related: https://github.com/ethereum/solidity/issues/11600

**Comment by ekpyron** [comment]
> Maybe related: #11600

It indeed also was the constructor call in my case, so maybe a duplicate - but the conditions under which it happens seem a bit fuzzy.

**Comment by cameel** [comment]
Which tests was that? #11974 has a lot of them :)

`--enforce-gas-cost-min-value` defaults to 100000 so maybe that is the issue? Do we want to lower it? Or make soltest not ignore it and instead have isoltest remove the directive if it's below min value?

**Comment by ekpyron** [comment]
As I said: it was the constructor for the deposit contract.
The gas expectations for that seem to be incorrect on develop even.

Try running ``build/test/tools/isoltest -t sem*/ext*/deposit* --enforce-gas-cost-min-value 1 --optimize`` and/or
``build/test/tools/isoltest -t sem*/ext*/deposit* --enforce-gas-cost-min-value 1`` on ``develop``.

Which means it's not only ``isoltest``, but also ``soltest``, since CI doesn't report the mismatch.

**Comment by ekpyron** [comment]
Also in both cases the value is way beyond 100000.

**Comment by cameel** [comment]
ok, in that case it does sound like a bug.

**Comment by ekpyron** [comment]
Actually it's also not only ``legacyOptimized``, but also ``ìrOptimized`` (just didn't notice it since you need to update legacy before it's even run).
