### ISSUE TITLE
Remove emscripten workarounds.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12235]
Looking into https://github.com/ethereum/solidity/issues/11689 I just saw:
```
# Patch soljson.js for backwards compatibility.
# TODO: remove this with 0.7.
# "viiiii" encodes the signature of the callback function.
sed -i -e 's/addFunction(func,sig){/addFunction(func,sig){sig=sig||"viiiii";/' libsolc/soljson.js
```
in ``solidity/scripts/ci/build_emscripten.sh.``.
We should try not to forget this for 0.9 at least.

**Comment by ekpyron** [comment]
Maybe we should have a label or sth to avoid missing stuff like this for breaking releases?
Or I can also just do it on the breaking branch right away.

**Comment by axic** [comment]
I don't think removing this is breaking. We promised to keep that backwards compatibility step for <0.7, so we can remove it anytime. I think this actually came up a few months ago.

**Comment by ekpyron** [comment]
Yeah, I was just about to say and wonder: we can probably also just remove it now.
