### ISSUE TITLE
Switch from js-ipld to js-multiformats in solc-bin

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12244]
While updating dependencies in https://github.com/ethereum/solc-bin/pull/100#issue-774215950 I noticed that [js-ipld](https://github.com/ipld/js-ipld), which we depend on seems to have been deprecated and replaced by [js-multiformats](https://github.com/multiformats/js-multiformats).

The task is simply to change the dependency and figure out what object to pass to `ipfsImporter()` instead of `IPLD` in [`ipfsHash()`](https://github.com/ethereum/solc-bin/blob/876858b2df0ea6f10b62e06485401db75176867c/update#L18-L22).

**Comment by hack3r-0m** [comment]
hi @cameel, I would like to work on it, can you tell me which branch to fork from to make changes?

**Comment by cameel** [comment]
The default branch of [solc-bin repo](https://github.com/ethereum/solc-bin/). It's called `gh-pages` rather than `master` due to historical reasons (it was used to serve Github Pages). Just make sure to start from the latest commit - https://github.com/ethereum/solc-bin/pull/100 has been merged today.

**Comment by elijahhampton** [comment]
Not sure if @hack3r-0m is still interested in this, but if not I'll give it a shot.

**Comment by cameel** [comment]
@elijahhampton Sure. Go ahead. Nothing has been done here so far so I think it's safe to reassign it at this point.

**Comment by elijahhampton** [comment]
> @elijahhampton Sure. Go ahead. Nothing has been done here so far so I think it's safe to reassign it at this point.

I just saw your comment.  Sure thing!

**Comment by elijahhampton** [comment]
@cameel https://github.com/ethereum/solc-bin/pull/108

I would be happy to take another look at this.  My first instinct was to re create the IPLD object swapping out the parts that multi formats could handle.

**Comment by 0xGeorgii** [comment]
@cameel is this still actual?

**Comment by 0xGeorgii** [comment]
@cameel I see there was no final solution so I grab it to solve as a prerequisite for #12332

**Comment by cameel** [comment]
Yeah, it's still up for grabs. There was an attempt to solve it before but unfortunately I did not manage to find time to review it in the end. Hopefully this time @r0qs can help.

By the way, #12332 is completely unrelated. I only suggested this issue there because it was simpler.

**Comment by 0xGeorgii** [comment]
@cameel I would like to hear a strategic approach for this. As I see there is no way to simply substitute the current version with the new one. So there are two options either leave it as is or rewrite this piece of code. I can proceed with the second one if it makes sense.

**Comment by cameel** [comment]
@GeorgePlotnikov We need something that's simple and low on maintenance. We're fine with adjusting our script to fit the new library, but we'd rather not have a big piece of boilerplate to do one simple thing. That script is already too big as it is. Basically, we need to find out what is currently the canonical way to calculate an IPFS hash of a file and do that. What we ended up with in https://github.com/ethereum/solc-bin/pull/108 is much, much better than what that PR started with, and the biggest issue was lack of manpower on our side to review it rather than some fundamental blocker. Still, it seems overcomplicated and I have a feeling that there must exist some wrapper in the IPFS libs that already does this boilerplate for us.

In the end, the solution from that PR was not *that* complicated so with some further simplification it might be acceptable. For example the support for different codecs/format feels like something we shouldn't really need in our use case. Without that maybe it would be simple enough.

**Comment by 0xGeorgii** [comment]
just to heads up: I'm not turned into a 🎃 but trying to understand how this library works and how to use it properly.

**Comment by 0xGeorgii** [comment]
@cameel what I have done is introduced a new small class as in #108 but with a bit more refactoring due to make is shorter, clearer and simpler. can you please give me a piece of advise now: how to test the solution and verify it?

**Comment by cameel** [comment]
@GeorgePlotnikov Get a fresh checkout of solc-bin, install JS dependencies, remove all the list files (`rm */list.json */list.txt */list.js`) and run `./update`. If it recreates the list files perfectly without introducing any changes to them, it's working correctly.
