### ISSUE TITLE
"UNLICENSED" (recommended for closed source in docs) is not a valid SPDX identifier, and the closest valid license (UNLICENSE) is the exact opposite. 

### ISSUE THREAD

**Issue by looksnap** [ethereum/solidity#12251]
from: https://docs.soliditylang.org/en/latest/layout-of-source-files.html?highlight=unlicensed#spdx-license-identifier

> If you do not want to specify a license or if the source code is not open-source, please use the special value `UNLICENSED`.

Except that, "Unlicensed" is not a valid SPDX identifier (find the list here: https://spdx.org/licenses/), and the closest valid license is the "Unlicense" (https://spdx.org/licenses/Unlicense.html), which is: "This is free and unencumbered software released into the public domain."

**Comment by looksnap** [comment]
And if you mean to say that "UNLICENSED" is a special value for Solidity specifically, perhaps you should change this special value to "None" or something that is less ambiguous. Etherscan uses "None" for no license, and "Unlicense" for public domain, and I've seen a couple contracts that use "UNLICENSED" in the SPDX, but chose "Unlicense" from the Etherscan dropdown.

**Comment by chriseth** [comment]
It is not a valid SPDX identifier on purpose. Using `UNLICENSED` here specifically says that you are not granted a license to use the source code in this form. It cannot be a valid SPDX identifier, since those are all licenses.

We decided to use `UNLICENSED` after the recommendation from npm: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license

**Comment by axic** [comment]
> We decided to use UNLICENSED after the recommendation from npm: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license

Perhaps we want to document this?

**Comment by tied2token** [comment]
I don't know if I can iam a trustee of the ietf and they just granted me
the ability to use any of there's

**Comment by looksnap** [comment]
Ok well, the most common place for the license to appear is in Etherscan and Bscscan, and you can find multiple verified contracts where the SPDX identifier is "UNLICENSED" but the License selected from the Etherscan/Bscscan dropdown is "Unlicense". Which one takes precedence?  

This indicates confused usage, regardless of whether that was the npm recommendation (which is a more generic recommendation anyways). Given the confusion in this specific area (solidity + smart contracts), I suggest the npm usage to not be followed.

At the very least, it should be well documented.

**Comment by caffeinum** [comment]
I asked a question on StackOverflow, too, before finding this issue.

https://opensource.stackexchange.com/questions/12410/is-there-a-difference-between-unlicense-org-and-spdx-unlicensed/12412#12412

**Comment by aspiers** [comment]
The fact that `UNLICENSED` is invalid SPDX also breaks validation by the REUSE license validation tool: https://github.com/fsfe/reuse-tool/issues/409
