### ISSUE TITLE
Documentation claims that 0x1F is a printable character

### ISSUE THREAD

**Issue by abacabadabacaba** [ethereum/solidity#12299]
## Page

[String Literals and Types](https://github.com/ethereum/solidity/blob/develop/docs/types/value-types.rst#string-literals-and-types)

## Abstract

> String literals can only contain printable ASCII characters, which means the characters between and including 0x1F .. 0x7E.

This implies that 0x1F is a printable character, but it is actually a control character.

**Comment by axic** [comment]
You are correct, [the code](https://github.com/ethereum/solidity/blob/develop/liblangutil/Scanner.cpp#L846) actually considers `0x20 ... 0x7E` (inclusive) as printable. The docs should be fixed.
