### ISSUE TITLE
CompilerContext::appendConditionalRevert does not conform to the memory model.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#12293]
Needs to be confirmed: Do we want the old codegen to conform to the memory model or not?

The function CompilerContext::appendConditionalRevert uses the fixed memory offset `0` - it should use the free memory pointer to be compatible with moving variables to memory.

**Comment by chriseth** [comment]
@ekpyron can you check when you are on again, please?

**Comment by ekpyron** [comment]
I moved this to https://github.com/ethereum/solidity/wiki#known-violations-of-the-memory-model
We're not likely to support stack-to-memory for legacy codegen, but it may be worthwhile to keep track of this behavior.
