### ISSUE TITLE
Confusing error message when a getter would return zero values and the compiler refuses to generate it

### ISSUE THREAD

**Issue by benediamond** [ethereum/solidity#12302]
Original title: "unusual behavior with mapping within struct within library".

## Description

When a library contains a struct type whose _only_ member is a `mapping`, and a contract contains a _public_ member of that struct type, then compilation fails with error `Internal or recursive type is not allowed for public state variables.`. But if you add a _further_ field in the struct (of type `uint256` for example), then compilation **does not fail**. This looks like a bug.

## Environment

- Compiler version: 0.8.10
- Target EVM version (as per compiler settings): compiler default (London)
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: MacOS

## Steps to Reproduce
`Lib.sol`
```solidity
pragma solidity 0.8.10;
library Lib {
    struct MyStruct {
        // uint256 myInt;
        mapping(uint256 => uint256) myMap;
    }
}
```
`A.sol`
```solidity
pragma solidity 0.8.10;
import './Lib.sol';
contract A {
    Lib.MyStruct public myStruct;
}
```
```
TypeError: Internal or recursive type is not allowed for public state variables.
 --> contracts/A.sol:6:5:
  |
6 |     Lib.MyStruct public myStruct;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
BUT IF YOU UNCOMMENT the commented line, then it compiles.

**Comment by cameel** [comment]
This is not really a bug but a limitation of automatically generated [getters](https://docs.soliditylang.org/en/latest/contracts.html#getter-functions):
> The mapping and arrays (with the exception of byte arrays) in the struct are omitted because there is no good way to select individual struct members or provide a key for the mapping:

When all members of the struct are omitted, your getter would not return anything and the compiler issues an error. This is by design. I agree that the error message for this is pretty bad and should be changed though.

Related issue: #11369.
