### ISSUE TITLE
`ConstantOptimizer` ignores the `runs` parameter when generating EVM assembly from Yul

### ISSUE THREAD

**Issue by lmittmann** [ethereum/solidity#12313]
## Description

When compiling the following code with optimizer enabled, solc always optimizes for contract size regardless of the "optimize-runs" arg.
The doc says the greater the runs-arg the more it is optimized for execution. So I would expect the optimizer to use PUSH32 at some point instead of PUSH4 and SHL. Is it possible to disable this specific "optimization" somehow? 

```
{
    mstore(0, 0xa9059cbb00000000000000000000000000000000000000000000000000000000)
}
```
## Got:
```
asm: 63a9059cbb60e01b60005200

PUSH4 0xa9059cbb
PUSH1 0xe0 
SHL
PUSH1 0x00
MSTORE
```

## Want: 
```
PUSH32 0xa9059cbb00000000000000000000000000000000000000000000000000000000
PUSH1 0x00
MSTORE
```

## Environment

- Compiler version: `Version: 0.8.10+commit.fc410830.Linux.g++`
- Target EVM version (as per compiler settings): `london`
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: `linux`

## Steps to Reproduce

```
# test.yul
{
    mstore(0, 0xa9059cbb00000000000000000000000000000000000000000000000000000000)
}
```

```
solc --optimize --optimize-runs=999999 --strict-assembly test.yul
```

**Comment by cameel** [comment]
This works as expected. It's just that in your input file all the instructions are treated as the creation code and that executes only once. Try the structure that the compiler produces when generating Yul from Solidity. That will make `--optimize-runs` actually affect the decision the optimizer makes here.

`test-runtime.yul`
```solidity
object "C" {
    code {}
    object "C_deployed" {
        code {
            mstore(0, 0xa9059cbb00000000000000000000000000000000000000000000000000000000)
        }
    }
}
```
### `--optimize-runs=999999`
```
solc test-runtime.yul --optimize --optimize-runs=999999 --strict-assembly --asm --debug-info none
```
```
======= test-runtime.yul (EVM) =======

Text representation:
  stop
stop

sub_0: assembly {
      0xa9059cbb00000000000000000000000000000000000000000000000000000000
      0x00
      mstore
      stop
}
```
### `--optimize-runs=1`
```
solc test-runtime.yul --optimize --optimize-runs=1 --strict-assembly --asm --debug-info none
```
```
======= test-runtime.yul (EVM) =======

Text representation:
  stop
stop

sub_0: assembly {
      shl(0xe0, 0xa9059cbb)
      0x00
      mstore
      stop
}
```
