### ISSUE TITLE
[help] Explicit type conversion not allowed from "uint256" to "int32"

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/solidity#12324]
I am having following error with the latest solc (`0.8.10`) version, which was not happening in the `solc versiona 0.7.*`

```
CompilerError: solc returned the following errors:

TypeError: Explicit type conversion not allowed from "uint256" to "int32".
   --> contracts/contract.sol:248:26:
    |
248 |         int32 core = int32(core);
    |                      ^^^^^^^^^^^
```

Would it be possible to fix it?

**Comment by cameel** [comment]
It's not a bug in the compiler. On 0.8.x you just need to explicitly convert it to `uint32` first. See [How to convert bytes1 to int8 in Solidity?](https://ethereum.stackexchange.com/questions/111261/how-to-convert-bytes1-to-int8-in-solidity) for an explanation of a similar problem.

**Comment by avatar-lavventura** [comment]
@cameel Thanks, I solved it via: `int32 core = int32(int256(core));` or `int32(int256(uint256(another_core)))` if the instance is `uint32`
