### ISSUE TITLE
Erc20 token transfer problem

### ISSUE THREAD

**Issue by jlinzhou** [ethereum/solidity#12338]
Can the erc20 token be  used in the following scenarios？
Address1 wants to  transfer erc20 token. Address1 gives the transaction to be sent to Address2. And Address2 signs the information related to the fee deduction and places it in the data data segment of the transaction. The transaction is then broadcast and the blockchain processes the transaction according to the rules.

**Comment by cameel** [comment]
This is not the right place to ask such questions. It's the bug tracker for the Solidity compiler and is meant for submitting reports about bugs in the compiler and feature requests. The compiler does not provide any ERC20 implementation. You can try on [#solidity](https://gitter.im/ethereum/solidity) gitter channel or https://ethereum.stackexchange.com instead.

If you're talking specifically about the OZ ERC20 implementation you could also ask on their [forum](https://forum.openzeppelin.com).
