### ISSUE TITLE
LLL: Allow initialization parameters to be passed in to a contract on deployment

### ISSUE THREAD

**Issue by zigguratt** [ethereum/solidity#1233]
Currently there is no way to pass parameters to an LLL-based contract on deployment in the way that Solidity contracts use constructors to accomplish this. We need to allow access to ABI-formatted data tacked on the end of the binary similar to how LLL's `lit` keyword does and, I'm told, similar to they way constructor parameters are stored in Solidity.

Adding this functionality would bring LLL to complete parity with Solidity with respect to being deployed, queried and manipulated from web3.

**Comment by zigguratt** [comment]
I've started investigating whether it's possible to accomplish this without any changes to the LLL compiler. I've created [a repository](https://github.com/zigguratt/lll-constructor) with the beginnings of a [contract](https://github.com/zigguratt/lll-constructor/blob/master/constructor.lll) that retrieves deploy-time parameters from the end of the runtime contract binary.

It doesn't work yet, but I think I'm close. Then again, it may not be possible!

**Comment by axic** [comment]
In order to accomplish this, there must be a new instruction added to LLL which emits the `PUSHSIZE` placeholder for Solidity's assembler.

@zigguratt added a WIP branch here, which introduces `(__pushsize)`: https://github.com/ethereum/solidity/tree/lll-constructor

At least it helps you to progress, but we'll need to review the actual syntax.

```
$ cat pushsize.lll 
(mstore 0 (+ 42 (__pushsize)))
$ lllc/lllc -x pushsize.lll 
6008602a01600052
$ evmasm -d 6008602a01600052
PUSH1 0x08
PUSH1 0x2a
ADD
PUSH1 0x00
MSTORE
```

It seems to work properly, 8 is the codelength.

**Comment by zigguratt** [comment]
Well that's excellent, @axic! I'll give that a shot. Thanks very much for your efforts.

**Comment by axic** [comment]
We have at least three options here:
1. have a built-in method, such as `(program-size)`
2. expose `PUSHSIZE` to libevmasm and use it as: `(asm PUSHSIZE)`
3. introducing a built in tag/label for end-of-code in the assembler and thus using `(asm [CodeEnd])`

The second option I think is cleaner, but is a change outsize lll.

**Comment by zigguratt** [comment]
Compiling that branch and using the temporary `__pushsize` operator I was able to get the parameters passed in via web3.

**Comment by zigguratt** [comment]
Exposing `PUSHSIZE` to libevmasm makes it more generally available, but having a `program-size` operator in LLL is cleaner from a source code perspective. Either way, it really helps the LLL-resurrection effort. Thanks again, Alex!

**Comment by zigguratt** [comment]
I've modified my `lll-constructor` test [repo](https://github.com/zigguratt/lll-constructor) to use the `__pushsize` operator. All works as expected now! When the [`lll-constructor`](https://github.com/ethereum/solidity/tree/lll-constructor) branch hits the Solidity main branch and gets released, I'll update my code to reflect the final state of the new operator, however it gets implemented.

**Comment by axic** [comment]
Irrelevant to how this will be internally implemented (either directly as a keyword or as a builtin mapping to the assembly) we need to come up with a name.

Some ideas:
- `program-size`
- `bytecode-size`
- `compiled-size`
- `lll-size` or `lllsize` (as a counterpart to the `lll` keyword)

Note that `lll <sequence> <memoffset>` wraps the passed sequence into a code block which is copied to the memory offset. `lllsize` will return the size of that given block. I think `lllsize` may be the best choice?

**Comment by zigguratt** [comment]
I'm leaning toward `bytecode-size`, myself. Doesn't the `lll` keyword return the size of the code that will be deployed to the blockchain, not the size of the binary that's running on deployment?

**Comment by axic** [comment]
If we would have symbols working properly, this could be a builtin:

```
(def 'contract (constructor body)
  {
    (constructor (lllsize))
    (returnlll (body))
  })
```

And used as:

```
(def 'constructor (args)
  ...)

(def 'body
  (panic))

(contract constructor body)
```

**Comment by zigguratt** [comment]
That makes things a lot clearer!

**Comment by axic** [comment]
We've come to a conclusion with @zigguratt to name it `bytecodesize`.

**Comment by zigguratt** [comment]
Thanks for your participation and efforts in this, @axic. This means a lot to the future of LLL despite the small code change.
