### ISSUE TITLE
Errors reported for modifier overloading should outright say that overloading is not allowed

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12332]
Error messages reported when you try to overload a modifier say that you cannot use the same name but do not say why. I think they should outright say that the cause of the error is that modifier overloading is not allowed. At least until we actually implement it (#72).

### Example 1: straightforward overloading
```solidity
contract C {
    modifier m(uint x) { _; }
    modifier m() { _; }
}
```
```
Error: Identifier already declared.
 --> test.sol:3:5:
  |
3 |     modifier m() { _; }
  |     ^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> test.sol:2:5:
  |
2 |     modifier m(uint x) { _; }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Example 2: overloading by inheriting from two bases
```solidity
contract A {
    modifier m() { _; }
}
contract B {
    modifier m(uint x) { _; }
}
contract C is B, A {}
```
This case is especially misleading because the message suggests that you should override the modifiers in the derived class but they aren't even virtual.

```
Error: Derived contract must override modifier "m". Two or more base classes define modifier with same name.
 --> test.sol:7:1:
  |
7 | contract C is B, A {
  | ^ (Relevant source part starts here and spans across multiple lines).
Note: Definition in "A":
 --> test.sol:2:5:
  |
2 |     modifier m() { _; }
  |     ^^^^^^^^^^^^^^^^^^^
Note: Definition in "B":
 --> test.sol:5:5:
  |
5 |     modifier m(uint x) { _; }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by elijahhampton** [comment]
Is anyone working on this?  I would like to take it on!

**Comment by cameel** [comment]
It's up for grabs. #12244 is probably simpler though so I'd suggest starting with that one. And going back to this one when you're done.

**Comment by 0xGeorgii** [comment]
hi @cameel can I take it?

**Comment by cameel** [comment]
If you're looking for a new issue to contribute, how about #9470? It already has an unfinished PR that you could use as a base: #13534.

We're focusing on getting the PR could down right now, so taking over an existing one would be very helpful if you don't mind :)

**Comment by 0xGeorgii** [comment]
@cameel yup, sure. I will consider #9470 and this one afterwards 😃

**Comment by cameel** [comment]
Great! But actually if you later want another issue, I can probably suggest a better one :)

We really need to rethink what gets labeled as `good first issue`. For now we've been often putting it on simple issues but when they're unrelated to what we're doing at the moment, their reviews either distract us away from roadmap work or the PRs sit unreviewed for a long time. We should review what's labeled and start selecting more relevant issues for this label. So if for some reason you really want to take this specific one, that's fine, but I could actually find you something that's more aligned with what we do currently :)

**Comment by 0xGeorgii** [comment]
@cameel  cool.  I don't have any specific wish to do exactly this one. I just used search 😄 I will get back to you after completing #9470.

**Comment by cameel** [comment]
Good. I can already suggest these:
- #13652
- #12783
- #13137
- #13496
- #10155

Generally bugfixes are always appreciated and these are currently marked as medium impact so they're all pretty relevant. Not all of them have detailed descriptions but with a repro it's at least easy to tell what's wrong and start working on it.

**Comment by cameel** [comment]
Bad error messages are an annoyance that I'd really like to see fixed. Maybe we should create a catch-all issue for this but until then, I'm going to keep this one open.
