### ISSUE TITLE
How  can I build solc v0.7.6 in aarch64 Architecture

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/solidity#12334]
I am working on the follow amazon instance `Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1020-aws aarch64)`. I was wondering would it be possible to install `solc v.0.7.6` into `aarch64`.

Installing `solc-linux-amd64-v0.7.6` freezes during the make process. Please note that `sudo snap install solc --edge` is able to install latest version of `solc v0.8.2` but I want to install its lower version (`v0.7.6`), which seems like not provided by the `snap`.

Any guide would be appreciated.

**Comment by cameel** [comment]
Have you tried to build the latest version (0.8.10) the same way (i.e. not from snap)? Does it have the same problem?

I have never really tried building on ARM myself but @axic said recently that at least on macOS it works fine without any tweaks needed and I assume the same should be true for Linux. You're saying that there are no errors in the log and make just hangs? Can you try to get more verbose output?

BTW, CircleCI now has support for Linux ARM and we're likely going to provide ARM release builds at some point. Unfortunately not yet. See #11351 if you want to track progress on that.

**Comment by avatar-lavventura** [comment]
I was using amazon instance with 1 GM RAM, that's why it was freezing.

When I increased RAM into 4 I was able to compile it without an issue for 0.7.6 and the latest version.
