### ISSUE TITLE
solc diagnostics to show either warnings or errors

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#12349]
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.0;

contract MyContract
{
    function f1() public pure
    {
        uint unused1; // [Warning 2072] Unused local variable.
        uint unused2;
    }

    function f2() public pure returns (uint)
    {
        return; // [Error 6777] Return arguments required.
        uint typeError = 3.14; // [Error 4486] Type error. (and unused and after return stmt)
    }
}
```

This snippet shows the error `6777` but not the warnings. If you comment out the return statement, the warnings are shown.

It should be expected to show always warnings along the errors.

**Comment by chriseth** [comment]
The compiler has different stages. If there has been an error inside one stage, the subsequent stages are not executed. This mechanism ensures that if a stage completes, the information it generates inside the AST annotations are always complete. For example, after the typechecker has run, you can be sure that every expression has an assigned type.

We can debate if some of the errors should allow subsequent stages to run, but to be honest, why not just fix the errors?

**Comment by christianparpart** [comment]
> We can debate if some of the errors should allow subsequent stages to run, but to be honest, why not just fix the errors?

We might need that for eventually adding completion, too.

**Comment by chriseth** [comment]
That's what we have `m_parserErrorRecovery` for.
