### ISSUE TITLE
Stop-after: full AST is available

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#12346]
The information contained in the AST is really useful. I think it's one of the best things about the compiler. In particular, I really appreciate stuff like `linearizedBaseContracts`, `referencedDeclaration`, `typeDescriptions`, `baseFunctions`, etc.

If I want all this information, as far as I know I currently need to run the full compiler pipeline. I assume (let me know if this is false) a significant speedup would be gained if it was possible to only request the full AST. I am wondering if it's possible to add an option to the `stopAfter` setting to do this.

One use case I have in mind is my [hardhat-exposed](https://github.com/frangio/hardhat-exposed) plugin where I generate Solidity contracts that automatically expose internal functions for testing. For this plugin I need to use most of the AST data I listed above. In my experience, any program that works with the AST eventually needs to know at least `referencedDeclaration`.

**Comment by chriseth** [comment]
We have this stage internally, but do not expose it. Depending on the interface, just not requesting any output that requires the bytecode should have the same effect. How do you interface to the compiler again?

**Comment by cameel** [comment]
Looks doable and pretty easy but I can't say exactly if savings would be worth it. `referencedDeclaration` is filled out by `TypeChecker` which runs somewhere in the middle of [analysis](https://github.com/ethereum/solidity/blob/2f95f3c6c6a2b68c58925fbc1f7f2f165e279602/libsolidity/interface/CompilerStack.cpp#L428-L580).

From a technical perspective it's no problem to add another value to `stopAfter` and slap an `if` to short-circuit it just after type checker (or any other part of the analysis for that matter), it's mostly a question of which stopping points make sense from the perspective of compiler's interface.

Also there are some implicit dependencies between analysis phases and such a partially filled AST output gets much less testing than a full run.

But overall looks like mostly a matter of making a design decision.

**Comment by cameel** [comment]
> We have this stage internally, but do not expose it. Depending on the interface, just not requesting any output that requires the bytecode should have the same effect.

That's a good point. I assumed it would not be enough because you can already do that by not requesting bytecode. But maybe that's actually enough for this use case? I have never tried to profile how much analysis takes relative to codegen - is the codegen that much heavier?

**Comment by frangio** [comment]
If you can confirm that not requesting bytecode should have the same effect I think we can close this issue.

**Comment by cameel** [comment]
Yeah. The compiler internally only generates artifacts on demand.

Just with one caveat (that only applies if you're **not** using Standard JSON): on the CLI this behavior has been introduced very recently (in 0.8.8, #11895). Before that the output for `--bin` would always be generated, even if not requested. Standard JSON had this behavior all along.
