### ISSUE TITLE
Identifier not found or not unique 

### ISSUE THREAD

**Issue by LOALtoken** [ethereum/solidity#12344]
## Abstract

 I don't know how to fix this. function buy_LOAL(address investor, uint BNB_invested)external can_by_LOAL (BNB_invested)

There's an error but I can't find it. Here's what the compiler points out: DeclarationError: identifier not found or not unique

**Comment by cameel** [comment]
This is a bug tracker for the Solidity compiler and is meant for reporting bugs in the compiler and requesting new features. If you need help debugging your contract you can try posting on the [#solidity](https://gitter.im/ethereum/solidity) gitter channel or [Ethereum StackExchange](https://ethereum.stackexchange.com).
