### ISSUE TITLE
sushiswap/trident: `StackTooDeepError` in the new Yul->EVM transform

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12343]
I'm trying to compile [Trident](https://github.com/sushiswap/trident) via IR to use it for benchmarking the optimizer. Unfortunately it runs into "stack too deep" errors both with and without the optimizer. The project compiles fine with the legacy codegen (also both with and without the optimizer).

If the legacy codegen has no problem with it then I guess it should be possible to improve the Yul->EVM transform to handle it as well. If not,  we should at least have some specific workarounds to recommend since it's a real-life project and has to be compilable one way or another once the IR codegen becomes the default.

Another problem is that the old EVM transform runs out of memory trying to compile this project. I'm not sure if the new transform replaced it completely or if it can still be used in some situations. If it can, we should to track down the problem and fix it.

### Repro
```bash
git clone https://github.com/sushiswap/trident
cd trident/
yarn install
find . test -name '*.sol' -type f -print0 | xargs -0 sed -i -E -e 's/pragma solidity [^;]+;/pragma solidity >=0.0;/'

solc \
    --bin \
    --optimize \
    --experimental-via-ir \
    --metadata-literal \
    --base-path . \
    --include-path node_modules/ \
    $(find contracts/ -name '*.sol' -type f | grep -v "contracts/flat/BentoBoxV1Flat.sol") 
```

Note: I'm excluding `BentoBoxV1Flat.sol` because it can't be compiled with 0.8.x (https://github.com/sushiswap/trident/pull/282). The problem is reproducible without it too.

#### New EVM transform (0.8.10)
If you run the above with sol 0.8.10, the compiler crashes with a `StackTooDeepError`:
```
Uncaught exception:
/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(77): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object&, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Cannot swap Variable var_nearestTick with Variable _4: too deep in the stack by 4 slots in [ RET var_upper var_nearestTick var_lower _1 _2 var_nearestTick var_currentPrice var_ticks var_upper var_amount var_feeGrowthGlobal0 var_nearestTick _1 var_upperOld var_secondsGrowthGlobal var_feeGrowthGlobal1 var_amount var_lower _3 _2 var_lowerOld var_ticks var_secondsGrowthGlobal var_feeGrowthGlobal1 var_feeGrowthGlobal0 _4 ]
[solidity::util::tag_comment*] = Cannot swap Variable var_nearestTick with Variable _4: too deep in the stack by 4 slots in [ RET var_upper var_nearestTick var_lower _1 _2 var_nearestTick var_currentPrice var_ticks var_upper var_amount var_feeGrowthGlobal0 var_nearestTick _1 var_upperOld var_secondsGrowthGlobal var_feeGrowthGlobal1 var_amount var_lower _3 _2 var_lowerOld var_ticks var_secondsGrowthGlobal var_feeGrowthGlobal1 var_feeGrowthGlobal0 _4 ]
```
Without `--optimize` the error is slightly different but it's still a `StackTooDeepError`:
```
Uncaught exception:
/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(95): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object&, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Variable var_amount_24379 is 9 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Variable var_amount_24379 is 9 slot(s) too deep inside the stack.
```

The compilation finishes successfully and produces IR if you replace `--bin` with `--ir-optimized` in the command.

#### Old EVM transform (0.8.9)
Running the above snippet with solc 0.8.9 on a machine with 32 GB RAM exhausts all available memory.

**Comment by cameel** [comment]
The [new ENS repo](https://github.com/ensdomains/ens-contracts.git) on the `master` branch (currently at [`ed365227`](https://github.com/ensdomains/ens-contracts/commit/ed3652275e71e8811c9ee690a14a6492f461a6d4)) is another project that runs into stack errors no matter whether optimizer is used:
- `viaIR: true, optimizer: {enabled: false}`
    ```
    YulException: Variable var__945 is 1 slot(s) too deep inside the stack.
    ```
- `viaIR: true, optimizer: {enabled: true, details: {yul: false}}`
    ```
    YulException: Variable var__945 is 1 slot(s) too deep inside the stack.
    ```
- `viaIR: true, optimizer: {enabled: true, details: {yul: true}}`
    ```
    YulException: Variable _5 is 1 too deep in the stack [ _5 usr$i usr$h _7 usr$scratch usr$k usr$f _4 usr$len usr$j_2 RET _2 _1 var_data_mpos usr$totallen usr$x _12 ]
    ```

**Comment by ekpyron** [comment]
If I force-enable stack-to-memory (it's disabled due to the inline assembly), then trident works.
Actually, none of the trident inline assembly actually touches memory. We could also detect that (i.e. detect lvalue references to solidity memory variables as well as memory-accessing opcodes would cover it I guess).

ENS is tricker - the inline assembly in there actually involves manual keccak and memory accesses. But also none that seem to violate the memory assumptions.

**Comment by cameel** [comment]
Two more projects that don't compile at all via IR due to stack errors: Uniswap v3 (#12532) and Euler (#12529).

On balance, in the other two there's at least one IR preset that works: Bleeps (#12531) and Yield Liquidator v2 (#12530).

**Comment by ekpyron** [comment]
Note: the euler contracts compile with a tiny change, i.e. with using
```
	auto generateSlotOnTheFly = [&](StackSlot const& _slot) {
		if (holds_alternative<FunctionCallReturnLabelSlot>(_slot))
			return true;
		return _aggressiveStackCompression && canBeFreelyGenerated(_slot);
	};
```
in ``StackLayoutGenerator::propagateStackThroughOperation``.

Actually that change has generally mostly positive effects, but at times (and especially for our the deposit and strings contracts in ``semanticTests/externalContracts``) results in ~2% increased code size... would be good to evaluate that a bit more carefully.

But it also means that ``_aggressiveStackCompression`` is not switched on in a critical situation here - it's probably during a jump or a cascading effect, that's also something that should ideally be fixed.

**Comment by cameel** [comment]
Another one that does not compile via IR: Tracer Perpetual Pools (#12561).

```Bash
#ir-no-optimize            # Compilation fails with "YulException: Variable var_amount_527 is 9 slot(s) too deep inside the stack."
#ir-optimize-evm-only      # Compilation fails with "YulException: Variable var_amount_527 is 9 slot(s) too deep inside the stack."
#ir-optimize-evm+yul       # Compilation fails with "YulException: Variable expr_mpos is 1 too deep in the stack"
```

**Comment by 0xdapper** [comment]
> Inline assembly that neither involves any operations that access memory nor assigns to any Solidity variables in memory is automatically considered memory-safe and does not need to be annotated.

From the latest docs it seems like the detection @ekpyron mentions is already implemented. I am seeking clarification if this includes any memory reads as well since it mentions "access" and not "write"s to memory. If it includes read as well, why is reading memory from memory considered unsafe?
