### ISSUE TITLE
Broken link in release post

### ISSUE THREAD

**Issue by Magicking** [ethereum/solidity#12356]
## Page

https://github.com/ethereum/solidity/releases/tag/v0.8.1

OK-> [https://blog.soliditylang.org/2021/01/27/solidity-**v**0.8.1-release-announcement/](https://blog.soliditylang.org/2021/01/27/solidity-v0.8.1-release-announcement/) (from above)
KO -> https://blog.soliditylang.org/2021/01/27/solidity-0.8.1-release-announcement/ (from blog)

## Abstract

The link for the blog post announcement is wrong it has a typo 'v' in front of the version tag.

## Pull request

Can't do pull request for that but release note can be edited at https://github.com/ethereum/solidity/releases/edit/v0.8.1 (you need to have the right access right)

**Comment by chriseth** [comment]
Thanks a lot, I just corrected it!
