### ISSUE TITLE
Solc fails compiling code with inline assembly when locale is set to Turkish

### ISSUE THREAD

**Issue by Shungy** [ethereum/solidity#12350]
## Description

Solc does not compile code with any inline assembly if the Linux system locale is set to Turkish.

## Environment

- Compiler version: any solc linux-amd64
- Target EVM version (as per compiler settings): any
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: linux

## Steps to Reproduce

Optional steps to get the same environment:

1. `docker run -it --rm ubuntu bash`
2. `apt update -y`
3. `apt install -y locales-all curl`

Then to replicate:

1. `export LANG=tr_TR.UTF-8`
2. `curl -O 'https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-contracts/master/contracts/utils/Address.sol'`
3. `curl -O 'https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.10+commit.fc410830'`
4. `chmod +x solc-linux*`
5. `./solc-linux-amd64-v0.8.10+commit.fc410830 --bin Address.sol` # compilation fails

You can then change `LANG` back to `en_US.UTF-8` and the compilation will succeed.

**Comment by chriseth** [comment]
Maybe related to the function `setDefaultOrCLocale` in main.cpp

**Comment by chriseth** [comment]
We should ensure that the same calls are made i libsolc.cpp

**Comment by Shungy** [comment]
I think I figured out the exact reason. Turkish capitalization rules are `i to İ`  and `I to ı`. I have realized that the both the inline assembly code I have tested have function names with letter `i`. So `extcodesize` is changed to `EXTCODESİZE` (notice dotted capital İ). This explains "function not found error".

**Comment by cameel** [comment]
Wow. I knew about this capitalization weirdness with Turkish "i" but I didn't even realize that it means that plain ASCII characters can be capitalized into ones from the Unicode set :) Maybe we should just randomly set system locale to Turkish in one of our CI runs just to catch problems like this :)

In any case, we do attempt to set the locale to `C` to avoid such problems and this bug means that somehow it's not enough. And once we fix it, we should recommend frameworks to set it on their side as a workaround because old binaries will still be affected.

@chriseth Isn't `libsolc` just statically compiled into the binary? Why would we have to set the locale there if `solc` already does that?

**Comment by chriseth** [comment]
libsolc has its own main function

**Comment by chriseth** [comment]
Or sorry: libsolc does not use the main function of the commandline interface - if you use solidity via js, you have to initialize it in a different way

**Comment by cameel** [comment]
Hmm... this is weird then - the problem is actually not reproducible via solc-js :) It only happens via solc. At least in the testing I did yesterday.

**Comment by itamarcps** [comment]
We had a similar issue with our C++ Desktop Wallet for Avalanche (https://github.com/avme/avme-wallet). The locale was causing a lot of trouble when dealing with non-standard file names (Like a file name with "é", or more specific, a file which the path includes "é", e.g. C:\Users\égrilo\AppData\Roaming\AVME\myfile.txt).

Our solution was using boost::nowide to set locale for boost::filesystem to properly read/write to files before running anything else, if you can integrate it as a dependency, I would recommend it.

https://github.com/avme/avme-wallet/blob/main/src/main-gui.cpp#L7

boost::nowide::nowide_filesystem(); is called right after running the program to kill any future issue, be aware that this solution requires you to use boost::nowide for every I/O operation to work, but it should be pretty straightforward to replace them, at least in our wallet, it was as simple as exchanging std::ifstream to boost::nowide::ifstream)

as referenced here;
https://github.com/avme/avme-wallet/blob/main/src/core/Utils.cpp#L327

On both Utils::readJSONFile and Utils::writeJSONFile functions.

**Comment by Shungy** [comment]
Turns out not just inline assembly is causing this. Running the following code with Turkish locale also fails to compile but with a lot more detailed output (383 lines) showing assembly input and errors.

Command: `export LANG=tr_TR.UTF-8 && ./solc-linux-amd64-v0.8.7+commit.e28d00a7 --bin test.sol 2> error.txt`

`test.sol`: 
```sol
contract Greeter {
    string private greeting;

    function greet() public view returns (string memory) {
        return greeting;
    }

    function setGreeting(string memory _greeting) public {
        greeting = _greeting;
    }
}
```

`head -5 error.txt`:
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/CompilerContext.cpp(463): Throw in function solidity::frontend::CompilerContext::appendInlineAssembly(const string&, const std::vector<std::__cxx11::basic_string<char> >&, const std::set<std::__cxx11::basic_string<char> >&, bool, const solidity::frontend::OptimiserSettings&, std::string)::<lambda(const string&)>
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Error parsing/analyzing inline assembly block:
Invalid assembly generated by code generator.
```

**Comment by Marenz** [comment]
the example in the last comment doesn't cause an ICE for me. Are there more steps required?

**Comment by Shungy** [comment]
> the example in the last comment doesn't cause an ICE for me. Are there more steps required?

Maybe you don't have the tr_TR.UTF-8 locale installed. I replicated again using the optional steps to get the same environment I wrote in my original post.

```
docker run -it --rm ubuntu bash
apt update -y
apt install -y locales-all curl less
export LANG=tr_TR.UTF-8
curl -O 'https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.7+commit.e28d00a7'
chmod +x solc-linux*
echo 'contract Greeter { string private greeting; function greet() public view returns (string memory) { return greeting; } function setGreeting(string memory _greeting) public { greeting = _greeting; } }' | ./solc-linux-amd64-v0.8.7+commit.e28d00a7 --bin - 2> error.txt
less error.txt
```

**Comment by wechman** [comment]
> In any case, we do attempt to set the locale to `C` to avoid such problems and this bug means that somehow it's not enough. And once we fix it, we should recommend frameworks to set it on their side as a workaround because old binaries will still be affected.

@cameel, Actually, we try to set locale to the system environment locale first. Only if it fails, we do attempt to set the locale to `C`:
https://github.com/ethereum/solidity/blob/e7d93f83769dd68c9d97e9be813595839dfcd1e2/solc/main.cpp#L52-L55

**Comment by cameel** [comment]
ok, so we should change that.

**Comment by wechman** [comment]
I did a little research on why this code is here and found [the original issue](https://github.com/ethereum/solidity/issues/674). Apparently, there was some problem with solc in case of invalid environment locale setting. 'export LC_ALL=C' was a workaround for that so I am not sure why solution involved environment default locale. Anyway, I agree we should change that.
