### ISSUE TITLE
An option that shows a storage location for each state variable

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1236]
For blockchain browsers and for bytecode annotations, it's useful if state variables are associated with storage indices.  This issue keeps track of adding such an output to the solidity compiler.
- [ ] which of the existing options shall output the association, or shall there be a new option?
- [ ] what is the output format?
- [ ] implementation

**Comment by chriseth** [comment]
Such a fixed table becomes ineffective as soon as you have structs or mappings. I would prefer the compiler to do things like output size information about the types used. On the other hand, if a blockchain explorer wanted to make any use of the value in storage, it has to know its encoding anyway and the encoding (and the order of the variables) is everything you need to compute the location.

**Comment by pirapira** [comment]
@chriseth I see.  Here I want to output the encoding as an executable program.

**Comment by chriseth** [comment]
Initial version implemented in https://github.com/ethereum/solidity/pull/7589
