### ISSUE TITLE
Would it be possible to install solc v0.7.6 using snap?

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/solidity#12367]
In `Ubuntu 20.04` node that uses [amd or arm] architecture, snap is not able to install v0.7.6 as a older version. Would it be possible to add `solc v0.7.6` as older version into snap? Related to this should I contact with snap?

For example for amd instances:

```
ubuntu@ip-172-31-40-250:~$ sudo snap info solc
name:      solc
summary:   Solidity - the Contract-Oriented Programming Language
publisher: Ethereum Build Automation (builds-c)
store-url: https://snapcraft.io/solc
license:   GPL-3.0
description: |
  Solidity is a contract-oriented, high-level language for implementing smart contracts. It was
  influenced by C++, Python and JavaScript and is designed to target the Ethereum Virtual Machine
  (EVM).

  Solidity is statically typed, supports inheritance, libraries and complex
  user-defined types among other features.
snap-id: CaErqkZuPgJ6qYTnxFQoryPUAhErAiiB
channels:
  latest/stable:    v0.5.16 2020-01-29 (6746)  36MB -
  latest/candidate: v0.5.17 2020-03-17 (6854)  36MB -
  latest/beta:      v0.6.8  2020-05-18 (6979)  43MB -
  latest/edge:      develop 2021-12-04 (7078) 324MB -
```

**Comment by mona1-jpg** [comment]
To tell you the truth I have no idea what I'm doing help me and we can
split what ever profit I have

**Comment by mona1-jpg** [comment]
Honestly I set this account up two years ago I heard of mining I found a
mobile and mining linked it together and every know and then I would get on
and try to figure it out you see I am still trying to figure out how to
verify all my contracts when I first opened the etherscan and the mining
app it asked me to enter a block number so what I. Did was generate a few
numbers based off the blocks I had seen typed in a few till it told me the
block number know is verified you see I'm not a greedy person I would be
happy with 35 % of my profits if I could trust someone enough to go on fix
what I may have done wrong I have at least 19 name tags that I didn't
verify but saved them with name tags so I know they were mines I don't know
if you can help me but we could both get something good going if you show
me how to do it step by step step by step

**Comment by avatar-lavventura** [comment]
Can someone ban @mona1-jpg

**Comment by cameel** [comment]
Not sure if snap stores specific older versions or only allows the latest one in each channel. Pinging @elopio, since he is the one managing the snapcraft packages.

In the meantime, if you need a specific version of the compiler I'd suggest to simply grab it from  [solc-bin](https://github.com/ethereum/solc-bin/). It contains static self-contained binaries, just download and run, no installation needed.

**Comment by avatar-lavventura** [comment]
For `aarch64` aws nodes, I need `arm64` binary for `v0.7.6``. 

In the `solc-bin` url I was not able to find it. If you can link me into the binaries page that will be helpful.

Please note that I am unable to see the binaries under ` https://solc-bin.ethereum.org/linux-arm64/` related to `v0.7.6`.

**Comment by mona1-jpg** [comment]
I have no idea can I trust you with my password look I'm give it to you if
you do me wrong no harm no foul but if you fix it we can both have enough
you 60%me 40% fair

**Comment by mona1-jpg** [comment]
Can someone ban you why would you ban me because I don't know my way around
it yet now that's absurd ban u I'm pray for you

**Comment by cameel** [comment]
Oh, you said "amd or arm" so I thought you're fine with either. If you specifically need an ARM build then yeah, unfortunately we don't have those in solc-bin yet (#11351).

Note that you can also use the [wasm binaries](https://github.com/ethereum/solc-bin/tree/gh-pages/emscripten-wasm32) via [solc-js](https://github.com/ethereum/solc-js) on ARM. They're not as fast as native ones and solc-js has more limited set of CLI options but at least they work everywhere.

**Comment by avatar-lavventura** [comment]
@cameel Thanks. From `wasm binaries` can I create a `./solc` binary file? As I understand I have to use them along with `solc-js`

**Comment by cameel** [comment]
No. You drop them inside solc-js dir (replacing the file called `soljson.js`) and then you can use the [`./solcjs`](https://github.com/ethereum/solc-js/blob/master/solcjs) script as the CLI. Or, to use it as a library in a JS program, you just import the package.

**Comment by avatar-lavventura** [comment]
@cameel Thanks
