### ISSUE TITLE
Resolving overloaded functions with implicitly convertible parameters

### ISSUE THREAD

**Issue by codywatts** [ethereum/solidity#1237]
Given the following Solidity code:

```
pragma solidity ^0.4.2;

contract OverloadedFunctionTest
{
    function overloadedFunction(bytes16 input) public constant returns(bool)
    {
        return true;
    }

    function overloadedFunction(bytes32 input) public constant returns(address)
    {
        return address(0x0);
    }
}
```

The following calls to `overloadedFunction` produce these compiler errors:

```
// Error: No unique declaration found after argument-dependent lookup.
overloadedFunction("hello world");
```

This error was expected, as it's ambiguous how the literal string `"hello world"` should converted.

```
// Error: No unique declaration found after argument-dependent lookup.
overloadedFunction(bytes16("hello world"));
```

This error was somewhat unexpected, because I am being explicit about the type I am passing in. But `bytes16` is still implicitly convertible to `bytes32`, so I can see how there may still be room for ambiguity.

```
// Error: No unique declaration found after argument-dependent lookup.
bool returnValue = overloadedFunction(bytes16("hello world"));
```

This error surprised me, because between the assignment and the explicit input, I expected that Solidity would have enough contextual information to deduce what function I was calling.

This code was tested using the online Solidity compiler, version `0.4.3-nightly.2016.10.12+commit.def3f3ea.Emscripten.clang`.

**Comment by axic** [comment]
@codywatts nice catch!

(As the return parameters are not part of the ABI, I would assume they are not part of the internal overload resolution either.)

**Comment by chriseth** [comment]
This is a missing planned feature I just copied from pivotal tracker: https://github.com/ethereum/solidity/issues/1256

**Comment by chriseth** [comment]
Closing as duplicate.

**Comment by fty48jj19** [comment]
e   nao fica fazendo coisas q nao diz a respeito nao em se nao vc mim prejudica aqui quando vc quiser mim peça aqui  nao fica enpurrando nada se vou broquia  vc mas  se eu ver coisa de vc de anormal da para frente vou broquia vc  mas agora nao segue endiante nao sobmeta fazer coisa que nao deve,
