### ISSUE TITLE
[isoltest] Warn if the gas cost expectations are not being enforced

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12386]
Currently `isoltest` automatically enables `--enforce-gas-cost` option but only if other options conflicting with it are not used (i.e. `--abiencoderv1` or `--evm-version` other than the latest). It's easy to miss that, especially if someone is not yet familiar with all the quirks of the tool. Isoltest should print a message if it's not actually enforcing gas costs.

**Comment by nishant-sachdeva** [comment]
https://github.com/ethereum/solidity/blob/develop/test/tools/IsolTestOptions.cpp#L86
@cameel  As you mentioned, we can add the warning around this line in the code. 

If possible, I'd like to take this issue up.

**Comment by cameel** [comment]
Sure.

**Comment by chriseth** [comment]
implemented in https://github.com/ethereum/solidity/pull/12456
