### ISSUE TITLE
Automatically generate API docs from natspec

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1238]
Solidity has the [Ethereum Natural Specification Format](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) which is similar to Doxygen.

Is it possible to automatically generate API documentation from this?

**Comment by LefterisJP** [comment]
From doxygen's [own documentation](http://www.stack.nl/~dimitri/doxygen/manual/faq.html#faq_pgm_X):

>  ## My favourite programming language is X. Can I still use doxygen?
> 
>  No, not as such; doxygen needs to understand the structure of what it reads. If you don't mind
>  spending some time on it, there are several options:
> -    If the grammar of X is close to C or C++, then it is probably not too hard to tweak src/scanner.l a bit so the language is supported. This is done for all other languages directly supported by doxygen (i.e. Java, IDL, C#, PHP).
> -    If the grammar of X is somewhat different than you can write an input filter that translates X into something similar enough to C/C++ for doxygen to understand (this approach is taken for VB, Object Pascal, and Javascript, see http://www.stack.nl/~dimitri/doxygen/download.html#helpers).
> -    If the grammar is completely different one could write a parser for X and write a backend that produces a similar syntax tree as is done by src/scanner.l (and also by src/tagreader.cpp while reading tag files).

So I would say it should be possible but would require some work on the upstream. I tried to run doxygen with C++ settings on a solidity project and got a lot of `warning: ignoring unknown tag` errors.

**Comment by axic** [comment]
@ethernomad the natspec can be compiled into two JSONs (user documentation and dev documentation) with using the `--userdoc` and `--devdoc` switches on `solc`. They are not currently displayed on browser-solidity.

**Comment by ethernomad** [comment]
That's true. It could then be converted from JSON to markup with another tool.

**Comment by ethernomad** [comment]
https://github.com/DigixGlobal/doxity
