### ISSUE TITLE
Granular parallel soltest runs

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12388]
## Abstract
We need an option in `soltest` to split all test cases into N batches and run only the i-th batch to take full advantage of CircleCI's [`parallelism`](https://circleci.com/docs/2.0/parallelism-faster-jobs/) option and make `soltest`/`soltest_all` jobs give us faster feedback.

## Motivation
The way we parallelize `soltest` today is to have [`soltest_all.sh`](https://github.com/ethereum/solidity/blob/v0.8.10/.circleci/soltest_all.sh) run it multiple times with different sets of options. We also single out ABI encoder v1 tests and tests that we know don't depend on the EVM version. This is not granular enough. No run takes less than ~5 mins and there are a few that take ~15 min or more. If we could split those runs, we'd get feedback in PRs much faster.

This would also let us parallelize `soltest` runs too - currently it's only practical to do this with `soltest_all`.

## Specification
Add two options to `soltest`: `--batches` and `--selected-batch`. Internally `soltest` should enumerate all tests it will run, deterministically assign them to batches of the same size and run the selected batch. It should not fail if a batch is empty.

When the new options are available, [`soltest_all.sh`](https://github.com/ethereum/solidity/blob/v0.8.10/.circleci/soltest_all.sh) and [`soltest.sh`](https://github.com/ethereum/solidity/blob/v0.8.10/.circleci/soltest.sh) will need to be adjusted to use them. In `soltest_all.sh` the runs for different EVM version and optimization options will need to stay until we have #10191. I'd also leave the separate ABI encoder v1 run there because there's no point in running it for every EVM version.

Finally, our [CI config](https://github.com/ethereum/solidity/blob/v0.8.10/.circleci/config.yml) will need to be adjusted to specify `parallelism` for `soltest` jobs and to increase the value for `soltest_all`.

**Comment by cameel** [comment]
Some time ago I tried a simpler approach to this - listing all cases `soltest` would run and just passing them to it explicitly as command-line arguments, with a standalone script to do the split: [`multicore-soltest-sh`](https://github.com/ethereum/solidity/commits/multicore-soltest-sh). Unfortunately this was not very successful. The problem was that I can only get the list all cases, not ones matching the options I would like to run `soltest` with. And the output of `--list_content` option is not very machine-readable - I had to reconstruct full test case names based on nesting. Finally, this did not produce the speedup I was expecting (only 2x rather than Nx), though I'm not completely sure why - I decided it was not worth spending the time to dig into it futher and gave up.

The approach with batching seems more promising because then we can let `soltest` itself select cases and it knows what it will run. The biggest problem I see is that I'm not sure if we have enough control over test suite execution in [`boostTest.cpp`](https://github.com/ethereum/solidity/blob/v0.8.10/test/boostTest.cpp). Back when I tried to do it, I could plug into code that collects the test cases from `.sol` files but I could not find a place that would be processing all cases that get registered. But hopefully there's some callback in Boost for that.

**Comment by cameel** [comment]
@mejsiej Maybe you'd like to take a stab at this issue? This would be really neat to have because currently `soltest_all` runs in CI take > 30 min. This one does not require deep knowledge about compiler internals, it's more about Boost, but I think it should also be pretty satisfying to solve.

**Comment by mejsiej** [comment]
Yeah, I want to give it a shot!

**Comment by chriseth** [comment]
Wouldn't it be better to have just a single option like `--batched 2/10`, which would run batch number 2 out of 10?

**Comment by cameel** [comment]
Fine with me. Having separate integer options is just a bit simpler but I guess this does look more readable.
