### ISSUE TITLE
No Module named solcx

### ISSUE THREAD

**Issue by JMiddey** [ethereum/solidity#12383]
-->

## Description

Hi I have been trying to run a python file that is using Solidity but I am getting this error:
joe@Joes-MacBook-Pro web3_py_simple_storage % python deploy.py
Traceback (most recent call last):
  File "deploy.py", line 1, in <module>
    import solcx
ImportError: No module named solcx

## Environment

- Compiler version: (Unknown since I cannot run the solcx code as it says command not found
- Target EVM version (as per compiler settings): zsh 5.8 (x86_64-apple-darwin21.0)(I think?)
- Framework/IDE (e.g. Truffle or Remix):Truffle
- EVM execution environment / backend / blockchain client: unsure?
- Operating system: MacOS

## Steps to Reproduce

running : import solcx
returning: oe@Joes-MacBook-Pro web3_py_simple_storage % python deploy.py
Traceback (most recent call last):
  File "deploy.py", line 1, in <module>
    import solcx
ImportError: No module named solcx

**Comment by cameel** [comment]
This does not seem to be related to the compiler itself. [py-solc-x](https://github.com/iamdefinitelyahuman/py-solc-x) is an independent project.

Also this does not really look like a bug, more like you have just not installed `solcx`. If you need help with setting up your environment, please try asking on the [#brownie](https://gitter.im/eth-brownie/community) channel on gitter.

**Comment by JMiddey** [comment]
I have solcx installed, its showing on my pip list but isnt working in my code

**Comment by cameel** [comment]
This was just a guess based on the output you posted. You should really ask someone familiar with `solcx`, this does not seem to be a problem in the Solidity compiler.

**Comment by JMiddey** [comment]
I just re read your inital comment, py-solc-x isnt part of solcx? what is the install code for solcx?
since i cant actually see solcx on my pip modules list, although py-solc-x is, aswell as (solc               0.0.0a0)

**Comment by cameel** [comment]
AFAIK it's the same thing. `py-solc-x` is the repo/package name and `solcx` is the name of the Python module provided by it.

**Comment by JMiddey** [comment]
oh well thats annoying then, no idea whats going on, I think its something to do with my file paths and directories or something, or its solcx but idk, ughh the endless search of answers on the internet lmao
