### ISSUE TITLE
Members of contracts with the same name within the same file are all available to call, even if only one of the contracts is deployed

### ISSUE THREAD

**Issue by avlahos** [ethereum/solidity#12391]
## Description

Given a single Solidity file that contains two contracts with the same name but different capitalization (Abc and ABC). Note that the contracts have no interaction with each other and neither one is a parent or child of the other. When one of the two contracts in the file is deployed, the user can execute the functionality of the second contract in the file that was not deployed.

The initial hypothesis is that the compiler has trouble differentiating between the two contracts in the file since they have the same name (although different capitalization).

## Environment

- Compiler version: v0.6.12+commit.27d51765
- Target EVM version (as per compiler settings): default evmVersion
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client: Polygon
- Operating system:

## Steps to Reproduce

The following deployed contract serves as an example of the described issue: https://polygonscan.com/address/0x96551a7873D3528B6C87f0B7456BC35ed2589FBD#code

This file features a few contracts, but we're mainly focusing on two (Mgas and MGAS). The Mgas contract is an ERC-20 token and the MGAS contract is intended to be an NFT marketplace (although it may not contain full functionality). Note that the contract ABI, the Read/Write sections all match what they should look like considering the MGAS contract was deployed. However, if you look at the transactions, you can see that functions of the Mgas token contract were called as if the functions on the deployed contract itself were being executed. You can see an initialize and a transfer function were called using code from the Mgas token contract.

**Comment by cameel** [comment]
> You can see an initialize and a transfer function were called using code from the Mgas token contract.

That's not the case here. They were actually handled by `MGAS`. True, the transaction data does contain the selector of `initialize()` or `transfer()` - functions that are not present in `MGAS` - but it does not mean that the contract has to implement these functions. There's another way for a contract to handle such transactions - the [`fallback()` function](https://docs.soliditylang.org/en/latest/contracts.html?highlight=fallback#fallback-function). Note that `Market` (which `MGAS` ultimately inherits from) does have such a function:
```solidity
abstract contract Market {
    fallback() external payable {
        _deal();
    }
    
    receive() external payable {
        _deal();
    }

    ...
}
```
The truth is that on the bytecode level there are no functions at all, it's just an abstraction provided by the language. A contract is just a long chain of instructions and is free to use or ignore whatever you include in calldata and interpret it however it likes. In Solidity external functions are simulated by having a big `switch` statement that looks at the selector and decides where to jump. By default the code is generated in such a way that, if a function is not present in the Solidity source, the contract reverts. But if you provide a `fallback` function, a `default` case is added to the `switch` and the code inside that function is executed instead. Unless you decide to revert in `fallback`, this counts as a successful call. This mechanism is often used by proxies to forward all calls to another contract but you can use it in other cases too. Here the author of the contract decided that if a matching function is not present, the specifics of the call should be ignored and `_deal()` should be executed instead. As you can see, this can be pretty confusing.

**Comment by avlahos** [comment]
@cameel Thank you so much for taking the time to answer this. I can see now that the MGAS contract serves as a proxy contract and routes calls to another contract containing the implementation code.
