### ISSUE TITLE
Type deduction for inline empty array constants in function parameters

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#12401]
## Description

Given these two contracts, where `B` is trying to call the constructor of `A` with an empty array:

```
contract A {
    address[] addresses public;
    constructor(address[] memory _addresses) {
        addresses = _addresses;
    }
}

contract B is A {
    constructor() A([]) {  // (*)
    }
}
```

At line `(*)`, I get `TypeError: Unable to deduce common type for array elements.`

If I change the parameter from `[]` to `(address[]) []`, I get `TypeError: Invalid type for argument in modifier invocation. Invalid implicit conversion from type(address[] memory[] memory) to address[] memory requested.`

## Environment

- Compiler version: 0.8.10
- Target EVM version (as per compiler settings): compiler default
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

## Steps to Reproduce

See above.

Related: #621.

**Comment by chriseth** [comment]
I currently don't see how to solve this, sorry.

Related: #11879

**Comment by lukehutch** [comment]
You can bound the type by looking at where the data is being sent (in this case, the function parameter).

As a workaround, how do I create a typed empty array and pass it from a constructor to the suoerconstructir? I can't seem to find a way.

**Comment by chriseth** [comment]
As one concept in Solidity, types of expressions are purely determined by the types syntactically inside the expression.

As a workaround you can use a free function:
```
function newAddressArray() pure returns (address[]) {}
```

**Comment by lukehutch** [comment]
Thanks for the suggestion, that solves my immediate problem, at least.

For locals, you can simply declare 

```
address[] memory empty;
func(empty);
```

however `empty` cannot be declared without an assignment, for a field of the contract (and a local can't be declared before a superconstructor call). Shouldn't the syntax of fields and local variables be the same?

**Comment by petr-hejda** [comment]
It's currently (v0.8) not possible to both declare and pass a dynamic-length array in a one-line statement.

However, if you are able to define the values passed to the `B` constructor, you can create an array param in the `B` constructor, and then pass it to the `A` constructor:

```
contract B is A {
    constructor(address[] memory _addresses) A(_addresses) {
    }
}
```

Then you just need to pass the empty array to the `B` constructor from the deployer script:

_offchain JS deployer:_
```
myContract.deploy([]);
```

_onchain Solidity deployer:_
```
address[] memory empty;
new B(empty);
```

**Comment by lukehutch** [comment]
@petr-hejda Thanks, yes, that's what I was doing before, but I didn't want to pass the array into the sub-contract's constructor, so the function solution that @chriseth supplied works better in my case.
