### ISSUE TITLE
Large array declaration hangs compiler when optimization enabled

### ISSUE THREAD

**Issue by citizen-stig** [ethereum/solidity#12406]
## Description

For private deployment of Ethereum I would like to deploy "larger" contracts than on mainnet.
Here's example of such smart contract: https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160

solc is able to compile this smart contract normally, but hangs when optimization is enabled.

## Environment

- Compiler version: 0.8.10+commit.fc410830.Linux.g++
- Target EVM version (as per compiler settings): Default
- Framework/IDE (e.g. Truffle or Remix): No
- EVM execution environment / backend / blockchain client: Besu
- Operating system:  x86_64 GNU/Linux 5.15.6-arch2 Archlinux

## Steps to Reproduce

Download example source code from [this gist](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160)

Run this command:

```
solc --bin -o build_check --optimize --optimize-runs=200 --no-optimize-yul ./MediumVerifier.sol
```

### Expected result

Code is compiled, same way as without optimization.

### Actual result

Compiler hangs, consuming 100% of single cpu thread.

### Notes

Outcome is the same if `--optimize-runs=1`

**Comment by chriseth** [comment]
This is probably due to the constant representation optimizer. As a "quick fix" you could try storing the constants as a single large string/hex array and create the points in a loop indexing the array using inline assembly.

**Comment by citizen-stig** [comment]
> This is probably due to the constant representation optimizer. As a "quick fix" you could try storing the constants as a single large string/hex array and create the points in a loop indexing the array using inline assembly

@chriseth thank you for quick reply!

Could you please elaborate more on "quick fix"? Should I store data in hex or decimal? Should it be large string or array of strings? 
What is the most efficient way to create points using inline assembly. Thank you.

**Comment by wechman** [comment]
I did a research on the problem and confirmed that the compiler gets stuck for a long time on [PeepholeOptimiser::optimise](https://github.com/ethereum/solidity/blob/develop/libevmasm/PeepholeOptimiser.cpp#L425). In consecutive optimization steps it applies [JumpToNext](https://github.com/ethereum/solidity/blob/develop/libevmasm/PeepholeOptimiser.cpp#L295) rule. For me it takes almost 5 hours to get the job done. I also verified that compilation time is  related to the length of "IC" array defined in the problematic contract. With the halved "IC", compilation time is reduced to 1 hour.

**Comment by wechman** [comment]
I did a research on the problem. First of all, [MediumVerifier.sol](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160)
 compilation finishes successfully, but it takes a lot of time. When I checked that for the first time it took almost 5 hours. Recently I updated to the newest develop and now it needs approximately 2 hours. I am not sure if the time drop is related to the recent changes in solc or to my local environment setup. Anyway, while debugging I find out that compiler spends a majority of the time in [Assembly::optimiseInternal](https://github.com/ethereum/solidity/blob/develop/libevmasm/Assembly.cpp#L406). It involves [JumpdestRemover](https://github.com/ethereum/solidity/blob/develop/libevmasm/JumpdestRemover.h#L33), [PeepholeOptimiser](https://github.com/ethereum/solidity/blob/develop/libevmasm/PeepholeOptimiser.h#L33) and [CommonSubexpressionEliminator](https://github.com/ethereum/solidity/blob/develop/libevmasm/CommonSubexpressionEliminator.h#L62). Code profiling confirmed that the compiler spends nearly 100% time on the code optimization. [CommonSubexpressionEliminator::getOptimizedItems](https://github.com/ethereum/solidity/blob/develop/libevmasm/CommonSubexpressionEliminator.cpp#L37)  is the most time-consuming process and takes 96.5% of this whole time.

**Comment by chriseth** [comment]
Can you find out how many iterations the loop in `Assembly::optimiseInternal` is run and how long each iteration takes?
Another useful information might be how long the chunks are that are passed to the CommonSubexpressionEliminator (i.e. the distance between `iter` and `orig`) and how often `shouldReplace` is false.

**Comment by wechman** [comment]
> Can you find out how many iterations the loop in `Assembly::optimiseInternal` is run and how long each iteration takes? Another useful information might be how long the chunks are that are passed to the CommonSubexpressionEliminator (i.e. the distance between `iter` and `orig`) and how often `shouldReplace` is false.

With #12801 I managed to reduce compilation time in a release build from 45 to 21 minutes. 99.99% of that time compiler spends in [Assembly::optimiseInternal](https://github.com/ethereum/solidity/blob/develop/libevmasm/Assembly.cpp#L406) iterating 1614 times over the [main loop](https://github.com/ethereum/solidity/blob/develop/libevmasm/Assembly.cpp#L429). Meanwhile `shouldReplace` has value `true` 1010 times and value `false` 2608589 times. More detailed data on that: 
```

(chunk_size, shouldReplace): number of iterations
(1|0): 920241
(2|0): 16153
(3|0): 699733
(4|0): 32283
(5|0): 14545
(6|0): 41984
(7|0): 40394
(8|0): 12912
(9|0): 17760
(10|0): 30650
(11|0): 37123
(12|0): 14519
(13|0): 25786
(14|0): 6456
(15|0): 1625
(16|0): 3226
(17|0): 16137
(18|0): 5
(19|0): 9
(20|0): 6448
(21|0): 1613
(24|0): 3227
(26|0): 1618
(27|0): 3223
(28|0): 1613
(29|0): 1612
(31|0): 3224
(34|0): 648831
(38|0): 1609
(86|0): 1610
(112|0): 1607
(4|1): 6
(5|1): 4
(6|1): 19
(7|1): 16
(8|1): 26
(9|1): 7
(10|1): 36
(11|1): 10
(12|1): 5
(13|1): 6
(14|1): 6
(15|1): 7
(16|1): 6
(17|1): 16
(18|1): 1
(19|1): 2
(20|1): 5
(22|1): 1
(23|1): 3
(25|1): 1
(26|1): 1
(27|1): 2
(28|1): 3
(32|1): 3
(33|1): 1
(37|1): 1
(44|1): 1
(45|1): 1
(49|1): 1
(71|1): 1
(73|1): 1
(82|1): 1
(84|1): 1
(87|1): 1
(132|1): 1
(219|1): 1
(224|1): 1
(246|1): 1
(266|1): 1
(286|1): 1
(307|1): 1
(328|1): 1
...
(16148|1): 1
(16168|1): 1
(16188|1): 1
(16208|1): 1
(16233|1): 1
(16248|1): 1
(16268|1): 1
(16288|1): 1
(16300|1): 1
(16308|1): 1

```


To improve readability, I filtered out all entries where shouldReplace=false and iterations <= 1.
