### ISSUE TITLE
Deprecate indexed in favour of topic

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1241]
Use of the keyword `indexed` for log topics is incorrect. Topics are clearly not indexed properly because they cost only 375 gas.

Geth does have accelerated topic scanning, but this is nowhere near as fast as loading a block, transaction or address balance.

I propose we use the proper term `topic` instead of `indexed` to be more correct.

**Comment by chriseth** [comment]
Topics are indexed, they are stored in a bloom filter. While I see the benefit of using the more neutral word "topic", I think such a drastic change is not justified enough.

**Comment by ethernomad** [comment]
The problem is that `indexed` implies that it can be found quickly, e.g. when you click a button in a dapp data can be retrieved immediately. However this is not the case. With Geth's bloom filter implementation it can take many seconds to find a log with the correct topic.

In order to retrieve data quickly from the blockchain it needs to be in state because state slots are properly indexed. Logs are really only useful for watching for live updates, unless the block number of the log is stored in state.

I think `indexed` is very bad developer experience because it implies that logs have a capability that they do not.

**Comment by chriseth** [comment]
Logs are intended to be retrieved immediately, so I think this should rather be fixed by adding an appropriate index on top of the bloom filter (e.g. a multi-level bloom filter). I would not want to change the language just because of a missing feature.

**Comment by axic** [comment]
@chriseth I think this can be revived/reconsidered as we're changing a couple of keywords for 0.5.0

**Comment by axic** [comment]
Actually it turns out Vyper uses `indexed` now.

**Comment by axic** [comment]
We could support this in 0.5.0 while still keeping `topic` to avoid the amount changes users need to do.
