### ISSUE TITLE
Parallelize macOS build in CI

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12422]
In https://github.com/ethereum/solidity/issues/11670#issuecomment-954297346 I discovered that our [macOS build](https://github.com/ethereum/solidity/blob/v0.8.10/.circleci/config.yml#L673-L707) job in CI takes ~20 min regardless of how many cores the machine has. Apparently the `-j` flag we put in `MAKEFLAGS` variable is getting ignored. I think that the build config generated by CMake on macOS is still `make`-based so I'm not sure why this is the case.

This needs to be investigated. Once we know how to parallelize it, we should adjust the number of threads/processes and machine resource class in CI for the best cost/benefit ratio.

**Comment by willianpaixao** [comment]
Hi @cameel, very interesting issue.

For over a decade I only saw the `-j` flag being used without a space as separator, eg, `-j4`, which raised my eyebrows. Maybe Ubuntu can understand that but MacOS can't. So I would remove the space and fire a pipeline to check.

That said, assuming this was not the problem, maybe we should try a different flag, here are the cmake equialent:

- [CMAKE_BUILD_PARALLEL_LEVEL](https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html#envvar:CMAKE_BUILD_PARALLEL_LEVEL)
- [CMAKE_CXX_FLAGS](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html#variable:CMAKE_%3CLANG%3E_FLAGS)

Unfortunately I don't own a Mac that I can try it myself.

**Comment by cameel** [comment]
That's a great point. Being used to the GNU tools it didn't even cross my mind but it could really be just that.

Honestly, I don't own a Mac either, I'm only ever using it in CI :) If you would like to try, it's as simple as tweaking our [config.yml](https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml). If you create a PR it will run with your changed config.

If you do that you should log into CircleCI though and follow the project if you can because otherwise there are some limits on external PRs. Sometimes mac/windows jobs do not run at all. If that happens, usually a branch created by one of the project members also helps to trigger it so let me know.

**Comment by willianpaixao** [comment]
Well, I tried but apparently CircleCI wants some schmoney:

> Apologies! Your build didn’t run because you haven’t selected a plan that includes macOS yet. Please change to a Performance Plan. If you have any questions please feel free to contact support.

**Comment by cameel** [comment]
OK, that's what was afraid would happen. Well, let me try it then.

**Comment by cameel** [comment]
Here's a PR: #12536. Let's see if your theory is true :) Feel free to review.
