### ISSUE TITLE
Can't seem to alter the symbol and name of the token....

### ISSUE THREAD

**Issue by zakimzf** [ethereum/solidity#12458]
I'm trying to deploy a bridge token(eth-bsc) unfortunately i can't see to figure out how to change its parameters(name&symbol) . Here is the repo: https://github.com/miquelcabot/eth-bsc-bridge
I tried changing the values in TOKENBSC.SOL and TOKENETH.SOL as you can see in the code but no matter whatever the values i change to they dont seem to reflect when deployed..Perhaps i am doing it wrong (as i am naive to solidity) . Hope to get a quick fix for this.

![Screenshot 2021-12-25 184638](https://user-images.githubusercontent.com/67141555/147455581-ad17b3db-c406-4caa-a510-9aa4453e4c6f.png)
![2021-12-25 18 46 33 rinkeby etherscan io d8df0f2c420e](https://user-images.githubusercontent.com/67141555/147455586-fe9bddb0-5a0a-49a3-b1c9-71fce128472b.png)

**Comment by hrkrshnn** [comment]
Wrong place for this question. Try solidity gitter or matrix chat.
