### ISSUE TITLE
Optimizer bytecode size limit

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#12459]
## Abstract

Using compiler option "runs" allows for bytecode optimization, but sometimes optimization expands smart contract bytecode that much it will not fit into EIP-171 (24KB). As far as I understand setting "runs=1" allows bytecode size optimization for deployment. Is there any way to have an additional argument for making optimizer aware of deployment limitation?

## Motivation

Want to optimize smart contract for execution and still be able to fit in 24KB.

## Specification

Let's introduce new parameter "smartContractBytecodeDeploymentLimit" or something like this. The optimizer could somehow reduce inlinings when the limit is exceeded.

## Backwards Compatibility

Can use 1 billion of gas as a default value to have almost unreachable backward compatibility.

**Comment by hrkrshnn** [comment]
A similar idea came up when discussing https://github.com/ethereum/solidity/issues/11084. 

BTW, we probably won't be able to compute this easily without a trail and error / binary search. So this can also be achieved by external tools without any additional compiler support. Regardless, this is a valid suggestion.
