### ISSUE TITLE
Question about the sample code in Mapping Types

### ISSUE THREAD

**Issue by wp-lai** [ethereum/solidity#12454]
## Page

+ [code page](https://github.com/ethereum/solidity/blame/develop/docs/types/mapping-types.rst#L88)
+ [document page](https://docs.soliditylang.org/en/v0.8.11/types.html#mapping-types)

## Abstract

In `Mapping Types` section of the solidity document page, there is a simplified version of an ERC20 token showing the usage of mappings.

The `transferFrom` func in that code includes a line `approve(sender, msg.sender, amount);`.

I was wondering that the intention of this line was to decrease `amount` allowance from msg.sender, so maybe this line could be changed to `approve(sender, msg.sender, allowance[sender][msg.sender] - amount);`

**Comment by chriseth** [comment]
It seems this example is totally broken - there is not even a check that the allowance is high enough. I will fix it, thanks for the pointer!
