### ISSUE TITLE
Binary grouping; solc "namespaces"

### ISSUE THREAD

**Issue by Nielsbishere** [ethereum/solidity#12466]
## Abstract

Sometimes you might have helper functions that are put in a library because it makes sense to be there (for example; Math, Errors, XHelper, etc.). However, these all produce separate binaries that have to be deployed separately.

## Motivation

I have this in my project; there are a few helpers that are quite small and would benefit from being able to be bundled together so I don't have to deploy them separately and can link them more easily. 
Currently I can "fix" it by just throwing them into the same library and prefixing functions/variables so that it indicates their real class.

## Specification

Something akin to namespaces that specify where binaries are produced. Example;
```sol
namespace Helpers {
  library MyHelper {
     function test() external pure { }
  }
  library MyOtherHelper {
     function test() external pure { }
  }
}
```
Should produce Helpers.bin alongside of MyHelper.bin and MyOtherHelper.bin. It shouldn't replace it because people might want to only use one of the two libraries. 
Nested namespaces could produce an inner and outer binary for further grouping.

## Backwards Compatibility

Libraries outside of a namespace would just function like they normally do.

**Comment by chriseth** [comment]
Thanks for creating this issue! I would like to understand your motivation a bit better. Are you really talking about libraries with external functions? Our current user research indicates that public (and external) library functions are a feature that is not very much used because of the high gas costs involved in calling such functions.

I'm especially confused because you are talking about small members - wouldn't functions at file level be better suited for that? You can namespace them using files - the preferred namespacing in Solidity since it does not require a globally unique namespace.

As to your proposal: If you want to group multiple libraries into the same library binary, then you have to ensure that the function names (signatures) are different - otherwise it is not clear which library function you want to call.

**Comment by Nielsbishere** [comment]
@chriseth I've not deployed anything yet; however, as far as I understand there is a 24KiB limit of a contract. This basically requires me to use libraries to circumvent it, unless this limit was removed at some point and I missed it. One of the use cases is that I pack multiple tokens into 1 uint256 (2 to 64 various tokens) and the (un)packing logic is quite bulky though it saves a lot of gas for sstore/sload operations (so this needs their own library). 

You're absolutely right about that; I never saw them used that way and so assumed Solidity was more like Java in the way that functions have to belong to a library/contract/interface. The only thing I dislike about that is that the file structure would be less clean as there would be one file that contains multiple "libraries", though I guess that should do for now, thanks.

**Comment by chriseth** [comment]
Yes, the size limit is still active, but I think you should still find a way to avoid too many external calls. As far as I know, people usually split the functionality of a contract into multiple areas and do not even use delegatecall for that.

Why would you need one file containing multiple libraries? There is on file number limit :)

**Comment by Nielsbishere** [comment]
@chriseth Hmm, I'm not sure how I would go about doing that. The contract is quite packed with functionality; though it only calls external where it's needed. It basically stores a private struct and passes that along to library functions that use it. The only thing this main contract does is provide a layer to call these functions for clients or other smart contracts and it emits events for transparency to nodes. This library then does internal (private/public) calls which shouldn't do a bunch of delegate calls, right? What would be the cost of these delegate calls?

I put libraries in quotes because currently they are libraries, but if they were global functions then you'd have to include 1 file that contains all these functions at once; which makes file structure a little less clean. But it doesn't matter that much tbh.

**Comment by chriseth** [comment]
If you use global functions (as well as internal library functions), only the functions that are called are included in the bytecode. You can split functions across multiple files in any way you wish. If you want to use a function from a different file, you just have to import it.

**Comment by Nielsbishere** [comment]
Yeah I'm using global functions now for the things I can. Some generate too much bytecode tho so I can't stop using library functions unfortunately.
