### ISSUE TITLE
Signed EXP operations should be blocked

### ISSUE THREAD

**Issue by yaronvel** [ethereum/solidity#1246]
The EVM `EXP` opcode (`0x0a`) arguments are two unsigned int.
Hence, solidity compiler should output an error (or at least a warning) for the following code:

```
int x = 5;
int y = -3;
int z = x ** y;
```

**Comment by chriseth** [comment]
Negative integer exponents were introduced for fixed-point numbers, but it does not make sense to allow them for integers.

**Comment by yaronvel** [comment]
As far as I understand the EVM also does not support negative bases.
It would make perfect sense to support the code:

```
function( int x ) returns(int) { return x**3}
```

But the EVM does not support it

**Comment by pirapira** [comment]
So, for the next release, I understand `x ** y` should
- <del>be banned when `y` is a constant (RationalType?) known to be negative, and</del> (I changed my mind)
- be banned when either `x` or `y` is a signed integer

**Comment by yaronvel** [comment]
I think it might be ok to allow x to be signed.
I think that for every `y >= 0`:

```
x ** y == int(uint(x) ** y)
```

It holds for `x = -1`, and therefor by programmers induction should work for any negative `x` :)
Seriously though, it might really be the case.

**Comment by pirapira** [comment]
@yaronvel I added an issue about this in #1303.  I chose to add `signed ** unsigned` rather than allowing `unsigned ** unsigned` and checking `y >= 0` at run-time.
