### ISSUE TITLE
solc v0.8.11 -- SMTChecker problem in assert -- Compilation time takes too long

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#12463]
## Description

Hello everyone,
in the contract below:

pragma experimental SMTChecker;
contract C {
	struct S {
		uint[2] a;
		uint u;
	}
	S public s;
	function f() public view {
		uint u = this.s();
		assert(u <= u&u); 
		assert(u == 1); 
	}
}

solc takes too long to compile it.
After about a minute or more that the Contract is compiled, there is a warning from both CHC and BMC, that verification could not be proved. Thus I believe that when CHC and BMC find "hard" to verify a "problem" there is might be an issue that makes solc to be extremely slow.

Thank you for your time,
I wish the new year finds you healthy!

## Environment

- Compiler version: solc v0.8.11
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: 
- Operating system: Ubuntu 16.04

**Comment by leonardoalt** [comment]
Thanks for the issue!

I just ran with latest release and develop and got the following output in 6s:

```
Warning: CHC: Assertion violation happens here.
  --> a.sol:10:3:
   |
10 | 		assert(u == 1);
   | 		^^^^^^^^^^^^^^

Warning: CHC: 1 verification condition(s) could not be proved. Enable the model checker option "show unproved" to see all of them. Consider choosing a specific contract to be verified in order to reduce the solving problems. Consider increasing the timeout per query.

Warning: BMC: 1 verification condition(s) could not be proved. Enable the model checker option "show unproved" to see all of them. Consider choosing a specific contract to be verified in order to reduce the solving problems. Consider increasing the timeout per query.
```

It can happen that in some cases the SMT solvers take too long, not much we can do there. The user should just use the `timeout` option to limit how much time they want to spend on solving if they use the SMTChecker.

**Comment by chamitro** [comment]
So you ran it with solc v0.8.11? Also is there a change that it compiles
faster locally from terminal and slower on Remix?

**Comment by leonardoalt** [comment]
The compilation itself is unaffected, what takes longer is the SMT solving. Yea locally should be much faster than via Remix because of the native binaries vs web assembly.
