### ISSUE TITLE
In "Solidity by Example --> Voting": will not report  winning proposal correctly if voteCount's are tied

### ISSUE THREAD

**Issue by siyu-k** [ethereum/solidity#12478]
## Page
https://docs.soliditylang.org/en/latest/solidity-by-example.html#voting
https://docs.soliditylang.org/en/latest/solidity-by-example.html#possible-improvements

## Abstract
Hi, in the voting example (at line 135 in Remix), picking the winning proposal will not work correctly if two (or more) proposals are tied in the voteCount (see screen shots below). 
Could we at least mention this as a limitation of the current implementation, and, perhaps include the handling of this special case as a "Possible Improvement"

Thank you!

<img width="553" alt="image" src="https://user-images.githubusercontent.com/92610128/147902210-b5762407-03db-4553-9b65-5f89d364c2e1.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/92610128/147902325-5ee34e74-7a72-4432-8af8-958694e9bd87.png">

**Comment by matheusaaguiar** [comment]
Hi @siyu-k, thanks for your report!
You have a valid point and your suggestion seems to amend the issue. Would you like to make the changes and open a pull request?
If you have any questions about how to do that, please, feel free to ask. :)

**Comment by siyu-k** [comment]
Hi, thanks for following up. Please go ahead and fix it.
Siyu

**Comment by matheusaaguiar** [comment]
Would you consider making the changes you proposed and contributing to the project?
If you are unsure about how to do it, I can give you some help.

**Comment by anshss** [comment]
I want to take on this issue if no one is already working on it.

**Comment by siyu-k** [comment]
Please go ahead.
Thank you!
