### ISSUE TITLE
Add Documentation: Only internal functions from a library that are actually used by a contract are added to the contract bytecode

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#12474]
## Page

https://docs.soliditylang.org/en/v0.8.11/contracts.html#libraries

## Abstract

It is useful for developers to know that only internal functions from a Solidity library that are actually used by a contract are added to the contract bytecode.  With this knowledge developers can be free to create larger Solidity libraries with internal functions without fear that they are bloating the bytecode size of their contracts.

**Comment by hrkrshnn** [comment]
Sounds good. Would you like to write a PR for it? @mudgen

**Comment by chriseth** [comment]
We already have:
```
 To realize this in the EVM, code of internal library functions and all functions called from therein will at compile time be included in the calling contract, and a regular JUMP call will be used instead of a DELEGATECALL.
```

We could add: "Conversely, this means that code of functions that are not called is not included.' but I'm not sure if that is really needed.

**Comment by mudgen** [comment]
Thanks.  I think it would be good to add that.   

Because when I look at this closely:

>  To realize this in the EVM, code of internal library functions and all functions called from therein will at compile time be included in the calling contract, and a regular JUMP call will be used instead of a DELEGATECALL.

It says, "code of internal library functions".  It is not totally explicitly clear to me that it means only the code that is called and used.

It does say, ""included in the calling contract"  that explicitly means that only libraries that are called are included in the contract,  but isn't explicitly specific that only the code in the library that is actually called and used is included.
