### ISSUE TITLE
Lost funds Metis 

### ISSUE THREAD

**Issue by mitchellvh** [ethereum/solidity#12475]
Hi guys, a while ago I transfered my Metis Funds (worth over 125.000$ right now) to the Metis contract address in state of my Metamask wallet address.
I really hope some experienced people overhere can tell me if we can get these tokens back and will pay 15.000$ for the solution.
From what I have heard it's impossible to get these tokens back but I am just hoping for a miracle. Just let me know if you can help me and I will cover all cost
that is needed to fix this problem. 
Metis contract : https://etherscan.io/address/0x9e32b13ce7f2e80a01932b42553652e053d6ed8e
Lost funds transfer: https://etherscan.io/tx/0xfcf63dd0fc691d02375b65f42e71a113f17d77c760a05553fad41031ff1f0253
Best, Mitchell

**Comment by hrkrshnn** [comment]
@mitchellvh Sorry about that, you seem to have accidentally transferred tokens to its own contract. There isn't anything that can be done here, other than asking the devs if they can mint you new ones (the contract lets the owners mint new tokens). Closing this.
