### ISSUE TITLE
Update gas costs in gas cost estimator

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1247]
The gas costs in the estimator do not reflect the latest hard fork changes. At best, it should be possible to select which "ruleset" to use for the estimation.

**Comment by axic** [comment]
See #1117.

**Comment by chriseth** [comment]
@pirapira would you like to do this task? We should provide an option to select which rules apply. For now, we do not need to expose that option to the commandline interface, instead, we just select the latest rules in effect in the real world.

**Comment by pirapira** [comment]
OK.  I also noticed the `nextrelease` label.

**Comment by pirapira** [comment]
This comes in two steps.
* [ ] update the gas table, without supporting multiple versions (this should solve the problems for the current users)
* [ ] support multiple versions of gas table
    * [ ] the test cases in `GasMeter.cpp` need to specify fee schedules

**Comment by chriseth** [comment]
There are some tests that check the gas usage against cpp-ethereum, so I think with this story, we also have to update the cpp-ethereum we use as testing backend. We might want to switch to the docker image for that.

**Comment by pirapira** [comment]
@chriseth I'll figure out what interface I need from `eth/eth`.

**Comment by chriseth** [comment]
I just ran the tests for the pull request and there are failures, so it will be postponed for the next release.

**Comment by chriseth** [comment]
Will be completed in #2220

**Comment by HelenB13** [comment]
Interesting info. I'm sure that the estimator is a useful and helpful tool. Thanks! Gas prices have been increasing. And according to the latest forecasts and the washington gas reviews, the national average could hit at least $2.80 in the coming weeks.
