### ISSUE TITLE
Warn if built-in globals are shadowed

### ISSUE THREAD

**Issue by codywatts** [ethereum/solidity#1249]
"Built-in" functions such as `sha3` and `selfdestruct` can be hidden by functions and events with the same name. This can alter the functionality of contracts in non-obvious ways.

Consider [the following contract](https://ethereum.github.io/browser-solidity/#gist=d90c5a799aab7a1595e9c62a0c80a0d4):

```
pragma solidity ^0.4.2;

contract FakingItsOwnDeath {
    function selfdestruct(address x) internal constant {}
}

contract SelfDestructive is FakingItsOwnDeath {
    function die() public {
        selfdestruct(address(0x0));
    }
}
```

At a glance, `SelfDestructive.die` appears to destroy the contract. But in fact, it's actually calling `FakingItsOwnDeath.selfdestruct` rather than the built-in version of `selfdestruct` and so the contract doesn't die.

It is also to possible to create functions/events called `this` and `now`.

(Tested using version `0.4.2+commit.af6afb04.mod.Emscripten.clang` of the online Solidity compiler.)

**Comment by chriseth** [comment]
This is all intended but should probably result in a warning if built-ins are overwritten, yes.

**Comment by chriseth** [comment]
This is also very important for `revert()`
