### ISSUE TITLE
Document the address.code and address.codeHash properties

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12495]
## Page

https://docs.soliditylang.org/en/v0.8.11/types.html?highlight=address#address

## Abstract

Features address.code and address.codeHash should be documented here

## Pull request

None yet

**Comment by chriseth** [comment]
Oh wow, weird that we missed that! Thanks!

**Comment by hrkrshnn** [comment]
@fulldecent Would you like to submit a PR adding it? :)

BTW, if it's easier, feel free to just submit a PR without opening an issue--we're confident about your judgment!

**Comment by fulldecent** [comment]
@hrkrshnn Thank you, on it.

https://github.com/ethereum/solidity/pull/12516
