### ISSUE TITLE
Feature request: array literals

### ISSUE THREAD

**Issue by vbuterin** [ethereum/solidity#125]
Quote often, contract developers are stuck doing things like this:

https://github.com/pipermerriam/ethereum-cron/blob/master/contracts/Crontab.sol#L178

```
 uint8[12] monthDayCounts;
 monthDayCounts[0] = 31;
 if (isLeapYear(year)) {
       monthDayCounts[1] = 29;
 }
 else {
       monthDayCounts[1] = 28;
 }
 monthDayCounts[2] = 31;
 monthDayCounts[3] = 30;
 monthDayCounts[4] = 31;
 monthDayCounts[5] = 30;
 monthDayCounts[6] = 31;
 monthDayCounts[7] = 31;
 monthDayCounts[8] = 30;
 monthDayCounts[9] = 31;
 monthDayCounts[10] = 30;
 monthDayCounts[11] = 31;
```

I would prefer there to exist syntax like this:

```
uint8[12] monthDayCounts = [31, isLeapYear(year) ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
```

**Comment by chriseth** [comment]
Increasing priority of [story](https://www.pivotaltracker.com/story/show/93095470)
- perhaps we should add a voting contract that interfaces with pivotal tracker...

**Comment by chriseth** [comment]
Continue tracking in PT.
