### ISSUE TITLE
The output from events can be stored as a tuple

### ISSUE THREAD

**Issue by codywatts** [ethereum/solidity#1250]
Not harmful, just strange. Consider [the following contract](https://ethereum.github.io/browser-solidity/#gist=8e848da5cc28dfcf8093279a1cb5f0f0&version=soljson-v0.4.2+commit.af6afb04.js&optimize=true):

```
pragma solidity ^0.4.2;

contract EventsAndTuples {
    function test() public {
        // Attempting to assign the result of an event to a variable yields this error:
        // "Error: Not enough components (0) in value to assign all variables (1)."
        //var resultOfEventOne = one();

        // However, the following line compiles without error:
        var (resultOfEventOne, resultOfEventTwo) = (one(), two());
    }

    event one();
    event two();
}
```

As shown, attempting to assign the result of a single event to a variable produces a compiler error, but assigning the results of _two_ events to a tuple is permitted.

(Tested using version `0.4.2+commit.af6afb04.mod.Emscripten.clang` of the online Solidity compiler.)

**Comment by chriseth** [comment]
Thanks for the interesting find!

**Comment by axic** [comment]
This is not an issue limited to events, but to tuple assignments.

```
    function f() {
    }
    function g() {
        var (x, y) = (f(), f());
    }
    function h() {
        var (z) = f();
    }
```

`h()` fails, `g()` compiles.
