### ISSUE TITLE
Refine inheritance documentation about super.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12506]
Triggered by https://github.com/ethereum/solidity/pull/12499

I tend to agree with the author of the PR that the documentation part in question could make it clearer from the start that one may expect different behaviour from languages that don't use C3 linearizations. I don't think we need to link to an external explanation, but maybe worth having a look into clarifying this.

**Comment by darkthunder0** [comment]
can i work on this?

**Comment by ekpyron** [comment]
@darkthunder0 Sure - if you see the problem of #12499 and have a good suggestion for improving our docs, feel free to open a PR!
