### ISSUE TITLE
Source not found/seen

### ISSUE THREAD

**Issue by mrx23dot** [ethereum/solidity#12502]
solc is not seeing source file.
Compiler should work in every directory (see gcc).

```
sudo snap install solc
cd /tmp
has source: test.sol
sudo solc test.sol
"test.sol" is not found.
solc --allow-paths /tmp test.sol
"test.sol" is not found.
```

It finds the file in another directory:
```
cd /home
solc test.sol
ok
```

versions
```
Debian 10
solc Version: 0.5.16+commit.9c3226ce.Linux.g++
```

**Comment by hrkrshnn** [comment]
@mrx23dot Does the problem also exist on a new solc version?

**Comment by mrx23dot** [comment]
Interesting, when I download only the binaries it doesn't seem to be a problem.
Not sure what's up with the 'snap' installation.

It would be also nice if could distribute solc via debian apt-get too, binaries are already done.

**Comment by hrkrshnn** [comment]
Snap seems to be broken: https://github.com/ethereum/solidity/issues/11940

I think you should be able to find solc on apt.

**Comment by mrx23dot** [comment]
apt only works for ubuntu, not debian, even though we have binaries for debian:
https://docs.soliditylang.org/en/v0.8.9/installing-solidity.html

**Comment by ekpyron** [comment]
If nothing else works you can always fall back to the statically linked binaries hosted in the github release pages, e.g. https://github.com/ethereum/solidity/releases/download/v0.8.11/solc-static-linux

Those should pretty much work anywhere and should not require any dependencies (unless you're running a system with a *really* ancient glibc).

**Comment by ekpyron** [comment]
But I'd agree that it would be nice to maintain debian builds. But if we want that, we should really use a proper debian build mechanism. The ubuntu packages *may* work by chance, but it's generally not the best idea to mix debian and ubuntu packages.

**Comment by mrx23dot** [comment]
I close this issue since investigation is already ongoin in #11940 for snap.

**Comment by cameel** [comment]
@mrx23dot An up to date snap should be available through the `edge` channel (see https://github.com/ethereum/solidity/issues/11940#issuecomment-999014242). If you can, please test it and post your feedback in #11940.
