### ISSUE TITLE
A very small typo

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#12503]
## Page

https://docs.soliditylang.org/en/v0.6.8/layout-of-source-files.html#spdx-license-identifier

## Abstract

"Trust in smart contracts can be better established..." is currently written as "Trust in smart contract can be better established..."

**Comment by hrkrshnn** [comment]
@brien-tech Thanks for the issue. Could you please fix it yourself and open a PR? For context, the file that needs fixing is https://github.com/ethereum/solidity/blob/develop/docs/layout-of-source-files.rst

**Comment by ghost** [comment]
@hrkrshnn Thanks for taking the time to respond.  Here is the link to my PR for your convenience https://github.com/ethereum/solidity/pull/12504
