### ISSUE TITLE
IR optimized code makes one fewer call than legacy optimized code

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12514]
When `f(int)` is called, IR optimized code makes one fewer call than legacy optimized code

```
contract C {
  function f(int) external {
    ((((((abi.decode("",(bytes7))^(abi.decode(ecrecover(abi.decode("dc12600bb44e943dc10568cbccc68d4c",(bytes32)),(2),((0)),keccak256(bytes.concat(bytes2(0)))).code,(bytes7)))))))));
  }
}
```

TODO: Steps to reproduce

**Comment by ekpyron** [comment]
What call exactly missing there :-)? I see a constant-argument ``keccak256`` in there... it may be that IR codegen compile-time evaluates that one for example...

**Comment by bshastry** [comment]
> What call exactly missing there :-)? I see a constant-argument `keccak256` in there... it may be that IR codegen compile-time evaluates that one for example...

Sorry, I mean an `EVMC_CALL` (ref: https://evmc.ethereum.org/group__EVMC.html#ggab2fa68a92a6828064a61e46060abc634abcf3ae29d9a88ff70b98374fc665694a)

Essentially, legacy optimizer makes an `EVMC_CALL` in the context of a call to `f(int256)` i.e., excluding the call to the function itself, there is another call made inside the function body (my guess is this is due to `ecrecover`)

IR optimizer does not make this `EVMC_CALL`.

Both engines fail (my guess is due to accessing code of an non-existent address returned by the call to ecrecover).

**Comment by bshastry** [comment]
> Both engines fail (my guess is due to accessing code of an non-existent address returned by the call to ecrecover).

Failure is due to failed `abi.decode` operations (both left and right operand). Legacy (right-to-left) fails on the `abi.decode` containing the call to `ecrecover` (hence the extra EVMC_CALL) while IR fails on the (left) `abi.decode` operand and hence the lack of an EVMC_CALL. I would vote to close this issue now since this is essentially documented behavior unless someone thinks otherwise.

**Comment by hrkrshnn** [comment]
```solidity
contract C {
  function f(int) external {
       abi.decode("",(bytes7)) ^
       abi.decode(
           ecrecover(
               abi.decode("dc12600bb44e943dc10568cbccc68d4c",(bytes32)),
               2,
               0,
               keccak256(bytes.concat(bytes2(0)))
            ).code,
           (bytes7)
       );
  }
}
```

Simplified.

**Comment by bshastry** [comment]
Closing since the call issue is explained by the evaluation order difference between legacy and IR engines which is now publicly documented.
