### ISSUE TITLE
Overhaul and modernize CMake setup.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12515]
Our cmake setup is an organically grown mess that today violates pretty much every best practice for writing clean modern cmake code.

One example is the entire mess around ``EthCompilerSettings``. What we should really do is to define an ``INTERFACE`` library to collect flags and pass them to the appropriate targets. Stuff like ``fdiagnostics-color`` has no business being defined there at all, that belongs in the user's configuration. Things like ``CMAKE_CXX_FLAGS_DEBUG`` should remain untouched. Etc. pp...

From all the issues and questionable things I see in this file alone, I'd actually tend to say we should just rewrite the cmake logic entirely - that can be done quickly and cleanly.

For the record: this was triggered by ``$<$<COMPILE_LANGUAGE:CXX>:-Wextra-semi>`` in ``EthCompilerSettings`` breaking for @christianparpart, after which we realized that our cmake setup is broken for ninja builds entirely right now. But the entire mechanism there is one single hack that should be replaced :-). 
https://github.com/ethereum/solidity/pull/11422 tried to work on this part once, but to be honest the result was not much better than what we have and also contrary to my understanding of modern cmake best practices.

**Comment by christianparpart** [comment]
Thanks @ekpyron for filing this ticket! We could gather the requirements of what we expect and then see how we can best achieve that. (I'm not saying we should move away from CMake btw - whatever fits best) :)

**Comment by ekpyron** [comment]
We should most definitely stay with cmake - it's the only sane choice. But we should use it properly.

**Comment by cameel** [comment]
> Stuff like `fdiagnostics-color` has no business being defined there at all, that belongs in the user's configuration.

What do you mean by user configuration? Flags passed to CMake? If so then I think we should keep that one. The thing is that by default output is not colored and hard to read. I think it should be enabled by default and that's AFAIK the way to do it.

**Comment by ekpyron** [comment]
The flag is a question of taste and depends on your situation. You may run stuff in an environment, in which colored output is harmful. If you think colored output is more readable in general, then the flag should be in your ``C(XX)FLAGS`` at all times and cmake will automatically pick it up. Stuff like this has nothing to do with the actual build process, so we shouldn't mess with it.

But it's only one of a whole bunch of issues and I don't really mind in this particular case, just saying from my perspective this is also definitely bad style.

**Comment by ekpyron** [comment]
Or tell gcc to make it the default on a terminal that supports colors. Which as a matter of fact is what gcc does anyways, so the flag is redundant in all cases in which it's reasonable anyways.

**Comment by cameel** [comment]
Maybe. I'm looking at it from a practical standpoint - when I joined the project it wasn't obvious at all why it's not enabled by default and how to enable it. Turned out that we had that flag but only for one of the compilers. I think new contributors should not have to go through that. If there's a better way to achieve that then fine but so far I think that having it in the build config solved the issue nicely. I'm not seeing ANSI escapes in logs people post or in CI so it seems to work fine as is.

Anyway, I completely agree with the need to clean up the CMake config but I'm not sure if a rewrite from scratch is the best way to go about it. In my experience smaller, iterative improvements are easier to pull off (there's never time for a big rewrite :)). And with a rewrite it always turns out that half of these warts actually had a good reason to be there and must be painfully restored through bug reports :)

**Comment by ekpyron** [comment]
Usually you may be right, but in this case, I'm pretty sure that a rewrite is significantly easier than trying to fix this :-). But doesn't matter that much to me how to do it, but yeah, it does need cleanup :-).

[Not that we need to argue through it further - but it's rather curious that the color stuff wouldn't have worked by default - for me even pure plain ``gcc`` emits colors without any flag unless explicitly disabled, if it runs in a terminal that claims to support colors... might be that that's newer gcc behaviour, though]

**Comment by cameel** [comment]
Right. Maybe it has changed in the newer compilers. Anyway, you're right, no point in getting deeper into it here, we can argue it in the PR when we actually have one :)
