### ISSUE TITLE
Shadowing named return variable declaration should be an error

### ISSUE THREAD

**Issue by artdgn** [ethereum/solidity#12525]
## Description

Shadowing a named return variable declaration is a warning, but should be an error since the value that is returned is of the one from the signature declaration. Only explicitly returning the variable works, but this defeats the purpose of the syntactic sugar of the named signature declaration and avoiding explicit return statements.

## Environment

Latest Remix environment, with latest compiler 0.8.7.

## Steps to Reproduce

```
pragma solidity 0.8.7;

contract Test {

    function veryBad() public view returns(uint good, uint bad) {
        good = 5;
        uint bad = 5;
        // returns (5, 0) which is totally unexpected
    }

    function notGood() public view returns(uint good, uint bad) {
        good = 5;
        uint bad = 5;
        return (good, bad);
        // returns (5, 5) which is good, but defeats the point of using named return variables
    }
}
```

## Expected behavior
Either:
1. The compiler raises an error "error: shadowing named return variables is not allowed".
2. The compiler returns the last variable with the matching name instead of the first one.

**Comment by ekpyron** [comment]
I don't think option 2 is a good way to go, but I'd be open to promoting this shadowing warning, together with all other shadowing warnings, to errors. However, that would be a breaking change, so we could only do it for 0.9.0.

**Comment by artdgn** [comment]
>  but I'd be open to promoting this shadowing warning, together with all other shadowing warnings

I'm not sure if other cases of shadowing must be errors, but this one is extra dangerous because it's actually reverse-shadowing. The shadowee, rather than the shadower is what's actually returned in the end, even though the correct variable may be used throughout the method.

**Comment by ekpyron** [comment]
Ok, I see that one might interpret it like that, yeah...
To me it seems just like regular shadowing: until I redeclare ``bad``, the name refers to the return variable, so assigning to it will change what is returned, and after I redeclare ```bad`` as a local variable, the name just refers to that local variable and assigning doesn't affect the return value anymore.
That's also why I wouldn't go for option 2: to me there seems to be little reason to expect the shadowing local variable to end up affecting the returned value - it's just a regular local variable.

But independently of that, you may be right, we could consider shadowing return variables to be "potentially more harmful" than other forms of shadowing.

So we have three options to consider:
1. Rely solely on the warning as we emit now.
2. Make shadowing return variables an error specifically.
3. Make any kind of shadowing an error.

**Comment by artdgn** [comment]
> To me it seems just like regular shadowing: until I redeclare bad, the name refers to the return variable, so assigning to it will change what is returned, and after I redeclare ```bad`` as a local variable, the name just refers to that local variable and assigning doesn't affect the return value anymor

I think it depends on the mental model of the user. My simplistic mental model (not being aware of how the implementation works), is that named return variables work as if they add an implicit `return (namedVar1, namedVar2);` that I don't need to write myself (e.g. if there are multiple `if` branches in the method). However, in reality, in case of shadowing, the explicit `return (namedVar1, namedVar2);` returns local variables, but the implicit `return (namedVar1, namedVar2);` returns signature variables. 

The danger is in a large enough project with already existing compiler warnings that are disregarded (for various reasons). A new warning might be easily missed by someone working on a particular scoped change, and the reviewer of that code might miss the shadowing, or have the wrong mental model about it, thinking that it should work.

**Comment by ekpyron** [comment]
Yes, I see!
Just as a side-remark unrelated to the issue at hand (you make a good case for making this particular case a full error): our goal is actually that there are no warnings whatsoever that (1) cannot be explicitly silenced via minor adjustments to the code (while retaining the desired behaviour) and (2) for which it is just fine to just ignore them completely.
So any warning should be taken seriously and production code should never have any residual warnings. If you know cases, in which this is impossible for any reason whatsoever, it may be worthwhile to open separate issues about that.
