### ISSUE TITLE
@notice tag used identically, producing errors arbitrarily

### ISSUE THREAD

**Issue by namrapatel** [ethereum/solidity#12524]
## Description

The notice tag seen in the images below is used identically in both images, but produces an error in one and not the other. 

Implementation without error:
<img width="487" alt="Screen Shot 2022-01-13 at 1 14 43 AM" src="https://user-images.githubusercontent.com/25423974/149275776-2e5754c6-3e1c-4cdd-a27c-8d4e3c56cdf9.png">

Implementation with error:
<img width="603" alt="Screen Shot 2022-01-13 at 1 14 58 AM" src="https://user-images.githubusercontent.com/25423974/149275801-5bee5698-b118-4fea-9559-9013c41ec879.png">

Error displayed:
<img width="631" alt="Screen Shot 2022-01-13 at 1 15 27 AM" src="https://user-images.githubusercontent.com/25423974/149275849-0de660c7-862b-4b93-ad7b-e94921e1bfbc.png">

## Environment

- Compiler version: v0.7.6+commit.7338295f
- Target EVM version (as per compiler settings): Unsure how to retrieve this information.
- Framework/IDE (e.g. Truffle or Remix): VSCode
- EVM execution environment / backend / blockchain client: Unsure how to retrieve this information.
- Operating system: MacOS Monterey 12.0.1

## Steps to Reproduce

I'm not quite sure how to reproduce this because this appear to be happening arbitrarily (or at-least I can't seem to identify a reason it should be happening in one file and not the other). I believe the images above are as informative as I can really be as far as reproducing the bug goes.

**Comment by cameel** [comment]
Thanks for the report!

It's not a bug though. You are using solc 0.7.6 and back then the `@notice` tag was not allowed on non-public state variables. This changed in 0.8.4 and now it's allowed. If you want to use `@notice` like this, please update to a newer compiler version.
