### ISSUE TITLE
Migrating project from solidity 0.6.6 to 0.8.6 raises Stack too deep when compiling inline assembly

### ISSUE THREAD

**Issue by dsapaev** [ethereum/solidity#12534]
Hi everybody!
We have a contract, that works fine with Solidity 0.6.6. I try to migrate our contract to 0.8.6, but compiler raises Stack too deep, when i using structs. Here the small example:
```
pragma solidity ^0.8.6;
interface ICompileError {

    struct A{
        bool arg1;
        InnerA arg2;
    }

    struct InnerA{
        address[] arg1;
        bool arg2;
    }

    struct B{
        uint arg1;
        InnerB[] arg2;
    }

    struct InnerB{
        uint[] arg1;
        bool arg2;
    }

    function stackToDeep(A calldata arg1, B calldata arg2) external returns(B memory, address[][] memory);
}
```

And implementation:
```
pragma solidity ^0.8.6;
import "./ICompileError.sol";

contract CompileError is ICompileError{
    function stackToDeep(A memory arg1, B memory arg2) public override returns(B memory, address[][] memory result){
        (arg2, result) = ICompileError(address(0x0)).stackToDeep(arg1, arg2);
        return (arg2, result);
    }
}
```

What can i do to fix it? I can not turn off optimization, because our contract is very large

**Comment by ekpyron** [comment]
This is a ``stack too deep`` error in the ABI decoding functions. It's a known issue and not easy to circumvent.
We are working on improving the situation in the new code generation pipeline via Yul.

With the most recent compiler version 0.8.11, your example compiles for me without error using ``--experimental-via-ir --optimize``. Is that an option for you? Code generation via Yul IR can be considered stable at this point, we will stop calling it "experimental" in one of the upcoming releases. (It would probably be wise to double-check if any of the slight behaviour changes listed in https://docs.soliditylang.org/en/latest/ir-breaking-changes.html affect you, though).

**Comment by dsapaev** [comment]
Thanks, we decided to refactor our contract and use old optimizer while YUL is experimental

**Comment by ekpyron** [comment]
Ok, I'll close this issue then, feel free to reopen if you need anything else.
As for compilation via Yul: you can expect it to be officially marked stable in Q1 2022 - my current guess would be 0.8.13.
