### ISSUE TITLE
Further Document the resiliency of storage usage

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12547]
This extends. https://github.com/ethereum/solidity/issues/5293

---

A commitment has been made on the resiliency of Solidity storage slot locations:

> To summarize: If compiling a contract with different Solidity versions results in different storage layout, this would be a bug in the compiler. We currently have no plans to change the layout, not even in breaking releases.
>
> https://twitter.com/ethchris/status/1073692785176444928

And this commitment is being dependent on in EIP-1967 (DRAFT).

---

Please document this commitment in official project documentation.

**Comment by chriseth** [comment]
I'm sorry, but "we currently have no plans" does not sound like a commitment to me that needs documenting. What do you want to achieve and what would your proposal for a documentation update be?

**Comment by fulldecent** [comment]
How about this?

> All released versions of Solidity are backwards compatible as to storage layout. It is anticipated that all future releases will continue as such.

Such language would be helpful for e.g. EIP1967 as well as block explorers which may perform inspection of storage locations.

I can make a PR if acceptable.

**Comment by chriseth** [comment]
I don't think this is the right language. We cannot tell what the future brings.

Would it be a big enough commitment for you to say that storage layout changes are a breaking change and if this happens, we try to provide a mechanism so that new contracts can always be compiled in a "compatibility mode"?

**Comment by fulldecent** [comment]
Yes, that's great.

PR -> https://github.com/ethereum/solidity/pull/12638

**Comment by fulldecent** [comment]
Fixed here https://github.com/ethereum/solidity/pull/12638, closing
