### ISSUE TITLE
Emit a warning when an assignment is unintentionally used in a condition

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/solidity#12543]
## Abstract

Emit a warning when an assignment is unintentionally used in a condition.

## Motivation

```solidity
bool a;

if (a = false) {
}
```

The above code snippet is likely never intended. Solidity should emit a warning if a variable assignment is used in a condition without further comparisons.

## Specification

The simplest option would be to blanket warn if _any_ assignment appears in a condition, but that is fairly limited. Unless assignment return values are going to be deprecated, this option is likely unworkable.

Instead, taking inspiration from GCC's [`-Wparentheses`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wparentheses), it might be possible to warn if an assignment in a condition appears without parentheses.

For example, this would not generate a warning:

```solidity
uint a;

if (6 > (a = 5 + 4)) {
}
```

While this would:

```solidity
bool a;
if (a = true || false) {
}
```

## Backwards Compatibility

Since this is just a warning, it shouldn't affect backwards compatibility.

**Comment by ekpyron** [comment]
At least warning in cases without parentheses is probably a good idea!

**Comment by Marenz** [comment]
Going with the same logic, would 

```
bool a;
if ((a = true) || false) {
}
```

or 

```
bool a;
if ((a = true || false)) {
}
```

create a warning?

**Comment by ekpyron** [comment]
IIUC the first one would be fine, the second one would warn or fail. While
``if ((a = (true || false))) ...`` would be fine again, but assign a different expression to ``a`` (which happens to have the same value in the example).

**Comment by chriseth** [comment]
I'm a bit torn on this, since the easy fix is to never compare to bools but use `!a` instead.
Does this problem happen a lot so that it requires a feature in the compiler instead of a linter?
