### ISSUE TITLE
A static check for reentrant calls

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12540]
[Context](https://twitter.com/maurelian_/status/1482392167884763136)

Actually not sure how this can be implemented in a way that minimizes false positives. 

This can be an info message.

**Comment by ekpyron** [comment]
IIRC @leonardoalt put some work into having the smt checker prove reentrancy safety, but not sure how well that'll work in complex cases in practice :-).

**Comment by leonardoalt** [comment]
I don't think we should rely on the smtchecker to give this type of warnings. I think what they mean is probably a syntactic check

**Comment by ekpyron** [comment]
Yeah, sure - but if we decide *against* a syntactic check, since it'd have too many false positives, we could nudge people into trying that, if they want automatic analysis (in case it works reasonably well in practice).

**Comment by hrkrshnn** [comment]
@leonardoalt Even for SMTChecker, one will have to manually add a reentrancy lock to a function and see if the SMTChecker can tell if the function is reentrant, right? It would be nicer if one doesn't have to add the lock.

**Comment by leonardoalt** [comment]
Right that's true. For that feature you'd have to add some new query.
