### ISSUE TITLE
Investigate and improve test coverage for copying reference types between data locations.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12559]
https://github.com/ethereum/solidity/issues/12558 indicates that we are seriously lacking some tests in that area - so we should double-check that we have all combinations covered for value types and reference types up to a certain level of nesting.

**Comment by wechman** [comment]
I went through the tests we have for reference types and found a minimal test set we lack of and might want to provide within this ticket:

1) Copy 2d static array from storage to memory.
```
contract C {
    uint8[2][2] s = [[1, 2], [3,4]];
    
    function f() public {
        uint8[2][2] memory tmp = s;
    }
```

2) Copy element of 3d static/dynamic array from calldata/memory/storage to 2d array in memory/storage.
```
contract C {
    uint[1][1][1] s;
    function f() public {
        uint[1][1] tmp = s[0];
    }
}
```

3) Copy 2d static/dynamic array of structs from calldata/memory to storage
```
contract C {
    struct S {uint8 x;}
    S s;
    function() public {
        S memory local = S({x: 7})l
        s = local;
    }
}
```

4) Copy element of 3d static/dynamic array of structures from calldata/memory/storage to 2d memory/storage array.
```
contract C {
    struct S { uint 8x; }
    S[1][1][1] s;
    function f() public {
        S[1][1] memory local = s[0];
    }
}
```

5) Copy 1d static/dynamic array of structures with nested array from storage to memory.
```
contract C {
    struct S { uint8[2] x};
    S[2] s = [S(x: [1, 2]), S(x: [3, 4])];
    function f() public {
        S memory local =  s[0];
    }
}
```

6) Copy elements of 2d static/dynamic array of structs with nested array from calldata/memory/storage to 1d memory/storage array.
```
contract C {
    struct S {uint8[2] x;}
    S[1][1] s = [[S({x: [1,2]})]];
    function f() public {
        S[1] local = s[0];
    }
}
```

7) Copy to/from `mapping (uint => struct/struct[])` to/from calldata/memory/storage array/struct.
```
contract C {
    struct S { uint8 x; }
    mapping (uint8 => S) m;
    function f() public {
        S memory s = m[0];
    }
}
```
Above code snippets are there just to illustrate what kind of test cases we need so they might not compile properly.
