### ISSUE TITLE
rewrite panoramix code to solidity

### ISSUE THREAD

**Issue by metrocoding** [ethereum/solidity#12555]
I get some code from panoramix decompiler and I wanna simulate it in a solidity.
the statement is so complex for me when I write solidity code from it, it returns a different value than the deployed one. can anyone help me with this I know somehow panoramix doesn't decompile well when the statement is complex, and a lot of math operators with parentheses?
my code:
```
function getResult() public view returns(uint256) {
    uint256 stor2 = uint256(0x3ce0aeabb74024302f3e46);
    uint256 stor3 = uint256(0x2a6b);
    uint256 blockTime = 1642438845;
    address coinbase = address(0xee226379dB83CfFC681495730c11fDDE79BA4c0C);
    uint256 blocknumber = 14449636;
    uint256 gasLimit = 79899525;    

    return uint256(keccak256(abi.encodePacked(stor3 + gasLimit + (blocknumber / 2) + uint256(keccak256(abi.encodePacked(coinbase))) + 
    (stor2 / stor3) + (((stor3 / gasLimit) + (blocknumber / blockTime) + (2 / stor2) + stor3 % 10000) + 
    1 / ((stor3 / 2) + (blocknumber / blockTime) + (gasLimit / stor3) % 1000) + 1))));
}

uint256 result = getResult();
// 25279031313781763603605541083549330584684253007145571427909533898943629946781
```

this is panoramix code that I change to solidity:
```
return sha3(stor3 + block.gas_limit + (block.number / block.difficulty) + sha3(block.coinbase) + (stor2 / stor3) + 
(((stor3 / block.gas_limit) + (block.number / block.timestamp) + (block.difficulty / stor2) + stor3 % 10000) + 
1 / ((stor3 / block.difficulty) + (block.number / block.timestamp) + (block.gas_limit / stor3) % 1000) + 1))

// result: 109084135154033787251718996376557886971406718557167085202600611003726171673652
```
why real contract returns different result? should I change something when I convert my code from panoramic decompiled to solidity?

**Comment by metrocoding** [comment]
i had same problem with statement below:
```
stor3 = (stor3 + (uint256(keccak256(abi.encodePacked(stor2 + 1 + 1642438845))) % 100) + 1 % 10) + 1;
```
then adding parentheses after + 1 help to do calculation correct:
```
stor3 = (stor3 + ((uint256(keccak256(abi.encodePacked(stor2 + 1 + 1642438845))) % 100) + 1) % 10) + 1;
```

**Comment by cameel** [comment]
This is a bug tracker for the Solidity compiler and is meant for reporting bugs and requesting new features. [Ethereum StackExchange](https://ethereum.stackexchange.com) is a better place for questions like this. You can also try asking on the [#solidity](https://gitter.im/ethereum/solidity) gitter channel.
