### ISSUE TITLE
Better documentation for storage pointers

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12550]
Triggered by https://github.com/ethereum/solidity/issues/12549.

We don't seem to have this documented very clearly.
To my surprise I didn't find a nice docs link to respond to that issue and @cameel also had a look and concluded in chat:

    The only thing I could find is this: https://docs.soliditylang.org/en/latest/types.html#data-location-and-assignment-behaviour:
    > Assignments from storage to a local storage variable also only assign a reference.
    I agree that we should have more on that. This is mostly glossed over.

So maybe we should think about where and how to improve the docs on this.

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by NunoFilipeSantos** [comment]
What about something like this example? https://ethereum.stackexchange.com/questions/127954/using-memory-vs-storage-for-arrays-in-structs-in-solidity-qa
