### ISSUE TITLE
Can't construct address array directly

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum/solidity#12563]
```
address[] memory x = [address(0), address(0)];
```

The above will report error:

```
Type address payable[2] memory is not implicitly convertible to expected type address[] memory.
```

I'm using version `0.8.5`

**Comment by ekpyron** [comment]
Thanks for filing this issue!

You're right, that's a known shortcoming right now. Array literals (e.g. ``[address(0), address(0)]``) are only convertible to statically sized arrays at the moment, so only either of the following works:
```
address[2] memory x = [address(...), address(...)];
```
or
```
address[] memory x = new address[](2);
x[0] = address(...);
x[1] = address(...);
```

We know that this is inconvenient and we're working on changing this, so hopefully in one of the next releases you *will* be able to simply use ``address[] memory x = [address(0), address(0)];``.

We're tracking this problem in https://github.com/ethereum/solidity/issues/11879, so I'm closing this issue as a duplicate, but feel free to reopen it, if you want to add anything!

**Comment by zhiqiangxu** [comment]
> address[2] memory x = [address(...), address(...)];

`address[2] memory x = [address(0), address(0)]` doesn't work, reports:

`Type address payable[2] memory is not implicitly convertible to expected type address[2] memory.`

so maybe a separate issue?

**Comment by ekpyron** [comment]
Which version of solidity are you using? That indeed used to be a separate issue, but that's already fixed.
With the current compiler version 0.8.11, it does work for me.

**Comment by zhiqiangxu** [comment]
> Which version of solidity are you using? That indeed used to be a separate issue, but that's already fixed. With the current compiler version 0.8.11, it does work for me.

was using 0.8.5, upgrading to 0.8.11 indeed fixed this issue, thanks!
