### ISSUE TITLE
[Sol->Yul] ICE when copying array of function ptr type from storage to memory

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12564]
```
contract C {
  function() external[1][] s0;
  constructor(function() external[1][] memory i0)
  {
    i0[0] = s0[1];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/0b9ab33fce5057ec4ea70842d13e6eafa593140c/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L2985

Repro

```
$ solc --ir test.sol
```

Note that memory to storage copy of the same type does not throw via IR.

**Comment by ekpyron** [comment]
Also falls under https://github.com/ethereum/solidity/issues/12558

**Comment by ekpyron** [comment]
But due to the base type being a multi-slot type, it's actually an interesting special case, which we should watch out for when fixing #12558, so probably good to keep it open and check specifically.

**Comment by bshastry** [comment]
Closing as duplicate of #12558

**Comment by ekpyron** [comment]
> Closing as duplicate of #12558

Ok, I just commented there to watch out for multi-slot base types then :-).
