### ISSUE TITLE
Extend the language to have an EVENT.selector and ERROR.selector

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#12581]
## Abstract

Add `ev.selector` and `err.selector` fields that would work similarly to `fun.selector`, extracting event signature (topic 0) from its definition

```
interface MyInterface {
    event someEvent();
    error someError();
    function someFunction() external;
}

contract Test {
    function nameIsIrrelevant() public {
        bytes4  x = MyInterface.someFunction.selector; // This works
        bytes32 y = MyInterface.someEvent.selector; // This doesn't, that is what I'd like to add
        bytes32 z = MyInterface.someError.selector; // This doesn't, that is what I'd like to add
    }
}
```

## Motivation

Some cross chain mechanism, such as polygon's [FxBaseRootTunnel](https://github.com/fx-portal/contracts/blob/main/contracts/tunnel/FxBaseRootTunnel.sol), perform event inclusion check that require the event signature. This is likely to become a more frequent need with inclusion proofs being an important part of rollups.

## Specification

Add a bytes32 field named `.selector`, `.topic0` or `.signature` to events (and a similar one to errors), that the compiler would replace with the event's signature (keccak256 of the event description)

## Backwards Compatibility

I can't imagine this would cause any backward compatibility issue

**Comment by axic** [comment]
This data is not currently inspectable on-chain.  Would this mean it would be used for processing some kind of proofs?

Isn't using a constant-keccak256 expression a good enough solution for now?

**Comment by Amxx** [comment]
Yes, it would be used to process some kind of proof.

constant-keccak256 expression is good enough, just like `bytes4(keccak256("transfer(address,uint256")` used to be enough: it works, but it is error prone.

**Comment by frangio** [comment]
`Event.selector` as well as `CustomError.selector` could both make sense. If they're necessary, it's better for the compiler to generate them.

**Comment by maurelian** [comment]
This would likely also be useful for Optimism's bridges

**Comment by chriseth** [comment]
This sounds good, but we have to find a better name. For anonymous events, `topic0` is something else.

**Comment by frangio** [comment]
What about `selector` just like for functions?

**Comment by chriseth** [comment]
Sorry, somehow I missed your coment. `selector` of course makes perfect sense.

**Comment by axic** [comment]
I think for error the term `selector` works, but for events it should have been `topic`.

**Comment by chriseth** [comment]
I was wondering as well, but I think users would find it confusing to have yet another name for something.
