### ISSUE TITLE
Is there any way to identify  which function that call current function?

### ISSUE THREAD

**Issue by PatDoe** [ethereum/solidity#12597]
In the full call chain  , such as Function A in  Contract A -> call Function B in Contract B, is there possible to identify the name of function A in function B?

**Comment by cameel** [comment]
No, currently you can only get function selector through the `.selector` member. The signature is not available that way.

This bug tracker is not the right place for questions like this. Please try the [#soldity](https://gitter.im/ethereum/solidity) gitter channel or [Ethereum Stack Exchange](ethereum.stackexchange.com) instead. It this is actually a feature request, please use the proper template to explain how the feature would work and how it would impact the language.

**Comment by PatDoe** [comment]
> 

thanks
