### ISSUE TITLE
The interaction between function types and the ternary operator is not documented

### ISSUE THREAD

**Issue by mosinnik** [ethereum/solidity#12602]
## Page

https://docs.soliditylang.org/en/v0.8.11/grammar.html

## Abstract

Found code: https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-linear/contracts/LinearPool.sol#L275-L282
```
        return
            (request.tokenOut == _mainToken ? LinearMath._calcMainOutPerBptIn : LinearMath._calcWrappedOutPerBptIn)(
                request.amount,
                balances[_mainIndex],
                balances[_wrappedIndex],
                _getApproximateVirtualSupply(balances[_bptIndex]),
                params
            );
```

But can't find any documentation for such function choosing. Can anyone link to docs how it work?

## Pull request
-

**Comment by cameel** [comment]
`LinearMath._calcMainOutPerBptIn()` and `LinearMath._calcWrappedOutPerBptIn()` are just internal functions defined in a library and if you refer to a function by name (without giving it parameters), you get a value of a [function type](https://docs.soliditylang.org/en/latest/types.html#function-types). This is a very common convention, used for examplein C, C++, Python or JavaScript. In Solidity you can use such values in some expressions and the ternary operator is one of them.

Is the documentation on function types enough or do you think it should be refined in some way?

**Comment by mosinnik** [comment]
@cameel thanks, docs is enough, just can't find it
