### ISSUE TITLE
Function override inconsistency bug

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#12615]
## Description

Inconsistent `override` identifier necessity behavior. We can have a typo in the method name and the compiler will not give us a clue we have 2 methods instead of 1.

## Environment

- Compiler version: 0.8.11
- Framework/IDE (e.g. Truffle or Remix): Remix, Hardhat

## Steps to Reproduce

Using `contract Ext is IExt, Base {}` in the following code unexpectedly produces no errors but changing inheritance order to the following `contract Ext is Base, IExt {}` leads to an expected error of missing `override` identifier in `Impl::foo()`.

```solidity
// SPDX-License-Identifier: MIT

pragma solidity 0.8.11;

interface IBase {
    function foo() external view;
}

contract Base is IBase {
    function foo() public virtual view {}
}

interface IExt is IBase {}

contract Ext is IExt, Base {}

contract Impl is Ext {
    function foo() public view {}
}
```

**Comment by ekpyron** [comment]
Oh, wow, thanks! Apparently something went wrong there when we dropped the ``override`` requirement on ``interface`` functions, we should definitely fix this ASAP!
