### ISSUE TITLE
Doc: slot calculation for mappings of strings/byte arrays

### ISSUE THREAD

**Issue by shuklaayush** [ethereum/solidity#12612]
## Page

https://docs.soliditylang.org/en/v0.8.11/internals/layout_in_storage.html#mappings-and-dynamic-arrays

## Abstract

> The value corresponding to a mapping key k is located at keccak256(h(k) . p) where . is concatenation and h is a function that is applied to the key depending on its type:
>
> - for value types, h pads the value to 32 bytes in the same way as when storing the value in memory.
>
> - for strings and byte arrays, h computes the keccak256 hash of the unpadded data.

I think the second bullet point here is incorrect. For strings and byte arrays, h is just the unpadded data and not its hash.

## Pull request

I can make a PR once I get a confirmation

**Comment by chriseth** [comment]
Oh wow, this is embarassing! You are totally right!
