### ISSUE TITLE
NatSpec: allow @dev @param @inheritdoc for libraries

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12613]
## Page

[
](https://docs.soliditylang.org/en/latest/natspec-format.html?highlight=NatSpec)

## Abstract

Update NatSpec specification at https://docs.soliditylang.org/en/latest/natspec-format.html?highlight=NatSpec

And update JSON parser.

## Pull request

(I can make if invited)

**Comment by chriseth** [comment]
Sorry, I don't understand what this issue is about. If you want, please create a PR directly.

**Comment by fulldecent** [comment]
Yeah, wow that was pretty bad, sorry!

Fixed at https://github.com/ethereum/solidity/pull/12618
