### ISSUE TITLE
New data type of variable (Built-in struct/class such as encrypted)

### ISSUE THREAD

**Issue by NineWoranop** [ethereum/solidity#12619]
## Abstract

In C/C++, you could create your class with custom operator and functions that code could be used in OOO.
From my understanding, it still be too early to introduce custom functions that could be stored on blockchain and they could be executed from any EVM. so I will reduce the scope to be new data type as built-in classes that will be supported on EVM.

## Motivation

Due to current data types that solidity have been supported, they have been designed to keep value(s) only(not even reference type and mapping type).
As you know, all values in blockchain will be transparent. What if I would like to introduce built-in class such as encrypted. You might ask that. Why do you not create a method and keep the result as variable? Back to data on blockchain world need to be transparent, the built-in class will introduce new one ability that has functions so this variable does not keep only value anymore but it could be execute with specific condition/situation.
Let's me introduce a use case for Health Insurance that could support arcoss our world.
If we have a Oracle for that would like to keep trace information (policy number, beneficiary name, gender, birthday, country, id, etc) of human that need to pass any orgnizations(include owner of information).
First thing, To make it could be aligned. This Oracle need to define standard format of data that need to be keeped.
Second thing, To make data could not be read by anyone, this Oracle would like to encrypted this personal information on blockchain even it is transparent data. so EVM need to encrypted this data.
Third thing, To make data could read(decrypt) information from some orgnizations (such as owner, hospital, clinic, etc). This Oracle could allow this data to be decrypted with specific condition/situation. How? In this case, the condition should EVM has private key to decrypt this data. Owner (address) need to generate a keypair and use public key to signed data during create a encrypted data. 

## Specification

encrypted data type should be the data type of data that have supported methods such as encrypt and decrypt

encrypted {variableName} = encrypt({data}, {condition when EVM could decrypt})

Example

struct Policy {
    uint256 policyNumber;
    string beneficiaryFirstName;
    string beneficiaryLastName;
	...
}

policyData = Policy({policyNumber: 123, beneficiaryFirstName: "NineWoranop", beneficiaryLastName, "", ...});
address myAddress = this;
encrypted enData = encrypt(policyData, (Address.isTheOwner())

## Backwards Compatibility

N/A

**Comment by chriseth** [comment]
I'm not sure I understand your proposal. Do you want to have a mechanism to access functions or data in implementations of the EVM that differ from Ethereum mainnet? If yes, then a high-level built-in data type is probably not the right way to do this. My counter-proposal would be to allow access to these features through inline assembly (or by calling special contracts at pre-defined addresses) and then build a custom data type (not provided by the compiler) around this.

**Comment by NineWoranop** [comment]
@chriseth Sorry, my proposal might not be clear enough. As I mentioned early, I would like to let solidity think about new kind of ability on the language as built-in function that could attach on data type. In this case, I expected to have specific function (encrypt) similar with "required" function that support condition. However, encrypt function does not use the condition immediately at that line of code. However, this condition will attach to variable and it will be execute when it used by specific function (decrypt). I hope that makes more clearer.

**Comment by chriseth** [comment]
Can you maybe write a small and complete example that does not contain `...`?

**Comment by NineWoranop** [comment]
It seems my specification, use case and example don't quite right from start.
For now, I could not come up with better use case and example. 
Let's me re-define the specification and example.

#### Specification
encrypted {variableName} = encrypt({data}, {condition function})
OR
encrypted {variableName} = encrypt({data}, &{condition function})

#### Synonym
- &
means Point to a function. It could be built-in function or custom function.
- condition function
means the whole function that has return type as Boolean only.
developer could put the whole function as parameter by has similar syntax.
    function myConditionFunction() public returns (bool) {
       return true;
    }

#### Example
    struct Policy {
        string data;
        string totp;
    }
    
    string policyData = "policynumber=123,name=NineWoranop";
    address myAddress = this;
    string myTimeBasedOTP = myAddress.generateTOTP();
    Policy originalData = Policy({data: policyData, totp: myTimeBasedOTP});
    encrypted encryptedData = encrypt(originalData, &Policy.isTheOwner());
    
    function (Policy policy) isTheOwner() public returns (bool) {
        address myAddress = this;
        string myTimeBasedOTP = myAddress.generateTOTP();
        require(policy.totp == myTimeBasedOTP, "Not authorized");
        return true;
    }

Notes !!! 
- (Policy policy) this syntax borrow from GOLANG.
- myAddress.generateTOTP() should be another built-in function that only owner of address that have private key, it could generate Time-based OTP.
Due to current EVM don't support to get private key. However, EVM might need to consider to support some functions that could use private key without pass through the code of developer.
TOTP might not be best practice in real world for this use case to validate. However, I would like to see Solidity could explore this ability on the language.
@chriseth I'm not sure. Does it make more sense? Could you please re-consider this proposal?

**Comment by NineWoranop** [comment]
@chriseth In case, that encrypted data type seems not be clear description yet.
I could reduce the scope to be another proposal if it still be interested.

#### Specifition

    condition {variableName} = conditionInterface{condition:{struct/class}, pass:{condition function of struct}};

    interface conditionInterface{
        function condition(struct data) public view returns(bool);//always return true because it expects to store data successfully.
        function pass() public view returns (bool);

        function data() public view returns (struct/class);
        // this function should invoke pass() method with require automacally
        // similar like this
        //      require(myCondition.pass(), "Not authorized");
    }

#### Example

    contract counterContract {
        // Private variables
        condition private myCondition;

        struct Counter {
            uint8 index;
        }

        function (Counter couter) pass() public returns (bool) {
            return (counter <100);
        }

        constructor(string data) {
            uint8 index = checkLength(data);
            Counter counter = Counter{index:index};
            myCondition = conditionInterface{condition:counter, pass:Counter.pass()};
        }

        private function checkLength(string data) public returns (uint8) {
            uint8 result = uint8(bytes(data).length);
            return result;
        }

        function readLength() public returns(uint8){
            return myCondition.data().index;
        }
    }


As you could see condition data type, it still stores value(s). However, it also keeps condition logic inside.
As I mentioned, I would like to see solidity could add new ability on data type in some way.
I hope that this is just a starting point. The way to put logic will be keep evolving in future.

**Comment by chriseth** [comment]
I'm sorry, but I still have no idea what area your proposal actually lies in.
