### ISSUE TITLE
AST JSON tests do not clear AST for parse-only test cases.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12621]
For example ``test/libsolidity/ASTJSON/assembly/switch.json`` and ``ASTJSON/assembly/nested_functions.sol`` can have arbitrary contents and the tests still pass.
My guess is that's because it's tests with syntax errors and the tests only consider the ``parseOnly`` cases. I'm not sure it's intentional for the cases, though, or whether they just broke at some point unnoticed. In any case this should be fixed.

Furthermore, it's not so nice that the AST JSON tests throw, if the ``.json`` files are missing - it should rather just create them.

**Comment by chriseth** [comment]
The logic for these tests are in `test/libsolidity/ASTJSONTest.h` / `.cpp`

You should be able to run only these tests using `isoltest -t *ASTJ*` or something similar.
