### ISSUE TITLE
Add support for IPFS

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#1262]
We would like to see support for allowing import from an IPFS hash.  

```
import "ipfs://http://ipfs.digix.io/ipfs/show/QmboQ6BnzAvEirV8XGRN4WW9m7UhGXkWgCsrMYyZwH33fT/sol" as AccountManagerFactory;

...
```

**Comment by chriseth** [comment]
This falls into the realm of the compiler "driver", i.e. browser-solidity, solc-js, dapple, truffle or whatever.

Moved to https://github.com/ethereum/browser-solidity/issues/274
