### ISSUE TITLE
Ideas for built-in SMT

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#12639]
- do the splitting earlier, so that the theory component can report a minimal set of infeasible clauses back to the boolean component
- the theory component can synthesize simple boolean implications using bounds on variables: If we have literals `A: x <= 7` and `B: x < 8`, it can infer `\neg A \lor B`.
- when the theory component finds a set of infeasible constraints, it might be good to run it again, removing each constraint to find a minimal set (because otherwise, we will likely run it again anyway)
- because of this, the cache could actually be built such that it suffices to find an infeasible subset of the input

CDCL very rough:
look at https://github.com/msoos/minisat-v1.14
add theory conflict analysis: return clause
if we only have positive constraint literals, we can ignore anything set to false, won't be wrong but inefifcient

**Comment by chriseth** [comment]
Relates to https://github.com/ethereum/solidity/pull/12002

**Comment by ekpyron** [comment]
May be worth thinking about a more involved incremental simplex implementation à la https://yices.csl.sri.com/papers/cav06.pdf
