### ISSUE TITLE
LSP Feature doHover() Implementation

### ISSUE THREAD

**Issue by stevennevins** [ethereum/solidity#12648]
## Abstract

I'm pretty sure doHover() is a LSP method that allows for automatic/keyboard shortcut triggered documentation popups.  The coc plugin indicated that it couldn't show documentation because doHover() wasn't implemented by the lsp

## Motivation

Standard lsp method that will benefit other integerations

## Specification

Expose doHover()

## Backwards Compatibility

N/A

-->

**Comment by chriseth** [comment]
The version we released was a very early preview. Documentation on hover is on our roadmap.

**Comment by cameel** [comment]
We do not handle `doHover()` though, do we? I don't see it in the source at least.

I think we should keep this open until we implement it.

**Comment by chriseth** [comment]
I don't think we should have random issues open for some lsp features and not for others.

**Comment by cameel** [comment]
I think it would not hurt having issues for features that are in scope. Especially now that #7763 is closed. Could be just one issue listing these features though. I'm actually pretty fuzzy on which ones we decided to implement in the end.
