### ISSUE TITLE
LSP Code Folding - Improper folding

### ISSUE THREAD

**Issue by stevennevins** [ethereum/solidity#12649]
## Description

LSP improper detection of code folding

## Environment

- Compiler version: 0.8.11
- Framework/IDE (e.g. Truffle or Remix): Vim
- Operating system: MacOS

## Example

setup function folds improperly

```solidity

// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;
import "ds-test/test.sol";

import "../../Greeter.sol";
import "forge-std/Vm.sol";

contract User {
    Greeter internal greeter;

    constructor(address _greeter) {
        greeter = Greeter(_greeter);
    }

    function greet(string memory greeting) public {
        greeter.greet(greeting);
    }

    function gm() public {
        greeter.gm();
    }
}

abstract contract Fixture1 is DSTest {
    Vm internal constant hevm = Vm(HEVM_ADDRESS);

    // contracts
    Greeter internal greeter;

    // users
    User internal alice;
    User internal bob;

    function setUp(
        address here,
        uint256 amount,
        address who,
        uint256 wad,
        uint256 test
    ) public virtual {
        greeter = new Greeter();
        alice = new User(address(greeter));
        bob = new User(address(greeter));
        greeter.transferOwnership(address(alice));
    }
}

```

<img width="317" alt="Screen Shot 2022-02-08 at 9 40 27 AM" src="https://user-images.githubusercontent.com/12021290/153012756-15845adc-80ef-4e00-9e41-de1ceeabe1ad.png">

**Comment by chriseth** [comment]
Code folding is not implemented in the solidity lsp. Could this maybe come from a different plugin?

**Comment by stevennevins** [comment]
I think i read in the coc plugin docs that it consults the lsp to fold based on syntax.  I'll do a bit more research and report back

**Comment by stevennevins** [comment]
I think this behavior is caused coc trying to handle the code folding itself and this is just coc doing it's best to infer folding ranges without knowing solidity syntax since it's not handled by the lsp.  Might be more appropriate to close this issue and add this to the list prioritizing features to support

**Comment by christianparpart** [comment]
I actually had a look at how LSP can guide folding and it's actually not that complex: => https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_foldingRange

Also, coc.nvim [does support](https://github.com/neoclide/coc.nvim/pull/3819) that, so it should be fairly trivial to ensure functionality with some working clients.
