### ISSUE TITLE
SMTChecker example doesn't output the correct result as stated in the documentation

### ISSUE THREAD

**Issue by skywormfol** [ethereum/solidity#12645]
## Page

https://docs.soliditylang.org/en/v0.8.10/smtchecker.html

## Abstract

For the example Monotonic contract of version 0.8.10, "Since f is indeed monotonically increasing, the SMTChecker proves that our property is correct." according to the documentation.
However, I checked it by my own compiled Solidity, the results are as follows,

Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> overflow.sol:28:16:
   |
28 |         return _x * 42;
   |                ^^^^^^^

Warning: CHC: Assertion violation might happen here.
  --> overflow.sol:33:9:
   |
33 |         assert(f(_b) > f(_a));
   |         ^^^^^^^^^^^^^^^^^^^^^

My command is:
solc_0.8.10 overflow.sol --model-checker-contracts "overflow.sol:Monotonic" --model-checker-engine chc --model-checker-invariants all --model-checker-solvers z3 --model-checker-show-unproved --model-checker-targets all --model-checker-timeout 10

Maybe something wrong with my command?
Btw, the flag of model-checker-contracts seems not work for me, it always checks all the contracts in the file, anything wrong?
Thanks.

**Comment by leonardoalt** [comment]
Hi @gaobo89 !

> Maybe something wrong with my command?

Please note that the timeout is given in milliseconds, and the solver can't find the answer within 10ms. Maybe try giving it a bit more time :) locally for me 100ms is enough, but usually I tend to give it 1s, 10s, or more depending on the problem.

> Btw, the flag of model-checker-contracts seems not work for me, it always checks all the contracts in the file, anything wrong?

Which solc version? There was a recent bug that was causing that, which was fixed 2 or 3 versions ago. If you're using the latest version and still seeing that behavior please open an issue and we can check there.

**Comment by skywormfol** [comment]
> 

Dear Leo,

Thanks for your response, it solves my problem, the timeout really matters!
