### ISSUE TITLE
I have implemented LLVM supports. 

### ISSUE THREAD

**Issue by Kenun99** [ethereum/solidity#12643]
## Abstract

We need generate LLVM bitcode for each smart contract so as to support code-independent optimizations or sanitizers. 

## Motivation

Actually, I have implemented EthSema (https://github.com/Kenun99/ethsema) to translate **EVM bytecode** to **LLVM bitcode**. To evaluate the correctness of the LLVM bitcode generated. I further use it to compile for eWASM smart contracts via an LLVM backend. In my experiments, these eWASM contracts can run in the Ethereum 2.0 blockchain.

## Backwards Compatibility

It does not affect the compatibility.

**Comment by chriseth** [comment]
This is out of scope for this project, sorry.
