### ISSUE TITLE
Rethrowing reverts

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12654]
## Abstract
There is currently no way to catch and rethrow the exact same error in a high-level way. This is problematic especially in the `catch(bytes memory)` clause where you can't simply create another instance of the same error type and copy the parameters.

Many languages have a convenient mechanism for rethrowing exceptions. For example in C++ you can use `throw;` in a `catch` block. Python has `raise`, which does the same thing when used without arguments. In Solidity `revert;` could be used for this purpose.

## Motivation
A practical use case where this would be useful is suppressing errors conditionally. Consider this example:

```solidity
function processBatch(Data[] calldata data, bool ignoreErrors) public returns (uint) {
    uint successCount = 0;
    for (uint i = 0; i < data.length; ++i) {
        try c.processData(data[i]) {
            ++successCount;
        } catch (bytes memory lowLevelData) {
            if (!ignoreErrors)
                assembly {
                    let start := add(lowLevelData, 0x20)
                    let end := add(lowLevelData, mload(lowLevelData))
                    revert(start, end)
                }
        }
    }

    return successCount;
}
```
`processBatch()`, depending on the value of `ignoreErrors` parameter, can either revert as soon as an external call fails or suppress all errors and try to process any batches that do not fail. The problem is that the decision must be made inside the `catch` block and there is no high-level way to continue with the same error once we're there.

It can be achieved with low-level `revert` in inline assembly but users should not be forced to reach for low-level mechanisms to do this. Especially since the user is likely to do this instead:
```solidity
                assembly {
                    returndatacopy(0, 0, returndatasize())
                    revert(0, returndatasize())
                }
```
which writes to arbitrary memory locations and is problematic for our new mechanism for moving extra variables to memory.

## Specification
If a `revert` statement without any arguments appears in a `catch` block, the compiler should generate code that reverts with the same error data it received from the external call.

Outside of `catch`, bare `revert` should be disallowed just as it is now.

With the new feature the catch block in the function above would look like this:
```solidity
        } catch (bytes memory lowLevelData) {
            if (!ignoreErrors)
                revert;
        }
```

## Backwards Compatibility

The change is fully backwards-compatible because `revert;` currently causes a compilation error.

`revert` with an empty message (i.e.  `revert("")`) is a different thing and should not be affected by this change.

**Comment by axic** [comment]
I came across this problem several times, but I do not think this is the right approach.

The simplest solution is just allowing `revert(bytes)` to be a passthrough command (i.e. not padding the `bytes` with anything). In essence we would have three signatures:
- `revert()`
- `revert(bytes)` -- uses the `bytes` buffer as the entire revert content
- `revert(string)` -- uses the `string` as the `Errror` payload

**Comment by cameel** [comment]
Why do you think it's not the right approach? It's a pretty common way to do this in other languages.

I would not be against just adding `revert(bytes)` but I think it has a higher potential for mistakes. People have to convert `string` to `bytes` all the time because you cannot do much with `string`. I can image a situation where someone passes in a `bytes` variable thinking it will be used as a message. People make mistakes all the time but the problem here is that this wouldn't be very apparent because it would appear to work.

Also, this would not work in the `catch` clause that has no argument.

**Comment by frangio** [comment]
`revert;` for rethrowing doesn't look right to me either. I would've assumed it was equivalent to `revert()`, and would never have expected it to rethrow. I didn't remember C++ did it this way and was not familiar with the Python construct either.

I also think `revert(bytes)` has potential for mistakes. What about `revert bytes;`, more in line with the revert statement for custom errors?

**Comment by cameel** [comment]
> What about `revert bytes;`, more in line with the revert statement for custom errors? 

It would not be bad on its own but I'd also expect users to be confused about the difference between `revert("");` and `revert "";`.

Plain `revert;` also has the problem that it could be taken for `revert("")` but it's such a common pattern that I think it might be acceptable. Honestly, I'm shocked to discover that JavaScript (and Java) are the exceptions that do not have this. A lot of very popular languages do. C++, Python, Ruby, C#. Hell, even Object Pascal/Delphi did. It always seemed pretty universal to me.
