### ISSUE TITLE
string.concat test cases facing issues with compileToEwasm setting

### ISSUE THREAD

**Issue by nishant-sachdeva** [ethereum/solidity#12651]
## Description
Of the test cases added in the PR #12628  for issue #12087, three test cases have given non-expected outputs when running with the flag `compileToEwasm: also`

1. string_concat_2_args.sol
2. string_concat_different_types.sol
3. string_concat_nested.sol

## Steps to Reproduce
For Eg: Running the command 
`./build/test/tools/isoltest --no-smt --vm ../libevmone/libevmone.so --vm ../hera-0.5.0-linux-x86_64/lib/libhera.so  -t "*string_concat_2*" --ewasm --evm-version byzantium` 

gives different outputs with the Old and New Code generators

Running the command 
`./build/test/tools/isoltest --no-smt --vm ../libevmone/libevmone.so --vm ../hera-0.5.0-linux-x86_64/lib/libhera.so  -t "*string_concat_2*" --ewasm`

gives the compile error 
`semanticTests/strings/concat/string_concat_2_args.sol: Exception during test: /solidity/test/libsolidity/SemanticTest.cpp(401): Throw in function solidity::frontend::test::TestCase::TestResult solidity::frontend::test::SemanticTest::runTest(std::ostream&, const string&, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: Failed to deploy contract.`

Removing the `compileToEwasm: also` flag results in error-free compilation and execution of the test cases with both the aforementioned commands

**Comment by NunoFilipeSantos** [comment]
We're closing all wasm issues for now.
