### ISSUE TITLE
distinct `call` behavior on non-payable `address` type

### ISSUE THREAD

**Issue by nvnx7** [ethereum/solidity#12657]
## Abstract

The methods `send` and `transfer` were introduced only for `address payable` with the intention to explicitly differentiate the addresses that can be sent Ether. But these two methods are now being [discouraged](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/) in the Solidity community, in favor of `call`.

But, currently, the `call` can be invoked successfully on both non-payable `address` and payable `address payable` types with some value set. For example, it is perfectly valid to send `someone` (`address` type) some Ether by invoking `sendSomeone()` method in the following `Dummy` contract:
```solidity
pragma solidity ^0.8.0;

contract Dummy {
    address someone = 0xAb8...cb2;

    function balanceOf(address addr) public view returns (uint) {
        return addr.balance;
    }

    function sendToSomeone() public payable returns (bool) {
        (bool sent, ) = someone.call{value: msg.value}("");
        return sent;
    }
}
```

## Motivation

Apart from defeating the original intention of differentiating `address` and `address payable`, the current behavior of `call` might introduce potential bugs or even security flaws by mistaken invocation of `call` on an address that wasn't even supposed to be payable. Changing the behavior of `call` in different contexts will further enforce the security in the contract.

## Specification

A possible solution is the different behavior of `call` for `address` and `address payable` types.

For `address payable` it should work as it works now. No changes.

But for a plain `address` type it should not compile if it is invoked with `value` param set. So, if `call` is invoked on `someAddr` of `address` type it won't compile:
```solidity
someAddr.call{value: 10000000}("");  // Error: Invalid!
```

However, it should be good if there is no value param:
```solidity
someAddr.call{gas: 1000000}("");  // This is fine!
```

## Backwards Compatibility

This change will not be fully backward compatible as currently `call` is allowed with `value` set and the proposed solution asks to prohibit it.

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/11017
