### ISSUE TITLE
Immutable style guide

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/solidity#12675]
## Page

https://docs.soliditylang.org/en/v0.8.10/style-guide.html

## Abstract

There is nothing that references the immutable variable style guides. 

Should it follow the syntax of `CONSTANTS_WITH_UNDERSCORES` or `camelCase`?

**Comment by chriseth** [comment]
@fulldecent (sorry, seems I cannot just assign)

**Comment by fulldecent** [comment]
Thank you. Added to project board at https://github.com/users/fulldecent/projects/2/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Repository%22%5D

And will follow back here.

This is prioritized as "new opinions" which is below "broken things".
