### ISSUE TITLE
Confusing error message relating to mutability modifiers

### ISSUE THREAD

**Issue by hjorthjort** [ethereum/solidity#12674]
## Description

I find the following error message confusing, implemented in [libsolidity/analysis/ViewPureChecker.cpp](https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/ViewPureChecker.cpp), line 249.

```
Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
```

This is what you get if you try to modify state in a `view` or `pure` function, which is common for a beginner. This is thus one of those messages where the compiler acts as a teacher.

I don't think every user has the mental model "there are four mutability modifiers: non-payable, payable, view and pure". It is [featured in the documentation](https://docs.soliditylang.org/en/v0.8.11/grammar.html?highlight=non-payable#a4.SolidityParser.stateMutability), but not prominently or beginner-friendly. My own mental model up until now has been that payable/non-payable is one category of modifiers, and pure/view is another, even though I was aware that a pure or view function can't be payable. The mental model of these being four mutually exclusive mutability levels makes sense, but I just never acquired it before.

Given that, I think a more sensible, helpful error message would be one that is more instructive in *what needs to change* (Rust is really good at this):

```
Function declared as <view|pure>, but this expression (potentially) modifies the state. Remove the <view|pure> modifier.
```

The question of whether a function should be payable or not is, to some extent, different, and would be addressed by other error messages if the user invokes `msg.value` or `callvalue()`.

I know there is discussion about making mutability explicit on all functions (by requiring `payable` or `nonPayable`).

## Environment

- Compiler version: 8.12

## Steps to Reproduce

```solidity
contract Foo {
    uint private localVal = 0;
    function read() public view {
        localVal = 1;
    }
}
```

**Comment by Marenz** [comment]
@hjorthjort do you think this message would be less confusing?

`Function cannot be declared as <view|pure> because this expression (potentially) modifies the state."`

No explicit suggestion as to what action to take, but it does tell you that pure|view is a problem..

**Comment by hjorthjort** [comment]
Absolutely, I think that's a good message.
