### ISSUE TITLE
Saving an integer to truffle develop does not persist (solidity 0.8.11)

### ISSUE THREAD

**Issue by algorithmical** [ethereum/solidity#12671]
## Description

Saving a value to a contract does not persist. Expected result: calling saveNumber(991) then getNumber() should return 991.
Instead, getNumber() returns 0.

Strangely, this code works correct on Remix. I therefore suspect the issue maybe in a truffle solidity configuration? Please advise if I should move this to truffle repo, thanks.

## Environment

- Compiler version: 0.8.11 Solidity
- Target EVM version (as per compiler settings): 0.8.11 Solidity
- Framework/IDE (e.g. Truffle or Remix): Truffle
- EVM execution environment / backend / blockchain client: truffle develop
- Operating system: Linux
- 0.8.11 Truffle,

## Steps to Reproduce

```solidity
uint256 public _myNumber = 0;

function saveNumber(uint256 num) public returns (uint256) {
  _myNumber = num;
  return _myNumber;
}

function getNumber() public view returns (uint256) {
  return _myNumber;
}
```

Using drizzle:

```
         <button
          onClick={async () =>
            { const tx = drizzle.contracts.SampleToken.methods.saveNumber("995");
              const result = await tx.call();
              console.log(result);
              }}>Save Number</button>

          <strong>My SampleToken Number </strong>
          <ContractData
            drizzle={drizzle}
            drizzleState={drizzleState}
            contract="SampleToken"
            method="getNumber"
            methodArgs={[]}
          />
```

**Comment by chriseth** [comment]
If it works on remix, it is very likely not a compiler issue. The reason might be that you use `tx.call()`, which I think is just meant for queries to the blockchain instead of actually performing an action. I think you need `tx.send()`.

**Comment by algorithmical** [comment]
> If it works on remix, it is very likely not a compiler issue. The reason might be that you use `tx.call()`, which I think is just meant for queries to the blockchain instead of actually performing an action. I think you need `tx.send()`.

Thank you
