### ISSUE TITLE
No uninitialized variables warnings

### ISSUE THREAD

**Issue by yaronvel** [ethereum/solidity#1269]
This code is compiling without any warnings:

```
    function debug_verifyShare( bytes coinBaseTxMiddle,
                          uint[] merkleBranch,
                          uint[] sibling,
                          bytes blockHeader,
                          uint  timestampIndex,
                          uint  steps ) constant returns (bool) {
        uint leaf = merkleBranch[ length - 1 ];
        uint length = merkleBranch.length;

        return leaf > 0;
    } 
```

I would expect warning message (not to mention error).

**Comment by axic** [comment]
Currently the scoping is designed this way (matches that of Javascript), read more at http://solidity.readthedocs.io/en/latest/control-structures.html?highlight=scoping#scoping-and-declarations.

I would agree that this isn't intuitive (unless someone understands Javascript deeply), see #219.

**Comment by yaronvel** [comment]
Regardless to the scope, warning for using uninitialized variables would be nice.
It almost always due to bug in the program.

**Comment by axic** [comment]
@yaronvel if you read the documentation, it states that there are no uninitialised variables, but implicitly set to the default value of the type (for numbers, that is 0).

In your example, the index will be `0 - 1`, which is a separate issue.

**Comment by yaronvel** [comment]
Ok, thanks.

**Comment by chriseth** [comment]
We plan to add some warnings about unused variables. Will close this one.
