### ISSUE TITLE
Internal JSON-RPC error on a private chain: `gas required exceeds allowance (8000000)`

### ISSUE THREAD

**Issue by msak222** [ethereum/solidity#12709]
Hello everyone, my smart contract runs normally on ganache and the public test network, but in the private chain built by myself, it always prompts gas required exceeds allowance (8000000)
![image](https://user-images.githubusercontent.com/19371846/155251228-0fa17307-44ca-40ff-8146-a2674c13ea3c.png)
source code：
![image](https://user-images.githubusercontent.com/19371846/155251254-9c50001d-a587-40c1-bd3f-6c07befd1f56.png)

**Comment by cameel** [comment]
This does not look like a problem in the compiler to me. Your contract probably just exceeds the gas limit you specified yourself in the transaction (i.e. 8000000 gas). What specifically makes you think it's a compiler bug?

By the way, please don't post code and errors as screenshots. This forces anyone who'd like to help you to retype all that code to reproduce your problem.

**Comment by chriseth** [comment]
Closing this as "not related to the compiler". If you think otherwise, please reopen.
