### ISSUE TITLE
`abi.encodeCall` does not properly convert the function type to an externally-called function

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#12718]
## Abstract

The following gives an error:

```solidity
pragma solidity 0.8.12;

contract Sender {
    function main(string memory helloworld) external {
        // TypeError: Cannot implicitly convert component at position 0 from "string" to "string".
        abi.encodeCall(IReceiver.methodName, (helloworld));
    }
}

interface IReceiver {
    function methodName(string calldata) external;
}
```

## Motivation

When encoding data for a call, it shouldn't really matter if it's calldata or memory. If the interface has calldata, but if the value that we want to pass is in memory, it triggers the typecheck error abi.encodeCall. 

## Specification

abi.encodeCall should not typecheck data location.

## Backwards Compatibility

This should not have any breakings.

**Comment by chriseth** [comment]
My first guess is that the function we encode to has not been properly converted to an external view, i.e. we have to convert the type to the same we convert when we perform an external call.

**Comment by ekpyron** [comment]
To be more precise: ``TypeChecker::typeCheckABIEncodeCallFunction`` should probably type-check the arguments on ``functionPointerType->asExternallyCallableFunction`` instead of the plain function type.

**Comment by cameel** [comment]
Just for reference since this is not included in the description. The error on 0.8.12 is:
```
Error: Cannot implicitly convert component at position 0 from "string" to "string".
 --> test.sol:6:46:
  |
6 |         abi.encodeCall(IReceiver.methodName, (helloworld));
  |                                              ^^^^^^^^^^^^
```

**EDIT**: Oh, just noticed that it's there but as a comment.

**Comment by cameel** [comment]
Similar failing cases:
### `storage` vs `calldata`
```solidity
interface I {
    function f(string calldata) external;
}

contract C {
    string s;
    function main() external view {
        abi.encodeCall(I.f, (s));
    }
}
```
```
Error: Cannot implicitly convert component at position 0 from "string" to "string".
 --> test.sol:8:29:
  |
8 |         abi.encodeCall(I.f, (s));
  |                             ^^^
```
Interestingly it does not fail if you change `calldata` to `memory` even though in that case types are still different.

### Function pointer
``` solidity
interface I {
    function f(function (string calldata) external) external;
}

contract C {
    function g(string calldata) external {}

    function main() external view {
        abi.encodeCall(I.f, (this.g));
    }
}
```
```
Error: Cannot implicitly convert component at position 0 from "function" to "function".
 --> test.sol:9:29:
  |
9 |         abi.encodeCall(I.f, (this.g));
  |                             ^^^^^^^^
```
This does not happen if you replace `calldata` with `memory`.

### ~`address payable`~
**EDIT**: This is one is also not implicitly convertible. It should be the other way around (`address` in the function and `payable` as argument) and in that case it compiles without errors. But again, the types listed in the error message should be more detailed because now it looks like they're identical.
```solidity
interface I {
    function f(address payable) external;
}

contract C {
    function main() external view {
        abi.encodeCall(I.f, (address(0)));
    }
}
```
```
Error: Cannot implicitly convert component at position 0 from "address" to "address".
 --> test.sol:7:29:
  |
7 |         abi.encodeCall(I.f, (address(0)));
  |                             ^^^^^^^^^^^^
```

**Comment by cameel** [comment]
I created a new issue to improve the types in the error message: #12776. They're not detailed enough which makes it harder to see what's wrong.

**Comment by cameel** [comment]
@ekpyron pointed out that the function call is a more general problem (not limited only to `abi.encodeCall()` so I reported it as a separate issue: #12778.

**Comment by Aivolt1** [comment]
Run command on cli
