### ISSUE TITLE
Use invalid locale instead of "C" to detect and fix any attempted locale-dependent operations in the codebase

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12720]
Requested in https://github.com/ethereum/solidity/pull/12716#issuecomment-1054141878.
Related to #12350.

> I would actually be happier if we could find a way to somehow set an "illegal" locale so that we get an error whenever we perform a locale-dependent operation (and of course remove all locale-dependent operations).

**Comment by cameel** [comment]
The docs for [`std::setlocale()`](https://en.cppreference.com/w/cpp/locale/setlocale) have a nice list of things that are affected by the global variable:
- `std::fprintf()`
- `std::fscanf()`
- `std::isalnum()`
- `std::isalpha()`
- `std::isblank()`
- `std::iscntrl()`
- `std::isdigit()`
- `std::isgraph()`
- `std::islower()`
- `std::isprint()`
- `std::ispunct()`
- `std::isspace()`
- `std::isupper()`
- `std::iswalnum()`
- `std::iswalpha()`
- `std::iswblank()`
- `std::iswcntrl()`
- `std::iswctype()`
- `std::iswdigit()`
- `std::iswgraph()`
- `std::iswlower()`
- `std::iswprint()`
- `std::iswpunct()`
- `std::iswspace()`
- `std::iswupper()`
- `std::iswxdigit()`
- `std::isxdigit()`
- `std::localeconv()`
- `std::mblen()`
- `std::mbstowcs()`
- `std::mbtowc()`
- `std::setlocale()`
- `std::strcoll()`
- `std::strerror()`
- `std::strtod()`
- `std::tolower()`
- `std::toupper()`
- `std::towlower()`
- `std::towupper()`
- `std::wcscoll()`
- `std::wcstod()`
- `std::wcstombs()`
- `std::wcsxfrm()`

**Comment by wechman** [comment]
@cameel I tried to run compilation with many different locales. The only failing scenario was the one with Turkey. I think, the locale change is not enough to identify all affected code pieces. We need also use non-trivial input file that involves the entire codebase. Another option could be to run all tests we have against several locales. Do you think it might work?

**Comment by cameel** [comment]
Have you tried to force `setlocale()` to use something that is not a real locale? @chriseth's idea was to do that so basically any use of these functions fails in some obvious way.

This way we'd find them all and replace them with locale-neutral alternatives. For example instead [`int toupper(int)`](https://en.cppreference.com/w/cpp/string/byte/toupper) from `<ctype>` we'd use [`charT toupper(charT, const locale&)`](https://en.cppreference.com/w/cpp/locale/toupper) from `<locale>` passing it the C locale explicitly.

> Another option could be to run all tests we have against several locales. Do you think it might work?

Not sure it's worth it. `soltest` runs in CI are already pretty heavy and we have quite a few of them. Locale is a corner case that I'd expect to work correctly once we get it right once so my minimal test should be enough to detect it. I even have doubts it my test isn't an overkill - it's an extra standalone job that will now run on every PR. Ideally I'd have it a a part of the CLI runs but I didn't want to add a dependency on the locale package to the CLI test script.

**Comment by wechman** [comment]
@cameel yes, I did and end up with "C" locale.
I am not surprised, since "setlocale" documentation says:

> If the function failed to set a new locale, this is not modified and a null pointer is returned.

I also tried to use not-existing environment locale or break locale environment configuration with: 

> export LC_ALL="invalid"
> dpkg-reconfigure locales

which leads to:

> locale -a
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_MESSAGES to default locale: No such file or directory
> locale: Cannot set LC_COLLATE to default locale: No such file or directory
> C
> C.UTF-8
> POSIX

In all the cases "C" was a locale in charge while solc execution.
