### ISSUE TITLE
Solidity Language Specification - Proposal

### ISSUE THREAD

**Issue by OmarTawfik** [ethereum/solidity#12739]
Hi, I'm Omar, and I working with @nomicfoundation, the team behind [Hardhat](https://hardhat.org/) and other Solidity developer tools. We recently announced [our long term plans](https://medium.com/nomic-foundation-blog/slang-rethnet-2ad465fd7880) to contribute to the Solidity Developer Experience, and as a first step, we, @nomicfoundation, want to make this proposal.

## Introduction

The Solidity language and compiler toolchain have evolved significantly since its inception in 2015. Rapid evolution and language updates to address emerging needs have incurred an expensive cost on the engineering teams that work on keeping up to date with new Solidity versions, while still providing support for old versions for existing contracts.

This issue is not new, has been discussed before ([example from 2016](https://github.com/ethereum/solidity/issues/717)), and we believe that this is only going to get more costly as the language evolves over time, and tool developers struggle to compile **informal technical specs**, **reverse engineer the compiler**, or rely on **incomplete third-party docs,** and **GitHub discussions**.

These challenges are **propagated to end-users of Solidity,** contract developers who struggle with knowing what are the correct tool versions to use, and how they interact with each other. This can lead to **frustration, build errors, and unspecified behavior**.

Here we talk about this problem in detail, mention its impact on the ecosystem, and one way we think can solve it. We believe building a standard versioned specification:

1. **Accelerates adoption of new language versions**, by making sure that tools adopt new changes rapidly, and with minimal effort.
2. **Evolves the ecosystem**, by making it easy to develop and ship new tools.

This **bridges the gap** between the compiler and downstream tools, and allows tools and **the entire ecosystem to evolve rapidly along with the language**. We believe **any effort we invest here is returned multiple times** for everyone working on tools in the Ethereum ecosystem.

In this document, we collected some instances of the problems around the lack of a language specification, particularly from the perspective of other tool developers, rather than focusing on the challenges we’ve faced building Hardhat. We’re hoping that by doing this we can build an objective perspective on the topic that’s not only based on our own specific experience.

We would love to have a discussion and get feedback from the Solidity team.

## Solidity evolves rapidly

The changes between versions are broad and touch many parts of the language. Here we list some examples, but this is just a subset. More examples can be found in [the docs](https://docs.soliditylang.org/), or the [changelogs](https://docs.soliditylang.org/en/v0.8.11/080-breaking-changes.html):

- Syntax changes:
    - New keywords like `try` and `catch` introduced in v0.6.0.
    - Keywords allowed in new locations, like top-level `struct` in v0.6.0.
    - Valid identifiers turned into keywords, like `gwei` in v0.7.0.
    - Operator associativity changed like exponentiation operator `**` in v0.8.0.
- Behavioral changes:
    - For example, v0.5.0 changed where `continue` jumps to in a loop.
    - It also prevents using `msg.value` in non-payable functions.
- Type System/API changes:
    - Methods change their implementation, return types, and parameters.
    - For example, v0.5.0 changed the return type of `call()` from a boolean to a tuple.
    - In v0.6.0, the function `push(value)` for dynamic storage arrays does not return the new length anymore (it returns nothing).
    - Global variables are deprecated, like `now` in v0.7.0.

## Impact on the Ecosystem

While [the official docs](https://docs.soliditylang.org/en/v0.8.10/) are a great starting point, it still has the following issues for external implementations:

- It is not a strict definition. It is meant to be user-facing to explain things from the user's point of view. It will often exclude important technical information about how tools should understand code.
- The docs focus on the latest language version, while a small changelog section documents a high-level list of the most user-impacting changes. That is not enough to accurately model the changes between them.
- Future version changes are only documented when it comes to [user-facing changes](https://docs.soliditylang.org/en/v0.8.11/080-breaking-changes.html), but not the internals of the compiler/underlying type-system.
- They don’t include specs for the built-in libraries (functions and variables), along with their changelog. Without it, it’s challenging to build reliable analyzers or type-aware editor features.

This issue is multiplied with every new version release since it is not easy or cheap to upgrade already deployed contracts to use the newer versions, so tools have to support all of them at the same time.

Without a versioned technical specification, it becomes **much harder to develop tools that read, analyze, and change contracts**. It becomes harder to share these tools and incrementally build on top of them. It compounds the issue for downstream tools, like formatters, linters, third party build systems, debuggers, and so on.

This also means that each tool has to **repeat the same investment, implementation effort, and even bugs** with each release, as each version update introduces more divergence in the ecosystem, that relies on best-guess effort to support them.

Here we list some of the examples of these issues and its impact on users:

### Duplicate Effort

Perhaps one glaring example is the syntax, where the compiler publishes [one grammar](https://github.com/ethereum/solidity/blob/develop/docs/grammar/SolidityParser.g4), the most popular VS Code extension uses a [second one](https://github.com/solidity-parser/antlr/blob/master/Solidity.g4), and third-party compilers [use other ones](https://github.com/hyperledger-labs/solang/blob/main/solang-parser/src/solidity.lalrpop), each with their implementation and output differences.

Another example is the ABI/compiler output; The Truffle team (cc @gnidan) previously proposed building a [formal spec](https://docs.google.com/document/d/1ZwpBCI0wvEnRqPw0BQow9EfQNy4agx-r_pS0Uh1EzEg) for debugging data format, and also worked on [building a reference](https://ethdebug.github.io/solidity-data-representation/) for the compiler binary output, to be used for debuggers.

### Inconsistencies between tools

When the exponentiation operator changed its associativity in v0.8.0, it broke formatting for tools like `prettier-plugin-solidity` (cc @fvictorio) and editors like VS Code, as it relied on the old rules to determine parenthesis around expressions. Such updates can produce subtle runtime bugs in user code, which can be incredibly hard to detect.

When function visibility stopped being required for constructors in v0.7.0, it broke a `solhint` linting rule (cc @fvictorio), as it couldn’t accurately recommend whether to add or remove the visibility. This can lead to their code being updated in a way that would produce compiler errors, specially with automatic fixes.

### Catching up to the compiler

Without clear information on changes between versions, and enough runway to support them before the official release, projects like [Truffle](https://trufflesuite.com/) (cc @gnidan) had to add a lot of last-minute conditionals in their codebase to work around version differences, sometimes after the features are already released, and users are affected. This leads to **delays in supporting new versions**, and increased implementation costs on their side to keep up.

Likewise for the [Etherscan](https://etherscan.io/) team (cc @Enigmatic331), a few enhancements introduced resulted in a contract's byte code being not as reproducible from a re-compilation, such as the introduction of the immutable keyword and introduction of different variants of metadata hashes over the years. To them, documenting and standardizing both versioning metadata and optimization settings in the byte code would help a great deal moving forward.

## What are other languages doing?

The C# language has solved this problem by maintaining a formal specification (that started with C# v6.0) as ECMA-334, and evolved over time by appending new sections with each version that describe the changes done.

- [https://github.com/dotnet/csharplang/tree/main/spec](https://github.com/dotnet/csharplang/tree/main/spec)

Each feature is described in detail, from the point of view of different tools, the parser, the type system, the runtime, and also any user-visible or runtime behavior updates. It also talks about how it is encoded into the output, and how it is represented in runtime reflection. Example:

- [https://github.com/dotnet/csharplang/blob/main/spec/attributes.md#attribute-specification](https://github.com/dotnet/csharplang/blob/main/spec/attributes.md#attribute-specification)

There is also a public database of all the standard types, methods, and properties that exist in .NET, where users can navigate and read detailed documentation, and how to use each of them. The database is also published in a machine readable format.

- [https://docs.microsoft.com/en-us/dotnet/api/?view=net-6.0](https://docs.microsoft.com/en-us/dotnet/api/?view=net-6.0)

They still maintain user-facing documentation of the language, that talks about language features from the user perspective:

- [https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/)

## What can we contribute to solving this?

One idea we have debated is implementing a formal technical specification, from the point of view of downstream tools, and not users. Such document can include (but not be limited to) the following topics:

1. **Language/Syntax**: information about each language construct, and how it is interpreted by the compiler, for each supported syntax (Solidity, Yul, inline assembly, others?)
2. **API/Semantics**: an index of any built-in types, functions (parameters and return types), variables, and libraries that are exposed in the language, its documentation, usage, and any implementation details/examples. This should be produced both as a user-facing wiki, and in machine-readable format for tools.
3. **ABI/Code Generation**: detailed form and format of the compiler output, how each language construct is lowered, and how downstream tools should interpret this output (supported output formats and targets).

Each section should be able to note (in-context) any version-specific changes, so that tool developers can have a holistic view of each feature, and how to properly support it across different versions.

The language team can probably chime in on other parts that they think would be helpful to be included here.

## How can we achieve this?

We realize that this is not a trivial task to produce such a spec. **We would love to contribute**, by starting with the existing language versions, and what changed between them, since it would be the most impactful to existing tools.

We propose to author, iterate on, and open source such a spec, and publish it in both a public user-facing format (similar to the official docs) and a machine-readable format as well. We hope rapid iteration and community feedback can allow us to achieve an end result that can be shared and standardized across the ecosystem and language tools.

However, we would love to ask for the Solidity team’s feedback and guidance as we work on this, particularly:

- Reviewing our updates, to make sure they are **accurate, up to date, and covering all needed grounds**.
- Externalizing any **internal or undocumented information** they think might be helpful to the community to include in the spec.
- Discussing how this can **benefit the Solidity team** in their own development/planning.
- Weighing in on **future discussions**, as they are the official and most reliable source of truth for any future updates.

## Final Thoughts

We believe having this leads to **a consistent ecosystem**, where **new versions are released along with support from downstream tools,** and leads to a **fantastic user experience** where users can have confidence in their tools doing the right thing.

**Comment by alcuadrado** [comment]
By the way, @OmarTawfik is part of Nomic and is working on our Solidity compiler project. He worked on the C# and F# compilers at Microsoft, and can provide more light on how these things are handled in languages at that scale, if that's useful!

**Comment by alcuadrado** [comment]
Tagging more people that built/maintain tools that can benefit from a Solidity spec: @gakonst @iamdefinitelyahuman @fubuloubu @cgewecke @krzkaczor @fubhy @frangio

**Comment by chriseth** [comment]
I think this could be useful. We should probably have a talk about the details and to check that we are actually talking about the same thing.

**Comment by alcuadrado** [comment]
I'll contact you on private to schedule a call

**Comment by GregTheGreek** [comment]
Great start!

instead of closed door calls can we try and setup something with a larger scope, make an agenda, have someone moderate etc. I know a few parties who care about this topic that are not listed in the above !

**Comment by medmin** [comment]
> I'll contact you on private to schedule a call

Maybe you can host a twitter space and everyone can participate ?

**Comment by chriseth** [comment]
I'm all for open calls!
Just as a reminder, all the solidity design and team calls are open to the public, just in case anyone wants to voice their opinion on something: https://docs.soliditylang.org/en/latest/contributing.html#team-calls

Oh and if we want the wider society to stop making fun of us, we should at least use something like jitsi instead of twitter.

**Comment by OmarTawfik** [comment]
We can use the same format then. I think having input from developers who work on Solidity tooling is important to make sure we get this right.

**Comment by alcuadrado** [comment]
Let's do an open call.

Here's a doodle with three different possible times for the call: https://doodle.com/meeting/participate/id/rb2AMjWa

Can you please vote for the ones that work for you, @OmarTawfik, @chriseth, @GregTheGreek, @medmin, and other people interested in joining? Please do it before Monday. If none of them work for you let me know.

We can definitely use jitsi.

**Comment by chriseth** [comment]
Which time zones are we actually in? I can make some of the suggested times, but they are out of my usual office hours.
I created a hackmd where we can gather some more information: https://notes.ethereum.org/@chriseth/SJTZ7jDb9/edit

**Comment by GregTheGreek** [comment]
I can't edit the hackmd, but im in EST but extremely flexible. This is an important discussion

**Comment by chriseth** [comment]
So shall we find a date together? Tomorrow would be ok for me, I would just prefer at least one hour earlier. 
I re-checked again and it seems the hackmd is indeed publicly editable, not sure what the problem is for you, @GregTheGreek

**Comment by GregTheGreek** [comment]
I'm unable to login since I'm not a memeber of the Ethereum org

**Comment by chriseth** [comment]
You should be able to edit it without logging in.

**Comment by alcuadrado** [comment]
I'm fine with scheduling this way. I believe we have people in timezones ranging from the west coast of the states (@OmarTawfik), to Europe, so some of us will need to be a bit flexible. I have no problem with that and will make whatever gets chosen work for me.

**Comment by OmarTawfik** [comment]
MAR 16 WED (12:00 PM PST) seems to be the most voted option, so let's use that. Happy to reschedule if there are any hard conflicts. If so, please add your vote [to the doodle](https://doodle.com/meeting/participate/id/rb2AMjWa).

**Comment by chriseth** [comment]
From what I can see in the hackmd, we can do the meeting at least two hours earlier than the options given in the doodle. Would that work for everyone?

16th of March 1600 GMT? This should be 0900 PST and 1700 CET

**Comment by alcuadrado** [comment]
That works! I just created a Calendar event and invited most people here (i.e. the ones I know their emails). For anyone who didn't receive the invite, here's the jitsi link: https://meet.jit.si/SoliditySpecInitialDiscussion

**Comment by alcuadrado** [comment]
Thanks everyone for joining the call! It went really well, and we are excited about this.

[Here](https://nomiclabs.notion.site/shared-notes-Solidity-Spec-Initial-discussion-de1a09f1a9874ca284a4f55c356810bb) are my notes. You should have permission to comment, so let me know if something is wrong/missing.

**Comment by OmarTawfik** [comment]
Thanks all for attending. I really appreciate you making the time. I'm excited for the future of this!

**Comment by chaals** [comment]
Thank you all for raising this and especially @alcuadrado for the notes of the meeting (nobody can attend all meetings, so have a written trail to follow is really important to improve the future).

I'm wondering where this is at now. 

My specific use case is being able to find out what things are slated for deprecation when they are - which I haven't so far been able to glean from going through documentation or release blogs. I'm not sure that's directly in the scope of the spec project, but it seems like a repo for that project **might** have a clear way to extract the info, like looking for a relevant issue label.

**Comment by OmarTawfik** [comment]
@chaals this is in progress now, and we have a cross-version grammar, and working on adding technical information for the Solidity syntax. We are collecting breaking changes across all older versions, and planning to announce progress/a preview once it is complete.

However, I'm not sure if the Solidity team has published information on future plans (around deprecation), so I can leave that question for the Solidity team. I think having this information is valuable in the spec too!

**Comment by NunoFilipeSantos** [comment]
Hi @OmarTawfik! 👋 I'm Nuno the new TPM for the Solidity team and I would love to know if you have an update regarding this issue since May?

Is there anything we can help you with here?

**Comment by chaals** [comment]
Hi @NunoFilipeSantos - thanks for bumping this. @OmarTawfik I'm potentially interested in helping out here as I know there is a lot of work. I've edited W3C specs including the versioned HTML 5.x series, as well as EEA specs.

As well as the fact that there needs to be a proper changelog between versions, I think it would be helpful to build it and make it available as the changes are under discussion, as an editors' draft.

**Comment by OmarTawfik** [comment]
Hi all. Glad to see the Solidity team growing!

So far, we have focused on the syntax/grammar spec, and we are working next on cross-version testing for a large number of open source/publicly available contracts, to make sure our current multi-version grammar is correct, and we captured everything. It is not done yet, but we are making good progress, and we are looking next into publishing the grammar in both machine and human readable formats.

I'm happy to meet/have a quick chat about this if you are interested. Would love to see if you have any recommendations/concerns about this work, or the Language Design Process, or if you have thoughts about how breaking changes and features can be specified, discussed, and released in the future.

**Comment by nishant-sachdeva** [comment]
Here's a paper from 2020 that seems to have attempted to create formal semantics for solidity.

https://ieeexplore.ieee.org/document/9152785

**Comment by OmarTawfik** [comment]
Hi all. I'm really excited to share some updates about our work in the last few months. Please read more on the official announcement here:

- https://medium.com/nomic-foundation-blog/slang-alpha-release-6d322cf986a3

In addition to what is mentioned there, we are working on publishing both a Grammar and a Language reference, covering 74 Solidity releases from `0.4.11` to `0.8.19`:

- https://nomicfoundation.github.io/slang/solidity-specification/supported-versions/
- https://nomicfoundation.github.io/slang/solidity-specification/grammar/
- https://nomicfoundation.github.io/slang/solidity-specification/reference/

We will be working on adding its content and improving the language reference over time. Contributions and suggestions are very much welcomed!
