### ISSUE TITLE
Remove  "using namespace util" directive from ASTAnnotations.h

### ISSUE THREAD

**Issue by wechman** [ethereum/solidity#12743]
Because header inclusion can be very deeply nested, "using namespace" directive located in header files can unexpectedly change the meaning of the code. It can also lead to the name collision. For instance, it is not possible to define isDigit function in CommonSyntaxTest.cpp.

TODO:
1) Remove [using namespace util;](https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/ASTAnnotations.h#L50)
2) Update [CommonSyntaxTest.cpp](https://github.com/ethereum/solidity/blob/develop/test/CommonSyntaxTest.cpp) so it has only one local definition of  "isDigit" function (can be addressed after #12740 merge).

**Comment by YashAtwal** [comment]
I'd like to fix this issue

**Comment by tfire** [comment]
Resolved

**Comment by cameel** [comment]
So is the `isDigit()` thing resolved? Can we close this?

**Comment by tylerfxn** [comment]
Yes, resolved @cameel
