### ISSUE TITLE
Add test suite for libevmasm (and the optimiser)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1275]
This should have test cases written assembly, testing also the special codes for codesize, .data sections, etc.

Certain optimisations could be tested also, especially once #887 is implemented.

**Comment by chriseth** [comment]
There already are some tests for the optimizer, but yes, the suite could be extended. The problem is that those tests are hard to get stable.

**Comment by axic** [comment]
Peephole optimiser tests would be stable enough (assuming the tests address single optimisation cases and maybe some combined ones).

**Comment by chriseth** [comment]
Indeed, but we do not have such an optimizer yet.

**Comment by axic** [comment]
This was achieved, we do have tests for the optimiser, including the peephole. It can always be improved though.
