### ISSUE TITLE
Take termination into account in data flow analyzer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#12755]
```
{
    let _1 := memoryguard(0x80)
    mstore(64, _1)
    let _2 := 0
    switch shr(224, calldataload(_2))
    case 0x06661abd {
        mstore(_1, sload(_2))
        return(_1, 32)
    }
    case 0xc2985578 {
        return(mload(64), _2)
    }
}
// ----
// step: fullSuite
//
// {
//     {
//         let _1 := memoryguard(0x80)
//         mstore(64, _1)
//         switch shr(224, calldataload(0))
//         case 0x06661abd {
//             mstore(_1, sload(0))
//             return(_1, 32)
//         }
//         case 0xc2985578 { return(mload(64), 0) }
//     }
// }
```

The mload at the end should be replaced by `_1`, but somehow it is not. The `mstore` in the first swich case seems to destroy it.

Similar example:
```
let x := 1
if calldataload(0) {
  x := 8
  revert(0, 0)
}
mstore(0, x)
```
The DataFlowAnalyzer will not be aware of the value of x in the last statement. It should take into account if a branching control-flow terminates or not before it clears knowledge of local variables and storage / memory.

**Comment by ekpyron** [comment]
There is a comment with ``// This is a little too destructive, we could retain the old values.`` in the switch case of the ``DataFlowAnalyzer``... that's probably it... ``clearKnowledgeIfInvalidated(_case.body)`` will clear all knowledge about memory, if the first case has any memory side effects...

**Comment by chriseth** [comment]
This is really interesting, I was not aware that it is so limited. For direct mstore / sstore operations, it takes into account if the location is overlapping or not - have to think this through again...

**Comment by ekpyron** [comment]
For reference: The [improvedDataFlow](https://github.com/ethereum/solidity/tree/improvedDataFlow) branch stemming from https://github.com/ethereum/solidity/pull/12769 contained some preliminary work towards this.
