### ISSUE TITLE
Make `solc --link` not modify the input file in place

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12777]
## Abstract
`solc --link` is the only input mode that modifies input files in place. In all the other modes the compiler prints to stdout by default and only writes to files when the `--output-dir` option is used. I think that the `--link` option should be changed to behave like the other input modes.

## Motivation
The way it works currently, apart from just being inconsistent, is one of the reasons why we do not have any tests covering it - our command-line test framework is not suited for testing the output written to a file. Especially when the output overwrites the input file.

## Specification
- By default `--link` should print to stdout.
- When `--output-dir` is used, the output should go to a file in the output directory. The name of the file should match the input file. The expected file extension is `.bin` but we don't enforce or change that, even if the input file has a different extension.
- Add some command-line tests covering this input mode
- Add a test for this input mode in [`test/solc/CommandLineParser.cpp`](https://github.com/ethereum/solidity/blob/develop/test/solc/CommandLineParser.cpp), similarly to how other modes are covered. The test should simply use as many command-line flags as possible and make sure the resulting `CommandLineOptions` object looks like it should.

## Backwards Compatibility
The change is not backwards compatible.

**Comment by chriseth** [comment]
Before we change this, we should ask if people use it like that. I think it could be rather annoying to change the behaviour if you use it like that.

**Comment by cameel** [comment]
Well, currently you have no other choice. It's the only way to use it (we don't support this via Standard JSON). So it's more of a question of whether people use it at all.

Even if they do use it, I think that for manual use this will actually be more intuitive (I was a bit surprised by this when I tried to use it for the first time) and for scripted usage we should just add this to Standard JSON.

**Comment by Darksinian** [comment]
I am happy to work on this issue.

**Comment by cameel** [comment]
@MohamedAlaa201 We still need to decide if we want to do this. This is way it's labeled `good first issue candidate` and not `good first issue`.
