### ISSUE TITLE
Cannot import shadowed functions in Solidity 0.8.12

### ISSUE THREAD

**Issue by cleanunicorn** [ethereum/solidity#12780]
## Description

Importing overloaded methods in Solidity 0.8.12 gives an error instead of loading the methods, even if the methods are not called.

Other info that might be relevant:
- Checking the Solidity change list I found something that *might* be relevant
> Inheritance: Consider functions in all ancestors during override analysis.

- @chriseth once said that Solidity performs conflict resolution when the method is called. However, this doesn't seem to be the case anymore.
https://github.com/ethereum/solidity/issues/12296#issuecomment-971705133

## Environment

- Compiler version: 0.8.12
- Target EVM version (as per compiler settings): compiler default (but happens with all versions)
- Framework/IDE (e.g. Truffle or Remix): Remix, but happens everywhere
- EVM execution environment / backend / blockchain client: any
- Operating system: any

## Steps to Reproduce

Consider these 2 files created in Remix IDE

- `Math.sol` - defines 2 methods, same name, different arguments

```solidity
function sub(uint256 x, uint256 y) pure {}
function sub(uint256 x, int256 y) pure {}
```

- `ImportMath.sol` - just tries to import the `sub` method 

```solidity
import {sub} from "./Math.sol";
```

Output error on compilation:

```
TypeError: No matching declaration found after variable lookup.
 --> ImportMath.sol:1:9:
  |
1 | import {sub} from "./Math.sol";
  |         ^^^
```

That means I don't know how to import those methods.

**Comment by chriseth** [comment]
So how do we fix it? Just not perform overload resolution if the reference is inside an import statement?

**Comment by ekpyron** [comment]
We didn't do it before 0.8.12, so we should just keep not doing it, yes.
