### ISSUE TITLE
Yul Optimzer : "Variable count for assignment to "z" does not match number of values (1 vs. 0).

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#12794]
## Description

Hello everyone,

I hope you are all well.
Shouldn't the contract below be compiled?
```
contract C {
    uint120[] data;
    function f() public returns (uint120 x, uint120 y, uint120 z) {
        data.push(123);
        data.push(234);
        data.push(345);
        assembly {
	    x := mload(mload(data.offset))
	    y := sload(sload(data.offset))
            z := mstore(data.offset, 3)
        }
	delete data;
        return (x, y, z);
    }
}
```
Instead it "Variable count for assignment to "z" does not match number of values (1 vs. 0).

## Environment

- Compiler version: 0.8.12
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: ubunt 18.04

**Comment by chriseth** [comment]
I guess the problem is that `mstore` does not return anything.

Apart from that, you are using storage pointers for memory, which will lead to undefined behaviour.

Questions like this are better asked on the matrix / gitter chat room because you will get faster and better responses there.
