### ISSUE TITLE
mapping getters don't return structs with arrays correctly

### ISSUE THREAD

**Issue by ramgos** [ethereum/solidity#12792]
Whenever there is a mapping from some type to a struct, and the struct contains a dynamic array - calling the getter of the mapping doesn't show the array's values

Compiler version: 0.8.12 (tested also 0.8.7 and 0.8.3)
Target EVM version: london
Framework/IDE: Remix, also reproduced on hardhat ethers
EVM execution environment: javascript VM
Operating system: Linux

example:

```solidity
pragma solidity ^0.8.0;

contract Contract {
    struct Struct {
        address sender;
        uint256[] numbers;
    }

    mapping(uint256 => Struct) public structs;

    function setValue(uint256 _index, uint256[] memory _array) external {
        structs[_index] = Struct(msg.sender, _array);
    }

    function getStruct(uint256 _index) external view returns(Struct memory) {
        return structs[_index];
    }
}
```
After `setValue(0, [1, 2, 3])`, calling `getStruct(0)` returns both the sender and numbers array, but `strcuts(0)` returns only the sender
This is also confirmed by the ABI definitions:
structs:
```
	"inputs": [
		{
			"internalType": "uint256",
			"name": "",
			"type": "uint256"
		}
	],
	"name": "structs",
	"outputs": [
		{
			"internalType": "address",
			"name": "sender",
			"type": "address"
		}
	],
	"stateMutability": "view",
	"type": "function"
```

getStruct:
```
			"inputs": [
				{
					"internalType": "uint256",
					"name": "_index",
					"type": "uint256"
				}
			],
			"name": "getStruct",
			"outputs": [
				{
					"components": [
						{
							"internalType": "address",
							"name": "sender",
							"type": "address"
						},
						{
							"internalType": "uint256[]",
							"name": "numbers",
							"type": "uint256[]"
						}
					],
					"internalType": "struct Contract.Struct",
					"name": "",
					"type": "tuple"
				}
			],
			"stateMutability": "view",
			"type": "function"
```

for the meanwhile, how can I bypass this? I tried calculating the mapping storage slot myself based on the docs, with no success. here is my function:
```
const keySlot = (mappingSlot, key) => {
    return keccak256(concat([zeroPad(key, 32), mappingSlot]));
};
```

**Comment by chriseth** [comment]
This is on purpose. Arrays are not returned by value from getters. Instead index access is provided for them. Since it is not possible for structs, we decided to drop these arrays. Unfortunately, you have to implement your own getter function if you want this functionality.

**Comment by sebastiantf** [comment]
Just noticed similar behavior for an array instead of mapping:
```diff
- mapping(uint256 => Struct) public structs;
+ Struct[] public structs;
```
Works as expected with an explicit getter function. But how/why is that different from the automatic getter function generated by the compiler for the public array/mapping? Aren't they the same essentially?

**Comment by cameel** [comment]
The compiler tries to avoid generating getters that will return big amounts of data in one go and be very expensive (maybe even unusable). When you define your own getter, it's still a problem but it's up to you to decide what to do about that, the compiler won't stop you there.
