### ISSUE TITLE
Requesting ability to define modifiers in Solidity libraries and use them in contracts

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#12807]
## Abstract

It would be useful if people could define modifiers in Solidity libraries and be able to import and use them in contracts.

## Motivation

It has been found by myself and others that it is possible to write clean code by writing internal functions in Solidity libraries and then importing those libraries into contracts and using them.

This can be a good way to write code because it can make it more clear where internal functions come from because once a library is imported the name of the library can be used when calling the functions in the library.  This makes it clear and explicit what and where internal functions come from when they are called.

However this style does not work with modifiers because it is currently not possible to define modifiers in Solidity libraries.

## Specification

It would be great if it was possible to define modifiers in Solidity libraries so they can be imported and used in contracts.

Note that with diamond storage people could access the state variables of contracts in modifiers written in Solidity libraries. 

Also note that a primary developer of OpenZeppelin recently said [that they plan to adopt Diamond Storage in the next major version of OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2964#issuecomment-1068278307).

**Comment by chriseth** [comment]
The main reason I did not yet consider to allow defining modifiers outside the current contract is that I don't see them to be useful because most of the time you would access at least a state variable of the contract. Can you provide some code examples where this is useful?

**Comment by mudgen** [comment]
@chriseth Yes, of course. Currently `storage` parameters can be defined on modifiers and state variables can be passed to modifiers as arguments. I would think the same thing could be done with modifiers defined in libraries.

But also, there is a growing use of Solidity libraries using Diamond Storage to access state variables of contracts directly, and modifiers in Solidity libraries could do this as well.

You see, Solidity libraries can be created to define state variables and internal functions that modify those state variables. Then it would be good to be able to define modifiers in the same libraries to control access to those state variables.

Here's an example of a small library that controls access to the ownership of a contract or diamond. A contract or diamond could use this library to easily implement contract ownership functionality.  Currently I can define the `onlyOwner` modifier in the library but I can't use it in a contract.

```Solidity
// SPDX-License-Identifier: MIT


pragma solidity 0.8.11;
    
library ContractOwnerLib {

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    bytes32 constant DIAMOND_STORAGE_POSITION = keccak256("diamond.standard.diamond.storage.myproject.contractowner");

    struct DiamondStorage {
        address contractOwner;
    }

    function diamondStorage() internal pure returns (DiamondStorage storage ds) {
        bytes32 position = DIAMOND_STORAGE_POSITION;
        assembly {
            ds.slot := position
        }
    }

    function setContractOwner(address _newOwner) internal {
        DiamondStorage storage ds = diamondStorage();
        emit OwnershipTransferred(ds.contractOwner, _newOwner);        
        ds.contractOwner = _newOwner;        
    }

    function contractOwner() internal view returns (address contractOwner_) {
        contractOwner_ = diamondStorage().contractOwner;
    }

    function enforceIsContractOwner() internal view {
        require(msg.sender == diamondStorage().contractOwner, "LibDiamond: Must be contract owner");
    }
    
    modifier onlyOwner() {
       enforceIsContractOwner();
       _;
   }      
}
```

I made a work around which is using a `Modifiers` contract that just holds modifiers and contracts inherit that.  But it would be cleaner/nicer to use modifiers from the Solidity libraries that are being used.

Here are links to the source code from different authors for just a few contracts I found that are using Diamond Storage that would or might benefit from modifiers defined in libraries:

An Aavegotchi Facet:
https://github.com/aavegotchi/aavegotchi-contracts/blob/master/contracts/Aavegotchi/facets/ItemsFacet.sol

A BeanStalk Facet:
https://github.com/BeanstalkFarms/Beanstalk/blob/master/protocol/contracts/farm/facets/ClaimFacet.sol

From 0xHashstack:
https://github.com/0xHashstack/Open-contracts/blob/release-v0.1.2/contracts/Comptroller.sol

**Comment by mudgen** [comment]
@chriseth more projects are using diamond storage in Solidity libraries which makes modifiers defined in Solidity libraries and used in contracts useful.

**Comment by decafboba** [comment]
Modifiers in Libraries would be super useful and help to tidy up our code, would love to see this functionality supported!

**Comment by friskyfoxdk** [comment]
Adding my vote for this as well, it would be useful even in instances where there is no state, like checking if the caller is a smart contract or not.

**Comment by mudgen** [comment]
@chriseth @cameel What is the status of this?  More and more developers are using diamond storage which makes modifiers in Solidity libraries useful. 

I basically provide technical support for people who are using EIP-2535 and it comes up that they can't use modifiers in Solidity libraries. It is a language addition that would help Solidity developers.

**Comment by ItsNickBarry** [comment]
Seems reasonable.

**Comment by pimhakkert** [comment]
+1 on adding this. It results in cleaner code when using EIP-2535 and other upgradable contract standards. (not limited to)

**Comment by zdenham** [comment]
+1 to modifiers (and events would be great too, but that may be a different discussion)

**Comment by pimhakkert** [comment]
I'd like to bump this to your attention @chriseth
