### ISSUE TITLE
Satoshi Nakamoto candidate

### ISSUE THREAD

**Issue by sahil5d** [ethereum/solidity#12817]
This Paypal cofounder is likely Satoshi Nakamoto, based on common

- technical capability
- psychological motivation
- time availability plausibility
- physical location coincidence
- software stylistic similarity
- technical jargon similarity
- unusual and quirky expressions similarity.

https://medium.com/p/4120f36da702

**Comment by cameel** [comment]
In what way is this relevant to Solidity compiler?

This looks like spam. Closing.
