### ISSUE TITLE
`require` statement does not emit the given error-message

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#12819]
## Description

I believe that this is a bug in the compiler, in which, under very specific circumstances, a `require` statement does not emit the given error-message.

## Environment

- Compiler version: 0.8.12 (optimizer-runs: 20000)
- Target EVM version (as per compiler settings): Ganache 7.0.1
- Framework/IDE (e.g. Truffle or Remix): Truffle 5.4.33
- Operating system: MacOS

## Steps to Reproduce

```solidity
contract MyContract {
    struct Set {
        address[] _values;
        mapping(address => uint256) _indexes;
    }

    Set private addressSet;

    function test(address[] calldata addresses) external {
        for (uint256 i = 0; i < addresses.length; i++)
            require(add(addresses[i]), "already exists");
    }

    function add(address value) internal returns (bool) {
        return _add(addressSet, value);
    }

    function _add(Set storage set, address value) private returns (bool) {
        if (set._indexes[value] == 0) {
            set._values.push(value);
            set._indexes[value] = set._values.length;
            return true;
        } else {
            return false;
        }
    }
}
```
When function `test(addresses)` is executed with an address which has already been passed to it in a previous execution, it should revert with an error-message `"already exists"`.

Indeed, this error-message is emitted when we do so in two different transactions:
```
await myContract.test([ADDRESS1, ADDRESS2]);
await myContract.test([ADDRESS1, ADDRESS2]); // reverts with `already exists`
```
However, when we do so in a single transaction:
```
await myContract.test([ADDRESS1, ADDRESS1]);
```
The transaction reverts with `exited with an error (status 0) after consuming all gas`.
I suppose that this error-message is a Truffle and/or Ganache implementation detail, so theoretically, the bug is there and not in the compiler.

However, each one of the following observations leads me to believe that this is in fact a compiler issue:
1. The correct error-message is emitted if we change the input type from a dynamic array `address[] calldata addresses` to a static array `address[2] calldata addresses`.
2. The correct error-message is emitted if we "merge" function `_add` into function `add`, as if some different "stack behavior" took place during runtime, and somehow made this work correctly. I would tend to relate this to the passing by reference of variable `addressSet` from function `add` to function `_add`, but using this variable in function `_add` directly (i.e., not via the reference input variable) results with the same (wrong) error-message.

Please find below the full Truffle test:
```
const MyContract = artifacts.require("MyContract");

const ADDRESS1 = "0x1234567812345678123456781234567812345678";
const ADDRESS2 = "0x8765432187654321876543218765432187654321";

async function assertRevert(promise, message) {
    try {
        await promise;
        throw null;
    }
    catch (error) {
        assert(error, "Expected an error but did not get one");
        assert(error.message.includes(message), `Expected an error with '${message}' but got '${error.message}' instead`);
    }
}

contract("MyContract", (accounts) => {
    let myContract;

    beforeEach(async () => {
        myContract = await MyContract.new();
    });

    it("revert in the 2nd transaction", async () => {
        await myContract.test([ADDRESS1, ADDRESS2]);
        await assertRevert(myContract.test([ADDRESS1, ADDRESS2]), "already exists");
    });

    it("revert in the 1st transaction", async () => {
        await assertRevert(myContract.test([ADDRESS1, ADDRESS1]), "already exists");
    });
});
```
All of the above seems to hold also when `optimizer-runs = 200`, and even when `optimizer-enabled = false`), so this is probably not a compiler optimization issue.

**Comment by cameel** [comment]
I did a quick test in Remix by adding this function and the code reverts properly:
```solidity
    function testTest() public {
        address[] memory addresses = new address[](2);
        addresses[0] = 0x1234567890123456789012345678901234567890;
        addresses[1] = addresses[0];
        this.test(addresses);
    }
```

So I think it's likely either a bug in how Truffle encodes parameters for the call or a problem in the test itself.

Before we dig deeper - can you make sure your test is correct? One thing that stands out to me is that you do not use `await` with `myContract.test()` when you use it in combination with ` assertRevert()`. Are you sure it will wait for the promise to be resolved? I've been bitten by this in the past when I was using Hardhat with Waffle matchers. Something like this:
```typescript
await expect(contract.foo()).to.changeEtherBalances([a, b, c], [x, y, z]);
```
would not fail even when balances did not match, as long as there was more than one balance to compare. In the end I traced it to the fact that it must be `await expect(await contract.foo())` to work. On he other hand I did not have to do this with `to.be.reverted` so it's a bit inconsistent. There could be a similar problem here, just with Truffle's helpers.

**Comment by barakman** [comment]
Hi @cameel ,thank you for your quick response :)

A few notes:
1. That doesn't look like the same scenario though, because your test code is onchain, while mine is offchain.

2. The `assertRevert` function is part of my test, so you can see exactly what it looks like (i.e., no hidden unknowns here); I can replace my call to this function with a `try/catch` clause, the result would be the same.

3. True, the problem could be in Truffle and/or Ganache, but like I said, a simple thing like changing the input array type from `address[]` to `address[2]` makes this problem "disappear", so my "gut feeling" is that this is a compiler issue; But I will post it on Truffle's GitHub just in case.

Thanks again.

**Comment by haltman-at** [comment]
So I commented on this over on the Truffle issue, but I took a look and as best I can tell, there is no compile error; rather, the reason there's an out of gas message instead of the expected revert string is because the transaction does in fact run out of gas before it hits the revert.

**Comment by cameel** [comment]
> That doesn't look like the same scenario though, because your test code is onchain, while mine is offchain.

That's the point. As long as we're considering a bug in the compiler not the underlying EVM it should not matter. An external call from the contract and one via a transaction should result in the same exact code being executed. My example shows that the contract does revert with properly encoded input so the problem must be elsewhere. Unless there are two perfectly synced bugs - one in ABI encoding in the calling contract **and** another in the contract code that decodes and uses it but that seems much less likely to me. We should explore the simpler possibilities first.

> The `assertRevert` function is part of my test, so you can see exactly what it looks like (i.e., no hidden unknowns here); I can replace my call to this function with a `try/catch` clause, the result would be the same.

But have you tried adding the second `await` as I suggested?

> True, the problem could be in Truffle and/or Ganache, but like I said, a simple thing like changing the input array type from `address[]` to `address[2]` makes this problem "disappear", so my "gut feeling" is that this is a compiler issue; But I will post it on Truffle's GitHub just in case.

Dynamic and static arrays are encoded very differently so it might also just indicate a client-side issue with ABI encoding.

I mean, I understand what happens with this data when you pass it to an external call in a contract. On the other hand the layers it goes through between the time you pass it to `assertRevert()` and the time it appears in the contract are unfortunately a black box to me.

**Comment by cameel** [comment]
@haltman-at After reading the other thread I see what you meant. Ok, so this indeed looks like a client-side problem, just a different one I was expecting.

@barakman I'm going to close this in that case. Please feel free to reopen if it turns out that there's something wrong on the compiler side after all.
