### ISSUE TITLE
Wrong documentation for CREATE2 address computation

### ISSUE THREAD

**Issue by hroussille** [ethereum/solidity#12811]
## Page

[This](https://docs.soliditylang.org/en/v0.8.13/control-structures.html#salted-contract-creations-create2) is the page where there is the issue.

## Abstract

The documentation explaining the behavior of salted contract creations / create2 is wrong and misleading since it relies on a special case :

The example code : 

```solidity
 keccak256(abi.encodePacked(type(D).creationCode, arg)
```

Implies that arguments are encoded with `abi.encodePacked` which produces the good output in that case since the `arg` argument is a uint variable and `abi.encodePacked(arg)` == `abi.encode(arg)` however, for any type that is not natively 32 bytes the computed address is wrong. 

It should be : 

```solidity
 keccak256(abi.encodePacked(type(D).creationCode, abi.encode(arg))
```
Which always outputs the correct value independent of the size of the underlying type of `arg` or combination of heterogeneous parameters.  ~~Additionally, a mention in the text explanation that the arguments should be abi encoded would clarify the computation and be coherent with the way parameters encoding actually works as described [here](https://docs.soliditylang.org/en/v0.8.13/abi-spec.html#contract-abi-specification).~~

## Pull request

[This](https://github.com/ethereum/solidity/pull/12810) is the link to my pull request with the aforementioned documentation modifications.

**Comment by hrkrshnn** [comment]
Fixed in https://github.com/ethereum/solidity/pull/12810
