### ISSUE TITLE
constant lookup tables or datacopy in Solidity

### ISSUE THREAD

**Issue by recmo** [ethereum/solidity#12821]
## Abstract

On several occasions I wished I could write lookup tables like so

```solidity
uint256[256] constant lookup = [1,2,3,4, /* data */];

function lookup_demo(int256 x) internal pure returns (int256 r) {
    assert(x < 256);
    r = lookup[x];
} 
```

The expected behaviour here is for solc to compile this down to a Yul `data` object and a `datacopy` to scratch followed by and 1mload`, which in turn results in an EVM `codecopy + mload` instruction. Unfortunately instead I get

```
TypeError: Type uint8[256] memory is not implicitly convertible to expected type uint256[256] memory.
```

## Motivation

I am not aware of an alternative with the same constant gas cost. It also appears I am not the only one looking for such a feature (see [this](https://ethereum.stackexchange.com/questions/51415/how-do-i-make-an-efficient-lookup-table) stackoverflow question).

## Specification

Possible solutions for lookup table in order of my personal preference:

1. Allow use of `data` objects and `datacopy` in inline assembly.
2. Support `code` as a full fledged read-only address space alongside `memory` and `storage`.
3. A language feature that allows for constant plain arrays using data objects and datacopy as in example code above.
4. Allow use of `verbatim_*_*` in inline assembly (some hacks using `PC` can make it work).

## Backwards Compatibility

Should be no concerns.

**Comment by recmo** [comment]
One currently available workaround (while still O(n)) is the stackoverflow suggestion:

```solidity
bytes constant lookup = hex"/* data */";

function lookup_demo(int256 x) internal pure returns (int256 r) {
    assert(x < 256);
    bytes memory copy = lookup;
    assembly {
        r := mload(add(copy, shl(add(x, 1), 5)))
    }
}
```

**Comment by recmo** [comment]
Another current available workaround (which is technically O(log n) but with a big factor) is a big ugly binary tree of branches:

```solidity
function lookup_demo(int256 x) internal pure returns (int256 r) {
    assert(x < 256);
    if (x < 128) {
        if (x < 64) {
            if (x < 32) {
                if (x < 16) {
                    if (x < 8) {
                        if (x < 4) {
                            if (x < 2) {
                                if (x < 1) {
                                    r = 0;
                                } else {
                                    r = 1;
                                }
                            } else {
                                if (x < 3) {
                                    r = 2;
                                } else {
                                    r = 3;
                                }
                            }
                        } else {
                            revert(); // TODO
                        }
                    } else {
                        revert(); // TODO
                    }
                } else {
                    revert(); // TODO
                }
            } else {
                revert(); // TODO
            }
        } else {
            revert(); // TODO
        }
    } else {
        revert(); // TODO
    }
}
```

Edit: This benchmarks as ~200 gas, compared to 2000 gas for the `bytes constant` one. Shows you the power of logarithms! But a proper `codecopy` solution should only be a dozen or so gas.

**Comment by hrkrshnn** [comment]
Effectively, implementing https://github.com/ethereum/solidity/issues/12587 would allow doing this. `immutable` / `code` data location would be stored in bytecode. The lookup would be `codecopy(...)` of some offset.
