### ISSUE TITLE
Allow public state variable with private setter

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12822]
## Usage

Sometimes it is required to a make a contract which is intended to be inherited. And the designer wants to ensure that the inherited will not change a specific storage variable. But at the same time this storage variable may be readable.

|                 | `public(get)`                                                | `internal(get)`                                              | `private(get)`                                               |
| --------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| `public(set)`   | :x: There are no public setters.                             | :x: There are no public setters.                             | :x: There are no public setters.                             |
| `internal(set)` | This is currently known as `public`.                         | This is current known as `internal`.                         | Currently you can only implement this with `private` storage variable and an `internal` setter function.<br /> |
| `private(set)`  | Currently you can only implement this with `private` storage variable and a `public` getter function. | Currently you can only implement this with `private` storage variable and an `internal` getter function. | This is currently known as `private`.                        |

## Existing code snippet

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

abstract contract ThreeChiefOfficers {
    /// @dev The account that can only reassign officer accounts
    address private _executiveOfficer;

    /// @notice Get the chief executive officer
    /// @return The chief executive officer account
    function executiveOfficer() public returns (address) {
        return _executiveOfficer;
    }
    // ...
}
```

## Proposed equivalent snippet

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

abstract contract ThreeChiefOfficers {
    /// @notice Get the chief executive officer
    /// @dev The account that can only reassign officer accounts
    address public(get) private(set) executiveOfficer;
    // ...
}
```

**Comment by hrkrshnn** [comment]
From a practical point of view, setters almost always have some access controls on them. Because of that, I don't see a need for compiler generated setters.

**Comment by fulldecent** [comment]
This issue is not about compiler generated setters.

This issue is about disallowing a subclass from accessing the setter of the parent.

**Comment by hrkrshnn** [comment]
@fulldecent The syntax is not quite clear to me:

```solidity
abstract contract ThreeChiefOfficers {
    /// @notice Get the chief executive officer
    /// @dev The account that can only reassign officer accounts
    address public(get) private(set) executiveOfficer;
    // ...
}
```

Would `private(set)` create a compiler generated setter? If not, how does the compiler connect the declaration to the actual setter?

**Comment by fulldecent** [comment]
There is no generated setter function. 

The expression is meant to indicate that an inheriting contract will NOT be allowed to use that state variable as an l-value.

**Comment by fulldecent** [comment]
Here are some actual use cases where this feature would be used today:

- ERC-721 implementation where the base class wants to allow overriding the `baseURL` variable (OZ does this)
- A owner implementation (ERC-5313 (DRAFT)) where changing the owner does something (like changing royalties) and therefore a subclass cannot edit the `_owner` variable directly.
- Libraries ("data structures") like queue and list, where there is some validation of the input variables (so directly setting the storage variables might lead to an unexpected state)
