### ISSUE TITLE
LSP: bare imports are not resolved

### ISSUE THREAD

**Issue by suicide** [ethereum/solidity#12833]
## Description

I am note sure whether this is actually a bug or rather a new feature.

When having a bare import like: 

```
import "hardhat/console.sol";
```
I get the following error message from the LSP:
```
ParserError: Source "hardhat/console.sol" not found: File not found. Searched the following locations: "/home/<someProjectDir>".
```

The file to import is part of a dependency within `node_modules`. The 'searched' location from the error msg is the project root.

The problem persists in truffle and hardhat projects as far as I can see. I'd also figure that nvim native LSP or Coc are not the issue.

Relative imports seem to be fine.

## Environment

- Compiler / LSP version: 0.8.13
- Target EVM version (as per compiler settings): 0.8.4
- Framework/IDE (e.g. Truffle or Remix): NVIM v0.7.0-dev+1292-ge9b53f3fb + native LSP, Truffle / hardhat
- EVM execution environment / backend / blockchain client: -
- Operating system: Arch Linux

## Steps to Reproduce

Create a new sample hardhat typescript project and open `Greeter.sol`

**Comment by chriseth** [comment]
Unfortunately, this is not yet possible, it needs the feature of setting the include path in the LSP.

**Comment by featheryus** [comment]
The feature seems under development， when to release it? Thanks

**Comment by christianparpart** [comment]
Hey @featheryus, we keep working on the LSP. I am currently onboarding also a second person to help boosting new features in. A date cannot be given, but we want to gradually add new features with each release (It may not *always* work, so bare with me :) )

@suicide I am looking into this now :)

**Comment by nickshatilo** [comment]
Hey @christianparpart, I tested the version with your PR (https://github.com/ethereum/solidity/pull/12994) included, and it seems like it still raises errors for hardhat like this issue mentioned. Altrough, go-to-definition works, but the errors are still in place. Could you please take a look?

<img width="751" alt="Screenshot 2022-07-15 at 12 15 56" src="https://user-images.githubusercontent.com/34378579/179212909-fb5ae453-e979-487c-bbba-9cd8ef3a6858.png">

My version:
```
Version: 0.8.16-develop.2022.7.15+commit.800088e3.Darwin.appleclang
```
