### ISSUE TITLE
Optimized Contract freezes with big uint number as argument

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#12848]
## Description

Hello again,

in the contract below,
```
contract C {
  function f(uint x2, string memory _str) public returns(uint d) {
    assembly 
    {
      for { let i := 0 } lt(i, x2) { i := add(i, 1) } {
        let c1 := 1002
        let x := mload(add(c1,2))
        d := mul(add(x2,x),keccak256(_str,x))
      }
    }
  }
}
```
when you try to run the optimized version given x2 a big number such as 100000000, then the optimized contract is never run and freezes.

## Environment

- Compiler version: solc 0.8.13
- Target EVM version (as per compiler settings): 
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: ubuntu 16.04

**Comment by chriseth** [comment]
Your contract uses a loop and you probably did not supply enough gas for the loop to finish.

What do you expect to happen?

**Comment by chamitro** [comment]
From what I see it does not even run with huge amount of gas. But maybe it does need even more.
But I understand your point.

**Comment by cameel** [comment]
I think it's just a problem with the in-browser EVM used by Remix not being very efficient at getting to the gas limit. Similarly as in https://github.com/ethereum/solidity/issues/12840#issuecomment-1112550272.

**Comment by bshastry** [comment]
Should we close this issue since it appears to be Remix related?
