### ISSUE TITLE
Request: bytes34

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#1284]
An ipfs multihash is by default 34 bytes. Is it possible to support bytes34?

**Comment by axic** [comment]
The main point of `bytesNN` is that it takes up one stack / storage slot, while `bytes` / `string` has the length as a 256 bit field preceding the data. This means that `bytes` cannot be used on stack operations easily and the conversion between `bytesNN` and `bytes` requires spending gas.

You can use `bytes` right now to store multihash values, introducing `bytes34` would not make the situation better.

**Comment by VoR0220** [comment]
I honestly would just make a library containing a special type for IPFS/Swarm hashes at this point.

**Comment by tymat** [comment]
IPFS addresses are:
1. base58 encoded 
2. padded with a single byte hash tag 
3. Prefixed with Qm

Removing the hash tag and the prefix will allow you to fit it inside a bytes32 data type.  You can check a sample implementation [here](https://github.com/tinybike/multi-hash)

**Comment by axic** [comment]
@tymat multihash itself has a header describing the hash family and type. For example sha256 or sha3-256 both will result in 32 bytes of output, which is then prefixed with the header.

It won't fit into `bytes32`.

What you see as Qm is actually the header in base58 encoding.

**Comment by ethernomad** [comment]
For future compatibility you should use `bytes` as multihashes could get longer. More expensive though...

**Comment by chriseth** [comment]
I would recommend either using `bytes`, juts two variables or a struct. The latter will hopefully be part of the ABI soon. Please reopen if you see the need for more discussion.

**Comment by aakilfernandes** [comment]
@chriseth nope sounds good. Thanks!
