### ISSUE TITLE
Support Yul objects in yulopti

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12856]
## Abstract
[yulopti](https://github.com/ethereum/solidity/blob/develop/test/tools/yulopti.cpp) is a simple tool for executing [optimizer step](https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-steps) sequences step by step.

Currently it only supports raw Yul input (example: [`medium.yul`](https://github.com/ethereum/solidity/blob/develop/test/libyul/yulOptimizerTests/fullSuite/medium.yul)). It would be convenient if it supported Yul objects as well (example: [`subObjectAccess.yul`](https://github.com/ethereum/solidity/blob/adc58c67b432ada0d7a4fc68f3de610ba78358c0/test/libyul/objectCompiler/subObjectAccess.yul)).

## Motivation
The compiler never produces raw Yul as output. When invoked with `--ir` or `--ir-optimized`, the Yul code is always wrapped in an object. The object part needs to be stripped for it to be usable with yulopti.

## Specification
- Use `ObjectParser` for parsing Yul objects (see how it was done in yul-phaser: #8513).
- yulopti should optimize all objects present in the file, including nested ones.
- (optional) add a command-line flag for selecting a specific object via a dotted path (e.g. `--object x.y.z`)

## Backwards Compatibility
This is an internal tool. We don't guarantee backwards-compatibility.

**Comment by dflupu** [comment]
@cameel I'd like to try my hand at implementing this. Could I be assigned to it?

Also, are there any tests at the moment for this particular tool? Should any tests be added?

**Comment by cameel** [comment]
We have a pending PR for this. It should not be closed, unless we also want to close the PR.

**Comment by ekpyron** [comment]
What does a pending (and stale) PR change about the fact that the issue is stale?

**Comment by cameel** [comment]
I mean, it does not make sense to close the issue alone. As long as we have that pending PR the issue should be open. If you want to close it, you should close both.
