### ISSUE TITLE
Add a mypy job to CI and fix type errors in our Python code

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12857]
## Abstract
We need a CI job that runs [mypy](https://github.com/python/mypy) on every PR and reports type errors in Python code.

## Motivation
Currently type annotations in our Python scripts are not checked at all. This is because the interpreter does not enforce them and an external tool is needed. mypy is currently the most popular one (though there are some others and we could use one of them if there are good arguments for doing so, see [ethanhs/python-typecheckers](https://github.com/ethanhs/python-typecheckers)). 

We already have CI jobs for [running Python unit tests](https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml#L724-L741) and [pylint](https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml#L661-L675) on Python code so there's no reason not to have mypy there as well.

## Specification
- Add a mypy config next to our [`pylintrc`](https://github.com/ethereum/solidity/blob/develop/scripts/pylintrc).
- Add a wrapper script in `scripts/` for easily running mypy with our config locally on all Python scripts in the repo..
- Run mypy on all existing Python scripts and fix any errors it finds. If there are any false-positives, you can disable them. For ease of review, the fixes should be a separate PR.
- Add a CI job that runs our wrapper script.

## Backwards Compatibility
No backwards-compatibility concerns here.

**Comment by gurukamath** [comment]
Unless someone else has already started working on this, I'd like to take a look.
