### ISSUE TITLE
Add Generics for Library usage.

### ISSUE THREAD

**Issue by karmabadger** [ethereum/solidity#12877]
## Abstract
Proposal to Add generic types for Libraries (and potentially for other types as well)

## Motivation
Often we would be writing libraries that are used for one type but could be used exactly the same way for different types as well. For instance, a library for uint256 that deals with uint256 arrays could literally be used to deal with uint8 or even your own custom struct types. (this is a problem that I did face). Without this feature, you would need to rewrite the entire library for each type that you would need to use it for which could be a lot of repetition. Plus, the libraries could easily get out of sync if only one of them was updated correctly. 

Example:
```solidity
library ArrayUint256Utils {
    function remove(uint256[] storage _array) internal returns (uint256) {
        // do something;
    }
}

library ArrayCustomTypeUtils {
    function remove(CustomType[] storage _array) internal returns (CustomType memory) {
        // do something;
    }
}
```

## Specification
Use angled brackets with generic type variable when declaring the library.
```solidity
library ArrayUtils<T> {
    function remove(T[] storage _array) internal returns (T memory) {
        // do something;
    }
}
```

Use angled brackets with the actual type name when using the library in contract code.
The following would be 2 different method to use the library function with generics. 
Method 1: with a "using" statement. (substitute the generic type value in the "using" statement)
Method 2: use the library directly (substitute the generic type value inline directly each time the library is being used or called).

example:
```solidity
contract useArrayUtils {
    using ArrayUtils<CustomType> for CustomType;

    function doSometihng() public {
        CustomType[] memory custom = something; // custom type array variable declaration
        custom.remove(); // method 1 
        ArrayUtils<CustomType>.remove(custom); // method 2
    }
}
```

## Backwards Compatibility
For backwards compatibility, libraries without generics would still also be accepted. There shouldn't really be any backwards compatibility issues.

## suggestions
- If a new library using generics has the same name as an old one and the generic type that's being substituted ends up giving the same library as the old one (same functions with same input outputs) then it should compile to the same bytecode and avoid being deployed another time.

- When one of the functions in the library returns with the generic type of the library, it has to be either "storage" or "memory" or "calldata". Then when it is being used, if substituted with a custom struct type or an array type, then the returned data would simply be either in "storage" or "memory" or "calldata". Else if substituted with a base type in solidity (uintN, intN, bool, address, fixedMxN, ufixedMxN, bytesN, bytes, etc) then, if when the returned type is "memory" simply return using the actual base type.
example: Let's take the example that I used previously of the library ArrayUtils<T>.  The function ArrayUtils<uint>.remove() would return (uint) instead of (uint memory) as it was declared as it wouldn't make sense to return (uint memory).

- Support the usage of multiple generic types in the same library using comma seperated type name inside the angled brackets.
Example: 
```solidity
library Utils<S,T,U,V> {
}

contract useUtils {
    using Utils<uint8, uint16, uint32, uint64> for CustomType

    function doSometihng() public {
        CustomType[] memory custom = something; // custom type array variable declaration
        custom.remove(); // method 1 
        ArrayUtils<uint8, uint16, uint32, uint64>.remove(custom); // method 2
    }
}
```
This might seem unnecessary as one single generic type might seem totally enough, but there might be for each function, different return types vs input types. There might be different types used to cast or do certain work on certain states.

- Allow type casting to generic type inside the library functions. Would error if it is not castable when the actual types are being used.

- A simple way that I can think of to implement this feature would probably just to find for each library using a generic type, to find each usage of it and the type with which it was used for the generic feature and create an equivalent library for which all of the generic types are replaced with the actual type. This may not be the right way to implement this, but is just a suggestion.

**Comment by karmabadger** [comment]
Please let me know if I haven't done this correctly or if it`s not clean enough, This is my first type writing a feature request here. Thanks!

**Comment by axic** [comment]
This is mostly covered in #869. Perhaps you can post your syntax suggestion there if it differs to the existing one.
