### ISSUE TITLE
bytes32 parameters cost more than uint256

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1287]
```
pragma solidity ^0.4.3;

contract GasTest {

    function testBytes32(bytes32 nonce) {}
    function testUInt256(uint256 nonce) {}

}
```

Without optimisation:
testBytes32(42): 156 gas
testUInt256(42): 134 gas

With optimisation:
testBytes32(42): 116 gas
testUInt256(42): 94 gas

Why is this? Surely it should be the same?

**Comment by axic** [comment]
The dispatcher code (matching ABI signatures to method locations) needs to check for each supported signature one by one. The later the function is in the dispatcher chain, the more gas it takes.

**Comment by ethernomad** [comment]
Ah this hadn't occurred to me. How does one control the order of the signatures in the dispatcher chain? It would be useful to put more commonly called functions at the beginning.

**Comment by axic** [comment]
I think the signature hashes are sorted, so you could try creating hashes which are a smaller number than the others :smiley: 

One optimisation though: if the fallback is defined, it comes first.

**Comment by axic** [comment]
Replaced by #1289.
