### ISSUE TITLE
Remove ewasm backend

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#12895]
Since Eth2 decided against ewasm, I think there's little reason for us to keep maintaining and developing the ewasm backend.
If people really want that, they can fork the compiler and maintain that in the fork.
If we need it again in the future, we can just revert the commits.

Thoughts?

**Comment by gakonst** [comment]
+1, personally never used the option in 4+ years

**Comment by transmissions11** [comment]
i didnt even know yall had an ewasm backend

**Comment by ControlCplusControlV** [comment]
+1 as well, ewasm doesn't make sense to continue development on if it's not being planned on being used, and keeping it in the Solidity compiler only adds more legacy code to manage

**Comment by lightclient** [comment]
+1

**Comment by NunoFilipeSantos** [comment]
We're closing all wasm issues for now.

**Comment by ekpyron** [comment]
> We're closing all wasm issues for now.

Haha, this one here I'm reopening, though :-). This here is the justification for closing all the others - but we haven't actually removed the backend just yet :-).

**Comment by ekpyron** [comment]
Done in https://github.com/ethereum/solidity/pull/13998
