### ISSUE TITLE
Document the subtleties of the dispatcher

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1289]
- [ ] The dispatcher has to check through all ABI signatures. The later the requested method is in the list, the more it will cost.
- [ ] Mention the order of gas cost differences (~20 gas for each additional step - as of EIP150).
- [ ] The signatures are sorted by value
- [ ] Fallback, if present, gets to be first (special case)

**Comment by chriseth** [comment]
Do we really want that deep level of documentation? Keep in mind that we have to keep it updated. Perhaps it would be better to tell people to look at the gas estimation for their functions. Furthermore, we should really use binary search for large contracts. And last but not least: Tell people that gas costs are subject to change with any hard fork and they should never rely on them.

**Comment by axic** [comment]
The dispatched now has a binary search, if enough functions are present.

There has been other requests to sort it by state mutability or by a supplied list. Since this comes up rather frequently, I'd say it would make sense documenting it.

@chriseth @ChrisChinchilla what do you think?

**Comment by chriseth** [comment]
Sounds good!

**Comment by ChrisChinchilla** [comment]
Sure, I will add it to the list, people like to know how things work :)

**Comment by axic** [comment]
Since we have the binary search option, this question comes up ever so often, and we may change the dispatcher with new functionality (#11102), I think it makes sense to really document this.

[This is the codegen function generating the dispatcher.](https://github.com/ethereum/solidity/blob/v0.8.3/libsolidity/codegen/ContractCompiler.cpp#L318)
