### ISSUE TITLE
Improve building Solidity on Windows

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#12904]
* While I personally think `vcpkg` should really be at least supported, I also struggled in getting `soltest.exe` linked against vcpkg's provided boost as it kept trying to link using the boost DLLs rather than static libraries.
* I was running `install_deps.ps1` from project root and have received error messages that come from the fact that  I wasn't executing the script one level deeper (d.g. ./build/ directory).
* Additional cmake flags are required, even when used in conjunction with the install-deps.ps1 provided dependencies. That should not be the case. Custom flags need to be passed to cmake are: `-DBoost_USE_STATIC_RUNTIME=ON -DBoost_DIR=${projectDir}\\deps\\boost\\lib\\cmake\\Boost-1.77.0 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded`
* The install-deps script could probably be made a little more fool-proof / robust, i.e. it should allow to be invoked more than once and not bail out with weird error messages.

**Comment by ekpyron** [comment]
Furthermore:
- we should more gracefully handle privilege errors in the symlink tests.
- we may consider making the non-release windows build a debug build (that would have caught https://github.com/ethereum/solidity/pull/12902)
- we need to fix VS2022 builds (https://github.com/ethereum/solidity/pull/12802 contains a CI setup for that, but is still lacking the actual range-v3-related fix)
- Also (although this may not strictly related to windows builds), ideally, linking soltest to dynamic boost should also be possible without issues.

**Comment by christianparpart** [comment]
I forgot what I did to work around the following error when executing `./scripts/install_deps.ps1`:

```
...
Building Boost.Build engine
LOCALAPPDATA=C:\Users\chris\AppData\Local
Found with vswhere C:\Program Files\Microsoft Visual Studio\2022\Community
###
### "Unknown toolset: vcunk"
...
```

which I am facing again, but probably also worth fixing for the common user.

**Comment by nikola-matic** [comment]
> I forgot what I did to work around the following error when executing `./scripts/install_deps.ps1`:
> 
> ```
> ...
> Building Boost.Build engine
> LOCALAPPDATA=C:\Users\chris\AppData\Local
> Found with vswhere C:\Program Files\Microsoft Visual Studio\2022\Community
> ###
> ### "Unknown toolset: vcunk"
> ...
> ```
> 
> which I am facing again, but probably also worth fixing for the common user.

Boost 1.77.0 doesn't support `vc143` toolset, i.e. your 2022 VS; support for this was only introduced in 1.78.0, so this will have to be bumped in the `install_deps.ps1`. Also, once you sort that out, you'll encounter a problem where you won't be able to generate the build via `cmake`, since the `cmake` we fetch is older, and also doesn't support generating build files for `VS 2022`, so we'll have to bump that to at least `v3.21.0`.

**Comment by nikola-matic** [comment]
#13434 should address VS2022 incompatibilities. Our docs however recommend using VS2019, and even though this particular change will have no effect on those using older versions of Visual Code, we should perhaps discuss updating the docs to instead recommend VS2022 (this will require bumping the minimum versions of `boost` and `cmake` in the docs as well).

**Comment by cameel** [comment]
We could also mention both and that minimum requirements are different in each case.
