### ISSUE TITLE
Prerelease warning made warning tests ineffective

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1291]
Due to the fact that every prerelease version of a compiler emits a warning for every input, the tests that check for the existing of some warning are now ineffective. We should change these tests to check the actual warning text.

**Comment by axic** [comment]
This should be done for the errors too - we want to check for specific errors and not "it's fine if any error has happened".

**Comment by chriseth** [comment]
@pirapira your PR only said "trying to fix". Do you want this to be reopened?

**Comment by pirapira** [comment]
Yes.  The PR started to fix the problem in only one file.  I knew the comment would close the issue, but I was too optimistic.

**Comment by pirapira** [comment]
This has been done by now.
