### ISSUE TITLE
Importation problem on VSCODE

### ISSUE THREAD

**Issue by lolo464644** [ethereum/solidity#12917]
Hello fam, this is my first post on Github so, hi !

I am currently learning to dev in Solidity so I am following the "online course" freecode camp : [https://www.youtube.com/watch?v=M576WGiDBdQ&t=18664s&ab_channel=freeCodeCamp.org]
I am currently at 5:10:25 and i have an issue with the compiler, when i try to compile, I have the following error : 

```
> CompilerError: solc returned the following errors:
> 
> contracts/FundMe.sol:5:1: ParserError: Source "C:/Users/Loïc PORCO/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/vendor/SafeMathChainlink.sol" not found: File outside of allowed directories.
> import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";
> ^------------------------------------------------------------------^
> 
> contracts/FundMe.sol:6:1: ParserError: Source "C:/Users/Loïc PORCO/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File outside of allowed directories.
> import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
> ^--------------------------------------------------------------------------^
```

After searching on internet, I think I understood that the place where my  2 files are is not in an allowed path so i have to manually allow this path w the command --allow-paths, but i didnt understand how it works, so iam asking for your help.

In order to be more specific ill post images of my VSCODE 
my .yaml :
![image](https://user-images.githubusercontent.com/103314104/162569520-b97f7708-7a3c-4fd5-8cc3-ff0e0e5b59b9.png)

my .sol :
![image](https://user-images.githubusercontent.com/103314104/162569562-a52ae6b3-a77b-4f75-b88b-4916383d9a82.png)
Iam on windows.
Thank you for your time ! 

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by nishant-sachdeva** [comment]
Would be much better to ask this question in the main Solidity chat 
https://matrix.to/#/#ethereum_solidity:gitter.im

Closing this issue for now. We can reopen this issue if we find some actionable insights.
