### ISSUE TITLE
Suggest trying to compile via IR in the stack-too-deep error message in legacy compilation.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12912]
Since it seems like via IR compilation works in a lot of such cases these days, this might help against stack-too-deep frustration and help in promoting via-IR codegen.

**Comment by ekpyron** [comment]
Actually, maybe better to explicitly suggest *optimized IR codegen*, since unoptimized via IR code is *more* likely to have issues than legacy code I'm afraid...

**Comment by hrkrshnn** [comment]
Agree. We should do this right away.

**Comment by Pedroa0710** [comment]
Impruve marged
