### ISSUE TITLE
Should support referring to foreign-constants as compile-time constants

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#12927]
`A.sol`:
```
import "./B.sol";

contract A {
    uint256 private constant LIMIT = B.MAX * B.SCALE;
}
```

`B.sol`:
```
library B {
    uint256 internal constant MAX = 1;
    uint256 internal constant SCALE = 100;
}
```

Results in:
```
TypeError: Initial value for constant variable has to be compile-time constant.
 --> contracts/A.sol:4:38:
  |
4 |     uint256 private constant LIMIT = B.MAX * B.SCALE;
  |                                      ^^^^^^^^^^^^^^^
```

The problem is not the multiplication, but rather that `B.MAX` or `B.SCALE` is not considered compile-time constant.

**Comment by StrongerXi** [comment]
This seems pretty tricky...

We can probably try to resolve a smaller example first:
```solidity
import "./B.sol";

contract A {
    uint256 private constant LIMIT = B.MAX;
}
```

Essentially, `bool TypeChecker::visit(VariableDeclaration const& _variable)` expects `TypeChecker::visit(MemberAccess const& _memberAccess)` to annotate the member accesses `B.MAX` as `pure`, but the latter call doesn't have enough information there, i.e., it knows the `referencedDeclaration`, which is a `class Declaration`, yet neither `Declaration` nor its `DeclarationAnnotation` has any information on the purity of the declaration.

**Comment by StrongerXi** [comment]
It might be simpler than I thought, see #12928.
