### ISSUE TITLE
More concise "Cheatsheet" page

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12934]
## Page
- [Cheatsheet](https://docs.soliditylang.org/en/latest/cheatsheet.html#global-variables)
- [Units and Globally Available Variables](https://docs.soliditylang.org/en/latest/units-and-global-variables.html)

## Abstract
Currently the "Cheatsheet" page mostly contains information already available in "Units and Globally Available Variables". The information is already concise in that original source so the cheatsheet just looks like an inferior copy. Also, having two copies is just an extra maintenance burden that's not worth it unless the cheatsheet actually adds something of value. I think we can make it more valuable by adding summaries of information from other pages and streamlining the way it's presented where possible.

Here's what I think we should do:
- Remove excessive detail from the cheatsheet. If the info is only available there, move it to a different location.
    - [x] Notes/warnings should not be there
    - [ ] (Optional) "Global Variables" section would be better off as a table. This may require tweaking the descriptions or presenting signatures in a more compact way.
        - Marking this as optional since we tried it and it did not look good (#13595). I still think it's possible but will require some editing of the content to make it actually suitable for a table.
    - [x] Members of `address`, `type`, etc. should be in a separate section, not under "Global Variables".
    - [x] The operator precedence should be under [Types > Operators](https://docs.soliditylang.org/en/latest/types.html#operators). Maybe it makes sense to have a copy here but that's also extra maintenance so I'd just move it.
    - [x] I think that the list of keywords should be moved to "Units and Globally Available Variables". It does not fit that page perfectly but is a bit related.
- Add missing info
    - [ ] Members available on functions, errors, events, calldata/storage variables, arrays, etc. (`slot`, `offset`, `length`, `address`, `selector`, ...).
        - These should be added to "Units and Globally Available Variables" as well.
    - [ ] Make sure that the list of "Global Variables" contains every item from "Units and Globally Available Variables"

**Comment by SamuelOsewa** [comment]
I created a pull request with the notes section removed from the cheat sheet. Was that done correctly? @cameel

**Comment by victorknox** [comment]
@cameel I have created a PR for moving the keywords, hope it's okay
I also noticed that separating members address, type etc. would make it very similar to "Units and Globally Variables"
would it be okay to proceed?

**Comment by cameel** [comment]
It's fine. The descriptions in "Units and Globally Available Variables" are similar but still not identical and they won't necessarily stay so brief forever. And even the short descriptions will likely diverge as we expand the cheatsheet. For the cheatsheet we'll actually want to shorten them even more so that the information can fit in a neat table. When members are in separate sections we'll also be able to show them in a more compact way, e.g. `codehash` instead of `<address>.codehash` since that will be clear from context.

But anyway, the primary motivation is that the current header is just wrong. Members are not global variables.

**Comment by mariagabrielacs123** [comment]
Hello! I can work on this issue.

**Comment by cameel** [comment]
Sure. Feel free to pick something from the list above and submit a PR!

**Comment by mariagabrielacs123** [comment]
I made a pull request for the "Global Variables" section as a table, let me know if this was done correctly! @cameel

**Comment by hsraktu17** [comment]
Hi, I wanted to contribute to this issue.

**Comment by ojasaklechayt** [comment]
@cameel for the task " Members of address, type, etc. should be in a separate section, not under "Global Variables". "
What should be the name of the section ?

**Comment by ojasaklechayt** [comment]
@cameel I have made a pull request for the 3rd task.
