### ISSUE TITLE
Add more useful information to the "Cheatsheet" page

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12935]
Should be done after #12934.

## Page
- [Cheatsheet](https://docs.soliditylang.org/en/latest/cheatsheet.html#global-variables)

## Abstract
When we're done cleaning up the cheatsheet, we could add more interesting information that's already described elsewhere but less concisely. Some ideas:
- [ ] Table of available types.
- [ ] Various types of literals (in particular string literals like `hex""` and `unicode""`).
- [ ] Table of allowed implicit and explicit conversions between types.
- [ ] Table of available pragmas and experimental pragmas.
- [ ] Table of [control structures](https://docs.soliditylang.org/en/latest/control-structures.html).
- [ ] Table of common signatures, in particular for `Error` and `Panic`.
- [ ] Possible forms of `using for` and `import` statements.
- [ ] Concise table showing settings usable in Standard JSON (full list is at [Using the Compiler > Input Description](https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description)) and the corresponding CLI options.
- [ ] Comparison between contracts, abstract contracts, libraries and interfaces (i.e. what is allowed/disallowed in each of them).
- [ ] Visual example for [C3 linearization](https://docs.soliditylang.org/en/latest/contracts.html#multiple-inheritance-and-linearization).

Some things are already available as tables or lists so we could move them to standalone pages and include in both places (like in #13138):
- [ ] Table of Yul opcodes: [Yul > EVM Dialect](https://docs.soliditylang.org/en/latest/yul.html#evm-dialect).
- [ ] Table of optimizer steps and their abbreviations: [Yul > Optimization Step Sequence](https://docs.soliditylang.org/en/latest/yul.html#optimization-step-sequence).
- [ ] Table of natspec tags: [Natspec Format > Tags](https://docs.soliditylang.org/en/latest/natspec-format.html#tags).
- [ ] List of supported EVM versions: [Using the Compiler > Target Options](https://docs.soliditylang.org/en/latest/using-the-compiler.html#target-options).

**Comment by swetepete** [comment]
Open to trying this out.

So the basic idea is to convert from the documentation any topic listed above to a much more concise version, in the cheat sheet?

For example, the types listed here?: https://docs.soliditylang.org/en/v0.8.12/types.html

Thank you

**Comment by cameel** [comment]
Please note that we need to clean up the cheat sheet first. This task should be done after #12934.
