### ISSUE TITLE
Discrepancy between a Library bytecode function identifier check and the generated abi with structs

### ISSUE THREAD

**Issue by hroussille** [ethereum/solidity#12947]
## Description

When compiling a simple library, the generated byte code doesn't match the output of the ABI regarding the function identifier.
This result in a revert for what seem to be a perfectly valid action.

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.7;

struct AB {
  uint8 a;
  uint8 b;
}

library TheLibrary {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
}
```

The generated bytecode checks for the function identifier : `0x70c40302` (`keccak256("add(AB)")`) but the ABI file interpretation generates the following function identifier `0x2f563ac4` (`keccak256("add((uint8,uint8))")` on the client side.

If  you were to compile a Contract : 

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.7;

struct AB {
  uint8 a;
  uint8 b;
}

contract TheContract {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
}
```

The generated byte code checks for `0x2f563ac4`, the discrepancy between library and contract seems like a bug to me ?

## Environment

- Compiler version: Tested from 0.8.7 and above
- Framework/IDE : Truffle / Remix / Hardhat
- EVM execution environment : Truffle / Remix JS EVM / Hardhat
- EVM version : London

## Steps to Reproduce

Compile the library above and try to call `add` directly, leading to a revert.

Call it with the following calldata : `0x70c4030200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001` and the result is `2` as expected.

**Comment by OrizzoN7** [comment]
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.7;

struct AB {
  uint8 a;
  uint8 b;
}

library TheLibrary {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
}
The generated bytecode checks for the function identifier : 0x70c40302 (keccak256("add(AB)")) but the ABI file interpretation generates the following function identifier 0x2f563ac4 (keccak256("add((uint8,uint8))") on the client side.

If you were to compile a Contract :

// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.7;

struct AB {
  uint8 a;
  uint8 b;
}

contract TheContract {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
}
The generated byte code checks for 0x2f563ac4, the discrepancy between library and contract seems like a bug to me ?

Environment
Compiler version: Tested from 0.8.7 and above
Framework/IDE : Truffle / Remix / Hardhat
EVM execution environment : Truffle / Remix JS EVM / Hardhat
EVM version : London
Steps to Reproduce
Compile the library above and try to call add directly, leading to a revert.

Call it with the following calldata : 0x70c4030200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001 and the result is 2 as expected.

KEYWORDS Required

**Comment by cameel** [comment]
It's by design. See [Function Signatures and Selectors in Libraries](https://docs.soliditylang.org/en/latest/contracts.html#function-signatures-and-selectors-in-libraries):

> While external calls to public or external library functions are possible, the calling convention for such calls is considered to be internal to Solidity and not the same as specified for the regular [contract ABI](https://docs.soliditylang.org/en/latest/abi-spec.html#abi).

> Non-storage structs are referred to by their fully qualified name, i.e. `C.S` for `contract C { struct S { ... } }`.

There's been a lot of discussion about whether the contract ABI should be updated to support user-defined types explicitly, like enums or structs but breaking changes in the ABI are problematic so the current status quo is that they're simply encoded as uints or tuples, respectively. With libraries we did not have that limitation.

**Comment by hroussille** [comment]
Ah okay I did miss that part, thanks !

I just don't understand why an incorrect ABI is exposed though? if such calls are considered to be internal, there should be no mention of it in the abi file ?

**Comment by cameel** [comment]
That's a bit of a grey area. It's not like the ABI of libraries is completely off-limits but it also does not have the strong compatibility an interoperability guarantees of the contract ABI. As the docs say, it's possible to interact with it, the compiler is not going out of its way to hide it but there are some caveats.

And as for the reasoning behind this, @chriseth or @axic would have to chime in with some historical details.

**Comment by hroussille** [comment]
> That's a bit of a grey area. It's not like the ABI of libraries is completely off-limits but it also does not have the strong compatibility an interoperability guarantees of the contract ABI. As the docs say, it's possible to interact with it, the compiler is not going out of its way to hide it but there are some caveats.
> 
> And as for the reasoning behind this, @chriseth or @axic would have to chime in with some historical details.

I see, thanks for your reply ! I'd be curious to know those details though.
