### ISSUE TITLE
LLL: Add a proper versioning system

### ISSUE THREAD

**Issue by zigguratt** [ethereum/solidity#1295]
Currently there's no versioning associated with the LLL compiler. The output of `lllc --version` is:

```
LLLC, the Lovely Little Language Compiler 
  By Gav Wood, (c) 2014.
```

At the very least we need to return a version number when someone asks for it with `--version`. Something like Solidity's `--version` output would probably make sense:

```
solc, the solidity compiler commandline interface
Version: 0.4.4-develop.2016.10.26+commit.41027535.Linux.g++
```

A `pragma` keyword should also be considered now that LLL development is no longer stagnant and new features and keywords are being added. e.g.:

```
(pragma "^0.1.0")
```

**Comment by axic** [comment]
I think regarding `--version`, for the moment it should just output the version of the Solidity tree, as that's where it resides.

I'm not sure about `pragma` though :smiley:

**Comment by zigguratt** [comment]
Where can one get the version number of the Solidity tree? (Ah, `dev::solidity::VersionString`) That would be fine with me. It's got to be better than what it's doing now. :grin: 

Re: `pragma`, it was just a thought. If people don't think it's necessary then I have no problem with that.

**Comment by chriseth** [comment]
lll cannot get the solidity version unless it links against libsolidity, but we can have a similar mechanism for lll.

**Comment by zigguratt** [comment]
@chriseth Yep, I discovered that already. :grin: I'll look into how Solidity does its version string, then.

**Comment by zigguratt** [comment]
Looks like adding a version string to LLL is beyond my current understanding of the code base and build process. It'll have to wait until I have a better grasp or until someone else does the work.
