### ISSUE TITLE
Prevent `dup`-ing values that are cheaper to recompute 

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12963]
From https://github.com/foundry-rs/foundry/issues/1373

> the TIMESTAMP opcode costs 2 gas, so this is a weird optimization. DUP1 costs 3 gas and POP costs 2 gas, so really, there isn't any gas saving here?

**Comment by hrkrshnn** [comment]
I don't have a minimal example for this yet.

**Comment by cameel** [comment]
What was the compiler version where they saw this? Since the linked issue mentions `via-ir`, it must have been 0.8.13?

**Comment by wminshew** [comment]
> What was the compiler version where they saw this? Since the linked issue mentions `via-ir`, it must have been 0.8.13?

op here -- confirmed `0.8.13`

separately, was under the impression (based on logged output w/i test) the issue was `via-ir` re-calling `TIMESTAMP` instead of duping the old saved value (since it "should" be immutable w/i a tx anyway, which is obviously broken by test time-travel logic)?

**Comment by wminshew** [comment]
here's a [minimal repro](https://github.com/wminshew/minimal-repro-12963)

**Comment by hrkrshnn** [comment]
@wminshew Thanks. Just to summarize the above mimal repro, the compiler assumes that `block.timestamp` is movable / copyable across the contract. So, instead of `dup`-ing, it's just repeating the computation (opposite of the title of the issue).

```solidity
function f() external {
    uint timeStart = block.timestamp;
    vm.warp(100);
    // compiler may replace the following value by `timestamp()` instead of `dup`-ing the value in stack.
    // Because `warp` can change this, this doesn't work for testing
    timeStart;
}
```

To fix this, we'll have to change the side-effects of the opcode `timestamp`. Since this is only relevant for testing, we'll likely need to create a flag for this. I wonder if we should just start creating a `--debug` flag for such changes.

**Comment by nikola-matic** [comment]
```
$ cat y.yul
{
        sstore(timestamp(), timestamp())
}
$ build/solc/solc --strict-assembly --optimize --asm y.yul

======= y.yul (EVM) =======

Text representation:
    /* "y.yul":23:34   */
  timestamp
  timestamp
    /* "y.yul":3:35   */
  sstore
    /* "y.yul":0:37   */
  stop
```

Not an issue as of  `0.8.23` (probably earlier versions well).
