### ISSUE TITLE
Download list is empty in the flyout menu in the docs for versions 0.8.9..0.8.13

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12961]
The list of downloadable formats in [0.8.13 docs](https://docs.soliditylang.org/en/v0.8.13/) (and also older versions, down to 0.8.9) seems broken:
![flyout-menu-versions-0 8 13](https://user-images.githubusercontent.com/137030/165140423-72a8dd50-e3c4-4005-b679-19c4ef835ca5.png)

For older releases and for `latest` the links are there:
![flyout-menu-versions-latest](https://user-images.githubusercontent.com/137030/165140424-92e6a968-7d61-4749-8f7d-87c4be5329d4.png)

It might be somehow related to changes we did in #12238, though I'm not certain about that. The biggest change was the move of the downloads section above the versions list and in 0.8.9 that change was still not present:
![flyout-menu-versions-0 8 9](https://user-images.githubusercontent.com/137030/165140416-97191dd4-48cc-46a4-a5ec-3cbc8ade5ee9.png)

**Comment by timweri** [comment]
I can't seem to see this bug. I already tried all the versions mentioned.

**Comment by cameel** [comment]
@nishant-sachdeva Can you check that?

**Comment by nishant-sachdeva** [comment]
@cameel Indeed, the download sections are not empty in the docs' versions mentioned here. I don't see the bug either.

**Comment by cameel** [comment]
Great! We can close it then. I guess it must have been something on RTD side.
