### ISSUE TITLE
Error message that results from using Unicode in string literal is confusing

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#12968]
## Description

Suppose I try to compile the following contract:

```solidity
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Repro {
  function run() public pure returns (string memory) {
    return "¡¡¡";
  }
}
```

I get the following error message:

```
ParserError: Invalid character in string.
 --> project:/contracts/Repro.sol:6:12:
  |
6 |     return "¡¡¡";
  |            ^^
```

Now, I know Solidity well enough to realize that, oh right, this is because Unicode strings have to be prefixed with the word `unicode`.  However, someone newer to Solidity, who hasn't read all the documentation, likely wouldn't realize this, and would likely conclude that Unicode strings simply aren't allowed at all.

The error message should be rewriten to point out the existence of `unicode` strings. Say something like, "Unicode character in non-unicode string literal; literal must be marked as unicode" or something like that.

## Environment

- Compiler version: 0.8.13
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle

## Steps to Reproduce

See above.

**Comment by cameel** [comment]
Right. This should be easy to improve. Adding a `good first issue` label since fixing it is basically rewording the error message.

We could also add an escaped representation in the message to make this clearer for characters that look close to ASCII chars (e.g. many cyryllic letters or the Turkish i/I).

**Comment by super1ha1** [comment]
Hi @cameel I made a pull request here, can you help to take a look
[12977](https://github.com/ethereum/solidity/pull/12977)

thanks you !

**Comment by SamuelOsewa** [comment]
Hey @cameel I made a pull request for this issue, please take a look

Thanks in advance
