### ISSUE TITLE
Solidity summit 2022 (Amsterdam) slide feature non-value immutables. 

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#12970]
Not exactly documentation, but [slide #5 of @chriseth's presentation at the Solidity summit](https://chriseth.github.io/notes/talks/summit_2022/#/5) includes 

```
string public immutable name = "MyToken";
```

Unlike the immutable array, this is not marked as "not available yet" ... but it doesn't appear to work with 0.8.13.

Maybe it would be nice to update the slide to clarify that point.

**Comment by chriseth** [comment]
Ah, thanks a lot! Should be fixed now.
