### ISSUE TITLE
Feature Request: Include some revert data to identify that function doesn't exist in contract

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#12982]
## Abstract

When a function doesn't exist in a contract, the contract simply reverts. It's quite frequent that devs jumble up contract addresses while interacting with the contracts (on the client-side), and they just see a `execution reverted` error which might not be helpful for someone in this situation for the first time.

## Motivation

But if some data is included (like a 4 bytes selector), it'd help libraries like ethers to show a better error. (related discussion https://github.com/ethers-io/ethers.js/discussions/2958). I understand this would not help with existing deployed contracts but in the long term this might be helpful.

## Specification

Solidity may revert with something like this, instead of no revert data.

```solidity
error FunctionNotFound();
```

## Backwards Compatibility

There should be no issues.

**Comment by zemse** [comment]
I faced this exact problem two days ago at a hackathon, my selector was wrong and I was trying to debug somewhere else. I think it would be great if this feature could be supported in Solidity, maybe some error code through `Panic`. I propose to reopen this issue if you also think it can add some value.

**Comment by cameel** [comment]
@zemse It's actually already a feature. If you pass `--revert-strings debug` to the compiler, the compiler will always include a message in the reverts it generates. If you call a function that does not exist, you should get:
```
Contract does not have fallback nor receive functions
```

You can see all the messages applicable to your code if you request the `--ir` output and look at the `revert_error_...()` functions.

The selector is not included, but that's a part of the input, so when you know the reason behind he revert, you should be able to easily get it from the tool, without having to embed that info in the contract. We also have `--revert-strings verboseDebug` variant, where we could include that info, but looks like it was never actually implemented. I think there just wasn't much demand for that.

This was added before custom errors were a thing so it uses free-form strings, but I'd say that we should definitely switch to custom errors with well defined codes. That's #11664, which I think should be reopened.

**Comment by zemse** [comment]
It is great that there's a debug option. But is it possible to include a Panic or Error code even in optimised runtime code (similar to overflow errors)?

**Comment by cameel** [comment]
Yeah, that's what #11664 was about. @ekpyron can we reopen it?

**Comment by ekpyron** [comment]
Yeah https://github.com/ethereum/solidity/issues/11664 should have stayed open... we can we close this as falling under https://github.com/ethereum/solidity/issues/11664 then, though, right?
