### ISSUE TITLE
Are 39 or 41 digit long address literals allowed?

### ISSUE THREAD

**Issue by sourabhxyz** [ethereum/solidity#12992]
## Page

https://docs.soliditylang.org/en/v0.8.13/types.html#address-literals

## Abstract

Do they mean: "Hexadecimal literals that **40** digits long and do not pass the checksum test produce an error." if not, then why does the language include 41 or 39 digits long hexadecimal literals?

## Pull request

I can create pull request if statement actually meant solely 40 digits long hexadecimal literals.

**Comment by cameel** [comment]
Try appending a single digit at the end of the address from the example. You'll get this error:
```
Error: This looks like an address but is not exactly 40 hex digits. It is 41 hex digits. If this is not used as an address, please prepend '00'. For more information please see https://docs.soliditylang.org/en/develop/types.html#address-literals
 --> test.sol:2:17:
  |
2 |     address a = 0xdCad3a6d3569DF655070DEd06cb7A1b2Ccd1D3AF1;
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
If you append more than one, you'll get this instead:
```
Error: Type int_const 3225...(43 digits omitted)...8545 is not implicitly convertible to expected type address.
 --> test.sol:2:5:
  |
2 |     address a = 0xdCad3a6d3569DF655070DEd06cb7A1b2Ccd1D3AF11;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Basically, the compiler assumes that 39- or 41-digit hex integers could be mistyped addresses and adapts the error message to that.

**Comment by sourabhxyz** [comment]
Thanks a lot cameel!
