### ISSUE TITLE
"npm install solc" fail on MacOS

### ISSUE THREAD

**Issue by jwter** [ethereum/solidity#1299]
install solidity on Mac.
on command line input "npm install solc" output :
npm WARN enoent ENOENT: no such file or directory, open '/Users/jwter/develop/package.json'
npm WARN develop No description
npm WARN develop No repository field.
npm WARN develop No README data
npm WARN develop No license field.
so. check file system. can see "node_modules" on finder. and  really ont  have that files

**Comment by jwter** [comment]
is a new version problem ?

**Comment by chriseth** [comment]
npm might be confused by the contents in the directory where you execute the command. Can you do that in a freshly created directory? It might also be better to use `npm install -g solc` or `sudo npm install -g solc`.

**Comment by jwter** [comment]
solc compile is install this ?  or  download "https://github.com/ethereum/solidity"  build from source?
i install with "npm install -g solc" ,but  just install 'usr/local/bin/solcjs'  don't have 'solc'
and some error when command excute " 

> web3.eth.getCompilers()
> []
> admin.setSolc("/usr/local/bin/solc")
> exec: "/usr/local/bin/solc": stat /usr/local/bin/solc: no such file or directory
>     at web3.js:3119:20
>     at web3.js:6023:15
>     at web3.js:4995:36
>     at <anonymous>:1:1
> 
> admin.setSolc("/usr/local/bin/solcjs")
> "0.4.3+commit.2353da71.Emscripten.clang\n\npath: /usr/local/bin/solcjs"
> source = "contract test { function multiply(uint a) returns(uint d) { return a \* 7; } }"
> "contract test { function multiply(uint a) returns(uint d) { return a \* 7; } }"
> clientContract = eth.compile.solidity(source).test
> solc: exit status 1
> Must provide a file

Specify --help for available options

```
at web3.js:3119:20
at web3.js:6023:15
at web3.js:4995:36
at <anonymous>:1:18
```

"

**Comment by chriseth** [comment]
You cannot use the npm package together with geth, it is solely meant to be used inside a javascript environment directly. If you want to use it with geth and `eth.compile.solidity` (which is discouraged due to its inflexibility), you have to either compile from source or install a homebrew package.
