### ISSUE TITLE
Error type should be `function (...) public pure`

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#12991]
## Abstract

Any error has a `.selector` member which returns the first four bytes of the keccak256 hash of the properly abi encoded function (error) selector. 

Any error as far as I have noticed is of `function () pure` type.

Internal and private function types do not possess a `.selector` member. This makes it impossible to write something like the following:

```solidity
pragma solidity ^0.8.13;

error ERROR1();

library TEST_L {
    event LOG(bytes4 sig);

    function _TEST(function () pure f) internal {
        emit LOG(f.selector);
    }
}

contract TESTER {
    using TEST_L for *;

    function TEST() external {
        ERROR1._TEST();
    }
}
```

Compile error:

```bash
TypeError: Member "selector" not found or not visible after argument-dependent lookup in function () pure.
--> test.sol:9:18:
|
9 | emit LOG(f.selector);
| ^^^^^^^^^^
```
 
## Motivation

Make errors, if possible, of type `function () public pure` This would solve the compile issue of the above snippet.

## Specification

`type()` should return for any error `function (types...) public pure` where `types...` are the types of the input arguments.

## Backwards Compatibility

This should introduce compatibility issues for solidity code which assumes any error type to explicitly be `function (...) pure`.

**Comment by chriseth** [comment]
The issue is that you cannot pass around a non-instance reference to an error, this is just not implemented in the language. We might allow that in the future with generics or we might allow passing around instances of errors.

In the meantime, I would recommend to pass the selector directly instead of the error.
