### ISSUE TITLE
Feature: `print(...)`

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12995]
## Abstract

A variadic function `print(...)` that would emit a `log*` with `abi` encoded data of its arguments.

## Motivation
It's typical for testing frameworks / debugging setups to have some way to print the value of variables.

For Hardhat, this is [`console.log`](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/console.sol). For dapptools and foundry, this is [`log_uint` etc](https://github.com/dapphub/ds-test/blob/master/src/test.sol#L22-L36).

## Specification

The (dapptools / foundry) implementation is fairly simple. `print(a, b, c)` is equivalent to emitting the following `bytes`: `abi.encode(a, b, c)`. However, testing tools would want to know how to decode this. Therefore, the first (or perhaps the second?) topic should be a marker for the types. This can probably be emitted in the JSON output for ABI. The tool can then lookup the hash to understand the types and do a `abi.decode` to get back the data.

For hardhat implementation, it seems to do a `staticcall` to a magic address. This is an alternative to consider for implementation.

We should also consider introducing a `--debug` flag. Where compiler would warn about `print` if `--debug` flag is not set.

**Comment by hrkrshnn** [comment]
For comparison, there is `print` in Vyper: https://github.com/vyperlang/vyper/pull/2818 modelled after `console.log` in hardhat.

**Comment by chriseth** [comment]
Logs are problematic because they are erased on revert, the optimizer might even remove `print`s before a `revert`.
If we want to do this, we need a special debugging EVM / a special opcode whose effects are not erased by revert.

**Comment by hrkrshnn** [comment]
> Logs are problematic because they are erased on revert, 

I don't think this is an issue. Just need to change this in the VM. I believe these tools are already doing it. 

> the optimizer might even remove prints before a revert.

Good point. Maybe a good use for a `--debug` flag.

**Comment by hrkrshnn** [comment]
Conclusion from the meeting: the team wants this to be solved using generics rather than having inbuilt functions.

Regarding a `--debug` flag (or something alike), this could still be useful for solving issues in testing. For example, the optimizer assuming that the value of `block.timestamp` is the same throughout a transaction.

Will close.

**Comment by chriseth** [comment]
Tiny addition: This is a good contender for the standard library, so I think it should be "built in" at least in some sense.

**Comment by hrkrshnn** [comment]
@chriseth Are we sure generics can really solve this?

This is an example of what I'm doing:

```solidity
        emit log_named_uint("returndatasize: ", rds);
        emit log_named_uint("offset: ", a);
        emit log_named_uint("length: ", b);
        emit log_named_bytes32("data: ", c);
```

I suspect we'll need to have variadic arguments (with generic args) to solve this (let's say I want to do `print("first", a, "second", b)`)   I'm not too keen on seeing variadic args in solidity.

Also more importantly, being able to print a struct (a json serialization of the struct) would be perfect.

**Comment by chriseth** [comment]
It can be solved in rust, so it should also be doable in solidity.
Why would you like to have variadic args for print, but not for user defined functions?
