### ISSUE TITLE
Native solidity support for EIP-196 EIP-197: ECADD and ECMOD for alt_bn128

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/solidity#13003]
## Abstract

Consider support ECADD and ECMOD as per [EIP-196](https://eips.ethereum.org/EIPS/eip-196) and [EIP-197](https://eips.ethereum.org/EIPS/eip-197)

## Motivation

Many use cases as per 
- https://eips.ethereum.org/EIPS/eip-1923
- https://medium.com/@rbkhmrcr/precompiles-solidity-e5d29bd428c4

## Specification

Some built-in function as https://medium.com/@rbkhmrcr/precompiles-solidity-e5d29bd428c4

```
function ecmul(uint ax, uint ay, uint k) public view returns(uint[2] memory p) {
 uint[3] memory input;
 input[0] = ax;
 input[1] = ay;
 input[2] = k;

 assembly {
   if iszero(staticcall(gas, 0x07, input, 0x60, p, 0x40)) {
       revert(0,0)
   }
 }
 return p;
}
```

## Backwards Compatibility

shall not have any backward compatibility issue

**Comment by chriseth** [comment]
Related to #10639
