### ISSUE TITLE
Revisit gcc 12 / boost workarounds with the next version of boost.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#13008]
https://github.com/ethereum/solidity/pull/13006 was a quick hack to restore compilation against gcc 12.

Once a newer boost version with proper gcc 12 compatibility (without warnings) is released, we can revisit this (and either make the workaround conditional depending on the boost version or bump the minimum required version of boost, at least in the presence of gcc 12).

On the other hand, it'll be a bit of a mess no matter what. We could also try to figure out why gcc does not consider boost system headers and ignores warnings in them by default.

**Comment by cameel** [comment]
I don't think we should be just closing all technical debt issues like this one.
