### ISSUE TITLE
Confusing error message when using function calls that don't return anything as expressions.

### ISSUE THREAD

**Issue by 0xalpharush** [ethereum/solidity#13017]
## Description

The behavior of dynamic storage arrays with struct type is inconsistent and the compiler output is not helpful. I would expect that `pop1` and `pop3` be semantically equivalent; that is, `.pop()` would return the last array element and delete it. However, the error message for `pop3` suggests that a type of tuple is return by `.pop()`. 

When I treat it as a tuple as suggested, the error message says there's a different number of components... Ideally one could cast this tuple to the struct type or receive the struct type and manually reference values, but neither works with `.pop()`. 

See also that the number of components is different when accessed via index versus using pop (`pop2` vs `pop4`).

## Environment

- Compiler version: Version: 0.8.13+commit.abaa5c0e.Darwin.appleclang
- Target EVM version (as per compiler settings): NA
- Framework/IDE (e.g. Truffle or Remix): NA
- EVM execution environment / backend / blockchain client:  NA
- Operating system: MacOS

## Steps to Reproduce
Run `solc test.sol`

```solidity
pragma solidity =0.8.13;
contract Test {
  struct MyStruct{
    uint num;
    bytes32 info;
  }
  MyStruct[] myStruct;
  function add(uint a, bytes32 b) external {
    myStruct.push(MyStruct({num: a, info: b}));
  }
  function pop1() external returns(MyStruct[] memory myMemoryStruct) {
   if (myStruct.length != 0) {
     myMemoryStruct = new MyStruct[](1);
     myMemoryStruct[0] = myStruct[myStruct.length - 1];
     delete myStruct[myStruct.length - 1];
   }
  }
  function pop2() external returns(MyStruct[] memory myMemoryStruct) {
   if (myStruct.length != 0) {
     myMemoryStruct = new MyStruct[](1);
     (uint a, bytes32 b) = myStruct[myStruct.length - 1];
   }
  }

  function pop3() external returns(MyStruct[] memory myMemoryStruct){
   if (myStruct.length != 0) {
     myMemoryStruct = new MyStruct[](1);
     myMemoryStruct[0] = myStruct.pop();
   }
  }

  function pop4() external returns(MyStruct[] memory myMemoryStruct) {
   if (myStruct.length != 0) {
      myMemoryStruct = new MyStruct[](1);
     (uint a, bytes32 b) = myStruct.pop();
   }
  }
}

```
```
Error: Different number of components on the left hand side (2) than on the right hand side (1).
  --> test.sol:21:6:
   |
21 |      (uint a, bytes32 b) = myStruct[myStruct.length - 1];
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Type struct Test.MyStruct storage ref is not implicitly convertible to expected type uint256.
  --> test.sol:21:6:
   |
21 |      (uint a, bytes32 b) = myStruct[myStruct.length - 1];
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Type tuple() is not implicitly convertible to expected type struct Test.MyStruct memory.
  --> test.sol:28:26:
   |
28 |      myMemoryStruct[0] = myStruct.pop();
   |                          ^^^^^^^^^^^^^^

Error: Different number of components on the left hand side (2) than on the right hand side (0).
  --> test.sol:35:6:
   |
35 |      (uint a, bytes32 b) = myStruct.pop();
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ekpyron** [comment]
``.pop`` on storage arrays does not return anything... that is to say an empty tuple, which is nothing... so you're trying to take this nothing (i.e. an empty tuple) and assign it to something :-)... that's how those error messages are to be understood, but yeah, maybe we should consider rephrasing them...

**Comment by 0xalpharush** [comment]
Is it just not implemented or it will never return anything? If the latter, I'd expect a warning like ".pop()` is not a member of dynamic storage array".

**Comment by ekpyron** [comment]
``someArray.pop();`` works just fine and is implemented and removes the last element of the array.
It just does not return the value of the removed element.
