### ISSUE TITLE
Broken link for Yul optimizations steps

### ISSUE THREAD

**Issue by 0xalpharush** [ethereum/solidity#13025]
## Page
https://github.com/ethereum/solidity/blob/develop/docs/internals/optimizer.rst

## Abstract
This link is dead.
> Available abbreviations are listed in the [Yul optimizer docs](https://github.com/ethereum/solidity/blob/develop/docs/internals/yul.rst#optimization-step-sequence).
## Pull request

If someone can point indicate where this should link, I'll submit a PR. I don't see the "optimization step sequence" heading on this page either https://github.com/ethereum/solidity/blob/develop/docs/yul.rst

**Comment by hrkrshnn** [comment]
Thanks! https://docs.soliditylang.org/en/v0.8.13/yul.html#optimization-step-sequence is the correct link.

**Comment by cameel** [comment]
In addition to that we should use an actual reference there. It broke without us notiticing because it uses the `#` URL syntax to link to a header in the rendered document.
