### ISSUE TITLE
[Optimizer] Does not respect returndatacopy specification

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#13039]
The optimizer incorrectly optimizes out `returndatacopy` calls in the following contracts. Found by fuzzing and inputs from @hrkrshnn 

```
contract C {
  fallback() external
  {
    assembly
    {
      returndatacopy(0, 0, 1)
    }
  }
}
```

and

```
contract C {
  fallback() external
  {
    assembly
    {
      returndatacopy(0, 1, 0)
    }
  }
}
```

From matrix chat

@hrkrshnn quotes from the spec

> This opcode has similar semantics to CALLDATACOPY, but instead of copying data from the call data, it copies data from the return data buffer. Furthermore, accessing the return data buffer beyond its size results in a failure; i.e. if start + length overflows or results in a value larger than RETURNDATASIZE, the current call stops in an out-of-gas condition. In particular, reading 0 bytes from the end of the buffer will read 0 bytes; reading 0 bytes from one-byte out of the buffer causes an exception.

So technically the optimizer should retain the returndatacopy call so that it would run out of gas.

**Comment by bshastry** [comment]
I formatted the edge-cases into semantic test inputs as follows

```
contract C {
  fallback() external
  {
    assembly
    {
      returndatacopy(0, 1, 0) // read zero bytes past end-of-returndata-buffer
    }
  }
}
// ====
// compileViaYul: also
// ----
// (): 7 -> FAILURE
```

```
contract C {
  fallback() external
  {
    assembly
    {
      returndatacopy(0, 0, 1) // read 1 byte past end-of-returndata-buffer
    }
  }
}
// ====
// compileViaYul: also
// ----
// (): 7 -> FAILURE
```

Both correctly fail *without* optimization but incorrectly pass *with* optimization. Also both legacy and IR optimizers behave identically i.e., remove the returndatacopy call.

**Comment by ekpyron** [comment]
@hrkrshnn mentioned in chat that IR codegen only uses ``returndatasize`` as length argument of ``returndatacopy``, so that should be fine. Given that @chriseth in chat:
> we should check if the last argument is returndatasize() and only remove it in that case
