### ISSUE TITLE
Allow signed ** unsigned

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1303]
As @yaronvel [suggested](https://github.com/ethereum/solidity/issues/1246#issuecomment-256781769), `signed ** unsigned == signed` operations do make sense and can be implemented by the `EXP` instruction.

This issue keeps track of adding these in Solidity.  We need first to convince the type checker that the left operand and the right operand of `**` can be of different types.

**Comment by anurag-git** [comment]
@pirapira @axic , I would like to have look at it, please provide some pointers to start.

**Comment by chriseth** [comment]
@axic actually I don't think this would be a "good first issue". If you think otherwise, can you give some guidance, please?

**Comment by chriseth** [comment]
Implemented in #7055
