### ISSUE TITLE
Payable modifier not required to send funds to constructor

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1304]
Should the constructor need to be `payable` in order for it to receive funds during deployment? Currently this is not the case.

Not that important because there are always other ways to put funds into an account, but I think it should be possible to write a contract that can not receive funds during deployment.

**Comment by axic** [comment]
I thought I've already commented here. I think it should require the `payable` modifier just as the fallback requires is.

**Comment by chriseth** [comment]
Is this really a breaking change instead of a bug?

**Comment by axic** [comment]
The documentation doesn't explicitly mention it with constructors, so it could qualify as either.
