### ISSUE TITLE
Misleading text in contract docs: `Take care to assign it from somewhere that is the same contract type`

### ISSUE THREAD

**Issue by itslittlefrankie** [ethereum/solidity#13053]
## Page

https://docs.soliditylang.org/en/v0.8.13/types.html#contract-types

## Abstract

The Contract Type section is stating: 

> If you declare a local variable of contract type (MyContract c), you can call functions on that contract. **Take care to assign it from somewhere that is the same contract type.**

The impression I got from reading this was that the compiler does not check if you assign a contract that is the same contract type. After checking in Remix, I realized the compiler verifies that the assigned value is of the same contract type, so why is this sentence necessary?

**Comment by cameel** [comment]
The paragraph just above is talking about conversions, including a conversion through `address` and this sentence essentially warns you about situations like this:
```solidity
ERC721 nft;
...
IERC20 token = IERC20(address(nft));
```
This could be valid if you know that your deployed `ERC721` also implements `IERC20` but the compiler cannot verify that and it could just as well be a mistake.

I agree that this sentence could be clearer. Feel free to submit a PR if you want to clarify this.
