### ISSUE TITLE
[YUL Optimizer] Optimize gas consumption in Solidity

### ISSUE THREAD

**Issue by sergiuiacob1** [ethereum/solidity#13058]
## Abstract

As the official Solidity documentation states, "the optimizer is under heavy development". I'm currently working on my Master's Thesis, which focuses on optimizing Solidity code by analysing the Control Flow Graphs built from Solidity Code. I'm looking to work on something that will be worth it.

## Motivation

The more efficient the bytecode is, the lower the cost of deploying and running a Smart Contract on the blockchain. If the optimizer gets better, all of the contracts will decrease in size / increase in efficiency / both. Worst case, they'll use the same amount of gas to deploy / run.

## Specification

I'm thinking of working with the YUL IR, since the docs also specify that the "new" optimizer works with YUL. I'm looking to do some high level optimizations that the current optimizer does not do / does not support. For example, this code
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

contract VariableLoop {
    function declareVariableInsideLoop() public pure {
        for (uint i = 1; i <= 1000; i++) {
            uint x = i * i;
        }
    }

    function declareVariableOutsideLoop() public pure {
        uint x;
        for (uint i = 1; i <= 1000; i++) {
            x = i * i;
        }
    }
}
```
uses `420223` gas to run `declareVariableInsideLoop`, and `415250` to run `declareVariableOutsideLoop`. From my experiments, the solc compiler (v 0.8.14) (with `--optimize-runs=200`) optimized the code to `237215` gas to run `declareVariableInsideLoop` vs `232242` gas to run `declareVariableOutsideLoop`.
The conclusion is that `declareVariableInsideLoop` will still use more gas. I'm thinking of starting with such a use case, where I'd extract declared variables inside loops and declare them before the loop block.

I'm looking for any advice / direction / requests on what could be improved, optimized and how (but mostly I'd figure out the how).

P.S. I hope this is the right place to start such a discussion. If not, please redirect me to a more appropriate place. It would also be great to get in touch with somebody working in the Solidity team to see how I can make a difference.

**Comment by hrkrshnn** [comment]
Can you try benchmarking with --via-ir? It should be the same in both cases already.

**Comment by sergiuiacob1** [comment]
> Can you try benchmarking with --via-ir? It should be the same in both cases already.

I've set up a truffle project, set the solc optimizer configuration in `truffle-config.js` to the following:
```
  compilers: {
    solc: {
      version: "0.8.14",      // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
       optimizer: {
        "yul": true,
        enabled: true,
        runs: 200
       },
       "viaIR": true
      //  evmVersion: "byzantium"
      // }
    }
  },
```
then deployed the `VariableLoop` contract above. The numbers remained the same:
```
truffle(develop)> VariableLoop.deployed().then(function (c) {return c.declareVariableInsideLoop.estimateGas()})
417223
truffle(develop)> VariableLoop.deployed().then(function (c) {return c.declareVariableOutsideLoop.estimateGas()})
412250
```

Is the compiler config sufficient? That should be equivalent to `solc --optimize --via-ir ...`, right?

**Comment by hrkrshnn** [comment]
@sergiuiacob1 this is weird. I looked at the optimized IR. Both functions are optimized into a single one! I wonder if truffle is taking in the parameter properly.

Can you try testing it on foundry? It definitely handles `viaIR` properly.

**Comment by sergiuiacob1** [comment]
> @sergiuiacob1 this is weird. I looked at the optimized IR. Both functions are optimized into a single one! I wonder if truffle is taking in the parameter properly.
> 
> Can you try testing it on foundry? It definitely handles `viaIR` properly.

`foundry.toml` is 
```
[default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

optimizer = true
via_ir = true
yul = true
optimizer_runs = 200
```

`declareVariableInsideLoop`: `119194` gas, `declareVariableOutsideLoop`: `119211` gas

Full output:
```
sergiuiacob@Sergius-MacBook-Pro foundry-project % forge build --contracts src/variable_declaration_loops.sol
[⠊] Compiling...
[⠢] Compiling 7 files with 0.8.14
[⠆] Solc 0.8.14 finished in 3.11s
Compiler run successful (with warnings)
warning[2072]: Warning: Unused local variable.
 --> /Users/sergiuiacob/solidity-optimization-with-control-flow-graphs/foundry-project/src/variable_declaration_loops.sol:7:13:
  |
7 |             uint x = i * i;
  |             ^^^^^^



sergiuiacob@Sergius-MacBook-Pro foundry-project % forge run src/variable_declaration_loops.sol --sig "declareVariableInsideLoop()"
[⠒] Compiling...
[⠢] Compiling 1 files with 0.8.14
[⠆] Solc 0.8.14 finished in 33.91ms
Compiler run successful (with warnings)
warning[2072]: Warning: Unused local variable.
 --> /Users/sergiuiacob/solidity-optimization-with-control-flow-graphs/foundry-project/src/variable_declaration_loops.sol:7:13:
  |
7 |             uint x = i * i;
  |             ^^^^^^



Script ran successfully.
Gas used: 119194
== Return ==
== Logs ==
sergiuiacob@Sergius-MacBook-Pro foundry-project % forge run src/variable_declaration_loops.sol --sig "declareVariableOutsideLoop()"
[⠊] Compiling...
[⠢] Compiling 1 files with 0.8.14
[⠆] Solc 0.8.14 finished in 32.56ms
Compiler run successful (with warnings)
warning[2072]: Warning: Unused local variable.
 --> /Users/sergiuiacob/solidity-optimization-with-control-flow-graphs/foundry-project/src/variable_declaration_loops.sol:7:13:
  |
7 |             uint x = i * i;
  |             ^^^^^^



Script ran successfully.
Gas used: 119211
== Return ==
== Logs ==
```

**Comment by hrkrshnn** [comment]
That looks correct. The difference you are seeing is because of dispatch affecting gas. See slides 11 to 13 in https://hrkrshnn.com/t/devconnect.pdf 

Closing this for now. Feel free to reply if you have any questions.
