### ISSUE TITLE
Seaport compile time in `--via-ir`

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#13050]
https://github.com/ProjectOpenSea/seaport uses `--via-ir`

The compile times are rather disappointing at ~10 minutes. Need to use it as a benchmark and tune performance of `solc`.

This is particularly about foundry. `forge build`.

**Comment by axic** [comment]
This is not a problem on my side. With Hardhat it takes ~15 seconds with legacy pipeline and ~60 seconds with `--via-ir`.

**Comment by hrkrshnn** [comment]
@axic Was mainly about foundry. Updated the issue. Hardhat is fine on my end as well.

**Comment by cameel** [comment]
@hrkrshnn That sounds like something you'd get in a debug build. Is that on a M1 Mac or a Linux ARM system? If so, where is Foundry getting the binary from?

**Comment by hrkrshnn** [comment]
@cameel This is on x86 linux. Note that foundry can find dependencies and compile things in parallel. This was running on 16 threads on my machine. 

I think foundry uses https://github.com/roynalnaruto/svm-rs to fetch solidity.

```bash
cargo install svm-rs
svm install 0.8.13
objdump -h ~/.cargo/bin/solc | grep debug
```

gives me
```
 30 .debug_aranges 000007e0  0000000000000000  0000000000000000  00065570  2**4
 31 .debug_info   00032cf0  0000000000000000  0000000000000000  00065d50  2**0
 32 .debug_abbrev 00001e29  0000000000000000  0000000000000000  00098a40  2**0
 33 .debug_line   00021221  0000000000000000  0000000000000000  0009a869  2**0
 34 .debug_str    000080f6  0000000000000000  0000000000000000  000bba8a  2**0
 35 .debug_line_str 000007bd  0000000000000000  0000000000000000  000c3b80  2**0
 36 .debug_loclists 0006c37d  0000000000000000  0000000000000000  000c433d  2**0
 37 .debug_macro  00002a56  0000000000000000  0000000000000000  001306ba  2**0
 38 .debug_rnglists 0000af55  0000000000000000  0000000000000000  00133110  2**0
```
I'm worried if the shipped binaries are debug builds now :(

Seems like `.cargo/bin/solc` is the wrapper for solc from https://github.com/roynalnaruto/svm-rs/tree/master/src/solc The debug symbols seems to be for the rust binary?

**Comment by cameel** [comment]
> The debug symbols seems to be for the rust binary?

Seems so. I just ran `objdump -h` in a loop on all Linux binaries from solc-bin and there are no debug symbols in any of them.

> Note that foundry can find dependencies and compile things in parallel. This was running on 16 threads on my machine.

That explains why it was so fast :P I more often get compilation times like 20-30 min on complex projects on debug builds. That's why I'm usually using release binaries rather than my local builds when working with ext tests.
