### ISSUE TITLE
Remove workarounds for ethers 5.6.2+ and `getStorageAt()` from external tests

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13051]
https://github.com/ethers-io/ethers.js/discussions/2849 and https://github.com/NomicFoundation/hardhat/issues/2709 are now fixed. We added workarounds in #13027 and #13020. Now we should be able to revert them.

**Comment by matheusaaguiar** [comment]
There are still 3 gnosis test cases failing in CI in every preset [1071808](https://app.circleci.com/pipelines/github/ethereum/solidity/24371/workflows/b68233fd-de80-4756-a47c-20a08ef21787/jobs/1071808). I was able to reproduce it locally, though I had to force hardhat version to 2.9.6 and apply the chainId workaround as discussed in [euler-xyz/euler-contracts#119](https://github.com/euler-xyz/euler-contracts/issues/119#issuecomment-1133367182). I guess it still has to do with the problem in [ethers-io/ethers.js#2849](https://github.com/ethers-io/ethers.js/discussions/2849).

**Comment by cameel** [comment]
Does Uniswap pass? It failed for me when I tried removing the workaround in #13063.

**Comment by matheusaaguiar** [comment]
> Does Uniswap pass? It failed for me when I tried removing the workaround in #13063.

I will test.

**Comment by matheusaaguiar** [comment]
Uniswap fails if workaround is removed.
