### ISSUE TITLE
Ensure every string in the AST has a location associated with it

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#13064]
This is a requirement for many LSP features, most recently the `semanticTokens` support for highlighting and the `rename` support.

Currently, the following AST types have strings which have no source location available for them:

* `IdentifierPath`: the individual strings that make up the path are only a vector of `ASTString`s, no location information for the individual parts are available
* * [x] https://github.com/ethereum/solidity/pull/13182
* * [x] https://github.com/ethereum/solidity/pull/13183
* `MemberAccess`: member has no location
*  * [x] https://github.com/ethereum/solidity/pull/13184
* `FunctionCall`: The list of argument names for a named call contains no source code locations
* * [x] https://github.com/ethereum/solidity/pull/13185

**Comment by chriseth** [comment]
I think we should introduce a new node type similar to identifier. For me, an identifier is a stand-alone string that refers to a symbol - this is also what is reflected in `IdentifierAnnotation`.

**Comment by Marenz** [comment]
What about an identifier path? Often the individual elements are symbols, though, probably not always. Should that be made of `Identifiers` or of that new tpye?

**Comment by christianparpart** [comment]
> What about an identifier path? Often the individual elements are symbols, though, probably not always. Should that be made of `Identifiers` or of that new tpye?

Maybe something similar to:

```cpp
class IdentifierPath....
{
    ....
private:
    std::vector<Identifier> m_identifiers;
};
```
?

**Comment by Marenz** [comment]
Exactly, or the suggested new type :)

**Comment by cameel** [comment]
Maybe we should have a separate node representing a keyword (or a reserved identifier meant to be used as a keyword - since not all of them are technically globally reserved keywords).
