### ISSUE TITLE
soltest in CI should print errors to stderr in addition to the XML report

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13066]
[`soltest.sh`](https://github.com/ethereum/solidity/blob/develop/.circleci/soltest.sh) passes `--logger=JUNIT` option to soltest, which makes it produce an XML report that CircleCI can then analyze to list failed test cases on the TESTS tab (see [CircleCI docs > Collecting test data](https://circleci.com/docs/2.0/collect-test-data/)). Currently using this option means that errors are no longer printed to stderr, which makes analyzing the output harder. Especially combined with bugs like #12862, which break processing of the XML report (and we actually still haven't fixed that completlely, it happens in some cases).

The task here is to make it print both to stderr and to the XML file, possibly with an extra option (though I think it would be fine as the default behavior too).

soltest is based on [Boost Test](https://www.boost.org/doc/libs/1_79_0/libs/test/doc/html/index.html) which, I think, does not have options for printing to both out of the box. Please check that first though - if it does, solving this could be as simple as specifying an extra option in `soltest.sh`. Otherwise it will have to be implemented manually in C++.

**Comment by matheusaaguiar** [comment]
I checked the [documentation](https://www.boost.org/doc/libs/1_79_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/logger.html) and it is possible to use more than one logger at the same time. I executed a [minimal example](https://www.boost.org/doc/libs/1_79_0/libs/test/doc/html/boost_test/intro.html) with both options and it worked as expected.
So, it is as you said, just adding the extra option in `soltest.sh`:  `--logger=HRF` . The default level is `error` and the default sink is `stdout` for that option. Should the sink be changed to `stderr` or explicity set to default?

**Comment by cameel** [comment]
Great. It's exactly what we need.

>  Should the sink be changed to `stderr` or explicity set to default?

I think that these errors should go to `stdout` since they're part of the expected output of the command, not a problem in `soltest` execution. E.g. if you wanted to capture the output you'd want both passing and failing tests in it.
