### ISSUE TITLE
Override of interface method with public field does not work for array types

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13077]
## Description

Consider the following interface and implementation:

**`ITest.sol`:**

```
pragma solidity 0.8.14;

interface ITest {
    function val0() external view returns (address);
    function val1() external view returns (address[] memory);
}
```

**`Test.sol`:**

```
pragma solidity 0.8.14;

import "./ITest.sol";

contract Test is ITest {
    address public val0;
    address[] public val1;
}
```

Field `val0` correctly overrides `function val0()`. However field `val1` does not:

```
TypeError: Contract "Test" should be marked as abstract.
 --> contracts/main/Test.sol:5:1:
  |
5 | contract Test is ITest {
  | ^ (Relevant source part starts here and spans across multiple lines).
Note: Missing implementation: 
 --> contracts/main/ITest.sol:5:5:
  |
5 |     function val1() external view returns (address[] memory);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error HH600: Compilation failed
```

Changing `address[] memory` to `address[] calldata` does not fix the problem.

## Environment

- Compiler version: 0.8.14
- Target EVM version (as per compiler settings): Unknown
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

## Steps to Reproduce

Compile the above code.

The only workaround appears to be:

**`Test.sol`:**

```
pragma solidity 0.8.14;

import "./ITest.sol";

contract Test is ITest {
    address public val0;
    address[] internal _val1;
    function val1() external view returns (address[] memory) { return _val1; }
}
```

**Comment by cameel** [comment]
This is because the signature of a getter that the compiler generates for an array is different than for a value type. Such a getter does not return the whole array. Instead it returns only one field at a time and has the index as an argument.

If you want to override `val1()` with with a public state variable, the interface should look like this:
```solidity
interface ITest {
    function val0() external view returns (address);
    function val1(uint index) external view returns (address);
}
```
