### ISSUE TITLE
Can someone check if my smart contract is secure?

### ISSUE THREAD

**Issue by CyniCatz** [ethereum/solidity#13080]
I need to know if we can be hacked after the minting, and if the ownership can be transferred to a different account. Here is the link to the contract:
https://etherscan.io/address/0x5d8d955560b1d67af02d1a7f54c01afc3325d2f7#code

**Comment by cameel** [comment]
This is a bug tracker for the compiler. It's not the right place for support questions. If you need help, the [#solidity](https://gitter.im/ethereum/solidity) channel on gitter might be a better place to ask.
