### ISSUE TITLE
Interface inheritance does not seem to add functions to type(Interface) object

### ISSUE THREAD

**Issue by maurelian** [ethereum/solidity#13095]
## Description

I _think_ this is a bug, unless I'm reading the docs wrong for interface inheritance: 

> Interfaces can inherit from other interfaces. This has the same rules as normal inheritance.

Source: [solidity/interfaces.rst at develop · ethereum/solidity](https://github.com/ethereum/solidity/blob/develop/docs/contracts/interfaces.rst)

## Environment

- Compiler version: 0.8.14
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): just using `solc` for this
- EVM execution environment / backend / blockchain client: N/A
- Operating system: macos

## Steps to Reproduce

([Runnable code here](https://github.com/maurelian/solidity-sandbox/blob/da1ec147fdce06080fc3c0ee764d6cb06dc62737/src/test/7_interfaceId.sol)).

When I run the compiler on the following code, I get the error listed in the comments below:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.14;

interface Foo {
    function x() external;
}

interface Bar is Foo {
    function y() external;
}

contract AccessBarX {
    function test() public {
      // This works
      Bar.y.selector;

      // This fails with "Error: Member "x" not found or not visible after argument-dependent
      // lookup in type(contract Bar)."
      Bar.x.selector;
    }
}
```

However if I comment out the problematic line, and run `solc --hashes` on the code, I see that
`x()` is included in the the interface:

```shell
======= src/test/7_interfaceId.sol:Bar =======
Function signatures:
0c55699c: x()
a56dfe4a: y()

======= src/test/7_interfaceId.sol:Foo =======
Function signatures:
0c55699c: x()
```

This issue also seems to affect `interfaceId` generation, ie. using forge and DSTest with same code above, the `assertEq()` call fails

```
contract Test_InterfaceId is DSTest {

  function test_IdGeneration() public {
    assertEq(
      type(Bar).interfaceId,
      Bar.x.selector ^ Bar.y.selector
    );
  }
}
```

**Comment by axic** [comment]
I think is partially by design, because this way ERC-165 support can be easily implemented -- otherwise having `is IERC165` on a contract would make it impossible to use `.interfaceId`.

**Comment by maurelian** [comment]
Ahh, you're right and it is actually documented

> A bytes4 value containing the [EIP-165](https://eips.ethereum.org/EIPS/eip-165) interface identifier of the given interface I. This identifier is defined as the XOR of all function selectors defined within the interface itself - excluding all inherited functions.

https://docs.soliditylang.org/en/latest/units-and-global-variables.html#meta-type

**Comment by silasdavis** [comment]
This is dreadful footgun. It means you need to know/care about whether an interface definition uses inheritance if you refactor your code you will break ERC-165 support.

The ERC-165 interface is defined by the resultant set of functions in the ABI which has nothing to do with the inheritance structure.

> otherwise having is IERC165 on a contract would make it impossible to use .interfaceId.

Do you mean because you'd also mix in the `supportsInterface` function id into the hash? I know some interfaces are specced to exclude this so I see your point, but really it ought to be included anyway.

Also it's trivial to XOR out an interface you don't want since XOR is its own inverse.

I really think this ought to be considered a bug, sadly changing the implementation would break backwards compatibility.
