### ISSUE TITLE
Most error messages describe objects representing errors and events as function types

### ISSUE THREAD

**Issue by nishant-sachdeva** [ethereum/solidity#13106]
## Description
Continued from #12896  . Created the issue as requested in https://github.com/ethereum/solidity/pull/13005#discussion_r877162339

In custom errors like the following : 
```
interface MyInterface {
    error MyCustomError();
}
```

The compiler mistakenly considers `MyInterface.MyCustomError` to be of type `function() pure` instead of type `error`. The latter is what should be used.

Running `solc test.sol` for the following code 
```
interface MyInterface {
    error MyCustomError(uint256, bool);
}

contract Test {
    function test() public returns(bytes4) {
        return (MyInterface.MyCustomError);
    }
}
```
gives the following error
```
Error: Return argument type function (uint256,bool) pure is not implicitly convertible to expected type (type of first return variable) bytes4.
 --> test.sol:7:16:
  |
7 |         return (MyInterface.MyCustomError);
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by cameel** [comment]
@nishant-sachdeva I wouldn't call this a bug. The type is not incorrect, we do assign function types to events and errors. I'd say that changing this is just a small enhancement.

So is this the only affected message? The point here was to do a more comprehensive check to identify as many as possible and tweak them all in bulk.

I mean, alternatively we can also leave it up to whoever will be implementing this to find them all.

**Comment by timweri** [comment]
I'm currently working on this and it's my first time contributing to solidity. I have a question about what `(143-176)` means in [explicit_conversion_error_to_bytes4.sol](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/syntaxTests/conversion/explicit_conversion_error_to_bytes4.sol)?

I've been digging through the docs but no luck

**Comment by timweri** [comment]
@cameel Hi. The PR is ready for a review. I think I found all the messages that need to be tweaked.
