### ISSUE TITLE
Better error needed when trying to call an `external` function from the same contract

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13132]
## Description

When trying to call an `external` function from the same contract, the error message generated is:

```
DeclarationError: Undeclared identifier. "functionName" is not (or not yet) visible at this point.
```

This is confusing as a newcomer to Solidity. It took me forever to realize that `external` functions cannot be called by other functions within the same contract. The assumption I made was that `external` was a superset of `public`, but actually it is the other way around.

I would suggest reporting an error like the following in this situation:

```
DeclarationError: Undeclared identifier. "functionName" is not visible at this point, because it is marked as external, not public.
```

Similarly trying to call a `private` function from a subcontract should probably show the same sort of warning that the function is marked `private` and not `internal`, although the reason for lack of visibility is far more obvious in that situation.

## Environment

- Compiler version: 0.8.14

**Comment by ekpyron** [comment]
Yes, that's definitely true. There could very well be a duplicate for this one already, but in any case, it shouldn't be too hard to improve the error message here and we should do it.

To be a bit more precise, the case is the following:
```
contract C {
        function f() external { }
        function g() external {
                f();
        }
}
// ----
// DeclarationError 7576: (67-68): Undeclared identifier. "f" is not (or not yet) visible at this point.
```

The idea would be to change the error message in this case. I'd suggest something along the lines of:

```
// DeclarationError 7576: (67-68): Undeclared identifier. "f" is an external function and thereby not visible unqualified. Either make ``f`` public to be able to use ``f`` as an internal function or use ``this.f`` to refer to ``f`` as an external function.
```

The place to start would probably be ``NameAndTypeResolver.cpp:L521``, where several cases of "invisible" declarations are collapsed - there it should be able to specially mark external functions and report that via ``registerDeclaration`` to the ``DeclarationContainer``, which would allow for the ``DeclarationContainer`` to report more information to ``NameAndTypeResolver`` to be passed down ultimately to ``ReferencesResolver.cpp:L133`` where the error is produced. It may take some time to look through the inter-dependencies of all these, but ultimately it should be easy to store the required information and use it for improving the error message.

**Comment by lukehutch** [comment]
`and thereby not visible unqualified` doesn't seem grammatical...

If this is some compiler-internal terminology, it should be surfaced in a more comprehensible way to the public via the error message.

**Comment by ekpyron** [comment]
Just to explain: Technically, a name/identifier being ``qualified`` means that its scope is explicitly mentioned, whereas ``unqualified`` means it does not mention its scope, i.e. ``f`` is unqualified, ``this.f`` is qualified...  but yeah, may be better to use some lighter phrasing for the message.

**Comment by mr-abims** [comment]
> contract C {
>         function f() external { }
>         function g() external {
>                 f();
>         }
> }

Using your example one way that i know solidity support to call an external function is by using this format

         function f() external {
        
         }

        function g() public {
                this.f();
        }
