### ISSUE TITLE
Missing custom errors from library assembly in smart contract ABI

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13149]
## Description

Sometimes custom errors are not included in the smart contract ABI based on their direct usage in Solidity code.

This case works fine:
```solidity
contract A {
    error Foo();

    function f() external {
        revert Foo();
    }
}
```

This case works fine too:
```solidity
contract A {
    error Foo();

    function f() external {
        bytes4 exception = Foo.selector;
        assembly {
            mstore(0, exception)
            revert(0, 4)
        }
    }
}
```

But using the same approach in the library does not work properly:
```solidity
library L {
    error Foo();

    function g() internal {
        bytes4 exception = Foo.selector;
        assembly {
            mstore(0, exception)
            revert(0, 4)
        }
    }
}

contract A {
    function f() external {
        L.g();
    }
}
```

`Foo` error is not included in the smart contract ABI, which I believe is a mistake. What about unconditionally including all libraries' custom errors in ABI?

## Environment

- Compiler version: 0.8.14

**Comment by ekpyron** [comment]
Related to https://github.com/ethereum/solidity/pull/10996 and its linked issues.

**Comment by cameel** [comment]
This is actually by design - which does not mean we can't change it - but the idea was that the ABI should contain only the events that are actually emitted and errors that are actually used - in addition to all events and errors defined within the contract. For example if you just do `L.Foo;`, i.e. refer to an error (or an event) without actually doing a revert, it won't appear in the ABI either.

So I guess we could treat it as a feature request. I can see how it can be useful in your example but it could also be misleading. E.g. you could refer to the selector but use a completely different value in the revert.

@chriseth Do you think this would be a good change?

**Comment by k06a** [comment]
Mentioned this issue here: https://ethereum.stackexchange.com/a/142809/3032

**Comment by sebastiantf** [comment]
I am seeing the same issue with errors defined outside the contract and used within the contract, but within assembly block, both with `CustomError.selector` or the raw selector:

```solidity

error Foo();

contract A {
    function f() external {
        bytes4 exception = Foo.selector;
        assembly {
            mstore(0, exception)
            revert(0, 4)
        }
    }

    function f() external {
        assembly {
            mstore(0, 0xbfb4ebcf) // Foo()
            revert(0, 4)
        }
    }
}
```

And declaring the errors within the contract seem to have increased gas usage than having them outside in some cases

**Comment by ekpyron** [comment]
The compiler can't magically guess the intention of inline assembly - if you want the compiler to output the use of an error, you need to emit it by the high-level mechanisms the compiler provides for that, i.e. by a ``revert Foo();``.

**Comment by k06a** [comment]
@ekpyron but compiler could detect error selector access:
```
bytes4 exception = Foo.selector;
```

**Comment by ekpyron** [comment]
That's a false positive, though - there is no telling what happens with the selector.
The interesting question is: why are you emitting these errors in inline assembly in the first place?

**Comment by sebastiantf** [comment]
Emitting these errors from inline assembly seem to clock lesser deployment gas than otherwise. 
Bytecode does seem to change, although its size seem to remain the same

**Comment by ekpyron** [comment]
Yeah, I'd recommend against micro-optimizing revert cases. Optimized via-IR compilation should be closer to the assembly version - optimized via-IR compilation with a high ``--optimize-runs`` value I'd expect to yield identical cost.

**Comment by ekpyron** [comment]
Ah, sorry, you said deployment gas cost - there is actually indeed an easy optimization we can do for these cases, I'll take a quick look at that. In general, we'd prefer to fix the reason for people resorting to inline assembly and I think we can improve the situation here.

**Comment by k06a** [comment]
Sometimes error needs to happen in the middle of assembly block, it’s not related to micro optimizations.

**Comment by k06a** [comment]
@ekpyron regarding reasoning for stepping back to assembly I have latest example: safeBalanceOf written in assembly cost 200 gas less than external call in solidity: https://github.com/1inch/solidity-utils/blob/b51b9348f703f7612fda7573d3cb476bccb34383/contracts/libraries/SafeERC20.sol#L26-L43 (PR https://github.com/1inch/solidity-utils/pull/83)

**Comment by k06a** [comment]
Same for `ecrecover`, somehow using assembly saves hundreds of gas: https://github.com/1inch/solidity-utils/blob/b51b9348f703f7612fda7573d3cb476bccb34383/contracts/libraries/ECDSA.sol#L21-L40

**Comment by ekpyron** [comment]
Yeah, there's multiple things we can do for those cases as well (returning to scratch space for small static return data sizes and some fusing of conditions in the optimizer), but I won't get around to do anything about them in time for tomorrow's planned release - but I'm making a note of those cases and more optimizations we can do in them.

**Comment by ItsNickBarry** [comment]
OpenZeppelin has made an attempt to pass errors between functions, but they had to use enums: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fda6b85f2c65d146b86d513a604554d15abd6679/contracts/utils/cryptography/ECDSA.sol#L169-L178

In my own implementation of the same library, I wrapped the errors in functions: https://github.com/solidstate-network/solidstate-solidity/blob/a61388fda0a6e8701cf20688e62b5eb9d777fe67/contracts/cryptography/ECDSA.sol#L214-L240

Both would be improved by passing error selectors instead and reverting via assembly.

#15388 would be a workaround.  But I still think accessing an error selector in Solidity should be enough to include it in the ABI.

> That's a false positive, though - there is no telling what happens with the selector.

What might be done with an error selector other than revert?

**Comment by k06a** [comment]
Hope one day Solidity would support Rust-like enums, meanwhile all `errors` could be considered as enums btw

**Comment by deluca-mike** [comment]
My workaround for this issue is as follows:

```solidity
interface IMyCastLibraryErrors {
    error InvalidInput();
}

library MyCastLibrary {
    function uint256ToUint64(uint256 x) internal returns (uint64 y) {
        if (x > type(uint64).max) revert IMyCastLibraryErrors.InvalidInput();

        return uint64(x);
    }
}

interface IMyContract is IMyCastLibraryErrors {
    function foo(uint256 x) external;
}

contract MyContract is IMyContract {
    uint64 value;

    function foo(uint256 newValue) external {
        value = MyCastLibrary.uint256ToUint64(newValue);
    }
}
```

Even if it would be nice if the ABI of `MyContract` automatically inherited all the custom errors of `MyCastLibrary`, what I really want is for `IMyContract` to be the complete interface that includes these errors, so there doesn't seem to be a tenable built-in solution.

If you get in the habit of defining interfaces for everything, including for your libraries that have custom errors and events, then you can inherit them as you would anything else.

**Comment by michprev** [comment]
The decision not to include such errors in ABI leads to a really bad UX.

For example, Uniswap v4 uses a custom logic for crafting revert data (https://github.com/Uniswap/v4-core/blob/d153b048868a60c2403a3ef5b2301bb247884d46/src/libraries/Hooks.sol#L101).
Another example is Lido CSM (https://github.com/lidofinance/community-staking-module/blob/d9c45973004316ecb38554cf793d5019d1d56883/src/lib/SSZ.sol#L10-L12). The declared errors are not even referenced in this case.

In both cases, development tools such as [Wake](https://github.com/Ackee-Blockchain/wake) cannot resolve the errors and have to interpret them like this:

<img width="3206" height="292" alt="Image" src="https://github.com/user-attachments/assets/cd16dd5e-6074-4341-a92a-7072412060db" />
