### ISSUE TITLE
Better Debugging Data (in particular for via-IR codegen)

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#13157]
We probably already have issues regarding this, but I'm creating a new one after our recent tooling call, since we're hoping to continue the discussion.

Requests for helpful modifications to the compiler I noted down:
- Easy way to set up the compiler to perform no optimizations other than stack-to-memory.
  - Related idea was to generate code for a ficticious EVM version with unlimited stack access (resp. codegen for https://eips.ethereum.org/EIPS/eip-663)
  - Problematic: stack-to-memory is via-IR-only at the moment.
-  Stack Variable Maps
   - Probably sufficient to emit stack layout on each assignment, the rest can be tracked.
   - Could also emit a map at the same granularity as source maps.
   - The compiler has readily available information about the locations of Yul variables.
      - We can try and resolve them to Solidity variables ourselves.
      - Or have tooling first refer to Yul and resolve from the source location comments in Yul further to Solidity
- Extended Source Maps
   - Multi-source-maps for deduplicated bytecode. Need to specify a format. Could have an index into the continuing source map at each jump. Might get tricky on collapsing already collapsed code further.
   - Control Flow Boundaries / Basic Block Boundaries
      - Again easily available in the compiler referring to Yul;
      - We could again resolve further to Solidity in the compiler or leave that to tooling

General question for the future of via-IR debugging:
Should debugging data and future source maps relate EVM bytecode directly to Solidity code or first to Yul code only (or both?)? Yul to Solidity should be possible via the source location comments in the Yul code.

General issue:
We need to ensure high quality of source maps; it may help to actually emit the utility yul code; might not be an actual issue in the most recent compilers.

General plan:
Keep the discussion alive; reach out to more participants; meet again; ideally have tooling prepare some draft for the best format for the information above, or have solc emit a prototype version.

Previous iteration on this by @alcuadrado: https://nomiclabs.notion.site/Solidity-debugging-symbols-Initial-proposal-b70fedc2c7914498bd7ed8e27db63883
Related issues (non exhaustive): https://github.com/ethereum/solidity/issues/9332

**Comment by cd1m0** [comment]
One question about the Multi-source-maps proposal. Is it guaranteed that at every jump the index of the called deduplicated function can be determined at compile time?

**Comment by cd1m0** [comment]
Also to add to this, there was the concern of not being able to use the source map to figure out the number of instructions. This is used to decode the bytecode. This in itself is a little hacky, as it assumes that the solidity compiler never mixes code and data (i.e. all data is at the end). So perhaps it would be useful if the compiler emitted enough metadata to enable determining what is code and what is data in the bytecode? This way making decoding easy, and untying your guy's hands to mix code and data if you wish in the future?

**Comment by ekpyron** [comment]
> Also to add to this, there was the concern of not being able to use the source map to figure out the number of instructions. This is used to decode the bytecode. This in itself is a little hacky, as it assumes that the solidity compiler never mixes code and data (i.e. all data is at the end). So perhaps it would be useful if the compiler emitted enough metadata to enable determining what is code and what is data in the bytecode? This way making decoding easy, and untying your guy's hands to mix code and data if you wish in the future?

https://github.com/ethereum/solidity/issues/9332 was meant to address that, I'm not entirely sure what stalled it.

**Comment by ekpyron** [comment]
> One question about the Multi-source-maps proposal. Is it guaranteed that at every jump the index of the called deduplicated function can be determined at compile time?

It'll take some consideration how such source maps would actually have to look like.
It may be better and more-future proof not to annotate the jumps with an index into source maps, but the pushes of the jump targets. In legacy code generation, currently, most of the time the disambiguation at jumps should work, but it won't for internal function dispatch. That could be solved by annotating the pushed jump target labels instead.
In via-IR code generation, it should currently be possible to disambiguate everything at the jump itself, but we may want to implement jump tables at some point, then it would get rather tricky (we have a draft PR for that in https://github.com/ethereum/solidity/pull/12978 - even though doing that may complicate analysis and debugging in general). Such jump tables would further complicate things significantly: we may end up with several jump targets packed into a single slot and then use shifts and masks on that before actually jumping... so a universal and future-proof solution for this may indeed be non-trivial to come up with.

**Comment by ekpyron** [comment]
We have too many issues like this - it's getting confusing. I'm closing this in favour of https://github.com/ethereum/solidity/issues/13157 (while hereby linking them together)

**Comment by ekpyron** [comment]
I meant https://github.com/ethereum/solidity/issues/13720 :-).
