### ISSUE TITLE
[soltest] Distinguish code size-induced cost from runtime gas cost in tests.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#13160]
Currently, the semantics test expectations contain full transaction gas costs without distinguishing between cost due to code size vs runtime gas cost. While this is a bit tricky to distinguish properly, it'd be good to try and separate them to make the gas values more meaningful.

We could probably have ``EVMHost`` (``test/EVMHost.*``) track the cost associated with code size on each and every creation during a transaction (just accummulating the costs of multiple contract creations), then have the ``SemanticTest``s subtract that from the runtime gas costs, while reporting the code size separately. (We could also try to account for the cost of the bytecode size in the payload of the creation transactions, but it'd be an improvement even without that.)

Then we'd have to adjust ``scripts/gas_diff_stats.py`` to list code size changes and runtime gas changes separately (and also make scripts/gas_diff_stats.py itself executable, it's mildly annoying that it's not).

**Comment by cameel** [comment]
Just noticed that this was a duplicate of #14477. It was implemented in #14843.
