### ISSUE TITLE
`pure` functions can read storage

### ISSUE THREAD

**Issue by duncancmt** [ethereum/solidity#13174]
## Description

It is possible to declare a `pure` function that reads storage

## Environment

- Compiler version: 0.8.15
- Target EVM version (as per compiler settings): London
- Framework/IDE (e.g. Truffle or Remix): Foundry
- EVM execution environment / backend / blockchain client: Hardhat
- Operating system: Fedora 34

## Steps to Reproduce

```solidity
pragma solidity ^0.8.15;

contract Demo {
  string internal _thing = "I am a string";

  function thing() external pure returns (string memory) {
    string storage ref;
    assembly ("memory-safe") {
      ref.slot := _thing.slot
    }
    return ref;
  }
}
```

Calling `Demo.thing()` returns `"I am a string"`.

---

I encountered this bug while investigating [my Stack Exchange question](https://ethereum.stackexchange.com/questions/130470/copying-strings-and-bytes-from-memory-to-storage-via-storage-references). Perhaps they're related? I would appreciate any opinion y'all can give.

**Comment by duncancmt** [comment]
This is related to #12820, which was closed with little explanation

**Comment by Marenz** [comment]
I checked our code and it seems for identifiers we don't do any check inside assembly blocks, only for function calls and instructions..

**Comment by duncancmt** [comment]
The assembly in this function is `pure`. The problem is that the implicit conversion from `storage` to `memory` is `view`.

**Comment by cameel** [comment]
This looks like another instance of #11573.

**Comment by cameel** [comment]
Closing in favor of #11573.
