### ISSUE TITLE
Struct typeIdentifier location

### ISSUE THREAD

**Issue by anton-cs** [ethereum/solidity#13186]
## Environment

- Compiler version: 0.8.15+commit.e14f2714.Linux.g++
- Operating system: Arch

## Steps to Reproduce

```solidity
struct A {
    uint a;
}

contract C{

    type B is uint256;

    function foo() external{
        A memory a;
        B c;
    }
}

```
Following snipper will produce ast json for the `A memory a`:

```json
{
    "constant": false,
    "id": 10,
    "mutability": "mutable",
    "name": "a",
    "nameLocation": "109:1:0",
    "nodeType": "VariableDeclaration",
    "scope": 16,
    "src": "100:10:0",
    "stateVariable": false,
    "storageLocation": "memory",
    "typeDescriptions": {
        "typeIdentifier": "t_struct$_A_$3_memory_ptr",
        "typeString": "struct A"
    },
    "typeName": {
        "id": 9,
        "nodeType": "UserDefinedTypeName",
        "pathNode": {
            "id": 8,
            "name": "A",
            "nodeType": "IdentifierPath",
            "referencedDeclaration": 3,
            "src": "100:1:0"
        },
        "referencedDeclaration": 3,
        "src": "100:1:0",
        "typeDescriptions": {
            "typeIdentifier": "t_struct$_A_$3_storage_ptr",
            "typeString": "struct A"
        }
    },
    "visibility": "internal"
}

```
The typeDescriptions.typeIdentifier is `"t_struct$_A_$3_storage_ptr"`. The type definition of struct defaults to `storage` location, even though it can be defined even outside of the contract. Can you please say what is the rational behind this and if there are any other types that behave similarly?

**Comment by ekpyron** [comment]
The type name itself is not associated with any data location, so there needs to be a default - which is arbitrarily chosen to be storage.

The underlying related issue here, is that data locations are tied to variable declarations, not to the type, so as far as the compiler is concerned it sees:
```
Type memory a;
```
where ``Type`` is merely ``A``.
Rather than seeing
```
Type a;
```
where ``Type`` is ``A memory``.

Does this answer your question? Do you have any particular practical problem caused by this?

**Comment by anton-cs** [comment]
Thanks for the explanation. 
No problems with that. Just small misunderstanding. Now it is clear that storage location is another attribute in conjunction to the type, and not really part of the type.
