### ISSUE TITLE
[Legacy codegen] Incorrect logging data possibly due to memory corruption via inline assembly

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#13181]
For the test below, the correct log data would be `0x20, 0x01, "f"`. However, legacy codegen returns `"f", 0x20, 0x01, "f"` i.e., an extra `"f"` is prefixed.

```
contract C {
  event ev1(bytes ep0);
  fallback() external {
  assembly {
    calldatacopy(0, 5, 0x60)
  }
  emit ev1(bytes("f"));
 }
}
// ====
// compileViaYul: also
// ----
// () ->
// ~ emit ev1(bytes): "f", 0x20, 0x01, "f"
```

**Comment by ekpyron** [comment]
```
    calldatacopy(0, 5, 0x60)
```
Overwrites the free memory pointer to zero, which is undefined behaviour, so in that sense this is a fuzzing challenge, but not a bug :-).

I.e. writing any random values to memory at ``[0, 0x40]`` is sound, but writing anything weird (like zero in this case) to memory offset ``0x60`` is expected to break subsequent solidity code.
