### ISSUE TITLE
Bug: Delegatecall doesn't work with non-standard types.

### ISSUE THREAD

**Issue by pedrommaiaa** [ethereum/solidity#13197]
## Description

When using `delegatecall` to call a function from another contract, it fails whenever using non-standard types.

## Environment

- Compiler version: 0.8.15+commit.e14f2714.Darwin.appleclang
- Target EVM version (as per compiler settings): Latest
- Framework/IDE (e.g. Truffle or Remix): Foundry
- EVM execution environment / backend / blockchain client: Foundry
- Operating system: MacOS M1

## Steps to Reproduce

I created a repo where I reproduce the bug: https://github.com/pedrommaiaa/solBug

As an example, this works:
```
address(this).delegatecall(abi.encodeWithSignature("deposit(address,uint256)", address(asset), amount));
```

but this doesn't:
```
address(this).delegatecall(abi.encodeWithSignature("deposit(ERC20,uint256)", ERC20(asset), amount));
```

**Comment by hrkrshnn** [comment]
ERC20 is not a "standard" type. Anyway, we recommend using `abi.encodeCall(deposit, ERC20(asset), amount)` instead of `abi.encodeWithSignature...`
