### ISSUE TITLE
Event inheritance in natspec (documentation)

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/solidity#13199]
## Abstract
Events, in natspec documentation, are not inherited like the methods are.

## Motivation
I'm building a Typescript output for solidity. A little bit like Typechain. When inheriting ERC20 from openzeppelin for example I can generate TsDoc from solc's devdoc output for the methods, but not for the events.

Example of output I would like to achieved using the devdoc output of the ERC20: 
```typescript
  events: {
    /**
     * Emitted when the allowance of a `spender` for an `owner` is set by a call to {approve}. `value` is the new allowance.
     */
    Approval: (owner: string, spender: string, value: BigNumber) => void;
    /**
     * Emitted when when an amount of token is sent from one address to another
     * @param from the address the tokens are taken from
     * @param to the address the tokens are moved to
     * @param value the amount of tokens transfered
     */
    Transfer: (from: string, to: string, value: BigNumber) => void;
  };
```

## Specification
Best would be for the events to work like methods : https://docs.soliditylang.org/en/v0.8.13/natspec-format.html#inheritance-notes 

## Backwards Compatibility
Backwards  Compatible

## Related issues
In #8911, @Marenz mentioned why events are not inherited from the parent class. Though I think this would greatly help for tools that want to generate dev-related documentation from the contract.

**Comment by leonardoalt** [comment]
@Marenz was the spec for this ever agreed upon? Is https://github.com/ethereum/solidity/issues/8911#issuecomment-631496750 the final spec?

**Comment by Marenz** [comment]
I don't think there was an official agreement, I just explained why it doesn't work for events as it is currently.

**Comment by cameel** [comment]
Event Natspec is inherited in userdoc so I think skipping it in devdoc was an unintentional omission when #9338 was implemented.
