### ISSUE TITLE
Access `this` in constructor should be allowed for non-calls stuff

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13203]
Access `this` in constructor should be allowed for non-calls.

## Description

Compiler produces warning on `this` usage in constructor, while it could be related to non-call stuff.

## Environment

- Compiler version: 0.8.15

## Steps to Reproduce

```solidity
contract C {
    constructor() {
        bytes4 a = this.f.selector;
    }
    function f() external {
    }
}
```
-->
```
Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
  --> C.sol:3:1:
   |
25 |         bytes4 a = this.f.selector;
   |                    ^^^^
```

**Comment by cameel** [comment]
This is less of a bug and more of a limitation of analysis in this case - it's not fine grained enough and lumps many harmless cases together with others that could be actual problems. We can and should improve it for selectors though. We already have an issue for that so I'm going to close this one in favor of #11540.

**Comment by k06a** [comment]
Found way to resolve this issue by replacing `this.f.selector` with `C(address(0)).f.selector`
