### ISSUE TITLE
SMTChecker: BMC timeout seems to not working

### ISSUE THREAD

**Issue by acmRecife** [ethereum/solidity#13202]
Context: I am using SMTChecker on a Solidity v0.8.10 contract

Environment: MacOS Monterey, V12.4, 8GB RAM

SMTChecker config:

modelChecker: {
        engine: 'bmc',
        targets: ['overflow'],
        timeout: 10, // <=== I tried 100 as well
        showUnproved: true
      }

BMC seems to not paying attention to the timeout. CHC worked as expected!

Could you please help me on this? Thanks!

**Comment by leonardoalt** [comment]
Hi @acmRecife , what do you mean by "not paying attention to the timeout"? Is it taking longer?
Also, it's hard to help here without the code that it's being used on. Would you be able to provide a reproducible snippet?

**Comment by acmRecife** [comment]
Yes, @leonardoalt . Taking too long... even for a timeout of 10. But the code I think is big and complex. Unfortunately I cannot share it :-( But CHC takes around 4min with a timeout of 50.... Best!

**Comment by acmRecife** [comment]
Finally, I got an answer from the BMC analysis...

An unexpected error occurred:

Error: Command failed: /Users/me/Library/Caches/hardhat-nodejs/compilers/macosx-amd64/solc-macosx-amd64-v0.8.10+commit.fc410830 --standard-json

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: null,
  killed: false,
  signal: 'SIGKILL',
  cmd: '/Users/me/Library/Caches/hardhat-nodejs/compilers/macosx-amd64/solc-macosx-amd64-v0.8.10+commit.fc410830 --standard-json'
}
npx hardhat compile --force  7801,23s user 7946,61s system 65% cpu 6:42:42,26 total

**Comment by Marenz** [comment]
@acmRecife With the given information we can't really help you or fix the problem.
We need something reproducable for as or at the very least a more complete description of your problem. "Taking too long" is very vague and lacks context.

What are you doing?
What do you expect to happen?
What actually happens?
Can you create a minimal code example of your problem?

Answering those questions can help us.
