### ISSUE TITLE
Refactor to use assembly as real intermediate language

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1320]
Currently, Solidity does not have a real intermediate language in the sense that this language could be stored in a file and re-compiled. If we had such an intermediate language, it would be easier to verify the correctness of compilation and compilation result, especially in connection with macros ( #1319 ), because the correctness of macros could be established one by one.

The "Solidity inline assembly" language already provides a step in that direction (and was also planned for that purpose). The core of the refactoring would happen between the compiler context and the Assembly object. The compiler context would not directly generate AssemblyItems but rather assembly text (or a lightly parsed representation of it) and this assembly text would then be transformed into AssemblyItems at the assembly stage. There are some missing items in transitioning from the C++ Assembly object into using the assembly language as intermediate language, which have to be added as syntactical elements or just keywords to assembly:

- [x] sub-assemblies (especially for distinguishing between runtime and creation time context)
- [ ] linkable libraries
- [x] the error tag
- [ ] program size
- [ ] source location

**Comment by VoR0220** [comment]
^yes.

**Comment by chriseth** [comment]
Further potential feature for inline assembly (especially important for macros):
`(x, y, z) := f(a, b,c)` - if `f` returns more than one stack element, those can be assigned to variables, also available in the form `let (x, y, z) := f(a, b, c)`

**Comment by chriseth** [comment]
I think we should spend some minutes talking about style before merging https://github.com/ethereum/solidity/pull/1327/files and we should probably define all the items mentioned above.

Generally about the style: Opcodes are lowercase and do not use camelcase. Should we follow that? What about prefixing system-level objects/routines/opcode-like symbols with e.g. a dollar sign? 
- sub-assemblies:
  `subtag: assembly ["VM"] { ... }`, at the end of the code, compiles the given assembly (in its own context), and appends it to the data section of the code

`dataSize(subtag)`: pushes the size of the sub-assembly of the given name

`dataOffset(subtag)`: pushes the offset of the sub-assembly of the given name
- linkable libraries:
  `linkerSymbol("SymbolName")` pushes a not yet specified linker symbol - note that currently, only 20 byte symbols are supported, we could change it to `linkerSymbol("SymbolName", size)` or `linkerSymbol[size]("SymbolName")` in the future
- error tag:
  Since opcodes are lowercase, I'm a bit worried about making it uppercase. Decision: `invalidJumpLabel`
- program size:
  `bytecodeSize`
- source location:
  In a comment after the opcode. We should find a condensed format similar to the ones used in the source mappings (only re-mention changes). I am not sure whether we should also replace the source name by the source index, as we can omit the source name most of the time, I would say it is fine.
  As far as the syntax is concerned:
  `/* "sourceName":start:length */`
  _before_ the inline assembly object it applies to, or `// "sourceName":start:length` _after_ the object it applies to.

**Comment by chriseth** [comment]
In many cases, it is also beneficial to declare real syntactic macros (as opposed to functions). This is helpful for example when we are considering different backends: WASM has direct support for loops and functions, so these should be retained in the intermediate language by e.g. using syntactic macros. The actual definition of the macro can be different depending on the backend.

We might go as far as rust's macros, or just use `{` and `}`-based arguments:

Example macro usage:
```
let x := 2
$for { let i := 1 } { lt(i, 10) } { i := add(i, 1) } {
  x := mul(x, i)
}
```

Arguments for macros are pseudo-blocks delimited by a balanced pair of `{` / `}`, although these braces do not create scope levels (because of that, `i` is visible inside the body.

Definitions of macros might look like this:

```
macro_def $for(init, cond, post, body) {
  {
    init
    $for_continue:
    jumpi($for_break, iszero(cond))
    body
    post
    jump($for_continue)
    $for_break:
  }
}
```

Note that the macro even supports `break` and `continue` be suitable other macros that jump to the respective labels. The only thing that has to be solved for that is stack height management.

**Comment by chriseth** [comment]
Having thought about it, it might make more sense to rather include a native loop construct into assembly. Syntax:
```
while condition {
  ...
}
```

**Comment by chriseth** [comment]
Discussion with @pirapira revealed that we should probably go for for loops that support break and continue.
Syntax (proposal):
```
for pre cond post {
 ...
}
```
pre and post can be blocks or single instructions (also in functional notation), cond has to be functional with one return value. Pre already creates a new scope.

**Comment by VoR0220** [comment]
@chriseth can you give me an example of the above?

**Comment by chriseth** [comment]
Not sure I understand you, but the following would zero out a memory array byte by byte:
```
// input: start, size
for {let i := 0} lt(i, size) {i := add(i, 1)} {
  mstore8(add(start, i), 0)
}
```

**Comment by pirapira** [comment]
I thought the `for` loop was desired in the inline assembly, and in that case, the `for` loops make more sense in a separate issue.

**Comment by VoR0220** [comment]
agreed with @pirapira either way it's a nice proposal.

**Comment by chriseth** [comment]
"switch" constructs are also really helpful for an intermediate language: https://github.com/ethereum/solidity/issues/1485

**Comment by chriseth** [comment]
Closing since the scope of this is way too large.
