### ISSUE TITLE
Solidity array allocation pre-erasing

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13218]
In order to allocate new arrays Solidity erases this memory with loop of `MSTORE`s. Same can be achieved with just `CALLDATACOPY` from huge offset like `SHL(255, 1)`.

Initial idea came from this tweet: https://twitter.com/k06a/status/1541392410546159617

## Abstract

Replace:
```solidity
for (uint i = 0 ; i < size; i += 32) {
    MSTORE(ptr + i, 0)
}
```
With this:
```solidity
CALLDATACOPY(ptr, SHL(255, 1), size)
```

## Motivation

It will be much cheaper in terms of gas (no loop overhead) and byte code will be much smaller.

## Backwards Compatibility

Should be fully compatible in terms of behaviour.

**Comment by hrkrshnn** [comment]
The compiler does this partially. The trick is to use `calldatacopy(ptr, calldatasize(), size)`. But I think it can be used for even more cases, so that needs to be investigated.

**Comment by axic** [comment]
I hope these quirks can be removed in the future (zero extension and memory expansion ignoring high offsets is nasty).

**Comment by k06a** [comment]
I see `CALLDATACOPY(*, CALLDATASIZE(), *)` happens in some cases, but not in all of them

**Comment by brockelmore** [comment]
related: https://github.com/ethereum/solidity/issues/13089

**Comment by axic** [comment]
I'm interested in a temperature check about a potential [`mzero` instruction](https://ethereum-magicians.org/t/mzero-instruction/11713).

**Comment by sambacha** [comment]
> I'm interested in a temperature check about a potential [`mzero` instruction](https://ethereum-magicians.org/t/mzero-instruction/11713).

is this been accepted 4 shanghai ?
