### ISSUE TITLE
Allow declaration of multiple variables in first clause of `for` statement

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13212]
## Abstract

Currently it is impossible to declare more than one variable in the first clause of a `for` statement, e.g.

```solidity
for (uint256 i = 0, len = array.length; i < len; ++i) { ... }
```

## Motivation

The above pattern saves gas, while saving polluting the namespace of the currently-possible alternative:

```solidity
uint256 len = array.length;
for (uint256 i = 0; i < len; ++i) { ... }
```

## Specification

Please allow multiple declarations of variables of the same type in the first clause of a for-loop, as is possible in C/C++/Java.

## Backwards Compatibility

No issues, since this is a superset of the current functionality.

**Comment by ekpyron** [comment]
This is worth a thought, but I'd not assign it high priority (unfortunately, we have a rather large backlog of non-critical design decisions).

**Comment by emretepedev** [comment]
Yes, this is exactly what I need.

@ekpyron @nikola-matic

**Comment by ekpyron** [comment]
Note that this has no effect on stack too deep errors whatsoever. (If you experience those, have you tried optimized via-ir code generation?)

Also note that none of this will save any gas either, this is purely cosmetics.

**Comment by duralsh** [comment]
it is not purely cosmetics, it prevents scope leakage
