### ISSUE TITLE
Add unitialized variable warning when for-loops contain uninitialized variables

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13214]
## Description

The following compiles and runs fine in Solidity without any warning:

```solidity
for (uint256 i; i < 10; ++i) { ... }
```

Whereas the following should probably be required:

```solidity
for (uint256 i = 0; i < 10; ++i) { ... }
```

I believe all variables are zero by default in Solidity, so the current behavior is not surprising, but the first of the two examples above gives an uninitialized variable warning in Slither, which is probably appropriate. (Often uninitialized variables are symptomatic of bugs in code, so they should always be initialized.)

Related question -- in the second code example above, is `i = 0` duplicating the work of zeroing out `i`, since `uint256 i` already zeroes it out?

## Environment

- Compiler version: 0.8.14
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client: Hardhat
- Operating system:  Linux

## Steps to Reproduce

See above

**Comment by timweri** [comment]
I'm not sure what the decision is on implementing this but I would like to take a jab at it.

However, regarding the question, I believe `i = 0` does not zero `i` twice:

`explicit_zero.sol`:
```solidity
contract Test {
    uint256 num;
    function f() public {
        for (uint256 i = 0; i < 10; i++) {
            num++;
        }
    }
}
```

`default_zero.sol`:
```solidity
contract Test {
    uint256 num;
    function f() public {
        for (uint256 i; i < 10; i++) {
            num++;
        }
    }
}
```

Running
```sh
 diff --unified \
    <(solc explicit_zero.sol --optimize --ir-optimized --debug-info none) \
    <(solc default_zero.sol --optimize --ir-optimized --debug-info none)
```
gives
```diff
@@ -1,18 +1,18 @@
 Optimized IR:
-/// @use-src 0:"explicit_zero.sol"
-object "Test_22" {
+/// @use-src 0:"default_zero.sol"
+object "Test_21" {
     code {
         {
             let _1 := memoryguard(0x80)
             mstore(64, _1)
             if callvalue() { revert(0, 0) }
-            let _2 := datasize("Test_22_deployed")
-            codecopy(_1, dataoffset("Test_22_deployed"), _2)
+            let _2 := datasize("Test_21_deployed")
+            codecopy(_1, dataoffset("Test_21_deployed"), _2)
             return(_1, _2)
         }
     }
-    /// @use-src 0:"explicit_zero.sol"
-    object "Test_22_deployed" {
+    /// @use-src 0:"default_zero.sol"
+    object "Test_21_deployed" {
         code {
             {
                 mstore(64, memoryguard(0x80))
@@ -48,7 +48,7 @@
                 ret := add(value, 1)
             }
         }
-        data ".metadata" hex"a2646970667358221220a099cb50fdae23f7d7946d610696635d5469af5c2c0012df3db7491309b1a3b064736f6c637827302e382e31362d646576656c6f702e323032322e372e362b636f6d6d69742e62326163306461640058"
+        data ".metadata" hex"a2646970667358221220984d16232d19482b09e7c6908a65c1774e912b1094f611887b022aa5eae57ffe64736f6c637827302e382e31362d646576656c6f702e323032322e372e362b636f6d6d69742e62326163306461640058"
     }
 }
```

The IR for initializing `i` is the same:
```yul
                    ....
                    let _1 := 0
                    if eq(0x26121ff0, shr(224, calldataload(_1)))
                    {
                        if callvalue() { revert(_1, _1) }
                        if slt(add(calldatasize(), not(3)), _1) { revert(_1, _1) }
                        let var_i := _1
                    ....
```

**Comment by StrongerXi** [comment]
Hey @timweri are you still working on this?

**Comment by timweri** [comment]
> Hey @timweri are you still working on this?

Hi. No I didn't really start. I was waiting for some maintainers to comment on the necessity of this before putting in the time. But it's all yours.

**Comment by ekpyron** [comment]
I don't think this should be a warning - variables declared in for loops are not special in any way, so we'd either have to warn about *all* uninitialized variables, independently of whether they occur in a for-loop or not, or none of them (including those in a for loop) (see also: https://github.com/ethereum/solidity/pull/13334#pullrequestreview-1057311873).

Also I'm not quite sure, why this reporting a warning in slither is an argument for it becoming a compiler warning. Arguably, there is call for avoiding uninitialized variables in general, but this is exactly the kind of opinionated style question that I'd think is best located in an external static analysis tool and *not* in the compiler. The behaviour of uninitialized variables is generally well-defined (except for storage pointers, in which the compiler does have a special checking logic), so as far as I'm concerned there is no need for the compiler to warn about it.

**Comment by lukehutch** [comment]
OK, that all makes sense. Should this bug be closed then?

**Comment by ekpyron** [comment]
Alright, we quickly talked about this in our meeting today and decided to indeed close it, so I'm closing!
