### ISSUE TITLE
Decode number of tokens and token contract address from msg.data (ERC-20)

### ISSUE THREAD

**Issue by maksimp13** [ethereum/solidity#13225]
I have a smart contract with just a fallback function and some logic.

I want users to send their tokens directly to the smart contract and do some smart contract logic.

I've implemented fallback function and smart contract now is able to receive ERC20 tokens, but i also want to track how much tokens user sent.

I thought that its possible to do via decoding of `msg.data` in fallback in the following way:

```
fallback() external payable {
        (sig, tokenAddress, amount) = abi.decode(msg.data, (bytes4, address, uint256));
    }
```

I tried different things but nothing works: 

```
fallback() external payable {
        (tokenAddress, amount) = abi.decode(msg.data[4:], (address, uint256));
    }
```

Can't decode even selector, just for test:

```
fallback() external payable {
        sig = abi.decode(msg.data[:4], (bytes4));
    }
```

Is it possible to implement this decoding somehow? I'm not able to rush user and execute another functions, i need to receive ERC20 tokens only via direct send.

**Comment by Marenz** [comment]
This is not the right place for Solidity programming help so I am going to close this.
About your issue though, read up more about it here

https://docs.soliditylang.org/en/latest/contracts.html#index-12

The docs even mention (in the first note on that link) your specific usecase, hope that helps!
