### ISSUE TITLE
Cross platform compilation issues

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#1322]
I have been relying on the cross platform builds of solc for compiling solidity contracts, OSX builds fairly easily with a couple of brew installs `make solc` works well.

However i'm having trouble compiling on Linux and Windows, although I can probably grab a ppa binary for linux if I really needed it.

After installing jsoncpp and boost libs Windows is throwing errors while running `cmake ..` with errors like cannot find pthread.h

I've tried to use the emscriptem js file but it presents its own set of problems.

Is there a plan (or resources) to maintain the binary releases going forward?

**Comment by chriseth** [comment]
We are constantly building solidity on windows and linux, so I would like to see the issues you are facing. I can try to see whether we can improve on our binary release process.

**Comment by slothbag** [comment]
First issue, is it compatible with Boost 1.6.2?

```
CMake Warning at C:/Program Files/CMake/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
```

**Comment by chriseth** [comment]
I think version `106200` is version `1.62.0` which should be supported. I think this error is rather about boost not being found on your system.

**Comment by slothbag** [comment]
After a lot of trial and error I have managed to get solc to build on Linux and Windows.

On Windows this line https://github.com/ethereum/solidity/blob/develop/libdevcore/CommonData.cpp#L24 causes an error, comment it out and windows builds fine.

**Comment by chriseth** [comment]
Thanks, fixed in #1348

**Comment by axic** [comment]
@slothbag can this be closed? Is latest Solidity working for you?

**Comment by slothbag** [comment]
@axic Yeah Solidity is compiling well. Will close this issue.

Thanks

**Comment by axic** [comment]
@slothbag thanks!
