### ISSUE TITLE
Add a method to erase the data in mapping 

### ISSUE THREAD

**Issue by jayendramadaram** [ethereum/solidity#13236]
I was writing smart contracts and at some point like traditional programming , I want to reset the mapping to its initial stage so far till now there are no such method to delete or erase contents of mapping. Please issue this feature

**Comment by hrkrshnn** [comment]
This is not really feasible in the EVM. For one, the `mapping` doesn't know about what locations are active (you need something like enumerable mappings to do this). Secondly, erasing slots is gas intensive and easily lead to DOS issues.

Closing this.
