### ISSUE TITLE
I have mapping function error

### ISSUE THREAD

**Issue by dev-tom-0108** [ethereum/solidity#13231]
I have coded like this:
```js
struct TreasurySend {
    address reciever;
    uint256 amount;
}
mapping (address => mapping ( TreasurySend => bool)) private checkTransfer;
```
And I got this message:
`Only elementary types, contract types or enums are allowed as mapping keys`

**Comment by FudgyDRS** [comment]
You can't map something that has multiple inputs to a single output. Since you were attempting to map a struct to a boolean, I suggest modifying your struct.

```
struct TreasurySend {

    address reciever;

    uint256 amount;

    bool check;

}

mapping (address => TreasurySend) private transfer;
```

**Comment by hrkrshnn** [comment]
@FudgyDRS's recommendation seems to be a way around the problem. 

An alternative is to have `mapping (uint => mapping(bytes32 => uint))` where the `bytes32` is something like `keccak256(abi.encode(TreasurySend(...)))`.

**Comment by dev-tom-0108** [comment]
Great! thanks these are good methods to solve my issue
Thanks
