### ISSUE TITLE
Inlining Functions That Only Use Variables Passed As Argument

### ISSUE THREAD

**Issue by toongeorges** [ethereum/solidity#13248]
## Abstract

This is a feature request for the optimizer to inline functions in a specific case.

If a function only use variables passed as argument, inlining the function does not increase the variables on the stack and therefore cannot cause a "Stack too deep" error.  It should be reasonably straightforward to inline such functions.  If such a function is private or internal and is only used once, it would always be more efficient to inline this function.

This feature request was suggested in a comment in #12782

## Motivation

The issue describes a specific case in which inlining functions is always more efficient.

## Specification

Whenever a private or internal function is only used once and this function uses only variables that are passed as argument, the function should be inlined.

## Backwards Compatibility

This feature request does not change the language and does not impact backward compatibility.

**Comment by toongeorges** [comment]
I made a prototype project at https://github.com/toongeorges/cryptoshares/
You could use the code in https://github.com/toongeorges/cryptoshares/blob/main/solidity/contracts/base/CorporateActions.sol as a test case:
there is one function `executeCorporateAction` that conditionally calls one of several other functions.  I did not want to write these functions inline.  The compiler however should inline these functions (if the feature is implemented).

**Comment by thedavidmeister** [comment]
this is relevant, please reopen it, there are common patterns like creating a custom type which is a "zero cost abstraction" but the moment you write functions for the custom type, i believe it adds jumps, etc. which is not zero cost currently

**Comment by petdomaa100** [comment]
+1
