### ISSUE TITLE
Transaction-local storage

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [ethereum/solidity#13254]
## Abstract

I want to propose a new conceptual storage area I will refer to as "transaction-local storage" (viz thread-local storage) that a user can store values into at any point within the lifetime of a transaction, but that is destroyed at the end of the transaction.

Transaction-local storage can be stored in regular storage, but the compiler would zero-out all transaction-local fields the first time the contract is called within a transaction.

## Motivation

My immediate usecase is that I want to set a flag before a call to a function in an external contract is made, and I want to prevent my contract from updating state whenever that flag is set. The flag's lifecycle should last until the transaction is finalized and the block mined, then the flag should be reset.

I don't see any way to accomplish this currently, since there is no `tx.id` or similar to distinguish unique transactions from each other.

## Specification

Contract fields could be modified with "transactionLocal", e.g.

```
bool private transactionLocal myFlag;
```

And if this modifier were present, the field would be zeroed out at the beginning of each transaction.

I do not know what underlying EVM mechanisms would be needed to implement this.

## Backwards Compatibility

100% backwards compatible.

**Comment by hrkrshnn** [comment]
This is similar to what transient storage eip is proposing.

**Comment by hiroshi-yamamoto-dublr** [comment]
> This is similar to what transient storage eip is proposing.

@hrkrshnn You're right, I think the transient storage EIP would solve exactly the problem I described -- and I assume that there is no way for Solidity to implement this without that EIP being approved and implemented in the EVM. I'll close this feature request. Thanks for the pointer!
