### ISSUE TITLE
Ability to create memory array of calldata slices

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13258]
## Abstract

I wish to be able to store `bytes calldata` slices in arrays.

## Motivation

Make calldata pointers a first class passengers as other types.

## Specification

Maybe we can pack `calldata`'s `offset` and `length` into single slot?
```
bytes calldata[] memory array;
```

## Backwards Compatibility

Fully compatible

**Comment by k06a** [comment]
I used `Calldata` wrapper to store it in arrays:
```solidity
type Calldata is uint256;

library CalldataLib {
    function wrap(bytes calldata data) internal pure returns (Calldata cd) {
        assembly {
            cd := or(shl(128, data.offset), data.length)
        }
    }

    function unwrap(Calldata cd) internal pure returns (bytes calldata data) {
        assembly {
            data.offset := shr(128, cd)
            data.length := and(cd, 0xffffffffffffffffffffffffffffffff)
        }
    }
}
```

**Comment by Marenz** [comment]
Related: https://github.com/ethereum/solidity/issues/13176

**Comment by k06a** [comment]
@Marenz I’m not sure it’s related. #13176 seems like a bug.

**Comment by k06a** [comment]
@Marenz definitely not related

**Comment by ekpyron** [comment]
Will be fixed as part of https://github.com/ethereum/solidity/issues/13730
