### ISSUE TITLE
Require "context" in free functions if they want to make external calls

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#13268]

**Comment by cameel** [comment]
Do you mean that the "context" would be a parameter of some global object? If a parameter, then this would effectively forbid making external calls inside operator and suffix definitions. Which may or may not be a good thing, but not sure if this was intended.

**Comment by chriseth** [comment]
This is a rough idea about how to fix the issue that free functions can make external calls in the "name" of the currently "active" contract. It is not useful to keep this issue open, but the underlying problem should be fixed at some point.
