### ISSUE TITLE
Chainlink ext test failing with `AssertionError: Expected transaction to be reverted with InvalidSubscription, but other exception was thrown`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13264]
External tests for Chainlink are failing in multiple PRs. For example: [1109949](https://app.circleci.com/pipelines/github/ethereum/solidity/25192/workflows/7117d158-1549-4641-9124-4e5b5d17fbb0/jobs/1109949)
```
352 passing (9m)
  65 pending
  2 failing

  1) VRFCoordinatorV2Mock
       #fundSubscription
         cannot fund a nonexistent subscription:
     AssertionError: Expected transaction to be reverted with InvalidSubscription, but other exception was thrown: TransactionExecutionError: VM Exception while processing transaction: revert with unrecognized return data or custom error
  

  2) VRFCoordinatorV2Mock
       #cancelSubscription
         can cancel a subscription:
     AssertionError: Expected transaction to be reverted with InvalidSubscription, but other exception was thrown: TransactionExecutionError: VM Exception while processing transaction
```

I suspect that this might be due to upstream changes so solution will probably be the same as in #12937.

**Comment by matheusaaguiar** [comment]
I could not reproduce the failing test, either locally or in CI... in any case, I did what you suggested, implementing a fix similar to #12937 .

**Comment by cameel** [comment]
So it does not happen on `develop`?

Maybe it was just a temporary issue. In that case we don't want to disable these tests. Let's keep it open for now in case the error comes back but if it does not, we should probably close the PR.

**Comment by matheusaaguiar** [comment]
It seems that develop is fine. Last [CI run](https://app.circleci.com/pipelines/github/ethereum/solidity/25209/workflows/baf0c36c-3c5c-46a4-8ae0-95e6b11d568e) did not failed and the same happened when I [tested](https://app.circleci.com/pipelines/github/ethereum/solidity/25194/workflows/a543f8fa-08d4-4c92-8ff4-9581b688c4fe) removing the PR proposed changes.

**Comment by cameel** [comment]
ok then. Let's close it. We can always revisit this if it turns out it comes back.
