### ISSUE TITLE
Inline assembly in constructor cannot write to state variables

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1326]
Version: 0.4.5-develop.2016.11.4+commit.dd0879fe.Linux.g++ says

```
Error: Identifier "result" not found, not unique or not lvalue.
```
for the following code
```
                contract C {
                        uint256 result;
                        function C() {
                                assembly {
                                        codesize
                                        =: result
                                }
                        }
                        function f() returns (uint256) {
                                return result;
                        }
                }
```

For comparison, when I write to a variable declared in the constructor function, the code compiles.

**Comment by chriseth** [comment]
Inline assembly cannot access storage values as lvalues in general, it can only access stack variables, and that is by design. In the future, you can do `sstore_uint256(codesize)`, but we are not there yet.

**Comment by pirapira** [comment]
OK.  I was mistaken about what the documentation says.
