### ISSUE TITLE
solc --strict-assembly should have optimization disabled, but it still does some optimization for yul

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/solidity#13284]
## Description

when using strict-assembly optimization should be disabled, but in reality I see some optimization.
A simple example is that unused variables and functions are removed.

I am trying to reverse engineer a contract and this makes it very hard since I want to do it function by function, but the optimizer removes lots of code that is not called and variables that are not changed.

## Environment
Version: 0.8.15+commit.e14f2714.Linux.g++
- Operating system: linux

## Steps to Reproduce
 
```yul
object "runtime" {
    code {
        let v0 := 0
        
        function x(){}
    }  
}
```
```
solc --strict-assembly file.yul
```

this results in no bytecode

**Comment by matheusaaguiar** [comment]
The peephole optimizer is enabled by default regardless of CLI options. In order to turn it off, you have to specify it via the [Standard JSON Interface](https://docs.soliditylang.org/en/v0.8.13/using-the-compiler.html?highlight=peephole#compiler-input-and-output-json-description).

**Comment by krasi-georgiev** [comment]
got it thanks
