### ISSUE TITLE
Chained tuple assignments fail typecheck

### ISSUE THREAD

**Issue by antonper** [ethereum/solidity#13297]
## Description

Compiler throws error when chained tuple assignments present in code.

```
Error: Type tuple() is not implicitly convertible to expected type tuple(int256,int256).
```
Looks like typechecker loses types of rvalues after the evaluation of first assignment.

## Environment

- Compiler version: Version: 0.8.15+commit.e14f2714.Linux.g+

## Steps to Reproduce

```solidity
pragma solidity ^0.8.13;
contract A{

    function foo()
        public
    {
        int a;
        int b;
        int c;
        int d;
        (a, b) = (c, d) = (3, 3);
    }
 }

```

**Comment by timweri** [comment]
Correct me if I'm wrong but this seems like an intended behaviour? I'm not sure what "sequenced assignment" here refers too but I assumed it's talking about the same chained assignment feature mentioned in the issue.

https://github.com/ethereum/solidity/blob/9f34322f394fc939fac0bf8b683fd61c45173674/libsolidity/analysis/TypeChecker.cpp#L1575-L1576

Maybe the error reporting should be better.

**Comment by chriseth** [comment]
Yes, this is intentional.

**Comment by antonper** [comment]
Thanks for clarification.

**Comment by antonper** [comment]
```
Error: Type tuple() is not implicitly convertible to expected type tuple(int256,int256).
```
Can this error be more informative then? This empty tuple does not appear in code, but appears in the message.
@chriseth
