### ISSUE TITLE
Memory allocation in function return

### ISSUE THREAD

**Issue by elshan-eth** [ethereum/solidity#13294]
## Environment

- Compiler version: 0.8.15
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: default
- Operating system: Mac OS

## Steps to Reproduce

When a function returns a memory type, solidity allocates space in memory but does not use it. 

This code has three examples. The first and second examples use 128 bytes in memory. But the last use 64 bytes. I think that all cases should use 64 bytes in memory.

```solidity
    // 128 bytes in memory
    function _a() internal pure returns(Object memory) {
        return Object({ a: 1, b: 2});
    }

    // 128 bytes in memory
    function _b() internal pure returns(Object memory object) {
        return Object({ a: 1, b: 2});
    }

    // 64 bytes in memory
    function _c() internal pure returns(Object memory object) { 
        object.a = 1;
        object.b = 2;
    }
```

**Comment by chriseth** [comment]
Thank you for this issue! This is a design problem in the memory allocator and fixing it is on our roadmap.
