### ISSUE TITLE
Optimise memory allocation for `keccak256` hashes with 32 bytes arguments

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#13290]
The Solidity compiler should automatically use the scratch space if it sees `keccak256(bytes.concat(a, b))` with `a` and `b` being 32 bytes each. Currently, such optimisation can only be done using inline assembly:

```solidity
function _efficientHash(bytes32 a, bytes32 b) private pure returns (bytes32 value) {
    /// @solidity memory-safe-assembly
    assembly {
        mstore(0x00, a)
        mstore(0x20, b)
        value := keccak256(0x00, 0x40)
    }
}
```

**Comment by cameel** [comment]
We already have an issue about a more general optimization that would also cover this case: #12335. It's unlikely that we'll be handling `bytes32` arguments as a special case so I'm going to close this issue. Feel free to post any specific ideas in that other issue.

As for using the scratch space, we might do that in a more general way, based on the total length of the input, but then I'd consider that an implementation detail for whichever solution we implement in the end.
