### ISSUE TITLE
Triggering complex events leads to transfer failure

### ISSUE THREAD

**Issue by PigCharid** [ethereum/solidity#13301]
Call transfer and send to transfer the contract address. When the contract fallback function is triggered, setting an event in the fallback function that returns string, address, uint will cause transfer and send to fail

**Comment by PigCharid** [comment]
```

// SPDX-License-Identifier:MIT
pragma solidity ^0.8;


contract ETHReceiver{
    event Log(uint amount,string func,address to);
    receive()external payable{
        emit Log(msg.value,"func",msg.sender);
    }
    function getBalance()external view returns(uint){
        return address(this).balance;
    }
}
contract SendEth{
    constructor() payable{

    }
    function sendViaTransfer(address payable _to)external  {
        _to.transfer(123);//发的是123个wei
    }
    function sendViaSend(address payable _to)external  {
        bool success = _to.send(123);
        require(success,"send fail");
    }
    function sendViaCall(address payable _to)external  {
       (bool success,)= _to.call{value:123}("");
       require(success,"call fail");
    }
     function getBalance()external view returns(uint){
        return address(this).balance;
    }
}
```

**Comment by PigCharid** [comment]
<div class="remix_ui_terminal_block px-4 py-1 text-break" data-id="block_tx0xdc8fbe8a9f8b7d0f4e584689e23977e4a77a0c224b6516328f9dbf51a665e921" style="box-sizing: inherit; padding: 0.25rem 1.5rem !important; word-break: break-word !important; overflow-wrap: break-word !important; white-space: pre-wrap; font-family: monospace; line-height: 2ch; color: rgb(162, 163, 189); font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 35, 54); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span id="tx0xdc8fbe8a9f8b7d0f4e584689e23977e4a77a0c224b6516328f9dbf51a665e921" style="box-sizing: inherit;">

status | false Transaction mined but execution failed
-- | --
transaction hash | 0xdc8fbe8a9f8b7d0f4e584689e23977e4a77a0c224b6516328f9dbf51a665e921
from | 0x5B38Da6a701c568545dCfcB03FcB875f56beddC4
to | SendEth.sendViaTransfer(address) 0xf5568aF61B089440008183EF92a3296C075A8c15
gas | 3000000 gas
transaction cost | 33593 gas
execution cost | 33593 gas
input | 0x636...a4713
decoded input | { 	"address _to": "0xAAC129A3e6e9f44147951dDD5655d66c312A4713" }
decoded output | {}
logs | []
val | 0 wei

</span></div><div class="px-4 block" data-id="block" style="box-sizing: inherit; padding-right: 1.5rem !important; padding-left: 1.5rem !important; color: rgb(162, 163, 189); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 35, 54); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="text-log" style="box-sizing: inherit;"><pre style="box-sizing: inherit; font-family: Menlo, Monaco, Consolas, &quot;liberation mono&quot;, &quot;courier new&quot;, monospace; font-size: 12px; margin-top: 0px; margin-bottom: 1rem; overflow: auto; display: block; color: inherit;">transact to SendEth.sendViaTransfer errored: VM error: revert.

revert
	The transaction has been reverted to the initial state.
Note: The called function should be payable if you send value and the value you send should be less than your current balance.
Debug the transaction to get more information.</pre></span></div>

**Comment by joshlangs** [comment]
I believe `transfer` only passes 2300 gas by default, which isn't enough to do the `call` + `emit`.

Use `.call` instead

**Comment by PigCharid** [comment]
However, if the event does not return string, uint and address at the same time, then transfer and send can succeed

**Comment by joshlangs** [comment]
Sure, but if I remember correctly, the `CALL` opcode takes 2100 gas?  Something like that, anyway.  `CALL` is how your function is called, and eats away at the 2300 gas that `transfer` passes.

Then `emit` takes like 700 or so, plus each parameter for a `LOG#` opcode

Accessing `msg.value` and `msg.sender` each cost a few gas

And there's gotta be some overload loading your string "func" onto the stack.

...Anyway, that's why `.call("")` exists.  It does the same stuff but sends as much gas as it can, plus has other options.  So... use it!  Noone really uses .send or .transfer any more, for good reason.

**Comment by PigCharid** [comment]
ok   thanku

**Comment by Marenz** [comment]
Thanks for the help @joshlang, closing this then.
