### ISSUE TITLE
Documentation request: hash type

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#1331]
I see a mention of a `hash160` type here: https://github.com/ethereum/wiki/wiki/Solidity-Features#conversion-between-string-and-hash-types

But nothing in the docs http://solidity.readthedocs.io/

Does documentation exist? If not could we get some?

Thanks!

**Comment by axic** [comment]
It was removed from the language a long while ago.

The wiki is also obsoleted by readthedocs as far as I know. Perhaps it should be replaced with a link?

As alternative to hash160, you have `uint160` and `bytes20` (also `address` if it is an address).

**Comment by chriseth** [comment]
The purpose of that wiki page is explained at its beginning. The only alternative to doing nothing I see here is deleting that page, but I'm not sure if that is the way to go. How do people get to that wiki page?

**Comment by axic** [comment]
I would rather include all the details from the wiki in the documentation **and** redirect the wiki to the documentation.

**Comment by chriseth** [comment]
All the details from that wiki page are included in the documentation.

**Comment by aakilfernandes** [comment]
Ah, i missed the big bold warning at the top =).
