### ISSUE TITLE
Deploy Bytecode  Generated by --via-ir Failed 

### ISSUE THREAD

**Issue by hpumengzhao** [ethereum/solidity#13311]
I tested the bytecode generated by IR (compiler version is 0.8.15).

The source code is here: https://paste.ubuntu.com/p/rxH3snBD6Y/

I compile it with the following command to obtain the bytecode.
```
solc --optimize --bin --via-ir  AIOtherdeed.sol
```
I used Ganache (v2.6.0-beta.3) to be the local Ethereum environment.

The key part of my deploy script:
```
deployer_account = '0xEE244D1397baf270C8d9246Cce70B9879c6Bc0e4'
const PRIVATE_KEY = Buffer.from('33c8727299783362b188e150d3405d56314d5bf25896d598affdd1e5010de5a4', 'hex')

var contract = new web3.eth.Contract(ContractABI)

var test = contract.deploy({
    data: bytecode, 
    arguments: []
}).send({
    from: deployer_account, 
    gas: '6721975'
  }, function (e, contract){
   // console.log(e, contract);
   if (typeof contract.address != 'undefined') {
        console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
   }
}).then(instance => {
    console.log(instance.options.address)
})
```
The deployment was revert 
```
  data: {
    '0x112039e3df20d578dd27904bee23abbcb264a20db6ebdd60b320fe1a40704074': {
      error: 'revert',
      program_counter: 351,
      return: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002e455243373231413a20636f6c6c656374696f6e206d75737420686176652061206e6f6e7a65726f20737570706c79000000000000000000000000000000000000',
      reason: 'ERC721A: collection must have a nonzero supply'
    },
    stack: 'RuntimeError: VM Exception while processing transaction: revert ERC721A: collection must have a nonzero supply\n' +
      '    at Function.RuntimeError.fromResults (C:\\Users\\23120\\AppData\\Local\\Programs\\Ganache\\resources\\static\\node\\node_modules\\ganache-core\\lib\\utils\\runtimeerror.js:94:13)\n' +
      '    at BlockchainDouble.processBlock (C:\\Users\\23120\\AppData\\Local\\Programs\\Ganache\\resources\\static\\node\\node_modules\\ganache-core\\lib\\blockchain_double.js:627:24)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
    name: 'RuntimeError'
  }
```
But the constructor is 

```
constructor(
) ERC721A("AI Otherdeed", "AIO", 100, maxSupply) {
}
```
where maxSupply is 4444.

The constructor of ERC721A:
```
  constructor(
    string memory name_,
    string memory symbol_,
    uint256 maxBatchSize_,
    uint256 collectionSize_
  ) {
    require(
      collectionSize_ > 0,
      "ERC721A: collection must have a nonzero supply"
    );
    require(maxBatchSize_ > 0, "ERC721A: max batch size must be nonzero");
    _name = name_;
    _symbol = symbol_;
    maxBatchSize = maxBatchSize_;
    collectionSize = collectionSize_;
  }
```

However, when I use the command 
```
solc --optimize --bin AIOtherdeed.sol
```
to generate the bytecode. The bytecode can be deployed successfully.

Actually, I tested 50 real-world smart contracts from Etherscan and 5 of them couldn't be deployed.

Another finding is that the gas consumption of IR generator is higher than the legacy generator.

Update:

If I change 
```
uint256 public  maxSupply = 4444;
```
to
```
uint256 public constant maxSupply = 4444;
```
IR generator works.

**Comment by hrkrshnn** [comment]
Do you have a link to the full contract?

**Comment by hpumengzhao** [comment]
https://paste.ubuntu.com/p/rxH3snBD6Y/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethereum/solidity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上7:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethereum/solidity] Deploy Bytecode  Generated by --via-ir Failed  (Issue #13311)





 
Do you have a link to the full contract?

**Comment by hrkrshnn** [comment]
The difference is documented in https://docs.soliditylang.org/en/v0.8.15/ir-breaking-changes.html#semantic-only-changes

This is due to the order of initialization of `maxSupply`, in the IR pipeline the variable is initialized at towards the end. So in the constructor, the value getting read is zero.

Closing this for now. Feel free to reply if you have questions.
