### ISSUE TITLE
Implement textDocument/hover

### ISSUE THREAD

**Issue by nishant-sachdeva** [ethereum/solidity#13322]
### Spec

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover

### Expectation

Hover information can display the symbol signature as well as some NatSpec documentation, if available.

**Comment by christianparpart** [comment]
@nishant-sachdeva I've renamed this ticket because it was too generic. And I'd like to create some defining the scope of what to do in the near future. I hope you don't mind.
