### ISSUE TITLE
Remove all references to "money"

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#13338]
I don't believe the Ethereum Foundation has made any reference to classifying Ether as "money" and therefore neither should the Solidity project.

**Comment by kriptonian1** [comment]
I would like to work on this issue

**Comment by daredevil3435** [comment]
Is this issue still open?

**Comment by NunoFilipeSantos** [comment]
Done.

There are only some references in actual solidity files as comments not on Docs.

**Comment by NunoFilipeSantos** [comment]
<img width="1128" alt="Screenshot 2023-05-22 at 12 57 27" src="https://github.com/ethereum/solidity/assets/2582498/0e0f9fe3-b5d4-46a8-8f96-c9f6f3ff87d1">
<img width="1110" alt="Screenshot 2023-05-22 at 12 57 43" src="https://github.com/ethereum/solidity/assets/2582498/753bae74-0f0e-4343-b89d-8b449eb3bb7c">

**Comment by fulldecent** [comment]
cool, thank you
