### ISSUE TITLE
Unexpected storage layout caused by interfaces

### ISSUE THREAD

**Issue by cyraxred** [ethereum/solidity#13332]
## Description

Addition of an interface causes reordering of fields in the storage layout.

## Environment

- Compiler version: reproduced on 0.8.0, 0.8.4, 0.8.10. 0.8.15
- Framework/IDE (e.g. Truffle or Remix): Remix, VisualStudio

## Steps to Reproduce

Compiling of the code below gives following storage layouts:
- V1: p11, p12
- V2: _p21_, p11, p12, _p22_

Expected layout is:
- V1: p11, p12
- V2: p11, p12, p21, p22 

When ITest is removed from P22, then the layout is generated as expected.
This effect depends on position of interfaces on the inheritance list, especially for contracts with complex composition.

```solidity
interface ITest {}

contract P11 is ITest {
    uint8 public p11 = 11;
}

contract P12 is P11 {
    uint8 public p12 = 12;
}

contract V1 is P12 {}

contract P21 {
    uint8 public p21 = 21;
}

contract P22 is P21, ITest {
    uint8 public p22 = 22;
}

contract V2 is V1, P22 {}

```

**Comment by cyraxred** [comment]
A simple demo
https://github.com/cyraxred/solidity-layout-bug

**Comment by ekpyron** [comment]
The layout of storage in the presence of inheritance is determined by the [C3 linearization](https://en.wikipedia.org/wiki/C3_linearization) of the inheritance graph.
Adding the interface changes the C3 linearization, so the change in the storage layout is expected, conforms to the current specification and is in that sense not a bug.

That being said, I'm actually wondering, whether interfaces should be exempt from being treated the same as contracts in the C3 linearization - out of my head, it seems to me that this would be possible and might actually be beneficial. This would be a gravely breaking change, though, so at least for the time being, the change in storage layout is expected and this behaviour cannot be changed in the short term...

**Comment by cyraxred** [comment]
yeah, ideally, interfaces should be exempt from the linearization

**Comment by Elyx0** [comment]
Is there any tool to preview the solidity C3 output of a given contract?

**Comment by montyly** [comment]
@Elyx0 : you can use slither's inheritance graph: https://github.com/crytic/slither/wiki/Printer-documentation#inheritance-graph

`slither file.sol --print inheritance-graph`
