### ISSUE TITLE
`abi.encodeError(...)` for custom errors

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#13339]
## Abstract

The type-safe `ab.encodeCall(f, args)` should be extended for custom errors.

## Motivation

It's very common in testing frameworks to encode custom errors (to check if a call reverts with the specified encoding). This is currently done by using `abi.encodeWithSignature('error_signature", ...)` or `abi.encodeWithSelector(error.selector, ...)`.

**Comment by cameel** [comment]
Related bug: #13266.

**Comment by hrkrshnn** [comment]
Decision to use `abi.encodeError` instead of `abi.encodeCall`.

**Comment by timweri** [comment]
Is anyone attempting this? May I take it?

**Comment by hrkrshnn** [comment]
@timweri Yeah go for it

**Comment by guidanoli** [comment]
This feature would be very useful when checking for errors in Forge:

```solidity
vm.expectRevert(abi.encodeError(MyContract.MyError, arg1, arg2));
```

**Comment by smartcontracts** [comment]
Is anything like this still being considered?

**Comment by adraffy** [comment]
I vote for `abi.encodeCall()` to just support errors.

Seems so obvious and trivial to implement.

Error(3509) explicitly claims you can't use it for errors even though it's 100% ABI compatible.
