### ISSUE TITLE
Inherited modifier which invokes private function should not compile

### ISSUE THREAD

**Issue by CryptoKiddies** [ethereum/solidity#13330]
## Description

Since the modifier is a code rollup that inlines code into functions that it decorates, it's expected that functions invoked in an inherited modifier which are private will fail when compiled. However there is no such issue in extended contracts, which inherit such modifiers from base contracts.

## Environment

- Compiler version: 0.8.13
- Target EVM version (as per compiler settings): London
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: any
- Operating system: Fedora

## Steps to Reproduce

``` solidity
abstract contract MyAbstractParent {
    modifier checkSomething(uint256 tag) {
            _checkActuallyTheThing(tag);
            _;
        }

    function _checkActuallyTheThing(uint256 tag) private view {
        if (
          ...  stuff...
        ) {
            revert("reverting");
        }
    }
}
```
## Comments

Perhaps this is the expected behavior for a modifier as it seems reasonable. I'm not sure whether it's intended to be loosely spec'ed or rule hasn't been finalized yet, which is I've submitted.

**Comment by migoldfinger** [comment]
This is perfectly fine behavior in every single OO-programming language I know.
Even virtual methods you can override in your class can call private functions of the class where they are defined.
Only if you actually override them you can not call the private functions (directly) anymore but you can call the overrideen implementation in the base/super-class.

**Comment by hrkrshnn** [comment]
This is expected behaviour. If you replace the modifier by another function, you'll get the same behaviour. As Michael comment, the behaviour is also present in other languages with inheritance. Closing.
