### ISSUE TITLE
Are unused internal functions of libraries removed from bytecode?

### ISSUE THREAD

**Issue by migoldfinger** [ethereum/solidity#13349]
I feel kind of stupid and this is more like a question I think. If not maybe it's a feature request :)
I searched for 2 hours now without finding a definite answer on the internet or in the documentation but maybe I am just blind.

As far as I understand is that inline functions of libraries are embedded in the bytecode of the contract that is using them.
Therefore instead of a delegatecall a jump will be performed just like if the library function where a internal or private function of the contract itself. 

However I did not find a definite answer to the question if unused internal library functions also got embedded and therefore affect the size of the contract.

For example if I plan to create an all mighty math library with every possible mathematical operation you can think of.
Abs, Add, Divide, DivRem, Log, Log10, Max, Min, ModPow, Multiply, Negate, Pow, Remainder, Subtract, Sqrt, ......
Then I have my contract that includes that library but only uses the Sqrt function. Will the solidity compiler generate a bytecode that only adds the Sqrt to my contract or will the whole library be added to my contract even if all other functions never get called?

**Comment by ekpyron** [comment]
Uncalled internal functions, including internal library functions, will generally not occur in bytecode.

**Comment by cameel** [comment]
Exactly. Only the functions you reference in some way (call, assign to a pointer, use in an expression) are included in the bytecode. And this pruning happens at the codegen level so it's true even with the optimizer disabled. You don't have to worry about the unused functions bloating your bytecode.

Also, you can always check for yourself. You can compile the code with `--ir` or `--ir-optimized --optimize` option (depending on if you use the optimizer or not) and look for annotations that look like this: `/// @src 0:51:75  "function f() internal {}"`. Or, with the legacy pipeline, you can check out `--asm`, which will show you `/* "test.sol":51:75  function f() internal {} */`. If the function is not there, it is not included.

**Comment by migoldfinger** [comment]
thx you are the best ;)
