### ISSUE TITLE
Function pointer assignment error when names are colliding

### ISSUE THREAD

**Issue by antonper** [ethereum/solidity#13356]
## Description

Compiler throws error when function with the same name but different signature exists  in code.

```
Error: No matching declaration found after variable lookup.
  --> a.sol:16:65:
   |
16 |         function(uint256) internal pure returns(uint256) _foo = foo;
   |       
```
Even though the type of declared variable can only match one out of 2 functions.
If this behavior is intended, the error message is not informative.

## Environment

- Compiler version: Version: 0.8.15+commit.e14f2714.Linux.g+

## Steps to Reproduce

```solidity
pragma solidity ^0.8.13;
// SPDX-License-Identifier: MIT


contract X{

    function foo(uint256 x) internal pure returns(uint256){
        return x;
    }

    function foo() internal pure returns(uint256){
        return 5;
    }


    function main() public pure {
        function(uint256) internal pure returns(uint256) _foo = foo;
    }
}
```

**Comment by hrkrshnn** [comment]
Yeah, this is a known issue. Unfortunately, in Solidity if you use a symbol by itself, then the lookup needs to be unique (of course, calling functions would work, but it's not smart enough in this case). 

As an immediate fix, how can the error message be improved to make this understandable? Any suggestions? @antonper

**Comment by antonper** [comment]
Message "Non-unique declaration found after variable lookup" is better.

**Comment by cameel** [comment]
I'm going to close this because the underlying issue is already tracked in #3556 and for improving the error messages for ambiguous overloads we have #9607.
