### ISSUE TITLE
Fix builds for Ubuntu 22.10

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#13362]
We trigger PPA release builds for the upcoming Ubuntu release as early failure indicator and in the last release it actually failed:
https://launchpadlibrarian.net/617180489/buildlog_ubuntu-kinetic-amd64.solc_1%3A0.8.16-0ubuntu1~kinetic_BUILDING.txt.gz

We should check with a ubuntu 22.10 docker image what to do to fix those builds. Best asap, but definitely before its release in October.

**Comment by nikola-matic** [comment]
```
c++: error: unrecognized command-line option '-Wfinal-dtor-non-final-class'
c++: error: unrecognized command-line option '-Wnewline-eof'
c++: error: unrecognized command-line option '-Wsuggest-destructor-override'
c++: error: unrecognized command-line option '-Wduplicate-enum'; did you mean '-Wduplicated-cond'?
```
Looks like we're passing clang options to g++ (GNU)

**Comment by cameel** [comment]
The `eth_add_cxx_compiler_flag_if_supported()` macro must be broken then:
https://github.com/ethereum/solidity/blob/bb41ddd7abb3fcb6ce7217f10059dcb9c1550ede/cmake/EthCompilerSettings.cmake#L68-L74

**Comment by ekpyron** [comment]
Should maybe have fixed this before this release - but yeah, this was probably the last release in which we'll get away with saying "22.10 is not released yet anyways" :-).

Not entirely sure if we should actually add CI runs for the short-lived ubuntu releases...

Anyways, new log, different failure this time:

https://launchpadlibrarian.net/622411533/buildlog_ubuntu-kinetic-amd64.solc_1:0.8.17-0ubuntu1~kinetic_BUILDING.txt.gz

Seems to be fmtlib related:

```
CMake Error at liblangutil/CMakeLists.txt:34 (target_link_libraries):
  Target "langutil" links to:

    fmt::fmt-header-only

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

Even though fmtlib should be bundled in the PPA source archives...
