### ISSUE TITLE
Incorrect Public Getter Created for Static Array

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1336]
It would appear that currently the ABI we get from a contract such as this:

```
contract SimpleConstructorArray {
  uint[3] public storedData;

  function SimpleConstructorArray(uint[3] x, uint[3] y) {
    storedData = x;
  }
}
```

returns something like this: 

```
======= SimpleConstructorArray =======
Contract JSON ABI
[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256[3]"}],"payable":false,"type":"function"},{"inputs":[{"name":"x","type":"uint256[3]"},{"name":"y","type":"uint256[3]"}],"type":"constructor"}]
```

I don't think storedData in this instance should be taking a uint as input to find the index value, rather it should take no inputs and return the entire static array. Looking to see if anyone agrees with this?

**Comment by axic** [comment]
The ABI and the code matches. This is the current behaviour and it mentioned in the documentation: http://solidity.readthedocs.io/en/develop/types.html?highlight=accessor#arrays

> It is possible to mark arrays public and have Solidity create an accessor. The numeric index will become a required parameter for the accessor.

Changing it is a breaking change and is not possible currently for variable length arrays (at least other contracts would have a hard time retrieving them).

**Comment by VoR0220** [comment]
Correct that its not possible for variable length arrays but i strongly feel like for static arrays this ought to be doable.

**Comment by axic** [comment]
@VoR0220 I think it would need to be a new feature. Do you have any ideas for notation?

**Comment by VoR0220** [comment]
What do you mean by notation?

**Comment by axic** [comment]
@VoR0220 I think if this would change, we would still need to support the current behaviour too.

I would refrain from changing the default behaviour of `public` for arrays now, because that is a breaking change across contracts (and not limited to a single contract compilation. It is possible to remove the `public` keyword entirely, but changing the behaviour of it is risky.

Therefore a new notation is neede to support the retrieval of arrays as arrays.

**Comment by axic** [comment]
Perhaps replacing `public` with these could make sense:
- `getter`: `uint[3] getter data;` generates `function data() returns (uint[3]);`
- `itemgetter` or `indexedgetter`: `uint[3] itemgetter data;` generates `function data(uint index) returns (uint);`
