### ISSUE TITLE
Different gas cost when using Libraries with using and without

### ISSUE THREAD

**Issue by migoldfinger** [ethereum/solidity#13375]
Hi, I stumbled across this while optimizing my contracts.
I do not know if this is maybe and hardhat-gas-reporter bug because in my opinion both options should lead to the same byte code.
UQ144x112 is just a library for unsigned fixed decimal it does not matter what kind of library is used.
```
contract Test
{
   using UQ144x112 for uint256;

   function test1() returns (uint256)
   {
      uint112 res1 = 1000;
      uint112 res2 = 2000;
      unchecked
      {
          return UQ144x112.encode(res1).uqdiv(res2);
      }
   }

    function test2() returns (uint256)
   {
      uint112 res1 = 1000;
      uint112 res2 = 2000;
      unchecked
      {
          return UQ144x112.uqdiv(UQ144x112.encode(res1),res2);
      }
   }
```
I hope there is now error but I just put it together instead of copying the whole contract.
If I run the tests with gas report enabled `test1()` uses 5 gwei more gas than `test2()` which I do find odd.

**Comment by hrkrshnn** [comment]
It's likely the order of the function in the dispatch affecting the gas. See: https://hrkrshnn.com/t/devconnect.pdf#page=11 for some details.

You can easily verify this by swapping the names of the functions and seeing the difference. Let us know if that is indeed the case. Closing this.

**Comment by migoldfinger** [comment]
@hrkrshnn I used 5 different libraries and even switched names as suggested. The result is always the same. 
The call without making use of using is slightly cheaper than the other one.

**Comment by hrkrshnn** [comment]
If you switched the names and noticed no difference, that's really odd. Note: I'm referring to switching the names of `test1` and `test2`.
