### ISSUE TITLE
Document the fact that zero-length arrays are not allowed (currently it's undefined behavior)

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#13372]
This code does not compile:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.16;

contract E {
    uint256[0] bob;
}
```

with error: 

>  Array with zero length specified.

---

I can't find any documentation that says I can't do this.

---

Reviewing live now during NFT/Web3 Community Service Hour. --> https://phor.net/#hour on twitch

**Comment by NunoFilipeSantos** [comment]
Hi @fulldecent !

I'm not sure if this is what you are looking for, but please let me know:

https://docs.soliditylang.org/en/v0.8.18/internals/layout_in_memory.html#layout-in-memory

```
There are some operations in Solidity that need a temporary memory area larger than 64 bytes and therefore will not fit into the scratch space. They will be placed where the free memory points to, but given their short lifetime, the pointer is not updated. The memory may or may not be zeroed out. Because of this, one should not expect the free memory to point to zeroed out memory.

While it may seem like a good idea to use `msize` to arrive at a definitely zeroed out memory area, using such a pointer non-temporarily without updating the free memory pointer can have unexpected results.
```

**Comment by cameel** [comment]
No, this bit is about the internal layout and I think the question is about our high-level abstractions. I.e. it's saying that the fact that zero-length arrays are not allowed by the compiler is not explicitly documented and therefore undefined behavior.

**Comment by fulldecent** [comment]
Yes, thank you. Just an undefined behavior problem.
