### ISSUE TITLE
Stop recommending .transfer

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#13371]
## Page

The Address.transfer function may not be compatible with smart contract recipients due to gas limits.

Since smart contract recipients are first-class citizens on Ethereum we should either:

1. Stop recommend `.transfer` everywhere (in documentation) and deprecate the function, or
1. Clearly explain the limitations of `.transfer` everywhere it is mentioned (in documentation) and explain the difference of `.call("")` inline.

## Discussion

I wanted to discuss this to get approval before offering any specific changes.

**Comment by hrkrshnn** [comment]
I think we should clearly indicate the differences.  The function`<address>.transfer` is quite convenient and I wouldn't entirely remove it from the docs or deprecate it. The notion of `callstipend` is well-defined in the Yellowpaper and the EVM. It provides enough gas to receive the ETH and emit an event, and cannot modify state. Even when storage / opcodes gets repriced, some care is made to ensure that most contracts will continue working (see how EIP-2929 introduced access lists).

The replacement`.call{value: ...}("")` adds a re-entrancy risk and solving it will cost ~3000 gas assuming full refunds. The applications that `.call{value: ...}("")` allow, i.e., complex smart contract wallets, forwarding patterns etc haven't really caught up. As a comparison, standards such as ERC-777, ERC-1155 and ERC-721's hooks are largely ignored by most protocols as they increase security risks. 

Also, do you have an example of a smart contract wallet that breaks on `.transfer`? (Assuming access lists can be used.)

**Comment by hrkrshnn** [comment]
Also relevant: https://github.com/ethereum/solidity/issues/7455 We did try to get community feedback in https://forum.soliditylang.org/t/feedback-on-address-payable-transfer/164.

**Comment by mojtaba-eshghie** [comment]
This might also be relevant:
https://medium.com/noblocknoparty/a-smartcontract-best-practice-push-pull-or-give-b2e8428e032a
