### ISSUE TITLE
buildpack-deps jobs are failing due to `arrlt/comment-on-pr`

### ISSUE THREAD

**Issue by timweri** [ethereum/solidity#13392]
## Description

While trying to update emscripten (#13122), I ran into buildpack-deps jobs failing.
buildpack-deps rely on the Dockerfile `aarlt/comment-on-pr@v1.2.0`.

The problem is `aarlt/comment-on-pr@v1.2.0` doesn't pin the version of `octokit` it uses.
Since [v5.0.0](https://github.com/octokit/octokit.rb/releases/tag/v5.0.0), `octokit` requires Ruby of version `>=2.7.0`.
However, `aarlt/comment-on-pr@v1.2.0` uses `2.6.0`.
```
  Step 8/10 : RUN gem install octokit
   ---> Running in e5a7ffb004b1
  ERROR:  Error installing octokit:
  	The last version of octokit (>= 0) to support your Ruby & RubyGems was 4.25.1. Try installing it with `gem install octokit -v 4.25.1`
  	octokit requires Ruby version >= 2.7.0. The current ruby version is 2.6.0.0.
```

## Steps to Reproduce

Any run of buildpack-deps should trigger this. For example, https://github.com/ethereum/solidity/pull/13386

**Comment by ekpyron** [comment]
Pinging @aarlt about this.
In particular see https://github.com/ethereum/solidity/runs/7816323898 for the issue in action.

Also: is there really any need for us to maintain this ourselves? My guess would be that there's ready-made alternatives with the same and/or similar functionality we could use as a replacement and which would lower our maintenance burden.
