### ISSUE TITLE
Not possible to define the same function signature (overload/override) in a sub-contract with "only" different return types

### ISSUE THREAD

**Issue by mojtaba-eshghie** [ethereum/solidity#13390]
## Description
Even though it is completely acceptable to define the same function signature with the same returns in a sub-contract with the override keyword. It is not possible to define the same function signature with only different return types. Such a situation will result in one of these:
- If we try to merely overload the function in the base contract (without using the virtual and override keywords), compiler will complain with the message "TypeError: Overriding function is missing "override" specifier".
- If we try to use virtual+override syntax, in the base and sub-contract, the compiler complains with "TypeError: Overriding function return types differ."

## Environment

- Compiler version: 0.8.16
- Target EVM version (as per compiler settings): The default current remix environment
- Framework/IDE (e.g. Truffle or Remix): -
- EVM execution environment / backend / blockchain client: Remix VM
- Operating system: -

## Steps to Reproduce
```
contract Base {
    function fn() public virtual returns (uint256) {
        return 0;
    }
}

contract SubContract1 is Base {
    function fn() public view virtual override returns (uint256) {
        return 0;
    }
}

contract SubContract2 is SubContract1 {

    // Either of the following two functions will fail to compile:

    // Overriding
    function fn() public view override returns (bool) {
        return true;
    }

    // Merely trying to fake overload by different return types:
    function fn() public view returns (bool) {
        return true;
    }
}
```

**Comment by matheusaaguiar** [comment]
This is by design as in many other languages. Also, the signature of a function does not take in account its return type, only its name and parameters. 
See [#259](https://github.com/ethereum/solidity/issues/259) for more, as it raises this same issue.
