### ISSUE TITLE
Standardize padding

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#1340]
```
contract TestContract {
    bytes32 public senderExplicit;
    bytes32 public stringExplicit;
    function TestContract(){
        senderExplicit = bytes32(msg.sender);
        stringExplicit = bytes32('hello world');
    }
}
```

`senderExplicit` padded left, while `stringExplicit` is padded right. Is there any reason this cant be standardized?

**Comment by axic** [comment]
`msg.sender` is an `address` (which is a special case of `uint`: `uint160`). Typecasting to `bytes32` will not change the value, just the type. Numbers are stored as big endian ("left padded").

A string on the other hand is a `bytes` type (variable length), and when typecasting to `bytes32` that is right padded.

**Comment by aakilfernandes** [comment]
@axic so am i correct that everything that is fixed length is left padded, everything else is right padded?

**Comment by aakilfernandes** [comment]
Also, why not left-pad variable length vars?

**Comment by chriseth** [comment]
@aakilfernandes the specification is here: https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI

**Comment by aakilfernandes** [comment]
@chriseth thanks!
