### ISSUE TITLE
First batch of new labels: effort, impact, desirability, task type

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13408]
The first batch of the issue management changes from [Issue labeling guidelines (proposal)](https://notes.ethereum.org/@solidity/SkMG8szAq).

- [x] Add the labels we decided that we want for now:
    - Effort: `epic`, `high effort`, `medium effort`, `low effort`.
    - Impact: `high impact`, `medium impact`, `low impact`.
    - Desirability: `roadmap`, `must have`, `must have eventually`, `should have`, `nice to have`.
    - Task type: `refactor`, `bug`, `documentation`, `research`, `testing`.
- [x] Delete `feature` and `enhancement` labels (remove them from all issues).
- [x] Choose sensible colors. My suggestion would be to have the same base color for each category with a lighter shade for `low` and darker for `high`. Feel free to adjust some of the existing colors if they clash. There are some that are what they are for a good reason (`bug`=red, `codegen error`=black, etc.) but most of them were chosen ad-hoc.
- [x] Make sure that `solc-js` has these labels too. For now I'd not synchronize the ones that are not in one of the categories from the list above, just add the ones that are missing and adjust colors if they're not the same.
- [x] Remove `feature` label from the link in [`ISSUE_TEMPLATE/config.yml`](https://github.com/ethereum/solidity/blob/develop/.github/ISSUE_TEMPLATE/config.yml) (this is the config for [the template chooser](https://github.com/ethereum/solidity/issues/new/choose)).
- [x] Add an entry to [the template chooser](https://github.com/ethereum/solidity/issues/new/choose) for opening a new forum discussion in the right category. We decided not to have the `controversial` label, so I think we need to more strongly encourage people to post their wilder ideas on the forum first and only open feature requests for them after getting some feedback.
- [x]  Consider also tweaking the [`feature_request.md` template](https://github.com/ethereum/solidity/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md) to mention the forum.

**Comment by cameel** [comment]
Also, the "medium" labels should be added to the guidelines. Were the any other changes on Monday that we should document?

**Comment by nikola-matic** [comment]
@cameel, when you say 
```
Remove feature label from the link in [ISSUE_TEMPLATE/config.yml](https://github.com/ethereum/solidity/blob/develop/.github/ISSUE_TEMPLATE/config.yml)
```
what exactly do you mean by `Remove feature label`? Keep the template, but instead of `Feature Request` have just `Request`, or remove the feature request entry completely?

Also, regarding the controversial issues, what's the 'right category' in this context? Language design, Feedback?

**Comment by cameel** [comment]
> what exactly do you mean by `Remove feature label`?

The config file defines links behind the buttons you see in the [template chooser](https://github.com/ethereum/solidity/issues/new/choose). Go there and see what happens when you select "Bug Report" - the new issue automatically has a `bug` label applied to it. It used to be the same for `feature` and "Feature Request" before you deleted the label.

The label is one of the query parameters in the link. I meant simply updating the link not to have that now.

BTW, these default labels did not turn out to be all that useful because they are not applied when users open issues. I think that's because they do not have permissions to change labels. So we might consider removing them and removing the config to get the original chooser we had before #12413. Not necessarily in this PR though.

> Also, regarding the controversial issues, what's the 'right category' in this context? Language design, Feedback?

I'd say "Language Design". We could add "Feedback" as well but that would be a separate button.

**Comment by nikola-matic** [comment]
I'm gonna delete labels from all of the issues in the selector, as it doesn't make much sense to remove it for `Feature` and leave it in for the others (until a later PR), especially if they're not applied in any case.

**Comment by cameel** [comment]
> it doesn't make much sense to remove it for `Feature` and leave it in for the others

Since we do not have a label for features (we just consider it the default) now but do have them for other things, I think it would still make sense - if the whole mechanism worked. But it does not so, year, I'm fine with removing them all :)

**Comment by nikola-matic** [comment]
> > it doesn't make much sense to remove it for `Feature` and leave it in for the others
> 
> Since we do not have a label for features (we just consider it the default) now but do have them for other things, I think it would still make sense - if the whole mechanism worked. But it does not so, year, I'm fine with removing them all :)

Yup. The only thing left at the moment is adding the labels to `solc-js`, which I assume is [this repository](https://github.com/ethereum/solc-js)?

**Comment by cameel** [comment]
Yes.

**Comment by nikola-matic** [comment]
Labels have been mirrored in [solc-js](https://github.com/ethereum/solc-js/labels).
