### ISSUE TITLE
Entering a numeric short form in assembly gives ParseError

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#13407]
## Description

Currently within assembly blocks, it is not allowed to write a number like `1e6` or with underscores. However, these kinds of notations make it easy to read a number.

```solidity
uint b;
b = 3_200_000_000; // works
assembly {
    b := 3_200_000_000 // ParserError: Invalid number literal.
    b := 3200000000 // works but its difficult to read
}
```

## Environment

- Compiler version: 0.8.16
- Target EVM version (as per compiler settings): London
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: EthereumJS VM
- Operating system: macos

**Comment by sgilflores3** [comment]
``1e6''

**Comment by cameel** [comment]
I think that supporting `_` is not a bad idea but scientific notation is not so clear-cut to me.

The simple cases like e.g. `5e20` might be useful in some limited situations but (1) this notation also allows negative exponents and decimal point, which would introduce fractional numbers into Yul and (2) this is base 10 while at the assembly level some base 2 notation would probably be more useful.

**Comment by cameel** [comment]
One more thing. The complication of supporting underscores is that Yul literals in the AST stop being simple strings of numbers and now require some minimal parsing. We perhaps should the tools know ahead of time.

**Comment by ekpyron** [comment]
I'm not convinced that any of this is worth the added parsing complexity of yul.

**Comment by cameel** [comment]
I think underscores alone might be simple enough to be worth it given that we're always working with 256-bit numbers. I do miss that sometimes when writing Yul.

The PR definitely was started prematurely though, before we got to actually discuss this.

**Comment by cameel** [comment]
@chriseth What's your opinion?

**Comment by zemse** [comment]
~Should low effort, good first issues be not closed this way? Since potential contributors would only be looking at open issues. (I understand lots of open issues make it look overwhelming and distractive so I don't mind this getting closed).~

I just noted that this is marked as "needs design"
