### ISSUE TITLE
Legacy optimizer does not remove zero length redundant write to memory inside inline assembly block

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#13417]
```
contract C0 {
  function f() external {
    assembly
    {
      calldatacopy(0x80, keccak256(0x80, exp(2, 40)), 0)
    }
  }
}
// ====
// compileViaYul: also
// ----
// f() -> FAILURE
// f() -> 
```

First call indicates outcome via legacy + optimize, the second via IR + optimize.

~~Why is it that legacy + optimize runs out of gas while IR + optimize does not? Afaiu, the Yul optimizer (specifically redundant store eliminator is run on inline assembly code in legacy mode).~~

**Comment by bshastry** [comment]
This could be expected behavior and hence a wontfix. Feel free to close this issue in that case.

I created it just to be sure and have it seen by at least one other person :-)

**Comment by bshastry** [comment]
From chat conversations, here is the summary so far

1. Due to the mstore bug affecting the legacy pipeline, redundant memory write removal was disabled. The said bug does not affect IR pipeline because the latter has a global view and can safely remove such redundant writes

2. Hence, this issue is expected behavior.

3. The only potential optimization that may be applied to the legacy pipeline is to remove zero length writes to memory such as the case in this issue. This does not seem high priority since such operations seem unusual.

**Comment by nishant-sachdeva** [comment]
@bshastry  Based on previous comments, would you recommend closing this issue? 

Or do we need to take a final call on point 3 from the previous comment?
> The only potential optimization that may be applied to the legacy pipeline is to remove zero length writes to memory such as the case in this issue. This does not seem high priority since such operations seem unusual.

**Comment by bshastry** [comment]
> @bshastry Based on previous comments, would you recommend closing this issue?
> 
> Or do we need to take a final call on point 3 from the previous comment?

I wouldn't recommend closing this issue, since `nice to have` could open to door to low priority external contributions.
