### ISSUE TITLE
Clarify effect of memory unsafe assembly

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#13416]
>Therefore, moving stack variables to memory and additional memory optimizations are, by default, disabled in the presence of any inline assembly block that contains a memory operation or assigns to solidity variables in memory.

Can you clarify what "in the presence of" means exactly? Are these optimizations _globally_ disabled for the entire contract if there is a memory unsafe block anywhere in it? Are they only disabled in the scope of the function body?

**Comment by nishant-sachdeva** [comment]
Since this is not a feature request/ bug, I would recommend asking this in the Solidity channel https://matrix.to/#/#ethereum_solidity:gitter.im

Will be closing this issue for now. If it's decided that this is actionable, we can reopen it.

**Comment by frangio** [comment]
I should've been clearer, but I'm pointing out that the documentation isn't clear about this and suggesting it should be improved.

Can you reopen as a documentation issue?

**Comment by hrkrshnn** [comment]
>  Are these optimizations globally disabled for the entire contract if there is a memory unsafe block anywhere in it

Yes.

> "in the presence of" means exactly?

Any operation that can write to memory would disable it. Two examples are  `mstore` and `calldatacopy`.


Reopening on request. @frangio Do you want to make a PR making this clarification? 👀
