### ISSUE TITLE
Remove redundant Error Types from codebase

### ISSUE THREAD

**Issue by nishant-sachdeva** [ethereum/solidity#13410]
Referenced in https://github.com/ethereum/solidity/pull/13162#discussion_r939153742  .

At the moment, the compiler as several Error types ( for eg. Exception, Internal compiler error, Compiler Error ) that seem to be redundant. 

The task here is to decide which of the error types can be removed and refactor the code accordingly.

**Comment by nishant-sachdeva** [comment]
The issue gets much easier to resolve once https://github.com/ethereum/solidity/pull/13162 is merged. Error::Type has been expanded.

The Error types are listed in an enum at 
`class Error: virtual public util::Exception` in `liblangutil/Exceptions.h`

**Comment by Divyansh-singh08** [comment]
Hii.. @nishant-sachdeva   I am new to the Open Source I am intermediate to the solidity can u please guide me on how to contribute to this project and solve a good first issue
