### ISSUE TITLE
Investigate emscripten build to reduce size / increase speed

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1341]
Currently loading the emscripten output can take a while. In the commandline (`solcjs`) it can easily take 5 seconds, while in browsers it can be faster due to caching in the VM.

We should investigate the build script to see if optimising for different requirements (`-Os` vs. `-O3`, size vs. speed) might produce asm.js outputs with different loading speed.

Also we should double check if dead code is eliminated.

**Comment by axic** [comment]
In https://github.com/ethereum/solidity/blob/develop/scripts/travis-emscripten/build_emscripten.sh we link against many boost libraries, some of htem seem unrelated to the jsonCompiler:

```
  -DBoost_CHRONO_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_chrono.a \
  -DBoost_CHRONO_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_chrono.a \
  -DBoost_DATE_TIME_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_date_time.a \
  -DBoost_DATE_TIME_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_date_time.a \
  -DBoost_FILESYSTEM_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_filesystem.a \
  -DBoost_FILESYSTEM_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_filesystem.a \
  -DBoost_PROGRAM_OPTIONS_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_program_options.a \
  -DBoost_PROGRAM_OPTIONS_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_program_options.a \
  -DBoost_RANDOM_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_random.a \
  -DBoost_RANDOM_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_random.a \
  -DBoost_REGEX_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_regex.a \
  -DBoost_REGEX_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_regex.a \
  -DBoost_SYSTEM_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_system.a \
  -DBoost_SYSTEM_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_system.a \
  -DBoost_THREAD_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_thread.a \
  -DBoost_THREAD_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_thread.a \
  -DBoost_UNIT_TEST_FRAMEWORK_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_unit_test_framework.a \
  -DBoost_UNIT_TEST_FRAMEWORK_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_unit_test_framework.a \
```

**Comment by axic** [comment]
@chriseth today's build after merging the removal of cryptopp actually resulted in a bigger binary:

```
7742759  soljson-v0.4.5-nightly.2016.11.4+commit.d97d267a.js
7744320  soljson-v0.4.5-nightly.2016.11.8+commit.7a30e8cf.js
```

This suggest dead code is not eliminated.

**Comment by chfast** [comment]
This suggested actually the opposite, at least for simple linker case. We were linking with unnecessary cryptopp library and that did not produce bigger "binary" (I checked that when I was removing it, the size was the same).

The best solution for shared library is to limit the visibility of symbols, otherwise all non-internal functions are exported. This reduced the size of evmjit shared library a lot (might be 4x or more). https://github.com/ethereum/evmjit/blob/develop/libevmjit/CMakeLists.txt#L28.

**Comment by axic** [comment]
You're right, it is too later here to be productive 😉

**Comment by axic** [comment]
It also seems like `soljson` is an executable (and not library) target (but also exports methods?): https://github.com/ethereum/solidity/blob/develop/solc/CMakeLists.txt#L21

It must be some weird way Emscripten uses.

**Comment by axic** [comment]
This suggests a some ideas https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html:
1. outlining (can help or make it worse)
2. limit inlining (reduces size, may result in worse speed)
3. memory file (this would result in two files and may be painful with async loading it, but definitely improves speed)
4. LLVM optims:

```
--llvm-lto <level>
    Enables LLVM link-time optimizations (LTO).
```
1. use closure:

```
Run closure compiler. This greatly reduces code size and may in some cases increase runtime speed (although the opposite can also occur). Note that it takes time to run, and may require some changes to the code.
```
1. `ELIMINATE_DUPLICATE_FUNCTIONS` (not supported by our Emscripten version)

@chfast `-fdata-sections -ffunction-sections -Wl,--gc-sections` didn't make a change, so I guess it did eliminate sections. `-fvisibility=hidden` didn't make a difference either.

**Comment by axic** [comment]
Changed by #1342, though not much reduction was achieved.
