### ISSUE TITLE
How can the contract detect the mode of calling according to solidity docs?

### ISSUE THREAD

**Issue by mojtaba-eshghie** [ethereum/solidity#13427]
## Page

[Call Protection For Libraries](https://docs.soliditylang.org/en/v0.8.16/contracts.html#call-protection-for-libraries)

## Abstract

According to the following paragraph in the contracts documentation, there is a subtle way to determine the mode of call (being delegatecall or call):

>The EVM does not provide a direct way for a contract to detect whether it was called using CALL or not, but a contract can use the ADDRESS opcode to find out “where” it is currently running. The generated code compares this address to the address used at construction time to determine the mode of calling.

However, I could not wrap my head around how the address used at construction time is useful or even what documentation really means by this address.

**Comment by nishant-sachdeva** [comment]
Since this is not a feature request/bug, I would recommend trying to ask in the Solidity group channel.
https://matrix.to/#/#ethereum_solidity:gitter.im

I'll be closing the issue for now. If it's decided that this issue is actionable, we can consider reopening it.

**Comment by hrkrshnn** [comment]
Here's an example of something similar implemented in pure solidity: https://github.com/Uniswap/v3-core/blob/main/contracts/NoDelegateCall.sol
