### ISSUE TITLE
Switch working dir to test dir in command-line tests

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13437]
## Abstract
Currently, when running [command-line tests](https://github.com/ethereum/solidity/tree/develop/test/cmdlineTests), the working directory is set to `test/cmdlineTests/` and not the directory of the specific test case. This means that we need to repeat the name of the test case (which is often long) to refer to a file inside it.

This is not a big problem as long as we rely on the test runner inserting the file path automatically. There are, however, cases where we do have to spell out the path. For example:
https://github.com/ethereum/solidity/blob/f802eafc679541cc1d3ba0ca5bc7c12b4bdaf939/test/cmdlineTests/standard_debug_info_in_yul_and_evm_asm_print_all/input.json#L3-L5

We should be able to do `"C": {"urls": ["in.sol"]}` instead.

## Specification
Adjust [`cmdlineTests.sh`](https://github.com/ethereum/solidity/blob/develop/test/cmdlineTests.sh) so that it enters test case dir before running it and exits it afterwards. Then remove any hard-coded test case names from test inputs and regenerate expectations.

**Comment by kevin-allen-uf** [comment]
Hi! I'm trying to find a suitable good first contribution and I'd like to help with this issue. Is is claimed by anyone else or can I take it on?

**Comment by cameel** [comment]
Sure, feel free to take it.
