### ISSUE TITLE
Retrieve the list of function selectors in solidity

### ISSUE THREAD

**Issue by gzliudan** [ethereum/solidity#13441]
Sometimes it needs to check a function is exist in a contract. Can solidity provides a function that extracts all function selectors of a  contract? If not, how to parse bytecode of a contract and get all function selectors?

**Comment by hrkrshnn** [comment]
`solc --hashes` will give you this. You can also get it from the standard json output. Closing.

If you are using foundry, something like `forge inspect script/Contract.s.sol:C methodIdentifiers`

**Comment by gzliudan** [comment]
What I proposal is add a function in solidity, such as `checkSelector(address, bytes4)`. Solc is run in os enviroment and must has contract source code. How can we do if we has bytecode only when has no source code?

**Comment by hrkrshnn** [comment]
Ah, I see. That would be very impractical to do at runtime, parsing EVM bytecode at runtime is unfortunately tedious and hard to get right. 

For well known EIP standards, one way to do be to leverage https://eips.ethereum.org/EIPS/eip-165. You could consider having an EIP proposal of something like `function implementsSelector(bytes4 selector) pure returns (bool)` if you truly want to have a feature like this.

Also relevant https://github.com/ethereum/solidity/issues/12982

**Comment by gzliudan** [comment]
Yes, it's better if EVM can check a contract has a function selector, since a lot of contracts not implement ERC165.
