### ISSUE TITLE
Enum constructor truncates value inconsistently

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1344]
```
contract C {
    enum ActionChoices { GoLeft, GoRight, GoStraight }
	function getChoice() returns (uint d)
	{
	    choices = ActionChoices(-1);
	    d = uint(choices);
	}
	ActionChoices choices;
}
```

returns `0x00000000000000000000000000000000000000000000000000000000000000ff`.

```
contract C {
    enum ActionChoices { GoLeft, GoRight, GoStraight }
	function getChoice() returns (uint d)
	{
	    ActionChoices choices = ActionChoices(-1);
	    d = uint(choices);
	}
}
```

returns `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`

**Comment by axic** [comment]
@pirapira probably this could be fixed by #1334 easily?

**Comment by pirapira** [comment]
On #1334, I added a test that sees `ActionChoices(-1)` throw an exception.

**Comment by axic** [comment]
I'm actually concerned a bit why is the value different on those two cases above.

**Comment by chriseth** [comment]
There was no cleanup for enums previously.

**Comment by pirapira** [comment]
@axic The difference comes from storage access.  When an enum is stored into the storage, the value is truncated.

**Comment by axic** [comment]
Oh right, that's storage. And enum's are stored as the shortest int type they fit in. I would argue the same should apply to when they are a variable in memory / stack.

**Comment by axic** [comment]
@pirapira @chriseth Even though the sympton is fixed now by not allowing negative values, the cleanup isn't yet performed. I wonder if there's any other way to trigger the above after the latest changes. If there is, we should definitely perform the cleanup.

**Comment by pirapira** [comment]
Let's keep this open till the doubt is gone.

**Comment by pirapira** [comment]
When I remember what @chriseth was saying about cleanups, we need
- [x] cleanups before sending an enum value as external function argument (#1371)
- [x] cleanups before returning an enum value from a function (#1372)
- [ ] cleanups before enum equality comparison
- [ ] cleanups before storing an enum value into memory
- [ ] cleanups before using an enum value for looking up a mapping
- [ ] cleanups before using an enum value as an event argument
- [ ] cleanups before storing an enum value into storage.

Test cases would involve inserting invalid enum values using some inline assembly.  I think invalid values should cause exceptions.

**Comment by chriseth** [comment]
Most of the items above are redundant because they involve copying the enum value to memory.

**Comment by pirapira** [comment]
When #1381 is merged the remaining points should be solved.
