### ISSUE TITLE
Introduce `codedata` keyword

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13448]
## Abstract

We already have identifiers:
- `storage`
- `memory`
- `calldata`

Let's have `codedata` which works similarly to `calldata` but references smart contract code slice.

## Motivation

Having constant arrays/data is inefficient currently, since it copies whole data into memory before any actual access.

## Specification

Let's replicate `calldata` keyword usage for `codedata`. So constant arrays/data can use this access layout by default:
```solidity
contract Foo {
    bytes constant data = hex"aabb..ccdd";

    function f(bytes codedata d, uint256 index) internal view returns(bytes1) {
        return d[index];
    }
}
```

We also need to have `.offset` and `.length` in Solidity Assembly (Yul).

## Backwards Compatibility

Not needed.

Related to #12821, #1772, #12587

**Comment by k06a** [comment]
I need to build some precomputed table with 1024 numbers and I will have access to 1-4 numbers from it. What I don't want - is to have this table fully copied from CODE to MEMORY. Even having `.offset` in assembly/yul would allow me to have access directly to these 4 items. But now it's impossible.

**Comment by cameel** [comment]
So the feature request here is basically immutable reference types (#13323) + being able to have actual references to them?

**Comment by ekpyron** [comment]
Thank you very much for this issue - but this is pretty much what we already decided to do for https://github.com/ethereum/solidity/issues/12587 in https://github.com/ethereum/solidity/issues/12587#issuecomment-1069183987 (it will be called ``code``, not ``codedata``, but apart from that this is exactly what we'll be doing), so I'm closing this as a duplicate.

We actually already started piecing this up into https://github.com/ethereum/solidity/issues/13368 and https://github.com/ethereum/solidity/issues/13369 as first steps, we just didn't have the capacity to start it yet.

**Comment by k06a** [comment]
@ekpyron glad to hear that you’re already working on this!
