### ISSUE TITLE
Produce a panic code for failed `abi.decode` calls

### ISSUE THREAD

**Issue by fvictorio** [ethereum/solidity#13446]
## Abstract

Failed `abi.decode` calls produce a revert without a reason. Instead, it would be better to produce a new panic code that indicates a failure during decoding. It could be just a generic `ABI_DECODE_ERROR` thing, and it could be split into more specific codes in the future if possible/necessary.

## Motivation

Development nodes like Hardhat try to give as much information as possible about failed transactions. We have a bunch of heuristics for different scenarios, and (maybe) we could add a new one for failed `abi.decode` calls, but it would be easier if this would be just a new panic code.

## Specification

A new panic code that is returned when an `abi.decode` call reverts. I guess it could be `0x23`, since this seems to be closer to `EnumConversionError` and `StorageEncodingError` than to the other panic codes.

## Backwards Compatibility

I guess this is backwards compatible, unless the change in the amount of revert data for failed decodings is considered a breaking change.

**Comment by nikola-matic** [comment]
Hey @frangio. We discussed this during our triage call, and decided to close this issue in favour of https://github.com/ethereum/solidity/issues/11664, as it's more general.
