### ISSUE TITLE
Add a special comment for storage layout

### ISSUE THREAD

**Issue by wiasliaw** [ethereum/solidity#13466]
## Abstract

Add a special comment to register a variable as an used storage slot.

## Motivation

Here's the common Proxy which store implementation address in storage index of `keccak256("proxy.implementation")`.

```solidity
contract Proxy {
    bytes32 private constant _IMPLEMENTATION = keccak256("proxy.implementation");
    ...
}
```

The storage index of `keccak256("proxy.implementation")` is used but the storage layout report from compiler will be:

```json
"storageLayout": {
    "storage": [],
    "types": {}
},
```

It will be useful to register the used storage index into report for further check by slither or other security tools.

## Specification

Adding special comment like below or other naming. The comment should include the type.

```solidity
contract Proxy {
  /// @solidity:storage-layout address
  bytes32 private constant _IMPLEMENTATION = keccak256("proxy.implementation");
  ...
}
```

## Backwards Compatibility

There's no backwards compatibility issue.

**Comment by SaadOps** [comment]
Can you guide me to the codebase

**Comment by cameel** [comment]
I'm not sure I fully understand what is being requested here. You want to be able to annotate that a certain constant could have been a variable and would have been taking up a storage slot then?

What is the expected output? What would happen if there were two such constants next to each other? Or if it's followed by a variable that actually takes up the slot?

Overall, this might be something that would be solved as a part of a feature for overriding the storage layout generated by the compiler. We have a bunch of feature requests for that:
- #597
- #4519
- #8353
- #12513
- #12920

Is there anything here that would not be covered by these? For example if we had #4519 you could just put an explicit gap next to such a constant to "reserve" its slot.

**Comment by ekpyron** [comment]
From what I understand the proper solution to this issue would be https://github.com/ethereum/solidity/issues/597, so I'm closing this. Feel free to reopen, if you disagree.
