### ISSUE TITLE
Example on Getter functions does compile but does not include the entire set of data

### ISSUE THREAD

**Issue by nicolasguasca1** [ethereum/solidity#13470]
## Page

Here is the documentation [link](https://docs.soliditylang.org/en/v0.8.16/contracts.html?highlight=nested%20mapping#getter-functions)

## Abstract

This contract:

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.4.0 <0.9.0;

contract Complex {
    struct Data {
        uint a;
        bytes3 b;
        mapping (uint => uint) map;
        uint[3] c;
        uint[] d;
        bytes e;
    }
    mapping (uint => mapping(bool => Data[])) public data;
}
```

Compiles but when deployed and called via the getter function of the mapping, there are three values the result doesn't bring: map mapping, c and d.

Any idea on why this happens?

**Comment by Marenz** [comment]
Thank you for your report!

The issue you see is actually documented in the same link you provided:

> It generates a function of the following form. The mapping and arrays (with the exception of byte arrays) in the struct are omitted because there is no good way to select individual struct members or provide a key for the mapping:

So this is expected behavior.
I'll be closing the issue. Feel free to re-open if you think this is wrong.

**Comment by nicolasguasca1** [comment]
Thank you for your reply @Marenz. I now understand the quote you cited. Should I assume this piece of code should NOT be used as it is not possible to retrieve the map in the conventional way as with the rest of the variables? Let me know and thank you so much again for your help!
