### ISSUE TITLE
Missing "statement has no effect" diagnostic

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#13471]
```solidity
contract C {
    receive() payable external {
        this;
        msg.sender;
    }
}
```

The compiler does not emit the warning "Statement has no effect." for these statements.

https://github.com/ethereum/solidity/blob/51929652291a833889c2f3132b2ca6f037c02a56/libsolidity/analysis/StaticAnalyzer.cpp#L186-L192

I think we need to consider statements that are beyond pure for this diagnostic.

**Comment by ekpyron** [comment]
This is at least partly intentional to allow using such statements for explicitly silencing the "Mutability can be restricted to..." warnings... not that that's beautiful, but that's the reasoning behind this.

**Comment by hrkrshnn** [comment]
Turns out this was done purely to avoid solidity prettier / linter errors.
