### ISSUE TITLE
Add a matrix bot that expands github issue/pr numbers to links

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#13483]
As the headline says, simply a bot that listens for any pattern of `#<numbers>` and either edits the message if that is possible and replaces it with a link or post an additional message with the link.

Side node: Github doesn't differentiate between PRs/issues in links, so you could always use the pattern

`https://github.com/ethereum/solidity/pull/<num>` and it will work, no matter if PR or issue.

**Comment by Marenz** [comment]
Related to https://github.com/ethereum/solidity/issues/13482

**Comment by cameel** [comment]
Removing `should have` label since it looks like we actually do not have a consensus on whether we want that and in what exact form.
