### ISSUE TITLE
Function pointer SSTORE behavior difference

### ISSUE THREAD

**Issue by antonper** [ethereum/solidity#13480]
## Description

During the assignment in the constructor `f = bar`, 
SSTORE to word 0x0 with data as:
0x0000000000000000000000000000000000000000000000000000004700000101
During the assignment in the swap function `f = f == bar ? foo : bar`, 
SSTORE to word 0x0 with data as:
0x000000000000000000000000000000000000000000000000000000000000013e - first swap
0x0000000000000000000000000000000000000000000000000000000000000101 - second swap

The storage operation on constructor and in function SSTOREs different word.
The internal storage pointer is 8 bytes, while only 4 bytes is used for the actual bytecode offset.
What are the first 4 bytes are used for? "0x00000047" in this case.
Why does the "0x00000047" is dropped during the SSTORE inside function calls?

## Environment

- Compiler version: Version: 0.8.16+commit.07a7930e.Linux.g++

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.16;

contract Test{
    function() pure returns (string memory) f = bar;

    function bar() pure private returns (string memory) {
        return "bar";
    }
    function foo() pure private returns (string memory) {
        return "foo";
    }

    function run() public returns (string memory) {
        return f();
    }

    function swap() public {
        f = f == bar ? foo : bar;
    }

}

```

**Comment by Marenz** [comment]
I find it a bit difficult to follow your description. Could you write what you expect to see with your reproduce-code and what you actually see? That would make it easier to evaluate the issue :)

**Comment by antonper** [comment]
```solidity

// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.16;

contract Test{
    function() pure returns (string memory) f = bar;

    function bar() pure private returns (string memory) {
        return "bar";
    }

    function run() public returns (string memory) {
        return f();
    }

    function set() public {
        f = bar;
    }

}

```
Reduced the example even more.
After deployment, the 0x0 storage slot value is 
0x00000000000000000000000000000000000000000000000000000040000000aa
After call to set() the 0x0 storage slot value is 
0x00000000000000000000000000000000000000000000000000000000000000aa
Note the missing 4 after set(). 
Question: Why function pointer storage slot end is ``40000000aa`` after constructor call and  ``00000000aa`` after set call?

**Comment by hrkrshnn** [comment]
This is to make `function` pointers work both in construction and runtime context. Some more details can be found in the following comment: https://github.com/ethereum/solidity/issues/12911#issuecomment-1094747593

At runtime, the result would be `and`-ed. So the higher order bits should not matter (calling run should give the correct result). Closing this for now. Feel free to reply / open if you still have questions.

**Comment by antonper** [comment]
Thank you a lot of explanation
