### ISSUE TITLE
Revert statement not working with ternary operator

### ISSUE THREAD

**Issue by emretepedev** [ethereum/solidity#13490]
## Abstract

The ternary operator we use to write shorter and more readable code cannot be used with the revert statement.

## Motivation
Example,
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.16;

contract Foo {
    error One();
    error Two();
    
    function foo(bool _bool) public {
        _bool ? revert One() : revert Two();
    }
}
```
And it gives this error:
`ParserError: Expected ':' but got identifier
--> Foo.sol:9:24:
|
9 | _bool ? revert One() : revert Two();
| ^^^`

Another example,
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.16;

contract Foo {
    error One();
    error Two();
    
    function foo(bool _bool) public {
        revert _bool ? One() : Two();
    }
}
```
And it gives this error:
`ParserError: Expected '(' but got '?'
--> AttackerForce.sol:9:22:
|
9 | revert _bool ? One() : Two();
| ^`

**Comment by leonardoalt** [comment]
The ternary operator is used to return expressions and not to execute statements.

https://docs.soliditylang.org/en/v0.8.16/types.html?highlight=ternary#ternary-operator
