### ISSUE TITLE
Document UnusedStoreEliminator

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13497]
## Page

https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-steps
https://docs.soliditylang.org/en/latest/yul.html#optimization-step-sequence.

## Abstract

The `UnusedStoreEliminator` optimizer step is not listed in the documentation. Neither #12672 nor #12311 provided any docs for it.

When fixing, please also check if all the other [steps listed in `Suite.cpp`](https://github.com/ethereum/solidity/blob/develop/libyul/optimiser/Suite.cpp#L241-L287) are present in the docs.

**Comment by nikola-matic** [comment]
@cameel 
As far as undocumented steps are concerned:
`ExpressionInliner` is not documented at all from what I can see.
`RedundantAssignEliminator` has been renamed to `UnusedAssignEliminator`, but the docs haven't been updated to reflect this.
Should this be done as part of this issue and perhaps #13501 (doesn't make sense to me), or this issue and separate PRs, or should a completely separate issue be opened?

**Comment by cameel** [comment]
Depends. If you'll be doing it yourself immediately (even if in a separate PR), opening new issues is not necessary. But if you want to leave it for later or have someone else do it, might make sense to open a new issue with proper title/description. Up to you I'd say.
