### ISSUE TITLE
Add examples of using memory structs in documentation

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#13504]
> The [documentation doesn't even show memory structs at all](https://docs.soliditylang.org/en/v0.8.13/types.html#structs): it looks as if they're just a hack to get packed storage variables

See: https://github.com/ethereum/solidity/issues/13475#issuecomment-1239993739

**Comment by uday03meh** [comment]
Hi @cameel,
Can you please assign me this issue? I would like to work on it.

**Comment by cameel** [comment]
Sure, feel free to try.

**Comment by NunoFilipeSantos** [comment]
Hi @uday03meh do you have PR we can take a look at?
