### ISSUE TITLE
`UnusedStoreEliminator` step missing in documentation

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#13511]
## Summary

In the current documentation on the [Yul-based optimizer steps](https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-steps), the step `UnusedStoreEliminator` is missing.

**Comment by hrkrshnn** [comment]
Actually, duplicate of https://github.com/ethereum/solidity/issues/13497
