### ISSUE TITLE
A variable can be bound to a type name, but it cannot be used as a type name

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1352]
Version `0.4.5-develop.2016.11.10+commit.ca78f742.Linux.g++` emits this error message
```
int.sol:4:9: Error: Name has to refer to a struct, enum or contract.
        x y;
        ^
```
for this program:
```
$ cat int.sol 
contract C {
    function f () {
        var x = int;
        x y;
    }
}
```

I think `var x = int;` should not be compilable if there is no use for `x`.

**Comment by federicobond** [comment]
There is a `typeof` reserved keyword which could eventually be applied to these kinds of expressions. It could also prove useful when implementing pattern matching.

**Comment by axic** [comment]
This should be gone with 0.5.0 given #3301.

@pirapira @chriseth should we close?

**Comment by pirapira** [comment]
Sounds good to close.
