### ISSUE TITLE
Calculate "CREATE2" address

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#13521]
The `new` operator now supports the "CREATE2" opcode, by using the syntax `new MyContract{salt:xx}(<constructor params>)`
Calling this method in a view context prior deployment let us get the "counterfactual" address.
But once the contract is deployed, there is no easy way to get its address: 
We have to use the "messy" format of
```
        return keccak256(abi.encodePacked(bytes1(0xff), address(this), salt, keccak256(abi.encodePacked(
                type(MyContract).creationCode,
                abi.encode(<constructor params>)
            ))));
```

This method would work, but has several drawbacks:
- an ugly boilerplace, easy to mis-type
- no type-checking on constructor parames

### Suggestion:
add a new `action` parameter to the "new" operation, in addition to the "salt", with the following values:
- `action: create`. This is the default, which will attempt to create the contract, and fail if CREATE2 fails (it is already exists)
- `action: address`. Just calculate the address, but don't attempt to create it
   e.g. `addr = new MyContract{salt: 0, action: address}(...)`
- `action: auto`. Calculate the address (using **action:address**). If it is already deployed, return this address, otherwise,  perform **"action: create"**

**Comment by cameel** [comment]
Is extending `new` this way really a good idea? `new` implies that something gets created. I think a new `abi.` function for that might be move intutitive and more consistent with that we already have in the language.

**Comment by axic** [comment]
Starting from this comment we discussed syntax for this: https://github.com/ethereum/solidity/issues/2136#issuecomment-559196297

**Comment by axic** [comment]
Actually we do have an older issue for this: #8798. Closing to keep the discussion from getting split across issues.
