### ISSUE TITLE
Semantic test for copying calldata structs placed in the wrong subdirectory

### ISSUE THREAD

**Issue by matheusaaguiar** [ethereum/solidity#13543]
It seems that [test/libsolidity/semanticTests/structs/copy_from_calldata.sol](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/semanticTests/structs/copy_from_calldata.sol) is misplaced, since it does not involve structs at all, but rather just dynamic arrays. Shouldn't it be inside `array` subdirectory? 
Noticed the possible issue [here](https://github.com/ethereum/solidity/pull/13464#issuecomment-1239819462).

**Comment by cameel** [comment]
True. We should move it and any other non-struct tests from that dir. But I think we should also add an actual test for copying calldata structs.

**Comment by KatyaPrusakova** [comment]
Hi, I would like to contribute, it would be my ever [good first issue] , so I hope it works :)

**Comment by cameel** [comment]
Sure! Feel free to create a PR.

**Comment by nikola-matic** [comment]
> True. We should move it and any other non-struct tests from that dir. But I think we should also add an actual test for copying calldata structs.

We already have these:
```
copy_struct_with_nested_array_from_calldata_to_memory.sol
copy_struct_with_nested_array_from_calldata_to_storage.sol
```
