### ISSUE TITLE
Ignore JSON formatting in command-line tests

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13552]
Related to #13544 and #7665.

Currently command-line tests in StandardJSON mode expect output exactly matching the expectations. This is not a problem until we try to post-process the output and run into problems like #13544.

Since the formatting is irrelevant most of the time, I think `cmdlineTests.sh` should be using `jq` on the output and expectations to reformat them before diffing.

We'll also need a way to disable this to keep tests for the `--pretty-print` CLI option functional. I'd go with that I suggested in #7665, i.e. disable this mode when a file called `no-pretty-print` exists in the test directory.

**Comment by Krish-bhardwaj** [comment]
Hi @cameel i have been doing open source contribution for a long time and i have worked on solidity language , i would like to push my self to solve  some more complex problem in Open source projects like this if you can guide and assign me this issue it would be really help full 
Thanks in advance

**Comment by cameel** [comment]
Maybe you could drop by at the [#solidity-dev](https://app.element.io/#/room/#ethereum_solidity-dev:gitter.im) channel to discuss this first? This is an easy issue but it's also very low priority so I'd rather find something more relevant for you. But this depends on how comfortable you are with C++ so we should talk a bit first.

**Comment by Krish-bhardwaj** [comment]
Yes sir I am comfortable in cpp I have been doing competitive programming for a long time and I have used cpp over there rest it will be better for me if I solve a low priority issue first as this can give me some time to learn new this also rest it's up to you if you can guide me I would take up this issue and solve it.

**Comment by cameel** [comment]
The problem with low priority issues though is that we get so many PRs solving them that we're currently struggling to get through the backlog (65 open PRs now, down from ~100 not so long ago) and they're taking the team's attention away from the real stuff we should be working on. We do appreciate contributions, but I'd rather find you something related to our current roadmap than this random issue :) Especially that the work to do here is pretty much all Bash, not C++.

If you're good at C++, that's great! We're really in need of more skilled contributors who can take on tasks that are not just simple refactors.

**Comment by cameel** [comment]
@Krish-bhardwaj How about #13652?
