### ISSUE TITLE
Yul formatter

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13550]
This came up in https://github.com/ethereum/solidity/issues/12570#issuecomment-1253478487.

The compiler can parse Yul and output it after processing. Implementing a pretty-printer mode for Yul that does no actual processing would be trivial and potentially useful.

Not sure if we actually want to do this (it's a bit tangential to compiler's main purpose) but on the other hand we already have all the pieces for it. Similar to the situation in #12753.

**Comment by timweri** [comment]
Hi. I'm looking at this issue. Just want to confirm something, say I have this Yul code:
```yul
// test.sol
{
    let a := 1
    {{ let b := 1
    let d := add(a, b)
    }}
}
```

Is this output from `solc --yul test.sol` what is wanted as pretty-printed Yul?
```yul
object "object" {
    code {
        let a := 1
        {
            {
                let b := 1
                let d := add(a, b)
            }
        }
    }
}
```

Or is this what we are looking for:
```
{
    {
        let a := 1
        {
            {
                let b := 1
                let d := add(a, b)
            }
        }
    }
}
```

**Comment by cameel** [comment]
Good question. I think it might be better for the formatter not to add the `object` if it's not there because then it would have to come up with a name and this could affect the meaning of the code. For example `datasize()` should fail if the object you're referencing does not exist - but if you happen to reference `"object"`, and the formatter adds it, it will compile, potentially obscuring a bug in the code.
