### ISSUE TITLE
[isoltest] Executing semantic tests at arbitrary paths

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13551]
Isoltest can execute contracts using evmone and we use that to implement semantic tests. Currently these tests have to be located inside `test/libsolidity/semanticTests/`. It would be convenient for debugging to be able to use isoltest to execute a code snippet from an arbitrary path by simply giving it that path on the command line.

**Comment by cameel** [comment]
My use case is that I often just go to `/tmp/` and create a file called `test.sol` when I want to try things out. I can easily compile that with `solc` but executing it with `isoltest` is more tedious:
- It has to be copied over to the working copy and shows up as a stray file in git, etc. These are one-offs most of the time and I just prefer them automatically gone on reboot.
- I always build out of tree so I have to add extra args to help isoltest locate my working copy in the first place (`--testpath <working copy path>/test`), which makes the command longer for no good reason.
- Since test names are not full paths, I can't use Bash completion when I do something like `--test=semanticTests/my_test.sol`. I have to type out the full path unless I'm actually inside `test/libsolidity/` in the working copy.

**Comment by ekpyron** [comment]
This needs to properly specify how to determine the test kind for arbitrary-path-tests.

Forcing the test kind to be in the path is ugly and hacky.

So I'd actually replace this by having isoltest consume free arguments and in this case (and this case only) allow and require a test kind argument as well ``isoltest --kind semanticsTests /path/to/file.sol``.

But that's just a suggestion, I'm open to different ways to do this. But I'll degrade this issue to "good first issue candidate" until this is clarified.
