### ISSUE TITLE
ETH on contract created by me

### ISSUE THREAD

**Issue by Lims1703** [ethereum/solidity#13561]
Dear all,

First of all, I really thank you for your time.
I have an issue, I was so stupid and I followed a contract creation and connected my Wallet to send 1ETH on it but it looks like the contract does not allow the created to withdraw the funds. 
Is is possible to connect me on the contract to request the funds to be transfered back to my wallet ?
https://etherscan.io/address/0x36c72af71222AF49016caD945DAFD624699595Cf?fbclid=IwAR1UObohP9AayrvoNweF1YW8vbHpx-O997fn3CgJMRq0wW55mVYwud_qbNw#comments

Here is my contract, I have no strong knowledge in crypto, so any help would be really appreciated.

Thank you,

Lims

**Comment by hrkrshnn** [comment]
We wouldn't be able to do anything, especially when the code is not published.

Closing this. Feel free to reply with a link to the code, and if there is something obvious, maybe it's possible to tell.

**Comment by Lims1703** [comment]
Many thanks @hrkrshnn for your reply.
Here is the code:
https://pastebin.com/raw/hR7EzaZt
If any advice, clarification on what to do next, that would be so helpful!
Lims

**Comment by hrkrshnn** [comment]
@Lims1703 Unfortunately, that looks like one of those uniswap front running scams. Can't find an obvious way to get the money out. The only way to withdraw is using `withdraw`, but it forwards the eth into a fixed address that is obfuscated.
