### ISSUE TITLE
Data location question?

### ISSUE THREAD

**Issue by yyx1111** [ethereum/solidity#13563]
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract test {
    uint[] x; // x 的数据存储位置是 storage，　位置可以忽略

    function f() public {
        x = new uint[](7);
        uint[] storage b = new uint[](7);  //error,    create an independent copy?
    }
}
```

**Comment by naveed949** [comment]
@yyx1111 within the scope of a function
1. you can instantiate a storage variable like you did for x i.e: `x = new uint[](7);`
2. you can point OR refer a storage variable with internal variable e.g: `uint[] storage b = x;`
3. but you can not declare OR define a new storage variable within the scope of a function i.e: `uint[] storage b = new uint[](7);` (as variables defined / declared within the scope of a function has to be erased after execution but storage variables doesn't)

**Comment by Marenz** [comment]
This is the wrong place for these kind of questions so I am closing this. You can try the [matrix solidity room](https://matrix.to/#/#ethereum_solidity:gitter.im) for solidity help questions.
