### ISSUE TITLE
Feature Request: return the slot index for a given variable

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/solidity#13585]
Dear Solidity dev community, just wanna ran this idea by you: Can we have a built-in method for solidity to return the slot index of a variable? Just like the `type(SomeInterface).interfaceId;` returns the interfaceId for the type `SomeInterface`, returning the slot index making it so much less error-prone when needing to work with SSTORE and SLOAD and other things. I am sure this information already exist in the compiler. The benefit is making it more testable and easy to interact with other APIs

Please also help advise if this is no the right channel to make suggestions. Is there something like Solidity Improvement Proposal?

**Comment by nikola-matic** [comment]
You can already get a slot index and byte offset of a variable in inline assembly, as `x.slot` and `x.offset`. [Documented here](https://docs.soliditylang.org/en/latest/assembly.html#access-to-external-variables-functions-and-libraries). I don't think adding (or rather copying/moving) such low level options into Solidity itself makes sense; after all, the whole purpose of Solidity is to provide a higher abstraction layer precisely so you don't have to worry about these things, and if you really want to, that's what inline assembly is for.

**Comment by ekpyron** [comment]
Inline assembly is also the only place in which you'd actually be working with ``sstore``s and ``sload``s anyways.
I'm assuming that you actually just wanted ``.slot`` and ``.offset`` that already exist as suggested by @nikola-matic and am thereby closing the issue - but feel free to reopen in case we misunderstood what you wanted and this is not already covered by the existing ``.slot`` and ``.offset`` access from inline assembly.
