### ISSUE TITLE
OS X El Capitan Cmake error

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1358]
Appears I just installed all the new dependencies and now I cannot seem to build properly on latest develop branch.

```
CMake Error at CMakeLists.txt:16 (include):
  include could not find load file:

    deps/jsoncpp.cmake
```

**Comment by VoR0220** [comment]
nvm fixed it. Had to update the submodule.

**Comment by ameten** [comment]
@VoR0220, could you advise what submodule you have updated and how?

**Comment by VoR0220** [comment]
Iirc i ran "git submodule update" and it just worked.
