### ISSUE TITLE
Pretty Format Opcode Output

### ISSUE THREAD

**Issue by wjddnjstj** [ethereum/solidity#13596]
As of now, solidity compiler produces the output for the opcode file as one line (shown below)
<img width="816" alt="Screen Shot 2022-10-01 at 2 02 46 PM" src="https://user-images.githubusercontent.com/60459873/193424378-ee836d1e-e629-4cab-ab64-e76c1a923a96.png">

Is there any way the opcode file could be formatted or have an option to be prettified before it's produced?

An example of what I'm desiring is shown below:
<img width="682" alt="Screen Shot 2022-10-01 at 2 06 40 PM" src="https://user-images.githubusercontent.com/60459873/193424500-69294e95-e9e5-4754-a67d-43941aa0e299.png">

I'm trying to solve this manually by writing an additional function to go through the produced output file and add a newline delimiter every time an operand is seen, but I think it could be beneficial if there was an option to prettify it before it's produced.

Any help will be appreciated, thank you!

**Comment by cameel** [comment]
What is your use case?

If you want to see the bytecode in a more readable form, you can request the assembly with `solc --asm --debug-info none`:
```
EVM assembly:
  mstore(0x40, 0x80)
  callvalue
  dup1
  iszero
  tag_1
  jumpi
  0x00
  dup1
  revert
tag_1:
  pop
  dataSize(sub_0)
  dup1
  dataOffset(sub_0)
  0x00
  codecopy
  0x00
  return
stop

sub_0: assembly {
      mstore(0x40, 0x80)
      0x00
      dup1
      revert

    auxdata: 0xa2646970667358221220b55687d4d26f9dab01409070b173f89f77de637640bdd40dfce98e96c5559d8d64736f6c63430008100033
}
```

This is is not identical to what you're requesting but might be close enough. As you can see above, it will also correctly distinguish between code and data and will also show separation between subassemblies. On the opcode list all of these look like opcodes:
```
PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH1 0xF JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x3F DUP1 PUSH1 0x1D PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN INVALID PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x0 DUP1 REVERT INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 0xB5 JUMP DUP8 0xD4 0xD2 PUSH16 0x9DAB01409070B173F89F77DE637640BD 0xD4 0xD 0xFC 0xE9 DUP15 SWAP7 0xC5 SSTORE SWAP14 DUP14 PUSH5 0x736F6C6343 STOP ADDMOD LT STOP CALLER
```

**Comment by nikola-matic** [comment]
Hi @wjddnjstj, since we're going to be dropping support for `--opcodes` (see https://github.com/ethereum/solidity/issues/14033), I'm closing this issue as won't do.
