### ISSUE TITLE
The storage layout of the internal function type

### ISSUE THREAD

**Issue by hydai** [ethereum/solidity#13603]
## Description

Hi teams,

I am doing some research on the storage layout. According to the documents, the external function type is 24 bytes(20 bytes for the contract address and 4 bytes for the function selector). ref: [1], [2]

However, when I try to declare an internal function type, I found that the size is only 8 bytes. But I have no idea what's the meaning of these 8 bytes.

Is there any document to identify this?
Thanks.

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): London
- Framework/IDE (e.g. Truffle or Remix): Remix

## Steps to Reproduce

Here is the minimal contract to show the storage layout of the internal function type and external function type:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

contract FuncType {
    function(uint256) pure internal returns (uint256) internalFunc;
    function(uint256) pure external returns (uint256) externalFunc;
}
```

The storage layout from remix IDE:
```json
{
	"storage": [
		{
			"astId": 9,
			"contract": "contracts/SolidityTutorial/st.sol:FuncType",
			"label": "internalFunc",
			"offset": 0,
			"slot": "0",
			"type": "t_function_internal_pure(t_uint256)returns(t_uint256)"
		},
		{
			"astId": 17,
			"contract": "contracts/SolidityTutorial/st.sol:FuncType",
			"label": "externalFunc",
			"offset": 8,
			"slot": "0",
			"type": "t_function_external_pure(t_uint256)returns(t_uint256)"
		}
	],
	"types": {
		"t_function_external_pure(t_uint256)returns(t_uint256)": {
			"encoding": "inplace",
			"label": "function (uint256) pure external returns (uint256)",
			"numberOfBytes": "24"
		},
		"t_function_internal_pure(t_uint256)returns(t_uint256)": {
			"encoding": "inplace",
			"label": "function (uint256) pure returns (uint256)",
			"numberOfBytes": "8"
		}
	}
}
```

[1]: https://docs.soliditylang.org/en/v0.8.17/abi-spec.html#function-selector
[2]: https://docs.soliditylang.org/en/v0.8.17/internals/layout_in_storage.html

**Comment by cameel** [comment]
We consider the interpretation of internal function pointer value to be an implementation detail, which is why this is undocumented. In the legacy codegen they're jump addresses (or a combination of two addresses to account for differences between construction and deployed bytecode). In the IR codegen they're just arbitrary IDs assigned to functions by the compiler.

I'm closing this since this does not look like a bug report or a feature request. I think that our [forum](https://forum.soliditylang.org) is a better place to ask these kinds of questions.

**Comment by AmadiMichael** [comment]
@hydai did you later ask about this in the forum? if yes, mind sharing a link? would love to read more on it.
