### ISSUE TITLE
Extend AST FunctionCall to contain SourceLocation of named arguments.

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#13608]
Result from posted by @christianparpart in https://github.com/ethereum/solidity/pull/12790#discussion_r986998412_

In order to properly locate references of named function call parameters, we need to adapt the AST a bit.

This is not directly related to the LSP, but in the LSP we could make use of this information in order to properly find all references when when pointing to a named argument (or to the function parameter's name, it should also find the names for named-argument function calls.)

**Comment by cameel** [comment]
@christianparpart Can you update the description to say more precisely what exactly needs to be added to the AST?

Also, changing the AST does not sound like a refactor. This will be visible to tools that export the AST.

**Comment by cameel** [comment]
Also, for anyone implementing this in the future: when this is done, we should add an LSP test case to make sure that the LSP now finds references to named arguments in cases like this:

```solidity
function f(uint x) {}

function g() {
    f({x: 1});
}
```

**Comment by ekpyron** [comment]
Since the AST does contain the locations of named arguments, I'm not sure what this issue is actually asking for - so I'm closing.

**Comment by christianparpart** [comment]
@ekpyron the source locations for named arguments are/were needed in the language server to be able to properly highlight their location with the right syntax color (but also for semantic token coloring) _or_ e.g. to properly rename the the parameter variable not just on the callee side but also on the caller side.

**Comment by ekpyron** [comment]
But ``FunctionCall::nameLocations()`` *does* already contain those source locations, doesn't it?

**Comment by christianparpart** [comment]
At the time of writing this ticket it clearly didn't. Maybe now. I don't know. I however do not know if anyone will ever pick up LSP or related tooling that would require this information
