### ISSUE TITLE
Remove redundant checks for lower bounds of `calldatasize() > 3`

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#13623]
The contract
```solidity
  contract C {
      uint public x;
  }
```
generates
```
            {
                let _1 := memoryguard(0x80)
                mstore(64, _1)
                if iszero(lt(calldatasize(), 4))
                {
                    let _2 := 0
                    if eq(0x0c55699c, shr(224, calldataload(_2)))
                    {
                        if callvalue() { revert(_2, _2) }
                        if slt(add(calldatasize(), not(3)), _2) { revert(_2, _2) }
                        mstore(_1, sload(_2))
                        return(_1, 32)
                    }
                }
                revert(0, 0)
            }
```

The revert in ` if slt(add(calldatasize(), not(3)), _2) { revert(_2, _2) }` is unreachable. We should remove this.

There are two ways to do this:

1. The check for `calldatasize` lower bounds should only be done if there is at least one parameter.
2. Build a symbolic solver that can infer this property.

**Comment by cameel** [comment]
> 1. The check for calldatasize lower bounds should only be done if there is at least one parameter.
> 2. Build a symbolic solver that can infer this property.

Given that (1) is just a simple `if` in the codegen, I think that waiting for the solver would be a bit of an overkill here :)

By the way, `if iszero(lt(calldatasize(), 4))` is redundant too. At least as long as the last byte of the selector is non-zero (and this can be determined at compilation time).

**Comment by hrkrshnn** [comment]
> By the way, if iszero(lt(calldatasize(), 4)) is redundant too. At least as long as the last byte of the selector is non-zero (and this can be determined at compilation time).

Why? `calldatasize` is dynamic and can only be known at runtime? @cameel

**Comment by cameel** [comment]
Because if it's shorter than 4 bytes, `if eq(0x0c55699c, shr(224, calldataload(_2)))` will never be true so the code will lead to the same revert.

**Comment by hrkrshnn** [comment]
Ah I see. We can only do that change in codegen if there is no function that has a selector 0.

It's also worth thinking if that check should be delayed to the end of the function dispatch.

**Comment by cameel** [comment]
> if there is no function that has a selector 0.

I'd say more generally, if the selector does not end with a zero byte (otherwise a truncated selector in calldata might match).

> It's also worth thinking if that check should be delayed to the end of the function dispatch.

I think we would risk going into the wrong branch with truncated calldata so probably no.

**Comment by hrkrshnn** [comment]
> if the selector does not end with a zero byte

Why zero byte? @cameel

**Comment by cameel** [comment]
Because otherwise when you send e.g. `0x112233` in calldata it would match selector `0x11223300`. The size check is only redundant if the selector does not end with a zero. Otherwise zeros read past the end could be mistaken for actual zeros sent by the client.

**Comment by A-Ashraf** [comment]
Has this issue been fixed? If not I would like to try working on it.
