### ISSUE TITLE
Address methods are not properly documented

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1363]
Addresses seem to have the following methods:

balance()
send()
call()
callcode()
delegatecall()

Some of these methods can be chained with gas() and value()

I can't find any good documentation on these methods.

Currently there is:
http://solidity.readthedocs.io/en/develop/types.html#address
http://solidity.readthedocs.io/en/develop/units-and-global-variables.html#address-related

**Comment by axic** [comment]
I think adding `gas()` and `value()` to the types chapter would make sense.

I'm not sure why we duplicate some of the information in _global variables_, but if we keep doing that, it should include all member names.

**Comment by chriseth** [comment]
Some of the documentation assumes some knowledge of the underlying architecture, but that should obviously be minimized. All functions that perform an actual EVM call (it should be visible from the documetation which of them do) also have the `gas` and `value` members unless they are non-payable, then they only have gas.

**Comment by axic** [comment]
All the methods are now described in the types section. The global variables needs an update as well as `value` and `gas` should be documented.
