### ISSUE TITLE
Define storage variables in the constructor

### ISSUE THREAD

**Issue by dalechyn** [ethereum/solidity#13645]
## Abstract
You can't implicitly define storage variables in the constructor and have to define ones explicitly.

It forces developers to **always** define the state variables explicitly:
```solidity
contract Contract {
  uint256 a;
  uint256 b;
  constructor(uint256 _a, uint256 _b) {
    a = _a;
    b = _b:
  }
}
```

Such not only expands the overall source size but also creates possible security flaws when dealing with **underscores**. There are plenty of cases when developers have forgotten to put one, leading to _incorrect logic execution_ with _loss of funds_. 

## Motivation
Such has been a feature in many languages.

Consider the next JavaScript example:
```js
class ContractLike {
  constructor(public a, private b) {}
}
```
It's much simpler to define variables this way, instead of
```js
class ContractLike {
  public a;
  public b;
  constructor(a, b) {
    this.a = a;
    this.b = b;
  }
}
```

Solidity should follow the latest industry standards and keep with them where possible.

## Specification

If variables put in `constructor` come with state visibility parameters, they are automatically placed on the storage top in the same order they are put in the `constructor`.

Example:
```solidity
contract Contract {
  constructor(address public a, uint256 public immutable b, bool private c, int128 internal d) {
    a = 0x0123456789ABCDEF0123456789ABCDEF01234567;
    b = 11;
    c = false;
    d = -12;
  }
}
```
If there are explicitly declared storage variables, they are put after the ones defined in the constructor (or before, depending on the implementation details).

## Backwards Compatibility
The feature is fully backward compatible as it does not break the current syntax but only extends it.

**Comment by ekpyron** [comment]
This would violate the design principles of solidity in explicitness and clear readability of the storage layouts, so I'm closing this.
