### ISSUE TITLE
Performance Improvements of the UnusedAssignEliminator

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#13689]
This is a list of ideas to improve the performance of the UnusedAssignEliminator.

One of the main problems in the UnusedAssignEliminator is that the `map`s are really large.
We could improve the performance by removing variables from the map at they point where they are last referenced.

**Comment by NunoFilipeSantos** [comment]
@chriseth I don't see a list. 🤔

**Comment by chriseth** [comment]
The compenent has been fully re-implemented. This issue is not helpful.
