### ISSUE TITLE
The `indexed` modifier can be specified multiple times for event arguments

### ISSUE THREAD

**Issue by blitz-1306** [ethereum/solidity#13681]
## Description

```solidity
pragma solidity ^0.8.17;

interface Foo {}

interface Bar {
    event MyEvent(Foo indexed indexed indexed some);
}
```

The above contract is _compiled_ while my expectation was to get a parse error. Other tools are failing to parse such source. For an instance, `solidity-coverage` HardHat plugin is failing on it. Is it intended to use multiple `indexed` entries for event arguments? Also is it documented somewhere?

## Environment

This is reproducible in Remix IDE.

## Steps to Reproduce

Run code sample from "Description" section in Remix IDE.

Regards.

**Comment by cameel** [comment]
I don't think it's intended. Looks like a bug to me. We don't allow that with any other modifier.

**Comment by Coollaitar** [comment]
Is anyone working on this issue??
I really want to contribute can anybody assign me for this issue?

**Comment by cameel** [comment]
There's already a PR for this issue waiting for review (#13816). Please choose one of the other things marked as [`good first issue`](https://github.com/ethereum/solidity/labels/good%20first%20issue).

**Comment by Coderayush13** [comment]
hey can you assign this issue to me

**Comment by ekpyron** [comment]
> hey can you assign this issue to me

As @cameel said, there is already a PR addressing this issue, so it not up for taking by anyone else.
