### ISSUE TITLE
Invalid stack size error for inline assembly

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1368]
The new inline assembly warning about imbalanced stack size is wrong in the following code. It might be caused by the variable.
```
contract c {
 function () {
  assembly {
      let x := 1
  }
 }
}
```

**Comment by axic** [comment]
Yes, it seem that variable assignment messes with it.

#1204 works as it should, except with the `let` example.

**Comment by chriseth** [comment]
Ah right, the variable cleanup block https://github.com/ethereum/solidity/pull/1224/files#diff-96cd46c6082618c350fdb46960bb80c6R242 has to go before the check.
