### ISSUE TITLE
Improve LoadResolver

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#13699]
This is the leftover task of https://github.com/ethereum/solidity/issues/6727 :  Improve LoadResolver to know that memory is zero initially

We could also improve it so that it knows that storage is zero in the constructor.

Additionally, we should also improve the way keccak knowledge is cleared on memory writes.

**Comment by cameel** [comment]
How much is this expected to improve things? I guess not much judging by how it was left hanging for so long?

**Comment by chriseth** [comment]
Adding the knowledge that storage is zero in the constructor could make quite a big improvement especially for packed storage. We might have to drag this through into function calls (especially when they are only called once).

**Comment by cameel** [comment]
I think this issue is now redundant. The part about zeroed memory/storage is covered by #13099, and looks like #12274 dealt with not erasing knowledge about keccak on memory writes.
