### ISSUE TITLE
Optimizer should optimize away body containing only call to super

### ISSUE THREAD

**Issue by joshlangs** [ethereum/solidity#13710]
Consider these two contracts:
```
contract MeowBase
{    
    function meow() public virtual view returns (uint256)
    {
        return address(this) == msg.sender ? 1 : 0;
    }
}
contract Meow is MeowBase
{
    function meow() public override view returns (uint256) 
    {
        return super.meow(); 
    }
}
```

Compiling them with solidity 0.8.17 and optimizations 999999999 creates two contracts of different size.  `MeowBase` is `145 bytes` and `Meow` is `157 bytes`.

Curiously, if the body of `MeowBase` just contained `return 1;` or other simple stuff, the contract sizes turn out the same.  Adding a conditional which can't be optimized away creates the size difference

But regardless...

`return super.meow()` should be optimized away completely

The particular use case that brought this up for me is testability/mocking.  Using the above example, I would create a `MeowTest` contract derived from `MeowBase` with additional functions/overrides allowing me to control the return value of `meow()` for various tests - but users of the contract would only derive from `Meow` and shouldn't be able to override `meow()`.

**Comment by ekpyron** [comment]
Both ``Meow`` and ``MeowBase`` produce identical runtime bytecode, if compiled via IR with enabled optimizer.
We're slowly moving towards switching towards via-IR compilation as default, even though we still need some improvements wrt compilation times and tooling support. However, at this point, we won't add features to the legacy optimizer anymore, so given that, I'm closing this issue.

I hope you can use the via-IR pipeline in your use case - if you haven't already, give it a try and report any issues you may have with it back to us! (Using CLI use ``--via-ir --optimize``, using standard-json use ``settings.viaIR: true``).
