### ISSUE TITLE
Possible error in Yul Object example.

### ISSUE THREAD

**Issue by Qlio** [ethereum/solidity#13711]
## Page

https://docs.soliditylang.org/en/latest/yul.html

## Abstract

Hello, I'm trying to understand the Yul Object example code. And there is a code section calling `create` function:
```yul
mstore(add(offset, size), 0x1234)
pop(create(offset, add(size, 32), 0))
```
If I understood correctly, the `create` function is getting parameters in the following order: 1. WEI to send, 2. from address, 3. size of contract. But in this example, the first parameter is the contract's address and the third parameter is 0. 

I'm new to Yul, and if this bug is not correct, please consider giving me an explanation of the code. Thank you.

## Pull request

https://github.com/ethereum/solidity/pull/13712

**Comment by cameel** [comment]
So I guess it was fixed by #13712?
