### ISSUE TITLE
1st iteration Generics Design Research

### ISSUE THREAD

**Issue by NunoFilipeSantos** [ethereum/solidity#13725]
First version of a structured concrete design document for generics.

This may also already involve defining weaker transitions in the type system, like introducing tuple types as first-citizen types and tying data locations to types instead of variables, and staging those for implementation. This preliminary transition of the type system may be split into a non-breaking part and a breaking part to be scheduled for the breaking release planned later in the year.

---
References
- #869

**Comment by ekpyron** [comment]
Done

**Comment by alvrs** [comment]
> Done

Where can I find the results of this design research?

**Comment by tinhbao789** [comment]
Good project
