### ISSUE TITLE
Documentation incorrectly states that a mapping `does not keep track of the keys that were assigned a non-zero value`

### ISSUE THREAD

**Issue by peizhao1** [ethereum/solidity#13747]
## Page

https://docs.soliditylang.org/en/v0.8.17/security-considerations.html#clearing-mappings

## Abstract

The double negative seems to read incorrect.

>  that does not keep track of the keys that were assigned a non-zero value

should be

>  that does not keep track of the keys that were assigned a zero value

**Comment by cameel** [comment]
No, it's correct. Mappings do not keep track of their keys, and this includes keys with non-zero value (i.e. the ones that you would expect to be affected by `delete`). That's why using `delete` on a mapping does not clear the values.

**Comment by peizhao1** [comment]
Thank you for the clarification!
