### ISSUE TITLE
Special optimizer rules for boolean context

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#13750]
As suggested by @k06a in https://github.com/ethereum/solidity/issues/13713#issuecomment-1327891344 , we should have a flag for rules in RuleList.h that states that they are used in a "boolean" context.

The problem is that the RuleList is generic. We cannot do the replacement `iszero(iszero(x)) -> x` (because those expressions are not identical), even though it would be valid in the context if `if iszero(iszero(x)) { ... }`.

Similar rules are `iszero(eq(x, y))`, which can be replaced by `sub(x, y)` if we are in a "boolean context".

What is a "boolean context":

An expression is in a "boolean context" if program semantics are only changed if the value of the expression changes between zero and nonzero. Any change inside the nonzero subset keeps the semantics.

Examples of boolean context:

`iszero(X)` - X is in boolean context
`if X { ... }` - X is in boolean context
`for {} X {} { ... }` - X is in boolean context

Implementation notes:

- SimplificationRules::findFirstMatch should obtain a flag to indicate that it only matches in a boolean context
- It should search a seperate list of rules that only apply in boolean context if that flag is true
- ExpressionSimplifier needs to track if we are inside a boolean context - this applies both to `if` as well as builtin calls

Potential complication:

The code is usually in split form, i.e.
```
let x := eq(a, b)
if x { ... }
sstore(0, x)
```
We have to take care that the replacement is only done on the `if` statement, but not inside the sstore call.

NB: Some of these replacements are currently implemented in the peephole optimizer because it can "see" a `jumpi`.

**Comment by k06a** [comment]
I think we need flag if this expression in gonna be used in AND operation or not. Since non-zero works fine for OR operation.

**Comment by chriseth** [comment]
I don't understand what you mean, @k06a - can you give an example? Are you saying that we should detect if an AND / OR is used as a boolean instead of a bitwise or?

**Comment by k06a** [comment]
Hi, I mean in the expression:
```
if and(expr1, or(expr2, expr3)) {
}
```

All the expr1, expr2 and expr3 should be normalized to 0/1 due to outer `and`.

But here is another expression:
```
if or(expr1, and(expr2, expr3)) {
}
```

Here only expr2 and expr3 should be normalized to 0/1, while expr1 can be zero/non-zero.
