### ISSUE TITLE
Add Foundry support to external tests scripts

### ISSUE THREAD

**Issue by r0qs** [ethereum/solidity#13767]
The [prb-math](https://github.com/paulrberg/prb-math/releases) migrated from Hardhat to Foundry in version `3.0.0` and requires that we update our external test scripts to support Foundry builds.

It may also be a good opportunity to migrate those scripts from shell script to python and better organize the external tests.

**Comment by ekpyron** [comment]
I'll actually give this a rather high priority, for two reasons:
- It's good to have a foundry test setup and run the compiler through foundry in general.
- The new version of prb-math is a very good test suite for our more recent features like user-defined value types and will be a very good test case for our upcoming features of user-defined operators and literals soon (while we can expect it to still remain on foundry).

So we don't need to jump at this immediately right now, but we should not put it on the long bench either. Ideally this should be done not too much after the operators and literals PRs are merged.
