### ISSUE TITLE
grammar.txt: IndexedParameterList & ParameterList

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#1376]
Should the key word `indexed` really be optional in `IndexedParameterList` ?

**Comment by chriseth** [comment]
Yes, it is optional, the `indexed` keyword is only valid for event parameters, that is why the `IndexedParameterList` nonterminal exists.

**Comment by walter-weinmann** [comment]
Ok - but now `ParameterList` is a subset of `IndexedParamerList`.

Wouldn't it be better to define:

`EventDefinition = 'event' Identifier ( IndexedParameterList | ParameterList ) 'anonymous'? ';'`

and make a clear distinction between `ParameterList` and `IndexedParameterList` ?

**Comment by chriseth** [comment]
Yes, `ParameterList` is a subset of `IndexedParameterList`. Your suggestion of using `( IndexedParameterList | ParameterList)` does not really convey the fact that you can choose between using `indexed` and not using it for each individual parameter and not the whole list.
