### ISSUE TITLE
Missing tests for StructType::interfaceType function

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1378]
After applying the following change, `./test/soltest` still passes.  This means that the replaced expression is not tested.

```
--- a/libsolidity/ast/Types.cpp
+++ b/libsolidity/ast/Types.cpp
@@ -1477,7 +1477,7 @@ MemberList::MemberMap StructType::nativeMembers(ContractDefinition const*) const
 
 TypePointer StructType::interfaceType(bool _inLibrary) const
 {
-       if (_inLibrary && location() == DataLocation::Storage)
+       if (_inLibrary && true)
                return shared_from_this();
        else
                return TypePointer();
```

**Comment by chriseth** [comment]
The following source code should be a valid test:

```
contract c { struct S { uint x; } function f() returns (S) {}}
```

**Comment by pirapira** [comment]
On this code, the behaviors of the original and the variant are the same.

```
ch.sol:1:57: Error: Internal type is not allowed for public or external functions.
contract c { struct S { uint x; } function f() returns (S) {}}
```

Maybe this conditional branch is hard to reach, and a unit test is necessary to touch this piece.

**Comment by chriseth** [comment]
Next try;

```
library c { struct S { uint x; } function f() returns (S) {}}
```

**Comment by pirapira** [comment]
<del>I still get the same error message on the original and the variant.  "Error: Internal type is not allowed for public or external functions."</del>  No, the test does it.

**Comment by pirapira** [comment]
Maybe I have to say `S storage`
