### ISSUE TITLE
[ast-json] `typeString` field of a function type doesn't have parameters' data locations

### ISSUE THREAD

**Issue by thanhtoantnt** [ethereum/solidity#13780]
## Description

- The `typeString` field of a function type, e.g., `function (string memory) external` is `function (string) external`. 
- It should be `function (string memory) external`

## Environment

- Compiler version: Solidity 0.8.17
- Operating system: Ubuntu 22.04

## Steps to Reproduce
- Input file: https://github.com/ethereum/solidity/blob/develop/test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol
- Running: `solc --ast-compact-json --pretty-json abi_encode_conversions.sol -o . --overwrite`

**Comment by nikola-matic** [comment]
@aarlt can you take a look and triage this, since you're the JSON AST expert? :)

**Comment by ekpyron** [comment]
The reference type arguments for external function types don't *really* involve a data location - you can also assign a function taking a calldata argument to a function pointer taking a memory argument. There's a related issue to actually make data locations on external function pointers optional to clarify this - it's a bit unfortunate that this way it's not precisely possible to construct sources from the AST (until we make the data locations actually optional in function types) - but you can always default to ``memory`` for them and all code should work...
