### ISSUE TITLE
Granular dependencies with deterministic compiler output

### ISSUE THREAD

**Issue by gerben-stavenga** [ethereum/solidity#13791]
## Abstract

I noticed that the bytecode output of contracts change depending on meaningless changes in the source, ie. adding a toplevel constant definition in some of the imports which is not used in the contract itself. The bytecode output of a compiled contract should only depend on the material definitions of the code of the contract and the libraries actually used.
 
## Motivation

A nice pattern is using create2 to deploy contracts at deterministic addresses. The deployed address depends on hashes of the bytecode and will thus change with due to spurious bytecode changes due to the non-determinism of the solidity compiler. This is a pain when developing code that relies on fixed addresses of some contracts. 

See clang as a model of ensuring complete hermetically closed generated output. Within build systems like bazel this is further used to prune recompiles when it detects output of dependent compiles didn't change. 

## Specification

The generated bytecode of a contract should only depend on the AST of the contract in question plus the AST of dependencies (libraries / values). In particular comments and unrelated changes in the AST of the whole file + transitive closure of the imports should not influence the output. In case of non-deterministic algorithms for optimizations the randomness must be generated by a deterministic pseudo-random generator that is seeded deterministically.

## Backwards Compatibility

This change is 100% backwards compatible

**Comment by cameel** [comment]
This is mostly due to the hash of metadata embedded in the binary. Metadata contains hashes of all the source files. You can use `--metadata-hash none` to disable it. Does that solve the issue?

**Comment by gerben-stavenga** [comment]
Oh thank you, I had no idea metadata was embedded.
