### ISSUE TITLE
Explicit contract variable declarations

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#13798]
## Abstract

Currently, when a variable is declared without any modifier being specified, it is considered an internal storage variable implicitly.

```solidity
contract Hello {
    uint age = 2;
    // above is same as:
    uint internal age = 2;
}
```

## Motivation

Have a look at the below two code snippets:

```solidity
contract Logic {
    address recipient = 0xSomeChecksumAddress;

    function rescue(IERC20 token) public {
        uint bal = token.balanceOf(address(this));
        usdc.transfer(recipient, bal);
    }
}

contract Logic {
    function rescue(IERC20 token) public {
        address recipient = 0xSomeChecksumAddress;

        uint bal = token.balanceOf(address(this));
        token.transfer(recipient, bal);
    }
}
```

They both look similar however they function differently under a delegatecall. The first Logic would SLOAD slot 0 while the second Logic would have the address in its bytecode. This might not be a big deal when looking at code with carefully, but might slip when in a hurry. It would be sweet if languages/toolings point out potential mistakes by dev that are easy to detect.

Explicit requirements, notably a lot of them introduced in 0.5.0 ([link](https://docs.soliditylang.org/en/latest/050-breaking-changes.html#explicitness-requirements)), were a great addition to Solidity language because they prevent dev mistakes.

## Specification

I think just not accepting the declaration of storage variables which is ascetically similar to the declaration of temporary variables can be helpful. Some ideas to deal with this, might not be the best.

### Option 1: Explicit mutability when assigned

When the variable is assigned, require the developer to specify `mutable` or `immutable`. This could be ideal and should prevent such dev mistakes.

```solidity
contract Hello {
    uint age; // works
    uint age = 2; // compiler error
    unit constant age = 2; // works, value stored in bytecode
    unit mutable age = 2; // works, value stored in storage
}
```

### Option 2: Just require the developer to specify at least one modifier

This makes it visually clear that it is a storage variable declaration and not a temporary variable stored in bytecode.

```solidity
contract Hello {
    uint age; // works
    uint age = 2; // compiler error
    unit immutable age = 2; // works
    unit public age = 2; // works
    unit internal age = 2; // works
    unit internal immutable age = 2; // works
}
```

## Backwards Compatibility

This feature request proposes a backwards incompatible change. Any code that declares a storage variable along with an initialization value without a modifier will trigger a compiler error.

**Comment by cameel** [comment]
So the issue is that it's easy to be unaware of the cost of an operation when looking at an expression? I'm not really sure if this change would fix that. It addresses only one special case - using a variable directly - and even then only if you have its definition close at hand to look at it.  What if it's hidden in a function instead?

Also, probably a more consistent way to go about it would be to require explicit location for all storage variables:
```solidity
contract C {
    uint storage age;
    address[] storage users;
    bool storage public enabled;
    bool immutable validate;
}
```

I wouldn't actually mind that but I also don't see big demand for that level of explicitness. The risks are much smaller than in case of functions - making a function `public` by accident can be a serious bug and very hard to notice while using `storage` instead of `immutable` just uses more gas.

**Comment by zemse** [comment]
> So the issue is that it's easy to be unaware of the cost of an operation when looking at an expression?

The gas cost aspect is not a big deal, someone who intends to optimize for costs should be able to see it. 

The motivation for asking explicitness is for the case when it works under a delegatecall. Imagine funds being transferred to a zero address (or some weird address) because the logic loads `recipient` from storage. Libraries are always supposed to be delegate called, hence there is an explicit requirement to include a constant keyword in a variable declaration.

```solidity
library Logic {
    uint age = 2; // TypeError: Library cannot have non-constant state variables
    uint constant age = 2; // works
}
```

However, contracts can also be delegate called, but one who intends to declare a constant, forgets to write constant keyword, the contract gets compiled and something else happens.
