### ISSUE TITLE
Unchecked expressions

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#13799]
https://github.com/ethereum/solidity/issues/10698 proposed "unchecked blocks as expressions" and even more generally "blocks as expressions". In the same issue, unchecked operators were discussed (with a few syntax proposals like `+u` or `+!`).

These may be interesting proposals but have perhaps unnecessarily turned a simpler problem into a much larger and more difficult one.

## Abstract

There are at least two concrete patterns using unchecked which are currently not well served by the language:

1) Use of unchecked in loop expression

```solidity
for (uint i; i < x; ) {
    ...;
    unchecked { i++; }
}
```

2) Use of unchecked in variable initialization

```solidity
uint256 apple;
unchecked { apple = banana + cherry; }
```

Both of these could be improved through the introduction of unchecked expressions.

## Specification

Introduce a new unary operator `unchecked` such that the value of `unchecked E` is the value of expression `E` as if it was evaluated in an `unchecked` block.

With this operator we would be able to implement the previous patterns more neatly:

```solidity
for (uint i; i < x; unchecked i++) {
    ...;
}
uint256 apple = unchecked banana + cherry;
```

My initial thoughts are that the precedence of this operator should be lower than arithmetic operators and higher than bitwise operators, so as to enable writing `unchecked a + b`.

It is worth considering that the [Solidity precedence table](https://docs.soliditylang.org/en/latest/cheatsheet.html#order-of-precedence-of-operators) lists "unary operators (`delete`)" with higher precedence than arithmetic operators, and based on this documentation there may be third-party parsers that parse all unary keyword operators with this precedence (unsure of this). For comparison, [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) does have unary keyword operators with different precedences (e.g. `delete` vs `yield`).

Note that if "blocks as expressions" are ever introduced into the language, the syntax `unchecked { ... }` becomes ambiguous but the semantics would be exactly the same, so it should not present a problem.

**Comment by ekpyron** [comment]
I'm closing this for the analog reasons as given in https://github.com/ethereum/solidity/issues/10698#issuecomment-1347357509, since while this is a valid proposal, we're working towards different solutions solving the underlying issues, i.e. on solving this on the type-level instead.
