### ISSUE TITLE
Compiler not detecting pure publie function overload on Library

### ISSUE THREAD

**Issue by JuanuMusic** [ethereum/solidity#13809]
## Description
Overloaded functions on a library don't seem to be picked up by the compiler.
Throws the error:  `error[6675]: TypeError: Member "getValue" not unique after argument-dependent lookup in type(library LibreryWithOverloads).`

## Environment

- Compiler version: tested from v0.8.0 to 0.8.17
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): VScode, Forge Foundry
- EVM execution environment / backend / blockchain client: Anvil
- Operating system: Mac

## Steps to Reproduce

1- Create a library with 3 overloads
2- Create a contract and consume the 3 overloads on the library.
3- Compile

**Expected Results**: Compile correct
**Actual Results**: Error saying: `error[6675]: TypeError: Member "getValue" not unique after argument-dependent lookup in type(library LibreryWithOverloads).`

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

library LibraryWithOverloads {
    /// @dev Overload for uin16
    function getValue(uint16 min, uint16 max) public pure returns(uint16) {   
        return max - min;
    }

    /// @dev Overload for uint32
    function getValue(uint32 min, uint32 max) public pure returns(uint32) {   
        return max - min;
    }

    /// @dev Overload for uint256
    function getValue(uint256 min, uint256 max) public pure returns(uint256) {   
        return max - min;
    }
}

contract ConsumingContract {
    constructor() {}

    function getValue() public pure {
        uint16 b = LibraryWithOverloads.getRangeFromSeed(uint16(2), uint16(3));
        uint32 c = LibraryWithOverloads.getRangeFromSeed(uint32(2), uint32(3));
        uint256 a = LibraryWithOverloads.getRangeFromSeed(uint256(2), uint256(3));
    }
}
```

Note: Renaming the functions to have unique names does make the code compile.

**Comment by cameel** [comment]
Thanks for reporting. This is a known problem with overloads taking implicitly convertible types and not limited to libraries:
```solidity
contract C {
    function f(uint16) public {}
    function f(uint32) public {}

    function test() public {
        f(uint16(1));
    }
}
```
```
Error: No unique declaration found after argument-dependent lookup.
 --> test.sol:6:9:
  |
6 |         f(uint16(1));
  |         ^
Note: Candidate:
 --> test.sol:2:5:
  |
2 |     function f(uint16) public {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Candidate:
 --> test.sol:3:5:
  |
3 |     function f(uint32) public {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

We already have an issue tracking this (#1256) so I'm going to close this one as a duplicate.
