### ISSUE TITLE
Warn about an expression statement without write-like side-effects

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1380]
By the time the compiler is able to enforce `view` and `pure` modifiers, it should be possible to detect expressions without side-effects.   This issue proposes a warning for expression statements without side-effects.

For instance, there would be a warning on the statement `3;`
```
Warning: a statement without side-effects.
function f() { 3; }
               ^^
```

This should also catch the case of `var a = 0; a;`

**Comment by pirapira** [comment]
This should also catch `msg;`.

**Comment by pirapira** [comment]
This should also catch expressions that are not pure but reads states.

**Comment by chriseth** [comment]
The `isPure` annotation on expression already goes into the right direction, but we can implement a little more, actually. We should add a `sideEffectFree` annotation that is true for e.g. referencing any variable (`isPure` is only true for constants).
