### ISSUE TITLE
[yul] Allow qualified access to top-level data objects

### ISSUE THREAD

**Issue by 0xGeorgii** [ethereum/solidity#13807]
## Abstract

During working on #13707 an occasion of the same object qualified member access issue was founded. Literally, it is impossible to get an access to an object member by calling it via the qualified name.

## Motivation

It might be useful to improve code readability and reduce number of possible errors. For tests it can help to write more precise test and not to miss tricky access issues.

**Example**
```
object "A" {
    code {
        sstore(0, datasize("A"))
        sstore(1, datasize("A.data1"))
        sstore(2, datasize("A.data2"))
    }

        data "data1" "abcdef"
        data "data2" "123"
}
```

## Specification

In the Object Parser

https://github.com/ethereum/solidity/blob/591df042115c6df190faa26a1fb87617f7772db3/libyul/ObjectParser.cpp#L215

when data objects are parsed it considers exact names (like `data1` `data2` from the example above).

however, when this data object is tried to get from parsed object according to the `funCall.arguments` in

https://github.com/ethereum/solidity/blob/591df042115c6df190faa26a1fb87617f7772db3/libyul/AsmAnalysis.cpp#L395

the condition fails because of hash mismatch ( `hash("A.data1") != hash("data1")` and `hash("A.data2") != hash("data2")`.

## Backwards Compatibility

Backwards compatibility should not be affected after this change.

**Comment by cameel** [comment]
As I said in https://github.com/ethereum/solidity/pull/13707#discussion_r1044846818, this seems like a natural extension of the way this works now - you can refer to object by its name (`A`) and access nested data via qualified name (`B.C.D.data`), so why not allow qualified access to the object itself (`A.data`)?

On the other hand, as the description above shows, it does introduce some problems. E.g. objects being accessible via multiple paths, resulting in different hashed IDs. Also, in practice this is probably not very common so we could just as well live without this feature.

So in the end I'm not sure if we're going to actually implement this. At least for the purposes of #13707 we can do just fine without it.

**Comment by cameel** [comment]
Not stale (at least not the issue on its own). It has a pending PR.
