### ISSUE TITLE
`encodeCall()` causes compile failure for overloaded functions like ERC721's `safeTransferFrom`

### ISSUE THREAD

**Issue by dnlchong** [ethereum/solidity#13815]
## Description

`encodeCall` fails when using a function selector of an overloaded function.

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): 0.8.17
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: Hardhat internal environment
- Operating system: Windows and Mac (tested on both)

## Steps to Reproduce
Attempt to compile the following code. The error occurs because safeTransferFrom is an overloaded function.

```solidity
import "@openzeppelin/contracts/token/ERC721/IERC721.sol"; // OpenZeppelin v4.6.0

(bool transferSuccess, bytes memory transferResult) = address(_erc721Address).call(
    abi.encodeCall(IERC721(_erc721Address).safeTransferFrom, (_ownerAddress, vaultAddress, _erc721Id))
);

// Error: Member "safeTransferFrom" not unique after argument-dependent lookup in contract IERC721
```

I've looked around but could not find this issue mentioned in the repo. I can start working on a PR if the issue looks valid.

**Comment by dnlchong** [comment]
related https://github.com/ethereum/solidity/issues/13813 ?

**Comment by cameel** [comment]
#13813 is something entirely different (it's only about how the error message looks like). But we do have an issue for this exact issue (#3556) so closing as duplicate.
