### ISSUE TITLE
Improve performance of DataFlowAnalyzer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#13822]
On some examples (notably chains.sol), the DataFlowAnalyzer still takes a gigantic part of the optimizer time.
Profiling shows that 63% of the whole computation time is spent inside `DataFlowAnalyzer::clearValues` while most of this time is spent inside `std::_Rb_tree<>::find(YulString const&)`.

An "easy" solution to this is to use better performing data structures to store the relation between how variables reference each other.

Another aspect that wastes time is that variables that are assigned inside e.g. an if body are determined multiple times when the if bodies are nested. It might be better to collect assigned variables (or reset them) at the point we visit the assignment.

**Comment by chriseth** [comment]
A backwards map-to-string already improved performance tremendously. What would probably best is to use a data structure that contains two instances of the form `set<pair<YulString, YulString>>`, for forward and backward references. loer_bound / upper_bound operations allow iterating over keys and efficient deleting without the additional overhead of a set inside a map.

**Comment by nikola-matic** [comment]
> A backwards map-to-string already improved performance tremendously. What would probably best is to use a data structure that contains two instances of the form `set<pair<YulString, YulString>>`, for forward and backward references. loer_bound / upper_bound operations allow iterating over keys and efficient deleting without the additional overhead of a set inside a map.

Ah, I did this with another `unordered_map<YulString, set<YulString>`. Will see if I can get additional gains with your approach.
