### ISSUE TITLE
Order of Precedence of Operators is incorrect in the documentation

### ISSUE THREAD

**Issue by pashov** [ethereum/solidity#13831]
## Page

https://docs.soliditylang.org/en/v0.8.17/cheatsheet.html#order-of-precedence-of-operators

## Abstract

I was reviewing code that looks something like this
```solidity
a & b == b
```
so to check the correctness of the expression I went on the Solidity Docs to understand operator precedence. I know that operators with higher precedence are executed earlier than operators with lower precedence in the case that you do not have wrapping braces. What I see is that the `&` bitwise AND operator has a precedence of 7, and the `==` equality operator has a precedence of 11.
Now my expectation was that the code above is the same as
```solidity
a & (b == b)
```
But when tested, it actually is the opposite, even though `&` has lower precedence than `==`. The expression is evaluated as
```solidity
(a & b) == b
```

Based on this, I think Solidity actually uses higher operator precedence for the `&` operator than for the `==` operator, which contradicts the documentation and should be updated.

**Comment by 0xalpharush** [comment]
> The following is the order of precedence for operators, listed in order of evaluation.

The lower the precedence in the table, the earlier its evaluated. Perhaps it could be clarified, but the docs are correct.

**Comment by NunoFilipeSantos** [comment]
Hey! 👋 We're closing this issue. Feel free to submit a PR with better phrasing.
