### ISSUE TITLE
Add a simplification rule that replace long `pushN 0x00 .. 00` to `push1 0x00` (and potentially `push0` in the future)

### ISSUE THREAD

**Issue by Saw-mon-and-Natalie** [ethereum/solidity#13834]
## Abstract

Sometimes the compiler injects long unnecessary pushes in the bytecode:

```asm
push32 0x0000000000000000000000000000000000000000000000000000000000000000
```

The above can be replaced by `push1 0x00`.

## Motivation

Although both of the above solutions would have the same runtime gas, `push1 0x00` would produce a smaller bytecode and so it should be favored by the compiler.

## Specification

A simplification rule can be added to the compiler that would transform all the instructions of the following form:

```asm
pushN 0x00 ... 00 ; N > 1
```

to `push1 0x00` and possibly `push0` after [EIP-3855](https://eips.ethereum.org/EIPS/eip-3855) is approved.

## Backwards Compatibility

The simplification rule will be backward compatible.

**Comment by axic** [comment]
Shouldn't instead a generalised rule be added which compresses pushes to the smallest option (i.e. strips leading zeroes)?

**Comment by Saw-mon-and-Natalie** [comment]
In the examples that I'm looking at the `push32 0x0000000000000000000000000000000000000000000000000000000000000000` appears to be where `loadimmutable` `YUL` instructions are used.

**Comment by Saw-mon-and-Natalie** [comment]
> Shouldn't instead a generalised rule be added which compresses pushes to the smallest option (i.e. strips leading zeroes)?

Yes, that's a better rule.

**Comment by ekpyron** [comment]
We only ever generate the smallest possible pushes. The only exception is indeed immutable loads, in which case the required push size is not known at compile time and cannot be changed during contract creation, since that would involve shifting all jump offsets.
So this is generally not possible to improve without heroic measures like typed immutables  on the yul level, which I don't think are worth the gain here.

**Comment by ekpyron** [comment]
To elaborate a bit further: those are not actually zeroes being pushed, but empty placeholders that will be modified by the contract creation code based on user supplied values and the ultimate push value is only known at creation time, at which point bytecode compression is no longer an option.

**Comment by ekpyron** [comment]
Closing this, since the occurrence of such pushes is related to immutable design rather than missing simplification/optimization.
