### ISSUE TITLE
Interface to Solidity on Etherscan contract interface does not check for authentication, Large number of admin functions callable by public, XSS vulnerability in etherscan.

### ISSUE THREAD

**Issue by amritabithi** [ethereum/solidity#13847]
#### Expected behaviour
- Many functions across all contracts are publicly callable that are clearly only intended for admins of the contract to use, it is as though there is no authentication happening in most contracts for some contract function calls whatsoever.
- The 'Write Contract' interface should prompt for authentication to make clicking the writable functions more difficult.
- The form processing done on input from text boxes on the smart contract interface screens of "Read Contract" / "Write Contract" should filter special characters when receiving input, at least for double quotes and their various representations in hex, decimal, unicode, html entities, escaped JavaScript, etc.  Code can currently be injected into function calls by escaping the double quotes character and at a minimum cause exceptions as a method of burning gas on purpose ( not all gas is reverted upon certain exceptions).

#### Actual behaviour
The public can manipulate some of the top contracts, potential for data corruption via XSS on etherscan, writeable panel of contract interface issues network requests on button clicks even if user is not logged in.  ( No error message or success message is displayed, but the request is sent and received and processed by the server when the button is pressed. )
Some contracts that I was able to look at on goerli had nearly every writable function callable anonymously by the public without doing a proper transaction or requiring coins to issue.

#### Steps to reproduce the behaviour
View a contract on testnet like this one, go to "Write Contract" and enter zeros into each field, hit submit, and you have written to the contract without spending coins. - https://goerli.etherscan.io/address/0x8ae7063d03213d4d90103c16f048b3f64de2d4d0#code

I have been trying to submit and get attention to these problems for some time now, to both an almost comical and embarassing degree, and after being completely ignored and seeing as this is being obviously abused I decided it better to post here so that people are made aware of the situation sooner than later.  I had reported this to solidity but have not heard back anything from them and in my opinion it is too late to siliently roll out a fix.

**Comment by ekpyron** [comment]
I'd defer you to the answer already given when you reported this to geth https://github.com/ethereum/go-ethereum/issues/26434#issuecomment-1371870041, which I'd fully agree to. Hence I'm closing the issue.
