### ISSUE TITLE
Deprecation warning for SELFDESTRUCT

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#13844]
Following https://eips.ethereum.org/EIPS/eip-6049 we should emit deprecation warnings on any use of selfdestruct.

**Comment by morganjweaver** [comment]
Hello there.  I'm a newer Solidity dev with a C++ and compilers background. I've found the Contributing to Solidity 101 doc, the [Workflow for PRs doc](git@github.com:morganjweaver/solidity.git), and the PR Review [Checklist](https://github.com/ethereum/solidity/blob/develop/ReviewChecklist.md) doc, and intend to submit a PR.  Please let me know if there is anything _not_ covered in the documentation that I should know.  I've also got the gitter solidity-dev channel open. Thank you!  

Also: since the callcode deprecation warning is most similar, I wanted to verify that I should include inline assembly in the check + warning, unlike callcode--is this correct?

**Comment by ekpyron** [comment]
Hi there and thank you very much for wanting to contribute!

Yes, ``callcode`` may be a good reference for emitting the deprecation warning on the solidity level - that was done a long time ago and the code base has changed a lot since, but the ``StaticAnalyzer`` should still work pretty much the same.

And indeed there should also be a warning about ``selfdestruct`` in inline-assembly, resp. Yul - the place to look for that would be ``libyul/AsmAnalysis.cpp`` - but we can also start with a PR that only addresses Solidity and take it from there!

Feel free to ask for any help you may need here or in the gitter/matrix channel - unfortunately, it seems like we're in different timezones, so we may have to rely on asynchronous communication.

I hope https://docs.soliditylang.org/en/develop/contributing.html will be a good enough reference to get you started e.g. on running the test suite. https://docs.soliditylang.org/en/develop/contributing.html#writing-and-running-syntax-tests and running ``isoltest`` should be the most relevant for this issue.

**Comment by ekpyron** [comment]
@morganjweaver Any update on this? Do you need any more input and/or help?

**Comment by nikola-matic** [comment]
@morganjweaver I'll be taking this over since we plan on releasing soon, and we'd rather like for this to go into the 0.8.18 release.

**Comment by cameel** [comment]
> And indeed there should also be a warning about selfdestruct in inline-assembly

Maybe it would be better not to issue a warning for its use in inline assembly? At the moment the opcode is still in the EVM so if you need and want its functionality, using `selfdestruct()` is still the way to go. There is no alternative construct available now and there's no way to silence this warning.

**Comment by nikola-matic** [comment]
> > And indeed there should also be a warning about selfdestruct in inline-assembly
> 
> Maybe it would be better not to issue a warning for its use in inline assembly? At the moment the opcode is still in the EVM so if you need and want its functionality, using `selfdestruct()` is still the way to go. There is no alternative construct available now and there's no way to silence this warning.

The draft PR only issues a warning when used from Solidity, so we're good so far if that's the case.

**Comment by cameel** [comment]
Yeah, I saw that. That's good for now but it was stated here that we should add it in inline assembly too so I wanted to get a decision on that.

**Comment by ekpyron** [comment]
Definitely also warn in assembly. The opcode is what's being deprecated.

**Comment by trendespresso** [comment]
> Definitely also warn in assembly. The opcode is what's being deprecated.

As an EVM developer a little out of the know: What should I replace `selfdestruct()` with? In the case of a `payable()` inside, how should that look: `selfdestruct(payable(msg.sender))` --> `??`

Thanks for any info! Appreciate everyone who works on Solidity
Cheers

**Comment by chriscrutt** [comment]
why is it being depreciated? I can't find much reason.

**Comment by trendespresso** [comment]
If we want to destroy contracts, how should we do so now that `selfdestruct()` is deprecated?

**Comment by Tshembani04** [comment]
I used  solidity: "0.8.17", after trying to get anything resourceful from the Ethereum docs and chatGPT
