### ISSUE TITLE
CVC4 has been superseded by CVC5 - please update the project

### ISSUE THREAD

**Issue by yurivict** [ethereum/solidity#13843]
https://cvc5.github.io/

**Comment by cameel** [comment]
I think last time we discussed it, CVC5 wasn't yet ready for general use. Did that change? Pinging @leonardoalt.

**Comment by leonardoalt** [comment]
> I think last time we discussed it, CVC5 wasn't yet ready for general use. Did that change? Pinging @leonardoalt.

Yes, it should be ready. It is the "default" cvc5 now and was officially released last year.

**Comment by cameel** [comment]
Ok then. I guess we should update eventually?

**Comment by leonardoalt** [comment]
Closing in favor of https://github.com/ethereum/solidity/issues/14325
