### ISSUE TITLE
Allow try/catch without the catch

### ISSUE THREAD

**Issue by Shungy** [ethereum/solidity#13851]
## Abstract

Solidity always requires `try { … }` to be followed by `catch { … }`. Make `catch { … }` optional.

## Motivation

Most of the time I do `try { … } catch {}` to make a non-reverting call, and do something if only there is no failure. In those cases, I have no use for `catch`, so I leave it empty within `{}`. But it just looks ugly. I want to be able to write `try { … }` without any trailing `catch {}`.

## Specification

Make `try { … }` equivalent to `try { … } catch {}`.

## Backwards Compatibility

This change seems to be entirely backwards compatible.

**Comment by NunoFilipeSantos** [comment]
Hey! 👋 Unfortunately, this feature is not planned and is not a priority in our [Roadmap](https://github.com/orgs/ethereum/projects/26/views/1).
