### ISSUE TITLE
Remove unused `endToEndExtraction` scripts

### ISSUE THREAD

**Issue by r0qs** [ethereum/solidity#13852]
Remove obsolete `endToEndExtraction` scripts.

**Comment by aarlt** [comment]
Maybe we could just remove the whole `scripts/endToEndExtraction` directory. I guess the probability is quite low that we will need that again. However, why should we only remove that `verify-testcases.py` script?

**Comment by r0qs** [comment]
Indeed. We should remove all `endToEndExtraction` if they are no longer used. I updated the title and issue description.

**Comment by cameel** [comment]
I see that we did test extraction in #8464 and #8518. In https://github.com/ethereum/solidity/issues/8197#issuecomment-609825831 @chriseth said that most of the remaining tests check for events. We also still have #12253 open ([`SolidityEndToEndTest.cpp`](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SolidityEndToEndTest.cpp) still has ~4k lines) and isoltest now supports events (#11050). So are we sure we won't be doing any more extraction?

**Comment by r0qs** [comment]
Right. We could quickly discuss that in the meeting this week then.

**Comment by ekpyron** [comment]
Nobody said we wouldn't extract anything else, but I don't see us using the scripts for whatever remains.
