### ISSUE TITLE
Export keyword for creating contract modules

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1385]
This is something that is needed/highly desired for our efforts in package management. A simple keyword not unlike `using for` but instead made for exporting a package of contracts. What this keyword will do is drop all symbols that are not currently in an `export` field of the module being passed up through the compiler, so that names can be reused in packages further up the import tree.

**Comment by chriseth** [comment]
What you can already do for now is importing some selected symbols from several other files into one file - similar to how this is generally handled in Python. Would that already help?

**Comment by VoR0220** [comment]
Not really. Atleast I don't think so based on how you're describing it. The thing is that file is still going to be passed up, symbols and all. 

Lets say I have a package, and inside this package are the contracts: 

```
contract A{}

contract B{}

contract C{}
```

These are fairly common names. Someone decides to use my package. They also want to create a package that might have fairly common names `contract A{}`. When we try to compile them, we will get a duplicate name error. To resolve this, I am proposing that we enable users to determine what is the main `module` of their contract package set that will be the main one for reuse. This can be defined either/or as such:

```
export C; //export contract C

//or 

export * for C; //exports all inherited symbols 

// or

export C as foo; //exports it under a different name

// or 

export * as foo; //exports all symbols in file under the name foo
```

This could probably use some brainstorming but I think the idea is fairly clear now of what I'm trying to get at.

**Comment by MrTibbles** [comment]
👍

**Comment by MrTibbles** [comment]
I think this is a sensible suggestion. It also sounds similar to ES6 methodologies for handling modules, or am i mistaken? https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export

**Comment by chriseth** [comment]
@VoR0220 Let's say you have the following file x.sol:
```
contract A{}

contract B{}

contract C{}
```

You can use `import "x.sol" as X;` which will only create the symbol `X` and you can access the contrats via `X.A`, `X.B`, etc.
You can also choose to only import some symbols from `x.sol` directly:
`import {A, B} from "x.sol";`

**Comment by VoR0220** [comment]
Interesting. Okay. I think that solves my problems.
