### ISSUE TITLE
Abi encoding should serialize parameters sequentially, to allow fluid composition and dynamic construction

### ISSUE THREAD

**Issue by RitzyDevBox** [ethereum/solidity#13861]
The existing Solidity ABI encoding is poor design for several reasons:

**Problem:**  
   I want to be able to appended the results of governance proposals dynamically to the function calldata

**Issue:**
Encoding design is erratic, the structure of the encoding, causes dynamic parameters to be injected earlier in the encoding, to be aware of the offset.

  1. There is no deterministic way to know what data is being sent, making it difficult to ensure the integrity of the data.
  2. There is no way to extend the calldata, making it difficult to add new functionality to contracts without breaking existing ones.

**Proposal.**
All parameters should be serialized seqentially, so the function selection can be swapped and additional calldata can be appended.

**Comment by ekpyron** [comment]
The ABI encoding actually predates solidity :-). And yes, it's flawed in many ways - but there's almost no smooth way to break it at this point without wreaking backwards-compatibility havok.
Without looking them up, we'll definitely have different issues about that already, in any case, so I'm closing this as a duplicate.

**Comment by RitzyDevBox** [comment]
@ekpyron why do you think you would need to break backwards compatibility?

All you need to do is.

1. Add a version when making a call to the contracts
2. The version number is places in the dead bytes after the function
selector.

If the version number is present change the decoder.

This version can affect other options

**Comment by ekpyron** [comment]
Which dead bytes after the function selector :-)? (Spoiler alert: there are none.)
Having two competing ABIs coexisting would increase the code size of all contracts in perpetuity in any case, which is quite non-ideal. There have been discussions about ABI versioning in the past you may find as a reference - but yeah, changing the ABI is extremely non-trivial - we couldn't even do it unilaterally, but it'd need to be a cross-language standard to maintain contract interoperability. Vyper recently made a move at defining a new ABI (albeit with a different focus) https://github.com/vyperlang/vyper/issues/2542 - but there hasn't been much movement (that I'm aware of) recently.

So as I said: yes, the current ABI is suboptimal, but no, we can't change it just like that.

**Comment by RitzyDevBox** [comment]
What do you mean there are no dead bytes, the function selector only takes
up 8 of the 32 bytes?

What are the other 24 bytes being used for?

**Comment by cameel** [comment]
Parameters are aligned to 32-bytes slots but the selector is not. It takes only 4 bytes and the parameters follow immediately, without any gap.

See [ABI encoding examples in the docs](https://docs.soliditylang.org/en/latest/abi-spec.html#examples).

**Comment by RitzyDevBox** [comment]
Okay everything's still fine then.  The parameters are aligned to 32
bytes.  +4 bytes for the selector.

Now just add 4 bytes for the version and change the offset to +8.

If the offset is +4 then use the old version of the offset is +8 check the
version

**Comment by esaulpaugh** [comment]
I've been working on an ABIv3 proposal: https://github.com/esaulpaugh/abiv3

In my opinion, existing contracts on Layer 1 are nearly irrelevant to the future of smart contracts. And Layer 2 is not standardized around ABIv2, so there would be no harm to compatibility overall. In fact, I believe compatibility would be helped by a more efficient standard that isn't prohibitively expensive in terms of gas costs. https://github.com/esaulpaugh/abiv3/blob/master/SPEC.md
