### ISSUE TITLE
Overload resolution between functions taking view and non-view function pointers results in a compiler error

### ISSUE THREAD

**Issue by wadealexc** [ethereum/solidity#13879]
## Description

Overloaded library functions cannot be passed function types with different mutability modifiers - this causes a compiler error, instead.

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): default remix EVM (merge)
- Framework/IDE (e.g. Truffle or Remix): tested using both Remix and solc-js
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 22.04

## Steps to Reproduce

The lines in User.setup cause a compilation error:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

library TestLib {

    function add(function() external view f) internal {
        f();
    }

    function add(function() external f) internal {
        f();
    }
}

contract User {

    using TestLib for *;

    function setup() public {
        this.testOne.add();
        this.testTwo.add();
    }

    function testOne() external view {
        require(msg.sender != address(0), "test value");
    }

    function testTwo() external {
        require(msg.sender != address(0), "test value 2");
    }
}
```

**Comment by cameel** [comment]
This does not look like a bug.

First, I think you meant functions attached with `using for` rather than modifiers (modifiers are declared with the `modifier` keyword). Second, this does not have anything to do with such functions. You can reproduce the same error without them:

```solidity
library L {
    function add(function() external view f) internal {}
    function add(function() external f) internal {}
}

contract C {
    function test() public {
        L.add(this.ext);
        L.add(this.extView);
    }

    function ext() external view {}
    function extView() external {}
}
```
```
Error: Member "add" not unique after argument-dependent lookup in type(library L).
 --> test.sol:8:9:
  |
8 |         L.add(this.ext);
  |         ^^^^^
```

But the thing is, this works as designed. One of your calls is ambiguous and matches both overloads. That's because a pointer to a view function can be passed both into a view and non-view parameter.

The non-view pointer on the other hand works only with the second overload and it does not cause an error. You can check that this code will compiler if you comment-out `L.add(this.ext)`.

**Comment by wadealexc** [comment]
By "modifier" I meant the words that affect the mutability of the function. i.e. "view" or "payable" were the "mutabillity modifiers". Sorry for the confusing wording!

I see, your explanation makes sense. It's frustrating that it works this way, because the usecase I have is that I want the `add` function to ultimately call the passed-in function type with either a `CALL` or `STATICCALL`, depending on the mutability of the function type.

I'm having to use different function names to accomplish this (`addView` and `addMut` etc), which is not as nice to read.

**Comment by cameel** [comment]
Well, this is something that we want to solve eventually. There's an issue about making the compiler automatically choose the more fitting overload: #1256. It focuses on integer types but your case is actually something that would fit that too.
