### ISSUE TITLE
Required boost version in the docs does not match the code after recent changes

### ISSUE THREAD

**Issue by nicsor** [ethereum/solidity#13870]
## Page

https://docs.soliditylang.org/en/latest/installing-solidity.html#building-from-source

## Abstract

According to the above page, for C++ we have as dependencies: 
       Boost (version 1.77+ on Windows, 1.65+ otherwise) | C++ libraries.

with a note below: "Starting from 0.5.10 linking against Boost 1.70+ should work without manual intervention."

But in this change: https://github.com/ethereum/solidity/commit/1da82045c4881e5ccd6f15f7abf472272e1028cd "fs::directory_options" was used. a feature which was added in boost 1.72.

What's the minimum boost version you are targeting?

**Comment by nikola-matic** [comment]
The Windows boost version is also technically wrong, as it needs to be 1.77 exactly. See:
https://github.com/ethereum/solidity/issues/12904
https://github.com/ethereum/solidity/pull/13434
