### ISSUE TITLE
Clean up documentation with regards to deprecated `selfdestruct`

### ISSUE THREAD

**Issue by nikola-matic** [ethereum/solidity#13889]
As `selfdestruct` is to be deprecated, and now even triggers a deprecation warning (see https://github.com/ethereum/solidity/issues/13844, https://github.com/ethereum/solidity/pull/13884), the docs should be fully updated to reflect this, whether by adding additional deprecation warnings, or by altering any existing examples so as not to suggest the usage of `selfdestruct`.

Changes should be made in the following files:
```
docs/cheatsheet.rst
docs/contracts/function-modifiers.rst
docs/contracts/functions.rst
docs/contracts/inheritance.rst
docs/examples/micropayment.rst
docs/internals/optimizer.rst
docs/metadata.rst
docs/security-considerations.rst
docs/smtchecker.rst
docs/style-guide.rst
docs/using-the-compiler.rst
```

**Comment by Coderayush13** [comment]
Hey i want to try this

**Comment by Coollaitar** [comment]
Solving this issue!

**Comment by nikola-matic** [comment]
Just a note for future (and current) contributors: if this is the first issue you've tackled in this project, consider finding another one, since this one is more complicated than it might seem - in some cases it would require re-writing existing code samples to not use `selfdestruct`, which in certain cases may even mean writing completely new ones.
In addition, before you open a PR for this issue (and for most of them really), please ask first if the issue is appropriate for a first time contributor, because otherwise we have to be the bad guys and close your PR, or invest our time into fixing something that was not of high priority (or is at least a much lower priority than what we currently have going on).
By all means feel free to contribute (we would really appreciate it), just make sure to ask first if the issue you've got your eyes on is a good fit. Cheers.

**Comment by Coollaitar** [comment]
> Just a note for future (and current) contributors: if this is the first issue you've tackled in this project, consider finding another one, since this one is more complicated than it might seem - in some cases it would require re-writing existing code samples to not use `selfdestruct`, which in certain cases may even mean writing completely new ones. In addition, before you open a PR for this issue (and for most of them really), please ask first if the issue is appropriate for a first time contributor, because otherwise we have to be the bad guys and close your PR, or invest our time into fixing something that was not of high priority (or is at least a much lower priority than what we currently have going on). By all means feel free to contribute (we would really appreciate it), just make sure to ask first if the issue you've got your eyes on is a good fit. Cheers.

Okay ser!

**Comment by ekpyron** [comment]
This should now also account for https://eips.ethereum.org/EIPS/eip-6780

**Comment by Rashann2471** [comment]
https://github.com/ethereum/go-ethereum/tree/f1794ba2788baf34489847bfa9ca00e067507db0
