### ISSUE TITLE
grammar.txt: PragmaDirective

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#1389]
The following `PragmaDirective` (from **introduction-to-smart-contracts.rst**) can not be parsed:

`pragma solidity ^0.4.0;`

The problem seems to be that `^0.4.0` is not an expression, i.e. `^` is not an unary operator..

**Comment by axic** [comment]
The pragma statement is parsed as a keyword (`solidity`) and whatever comes after the keyword is taken verbatim without parsing.

**Comment by walter-weinmann** [comment]
Thanks for the explanation - but how does this fit with its definition in grammar.txt?

In general I'm trying to develop a parser based on grammar.txt (see https://github.com/walter-weinmann/syparse) - but it seems to be an impossible task.  Even the most basic code doesn't comply with grammar.txt, e.g. try the Coin contract - it uses the reserved word `from` as a name. 

```
pragma solidity ^0.4.0;

contract Coin {
    // The keyword "public" makes those variables
    // readable from outside.
    address public minter;
    mapping (address => uint) public balances;

    // Events allow light clients to react on
    // changes efficiently.
    event Sent(address **from**, address to, uint amount);

    // This is the constructor whose code is
    // run only when the contract is created.
    function Coin() {
        minter = msg.sender;
    }

    function mint(address receiver, uint amount) {
        if (msg.sender != minter) return;
        balances[receiver] += amount;
    }

    function send(address receiver, uint amount) {
        if (balances[msg.sender] < amount) return;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        Sent(msg.sender, receiver, amount);
    }
}
```

**Comment by axic** [comment]
Correction to pragma: whatever comes after _on the same line_.

Why is `from` reserved?

**Comment by walter-weinmann** [comment]
```
ImportDirective = 'import' StringLiteral ('as' Identifier)? ';'
        | 'import' ('*' | Identifier) ('as' Identifier)? 'from' StringLiteral ';'
        | 'import' '{' Identifier ('as' Identifier)? ( ',' Identifier ('as' Identifier)? )* '}' 'from' StringLiteral ';'

```

**Comment by axic** [comment]
I thought it is only being reserved when part of the `import` statement? Not sure if it can be described well in the grammar.

**Comment by walter-weinmann** [comment]
My parser is based on yecc and leex  which are Erlang's equivalents to yacc and lex - so I think I'm at the end of my wisdom now.
