### ISSUE TITLE
EVM version awareness for EVM ASM json import/export

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#13899]
Related to #13673 and #13759.

Right now the current implementation is not taking the EVM version into account. E.g. it is possible to use `prevrandao` and `difficulty`, even inside the same assembly json file. Those are right now just treated as exactly the same opcode, where no warnings/errors are generated. However, it may make sense to add the used EVM version during export and using it correctly during the import. This will also ensure that `--asm` or `--opcodes` will return the correct opcode name defined by the specified EVM version.

**Comment by NunoFilipeSantos** [comment]
We have decided not to do this now. Closing
