### ISSUE TITLE
Move triage to the bug traging board

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13892]
Related to #13615.

Currently, issues to triage are being tracked on the old [Solidity](https://github.com/ethereum/solidity/projects/43) board. We need to move the column to the [Solidity Bug Triaging](https://github.com/orgs/ethereum/projects/27) board. 
This includes adjusting the action that adds new issues to this column (#13528).

- [ ] Move new issues to the triaging column on [Solidity Bug Triaging](https://github.com/orgs/ethereum/projects/27)
- [ ] Once it's done, close the old board.

**Comment by ekpyron** [comment]
Why exactly the bug triaging board? Are all incoming issues bugs now :-)?

**Comment by cameel** [comment]
That's what @NunoFilipeSantos suggested. I'm fine with a different board but the bug triaging one actually has a triage column, so it seemed reasonable to me (we had one on the focus board but it was removed).

And anyway, it does make some sense. Every issue is a potential bug until we look at it :) We're dropping stuff from the triage column when we triage so it's not like non-bugs would be clogging that board.
