### ISSUE TITLE
Invalid function signature due to a whitespace in between function parameter arguments

### ISSUE THREAD

**Issue by dcbuild3r** [ethereum/solidity#13907]
## Description

When calling a function through an interface and using **(1)**
```solidity
abi.encodeWithSignature(“functionSignature(param1Type, param2Type)”)
``` 
to encode the message it creates a different function signature than **(2)**
```solidity
abi.encodeWithSignature(“functionSignature(param1Type,param2Type)”)
```
 because of the whitespace between `(“param1Type,<WHITESPACE>param2Type)”`.

The correct use is **(2)** and this can introduce bugs in contracts.

One of the contracts I made had this bug and the resulting behavior is that the Solidity contract reverts because it can't find a corresponding function signature to what's being called through the interface in a different contract. ([example](https://goerli-optimism.etherscan.io/tx/0x175fb60ef815fdfd96945a360594be529ecf201b5e51bda2a90698fdaeb73013))

My question is whether the `solc` compiler can remove whitespaces between function parameter arguments at compile time or at least issue a warning that there are whitespaces in between function parameter arguments.

## Environment

I believe this applies to all Solidity versions that support [EIP-712](https://eips.ethereum.org/EIPS/eip-712) if I'm not mistaken.

**Comment by ekpyron** [comment]
The compiler just sees a regular memory string here - i.e. there's no real difference between ``abi.encodeWithSignature(“functionSignature(param1Type,param2Type)”)`` and
```
string memory x = “functionSignature(param1Type,param2Type)”;
abi.encodeWithSignature(x);
```

And for an arbitrary statement like ``string memory x = “functionSignature(param1Type,param2Type)”;``, in general, there is no way to tell if this is meant to be a function signature or any other kind of string, in which you may very much *want* explicit whitespace.

So given that, I don't think warning about the whitespace nor automatically removing this is an option.


However, what we can consider, is adding compiler-constructs for constructing suitable strings from properly typed expressions in the language, similar to how we have builtin constructs for computing selectors of functions.

So e.g. for
```
contract C {
function f(uint a, uint b) external {}
}
```
We currently have ``f.selector`` being based on the hash of the signature ``f(uint256,uint256)``. We *could* add something like that as ``f.signature``. However, that would not really match all the cases occurring in EIP-712, e.g. structs.

Eventually, it would be nice to have sufficient compile-time-constant expression evaluation and reflection in the language to actually be able to safely synthesize such strings at compile-time, but that's far away in the future, so the question is whether we can do something now that will help in these cases.

**Comment by dcbuild3r** [comment]
my friend @smartcontracts recommended me to just use 
```solidity
abi.encodeCall(MyContract.function, (arg1, arg2))
``` 
because it's type safe and it is impossible to mess up this way. Maybe a linter or LSP could catch the bug I had above as well with `regexp` or something.

**Comment by ekpyron** [comment]
That will give you a four-byte selector based on the hash of the signature of ``MyContract.function``, with the ABI-encoding of the arguments ``(arg1, arg2)`` appended to it. If that's in fact the only thing you end up needing, then that's indeed the best option.

And yes, this could be hinted at by analysis or linting tools, but I'd consider it out-of-scope of the compiler itself, i.e. that'd be a job for an external tool plugged into an IDE or such.

**Comment by ekpyron** [comment]
So yeah, I got a bit distracted by the mention of EIP-712 there.

For any use of ``abi.encodeWithSignature(...)``, using `abi.encodeCall(...)`, if possible, is indeed *always* the better choice. Will that cover all the cases of type hashes that may occur in EIP-712 as well?

**Comment by dcbuild3r** [comment]
I believe so

**Comment by ekpyron** [comment]
Alright, if this is actually already covered by `abi.encodeCall`, I'm closing the issue.

Feel free to reopen, if any additional case not handled by this comes up.

**Comment by dcbuild3r** [comment]
thanks!
