### ISSUE TITLE
Incorporate the wiki pages in the documentation and retire the wiki

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1390]
Raised by @VoR0220:
> we should really get rid of the old solidity wiki…it’s confusing people who come by and they are asking me why inherited contracts can access private members.

The current pages on the wiki are:
- [x] https://github.com/ethereum/wiki/wiki/The-Solidity-Programming-Language
- [x] https://github.com/ethereum/wiki/wiki/Solidity
- [x] https://github.com/ethereum/wiki/wiki/Solidity-Changelog
- [x] https://github.com/ethereum/wiki/wiki/Solidity-Collections
- [x] https://github.com/ethereum/wiki/wiki/Solidity-Features
- [x] https://github.com/ethereum/wiki/wiki/Solidity-standard-library
- [x] https://github.com/ethereum/wiki/wiki/Solidity-Tutorial
- [x] https://github.com/ethereum/wiki/wiki/Solidity,-Docs-and-ABI
- [x] https://github.com/ethereum/wiki/blob/master/Tags-for-Solidity-in-code-documentation.md

**Comment by pirapira** [comment]
I start removing those sections already seen in `solidity/doc`.

**Comment by pirapira** [comment]
I don't think I need to do anything about this one: just some collection of links. https://github.com/ethereum/wiki/wiki/Solidity-Collections

**Comment by axic** [comment]
Marking this a bug as the wiki contains some misleading information.

**Comment by pirapira** [comment]
The only thing remaining is that https://github.com/ethereum/wiki/pull/406 gets merged.

**Comment by pirapira** [comment]
That got merged.
