### ISSUE TITLE
Null dereference in `checkDoubleStorageAssignment()` when type-checking some forms of tuple assignment expressions

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#13901]
```
contract C{bool x;fallback(){(((),x)&x)=((),0);}}
```

```
solc test.sol
```

throws due to null deref from here

https://github.com/ethereum/solidity/blob/206e7cf5db48b13085b943436764c41f169c6c3b/libsolidity/analysis/TypeChecker.cpp#L119

**Comment by cameel** [comment]
Simplified and cleaned up repro:
```solidity
function f() {
    ((0, 0) + 0) = (0, 0);
}
```

It's reproducible with operators other than `&`, including `|`, `%`, `**` or `+`, but not with `==`. It's also reproducible when the assignment is replaced by a different assignment operator, like `+=`.


It started happening on 0.8.16. Before then it would produce compilation errors:
```
Error: Operator + not compatible with types tuple(int_const 0,int_const 0) and int_const 0
 --> test.sol:2:6:
  |
2 |     ((0, 0) + 0) = (0, 0);
  |      ^^^^^^^^^^

Error: Expression has to be an lvalue.
 --> test.sol:2:6:
  |
2 |     ((0, 0) + 0) = (0, 0);
  |      ^^^^^^^^^^

Error: Type tuple(int_const 0,int_const 0) is not implicitly convertible to expected type tuple(int_const 0,int_const 0).
 --> test.sol:2:20:
  |
2 |     ((0, 0) + 0) = (0, 0);
  |                    ^^^^^^
```

**Comment by cameel** [comment]
Looking at the changelog, seems likely that it's a regression introduced by this bugfix: #13367.
