### ISSUE TITLE
Introducing AST node identifiers

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1391]
In order to make the compilation process more deterministic, we can introduce IDs on AST nodes and use those IDs for sorting the nodes.  The IDs are more stable than the pointers that allocators return.

**Comment by VoR0220** [comment]
how would the IDs be determined?

**Comment by pirapira** [comment]
There would be a static counter in `ASTNode` class, and new objects will receive IDs from the counter values.

**Comment by VoR0220** [comment]
Neat! Im down.

**Comment by VoR0220** [comment]
Can this be closed as this appears to be implemented now?

**Comment by VoR0220** [comment]
nevermind, I am incorrect.

**Comment by chriseth** [comment]
This is needed for another feature, will implement now.
