### ISSUE TITLE
Yul compiler does not recognize iszero() function

### ISSUE THREAD

**Issue by guplersaxanoid** [ethereum/solidity#13922]
## Description

Running `solc --yul`  on a yul file throws the following error on every instances where `iszero()` function is used:
```
Error: Function "iszero" not found.
```

## Environment

- Compiler version: 0.8.18+commit.87f61d96.Linux.g++
- Target EVM version (as per compiler settings): paris
- Framework/IDE (e.g. Truffle or Remix): foundry
- EVM execution environment / backend / blockchain client: foundry
- Operating system: ubuntu 20.04

## Steps to Reproduce

```solidity
object "Sample" {
    code {
        datacopy(0, dataoffset("runtime"), datasize("runtime"))
        return(0, datasize("runtime"))
    }

    object "runtime" {
         code {
             requires(iszero(callvalue()))

            function requires(condition) {
                if iszero(condition) { revert(0, 0) }
             }
         }
    }
}
```

Compilation of the above contract will throw these errors
![image](https://user-images.githubusercontent.com/40036742/216346012-453764b5-ac1e-47b1-916d-1a231a3d4836.png)

**Comment by cameel** [comment]
The `--yul` option compiles Typed Yul. The one you want is `--strict-assembly`.

And yeah, it's a mess, we need to document them properly. Closing because we already have an issue for that: #13296.
