### ISSUE TITLE
Gnosis ext test failing: `TypeError: Cannot read properties of undefined (reading 'sourceName')`

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13927]
[`t_native_test_ext_gnosis` is failing on `develop`](https://app.circleci.com/pipelines/github/ethereum/solidity/28370/workflows/17367c74-0377-4e64-9467-9621857964e7/jobs/1259218)

Likely caused by https://github.com/safe-global/safe-contracts/pull/502. It probably added new tests that fail due to https://github.com/NomicFoundation/hardhat/issues/2115 (recently closed and replaced by https://github.com/NomicFoundation/hardhat/issues/3365).

169 tests are failing but that's because one test failing like this usually causes a cascade failure in all subsequent tests. It will probably be enough to disable just a few tests.

### CI output
```
Safe
    setup

      1) should not allow to call setup on singleton

      2) should set domain hash

      3) should revert if called twice

(...)

  93 passing (7s)
  4 pending
  169 failing

/tmp/ext-test-Gnosis-Safe-AmUGHU/ext/node_modules/hardhat/internal/hardhat-network/stack-traces/solidity-errors.js:111
    return new SolidityCallSite(sourceReference.sourceName, sourceReference.contract, sourceReference.function !== undefined
                                                ^

TypeError: Cannot read properties of undefined (reading 'sourceName')
(Use `node --trace-uncaught ...` to show where the exception was thrown)

```

**Comment by nikola-matic** [comment]
Most likely due to [this](https://github.com/safe-global/safe-contracts/pull/502), as previous commits pass without issue. It's a 4k line diff due to formatting changes, but am unsure as of yet whether anything else was changes that would cause the test failures.
