### ISSUE TITLE
Allowed developer to specify value of their `enum`

### ISSUE THREAD

**Issue by chiro-hiro** [ethereum/solidity#13930]
## Abstract

Allowed developer to specify value of their `enum`

## Motivation

Solidity don't allow developer to specify `enum` value that made difficult to keep the `enum` in smart contract to be synced with the off-chain or predefined `enum`.

## Specification

```solidity
enum Permission {
    None = 0,
    Read = 1,
    Write = 2;
    Execute = 4;
    Terminate = 8;
}
```

## Backwards Compatibility

It might not backward compatible.

**Comment by cameel** [comment]
We already have an issue for this (#4638), so closing. It's not hard to implement but we're not fully convinced this is actually needed so giving a concrete use case would help.

**Comment by chiro-hiro** [comment]
This [EIP-6366](https://github.com/ethereum/EIPs/pull/6366) would benefit from it.

**Comment by cameel** [comment]
Please post that in #4638.
