### ISSUE TITLE
[SMTChecker] Report success

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#13949]
Currently the SMTChecker reports nothing in case of success. We should add an `info` message at the end saying how many properties were successfully proven safe, similarly to how `unproven targets` are reported.

**Comment by PaulRBerg** [comment]
YES, please 🙏 

Related question I have recently posted on StackExchange:

[How do I know when the Solidity SMTChecker did not find any unproven targets?](https://ethereum.stackexchange.com/questions/144452/how-do-i-know-when-the-solidity-smtchecker-did-not-find-any-unproven-targets)
