### ISSUE TITLE
Keep mobile navigation bar fixed in the documentation page.

### ISSUE THREAD

**Issue by emamoah** [ethereum/solidity#13946]
## Page

All pages.

## Abstract

This is about the design of the documentation pages. It would be better for the navigation bar on mobile view to be fixed to the top during scrolling to enable users access the sidebar menu from any point in the page. It really hurts UX to have to scroll all the way back to the top just to access the table of contents. And there's not even a "Back to top" button.

**Comment by r0qs** [comment]
Hi @emamoah, definitely, I think it would be beneficial to have the navbar fixed or at least the "back to top" button as you suggested. We will eventually take a look at it. If you would like to contribute, please feel free to submit a PR with either approach ;)

**Comment by emamoah** [comment]
@r0qs Can I make a PR? I can't easily find out where the front-end code is in the repo.

**Comment by r0qs** [comment]
Hi @emamoah of course! :)

Our customization of the `read-the-docs` layout can be found here: https://github.com/ethereum/solidity/tree/develop/docs/_static/css

We use the [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme), so you will need to customize it to support the fixed navigation bar. More specifically, I believe you will need to override some of the default rules for the `wy-nav-top`. You can see the defaults in the theme here: https://github.com/readthedocs/sphinx_rtd_theme/blob/918ca5bed80e83c19d657ce87402044780293c9c/src/sass/_theme_layout.sass#L296

Note that currently, our customizations of the original theme don't change anything for the `wy-nav-top` css class, so you will need to apply your changes to it in our `custom.css` in a way that it still works as now but with a fixed position. Not sure if you will need to change other files as well.

**Comment by cameel** [comment]
> Can I make a PR?

I think we should hold off with this.

First, I don't think this is a clear-cut improvement. These floating bars are often more of an annoyance than help, especially on mobile, when the screen real estate is very limited. We should first discuss in the team whether we really want this. My vote would be "no" and I'd be curious what others think.

Still, if we do decide we want this, I'd first look at RTD configuration. Have you checked if it already provides such an option? I see e.g. [`sticky_navigation`](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-sticky_navigation) so it may already have this. I think we should try to keep customizations on our side minimal.

Finally, if it's not possible to get it via configuration and we want to implement this, I'd suggest to try [submitting a feature request to RTD first](https://github.com/readthedocs/sphinx_rtd_theme/issues/new/choose). This way many more people can benefit from this feature. We can also be sure if will be more polished and tested if done on their side.

We should in general try to go in that direction and even upstream as much of the customizations we already have in [`ext/`](https://github.com/ethereum/solidity/tree/develop/docs/ext/) and [`_static/`](https://github.com/ethereum/solidity/tree/develop/docs/_static/) as is reasonable. Only if RTD does not want to accept such a feature, I'd look into doing it on our side.

**Comment by r0qs** [comment]
> These floating bars are often more of an annoyance than help

Well, in my opinion, they can be helpful when you are reading a long text and would like to change to another section, so you could quickly open the sidebar menu and select a new section to read. A button of `back to the top` as @emamoah also suggested could also help with that. For instance, Github provides a similar feature when reading markdown files on mobiles, but to jump to different sections in the specific markdown, and it is very helpful and doesn't take too much of the screen.
But I'm not strongly in favor to have it either, just thought that it could indeed help a bit to navigate through the documentation when reading on a mobile device.


> Have you checked if it already provides such an option? I see e.g. [`sticky_navigation`](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-sticky_navigation) so it may already have this.

No, I haven't and I was not aware of such an option. So yeah, if RTD already has it, it is much better and simpler then :)

**Comment by emamoah** [comment]
@cameel I'm a developer. But I'm also a designer (Both UI and UX). And I must say I've never come across any documentation page that is less user-friendly as this. You can show me an example, if I'm wrong. I don't think this is something that should be voted on. It even fulfills WCAG guideline 2.4 (Navigable).
Every documentation site I've seen has persistent navigation. Look at https://vuejs.org/guide/ for example. And no one has ever complained that the space left is too small.
There's no way this will impact screen real-estate. Nobody reads text from the very top to the very bottom before they scroll.
But if you think this really isn't worth it, well... I was just suggesting.
