### ISSUE TITLE
Build static release binaries on ubuntu 20.04 again to avoid glibc incompatibilities.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#13954]
We only temporarily worked around https://github.com/ethereum/solidity/issues/13921 in https://github.com/ethereum/solidity/pull/13923 but haven't done anything to prevent it from happening again for the next release.

We briefly discussed it in our design call today with the following result at least as temporary solution for the upcoming releases:

- We permanently restore the ubuntu 20.04 docker file.
- We run the static ubuntu build run against the old 20.04 docker image. This will simultaneously ensure we don't break the builds.
- We run bytecode comparison between static and non-static builds.

In the longer run, we may reevaluate if we move away from ``dlopen``ing Z3 together with @leonardoalt (either by full static linking suffering the binary size increase, or by moving to calling z3 as binary via smtlib roundtrips causing suffering *for* @leonardoalt)

Pinging @cameel in case I missed anything.

**Comment by cameel** [comment]
> or by moving to calling z3 as binary via smtlib roundtrips causing suffering for @leonardoalt

So... how much suffering are we talking about? :)

**Comment by leonardoalt** [comment]
> So... how much suffering are we talking about? :)

C++ template compiler errors kind of suffering

**Comment by leonardoalt** [comment]
@cameel To be precise, this wouldn't affect solving, but would affect counterexample and invariant generation. Currently we rely on z3's data structures being passed back via the API, and we translate those back into our format which are further translated into a pseudo-Solidity format. If we do that via smtlib2, we need to write an smtlib2 parser to translate counterexamples and invariants into our format.

**Comment by ekpyron** [comment]
We *did* note down the plan for this for the upcoming release somewhere, but I cannot find it :-). Maybe it just was in chat and nobody deemed it necessary to note it down here, we should avoid that :-).

So to reiterate: we won't go for a long-term fix for 0.8.19, but rather go for the following short term fix:

- Restore our ubuntu 20.04 buildpak Dockerfile (no need for actually rebuilding it, we just bring it back for reference)
- Change the ``b_ubu_static`` run to use the hash of that old 20.04 docker image - all other CI runs can remain on the 22.04 images.
- That's basically it - now we have working release builds again. To make @cameel happy we can extend bytecode comparison to run between the ``b_ubu_static`` binaries and e.g. the ``b_ubu`` binaries to make sure they behave the same, but I'd even consider that optional.

Let me know if anything's still unclear.
