### ISSUE TITLE
implement --opcodes-runtime

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/solidity#13956]
I want to get the opcodes dump of only the runtime bytecode  but currently only have --opcodes flag

**Comment by cameel** [comment]
Sounds reasonable, I wonder why we actually don't have it already. @chriseth @axic is there a good reason for it? The only one I can think of would be that it's not needed often enough in practice.

Note also that you can get this via Standard JSON already, by using the `evm.deployedBytecode.opcodes` output (see [Compiler Input and Output JSON Description](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description)).

**Comment by hrkrshnn** [comment]
A hacky way to get this right now is to get `--opcodes` and take the inputs after `RETURN INVALID`. We mark the runtime and deploy time code with the `INVALID` as a marker.

**Comment by ekpyron** [comment]
Out of curiosity: what's your use case? Usually I'd consider the evmasm assembly (``--asm``) output to be superior in pretty much every way. I'd even have considered dropping ``--opcodes`` and asking people to pipe ``--bin`` through geth's disassembler or something similar instead, so curious to hear use cases for this!

**Comment by chriseth** [comment]
Indeed, I would also rather remove it. It just takes the binary output and turns it into opcodes, no magic there.

**Comment by NunoFilipeSantos** [comment]
@fxfactorial can you explain with a bit more of detail your specific use case?

**Comment by nikola-matic** [comment]
Closing, as we'll be dropping support for `--opcodes` eventually.
