### ISSUE TITLE
Is the update suggestion regarding breaking changes to exponentiation in Solidity v0.8.0 correct?

### ISSUE THREAD

**Issue by ednasawe** [ethereum/solidity#13958]
## The changes in the exponentiation expression

The changes on the exponentiation on v0.8.0 was changed to be right associative operand expression from the previous (which was left associative operand) as shown on the documentation here https://docs.soliditylang.org/en/latest/080-breaking-changes.html

This is to ask for more clarification of these two statements changes you provided:

> Exponentiation is right associative, i.e., the expression `a**b**c` is parsed as `a**(b**c)`. Before 0.8.0, it was parsed as `(a**b)**c`.

While in the updates it says:

> Change `x**y**z` to `(x**y)**z`.

## Clarification

Is it correct or should the update be `x**(y**z)` instead?

**Comment by cameel** [comment]
It is correct. It tells you to change `x**y**z` to `(x**y)**z` to preserve the old behavior. If you don't do that, it will be interpreted as `x**(y**z)`, changing the meaning of your code, which most likely was written with the assumption that it means `(x**y)**z`.
