### ISSUE TITLE
Support named parameters in `abi.encodeCall`

### ISSUE THREAD

**Issue by scnale** [ethereum/solidity#13967]
## Abstract

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

interface ITest {
    function someFunction(uint256 number, bytes memory buffer) external;
}

contract Test {
    function testCallWithNamedParams(ITest someContract) external {
        // Compiles correctly ✅
        someContract.someFunction({
            number: 42,
            buffer: new bytes(0)
        });
    }

    function testEncodeCallWithNamedParams(ITest someContract) external {
        // Doesn't compile ❌
        bytes memory encodedCall = abi.encodeCall(ITest.someFunction,
            ({
                number: 42,
                buffer: new bytes(0)
            })
        );
    }
}
```

Ideally, the code above would compile as is.

## Motivation

Being able to bind arguments to named parameters reduces the chance of making a mistake when writing a call, especially so for functions with many parameters.

## Specification

I'm guessing this would require modifying the current language syntax but I'm not sure. Maybe there's an alternative way of providing this feature?

## Backwards Compatibility

I've no idea how this would impact existing code. If this does introduce new syntax like I think, there shouldn't be any backwards compatibility issues.

**Comment by cameel** [comment]
Well, we'd rather avoid introducing special syntax just for this, so it would have to be a more general language mechanism. Currently the second arg to `encodeCall()` is just a tuple and we plan to eventually introduce them as proper types you can use to declare variables. Not sure what that `({})` notation would be. A struct literal?

**Comment by scnale** [comment]
I forgot to follow up on this. Yeah, I was thinking that a struct would be the only thing that makes sense. In fact, I was thinking that having a struct type derived from a function type would help to forward parameters. Invented syntax/language features follow obviously:

```solidity
interface ITest {
    function someFunction(uint256 number, bytes memory buffer) external;
}

contract Test {
    ITest immutable someContract;

    constructor(ITest initContract) {
        someContract = initContract;
    }

    function testCallWithForwardedParams(ITest someContract, ITest.someFunction.params someArgs) external {
        someContract.someFunction(someArgs);
        // Specific syntax could instead be like this to avoid confusing with a normal call
        // someContract.someFunction(...someArgs);
    }
}
```

There's a bit of subtlety with the fact that these struct types would be encoded respecting the standard ABI at the time of performing a call instead of passed as is. That's the only thing that strikes at me as a bit strange and maybe arbitrary. I don't think there's any way to ABI encode a struct currently in the language. This would allow that even if indirectly.

Anyway, I don't really have more to offer on this topic, at least for now.
