### ISSUE TITLE
External test for OpenZeppelin failing on legacy codegen at `ERC20VotesTimestampMock` 

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13975]
`t_native_test_ext_zeppelin` started failing recently in optimized legacy runs.

### Details of the failure
[run 1265534 of `t_native_test_ext_zeppelin`](https://app.circleci.com/pipelines/github/ethereum/solidity/28507/workflows/cef6dc8d-1e7a-48db-be1e-82cb157e399d/jobs/1265534):

```
1) Contract: Governor
       using $ERC20VotesTimestampMock
         state
           Succeeded:

      AssertionError: expected '4' to equal '1'
      + expected - actual

      -4
      +1
      
      at Context.<anonymous> (test/governance/Governor.test.js:382:75)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by r0qs** [comment]
For reference, I reported the error upstream https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4049 since it seems it is not on our end.

**Comment by cameel** [comment]
Can you also disable the test as a temporary workaround?
