### ISSUE TITLE
[Feature request]: expose a function in `mapping` to return all the keys/indexes

### ISSUE THREAD

**Issue by maifeeulasad** [ethereum/solidity#13984]
## Abstract
We can create a `std::Map` or `dict` (as in python), by `mapping` in solidity. But there is a huge issue with it, I can't directly access the keys of this mapping. *I think it should be resolved*

## Motivation & Solution

I faced this issue, and resolved it with something like this:
```
mapping(address => address) public usersMapping;
address[] public users;
...
users.push(add1);
userMapping[add1] = add2;
```

## Specification
?!?

## Backwards Compatibility
!?!

## Proposal
Maybe we can resolve this by exposing a new function which will return all the keys.

## Additional note
I am pretty sure, I can help implementing this feature.

**Comment by cameel** [comment]
Sorry, but this is not fixable. Mapping keys are not stored anywhere, it's impossible for the compiler to enumerate them. If you need them, using an auxiliary array like you did is pretty much what you need to do. You can also look at iterable/enumerable mapping implementations provided by various libraries, e.g. OpenZeppelin.
