### ISSUE TITLE
Potentially non-exhaustive documentation of available invariants in SMTChecker

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum/solidity#13988]
## Page

[Reported Inferred Inductive Invariants](https://docs.soliditylang.org/en/v0.8.18/smtchecker.html#reported-inferred-inductive-invariants)

## Issue Description

It is not clear from the current documentation whether the "contract" and the "reentrancy" invariants are the only invariants that the SMTChecker can produce.

If these are not all available invariants, it would be nice to document all of them with a bulleted list. Conversely, if these are the only available invariants, then a note about this would be nice.

**Comment by NunoFilipeSantos** [comment]
@leonardoalt can you clarify? Thank you!

**Comment by leonardoalt** [comment]
Yea currently those are the only 2 reported. Will clarify it in the docs, thanks!
