### ISSUE TITLE
`build.sh` should not be installing binaries system-wide

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14012]
[`scripts/build.sh`](https://github.com/ethereum/solidity/blob/develop/scripts/build.sh) at a glance looks like a simple helper to build the compiler from source. However, it also attempts to install the built binary system-wide, which is completely unexpected. It may also overwrite a binary someone installed in `/usr/local/bin/` from a different source.

The script is recommended as a part of our instruction to install from source: [Command-Line Build](https://docs.soliditylang.org/en/latest/installing-solidity.html#command-line-build).

I think the script is at the very least confusing, if not outright dangerous. We should either remove the install part from it or rename it to make its purpose clearer.

**Comment by cameel** [comment]
Decision after discussing this: we should remove the script and put the instructions directly in the docs. This is in line with the plan to eventually clean the `scripts/` directory or rarely used stuff of questionable usefulness.

**Comment by AbhinavMir** [comment]
PR above had some issues, will re-send one in a bit! Would probably also make sense to allow for a flag `--install-to=<PATH>` for better DX.
