### ISSUE TITLE
Keyword for readonly modifiers

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#1402]
Looking across contracts, it appears that most modifiers don't change state: they're generally used for checking preconditions and "condition-orientated" programming.  IMO this is good since they are kept simple, and since they don't change state, their order doesn't matter.  So instead of the term `modifier`, as a starting point how about another (additional) keyword for them?  The cases where people are changing state in a modifier can remain the same and use `modifier`, but for new contracts where they don't change state, a term other than `modifier` seems more fitting as the contract isn't getting modified.

Some suggestions are `condition`, `precondition`, `pre`.  Other languages from https://en.wikipedia.org/wiki/Design_by_contract could be consulted for other potential names.

**Comment by VoR0220** [comment]
hmmm...interesting proposal. `pure modifier`?

**Comment by axic** [comment]
I was thinking about allowing `view` and `pure` on modifiers, but that might make it fairly complex :)

**Comment by VoR0220** [comment]
Indeed. But he raises a fine point. Modifier isnt exactly the correct keyword for most of these because its not really modifying anything. Moreso prechecking and postoperating on things.

**Comment by redsquirrel** [comment]
Modifier is the correct keyword in the context of "statement modifiers", which are a common term in Ruby and Perl (maybe other languages too).

**Comment by VoR0220** [comment]
@redsquirrel good to know! :)

**Comment by ethers** [comment]
I was aware of contexts like "statement modifiers" which do make sense.  Part of this suggestion is to prevent modifiers from being abused: sometimes it may not be clear what should be in a modifier as opposed to a function.

**Comment by VoR0220** [comment]
should modifiers not be allowed to change state?

**Comment by ethers** [comment]
> should modifiers not be allowed to change state?

Could be another discussion; I was avoiding the discussion for the meantime by suggesting this issue is like an alias just for readonly ones.  But it would be good if there were ways that the language could minimize misuse of features: I don't think modifier abuse is an issue currently, but something for us to keep in mind.

**Comment by chriseth** [comment]
We might add `view` and `pure` to modifiers (which is then of course only checked against the modifier's body and not to the function it is applied to), but I'm also fine with adding a `precondition` keyword. In that case, though, the precondition should be a bool expresison or return a bool and throw if it is false.
