### ISSUE TITLE
abi.decode failing with "Stack too deep" for a complex struct

### ISSUE THREAD

**Issue by windhustler** [ethereum/solidity#14035]
## Description

I have a complex struct:

```
 struct A {
        B[] b;
        C[] c;
        address someAddress;
}
```

where

```
struct B {
        uint96 a;
        uint32 b;
        address[] c;
        uint256[] d;
}

struct C {
        D[] d;
}

struct D {
        address a;
        address b;
        uint256 c;
        uint256 d;
        bytes e;
}
```

First I need to encode `A` into `bytes memory payload = abi.encode(A)` and then later inside another contract I need to decode `A` into `A memory a = abi.decode(payload, (A));`

The issue I am facing is `Stack too deep`, which only gets resolved if I compile it `--via-ir`.
Is this structure too complex and the only way to compile it is by turning the intermediate Yul compilation step?

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Foundry
- EVM execution environment / backend / blockchain client:
- Operating system: macOS

**Comment by matheusaaguiar** [comment]
> Is this structure too complex and the only way to compile it is by turning the intermediate Yul compilation step?

Yes. Usually, the recommended way of fixing `Stack too deep` errors is enabling `--via-ir`. Please, try using that option.

**Comment by matheusaaguiar** [comment]
Closed.
