### ISSUE TITLE
Solidity keywords based on grammar.txt

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#1403]
The following keywords should not be used outside their context defined in grammar.txt, for example not as identifiers. Else-wise Solidity code can not be processed by lexical analysers based on lex-like programs.  
 
```
-define(TOKEN_PATTERNS, [
    {"^(?i)(ADDRESS)$",          'ADDRESS'},
    {"^(?i)(ANONYMOUS)$",        'ANONYMOUS'},
    {"^(?i)(AS)$",               'AS'},
    {"^(?i)(BOOL)$",             'BOOL'},
    {"^(?i)(BREAK)$",            'BREAK'},
    {"^(?i)(CONSTANT)$",         'CONSTANT'},
    {"^(?i)(CONTINUE)$",         'CONTINUE'},
    {"^(?i)(CONTRACT)$",         'CONTRACT'},
    {"^(?i)(DAYS)$",             'DAYS'},
    {"^(?i)(DELETE)$",           'DELETE'},
    {"^(?i)(DO)$",               'DO'},
    {"^(?i)(ELSE)$",             'ELSE'},
    {"^(?i)(ENUM)$",             'ENUM'},
    {"^(?i)(ETHER)$",            'ETHER'},
    {"^(?i)(EVENT)$",            'EVENT'},
    {"^(?i)(EXTERNAL)$",         'EXTERNAL'},
    {"^(?i)(FALSE)$",            'FALSE'},
    {"^(?i)(FINNEY)$",           'FINNEY'},
    {"^(?i)(FOR)$",              'FOR'},
    {"^(?i)(FROM)$",             'FROM'},
    {"^(?i)(FUNCTION)$",         'FUNCTION'},
    {"^(?i)(HOURS)$",            'HOURS'},
    {"^(?i)(IF)$",               'IF'},
    {"^(?i)(IMPORT)$",           'IMPORT'},
    {"^(?i)(INDEXED)$",          'INDEXED'},
    {"^(?i)(INTERNAL)$",         'INTERNAL'},
    {"^(?i)(IS)$",               'IS'},
    {"^(?i)(LIBRARY)$",          'LIBRARY'},
    {"^(?i)(MAPPING)$",          'MAPPING'},
    {"^(?i)(MEMORY)$",           'MEMORY'},
    {"^(?i)(MINUTES)$",          'MINUTES'},
    {"^(?i)(MODIFIER)$",         'MODIFIER'},
    {"^(?i)(NEW)$",              'NEW'},
    {"^(?i)(PRAGMA)$",           'PRAGMA'},
    {"^(?i)(PRIVATE)$",          'PRIVATE'},
    {"^(?i)(PUBLIC)$",           'PUBLIC'},
    {"^(?i)(RETURN)$",           'RETURN'},
    {"^(?i)(RETURNS)$",          'RETURNS'},
    {"^(?i)(SECONDS)$",          'SECONDS'},
    {"^(?i)(STORAGE)$",          'STORAGE'},
    {"^(?i)(STRING)$",           'STRING'},
    {"^(?i)(STRUCT)$",           'STRUCT'},
    {"^(?i)(SZABO)$",            'SZABO'},
    {"^(?i)(THROW)$",            'THROW'},
    {"^(?i)(TRUE)$",             'TRUE'},
    {"^(?i)(USING)$",            'USING'},
    {"^(?i)(VAR)$",              'VAR'},
    {"^(?i)(WEEKS)$",            'WEEKS'},
    {"^(?i)(WEI)$",              'WEI'},
    {"^(?i)(WHILE)$",            'WHILE'},
    {"^(?i)(YEARS)$",            'YEARS'}
]).
```

**Comment by pirapira** [comment]
Do I understand correctly that this issue is about adding these keywords in the documentation and adding checks against these keywords appearing as identifiers?

**Comment by walter-weinmann** [comment]
These would be in my opinion the requirements to support lex / yacc based parsers.

**Comment by chriseth** [comment]
@walter-weinmann I am sure that this is already the case for most of these keywords. Can you create a subset of keywords where this is not the case?

Unfortunately, I think we already have quite a lot of other situations that cannot be properly parsed by parser-generator based parsers, and those are much harder to fix.

**Comment by walter-weinmann** [comment]
I could check all examples in the Solidity documentation and try to fix the problems. This would also be a good test for my parser. To make it a one time effort, we could perhaps also find a solution for my problems with the pragma directive (#1395). I could start immediately with this piece of work.

Let me know if you are interested.

**Comment by chriseth** [comment]
If all the keywords you listed are part of the token list in Token.h, then it should be fine - the pragma is of course a special case.

**Comment by walter-weinmann** [comment]
Comparing Tokren.h and grammar.txt gives the following differences:

- missing in Token.h: `from`
- missing in grammar.txt: `assembly`, `default`, `null`, `payable`

**Comment by chriseth** [comment]
Great, thanks a lot! `from` was deliberately not added to the list of keywords because it is a very common variable name.

**Comment by walter-weinmann** [comment]
Ok - then my parser is more restrictive than the compiler. I think this is not a big issue for my parser. But do we get the missing language constructs based on `assembly`, `default`, `null `and `payable `into grammar.txt?

**Comment by chriseth** [comment]
@pirapira could you add the missing keywords to the documentation, please?

**Comment by axic** [comment]
Payable is actually defined, but it has a typo: `' payable'`

**Comment by pirapira** [comment]
@chriseth I added this task to my queue.  Looks like the first PR arrives tomorrow afternoon.

**Comment by pirapira** [comment]
In `grammar.txt` I need to exclude keywords from the set of identifiers.

Can I use some syntax for excluding one syntactic category from another, like
```
Identifier = [a-zA-Z_] [a-zA-Z_0-9]* && ~Keyword
```
?

The alternative is to define `IdentifierStartingFromD` and so on, carefully avoiding the keywords.

**Comment by pirapira** [comment]
Another alternative to let the keywords to be identifiers.  In this case, some keywords do not appear in `grammar.txt` at all.

**Comment by walter-weinmann** [comment]
It is very unusual to let keywords be identifiers - in this case at least yacc-like parsers cannot be used any more. There is no need in grammars suitable for yacc-like parsers to exclude keywords explicitly from identifiers.

**Comment by pirapira** [comment]
@walter-weinmann Thank you.  Following your advice I didn't do anything to the definition of identifiers.
