### ISSUE TITLE
built-in math library

### ISSUE THREAD

**Issue by kjsisco** [ethereum/solidity#14044]
Math functions should be a part of the syntax.  I have developed a library to make it smoother for the developer.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;
library math
{
//dedicated math library
function add(uint a, uint b) internal view returns(uint)
{
//begin function
return a+b;
}
//end function
function sub(uint a, uint b) internal view returns(uint)
{
//begin function
return a-b;
}
//end function
function mult(uint a, uint b) internal view returns(uint)
{
//begin function
return a*b;
}
//end function
function div(uint a, uint b) internal view returns(uint)
{
//begin function
require(a > b, "cannot divide this");
return a/b;
}
//end function
function random(uint n) internal view returns(uint)
{
//begin function
//not cryptographically secure
return n*9+1;
}
//end function
function abs(uint n) internal view returns(uint)
{
//begin function
//absolute value
return 0+n;
}
//end function

}
//end library

**Comment by cameel** [comment]
Is this a joke?
