### ISSUE TITLE
Internal libraries in contracts does not internal into code if viaIR-mode is enabled and solidity-coverage is running

### ISSUE THREAD

**Issue by SevenSwen** [ethereum/solidity#14055]
Solidity-coverage has broken inliner optimization.
When I run coverage with optimizerSteps:
```
"dhfoDgvlfnTUtnIf" +
"[" +
    "xa[r]EscLM" +
    "cCTUtTOntnfDIl" +
    "Lcl" +
    "Vcl [j]" +
    "Tpel" +
    "xa[rl]" +
    "xa[r]cL" +
    "gvif" +
    "CTUca[r]LSsTFOtfDnca[r]Ilc"
"]" +
  "jml[jl] VcTOcl jml",
```
(default settings without `u` instrumentation in all steps) than all tests will be finished success. But If I remove `"gvif"` step then I will have error:
`NomicLabsHardhatPluginError: The contract <contract_name> is missing links for the following libraries: @openzeppelin/contracts/utils/math/Math.sol:Math`
Repo/branch:
https://github.com/1inch/farming/tree/feature/enable_viaIR

Maybe problem into solidity-coverage code, but probably they do not make any injections into the optimization steps, and any of their actions should not affect the success of the code compilation.

I also added a comment to the solidity-coverage repo [issue](https://github.com/sc-forks/solidity-coverage/issues/760#issuecomment-1473830415)

**Comment by r0qs** [comment]
Hi @SevenSwen thanks for the issue, but I suspect this is because Hardhat currently does not fully support via-ir. See: https://hardhat.org/hardhat-runner/docs/reference/solidity-support#support-for-ir-based-codegen

For reference:
```
At the moment, this option only works well when the optimizer is enabled.
Since Hardhat works much better when the optimizer is disabled, we don't completely support the viaIR option yet.
You can still enable it to compile your contracts and run your tests, but things like stack traces might not work correctly.

If you use the viaIR option, we recommend you set the optimization step sequence to "u", to make Hardhat work as well as possible
```

Could you please try using the following compiler setting:
```
settings: {
    viaIR: true,
    optimizer: {
      enabled: true,
      details: {
        yulDetails: {
          optimizerSteps: "u",
        },
      },
    },
}
```
