### ISSUE TITLE
Update deprecated github actions that the solc-bin PR check depends on

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14059]
[GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

Our PR checks in solc-bin have been complaining about it for a while now. See e.g. [run #135 on Fix nodejs version to 16 in nightly builds](https://github.com/ethereum/solc-bin/actions/runs/4245861443?pr=131):

```
generate (emscripten-wasm32, ubuntu-latest)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-python@v2, actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

We're not explicitly using node 12 (in fact we update it to node 16) so I think this must be caused by the stock actions that we invoke. They're even listed in the message:
- `actions/setup-python@v2`
- `actions/checkout@v2`
- `actions/upload-artifact@v2`

Just switching to a newer version for each of them should do the trick.

**Comment by BraxWong** [comment]
I can take this if nobody wants to
