### ISSUE TITLE
Switch to Gen2 macOS resources on CircleCI

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14058]
CircleCI is deprecating `large` and `medium` resource classes for macOS: [macOS Resource Deprecation Update](https://discuss.circleci.com/t/macos-resource-deprecation-update/46891). We're using those so we should switch to the new ones and make sure everything works.

Hopefully, should be as simple as changing their names in our config.

**Comment by BraxWong** [comment]
I can take this
