### ISSUE TITLE
Random valid program generator

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1406]
The first step of formal specification of Solidity #717 is to specify the set of strings that should compile.  This issue proposes to create a random-program generator for Solidity that produces Solidity programs that should compile.  The program generation would take less than a second, so we can test tens of thousands of random programs on the Solidity compiler.  If the compilation fails on any of these, either the program generator or the compiler is wrong.  Eventually we will get more and more accurate definition of valid Solidity programs.

**Comment by axic** [comment]
@chriseth @bshastry I think this can be closed as we have it with protobuf now? Or do we want to keep this for a standalone app?

**Comment by bshastry** [comment]
The protobuf spec targets yul/strict assembly at the moment, and not solidity itself. So, this issue can remain unless we don't want to target Solidity directly.

If we want to target Solidity, what we need to decide is how we are going to verify to test the correctness of compiled output. We could use an existing Ethereum client like geth to actually execute generate EVM bytecode, but the question remains if this EVM bytecode is correct.

Perhaps, it's more important to target the legacy optimizer (libevmasm) than Solidity.
