### ISSUE TITLE
Inquiring about Solidity Compilation Process and YUL Intermediate Language

### ISSUE THREAD

**Issue by shiningdai** [ethereum/solidity#14070]
Dear Solidity Compiler Engineers

I hope this email finds you well. I am writing to inquire about the Solidity compilation process, specifically regarding the use of YUL intermediate language.

1.  I am curious to know whether the Solidity compiler always uses YUL during the compilation process, and what role YUL plays in the overall process.

 2.  Additionally, I am interested in understanding how the Solidity compiler generates bytecode after completing the lexical, syntax, and semantic analysis phases. I have spent a significant amount of time analyzing the function call relationships in the source code, but have been unable to fully grasp the process.

Unfortunately, I do not have your email or other contact information, so I am creating this issue to make my inquiry.

I greatly appreciate any help and information you can provide on these topics. Thank you for your time and consideration, and I look forward to hearing back from you soon.

PS: I would like to clarify that my inquiry is not related to the attached files. I apologize for including them, as they were required to submit this issue on GitHub.
[README.md](https://github.com/ethereum/solidity/files/11059994/README.md)

Best regards

**Comment by cameel** [comment]
> Unfortunately, I do not have your email or other contact information, so I am creating this issue to make my inquiry.

The [forum](https://forum.soliditylang.org) is our preferred place for such discussions. Could you please repost it there?

**Comment by shiningdai** [comment]
Thank you for your prompt response. I apologize for any inconvenience caused by my previous behavior. I understand that your forum is the preferred platform for such discussions and I will repost my question there as suggested.Thank you for providing the forum for the community to share and learn from each other.



发件人："Kamil Śliwak" ***@***.***>
发送日期：2023-03-25 00:01:12
收件人：ethereum/solidity ***@***.***>
抄送人：shiningdai ***@***.***>,Author ***@***.***>
主题：Re: [ethereum/solidity] Inquiring about Solidity Compilation Process and YUL Intermediate Language (Issue #14070)

Unfortunately, I do not have your email or other contact information, so I am creating this issue to make my inquiry.
The forum is our preferred place for such discussion. Could you please repost it there?
