### ISSUE TITLE
Closed milestones are preventing some issues from being considered stale

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14092]
We have quite a few old milestones that have already been closed, e.g. [`99-nice-but-how`](https://github.com/ethereum/solidity/milestone/7). Some issues are still assigned to them and it appears that this makes the stale bot skip them. I think it should only apply to open milestones.

Modify the stale bot not to ignore issues assigned to closed milestones.

**Comment by NunoFilipeSantos** [comment]
Thank you for debugging the bot, I have been wondering the same myself.

- Milestones should be complete when closed like we have been doing. What is not complete either gets removed or shifted into a new one.
- This is a remainder of the old process. I've removed all the milestones from those issues.

Do not waste time automating this.
