### ISSUE TITLE
Cancun Support

### ISSUE THREAD

**Issue by NunoFilipeSantos** [ethereum/solidity#14094]
### Tasks
- [ ] [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
- [ ] EOF
- [ ] TBD ...
- [ ] Update Docs

### References
- [Cancun Network Upgrade Specification](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/cancun.md)
- Upgrade schedule: TBD

**Comment by laudiacay** [comment]
Hi! Has there been any thought on how to represent instantiating transient storage in solidity? Will it just be `Type transient variable = _____;`?

When can this be expected to be implemented? Is a PR helpful?

**Comment by ekpyron** [comment]
Closing in favour of https://github.com/ethereum/solidity/issues/14739
