### ISSUE TITLE
Inconsistent validation against the size of representation of rational literals

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14100]
### Description
The compiler has a check against rational literals whose representation requires more than 4096 bits to be stored. This validation is broken and also only enforced for literals using scientific notation.

I'm not sure if this actually allows anything that would break in the codegen (do we actually need to fit literals in 4096 bits?), but the broken validation should either be fixed or removed.

#### Some literals in scientific notation that do not fit 4096 bits are being accepted
`RationalNumberType::isValidLiteral()` uses `fitsPrecisionBase10()` to ensure that a literal fits available precision:
https://github.com/ethereum/solidity/blob/e29a68d37421ba46364e2e0d839ffa49a8625257/libsolidity/ast/Types.cpp#L968-L985

In `fitsPrecisionBaseX()` that precision is set to 4096 bits:
https://github.com/ethereum/solidity/blob/e29a68d37421ba46364e2e0d839ffa49a8625257/libsolutil/Numeric.cpp#L32-L39

The problem is that we don't check the precision of the whole mantissa. We only take into account the numerator (when exponent is positive) or the denominator (when exponent is negative). This means that as long as the exponent in the scientific notation is not below -1233, the mantissa can be arbitrarily large.

For example this compiles just fine despite requiring more than 4096 bits:
```solidity
contract C {
    function f() public {
        13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084096e-1233; // 2**512 * 10-1233
    }
}
```
Adding/removing digits from a mantissa does not change it.

#### Some literals in scientific notation that fit 4096 bits are being rejected
On the other hand just decreasing the exponent to -1234 makes it fail even in situations when mantissa and exponent actually would fit in 4096 bits:
```solidity
contract C {
    function f() public {
        1e-1234;
    }
}
```
```
Error: Invalid literal value.
 --> test.sol:3:9:
  |
3 |         1e-1234;
  |         ^^^^^^^
```

#### Arbitrarily large literals not in scientific notation are being accepted
Since the check is performed only for numbers that contain `e` or `E` (i.e. ones in scientific notation), the compiler still allows the user to input literals with representation just as large as `1e-1234` and even larger, as long as they're spelled out in their entirety:

```solidity
contract C {
    function f() public {
        0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001; // * 10-1234
    }
}
```

### Environment
Compiler version: 0.8.19 (`develop`)

**Comment by Saty248** [comment]
@cameel hi, is anyone working on this issue? else I can work on it.

**Comment by cameel** [comment]
This is not a good first issue. First of all, we have not really discussed it yet in the team so there's no decision on how to deal with it.

**Comment by NunoFilipeSantos** [comment]
My math might be a bit rusty, and I might be completely wrong here, but what if we:

1. Update the fitsPrecisionBaseX() function to take into account the entire mantissa of the rational literal, rather than just the numerator or denominator, by calculating the number of bits required to represent the entire mantissa using `ceil(log2(abs(numerator))) + ceil(log2(denominator))`
2. The fitsPrecisionBaseX() function should compare this number of bits to the maximum precision allowed (i.e., 4096 bits)
2.1. Return true if the number of bits required to represent the entire mantissa is less than or equal to 4096
2.2 Return false otherwise.
3. The updated fitsPrecisionBaseX() function should be called from the isValidLiteral() function to validate the precision of all rational literals, not just those in scientific notation. This would ensure that all rational literals with a representation requiring more than 4096 bits to be stored are rejected, regardless of their notation.

**Comment by ekpyron** [comment]
This is really a non-issue. The bounds are completely arbitrary and the checks are not supposed to properly validate that the numbers fit within 4096 bits, but are just to impose an arbitrary bound sufficiently larger than 256 bits that's not infinite.
I'd tend to close this issue, really.

**Comment by ekpyron** [comment]
Actually I will close this issue :-).

**Comment by cameel** [comment]
But it's not just an implementation detail. It shows through in the language. Having such arbitrary limits on scientific notation, but not normal literals is at least a wart on the language, if not an outright bug.

**Comment by ekpyron** [comment]
> But it's not just an implementation detail. It shows through in the language. Having such arbitrary limits on scientific notation, but not normal literals is at least a wart on the language, if not an outright bug.

It's non-existent cases that will *never* happen in practice. We put up those limits to get fuzzers to shut up - there is zero cause for spending time on doing this more properly.

**Comment by cameel** [comment]
Well, that's not obvious at all. In the code it looks just like a bug. I'd say that that alone warrants fixing it because anyone looking at it will just lose time trying to understand why this code is so weird. Same for anyone who actually runs into it when using the language.

Not saying that this is high priority or anything but I do think that such warts should be considered undesirable and eventually removed.

**Comment by ekpyron** [comment]
Nowhere in the code, in the error messages or elsewhere it says that we enforce a strict proper limit of 4096 bits on anything.
This is *not* worth keeping an issue open just as well as it wasn't worth spending time on doing this more properly when we added this - this discussion is already an unnecessary distraction as it stands.
We won't fix this. Sooner than fixing this directly, we'll change the way literals are handled and our bigint backend in general. Please stop these unnecessary arguments ;-).
