### ISSUE TITLE
Allow implicit conversion between contract type and address/int

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1410]
I think it would be useful at least with allowing it for `address`es:

```
contract A {
    function a() {
        A addr = address(0x123);
    }
    function b() {
        if (this != address(0x123)) {
        }
    }
}
```

**Comment by chriseth** [comment]
`address` is a "base contract" for any other contract, so implicit conversion to address is possible (`this != address(0x123)` compiles). The first use-case you mention should perhaps be better solved by the linker anyway.

Another thing we might introduce: If a hex string is exactly 20 bytes long and passes the hex "checksum" check, it is interpreted as an address and not as an integer. Adding this to https://github.com/ethereum/solidity/issues/630

**Comment by VoR0220** [comment]
One thing I want to do with the "super" class that I was talking about was separating integer from address and giving address its own type which could very well make this doable.

**Comment by axic** [comment]
> `this != address(0x123)` compiles

It doesn't, only explicit conversion is allowed, because `this` is a `ContractType` and not an `IntegerType`.

**Comment by axic** [comment]
> `A addr = address(0x123);`

So basically the question is if we want implicit address to contract conversion.


```
contract A {
    function a() {
        A addr = address(0x123);
    }
    function b() {
        if (this != address(0x123)) {
        }
    }
    function c() {
        A addr;
        if (addr != address(0x123)) {
        }
    }
}
```

`c()` compiles, but `a()` doesn't.

**Comment by chriseth** [comment]
address is a base of each contract. Allowing implicit conversion from address to contract would be like allowing implicit conversion from base to derived. What should work no and is much more intuitive:
`A a; address(a) == 0x1234`.
