### ISSUE TITLE
Addition of lottery game smart contract 

### ISSUE THREAD

**Issue by jinilshah21** [ethereum/solidity#14130]
## Abstract

I saw the examples codes like auctions, voting smart contracts provides in the code base. I will like to add one more example code to it namely lottery game smart contract.

## Motivation

Reason to add this example smart contract is to show use of global variables and show automation in smart contracts, Additionally, lottery smart contract will give insights on creating random numbers in solidity, registering users and fund allocation.

**Comment by NunoFilipeSantos** [comment]
It is not a priority for us, but you can go ahead with a draft PR, and we'll review it when we can.
I don't think the issue itself is needed. Thank you.
