### ISSUE TITLE
'string.h' file not found, when building

### ISSUE THREAD

**Issue by madvas** [ethereum/solidity#1414]
When trying to build latest release `untagged-ac13667a0597c2802196` I get following error:

```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:626:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:61:10: fatal error:
      'string.h' file not found
#include <string.h>
         ^
1 error generated.
make[2]: *** [libdevcore/CMakeFiles/soldevcore.dir/CommonData.cpp.o] Error 1
make[1]: *** [libdevcore/CMakeFiles/soldevcore.dir/all] Error 2
make: *** [all] Error 2
```

I installed dependencies with `./scripts/install_deps.sh`
I'm using macOS Sierra 10.12.1
Xcode Version 8.1 (8B62)

**Comment by madvas** [comment]
nevermind, I removed build folder and started again and it went through

**Comment by chriseth** [comment]
Note that the "untagged" tags are not meant as releases, we have some problems with our build system that generates such tags.
