### ISSUE TITLE
Missing Function Types

### ISSUE THREAD

**Issue by davidBar-On** [ethereum/solidity#14150]
## Page

[Function Types](https://docs.soliditylang.org/en/v0.8.19/types.html#function-types)

## Abstract

> Function types are notated as follows:
`function (<parameter types>) {internal|external} [pure|view|payable] [returns (<return types>)]`

`{internal|external}` should probably be `{internal|external|public|private}` as described for contract's [Function Visibility](https://docs.soliditylang.org/en/v0.8.19/contracts.html#function-visibility), where these types are called "visibility types".  It would also help if a reference to [Function Visibility](https://docs.soliditylang.org/en/v0.8.19/contracts.html#function-visibility) will be added.

## Pull request

Did not find find an issue or PR about this issue.  I am not submitting a PR since I am new to Solidity.  If the changes are acceptable then I can submit a related PR if this can help.

**Comment by ekpyron** [comment]
Note that this is about **variables of function types** not function declarations.
While a function **declaration**, so e.g.
```
contract C {
  function f() public pure {}
}
```
can indeed have public and private visibility as indeed explained in the section you mentioned: https://docs.soliditylang.org/en/develop/contracts.html#function-visibility, this is *not* the case for *variables of function type*.

A variable of function type is for example ``g`` in the following:
```
function f() public {
  function() internal pure g = ...;
}
```

For variables of function type, ``public`` and ``private`` are *not* admissible (each function type variable has to either refer to the internal or the external view of a function, so it cannot be public, and private also doesn't make sense in the context of function type variables).

Given this, I'd not consider this issue a documentation bug and am closing it (feel free to reopen if you disagree, though).
That being said, we're always welcoming PRs that improve the documentations on subtleties like this or add more cross-links for clarity, so if you have any suggestions about that, feel free to open a PR.

**Comment by davidBar-On** [comment]
Thanks for the detailed explanation.  I missed the point that this is about variables types ...  I assume that this is because I am new to Solidity, so probably no additional clarification is needed.
