### ISSUE TITLE
[SMTChecker] Underflow detected for msg.value - 0

### ISSUE THREAD

**Issue by GollyTicker** [ethereum/solidity#14169]
## Description

I have a relatively simple and small smart contract where soldity smtchecker CHC reports an underflow for an expression `msg.value - 0` - which is obviously never true. I have tried many variations and couldn't really understand and debug why this error occurs. I've minimised the entire setup into this [repository branch](https://github.com/GollyTicker/ethereum-bridge-when-cheap/tree/smtchecker-problem) where one can run a few small commands to reproduce the error. I reproduced it on two different computers running Ubuntu and latest Solidity.

## Environment

- Compiler version: 0.8.19
- Target EVM version (as per compiler settings): latest (?)
- Framework/IDE (e.g. Truffle or Remix): npm solc
- EVM execution environment / backend / blockchain client: not executed, just SMTChecker during compilation
- Operating system: Ubuntu LTS 22.4

## Steps to Reproduce

Simply follow these steps in the [README](https://github.com/GollyTicker/ethereum-bridge-when-cheap/tree/smtchecker-problem).

It will lead to the following error:
```
Warning: CHC: Underflow (resulting value less than 0) might happen here.
  --> Reproducer.sol:20:26:
   |
20 |             sentAmount = msg.value - 0;
   |                          ^^^^^^^^^^^^^
```

Obviously, there is something wrong with that.

And even more interestingly, when I change some *unrelated lines*, the warning sometimes goes away! It doesn't make any sense to me!

I couldn't figure out how to get more detailed debugging information (intermediate steps etc.) - so I'm reporting this here.

Maybe this is a configuration error on my side? But maybe it's a bug in Solidity SMTChecker.

What do you think?

**Comment by leonardoalt** [comment]
When it says "might happen here" it may be a false positive, it's not stating that it has detected an underflow. This happens when the underlying solver isn't able to prove the SMT/Horn query. A detected underflow would be reported as "happens here".

It looks silly for this expression, but it happens sometimes for CHC because CHC doesn't only look at that expressions but needs to compute inductive invariants for the whole contract, considering an unbounded number of transactions. That's also why changing seemingly unrelated things have an effect on a certain query. If you increase the timeout the false positive may vanish.  Also if you use the BMC engine it might be able to prove it.

**Comment by GollyTicker** [comment]
Ah, thanks for the quick response and the suggestions.

Funny. I interpreted the `might happen` in the way of `there exists some txs and variable assignments so that this case happens`. It seems, that the intended interpretation is `we couldn't prove safety here within the given time constraints.`

Could we perhaps change/improve the wording in the output/[documentation](https://docs.soliditylang.org/en/v0.8.19/smtchecker.html)? I have the impression, that many people will fall into the same misinterpretation. I knew, that false positives existed, but I didn't know, that this formulation of words might be a false positive. The difference in the wording is realy sublte and for non-experts it's not intuitive to know, that that's whats meant.

> It looks silly for this expression, but it happens sometimes for CHC because CHC doesn't only look at that expressions but needs to compute inductive invariants for the whole contract, considering an unbounded number of transactions. That's also why changing seemingly unrelated things have an effect on a certain query. If you increase the timeout the false positive may vanish. Also if you use the BMC engine it might be able to prove it.

Thanks for the explanations! I actually want to prove the stuff with the transactions and their interactions - which is why  I'm using CHC.

I tried now to use timeouts (which are in milliseconds according to the docs). However, using any of these values `5, 1000, 10000, 100000` leads to the following error which I can't find a way to debug:
```
Unknown exception during compilation: Dynamic exception type: std::__2::system_error
std::exception::what: thread constructor failed: Resource temporarily unavailable
```

I didn't find anything related to this. Do you know something about it?

**Comment by leonardoalt** [comment]
> Funny. I interpreted the might happen in the way of `there exists some txs and variable assignments so that this case happens`. It seems, that the intended interpretation is `we couldn't prove safety here within the given time constraints`.

Exactly! I've been meaning to change that since this is often misinterpreted, that's a nice way to put it.

> Could we perhaps change/improve the wording in the output

Will do, thanks for the feedback.

> leads to the following error which I can't find a way to debug:

That's unfortunately a bug in our WebAssembly binary when compiled with z3 that we only found out a couple weeks ago too. Unfortunately the only fix for now is using either a Linux or OSX binary (directly or with foundry/hardhat).

**Comment by GollyTicker** [comment]
> Exactly! I've been meaning to change that since this is often misinterpreted, that's a nice way to put it.

Great!

> That's unfortunately a bug in our WebAssembly binary when compiled with z3 that we only found out a couple weeks ago too. Unfortunately the only fix for now is using either a Linux or OSX binary (directly or with foundry/hardhat).

Thanks for the explanation! I tried it with the Linux package and it works seamlessly! And the timeout of 10 seconds works wel lto fix the above issue! :partying_face:

**Comment by leonardoalt** [comment]
Great to hear!
