### ISSUE TITLE
Optimizer causes code that overwrites contract fields, with an if(false) nearby

### ISSUE THREAD

**Issue by pdobacz** [ethereum/solidity#1416]
> Which version of Solidity you are using

solc is 0.4.5+commit.b318366e.Linux.g++

> What was the source code (if applicable)

```
pragma solidity ^0.4.5;

contract Test {
    uint256 public totalSupply;
    function Test() {
        totalSupply = 1000;
    }
    function f() {
        if (false) // comment the if out to fix
            var other_name = totalSupply;
        totalSupply -= 456;
    }
}
```

> Which platform are you running on

populus (TestRPC), online solidity compiler as well

> How to reproduce the issue

compile with optimization, deploy `Test`, call `f`, `totalSupply` is 2^256 - 456 afterwards

populus:
```
def test_test(chain):
    contract_factory = chain.get_contract_factory("Test")
    deploy_txn_hash = contract_factory.deploy()
    deploy_address = chain.wait.for_contract_address(deploy_txn_hash)
    asset = contract_factory(address=deploy_address)

    assert asset.call().totalSupply() == 1000
    txn_hash = asset.transact().f()
    chain.wait.for_receipt(txn_hash)
    assert asset.call().totalSupply() == 544
```

> What was the result of the issue

with the `if(false)` condition in the contract, the `totalSupply` variable gets overwritten with 0 somewhere.

> What the expected behaviour is

`totalSupply == 544`

**Comment by ethernomad** [comment]
When was this bug introduced?

**Comment by pirapira** [comment]
I'm doing `git bisect` now.  I already know it's quite recent.

**Comment by pirapira** [comment]
From 0.4.5, at e543bd34c0b4884b5a27555f698f50af6a1c0b81

**Comment by ethernomad** [comment]
Great!

https://github.com/ethereum/solidity/pull/1424
