### ISSUE TITLE
[MSVC][std:c++latest] solidity failed to build with MSVC due to error C2280:'ranges': ambiguous symbol 

### ISSUE THREAD

**Issue by Zhaojun-Liu** [ethereum/solidity#14197]
## Description
Hi all,
We add Solidity for MSVC RWC testing to detect compiler regression bugs, it built failed due to error C2872: 'ranges': ambiguous symbol with option /std:c++latest (option /std:c++20 is the same result). Could you please take a look? Thanks.

## Environment

- Compiler version: inner latest msvc build.
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Windows server 2022

## Steps to Reproduce
1. git clone https://github.com/ethereum/solidity F:\gitP\ethereum\solidity
2. git -C "F:\gitP\ethereum\solidity" checkout e1a9446
3. set \_CL_= /std:c++latest (or set \_CL_=/std:c++20)
4. mkdir F:\gitP\ethereum\solidity\build_amd64 and cd F:\gitP\ethereum\solidity\build_amd64
5. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DBoost_DIR=F:\tools\boost_1_77_0\x64\lib64-msvc-14.2\cmake\Boost-1.77.0 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded .. 
6. msbuild /m /p:Platform=x64 /p:Configuration=Release solidity.sln /t:Rebuild

I also tried the latest commit: 2da0a86, the same result.

**Expected Result:**
Build successfully.

**Actual result:**
error C2872: 'ranges': ambiguous symbol 

**detailed log:**
[build_solidity.log](https://github.com/ethereum/solidity/files/11426754/build_solidity.log)

**Comment by ekpyron** [comment]
Yeah, we used the shortcut of range-v3 to jump-start into ranges before proper C++20 support on all platforms - which together with a bad legacy habit of ``using namespace std;`` leads to problems now. We'll be attempting to refactor things to be able to be forward-compatible again (and then hopefully even switch to C++20) soon (maybe pending the upcoming debian release).

**Comment by Zhaojun-Liu** [comment]
Hi @ekpyron, any update for this issue? Or a temporary workaround will be appreciated. Thanks in advance!

**Comment by ekpyron** [comment]
By now, we are in fact actively working on refactoring the code-base and eliminating our use of ``using namespace std`` (see https://github.com/ethereum/solidity/issues/14403) - it will take some time to work through the full code base with that, but once that's done that should resolve this issue.

**Comment by nikola-matic** [comment]
This should be fixed now.
