### ISSUE TITLE
Next breaking release: change the key to lower-case "ast"

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#14194]
See https://github.com/ethereum/solidity/pull/14171/files#r1186733318.

**Comment by hrkrshnn** [comment]
Is it really needed? I think we should keep it as it is.

**Comment by ekpyron** [comment]
Yes, indeed - we'll eventually deprecate ``--combined-json`` completely and transition all its use cases to standard-json - in the interim, there's really no need to bother with this.
So I'm closing this and you can just remove the comment that triggered opening this from the import PR :-).
