### ISSUE TITLE
Update NatSpec docs to mention structs and enums

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum/solidity#14217]
## Page

https://docs.soliditylang.org/en/v0.8.20/natspec-format.html

## Description

According to the [v0.8.20 release notes](https://github.com/ethereum/solidity/releases/tag/v0.8.20), structs and enums can now be documented with NatSpec comments.

However, Solidity's documentation website doesn't make any references to these newly introduced capabilities. For example, the [`Tags` table](https://docs.soliditylang.org/en/v0.8.20/natspec-format.html#tags) should be updated to explain that the `@title`, `@author`, `@notice`, and `@dev` tags can now be applied to structs and enums.

**Comment by AnuragNishad12** [comment]
Hey @PaulRBerg  can u tell me what i have to do here in the documentation?

**Comment by adityakode** [comment]
@PaulRBerg  I have  made a PR that will fix this https://github.com/ethereum/solidity/pull/14267

**Comment by PaulRBerg** [comment]
Thanks @adityakode - sorry, I am not a Solidity maintainer so I'm not sure if your PR is complete, but it looks good to me.

**Comment by auryn-macmillan** [comment]
It would be really nice if there was something analogous to the `@param` tag for documenting the members of a struct or enum.

For example:
```solidity
/// @dev A struct with two members
/// @member firstNumber The first member in this struct
/// @member secondNumber The second member in this struct
struct MyStruct {
    uint256 firstMember;
    uint256 secondMember;
```

Would using the `@param` tag be acceptable here?
```solidity
/// @dev A struct with two members
/// @param firstMembers The first member in this struct
/// @param secondMember The second member in this struct
struct MyStruct {
    uint256 firstMember;
    uint256 secondMember;
```

Or would one be better off using a custom tag?
```solidity
/// @dev A struct with two members
/// @custom:member firstMembers The first member in this struct
/// @custom:member The second member in this struct
struct MyStruct {
    uint256 firstMember;
    uint256 secondMember;
```

**Comment by gabrielkrell** [comment]
Got here via Google. I would also really like tag support for struct and enum members. Currently I have to do this nonsense
```solidity
    /**
     * @notice Share of incoming fees given to `recipient`.
     * @custom:recipient Who these fees should be delivered to
     * @custom:feeratio Fraction of incoming fees sent to this recipient. In range (0, 1]
     * @custom:pendingfees Accumulated fees that have not yet been delivered
     * @custom:distributiontype See [DistributionType](#distributiontype)
     */
    struct FeeAllocation {
        address recipient;
        FPUnsigned feeRatio;
        FPUnsigned pendingFees;
        DistributionType distributionType;
    }
 ```
 and parse the custom tags myself for my documentation generator (note that uppercase characters are not valid custom tag names, so you need to transform the member names), instead of just writing `@notice` in line.
 
 ```solidity
     struct FeeAllocation {
        address recipient; ///@notice Who these fees should be delivered to
        FPUnsigned feeRatio; ///@notice Fraction of incoming fees sent to this recipient. In range (0, 1]
        FPUnsigned pendingFees; ///@notice Accumulated fees that have not yet been delivered
        DistributionType distributionType; ///@notice See [DistributionType](#distributiontype)
    }
```

Software shouldn't make us choose between documented and ugly code. Can make a separate issue for this if necessary.
