### ISSUE TITLE
Update warning in Inline assembly section in Solidity docs

### ISSUE THREAD

**Issue by mcgrathcoutinho** [ethereum/solidity#14224]
## Page

(https://docs.soliditylang.org/en/v0.8.20/assembly.html#memory-management)

## Abstract

The warning in the section i've linked above does not seem to be valid. Statically-sized memory arrays seem to have a length field when I test it in Remix. Images for reference: 

![image](https://github.com/ethereum/solidity/assets/109625274/23709da9-5208-4ba9-b4b3-8ca4e588af96)
![image](https://github.com/ethereum/solidity/assets/109625274/0d3f8e1d-0d2f-4e90-9999-06440e1bc112)

## Pull request

https://github.com/ethereum/solidity/pull/14223#issue-1709345438

**Comment by ekpyron** [comment]
The documentation is talking about the low-level representation in memory, not about high-level language members here. The docs are still accurate in that regard: static arrays don't store their length in memory, but might in the future.
