### ISSUE TITLE
Compile from source failing

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#1423]
I'm running into an error when compiling from source.

The error occurs during execution of the `./scripts/install_deps.sh` script.

* Error: https://travis-ci.org/pipermerriam/py-solc/jobs/178072066#L1583
* Full Script being used to build: https://github.com/pipermerriam/py-solc/blob/9caabbc9debfe744848df1b834a99228706b8053/bin/install_solc-0.4.6.sh

This has been working for all previous released versions down to `0.3.6`

**Comment by axic** [comment]
```
 CMake Error at CMakeLists.txt:16 (include):
  include could not find load file:
    deps/jsoncpp.cmake
```

You need to ensure the `deps` submodule is properly updated.

**Comment by pipermerriam** [comment]
I'm pulling the source from the zip file from the releases on github so I'm
not working in a repository. Is this potentially something that is missing
from the script that is supposed to install all dependencies?

**Comment by chriseth** [comment]
Yes, please only compile using git. The zip auto-generated by github does not work because it does not contain the submodule, and there is no way to modify the generation to include submodules.

**Comment by VoR0220** [comment]
The hash matching the newly signed file is incorrect. Per alpine problems.
