### ISSUE TITLE
Nightly builds of Colony external test failing due to Shanghai update

### ISSUE THREAD

**Issue by r0qs** [ethereum/solidity#14230]
See: https://app.circleci.com/pipelines/github/ethereum/solidity/29756/workflows/a23efbf4-843d-4aa7-a909-a5161e7351ca/jobs/1322000?invite=true#step-110-1258

There is a fix in progress here: https://github.com/ethereum/solidity/tree/update-colony-ext-test but it still failing for some of the Colony tests which are triggered during nightly builds.

As this requires a bit more investigation, I decided to open the issue here so I can get back to it later.

**Comment by AnuragNishad12** [comment]
hey @r0qs  im new here how i can contribute to it

**Comment by r0qs** [comment]
Hi @AnuragNishad12 thanks for interest in contributing, but we decided to drop that test from the nightly builds.

**Comment by AnuragNishad12** [comment]
okay thanks
