### ISSUE TITLE
solc does not warn/error on duplicate `@param` entry

### ISSUE THREAD

**Issue by seanyoung** [ethereum/solidity#14256]
## Description

Developer would like to know if duplicate `@param` entries are given.

## Environment

solc-0.8.20

## Steps to reproduce

```solidity
contract c {
	/// @param f asdad
	/// @param f bar
	struct s {
		uint32 f;
	}
}
```

Compile this: no errors/warnings

Note: solang says:

```
warning: duplicate tag '@param' for 'f'
  ┌─ /home/sean/git/solang/f.sol:3:6
  │
2 │     /// @param f asdad
  │         -------------- previous tag '@param' for 'f'
3 │     /// @param f bar
  │         ^^^^^^^^^^^^
```

See https://github.com/hyperledger/solang/pull/1320

Found in uniswap v3: https://github.com/Uniswap/v3-core/blob/main/contracts/interfaces/pool/IUniswapV3PoolEvents.sol#L118-L119

**Comment by NunoFilipeSantos** [comment]
Decision: For now, we have decided to go with a Warning instead of throwing out an error.
