### ISSUE TITLE
Fix small typo on "Units and Globally Available Variables" page

### ISSUE THREAD

**Issue by johnnygee19** [ethereum/solidity#14253]
## Page

https://docs.soliditylang.org/en/latest/units-and-global-variables.html

## Abstract

Just a small typo.

"OpenZeppelin have a ECDSA helper library that..." should be "OpenZeppelin has a ECDSA helper library that...".

## Pull request

https://github.com/ethereum/solidity/pull/14252

**Comment by AnuragNishad12** [comment]
I can fix it

**Comment by NunoFilipeSantos** [comment]
Merged.
