### ISSUE TITLE
Optimizer failed to detect useless ``require(x == y || true)`` statement

### ISSUE THREAD

**Issue by hpumengzhao** [ethereum/solidity#14251]
### Description
The compiler failed to simplify ``x == y || true`` to ``true`` but it can optimize ``true || x == y`` and ``false || true``
### Environment 
Tested on Remix of compiler version 0.8.19+commit.7dd6d404
### Reproduce 
1. source code
```solidity
pragma solidity ^0.8.0;

contract RandomProgram {
    function test(uint x, uint y) pure public returns(uint){
        require(x == y || true);//failed
        require(false || true);//optimized
        require(true || x == y);//optimized
        x += y;
        return x;
    }
}
```
2. compiler_config.json
```json

{
	"language": "Solidity",
	"settings": {
		"viaIR": true, 
		"optimizer": {
			"enabled": true,
			"runs": 200
		},
		"outputSelection": {
			"*": {
			"": ["ast"],
			"*": ["abi", "metadata", "devdoc", "userdoc", "storageLayout", "evm.legacyAssembly", "evm.bytecode", "evm.deployedBytecode", "evm.methodIdentifiers", "evm.gasEstimates", "evm.assembly"]
			}
		}
	}
}
```

**Comment by AnuragNishad12** [comment]
what's the problem u are facing?
@hpumengzhao

**Comment by hpumengzhao** [comment]
I mean if it is a missed optimization can be fixed？

**Comment by ALIR86** [comment]
Hello when creat a legally contract of my token source complate legally and officialy  just tell me this address not added to list yourself with sorry easly talking with you ,error give me I donot what's the means opinions  this all contract just 4,5 are in my list,this contract f,ETHFixed  leansi donot submitted it compiler version , v0.8.4+ commit.c7e47f2.pdf  display me with succefully do it but why my contracts aren't  in list contract me in my account etherscan ,they have a  Audit registered ion that of sour code 13 file you should find any issuse that it has been coded to fill the audit registere you should enter address a few company  with explain added the more ,pleasure request language  congime source  code for confim  a few forms pleasure  request language  progress  coded easly  for to filling as language easy a human  that is new. User or unfortunately  experience  it I hasnot and confime source code contract that of a   secure and legally address coming to etherscan.io I saw a  top course  code a ⚠️entered fthat any code but havenont any contract not to be secure  ,,am so sorry in metawin.com  I have 3 contract win a contract PEPE  coins a contract 5 rewad ETH and a win polygon to billion are those that a person in the and social app,worte to me about PEPE coins ,sended message in tage my device  ,!!You are Tagged and confimed  in PEPE coins but no in Twitter  PEPE account  were with a address contract in tweet their  I donot know but address transaction they were,didnot got it and now I am depressed  and confuced metawin.com  nothing responce about my history activity me to participate  in rewads them that after I saw my balance was 1 ETH  that zeroed a one I know by metawin.com  was pricing amount  ERH wrote in official screen this platform that but of coinflex.com a one wrote to me this are a crazy due zeroed ETH balance  account etherscan to , pleasure request any where pritect and  the monitoring in the all my contract smart  and my issues about Goverance proposal addresses contracts give me management this digital currency compond, Lido,please protect of my right and my salary your always help and support me thank you of my all ❤️ 💙 💜 https://.www.github.com  pleasure iam not API and domain and today cloudflare.com  becuse donations  address i request for Goverance  help of commanity but cloudflare.com  but doesnot let to open screen etherscan.io to confim it by myself still not donot them  cloudflare.com like CAPTCHA  is a private picy monitor no banand leftsolve all my request 
Best regards,goodnight.🪽💚🙏
