### ISSUE TITLE
Allow `@inheritdoc` Natspec tag for `constructor`

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14260]
## Abstract

Currently, the Natspec tag `@inheritdoc` is only valid for `functions` and `public` state variables.

<img width="695" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/6bce94d2-e15d-4731-86a1-179691139cb4">

Solidity does not allow to compile if a `constructor` contains an `@inheritdoc` Natspec tag. See below.

<img width="1259" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/3bacc28b-48ad-4c0f-9716-eb1203cb0fba">

<img width="631" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/c6482579-3d88-4b05-a8dc-0db372960b7c">

## Motivation

This would be useful to not have to copy-paste the Natspec comments from the Parent contract `constructor` into the child contract `constructor` for behaviour inherited from `constructor`.

For instance in the example above, I have to write twice the Natspec tag `@dev Emits a `ValueReceived` event when funding the contract on deployment.`, although this is already present in the Natspec of the `constructor` of the parent contract.

**Comment by AnuragNishad12** [comment]
I didn't understand this can u , simplify it for me @CJ42

**Comment by CJ42** [comment]
@AnuragNishad12 

Basically if a contract inherits another contract that has a `constructor` with some Natspec in it, the Natspec in the `constructor` of the parent contract are lost unless you copy-paste them in the child contract.

In the example above, the `constructor(...)` of `UniversalProfile` also runs the `constructor` of the inherited contract `LSP0ERC725Account`.
The `constructor` of `LSP0ERC725Account` contains some Natspec, but it is not parsed, unless I copy-paste and port over all the Natspec from `LSP0ERC725Account -> constructor` to `UniversalProfile -> constructor`.
