### ISSUE TITLE
Can't see generated SMTLib2 code 

### ISSUE THREAD

**Issue by cvick32** [ethereum/solidity#14293]
Solidity version 0.8.19

## Page

https://docs.soliditylang.org/en/v0.8.17/smtchecker.html and https://docs.soliditylang.org/en/v0.8.17/smtchecker.html#smtchecker-options

## Abstract

I want to see the SMTLib2 file that is being generated for a contract (see below). I see that there is a command line flag for this, --model-checker-solvers=smtlib2, but when I use that option nothing is generated. 

Thanks for your help. 

`// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.0;

contract Robot {
    int x = 0;
    int y = 0;

    modifier wall {
        require(x > type(int128).min && x < type(int128).max);
        require(y > type(int128).min && y < type(int128).max);
        _;
    }

    function moveLeftUp() wall public {
        --x;
        ++y;
    }

    function moveLeftDown() wall public {
        --x;
        --y;
    }

    function moveRightUp() wall public {
        ++x;
        ++y;
    }

    function moveRightDown() wall public {
        ++x;
        --y;
    }

    function inv() public view {
        assert(!(x == 2 && y == 4));
        //assert((x + y) % 2 == 0);
    }
}`

**Comment by cvick32** [comment]
So it looks like in the solc-js project you can see a temporary smtlib2 file [being written](https://github.com/ethereum/solc-js/blob/master/smtsolver.ts#LL39C13-L39C13). I really just need this file to persist. 

Any ideas?

**Comment by AnuragNishad12** [comment]
Hi @cvick32 read this
<img width="584" alt="image" src="https://github.com/ethereum/solidity/assets/124987038/23ed4304-d838-4edc-ba9e-8c51c4558882">

**Comment by leonardoalt** [comment]
@cvick32 currently it's possible but it's tricky. There's a PR adding that and it will be available in the next release.

https://github.com/ethereum/solidity/pull/14307
