### ISSUE TITLE
Out of Gas issue

### ISSUE THREAD

**Issue by Alinawaz-786** [ethereum/solidity#14294]
When I try to send transection I have getting issue of out of gas
https://testnet.snowtrace.io/tx/0xa0d95c6fdfe7eb91118ce5b3649a7af9c0b410024294b199b5891b25f27642fa

**Comment by Prezzy06** [comment]
@Alinawaz-786  
@Alinawaz-786                                                                                                                                                                                 I think that it can have any of the three reasons:
1. The transaction is trying to do something that requires a lot of computation, such as interacting with a complex smart contract.
2. The gas limit is set too low.
3. The user does not have enough ETH to pay for the gas.

To fix this error, you can try increasing the gas limit, or you can try again with a smaller transaction. If you do not have enough ETH to pay for the gas, you will need to deposit more ETH into your wallet.

To avoid this error, it is important to set the gas limit high enough to cover the computational effort required to execute the transaction. You can use a tool like Etherscan to estimate the gas needed for a transaction.

**Comment by Prezzy06** [comment]
I think that it can have any of the three reasons:

The transaction is trying to do something that requires a lot of computation, such as interacting with a complex smart contract.
The gas limit is set too low.
The user does not have enough ETH to pay for the gas.
To fix this error, you can try increasing the gas limit, or you can try again with a smaller transaction. If you do not have enough ETH to pay for the gas, you will need to deposit more ETH into your wallet.

To avoid this error, it is important to set the gas limit high enough to cover the computational effort required to execute the transaction. You can use a tool like Etherscan to estimate the gas needed for a transaction.

**Comment by Prezzy06** [comment]
@Alinawaz-786 I think that it can have any of the three reasons:

1.The transaction is trying to do something that requires a lot of computation, such as interacting with a complex smart contract.
2.The gas limit is set too low.
3.The user does not have enough ETH to pay for the gas.

To fix this error, you can try increasing the gas limit, or you can try again with a smaller transaction. If you do not have enough ETH to pay for the gas, you will need to deposit more ETH into your wallet.

To avoid this error, it is important to set the gas limit high enough to cover the computational effort required to execute the transaction. You can use a tool like Etherscan to estimate the gas needed for a transaction.

**Comment by Prezzy06** [comment]
I think it may have resolved your issue

**Comment by Alinawaz-786** [comment]
> @Alinawaz-786 I think that it can have any of the three reasons:
> 
> 1.The transaction is trying to do something that requires a lot of computation, such as interacting with a complex smart contract. 2.The gas limit is set too low. 3.The user does not have enough ETH to pay for the gas.
> 
> To fix this error, you can try increasing the gas limit, or you can try again with a smaller transaction. If you do not have enough ETH to pay for the gas, you will need to deposit more ETH into your wallet.
> 
> To avoid this error, it is important to set the gas limit high enough to cover the computational effort required to execute the transaction. You can use a tool like Etherscan to estimate the gas needed for a transaction.

I thing I have issue **(1)** in our smart contract is they any solution to solve this problem?

**Comment by HamzaMobeen786** [comment]
I also have same issue

**Comment by r0qs** [comment]
Hi @Alinawaz-786 and @HamzaMobeen786 , please let's keep issues in this repo only for problems directly related to the Solidity compiler. You can post general questions about Solidity or usage problems in our [forum](https://forum.soliditylang.org/), [Matrix channel](https://app.gitter.im/#/room/#ethereum_solidity:gitter.im), or [Ethereum stackexchange](https://ethereum.stackexchange.com/).
