### ISSUE TITLE
Allow to define `constructor` with params lists in `interface`

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14308]
## Abstract

There are occurences of some contract implementation that miss implementing a `constructor` to set some crucial state variables on deployment. Most basic example is `Ownable`. If the `owner` is not defined on deployment, the contract is blocked.

This can be an issue as this can only be caught at runtime, once the contract has been deployed. But the damage has already been done.

## Motivation

I would like to propose enabling to add `constructor` in an `interface`, so that to define what MUST be set on deployment, but also to ensure that state variables that must be set on deployment are actually set. The error would then be thrown in this case at compile time, not caught at runtime after the contract has been deployed.

## Specification

Here would be a basic example with `Ownable`

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IOwnable {

    constructor(address newOwner) external;

}
```

## Backwards Compatibility

The problem comes with the proxy pattern. Where the `constructor` in this case is not applicable. However, alternative interfaces can be defined for proxy versions.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IOwnableProxy {

    function initialize(address newOwner) external;

}
```

**Comment by NunoFilipeSantos** [comment]
Hi @CJ42 ! 👋  
Currently, we're not planning to spend time on this.

Thank you for reaching out.
