### ISSUE TITLE
We were not able to estimate gas. There might be an error in the contract and this transaction may fail.

### ISSUE THREAD

**Issue by s-bunthoeun1** [ethereum/solidity#14312]
## Description
Please team core help check this function on testnet workingl, but mainnet does't work

## Environment
ethereum mainnet 
https://etherscan.io/address/0x24288d6332f800282eE0538d044dcaA3A8786Aaf#code

**Comment by r0qs** [comment]
Hi, this is not the right place for this type of problem. Please refer to our [forum](https://forum.soliditylang.org/), [Matrix channel](https://app.gitter.im/#/room/#ethereum_solidity:gitter.im), or [Ethereum stackexchange](https://ethereum.stackexchange.com/).
