### ISSUE TITLE
Enums can be implicitly converted to integers when using abi.encodePacked

### ISSUE THREAD

**Issue by rellfy** [ethereum/solidity#14326]
## Description

[The documentation states that Enums cannot be implicitly converted to integers. ][0]
However, this does not result in a compile time error.

The following code

```solidity
enum Enum { A }
bytes32 message_implicit = keccak256(abi.encodePacked(Enum.A));
```

Results in the enum being implicitly converted to an `uint8`. It is the same as:

```solidity
bytes32 message_explicit = keccak256(abi.encodePacked(uint8(Enum.A)));
```

This is counter-intuitive and likely not wanted for the reason that `abi.encodePacked` is usually used for packing messages, and these messages are then verified by signatures. If the type is implicitly `uint8` but the signature expects `uint256` (usually the case by solidity standards), then the signature check will fail.

Either the docs need to be corrected, or this should be fixed to result in a compilation error requiring an explicit cast.

## Environment

- Compiler version: 0.8.20
- Target EVM version: Hardhat 2.14.1
- Framework/IDE: Hardhat
- EVM execution environment / backend / blockchain client: Hardhat

## Steps to Reproduce

```solidity
contract OhMyGod {
    enum Enum { A }
    constructor() {
        bytes32 message_explicit = keccak256(abi.encodePacked(uint8(Enum.A)));
        // This should revert because the enum is implicitly converted to uint.
        bytes32 message_implicit = keccak256(abi.encodePacked(Enum.A));
        assert(message_explicit == message_implicit);
    }
}
```

[0]: https://docs.soliditylang.org/en/v0.8.20/types.html#enums

**Comment by r0qs** [comment]
Hi @rellfy thanks, but this is not an issue. The encoding type of `Enum` is `uint8` so your example should not revert indeed. Please see table https://docs.soliditylang.org/en/latest/abi-spec.html#mapping-solidity-to-abi-types for details of abi encoding types associated with other Solidity types.

The `abi.encodePacked` result is consistent for all encoding types of a type. However, its use is discourage for signatures, authentication or data integrity (please see the [warning](https://docs.soliditylang.org/en/develop/abi-spec.html#non-standard-packed-mode) in the end of this documentation section), but in some use cases you cannot avoid it. The use of `abi.encode` and `bytes.concat` is preferred.
