### ISSUE TITLE
internalType in ABI json not documented

### ISSUE THREAD

**Issue by thedavidmeister** [ethereum/solidity#14352]
## Page

https://docs.soliditylang.org/en/latest/abi-spec.html#json

## Abstract

`internalType` that appears in ABI JSON is not documented

**Comment by AnuragNishad12** [comment]
Hi @thedavidmeister  Should i document the internalType ?

**Comment by thedavidmeister** [comment]
@AnuragNishad12 yes please, i can't because i don't know what it is because it isn't documented

**Comment by AnuragNishad12** [comment]
okay @thedavidmeister
