### ISSUE TITLE
Function signature literals

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1435]
Out of a gitter conversation there came an idea of looking up `authorization_table[msg.sig][msg.caller]`.  For setting up such a table, it would be convenient to have function signature literals `signature_hash(f(void))` that represents the signature hash.

```
contract C {
    mapping (bytes4 => mapping (address => bool)) authorization_table;
    modifier auth() {
        if (!authorization_table[msg.sig][msg.caller]) throw;
        _;
    }

    function interface() auth;
    function allow_interface(address _somebody) auth {
        authorization_table[signature_hash(interface(void))][_somebody] = true;
    }
}
```

**Comment by VoR0220** [comment]
I think this falls under Christians group modifier proposal.

**Comment by pirapira** [comment]
@VoR0220 the proposal #623 does not use `msg.sig`.

Since `msg.sig` is a part of the language, the language should also support interpreting the value of `msg.sig` in a convenient manner.  For interpreting `msg.sig`, the language needs a way to associate the signature hashes and the function signatures.

**Comment by VoR0220** [comment]
It could very well use msg.sig "under the hood" is my point. This is a potential way to implement it is my point.

**Comment by VoR0220** [comment]
But i think maybe you're looking for something else is your point.

**Comment by axic** [comment]
You can already create function signatures with `bytes4(keccak256("interface()"))`.

However since we have function types, we could introduce `.sig` member on them to return this: `interface.sig`.

**Comment by frangio** [comment]
Manually creating function signatures seems error prone. A `.sig` member sounds great.
