### ISSUE TITLE
docs: what happens on insufficient balance during ether transfer

### ISSUE THREAD

**Issue by sebastiantf** [ethereum/solidity#14376]
## Page
https://docs.soliditylang.org/en/v0.8.19/security-considerations.html#sending-and-receiving-ether

## Abstract

Couldn't find an explanation of what happens when an ether transfer occurs from a contract, for more amount that the caller's balance. This could arguably be a trivial info to have, but still would be helpful to an official note about this.

Would be helpful if the case is discussed wrt different ways of ether transfer (`send()`, `transfer()`, `call()`)

PS: Apologies if I missed the explanation from elsewhere

## Pull request
Nil

**Comment by Ifechukwudaniel** [comment]
Hey would you love this if i work on it

**Comment by Ifechukwudaniel** [comment]
Should I work on this

**Comment by matheusaaguiar** [comment]
Hi @sebastiantf, thanks for your report. 
That information is already available in the docs. You can check it [here](https://docs.soliditylang.org/en/v0.8.20/types.html#members-of-addresses):
`The transfer function fails if the balance of the current contract is not large enough or if the Ether transfer is rejected by the receiving account. The transfer function reverts on failure.`

**Comment by sebastiantf** [comment]
Thanks! Altho, it would make sense to have it in https://docs.soliditylang.org/en/v0.8.19/security-considerations.html#sending-and-receiving-ether too

**Comment by matheusaaguiar** [comment]
I would say that having insufficient funds is **not** a security consideration or concern.
