### ISSUE TITLE
Add additional composite assignments `||=` and `&&=`

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#14383]
## Abstract

Solidity should add support for the following two new composite assignments:
- Logical `OR` assignment (`||=`)
- Logical `AND` assignment (`&&=`)

> I opened this issue in order to discuss whether this is worth adding or not.

## Motivation

A couple of languages (e.g. Ruby or JavaScript) support the following two composite assignments:
- Logical `OR` assignment (`||=`)
- Logical `AND` assignment (`&&=`)

Those are currently not supported by Solidity. I open this issue in order to discuss whether this is a desired feature for Solidity devs.

## Specification

- The logical `OR` assignment (`x ||= y`) operator only assigns if `x` is "`falsey`". Or in other words, `x ||= y` is equivalent to `x || (x = y)`. `x` is "`falsey`" if it matches the Solidity type default value.
- The logical `AND` assignment (`x &&= y`) operator only assigns if `x` is "`truthy`". Or in other words, `x &&= y` is equivalent to `x && (x = y)`. `x` is "`truthy`" if it doesn't match the Solidity type default value.

## Backwards Compatibility

Not backward-compatible as this introduces a new language feature.

**Comment by DanielVF** [comment]
Although it naturally follows from the specification above, shortcutting behavior is often a key part of how these operators are used in other languages. In the following example, the expensive computation will only be run if the cached value is not present.

```javascript
cached ||= otherContract.expensiveComputation();
```

Another aspect is that this can be used on more than just simple variables.

With transient storage on the way, code could be:

```javascript
cache[foo] ||= _expensiveCalc(foo);
```

Or it could work on structs or arrays:

```javascript
bacon.interestRate ||= 1e5;
```

**Comment by DanielVF** [comment]
All of the above straightforwardly follow from the basic syntax expansion.

It does gets non-obvious what would happen when code executing on the right hand side modifies a variable used to select the read/write variable in the left hand side. For example:

In javascript,

```javascript
foo = 1
doStuff = () => foo = 2
dict = {}
dict[foo] ||= doStuff()
```

In ruby,

```ruby
foo = 1
doStuff = proc { foo = 2 }
dict = {}
dict[foo] ||= doStuff.call()
```

In both languages cases the key used for the set in `dict` is `1`. The rule followed is that the location read is the location written to, rather than just rerunning the syntax again for an assignment. So strictly speaking 


```javascript
dict[foo] ||= doStuff()
```

is the same as

```javascript
if(! dict[foo]) {
  dict[foo] = doStuff()
}
```

but not:

```javascript
if(! dict[foo]) {
  newValue = doStuff()
  dict[foo] = newValue
}
```

**Comment by NunoFilipeSantos** [comment]
Hi @DanielVF! 👋 
We really appreciate your enthusiasm. 
However, this is not something we are currently interested in pursuing for the Language.
