### ISSUE TITLE
Work around breaking Windows changes added in `boost::filesystem` 1.78

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14396]
We discovered this back in https://github.com/ethereum/solidity/pull/13434#issuecomment-1227665365. 

Boost introduced some changes in behavior in a some obscure corner cases on Windows (UNC paths is one of them), which would make compiler behavior in these cases different, depending on which version it was built with. We need to add workarounds to make the compiler keep its current behavior even with new Boost.

Being stuck on Boost < 1.78 is also a blocker for our C++ 20 migration.

**Comment by molecula451** [comment]
is this a reproducible issue only on Windows builds?

**Comment by cameel** [comment]
Yes.
