### ISSUE TITLE
User-defined operators don't select the correct overloaded function

### ISSUE THREAD

**Issue by gabrielkrell** [ethereum/solidity#14400]
## Description

If you have multiple functions with the same name but different parameters, they cannot be used as user-defined operators. Since, for instance, `isEqual(Signed, Signed)` is not a valid target for a user-defined `Unsigned.==` operator, I expect the compiler to be smart enough to select the correct function. Unfortunately it isn't, and there's no way to explicitly select the correct function (#3556).

## Environment

- Compiler version: 0.8.20
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): hardhat

## Steps to Reproduce

```solidity
pragma solidity ^0.8.19;

type Unsigned is uint256;
type Signed is int256;

function isEqual(Unsigned a, Unsigned b) pure returns (bool) {
    return Unsigned.unwrap(a) == Unsigned.unwrap(b);
}

function isEqual(Signed a, Signed b) pure returns (bool) {
    return Signed.unwrap(a) == Signed.unwrap(b);
}

using {
    FixedPoint.isEqual as == // DeclarationError: Identifier is not a function name or not unique. (9589)

} for Unsigned global;
```

**Comment by cameel** [comment]
Yeah, well, it's a known limitation and was even mentioned in the [blog post introducing operators](https://blog.soliditylang.org/2023/02/22/user-defined-operators/). As you mentioned we have #3556, which already covers the underlying issue. We won't be adding workarounds just  just for the operator case.

As for #3556, we know it's a problem, and we're working on addressing it in the long term, but it probably won't be in the form of a direct fix. We have big design changes in the pipeline, including changes to how overloading works, and these will likely just make the problem irrelevant in the first place.
