### ISSUE TITLE
Change style to not use `using namespace std`

### ISSUE THREAD

**Issue by nikola-matic** [ethereum/solidity#14403]
As part of our move towards c++20, we need to remove all instances of `using namespace std;` usage in order to alleviate current and future name clashes from within different namespaces; a prominent example of this is our use of `ranges`, where we are currently using `rangesv3` and will switch to `std::ranges`.

This is also a prerequisite for the introduction of `clang-format`, which should make our style checking and consistency of said style significantly easier.

The following directories are to be adapted:

- [x] libevmasm
- [x] liblangutil
- [x] libsmtutil
- [x] libsolc
- [x] libsolidity/analysis
- [x] libsolidity/ast
- [x] libsolidity/codegen
- [x] libsolidity/formal
- [x] libsolidity/interface
- [x] libsolidity/lsp
- [x] libsolidity/parsing
- [x] libsolutil
- [x] libyul
- [x] libyul/backend
- [x] libyul/optimiser
- [x] solc
- [x] test
- [x] test/contracts
- [x] test/libevmasm
- [x] test/liblangutil
- [x] test/libsolidity
- [x] test/libsolidity/analysis
- [x] test/libsolidity/interface
- [x] test/libsolidity/util
- [x] test/libsolutil
- [x] test/libyul
- [x] test/solc
- [x] test/tools
- [x] test/tools/ossfuzz
- [x] test/tools/ossfuzz/protomutators
- [x] test/tools/yulInterpreter
- [x] test/yulPhaser
- [x] tools/yulPhaser

**Comment by cameel** [comment]
We're not done with this yet. Should this really be closed already?

**Comment by nikola-matic** [comment]
> We're not done with this yet. Should this really be closed already?

Uh, no. I put in `partially fixes` in my PRs, why is this auto closing?

**Comment by cameel** [comment]
Because this still matches github's `fixes #xyz` regex :) I guess it's a feature.

**Comment by cameel** [comment]
I see that this was closed, but weren't we supposed to get rid of this whitelist before doing that? https://github.com/ethereum/solidity/blob/ae40e1a04acacd639fed0dfcb3dd1cdc11406044/scripts/check_style.sh#L23-L59

It really should have been a list we're removing stuff from over time, not the other way around...

**Comment by nikola-matic** [comment]
> I see that this was closed, but weren't we supposed to get rid of this whitelist before doing that?
> 
> https://github.com/ethereum/solidity/blob/ae40e1a04acacd639fed0dfcb3dd1cdc11406044/scripts/check_style.sh#L23-L59
> 
> It really should have been a list we're removing stuff from over time, not the other way around...

No? This is about the only thing that's going to stay in the check style script after we introduce clang-format. An easier way would be to just check that `using namespace std;` does not occur in any cpp file, but if we want to hard forbid it, there's really no other way.

On the other hand, we could get rid of this list completely and rely on the fact that we'll notice in the review if someone introduces it.

**Comment by cameel** [comment]
> An easier way would be to just check that `using namespace std;` does not occur in any cpp file

Wasn't that the whole point? We have no files containing `using namespace std;` now. A check that it does not get added back is exactly what we want.

Even if we wanted to allow it in some files, having a mechanism where you have to list all places where it *cannot* appear (instead of simply listing that single place where it can) is just bizarre :)  I only really let this through because you said it was easier to implement this way and that it was just temporary anyway. Otherwise it makes no sense.

This needs to be removed.
