### ISSUE TITLE
Shouldn't using `now` to define a constant variable fail at compile time?

### ISSUE THREAD

**Issue by maraoz** [ethereum/solidity#1441]
Doing this:
```
uint public constant expiration = now + 10 days;
```
works and makes `expiration == 10 days`. This was confusing to me. Would it be better if `solc` failed and said something like "Can't use `now` to define constant variable"?.

**Comment by VoR0220** [comment]
No because at run time is when `now` would be defined.

**Comment by maraoz** [comment]
Aren't `constant` variables defined at compile time?

**Comment by VoR0220** [comment]
not currently...currently they are not enforced by the compiler (there's an issue discussing what to do with `constant` in the future [here](https://github.com/ethereum/solidity/issues/992))

**Comment by maraoz** [comment]
Oh my! Thanks @VoR0220

**Comment by chriseth** [comment]
This is being fixed by #1729
