### ISSUE TITLE
Allow Custom Errors inheritance

### ISSUE THREAD

**Issue by ernestognw** [ethereum/solidity#14418]
## Abstract

Currently, there's no way of doing error inheritance, this proposal would allow users to define an error extending from another in something similar to the following format:

```solidity
// .selector == bytes4(keccak256("InsufficientBalance(uint256)"))
error InsufficientBalance(uint256 value)

// .selector == bytes4(keccak256("ERC20InsufficientBalance(uint256),InsufficientBalance(uint256)"))
error ERC20InsufficientBalance(uint256 value) is InsufficientBalance(value)
```

## Motivation

There's already some interest in standardized custom errors as seen in [the EIP-6093 discussions](https://ethereum-magicians.org/t/eip-6093-custom-errors-for-commonly-used-tokens/12043/17), and having a way of inheriting from these standard errors would allow some business logic customization 

## Specification

A custom error should be allowed to extend from another similarly to the way contracts are extended:

```solidity
// Contract definition
contract Test { ... }
contract TestExtended is Test { ... }

// Constructor
constructor(uint256 value) {}
constructor(uint256 value, uint256 another value) Test(value) {}

// Errors
error InsufficientBalance(uint256 value)
error ERC20InsufficientBalance(uint256 value) is InsufficientBalance(value)
```

When an error is single (doesn't inherit), the selector remains the same, but for inheriting errors the selector can be computed by the first 4 bytes of the keccak256 of the error names comma separated following the same inheritance order as in contracts inheritance.

```solidity
// From an original selector, selector remains
// bytes4(keccak256("InsufficientBalance(uint256)"))
// And for a child, the string follows the C3 linearization algorithm
// bytes4(keccak256("ERC20InsufficientBalance(uint256),InsufficientBalance(uint256)"))
```

Alternatively, the inherited selectors can be ordered in the same way as error names and put in memory before the rest of the arguments so the origin of the error can be traced to a specific contract. This way extending from standard errors without losing the selector would be possible.

## Backwards Compatibility

Not breaking

**Comment by haythemsellami** [comment]
Curious what's the use case of this?

**Comment by ernestognw** [comment]
I have 2 use cases in my mind

1. It allows users to extend from standard errors without losing contextual information. 

For example, in [EIP-6093](https://eips.ethereum.org/EIPS/eip-6093), there has been interest in more specific errors without redefining the error or breaking the standard. It will similarly benefit users of OpenZeppelin contracts who extend a contract behavior but some errors don't fit into their added business logic. 

We can also have error libraries for generic errors. We tried this approach in [this PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4261) but decided that the errors library was not expressive at all and custom errors that are too generic might confuse.

2. The selector trace I'm proposing would be a security feature, it would allow for keeping the error interface consistent with the standards even after extending from an error. I consider this an important addition because error selector decoding is [already suggested](https://dev.to/george_k/embracing-custom-errors-in-solidity-55p8) by the community and it's another interface to maintain. Note that an ERC165 version for error interfaces would likely help but I'm not a fan of that approach.

EDIT: Now that I read myself I think this issue is more about extending without losing the selector rather than allowing inheritance on itself

**Comment by AdrianKoch3010** [comment]
This would be great actually, as currently my code looks like this:

`error ERR_NOT_ENOUGH_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );

    error ERR_NOT_ENOUGH_CASHBACK_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );
    
    error ERR_NOT_ENOUGH_PENDING_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );`

**Comment by AdrianKoch3010** [comment]
This would be great actually, as currently my code looks like this:

```solidity
    error ERR_NOT_ENOUGH_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );

    error ERR_NOT_ENOUGH_CASHBACK_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );
    
    error ERR_NOT_ENOUGH_PENDING_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );
```
Which, with custom error inheritance, would just be:

```solidity
    error ERR_NOT_ENOUGH_BALANCE (
        address account,
        uint256 available,
        uint256 needed
    );

    error ERR_NOT_ENOUGH_CASHBACK_BALANCE  is ERR_NOT_ENOUGH_BALANCE  ( );
    
    error ERR_NOT_ENOUGH_PENDING_BALANCE ( );
```

Obviously, one could include the error type as string or eum, but its not as clean
