### ISSUE TITLE
Release 0.8.21

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14419]
### Pre-flight checks
At least a day before the release:
 - [x] Run ``make linkcheck`` from within ``docs/`` and fix any broken links it finds.
       Ignore false positives caused by ``href`` anchors and dummy links not meant to work.
 - [x] Double-check that [the most recent docs builds at readthedocs](https://readthedocs.org/projects/solidity/builds/) succeeded.
 - [x] Make sure that all merged PRs that should have changelog entries do have them.
 - [x] Rerun CI on the top commits of main branches in all repositories that do not have daily activity by creating a test branch or PR
      - [x] ``solc-js`` [Pass](https://app.circleci.com/pipelines/github/ethereum/solc-js/1346/workflows/69b9c10a-0244-4d4b-8174-f33b9bc2586d)
      - [ ] ~``solc-bin`` (make sure the bytecode comparison check did run)~ Skipped
      - [ ] ~``homebrew-ethereum``~ Skipped
 - [ ] (Optional) Create a prerelease in our Ubuntu PPA by following the steps in the PPA section below on ``develop`` rather than on a tag.
       This is recommended especially when dealing with PPA for the first time, when we add a new Ubuntu version or when the PPA scripts were modified in this release cycle.
 - [x] Verify that the release tarball of ``solc-js`` works.
       Bump version locally, add ``soljson.js`` from CI, build it, compare the file structure with the previous version, install it locally and try to use it.

### Drafts
At least a day before the release:
 - [x] Create a draft PR to sort the changelog.
   - [x] https://github.com/ethereum/solidity/pull/14422
 - [x] Create draft PRs to bump version in ``solidity`` and ``solc-js``.
   - [x] https://github.com/ethereum/solc-js/pull/703
   - [x]  https://github.com/ethereum/solidity/pull/14423
 - [x] Create a draft of the release on github.
 - [ ] Create a draft PR to update soliditylang.org.
 - [x] Create drafts of blog posts.
 - [ ] Prepare drafts of Twitter, Reddit and Solidity Forum announcements.

### Blog Post
 - [ ] Create a post on [solidity-blog](https://github.com/ethereum/solidity-blog) in the ``Releases`` category and explain some of the new features or concepts.
 - [x] Create a post on [solidity-blog](https://github.com/ethereum/solidity-blog) in the ``Security Alerts`` category in case of important bug(s).

### Changelog
 - [x] Sort the changelog entries alphabetically and correct any errors you notice. Commit it.
 - [x] Update the changelog to include a release date.
 - [x] Run ``scripts/update_bugs_by_version.py`` to regenerate ``bugs_by_version.json`` from the changelog and ``bugs.json``.
       Make sure that the resulting ``bugs_by_version.json`` has a new, empty entry for the new version.
 - [x] Commit changes, create a pull request and wait for the tests. Then merge it.
   - [x] https://github.com/ethereum/solidity/pull/14427
 - [x] Copy the changelog into the release blog post.

### Create the Release
 - [x] Create a [release on GitHub](https://github.com/ethereum/solidity/releases/new).
       Set the target to the ``develop`` branch and the tag to the new version, e.g. ``v0.8.5``.
       Include the following warning: ``**The release is still in progress and the binaries may not yet be available from all sources.**``.
       Do not publish it yet - click the ``Save draft`` button instead.
 - [x] Thank voluntary contributors in the GitHub release notes.
       Use ``scripts/list_contributors.sh v<previous version>`` to get initial list of names.
       Remove different variants of the same name manually before using the output.
 - [x] Check that all tests on the latest commit in ``develop`` are green.
 - [x] Click the ``Publish release`` button on the release page, creating the tag.
 - [x] Wait for the CI runs on the tag itself.

### Upload Release Artifacts and Publish Binaries
 - [x] Switch to the tag that archives have to be created for.
 - [x] Create the ``prerelease.txt`` file: (``echo -n > prerelease.txt``).
 - [x] Run ``scripts/create_source_tarball.sh`` while being on the tag to create the source tarball. This will create the tarball in a directory called ``upload``.
 - [x] Take the tarball from the upload directory (its name should be ``solidity_x.x.x.tar.gz``, otherwise ``prerelease.txt`` was missing in the step before) and upload the source tarball to the release page.
 - [x] Take the ``github-binaries.tar`` tarball from ``c_release_binaries`` run of the tagged commit in circle-ci and add all binaries from it to the release page.
       Make sure it contains four binaries: ``solc-windows.exe``, ``solc-macos``, ``solc-static-linux`` and ``soljson.js``.
 - [x] Take the ``solc-bin-binaries.tar`` tarball from ``c_release_binaries`` run of the tagged commit in circle-ci and add all binaries from it to solc-bin.
 - [x] Run ``npm run update -- --reuse-hashes`` in ``solc-bin`` and verify that the script has updated ``list.js``, ``list.txt`` and ``list.json`` files correctly and that symlinks to the new release have been added in ``solc-bin/wasm/`` and ``solc-bin/emscripten-wasm32/``.
 - [x] Create a pull request in solc-bin and merge.

### Homebrew and MacOS
 - [x] Update the version and the hash (``sha256sum solidity_$VERSION.tar.gz``) in the [``solidity`` formula in Homebrew core repository](https://github.com/Homebrew/homebrew-core/blob/master/Formula/solidity.rb).
   - [x] https://github.com/Homebrew/homebrew-core/pull/137008
 - [x] Update the version and the hash (``sha256sum solidity_$VERSION.tar.gz``) in [our custom ``solidity`` Homebrew formula](https://github.com/ethereum/homebrew-ethereum/blob/master/solidity.rb).
   - [x] https://github.com/ethereum/homebrew-ethereum/pull/325 

### Docker
 - [x] Run ``./scripts/docker_deploy_manual.sh v$VERSION``.
     - [`0.8.21`](https://hub.docker.com/layers/ethereum/solc/0.8.21/images/sha256-b202f06c06631c1139e36465d80709cfdc8ec1bf9e405bb73ec512ffe90ccf80)
     - [`0.8.21-alpine`](https://hub.docker.com/layers/ethereum/solc/0.8.21-alpine/images/sha256-4ca6e60fd07f6e622755335131c94a36a41728e27942e38bfc5abb78ddb1fa8b)

### PPA
 - [x] Create ``.release_ppa_auth`` at the root of your local Solidity checkout and set ``LAUNCHPAD_EMAIL`` and ``LAUNCHPAD_KEYID`` to your key's email and key id.
 - [x] Double-check that the ``DISTRIBUTIONS`` list in ``scripts/release_ppa.sh`` and ``scripts/deps-ppa/static_z3.sh`` contains the most recent versions of Ubuntu.
 - [x] Make sure the [``~ethereum/cpp-build-deps`` PPA repository](https://launchpad.net/~ethereum/+archive/ubuntu/cpp-build-deps) contains ``libz3-static-dev builds`` for all current versions of Ubuntu.
       Note that it may be included in the ``z3-static`` multipackage (follow the ``View package details`` link to check).
       If not present, run ``scripts/deps-ppa/static_z3.sh`` and wait for the builds to succeed before continuing.
 - [x] Run ``scripts/release_ppa.sh v$VERSION`` to create the PPA release.
       This will create a single package containing static binary for older Ubuntu versions in the [``~ethereum/ethereum-static`` PPA](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum-static)
       and separate packages with dynamically-linked binaries for recent versions (those listed in ``DISTRIBUTIONS``) in the [``~ethereum/ethereum`` PPA](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum).
 - [x] Wait for the build to be finished and published for *all architectures* (currently we only build for ``amd64``, but we may add ``arm`` in the future).
       **SERIOUSLY: DO NOT PROCEED EARLIER!!!**
    - [x] [static binary](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum-static/+sourcepub/15028715/+listing-archive-extra)
    - [x] focal
    - [x] jammy
    - [x] kinetic
    - [x] lunar
 - [x] *After* the package with the static build is *published*, use it to create packages for older Ubuntu versions.
       Copy the static package to the [``~ethereum/ethereum`` PPA](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum)
       for the destination series ``Trusty``, ``Xenial`` and ``Bionic`` while selecting ``Copy existing binaries``.

### Release solc-js
 - [x] Wait until solc-bin was properly deployed. You can test this via remix - a test run through remix is advisable anyway.
 - [x] Increment the version number, create a pull request for that, merge it after tests succeeded.
 - [x] Run ``npm run build:tarball`` in the updated ``solc-js`` repository to create ``solc-<version>.tgz``. Inspect the tarball to ensure that it contains an up to date compiler binary.
 - [x] Run ``npm run publish:tarball`` to publish the newly created tarball.
 - [x] Create a tag using ``git tag --annotate v$VERSION`` and push it with ``git push --tags``.

### Post-release
 - [x] Make sure the documentation for the new release has been published successfully.
       Go to the [documentation status page at ReadTheDocs](https://readthedocs.org/projects/solidity/) and verify that the new version is listed, works and is marked as default.
 - [x] Remove "still in progress" warning from the [release notes](https://github.com/ethereum/solidity/releases).
 - [x] Merge the [blog posts](https://github.com/ethereum/solidity-blog/pulls) related to the release.
 - [x] Create a commit to increase the version number on ``develop`` in ``CMakeLists.txt`` and add a new skeleton changelog entry.
   - [x] https://github.com/ethereum/solidity/pull/14423
 - [x] Update the release information section [in the source of soliditylang.org](https://github.com/ethereum/solidity-portal/blob/master/index.html).
 - [x] Announce on [Twitter](https://twitter.com/solidity_lang), including links to the release and the blog post.
 - [x] Announce on [Fosstodon](https://fosstodon.org/@solidity/), including links to the release and the blog post.
 - [x] Share the announcement on Reddit in [``/r/ethdev``](https://reddit.com/r/ethdev/), cross-posted to [``/r/ethereum``](https://reddit.com/r/ethereum/).
 - [x] Share the announcement on the [Solidity forum](https://forum.soliditylang.org) in the ``Announcements`` category.
 - [x] Share the announcement on [Project Updates](https://discord.com/channels/420394352083337236/798974456704925696)
 - [x] Share the announcement on [`#solidity` channel on Matrix](https://matrix.to/#/#ethereum_solidity:gitter.im)
 - [x] Share the announcement on [`#solc-tooling`](https://matrix.to/#/#solc-tooling:matrix.org)
 - [x] Lean back, wait for bug reports and repeat from step 1 :).

**Comment by cameel** [comment]
Missing changelog entries for:
- https://github.com/ethereum/solidity/pull/14377
- https://github.com/ethereum/solidity/pull/14276

Pinging @blishko.

**Comment by cameel** [comment]
All the non-comm stuff is done so handing off to @NunoFilipeSantos and @franzihei.

**Comment by NunoFilipeSantos** [comment]
Thank you!

**Comment by NunoFilipeSantos** [comment]
Done.
