### ISSUE TITLE
Modulus Operations Return Negative Values

### ISSUE THREAD

**Issue by alphak3y** [ethereum/solidity#14415]
## Description

Whenever you do a modulus operation on a negative number it returns a negative value.

Example: `(-5) % 10 == -5` will return `true`.

## Environment

N/A

## Steps to Reproduce

See Description.

**Comment by cameel** [comment]
Yes, it's not a bug though. It's a design choice, documented here: [modulo](https://docs.soliditylang.org/en/latest/types.html#modulo).

Unfortunately, there's more than one valid way to define the `%` operator and it's not uniform across different languages: https://en.wikipedia.org/wiki/Modulo#In_programming_languages
