### ISSUE TITLE
Logo and other images are not loading in Internals section 

### ISSUE THREAD

**Issue by allwin199** [ethereum/solidity#14435]
## Page

https://docs.soliditylang.org/en/latest/internals/layout_in_storage.html

## Abstract

The logo and theme change icon is not loaded.
URL looks a bit different in `Internals` comparing it to other sections.

**Comment by Najamulhassan3383** [comment]
@worksofallwin Hi, I am new to open Source. Can you plz provide a bit more detail about the issue and where do i have to make changes. It would be really helpful. Thanks.

I found these urls for the logos in internals
https://docs.soliditylang.org/en/latest/internals/_static/img/moon.svg
https://docs.soliditylang.org/en/latest/internals/_static/img/logo.svg

but in others it is this
https://docs.soliditylang.org/en/latest/_static/img/logo.svg

**Comment by allwin199** [comment]
Hey, I have reported this issue. Someone from the Ethereum team will review this issue and after that, they will plan when to fix it. 

If they labeled this as `good-first-issue`, then you can ask the author to assign it to you and they will provide more details on how to fix this issue.

**Comment by Najamulhassan3383** [comment]
@worksofallwin thanks

**Comment by NunoFilipeSantos** [comment]
@wackerow can you take a look?

**Comment by cameel** [comment]
I think it's because these images are linked using relative URLs. The pages under "Internals" are not directly at the root, so the URL must be wrong there.

**Comment by wackerow** [comment]
Happy to take a look at this, will add to my list (feel free to assign me) 🙂

**Comment by wackerow** [comment]
@cameel Yeah this is what I'm seeing...

These images are located in the `docs.soliditylang.org/lang/version/_static/img/filename.ext` path, but referenced using a relative path of just `_static/img/filename.ext`. 

The bug appears to be for any page that is nested further, so the relative path is checking in `/lang/version/sub-folder/_static/img/filename.ext` which doesn't exist.

We should prepend the active location `https://docs.soliditylang.org/en/_version_/` to the image paths... this will allow it to still reference the active version. Will put up a patch for this.
