### ISSUE TITLE
[Docs] PDF shows incorrect version

### ISSUE THREAD

**Issue by raxhvl** [ethereum/solidity#14432]
## Page
https://docs.soliditylang.org/_/downloads/en/latest/pdf/

## Abstract
The PDF documentation displays version `0.8.22`, which differs from the expected version `0.8.21` listed in the latest release.

![Screenshot](https://github.com/ethereum/solidity/assets/10168946/5423ffaa-31b3-4a5c-809f-97b34bd78b98)

I'm unsure where to fix this, but I'm happy to work on this. Should be quick fix I suppose.

**Comment by cameel** [comment]
Version is correct. You're looking at `latest`, which is the docs built from the latest code snapshot from `develop` branch, which contains changes that will eventually go into 0.8.22. If you want docs for the latest release, you should use [`stable`](https://docs.soliditylang.org/_/downloads/en/stable/pdf/) or [`v0.8.21`](https://docs.soliditylang.org/_/downloads/en/v0.8.21/pdf/).

**Comment by raxhvl** [comment]
That makes sense @cameel ! At the time of this issue, the website was pointing to `latest` instead of `stable` which now has been fixed!
