### ISSUE TITLE
ICE during Natspec generation when emitting an event from a foreign contract or interface

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#14430]
I moves the OZ contract repo to 0.8.21 to benefit from the new language features, but I'm getting the following error:

```
Internal exception in StandardCompiler::compile: /solidity/libsolidity/interface/Natspec.cpp(85): Throw in function static Json::Value solidity::frontend::Natspec::userDocumentation(const solidity::frontend::ContractDefinition&)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```

## Environment

- Compiler version: 0.8.21
- Target EVM version (as per compiler settings): shanghai
- Framework/IDE (e.g. Truffle or Remix): hardhat
- EVM execution environment / backend / blockchain client: hardhat node
- Operating system: linux

## Steps to Reproduce

Minimal example:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.21;

interface I {
    event E();
}

library L {
    function f() internal {
        emit I.E();
    }
}

contract C {
    function g() public {
        L.f();
    }
}
```

**Comment by Amxx** [comment]
The issue is caused by the changes to events in `contracts/proxy/ERC1967/ERC1967Utils`.

If I comment the following lines
```solidity
emit IERC1967.Upgraded(newImplementation);
...
emit IERC1967.AdminChanged(getAdmin(), newAdmin);
...
emit IERC1967.BeaconUpgraded(newBeacon);
```

compilation works fine.

**Comment by Amxx** [comment]
This is the assert that fails:
```cpp
solAssert(
	*eventOrigin == _contractDef ||
	(!eventOrigin->isLibrary() && _contractDef.derivesFrom(*eventOrigin)) ||
	(eventOrigin->isLibrary() && !_contractDef.derivesFrom(*eventOrigin))
);
```
In my case the event is declared in an interface and used (emited) by a library. Please don't tell me that is not supported ...

**Comment by blitz-1306** [comment]
This happends when using WASM and linux-native compilers.

**Comment by blitz-1306** [comment]
@Amxx It is not only libraries. I get the same error with even more minimalistic example:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.21;

contract X {
    event E();
}

contract C {
    function g() public {
        emit X.E();
    }
}
```
Results:
```
Internal exception in StandardCompiler::compile: /solidity/libsolidity/interface/Natspec.cpp(89): Throw in function static Json::Value solidity::frontend::Natspec::userDocumentation(const ContractDefinition &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```
It seems to happen when event is referenced with qualifier.

**Comment by nikola-matic** [comment]
> This is the assert that fails:
> 
> ```c++
> solAssert(
> 	*eventOrigin == _contractDef ||
> 	(!eventOrigin->isLibrary() && _contractDef.derivesFrom(*eventOrigin)) ||
> 	(eventOrigin->isLibrary() && !_contractDef.derivesFrom(*eventOrigin))
> );
> ```
> 
> In my case the event is declared in an interface and used (emited) by a library. Please don't tell me that is not supported ...

Heya, so obviously, the compiler throwing an ICE is generally going to be considered a bug - however, the snippets that both you and @blitz-1306 posted do compile without throwing an ICE. Also, looking at the ICE, it's thrown in Natspec, and I can reproduce it by requesting user docs, i.e. `solc --userdoc test.sol`, so it's more of a Natspec bug than an event bug by the looks of it.

In any case, fix is on the way.

edit: same issue is present when requesting `--devdoc`, due to the same failing assertion.

**Comment by pcaversaccio** [comment]
You claim that compilation works fine but I'm having a hard time making a contract compile (without `userdoc` or `devdoc`), however; let's take the following contract (`Test.sol`):

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.21;

contract X {
    event E();
}

contract C {
    function g() public {
        emit X.E();
    }
}
```

Now invoking something like `solc --asm .\Test.sol` (not requesting `userdoc` nor `devdoc`), will still throw:

```console
Internal compiler error:
C:\Users\circleci\project\libsolidity\interface\Natspec.cpp(89): Throw in function class Json::Value __cdecl solidity::frontend::Natspec::userDocumentation(const class solidity::frontend::ContractDefinition &)
Dynamic exception type: struct boost::wrapexcept<struct solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[struct solidity::util::tag_comment * __ptr64] = Solidity assertion failed
```

Can you elaborate on what am doing wrong? The version I used is the Windows one `0.8.21+commit.d9974bed.Windows.msvc` but I get the similar behaviour on Ubuntu & Debian.

**Comment by pcaversaccio** [comment]
Cross-posting the [answer](https://github.com/pcaversaccio/snekmate/issues/148#issuecomment-1647402110) by @nikola-matic here for clarity:

> In that case nothing - essentially, any steps that require userdoc or devdoc (asm, metadata, etc.) will indeed fail - I was just commenting in case you just read the issue and didn't try to compile anything. I guess you'll have to wait for the 0.8.22 release like most everyone else :)
