### ISSUE TITLE
Style guide: define the contract layout

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1444]
Follow up of #1394:

> where to place modifiers, events, state variables? Probably we need a new section for "contract layout".

**Comment by ChrisChinchilla** [comment]
@axic Looking through _style-guide.rst_ I think this is all done? I can see sections for each of the items in your comment above.

**Comment by chriseth** [comment]
Actually the components are all there, but it does not state which oder they should be in.

I guess it should be:

import statements

interfaces

libraries

contracts

inside contracts / libraries / interfaces: type declarations first, then state variables, then events, then functions. It might make sense to declare types close to their use in events or state variables though.
