### ISSUE TITLE
Custom Errors support in `require`

### ISSUE THREAD

**Issue by SteMak** [ethereum/solidity#14442]
## Abstract

Since Gas-efficient Custom Errors were added in `solidity 0.8.4`, the `require` statement has become mostly unused. The `if (!condition) revert CustomError()` pattern sometimes looks branchy and makes requirement understanding somewhat harder.
```js
require(min <= value && value <= max, "Value not within bounds");
// comparing to
if (min > value || value > max) revert NotWithinBounds(min, max, value);
```

I found a [workaround](https://github.com/SteMak/solidity_ensure), however, it consumes some more Gas compared to ordinary Custom Errors usage.

## Motivation

I propose implementing Custom Errors support for the `require` statement, providing Custom Error as the second parameter instead of an error message.
```js
error NotWithinBounds(uint256 min, uint256 max, uint256 actual);

function checkBounds(uint256 min, uint256 max, uint256 value) external pure {
  require(min <= value && value <= max, NotWithinBounds(min, max, value));
}
```

## Specification

There are several opportunities:
- Make error an ordinary type lazy loads on `revert` burning
  ```js
  // Bytes error message is not calculated there
  require(condition, CustomError(params));

  function require(bool condition, error err) pure {
    if (!condition) revert err; // Bytes error message is generated here
  }
  ```
- Implement inline functions #12297
  ```js
  require(condition, () => revert CustomError(params));

  function require(bool condition, function() pure handler) pure {
    if (!condition) handler();
  }
  ```
- Make the transformation below in compile time
  ```js
  require(condition, CustomError(params));
  // changed to
  if (!condition) revert CustomError(params);
  ```

## Backwards Compatibility

As Solidity allows function overloading, the creation of `require(bool, error, or other suitable type)` should not break backward compatibility.

**Comment by agnxsh** [comment]
can i take this issue please?

**Comment by fulldecent** [comment]
I fully support this issue because it increases clarity and expressiveness of the language.

It matches "guards" that other languages have. And a great programming pattern is to put all your guards at the top of a function.

Recognizing that this issue is now labeled as "must have" I have added at to the documentation at https://github.com/ethereum/solidity/pull/14539

**Comment by 0xCardiE** [comment]
Please lets have it. 
"If pattern" is really suboptimal.

**Comment by luislucena16** [comment]
this could be a great implementation for `0.8.26`, taking advantage of the arrival of the `0.8.25` fork!!
I will be following this issue!

**Comment by wadealexc** [comment]
Bumping this -- we really need this feature!

The readability using custom error types is really bad - requiring branching statements for every check really clutters up the code. So we're still using `require` with error strings - but error strings are inflating our deployment bytecode!

It would be so awesome to be able to use `require` with custom errors!
