### ISSUE TITLE
SMTChecker: Loop is unrolled after it completes

### ISSUE THREAD

**Issue by pgebal** [ethereum/solidity#14447]
## Description

For some cases model checker unrolls a loop even after it should complete.

## Environment

- Compiler version: commit 83fe3d4011e3d14385f83aef0c32a0d894273501

## Steps to Reproduce
run compiler with `--model-checker-engine bmc --model-checker-bmc-loop-iterations 5 --model-checker-solvers z3` on the following contract:
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.0;
contract C
{
	uint x;
	uint y;

	function condition() private returns(bool) {
		x = (x + 1) % 2;
		return (x == 1);
	}

	function f() public {
		require(x == 0);
		require(y == 0);
		for (; condition();) {
			++y;
		}
		assert(y == 1);
	}
}
```
I expect the assertion `y == 1` to hold but it fails, `y > 1` holds and it shouldn't.
There is a similar bug in `while` and `do while` loops.

**Comment by agnxsh** [comment]
hi can anyone assign me this? I can look into it!

**Comment by pgebal** [comment]
> hi can anyone assign me this? I can look into it!

Hi @agnxsh. There is already a PR fixing this: https://github.com/ethereum/solidity/pull/14448

**Comment by agnxsh** [comment]
sure
