### ISSUE TITLE
Add PRs to Release Notes

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#14440]
It would be very valuable to the people who are interested in the details to add the relevant PRs to each bullet point of the release notes going forward. I was going through the `0.8.21` release notes yesterday and I wanted to specifically understand the scope of "Relax restrictions on initialization of immutable variables.". I had to search in the repo for the specific PR, but doing this for multiple bullet points will be very time-consuming.

**Comment by NunoFilipeSantos** [comment]
We did have an example in the [release announcement](https://soliditylang.org/blog/2023/07/19/solidity-0.8.21-release-announcement).

**Comment by pcaversaccio** [comment]
I'm sorry but I strongly disagree with this decision. You make everyone's life more difficult in an environment where transparency is key. Very very disappointing...

**Comment by NunoFilipeSantos** [comment]
I'm sorry you feel that way. However, this is not a priority for us.
