### ISSUE TITLE
Yul sources are given id 1 instead of 0 in compiler output (inconsistent with source map & ast)

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#14453]
## Description

In the `sources` output in Yul mode (when present), the ID of each source is given as `1`, instead of `0`.  This is inconsistent with Solidity's general practice of 0-indexing sources.  Worse yet, it's inconsistent with the numbering elsewhere in the output, namely, the source map and the AST; both of these will give the ID as `0`.

## Environment

- Compiler version: 0.8.21
- Target EVM version (as per compiler settings): default

## Steps to Reproduce

Any Yul source code will do, just make sure to request ASTs in the output (about which see #14452) so that you get `sources` output.  Also good idea to request the source map as well for comparison.

**Comment by r0qs** [comment]
Hi @haltman-at, thank you very much! Indeed the IDs are inconsistent. The wrong ID was added here: https://github.com/ethereum/solidity/pull/14177/files#diff-ad23dac446ab50b79251aacbae1a5230bacd344588c52241eca0f0b1d815e8acR1528.

I opened a PR to fix it :)

**Comment by cameel** [comment]
Yes, just like #14452 this is just an oversight from #14177. The IDs are arbitrary, but if they don't match numbers in the AST or source map, it's a bug. And there's no reason for it not to start at 0.
