### ISSUE TITLE
Enable "safe" call a function on arbitrary address.

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#14467]
## Abstract

Fix the try catch pattern.

## Motivation

There are many ways to perform an evm call and decode the result:

#### simple call
```solidity
address owner = IERC5313(target).owner()
// do stuff with owner
```

#### try catch
```solidity
try IERC5313(target).owner() returns (address owner) {
    // do stuff with owner
} catch {
    // process error
}
```

#### low level call
```solidity
(bool success, bytes memory returndata) = target.staticcall(abi.encodeCall(IERC5313.owner, ()));
if (success & returndata.length >= 0x20) {
    address owner = abi.decode(returndata, (address));
    // do stuff with owner
} else {
    // process error
}
```

**None of them is safe to call, is you want to make sure that the operation does not revert and that errors can be catched properly!**

- Simple call will revert is anything wrong happens, that is ok.
- Try catch will revert if
  - the target has no code: that is something we can check before doing the try catch. Its a bit painfull, but its ok
  - the target does not revert, but the returned data are not long enough for doing `abi.decode`. This is bad
- Low level call doesn't limit the return data, and is vulnerable to the "returnbomb" attack.

Said otherwize, if I want to look for an `owner()` in a way that will never revert, regardless of the target address, I have no choice but to go heavily into assembly. That is a simple usecase that solidity does not cover.

## Specification

There are multiple possible solutions:
- change the "try catch" behavior so that "not enough return data for decode" can be catched.

- change the `call` and `staticcall` operation by adding a new parameter that is the maximum return data, so that the return bomb is contained.
```solidity
target.staticcall{returnsize: 0x20}(abi.encodeCall(IERC5313.owner, ()));
```

## Backwards Compatibility

TBD

**Comment by frangio** [comment]
+1 to this idea:

```solidity
target.staticcall{returnsize: 0x20}(abi.encodeCall(IERC5313.owner, ()));
```

Attempt to specify it fully:
- Add a `returnsize` named parameter to all `*call` functions
- Emit the corresponding call opcode with 0 for output size parameter (no change here)
- Allocate the `bytes memory` array length to the minimum of the `returnsize` parameter and actual `returndatasize()`
- Emit `returndatacopy` for that amount of bytes

**Comment by Amxx** [comment]
this is still relevant

**Comment by mehtavishwa30** [comment]
Thanks for your proposal, @Amxx. As we get more inputs on `try`/`catch` improvements of similar nature, we intend to focus these discussions on [our call for feedback on the Solidity forum](https://forum.soliditylang.org/t/call-for-feedback-the-future-of-try-catch-in-solidity/1497). This post details the current state of the `try`/`catch` syntax and aims to collect feedback regarding the evolution of this feature in the future.

Additionally, your suggestion to fix the `try`/`catch` pattern (revert from decoding when return data is too short) is covered by a few other open issues listed below:
- #11886
- #13869
- #12725

Considering the overlap with other open issues, we will be closing this issue and encourage you to participate or keep an eye out for the developments in the [forum discussion](https://forum.soliditylang.org/t/call-for-feedback-the-future-of-try-catch-in-solidity/1497).
