### ISSUE TITLE
Deprecation warning for old EVM versions (< constantinople)

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#14475]
Prepare https://github.com/ethereum/solidity/issues/12246 by means of a warning.
Additionally to a compiler-warning, we should announce this as a plan before releasing it.

**Comment by cameel** [comment]
It looks like `petersburg` in terms of compiler features is identical with `constantinople` (#6086). I think it would make more sense to either deprecate both or keep both. If we keep one, we won't really be able to drop any code related to the other.

**Comment by ekpyron** [comment]
See https://github.com/ethereum/solidity/pull/14591/files#r1350395818 - I adjusted the title here to keep constantinople support around as non-deprecated for now.
