### ISSUE TITLE
Add a flag to disable the default import callback

### ISSUE THREAD

**Issue by fvictorio** [ethereum/solidity#14484]
## Abstract

Add a mechanism to disable the default import callback when using the native binary.

## Motivation

The native binary defaults to the Host Filesystem Loader, meaning that JSON inputs that are not self-contained can still compile fine. This is a problem for Hardhat because we want to get an error in those cases.

There is a workaround: creating an empty temporary directory and using it with `--base-path`. But having a specific flag like `--no-import-callback` would be much better.

## Specification

Add a `--no-import-callback` to the solc binary that disables any default import callback.

## Backwards Compatibility

This is a new flag so there shouldn't be backwards compatibility issues.

**Comment by fvictorio** [comment]
After reading the [Import Path Resolution docs](https://docs.soliditylang.org/en/v0.8.21/path-resolution.html), I understand better why the Host Filesystem Loader is used by default in the solc's binary: it is a design decision for the use case where someone compiles Solidity files from the command line using the `solc` binary directly.

But I think it's fair to say that most users don't do that. Instead, they use the solc binary indirectly when they compile with Hardhat or Foundry, where I think this flag will be used for every compilation once it's available.

**Comment by virusbug07** [comment]
Hey i would like to work on this issue

**Comment by vvarl0cks** [comment]
hello, i would like to work on this, can you assign me. thanks.
