### ISSUE TITLE
Modifiers with named parameters

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#14483]
## Abstract

Add support for calling modifiers with named parameters.

## Motivation

I can call functions, events, and errors using named parameters, but it's not yet possible to use named parameters in modifiers. Being explicit in the modifiers can provide a big value-add as well.

## Specification

```solidity
modifier guard(bytes32 salt) {
    ...
    _;
}

function fn(bytes32 x) public guard({salt: x}) returns (address) {
    ...
}
```

## Backwards Compatibility

This is a new feature that is not backward-compatible.

**Comment by r0qs** [comment]
Thanks @pcaversaccio, but there is already an open issue to track this feature, see: https://github.com/ethereum/solidity/issues/14466
So I will be closing this one :)
