### ISSUE TITLE
Bug: `solc --ir` includes uncommented string resulting in parsing failure

### ISSUE THREAD

**Issue by sambacha** [ethereum/solidity#14486]
Using latest solc on apple arm64

```bash
solc --ir $CONTRACTNAME
```

```console
$ solc --strict-assembly ir_output
Error: Expected keyword "object".
 --> ir_output:1:1:
  |
1 | IR:
  | ^^
```

Editing the file to comment out the line `IR` results in successful compilation 

```console
$ solc --strict-assembly ir_output

======= ir_output (EVM) =======

Pretty printed source:
```
> truncated success

**Comment by nidhi-singh02** [comment]
Could you mention the solc version that you are using to replicate this ? I could have a look.

**Comment by mehtavishwa30** [comment]
Hey @sambacha! This isn't a bug as the CLI does not produce outputs that are being machine parsed. If you wish to produce machine readable output, you can check out the Standard JSON Interface.

Is there a specific reason why you would like to do so?
