### ISSUE TITLE
The solidity icon is not display 

### ISSUE THREAD

**Issue by AnuragNishad12** [ethereum/solidity#14498]
<img width="272" alt="image" src="https://github.com/ethereum/solidity/assets/124987038/9a7d301e-56c2-4cdb-9cbb-e30aa6ad18d8">

**Comment by kuzdogan** [comment]
Works for me

**Comment by cameel** [comment]
It was already reported and fixed in #14435. Unfortunately the fix is only applied in newly rendered docs. So it will stay that way for v0.8.21, but v0.8.22 won't have that issue.
