### ISSUE TITLE
Issue with source map offset ("s")

### ISSUE THREAD

**Issue by AntoineMrtl** [ethereum/solidity#14523]
## Description

There might be an issue concerning source map with solc compiler : at some point, the source map no longer point to valid instruction, at the beginning it's correct but then It's cutted in half, I tried also with remix and it's the same. The source map length it's the same as the opcodes length so I don't think I'm misinterpreting and the weirdest is that at the end, the first element of the source map ("s"), the offset is outside my file total number of character, like I have not even 700 characters in my files and it tell me an instruction start from 2120 ...

## Environment

- Compiler version: solc@0.8.21
- Target EVM version (as per compiler settings): default 
- Framework/IDE (e.g. Truffle or Remix): Remix
- Operating system: Windows

## Steps to Reproduce

Copy this code in remix :

```solidity
pragma solidity ^0.8.0;

contract TestContract {
    address public constant deadAddress = address(0xdead);

    mapping(address => bool) private _isExcludedFromFees;
    mapping(address => bool) public _isExcludedMaxTradingAmount;

    uint256 public maxTradingAmount;
    uint256 public swapTokensAtAmount;
    uint256 public maxWallet;

    constructor() {
        uint256 totalSupply = 10_000_000 * 1e18;

        swapTokensAtAmount = (totalSupply * 100) / 10000;
        maxTradingAmount = (totalSupply * 100) / 10000;
        maxWallet = (totalSupply * 100) / 10000;
    }

    receive() external payable {}

    function test() external {
        uint aaaa = 543646;
        uint bbbb = 11324;
    }
}

```

Compile, see compilation detail, go to runtime Bytecode, and then see "sourceMap".

The source map ("25:683:0:-:0;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;53:53;;;;;;;;;;;;;:::i;:::-;;;;;;;:::i;:::-;;;;;;;;237:31;;;;;;;;;;;;;:::i;:::-;;;;;;;:::i;:::-;;;;;;;;171:59;;;;;;;;;;;;;;;;;;;;;;;:::i;:::-;;:::i;:::-;;;;;;;:::i;:::-;;;;;;;;274:33;;;;;;;;;;;;;:::i;:::-;;;;;;;:::i;:::-;;;;;;;;619:87;;;;;;;;;;;;;:::i;:::-;;313:24;;;;;;;;;;;;;:::i;:::-;;;;;;;:::i;:::-;;;;;;;;53:53;99:6;53:53;:::o;237:31::-;;;;:::o;171:59::-;;;;;;;;;;;;;;;;;;;;;;:::o;274:33::-;;;;:::o;619:87::-;654:9;666:6;654:18;;682:9;694:5;682:17;;644:62;;619:87::o;313:24::-;;;;:::o;7:126:1:-;44:7;84:42;77:5;73:54;62:65;;7:126;;;:::o;139:96::-;176:7;205:24;223:5;205:24;:::i;:::-;194:35;;139:96;;;:::o;241:118::-;328:24;346:5;328:24;:::i;:::-;323:3;316:37;241:118;;:::o;365:222::-;458:4;496:2;485:9;481:18;473:26;;509:71;577:1;566:9;562:17;553:6;509:71;:::i;:::-;365:222;;;;:::o;593:77::-;630:7;659:5;648:16;;593:77;;;:::o;676:118::-;763:24;781:5;763:24;:::i;:::-;758:3;751:37;676:118;;:::o;800:222::-;893:4;931:2;920:9;916:18;908:26;;944:71;1012:1;1001:9;997:17;988:6;944:71;:::i;:::-;800:222;;;;:::o;1109:117::-;1218:1;1215;1208:12;1355:122;1428:24;1446:5;1428:24;:::i;:::-;1421:5;1418:35;1408:63;;1467:1;1464;1457:12;1408:63;1355:122;:::o;1483:139::-;1529:5;1567:6;1554:20;1545:29;;1583:33;1610:5;1583:33;:::i;:::-;1483:139;;;;:::o;1628:329::-;1687:6;1736:2;1724:9;1715:7;1711:23;1707:32;1704:119;;;1742:79;;:::i;:::-;1704:119;1862:1;1887:53;1932:7;1923:6;1912:9;1908:22;1887:53;:::i;:::-;1877:63;;1833:117;1628:329;;;;:::o;1963:90::-;1997:7;2040:5;2033:13;2026:21;2015:32;;1963:90;;;:::o;2059:109::-;2140:21;2155:5;2140:21;:::i;:::-;2135:3;2128:34;2059:109;;:::o;2174:210::-;2261:4;2299:2;2288:9;2284:18;2276:26;;2312:65;2374:1;2363:9;2359:17;2350:6;2312:65;:::i;:::-;2174:210;;;;:::o") end with offset more than 2k (i.e. 2174), but the file doesn't even have this length. (709 characters length).

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by ekpyron** [comment]
Note that the source map entry ``7:126:1:-`` switches to source index 1, which refers to a generate yul file. There is some discussion of this in https://docs.soliditylang.org/en/develop/analysing-compilation-output.html - you can query the generated source files for example via ``--combined-json generated-sources,generated-sources-runtime``, the source mappings after ``7:126:1:-`` refer to the generated source file with source index 1.

Does that explain what you're seeing?

**Comment by AntoineMrtl** [comment]
Oh I see ! So there isn't any issue. Thanks for your response ! I was just wondering : so can't we retreive the last opcodes's sources in the main sol file ? Why does there are in a yul file and not in the .sol ? Thanks !

**Comment by ekpyron** [comment]
The third entry in the source map is the source ID - you'll need to consider that source ID to map the source mappings back to the correct source file. There is, in general, no guarantee that the bytecode will be generated one source file at a time, you have to assume that opcodes referring to different source files can be interleaved.

The compiler generated Yul file contains shared utility functions like panic helpers that can be invoked from different places of the user-supplied solidity code.

I hope this helps!

Since it doesn't look like there is an issue with the source mappings here, I'm closing the issue!

**Comment by AntoineMrtl** [comment]
I genuinely thank you for your answer ! I just have a last question : did this mean that it is possible that a line of solidity code executed (for exemple in a solidity funtion) is not mapped in the source map ? Like if you trace back in the source map, is it possible that the mapping only map certain line and ignore other in solidity (because it map them in yul ?). To be honest, i'm trying to create a little solidity compiler and debugger to learn evm, and I want to know if it's possible to associate each line of solidity code to the corresponding opcodes, but it seems tricky, right ?

**Comment by ekpyron** [comment]
It's in particular also possible that a line of solidity code is optimized out by the compiler, in which case you will not find a reference to it in the source maps. So that alone means, that you won't be able to map each line of Solidity to an opcode in all cases.

**Comment by ALIR86** [comment]
Name contract:vyper contract
Version campiler:0.3.0
Axis MIT, I have problem in accept a of section "commit"pdf or "commit" why doesnot write compiler version is example: a v3***commit**pdf or just a v3***commit version commit this vyper contract which is a of them thank you all time to fix ,solve,support to guide,help growing of supports your thank you.👋✨️🪽💜💜

TEST
دریافت Outlook برای Android<https://aka.ms/AAb9ysg>
________________________________
