### ISSUE TITLE
Include a JSON file with known broken compiler versions

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1452]
It could be placed either into this repo and be part of `solc-bin/bin/list.json`:

```
[
{
  version: "0.4.5+commit.b318366e",
  issues: [ "optimiser" ]
},
{
  version: "0.4.3...",
  issues: [ "optimiser" ]
},
{
  version: "0.3.6...",
  issues: [ "optimiser" ]
},
{
  version: "0.3.0...",
  issues: [ "optimiser" ]
},
{
  version: "0.2.1...",
  issues: [ "optimiser" ]
}
]
```

This information can be used by during the verification process to display a warning if the contract was compiled with a known broken compiler.

**Comment by mtbitcoin** [comment]
This is a good idea, perhaps also add another value to indicate if this only affects contracts with optimization enabled/disabled or either way

**Comment by chriseth** [comment]
I think it should rather be part of this feature: https://github.com/ethereum/solidity/issues/628

**Comment by axic** [comment]
I don't think it is mutually exclusive. #628 would be nice, but we already have `list.json` in solc-bin, we might as well update it with this detail. In the future, #628 could replace `list.json` entirely.

**Comment by chriseth** [comment]
I think it should be a separate sevice than list.json provides.
