### ISSUE TITLE
Retreive exact line of opcode execution

### ISSUE THREAD

**Issue by AntoineMrtl** [ethereum/solidity#14528]
Hello, i'm sincerely sorry to not respect the supposed style of the issue but I couldn't find any way to just ask a question. My question is the following : how can I map each line to the corresponding opcodes of a solidity contract execution (runtimebytecode). I found the solc argument ("viaIR": true) to specify to the compiler to not use Yul to generate sources so it only reffer to the solidity code. The problem is that I have like I wanted only solidity source map, but maybe 90% of my opcodes are just reffered to the entire contract.

My solidity contract :

``` solidity
pragma solidity ^0.8.0;

contract TestContract {
    address public constant deadAddress = address(0xdead);

    mapping(address => bool) private _isExcludedFromFees;
    mapping(address => bool) public _isExcludedMaxTradingAmount;

    uint256 public maxTradingAmount;
    uint256 public swapTokensAtAmount;
    uint256 public maxWallet;

    constructor() {
        uint256 totalSupply = 10_000_000 * 1e18;

        swapTokensAtAmount = (totalSupply * 100) / 10000;
        maxTradingAmount = (totalSupply * 100) / 10000;
        maxWallet = (totalSupply * 100) / 10000;
    }

    receive() external payable {}

    function test(uint aaaa) external returns (uint) {
        return aaaa * 2;
    }
}

```

When i compile this contract with the following settings : 

```ts
const input = {
  language: "Solidity",
  sources: {
    "TestContract.sol": {
      content: source,
    },
  },

  settings: {
    viaIR: true,

    outputSelection: {
      "*": {
        "*": ["*"],
        "": ["*"],
      },
    },
    optimizer: {
      enabled: false,
      details: {
        yul: false,
      },
    },
  },
};
```

The MUL opcode, used to make the multiplication (or ADD if the compiler decide to add for some reason), are not mapped to the line where the variable is multiplied by 2.

 So yeah i don't really understand how online debugging tool, for exemple "tenderly", succeed to map opcode execution of function and keep a track of it. Thanks.

**Comment by VinnuReddy18** [comment]
The mapping is not always one-to-one. The compiler might optimize the code, which can result in multiple lines of Solidity code being represented by a single opcode, or vice versa1. This is likely why you’re seeing many of your opcodes referred to the entire contract.
