### ISSUE TITLE
Via-IR bytecode differences when explicitly requesting a file that would be pulled by an import

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14541]
Originally reported in https://github.com/ethereum/solidity/issues/14494#issuecomment-1692358415.

## Description
Explicitly requesting compilation of a file that is already included via imports may in certain situations affect the order in which Yul functions are placed in the IR output, which causes bytecode differences. This is apparently due to different AST IDs assigned to those functions.

The problem manifests both with and without optimizer. Only the IR pipeline is affected.

## Environment

- Compiler version: 0.8.21

## Steps to Reproduce
```bash
mkdir @

cat <<=== > a.sol
    import "@/za.sol";
    import "b.sol";

    contract A is B {
        function a() public pure {
            zb();
        }
    }
===

cat <<=== > b.sol
    import "@/zb.sol";
    import "c.sol";

    abstract contract B is C {}
===

cat <<=== > c.sol
    abstract contract C
    {
        function f() public pure {}

        function c() public view returns (uint) {
            try this.f() { return 0; }
            catch {}
        }
    }
===

cat <<=== > @/za.sol
    import "@/zc.sol";
===

cat <<=== > @/zb.sol
    import "@/zc.sol";

    function zb() pure {
        zc();
    }
===

cat <<=== > @/zc.sol
    function zc() pure returns (bytes memory returndata) {
        if (returndata.length == 0) {
            return "";
        }
    }
===

diff --color --unified \
    <(solc a.sol b.sol --bin --via-ir | grep '======= a.sol:A =======' --after-context=2 | fold --width 100) \
    <(solc a.sol       --bin --via-ir | grep '======= a.sol:A =======' --after-context=2 | fold --width 100)

diff --color --unified \
    <(solc a.sol b.sol --ir) \
    <(solc a.sol       --ir)
```

I could not go below 6 files or get rid of a subdirectory, though I suspect this is needed only due to the way it affects the import/compilation order and examples without it should be possible as well.

The import pattern goes like this:

```
a──►za──►zc
│         ▲
▼         │
b──►zb────┘
│
▼
c
```

But the pattern itself is not enough. The `try`/`catch` and all the other calls are necessary and must also be placed in specific files.

**Comment by cameel** [comment]
I think this issue is actually inherent in how we [process input files and imports](https://github.com/ethereum/solidity/blob/v0.8.21/libsolidity/interface/CompilerStack.cpp#L358-L393).

The way we do it currently is to take the files passed to the compiler initially (on the CLI or in Standard JSON) and iterate them in lexicographic order of their source unit names. We parse each file, and while doing this discover its imports and append them at the end of the list we're iterating. This means that an imported file may end up being processed earlier in that order if we include its name on the command line. This then affects AST IDs.

I don't really see a way to solve it other than collecting all the files up front and ordering them before assigning IDs. We could do it by having a separate phase of import discovery, but this is complicated because it would still require some lightweight parsing. So we could instead use the idea mentioned on the call today - assigning new IDs somewhere between parsing and codegen.

While at it, we could also order the files by content hash rather than source unit names to make the IDs independent of naming.

**Comment by r0qs** [comment]
I played a bit with the example and could simplify it a bit more, i.e. `zb` and the `try / catch` in `c` are unnecessary:

```bash
compiler=${1:-solc}

mkdir -p @

cat <<=== > a.sol
    import "@/za.sol";
    import "b.sol";

    contract A is B {
        function a() public pure {
            zc();
        }
    }
===

cat <<=== > b.sol
    import "c.sol";

    abstract contract B is C {}
===

cat <<=== > c.sol
    abstract contract C
    {
        function c() public pure returns (uint) {
            return 0;
        }
    }
===

cat <<=== > @/za.sol
    import "@/zc.sol";
===

cat <<=== > @/zc.sol
    function zc() pure returns (bytes memory returndata) {
        if (returndata.length == 0) {
            return "";
        }
    }
===

diff --color --unified \
    <($compiler a.sol b.sol --bin --via-ir | grep '======= a.sol:A =======' --after-context=2 | fold --width 100) \
    <($compiler a.sol       --bin --via-ir | grep '======= a.sol:A =======' --after-context=2 | fold --width 100)

diff --color --unified \
    <($compiler a.sol b.sol --ir) \
    <($compiler a.sol       --ir)
```

So the new import pattern is:
```
a──►za──►zc
│         
▼         
b
│
▼
c
```
