### ISSUE TITLE
Yul code compiled by solc 0.8.21 cannot be deployed

### ISSUE THREAD

**Issue by akalmykov** [ethereum/solidity#14549]
## Description

Yul code code compiled by latest solc 0.8.21 cannot be deployed by reth / anvil / goerli. I first found the problem while working with halo2-lib, which uses reth under the hood to run Yul verification. When I couldn't make it work, I tried deploying using `foundry`, forking `foundry-yul` repo. Deplyoment worked neither in test environment (anvil) nor on Goerli. After switching to 0.8.15 solc using `svm`, everything worked just fine.

I created a repo to reproduce this: https://github.com/akalmykov/foundry-yul

Note that it uses `--ffi` to call `solc`, so take a look at the source code executing.

## Environment

- Compiler version: 0.8.21 and 0.8.15
- Target EVM version (as per compiler settings): default, no additional settings
- Framework/IDE (e.g. Truffle or Remix): Foundry
- EVM execution environment / backend / blockchain client: Anvil/Reth/Goerli
- Operating system: Ubuntu 22

## Steps to Reproduce

- Clone https://github.com/akalmykov/foundry-yul
- Switch to 0.8.21: `svm use 0.8.21`
- Run `forge test`: `[FAIL. Reason: Setup failed: YulDeployer could not deploy contract] setUp() (gas: 0)`
- Switch to 0.8.15: `svm use 0.8.15`
- Run `forge test`: `[PASS] testExample() (gas: 6883)`

The same error can be reproduced by Goerli deployment. This works:
```sh
svm use 0.8.15
forge script script/Deploy.sol:Deploy --rpc-url https://ethereum-goerli.publicnode.com --broadcast --private-key <PRIVATE_KEY> --ffi

✅  [Success]Hash: 0x33fed28b40525accdbb9a8e1158b93b0bd842bf8e34879432751faf05b6b2580
Contract Address: 0x166902beE28AD9F380dD0D1b10dC292D9a9F572e
Block: 9652762
Paid: 0.00016607400055358 ETH (55358 gas * 3.00000001 gwei)
```

However, this fails:

```sh
svm use 0.8.21 
forge script script/Deploy.sol:Deploy --rpc-url https://ethereum-goerli.publicnode.com --broadcast --private-key <PRIVATE_KEY> --ffi

No files changed, compilation skipped
Traces:
  [397935] → new Deploy@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 1877 bytes of code

  [9079256848778921037] Deploy::run() 
    ├─ [0] VM::ffi([bash, -c, cast abi-encode "f(bytes)" $(solc --yul yul/Example.yul --bin | tail -1)]) 
    │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000146009600b5f3960095ff3fe5f35608052366080f3000000000000000000000000
    ├─ [0] VM::broadcast() 
    │   └─ ← ()
    ├─ [6] → new <Unknown>@0x1E3742019B621CF2981225aB8D9D36c9176a1778
    │   └─ ← 0 bytes of code
    └─ ← "YulDeployer could not deploy contract"
```

Contract byte codes for two solc versions:

```
svm use 0.8.15
solc --yul --bin yul/Example.yul 

======= yul/Example.yul (EVM) =======

Binary representation:
600a600d600039600a6000f3fe600035608052366080f3

svm use 0.8.21 
solc --yul --bin yul/Example.yul 

======= yul/Example.yul (EVM) =======

Binary representation:
6009600b5f3960095ff3fe5f35608052366080f3
```

**Comment by cameel** [comment]
On v0.8.21 `--evm-version shanghai` is the default. On that version we emit code that makes use of the `PUSH0` opcode (`0x5f`) that was not available in earlier versions. Deployment will naturally fail if you try to do it on a chain that runs an earlier EVM version.

So the question is: does Goerli run a `shanghai` EVM? I remember that in March the Shanghai upgrade was performed there (successfully), but looking at https://github.com/eth-clients/goerli now it says that the EVM version is `london`. Has it been reset in the meantime?

In any case, this does not look like a bug in the compiler. If you deploy somewhere with an earlier EVM version, you can request compatible bytecode using the `--evm-version` option.

**Comment by akalmykov** [comment]
> In any case, this does not look like a bug in the compiler. If you deploy somewhere with an earlier EVM version, you can request compatible bytecode using the `--evm-version` option.


Setting `--evm-version=london` indeed helped. The issue can be closed. Thank you!
