### ISSUE TITLE
Where can I find specifications about `call`, `delegatecall` and `staticcall`?

### ISSUE THREAD

**Issue by adu-web3** [ethereum/solidity#14567]

**Comment by r0qs** [comment]
Hi @adu-web3, you can find a brief description of the mentioned opcodes here in our docs: https://docs.soliditylang.org/en/latest/yul.html#evm-dialect
Also, for more details about them, you can check the [Yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) or https://www.evm.codes/#f1?fork=shanghai.

Furthermore, the Github issue page is for bugs/feature requests only, post your questions related to Solidity language or the compiler in our [forum](https://forum.soliditylang.org/) or talk to us directly on the [#solidity-dev](https://matrix.to/#/#ethereum_solidity-dev:gitter.im) channel on Matrix.
