### ISSUE TITLE
New doc style is not good for reading.

### ISSUE THREAD

**Issue by adu-web3** [ethereum/solidity#14568]
## Abstract

Could we provide old doc style so that readers could choose which style they want?

**Comment by r0qs** [comment]
As far as I know, we do not have plans to support the old style of the documentation page. Any reason to not use the current version?

**Comment by adu-web3** [comment]
The background is grey while the text is like purple, which means that the
text would not stand out as much as black against white

r0qs ***@***.***>于2023年9月19日 周二18:49写道：

**Comment by r0qs** [comment]
Hum...for me it does not show grey but pinkish/purplish. Have you tried to switch to the dark mode? However, we could definitely rethink the accessibility features of the page if needed. For that, you can open an issue describing your specific concerns on https://github.com/ethereum/solidity-website.

![2023-09-19-125928_4176x1504_scrot](https://github.com/ethereum/solidity/assets/457348/8230e9ff-9170-4299-9581-db23b69a3a17)
![2023-09-19-125929_4176x1504_scrot](https://github.com/ethereum/solidity/assets/457348/8e25368d-354f-42e4-b037-f06012bab0fb)
