### ISSUE TITLE
Distinguish fixed free types from generic type variables in experimental solidity.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#14570]
Currently, all type variables, whether implicitly assigned or explicitly mentioned in the sources, are treated as generic type variables (``TypeVariable``). It is worthwhile to distinguish those from contextually fixed free types. (See also "Distinction between Fixed Free Type Variables and Schematic Type Variables" in https://notes.ethereum.org/_OSmtx9aQAOHQXwa60IDsQ for some previous notes on that)

The unification behaviour of fixed free type variables is simple: they only unify with themselves (including identical sort constraints), nothing else.

The assignment between a name (like ``a`` in ``function f(x:a)``) and a free type variable is scoped (here valid for the function signature and body - for type variables in type classes for the entire type class definition), but for safety their internal representation in the type system should be globally unique.

One of the main advantages of having free type variables is that they can prevent accidental, undesired unification.

The process of type-checking a function should involve a post-processing step on the type, which replaces all generic type variables by free types. That prevents further unification of the function type after its passed type inference (unifying the actual function signature later on is erroneous).
Conversely, that means that *importing* a function (when referred to with an identifier) into local context will involve the opposite transformation, *generalization*, i.e. replacing the fixed free types with fresh type variables (the analog to this currently happens using ``polymorphicInstance``, but nothing prevents us from forgetting to use this function and import with not-freshened type variables, which will result in invalid behaviour - if we have assign fixed free types to the function instead, importing that type without generalization will usually result in unification errors rather than invalid behaviour)

Note that this approach is expected to break mutually recursive functions for now (they're not expected to properly work in the current version anyways, though) - that will be remedied after we can order type inference using the upcoming function call graph (https://github.com/ethereum/solidity/issues/14532), but there's no reason to delay this issue until that's done.

Furthermore, explicitly mentioned type variables should be assigned fixed free types to begin with instead of generic type variables. Note that reference resolution currently also doesn't scope explicitly mentioned type variables correctly, so don't be surprised by that (e.g. ``function f(x:a) -> a`` won't resolve the second ``a`` properly, I think). We could resolve this by messing with scoping in name and type resolution, but we can also just already introduce proper syntax for declaring fixed free types (i.e. ``f<a>`` - we can still haggle over iterating the syntax later). That'd involve treating ``<a>`` as declaration with a proper scope in reference resolution, s.t. the uses in the signature resolve to that declaration. (Obviously, we would need to allow ``<a, b>`` and ``<a:SomeClass, b:SomeOtherClass>``, etc.)

So initial scope:
- Introduce a new ``variant`` of ``Type`` for fixed free type variables.
- Implement unification on them.
- Fix types after type-inference on function.
- Replace ``polymorphicInstance`` on importing types of already type-checked functions with a generalization step.
- Treat explicit type variables in function signatures and type class declarations as fixed free types instead of generic type variables. Optionally, adjust syntax and scoping for them in function signatures.

**Comment by cameel** [comment]
> We could resolve this by messing with scoping in name and type resolution, but we can also just already introduce proper syntax for declaring fixed free types

Well, I think that they should be declared explicitly anyway. Otherwise there are some issues:
1. How do you choose between a fixed/generic type variable for the result? You cannot omit the type there.
2. It's too easy to accidentally introduce a type variable by just misspelling something in the type.

**Comment by ekpyron** [comment]
In particular for function return types a placeholder ``_`` indicating a fresh generic type variable would generally come in handy :-).

**Comment by cameel** [comment]
> - Replace `polymorphicInstance` on importing types of already type-checked functions with a generalization step.

Is this still something we want to do? Generalization is just the replacement with fresh type variables, i.e. `TypeEnvironment::fresh()`, which is why I wanted to replace `polymorphicInstance()` with it in #14635, but then you objected to that. So now I'm not sure if I should do anything for this point.

> Treat explicit type variables in function signatures and type class declarations as fixed free types

Should I do that for type declarations (e.g. make `X` fixed in `type T(X) = ...`) too? For now #14655 only handles what the description says, but it seems to me that the same exact problem exists for type declarations.

**Comment by ekpyron** [comment]
> > * Replace `polymorphicInstance` on importing types of already type-checked functions with a generalization step.
> 
> Is this still something we want to do? Generalization is just the replacement with fresh type variables, i.e. `TypeEnvironment::fresh()`, which is why I wanted to replace `polymorphicInstance()` with it in #14635, but then you objected to that. So now I'm not sure if I should do anything for this point.
> 

You can just keep using ``polymorphicInstance`` for this, since we're switching to merely marking fixed type variables in type environments.

> > Treat explicit type variables in function signatures and type class declarations as fixed free types
> 
> Should I do that for type declarations (e.g. make `X` fixed in `type T(X) = ...`) too? For now #14655 only handles what the description says, but it seems to me that the same exact problem exists for type declarations.

Yes, every named type should be fixed.

**Comment by ekpyron** [comment]
It may actually make sense to just rename ``polymorphicInstance`` to ``generalize``.
