### ISSUE TITLE
Enable function pointers to work with overloaded functions

### ISSUE THREAD

**Issue by Arvolear** [ethereum/solidity#14579]
## Abstract

Function pointers don't work with overloaded functions.

## Motivation

The current compiler doesn't recognize valid overloaded functions as candidates for function pointers. This limitation forces developers to use different function names *for the functions that have similar functionality*, which creates unnecessary code bulk. 

The compilation fails with the misleading message `TypeError: No matching declaration found after variable lookup.`. Even though the matching declaration is there. At least the error message may be a tiny bit more meaningful.

## Specification

Can't provide in-depth technical specification, however here is the code snipped that doesn't compile. 

```solidity
pragma solidity ^0.8.21;

contract WontCompile {
    function deduce() external {
        bar(foo); // compilation fails due to this line
    }

    function foo(uint256) internal {}

    function foo(address) internal {}

    function bar(function(uint256) internal numFoo) internal {}
}
```

## Backwards Compatibility

Should not be backward incompatible.

**Comment by VinnuReddy18** [comment]
In your code, you’re trying to pass a function foo as an argument to another function bar. However, foo is an overloaded function, meaning there are multiple functions named foo with different parameters. When you try to pass foo to bar, the compiler doesn’t know which version of foo you’re referring to, hence the error.
Assign me..

**Comment by Yash9276** [comment]
<h1>Isuue : Function pointers don't work with overloaded functions</h1>
<p>
  <h2>Cause</h2>  In Solidity, it's not possible to directly pass functions as arguments to other functions without using function types or assigning them to variables. You need to define the function type or assign the function to a variable before passing it as an argument to another function. This is a limitation of the language.
</p>
I hope this solution helps you.
<br/>
Assign this issue to me I will solve it 
<br/>
Thank you :)
</p>

**Comment by ArpitKRS** [comment]
Please /assign this issue to me and let's discuss over it.
