### ISSUE TITLE
Solver z3 was selected for SMTChecker but it is not available.

### ISSUE THREAD

**Issue by mysteryon88** [ethereum/solidity#14583]
Hi all, please help me to get SMTChecker up and running.
I'm using Debian, same problem on Ubuntu. I install solc from ppa:ethereum, z3 installed in different ways, there was a problem in z3lib, now I installed z3-static from cpp-build-deps and now I get this error "Solver z3 was selected for SMTChecker but it is not available.". 
How do I install z3 and solc to make it work?

**Comment by r0qs** [comment]
Hi @mysteryon88,

what are your Debian and z3 version? Are you trying to compile `solc` or just downloading the binary?

Could you try install `solc` and `z3` from the PPA as mentioned here: https://github.com/ethereum/solidity/issues/13073#issuecomment-1688473817

See https://github.com/ethereum/solidity/issues/13073#issuecomment-1149675618 for context.

**Comment by mysteryon88** [comment]
Hi, @r0qs!
Using:
Debian 12.1.0
I load solc like this
```sh
sudo add-apt-repository ppa:ethereum/ethereum 
sudo apt-get update 
sudo apt-get install solc
```
I downloaded z3 via apt and it didn't work, there was an error related to the lack of `libz3.so.4.8` library.
Following the advice from that thread, I installed z3 from `ppa:ethereum/cpp-build-deps`.

I've seen that maybe it won't work on Ubuntu/Debian, then maybe you can tell me on which operating system it will be possible to run SMT Checker? Maybe use other SMT solvers?

**Comment by r0qs** [comment]
Hi,

I know it works fine on Archlinux and, as far as I know, it should work fine on Ubuntu if you use the `cpp-build-deps` ppa to install `z3`. I just tried it here in a Docker image and it works. I will paste it here for you as guidance.

```dockerfile
# syntax=docker/dockerfile:1-labs

FROM ubuntu:22.04
RUN apt-get update; \
    apt-get install -qqy software-properties-common

RUN add-apt-repository -y ppa:ethereum/ethereum; \
    apt-get update; \
    apt-get install -qqy solc

RUN add-apt-repository -y ppa:ethereum/cpp-build-deps; \
    apt-get install -qqy z3-static

RUN <<EOT
cat << EOF > /tmp/c.sol
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.0;
contract test {
	uint x;
    function f() public view {
		assert(x < 10);
    }
}
EOF
EOT

CMD solc --model-checker-engine=chc --model-checker-solvers=z3 --model-checker-invariants "contract" /tmp/c.sol
```

If you build and run this Dockerfile as below, you should get the smtChecker output as expected:
```sh
docker build -t ubuntu2204-solidity -f Dockerfile . --force-rm

docker run -it --rm --name solc-docker ubuntu2204-solidity:latest
Info: CHC: 1 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: Contract invariant(s) for tmp/c.sol:test:
(!(x >= 1) || true)
```

**Comment by mysteryon88** [comment]
@r0qs, thanks, I'll give it a try.

**Comment by mysteryon88** [comment]
@r0qs, thanks a lot, everything worked out, I still can't figure out what I did wrong, although I put everything through the ppa...
We should make this correspondence a guide for everyone.
