### ISSUE TITLE
Assigning private function to a function pointer of an internal type

### ISSUE THREAD

**Issue by msm-mdmahbubur-rahman** [ethereum/solidity#14623]
In Solidity documentation, I found the below information:
**A function of an internal type can be assigned to a variable of an internal function type regardless of where it is defined. This includes **private**, internal and public functions of both contracts and libraries as well as free functions. External function types, on the other hand, are only compatible with public and external contract functions.**

Here private function of a contract or from library if assigned to a function pointer of internal type, will lead to a compilation error.

Example:

    pragma solidity ^0.8.0;
    contract MyContract {
    uint privateData = 42;

    function internalFunction() internal {
        // This is an internal function within MyContract
        privateData = 100;
    }
    function privateFunction() private {
        // This is a private function within MyContract
        privateData = 200;
    } }
    contract FunctionPointerExample {
        // Attempting to assign a private function to a function pointer. This will result in a compilation error
        function () internal internalFunc = MyContract.privateFunction;
     }

Reference: https://docs.soliditylang.org/en/v0.8.21/types.html#function-types

**Comment by adityakaaltatva** [comment]
pragma solidity ^0.8.0;

contract MyContract {
    uint privateData = 42;

    function internalFunction() internal {
        // This is an internal function within MyContract
        privateData = 100;
    }

    function privateFunction() private {
        // This is a private function within MyContract
        privateData = 200;
    }
}

contract FunctionPointerExample {
    function callPrivateFunction() internal {
        (bool success, ) = address(this).delegatecall(
            abi.encodePacked(bytes4(keccak256("privateFunction()")))
        );
        require(success, "Private function call failed");
    }
}
//improved solidity code

**Comment by Rashann2471** [comment]
> In Solidity documentation, I found the below information: **A function of an internal type can be assigned to a variable of an internal function type regardless of where it is defined. This includes private, internal and public functions of both contracts and libraries as well as free functions. External function types, on the other hand, are only compatible with public and external contract functions.**
> 
> Here private function of a contract or from library if assigned to a function pointer of internal type, will lead to a compilation error.
> 
> Example:
> 
> ```
> pragma solidity ^0.8.0;
> contract MyContract {
> uint privateData = 42;
> 
> function internalFunction() internal {
>     // This is an internal function within MyContract
>     privateData = 100;
> }
> function privateFunction() private {
>     // This is a private function within MyContract
>     privateData = 200;
> } }
> contract FunctionPointerExample {
>     // Attempting to assign a private function to a function pointer. This will result in a compilation error
>     function () internal internalFunc = MyContract.privateFunction;
>  }
> ```
> 
> Reference: https://docs.soliditylang.org/en/v0.8.21/types.html#function-types
