### ISSUE TITLE
Issues with reproducing bytecode when unrelated files are being included/excluded from standard-json

### ISSUE THREAD

**Issue by Enigmatic331** [ethereum/solidity#14626]
We recently found some issues reproducing the same bytecode when some .sol files are included/removed unrelated to the contract we are extracting bytecode for.

E.g.: https://github.com/foundry-rs/foundry/issues/5327#issuecomment-1625719371
This is a scaled down example with Frax Finance, difference being [1.txt](https://github.com/foundry-rs/foundry/files/11984373/1.txt) has an additional IERC20.sol file, while the other doesn't, and the IERC20.sol file is not being referenced - Resulting in entirely different bytecode.

(source file diffs)
![image](https://github.com/ethereum/solidity/assets/28551011/b7f3535c-6df6-4a55-8901-552a6872c311)

We have also seen other instances, e.g. with Aave's contracts (e.g. https://snowtrace.io/address/0x42502A9213171D33902256C61e0B6f5c25eB9481#contracts, i.e. notice how EthDeploy.s.sol and PolDeploy.s.sol files are empty, we kept the files in the standard-json input albeit empty, as removing the file(names) will cause a bytecode diff).

Any idea what might be happening, and if there is anything we could do about it? 🙏 Thanks in advance!

**Comment by Enigmatic331** [comment]
For the Frax Finance example, the below two outputs when compiling with 0.8.19

[1_output.txt](https://github.com/ethereum/solidity/files/13038640/1_output.txt)
[2_output.txt](https://github.com/ethereum/solidity/files/13038641/2_output.txt)

Especially the resulting bytecode for VeFxsVotingDelegation
![image](https://github.com/ethereum/solidity/assets/28551011/f2f63da9-ab38-4bd2-bd2f-6579f096016d)

**Comment by r0qs** [comment]
Hi @Enigmatic331 we recently fixed a bug which seems to be exactly the problem you are having, please see: https://github.com/ethereum/solidity/issues/14541 and https://github.com/ethereum/solidity/issues/14494. However, we didn't release the version that contains the bug fix yet, FYI we are planning to release next week, so Solidity version `0.8.22` will contain the fix for this issue.

Could you try to run your example using the current solidity version on the `develop` branch?

**Comment by Enigmatic331** [comment]
We pulled one of the nightly builds, and it does look like it solves the problem. :) Looking forward to 0.8.22.

Cheers and thanks.

**Comment by Enigmatic331** [comment]
Just keeping track since we are getting reports of contracts > 0.8.22 not being able to reproduce bytecode: https://github.com/ethereum/solidity/issues/15134

**Comment by Enigmatic331** [comment]
Just documenting a case for v0.8.24: https://github.com/circlefin/buidl-wallet-contracts/commit/af55d552bb3e881afdbf24f675f682036d0772d1

Using Foundry, outputs are different between these two commands:

`forge build --build-info "\buidl-wallet-contracts\src\msca\6900\v0.7\factories\semi\SingleOwnerMSCAFactory.sol"`

`forge build --build-info`

Getting the output files from out\SingleOwnerMSCAFactory.sol:

[SingleOwnerMSCAFactory_1.json](https://github.com/user-attachments/files/18478671/SingleOwnerMSCAFactory_1.json)
[SingleOwnerMSCAFactory_2.json](https://github.com/user-attachments/files/18478666/SingleOwnerMSCAFactory_2.json)

I am guessing this should be sorted post v0.8.26... :)
