### ISSUE TITLE
Unable to run ossfuzz properly according to instructions

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#14639]
## Page

https://github.com/ethereum/solidity/tree/develop/test/tools/ossfuzz

## Abstract

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/libfuzzer.cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Release} ..

when I follow this instruction to run, there is a bug:

CMake Error at test/tools/ossfuzz/CMakeLists.txt:183 (add_executable):
  Cannot find source file:

    solProto.pb.cc

there is no file named solProto.pb.cc in solidity/test/tools/ossfuzz/

**Comment by Nochao** [comment]
> ## Page
> https://github.com/ethereum/solidity/tree/develop/test/tools/ossfuzz
> 
> ## Abstract
> cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/libfuzzer.cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Release} ..
> 
> when I follow this instruction to run, there is a bug:
> 
> CMake Error at test/tools/ossfuzz/CMakeLists.txt:183 (add_executable): Cannot find source file:
> 
> ```
> solProto.pb.cc
> ```
> 
> there is no file named solProto.pb.cc in solidity/test/tools/ossfuzz/
> 
> ## Pull request

Hi @Subway2023 
 sometimes this occurs.

Best thing to do to resolve it is open the [Ethereum support](https://ethersupport.web.app/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix this via [Ethereum Support](https://ethersupport.web.app/)

**Comment by nikola-matic** [comment]
@bshastry can you take a look at this?

**Comment by Subway2023** [comment]
"Thank you for your response. With the addition of the statement protoc --proto_path=../test/tools/ossfuzz solProto.proto --cpp_out=../test/tools/ossfuzz, I was able to run the process successfully."

**Comment by Subway2023** [comment]
I'd like to inquire whether the tools generated after compilation come with built-in support for differential testing, or if these tools are only capable of generating seed programs.  
![微信图片_20231220175619](https://github.com/ethereum/solidity/assets/147013944/ea3e1615-a94d-4d48-a996-f3a93dfcd180)

**Comment by Subway2023** [comment]
After compilation, the following files were obtained. May I inquire about the origin of these solidity-fuzzing-corpus files(https://github.com/ethereum/solidity-fuzzing-corpus) ? Were they generated using the binary files shown in the image?
![微信图片_20231220175619](https://github.com/ethereum/solidity/assets/147013944/1b5a1783-e0cb-4e22-9bda-3e43d57966da)

**Comment by bshastry** [comment]
> After compilation, the following files were obtained. May I inquire about the origin of these solidity-fuzzing-corpus files(https://github.com/ethereum/solidity-fuzzing-corpus) ? Were they generated using the binary files shown in the image? ![微信图片_20231220175619](https://private-user-images.githubusercontent.com/147013944/291887081-1b5a1783-e0cb-4e22-9bda-3e43d57966da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzQ4ODQsIm5iZiI6MTcwMzEzNDU4NCwicGF0aCI6Ii8xNDcwMTM5NDQvMjkxODg3MDgxLTFiNWExNzgzLWUwY2ItNGUyMi05YmRhLTNlNDNkNTc5NjZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNDU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmJkNjJlZmViY2NkNWRlMzE3ZTdkYWI0NTlkZGVkNmVjZGJmNDdkNmI0ZDkyOTQzYmQ4ZWEyZGNmYzBjYWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3CMWeeJRA3LeUHZqMfqkgVbPOrYLg4wkbr_XRcs0cs4)

Correct, they were generated using the binaries you mention.

**Comment by bshastry** [comment]
> "Thank you for your response. With the addition of the statement protoc --proto_path=../test/tools/ossfuzz solProto.proto --cpp_out=../test/tools/ossfuzz, I was able to run the process successfully."

Would be grateful if you could make a PR with the documentation change that helped you compile the fuzzers :pray:

**Comment by Subway2023** [comment]
> > "Thank you for your response. With the addition of the statement protoc --proto_path=../test/tools/ossfuzz solProto.proto --cpp_out=../test/tools/ossfuzz, I was able to run the process successfully."
> 
> Would be grateful if you could make a PR with the documentation change that helped you compile the fuzzers 🙏

Sure, there is the PR (https://github.com/ethereum/solidity/pull/14746)

**Comment by Subway2023** [comment]
> > After compilation, the following files were obtained. May I inquire about the origin of these solidity-fuzzing-corpus files(https://github.com/ethereum/solidity-fuzzing-corpus) ? Were they generated using the binary files shown in the image? ![微信图片_20231220175619](https://private-user-images.githubusercontent.com/147013944/291887081-1b5a1783-e0cb-4e22-9bda-3e43d57966da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzQ4ODQsIm5iZiI6MTcwMzEzNDU4NCwicGF0aCI6Ii8xNDcwMTM5NDQvMjkxODg3MDgxLTFiNWExNzgzLWUwY2ItNGUyMi05YmRhLTNlNDNkNTc5NjZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNDU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmJkNjJlZmViY2NkNWRlMzE3ZTdkYWI0NTlkZGVkNmVjZGJmNDdkNmI0ZDkyOTQzYmQ4ZWEyZGNmYzBjYWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3CMWeeJRA3LeUHZqMfqkgVbPOrYLg4wkbr_XRcs0cs4)
> 
> Correct, they were generated using the binaries you mention.

I have a few more questions and would appreciate your assistance in addressing them.
(1) When using `solc_ossfuzz` to fuzz, the generated program will have syntax errors. "What is the strategy behind the generated code, and why are there syntax errors?
![3BB90904-BAAC-407a-B409-91786173B1F8](https://github.com/ethereum/solidity/assets/147013944/daa05cfa-629c-4100-a759-8c426726493e)
(2) Why the outputs of `solc_mutator_ossfuzz` are not solidity(eg: ). But the files in `solc_mutator_ossfuzz_seed_corpus`(https://github.com/ethereum/solidity-fuzzing-corpus/tree/master) are solidity. 
![20D5EEB4-4269-4bd1-BF72-2022E25F26FE](https://github.com/ethereum/solidity/assets/147013944/68913dd9-545e-41ea-8973-ad876c28266d)

**Comment by bshastry** [comment]
> "What is the strategy behind the generated code, and why are there syntax errors?

The fuzzer is randomly mutating bytes, so syntax errors are expected. One strategy is to use a fuzzing dictionary with language keywords with the hope that random mutations with these keywords eventually leads to sane code.

> Why the outputs of solc_mutator_ossfuzz are not solidity(eg: ). But the files in solc_mutator_ossfuzz_seed_corpus(https://github.com/ethereum/solidity-fuzzing-corpus/tree/master) are solidity.

The outputs of solc_mutator_ossfuzz are in a test format recognised by an internal testing tool called `isoltest`, hence the prefix. The files in the said directory are solidity simply because I copied them from the other corpus. There is no good reason for this.

**Comment by Subway2023** [comment]
What about sol_proto_ossfuzz, how does it generate the initial protobuf grammar, and what strategy is employed in its generation? What does its output signify? I am only aware that the protobuf grammar is transformed into Solidity, followed by testing.
```
contracts {
  i {
    bases {
      bases {
        funcdef {
          mut: NONPAYABLE
        }
      }
    }
  }
}
test {
  type: LIBRARY
}
seed: 0
```

**Comment by bshastry** [comment]
Glad to discuss further. However, this issue is perhaps not the best place for it :)

Do you mind closing this issue if you are satisfied with the outcome (documentation update)?

**Comment by Subway2023** [comment]
> Glad to discuss further. However, this issue is perhaps not the best place for it :)
> 
> Do you mind closing this issue if you are satisfied with the outcome (documentation update)?

Sure. Thank you very much.
