### ISSUE TITLE
Add explanation about new optimization `simpleCounterForLoopUncheckedIncrement`

### ISSUE THREAD

**Issue by matheusaaguiar** [ethereum/solidity#14648]
## Page

Optimizer Section of the documentation.

https://docs.soliditylang.org/en/latest/internals/optimizer.html

## Abstract

Since `0.8.22`, the compiler can use unchecked arithmetic when incrementing the counter of `for` loops, under certain specific conditions. Those conditions need to be properly explained in the documentation.
The blog [post](https://soliditylang.org/blog/2023/10/25/solidity-0.8.22-release-announcement) about the `0.8.22` release and the [PR](https://github.com/ethereum/solidity/pull/13378) that introduced the functionality have the necessary information and examples about that.

**Comment by ekpyron** [comment]
This will in fact open a third subsection there besides ``Opcode-Based Optimizer Module`` and ``Yul-Based Optimizer Module``.
As a name for that section, I'd suggest ``Codegen-Based Optimizations`` or ``Optimized Code Generation`` or such, but open for better choices (``Code Generation Optimizations Based On An Analysis Of Solidity Code`` is a bit bulky :-)).

**Comment by matheusaaguiar** [comment]
Closed by #14650.
