### ISSUE TITLE
Compiler Flag for Upgradeable Storage Arrays Using Mappings

### ISSUE THREAD

**Issue by quirp** [ethereum/solidity#14662]
## Abstract

In Solidity, when developing upgradeable contracts, a primary challenge is ensuring consistent storage layouts across upgrades. The current storage array design does not offer a straightforward mechanism for natural upgradeability. This proposal introduces a compiler flag that implicitly converts storage arrays, specifically of type struct, to a schema of an array of mappings from uint8 to the type of struct. In this schema, the 0 key is always implicitly used. This method leverages Solidity's storage slot schema to protect against unforeseen future upgrades and ensures a consistent storage layout.
## Motivation

With the rise of upgradeable contracts in the Ethereum ecosystem, there's a significant need to maintain the consistency of storage variables across various contract upgrades. Currently, developers must be cautious when adding or modifying storage variables, especially arrays. Unintended changes to the storage layout can lead to data corruption or other unexpected complications.

For instance, consider a scenario where a developer uses an array to store structs:

```
struct A {
    uint256 value;
    // ... other fields ...
}

A[] public data;
```
If there's a change to the structure of A in a subsequent upgrade or if additional storage variables are introduced to the contract, the storage layout may be at risk. By transitioning arrays to a schema of an array of mappings, where each mapping is from uint8 to the datatype (e.g., A), a layer of indirection is added, ensuring the storage slot's consistency:

```
mapping(uint8 => A)[] public data;
```

Here, the zero key is always implicitly used.

This approach offers a safeguard against unintentional storage layout changes and ensures data remains accessible and consistent across upgrades.
## Specification

Compiler Flag: --useUpgradeableArrays

When this flag is enabled, the compiler will implicitly transform all storage arrays in the contract to the array of mappings schema. For any storage array declared as T[], it will be internally represented as mapping(uint8 => T)[], with the zero key being consistently used.
# Syntax:

No changes to the existing Solidity language syntax are required. Developers can continue to declare arrays as they typically would.
# Semantics:

    Addition: When appending a new element to an array, it should be placed into the mapping using the 0 key within a new array element.

    Access: When accessing an element of an array, the compiler will fetch the data from the mapping using the 0 key.

**Comment by nikola-matic** [comment]
Hi @quirp, the storage layout is well defined, and has been for ages, so we will not be changing it. Changing anything storage layout related is incredibly touchy, and incredibly breaking, and we would only consider doing so if absolutely necessary, which this is not.

You can either use the approach you suggested, or one of the upgradeable contracts libraries (e.g OZ).
