### ISSUE TITLE
Solidity optimizer hangs on certain constants.

### ISSUE THREAD

**Issue by recmo** [ethereum/solidity#1466]
Running `solc --optimize` on the following takes forever, without `--optimize` it compiles fine.
 
```
pragma solidity ^0.4.0;

contract Test {
    function test() returns (uint) {
        return 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff;
    }
}
```

**Comment by Recmo** [comment]
Minimized test case:

```
pragma solidity ^0.4.0; // + optimizations

contract Test {
    function test(uint y) returns (uint x) {
        x = y;
        x = (x | (x * 2** 8)) & 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff;
    }
}
```

**Comment by recmo** [comment]
It looks like a exponential blowup. With smaller constants it optimizes: 
* `0x00ff00ff00ff00ff00ff00ff00ff00ff` compiles 2 seconds.
* `0x00ff00ff00ff00ff00ff00ff00ff00ff00ff` compiles in 11 seconds.
* `0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff` takes more than one minute.

**Comment by VoR0220** [comment]
hmmmmm @axic this seems like it might have been something you worked on in the past, no?

**Comment by chriseth** [comment]
This is a quite old feature, @VoR0220 , it tries to represent the number with an expression that is shorter than the constant.

**Comment by recmo** [comment]
Here's my use-case: https://gist.github.com/Recmo/2fe7e4179127cc7fd693fe5b876c1525 Feel free to include it in the test suite, if you want.
