### ISSUE TITLE
Can a plain return be an error when a return value is expected

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#1467]
```
function greet() returns (string) {
    return;
}
```
Can the compiler detect this as an error?  And require the user to have something after the `return` (a literal string, or a variable that is of type string)?

**Comment by chriseth** [comment]
It is not an error, for example consider the following:
```js
function computeTwoValues(uint x) returns (uint a, uint b) {
  a = computeFirst(x);
  b = computeSecond(x);
  if (a != b) return;
  else throw;
}
```

**Comment by chriseth** [comment]
But it is probably fine to add a warning here for future versions.

**Comment by chriseth** [comment]
Sub-issue of https://github.com/ethereum/solidity/issues/718
