### ISSUE TITLE
Source file requires different compiler version

### ISSUE THREAD

**Issue by emiliolanzalaco** [ethereum/solidity#14676]
Hi, I am having some issues with the compiler version. 

I am inside of a basic forge init repo. I am trying to use solidity version 0.8.22 but I am locked to 0.8.19 no matter what settings I choose. 

Here is my settings.json inside the workspace:
```
{
    "solidity.compileUsingRemoteVersion": "v0.8.22+commit.4fc1097e",
    "solidity.defaultCompiler": "remote"
}
```

Here is my solidity file:
```
// SPDX-License-Identifier: MIT

pragma solidity 0.8.22;
```

And here is my error:
```
Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version(5333)
```

I think this could be a bug. Could someone replicate this?

**Comment by emiliolanzalaco** [comment]
Sorry I meant to open this in https://github.com/juanfranblanco/vscode-solidity

**Comment by qwerty472123** [comment]
@emiliolanzalaco 
I found this is caused by the content of <https://binaries.soliditylang.org/bin/soljson-latest.js> is same as <https://binaries.soliditylang.org/bin/soljson-v0.8.19+commit.7dd6d404.js>, now.

I wonder where can found maintainer of binaries.soliditylang.org to fix this issue. Thanks.

**Comment by marospaliga** [comment]
Any solution for this? I have same problem trying to use higher versions.

**Comment by last0x** [comment]
this fix seems to work - https://medium.com/michaels-dapp-dev-tips/how-to-change-the-solidity-compiler-in-vs-code-4c2660a856da
