### ISSUE TITLE
Inheritance Linearization and Storage Layout

### ISSUE THREAD

**Issue by ArielTM** [ethereum/solidity#14684]
## Description

Inheritance Linearization affects the storage layout. An upgrade that seemingly shouldn't affect the layout might result in storage variables shifting places.

## Environment

- Compiler version: 0.8.21
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Foundry
- EVM execution environment / backend / blockchain client: none
- Operating system: mac

## Steps to Reproduce

The following simple code:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.12;

contract A {
    uint256 public param_a;
}

contract B is A {
    uint256 public param_b;
}

contract C {
    uint256 public param_c;
}

contract Test is C, B {
    uint256 public number;
}
```

Will produce the following storage layout:

```json
{
  "storage": [
    {
      "astId": 12,
      "contract": "src/Counter.sol:Test",
      "label": "param_c",
      "offset": 0,
      "slot": "0",
      "type": "t_uint256"
    },
    {
      "astId": 4,
      "contract": "src/Counter.sol:Test",
      "label": "param_a",
      "offset": 0,
      "slot": "1",
      "type": "t_uint256"
    },
    {
      "astId": 9,
      "contract": "src/Counter.sol:Test",
      "label": "param_b",
      "offset": 0,
      "slot": "2",
      "type": "t_uint256"
    },
    {
      "astId": 19,
      "contract": "src/Counter.sol:Test",
      "label": "number",
      "offset": 0,
      "slot": "3",
      "type": "t_uint256"
    }
  ],
  "types": {
    "t_uint256": {
      "encoding": "inplace",
      "label": "uint256",
      "numberOfBytes": "32"
    }
  }
}
```

While inroducing a simple upgrade to the contract, that shouldn't affect the storage:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.12;

contract Upgrade {

}

contract A {
    uint256 public param_a;
}

contract B is A, Upgrade {
    uint256 public param_b;
}

contract C is Upgrade {
    uint256 public param_c;
}


contract Test is C, B {
    uint256 public number;
}
```

The storage changes:

```json
{
  "storage": [
    {
      "astId": 4,
      "contract": "src/Counter.sol:Test",
      "label": "param_a",
      "offset": 0,
      "slot": "0",
      "type": "t_uint256"
    },
    {
      "astId": 16,
      "contract": "src/Counter.sol:Test",
      "label": "param_c",
      "offset": 0,
      "slot": "1",
      "type": "t_uint256"
    },
    {
      "astId": 11,
      "contract": "src/Counter.sol:Test",
      "label": "param_b",
      "offset": 0,
      "slot": "2",
      "type": "t_uint256"
    },
    {
      "astId": 23,
      "contract": "src/Counter.sol:Test",
      "label": "number",
      "offset": 0,
      "slot": "3",
      "type": "t_uint256"
    }
  ],
  "types": {
    "t_uint256": {
      "encoding": "inplace",
      "label": "uint256",
      "numberOfBytes": "32"
    }
  }
}
```

This will have devastating effect in case of a protocol upgrade. I wonder if there should be a mechanism in which storage slots are not affected by linearization.

**Comment by nikola-matic** [comment]
Given that we support multiple inheritance, and therefore run into the diamond problem (your second example), the only way to deal with this properly is to use the C3 linearization - in fact the whole [storage layout mechanism](https://docs.soliditylang.org/en/latest/internals/layout_in_storage.html) is fairly well document, and has been around for a long time - so essentially:

1. There's no other way for us to deal with this - it's simply the way C3 linearization works, and that's how we construct the storage layout
2. I don't see how this would have a devastating effect on protocol upgrades, seeing as it hasn't been an issue thus far.

I'll therefore be closing the issue, since we have no plans to change the storage layout generation in the near future.
