### ISSUE TITLE
Memcpy can fail and is silently ignored

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1469]
`CompilerUtils::memoryCopy()` is used for copying arrays (string, bytes, arrays, etc.)

Currently it uses the identity precompile to accomplish this (it might change, see #1248), but it won't check if the actual call succeeded: https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/CompilerUtils.cpp#L315

Shouldn't it throw if it couldn't copy?

**Comment by chriseth** [comment]
The only way it might fail is due to gas problems. Let's just remove it.

**Comment by axic** [comment]
And if it is run on chain without the precompile.
