### ISSUE TITLE
Interfaces for libraries

### ISSUE THREAD

**Issue by kopy-kat** [ethereum/solidity#14697]
## Abstract

Currently, its not possible for libraries to have interfaces. While one upside of an interface is to be able to call a contract, this is not needed for libraries. Another feature of interfaces is the assurance for a developer that their code implements the required functions. 

## Motivation

I think that being able to easily determine whether a library implements some functions would be very useful, for example, when one has two different versions of the same library that have some differences in functionality but have the same functions.

## Specification

Libraries should be able to inherit from interfaces like so:

`library Example is ILibrary {}`

## Backwards Compatibility

No issues that come to mind

**Comment by nikola-matic** [comment]
HI @kopy-kat. We currently have no plans on investing more time into libraries as we're focusing on the new type system, so I'll be closing the issue.
