### ISSUE TITLE
[Documentation] Why allowing to pass `bytesM` type to param of `bytesN` where `M < N`?

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14692]
## Page

The title sounds complicated, and it is more easily understandable through the code snippet below. (Feel free to change the title of this issue).

If a function accepts for example as a parameter a type of `bytes20` (Here `N` from the title is essentially `20`), why is it possible to pass a smaller `bytesN` type? For instance `bytes4`? The compiler does not give any error.

See the example code below.

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.4;

contract Example {

    bytes10 constant PREFIX = 0xcafecafecafecafecafe;

    function _generateMappingKey(
        bytes10 keyPrefix,
        bytes20 bytes20Value
    ) internal pure returns (bytes32) {
        bytes memory generatedKey = bytes.concat(
            keyPrefix,
            bytes2(0),
            bytes20Value
        );
        return bytes32(generatedKey);
    }

    function generateMappingKey(bytes4 functionSig) public pure returns (bytes32) {
        return _generateMappingKey(PREFIX, functionSig);
    }
}
```

Essentially the type of the parameter `functionSig` above can be changed to any `bytesN` type between `bytes1` and `bytes19`, and it will work and right-pad.

If this is a language design, it would be good imo to document this somewhere in the Solidity documentation under the `bytesN` section.

**Comment by nikola-matic** [comment]
Technically in this case, it should go into the [implicit conversions](https://docs.soliditylang.org/en/latest/types.html#implicit-conversions) section; there are already some examples in the [explicit conversions](https://docs.soliditylang.org/en/latest/types.html#explicit-conversions) section that kind of hints at the behaviour, and describes the semantics of explicit type conversions for fixed sized byte types, where either right side padding will occur (in case you're converting `bytesN` to `bytesM`, where `N<M`), or where `N-M` bytes will be truncated conversely.

If you want to - feel free to open a PR with a short sentence describing the behaviour.

**Comment by CJ42** [comment]
> or where `N-M` bytes will be truncated conversely.

I am not sure to understand the `-` in the quoted example (`N-M`?). But it seems that the other way around, no truncation occurs if `N>M`. Rather the compiler will raises an error, because from my understanding implicit conversion does not allow to truncate, because of the potential loss of information due to the truncation. Only explicit conversion will allow to truncate.

The following example based on above raises an error:

```solidity
    bytes10 constant PREFIX = 0xcafecafecafecafecafe;

    function _generateMappingKey(
        bytes10 keyPrefix,
        bytes20 bytes20Value
    ) internal pure returns (bytes32) {
        bytes memory generatedKey = bytes.concat(
            keyPrefix,
            bytes2(0),
            bytes20Value
        );
        return bytes32(generatedKey);
    }
    
    function generateMappingKey(bytes22 functionSig) public pure returns (bytes32) {
        // Invalid type for argument in function call. Invalid implicit conversion from bytes22 to bytes20 requested.
        return _generateMappingKey(PREFIX, functionSig);
    }
```

**Comment by CJ42** [comment]
I guess the same example used for **explicit conversion**:

<img width="775" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/4ac8f669-8566-493a-a669-b99fcfad7096">

Can be re-used to create an example for the **Implicit conversion** section that does not really mention anything.

<img width="818" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/b1b7adc4-df94-4985-b546-8d9f22f262fc">

As follow:

```solidity
bytes2 a = 0x1234;
bytes4 b = a; // b will be 0x12340000
assert(a[0] == b[0]);
assert(a[1] == b[1]);
assert(b[2] == 0x00);
assert(b[3] == 0x00);
```

**Comment by CJ42** [comment]
One question that this makes me wonder is that the section about **Implicit conversion** states

> _"For more details about which implicit conversions are possible, please consult the sections about the types themselves."_

But in the section for fixed size bytes array, there is no infos about this.

<img width="809" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/10b98fdb-92da-4ad5-aca0-5cb5205883ea">

@nikola-matic do you still suggest to put these explanation in the Implicit conversion section? Or in the section about the type itself?
