### ISSUE TITLE
Array access for strings

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#147]
Should there be a new variable type of `char`?

A string should be able to be treated as an array of chars and .length() should be implemented.

**Comment by chriseth** [comment]
The main problem with this is that strings are sequences of utf-8 encoded characters. This means that they do not really behave like arrays - arrays are lists of elements with equal encoding sizes.
So if you want to change a character inside a string, you might have to shift a large portion of the string - which causes a potentially unexpected impact on the gas usage.

Furthermore, such routines are currently hard to implement in the compiler, but eventually we will have to add support for something like dynamically injected Solidity.

**Comment by VoR0220** [comment]
Nick Johnson's string library handles this. Length is also implemented. You can handle this all via inline assembly. Closing.

**Comment by axic** [comment]
Maybe it is worth considering making string handling a first-class citizen?

At least a complete API should be defined if it is not part of the language, before considering this done.

**Comment by VoR0220** [comment]
@axic there have been talks about this. I think we should consider this once there is a solution for string concatenation. Then I think we would go about it with first class citizenry.
