### ISSUE TITLE
Division and Modulo by Zero does not produce Compiler Error when using shorthand notation /= and %=

### ISSUE THREAD

**Issue by rafaelmohr** [ethereum/solidity#14702]
## Description

When performing a Division or Modulo by Zero using the long notation, the compiler reports the 'Division by Zero' or 'Modulo zero' error. When performing the same operations using the shorthand '/=' or '%=' operators, the compiler does not raise any errors, and instead the operation will cause a revert at runtime.
As the shorthand notation is semantically equivalent to the longer syntax, both should produce the same behaviour.

## Environment

- Compiler version: 0.8.23
- Target EVM version (as per compiler settings): Shanghai
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix VM
- Operating system: macOS 14.1

## Steps to Reproduce

The following two contracts will produce an error on compilation:

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract DivisionByZero {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num = num / 0;
        return num;
    }
}
```
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract ModuloByZero {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num = num % 0;
        return num;
    }
}
```

The following two contracts will compile successfully, and instead revert when calling the function `test()`
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract DivisionByZeroShorthand {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num /= 0;
        return num;
    }
}
```

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract ModuloByZeroShorthand {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num %= 0;
        return num;
    }
}
```

**Comment by AkhilKamath** [comment]
hello, is anyone working on this? if not could you please assign it to me? i would like to work on this, thank you!

**Comment by nikola-matic** [comment]
> hello, is anyone working on this? if not could you please assign it to me? i would like to work on this, thank you!

Hi @AkhilKamath, this one is still under discussion, so please don't start work on this until further notice.

**Comment by gsalzer** [comment]
@nikola-matic @cameel What is the final verdict on this issue? I'd be interested in the pros and cons of treating /=0 and %=0 the same as or different from /0 and %0.
