### ISSUE TITLE
An issue arises when using the `--import-ast` option to process an AST containing inline assembly.

### ISSUE THREAD

**Issue by lum7na** [ethereum/solidity#14707]
## Description

The `--import-ast` option of `solc` is failing to correctly recognize the AST generated by an empty `let` statement.

This bug prevents `solc` from passing the `test/libsolidity/semanticTests/inlineAssembly/inlineasm_empty_let.sol` test case.

## Environment

- Compiler version: commit `7df949edb22598e9d946660020c5390d0ce81bf8`
- Target EVM version (as per compiler settings): `shanghai`

## Steps to Reproduce

1. Generate the AST in JSON format: `solc --combined-json ast inlineasm_empty_let.sol > ast.json`
2. Compile using the `--import-ast` option: `solc --import-ast ast.json`

`solc` should report an error: `Error: Failed to import AST: Expected "nodeType" to be of type string.`

This appears to be due to the `createVariableDeclaration` function in the `libyul/AsmJsonImporter.cpp` file not handling an empty `value` appropriately.

**Comment by matheusaaguiar** [comment]
Hi @lum7na, thanks for your report.
This problem can be triggered by the following minimal code snippet:
```solidity
contract C {
  function f() public pure {
    assembly {
      let x
    }
  }
}
```
You are right, this is a problem with `AsmJsonImporter::createVariableDeclaration`.  The generated `ast` does not have a `value` object associated with the variable and that is not checked against, resulting in a `Json::nullValue` being passed to `AsmJsonImporter::createExpression` where the error originates from.
I think that simply safeguarding against a non-existent `value` object in `AsmJsonImporter::createVariableDeclaration` should be enough to fix this problem.
