### ISSUE TITLE
a everywhere-visible function should be able to override an external function

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1471]
During discussion and experiments with @chriseth, we found a code that should compile but does not currently:

```
$ cat ext-general.sol 
contract B {
                function f() external {}
}

contract D is B {
                function f() {}
}
$ solc/solc ext-general.sol 
Warning: This is a pre-release compiler version, please do not use it in production.
ext-general.sol:1:1: Warning: Source file does not specify required compiler version!
contract B {
^
Spanning multiple lines.
ext-general.sol:6:3: Error: Override changes extended function signature.
                function f() {}
                ^-------------^
```

**Comment by axic** [comment]
Should it though?

If you consider the parent contract an interface, then this changes the interface specification.

**Comment by pirapira** [comment]
I just think it's acceptable if a function becomes internally accessible in a derived contract because that only matters to the implementor of the contract.  @chriseth was, at that moment, saying this should be accepted (though we were in a special mindset after discussing #1084 ).

**Comment by Marenz** [comment]
I assume that the derived `f()` function is meant to be `public` here which was probably a default in earlier versions. With that assumption, the above example works now.

```
contract B {
	function f() external virtual {}
}

contract D is B {
	function f() public override {}
}
```
