### ISSUE TITLE
for loops for assembly

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1472]
Came out of #1320.

Loops should be a native feature of assembly both for ease of use and also for better optimization and analysis abilities. Furthermore, loops are a basic feature of wasm which might be a future backend for solidity.

Proposed syntax:
```
for pre cond post {
 ...
}
```
pre and post can be blocks or single instructions (also in functional notation), cond has to be functional with one return value. Pre already creates a new scope. break and continue are also available inside loops.

Example:
```
// input: start, size
for {let i := 0} lt(i, size) {i := add(i, 1)} {
  mstore8(add(start, i), 0)
}
```

**Comment by bbuenz** [comment]
Is this already implemented? It shows up in the documentation but I can see no other evidence of it being implemented: http://solidity.readthedocs.io/en/develop/assembly.html?highlight=assembly#standalone-assembly

**Comment by chriseth** [comment]
No, this is still work in progress. There is a note about it in the documentation, but not too visible, I have to admit.
