### ISSUE TITLE
Fix or work around broken tests in new analysis

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#14729]
See also https://github.com/ethereum/solidity/pull/14510#issuecomment-1850239073

Remaining fixes before we can have green CI and merge the prototype:
- [x] #14660
- [x] #14659
    - [x] #14726
- [x] #14722
- [x] #14727
- [x] Consistent bytecode report output between CLI and StandardJSON in presence of `UnimplementedFeatureError`.
    - ~IMO we should fix #13925, but there's no consensus that this is the best approach and working around this in `prepare_report.py` will probably be quicker to do.~
    - It was a bug: #14731

**Comment by ekpyron** [comment]
We definitely should **not** waste effort on https://github.com/ethereum/solidity/issues/13925. Why doesn't the filter in ``prepare_report.py`` already cover these cases?

**Comment by cameel** [comment]
I tried hard to avoid `prepare_report.py` having to parse CLI output and fish ICEs out of it. Instead it just checks whether it can find the artifacts. No artifacts == error. The filter is only necessary for Standard JSON to ignore inconsistent artifacts.

But actually, turns out that this was not the cause. The script had a bug - it was not looking at the exit code, which for CLI is another indication that something went wrong. The script originally only handled Standard JSON and there the exit code does not matter. When I was adding CLI support later, I must have forgotten to add a check for that.
