### ISSUE TITLE
How to deploy UUPS upgradeable contract with same addresses in different chains by using creat2|create3 and salt?

### ISSUE THREAD

**Issue by DaoSpirit** [ethereum/solidity#14749]
## Description
Trying to deploy UUPS upgradeable contract to multi evm based chains with same addresses.
I can deploy normal contract with same addresses using create3 and creat2 factory and salt.
Also I can deploy UUP upgradeable contract using **deployProxy**

In addition, how to create UUP upgradeable contracts (e.g. Pool, Vault)  in another smart contract (PoolFactory) which can be upgradeable in the future?

## Environment
- Framework/IDE (e.g. Truffle or Remix): Hardhat & Foundry
- Operating system: Windows10, Ubuntu

```[tasklist]
### Tasks
```

**Comment by r0qs** [comment]
Hi @DaoSpirit, as this is not a compiler issue I will be closing it. Here is not the right place for this type of question. Please feel free to use our [forum](https://forum.soliditylang.org/), the [Ethereum StackExchange](https://ethereum.stackexchange.com/) or our [Matrix Solidity](https://matrix.to/#/#ethereum_solidity:gitter.im) channel for this type of question. You can also refer to [Openzeppelin Proxy patterns documentation](https://docs.openzeppelin.com/upgrades-plugins/1.x/#proxy-patterns) for more information about the upgradable pattern in question.
