### ISSUE TITLE
Running the Fuzzer via AFL.

### ISSUE THREAD

**Issue by Xutp-F** [ethereum/solidity#14761]
description：
cd build
# if needed
make clean
cmake .. -DCMAKE_C_COMPILER=path/to/afl-gcc -DCMAKE_CXX_COMPILER=path/to/afl-g++
make solfuzzer
afl-fuzz -m 60 -i /tmp/test_cases -o /tmp/fuzzer_reports -- /path/to/solfuzzer

issue：
If I want to use afl-cov with afl-fuzz, how do I set the Cmake parameter?

I added the following to CMakeLists.txt:
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fprofile-arcs -ftest-coverage")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage")

But it seems that the solfuzzer did not achieve the piling.
I want guidance. Thanks.

**Comment by Subway2023** [comment]
Did you successfully compile Solidity in the end and use AFL-Cov for code coverage?
