### ISSUE TITLE
Retire suicide and sha3 methods with the next breaking release

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1476]
The preferred way is to use `keccak256` instead of `sha3` and `suicide` was renamed to `selfdestruct` by an EIP.

**Comment by yaronvel** [comment]
Could you make `sha3` a reserved word that no one could use?
Otherwise, one could fool others with a call to dummy `sha3` implementation.

**Comment by chriseth** [comment]
We should probably just warn about these.

**Comment by axic** [comment]
I think it may be better to start issuing warnings instead to avoid the problem of libraries starting to define those functions.

**Comment by roadriverrail** [comment]
If we're just issuing deprecation warnings for calling these functions, put it on my queue.
