### ISSUE TITLE
"error": "Failed to decode output: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ]

### ISSUE THREAD

**Issue by qwe231cvb** [ethereum/solidity#14775]
I wrote a smart contract in the remix development environment, and then deployed the contract in the local test network. I clicked the button with the "LowLevelPlateArmorFragments_addItem" contract function on the left side of the editor, and then the following error was displayed on the right side of the editor，This error occurs after calling the “LowLevelPlateArmorFragments_addItem” contract function:，the error as follows:

"[vm]from: 0x5B3...eddC4to: GameItems.LowLevelPlateArmorFragments_addItem() 0xDA0...42B53value: 0 weidata: 0xf0f...bc9aclogs: 0hash: 0x6c3...28778
Status 0x0 The transaction has been packaged but failed to execute
Transaction Hash 0x6c3358cf556129c9b942e455870c5f74aa666b8aebce93cd8732aaed34c28778
Block hash 0xd045bab08a0998bc409d3e4211a63e6e690ace8773b03c10aac7bbb9ebc31a23
Block number 7
from 0x5B38Da6a701c568545dCfcB03FcB875f56beddC4
to GameItems.LowLevelPlateArmorFragments_addItem() 0xDA0bab807633f07f013f94DD0E6A4F96F8742B53
gas 3000000 gas
Transaction cost 46340 gas
Execution cost 25276 gas
Enter 0xf0f...bc9ac
Decode input {}
decode output {
"error": "Failed to decode output: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"toNumber\" , value=\"3963877391197344453575983046348115674221700746820753546331534351508065746944\", code=NUMERIC_FAULT, version=bignumber/5.7.0)"
}
log	[]"

My contract code is as follows:
````
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.7.0 <0.9.0;

contract GameItems {
    struct LowLevelPlateArmorFragments1 {
        string name;
        address owner;
        uint index;
        uint price;
        string ipfsHash;
    }
    LowLevelPlateArmorFragments1[] public LowLevelPlateArmorFragments;
    uint nonce = 0;
    address contract_owner;
    uint LowLevelPlateArmorFragments_currentIndex = 0;

    constructor() {
        contract_owner = msg.sender;
    }

    event IPFSHashChanged_LowLevelPlateArmorFragments(string newIPFSHash);

    function LowLevelPlateArmorFragments_addItem() public returns (string memory){
        if (LowLevelPlateArmorFragments_currentIndex <= 200000){
            nonce++;
            if (nonce > 20000)
            {
                nonce = 0;
            }
            require((nonce % 3) == 0, "Random event not satisfied");
            address owner = msg.sender;
            uint price = 1;
            string memory name = "LowLevelPlateArmorFragments";
            string memory ipfsHash = "QmcKwm9cQgaipuy9cfdmGX7C5fdJKpic41cqCEBz8QPFR9";
            LowLevelPlateArmorFragments.push(LowLevelPlateArmorFragments1(name, owner, LowLevelPlateArmorFragments_currentIndex, price, ipfsHash));
            LowLevelPlateArmorFragments_currentIndex++; 
            emit IPFSHashChanged_LowLevelPlateArmorFragments(ipfsHash);
            return ipfsHash;
        }
        if (LowLevelPlateArmorFragments_currentIndex > 200000){
            nonce++;
            if (nonce > 20000)
            {
                nonce = 0;
            }
            require((nonce % 3) == 0, "Random event not satisfied");
			require((nonce % 2) == 0, "Random event not satisfied");
            for (uint p = 0; p < LowLevelPlateArmorFragments.length; p++){
                if (LowLevelPlateArmorFragments[p].owner == contract_owner){
                    LowLevelPlateArmorFragments[p].owner = msg.sender;
                    emit IPFSHashChanged_LowLevelPlateArmorFragments(LowLevelPlateArmorFragments[p].ipfsHash);
                    p = LowLevelPlateArmorFragments.length;
                    return LowLevelPlateArmorFragments[p].ipfsHash;
                }
            }
        }
    }

    function getItemsCount() public view returns (uint) {
        return LowLevelPlateArmorFragments.length;
    }

    function getItem(uint index) public view returns (string memory, address, uint, uint) {
        LowLevelPlateArmorFragments1 memory item = LowLevelPlateArmorFragments[index];
        return (item.name, item.owner, item.index, item.price);
    }
}
````

**Comment by nikola-matic** [comment]
This isn't compiler bug - rather, it's likely a bug in the Solidity code you've written, and then possibly a bug in remix/[ethers-js](https://github.com/ethers-io/ethers.js) (although less likely).


`"error": "Failed to decode output: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber" , value="3963877391197344453575983046348115674221700746820753546331534351508065746944", code=NUMERIC_FAULT, version=bignumber/5.7.0)"`

Typically people encounter overflow errors with `bignumber` when they pass large numbers as numbers, rather than string, but this doesn't seem to be the case here. I'd suggest asking help in the ethereum stack exchange.
