### ISSUE TITLE
Extract tests in `test/libsolidity/ViewPureChecker.cpp` to `syntaxTests/viewPureChecker`

### ISSUE THREAD

**Issue by r0qs** [ethereum/solidity#14796]
As suggested by https://github.com/ethereum/solidity/pull/14759#discussion_r1461894555.

**Comment by AbhinavMir** [comment]
I'd love to hop on this! It'll be my first PR here, and had a question re: test running. If I make a new file in `syntaxTests/viewPureChecker` would it be read by the test runner automatically or do I have to add it in some file for it to be indexed?
