### ISSUE TITLE
Enable Discussions In This Repository

### ISSUE THREAD

**Issue by vidhanmangla** [ethereum/solidity#14801]

**Comment by r0qs** [comment]
Thanks @vidhanmangla but we prefer to keep discussions on [our forum](https://forum.soliditylang.org/) and Matrix community channels: [solidity](https://matrix.to/#/#ethereum_solidity:gitter.im) (for general Solidity-related questions and topics) and [solidity-dev](https://app.gitter.im/#/room/#ethereum_solidity-dev:gitter.im) (for questions about the development of the Solidity compiler and language).
