### ISSUE TITLE
Remove EIP-1153 Warning

### ISSUE THREAD

**Issue by jtriley2p** [ethereum/solidity#14817]
## Description

The warning associated with transient storage is hostile towards engineers attempting to use the opcodes given the following context:

Transient storage warning:

```
Warning 2394: (77-83): Transient storage as defined by EIP-1153 can break the composability of smart contracts: Since transient storage is cleared only at the end of the transaction and not at the end of the outermost call frame to the contract within a transaction, your contract may unintentionally misbehave when invoked multiple times in a complex transaction. To avoid this, be sure to clear all transient storage at the end of any call to your contract. The use of transient storage for reentrancy guards that are cleared at the end of the call is safe.
```

Solidity's [documentation](https://docs.soliditylang.org/en/latest/security-considerations.html#take-warnings-seriously) related to compiler warnings:

```md
## Take Warnings Seriously

If the compiler warns you about something, you should change it. [ .. ]
```

Transient storage is an opcode that was accepted into EVM Cancun, it is neither deprecated nor inherently harmful. The debate of its implementation details belong in the forums, not in compiler warnings engineered to push users into using other opcodes.

## Environment

- Compiler version: 0.8.24
- Target EVM version (as per compiler settings): Cancun

## Steps to Reproduce

```solidity
contract C {
    function f() external pure {
        assembly {
            tstore(0, 0)
        }
    }
}
```

**Comment by Neurone** [comment]
Let's ask ChatGPT; what can possibly go wrong? Oh, it suggests solving the issue using a completely made-up `treset` command. An EIP should be written about it. Let's ask ChatGPT; what can possibly go wrong? 😁😁😁 

> Waiting for GPT answer...
>
> The error occurred because the code is using the `tstore` instruction in the Solidity assembly. The `tstore` instruction is part of the EIP-1153 proposal, which introduces transient storage in Solidity. Transient storage is a new type of storage that persists only within a transaction and is not cleared between calls within the same transaction.
> 
> The warning message is stating that the use of transient storage can break the composability of smart contracts. This means that if your contract uses transient storage and is called multiple times within a complex transaction, it may misbehave unintentionally. This is because the transient storage is not cleared at the end of each call within the transaction, but only at the end of the transaction.
> 
> To fix this issue, you need to ensure that all transient storage is cleared at the end of any call to your contract. This means that you should manually clear any transient storage variables or data structures that you have used before the end of your function. This will prevent any unexpected behavior when your contract is invoked multiple times within a transaction.
> 
> In the given code, the `tstore(0, 0)` instruction is storing a value into transient storage, but it is not cleared after that. To fix this, you can add a `treset` instruction after the `tstore` to clear the transient storage. The updated code would look like this:
> 
> ```solidity
> pragma solidity >=0.8.2 <0.9.0;
> 
> contract C {
>     function f() external {
>         assembly {
>             tstore(0, 0)
>             treset()
>         }
>     }
> }
> ```
> 
> By adding the `treset()` instruction, you are explicitly clearing the transient storage after using it. This ensures that the contract behaves correctly even when called multiple times within a transaction.

**Comment by jtriley2p** [comment]
add the following to your `foundry.toml` file and move on.

```toml
ignored_error_codes = [2394]
```

**Comment by kayabaNerve** [comment]
I use solc directly. Anyone able to chime in how I can ignore this/want to additionally argue removal/advocate for comment-based warning disabling (`// warnings: allow(2394)`)?

This isn't me being a pedant about having no warnings. Because solc exits with 0 even when compilation fails, I'm checking if stderr has messages to detect build failures. Since warnings are printed to stderr, I now have to parse the text-based stderr (which I do see I can get as JSON) to detect if there are actually errors which is a notable headache.

**Comment by frangio** [comment]
For Hardhat, `npm install hardhat-ignore-warnings`, then
```diff
 // hardhat.config.js

+require('hardhat-ignore-warnings');

 module.exports = {
+  warnings: {
+    'transient-storage': 'off',
+  },
 };
```

**Comment by jtriley2p** [comment]
man remember this

good times

**Comment by johnson86tw** [comment]
> add the following to your `foundry.toml` file and move on.
> 
> ignored_error_codes = [2394]

Ah, this doesn't work for me..
