### ISSUE TITLE
Donating Funds to Solidity

### ISSUE THREAD

**Issue by Lfada** [ethereum/solidity#14848]
Hi Solidity maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[Zoltu/Deterministic-deployment-proxy](https://github.com/Zoltu/deterministic-deployment-proxy)(https://github.com/Zoltu/deterministic-deployment-proxy) has been using https://github.com/ethereum/solidity. It's in fact one of their most critical dependencies!

Zoltu core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @chriseth @axic @cameel @danielhams @leonardoalt

**Comment by franzihei** [comment]
Hi @Lfada, Thanks for reaching out! Do you have any documentation or guides for teams on how to treat drips tax-wise and how to do accounting for this type of financial support? We would need to figure this out first, before we can receive such a type of donation.

**Comment by Lfada** [comment]
Hi @franzihei, we cannot give any docs or guides, I would suggest talking to a lawyer, or accountant to figure things out.

 What I can do is give you a bit more context around the whole thing. This is part of a Dependency Funding initiative to donate/support FOSS repositories. 

What Drips allows you to do, is claim the donations and then split them into your critical dependencies and/or amongst other maintainers. A great example is Ethers.js, which is splitting 40% of all incoming funds to their dependencies as you can see [here](https://www.drips.network/app/projects/github/ethers-io/ethers.js).

[Here's](https://www.drips.network/app/projects/github/ethereum/solidity?exact) Solidity profile in Drips. A maintainer/admin of this GH repo would need to claim the profile to retrieve the funds.

For a step-by-step guide on the claim process, watch [this video](https://www.youtube.com/watch?v=AOl_XkgWv-A) and for more detailed information, [here](https://docs.drips.network/claim-your-repository/) you can find the docs.
