### ISSUE TITLE
Multiple _ within a function modifier lead to incorrect behavior when via-ir is enabled

### ISSUE THREAD

**Issue by lum7na** [ethereum/solidity#14853]
## Description

Hi! I'm having some problems with the `via-ir` option.

When the `via-ir` option is enabled, multiple occurrences of `_` within a function modifier lead to incorrect behavior.

## Environment

- Compiler version: 0.8.24
- Framework/IDE (e.g. Truffle or Remix): Foundry
- Operating system: Debian

## Steps to Reproduce

Minimal:

```solidity
contract C {
    modifier modi() {
        _;
        _;
    }
    function f() public modi returns (uint256 x) {
        x = x + 1;
    }
}
```

When `via-ir` is not enabled, the return value of the function is 2.

**Comment by cameel** [comment]
Yes, that's intentional. See [Solidity IR-based Codegen Changes > Semantic Only Changes](https://docs.soliditylang.org/en/latest/ir-breakin-changes.html#semantic-only-changes):
> Function modifiers are implemented in a slightly different way regarding function parameters and return variables. This especially has an effect if the placeholder `_;` is evaluated multiple times in a modifier. In the old code generator, each function parameter and return variable has a fixed slot on the stack. If the function is run multiple times because `_;` is used multiple times or used in a loop, then a change to the function parameter’s or return variable’s value is visible in the next execution of the function. The new code generator implements modifiers using actual functions and passes function parameters on. This means that multiple evaluations of a function’s body will get the same values for the parameters, and the effect on return variables is that they are reset to their default (zero) value for each execution.
