### ISSUE TITLE
Enable function overloading resolution when importing specific libraries or free functions via `using for`

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14879]
## Abstract

In Solidity, the `using ... for ...` syntax enables to load specific functions instead of the whole library, as stated by the documentation.

For instance for the following library with 2 overloaded functions.

```solidity
library LSP2Utils {

    function generateMappingKey(
        string memory firstWord,
        string memory lastWord
    ) internal pure returns (bytes32) {
        bytes32 firstWordHash = keccak256(bytes(firstWord));
        bytes32 lastWordHash = keccak256(bytes(lastWord));

        bytes memory temporaryBytes = bytes.concat(
            bytes10(firstWordHash),
            bytes2(0),
            bytes20(lastWordHash)
        );

        return bytes32(temporaryBytes);
    }

    function generateMappingKey(
        string memory firstWord,
        address addr
    ) internal pure returns (bytes32) {
        bytes32 firstWordHash = keccak256(bytes(firstWord));

        bytes memory temporaryBytes = bytes.concat(
            bytes10(firstWordHash),
            bytes2(0),
            bytes20(addr)
        );

        return bytes32(temporaryBytes);
    }
    
    function generateMappingKey(
        bytes10 keyPrefix,
        bytes20 bytes20Value
    ) internal pure returns (bytes32) {
        bytes memory generatedKey = bytes.concat(
            keyPrefix,
            bytes2(0),
            bytes20Value
        );
        return bytes32(generatedKey);
    }
    
}
```

In a contract, the 3rd function cannot be imported with the following syntax:

```solidity
// pragma and import statements omitted for brevity

contract Example is {
 
    using {LSP2Utils.generateMappingKey} for bytes10;

}
```

This generates the following error:

```
Identifier is not a function name or not unique.
```

## Motivation

Enable to write functions with same name, and load specific ones in a `library`. This prevents from having to refactor the code to change all functions names, which can break compatibility for code bases that are already using some of these overloaded functions.

## Specification

To Be Defined. How to specify which function signature to load via `using for`?

**Comment by cameel** [comment]
This is a known limitation and a more general issue, not limited to just `using for`: #3556. Unfortunately we probably won't get to this before we ship the new type system. It will affect the language syntax and the future of overloading in the language and the solution we'll choose will heavily depend on those.
