### ISSUE TITLE
build solidity error

### ISSUE THREAD

**Issue by cqray1990** [ethereum/solidity#14894]
enviroment :
ubantu 20.04
gcc g++ version 9.4.0

solidity/0.4.24-45713c02581/libsolidity/inlineasm/AsmParser.cpp:609:7: error: unnecessary parentheses in declaration of ‘_literal’ [-Werror=parentheses]
  609 |   u256(_literal);

**Comment by laumeng** [comment]
Try changing to centos

**Comment by smallerxuan** [comment]
Check your compiler version

**Comment by r0qs** [comment]
Closing as it appears to be a duplicate of https://github.com/ethereum/solidity/issues/14752. Please refer to https://github.com/ethereum/solidity/issues/14752#issuecomment-1869588087 to provide further details. If you have additional information regarding the error, please feel free to reopen the issue.
