### ISSUE TITLE
Security vulnerability: Why do % and MOD result in different outputs despite being technically the same function?

### ISSUE THREAD

**Issue by milaabl** [ethereum/solidity#14925]
Writing a ^0.6.0 test, I noticed a bug which gives unexpected results for the operation of getting the `remainder` of a `modulo` function. That bug only occurs when the operands are integers of different bit representation types.

Consider the following example:

```solidity
pragma solidity ^0.6.0;

contract Test {
    function moduloPlain() external view returns (uint256 result) {
        uint8 _maxNumber = uint8(1000);
        uint256 _pseudoRandomNumber = 2345200000000000000000000000000000000000000000000000000000000000000000003;
        result = (_pseudoRandomNumber % _maxNumber) + 1;
    }

    function moduloAssembly() external view returns (uint256 result) {
        uint8 _maxNumber = uint8(1000);
        uint256 _pseudoRandomNumber = 2345200000000000000000000000000000000000000000000000000000000000000000003;
        assembly {
            result := add(mod(_pseudoRandomNumber, _maxNumber), 1)
        }
    }
}
```

I'm running this on RemixIDE.

**This results in the following:**

![unexpected-result-solidity-modulo-1](https://github.com/ethereum/solidity/assets/86361434/34768b90-bf2d-4f30-98e1-e3d5e38a447e)

However, this gives a correct, expected result:

```solidity
pragma solidity ^0.6.0;

contract Test {
    function moduloPlain() external view returns (uint256 result) {
        result = (2345200000000000000000000000000000000000000000000000000000000000000000003 % 1000) + 1;
    }

    function moduloAssembly() external view returns (uint256 result) {
        uint8 _maxNumber = uint8(1000);
        uint256 _pseudoRandomNumber = 2345200000000000000000000000000000000000000000000000000000000000000000003;
        assembly {
            result := add(mod(_pseudoRandomNumber, _maxNumber), 1)
        }
    }
}
```

![expected-result-on-the-contrary](https://github.com/ethereum/solidity/assets/86361434/1f721e5b-17d2-423e-9142-6b7102a2bf8f)

**Could you please confirm that it's a bug?**

**Comment by crystalbit** [comment]
You put 1000 into `uint8`, maybe here is the difference

**Comment by milaabl** [comment]
> You put 1000 into `uint8`, maybe here is the difference

Oh, la vache! Thank you, you opened my eyes!! That explains why the assembly function works though, it's getting the whole value even if it's an underflow on the higher-level. Merci. Closing this issue.
