### ISSUE TITLE
Add definitions for tuples in grammar.txt

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#1493]
I am working in [ConsenSys/solidity-parser](https://github.com/ConsenSys/solidity-parser) and some definitions for how to handle tuples would be very useful for this and other parsers.

**Comment by chriseth** [comment]
Tuples are part of the grammar:

https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt#L67 and
https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt#L82

What information do you specifically need?

**Comment by federicobond** [comment]
You are right, what is missing is the definition of tuples as lvalues though. Specifically, in the [VariableDeclaration](https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt#L38) rule.
