### ISSUE TITLE
Reduce default font weight for readability

### ISSUE THREAD

**Issue by RaoulSchaffranek** [ethereum/solidity#14942]
## Page

The entire Solidity docs. Example: https://docs.soliditylang.org/en/v0.8.25/

## Abstract

The texts in the Solidity documentation are all rendered with a bold font face.
This makes it hard to read and emphasized content is no longer recognizable as such.

IS (`font-weight: 400`)

![bold](https://github.com/ethereum/solidity/assets/1412344/ea47efba-1b59-403e-b6c2-0f08134f3426)

SHOULD (`font-weight: 200`):
![not-so-bold](https://github.com/ethereum/solidity/assets/1412344/79ee6a2b-c8ef-4598-985d-70916d39cd89)

## Pull request

I'm not sure where the corresponding stylesheet is coming from. The browser dev tools indicate that it must be a file named `theme.css`, but I cannot find it in this repository.

**Comment by edurivara** [comment]
I changed the default body font weight from 400 to 200 at the toggle.css (as per specified on the conf.py: html_css_files = ["css/toggle.css"])
Created a pull request (https://github.com/ethereum/solidity/pull/14944)

**Comment by franzihei** [comment]
See my comment in the PR here https://github.com/ethereum/solidity/pull/14944#pullrequestreview-1947555972

I would not change the font weight for the reasons mentioned in my comment. Thus, from my perspective, we can close this issue and the associated PR.
