### ISSUE TITLE
SMT logic error for bitwise operators

### ISSUE THREAD

**Issue by alex1448** [ethereum/solidity#14959]
## Description

The following code triggers the exception shown bellow, which happens for all three bitwise operators. The problem seems to appear with version ```0.8.10```.

## Steps to Reproduce

```testcase.sol```

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity =0.8.25;

contract C {
    function f(int[10] memory p) public pure {
        1 ^ p[0];
    }
}
```

```
solc testcase.sol --model-checker-engine all
```

```
SMT logic error:
./libsmtutil/Z3Interface.cpp(390): Throw in function solidity::smtutil::Expression solidity::smtutil::Z3Interface::fromZ3Expr(const z3::expr&)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: SMT assertion failed
[solidity::util::tag_comment*] = SMT assertion failed
```

## Environment

- Compiler version: ```>=0.8.10```

**Comment by r0qs** [comment]
Hi @alex1448, thank you for raising the issue. It appears that the [smtAssert(false)](https://github.com/ethereum/solidity/blob/develop/libsmtutil/Z3Interface.cpp#L390) is triggered when utilizing `chc` as the model checker engine option. Interestingly, this error does not manifest when using the `bmc` engine.

The `kind` of the generated Z3 expression seems to be interpreted as a [Z3_OP_CONCAT](https://github.com/Z3Prover/z3/blob/c18a42cf5b0db2f45475ff84266237e10a361a72/src/api/z3_api.h#L336), i.e. bit-vector concatenation, which, to the best of my knowledge, is currently unsupported by `Z3Interface::fromZ3Expr`. Perhaps @blishko has insights into this issue and suggestions for addressing it.

**Comment by pgebal** [comment]
> Hi @alex1448, thank you for raising the issue. It appears that the [smtAssert(false)](https://github.com/ethereum/solidity/blob/develop/libsmtutil/Z3Interface.cpp#L390) is triggered when utilizing `chc` as the model checker engine option. Interestingly, this error does not manifest when using the `bmc` engine.
> 
> The `kind` of the generated Z3 expression seems to be interpreted as a [Z3_OP_CONCAT](https://github.com/Z3Prover/z3/blob/c18a42cf5b0db2f45475ff84266237e10a361a72/src/api/z3_api.h#L336), i.e. bit-vector concatenation, which, to the best of my knowledge, is currently unsupported by `Z3Interface::fromZ3Expr`. Perhaps @blishko has insights into this issue and suggestions for addressing it.

That's right. I'm fixing this.  I wish I've seen your comment earlier. I had to go over it myself.
