### ISSUE TITLE
Abnormal execution time of the SMTChecker

### ISSUE THREAD

**Issue by lum7na** [ethereum/solidity#14966]
## Description

Hello! I encountered some issues while using the SMTChecker. On the following code, the SMTChecker requires 8 minutes to complete execution. I believe this is an abnormal execution time.

```solidity
contract C {
  enum X { A, B }

  X public x;

  function f() public returns(uint256) {
    X c = X.A;
    uint256 a = 1;
    uint256 b = a / a;
    a = a - a;
    b = (b + a / b) >> 1;
    a = a + a + a;
    a += a * a / a;
    if (a > a) a = a + (a - a);
    x = c;
    return 1;
  }

  function g() public returns(uint256) {
    x = X.A;
    return 1;
  }

}
```

By changing the order of statements without altering the semantics, the SMTChecker quickly finishes execution and produces the same output. 

```solidity
contract C {
  enum X { A, B }

  X public x;

  function f() public returns(uint256) {
    uint256 a = 1;
    uint256 b = a / a;
    X c = X.A;
    a = a - a;
    b = (b + a / b) >> 1;
    a = a + a + a;
    a += a * a / a;
    if (a > a) a = a + (a - a);
    x = c;
    return 1;
  }

  function g() public returns(uint256) {
    x = X.A;
    return 1;
  }

}
```

Additionally, the SMTChecker provided a counterexample, which did not appear in the results of the first code. Is this because the SMTChecker spent a lot of time searching for a counterexample?

## Environment

- Compiler version: 0.8.25

## Steps to Reproduce

`solc --model-checker-engine all a.sol`

**Comment by aman85662** [comment]
Please try this and tell me the result.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;
 contract C {
  enum X { A, B }

  X public x;

  function f() public returns(uint256) {
    uint256 a = 1;
    uint256 b = a / a;
    X c = X.A;
    a = a - a;
    b = (b + a / b) >> 1;
    a = a + a + a;
    a += a * a / a;
    if (a > a) a = a + (a - a);
    x = c;
    return 1;
  }

  function g() public returns(uint256) {
    x = X.A;
    return 1;
  }

}

**Comment by lum7na** [comment]
Hi, after checking the code and recompiling solc I finally realized that this is a z3 bug. i will close this issue.
