### ISSUE TITLE
IR-based Code Generator truncates overflow values, resulting in inconsistent variable values.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#14987]
## Description

When assigning a value using assembly that exceeds the variable type range, it gets truncated by the IR-based Code Generator, causing inconsistency in bytecode execution compared to the bytecode generated by the regular Code Generator.

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE: Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```solidity
contract C {
    function f() public returns (uint256) {
        uint16 x = 0xffff;
        uint8 y = uint8(x);
        uint256 r;
        assembly {
            r := y
        }
        return r;
    }
}
```
### Four compilation modes
origin, optimize, viaIr, optimize-viaIr. Specific configuration details can be found at the [four compilation configuration ](https://github.com/ethereum/solidity/issues/14982)
#### origin/optimize
![1712240492145](https://github.com/ethereum/solidity/assets/147013944/184c7bf7-c17e-4356-91c4-1128973fd807)
#### viaIr and optimize-viaIr
![image](https://github.com/ethereum/solidity/assets/147013944/4196aab0-48ea-46c0-b734-4ae865e02e5b)

Due to the fact that IR-based Code Generator truncates overflow values, the return value of **f()** is different in different compilation modes.

**Comment by mehtavishwa30** [comment]
Hey @Subway2023!

This result is due to the difference in the old codegen and the IR-based codegen cleanup sequence and is not a bug. See for the instance [the Cleanup example in the Solidity docs](https://docs.soliditylang.org/en/develop/ir-breaking-changes.html#cleanup) to understand this better.

Hence, I will be closing this issue. :)

**Comment by Subway2023** [comment]
```
uint8 y = uint8(x);
```
Why does the mandatory conversion here fail.
