### ISSUE TITLE
Incorrect `src` start position in ast.

### ISSUE THREAD

**Issue by minhnn32** [ethereum/solidity#14984]
## Description

Hi, I was trying to align the the ast and the source code using the `src` key in the ast.

From my understanding, the `src` follows the following format "\<start\>:\<length\>:\<index\>" where \<start\> indicates the start position (starts from 0) of the node and \<length\> is the length in terms of character of the node.

However, when I tried with certain source code, the ast generated have correct \<length\> but incorrect \<start\> position.

Here is an example:

The solidity source code file:
[buggy_31.txt](https://github.com/ethereum/solidity/files/14863282/buggy_31.txt)

I changed the solidity version with:
```
solc-select --always-install use 0.5.11
```

And then I compiled with the following command:
```
solc buggy_31.sol --ast-compact-json -o buggy_31
```

Here is the ast it generated:
[buggy_31.sol_json.txt](https://github.com/ethereum/solidity/files/14863312/buggy_31.sol_json.txt)

The `src` of function `claimReward_TOD38` from the ast is `"4078:203:0"`, however when I check it using Python, it returns the following:

```python
with open("./data/solidifi_buggy_contracts/front_running/buggy_31.sol", 'r') as f:
    buggy_contract = f.read()
    
print(buggy_contract[4078 : 4078 + 203])
> "ction claimReward_TOD38(uint256 submission) public {
        require (!claimed_TOD38);
        require(submission < 10);

        msg.sender.transfer(reward_TOD38);
        claimed_TOD38 = true;
    }
  "
```

Apparently the `src` \<start\> position of this function was shifted by 3 characters to the right.

**Comment by r0qs** [comment]
Hi @minhnn32, your code example has Unicode characters in comments, which occupies more than one byte per character. For instance, see this comment in your code: `// the valid range for s in (281): 0 < s < secp256k1n ÷ 2 + 1, and for v in (282): v ∈ {27, 28}. Most`

The Unicode character `∈` occupies 3 bytes and `÷` occupies 2 bytes when encoded in UTF-8. You can check it with: `print(len('∈'.encode('utf-8')))`. 
Your current method of accessing the source location would work for this example if you remove those Unicode characters from the source code. However, please note that the `src` field of the AST output returns the source location in bytes, *not* the position based on number of characters. This distinction becomes significant when dealing with Unicode characters in the source code.

Please, see our documentation for further information about source mappings: https://docs.soliditylang.org/en/v0.8.25/internals/source_mappings.html#source-mappings. I.e.:
```
Format: s:l:f
Where s is the byte-offset to the start of the range in the source file, l is the length of the source range in bytes and f is the source index mentioned above.
```

Therefore, a more reliable approach to reading the file would be something like:
```python
with open("./buggy_31.sol", 'r') as f:
    f.seek(4078)
    buggy_contract = f.read(203)

print(buggy_contract)
```

Thus, this is not actually a bug in the compiler ;)

**Comment by minhnn32** [comment]
Thank you very much. I misinterpreted the 'src' as character position. It should be byte position.
