### ISSUE TITLE
Implement abi.decodeWithSelector 

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/solidity#14996]
This is a potential re-opening of https://github.com/ethereum/solidity/issues/9439, and it may also be a request to implement converting `bytes memory slice` -> `bytes memory`.

## Abstract

Adding an `abi.decodeWithSelector` will make it easier to decode data encoded with a function selector, which is relatively common in the EVM ecosystem. 

If you could convert to a `bytes memory slice` from a `bytes memory` and only from `bytes calldata`, this would be trivially easy to do, but at the moment, you cannot. However, adding such a feature requires a lot more "stuff" under the hood than just adding an `abi.decodeWithSelector` function (I think). 

## Motivation

Let's say I have the task of extracting data from a `bytes memory` object without the first four bytes. Additionally, grabbing the first four bytes (the function selector) from a `bytes memory` object. According to [this issue](https://github.com/ethereum/solidity/issues/3876#issuecomment-722233624) and the [language design issue](https://github.com/ethereum/solidity/issues/9439) this can typically be accomplished as such:

```javascript
(uint256 a, string memory b) = abi.decode(abi.encodePacked(data[4:]), (uint256,string));
```

However, this comes with some assumptions:

1. The `data` object must be `bytes calldata` and not bytes memory. 
2. The data was encoded with `abi.encode` and not `abi.encodeWithSelector`

### 1. The `data` object must be `bytes calldata` and not bytes memory

Yes. You can only make a bytes slice on `calldata`. They do not work on `memory`. The following will not compile:

```javascript
function encodeBytes4(bytes memory myData) public pure{
        myData[4:];
    }
```

You'll get:
```
TypeError: Index range access is only supported for dynamic calldata arrays.
```

### 2. The data was encoded with `abi.encode` and not `abi.encodeWithSelector`

`abi.encodeWithSelector` prepends the function selector to the start of the result. However, this can be a bit misleading. If you encode some data with a function selector and then go to decompile it, you'll end up running into an EVM revert because `abi.decode` doesn't expect an odd 4-byte object. 

```javascript
    function encodeBytes4() public pure returns(bytes memory){
        bytes4 selector = hex"60606060";
        return(abi.encodeWithSelector(selector));
    }

    // This compiles fine, but if you run it, it will result in an EVM revert 
    function decodeBytes4() public pure returns(bytes4){
        return abi.decode(encodeBytes4(), (bytes4));
    }
```

This seems... odd. But ok. 

So, if I want to separate the function selector from the data in my `memory` bytes object, I have to do this:

```javascript
function doStuff(bytes memory myData) public pure returns(bytes memory, bytes4){
        uint256 BYTES4_SIZE = 4; 
        uint256 bytesSize = myData.length - BYTES4_SIZE;
        bytes memory dataWithoutSelector = new bytes(bytesSize);
        for (uint8 i = 0; i < bytesSize; i++) {
            dataWithoutSelector[i] = myData[i + BYTES4_SIZE];
        }
        bytes4 selector = bytes4(myData);
        return (dataWithoutSelector, selector);
}
```

Which seems... janky. 

## Specification

Have the first return be the selector of the decoding. The API could look like such:

```javascript
(bytes4 selector, type, type,...) = abi.decodeWithSelector(data, (selector, type, type...)
```

One could argue you could just do `abi.decodeWithSelector(data, (type, type...)` since it's assumed that if you're using `abi.decodeWithSelector` that the first response would be a `bytes4` object.

## Backwards Compatibility

Since this is a new feature, it shouldn't affect anything else.

**Comment by Assawal** [comment]
пн, 8 квіт. 2024 р., 01:05 користувач Patrick Collins <
***@***.***> пише:

**Comment by Assawal** [comment]
пн, 8 квіт. 2024 р., 04:52 користувач Assawal ***@***.***>
пише:

**Comment by mehtavishwa30** [comment]
Hey @PatrickAlphaC! Thanks for your proposal.

We believe that the new standard library should enable developers to implement features such as the one proposed with relative ease in the future.

Additionally, working on the issue about implementing [support for array slicing for dynamic calldata arrays](https://github.com/ethereum/solidity/issues/7423) (memory and storage) is still on the roadmap. It would make most sense currently for the team to address the underlying problem regarding decoding data by implementing support for the array slicing issue.

I will be closing the issue on these grounds. Feel free to [join us for a discussion on matrix](https://matrix.to/#/#ethereum_solidity-dev:gitter.im) if you have any further questions or ideas.
