### ISSUE TITLE
solc: Fallback functions incorrectly allowed to have a return type

### ISSUE THREAD

**Issue by LianaHus** [ethereum/solidity#15]
(moved) see original issue here: https://github.com/ethereum/cpp-ethereum/issues/2828

**Comment by nmushegian** [comment]
propose to reclassify as official feature, which will be usable when this is done:  https://github.com/ethereum/solidity/issues/15

**Comment by chriseth** [comment]
Ok, as it _is_ possible to access the input via `msg.data`, I guess it would be fair to allow the fallback function to return something. As the idea of the fallback function is to be called whenever the signature check failed, it can act as emulating several functions with different types. So it would make sense to let its internal return type be `bytes`, but the data is encoded as `(bytes)` but just taken raw, i.e. without the (0x20, length)-prefix.

**Comment by chriseth** [comment]
As we now have inline assembly, I would prefer not to allow the fallback function to return data. If you must return data, you have to use inline assembly.
