### ISSUE TITLE
Proposed dockerfile changes

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1500]
1. I'm requesting that https://hub.docker.com/r/ethereum/solc/tags/ be utilized when releasing from now on. Each time that a release is made, the version should be tagged into the docker image. 

2. If at all possible, it would be nice to have solc released on apk in alpine. 

That is all. 1. should be more than doable (I'll help write the test script if I have to). 2. is a nice to have, but not required. 

Let me know what thoughts are surrounding this.

**Comment by chriseth** [comment]
That was the plan. We just did not have a release after the dockerfile was included into develop.

**Comment by VoR0220** [comment]
:DDDD

**Comment by chriseth** [comment]
Should be working now.

**Comment by VoR0220** [comment]
problem is that it's only designated into "stable"-"nightly"....needs an exact "version" tag every time we make a commit to develop....yes it will clog it up slightly, BUT...definitely needed for verification of compiler version.
