### ISSUE TITLE
Mapping EVM code back to source code to facilitate program analysis on bytecode-level

### ISSUE THREAD

**Issue by wuestholz** [ethereum/solidity#1501]
I'm working on program analysis for EVM bytecode and it would be very useful to be able to map errors on in the bytecode back to errors in the source code (e.g., written in Solidity).

One way to achieve this would be to record some additional information during compilation. For instance, in .Net .pdb-files are used for this purpose. I was thinking it might be nice to support something similar for Solidity by, for instance, producing a JSON output like this:

```
{
    Instructions: [ { Offset: K, SourceLine: N, SourceColumn: M, SourceFile: "foo.sol", SourceExpression: "a + b" } ... ],
    Compiler: "solc",
    Version: "X.Y",
    Code: [ { Filename: "foo.sol", Code: "..." } ... ]
}
```

The instruction mapping is crucial, but the other meta data might also be useful to produce optionally.

It would be great to hear if others would also find this useful and if there are other or easier ways to achieve this.

**Comment by VoR0220** [comment]
You may want to look at the json file input/output metadata issue that is being talked about. Though the mapping of instructions hasn't been brought up, and that might be useful...maybe.

**Comment by chriseth** [comment]
This one should help you: https://solidity.readthedocs.io/en/develop/miscellaneous.html#source-mappings

**Comment by wuestholz** [comment]
@chriseth Great! That should do. Thank you very much for the pointer.
