### ISSUE TITLE
SMTChecker: Unable to accurately determine the correctness of operations following assembly code

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15019]
## Description
SMTChecker: Unable to accurately determine the correctness of operations following assembly code

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Command-line
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce
```
solc C.sol --model-checker-engine all
```

```solidity
contract C {
  uint256 s;
  function f() public returns (uint256 ret) {
      s=1;
      assembly {
          ret := sload(s.slot)
      }
      assert(ret==1);
  }
}
```
![1712928877382](https://github.com/ethereum/solidity/assets/147013944/98bb50db-7962-4c6b-8029-9254c62e3c72)

```solidity
contract C {
  uint[] myArray;
  
  function f() public {
      assembly{
          sstore(0,1)
      }
      myArray.pop();
  }
}
```
![1712928972967](https://github.com/ethereum/solidity/assets/147013944/6b07a00d-29ba-4449-b337-c7284c4d4acf)

**Comment by blishko** [comment]
SMTChecker is currently not able to analyze inline assembly, so it is over-approximating possible behaviours. Basically it assumes that anything could have been changed.

You should see the warning
```
Warning: SMTChecker: 1 unsupported language feature(s). Enable the model checker option "show unsupported" to see all of them.
```

And if you run with `--model-checker-show-unsupported`, you will see more details.
```
Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
 --> test.sol:5:7:
  |
5 |       assembly {
  |       ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by Subway2023** [comment]
May I ask if SMTChecker will support inline assembly in the future

**Comment by blishko** [comment]
If someone will implement it then yes :)
But at the moment, there are no concrete plans regarding this feature.
