### ISSUE TITLE
SMTChecker: Unable to accurately determine the value of an empty array

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15016]
## Description

When performing a push() operation on an empty array, SMTChecker is unable to correctly determine that its value is 0

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Command-line
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce
```solidity
contract C {
  bytes s;
  function f() public {
      s.push();
      assert(s[0]==0x0);
  }
}
```

```
solc C.sol --model-checker-engine bmc
```
![1712927475832](https://github.com/ethereum/solidity/assets/147013944/792ef904-a17a-4155-a60a-376d48e53d10)

**Comment by blishko** [comment]
BMC engine does not work with the state of the contract, it only analyzes functions locally, so it cannot verify this assertion.
CHC engine is more powerful and can verify this example successfully.

**Comment by Subway2023** [comment]
Will BMC support state of the contract in the future

**Comment by blishko** [comment]
Most likely no.
The recommendation is to use CHC engine, which should be more powerful in almost most cases.
