### ISSUE TITLE
grammar.txt is not correct with respect to identifiers starting with $

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1502]
`grammar.txt` has `Identifier = [a-zA-Z_] [a-zA-Z_0-9]*`.  However, the implementation allows an identifier `$x`.

**Comment by axic** [comment]
Should we allow identifiers with `$` though?

`grammar.txt` should be fixed, but I would be inclined to say that next breaking release, that should be removed. It is a JavasScript-ism 😉

**Comment by chriseth** [comment]
I think dollars are fine, although I would not go all the way down [swift went](http://www.globalnerdy.com/2014/06/03/swift-fun-fact-1-you-can-use-emoji-characters-in-variable-constant-function-and-class-names/)

**Comment by axic** [comment]
Why should dollar variables be used?

**Comment by pirapira** [comment]
#1576 uses `_` and `$` to encode complicated structure in an identifier.

**Comment by axic** [comment]
Looks horrible to be honest 😉
