### ISSUE TITLE
NEED HELP FOR DEPLOYING SMARTCONTRACT

### ISSUE THREAD

**Issue by vein451** [ethereum/solidity#15065]
Hello, im having issue deploying this contract, what should i edit with this params

![image](https://github.com/ethereum/solidity/assets/108234086/710570f3-4c17-40c8-b503-15bd74dd8900)

**Comment by r0qs** [comment]
Hi @vein451, this isn't the appropriate place for seeking assistance with deploying contracts. Please direct general Solidity-related questions and discussions to [our forum](https://forum.soliditylang.org/) or the [Matrix community channel](https://matrix.to/#/#ethereum_solidity:gitter.im).
