### ISSUE TITLE
Segmentation fault when assigning to a parenthesized non-tuple expression of a tuple type

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15075]
## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: Command
- Operating system: Linux

## Steps to Reproduce
```solidity
contract A {
    function f ( ) internal virtual {
        ( ( f() ) -= f() ) [ f() ] ;
    }
}
```
Segmentation fault

**Comment by r0qs** [comment]
Hi @Subway2023 thanks for opening the issue. We are indeed incorrectly detecting assignments to empty tuple expressions. I opened a PR to fix it ;)

A simpler reproduction of the bug would be:
```solidity
contract C {
    function f() {
        (f()) = ();
    }
}
```

**Comment by cocohearts** [comment]
is this suitable for first issue? i'd like to contribute to fix this, suggestions from @cameel @r0qs ?
