### ISSUE TITLE
Scheme to allow returning `bytes` and `string` between contracts

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#1509]
My understanding is that this is currently not allowed because the length of the returned value is unknown so the caller cannot pre-allocate the *proper* amount of memory for the return value.  I propose the following scheme to enable this functionality.

```
contract Returner {
    string value;
    function returnString() constant returns (string) {
        return value;
    }
}

contract Getter {
    Returner other;
    function getString() {
        var theValue = other.returnString();
        ... // Do something with it.
    }
}
```

The RLP encoding for `bytes` and `string` values begins with a 32 byte representation of the length of the value followed by the actual bytes of the value padded to a multiple of 32 bytes.

In order to retrieve a string solidity would compile the code above to perform the following actions.

1. Call the `returnString` function only allocating 32 bytes for the return value.
2. Read the length of the string from the returned value.
3. Call the `returnString` function again, this time allocating the total necessary space for the returned value (as derived from the previous steps)

This assumes that the EVM will gracefully allow the called contract to try and write more return bytes than have been allocated *and* that when this happens that the first bytes written are preserved and still returned.

This also assumes that the act of retrieval does not modify the returned value.

Could this work?

**Comment by chriseth** [comment]
I think this is extremely dangerous since the called function might have side-effects. Let's wait for metropolis, where we hopefully have EIP-5 implemented.

**Comment by pipermerriam** [comment]
Fair point.  At least I now know it's possible :)
