### ISSUE TITLE
Boost 1.65 is not compatible

### ISSUE THREAD

**Issue by guidanoli** [ethereum/solidity#15117]
## Page

[Installing the Solidity Compiler — Solidity 0.8.24 documentation](https://docs.soliditylang.org/en/v0.8.24/installing-solidity.html#prerequisites-all-operating-systems)

## Abstract

The page states that Solidity v0.8.24 can be compiled with Boost 1.65, however, I was not able to.
Apparently, it has something to do with the `boost/container_hash` library, which is imported [here](https://github.com/ethereum/solidity/blob/028cf3309437819503a37f60bfa8aad2af7fb9b7/libevmasm/ExpressionClasses.cpp#L31).
This module was only available in Boost 1.67, apparently.
See the [changelog](https://www.boost.org/doc/libs/1_81_0/libs/container_hash/doc/html/hash.html#changes_boost_1_67_0) on Boost documentation.

**Comment by nikola-matic** [comment]
Yup, looks like we introduced `boost/container_hash` in 2022 and did not update the docs.

**Comment by guidanoli** [comment]
Not assigning responsibilities or anything, but this would be caught if there were a CI that tried to build with the dependencies in the oldest supported version.
