### ISSUE TITLE
Document the AST output

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1511]
The AST output from the compiler should be documented and we should follow our policy of breaking changes there as well.

**Comment by chriseth** [comment]
I think it is fine if we just document the new format.

**Comment by Assawal** [comment]
> The AST output from the compiler should be documented and we should follow our policy of breaking changes there as well.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 
Closing this issue for the same reason as #7387.
