### ISSUE TITLE
Metadata - decide/document sorting/ordering of fields

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1512]
The ordering of the fields in the metadata output should be deterministic for each compiler version as it should reproduce the same output file.

We need to test/review and ensure that it is definitely the case.

(Pulled from #1508.)

**Comment by chriseth** [comment]
jsoncpp sorts keys in objects alphabetically. Are you talking about that?

**Comment by chriseth** [comment]
Can this be closed?
