### ISSUE TITLE
SMTChecker: Unable to support ripemd160, sha256 well

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15143]
## Description
Similar to [14983](https://github.com/ethereum/solidity/issues/14983)， the SMTChecker cannot evaluate the results of these functions

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Command-line
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce

```solidity
contract test {

    function f()public returns (int) {
        bytes memory t0="1";
        bytes memory t1="1";
        bytes32 a=ripemd160(t0);
        bytes32 b=ripemd160(t1);
        assert(a==b);
    }
}
```

```solidity
contract test {

    function f()public returns (int) {
        bytes memory t0="1";
        bytes memory t1="1";
        bytes32 a=sha256(t0);
        bytes32 b=sha256(t1);
        assert(a==b);
    }
}
```
![1716521695310](https://github.com/ethereum/solidity/assets/147013944/3368aa40-c4fb-4a56-8185-4966f1cf8680)

**Comment by blishko** [comment]
This has the same underlying issue as #14983 and has been fixed by #15050.
At `develop`, and in the latest release, `v0.8.26`, SMTChecker already proves this assertions safe.
