### ISSUE TITLE
[SMTChecker] Bug: Inconsistent Storage Array Bytes Writing

### ISSUE THREAD

**Issue by sallywang147** [ethereum/solidity#15158]
Thank you for building SMTChecker and Solidity -great work! As I'm experimenting, I found a compiler bug below. When you get a chance, would you mind confirming if this bug indeed exists and should be fixed? Thank you! 

## Environment

- Compiler version: pragma solidity >=0.7.0;
- Target EVM version (as per compiler settings): [0.7.0+commit.9e61f92b](https://remix.ethereum.org/#)
- Framework/IDE (e.g. Truffle or Remix): the following trances are from running on Mac Terminal locally. Similar issues are observed on REMIX IDE too. 
- EVM execution environment / backend / blockchain client: N/A
- Operating system: MacBook Air (Retina, 13-inch, 2018)

## Steps to Reproduce

The following code passes assertion checks when it really shouldn't, because x[0] = 23 after reassigning at ``x = y;``
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.0;
pragma experimental SMTChecker;

contract C {
    uint128[] x;
    function f() public {
        x.push(42); x.push(42); x.push(42); x.push(42);
        uint128[] memory y;// = new uint128[](1);
        y[0] = 23;
        // This will shrink the array x to one element.
        // Resizing the array to length 4.
        x = y;
        x.push(); x.push(); x.push();
        assert(x[0] == 0);
        assert(x[1] == 0);
        assert(x[2] == 0);
        assert(x[3] == 0);
        // After resizing the array, its contents are [0, 0, 0, 0],
        // instead of [23, 0, 0, 0]. Resizing can be also be done by
        // assigning to `.length` or by assigning to the `slot` member
        // inside inline assembly.
    }
}
```

<img width="546" alt="Screen Shot 2024-05-28 at 12 43 20 PM" src="https://github.com/ethereum/solidity/assets/60257613/056fcb61-eefa-43fd-92d7-ff4edba248eb">

It throws violations in the following code when it really shouldn't, because x[0] = 23 after reassigning at ``x = y;``
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.0;
pragma experimental SMTChecker;

contract C {
    uint128[] x;
    function f() public {
        x.push(42); x.push(42); x.push(42); x.push(42);
        uint128[] memory y;// = new uint128[](1);
        y[0] = 23;
        // This will shrink the array x to one element.
        // Resizing the array to length 4.
        x = y;
        x.push(); x.push(); x.push();
        assert(x[0] == 23);
        assert(x[1] == 0);
        assert(x[2] == 0);
        assert(x[3] == 0);
        // After resizing the array, its contents are [0, 0, 0, 0],
        // instead of [23, 0, 0, 0]. Resizing can be also be done by
        // assigning to `.length` or by assigning to the `slot` member
        // inside inline assembly.
    }
}
```
<img width="521" alt="Screen Shot 2024-05-28 at 1 13 54 PM" src="https://github.com/ethereum/solidity/assets/60257613/fc2606c6-ef2b-4ba8-ae36-aa0bad42dfd7">

If we use REMIX to reproduce the bug, it throws assertion violations in both scenarios in the code above: 
<img width="557" alt="Screen Shot 2024-05-28 at 1 16 36 PM" src="https://github.com/ethereum/solidity/assets/60257613/ebc4390d-4537-47db-b257-195b83a15ca0">

<img width="268" alt="Screen Shot 2024-05-28 at 1 16 19 PM" src="https://github.com/ethereum/solidity/assets/60257613/6dc62290-7f97-4cd5-9772-3610a9b242df">

<img width="654" alt="Screen Shot 2024-05-28 at 1 18 21 PM" src="https://github.com/ethereum/solidity/assets/60257613/6fe75508-b693-4397-89c4-779b6775a091">
<img width="261" alt="Screen Shot 2024-05-28 at 1 18 34 PM" src="https://github.com/ethereum/solidity/assets/60257613/c57aa76a-f7fb-4b61-a2d9-840da862c9f6">

**Comment by blishko** [comment]
Hi @sallywang147,

do I read it correctly that you are using `solc 0.7.0`? That is rather old version of the compiler, `SMTChecker` has matured significantly since then.

On the latest version, I see different results from `SMTChecker`.
Can you check with the latest version and let us know if you still consider the answers incorrect?

One note about your examples: 
```
uint128[] memory y;// = new uint128[](1);
y[0] = 23;
```
This is an access out of bounds, so the code would always revert at this point, making the assertions that follow always unreachable (and thus safe).

**Comment by sallywang147** [comment]
Hi @blishko, many thanks for your quick response! I totally agree that the newer compiler version (>=0.8.0) would prevent this issue. On 0.7.0, I think the root cause is not SMTChecker but the older compiler. For example, the 0.7.0 compiler generated x[0] = 0 when it really should've been x[0] = 23. That's why SMTChecker throws the violation when it executes the assertion ``assert(x[0]==23);``. Is this explanation plausible? or in your view, is the issue caused by something else? Many thanks for your time!

**Comment by blishko** [comment]
I suspect that the SMTChecker warnings are independent of the code generated by the compiler.
Unfortunately, we cannot afford to investigate the behaviour in the old version of the compiler when the new version does not suffer from this issue.

**Comment by sallywang147** [comment]
Ah no worries at all, many thanks again for your quick response! I'll close the comment.
