### ISSUE TITLE
Exponential compilation time with multiple if clauses

### ISSUE THREAD

**Issue by pnomarev** [ethereum/solidity#1517]
It takes about 6 seconds for the following code to be compiled. Every additional 'if' clause roughly doubles this time.

pragma solidity ^0.4.7;

contract test {
    
    uint x0;
    function b() returns (uint) {
        uint answer;
        
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        if(x0>3) answer = 42;
        
        return answer;
    }
    
}

**Comment by federicobond** [comment]
I cannot reproduce this on latest master (with or without optimization).

**Comment by pnomarev** [comment]
Could you try to double the number of ifs? It just hangs my browser's tab

**Comment by chriseth** [comment]
This is a know bug in the optimizer.

**Comment by chriseth** [comment]
This seems to be not an issue anymore, now even with #1356
