### ISSUE TITLE
Where can I find Test Sepolia so I can deploy a contract on a testnet?

### ISSUE THREAD

**Issue by Greenswordfish1** [ethereum/solidity#15202]
I am following a tutorial on thirdweb via youtube text And I am stuck at 8:20 mark because I do not have Sepolia, This youtube video does not explain where to get it as far as I am aware & I asked ChatGpt and the site it recommends says YOU ALREADY NEED Sepolia in order to obtain more.

I tried using CHATgpt & Followed the youtube tutorial and could not find an answer. I was expecting to obtain Sepolia to use on for a testnet[YOUTUBE link to web3 video tutorial here][1]

  [1]: https://www.youtube.com/watch?v=emYUnTZ5ndM

**Comment by mehtavishwa30** [comment]
I'm afraid this is not relevant to the Solidity compiler and language team. Please refrain from posting ad hoc Solidity support questions here and consider checking out the Ethereum StackExchange or relevant project forums for it (Thirdweb) in this case.
