### ISSUE TITLE
Problem with current remappings and suggestions for better model

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1520]
Current Problem: 

Suppose I have a file structure for a module `foo` as such:
```
. 
├── contract_bundles
│   ├── bar
│   │   ├── 1.0.0
│   │   │   └── bar.sol
│   │   └── 2.0.0
│   │       └── bar.sol
│   └── dee
│       └── dee.sol
└── foo.sol
```
And the following contents in the files set as:

foo.sol:
```
import "bar/bar.sol";
import {Dee} from "dee/dee.sol";

contract Foo {
	Bar bar;
	Dee dee;
	int version;
	function Foo() {
		version = bar.Version1();
	}
	function callDee() {
		version = dee.version();
	}
}
```

dee.sol:
```
import "bar/bar.sol";

contract Dee {
	Bar bar;
	int public version;
	function Dee() {
		version = bar.Version2();
	}
}
```

1.0.0/bar.sol:
```
contract Bar {
	function Version1() returns (int) {
		return 1;
	}
}
```

2.0.0/bar.sol:
```
contract Bar {
	function Version2() returns (int) {
		return 2;
	}
}
```

Currently I can get this to compile using the following command:

```
solc dee/=./contract_bundles/dee/ foo.sol:bar/=./contract_bundles/bar/1.0.0/ $dee/:bar/=./contract_bundles/bar/2.0.0/ foo.sol
```

#### Mid issue writing update 
Documentation complaint: I was about to complain about the fact that there is no way to reference an already created prefix from a remapping. While trying out different potential syntactical ways that would be intuitive I actually found that a brilliant one works and isn't at all documented (that being the $ reference approach above). 

Prior to finding this out I had been referencing the actual directory `dee.sol` was housed in to make a module (aka: `./contract_bundles/dee/:bar=./contract_bundles/bar/2.0.0/`). This *NEEDS* to be documented. 
#### End update

I find this command missing an important feature (possibly 2):
- There is no way to define the present working directory and maintain `module` targeting. Believe me...I've tried `./:`, `.:`, and even `:`. None of these ways work. There are times (from a package management perspective) where you do want to blank define the `pwd` and use a remapping only for this module.
- There may be utility in the ability to exclude a directory from a remapping prefix. Currently that is not possible (perhaps something like a `!` rather than a `:` to define a module).

**Comment by VoR0220** [comment]
Upon even FURTHER investigation, it turns out that `$` actually isn't doing anything and simply adding another `potential` remapping into the mix...which I guess is alright, but isn't precise and could break/harm things. Going to try to go for a fix using `@` instead. The command line will most likely pick that up.

**Comment by chriseth** [comment]
Solidity remappings always operate on global paths, and the context (the stuff before the `:`) is always a global path prefix, so you should get better result by using `/home/user/src/dee:bar=bla`.

**Comment by VoR0220** [comment]
Realize that @chriseth (its what i used prior to) but what im saying is that could be put together in an easier way by enabling a reference ability to resolve paths. Im currently working on a PR for this. Will link when finished.

**Comment by chriseth** [comment]
I assume everything herein is captured by https://github.com/ethereum/solidity/issues/1535 so closing.
