### ISSUE TITLE
Detailed Errors Instead of Gas Error For Easy Debugging

### ISSUE THREAD

**Issue by vidhanmangla** [ethereum/solidity#15235]
## Abstract

We get a very generic error response from the compile which just says, "Gas Estimation Error", for any kind of errors in the code. We should consider adding support for more specific errors by the EVM. Just a thought, happy if this is not worth taking a look.

## Motivation

I think everyone would understand this.

## Backwards Compatibility

We can put this into the new version, like, 0.8.28.

**Comment by web31357** [comment]
Yes!! definetely useful , But if we more adding more support it will become more complicated and there is a feature of Ai which we can use more efficiently.
