### ISSUE TITLE
Public function is not visible outside of the contract.

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#15266]
## Description
Seems that a contract instance does not expose the scope of the contract it refers to.

## Environment

- Compiler version:0.8.27-develop.2024.6.25+commit.ce4be6e1.Darwin.appleclang

## Steps to Reproduce

Execute the following code snippet
```Solidity
contract A {
    function f() public {
    }
}

contract B {
    A public a;
    function f() external {
        a.f();
    }
}

contract C {
    B b;
    function f() public {
        b.a.f();
    }
}
```

And you will get the following error:
```
Error: Member "f" not found or not visible after argument-dependent lookup in function () view external returns (contract A). Did you intend to call the function?
  --> test.sol:16:9:
   |
16 |         b.a.f();
   |         ^^^^^


```

**Comment by ekpyron** [comment]
In the external view of a contract, public state variables become getter functions, i.e.
``b`` will get an external function ``function a() external returns (A)`` that returns the value of the state variable.

So what you want to do here is ``b.a().f()``.

**Comment by haoyang9804** [comment]
> In the external view of a contract, public state variables become getter functions, i.e. `b` will get an external function `function a() external returns (A)` that returns the value of the state variable.
> 
> So what you want to do here is `b.a().f()`.

Thanks! May I ask if there exists a formal specification for this special grammar on the Solidity website?

**Comment by ekpyron** [comment]
This in particular is documented here: https://docs.soliditylang.org/en/develop/contracts.html#getter-functions

**Comment by haoyang9804** [comment]
Thx!
