### ISSUE TITLE
SMT logic error: sorts are incompatible

### ISSUE THREAD

**Issue by alex1448** [ethereum/solidity#15308]
## Description

The following code triggers the exception shown bellow in the latest solc version ```0.8.26```. I think the issue is due to the two arrays having a different (but compatible) base type. The problem seems to appear with version ```0.6.9``` (tested on remix).

## Steps to Reproduce

```testcase.sol```

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity =0.8.26;

contract A {}

contract B is A {}

contract C {
    A[10] a;
    B[10] b;

    function f() public {
        a = b;
    }
}
```

```
solc testcase.sol --model-checker-engine chc
```

```
SMT logic error:
./libsmtutil/Z3Interface.cpp(276): Throw in function z3::expr solidity::smtutil::Z3Interface::toZ3Expr(const solidity::smtutil::Expression&)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Sorts |contract A_array_tuple| and |contract B_array_tuple| are incompatible
[solidity::util::tag_comment*] = Sorts |contract A_array_tuple| and |contract B_array_tuple| are incompatible
```

## Environment

- Compiler version: ```0.8.26```

**Comment by alex1448** [comment]
I was testing with the newest solc version ```0.8.27``` since it recently got released and although the issue is fixed for arrays and functions, apparently it also happens with address types aswell.

```Solidity
contract C {
    address[10] a;
    address payable[10] b;

    function f() public {
        a = b;
    }
}
```

**Comment by pgebal** [comment]
Thank you. I'll look into it.
