### ISSUE TITLE
remapping rules with directory names containing `=`; exclude them in the doc, or support them

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1532]
In the documentation, in `docs/layout-of-source-files.rst`, it should be documented that the context dependent module remapping does not work when the context contains a `=` character.  In `develop` the following test fails.  I found this while reviewing #1525.

```
--- a/test/libsolidity/Imports.cpp
+++ b/test/libsolidity/Imports.cpp
@@ -164,6 +164,17 @@ BOOST_AUTO_TEST_CASE(context_dependent_remappings)
        BOOST_CHECK(c.compile());
 }
 
+BOOST_AUTO_TEST_CASE(context_dependent_remappings_context_with_equal)
+{
+       CompilerStack c;
+       c.setRemappings(vector<string>{"a=:s=s_1.4.6", "b:s=s_1.4.7"});
+       c.addSource("a=/a.sol", "import \"s/s.sol\"; contract A is SSix {} pragma solidity >=0.0;");
+       c.addSource("b/b.sol", "import \"s/s.sol\"; contract B is SSeven {} pragma solidity >=0.0;");
+       c.addSource("s_1.4.6/s.sol", "contract SSix {} pragma solidity >=0.0;");
+       c.addSource("s_1.4.7/s.sol", "contract SSeven {} pragma solidity >=0.0;");
+       BOOST_CHECK(c.compile());
+}
+
```

**Comment by VoR0220** [comment]
so here's what that actually is doing. a becomes the remapping and `:=s=s` the target. So it's doing its job...it's properly failing....but what did you have in mind that it should do?

**Comment by pirapira** [comment]
In the context `a=`, the prefix `s` should be mapped to `s_1.4.6`.

**Comment by VoR0220** [comment]
okay, here's a better question: what is context `a=` in this instance? That would be a remapping under current definition?

**Comment by pirapira** [comment]
`a=` is a directory.  I can create one like `mkdir a=`.

**Comment by VoR0220** [comment]
so what you're saying is that only the last `=` should be used to create a remapping in the full string, yes?

**Comment by pirapira** [comment]
Maybe not, because the target can contain `=` too.  One way around is to introduce some escaping; `==` means a single `=`, perhaps.

**Comment by VoR0220** [comment]
Then it should be the first `=` defines the remapping so long as it's after the colon for context. Escaping might be something useful, but I'm feeling this might be overcomplicating things.

**Comment by chriseth** [comment]
I think the current behaviour is fine (longest match goes to target, not path) and I also think it is fine to assume that `=` is not part of a path, so we do not really need an escape. Let's add a test nevertheless that enforces the current behaviour (unless there are arguments against).
