### ISSUE TITLE
Remapping specifier without an `=` should cause an error

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1533]
In `develop`, when a remapping is specified without an `=`, the remapping is silently dropped.  However, this should cause an error.  The following test should pass.

```
test/libsolidity/Imports.cpp:

BOOST_AUTO_TEST_CASE(remapping_without_equal)
{
	CompilerStack c;
	c.setRemappings(vector<string>{"foo"});
	c.addSource("s_1.4.7/s.sol", "contract SSeven {} pragma solidity >=0.0;");
	BOOST_CHECK(!c.compile());
}
```

Or, documentation should describe how a remapping without `=` should behave.

**Comment by VoR0220** [comment]
Well...no it shouldn't because a remapping without an `=` is just...a target. So without that you're basically referencing a file to be compiled.

**Comment by VoR0220** [comment]
so actually this should continue to compile...in this example, `foo` wouldn't even make it into remappings.

**Comment by VoR0220** [comment]
although I suppose it couldn't hurt to make sure that if `foo` is included in `setRemappings` that it should fail.

**Comment by pirapira** [comment]
OK.  I added the last sentence in the description of this issue.

**Comment by VoR0220** [comment]
but it already does document how it behaves. https://solidity.readthedocs.io/en/latest/layout-of-source-files.html#use-in-actual-compilers I think this test could be added though. As it should never make it that far.

**Comment by pirapira** [comment]
I see.  Thanks.  Something is still fogging me but I will try to raise another issue for that.
