### ISSUE TITLE
Enabling the `@` reference in the targets of remappings too

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1535]
In #1525, `@prefix` can be used as a context for remapping.  This looks up the already defined remappings.

This issue is about enabling the same notation in the target part of the remapping declarations.

Example:
`dapp_bin=/somewhere/dapp/bin/is famous_dapp=@dapp_bin/famous_dapp`

**Comment by VoR0220** [comment]
what is the use case here? I'm confused how this would be utilized.

**Comment by pirapira** [comment]
Started thinking about the use case..., yes,
```
dapp_bin=/somewhere/dapp/bin/is \
famous_dapp=@dapp_bin/famous_dapp \
another_dapp=@dapp_bin/another_dapp \
third_dapp=@dapp_bin/third_dapp
```
is much shorter with the `@` notation in the target.

**Comment by VoR0220** [comment]
Ahhhhh..okay...i see where you're going with this.

**Comment by chriseth** [comment]
I think this should not be a base feature of the remapping mechanism but rather a feature of the user interface.

**Comment by VoR0220** [comment]
I can agree with that.

**Comment by chriseth** [comment]
The `@`-syntax was never added.
