### ISSUE TITLE
Memory alignment requirements

### ISSUE THREAD

**Issue by CodeSandwich** [ethereum/solidity#15351]
## Page

https://docs.soliditylang.org/en/v0.8.7/assembly.html

## Abstract

Is there a requirement for address alignment in memory? I don't know, and it would be helpful to be able to learn it from the documentation.

Solidity seems to allocate memory in chunks being multiples of 32. This is understandable since all allocation sizes are multiples of 32. But is it a requirement and is it fine if a Yul inline violates this convention? E.g. in Yul you can easily allocate 33 bytes: `mstore(0x40, add(33, mload(0x40))`, but will it cause problems for Solidity? You can also place items under non-aligned locations, e.g. `my_array := add(mload(0x40), 1)` (remember to initialize `my_array` and update `0x40`), will Solidity work fine with `my_array`?

## Pull request

None yet, but I can create one.

**Comment by CodeSandwich** [comment]
It's still unresolved.

**Comment by mehtavishwa30** [comment]
Hey @CodeSandwich! Appreciate you raising the concern regarding this.

The 32-byte alignment in memory layout is not mandatory. It's just a natural consequence of the fact that multiple values are never packed into a single slot. And the lack of packing is just a trade-off: packed values take less space but extra masking and bit shift operation are necessary to move them between memory and stack. In case of memory it's usually cheaper not to pack.

It's perfectly fine to manually allocate unaligned memory in inline assembly and it won't interfere with what compiler does. The compiler assumes that values take full 32-bytes so allocating less would be dangerous but there are no assumptions about their alignment. If you want to be sure, you can take a look at the helpers the compiler generates for your code in the unoptimized Yul source.

Based on this, I would be inclined to close this issue. Do let me know if this helps. :)

**Comment by CodeSandwich** [comment]
Thanks! As you can see I've opened a PR adding to the documentation what you just told me. I'd keep this issue open until the PR is merged or discarded.
