### ISSUE TITLE
Output selection `evm.deployedBytecode.*` with `Yul` as language should error.

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#15364]
The compiler should not just accept the following JSON:
```Json
{
  "language": "Yul",
  "settings": {
    "outputSelection": {
      "*": {
        "*": [
          "evm.deployedBytecode.sourceMap"
        ]
      }
    }
  },
  "sources": {
    "fileA": {
      "content": "{}"
    }
  }
}
```

Current behaviour:
```
❯ solc/solc --standard-json test.json
{"errors":[]}
```

**Comment by cameel** [comment]
The output names in `outputSelection` are not validated. The last time I brought it up, in #12153, it turned out that tooling prefers it that way so I don't think we'll be changing it.

**Comment by nikola-matic** [comment]
> The output names in `outputSelection` are not validated. The last time I brought it up, in #12153, it turned out that tooling prefers it that way so I don't think we'll be changing it.

Close as won't do?
