### ISSUE TITLE
strings being prefixes of each other should be equal, but supposed to be different

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1536]
In the documentation, `layout-of-source-files.html` contains this sentence:  `If remapping keys are prefixes of each other, the longest is tried first.`

When two strings are prefixes of each other, the two strings are equal (both the length and the contents are equal).  So this sentence should be saying something else.

**Comment by chriseth** [comment]
I think the intention was to say `If the remapping keys are not prefix-free, the longest is tried first` but make it understandable to non-theorists. We could just say `If multiple remappings can be applied, the one with the longest key is tried first.`

**Comment by pirapira** [comment]
I like the last rephrasing.
