### ISSUE TITLE
Yul optimization causes mstore to be eliminated.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15363]
## Environment

- Compiler version: 0.8.26
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): None 
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce
```solidity
{
    let index := 0
    for { } lt(index, 5) { index := add(index, 1) }
    {
        let y := mul(index, 2)
        mstore(mul(0x20, index), y)
    }
    let r:=mload(0x40)
    mstore(0x80, r)
    sstore(1, mload(0x80))
}
```
#### normal
```
solc-0826  --strict-assembly --bin test.yul
5f5b60058110601657604051608052608051600155005b80600260019202816020025201600156
```
#### optimize
```
solc-0826  --strict-assembly --bin test.yul
5f5b60058110601057604051600155005b80600191821b8160051b5201600156
```
#### normal
```
go-ethereum/build/bin/evm --debug --json --code 5f5b60058110601657604051608052608051600155005b80600260019202816020025201600156 run
```
#### optimize
```
go-ethereum/build/bin/evm --debug --json --code 5f5b60058110601057604051600155005b80600191821b8160051b5201600156 run
```
#### normal
```
output,storage,memory
{'output': '', 'gasUsed': '0x57ea'},{'1': '4'},{'0': '0', '32': '2', '64': '4', '96': '6', '128': '4'}
```
#### optimize
```
output,storage,memory
{'output': '', 'gasUsed': '0x57ca'},{'1': '4'},{'128': '8', '0': '0', '32': '2', '64': '4', '96': '6'}
```
The value in memory at position 128 (0x80) differs. The possible reason is that mstore(0x80, r) might have been incorrectly removed.

**Comment by ekpyron** [comment]
The explanation given in https://github.com/ethereum/solidity/issues/15362 also applies here from what I can tell, so I'm closing this one already as a duplicate (I think the other one can also be closed, since so far the cases are valid optimizations)

**Comment by Subway2023** [comment]
> The explanation given in #15362 also applies here from what I can tell, so I'm closing this one already as a duplicate (I think the other one can also be closed, since so far the cases are valid optimizations)

I don't think this is a duplicate of the example in #15362. #15363 causes the value in sstore to change, while #15362 only changes the value in mstore. Could you please let me know if my reasoning is valid?

**Comment by ekpyron** [comment]
At least in the "execution result analysis" section of this issue the storage trace in both cases is identical - what makes you say that the value in the ``sstore`` changes?

**Comment by Subway2023** [comment]
> At least in the "execution result analysis" section of this issue the storage trace in both cases is identical - what makes you say that the value in the `sstore` changes?

Thank you, i had a mistake.
