### ISSUE TITLE
Unimplemented error when using fixed-point types

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15379]
## Environment

- Compiler version: 0.8.26
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce

```solidity
contract C {
    fixed x;
    function f() public {
        x = 0.10;
        f_internal();
    }
    function f_internal() internal {
        ufixed8x2 y = 0.20;
        x = x + y;
    }
}
```
```
solc test.sol --bin
```
./libsolidity/codegen/CompilerUtils.cpp(814): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type&, const solidity::frontend::Type&, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Not yet implemented - FixedPointType.
[solidity::util::tag_comment*] = Not yet implemented - FixedPointType.

**Comment by cameel** [comment]
Fixed-point types are not yet fully implemented. See #409.

**Comment by Escarcega1989** [comment]
> ## Environment
> * Compiler version: 0.8.26
> * Target EVM version (as per compiler settings): None
> * Framework/IDE (e.g. Truffle or Remix): None
> * EVM execution environment / backend / blockchain client: None
> * Operating system: Linux
> 
> ## Steps to Reproduce
> contract C {
>     fixed x;
>     function f() public {
>         x = 0.10;
>         f_internal();
>     }
>     function f_internal() internal {
>         ufixed8x2 y = 0.20;
>         x = x + y;
>     }
> }
> ```
> solc test.sol --bin
> ```
> 
> ./libsolidity/codegen/CompilerUtils.cpp(814): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type&, const solidity::frontend::Type&, bool, bool, bool) Dynamic exception type: boost::wrapexceptsolidity::langutil::UnimplementedFeatureError std::exception::what: Not yet implemented - FixedPointType. [solidity::util::tag_comment*] = Not yet implemented - FixedPointType.

**Comment by Escarcega1989** [comment]
> > ## Environment
> > 
> > * Compiler version: 0.8.26
> > * Target EVM version (as per compiler settings): None
> > * Framework/IDE (e.g. Truffle or Remix): None
> > * EVM execution environment / backend / block coin client: None
> > * Operating system: Linux
> > 
> > Steps to Reproduce
> > ##contract C {
> > fixed x;
> > function f() public {
> > x = 0.10;
> > f_internal();
> > }
> > function f_internal() internal {
> > y = 0.20;
> > x = x + y;
> > }
> > }
> > ```
> > solc test.sol --bin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ./solidarity/codegen/CompilerUtils.cpp(814): Throw in function void solidity::frontend::Compilations::Convert types(const solidity::frontend::Type&, const solidity::frontend::Type&, bool, bool, bool) Dynamic exception type: boost::solidarity::languages::Implementation::exception::what: Not yet implemented - Fixed point type. [solidity::util::tag_comment*] = Not yet implemented - Standpoint.
