### ISSUE TITLE
Precision in Misc docs about automatic getters

### ISSUE THREAD

**Issue by esques** [ethereum/solidity#1539]
From the [Solidity documentation][1]:

> Make your state variables public - the compiler will create getters for you for free.

However, this is an illusion if your variable is of a complex type like `mapping` or `array`.
So could you add: for primitive types in the documentation?

  [1]: https://solidity.readthedocs.io/en/develop/miscellaneous.html?highlight=getter#tips-and-tricks

**Comment by esques** [comment]
And why does it work in Browser-solidity so smoothly?

**Comment by redsquirrel** [comment]
It still creates getters for complex types, but those getters require parameters (a key for a mapping, and an index for an array).

**Comment by esques** [comment]
Oh, I found the error. Was false alarm! thanks
