### ISSUE TITLE
Documentation of log0, log1...

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#154]

**Comment by LianaHus** [comment]
https://github.com/ethereum/solidity/issues/38

**Comment by ethers** [comment]
thanks @LianaHus
#38 has been opened for several months...  maybe a brief documentation of log0, log1 could be added to the Solidity guide.  Example: the parameters they take, and how to log `bytes` (not `bytes32` which is straightforward).

**Comment by janx** [comment]
+1. any updates?

**Comment by chriseth** [comment]
Is #271 sufficient or do you need more information?

**Comment by janx** [comment]
I'd like to see `logX` api and how X relates to topics count, although it should not be used directly.

https://github.com/ethereum/wiki/wiki/Solidity-Features#events also gives a good example on how does a event map to `log3`.

**Comment by chriseth** [comment]
Added some more.

**Comment by janx** [comment]
@chriseth looks great :+1:
