### ISSUE TITLE
SMTChecker: Error trying to invoke SMT solver

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15407]
## Environment

- Compiler version: 0.8.26 and 0.8.27
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce

```solidity
contract BugDetection {
    bytes a;
    uint256[] b;
    function process() public {
        // Assign storage array b to memory array a, which is not allowed
        // a = bytes(b); // This line is intentionally incorrect
        // Correctly pushing values to array a
        for (uint256 i = 0; i < 1; ++i) {
            a.push() = bytes1(uint8(i));
        }
        // Check for any dirty values in a
        assert(a.length == 1);
    }
}
```
### CHC
```
solc b.sol --model-checker-ext-calls trusted --model-checker-timeout 0 --model-checker-engine chc --model-checker-solvers z3
```
#### 0.8.26
```
Warning: CHC: Assertion violation happens here.
  --> test/b.sol:12:9:
   |
12 |         assert(a.length == 1);
   |         ^^^^^^^^^^^^^^^^^^^^^
```
#### 0.8.27
```
Warning: CHC: Error trying to invoke SMT solver.
  --> test/b.sol:12:9:
   |
12 |         assert(a.length == 1);
   |         ^^^^^^^^^^^^^^^^^^^^^
```
0.8.26 has a false positive, while 0.8.27 fails to invoke SMT
### BMC
```
solc b.sol --model-checker-ext-calls trusted --model-checker-timeout 0 --model-checker-engine bmc --model-checker-bmc-loop-iterations 10 --model-checker-solvers z3
```
```
Warning: BMC: Assertion violation happens here.
  --> test/b.sol:12:9:
   |
12 |         assert(a.length == 1);
   |         ^^^^^^^^^^^^^^^^^^^^^
```
both 0.8.26 and 0.8.27 have false positive.

**Comment by pgebal** [comment]
@Subway2023
On the CHC engine vs 0.8.26:
The output is correct. The assertion is violated when `process()` is called multiple times.

I could not reproduce the `Warning: CHC: Error trying to invoke SMT solver.` in  0.8.27 and the current 0.8.28. It prints that the assertion has failed. Please make sure that you have built solc with z3 version requirement satisfied.

On the BMC engine:
BMC engine analyzes functions in isolation, it does not take into account an overall behavior over multiple transactions. It does not make assumptions on values of state variable. In this context output is correct.

You can get a counterexample for the assertion by removing the unsued state variable `b` and invoking smt checker again.
