### ISSUE TITLE
write to uint[2][2] calldata fail in IR-based Codegen

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15415]
## Description
If the function parameter is uint[2][2] calldata, and the assembly is used in the function body to assign values to the parameter, IR-based codegen fails when calling this function. 

## Environment

- Compiler version: 0.8.27
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```solidity
contract Test {
    uint z;
    function outer(uint[2][2] calldata foo) public returns (uint[2][2] memory r) {
        assembly { foo := 0x24 }
        r = foo;
    }
    function ext() public returns (bool,bytes memory) {
        bytes memory buffer = abi.encodeWithSignature("outer(uint256[2][2])", [uint256(12), uint256(34)], [uint256(56), uint256(78)]);
        (bool succ, bytes memory ret) =  address(this).call(buffer);
        return (succ,ret);
    }
}
```
#### Legacy codegen
call ext()
![image](https://github.com/user-attachments/assets/2cab625e-c693-4d2e-83c4-eafd1de95eb0)
#### IR-based codegen
![image](https://github.com/user-attachments/assets/862f2ca0-6423-4534-8e4c-cc4ef4459ecf)

If we comment out assembly { foo := 0x24 }, succ becomes true.

**Comment by Subway2023** [comment]
```solidity
contract Test {
    uint z;
    function outer(uint[2][2] calldata foo) public returns (uint[2][2] memory r) {
        assembly { foo := 0x24 }
        r = foo;
    }
    function ext() public returns (uint[2][2] memory) {
        bytes memory buffer = abi.encodeWithSignature("outer(uint256[2][2])", [uint256(12), uint256(34)], [uint256(56), uint256(78)]);
        (bool succ, bytes memory ret) =  address(this).call(buffer);
		uint[2][2] memory decoded=abi.decode(ret,(uint[2][2]));
        return decoded;
    }
}
```
![1725982624117](https://github.com/user-attachments/assets/120bd982-bf09-4982-b16a-999dbdaf36a1)

The decoded data is: 34, 56, 78, 0

**Comment by cameel** [comment]
> ```solidity
> assembly { foo := 0x24 }
> ```

It looks to me like just a wrong assumption about the layout of `foo`. It's statically sized so it's encoded in-place in the calldata tuple (there's no offset stored there). So it starts at `0x04`, not `0x24`. If you set `r` to `0x24`, ABI coder will start decoding in the middle of the array. All the other weird effects must be coming from that.
