### ISSUE TITLE
mstore(add(mload(0x80), 0x20), xx) cause IR-based codegen execution revert.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15411]
## Description

mstore(add(mload(0x80), 0x20), xx) cause IR-based codegen execution revert. However, legacy codegen can execute successfully.

## Environment

- Compiler version: 0.8.27
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```solidity
contract Test {
    bytes public a;
    uint[] public b;
    function f(uint x) public returns (bytes memory) {
        a = "";
        for (uint i = 0; i < x; ++i) {
            a.push() = bytes1(uint8(i));
        }
        return g(a);
    }
    function g(bytes memory input) public returns (bytes memory) {
        uint[2] memory tempStorage;
        tempStorage[0] = 12345;
        tempStorage[1] = 67890;
        assembly {
            let tempMemory := mload(0x80)
            mstore(add(tempMemory, 0x20), 0x12345678)
        }
    }
}
```
### Lecacy codegen
![image](https://github.com/user-attachments/assets/c962304f-07bd-47b4-ba3d-b916dc850120)
### IR-based codegen
![image](https://github.com/user-attachments/assets/7154a345-651b-4e6f-b010-4f2dc6f18ff2)

**Comment by mehtavishwa30** [comment]
Hey @Subway2023!

This is another instance of manually interfering with Solidity's memory model, similar to your other issue (https://github.com/ethereum/solidity/issues/15384). It ignores the memory pointer, reads from 0x80 via inline assembly, and further uses the value as an address. Something like this would always lead to undefined behaviour. Hence, this isn't a bug, but rather incorrect usage of the free memory pointer.

Please refer to https://github.com/ethereum/solidity/issues/15391#issuecomment-2326081058 or https://github.com/ethereum/solidity/issues/15384#issuecomment-2497818459 for more context. Closing this based on similar reasoning.
