### ISSUE TITLE
Request: expose address.codehash

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#1543]
I want to use a proxy contract that exposes it's `msg.sender` as a `public address proxyFor` variable. Problem is, without knowing an address' codehash, I can't tell if a call is being made from a proxy contract or an imposter-proxy contract. My understanding is there is no way to get the codehash from solidity.

**Comment by chriseth** [comment]
The current way to do this would be to use a suitable library that does the job for you: https://solidity.readthedocs.io/en/develop/control-structures.html#example

Also, I don't fully understand what you are trying to do, but if you in any way rely on the initial state of the contract (for example if you store a specific owner in storage), checking the deployed code is not enough, you also have to check the constructor code, a task that cannot be done on chain.

**Comment by aakilfernandes** [comment]
So this is a simplified version of a contract I want to use.

```
contract Proxy{
    address sender;
    function Proxy() { sender = msg.sender; }
    function call(address addr, bytes calldata) { addr.call(calldata); }
}
```

I need to differentiate between this Proxy and an ImposterProxy like this.

```
contract ImposterProxy{
    address sender;
    function Proxy(address _sender) { sender = _sender }
    function call(address addr, bytes calldata) { addr.call(calldata); }
}
```

Would using the codeHash be acceptable?

**Comment by chriseth** [comment]
If you use storage, codhash is not suitable. On the other hand - is your contract correct that way? `sender` is not really used after the constructor.

**Comment by aakilfernandes** [comment]
@chriseth yup, the idea is that whatever `proxyReceiver` contract that `proxy` calls can check

1. the code hash of `msg.sender`
2. the `sender` variable

```
contract ProxyCallReceiver{
        function modifier proxyCheck() {
              if (msg.sender.codeHash != 0xPROXYHASH ) throw;
              if (proxy(msg.sender).sender != owner ) throw;
              _;
        }
      }
```

and know who is proxying

So in this case, your not checking the codehash to make sure the `sender` is correct, just to make sure that the proxy contract has a constructor function which sets `sender` to `msg.sender`

**Comment by chriseth** [comment]
If you can, change the proxy so that it does not use storage, then you can verify everything by retrieving its code.

**Comment by chriseth** [comment]
Closing as it would clutter the address namespace.

**Comment by jtakalai** [comment]
now available since Constantinople in 2019 :) https://docs.soliditylang.org/en/v0.8.7/units-and-global-variables.html#members-of-address-types
