### ISSUE TITLE
The new compiler does not work as intended in `Semantic Only Changes` section in docs for Cancun upgrade

### ISSUE THREAD

**Issue by 0xumarkhatab** [ethereum/solidity#15472]
## Description

The [Semantic Only Changes](https://docs.soliditylang.org/en/v0.8.27/ir-breaking-changes.html#semantic-only-changes) states that new compiler version will compile the code differently due to change in the order which compiler processes inheritance hierarchy.
However, when the same given code is ran on remix with latest version of solidity `0.8.27` , it's output is different than intended.

## Environment

- Compiler version: 0.8.27
- Target EVM version (as per compiler settings): Cancun
- Framework/IDE (e.g. Truffle or Remix): Remix VM
- EVM execution environment / backend / blockchain client: Remix
- Operating system: Windows but i ran Remix on Brave [Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)](https://brave.com/latest/)

## Steps to Reproduce

1. Visit https://docs.soliditylang.org/en/v0.8.27/ir-breaking-changes.html#semantic-only-changes
2. For the given first block of the code , click `open in remix`

![image](https://github.com/user-attachments/assets/65fab5ca-9036-4e0d-898c-9d7b0ab46fa0)

3. Compile with latest `0.8.27` version 

![image](https://github.com/user-attachments/assets/d2f25f86-6239-46ef-bd80-4bf9183fbf50)

4. Deploy Contract `B` on `Remix VM (Cancun)`
5. Check the Output

Expected Output :

y=42 ( According to Docs )

Actual Output 

y=0

![image](https://github.com/user-attachments/assets/a07856b0-f1b1-48b9-b3ab-276ce1df3830)

 

```solidity

// SPDX-License-Identifier: MIT
pragma solidity 0.8.27;
contract A {
    uint x;
    constructor() {
        x = 42;
    }
    function f() public view returns(uint256) {
        return x;
    }
}
contract B is A {
    uint public y = f();
}
```

**Comment by matheusaaguiar** [comment]
Hi @0xumarkhatab , thanks for the report, but this is not a bug.
The `Semantic Only Changes` section you refer to actually requires the `viaIR` setting to be enabled, using `--via-ir` on command line or `"viaIR": true` in standard-json as explained one paragraph before in the docs. See [Solidity IR-based Codegen Changes](https://docs.soliditylang.org/en/v0.8.27/ir-breaking-changes.html#solidity-ir-based-codegen-changes).
You can enable this option in remix by accessing the advanced configurations menu and add `"viaIR":true` in the configuration file.

**Comment by curtwaynesamson** [comment]
I find that object statement ran in windows should follow the path/string to run. Brave configure ties to object with per code indicators for possible recovery if lost. or they plan a world take over.
