### ISSUE TITLE
bug: Interface in Struct in Library has wrong ABI Type

### ISSUE THREAD

**Issue by adraffy** [ethereum/solidity#15470]
## Description

Interfaces in structs in libraries compile to the wrong type.  The scope of the issue may be larger than illustrated but the following is a simple example.

## Environment

- Compiler version: 0.8.23+

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
interface I {
  function f() external pure returns (uint256);
}
struct S {
  I i;
}
library L {
  function g(S memory s) external pure returns (uint256) {
    return s.i.f();
  }
}
contract C {
  function h() external pure returns (uint256) {
    S memory s;
    return L.g(s);
  }
}
```
ABI of **L**
```json
{
  "inputs": [
    {
      "components": [
        {
          "internalType": "contract I",
          "name": "i",
          "type": "I" // <-- should be "address"
        }
      ],
      "internalType": "struct S",
      "name": "s",
      "type": "tuple"
    }
  ],
  "name": "g",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
    }
  ],
  "stateMutability": "pure",
  "type": "function"
}
```

**Comment by ekpyron** [comment]
This *is* the correct type in the library ABI. Libraries (unfortunately) don't use the same ABI as contracts - primarily since they support more types not expressible in the ABI like passing storage pointers to recursive structs. See https://docs.soliditylang.org/en/latest/contracts.html#library-selectors

**Comment by adraffy** [comment]
interesting, thanks!
