### ISSUE TITLE
Layout of docs page is too right aligned when choosing solc version 0.8.21 to 0.8.27

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#15498]
I have just noticed that when accessing docs.soliditylang.org the first time from my browser, the version of the docs that load automatically is 0.8.27 (probably not yet 0.8.28 as it was released only yesterday).

When picking 0.8.28, the layout is correct ✅

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/9fcc071c-d1c6-4921-ab80-2a55261df031">

However when picking any of the version below, the layout is just not right and the content is too right aligned.
- 0.8.21 (okayish)

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/6185739e-bf1d-4b4a-b7f0-27c0c529074e">

- 0.8.22
- 0.8.23
- 0.8.24
- 0.8.25
- 0.8.26
- 0.8.27

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/fae35054-99a2-4213-822a-d9a321242a70">

**Comment by r0qs** [comment]
Hi @CJ42, thanks. We already have an open issue on RTD regarding this problem, please see: https://github.com/readthedocs/readthedocs.org/issues/11474#issuecomment-2392284548. Unfortunately, there is no immediate solution for documentation older than `0.8.28`. We've contacted RTD support and are currently looking into potential solutions.

**Comment by r0qs** [comment]
It should be fixed by now. Thanks @humitos for the help ;)
