### ISSUE TITLE
grammar.txt: AssemblyAssignment

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#1552]
Should it not rather be

`AssemblyAssignment = Identifier ( ':=' FunctionalAssemblyExpression | '=:' Identifier )`

instead of

`AssemblyAssignment = Identifier ':=' FunctionalAssemblyExpression | '=:' Identifier`

?

**Comment by federicobond** [comment]
This is legal code:
```
assembly {
    let v := 0 // functional-style assignment as part of variable declaration
    let g := add(v, 2)
    sload(10)
    =: v // instruction style assignment, puts the result of sload(10) into v
}
```

See https://solidity.readthedocs.io/en/develop/control-structures.html#assignments

**Comment by walter-weinmann** [comment]
Thanks.
