### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by rnkhouse** [ethereum/solidity#1557]
Compiling below code:

pragma solidity ^0.4.2;
contract HelloWorld {
    uint public balance;

    function Helloworld(){
        balance = 1000;
    }
}

truffle(default)> HelloWorld.balance.call()

Error:
TypeError: Cannot read property 'call' of undefined
    at evalmachine.<anonymous>:1:19
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Object.exports.runInContext (vm.js:67:17)
    at TruffleInterpreter.interpret (/usr/lib/node_modules/truffle/lib/repl.js:99:17)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:239:10)

**Comment by chriseth** [comment]
This looks like a bug in truffle, please file a bug report there.

**Comment by jeanjluo** [comment]
I have also encountered the same issue. How did you solve it?

**Comment by rnkhouse** [comment]
Hi @jeanjluo : You need to use `HelloWorld.deployed().balance.call()`

**Comment by steveO1234** [comment]
I know this is a fairly old thread, but I'm running the same exact code and running into the same problem. HelloWorld.deployed().balance.call() results in the same error; TypeError: Cannot read property 'call' of undefined. Any idea for a work around?

**Comment by ghost** [comment]
@steveO1234 @rnkhouse @chriseth @jeanjluo  

**Try This:**

```
HelloWorld.deployed().then(helloworld=> console.log(helloworld.balance.call()))
```
**OR**
```
HelloWorld.deployed().then(function(instance){helloworld=instance})
helloworld.balance.call()
```

**Comment by sahilsarpal15** [comment]
@daljeetv  +1 for your answer. Bingo

**Comment by magum** [comment]
8 oct 17 truffle 4.0 beta - problem still actual (((

truffle(develop)> MetaCoin.deployed().then(ct => console.log(ct.creator.call()))
Promise { <pending> }
undefined
truffle(develop)> (node:16379) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Invalid number of arguments to Solidity function

undefined
truffle(develop)>

**Comment by axic** [comment]
This looks like a problem in Truffle. Please report it to them.
