### ISSUE TITLE
introducing wildcard modifiers

### ISSUE THREAD

**Issue by esques** [ethereum/solidity#1559]
Modifiers currently need to be explicitly applied to a function.

With a wildcard operator for modifiers, it would be possible to apply them o a defined set of functions.

e.g.:

`modifier checkAuth() appliesto public {}`

`modifier checkInvariants() appliesto * {}`

**Comment by chriseth** [comment]
I think modifier areas https://github.com/ethereum/solidity/issues/623 are a clearer and less error-prone way to achieve a similar goal. What do you think?

**Comment by esques** [comment]
Agree!
