### ISSUE TITLE
Disallow variables overriding internal or public functions during inheritance

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1565]
On `develop` 8bdb99dcc5870268e68a42d8c567afa54f93a9b2 the following code compiles into a non-empty bytecode.

```
contract A {
    function f() returns (uint) {
        return 1;
    }
    function g() returns (uint) {
       return f();
    }
}

contract B is A {
    uint public f;
}
```

A function `f` in `A` is overridden by a public state variable in `B`.

* [ ] what does the documentation say about this case
* [ ] add a test according to the documentation.

**Comment by chriseth** [comment]
We should treat variables overriding functions as an error in the next breaking version.

**Comment by frangio** [comment]
Why should this be disallowed? If public state variables generate functions they should be treated like any other function.

**Comment by pirapira** [comment]
Public state variables generate functions which are not accessible from inside the contract.  So, not "like any other function", but maybe "like any other public function".

**Comment by frangio** [comment]
But according to the solidity docs public functions can be called internally too.

> Public functions are part of the contract interface and can be either called internally or via messages. For public state variables, an automatic getter function (see below) is generated.

**Comment by chriseth** [comment]
Public state variables create external functions, not public functions.

**Comment by frangio** [comment]
Ah, I understand then. Thank you.

**Comment by axic** [comment]
> For public state variables, an automatic getter function (see below) is generated.

I guess we could clarify this to be "an automatic external getter".

**Comment by pirapira** [comment]
I don't think the getter is particularly automatic compared with other functions.  So, "an external getter function is generated automatically".

**Comment by wjmelements** [comment]
Similarly, automatic getter functions do not implement interface methods, but they should. Example:

```
interface A {
  function decimals() public view returns (uint8);
}
contract B is A {
  uint8 public constant decimals = 1;
}
```

**Comment by fulldecent** [comment]
Related: https://github.com/ethereum/solidity/issues/3411

**Comment by chriseth** [comment]
There were some requests to keep getters being valid as external functions - have we taken a decision on this? I.e. is it fine to "implement" an external interface function using a getter?

**Comment by wbt** [comment]
Issue #3675 is related but not a duplicate.  The behavior I'd most expect, and which I think offers developers the best amount of flexibility, is for the compiler to behave as if the automatically-created getter were already there before considering inheritance, and then have that function in B override the one from A.

**Comment by fulldecent** [comment]
Fixed in latest version.

<img width="611" alt="Screen Shot 2019-11-27 at 20 47 54" src="https://user-images.githubusercontent.com/382183/69770490-3c512800-1157-11ea-99db-2154eed8552a.png">

Ready to close.
