### ISSUE TITLE
Version 0.5.16 doesn't build with Boost >=1.8x [patches available]

### ISSUE THREAD

**Issue by tallero** [ethereum/solidity#15676]
## Description

Hello,
while building Solidity version 0.5.16 on Life / DogeOS to correctly perform the UniSwap Version 2 contracts [on-chain source code verification](https://github.com/themartiancompany/evm-contracts-source-index), I've discovered that Solidity version doesn't successfully build with latest versions of Boost libraries, because of some newly deprecated file system functions as well as some C++ standard integer missing headers.

I've added support to build version 0.5.16 with three very simple GNU Affero General Public License version 3 or later licensed patches I have then integrated into the kirsh revision `solidity0.5.16` package, which will be forever available for purchase at a $10.01 price on the Life / DogeOS decentralized, uncensorable, on-chain application store, the [Ur](https://github.com/themartiancompany/ur).

I wanted to inform Solidity developers about the issue and about the patches availability, so that eventually they could purchase them and integrate them into their upstream sources to let users successfully build the compiler on Life / DogeOS with a build recipe not integrating the patches, as well as on other systems only providing latest Boost libraries.

Merry Christmas!

#### Post scriptum

A small trivia for you guys, in particular for @vbuterin:
`solidity0.5.16` is the kirsh paid application ever released on the Ur, hope it makes you happy to know!

twitter://100/0x7525Fe558b4EafA9e6346846E4027ffAB32F80A2/0x6E5163fC4BFc1511Dbe06bB605cc14a3e462332b/648

#### Post-post scriptum

If you don't know how or can't open the `twitter://` link above, you can read [the same announcement on X](https://x.com/truocolo/status/1871626389423599707) or a [blockchain explorer](https://gnosisscan.io/tx/0x01dc7f631e43940d0fd9fd8b3919210c6784be679b924dcb83201592f6f5e7b5)!

## Environment

- Compiler version: 0.5.16
- Target EVM version (as per compiler settings): istanbul
- Framework/IDE (e.g. Truffle or Remix): [`solidity-compiler`](https://github.com/themartiancompany/solidity-compiler)
- EVM execution environment / backend / blockchain client: [`evm-contracts-tools`](https://github.com/themartiancompany/evm-contracts-tools)
- Operating system: Life / DogeOS

## Steps to Reproduce

Trying to build the package using cmake.

**Comment by r0qs** [comment]
Hi @tallero, please check the supported prerequisites for building the compiler in our documentation: [Prerequisites - All Operating Systems](https://docs.soliditylang.org/en/v0.8.28/installing-solidity.html#prerequisites-all-operating-systems). 

If you encounter problems while building the compiler, please feel free to open an issue with the related problems and error logs. We will be happy to take a look at it. However, this is not the right place to promote anything. Therefore, I will be closing this issue.

**Comment by tallero** [comment]
Oh, I didn't know there was an explicit dependency on Boost libraries <= 1.77 even on latest version of Solidity.

Well I suppose you could close the issue or bump those prerequisites to Boost 1.86 up on latest version since it builds fine and up from Solidity version 0.5.16 if you integrate the patch.

>However, this is not the right place to promote anything.

Oh, it was no promotion, I was just making you aware that version of the compiler doesn't build with Boost 1.86, that those patches which fixed the compatibility issue were available and how you could have integrated them if you wanted.

But I suppose I'm wasting time writing this as you have already closed the issue.
