### ISSUE TITLE
Gas estimate hints

### ISSUE THREAD

**Issue by phiferd** [ethereum/solidity#1568]
The gas estimate feature is nice, but it can quickly become useless if there are functions for which the compiler cannot estimate gas.  For example, calling another contract.  While in a strict sense, it's true that the amount is unknown, it would be nice to allow the developer to annotate a method with some empirically determined estimate/hint.  In cases where the gas estimator cannot estimate gas, it can fallback on the hint.  

Estimates that we computed using one or more hints should probably indicate that they may be less reliable that other estimates.

**Comment by axic** [comment]
A solution would be defining the min and max (as opposed to max only) for each method.

**Comment by chriseth** [comment]
I think the best solution here is to use external tools that have more information about the context and values ranges.
