### ISSUE TITLE
BREAKING: Support enums in the ABI

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1602]
- [ ] modify the type system to support enums as they are, not as integers
- [ ] modify the signatures

**Comment by chriseth** [comment]
Note that if the function signature changes, this might break new contracts interacting with old contracts.

We could just change the json-abi but keep the function signature.

**Comment by fulldecent** [comment]
Attack vector:

```solidity
contract MarketOffer {
    enum {Buy, Sell} type;
    ...
}
```

Somebody deploys that contract.

Somebody ELSE swaps buy/sell and uploads source code and contract metadata to etherscan.

Now your metadata on etherscan is deceptive. 

Why did this happen? Because this adds information to the ABI (again, I hate this word choice) which cannot be validated.

**Comment by chriseth** [comment]
We have many of these examples already. The ABI is always a condensed version of the external interface.

I would argue that this is not a possible attack, though, since it should not be possible to verify the compilation - the hash of the source code is part of the deployed bytecode.

**Comment by VoR0220** [comment]
^^ This. Were this 2016 I would agree with you @fulldecent but as it currently stands this particular attack has been covered up. 

Either way...is it still on the roadmap to make structs "rust like" ?

**Comment by axic** [comment]
I think #2899 will solve this.

**Comment by alextnetto** [comment]
How can we bring this back? it's very much needed.
