### ISSUE TITLE
Duplicate library names cause compiler errors.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#1614]
* Solidity Version: 0.4.8+commit.60cc1668.Darwin.appleclang

Given the following four solidity source files `A.sol`, 'B.sol', `ALibV1.sol` and `ALibV2.sol`.

```javascript
// ALibV1.sol
pragma solidity ^0.4.0;

library ALib {
  function return7() constant returns (uint) {
    return 7;
  }
}

// ALibV2.sol
pragma solidity ^0.4.0;

library ALib {
  function return3() constant returns (uint) {
    return 3;
  }
}

// A.sol
pragma solidity ^0.4.0;

import {ALib as ALibV1} from "./ALibV1.sol";

contract A {
  function return10() constant returns (uint) {
    return ALibV1.return7() + 3;
  }
}

// B.sol
pragma solidity ^0.4.0;

import {ALib as ALibV2} from "./ALibV2.sol";

contract A {
  function return10() constant returns (uint) {
    return 7 + ALibV2.return3();
  }
}
```

When compiled the following error occurs.

```bash
$ solc A.sol B.sol ALibV1.sol ALibV2.sol
ALibV2.sol:3:1: Error: Library "ALib" declared twice (will create ambiguities during linking).
library ALib {
^
Spanning multiple lines.
The other declaration is here: ALibV1.sol:3:1:
library ALib {
^
Spanning multiple lines.
```

This behavior is problematic for the work that's being done to enable smart contract packaging.  There are likely to be libraries which are very common dependencies for many packages.  Consider this simple dependency tree.

```
standard-token --(depends-on)--> math-lib
standard-wallet --(depends-on)--> math-lib
```

In this setup, both `standard-token` and `standard-wallet` would be installed as *top-level* dependencies.  Each of these packages would each have their own installed versions of `math-lib`.  The current behavior of solidity will cause any attempt to compile this project to fail.

Any thoughts on how this could be remedied?

**Comment by chriseth** [comment]
This should be fixed in latest develop, please check. The fix is to prefix library names by their file names.
