### ISSUE TITLE
Check for parser error messages in natspec tests

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1617]
And include tests for all failure cases.

**Comment by axic** [comment]
@hrkrshnn do you know if we check for error messages now?

**Comment by hrkrshnn** [comment]
There are some asserts in `libsolidity/interface/Natspec.cpp` for `@return`. In `libsolidity/parsing/DocStringParser.cpp` there are some parsing errors that are reported using `appendError()` function.

But I don't think there are parsing errors when a tag is repeated.

This https://github.com/ethereum/solidity/issues/8247 might be relevant for this.
