### ISSUE TITLE
Clone binaries: document and add tests OR remove feature

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1618]

**Comment by chriseth** [comment]
I would actually propose to extend it properly once we have EIP5/8.

**Comment by axic** [comment]
I propose to remove it and we focus on #2296.

**Comment by chriseth** [comment]
#2296 needs a factory contract, this is basically the same thing without a factory contract, but yes, let's first focus on the other one.

**Comment by axic** [comment]
Do we agree to remove the clone binary functionality in 0.5.0 then?

One less unspecified feature to be maintained, so we can properly design it and reintroduce it.
