### ISSUE TITLE
Feature request: Warn on missing return value

### ISSUE THREAD

**Issue by PeterBorah** [ethereum/solidity#1628]
I find myself surprisingly often debugging problems that turn out to be caused by not putting "return" before the last line of a function. A warning for a function that declares a return type and doesn't actually return anything would be very helpful.

**Comment by VoR0220** [comment]
Can you give an example? Sounds like this should be an error.

**Comment by PeterBorah** [comment]
Minimal example:

    contract BadAdder {
        function add(uint x, uint y) returns(uint) {
            x + y; // Always returns 0.
        }
    }

**Comment by VoR0220** [comment]
....yeah that should be an error. Idk why we don't do that already. Anybody disagree? Unless they are named variables, the return statement should be found somewhere in the block. While we're at it, we should mandate that if one of the return variables is named that all of them are named. This keeps a decent amount of backward compatibility while also putting in place sensible restrictions on the developer.

**Comment by axic** [comment]
Related #276 and #1467.

**Comment by VoR0220** [comment]
Okay. I see the accepted tag. Time to get to work.

**Comment by chriseth** [comment]
Closing as duplicate.
