### ISSUE TITLE
Impossible to differentiate link references in bytecode

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#1645]
Suppose I have the following solidity file in my project under the path `./a-really-long-directory-name-that-is-quite-long/MyContracts.sol`

```
pragma solidity ^0.4.0;

library A {
  function return10() constant returns (uint) {
    return 10;
  }
}

library B {
  function return13() constant returns (uint) {
    return 13;
  }
}

contract C {
  function return11() constant returns (uint) {
    return A.return10() + 1;
  }

  function return26() constant returns (uint) {
    return 2 * B.return13();
  }
}
```

The compiler will produce the following output

```
$ solc a-really-long-directory-name-that-is-quite-long/a.sol --bin --optimize

======= a-really-long-directory-name-that-is-quite-long/a.sol:A =======
Binary:
60606040523415600b57fe5b5b606a8060196000396000f300606060405263ffffffff60e060020a600035041663f12005ed81146020575bfe5b60266038565b60408051918252519081900360200190f35b600a5b905600a165627a7a723058209906d15f5f839b6eaa5d5fd36bd25399e0737a4a1d3a36019da5e91bb48f66800029

======= a-really-long-directory-name-that-is-quite-long/a.sol:B =======
Binary:
60606040523415600b57fe5b5b606a8060196000396000f300606060405263ffffffff60e060020a60003504166316216f3981146020575bfe5b60266038565b60408051918252519081900360200190f35b600d5b905600a165627a7a7230582086610ca3cae669c8689d63ea85af911f8f3d66de0bdd3564a3ca6a69f348b6650029

======= a-really-long-directory-name-that-is-quite-long/a.sol:C =======
Binary:
6060604052341561000c57fe5b5b6101788061001c6000396000f300606060405263ffffffff60e060020a6000350416633f2c0057811461002c578063fbbb978c1461004e575bfe5b341561003457fe5b61003c610070565b60408051918252519081900360200190f35b341561005657fe5b61003c6100de565b60408051918252519081900360200190f35b600073__a-really-long-directory-name-that-is__63f12005ed6000604051602001526040518163ffffffff1660e060020a02815260040180905060206040518083038186803b15156100c157fe5b60325a03f415156100ce57fe5b5050604051516001019150505b90565b600073__a-really-long-directory-name-that-is__6316216f396000604051602001526040518163ffffffff1660e060020a02815260040180905060206040518083038186803b151561012f57fe5b60325a03f4151561013c57fe5b5050604051516002029150505b905600a165627a7a7230582074f1df49e3f69a4db9066a374b46d2abe8665e58bfad7cef20373957d6b82d520029
```

Given that the file path is sufficiently long it does not appear to be possible to differentiate which link reference in the bytecode belongs to which library since both appear as `__a-really-long-directory-name-that-is__` with the actual filename and library name cutoff.

**Comment by pipermerriam** [comment]
First idea off the top of my head to fix this:  

Instead of using the string `__a-really-long-directory-name-that-is-quite-long/a.sol:B__`  which gets truncated, you could instead use something like `md5('a-really-long-directory-name-that-is-quite-long/a.sol:B')`.  This way the link reference in the bytecode is a fixed length and can be reliably mapped to which contract it belongs to.

Another option would be to not truncate it and instead include the byte length in the string as well.  `__a-really-long-directory-name-that-is-quite-long/a.sol:B:20__`.

**Comment by pipermerriam** [comment]
Oh, and my example here is contrived but with package management these kind of long paths are actually pretty common.

**Comment by axic** [comment]
I think this will rather be solved by the JSON compiler interface to return the positions in the byte code used for linking. With that in place, the compiler will also be flexible at what content to include in that location.

**Comment by pipermerriam** [comment]
Is there an ETA for that? This fundamentally breaks packaging which is
problematic.

**Comment by axic** [comment]
I hope we can close off the spec this coming week, then it is up to implementing it.

**Comment by pipermerriam** [comment]
Thanks for the quick responses. I'll keep an eye out for progress in this.

**Comment by axic** [comment]
Fixed by #1387, but not yet implemented.

**Comment by pipermerriam** [comment]
Any word on when the JSON interface stuff is going to make it's way into a release.  Since `0.4.9` is installed by default and brew/apt doesn't have easy facilities for installing old versions this is causing many of my users problems.

**Comment by LefterisJP** [comment]
+1 I am one of these users :)

**Comment by axic** [comment]
I think it likely could make it into the release following the next one.

**Comment by chriseth** [comment]
As this is not an issue on its own and already has a fix planned I'm closing it.

**Comment by pipermerriam** [comment]
This continues to effect my users.  Is there an estimation on getting it fixed.  Any way that I can help speed up getting a release out that unbreaks library linking?

**Comment by tcoulter** [comment]
This issue is a showstopper for my users as well. Here's the bytecode `solc` generates when full paths are submitted to solc.js: 

<img width="630" alt="screen shot 2017-03-29 at 10 11 26 am" src="https://cloud.githubusercontent.com/assets/92629/24467290/cdeb032e-1468-11e7-972b-f0ac5e1e937e.png">

There's no way to determine which contract should be linked, as they result in the same truncated base path. This prevents us from upgrading Truffle to solc 0.4.10, and keeps us running on 0.4.8. It also prevents us from implementing new features, as the new output in 0.4.9 and 0.4.10 provides much needed references back to source files.

This has become enough of an issue for users to [call out for it specifically](https://www.reddit.com/r/ethdev/comments/61lpxg/how_can_i_use_truffle_with_solidity_0410/). 

As always, appreciate your guy's work. Would love for this bug to be at the top of the list.

**Comment by tcoulter** [comment]
I should add that you don't even need a long directory name as @pipermerriam mentioned, you just need a full path. In general that's enough to fill up the available 36 characters when you also include the contract name.

**Comment by axic** [comment]
#1639 implements the JSON IO as described here: https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description

Once that's merged, the `linkReferences` object is exported and ready to use 😉

**Comment by pipermerriam** [comment]
Any updates on this?  Been another two weeks.  Anyone who wants to use Populus has to install solidity from source which is a huge barrier to entry.

**Comment by pipermerriam** [comment]
If it's not likely to get done in the next week is it possible to get an intermediate release with something done to provide an intermediate fix for this?

**Comment by chriseth** [comment]
@pipermerriam @tcoulter the current idea is that you will use `solc --standard-json`, which takes its input from stdin and writes the result to stdout (in the "standard json" format described behind the link @axic posted above). Does that work for you?

**Comment by pipermerriam** [comment]
@chriseth yes, I'm good with that solution.  I just need *any* solution shipped asap because things have been broken for over two months now.

**Comment by 3esmit** [comment]
Related to #1809
