### ISSUE TITLE
Output of --combined-json changed

### ISSUE THREAD

**Issue by bas-vk** [ethereum/solidity#1656]
go-ethereum offers the `abigen` utility. This utility can generate go binding for a given solidity source file. Abigen uses the solc compiler to extract metadata and uses that to generate binding with the correct identifiers. Recently a user reported the following issue https://github.com/ethereum/go-ethereum/issues/3646.

Abigen calls solc with the `--combined-json` flag. This output has recently changed.

Old:
```
{"contracts":{"Test":{"abi":"[]","bin":"6060604052346000575b60098060156000396000f360606040525b600056","devdoc":"{\"methods\":{}}","userdoc":"{\"methods\":{}}"}},"version":"0.4.5+commit.b318366e.Darwin.appleclang"}
```

New:
```
{"contracts":{"/Users/bas/Development/solidity/test.sol:Test":{"abi":"[]","bin":"60606040523415600b57fe5b5b60338060196000396000f30060606040525bfe00a165627a7a723058206f9044412a2f9a29f53b93219d1c72e0ab78781f0df0747245addce67b218c5b0029","devdoc":"{\"methods\":{}}","userdoc":"{\"methods\":{}}"}},"version":"0.4.10-develop.2017.2.6+commit.3cbdafcf.Darwin.appleclang"}
```

Instead of the contract identifier it now holds the entire path combined with the contract name.
Is that intended and should we update the abigen utility, or is it a bug in solc?

**Comment by axic** [comment]
It is intended. If there is a `:`, the part before is the file name.

**Comment by bas-vk** [comment]
Ok thx, will update abigen.
