### ISSUE TITLE
Return dynamic arrays. 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/solidity#166]
This code 

```
contract C2 {

    uint[] arr;
    function retArr() public returns (uint[] bb)  {
        return arr;
    }
}

contract Test {
    C2 c2;
    uint[] bb;    

    function f() {
      bb = c2.retArr();
    }
}
```

results in the following `solc` (0.1.6) error:

```
/mnt/d/c3.sol:14:12: Error: Type tuple() is not implicitly convertible to expected type uint256[] storage ref.
      bb = c2.retArr();
           ^---------^
```

Any options to return dynamic arrays?

**Comment by nmushegian** [comment]
It appears no:  https://github.com/ethereum/solidity/issues/164

**Comment by chriseth** [comment]
Sorry, this has to wait for a protocol update.

**Comment by cristicmf** [comment]
Type inaccessible dynamic type is not implicitly convertible to expected type int256[] storage pointer. @nmushegian ，Do you have any ideas about it?
