### ISSUE TITLE
If a contract is not payable, `address(C).send()` should not be available.

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1665]
Hm, perhaps we could change it to:
the `send` member is available on all addresses and all contracts, but if it is used for a contract that does not have a payable fallback, an error is generated.
And `address(c).send()` does _not_ generate an error, because you can send to any address.

we could also still provide the member but create an error inside the TypeChecker.

**Comment by VoR0220** [comment]
I'm not sure I agree with this...going to have to elaborate for rules that you have in mind. Just because a function itself is not payable doesn't necessarily mean that it shouldn't be allowed to release funds from the contract.

**Comment by axic** [comment]
If the recipient is not payable, the send will result in a throw. (The discussion was moved from #1651.)

**Comment by VoR0220** [comment]
That part is true, but how far do we take this? How do we examine all external contracts for whether or not they are payable?

**Comment by axic** [comment]
> That part is true, but how far do we take this? 

We send mobs to anyone trying to call it 😉 

In my opinion, if we add this, it could be a warning too, which the user can ignore.

**Comment by VoR0220** [comment]
And again we settle for the warning *sigh* :)

**Comment by chriseth** [comment]
Hm, perhaps we could change it to:
the `send` member is available on all addresses and all contracts, but if it is used for a contract that does not have a payable fallback, an error is generated.
And `address(c).send()` does _not_ generate an error, because you can send to any address.

**Comment by VoR0220** [comment]
^I like that.

**Comment by axic** [comment]
I think I like the warning/error in the typechecker the most as that seems to be most valuable output to a user.
