### ISSUE TITLE
Warn if using .send() and suggest using .transfer()

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1666]
Depends on #610.

**Comment by chriseth** [comment]
There is a policy that all warnings can be silenced by changing the syntax in some way. Is there such a way here? If not, I would prefer to put this warning into remix or changing the wording of the warning for unchecked send.

**Comment by chriseth** [comment]
In a similar spirit, is it possible to let the `resolver` functions return an `AbstractResolver` type?
