### ISSUE TITLE
Parser: scientific notation for numbers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1671]
The scanner has support for scientific notation (`1e1`, `1e-1`, `1e+1`, etc.), thought it is not currently working.

Is it something we want to support or should it be removed?

**Comment by federicobond** [comment]
I approve adding support for scientific notation. It's easy to misread the number of zeros in big numbers.

Other languages also allow optional underscores as thousands separators, like this: `1_000_000`. We might want to consider those too.

**Comment by axic** [comment]
This seems to be a bug in `RationalNumberType::isValidLiteral`, because the scanner seems to be correct.

I'm not sure we should push for the scientific notation, but would rather agree to have underscores.

**Comment by chriseth** [comment]
This fits now quite nicely with decimal fixed point numbers, so yes, let's (re-)add it.

**Comment by chriseth** [comment]
@axic what is the progress on this? I would like to get the next release as bug-free as possible. Is this considered as a bug or a missing feature?
