### ISSUE TITLE
Underscores in number literals

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1677]
It would be nice to support underscores in number literals to have easily readable numbers: `1_000_000`.

Question:
- should it allow multiple underscores next to each other `1__000_____000`?
- should it allow underscores at arbitrary places `1_0_00_000_0_000`?

**Comment by chriseth** [comment]
If we add such a thing, the only reasonable strategy would be to force all numbers except for the first into triples. What about fractional numbers?

Oh and to be honest, I find these underscores extremely ugly. What about `1 000 000`?

**Comment by axic** [comment]
> What about fractional numbers?

I wouldn't allow fractional numbers if we're segmenting it with underscore.

> Oh and to be honest, I find these underscores extremely ugly. What about 1 000 000?

I wasn't a big fan of the underscores, but it gained some following and is kind of understood what it means. Having whitespace could be confusing I think.

**Comment by chriseth** [comment]
I don't think it makes sense to support this only for integers.

**Comment by axic** [comment]
Here's Python's approach: https://www.python.org/dev/peps/pep-0515/

Has most of these questions covered.

**Comment by chriseth** [comment]
looks good!

**Comment by chfast** [comment]
I'd take the design from existing languages. Python's one looks good.

**Comment by Balajiganapathi** [comment]
Hello can I take up this issue?

**Comment by Balajiganapathi** [comment]
Please ignore the first commit (https://github.com/Balajiganapathi/solidity/commit/7a449c472d2f6c39ff52c2a29abf2e55786d9d2e). 

Have created a pull request with the second commit: https://github.com/ethereum/solidity/pull/3120.

**Comment by axic** [comment]
Assigned to @Balajiganapathi

**Comment by jtakalai** [comment]
Note BTW that forcing triplets isn't super great, since in East Asia they separate zeros in quadruplets, and in India they do it in a third way, see https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

**Comment by Balajiganapathi** [comment]
@jtakalai Only hex numbers have strict validation. Decimal numbers don't have any such rules. So, any grouping rule should work.
