### ISSUE TITLE
Move from Javascript scoping rules to C99/C++ scoping rules

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1679]
I think it counters the general aim of safety to retain the scoping rules from Javascript. While historically the language might have been much closer to it, today it provides less resemblance.

The sheer amout of guidance in the documentation to warn about the scoping rules is also an indication that it is not neccesarily providing a safe behaviour.

The two main changes:
- variables must be defined before the first reference
- conditionals and loops have their own scope (can access upvalues of course)

**Comment by chriseth** [comment]
Please just add variable declarations using `let`. There should already be an issue for that.

**Comment by axic** [comment]
I don't see any good reason keeping current scoping and introducing let.

**Comment by chriseth** [comment]
it is a breaking change and introducing let was planned almost 2 years ago, I think, that's why we have it as a reserved word.

**Comment by axic** [comment]
I understand `let` was planned for a while now, but is there a strong benefit of the current scoping rules?

**Comment by axic** [comment]
Update: we have agreed on the last meeting to go forward with this in a breaking release.
