### ISSUE TITLE
Dont issue "Warning: This looks like an address but has an invalid checksum" when numerical operations are involved

### ISSUE THREAD

**Issue by yaronvel** [ethereum/solidity#1685]
In version 0.4.9 I get this warning
```
Warning: This looks like an address but has an invalid checksum
```
on the code
```
publicKeyHash & 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
Would be nice if you can deduce that a number involved in numerical calculation is unlikely to be an address.

(for future readers a work around is to use `0x00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF`)

**Comment by chriseth** [comment]
This warning is triggered by the all-caps of the constant and the fact that it has 20 bytes. Another workaround would be to use lowercase. We could remove the checksum check for all caps, though.

**Comment by chriseth** [comment]
I was wrong, the warning is present for both all-upper- and all-lowercase. Modified the warning message to mention the way to silence the message. I think it is better to warn even if the constant is used in calculations.

**Comment by yaronvel** [comment]
I guess it would be nice if the warning could state that adding (e.g.) a leading zero will prevent the warning.

**Comment by chriseth** [comment]
@yaronvel that's what I did: https://github.com/ethereum/solidity/pull/1746/files#diff-9f2a45efaa7b75ab7ec620d3177cf01aR1586
