### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#169]
```
aeufemio at kingmob in contracts
$ tree
.
├── Digixbot.sol
├── DigixbotConfiguration.sol
├── DigixbotEthereum.sol
└── DigixbotUsers.sol

0 directories, 4 files

aeufemio at kingmob in contracts
$ solc --bin DigixbotEthereum.sol
DigixbotEthereum.sol:24:1: Parser error: Source not found.
import "DigixbotConfiguration.sol";
^---------------------------------^
```

Even relative paths do not work

```
aeufemio at kingmob in contracts
$ solc --bin DigixbotEthereum.sol
DigixbotEthereum.sol:24:1: Parser error: Source not found.
import "./DigixbotConfiguration.sol";
^-----------------------------------^
```

**Version**

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.1.5-23865e39/RelWithDebInfo-Darwin/unknown/int linked to libethereum-1.0.0-ae0b829d/RelWithDebInfo-Darwin/unknown/int
```

**Comment by chriseth** [comment]
The commandline compiler does not proactively search for files on your filesystem:
https://ethereum.github.io/solidity//docs/miscellaneous/#using-the-commandline-compiler

You have to use `solc *.sol` to compile the contracts.

This might change in the future.

**Comment by drandreaskrueger** [comment]
link https://ethereum.github.io/solidity//docs/miscellaneous/#using-the-commandline-compiler is broken

**Comment by chriseth** [comment]
It was moved to solidity.readthedocs.org - content structure should be similar.

**Comment by drandreaskrueger** [comment]
http://solidity.readthedocs.io/en/latest/miscellaneous.html#using-the-commandline-compiler

you're welcome ;-)

**Comment by aertoria** [comment]
while lots of people make it work, it still not working for me.

I use remix

**Comment by sdelvalle57** [comment]
Try this:

const path = require('path');
const fs = require('fs');
const solc = require('solc');

const MyToken= path.resolve(__dirname, 'contracts', 'MyToken.sol');
const StandardToken = path.resolve(__dirname, 'contracts', 'StandardToken.sol');
const StandardBurnableToken = path.resolve(__dirname, 'contracts', 'StandardBurnableToken.sol');
const SafeMath = path.resolve(__dirname, 'contracts', 'SafeMath.sol');
const ERC20Basic = path.resolve(__dirname, 'contracts', 'ERC20Basic.sol');
const ERC20 = path.resolve(__dirname, 'contracts', 'ERC20.sol');
const BurnableToken = path.resolve(__dirname, 'contracts', 'BurnableToken.sol');
const BasicToken = path.resolve(__dirname, 'contracts', 'BasicToken.sol');


var input = {
    'MyToken.sol': fs.readFileSync(MyToken, 'utf8'),
    'StandardToken.sol': fs.readFileSync(StandardToken, 'utf8'),
    'StandardBurnableToken.sol': fs.readFileSync(StandardBurnableToken, 'utf8'),
    'SafeMath.sol': fs.readFileSync(SafeMath, 'utf8'),
    'ERC20Basic.sol': fs.readFileSync(ERC20Basic, 'utf8'),
    'ERC20.sol': fs.readFileSync(ERC20, 'utf8'),
    'BurnableToken.sol': fs.readFileSync(BurnableToken, 'utf8'),
    'BasicToken.sol': fs.readFileSync(BasicToken, 'utf8'),
};

console.log(solc.compile({sources: input}, 1));

**Comment by sdelvalle57** [comment]
Or this:

const path = require('path');
const fs = require('fs');
const solc = require('solc');

const CONTRACTS_DIR = path.resolve(__dirname, 'contracts');

function findContract(pathName) {
    const contractPath = path.resolve(CONTRACTS_DIR, pathName);
    if (isContract(contractPath)) {
        return fs.readFileSync(contractPath, 'utf8');
    } else {
        throw new Error(`File ${contractPath} not found`);
    }
}

function isContract(path) {
    return fs.existsSync(path);
}

function findImports (pathName) {
    try {
        return { contents: findContract(pathName) };
    } catch(e) {
        return { error: e.message };
    }
}

const source = findContract('MyToken.sol');
const compiled = solc.compile({
    sources: {
        'Contract' : source
    }
}, 1, findImports);

console.log(compiled);
