### ISSUE TITLE
Request: expose sender.publicKey

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#1694]
I'm working on a dapp using ecies. I need a users public key, however, don't have a way of accessing it without explicilty passing it as an argument. Would it be possible to expose it via solidty?

**Comment by axic** [comment]
Solidity can only expose data available via the EVM. The whole incoming message or the public key thereof is not available.

**Comment by aakilfernandes** [comment]
Gotcha. Thanks
