### ISSUE TITLE
Better "make install" and fix build info problems

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1704]
This should be a change analogous to https://github.com/ethereum/cpp-ethereum/pull/3565

**Comment by chfast** [comment]
Do you have multiple executables?
Do you want to install libraries?
Do you want to build static libs by default?

**Comment by chriseth** [comment]
There is the main executable `solc` and some others for testing, but only `solc` should be installed, no libraries, etc.
The final binary should not have any additional libraries, so it should at least be statically linked to internal libraries.

**Comment by axic** [comment]
@chfast do you want to take this issue? 😉

**Comment by chfast** [comment]
Current status:
`make install` will install solc correctly

Do you want to install other tools? Like lllc?

**Comment by chriseth** [comment]
Hm, I think it's fine.

**Comment by chfast** [comment]
Fixed then.
