### ISSUE TITLE
CLI should be able to take in longer strings for libraries

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1717]
Currently running into a problem where I have 6 libraries that contain longer than normal names that I'm trying to compile from the CLI with the ```--libraries``` string. 

Getting the following:

```
libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::status: File name too long
```

I found a way by popping all the libraries in a file and pointing to said file but I would think that there ought to be better handling of the string and perhaps have it be held in something that could contain more information. Feel free to close if this isn't worth the time or if it will be handled in the json input/output scheme currently being devised.

**Comment by axic** [comment]
I assume you are hitting this line: https://github.com/ethereum/solidity/blob/develop/solc/CommandLineInterface.cpp#L422 ?

**Comment by VoR0220** [comment]
yup...it would appear so.
