### ISSUE TITLE
Question wrt events

### ISSUE THREAD

**Issue by DaveAppleton** [ethereum/solidity#1726]
In the solidity docs, events are parametrised i.e.
```
    event logANumber(uint a);
    event logAString(string a);
    event logANumString(uint a,string b);
    event logAStringNum(string a ,uint b);
    event logANumNum(uint a,uint b);
    event logANumNumString(uint a,uint b,string c);
```
but the solc compiler also allows 
```
    event logANumberX(uint);
    event logAStringX(string);
    event logANumStringX(uint,string);
    event logAStringNumX(string,uint);
    event logANumNumX(uint,uint);
    event logANumNumStringX(uint,uint,string);
```
and these work perfectly in remix

Are there any issues with the second unparameterised version / is it a solc bug & remix feature?

**Comment by VoR0220** [comment]
not at all afaik. In fact I'm honestly not sure whether or not they should be allowed to be named parameters outside of for ease of understanding what the event is for because the name AFAIK doesn't have any baring on how the event is called/returned.

**Comment by VoR0220** [comment]
Scratch that, it may have some implications at the ABI level (getting a call back in javascript) but shouldn't effect EVM execution at all.

**Comment by chriseth** [comment]
@DaveAppleton events are just special functions, so the same features and limitations apply.

**Comment by DaveAppleton** [comment]
@chriseth - to be confident of your reply - are you saying that we shouldn't use the "X" series?

Ethereum Wallet objects to them but remix doesn't.

![image](https://cloud.githubusercontent.com/assets/1858302/23471662/08a22ac2-fee5-11e6-81b8-12b0cb94d5f6.png)

![image](https://cloud.githubusercontent.com/assets/1858302/23471719/407fbbb2-fee5-11e6-91b4-bc6bcd03d776.png)

**Comment by chriseth** [comment]
Not sure if I understand you correctly. You should name the parameters of an event, but leaving out the name does not change the event, so `logANumString` and `logANumStringX` are essentially equivalent. It seems to be a bug in the json interface parser of mist.

**Comment by DaveAppleton** [comment]
OK - thanks - so it is should be reported to MIST then :-)
