### ISSUE TITLE
I don't get an opcode with mapping to a constructor's line during debugging

### ISSUE THREAD

**Issue by asinyagin** [ethereum/solidity#1730]
Hi,

I'm tracing the following contract:
```
pragma solidity ^0.4.0;

contract Contract {
  uint public num;
  event aNum(uint x);
  function Contract(uint x) {
    aNum(x);
    num = x;
  }
}
```
And I don't get an opcode mapped to the line `num = x`. I get the mapping if I delete the line `aNum(x)`.

```
root@4a541893579d:~# solc --version
solc, the solidity compiler commandline interface
Version: 0.4.9+commit.364da425.Linux.g++
```

**Comment by chriseth** [comment]
I just tried: If the optimizer is enabled, there is no instruction that references `x` alone, but there are instructions that reference the line `num = x`. If the optimizer is turned off, there are instructions for both `x` and `num = x`.

**Comment by asinyagin** [comment]
@chriseth I compile the contract with the command: `solc contract.sol --combined-json bin,abi,srcmap,srcmap-runtime,ast`.

I'll make a full trace of the constructor.

**Comment by asinyagin** [comment]
Here's a full trace of the constructor https://gist.github.com/asinyagin/0c6cbf021446dbc9bdabbd6a90f543d2

There's no mapping to the line 7.

**Comment by asinyagin** [comment]
Sorry, my bad.
