### ISSUE TITLE
Uncaught compiler exception. mappings declared in functions overwrite mappings declared in storage.

### ISSUE THREAD

**Issue by rob-Hitchens** [ethereum/solidity#1731]
#### System information
``````
Solc: `0.3.6-0.4.9'
**Remix**
``````
This was first discovered by ACloudFan and reported here: [http://ethereum.stackexchange.com/questions/12623/solc-compiler-oversight-innappropriate-mapping-declaration-overwrites-storage](http://ethereum.stackexchange.com/questions/12623/solc-compiler-oversight-innappropriate-mapping-declaration-overwrites-storage)

When a mapping is (inappropriately) declared inside a function, data stored will **overwrite data stored in properly declared mappings**. 

**Expected Behavior: mapping inside function = compiler error**. 

```js
contract Mapping {

  mapping(address => uint)  balancesA;
  mapping(address => uint)  balancesB;

  function Mapping() {
    // constructor
    balancesA[msg.sender] = 100;
    balancesB[msg.sender] = 200;
  }

  function getBalance(address addr) returns(uint balanceA, uint balanceB) {

    // If these 2 lines are commented then behavior is as expected
    mapping(address => uint)  balancers;
    balancers[msg.sender] = 500;

    return (balancesA[addr], balancesB[addr]);

  }
}
```

Returns (500,200).  Expected response: (100,200). 

We have found many instances of this behavior using different compilers and using Remix on different platforms. We have found no configuration that produces the expected results.

**Comment by chriseth** [comment]
Thanks for reporting! This is a traditional use of uninitialized variable. The compiler should produce an error here.
