### ISSUE TITLE
Broken --output-dir with --abi option

### ISSUE THREAD

**Issue by LukasGasior1** [ethereum/solidity#1732]
```
mkdir test
cd test
mkdir code out

echo "pragma solidity ^0.4.9;" >> code/test.sol
echo "contract Test {" >> code/test.sol
echo "}" >> code/test.sol

solc code/test.sol --abi -o out
```

outputs
```
Exception during output generation: /build/solc-HPCzPP/solc-0.4.9/solc/CommandLineInterface.cpp(469): Throw in function void dev::solidity::CommandLineInterface::createFile(const string&, const string&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::FileError>
std::exception::what: FileError
[dev::tag_comment*] = Could not write to file: out/code/test.sol:Test.abi
```

when --abi is changed to --bin all works just fine.

**Comment by chriseth** [comment]
Thanks for reporting!

**Comment by chriseth** [comment]
The fix should probably also include a commandline test that runs all options with output directory.

**Comment by LukasGasior1** [comment]
Seems it's just a matter of concatenating full input file path, instead of just the filename to the out path.

**Comment by androlo** [comment]
I could add that it does some pretty weird stuff some times. For example, I have this file:

C.sol
```
pragma solidity ^0.4.0;

contract C {
    function x() constant returns (uint n) {
        return 5;
    }
}
```

When I run this:

`solc --bin --abi -o ./build C.sol`

It will not throw like in Lukas' example, and it will produce a proper `C.bin` file in the output folder, but it will also dump an empty `C.sol` file, rather then the expected `C.abi`.

I also get the throw btw in most cases. Same error.

**Comment by androlo** [comment]
Btw. the compiler used in latest comment: `Version: 0.4.9+commit.364da425.Windows.msvc`

**Comment by androlo** [comment]
Yes, it's Windows, I know... :P

**Comment by chriseth** [comment]
I noticed that this is already fixed in latest develop.
