### ISSUE TITLE
Unable to verify contracts deployed by other contract

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#1734]
https://etherscan.io/address/0x80822493FC792641C9F6b4F14a71b0cd486B4a7d#code This is a BasicCoin deployed by https://etherscan.io/address/0x9b8eb09a59a180e7798fbe7e099c8c351ac56af0#code

I grabbed the constructor arguments from the transaction, they are
`00000000000000000000000000000000000000000000000000005af3107a4000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000087e093f4a39bc0f486f59e45af64d2d669d61b5b0000000000000000000000000000000000000000000000000000000000000003494e440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b494e4449434120636f696e000000000000000000000000000000000000000000`

I use the same code, specify all the same compiler settings in the BasicCoin than the used in BasicCoinManager verification and there is a different compiled bytecode. 
The contract deployed by BasicCoinManager misses a whole chunk of bytes:
`6060604081815260008054600160a060020a0319163317905580610523833960a09052516080516000341115609d576002565b8260016000508190555081600060006101000a815481600160a060020a03021916908302179055506001600050546002600050600084600160a060020a0316815260200190815260200160002060005060000160005081905550505050610479806100aa6000396000f35b818060001415603257600256`

Bytecode compiled by solc v0.4.2+commit.af6afb04 (optimization enabled):
`0x6060604081815260008054600160a060020a0319163317905580610523833960a09052516080516000341115609d576002565b8260016000508190555081600060006101000a815481600160a060020a03021916908302179055506001600050546002600050600084600160a060020a0316815260200190815260200160002060005060000160005081905550505050610479806100aa6000396000f35b818060001415603257600256606060405236156100775760e060020a6000350463095ea7b3811461008457806313af4035146100a257806318160ddd146100c957806323b872dd146100d75780635001f3b5146100f857806370a08231146101075780638da5cb5b1461013a578063a9059cbb14610151578063dd62ed3e1461016f575b34610002576101ae610002565b34610002576101b0600435602435600060003411156101e157610002565b34610002576101ae600435600054600160a060020a03908116339091161461026457610002565b346100025761012860015481565b34610002576101b0600435602435604435600060003411156102bf57610002565b3461000257610128620f424081565b3461000257600160a060020a03600435166000908152600260205260409020545b60408051918252519081900360200190f35b34610002576101c4600054600160a060020a031681565b34610002576101b0600435602435600060003411156103cb57610002565b3461000257610128600435602435600160a060020a03828116600090815260026020908152604080832093851683526001909301905220545b92915050565b005b604080519115158252519081900360200190f35b60408051600160a060020a03929092168252519081900360200190f35b82600160a060020a031633600160a060020a03167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925846040518082815260200191505060405180910390a35033600160a060020a0390811660009081526002602090815260408083209386168352600193840190915290208054830190556101a8565b60008054604051600160a060020a03848116939216917f70aea8d848e8a90fb7661b227dc522eb6395c3dac71b63cb59edd5c9899b236491a36000805473ffffffffffffffffffffffffffffffffffffffff19168217905550565b600160a060020a03841660009081526002602052604090205484908390819010156102e957610002565b600160a060020a03868116600090815260026020908152604080832033948516845260010190915290205487919086908190101561032657610002565b87600160a060020a031689600160a060020a03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef896040518082815260200191505060405180910390a3600160a060020a03898116600090815260026020818152604080842033861685526001818101845282862080548f900390559390925281548c9003909155928b168252919020805489019055955050505050509392505050565b33600160a060020a0381166000908152600260205260409020548390819010156103f457610002565b84600160a060020a031633600160a060020a03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef866040518082815260200191505060405180910390a333600160a060020a03908116600090815260026020526040808220805488900390559187168152208054850190556001925050509291505056`

Bytecode of the deployed contract:
`0x606060405236156100775760e060020a6000350463095ea7b3811461008457806313af4035146100a257806318160ddd146100c957806323b872dd146100d75780635001f3b5146100f857806370a08231146101075780638da5cb5b1461013a578063a9059cbb14610151578063dd62ed3e1461016f575b34610002576101ae610002565b34610002576101b0600435602435600060003411156101e157610002565b34610002576101ae600435600054600160a060020a03908116339091161461026457610002565b346100025761012860015481565b34610002576101b0600435602435604435600060003411156102bf57610002565b3461000257610128620f424081565b3461000257600160a060020a03600435166000908152600260205260409020545b60408051918252519081900360200190f35b34610002576101c4600054600160a060020a031681565b34610002576101b0600435602435600060003411156103cb57610002565b3461000257610128600435602435600160a060020a03828116600090815260026020908152604080832093851683526001909301905220545b92915050565b005b604080519115158252519081900360200190f35b60408051600160a060020a03929092168252519081900360200190f35b82600160a060020a031633600160a060020a03167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925846040518082815260200191505060405180910390a35033600160a060020a0390811660009081526002602090815260408083209386168352600193840190915290208054830190556101a8565b60008054604051600160a060020a03848116939216917f70aea8d848e8a90fb7661b227dc522eb6395c3dac71b63cb59edd5c9899b236491a36000805473ffffffffffffffffffffffffffffffffffffffff19168217905550565b600160a060020a03841660009081526002602052604090205484908390819010156102e957610002565b600160a060020a03868116600090815260026020908152604080832033948516845260010190915290205487919086908190101561032657610002565b87600160a060020a031689600160a060020a03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef896040518082815260200191505060405180910390a3600160a060020a03898116600090815260026020818152604080842033861685526001818101845282862080548f900390559390925281548c9003909155928b168252919020805489019055955050505050509392505050565b33600160a060020a0381166000908152600260205260409020548390819010156103f457610002565b84600160a060020a031633600160a060020a03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef866040518082815260200191505060405180910390a333600160a060020a03908116600090815260026020526040808220805488900390559187168152208054850190556001925050509291505056`

![image](https://cloud.githubusercontent.com/assets/224810/23553483/b0a8dd18-ffff-11e6-931e-777dd2092539.png)

I talked with @mtbitcoin and he said is unable to verify as bytecodes are different, so I'm opening an issue here to see how we can verify this contracts. 

I know I can trust in the contract creator source, but without this verification I cannot read contract from etherscan.io, unless I contact Matt and ask him for adding the ABI to that contract.

**Comment by axic** [comment]
@3esmit is this still an issue?

Have you tried recreating the same with a newer compiler? 0.4.2 had a couple of compiler bugs.

**Comment by 3esmit** [comment]
Not anymore.

**Comment by rushairer** [comment]
I have the same issue too.

**Comment by chriseth** [comment]
@rushairer please open a new issue, your situation might be rather different.
