### ISSUE TITLE
Unable to install Solidity on Mac

### ISSUE THREAD

**Issue by DSofter** [ethereum/solidity#1739]
Solidity beginner here. I tried to follow this tutorial https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial and build my hello world app with Solidity, only to find that I couldn't install Solidity on Mac!

Running the following command 
![image](https://cloud.githubusercontent.com/assets/1687829/23583131/762d5cee-00f0-11e7-8749-138db962999d.png)

gave me:
<img width="568" alt="screen shot 2017-03-04 at 3 37 56 pm" src="https://cloud.githubusercontent.com/assets/1687829/23583145/ab05c4ba-00f0-11e7-82de-cbd7a66c1096.png">

Where the url https://files.pythonhosted.org/packages/b2/d5/bb4bf7fbc2e6b85d1e turned out to be invalid!

Could someone please fix that? Thanks!

**Comment by chriseth** [comment]
It seems a dependency broke. @pirapira could you take a look, please?
Also note that installing solidity like that is not the recommended way anymore (the wiki is slightly outdated, sorry for that). Please follow these instructions: https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#using-the-online-compiler or use solidity via nodejs if that is any simpler for you: https://github.com/ethereum/solc-js

**Comment by pirapira** [comment]
@karalabe can you give me the permission to edit the go-ethereum wiki?  I want to remove the Solidity tutorial there (and also the abandoned Japanese translation, after contacting the translator).

**Comment by pirapira** [comment]
@DSofter I'm trying to reproduce this, but in my environment `sphinx-doc` is not in the dependency.

https://github.com/ethereum/homebrew-ethereum/blob/master/solidity.rb does not mention `sphinx-doc` either.

**Comment by pirapira** [comment]
A direct `brew install sphinx-doc` succeeds for me.

**Comment by axic** [comment]
Is this still a problem? It works for me.

Also I don't have `sphinx-doc` as a dependency. (It is not needed for compiling it, only needed for dvelopment.)

**Comment by axic** [comment]
This should not be an issue given our homebrew package doesn't require sphinx.
