### ISSUE TITLE
Document translation

### ISSUE THREAD

**Issue by fkysly** [ethereum/solidity#1741]
Do you have any plans for document translation? I am very happy to translate your documents into Chinese and provide it to more Chinese developers.

**Comment by chriseth** [comment]
That would be really wonderful! We should talk about the details! Are you on gitter?

**Comment by fkysly** [comment]
yes, I will give you a message on gitter.

**Comment by kcyang** [comment]
Hi, Is it possible to translation to other languages? I want to translate your documents into Korean. Please help for it.

**Comment by ChrisChinchilla** [comment]
Now all tracked here - https://github.com/ethereum/solidity/labels/Translations%20🌍
