### ISSUE TITLE
SolidityLexer.py missing 'delete' and 'for'

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#1743]
Unless there's something I'm missing, it looks to me like the [SolidityLexer.py](https://github.com/ethereum/solidity/blob/d4da4ef35f8118d49bed54f11392036e1d31f7e7/docs/utils/SolidityLexer.py) is missing the _delete_ and _for_ keywords.

**Comment by chriseth** [comment]
Thanks for pointing out!
