### ISSUE TITLE
Request: Compiler Error Message Improvement

### ISSUE THREAD

**Issue by mcqj** [ethereum/solidity#1752]
The compiler error messages are incredibly frustrating.

It is commonly the case that the error message only references a line number in the parser and does not give any indication of where in the source code being compiled the error is occurring.

It is really difficult to contemplate building something of significant size without a compiler that can give you the source file / line number of your error. Its needle in a haystack.

**Comment by axic** [comment]
The current error messages usually do contain the source filename and the line number. Do you have some examples where this is not the case?

The new compiler interface (defined in https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description) will support a more detailed error reporting. Please check the documentation and let us know if you think that level detail could still be improved. Note: this is not yet implemented in the compiler.

**Comment by mcqj** [comment]
Thanks - I should say that the compiler does typically produce filename and line number, just not always. I am using truffle and so running the compiler from truffle.
Here is an example of an error message:-
```
/Users/johnm/workspace/blockster/node_modules/truffle-solidity-utils/node_modules/solidity-parser/index.js:39
      throw e;
      ^
SyntaxError: Expected ")" but "," found.
    at peg$buildStructuredError (/Users/johnm/workspace/blockster/node_modules/truffle-solidity-utils/node_modules/solidity-parser/build/parser.js:1264:12)
    at Object.peg$parse [as parse] (/Users/johnm/workspace/blockster/node_modules/truffle-solidity-utils/node_modules/solidity-parser/build/parser.js:15439:11)
    at Object.parse (/Users/johnm/workspace/blockster/node_modules/truffle-solidity-utils/node_modules/solidity-parser/index.js:34:23)
    at /Users/johnm/workspace/blockster/node_modules/truffle-solidity-utils/index.js:15:32
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```
By trial and error, I can find the line in the code that causes this error. The particular function is shown below. There is one line commented out - without this line no error. When added back in, the error occurs.
```
  function testSongAdded() {
    string memory isrc = 'ABCDEFGHIJKL';
    string memory title = 'Love Me Do';
    string memory composer = 'Lennon/McCartney';
    Songs songs = Songs(DeployedAddresses.Songs());
    songs.add(isrc, title, composer);
//    var (r_isrc, r_title, r_composer) = songs.retrieve(isrc);
  }
```

**Comment by mcqj** [comment]
Having carried out some further investigation, I now believe the issue is somewhere in truffle rather than in the solidity compiler. I am closing the issue and sorry if I've wasted your time.
