### ISSUE TITLE
Endless delegation loop in Ballot example contract

### ISSUE THREAD

**Issue by anoFish** [ethereum/solidity#1753]
The function delegate() in the [Ballot example contract](https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst) does not behave as expected. It is possible to create an endless delegation loop.

An "->" means "delegates to"

Initial state:
- voter1 -> voter2
- voter2 -> voter3

For adding another delegation from voter3 to voter1, a throw is expected, because of a delegation loop. However, this does not work as expected.

The while-loop stops as soon as voters[to].delegate is equal to msg.sender. At this time the variable "to" points still to voter2.

```
while (
    voters[to].delegate != address(0) &&
    voters[to].delegate != msg.sender    // <----- stops here, at the second time
) {
    to = voters[to].delegate;
}

if (to == msg.sender) {
    throw;
}
```
Since the sender is voter3 and "to" is still voter2, the if statement that checks for delegation loops is therefore false and no throw occurs.

Instead of a throw, a delegation to voter2 is created:
- voter3 -> voter2

Now we have the following delegations with a loop between voter2 and voter3:
- voter1 -> voter2
- voter2 -> voter3
- voter3 -> voter2

When we now add an additional delegation from a voter4 to one of this three voters, we stuck in an endless while loop.

**Comment by chriseth** [comment]
Nice find! Do you want to create a pull request to fix it? The code can be found at https://github.com/ethereum/browser-solidity/blob/master/src/app/example-contracts.js

**Comment by anoFish** [comment]
Actually, I meant the code here in the documentation: https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst

The code here is not exactly the same, but obviously it has the same issue:
https://github.com/ethereum/browser-solidity/blob/master/src/app/example-contracts.js

I think it would be useful if the code is the same in both places, and we fix it once. Which one should we use? The code in the documentation is better commented and easier to read. Are there any objections to use this code everywhere?

**Comment by chriseth** [comment]
Yes, good idea! Let's us the better documented code in both places.
