### ISSUE TITLE
Assembly: Implement "jump @label"

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1754]
In order to be compatible with https://github.com/ethereum/go-ethereum/pull/3686, the following rule should be added to the assembly parser:

If a jump opcode is followed by an identifier that starts with an `@`: `jumpX @label`, it is replaced by `label jumpX`.

**Comment by axic** [comment]
I would rather have `solidity` and `geth` flavoured assembly parsers. Currently we do have `"evmasm"` defined as a default (`assembly "evmasm" {}`)

**Comment by chriseth** [comment]
Forcing the flavour is a different issue. Note that `assembly "evmasm" {...}` is only possible for inline assembly.

**Comment by chriseth** [comment]
I guess we won't implement this anymore since we are moving away from jumps.
