### ISSUE TITLE
Very dangerous "ETH ERC20" compatibility attempt

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#1758]
> Introduce .transfer(value) for sending Ether.

Please delete this reckless meme ASAP and stop treating language semantics so recklessly

this is why LLL is making a comeback

**Comment by axic** [comment]
This is predominantly designed for being used with an `address`. The fact that the `contract` type is overloaded to have `.send`, `.call`, etc. is up for a different debate.

**Comment by chriseth** [comment]
@nmushegian thanks for your feedback! Let's talk about that on gitter.

**Comment by chriseth** [comment]
I put this as a blocker for the release for now.

**Comment by chriseth** [comment]
We discussed this issue (at least how we interpret it) during the weekly call and came to the following conclusions:

 - if a contract type has a `transfer` function, it will supersede the transfer function on the address type, so the ERC20 tokens should not be affected. Furthermore, the signature of the ERC20 transfer function is different.
 - adding the address members to contract types does not make much sense, so we will probably deprecate them in the future (add a warning) and eventually remove them. The only real use for these members would be `this.balance`, which might stay.

@nmushegian it would be great to have some more input about what exactly you find reckless about this change. If you can come up with a better name for such a function, we are all ears.

**Comment by nmushegian** [comment]
Let's chat on gitter, if you guys talked it through it's probably OK, but want to double check

**Comment by chriseth** [comment]
Closing this now in the hope that everyone is satisfied.
