### ISSUE TITLE
Disallow unary plus

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1760]
Expressions like `+x` should be disallowed as they serve no purpose and are especially dangerous in situations like `a =+ x`.

**Comment by roadriverrail** [comment]
Is there any scenario where you want to preserve the unary `+`?

**Comment by roadriverrail** [comment]
Ah.  As per #1184 it's been concluded there isn't a meaningful purpose for the unary +.  I'll remove it and replace it with a hard error stating its deprecation.

**Comment by chriseth** [comment]
Please use a warning for now and keep this issue open.

**Comment by roadriverrail** [comment]
I'll step up for this to now be an error as I wrote the deprecation warning.

**Comment by roadriverrail** [comment]
PR for this as experimental feature: #2939 
We should probably continue to leave this open until we fully strip the operator from the parser.

**Comment by 0xKiwi** [comment]
Can there be more detail put behind this change? Many people don't understand what unary + does, I believe adding a tad of more clarity in the official docs would help a lot as right now they just say `The unary + operator is now disallowed.`

**Comment by chriseth** [comment]
@ChrisChinchilla can you handle @IvanTheGreatDev 's request, please?
