### ISSUE TITLE
Re-add require and assert

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1762]
- `require(bool)`: calls `revert()` if the argument is false
 - `assert(bool)`: invalid opcode if argument is false

**Comment by chriseth** [comment]
require might receive an argument for an explanation message or error code in the future

**Comment by axic** [comment]
I'm not sure if we had thought about `expect`.

**Comment by axic** [comment]
According to *thesaurus.com*:

> Synonyms for ensure
> verb guarantee; make secure

> Synonyms for expect
> verb believe strongly; anticipate

> Synonyms for require
> verb need, want

> Synonyms for assume
> verb believe, take for granted

> Synonyms for assert
> verb insist, declare, maintain

Maybe we should look at dictionaries more often to make decisions quicker :)
