### ISSUE TITLE
Problem with internal passing of structs

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#1769]
I managed to create minimum reproducible build of this error involving internal passing of structs. 

Note the below code:

```
pragma solidity >=0.0.0;

library Model {

    struct DataMap {
        mapping(bytes32 => DataElement) rows;
        bytes32[] keys;
        uint size;
    }

    struct DataElement {
        bool exists;
        uint keyIdx;
        Data data;
    }

    struct Data {
        bytes32 id;
        uint uintValue;
        bytes32 bytes32Value;
        address addressValue;
        bool boolValue;
    }
}

library Api {
   function get(Model.DataMap storage _map, bytes32 _id) internal returns (Model.Data);
}

contract Process {

    using Api for Model.DataMap;

    Model.DataMap processData;

    function getDataAsAddress(bytes32 _id) constant returns (address) {
        Model.Data memory data = processData.get(_id);
        return data.addressValue;
    }

}
```

This does not compile currently although it probably should based on our current documentation (unless I'm missing something). This produces the following error:

```
Internal compiler error during compilation:
/Users/vor0220/solidity/libsolidity/codegen/ContractCompiler.cpp(843): Throw in function void dev::solidity::ContractCompiler::appendModifierOrFunctionCode()
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] =
```

The error can be turned off at the cost of not being able to publicly retrieve the variable in getDataAsAddress by making the return an internal return. How might one go about alleviating this? Either way we need to come up with a better error if indeed this is intended functionality.

**Comment by chriseth** [comment]
You can fix it easily by adding an implementation for `Api.get`.
Whether or not libraries that do not implement all functions should be allowed or not is a decision we have to make, I think.

**Comment by VoR0220** [comment]
One reason why this decision was made was to create a potential to create proprietary smart contracts and obfuscate binaries in general, only exposing an API. I would recommend that if the decision is made to get rid of libraries that do not implement all functions, that it come with something akin to @axic 's proposal of an interface type of some kind that can communicate with the libraries via an API format.

**Comment by j-h-scheufen** [comment]
Interesting, thanks for the super fast comment, @chriseth! You're saying if we convert the API library to have functions with an (empty) implementation instead of abstract functions, the error would be avoided?
Can you confirm if this problem is connected to the passing of structs? Because the same setup using only primitives as function parameters / return values seems to work fine.

**Comment by VoR0220** [comment]
@j-h-scheufen no he's saying that we need to implement the function (aka, it cannot be abstracted). That gets it running. Might not be aware of the latter though and that might churn some discussion. Perhaps we should provide an example?

**Comment by axic** [comment]
Right now, the proposed `Interface` keyword (#1688) aims to map the *external interface* of a deployed contract, which is what the ABI defines.

Once structs become part of the ABI, we could consider supporting them in interfaces. In that case, this could work:

```
interface Model {
  ...
}

library Api is Model {
   function get(Model.DataMap storage _map, bytes32 _id) internal returns (Model.Data);
}
```

Although I think `Model` looks cleaner being part of a library.

**Comment by axic** [comment]
I think in order to close this off we should just emit the correct error and not let it reach an ICE.

**Comment by axic** [comment]
Shortest example to trigger the problem:
```
library L {
  function f() internal;
}

contract C {
  function g() { L.f(); }
}
```
