### ISSUE TITLE
Add inline docs to the AST

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1771]
In ASTJsonConverter.cpp, add something like  `make_pair("documentation", _node.documentation() ? toJson(*_node.documentation()) : Json::nullValue)` to all statement nodes. More precisely: To all AST nodes that inherit from `Documented` in AST.h

**Comment by axic** [comment]
@chriseth @djudjuu is this still an open issue?

**Comment by djudjuu** [comment]
yes, currently only contract-documentation is exported to the JSON.

**Comment by axic** [comment]
cc @aarlt

**Comment by montyly** [comment]
Is there any update on this feature? 

That would be super helpful for third-party analyzers to have access to the user-comment

**Comment by hacker-DOM** [comment]
Hey folks, just asking if there is any plans to add this to the development pipeline

We'd love to build a Solidity formatter/prettier/linting tool that takes the AST and automatically formats the document. But the user might be a little surprised if it stripped all of her comments 🙂

**Comment by hacker-DOM** [comment]
Would adding `--include-all-comments` or `--include-comments` as a flag to the compiler (when ast output is selected) be a good API for this feature @chriseth ?

**Comment by chriseth** [comment]
This is actually implemented for the documentation comments (`///` and `/** */`)
