### ISSUE TITLE
Compact AST

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1774]
The current json AST has mainly two drawbacks:

 - it is very verbose
 - if a node has multiple children, it is hard to see the function of each of the children (i.e. in a for loop, you have to know that the second child is the condition in the loop header)

This issue proposes a new AST format:

```js
{
    id: 2,
    src: '23:2:0',
    nodeType: 'FunctionDefinition',
    name: 'f',
    parameters: [
        {
            id: 3,
            nodeType: 'VariableDeclaration',
            name: 'x',
            type: 'uint'
        }
    ],
    returnParameters: [
    ],
    body: {
    }
}
```

Here, the contents of the node itself, its `attributes` sub-object and its `children` sub-object are merged into a single json object and it is readily visible which of the children is the parameters.

It should be possible to generate both versions from more or less the same code. The new version has to explicitly traverse the child nodes and assign names to them (which are just ignored for generating the old version). The new version uses `nodeType` instead of `name` for the type of the AST node. The new version merges attributes into the json object itself, while for the old version, it is in a separate sub-object.

**Comment by chriseth** [comment]
Now that I think of it, this could even develop in a feature where we can export and import the AST (potentially with modifications).

**Comment by axic** [comment]
> Now that I think of it, this could even develop in a feature where we can export and import the AST 

That would be nice. Would the import of AST just replace the source code? For contract verification, would we store a the hash of the AST?

**Comment by chriseth** [comment]
Not sure yet, this feature is firstly only about allowing external tools (write) access to the AST

**Comment by soad003** [comment]
Do you want to implement a separate AST that is directly generated from source or a conversion from the old format to the new one. The second option would make porting code that uses the old AST version easier because they could transform only parts of the AST to the new version.

**Comment by chriseth** [comment]
@soad003 the old AST cannot directly be transformed to the new one because the child nodes are not named. It is probably easier to convert the new format to the old one, but the approach we are currently thinking of will have internal routines that can generate both formats from the same internal data.

**Comment by chriseth** [comment]
This has been implemented by @djudjuu
