### ISSUE TITLE
less-than or greater-than comparison accidentially allowed for addresses

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1775]
Solidity has a separate type `address` that cannot be added or multiplied and only be compared against one another.  I think comparing addresses for equality makes sense, but larger-than or smaller-than does not make sense.

Currently ( 409eb9e3e494ad5a45c14eb7f550ad8fad2b5573 ) the following program passes the compiler:

```
contract A {
  function f() {
    address a;
    address b;
    a < b;
  }
}
```

**Comment by chriseth** [comment]
This was done on purpose. The reason is to allow for data structures that require an order on keys.

**Comment by pirapira** [comment]
That's reasonable.

**Comment by 0xJacobs** [comment]
What the essence of the larger than or smaller, order of keys in what sense???

**Comment by 0xJacobs** [comment]
Can thiis always check that a ! = b too in some cases?? Or just for ordering?
