### ISSUE TITLE
Deprecate throw and suggest revert()/assert()/require() instead

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1793]
I think we had this discussed a few times, but no decision reached yet.

**Comment by chriseth** [comment]
I think throw was a misnomer - we cannot catch anything and reverting a transaction is not actually the same as throwing an exception.

**Comment by axic** [comment]
@chriseth if we are committed to this, I think for the next release we might want issue a warning on `throw;` and suggest `Use require or revert.`.

Then in the breaking or the next breaking release it could be removed.

**Comment by axic** [comment]
Even if we remove throw as a feature, the keyword should be kept. We might be able to introduce something in the future.

**Comment by roadriverrail** [comment]
This looks simple enough for me to knock out quickly.

**Comment by axic** [comment]
We have a warning already, so this issue now is about removing support for `throw` in two ways:
- a) in the parser and the AST. It should still remain as a keyword in `Token.h`, or
- b) turn the warning in the error.

Option a) makes sense if we don't want to use `throw` any time soon.

**Comment by Catspro** [comment]
just simply use revert() or any of the shown error and replace the throw()...Trust me this works

**Comment by axic** [comment]
@roadriverrail will you have time for this soon-ish?

**Comment by roadriverrail** [comment]
@axic I don't think I am.  My commitments at my job have gone up
approximately 3x and it'll probably be a few more months until I come back
around.  I'll see you guys when things get calmer here.

**Comment by axic** [comment]
No worries, Rhett! I'll just remove your assignment so it is up for grabs.
