### ISSUE TITLE
Conversion from literal to string does not work

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1799]
The following code should correctly convert the literal into a memory string but does not allow the conversion (the assignment works, though):
```
contract c {
    function f() {
        string memory x = "abc";
        string("abc");
    }
}
```

**Comment by axic** [comment]
```
_1799.sol:4:9: Error: Explicit type conversion not allowed from literal_string "abc" to string storage pointer
        string("abc");
        ^-----------^
```

**Comment by axic** [comment]
This means `string("abc")` defaults to storage and not memory. The above issue is sorted by extended the error to include both types so it is apparent.

If it should default to memory that is a different issue.
