### ISSUE TITLE
Contract fails to return public member in JS

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#180]
trying to access a contract from Angular.

```
contract foo {
 uint public bar;
}
```

when trying to log it

```
console.log(foo.bar())
```

I get a 

```
Uncaught TypeError: foo.bar is not a function
```

**Comment by chriseth** [comment]
You need `uint public bar;` if you want to access the variable from outside.

**Comment by VoR0220** [comment]
Sorry. Typo corrected.

**Comment by chriseth** [comment]
If this is still happening, then you probably did not create the JavaScript variable `foo` correctly. Please provide some more details.

**Comment by VoR0220** [comment]
I created foo with a constructor

```
contract foo {
 uint public bar;

  function foo () {
     bar = 0;
  }

  function addOne() {
    bar++;
  }
}

```

and then I try to see if it incremented. But I can't even get the value to return. What might be the case?

**Comment by chriseth** [comment]
I think the problem lies in the JavaScript code you use to perform those operations.

**Comment by VoR0220** [comment]
possible. Let me see report back when I find out more.

**Comment by chriseth** [comment]
Closing for now. Please reopen if it turns out to be a problem with Solidity.
