### ISSUE TITLE
Solidity 0.4.10 archive corrupted on Homebrew

### ISSUE THREAD

**Issue by miohtama** [ethereum/solidity#1804]
Not sure if this is the correct place to report an issue, but please guide me forward if needed.

`brew install solidity` doesn't seem to work at the moment, as the source download is corrupted for some reason. I tried install couple of times to confirm that it's not a local download issue.

    ==> Installing solidity from ethereum/ethereum
    ==> Downloading https://github.com/ethereum/solidity/releases/download/v0.4.10/solidity_0.4.10.tar.gz
    ==> Downloading from https://github-cloud.s3.amazonaws.com/releases/40892817/f3804bea-09ae-11e7-8354-b693032ea3cf.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=x
    ######################################################################## 100.0%
    Error: SHA256 mismatch
    Expected: 542a0613f700ff2bd58932307c96a89a702541eb84c8c6bfe3817e70df55ac24
    Actual: a1103f91d240101a90c9bec5243f2436563d3772c4571a352ea7bc21de8706d1
    Archive: /Users/mikko/Library/Caches/Homebrew/solidity-0.4.10.tar.gz
    To retry an incomplete download, remove the file above.

**Comment by ghost** [comment]
I am getting the same error message.
You can override the SHA256 check by running `brew edit solidity` and then replacing the expected hash with the actual. Ofc only do this if you trust that the package that you download is the one you want to install.

**Comment by chriseth** [comment]
Sorry for the inconvenience, should be fixed now.

**Comment by ghost** [comment]
@chriseth thanks! 
@miohtama You can close this issue, it seems to work now.
