### ISSUE TITLE
Not able to link a lib if you have >= 36 symbols in the path

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#1809]
I get the error `There is no lib to link with __src/library/MyAppTokenLibraryN.sol:M__`

This happens because full path does not fits in the library placeholder and than compiler cannot find it.

**Comment by asinyagin** [comment]
That's an error message from Ethereum Studio. It has troubles looking for libraries with long paths and names.

But in general I think 36 symbols are not enough to define a library with its path.

**Comment by chriseth** [comment]
This is already possible if you link at the same time when you compile, but user experience should improve with json-i/o.

**Comment by pipermerriam** [comment]
loosely a duplicate of #1645

**Comment by axic** [comment]
Should be fixed by #1639.  Please reopen if it isn't.
