### ISSUE TITLE
solc binary 0.4.10 has a format issue

### ISSUE THREAD

**Issue by islandBilly** [ethereum/solidity#1813]
I just downloaded the solc file, and moved it to /usr/local/bin, but when I tried to test it, it gave an error that indicates there is something wrong with the binary:
~$  /usr/local/bin/solc --bin Test.sol
bash: /usr/local/bin/solc: cannot execute binary file: Exec format error

Am I missing something? I just wanted to get a local compiler to work with my geth node via web3...

**Comment by chriseth** [comment]
No binary is suitable for all platforms. What exactly is your platform?

**Comment by islandBilly** [comment]
I am currently using the XtraPC, which is a live Linux USB thing built on
the Trusty Ubuntu system. It's running on an aging Toshiba laptop, but I've
had no trouble with geth and Mist so far.

**Comment by chriseth** [comment]
Might it be that you are running a 32 bit platform?

**Comment by islandBilly** [comment]
Ah, yes. My aging laptop has a 32 bit processor. Somehow, I thought that if
geth could run on this system, solc could too, but now you mention it, of
course there is no reason for that to be true. Thanks.

**Comment by chriseth** [comment]
You should still be able to get a 32 bit solc via the PPA system:
```js
sudo add-apt-repository ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install solc
```

**Comment by axic** [comment]
Perhaps we should include `64` or `x64` in the file names of the Linux releases?

**Comment by islandBilly** [comment]
Well if you change the name of the solc binary in the release list, it will
probably see up people's script coding. Everybody knows it as solc. But you
could put a reminder in the readme md...

On Mar 22, 2017 7:54 PM, "Alex Beregszaszi" <notifications@github.com>
wrote:

Perhaps we should include 64 or x64 in the file names of the Linux releases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/solidity/issues/1813#issuecomment-288575576>,
or mute the thread

**Comment by axic** [comment]
It was only added the last release and has the name changed since.
