### ISSUE TITLE
Equip the assembly with a way to talk about stack elements built out of the assembly

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1817]
Sometimes (as inline assembly), the assembly is used as a part of a bigger context.

```
context
<A>
assembly {  {  <B>  }  <C> }
```

For exposing all the power of EVM, from location `<B>` and `<C>`,  the `n`-th topmost stack element at location `<A>` needs to be accessible.

For example, `$5` can mean the fifth topmost stack element when the assembly is entered.  Since these stack elements exist before the assembly starts, they are not internal to the assembly, and so can be only referenced by positions.

This is particularly useful for compiling away Solidity variables in inline assembly.   More generally, when the location `<B>` or `<C>` contains expressions that are not part of the assembly, but part of the outer language.  The compiler of the outer language knows how to interpret those expressions at `<B>` and `<C>` if they were at `<A>`.  For instance, it is the third topmost stack element at location `<A>`.  This is when it is useful to express "the third topmost stack element at location `<A>`" at location `<B>` or `<C>`.

Preferably for the inline assembly implementors, at locations `<B>` and `<C>`, the same syntax should be used for accessing the `n`-th topmost stack element at `<A>`.

**Comment by chriseth** [comment]
Assembly does not have a concept of stack anymore.
