### ISSUE TITLE
Remove Solidity identifiers from the syntax of the assembly

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1818]
The assembly language is going to be used as a mechanism independent from Solidity.  So the syntax of the assembly language should not include Solidity identifiers.

Solidity codes can continue to contain inline assembly with Solidity identifiers, but these inline assembly pieces are not assembly.  When the inline assembly with Solidity identifiers is compiled into assembly, #1817 might be useful.

--

One can argue that the assembly contains generic identifiers and it does not know about Solidity identifiers or other identifiers  In that case, this issue requests removal of free identifiers that are not declared in the assembly.

**Comment by chriseth** [comment]
I think the outcome of a discussion here was that Solidity identifiers are just removed by string replacement, then the inline assembly is just inserted as is into the generated Solidity assembly and both are forwarded to the assembler.

**Comment by pirapira** [comment]
* The assembler mode of `solc` should not accept Solidity identifiers
* The documentation of the assembly should say that random identifiers cause errors

**Comment by chriseth** [comment]
We have a pretty good understanding now of how inline assembly interfaces with IR code in yul, so I'm closing this.
