### ISSUE TITLE
Unreal big gas consumption for contract deploying

### ISSUE THREAD

**Issue by AlexeyBarsuk** [ethereum/solidity#1819]
The problem is described at http://ethereum.stackexchange.com/questions/13469/unreal-big-gas-consumption-for-contract-deploying

**Comment by chriseth** [comment]
Added a comment with a request for the actual source code at the point of the gas consumption jump. Also, it might be better to not use `web3.eth.compile` but using the javascript compiler directly.

**Comment by AlexeyBarsuk** [comment]
code here pastebin.com/4NvTJ8Pv
compiled code: pastebin.com/2rSxAKkc

**Comment by chriseth** [comment]
I was not able to reproduce that with http://remix.ethereum.io - perhaps it is some kind of overflow in the gas counter of the node you are using? Which one is it?

**Comment by AlexeyBarsuk** [comment]
geth    1.5.10-unstable-c8695fae 
maybe it an issue ( I' ll try stable version

**Comment by AlexeyBarsuk** [comment]
Rebuilt geth. 
VERSION:
   1.5.9-stable-a07539fb
Problem exists. I do start node this way 
`geth  --shh --fakepow --nodiscover --maxpeers 1 --nat none --rpc  --rpcapi="db,eth,net,web3,personal,debug" --rpccorsdomain "*" --datadir "/Users/admin/Desktop/etherium-research/private_chain_directory/" --identity "private_node_1"  --networkid 19045    console`

**Comment by AlexeyBarsuk** [comment]
Tryed to use solc-js to compile. Different versions. The same problem. Take a look at EDIT2 http://ethereum.stackexchange.com/questions/13469/unreal-big-gas-consumption-for-contract-deploying

**Comment by AlexeyBarsuk** [comment]
Seems problem appears when bytecode size is ower 48 Kb. Take a look at EDIT 3 http://ethereum.stackexchange.com/questions/13469/unreal-big-gas-consumption-for-contract-deploying

**Comment by AlexeyBarsuk** [comment]
Seems you are right it a problem of node. Created issue https://github.com/ethereum/go-ethereum/issues/13846

**Comment by AlexeyBarsuk** [comment]
Issue can be closed. Contract code cannot exceed 24576 bytes. https://github.com/ethereum/go-ethereum/issues/13846#issuecomment-290159176
