### ISSUE TITLE
Assembly: Strict mode

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#1820]
Assembly should be strict than currently defined. Issues should be warned about for now and turn into errors later. Only the following aspects of assembly should be allowed:

 - [x] directly below a block, only the following is allowed:
   - function definition
   - variable declaration
   - functional assignment
   - function call with zero returns
   - functional instruction that has zero returns
   - block
   - for
   - switch
   - break
   - continue
   - subassembly
- [x] invalidJumpTag should be replaced by `revert()` / `invalid()`
- [x] jumps are disallowed
- [x] DUP and SWAP instructions are disallowed
- [x] labels are disallowed
- [x] statements (elements of a block) are disallowed if they return something onto the stack at the end.

**Comment by axic** [comment]
Need to add a flag to select parsing between "inline assembly" and Julia. In Julia mode it will:

- enable functions
- enable for statements
- enable switch statements
- enable tuple assignments with let
- enable types
- disable labels
- disable assignment from stack
- check that everything is assigned or discarded
- (potentially something else)

**Comment by axic** [comment]
Basically this means introducing a third option to the assembly stack, between the current "regular assembly" and julia mode. This mode is then used by the `assembly` keyword, but is not used by the `solc --assemble` mode.

**Comment by axic** [comment]
> statements (elements of a block) are disallowed if they return something onto the stack at the end.

This should be fixed already with the stack balancing requirement.
