### ISSUE TITLE
Control flow name check for non-strict assembly

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1823]
In the non-strict mode assembly, add checks:

* [ ] before and after the jump, the named stack elements stay at the same positions
* [ ] the control-flow source and destination of `continue` have named stack elements at the same positions
* [ ] the control-flow source and destination of `break` have named stack elements at the same positions
* [ ] the control-flow source and destination of `switch` have named stack elements at the same positions
* [ ] the control-flow source and destination of `for` have named stack elements at the same positions

**Comment by chriseth** [comment]
Closing since non-strict assembly will be phased out soon.
