### ISSUE TITLE
Enforce strict mode in the inline assembly

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1824]
Currently, Solidity exposes inline assembly without checks proposed in #1820 #1821 #1822 #1823 #1825 .  This is not safe.

* strict mode (#1820) should be enforced on the inline assembly
* consider making the next breaking release `0.5.0` earlier for this change

**Comment by axic** [comment]
After #3317 is applied the `--strict-assembly` commandline option will need to be removed too.
