### ISSUE TITLE
Version string does not include commit hash

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#186]
This applies to the binaries from the release repository.

Suggested fix:

Change the build scripts:
- use `$TRAVIS_COMMIT` and explicitly store it in a special file as part of the source code (the one that is also uploaded to the ppa as "orig"), then run the build.

Change cmake files:
- change the build_info cmake to: if `.git` is not present, use the special file (if not available, abort), otherwise read the commit hash from git.

This "special file" should be used to contain the prerelease- and the build specifier (as defined in semver). If the prerelease part is empty, this is a proper release (this should only be done from the release branch and potentially err if such a version already exists). The build specifier should contain the commit hash and potentially the platform and whether the source is modified from the commit. The prerelease specifier should be `-nightly-year-month-day`.

**Comment by chriseth** [comment]
Analysis: The reason is that the binaries are built outside of the git repository. In this case, `buildinfo.cmake` should take the version from some other place.

**Comment by axic** [comment]
@chriseth @bobsummerwill is this still an issue?

I see that currently it defaults to `0` if missing. What should it default to?

**Comment by bobsummerwill** [comment]
We should probably do a quick audit on versioning for both `solidity` and `cpp-ethereum` for development releases.   Ideally we should have commit-hashes, IMHO.

And is va.b.c-hash better than develop-hash?    Does the version number we have in for those development releases serve a purpose?  I'm not sure.

**Comment by axic** [comment]
The version number is useful to have them ordered chronologically.  I do agree the current versioning scheme is misleading.

My proposal:
- `vA.B.C` for releases (there's no commit hash requirement as that can be retrieved from git tags)
- `vA.B.C-alpha<N>-<hash>` or `vA.B.C-develop<N>-<hash>` for the dailies

The `N` should be an incremental number going from 1.

Additionally, I would bump the version number just after a release. So:

```
v0.3.5 - current release
v0.3.6-alpha1-13b324b - nightly
v0.3.6-alpha2-88231aa - nightly
v0.3.6 - next release
```

This is also compatible with semver.

**Comment by chriseth** [comment]
The commit hash should always be available at build time, we need that for source code verification. I don't think that the version number or git tag is enough because it is not authenticated. There are plans to publish that on the blockchain (there is an issue about that), but that is a different matter.

The versioning scheme suggested by @axic looks sound, I would still prefer to include the commit hash for every release, but if it is available in the code (i.e. reproduced in `solc --version`) I'm also fine with that.
