### ISSUE TITLE
Docker image for solc

### ISSUE THREAD

**Issue by dbabits** [ethereum/solidity#207]
Preferably looking for a binary, for RHEL/CentOS.
Compatible with geth --solc flag.
All links seem to be broken.

Thanks

**Comment by chriseth** [comment]
I put some information on https://ethereum.github.io/solidity/ does that help?

**Comment by dbabits** [comment]
every bit of documentation helps, thank you.
I need an rpm.
Short of that, I would prefer to see solc packaged in a docker image,
together with all the other tools, and command-line examples how to use it.
I dont think that dependency on node.js is justified since people use
different languages.
solc should be usable the same way as gcc.
Short of making binaries for every platform, docker seems to be the way to
go.

Thanks again.

**Comment by konradkonrad** [comment]
Hey everyone, a way to use `solc` from `docker` can be found in this gist: https://gist.github.com/konradkonrad/38a02157ddb379e831ea0642a7ee6585

Once you installed the `solc` shell script in your path, it should behave just like a global install.

**Comment by chriseth** [comment]
TODO: integrate into documentation

**Comment by chriseth** [comment]
We should also provide a tiny image based on alpine - without the PPA.

**Comment by VoR0220** [comment]
@dbabits use alpine...it's basically made for docker. Then just run the install_deps.sh after git cloning. At eris, we have a docker image for installing an older version of solidity so that it can work with out compilers service. Check it out here. https://github.com/eris-ltd/eris-compilers/blob/master/Dockerfile
