### ISSUE TITLE
Assembly: simplifying the desugaring with some preprocessing

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2089]
In the documentation in `assembly.rst`, the desugaring of function calls are described as follows (at the bottom of this description).  There is a case analysis whether the function call appears directly in the `let` assignment or not.  I think it is possible to remove the `else` case.

Currently, `let z := f(g(), h())` would fall in the `else` case, but we can preprocess this expression into
```
let z := 0
{ let x := h()
  let y := g()
  z := f(y, x)
}
```
then, we can remove the `else` case in the desugaring process below
```
            // find I such that $funcallI_* does not exist
            $funcallI_return argn  ... arg2 arg1 jump(<name>)
            pop (n + 1 times)
            if the current context is `let (id1, ..., idm) := f(...)` ->
              let id1 := 0 ... let idm := 0
              $funcallI_return:
            else ->
              0 (m times)
              $funcallI_return:
              turn the functional expression that leads to the function call
              into a statement stream
```

**Comment by axic** [comment]
Closing this as this process is gone. We should also consider removing it from the documentation, but that is tracked elsewhere.

@pirapira reopen if you think otherwise
