### ISSUE TITLE
Assembly: desugaring of AssemblyFunctionDefinition circumvents checks

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2091]
In the documentation, in `assembly,rst`, the desugaring process for function definitions contain these lines:

```
        jump($<name>_start)
        let $retPC := 0 let argn := 0 ... let arg1 := 0
        $<name>_start:
```

where the jump source and the jump destination have different stack layouts.  Since the two incoming control flow at `$<name>_start` assume different stack layouts, the assembly analyzer does not give sound analysis.

**Comment by chriseth** [comment]
Right, so this almost looks like we have to add a manual annotation to the syntax...

**Comment by pirapira** [comment]
Not necessarily, I guess replacing `$<name>_start` with `$<name>` is enough.

**Comment by chriseth** [comment]
No, because then it will not be visible outside the block.

**Comment by pirapira** [comment]
We need tunnels below walls, or swimming over the river.

**Comment by pirapira** [comment]
Or, declare a label before defining or using it.
```
ell is label
{  let a := 0
   let b := 0
   ell:
      something
}

let a := x
let b := y
jump(ell)
```

**Comment by pirapira** [comment]
Or, jumping with expressions and labels receiving expressions

```
ell(a, b, retP): {
  something
  jump(retP)<ret_val>
}

{
jump(ell)<x,y,returned>
}

returned(return_value):
{
  continuation
}
```

**Comment by axic** [comment]
Desugaring is gone, so we could close this.
