### ISSUE TITLE
Invalid Warning: This looks like an address but has an invalid checksum

### ISSUE THREAD

**Issue by ruchevits** [ethereum/solidity#2092]
```js
contract Users {
  struct User {
    address addr;
    string name;
  }
  mapping (bytes32 => User) users;
  function create(bytes32 id, string name) {
    users[id] = User(msg.sender, name);
  }
}
```

I'm getting the following error trying to compile it:
> Warning: This looks like an address but has an invalid checksum. If this is not used as an address, please prepend \'00\'.

It looks like an address because it is an address. And it is used as an address.

**Comment by federicobond** [comment]
I cannot reproduce this with latest master or browser-solidity. Which version of solidity are you using?

**Comment by ruchevits** [comment]
solc 0.4.10

**Comment by chriseth** [comment]
@ruchevits if you use literal addresses, you have to use the uppercase / lowercase encoding. This error might also come from the `--libraries` option to solc and not necessarily from the source code itself.

**Comment by ruchevits** [comment]
@chriseth @federicobond Sorry, my mistake, the error actually happens with:

```js
contract Users {
  struct User {
    address addr;
    string name;
  }
  mapping (bytes32 => User) users;
  function create(bytes32 id, string name) {
    address myAddr = 0x0E5CB767CCE09A7F3CA594DF118AA519BE5E2B5A;
    users[id] = User(myAddr, name);
  }
}
```

(when the address is hardcoded)

If I wrap the address in double quotes, the error is: `Error: Type literal_string "0x0E5CB767CCE09A7F3CA594DF118AA519BE5E2B5A" is not implicitly convertible to expected type address.`

`address myAddr = "0x0E5CB767CCE09A7F3CA594DF118AA519BE5E2B5A";`

If I try to explicitly cast literal string to address, the error is: `Error: Explicit type conversion not allowed.`

`address myAddr = address("0x0E5CB767CCE09A7F3CA594DF118AA519BE5E2B5A");`

**Comment by chriseth** [comment]
The warning asks you to add a checksum to your address: https://github.com/ethereum/EIPs/issues/55

**Comment by ruchevits** [comment]
@chriseth Thank you!

**Comment by ronnie173** [comment]
So how exactly did you fix this? Can you please post an example? Because I tried everything

**Comment by axic** [comment]
Just follow what the compiler suggests - it also suggests you the correctly encoded address. Note: the distinction between lower and uppercase letters matters.

**Comment by CHAOWEICHIU** [comment]
I had the same issue, but you can make it work by using `ethereumjs-util`
const { toChecksumAddress } = require('ethereumjs-util')
The address I had was 
`0x8a9a728f64e58db7e790f099bddb3416ccc2eb77`
by using ` toChecksumAddress()` I get 
`0x8a9a728f64E58Db7e790F099BdDB3416ccC2Eb77`

For how they did it, please refer to 
https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L476
