### ISSUE TITLE
Improve checksum error message

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2094]
The address checksum error message is not understandable to people who do not know the checksum algorithm or concept.

We should link the EIP (https://github.com/ethereum/EIPs/issues/55) and provide the correct checksum for addresses in all-caps or all-lowercase.

Related: https://github.com/ethereum/solidity/issues/2092

**Comment by siblingzconsult** [comment]
Please clarify;do you feel that we should link the checksum for the entire EIP Structure in the same Caps?[Upper Caps or LowerCaps]?

**Comment by chriseth** [comment]
This is just about modifying the error message string to include the link.

**Comment by axic** [comment]
It should actually link to https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md or perhaps a section in the Solidity documentation.
