### ISSUE TITLE
AST: import from json

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2096]
It should be possible to import the AST from the new json format (this is also a good way to test that we did not forget anything). The idea is that after parsing and type checking, all information in the compiler can be exported and then later re-imported into a new instance of the compiler and produce the same bytecode.
This opens the door for things like mutation testing.

**Comment by yxliang01** [comment]
This is very useful! @axic @chriseth How is this going?

**Comment by axic** [comment]
There was a PR, #2500, but it was never finished. It is up for taking.

**Comment by yxliang01** [comment]
I see. Thanks for pointing @axic . This looks to be a good effort. However, I don't think I am not familiar with this codebase enough to contribute to this super huge PR... So, wondering whether @djudjuu @ekpyron  will still be contributing to this.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/7153
