### ISSUE TITLE
Support for path globbing in imports.

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#210]
given some source:

```
import "SomeContractLib.sol";
```

We should be able to pass a directory to solc for it to be able to find the files needed without having to do something like:

```
import "some/file/path/that/may/not/be/portable/between/environments/SomeContractLib.sol";
```

Having to do the latter makes it difficult to do cross-environment testing of contracts where directories/compile scripts may not be called from the same paths.  Some of us don't use Mix as part of our workflow.

**Comment by chriseth** [comment]
The current import mechanism is extremely crude and will soon be replaced by a much more flexible framework. Do I understand you correctly that you would like to have something similar to what `-I` does for c compilers?

**Comment by tymat** [comment]
@chriseth That's exactly what I wanted.

**Comment by tymat** [comment]
I don't see the changes?  Was this a mistake to close?

**Comment by chriseth** [comment]
Oh sorry about the confusion. I closed it because it is a feature request, which are tracked in https://www.pivotaltracker.com/n/projects/1189488 and not as github issues.
