### ISSUE TITLE
Assembly: declare labels before they are defined

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2101]
Currently, in the assembly, labels cannot be used out of the block it is defined.  This creates an artificial burden that one cannot jump into a block, except when the label is passed in the runtime dataflow.  This restriction poses problems like https://github.com/ethereum/solidity/issues/2091#issuecomment-289460221 .

This issue proposes to remove this restriction by introducing a label declaration `label(_IDENTIFIER_)`, where `_IDENTIFIER_` is declared to be a label, but unknown to reference any location.

```
{
    label(L2)
    jump(L2)
    {
        L2:
    }
}
```

Note: Usually, I don't propose a new language feature but this proposal is a compromise.  My real preference is to remove scoping rules about labels and put labels in a single global namespace.

**Comment by chriseth** [comment]
Actually in the previous version of assembly, labels were visible everywhere, but I thought that would create problems since it is not modular. I think especially for functions, it would be weird to be able to define them inside blocks (and inside other functions) but still have them visible everywhere. Since functions are turned into labels during the desugaring, I thought it makes sense to have exactly the same visibility rules for labels.

Your proposal could be a clean solution to that problem.

**Comment by chriseth** [comment]
Discussion lead to the following conclusions:

 - `label(L2)` requires an identifier `L2` to be uniquely defined in the current or any of its sub-blocks.
 - It makes it possible to refer to the identifier in the current or any of its sub-blocks (usual scoping rules), also before the point of declaration.
 - Requiring the declaration to be at the beginning of the block makes function definition desugaring non-local, so it should not be enforced.
 - The syntax should be different from a usual expression and we should potentially find a better name. A candidate could be `label x` (without parentheses). This would make `label` a keyword.



@axic what do you think?

**Comment by axic** [comment]
Sorry, haven't seen this in time. Now with Julia being the inline assembly, don't we decided not to have jumps at all and thus this becomes an outdated question?

**Comment by axic** [comment]
Maybe a clobber list like C inline assembly would be nice for scopes :)

**Comment by pirapira** [comment]
I think this issue is now about the language Julia is desugared into.  The idea is that the desugaring would be [easier](https://github.com/ethereum/solidity/issues/2091#issuecomment-289460221).  I had completely forgotten the motivation in the off-line discussion though.

**Comment by chriseth** [comment]
This is not needed anymore.

**Comment by pirapira** [comment]
Nice.
