### ISSUE TITLE
swarm hash in contract binary changes

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#2102]
I am using hashes of the contract binary to determine if the structure of the contract has been changed and it appears if I compile contract A it gets one deterministic hash, but if I compile contract B which inherits contract A then contract A gets recompiled and the swarm hash is changed, therefore indicating that the contract binary data has changed even though the actual contract and its logic are identical.

I'm assuming here that the last 34 bytes in the binary is the swarm hash + 2 extra bytes? I could be wrong, maybe its something else.

Given storage space for these contracts is expensive and limited, and the manifest may not make it into swarm or still be there it would be great to have an option to strip out or not included any metadata including swarm hash from the contract binary output if one wishes.

Here is a similar discussion from January. https://github.com/ethereum/solidity/issues/1571 which got rejected it seems.

Interestingly, if I was able to import from parent directories https://github.com/ethereum/solidity/issues/553 this problem wouldn't effect me..  but it appears the PR https://github.com/ethereum/solidity/pull/554 got rejected.

**Comment by chriseth** [comment]
The reason is that the compiler currently does not automatically determine which source files are needed to compile a certain contract. It just assumes all input files to be necessary.

**Comment by axic** [comment]
@slothbag can you please confirm that #2561 will fix your problem?

**Comment by axic** [comment]
I believe this was fixed via #2561. @slothbag please reopen if you still have the problem with latest solc.
