### ISSUE TITLE
Inheriting a contract with a CTOR with params results in no binary

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#2103]
If you inherit a contract and that contract has a constructor with parameters then solc outputs no binary data for the inheriting contract.

I have tweaked the example given in the docs regarding inheritance.. Contract mortal returns no binary bytes.

```
contract owned {
    function owned(uint someParam) { owner = msg.sender; }
    address owner;
}


// Use "is" to derive from another contract. Derived
// contracts can access all non-private members including
// internal functions and state variables. These cannot be
// accessed externally via `this`, though.
contract mortal is owned {
    function kill() {
        if (msg.sender == owner) selfdestruct(owner);
    }
}
```

**Comment by chriseth** [comment]
You have to provide arguments for the base contract in the derived, this is the only way to pass them to the base contract and thus your derived contract remains abstract and cannot have bytecode. You can forward arguments, though:

```
contract owned {
    function owned(uint someParam) { owner = msg.sender; }
    address owner;
}
contract mortal is owned {
    function mortal(uint param) owned(param) {}
    function kill() {
        if (msg.sender == owner) selfdestruct(owner);
    }
}
```
