### ISSUE TITLE
Internal compiler error: modifier not found in library

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#2104]
```
pragma solidity 0.4.8;

library WithModifier {
    modifier mod() {
        _;
    }

    function withMod(uint self) mod() internal {}
}

contract Test {
    using WithModifier for *;

    function wontCompile(uint _value) {
        _value.withMod();
    }
}
```

Compiler fails to find **mod()** modifier.

**Comment by axic** [comment]
This seems to compile properly with 0.4.13. Please reopen if it persists.

**Comment by lastperson** [comment]
@axic just checked in 0.4.15 and 0.4.19, still doesn't compile.

**Comment by axic** [comment]
Indeed, it seems to fail with 0.4.19.

**Comment by axic** [comment]
The error is:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/CompilerContext.cpp(203): Throw in function const dev::solidity::ModifierDefinition &dev::solidity::CompilerContext::functionModifier(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Function modifier mod not found.
[dev::tag_comment*] = Function modifier mod not found.
```

**Comment by pmumby** [comment]
First, just confirming that this still occurs in 0.4.20, but also wanted to note, this appears to apply to both the method style invocation (using "using") as outlined in example above, as well as direct invocation using fully qualified method name and full signature as in this modified example:

```
pragma solidity 0.4.20;

library WithModifier {
    modifier mod() {
        _;
    }

    function withMod(uint self) mod() internal {}
}

contract Test {
    function wontCompile(uint _value) {
        WithModifier.withMod(uint(1));
    }
}
```

This appears to be a pretty major issue blocking use of modifiers in libraries entirely.

Only workaround for now is to directly replicate the modifier code into the methods that would like to use it, until this is resolved.
