### ISSUE TITLE
Allow accessing function return value inside modifiers

### ISSUE THREAD

**Issue by rainbreak** [ethereum/solidity#2105]
Allow the following:

```
modifier check {
    var ret = _;
    do_something_with(ret);
}
```

This is closely related to https://github.com/ethereum/solidity/issues/49, but doesn't change the function return value.

**Comment by lastperson** [comment]
You can achieve this already through some trickery, check out this:
https://github.com/ChronoBank/SmartContracts/blob/master/contracts/ChronoBankAssetWithFee.sol#L25
`_success[0]` is the return value of the function.

**Comment by martasaparicio** [comment]
Hi there. I'm writing a Smart Contract that follows the StateMachine and AccessRestriction common patterns of Solidity for my thesis.
I have this code:
```
function nextStage() internal { stage = Stages(uint(stage) + 1); } 
modifier transitionNext() { _; nextStage(); } 
function rq_rentalCompleting() transitionNext { if(true){return true;} else {return false;} }
```
So I would like to know if i can in same way get the retruned value of rq_rentalCompleting on the modifier transitionNext so i can change his behaviour accordingly on the nextStage function?
The link @lastperson shared is not working for me...

Thank you :)
