### ISSUE TITLE
array.length returns incorrect value for uninitialized dynamic array 

### ISSUE THREAD

**Issue by travs** [ethereum/solidity#2106]
Solidity compiler: [v0.4.10](https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.10+commit.f0d539ae.js) (same behaviour using latest 0.4.11 nightly, and 0.4.8; have not tried others)
OS: macOS Sierra 10.12.3

I expected the event to output `0` for the `arr.length` call on the empty array, or for the compiler to throw an error since the code tries to get the length of an uninitialized array.
It actually returns `1154414090619811796818182302139415280051214250812`.

Try loading the code below, or equivalently from [this gist](https://gist.github.com/anonymous/98678f7fc80592c4d9685d0720b3e630).
Create it and then run the function `fn` to reproduce.

```solidity
pragma solidity ^0.4.8;

contract C {
  address creator;

  event Log(uint _i);

  function C () {
    creator = msg.sender;
  }

  function fn () public  {
    address[] arr;
    Log(arr.length);
  }
}
```

It may be that this is not related to the solidity compiler, since I have only tried with browser solidity and not geth.

I did a cursory search but couldn't find a similar issue that wasn't closed. Please let me know if you think this belongs in another repo  and I will gladly move it. 😄 

Possibly related issues:

- [Creating a memory array of length 0 generates an infinite loop](https://github.com/ethereum/solidity/issues/590)
- [Browser crashes when allocating empty dynamic array](https://github.com/chriseth/browser-solidity/issues/107)

**Comment by travs** [comment]
## Update:

From running the code below it appears that:
- type of array may not matter
- uninitialized array takes on size equal to value set inside constructor

```solidity
pragma solidity ^0.4.8;

contract C {
  uint someint;

  event Log(string _s);

  function C () {
      someint = 5;
  }

  function fn () public  {
    uint[] arr;
    for (uint i=0; i<arr.length; i++)
      Log('I get written 5 times');
  }
}
```

**Comment by lastperson** [comment]
@travs this is incorrect using of reference types.
When you are putting `uint[] arr;` inside of a function, solidity will reference a storage. In this case it takes first storage entry, to use for `uint[]`, and arrays layout in storage starts with a cell denoting their length, so in your case length becomes the value of `someint`.
If you will put `uint[] memory arr` it will work as expected (might need to initialize it in place).
This is not a bug, though I think compiler should warn about such declarations.

**Comment by chriseth** [comment]
Please also note that the compiler warns you about this incorrect usage of storage references.
