### ISSUE TITLE
Introduce "require()" and "assert()" into documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2118]
The examples in the documentation still contain the pattern
```js
if (!x) throw;
```
All uses of that pattern should be replaced by
```js
require(x);
```
or
```js
assert(x);
```
depending on whether the condition is a condition on inputs or authorization checks or whether it is a check for internal consistency (it might be that the latter is not present in the examples).

**Comment by InfamousVague** [comment]
In what situation is require favored over assert? I can take care of this real quick but want to make sure I understand usage correctly first.

**Comment by chriseth** [comment]
@wski thanks for taking a look here! As I said, I don't think that anything in the documentation actually will use `assert()`. `require()` should be used if you are checking the input or whether a user is allowed to do something or whether the contract is in the correct state to do something. You should use assert for e.g. checking that the state of the contract will never be set to something invalid.

**Comment by InfamousVague** [comment]
I left the bit about exceptions showing throw usage. However, it sounds like this should be removed entirely if the intent is to deprecate `throw`. (referencing https://github.com/ethereum/solidity/issues/1793)
