### ISSUE TITLE
Overwrites when assigning to bytes elements

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#212]
Apologies if this is more of a question for EVM, than Solidity.

Basically what I am doing is trying to find the cheapest (in gas) way to build up a string (using dynamic bytes), but in a non-linear fashion.

The following works:

``` js
string memory holder = "     ";
bytes memory ret = bytes(holder);
ret[0] = 0x30;
ret[1] = 0x31;
ret[2] = 0x32;
return string(ret);
```

Output is: 30313220

But the following will be truncated to the last access:

``` js
string memory holder = "     ";
bytes memory ret = bytes(holder);
ret[2] = 0x32;
ret[1] = 0x31;
ret[0] = 0x30;
return string(ret);
```

Output is: 30

Of course I have digged deeper and found out the very simple reason. Solidity compiles the above into MLOAD + MSTORE instructions, and those according to the the yellow paper, will set the size of the memory to that index (truncate).  Therefore by the last ret[0] it will be truncated to 1 entries.

Simple way to confirm this behaviour:

``` js
string memory holder = "      ";
bytes memory ret = bytes(holder);
ret[2] = 0x32;
ret[1] = 0x31;
ret[0] = 0x30;
ret[3] = 0x20;
return string(ret);
```

Output is: 30000020

_What is the best way to do this properly?_ Mappings work, at a cost.

**Comment by chriseth** [comment]
This is a bug in the compiler and will be fixed shortly. The reason is not that the length is changed, the reason is that adjacent memory locations are overwritten by the assignments.
