### ISSUE TITLE
Compiler does not throw error on improper use of `revert` keyword

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/solidity#2121]
The `revert` keyword can be used in two ways that may cause confusion. As a function call `revert()` in solidity, or as an opcode `revert` in inline assembly.

The compiler however does not throw an error if used as a keyword in solidity instead of a call.  And the compiled bytecode does not contain the REVERT opcode as might be expected.

    contract Revert{
    
    // Improper successful compilation on invalid use of `revert` keyword
    //  JUMPDEST 			function r1() {\n        rever...
    //  JUMP [out]			function r1() {\n        rever...
    function r1() {
        revert;
    }

    // proper use and function of keyword as function call
    //  JUMPDEST 			function r2() {\n        rever...
    //  PUSH 0			revert()
    //  PUSH 0			revert()
    //  REVERT 			revert()
    function r2() {
        revert();
    }
    
    // proper use and function of keyword in assembly
    //  JUMPDEST 			function r3() {\n        assem...
    //  REVERT 			revert
    function r3() {
        assembly {
            revert
        }
    }
    }

**Comment by federicobond** [comment]
This is not an error in Solidity, since you can reference functions in expressions without actually calling them (try replacing `revert` with `sha256`), but in this case, I think there is a potential for introducing serious security bugs in contracts, so perhaps we should give it more thought.

**Comment by federicobond** [comment]
Besides preventing the case you mentioned, I would find it easier to understand `revert` as a statement like `break`, `continue`, or `return` rather than a builtin function call.

**Comment by axic** [comment]
I think this is tracked in #1380 / #1816

**Comment by o0ragman0o** [comment]
Example to execute unreachable code by improper use of `revert`. `a` is assigned `1`. 

    contract RevertFail{
        uint public a;
        function unreachable() returns (bool)
        {
            if (true) revert;
        
            // should be unreachable but executes anyway 
            a = 1;
            return true;
        }
    }
 
I agree use as a keyword would be more consistent with the `throw` like nature of the operation.  However given there are live versions of solidity that allow this, k developers and auditors will have to take into account the additional factor of versions allowing valid and invalid use which may cause additional confusion.

**Comment by federicobond** [comment]
The REVERT opcode is not active in any Ethereum network AFAIK, so it's far from widely used.

**Comment by axic** [comment]
`revert()` will result in a failed execution (and have the same effect as `throw;`). Once the `REVERT` opcode is supported by the network, it will not consume all the remainder gas.

**Comment by o0ragman0o** [comment]
As correctly demonstrated in `function r2()` of my example code.

However here is some [live code as a demonstration](https://www.reddit.com/r/ethereum/comments/65ikqa/eip_140_reverse_bug_bounty/)

**Comment by axic** [comment]
Having read your reddit post, I do not see what bug you are talking about. The way to call revert from Solidity is `revert()` as it is a function, not a language keyword.

One can reference and assign a function without ever calling it, e.g.:
```
function () {
  var a = revert; // reference and assign
  revert; // reference without assignment

  a(); // execute
  revert(); // execute
}
```

The referenced issues deal with providing warnings if an empty statement is encountered. That will provide a warning for `revert;`.

**Comment by o0ragman0o** [comment]
So having read the code of my contract, would you send it money?

**Comment by axic** [comment]
You are not using revert in your code. Your fallback function has an empty statement.

See the documentation http://solidity.readthedocs.io/en/develop/units-and-global-variables.html?highlight=revert#mathematical-and-cryptographic-functions :
> revert(): abort execution and revert state changes

**Comment by Arachnid** [comment]
Setting aside the argument as to whether this should be a keyword or a function, Solidity should definitely output a compiler warning for statements that have no effect, such as `revert` or `2 + 2`.

**Comment by axic** [comment]
@Arachnid that is tracked in #1380 / #1816, as mentioned earlier.

**Comment by o0ragman0o** [comment]
Preference would be for a keyword as it's intent is to depreciate the keyword `throw`. however 0.4.10 would need to be flagged as insecure given the different resultant bytecode of `revert` to future versions

**Comment by axic** [comment]
> Preference would be for a keyword as it's intent is to depreciate the keyword `throw`.

I do not entirely see the relation that `revert()` must be a keyword, because `throw` was one. `assert()`, `require()` and `selfdestruct()` all abort a contract, yet they are not keywords. Furthermore, revert accepts data to be returned (not yet supported in the language).

> however 0.4.10 would need to be flagged as insecure given the different resultant bytecode of `revert` to future versions

This statement assumes that `revert` would become a keyword.

**Comment by o0ragman0o** [comment]
`assert()`, `require()` and `selfdestruct` all take arguments. `revert` needs none

**Comment by axic** [comment]
As mentioned, `revert` can (will) take an argument with the reason of failure (possibly a string).

**Comment by o0ragman0o** [comment]
Sorry, misunderstood that.  Wasn't fully aware of the future intentions of `revert()`

**Comment by chriseth** [comment]
I thought I already created an issue for that. We should at least warn for such uses of `revert` and later implement #1816
