### ISSUE TITLE
Separate subs and actual data in Assembly::m_data

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2130]
sub-assemblies and actual data are both contained in the same container, though they are handled differently both during bytecode generation and assembly output. They should be split into two different containers.

Split out from this conversation: https://github.com/ethereum/solidity/pull/2117/files#r111107476

**Comment by axic** [comment]
@chriseth can you explain this issue? Is it still relevant? If it is not a significant amount of work, I'd opt to do it, but if it is, given the new libyul approach this may be obsolete soon(tm).

**Comment by chriseth** [comment]
It is still relevant and might be not too much work. The problem is that currently, `dev::eth::Assembly::m_data` is used both for sub-assemblies and for actual data, where data uses its hash as index while sub-assemblies use counters.

**Comment by axic** [comment]
It seems that since before this issue was created we had `m_data` and `m_subs`:
```
129b4142d8 Assembly.h           (chriseth          2015-09-10 12:02:18 +0200 171)       std::map<h256, bytes> m_data;
e51f852504 libevmasm/Assembly.h (chriseth          2016-11-11 11:41:50 +0100 174)       std::vector<std::shared_ptr<Assembly>> m_subs;
```

And as far as I can tell the two handled independently. However where it gets messy is `assemblyStream()` and `assemblyJSON()`.
