### ISSUE TITLE
Natspec errors do not correctly report the location of the error.

### ISSUE THREAD

**Issue by simonjanin** [ethereum/solidity#2137]
As I detailed it [here](https://ethereum.stackexchange.com/questions/15357/solidity-error-doc-tag-notice-not-valid-for-statements), having `///` in my code lead to solc giving me the following error: `Doc tag @notice not valid for statements`. I just wanted to comment with `//` but mistakenly added another `/`, which lead to the error.
Since no line number was given, it took me a lot of time to detect the error.

To avoid it, I suggest that the Solidity compiler should be able to detect this error and return where it occurred (at least the line number).

**Comment by axic** [comment]
I can't seem to reproduce:

```
contract A {
  function f() {
    /// TODO
  }
}
```

The code in your link is incomplete, because it references a lot of undefined variables, hence I cannot easily test it to see the problem.

**Comment by simonjanin** [comment]
Indeed, I also could not reproduce the bug with the code you provided.

Yet, I could reproduce it with the following simplified example:

```
pragma solidity ^0.4.2;

contract A {
    function f() returns (bool) {
        /// TODO: careful 
        return true;
    }
}
```

**Comment by dddejan** [comment]
This issue still persists in the latest 0.5 

```solidity
pragma solidity >=0.5.0;
/// @hey hey hey
contract Test {}
```

Gives 

```console
$ solc Test.sol 
Error: Doc tag @hey not valid for contracts.
```

**Comment by axic** [comment]
I think your issue is different, @dddejan can you open a new issue please?
