### ISSUE TITLE
solc  -  malloc(): memory corruption & sysmalloc: Assertion failed - Debian stable - boost 1.55

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/solidity#2141]
# problem
I have problems with `solc` on **Debian Jessie stable**

# examples
Using a standard contract `solc` aborts:

    solc token.sol 
    *** Error in `solc': corrupted double-linked list: 0x0000000001c2b360 ***
    Aborted

different but similar with the Minimum viable token MyToken.sol from https://www.ethereum.org/token

```
solc MyToken.sol 
solc: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted
```

or the full coin code from the same page

```
solc FullCoinCode.sol 
*** Error in `solc': malloc(): memory corruption: 0x00000000006672c0 ***
Aborted
```

# dependencies

Perhaps boost is causing this?

    apt-cache showpkg libboost-dev

shows that I have version 1.55.0.2

```
Package: libboost-dev
Versions: 
1.55.0.2 (/var/lib/apt/lists/ftp.uk.debian.org_debian_dists_jessie_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ftp.uk.debian.org_debian_dists_jessie_main_binary-amd64_Packages
                  MD5: 45501eece42cd718fe21956e16b0e157
 Description Language: en
                 File: /var/lib/apt/lists/ftp.uk.debian.org_debian_dists_jessie_main_i18n_Translation-en
                  MD5: 45501eece42cd718fe21956e16b0e157


Reverse Depends: 
  libresiprocate-turn-client-1.10-dev,libboost-dev
... 
Dependencies: 
1.55.0.2 - libboost1.55-dev (0 (null)) libboost-doc (0 (null)) 
Provides: 
1.55.0.2 - 
```

```
lsb_release -a

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
```

# what to do?

Routes for me now:

1) installing a newer OS after wiping Debian Jessie :-(
2) using an older solidity compiler `solc` which is compatible with Debian Jessie - but which solidity version can guarantee that?
3) upgrading boost somehow (and without destroying my current system). How?
4) your suggestion ...

What would you do?

**Any hints? Please help - thanks!**

**Comment by drandreaskrueger** [comment]
Thx @pirapira 

No hurries though; I have now created a VirtualBox machine based on ArchLinux - and in there -*hooray*- all ETH tools are working fine. 

If you solve this though, then thanks in the name of all Debian users  ;-)

**Comment by pirapira** [comment]
And I tried to make a VirtualBox with Debian stable, and saw "do you disable UEFI secure boot?" and wondered if to proceed.

**Comment by axic** [comment]
@drandreaskrueger @pirapira is this still an issue?

**Comment by axic** [comment]
Please reopen if the issue persists.
