### ISSUE TITLE
Is there a way to use the BYTE instruction?

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#215]
Is there a simple way of using the BYTE instruction on a variable? Basically it could be used to do shift right & masking for 8 bits, which is a fairly common reason why many are looking for shift operators in Solidity. Those might take a while, but the BYTE is already there.

From the yellow paper:

```
0x1a BYTE 2 1 Retrieve single byte from word.
For Nth byte, we count from the left (i.e. N=0 would be the most significant in big endian)
```

E.g. what I would imagine is something like:

``` js
// <value>, <position>
inbyte(0xffbb1133dd, 0)
```

**Comment by chriseth** [comment]
`bytes32` and similar types are planned to be treated as arrays at some point, so it is possible to do things like `bytes32(0xffbb1133dd)[0]`.

**Comment by axic** [comment]
Do you have any planned ETA for that feature?

**Comment by chriseth** [comment]
Probably before the end of the year. Please track the progress here: https://www.pivotaltracker.com/n/projects/1189488 - the story is called "Array access for bytesXX".
