### ISSUE TITLE
Crash on use of variable as rvalue(?) in library contract

### ISSUE THREAD

**Issue by paulperegud** [ethereum/solidity#2154]
* Which version of Solidity you are using
`Version: 0.4.10+commit.f0d539ae.Linux.g++`
* What was the source code (if applicable)
[gist: minimal testcase](https://gist.github.com/paulperegud/351ac17c5d7bdde02b37828416821257)
* Which platform are you running on
`Linux ppsh 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
* How to reproduce the issue
`$ solc --combined-json abi,bin,bin-runtime,devdoc,metadata,userdoc LibContract.sol MainContract.sol`
* What was the result of the issue
Solidity crashes with following message:
`
Internal compiler error during compilation:
/build/solc-a0HVAb/solc-0.4.10/libsolidity/analysis/PostTypeChecker.cpp(51): Throw in function virtual bool dev::solidity::PostTypeChecker::visit(const dev::solidity::ContractDefinition&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = 
`
* What the expected behaviour is
Library contract compiles correctly. Main contract should also compile correctly when library contract is imported.

**Comment by federicobond** [comment]
Could not reproduce with latest version.

**Comment by paulperegud** [comment]
Yep, seems to be fixed.
