### ISSUE TITLE
CLI: read callback should support parsing URLs

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2157]
It should:
- support `file://` for reading
- and raise an error for every other URL
- for backwards compatibility should take a non-url as a file name

**Comment by BlinkyStitt** [comment]
I was just reading the docs (https://solidity.readthedocs.io/en/v0.5.2/using-the-compiler.html) where it suggests using `file://` in the sources section. This leads to `File not found.` (hence this issue). 

Since this task is on the backlog, maybe the docs should be updated to remove `file://`?

**Comment by chriseth** [comment]
`file://` has been implemented.
