### ISSUE TITLE
doc: add description about gas estimate

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2173]
[Solidity features wiki page](https://github.com/ethereum/wiki/wiki/Solidity-Features) contained some description about gas estimation. However, I find nothing similar in the `doc` directory here. Perhaps gas estimation should be explained in the documentation.

Here are the paragraphs removed from the wiki page:

> PT Solidity provides two ways to compute an upper bound on the gas usage of code: A structural one, which can be used to identify expensive statements and a functional one which tries to give an exact gas estimation for each function. Some gas costs depend on the state of the virtual machine, e.g. on the cost of sha3 depends on the length of the argument and writing to storage has different costs depending on whether the storage slot had the value zero or not.
> 
> For the structural gas estimation, the gas cost of each opcode is computed assuming the intersection of all states in which the VM could reach this opcode. These costs are accumulated for each opcode that results from a specific statement (in some situations also other AST nodes) in the AST. So in this mode, opcodes are not counted multiple times even if they occur in loops.
> 
> The functional gas estimation takes a different approach: For each function in a contract, the execution of this function is "simulated". As we want to provide an upper bound on the gas costs independent of the actual arguments, this is sometimes not accurate and may even result in "infinite" gas costs. Note that the gas costs of message-called functions are not included in the gas costs of a function.
>

**Comment by chriseth** [comment]
We should not talk about structural gas estimation (it is not widely used and may be removed soon anyway), only about functional. Mention that `solc --gas` can be used, and how to get it from standard-json.

**Comment by chriseth** [comment]
Also mention that gas estimation excludes the cost of the transaction itself. Explain the various fields that are output when using `solc --gas`.

**Comment by cameel** [comment]
Closing because we decided to remove the gas estimator from the compiler: #13566.
