### ISSUE TITLE
Remove bare callcode

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2174]
`Callcode` is a feature of the EVM now superseded by `delegatecall`. It does not make much sense to keep it for newer Solidity versions. It should still be usable by inline assembly, though. So the tasks of this issue are:

 - [ ] remove the `callcode` member of the address type
 - [ ] change the documentation so that it says that callcode used to be part of the language but is not anymore. It is probably sufficient to mention that it was similar to bare delegatecall.

----

In the [Solidity features wiki page](https://github.com/ethereum/wiki/wiki/Solidity-Features) there was some description about bare callcode.  I cannot find any `.callcode` in the documentation here.  Perhaps we should either explain the syntax in the documentation or remove the feature.

Here are the paragraphs removed from the wiki page:

> Bare Callcode
> 
> Yoichi thinks these descriptions should be ported to the official documentation.
> 
> PT The address type receives a method callcode which is similar to call, but uses CALLCODE instead of CALL when the function is invoked. This means that the code at the given address will be executed in the context of the current contract. Example:
> 
> contract Code {
>   uint m_data;
>   function (uint v) { m_data = v; }
> }
> contract ActualContract {
>   uint public m_data;
>   function f() { Code(0x12345).callcode(7); }
> }
> 
> Assuming the contract Code is deployed at the address 0x12345, calling f() of ActualContract will result in m_data of ActualContract being modified. The user has to ensure that the layout of storage in both contracts is suitable for callcode to be used.

**Comment by axic** [comment]
I think we should deprecate `callcode`. It is not used and provides no benefit to Solidity. Users can still reach it via inline assembly.

**Comment by chriseth** [comment]
If possible, allow callcode but create a warning whenever it is used, that can be merged right now and then remove it completely for 0.5.0.

**Comment by chriseth** [comment]
The error would be created inside `bool TypeChecker::visit(MemberAccess const& _memberAccess)`. There should be a check that the type of the base expression is address or contract and the name of the member is `callcode`.

**Comment by pirapira** [comment]
I suggest making the next releases `0.5.0`, `0.6.0` and so on so that we can make breaking changes in every release.
