### ISSUE TITLE
doc: phrase "ABI type" appears without explanation

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2177]
In the documentation in this repository the phrase "ABI type" appears once but it is never defined or explained.

**Comment by pirapira** [comment]
[Solidity features](https://github.com/ethereum/wiki/wiki/Solidity-Features) wiki page contained the following section. This might be useful.

> External Types
> 
> Yoichi could not find this in the official documentation.
> 
> PT All functions with visibility more than internal should have external types (ABI types) otherwise raise an error. For Contract type external type is address type.
> 
> contract Foo {}
> contract Test {
>     function func() {
>         Foo arg;
>         this.Poo(arg);
>         Poo(arg);
>     }
>     function Poo(Foo c) external {}
> }
> 
> the ABI interface for Poo is Poo(address) when the Solidity interface is still Poo(Foo).

**Comment by aj07** [comment]
I think it got defined at https://solidity.readthedocs.io/en/develop/abi-spec.html?highlight=ABI#application-binary-interface-specification  . Maybe PR was done later.

**Comment by chriseth** [comment]
Yes, the list of all ABI types is defined here: https://solidity.readthedocs.io/en/develop/abi-spec.html?highlight=ABI#types

**Comment by aj07** [comment]
Can we close this, Since Pharse ABI has already been defined

**Comment by chriseth** [comment]
I would still like to have a link to the abi spec.
