### ISSUE TITLE
doc: explain that state variables can be initialized inline

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2178]
[Solidity features](https://github.com/ethereum/wiki/wiki/Solidity-Features) wiki page contained the following section.  The documentation in this repository does not explain this feature yet.  This issue keeps track of adding such explanations to the this repository.

> Inline members initialization
> 
> This point seems to be missing from the official documentation.
> 
> PT Inline members can be initialized at declaration time.
> 
> contract test {
>   function test(){
>     m_b = 6;
>   }
>   uint m_a = 5;
>   uint m_b;
> }

**Comment by pirapira** [comment]
This feature is already [explained](https://github.com/ethereum/solidity/blob/3d1830f3f27f4b915b27472dcfb326223ef77e50/docs/frequently-asked-questions.rst#can-state-variables-be-initialized-in-line) in the frequently asked questions section.

**Comment by chriseth** [comment]
I would consider the FAQ only supplementary. If it is not explain in the main body of the documentation, it should be added.

**Comment by pirapira** [comment]
Then the issue is still open.

**Comment by ChrisChinchilla** [comment]
This will be closed by https://github.com/ethereum/solidity/pull/4499 when it is merged.
