### ISSUE TITLE
Reserve additional keywords

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2182]
`const`, `immutable` (#715), `mutable`, `promise`

**Comment by axic** [comment]
@federicobond suggested to reserve `override` to introduce the explicit `override` keyword on inherited, but locally declared state variables and functions.

**Comment by axic** [comment]
`auto` from #2558.

**Comment by axic** [comment]
`final` and `sealed` from #463.

**Comment by axic** [comment]
`alias`, `typedef`, `define`, `macro` from #1013.

**Comment by axic** [comment]
`topic` from #1241.

**Comment by chriseth** [comment]
Potentially `apply` and `using` for modifier areas.

**Comment by axic** [comment]
`sizeof` perhaps

**Comment by chriseth** [comment]
`unchecked`, so that we can disable the SMT checker for certain parts of the code, especially hand-crafted assembly (rust and c# have a similar feature).

**Comment by axic** [comment]
`reference` for variable references

**Comment by axic** [comment]
`constructor` from #3196 and `fallback` from #3198

**Comment by chriseth** [comment]
@axic do we want to reserve all of these above?

**Comment by axic** [comment]
I don't think any of them is particularly common in current use, though we could say `auto` can be removed from the above list since we deprecated `var`. Maybe it will be useful for something else, so would also consider keeping it.

**Comment by axic** [comment]
`implements` and/or `supports` from #2330

**Comment by chriseth** [comment]
Can this be closed?

**Comment by axic** [comment]
Why?

**Comment by chriseth** [comment]
Ah sorry, my bad.

**Comment by axic** [comment]
`partial` from #649
