### ISSUE TITLE
Document JSON I/O error classes

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2186]
- `JSONError`
- `IOError`
- `InternalCompilerError`
- `Exception`
- `UnimplementedFeatureError`
- ...

**Comment by izgzhen** [comment]
Hi, I'd like to contribute to this issue -- one question, should the documentation go here: https://solidity.readthedocs.io/en/latest/using-the-compiler.html#compiler-input-and-output-json-description or in-tree?

**Comment by axic** [comment]
What do you mean by *in-tree*? The source for the documentation is the `docs` directory in this repo, if that is what you mean by *in-tree*, it should go there.

**Comment by axic** [comment]
I think it should have its on subsection there and not part of the proto-JSON example.

**Comment by izgzhen** [comment]
> What do you mean by in-tree? The source for the documentation is the docs directory in this repo, if that is what you mean by in-tree, it should go there.

By in-tree I mean writing the documentation in the code file. But it looks like I should go to the `docs` directory. Thanks!

**Comment by axic** [comment]
Fixed in #3068.
