### ISSUE TITLE
Strange behaviour with scopes: variable assignments can predate a declaration

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#219]
The following two pieces will compile to the same assembly:

``` js
bytes32 a;
a = bytes32(0xff11);
```

``` js
a = bytes32(0xff11);
bytes32 a;
```

The assembly (using the online compiler):

```
  # Case 1
  JUMPDEST          function Test() {\n        a =...
  PUSH 0            bytes32 a
  PUSH FF11         0xff11
  PUSH 1            bytes32(0xff11)
  MUL           bytes32(0xff11)
  SWAP1             a = bytes32(0xff11)
  POP           a = bytes32(0xff11)
  DUP1          a = bytes32(0xff11)
  POP           a = bytes32(0xff11)

  # Case 2
  JUMPDEST          function Test() {\n           ...
  PUSH 0            bytes32 a
  PUSH FF11         0xff11
  PUSH 1            bytes32(0xff11)
  MUL           bytes32(0xff11)
  SWAP1             a = bytes32(0xff11)
  POP           a = bytes32(0xff11)
  DUP1          a = bytes32(0xff11)
  POP           a = bytes32(0xff11)
```

Having more code in between the assignment and declaration doesn't make any change to it. The variable will be deemed to be declared at the first assignment, as long as it is declared somewhere in the same scope.

I am not sure if this is a bug, or is desired, but it is a bit confusing to be honest. At least it should be documented. Apologies if I have missed it in the documentation.

**Comment by chriseth** [comment]
This behaviour is inherited from javascript. Leaving this open as a reminder to document it better.

**Comment by axic** [comment]
I've figured that it would come from Javascript given you are using v8. However in JS there's not much of a static analyser to weed out things like that, e.g. it accepts:

``` js
for (var i = 0; i < 42; i++) {
  var x;
}
for (var i = 0; i < 42; i++) {
  var x;
}
```

Definitely a documentation piece would help, because the static analyser in Solidity makes you think it is different.

**Comment by chriseth** [comment]
There is a story on the backlog to introduce block-scoped variables, by the way.

**Comment by axic** [comment]
@Denton-L I think you have documented this already?

**Comment by Denton-L** [comment]
Yes, it's documented here: http://solidity.readthedocs.io/en/latest/control-structures.html#scoping-and-declarations

**Comment by axic** [comment]
Thank you @Denton-L.
