### ISSUE TITLE
Clarify AssemblyLocalDefinition grammar rule 

### ISSUE THREAD

**Issue by cgewecke** [ethereum/solidity#2191]
I'm trying to get [consensys/solidity-parser](https://github.com/ConsenSys/solidity-parser) to parse `AssemblyLocalDefinitions` (e.g. let x := 1) correctly and could use some help understanding what kinds of statements are allowed on the right hand side of the assignment. The grammar in `docs/assembly.rst` reads:
```
FunctionalAssemblyExpression = Identifier '(' ( AssemblyItem ( ',' AssemblyItem )* )? ')'
AssemblyLocalDefinition = 'let' IdentifierOrList ':=' FunctionalAssemblyExpression
```
Looking at `elementaryOperation` in [AsmParser.cpp](https://github.com/ethereum/solidity/blob/develop/libsolidity/inlineasm/AsmParser.cpp##L163) its clear that numeric and string literals are also allowed. However, I'm wondering if someone could tell me what other constructions are made possible by [this block of code](https://github.com/ethereum/solidity/blob/develop/libsolidity/inlineasm/AsmParser.cpp#L174-L193).

**Comment by axic** [comment]
That piece of code translates three parser tokens (return, byte and address) into strings literals. Then all string literals are compared against the EVM instructions list and those on the list become `Instruction` AST items, while those which aren't become `Literal`s.

**Comment by cgewecke** [comment]
@axic Thanks so much! Closing.
