### ISSUE TITLE
A for loop is not considered a scope of its own

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#220]
The following code won't compile stating the variable _i_ is redeclared:

``` js
        for (uint i = 0; i < 42; i++) {
        }
        for (uint i = 0; i < 42; i++) {
        }
```

Either of these work:

``` js
        for (uint i = 0; i < 42; i++) {
        }
        for (i = 0; i < 42; i++) {
        }
```

and

``` js
        for (i = 0; i < 42; i++) {
        }
        for (uint i = 0; i < 42; i++) {
        }
```

This means it might be related (or be the same) to the this problem: https://github.com/ethereum/solidity/issues/219

However, going a step further, the following fails too:

``` js
        for (uint i = 0; i < 42; i++) {
            uint tmp;
        }
        for (i = 0; i < 42; i++) {
            uint tmp;
        }
```

Removing the second _tmp_ declaration and just referencing it works. This might suggest the _for_ loop is not considered a separate scope.

Is this desired behaviour or a bug?

**Comment by chriseth** [comment]
This behaviour is inherited from javascript. Leaving this open as a reminder to document it better.

**Comment by Denton-L** [comment]
Documented in #557.

**Comment by axic** [comment]
Thank you @Denton-L, looks great!

**Comment by mcoblenz** [comment]
I just encountered this issue and was confused by it. I don't think Solidity should inherit this behavior from JavaScript. First of all, JavaScript is fixing this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let. Second, Solidity is very far from JavaScript now (for example, not using prototypes like JS does); JS is no longer a suitable model for the language.

**Comment by chriseth** [comment]
We are also planning to introduce `let`.
