### ISSUE TITLE
Error: Events not supported.

### ISSUE THREAD

**Issue by realthargor** [ethereum/solidity#2202]
When running mixed and having a sol file like this:
`contract EventDefinitions {
    event FooBarEvent(address adr);
}`
Analysis-Tab reports: "Error: Events not supported."
Reason for that seems to be solidity/libsolidity/formal/Why3Translator.cpp:203

Since the contract is working fine I assume the Why3Translator is outdated.

**Comment by chriseth** [comment]
Thanks for the report! It is not outdated but incomplete. We plan to remove it altogether, so I'm just closing this.
