### ISSUE TITLE
Solidity 0.4.10 produces different byte code on different platforms (probably just adds garbage at the end)

### ISSUE THREAD

**Issue by 3sGgpQ8H** [ethereum/solidity#2204]
I compile the following smart contact with solc 0.4.10 (optimisations enabled):

    pragma solidity ^0.4.10;
    
    contract Foo {
    }

On MacOS X it produces the following byte code:

60606040523415600b57fe5b5b60338060196000396000f30060606040525bfe00a165627a7a72305820**0b12a420c478b66a2e48bd4de472c2cd0cf2d34f77ed5a69ebf1f64b5b0fa532**0029

When I use online solidity compiler (https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.10+commit.f0d539ae.js&optimize=true) it produces the following byte code:

60606040523415600b57fe5b5b60338060196000396000f30060606040525bfe00a165627a7a72305820**cfb75ffd8494c84a2b91c71eb0dec74c4f10c462d920d5b598d02573b6922d25**0029

Compiling under MS Windows produces byte code that differs from both, MacOS and online compiler.

I experimented with different smart contracts.  For particular contract, byte code length is the same on all platforms, as well as first (length-34) bytes and last two bytes.  So the different part is always located between (length-34) and (length-2).  The length of different part is always 32 bytes.  Content of the different part seems to depend on the code of smart contract.  I tried to disassemble the different part and it looks like garbage.

**Comment by axic** [comment]
The end of the bytecode contains the hash of a metadata, which contains the compiler version among other things. See http://solidity.readthedocs.io/en/develop/miscellaneous.html#contract-metadata for explanation.

**Comment by 3sGgpQ8H** [comment]
Thank you for explanation.  Hope source code validators in mainstream blockchain explorers are able to handle this.  I just followed advice on https://ethereum.stackexchange.com/questions/9881/is-the-solidity-compiler-deterministic reporting this issue.

**Comment by axic** [comment]
The exact same bytecode should be produced if using the very same compiler (e.g. use the same platform too). We have tests in place which compares bytecode produced by compilers on different platforms to ensure they are identical (apart from the compiler version in the hash).

The online verification tools should be aware of this.

**Comment by chriseth** [comment]
@axic the compiler version in the hash is also identical cross platform. If you use the same source (including filename paths) and the same compiler version, you should always get exactly the same result.

**Comment by chriseth** [comment]
@mikhail-vladimirov as I said in the other comment: It might be that the file names produce the difference.

**Comment by chriseth** [comment]
Can you create the metadata json (using `--metadata`) and compare those across platforms?

**Comment by 3sGgpQ8H** [comment]
Looks like metadata JSON does not contain compiler's binary hash, but does contain relative paths of .sol files as specified in `solc` command line.  So specifying the same file as `Foo.sol` or `./Foo.sol` leads to different metadata hashes.

**Comment by chriseth** [comment]
@mikhail-vladimirov right! So is this issue resolved? If yes, please close it.

**Comment by 3sGgpQ8H** [comment]
Yes, my problem is resolved, because
1) I now understand that Solidity compiler works as designed and such behaviour is not a bug
2) Such behaviour does not prevent byte code from being successfully verified by etherscan.io and similar blockchain explorers
So I may not close the issue.

But it looks a bit weird for me that things such as relative paths of source file affect metadata hash, while such thinks may not affect byte code even in theory.  Probably metadata should be somehow normalized before hashing.
