### ISSUE TITLE
Create "add error / warning" helper function

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2209]
The code
```
	auto err = make_shared<Error>(Error::Type::Warning);
	*err <<
		errinfo_sourceLocation(_location) <<
		errinfo_comment(_description);

	m_errors.push_back(err);
```
is duplicated in lots of files. There should be a helper function for these. If we add a helper, then it should still be simple to use. Currently, we have `addTypeError(location, "description")`.

**Comment by chriseth** [comment]
No yet 100% sure how to do this nicely. A base class containing the `m_errors` array would be nice, so we do not have to supply it for each of the calls.

**Comment by roadriverrail** [comment]
I've got this one.

**Comment by chriseth** [comment]
@roadriverrail is this finished?

**Comment by roadriverrail** [comment]
@chriseth I seem to recall the ErrorReporter work getting merged in a couple of weeks ago.  Yes?
