### ISSUE TITLE
`.call` with callData resets string in storage

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/solidity#2226]
The following test contract allows a string `myS` to be set in three different ways:
```
contract Test {
    string public myS;

    function f(string _s) {
        myS = _s;
    }
    
    function callF() {
        this.call(bytes4(sha3("f(string)")), "test");
    }
    
    function setF() {
        f("test");
    }
}
```
Calling `callF` seems to just reset the storage of `myS` with the default value (empty string) instead of setting it to `"test"`. The same pattern works for all other types that I tested (uint and address).

I tested this using the latest compiler (older versions seem to behave the same way) and remix as well as Ether Camps Ethereum Studio.

**Comment by axic** [comment]
@SCBuergel a string is a dynamic ABI item and as such is encoded differently. The offset where the string starts in the calldata is the first parameter followed by the length and the actual string at the given offset:

```
91e145ef // sig
0000000000000000000000000000000000000000000000000000000000000020 // offset for dynamic parameter
0000000000000000000000000000000000000000000000000000000000000004 // length of string
7465737400000000000000000000000000000000000000000000000000000000 // string
```

Here is the full specification for the ABI: https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI
