### ISSUE TITLE
MacOS 10.9 error: chosen constructor is explicit in copy-initialization

### ISSUE THREAD

**Issue by egalleye** [ethereum/solidity#2227]
I had an issue with build failing for the release branch of solidity on MacOS 10.9.5 

The error I got:
*$ cmake .. && make
...
error: 
      expected '(' for function-style cast or type construction
  ...const*> const& _seen = std::set<VariableDeclaration const*> const{}*

I wrote in a fix to ./libsolidity/analysis/PostTypeChecker.h that allowed it to compile. If interested I have the change @ https://github.com/egalleye/solidity/blob/release/libsolidity/analysis/PostTypeChecker.h

**Comment by egalleye** [comment]
btw, I'm new to filing issues/contributing so if I make any mistakes or don't include important info please let me know..

p.s.
Is there a desired format for filing issues?

**Comment by chriseth** [comment]
Thanks, this seems to be the proper fix! Can you create a pull request out of your develop branch? @roadriverrail can help you if you experience difficulties.

**Comment by egalleye** [comment]
Okay, I've submitted a pull request. I found and read through the contribution section, hopefully I got everything right.

Thanks for the quick response!
