### ISSUE TITLE
grammar.txt: FunctionCall & FunctionCallArguments

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#2234]
Should it be

```
FunctionCall = ( PrimaryExpression | NewExpression | TypeName ) ( ( '.' Identifier ) | ( '[' Expression ']' ) )* '(' FunctionCallArguments? ')'
FunctionCallArguments = '{' NameValueList? '}'
                      | ExpressionList
```

instead of

```
FunctionCall = ( PrimaryExpression | NewExpression | TypeName ) ( ( '.' Identifier ) | ( '[' Expression ']' ) )* '(' FunctionCallArguments ')'
FunctionCallArguments = '{' NameValueList? '}'
                      | ExpressionList?
```

?

**Comment by axic** [comment]
Is `func({})` valid?

**Comment by federicobond** [comment]
They are equivalent, right? Or am I missing something? Only difference would be the implied parse tree when function is called with no arguments.

**Comment by walter-weinmann** [comment]
You have already `FunctionCallArguments?` hence `ExpressionList?` makes not really sense.

**Comment by axic** [comment]
@federicobond @walter-weinmann was this solved or is this still an outstanding quesiton?

**Comment by federicobond** [comment]
I never understood what @walter-weinmann was referring to.
