### ISSUE TITLE
Create a release notes JSON

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2238]
This JSON should contain:
- `notes` (the "readme")
- `artefacts` (object), where the artefact name is the key and the content is as follows:
  - `urls` (a list of URLs, including Github and Swarm links)
  - `sha256` hash of the file

This JSON should be uploaded to Swarm and the link be published on the Github release notes.

Probably it should be an actual JSON array of all previous releases.

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/628

**Comment by axic** [comment]
Oh, we still don't have this...

**Comment by axic** [comment]
Alternatively this could be part of the solc-bin repository, which would practically mean just adding a changelog node to the release binaries. In that case we would need to publish the hashes of each of the list files (i.e. `wasm/list.json`, `linux-amd64/list.json`, and so forth) to provide authentication to builds for various platform.

I still think it would make more sense keeping a `releases.json` in this repository (containing the changelog as well as the names, links, and hashes of the release binaries which are currently uploaded to the release page) and in the future committing the hash of the `releases.json` in some form. A potential option would be using an ENS entry under some team controlled domain.

I could be convinced that keeping all this in the solc-bin repository is the better place.

A suggested layout is a JSON array, where the last (trailing) entry is the newest release -- so it works in an append-only fashion. Each entry looks like the following:
```
{
  "version": "0.8.6",
  "date": "2021-05-20",
  "changelog": "<content of the release changelog>",
  "bugs": "<content of the bugs.json>",
  "artefacts": {
    "linux-amd64": { "urls": [...], "sha256": "..." },
    ...
  }
}
```

Alternative option is to make `artefacts` an array:
```
"artefacts": [
  { "kind": "linux-amd64", "name": "solc-linux-amd64", "urls": [...], "sha256": "..." },
  { "kind": "wasm", "name": "solc.wasm", "urls": [...], "sha256": "..." },
]
```

(In https://github.com/ethereum/solc-bin/pull/19 there is an argument to keep those `list.json`s a relative paths.)

**Comment by axic** [comment]
I still think this would be a cool feature.
