### ISSUE TITLE
[Documentation] - Include examples on Standard JSON I/O

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#2240]
Currently it's a bit bare, could definitely use some example of the piping and passing in of different inputs.

**Comment by axic** [comment]
What kind of examples do you think of?

**Comment by VoR0220** [comment]
I would imagine some string passing of json input and retrieving outputs?

**Comment by axic** [comment]
Isn't that documented?

What level of detail is needed in an example? How many examples are needed? What features have to be covered?

Alternatively if you could submit a PR with examples that would help 😉

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to contribute with a PR.
