### ISSUE TITLE
Solidity shouldn't warn about unused locals when the variable is used in inline assembly

### ISSUE THREAD

**Issue by Arachnid** [ethereum/solidity#2242]
Presently, Solidity warns about unused locals when a local or function argument is used only in an inline assembly block.

**Comment by mezrin** [comment]
Mist do not let to deploy a contract from source code because of this warning. I found a way to bypass it: `_myAddress = _myAddress;`. Just assign variable to itself.

**Comment by axic** [comment]
Fixed by #2265.

**Comment by gary0318** [comment]
Hey. This line is giving me the Unused local variable message inside of mist, and I can't figure out how to get around it:--->

  var _ = admin.call.gas(GAS_LIMIT).value(this.balance)();

How would I do it?
