### ISSUE TITLE
documentation fields of Json-AST are empty

### ISSUE THREAD

**Issue by djudjuu** [ethereum/solidity#2243]
Many kinds of ASTNode-classes (subclasses of Documented) have a documentation field that can be exported by the ASTJsonConverter (and afterwards be filled by the ASTJsonImporter)

**Comment by roderik** [comment]
@djudjuu do you think this is also possible for documentation on functions? I do not really have an idea on where to start looking :)

**Comment by axic** [comment]
@aarlt since you've worked on natspec changes, do you want to check this one out?

**Comment by axic** [comment]
@chriseth isn't this solved now by #7834 ?
