### ISSUE TITLE
[Documentation] Improve warning when returning dynamic arrays

### ISSUE THREAD

**Issue by Qqwy** [ethereum/solidity#2253]
It took me quite some time to understand the warning on the [Arrays section of the Solidity documentation](http://solidity.readthedocs.io/en/develop/types.html?highlight=arrays#arrays):

> Due to limitations of the EVM, it is not possible to return dynamic content from external function calls.  The function f in contract C { function f() returns (uint[]) { ... } } will return something if called from web3.js, but not if called from Solidity.
>The only workaround for now is to use large statically-sized arrays.

It was only after I read through #164, specifically [this comment](https://github.com/ethereum/solidity/issues/164#issuecomment-149846605), that I understood that this restriction only happens from within contracts calling functions in remote contracts, and that returning a dynamic array (such as a string) as result of a direct invocation from outside of the EVM is possible.

I believe that this warning could be improved to be more clear on the difference of invocating a function from outside of the EVM and from somewhere else inside the EVM.

**Comment by chriseth** [comment]
This is superseeded by updating the documentation to state that this limitation is no longer in effect.
