### ISSUE TITLE
The compiler doesn't recognize auto generated functions as a valid abstract interface implementation

### ISSUE THREAD

**Issue by yudilevi** [ethereum/solidity#2254]
Hey,

In the following example -

```
contract AbstractToken {
    function totalSupply() public constant returns (uint256 totalSupply);
}

contract Token is AbstractToken {
    uint256 public totalSupply = 0;
}
```

'Token' will be generated by the compiler as an abstract contract, even though the auto generated compiler function for `totalSupply` matches the abstract interface signature.

Was tested on solidity 0.4.11

**Comment by chriseth** [comment]
The auto-generated function does have a different signature than the one in the interface. The one in the interface requires an external and an internal implementation, while the internal implementation is missing for the auto-generated function. There is no way to call `totalSupply()` internally in `Token`. Sorry that the keyword `public` for auto-generated functions is misleading here. If you change `AbstractToken` to `function totalSupply() external constant ...`, it should work.

**Comment by yudilevi** [comment]
Gotcha - thanks for the clarification.

Also note that the compiler does allow both public and external for 2 different functions with the same name in this case - not sure if that's supposed to be supported or not, cause I imagine that can create issues of its own.
