### ISSUE TITLE
dynamic array declaration and assign only one item compile error

### ISSUE THREAD

**Issue by yuanaichi** [ethereum/solidity#2259]
below is my contract:
`
contract TransferContract {
  address owner;
  address[] public receivers = [
    0x6aebda91307743b691b57ce664cdbf24beb02b61
  ];
}
`

when receivers have only one item,  have a internal compile error like this

`Internal compiler error:
Compiliation failed. See above.`

when receivers have more than one item, no error

is this a bug??

**Comment by axic** [comment]
Can you tell me what compiler version are you using? Cannot reproduce with 0.4.10 or 0.4.11.

**Comment by yuanaichi** [comment]
i don't know what compiler I used , I use Mist client. 
Now I upgrade my Mist client from v0.8.9 to v0.8.10,  it is ok.
