### ISSUE TITLE
Explicit throw raises invalid opcode

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#2260]
The explicit `throw` in the following code results in an invalid opcode exception in solidity >=0.4.10. 
```
pragma solidity ^0.4.10;
contract Test {
    function test() {
        throw;
    }
}
```

Is this the new expected behavior? It's not documented in the changelog. In fact, the last relevant entry (0.4.9) says: "Invalid jump is still kept for explicit throws".

**Comment by axic** [comment]
`throw` uses the `revert` opcode internally (which is an invalid opcode before Metropolis).

Seems like we have missed to mention this in the changelog for 0.4.10, but it is part of the documentation: http://solidity.readthedocs.io/en/develop/control-structures.html#exceptions

**Comment by frangio** [comment]
I see. Thanks.
