### ISSUE TITLE
Standard JSON compilation cannot find or read files.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#2266]
The compiler throws an error when trying to compile using the `--standard-json` flag when reading from a file.

```bash
echo '{"language": "Solidity", "sources": {"Greeter.sol": {"urls": ["file:///Users/piper/sites/py-solc/tmp/Greeter.sol"]}}}' | solc --standard-json
{"contracts":{},"errors":[{"component":"general","formattedMessage":"Cannot import url (\"file:///Users/piper/sites/py-solc/tmp/Greeter.sol\"): Unknown exception in read callback.","message":"Cannot import url (\"file:///Users/piper/sites/py-solc/tmp/Greeter.sol\"): Unknown exception in read callback.","severity":"error","type":"IOError"}],"sources":{}}
```

I've also tried the following formats for the file path just in case I was formatting something a little wrong:

- `file:///Users/piper/sites/py-solc/tmp/Greeter.sol`
- `file://Users/piper/sites/py-solc/tmp/Greeter.sol`
- `file://tmp/Greeter.sol`
- `file://./tmp/Greeter.sol`
- `tmp/Greeter.sol`
- `/Users/piper/sites/py-solc/tmp/Greeter.sol`

Help please

**Comment by axic** [comment]
`solc` at the moment doesn't support URL prefixes, such as `file://` (tracked in #2157), but using it in for example browser-solidity should be possible.

For regular paths, the paths must first be whitelisted via `--allow-paths <path1>,<path2>,..`. So for your use case, it should be `echo .. | solc --allow-paths tmp --standard-json`.

Also `--allow-paths` cannot handle trailing forward slashes yet (see #2147).

**Comment by pipermerriam** [comment]
That got things working, though I had to use absolute paths for everything as I wasn't able to get any form of relative path to work for either the `allow-paths` value or the paths passed in via standard json.

**Comment by MicahZoltu** [comment]
Workaround is to provide an absolute path to to some ancestor directory as an `--allow-paths` parameter and then include a full path to the file as one of the `urls` in `--standard-json`.

```
echo '{"language": "Solidity", "sources": { "file.sol": { "urls": [ "/full/path/to/file.sol" ] } } }' | solc --allow-paths /full/path --standard-json
```
