### ISSUE TITLE
Create Ubuntu Trusty build for 0.4.11

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#2267]
Is it possible to get a `solidity-ubuntu-trusty.zip` build added for `0.4.11`?

**Comment by chriseth** [comment]
Can you explain a bit more what you would be doing with it? Why does the static binary not serve your purposes?

**Comment by pipermerriam** [comment]
It's this build script: https://github.com/pipermerriam/py-solc/blob/master/bin/install_solc.sh

I assume you are referring to this build asset: https://github.com/ethereum/solidity/releases/download/v0.4.11/solc-static-linux

I honestly skipped over that somehow.  I'll give it a try and see if it does what I need.
