### ISSUE TITLE
Incorrect encoding of dynamic arrays in address.call

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#2269]
Solidity 0.4.11
Explained in detail here:
https://ethereum.stackexchange.com/a/16165/1328

In a nutshell, call encodes dynamic arrays as fixed arrays, omitting length prefixes.

**Comment by axic** [comment]
This came up in #2226 too. I think we could argue whether it should do:
a) the entire ABI encoding or
b) the encoding as of today and let the user control the structure.

Currently it encodes the shortest way possible, that kind of doesn't matches with a) anyway.

Also a longer discussion is at #1707. See `encode.calldata(sig, varargs)`.

**Comment by lastperson** [comment]
Perhaps we can just wait for the #1707 to be implemented, and update documentation on `address.call`.

**Comment by chriseth** [comment]
Functions like `call` and `sha3` do specifically not use the full ABI encoding. Yes, we should more clearly document that.

**Comment by chriseth** [comment]
The behaviour of those functions has changed in 0.5.0 and it is now properly documented.
