### ISSUE TITLE
Appveyor test fails when a deploy key is not available

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2272]
As observed in https://ci.appveyor.com/project/ethereum-free/solidity/build/1.0.3089 , when a PR is from an account without the write access to `ethereum/solidity` repository, the Appveyor test fails.

**Comment by axic** [comment]
I think the tests should just skip the bytecode comparison in that case. it is still better to have compilation succeeding than ignoring the entire Windows platform for third party PRs.
