### ISSUE TITLE
Create EIP for standard json output

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#2276]
It seems like the new standard JSON output format deserves an EIP.  Is this in the works?

**Comment by axic** [comment]
I've started drafting up something, but the spec is in the flux at the moment and wouldn't want to finalise it yet. At the bare minimum the following must be sorted:
- Output target selection
- Input/output support for: Assembly, Julia, LLL
- Julia, EVM1.5, eWASM outputs

I'd imagine it will take a couple of Solidity releases before it is really stable, though we don't really expect breaking changes.
