### ISSUE TITLE
support `switch`-`case` statements

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/solidity#2284]
Currently, the [typical javascript](https://www.w3schools.com/js/js_switch.asp) `switch`-`case` statement yields an `Error: Expected primary expression.`. This would be nice to have for many applications.

**Comment by chriseth** [comment]
This has not been added yet because some more research has to go into how to handle match expressions for sum types and destructuring.

**Comment by bbzorba** [comment]
It says the switch is added to 0.6.7. But remix compiler says Error: Expected primary expression when switch-case control structure is used. What should I do? #9647
