### ISSUE TITLE
different sourceIndices when using --combined-json and ast-json

### ISSUE THREAD

**Issue by djudjuu** [ethereum/solidity#2286]
`solc --combined-json ast input.sol` produces SourceLocations where the third number starts at 0 whereas `solc --ast-json input.sol` starts at -1

**Comment by axic** [comment]
@djudjuu @chriseth This needs to be fixed for `jsonCompiler` and `StandardCompiler` too.

**Comment by axic** [comment]
Never mind, it wasn't broken in those two :)

**Comment by axic** [comment]
Fixed by #2287.
