### ISSUE TITLE
Size and stack pos mismatch for multiple non-empty 'post condition' modifier

### ISSUE THREAD

**Issue by retotrinkler** [ethereum/solidity#2288]
- Which version of Solidity you are using
0.4.11+commit.68ef5810.Emscripten.clang
- What was the source code (if applicable)
https://gist.github.com/be21f66e6cf208ce78cbd2dece7e1db9
- Which platform are you running on
https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.11+commit.68ef5810.js&optimize=true
- How to reproduce the issue
See gist https://gist.github.com/be21f66e6cf208ce78cbd2dece7e1db9
- What was the result of the issue
`Internal compiler error (/src/libsolidity/codegen/LValue.cpp:50): Size and stack pos mismatch.
`
- What the expected behaviour is
No compilation error

**Comment by wuestholz** [comment]
In case this helps, we were able to reproduce this issue even when disabling optimization.
