### ISSUE TITLE
intX, X != 256 not converted from internal representation when returned?

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#23]
Tried with web compiler today, and latest dev ubuntu PPA version (as of 3 days ago). This may be an error. First: If I use `uint128`, for example, and i set it to 1, the output will be `000...001`.

```
contract Property {
  uint128 public intVal;
  function Property() {
    intVal = 1;
   }
}
```

Output:
```
{ value: '0000000000000000000000000000000000000000000000000000000000000001',
  offset: undefined }
```

In the case of `int128`.

```
contract Property {
  int128 public intVal;
  function Property() {
    intVal = 1;
   }
}
```

Output:
```
{ value: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000000000000000000000000',
  offset: undefined }

```

Not using the current VM but I see in the assembly output that the values are being converted in the `Property` function - both in the case of `int`'s and `uint`'s, but i only see the back conversion in the getter function when it's `uint`'s.

**Comment by chriseth** [comment]
I was not able to reproduce your issue, neither in a test environment nor in the browser runtime. Could you provide more information please?

**Comment by chriseth** [comment]
@androlo is this still an issue for you?

**Comment by androlo** [comment]
sorry. don't seem like it.
