### ISSUE TITLE
Interface functions are external, or no interfaces

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2330]
Suggestion by @pirapira :

Functions in interface contracts are external by default and functions cannot be anything else than external.

We have to make sure that it is still fine to override external interface functions with public functions in contracts.

**Comment by pirapira** [comment]
I would argue interfaces are not contracts, and their members have no visibilities.

When a contract inherits an interface, the contract's externally visible members are examined against the interface's members.

**Comment by pirapira** [comment]
Another good way (which I prefer) is to remove the `interface` keyword so that we do not need to choose a meaning of the word.

**Comment by axic** [comment]
I think it is a good idea to change the "visibility" to external and disallow visibility modifiers in interfaces. They are meant to describe what the ABI describes.

I am not in favour of removing the `interface` keyword.

**Comment by axic** [comment]
> I would argue interfaces are not contracts

Would it make sense introducing a new keyword `implements` / `supports` for interfaces to dinstinguish between inheritance?

```
contract Nekot supports Token {}
```

**Comment by chriseth** [comment]
If we do that, I would vote for `implements`, although I'm not sure if this justifies another keyword to learn.

**Comment by axic** [comment]
Question is, should we force the `external` keyword be present or force that no keyword is present?

**Comment by fulldecent** [comment]
@pirapira further arguments on getting rid of the current `interface` keyword are at #3420.

**Comment by axic** [comment]
> Question is, should we force the external keyword be present or force that no keyword is present?

Actually #3038 has implemented this for 0.5.0.

Just shows we need to create that 0.5.0 release sooner rather than later..

**Comment by fulldecent** [comment]
@chriseth I think we can mark this as closed because of https://github.com/ethereum/solidity/pull/3038

---

The second half of your original issue is duplicated here (and has a test case)

https://github.com/ethereum/solidity/issues/3458

**Comment by axic** [comment]
Started implementing this.

**Comment by axic** [comment]
Realised that actually this was implemented already via #3038.
