### ISSUE TITLE
Access constant state variables via class name

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#2333]
Currently if I want to access some constants in another class I have to use the `is` notation to "import" the contract containing the constants into the current contract. This pollutes the namespace of the current contract.

It would be great if I could just access constant state variables in another contract directly:

`className.constantThatIWant`

**Comment by chriseth** [comment]
I know you really badly want this, but creating the same issue again and again won't help implementing it: https://github.com/ethereum/solidity/issues/1290 ;-)

I have labeled the other one as up-for-grabs meaning that this should be a good issue for external contributors to implement.

**Comment by ethernomad** [comment]
Ah - I couldn't find the first one!
