### ISSUE TITLE
Introduce optimiser in julia/evm/Assembly

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2337]
- [x] function inliner
- [x] unused variable elimination
- [x] unused function elimination
- [ ] turn `switch <e> case 0 <b>` into `if not(tobool(<e>)) <b>` (needs the built in functions finalised)
- [ ] turn `switch <e> case 1 <b>` into `if tobool(<e>) <b>` (needs the built in functions finalised)

And the filters listed in #2405.

**Comment by chriseth** [comment]
We could already think about optimization strategies. One analysis step that certainly has to be perform is to check which functions can have side-effects.

One optimization pass that I was not able to do in the old system was [loop invairant code motion](https://en.wikipedia.org/wiki/Loop-invariant_code_motion) which should now be much easier.

I think we should take a look at code generated from the compiler and look for obivous improvements we would do manually. One thing I for example would like to avoid is the array-out-of-bounds-check for code like `for (uint i = 0; i < a.length; i++) a[i] = 2;`.

**Comment by chriseth** [comment]
- [ ] unification of semantically equivalent functions (or at least syntactically equivalent functions)

**Comment by axic** [comment]
I think these were implemented or are obsolete now.

@chriseth if you think something is missing from here, can you create a new issue for them?
