### ISSUE TITLE
Should warn for unreachable code

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2340]
```
contract C {
  function f() {
    uint a = 1;
    throw;
    a = 5; // unreachable code
  }
}
```

Perhaps this fits the static analyzer in browser-solidity better.

This should also be able to deal with `modifier mod(){ return; _; }`

**Comment by roadriverrail** [comment]
Another possibility-- I need to do control flow analysis for the compile-time overflow checks.  If we have control-flow analysis, then unreachable code detection shouldn't be hard.

**Comment by chriseth** [comment]
@ekpyron can't we do that now?

**Comment by chriseth** [comment]
Added to 0.5.1 queue.

**Comment by ekpyron** [comment]
@chriseth Yes, that's possible with the control flow graph in most cases - it would work in the example above. But it's a non-breaking change, so I agree to put it into 0.5.1.

**Comment by chriseth** [comment]
We could also detect some branch conditions like comparisons with constants.
