### ISSUE TITLE
Solidity Logo

### ISSUE THREAD

**Issue by kiknaio** [ethereum/solidity#2343]
It would be nice if Solidity had a logo 👍

**Comment by roadriverrail** [comment]
Are you volunteering, then? 😁

**Comment by kiknaio** [comment]
I will try to do my best 😃

**Comment by roadriverrail** [comment]
I'm not in charge or anything, mind you, but I don't think we have a
dedicated designer for logos.

**Comment by kiknaio** [comment]
I am not a designer but I will try :)

**Comment by axic** [comment]
Solidity already has a logo, it is this: https://github.com/ethereum/browser-solidity/blob/16e7446998a2d012a482070f856d96b37cab8c19/assets/img/sol.svg (though it was only used in browser-solidity)
