### ISSUE TITLE
"At Address" not working + create shows Error - callback contain no result Error: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by vanshaj2608** [ethereum/solidity#2352]
i am trying build a contract on rinkeby network through metamask but when i click create it shows error  - callback contain no result Error: SyntaxError: Unexpected token < in JSON at position 0
prior to create  there is no error in the contract and is build with no errors .
"At Address" button is also not working on clicking it shows pop up that enter the address but after entering and clicking it is not doing anything.
i am in middle of something very important please help ? Thanks.

**Comment by vanshaj2608** [comment]
![image](https://user-images.githubusercontent.com/27974958/26915530-05ef878c-4c44-11e7-9d25-794479a49069.png)

**Comment by chriseth** [comment]
Moved the correct repository: https://github.com/ethereum/browser-solidity/issues/586

**Comment by yann300** [comment]
@vanshaj2608 could you retry the `atAddress` now?

**Comment by vanshaj2608** [comment]
i moved on to use compiler from this url - https://ethereum.github.io/browser-solidity/
and it is working fine.
