### ISSUE TITLE
non UTF-8 literals are dropped from JSON-export without warning

### ISSUE THREAD

**Issue by djudjuu** [ethereum/solidity#2355]
A warning should be generated at 
ASTJsonConverter::visit(Literal) : 709

example code:

`contract C {
  bytes a = hex"1237651237125387136581271652831736512837126583171583712358126123765123712538713658127165283173651283712658317158371235812612376512371253871365812716528317365128371265831715837123581261237651237125387136581271652831736512837126583171583712358126
}"

**Comment by axic** [comment]
To me `solc --ast-compact-json` seem to output the right detail:

```
						"hexValue" : "1237651237125387136581271652831736512837126583171583712358126123765123712538713658127165283173651283712658317158371235812612376512371253871365812716528317365128371265831715837123581261237651237125387136581271652831736512837126583171583712358126",
						"typeDescriptions" : 
						{
							"typeIdentifier" : "t_stringliteral_e5a401fae0f0563a663ecf8c8b0e111e4c34979af21ae9f0bd57b92ded737bda",
							"typeString" : "literal_string (contains invalid UTF-8 sequence at position 7)"
						},
						"value" : null
```

Note that the `value` field is omitted if it is not UTF-8 compatible, because that will produce an invalid JSON file, which breaks emscripten. Also have a look at the description above :)

**Comment by djudjuu** [comment]
thx, I was not aware that I can always recreate the value from the hexValue-String
