### ISSUE TITLE
Function comparison creates disturbance in the stack 

### ISSUE THREAD

**Issue by illuzen** [ethereum/solidity#2356]
After binary search a la code deletion, I finally found what was causing my stack disturbance: casting an address as a contract and then incorrectly referencing variables in that contract (without parentheses). Putting the parens in fixes it, but it is hard to find in a larger contract, so maybe the compiler could give a more helpful response. Also, it's odd because function comparison doesn't seem to bother the compiler.  

contract B {

       uint public b;
       uint public c;
 }

contract A {

        function d() {

                B BB =  B(0);

                // the following works

                BB.b() < BB.c();

                // but this is disturbing

                BB.b < BB.c;

        }

}

I've spent a bit of time now poking around in the compiler, so if someone wants to give me a hint, I could tackle this one.

**Comment by chriseth** [comment]
Thanks a lot, @illuzen ! The proper fix would be to disallow the comparison operator for function types. This is determined by the `binaryOperatorResult` function on the type classes (in `Types.h`). Currently, the default implementation in the Type base class is to allow comparison operators for all types. Most of the derived classes then again disallow it by returning the empty `TypePointer()` for that function (this signals that it is not possible).

I think a better default implementation would be to only allow it if `commonType(shared_from_this(), _other)` is non-null and is a value type.

If you need any more realtime help, please try to reach us on https://gitter.im/ethereum/solidity-dev

**Comment by chriseth** [comment]
By the way, it seems that the same bug is also present if you want to compare mappings.

**Comment by illuzen** [comment]
Ah just pulled this up and saw that you've already grabbed. Will have to move faster next time.
