### ISSUE TITLE
Layout of a Solidity Source File Version Pragma

### ISSUE THREAD

**Issue by jamesray1** [ethereum/solidity#2357]
•Which version of Solidity you are using
N/A, just learning on readthedocs.
•What was the source code (if applicable)
N/A
•Which platform are you running on
N/A
•How to reproduce the issue
N/A
•What was the result of the issue
N/A
•What the expected behaviour is
N/A
I am not reporting on a bug with Solidity, but with an issue on readthedocs here:

https://github.com/ethereum/solidity/blob/develop/docs/layout-of-source-files.rst#version-pragma

"It is possible to specify much more complex rules for the compiler version, the expression follows those used by npm."

This is vague, providing more information would be better.

**Comment by benicillin** [comment]
does this comment refer to semver-compatible versions as defined by NPM here https://docs.npmjs.com/misc/semver ?

**Comment by chriseth** [comment]
@benicillin yes

**Comment by jamesray1** [comment]
I will create a fork and pull request.

**Comment by jamesray1** [comment]
Here it is: https://github.com/ethereum/solidity/pull/2407
