### ISSUE TITLE
Warn if `for (var i = 0; ...)` is used

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2358]
This is a common pitfalls because type deduction will assign the type `unt8` to `i`, which will probably lead to problems with overflow and the for condition.

**Comment by illuzen** [comment]
Is there a case where type deduction is good and doesn't lead to errors like this?

**Comment by VoR0220** [comment]
@illuzen Contract referencing comes to mind. But even that has some pitfalls (which I believe are being addressed as we speak).

**Comment by axic** [comment]
It was useful before function types were added. Less useful now.

**Comment by chriseth** [comment]
I think this is quite important, as the question comes up again and again. Will implement.
