### ISSUE TITLE
Variable locations are wrongly calculated in Julia assembler

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2365]
```
{
  let x := 1

  jump(label)

  let y := 2
  
label:
  let z := x
}
```

The location of `x` is calculated wrongly, because the other declarations between the jump and label are also taken into account.

`z` should be `dup1`, but is generated as `dup2`. If `let y` is removed it results in `dup1`.

**Comment by axic** [comment]
This can also be reproduced in inline assembly:
```
contract C {
  function f() returns (uint a) {
    assembly {
      let x := 1

      jump(label)

      let y := 2
  
    label:
      let z := x
      
      a := z
    }
  }
}
```

**Comment by chriseth** [comment]
This is a documented downside of using a raw `jump`. To fix it, we should ban raw jumps and labels.

**Comment by axic** [comment]
At the bare minimum we need a warning displayed. The warning in the documentation is quite hidden.

**Comment by chriseth** [comment]
You are proposing to show a warning whenever labels are used instead of banning them (at least for the next release)?

**Comment by chriseth** [comment]
Note that such a warning can only be silenced by changing to switch and for.

**Comment by axic** [comment]
Well labels are not doing anything, but jump instructions are. Ideally it should warn if a variable declaration is within a block jumped over, but it is way easier to simply warn on a jump instruction.

I think it is a good way to prepare for deprecation of inline assembly in favour of Julia.
