### ISSUE TITLE
Explain unexplained terms in the documentation

### ISSUE THREAD

**Issue by jamesray1** [ethereum/solidity#2371]
Learning Solidity on http://solidity.readthedocs.io, there are too many terms that are introduced without a proper definition for those who may not be familiar with such terms. This makes it difficult to learn Solidity without doing a lot of background reading, or learning another language. I know VBA from university and some C++ from learncpp.com, but there is a lot that I have to read up on elsewhere as it is not explained properly.

**Comment by tclass** [comment]
could you give some examples what terms would need a proper definition? I think we don't want to explain common computer science terms, but we could make a glossary, for some terms

**Comment by jamesray1** [comment]
Basically, my intention is to make it easier for someone to learn Solidity as their first programming language. If you go to learncpp.com, that is a good example of how to teach clearly, without always assuming that the reader knows what you are talking about. So any terms that may not be familiar to such an audience would be good to be defined.

For example, one of the docs mentioned ABI, without the full meaning. So I then had to look up ABI, which there were many results for, and finally found Application Binary Interface. Even having a link to this article would be good, so I edited this. Other examples that weren't clear I have already edited.

If I had not learnt VBA and had been learning C++ then a lot of the terms would be confusing for me.

**Comment by jamesray1** [comment]
"It is possible to mark arrays public and have Solidity create a getter."

http://solidity.readthedocs.io/en/develop/types.html

What is a getter?

I found this:

http://solidity.readthedocs.io/en/develop/contracts.html#getter-functions

It should say:

"It is possible to mark arrays public and have Solidity create a getter. Getters will be explained later [here](http://solidity.readthedocs.io/en/develop/contracts.html#getter-functions)."

**Comment by jamesray1** [comment]
A newbie doesn't have to understand all the terms when they are introduced. However, it is important that it is explained that those terms will be explained later (ideally with a reference to where it is explained).

**Comment by pirapira** [comment]
@jamesray1 please change the title "Documentation" to a more descriptive one.  That would draw more attention, which this issue deserves.

What's missing is a list of technical terms, and an ordering between them showing which can be explained after which.

**Comment by chriseth** [comment]
@jamesray1 these are very good suggestions! I don't think the documentation as it is now is suitable for people who learn Solidity as their first programming language, and perhaps it should also not have such people as audience because programming should be learnt properly.

Having said that: If terms can be explained without breaking the flow for people who know these terms, then they should be explained! In the example above: `"It is possible to mark arrays public and have Solidity create a getter.` - the term "getter" should just be converted to a link.

**Comment by axic** [comment]
I am not entirely convinced Solidity should be a first language to learn. While it has a relatively simple syntax there are many caveats even seasoned developers tend to omit at first.

I do like the idea of a glossary and links to the glossary though.

**Comment by chriseth** [comment]
As this is a meta-issue which can never considered "finished", I will close it.

**Comment by jamesray1** [comment]
OK, thanks for the comments, sounds reasonable.

**Comment by jamesray1** [comment]
So can we start building a glossary doc?

Here's a start:

[Keccak](http://keccak.noekeon.org/specs_summary.html)

**Comment by pirapira** [comment]
For Keccak, we have to mention that we do not use the newest specification available but the one submitted to the SHA3 competition.

**Comment by pirapira** [comment]
@jamesray1 what you can do:

1. create `jamesray1/ethereum-glossary` repository
2. create a very small glossary in it
3. add an open source license
4. post the repo in reddi
5. let people fork and add entries

**Comment by jamesray1** [comment]
> add an open source license

Any suggestions?

![2017-06-30 15_39_41-create a new repository](https://user-images.githubusercontent.com/16969914/27722346-6c105b00-5daa-11e7-81ac-520b639eeec4.png)

**Comment by jamesray1** [comment]
https://github.com/jamesray1/solidity-glossary
https://www.reddit.com/r/ethereum/comments/6kedst/glossary_to_assist_with_learning_solidity/
