### ISSUE TITLE
Documentation stating fallback function required

### ISSUE THREAD

**Issue by eyezick** [ethereum/solidity#2377]
```
Contracts that receive Ether but do not define a fallback function throw an exception, sending back the Ether (this was different before Solidity v0.4.0). So if you want your contract to receive Ether, you have to implement a fallback function.
```

I have a small contract here, that does not have a fallback, but receives ether through the depositFunds function. So it seems the above text should be edited/removed.
```
pragma solidity ^0.4.4;

contract Bank {

    address owner;

    function Bank(){
        owner = msg.sender;
    }

    function depositFunds() payable returns (uint _fundsDeposited){
        return msg.value;
}

    function withdrawFunds() {
        require(msg.sender == owner);
         if (!owner.send(this.balance)) throw;
}

}
```

**Comment by naterush** [comment]
While I agree this is slightly confusing wording when alone, it seems fine as it is in the section about sending Ether when calling the callback function. In this case, it is true that in a contract w/o a fallback function will throw if sent ether.
