### ISSUE TITLE
delete array[index] doesn't change length and leave "0"

### ISSUE THREAD

**Issue by rstormsf** [ethereum/solidity#2379]
How am I supposed to remove an element from an array without having "0" in there and having resized `length`. The only way I could find is the following:

need some method 
```
      function remove(address[] array, uint index) internal returns(address[] value) {
        if (index >= array.length) return;
        
        address[] memory arrayNew = new address[](array.length-1);
        for (uint i = 0; i<arrayNew.length; i++){
            if(i != index && i<index){
                arrayNew[i] = array[i];
            } else {
                arrayNew[i] = array[i+1];
            }
        }
        delete array;
        return arrayNew;
    }
```
but this method still gives me wrong `length` and has `0` in removed array, althougt I use completely new Array and don't even touch the index.

**Comment by chriseth** [comment]
This looks like correct code to me. I would suspect the error to be in the code where `remove` is called. I think this question might be better suited for the ethereum stackoverflow. Furthermore, are you sure you need such an expensive function? If you store the array in storage, then a mapping might be a better choice.

**Comment by rstormsf** [comment]
So u mean, instead of using array structure, I better off using `mapping(uint number => string value) ` if so, how do I make sure to keep the index in order when I remove an item? Would u mind to give an example. Sorry for posting it here.

**Comment by rstormsf** [comment]
Yes, the code above works fine, and I'm trying to find a better way, less expensive way of doing it

**Comment by chriseth** [comment]
Ah I see! Without knowing more context, it is hard to say, but do you actually need contiguous indices for your data?

**Comment by rstormsf** [comment]
True. I might not need it at all and keep a variable to count the size. Thank you
