### ISSUE TITLE
Invalid option to --combined-json: hashes

### ISSUE THREAD

**Issue by ruchevits** [ethereum/solidity#2380]
`g_strSignatureHashes` option is not picked up in [CommandLineInterface::handleCombinedJSON](https://github.com/ethereum/solidity/blob/002df12d13fb423be641878a20b73bd10f90a6df/solc/CommandLineInterface.cpp#L825)

**Comment by ruchevits** [comment]
https://github.com/ethereum/solidity/pull/2382

**Comment by chriseth** [comment]
Thanks for reporting and fixing!
