### ISSUE TITLE
Forbid trailing commas in { }

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2385]
It [seems like](https://github.com/ethereum/solidity/pull/2378#issuecomment-308167778) the parser allows `{ x : 1, y : 2, }`, but @chriseth  is [against it](https://github.com/ethereum/solidity/pull/2378#issuecomment-308177075).

**Comment by chriseth** [comment]
Not only me, also the  grammar! ;-)

**Comment by pirapira** [comment]
But, I don't know how `;` ended up being a terminator.
