### ISSUE TITLE
Failed to run script "install_deps.sh" on CentOS

### ISSUE THREAD

**Issue by zyfdegh** [ethereum/solidity#2391]
## Which version of Solidity
latest commit  on branch develop c99c1c76f

## What was the source code
File `scripts/install_deps.sh`, [Line 325~Line 366][line325]

## Which platform are you running on
* OS: CentOS 7.3
* Kernel: Linux x86_64 3.10.0-514.21.1.el7

## How to reproduce the issue
Clone the repo, fetch submodules
```sh
$ git clone https://github.com/ethereum/solidity.git
$ git submodule update --init --recursive
```
And
```sh
$ ./scripts/install_deps.sh
```

## What was the result of the issue
Retrieve GPG keys from remote failed 
```sh
This script will heavily modify your system in order to allow for compilation of Solidity. Are you sure? [Y/N]YLoaded plugins: axelget, fastestmirror
No metadata available for base
No metadata available for extras
No metadata available for updates
Loading mirror speeds from cached hostfile

Package epel-release-7-9.noarch already installed and latest version
Nothing to do
curl: (22) The requested URL returned error: 404 Not Found
error: http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/RPM-GPG-KEY-cern: import read failed(2).
```
## What the expected behaviour is
Successfully imported GPG keys and installed dependent packages.

[line325]: https://github.com/ethereum/solidity/blob/develop/scripts/install_deps.sh#L325

**So, will this issue be fixed? Any other advice on building solidity for CentOS?**

**Comment by chriseth** [comment]
I'm sorry, but we cannot provide detailed support for all distributions. This script mostly relies on the community to provide feedback.

**Comment by axic** [comment]
Can you check what `g++` and `boost-devel` versions do you have installed? Perhaps newer CentOS versions don't need a new one installed.

**Comment by zyfdegh** [comment]
@chriseth I'm on it and trying to install the many dependencies. I will put a PR if I succeed.

**Comment by zyfdegh** [comment]
@axic  Yeah,  I've installed boost 1.53.0 but the precheck script told me it's too old. I'll upgrade it and see if it works.

**Comment by chriseth** [comment]
Wonderful, thanks a lot!

**Comment by axic** [comment]
@zyfdegh did you had any success with this?

**Comment by zyfdegh** [comment]
@axic Nope, gave up

**Comment by born2net** [comment]
same here... can't get Solidity installed on RedHat :(

**Comment by axic** [comment]
@born2net did you manage to solve it?

**Comment by born2net** [comment]
actually moved to diff project
