### ISSUE TITLE
LLL: "set", "get" and "ref" expressions not compiling.

### ISSUE THREAD

**Issue by benjaminion** [ethereum/solidity#2400]
While writing some end-to-end tests for the built-in macros in LLL (yay!), it became apparent that the "set" expression (used in the first msg macro) no longer compiles. E.g.

    > echo '(set x 1)' | lllc
    ...blah...
    Symbol not found: set

The same goes for "get" and "ref".

SET, GET and REF are handled in the parser, *liblll/CodeFragment.cpp*. Parsing fails when the parser executes `m_asm.append((u256)varAddress(firstAsString()));`

`varAddress()` [line 174] tries to look up a string in the `_s.vars map`, defined in line 47 of *liblll/CompilerState.h*. But `vars` is always empty - nothing ever writes to it so this look up always fails.

I guess that at some stage variables were a thing in LLL and this functionality has since been removed, leaving "set", "get", "ref" and varAddress() as remnants. I was unable to find the commit that might have done this, however.

Anyway, I'm happy to make a PR to remove all of this and independently fix up the msg macro, but wanted to check with those more familiar with the code whether this is desirable, or if they should instead be fixed.  Any thoughts?

**Comment by axic** [comment]
It seems this was broken by https://github.com/ethereum/solidity/commit/b1add657b76621952be100b4203dd2c8a466b9a1.

Can you create a PR with your tests? Just write them as you think they should work.

**Comment by benjaminion** [comment]
A test for this is included in PR #2418 (msg_six_args). I can split it out into a separate PR if you prefer. Let me know.
