### ISSUE TITLE
Yul to Webassembly code generator

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2405]
- [x] fix add_carry and other functions
- [x] implement basic codegen using text output
- [ ] move to binaryen
- [x] implement switch
- [x] implement for
- [x] split >64 bit types into memory
- [x] move multi return values to globals
- [x] filter: move root statements to the "main" function (a step already exists which encloses statements and moves them into a block at the top of the AST; this block needs to be made into a function)
- [x] filter: move embedded functions
- [x] filter: allocate local variables at the beginning of the function (need to be pulled out of sub scopes, including for loops)
- [x] filter: flatten nested blocks (variables)
- [x] filter: replace 256-bit builtins with arithmetic code using 64-bit builtins (inject it as Yul snippets)

**Comment by sifmelcara** [comment]
Hello!

We have a team working on ewasm-related products thus we would love to see a working implementation of yul to ewasm code generator. Also we have some engineer's time available but not sure what is the best way to contribute to help it to progress.

#2233 looks like a solid starting point. Maybe we can merge that PR into develop so people can start to contribute missing features/tests listed in this issue? What do you think? Thanks :)

**Comment by chriseth** [comment]
Such a prototype is also very high on our priorities list. The pull request you cite is very outdated by now and we actually do not intend to use binaryen anymore but instead just output wasm string representation. I think one of the most challenging parts here is to decide how to do proper versioning and feature support, mainly related to types larger than 64 bits.

**Comment by chriseth** [comment]
Interface spec: https://github.com/ewasm/design/blob/master/eth_interface.md
How to use: https://github.com/ewasm/design/blob/master/interface_questions.md#synchronous

**Comment by chriseth** [comment]
I think this can be closed. The task still needs testing, but it is not clear yet which runtime we are supposed to use and how.
