### ISSUE TITLE
UTF8 validation is too sloppy

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2412]
Some invalid utf8 sequences are allowed by the utf8 validator code.

https://stackoverflow.com/questions/6555015/check-for-invalid-utf8

https://github.com/ethereum/solidity/pull/2386

**Comment by axic** [comment]
I'd rather just go by the spec: *pp124 of http://www.unicode.org/versions/Unicode9.0.0/ch03.pdf*

The current validator implements Table 3-6. Table 3-7 specifies irregular exceptions, which we need to add. Damn you, Unicode.
