### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2414]
Since the license is now included in the binary it should actually represent the entirety of the code. There are three parts, which are not GPL3 licensed:

1. [ ] `libdevcore/SHA3`
```
 /** libkeccak-tiny
 *
 * A single-file implementation of SHA-3 and SHAKE.
 *
 * Implementor: David Leon Gil
 * License: CC0, attribution kindly requested. Blame taken too,
 * but not liability.
 */
```

Where CC0 corresponds to public domain (as much as allowed by local law), but the *attribution kindly requested* moves it to a bit of a grey area.

2. [x] `libdevcore/debugbreak.h`

2-clause BSD. This requires reproduction in the binary.

3. [ ] `jsoncpp`

See https://github.com/open-source-parsers/jsoncpp/blob/master/LICENSE. It is licensed under public domain + MIT.

MIT requires distribution with all copies. Since our distribution is a sole binary file, that should include it.

**Comment by chriseth** [comment]
Let's remove debugbreak.

As far as I know, MIT only requires reproduction in the source code, not in the binary.

**Comment by axic** [comment]
MIT doesn't, but a LICENSE file containing it should be supplied with the binary. Since we don't supply a separate file, but a built in version, one could argue that should contain it.
