### ISSUE TITLE
[solc feature]  library-like linking for normal addresses

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#242]
We're in the process of designing a build/deploy cycle for working with ever-growing contract systems. The concept of a `library` plus contract constructor arguments in solidity together are _almost_ enough to enable future-proof "packages" or "modules", but not quite.

We've been able to reduce source-level hacks to make our package system work like we want to a single macro that looks like this:

`var namereg = NameReg( LINK("my-environments-namereg"))`

If you use a statement that uses this macro anywhere in a contract definition, then the contract is annotated what are essentially "deploy-time-only" constructor arguments which come from your environment definition.

Seems there is something in between a `contract` and a `library` which would let us achieve the same goal natively.

**Comment by nmushegian** [comment]
Here's a rough idea of how to make it more elegant using a new native concept instead of a link macro:

```

template MyDapp(NameReg namereg, Maker M, Alarm A) {
    function MyDapp( uint bytes32 ny_name ) }
        namereg.register(ny_name, address(this));
    }
    function doStuff() {
        A.schedule(address(M), 0x0);
    }
}
```

This would "precompile" into:

```

contract MyDapp {
    function MyDapp( uint bytes32 ny_name ) }
        NameReg(<LINKED ADDRESS>).register(ny_name, address(this));
    }
    function doStuff() {
        Alarm(<LINKED ADDRESS>).schedule(address(Maker(<LINKED ADDRESS>)), 0x0);
    }
}
```

**Comment by axic** [comment]
You have the template file and the output. Where do you use your template and set the values? Is it something like:

```
NameReg namereg = NameReg(0x...);
MyDapp(namereg, .., ..)
```

On its own in a .sol file?

**Comment by nmushegian** [comment]
We have a notion of "deploy sequence" or "deploy script", it will be DSL in which something like your code snippet would make sense (could maybe even be a subset of Solidity). At this stage you need to define an "environment" or "context" which distinguishes "the same" system on different chains or different system instances on a single chains. Part of package management is distributing partial environments and/or setup scripts.

**Comment by nmushegian** [comment]
A deploy script could also be called an "account script". It should be like writing Solidity "as" a `tx.origin`, a key and not an address. It has a few key differences, like it requires an environment / chain context, and sequences of statements are not atomic.

**Comment by chriseth** [comment]
I would say this is basically identical to constants that are only filled at link-time.

**Comment by nmushegian** [comment]
That's correct but I think extreme care has to be taken to make sure your constants are the same size as in the original bytecode, or do this earlier at the AST - not sure how linking works or if there is anything like an unlinked object file

Right now we have an ad-hoc implementation of this with a CONSTANT macro and bytecode postprocessing but it requires using address-sized constants

@mhhf might be interested in this issue for historical context

**Comment by chriseth** [comment]
This has been stale for a very long time, and I think #3835 will get very near to this. closing.
