### ISSUE TITLE
RFE: Introduce private selectors for struct and other types

### ISSUE THREAD

**Issue by ethernian** [ethereum/solidity#2421]
# Problem
Consider an already deployed contract `Base` exposing a complex struct into public space.
```
contract Base {
    struct S { uint n; string name; bytes code; /* and so on */ }
    S public s;
}
```
Consider some other contract `BaseUser` developed later and accessing some fields of the struct `S` from the contract `Base.`

```
contract BaseUser{
    Base base = Base(BASE_ADDR);
    function storeIfOnly(string _name) {
        var (n,name,code) = base.s();  //(A)
        if (sha3(name) == sha3(_name) && n==1) {
             //store something.
        }    
    }
}
```
As you see, if the contract `Base` does not define individual accessors for fields of struct `S`, the `BaseUser` should retrieve whole struct, what is inefficient. If the contract `Base` defines accessors for individual fields of `S`, it is also inefficient to make one message call per field access. It could be impossible to define a group field accessors in `Base` in advance, because `BaseUser` is not designed yet.

There is another problem retrieving whole struct in `BaseUser`: solidity compiler supports currently up to 16 local variables. Line **(A)** pollutes local space with unused variables. It can lead to  _"Stack too deep, try removing local variables"_ error.

# Solution
I would propose a new language feature "private selectors". It selects only necessary fields from the struct. The syntax could be like:

```
contract BaseUser{
    Base base = Base(BASE_ADDR);
    function storeIfOnly(string _name) {
        var (n,name) = base.s[name,n]();  //(A)
        if (sha3(name) == sha3(_name) && n==1) {
             //store something.
        }    
    }
}
```
where **[name,n]** is the private _field_ selector for the type `struct`.

# Implementation
Implementation of this private selector is quite simple: Solidity compiler should inject a bitmask as a field selector into the current accessor call:

contract BaseUser:
```
var (n,name) = base.s(/*injected*/ 0x3);  // binary 011 selects fields 'n', 'name' but not 'code'
```
The public accessor `s()` in the contract Base should evaluate the given bitmask and make internally an private call to embedded selector function returning only requested fields. This is essentially the  'private selector' or 'embedded selector'.

Note, that length of the return value is known at compile time of the contract `BaseUser`. 

# Generalization
We could define private selectors not only for `struct`, but for another types as well. Here is an example of private selector for arrays.

```
contract Base {
    uint[] publlic arr;
}
```
and access the first element of `arr` as
```
  var e =  base.arr[0]();
```
The  **()** are still necessary in order to express, that we have a read-only accessor call here, and not an array access. Thus the expression can't be used as the left part of an assignment.
```
  base.arr[0]() = 0x42;  // causes compile error
```

Personally I find an expression `base.arr[0]()` for an array element access much more consequent and clear as the current solidity syntax `base.arr(0)`.

# Other complex structures
It could be useful to define selectors for more complex data types like trees.

```
contract Base {
    //we should better define a new type 'tree' for that
    struct Node { uint id; uint[] children; string name; }
    mapping(uint=>Node) public tree;
}
```
and select it like...
```
var node = base.tree[/foo/bar]();
```
# Custom selectors
There are also ideas to define a custom selector functions in the `Base` contract. 
Possible syntax and semantic is still unclear and to be discussed.

### Acknowledgement
A lot of thanks to @chriseth  and @pirapira for important feedback and ideas.

**Comment by ethernian** [comment]
### [Change 1] Implementation: 
it would be better to use reverse bitmask; 0-include the field, 1- exclude it. 
0x0 value would select all fields per default. 
It would be compatible with current struct accessor (without bitmask support). 
``` 
var (n,name) = base.s(/*injected*/ 0x8);  // binary 100 deselects 'code' keeping 'n' and 'name' 
```

**Comment by pirapira** [comment]
An alternative is to introduce `ignore` in the tuple assignment:

```
var (_, name, _) = base.s()
```

**Comment by ethernian** [comment]
@pirapira , the `ignore` statement will workaround the local vars limitation, but doesn't solve the efficiency problem.  Is it correct?

**Comment by federicobond** [comment]
Looks reasonable. I would suggest a more standard destructuring syntax:
```javascript
var { n, name } = base.s()
```
You could also allow renaming:
```javascript
var { n: sN, name: sName } = base.s()
// or:
var { n as sN, name as sName } = base.s()
```
For arrays, I am more inclined to provide a fake method:
```javascript
base.arr.get(i)
// or:
base.arr.getElementAt(i)
```

**Comment by ethernian** [comment]
@federicobond 
I think it is not like destructuring because we don't want to transfer the whole object through msg.data. There is no object to destruct at all; we want to request parts of it. 
It should be quite tricky, to pass the field list from the left part of the assignment into the right part to build an accessor call. And what about if we have no assignment at all, but a method call or return?

**Comment by federicobond** [comment]
You are right, what I had in mind would be tricky to implement and only work with assignment statements. I am still not sold on the syntax though, I'll give it some thought.

**Comment by ethernian** [comment]
@federicobond 

> I am still not sold on the syntax though,

Yes, it is not perfect yet. 

My problem with the syntax is that the expression in the brackets sometimes looks like compile time declaration of struct fields like `base.s[name,n]()` and sometimes it looks like runtime expression like `base.arr[i+1]()`. Although it should not be a problem because the type of the context is always defined, I am not quite happy with compile-time/runtime semantic mix inside of square brackets. 

But nevertheless I am not happy with the syntax of fake methods like `base.arr.get(i)` too.
I see here two problems:
1. we use the same dot operator twice in different cases. Once to express reference from `base` to `arr` which is cheap, and then to express a message call to another contract with object serialization inside which more expensive and is subject to further restrictions. For example your fake method syntax implies you could use `base.arr` in expressions as an accessible object, but you can't.
2. with fake methods we have completely different syntax to access array elements inside declaring contract and from outside. It is not consequent.

The syntax `base.s[name,n]()` defines a method call, configurable by selector. The selector gets executes **before** the `msg.data` serialization takes place. This is the main objective of this RFE.
