### ISSUE TITLE
Should function types be allowed to name their arguments?

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2428]
The example for function types in the documentation looks like this, where function parameters can have names. 

```javascript
  // ...
  function reduce(
    uint[] memory self,
    function (uint x, uint y) returns (uint) f
  )
    internal
    returns (uint r)
  {
    r = self[0];
    for (uint i = 1; i < self.length; i++) {
      r = f(r, self[i]);
    }
  }
  // ...
```

This behavior was explicitly forbidden in the grammar specification (see [here](https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt#L50-L51)). Is this a bug in the current implementation?

**Comment by chriseth** [comment]
I agree that this would increase readability, but in general, the name of a variable is not part of the type....

**Comment by federicobond** [comment]
FWIW, I think the implementation should change to enforce no names in types for consistency.

**Comment by axic** [comment]
I'd agree with @federicobond, having names could be confusing considering shadowing rules.

**Comment by chriseth** [comment]
Oh I'm sorry, misunderstood you there. Yes, let's disallow the names.

**Comment by federicobond** [comment]
Should we merge a deprecation warning first or are we already inside the merge window for 0.5.0?

**Comment by axic** [comment]
Yes, we aim to have warnings for obsolete features as soon as possible once we decided it is deprecated. And then probably have a major 0.5.0 release removing all the cruft.

**Comment by axic** [comment]
Hm, maybe it does make sense allowing named arguments (but not return parameters):
```
  function f() {
    function (uint a, uint b) fn;
    fn({ a: 1, b: 2});
  }
```

Though for some reason it doesn't work. It works properly with functions:
```
  function g(uint a, uint b) {
    g({ a: 1, b: 2});
  }
```

**Comment by chriseth** [comment]
We should check how this behaves with regards to parameter name changes during assignment.

**Comment by axic** [comment]
Decision: return parameter naming is removed.

**Comment by axic** [comment]
Consensus seems to be that naming of return parameters should be removed, which will be merged soon, however there's no consensus yet on removing named arguments. That is now tracked in #4299.
