### ISSUE TITLE
Solidity By Example Voting contract bug fix

### ISSUE THREAD

**Issue by DillonBArevalo** [ethereum/solidity#2430]
issue: function `giveRightToVote` can destroy weight given by function `delegate`.

For example:

1. chairperson makes ballot
2. chairperson gives right to vote to voter1
3. chairperson delegates to voter1
4. voter1 votes for prop
5. total votes = 2

vs

1. chairperson makes ballot
2. chairperson gives right to voter1
3. chairperson delegates to voter1
4. chairperson gives right to voter1 again #this is a problem. as it removes the votes from everyone who delegated to voter1
5. voter1 votes for prop
6. total votes = 1

This can be easily shown by taking five voters, giving them all the right to vote and creating two proxies: voter1 which has been delegated to twice (now with a weight of 3) and voter2 who has been delegated to once (now with a weight of 2). Then give voter1 the right to vote again, have them vote on different propositions and see that voter2's choice wins despite the greater support for voter1's choice.

proposed solution is to add the condition
`&& (voters[voter].weight == 0)`
when trying to give right to vote.

```
function giveRightToVote(address voter) {
            // If the argument of `require` evaluates to `false`,
            // it terminates and reverts all changes to
            // the state and to Ether balances. It is often
            // a good idea to use this if functions are
            // called incorrectly. But watch out, this
            // will currently also consume all provided gas
            // (this is planned to change in the future).
            require((msg.sender == chairperson) && !voters[voter].voted && (voters[voter].weight == 0));
            voters[voter].weight = 1;
        }
}
```

I understand that the intended use of the `giveRightToVote` function is to allot votes at the beginning of a voting cycle, but there is nothing explicit in the program that prevents either an accident deleting votes or someone with access to the chairperson's keys from seriously tampering with results. There is currently no way to see what has happened or correct for it after votes are deleted. The votes cannot be given back to the voters who delegated because they already have a status of having voted.

I have made a PR with this very small change.

**Comment by chriseth** [comment]
Thanks!
