### ISSUE TITLE
Address literals not being treated as "compile-time constant"

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/solidity#2441]
This has been brought to my attention in a recent code review, that the compiler triggers a 'compile-time constant' warning when assigning an address literal to a constant:

    contract addrConstantWarning {
        address constant test = 0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c;
    }

> Untitled:2:29: Warning: Initial value for constant variable has to be compile-time constant. This will fail to compile with the next breaking version change.
>     address constant test = 0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c;

The workaround is to assign to a variable but this unnecessarily consumes state. 

Compiled in 0.4.11

**Comment by chriseth** [comment]
Thanks for reporting!

In addition to that, the code above should not compile at all, since the right hand side is a 42 byte string and not an address.

**Comment by o0ragman0o** [comment]
Ah, actually I forgot to remove the quotes.  That was just to test for alternative behaviour...

**Comment by GriffGreen** [comment]
Wow! Such an incredibly fast turn around on these bugs! Thank you @chriseth and @federicobond :-D
