### ISSUE TITLE
LLL: include real life contracts in the test suite

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2447]
A good candidate is `ens.lll`. Are there any other substantial pieces of code worth including?

cc @zigguratt @benjaminion

**Comment by zigguratt** [comment]
There aren't any other deployed LLL contracts, afaik. I have a few full contracts that compile properly and would work for the purposes of testing, but I'd have to check them over and make them test-ready. I'm extremely busy for the next two days, but I can get to it after that.

@benjaminion, to his great credit, has implemented an ERC20 token in LLL. He could tell you more about it and whether it's suitable for this purpose.

**Comment by axic** [comment]
@benjaminion I'll have a look at finishing the alloc tests tomorrow, but if you want to progress, feel free to take up this issue

**Comment by benjaminion** [comment]
@axic 

> feel free to take up this issue

I'll gladly take ownership of this, but it'll be queued up for a while behind a couple of other things I'm working on. Namely, I've made a start on [some documentation for LLL](http://lll-docs.readthedocs.io/en/latest/index.html) which I want to get done asap, and I'd like to get my [ERC20 LLL code](https://github.com/benjaminion/LLL_erc20) benchmarked and then deployed in the wild. It needs a bit more work; I might refactor it to use `set` and `get` now that they are working again!

So it might be a few weeks until I get to this (never mind the day job...), but happy to take it on in due course.

**Comment by axic** [comment]
I think we can consider this done now.
