### ISSUE TITLE
A dynamic array declared in a function cannot be substituted away.

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2458]
The violated property
----------------------------

In general,
```
<type> v = a;
<code contaning v>
```
should be equivalent to
```
<code containing a>
```
if `a` does not have side-effects.

The violation
----------------

However, this property does not hold in Solidity because
```
contract C {
    uint[] a;
    uint[] b;
    function f() {
        uint[] ref = a;
        ref = b;
    }
}
```
behaves quite differently from
```
contract C {
    uint[] a;
    uint[] b;
    function f() {
        a = b;
    }
}
```

The latter performs elementwise copy while the former does not.

**Comment by chriseth** [comment]
Solidity is not the only language that does not have this property. Python for example, a language that is usually considered to be very intuitive or at least easy to learn behaves like that:

```
>>> a = [1,2,3]
>>> b = [4,5]
>>> ref = a
>>> ref = b
>>> a
[1, 2, 3]
>>> b
[4, 5]
```

```
>>> a = [1,2,3]
>>> b = [4,5]
>>> a = b
>>> a
[4, 5]
>>> b
[4, 5]

```

**Comment by chriseth** [comment]
In general, I think that https://github.com/ethereum/solidity/issues/2435 should make this distinction clear to the programmer.

**Comment by pirapira** [comment]
Yes, I have the same complaint against Python.

**Comment by pirapira** [comment]
After #2435, it should be straightforward to fix this issue, whether element-wise copying into a reference is allowed or not.
