### ISSUE TITLE
LLL: (alloc 0) corrupts memory

### ISSUE THREAD

**Issue by benjaminion** [ethereum/solidity#2465]
The built-in `alloc ` expression in LLL reserves some memory by writing a zero byte to memory at (msize + n -1) where n is the number of bytes requested, ie `(alloc n)`.

If n is 0, then this can corrupt the previous word in memory with data at (misze - 1). Sample code:

```
(seq
  (mstore 0x00 1)
  (alloc 0)
  (return 0x00 0x20))
```

This returns 0 rather than 1 as it should.

For me, `(alloc 0)` could be flagged as a run-time error as there could be security implications of this either way.  If we just alloc 0 bytes (don't change msize), then that could lead to other problems if the later code is expecting some allocated memory to have been reserved for it. But thoughts welcome.

**Comment by chriseth** [comment]
memory can be grown by reading, not by writing, and I think LLL should always allocate at least 32 bytes (although I would not make `alloc 0` fail).

**Comment by benjaminion** [comment]
> memory can be grown by reading, not by writing

Interesting. That would definitely be safer!

> I think LLL should always allocate at least 32 bytes

I guess this could be achieved cheaply and without jumps by inserting the following after putting the alloc argument on the stack.

```
DUP1
ISZERO
ADD
```

This should then make alloc safe whether we read or write to extend the memory.

**Comment by axic** [comment]
As mentioned memory is extended by reading or writing an offset not previously touched. Changing alloc to `mload` would at least solve the overwriting issue.

Not entirely sure an overhaul is not needed, because static memory ranges are assumed right now by the compiler, such as the range by `set`/`get`, etc.

Do I understand correctly that `(alloc n)` allocated n bytes and returns the starting offset? I think `n = 0` is fine in that case (it won't change current semantics), but not very useful.

I'd rather go into thinking about a proper design of these LLL features and do an overhaul at some point.

**Comment by benjaminion** [comment]
> As mentioned memory is extended by reading or writing an offset not previously touched. Changing alloc to mload would at least solve the overwriting issue.

Agreed, but two issues:

 1. There is no `MLOAD8` opcode, so some logic change is needed.
 2. When I try to implement it with `MLOAD` there seems to be a compiler problem (see below).

> Not entirely sure an overhaul is not needed, because static memory ranges are assumed right now by the compiler, such as the range by set/get, etc.

Also agreed. There is some legacy code at the top of liblll/CodeFragment.cpp to handle conflict with variables storage, I think. But it is no longer effective since `vars.size` is not managed when variables are created:

```
void CodeFragment::finalise(CompilerState const& _cs)
{
	if (_cs.usedAlloc && _cs.vars.size() && !m_finalised)
	{
```

> Do I understand correctly that (alloc n) allocated n bytes and returns the starting offset?

Yes, except that 32 * (1+(n-1)/32) bytes are allocated (rounded up to a multiple of 32).

> I'd rather go into thinking about a proper design of these LLL features and do an overhaul at some point.

Yes. I'm not honestly a fan of `alloc`; it seems to me that most will want to do their own memory management. That's kind of the point of LLL.

In the meantime, the following is a quick fix that still uses `MSTORE8`, but fixes the immediate issue effectively. For the `(alloc 0)` case it allocates 32 bytes as suggested by @chriseth.

```
m_asm.append(Instruction::MSIZE);
m_asm.append(u256(0));
m_asm.append(u256(1));
m_asm.append(code[0].m_asm, 1);
// Handle (alloc 0) case: always alloc at least 32 bytes.
m_asm.append(Instruction::DUP1);
m_asm.append(Instruction::ISZERO);
m_asm.append(Instruction::ADD);
m_asm.append(Instruction::MSIZE);
m_asm.append(Instruction::ADD);
m_asm.append(Instruction::SUB);
m_asm.append(Instruction::MSTORE8);
```

The above code all seems to work as expected and should be safe.

Now, the code below is an attempt to use `MLOAD` instead of `MSTORE8` to achieve the same thing. I believe it should work, but for reasons unclear the compiler does not emit the `MLOAD` instruction, although it emits all the rest! So my implementation is currently failing.

```
m_asm.append(Instruction::MSIZE);
m_asm.append(u256(32));
m_asm.append(Instruction::DUP1);
m_asm.append(u256(1));
m_asm.append(code[0].m_asm, 1);
m_asm.append(Instruction::DUP1);
m_asm.append(Instruction::ISZERO);
m_asm.append(Instruction::ADD);
m_asm.append(Instruction::SUB);
m_asm.append(Instruction::DIV); // Align on 32 byte boundary
m_asm.append(Instruction::MUL);
m_asm.append(Instruction::MSIZE);
m_asm.append(Instruction::ADD);
m_asm.append(Instruction::MLOAD); // <-- The compiler does not emit this!! Why not?
m_asm.append(Instruction::POP);
```

This is the assembly produced. You can see that `mload` is missing at the end.  This is a mystery.

```
build> echo '(alloc 64)' | lllc -a
  msize
  0x20
  dup1
  0x1
  0x40
  dup1
  iszero
  add
  sub
  div
  mul
  msize
  add
  pop
```

**Comment by axic** [comment]
> There is no MLOAD8 opcode, so some logic change is needed.

`MSTORE8` writes strictly 8 bits to the offset provided. In order not to overextended by 248 bits, just do an `MLOAD(SUB(n, 31))`

**Comment by benjaminion** [comment]
> MSTORE8 writes strictly 8 bits to the offset provided. In order not to overextended by 248 bits, just do an MLOAD(SUB(n, 31))

That could work. We'd need to handle the case that n < 31 so as not to attempt to read from the top of memory. E.g. `(alloc 8)` with MSIZE initially 0 (another edge case).

**Comment by axic** [comment]
Having read the above again, I think `alloc 0` should equal to `msize`. I'm not sure why `MLOAD` is omitted in the above code, will check.

**Comment by axic** [comment]
It is some kind of optimiser issue as for example: `(alloc 0)` works, but `(return (alloc 0))` optimises it out, however forcing the usage of the stack (such as `keccak256`) keeps it even in that case.
