### ISSUE TITLE
Modifiers are considered like public functions when they are always internal

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#2468]
The following code doesn't compile.
```
contract Foo {
    struct S { }
    
    modifier mod(S storage x) {
        _;
    }
}
```
```
Error: Location has to be memory for publicly visible functions (remove the "storage" keyword).
    modifier mod(S storage x) {
                 ^---------^
```

Modifiers are always called internally and so it looks to me like this should be possible.

**Comment by chriseth** [comment]
Thanks for reporting! I wonder whether we "introduced" this only lately by visiting function parameters in the type checker?

**Comment by chriseth** [comment]
Ok, it was not added recently, therefore removing the "nextrelease" tag.
