### ISSUE TITLE
Hard to debug contract

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/solidity#2477]
Everytime change contract we need to past it to web3 command and miner.start then execute contract function.

Are there some tool that like Remix but can execute function directly in web UI?

**Comment by chriseth** [comment]
This sounds like a feature request for remix, can you create an issue in github.com/ethereum/browser-solidity, please? We are currently working on a console that might help you. In any case, please contact @yann300 to tell about your use-case, we are always eager to hear about how people use remix and the debugger.
