### ISSUE TITLE
Refactor implicit case fallthroughs in the code

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/solidity#2479]
As a continuation of https://github.com/ethereum/solidity/pull/2339 there are 2 places in the codebase where we rely on an implicit fallthrough of a `case` in a `switch` statement. 

The linked PR simply disables the gcc > 7.0 warning for implicit fallthrough warning, going around the problem.

This issue is for properly refactoring the code so that no implicit fallthrough is required.

**Comment by axic** [comment]
Also remove it from Cmake when done: https://github.com/ethereum/solidity/blob/develop/cmake/EthCompilerSettings.cmake#L97

**Comment by axic** [comment]
Add support for running CI with gcc > 7.0 and remove the flag from Cmake.

@chfast is it possible to use gcc 7.0?

**Comment by chfast** [comment]
Fixed in #2946.

**Comment by chfast** [comment]
Both GCC7 and clang5 warn about missing `[[fallthrough]]`.
