### ISSUE TITLE
Option to disable Unused local variable warning

### ISSUE THREAD

**Issue by madvas** [ethereum/solidity#2482]
There should be option to disable "unused local variable" warnings, since it's very annoying during development and makes errors harder to see. Many 3rd party contracts/libraries produce this warning, which makes it even worse. 

Thank you

**Comment by chriseth** [comment]
You can "disable" the warning by e.g. commenting out the name of the variable:

`function f(uint /* x */) { }`.

**Comment by madvas** [comment]
Yeah, but wouldn't it be just simpler if we could do something like `--disable-unused-var-warning`

**Comment by chriseth** [comment]
Disabling all unused variable warnings is too strong and there is a good way to disable the warning locally. Closing this.
