### ISSUE TITLE
Drop constant keyword from functions

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2502]

**Comment by o0ragman0o** [comment]
*surprised* Is there some reasoning for this somewhere? `constant` has pretty specific compiler behaviour.

**Comment by qjflores** [comment]
I currently have contracts that use 'constant', what changes or actions do I need to take to ensure the same behavior?

**Comment by axic** [comment]
It will be replaced with `view` (same as what `constant` means) and `pure` specifiers.

**Comment by o0ragman0o** [comment]
In what sense will `pure` be used?

**Comment by axic** [comment]
Please see https://solidity.readthedocs.io/en/develop/miscellaneous.html#modifiers for explanation.

**Comment by axic** [comment]
The function part is done, created #4755 to track the ABI part.
