### ISSUE TITLE
Enable safety features in Emscripten

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2506]
We could enable debugging/safety features in the emscripten build (https://kripken.github.io/emscripten-site/docs/porting/Debugging.html):
- `ASSERTIONS=1` is used to enable runtime checks for common memory allocation errors
- `SAFE_HEAP=1` adds additional memory access checks, and will give clear errors for problems like dereferencing 0 and memory alignment issues.
- `STACK_OVERFLOW_CHECK=1` (see the description there)

**Comment by ekpyron** [comment]
Last state of this was the idea to add a dedicated test run with these enabled to be run before releases, but to not actually enable them. Given that I'm closing https://github.com/ethereum/solidity/pull/2519 for now and queue this issue for 0.5.12.

**Comment by chriseth** [comment]
Closing since the benefit is probably not too large but the runtime overhead is.
