### ISSUE TITLE
Metropolis-upgrade to chain parameters for the test

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2508]
https://github.com/ethereum/solidity/blob/aa262d5c8febadd067539c1e05232b1b8c91b4f5/test/RPCSession.cpp#L214 has the chain parameters used for testing Solidity.

Here, only the first four precompiled contracts are listed, but after Metropolis more precompiled contracts should appear.

@chriseth do you agree this should be done?

**Comment by chriseth** [comment]
Yes, good idea!
