### ISSUE TITLE
Version 0.5.0

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2511]
Since the next release is 0.4.12 and 13/14 are numbers with specific meaning in the western or eastern side of the globe it may make sense doing the breaking 0.5.0 release next.

**Comment by chriseth** [comment]
Yes, let's start work on 0.5.0:

  https://github.com/ethereum/solidity/issues?q=is%3Aissue+is%3Aopen+label%3A%22breaking+for+0.5.0%22

On the other hand: I want to avoid having such a gigantic release cycle again. Let's either not merge breaking stuff or merge it into a different branch, so that we are still able to make a release every week or every second week if needed.

**Comment by axic** [comment]
@chriseth I think we agreed to merge and enable some of these changes with `pragma experimental v0.5.0;`

**Comment by fulldecent** [comment]
Is there a link for 0.5.0 experimental documentation?

**Comment by chriseth** [comment]
No, we do not yet have documentation for it.

**Comment by fulldecent** [comment]
Here is exhaustive documentation for v0.5.0 so far. Maybe you can tell me a good place to put this.

- Unary + [is now disallowed](https://github.com/ethereum/solidity/blob/bc39e730b6acaff7bb2bdb3ad99547ab6cdc1841/libsolidity/analysis/SyntaxChecker.cpp#L189-L190) (formerly deprecated)

  ```solidity
  // THIS WONT COMPILE WITH V050
  pragma solidity ^0.4.19;

  contract Foo {
      function() public {
          var a = +5;
      }
  }
  ```

- `callcode` [is now disallowed](https://github.com/ethereum/solidity/blob/0ae4aad8f346e3c23873aa97a359239714f3c039/libsolidity/analysis/StaticAnalyzer.cpp) (formerly deprecated)

  ```solidity
  // THIS WONT COMPILE WITH V050
  pragma solidity ^0.4.19;

  contract D {
      function callcode(address _contract, bytes4 _functionHash, uint _callData) public {
          require(_contract.delegatecall(_functionHash, _callData));
    }
  }
  ```

- `view` keyword [is now enforced](https://github.com/ethereum/solidity/blob/2cdd789b5d371de6612dadb4ae9a18359cf150df/libsolidity/analysis/ViewPureChecker.cpp#L126-L128)

  ```solidity
  // THIS WONT COMPILE WITH V050
  pragma solidity ^0.4.19;

  contract A {
      string a;
      function aView() public view {
          a = "yo";
      }
  }
  ```

- Storage location [must be specified](https://github.com/ethereum/solidity/blob/a75d5333d8ae614316b9c707e2022c2d144eaf33/libsolidity/analysis/ReferencesResolver.cpp#L303-L306) as either "memory" or "storage".

  ```solidity
  (Will has no idea what this means)
  ```

- Fallback function [must be declared](https://github.com/ethereum/solidity/blob/a75d5333d8ae614316b9c707e2022c2d144eaf33/libsolidity/analysis/TypeChecker.cpp#L125-L126) as `external`

  ```solidity
  // THIS WONT COMPILE WITH V050
  pragma solidity ^0.4.19;

  contract A {
      function() public payable {
          
      }
  }
  ```

- [Adjusts gas sent](https://github.com/ethereum/solidity/blob/8fbfd62d15ae83a757301db35621e95bccace97b/libsolidity/codegen/ExpressionCompiler.cpp#L1724-L1726) for calls to handle [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md)

- [Do not populate address members](https://github.com/ethereum/solidity/blob/060b2c2b23da99836eb54dc30eb7d870016bcb7a/libsolidity/ast/Types.cpp#L1664-L1667) into the contract  (Will has no idea what this means)

**Comment by OTTTO** [comment]
did we not choose to go with a keyword for fallback functions??

**Comment by chriseth** [comment]
@OTTO there was no clear conclusion about how to name the actual fallback function (function selector set, but does not match any function in the contract) and the function that is called when ether is sent and not data. It will probably go into 0.6.0.

**Comment by chriseth** [comment]
@axic what is this issue about, i.e. when can it be closed? Doesn't the project cover this?

**Comment by axic** [comment]
I don't remember, this was prior the introduction of the project feature.
