### ISSUE TITLE
0.4.11 compiler doesn't throw any error but 0.4.12 throws an internal compiler error when compiling same contracts

### ISSUE THREAD

**Issue by Dexaran** [ethereum/solidity#2517]
The source codes of contracts and error descriptions are located here: https://github.com/Dexaran/solidity/tree/master/Compiler-Errors

These contracts are compiled without errors when trying to compile them using `0.4.11+commit.68ef5810`.

There is an internal compiler error when trying to compile them using `0.4.12+commit.194ff033`.

` 0.4.12-nightly.2017.6.23+commit.793f05fa` compiles it without any errors also.
For the first time the error appears in version `0.4.12-nightly.2017.6.25+commit.29b8cdb5`.

**Comment by slothbag** [comment]
I'm getting a similar issue.. contracts compiled fine in 0.4.11, in 0.4.12 I get the following error:
```
Internal compiler error during compilation:
C:\projects\solidity\libsolidity\codegen\CompilerContext.cpp(127): Throw in function void __cdecl dev::solidity::CompilerContext::addVariable(const class dev::solidity::VariableDeclaration &,unsigned int)
Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::solidity::InternalCompilerError>
std::exception::what: Unknown exception
[struct dev::tag_comment * __ptr64] = Variable already present
Error performing solc 1
```

**Comment by axic** [comment]
@slothbag do you have a source code to reproduce this?

**Comment by slothbag** [comment]
This appears enough to do it

```
pragma solidity ^0.4.12;
contract Test1 {
    modifier m1 {
        address a1 = msg.sender;
        _;
    }
    function f1() m1() {
    }
    function f2() m1() {   
    }
}
```

**Comment by chriseth** [comment]
These are actually two bugs. We still need a short example that triggers the following bug:
```
Dynamic exception type: N5boost16exception_detail10clone_implIN3dev8solidity21InternalCompilerErrorEEE
std::exception::what: std::exception
[PN3dev11tag_commentE] = Unknown kind of function call .
```

**Comment by chriseth** [comment]
"unknown kind of function call" is an error generated in the AST JSON export routine.

**Comment by chriseth** [comment]
Ah, it might  be that this error was related to the previously incomplete compiler stack state checks, i.e. where it generated the ast json export for source that was not properly parsed.
