### ISSUE TITLE
unclear error message for `--combined-json`

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/solidity#252]
When using `--combined-json` without arguments, the resulting error message is inaccurate (it mentions about `--json` instead of `--combined-json`).

```
$ touch test.sol
$ solc test.sol --combined-json
the required argument for option '--json' is missing
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.1.6-0/Release-Linux/g++/int linked to libethereum-0.9.93-0/Release-Linux/g++/int
```

I would have loved to file a PR for this, but I could not figure out, how and where the error message is constructed :(

**Comment by chriseth** [comment]
Nice find! Thanks for your efforts, but there is a reason you did not find the place: it is actually a bug in the boost library we use:
https://svn.boost.org/trac/boost/ticket/8009

The fix is included in version 1.56.0
