### ISSUE TITLE
Method/constructor array args are interepreted wrong

### ISSUE THREAD

**Issue by asinyagin** [ethereum/solidity#254]
Hi,

I have a contract:

```
contract C2 {
    function C2(uint[1] i) {
        log0(bytes32(i[0]));
    }
}
```

Binary for this contract: `60606040526040516020806062833981016040528080518201919060200150505b8060006001811015600257909060200201516001026040518082815260200191505060405180910390a05b50600a8060586000396000f360606040526008565b00`. So, to create it I send: `60606040526040516020806062833981016040528080518201919060200150505b8060006001811015600257909060200201516001026040518082815260200191505060405180910390a05b50600a8060586000396000f360606040526008565b000000000000000000000000000000000000000000000000000000000000000001` (contract binary + 32 bytes of arg). But it prints 256 instead of 1. I checked that with solc 0.1.6 and 0.1.7.

**Comment by chriseth** [comment]
Confirmed using

```
contract C2 {
    bytes32 public x;
    function C2(uint[1] i) {
        x = bytes32(i[0]);
    }
}
```

in browser-solidity.

**Comment by chriseth** [comment]
The bug only happens for constructor arguments that are of fixed-size array type (i.e. it does not apply for normal functions). They were incorrectly interpreted as dynamically-sized.
