### ISSUE TITLE
clang bulid error

### ISSUE THREAD

**Issue by qhdwns123** [ethereum/solidity#2547]
Hi

Is there a way to fix the error below?

```
../libdevcore/libsoldevcore.so: error: undefined reference to 'boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
../libdevcore/libsoldevcore.so: error: undefined reference to 'boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
solc/CMakeFiles/solc.dir/build.make:136: recipe for target 'solc/solc' failed
make[2]: *** [solc/solc] Error 1
CMakeFiles/Makefile2:335: recipe for target 'solc/CMakeFiles/solc.dir/all' failed
make[1]: *** [solc/CMakeFiles/solc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

Thanks.

**Comment by axic** [comment]
@qhdwns123 can you tell us details of your system? OS version, Boost version, compiler version, etc.

**Comment by qhdwns123** [comment]
@axic 

Clang version: 
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Boost Version:  dpkg -s libboost-dev | grep 'Version'
Version: 1.58.0.1ubuntu1
cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_58"


OS: Ubuntu 16.04 32bit.

**Comment by axic** [comment]
I think it is this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823978

Which was fixed in a later Boost version.

**Comment by qhdwns123** [comment]
I'll try.

There are many people who have similar problems with the internet. :)

**Comment by axic** [comment]
@chriseth @chfast could we issue a warning in cmake for a specific boost version?

**Comment by chriseth** [comment]
Is this only related to clang? I wonder why this does not happen in the PPA.

**Comment by axic** [comment]
The debian bugreport is with g++.

**Comment by chriseth** [comment]
solc builds fine on ubuntu 16.04, 32 bit with boost 1.58: https://launchpadlibrarian.net/327012599/buildlog_ubuntu-xenial-i386.solc_1%3A0.4.13-0ubuntu1~xenial_BUILDING.txt.gz

So the problem seems to be clang. @qhdwns123 can you try building with gcc?

I would not like to force the boost version to 1.60 because then we cannot build natively on these ubuntu versions.

**Comment by qhdwns123** [comment]
I succeeded in building it in a clean environment.

In 16.04 LTS version, gcc build succeeds. 

Thank you for your help!
