### ISSUE TITLE
eth_compileSolidity error

### ISSUE THREAD

**Issue by mahan14** [ethereum/solidity#2548]
web3.eth.compile.solidity(foodSafeSource, function(error, foodSafeCompiled){
        console.log(error);
       console.log(foodSafeCompiled);
          foodSafeABI = foodSafeCompiled['<stdin>:FoodSafe'].info.abiDefinition;
           foodSafeContract = web3.eth.contract(foodSafeABI);
          foodSafeCode = foodSafeCompiled['<stdin>:FoodSafe'].code;

Not able to parse my contract, getting eth_compileSolidity, not available, please suggest any alternative.

**Comment by axic** [comment]
In recent clients the RPC method `eth_compileSolidity` has been removed. Please use the compiler directly, I suggest giving https://remix.ethereum.org a try. 

For any other issues with web3, please report on https://github.com/ethereum/web3.js.
