### ISSUE TITLE
Replace `var` with `auto`

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2558]
This is not a mature proposal yet, but the benefit is that it discourages the use of `var`, since `auto` needs some prior reading from the user.

**Comment by chriseth** [comment]
... you mean a user that assumes Solidity == Javascript?

**Comment by axic** [comment]
For a C++ user it will be clear types are derived automatically and a Javascript user wouldn't be inclined to use `var` as they could be today.

**Comment by axic** [comment]
> ... you mean a user that assumes Solidity == Javascript?

That is the assumption by many and was even suggested by old documentation.

**Comment by axic** [comment]
`var` has been deprecated in #3301. Closing this now.
