### ISSUE TITLE
How to get return data from a failing call

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2568]
Is it possible that a contract written in Solidity calls another contract that fails, but gets the returned data?

* The recommended syntax `contract.method(arg0, arg1)` causes an exceptional halt when the callee fails.
* The lower level syntax `contract.call(something)` does not give access to the returned data.

Originally @dip239 asked me this question.

**Comment by axic** [comment]
From my side this is tracked in #434.

**Comment by pirapira** [comment]
Yes, #434 will do it.  @dip239

**Comment by axic** [comment]
Also the higher level part can be considered to be tracked by #1505.
