### ISSUE TITLE
Improve error message for trailing commas in function signatures

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2579]
Current message:
```
test.sol:4:31: Error: Expected type name
  function foo(uint a, uint b,) {}
                              ^
```
Improved message:
```
test.sol:4:31: Error: Unexpected trailing comma in function arguments
  function foo(uint a, uint b,) {}
                             ^
```

Also applies to return types:
```
test.sol:4:45: Error: Expected type name
  function foo(uint a, uint b) returns(uint,) {}
                                            ^
```

**Comment by axic** [comment]
Should be simple enough to change the parser (check if the next token is `rparen`).

**Comment by federicobond** [comment]
Yes, wrote it here to remember it, plus, it's a nice one for beginners to tackle.

**Comment by axic** [comment]
In `libsolidity/parser/Parser.cpp` change `parseParameterList`. This will "fix" it for:
- function arguments (in function definitions and function types)
- return parameters (in function definitions and function types)
- event arguments
- modifier arguments

 Special care must be taken (i.e. enough tests must be added) to ensure it doesn't break anything else.

**Comment by JohnAllen** [comment]
Is this issue a) changing the parser, b) improving an error message or c) both?

**Comment by federicobond** [comment]
Only improving the error message.
