### ISSUE TITLE
Numerical Issues

### ISSUE THREAD

**Issue by GoldenDave** [ethereum/solidity#2587]
The following code will freeze remix and die inside geth's simulated backend

```
pragma solidity ^0.4.13;

contract test{
    uint256 rateMM = 9999452054794520548;
    uint256 rateN = 999945205479452;
    uint256 maxRate = 999945205479452;
    
    function testIt() returns (uint256 r) {
        uint256 pow = 2;
        uint256 newN = rateN ** pow; // check for overflow
        uint256 checkVal = newN / maxRate;
        r = checkVal;
    }
}
```

**Comment by axic** [comment]
Can you please describe the kind of failure? What is the gas limit supplied to these clients? Does it run out of gas? Have you tried lowering the gas limit to see what happens?

**Comment by GoldenDave** [comment]
or to make it easier...

```
pragma solidity ^0.4.13;

contract test{
    function x()returns (uint) {
        uint a = 999560084690683640515566850045758101858937890625;
        uint b = 999780018149334509150625;
        return uint(a / b); // hangs here with or without the cast
    }
}
```

**Comment by GoldenDave** [comment]
![image](https://user-images.githubusercontent.com/18424493/28326824-647e00fe-6c14-11e7-9f0f-56cd545c5eab.png)

**Comment by GoldenDave** [comment]
```
pragma solidity ^0.4.13;

contract test{
    function x() constant returns (uint) {
        uint a = 999560084690683640515566850045758101858937890625;
        uint b = 999780018149334509150625;
        return uint(a / b);
    }
}
```

![image](https://user-images.githubusercontent.com/18424493/28326884-886ace5c-6c14-11e7-998a-9dfc8cd4da90.png)

**Comment by axic** [comment]
Do you have optimisations turned on or off?

**Comment by GoldenDave** [comment]
![image](https://user-images.githubusercontent.com/18424493/28327093-125bfdde-6c15-11e7-9b43-aef46498934d.png)

**Comment by GoldenDave** [comment]
OFF

**Comment by GoldenDave** [comment]
Let's go a bit further.... with 0.4.14-nightly.2017.7.18+commit.c167a31b.Emscripten.clang
```
pragma solidity ^0.4.13;

contract test{
    function x() constant returns (uint) {
        uint a = 999560084690683640515566850045758101858937890625;
        uint b = 999780018149334509150625;
        return a / b;
    }
    function y() constant returns (uint) {
        uint a = 999560084690683640515566850045758101858937890625;
        uint b = 999780018149334509150625;
        uint c;
        assembly {
            c := div(a,b)
        }
        return c;
    }
}
```

![image](https://user-images.githubusercontent.com/18424493/28344975-ab0ab11c-6c59-11e7-8795-9879dd4ef338.png)

**Comment by axic** [comment]
The bytecode doesn't contain a `DIV` instruction.

**Comment by axic** [comment]
It seems to fail incorrectly on the division by 0 check.

**Comment by GoldenDave** [comment]
Thanks for the fast attention.

**Comment by axic** [comment]
Are you sure this fails with geth? It seems to me a remix bug, where the `ISZERO` instruction is broken. Turning optimisations on will remove all that and the code works.

Original issue: https://github.com/ethereum/browser-solidity/issues/628

**Comment by GoldenDave** [comment]
I will re-test and let you know.

**Comment by GoldenDave** [comment]
OK - my mistake - we got there tracking what must have been another error.

https://github.com/DaveAppleton/testSBE

**Comment by axic** [comment]
Can we close this here then? It must be fixed in Remix.

The relevant Remix error is: https://github.com/ethereum/browser-solidity/issues/634.

**Comment by axic** [comment]
Fixed in Remix.
