### ISSUE TITLE
Exception during creating contract from function in solidity

### ISSUE THREAD

**Issue by reddec** [ethereum/solidity#2601]
We have this contract in Remix:

```solidity
pragma solidity ^0.4.10;

contract Sample {
    
}


contract Generator {
    function make() payable returns (Sample something) {
        return new Sample();
    }
}
```

If you will try to create `Generator` and then invoke `make()` the 

    Exception during execution. (invalid opcode). Please debug the transaction for more information.

is rised.

**Versions:**

* Remix: soljson-v0.4.13+commit.fb4cb1a.js
* Solidity: 0.4.10

**Comment by axic** [comment]
This seems to be due to a bug in Remix. Can you test it with a local RPC node (do not use the VM mode in Remix).

The relevant Remix error is: https://github.com/ethereum/browser-solidity/issues/634.

**Comment by axic** [comment]
Fixed in Remix.
