### ISSUE TITLE
Unused Local Variable error in Crowdsale contract

### ISSUE THREAD

**Issue by ErvinSenaj** [ethereum/solidity#2610]
Hi everyone, I've been trying to create a crowd sale contract but it does not compile and comes with the error "unused local variable". Really not sure what to do as the code came directly from the ethereum crowd sale guide. 
![image](https://user-images.githubusercontent.com/30314368/28410549-ebafe052-6d35-11e7-9bd1-f73fbbfb028d.png)

**Comment by axic** [comment]
This is actually a warning, just your IDE presents it as an error.

Remove the parameter names from `transfer`:  `contract token { function transfer(address, uint) {} }`

**Comment by axic** [comment]
Please try https://remix.ethereum.org, which displays errors/warnings and join https://gitter.im/ethereum/solidity if you need more help.

**Comment by axic** [comment]
Tracked in https://github.com/ethereum/mist/issues/2797
