### ISSUE TITLE
Check for actual error message in NameAndTypeResolution tests

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2613]
Many of the test cases only check that there is a `DeclarationError` or a `TypeError`:
```
CHECK_ERROR(text, TypeError, "");
```

This should be changed to include the actual message expected, such as:
```
CHECK_ERROR(text, TypeError, "Interfaces cannot inherit");
```

**Comment by izgzhen** [comment]
I can help on this :)

**Comment by axic** [comment]
@izgzhen thanks!

The file in question is this: https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SolidityNameAndTypeResolution.cpp. Start anywhere you like within the file.

You can run the tests locally as described here: http://solidity.readthedocs.io/en/develop/contributing.html#running-the-compiler-tests

Submitting a pull request will run the tests on Travis anyway. You can also submit a work in progress pull request and keep adding more of these clarifications to it before merging.
