### ISSUE TITLE
Option to output concatenated source code

### ISSUE THREAD

**Issue by dbrock** [ethereum/solidity#2620]
Can we add an option (perhaps `--src` and `--combined-json=src`) that causes the compiler to simply output the concatenated source code after resolving all `import` statements?

This is needed for e.g. Etherscan verification and is quite tedious to perform by hand if you have multiple layers of recursive dependencies.

dapphub/ds-token#13

**Comment by chriseth** [comment]
If you just concatenate the source files, you might get a different result. Etherscan has to implement a multi-file feature if it wants to verify all contracts. As an example:

a.sol:
```
contract C {}
```
b.sol:
```
import "b.sol" as X;
contract C {}
```

If you concatenate these two files, imports will break and you will get multiple identifiers with the same name.

**Comment by iam-peekay** [comment]
@chriseth so is the only option right now to either write my own script to concatenate files and/or do it manually?

**Comment by chriseth** [comment]
@iam-peekay you might find this tool here handy: https://github.com/BlockCatIO/solidity-flattener

**Comment by iam-peekay** [comment]
I'll check this out. Thank you! @chriseth
