### ISSUE TITLE
Run the test suite with Geth too

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2626]
This depends on https://github.com/ethereum/interfaces/issues/4 (i.e. agreeing on a test RPC class and implementing it in Geth).

Added here as a long term goal.

**Comment by chriseth** [comment]
Is this about always running geth and cpp-ethereum as part of the CI? If yes, then I don't see the benefit. Whether or not the two clients produce the same result is not something that should be tested with the solidity CI, but with the cpp-ethereum / go-ethereum CI. We can provide scripts to run on demand, though.

Making soltest compatible with both cpp-ethereum and geth, on the other hand, is something we should do.

**Comment by axic** [comment]
First, the RPC API must be defined and other clients need to support it. It would be useful for developers coming from other clients.

Second, I think running it with both Geth and Cpp is useful in CI, because despite best efforts in test case creation (ethereum-tests), even if a single test failure can be produced in Solidity in the future, it was worth the extra 2-3 minutes spent on CI.

**Comment by lazaridiscom** [comment]
This issue should get priority. It made a really bad impression to me (and for sure to other users) that this is not standardized.

> This depends on ethereum/interfaces#4 (i.e. agreeing on a test RPC class and implementing it in Geth).

Suggestion: Solidity is a major subsystem of Ethereum. Solidity uses currently cpp-ethereum for tests. This exact api should be make available initially in geth and the other clients. It can be later extended.

**Comment by ekpyron** [comment]
They merged "retesteth" support in https://github.com/ethereum/go-ethereum/pull/19631, so it might be worth looking into this again, since they now seem to implement most, if not all, of the RPC API we need for soltest.
EDIT: Adding this to the 0.5.10 project to stage it for reconsideration.

**Comment by chriseth** [comment]
De-prioritizing because we probably want to switch to EVM-C first and then this should be easy to do.

**Comment by axic** [comment]
This is now obsolete since we use EVMC + evmone.
