### ISSUE TITLE
Warn about usage of uninitialized storage pointer in all code paths.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2628]
The compiler currently does not warn about the use of an uninitialized storage pointer in the following code.
```
contract c {
    struct S { uint x; }
    S s;
    function f(bool flag) {
        if (flag) {
            S storage l = s;
        }
        l.x = 2;
    }
}
```
This will be fixed by changing the scoping rules away from JavaScript, but in the meantime, we should still have a warning. This requires a control flow graph, which could be a useful structure in general.

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/1789

**Comment by chriseth** [comment]
Even after #1789, return values are still problematic:

```
contract c {
    struct s { uint a; }
    function f() internal returns (s) {
    }
}
```

**Comment by ekpyron** [comment]
First I thought the control flow graph could just ignore function calls, but there are cases for which cross-function control flow is required, e.g. the following should be fine and not warn:

```
contract C {
    struct s { uint a; }
    function my_revert() internal {
        revert();
    }
    function f(bool flag) internal returns (S storage c) {
        if (flag) c = s;
        else my_revert();
    }
}
```

**Comment by ekpyron** [comment]
However, I don't think all cases can be caught anyways.

```
contract C {
    struct S { uint a; }
    function my_revert() internal {
        revert();
    }
    function my_revert2() internal {
        revert();
    }
    function f(bool flag, bool flag2) internal returns (S storage c) {
        if (flag) c = s;
        else (flag2 ? my_revert : my_revert2)();
    }
}
```

Probably most of such cases are corner cases, though. The only function calls that are problematic are calls to functions that never return, but always revert... And in those cases a potential warning could easily be supressed, e.g. by:


```
contract C {
    struct S { uint a; }
    function my_revert() internal {
        revert();
    }
    function my_revert2() internal {
        revert();
    }
    function f(bool flag, bool flag2) internal returns (S storage c) {
        if (flag) c = s;
        else
        {
             (flag2 ? my_revert : my_revert2)();
             revert();
        }
    }
}
```

**Comment by chriseth** [comment]
Don't make it too complicated for the first version :)

**Comment by ekpyron** [comment]
@chriseth Ok :). However, unfortunately, incompleteness in the first version will mostly result in false positives and not false negatives, which may be annoying - so I'll still try to minimize that already. I'll continue to ignore function calls for now, though, since I reckon this will rarely be an issue and there is a workaround to suppress the warning.

For simplicity I'll also consider every reference from inline assembly as an assignment without checking the control flow in there and/or whether it's actually a load instead of a store.
