### ISSUE TITLE
Abstract getters should describe contracts public state variables

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/solidity#2633]
An abstract getter function does not appear to describe a public state variable of the same name.

The following contract compiles as abstract because the abstract interface function is not explicitly implemented in the contract.
Given that state variables cannot be included in interfaces, contract state variables need to be private with explicit getter functions rather than the very handy accessor model.

(I note that there are a number of other current issues surrounding `interface` `public` and `constant` keywords so apologies if this is being addressed elsewhere)

    interface TestInterface {
        function foo() public constant returns (uint);
    }

    contract Test is TestInterface {
        uint public foo;
    }

**Comment by axic** [comment]
Relevant #1565.

**Comment by ondratra** [comment]
It's not an issue of only `interface`. `contract` is working neither.
```
contract TestInterface {
    function foo() public constant returns (uint);
}

contract Test is TestInterface {
    uint public foo;
}
```
