### ISSUE TITLE
Discuss: disallow visibility specifiers in constructor functions

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2638]
I was doing some experiments with visibility specifiers and noticed that constructor functions can be defined as `internal`. This causes the contract to be marked as abstract, but child contracts can call the super constructor without problems.

Are there any real world use cases of this? Is it something we would like to support?

**Comment by axic** [comment]
Prior reading #979 😉

**Comment by axic** [comment]
Example code:
```
contract A {
  uint public a;

  function A(uint _a) internal {
    a = _a;
  }
}

contract B is A(1) {
  function B() {}
}
```

**Comment by axic** [comment]
@federicobond the reason is explained in #3132. Is there any need to keep this issue?

**Comment by federicobond** [comment]
No need. We can close it.

**Comment by Tectract** [comment]
I'm not sure I understand the full implications of public versus internal constructor functions, but I know I'm getting a compiler warning on the "standard" erc20 token contract in the latest solc compiler version. Is it safe to just make the constructor as public?
