### ISSUE TITLE
Custom getters for user-defined structs

### ISSUE THREAD

**Issue by NoahZinsmeister** [ethereum/solidity#2648]
Will it be/is it currently possible to write custom getters for public variables that are user-defined structs, possible with something like a getter modifier? E.g.:

```
pragma solidity ^0.4.13;

contract Example {
    struct myStruct {
        uint myInt;
        bool myBool;
        bytes32[] myArr;
    }

    myStruct public expose;

    function expose() getter returns (bool) {
        return expose.myBool;
    }
}
```

**Comment by chriseth** [comment]
This is not possible without modifying the name, although I think the following  should be allowed:

```
pragma solidity ^0.4.13;

contract Example {
    struct myStruct {
        uint myInt;
        bool myBool;
        bytes32[] myArr;
    }

    myStruct expose;

    function expose() external returns (bool) {
        return expose.myBool;
    }
}
```

What do you think, @axic?

**Comment by axic** [comment]
It can only work if `expose()` is marked `external`, while if `internal`/`public` it would be a declaration clash. Technically it is fine.

Considering the reliance on visibility, it may not be a good idea to allow it to avoid confusion (and potential future issues).
