### ISSUE TITLE
A function is called balance() confuses compiler with balance property

### ISSUE THREAD

**Issue by adria0** [ethereum/solidity#2655]
Using 0.4.13+commit.0fb4cb1a

```
pragma solidity ^0.4.13;

contract A {
    function balance() returns (uint) {
        return 1;
    }
}
contract C {
    event Log(uint v);
    function B() {
        A a = new A();
        Log(a.balance);
    }
}
```
The following error is generated:

```
TypeError: Member "balance" not unique after argument-dependent lookup in contract A
        Log(a.balance);
            ^-------^
```

**Comment by axic** [comment]
`.balance` defaults to the Ether balance of the said contract.

You should be using `a.balance()` to reach your function, but the error is a problem nonethess.

**Comment by axic** [comment]
The real solution will be #2683, but we should try to fix this before the breaking release.
