### ISSUE TITLE
block.timestamp returning 0

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#266]
https://github.com/ethereum/go-ethereum/issues/2029

Contract is compiled using solidity optimizer (Default number of passes)

It works fine when using block.timestamp in the constructor but sets to 0 during function calls.

**Comment by chriseth** [comment]
Could you please provide details on how to reproduce the situation? Please give full source code and not only a single function.

**Comment by chriseth** [comment]
Please reopen if you are able to provide more information.
