### ISSUE TITLE
Documentation: Contracts/creating contracts

### ISSUE THREAD

**Issue by jamesray1** [ethereum/solidity#2661]
I read over and over the following code [here](https://solidity.readthedocs.io/en/develop/contracts.html#creating-contracts
), but I don't fully understand why the checking condition in isTokenTransferOK is the way it is. 

```
function transfer(address newOwner) {
        // Only the current owner can transfer the token.
        if (msg.sender != owner) return;
        // We also want to ask the creator if the transfer
        // is fine. Note that this calls a function of the
        // contract defined below. If the call fails (e.g.
        // due to out-of-gas), the execution here stops
        // immediately.
        if (creator.isTokenTransferOK(owner, newOwner))
            owner = newOwner;
    }
```

```
function isTokenTransferOK(
        address currentOwner,
        address newOwner
    ) returns (bool ok) {
        // Check some arbitrary condition.
        address tokenAddress = msg.sender;
        return (keccak256(newOwner) & 0xff) == (bytes20(tokenAddress) & 0xff);
```

I understand what the checking condition in isTokenTransferOK does, but how does the following check "ask the creator if the transfer is fine"? Wouldn't that require user input from the creator (with appropriate checks)?
```
if (creator.isTokenTransferOK(owner, newOwner))
            owner = newOwner;
```

**Comment by jamesray1** [comment]
@chriseth

**Comment by chriseth** [comment]
This is probably not the most meaningful example. Note that the creator is a smart contract and not a user.

**Comment by jamesray1** [comment]
Ah OK. Yeah thanks for clarifying that point, it slipped my mind.

**Comment by aj07** [comment]
@chriseth @axic Do we need to work on it. On read the docs there is already example on subcurrency.
