### ISSUE TITLE
Add code coverage CI

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2663]

**Comment by chfast** [comment]
Can it be https://codecov.io/gh/ethereum/cpp-ethereum ?

**Comment by axic** [comment]
Never used any tools for C++ so have no preference, apart from not having comments on pull requests from the bots (at least now) and as long as it can mark a build failed if coverage decreased, say more than 1%.

**Comment by chfast** [comment]
It can all of these. Check any newer cpp-ethereum PR.

**Comment by chriseth** [comment]
Using coveralls this could be very helpful to see if all syntax features are caught in the syntax tests (compare TypeChecker.cpp against isoltest). Some links:

 - https://github.com/ethereum/cable/blob/master/CableCompilerSettings.cmake#L118-L129
 - https://github.com/chfast/ethash/blob/master/circle.yml#L100
 - https://github.com/chfast/ethash/blob/master/codecov.yml

Note that the binary used for coverage reporting should not be the same as the release binary.

**Comment by chfast** [comment]
So you prefer coveralls over codecov?

On codecov the coverage is a big flaky, but I suspect it is gcov issue, not the service.

**Comment by chriseth** [comment]
Ah sorry, I did not realize there are two services. One feature we need is separate coverage reports for different binaries. Is that provided by one of them?

**Comment by chfast** [comment]
You mean separate coverage by source code or by runtime execution of different  set of tests?

**Comment by chriseth** [comment]
Separate coverage by runtime execution. I would like to have coverage of TypeChecker.cpp (and others) only through the syntax tests and then a separate coverage report for all other tests.

**Comment by chfast** [comment]
I will take care of this.

**Comment by chfast** [comment]
How to run TypeChecker tests?

**Comment by chfast** [comment]
I believe we have a big issue here: tests are done in other CircleCI job.
I'm not sure about it but 
1) the .gcno files are stored along the object files, if the corresponding directory does not exist it might not work
2) gcov probably needs the source files to process the data.

**Comment by chriseth** [comment]
We could afford running the syntax checks (the ones relevant for the type checker twice). The only problem is that this would bean that the whole `build` directory is the build artefact - which would also be ok, I think.

You run the type checker tests by running `./scripts/soltest.sh -t syntaxTest* --no-ipc   ` or with a direct binary: `./build/test/soltest -t syntaxTest* --no-ipc --testpath $REPO_ROOT/test`

**Comment by chriseth** [comment]
Another short-term solution would be to at least add some scripts that automate these checks locally, so that at least before a release we can confirm that we have at least one test case for each error.
