### ISSUE TITLE
Change block.blockhash() to use the blockhash contract

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2680]
After Metropolis.

**Comment by chriseth** [comment]
Is there a plan to deprecate the opcode?

**Comment by chriseth** [comment]
The blockhash contract is much more expensive, I don't think we should switch to using it.

**Comment by axic** [comment]
For the first 256 items it shouldn't be any different - though it is not decided yet whether it is subsidised or not, given the contract is not ready. In any case the cost will increase.

Alternatively it could call the opcode for <=256 and the contract otherwise, if there will be a significant difference.

**Comment by axic** [comment]
Closing since [EIP-210](https://eips.ethereum.org/EIPS/eip-210) was dropped in Byzantium and hasn't been picked up since.
