### ISSUE TITLE
Method overriding field on interface breaks entire contract.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#2684]
```
contract IFoo {
	function apple() public returns (uint256);
}
contract Foo is IFoo {
	uint256 public apple;
	...
}
```
All other methods on contract Foo will return what appears to be garbage data if you have the above as part of `Foo`.

I would _like_ for the above to work since `function totalSupply() public returns (uint256)` is part of the ERC20 interface and I would like to be able to implement that with a field rather than a function + backing field.  However, if that isn't trivial the compiler should at _least_ error on me rather than outputting a contract that doesn't function correctly.

**Comment by axic** [comment]
Are you sure this is not a problem local to Remix?

Also relevant #2633 and #1565.

**Comment by MicahZoltu** [comment]
I actually can't reproduce this in Remix because for some reason Remix won't let me deploy the contract (though it doesn't have any compiler errors).  Problem is sourced from Pyethereum, using py-solc and solc 0.4.13.

**Comment by axic** [comment]
It doesn't let you deploy, because it considers it as an abstract contract, aka. no bytecode produced.

Are you sure the above compiles with solc?

**Comment by MicahZoltu** [comment]
Using py-solc, I don't get back any compiler errors (normally I do if there is a compile error).  Also, my IDE tooling which does background compiling for me using solc directly I believe doesn't result in any errors.

Re: "abstract contract", if solc will happily spit out no bytecode for a contract without returning an error code, then there is a good chance that py-solc will proceed to do the same and pyethereum will happily let me upload nothing as well.  I'll dig into this a bit, if it turns out to be the case I'll close this issue as a dupe of the two you linked.

**Comment by axic** [comment]
Being abstract is not an error and the result is an empty (0 byte long) bytecode.

It can be argued that abstract contracts should have their own keyword/modifier to avoid ambiguity, see #649.

**Comment by MicahZoltu** [comment]
If it spits out a 0-length byte array as the contract bytecode then I'm pretty sure that is my problem.  Will close this in favor of #649, #2633 and #1565.  😄
