### ISSUE TITLE
FAQ: can a struct be passed to another contract?

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#269]

**Comment by kumavis** [comment]
seemingly no. is it possible to add this feature or is there some fundamental blocker?

**Comment by VoR0220** [comment]
This has already been added to the documentation and it does indeed say that you can so long as the internal modifier is appended.

**Comment by kumavis** [comment]
@VoR0220 thanks for responding

the docs have this to say:

> internal:
> Those functions and state variables can only be accessed internally (i.e. from within the current contract or contracts deriving from it), without using this.

https://solidity.readthedocs.org/en/latest/contracts.html?highlight=internal#visibility-and-accessors

The original question is

> can a struct be passed to _another_ contract?

So it seems the answer is that it is **not** possible. This brings me back to my subsequent question,

> is it possible to add this feature or is there some fundamental blocker?

**Comment by VoR0220** [comment]
wow, silly me...missed that part. I don't think that there isn't a true fundamental blocker...it's just getting the pieces properly aligned. Currently waiting on a struct object in the web3 calls to help with this or last I discussed structs with @chriseth .

**Comment by chriseth** [comment]
Adding structs as ABI types make that possible and it is quite high on our backlog.

**Comment by chriseth** [comment]
Will be implemented here: https://github.com/ethereum/solidity/issues/595
