### ISSUE TITLE
mulmod and addmod by 0 does not throw

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#2694]
`mulmod(a, b, 0)` is zero, which isn't consistent with https://github.com/ethereum/solidity/issues/670
Was it missed?

(tested on http://remix.ethereum.org/#version=soljson-v0.4.14+commit.c2215d46.js)

**Comment by axic** [comment]
I think it was just missed. 

Even the documentation says "Division by zero and modulus with zero throws an exception.", though not for the global functions part (where mulmod / addmod) resides.

**Comment by axic** [comment]
I think fixing this would be a breaking change, since it was missed last time and compiling the same will result in different behaviour.
