### ISSUE TITLE
update brew formula

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/solidity#2705]
The current version in brew for MacOS gives me solidity 0.4.11+commit.68ef5810.Darwin.appleclang and it would be good to update this formula to latest version.

**Comment by axic** [comment]
You must have a local issue, because brew is up to date:
```
$ brew info solidity
ethereum/ethereum/solidity: stable 0.4.14
```

Note, the package is maintained at https://github.com/ethereum/homebrew-ethereum.
