### ISSUE TITLE
not calling base constructor with arguments should raise compiler error

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/solidity#2706]
The following contract has a base contract with a constructor that requires arguments and that then gets derived by another contract that does not explicitly call the base constructor:
```
contract base {
    uint public a;
    string public b;
    
    function base(uint _a, string _b) {
        a = _a;
        b = _b;
    }
}

contract derived is base {
    function derived() {
    }
}
```

According to [the documentation]

> Derived contracts need to provide all arguments needed for the base constructors. 

However, in all versions until now (0.4.14) this does not yield a compiler error but also does not create an output binary. I suggest to raise a compiler error here.

**Comment by axic** [comment]
This has been fixed in #2698.
