### ISSUE TITLE
raise an error when a statement can never have side-effects

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#2707]
When a statement contains
* no calls on accounts
* no assignments
* no function calls
* no event logging
* no variable declaration, and
* no `new` expression
the statement does not do anything and can be removed, so the compiler should raise an error.

This prevents things like
* `1;`
* `variable == 3;`

**Comment by axic** [comment]
A good start to this feature could be detecting empty function and event calls, which aren't even assigned to a variable. That should be possible to implement manually. It would raise a warning on:
- `myFunction;`
- `MyEvent;`
- `address(1).call.value(1234);`

**Comment by axic** [comment]
@ekpyron I think you have worked on unreachable code and code without effect detection. Can you update this issue where we stand and what is left to be supported?
