### ISSUE TITLE
Tuples without commas should throw a syntax error

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2713]
The current implementation accepts this code as valid:

```
contract test {
    function() {
      (2 2 2);
    }
}
```

This becomes really confusing if you accidentally use a C-like cast syntax (I wrote a parser, I should know better 🙄 ):

```
contract A {
    function foo() {}
}

contract B {
    address addr;
    
    function() {
        ((A) addr).foo();
    }
}
```

solc output:

```
browser/dowhile.sol:9:9: TypeError: Member "foo" not found or not visible after argument-dependent lookup in tuple(type(contract A),address)
        ((A) addr).foo();
        ^------------^
```

**Comment by axic** [comment]
Comments in the parser even say it is not a "real tuple":
```
                 // Tuple/parenthesized expression or inline array/bracketed expression.
                // Special cases: ()/[] is empty tuple/array type, (x) is not a real tuple,
                // (x,) is one-dimensional tuple, elements in arrays cannot be left out, only in tuples.
```

The grammar however allows it:
```
TupleExpression = '(' ( Expression ( ',' Expression )*  )? ')'
                | '[' ( Expression ( ',' Expression )*  )? ']'
```

I guess the easiest would be adding a syntax checker case for a single member tuple.

**Comment by federicobond** [comment]
The problem is not with the `(A)` but with the `(X Y)` construct. The parser is recognizing a two-element tuple of type `tuple(type(contract A),address)` as described in the output message.

**Comment by federicobond** [comment]
Testing a fix right now.

**Comment by axic** [comment]
Ah right, though as a separate issue don't think a tuple with a single member is a tuple (and should be allowed).

**Comment by chriseth** [comment]
A parenthesized expression is considered as a single-element tuple of that expression which is identical (apart from the syntax) to just the expression. If a tuple contains multiple elements, which are not separated by commas, this should of course be an error.
