### ISSUE TITLE
Automatically generated getter for struct does not return fixed size array field

### ISSUE THREAD

**Issue by yondonfu** [ethereum/solidity#2723]
In the source code below, the automatically generated getter for `foos` does not return the fixed size array field `uint256[3] c` when invoking `foos[0]`. It seems like the automatically generated getter for `foos` should replicate the behavior of `customGetter` (which properly returns `uint256[3] c`), however at the moment it does not.

Source Code:

```
pragma solidity ^0.4.13;

contract Test {
    struct Foo {
        uint256 a;
        uint256 b;
        uint256[3] c;
    }
    
    mapping (uint256 => Foo) public foos;
    
    function Test() {
        foos[0].a = 0;
        foos[0].b = 2;
        foos[0].c[0] = 1;
        foos[0].c[1] = 2;
        foos[0].c[2] = 3;
    }
    
    function customGetter(uint256 _arg1) public returns (uint256 a, uint256 b, uint256[3] c) {
        a = foos[_arg1].a;
        b = foos[_arg1].b;
        c = foos[_arg1].c;
    }
}
```

Solidity Version: 0.4.13
Platform: https://ethereum.github.io/browser-solidity/

**Comment by chriseth** [comment]
Arrays are removed from structs in getters, because the idea is that full arrays are never returned by the getter, only individual elements. This is also true for statically-sized arrays because there is no obvious "max size" where you could draw the line.

**Comment by yondonfu** [comment]
Ah got it. I find it a little strange that getters for structs that contain arrays omit the arrays when returning the values of the struct, while the compiler will throw an error if you try to generate a getter (by declaring the state variable as `public`) for structs that contain structs. I would think the behavior for these two cases would be the same - either the compiler throws an error for both cases or the getter omits the array/struct when returning the values of the struct.
