### ISSUE TITLE
can contract call itself and produced txn

### ISSUE THREAD

**Issue by satyamakgec** [ethereum/solidity#2736]
Suppose if i deploy the smart contract on the ethereum blockchain having a functionality to pay some tokens at particular timestamp. Then on which node's evm that smart contract get executed how it get decided ? and my node is not any more connected to the network at the same time . Is this node selected by network randomly or their is any other algorithm or paradigm exists for this process.

Thanks

**Comment by axic** [comment]
Please ask this on https://ethereum.stackexchange.com/.
