### ISSUE TITLE
Unable to build and install Solidity in Ubuntu

### ISSUE THREAD

**Issue by varadarajana** [ethereum/solidity#2737]
I tried to compile Solidity in Ubuntu 16.04.2. I have installed the dependencies.
boost - version 1.61
[ 63%] Building CXX object liblll/CMakeFiles/lll.dir/Parser.cpp.o
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /usr/local/include/boost/spirit/home/qi/stream.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi.hpp:30,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from /home/varadaradarajan/projects/blockchain/go-ethereum/src/github.com/solidity/liblll/Parser.cpp:30:
/usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
                                                                               ^
In file included from /usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:21:0,
                 from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /usr/local/include/boost/spirit/home/qi/stream.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi.hpp:30,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from /home/varadaradarajan/projects/blockchain/go-ethereum/src/github.com/solidity/liblll/Parser.cpp:30:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /usr/local/include/boost/spirit/home/qi/stream.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi.hpp:30,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from /home/varadaradarajan/projects/blockchain/go-ethereum/src/github.com/solidity/liblll/Parser.cpp:30:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
liblll/CMakeFiles/lll.dir/build.make:134: recipe for target 'liblll/CMakeFiles/lll.dir/Parser.cpp.o' failed
make[2]: *** [liblll/CMakeFiles/lll.dir/Parser.cpp.o] Error 4
CMakeFiles/Makefile2:433: recipe for target 'liblll/CMakeFiles/lll.dir/all' failed

**Comment by axic** [comment]
This seems to be a gcc compiler bug:
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See file:///usr/share/doc/gcc-5/README.Bugs for instructions.

**Comment by chriseth** [comment]
Usually this is due to out-of-memory on the compiling machine. Are you running this inside a virtual machine?

**Comment by varadarajana** [comment]
I think we can close this issue. This is due to running on a VM where disk space was running low and memory was also running at 100%. I cleaned it up and now got it built. Thank you @chriseth

**Comment by varadarajana** [comment]
As mentioned earlier compiling solidity was more an issue with VM I was using. This is working fine now.
