### ISSUE TITLE
Metadata CBOR to contain compiler version

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2741]
The idea is that it can be figured out easily if a contract uses a broken compiler version and therefore should not be trusted.

One could argue against this though that contracts which don't have their metadata JSON uploaded to Swarm should not be trusted and once it is uploaded the version can be verified within.

Note: libraries already include a version byte (though not as part of the metadata). We could consider replacing that version byte with one in the metadata CBOR or use the same compact form in the metadata CBOR.

**Comment by axic** [comment]
Apparently we do not put any mark in the CBOR if it was compiled with a pre-release version. I think that should be done either by including the version with a pre-release tag or adding another bool for `prerelease` (similar to experimental).

**Comment by axic** [comment]
I still think both of these make sense: including the compiler version and the fact it is a prerelease. At least currently we have experimental mode flagged in it.

I propose to include the new field `solc` (or `version`) corresponding to proper version. It could be argued that it is quite long in some cases, we could cut it down to not contain the host and compiler markings, just the version (+ prerelease and hash if it is not a release).

**Comment by chriseth** [comment]
Yes, we should not include the host and compiler because that would not make builds reproducible across platforms. The compiler selection dropdown is certainly annoying :)

**Comment by axic** [comment]
Actually we have that specific version already included into the metadata JSON, we can include the very same in the CBOR part.

**Comment by axic** [comment]
Proposed CBOR key `solc` and value `VersionStringStrict` (the same as in the metadata JSON).

Need to update: tests, Remix, Etherscan.

**Comment by chriseth** [comment]
Is there an easy compression that can be applied to the version string? We used to store the version in library code in binary, for example. Also, perhaps something like `solVer` as key?

**Comment by spalladino** [comment]
> The idea is that it can be figured out easily if a contract uses a broken compiler version and therefore should not be trusted.

Should the field also include whether the optimiser was used, in case a bug is found only in the optimiser of a particular compiler? Or can this information be retrieved easily from other part of the binary?

**Comment by axic** [comment]
Good idea. It cannot be retrieved from anywhere, but the metadata JSON.

**Comment by axic** [comment]
Some proposal from todays meeting:
- use the compact (32bit) version encoding and include flags in it
- use the compact encoding, but include flags in CBOR (`prerelease`, `optimiser`)
