### ISSUE TITLE
left shift operation works with only number literals, or only variables, but not mixed

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#2756]
Seems that it will fail when you mix literals and variables, which makes for some un-intuitive results.

Solidity: `0.4.15+commit.bbb8e64f.Emscripten.clang`

```
pragma solidity ^0.4.0;

contract C {
    
    function get() constant returns (uint, uint) {
        uint n = 255;
        return (1 << 255, 1 << n);
    }
    
    function get2() constant returns (uint, uint) {
        uint n = 255;
        uint m = 1;
        return (1 << 255, m << n);
    }
    
    function get3() constant returns (uint, uint) {
        uint8 n = 255;
        return (1 << 255, 1 << n);
    }
    
    function get4() constant returns (uint, uint) {
        int n = 255;
        return (1 << 255, 1 << n);
    }
    
    function get5() constant returns (uint, uint) {
        uint n = 255;
        return (0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff >> 255, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff >> n);
    }
    
    function get6() constant returns (uint, uint) {
        uint n = 255;
        uint val = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
        return (val >> 255, val >> n);
    }
    
    
}
```

In the contract, the second output of `get` is 0, but for `get2` it is not.

The integer type of the input doesn't seem to matter (`get3` and `get4`).

Right shift does not seem to be affected (`get5` and `get6`).

**Comment by chriseth** [comment]
This is a peculiarity in the type system. If you write `1 << n` (for `n` being `uint`) what is the type of `1` and what is the type of `1 << n`?

I actually thought we had a warning there, but it seems we only implemented that for `**`.

**Comment by androlo** [comment]
`1` is reported as being of type `int_const`, and is for all intents and purposes a `uint8`, which is also the type of `1 << n` - who's type is derived from the shifted value. I know that because shifting up to `1 << n=7` worked, but not for `n=8` or more. Guess that's why right shifting works - the shifted value is never larger then the result of the shift.

It is weird that using a literal, (1 << 255), works though, since neither of those numbers are larger then 8 bits. How about automatically making the shifted value a max size `uint/int` (depending on the number type), regardless of the type of the second param (ie number of shifts)? It feels like the type of the second param should not have an impact on the resulting type.

**Comment by chriseth** [comment]
The type of the second param does not have an impact on the resulting type. The rule that is applied here is that as soon as an integer constant is converted to an actual type, it assumes the smallest type that can fit its value (where unsigned types are considered smaller than signed types).

**Comment by androlo** [comment]
oh, right. so literals work because you get a `int_const X` (essentially another literal) from the shift, rather then a number of type int/uintX. I get it now.

**Comment by androlo** [comment]
```
Return argument type int_const 57896044618658097711785492504343953926634992332820282019728792003956564819968 

return 1 << 255;
```
