### ISSUE TITLE
Add a warning if return variable is not touched at all in a function.

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#276]
This should produce a compiler error.  It seems like a common problem for people coming from languages that do implicit returns of last evaluated values:

```
function someFunction(address _someaddress) returns (bool) {
   owner = _someaddress;
}
```

**Comment by chriseth** [comment]
Note that there are legitimate use-cases for the following code:
```
function f(uint x) returns (bool error) {
  if (x > 7) return true;
  do_something();
}
```

I guess it is fine to add a warning if none of the return variables are assigned and there is no return statement that includes a value.

Other cases might be debatable. In any case, all of them can be silenced.

**Comment by axic** [comment]
Maybe it makes sense making this part of the static analyzer?

**Comment by VoR0220** [comment]
@chriseth at the very least in that example, `do_something` should be in the return statement, also, the return bool should not be named, as error should be set somewhere in that statement. I think small changes like this could really help produce safer code.

**Comment by chriseth** [comment]
Closing this since I don't see how it can be implemented without giving too many false positives.
