### ISSUE TITLE
Impossible to Install Ethereum on Windows 10

### ISSUE THREAD

**Issue by SEBBISUBBU** [ethereum/solidity#2766]
Hi, I have followed the installation instructions from:  http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html, and I have installed git, cmake and visual studio, but when I execute the command "scripts/install_deps.sh" I receive this error:
#################################
"GIUSEPPE@xxxx-xxxx MINGW64 ~/cpp-ethereum (develop)
$ scripts/install_deps.sh
ERROR - Unsupported or unidentified operating system.
See http://cpp-ethereum.org/building-from-source/ for manual instructions.
If you would like to get your operating system working, that would be fantastic.
Drop us a message at https://gitter.im/ethereum/cpp-ethereum-development."
##################################################
How can I solve this issue? 

Thank you!

**Comment by axic** [comment]
This is the wrong repo. You are looking for https://github.com/ethereum/cpp-ethereum.

**Comment by SEBBISUBBU** [comment]
Sorry, But before resolving the dependencies I had executed this code: $ git clone https://github.com/ethereum/cpp-ethereum
and after that I tryed to resolve the dependencies.. receiving the error message above.. So this issue it's not closed  from my point of view. Thanks!

**Comment by SEBBISUBBU** [comment]
$ case $(uname -s) in Darwin)     case $(sw_vers -productVersion | awk -F . '{print $1"."$2}') in         10.9)             echo "Installing cpp-ethereum dependencies on OS X 10.9 Mavericks.";             ;;         10.10)             echo "Installing cpp-ethereum dependencies on OS X 10.10 Yosemite.";             ;;         10.11)             echo "Installing cpp-ethereum dependencies on OS X 10.11 El Capitan.";             ;;         10.12)             echo "Installing cpp-ethereum dependencies on macOS 10.12 Sierra.";             echo "";             echo "NOTE - You are in unknown territory with this preview OS.";             echo "Even Homebrew doesn't have official support yet, and there are";             echo "known issues (see https://github.com/ethereum/webthree-umbrella/issues/614).";             echo "If you would like to partner with us to work through these issues, that";             echo "would be fantastic.  Please just comment on that issue.  Thanks!";             ;;         *)             echo "Unsupported macOS version.";             echo "We only support Mavericks, Yosemite and El Capitan, with work-in-progress on Sierra.";             exit 1;             ;;     esac;      if [ "$TRAVIS" ]; then         TRAVIS_PACKAGES="ccache";     fi;      brew -v > /dev/null 2>&1 || { echo >&2 "ERROR - cpp-ethereum requires a Homebrew install.  See http://brew.sh."; exit 1; };      brew install         leveldb         libmicrohttpd         $TRAVIS_PACKAGES;      ;; FreeBSD);     echo "Installing cpp-ethereum dependencies on FreeBSD.";     echo "ERROR - 'install_deps.sh' doesn't have FreeBSD support yet.";     echo "Please let us know if you see this error message, and we can work out what is missing.";     echo "At https://gitter.im/ethereum/cpp-ethereum-development.";     exit 1;     ;; Linux);      if [ $(id -u) != 0 ]; then         SUDO="sudo";     fi;      if [ -f "/etc/arch-release" ]; then         echo "Installing cpp-ethereum dependencies on Arch Linux.";          $SUDO pacman -Sy --noconfirm             autoconf             automake             gcc             libtool             leveldb             libmicrohttpd;      elif [ -f "/etc/os-release" ]; then         DISTRO_NAME=$(. /etc/os-release; echo $NAME);         case $DISTRO_NAME in         Debian*)             echo "Installing cpp-ethereum dependencies on Debian Linux.";              $SUDO apt-get -q update;             $SUDO apt-get -qy install                 build-essential                 libgmp-dev                 libleveldb-dev                 libmicrohttpd-dev;             ;;         Fedora)             echo "Installing cpp-ethereum dependencies on Fedora Linux.";             $SUDO dnf -qy install                 gcc-c++                 leveldb-devel                 libmicrohttpd-devel                 gmp-devel;             ;;         Ubuntu|"Linux Mint")             echo "Installing cpp-ethereum dependencies on Ubuntu.";             $SUDO apt-get -q update;             $SUDO apt-get install -qy --no-install-recommends --allow-unauthenticated                 build-essential                 libgmp-dev                 libleveldb-dev                 libmicrohttpd-dev                 $TRAVIS_PACKAGES;             ;;         CentOS*)             echo "Installing cpp-ethereum dependencies on CentOS."             $SUDO yum -y -q install epel-release;             $SUDO yum -y -q install                 make                 gcc-c++                 leveldb-devel                 libmicrohttpd-devel                 gmp-devel;             ;;         *)             echo "Unsupported Linux distribution: $DISTRO_NAME.";             exit 1;             ;;         esac;      elif [ -f "/etc/alpine-release" ]; then         echo "Installing cpp-ethereum dependencies on Alpine Linux.";         $SUDO apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/             g++             make             libmicrohttpd-dev             leveldb-dev;      else         case $(lsb_release -is) in         openSUSE*)             echo "Installing cpp-ethereum dependencies on openSUSE.";             echo "ERROR - 'install_deps.sh' doesn't have openSUSE support yet.";             echo "See http://cpp-ethereum.org/building-from-source/linux.html for manual instructions.";             echo "If you would like to get 'install_deps.sh' working for openSUSE, that would be fantastic.";             echo "See https://github.com/ethereum/webthree-umbrella/issues/552.";             exit 1;             ;;         *)             echo "ERROR - Unsupported or unidentified Linux distro.";             echo "See http://cpp-ethereum.org/building-from-source/linux.html for manual instructions.";             echo "If you would like to get your distro working, that would be fantastic.";             echo "Drop us a message at https://gitter.im/ethereum/cpp-ethereum-development.";             exit 1;             ;;         esac;     fi;     ;; *)     echo "ERROR - Unsupported or unidentified operating system.";     echo "See http://cpp-ethereum.org/building-from-source/ for manual instructions.";     echo "If you would like to get your operating system working, that would be fantastic.";     echo "Drop us a message at https://gitter.im/ethereum/cpp-ethereum-development.";     ;; esac

**Comment by axic** [comment]
You are still reporting this on **https://github.com/ethereum/solidity**. Please report it on the correct repository.

**Comment by SEBBISUBBU** [comment]
$ git clone --recursive https://github.com/ethereum/cpp-ethereum
fatal: could not create work tree dir 'cpp-ethereum': Permission denied

**Comment by SEBBISUBBU** [comment]
ok.. Thanks for your help.
