### ISSUE TITLE
Improve usability for error messages

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2768]
Over the past few years, there have been significant advances in making compiler error messages understandable and usable by humans. The Elm team has done [some excellent work](http://elm-lang.org/blog/compiler-errors-for-humans) pointing the way forward, and both the [Rust](https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html) and [Scala](http://scala-lang.org/blog/2016/10/14/dotty-errors.html) communities have picked up from that.

It's absolutely essential for smart contract developers to improve their understanding of the language they work with and to be able to focus their mental energies on the actual logic of their contracts. I think we ought to give more thought to the way error messages are presented in Solidity.

This issue is meant to track the work required to improve the reporting of Solidity errors and to discuss different approaches.

### Recommended reading

 * http://elm-lang.org/blog/compiler-errors-for-humans
 * https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html
 * http://scala-lang.org/blog/2016/10/14/dotty-errors.html

### Roadmap

*(to be discussed)*

 * Collect code samples that trigger different error messages and see if we can improve them
 * Assign a unique number to each Solidity error message and warning
 * Improve formatting of basic messages (colors, layout, etc.)
 * Add methods to show additional information (notes, explanations, etc) and take advantage of them where appropriate
 * Discuss additional ways in which we can improve reporting

### Questions

 * How do we maintain compatibility with the standard JSON interface?
 * Can we move away from Boost's errinfo and have a richer API for presenting errors?
 * Should we add a small library like termcolors or rang for handling colored output? termcolors looks battle-tested and BSD licensed, so GPL-compatible. 

**Update 08/23:** added questions about errinfo API and colored output.

**Comment by axic** [comment]
I was thinking about this a while back and I think:
- messages should be split into error message and optional details (which can be lengthy; could be switched on/off by the IDE or displayed on hover; etc.)
- worth considering introducing unique error codes, because that would give users a way to search for an error code even if the message has changed

**Comment by federicobond** [comment]
Good! I like the idea of specifying error codes too. What do you think about providing a `--explain` option that outputs lengthy descriptions for each error (see linked articles).

**Comment by axic** [comment]
Some status report, today:
- Unique error codes are assigned (#3202)
- The new error formatter is enabled by default (in standard json too) since 0.8.0 -- this has nicer layout and colours (but colours are not turned on in standard json: #11507)
- Split messages into core and optional details -- tracked in #10534

The other suggestions are not yet supported.

**Comment by MrChico** [comment]
@axic I don't see any colors in the standard json error output. It has a formatted error message, but not any color :(

**Comment by axic** [comment]
The CLI is colourised, standard json is not, as we were afraid that could cause issues by users of it. We could either switch it to colour only, have an input flag for it, or have a new field for coloured output?

**Comment by MrChico** [comment]
Yeah, any option to activate it would be appreciated! An option in the input json `color` could match the CLI behaviour nicely (although the default may be different)

**Comment by axic** [comment]
Created an issue to track this: #11507.
