### ISSUE TITLE
Coverity Scan integration in CI

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2774]
There's a repo on Coverity for Solidity: https://scan.coverity.com/projects/ethereum-solidity?tab=overview

The CI should submit a new Coverity report when the nightly is built. In order to that a report must be built using the tools here (https://scan.coverity.com/download). It seems the tool is quite large (~600 Mb), so preferable a docker image should be used instead (I'm sure someone made one already).

Travis integration guide: https://scan.coverity.com/travis_ci

**Comment by axic** [comment]
Though many of the issues found by Coverity were found by cppcheck too (at least on that particular build).

**Comment by chfast** [comment]
You can also start with clang static analyzer.

**Comment by axic** [comment]
I've been using it on other projects, but either it cannot find anything or it cannot properly hijack cmake on Mac, because the result I get is always "no issues found".

**Comment by bshastry** [comment]
> I've been using it on other projects, but either it cannot find anything or it cannot properly hijack cmake on Mac, because the result I get is always "no issues found".

I can confirm this on a linux build. However, when I run Clang SA with a set of non-default checkers enabled (marked `alpha`), the scan throws up bug reports. So far, most of these bug reports seem to be false positives. It is on expected lines because `alpha` checkers are just that.

The good news is that there are no warnings with production checkers :+1:

**Comment by axic** [comment]
How do you run it? Coverity website seems to be down for weeks.

**Comment by bshastry** [comment]
> How do you run it? Coverity website seems to be down for weeks.

I ran the clang static analyzer, not Coverity. You are right, the Coverity scan service is down atm

**Comment by axic** [comment]
> You can also start with clang static analyzer.

In the past Coverity was able to find different issues, but that is experience from over 4 years ago. Since the coverity site seems unreliable, I don't think we'll use it anytime soon.
