### ISSUE TITLE
Doc search results routing to another non-public subdomain

### ISSUE THREAD

**Issue by eyezick** [ethereum/solidity#2777]
Searching ```revert``` for instance, the first linked result is: http://solidity-482solution.readthedocs.io/en/develop/control-structures.html?highlight=revert

The subdomain is prepended with `-482solution`

**Comment by axic** [comment]
Thanks this seems to be down to readthedocs. We've filed an issue yesterday at https://github.com/rtfd/readthedocs.org/issues/3061.
