### ISSUE TITLE
Easy Peazy: State Mutability should be more readable in ABI

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#2778]
Can we make the ABI field for "statemutability" (current) to something like "state_mutability" or "state-mutability" or even some mixedCase? Makes the whole thing read easier.

**Comment by axic** [comment]
I actually like it the way it is, but not too much attached to it. In order to be consistent, I’d go for `stateMutability`. Definitely against `-` and `_` looks a bit ugly to me (in JSON at least).

We should also change the AST JSON appropriately.

**Comment by chriseth** [comment]
Fine for me!
