### ISSUE TITLE
Absolute values nonintuive/broken.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/solidity#278]
I would expect

```
    function abstest() returns (int) {
        return (+int(-14));
    }
```

to return 14. It returns -14.

Am I completely misunderstanding unary +, or is this a bug?

**Comment by chriseth** [comment]
This is the way it works with most programming languages. Unary plus has no effect apart from implicit type conversions - try that in JavaScript.

**Comment by PaulRBerg** [comment]
@chriseth is there a [Math.Abs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs) function in solidity?

**Comment by chriseth** [comment]
No, this is not available in Solidity. You have to use `x >= 0 ? x : -x`.
