### ISSUE TITLE
Add `pop()` method to storage array types that throws on empty arrays

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2780]
This method should be implemented analogously to `push`.

The relevant functions are `ArrayType::nativeMembers` in `Types.cpp` and `ExpressionCompiler::visit(MemberAccess const& _memberAccess)` (search for `"push"`) in ExpressionCompiler.cpp. The actual implementattion of the pop operation requires extending the `Kind`-enum in the class `FunctionType` (Types.h). Check how it is done for `ArrayPush` and just do it accordingly.

If the array is empty, the function should cause an assertion failure (`appendConditionalInvalid`).

**Comment by kasjan-s** [comment]
Hey, is this still up-for-grabs (you've assigned yourself, so I'm not sure) ? If so, then I could take care of it.

**Comment by chriseth** [comment]
@kasjan-s I'm sorry, yes this is still up for grabs! Please don't hesitate to ask any questions, either here or in https://gitter.im/ethereum/solidity-dev

**Comment by kasjan-s** [comment]
Very well, I'll do it! I'll be sure to ask any questions I come up with on gitter. 

But for starters just two quick questions:
1. I assume the idea is to have pop() return the new length of the array, just like push()?
2. Part of the task is to update the documentation as well, right?

**Comment by chriseth** [comment]
For now, I would not make pop return anything. There are some candidates but they all have their drawbacks.

**Comment by kasjan-s** [comment]
There's started work in above PR, but I'm not going to have time to work on it again untill 2nd half of November. Sorry.

If anyone's interested, feel free to pick this up.

**Comment by chriseth** [comment]
@kasjan-s do you think you can take this up again?
