### ISSUE TITLE
fails to build in a clean ubuntu xenial

### ISSUE THREAD

**Issue by come-maiz** [ethereum/solidity#2789]
Hello!

With the latest addition of z3, I can no longer build solidity. I'm running this in a clean ubuntu xenial lxc:

    $ git clone https://github.com/ethereum/solidity
    $ cd solidity
    $ git submodule update --init --recursive
    $ ./scripts/install_deps.sh  
    $ mkdir build
    $ cd build
    $ cmake ..

And it fails with:
```
CMake Error at cmake/FindZ3.cmake:3 (include):
  include could not find load file:

    /root/solidity/cmake/FindPackageHandleStandardArgs.cmake
Call Stack (most recent call first):
  libsolidity/CMakeLists.txt:5 (find_package)


Z3 SMT solver FOUND.
-- Configuring incomplete, errors occurred!
```

I don't really understand cmake, but it seems we are either missing that `FindPackageHandleStandardArgs.cmake` file in the repo, or we should just use the one provided by cmake. This diff seems to solve it:

```
diff --git a/cmake/FindZ3.cmake b/cmake/FindZ3.cmake
index 8f3f9ee..9364c00 100644
--- a/cmake/FindZ3.cmake
+++ b/cmake/FindZ3.cmake
@@ -1,6 +1,6 @@
 find_path(Z3_INCLUDE_DIR z3++.h)
 find_library(Z3_LIBRARY NAMES z3 )
-include(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
+include(FindPackageHandleStandardArgs)
 FIND_PACKAGE_HANDLE_STANDARD_ARGS(Z3 DEFAULT_MSG Z3_LIBRARY Z3_INCLUDE_DIR)
 
 if(Z3_FOUND)
```

I'm not proposing a PR with it because I'm not totally sure that's the right fix.

**Comment by axic** [comment]
Fixed by #2791.
