### ISSUE TITLE
Review old exceptions in Cmake

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2816]
1. `-fpermissive` (see https://github.com/ethereum/solidity/blob/develop/cmake/EthCompilerSettings.cmake#L57-L76)
2. `-Wno-unused-function -Wno-dangling-else` (see https://github.com/ethereum/solidity/blob/develop/cmake/EthCompilerSettings.cmake#L103-L112)

**Comment by axic** [comment]
@chfast any comments on this?

**Comment by chfast** [comment]
I believe we don't use any of these in cpp-ethereum. Simply remove all of that and run CI jobs. You should have clang build at least on Linux.
