### ISSUE TITLE
`staticcall()` always throws an error inside an assembly block

### ISSUE THREAD

**Issue by GNSPS** [ethereum/solidity#2824]
The use of the `staticcall()` function inside an assembly block always throws an error:

`Unbalanced stack at the end of a block: 1 surplus item(s).`

This happens with every major release version of the compiler with the optimization both turned on or off, indifferent.

**Comment by GNSPS** [comment]
Looking at the tests for this I tried:

`pop(staticcall(g, a, in, insize, out, outsize))`

and it did work.

**Comment by GNSPS** [comment]
Wooops. Just realized my own stupidity!

Closing now. 😂

**Comment by sivachaitanya** [comment]
what did you do ? please elaborate on what you have done

**Comment by GNSPS** [comment]
Basically I wasn't `pop()`ing the elements that get pushed onto the stack by the call
