### ISSUE TITLE
loading solc compiler from Nodejs throws error

### ISSUE THREAD

**Issue by varadarajana** [ethereum/solidity#2827]
I am loading solc from NodeJS. This solc was seperately built from source. Here is the error i get

> solc = require('/path/to/solc')
/path/to/solc:1
(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^

SyntaxError: Invalid or unexpected token

Why am i getting this? I was able to use solc along with geth.

**Comment by axic** [comment]
Apparently you are trying to load a Linux binary in Node.js. That will not work. I suggest to checkout https://github.com/ethereum/solc-js.
