### ISSUE TITLE
Upgrade to jsoncpp 1.8.2

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2829]
The changes since 1.7.7:
- Require cmake>=3.1
- Minor bug fixes and optimizations
- Some C++ "move" operators.
- Fix uninitialized value detected by valgrind.
- Other minor improvements.

**Comment by axic** [comment]
The uninitialized is part of the parsing: https://github.com/open-source-parsers/jsoncpp/commit/90061941390595dbdb71f5f1eb9ccfcdb28d168d

Move: https://github.com/open-source-parsers/jsoncpp/commit/8996c377aad3a333a9bada1cfe7d5924e71a3269

**Comment by chriseth** [comment]
sounds good!

**Comment by axic** [comment]
`StyledWriter` and `FastWriter` are deprecated and there's a new `StreamWriterBuilder` class to be used instead.

Likewise, `Reader` is deprecated and `CharReader` is supplied (which has quite a different API).

**Comment by changwu-tw** [comment]
Would be great to upgrade to newer version of jsoncpp, or the error occurs when installing via homebrew. https://github.com/ethereum/homebrew-ethereum/issues/128

**Comment by axic** [comment]
@changwu-tw the compilation issue is tracked in #2956. The problem is it should always use the built in version, but for some reason it uses the external one if present.
