### ISSUE TITLE
Unused variable: recommend to comment out at least for parameters

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2830]
People that use functions which intentionally do not use a parameter have a hard time to find the correct way to silence the warning (the correct way is to either remove the parameter name or comment it out, and keep just the type of the parameter). We should explain how to do it in the warning text (perhaps only if the variable is a function parameter).

Now: "Warning: Unused variable"

Better: "Warning: Unused variable. Remove or comment out the variable name to silence this warning"

**Comment by ssuman** [comment]
I would like to work on this.

**Comment by chriseth** [comment]
@ssuman wonderful! The relevant line is in StaticAnalyzer.cpp line 72. I think the check for parameter or return parameter would be VariableDeclaration::isCallableParameter. If you have further questions, please ask in https://gitter.im/ethereum/solidity-dev
