### ISSUE TITLE
Crash in LLL LIT

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2832]
```
{ (lit 'a aaaa) }
```

```
{ (lit 'aa 3 "aaa") }
```

```
{ (lit 3 "aaa") }
```

**Comment by axic** [comment]
This is due that the error is raised via `error<InvalidLiteral>();`, i.e. no text reason included. There are 9 other instances of such errors, all of them will crash.

The actual is crash is due to `what()` returning `nullptr` in https://github.com/ethereum/solidity/blob/develop/libdevcore/Exceptions.cpp#L25-L31, however according to boost that should be valid: http://www.boost.org/doc/libs/1_63_0/libs/exception/doc/diagnostic_information_what.html

Changing that to return a literal, `"???"` in my case, "fixes" all these crashes.

@chriseth @chfast any ideas?

**Comment by axic** [comment]
Before #2567 this used `std::exception::what()` as a fallback:
https://github.com/ethereum/solidity/commit/09e821619e20943af7bbd61ad10fb5ae40d2558c#diff-3142d546f3e8846b9670f0bba513fc82L42

**Comment by chfast** [comment]
Let's follow the C++ standard on this: http://en.cppreference.com/w/cpp/error/exception/what
It requires the pointer to be valid.

I would call `std::exception::what()` as the fallback.
