### ISSUE TITLE
Same event declared as anonymous and non-anonymous

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2839]
This compiles without issues:
```
event E();
event E() anonymous;
```

In the assembly it seems the declaration order decides which one is taken.

**Comment by chejazi** [comment]
Additionally, it seems odd that the following compiles without any warning.
```
contract DuplicateEventContract {
    event AnEvent(
        uint foo
    );
    
    // Duplicate
    event AnEvent(
        uint foo
    );
    
    // Indexed
    event AnEvent(
        uint indexed foo
    );

    // Different args
    event AnEvent(
        uint bar,
        string baz
    );
}
```

**Comment by axic** [comment]
The last one should work due to overloading, but the other two issues (duplicate and that `indexed` is not considering at overload resolution) is a bug.
