### ISSUE TITLE
Unknown solidity bug

### ISSUE THREAD

**Issue by iFA88** [ethereum/solidity#2845]
Greetings everyone, I have spend a day for _why my code is not working_ and finally have found the problem.

### My code:
```javascript
pragma solidity ^0.4.15;
contract provider {
    uint8 public rentRate = 20;
    address rewardLibAddress;
    /* Constructor */
    function provider(address rewardLibAddr) {
        rewardLibAddress = rewardLibAddr;
        require( providerRewardLib(rewardLibAddress).ownSign() == sha3("providerRewardLib") );
    }
    /* Constants */
    function checkReward(uint256 providerUID, uint256 roundLimit) public constant returns (uint256 senderReward, uint256 adminReward, uint256 ownerReward, uint256 round) {
        //bytes4 sig = bytes4(sha3("checkReward(uint256,uint256)"));
        assembly {
            let m := mload(0x80)
            mstore(m, 0xbfd8222a00000000000000000000000000000000000000000000000000000000)
            mstore(add(m, 0x04), providerUID)
            mstore(add(m, 0x24), roundLimit)
            let success := delegatecall(gas, sload(rewardLibAddress_slot), m, 0x44, m, 0x80)
            switch success case 0 {
                revert(0,0)
            } default {
                return(m, 0x80)
            }
        }
    }
}
contract providerRewardLib {
    bytes32 public ownSign = sha3("providerRewardLib");
    /* Constants */
    function checkReward(uint256 providerUID, uint256 roundLimit) public constant returns (uint256 senderReward, uint256 adminReward, uint256 ownerReward, uint256 round) {
        return (1,2,3,4);
    }
}
```
### The issue:
On `provider.checkReward(1,1)` call I got the `calldata` as return back like:
```
0xbfd8222a00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"
```

### Solution
If I change the third line to:
```javascript
uint256 public rentRate = 20;
```
Then works everything as excepted. Return:
```
0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004
```
### Environment 
Latest Windows 10
Firefox 55.0.3 64bit
https://ethereum.github.io/browser-solidity
I have the same issue with compiler from `0.4.15+commit.bbb8e64f` to `0.4.17-nightly.2017.8.28+commit.d15cde2a`, with enabled or disabled optimization.

**Comment by chriseth** [comment]
For types that are smaller than 32 bytes (like address) you have to take both `_slot` and `_offset` into account: https://solidity.readthedocs.io/en/develop/miscellaneous.html#layout-of-state-variables-in-storage

You can avoid that by packing the address into a struct, which will cause the compiler to put it into a slot of its own.

**Comment by iFA88** [comment]
Alright, how can I use both of them?
`rewardLibAddress_slot_offset` ?
Sadly this is not working. I can't find an any documentation how should be that use. ( https://solidity.readthedocs.io/en/develop/search.html?q=_offset&check_keywords=yes&area=default )

**Comment by chriseth** [comment]
Something like `div(sload(rewardLibAddress_slot), exp(2, rewardLibAddress_offset))` could work, but I would strongly advise against that.

**Comment by chriseth** [comment]
Oh and you should also perform a cleanup of the address in case there is something after it in the slot.

**Comment by axic** [comment]
Closing as this is part of the documentation ("Assembly" chapter).
