### ISSUE TITLE
Enforce coding style via clang-format

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2856]

**Comment by chriseth** [comment]
We tried that two years ago, but clang-format did not support
```
x(
  a,
  b
)
```
back then.

**Comment by axic** [comment]
A configuration was added in #7240, now we need to reformat everything and run it on CI :wink:

**Comment by chriseth** [comment]
I really like the closing-bracket-on-same-indentation feature.

**Comment by axic** [comment]
Don't we have this now?

**Comment by chriseth** [comment]
No, still a missing feature in clang-format.
