### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ValeryDubrava** [ethereum/solidity#2859]
Version: d7661dd commit (tag v0.4.16)
OS: Centos 7
CMake: 3.9

I've faced with compilation error:

In file included from /home/valery/solidity/libsolidity/formal/SMTChecker.h:21:0,
                 from /home/valery/solidity/libsolidity/formal/SMTChecker.cpp:18:
/home/valery/solidity/libsolidity/formal/SolverInterface.h:60:2: error: unused parameter '_other' [-Werror=unused-parameter]
  Expression(Expression&& _other) = default;
  ^
/home/valery/solidity/libsolidity/formal/SolverInterface.h: In static member function 'static dev::solidity::smt::Expression dev::solidity::smt::Expression::ite(dev::solidity::smt::Expression, dev::solidity::smt::Expression, dev::solidity::smt::Expression)':
/home/valery/solidity/libsolidity/formal/SolverInterface.h:68:3: note: synthesized method 'dev::solidity::smt::Expression::Expression(dev::solidity::smt::Expression&&)' first required here
   });
   ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from /home/valery/solidity/libsolidity/ast/ASTVisitor.h:27,
                 from /home/valery/solidity/libsolidity/formal/SMTChecker.h:20,
                 from /home/valery/solidity/libsolidity/formal/SMTChecker.cpp:18:
/usr/include/c++/4.8.2/bits/stl_vector.h:364:7: error:   initializing argument 1 of 'std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = dev::solidity::smt::Expression; _Alloc = std::allocator<dev::solidity::smt::Expression>; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<dev::solidity::smt::Expression>]'
       vector(initializer_list<value_type> __l,
       ^
In file included from /home/valery/solidity/libsolidity/formal/SMTChecker.h:21:0,
                 from /home/valery/solidity/libsolidity/formal/SMTChecker.cpp:18:
/home/valery/solidity/libsolidity/formal/SolverInterface.h: At global scope:
/home/valery/solidity/libsolidity/formal/SolverInterface.h:59:2: error: unused parameter '_other' [-Werror=unused-parameter]
  Expression(Expression const& _other) = default;
  ^
/home/valery/solidity/libsolidity/formal/SolverInterface.h: In member function 'dev::solidity::smt::Expression dev::solidity::smt::Expression::operator()(dev::solidity::smt::Expression) const':
/home/valery/solidity/libsolidity/formal/SolverInterface.h:122:29: note: synthesized method 'dev::solidity::smt::Expression::Expression(const dev::solidity::smt::Expression&)' first required here
   return Expression(name, _a);
                             ^
/home/valery/solidity/libsolidity/formal/SolverInterface.h:135:2: error:   initializing argument 2 of 'dev::solidity::smt::Expression::Expression(std::string, dev::solidity::smt::Expression)'
  Expression(std::string _name, Expression _arg):
  ^
cc1plus: all warnings being treated as errors
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/formal/SMTChecker.cpp.o] Error 1
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
make: *** [all] Error 2

**Comment by chriseth** [comment]
Thanks for reporting! Which compiler version are you using?

**Comment by ValeryDubrava** [comment]
➜  build git:(d7661dd) make -v
GNU Make 3.82

gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by chriseth** [comment]
This seems to be a quite old compiler, but I will still create a fix for this warning.

**Comment by ValeryDubrava** [comment]
Great, thanks. I'm realy need to build it under centos. In any case I will try to update compiler, but I think it is not easy task for centos. Could you suggest me which version of the compile is better to use?

**Comment by chriseth** [comment]
I'm using 6.3.0. You might also want to try clang instead of gcc.

**Comment by ValeryDubrava** [comment]
Wow, thanks, your commit have solved this issue for me!
