### ISSUE TITLE
Don't fully compiler/check imports.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#2862]
At the moment, it _appears_ that Solidity is doing a full check/compile of imported contracts.  However, it could save notable time by instead just parsing enough to get the contracts and function signatures which is all that is needed by the importer.

Compilation time on some of my contracts is up to minutes because the import hierarchy is large.  I would really like to get this number down, and one way would be if imported contracts weren't fully compiled and instead were just parsed.

**Comment by chriseth** [comment]
The main reason for this is that there is not yet a way to specify which contract you actually want to have compiled (there is an open issue about that and I think @axic started an implementation). For the normal commandline solc, we could compile just the contracts in the first source file specified, but that won't work for all versions.

What you could do is use interfaces, basically the same workaround C is using with its header files. It's not nice, but at least it will help until we have the proper solution.

**Comment by MicahZoltu** [comment]
That is our current planned workaround, but as anyone who has worked with C knows its quite the PITA to maintain duplicates of every file.

**Comment by axic** [comment]
I don think headers are duplicates, they have a different purpose. Similarly, `interface`s have their own distinct purpose. Though I must admit that I do not know your situation and the codebase you are working on.

**Comment by chriseth** [comment]
I also think this should be solved in collaboration with the package managers - for example truffle seems to call the compiler once for each source file, while a single call for everything should be enough.

@axic perhaps we could implement the output selection to a point where you specify a single file and just want everything from there, since this seems to be the feature required by truffle. More fine-grained control can be added later.

**Comment by MicahZoltu** [comment]
Our (Augur's) build/test pipeline is pretty naive right now.  At the moment it compiles each file separately, rather than compiling the whole project.  This could be improved such that we compile the entire project in one call to solc rather than compiling each independently.  Right now I'm going through the codebase and making everything have a separate Interface file and the compilation times are decreasing by 60-100 fold.

**Comment by axic** [comment]
@chriseth @MicahZoltu Is this issue solved by #8739 ?

**Comment by MicahZoltu** [comment]
I'll defer to @chriseth on that.  I'm not actively working on the aforementioned project anymore so I wouldn't be able to help test.

**Comment by chriseth** [comment]
I would say we can close it.
