### ISSUE TITLE
libsolc and public API

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2864]
I think with the JSON I/O specification we could consider our interface quite stable and could consider making it public (it is already public as an emscripten binary) in terms of a statically linked shared library on Linux similarly to the static build based on Alpine.

For that I'd propose to:
- rename `soljson` / `jsonCompiler` to `libsolc`
- create three public methods: `solcLicense`, `solcVersion`, `solcCompile` (aka. `license`, `version`, `compileStandard` currently)
- retire the obsolete method in the future (`license`, `version`, `compileJSON`, `compileJSONMulti`, `compileJSONCallback` and `compileStandard`) 
- build `libsolc` as a statically linked shared library so that the only symbols it exposes are those three and doesn't import anything
- include `libsolc` in `make install` and the releases

@chriseth @chfast what do you think?

**Comment by chfast** [comment]
Doable. The only toolchain specific part is exporting symbols from a DLL. But I have it done for evmjit.so, not so big deal.

But why libsolc is needed?
And what is relation between solc and libsolc?

**Comment by axic** [comment]
There is no relation between `jsonCompiler` and `solc`, though I think `libsolc` is the most fitting name (even if we don't decide on making official releases of those binaries), because is it is a "**sol**idity **c**ompiler" library.

It would be useful for binding to currently less supported platforms, such as Python, Java and even a much faster node.js integration (though one can argue a webassembly binary should be as fast).

I should make it clear that this issue has two parts:
1) cleanup of the interface (which is the used in the emscripten and hopefully later in the webassembly build)
2) deciding to make it part of the release

**Comment by chfast** [comment]
Are functions solcLicense, solcVersion, solcCompile `export "C"`?

**Comment by axic** [comment]
Yep (they replace the current `license`, `version` and `compileStandard`)

**Comment by chfast** [comment]
For C-like function I would recommend using underscore naming convention: `solc_compile()`, etc.

**Comment by axic** [comment]
Should it be `solc_compile`, `solc_version` and `solc_license` or rather `solidity_compile`, etc ?

**Comment by chfast** [comment]
I vote for `solidity_` prefix.
