### ISSUE TITLE
Add support for interfaces inheriting from other interfaces.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#2866]
```
interface Named {
  function getName() returns (string);
}
interface Colored {
  function getColor() returns (string);
}
interface Fruit is Named, Colored {
  function eat();
}
contract RedApple is Named, Colored {
  event Nomnom();
  function getName() { return "apple"; }
  function getColor() { return "red"; }
  function eat() { Nomnom(); }
}
contract PickyEater {
  function consider(Fruit fruit) {
    if (fruit.getName() == "apple" && fruit.getColor() == "red") { fruit.eat(); }
    else { throw; }
  }
}
```

The above, of course, doesn't actually work because the Fruit interface is invalid (it derives from two other interfaces).  One can make the `Fruit` interface a contract and this will work, but in an application of significant size/abstraction this quickly turns into interfaces being useless as almost everything ends up needing to be a contract except some _very_ low level primitives (like `Ownable`).

An alternative solution may be to support multi-typed parameters like `function consider(Named|Colored fruit)`.

**Comment by Marenz** [comment]
I suppose you meant to derive `RedApple` from `Fruit` ;) but other than that, this is now implemented in `0.6.2` (or 3?)
