### ISSUE TITLE
Incorrect msg.sender

### ISSUE THREAD

**Issue by nosferatu500** [ethereum/solidity#2868]
Hello, I got a problem.
When I use this:

````
address myAddress = msg.sender;

modifier someModifier() {
  if (msg.sender == myAddress) {
  
  }
}
````

I got a **false**. Why? 

PS: version 0.4.15
PPS: sorry for bad english, I'm not native speaker

**Comment by axic** [comment]
Can you post a more complete code please?

Are you by any chance seeing this on a `constant` function or when doing an `eth_call` over RPC?

**Comment by nosferatu500** [comment]
It is not `constant` function.

Look, it very simple function.

```
address myAddress = msg.sender;

modifier someModifier() {
  if (myAddress == msg.sender) {
    _;
  } else {
    revert();
  }
}

function someFunction() someModifier returns(uint256) {
  return 1234;
}
```

And I get `revert()`

But, if I use function instead of modifier, like this:
```
address myAddress = msg.sender;

function someModifier() returns (bool) {
  if (myAddress == msg.sender) {
    return true;
  } else {
    revert();
  }
}

function someFunction() returns(uint256) {
  if (someModifier()) {
   return 1234;
  }
}
```
It is work correct. I get `1234`

I thought that, `msg.sender` can not be used in modifiers, but it's probably strange.

**Comment by nosferatu500** [comment]
I use `truffle compile` and `truffle migrate` to deploy to `testrpc`. There maybe an error in the `truffle`? Incorrect parse and compile maybe? I don't know. why I got it. :)

**Comment by axic** [comment]
@nosferatu500 sorry, is this still a bug? Have you managed to solve it?

**Comment by nosferatu500** [comment]
@axic Hi! I will checking it tomorrow and describe result here.

**Comment by nosferatu500** [comment]
I checked it in Remix. The problem is gone, but I want to make a little more tests in "real life" contract I'll do it tomorrow and send you message about it.

**Comment by axic** [comment]
Thank you!

**Comment by nosferatu500** [comment]
Hi! I make a lot of tests for my contract with old issue. Currently, everything okay. You can close this issue.

**Comment by chriseth** [comment]
Thanks a lot!
