### ISSUE TITLE
Limit number of columns of source snippets in error messages

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2885]
For very long lines, source snippets in error messages are not useful anymore, since the place where the `^` pointer points is not visible anymore if e.g. a terminal breaks the line.

In such a case (e.g. if the line is longer than 150 characters), only a certain context around the error location should be shown. Also, if the error location itself is longer than 150 characters, it should not be shown.

Example:

```
... f(x + 2) ...
      ^---^
```

The relevant source file is SourceReferenceFormatter.cpp

Related: https://github.com/ethereum/solidity/issues/2876

**Comment by vdimic** [comment]
Can I work on this?

**Comment by chriseth** [comment]
Sure! If you need any help, please either ask here or on https://gitter.im/ethereum/solidity

**Comment by chriseth** [comment]
@vdimic did you have any time to work on this? Do you need help?

**Comment by adamsau** [comment]
@chriseth is it possible that i can pick up the task since vdimic is not active? What should be the output of the error outside the context, leading 3 dots and trailing 3 dots as in the example?

Also, if the error location itself is longer than 150 characters, it should not be shown. Does it mean completely no output source snippets? or would it be better to have some kind of indicators to indicate the line is too long to display?

**Comment by vdimic** [comment]
@chriseth I had no time to dedicate to this due to unplanned work commitments. I am fine if @rivenhk wants to take over.

**Comment by chriseth** [comment]
@rivenhk sure, please pick it up! Yes, replace the prefix and the suffix with three dots. If the location itself is longer than 150 characters, perhaps display 15 characters from the start and 15 characters from the end:

````
var x = (1+(1+(1+(+(1+( ... )))))))))))))))
        ^-------------- ... --------------^
````

But perhaps best to create a pull request already after the firs half, then we can comment and help directly on the code.

**Comment by adamsau** [comment]
sure, checking out the contributing guidelines for now.

**Comment by adamsau** [comment]
@chriseth i have created a PR #3092, thanks~
