### ISSUE TITLE
Introduce type annotations in the ABI

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2899]
Currently the `type` in the ABI refers purely to the *encoding type* (which is specific and defined in the ABI).

It could be useful to show a higher level type how the data can be interpreted. For example `structs` and `tuples` can both be encoded as `tuples` (and they do not need a different low level encoding), but their high level interpretation might differ (for one, `structs` will have named components, while `tuples` wont).

Another good example is function types are encoded as `bytes24` but could benefit from a specific interpretation if the application desires.

Propose to extend the ABI with a new field `annotatedType` next to `type`.

**Comment by axic** [comment]
It should also come in handy with `enum`s.

**Comment by juanfranblanco** [comment]
@axic I don't know if my comments of https://github.com/ethereum/solidity/issues/3618 fit better here. As you have thought of the solution already.
