### ISSUE TITLE
Documentation: Add docs on decimals for ERC20 tokens

### ISSUE THREAD

**Issue by iam-peekay** [ethereum/solidity#2906]
There's a lot of confusion among smart contract developers on what exactly the `decimals` means with the ERC20 token standard. It's a foreign concept that is poorly named. We need to add documentation explaining that "decimals" is related to the divisibility of the token, and the number is how divisible the token is.

See relevant discussions on decimals here: 
https://github.com/ethereum/EIPs/issues/223

**Comment by aj07** [comment]
I will take this

**Comment by chriseth** [comment]
@aj07 is ERC20 part of the solidity documentation?

**Comment by aj07** [comment]
no as of now, I will include it in decimal section

**Comment by ChrisChinchilla** [comment]
Going to close this as off-topic. While I agree that `decimals` is poorly explained, it's not really the place of the Solidity docs to explain token standards (at the moment). I may attempt to improve the explanation on the link above.
