### ISSUE TITLE
Enforce address literals to be 20 bytes long in every case

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2907]
Address literals have to have a valid checksum and should be exactly 20 bytes long. Anything else is an error.

**Comment by axic** [comment]
Of course this should be implemented with an experimental pragma, i.e. show a warning now and and an error in 0.5.0 mode.

**Comment by OTTTO** [comment]
0x0 can still be used for resetting to default value or burn?

**Comment by axic** [comment]
All zeroes must be typed for an address.

**Comment by chriseth** [comment]
`address(0)` could still be possible.
