### ISSUE TITLE
Constructor parameters are not enforced by child

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2911]
These compile without issues:
```
contract Base {
  function Base(uint a) {}
}

contract Derived is Base() { }
```

```
contract Base {
  function Base(uint a) {}
}

contract Derived { }
```

The generated ABI of both cases for Derived have no constructor and they become abstract.

```
contract Base {
  function Base(uint a) {}
}

contract Derived { }

contract Derived2 is Derived(2) {}
```

The child of Derived cannot be compiled as the constructor is missing.

**Comment by chriseth** [comment]
I think the idea behind this was that further derived classes may specify the constructor arguments of the very base class. so you could have

```
contract Base {
  function Base(uint a) {}
}

contract Derived is Base { }

contract FurtherDerived is Derived, Base(7) {}
```

**Comment by chriseth** [comment]
To expand on the previous comment: The use-case for this is that some contract wants to inherit functionality from a base contract but leaves it to the further derived class to actually specify concrete parameters.

**Comment by axic** [comment]
I think that idea is covered in #2912 and currently crashes the compiler.

**Comment by axic** [comment]
@ekpyron @chriseth I think we may have fixed this

**Comment by chriseth** [comment]
This has never been a bug for me anyway....

**Comment by Marenz** [comment]
I am a bit confused by the description. Is this a feature to be implement, an existing problem? I just read a lot of statements in the opening part but no "This should be X instead of Y".. as in, the current and desired behavior is not clear to me..

**Comment by chriseth** [comment]
I think it can be closed. The `abstract` keyword makes this visible and everything compiles correctly.
