### ISSUE TITLE
Constant byte array of arbitrary length no longer compiles

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/solidity#2914]
In older solidity versions I could store an arbitrary length byte array as a constant in a contract in the following way:

```
contract Test {
    bytes constant sin_table = "\x00\x00\x0c\x8c\x18\xf9\x25\x28\x30\xfb\x3c\x56\x47\x1c\x51\x33\x5a\x82\x62\xf1\x6a\x6d\x70\xe2\x76\x41\x7a\x7c\x7d\x89\x7f\x61\x7f\xff";
}
```
I tried to do it again with the latest stable solidity version (0.4.16) and got the following error:
`Constants of non-value type not yet implemented.`

If my byte array is 32 bytes in length, I can then used `bytes32`. If it's not I will always get the above error.

Is this a known breaking change of newer solidity versions? Or is it a bug? If it's not a bug are there plans to re-introduce the ability to store constant byte arrays in any form?

**Comment by chriseth** [comment]
It seems we only allow strings there, which does not make a lot of sense.
