### ISSUE TITLE
Undescriptive exception is thrown when stack underflows during --assemble

### ISSUE THREAD

**Issue by ritave** [ethereum/solidity#2916]
I was writting standalone assembly and had a bug in my code, with a minimal reproduction being:
```
{
    0x1
    jumpi my_tag
    my_tag:
    stop
}
```
which should be
```
{
    0x1
    my_tag
    jumpi
    my_tag:
    stop
}

```
instead.
Solc then threw out an error without any explanation:
```
Pretty printed source:
{
    0x1
    jumpi
    my_tag
    my_tag:
    stop
}
Exception while assembling: D:\Libraries\Documents\Praca\solidity\libevmasm\Assembly.cpp(323): Throw in function const class dev::eth::AssemblyItem &__cdecl dev::eth::Assembly::append(const class dev::eth::AssemblyItem &)
Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::eth::AssemblyException>
std::exception::what:
[struct dev::tag_comment * __ptr64] =
```

Assembly.cpp calculates the stack depth constantly, and on underflow throws an undescriptive exception   in [Assembly.cpp:323](https://github.com/ethereum/solidity/blob/develop/libevmasm/Assembly.cpp#L323)

I would expect the error to be ignored (I'm doing raw jumps, safety is up-to me), or a warning issued.

While we're here I believe that stack depth calculations shouldn't be enforced and be more-or-less optional (so you can use `:=` variables). That's because if I'm writing raw manual assembly, the flow and stack-depth might really not follow the expectations of blocks and empty stacks after each one and I might be jumping around the control flow.

Additional info:
Solidity commit hash which I used:
```a0d171722a211720773aae0ded8a80991d44ba9d```

**Comment by axic** [comment]
@ritave thanks for reporting this. As a quick aid added the proper message to the assertion.

**Comment by chriseth** [comment]
This will be "fixed" when we disallow non-strict mode.
