### ISSUE TITLE
Style Guide Docs -- Mappings section

### ISSUE THREAD

**Issue by aupiff** [ethereum/solidity#2917]
What was intended for the mappings section of the style guide? It's a TODO currently. If somebody could point me to a few good `mapping` usage examples I'd happily complete this section of `style-guide.rst`.

**Comment by axic** [comment]
You could have a look at the rest of documentation where it is using `mapping`, e.g.

`mapping (uint => uint) map;`
`mapping (uint => mapping(bool => Data[])) public data;`

I think that's as far as it goes.

Just create a pull request, list the good examples and some bad examples (wrong indentation, etc.) and we can debate it on the pull request.

**Comment by aupiff** [comment]
In the docs file miscellaneous.rst, line 56 does not follow the same conventions as your examples from contracts.rst.

```
line 56: mapping(uint => mapping(uint => s)) data;
```

The examples you provide imply that there should be a space between the leftmost `mapping` and the open parenthesis, but much of the solidity code uses the convention of line 56 above. Here's an example of the a file that uses both styles:

```
test/libsolidity/SolidityNameAndTypeResolution.cpp:4310:  mapping(ufixed8x1 => string) fixedString;
test/libsolidity/SolidityNameAndTypeResolution.cpp:6604:  mapping (uint => uint) m;
```

I'd suggest adding the following to the mappings section if you think the style of contracts.rst is better.

```
+The type of `mapping` is invariably surrounded by parentheses. In variable
+declarations, the keyword `mapping` should be seperated from its type by
+a single space. Any nested `mapping` keyword, however, should not be seperated from
+its type by whitespace.
+
+Yes::
+
+    mapping (uint => uint) map;
+    mapping (address => bool) registeredAddresses;
+    mapping (uint => mapping(bool => Data[])) public data;
+    mapping (uint => mapping(uint => s)) data;
+
+No::
+
+    mapping(uint => uint) map;
+    mapping( address => bool ) registeredAddresses;
+    mapping(uint => mapping (bool => Data[])) public data;
+    mapping(uint => mapping(uint => s)) data;
```

Thoughts?

**Comment by androlo** [comment]
The extra space doesn't really seem like it makes it clearer or better in any way. Functions and arrays (brackets) doesn't encourage the use of an extra space, for example. Also, making the rule context sensitive seems to add complexity where it isn't really needed.

Maybe I don't get it - what makes this standard objectively better then the alternative of having no space after `mapping`?

**Comment by ChrisChinchilla** [comment]
This issue is now in progress, PR coming very soon

**Comment by chriseth** [comment]
I agree with @androlo. It's probably better to have no space after `mapping` in every case.
