### ISSUE TITLE
multiple assignment for IULIA

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#2923]

**Comment by axic** [comment]
I've started doing this a while ago. Uploaded the branch `inlineasm-assign-multi`.

**Comment by chriseth** [comment]
Ah nice! I just realized I need this feature for the ABI decoder :)

**Comment by axic** [comment]
You were against it at the time :)

**Comment by chriseth** [comment]
Hm, must have been connected with some weird desugaring requirements...
