### ISSUE TITLE
Memory leak in LLL parser

### ISSUE THREAD

**Issue by chfast** [ethereum/solidity#2932]
I extracted the test causing it: `[[0x0]]` https://github.com/ethereum/solidity/commit/29b3aa4696294d31fb607d068e8661b933ed8a35.
But I have no idea how to attack this problem. The boost spirit is so undebuggable.

**Comment by axic** [comment]
Basically numbers are represent as bignums and they are never freed.

**Comment by Marenz** [comment]
We will no longer work on the LLL parser
