### ISSUE TITLE
Add variable type and build-in function: ECDSA_signature, ECDSA_verify

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#2958]
**Suggestion:** 

1. A new 72-byte **ecdsa_signature** type and

2. a built-in function **ecdsa_verify(address pubkey, bytes32 data, ecdsa_signature sig) pure returns (bool)**

**Rationale:** many contracts in Solidity need to verify signatures on data. The current **ecrecover()** returns an address given a Keccak256 hash and a (uint8 v, bytes32 r, bytes32 s) triplet. The proposed type and built-in would create a neater experience for passing around, storing, and verifying signatures on data. 

**Existing workaround:** Many project create their own structs for storing signatures and wrapper functions around **ecrecover**. The proposed changes would reduce bloat through standardization.

**How:** **ecdsa_signature** would be a new 72-byte variable type. **ecdsa_verify** would be a wrapper around ecrecover that decomposes a passed in **ecdsa_signature** into (uint8 v, bytes32 r, bytes32 s) and passes the triplet into **ecrecover**.

Let me know if anyone is interested in adding this feature!

**Comment by axic** [comment]
I think this is something really fit for a library. I'd be against adding more builtin types to the compiler if it can be avoided.

**Comment by ghost** [comment]
Given standard library maturity, it seems like I good idea to keep this out of the compiler. However, in anticipation of this, I would argue that these changes strictly improve the experience of using the **ecrecover** built-in (and may even replace it to avoid increasing the number of built-ins).

**Comment by chriseth** [comment]
I think it is the job of EIPs to standardize the different implementations and adding this as a type to Solidity is too big a complication.
