### ISSUE TITLE
New contract with 3 uint fields not worked

### ISSUE THREAD

**Issue by Format-X22** [ethereum/solidity#2959]
Contract maker:

    contract X {
        address[1] public results;

        function t1() {
            results[0] = new T();
        }
    }

This code with 2 uint fields worked ok:

    contract T {

        address public sender;
        uint public a;
        uint public b;

        function T() {
            sender = msg.sender;
        }
    }

...but this code with 3 uint fields not worked:

    contract T {

        address public sender;
        uint public a;
        uint public b;
        uint public c;

        function T() {
            sender = msg.sender;
        }
    }

This code with 3 uint fields and not public sender worked ok:

    contract T {

        address sender;
        uint public a;
        uint public b;
        uint public c;

        function T() {
            sender = msg.sender;
        }
    }

...but this code with sender getter not worked:

    contract T {

        address sender;
        uint public a;
        uint public b;
        uint public c;

        function T() {
            sender = msg.sender;
        }

        function getSender() returns (address) {
            return sender;
        } 
    }

**Comment by axic** [comment]
What do you mean by worked? What client are you using and what symptoms do you see in each case?

**Comment by Format-X22** [comment]
Steps:
1 - Deploy contract X.
2 - Call method t1.

In first case with 2 uint address write to results array, in case with 3 uint - address not write in results array.

Use Ethereum Wallet with "pragma solidity ^0.4.11;"

**Comment by chriseth** [comment]
Please reopen if you have more information.
