### ISSUE TITLE
Modifier can't read correct data from contract fields in some case

### ISSUE THREAD

**Issue by Format-X22** [ethereum/solidity#2960]
Code:

    pragma solidity ^0.4.11;

    contract A {
        address public owner;

        modifier onlyOwner() {
            require(msg.sender == owner);
            _;
        } 
    }

    contract B is A {
        address public owner;
        bool public ok;

        function B() {
            owner = msg.sender;
        }

        function callMe() onlyOwner {
            ok = true;
        }
    }

    contract C is A {
        bool public ok;

        function C() {
            owner = msg.sender;
        }

        function callMe() onlyOwner {
            ok = true;
        } 
    }

Steps:
1 - Deploy contract B and C.
2 - Call "callMe" methods on B and C.
3 - See "ok" field.

In B field is FALSE, but owner is correct. Modifier read owner field from parent class?
This may be a vulnerability and cause loss of money in some cases like this:

    pragma solidity ^0.4.11;

    contract A {
        bool public started = true;

        modifier onlyIfStarted() {
            require(started == true);
            _;
        }
    }

    contract B is A {
        bool public started = false;
        bool public thisFail;

        function callMe() onlyIfStarted {
            thisFail = true;
        }
    }

**Comment by chriseth** [comment]
Yes, this behaviour is due to the shadowing of state variables. We have a fix in the pipeline: https://github.com/ethereum/solidity/issues/2563
