### ISSUE TITLE
Re-enable trailing commas in function parameters, arrays, etc.

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#2991]
I don't know why this functionality was removed. Diffs are much cleaner if trailing comma are allowed.

EMCA supports trailing commas: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by axic** [comment]
Can you please expand where do you miss trailing commas?

**Comment by ethernomad** [comment]
The problem with not allowing trailing commas is you get ugly diffs like this:
```
   "dependencies": {
+    "brotli": "^1.3.2",
     "express": "^4.16.1",
     "google-protobuf": "^3.4.0",
-    "jquery": "^3.2.1"
+    "jquery": "^3.2.1",
+    "pako": "^1.0.6"
   }
```

**Comment by axic** [comment]
I understand, but can you please show an example in which Solidity statement you are missing it?

**Comment by Tootoot222** [comment]
I've noticed this bug in several places:

Instantiating a struct:
```
  struct BigStruct {
    string title;
    uint256 number;
    ...
    uint256 balance;
    int256 permissions;
  } //this is fine since they end with ;
...
  BigStruct memory bs = BigStruct({
    title: "whatever",
    number: ++structCount,
    ....
    balance: 0,
    permissions: 0 //wish the , could be put here so new fields can be easily added!
  });
```

Function returns:
```
function getStructWithLotsOfFields(uint256 num) returns (
  string title,
  uint256 number,
  ...
  uint256 balance,
  int256 permissions //wish i could put the , on the end so new fields can be easily added!
) {
  return (
    bigStructMap[num].title,
    ...
    bigStructMap[num].permissions //same problem here
  );
```

Might be others in similar situations, but these were some I found recently

**Comment by axic** [comment]
Sorry for the delay in noticing the answer and thank you for expanding on it.

I think in general this goes against Solidity's goal of explicitness. I am sure having a trailing comma for example in a return parameters list could be interpreted by the user in multiple ways. (Does it return an extra unnamed parameter?!)

As a result I think while there might be some benefits (for example with diff), it is a really bad idea for Solidity.

**Comment by axic** [comment]
I suggest to close this proposal. @chriseth @ekpyron @bit-shift @leonardoalt @christianparpart anybody for keeping this?

**Comment by leonardoalt** [comment]
@axic I agree with you

**Comment by leonardoalt** [comment]
In the meantime @axic became a Rustacean. Does it make sense to reconsider it?
IMO it's not really harmful and may be of interest to some people.

**Comment by cameel** [comment]
Coming from some languages where it's allowed (Python especially), I always thought it's a nice feature and I'd be for having it in Solidity as well.

There's one problem though - tuples can have empty elements.

**Comment by leonardoalt** [comment]
You mean unnamed elements? But that's still fine I guess? You just allow one extra comma

**Comment by cameel** [comment]
How would that work? Is `(,,,)` 3 unnamed elements or 2 with an extra comma?

**Comment by leonardoalt** [comment]
Yea, there's also ambiguity in `(a,b,)`

**Comment by cameel** [comment]
Not if unnamed elements are not allowed. Maybe we should get rid of them? There was a proposal on the forum in the past to use `_` for them like some languages do. That would require some gymnastics to deal with modifier placeholders but we might still be able to deal with it somehow by distinguishing them inside and outside of tuples.

**Comment by ekpyron** [comment]
To be honest, in Solidity this causes way more problems than it solves, so we shouldn't be doing this at least now.

**Comment by cameel** [comment]
Just wanted to note that if we do decide to go forward with it, a good way to resolve the ambiguity would be to allow leaving the type in the tuple declaration when the component is not used. I.e. being able to do `(T1 a, T2, T3 c)` instead of the current `(T1 a,, T3 c)`. Doing it that way would also be non-breaking because this is currently a syntax error - we could allow trailing commas only in that form.

**Comment by ekpyron** [comment]
As far as I'm concerned, we should never have gone for the weird non-uniform ``(T1 a, T2 b, T3 c) = ...`` syntax anyways and rather have made it ``(T1, T2, T3) (a,b,c) = ...``. I was outvoted back then and I do see the readability difference, but the latter is that much more uniform that it'd have paid of a lot in the long run... once we tackle having proper namable tuple types we'll probably have to get back to this.

But for the time being, I seriously think we shouldn't mess with the commas here - it'll have even further implications for type uniformity. We can revisit this once our type system is fully future-proofed - only then all potential issues with this will become apparent.
