### ISSUE TITLE
Add experimental tag to natspec

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#2992]
This is only playing with an idea - a way to leverage natspec and the experimental pragma system to signal to users that a contract/library should be considered experimental (i.e. not ready for live deployment).

Experimental pragma supports "libraries", or something similar:

`pragma experimental "libraries";`

Natspec has a tag for contract docs `@experimental`

```
/// @title MyDevLibrary
/// @experimental
contract MyDevLibrary {

}
```

Compiler will report an error if `MyDevLibrary` is used without the pragma.

**Comment by androlo** [comment]
This (or anything similar to it) would of course not prevent experimental code from being used, since the developer can chose not to flag their code, but it would be a great way for serious developers to show that it should not be used (like for example when it comes to standard library code). 

There is so much code out there where the writers point out in the repo docs that the code is experimental / under development. How great if they could raise this flag in the actual code instead.

**Comment by christianparpart** [comment]
I took that one too quickly. Unassigning.

**Comment by axic** [comment]
Do we still need this or using `@custom:experimental` good enough for now?

On the other hand I am not fully convinced there should be experimental functions in released contracts.
