### ISSUE TITLE
block.blockhash cannot be assigned to a function type variable

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2996]
```
blockhash.sol:3:5: Error: Type function (uint256) view returns (bytes32) is not implicitly convertible to expected type function (uint256) view returns (bytes32).
    function (uint) view returns (bytes32) blockhash = block.blockhash;
    ^----------------------------------------------------------------^
```

**Comment by axic** [comment]
The reason is that `FunctionType::toString` is used, which doesn't list all the function kinds. In the above case it is `internal` while `block.blockhash` is of kind `blockhash`.

At least `var blockhash = block.blockhash; blockhash(5);` should work, but that fails with:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/ExpressionCompiler.cpp(1113): Throw in function virtual bool dev::solidity::ExpressionCompiler::visit(const dev::solidity::MemberAccess &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Unknown magic member.
[dev::tag_comment*] = Unknown magic member.
```

**Comment by chriseth** [comment]
I'm fine with completely disallowing the assignment.

**Comment by axic** [comment]
> At least `var blockhash = block.blockhash; blockhash(5);` should work, but that fails with:

Is not a problem anymore as `var` is disallowed.

**Comment by axic** [comment]
Assigning built in functions to function type should be a new feature and not a bug, closing this.
