### ISSUE TITLE
Unused local variable... 

### ISSUE THREAD

**Issue by gary0318** [ethereum/solidity#2998]
I have this line in a contract, trying to compile from within mist.
      
         var _ = admin.call.gas(GAS_LIMIT).value(this.balance)();

Not sure what to do to correct this. Here is the whole function.

    function finalizeLottery(uint _steps)
             afterInitialization {
        require(needsFinalization());

        if (lotteries[id].nearestKnownBlock != lotteries[id].decidingBlock) {
            walkTowardsBlock(_steps);
        } else {
            int winningTicket = lotteries[id].nearestKnownBlockHash %
                                int(lotteries[id].numTickets);
            address winner = lotteries[id].tickets[uint(winningTicket)];

            lotteries[id].winningTicket = winningTicket;
            lotteries[id].winner = winner;
            lotteries[id].finalizationBlock = block.number;
            lotteries[id].finalizer = tx.origin;

            if (winner != 0) {
                uint value = lotteries[id].jackpot;
                bool successful = winner.call.gas(GAS_LIMIT).value(value)();
                if (!successful) {
                    Escrow(escrow).deposit.value(value)(winner);
                }
            }
           var _ = admin.call.gas(GAS_LIMIT).value(this.balance)();
        }
    }

**Comment by axic** [comment]
Not sure if that is entire source code, but `_` is assigned to and never used and as such is an unused local variable.

**Comment by axic** [comment]
Please reopen if more clarification is needed.
