### ISSUE TITLE
build failed!

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/solidity#30]
-- Build files have been written to: /home/ubuntu/solidity/build
ubuntu@:~/solidity/build$ make -j2
Scanning dependencies of target solidity
[  4%] [  4%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ASTJsonConverter.cpp.o
Building CXX object libsolidity/CMakeFiles/solidity.dir/Version.cpp.o
/home/ubuntu/solidity/libsolidity/Version.cpp:25:23: fatal error: BuildInfo.h: No such file or directory
 #include <BuildInfo.h>
                       ^
compilation terminated.
In file included from /home/ubuntu/solidity/libsolidity/../libsolidity/ASTVisitor.h:28:0,
                 from /home/ubuntu/solidity/libsolidity/../libsolidity/ASTJsonConverter.h:27,
                 from /home/ubuntu/solidity/libsolidity/ASTJsonConverter.cpp:23:
/home/ubuntu/solidity/libsolidity/../libsolidity/AST.h:30:38: fatal error: libevmasm/SourceLocation.h: No such file or directory
 #include <libevmasm/SourceLocation.h>
                                      ^
compilation terminated.
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/Version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/ASTJsonConverter.cpp.o] Error 1
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
make: *** [all] Error 2

**Comment by debris** [comment]
can you try again? there was a little bug in cmake files, but it should be fixed in https://github.com/ethereum/cpp-ethereum-cmake/commit/35256410cd635fa55ac943dac375bf7a3310282c

**Comment by LianaHus** [comment]
problem fixed in ethereum/cpp-ethereum-cmake@3525641
