### ISSUE TITLE
Cmake compilation failed

### ISSUE THREAD

**Issue by pawanjay176** [ethereum/solidity#301]
Compilation fails when I run cmake. How do I resolve this?

Here's the log file

Determining if the CL_VERSION_2_0 exist failed with the following output:
Change Dir: /home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec749800118/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec749800118.dir/build.make CMakeFiles/cmTryCompileExec749800118.dir/build
make[1]: Entering directory `/home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec749800118.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fuse-ld=gold -fuse-ld=gold    -o CMakeFiles/cmTryCompileExec749800118.dir/CheckSymbolExists.c.o   -c /home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘CL_VERSION_2_0’ undeclared (first use in this function)
   return ((int*)(&CL_VERSION_2_0))[argc];
                   ^
/home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [CMakeFiles/cmTryCompileExec749800118.dir/CheckSymbolExists.c.o] Error 1
make[1]: Leaving directory`/home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp'
make: **\* [cmTryCompileExec749800118/fast] Error 2

File /home/pawan/webthree-umbrella/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/\* */
# include </usr/include/CL/cl.h>

int main(int argc, char*\* argv)
{
  (void)argv;
# ifndef CL_VERSION_2_0

  return ((int*)(&CL_VERSION_2_0))[argc];
# else

  (void)argc;
  return 0;
# endif

}

**Comment by suyashgupta25** [comment]
What is the solution here?
