### ISSUE TITLE
Crowdsale not compiling: problem with GoalReached

### ISSUE THREAD

**Issue by wrisx** [ethereum/solidity#3018]
System information

Geth version: geth version 1.7.0
OS & Version: Windows 10

Expected behaviour

Deploy the crowdsale contract in the Ethereum wallet. The code from: https://www.ethereum.org/crowdsale. The code is pragma solidity ^0.4.16.

Actual behaviour

It won't. It says: Could not compile source code. And then the error stated below this text. Does anybody know how to still deploy a crowdsale?

Backtrace

Could not compile source code. 

 This declaration shadows an existing declaration.
    event GoalReached(address beneficiary, uint amountRaised);
                      ^-----------------^

**Comment by axic** [comment]
Unfortunately this is a bug in Mist (Ethereum wallet). This is a warning and not an error. It has been raised at Mist before: https://github.com/ethereum/mist/issues/2797

You can compile the contract with Remix (https://remix.ethereum.org) or try renaming `GoalReached` to not conflict with another declaration.

**Comment by chka** [comment]
ehh... it's not a bug, it simply needs different variables inside the event:

event GoalReached(address beneficiary1, uint amountRaised1);

**Comment by axic** [comment]
The bug in Mist is that it considers Solidity warnings as errors (without a way to disable this behaviour) and shadowing declarations is only a warning.

**Comment by acgoldfish** [comment]
The Bug in Mist  is these  Warnings are been treated as a hard Errors
ethereum/mist#2797 when is this going to be fixed ?
