### ISSUE TITLE
Solidity is compiling and executing the contract which doesn't conform with actual return type.

### ISSUE THREAD

**Issue by rajcspsg** [ethereum/solidity#3026]
1. Which version of Solidity you are using - 
          soljson-v0.4.8+commit.60cc1668.js

    2. What was the source code (if applicable) -

    ```contract Sheep {
       string public name;
       string public dna;
       function Sheep(string _name, string _dna) {
           name = _name;
           dna = _dna;
        }
    
        function geneticallyEngineer(string _dna) returns (bool) {
           dna = _dna;
       }
   }```


    3. Which platform are you running on - remix browser
         https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.8+commit.60cc1668.js

    4. How to reproduce the issue -  compile and execute the contract

    5. What was the result of the issue - Compilation is successful.

    6. What the expected behavior is - The contract `geneticallyEngineer` is expected to return Boolean as result as per code(`returns (bool)`)  but it is not returning anything. Still the code compiles and executes. 


Looks to me this is a bug.

**Comment by axic** [comment]
Return values just like local variables are initialised to the "default empty value", in case of `bool` that's false. There's no requirement for explicit returns at the moment.

@soad003 @yann300 this would be a good feature for the static analyzer: raise a warning if no return statement is present and none of the return parameters are named.

**Comment by soad003** [comment]
@axic yeah sounds good, should be straight forward to implement. I can do that if i find time ...

**Comment by soad003** [comment]
In progress: https://github.com/ethereum/browser-solidity/pull/866

**Comment by axic** [comment]
@soad003 great work, thanks!
