### ISSUE TITLE
Shall block.blockhash throw if the argument is invalid?

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3028]

**Comment by axic** [comment]
Invalid as in out of range?

**Comment by chriseth** [comment]
Yes

**Comment by chriseth** [comment]
We could also just throw if it returns zero, in anticipation for potential changes in the EVM.

**Comment by axic** [comment]
The opcode is defined as returning 0 in case of out of range. The new blockhash will have weird rules to see if the hash is present or not - how will the user be able to check if it is in range without throwing?

**Comment by federicobond** [comment]
Agree with @axic that it will be hard to check beforehand if the value is present. This could be partially solved with the planned try-catch construct, but even then you are not forced or even encouraged to handle the failure case in your code. 

Another, more explicit alternative is returning a `(uint256 hash, bool exists)` tuple.

**Comment by chriseth** [comment]
So a better option would be to have the SMT checker see if the argument is in range?

**Comment by axic** [comment]
Could reconsider this now with having `try/catch` in place.

**Comment by chriseth** [comment]
For that, we need to extend try/catch to certain non-external functions and I don't know if this would be a good idea.
