### ISSUE TITLE
SMT Solver Additions

### ISSUE THREAD

**Issue by joeykrug** [ethereum/solidity#3034]
It’d be great if the SMT solver supported the following features from oyente

Money concurrency detection
Time dependency detection
Reentrancy bug detection

**Comment by chriseth** [comment]
I think this is not the level the SMT solver is working at, although it can be used to detect problems arising from e.g. not thinking about reentrancy.

Could you give short example code containing such bugs? Then we could see which features we can add to the SMT solver exactly to find these bugs.
