### ISSUE TITLE
Error out instead of skipping non-existent source files

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#3037]
I don't know if anyone is relying on this behavior, we could define a command-line option instead.
Suggested name: `--ignore-missing`, `--noignore-missing`

**Comment by axic** [comment]
I'd lean towards erroring as perhaps that is the expected behaviour.

**Comment by axic** [comment]
@chriseth I think we should make an exception here and do a "breaking change" in a non-breaking release by making reading non-existant files an error, which can be turned off by `--ignore-missing-files`.

If someone relies on this behaviour it is an easy fix for them, but most of the frameworks (truffle, dapple) use solc-js and are not affected. Populous uses the commandline so they may be affected.

cc @veox @pipermerriam

**Comment by chriseth** [comment]
@axic yes, good idea. We do not have to be that strict in the commandline interface.

**Comment by veox** [comment]
When used with Solidity >= 0.4.11, Populus will use the StandardJSON approach - piping to `solc`'s `stdin`.

That is, Populus should be unaffected by the change.

**Comment by federicobond** [comment]
I think it would be useful to discuss the changes required first. In particular, `ReadCallback::Result` has a boolean indicating whether the read succeeded or not. Should we augment it with the type of error? Throw exceptions? How does it impact `solc-js`?

**Comment by AnthonyBroadCrawford** [comment]
@chriseth mind if I run with this issue?

**Comment by axic** [comment]
@AnthonyBroadCrawford please go ahead

**Comment by axic** [comment]
@federicobond I think it may be a good idea to support multiple levels of error types, but is it needed for this issue?

**Comment by pipermerriam** [comment]
@axic this change will be fine for populus.

**Comment by AnthonyBroadCrawford** [comment]
@axic Can you point me in the initial direction within the codebase?  I'm sure I'll have more question but I should be able to figure it out once I know where to start.  Thank you!

**Comment by axic** [comment]
It most likely will have to be changed here: https://github.com/ethereum/solidity/blob/develop/solc/CommandLineInterface.cpp#L513

**Comment by AnthonyBroadCrawford** [comment]
@axic For my first pass I'm going to have it error on missing files, but take @federicobond suggestion and add an option allowing users to inform the compiler to ignore missing files.

**Comment by axic** [comment]
Sounds good!

**Comment by AnthonyBroadCrawford** [comment]
@axic I opened a PR here https://github.com/ethereum/solidity/pull/3754 for feedback.  The feature is functional but not ready for merge.  I simply wanted some eyes on a few of my decisions.  Once I have feedback I'll 

1. Implement feedback 
2. Squash down into a single commit 
3. Update change log 
4. Etc 

Let me know what you think.
