### ISSUE TITLE
Internal compiler error when compiling function attempting to return "var storage"

### ISSUE THREAD

**Issue by vindalho2** [ethereum/solidity#3039]
The following Internal compiler error is generated when compiling a function attempting to return "var storage":

```
$ solc testapp.sol 
Internal compiler error during compilation:
/tmp/solidity-20171002-24864-zigqo9/solidity_0.4.17/libsolidity/parsing/Parser.cpp(582): Throw in function ASTPointer<dev::solidity::VariableDeclaration> dev::solidity::Parser::parseVariableDeclaration(const dev::solidity::Parser::VarDeclParserOptions &, const ASTPointer<dev::solidity::TypeName> &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

The solc version:
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.17+commit.bdeb9e52.Darwin.appleclang
```

The contract source code:
```
contract TestApp  {
    struct TransactionalAppData { 
        address warrior;
        address warriorBlock;
        address king;
    }

    TransactionalAppData appData1;
    TransactionalAppData appData2;

    uint currentExecutingTransaction;

    function getAppDataPointer2() internal returns (var storage)  
    {
	return (currentExecutingTransaction == 0) ? appData1 : appData2;	
    }   
}
```

**Comment by axic** [comment]
`var` should be disabled in arguments/return parameters

**Comment by chriseth** [comment]
`options.allowVar` should be set to false but somehow is not. This might be a good first bug for someone.

**Comment by jklepatch** [comment]
I would like to work on this, but I need some guidance.
Is this the right place to look?
https://github.com/ethereum/solidity/blob/010189d58eca560dd319aab07daa43bda0911a40/libsolidity/parsing/Parser.cpp

**Comment by federicobond** [comment]
Yes, that's the file. You might want to take a look at the code inside `parseFunctionHeader`.

**Comment by jklepatch** [comment]
This is the call stack:
```
parseFunctionHeader()
 |--> parseParameterList()
         |--> parseVariableDeclaration()
                 |--> parseTypeName()
```

In `parseFunctionHeader()`, I have set `options.allowVar = false;`  before each call to `parseParameterList()` .

In `parser.cpp` on line 582 the same internal compiler error occured:
```
      //this is inside `parseVariableDeclaration()`)
	if (_options.allowEmptyName && m_scanner->currentToken() != Token::Identifier)
	{
		identifier = make_shared<ASTString>("");
		solAssert(type != nullptr, ""); //This assertion fails
		nodeFactory.setEndPositionFromNode(type);
	}
```
By adding an extra condition `&& _options.allowVar == true` to the above `if` statement, we have a solidity compilation error (as opposed to an internal compiler error that we had before):

`test.sol:13:35: Error: Expected explicit type name`

Is this the intended behavior?

**Comment by chriseth** [comment]
@jklepatch yes, this sounds about right! Can you create a pull request?

**Comment by jklepatch** [comment]
Sure i will. Before this, may I know if there  are tests that check that some contracts produce specific compile errors ? So that I could also add a test case with the pr.
-- On Thu, 12 Oct 2017 15:27:49 +0800 notifications@github.com wrote ----

@jklepatch yes, this sounds about right! Can you create a pull request?

**Comment by axic** [comment]
Have a look at the `test/libsolidity` directory. A test for this error should go into `test/libsolidity/SolidityNameAndTypeResolution.cpp`.

**Comment by jklepatch** [comment]
My changes: https://github.com/jklepatch/solidity/commit/8d6f94fb0e8ffb53451629f7498015ecc993d36f
Test: https://github.com/jklepatch/solidity/commit/682a03519287aa79b3f46a252b40521fa3034322

When I tested my changes with the compiler by running the executable against the contract, it worked.
However, when I ran the test with ./build/test/soltest -- --no-ipc I saw that my changes broke lots of tests, for example:
```
/home/jklepatch/os/solidity/test/libsolidity/AnalysisFramework.cpp(51): error in "address_overload_resolution": Parsing contract failed in analysis test suite:Warning: This is a pre-release compiler version, please do not use it in production.
:4:36: Error: Expected identifier, got 'RParen'
			function balance() returns (uint) {
```

**Comment by chriseth** [comment]
@jklepatch please create a pull request. It willl run the tests and we can discuss there.

**Comment by axic** [comment]
@chriseth I think this might show another bug too `returns (var storage)`. Should the `storage` modifier be valid on `var`?

@jklepatch are you still interested in this?

**Comment by erak** [comment]
@ekpyron Running the follwing
```
contract C {
    struct S { uint a; }
    S s;
    function f() internal view returns (var storage) {
        return s;
    }
}
```
through ``isoltest`` does not expose the ``InternalCompilerError`` that occurs here. It rather acts as expected and shows a ``ParserError`` instead. Seems the exception is been caught.
 
Is handling ``ParserErrors`` in ``isoltest`` supported at all? I could not make the expectations work.

**Comment by ekpyron** [comment]
@bit-shift Parser errors are not yet supported in the new testing framework, so parser tests should still go to ``test/libsolidity/SolidityParser.cpp``.

**Comment by ekpyron** [comment]
@bit-shift I'm about to add support for parser errors, though.

**Comment by erak** [comment]
@ekpyron Thanks for clarifying! Adding support for parser errors would be great :)
