### ISSUE TITLE
Support overloading for modifiers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3041]
```
contract C {
  modifier m(uint a) { _; }
  modifier m(bytes b) { _; }
  modifier m(uint a, bytes b) { _; }
}
```

(From Pivotaltracker https://www.pivotaltracker.com/story/show/104324810.)

**Comment by chriseth** [comment]
This should be a duplicate of https://github.com/ethereum/solidity/issues/72

**Comment by martasaparicio** [comment]
is overloading modifiers available?
