### ISSUE TITLE
address.code and address.codesize

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3044]
> Add a member called "code" to the address type that returns a variably-sized byte array which contains the code at that address.
> Translate "address.code.length" directly to CODESIZE.

(From https://www.pivotaltracker.com/story/show/89623638)

**Comment by axic** [comment]
With Constantinople's `extcodehash` feature this should also support `address.hash` or `address.codehash`.

**Comment by axic** [comment]
I think these features would be nice, especially considering that a lot of contracts now use assembly to access them, which puts an extra burden on the SMTChecker.

cc @leonardoalt 

Probably should be considered in conjunction with #4910

**Comment by chriseth** [comment]
`.codeHash`, `.code`, `.codeSize`? Or `.codeLength`?

**Comment by axic** [comment]
I think codesize is fine as it is close to the opcode. A user can also do `code.length` at the cost of memory expansion, unless we want to make a weird shortcut where `code.length` translates to `extcodesize`.

Also question: should the compiler generate `codesize/codecopy` (and not `extcodesize/extcodecopy`) in case of `address(this).codesize` and `address(this).code`?

**Comment by chriseth** [comment]
Sure, same mechanism as with selfbalance.

**Comment by chriseth** [comment]
Let's implement `.code` as memory array with a shortcut for `.code.length` (and for codecopy / extcodecopy)

**Comment by axic** [comment]
We agreed to `.code` (and `.code.length`), but there seems to be no clarity on hash. Is it `.hash` or `.codeHash` or `.codehash`? Or adding yet another hack of translating `keccak256(...code)` in the codegen? I would rather not.

**Comment by axic** [comment]
> Or adding yet another hack of translating keccak256(...code) in the codegen? I would rather not.

Actually a good point against this is the push for code merkleization (i.e. [EIP-2926](https://eips.ethereum.org/EIPS/eip-2926)) which would change the way the codehash is calculated.
