### ISSUE TITLE
Incorrect solc install documentation

### ISSUE THREAD

**Issue by lorien** [ethereum/solidity#3048]
This document https://github.com/ethereum/solidity/blob/develop/docs/installing-solidity.rst says: clone repo, make directory "build" and run `cd build; cmake .. && make`
That does not work. When I run `cmake ..` inside build directory it creates files on top-level directory and the build directory remains empty. Then the `make` command does nothing.
Running './scripts/build.sh` fails same way.

Debian stretch
cmake 3.7.2
make 4.1

**Comment by limexp** [comment]
I am afraid that you missed [External Dependencies step](https://github.com/ethereum/solidity/blob/develop/docs/installing-solidity.rst#external-dependencies).
Just checked on a clean Debian installation that the following commands are fine:
```
apt-get install sudo git gcc g++ cmake
git clone --recursive https://github.com/ethereum/solidity.git
cd solidity
git submodule update --init --recursive
./scripts/install_deps.sh
mkdir build
cd build
cmake .. && make
```

Last three lines can be replaced with one command ```./scripts/build.sh```.

I also missed External Dependencies for the first time and Boost_INCLUDE_DIR error is not very descriptive, so adding an accent is a good idea.

**Comment by chriseth** [comment]
@lorien does that fix it for you? If not, can you please paste the console output of the commands?

**Comment by lorien** [comment]
@chriseth @limexp My problem was not in ext. dependencies
I just can't run `make` command from `build` directory, because it is empty because `cmake ..` creates files in upper directory. I'll try today/tomorow to reproduce the problem and provide more detailed description.

**Comment by limexp** [comment]
@lorien 
I installed a brand new copy of Debian yesterday and executed above commands as root. Everything was fine. Unfortunately I forgot to check cmake and make versions.
Without a console log it is hard to guess.

**Comment by lorien** [comment]
I've checked few times - it works OK for me now. Exactly as described in documentation. I think I should close the issue.
