### ISSUE TITLE
Formal Verif: Issue warning when struct are not passed conpletely

### ISSUE THREAD

**Issue by chevdor** [ethereum/solidity#3050]
I ran into an issue with this code:
```
mapping (bytes32 => RegEntry) public regMap;
struct RegEntry {
     address addr;
     mapping (bytes32 => bytes32) meta;
}
  
 function register(bytes32 _id, address _addr) public  payable 
	returns (bool) {
		// ...
		regMap[_id] = RegEntry(_addr);     // <---- ISSUE HERE
		Registered(_id, _addr);
		return true;
	}
  
  function getEntry(bytes32 _id) public constant 
	returns (address entry)  {
		return regMap[_id].addr;
	}
```

As a result of this code, getEntry(bytes32) would always return 0x0 whereas `regMap(bytes32) `would return the correct value. There is probably an issue already at that level as I would think that the 2 calls should be equivalent.

The issue in my code is that I did not pass all the fields of the struct.
To fix my code, the solution is:
`regMap[_id] = RegEntry({addr: _addr});`

Issuing a warning could help stop issues.

**Comment by chriseth** [comment]
Thanks for the issue, @chevdor !
I don't fully understand, is this related to the new SMT checker, or is it about (traditional) static analysis?
Also, I don't really see the issue here. Is `regMap[_id] = RegEntry(_addr);` not storing the struct properly? Since the `meta` member is a mapping, there is no way to supply it for a memory struct, i.e. you did actually supply all fields of the struct.

Is the issue in `getEntry` or in `register`? If `getEntry(x)` is not identical to `regMap(x)`, this sounds like a bug in the code generator.

**Comment by chevdor** [comment]
I also *thought* my code would be ok but if you test it you will see that `getEntry()` does not work as expected and never returns an address whereas `regMap()` (=using directly the mapping) does.

Specifically setting the struct with {addr: ...} however seems to behave differently and the issue I described above does not show up.

I think there are 2 points here:
- first I think there is an issue to fix
- if the issue is fixed, we can probably stop there
- if the issue is not fixed or cannot be, I would recommend throwing a warning if possible.

I forgot to mention btw but I tested initially with an old 0.4.15 and rebuild solidity from `develop` to ensure I was not seeing an old issue.

**Comment by chriseth** [comment]
Can you provide minimal example code (without `//...`) together with inputs and outputs that shows the issue?

**Comment by chevdor** [comment]
Yes, finishing something and I will provide a simple one as well as a deployed version. Give me a few minutes.

**Comment by chevdor** [comment]
I need to let my node run on another network for a while so I could not deploy yet on Kovan or test but that should show the issue:
```
pragma solidity ^0.4.17;

contract SampleReg {
	mapping (bytes32 => RegEntry) public regMap;			
	
	struct RegEntry {
		address addr;
		mapping (bytes32 => bytes32) meta;
	}
	
	// Call this function, query regMap(_id) and call getEntry(_id) 
	// - regMap => OK
	// - getEntry() => Not OK 
	function register1(bytes32 _id, address _addr) public {
		regMap[_id] = RegEntry(_addr);
	}

	// Call this function, query regMap(_id) and call getEntry(_id) 
	// - regMap => OK
	// - getEntry() =>  OK 
	function register2(bytes32 _id, address _addr) public {
		regMap[_id] = RegEntry({addr: _addr});
	}
	function getEntry(bytes32 _id) public constant returns (address entry)  {
		return regMap[_id].addr;
	}
}
```

**Comment by chriseth** [comment]
Sorry, I don't see the behaviour you are seeing. I tried remix with `_id = 1` and `_addr = 2`. All combinations returned `2`.

**Comment by chevdor** [comment]
I confirm, the sample I gave does NOT expose the issue...
I need to check with my original contract what can be on the way.

**Comment by axic** [comment]
@chevdor is this still a problem?

**Comment by chevdor** [comment]
Hi, I did not forget but it took me a while to find the contract.
Note for self: the contract is `kireg.sol`

I can no longer reproduce this issue although I have updated my solidity compiler a few times since october last year.
