### ISSUE TITLE
Should the compiler raise visibility warnings for constructor functions?

### ISSUE THREAD

**Issue by JohnAllen** [ethereum/solidity#3052]
I assume the visibility warnings are there to get developers thinking more about function visibilities to prevent future multi-sig-like hacks, etc.

Should there be one for constructor functions though?  I'm getting `No visibility specified` warnings in remix using `v0.4.17+commit.bdeb9e52.js` for all of my constructor functions.  I assume they can't be run more than once -- at deploy time and just searched the docs in case they can be, but didn't find anything.

**Comment by JohnAllen** [comment]
Just found out the hard way that various deployment options will throw unrelated errors if constructor functions are marked `internal`. So perhaps the warning should say that?  Will look in the source to see if this is a simple string change.

**Comment by axic** [comment]
The reason is explained in #2638 (also see #3132).

> various deployment options will throw unrelated errors if constructor functions are marked `internal`

Do you have examples for any of these?

I'm closing this as a duplicate now, but if you do find examples where unrelated errors surface, please do reopen or create new issues for those.
