### ISSUE TITLE
No exception ever raised

### ISSUE THREAD

**Issue by Deams51** [ethereum/solidity#3057]
Solidity documentation ([doc](http://solidity.readthedocs.io/en/develop/contracts.html)), present the following contract and comments: 
```
pragma solidity ^0.4.0;

contract Test {
    // This function is called for all messages sent to
    // this contract (there is no other function).
    // Sending Ether to this contract will cause an exception,
    // because the fallback function does not have the "payable"
    // modifier.
    function() { x = 1; }
    uint x;
}
```

After deployment on Rinkeby, as well as Ropsten, I initiated a few test transactions to the contract and to my surprise, all transactions were successful and no exception have been raised.

Compiler version: 0.4.17
Example of the contract on Rinkeby with an accepted transaction: [Rinkeby.Etherscan](https://rinkeby.etherscan.io/address/0xed47b8fdba2572f2d0e67fc0e0c2e4511f88ca93)

A few different exception situations were tested on other variations of the contract, and once again, none were raised.
Is there a trick to the testnets? Or am I missing something?

Byte code generated (and confirmed on etherscan):
```
60606040523415600e57600080fd5b604480601b6000396000f30060606040523415600e57600080fd5b60016000819055500000a165627a7a7230582040d23036c367ce2ac2ca5d45308cb53dc5827eb3a743efb98835338ead53aa620029
```

**Comment by GNSPS** [comment]
What version of the compiler did you use?

**Comment by Deams51** [comment]
@GNSPS it has been tested on 0.4.17

**Comment by chriseth** [comment]
A quick test in remix.ethereum.org shows that this is working as expected. How exactly did you call the fallback function?

**Comment by Deams51** [comment]
@chriseth I have tested on main net and JS VM and it does work as intended. The issue is only occurring on Ropsten and Rinkeby, thus making it hard to proof test a contract properly before main net deployment.

**Comment by chriseth** [comment]
@Deams51 ah I see! Then the tools you use are not yet prepared for the byzantium hard fork: "Failure" is flagged differently after byzantium and cannot be recognized by looking at the "gas used" anymore: https://ethereum.stackexchange.com/questions/28077/how-do-i-detect-a-failed-transaction-after-the-byzantium-fork-as-the-revert-opco

**Comment by Deams51** [comment]
@chriseth Interesting, thank you!
If I may abuse of your patience, would you know where I can keep myself up to date about such changes?

**Comment by chriseth** [comment]
I have to admit that we do not have a good place to inform about such things, but the go-ethereum and solidity release notes contain some information about it.

**Comment by Deams51** [comment]
Alright, thank you again. :)
