### ISSUE TITLE
memory allocation for 'bytes memory' when using 'new' is one word per byte

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#3064]
I'm assuming that this is not the intended behavior.

Solidity: `0.4.17+commit.bdeb9e52.Emscripten.clang`, as well as in `0.4.18-nightly.2017.10.10+commit.c35496bf.Emscripten.clang` (optimized and unoptimized)

```
contract C {
    
    uint constant WORD_SIZE = 32;
    
    function bytesAllocTest() pure {
        
        for(uint i = 0; i < 20; i++) {
            bytes memory bts0 = new bytes(i);
            bytes memory bts1 = new bytes(0);
            uint m0;
            uint m1;
            assembly {
                m0 := bts0
                m1 := bts1
            }
            assert((m1 - m0) / WORD_SIZE == 1 + i);
        }
    }
}
```

**Comment by chriseth** [comment]
Confirmed, will be fixed ASAP.

**Comment by axic** [comment]
`new bytes(i)` IMHO should allocate 32 (size field) + number of bytes. Calldata/storage encoding of course should pad it appropriately, however I do not think it would hurt (apart from gas cost) to align it to the word size.

**Comment by chriseth** [comment]
@axic after the fix the allocation for a byte array is always a multiple of 32.
