### ISSUE TITLE
lllc unable to parse JUMPDEST

### ISSUE THREAD

**Issue by winsvega** [ethereum/solidity#3066]
it was working before. now I get this error when generating the tests.

Parse error.
/home/wins/Ethereum/solidity/liblll/CodeFragment.h(59): Throw in function static void dev::eth::CodeFragment::error(const string&) [with T = dev::eth::InvalidName; std::__cxx11::string = std::__cxx11::basic_string<char>]
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InvalidName>
std::exception::what: Symbol not found: JUMPDEST
[dev::tag_comment*] = Symbol not found: JUMPDEST

/home/wins/Ethereum/cpp-ethereum/test/tools/libtesteth/TestHelper.cpp(292): error: in "GeneralStateTests/stRevertTest": The command 'lllc /tmp/9195-7c86-e461-6760' exited with 256 code.

**Comment by axic** [comment]
Can you post a code please?

`(jumpdest)` is not valid as LLL, but you can still emit one via `(asm JUMPDEST)`

**Comment by winsvega** [comment]
"code" : "create in init code on depth = 1024. account should not be created",
"code" : "{ (JUMPI 63 (EQ (SLOAD 0) 1023)) [[0]] (+ (SLOAD 0) 1) (CALL (GAS) 0xa000000000000000000000000000000000000000 0 0 0 0 0) (JUMPI 83 (LT (SLOAD 0) 1050)) (JUMPDEST) (MSTORE 0 0x600060006002f0) (CREATE 3 25 7) (JUMPDEST)}",

**Comment by axic** [comment]
That code looks fairly dangerous since LLL instructions provide no guarantees how they will be laid out (any padding in between, etc).

It should be rewritten as LLL assembly:
```
(asm 0 SLOAD 1023 EQ 63 JUMPI ...)
```

**Comment by axic** [comment]
Alternatively one could use `(if)`, `(switch)` or `(when)` to cater for the jumps:
```
(if (EQ (SLOAD 0) 1023) <true branch> <false branch>)
```

**Comment by winsvega** [comment]
this asm is not really clear when you read it. 
so you say { } is not safe to use?

**Comment by axic** [comment]
Using `jumpdest` and `jumpi` referring to locations is not very safe, should use higher level constructs or resort to assembly only.

**Comment by axic** [comment]
I haven't calculated offsets but assume that

`(JUMPI 63 (EQ (SLOAD 0) 1023)) [[0]] (+ (SLOAD 0) 1) (CALL (GAS) 0xa000000000000000000000000000000000000000 0 0 0 0 0) (JUMPI 83 (LT (SLOAD 0) 1050)) (JUMPDEST) (MSTORE 0 0x600060006002f0) (CREATE 3 25 7) (JUMPDEST)
`

is broken up as

```
(def 'create-contract { (MSTORE 0 0x600060006002f0) (CREATE 3 25 7) })
(if (EQ (SLOAD 0) 1023)
  (create-contract)
  {
    [[0]]
    (+ (SLOAD 0) 1)
    (CALL (GAS) 0xa000000000000000000000000000000000000000 0 0 0 0 0)
    (if (LT (SLOAD 0) 1050)
      {}
      ('create-contract))
  })
```

**Comment by axic** [comment]
If you want to avoid any work, you can replace `(JUMPDEST)` with `(asm JUMPDEST)` though that may or may not be correct with different versions of LLL.

**Comment by axic** [comment]
@winsvega @pirapira can we close this issue?

**Comment by pirapira** [comment]
I think it's up to @winsvega .

**Comment by winsvega** [comment]
so two options here. while JUMPDEST are exist in tests. 
1) rewrite tests without JUMPDEST
2) use lllc with JUMPDEST support

so if close this issue we need a new one

**Comment by axic** [comment]
As mentioned in https://github.com/ethereum/solidity/issues/3066#issuecomment-335768311 if there is no desire to use LLL properly, `(JUMPDEST)` can be replaced with `(asm JUMPDEST)`. However I must note that the way LLL is used in the tests is not how LLL should be used and as a result it may produce invalid output at any point of time.

**Comment by pirapira** [comment]
I think @winsvega and I just want a lisp-looking assembly.  Now it's clear that LLL is not assembly (`asm` keyword delimits LLL from assembly).  So @winsvega and I need to build a lisp-looking assembly.

**Comment by axic** [comment]
I was concerned for a while that the tests use LLL and may output random stuff and nobody notices :)

**Comment by winsvega** [comment]
most of the tests has expect sections which will check that results are correct. 
however an invalid lllc code might potentially produce expected result while not actually testing the test case.

**Comment by axic** [comment]
@winsvega can we close this issue?

**Comment by winsvega** [comment]
some tests still have this opcodes an should be rewritten. but that is another issue not for this repo.
https://github.com/ethereum/tests/issues/306
