### ISSUE TITLE
Build fail: "Unable to determine commit hash. Either compile from within git repository or supply a file called commit_hash.txt"

### ISSUE THREAD

**Issue by giacecco** [ethereum/solidity#3076]
Not clear if this is an issue or intentional. Trying to build 0.4.17 from source - not from the git repository - I get the error you see below, interrupting the _make_ stage. The problem does not happen if I actually create the ```commit_hash.txt``` as suggested. Perhaps you want to force the user to find the real commit hash, in case she downloaded the source code from a malicious source? Thanks.

```
# make
Scanning dependencies of target jsoncpp-project
[  0%] Creating directories for 'jsoncpp-project'
[  1%] Performing download step (download, verify and extract) for 'jsoncpp-project'
-- verifying file...
       file='/usr/local/src/solidity-0.4.17/deps/downloads/jsoncpp-1.7.7.tar.gz'
-- File already exists and hash match (skip download):
  file='/usr/local/src/solidity-0.4.17/deps/downloads/jsoncpp-1.7.7.tar.gz'
  SHA256='087640ebcf7fbcfe8e2717a0b9528fff89c52fcf69fa2a18cc2b538008098f97'
-- extracting...
     src='/usr/local/src/solidity-0.4.17/deps/downloads/jsoncpp-1.7.7.tar.gz'
     dst='/usr/local/src/solidity-0.4.17/build/deps/src/jsoncpp-project'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  1%] No patch step for 'jsoncpp-project'
[  2%] No update step for 'jsoncpp-project'
[  3%] Performing configure step for 'jsoncpp-project'
-- The C compiler identification is GNU 6.4.1
-- The CXX compiler identification is GNU 6.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- JsonCpp Version: 1.7.7
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/solidity-0.4.17/build/deps/src/jsoncpp-project-build
[  4%] Performing build step for 'jsoncpp-project'
Scanning dependencies of target jsoncpp_lib_static
[ 25%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
[ 50%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
[ 75%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_writer.cpp.o
[100%] Linking CXX static library libjsoncpp.a
[100%] Built target jsoncpp_lib_static
[  5%] Performing install step for 'jsoncpp-project'
[100%] Built target jsoncpp_lib_static
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/lib/libjsoncpp.a
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/allocator.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/assertions.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/autolink.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/config.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/features.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/forwards.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/json.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/reader.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/value.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/version.h
-- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/writer.h
[  6%] Completed 'jsoncpp-project'
[  6%] Built target jsoncpp-project
Scanning dependencies of target solidity_BuildInfo.h
CMake Error at cmake/scripts/buildinfo.cmake:52 (message):
  Unable to determine commit hash.  Either compile from within git repository
  or supply a file called commit_hash.txt


CMakeFiles/solidity_BuildInfo.h.dir/build.make:57: recipe for target 'CMakeFiles/solidity_BuildInfo.h' failed
make[2]: *** [CMakeFiles/solidity_BuildInfo.h] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/solidity_BuildInfo.h.dir/all' failed
make[1]: *** [CMakeFiles/solidity_BuildInfo.h.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
#
```

**Comment by chriseth** [comment]
The compiler version string includes a part of the commit hash, so you have to get it to cmake somehow. Either you build directly in the git repository or you use the archive attached to the release page: https://github.com/ethereum/solidity/releases/download/v0.4.17/solidity_0.4.17.tar.gz or you create a file called `commit_hash.txt` in the root of the source directory.

**Comment by chriseth** [comment]
About the potential attack: I don't think there is anything we can do if users compile software they download from somewhere else.

**Comment by giacecco** [comment]
Got it, not a security feature, just a way to be absolutely crystal clear with the user of the binary about what exact version she's using.

**Comment by 77liyan** [comment]
> Not clear if this is an issue or intentional. Trying to build 0.4.17 from source - not from the git repository - I get the error you see below, interrupting the _make_ stage. The problem does not happen if I actually create the `commit_hash.txt` as suggested. Perhaps you want to force the user to find the real commit hash, in case she downloaded the source code from a malicious source? Thanks.
> 
> ```
> # make
> Scanning dependencies of target jsoncpp-project
> [  0%] Creating directories for 'jsoncpp-project'
> [  1%] Performing download step (download, verify and extract) for 'jsoncpp-project'
> -- verifying file...
>        file='/usr/local/src/solidity-0.4.17/deps/downloads/jsoncpp-1.7.7.tar.gz'
> -- File already exists and hash match (skip download):
>   file='/usr/local/src/solidity-0.4.17/deps/downloads/jsoncpp-1.7.7.tar.gz'
>   SHA256='087640ebcf7fbcfe8e2717a0b9528fff89c52fcf69fa2a18cc2b538008098f97'
> -- extracting...
>      src='/usr/local/src/solidity-0.4.17/deps/downloads/jsoncpp-1.7.7.tar.gz'
>      dst='/usr/local/src/solidity-0.4.17/build/deps/src/jsoncpp-project'
> -- extracting... [tar xfz]
> -- extracting... [analysis]
> -- extracting... [rename]
> -- extracting... [clean up]
> -- extracting... done
> [  1%] No patch step for 'jsoncpp-project'
> [  2%] No update step for 'jsoncpp-project'
> [  3%] Performing configure step for 'jsoncpp-project'
> -- The C compiler identification is GNU 6.4.1
> -- The CXX compiler identification is GNU 6.4.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- JsonCpp Version: 1.7.7
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /usr/local/src/solidity-0.4.17/build/deps/src/jsoncpp-project-build
> [  4%] Performing build step for 'jsoncpp-project'
> Scanning dependencies of target jsoncpp_lib_static
> [ 25%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
> [ 50%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
> [ 75%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_writer.cpp.o
> [100%] Linking CXX static library libjsoncpp.a
> [100%] Built target jsoncpp_lib_static
> [  5%] Performing install step for 'jsoncpp-project'
> [100%] Built target jsoncpp_lib_static
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/lib/libjsoncpp.a
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/allocator.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/assertions.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/autolink.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/config.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/features.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/forwards.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/json.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/reader.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/value.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/version.h
> -- Installing: /usr/local/src/solidity-0.4.17/build/deps/include/json/writer.h
> [  6%] Completed 'jsoncpp-project'
> [  6%] Built target jsoncpp-project
> Scanning dependencies of target solidity_BuildInfo.h
> CMake Error at cmake/scripts/buildinfo.cmake:52 (message):
>   Unable to determine commit hash.  Either compile from within git repository
>   or supply a file called commit_hash.txt
> 
> 
> CMakeFiles/solidity_BuildInfo.h.dir/build.make:57: recipe for target 'CMakeFiles/solidity_BuildInfo.h' failed
> make[2]: *** [CMakeFiles/solidity_BuildInfo.h] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/solidity_BuildInfo.h.dir/all' failed
> make[1]: *** [CMakeFiles/solidity_BuildInfo.h.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> #
> ```

I met the same problem, how to solve

**Comment by chriseth** [comment]
@77liyan Did you follow the instructions here https://github.com/ethereum/solidity/issues/3076#issuecomment-336503636 ?

**Comment by b17wise** [comment]
Same issue here:
I am building from tarball. Why it asking for a commit_hash?
https://cloud.drone.io/alpinelinux/aports/8293/

[Alpine Linux build]( https://github.com/b17wise/aports/blob/master/testing/solidity/APKBUILD)

**Comment by chriseth** [comment]
The commit hash is used to have a proper version number. Please use the archive that is provided as an artefact in the release.

**Comment by philtruing** [comment]
> The compiler version string includes a part of the commit hash, so you have to get it to cmake somehow. Either you build directly in the git repository or you use the archive attached to the release page: https://github.com/ethereum/solidity/releases/download/v0.4.17/solidity_0.4.17.tar.gz or you create a file called `commit_hash.txt` in the root of the source directory.

how to  create a file called `commit_hash.txt` in the root of the source directory? I mean where is the root of the source diretory
