### ISSUE TITLE
visual-studio +solidity smart contract deployment issue

### ISSUE THREAD

**Issue by divz1010** [ethereum/solidity#3080]
i am expensing the following issue Deployment to http://localhost:8001/ started! User used for deployment: testuser User found: 0d97173dc52b4d8b2c1034228b129c6d763160eb Contract Payout created successfully at address error uploading contract Contract can be accessed here: http://localhost:8001/contracts/Payout/error uploading contract.html (default password: testing) Anyone please help me to resolve this

**Comment by axic** [comment]
This seems to be something unrelated to solidity. Please open the issue on the framework you are using.

**Comment by mamohanc** [comment]
@divz1010 Did you happen to resolve it. Please let me know
