### ISSUE TITLE
visual studio + solidity +deployment issue

### ISSUE THREAD

**Issue by divz1010** [ethereum/solidity#3081]
I have installed a local deployment via docker of Strato Management.
I am trying to setup the BlockApp to deploy custom contracts from Visual Studios:

prompt: Enter the name of your app: TestApp
prompt: Enter your name: test user
prompt: Enter your email so BlockApps can reach you:
prompt: apiURL: (http://strato-dev4.blockapps.net2) http://localhost1
prompt: Enter the blockchain profile you wish to use. Options: strato-dev, ethereum: (strato-dev) ethereum

I’m not sure what I should put for the blockchain profile.

I can then do bloc start and the server runs, but when I deploy sample code from VS I get the following:

PS C:\Users\Chris Mills\source\TestApp> bloc start
bloc is listening on http://0.0.0.0:8000
api is pointed to http://localhost1 with profile ethereum
GET /users/ 200 23.899 ms - 2
body: {“password”:“testing”,“faucet”:“1”}
hitting faucet for ec68289242f8064f5d79da6226a570d3224e1a1a
wrote: app\users\testuser\ec68289242f8064f5d79da6226a570d3224e
POST /users/testuser 200 214.521 ms - 40
GET /users/ 200 8.997 ms - 12
GET /users/testuser 200 4.523 ms - 44
contract as body is: undefined
constructor arguments: undefined
data is: ec68289242f8064f5d79da6226a570d3224e1a1a
About to upload contract
compile failed with error message: TypeError: Cannot convert u
caught a single contract
POST /users/testuser/ec68289242f8064f5d79da6226a570d3224e1a1a/
extension was matched: html

Then the service crashes and I have to restart it. Is there something I’m doing wrong here?
please let me know
how I can resolve this

**Comment by axic** [comment]
This seems to be unrelated to Solidity. Please open an issue on the framework you are using.
