### ISSUE TITLE
Mist 0.9.2 Compile issue re-occurrence of - This declaration shadows an existing declaration

### ISSUE THREAD

**Issue by acgoldfish** [ethereum/solidity#3084]
Mist 0.9.2 Compile issue re-occurrence of - This declaration shadows an existing declaration

System information
Mist Version : 0.9.2
Geth version: geth version 1.7.2
OS & Version: Windows 10

Expected behaviour

Deploy the crowdsale contract in the Ethereum wallet. EC20 ICO Crowdsale The code is pragma solidity ^0.4.16.

**Actual behaviour**

It won't. It says: Could not compile source code. And then the error stated below this text. 

Backtrace

Could not compile source code. 

 This declaration shadows an existing declaration.
    event NewLockedTok(address lockedTokens);
                                        ^------------------^

**Comment by axic** [comment]
This is actually tracked in https://github.com/ethereum/mist/issues/2797. The above is a warning not an error.

Until that issue is solved, you can opt to rename your event not to conflict with another declaration (as the message says).
