### ISSUE TITLE
 Bad instruction fd

### ISSUE THREAD

**Issue by akshay951228** [ethereum/solidity#3093]
solidity gives this error **Encountered error on making system call: Bad instruction fd**
smart contract link https://github.com/paritytech/contracts/blob/master/validator_contracts/TestList.sol

**Comment by axic** [comment]
Please provide a bit more detail, such as the compiler version, the environment (IDE, tools, etc), your OS, etc.

**Comment by akshay951228** [comment]
I taken the bitecode code from **remix** onlline ide and deployed this contract in parity 1.7.0 node.

**Comment by axic** [comment]
That would mean the error is shown by Parity and should be reported to Parity then.

**Comment by akshay951228** [comment]
**they said open a issue on solidity**

**Comment by axic** [comment]
Can you add a pointer to the issue?

**Comment by benjamincburns** [comment]
I think 0xfd is `REVERT`, as I ran across similar output while pumping some problematic bytecode through https://etherscan.io/opcode-tool

Also [this](https://github.com/ethereum/solidity/blob/c61610302aa2bfa029715b534719d25fe3949059/libevmasm/Instruction.h#L195).

Chances are Parity 1.7.0 doesn't support this new opcode.

**Comment by axic** [comment]
@akshay951228 please add a pointer to the report to Parity.

**Comment by axic** [comment]
Please reopen if issue persists. It doesn't seem like a Solidity issue.
