### ISSUE TITLE
Constant function analysis tool issues warning for functions with selfdestruct

### ISSUE THREAD

**Issue by KPull** [ethereum/solidity#3094]
The "possible `constant`/`view` function" warning gives a warning:

```
GuessTheNumberGame.collectOperatorWinnings(): Potentially should be constant but is not. 
Note: Modifiers are currently not considered by this static analysis.
```

The code in question is: https://github.com/KPull/eth-guess-the-number-game/blob/master/GuessTheNumberGame.sol#L92-L94. As you can see the function only contains the `selfdestruct` operation.

`selfdestruct` changes the state of the blockchain so I think the warning, given by the analyzer, is not correct.

I am using Solidity compiler version `0.4.17-nightly.2017.9.21+commit.725b4fc2.Emscripten.clang` through Remix IDE.

**Comment by axic** [comment]
This is actually a problem in Remix, since the static analyzer is part of Remix and as such generally should be reported to https://github.com/ethereum/browser-solidity.

@soad003 would this be an easy thing to fix?

**Comment by axic** [comment]
Actually, this module could be retired since the functionality now is provided by the compiler, but in any case the rules should be copied from: https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/ViewPureChecker.cpp

**Comment by soad003** [comment]
@axic this particular problem should be easy to fix, but if the functionality is now provided by the compiler we probably should not maintain it twice. Do you want me to delete the module?

**Comment by chriseth** [comment]
Hm, it is still useful for older compilers and you can always disable individual modules in remix.

**Comment by soad003** [comment]
@chriseth ok, the problem here is that i did not consider selfdestruct as a change of state (we had the same discussion with new). I can add it to the module if that is a solution for you.
Model the exact same rules as in viewPureChecker would be way more work. 
Maybe we should introduce something like compiler version dependent static analysis modules for such purposes...

**Comment by axic** [comment]
I'd just turn it off by default. Users of old compiler could turn it back, but Remix always uses the latest one anyway. Is that an option?

**Comment by chriseth** [comment]
As this does not concern solidity, I'm closing this issue.
