### ISSUE TITLE
Issue that links to other issues about tests

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#3102]
This issue links to open issues concerning missing tests, if someone wants an overview. 

- CLI: https://github.com/ethereum/solidity/issues/3035
- Source location, AST: https://github.com/ethereum/solidity/issues/2987
- AST JSON: https://github.com/ethereum/solidity/issues/2796
- libevmasm: https://github.com/ethereum/solidity/issues/1275

Other issues related to testing:

- Run tests with Geth as well: https://github.com/ethereum/solidity/issues/2626
- Change precompiles vector: https://github.com/ethereum/solidity/issues/2508
- No bytecodecompare after failed tests: https://github.com/ethereum/solidity/issues/2300
- Handle accounts locally in soltest: https://github.com/ethereum/solidity/issues/2169

**Comment by axic** [comment]
Created a [label](https://github.com/ethereum/solidity/labels/testing%20%3Ahammer%3A), that should be ok to track them. Closing this.

Thanks for collecting them though!
