### ISSUE TITLE
Allow comparing large rational numbers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3116]
```
contract C {
  bool x = 2**700 > 2**600;
}
```
currently fails with

```
Error: Operator > not compatible with types int_const 5260...(203 digits omitted)...1376 and int_const 4149...(173 digits omitted)...5376
 --> 3116.sol:2:12:
  |
2 |   bool x = 2**700 > 2**600;
  |            ^^^^^^^^^^^^^^^
```

Admittedly it is a not very useful/frequent use case.

**Comment by Balajiganapathi** [comment]
How to do this? Per my understanding, this fails because when getting the integerType of the RationalNumberType, it returns empty as number of bits needed is greater than 256. This happens because we are converting both sides to mobile types before comparing.

**Comment by axic** [comment]
I'd argue it's not worth spending much effort on this case unless a good use case can be presented.

**Comment by hrkrshnn** [comment]
I would expect the value of `b` in `bool b = 2**256 > 2**256 - 1` to be `false` because of the `mod 2**256` arithmetic. The proposal would make the value of `b` to be `true.` Perhaps this is confusing.

**Comment by chriseth** [comment]
Constants do not have the `mod 2**256` arithmetic. You can do `2**5000 / 2**5000` and will get 1

**Comment by hrkrshnn** [comment]
What I meant is that for `+, -` and `*`, any expression of constants with these operations would evaluate to the same value in both arbitrary precision arithmetic and `mod 2**256` arithmetic (provided that the evaluated value is fits in 256 bits.) Division may be an exception here (It is true for `a/b` under certain conditions for `b`.) So the above change goes against the intutiion.
