### ISSUE TITLE
Another SMTChecker bug

### ISSUE THREAD

**Issue by joeykrug** [ethereum/solidity#3121]
```
solc Controller.sol
Internal compiler error during compilation:
```

That's all it says, I get it when running it on Controller.sol here https://github.com/AugurProject/augur-core/tree/develop/source/contracts

When removing the smt checker pragma it compiles fine :/

Sidenote: the Augur contracts are probably a good benchmark for running the SMTChecker / new solidity compiler versions against as they're complex and use a lot of varied functionality

**Comment by axic** [comment]
@joeykrug can you run it #2993 applied?

**Comment by joeykrug** [comment]
Just tried it, still gives the same issue

**Comment by axic** [comment]
Can you copy in the entire error message? (It should have text after "Internal compiler error")

**Comment by joeykrug** [comment]
Unfortunately it doesn’t have any text after that, which is frustrating

**Comment by chriseth** [comment]
Slightly unrelated: @joeykrug is there an "easy" way to run the augur smart contract tests? We are running some external project's tests against each pull request and as you say, your contract would be another good candidate, I guess. Running them against the SMT checker is probably a little too early, though.

**Comment by axic** [comment]
@joeykrug are you using a native `solc` binary? There must be text after it.

**Comment by joeykrug** [comment]
@axic, I compiled it locally, yeah. There's no text. There's also no text when I use the apt-get install solc binary version either.

**Comment by joeykrug** [comment]
@chriseth Sure, 

```
git clone https://github.com/AugurProject/augur-core.git
npm install
pip install -r requirements.txt
cd tests
pytest -vv
```

will run the tests on all the contracts.

**Comment by axic** [comment]
This won't be very helpful for testing:

```
IController.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.19-develop.2017.10.23+commit.a4fa4e07.mod.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.17;
^---------------------^
```

How do you actually run your SMT tests?

**Comment by joeykrug** [comment]
Oh, on my local version I found / replaced `pragma solidity 0.4.17;` with `pragma solidity ^0.4.17;`

**Comment by axic** [comment]
And which file(s) do you add the smtchecker pragma?

**Comment by axic** [comment]
Adding the pragma only to Controller results in:

```
$ solc Controller.sol 
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/formal/SMTChecker.cpp(527): Throw in function smt::Expression dev::solidity::SMTChecker::currentValue(const dev::solidity::Declaration &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

**Comment by chriseth** [comment]
I think the problem above is already fixed in the upcoming pull request.

**Comment by axic** [comment]
It doesn't according to https://github.com/ethereum/solidity/issues/3121#issuecomment-338521285 - also tried it myself now:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/formal/SMTChecker.cpp(656): Throw in function smt::Expression dev::solidity::SMTChecker::currentValue(const dev::solidity::Declaration &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

**Comment by chriseth** [comment]
Ah ok, sorry then. Will take a look after devcon.

**Comment by joeykrug** [comment]
> And which file(s) do you add the smtchecker pragma?

Controller, IController, IControlled

**Comment by axic** [comment]
Seems to be worked with 0.4.19.
