### ISSUE TITLE
Optimiser: remove conditional jump to next

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3123]
> In some situations, we end up having
>
> PushTag 4
> JUMPI
> Tag 4:
>
> This can be simplified to
> POP
> 
> Remarks for implementation: As the code is now (August 2015), this can neither be implemented in ControlFlowGraph (because it cannot modify items) nor in CommonSubexpressionEliminator (because it cannot look ahead), so we have to use a new stage. It should not be implemented by a sliding window optimizer because then we cannot detect cases where the tag is DUPed from somewhere else.

(from https://www.pivotaltracker.com/story/show/96789744)

**Comment by chriseth** [comment]
I'm pretty sure this is implemented in the peephole optimizer.

**Comment by axic** [comment]
This is implemented https://github.com/ethereum/solidity/blob/develop/libevmasm/PeepholeOptimiser.cpp#L157-L181
