### ISSUE TITLE
Optimiser: Do not store in memory if not needed anymore

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3124]
> If the current block ends with the EVM terminating (STOP, RETURN, ...), avoid memory writes if we can infer that the memory is not accessed anymore.

(from https://www.pivotaltracker.com/story/show/93191202)

**Comment by axic** [comment]
Okay, this could be done for `STOP`, `RETURN`, `REVERT`, `INVALID`, `SELFDESTRUCT`.

**Comment by axic** [comment]
@chriseth is this still relevant? The yul optimizer should do this already.

**Comment by chriseth** [comment]
Not at all. The optimizer does not even remove redundant stores.
