### ISSUE TITLE
One-method contracts

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3125]
Support one-method contracts:

```
contract OneMethod {
  OneMethod() {
    m_value = 1;
  }
  function default(uint _x) returns (uint _r)
  {
    _r = _x + m_value;
  }
  uint m_value;
}
```

Would do the same as:
```
contract OneMethod {
  OneMethod() {
    m_value = 1;
  }
  function foo(uint _x) returns (uint _r)
  {
    _r = _x + m_value;
  }
  uint m_value;
}
```

except that the first four bytes that would normally switch between the methods would not be expected to exist for this contract type's ABI.

Calling into it would happen like a function: `OneMethod(addr)(65)` would yield `65 + the m_value`.

It is not allowed to inherit multi-function (standard) contracts.

It may be inherited by a multi-function (standard) contract, however, a method name must be given into which the single-function's code be placed: `contract StandardContract extends OneMethod as foo`

(from https://www.pivotaltracker.com/story/show/86479016)

**Comment by axic** [comment]
@chriseth what is the point of this?

**Comment by chriseth** [comment]
I have no idea. Someone else created this story. Fine with closing this.
