### ISSUE TITLE
SMT Solver: Add modifer post-assertions as postconditions for functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3138]
When storage variables are tracked by the SMT solver, they have to be set to "unknown" after each non-view function call (even internal function call) because we currently do not know what that function will do. We can add a little insight by at least searching for modifiers without arguments and adding all assertions that appear after the `_` to the constraint set.

**Comment by fincrypchain001** [comment]
Closes

**Comment by leonardoalt** [comment]
Don't think we're going to do that.
