### ISSUE TITLE
[feature]  Canonical sources, viewing "expanded" form of derived contracts

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#314]
It would be neat if given this:

```
contract A {
    uint stuff;
    function f1();
}
contract B is A {
    function f2();
}
```

I could see:

```
contract B_expanded {
    uint stuff;
    function f1();
    function f2();
}
```

Is this possible without renaming members? IE can you use a name that's protected/private somewhere in your inheritance graph?

In any case, do you think it would be straightforward to create a canonical human-readable form for any AST or no?

**Comment by chriseth** [comment]
The compiler can output the ast, which is human-readable (might depend on the human), using `solc --ast <filename.sol>`.
Members in base classes (especially private) can be shadowed by members in derived classes, so it is not possible without renaming. Furthermore, this feature rather belongs into an IDE, in my opinion.
