### ISSUE TITLE
LLL: the bitwise shift macros after EIP-145 is implemented

### ISSUE THREAD

**Issue by benjaminion** [ethereum/solidity#3141]
@axic @zigguratt 

Just kicking off a discussion about this ahead of time. [EIP-145](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md) will introduce native `shl` and `shr` EVM opcodes, which is long overdue. This is slated for the Constantinople fork.

The issue for LLL is that there currently exist compiler macros for `shl` and `shr` introduced in #2394.  Unfortunately, the order of the operands to the LLL macros is inverted with respect to order of the operands in EIP-145.

I think there are a couple of options for handling this in LLL.

1. Remove the compiler macros entirely. This will allow LLL to recognise the new `shl` and `shr` EVM operators natively.
    - Pro: clean, intuitive.
    - Con: may break a proportion of existing LLL  code.

2. The current macros will take precedence over the EVM opcodes, so update the macro bodies to invert the operands before passing them to the native EVM versions of `shl`, `shr`. E.g. `(def 'shl (val shift) (shl shift val))`.
    - Pro: doesn't break existing code; no performance penalty.
    - Con: confuses anyone who is unaware of this inversion and believes they are using the native opcodes in their code.

Given that the amount of LLL code created between the introduction of these macros and the deployment of this EIP is likely to be relatively small, I'd slightly favour option 1.  Historically, breaking changes to LLL have not been uncommon. It's possible that I am the only person who has used these macros :-)

Anyway, opening for discussion.

**Comment by axic** [comment]
Removing them or swapping the operands are both breaking changes, though we haven't so far paid much attention to breaking changes, partially due to the fact LLL has no releases :)

I don't particularly like that people are using builtin functions and inline assembly interchangeably. A good actual step forward could be defining builtin functions (aka functions exposing underlying opcodes). In that case `shl` as it is could remain, because in a higher level language the operand order `val, shift amount` seems more logical.

**Comment by benjaminion** [comment]
> A good actual step forward could be defining builtin functions (aka functions exposing underlying opcodes).

Actually, I like this. For example, opcode expressions could be required to be capitalised: `SHL` vs. `shl`. The parser is already case-sensitive, so the following results in neither `0` nor `10`, but `3`:

    (returnlll (seq (def 'add (a b) 0) (return (+ (ADD 1 2) (add 3 4)))))  => 3

I think this would be easy to implement, maybe just one change in *CodeFragment.cpp*, `validAssemblyInstruction()`.

It would, however, be **very** breaking. I'm completely OK with that, but it might mess up, say, the exisiting body of Ethereum client tests.

Perhaps a compiler flag:
  * default: EVM opcodes must be capitalised when used in LLL.
  * with flag: the compiler behaves as now, either by relaxing the new check in `validAssemblyInstruction()` or by automatically including a set of macros `(def 'add (a b) (ADD a b))` etc.

@zigguratt  - any thoughts?
