### ISSUE TITLE
grammar.txt: unknown assembly 'for' construct

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#3146]
(I am currently trying to verify my Solidity LALR Parser project [syparse](https://github.com/walter-weinmann/syparse) with the examples in the [Solidity  documentation](https://github.com/ethereum/solidity/tree/develop/docs).)

The following example is taken from chapter `Inline Assembly (second example)` in document `assembly.rst`:
```
    pragma solidity ^0.4.12;

    library VectorSum {
        // This function is less efficient because the optimizer currently fails to
        // remove the bounds checks in array access.
        function sumSolidity(uint[] _data) returns (uint o_sum) {
            for (uint i = 0; i < _data.length; ++i)
                o_sum += _data[i];
        }

        // We know that we only access the array in bounds, so we can avoid the check.
        // 0x20 needs to be added to an array because the first slot contains the
        // array length.
        function sumAsm(uint[] _data) returns (uint o_sum) {
            for (uint i = 0; i < _data.length; ++i) {
                assembly {
                    o_sum := add(o_sum, mload(add(add(_data, 0x20), mul(i, 0x20))))
                }
            }
        }

        // Same as above, but accomplish the entire code within inline assembly.
        function sumPureAsm(uint[] _data) returns (uint o_sum) {
            assembly {
               // Load the length (first 32 bytes)
               let len := mload(_data)

               // Skip over the length field.
               //
               // Keep temporary variable so it can be incremented in place.
               //
               // NOTE: incrementing _data would result in an unusable
               //       _data variable after this assembly block
               let data := add(_data, 0x20)

               // Iterate until the bound is not met.
               for
                   { let end := add(data, len) }
                   lt(data, end)
                   { data := add(data, 0x20) }
               {
                   o_sum := add(o_sum, mload(data))
               }
            }
        }
    }

```
The for construct is neither covered by the `ForStatement` rule nor by the `UsingForDeclaration` rule.

**Comment by federicobond** [comment]
Hi @walter-weinmann, you mean the for construct inside the assembly block? Have you checked the docs [here](https://github.com/ethereum/solidity/blob/develop/docs/assembly.rst#parsing--grammar)? You can take a look at my [ANTLR4 grammar](https://github.com/solidityj/solidity-antlr4/blob/c37c042/Solidity.g4#L328-L330) too.

**Comment by walter-weinmann** [comment]
I've been trying to write a parser for the programming language Erlang based on grammar. txt for some time now - unfortunately grammar. txt doesn't seem to be a good basis for this project. I'm really looking forward to #3158.

**Comment by federicobond** [comment]
Not being testable, it's hard to keep `grammar.txt` updated and free of bugs. The ANTLR4 grammar I linked above, on the other hand, should serve your needs pretty well. It parses every Solidity code I have seen in the wild.
