### ISSUE TITLE
grammar.txt: missing rule for 'AssemblyAssignment'

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#3148]
(I am currently trying to verify my Solidity LALR Parser project [syparse](https://github.com/walter-weinmann/syparse) with the examples in the [Solidity  documentation](https://github.com/ethereum/solidity/tree/develop/docs).)

The following example is taken from chapter `Inline Assembly (Declaring Assembly-Local Variables)` in document `assembly.rst`:
```
    pragma solidity ^0.4.0;
    contract C {
        function f(uint x) returns (uint b) {
            assembly {
                let v := add(x, 1)
                mstore(0x80, v)
                {
                    let y := add(sload(v), 1)
                    b := y
                } // y is "deallocated" here
                b := add(b, v)
            } // v is "deallocated" here
        }
    }
```
The existing grammar rule
`AssemblyAssignment = ( Identifier ':=' FunctionalAssemblyExpression ) | ( '=:' Identifier )`
does not cover an expression like
`Identifier ':=' Identifier`.

**Comment by federicobond** [comment]
Yes, the docs should be updated. You can find a better version of the assignment rule [here](https://github.com/solidityj/solidity-antlr4/blob/c37c042/Solidity.g4#L299-L300).
