### ISSUE TITLE
ABI file should contain a "name" field for the constructor type

### ISSUE THREAD

**Issue by tjayrush** [ethereum/solidity#3153]
An ABI file contains items defining each object type: `function`, `event`, `fallback`, and `constructor`.

The `fallback` function, obviously, doesn't have a name (since the fallback is a function with no name).

The `function` and `event` types have a JSON field called name. This makes it easy to write code to automatically parse the input data of a transaction (as we do with QuickBlocks's **grabABI** program).

For some reason, the `constructor` has no name even though it's clearly there in the source code (i.e. and it actually carries the name of the smart contract).

If a `name` field existed in the ABI file, one could write code to grab an ABI from a smart contract from somewhere (Etherscan, ENS, wherever) and one would know the contract's name. As it is, if one wants that information, one must look outside the ABI file.

Suggestion: add a name field to the constructor object in an ABI using the name of the smart contract for use in various tools.

**Comment by axic** [comment]
The reason for this is the ABI is describing all the information needed for encoding/decoding data according to the ABI. The name of the constructor is not needed at all.

Please note the ABI doesn't necessarily describe a given contract, but a subset of the interface such contract supports.

I can see the point of putting the name into the ABI in the short term, but I have a feeling in the long term that might not be the best choice. Have you seen the metadata the compiler outputs?

Can you also explain the uses cases where the name for the constructor in the ABI would help?

**Comment by chriseth** [comment]
Also note that the fact that the constructor is named the same way as the contract is a specific choice of Solidity. The ABI is supported by many more languages and not all of them tag the constructor this way.

**Comment by tjayrush** [comment]
I come at everything I do from the direction of a "forensic accountant." By this, I mean trying to account for or audit the transactions on a contract with nothing but an Ethereum address.

The ABI faces in two directions. It faces into the EVM, and I understand that here it would serve little purpose, but it also faces out to the world. It's this second case I was thinking of.

If I have only an address, I'm hoping someday to ask ENS (or Etherscan if I must) for an ABI (if there is one), and if there's a name there, I get a little bit more information than I would otherwise.

I always forget that Solidity is not the only game in town, but this is the solidity repo. Would adding a name field to the constructor's ABI break other languages in some way? (Does anyone know what percentage of contracts are written in Solidty?)

Plus--the name is already there, so it seems trivial to include it. Minimal work. Greater than zero benefit. May I kindly ask what the downsides might be?

**Comment by axic** [comment]
For downsides, see my questions above. If Solidity adds a new field to the ABI, that puts a pressure on the ecosystem to also add that field in other languages, where it may or may not make sense.

I am not entirely sure the best way to understand what a contract at a specific address does is solely by the ABI, but rather more data points would be helpful. Please have a look at the contract metadata: https://solidity.readthedocs.io/en/develop/metadata.html

**Comment by tjayrush** [comment]
Got it. I think the metadata serves my purpose. Thanks. Sorry for the newbie question: should I close this or will you?
