### ISSUE TITLE
Require/Assert should allow a message as an additional argument

### ISSUE THREAD

**Issue by subramanianv** [ethereum/solidity#3154]
Currently in Solidity, if there are multiple require/assert statements. You would not know which require/assert statement caused the exception. It would be super useful if the require/assert statements take into a message as an argument.

for example something similar to this.
`require(a>5, "Error Message: Caused by a>5");`
   or
`assert(a>5, "Error message: Caused by a>5");`

**Comment by axic** [comment]
This is tracked in #1686.
