### ISSUE TITLE
grammar.txt: missing rule ExpressionList or IdentifierList

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#3156]
(I am currently trying to verify my Solidity LALR Parser project [syparse](https://github.com/walter-weinmann/syparse) with the examples in the [Solidity  documentation](https://github.com/ethereum/solidity/tree/develop/docs).)

The following example is taken from chapter `Assignment (Destructuring Assignments and Returning Multiple Values)` in document `control-structure.rst`:
```
    pragma solidity ^0.4.0;
    contract C {
        uint[] data;
        function f() returns (uint, bool, uint) {
            return (7, true, 2);
        }
        function g() {
            // Declares and assigns the variables. Specifying the type explicitly is not possible.
            var (x, b, y) = f();
            // Assigns to a pre-existing variable.
            (x, y) = (2, 7);
            // Common trick to swap values -- does not work for non-value storage types.
            (x, y) = (y, x);
            // Components can be left out (also for variable declarations).
            // If the tuple ends in an empty component,
            // the rest of the values are discarded.
            (data.length,) = f(); // Sets the length to 7
            // The same can be done on the left side.
            (,data[3]) = f(); // Sets data[3] to 2
            // Components can only be left out at the left-hand-side of assignments, with
            // one exception:
            (x,) = (1,);
            // (1,) is the only way to specify a 1-component tuple, because (1) is
            // equivalent to 1.
        }
    }
```
Round brackets including leading or trailing commas are only allowed with an `IdentifierList`:
`IdentifierList = '(' ( Identifier? ',' )* Identifier? ')'`
Hence the following expressions are not covered by `grammar.txt`:
```
            (data.length,) = f(); // Sets the length to 7

            (,data[3]) = f(); // Sets data[3] to 2

            (x,) = (1,);
```

**Comment by axic** [comment]
It seems that leading comma is covered ((`Identifier? ',')*`), but trailing one isn't.

I think the rule should be
```
'(' ( Identifier? ','?)+ ')'
```

if `+` (meaning at least once) is not available then:
```
'(' ( Identifier? ',' )* (Identifier ','?)? ')'
```

**Comment by walter-weinmann** [comment]
In my  opinion leading and trailing commas in an `IdentifierList `are covered, but here the problems are:

1. `data.length` is not an Identifier 
2. `date[3]` is not an Identifier
3. it should be `var (x,) = (1,);`

**Comment by axic** [comment]
Sorry, you are correct, the grammar expression seems to be ok.

1. and 2. it actually takes an expression (which must be valid as an lvalue) and not an identifier
3. is fine, because `x` is already declared in the first expression of the function (`var (x,b,y)`)

**Comment by walter-weinmann** [comment]
The only rule which allows leading or trailing commas in a round bracket is
`IdentifierList = '(' ( Identifier? ',' )* Identifier? ')'`
Now `IdentifierList` is only allowed in rule `VariableDefinition`:
`VariableDefinition = ('var' IdentifierList | VariableDeclaration) ( '=' Expression )?`
But then the VariableDefinition has to start with the keyword `var`.

My guess was that the three statements should all be of `VariableDefinition` type - but I think they are violating the defined rules in `grammar.txt`.
