### ISSUE TITLE
Include a BNF parser generator capable of using grammar.txt and run all examples from tests/docs on it

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3158]

**Comment by federicobond** [comment]
grammar.txt in its current state is not formal enough to be used as input to a parser generator, but feel free to use my own ANTLR4 grammar to do it.

**Comment by erak** [comment]
Would it be feasible to use [Pest](https://github.com/pest-parser/pest) for this?

**Comment by axic** [comment]
I suppose but not sure how many languages we want to mix into the repo. C, C++, Python, Javascript are already present :)

**Comment by axic** [comment]
Accomplished by #8482
