### ISSUE TITLE
struts data to json data

### ISSUE THREAD

**Issue by dreamer-zq** [ethereum/solidity#3160]
How do I convert struts data to json data，example: 
struts {
        uint id;
        address def
        string cd; //service code (unique)
        string def_type; // service definition type
        string auth; //
        string github; //github address
        uint createtime; //
}
do someone has some good ideas?

**Comment by limexp** [comment]
@zhiqiang-bianjie 
You have fixed structure, so calculate json string length (sum lengths of names, delimiters and values). Be aware of special characters in string values.
Then allocate a new string (Array) and copy or encode values into it. 
Without optimization everything is very straightforward.

**Comment by dreamer-zq** [comment]
ok,i got it.thanks
