### ISSUE TITLE
Calculate the position of mapping value

### ISSUE THREAD

**Issue by gaoxiangxyz** [ethereum/solidity#3161]
I try to write codes as below to calculate the position of value of mapping ( `keccak256(k . p)` ) described at [Layout of State Variables in Storage](https://solidity.readthedocs.io/en/develop/miscellaneous.html#layout-of-state-variables-in-storage).
But both results are different with position show in debugger.
Could you point what mistake I make?
Thanks.

` byte32 pos = keccak256(uint256(k),'.',uint256(p));`
and 
```
        bytes memory byteArr = new bytes(32 + 1 +32);
        bytes32 bytesK = bytes32(uint256(k));
        for (uint i = 0; i < 32; i++) {
            byteArr[i] = bytesK[i];
        }
        byteArr[32] = byte('.');
        bytes32 bytesP = bytes32(uint256(p));
        for (uint j = 0; j < 32; j++) {
            byteArr[33 + j] = bytesP[j];
        }
        byte32 pos = keccak256(byteArr);
```

**Comment by limexp** [comment]
@gaoxiangxyz 
Dot ('.') is a concatenation operator. Omit it from formula.

>  located at keccak256(k . p) where **.** is concatenation
