### ISSUE TITLE
brew linkapps deprecated

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/solidity#3162]
brew linkapps solidity
Warning: `brew linkapps` has been deprecated and will eventually be removed!

Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
bundles that can be relocated. Instead, please consider using `brew cask` and
migrate formulae using `.app`s to casks.

From: http://solidity.readthedocs.io/en/develop/installing-solidity.html

**Comment by glaksmono** [comment]
@quantumproducer do you have any luck on this? I'm also experiencing the same problem

**Comment by baezor** [comment]
Same problem:

Warning: Calling 'brew linkapps' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cmd/linkapps.rb:18:in `linkapps'

**Comment by eduardocruz** [comment]
Same here

```
Warning: Calling 'brew linkapps' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cmd/linkapps.rb:18:in `linkapps'
```

**Comment by axic** [comment]
I don't think actually `linkapps` makes sense for solidity. Why would anyone need `/Applications/solidity.app`? It cannot be meaningfully run anywhere else but on the command line.

**Comment by chriseth** [comment]
I think this might have been a remnant of solidity sharing a repository with AlethZero, AlethOne and AlethFive ;-)
