### ISSUE TITLE
Solidity by example - Warnings with voting.sol

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/solidity#3163]
Installed from source today. Following https://solidity.readthedocs.io/en/latest/solidity-by-example.html

Get Warnings when compiling the code.

Unclear what "Spanning multiple lines" means. Is this an error?

﻿﻿~/solid/examples/solc voting.sol
Warning: This is a pre-release compiler version, please do not use it in production.
voting.sol:31:5: Warning: No visibility specified. Defaulting to "public".
    function Ballot(bytes32[] proposalNames) {
    ^
Spanning multiple lines.
voting.sol:51:5: Warning: No visibility specified. Defaulting to "public".
    function giveRightToVote(address voter) {
    ^
Spanning multiple lines.
voting.sol:64:5: Warning: No visibility specified. Defaulting to "public".
    function delegate(address to) {
    ^
Spanning multiple lines.
voting.sol:105:5: Warning: No visibility specified. Defaulting to "public".
    function vote(uint proposal) {
    ^
Spanning multiple lines.
voting.sol:119:5: Warning: No visibility specified. Defaulting to "public".
    function winningProposal() constant
    ^
Spanning multiple lines.
voting.sol:134:5: Warning: No visibility specified. Defaulting to "public".
    function winnerName() constant
    ^
Spanning multiple lines.
voting.sol:91:9: Warning: This declaration shadows an existing declaration.
        Voter storage delegate = voters[to];
        ^--------------------^
voting.sol:64:5: The shadowed declaration is here:
    function delegate(address to) {
    ^
Spanning multiple lines.

voting.sol:120:22: Warning: This declaration shadows an existing declaration.
            returns (uint winningProposal)
                     ^------------------^
voting.sol:119:5: The shadowed declaration is here:
    function winningProposal() constant
    ^
Spanning multiple lines.

voting.sol:135:22: Warning: This declaration shadows an existing declaration.
            returns (bytes32 winnerName)
                     ^----------------^
voting.sol:134:5: The shadowed declaration is here:
    function winnerName() constant
    ^
Spanning multiple lines.

**Comment by limexp** [comment]
@quantumproducer 
The source for this message is here https://github.com/ethereum/solidity/blob/dc154b4e5661945ca9c98720e097e84729a528be/libsolidity/interface/SourceReferenceFormatter.cpp#L86

It is just a notice that the source code for the previous output message was not on a single line.

**Comment by axic** [comment]
Any wording suggestions how to improve this?

cc @federicobond

**Comment by guptasiddharth** [comment]
Its just a warning. If you want to get rid of it just define the scope of the functions (eg. public)

**Comment by lazaridiscom** [comment]
@axic , the suggestion is:

* Remove "Spanning multiple lines" completely, as its misleading.

or change to:

`^___spanning multiple lines`

(I was just wondering myself. Now realizing that the pointer is meant ^, that it cannot point, as the warning affects something that is "Spanning multiple lines")

**Comment by chriseth** [comment]
@lazaridiscom yes, the fact that "spanning multiple lines" is on a different line confuses many, we should change that.

**Comment by lazaridiscom** [comment]
@chriseth , glad you agree. Btw: how straightforward is the dev-system setup? I'm on Win10 currently, but could use docker or Hyper-V, too (or Windows Bash).

**Comment by axic** [comment]
Tracked in #3620 now.
