### ISSUE TITLE
Missing Documentation for Test Network

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/solidity#3164]
Neither https://solidity.readthedocs.io/en/latest/frequently-asked-questions.html or https://solidity.readthedocs.io/en/latest/solidity-by-example.html

has examples of running solidity contracts on a test network and validating the contract does what it's supposed to.

I expected to see examples showing how to run these contracts on a test network so I can manually verify the contract behaves as expected.

**Comment by limexp** [comment]
@quantumproducer 
You can use [Truffle](https://github.com/trufflesuite/truffle) and [TestRPC](https://github.com/ethereumjs/testrpc) for testing. As I know this is the simplest and fastest way to test. These projects have good documentation about testing.

**Comment by quantumproducer** [comment]
Thank you. I found https://medium.com/@ConsenSys/a-101-noob-intro-to-programming-smart-contracts-on-ethereum-695d15c1dab4 which looks like a good start. Would like to see documentation like this in the official repo.

**Comment by Cryt1c** [comment]
This is also an awesome introduction into the tools of the space and how to deploy your first smart contract on your private blockchain: https://codeburst.io/build-your-first-ethereum-smart-contract-with-solidity-tutorial-94171d6b1c4b

**Comment by elenadimitrova** [comment]
I wouldn't expect working with the network (testnet or mainnet) to be part of the Solidity documentation.  This is a process that entails a few different tools and frameworks and is best described in various introductory posts as noted by the people above. For example the client you use could be different, e.g. ganache-cli, parity, geth or go via Infura, you could also deploy via a UI like MEW or even Remix. Contract validation then happens on a block explorer like Etherscan using the compiled output from truffle or directly with`solc`. Basically it all depends on your setup and there's not one "recommended" way of doing it. The purpose of the Solidity documentation is to teach us purely about the Solidity language and compiler specifics, writing smart contracts and non functional aspects like security. Anything outside of that, I believe, is out of scope of the language documentation. Therefore if people agree, we can close this issue.

**Comment by chriseth** [comment]
I agree. The documentation also does not mention how to work with mainnet...
