### ISSUE TITLE
onlyOwner modifier in one function doesn't allow the owner himself to call another function with the same onlyOwner

### ISSUE THREAD

**Issue by stefanionescu** [ethereum/solidity#3170]
Solidity: 0.4.15
Deployment of contracts on Mist (latest)

I have a function "mint" in contract A that mints a token. I also have another contract B that keeps a mapping with the minted amounts of tokens for each address. In contract B, I have a function "increaseTotal" that increases the total amount of minted tokens when I mint something.

Inside "mint", I call the function "increaseTotal" from contract B. 

The problem:

Both "mint" and "increaseTotal" have a modifier annotated to them, onlyOwner. I make them so that both contracts are deployed from the same address. If I call "mint", "increaseTotal" also needs to be called. Although the owner is the same for both functions, Mist tells me that it's impossible to execute this.

Am I doing something wrong?

P.S If I let onlyOwner only for "mint" and not for "increaseTotal", it works...

**Comment by limexp** [comment]
@stefanionescu 
It may be a migration issue. Please describe the procedure and provide code fragments for at least constructors of both contracts and call to increaseTotal from mint.

**Comment by stefanionescu** [comment]
@limexp 

The contract with my modifier:

     contract Owned {

    address private owner;
    address private newOwner;

   
    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }

    /// @notice The Constructor assigns the message sender to be `owner`
    function Owned() {
        owner = msg.sender;
    }


    function changeOwner(address _newOwner) onlyOwner {

        newOwner = _newOwner;

    }

    function acceptOwnership() {
        if (msg.sender == newOwner) {
            owner = newOwner;
            newOwner = 0x0000000000000000000000000000000000000000;
        }
    }
    }

TokenController (contract A):

     contract TokenController is Owned {

    SapienToken private sapienToken;

    event Mint(address indexed to, uint256 amount);

    function TokenController(address _sapien) {

        sapienToken = SapienToken(_sapien);
    
    }

    function changeBasicToken(address _sapien) onlyOwner {

        sapienToken = SapienToken(_sapien);

    }

    function mint(address _to, uint256 _amount) onlyOwner returns (bool) {
        sapienToken.increaseTotal(_amount);
        sapienToken.addToBalance(_to, _amount);
        Mint(_to, _amount);
        return true;
    }

    }

SapienToken (contract B):

    contract SapienToken is ERC20Basic, Owned {
  
    using SafeMath for uint256;

    mapping(address => uint256) balances;

    string public name = "NAME";
    string public symbol = "SYMBOL";
    uint256 public decimals = 18;


    function SapienToken() {


    }


    function transfer(address _to, uint256 _value) public returns (bool) {
    
    require(_to != address(0));

    balances[msg.sender] = balances[msg.sender].sub(_value);
    balances[_to] = balances[_to].add(_value);
    Transfer(msg.sender, _to, _value);
    return true;

    }

  
    function balanceOf(address _owner) public constant returns (uint256 balance) {
    return balances[_owner];
    }

    function increaseTotal(uint256 _amount) public onlyOwner {

    totalSupply = totalSupply.add(_amount);

    }

    function addToBalance(address _to, uint256 _amount) public onlyOwner {

    balances[_to] = balances[_to].add(_amount);

    }

    }

I deploy SapienToken and then TokenController.

**Comment by limexp** [comment]
@stefanionescu 
When you call **mint** function of TokenController from address X the value of **msg.sender** will be equal to X.
But when **increaseTotal** function of SapienToken called from mint function then the value of **msg.sender** will be equal to the address of TokenController instance. That's why onlyOwner check in increaseTotal fais.

**Comment by stefanionescu** [comment]
You're a genius. I can't believe I couldn't see that...thanks!

**Comment by jerryji** [comment]
So how to enforce the onlyOwner modifier in SapienToken when calling those functions from TokenController?

**Comment by ozenirgokberk** [comment]
Is there any improvement about this content ? This approach cannot solve the problem i guess. if you try to call onlyOwner functions in SapienToken from TokenController, you can see the fails about ownership.

**Comment by IngridMi** [comment]
> Solidity: 0.4.15 Deployment of contracts on Mist (latest)
> 
> I have a function "mint" in contract A that mints a token. I also have another contract B that keeps a mapping with the minted amounts of tokens for each address. In contract B, I have a function "increaseTotal" that increases the total amount of minted tokens when I mint something.
> 
> Inside "mint", I call the function "increaseTotal" from contract B.
> 
> The problem:
> 
> Both "mint" and "increaseTotal" have a modifier annotated to them, onlyOwner. I make them so that both contracts are deployed from the same address. If I call "mint", "increaseTotal" also needs to be called. Although the owner is the same for both functions, Mist tells me that it's impossible to execute this.
> 
> Am I doing something wrong?
> 
> P.S If I let onlyOwner only for "mint" and not for "increaseTotal", it works...
