### ISSUE TITLE
Get rid of "no visibility specified" warnings in documentation

### ISSUE THREAD

**Issue by limexp** [ethereum/solidity#3172]
After PR #2749 now examples in documentation produce messages:
> Warning: No visibility specified. Defaulting to "public".

Adding "public" visibility will solve the problem. 

I can make a PR after merge of #3152.

**Comment by axic** [comment]
@limexp good idea! Please do.

**Comment by axic** [comment]
@limexp it has been merged if you are still interested

**Comment by ChrisChinchilla** [comment]
@axic Looking into this one, I'm having some technical issues which I'll investigate, but mostly I wondered if these tests are all contained in the _scripts/tests.sh_ script as it's not completely clear if this includes the docs tests? If so, I might clarify that in another PR.

**Comment by axic** [comment]
I think it is done in `test/commandlineTests.sh`.
