### ISSUE TITLE
Add support for compiler output filtering.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#3174]
This is both a bug and a feature request.  I can split it into two if that helps:

### Bug

https://solidity.readthedocs.io/en/develop/using-the-compiler.html#input-description says that `outputSelection` is a setting that can be passed to the input JSON but #2256 suggests that this is not actually the case.  The documentation should be updated and that section removed.

### Feature

Implement compiler output filtering.  My project currently produces a 12.5MB JSON file that is _really_ hard/expensive to work with due to its size.  I have been playing around with various JS object filters and JSON parsers but due to the size of the JSON file all of them choke really hard and do not allow me to actually filter the output.  I can do `JSON.parse(compilerOutputJson)` and that gets me an in-memory JS object but its so big that I can't actually filter it.  This is complicated by the fact that the keys aren't well defined (they are the names of files and contracts) which means any filtering needs to walk the entire structure.

**Comment by axic** [comment]
Please refer to the changelog, output filtering exists, though to the fullest extent yet.

As a side note, the compiler must parse that 12.5MB JSON file that, so perhaps it is a good indication for review (why is that big? 😉)

**Comment by MicahZoltu** [comment]
This is the _output_ JSON that is that big, it is the JSON file the compiler is generating.  I don't want it to generate 90% of what is in that file, but I can't stop it because the configuration in the documentation doesn't actually work.

I see this in the 0.4.18 changelog:
> Standard JSON: Support the outputSelection field for selective compilation of supplied sources.

However, when I upgrade my contracts to 0.4.18 the compiler complains about my input JSON:
```
            language: "Solidity",
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 500
                },
                outputSelection: {
                    "*": {
                        "*": [ "abi", "evm.bytecode.object" ]
                    }
                }
            },
            sources: {}
```
If I delete the `outputSelection` section it works.  I believe what I have aligns with what the documentation says I should have.  The same input JSON in 0.4.17 doesn't appear to do anything at all, though it also doesn't error.

**Comment by axic** [comment]
The changelog is correct, it does support output selection, though not to the fullest extent. Currently it will filter based on file names / contract names requested. However, by using `*` / `*` you disable that feature.

Can you please expand on what "the compiler complains about my input JSON" means?

**Comment by nuevoalex** [comment]
When we provide the following outputSelection configuration:

```
'outputSelection': {
    '*': [ 'metadata', 'evm.bytecode', 'evm.sourceMap' ]
}
```

It results in this error:

```
SolcError: JSON logic exception: in Json::Value::getMemberNames(), value must be objectValue
E               > command: `solc --allow-paths /home/alex/Work/augur-core --standard-json`
E               > return code: `0`
E               > stderr:
E               {"errors":[{"component":"general","formattedMessage":"JSON logic exception: in Json::Value::getMemberNames(), value must be objectValue","message":"JSON logic exception: in Json::Value::getMemberNames(), value must be objectValue","severity":"error","type":"InternalCompilerError"}]}
```

**Comment by axic** [comment]
It is a two-level object: `"outputSelection": { "<filename>": { "<contractname>": [ "metadata" ] } }`, where both `filename` and `contractname` can be wildcards (please see the documentation, it has a couple of rules).

**Comment by MicahZoltu** [comment]
Gah!  Our code had two blocks, one with the two layers and one with a single layer.  I didn't realize they were different which is why the code I pasted above is correct, but it was actually the code that @nuevoalex pasted that was throwing the error.  Sorry for all of the rage from me in this thread.  :/
