### ISSUE TITLE
Event not emitted

### ISSUE THREAD

**Issue by chuacw** [ethereum/solidity#3175]
The following contract is supposed to emit 2 events on creation, however, only 1 event is emitted.

EXP: 2 events emitted.
ACT: 1 event emitted.

Using Ethereum Wallet 0.9.2 for the contract deployment.
The contract is on Ropsten. 

pragma solidity ^0.4.16;

contract EventBug {
  event NotEmitted;
  event Emitted();

// Ropsten TxHash: 0xc9dbde78f19a2463af505a44bd16e56084cb3da3f5aa96aea832550eba2a2f4b
// Notice that only 1 event is emitted, as opposed to 2.
  function EventBug() {
     NotEmitted; // <-- No error as well
     Emitted();
  }
}

**Comment by federicobond** [comment]
That’s some funny looking code. Thanks for reporting it @chuacw!

The specific problem with your code is that you are not calling the event, just referencing it. Try replacing NotEmitted with NotEmitted().

You can see the difference more clearly if you do:
```
var e = NotEmitted;
e();
```

The other issue is that you can apparently declare events with an implicit empty argument list, something that is not specified in the official grammar. If that is intented behavior, we should update the spec. Personally, I don’t like that style very much.

**Comment by axic** [comment]
`event NotEmitted;`

Is clearly a bug as mentioned by @federicobond, it should be a parser error.

`NotEmitted; // <-- No error as well`

We should issue a warning in this case.

**Comment by axic** [comment]
The second problem will be sorted by #2707.
