### ISSUE TITLE
Memory not cleared (?) before call and result after fallback function is treated as boolean

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3179]
Found by @D-Nice, I think there is another issue this is a duplicate of, but couldn't find it:

```
contract C {
    function g() returns (bool);
}

contract D {
    function() {}

    function f() returns (bool) {
        // call `g()` on `D` (non existing method), but returns `true`
        // due to the memory not cleared after the fallback function 
        return C(this).g();
    }
}
```

**Comment by chriseth** [comment]
Invalid casts always cause undefined behaviour. We can probably partly fix this with returndatacopy, but the issue will always persist.

**Comment by axic** [comment]
One way to make this more deterministic currently is to clear the return memory space before the call, though with `returndatasize` it is arguably simpler.

**Comment by chriseth** [comment]
This has been fixed.
