### ISSUE TITLE
Consider updating all documentation examples to match latest compiler

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3180]
e.g. disallow any warnings.

This also means that likely it won't compile with older ones.

I'm not sure which is the better option out of the two (current behaviour vs. this proposal).

**Comment by redsquirrel** [comment]
This sounds like a great idea. Also, can the documentation be versioned so people using an older compiler version can see what works for them?

**Comment by maurelian** [comment]
@redsquirrel isn't it already versioned? 
ie. https://solidity.readthedocs.io/en/v0.4.1/solidity-in-depth.html

**Comment by redsquirrel** [comment]
Right, so if that’s the case, why not keep the docs up to date with the
latest version?

**Comment by axic** [comment]
Because that forces users to always have the latest version of the compiler. It is debatable whether that is good or bad, but it seems that popular frameworks adopt Solidity releases with different delays.

Additionally for some reason readthedocs includes some versions and not others. Any ideas for that?

**Comment by chriseth** [comment]
We now do not allow any warnings in documentation examples anymore.
