### ISSUE TITLE
Ethereum.org learn solidity takes to develop that can't be found to edit

### ISSUE THREAD

**Issue by janat08** [ethereum/solidity#3181]
Ethereum.org learn solidity takes to develop that can't be found to edit. That is if you want help with documentation it would help to not link develop branch of documentation in footer that then can't be found to contribute to.

**Comment by axic** [comment]
Can you please explain the issue in more detail? I am not sure what page to look at.

It is very likely though this issue should be addressed at https://github.com/ethereum/ethereum-org/issues (since that is the source for the website)
