### ISSUE TITLE
Query style syntax

### ISSUE THREAD

**Issue by r0kk3rz** [ethereum/solidity#3184]
In a multisig wallet scenario, if you want to check that everyone has signed a particular pending transaction you end up doing something like this.

```
    function isConfirmed(uint transactionId)
        returns (bool)
    {
        uint count = 0;
        for (uint i=0; i<owners.length; i++) {
            if (pendingTx[transactionId][owners[i]])
                count += 1;
            if (count == owners.length)
                return true;
        }
    }
```

Which is a rather long winded way of saying 'Everyone needs to agree to this'.

Instead it would be nice to get a bit more declarative and query-like with it.
Eg.
```
    function IsConfirmed(uint transactionId)
        returns (bool)
    {
        return where all owners in pendingTx[transactionId]
    }
```

Which reduces a hand crafted loop with possible off by one errors and other common mistakes into something that in my mind is quite readable and would be great in modifiers

**Comment by chriseth** [comment]
We do not plan to add declarative constructs for now.
