### ISSUE TITLE
Better tools for implementing proxies via delegatecall

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#3185]
In the wake of the recent Parity hack, it's clear that we can do better at the language level to improve the security of some of the patterns that have appeared recently due to the increased use of delegatecall.

While putting several hundreds of millions of dollars in a complex contract structure like the one used by Parity was foolish, especially when there are [much better alternatives](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol) that have been extensively audited, I think their design goals were reasonable and we should try to improve support for contracts that serve as proxies to a library which implements the actual logic.

My own (extremely fresh) proposal looks something like this:

```javascript
impl Wallet {
  // rejects all calls that don't come from a delegatecall
  // lets you declare fields that specify the storage layout
}

contract MyWallet is Wallet {
  // proxies all internal and external calls transparently via delegatecall
  // but you can overwrite individual methods
  function MyWallet() Wallet(0x692a70d2e424a56d2c6c27aa97d1a86395877b3a) {}

  function transfer(address to, uint amount) {
    require(additionalCheck);
    super.transfer(to, amount);
  }
}
```

I would love to hear your feedback on it.

**Comment by axic** [comment]
Please see #2296 as part of the suggested solution.

**Comment by federicobond** [comment]
Yes, I like the ideas on how to distinguish between delegatecalls and regular calls to the contract (I was thinking about proposing a new opcode CODEADDRESS or something similar, but checking for a magic storage value works too).

I also agree that we might want to be careful with the fallback function (perhaps a simple check for empty CALLDATA can work).

@chriseth's proposal requires the master contract to act as a factory for all proxy contracts, so it can enforce certain invariants for all of them. It also makes it impossible for contracts to have individual behaviour independent of the master copy. Whether that's a tradeoff that most users are comfortable with I am not sure, we may need to gather additional feedback.

**Comment by 3esmit** [comment]
One thing that would be useful is the ability to have storage in stub contract that is not affected in anyway by actions in code at delegatecall. 
The use for this is to set an address variable storage that stores the target (or targets) to delegate call. 
I've been able to accomplish this by using a secondary contract to store the target address, but this overloads the gas on each call to the read of an external contract storage. 
I'm trying to develop a upgradable stub contract, where stub contracts could opt-in to update itself in case of emergency (such as selfdestruct of library or some other conditions) or in case is available update. 
The "problem" is that we need to everytime have that `address libraryAddr = 0xAddr` in all "library contracts" that are meant to be used by this contract. See https://github.com/aragon/aragon-core/blob/dev/contracts/kernel/KernelStorage.sol by @izqui 

Other problem is that, in a case of update. when you change the variables of the library address, you might break the storage, unless you do it right - and sometime a migration might be need. 
If we could enforce that some variables use determined pointers, such as the one old contract was using, then this migrations would not be needed.

**Comment by federicobond** [comment]
Yes, upgradeable contracts are going to be really popular, and we must provide better tools at the language level. The issues you mention are real and the solutions we have found so far have been hacky at best. Let me offer some thoughts on your last point.

> Other problem is that, in a case of update. when you change the variables of the library address, you might break the storage, unless you do it right - and sometime a migration might be need.
If we could enforce that some variables use determined pointers, such as the one old contract was using, then this migrations would not be needed.

One way to perform safe upgrades is to have a language to describe a specific storage layout. Then, you can have multiple versions of the same contract but as long as they follow the same storage layout, you can upgrade the underlying implementation.

```
storage TokenStorage {
  mapping(address => uint256) balances;
  uint256 totalSupply;
}
```
```
contract TokenV2 is TokenStorage {
  // ... TokenV2 cannot add additional state variables
}
```
Of course, the compiler should provide a guarantee that variables are packed in a consistent way in the contract state.
