### ISSUE TITLE
Date function

### ISSUE THREAD

**Issue by martriay** [ethereum/solidity#3186]
(Originally an [OpenZeppelin proposal](https://github.com/OpenZeppelin/zeppelin-solidity/issues/533))

Smart contracts have to deal with dates for a multiplicity of reasons. Nowadays this is not only done by placing a [magic constant](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) but also by representing them as seconds since unix epoch, which is not human-readable and error prone.

Smart contract programming is no different discipline from "regular" software programming as we tend to refactor existing code or change our minds on a given functionality. When this happens, arbitrary numbers representing old dates are difficult to catch.

To address this issue I suggest a Date function for defining dates in a human-readable manner following [javascript's Date interface](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) as it's something we're used to.

Thus if we wanted to state that a given crowdsale starts on October 31st at 16:30 UTC, we would write it like this:

```javascript
uint256 crowdsaleStartsAt = Date(2017, 9, 31, 16, 30) // months are 0-based so October is the 9th
```

Opening up the topic for discussion.

**Comment by axic** [comment]
I think this is a very good candidate for a library function (`Date(uint,uint,uint,uint,uint,uint) returns (uint)`).

If it is marked `pure` and we implement compile time constant expressions, then `uint constant crowdsaleStartsAt = Date(2017, 9, 31, 16, 30, 0)` can be a constant value.

**Comment by federicobond** [comment]
Is there a way to skip pure functions from the generated bytecode? I think the Date function would require a non-trivial amount of code that would be wasteful to deploy if used only for initializing a constant.

**Comment by federicobond** [comment]
For example, in v8 computing just days from epoch uses [this code](https://github.com/v8/v8/blob/master/src/builtins/builtins-date.cc#L67-L83):
```c++
    static const int kYearDelta = 399999;
    static const int kBaseDay =
        365 * (1970 + kYearDelta) + (1970 + kYearDelta) / 4 -
        (1970 + kYearDelta) / 100 + (1970 + kYearDelta) / 400;
    int day_from_year = 365 * (y + kYearDelta) + (y + kYearDelta) / 4 -
                        (y + kYearDelta) / 100 + (y + kYearDelta) / 400 -
                        kBaseDay;
    if ((y % 4 != 0) || (y % 100 == 0 && y % 400 != 0)) {
      static const int kDayFromMonth[] = {0,   31,  59,  90,  120, 151,
                                          181, 212, 243, 273, 304, 334};
      day_from_year += kDayFromMonth[m];
    } else {
      static const int kDayFromMonth[] = {0,   31,  60,  91,  121, 152,
                                          182, 213, 244, 274, 305, 335};
      day_from_year += kDayFromMonth[m];
    }
    return static_cast<double>(day_from_year - 1) + date;
```

**Comment by axic** [comment]
`internal` functions which are not referenced by anything should be dropped from the bytecode already (need to double check if this is the case)

If all the plans for *compile time constants* are implemented, then `internal pure` functions assigned to a simple constant only would be done compile time. If *compile time constants* are not implemented, we could still aim to turn (or have an option) constants into evaluate-once and keep in memory.

**Comment by axic** [comment]
With #3157 and #3271 this could be implemented in a library.

**Comment by chriseth** [comment]
This should be implemented in a library.
