### ISSUE TITLE
Document shortcut pattern

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#319]
Try to implement and document the following general pattern:

A certain expensive computation is implemented as a contract function on the blockchain.
By default, the computation is performed off-chain and only its result is supplied together with a deposit.
Anyone can challenge the computation by forcing the contract to run the computation, including another deposit. If the challenge is successful, the challenger gets half of the original deposit, the second half is destroyed. If it is not successful, the challenger's deposit is destroyed.

Potential problems:
- computation has to be stateless (and this has to be enforced in some way)
- parameters should be implemented in a polymorphic way
- verification could take more than one transaction (gas)

Possible extensions:
- initial invocation could supply an appropriately encoded transcript of the computation (or only its hash) and the challenge only has to uncover a single incorrect bit in the transcript.

**Comment by elenadimitrova** [comment]
When reading this I think about Merkle proofs and associated challenge-response protocol. Is this what you had in mind?

**Comment by chriseth** [comment]
I think this was something that later turned into TrueBit. Maybe we can close it?

**Comment by elenadimitrova** [comment]
This pattern is used in many places including the Colony Network protocol, The Matic Network etc. but I think it sits at a higher level than the Solidity documentation itself, perhaps as an EIP standard. We should close it here.
