### ISSUE TITLE
SolidityLexer causing build fail on readthedocs

### ISSUE THREAD

**Issue by FugueWeb** [ethereum/solidity#320]
Hello Ethereum,

Great work, simply brilliant, so a big thanks up front. I'm making my own set of docs on readthedocs with Sphinx and the docs compile/build just fine on my local machine. And when I initially set up the service hook between Github where the files are hosted and Readthedocs, again, still no problem. However, when I added in the `SolidityLexer` and configured the `conf.py` file, the docs build fine on my local machine but throw an error when trying to build on the readthedocs:

```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/idrevo/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
File "/home/docs/checkouts/readthedocs.org/user_builds/idrevo/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 148, in __init__
self.config.setup(self)
File "conf.py", line 27, in setup
from SolidityLexer import SolidityLexer
ImportError: No module named SolidityLexer

Exception occurred:
File "conf.py", line 27, in setup
from SolidityLexer import SolidityLexer
ImportError: No module named SolidityLexer
The full traceback has been saved in /tmp/sphinx-err-AFMkl3.log, if you want to report the issue to the developers.
```

It has to do with this line of code in the conf.py file, and again, it works fine on my local machine. This seems like a path issue, but unfortunately I am new to Python. All help is appreciated, thanks!

```
def setup(sphinx):
  sys.path.insert(0, os.path.abspath('./utils'))
  from SolidityLexer import SolidityLexer
  sphinx.add_lexer('Solidity', SolidityLexer())
```

**Comment by chriseth** [comment]
SolidityLexer is a custom lexer that is included in the repository (in docs/utils - the directory that is added to the module search path in the snippet you cited). It runs fine for us on readthedocs:
https://readthedocs.org/projects/solidity/builds/3608396/

**Comment by chriseth** [comment]
Closing as it runs fine on readthedocs. You might have to adjust the path or correctly import `SolidityLexer.py`.
