### ISSUE TITLE
grammar: consider removing built in types

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3211]
(From #3173.)

The suggestion here is to not include the complete list of built in types in the grammar, just consider them the same as user-defined types.

It should not make a difference grammar wise, only syntax highlighting benefits from it.

**Comment by aj07** [comment]
Can we close this. This has been merged in https://github.com/ethereum/solidity/pull/3173

**Comment by axic** [comment]
This wasn't done in #3173. That PR prompted the idea.

**Comment by aj07** [comment]
saw patch was merged. There were no comments about further improvement.
Please, let me know if there is further improvement.

**Comment by axic** [comment]
Even after #8505 this is still the same.
