### ISSUE TITLE
Feature request: mechanism to put local variables in memory

### ISSUE THREAD

**Issue by tinybike** [ethereum/solidity#3223]
One aspect of the stack depth limit issue is described in https://github.com/ethereum/solidity/issues/3222 (inability to remove local variables from the stack).  Another aspect is that Solidity does not allow the user to specify whether a variable should be stored [in memory or on the stack](https://solidity.readthedocs.io/en/latest/frequently-asked-questions.html#what-is-the-memory-keyword-what-does-it-do).  However, it is often useful for the programmer to be able to specify where to put variables (primarily due to the stack depth limit).

I'm making this issue to, first, ask whether this was an intentional design decision -- if so, why? -- and second, to propose that a mechanism to put local variables in memory be added to Solidity.

For reference, in Serpent, the programmer could specify where local variables would be stored as follows:
```
x = 5 # puts x in memory
with y = 2: # puts y on the stack
```
In Solidity, the `memory` keyword might be a natural way to implement this.  For example:
```
uint256 memory x = 5; // puts x in memory
uint256 y = 2; // puts y on the stack
```

**Comment by axic** [comment]
This should be relieved now by that fact that with C++ scoping variables are freed at the end of their scopes. This creates the option to have sub blocks for short lived variables.

However, the proposal here still stands and is valid. The feature however is more costly than using the stack.
