### ISSUE TITLE
When contract instantiation fails, is created with null state variables

### ISSUE THREAD

**Issue by jvanecek** [ethereum/solidity#3224]
Let `Purchasable` be this [contract](https://github.com/jvanecek/eth-monopoly/blob/c738fdfadd7a50f277ea02b67de6f527dc620a35/contracts/Purchasable.sol). 

I wrote [this](https://github.com/jvanecek/eth-monopoly/blob/c738fdfadd7a50f277ea02b67de6f527dc620a35/test/PurchasableTest.js) test to assert the correct instantiation. 

As you can see in [this](https://travis-ci.com/jvanecek/eth-monopoly/builds/59754662) build, the test Purchasable Creation was failing as the contract had all the state variables in null (`assetName == ""`, `priceAmount == 0`, `bankerAddress == address(0)`).

The problem was in the beforeEach of the test `await Purchasable.new("Park Place", 350, banker)`, that should have been `await Purchasable.new("Park Place", 350, banker.address)`. 

Apparently the `await` failed, silenced the exception, and returned me a `Purchasable` all broken. 

I know the `await` operator is out of your domain, but thought this was no minor issue to report.

**Comment by axic** [comment]
Can you please explain what is the Solidity problem here?

**Comment by axic** [comment]
I think this may need to be brought up with Truffle.
