### ISSUE TITLE
Generate a payload for call of another contract

### ISSUE THREAD

**Issue by naumenkogs** [ethereum/solidity#3229]
Hi.
Is it possible to access a low-level payload of a call to another contract on a solidity level?
In web3.js I can do
const addOwnerData = multisigInstance.contract.addOwner.getData(accounts[3])
And I'll have such a payload. Is it possible to do at the solidity-level? Assuming I have an instance of another contract.

**Comment by axic** [comment]
I am not fully sure what do you mean, but `msg.data` should give access to the entire incoming message for an external function.

Please reopen if this doesn't answer the question.

**Comment by naumenkogs** [comment]
@axic I'm not sure I can reopen this issue.

msg.data gives access to the payload for the function of *current contract*.
I need to prepare a call from *current contract* to *another contract*, and get the payload of such a call without execution.

*From inside solidity function*:

```
function storePayloadForCallingAnotherContract() {
    TestContract contract = TestContract("address....");

    // *Without execution*
    var payload = contract.call("functionFromTestContract", "argument1", argument2).getPayload();
} 
```

**Comment by axic** [comment]
Oh, I understand then. That is tracked in issue #1707, a pull request is pending but it is a not finished feature yet.
