### ISSUE TITLE
Private keys in CI

### ISSUE THREAD

**Issue by adria0** [ethereum/solidity#3230]
It seems that the `appveyor.yml` contains private keys.
Maybe is a good idea to dettach them from github in some way.

**Comment by chriseth** [comment]
They are currently required to push artifacts to a github repository. The keys are of course encrypted, but I agree that it is not ideal. Do you have any suggestions?

**Comment by chriseth** [comment]
We could at least switch to a different account.

**Comment by erak** [comment]
Remove all private keys from all CI (travis, AppVeyor) or at least switch to a different account.

**Comment by chriseth** [comment]
This has been fixed with shutting down travis.
