### ISSUE TITLE
Pure functions should not be allowed to do revert()

### ISSUE THREAD

**Issue by pash7ka** [ethereum/solidity#3237]
I understand that pure functions should not have any side effects. And doing revert() is a side effect.
Here is the test contract:
```
pragma solidity ^0.4.17;
contract Test {
    uint public a;
    function setA(uint _a) public {
        notZero(_a);
        a = _a;
    }
    function notZero(uint v) pure public {
        if(v == 0) revert();
    }
}
```
In my opinion compilation should fail. But instead if i don't specify "pure" solcjs generates warning:
```
Test.sol:8:5: Warning: Function state mutability can be restricted to pure
    function notZero(uint v) public {
    ^
Spanning multiple lines.
```

**Comment by axic** [comment]
This is actually a very good question and we had some discussions on different level of "pureness". Currently `pure` functions are only pure when externally called. If they are called internally, they can use `revert` as well as modify the memory as they wish.

Regarding the avoidance of memory modification we have the `immutable` keyword on input arguments (not yet implemented).

I think `revert` is a very useful feature in many use cases of a pure function (when externally called), but how (if) should we mark these two types of pure functions within a contract?

One obvious answer is that `pure external` functions can use `revert`, `require`, etc., while `pure internal`, `pure private`  and `pure public` cannot (the last has both an internal and external interface). This however seriously affects the usefulness of such functions.

**Comment by pash7ka** [comment]
I've found this behaviour when compiling a [HasNoTokens.sol](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/HasNoTokens.sol) generated a warning on ``tokenFallback()``.
If I mark  ``tokenFallback()`` as pure and some ERC-223 token will try to call it, the transfer will be reverted. So the state of the token contract will be modified as a result of calling my pure function.
And the documentation for pure keyword states that
> Functions can be declared pure in which case they promise not to read from or modify the state.

That was the reason I've created this issue.

Can you give me some examples of that use cases where revert() in pure function will be useful?

**Comment by axic** [comment]
> If I mark tokenFallback() as pure and some ERC-223 token will try to call it, the transfer will be reverted.

How exactly will that modify the state of your contract?

Note, revert doesn't "modify" the state because it aborts *and* reverts any changes done to it in that execution context.

**Comment by pash7ka** [comment]
Please correct me if i'm wrong, but i understood that "state" in the documentation is a refference to an Ethereum world state, not the state of the contract where the pure function is declared.
So that if i have some contract which calls a pure function of another contract, i can be sure that nothing will be changed in the world state during this call.
During the execution of my contract's call i modify something in my state.
And now you are saying that calling pure function of another contract i should not expect, that my changes will be preserved?

**Comment by axic** [comment]
If you make an external call to another contract, nevertheless if it is a Solidity "pure" function on the receiving end, that creates a new context (execution instance). If there is a revert happening there, it only affects that context. Internally the assembly `CALL` opcode is the one used to message external contracts and it returns 0 or 1 whether it was successful.

There are certain Solidity functions (such as `.transfer()`) which will revert the calling contract if the callee fails.

**Comment by pash7ka** [comment]
Thank you for the explanation.
Also, i understand the problem, that if ``revert()``, ``require()`` and ``assert()`` will be not allowed in pure functions, then using libraries like SafeMath will not be possible there.
So perhaps you are right, and this issue should be closed.
