### ISSUE TITLE
Bug in Blind Auction contract example

### ISSUE THREAD

**Issue by nikhil-tibrewal** [ethereum/solidity#3239]
Referencing: https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst#blind-auction-1

The `auctionEnd()` says that:

```
        // We send all the money we have, because some
        // of the refunds might have failed.
        beneficiary.transfer(this.balance);
```
But this isn't correct right? What if the bidders haven't called `withdraw` yet? Any unclaimed ether would also go to the beneficiary? And in what scenarios would refunds fail? This is the first instance since the beginning of the Solidity docs where `failure` is brought up. Could this be elaborated further?

**Comment by chriseth** [comment]
Thanks a lot for finding this! I think this is a remnant of an incomplete change to the withdraw pattern. Refunds cannot fail anymore here.

**Comment by JLansey** [comment]
Just to add more info here, the new code transfers the highest bid instead of the contract balance.

```
       // 3. Interaction
        beneficiary.transfer(highestBid);
```
