### ISSUE TITLE
Remove solc warning detection from zeppelin tests

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3244]
Currently our tests are always failing:

```
> zeppelin-solidity@1.3.0 test /tmp/tmp.Cblq5apBSn
> scripts/test.sh
Starting our own testrpc instance
Error parsing /tmp/tmp.Cblq5apBSn/contracts/Bounty.sol: Warning: This is a pre-release compiler version, please do not use it in production.
Compilation failed. See above.
```

@frangio would it be possible to have a flag for disabling this check?

**Comment by chriseth** [comment]
Can we somehow patch it out from the testing framework?

**Comment by frangio** [comment]
@axic I don't understand what the problem is. What check would we have to disable?

**Comment by axic** [comment]
It seems that zeppelin tests are failing because the above `Warning: This is a pre-release compiler...` is treated as an error. Maybe it is enforced by truffle?

Context: during the Solidity build the `soljson.js` is replaced with a fresh build, which is a prerelease version.

**Comment by spalladino** [comment]
@axic I haven't been able to reproduce this warning at all when running the tests locally using soljson.js version `soljson-v0.4.19-nightly.2017.11.22+commit.f22ac8fc.js`, downloaded from https://ethereum.github.io/solc-bin/bin/. I'm assuming that that version should be considered pre-release, and thus trigger the warning, right?

**Comment by axic** [comment]
@spalladino that should work. You can try running the exact same tests with `test/externalTests.sh <absolute path to soljson.js>`

**Comment by axic** [comment]
Did it locally and it triggered the problem:
```
$ wget https://ethereum.github.io/solc-bin/bin/soljson-v0.4.19-nightly.2017.11.22+commit.f22ac8fc.js
$ ./externalTests.sh `pwd`/soljson-v0.4.19-nightly.2017.11.22+commit.f22ac8fc.js
```

**Comment by axic** [comment]
It seems that truffle emits this when using truffle-compile `parse` or `parseImports` https://github.com/trufflesuite/truffle-compile/blob/develop/parser.js#L44

**Comment by spalladino** [comment]
Thanks @axic, I did manage to reproduce it using that compiler. Issue was I was overwriting the file in `node_modules/solc`, but not in `node_modules/truffle/node_modules/solc`.

**Comment by spalladino** [comment]
> It seems that truffle emits this when using truffle-compile parse or parseImports 
> https://github.com/trufflesuite/truffle-compile/blob/develop/parser.js#L44

I'll take a look there. Last thing I had managed to check was that truffle emits warns as errors only if the strict flag is set, which is disabled by default. Thanks!

**Comment by axic** [comment]
@spalladino never mind. It seems this is entirely an issue in Truffle. They use the above methods as part of the which-file-has-changed mechanism for keeping a compilation cache.

**Comment by spalladino** [comment]
> @spalladino never mind. It seems this is entirely an issue in Truffle. They use the above methods as part of the which-file-has-changed mechanism for keeping a compilation cache.

Got it. Keep us posted on whether we should change anything on our end!
