### ISSUE TITLE
Suggestion: Use negative array index to access from back.

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#325]
```
function diff(int[] toDiff, int starting) returns (int){
        int difference = toDiff[starting];
        for (uint i = 1; i < toDiff.length; i++){
            difference -= toDiff[i];
        }
        if (difference < 0) {
            return int(difference);
        }
        //return uint(difference); trying to figure 
    }
```

gives the bug:

`Error: Type int256 is not implicitly convertible to expected type uint256.`

at the variable starting in: 

`int difference = toDiff[starting];`

simply put, that's clearly not a uint256.

**Comment by ethernomad** [comment]
starting needs to be declared as a uint

**Comment by VoR0220** [comment]
I guess I'm asking whether or not we should enable arrays to "wrap around" with an integer value that is signed. I doubt this will happen...but it'd be nice to have.

**Comment by axic** [comment]
I don't think it is a good idea introducing this since it goes against the general direction of being a safer language.

**Comment by VoR0220** [comment]
tight constraints on where you're at in the iterator and you should be able to achieve this...and in the process of making this happen, you could probably make the language safer as a result I think.

**Comment by chriseth** [comment]
I'm also not too convinced we should have this.

**Comment by VoR0220** [comment]
Well what would be the problem with jumping back to the front of the loop if the end is reached?

**Comment by VoR0220** [comment]
perhaps this could be a solidity module now that I'm thinking about it. Some inline assembly could probably make this work.

**Comment by axic** [comment]
@VoR0220 my concern is that for little benefit it makes unexpected behaviour possible, while we're trying to make it generally safer.

**Comment by VoR0220** [comment]
This is a fair concern. It's mere syntactic sugar and we ought to be focusing on safety atm. So I can see that concern. Closing for now.
