### ISSUE TITLE
ICO Tokens stuck on contract in Parity

### ISSUE THREAD

**Issue by BlockwareSolutions** [ethereum/solidity#3251]
Hello -

I need some help, I got a bit confused with Parity and had created a contract from my Parity Wallet - then the tokens of the ICO that I participated in were sent to the contract Address.

I am the owner / creator of this contract. I need to figure out how I can transfer these tokens from that contract to my actual parity wallet. I have tried for a couple of months and am stuck, I originally did this when I was newer to Crypto Currencies - hence the mistake. 

Appreciate any help I can get.

**Comment by axic** [comment]
I think this question should be opened with Parity. Check out https://github.com/paritytech
