### ISSUE TITLE
How to return array of structs ?

### ISSUE THREAD

**Issue by mimitc123** [ethereum/solidity#3253]
contract Donate{
  
   
    struct DonateInfo{
        uint id;
        uint value;
        uint time;
    }
    
    DonateInfo[] public list;
    
    function all() public returns (DonateInfo []){
        return list;
    }
   
   
    
}

When execute the return array function it says below
Failed to decode output: Error: Unsupported or invalid type: tuple

**Comment by axic** [comment]
That is a problem in the tooling you are using, which doesn't support the `tuple` ABI type (that is the one representing structs). Please report the issue on the project you are using to decode output from Solidity. I think you may be using Remix, in that case open an issue on https://github.com/ethereum/browser-solidity
