### ISSUE TITLE
How to compare strings

### ISSUE THREAD

**Issue by mimitc123** [ethereum/solidity#3255]
How to compare strings in contract

**Comment by Shrugs** [comment]
http://lmgtfy.com/?q=solidity+compare+string+site%3Astackoverflow.com

**Comment by axic** [comment]
Please see https://solidity.readthedocs.io/en/develop/#language-documentation for guidance. Hint: ask on the appropriate channels, https://gitter.im/ethereum/soldity or https://ethereum.stackexchange.com

**Comment by sweetMegan** [comment]
string name = "zhq";
    function compareString(string _name) view public returns(string){
       if(uint(keccak256(abi.encodePacked(name))) == uint(keccak256(abi.encodePacked(_name)))) {
           return "对 ";
       }else{
           return "不对";
       }
    }

**Comment by Flaque** [comment]
Reprinted sweetMegan's with formatting: 

```solidity
string name = "zhq";
function compareString(string _name) view public returns(string){
	if(uint(keccak256(abi.encodePacked(name))) == uint(keccak256(abi.encodePacked(_name)))) {
		return "对 ";
	}else{
		return "不对";
	}
}
```

**Comment by Chhe-chinyong** [comment]
I got the same question , could anyone help me out ?

**Comment by erak** [comment]
@Chhe-chinyong Please have a look at the documentation: https://solidity.readthedocs.io/en/latest/types.html#bytes-and-strings-as-arrays. You can compare strings like this: `keccak256(abi.encodePacked(s1)) == keccak256(abi.encodePacked(s2))`
