### ISSUE TITLE
Warn when using `return(p, s)` assembly in non external functions.

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#3258]
When using assembly return it ends the call at the moment encounter this assembly return, so this type of return should be used carefully as its not as a regular solidity return (which ends the internal call), this one ends the whole call to the contract at that moment.

Example:

```
pragma solidity ^0.4.10;


contract SystemA {

    event Test(bool);

    function testA() public {
        Test(TestReturns());
    }
    
    function TestReturns() public constant returns(bool) {
        assembly { 
            return(0,0)
        }

    }
    
}   
``` 

calling testA() will never fire the event Test.

**Comment by chriseth** [comment]
While this is a good suggestion, such a warning could give a false impression of safety.

Assembly can do just about anything and there are many things that are not checked about assembly code.

**Comment by axic** [comment]
The same applies to `require`, `assert`, `revert`, `throw` and `selfdestruct` in non-assembly.

**Comment by 3esmit** [comment]
This case is different. Most developers, specially the ones not aware of behavior of `assembly { return(p,s) } ` may assume that this return will return at internal function level, in the example is easy for make this misunderstand of behavior. 
I think that should be added some kind of warning for this case, maybe at "deep analysis", specially at "Low level calls: Semantics maybe unclear", only if the function using `return(p,s)` is not an external function.

**Comment by axic** [comment]
`assembly` should only be used by those who have a very good understanding about the language. Since there is no way to disable warnings in the compiler, you'd need to add this feature to the static analyzer in Remix.

**Comment by 3esmit** [comment]
I agree that this should go to static analizer. 
BTW, Paritytech team did not noticed this, look:
https://github.com/paritytech/contracts/blob/657da22245dcfe0fe1cccc58ee8cd86924d65cdd/validator_contracts/interfaces/RelaySet.sol#L56

This function callls `getValidators()`, and passes the result of the function to an event called `FinalizeChange` but this function is using `return(p,s)`  so it will end execution there.
https://github.com/paritytech/contracts/blob/657da22245dcfe0fe1cccc58ee8cd86924d65cdd/validator_contracts/interfaces/RelaySet.sol#L59-L69

Perhaps we need another type of assembly return, return2(p,s) that does not end call but returns at internal call scope?

**Comment by axic** [comment]
The "another type of assembly return" is assigning to the return variables directly from assembly.

Instead of `returndatacopy` + `return` it should write directly to the array: `returndatacopy(output_addresses, 0, returndatasize)` where `returns (address[])` is named as `output_addresses`. (assuming returndatacopy's first parameter is the output memory offset).

**Comment by 3esmit** [comment]
Closing issue to be addressed to specific "static analyzer tool"
