### ISSUE TITLE
Introduce restricted set of assembly

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3262]
Based on #3258 it may make sense introducing a restricted subset of the assembly to be used for snippets which do not need full access to the instruction set. I think majority of the use cases are like that.

Initial suggested list for removed features:
- invalid
- return
- revert
- selfdestruct

```
assembly "restricted" {
  revert(0, 0) <-- error
}
```

**Comment by axic** [comment]
Alternatively, introduce an "unchecked" or "unrestricted" version of assembly. The regular (not "unchecked") version would raise a warning if any of the above instructions are used in a non-external (internal, private, public) function, but an "unchecked" version would allow it.

```
assembly {
  // all of these are errors
label42:
  jump(label42)
  jump(0x2)
  selfdestruct(42)
  // these would be errors if the function is no marked "external"
  invalid()
  return(0, 42)
  revert(0, 42)
}

assembly "unchecked" {
  // none of these are errors
label42:
  jump(label42)
  jump(0x2) // this is a warning at the moment, that could be removed after this change
  invalid()
  return(0, 42)
  revert(0, 42)
  selfdestruct(42)
}
```

**Comment by 3esmit** [comment]
I agree in requiring a special flag in assembly blocks that affect the behavior of solidity internal calls, specially because this is not a common behavior.

Such as `return(p,s)` being used in a public function, when called externally it works fine but when called as internal function it will end execution at that `return(p,s)`.

**Comment by axic** [comment]
I wonder if this could make sense now since we have dialects, especially as @ekpyron suggested today to have an mstore-less version (where only mobj's are allowed).

**Comment by ekpyron** [comment]
I'm not sure about this - yes, sooner or later we will need to specify dialects for assembly blocks - but I'm not sure if there's much benefit in having a restricted instruction set. We even output the Yul AST to JSON in the meantime, so validating that specific instructions aren't used can easily be done by external tools. And the dialect namespace will get crowded and confusing anyways, so I'd try not to add more stuff than absolutely necessary to it.
