### ISSUE TITLE
Support dynamic arrays returned across contracts.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#3269]
As of Byzantium, I expect the following code to work:
```
contract Apple {
    string public seeds;
    function eat() public view returns (string) {
        return seeds;
    }
    
    function poop() public view returns (string) {
        return this.eat();
    }
}
```
However, it yields the following error on `return this.eat()`:
```
browser/ballot.sol:10:16: TypeError: Return argument type inaccessible dynamic type is not implicitly convertible to expected type (type of first return variable) string memory.
        return this.eat();
               ^--------^
```
I'm guessing the new dynamic return stuff (EIP211) hasn't been fully implemented yet?

**Comment by VoR0220** [comment]
It hasn't yet. It's finally at a stage where it can be worked on. Weirdly, with the experimental decoder, you *should* (I haven't tried this yet, but based on the release notes, I believe my interpretation is correct) be able to return a dynamic array or string that's inside of a struct by returning the struct itself, but not the dynamic array itself, or an array of the structs for that matter.

**Comment by axic** [comment]
Closing this in favour of #3270. I was sure we had an issue for it already, but couldn't find it.
