### ISSUE TITLE
Remove byzantium-only warning

### ISSUE THREAD

**Issue by nuevoalex** [ethereum/solidity#3273]
Using any of these assembly instructions:

- CREATE2
- RETURNDATACOPY
- RETURNDATASIZE
- STATICCAL

Will result in the compiler throwing a warning.

It seems like this might be something that should be removed or at least could be silenced.

**Comment by MicahZoltu** [comment]
Warning is along the lines of:
> instruction is only available after the Metropolis hard fork

**Comment by andy-mcewan-aventus-io** [comment]
Any news on silencing these warnings?
