### ISSUE TITLE
Feature Request: Composition-based inheritance

### ISSUE THREAD

**Issue by rphmeier** [ethereum/solidity#3276]
Apologies if this has already been suggested.

Currently if we want to extend the functionality of a contract `B` with some additional functionality in `A` we have two options:
  1. declare a `contract A extends B {}` and access all items of `B` from within the context of `A` implicitly. I find this can make logic harder to follow when `A` and `B` are defined in separate files.
  1. declare `contract A { B b_member; }`. This requires actually deploying another contract and being allowed only to access public items. Additionally, each call requires actually making an EVM sub-call, which is fairly expensive.

I would like to be able to declare something along the lines of

```
contract A {
    B b_member inline;
}
```

where `b_member` will be laid out in storage and code the same way as in option 1, but will function the same way as in option 2, but with private items also accessible. This kind of composition is helpful for code quality but should not harm performance.

Alternatives:
  - Only have public items accessible from an inline member contract. The member's logic may require certain invariants about the state of its storage to be upheld, and can expose a safe public interface. Bypassing the public interface could lead to invariants being broken. If access to private items is allowed, it should be actively discouraged and linted against.

**Comment by chriseth** [comment]
This actually has been considered before ("relocatable contracts"), although I think it also used calls (back then they were of course much cheaper).

So if I understand you correctly, you only want to separate the code into different files / blocks and have an implicit "self" struct that might be at a different place than the default beginning of storage, right?

**Comment by chriseth** [comment]
You currently can get something like this by using a library with internal functions and a struct as first parameter, by the way.

In general, I think the code size will get too big quite fast, so I'm not too sure this model is very useful. But I'm happy to learn of different numbers :)

**Comment by rphmeier** [comment]
> have an implicit "self" struct that might be at a different place than the default beginning of storage, right?

yes, from an implementation standpoint that sounds correct. Although one alternative would be make it work exactly as `extend` does but prefix item names with the member name. e.g. if B has a member `bar` and `A` has an inline member `B foo`, The identifier is changed to `foo.bar` instead of just `bar`. I am not familiar with solc internals so it's hard for me to say which implementation approach is easier -- although this will probably break tokenization.

> You currently can get something like this by using a library with internal functions and a struct as first parameter

Interesting! I think the ergonomics could be better but it might be worth a shot.

**Comment by chriseth** [comment]
It's actually not too different than direct inheritance. Take a look at the library code here: https://github.com/Arachnid/solidity-stringutils/blob/master/strings.sol

The main difference is that you have an explicit `self` argument like in Python, but then you can just use `a.f()` (again, like in Python). And you have the flexibility to make some functions internal and others not.
