### ISSUE TITLE
Prevent ./scripts/build.sh from marking release tag as pre-release

### ISSUE THREAD

**Issue by Sjors** [ethereum/solidity#3277]
I'm trying to build solc locally on OSX:

```
git checkout v0.4.19
./scripts/build.sh
```

Unfortunately this gets marked as a pre-release:
```
solc --version
solc, the solidity compiler commandline interface
Version: 0.4.19-develop.2017.12.4+commit.c4cbbb05.mod.Darwin.appleclang
```

This in turn causes `solc` to complain that it's too old:
```sh
$ solc contract.sol 
Warning: This is a pre-release compiler version, please do not use it in production.
contract.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.19-develop.2017.12.4+commit.c4cbbb05.Darwin.appleclang - note that nightly builds are 
considered to be strictly less than the released version
```

I can't figure out how to not make it do this...

**Comment by Sjors** [comment]
The Bitcoin Core build process [checks if a commit is tagged](https://github.com/bitcoin/bitcoin/blob/v0.15.1/share/genbuild.sh#L26-L39) and changes the version string accordingly.

**Comment by chriseth** [comment]
The build process should check if we have a git directory (this is not required) and if the current commit is tagged starting with a `v` and then create an empty file called `prerelease.txt` in the top directory. This will cause the build process to create a release binary.

At best, we should use a different mechanism that the prerelease.txt file, but we have a requirement that he build has to be possible without git.

**Comment by Sjors** [comment]
Looking for `prerelease.txt` could be a fallback when Git isn't present.

**Comment by kayuri** [comment]
@chriseth just as a temp solution would something like https://github.com/ethereum/solidity/pull/3288 work for you?

**Comment by chriseth** [comment]
@kayuri yes, that would be a good temporary solution

**Comment by chriseth** [comment]
Thanks, @kayuri! Is that sufficient for you, @Sjors ?

**Comment by Sjors** [comment]
I'll try it after the next release, but lgtm.
