### ISSUE TITLE
Calling a library function declared `internal` from a constructor of a contract throws OOG error

### ISSUE THREAD

**Issue by lsaether** [ethereum/solidity#3280]
While working on the [Ethereum Alarm Clock](https://github.com/chronologic/ethereum-alarm-clock) I was running into out of gas errors while deploying the contract `RequestFactory.sol`. I narrowed the problem down to the function `createRequest(...)` which creates an instance of the contract `TransactionRequest.sol` that calls the `RequestLib` library function `initialize(...)` in its constructor. This function was declared with an INTERNAL modifier. After debugging it was found that removing the `internal` modifier on the library function allowed the contract to deploy without issue.

Why does putting an `internal` modifier on a library function that is called in a constructor of a contract cause an out of gas error on deployment? Is this an idiosyncrasy of Solidity?

**Comment by axic** [comment]
Can you provide a short example which produces the problem?

**Comment by axic** [comment]
Please reopen if the problem persists and there's an example.
