### ISSUE TITLE
Transaction with struct as a function input is reverted

### ISSUE THREAD

**Issue by dshulyak** [ethereum/solidity#3286]
I am trying to send a struct to a function, but transcation fails with revert and i can't understand what is the error. Perhaps I misunderstood release notes and this doesn't suppose to work.

For example:
```
  struct Data {
    uint8 height;
  }

  function send(Data val) public returns(Data) {
    return val;
  }
```

I can also atach whole status from geth console, if it will be necessary:
```
{
      depth: 1,
      gas: 978316,
      gasCost: 0,
      memory: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060"],
      op: "REVERT",
      pc: 134,
      stack: ["0000000000000000000000000000000000000000000000000000000019f9a0ca", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000"],
      storage: {}
  }]
}
```

I am also using this two pragmas
```
pragma solidity ^0.4.18;
pragma experimental ABIEncoderV2;

```

**Comment by axic** [comment]
The decoder is only supported in 0.4.19 so I suggest to change your version requirement to that.

Very likely the outside library you are using to encode the data being sent doesn't prepare the proper structure. One common reason it would revert if the passed input data is shorter than the minimum length of the expected structure.

**Comment by dshulyak** [comment]
@axic thanks, for a fast answer

sorry for confusion, i am using 0.4.19
```
> solc --version
solc, the solidity compiler commandline interface
Version: 0.4.19+commit.c4cbbb05.Linux.g++
```

Could you describe the expected encoding? If I understood correctly it should be the same as for the static array, 4 bytes for function selector and 32 for each field, e.g:
```
0x8be65246 \\ function selector
  0000000000000000000000000000000000000000000000000000000000000010 \\ uint8 encoded
```

**Comment by dshulyak** [comment]
It was my mistake, i didnt notice that method signature should be different in this case, like
`emit((uint8))`

**Comment by axic** [comment]
@dshulyak oh, yes that's correct. It is the "tuple" notation in the spec. Glad it works!
