### ISSUE TITLE
How to use ICO tokens to pay for ethereum dapp smart contract transactions ?

### ISSUE THREAD

**Issue by sivachaitanya** [ethereum/solidity#3289]
Hello

Assume I had a successful token sale and sold all my tokens, now I have built an awesome dApp for the users using solidity smart contracts. Now my questions in this regard are - 

1. How will my users with ICO tokens pay for dApp transactions fee on Ethereum, should I send them in ether or token  ?

2. How to use tokens in a private chains built on Ethereum ?

3. How to use tokens to make transactions on another blockchain lets assume Ethermint for example here ?

**Comment by axic** [comment]
I think this a good question for https://ethereum.stackexchange.com.

This repository is strictly for issues regarding the Solidity language and the Solidity compiler.
