### ISSUE TITLE
Inconsistent requirements of block in FunctionDefinition.

### ISSUE THREAD

**Issue by maciejhirsz** [ethereum/solidity#3291]
edit: Forgive me for confusion, I'm literally just learning Solidity while writing a parser.

The following should be equivalent according to grammar.txt:

```
function bar() only_owner public; // this compiles
function bar() public only_owner; // this does not compile
```

Either a function with a modifier must have a block following it and the first case is a bug, or it doesn't and the second case is a bug. Can't tell which atm.

**Comment by maciejhirsz** [comment]
~Actually, it seems to be an issue with solc, will open a new issue (unless I find one)...~

Updated original issue.

**Comment by axic** [comment]
I think that should compile, but seemingly fails.

**Comment by axic** [comment]
> I think that should compile, but seemingly fails.

When I made this comment I didn't observe properly that the functions are not implemented.

I don't think it should compile if the function is not implemented. What is the point of the modifier in that case?
