### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by srameshr** [ethereum/solidity#3296]
Functional and pure methods
```
1. Filter
2. Reduce
3. Map
```
Array utilities like in JS

**Comment by axic** [comment]
I think you have 5 suggestions here?

There is already support for pure methods (with some restrictions). Check out the `pure` keyword in the documentation.

I'm not sure what you mean by "Array utilities like in JS". Can you elaborate?

The preferred way to have map/reduce and array utilities is by implementing them as Solidity libraries, though keep in mind they are really expensive operations in the EVM and very likely by structuring the problem differently they are not even needed.

**Comment by srameshr** [comment]
@axic I will close this as when I was raising these bugs I did not have enough foresight about the language.
