### ISSUE TITLE
LLL: simple way of retrieving runtime bytecode

### ISSUE THREAD

**Issue by veox** [ethereum/solidity#3298]
I'm attempting to add LLL support to [Populus](https://github.com/ethereum/populus).

This requires three components to be available:

- [x] the ABI, which for now we'll be [providing "externally"](https://github.com/ethereum/populus/issues/400), via an `.lll.abi` file;
- [x] the (deployment?) bytecode, already available via `lllc -x /path/to/contract.lll`;
- [ ] runtime bytecode, as it will be present on-chain - currently unavailable.

Could `lllc` provide this, perhaps with dedicated CLI options, e.g. `-B` and `-X`?

...Or should I look into "stripping" the bytecode (given by `lllc -x`) in Populus itself?

**Comment by axic** [comment]
I am not fully sure I understand this issue? What are the required new features for LLL here?

**Comment by veox** [comment]
Output for the equivalent of `solc`'s `evm.deployedBytecode.object`.

I'll edit the OP to be clearer.

**Comment by veox** [comment]
I've looked at [disassembly](https://gist.github.com/veox/5dcd70fc8486640237c233f7cbf15671) of a [simple LLL program](https://github.com/veox/populus/blob/e3e4adb12546cac7661643dc5b4dbc69c672e11d/tests/fixtures/Greeter.lll); and it does seem possible to just "strip" the bytecode with external tools, removing the `codecopy` head and `data` tail.

However, it might be useful if `lllc` could do this itself. (I've looked at `lllc`'s sources, too, and understood little.)

**Comment by axic** [comment]
Why do you need the "runtime bytecode"?

**Comment by veox** [comment]
`populus deploy` tests if a contract's code post-deployment matches that given by the compiler.

(Actually, I'll go ask if there's any other reason.)

**Comment by axic** [comment]
Because there's no way for `lllc` to give you it. It has no concept of creation and deployed bytecodes. The LLL source code is just like assembly, it has no restrictions. The example you've found happens to do this, but it is not a requirement presented by the compiler.

**Comment by veox** [comment]
Thank you for the clarification. Closing.
