### ISSUE TITLE
Implement bit shifting

### ISSUE THREAD

**Issue by linagee** [ethereum/solidity#33]
@hynese asks:
_Anyone know if it's possible to rotate a uint256 by 8 bits? I can't seem to find any suitable operators ;(_

(There is no lower level EVM opcode for SHL/SHR/ROR/ROL, I checked. So they must be emulated.)

It would be nice to implement:
https://github.com/ethereum/solidity/blob/develop/libsolidity/ExpressionCompiler.cpp#L1071
or this:
https://github.com/ethereum/solidity/blob/develop/libsolidity/ExpressionCompiler.cpp#L1067

Using this: (and testing, of course!)
_Shifting left by N is equivalent to multiplying by 2^N._
_Shifting right by N is (if you are using ones' complement) is the equivalent of dividing by 2^N and rounding to zero._
source: https://en.wikipedia.org/wiki/Bitwise_operation#Arithmetic_shift

SHL(input, bits) = input \* (2^bits)
SHR(input, bits) = input / (2^bits)  (then round to zero?)
Wikipedia has some code describing how to do rotate using shift, this is probably the most optimal way: https://en.wikipedia.org/wiki/Circular_shift#Implementing_circular_shifts
http://stackoverflow.com/questions/2835469/how-to-perform-rotate-shift-in-c#answer-2835503

(This also has applications for some cryptographic code, although such code is probably optimized by not using an emulated rotate/shift, it would simplify the logic of it.)

**Comment by axic** [comment]
Fixed by #1487.
