### ISSUE TITLE
Allow multiple variable declaration of the same type in the same statement

### ISSUE THREAD

**Issue by srameshr** [ethereum/solidity#3300]
Currently syntax like this is not supported.
```
uint i = 2, j, k;
```

**Comment by axic** [comment]
I think this feature may not necessarily improve readability of a contract. Do you have any use cases where this restriction adversely affects the readability of a contract?

**Comment by srameshr** [comment]
No I dont have any such use cases.
It just reduces some typing. But as you said readability might be more important in case of contracts.

**Comment by axic** [comment]
@chriseth I propose to close this issue as it goes against the general aim of the language design.

It can be reopened if it receives enough support.

**Comment by srameshr** [comment]
@axic I agree. I was just trying to cut out some typing. Il close this issue.

**Comment by antsankov** [comment]
+1 This feature would be nice.

**Comment by PipsqueakH** [comment]
+1

**Comment by AlbertSu123** [comment]
Agreed, this would be a nice feature

**Comment by ColeHoffmann** [comment]
+1

**Comment by RacketyWater7** [comment]
+1 pls add this feature.
For example currently:
address public hospitals;address public doctor1; address public laboratories;
future expectation example:
address public hospitals,  doctors, laboratories;
