### ISSUE TITLE
Audit - SOL-001: O(n​ 2​ )​ ​ compiler​ ​ output​ ​ blow-up​ ​ by​ ​ forced​ ​ warnings/errors

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3306]
The​ ​ compiler​ ​ does​ ​ not​ ​ limit​ ​ the​ ​ number​ ​ of​ ​ errors​ ​ or​ ​ warnings​ ​ reported​ ​ (characters​ ​ sent
to​ ​ stderr).​ ​ Generally​ ​ there​ ​ is​ ​ no​ ​ benefit​ ​ to​ ​ the​ ​ developer​ ​ to​ ​ receive​ ​ more​ ​ than​ ​ 1000
errors/warnings​ ​ at​ ​ once.
An​ ​ associated​ ​ problem​ ​ is​ ​ that​ ​ the​ ​ compiler​ ​ prints​ ​ the​ ​ full​ ​ line​ ​ for​ ​ each​ ​ error​ ​ message.
Therefore,​ ​ if​ ​ a ​ ​ single​ ​ line​ ​ contains​ ​ multiple​ ​ errors,​ ​ the​ ​ line​ ​ is​ ​ printed​ ​ once​ ​ every​ ​ error
found.​ ​ ​ A ​ ​ single​ ​ line​ ​ of​ ​ char​ ​ size​ ​ n ​ ​ can​ ​ create​ ​ O(n​ 2​ )​ ​ characters​ ​ of​ ​ error​ ​ output.
This​ ​ error​ ​ might​ ​ thwart​ ​ the​ ​ possibility​ ​ of​ ​ automated​ ​ verification​ ​ and​ ​ matching​ ​ of​ ​ source
code​ ​ with​ ​ bytecode,​ ​ due​ ​ to​ ​ resource​ ​ exhaustion​ ​ by​ ​ warning​ ​ messages​ ​ in​ ​ the​ ​ verification
server.
The​ ​ consequence​ ​ is​ ​ that​ ​ a ​ ​ very​ ​ small​ ​ contract​ ​ code​ ​ when​ ​ compiled​ ​ may​ ​ create​ ​ a ​ ​ huge
error​ ​ file.​ ​ For​ ​ example,​ ​ a ​ ​ 16​ ​ Kbyte​ ​ source​ ​ code​ ​ can​ ​ force​ ​ the​ ​ compiler​ ​ to​ ​ emit​ ​ 130
Mbytes​ ​ of​ ​ errors,​ ​ and​ ​ compilation​ ​ takes​ ​ 5 ​ ​ minutes.​ ​

**Comment by chriseth** [comment]
I thought we fixed that already - @axic?

**Comment by federicobond** [comment]
It’s marked as fixed in the report (blue row)

**Comment by axic** [comment]
It was fixed in 0.4.17.

There is a limit of 32 duplicates for each function and constructor, though there is no total limit on the number of errors reported.

**Comment by chriseth** [comment]
Oh I'm sorry - will take a closer look at the report :)
