### ISSUE TITLE
How to use smart contracts to increase the speed of data into the blockchain

### ISSUE THREAD

**Issue by mimitc123** [ethereum/solidity#3316]
for example

pragma solidity ^0.4.18;

contract charity_tab{
   
    
    string [] public charity;
    uint public charitySize=0;
   
    
    

  function addCharity(string a) {
    charity.push(a);
    charitySize++;
   
  }
  
 
}

This contract to add a data time about 30-40 seconds, how to improve efficiency？

**Comment by axic** [comment]
I think this question is more suited for https://ethereum.stackexchange.com
