### ISSUE TITLE
sha() crashes on structs

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#332]
```
contract test {

    struct TestStruct {
        uint a;
    }

    function test() {
        TestStruct memory testing = TestStruct({a: 1});
        sha3(testing);
    }
}
```

**Comment by tjade273** [comment]
This also seems to happen with arrays.

**Comment by chriseth** [comment]
This feature is not yet implemented.

**Comment by axic** [comment]
> This also seems to happen with arrays.

Arrays have been fixed since.

**Comment by pirapira** [comment]
I was able to reproduce the original problem.  Since #980 exists, this issue can be closed when the crash is fixed.
