### ISSUE TITLE
When will translate the documentation to Simplified Chinese(简体中文)？

### ISSUE THREAD

**Issue by zhuangjinxin** [ethereum/solidity#3320]
Up to now, many institutions and individuals try to translate this documentation to simplified chinese, like `http://wiki.jikexueyuan.com/project/solidity-zh/introduction.html`.

Documentation: `http://solidity.readthedocs.io/en/develop/`

**Comment by ChrisChinchilla** [comment]
A note here for @axic and @chriseth I met some people at DAppcon who might help with regular Chinese translation. I will follow up soon.

**Comment by ChrisChinchilla** [comment]
@zhuangjinxin Are you also interested in helping with a translation? I think the other people I spoke with are interested in Mandarin, but I will confirm. If you are, I have a plan in place and am happy to share it with you. :)

**Comment by ChrisChinchilla** [comment]
Now in progress on #4989
