### ISSUE TITLE
Why get* functions not use modifier to check and revert wrong input params? 

### ISSUE THREAD

**Issue by lisuyong** [ethereum/solidity#3321]
Hi there, I’m confused that why so many constant get* functions not use modifier to check and revert wrong input params. Just as follows from [gnosis multisig wallet](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L289).

```
    function getConfirmationCount(uint transactionId)
        public
        constant
        returns (uint count)
    {
        for (uint i=0; i<owners.length; i++)
            if (confirmations[transactionId][owners[i]])
                count += 1;
    }
```

If the transactionId isn't in the confirmations map, why not use modifier to check and then revert it?

I know the revert is normally used to clear state changes and save gas. And the map with new key have default 0 value.

And, if I follow as the code say, I'll maybe get a 0 value result.

So the question is how can I know what I got is because “I passed wrong params” or “the result is just 0” ?

Thanks,
Justin

**Comment by chriseth** [comment]
This does not look like a language / compiler issue. Please reopen if you think otherwise.
