### ISSUE TITLE
SOL-005 Unbounded gas cost when deleting dynamically sized arrays

### ISSUE THREAD

**Issue by mvglasenapp** [ethereum/solidity#3324]
**Description**

The “delete” operation when applied to a dynamically sized array in Solidity generates code to delete each of the elements contained. If the array is large, this operation can surpass the block gas limit and raise an OOG exception. Also nested dynamically sized objects can produce the same results.

**Recommendations**

Warn the user of the implications of deleting dynamically sized arrays.

**Comment by axic** [comment]
@soad003 are you interested in adding a static analyzer module for this?

**Comment by soad003** [comment]
@axic sounds good. I will take a look.

**Comment by axic** [comment]
@soad003 was there any progress on static analyzer part?

@leonardoalt are you interested in this?

**Comment by chriseth** [comment]
The idea is to add a static analyzer module to remix here, right?

**Comment by axic** [comment]
Yes.

**Comment by soad003** [comment]
https://github.com/ethereum/remix/pull/766

**Comment by axic** [comment]
This was fixed in 
https://github.com/ethereum/remix/pull/766.
