### ISSUE TITLE
SOL-006 Duplicated super-constructor calls not reported

### ISSUE THREAD

**Issue by mvglasenapp** [ethereum/solidity#3325]
**Description**

Solidity has two methods to define super constructor calls: the first one is embedding the arguments in super contract definition and the second is by declaring a new constructor and adding the name and arguments for the super contract. If both methods are used concurrently, the constructor definition is used. However, the compiler does not warn the user that the first set of arguments has been overridden by the second.
The following example shows the problem. The parent constract is constructed with the
argument 40, not 20.

```
pragma solidity ^0.4.16;

contract P1 {
constructor P1(uint v) {}
}
contract P2 is​ ​P1(20)​ {
function P2(uint v)​ ​P1(40)​ {
}
}
```

**Recommendations**

Either prevent the user from defining two super-constructors or warn if one super-constructor overrides the other.

**Comment by chriseth** [comment]
In addition to the above, conflicting super constructor arguments should also be an error in a multi-inheritance setting.

**Comment by chriseth** [comment]
Furthermore, if parentheses are given, the number of arguments has to match the number of parameters (currently, empty parentheses is the same as no parentheses).
