### ISSUE TITLE
SOL-008 CPU blow-up using huge bignums literals

### ISSUE THREAD

**Issue by mvglasenapp** [ethereum/solidity#3327]
**Description**

The Solidity compiler accepts numeric literals of arbitrary precision. But computing those literals can take arbitrary high time.
When the following sample contract is compiled, the compiler runs for several hours (we’ve not waited until it finishes):

contract BIGNUMTEST {
function bignum() {
uint c;
c=1E10000000;
}
}

**Recommendations**

Limit the size of numeric literals.

**Comment by chriseth** [comment]
Proposal: Limit the number of rational numbers to some sane value (4096 bits) and throw a FatalError otherwise.

**Comment by chriseth** [comment]
The relevant point is `RationalNumberType::binaryOperatorResult`. We cannot throw an exception there, but we can return a null pointer.
