### ISSUE TITLE
SOL-009 Output messages size blow-up using huge bignums literals

### ISSUE THREAD

**Issue by mvglasenapp** [ethereum/solidity#3328]
**Description**

The Solidity compiler accepts numeric literals of arbitrary precision. When a literal is assigned to a variable of shorter size, an error will be written to stderr containing the expanded representation of the literal.

For example, the following code, generates an error output of approximate size 600 KBytes:

```
contract BIGNUMTEST {
function bignum() {
uint c;
c=1E600000;
}
}
```

The huge error line is:
filename.sol:4:5: Error: Type int_const 100000000000000000…..…..000000000
is not implicitly convertible to expected type uint256.

Since computing the 1E600000 integer takes approximately 30 seconds, the same output blow-up can be obtained by forcing multiple conversion errors.

The following example generates a 6 Mbyte output in only 6 seconds:

contract BIGNUMTEST {
function bignum() {
uint c;
c=1E10000;c=1E10000;c=1E10000;
c=1E10000;c=1E10000;c=1E10000;
c=1E10000;c=1E10000;c=1E10000;
...last line repeated 200 times …
}
}

**Recommendations**

● Shorten literal constants by replacing intermediate digits by “...” when printing errors to
stderr (e.g. 1000...000)
● Reduce the number of warnings/errors written to stderr

**Comment by mekkanik** [comment]
If the fix for SOL-008 is accepted (https://github.com/ethereum/solidity/pull/3348), the error message will be different, and much shorter for values over 1E1232. For 1E1232, the error message length is approximately 1586 bytes. The new error message will be along the lines of:

```
biginttest.sol:6:11: Error: Invalid literal value.
        c=1E1233;
          ^----^
```

**Comment by federicobond** [comment]
You are right, there is no blowup with #3348 but a readability improvement nonetheless.

**Comment by mekkanik** [comment]
Also I figure that there are other ways to cause this. Will look into this.
