### ISSUE TITLE
SOL-010 Easy underhanded code using false overrides

### ISSUE THREAD

**Issue by mvglasenapp** [ethereum/solidity#3329]
**Description**

Solidity smart contracts often override a function defined in a parent contract to restrict it access, for example, by adding an onlyOwner() modifier. However function overrides only work when the exact function signature is used (same argument types and same return parameters). It’s easy to make small changes in the function signature that may go unnoticed by a reviewer and that will expose the parent function without restrictions.
The following is an example contains a hidden backdoor by not providing the correct override:
```
pragma solidity ^0.4.13;

// String Helper contract library
library String {
function equals(string memory _a, string memory _b) internal returns (bool) {
bytes memory a = bytes(_a);
bytes memory b = bytes(_b);
if (a.length != b.length)
return false;

for (uint i = 0; i < a.length; i ++)
if (a[i] != b[i])
return false;
return true;
}
}

contract MyEtherWallet {
using String for string;
event onWithdrawal(string logmsg,address a);
function MyEtherWallet() {
}
// Basic function to withdraw an amount of funds from the Token contract
function withdrawFunds(string logmsg) returns(bool) {
if (logmsg.equals("OWNER"))
onWithdrawal(logmsg,msg.sender);
return msg.sender.send(this.balance);
}
}

contract MyProtectedWallet is MyEtherWallet {

address owner;
function MyProtectedWallet() {
owner = msg.sender;
}
// This function restricts withdrawals to the contract owner and
// fixes log msg.
function withdrawFunds(String logmsg) returns(bool) {
if (msg.sender!=owner)
return false;

return super.withdrawFunds("OWNER");
}
}
```

The widrawalFunds() method that is supposed to override the parent, uses the String type instead of the string type, and therefore does not override the parent.
The same can be accomplished by replacing an int argument with an uint argument.

**Recommendations**

Modify the solidity language to require the keyword “override” as modifier to function definitions
in these cases. The compiler should generate an error when attempting to compile a method
with the override modifier which does not override a parent method.

**Comment by axic** [comment]
This is discussed in #2563.
