### ISSUE TITLE
Property overwriting not working?

### ISSUE THREAD

**Issue by danutavadanei** [ethereum/solidity#3336]
**Description**

The solidity compiler accepts inheritance overloading of both modifiers and functions. But what about properties?

Check this example:
```sol
pragma solidity ^0.4.18;

contract Animal {
    uint256 public age;
    
    function getAnimalAge() public constant returns (uint256) {
        return age;
    }
}


contract Dog is Animal {
    uint256 public age;
    
    function Dog(uint256 _age) public {
        age = _age;
    }
    
    function getDogAge() public constant returns (uint256) {
        return age;
    }
}
```

In this case, by initializing `Dog` contract with age 20 one would expect that `Animal` age property to be 20, right? No, this doesn't happen. Calling `getDogAge` function will return `20` and calling `getAnimalAge` will return `0`.

I know solidity inheritance doesn't work as in other standard programming languages but shouldn't the inherit from properties that are overloaded  to have the value assigned in the child?

You can test that out [here](https://ethfiddle.com/mtn7Pbpqhs).

**Comment by chriseth** [comment]
Might be the same as https://github.com/ethereum/solidity/issues/2563

**Comment by wbt** [comment]
See also #3675.

**Comment by Marenz** [comment]
This example now gives an error when you try to override the property. I assume that finishes this ticket,  if you feel different please re-open and discuss with us :)
