### ISSUE TITLE
How to debug the failure transaction to a contract?

### ISSUE THREAD

**Issue by kenneth-1024** [ethereum/solidity#3353]
Hi all,
I am new to the ethereum contract, and want to learn how to debug it.
I have sent a transaction to my contract, and it failed. From the https://etherscan.io/tx/0x20a79ec615ca8c4668016624e83b82ffc1a54f61b90f05e0e531fda29fc0b4d1, it just failed and without any error information. In fact I have the source, and I know there are several "require" statements in the contract call, so I can guess one of the require failed and the call is reverted. 
But is there anyway to debug which line or statement of the contract failed, just like we debug in Javascript or other language? 

Any help will be appreciated.

**Comment by axic** [comment]
You could try https://remix.ethereum.org for debugging or the `Tools & Utilities` dropdown on etherscan.

This seems to be a question better suited for http://ethereum.stackexchange.com
