### ISSUE TITLE
Left menu scrolls alongside with the main page

### ISSUE THREAD

**Issue by IvanYurchenko** [ethereum/solidity#3367]
Here's it: when you scroll the left menu itself it scrolls fine, but when you scroll an article that's on the right side the left side menu is scrolling as well which is definitely not correct behavior.

![screenshot](https://d1ro8r1rbfn3jf.cloudfront.net/ms_105836/x0nR3MdZPin14NZXON9kc2EEoerYbk/2018-01-01%2B13.02.03%2BSolidity%2Bby%2BExample%2B%25E2%2580%2594%2BSolidity%2B0.4.20%2Bdocumentation%2B-%2BGoogle%2BChrome.png?Expires=1514890961&Signature=nooioFTEcyQTGRny288cE~RRpBV6t1qcrm2VhOWpfzFQlPySOcEB7yofGZ7Oak6giaFc9j2oZeA8YNRQvK2y2QfFfe8awT5huRbPqHEP6NT9Kq3uLK-MeZNo7rjSxYqel909FC1hL1sue7pYbPN16eIn1hemZ6PXI9QSdBZEFd4Os0gMD53luvv3vM9GLV71aA8nzDtJPkGh54HHfJqXj20lMM00Kvoj7JnDzdg7mcXh~S2vMfldVooe8Nz-3jf-Yb37TDy09NjI~-COQOQZf-UD6kmW9RxAWRZBedKKFumC39ywgcd9RCgKSodl8hM6EfTpn6S7HzxaOAcb-x6e4g__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

![screenshot2](https://d1ro8r1rbfn3jf.cloudfront.net/ms_105836/Bgduhm1D6aAAjH9BCZsRoY02sx0uTh/2018-01-01%2B13.03.24%2BSolidity%2Bby%2BExample%2B%25E2%2580%2594%2BSolidity%2B0.4.20%2Bdocumentation%2B-%2BGoogle%2BChrome.png?Expires=1514891016&Signature=Ay40o8yckToNHf~GSFiG4JU6I-q4D4G77SW0Vo58S-lonfVYQ6X6J3A2OTOU6oT4pZAxshXGXWag1X48iZyOxrFu84FjUGk-W3sxrkQReon524PkoDDeTLBT0lmTePH-4ASn1MhKFtk9-NTQvXf-sZhEj~PsWtGgapGO4q~CHfYrUSAfxX9i1HdB212yRotlNeS94bpQwYgyv2QI3oWmtEmo2x0t~VE58-3HLtkzx5kfsH9K1ivvS1YjQK4U5qtmY1WnFdB2Ub90vRA1J0pEla-UO~h3SfXKufI3EAVDn5m7OkGltOQe6u5L4UdvNNndUKFcQ86wNBV2VJLtQXXj7A__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Chrome 63.0.3239.84, Windows 10

**Comment by axic** [comment]
@IvanYurchenko I do not see this happening here, but the documentation is running on readthedocs. Please report such issues with readthedocs.org.
