### ISSUE TITLE
Allow making raw calls returning a value.

### ISSUE THREAD

**Issue by clesaege** [ethereum/solidity#3368]
Currently the function for making raw calls is `call`, however the documentation (p42 https://media.readthedocs.org/pdf/solidity/develop/solidity.pdf) specifies that 

> It is not possible to access the actual data returned (for this we would need to know the encoding and size
> in advance).

It would be nice to have a way to make a raw call returning the raw return value. Or to have a raw call where the return value can be specified.

It should work like:
`var (x, y) = callReturn[uint, string](bytes4(keccak256("fun(uint256)")), 5778));`

That's a real need, in my case for action callback https://github.com/kleros/kleros-interaction/issues/13.

**Comment by axic** [comment]
For callbacks I suggest to have a look at http://solidity.readthedocs.io/en/develop/types.html?#function-types.

Regarding returning data please see #434. And for ABI decoding see #1707.

**Comment by clesaege** [comment]
Thanks.
I was aware of #1707 but not of #434. I'll move the discussion to #434.
