### ISSUE TITLE
Improve install instructions

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3376]
Install instructions at http://solidity.readthedocs.io/en/develop/installing-solidity.html includes many install options. The first recommendation is:

    npm install -g solc

The usage instructions are at http://solidity.readthedocs.io/en/develop/using-the-compiler.html and begin with:

    solc

----

If you buy a new Mac, then install and run Xcode, per instructions, and then run those two commands you will get:

> command not found: solc

**Comment by axic** [comment]
Please note the text above the `npm install` command which reads:

> It also contains a commandline tool called solcjs, which can be installed via npm:
> npm install -g solc

It mentions that the installed tool will be called `solcjs`. It may be a bit confusing - do you have any suggestions to improve the wording? A pull request would be welcome if you are interested.

**Comment by fulldecent** [comment]
Thanks for explaining. Here is a brief pair of PRs.

**Comment by fulldecent** [comment]
Merged. Fixed in https://github.com/ethereum/solidity/commit/c7632fc732dcd49bb3add1aea1d9fdc05612c034
