### ISSUE TITLE
All code examples should use the latest released version of Solidity

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3379]
As per http://solidity.readthedocs.io/en/develop/installing-solidity.html?highlight=latest we see:

> We recommend using the latest release. 

The latest version is 0.4.19 as per https://github.com/ethereum/solidity/releases

The Solidity code examples in the documentation, therefore, should also use version 0.4.19.

---

Following are the examples to update, found with `git grep --line-number 'pragma solidity'`.

Work plan:

- Run the existing code under 0.4.19
- Fix any warnings
- Fix the code and the update the compiler version

---

- [x] [abi-spec.rst:190](https://github.com/ethereum/solidity/blob/develop/docs/abi-spec.rst): `pragma solidity ^0.4.0;`
- [x] [abi-spec.rst:335](https://github.com/ethereum/solidity/blob/develop/docs/abi-spec.rst): `pragma solidity ^0.4.0;` -- no necessary change
- [x] [abi-spec.rst:382](https://github.com/ethereum/solidity/blob/develop/docs/abi-spec.rst): `pragma solidity ^0.4.19;`
- [ ] [assembly.rst:54](https://github.com/ethereum/solidity/blob/develop/docs/assembly.rst): `pragma solidity ^0.4.0;`
- [ ] [assembly.rst:81](https://github.com/ethereum/solidity/blob/develop/docs/assembly.rst): `pragma solidity ^0.4.12;`
- [ ] [assembly.rst:387](https://github.com/ethereum/solidity/blob/develop/docs/assembly.rst): `pragma solidity ^0.4.11;`
- [ ] [assembly.rst:462](https://github.com/ethereum/solidity/blob/develop/docs/assembly.rst): `pragma solidity ^0.4.0;`
- [ ] [assembly.rst:713](https://github.com/ethereum/solidity/blob/develop/docs/assembly.rst): `pragma solidity ^0.4.0;`
- [ ] [common-patterns.rst:31](https://github.com/ethereum/solidity/blob/develop/docs/common-patterns.rst): `pragma solidity ^0.4.11;`
- [ ] [common-patterns.rst:68](https://github.com/ethereum/solidity/blob/develop/docs/common-patterns.rst): `pragma solidity ^0.4.11;`
- [ ] [common-patterns.rst:133](https://github.com/ethereum/solidity/blob/develop/docs/common-patterns.rst): `pragma solidity ^0.4.11;`
- [ ] [common-patterns.rst:275](https://github.com/ethereum/solidity/blob/develop/docs/common-patterns.rst): `pragma solidity ^0.4.11;`
- [ ] [contracts.rst:43](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:176](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:192](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:235](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:255](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:269](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:304](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.11;`
- [ ] [contracts.rst:423](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:461](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:497](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:558](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:603](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:621](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:653](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:717](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:772](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.10;`
- [ ] [contracts.rst:819](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:891](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:920](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:964](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:1005](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:1034](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:1044](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.0;`
- [ ] [contracts.rst:1079](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.11;`
- [ ] [contracts.rst:1125](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:1199](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:1303](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [contracts.rst:1353](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:23](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:39](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:102](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:129](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.0;`
- [ ] [control-structures.rst:184](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.0;`
- [ ] [control-structures.rst:205](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:228](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.0;`
- [ ] [control-structures.rst:277](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:334](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.16;`
- [ ] [control-structures.rst:371](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.0;`
- [ ] [control-structures.rst:417](https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:114](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.16;`
- [ ] [frequently-asked-questions.rst:143](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:188](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:235](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.16;`
- [ ] [frequently-asked-questions.rst:315](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:348](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:374](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:458](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.0;`
- [ ] [frequently-asked-questions.rst:506](https://github.com/ethereum/solidity/blob/develop/docs/frequently-asked-questions.rst): `pragma solidity ^0.4.16;`
- [ ] [introduction-to-smart-contracts.rst:19](https://github.com/ethereum/sintroduction-to-smart-contracts.rstolidity/blob/develop/docs/): `pragma solidity ^0.4.0;`
- [ ] [introduction-to-smart-contracts.rst:83](https://github.com/ethereum/sintroduction-to-smart-contracts.rstolidity/blob/develop/docs/): `pragma solidity ^0.4.0;`
- [ ] [layout-of-source-files.rst:26](https://github.com/ethereum/solidity/blob/develop/docs/layout-of-source-files.rst)`pragma solidity ^0.4.0;`
- [ ] [layout-of-source-files.rst:198](https://github.com/ethereum/solidity/blob/develop/docs/layout-of-source-files.rst): `pragma solidity ^0.4.0;`
- [ ] [miscellaneous.rst:51](https://github.com/ethereum/solidity/blob/develop/docs/miscellaneous.rst): `pragma solidity ^0.4.0;`
- [ ] [security-considerations.rst:58](https://github.com/ethereum/solidity/blob/develop/docs/security-considerations.rst): `pragma solidity ^0.4.0;`
- [ ] [security-considerations.rst:81](https://github.com/ethereum/solidity/blob/develop/docs/security-considerations.rst): `pragma solidity ^0.4.0;`
- [ ] [security-considerations.rst:99](https://github.com/ethereum/solidity/blob/develop/docs/security-considerations.rst): `pragma solidity ^0.4.11;`
- [ ] [security-considerations.rst:183](https://github.com/ethereum/solidity/blob/develop/docs/security-considerations.rst): `pragma solidity ^0.4.11;`
- [ ] [security-considerations.rst:203](https://github.com/ethereum/solidity/blob/develop/docs/security-considerations.rst): `pragma solidity ^0.4.11;`
- [ ] [solidity-by-example.rst:39](https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst): `pragma solidity ^0.4.16;`
- [ ] [solidity-by-example.rst:217](https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst): `pragma solidity ^0.4.11;`
- [ ] [solidity-by-example.rst:374](https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst): `pragma solidity ^0.4.11;`
- [ ] [solidity-by-example.rst:527](https://github.com/ethereum/solidity/blob/develop/docs/solidity-by-example.rst): `pragma solidity ^0.4.11;`
- [ ] [structure-of-a-contract.rst:23](https://github.com/ethereum/solidity/blob/develop/docs/structure-of-a-contract.rst): `pragma solidity ^0.4.0;`
- [ ] [structure-of-a-contract.rst:43](https://github.com/ethereum/solidity/blob/develop/docs/structure-of-a-contract.rst): `pragma solidity ^0.4.0;`
- [ ] [structure-of-a-contract.rst:65](https://github.com/ethereum/solidity/blob/develop/docs/structure-of-a-contract.rst): `pragma solidity ^0.4.11;`
- [ ] [structure-of-a-contract.rst:89](https://github.com/ethereum/solidity/blob/develop/docs/structure-of-a-contract.rst): `pragma solidity ^0.4.0;`
- [ ] [structure-of-a-contract.rst:113](https://github.com/ethereum/solidity/blob/develop/docs/structure-of-a-contract.rst): `pragma solidity ^0.4.0;`
- [ ] [structure-of-a-contract.rst:134](https://github.com/ethereum/solidity/blob/develop/docs/structure-of-a-contract.rst): `pragma solidity ^0.4.0;`
- [ ] [types.rst:334](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.16;`
- [ ] [types.rst:412](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.16;`
- [ ] [types.rst:422](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.16;`
- [ ] [types.rst:473](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.11;`
- [ ] [types.rst:542](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.0;`
- [ ] [types.rst:625](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.16;`
- [ ] [types.rst:646](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.16;`
- [ ] [types.rst:669](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.0;`
- [ ] [types.rst:708](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.16;`
- [ ] [types.rst:780](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.11;`
- [ ] [types.rst:872](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.0;`
- [ ] [types.rst:915](https://github.com/ethereum/solidity/blob/develop/docs/types.rst): `pragma solidity ^0.4.0;`

---

Follow on work:

- [ ] Update [the build script](https://github.com/ethereum/solidity/blob/develop/.travis.yml) to test for this automatically

**Comment by fulldecent** [comment]
It will be helpful if someone with authority can say "all code with 0.4.16 can compile without warnings on 0.4.19 with no changes necessary".

**Comment by axic** [comment]
Please note those are the minimum versions required by each example. Since it uses semver, `^0.4.0` means it will also compile with `0.4.19`.

Every change is backwards compatible, fixing warnings emitted by 0.4.19 will still results in a compilable code on 0.4.0.

**Comment by fulldecent** [comment]
Counter example:

This compiles in 0.4.19 but not in 0.4.0:

```
pragma solidity ^0.4.19;

contract A {
    function a() public pure;
}
```

**Comment by axic** [comment]
I do not exactly follow what counter example is this?

**Comment by fulldecent** [comment]
You stated "fixing warnings emitted by 0.4.19 will still results in a compilable code on 0.4.0."

This counter example shows a contract where warnings are fixed in 0.4.19 but where the code does not compile in 0.4.0.

**Comment by axic** [comment]
That is a response to your original issue listing this task:
> Fix any warnings

What I've said is that fixing warnings in the code to make the 0.4.19 compiler silent will still result in code which can be compiled with `>=0.4.0` (if the given pragma is `^0.4.0`).

If there is a given code piece which already requires a higher version, that is for a reason, which is it uses a feature introduced in that given version.

You have also mentioned that all pragmas should be updated to require the latest version:
> The Solidity code examples in the documentation, therefore, should also use version 0.4.19.

I do not agree with this, all examples should use the minimum version they require.

**Comment by fulldecent** [comment]
Here is a screenshot where the 0.4.19 compiler using 0.4.0 pragma does recommend a change that is incompatible with 0.4.0.

![screen shot 2018-01-23 at 9 11 06 pm](https://user-images.githubusercontent.com/382183/35310945-fca528a6-0081-11e8-8db7-9b160ee7583e.png)

**Comment by fulldecent** [comment]
When developing documentation I subscribe to the best practices: 

* Warnings are errors
* If a code example causes an error with the latest released compiler then the code example should be fixed

Currently "Improving the documentation" is the [first item listed](http://solidity.readthedocs.io/en/latest/contributing.html) for contributors to help with. If a different set of best practices apply for code snippets in the Solidity project, then it would be helpful to spell that out in http://solidity.readthedocs.io/en/latest/contributing.html so contributors can make more useful contributions.

**Comment by axic** [comment]
I've never opposed adding state mutability modifiers (pure, view) to examples (I think somebody started doing that in a PR a while back). If we do that, of course the version requirement must bump to where it was introduced.

**Comment by fulldecent** [comment]
Cool. So basically most things before 0.4.16 are at least in scope for an update to 0.4.16 for mutability guarantees. If I can find an important feature past 0.4.16 then that's a reason to upgrade further. But otherwise, maintain the oldest supported prama for any given code.

Here's a first step: https://github.com/ethereum/solidity/pull/3431

**Comment by leonardoalt** [comment]
Currently (v0.5.0) almost all examples in the documentation have the form `pragma solidity >=0.4.0 <0.6.0` which is correct. There are 3 "wrong" ones that should be checked.

**Comment by ChrisChinchilla** [comment]
@leonardoalt after a quick search I can't see any more now, unless you can point me to those remaining 3 (possibly 2, as one was fixed in https://github.com/ethereum/solidity/commit/af3e6db038c0ef2ce847537129e19deaec3c906a)

**Comment by leonardoalt** [comment]
The different ones that I found:
```
050-breaking-changes.rst:   pragma solidity ^0.4.25;
050-breaking-changes.rst:   pragma solidity ^0.4.25;
layout-of-source-files.rst:  pragma solidity ^0.4.0;
```

**Comment by ChrisChinchilla** [comment]
@leonardoalt I think all of these are intentional if you read the context around them. As far as I can tell, this issue is now resolved.

**Comment by chriseth** [comment]
The one in `layout` could be updated, but does not have to.

Furthermore, shouldn't we change all `0.4.99` to `0.5.0`?

**Comment by ChrisChinchilla** [comment]
@chriseth I guess we should. I shall update and hope that all tests still pass.
