### ISSUE TITLE
lllc is missing SHA3 opcode

### ISSUE THREAD

**Issue by winsvega** [ethereum/solidity#3387]
https://github.com/ethereum/solidity/blob/dd9416be29e9ac22b9b2a33cb9424514067cc6bf/libevmasm/Instruction.cpp

YP says that there shoul be SHA3 opcode at 0x20.
is it correct that lllc is missing that code?
  
looks like it using KECCAK256 instead. a bit of a naming issue is confusing.

**Comment by axic** [comment]
It is called `KECCAK256` in the assembler, the Solidity inline assembly and llc both have an alias for `sha3`.

**Comment by FrankSzendzielarz** [comment]
https://medium.com/@ConsenSys/are-you-really-using-sha-3-or-old-code-c5df31ad2b0

**Comment by axic** [comment]
@winsvega closing this, please use `keccak256`.
