### ISSUE TITLE
Native solidity staticcall  

### ISSUE THREAD

**Issue by leviadam** [ethereum/solidity#3388]
Hi,

I wanted to suggest an enchantment.
To allow solidity to use the new staticcall not just as assembly, but be able to do something like:
```contract.static.function(arg1, arg2); ```

Hope this is not a repost, searched old issues and couldn't find anything similar.

Adam.

**Comment by axic** [comment]
Note the compiler (once the feature is enabled) will automatically use `staticcall` if the function is marked `view` or `pure`. For `public` functions the static call can be enforced by using the external interface, e.g. `this.mypurefunction(1,2);`

**Comment by leviadam** [comment]
Is there a timeline when this feature will be enabled?

**Comment by maurelian** [comment]
When the tests are written I guess: https://github.com/ethereum/solidity/pull/2966

**Comment by axic** [comment]
Done via #2966.
