### ISSUE TITLE
invalid solidity type!: tuple[]

### ISSUE THREAD

**Issue by OlyRice** [ethereum/solidity#3394]
I have tried on Stack Exchange [here](https://ethereum.stackexchange.com/questions/36229/invalid-solidity-type-tuple) with no luck so far so I thought I would try here. I have a contract with the following at the top.

`pragma solidity ^0.4.18;
pragma experimental ABIEncoderV2;`

I then call from JQuery the following function within that contract. The aim is to return an array that contains structs. 

```
function getAllLand() external view returns (Land[]) {
        return landRegister;
    }
```

The problem is that the console is throwing an error that states 

> invalid solidity type!: tuple[]

. I am running the contract on a test network, any ideas why this error might be thrown? Cheers

**Comment by VoR0220** [comment]
This hasn't been implemented yet in the ethereumjs-abi is my guess.

**Comment by axic** [comment]
I think the example code you are following on stackexchange uses web3.js. Please open an issue on https://github.com/ethereum/web3.js.
