### ISSUE TITLE
What is an owning contact?

### ISSUE THREAD

**Issue by Tusharchoudhary** [ethereum/solidity#3395]
While going through *solidity* [documentation](https://solidity.readthedocs.io/en/develop/introduction-to-smart-contracts.html) I came across a term 'the owning contract' which i didnt understand.

> A contract in the sense of Solidity is a collection of code (its functions) and data (its state) that resides at a specific address on the Ethereum blockchain. The line uint storedData; declares a state variable called storedData of type uint (unsigned integer of 256 bits). You can think of it as a single slot in a database that can be queried and altered by calling functions of the code that manages the database. In the case of Ethereum, this is always **the owning contract**. And in this case, the functions set and get can be used to modify or retrieve the value of the variable.

**Comment by aj07** [comment]
@axic in docs this seems to be very clearly understandable. Should we close it?

**Comment by chriseth** [comment]
I think 'owning' is still the wrong term here.

**Comment by aj07** [comment]
can we put the word "changeable" or "dynamic" in place to owning?

**Comment by OTTTO** [comment]
if "owning" means the contract that contains the specified code then it seems fine to me.
