### ISSUE TITLE
crash - calling constructor from derived contract

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/solidity#340]
Trying to compile https://chriseth.github.io/browser-solidity/?gist=0e96e870387a6479d2e5 crashes the compiler.

When I change the conract DAO.sol line 154 sol, to not call the constructor of the base contract, it doesn't crash.

**Comment by chriseth** [comment]
Fix is in #342 . Another problem was that in CrowdfundingInterface, you define a function called Crowdfunding which is also visible in the derived contracts and shadows the constructor of Crowdfunding.
