### ISSUE TITLE
SMTChecker - simple contract throws 'Internal compiler error during compilation'

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/solidity#3405]
* Version: 0.4.20-develop.2018.1.17+commit.4715167e.Linux.g++

I found a contract where the SMTChecker throws a very weird error and I am unsure if this is a known issue. The error is:

```
Internal compiler error during compilation:
solidity-git/src/solidity/libsolidity/formal/SMTChecker.cpp(762): Throw in function dev::solidity::smt::Expression dev::solidity::SMTChecker::currentValue(const dev::solidity::Declaration&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

To reproduce, this simplified contract is enough:
```
pragma experimental SMTChecker;
pragma solidity ^0.4.18;

contract Test {
	modifier t {
		 require(msg.sender == addr);
		 _;
	}

	address public addr;
}
```

SMTChecker works fine for various other contracts

**Comment by leonardoalt** [comment]
Thanks for the report!
This bug is very likely caused by the SMTChecker not yet supporting storage vars.

**Comment by axic** [comment]
At the minimum the message should be a bit more clear (e.g. the assertion to have a proper reason).

**Comment by leonardoalt** [comment]
Yes, this shouldn't happen, I'll fix it.
