### ISSUE TITLE
CALL with string

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#341]
https://chriseth.github.io/browser-solidity/?gist=9910135d68ac7f30815b
Create SimpleRegistry, then create Proxy.
On Proxy do `forward_method` with input like:
`"0x692a70d2e424a56d2c6c27aa97d1a86395877b3a", 0, 0, ["0xcde", "0x1234567890123456789012345678901234567890"]`
(make sure you use address of SimpleRegistry if it's different for you)

On SimpleRegistry do `lookup` with input "0xcde" and the output is zero incorrect.
`_transactionData` is `bytes32[]` and how to make it work with `string` ?

If you replace `string` with `bytes32` as in 
https://chriseth.github.io/browser-solidity/?gist=e6d8e79383f4ba57cbcb
and do the same steps above, you get correct output that is not zero.

**Comment by chriseth** [comment]
This is because strings are encoded in a different way than `bytes32` - their data is appended at the end (among other things). If you use `call`, you have to do the ABI encoding yourself.
