### ISSUE TITLE
why  error en Etherdelta??

### ISSUE THREAD

**Issue by olidyver** [ethereum/solidity#3410]
I made a transaction to upload my token in etherdelta but it gives me TxReceipt Status: Fail, does anyone know what I could be doing wrong?
https://etherscan.io/tx/0x35d005938651e32ea04b69d9b0b2dc93e6a44265613dcb938cc54e699be8f58e

**Comment by axic** [comment]
I think the best place to ask this question is on https://ethereum.stackexchange.com
