### ISSUE TITLE
Compiler should complete even if contract is not fully implemented

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3428]
Currently, the compiler will not run if contract/interface methods are left unimplemented.

Instead the compiler should run if there are no syntactical/grammar errors.

Why? Because the compiler parses NatSpec and NatSpec is useful even for incomplete contracts and for interfaces.

![screen shot 2018-01-23 at 7 52 08 pm](https://user-images.githubusercontent.com/382183/35308745-294cc518-0077-11e8-922f-bbe940ea9d9e.png)
![screen shot 2018-01-23 at 7 52 55 pm](https://user-images.githubusercontent.com/382183/35308751-315ae7e4-0077-11e8-8107-ce6fc8b56931.png)
![screen shot 2018-01-23 at 7 53 11 pm](https://user-images.githubusercontent.com/382183/35308758-356a258e-0077-11e8-88de-6de9d06ed768.png)
![screen shot 2018-01-23 at 7 53 14 pm](https://user-images.githubusercontent.com/382183/35308761-37c99ad0-0077-11e8-87dc-aa98f86e0b46.png)

**Comment by axic** [comment]
> Currently, the compiler will not run if contract/interface methods are left unimplemented.

Please verify that is the case with the Solidity commandline tool (`solc`). Not sure what exactly "will not run" means, but the screenshots only show fields (apart from the `methodHashes`) which are relevant for bytecode output.

Remix IDE related issues should not be reported here.

**Comment by fulldecent** [comment]
Thank you @axic, I have followed your advice and confirm `solc` DOES work as expected. Closing issue. Adding notes. Reporting downstream.

TEST CASE:

```
pragma solidity ^0.4.19;

/// @title A simulator for Bug Bunny, the most famous Rabbit
/// @author Warned Bros
/// @notice You can use this contract for only the most basic simulation
/// @dev All function calls are currently implement without side effects
interface BugsBunny {
    /// @author Bob Clampett
    /// @notice Determine if Bugs will or will not accept given food
    /// @dev Food must be provided in UTF-8 format
    /// @param _food The name of a food to evaluate (English)
    /// @return true if Bugs will eat it, false otherwise
    function doesEat(string _food) public pure returns (bool);
}
```

COMMAND:

```sh
./solc --devdoc --userdoc bunnyint.sol
```

OUTPUT:

```
======= /Users/williamentriken/Desktop/bunnyint.sol:BugsBunny =======
Developer Documentation
{
   "author" : "Warned Bros",
   "methods" : {
      "doesEat(string)" : {
         "author" : "Bob Clampett",
         "details" : "Food must be provided in UTF-8 format",
         "params" : {
            "_food" : "The name of a food to evaluate (English)"
         },
         "return" : "true if Bugs will eat it, false otherwise"
      }
   },
   "title" : "A simulator for Bug Bunny, the most famous Rabbit"
}

User Documentation
{
   "methods" : {
      "doesEat(string)" : {
         "notice" : "Determine if Bugs will or will not accept given food"
      }
   }
}
```
