### ISSUE TITLE
Please make Solidity installable through Chocolatey on Windows

### ISSUE THREAD

**Issue by fjl** [ethereum/solidity#343]
See https://github.com/ethereum/go-ethereum/issues/1998

**Comment by chriseth** [comment]
This will probably need community support. Because of maximal portability, Solidity releases are currently focused on emscripten as target platform.

**Comment by chfast** [comment]
Does geth have Chocolatey support?

**Comment by axic** [comment]
I was going to close this issue since in 1.5 years nobody ever looked for it.

**Comment by axic** [comment]
Closing this as for over 2 years nobody ever complained about missing Chocolatey support.
