### ISSUE TITLE
Introduce bytecode compression for gigantic contracts

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3432]
(Originally tracked in https://www.pivotaltracker.com/story/show/84781120)

Also see https://github.com/ethereum/EIPs/issues/91.

The idea is to have a decompressor during deploy time in the "constructor" (just like self extracting ZIPs and the 624 packer worked). This could save on deployment fees (but only if the input didn't contain a lot of zeroes).

Unlikely though this will produce usable results in the near future, it still may be a fun project. However, should gas costs increase, this will be become more important.

**Comment by chriseth** [comment]
Actually I think I have seen an lz decompressor in EVM at some point by someone...

**Comment by axic** [comment]
Yes, it is linked in the EIP linked above :)

But it is quite outdated, uses `call` for memcpy. It could be implemented much better in Julia.
