### ISSUE TITLE
Doc repository

### ISSUE THREAD

**Issue by dilab** [ethereum/solidity#3434]
Can we separate the doc to a new repository? 

This will make it much easier to do translation and keep the translation in sync with the main repo.

**Comment by axic** [comment]
Can you please expand how a separate repository helps having translations in sync?

Two benefits we have for having documentation in this repo:
- all examples can be compiled with every change, ensuring they never break
- new features/changes can be merged to documentation the same time the change is applied to code

**Comment by dilab** [comment]
Okay, thanks for answering. 

Here is what I am trying to achieve:
1. Git clone a **doc** repository and set up a Chinese translation site
2. Closely watch changes of the **doc**  and do the Chinese translation accordingly.

With current repository(doc + source code), I will get a lot of noise. Meaning a lot of changes have nothing to do with translation.

Hope that answers the question.

**Comment by axic** [comment]
It is possible to see the commit log for specific directories. For example this shows relevant commits for the `docs` directory: https://github.com/ethereum/solidity/commits/develop/docs

I think that should be enough to accomplish what you need.

**Comment by dilab** [comment]
Thanks for the clarification
