### ISSUE TITLE
A clearer naming convention for events

### ISSUE THREAD

**Issue by devzl** [ethereum/solidity#3435]
The only convention that differentiates triggering an event from calling a function now, is the capital letter at the beginning of an event.

I think it will be a better thing, to make the code of a Solidity snippet more clear, and make a developer's intentions explicit, is to prefer another naming convention for events such as:

* Putting an "E_" at the beginning. Example: E_Transfer
* Ending the name with "Event". Example: TransferEvent
* Ending the name with "Log". Example: TransferLog

What do you think of this proposition?

**Comment by federicobond** [comment]
For code style conventions, the well-known ConsenSys Smart Contract Best Practices recommend [adding a Log prefix](https://consensys.github.io/smart-contract-best-practices/recommendations/#differentiate-functions-and-events). For language-level differentiation, please follow the discussion here: https://github.com/ethereum/solidity/issues/2877
