### ISSUE TITLE
Metadata is not created for abstract contracts

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3437]
From https://github.com/ethereum/browser-solidity/issues/1012 and https://github.com/ethereum/browser-solidity/pull/1018#issuecomment-360603397

cc @fulldecent

**Comment by axic** [comment]
Created this here to track the issue, but I do not think it actually makes sense forcing the creation of the metadata, since the only purpose it has to serve as a source to recreating the same binary.

@chriseth what do you think?

**Comment by chriseth** [comment]
Hm, I would also agree.

**Comment by fulldecent** [comment]
Here is a use case for abstract contract metadata.

Currently abstract contracts are the only way to define "an interface" which includes *some* implementation details. Interfaces should be documented. Therefore abstract contract metadata is the only way to properly document these types of interfaces.

Related: https://github.com/ethereum/solidity/issues/3420

---

Also, if you ever think changing the `interface` keyword is in scope for work that should get done, call me.

**Comment by axic** [comment]
> metadata is the only way to properly document these types of interfaces.

I am not sure how metadata and "documentation" are related.

I think you should have a look at the compiler interface: http://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description

Natspec can be retrieved from the compiler for any contract (as it is created during parsing stage, before compilation).

The metadata, additionally, contains natspec. That is for a reason: the metadata could be used by tools interacting with deployed contracts and retrieving natspec there is useful.

**Comment by fulldecent** [comment]
Got it, natspec *can* generate for abstract contracts. I'm happy.

**Comment by chriseth** [comment]
Closing since it seems to be a feature that was not actually requested.
