### ISSUE TITLE
Should explain the use case for "Non-standard Packed Mode"

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3438]
It is there to efficiently support hashing non-ABI encoded data. Should probably rename it too.

(Trigger: https://twitter.com/socrates1024/status/956732271997915136)

cc @amiller

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
