### ISSUE TITLE
Introduce multi-word memory load in assembly

### ISSUE THREAD

**Issue by riordant** [ethereum/solidity#3441]
Outside of calldatacopy, which won't work in every case, there is no way currently to load more than a single word in memory in assembly. From the docs:
`mload(p):  mem[p..(p+32))`

Multi-word memory copy would involve specifying a memory address and a number of bytes/words to copy. in the case of bytes:
`mload(p, n):  mem[p..(p+n))`

Subsequent operations should also be introduced for mstore, eg.:
`mstore(p, n, v): mem[p..(p+n)) := v`

**Comment by chriseth** [comment]
In my opinion, there should be as few builtin functions as possible. Using for-loops, it is rather easy to implement a memcopy.

Where would you place the return value of `mload(p, n)` - if `n` is dynamic?

**Comment by riordant** [comment]
My rationale is that it means cleaner code where multi-word copying is necessary; perhaps `mload` could be overloaded - meaning no extra builtin functions.

I'm not quite sure I understand what you mean - the result is still getting placed at memory address `p`. Why does a dynamic `n` change that?

**Comment by axic** [comment]
I am a bit confusing but this proposal. Are you proposing inline assembly builtin functions or new EVM opcodes?

Not sure what `mload(p, n): mem[p..(p+n))` is doing. `mload` is loading memory onto the stack. Is this loading multiple stack items?

Aren't you sure you need `mcopy` (memory copy) instead which can copy sections of memory?

**Comment by riordant** [comment]
I was proposing a built-in function however `mcopy` seems to be what I'm describing. Have you got a reference for operation? Is it a built-in function? Thanks

**Comment by axic** [comment]
It is not present yet, but some initial discussions are available here #474 and #1319

**Comment by riordant** [comment]
Thanks. As a result I'll close this. I've messaged you on Gitter @axic
