### ISSUE TITLE
Add 'deprecated' keyword for preserving storage layout

### ISSUE THREAD

**Issue by mossid** [ethereum/solidity#3443]
While upgrading contract is available now using proxy contracts, removing storage variable makes the storage layout different from before the upgrade. 

```
contract C {
  uint version;
  uint maximumIndex;
  uint currentIndex;
}
```
The position of `currentIndex` is at `keccak256(uint256(2))`;

After we upgrade it to the following:

```
contract C {
  uint version;
  // variable `maximumIndex` is removed for some reason
  uint currentIndex;
  bool isAppendable;
}
```
The position of `currentIndex` is now at `keccak256(uint256(1))`, which leads us to referring wrong position (which used by `maximumIndex`).

To preserve memory index, we can add `deprecated` keyword.

```
contract C {
  uint version;
  uint deprecated maximumIndex;
  uint currentIndex;
  bool isAppendable;
}
```

The compiler will show an error if any deprecated variables are used in the code but on an actual compilation, the compiler will allocate space for them just like as normal, making it backward-compatible.

**Comment by chriseth** [comment]
I would say this way of doing it is extremely dangerous. There is no protection that you did not do any other changes. It would probably be better to somehow directly refer to an old version of the contract.

**Comment by veox** [comment]
One of Solidity's advantages is abstracting away storage layout management. You don't have to worry what goes where, as long as it's confined to the storage of the same contract.

I think `solc`'s been designed with that assumption (@chriseth - please correct me if needed). EDIT: The assumption being - that the compiler's scope is a single program/contract; and that if interactions with a different contract are to be made, then they will be through a web3-compatible ABI.

Trying to "fix" it like this is asking for trouble... @mossid, may I interest you in LLL instead? :D

If not, perhaps you'd want to look at existing approaches to persistent storage for upgradable contracts (aka "eternal storage"):

* [`RocketStorage` by RocketPool](https://medium.com/rocket-pool/upgradable-solidity-contract-design-54789205276d);
* [`UpgradeableTokenStorage` by Zeppelin](https://blog.zeppelinos.org/smart-contract-upgradeability-using-eternal-storage/).

This is not exactly about what you're proposing, but I think it's close to what you aim to achieve, and to what in turn led you to opening this issue.

-----

EDITs: clarification, typos (many)
