### ISSUE TITLE
Deprecate old jsonCompiler interface

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3452]
The original compiler interface for Javascript consisted of `compileJSON`, `compileJSONMulti` and `compileJSONCallback` as it evolved. For many releases now the "standard json" format is available via `compileStandard`.

Proposal is to remove these interfaces in 0.5.0. Anyone using the commandline `solc` tool or the `solc-js` library is not affected by this change.

I think every consumer of soljson uses the new interface, at least Remix and Truffle does.

Related to #2864.

**Comment by axic** [comment]
This would only affect those not using `solc-js`. Is there anyone using `soljson` directly?

cc @iurimatias @gnidan @pipermerriam

**Comment by gnidan** [comment]
Truffle should be using only `compileStandard` at this point, but cc @cgewecke in case his upcoming changes are affected by this.

**Comment by axic** [comment]
Sorry, should have been more clear. Issue #2864 proposes new native function names in `soljson`. `solc-js` will be able to figure out what the underlying `soljson` has.

**Comment by iurimatias** [comment]
Embark uses `compileStandardWrapper` in solc-js.

**Comment by axic** [comment]
@yann300 does Remix still uses solc-js and doesn't handle soljson directly?

**Comment by yann300** [comment]
Remix uses `compileStandardWrapper` and solc-js

**Comment by axic** [comment]
This is now blocked on first merging the appropriate solc-js PRs. Will do that next.

**Comment by axic** [comment]
@yann300 @iurimatias @gnidan @cgewecke the plan now for 0.5.0 is that:
- `compile` and `compileStandard` would be gone
- `compileStandardWrapper`  would be renamed to `compile`

This means all of you would need to change the code to use `compile`, but the format passed to or received from it wouldn't change.

**Comment by Tectract** [comment]
I'm downstream in a breaking library that used compileJSON and trying to figure out how to update/fix my fork.

I'm looking at trying to figure out what to do with 

```
var compile=function(input,optimise,readCallback){
  var result='';
  if(readCallback!==undefined&&compileJSONCallback!==null) {
    result=compileJSONCallback(JSON.stringify(input),optimise,readCallback);
  } else if(typeof input!=='string'&&compileJSONMulti!==null) {
     result=compileJSONMulti(JSON.stringify(input),optimise);
  } else {
    result=compileJSON(input,optimise);
  }
  return JSON.parse(result);
};
```

from here: line 1576

https://github.com/ericxtang/browser-solc/blob/master/browser-solc.js

Can I get some info on how to fix / update this for the newest versions of solc, so that my in-browser compiler will work again?

related issue: https://github.com/ericxtang/browser-solc/issues/4
