### ISSUE TITLE
Too many variables when calling a function from another contract

### ISSUE THREAD

**Issue by elie222** [ethereum/solidity#3457]
We have a contract that is in production already and has a `getPerson()` function. This is a public function that returns 12 `uint256` values. That contract works fine when calling it from web3, but when calling it from another contract get a compiler error. The call in the other contract is as follows:

```

    function _getPerson(uint256 _personId) private returns (uint256) {
        uint256 a;
        uint256 b;
        uint256 c;
        uint256 d;
        uint256 e;
        uint256 f;
        uint256 g;
        uint256 h;
        uint256 i;
        uint256 j;
        uint256 k;
        uint256 l;

        (a, b, c, d, e, f, g, h, i, j, k, l) = personContract.getPerson(_personId);
        
        return a;
    }
    
```

And the compiler warning on the line that we call `getPerson` is:

`Compiler Error: Stack too deep. Try removing local variables.`

Is there any way to get around this? Redeploying isn't the contract is a pretty bad option for us as there is a lot of data to move over (production contract).

Why is there an issue as we're only returning 12 items and the limit is 16 isn't it? Why does it work with web3, but not from another contract?

**Comment by axic** [comment]
Tracked in #4261.
