### ISSUE TITLE
Allow modifier declaration with no implementation

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3459]
# Discussion

This allows separation of concerns.

# Test case

```solidity
pragma solidity ^0.4.19;

contract A {
    modifier readyToAct;
    
    function act() readyToAct external {
        
    }
}

contract B is A {
    modifier readyToAct {
        require(true);
        _;
    }
}
```

**Comment by ekpyron** [comment]
So since we have ``abstract`` in the meantime, I'd say that either declaring an unimplemented modifier in a contract, or at least using one on a function, has to make the contract ``abstract``. Which of the two doesn't matter much to me.

**Comment by hrkrshnn** [comment]
In the implementation, the modifier implementation in derived class will have to use the `override` flag.

The same example:

```
pragma solidity ^0.4.19;

contract A {
    modifier readyToAct;
    
    function act() readyToAct external {
        
    }
}

contract B is A {
    modifier readyToAct override {
        require(true);
        _;
    }
}
```

This check already happens in the code, and makes the code clearer, so I'll keep it. What do you think @ekpyron

**Comment by ekpyron** [comment]
Yes `override` should be required in the overriding modifier. As a matter of fact we should probably force unimplemented modifiers to be `virtual` as well, i.e. do things exactly as for functions.
