### ISSUE TITLE
Require super constructor calls explicitly

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3461]
See: https://github.com/ethereum/solidity/pull/3305#discussion_r159631442

**Comment by chriseth** [comment]
What happens if some constructor parameters are not specified? Does the contract get abstract or is it an error right away?

It seems we do not even have an errorif two parameters for the same base disagree:
```
contract A { function A(uint x) {..}}
contract B is A(2) { }
contract C is A(3) { }
contract D is B, C {}
```

**Comment by chriseth** [comment]
It should be an error if the base constructor parameters are given both at the base contract list and at the derived constructor:

```
contract A { function A(uint x) {}}
contract B is A(2) { function B() A(2) {}}
```

**Comment by axic** [comment]
> It seems we do not even have an errorif two parameters for the same base disagree:

See #2912.

**Comment by axic** [comment]
> What happens if some constructor parameters are not specified?

Since there's no constructor overloading it shouldn't be possible?

**Comment by chriseth** [comment]
> >   What happens if some constructor parameters are not specified?
> 
> Since there's no constructor overloading it shouldn't be possible?

I thought about leaving out one level in the inheritance hierarchy, but I guess the solution would be to just add a forwarding constructor. The problem here is that this might not work in the multi-inheritance setting:

```
contract owned { constructor(address owner { ... } }
contract mortal is owned { constructor(address owner) mortal(owner) { ... } }
contract anotherBehaviourContract is owned { constructor(address owner) mortal(owner) { ... } }
contract OurActualContract is mortal, anotherBehaviourContract {
  constructor(address owner)
    anotherBehaviourContract(owner) mortal(owner) { ... }
}
```
This provides the parameter to `owned` twice. Of course it is twice the exact same value, but that does not have to be the case and the compiler might not be able to detect it.

**Comment by axic** [comment]
@chriseth  @ekpyron is this question by any chance closed via the new inheritance rules?

**Comment by ekpyron** [comment]
I think this is all disallowed by now. We didn't solve the issue in https://github.com/ethereum/solidity/issues/3461#issuecomment-370434062 , though - we just disallow this without any way around it at the moment :-).

**Comment by chriseth** [comment]
You do not have to provide arguments to base constructors, as long as they are provided somewhere in the inheritance hierarchy. This one is valid:
```solidity
contract owned { constructor(address owner) public {  } }
abstract contract mortal is owned { constructor(address owner)  public  { } }
abstract contract anotherBehaviourContract is owned { constructor(address owner) public { } }
contract OurActualContract is mortal, anotherBehaviourContract {
  constructor(address owner)
    anotherBehaviourContract(owner) owned(owner) mortal(owner) public { }
}

```

**Comment by ekpyron** [comment]
True, that's **a** solution at least... and so far no-one complained as far as I know :-). I'll close this issue then - please reopen, if you disagree.
