### ISSUE TITLE
Change codegen to output non-strict Yul

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3463]
The idea is to output a Julia AST or code which uses `FunctionalInstruction` for EVM opcodes.

- [ ] A special flag must be introduced for `FunctionDefinition` which allows the function to use jumps. These functions will not be evaluated in the optimiser.
- [ ] Any code which cannot be rewritten easily to avoid the use of jumps must be enclosed as a function and marked as above.
- [ ] An on-the-fly translation must happen where `SWAP` and `DUP` are replaced by variable access (`Identifier)` (and the variables must be created for all the input arguments as well as for `PUSH`es with `VariableDeclaration`)
- [ ] `appendInvalid` and `appendRevert` should be replaced with a `FunctionCall`

**Comment by kaibakker** [comment]
I would be interested in this, are there any plans to implement this? Would this create a function which takes bytecode and abi and outputs julia/solidity code?

**Comment by axic** [comment]
This is actually a substantial internal change to the current "code generator" in the compiler, which takes Solidity AST and outputs EVM instructions (the `libsolidity/codegen/` directory in the sources).

The features/changes needed are the ones above, in order of implementation.

The first task is actually quite easy and would be a good start if you are interested in learning more about the internals.

**Comment by chriseth** [comment]
I'm actually not sure if this is possible at all...

**Comment by chriseth** [comment]
Saying: I think this should be further discussed before effort is put into it.

**Comment by axic** [comment]
First task above is useful in general (though instead of a flag there could be a helper to return true if a `FunctionDefinition` uses jumps), but we didn't fully discuss the feasibility of everything else.

**Comment by chriseth** [comment]
I think that rewriting those using proper iulia is much faster and less error-prone.

**Comment by chriseth** [comment]
@axic I'm not sure what this is about.

**Comment by chriseth** [comment]
We don't have any non-strict yul anymore.
