### ISSUE TITLE
An issue about totalSupply

### ISSUE THREAD

**Issue by lehuyit275** [ethereum/solidity#3465]
A problem that I think you need to pay attention and update the fixes immediately.
I do not know if you really understand me. I will present it in the most detailed way I can. Hope you will understand my mind.

This problem is in the total supply of a token.

When a token is generated, it will have a TotalSupply. Based on TotalSupply, the investor will decide what to invest in at a reasonable price. Nothing if totalSupply does not change. But now, many fraudsters take advantage of everyone's trust, generating a much larger amount than TotalSupply to sell.

I do not know the reason why you allow this to happen. But it's not fair. It only benefits scammers. Consequently, a lot of people lose their money.

I think you need to fix it, you should create a trigger to bind it. Do not allow to create a greater number of tokens than totalSupply. Or at least before allowing totalSupply change it needs to be temporarily locked out in a timely manner so that investors have time to review.

I hope you know what I mean and fix it soon.

**Comment by axic** [comment]
I think this repo isn't the right place to discuss this. Please take it to the ERC20 discussion thread or https://gitter.im/ethereum/EIPs or any other relevant forum.
