### ISSUE TITLE
Compiler produces apparently suboptimal code

### ISSUE THREAD

**Issue by abbbe** [ethereum/solidity#3466]
> Which version of Solidity you are using

0.4.19

> What was the source code (if applicable)

```
pragma solidity ^0.4.6;
contract CatsAreForReal {
}
```

> Which platform are you running on

https://remix.ethereum.org

> How to reproduce the issue

Compile and look at assembler code

> What was the result of the issue

```
.code
  PUSH 60			contract CatsAreForReal {\n   ...
  PUSH 40			contract CatsAreForReal {\n   ...
  MSTORE 			contract CatsAreForReal {\n   ...
  CALLVALUE 			contract CatsAreForReal {\n   ...
  ISZERO 			contract CatsAreForReal {\n   ...
  PUSH [tag] 1			contract CatsAreForReal {\n   ...
  JUMPI 			contract CatsAreForReal {\n   ...
  PUSH 0			contract CatsAreForReal {\n   ...
  DUP1 			contract CatsAreForReal {\n   ...
  REVERT 			contract CatsAreForReal {\n   ...
tag 1			contract CatsAreForReal {\n   ...
  JUMPDEST 			contract CatsAreForReal {\n   ...
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract CatsAreForReal {\n   ...
  DUP1 			contract CatsAreForReal {\n   ...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract CatsAreForReal {\n   ...
  PUSH 0			contract CatsAreForReal {\n   ...
  CODECOPY 			contract CatsAreForReal {\n   ...
  PUSH 0			contract CatsAreForReal {\n   ...
  RETURN 			contract CatsAreForReal {\n   ...
.data
  0:
    .code
      PUSH 60			contract CatsAreForReal {\n   ...
      PUSH 40			contract CatsAreForReal {\n   ...
      MSTORE 			contract CatsAreForReal {\n   ...
      PUSH 0			contract CatsAreForReal {\n   ...
      DUP1 			contract CatsAreForReal {\n   ...
      REVERT 			contract CatsAreForReal {\n   ...
    .data
```

> What the expected behaviour is

I expected compiled code not to have the following redundancies:

- "PUSH 60 PUSH 40 MSTORE" during contract creation helps to reserving memory buffer to copy contract code, but why 2 words more than needed?
- Why one needs this code in the fallback function at all?
- STOP after RETURN, which never ever gets reached.

I am trying to better understand how Solidity/EVM works and what is the purpose of these artefacts.

**Comment by chriseth** [comment]
The compiler does not focus on optimizing artificially short contracts. That being said, we could probably detect whether a function uses memory at all and only initialize the free memory pointer for those. This might result in longer code, though, and thus would be a trade-off between deploy time cost and run time cost.

The free memory pointer is at `0x40` to have the first 64 bytes as a "scratch area" which does not have to be allocated.

The stop after return is inserted as a safety measure in case the code does not end with a 'return'. We should probably replace it by an InvalidInstruction instead.

**Comment by abbbe** [comment]
I understand

> The stop after return is inserted as a safety measure in case the code does not end with a 'return'. 

I thought EVM is obliged to halt execution RETURN. Is there any practical scenario of this happening?

**Comment by chriseth** [comment]
It just appends a stop all the time, it does not inspect the bytecode (just in case this inspection might also be broken in some way).
