### ISSUE TITLE
Keep allowing event declarations with no parameter list

### ISSUE THREAD

**Issue by jksf** [ethereum/solidity#3475]
I noticed that changelog for version 0.4.20 introduces bugfix:
> Parser: Disallow event declarations with no parameter list.

I use events to log that something happened at given block. Sometimes it doesn't make sense to include any parameters, the name of the event is sufficient.

What is the motivation for this change? If this change makes it into 0.4.20 will it break backward compatibility?

**Comment by axic** [comment]
This is about event declarations and not about actually emitting an event.

`event Something;` is now invalid, but `event Something();` is valid.

Invocation was already "enforced" as `Something();` as `Something;` is just an empty statement.

**Comment by jksf** [comment]
@axic Thanks for the clarification. The issue can be closed, sorry for bothering
