### ISSUE TITLE
compiler error for public struct only containing `string[]`, but ok if other types present too

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/solidity#3481]
I am working with remix on the following example (compiler version 0.4.19+commit.c4cbbb05.Emscripten.clang)
```
contract testStruct {
    
    struct stru{
        string[] s;
        //uint256 u;        // if I remove this line the `myStru` cannot be public
    }

    stru[] public myStru;   // compiler error "TypeError: Internal or recursive type is not allowed for public state variables.
                            // there are two ways of fixing this:
                            // 1) adding another type into the struct (like uint256)
                            // 2) making this property not public
}
```

I get a compiler error in the code as pasted above because the struct only contains a nested string array. Once I add another type (e.g. `uint256`) then all is fine and if I make the member not `public` it is also ok. This seems somewhat inconsistent. Additionally, when adding another type to my struct Remix will not show the struct output when calling the getter - this is expected but it would be good to at least be informed that something is missing.

**Comment by federicobond** [comment]
While trying to reproduce this I found a segfault in solc probably related to the last patch I got merged, so thank you 😊

**Comment by chriseth** [comment]
This is be design: Getter functions were introduced before we had structs in the ABI. The idea behind a getter function is that it is always of the form `return a[b][c][d];` This works if there is a unambiguous member in the struct we want to follow. It also works if the struct only contains non-indexable members. If you have at least one indexable member, there cannot be another one in the struct.

**Comment by chriseth** [comment]
Please re-open if you think any change to the compiler is necessary.
