### ISSUE TITLE
Spanning multiple lines

### ISSUE THREAD

**Issue by freshonline** [ethereum/solidity#3482]
What is it?
All version solc, many exemples cause this error.
https://www.photobox.co.uk/my/photo/full?photo_id=500573127593

**Comment by chriseth** [comment]
What you cite is just the location of the error, not the actual message. The screenshot link does not work for me. Do you have the full compiler error message?

**Comment by axic** [comment]
Assuming it is just a "Spanning multiple lines" message confusing @freshonline, which is tracked in #3620.

Please reopen with a proper log if it is a different issue.
