### ISSUE TITLE
Add outputSelection for original source in Standard JSON Output

### ISSUE THREAD

**Issue by jamespic** [ethereum/solidity#3483]
I'm working on a standalone debugger for Solidity contracts.

The standard JSON output format provides almost everything needed to debug a transaction, but doesn't include the original source code. Finding the original source code from the filename can be a non-trivial task if the project was compiled using a complex file resolver, which means that either debuggers need to be aware of the resolution rules used at compilation time, or need to have sources provided to them separately.

Could an `outputSelection` be added that would include the original source text in the compiler output?

**Comment by axic** [comment]
There is already a solution for this: the metadata output contains the sources or references to the sources. For your use you'll need to pass the following settings:
```
"settings": { "metadata": { "useLiteralContent": true } }
```

**Comment by jamespic** [comment]
Ah, brilliant. I'd seen that setting in the docs, but misunderstood what it did. Thanks.
