### ISSUE TITLE
Adding Elvis operator (Allow omitting second argument in ternary operator)

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#3487]
Elvis operator: https://en.wikipedia.org/wiki/Elvis_operator

Many languages support allows omitting the second operand, and using implicitly the first operand as the second also:
```
a = x ?: y;
```
The expression is equivalent to
```
a = x ? x : y;
```
except that if `x` is an expression, it is evaluated only once. The difference is significant if evaluating the expression has side effects.

This would allow to write more expressive code:
```
function transfer(address to, uint256 value) public returns (bool) {
    address destination = (proxyOwners[to] == address(0)) ? to : proxyOwners[to];
    return super.transfer(destination, value);
}
```
=>
```
function transfer(address to, uint256 value) public returns (bool) {
    return super.transfer(proxyOwners[to] ?: to, value);
}
```

**Comment by chriseth** [comment]
I don't think this is useful in Solidity since no type is implicitly convertible to bool. Does the "longhand" version of your example
```
function AccountContract(StorageContract _storageContract) public {
    storageContract = _storageContract ? _storageContract : new StorageContract();
}
```
compile?

**Comment by k06a** [comment]
@chriseth I agree, it will not compile until `uint256/address` will be implicitly convertible to `bool`

**Comment by k06a** [comment]
One more example:
```
function transfer(address to, uint256 value) public returns (bool) {
    address destination = (proxyOwners[to] == address(0)) ? to : proxyOwners[to];
    return super.transfer(destination, value);
}
```
=>
```
function transfer(address to, uint256 value) public returns (bool) {
    return super.transfer(proxyOwners[to] ?: to, value);
}
```

**Comment by k06a** [comment]
Also found Elvis operator on Wikipedia: https://en.wikipedia.org/wiki/Elvis_operator

**Comment by chriseth** [comment]
Closing since we do not support implicit conversion to bool.
