### ISSUE TITLE
Compiler incorrectly reasons about the selector function

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3494]
![screen shot 2018-02-13 at 1 16 21 am](https://user-images.githubusercontent.com/382183/36136025-6809e55c-105c-11e8-8224-9d795d8176e3.png)
![screen shot 2018-02-13 at 1 16 34 am](https://user-images.githubusercontent.com/382183/36136030-6f42a4d0-105c-11e8-8ff2-e5e73eb1928d.png)

**Comment by chriseth** [comment]
That's a tricky one. Of course `this.f.selector` should be fine, and even `this.f` should be fine. The problem is that `this` is disallowed in a view context - reading the current address is not a pure action.

**Comment by fulldecent** [comment]
Thank you.

At a minimum, can we a get a "this should be fixed someday" on this issue.

I am more interested in this issue being accepted and less interested in the actual fix. I think you know why...

**Comment by fulldecent** [comment]
Wow, that was much faster than I hoped. Thanks!

**Comment by aion82** [comment]
ok

**Comment by chriseth** [comment]
Some things are easy, some not so much :)
