### ISSUE TITLE
improve an error msg. Wrong location.

### ISSUE THREAD

**Issue by LianaHus** [ethereum/solidity#35]
contract ClientReceipt {
			bytes32 x = 0xFFFFFFFF;
			function deposit() returns (uint x1) {
				return int(x);
			}
		}

result in 
:4:12: Type error: Type int256 is not implicitly convertible to expected type uint256.
				return int(x);
				       ^----^

**Comment by LianaHus** [comment]
strange, can't reproduce this anymore

**Comment by chriseth** [comment]
Can this be closed?

**Comment by LianaHus** [comment]
probably, I'll reopen it when I can reproduce
