### ISSUE TITLE
How to use modifiers to form combination of boolean conditions?

### ISSUE THREAD

**Issue by GaikwadPratik** [ethereum/solidity#3504]
As of now, when function modifiers are placed using a space will execute in order they are placed resulting in **AND**  condition. Is it possible to use them to form other boolean conditions?

**Comment by federicobond** [comment]
Modifiers work by wrapping the original function, so there isn’t a clean way to apply OR semantics. You’re better off creating a separate function for each condition and writing a modifier AorBorC that enforces the combination.
