### ISSUE TITLE
Allow static access to interface function selectors

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3506]
# Test cases

```solidity
 //pragma solidity 0.6.0-develop;

interface I {
    function i() external;
}

abstract contract C {
    function c() virtual external;
}

contract TestCase {
    function f() external {
        I.i.selector; // <------------- this is currently an error but should not be
        C.c.selector;
    }
}

contract TestCase2 is I, C {
    function f() external {
        I.i.selector;
        C.c.selector;
    }
    function i() override external{}
    function c() override external{}
}
```

# Actual outcome

> TypeError: Member "i" not found or not visible after argument-dependent lookup in type(contract I). I.i.selector;
 
# Expected outcome

No error.

# Discussion

Also need to handle specifying the function where there is function overloading.

Reference: related to https://github.com/ethereum/EIPs/pull/881

**Comment by fulldecent** [comment]
Possibly related, or I can create a separate issue.

```solidity
pragma solidity ^0.4.19;

contract TestCase {

    function bob() public pure {
        
    }
    
    function TestCase() public {
        this.bob.selector;
    }
}
```

The error is

> Warning: "this" used in constructor.

Likewise, I do not think this should be a warning.

**Comment by chriseth** [comment]
Yes, sounds useful.

**Comment by Arachnid** [comment]
It'd also be useful to be able to access these fields in constant initialisers:

```
contract Test{
  function foo() { }
  bytes4 constant FOO_FUNCTION_ID = foo.selector;
}
```

**Comment by chriseth** [comment]
The main complication for implementing this is that `this` is not compile-time constant (it returns the current address) and thus you have a compile-time constant expression that has a non-compile-time constant sub-expression...

**Comment by fulldecent** [comment]
For a first step requesting just the feature from the original post. Can add constants as an separate issue. (Which I still support.)

---

Here is a a case found in the wild that shows the problem of not having this feature:

https://github.com/erasureprotocol/erasure-protocol/blob/master/contracts/posts/Post_Factory.sol#L11

```solidity
    constructor(address instanceRegistry, address templateContract) public {
        // declare template in memory
        Post template;

        // set instance type
        bytes4 instanceType = bytes4(keccak256(bytes('Post')));
        // set initSelector
        bytes4 initSelector = template.initialize.selector;
        // initialize factory params
        Factory._initialize(instanceRegistry, templateContract, instanceType, initSelector);
    }
```

They create `template` just to use the selector.

**Comment by axic** [comment]
We actually have this implemented for contracts, added probably some time last year.

**Comment by bshastry** [comment]
Notes from stand up: @fulldecent will do some more testing and update on this

**Comment by fulldecent** [comment]
Top comment updated, test case updated per discussion.

**Comment by chriseth** [comment]
Since this seems to be non-breaking, I'll add it to 0.6.1.
