### ISSUE TITLE
"non-existent calling account" - typo in docs?

### ISSUE THREAD

**Issue by abbbe** [ethereum/solidity#3507]
https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst says: 

> Warning The low-level call, delegatecall and callcode will return success if the calling account is non-existent, as part of the design of EVM. Existence must be checked prior to calling if desired.

It is not clear how _calling_ account can be non-existent. Are we talking about _called_ account here?

**Comment by chriseth** [comment]
Indeed! Do you want to create a pull request containing the change?
