### ISSUE TITLE
List and explain all pragmas, especially the experimental ones.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3511]

**Comment by aj07** [comment]
Will you Please give bit more info about it. I would like to send PR on it.

**Comment by chriseth** [comment]
There is a file called `ExperimentalFeatures.h` that lists all experimental pragmas, but these are not the only pragmas. Also I fear you have to search the source code to see which effects `pragma experimental "v0.5.0";` has.

**Comment by axic** [comment]
Somewhat related is #3761 for documenting 0.5.0 features.

**Comment by aj07** [comment]
https://github.com/aj07/solidity/commit/e201f76730f116cef752266d2bec111e3fd92d6d

**Comment by axic** [comment]
Please create a PR, links to commits is not something what can be reviewed.

**Comment by aj07** [comment]
https://github.com/ethereum/solidity/pull/3967

**Comment by ChrisChinchilla** [comment]
Looks to me like this is all done now.
