### ISSUE TITLE
Allow contract's public state variable to implement interface function

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3514]
# Test case

```solidity
pragma solidity ^0.4.19;

interface I {
    function bob() external returns (int);
}

contract C is I {
    int public bob;
}
```

# Current outcome

> This contract does not implement all functions and thus cannot be created.

# Expected outcome

Compiles successfully

# Discussion

Getter functions are defined in the documentation at http://solidity.readthedocs.io/en/develop/contracts.html#visibility-and-getters:

> The compiler automatically creates getter functions for all public state variables.

In contract `C`, the implicit function `function bob() external returns (int);` is generated for the public variable `int public bob;`. Therefore the contract should be a valid implementation of the interface.

---

References:

* This issue is the opposite of https://github.com/ethereum/solidity/issues/3411

**Comment by chriseth** [comment]
I fear we need a centralized point where we discuss how function inheritance is supposed to work in the future.

**Comment by fulldecent** [comment]
Good point. In the Swift Evolution process, this would call for a manifesto. We could call it the Inheritance Manifesto. This would document what is going changing, the motivation and how to make the new behavior self-consistent.

If would like me to do this, maybe we could have a quick phone call. This will let me understand what type of end product would be accepted.

**Comment by axic** [comment]
Well as a first step we should collect all the relevant issue numbers in one place. There are probably close to 10 issues talking about different facets of inheritance.

**Comment by fulldecent** [comment]
RUNNING TALLY:

- Solidity Issue #3412 -- Implement Interface: Allow Stricter Mutability. https://github.com/ethereum/solidity/issues/3412
- Solidity Issue #3419 -- Interfaces Can't Inherit. https://github.com/ethereum/solidity/issues/3419

- to add more

**Comment by chriseth** [comment]
@fulldecent I created a project https://github.com/ethereum/solidity/projects/9 - not sure if you can add items there, but if you tell me, I will add them.

**Comment by chriseth** [comment]
Also created umbrella issue: https://github.com/ethereum/solidity/issues/3698

**Comment by superduck35** [comment]
Interested to know the status of this as I seem to be getting some inconsistent behaviour between ~0.4.24 and 0.5.xx

**Comment by fulldecent** [comment]
@alsco77  This discussion is now rolled into https://github.com/ethereum/solidity/pull/3729

This issue can be closed when the conclusion is reached, wherever that discussion happens.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/7839
