### ISSUE TITLE
It should not be possible to initialize constant variables with expressions that divide by zero or use addmod/mulmod with zero.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3522]

**Comment by erak** [comment]
@chriseth I found the following case which is not handled correctly:
```
contract c {
    uint constant a = mulmod(3, 4, 0);
    uint constant b = addmod(3, 4, 0);
    function f() public pure {

    }
}
```
Division by zero e.g. ``uint constant a = 1 / 0`` seems to be catched by ``binaryOperatorResult``. Do you have another example?

**Comment by chriseth** [comment]
What about
```
contract c {
    uint constant a = 0;
    uint constant b = 7 / a;
}
```

If we cannot think of other cases, then only mulmod / addmod needs to be included.
