### ISSUE TITLE
example fails w/ invalid opcode

### ISSUE THREAD

**Issue by maurelian** [ethereum/solidity#3528]
## Issue:

The example here: https://solidity.readthedocs.io/en/develop/types.html#data-location

Fails with an invalid opcode when I call `C.f([1,2,3])`. The invalid opcode is at location 339, and maps to line 10, `y[7];` in the source code. The opcode is `0xfe`.

## Expected behavior

Should an out of bounds lookup not be failing with`revert` now?

**Comment by chriseth** [comment]
Revert is only done for things that can be accounted for invalid input. If you access `y[7]` in your code, it is your responsibility to check that it does no go out of bounds, especially since `y` is now stored in storage and thus part of the internal logic of the contract.
