### ISSUE TITLE
Supress warnings on functions meant to be overriden.

### ISSUE THREAD

**Issue by ealmansi** [ethereum/solidity#3529]
Currently, the following code throws two warnings:

```
function fn(uint256 a) public {
}
```
Namely, that parameter `a` is unused, and that function `fn` could be restricted to being pure. AFAIK, there is currently no way to tell the compiler to ignore these specific warnings.

However, there are valid use cases where this pattern seems perfectly reasonable, and the warnings should either be omitted, or there should be a way to tell the compiler to suppress them. For example, whenever a base class wants to provide a function which is optionally overrideable and yet does not have any behaviour by default. This could be expressed by making the function abstract, but that prevents the base class from being instantiable. (See #2828)

Consider the following snippet:

```
contract Crowdsale {
    function validate(address user) public {
        // ...
        _afterValidate(user);
    }

    function _afterValidate(address user) public {
    }
}

contract FriendlyCrowdsale is Crowdsale {
    event Welcome(address user);
    function _afterValidate(address user) public {
        Welcome(user);
    }
}
```

Currently, there is no way to prevent the compiler from issuing two warnings on `Crowdsale._afterValidate`. Making this function abstract would prevent `Crowdsale` from being instantiated. 

Two possible solutions could be:
1/ Make the compiler treat empty functions the same way as abstract functions, in terms of warnings.
2/ Introduce a new construct akin to `@SupressWarnings("unused")` from Java, or extend natspec to allow the user to ignore specific warnings.

**Comment by eternauta1337** [comment]
+1

This pattern is indeed reasonable (specially with multiple inheritance) and we are considering it for [OpenZeppelin](https://github.com/OpenZeppelin/zeppelin-solidity).

**Comment by chriseth** [comment]
The way to suppress the unused warning is to comment out the name of the variable, this might be suboptimal, but at least it works. A workaround for the purity would be to e.g. use `this` in the body.

I guess the best solution would be to introduce a modifier which tells that a function can optionally be overridden. Then the derived class also has to either override it or explicitly state that it just takes the default implementation of the parent.

**Comment by eternauta1337** [comment]
Thanks @chriseth 
_"The way to suppress the unused warning is to comment out the name of the variable, this might be suboptimal, but at least it works"_
This is a bit of a problem if you're writing documentation. For example:
```
/**
 * @param _a A very useful parameter.
 */
function aVeryUsefulFunction(uint256 _a) {
//...
}
```

If you omit the variable name (with the documentation in place), the compiler fails:
```
DocstringParsingError: Documented parameter "_a" not found in the parameter list of the function.
Compilation failed. See above.
```

**Comment by ealmansi** [comment]
@chriseth thanks for your reply.

If I understood correctly, I believe this is what you are suggesting as a workaround:

```
function _afterValidate(address /*user*/) public {
    this;
}
```

This indeed solves the two warnings that I mentioned in the issue description, but unfortunately also introduces two new issues:

i) A new warning is raised: "state mutability can be restricted to view".
ii) Like described by @ajsantander, this prevents the user from documenting the parameters.

Also, it seems to me that a language construct for this purpose is justified, since there is probably no general rule that can determine for every function whether its unused parameters are a potential error or are likely intentional.

A potentially simpler approach could be extending natspec with `@ignore warning unused` and `@ignore warning mutability`, or more generally `@ignore warning <warning_type>`.

**Comment by chriseth** [comment]
Indeed, that's what I mean with suboptimal. Currently, I can only think of functions to be overridden as a use-case of suppressing the warnings. Because of that, I would propose to rather introduce a modifier for that use-case instead of providing a general "ignore warning" statement.

**Comment by ealmansi** [comment]
An ugly hack that works (with additional gas costs :frown:):

```
// C.sol
pragma solidity ^0.4.19;

import "./SupressWarnings.sol";

contract C is SupressWarnings {
    /**
     * @param str Some str.
     * @param addr Some addr.
     * @param i Some int.
     */
    function fn(string str, address addr, uint256 i) public {
        noStateMutabilityWarning();
        noUnusedParamWarning(str);
        noUnusedParamWarning(bytes32(addr));
        noUnusedParamWarning(bytes32(i));
    }
}

// SuppressWarnings.sol
pragma solidity ^0.4.19;

contract SupressWarnings {
    uint8 _noStateMutabilityWarning;
    function noStateMutabilityWarning() public {
        _noStateMutabilityWarning = _noStateMutabilityWarning;
    }
    function noUnusedParamWarning(bytes32 param) public pure {
        param = param;
    }
    function noUnusedParamWarning(string param) public pure {
        param = param;
    }
}
```

**Comment by ealmansi** [comment]
An ugly hack that works:

```
contract C {
    uint8 _noWarning;
    /**
     * @param str Some str.
     * @param addr Some addr.
     * @param i Some int.
     */
    function fn(string str, address addr, uint256 i) public {
        _noWarning = _noWarning;
        str = str; addr = addr; i = i;
    }
}
```

This prevents all warnings and allows parameters to be documented.

**Comment by ealmansi** [comment]
@chriseth I would personally (slightly) favour adding a non-semantic construct (natspec or other type of comment) rather than a new modifier, since I'm not sure a modifier with the semantics "I plan to eventually override this function" fully makes sense. In my experience, other PLs either leave these types of warnings entirely to linters and not to compilers, or have extra-semantic constructs to disable specific warnings (like `@SupressWarnings("unused")` in Java, or `#pragma` in C++ or C#).

**Comment by axic** [comment]
As a quick note: these warnings are not emitted for function prototypes in [interfaces](http://solidity.readthedocs.io/en/develop/contracts.html#interfaces).

**Comment by axic** [comment]
Instead of new annotations I'd rather see disabling the unused variable and state mutability suggestion warnings for abstract functions (i.e. functions without an implementation) and treat them the way we treat interfaces.

**Comment by ealmansi** [comment]
@axic I believe this is the case already for abstract functions. See: #3033.

However, this issue is specifically about non-abstract functions. Like discussed above, there are valid uses cases for disabling unused parameter warnings in functions which do have a body. Essentially, this is the case whenever we want some default behavior (possibly a no-op) which should also be optionally overrideable.

**Comment by barakman** [comment]
Another example:

I have a contract with a non-constant function (i.e., changes state) which returns a value.

For testing purposes only, I want to store the output before returning it, which will allow me to test the function via `web3`.

Here is my implementation:
```
contract MyContract {
    function func(uint256 input) external returns (uint256) {
        uint256 output = ...;
        store(output);
        return output;
    }

    function store(uint256 output) internal pure {}
}

contract MyContractTester is MyContract {
    uint256 public _output;
    function store(uint256 output) internal {_output = output;}
}
```

As you can see, the `store` function is constant in the base class but non-constant in the derived class.

BTW, I could also implement this with an `event`, but it would yield the same effect since emitting an `event` changes the state so any such function cannot be declared constant.

**Comment by chriseth** [comment]
@barakman sorry, but this just does not work. It is like making functions public for testing purposes.

**Comment by nventuro** [comment]
@chriseth are there any plans to work around this warning? The Crowdsale example @ealmansi raised back in Febraury is still being used in OZ, and currently (AFAIK) the only way to get rid of the 'unused parameter' warnings is to remove the argument name (which in turn also requires removing the docstring), and there is no workaround for the 'mutability could be pure' one.

**Comment by chriseth** [comment]
You have to work around the problem that you cannot formally refer to the parameter, yes.
We might just add an exception if the body is empty for now.

**Comment by chriseth** [comment]
I'm closing this in favour of https://github.com/ethereum/solidity/issues/5295 because it got too broad. If that issue does not cover your use-case, please open a new issue.
