### ISSUE TITLE
should we support comparison between two tuples?

### ISSUE THREAD

**Issue by guanqun** [ethereum/solidity#353]
Something like this:

```
(1, 2) == (2, 3)
```

?

**Comment by guanqun** [comment]
I come to this case in this PR: https://github.com/ethereum/solidity/pull/326

**Comment by chriseth** [comment]
Certainly! Especially `(a,b,c) < (d,e,f)` is extremely useful.

**Comment by chriseth** [comment]
Created story: https://www.pivotaltracker.com/story/show/111675742

**Comment by guanqun** [comment]
I'll pick this.
