### ISSUE TITLE
Add missing 'documentation' property to exported JSON AST.

### ISSUE THREAD

**Issue by ealmansi** [ethereum/solidity#3537]
Looking at the AST definition in `libsolidity/ast/AST.h`, all of the following extend from the abstract class `Documented`: `ContractDefinition`, `FunctionDefinition`, `ModifierDefinition`, `EventDefinition`.

However, the JSON converter `libsolidity/ast/ASTJsonConverter.cpp` only includes the `documentation` property available to all `Documented` classes in the case of `ContractDefinition`. This property is missing in the exported JSON for `FunctionDefinition`, `ModifierDefinition`, and `EventDefinition` classes.

Adding this is valuable for tools using the AST exported into JSON that `solc` produces, such as the tool used to generate documentation automatically here: https://openzeppelin.org/api/docs/open-zeppelin.html

**Comment by chriseth** [comment]
Thanks for catching this! Would you be willing to add it?

**Comment by ealmansi** [comment]
Yes, I'll send out a PR in short linking to this issue.
