### ISSUE TITLE
The right way to create a struct instance inside a function

### ISSUE THREAD

**Issue by Grobeu** [ethereum/solidity#3541]
I read in a stackoverflow discussion that if you create a storage variable inside a function, it could overwrite another existing one in the global scope of the smart contract, is that true?

Also, if I wanted to create a new struct variable inside a function, and then add push it to an array, should I create is in the storage space or memory space?

```
MyStruct storage newStruct;
... // modifiying newStruct variables
myStructsArray.push(newStruct);
```

Or

```
MyStruct memory newStruct;
... // modifiying newStruct variables
myStructsArray.push(newStruct);
```

Same question for when wanting to add a newly instantiated struct to a mapping:

```
MyStruct storage/memory newStruct;
...
MyStructMapping[index] = newStruct;
```

**Comment by chriseth** [comment]
It is impossible to allocate an object in storage. Because of that, the latter examples are correct. We should clarify this with examples in the documentation.

**Comment by devzl** [comment]
The line `MyStruct storage newStruct;` will override whatever first state variable that was declared in the global scope of the smart contract.

Declaring the new struct in memory before pushing it to an array seems to work perfectly well as per my tests.

For the mapping, there is no need to instantiate a struct. Just modify the struct by index directly. For example:

    function f (uint index, uint _a, uint _b) public {

        MyStructMapping[index].a = _a;

        MyStructMapping[index].b = _b;

    }

From the docs: 

> Mappings can be seen as hash tables which are virtually initialized such that every possible key exists and is mapped to a value whose byte-representation is all zeros

**Comment by MatthewDLudwig** [comment]
Does the situation differ if you're taking something out of a mapping or array and don't want to create the space for it, just reference the stored object?

    Player storage player = players[_tokenId];
    playerName = player.name;
    internalPlayerId = player.internalPlayerId;
    sellingPrice = playerIndexToPrice[_tokenId];
    owner = playerIndexToOwner[_tokenId];


This code isn't accessing the values of the contract but instead the struct stored in the players mapping.  Should memory have been used or would that cause extra space on the stack to be used.

**Comment by aj07** [comment]
https://github.com/ethereum/solidity/pull/3967

**Comment by ChrisChinchilla** [comment]
Looks like this was resolved.
