### ISSUE TITLE
Error in simple ballot contract

### ISSUE THREAD

**Issue by davec432** [ethereum/solidity#3542]
I'm trying to create my first ether token and I'm getting an error message.  

browser/ballot.sol:120:18: ParserError: Expected primary expression.
        balances[00x2926ad2f538A0e3A0B667B58B3188c9968513287] = _totalSupply;

If anyone can help me I can send tokens when I get this project working

Thank You

**Comment by chriseth** [comment]
You have to change it to `balances[0x2926ad2f538A0e3A0B667B58B3188c9968513287] = _totalSupply;`, i.e. remove one of the zeros.

**Comment by davec432** [comment]
Chriseth, Thanks for your reply, I have resolved this issue already but thanks again anyway.  I will send you some tokens of appreciation (pardon the pun) if you want to tell me your ether wallet address.

Thanks

**Comment by chriseth** [comment]
Thanks a lot! Please send them to the Foundation tip jar: 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359

**Comment by naturalbrnchillr** [comment]
having the problem right now Dec 12 2018
    return ERC20Interface(tokenAddress).transfer(owner, tokens)
