### ISSUE TITLE
Cannot calculate selector of function named transfer

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3544]
# Test case

```solidity
pragma solidity ^0.4.20;

contract Selector {
    function transfer(address, uint) external;
    function calculateSelector() public pure returns (bytes4) {
        return this.transfer(address, uint).selector;
    }
}
```

# Error

> Member "transfer" not unique after argument-dependent lookup in contract C.

# Expected

This behavior is understandable (`transfer` also has a special meaning). But this behavior is currently undocumented.

**Comment by axic** [comment]
Should use `this.transfer.selector`  and 0.5.0 mode (`pragma experimental "v0.5.0";`)

**Comment by chriseth** [comment]
Closing as this will be solved in 0.5.0.

**Comment by k06a** [comment]
Any progress?

**Comment by fulldecent** [comment]
This is resolved. Here is a test case:

```solidity
pragma solidity ^0.5.1;

contract Selector {
    function transfer(address, uint) external;
    
    function calculateSelector() public pure returns (bytes4) {
        return this.transfer.selector;
    }
}
```

**Comment by k06a** [comment]
@fulldecent but how to solve methods overloading?
```
function transfer(address, uint) external;
function transfer(address, uint, bytes) external;
```

**Comment by fulldecent** [comment]
That issue is not resolved and it should be reported separately.

**Comment by fulldecent** [comment]
Another issue still is calculating the erc165 identifier for an entire interface. For more on that, see https://github.com/ethereum/solidity/pull/3729
