### ISSUE TITLE
Windows builds are not updated

### ISSUE THREAD

**Issue by isaackwan** [ethereum/solidity#3545]
Reproduction steps (Imaginary steps obviously, used to Linux sorry):

1. `wget https://github.com/ethereum/solidity/releases/download/v0.4.20/solidity-windows.zip`
2. `unzip solidity-windows.zip && cd solidity-windows`
3. `./solc --version`

Output is as follows:
```
solc, the solidity compiler commandline interface
Version: 0.4.18+commit.9cf6e910.Windows.msvc
```

which is built out of commit 9cf6e910

**Comment by chriseth** [comment]
Are you sur eyou ran the correct binary?
```
> strings solc.exe  | grep 0\\.4
0.4.20
```

**Comment by isaackwan** [comment]
WTF, ran `solc --version` again and I got 0.4.20 now.

/issue
