### ISSUE TITLE
Update spanish translation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3564]
It seems there are people willing to do the translation, it just lacks organisation.

**Comment by chriseth** [comment]
Shall we try to ping them once more? I fear that we need some person properly in charge for the translations.

**Comment by ChrisChinchilla** [comment]
@chriseth Do you know who this person was?

**Comment by chriseth** [comment]
@AdrianClv - we would like to try again perhaps with some more guidance and project management, @ChrisChinchilla is willing to coordinate.

**Comment by AdrianClv** [comment]
@chriseth It's ok. I can transfer the ownership of the repo to someone else if he is willing to work on it.

**Comment by franzihei** [comment]
We are currently working on a new, hopefully more structured workflow for the Solidity docs translations. I will ping you once this is ready. Closing this issue for now, you can track the progress of the new process etc. in issue #10119.
