### ISSUE TITLE
UnimplementedFeatureError: Only in-memory reference type can be stored.

### ISSUE THREAD

**Issue by vrolland** [ethereum/solidity#3577]
Hello Guys,

I experiment an odd behavior with nasty (nested) structs.

The following code works like a charm:
```
pragma solidity 0.4.20;

contract test {
    
    struct S1 {
        uint param1;
        S2 structure2;
    }

    struct S2 {
        uint param2;
    }
    
    S1 object;
    
    function test2() external {
        object = S1( 1, S2(2));
    }
}

```
but when I change the visibility of "object" to public:
`S1 public object;`

I get this error:
> UnimplementedFeatureError: Only in-memory reference type can be stored.

I don't get what happen. 

Any idea?

Best,

**Comment by chriseth** [comment]
Using `public` with such a type is not yet supported. It might appear with 0.5.0, I have to check.

**Comment by vrolland** [comment]
Fair enough. Thank you for your quick answer !

**Comment by L-F-Escobar** [comment]
@chriseth Any idea when it will be allowed? I just discovered this issues when attempting to nest structs since it appears you can only have around 11 members in a struct

**Comment by chriseth** [comment]
This is working in 0.4.21.
