### ISSUE TITLE
Create test fixture for tests that create CompilerStack instances

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3584]
... and move the CompilerStack into a member variable.

**Comment by ksolo** [comment]
@chriseth I'd like to try and help with this. Can you provide any more details so I can get a better idea of what's needed?

**Comment by chriseth** [comment]
Sure! There are many test files (e.g. Metadata.cpp, Imports.cpp) that create an instance of CompilerStack per test (not test file) and adjust certain settings on it. This can be moved into a test fixture as it is done in AnalysisFramework.h and others. The best solution would probably be to even move out the CompilerStack member from AnalysisFramework.h (and other fixtures) into a general base class that contains all functionality common to the frameworks.

Does that explain it?

**Comment by ksolo** [comment]
I think so. I'll give it a shot and see what I can do. I'll start a PR early and may ask for feedback while it is still in progress.

**Comment by chriseth** [comment]
Please create a pull request as soon as you have something, so we can help by commenting.

**Comment by ksolo** [comment]
I ended up having a few things come up, but I do plan on working on this Sunday. I'll get a PR open ASAP and we'll go from there. Thank you for checking in on it!

**Comment by ksolo** [comment]
@chriseth I'm going through a quick c++ primer now and will have something for you to look at tonight.

**Comment by ksolo** [comment]
@chriseth I'm getting back to this.

**Comment by ksolo** [comment]
@chriseth 
I'm getting an error in the test run (reverted my changes and rebased with latest develop branch)

```
$  ./test/soltest -- --no-ipc --testpath ./test/libsolidity
Running 1136 test cases...
/Users/ksolo/Projects/opensource/solidity/test/libevmasm/Optimiser.cpp:1050: error: in "Optimiser/jumpdest_removal_subassemblies": check { sub->items().begin(), sub->items().end() } == { expectationSub.begin(), expectationSub.end() } has failed.
Mismatch at position 1:  PUSH 2 !=  Tag 1
Mismatch at position 2:  JUMP	 !=  PUSH 2
Mismatch at position 3:  Tag 4 !=  JUMP
Mismatch at position 4:  PUSH 7 !=  Tag 4
Mismatch at position 5:  PushTag 4 !=  PUSH 7
Mismatch at position 6:  JUMP	 !=  PushTag 4
Collections size mismatch: 7 != 8
```
Do you have any suggestions on getting the tests to run?

**Comment by chriseth** [comment]
@ksolo this is an unrelated problem that only occurs on certain macos versions. The proposed fix is here: https://github.com/ethereum/solidity/pull/3999

Perhaps it is better to ignore that problem for now.

**Comment by axic** [comment]
@chriseth do we really need this? There doesn't seem to be too many tests using it.

**Comment by chriseth** [comment]
I still think this would be beneficial.
