### ISSUE TITLE
Evaluate whether CompilerStack::reset() should reset optimizer and evm version setting

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3586]
reset should be called when adding a new source. It should reset the compiler state, but not the complier settings.

If this is done, some reset calls in the testing frameworks might get redundant.

**Comment by chriseth** [comment]
Some other cleanup around here might also be done.

**Comment by axic** [comment]
It seems this is already done? Or do you mean to remove the `keepSources` flag?

**Comment by chriseth** [comment]
I would like a general cleanup of the internal interface of CompilerStack. Do we really need a reset function, for example? Do we really need a way to incrementally add source files?

**Comment by axic** [comment]
Proposal:
```
void CompilerStack::reset(bool _keepSettings = false)
{
        m_stackState = Empty;
        m_sources.clear();
        m_smtlib2Responses.clear();
        m_unhandledSMTLib2Queries.clear();
        if (!_keepSettings)
        {
                m_remappings.clear();
                m_libraries.clear();
                m_evmVersion = langutil::EVMVersion();
                m_optimiserSettings = OptimiserSettings::minimal();
                m_metadataLiteralSources = false;
        }
        m_globalContext.reset();
        m_scopes.clear();
        m_sourceOrder.clear();
        m_contracts.clear();
        m_errorReporter.clear();
}
```

Currently reset doesn't touch `metadataLiteralSources` and `remappings`.

**Comment by chriseth** [comment]
Looks good!
