### ISSUE TITLE
contract invocation: raw call with string param won't be passed

### ISSUE THREAD

**Issue by mirgj** [ethereum/solidity#3591]
I'm trying to invoke another contract in solidity using raw calls but I'm encountering some problems.
```solidity
instance.call.gas(gas).value(price)(bytes4(keccak256("method(string)")), param);
```
this instruction is inside my second contract and while I try to get the value of the `param` from my first contract method its empty but instead its value is passed into `msg.data`.

I added an event on my first contract to see how the parameters has been sent.

```solidity
function method(string param) payable external {
 Debug(param, msg.sender, msg.value, msg.data);
}
```
basically `param` is always empty while the data inside `msg` are always sent. In `msg.data` there is the parameter value (in bytes).

Using this other kind of invocation will work well

```solidity
instance.method.gas(gas).value(price)(param);
```
but it won't help me much because in this case will throw an exception that I couldn't handle in the caller block (that's why I'm going for the raw call) 

I'm using **solc@0.4.19**

**Comment by dryruner** [comment]
Coming from stackoverflow and experiencing the same issue here.

**Comment by chriseth** [comment]
Can you link the stackoverflow question, please? You should use `instance.call` only in extremely rare circumstances. This is a very dangerous way to call another contract.

**Comment by chriseth** [comment]
Ah sorry, the reason is explained at the end of the issue. Can you please post complete smart contract code so we can try to reproduce the issue?

**Comment by chriseth** [comment]
It looks like you do not perform abi encoding properly. We will soon support `abi.encode` that could help you there, until then, you have to do it manually.

**Comment by dryruner** [comment]
@chriseth Hi Chris here's the link - https://ethereum.stackexchange.com/questions/40769/solidity-contract-invocation-raw-call-with-string-param-wont-be-passed, basically the same.

My question is: What if I don't know the contract type of instance (it's just an address), but I do know that it has a function of signature say func(string)? Then I could only use instance.call(bytes4(keccak256("func(string)")), raw_str)....

**Comment by chriseth** [comment]
```
interface StringFuncContract {
  function func(string);
}
contract MyContract {
  function myFunction(address _a) {
    StringFuncContract(_a).func("abc");
  }
}
```

Or even better:
```
contract MyContract {
  function myFunction(StringFuncContract _a) {
    _a.func("abc");
  }
}
```

**Comment by dryruner** [comment]
Ah it's an awesome trick! Thank you Chris!  A bit curious since I'm not able to find any detail about it from solidity documentation: how does _a find func's code to invoke, as StringFuncContract.func has no implementation? They just share the same function signature

**Comment by dryruner** [comment]
@chriseth I've deployed test contracts to demonstrate the issue:

TestCallWithString.sol - has a function "callback(string)" to be invoked by other contract and the string argument passed in is stored as result:
https://rinkeby.etherscan.io/address/0x78134e6ab7d952692ef9f35751f64d925609475d

Call.sol - calls TestCallWithString.callback using call:
https://rinkeby.etherscan.io/address/0xa058a62979b12aa6fba8852a1447699dd0ec267f

The passed string is lost if using call:
From this tx: https://rinkeby.etherscan.io/tx/0x6f0932bf5302b0d107e5fede1af225e3375c38186eb511c628fb61b593a57a42;
and its event logs: 
![image](https://user-images.githubusercontent.com/1220361/36878383-95592882-1d73-11e8-9bfb-9f70914faffc.png)

Also from TestCallWithString's state: timestamp is set correctly but result is empty:
![image](https://user-images.githubusercontent.com/1220361/36878403-af176306-1d73-11e8-9682-0064c5cacee6.png)

So raw call with string param is indeed not passed.

**Comment by chriseth** [comment]
@jonnyhsy if you use a raw call, you have to properly encode the string argument. I explained it on the stackexchange question.
