### ISSUE TITLE
Build script install ffmpeg

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3592]
On this step:

    ./scripts/install_deps.sh

All kinds of things are installing, including ffmpeg.

There is probably some "update all" in there which is unnecessary.

**Comment by axic** [comment]
Would you mind giving more detail such as OS and OS version?

**Comment by axic** [comment]
Apparently this happen on Mac with brew based on @pinnaclesystemsgroup's report.

**Comment by axic** [comment]
This has been fixed IIRC.
