### ISSUE TITLE
Release 0.4.20 is not available via apt-get on Ubuntu

### ISSUE THREAD

**Issue by vlad-mik** [ethereum/solidity#3593]
As recommended by official docs (http://solidity.readthedocs.io/en/develop/installing-solidity.html) I tried to install latest stable version of Solidity compiler on Ubuntu via the following commands:

    sudo add-apt-repository ppa:ethereum/ethereum
    sudo apt-get update
    sudo apt-get install solc

Installation was successful but installed version appeared to be 0.4.19 while I expected it to be 0.4.20 because this is latest stable release according to this page: https://github.com/ethereum/solidity/releases

This was clean install, not an upgrade, i.e. Solidity compiler was not installed on this machine ever before.

Here is operation system version I use:

    Linux <snip> 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Before trying to install on Ubuntu, I successfully upgraded Solidity to 0.4.20 on MacOS via `brew`.

**Comment by axic** [comment]
Which Ubuntu version are you running?

@chriseth wouldn't it make sense removing the package (or adding some other kind of notification) on outdated distributions?

```
solc | 1:0.4.20-0ubuntu1~xenial | Ethereum Build Automation (2018-02-14)
solc | 1:0.4.20-0ubuntu1~trusty | Ethereum Build Automation (2018-02-14)
solc | 1:0.4.20-0ubuntu1~artful | Ethereum Build Automation (2018-02-14)
solc | 1:0.4.19-0ubuntu1~zesty | Ethereum Build Automation (2017-11-30)
solc | 1:0.4.17-0ubuntu1~vivid | Ethereum Build Automation (2017-09-21)
solc | 1:0.4.13-0ubuntu1~yakkety | Ethereum Build Automation (2017-07-06)
solc | 1:0.4.6-0ubuntu1~wily | Ethereum Build Automation (2016-11-22)
```

**Comment by mikhail-vladimirov** [comment]
$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.3 LTS
    Release:        16.04
    Codename:       xenial

But initially I encountered this problem when I tried to assemble docker image with Solidity compiler inside based on official Ubunty "latest" image.  Same result: 0.4.19 was installed instead of 0.4.20.

**Comment by vlad-mik** [comment]
$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.3 LTS
    Release:        16.04
    Codename:       xenial

But initially I encountered this problem when I tried to assemble docker image with Solidity compiler inside based on official Ubunty "latest" image.  Same result: 0.4.19 was installed instead of 0.4.20.

**Comment by chriseth** [comment]
It turns out we had a build failure on xenial which we didn't notice. The build problem has been fixed in the meantime, but I'm not sure we should spend time backporting the fix and re-publishing. Our release process also does not really know such a procedure. I'd rather try to release 0.4.21 this week.

**Comment by chriseth** [comment]
Build for 0.4.21 was successful, please reopen if it still does not work.
