### ISSUE TITLE
Output which functions are not implemented

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3594]
Currently, `--bin` outputs nothing if a contract is a virtual contract.

There does not appear to be any option which allows you to find which functions of a contract are not implemented.

This results in the dreaded:

> This contract does not implement all functions and thus cannot be created.

The programmer's intention is to implement all functions and compile the contract. However Remix IDE and solc are lacking a way to help the programmer find which function is not implemented. This can take significant time.

---

# Test case

**ERC165.sol**

```solidity
pragma solidity ^0.4.20;

interface ERC165 {
    function supportsInterface(bytes4 interfaceID) external view returns (bool);
}
```

**OtherInternalAbstractContract.sol**

```solidity
pragma solidity ^0.4.20;

interface ERC165 {
    function anInternal() internal;
}
```

**ImplementERC165.sol**

```solidity
import "./ERC165.sol";
import "./OtherInternalAbstractContract.sol";
contract ImplementERC165 is ERC165, OtherInternalAbstractContract {
    function supportsInterfaceTYPO(bytes4 interfaceID) external view returns (bool){}
    function anInternalTYPO(){}
}
```

The programmer made two typos on the implementing contract, can you find them?

# Discussion

There is no good way for a programmer to learn which function they failed to implement. For a large project, this can become a large pain point.

I tried searching using this:

    solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,compact-format,devdoc,hashes,interface,metadata,opcodes,srcmap,srcmap-runtime,userdoc ImplementERC165.sol

None of the options gave me the needed information.

Persisting I found a way to find *some* unimplemented functions:

```bash
# A list of external functions
solc --combined-json ast,hashes ImplementERC165.sol | jq '.contracts."ImplementERC165.sol:SuERC165".hashes|keys|.[]'
# A list of implemented functions
solc --combined-json ast,hashes ImplementERC165.sol | jq '.sources."ImplementERC165.sol"|..|select(.implemented)?|{name}|.[]'
```

# Proposal (RFC)

Add a new command line function: `--functions` which returns an array of the functions of each contract, including through inheritance. And each function is NULL if unimplemented or shows the name of the contract that implements that function. This even includes private and internal functions.

**Comment by axic** [comment]
Currently, trying to instantiate an abstract contract will output all unimplemented functions: `contract C { function f() { new ImplementERC165(); } }`

I'd rather improve this in a generic way, see #3596.

**Comment by mikgross** [comment]
Hi @axic , has this issue advanced in any way? cheers!

**Comment by naddison36** [comment]
Why does Solidity even compile these? Why can't it fail the compile because not all the functions have been implemented?
I've wasted too many hours debugging contracts only to find I've stuffed the inheritance which has resulted in weird partially working contracts.

**Comment by chriseth** [comment]
@naddison36 you might like #7358

**Comment by chriseth** [comment]
This has been mostly implemented by https://github.com/ethereum/solidity/pull/7358 we just need to list the functions in the error message.

**Comment by chriseth** [comment]
Finished in https://github.com/ethereum/solidity/pull/7666
