### ISSUE TITLE
libsolc external API compilation optimization runs

### ISSUE THREAD

**Issue by dimorinny** [ethereum/solidity#3595]
Hi.

I found, that I can't pass custom param for compilation optimization runs count in solc-js binding.

Why you decided to block opportunity to specify this param and hardcoded it in libsocl? https://github.com/ethereum/solidity/blob/70790d4729a8cee7d587bf274ed1733b255b2120/libsolc/libsolc.cpp#L128-L129

Thanks a lot.

**Comment by dimorinny** [comment]
cc @fanatid

**Comment by axic** [comment]
You are referring to the backwards compatibility layer, which itself never had the option to adjust that.

One should use `compileStandard`, which implements the latest API: https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description

It also available via solc-js: https://github.com/ethereum/solc-js#from-version-0411
