### ISSUE TITLE
Use variable before declaration

### ISSUE THREAD

**Issue by AlexejShevchenko** [ethereum/solidity#3597]
```
contract A{
function getA() public pure returns(uint){
        uint b = a + 1;   // <- use variable 'a' before declaration
        uint a = 1;
        return b;
    }
}
```
This code is compiled without errors.

**Comment by axic** [comment]
This is by design: http://solidity.readthedocs.io/en/develop/control-structures.html#scoping-and-declarations

It will be changed in the next breaking release to follow C++/C99 scoping rules.
