### ISSUE TITLE
Please remove "brew update" in the install_deps.sh script. 

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [ethereum/solidity#3598]
The use of the "brew update" command in the install_deps.sh script should be changed to only update dependencies for this repo, and not the user's entire installed brew package library as the current install script does now. The wholesale update of user's package library risks breaking other applications and development chains in the user's target system as a result which may depend on specific "outdated" brew packages which the user has intentionally chosen not to update.

**Comment by axic** [comment]
I guess this is the same issue as #3592 ?

**Comment by pinnaclesystemsgroup** [comment]
Yes its the same issue. Was told to post it here instead of filing a pull
request

Thanks


On Feb 26, 2018 4:20 AM, "Alex Beregszaszi" <notifications@github.com>
wrote:

I guess this is the same issue as #3592
<https://github.com/ethereum/solidity/issues/3592> ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/solidity/issues/3598#issuecomment-368437148>,
or mute the thread

**Comment by axic** [comment]
Closing this in favour of the other one.

**Comment by pinnaclesystemsgroup** [comment]
Ok, but please be advised the moderator of the other pull request post
closed that incident request and told me to post it to the "issues" area
here .





‌

**Comment by pinnaclesystemsgroup** [comment]
Alex

I don't wish to send you down the wrong path with my issue. Simply, the
install_dep.sh script invokes brew update against the target systems
package library instead of selectively updating and installing just the
packages that are required  ....

Thanks


‌
