### ISSUE TITLE
Update build guide for solc 1.2 on OSX

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#36]
I can't find instructions for setting up the new solidity repo and building 1.2 on OSX (particularly the eth dev cmake environment). Everything in the wiki is outdated.

**Comment by nmushegian** [comment]
is anyone actually looking at this?

**Comment by chriseth** [comment]
Sorry, especially MacOS is still in some kind of flux regarding the build system.

**Comment by chriseth** [comment]
Could you please check if this is still an issue?
