### ISSUE TITLE
Provide name hints for tuples in ABI-json

### ISSUE THREAD

**Issue by iikirilov** [ethereum/solidity#3618]
Hey, I'm using pragma experimental ABIEncoderV2; when compiling a contract with a struct as a constructor parameter. I am looking to generate a java wrapper class for web3j to use java to communicate with the contract, however the abi is rather ambiguous and generic
```
{  
   "components":[  
       {  
          "name":"id",
           "type":"string"
       },
       {  
          "name":"name",
           "type":"string"
       }
   ],
   "name":"_toSet",
   "type":"tuple"
}
```
        
I know this is an experimental feature, but I am wondering what are the plans for the final product. I envisage the "type":"tuple"should become "type":<struct_name>?
N.B. this is a generic example but I can see a number of issues with this kind of encoding, checkout web3j/web3j#368 for more info.

**Comment by axic** [comment]
This is to be improved with #2899. Please read that issue thoroughly, it should explain this.

**Comment by chriseth** [comment]
@iikirilov the tl;dr is that user-defined types in the ABI are not named, because there is no way to make such names globally unique. ABI only knows anonymous tuples with named components. Solidity's structs are mapped to those, stripping off the identity of the struct.

**Comment by chriseth** [comment]
What would be your suggestion?

**Comment by iikirilov** [comment]
Correct me if I'm wrong, such user-defined names are unique to the contract. As suggested in #2899 an extra field with user-defined name could be used when generating the ABI.

What is the downside to adding a field to the ABI for such cases?

**Comment by chriseth** [comment]
Yes, user-defined names are unique to the contract, but the contract name is not globally unique, it only gets globally unique for a compilation run if you prepend the full path to the source name.

**Comment by iikirilov** [comment]
Agreed, but I do not understand the why the added should be globally unique. An example encoding of what is proposed follows:

```
{  
   "components":[  
       {  
          "name":"id",
           "type":"string"
       },
       {  
          "name":"name",
           "type":"string"
       }
   ],
   "name":"_toSet",
   "type":"tuple"
   "namedType": "Foo"
}
```
An extra field added like this for such cases would cause the swarm hash to change, which is essentially what happens when compiling the same contract with different version of Solidity anyway, so developers would expect this.

Apart from the fact that the ABI files will be (slightly) larger I do not see an immediate drawback to this. From my understanding the ABI is not stored on the blockchain so no extra gas cost is incurred. Also adding an extra field should not break backwards compatibility when interacting with contracts via geth/parity etc. 

Consider the case, where there are multiple structs in a contract used in multiple function input/output. With the current ABI, we are able to generate classes with ambiguous name such as `Struct1`, `Struct2` etc. It does not make sense to expect the developer to know that class `Struct1` in their java smart-contract wrapper is the same as the `Foo` struct in their contract.

In either case, this metadata is invaluable information for creating high-level construct such as smart-contract wrappers to interact with smart contract via major languages such as Java. It will make it easier for developers using web3j/ether.js/nethereum to be able to create instances of their structs in their native language to call methods that require those structs as parameters.

**Comment by chriseth** [comment]
@iikirilov you have a point, perhaps it is not too important that the names are unique. Could you explain how exactly you would use such information? We haven't really discussed that yet. Please also consider cases where users might be tricked into using the wrong struct. Furthermore, we should check what information an algorithm using the ABI information needs to know in addition to just the ABI (currently, no additional information is require).

**Comment by iikirilov** [comment]
Web3j has a module to autogenerate smart-contract wrappers from smart contract ABI. One would type in terminal:
```
web3j solidity generate [--javaTypes|--solidityTypes] /path/to/<smart-contract>.bin /path/to/<smart-contract>.abi -o /path/to/src/main/java -p com.your.organisation.name
```
This creates a Java class representing their contract using [JavaPoet](https://github.com/square/javapoet). In our case, the generated constructs are typesafe so one could not possibly use the wrong struct. The class is used to interact with the the smart contract, including things like deploying a new contract, loading an existing contract and executing functions.

I believe discussing the algorithm used to autogenerate these smart-contract wrappers is out of the scope of this issue. However, feel free to checkout the implementation [here](https://github.com/web3j/web3j/tree/master/codegen/src/main/java/org/web3j/codegen).

**Comment by chriseth** [comment]
Sure, Solidity is also type safe, but still, people could confuse two structs of the same name (but different namespaces). I'm fine with ignoring this potential point of confusion, though. If the compiler only specifies the name of the struct and not its full location, would your tool still be able to work with it?

**Comment by iikirilov** [comment]
Yes, we do not need the full location for our use case. 

I do see the potential for confusion now. Let us consider the following case:
1. Library A with struct W
2. Library B with struct X
3. Contract C with struct Y which imports Libraries A and B
4. Contract D with struct Z,
where the name of W, X, Y, Z is `MyStruct`.

The ABI of A and B is empty as they are libraries.

The ABI of C will include:
every instance of W as `A.MyStruct`,
every instance of X as `B.MyStruct` and
every instance of Y as `MyStruct`

The ABI of D will include every instance of Z as `MyStruct`

To remove the ambiguity just use the fully qualified name such that:
C will represent Y as `C.MyStruct` and
D will represent Z as `D.MyStruct`

Now, even if D imports C the "name hint" for each struct will be unique, until you get two contract with the same name, but that is a different issue.

**Comment by chriseth** [comment]
I specifically had the case of two contracts with the same name in mind. This is perfectly fine if they are in different files.

**Comment by juanfranblanco** [comment]
With Netherum we will face the very same problem, in a similar way as we create a class per command / query input / ouput message, each struct will represent also a class type. It will be great that for a Contract each struct type component will be listed (to simplify and avoid duplication).

Having something like described in #2899 will solve the problem, but also the internal parameter name. 

For example Contract X has struct Y. 
Contract X could have methods Add(Y), Update(Y), DoSomethingWith(Y) 
Y should be listed in the Contract ABI.

The abis could become smaller as you would only need the input / output parameter pointing to the struct type including its name.

But if Y has Z and A internally each element needs to be named so a hierarchical structure can be created.

**Comment by juanfranblanco** [comment]
Now the interesting part is when you are creating "Standard Contracts" that can be extended / inherited, for example, a custom ERC20 with extra functions. 

In this scenario, most of your business logic (for example validation, assignment etc) will be the duplicated if having duplicated types. 

Probably in this scenario the end user will have to remove duplications himself / herself providing the right namespace.

**Comment by juanfranblanco** [comment]
An example (using a previous issue)

```solidity
pragma solidity 0.4.23;
pragma experimental ABIEncoderV2;

contract TestContract
{
    struct SubStruct {
        uint256 id;
        string description;
    }

    struct TestStruct {
        SubStruct subStruct1;
        SubStruct subStruct2;
    }

    event SomethingDone(uint256 indexed id1, uint256 indexed id2 );

    TestStruct[] internal tests;

    function addTestStruct(TestStruct testStruct) public
    {
        tests.push(testStruct);
    }

    function doSomethingWithStruct(TestStruct testStruct) public {
        emit SomethingDone(testStruct.subStruct1.id, testStruct.subStruct2.id);
    }
}
```

Results in this abi

```
[
   {
      "constant":false,
      "inputs":[
         {
            "components":[
               {
                  "components":[
                     {
                        "name":"id",
                        "type":"uint256"
                     },
                     {
                        "name":"description",
                        "type":"string"
                     }
                  ],
                  "name":"subStruct1",
                  "type":"tuple"
               },
               {
                  "components":[
                     {
                        "name":"id",
                        "type":"uint256"
                     },
                     {
                        "name":"description",
                        "type":"string"
                     }
                  ],
                  "name":"subStruct2",
                  "type":"tuple"
               }
            ],
            "name":"testStruct",
            "type":"tuple"
         }
      ],
      "name":"addTestStruct",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "components":[
               {
                  "components":[
                     {
                        "name":"id",
                        "type":"uint256"
                     },
                     {
                        "name":"description",
                        "type":"string"
                     }
                  ],
                  "name":"subStruct1",
                  "type":"tuple"
               },
               {
                  "components":[
                     {
                        "name":"id",
                        "type":"uint256"
                     },
                     {
                        "name":"description",
                        "type":"string"
                     }
                  ],
                  "name":"subStruct2",
                  "type":"tuple"
               }
            ],
            "name":"testStruct",
            "type":"tuple"
         }
      ],
      "name":"doSomethingWithStruct",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "name":"id1",
            "type":"uint256"
         },
         {
            "indexed":true,
            "name":"id2",
            "type":"uint256"
         }
      ],
      "name":"SomethingDone",
      "type":"event"
   }
]

```

**Comment by conor10** [comment]
@chriseth @axic did you have any further thoughts on the above? It would be really useful if for the web3j community we could have an additional field in the ABI for structs

**Comment by axic** [comment]
Sorry for the delay. I haven't fully read this thread yet, but proposed to have an `annontatedType` next to the current *encoding* `type` field. See #2899.

**Comment by juanfranblanco** [comment]
@chriseth Following our chat a while ago, would it be possible to add the hint of the struct type to the abi? This is probably the simplest solution before we have @axic ```annotatedTypes```

Similar to what @iikirilov said, this will allow for simple identification of the different structs and be code generated accordingly so we can avoid duplication of types generated.

```json
{  
   "components":[  
       {  
          "name":"id",
           "type":"string"
       },
       {  
          "name":"name",
           "type":"string"
       }
   ],
   "name":"_toSet",
   "type":"tuple"
   "namedType": "Foo"
}
```

**Comment by chriseth** [comment]
@juanfranblanco @iikirilov sorry for the delay, we are working on this now. Please check out the [PR](https://github.com/ethereum/solidity/pull/7033) to see if this is sufficient for your needs. Thanks!
