### ISSUE TITLE
sha3 output is not per SHA-3 standard

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#362]
Solidity's `sha3` function does not return hashes per the SHA-3 (FIPS 202) standard.  This is a tracking issue for a Solidity function that does return SHA-3 output.

**Comment by axic** [comment]
It returns a Keccak hash with the original padding. It is mentioned in the Yellow paper too. It might make sense proposing an EIP to rename the method or to include a `keccak` opcode too, but it is not as simple as that given how widely it is used.

**Comment by chriseth** [comment]
If I understand this correctly, this is about providing a compiler-generated function that computes the sha3 hash function per the FIPS 202 standard. If such a function is needed, it has to be either implemented in some languages that compiles to EVM (and can be used as a library) or has to be added as a precompiled contract as a hard fork.
