### ISSUE TITLE
"Spanning multiple lines" should not be on its own line to reduce confusion.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3620]

**Comment by AnthonyBroadCrawford** [comment]
@chriseth  is it okay if I get assigned to this issue.  If I have any questions who where can I go to ask a few questions?

**Comment by axic** [comment]
@AnthonyBroadCrawford the best place is to join https://gitter.im/ethereum/solidity-dev and discuss questions there.

**Comment by chriseth** [comment]
@AnthonyBroadCrawford please go ahead! Github does not let us formally assign this to you, though, but it is reserved for you :)

**Comment by AnthonyBroadCrawford** [comment]
@chriseth awesome, digging in today/tonight.  Thank you!
@axic I'll hop onto the group chat for the million questions I'm sure to have.  

Thanks both of you.

**Comment by chriseth** [comment]
The message is generate in SourceReferenceFormatter.cpp:83. It is triggered for example if you have a file that does not have a pragma for the compiler version. Then the generated warning applies to the whole file (and thus "spanning multiple lines").

**Comment by AnthonyBroadCrawford** [comment]
@chriseth Awesome, thank you!

**Comment by AnthonyBroadCrawford** [comment]
@chriseth I've made the change to have it appear on the same line as the ^ and am wondering if I should wrap this change in a unit test within the tests folder?  Is that something that would typically be tested in the project?

**Comment by AnthonyBroadCrawford** [comment]
@chriseth I opened up a pull request to gain feedback on the code.  I followed the guidelines to do so.  Let me know if you have any questions. 

https://github.com/ethereum/solidity/pull/3640
