### ISSUE TITLE
emscripten test isn't working (I believe it's a sourceforge issue).. any alternatives?

### ISSUE THREAD

**Issue by chris-shyft** [ethereum/solidity#3623]
from the tag v0.4.20, on the emscripten test, I'm getting: (from travis-ci.org)

<img width="1117" alt="screen shot 2018-02-28 at 5 19 13 pm" src="https://user-images.githubusercontent.com/34154131/36813627-91c675a8-1cab-11e8-8367-7e86a9a9142c.png">

do we have any alternatives or is this just outright broken for now?

**Comment by axic** [comment]
This hasn't been occurring since.
