### ISSUE TITLE
Source maps sometimes have sourceIndex === -1

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereum/solidity#3629]
This might not be an issue, but I just can't figure out how to interpret that.

I'm compiling my contracts with source maps and when I try to decode them I get `sourceIndex === -1`. The docs on the source maps don't describe that possibility. I looked into the code and found [this line](https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/CompilerStack.cpp#L880)
I've printed the location to find out why fas my file name not in the mapping and the file name is: `--CODEGEN--`.  Could you please give some explanation on what does that mean, what causes that and how should I handle that?

**Comment by axic** [comment]
It is code generated by "inline assembly" statements generated by the compiler: https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/CompilerContext.h#L193-L201

They do not have an accompanying source code supplied by the user.

**Comment by axic** [comment]
I mean the above is true for those marked `--CODEGEN--`. I don't think there is any other way currently for a piece of code lacking a source index.

**Comment by LogvinovLeon** [comment]
Thanks

**Comment by axic** [comment]
It would be nice to document this. Would you be interested documenting it?

**Comment by recmo** [comment]
I just read through the Solidity source. If I understand correctly, whenever `appendInlineAssembly` is called, these instructions would be attributed to `--CODEGEN--`.

This happens in `memoryCopy32`, `memoryCopy`, `deployLibrary` and `appendMissingFunctions`, no where else at the moment.

In the case of memory copies, it should be quite clear which line of Solidity code caused the memcopy to be there.

In the case of `deployLibrary` and `appendMissingFunctions` I can see that it is harder to identify code that corresponds to it. Though I would suggest to map it to the source range that spans the entire contract, as this would be in line with how the sourcemap works for the function selector logic.

**Comment by chriseth** [comment]
The value of `-1` is a general "unknown" value. Code generation through compiler-generated inline assembly is also performed with the new ABI encoder. In this case, lots of code will be re-used from many places, and it can even be the case that an internal function of a library uses the same encoding code as a function in a contract in a different source file. Because of that, I think we cannot entirely remove this unknown value.

Remix currently treats it as no change in source location.

**Comment by axic** [comment]
@LogvinovLeon or @Recmo are you interested in documenting this?

If not, @ekpyron or @bit-shift, would you do it?
