### ISSUE TITLE
 pass a decimal in a function whose parameter is uint!

### ISSUE THREAD

**Issue by mxito3** [ethereum/solidity#3636]
function _transfer(address _from, address _to, uint _value) internal {
        require (_to != 0x0);                               // Prevent transfer to 0x0 address. Use burn() instead
        require (balanceOf[_from] >= _value);               // Check if the sender has enough
        require (balanceOf[_to] + _value > balanceOf[_to]); // Check for overflows
        require(!frozenAccount[_from]);                     // Check if sender is frozen
        require(!frozenAccount[_to]);                       // Check if recipient is frozen
        balanceOf[_from] -= _value;                         // Subtract from the sender
        balanceOf[_to] += _value;                           // Add the same to the recipient
        Transfer(_from, _to, _value);
    }
as you can see,this function is in part of  'Improved Coin' of 'https://www.ethereum.org/token'. which used to transfer coin from address to another!but the question is i want transfer coin in decimal,but the compiler told me i can't!what should i do?could you give me some help?

**Comment by axic** [comment]
I think this question is better suited for http://ethereum.stackexchange.com/ or https://gitter.im/ethereum/solidity

Hint: `uint` support no decimal points (they will be in "fixed point types").
