### ISSUE TITLE
Random Yul code generator

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3639]
## Abstract

Valid YUL code needs to be generated for testing purposes.

## Motivation

There are two ways to do this

[Low effort] Use a fuzzer with existing yul code samples for code generation. The benefit is that this is very little work, the disadvantage is that yul code generated semi-randomly may not even be parseable. This means that we won't be able to test deeper portions of the YUL compiler/optimizer.

[High effort] Write a grammar for yul [1] and write a protobuf-based-libfuzzer yul generator [2] to stress test the optimizer. The main advantage compared to the purely coverage guided yul generation approach is that the yul generator is probably more likely to be parseable and can hence test deeper portions of the program.

[1]: https://solidity.readthedocs.io/en/v0.5.0/yul.html#specification-of-yul
[2]: https://github.com/llvm-mirror/clang/blob/master/tools/clang-fuzzer/cxx_proto.proto

**Comment by bshastry** [comment]
## Abstract

The YUL optimizer needs to be fuzz tested. See also #3638 and #3639

## Motivation

1. Step 1: Write the test harness
2. Step 2: Devise ways to assert optimizer inconsistencies

### Test harness

There are two ways to do this

[Medium effort] Write a libFuzzer test harness that takes a corpus of existing `yul` code that is available in the source repo, and uses random-but-clever-coverage-guided-mutations of this corpus to stress test the optimizer

[High effort] Write a grammar for yul [1] and write a protobuf-based-libfuzzer yul generator [2] to stress test the optimizer. The main advantage compared to the purely coverage guided yul generation approach is that the yul generator is probably more likely to be parseable and can hence test deeper portions of the program.

[1]: https://solidity.readthedocs.io/en/v0.5.0/yul.html#specification-of-yul
[2]: https://github.com/llvm-mirror/clang/blob/master/tools/clang-fuzzer/cxx_proto.proto

### Assertion

Assertion should be based on inconsistencies between execution traces corresponding to input yul code and output (optimized) yul code. At a high level something like so:

```
yul_in_trace = traceYul(yul_in);
yul_out_trace = traceYul(yul_out);
assert(yul_in_trace == yul_out_trace);
```

where `yul_in` and `yul_out`  are the (fuzzed) input yul code and the optimized yul code.

**Comment by chriseth** [comment]
A first MVP could be the following:
 - variable declarations
 - assignments
 - restricted set of built-in functions (EVM opcodes)
 - variable references
 - constants

Variables can only be referenced if they have been defined before. This means the first statement has to be a variable declaration.

The set of opcodes to use could be: add, sub, mul, div, eq, lt, gt, mstore, mload, sstore, sload

**Comment by axic** [comment]
There is an initial version of this in #3846.
