### ISSUE TITLE
Re-check documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3645]
Everyone should read through the documentation, check that all examples are meaningful, work and the code is up to date.

**Comment by chriseth** [comment]
I'm currently reading through it and will continue at https://solidity.readthedocs.io/en/develop/types.html#fixed-point-numbers

**Comment by chriseth** [comment]
Updated everything up to and not including Reference Types.

**Comment by chriseth** [comment]
Read documentation up to and not including "Contracts".

**Comment by chriseth** [comment]
Will continue with "Security Considerations".

**Comment by erak** [comment]
Should we add a section about arithmetic over / underflows to our "Security Considerations"?

**Comment by chriseth** [comment]
Yes, please do!
