### ISSUE TITLE
Coding standars link on the 'contributing to Solidity' page errors to a 404 

### ISSUE THREAD

**Issue by AnthonyBroadCrawford** [ethereum/solidity#3654]
# Issue 
When clicking on the link 'coding standards' in the "workflow for pull requests" section on the *Contributing* to Solidity page found [here](https://solidity.readthedocs.io/en/latest/contributing.html) it errors on a 404.  

## Steps to recreate 

1.  Navigate to the Contributing page found [here](https://solidity.readthedocs.io/en/latest/contributing.html)
2.  Click on "coding standards" which links to the following [url](https://raw.githubusercontent.com/ethereum/cpp-ethereum/develop/CodingStandards.txt)
3.  Receive 404 

## Additional details 
Broken link leads to the following url which results in a 404 

`https://solidity.readthedocs.io/en/latest/contributing.html`

## Specs 

1. Using High Sierra 10.13.2 
2. Using Safari 11.0.2  

Ideally, it should link to our coding standards documentation.  

## Ideal solution 
Page links to our coding  standards

**Comment by axic** [comment]
Seems like the `CodingStandards.txt` was removed from cpp-ethereum. @chfast was it moved or removed? As a quick fix we should push a copy of it to Solidity.

**Comment by chfast** [comment]
Just moved, and reformatted: https://github.com/ethereum/cpp-ethereum/blob/develop/CODING_STYLE.md.

But it might not be accurate for solidity.

**Comment by axic** [comment]
@chriseth do we plan to use clang-format or keep it manual? If we want to use clang-format, we should adopt the above coding style without changes, otherwise we should fork it to match Solidity.

**Comment by chriseth** [comment]
@axic we discussed that in berlin last week. clang-format sounds tempting but in the end it cannot do what humans do, so I would like to keep it as we do it now.

**Comment by chriseth** [comment]
I would also like to propose some changes to gavin's old rules.

**Comment by chriseth** [comment]
I think this is roughly where we could start off from: https://github.com/ethereum/cpp-ethereum/blob/b6dbb3549f8d50510111baf0d3088cc15284bcec/CodingStandards.txt
