### ISSUE TITLE
Doc parsing: Multiple return value support, way to dev-doc contracts

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#366]
These are some features that would be nice when generating documentation using the natspec format.

First it would be great if return-values worked like params, meaning you get an object with name -> description mappings. Right now it ends up being a single string. 

Example:

```
/// @return contractAddress the contract address.
/// @return error an error code.
function getContract(bytes32 id) constant returns (address contractAddress, uint16 error);
```

Object would be:

```
{
    "contractAddress": "the contract address",
    "error": "an error code"
}
```

Multiple return values does work, but they will only be appended after one another without a separator. In this case it would be the string:

`contractAddress the contract addresserror an error code`

Right now I solve it by adding a `|` at the end of return values if i have more then one, then split and parse them manually.

Currently you can't add a `@dev` tag to a contract. It will not end up in the `.docdev` json file under `details`, like it does in functions. That would be very nice. 

Using: `Version: 0.2.0-67c855c5/RelWithDebInfo-Linux/g++/int linked to libethereum-1.1.0-34716679/.-Linux/g++/int` (built yesterday i believe).

By the way - Might I suggest removing documentation compiler errors (unless --devdoc or --userdoc flags are used, or by adding a --ignoredoc flag or something). That way those of us who wants to produce professional looking doc pages using external tools can do that without having to break with natspec.

**Comment by androlo** [comment]
Come to think of it, a flag wouldn't really help as it would still catch the errors that unknown flags produce when building the user and devdocs. Scratch that...

**Comment by androlo** [comment]
Actually, no. Is devdoc even used in the natspec validation process in the clients?

**Comment by chriseth** [comment]
Added to https://github.com/ethereum/solidity/issues/1141
