### ISSUE TITLE
Question: Is there any simple method to add a built-in function?

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/solidity#3670]
There are some precompiled accounts in ethereum(account `0x...00001` - `0x...00008`). If we want to customize the evm precompiled accounts (e.g. add another precompiled account to support some financial computation), how can we add this built-in function to solidity?

Is the code modification necessary?

**Comment by axic** [comment]
Those accounts are part of the clients and not part of Solidity. If you want to get a new "precompiled" contract approved, the best way is to create a new EIP proposal at https://github.com/ethereum/EIPs and convince the community to support it.

**Comment by chriseth** [comment]
If you are talking about a private chain, then the best way is to use inline assembly to create a high level function for the precompiled contract. You can find an example here: https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SolidityEndToEndTest.cpp#L10543

**Comment by rjl493456442** [comment]
@chriseth Thanks!  That is what i want. Love the freedom of the solidity grammar. 
If we can expose precompiled account related function(e.g. `sha256`) easier, it can more elegant.

**Comment by axic** [comment]
> If we can expose precompiled account related function(e.g. `sha256`) easier, it can more elegant.

Can you elaborate what you mean by this?

**Comment by rjl493456442** [comment]
@axic We can invoke precompiled account by the method as chriseth said. But this call for solidity developer have high requirements, need to be completed by the bottom of the assembly instructions.

So if we can add the solidity builtin function(e.g. `ecrecover ` or `sha256`) as easy as adding a precompiled account, i think the dapp source code will be more elegant and more friendly to dapp developer.

I know this process involves lexical analysis, grammatical analysis. So it is not known whether providing a mechanism like registering a builtin function is not achievable.

**Comment by axic** [comment]
Sorry I am still a bit unsure. It should be fairly easy to write libraries which interact with new "precompiles" via assembly instructions and then only use those high level libraries, such as:

```
library FancyPrecompile {
  function doFancyStuff() internal view {
    assembly {
      staticcall(...)
    }
  }
}

contract MyContract {
  function f() public view {
    FancyPrecompile.doFancyStuff();
  }
}
```
