### ISSUE TITLE
Free variable stack slot at end of scope

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3672]
Since variables are now scoped within a block as opposed to the whole function, it makes sense to reserve their stack slot also only for the duration of that block.

This requires small modifications in the CompilerContext. Some special handling with regards to break and continue statements is probably also needed.

**Comment by leonardoalt** [comment]
Current trick case:
```
while (...) {
   uint x;
   if (...) {
      uint y;
      ...
      if (...) break; // B1
      uint z;
      ...
   }
   uint t;
   ...
}
```
B1 should free both `y` and `x`, but not `z` and `t` because those wouldn't have been reserved yet.

**Comment by chriseth** [comment]
But this should not be too big of a problem, if we keep
 - a mapping from blocks to sets of variables defined in that block (or added in that block), and
 - a set of variables defined at the current syntactic point (this could be m_localVariables in CompilerContext)

and then m_breakTags and m_continueTags in ContractCompiler need to be extended to point at the syntatic structures instead of just assembly tags. Using that, we can calculate the difference and then also have cross-checks by counting the number of variables and the current stack height.

**Comment by leonardoalt** [comment]
That's very similar to what I have right now in `ContractCompiler`:
- A mapping from blocks to sets of variables declared in that block, such that they're freed in `endVisit(Block const&)`, which takes care of the general case.
- A mapping from loops to sets of variables declared inside the loop up to the analyzed syntactic point. At `B1`, for example, the `while` would be pointing to `x` and `y`. The break tag then points to a piece of code that frees those variables only.

**Comment by loredanacirstea** [comment]
I assume this will also affect `modifiers`? 

E.g. If I want to move `require(channel_identifier > 0);` from the function code to a modifier, like this:
```
modifier validChannelIdentifier(uint256 channel_identifier) {
        require(channel_identifier > 0);
        _;
    }
```
I get into the `stack too deep` error. So, as far as I see, the reason is `channel_identifier` being added to the `stack` multiple times and not being removed after the modifier's scope is finished.

**Comment by axic** [comment]
Please see #3060.

**Comment by chriseth** [comment]
@loredanacirstea the problem is that the scope of `channel_identifier` extends beyond the part after `_`, so it's slot cannot be really deleted. Of course there could be an optimization pass that detects that it is not really used anymore, but that's a different story.
