### ISSUE TITLE
Compiler crashes on a specific set of contracts

### ISSUE THREAD

**Issue by maraoz** [ethereum/solidity#3676]
Steps to reproduce:

1. Clone this repo, branch `factory`: https://github.com/maraoz/core/tree/factory/contracts
2. Install latest solidity: `npm i -g solc`
3. Compile the contracts: `solcjs --bin contracts/*.sol contracts/Factory.sol contracts/upgradeability/*`

Expected output: some high level error or more human-readable output.
Actual output: 
```
Exception during compilation: /root/project/libevmasm/Assembly.h(92): Throw in function void dev::eth::Assembly::adjustDeposit(int)
Dynamic exception type: N5boost16exception_detail10clone_implIN3dev8solidity14InvalidDepositEEE
std::exception::what: InvalidDeposit
[PN3dev11tag_commentE] = 

```

**Comment by axic** [comment]
@maraoz can you pin point at least the file? That would help in finding the reason.

**Comment by maraoz** [comment]
@axic what do you mean pin point the file? I'm not sure which contract is making the compiler crash. I was working on the `Factory.sol` contract when this started happening, but not entirely sure if that's the source of error.
The commands to reproduce the error are specified above. (i.e: `solcjs --bin contracts/*.sol contracts/Factory.sol contracts/upgradeability/*`)

**Comment by maraoz** [comment]
FWIW, `solcjs --bin contracts/*.sol contracts/upgradeability/*` also fails with the same error

**Comment by axic** [comment]
Well I guess we could add a debug line to see which contract it happens in.

**Comment by axic** [comment]
Tried compiling it and it works here with `solc` on latest `develop`. Can you try a nightly release from yesterday?

**Comment by axic** [comment]
It compiles for me with `solc` from 0.4.20. Haven't tried `solcjs`.

**Comment by maraoz** [comment]
I'm having problems installing/running the v0.4.20 `solc` release. I'll report back when I sort it out.

FWIW, this commit fixes the crash for me: 
https://github.com/maraoz/core/commit/5168b51a2f6ae3467bbee9fa44454757b705cb5b

**Comment by chriseth** [comment]
@maraoz any news on this?

**Comment by chriseth** [comment]
Please reopen if this is reproducible.
