### ISSUE TITLE
Should default to external visibility for interfaces

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3682]
```
:4:4: Warning: No visibility specified. Defaulting to "public".
			function f();
			^-----------^
:4:4: Warning: Functions in interfaces should be declared external.
			function f();
			^-----------^
```

**Comment by chriseth** [comment]
Since the function's scope is only set after the NameAndTypeResolution phase, its default visibility is only known at that point. While that is still before the TypeChecker needs the visibility, it might no be worth the hassle and thus we could just keep it like that.

**Comment by beether** [comment]
@chriseth 

Is there not a use case for defining, in an interface, that a `public view` should exist?

I get compiler warnings when doing this.
