### ISSUE TITLE
Confusing examples of types used for binary operators

### ISSUE THREAD

**Issue by limexp** [ethereum/solidity#3689]
After operations the compiler implicitly performs type conversions which could lead to information lost.

If I sum two uint8 variables the result will be implicitly converted to uint8 despite the required result type.

Take a look at the [following contract](https://rinkeby.etherscan.io/address/0x6034913e5aed454efddcdefc82ed8148e75ba2c3):

```
pragma solidity ^0.4.16;

contract lim {
    function add1(uint8 a, uint8 b) public pure returns (uint ret) {
        return a + b;
    }
    
    function add2(uint8 a, uint8 b) public pure returns (uint ret) {
        uint c = a + b;
        return c;
    }
    
    function add3(uint8 a, uint8 b) public pure returns (uint ret) {
        if (300 < a + b) return 1000;
        uint c = 300;
        if (c < a + b) return 2000;
        return a + b;
    }
  
    function exp1(uint8 a, uint8 b) public pure returns (uint ret) {
        return a ** b;
    }
}
```

Try to execute exp1(10, 3) or addN(200, 200). 

Result will be "wrong" since after ADD and EXP instructions there are AND instructions: "ADD **PUSH1 0xFF AND**", "EXP **PUSH1 0xFF AND**". So the real result is always implicitly converted to narrower type without any warning. 

I think that such conversions are not obvious and could lead to errors. Unfortunately the [documentation](http://solidity.readthedocs.io/en/latest/types.html#implicit-conversions) also could lead to misunderstanding: "If an operator is applied to different types, the compiler tries to implicitly convert one of the operands to the type of the other (the same is true for assignments). **In general, an implicit conversion between value-types is possible if it makes sense semantically and no information is lost**".

**Comment by chriseth** [comment]
The documentation could be more specific by changing it to:


If an operator is applied to different types, the compiler tries to implicitly convert one of the operands to the type of the other (the same is true for assignments). **This means that operations are always performed in the type of one of the operands.** In general, an implicit conversion between value-types is possible if it makes sense semantically and no information is lost".

Would that help?

**Comment by chriseth** [comment]
Note that the paragraph says "an implicit conversion is possible" and not "is performed".

**Comment by limexp** [comment]
As I understand a bottom up approach is used now for types determination. The ideal solution could be the opposite one - taking the result type and convert all the expression to it. 

Documentation changes could help a little. But I am afraid that most smart contract developers will never notice this compiler behaviour before they run into the problem.

Here is [another contract](https://rinkeby.etherscan.io/address/0x9c4b763433354add099039c3b9454dac58a6fac5#readContract) example where associative property is broken for addition.
```
pragma solidity ^0.4.16;

contract lim {
    function add4() public pure returns (uint ret) {
        uint8 a = 100;
        uint8 b = 200;
        uint16 c = 300;
        return a + b + c;
    }
    
    function add5() public pure returns (uint ret) {
        uint8 a = 100;
        uint8 b = 200;
        uint16 c = 300;
        return a + c + b;
    }
    
    function add6() public pure returns (uint ret) {
        uint8 a = 100;
        uint8 b = 200;
        return 300 + a + b;
    }
    
    function add7() public pure returns (uint ret) {
        uint8 a = 100;
        uint8 b = 200;
        return a + b + 300;
    }
    
    function exp2() public pure returns (uint ret) {
        uint8 b = 3;
        return 10 ** b;
  
    }
    
    function exp3() public pure returns (uint ret) {
        uint8 a = 10;
        uint8 b = 3;
        return a ** b;
    }
}
```

While function exp2 and exp3 are similar there is a warning only for the first one:

> Warning: Result of exponentiation has type uint8 and thus might overflow. Silence this warning by converting the literal to the expected type.

**Comment by chriseth** [comment]
Indeed, the current approach is that the type of an expression or the resulting type of an operation can be determined by looking at the types of the operands only.

**Comment by chriseth** [comment]
In practice, though, I would say that people do not often use arithmetic types that are not 256 bits wide.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
