### ISSUE TITLE
0.4.21 update breaks go-ethereum makeArgs function: "unrecognized option --add-std"

### ISSUE THREAD

**Issue by jeffwalsh** [ethereum/solidity#3695]
Hi. I install solc in Travis CI through the ppa and noticed my build was broken today. I updated solc locally and now find updating solc is the issue.

```
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install -y solc
```

Trying to use the go-ethereum Solidity compiler results in this error now:

```
solc: exit status 1
		unrecognised option '--add-std'
```

Which comes from the `Solidity.makeArgs()` function in `github.com/ethereum/go-ethereum/common/compiler`, which is used by my app indirectly via `compiler.CompileSolidityString("", solidityString)`. 
Not sure if an `--add-std` option was removed with the patch yesterday or if I've done something wrong here.

**Comment by axic** [comment]
This actually was removed in 5ab4a1ae7819004415293bf72a86824beb43cd51, @chriseth we should have mentioned it in the changelog.

The actual feature was removed probably 15 releases ago, just the option was left for "backwards compatibility", but it didn't actually do anything.

@karalabe @holiman can that option be removed from go-ethereum?

**Comment by jeffwalsh** [comment]
fixed in go-ethereum, leave issue open until they fix in others (ie: EthWorks/ethereum.rb) ?

**Comment by quantumproducer** [comment]
How did you install 0.4.21? I updated truffle and it's still on 4.19

**Comment by LefterisJP** [comment]
Same issue with pyethereum. We had this option in there always on and just noticed it went missing through Raiden.

Please add it to the changelog so that it's easier to spot when choosing to upgrade.

**Comment by jeffwalsh** [comment]
@quantumproducer I installed directly through apt on Ubuntu by adding the ethereum/ethereum PPA.

**Comment by xsslong** [comment]
Same issue when I was using abigen, 
`abigen --sol token.sol --pkg token --lang go --out token.go`
Trying to bind solidity with abigen command,  results in this error:
```
Failed to build Solidity contract: solc: exit status 1
unrecognised option '--add-std'
```
I find use func in go-ethereum "compiler.CompileSolidity(*solcFlag, *solFlag),"  it's a solc command operation.
```
--combined-json
bin,abi,userdoc,devdoc,metadata
--add-std
--optimize
--
token.sol
```
but"--add-std" arg, deprecated in solidity 0.4.21
fixed in go-ethereum , please
![image](https://user-images.githubusercontent.com/16704850/38601187-49530606-3d99-11e8-99e0-87dcc6aeb535.png)

**Comment by karalabe** [comment]
The flag removal was shipped in Geth 1.8.3 two weeks ago.

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/commit/a25561dfb47fd2b9ee2dc4e1333508a1742e2562

**Comment by Night-mk** [comment]
I have the same issue when using abigen:
`abigen -sol inbox.sol -pkg contracts -out inbox.go`
I got the same error as:
`Failed to build Solidity contract: solc: exit status 1
unrecognised option '--add-std'
`
my geth version is `1.8.15-stable` , and solc version is `0.4.24+commit.e67f0147.Linux.g++`
how can I fix it?

**Comment by leonardoalt** [comment]
@Night-mk As pointed in https://github.com/ethereum/solidity/issues/3695#issuecomment-380361834, Geth already had a fix. Could you please try it with updated Geth and Solidity?

**Comment by axic** [comment]
I've checked the geth 1.8.15 source and it doesn't seem to have `--add-std` in it. Closing. Please reopen if the issue persists, could also check geth 1.8.18.
