### ISSUE TITLE
Not accurate

### ISSUE THREAD

**Issue by PeterT11** [ethereum/solidity#3701]
Source:[https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst#fallback-function](https://github.com/ethereum/solidity/blob/develop/docs/contracts.rst#fallback-function)
_Contract.rc: In such a context, there is usually very little gas available to the function call (to be precise, 2300 gas), so it is important to make fallback functions as cheap as possible._

I think here is confusing. 2300 gas only applied when this fall back is called from a message call. you can actually specify gas limit if you can a fallback function by a transaction call.

**Comment by chriseth** [comment]
Thanks for your suggestion! We have changed the wording in the meantime. If you still think there is room for improvement, please either re-open the issue or create a pull request right away.
