### ISSUE TITLE
Allow functions with the name matching the contract (0.6.0)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3705]
Follow up of #3196.

With the introduction of the `constructor` keyword we are deprecating functions named the same as the contract. They will be rejected in 0.5.0.

After a while when the ecosystem has moved on, we could consider removing that extra corner case rejecting special function names (such as the one matching the contract name).

**Comment by chriseth** [comment]
Since compiling old code with a new compiler would not generate a warning but severely changes the semantics with security holes in practically any such contract, I would strongly advise against allowing that even in 5 years time.

**Comment by axic** [comment]
When this issue was created, the following code was handled by a special case in the compiler:
```solidity
contract C {
  function C() external {}
}
```

Since around 0.6.0 when shadowing rules were strengthened/introduced, we get the following:
```solidity
Error: Functions are not allowed to have the same name as the contract. If you intend this to be a constructor, use "constructor(...) { ... }" to define it.
 --> 3705.sol:2:3:
  |
2 |   function C() external {}
  |   ^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Source file does not specify required compiler version!
--> 3705.sol

Warning: This declaration shadows an existing declaration.
 --> 3705.sol:2:3:
  |
2 |   function C() external {}
  |   ^^^^^^^^^^^^^^^^^^^^^^^^
Note: The shadowed declaration is here:
 --> 3705.sol:1:1:
  |
1 | contract C {
  | ^ (Relevant source part starts here and spans across multiple lines).
```

I would argue we do not need the special case anymore, and we can just rely on the shadowing warning.
