### ISSUE TITLE
SMT: Check that short-circuiting is implemented correctly.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3711]

**Comment by leonardoalt** [comment]
I tried the code you wrote in the PR
> `bool x = false; if (true || (x = true)) {}; assert(!x);`

and the solver does set `x` to `true`:
```
short.sol:8:5: Warning: Assertion violation happens here for:
  x = true
```
So we do need to fix the code if we want the second argument to depend on the first one failing.
