### ISSUE TITLE
Ability to make HTTP requests w/ cached response for future replayability in the blockchain

### ISSUE THREAD

**Issue by ted-hanson** [ethereum/solidity#3715]
Just want to get thoughts on the idea and bring up some discussion.

**Comment by chriseth** [comment]
Sorry, but I don't really understand. How does Solidity relate to HTTP? Is this the right repository for this issue?

**Comment by ted-hanson** [comment]
Should this be more directed toward the EVM? I can see a lot of value saving the state of an HTTP request in an Ethereum block and using the values in some way to calculate something.

**Comment by chriseth** [comment]
The abstracted Ethereum Virtual Machine cannot initiate or even sustain HTTP requests. Please open a question at https://ethereum.stackexchange.com and perhaps read https://ethereum.stackexchange.com/questions/2/how-can-an-ethereum-contract-get-data-from-a-website

If you are serious with such changes, you should consider opening an EIP at https://github.com/ethereum/EIPs.

The Solidity repository is certainly too high-level for such things.

**Comment by ted-hanson** [comment]
perfect thanks
