### ISSUE TITLE
Update version pragmas in documentation for constructors.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#3717]
Update >0.4.21 to ^0.4.22 in doc/contracts.rst (lines 43 and 986), as well as in std/StandardToken.sol and std/owned.sol.

Only applicable if #3635 is merged.

**Comment by ekpyron** [comment]
Necessary changes are on branch ``updateConstructorVersionPragmas`` - I was not sure about creating a pull request, since this has to be merged simultanously with the 0.4.22 release.

**Comment by axic** [comment]
@ekpyron do you want to create the PR off that branch?

**Comment by ekpyron** [comment]
Do we have a convention for dealing with, resp. naming PRs in such cases?

**Comment by ekpyron** [comment]
I'm not sure about the release process so far, so I wasn't sure whether this should be a PR at all or whether the branch would just be merged into the release PR...
