### ISSUE TITLE
Invalid file given for syntax tests

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3723]
The syntax tests create the following report:
```
- name: syntaxTests/double_variable_declaration_050
- description: ''
- file: �U����U@0����U
- line: 0
```

This looks like an invalid pointer to what is supposed to contain the file name.

**Comment by ekpyron** [comment]
Where does this happen?

**Comment by chriseth** [comment]
The quote above is from a file generated via `--logger=JUNIT,test_suite,report.xml` (this is automatically done on circle).

**Comment by ekpyron** [comment]
OK, I can reproduce now (``soltest -t syntax* -l all -- -- testpath ./test``).
