### ISSUE TITLE
This looks like an address but has an invalid checksum. If this is not used as an address, please prepend '00'.

### ISSUE THREAD

**Issue by minhtrih** [ethereum/solidity#3733]
I use Mist, Rinkeby testnet to deploy my code
I have a problem with address _to
Should and How I code to check address ?

`pragma solidity ^0.4.15;

contract WithdrawalFunds {
    //account.value = account.value - amount
    //otherAcc += total
    address public mainAcc;
    uint public etherAcc = 0;
    
    address Address = 0x9dae7bf014e83fdb2fd11a3ed99e775f58b256d9;
    
    //check account
    modifier checkAcc() {
        require (msg.sender == mainAcc);
        _;
    }
    
    modifier checkAddress() {
        require(msg.sender != Address);
        _;
    }
    
    // Allowed withdrawals of previous bids
    mapping (address => uint) pendingWithdraws;
    
    function WithdrawalFunds() public payable {
        mainAcc = msg.sender;
        etherAcc = msg.value;
        
    }
    
    //withdrawal start
    function withdraw() public checkAcc checkAddress {
        if(etherAcc > 0){
            msg.sender.transfer(etherAcc);
        }
    }
    
}`

**Comment by axic** [comment]
Please follow the compiler instructions, add a proper checksum to `0x9dae7bf014e83fdb2fd11a3ed99e775f58b256d9`.
