### ISSUE TITLE
Function overload clash when using the extern keyword

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#3755]
I noticed that when using solidity versions  0.4.20 and  0.4.21 that I get a name clash error when I try to compile an interface that has this code in it: 
```
function safeTransferFrom(address _from, address _to, uint256 _tokenId) external; 
function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes _data) external;
```
This is the error I get:
> TypeError: Function overload clash during conversion to external types for arguments.

But this code should work, but it does not.  It does work if I change the keyword external to public.
The code is from the ERC721 standard.

I am using the compiler in remix.

https://github.com/ethereum/solidity/pull/3699
https://github.com/ethereum/solidity/pull/3729

**Comment by mudgen** [comment]
Nevermind, it was a bug in my code.

**Comment by rkbansal** [comment]
@mudgen what was your bug in the code, as I am also getting the same issue?

**Comment by hilobrain** [comment]
got the same
