### ISSUE TITLE
Constant folding with arbitrary precision arithmetic?

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#3759]
contract c {
function f() returns (int) {
return 4 ** 4 ** 2 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 * 2;

}

Causes the compiler to hang (surprisingly, not exceed memory limit) for hours.  Not sure a "bug," but worth reporting as sub-optimal.

**Comment by agroce** [comment]
(same TSTL effort)

**Comment by chriseth** [comment]
I think we detect that in the case of a single exponentiation, but not with multiple.

**Comment by agroce** [comment]
This form also sends the compiler into a hang:

```
contract c {
function f() public payable returns (int) {
for (10 / 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10; 8 <= (10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10) ** 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8; (10) * (10) * 8)
for (10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8 * 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8 ** (10); 8 > (10); (10) * (10) * 8 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8)
for (10 >> (10) >> (10) ** 10 >> (10) >> (10); 10 <= 10 >> (10) >> (10) ** 10 >> (10) >> (10); 8)
return (8);




}

}
```

Same underlying problem, but different enough might be useful for fixing the detection.

**Comment by chriseth** [comment]
@bit-shift please also add a test for the one above.

**Comment by erak** [comment]
@chriseth Please have a look :) https://github.com/ethereum/solidity/pull/3793

**Comment by erak** [comment]
Should we close this as duplicate of #3327? Slightly different scenario but both will be fixed with the same pull request.

**Comment by chriseth** [comment]
If the pull request fixes both, then just add a "fixes" entry to the description of the pull request.
