### ISSUE TITLE
Solc --optimize produces a function which consumes higher gas?

### ISSUE THREAD

**Issue by njaliu** [ethereum/solidity#3760]
`    

    address public constant minter1 = 0x884FFccB29d5aba8c94509663595F1dBF823dCC9;

    address public constant minter2 = 0x5aCC33B4318575581a80522B2e57D1d09e5eC111;

    function checkMinter() {
      require(msg.sender == minter1 || msg.sender == minter2);
    }
`

Regarding the code above, I compiled it using `solc --gas` with and without `--optimize` respectively.
The output indicates that with `--optimize`, the funciton `checkMinter` is estimated to consume 214 gas while without `--optimize` the gas consumption is 88.

Is `solc` supposed to optimize the gas consumption or not? Or this is something linked to a bug? 
The entire source file is attached. Thanks!

[test.zip](https://github.com/ethereum/solidity/files/1822441/test.zip)

**Comment by chriseth** [comment]
Especially with regards to constants, the optimizer has to decide on a trade-off: There are multiple ways to represent constants which produce different costs for storing the code (i.e. at deploy time) and for running the code (i.e. at runtime). Could you also compare the costs for the constructor in both version? The trade-off factor can be adjusted with the `--optimize-runs` switch.

**Comment by njaliu** [comment]
@chriseth Thanks for the explanation. I tried the `--optimize-runs n` with n=1,15,150,200,10000000, and the gas estimation becomes the same as the non-optimized code (i.e., 88). Is solc expected to generate such a compilation? Or can I say for this code, non-optimized contract is better "optimized"?

**Comment by njaliu** [comment]
@chriseth Thanks for the explanation! I tried tuning via the `--optimize-runs`. With n=1, 10, 100, 1000, the gas is still 214 (same as `--optimize`). However, when n=20000, the gas becomes 76. But still, in case of small values of n, non-optimized outperforms optimized, 88 vs 214.

**Comment by chriseth** [comment]
@njaliu as I said, the word "outperforms" is only valid if you also take a look at the deployment costs.
