### ISSUE TITLE
Document 0.5.0 features

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3761]
Create a section in the documentation explaining changes introduced by 0.5.0.

Most of these need to be found based on:
- https://github.com/ethereum/solidity/issues/2511#issuecomment-361469013
- changelog
- source code and/or git commit history :)

**Comment by aj07** [comment]
Should we make a new section just below in the name of " v.0.5.0 features"  and put the #2511 (comment) and changelog ?

**Comment by axic** [comment]
Below what exactly? Please make a simple PR with your proposed location in the documentation and we can discuss it from there.

**Comment by aj07** [comment]
Please, review https://github.com/ethereum/solidity/pull/4257
