### ISSUE TITLE
Re-enable dead code removal

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3766]
Unused code removal was disabled because code can be jumped to from inline assembly and internal functions can be referenced from constructors, stored in storage and then jumped to after deployment.

This means that removing code blocks whose labels are unreferenced may lead to invalid code.

Once we fully disabled the use of the `jump` opcode in inline assembly, and we changed the way internal function identifiers are handled (we need to do that for the switch to wasm anyway), we can re-enable dead code removal.

TODO:

 - [ ] introduce identifiers for functions that are not based on they entry label (and introduce dispatch routine)
 - [x] check that the `jump` opcode is disabled in inline assembly
 - [ ] re-enable dead code removal

**Comment by federicobond** [comment]
Why not throw an error on dead code instead of silently removing it?

**Comment by chriseth** [comment]
This is about dead EVM code, not dead Solidity code.

**Comment by axic** [comment]
> Once we fully disabled the use of the jump opcode in inline assembly, and we changed the way internal function identifiers are handled (we need to do that for the switch to wasm anyway), we can re-enable dead code removal.

We did this with 0.6.0.

@chriseth Time to reconsider?

**Comment by chriseth** [comment]
We only did the change for the sol->yul codegen, and that optimizer already has its own dead code removal, so maybe this can be closed.
