### ISSUE TITLE
Always use returndatacopy if supported

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3767]
After #3308 we'll have four different cases for external calls and their return values:
1) static length expected (<byzantium): doesn't use `returndatacopy`, calculates the expected length, `call` allocates the memory
2) static length expected (>=byzantium): doesn't use `returndatacopy`, calculates expected length, `call` allocates the memory, **but** the return length is restricted for the ABI decoder
3) dynamic length expected (<byzantium): doesn't use `returndatacopy`, calculates the expected length, `call` allocates the memory and dynamic types are skipped (*)
4) dynamic length expected (>=byzantium): uses `returndatacopy`, doesn't calculate expected length, `call` doesn't allocate memory and length equals to that of `returndatasize`

It would be nice to simplify this behaviour to less cases and more predictability for the user. As a bare minimum we should document this.

If we decide to use `returndatacopy` in every case (>=byzantium) that means a `call` may succeed, but `returndatacopy` may fail if extending the memory results in OOG.

(*) Skipping here means that their pointer is just skipped. If a dynamic type is the last ABI item, very likely the decoder will not reach a point of checking the actual data boundaries and therefore would accept a short input.

**Comment by chriseth** [comment]
Since `returndatacopy` has a cost, I would actually prefer to use it only if dynamic data is expected. We could "simplify" case 2 to "don't use `returndatacopy`, calculated the expected length and check that the real length is at least as long" (I actually thought #3308 is implemented that way).

**Comment by juanfranblanco** [comment]
I am trying to have the capability of "querying" the chain, with many calls at once.  The idea is to stop it to be so chatty across the wire and reduce latency. So in that scenario, it is simpler not to know the size of the return in advance (well at least for the smart contract).

**Comment by chriseth** [comment]
I would propose to close this. The current behaviour is: Use returndatacopy if dynamic data is to be expected and returndatacopy is available in the EVM. I don't think that is a very complex behaviour.

**Comment by chriseth** [comment]
Please reopen if you would like modifications to the current behaviour.
