### ISSUE TITLE
2 SSTORE instead of 1 when assigning as a struct

### ISSUE THREAD

**Issue by gakonst** [ethereum/solidity#3768]
```
pragma solidity ^0.4.21;
contract Test {
    struct A { 
        uint128 x;
        uint128 y;
    }
    A a;
    function x() public {
        // a.x = 1;
        // a.y= 2;
        a = A(1,2); 
    }
}
```

In the above example, assigning `A(1,2)` to `a` requires 2 sstore operations,.
Assigning via `a.x` and `a.y` instead packs the values as expected and requires 1 sstore only.
I'm checking via: `solc --optimize --asm Test.sol | grep sstore | wc -l`
I've noticed the [documentation](https://solidity.readthedocs.io/en/latest/miscellaneous.html#internals-the-optimizer)  talks about this, but why does this happen?

Solc Version: 0.4.22-develop.2018.3.16+commit.2b2527f3.Linux.g++
Ubuntu 17.04

**Comment by chriseth** [comment]
Might be already fixed in a pending PR. Assigning to the current project to re-check.

**Comment by chriseth** [comment]
Confirmed fixed.
