### ISSUE TITLE
Consider adding calldataEncodedSize/isDynamicallyEncoded to TupleType

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3769]
This would simplify the code in `ExpressionCompiler` added by #3308.

**Comment by axic** [comment]
@chriseth Hmm, is this still relevant?

**Comment by cameel** [comment]
I'm not sure if it's still relevant but I wanted to add that this is probably much simpler now than it was back then. `TupleType` and `ReferenceType` both inherit from `CompositeType` (#9746) so we could just move the pure virtual declarations of these functions there.
