### ISSUE TITLE
Modifier that uses `msg.value` should generate a warning if used in non-payable function

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3770]
This should generate a warning:

```
contract C {
  modifier costs(uint _amount) { require(msg.value >= _amount); _ }
  function f() costs(1 ether) public {}
}
```

**Comment by chriseth** [comment]
Discovered in https://github.com/ethereum/solidity/pull/3763

**Comment by axic** [comment]
Perhaps we need to add new test cases within modifiers for every single statement covered by `ViewPureChecker`.
