### ISSUE TITLE
CompilerStack::analyze(): SMTChecker/z3: global shared state prevents multi-threaded usage

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#3777]
Due to the usage of an allocator that seem to be managed through global shared state within the `z3` library a multi-threaded usage of multiple `CompilerStack` instances is prevented (if they call  `CompilerStack::analyze()`). 

So basically I do this:
```
thread1 {
  CompilerStack compiler;
  compiler.addSource(...);
  compiler.parseAndAnalyze();
}
thread2 {
  CompilerStack compiler;
  compiler.addSource(...);
  compiler.parseAndAnalyze();
}
```
![screen shot 2018-03-24 at 00 13 13](https://user-images.githubusercontent.com/5008794/37857335-820584a4-2efa-11e8-9b9e-5377f3047993.png)

As far as I know `Solidity` is currently single-threaded, but I guess that it could make sense to somehow support multi-threading, especially if third-party applications are just using `Solidity` libraries. It may also make sense to add multi-threading support to the `Solidity` compiler in the future.

However, the described issue can be easily solved by protecting the initialisation with a mutex (see `libsolidity/interface/CompilerStack.cpp`):
```cpp
bool CompilerStack::analyze()
{
...
	if (noErrors)
	{
		static boost::mutex mutex;
		boost::mutex::scoped_lock lock(mutex);

		SMTChecker smtChecker(m_errorReporter, m_smtQuery);
		lock.unlock();
		for (Source const* source: m_sourceOrder)
			smtChecker.analyze(*source->ast);
	}
...
}
```

Of course it is also possible to just create a `mutex` around `CompilerStack::parseAndAnalyze` or `CompilerStack::analyze` within third-party applications/libraries, but this may have a bigger impact on the performance.

Probably the `z3` library api's support better ways to solve this issue - e.g. not to use that allocator.

**Comment by axic** [comment]
Good catch! Can you ask around on https://github.com/Z3Prover/z3 ?

cc @leonardoalt

**Comment by chriseth** [comment]
Solidity was never designed to be used in a multi-threaded setting. You will find other places where this will go wrong. I *really* want to avoid using manual mutexes. Also, you have to ensure that the compiler is still deterministic, which could be a challenge to test.

**Comment by aarlt** [comment]
Yep, I know that Solidity is not designed to run in a multi-threaded environment. I would also avoid the introduction of these manual mutexes. But if there is a way to prevent the usage of that global shared state within `z3` - e.g. by using different API's - we should change it from my point of view. 

If I find some time, I will look into `z3`.

**Comment by aarlt** [comment]
Hmm.. looks like that the easiest solution could be to move the instantiation of the `SMTChecker` from `bool CompilerStack::analyze()` into the the constructor of `CompilerStack`. Within `bool CompilerStack::analyze()` we should then just call `m_smtChecker.analyze(*source->ast);`. Doing so, the `context` for `z3` was already constructed. If every thread using it's own `z3_context`, `Z3` should behave nicely within multi-threading setup's.

However with that we basically just moving the problem to the constructor. But from my point of the "sequential" construction of `CompilerStack` instances within a multi-threaded setup is totally ok. It would be just nice to be able to use `parseAndAnalyze()` from different threads - because some real work is done here. 

@chriseth if you are aware of things that will definitely become a show stopper for the multi-threaded usage within third-party applications, I would really appreciate any hint.

**Comment by aarlt** [comment]
hmm.. i just realized that the `jsoncpp` usage in `libdevcore/JSON.cpp` may become a problem.. 
e.g.
```cpp
string jsonPrettyPrint(Json::Value const& _input)
{
	static map<string, string> settings{{"indentation", "  "}};
	static StreamWriterBuilder writerBuilder(settings);
	return print(_input, writerBuilder);
}
```
I will probably find it out quite soon.. I will let you know..

**Comment by chriseth** [comment]
I specifically did not pay attention to problems that might arise in a multi-threaded context, because Solidity was explicitly designed to be single-threaded.

**Comment by aarlt** [comment]
@chriseth thank you for your feedback! i just decided to do the multi-threaded usage of Solidity libraries optional. I guess there will be no big performance benefit in the average case - but only headaches - if my code just rely on pure multi-threading usage. I will mark that feature as highly experimental :) So thanks again :)

**Comment by aarlt** [comment]
@chriseth @axic From my point of view this issue can be closed.
