### ISSUE TITLE
Gas estimates infinite

### ISSUE THREAD

**Issue by denisglotov** [ethereum/solidity#3779]
The compilation of the following contract results that the gas estimate of all 3 functions is infinite.
```
pragma solidity ^0.4.19;

contract Test {
    uint256 public constant unused = 12345;
    address public owner;

    function () public payable {
        owner.transfer(msg.value);
    }
}
```
**Note**, that commenting out the last line solves the problem and all estimates become finite.

Solc version 
-------------
0.4.19+commit.c4cbbb05.Linux.g++,
0.4.21+commit.dfe3193c.Emscripten.clang.

Reproduce steps
------------------
Use Remix, copy the above contract code there, see 3 yellow warnings ("Gas requirement of function Test.unused() high: infinite").

Or run `solc test.sol --gas` with 'test.sol' being the code from above. See that
```
======= test.sol:Test =======
Gas estimation:
construction:
   124 + 77600 = 77724
external:
   fallback:    infinite
   owner():     infinite
   unused():    infinite
```

**Comment by DanielRX** [comment]
Just to add, this seems to be an issue of a view function being allowed (assumed allowed) to call a state changing function (the fallback). So the gas estimate is wrongly added the fallback function to the gas cost.

**Comment by OTTTO** [comment]
@DanielRX, the view modifier is to be enforced as of 0.5.0.  so, that should hopefully fix the issue.

**Comment by DanielRX** [comment]
@OTTTO Yeah, I wasn't sure when it was, does the fallback function get included in that, as it already shows a warning on a view calling an non-view, but not for the fallback?
