### ISSUE TITLE
Define rules for writing custom getters for public functions

### ISSUE THREAD

**Issue by chaoliu92** [ethereum/solidity#3780]
As I understand, every **public state variable** will have a corresponding **external getter function** with the same name (but can have necessary input parameters for some cases). 

My question is what if I have a function _with the same signature_ (function name and input parameter types) as this auto-generated getter function?

I've experimented with the following simple contract in Remix, and I found the explicitly defined function (here `number()`) seems to **shadow** the auto-generated getter function.

```solidity
pragma solidity ^0.4.21;

contract TestFunctionStateVariableNameConflict {
    event log(uint256 number);
    uint256 public number = 111;
    function number() public pure returns(uint256) {
        return 222;
    }
    function print() public {
        emit log(number);  // This will output value 111 (as the state variable)
        emit log(this.number());  // This will output value 222 (as the function number())
    }
}
```

Here I found the log output of function `print()` are 111 and 222. If I change the signature of function `number()` (e.g., add an unused input parameter `bool unusend`), the result will be both 111 as I expected, since the getter and explicitly defined function now have different signatures.

What's more, if I move the declaration of `uint256 number` to the end of the contract body (so it is after the declaration of `function number()`), I will be given a TypeError for `emit log(number)` and a DeclarationError for `emit log(this.number());`. It seems when dealing with `emit log(number);`, Solidity thinks here `number` is a function and so give a TypeError; and when seen `uint256 public number = 111;`, it thinks there's already an attribute named `number` (the function) and so give a DeclarationError.

```solidity
pragma solidity ^0.4.21;

contract TestFunctionStateVariableNameConflict {
    event log(uint256 number);
    // uint256 public number = 111;
    function number() public pure returns(uint256) {
        return 222;
    }
    function print() public {
        emit log(number);  // This will lead to a TypeError
        emit log(this.number());
    }
    uint256 public number = 111;  // This will lead to a DeclarationError
}
```

So, my question is: should there be constraints between state variable names and function names in Solidity, especially when public state variables have their auto-generated getter functions? If so, what is the precise rule and where can I find it in any documentation.

**Comment by VoR0220** [comment]
This is to reduce costs. Basically any time there is a public state variable made available, it automatically generates a public gitter. Someone feel free to close this as already answered in the docs?

**Comment by chriseth** [comment]
We are currently working on a proper inheritance and shadowing specification: #3698

**Comment by chriseth** [comment]
Sorry, the correct issue is https://github.com/ethereum/solidity/pull/3729
