### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3784]
We had several discussions in the past about improving the documentation. This list below is the outline of tasks to be done.

In order of importance:
- Close off all the issues labeled `documentation` (https://github.com/ethereum/solidity/labels/documentation)
- ~Merge the FAQ into the main documentation (#1219)~
- Add an introductory section for deploying and interacting with smart contracts in Remix
- Give a brief introduction to types and globals the Introduction section (and link to the more
comprehensive Types chapter)
- Include more real-world examples of smart contracts in a tutorial-esque step-by-step format.
Create snippets that build up from small contracts to more complex contracts.
- Document best practices for writing smart contracts using Solidity. Try to merge the documentation with https://github.com/ConsenSys/smart-contract-best-practices
- Document common security pitfalls and how to mitigate them
- Document methodologies for testing smart contracts (consider different frameworks)

**Comment by onggunhao** [comment]
For Point 5 (_Include more real-world examples of smart contracts in a tutorial-esque step-by-step format. Create snippets that build up from small contracts to more complex contracts_)

Could we explore using Twilio's step-by-step tutorial framework? It's pretty nice and seems to be licensed under MIT.

Demo of Twilio tutorial:
https://www.twilio.com/docs/tutorials/account-verification-node-express

Framework (under MIT license): 
https://github.com/TwilioDevEd/account-verification-node/tree/gh-pages

**Comment by ChrisChinchilla** [comment]
I am making good progress through 1 and 2, then I'll get stuck into the rest.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
