### ISSUE TITLE
Disallow conversion between bytesX and uintX of different sizes

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3786]
Conversions between bytes and integer types always confuse people. It is rather straightforward to convert between bytes and uint types of the same size (nothing happens on the high-level side, alignment change on the low-level side). Size-changes inside the same type are also not too difficult (bytesXX is left-aligned, i.e. padding or cutting on the right, uintXX is right-aligned, i.e. padding or cutting on the left).

If both happens at the same time, users basically have to guess what happens first. If we just disallow such conversions, users have to explicitly state the order:

```
uint16 x = 0xffff;
bytes32(uint256(x)); // pad on the left
bytes32(bytes2(x)); // pad on the right
```

Inspiration: https://twitter.com/LefterisJP/status/977515366900555776

**Comment by ekpyron** [comment]
Depending on the solution of #3879 and whether it is extended to ``isExplicitlyConvertible`` as well, it may be possible to implement this in a backwards-compatible way. Otherwise it would be much easier to implement this as breaking change.

**Comment by chriseth** [comment]
This has been fixed. Literals are tracked in https://github.com/ethereum/solidity/issues/3942
