### ISSUE TITLE
Consider using Cable

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3787]
See: https://github.com/ethereum/cable

A lot of the shared CMake file could be pulled from there.

**Comment by axic** [comment]
@chfast @chriseth what do you think?

**Comment by chriseth** [comment]
At the moment, this repository is rather self-contained, which allows builds from the tarball only. I'm not sure if cable will provide such a big improvement for us.

**Comment by chfast** [comment]
I agree with @chriseth. Use it if you need it.
I'm only doing this because we are constantly creating new repos powered by CMake, and I don't want to repeat the same patterns all the time (CMake is very verbose).

**Comment by axic** [comment]
Would be useful for #5868 to import the `SANITIZE` feature set from `CompilerSettings`.

@chfast how much effort would it be to integrate?

(Note I have a branch `asan-clang` which tries to run ASAN on Solidity).

**Comment by axic** [comment]
> At the moment, this repository is rather self-contained, which allows builds from the tarball only. I'm not sure if cable will provide such a big improvement for us.

It is possible to use "git subtrees" (used in evmc) which practically creates a commit with the entire imported tree, but keeps the commit hash in the log so the tool can track it with upstream ([an example commit](https://github.com/ethereum/evmc/commit/e60d8604af0b40a39db2d7b386df8177a2994e7f)). It would still be self contained aka no submodules.

**Comment by chriseth** [comment]
Could you explain why cable would help with sanitize? DId `cmake -DSANITIZE=...` stop working?

**Comment by axic** [comment]
Oh you're correct we do have that, missed when looking for it. Just less sophisticated then the one in cable 😉
