### ISSUE TITLE
Unexpected compilation differences leading to gas cost differences

### ISSUE THREAD

**Issue by wbt** [ethereum/solidity#3788]
Summary
----
Making some small changes to a contract changes gas usage in surprising ways.  This Issue gives code/steps to reproduce and identifies those surprising ways, identified by letters, below. 

Code to reproduce
----
I have the following files in a Truffle project:

`contracts/Contract.sol`: 

    pragma solidity ^0.4.0;
    contract Counter {
        int public value; //starts at 0 by default

        function increment() public {
            value = value+1;
        }

        function decrement() public {
            value = value-1;
        }

        function reset() public {
            value = 0;
        }

    }

`migrations/2_deploy_contracts.js`

    var Counter = artifacts.require("./Counter.sol");

    module.exports = function(deployer) {
        var counterInstance;
        deployer.deploy(Counter)
        .then(function () {
            return Counter.deployed();
        }).then(function (data) {
            counterInstance = data;
            return counterInstance.value.call();
        }).then(function (data) {
            console.log("Counter value at start is "+data);
            return counterInstance.increment();
        }).then(function (data) {
            console.log("Increment #1 used "+data.receipt.gasUsed+" gas.");
            return counterInstance.increment();
        }).then(function (data) {
            console.log("Increment #2 used "+data.receipt.gasUsed+" gas.");
            return counterInstance.increment();
        }).then(function (data) {
            console.log("Increment #3 used "+data.receipt.gasUsed+" gas.");
            return counterInstance.increment();
        }).then(function (data) {
            console.log("Increment #4 used "+data.receipt.gasUsed+" gas.");
            return counterInstance.increment();
        }).then(function (data) {
            console.log("Increment #5 used "+data.receipt.gasUsed+" gas.");
            return counterInstance.value.call();
        }).then(function (data) {
            console.log("Counter value at end is "+data);
        }).catch(function(err) {
            console.log(err.message);
        });
    };

For a simpler example, I am not using the Migrations contract nor any first migration.

I am connecting to Ganache, compiling and running this with `truffle migrate --reset`.

Unexpected Results
----
**A**: The first call to increment() used 41664 gas and subsequent calls used 26664 gas each.  Unexpected point **A** is that these are different amounts; the expected behavior is that they would cost the same gas.  This one may be just a result of the limits of my own present understanding.

**B**: When I comment out the decrement() function, all calls to increment() cost 2 gas less.  I'd expect the gas for a call to increment() to not depend on whether or not a decrement() function exists (though I'd expect *contract deployment* gas costs to be lower for the version with less code).  Adding an additional simple function, such as `decrement2` which subtracts 2 from `value`, also raises the gas price of calling `increment()` by 2.

**C**: When I comment out the `reset()` function, the gas price for calls to `increment()` does not change.  This is only unexpected because of the observation in **B.** If **B** is explained by the fact that having an extra function requires an extra step of iteration through contract code to find the right function when executing `increment,` `reset` should have the same effect as `decrement` and the inconsistency between these two is surprising point **C**.

**D**: When I change the name `reset()` to `resot()` or `resat()` (note that both are the same length as `reset()`), the gas price for `increment()` goes up by 2 and the `resot()` function behaves like `decrement()`.  The fact that this tiny tweak to the function name, with no other change in the function contents, changes whether or not this function's presence affects another function's gas cost, is surprising point **D**.  (Is `reset` a reserved word, and if so, is that documented somewhere?) 

All of the above observations hold if I swap the positions of `reset` and `decrement`, so I don't think there's anything special about the last position in the contract definition which is causing this.  

  

Versions:
----
OS: Windows 10 x64
Ganache v1.1.0-beta.0, on localhost:7545
Truffle: v4.0.4 (core: 4.0.4)
Solidity: v0.4.18 (solc-js) (specifically, `0.4.18+commit.9cf6e910.Emscripten.clang`)

**Comment by axic** [comment]
> A: The first call to increment() used 41664 gas and subsequent calls used 26664 gas each. 

This first call changes `value` from 0 to non-zero. Internally that is done using the `sstore` opcode, which has this behaviour.

> B: When I comment out the decrement() function, all calls to increment() cost 2 gas less.

This is due to the dispatcher function being an if-else jungle. #1289 is an issue to document this.

> C: When I comment out the reset() function, the gas price for calls to increment() does not change.

This is because the order of function in the dispatcher is determined by the function signature (the hash of the function + its parameters). See the previous point.

> D: When I change the name reset() to resot() or resat()

It is due to the same issue.

I think B, C and D should be explained by documenting what #1289 mentions.

**Comment by wbt** [comment]
Thanks!  This is helpful and the underlying reasons were not intuitive!
