### ISSUE TITLE
get balance is error

### ISSUE THREAD

**Issue by Fire-boy** [ethereum/solidity#3795]
//source code:    
```
contract HelloWorld
{
    address creator;
    string greeting;
    int256 amt;
    function HelloWorld(string _greeting) public
    {
        creator = msg.sender;
        greeting = _greeting;
    }

    function greet() constant returns (string)
    {
        return greeting;
    }

    function setGreeting(string _newgreeting)
    {
        greeting = _newgreeting;
    }
    
	function getEth(address _addr) public view returns(int256){

	    amt=int256(_addr.balance);
		return amt;
	}
 
  
    function getBalance(address addr)public constant returns (uint256){  
        return addr.balance;  
    }  
  


     /**********
     Standard kill() function to recover funds
     **********/

    function kill()
    {
        if (msg.sender == creator)
            suicide(creator);  // kills this contract and sends remaining funds back to creator
    }
}
```
//after run:
```
> helloworld.getEth(eth.accounts[0])
-2500000000000000001
> helloworld.getBalance(eth.accounts[0])   //wrong
1.15792089237316195423570985008687907853269984665640564039455084007913129639935e+77
 > eth.getBalance(eth.accounts[0])      //right
5.31827682037048e+23
```

can you send to my email ? : 961051751@qq.com  thank you!

**Comment by chriseth** [comment]
Can you describe the scenario in which you run this in a little more detail, please?

**Comment by Fire-boy** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3

OS:CentOS Linux release 7.4.1708 (Core) 
Linux localhost 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
soft:  go-ethereum-1.8.1
my private chain

**Comment by chriseth** [comment]
Sorry, what I meant to ask was, how did you set up your blockchain? What is the actual balance of that account? `gethEth` and `getBalance` could be consistent with each other, but these numbers are certainly not something you would see in a production blockchain.

**Comment by Fire-boy** [comment]
this is my  blockchain. the balance of eth.accounts[0] should be 5.31827682037048e+23,but contract HelloWorld's function  getBalance(eth.accounts[0])  is 1.15792089237316195423570985008687907853269984665640564039455084007913129639935e+77,so I want to know why get so big number!

**Comment by Fire-boy** [comment]
this is my  blockchain. the balance of eth.accounts[0] should be 5.31827682037048e+23,but contract HelloWorld's function  getBalance(eth.accounts[0])  is 1.15792089237316195423570985008687907853269984665640564039455084007913129639935e+77,so I want to know why get so big number!

**Comment by Fire-boy** [comment]
I'm sorry my english is so poor,I can't make you understand known me,can you speak chinese.

**Comment by chriseth** [comment]
Since the contract is very simple, I do not think this is a problem with solidity. You might get better answers (and perhaps also by people who speak chinese) at https://ethereum.stackexchange.com

**Comment by axic** [comment]
I think for some reason all bits (or at least the top bit) are set for the balance, hence the `int256(_addr.balance)` returns a negative number.

It is impossible to know without seeing the configuration for your chain and tools (the client, the tool you use to interact with the RPC, web3.js, etc.).

Please try your contract in https://remix.ethereum.org (where it actually works).

**Comment by Fire-boy** [comment]
Hello, my client is the geth command compiled by go-etherum-1.8.1, and the private chain built with this is not called RPC, and the client is set to: geth --networkid... --datadir my dir --syncmode full --port my IP --rpcapi net,eth,web3,personal -- RPC --rpcaddr my RPC IP --rpcport my RPC port console.
I'm going to convert the result strongly into int256 and I get a value of -250000000001, the number of digits may be wrong, but it's a negative number, and it starts at -25 and the last one is 1.
