### ISSUE TITLE
Type checking for comparison operator with literal and int8 is not symmetric.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3796]
```
//pragma solidity 0.4.20;

contract test {
    function f() pure public {
        int8 x;
        if( x == 1) {} // OK
        if( 1 == x) {} // Compiler error
    }
}
```

**Comment by tolymoz** [comment]
Such mistake is also possible to find for int16 (probably for others as well). It just depends on the literal, which int type it needs.
Example:
        `int16 x;`
        `if( x == 255) {} // OK`
        `if( 255 == x) {} // OK`
        `if( 256 == x) {} // Compiler error`

**Comment by randomnetcat** [comment]
Okay, I got it down to asymmetrical handling of the literal.

When the variable is on the left, the compiler checks `IntegerType::binaryOperatorResult`. Inside this call, `commonType` finds that the literal's `RationalNumberType` is implicitly convertible to `int8`'s `IntegerType` However, in `RationalNumberType::binaryOperatorResult`, it first converts itself to its `mobileType`, `uint8`, then checks the operator based on that. Of course, `commonType` finds that `int8` is not implicitly convertible to `uint8`, or vice-versa. Typechecking therefore fails.

**Comment by chriseth** [comment]
So the bug is that we forgot another conversion to mobile type?

**Comment by randomnetcat** [comment]
I think it's kind of the opposite. When you take the mobile type of the rational, you lose comparison compatibility with either the signed or unsigned integer types, depending on whether the literal is signed. The problem is that rational's mobileType doesn't know context.
