### ISSUE TITLE
improve Event section in Tutorial

### ISSUE THREAD

**Issue by LianaHus** [ethereum/solidity#38]
https://github.com/ethereum/wiki/issues/23

**Comment by taoeffect** [comment]
Thanks for keeping this open. :+1:

**Comment by itsnotlupus** [comment]
On that line of thought, it'd be great to have something explaining how long transaction logs are kept around to be accessed by web3's filters or similar mechanisms. 

I thought they were permanent, but the 256 block limitation on accessing block hashes makes me wonder if that's really the intent.

The persistence of events can make a fairly large difference in the way external code will interface with contracts, so clarity there would be really useful.

**Comment by sillytuna** [comment]
I asked Vitalik about this. He said logs are stored forever although in future it'll be down to individual nodes (who I suggested could just for archive access). The longevity of logs and contracts is important to DAPs  so I would also like to see more documentation on this.
