### ISSUE TITLE
Struct not being stored in mapping when it contains more than two 'string' properties.

### ISSUE THREAD

**Issue by clowestab** [ethereum/solidity#381]
Issue as described on the Ethereum StackExchange site: http://ethereum.stackexchange.com/questions/900/struct-not-being-stored-in-mapping-when-it-contains-more-than-two-string-prope/

**Comment by clowestab** [comment]
Created a Gist to demonstrate the problem [here](https://gist.github.com/clowestab/ca86d0ee43de1e918c22)

To reproduce:
- Mine the contract
- Run `whois.buildAddress("ID","STREET","CITY", {from:eth.accounts[0]});`
- Mine transaction
- `whois.getAddressStreet("ID");` will output "No address" (which is incorrect)

**Comment by VoR0220** [comment]
so it appears to be compiling correctly. Looking further into this.

**Comment by VoR0220** [comment]
Interesting. I'm going to make a test to check this out. Will let you know the results.

**Comment by VoR0220** [comment]
Okay. So I ran a test, it isn't the multiple strings in a struct, that is not the problem. My guess would be that it has something to do with SHA3 as we've been running into issues with that recently. Doing some further testing on it.

**Comment by VoR0220** [comment]
Alright, I am indeed able to replicate this exact problem. I am now trying to figure out whether SHA3 is the problem or if it's another factor. 

UPDATE: I take back what I said about SHA3 earlier...might still be the reason. Trying to figure out how to get this running.

**Comment by clowestab** [comment]
Sorry for the delayed response. Thanks for looking into this.

I initially utilized `mapping(string => Address) addresses;` which also presented the issue.
I changed it to byte32, and sha3'd the string 'key' thinking that it might be the fact that I was utilizing a string that caused the issue. The issue however presents itself in both cases.

**Comment by VoR0220** [comment]
so the problem would appear to be the key itself and it not storing it. This is very problematic. Potential showstopper. Currently I am able to get more than one string so that is itself not the problem. But it may also be a problem with mappings of structs.

**Comment by clowestab** [comment]
Interesting. Thanks for the update.
"Potential showstopper" sounds pretty fatalistic. 

Unfortunately my knowledge and understanding of the 'behind the scenes' of programming languages is somewhat limited.

Any insight you can share (as a matter of interest) would be greatly appreciated although I appreciate that the priority is probably resolving the issue ;)

**Comment by chriseth** [comment]
Was neither able to reproduce this in browser-solidity nor in Mix. Are you sure the first transaction did not go out of gas?

**Comment by clowestab** [comment]
I'm running it on a test network using an account that has a huge amount of gas.

Have tried a number of times executing utilising contract code containing structs with different numbers of properties.

Consistently works with only one property but not with 2+

Is there any in built debugging that would help me to debug this further?

Others likewise seem to have had similar issues..

Sent from mobile.

**Comment by chriseth** [comment]
You can enable the vm trace of you node, and in general increase the verbosity.
Could you provide me the actual data sent to the contract (including the constructor parameters)?

**Comment by chriseth** [comment]
Any news on this?

**Comment by clowestab** [comment]
Issue still persists on my test network. I gave up in the end.
My exact reproduction steps were posted in the second comment.

**Comment by ismaelbej** [comment]
We have the same issue with the latest version of geth and solc running in Ubuntu xenial, in a private network.

Investigating it fails when the struct has 3 strings fields. But it works with 2 strings.

After mining `test.write.sendTransaction(1,"marco","polo","nop",{from:eth.accounts[0]})`. When trying to retrieve it `with test.store.call(1)` it will return `[false, "", "", ""]`.

Chaning the contract to remove any reference to data3, then the same commands will work.

```
contract test {
    struct data {
        bool used;
        string data1;
        string data2;
        string data3;
    }
    mapping(uint => data) public store;
    function write(uint id, string data1, string data2, string data3) public {
        store[id].used = true;
        store[id].data1 = data1;
        store[id].data2 = data2;
        store[id].data3 = data3;
    }
    function read(uint id) public returns (string, string, string) {
        return (store[id].data1, store[id].data2, store[id].data3);
    }
}
```

```
$ geth version
Geth
Version: 1.4.3-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6
```

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.3.2-0/Release-Linux/g++/Interpreter
```

**Comment by SebasAran16** [comment]
I found the same issue with a struct inside a mapping with two enum types and one string (2 storage slots on mapping, might it be the cause?). Somebody found something else about this issue?
