### ISSUE TITLE
Bool variables should not allow comparison/bitwise operators

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3811]
```
bool a = true;
bool b = false;
bool c;

// compiles
c = a < b;
c = a <= b;
c = a > b;
c = a >= b;

// rejected
c = a | b; // bitwise or
c = a ^ b; // bitwise xor
c = a & b; // bitwise and
c = a << b; // shifts (all of them are properly rejected)
// add, sub, mul, div, mod and exp is rejected
```

Only logical `and` and `or` and (non)equality should be supported.

Found by @leonardoalt.

**Comment by chriseth** [comment]
Oh wow, bitwise or compiles, but bitwise and does not??

**Comment by chriseth** [comment]
Cannot reproduce (bitwise or).

**Comment by chriseth** [comment]
This might be something for Christian to do together with someone else.

**Comment by axic** [comment]
> Cannot reproduce (bitwise or).

It doesn't work here anymore, probably had a wrong version of the binary. The rest still stands.

**Comment by chriseth** [comment]
Ah wait a second, it is a change in `binaryOperatorResult` where we do not have access to the pragma, so probably cannot be done as of now.

**Comment by chriseth** [comment]
It might be worth considering whether the conversion functions in the Type class and its subclasses could receive a flag that tells whether 050 is active or not.
