### ISSUE TITLE
Putting struct with same name in two contracts makes constructor assignment fail

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#383]
```
contract A {

    struct S {
        uint x;
    }

    S s;

    function A(uint x) {
        s.x = x;
    }

    function getX() constant returns (uint x) {
        return s.x;
    }

}

contract B {
    struct S {
        uint x;
    }
}
```

Run in online compiler, pass a value into create for 'A', and getX will still return 0. Remove contract B and it will work.

Online compiler: `0.2.1-91a6b35f/.-Emscripten/clang/int`

Also. Struct inheritance? Nice! :P

```
contract A {

    struct S {
        uint x;
    }

    S s;

    function A(uint x) {
        s.x = x;
    }

    function getX() constant returns (uint x) {
        return s.x;
    }

}

contract B is A {

    struct S {
        uint y;
    }

    S s;

    function B(uint x, uint y) A(x) {
        s.y = y;
    }

    function getY() constant returns (uint y) {
        return s.y;
    }

}
```

**Comment by chriseth** [comment]
Quick analysis revealed that it is not relevant whether `B` has the struct, just `contract B{}` also produces the bug. Weird.
By the way, do you know that you can just use `A.S` inside `B`?

**Comment by androlo** [comment]
Ok.

I did not know that. Thought it was only possible through libraries. Thanks.

**Comment by chriseth** [comment]
The reason was a bug in web3.js: https://github.com/ethereum/web3.js/pull/385
