### ISSUE TITLE
How to generate random values?

### ISSUE THREAD

**Issue by wangh09** [ethereum/solidity#3837]
Hi, I found the following sentences in the documentation:

Do not rely on block.timestamp, now and block.blockhash as a source of randomness, unless you know what you are doing.

Both the timestamp and the block hash can be influenced by miners to some degree. Bad actors in the mining community can for example run a casino payout function on a chosen hash and just retry a different hash if they did not receive any money.

I don't quite follow the example, could anyone explain it more clearly? And then is it possible to generate random values?  Thanks!

**Comment by chriseth** [comment]
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
