### ISSUE TITLE
Modifier-style constructor calls without parentheses should be an error.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#3838]
Came up in #3821.

In this code snipped:

    contract A { constructor() public { } }
    contract B1 is A { constructor() A() public { } }
    contract B2 is A { constructor() A public { } }

the constructor call in ``B1`` is fine, but in ``B2`` the ``À`` in ``constructor() A public {}`` serves no purpose and should be disallowed.

**Comment by ekpyron** [comment]
The git branch ``modifierStyleWithoutParentheses`` contains a fix that depends on #3821.
I will create a pull request once #3821 is merged.

**Comment by chriseth** [comment]
You can create a pull request now and state that it depends on #3821
