### ISSUE TITLE
"this used in constructor" static analysis rule has false positives

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#3843]
One of the warnings emitted by the static analyzer is `"this" used in constructor` from #2605.

https://github.com/ethereum/solidity/blob/fe61435c273bf43ac1a20d8bc97b6935a54b7117/libsolidity/analysis/StaticAnalyzer.cpp#L210-L211

The warning was implemented by checking that the static type of the LHS of a member access is the same as the contract being defined. But this wrongly catches other scenarios too such as:

```solidity
pragma solidity ^0.4.14;

contract Foo {
    bool public bar;
    
    function Foo(Foo other) public {
        require(other.bar());
    }
}
```

**Comment by nbauernfeind** [comment]
Using `super` also causes a false positive. See #3861.
