### ISSUE TITLE
What is the unit of time functions on smart contract

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#3844]
Hello guys,

I really confused what is the unit of airBegintime, airEndtime, icoBegintime and icoEndtime in contract address? Are they millisecond? And how these functions work?

Can someone inform me, please?

Here the contract address: https://etherscan.io/address/0x8c37188945c02818f09c7650093befcaa4085127#code

Here the functions:
---
airBegintime = 1520312400;
airEndtime = 1609390800;
---
icoBegintime = 1520312400;
icoEndtime = 1924923600;
---

**Comment by ucwong** [comment]
it  seems like second

**Comment by chriseth** [comment]
I don't see any way to improve the documentation: https://solidity.readthedocs.io/en/v0.4.21/units-and-global-variables.html?highlight=time#time-units

This is the first hit if you search for time.
