### ISSUE TITLE
Signed rights shifts use SDIV and as such round differently to proper SAR

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3847]
From https://github.com/ethereum/solidity/pull/3797/files#r179776071.

This could be changed in a breaking release.

**Comment by chriseth** [comment]
Any ideas about how to implement it efficiently?

**Comment by axic** [comment]
I think this should do it:

```
or(shift_right(value, bits), sub(0, shift_right(value, type_width - 1)))
```

where `shift_right` is either `div` or `shr` (assuming that the stack item has the high bits cleaned to 0 if `type_width != 256` and that `type_width` is a constant, such that `-1` doesn't need to be done via an opcode).

**Comment by chriseth** [comment]
ok, we could also use a combination of `div` / `shr` and `signextend`.

**Comment by ekpyron** [comment]
To be discussed:

  * This is a dangerous change - should we introduce warnings before? after?
  * Consider using ``>>>``, check how it's used in other languages.
