### ISSUE TITLE
Purchase contract Code in Solidity documentation

### ISSUE THREAD

**Issue by ArpanaGupta** [ethereum/solidity#3849]
Hello,

http://solidity.readthedocs.io/en/develop/solidity-by-example.html?#safe-remote-purchase . 
In the "Purchase" contract , the constructor function of Purchase() should also set the 'state' state variable as State.Created.
Otherwise the abort(), confirmPurchase() functions will not work.
Please confirm if understanding is correct.

Thanks,

**Comment by chriseth** [comment]
Almost! The default value is already `State.Created`. It would probably be good to mention this in the text.

**Comment by aj07** [comment]
@chriseth , please correct me if I am wrong. I am assuming that in the comment section (in text) we need to include "how state variable is stated" to users. Isn't?

**Comment by axic** [comment]
@chriseth I think it makes actually more sense to explicitly set the state variable either in the constructor or at declaration time. Otherwise it should link to a section which explains what default value `enum`s are taking.

**Comment by chriseth** [comment]
Yep, we could mention it right before the state variable itself.

**Comment by chriseth** [comment]
I think it is better to explain the default value than setting it, because it is a well-defined feature that can be used by users.
