### ISSUE TITLE
Feature request - Pass numerical data using sendTransaction inside the data object

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#385]
I would like to submit the number 1 in a sendTransaction like so

eth.sendTransaction({from: eth.accounts[0], value: web3.toWei(.001, 'ether'), to: '0xXXXXXX....', gas: 500000, data: web3.fromAscii('1')})
then compare that number with a number created like so within my smart contract:

uint256 x =1; if (msg.data == x) {doSomethingCool};
How can I do this? The only way to get data into the smart contract is via the data object like so:

eth.sendTransaction({from: eth.accounts[0], value: web3.toWei(.001, 'ether'), to: '0xXXXXXX....', gas: 500000, data: web3.fromAscii('1')})
Which means I am sending and then comparing the hex version of 1 (0x31) to the uint256 version of 1 inside the smart contract. :\

How can I send a number? e.g

eth.sendTransaction({from: eth.accounts[0], value: web3.toWei(.001, 'ether'), to: '0xXXXXXX....', gas: 500000, data:1})
Or is there a round-about way I can go about doing this?

It is vital for something I am building and is a showstopper for me right now. Surely there is a way.

**Comment by chriseth** [comment]
Answered elsewhere.
