### ISSUE TITLE
Improve the contributors guide

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3850]
Some good inspiration to read first:
- https://github.com/ethereum/remix-ide/blob/d5aec6736dafd5050119aafffe5ac1e353943457/team-best-practices.md
- https://github.com/pipermerriam/ethereum-dev-tactical-manual

**Comment by randomnetcat** [comment]
I'd like to note that the coding standards link goes to a 404, leaving no official style guide for C++ code in this repository.

**Comment by chriseth** [comment]
@meowingtwurtle which link? We recently merged a new version of the coding style.

**Comment by randomnetcat** [comment]
![image](https://user-images.githubusercontent.com/1988485/38564157-8c5c9126-3cac-11e8-9ab1-a7621467ee52.png)
The link in that image goes to a 404 at https://raw.githubusercontent.com/ethereum/cpp-ethereum/develop/CodingStandards.txt. This is presumably where the style guide for C++ code was originally.

**Comment by axic** [comment]
The link worked for me as long as you are on `develop`. Probably the release version of readthedocs points to an old link.

**Comment by aj07** [comment]
@axic Should we put https://github.com/ethereum/remix-ide/blob/d5aec6736dafd5050119aafffe5ac1e353943457/team-best-practices.md  into readthedocs. There, its written but in very short way. We can elaborate it there.

**Comment by axic** [comment]
Are you suggesting to just copy Remix's guide? I think our development process differs slightly, it should be adjusted.

**Comment by aj07** [comment]
@axic No, it will be change a lot. Like 
1. How team communicates.
2. How to file bug?
3. How to dive as contributor ?
4. What coding standard we use?
5. Minimum system requirements?
6. Testing pattern

**Comment by ChrisChinchilla** [comment]
OK, we discussed this in a retro, so prioritising this one for me to do :)

Also want to highlight issues people can work on and make process as simple as possible.
