### ISSUE TITLE
Consider using intx instead of boost::multiprecision (once stable)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3851]
**Do not start doing this, since intx is not ready yet**

See https://github.com/chfast/intx.

Benefit:
- the features needed to the compiler could be well optimised
- the binary size could be reduced

However, these are only goals, the current or the "stable" version of intx may not satisfy any of those needs.

**Comment by chfast** [comment]
intx has all implementation for int256 but no public API yet. Do you also need int128?

**Comment by axic** [comment]
Well actually we need int256, uint256 and unlimited precision. The last requirement might put intx out of scope for this.

**Comment by axic** [comment]
The two places we use unlimited precision:
1) Evaluating constant expressions.
2) The constant optimiser, but there I think we really just need to tell if an overflow has occurred.

@chfast said that 1024-bit precision would be possible with intx, if we want to consider that breaking change in Solidity for constant expressions.

**Comment by ekpyron** [comment]
Can't ``intx`` nowadays just double the precision of each of its types and continue doing so? If so, we could have 4096-bit precision - and we already basically limit our ``RationalNumberType`` to that range - we just have to be careful with overflows and the like...

**Comment by chfast** [comment]
It should work for 4096 bit precision (only unit tests are required at this point). However, because of the recursive design the code size can be an issue. Here is an example procedures for 4096-bit add and mul (see the end of the file): https://godbolt.org/z/3qJEF4.

The mul one is ok, because it is implemented as loop over 64-bit words (this turned out to be currently faster for 512+-bit types). But add is implemented recursively - the 4096-bit one uses 2048-bit types. If that is going to be a problem, I can consider re-implementing some parts as loops.

**Comment by ekpyron** [comment]
I'd imagine the performance would still be better than boost's bigints anyways, so I don't think it'll be a problem.

**Comment by axic** [comment]
If we want to test the move to intx, we could consider changing the constant optimiser to intx, as a test.

**Comment by ekpyron** [comment]
We should probably have another discussion about dependencies then, shouldn't we? We kind of already agreed to go for fmtlib and ranges-v3 - and nlohmann-js can still be considered. I'd still actually go for submodules (maybe with some fancy cmake automation), but not sure we can agree on that...

**Comment by axic** [comment]
> We should probably have another discussion about dependencies then, shouldn't we?

Sure, you mean a dedicated call?

> We kind of already agreed to go for fmtlib and ranges-v3

Where/when?

> I'd still actually go for submodules (maybe with some fancy cmake automation)

What is wrong with `ExternalProject` in cmake?

**Comment by axic** [comment]
As a heads up, @chfast is working on changing the recursive design of intx to a flat array based one. This would mean large instances (like the 4096-bit precision we discussed here) would become cheap.
