### ISSUE TITLE
Correct the style of coding style

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3854]
The coding style document (`CODING_STYLE.md` at the project root) is an md document but does not properly format according to these rules.

**Comment by randomnetcat** [comment]
This is so meta :P

**Comment by MushuLeDragon** [comment]
Since we merged the PR, can we close the issue ?

**Comment by chriseth** [comment]
Yes, I thought it would auto-close.

**Comment by tsauvajon** [comment]
I believe it closes only if you add keywords (`closes`, `resolves`) and the number of the issue in a commit message. We've not referenced the issue in any of our commits !
