### ISSUE TITLE
Solidity Multiple inheritance resolution

### ISSUE THREAD

**Issue by boorac** [ethereum/solidity#3856]
# Environment

```
Truffle v4.1.5 (core: 4.1.5)
Solidity v0.4.21 (solc-js)
node v8.10.0
Ubuntu 16.04
```

# Issue
I'm attempting to understand how solidity resolves multiple inheritance. As explained in the docs, Solidity uses C3 linearization. The relation between my classes is displayed on the image below: 
![hjzsp](https://user-images.githubusercontent.com/25860364/38619929-9718d218-3d9d-11e8-8683-01eb720bed7e.png)

I want to understand in which order super is working when called from SampleCrowdsale. I ran the C3 linearization algorithm manually as well as using [this](https://github.com/federicobond/c3-linearization) tool. The results I get:

```
1) SampleCrowdsale
2) CappedCrowdsale
3) RefundableCrowdsale
4) FinalizableCrowdsale
5) TimedCrowdsale
6) MintedCrowdsale
7) IndividuallyCappedCrowdsale
8) TieredCrowdsale
9) Crowdsale
10) Ownable
```
Then I tried to confirm my findings empirically. I added a method `log` to every contract in the inheritance chain, the method fires an event with the contract name. My findings using this method differ from the analytical approach:

```
1) SampleCrowdsale
2) TieredCrowdsale
3) IndividuallyCappedCrowdsale
4) MintedCrowdsale
5) RefundableCrowdsale
6) FinalizableCrowdsale
7) TimedCrowdsale
8) CappedCrowdsale
9) Crowdsale
10) Ownable
```
Can anyone explain to me how to solve this?

**Comment by chriseth** [comment]
My first hunch would be that the tool you mention uses a different order of the direct parents.

**Comment by federicobond** [comment]
@boorac can you post the Solidity code you are using for the empirical part?

**Comment by boorac** [comment]
@federicobond I can't post the exact code, however I mashed up a quick repo with the same features:
https://github.com/boorac/solidity-multiple-inheritance-resolution

For completion, the same discussion on [stackexchange](https://ethereum.stackexchange.com/questions/43650/solidity-and-multiple-inheritance)

**Comment by frangio** [comment]
@chriseth What order of direct parents is passed to the C3 algorithm in the Solidity compiler?

**Comment by chriseth** [comment]
Let's check with the compiler:

This one compiles:
```
contract A { }
contract B is A { }
contract C is A, B { }
```
But that one does not:
```
contract A { }
contract B is A { }
contract C is B, A { }
```

So the order in the inheritance specifier (the direct parents) is base-to-derived (read from left to right).

**Comment by chriseth** [comment]
Of course it might also be that there is a bug in the C3 implementation, and not in the way the inheritance graph is passed to the algorithm.

**Comment by federicobond** [comment]
We talked this a bit with @frangio yesterday. The problem here is that Solidity does the linearization from right to left while Python does it from left to right. In Python, for example, you always put mixins before the base class whereas in Solidity you always put them after.

Here's some sample Python code:

```python
class ERC721Basic:
    pass

class ERC721Metadata(ERC721Basic):
    pass

class ERC721Enumerable(ERC721Basic):
    pass

class ERC721(ERC721Metadata, ERC721Enumerable, ERC721Basic):
    pass

print(ERC721.__mro__)
# (<class '__main__.ERC721'>, <class '__main__.ERC721Metadata'>, <class '__main__.ERC721Enumerable'>, <class '__main__.ERC721Basic'>, <class 'object'>)
```
To get the same method resolution order in Solidity, you have to do:
````solidity
contract ERC721Basic {}

contract ERC721Metadata is ERC721Basic {}

contract ERC721Enumerable is ERC721Basic {}

contract ERC721 is ERC721Basic, ERC721Enumerable, ERC721Metadata {}
````
Notice the reversed order of parents in ERC721.

This is not properly explained in the documentation, which on one hand says:
> Solidity follows the path of Python and uses “C3 Linearization” to force a specific order in the DAG of base classes.

But then states:
> A simple rule to remember is to specify the base classes in the order from “most base-like” to “most derived”.

Which is not what you would do in Python.
