### ISSUE TITLE
SMT checker integration

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3857]
It would be nice to have better integration with solvers, currently it only works on the commandline if compiled with z3 (or cvc4).

There are multiple ways to do it, but at least two major options:
1) Have it compiled in with the release: solc binary + soljson
2) Have it supported via a callback or two-steps compilation mechanism

Option 1) works on the native binaries (such as Linux), but compiling z3 with emscripten fails. Needed:
- figuring out why it fails (it is a runtime exception)
- figuring out how to shrink the binary size (it is 40mb via emscripten)
- optimising the binary for a good balance between size / speed

Option 2) requires a generic interface to be finished and external packages supporting it:
- the generic interface is dealt with in #3073 
- we could use a node.js binding to be used with truffle (check https://www.npmjs.com/package/cvc4)
- for browsers cvc4/z3 could be compiled to webassembly
- or alternatively browsers could use an external service via http (bad)

**Comment by leonardoalt** [comment]
@axic Do you remember what exactly happens with z3 and emscripten?
I added it now and I get a compilation error from emscripten on Solidity, complaining about an unused var in a function from `z3++.h`

**Comment by leonardoalt** [comment]
For future reference: https://github.com/cpitclaudel/cvc4.js/

**Comment by leonardoalt** [comment]
I checked https://www.npmjs.com/package/cvc4, and it doesn't seem to accept `smtlib2` inputs, only formulas constructed within the library.
Right now I'm more optimistic about https://github.com/cpitclaudel/cvc4.js/

**Comment by chriseth** [comment]
How difficult is it to create a binary multi-platform npm package?

**Comment by leonardoalt** [comment]
Of CVC4? Looking at https://github.com/cpitclaudel/cvc4.js/ it seems non-trivial

**Comment by chriseth** [comment]
npm packages can have native binaries, i.e. things that are not javascript.

**Comment by leonardoalt** [comment]
Status:
- SMTChecker can be used via `--standard-json` double run
- From 0.6.0 it will also be able to use a sync callback to solve queries

The only step missing then will be a solver in js we can somehow link to.

**Comment by leonardoalt** [comment]
https://github.com/ethereum/solidity/issues/8851 successfully links emscripten z3, and it works for node and browsers

**Comment by leonardoalt** [comment]
We actually have all the initial options implemented by now ;)
(https://github.com/ethereum/solidity/pull/8909)
