### ISSUE TITLE
Extend the types section of the documentation with operation semantics

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3860]
Would be important to explain unary and binary operators on integer and fixed point types.

(Raised in #3389).

**Comment by ChrisChinchilla** [comment]
@axic and @chriseth I just started looking at this, but noticed that 
https://github.com/ethereum/solidity/pull/3389 has a docs contribution already, so shall I just extend and polish the changes there? And work in that branch or fork a new branch from it? or just start a new branch with their commits and my polish?

**Comment by randomnetcat** [comment]
#3389's doc contributions are specifically concerning fixed point operations and semantics. I would not recommend basing anything for this task off of that.

**Comment by chriseth** [comment]
@axic is there something else to do here?

**Comment by axic** [comment]
We can open a new issue for tracking fixed point types only or request it to be filled within the fixed point PR.
