### ISSUE TITLE
[CLI] Do not ignore the output selection in assembler mode

### ISSUE THREAD

**Issue by thomaseizinger** [ethereum/solidity#3870]
I am using the `--assemble` mode for transforming assembly-syntax into binary representation through a tool.

This works good except for the fact that the output of the compiler is not really machine-readable as it just dumps everything to stdout and stderr.

It would be nice if `solc` would care about the `--bin` flag that is already present if run in assemble mode (`--assemble`).

This way, one would not have to use a regex over the data in stdout in order to retrieve the binary representation.

Current behaviour:
```
➜  /tmp solc --assemble --bin temp_2.asm

======= temp_2.asm (EVM) =======

Pretty printed source:
{
    0x40
    0x50
    add
    pop
}

Binary representation:
604060500150

Text representation:
    /* "temp_2.asm":3:7   */
  0x40
    /* "temp_2.asm":9:13   */
  0x50
    /* "temp_2.asm":15:18   */
  add
    /* "temp_2.asm":20:23   */
  pop
```

Desired behaviour:
```
➜  /tmp solc --assemble --bin temp_2.asm
604060500150
```

**Comment by chriseth** [comment]
Thanks for the suggestion! We will probably need to ramp up these options anyway with regards to the optimizer coming up.

**Comment by cameel** [comment]
I have adjusted the title, because this applies to all the output options. For example `--metadata` is ignored in assembler mode as well.

**Comment by cameel** [comment]
#12074 solves this. The output does not exactly match the one shown under "Desired behavior" above because output includes headings but that's a separate issue: #10275.

Also, the PR only makes it possible to select existing outputs (`--ir`, `--asm`, `--bin` and `--ewasm`). It does not add any others that are available via Standard JSON.
