### ISSUE TITLE
Proper source locations for parser errors.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#3874]
Parser errors currently use the current scanner position as both start and end of their source location.
I think it may be beneficial to change that towards using the whole range of the current token as error location.
Most parser errors will have the form "expected something, but got another thing" and I think it makes sense to mark the other thing in the error entirely. And it will make it easier to identify the error locations in the interactive testing tool.

Comments?

**Comment by chriseth** [comment]
We should also fix the error messages. "Expected token LParen" should be changed to something like `Expected '('`.
