### ISSUE TITLE
ABI decoding API

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3876]
Split off #1707.

With #1707 an ABI encoding API was introduced:
- `abi.encode(...) -> bytes`
- `abi.encodePacked(...) -> bytes`
- `abi.encodeWithSelector(bytes4, ...) -> bytes`
- `abi.encodeWithSignature(string, ...) -> bytes`

It would be natural to extend this with a decoding counterpart.

Listing here a couple of options as they came up historically:

1) The first suggestion has been `decode[T1,...,Tn](input)` where `Ti` is a type.

For example:
- `decode[uint, uint, string](data) -> uint, uint, string`
- `decode[bytes4, uint, uint, string](data) -> bytes4, uint, uint, string` (`msg.data` with selector`)

2) Alternative syntax to this is `decode<T1,...,Tn>(input)`.

3) Potentially the types could be string literals (and not types): `decode<"uint","uint","string">(input)` and if that is allowed, it could also use variables.

4) It also may make sense to introduce tuple types and make use of them: `decode<(uint,uint,string)](input)` (this really makes sense if tuple types are first class and can be passed around).

5) Other suggestions included passing the types as a string: `decode("bytes4,uint,uint,string", input)`

6) And having a `decode` overload over function types:

```
function (uint, uint, string) f;
f.decode() -> uint, uint
```

But since function types have no names, the selector cannot be computed without passing it explicitly:
```
function (uint, uint, string) f;
// assuming this would throw if there's a selector mismatch
f.decode("f(uint,uint,string)") -> uint, uint
```

**Comment by chriseth** [comment]
Some notes;

 - the return type of the decode function has to be a compile-time constant, so anything that utilizes strings has no real benefit over the types themselves.
 - `[...]` is easier to parse than `<...>`.
 - another option might be just `abi.decode((uint, uint, uint[]), data)` or  `abi.decode([uint, uint, uint[]], data)` or even `abi.decode(data, uint, string, uint[])`.

**Comment by chriseth** [comment]
Especially the third option would not even need any modifications to the parser.

**Comment by axic** [comment]
I think I like the following if no parser changes are allowed:
- `abi.decode(input, T1, ...,  Tn) -> T1, ..., Tn`
- `abi.decodeWithSelector(input, T1, ..., Tn) -> bytes4, T1, ..., Tn`

But it also could use modifier functions (like `value()` and `gas()` - I'd suggest `types`, `fields` or `members`):
- `abi.decode.types(T1, ...,  Tn)(input) -> T1, ..., Tn`
- `abi.decodeWithSelector.types(T1, ..., Tn)(input) -> bytes4, T1, ..., Tn`

This could also be used as a type annotation on the encoders too: `abi.encodeWithSelector.types(uint256,uint8,bytes)("f()", a, b, c)`

Then again if the goal is visibility, it would make sense making them stand out syntactically:
- `abi.decodeWithSelector<uint256,uint8,bytes)(input)`
- `abi.encodeWithSelector<uint256,uint8,bytes)("f()", a, b, c)`

**Comment by chriseth** [comment]
I think I would also prefer the template style, but we have to see how easy that is to implement in the parser. The problem is that `<` is also used as a binary operator, while `[` only has a bracket-like functionality.

**Comment by PhABC** [comment]
If I could only wish for one early Christmas gift, this would be it.

**Comment by chriseth** [comment]
This is requested a lot, and I actually think that at least `abi.decode(data, T1, T2, ...., Tn) -> T1, T2, ..., Tn` shouldn't be too hard to implement. Should we give it a shot for 0.5.0?

**Comment by snario** [comment]
Yes -- this will accelerate state channels adoption.

**Comment by chriseth** [comment]
If we add things like `functionName.returnTypes` it might be better to use `abi.decode(data, (T1, T2, ...., Tn)) -> T1, T2, ..., Tn`, also it kind of looks cleaner to me. Does anyone think this would be too complicated? For single types, we could also allow `abi.decode(data, uint) -> uint` without parentheses (`(uint)` and `uint` is treated identical by the type checker anyway).

**Comment by PhABC** [comment]
@chriseth 

Posted the following 2 questions in the PR, but here seems more appropriated ; 

Would the format `abi.decode(data, (type1, type2, ...))` allow for predefined decoding patterns?

e.g.
```javascript
struct TransferArgs{
  address from;
  address to;
  uint256 amount;
}
```
and then `TransferArgs memory transferArgs = abi.decode(data, TransferArgs)`? What would the argument be to use this tupple format otherwise?

Also, I assume it will be possible, but just to be sure, will it be possible to decode the first n types and then pack the rest is a bytes array? Something like `abi.decode(data, (address, bytes))` instead of `abi.decode(data, (address, address, uint256))`.

**Comment by chriseth** [comment]
Structs will be supported if you enable `ABIEncoderV2`. Partial decoding sounds useful but is probably not part of the first iteration. I would imagine something like: `x = abi.decode(data, (address, bytes, uint256))` and then using `x[0]` actually only performs the decoding.

**Comment by PhABC** [comment]
And `x[0]` would return `address`, the first element to be decoded?

**Comment by chriseth** [comment]
Yes, indeed. It would be better to also access elements by name, so I think this should still be refined.

**Comment by chriseth** [comment]
But once we have that, we might in the future also apply this lazy decoding to functions in general.

**Comment by PhABC** [comment]
It does sound more efficient. Good idea.

**Comment by D-Nice** [comment]
Passing the types as a string would appear to be most flexible imo.

**Comment by k06a** [comment]
Finally with Solidity 0.6.x you can do this:
```solidity
(uint256 a, string memory b) = abi.decode(abi.encodePacked(data[4:]), (uint256,string));
```
