### ISSUE TITLE
Revise "this" warning for constructors.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#3877]
In #3875 the warning about the use of "this" in constructors was revised to reduce false positives.

However, now there are cases like ``C c = this; c.f();`` that could be detected at compile-time, but are not warned about.

A general compile-time pure expression evaluator may help in detecting these cases.

**Comment by cameel** [comment]
Somewhat related issue: #11540.

**Comment by ekpyron** [comment]
Closing this - we may want to pick it up again after https://github.com/ethereum/solidity/issues/13724.
