### ISSUE TITLE
General compile-time pure expression evaluator.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#3878]
I've been working on several issues, that would benefit from a general compile-time pure expression evaluator.

This includes #3877, #3522, as well as expressions used for array lengths.

The main reason against a general compile-time evaluator for such expressions would be its complexity and the danger of introducing errors in it.

The main reasons for such an evaluator are that it would be a powerful analysis tool, that it would enable additional features like array lengths resulting from calling pure functions and that it could be used as an early optimizer step.

**Comment by chriseth** [comment]
Note that for the existing evaluator, we already have a representation of the run-time value at compile time (RationalNumberType), which is not the case for anything else.

**Comment by ekpyron** [comment]
Duplicate of https://github.com/ethereum/solidity/issues/3157

**Comment by ekpyron** [comment]
Closing as duplicate of the others.
