### ISSUE TITLE
Ensure that jsoncpp installed on the system won't interface with the builtin one in CMake

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3883]
It seems that in certain cases when jsoncpp headers are lingering as a system installation they may interfere with the built in version.

This is the case in https://github.com/ethereum/homebrew-ethereum/issues/163 and #3467 (our attempt to update jsoncpp).

**Comment by chriseth** [comment]
I think I also exerince this from time to time. I guess the proper fix would be to prefer our version of the jsoncpp headers before the system headers.

@chfast could you perhaps help here?

**Comment by chfast** [comment]
I will inspect the CMake scripts.

The solution is simple but hard to achieve and requires CMake discipline. You must make sure that system deps are behind local deps and libs in dependency tree (depth-first).

Easy test is to run `make VERBOSE=1` and check if there is `-I/usr/include` before `-I<local-deps>`.

Can you list of your current dependencies?

**Comment by chfast** [comment]
I notices Boost includes were before JSONCPP includes. Fixed in https://github.com/ethereum/solidity/pull/3888.
This is hard to test on Linux where it seems the `/usr/include` (Boost) is implicit so CMake skips it anyway.

**Comment by chriseth** [comment]
@chfast can this be closed?

**Comment by chfast** [comment]
Give me an hour.

**Comment by chfast** [comment]
I wanted to test it on macOS, but you don't have macOS in CI.

I tested it with invalid header `/usr/include/json/json.h` and it built fine on Linux.
