### ISSUE TITLE
How can I fix the probem?

### ISSUE THREAD

**Issue by 08zhangyi** [ethereum/solidity#3886]
My contract is,
`pragma solidity ^0.4.2;

contract sample1 {
	int public b = 78;
	int internal c = 90;
	
	function sample1() public {
		this.a();
		//a();

		b = 21;
		this.b;	
		this.b();
		//this.b(8);
		
		//this.c();
		c = 9;
		
	}
	
	function a() external {
	}
}

contract sample2 {
	int internal d = 9;
	int private e = 90;
}

contract sample3 is sample2 {
	sample1 s;
	
	function sample3() public {
		s = new sample1();
		
		s.a();
		
		int[1] memory f;
		f[0] = s.b;
		
		//s.b = 18;
		
		//s.c();
		
		d = 8;
		
		//e = 7;
	}
}`
the wallet tells me that,
`Type function () view external returns (int256) is not implicitly convertible to expected type int256.
		f[0] = s.b;
`
in line 39. What is the problem? How can I fix it?

**Comment by chriseth** [comment]
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
