### ISSUE TITLE
Compare test performance with different compilation modes (Debug, RelWithDebInfo, Release)

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#3890]

**Comment by leonardoalt** [comment]
I've compiled Solidity with the four different build options (Debug, RelWithDebInfo, Release and MinSizeRel) and here are the initial test results:

**Debug**
Soltest
real	0m4,265s
user	0m4,194s
sys	0m0,068s

cmdlineTests
real	1m41,135s
user	1m31,042s
sys	0m10,278s

**RelWithDebInfo**
Soltest
real	0m0,873s
user	0m0,832s
sys	0m0,041s

cmdlineTests
real	0m36,379s
user	0m26,417s
sys	0m10,172s

**Release**
Soltest
real	0m0,850s
user	0m0,754s
sys	0m0,096s

cmdlineTests
real	0m31,815s
user	0m26,635s
sys	0m5,395s

**MinSizeRel**
Soltest
real	0m0,964s
user	0m0,911s
sys	0m0,052s

cmdlineTests
real	0m34,061s
user	0m28,968s
sys	0m5,292s

I'm still not sure how they got `cmdlineTests` to run in 7s.

**Comment by chriseth** [comment]
I don't see a big improvement between RelWithDebInfo and Release, so I think we have to wait for a reply from the other team.

**Comment by axic** [comment]
What is this issue exactly about? That we should use `Release` in testing?

**Comment by leonardoalt** [comment]
There was a group of students who contacted us on Gitter about a project they were running, and they mentioned `Release` tests were several times faster than `Debug` tests, so I ran these. We haven't heard from them since then though.

**Comment by chriseth** [comment]
This was the pull request https://github.com/ethereum/solidity/pull/3929

**Comment by raphael-s-norwitz** [comment]
I was one of the students in the group.

I don't think we ever got all of cmdlineTests.sh to run in 7 seconds. From what I recall, we focused on the compile time of the various other contracts and libraries (corion, gnosos, zeppelin...etc) and the examples from the documentation. I just pulled the code twice in two separate directories and it seems it still takes about 26 seconds to build the other contracts and libraries when it is built with debug, vs about 7 seconds when it is built on release on my machine.

Happy to help you debug if this is still of interest.

**Comment by chriseth** [comment]
Ok this is weird - could you tell us more about your setup? Which compiler do you use, which platform, how do you compile and how exactly do you invoke the compiler?

**Comment by raphael-s-norwitz** [comment]
Sure. For `gcc -v` I get the following output:

```
raphael@raphael-laptop:<directory>$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
```
As for my setup I'm running Ubuntu 16.04 on a X86_64 machine (an HP Spectre laptop). Any other details you'd like?

Here's what I do to get the benchmark:

For compiling in Debug:

1. create a new directory
2. Navigate to that directory clone the repo
3. Follow the instructions on the build readme:
`mkdir build && cd build`
`cmake .. && make`
4. then I navigate to the `test/` directory, open `cmdlineTests.sh` and on line 106 change:
`compileFull *.sol */*.sol`
to
`time compileFull *.sol */*.sol`

Then I run `./cmdlineTests.sh` and here are the results I get for the libraries:
```
 - corion

real	0m12.879s
user	0m12.804s
sys	0m0.076s
 - gnosis

real	0m8.915s
user	0m8.856s
sys	0m0.064s
 - milestonetracker

real	0m1.012s
user	0m0.988s
sys	0m0.020s
 - MultiSigWallet

real	0m2.387s
user	0m2.364s
sys	0m0.024s
 - stringutils

real	0m0.125s
user	0m0.120s
sys	0m0.004s
 - zeppelin

real	0m2.668s
user	0m2.652s
sys	0m0.020s
```

Then to test Release, I create a new directory and repeat the same process except for step 3, as in `./scripts/build.sh` I run:

```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release && make
```

And I get the following results:

```
Compiling various other contracts and libraries...
 - corion

real	0m2.204s
user	0m2.132s
sys	0m0.076s
 - gnosis

real	0m1.547s
user	0m1.500s
sys	0m0.048s
 - milestonetracker

real	0m0.195s
user	0m0.176s
sys	0m0.016s
 - MultiSigWallet

real	0m0.424s
user	0m0.388s
sys	0m0.036s
 - stringutils

real	0m0.067s
user	0m0.064s
sys	0m0.000s
 - zeppelin

real	0m0.513s
user	0m0.496s
sys	0m0.020s
```

As I recall we repeated this on OSX and a GCP instance and saw the same results.

**Comment by chriseth** [comment]
Here are my numbers:
```
Debug:
- corion

real	0m10.512s
user	0m10.428s
sys	0m0.048s
 - gnosis

real	0m6.904s
user	0m6.848s
sys	0m0.052s
 - milestonetracker

real	0m0.850s
user	0m0.844s
sys	0m0.004s
 - MultiSigWallet

real	0m1.916s
user	0m1.896s
sys	0m0.016s
 - stringutils

real	0m0.143s
user	0m0.136s
sys	0m0.004s
 - zeppelin

real	0m2.044s
user	0m2.020s
sys	0m0.016s

RelWithDebInfo:

 - corion

real	0m1.561s
user	0m1.508s
sys	0m0.056s
 - gnosis

real	0m1.068s
user	0m1.024s
sys	0m0.044s
 - milestonetracker

real	0m0.138s
user	0m0.128s
sys	0m0.004s
 - MultiSigWallet

real	0m0.299s
user	0m0.284s
sys	0m0.012s
 - stringutils

real	0m0.046s
user	0m0.044s
sys	0m0.000s
 - zeppelin

real	0m0.344s
user	0m0.320s
sys	0m0.024s


Release:
 - corion

real	0m1.573s
user	0m1.508s
sys	0m0.068s
 - gnosis

real	0m1.055s
user	0m0.980s
sys	0m0.072s
 - milestonetracker

real	0m0.140s
user	0m0.136s
sys	0m0.000s
 - MultiSigWallet

real	0m0.303s
user	0m0.272s
sys	0m0.028s
 - stringutils

real	0m0.046s
user	0m0.044s
sys	0m0.000s
 - zeppelin

real	0m0.339s
user	0m0.324s
sys	0m0.016s
```

I assume the default build is Debug which explains the numbers by @raphael-s-norwitz . Since we run our tests and also do binary releases based on "RelWithDebInfo", I think this issue can be closed.
