### ISSUE TITLE
Not able to install the solidity compiler on windows

### ISSUE THREAD

**Issue by vidhyaramani** [ethereum/solidity#3908]
Truffle migrate: Error: No network specified. Cannot determine current network.

Also need the instructions to install the solidity compiler on windows. I have followed the https://solidity.readthedocs.io/en/v0.4.22/ this link but not working. Please need your answer.

Thanks in advance!

pragma solidity ^0.4.18;

 
contract Mycontract{
    mapping(uint=>address)public addresses;

}

**Comment by axic** [comment]
> Truffle migrate: Error: No network specified. Cannot determine current network.

This seems to be a problem with truffle, not solidity.

> Also need the instructions to install the solidity compiler on windows. I have followed the https://solidity.readthedocs.io/en/v0.4.22/ this link but not working.

Please provide logs otherwise there's no way to help.

**Comment by vidhyaramani** [comment]
Truffle v:4.1.3


Error:

```
truffle(develop)> migrate --reset
Compiling .\contracts\MetaCoin.sol...
Writing artifacts to .\build\contracts

Using network 'develop'.

Running migration: 1_initial_migration.js
Replacing Migrations...
... 0xbe08a360a53514f1751645230046ad03034f2ce3fc6ae2591ecfd34069c67e6a
Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving successful migration to network...
... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
Saving artifacts...
Running migration: 2_deploy_contracts.js
C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:66536
throw new Error("Could not find artifacts for " + import_path + " from any sources");
^

Error: Could not find artifacts for ./MetaCoin.sol from any sources
at Resolver.require (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:66536:9)
at Object.require (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:77630:36)
at ResolverIntercept.require (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:239478:32)

at C:\Windows\system32\metacoin\migrations\2_deploy_contracts.js:2:26
at Script.runInContext (vm.js:74:29)
at Script.runInNewContext (vm.js:80:15)
at C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:125917:14
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
```

Environment

    Operating System: Windows

    Truffle version (truffle version): truffle v 4.1.3

    node version (node --version):v9.9.0

    npm version (npm --version): v 5.8.0

@vidhyaramani

**Comment by axic** [comment]
This seems to be entirely a problem with truffle. Please raise an issue with them.

**Comment by vidhyaramani** [comment]
what can i do now? Please help me through this issue. Thanks!

**Comment by axic** [comment]
The best is to ask on truffle's support channels.

**Comment by vidhyaramani** [comment]
thanks!
