### ISSUE TITLE
Old- and new-style constructors are allowed at the same time

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3911]
Found by @yann300.

```
contract test {
    uint a;
    constructor () {
        a = 5;
    }
    function test () {
        a = 10;
    }
}
```

The above should raise an error of two constructors declared. Currently it compiles without warnings and whichever constructor was declared first takes precedence (the other is just ignored).

**Comment by chriseth** [comment]
Duplicate of https://github.com/ethereum/solidity/issues/3904

**Comment by chriseth** [comment]
Oh I'm sorry, confused this because I was working on both.
