### ISSUE TITLE
Add warning for a function named "constuctor"

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3915]
Found by @grigio & @yann300.

```
pragma solidity ^0.4.22;
contract MyContract {
    address me;

    // not run at init!!
    function constructor() public {
        me = msg.sender;
    }

    function getMe() public view returns (address) {
        return me;
    }

}
```

One can argue it is too easy to confuse `function constructor()` with `constructor()`.

**Comment by chriseth** [comment]
Note that this basically disallows any function called `constructor`, but I would say this is an acceptable limitation.

**Comment by leonardoalt** [comment]
I agree that this limitation is acceptable. I think it's worth it to lose one potential function name in order to ensure clarity.

**Comment by axic** [comment]
We already decided, at least for the time being, to lose another function name: the name matching the contract.

Both of these should also be documented properly. I don't think they are at the moment.

**Comment by wadealexc** [comment]
This was definitely needed in the new release. Good call!
