### ISSUE TITLE
Introduce pedantic mode

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3916]
with `pragma pedantic;`.

This could be a middle ground between having warnings which can be turned off. Opinionated warnings could go under the pedantic mode.

One such example is #3915.

**Comment by chriseth** [comment]
I'm not sure about this. Compiler warnings are mostly, but not only for the developers. If we enforce pedantic mode, then people cannot that easily be fooled by functions named 'constructor'.

**Comment by chriseth** [comment]
If we make it optional, then scammers just don't use it.

**Comment by pirapira** [comment]
With another mode, every design decision takes more time.
