### ISSUE TITLE
Constructor doesn't working as expected

### ISSUE THREAD

**Issue by satyamakgec** [ethereum/solidity#3921]
I have the simple contract 

    
    pragma solidity ^0.4.22;

    contract Demo22 {
    
    address public a;
    uint256 public b;
    
    constructor(address _a, uint256 _b) public {
        require(_a != address(0), "Address should not be zero");
        a = _a;
        b = _b;
    }
    
    function getValue() returns(address, uint256) {
        return(a,b);
    }
    }

Behaviour for constructor parameters
_a = 0, _b = 123
It get passed , I don't understand why It should fail as per the require condition. I am also giving the error message for the require but it doesn't print or provide any warning at the compilation time if I did not provide any message string in it.

And even I am not able to access the public variable directly or even not by the `getValue()` functions. It gives me a wired error `call to Demo22.a errored: Cannot read property 'length' of undefined`. 

Environment 
Javascript VM of Remix IDE

**Comment by chriseth** [comment]
This seems to be a problem with remix. The constructor properly reverts, but remix still reports the contract to be deployed. Can you report it there, please?
