### ISSUE TITLE
Improve output selection within evm in standard JSON output (do not return unrequested fields)

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereum/solidity#3930]
I've requested just: `evm.bytecode.object`, but I've got `evm.bytecode.object`, `evm.bytecode.opcodes`, `evm.bytecode.sourceMap`, `evm.bytecode.linkReferences`.

/Users/leonidlogvinov/Dev/0x/solidity/libsolidity/interface/StandardCompiler.cpp:536
```cpp
		if (isArtifactRequested(
			outputSelection,
			file,
			name,
			{ "evm.bytecode", "evm.bytecode.object", "evm.bytecode.opcodes", "evm.bytecode.sourceMap", "evm.bytecode.linkReferences" }
		))
			evmData["bytecode"] = collectEVMObject(
				m_compilerStack.object(contractName),
				m_compilerStack.sourceMapping(contractName)
			);
```

**Comment by axic** [comment]
Thanks! This is a known limitation. Also sub-matching of the requested items isn't supported either: https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/StandardCompiler.cpp#L139
