### ISSUE TITLE
Jumps are considered modifying the state according to ViewPureChecker

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3937]
```
RLP.sol:389:18: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
                 jumpi(end, eq(i, words))
                 ^----------------------^
RLP.sol:395:18: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
                 jump(tag_loop)
                 ^------------^
```

I am not sure whether this is good or bad. It is true it could jump to locations in the contract which have non-pure instructions, but that is really hard to control.

**Comment by chriseth** [comment]
It was done like that on purpose and the reason is as you describe. Jumps are discouraged anyway, so I think we are fine.

**Comment by axic** [comment]
I am fine with this, but it would be nice to have it properly explained in the documentation (if someone has the time to do it).

It can be closed when loose assembly is entirely removed, if nobody documents it until then.
