### ISSUE TITLE
Update the documentation to not generate any compiler warning.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3944]
We can utilize `test/cmdlineTests.sh` to find warnings in the documentation.

After this, we should also change this script to force no warnings.

**Comment by axic** [comment]
The first step here is to compile the documentation in strict mode, e.g. fail if there are any warnings. This can be done by adjusting `tests/commandlineTests.sh`.

Then all the appropriate warnings must be fixed.
