### ISSUE TITLE
Error:Operator != not compatible with types address and type(struct Metacoin.doctor storage pointer

### ISSUE THREAD

**Issue by vidhyaramani** [ethereum/solidity#3960]
function agreement(bytes32 hash)public returns(bool success){
    if(msg.sender!=patient&& msg.sender!=doctor)throw;
    if(msg.sender==patient&& msg.sender==doctor)data[hash].approvedBypatient=true;
    if(msg.sender==doctor)data[hash].approvedBypatient=true;

**Comment by axic** [comment]
This snippet is not enough to understand the problem. I suggest to check out https://ethereum.stackexchange.com or https://gitter.im/ethereum/solidity for quick help on programming questions.
