### ISSUE TITLE
Should tight packing report a warning for string or hex literals?

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3962]
None of these report an issue currently:
```
        function f() pure public returns (bytes32) {
            return keccak256("hello");
        }
        function g() pure public returns (bytes32) {
            return keccak256(hex"001122");
        }
```

(Issue from https://github.com/ethereum/solidity/pull/3956#pullrequestreview-114043230)

**Comment by chriseth** [comment]
I'm actually not sure we should have a warning here. The expectation would be that no padding is added. If that is the case, we do not need a warning.

**Comment by chriseth** [comment]
This works as expected and we have tests for it.

**Comment by axic** [comment]
For the record can you mention the test case names?

**Comment by chriseth** [comment]
`bytes_from_calldata_to_memory`, `sha3_multiple_arguments`, and especially `iterated_keccak256_with_bytes` and `keccak256_with_bytes`.
