### ISSUE TITLE
Difference between unused address vs address that used selfdestruct?

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#3966]
Is there a **difference between** an **address** that was **never used** to store a contract and an **address** that previously had a contract and **did a selfdestruct**?

**Comment by axic** [comment]
I think this is a better question for https://github.com/ethereum/yellowpaper.

Good question though, I haven't seen the latest version of the YP, but it may need more clarity regarding this.

**Comment by chriseth** [comment]
As a short answer: From inside the EVM, this distinction cannot be detect, although it is encoded differently in the state trie, as far as I know.
