### ISSUE TITLE
Solc: More output during builds.

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#397]
Not a big issue but it would be nice with more build output at some point. Making a big build now with optimizer can take minutes, and it is almost completely silent (unless there are errors). Some messages about which contract it is processing and such would be great.

**Comment by chriseth** [comment]
Minutes, that's embarassing. Would be great to get some examples so we can experiment a bit about performance.

**Comment by androlo** [comment]
I will submit something, although performance is not really the issue (to me). Large builds with hundreds of optimization runs takes some time, but the same non-optimized build can take less then a second. At least with the C++ version of the compiler. It would be nice with some more output at some point.

**Comment by androlo** [comment]
(for when it does take time)

**Comment by androlo** [comment]
Lots of building, hard to find minimal examples etc. I will analyze builds at some point and make a proper issue where I add some data, if that is helpful.

**Comment by axic** [comment]
@androlo did you manage to find an example exhibiting an excessive build time?

**Comment by androlo** [comment]
I didn't try. Would still like more fine grained logging and more output at some point, but I guess that doesn't really need its own issue. Closing.
