### ISSUE TITLE
Delegatecall not working in some cases

### ISSUE THREAD

**Issue by rmeissner** [ethereum/solidity#3983]
Hey,

I used the following example contracts in Remix:

```
pragma solidity ^0.4.17;

contract SomeContract {
    event CallMeMaybeEvent(address _from);
    function callMeMaybe() payable public {
        CallMeMaybeEvent(this);
    }
}

contract ThatCallsSomeContract {
    function callTheOtherContract(address _contractAddress) public {
        require(_contractAddress.call(bytes4(keccak256("callMeMaybe()"))));
        require(_contractAddress.delegatecall(bytes4(keccak256("callMeMaybe()"))));
        SomeLib.calledSomeLibFun();
    }
}

library SomeLib {
    event CalledSomeLibEvent(address _from);
    function calledSomeLibFun() public {
        CalledSomeLibEvent(this);
    }
}
```

(source: https://vomtom.at/address-call-vs-delegatecall-vs-libraries/)

When I select any compiler before 0.4.20 it will generate 3 events (if you call `ThatCallsSomeContract.callTheOtherContract` with the address of `SomeContract`). If I choose 0.4.20 or a newer compiler I don't have any event output.

I used the JavaScript VM of Remix to execute these calls.

EDIT: The transaction actually fails (somehow didn't see that in remix) ... still not sure why.

**Comment by rmeissner** [comment]
Sorry ... too late ... missed the library call change ... issue can be closed.

**Comment by axic** [comment]
> Sorry ... too late ... missed the library call change ... issue can be closed.

What do you mean by library call change?

**Comment by rmeissner** [comment]
I assume it was 
```
Code Generator: Prevent non-view functions in libraries from being called
directly (as opposed to via delegatecall).
```
but not exactly sure anymore, too long ago. If you want I can try to reproduce my issue :D 

EDIT: I cannot reproduce the issue :/ not sure what happened there :(

**Comment by axic** [comment]
No, that shouldn't apply here. It is still called via `SomeLib.calledSomeLibFun();` so the compiler will use `delegatecall`.
