### ISSUE TITLE
solc: exit status 1

### ISSUE THREAD

**Issue by miraggool** [ethereum/solidity#3984]
my env : 
windows 10, solc version : 0.4.22 + commit.4cb486ee.windows.msvc
geth version : 1.5.5-stable

when i compile solidity, error occured like this. 
Error: solc: exit status 1
unrecognised option '--add-std'

i tested simple command  on geth Console
> eth.compile.solidity("contract C{}") 

how can i fix this?

**Comment by chriseth** [comment]
The `--add-std` option was removed. Please update geth, the latest version is 1.8.6.
