### ISSUE TITLE
address sanitizer reporting potential memory leaks

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#3988]
After running `soltest` with enabled address sanitizer potential memory leaks are detected in `develop` branch, running on `Ubuntu 16.04.3 LTS`.  I also checked releases `0.4.23` and `0.4.21` with similar results.

# steps to reproduce
```
git clone https://github.com/ethereum/solidity.git
cd solidity
mkdir build
cd build
cmake -DSANITIZE=address ..
make
test/soltest -- --no-smt --no-ipc --testpath ../test
```

see [sanitizer.log](https://gist.github.com/aarlt/df2bfa7d6a33d6c72233d452edca6f96)

**Comment by chriseth** [comment]
Hm, these rather look like false positives to me. Could you try to check the compiler itself for memory leaks as opposed to the testing binary? I think it is enough to just run `test/cmdlineTests.sh`

**Comment by aarlt** [comment]
I ran `test/cmdlineTests.sh` with similar results.

see [sanitize-cmdlineTests.log](https://gist.github.com/aarlt/8c61e820f97f4c092f268ac239cc6ff1)

**Comment by chriseth** [comment]
Ah, that's actually much better!

**Comment by aarlt** [comment]
@chriseth nice!

**Comment by chriseth** [comment]
All of the errors shown above point to LValue, which is a polymorphic class that does not have a virtual destructor. Created https://github.com/ethereum/solidity/issues/3990 for that, so I think this can be closed.

**Comment by chriseth** [comment]
Thanks for checking, @aarlt !

Perhaps we should really setup asan as part of the CI, or at least as part of the fuzz testing we do from time to time.

**Comment by aarlt** [comment]
@chriseth i highly recommend this! if this fixes also all the other potential warnings within `soltest`, the best would be to compile `soltest` always with enabled `address sanitizer`, the `undefined behaviour sanitizer` may also be very usefull..
