### ISSUE TITLE
compiler using --standard-json doesn't error if incorrect version

### ISSUE THREAD

**Issue by ewingrj** [ethereum/solidity#3997]
If I try and compile a contract with `pragma solidity ^0.4.21` using the `--standard-json` option & solc version 0.4.18, the compiler will error complaining about the syntax for `emit MyEvent()` but with no mention that I am using an incorrect version of solc to compile the contracts.

I'm not sure if this is fixed in a more recent version or not

**Comment by axic** [comment]
That is weird and should not happen. ~~Are you sure you are using 0.4.18 ?~~

Tried it in Remix and the problem indeed seems to be present.

**Comment by axic** [comment]
Sorry, it is just the way the compiler works.

The version pragma is evaluated after the parsing stage and since the issue is a parser error, it doesn't even get to evaluate the version pragma.

**Comment by ewingrj** [comment]
I thought that might be the case. Thanks
