### ISSUE TITLE
String memory variable cause function to return no value

### ISSUE THREAD

**Issue by Pzixel** [ethereum/solidity#3998]
I'm writing a simple smart contract which loops over internal array and checks if strings are equal. It compiles fine but when I run this smart contract I get no value at all. I started my investigation and here is what I have found.

Consider following smart contract:

```
pragma solidity ^0.4.23;

contract Season {
    address[] public requests;
    mapping(bytes32 => address) requestIdToAddress;
        
    function createRequest(string id) public {
        bytes32 hash = keccak256(id);
        require(requestIdToAddress[hash] == 0);

        Request request = new Request(id);
        requests.push(request);
        requestIdToAddress[hash] = request;
    }

    function getRequestsCount() public view returns(uint) {
        return requests.length;
    }

    function getRequestById(string id) public view returns(address) {
        return getRequestByHash(keccak256(id));
    }

    function getRequestByHash(bytes32 hash) public view returns(address) {
        return requestIdToAddress[hash];
    }

    function getRequestsByFilter(string id) public view returns(uint, uint, uint, bytes32[]) {
        bytes32[] memory filteredRequests = new bytes32[](getRequestsCount());
        uint j = 0;
        for (uint i = 0; i < filteredRequests.length; i++) {
            Request request = Request(requests[i]);
            //string memory requestId = request.id();
        }
        return (filteredRequests.length, getRequestsCount(), j, filteredRequests);
    }    
}

contract Request {
    string public id;

    constructor(string id_) public {
        id = id_;
    }
}
```

Deploy it and call `createRequest(somevalue)`. Then call  `getRequestsByFilter(anyvalue)` and you should see `1 1 1 0x00..00`. Ok, it's good, it works fine.

However, try to uncomment `//string memory requestId = request.id();` line and repeat steps above. In this case this contract is still compiling, however trying to call it always leads to `0 0 0 null`. But this line shouldn't change observable behaviour?! Yes, it shouldn't, however, it does.

I consider it's either VM or compiler bug.

> solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Windows.msvc

**Comment by chriseth** [comment]
Are you sure you are running this on a byzantium-compatible blockchain?

**Comment by Pzixel** [comment]
I run it on parity. However, it seems just an error because of trying to access other's contract dynamic string method. However, It doesn't work with sized types too:

```
pragma solidity ^0.4.23;

contract Season {
    address[] public requests;

    constructor() public {
        requests.push(new Request());
    }

    function getRequestsByFilter() public view returns(bool) {
        Request r = Request(requests[0]);
        bool ret = r.isMatch();
        return ret;
    }
}

contract Request {  
    function isMatch() public pure returns(bool) {
        return true;
    }    
}
```

Here expected value is `true` but it's actually `false`.

![](https://i.stack.imgur.com/V15E4.png)

I'm not sure anymore if it's a compiler bug or just bad EVM, but I think we need at least some explanation here, like some warning or something.

**Comment by Pzixel** [comment]
I have found out that it's parity bug, others ethereum implementations works fine with this code.

**Comment by axic** [comment]
You can link to the Parity issue? It is useful for others finding this issue to be able to track what's going on.

**Comment by Pzixel** [comment]
Of course: https://github.com/paritytech/parity/issues/8503

It basically forbids any interacton between contracts, e.g. in provided example you cannot call `id()` function.

**Comment by axic** [comment]
Related to #4259.
