### ISSUE TITLE
Public View's in interfaces gives a warning

### ISSUE THREAD

**Issue by beether** [ethereum/solidity#4007]
I see the intent here, but it seems incorrect. There is a strong argument in favor of allowing `view`s in interfaces -- namely that it provides some degree of "view-safety" when calling implementors of that interface.

By forcing all functions to be `external`, you'll now get compiler warnings when calling implemented methods from within a view.

Here's an example:

```
pragma solidity ^0.4.23;

interface Viewable {
    function someView() external returns (uint);
}
contract Foo is Viewable() {
    function someView() public view returns (uint) {
        return 123;
    }
}

contract Test {
    Foo foo = new Foo();
    
    function getViewable(address _addr) public pure returns (Viewable) {
        return Viewable(_addr);
    }
    
    // compiler warns that .someView() may change state, and so testView() should not be a view.
    function testView() public view returns (uint) {
        return getViewable(address(foo)).someView();
    }
}
```

**Comment by chriseth** [comment]
I'm sorry, I do not yet understand the problem here. If you change 
```
interface Viewable {
    function someView() external returns (uint);
}
```
to
```
interface Viewable {
    function someView() external view returns (uint);
}
```
(add `view`) it compiles without warning.

**Comment by beether** [comment]
@chriseth I was unaware that both `view` and `external` could be used. I thought `external` implied that state could be changed.

**Comment by beether** [comment]
Not an issue.
