### ISSUE TITLE
Compiler appends seemingly random bytes

### ISSUE THREAD

**Issue by samczsun** [ethereum/solidity#4011]
I have a simple empty contract which should produce only a handful of opcodes:

```
pragma solidity 0.4.23;

contract Test {
    constructor() public payable {
        
    }
    
    function() public payable {
    }
}
```
After compilation (and deployment), I inspected the instructions generated for both the creation transaction and the actual contract in both Remix and on-chain.

Creation:
```
608060405260328060116000396000f30060806040520000a165627a7a72305820b94064798b96321951fc2a5895e46103b3591c0fa9ec74f72e9b713fdeaf1e960029
```
```
PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x32 DUP1 PUSH1 0x11 PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN STOP PUSH1 0x80 PUSH1 0x40 MSTORE STOP STOP LOG1 PUSH6 0x627A7A723058 KECCAK256 0xb9 BLOCKHASH PUSH5 0x798B963219 MLOAD 0xfc 0x2a PC SWAP6 0xe4 PUSH2 0x3B3 MSIZE SHR 0xf 0xa9 0xec PUSH21 0xF72E9B713FDEAF1E96002900000000000000000000 
```

Contract:
```
60806040520000a165627a7a72305820b94064798b96321951fc2a5895e46103b3591c0fa9ec74f72e9b713fdeaf1e960029
```
```
PUSH1 0x80 PUSH1 0x40 MSTORE STOP STOP LOG1 PUSH6 0x627A7A723058 KECCAK256 0xb9 BLOCKHASH PUSH5 0x798B963219 MLOAD 0xfc 0x2a PC SWAP6 0xe4 PUSH2 0x3B3 MSIZE SHR 0xf 0xa9 0xec PUSH21 0xF72E9B713FDEAF1E96002900000000000000000000 
```

It seems that in both cases, there are seemingly random bytes appended to the end of the instructions. I can't imagine what they might be for because there is only one basic block and execution stops at the first `RETURN`/`STOP`.

**Comment by axic** [comment]
It is the compiler metadata. Please see the documentation: https://solidity.readthedocs.io/en/v0.4.23/metadata.html

Please let us know if you think the documentation is inadequate in this matter and how it could be improved.
