### ISSUE TITLE
Compiler problem with local variable

### ISSUE THREAD

**Issue by Nitro888** [ethereum/solidity#4015]
![screen shot 2018-04-29 at 10 12 19 pm](https://user-images.githubusercontent.com/11692220/39407058-3cda427a-4bfb-11e8-8720-6d82221079ad.png)

what is this? It's normal case?

**Comment by chriseth** [comment]
You are not using the local variable `a`, yes, this is normal.

**Comment by Nitro888** [comment]
No that's not a point. variable a can use ariable b. before it define. and self initialize at define.

**Comment by chriseth** [comment]
Yes, this is intentional, fully documented  ("javascript scoping rules") and will be changed with version 0.5.0.
