### ISSUE TITLE
public function does not work in library

### ISSUE THREAD

**Issue by sjmini** [ethereum/solidity#4016]
The square function in contract "IntOpsUser" fails in remix with compiler version 0.4.23 and above.
I test it with both java VM and with my private network through Web3 provider.
It works correct only if I specify "internal" keyword in library function.
Is this correct behavior? It seems that library cannot have public function. 

```
pragma solidity ^0.4.23;

library IntOps {
  function square(int8 self) returns (int8) {
    return self*self;
  }
}

contract IntOpsUser {
  using IntOps for int8; 
  
  int8 public c = 3;

  function square(int8 a) returns (int8) {
    return c.square();
  }
}
```

**Comment by chriseth** [comment]
The root cause seems to be a bug in remix: https://github.com/ethereum/remix/issues/783

**Comment by axic** [comment]
Likely this was fixed. Please reopen if it still persists.
