### ISSUE TITLE
Run all tests on CircleCI on compiled as 32-bit Linux binary

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4027]
This requires compiling Solidity to a 32-bit target first.

**Comment by axic** [comment]
@ekpyron is Emscripten compiling to a 32-bit target or 64-bit? Couldn't find an answer in the docs. For the wasm output 64-bit makes sense, but for the asm.js output 32-bit makes more sense (given Javascript numbers are 53 bits).

**Comment by ekpyron** [comment]
Afaik browser wasm doesn't supports 64-bit anywhere atm - and I think both the wasm and asm.js builds are 32-bits - one of the windows builds might actually be as well.

**Comment by axic** [comment]
> Afaik browser wasm doesn't supports 64-bit anywhere atm - and I think both the wasm and asm.js builds are 32-bits - one of the windows builds might actually be as well.

Please note that wasm32 vs. wasm64 means 32-bit or 64-bit memory addressing. The instruction set is 64-bit in both cases.
