### ISSUE TITLE
Solc preprocessor

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#403]
Been using gpp to modify and add debugging code in contracts when test-running a somewhat big application. Debug version mostly includes things like a few extra solidity events, and using different values for some constants. It works somewhat well but it is hard since it has to pre-process every contract in the build hierarchy manually. An optional pre-processing step in solc would maybe be good at some point (or something to that effect).

**Comment by 0xdapper** [comment]
Why closed?
