### ISSUE TITLE
Improve loop detection in the gas estimator

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4030]
From https://www.pivotaltracker.com/story/show/95349770:

Currently, a loop is reported for any repeated PC. This is triggered already if the same function is called from two different places. The mechanism might be changed to
1. check from-to pairs or
2. store an ordered list of all past from-to pairs and break if this list ends in e.g. (abcd)(abcd), i.e. a repetition of four from-to pairs. This will not detect all loops, so we have to also check of some upper limit.

**Comment by chriseth** [comment]
I'm looking forward to doing gas estimation based on yul code - if that is possible with high accuracy.

**Comment by cameel** [comment]
Closing because we decided to remove the gas estimator from the compiler: #13566.
