### ISSUE TITLE
ParserError: Expected Identifier not found or not unique. function _(ITokenPorter)  {

### ISSUE THREAD

**Issue by bitcoinbotwin** [ethereum/solidity#4031]
ParserError: Expected Identifier, got 'Return' return_toatalSupply

**Comment by chriseth** [comment]
You are missing a `{` after `function (totalSupply) public constant returns (uint256) `.

**Comment by bitcoinbotwin** [comment]
@chriseth Thanks! I dug around for hours yesterday before finding that.
