### ISSUE TITLE
Improve Token class

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4035]
From https://www.pivotaltracker.com/story/show/82115102:

> Improve the token class such that we can get rid of most of the assertions and we can have C++ type guarantees that some token is e.g. an assignment operator.

**Comment by axic** [comment]
@chriseth is this mostly about removing the `assertDetails` for elementary types?

**Comment by chriseth** [comment]
The class `Assignment` in the AST has a member `Token m_assigmentOperator;`. It would be nice if the C++ compiler could guarantee that it can only receive a token that is a (compound) assignment operator. But I would not say that this issue is particularly important.
