### ISSUE TITLE
Optimizer bug

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/solidity#404]
When switching on the optimizer I get a bug in [this simple contract](https://gist.github.com/anonymous/38282f368a519070125c).

Procedure:
First call `setH` with the two arguments "test" and "bla", then call function `test` with the arguments "test" and "bbla". When the optimizer is switched off, this (correctly) returns 0 (false). When switching on the optimizer, I get an incorrect return value of 1 (true).

(I am using the [browser solidity compiler](https://chriseth.github.io/browser-solidity/))

Observations:
When changing the first argument to int (second remains string), then all works fine (with optimizer). When changing the order (first argument string, second int), it breaks again.

**Comment by chriseth** [comment]
The function in the following contract also fails (always returns true). If `sha256` is replaced by `sha3` or one of the arguments is replaced by a value type the problem goes away.

```
contract c
{
    function test(string s1, string s2) constant returns (bool)
    {
        return sha256(s1) == sha256(s2);
    }
}
```
