### ISSUE TITLE
Run bytecode comparison on macos in CI

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4044]

**Comment by cameel** [comment]
Is it just not implemented yet or are there some specific problems with running it on MacOS?

**Comment by chriseth** [comment]
Just not implemented.

**Comment by cameel** [comment]
This has now been implemented in #10039/#9931.

https://github.com/ethereum/solidity/blob/v0.7.4/.circleci/config.yml#L987-L1002
