### ISSUE TITLE
ParserError: Expected token Semicolon got 'LParen' function() allowance(address _owner, address _spender) _;

### ISSUE THREAD

**Issue by bitcoinbotwin** [ethereum/solidity#4050]
Error:

ParserError: Expected token LParen got 'Identifier'
    function allowance(address _owner, address _spender) _;

**Comment by chriseth** [comment]
Sorry, but this is not the correct place to ask for programming advice. Please use https://gitter.im/ethereum/solidity or ethereum.stackexchange.org

I think you meant `constructor(Token) (` instead of `constructor(Token) {`.
