### ISSUE TITLE
ABI: should disallow empty tuples and fixed length arrays of 0 members

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4069]
Currently the ABI allows tuples to have 0 members and fixed length arrays to be at fixed 0 length.

> The following (fixed-size) array type exists:
> `<type>[M]`: a fixed-length array of `M` elements, `M >= 0`, of the given type.

and

> `(T1,T2,...,Tn)`: tuple consisting of the types `T1, …, Tn`, `n >= 0`

I am not convinced it makes sense supporting these.

What are the arguments for having these?

**Comment by chriseth** [comment]
We at least need empty statically-sized arrays, because they are needed in the definition of the encoding of dynamically-sized empty arrays, and I think the statically-sized arrays in turn use tuples for encoding (or vice-versa), so I guess we could just keep all of them for completeness.

**Comment by danjm** [comment]
An issue in the ethereum/wiki repo that also questions the necessity of supporting fixed length arrays of 0 members: https://github.com/ethereum/wiki/issues/614

**Comment by chriseth** [comment]
A language is not required to support the full range of types documented in the ABI specification.
