### ISSUE TITLE
Enhancement large project: dataflow-style programming, Zilliqa style

### ISSUE THREAD

**Issue by jamesray1** [ethereum/solidity#4072]
See https://docs.zilliqa.com/whitepaper.pdf FMI.

Also mentioned in https://github.com/ethereum/vyper/issues/807.

**Comment by chriseth** [comment]
This seems to be a proposal for a new programming language or at least a new frontend for Solidity. While this might be a very good idea, it is out of scope for this issue tracker.

**Comment by jamesray1** [comment]
Is it out of scope? You could have an issue labelled as a long-term, high-level project/program and refer to it from the projects.

**Comment by chriseth** [comment]
Yes, it is out of scope because this would be a different project.
