### ISSUE TITLE
can not read byteN  in remix

### ISSUE THREAD

**Issue by zhuimengshaonian66** [ethereum/solidity#4076]
in this code , i  do it in : 
https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.23+commit.124ca40d.js

but  it return  0:0x.
i think it  cant read byte2's content , so   why?   what happend?
_________________________________________________________________________________________________________
pragma solidity ^0.4.16;

contract C {
        bytes2 public a=0x1234;
   function hexLiterBytes()public constant returns (bytes1){
   
       bytes1 jj = a[0];
       return jj;
    }
}

**Comment by chriseth** [comment]
This is a bug in remix / ethereumjs-vm which will hopefully be fixed soon: https://github.com/ethereum/remix/issues/783
