### ISSUE TITLE
Typo in Compiler Error Message

### ISSUE THREAD

**Issue by njwest** [ethereum/solidity#4078]
Fixed by #4077 

There is a grammatical error in the too many variables stack compilation error:

"Stack too deep, try using less variables." should be "Stack too deep, try using fewer variables."

Further explanation, with lines, etc, in Pull Request #4077

**Comment by chriseth** [comment]
Haha, this is great! So many people struggle with this error message, but nobody actually suggested to fix the grammar mistake in the text :) Thanks!

**Comment by njwest** [comment]
My pleasure, thank you for the great code!
