### ISSUE TITLE
magic happen in a function with delegateCall

### ISSUE THREAD

**Issue by idotial** [ethereum/solidity#4080]
here's my code of test.
```
pragma solidity ^0.4.21;
contract D {
  uint256 public n;
  uint256 public i;
  address public sender;
  address public isender;
  bool public result;
  
  event LogInputN(uint256 _n);

  function delegatecallSetN(address _e, uint256 nst) public {
    i = nst;
    isender = msg.sender;
    result = _e.delegatecall(bytes4(keccak256("setN(uint256)")), nst); // D's storage is set, E is not modified
    emit LogInputN(nst);
  }
  
  function outerCall(uint _n) public {
    i = _n;
  }
}

contract E {
  uint256 public n;
  address public sender;
  event setNLog(address, uint256);

  function setN(uint256 _n) public {
    n = _n;
    sender = msg.sender;
    // msg.sender is D if invoked by D's callcodeSetN. None of E's storage is updated
    // msg.sender is C if invoked by C.foo(). None of E's storage is updated
    emit setNLog(sender, _n);
    // the value of "this" is D, when invoked by either D's callcodeSetN or C.foo()
  }
}
```

i deploy E and then deploy C and run the delegatecallSetN function with address of E. here is my log
```
[
	{
		"topic": "0x22ee5a26ec362b4ed0545268cdc6d61c106b03827d89b4015735a924c302085b",
		"event": "setNLog",
		"args": [
			"0x555312850b2151d13313d32249b4f83bcf26d8e5",
			"14"
		]
	},
	{
		"topic": "0x475a8950a30bab904d14c8568aa0131d4292fa32b085d91df69e9a2e654e2ef8",
		"event": "LogInputN",
		"args": [
			"14"
		]
	}
]
```
the log seems right, but in Contract D, i appear to be 0: uint256: 487116790665000486649457261411995878465095522533, and n is 14, even i change the function to be
```
  function delegatecallSetN(address _e, uint256 nst) public {
    i = 1234;
    isender = msg.sender;
    result = _e.delegatecall(bytes4(keccak256("setN(uint256)")), nst); // D's storage is set, E is not modified
    emit LogInputN(nst);
  }
``` 
the i is still a very big number, however if i delete the delegatecall in the function, then every thing work fine.
???????why this happen?or what's happening?

**Comment by idotial** [comment]
after some test, i think it because the variable n get longer after delegatecall, but the contract E don't know about the other uint i, some the position of i didn't move back. if i change the order of variables from `uint256 public n;
uint256 public i;
address public sender;
address public isender;`
to `  uint256 public n;
  address public sender;
  uint256 public i;
  address public isender;`
then every thing work fine……
i just think a lot contract might have this issue

**Comment by chriseth** [comment]
Please understand the implications of the low-level `delegatecall` before using it. This might help: https://solidity.readthedocs.io/en/latest/miscellaneous.html#layout-of-state-variables-in-storage

If you do not want to dig that deep, please use libraries instead.

**Comment by idotial** [comment]
I know it has a reason, but i just feel it's a bug and should be fixed

**Comment by chriseth** [comment]
@idotial the only fix I can think of is removing low-level access to the EVM (and this includes the `delegatecall` function on the `address` type). Can you think of a better fix?
