### ISSUE TITLE
Transfer event position

### ISSUE THREAD

**Issue by cytl5yy** [ethereum/solidity#4086]
function transferFrom(address _from, address _to, uint256 _value)  returns (bool success) {
        require(balanceOf[_from] >= _value);
        balanceOf[_to] += _value;
        emit Transfer(_from, _to, _value);
        balanceOf[_from] -= _value;
        return true;
    }
 I‘m not sure the event  Transfer must be under the   balanceOf[_from] -= _value;   Or there is nothing wrong with the writing of the upper function？

**Comment by chriseth** [comment]
The place of the event should in general not matter, but this question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
