### ISSUE TITLE
Allow enums in interface

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4087]
I believe this was raised previously a couple of times and it is handled as part of the inheritance discussion (#3729).

I'd however propose to make an exception and allow this simple change outside of concluding that discussion, right now.

Are there any reasons for disallowing it? I remember we disallowed it out of fear something might break (or rather lack of time to check everything) and probably `enum`s weren't supported to be used from a foreign contract making it less useful.

However, as of today this should be working (granted `bool TypeChecker::visit(EnumDefinition const& _enum)` is removed in the type checker):
```
  enum X { A, B, C }
  function x() returns (I.X);
}

contract C is I {
  function x() returns (I.X) { return f(); }
  function f() returns (I.X) { return X.B; }
}
```

It also seems the output has the proper enum values after compilation.

**Comment by chriseth** [comment]
I think it is fine to allow both enums and structs in interfaces.

**Comment by chriseth** [comment]
I was never aware of any problem, we just wanted to restrict interfaces as much as possible.

**Comment by axic** [comment]
I think it was rather lack of time to properly evaluate the implications and to get a basic version of interfaces out.

**Comment by chriseth** [comment]
We should also allow structs.

**Comment by axic** [comment]
I am working on this now.

**Comment by chriseth** [comment]
Documentation change is missing.
