### ISSUE TITLE
Always use staticcall for pure (not only in 0.5.0 mode)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4089]
When we introduced to use `STATICCALL` for `view` and `pure` we enabled that for 0.5.0 only, in order not to break non-compliant `view`/`constant` functions.

However we never made such a commitment for `pure`, since it was newly introduced, so we could have enabled `staticcall` for that unconditionally.

**Comment by axic** [comment]
@chriseth what do you think about this?

**Comment by chriseth** [comment]
We could do it, but it might also just increase complexity and it might break some contracts because of incorrect explicit conversions between contracts. Perhaps it is better to wait for 050.

**Comment by axic** [comment]
We missed to put this onto the 0.5.0 project.
