### ISSUE TITLE
Consider wording for assert (and require) explanations

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4099]
From https://github.com/ethereum/solidity/pull/4082/files#r186545745

**Comment by androlo** [comment]
If I understand correctly, 'reverts' and 'exceptionally aborts' is the right terms now. I can comb through all docs and see where it should be replaced and then PR.

**Comment by axic** [comment]
I think they are the right one, but we could brainstorm here a bit about them.

**Comment by ChrisChinchilla** [comment]
Closed by https://github.com/ethereum/solidity/pull/6846
