### ISSUE TITLE
Introduce new keywords

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#410]
New keywords for inline assembly and fixed point types should be introduced with the 0.3.0 release. These include:

`fixed`, `ufixed` and their `MxN` variants.
`assembly`
`inline` (for future use)

**Comment by LianaHus** [comment]
FYI I'm assigning this task to myself.
to  @chriseth: Unfortunately for some reasons currently I don't have access to solidity repo :)

**Comment by chriseth** [comment]
@LianaHus please ask @VoR0220 for a partial PR of his that only includes the `fixed` / `ufixed` keywords. Make sure to align merging these changes as close to the switch to version 0.3.0 as possible.

**Comment by VoR0220** [comment]
https://www.youtube.com/watch?v=y9IcGZZnC1k
