### ISSUE TITLE
Consider showing a warning when pragma & compiler versions are different

### ISSUE THREAD

**Issue by alex-ppg** [ethereum/solidity#4103]
Using a different compiler version than the one specified with the `pragma` keyword can result in unintended behavior as the `pragma` keyword is ambiguous. As such, it would be best to show a **warning** for those who want to heed it and ensure backward compatibility. An example scenario can be found below:
- Which version of Solidity are you using?
The compiler is running Solidity version 0.4.23.
- What was the source code?
```
pragma solidity ^0.4.1;

contract StringTest {
    event A();
    
    constructor() public {
        emit A();
    }
}
```
- Which platform are you running on?
Irrelevant.
- How to reproduce the issue?
Attempt to compile the above contract with Solidity 0.4.1.
Proceed to compile the above contract with Solidity 0.4.23.
- What was the result of the issue?
The compiler failed to compile the code with Solidity 0.4.1 but succeeded with version 0.4.23.
- What is the expected behavior?
The compiler, when writing code using version 0.4.23, should show a **warning** suggesting that you alter your pragma version to match your compiler version.

This can be done simply by checking if the `^` keyword exists in `pragma` and if it does check whether the version is lower than the compiler. Showing an ***error*** instead of a ***warning*** would require that the compiler has knowledge of previous versions and available features which would unnecessarily increase its complexity.

**Comment by Schaeff** [comment]
I agree with @axic that this may be a issue with the warning message itself: in some cases, warnings suggest changes which would make the code invalid on versions of the compiler which should be compatible as stated in the pragma statement. One should either check all versions in the range for support of the suggested change, or warn that the change may break the code on earlier versions.

It's important because if fixing warnings can in some cases break my code, I'm more likely to just never fix them at all.

**Comment by axic** [comment]
The problem at hand here is, which should be an exception, is that `emit A();` causes a parser exception in <0.4.23 and as a result we cannot evaluate the version pragma, which is done at a later stage, to show a proper error: "you are using a too old compiler".

I guess we could add some workaround or put effort into fixing this, but as we are trying to move on to 0.5.0 it may not be worth the effort. It definitely should be taken as a learning though.

An entry in the documentation probably would be very welcome though, where `emit` is explained.

**Comment by alex-ppg** [comment]
The problem is not limited to the `emit` keyword. You can use `pragma solidity ^0.4.0` and it will still allow you to use all features of `0.4.24` such as the `constructor()` identifier or a message with the `require` keyword. **A warning definitely needs to be added during compilation**.

**Comment by chriseth** [comment]
If you are testing your contracts with version `0.4.24`, you should also use the `^0.4.24` pragma. Furthermore, if you want your contracts to work for `^0.4.0`, then you should read the `0.4.0` documentation and not the latest version of the documentation.

I don't see a problem here apart from the misleading warning @axic mentioned.

**Comment by alex-ppg** [comment]
@chriseth I believe you have misunderstood. The ***misleading warning*** @axic mentioned does not exist, he theorized how my issue could be solved. The whole purpose (and title) of this issue is the presence of the warning which does not currently exist.

Furthermore, a lot of boilerplate code exists with older `pragma`s and even the default contract shown by the Remix IDE is using `pragma solidity ^0.4.0`.

**Comment by chriseth** [comment]
@alex-ppg I think we still have a misunderstanding. `pragma solidity ^0.4.21;` is a statement from the author of the code that this code is supposed to be compiled with the solidity compiler in a version between 0.4.21 and 0.5.0 (exclusive). This probably means that the author uses a feature that was added to the compiler in version 0.4.21. If you use `^`, then you should be pretty safe from your contract changing semantics with newer solidity versions unless we screw up. Because of that, `^` is the recommended way of using the pragma. You can also use `pragma solidity 0.4.21;` if you want to force an exact version.

Adding a warning whenever we do not have an exact match would remove this flexibility from the code author.

In my opinion, the problem in the initial code example you showed is that the author did not use the correct compiler version when he or she initially wrote the code, but the compiler cannot distinguish between the situations where it was initially run by the author or at a later time by someone else.

**Comment by alex-ppg** [comment]
Since the `^` keyword is used, any compiler above or at that version is deemed correct otherwise it wouldn't compile. 

A programming language is supposed to be clear & self explanatory in its keywords. If I see the line below as a programmer:
```
pragma solidity ^0.4.0;
```
I expect whatever follows to compile from version 0.4.0 and on-wards. Since Solidity is a statically-typed language, I find it very ambiguous for code to note "*You can use Solidity version 0.4.0 and up*" while in reality I can only use Solidity version 0.4.X and up, which X I need to "brute-force" by trying the different compilers.

The issue I have opened above was reported on the Solidity Gitter chat, it is not strictly an opinionated view but if you deem my reasoning illogical feel free to close this issue.

**Comment by chriseth** [comment]
OK, I see. So I think this is a misunderstanding about what `pragma solidity` does. You assume (which is probably what it ideally should be) that it configures the compiler into a certain mode, while it actually is much closer to what you would do in C with `#ifdef GNU_VERSION_AT_LEAST_X`. We should clarify that in the documentation. Your desired behaviour would result in far too big complexity in the compiler and thus would be dangerous to implement at this stage of evolution of the language.

**Comment by alex-ppg** [comment]
@chriseth 
> We should clarify that in the documentation. Your desired behaviour would result in far too big complexity in the compiler and thus would be dangerous to implement at this stage of evolution of the language.

My desired behaviour can be observed in the following pseudo-code:

```js
if (contractVersion < compilerVersion) {
    showWarning("You are using a higher compiler version than the one specified by the 'pragma' keyword, your code may not compile at an earlier version. Consider using 'pragma solidity ^" + compilerVersion + ";' to avoid compatibility issues.");
} else if (contractVersion == compilerVersion) {
    // ...
} else {
    // ...
}
```

If the `pragma solidity` keyword does not exist within the contract, your compiler already suggests using the current compiler version as the one for it. Additionally, the warning is worded as such:

> Warning: Source file does not specify required compiler version!

Further contributing to the fact that the `pragma solidity` keyword with the `^` character denotes "*This smart contract requires you to use a compiler versioned at or above the one specified by the `pragma`*" which is false, as your contract requires you to use a higher compiler version based on the keywords used within.

I am not suggesting scanning the contract itself for features that do not exist in the `pragma` specified, **I am suggesting simply comparing the compiler version and contract version and if the compiler is at a higher version, show a warning**. I do not really see the dangerous complexity in that.

**Comment by axic** [comment]
To clarify, based on your last comment, you would like to issue a warning if the compiler used is a version above the required minimum stated by the pragma?

**Comment by axic** [comment]
> The misleading warning @axic mentioned does not exist, he theorized how my issue could be solved. 

I'm not sure what you mean, but what I described indeed does exists.

**Comment by axic** [comment]
> The problem is not limited to the emit keyword. You can use pragma solidity ^0.4.0 and it will still allow you to use all features of 0.4.24 such as the constructor() identifier or a message with the require keyword. A warning definitely needs to be added during compilation.

I am getting the feeling that what you actually need is a module in the Remix static analyzer (cc @soad003) which suggests the correct minimum version after considering all the language features used in the given snippet.

**Comment by alex-ppg** [comment]
> To clarify, based on your last comment, you would like to issue a warning if the compiler used is a version above the required minimum stated by the pragma?

Although your wording makes it sound illogical that is correct. The warning simply suggests that there may be incompatibility issues and is a simple workaround to scanning the actual code for features not existent in the minimum version specified by the pragma.

> I'm not sure what you mean, but what I described indeed does exists.

The warning you refer to states "You are using an old compiler". What the warning proposed on this issue will trigger when **you are using a newer compiler**.

> I am getting the feeling that what you actually need is a module in the Remix static analyzer (cc @soad003) which suggests the correct minimum version after considering all the language features used in the given snippet.

This is the full-fledged solution which would solve this issue completely. This feature could also be implemented in the Solidity compiler directly as well.

**Comment by axic** [comment]
> The warning you refer to states "You are using an old compiler". What the warning proposed on this issue will trigger when you are using a newer compiler.

What I state is that due to the having a parser exception earlier in the process, the compiler is not able to output a proper message explaining an old compiler is used. Please also consider trying out different examples and cases to see what the compile actually does when creating a feature proposal 😉 

> This is the full-fledged solution which would solve this issue completely. This feature could also be implemented in the Solidity compiler directly as well.

It actually cannot be implemented in the compiler, because it doesn't offer an option to disable such suggestions and given users consider warnings as errors in many cases, it would be detrimental forcing them to tackle these suggestions. The Remix static analyzer is filling this exact gap.

**Comment by alex-ppg** [comment]
I still believe that the following is ambiguous:
```
pragma solidity ^0.4.0;
contract Test {
    event A(uint256 test);
    constructor() public {
        emit A(32);
    }
}
```
The first line indicates "Use at least version 0.4.0 or above" while the code itself won't compile at 0.4.0.

It seems though that I am either not able to convey my reasoning correctly or my view is not shared and as such I am closing this issue since it has been re-phrased at #4149.

**Comment by axic** [comment]
It is a user error to use `^0.4.0` for that given snippet. If there are examples in the documentation which suggest this, then please tell us as they should be fixed. Also do not hesitate to report that to other sources of documentation or tutorials. (Perhaps the default ballot example in Remix has this problem?)

Once implemented, the Remix static analyzer can suggest the user the proper versions needed.

I am still a bit confused what misunderstanding is left?

**Comment by alex-ppg** [comment]
It is a user error, but so is `uint256 a = -1`. I personally believe that the user should be instructed to use the latest compiler version in the `pragma` keyword. Although there is an error as you said within the above code snippet, it isn't noted anywhere by the compiler so *why* is it an error if the compiler treats it as perfectly fine?

**Comment by alex-ppg** [comment]
I believe what I may have misunderstood is that the `pragma` keyword is syntax strictly for the pre-wrapper of the compiler and not for the compiler itself (Converting the code to EVM OPCODEs). In that case I can understand why you label it as a user error but I still believe a warning would be a good addition to the pre-wrapper (Or more suited to the static analyzer as you mentioned).
