### ISSUE TITLE
Replace all GLOBs in CMake files.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4105]
The ``CMakeLists.txt`` files should be updated and all ``file(GLOB ...)``'s should be replaced by lists of filenames (potentially split into ``CMakeLists.txt``'s in subdirectories).

This came up before (I haven't found an issue for it, though) and I now noticed it again, since the ``develop`` branch contains a file that the ``050`` branch does not contain and switching between them breaks the build unless ``cmake`` is re-run. Using explicit lists of source files will allow ``make`` to deal with added and removed source files without the need for running ``cmake`` again.

**Comment by axic** [comment]
@christianparpart I think you did these?

**Comment by ekpyron** [comment]
There's at least some ``GLOB``'s left in ``test/``. Also I think we haven't found a definite agreement on whether to include all headers to the targets - I'm very much in favour to do so, since it'll make life much easier for IDEs.

**Comment by christianparpart** [comment]
So. The last one GLOB remained on purpose. Also, now, after talking with @ekpyron, we concluded that we close *this* ticket nevertheless. We want to overall-improve the test infrastructure (a few files compiled multiple times shouldn't happen e.g.), and then we can also remove that last GLOB.
