### ISSUE TITLE
Yul: allow dot (.) as part of an identifier

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4108]
From https://github.com/ethereum/solidity/pull/3238#discussion_r153902771:

How about introducing dot and/or hashmark as part of valid identifiers, such as `lt.u256` and` lt#u256` would be valid identifiers.

The downside is that currently even for assembly some parts of the Solidity parser are shared and that could cause an issue with dot, since in Solidity it has a different purpose.

**Comment by chriseth** [comment]
I don't think this is a big deal, the identifier parser for assembly would just peek for `.` and continue aggregating. This is similar to a path in solidity.

**Comment by chriseth** [comment]
This is also required for #5358
