### ISSUE TITLE
Gas warning for fallback function

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#411]
https://www.pivotaltracker.com/story/show/114641125

**Comment by axic** [comment]
@chriseth The gas estimator output includes an estimate for the fallback.  I think this issue is more suitable for the static analyzer, which could issue a warning if the estimate is above 2300.

**Comment by axic** [comment]
Is this still needed or covered by the remix static analyzer?

**Comment by chriseth** [comment]
This has been implemented in the remix static analyzer.

**Comment by chriseth** [comment]
Perhaps to document here: The reason we did not add it to the compiler itself is because gas estimation can only be done after we have the final code and at that point, it is hard to generate an error or warning.

**Comment by axic** [comment]
I think this can be done in a manner similar to #8008.

**Comment by axic** [comment]
The reason it may not be a good idea to add:
1. the gas estimator may not be correct at all times
2. if the warning cannot be switched off, users could be annoyed if it is intentionally using more
3. if we are trying to demote the send/transfer process, may be it is not important to highlight this (as we would suggest users to always send appropriate gas)

**Comment by chriseth** [comment]
I think this is outdated by now.
