### ISSUE TITLE
Exponentiation Error “TypeError: Type rational_const”

### ISSUE THREAD

**Issue by iumag** [ethereum/solidity#4118]
I can not get the answer of the expression

`int256 test2 = ((0.0035+1)**120)*(10**18);`

> TypeError: Type rational_const 2021...(389 digits omitted)...2001 / 1329...(371 digits omitted)...0000 is not implicitly convertible to expected type int256. Try converting to type ufixed256x58 or use an explicit conversion.

`int256 test2 = ((0.0035+1)**4)*(10**18);`

> This expression does not give an error

**Comment by chriseth** [comment]
The compiler thinks that the first number is not an integer, it has 58 decimal digits after the comma. Is that correct?

**Comment by iumag** [comment]
Yes, but is this expression not to be equal to 1520845926296400000?

**Comment by chriseth** [comment]
It looks correct to me. The glorified calculator also does not think it is an integer, although it has some weird numbers: https://www.wolframalpha.com/input/?i=((0.0035%2B1)**120)*(10**18)

Why do you think it is integer?

**Comment by iumag** [comment]
https://www.wolframalpha.com/input/?i=1.5208459262963889506832058380746608320809993017800259+×+10%5E18&lk=1&rawformassumption="ClashPrefs"+->+%7B"Math"%7D

Decimal form 1520845926296388950.6832058380746608320809993017800259

For this, I multiply by 10 ^ 18 to get the whole part of this expression. Maybe I do not understand something correctly, but if after multiplying by 10 ^ 18 I should not get 1520845926296388950?

**Comment by chriseth** [comment]
Note the `...` after `259`. The following already seems to be not integer anymore: `((0.0035+1)**14)*(10**18)`

**Comment by iumag** [comment]
How then to carry out such trivial calculations in Solidity?
I think that when multiplying by 10 ^ 18, I should get 1520845926296388950

For example: 

```
let a = Math.pow(0.0035+1,120);
let b = c *Math.pow(10,18);
```

return 1520845926296388950

**Comment by chriseth** [comment]
Are you doing that in javascript to cross-check? Javascript only has a limited precision, so the result has to be Integer, because the precision in a is cut off. In Solidity, expressions only involving constant literals have unlimited precision.

**Comment by chriseth** [comment]
If you want to force truncation, you can use an explicit type conversion to `int256`: `int256 test2 = int256(((0.0035+1)**120)*(10**18));`

**Comment by iumag** [comment]
This method causes UnimplementedFeatureError: Not yet implemented - FixedPointType.

**Comment by chriseth** [comment]
I'm sorry but it seems that you have to do the calculations somewhere else.

**Comment by iumag** [comment]
```
        int256 coefficient = int256(((percent+10000))*10**18);
    
        for (int i=0;i<month-1;i++){
            coefficient = coefficient * int256(((percent+10000))*10**14) / 10**18;
        }

```

I had to calculate it this way. It turned out almost perfect

**Comment by chriseth** [comment]
The code you give might provide a different result due to rounding errors.
