### ISSUE TITLE
Error encoding arguments

### ISSUE THREAD

**Issue by rayenrejeb** [ethereum/solidity#4119]
Hello,
My contract was running well one month ago, and now new errors show up when I want to insert bytes16, bytes32... A new error shows up :
Error encoding arguments: Error: invalid bytes16 value (arg=undefined, type="string", value="Something")
I try to insert the value between " " as I used to do.  But if i try to change type to String it works but with infinite gas estimation which is normal.
Is there a a reason for this issue ? I'll appreciate any help.

(I'm using testrpc for developing)

**Comment by erak** [comment]
@rayenrejeb Could you please provide the contract that's breaking for you? 

> (I'm using testrpc for developing)

It would be also very helpful to see the JSON-RPC call (if I got that right from your question) that is triggering this behavior.

**Comment by chriseth** [comment]
@rayenrejeb this very much looks like a change in testrpc as opposed to solidity. Did you change the compiler version or the version of testrpc?

**Comment by axic** [comment]
This seems to be a Remix issue. They have changed their ABI encoder, which may be more or less strict in cases.
