### ISSUE TITLE
No struct params for interfaces

### ISSUE THREAD

**Issue by Astrovicis** [ethereum/solidity#4123]
I want to use ABIEncoderV2 to allow a few more params in some of the more involved functions of our smart contract system. We're using interfaces to connect things but (as is documented) we can't use structs in interfaces. In my head this was fine because I assumed I could instead use an abstract contract i.e.

```
pragma solidity ^0.4.23;
pragma experimental ABIEncoderV2;

contract iContract
{
  struct objectParams
  {
     uint256 aMember;
     uint256 anotherMember;
     address[] yetAnotherMember;
     uint256[] distributionforAboveMember
     address[] moreAddresses;
  }

  function createObjectInSystem(objectParams params) external returns (address _objectAddress);
}
```

but when I try to compile this along with its corresponding contract (which doesn't inherit from it because that would cause a struct redefinition error), I get the following 

```
UnimplementedFeatureError:
Compilation failed. See above.
```

Which...yeah. I just need some way to pass in a few more parameters than I'm currently allowed and it doesn't seem like there's a very good way to do it right now. I'm thinking I'm going to have to change that signature to 

```
function createObjectInSystem(bytes params) external returns (address _objectAddress);
```

and manually encode the parameters on the frontend just to get things working. This is opaque though and will require assembly to parse. I don't want to go this route but I feel like I will likely need to.

Halp :(

**Comment by chriseth** [comment]
ABIEncoderV2 does not yet support external functions, so changing it to `public` should work.

**Comment by chriseth** [comment]
Please reopen if this did not help.

**Comment by Astrovicis** [comment]
This helped. Thank you!
