### ISSUE TITLE
solc: "Assembly exception for bytecode" compilation error if parent contract method called in constructor

### ISSUE THREAD

**Issue by ByKraB** [ethereum/solidity#4126]
> Which version of Solidity you are using

0.4.23

> What was the source code (if applicable)

```
pragma solidity 0.4.23;

contract B {
	function doSomethingB() public pure returns (bool) {
		return true;
	}
}

contract A is B {
	mapping(uint => uint) testData;

	constructor() public {
		doSomethingA(); // error
//		doSomethingInternal(); // compiled without errors
//		super.doSomethingB(); // error
	}

	function doSomethingA() public pure returns(bool) {
		return super.doSomethingB();
	}

	function doSomethingInternal() public {
		testData[0] = 42;
	}
}
```

> Which platform are you running on

mac os 10.13.4

> How to reproduce the issue

Call in terminal `solc ContractName.sol`

> What was the result of the issue

```
Internal compiler error during compilation:
/tmp/solidity-20180512-37913-1rgxue/solidity_0.4.23/libsolidity/interface/CompilerStack.cpp(732): Throw in function void dev::solidity::CompilerStack::compileContract(const dev::solidity::ContractDefinition &, map<const dev::solidity::ContractDefinition *, const eth::Assembly *> &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Assembly exception for bytecode
[dev::tag_comment*] = Assembly exception for bytecode
```
> What the expected behaviour is

Successful compilation

P.S:
solc-js compiles this code without  problems.
I tested the contract in Remix and it works fine so it is 100% valid code;

**Comment by chriseth** [comment]
@bit-shift told me that this might have been fixed already in https://github.com/ethereum/solidity/pull/3999 and actually this is very likely because you have a constructor that calls a local function.

**Comment by chriseth** [comment]
@ByKraB to check if it is fixed, you can try this binary here: https://12908-40892817-gh.circle-artifacts.com/0/solc

**Comment by ByKraB** [comment]
@chriseth, binary works fine. thanks for quick answer.
