### ISSUE TITLE
On readthedocs, Interface restrictions use ordered list, while Library restrictions use unordered list.

### ISSUE THREAD

**Issue by ahester57** [ethereum/solidity#4134]
Simply an inconsistency. I believe it would be better practice to be consistent with lists, especially lists in separate sections relating to the same concept.

It would be a simple change and it would prevent people like me from creating issues about inconsistencies in the docs.

https://solidity.readthedocs.io/en/v0.4.21/contracts.html#libraries

**Comment by wjmelements** [comment]
https://github.com/ethereum/solidity/pull/4202

**Comment by ChrisChinchilla** [comment]
This was closed by https://github.com/ethereum/solidity/pull/4202
