### ISSUE TITLE
`delete` to shrink array if last item is deleted

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#414]
Currently delete will just zero out the elements of an array.

Would it make sense to reduce the array size if the last element is being deleted? At least in terms of the ABI response the size field could be different to the storage size. **Update**: I assume it is not being done because that would mean an extra SSTORE call, which increases the cost.

Alternatively would a specific method make sense which upon deleting an item, will move the rest of the array back? e.g. after deleting item 3 in [1, 2, 3, 4] would result in [1, 2, 4]

I assume that would cost more gas, but would eliminate gas usage in other parts of the code when checking for empty items or transforming arrays for the same reason.

**Comment by ethernomad** [comment]
.pop() maybe?

**Comment by axic** [comment]
Sounds good.

I there are two questions now:

1) Is the above assumption regarding `delete()` correct? i.e. the size is not updated because that would be a second SSTORE.

2) Would it be possible to include a new operation (e.g. `pop()`)?

**Comment by ethernomad** [comment]
I think delete on an individual item just zeros out the data and gives you the refund.

It's best to design your contracts to avoid re-arranging of data so that they remain scalable.

A new operation would be up to chriseth

**Comment by VoR0220** [comment]
There's been a lot of concern about the deletion of individual portions of an array because of the scalability and cost prohibitive issues surrounding it. That's what I'll say on the matter.

**Comment by axic** [comment]
The way `delete` works has its reasons and should be better documented (so no one else will raise another issue).

Adding `pop(index)` I think would be nice. The implications must be properly documented and it should only be used when it makes sense.

**Comment by VoR0220** [comment]
hmmmm...sounds like we're talking a conversion from storage to memory of one variable and erasing a storage variable....that might get expensive.

**Comment by chriseth** [comment]
Using `delete` to shrink arrays changes semantics for this special case, so is not a good option. Introducing `.pop()` might make sense, though, but I think it is better to provided that on a higher level data structure by the use of libraries.

**Comment by axic** [comment]
It certainly can be implemented using Solidity itself. I assume it would use way less gas when implemented in the language (and having fully understanding of the storage layout).

Would inline assembly give access to all that?

**Comment by chriseth** [comment]
@axic indeed, inline assembly will be used in such a library. The goal is to provide all information that is available in the compiler also to the inline assembly snippet (this mainly concerns storage sizes of types and similar things).

**Comment by axic** [comment]
@chriseth I was looking at this with assembly and not sure how this could accomplished cleanly.

From the semantics point it would look like:

`a = ArrayUtils.pop(a, 1)`

if the code is placed into a library.

If it is accessed via delegatecall, would `pop()` receive the storage location of `a`?  Can Solidity handle that today properly?

**Comment by chriseth** [comment]
@axic if you combine that with `using x for y`, it can actually be `a.pop()` and yes, if the library function in `function (T[] storage a)`, then it would receive the storage location. What this needs is templates.

**Comment by chriseth** [comment]
We added `.pop` a long time ago.
