### ISSUE TITLE
Array.push() after delete doesn't work properly [possible bug]

### ISSUE THREAD

**Issue by carbogninalberto** [ethereum/solidity#4140]
I have the following code:
``` solidity
struct Participant {
	address participantAddress;
	bool participate;
	uint goal;
}


struct Challenge {
	string name;
	string description;
	string targetDescription;
	uint256 timestamp;
	uint prize;
	uint target;
	uint fee;
	address owner;
	bytes32 challengeHash;

	// these arrays rappresent the same object
	address[] participantsAddress;
	bool[] participantsStatus;
	uint[] participantsGoal;

	//other
	address winner;
}

Challenge[] public challenges;
uint public challengesLength;
```
I add Challenge struct to array challenges without problem, then i delete elements with the following lines (where i is the index of the element i want to delete):
```solidity
challenges[i] = challenges[challengeLength-1];
delete challenges[challengeLength-1];
challengesLength = challengesLength-1;
```
And when i use push() to add a new element at the end with the following lines, the last element has the position of the last element+1. I try in different ways to check whether is a bug or not.
```solidity
challenges.push(Challenge(
	nameCreate,
	descriptionCreate,
	targetDescriptionCreate,
	nowUnix,
	prizeCreate,
	targetCreate,
	feeCreate,
	msg.sender,
	hash,
	new address[](0),
	new bool[](0),
	new uint[](0),
	address(0)
	));

challengesLength++;
```
Is my code wrong or is there a bug?

**Comment by chriseth** [comment]
`delete` is equal to assigning a freshly initialized value, i.e. it does not free the slot or change the length when you use it with array elements. Why do you keep a second variable that stores the length instead of just using `challenges.length`? If you do `challenges.length = challenges.length - 1` above, your code could work correctly, because that actually removes the array slot.

**Comment by carbogninalberto** [comment]
Thank you for your response.
Now the code is working, i thought that the length of the array was updated automatically. I read documentation, but i missed this detail.
By the way i was storing the length in a second variable to access it directly from web3.js! 
I realized now that i could write a simple getter.

**Comment by chriseth** [comment]
Glad that this worked!
