### ISSUE TITLE
Static analyzer to suggest minimum compiler version based on features used

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4149]
It would make sense for the Remix static analyzer to suggest the minimum compiler version needed after considering all the language features used in the source code.

It should suggest the proper version pragma or complain in the version pragma present states an earlier version.

cc @soad003

Closes #4103

**Comment by soad003** [comment]
@axic Sounds good, can you provide me with a list of features introduced in each compiler version?

**Comment by axic** [comment]
@soad003 sure, give me a bit of time, I have a collection of these, but need to update them.
