### ISSUE TITLE
contract function call fail in mainnet but, in testnet, contract function call success

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#4164]
First, I use remix-ide.

I want to 'ETC contract function' call that send coins to multiple addresses.

And, this code is below.

![jkall](https://user-images.githubusercontent.com/8006373/40282000-3d4dfe3c-5ca3-11e8-8fc5-21a68c930835.png)

I wanted to call 'send_to_N' function.

And, I tested my ETC contract source in testnet.

this function call was success.

But, in mainnet, this function call was failed.

I can't know the cause of failure.

For the cause, I attempted to call "eth.getTransactionRecipt" -> I got some information but, I can't get information I want.

transaction failed log is below link.

[http://gastracker.io/tx/0x1af25b03705c59e1f4665ce00d8f5e0d25b098ab83c78e420258f3207d8e3ea2](url)

Does anyone know how?

**Comment by chriseth** [comment]
Does ETC support he byzantium opcodes?

**Comment by chriseth** [comment]
If not, you have to compile with `--evm-version homestead`

**Comment by axic** [comment]
This is tracked in #4259.
