### ISSUE TITLE
Note about events is inaccurate

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#4167]
This note about event logging is inaccurate:

https://solidity.readthedocs.io/en/v0.4.24/contracts.html#events

> Indexed arguments will not be stored themselves. You can only search for the values, but it is impossible to retrieve the values themselves.

---

Counterexample: see the event log on this Su Squares transaction:

https://etherscan.io/tx/0x23de16e75c4b8f8d337d229efe8bde2df9622ad2a026c966e633678a987abbf3#eventlog

The `from` and `to` addresses are the values and they are indexed, and it IS possible to retrieve this value as etherscan has done. This contradicts with the statement quoted above.

**Comment by axic** [comment]
The values of the indexed arguments are hashed together IIRC, hence it is possible to find logs for specific values, but should not be possible to extract the values from the logs themselves.

**Comment by fulldecent** [comment]
Please see counter example above.

https://github.com/ethereum/solidity/issues/4167#issuecomment-391479016

It is possible that EtherScan is using black magic to get the values (e.g. decompiling the program trace and/or running a non-standard log3 implementation that saves all the values).

I need to find a definitive answer on this for ERC-721 standardization. Other ERCs will surely have an interest here as well.

**Comment by ralph-pichler** [comment]
Afaik you can retrieve them as long as the data type fits into one word. In that case the topic in the log is the value itself. For values which can be larger the hash is used as the topic (and thus the data itself isn't actually contained in the log).

**Comment by chriseth** [comment]
Ok, I'm pretty sure that this is incorrect for values that fit inside 32 bytes. The topics are inserted into a bloom filter which is not exact. In order to get a correct match when you search by topic, the topic itself needs to be stored in the receipts, too.

**Comment by fulldecent** [comment]
@chriseth Can you please explain "the topic itself needs to be stored in the receipts, too"?

Can you please give specific examples of things that do work and things that don't work?

**Comment by ralph-pichler** [comment]
@chriseth I'm pretty sure the topic is already automatically stored in full in the receipt in addition to the bloom filter.

**Comment by chriseth** [comment]
@ralph-pichler yep! @fulldecent reference types cannot be retrieved. Value types can be retrieved.
