### ISSUE TITLE
When total translate English to Spanish 

### ISSUE THREAD

**Issue by naitsirhc007** [ethereum/solidity#4174]
In the Web solidity, in Spanish is translated just to half. 

https://eleanarey.github.io/solidity-en-español/index.html#document-index

**Comment by chriseth** [comment]
Here is a full translation but it is out of date: https://solidity-es.readthedocs.io/es/latest/

We cannot answer your question, unfortunately, it is a community effort.

**Comment by ChrisChinchilla** [comment]
Hey @naitsirhc007 as part of many other docs efforts, I am handling translations. Are you, or @eleanarey interested in continuing this Spanish translation? I have a plan in place and am happy to help you with whatever you need.
