### ISSUE TITLE
Update IdentifierList Grammar Rule

### ISSUE THREAD

**Issue by sledrho** [ethereum/solidity#4186]
The current grammar defines **IdentifierLists** as being
> IdentifierList = '(' ( Identifier? ',' )* Identifier? ')'

This in theory requires **IdentifierLists** to retain the trailing comma.
> (identifier1,)
(identifier1,identifier2,)

But it also allows **IdentifierLists** to contain only separation comma's and not identifiers, something the solidity compiler (Version 0.4.24) errors on.
> identifierlist.sol:7:7: Error: Tuple component cannot be empty.
      (test1,,,);
      ^--------^

Therefore should the grammar not be altered to the following in order to properly reflect what the compiler accepts?
>IdentifierList = '(' Identifier+ ( ',' Identifier )* ')'

Code used to obtain the above error:
``` 
pragma solidity ^0.4.24;
contract test {
   uint8 public test1 = 0;
   uint8 public test2 = 0;
   string private test3 = "test";
   function test_func() public {
      (test1,,,);
   }
}
```

**Comment by axic** [comment]
It is still accepted, but you have to have it as a left value (e.g. what `IdentifierList` describes):
```
contract C {
  function g() returns (uint, uint, uint, uint) {}
  function f() {
    uint v;
    (v,,,) = g();
  }
}
```

**Comment by chriseth** [comment]
`IdentifierList` will be removed from the grammar with 0.5.0, because we remove `var`.
