### ISSUE TITLE
Need an explanation there

### ISSUE THREAD

**Issue by aj07** [ethereum/solidity#4189]
There is need an explanation why we are doing 16 elements "Access to the stack is limited to the top end in the following way: It is possible to copy one of the topmost 16 elements to the top of the stack or swap the topmost element with one of the 16 elements below it."

**Comment by chriseth** [comment]
Still, you can only access the 16 topmost stack elements unless you move them somewhere else. Where do you think this explanation is needed?

**Comment by aj07** [comment]
Question was why we are limiting to 16 elements only? Any specific reason on it?

**Comment by chriseth** [comment]
The solidity documentation cannot provide a historical explanation of design decisions for the EVM.
