### ISSUE TITLE
Nice to have -  sorry it is not issue  

### ISSUE THREAD

**Issue by raky35** [ethereum/solidity#4191]
Hi Team,
it is good to have function which converts "wei" to ether-   Any values are stored in mapping as "wei"  it needs conversion for comparison i.e ether and wei. 

i did not find any function which converts "ether" to "wei" rather than custom logic of. (10**18) . 

Cheers
rakesh

**Comment by chriseth** [comment]
Thanks for the input, but to be a proper feature request, this requires a little more detail. You can use `x / 1 ether` to convert wei to ether, but I don't see a real good reason to do this, as it loses precision.
