### ISSUE TITLE
Multiply return values not supported.

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/solidity#42]
solc compiles the following:
```
    function ret() returns (int a, int b) { 
        a = 1;
        b = 2;
    }
```
But no ways to get both `a` and `b` from return data. That feature would be very handy in absence of Struct returns.

**Comment by LianaHus** [comment]
sorry I can't understand the problem. So your example is working now. you have a and b in return data. could you please rephrase your question

**Comment by Nashatyrev** [comment]
Sorry, I've probably missed something, but what is the syntax of calling such function and obtaining `a` and `b` from the returned data?

**Comment by LianaHus** [comment]
ah, sure. unfortunately  now you still can't do that, but you can return struct from internal function(don't forget should to add "internal" specifier before "returns").
we have pending story to implement (a, b) = func(); 
https://www.pivotaltracker.com/n/projects/1189488/stories/99085194

**Comment by LianaHus** [comment]
https://www.pivotaltracker.com/n/projects/1189488/stories/99085194
