### ISSUE TITLE
Tail call optimization and finite state machines?

### ISSUE THREAD

**Issue by talon** [ethereum/solidity#420]
Looks like smart contracts rely on storing state in variables bound inside the contract structure but otherwise operate very similarly to Erlang/Elixir processes (with message passing to communicate)

Still learning about it but I'm curious if it would be possible to handle state in a similar way that they do? via recursive functions that call themselves with new state, finite state machines.

**Comment by VoR0220** [comment]
@LegitTalon can you give me an example?

**Comment by talon** [comment]
I'm gonna learn more about Solidity. Might have jumped the gun here. If the thought clarifies I'll be back.
