### ISSUE TITLE
Remove suicide/sha3 aliases

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4203]
Similar to #3003.

I think two years having `selfdestruct` (and `suicide` being deprecated) should have been enough time to stop using it.

**Comment by axic** [comment]
I think we had an issue for this, but couldn't find it.

There the consensus was it may be bad idea because malicious libraries could specify it, I may not fully share that, because that would mean we are keeping legacy indefinitely and most of these things should be tested before deploying a contract.

However, a middle ground could be turning the "deprecated" warnings into errors for the above two functions.

**Comment by chriseth** [comment]
Yep, let's at least make them errors.
