### ISSUE TITLE
Since 0.4.22, when calling a function which is expected to have a return value but doesn't, the transaction will fail

### ISSUE THREAD

**Issue by hcaw** [ethereum/solidity#4209]
```
pragma solidity 0.4.22;

contract ExpectedContract {
    function transfer() public returns (bool){ return true; }
}

contract ActualContract {
    function transfer() public {}
}

contract MainContract {
    function someFunction(address actual) public {
        ExpectedContract(actual).transfer();
    }
}
```
When calling `MainContract.someFunction()`, using the address of `ActualContract` instead of `ExpectedContract`, the transaction will fail.
The transaction will be succesful when MainContract is compiled with 0.4.21, but not with 0.4.22.
I have tested this on mainnet today.

I discovered this issue when calling the `transfer` function of ERC20 tokens from another contract, as the expected interface returns a boolean, however some tokens such as OMG, do not return a boolean.

**Comment by BrendanChou** [comment]
Duplicate #4116

**Comment by axic** [comment]
Handled in #4259.
