### ISSUE TITLE
Update "Safe Remote Payments" example with non-truncating division

### ISSUE THREAD

**Issue by kronosapiens** [ethereum/solidity#4211]
The "Safe Remote Payments" example in the solidity tutorial (https://github.com/ethereum/solidity/blob/v0.4.24/docs/solidity-by-example.rst) assumes truncating division.

As division is no longer truncating, this example should probably be updated.

**Comment by chriseth** [comment]
Why do you think division is no longer truncating?

**Comment by kronosapiens** [comment]
I was referring to the note here: http://solidity.readthedocs.io/en/v0.4.24/types.html#rational-and-integer-literals

```
Division on integer literals used to truncate in earlier versions, but it will now convert into a rational number, i.e. 5 / 2 is not equal to 2, but to 2.5.
```

I was confusing the handling of integer literals with `uint`-valued variables. It's a non-issue.
