### ISSUE TITLE
Support splitting computation across multiple transactions for (seemingly) infinite gas limit.

### ISSUE THREAD

**Issue by tsuberim** [ethereum/solidity#4218]
The blockchain does not allow us to execute transactions beyond the bound of the block gas limit. This leads to various hacks and methods that mitigate the problem but require much work.
Can we split a heavy computation across many transactions to get truly unbounded execution? That way the programmer does not need to specify various locks and methods to overcome this challenge.

Potential issues: 
- What about interleaving transactions (i.e. transactions that happen in between continuations)? do we lock the contract until the mega-transaction complete? if so we risk a DOS attack on the contract, where a participant can never finish the mega-transaction and the contract will remain locked. if not we run into race condition issues and we lay a heavy burden on the programmer to make sure it doesn't interfere with the contract's logic.
- Can multiple people jointly perform one mega-transaction by each contributing one step? if so we may violate the semantics of solidity because `msg.sender` (and other globals) may change during execution.

Implementation:
The naive way is that the compiled code would stop it's own execution when it reaches close to the gas limit and save it's program counter, stack and transaction so that it may resume again from exactly the same point.

Problems with the naive approach:
- Saving the stack is potentially very expensive.
- How do we decide when we don't have enough gas and need to save the state?
- The gas required to save the state is variable and hard to predict when is the right time to do it.

(Possibly) better approach:
We only save a hash of the current state (stack and PC) and leave the user to provide the complete state along with the transaction next, to decide when to save the state we split the code into control-flow blocks (we also need to split blocks that are larger than the gas limit into multiple smaller blocks) and insert a simple check at the start of each block that checks if we have enough gas for the execution of the next block. If so, we save the state.

We invent a new convention for the transaction data of continuation transactions as opposed to regular transactions, and check for this format at the beginning of each function, if we find it, we need to verify the integrity of the state and possibly other things.

**Comment by VoR0220** [comment]
You might want to look at some scalability solutions elsewhere. Check out:

truebit.io 
state channels
and OMG's Plasma MVP


As it stands I'm not sure this issue belongs here? Possibly better to plop this in the EIP repo.

**Comment by tsuberim** [comment]
I'm not looking to solve the blockchain scalability problem, just to make the existing technology a little better. Seems to me that it's a compiler feature and probably belongs in the solidity repo.

**Comment by chriseth** [comment]
This is very useful, but I fear that the complications it introduces do not make up for its usefulness. Certainly, we should only allow computations to be broken up at very clear points where the stack is (almost) empty, and this should be a very explicit feature.

**Comment by tsuberim** [comment]
@chriseth I agree, what about something like:
```
function blah() public {
  atomic {
    uint a = 5
  }
  atomic {
    // cannot use `a` from here.
    uint b = 7
  }
}
```

an `atomic` code block executes in one transaction, subsequent code blocks cannot see the local variables from other `atomic` code blocks so we can empty the stack.

**Comment by chriseth** [comment]
What if `blah()` is called from another internal function or even a different contract? `msg.sender` might change in mid flight.

**Comment by chriseth** [comment]
What about `function blah(uint counter, uint max) public { ... }` where `blah` is automatically called multiple times as long as there is gas, `counter` is incremented until it hits `max` and inside `blah` you have an if-else construct?

**Comment by tsuberim** [comment]
`atomic` indicates that the code block executes in one transaction, thus it's expected that some globals (`msg.sender`, `txHash`, ...) may be different for each `atomic` block. 

> What about function blah(uint counter, uint max) public { ... }

How do you seperate the real arguments from the "automatically handled" arguments?
Do you dispatch different code depending on `counter`? seems like superfluous boilerplate.
