### ISSUE TITLE
Scope resolution operator?

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#423]
https://en.wikipedia.org/wiki/Scope_resolution_operator

It would be great is we could indicate if prefixing a variable with `::` would be equivalent to `this.` (Not that `this.` works either).

**Comment by VoR0220** [comment]
seems to be borrowing more from c++ than JS. I think `this` is just fine :/

**Comment by chriseth** [comment]
I avoided `::` as much as I could for now because it will confuse people coming from JavaScript.
I think that `ThisClassName.` should actually work, so there might be a bug.
What is your use case? Disambiguating between globals and state variables or between state variables and local variables?

**Comment by chriseth** [comment]
@drupalnomad any response to my questions?
