### ISSUE TITLE
Odd functionality between web3 and .sol SHA3

### ISSUE THREAD

**Issue by drewstone** [ethereum/solidity#424]
It would help to have clear documentation on the different results that arise when computing sha3 hashes of different types in solidity. Solidity sha on multiple arguments of the same type doesn't work correctly as well.

To get the same output from these inputs into the web3.sha3 function, I had to use an input of type bytes for the function `compute_sha`. Using bytes32 as the type of `input` returns a different hash value as does changing the input into any different type.

```
function compute_sha(bytes input) returns (bytes32 result) {
       return sha3(input);
}
```

``` javascript
var hash = "0x" + web3.sha3("secret") // 0x65462b0520ef7d3df61b9992ed3bea0c56ead753be7c8b3614e0ce01e4cac41b
var hash_of_hash = "0x" + web3.sha3(hash, {encoding: "hex"}) // 0x2ed293efa90dd457a302c46949588d43099e0897bccde03115db594d0ba62445

myContract.compute_sha.call("secret") // 0x65462b0520ef7d3df61b9992ed3bea0c56ead753be7c8b3614e0ce01e4cac41b
myContract.compute_sha.call(hash) // 0x2ed293efa90dd457a302c46949588d43099e0897bccde03115db594d0ba62445
```

Additionally, it doesn't appear that web3.sha3 has functionality for computing the hash over multiple arguments. Even so, computing the hash of multiple arguments of type bytes in solidity still only returns the hash of the first argument. From:

```
function sha_args(bytes input, bytes extra) returns (bytes32 result) {
      return sha3(input, extra)
}
```

``` javascript
myContract.sha_args.call("secret","10") // 0x65462b0520ef7d3df61b9992ed3bea0c56ead753be7c8b3614e0ce01e4cac41b
myContract.compute_sha.call("secret") // 0x65462b0520ef7d3df61b9992ed3bea0c56ead753be7c8b3614e0ce01e4cac41b
```

**Comment by VoR0220** [comment]
This is a known issue and we have it in mind that it needs fixing. Labeling bug.

**Comment by chriseth** [comment]
Thanks for reporting, but these issues all seem to be coming from web3.js.
- Solidity has documentation about how mulitple arguments are encoded: https://solidity.readthedocs.org/en/latest/units-and-global-variables.html?highlight=sha3#mathematical-and-cryptographic-functions
- the problem with `sha_args.call("secret", "10")` seems to be a problem with how `"10"` is encoded, because if get a different result if you use `("secret", "x10")`.

Please file a bug in web3.js.
