### ISSUE TITLE
Compiling older solidity versions

### ISSUE THREAD

**Issue by igorffs** [ethereum/solidity#4242]
I'm part of a team that is building an [open-source explorer for an Ethereum sidechain called POA](https://github.com/poanetwork/poa-explorer) and we'll be implementing a contract verification feature. In order to verify older contracts, we'll need to compile a given source code in any specified solidity version. 

(We've already considered using the already compiled JS versions, but our team agrees that the C version would suit us better.)

I've been trying to compile solidity's older versions (since the first one available v0.1.2), but I'm getting some missing files errors, for example:

```
CMake Error at CMakeLists.txt:31 (include):
  include could not find load file:

    EthDependencies


CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    EthExecutableHelper


CMake Error at CMakeLists.txt:33 (include):
  include could not find load file:

    EthCompilerSettings
```

I believe that this is related to the changes in the building process throughout the versions. I already had a similar error from the issue https://github.com/ethereum/solidity/issues/86. It seems that there were some documentation to solve it but it were deprecated or moved https://github.com/ethereum/solidity/issues/86#issuecomment-142718682 👇  

> I added an alternate way to build the repos in the wiki. It does not utilize the umbrella project but clones/updates only the repos required for a project in the current directory and then builds them. You can also give that a try if you want to build only solidity:
> 
> https://github.com/ethereum/webthree-umbrella/wiki/building

I've tried using some of the [current dependency install scripts](https://github.com/ethereum/solidity/blob/develop/scripts/install_deps.sh) hoping that it could bring any old important deps but it doesn't seem to solve the problem.

Any tips on how I could accomplish that given the current build process?

**Comment by chriseth** [comment]
I am really not sure I can recommend building native historic binaries, I am pretty sure, this has all you need: https://github.com/ethereum/webthree-umbrella/tree/131f80ea0992f1edbc8950af2e1c03c3fcdc7e60

The missing files reported above should be here: https://github.com/ethereum/webthree-helpers/tree/7a580d70a94397e797621d02110018e045ccdab9/cmake

Please note that the native binaries might even have different interfaces (although single-file stdin should work).

Note that the javascript binaries found in https://github.com/ethereum/solc-bin have a unified interface via http://github.com/ethereum/solc-js. Furthermore, the javascript binaries have lower trust requirements, as users of your platform can re-check the compilation locally in their browser.

**Comment by igorffs** [comment]
Thank you @chriseth!
