### ISSUE TITLE
Always fail when the contract call external contract

### ISSUE THREAD

**Issue by dksuper** [ethereum/solidity#4248]
geth version: 1.8.7

code:
![image](https://user-images.githubusercontent.com/35549846/41153114-6714238c-6b48-11e8-9548-dd21d4f1f1f8.png)

I don't know why , but it always cost all gas!

**Comment by jeichel-miovision** [comment]
cross posted with https://github.com/ethereum/go-ethereum/issues/16931

**Comment by axic** [comment]
The go-ethereum issue seems to deal with it. Also created a documentation issue #4259.
