### ISSUE TITLE
bug in bower remix

### ISSUE THREAD

**Issue by zhuimengshaonian66** [ethereum/solidity#4251]
```
pragma solidity ^0.4.18;


contract  myToken{
     mapping(address =>mapping(address =>uint)) allowed;

    
       function allowance(address af,address spender) public view returns (uint remaining) {
        return allowed[af][spender];
    }
    
    
}
```

when i want to  test the function allowance  when i transfer two address in bower remix  it  return fault:
call to FixedSupplyToken.allowance errored: Error encoding arguments: SyntaxError: Unexpected token x in JSON at position 47

**Comment by axic** [comment]
I think you may have better luck asking this at Remix directly: https://github.com/ethereum/remix-ide
