### ISSUE TITLE
unrecognised option '--add-std'

### ISSUE THREAD

**Issue by tb1055** [ethereum/solidity#4253]
I am using these versions of geth and solc on Ubuntu 16.04..
```
geth Version:  1.8.10-stable-eae63c51
solc Version:  Version: 0.4.25-develop.2018.6.6+commit.59b35fa5.Linux.g++
```
and am getting this error message from solc:  `unrecognised option '--add-std'`

Post [3984](https://github.com/ethereum/solidity/issues/3984) said to fix this by updating geth to 1.8.6 but I am on a newer version of Geth.

Any ideas on how to fix?

**Comment by erak** [comment]
@tb1055 This is a bit weird. Your geth version (https://github.com/ethereum/go-ethereum/tree/eae63c51) does not pass ``--add-std`` any more. Have you already asked for advise in the geth gitter channel (https://gitter.im/ethereum/go-ethereum)?

**Comment by tb1055** [comment]
Thanks for the tip -  [I re-posted my question on gitter](https://gitter.im/ethereum/topics/topic/5b1d6dd44b2d9417e1db4864/solc-message-unrecognised-option-add-std-4253).
