### ISSUE TITLE
constructor public by default

### ISSUE THREAD

**Issue by benjiqq** [ethereum/solidity#4254]
constructor requires public keyword, but should be public by default I believe

```

contract Foo {
   constructor(){//..}
}
```

versus 

```
contract Foo {
   constructor() public{//..}
}
```

**Comment by erak** [comment]
@benjyz This behaviour is by design. The reasoning behind it is, that making something externally accessible should be a concious decision made by the programmer. Please see #2608 for further discussion on the default visibility of functions.
