### ISSUE TITLE
Guide for Remix debugger for solidty code

### ISSUE THREAD

**Issue by aj07** [ethereum/solidity#4258]
There needs to be guide on how to use debugger on remix IDE.

**Comment by axic** [comment]
I'm not sure this belongs to the Solidity documentation and not into the Remix documentation. Why would you put it here?

**Comment by aj07** [comment]
@axic , I am suggesting to have a debugger section for solidity, which is missing as of now.

**Comment by axic** [comment]
What would be the benefit to put that here instead of the more comprehensive Remix documentation?

**Comment by aj07** [comment]
Remix is missing extensive documentation. Most of the solidity developer uses Remix where they would like to have knowledge of debugging option. So, I think we should include. If it doesn't fit here, we can skip this part.

**Comment by axic** [comment]
Remix is currently spending a lot of effort in creating such a documentation and there is a lot more to explain about Remix than just the debugger.

**Comment by aj07** [comment]
Sure, in that case I would close this issue.
