### ISSUE TITLE
Add section about "stack too deep" errors

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4261]
Should explain the reasons and offer potential solutions (i.e. use structs with ABIEncoderV2).

**Comment by axic** [comment]
Should also mention this workaround: https://github.com/ethereum/solidity/issues/2931#issuecomment-422024109

**Comment by rhlsthrm** [comment]
@axic thank you for mentioning that workaround, I was going about a completely different type of refactor when this is all I needed for compilation.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
