### ISSUE TITLE
version name of solidity is missing

### ISSUE THREAD

**Issue by aj07** [ethereum/solidity#4267]
Process to get to know the version name of solidity is missing in the http://solidity.readthedocs.io/en/v0.4.24/installing-solidity.html#building-from-source

Reason :  on this page we are discussing about the download of binary and how to compile and build it. But knowing the right version for solidty // solc --version should also be there.

**Comment by aj07** [comment]
@chriseth  do you think this should be included in doc.

**Comment by chriseth** [comment]
The documentation [explains](https://solidity.readthedocs.io/en/v0.4.24/using-the-compiler.html#using-the-commandline-compiler) `--help` which shows you how to get the version.
