### ISSUE TITLE
Create a compiler internals overview

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4278]
- This should list all the directories and their duties.
- Should explain the high level flow of the compiler.
- Should go into detail on specific parts (e.g. optimiser, using yul in `ABIEncoderV2`, etc.)

This could be a section in the contributors guide or be a chapter on its own linked from the contributors guide. The contributors section already explains testing and fuzzing.

**Comment by axic** [comment]
Related #5202.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 Closing in favor of #5202, which is more detailed.
