### ISSUE TITLE
Interface show warning if missing solidity version

### ISSUE THREAD

**Issue by ewingrj** [ethereum/solidity#4279]
It seems to me that an interface should not need to specify a pragma directive. Is there a reason a warning is emitted during compilation is the pragma is missing?

**Comment by axic** [comment]
The pragma actually is file (and not interface/contract) specific.

Why would it make sense not having it for file only containing interfaces?

**Comment by ewingrj** [comment]
To me an interface is for defining the external api of a contract. As an api consumer, I don't care what version compiler was used.

If my interface file has `pragma solidity 0.4.18`, I can't import that interface into a contract that is using a different solidity version.

**Comment by axic** [comment]
While the pragma can be used to lock in a specific compiler version, it is mostly intended to be used to specify version ranges (for example by the caret: `^0.4.16` means anything, including, 0.4.16 is supported, but 0.5.0 is not) where these different versions can introduce different syntactical elements/features and semantics.

If you are looking for an external interface, I'd suggest to consider only dealing with the ABI JSON as that maps the external interface 100% accurately.

(I have a proposal #1687 doing so.)

**Comment by ewingrj** [comment]
ya, we typically use the caret, however we are building an app upon aragonOS which locks the version to `0.4.18`.

I have other code that I want our app to interact with that is compiled with `^0.4.21`. however I can't include the the other code interface in the app b/c the interface is ^. The only option right now is to live with the warning & don't include the pragma in the interface file, or copy the interface file to a new file in the app repo and specify a different pragma. Neither are good options in my opinion.

#1687 would work, however it seems like a statically typed file would better serve as an interface then the abi string

**Comment by chriseth** [comment]
I would say the solution is to relax the version requirement of the interface. You can also do weird stuff like `pragma solidity 0.4.18 || ^0.4.0;`. You can include the same interface file from different compilation runs with different compiler versions.

**Comment by ewingrj** [comment]
thx, just relaxing the version to `^0.4.0` did the trick
