### ISSUE TITLE
Token::name and Token::toString do not work for fixed

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#428]
The functions Token::name and Token::toString do not work for the new complex tokens fixed and ufixed, e.g. they return "UFixed" for "ufixed8x8".

**Comment by VoR0220** [comment]
will look into this.

**Comment by VoR0220** [comment]
think I've zoned in on the fix. How were you testing this?

**Comment by VoR0220** [comment]
Fixed this in the FixedType PR...if you want it now, let me know.

**Comment by chriseth** [comment]
@VoR0220 could you create a new PR just for this? Better to fix issues early.
