### ISSUE TITLE
Events with storage structs as argument cause internal error

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4291]
```
contract c {
    struct S { uint a ; uint b; }
    event E(S);
    S s;
    function f() {
        emit E(s);
    }
}
```
UnimplementedFeatureError: Only in-memory reference type can be stored.

and
```
contract c {
    struct S { uint a ; uint b; }
    event E(S indexed);
    S s;
    function f() {
        emit E(s);
    }
}
```

Although works currently, it should be disallowed.

**Comment by chriseth** [comment]
It does not cause an internal error with `indexed`, but it should also be disallowed.

**Comment by chriseth** [comment]
Clarification: Without ABIEncoder2, structs should be disallowed in events both as indexed and non-indexed parameters.

**Comment by axic** [comment]
There is also a counterpart to this issue with dealing with structs in memory: #4292

**Comment by leonardoalt** [comment]
I tested the following code on Remix, and if I call `set` and then `f`, the log is
```
                ...
		"event": "E",
		"args": {
			"0": [
				"123",
				"123"
			],
			"length": 1
		}
```

```
pragma solidity >=0.4.24;
pragma experimental ABIEncoderV2;
contract c {
    struct S { uint a ; }
    event E(S);
    S s;
    function set() public {
        s.a = 123;
    }
    function f() public {
        emit E(s);
    }
}
```

Any idea why the repetition?

**Comment by chriseth** [comment]
Can you try to retrieve the raw data of the event? Perhaps it is a bug in the decoder.

**Comment by chriseth** [comment]
Follow-up: https://github.com/ethereum/solidity/issues/4686
