### ISSUE TITLE
web3 compiler stop working with solc version 0.1.2

### ISSUE THREAD

**Issue by danielnovy** [ethereum/solidity#43]
Not sure the appropriated repo to post this so I'm posting to both web3 and here. Upgrading solc from `0.1.1` to `0.1.2` makes the web3 compiler stop working with the message `solc: no build results found`. The solc command line options changed a lot from `0.1.1` to `0.1.2` and that's probably the reason. Downgrading solc to `0.1.1` solved the issue. I'm using Ubuntu 15.04.

**Comment by ethers** [comment]
a similar PR/fix to this https://github.com/ethereum/pyethereum/pull/285 may be needed for web3

**Comment by chriseth** [comment]
Thanks for posting, but this is neither a bug in web3 nor in solidity. The backend (i.e. geth, AlethZero or whatever you use) needs to adopt the interface change in solc. We meant not to release binaries for 0.1.2 before at least geth adopted the change, but somehow they slipped through.

**Comment by ethers** [comment]
yes, a geth bug was filed previously https://github.com/ethereum/go-ethereum/issues/1770
