### ISSUE TITLE
Pointers in Solidity - Question

### ISSUE THREAD

**Issue by davinci26** [ethereum/solidity#4312]
I have a mapping that maps a string to a struct that has a substantial size.
``` solidity
Struct Big_struct{
        address creator;
       Other variables
}
    mapping(string => Big_struct[]) mapping1;
   function foo(string key) {
    mapping1[key].push (Big_struct(msg.sender, other arguments))
  }
 function get_big_struct(address specific_creator) returns (Big_struct){
      ????
 }
```
I want to access this big struct mapping in multiple ways, is there a pointer-like type that I could use to reduce the size required by my contract. Coming from a C++ background I would create 
``` solidity
 mapping( address => Big_struct*[]) ptr_mapping
```
Is there some solidity design pattern to achieve something similar without storing multiple copies/instances of the same Big_struct?

**Comment by OTTTO** [comment]
are you familiar with the ```memory``` and ```storage``` keywords?
```memory``` is used to make a transient reference to something in storage.
in certain cases you can even utilize this to make costly functions ```view``` functions.

**Comment by davinci26** [comment]
Thanks alot for the reply :) 

The way I had it in my mind ``` mapping( address => Big_struct*[]) ptr_mapping ``` would be a state/contract variable.

I was able to find a lot of information on the ```memory``` keyword, not so much on ``` storage```.

In general I would consider pointers as good addition to the language, as most Solidity developers want to minimize the storage they use to reduce tx fees.

**Comment by chriseth** [comment]
I am not really sure I understand the problem. What I can say is that a local variable of type `Big_struct storage` is always just a pointer. If you want to use pointers in storage (as opposed to "to storage"), using IDs is as close as you can get.

**Comment by chriseth** [comment]
Closed due to inactivity.
