### ISSUE TITLE
Documentation of comments in source files is misleading

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#4314]
The section that describes how to use NatSpec-style comments in Solidity source files (https://solidity.readthedocs.io/en/develop/layout-of-source-files.html?highlight=natspec#comments) is misleading. It refers to the Doxygen documentation, but should rather refer to the NatSpec documentation itself: https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format.

Apparently, NatSpec only supports a subset of the Doxygen tags, which is currently not reflected in the documentation.

**Comment by ligi** [comment]
The misleading documentation might also be the cause for this:

![selection_082](https://user-images.githubusercontent.com/111600/41552644-a0fd93a0-732f-11e8-801f-db83f580e2c2.png)

the very same code compiles with remix - I think the etherscan coders just also had problems finding the list of allowed tags and just probed some - and missing "dev" in the process.

Had trouble googling for the list of allowed tags before also - but thanks to @bit-shift I found it.

**Comment by aj07** [comment]
I have gone through the doc and found that they have written something like "comment called a natspec comment, for which the documentation is not yet written." whereas, I found https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format  There they have written about natspecs. Can we put summarize format of that link in solidity doc along with example. As of now the example is written for Doxygen

**Comment by aj07** [comment]
@chriseth @axic need comments from your side..

**Comment by chriseth** [comment]
@aj07 sounds good!
