### ISSUE TITLE
Disallow explicit conversion between unrelated contract types

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4320]
Surfaced in https://github.com/ethereum/solidity/issues/4308

If you still want to do it, you have to go through `address`.

**Comment by axic** [comment]
I'm fine disabling it unless the inheritance chain is known between the two, e.g.

```
contract A {}
contract B is A {}
contract C is B {}

contract D {
  function f() {
    A a = A(new C()); // should be valid
  }
}
```
