### ISSUE TITLE
Function signature returns a named variable `sum`, assigning to it and returning something else should trigger compiler warning?

### ISSUE THREAD

**Issue by stefek99** [ethereum/solidity#4322]
```
pragma solidity ^0.4.24;
contract ThatReturnsSomething {
    
    function Foo(uint a, uint b) pure public returns (uint sum) {
        sum = a + b;
    }
    
    // TypeError: Different number of arguments in return statement than in returns declaration.
    // function Bar(uint a, uint b) public {
    //     return a + b;
    // }
    
    function Baz(uint a, uint b) pure public returns (uint sum) {
        return a * b; 
    }
    
    function Foo2(uint a, uint b) pure public returns (uint sum) {
        sum = a + b;
        uint somethingElse = 123; // something random
        return somethingElse;
    }
}
```

Related: https://ethereum.stackexchange.com/questions/34046/what-is-the-purpose-of-giving-name-to-return-variables-in-function-declaration

6 months ago I didn't know how to use Remix and Metamask to deploy ERC20... No wonder why I didn't know this syntax: https://github.com/kleros/openiico-contract/issues/34

I believe that `foo2` is potentially confusing, should trigger warning.

**Comment by axic** [comment]
I think this tracked in #708 (also relevant #3134). Please comment if you think those issues are not enough to discuss the problem.

**Comment by stefek99** [comment]
@axic of course you are right, I should use "search" option first.

Me = data point. It's really really confusing.
