### ISSUE TITLE
Unexpected 'now' time behavior when set on constant variable

### ISSUE THREAD

**Issue by fakel** [ethereum/solidity#4334]
When a variable using compile-time 'now' is wrong setup as 'constant' during compilation time like:

```
pragma solidity ^0.4.24;
contract testTime{
    uint256 constant public startTime = now;
    constructor () public {}
}
```

The variable getter created for 'startTime' will become actually variable over time and not a fixed value, so it will return current request time instead of compile set time.

**Comment by chriseth** [comment]
Using `now` for constants is deprecated (it generates a warning) and will not be possible anymore starting with version 0.5.0.
