### ISSUE TITLE
Documentation is wrong about conditional operator precedence

### ISSUE THREAD

**Issue by jzakrzew** [ethereum/solidity#4336]
The documentation at http://solidity.readthedocs.io/en/latest/miscellaneous.html#cheatsheet claims that the ternary conditional operator precedence is 14, while the precedence of assignment operator is 15 (like in C).
However this would mean that the following testcase (conditional_expression_with_return_values from SolidityEndToEndTest) 

	contract test {
			function f(bool cond, uint v) returns (uint a, uint b) {
				cond ? a = v : b = v;
			}
	}
should parse as

	contract test {
			function f(bool cond, uint v) returns (uint a, uint b) {
				(cond ? a = v : b) = v;
			}
	}

when in fact it parses as

	contract test {
			function f(bool cond, uint v) returns (uint a, uint b) {
				cond ? (a = v) : (b = v);
			}
	}

This means that the precedence of conditional and assignment operators should probably be equal (like in C++).
See also notes at https://en.cppreference.com/w/cpp/language/operator_precedence

**Comment by axic** [comment]
@jzakrzew thanks for noticing! @androlo do you want to create a test case for this?

After that we could discuss which behaviour is desired and keep the documentation and implementation consistent with that.

I'd vote the current implemented behaviour should be kept.

**Comment by androlo** [comment]
@axic I could. Do you want more end-to-end tests of this kind? 

I could also add a syntax test for the TypeError you get when trying to use a conditional expression as an lvalue, since it is kind of related. I looked but I haven't found one.

EDIT: Actually I found it: `283_left_value_in_conditional_expression_not_supported_yet.sol` in nameAndTypeResolution

**Comment by leonardoalt** [comment]
Closed by https://github.com/ethereum/solidity/pull/6272
@ChrisChinchilla please reopen if I'm wrong

**Comment by ChrisChinchilla** [comment]
That is true @leonardoalt I hadn't noticed it merged to close the issue, thanks :)
