### ISSUE TITLE
Typo in FAQ documentation

### ISSUE THREAD

**Issue by lawrnce** [ethereum/solidity#4339]
In the section [https://solidity.readthedocs.io/en/v0.4.24/frequently-asked-questions.html#what-happens-to-a-struct-s-mapping-when-copying-over-a-struct](url), there is a typo.

> In this case, the mapping of the struct being copied over into the userList is ignored as there is no “list of mapped keys”. Therefore it is not possible to find out which values should be copied over.

Should read:
> In this case, the mapping of the struct being copied over into **user2** is ignored as there is no “list of mapped keys”. Therefore it is not possible to find out which values should be copied over.

**Comment by axic** [comment]
Thanks! Do you want to create a PR fixing it?

**Comment by ChrisChinchilla** [comment]
@axic and @lawrnce I'm going through the FAQ as part of https://github.com/ethereum/solidity/issues/1219 right now, so will fix it as part of that issue if that's OK?

**Comment by JamieHarper95** [comment]
Hi, if this still needs doing i'm available now??

**Comment by ChrisChinchilla** [comment]
Getting the prs out today :)

**Comment by JamieHarper95** [comment]
no worries i'm primarily a web developer so if anything comes up like this again, more than happy to contribute :)

**Comment by ChrisChinchilla** [comment]
@JamieHarper95 Please do :)

**Comment by chriseth** [comment]
Has this been fixed? If not, please create a single PR only fixing this one, so we can merge it right away.
