### ISSUE TITLE
$solc --gas largeBase64Storage.sol returns base64 strings and not returns gas calculation (but can upload as below)

### ISSUE THREAD

**Issue by TOMOAKI12345** [ethereum/solidity#435]
https://gyazo.com/2010bc9222c66ec32766c45d05a3a852

https://gyazo.com/1602a3b6bba98444eb0fff8daed0927c

**Comment by VoR0220** [comment]
can you show me the actual solidity code that you're working with here?

**Comment by TOMOAKI12345** [comment]
yes here's the code (just 5MB base64 image to do "SSTORE") https://www.dropbox.com/s/cswszm3tvb1we3y/SimpleStorage.sol?dl=0

**Comment by VoR0220** [comment]
jesus that's a long string....and you're saying which method is not returning the gas calculation?

**Comment by TOMOAKI12345** [comment]
this is $ solc --gas simpleStorage.sol

**Comment by TOMOAKI12345** [comment]
the bug coms from unexpected \n, sorry
