### ISSUE TITLE
new bytes overallocates memory, causing unneeded gas waste

### ISSUE THREAD

**Issue by D-Nice** [ethereum/solidity#4357]
It seems when using `new bytes`, an order of magnitude more memory is allocated than is actually needed for the specified length. 

Please refer to the following example, where A profiles current cost, B profiles expected cost, and C profiles current cost with the asm equivalent of what I think solidity is doing under the hood.

```
contract memoryProfiler {
    function A() returns (uint r) {
        new bytes(128);
        assembly {
            r: = msize
        }
        // returns 4256 for msize
        // 1224 gas used
    }
    
    function B() returns (uint r) {
        newBytesProper(128);
        assembly {
            r: = msize
        }
        // returns 288 for msize
        // 321 gas used        
    }
    
    function C() returns (uint r) {
        newBytesNative(128);
        assembly {
            r: = msize
        }
        // returns 4224 for msize
        // 1139 gas used
    }
    
    // approximate expected action
    function newBytesProper(uint _len) returns (uint o) {
        assembly {
            let f := mload(0x40)
            codecopy(f, codesize, add(_len, 0x20))
            mstore(f, _len)
            o := f
            mstore(0x40, msize)
        }
    }
    
    // approximation of what solidity does
    function newBytesNative(uint _len) returns (uint o) {
        assembly {
            let f := mload(0x40)
            // native appears to mul 0x20 rather than just adding
            // the extra length slot?
            codecopy(f, codesize, mul(_len, 0x20))
            mstore(f, _len)
            o := f
            mstore(0x40, msize)
        }
    }
}
```

As the comment under the `newBytesNative` function states, it appears that solc erroneously multiplies the length slot, rather than adding. With the offending line of code likely being here: https://github.com/ethereum/solidity/blame/dc5cd3e1e7db933493fe1b0dc12e5ecdf2a50ed7/libsolidity/codegen/CompilerUtils.cpp#L522

**Comment by axic** [comment]
What version are you using? There was a bug like this which has been fixed.

**Comment by D-Nice** [comment]
Any I've tried, which was quite a few, including early ones, so it appeared that all 0.4.* were affected. The ones I can vouch for sure which I just tested are 0.4.24 stable and the 0.4.25 nightly that's most recent of today.

**Comment by D-Nice** [comment]
The latest nightly still has this issue. Would be nice to see this fixed before 0.5 release.

**Comment by chriseth** [comment]
The bug was introduced with https://github.com/ethereum/solidity/commit/6777f7a57fed6b39128773f13084da729dd64588. I will fix it right away! Thanks a lot for finding and reporting!

**Comment by chriseth** [comment]
@axic the old bug was that the free memory pointer was advanced too much, here, "only" `msize` gets too large.
