### ISSUE TITLE
How to call a token contract in another contract.

### ISSUE THREAD

**Issue by carbonnetwork** [ethereum/solidity#4358]
I have a ERC20 token contract. when I used javascript call the contract it worked very well.But when I call it in my another contract, it can't be work normally. My token inherited structure:

```
ERC20
StandardToken is ERC20
MyToken is StandardToken
```
 I run these case below with truffle test. 

First, I used like this:
```
MyToken token = MyToken(address);
token.transfer(_to,2000);
```
Becase the msg.sender is caller address, it can't be transfer token from user who initiate the transaction.

Then , I tried like this: 
```
bool res = tokenAddress.delegatecall(bytes4(keccak256("transfer(address,uint256)")),_to, _amout);
&
assembly {
  mstore(mload(0x40), sig)
  mstore(add(4, mload(0x40)),_to)
  mstore(add(36,mload(0x40)),_amout)
  r := delegatecall(sub(gas, 700), tokenAddress, mload(0x40), 68, mload(0x40), 1)
}
```
In this case, although the msg.sender is expected, but the balance of msg.sender is 0(msg.sender is the token contract owner,it should have many tokens), it was not correct.

Anyone who knows what should I do can make it work well. Please tell me, and thank you very much.

**Comment by chriseth** [comment]
Sorry, but this does not sound like a compiler bug and the solidity issue tracker is not meant to be used for language support. Could you ask you question in http://gitter.im/ethereum/solidity or on ethereum.stackexchange.org, please?

It might be that you are running your contract on a testnet that is not set to byzantium mode.

**Comment by carbonnetwork** [comment]
@chriseth  OK，Thanks!
