### ISSUE TITLE
Official Solidity "standard library"

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#436]
Curious if there is some concrete work, and if it is possible to contribute in some way.

If not, then I would not mind helping out with things like writing code, documentation (including code docs, UML diagrams, etc.), tests, and maintainting the repo.

I am very familiar with the language and tools (the entire ethereum stack tbh), and could basically be roaming. Would also need an expert in algorithms, and someone who is an expert in the crypto part.

I know this puts extra load on the Solidity project, and language devs, but it shouldn't have to be much if it starts out small.

**Comment by axic** [comment]
You might want to check this thread out: https://github.com/ethereum/solidity/issues/228.

Back then it was a bit early. Today we have libaries (and linking & delegatecall) and soon enough assembly - armed with these it should be possible to get this done properly.

**Comment by androlo** [comment]
Sorry. I looked through the issues but didn't find it. Thought i saw something like it before.
