### ISSUE TITLE
Update to CircleCi 2.0

### ISSUE THREAD

**Issue by godfreyhobbs** [ethereum/solidity#4361]
CircleCI is currently warning that support for the 1.0 style configuration will end on August 31st, 2018. At this point, builds for this project will fail unless the configuration is updated.

Migration documentation is available here: https://circleci.com/docs/2.0/migration/

**Comment by chriseth** [comment]
Thanks for opening the issue! I'm a little worried - we never started with circleci 1.0 in the first place, are we not using 2.0 already?

**Comment by erak** [comment]
@chriseth Our ``circle.yml`` already requires version 2.0. I think we just have to move ``circle.yml`` to ``.circleci/config.yml``.

**Comment by chriseth** [comment]
Do you want to do that, @bit-shift ?

**Comment by erak** [comment]
@chriseth Yes, can do that right away.
