### ISSUE TITLE
Infinite gas estimated in Remix

### ISSUE THREAD

**Issue by jameschen-epro** [ethereum/solidity#4362]
Remix always tells the estimated gas of my getRemainingTimeEthToken function is infinite. When I deploy the contract to geth, the function always fails executing. However, it works well in local Javascript VM or Ganache.
* Solidity compiler version: 0.4.24
* Contract source:
```javascript
pragma solidity ^0.4.24;

contract StandardCrowdsale {

  ERC20 tokenReward;
      
  constructor(
    address _tokenReward
  ) public {
    tokenReward = ERC20(_tokenReward);
  }
 
  function getRemainingTimeEthToken()
    public
    view
    returns(uint _remainToken)
  {
    _remainToken = tokenReward.balanceOf(this);
  }

}
```
**tokenReward** is the ERC20 standard token contract, **balanceOf** is the function of which as below:
```javascript
pragma solidity ^0.4.24;

contract ERC20 {

  mapping (address => uint256) public balances;

  function balanceOf(address _owner) public view returns (uint256) {
    return balances[_owner];
  }

}
```

* Remix GASESIMATES:
![image](https://user-images.githubusercontent.com/39472215/41957440-eca8f8b4-7a21-11e8-9e11-fdf24c59e1d4.png)

* Estimate Gas in Geth console:
```javascript
> instance.getRemainingTimeEthToken.estimateGas();
Error: gas required exceeds allowance or always failing transaction
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:4154:16
    at <anonymous>:1:1
```

Apart from this, other functions call **balanceOf** get infinite gas as well.
How can I fix it? Is it an issue of sol compiler?

**Comment by chriseth** [comment]
This sounds like the contract reverts at some point. Could you try to find out where exactly that happens using a debugger? It might also be that geth is not switched to byzantium mode.

**Comment by jameschen-epro** [comment]
Based on your suggestion, I reinitialize the private chain with additional configuration in the genesis.json as below.
```javascript
"config": {
  "eip150Block": 0,
  "ByzantiumBlock": 0
}
```
Configuration working confirmed.
```javascript
INFO [07-11|18:17:17] Initialised chain configuration          config="{ChainID: 2828 Homestead: 0 DAO: 0 DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> Engine: unknown}"
```
Gas estimated is still infinite though, functions all work well! Appreciate so much.
Hope this configuration could be helpful to others who are encountering the same issue.
