### ISSUE TITLE
"_;" in modifier excluded from sourceMap

### ISSUE THREAD

**Issue by ewingrj** [ethereum/solidity#4364]
Currently, the sourcemap excludes the `_;` within a modifier. I would think that the `jumpdest` in the modifier would map to this line, however in the following example it would actually map to the `require` statement. Is there a reason it doesn't?

```
modifier onlyMod() {
    require(something);
    _;
}
```

**Comment by chriseth** [comment]
I actually don't think that any code is generated that could be assigned to the `_` - in the end, the code of the function is placed where `_` has been. Example:

```
contract c {
uint a;
uint b;
modifier m() { a = 2; _; }
function f() m { b = 3; }
}
```
compiles to
```
// this is `a = 2`
      0x2
      0x0
      dup2
      swap1
      sstore
      pop // end of `a = 2`
// this is b = 3
      0x3
      0x1
      dup2
      swap1
      sstore
      pop
// this is the "return"
      jump	// out
```
Which of the opcodes in that example would you assign to `_`?

**Comment by chriseth** [comment]
Please re-open if you think there is an opcode the underscore can be mapped to.
