### ISSUE TITLE
Misuse of `view` modifier leads to weird side-effects

### ISSUE THREAD

**Issue by NavyaZaveri** [ethereum/solidity#4369]
Here's a simple dummy contract to illustrate the problem: 
 ```

pragma solidity ^0.4.24;

contract Contract{
    uint public value = 0;
 
    
    //view modifier used incorrectly 
    function set_value(uint num) public view {
        value = num; 
    
    }
    
    function get_value() public view returns(uint){
        return value;
    }

}
```
Say you call the follwing functions (in the same order):
1) `set_value(100);`
2) `get_value();`

The value returned turns out to be 0, not 100. The` view `modifier chunked beside` set_value(uint num) `isn't allowing for the state variable to be updated. 

A slip-up like this could be potentially very dangerous. While the compiler does throw a warning, when working on a large codebase this could easily be lost in a mix of other harmless warnings. It'd be really nice if it's possible to throw a compile-time error instead.

**Comment by chriseth** [comment]
This will turn into an error in the next release.
