### ISSUE TITLE
Complete Grammar?

### ISSUE THREAD

**Issue by ricmoo** [ethereum/solidity#437]
It looks like the parser uses a lot of custom code, and I was wondering if it would be possible to move to a fully described grammar (grammar.txt is incomplete), and build the compiler from that?

For a web form I'm working on I would like to validate the contract as the user is typing, and a grammar fed through something like Jison could validate input quickly, in "real time" as the user types; the compiler takes a considerable amount of time to compile (which makes sense, it's doing more).

**Comment by chriseth** [comment]
I don't think it is a viable way to re-implement syntax and type checking just for that purpose. We might provide options to just do syntax and type checking in the compiler to save you some time, but actually it should be quite fast anyway. Can you name some numbers and provide example source code?

**Comment by ricmoo** [comment]
Heya!

Sorry for the false alarm, it was a bug in my code. The compiler is lickety-split fast. I had a setTimeout I forgot about, to test what would happen if the compiler took a long time to respond, which I haven't actually observed...

**Comment by chriseth** [comment]
Ah :-) good to know!
