### ISSUE TITLE
Error: Error: [ethjs-rpc] rpc error with payload {“id”:6223335088050,“jsonrpc”:“2.0”,“params”:

### ISSUE THREAD

**Issue by sugalivijaychari** [ethereum/solidity#4371]
I have deployed a smart contract in remix ide using meta mask and test rpc. I got the below error:

Error: Error: [ethjs-rpc] rpc error with payload {"id":6223335088050,"jsonrpc":"2.0","params":["0xf9061.......f2b"],"method":"eth_sendRawTransaction"} Error: transaction underpriced

So, please give me solution to resolve this issue.

**Comment by axic** [comment]
I don't think this question belongs to this repo. Please check https://ethereum.stackexchange.com/ for answers.
