### ISSUE TITLE
Codegen: Local variables are zero-initialized even if they are assigned in the same statement

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#4373]
This can now be handled better since we create the stack slot at the same time the variable comes in scope and not at the start of the function.

**Comment by axic** [comment]
Ah, that's a nice benefit of the new scoping rules 😉

**Comment by cameel** [comment]
Is this still the case? Seems like something we would want to optimize.

I know that we at least solved it for memory objects: #10341. Not sure about other types.
