### ISSUE TITLE
CI: Check that every error/warning message in the code also appears in at least one test

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4383]

**Comment by ekpyron** [comment]
What about having another look at code coverage? That'd be a superior solution to this...

**Comment by chriseth** [comment]
I actually think code coverage is inferior. Error coverage can be a hard requirement in CI, code coverage is too soft.

**Comment by chriseth** [comment]
And code-coverage depends on external tools and slows down testing.

**Comment by axic** [comment]
#10203 and #10207 in particular shrunk this list heavily. So did #10964, #10965, #10969, #10970.

The current status is as follows:
```
$ scripts/error_codes.py --examine-coverage
IDs in source files: 568
IDs in test files  : 548 (-20)

The following error codes found in sources, but not in tests:
libsolidity/analysis/TypeChecker.cpp
 3893 4802 7128 7589 7593
libsolidity/formal/BMC.cpp
 1584 1823 3356 4010 5272 5622 8065 8084 8140 8312 8592
libsolidity/formal/CHC.cpp
 1988 3996
libsolidity/interface/CompilerStack.cpp
 2066 9609


Please make sure to add appropriate tests.
```

I think the SMT cases were mostly non-deterministic failure cases, which are very hard to test. The analysis tests were something we could not find examples for, so maybe they are not triggerable and an assertion would be due.

**Comment by axic** [comment]
I think we can close this issue, since the `scripts/error_codes.py` script also runs on CI.

**Comment by axic** [comment]
The remaining errors in libsolidity/analysis/TypeChecker.cpp:
- 3893 / 7589 / 7593 -- all are around overload resolution
- 7128 -- not sure about this
- 4802 -- I think this cannot be triggered as 1227 covers it too, not entirely sure
