### ISSUE TITLE
Cannot access an array within a struct

### ISSUE THREAD

**Issue by sontuphan** [ethereum/solidity#4384]
Hi team! As the title, I got a problem with accessing the value of an array within a struct. For example:
```
contract BountyModerator {

    struct Info {
        address owner;
        uint256 start;
        uint256[] percentages;
    }
    
    uint256 public INDEX;
    
    mapping(uint256 => Info) public BountyInfos;

    function add(uint256[] _percentages) public {
        Info memory _info = Info(msg.sender, block.number, _percentages);
        BountyInfos[INDEX] = _info;
        INDEX++;
    }
}
```

I used remix.ethereum.org to call `add([1,2,3])` and then got the saved value by `BountyInfos[0]` but it just returned  `owner` and `start` properties. I also tried to get deep a little by looking over the ABI and I saw that the output only defines `owner` and `start`.
So, without creating a new mapping for `percentages`, how can I get around this problem? Thanks in advance.

**Comment by chriseth** [comment]
The automatically added getters are a little limited. For this example, you have to write your own getter. The reason for the limit is that the size of the return value should be small and thus the getter cannot return dynamically sized arrays.
