### ISSUE TITLE
Using `create` opcode with arguments?

### ISSUE THREAD

**Issue by YoonjaeYoo** [ethereum/solidity#4394]
With opcode `create`, a new contract account is created mentioned in https://blog.aragon.one/advanced-solidity-code-deployment-techniques-dc032665f434.

How can I specify **arguments** for the constructor of the contract to be created?
On Yellow Paper of Ethereum, it only says `create` opcode requires only v, p, s and none of these explains about **arguments**.

**Comment by chriseth** [comment]
Constructor arguments are appended at the end of the code, both when using the `create` opcode and in a creation transaction. This might be a point to clarify in the documentation.

**Comment by Qkyrie** [comment]
@chriseth 
so, say you have 2 arguments you would like to append, would you use abi.encodePacked(arguments) before appending to the dynamic code, or what function would result in the correct encoding?

**Comment by YoonjaeYoo** [comment]
Below is how I solved it. First of all, you need to use 'abi.encodePacked(bytecode, arg1, arg2, ...)'. What's important is, each argument needs to be padded in 32 bytes whereas encodePacked doesn't automatically insert padding. Therefore, for bool, address, uint or int whose size is smaller than 32, you need to convert it to a uint256 and then use it. For strings, you need to convert it into a bytes with 32 bytes padding manually.

Anyone has better idea?

**Comment by axic** [comment]
Why not just use `abi.encode()` which encodes properly? (Check the documentation about `abi.encodePacked`, it is not performing ABI encoding).

**Comment by YoonjaeYoo** [comment]
@axic 
`abi.encode()` inserts length of each arguments whereas `abi.encodePacked()` doesn't. You don't need each arg's length for a function call (including constructor).

**Comment by chriseth** [comment]
You actually do. If `bytes memory data`  is the code of the contract you want to deploy, you can use `data = abi.encodePacked(data, abi.encode(arg1, arg2, arg3))` to get code plus correctly encoded arguments to deploy.

**Comment by YoonjaeYoo** [comment]
@chriseth `abi.encodePacked()` works as you mentioned but `abi.encode()` doesn't work.

**Comment by YoonjaeYoo** [comment]
@chriseth I was wrong. For others, http://solidity.readthedocs.io/en/v0.4.24/abi-spec.html#examples.

**Comment by chriseth** [comment]
So can this be closed?

**Comment by YoonjaeYoo** [comment]
Documentation needs to be done.
