### ISSUE TITLE
Internal compiler error on multiple variable declaration.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4414]
The following code:
```
pragma solidity >0.0.0;
contract C {
    function f() {
        int a;
        int a;
    }
}
```

With 0.4.24:

```
test.sol:5:3: Error: Identifier already declared.
		int a;
		^---^
test.sol:4:3: The previous declaration is here:
		int a;
		^---^
```
With current develop:

```
Internal compiler error during compilation:
/home/daniel/dev/solidity/libsolidity/analysis/DeclarationContainer.cpp(93): Throw in function void dev::solidity::DeclarationContainer::activateVariable(const ASTString&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Tried to activate a non-inactive variable or multiple inactive variables with the same name.
[dev::tag_comment*] = Tried to activate a non-inactive variable or multiple inactive variables with the same name.

```

A bit troubling that this was not caught by any test (there's tests for state variables, but not for locals).

I suspect this might be connected to scoping @leonardoalt? Do you want to look into it? Otherwise I can take it.

**Comment by leonardoalt** [comment]
The bug is also present in 0.4.24 if experimental v050 is used.

**Comment by ekpyron** [comment]
@leonardoalt Ok, that makes sense - still my guess would be that it's related to scoping. Are you looking into it? Otherwise I'll try to fix it.

**Comment by leonardoalt** [comment]
Yes, it's related. I started looking into it but didn't get very far yet: the same error IS reached, but there's an extra piece of code in `ReferencesResolver::endVisit(VariableDeclarationStatement...` that calls `m_resolver.activateVariable(var->name());` regardless.
Feel free to take over if you want, but let me know if you do.

**Comment by ekpyron** [comment]
At the moment I have some other issues I can take care of first, so let's see who's free to really start this first later on :smile:
