### ISSUE TITLE
Sending weis with constructor couldn't be compiled

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/solidity#442]
```
contract B {}
contract A {
  address child;
  function test() {
    child = new B.value(10)();
  }
}
```

`contract.sol:7:17: Error: Identifier not found or not unique.
    child = new B.value(10)();
                ^-----^`

Sample taken from here: https://github.com/ethereum/wiki/wiki/Solidity-Features#specify-value-and-gas-for-function-calls

**Comment by VoR0220** [comment]
strange...that seems to be an older one. Let me clarify with the newer docs.

**Comment by Nashatyrev** [comment]
Hi @VoR0220, any updates so far? M.b. any other method to send weis with constructor?

**Comment by VoR0220** [comment]
I can confirm that this is indeed the case that it is throwing an error, but whether or not it is supposed to I am not sure.

**Comment by VoR0220** [comment]
For now I'm going to give this the bug flag.

**Comment by chriseth** [comment]
This is a bit weird, but cannot be improved. The right way to do it is `(new B).value(10)()` - please see https://github.com/ethereum/wiki/wiki/Solidity-Changelog#020-2015-12-02
@VoR0220 do you want to add an entry to the faq for that?

**Comment by Nashatyrev** [comment]
Thanks, Chris!

**Comment by VoR0220** [comment]
Yeah let me get on that.

**Comment by VoR0220** [comment]
Just curious though...are you sure there is no way to improve that? Every time you say that you know it just makes me want to prove you wrong :)
