### ISSUE TITLE
Dynamically generate pragma solidity version

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#4421]
The `pragma solidity` version spread across the documentation is quite inconsistent, it might be a good idea to use [substitutions](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#default-substitutions) or something similar to bring each example in-line with the version of solidity.

**Comment by chriseth** [comment]
The issue is that some code is valid in older versions and some is not. We want to express that with the pragma, but I'm not sure if that is actually of value to the reader since we don't even check that together with our CI.

**Comment by ChrisChinchilla** [comment]
@chriseth Hmm, I'll look at this later, this was more me parking a few ideas and removing them from my own private Evernote. There may be a more graceful way, but it will require research.

**Comment by axic** [comment]
In any case we should explain the intention in the documentation:
a) if we keep it this way then it should be explained why
b) if we move to a consistent version, then it should be explained why

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
