### ISSUE TITLE
Contribution docs don't mention docs.sh

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#4422]
The contribution guide doesn't mention that _scripts/docs.sh_ exists or that it needs to pass for docs related PRs to pass. It's fairly similar to `make html` but not quite as it breaks a build.

**Comment by chriseth** [comment]
It is actually even stricter: All source code snippets in the documentation have to compile without warnings. This is tested inside `test/cmdlineTests.sh` which we could perhaps extract into its own script.

**Comment by ChrisChinchilla** [comment]
@chriseth And this is a very good thing, I just want to make sure future contributors know that.

I am very much a supporter of automating docs testing, I'll show you my language listing stuff some day :)
