### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4445]

**Comment by come-maiz** [comment]
This is super good news, thanks @axic, @chriseth and @bit-shift!
I suggest you tweet about this and make some noise spreading the good news,  maybe some other ethereum projects will join :)

**Comment by chriseth** [comment]
Adding a code of conduct is a first step, but not a big achievement. Enforcing it properly is the tough task, so I'm not sure if we should already celebrate this as good news.

**Comment by RichardLitt** [comment]
Should this CoC apply to the entire organization, or only to this repository? If the entire org, would it help if we copied it to the other popular repositories?

**Comment by RichardLitt** [comment]
As well; the CoC is mentioned mainly in relation to Pull Requests. Does the Code also apply for issues and other interactions around solidity (Gitter, Etc.)? If so, we should make this a bit more apparent. I'd be happy to PR a change for this.

**Comment by chriseth** [comment]
@RichardLitt thanks, that's a good point! I think we do not have the authority to make this apply to the whole organisation, but extending it to the two solidity-related gitter channels is probably a very good idea. Please create a PR!
