### ISSUE TITLE
NatSpec Json output missing several tag types

### ISSUE THREAD

**Issue by zone117x** [ethereum/solidity#4446]
According to the [NatSpec standard](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format#tags) the `@dev` and `@notice` tags can be applied to a contract definition as well as a function definition. 

These contract-level tags never show up when using the `compileStandard` function in libsolc. This bug appears to be located here: https://github.com/ethereum/solidity/blob/f3e0bf1dd85fef29bf80f2235b5c0c19a6d30f31/libsolidity/interface/Natspec.cpp#L62 where only a couple of the tags are used.

Not having support for the `@dev` tag on contracts is particularly bad because of the quantity of contracts (open-zeppelin for example) which include highly pertinent documentation with this tag.

Can a repo maintainer here confirm that this is a bug? I'd like to get confirmation before creating a pull request.

**Comment by chriseth** [comment]
Natspec unfortunately never got the love it deserved. I hope we can pick it up again soon.

**Comment by zone117x** [comment]
Our intellisense / code completion of Solidity contract codegen is vastly improved when the Solidity source has lots of properly formatted NatSpec comments. Unfortunately it's far too common for even well commented solidity contracts to not use NatSpec. 

It would be interesting if there was some kind of non-strict mode for comment parsing where function and contract comments without proper NatSpec tags could still be output in the solc json. 

Any input on this idea? If I implemented this capability into libsolc would it have any chance of being merged into mainline?

**Comment by chriseth** [comment]
Are you talking about regular double-slash comments or just triple-slash comments with errors in the tags?

**Comment by chriseth** [comment]
Can you open a new issue for that, please?
