### ISSUE TITLE
UnimplementedFeatureError: Not yet implemented - FixedPointType.

### ISSUE THREAD

**Issue by Colonel86** [ethereum/solidity#4450]
`
pragma solidity ^0.4.24;

contract FloatDemo {
    // fixed f1 = 3.45;
    fixed128x19 f3 = -1.23;
}
`
Error while compiling this code：
UnimplementedFeatureError: Not yet implemented - FixedPointType.

But Solidity 0.4.25 says it can be used 
https://solidity.readthedocs.io/en/latest/types.html#fixed-point-numbers

**Comment by erak** [comment]
@Colonel86 Fixed point types are not fully supported yet. The section https://solidity.readthedocs.io/en/latest/types.html#fixed-point-numbers contains a warning, stating that they can be declared, but cannot be assigned to or from. It's also still undecided which of the upcoming compiler versions will support them.

**Comment by Colonel86** [comment]
@bit-shift  I understand what that means
"they can be declared"
` 
ufixed128x18 f;  
`
it's allow。

 "but cannot be assigned to or from" 
`
ufixed128x18 f= 1.23;

ufixed128x18 f1;

f1 = 3.45;
`
it's not allow.

**Comment by Colonel86** [comment]
@bit-shift Thank you. If you are a relevant staff member who wishes to make the documentation more clear, or if you are not a good feature for this support, you should remove it, or describe it in a unified place

**Comment by erak** [comment]
@Colonel86 Thanks for sharing your thoughts. We'll take it into account. Since this seems to be resolved, I'll close this issue now. Please re-open if you encounter further issues.

**Comment by seaona** [comment]
hi, @erak do you know if there are any plans to include fully support of fixed point numbers? thanks!!

**Comment by cameel** [comment]
There are. It's actually one of the priority tasks right now (#409, #11019).
