### ISSUE TITLE
Could not compile source code. 

### ISSUE THREAD

**Issue by qq597353** [ethereum/solidity#4451]
The error information is as follows
---------------------------------------------
 Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.
    function MyToken(
    ^ (Relevant source part starts here and spans across multiple lines).
---------------------------------------------

How to solve
The code is https://www.ethereum.org/token copied here.

**Comment by erak** [comment]
@qq597353 The syntax for defining a constructor has changed since the version used in the example. You can fix this by using the new ``constructor`` keyword:
```
contract MyToken {
    constructor() {...}
}
```
Please see http://solidity.readthedocs.io/en/v0.4.24/contracts.html#creating-contracts for further explaination.

**Comment by qq597353** [comment]
pragma solidity ^0.4.18;

contract MyContract {
    /* Constructor */
    function MyContract() public {

    }
}
The above code will be wrong, how to modify it?

The error information is as follows.
Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.
function MyToken(
^ (Relevant source part starts here and spans across multiple lines).

**Comment by erak** [comment]
@qq597353 Can we close this issue? Did you figure out how to migrate your code?

**Comment by erak** [comment]
@qq597353 Please re-open if you encounter further issues.
