### ISSUE TITLE
Unexpected behavior while using solidity string array 

### ISSUE THREAD

**Issue by GavinDmello** [ethereum/solidity#4455]
Hello everyone,

I'm using a simple contract.

```
pragma solidity ^0.4.24;

contract Simple {

  struct S {
    string [] dps;  
  }
 
  mapping(string => S) t;

  function s(string se, string num) public {
    S storage d =  t[num];
    d.dps.push(se);
  }
  
  function g(string num) public constant returns (string[]) {
      S d = t[num];
      return  d.dps;
  }
}
```
This doesn't seem to work properly with ganache. I'm using web3@0.2 .
The first time when I call the function g, I get an array with an empty element like ['']. Also, the mutation to the dps array happens on the subsequent call, the first push always being an empty string.
Everything seems to work smoothly with remix though.

**Comment by erak** [comment]
@GavinDmello Did you enable the new, but still experimental, ABI encoder via ``pragma experimental "ABIEncoderV2";``? Because otherwise this won't compile. 
Also, have you considered creating an issue in the Truffle project (https://github.com/trufflesuite)? As far as I can tell, this seems to be an issue with Ganache and not the compiler itself (tested with Remix as well).

**Comment by GavinDmello** [comment]
@bit-shift Thanks for responding. Yea, I'm using the `pragma experimental "ABIEncoderV2";`. I think the Rinkeby test net had the same issue as well. I'll confirm and report back in a few days.

**Comment by chriseth** [comment]
Especially since you say that it works with remix, this might also be cause by not using a byzantium EVM on the network you run on.

**Comment by axic** [comment]
I think this should be covered by #4259.

Please comment if setting the proper network in Ganache doesn't solve the issue.

**Comment by panicape** [comment]
This also happened to me but no one seems to have any solution
