### ISSUE TITLE
Documentation of allowed types in mappings is misleading

### ISSUE THREAD

**Issue by Colonel86** [ethereum/solidity#4457]
`
mapping (int[2]  => int) public intFixedSizeArrKeyMap;
`
In remix browser
Solidity version
Current version:0.4.24+commit.e67f0147.Emscripten.clang

ParserError: Expected '=>' but got '['
    mapping (int[2]  => int) public intKeyMap;

But the official document does not mention it.
the official document say:"Here _KeyType can be almost any type except for a mapping, a dynamically sized array, a contract, an enum and a struct.".
It does not say that the fixed-size array cannot be an _keytype.

**Comment by erak** [comment]
@Colonel86 Thanks for opening this issue. The documentation seems to be wrong here about the allowed types.

**Comment by chriseth** [comment]
The parser only allows elementary type names.

**Comment by chriseth** [comment]
I think contracts should be fine, though.
