### ISSUE TITLE
Fuzzer catches too many exceptions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4458]
The fuzzer currently does not fail on failing assertions.

Example code (from #4417):
```
pragma solidity ^0.4.24;

contract SomeContract {

  uint public balance = 0;


  function balance(uint number) public {

  }

  function doSomething() public {
    balance(3);
  }
}
```

-- found by @mattaereal

**Comment by axic** [comment]
I think this was broken by #2213, which means for a year.

For the above example, the error returned is `InternalCompilerError: Requested type not present.`, while the fuzzer is grepping for the text `Internal compiler error`.
