### ISSUE TITLE
Attempting to uint8() a larger number causes eventual throw after array access.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/solidity#446]
The code in question is [here](https://gist.github.com/Smithgift/7cb693556470ea5764fa). Pardon the mess, I had to kludge a few things for mix to debug it.

Essentially, the line:

```
newCoords = uint8(seed);
```

attempts to turn a uint (seed) into a uint8 (newCoords). My belief was that newCoords was a truncated seed. It doesn't actually matter to me if this isn't true, because I can stick a mod 256 in there.

The issue is that this line:

```
var chosenSector = newMap[newCoords];
```

Throws. newMap is a 256 entry array. Examining it in Mix shows that newCoords isn't actually a truncated version of seed, so it goes out of bounds and throws.

Again, it doesn't really matter to me if it turns out that this isn't the right way to do it, but it's still a throw bug.

**Comment by VoR0220** [comment]
This seems to be acting as it should, though the truncation of the number is an interesting feature request...for now I would try the mod 256 but I will label this as a feature request for now.

**Comment by Smithgift** [comment]
Well, it's not so much the truncation or lack thereof that's the problem. It's that a uint8 may unintiutively not actually be a uint8, which IMHO breaks some level of type safety. In reality, mod 256 is the clearest and sanest answer.

As a philosophical question, though, what should converting a larger type into a smaller type actually do? This specific case is probably rare enough that forcing truncation may not be the best answer (especially with the performance cost of normal cases).

**Comment by Smithgift** [comment]
Here's some more weird type conversion behavior.

```
    function weird() constant returns (bool a, bool b, bool c) {
        uint foo = 257;
        uint8 bar = uint8(foo);
        uint baz = 256;
        a = bar == 1;
        b = foo > baz;
        c = bar > baz;      
    }
```

a will be true, b will be true, c will be false. So it would seem that there is a truncation going on _sometimes?_

**Comment by chriseth** [comment]
I don't see a problem with the function `weird()`. Truncation to smaller types is done in the same way it would be done in e.g. C, so `uint8(257) == 257 % 2**8 == 1`.

So `bar == 1` is what at least I would expect. Furthermore, `foo > baz`: `257 > 256` so true and finally `bar > baz`: `1 > 256` so false.

**Comment by chriseth** [comment]
Concerning the more complicated code cited in the beginning: You are right, it should not throw. Can you get a bit more information about the actual value of the uint8 - perhaps using the mix assembly debugger?

The thing is that truncation is not done immediately, it is done whenever it is needed, i.e. some values can have dirty higher order bits, but those should be cleaned as soon as e.g. the comparison is done. It might be that since the comparison with array length is implemented directly in assembly, we forgot to do that.

**Comment by chriseth** [comment]
Ok, sorry for being impatient, I was able to reproduce the bug with

```
contract C {
    function f(uint x) returns (uint[256] r){
        r[uint8(x)] = 2;
    }
}
```
