### ISSUE TITLE
 Gas estimates infinite when using libraries

### ISSUE THREAD

**Issue by denisglotov** [ethereum/solidity#4471]
The compilation of the following contract results that the gas estimate of the function `Test.increment` is infinite.

```
pragma solidity 0.4.24;

library Math {
    function add(uint256 a, uint256 b) internal pure returns (uint256 c) {
        return a + b;
    }
}

contract Test {
    using Math for uint;
    
    uint val;
        
    function increment(uint delta) public {
        val = val.add(delta);   
    }
}
```

Solc version
-------------
0.4.24+commit.e67f0147.Emscripten.clang

Reproduce steps
------------------
Use Remix, copy the above contract code there, see a blue warning ("Gas requirement of function Test.increment(uint256) high: infinite").

**Comment by chriseth** [comment]
If `val = val.add(delta);` is replaced by `val = Math.add(val, delta);`, the estimator can find a finite value. 

My suspicion is that the gas estimator cannot correctly resolve the jump destination because of the masking of the "combined function entry label".

**Comment by chriseth** [comment]
So a fix would be to either directly push the correct function entry label at the point where it is called (I think we already use this mechanism already at some other point), or make the gas estimator smarter.
