### ISSUE TITLE
solc-nightly causes test failures in OpenZeppelin

### ISSUE THREAD

**Issue by shrugs** [ethereum/solidity#4474]
hi! I perhaps might have noticed a regression in the latest nightly:

We have a contract and test case that looks like:

[ECRecovery.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/fix%2Fweb3-async-%23999/contracts/ECRecovery.sol#L18)
```solidity
  function recover(bytes32 hash, bytes sig)
    internal
    pure
    returns (address)
  {
    bytes32 r;
    bytes32 s;
    uint8 v;

    // Check the signature length
    if (sig.length != 65) {
      return (address(0));
    }

    // Divide the signature in r, s and v variables
    // ecrecover takes the signature parameters, and the only way to get them
    // currently is to use assembly.
    // solium-disable-next-line security/no-inline-assembly
    assembly {
      r := mload(add(sig, 32))
      s := mload(add(sig, 64))
      v := byte(0, mload(add(sig, 96)))
    }

    // Version of signature should be 27 or 28, but 0 and 1 are also possible versions
    if (v < 27) {
      v += 27;
    }

    // If the version is correct return the signer address
    if (v != 27 && v != 28) {
      return (address(0));
    } else {
      // solium-disable-next-line arg-overflow
      return ecrecover(hash, v, r, s);
    }
  }
```

[ECRecovery.test.js](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/fix%2Fweb3-async-%23999/test/library/ECRecovery.test.js#L65)
```js

  it('recover should fail when a wrong hash is sent', async function () {
    // Create the signature using account[0]
    let signature = signMessage(accounts[0], TEST_MESSAGE);

    // Recover the signer address from the generated message and wrong signature.
    const addrRecovered = await ecrecovery.recover(hashMessage(TEST_MESSAGE).substring(2), signature);
    addrRecovered.should.eq('0x0000000000000000000000000000000000000000');
  });
```

Our normal test suite passes, and `ECRecovery.recover` returns the zero address. But when we run the suite against solc-nightly using [this script](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/fix%2Fweb3-async-%23999/scripts/test.sh#L57) the call fails due to a revert. 

here's the ci run: https://travis-ci.org/OpenZeppelin/openzeppelin-solidity/jobs/402353224

**Comment by chriseth** [comment]
We recently added the safety (?) measure to revert on too short calldata. It might be that the second `bytes` parameter is not correctly padded to 32 bytes (yes, I know, this is questionable, but the ABI requires all array elements to be padded to 32 bytes).

**Comment by axic** [comment]
We have an open PR against this on OpenZeppelin: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1050

**Comment by shrugs** [comment]
ah, thanks for the link! will fix it today. apologies for not seeing that earlier.
