### ISSUE TITLE
how use msg.data to retrieve any payload supplied with the fallback function???

### ISSUE THREAD

**Issue by Colonel86** [ethereum/solidity#4475]
The document said：“Even though the fallback function cannot have arguments, one can still use msg.data to retrieve any payload supplied with the call.”
https://solidity.readthedocs.io/en/latest/contracts.html#fallback-function

Remix 
Current version:0.4.24+commit.e67f0147.Emscripten.clang

![1531275662072](https://user-images.githubusercontent.com/11241911/42548237-c6e9f18c-84f8-11e8-8c77-edcb2931ce7b.jpg)
This way i can get a value of 0x
![1531275742273](https://user-images.githubusercontent.com/11241911/42548427-8930912e-84f9-11e8-93e2-8450f00a4127.jpg)
when i use web3.eth.sendTransaction call fallback
params:({
  "from": "0xc577d17dc060a9a3b0b98723dc2f9eb825f1c66d",
  "to": "0xc69e559eafbf273ad9639db0ecd226a217bd2bc4",
  "gas": "0x9faa",
  "gasPrice": "0x1",
  "value": "0x111111119184e72a",
  "data": "0x00000000000000000000000000000000000000000000000000000000000000000000007b"
})
An error：VM Exception while processing transaction: out of gas

when i use web3.eth.sendTransaction call setData, it's ok.
params:({
  "from": "0xc577d17dc060a9a3b0b98723dc2f9eb825f1c66d",
  "to": "0xc69e559eafbf273ad9639db0ecd226a217bd2bc4",
  "gas": "0x9faa",
  "gasPrice": "0x1",
  "data": "0x5b4b73a90000000000000000000000000000000000000000000000000000000000000011"
})

How do I pass in data via web3.eth. SendTransaction and get it in fallback?

**Comment by chriseth** [comment]
Did you try to use the debugger?

**Comment by chriseth** [comment]
Are you sure the amount of gas you provided is enough?

**Comment by Colonel86** [comment]
@chriseth I have a different way to do it.“Even though the fallback function cannot have arguments, one can still use msg.data to retrieve any payload supplied with the call”

use call can pass msg.data, The following code：
`
contract Person{
    
    bytes public fail;
    
    function() public payable {
        fail = msg.data;
    }
    
    function getFail() public view returns (bytes){
        return fail;
    }
    function getBanlance() returns (uint256) {
        return address(this).balance;
    }
}


contract CallTest{
    constructor() payable public {
        
    }
    function callData(address addr) public returns (bool){
        return addr.call.value(1 ether)("abc", 123, "123");
    }
}
`

![1531574886055](https://user-images.githubusercontent.com/11241911/42724866-e5036dea-87ac-11e8-93ff-c72aeb6b59ea.jpg)

Thank you
