### ISSUE TITLE
Incorrect way of processing data calculation leading solc dos hang

### ISSUE THREAD

**Issue by zhongyinglou** [ethereum/solidity#4477]
Incorrect way of processing data calculation leading solc dos hang
data calculation liking a=0e123456789
[0e12345678_hang_compiler.zip](https://github.com/ethereum/solidity/files/2183697/0e12345678_hang_compiler.zip)

**Comment by zhongyinglou** [comment]
Also affects online remix ide

**Comment by chriseth** [comment]
Culprit is the literal `0e12345678`

**Comment by zhongyinglou** [comment]
This vulnerability found by security researcher limingzheng From China Beijing Chainsguard (www.chainsguard.com) .
