### ISSUE TITLE
Document the caveats/reasons around explicit conversion between bytes/uint

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4487]
A nice explanation is here: https://github.com/ethereum/solidity/issues/4341#issuecomment-402542639

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is solved, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
