### ISSUE TITLE
Incorrect assignment of struct data when containing a field of type bytesX where X < 32

### ISSUE THREAD

**Issue by ckeenan** [ethereum/solidity#449]
A struct with bytesX where X < 32 will overflow the input of subsequent fields of the struct. Placing the bytesX type last will work, however (if it is the only one of its kind in the struct). Using browser-solidity version: '0.3.0-1f9578ce/.-Emscripten/clang/Interpreter linked to libethereum-'

For example

```
struct SomeStruct {
    bytes2 testB;
    bytes32 testA;
}

testStruct = SomeStruct({
    testA: 0x0c98fceab753c7528a29469e19c7901cab3e987b379bf0627c4027ef0a6993c4,
    testB: 0x1210
});
```

testStruct will return `[ '0x1210', '0x0000000000000000000000000000000000000000000000000000000000000c98' ]` when accessed

reversing the field order results in correct values

```
struct SomeStruct {
    bytes32 testA;
    bytes2 testB;
}
```

**Comment by chriseth** [comment]
Can you please provide a full example instead of just a snippet? Is this about memory structs, storage structs or initializers?

**Comment by ckeenan** [comment]
```
contract Test {
    struct SomeStruct {
        bytes2 testB;
        bytes32 testA;
    }

    function Test() {
        testStruct = SomeStruct({
            testA: 0x0c98fceab753c7528a29469e19c7901cab3e987b379bf0627c4027ef0a6993c4,
            testB: 0x1210
        });
    }

    function add(bytes32 a, bytes2 b) {
        testStruct.testA = a;
        testStruct.testB = b;
    }

    SomeStruct public testStruct;
}
```

both the `add` and `Test` methods produce the incorrect result in my first comment

**Comment by chriseth** [comment]
This seems to be an encoding issue. In the ABI, `bytes2` and `bytes32` are both padded to 32 bytes on the right. So in your initial comment, when you say that testStruct returns `[ '0x1210', '0x0000000000000000000000000000000000000000000000000000000000000c98' ]`, the zeros probably belong to the first value and you cut off other data at the end. What did you use to decode these values?

**Comment by ckeenan** [comment]
Yeah that could be it. I'm using `web3@0.15.3`

**Comment by ckeenan** [comment]
OK I can confirm this is a web3 issue. I wrote functions that return individual fields of the structs and those verify the storage data is correct. Closing for https://github.com/ethereum/web3.js/issues/421. Thanks!
