### ISSUE TITLE
Calldata arrays with non-value base types should be disallowed by the type checker.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4490]
The unimplemented assertion in `ABIFunctions::abiDecodingFunctionCalldataArray(ArrayType const& _type)` should be caught earlier in the type checker or we just implement those types...

**Comment by axic** [comment]
@chriseth what's the status of this?

**Comment by chriseth** [comment]
I thought we decided to implement that with 0.5.4 instead of disallowing.

**Comment by chriseth** [comment]
Closing this since @ekpyron is implementing it.
