### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4491]
From the zeppelin audit:

The README in the root of the project on GitHub is what many users and contributors will read first. Thus, it is very important to make it complete and clear. Currently the Solidity README includes many links to other documents without a clear sequence or intended audience. In particular, this document does not explain the proper way to responsibly disclose security vulnerabilities found in the code.
Consider following the recommendations of [Standard Readme](https://github.com/RichardLitt/standard-readme) about sections, content and formatting.

**Comment by aj07** [comment]
@chriseth this looks good to me. I have few query like:
1. Installation part we have already included on readthedocs. Do we need to include in readme file. IMO we should keep it in read the docs. Need inputs from community on this..
2. What should we put on related Efforts section ?

**Comment by aj07** [comment]
Please, let me know if you found any typo or want to suggest any changes
