### ISSUE TITLE
Document how to test the nightly release

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4492]
Tell users how they can use remix with the nightly or truffle, etc.

**Comment by aj07** [comment]
@chriseth this question looks perfect for remix docs & truffle docs. Need an opinion on it.

**Comment by ChrisChinchilla** [comment]
@aj07 I have added minor mention to Solidity docs, happy to lend an opinion on PRs if you want to submit something to the Remix and Truffle repos (if they haven't already filled the gap).
