### ISSUE TITLE
Eth_DEVCORE_LIBRARY NOTFOUND

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#45]
on aad59bd

in build dir, running `cmake ..` gives:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Eth_DEVCORE_LIBRARY
```

**Comment by LefterisJP** [comment]
As per [the building guide](https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu) you need to also have the [cpp-ethereum](https://github.com/ethereum/cpp-ethereum), the [webthree](https://github.com/ethereum/webthree) and the [cpp-ethereum-cmake](https://github.com/ethereum/cpp-ethereum-cmake) repositories in the same directory as the solidity repo.

In addition at the moment you have to manually build cpp-ethereum and webthree before trying to build solidity.

**Comment by ethers** [comment]
yes i had those repos per the guide.

Is it worth updating the guide to have webthree build before solidity ?

**Comment by ethers** [comment]
i built cpp-ethereum master branch with `cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFATDB=1 -DBUNDLE=full -DEVMJIT=0`

it built good:
```
[ 88%] Building CXX object alethzero/CMakeFiles/alethzero.dir/main.cpp.o
[ 89%] Building CXX object test/CMakeFiles/testeth.dir/libwhisper/shhrpc.cpp.o
[ 89%] Building CXX object alethzero/CMakeFiles/alethzero.dir/DappLoader.cpp.o
[ 89%] Building CXX object alethzero/CMakeFiles/alethzero.dir/MainWin.cpp.o
[ 89%] Building CXX object alethzero/CMakeFiles/alethzero.dir/alethzero_automoc.cpp.o
Linking CXX executable testeth
[ 93%] Built target testeth
Linking CXX executable alethzero
[100%] Built target alethzero
```

but with webthree ``cmake ..`` also has same error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Eth_DEVCORE_LIBRARY
```

**Comment by LefterisJP** [comment]
Ahhh master branch? I see. There is your problem. All these are changes that are in the develop branch. Master should still be building the old way, all in one repo.

So for all the repositories mentioned above please make sure you have latest `develop` checked out and built.

**Comment by ethers** [comment]
thanks.  i've built develop cpp 3c52b7a

but with webthree ``cmake ..`` still has error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Eth_DEVCORE_LIBRARY
```

**Comment by LefterisJP** [comment]
cmake version?

**Comment by ethers** [comment]
the build directory of cpp-ethereum has to be named `build`   Renaming my build dir to `build` allowed me to build solidity.
