### ISSUE TITLE
Returning double array from library seems to have broken with 0.4.22

### ISSUE THREAD

**Issue by jmahhh** [ethereum/solidity#4506]
`a()` in the following works under 0.4.22, and throws `UnimplementedFeatureError: Nested memory arrays not yet implemented here` above:
```
pragma solidity ^0.4.24;

library aLib {
    struct aStruct {
        uint[10][51] values;
    }

    function getStruct(aStruct storage self) public constant returns(uint[10][51]) {
        return (self.values);
    }
}

contract Test {
    uint[10][51] array;
    aLib.aStruct theStruct;

    constructor(){}

    function a() public constant returns (uint[10][51]) {
        return aLib.getStruct(theStruct);
    }

    function b() public constant returns (uint[10][51]) {
        return array;
    }
} 
```

`b()` works fine across versions. Suspect this may be related to the changes to returning dynamic arrays in 0.4.22 but just guessing.

**Comment by leonardoalt** [comment]
@jmahhh Did you test that on 0.4.21? I had a suspicion that this actually didn't work even though the compiler didn't complain, so I added a function in the library to set the values and tested it on Remix with 0.4.21: the compiler doesn't complain but the values come 0 anyway!
If the version is `>=0.4.22` and `pragma experimental ABIEncoderV2` is used it works fine.
In any case this should work.

**Comment by jmahhh** [comment]
Hi @leonardoalt I see, my testing on 0.4.21 only went as far as the compiler, didn't actually check for return values. Thanks for the tip! Am I closing this?

**Comment by leonardoalt** [comment]
Let's leave it open for now. I'm still checking which cases are buggy. We might rename the issue but keep the discussion.

**Comment by leonardoalt** [comment]
@axic Consider the following code.
After testing on Remix, I have that
- function `values` works, returning `uint256[2][2]: 0,0,0,44975`
- function `libValues` returns `uint256[2][2]: 0,0,0,0`

This only happens to nested arrays (1D works with the library).

```
pragma solidity >=0.4.21;

library aLib {
    function values() public pure returns(uint[2][2]) {
        uint[2][2] memory v;
        v[1][1] = 0xcafe;
        return v;
    }
}

contract Test {
    function libValues() public pure returns (uint[2][2]) {
        return aLib.values();
    }
    
    function values() public pure returns (uint[2][2]) {
        uint[2][2] memory v;
        v[1][1] = 0xafaf;
        return v;
    }
}
```

**Comment by axic** [comment]
I think in that case this is a compiler bug we should list. In 0.5.0 it is "fixed" by properly detecting in the typechecker that it is unsupported (but also alternatively ABIEncoderV2 works with it).

**Comment by leonardoalt** [comment]
But why is it unsupported if it's fixed size?

**Comment by chriseth** [comment]
Decision on call: Severity medium, potentially low/medium depending on whether this is out in the wild or not.

**Comment by chriseth** [comment]
Analysis of Etherscan source data only revealed 7 functions that return nested statically-sized arrays and none of them is called externally from anywhere. @axic @holiman
