### ISSUE TITLE
How recuperate a result returned by calling a function of another contract.

### ISSUE THREAD

**Issue by Aghorb** [ethereum/solidity#4509]
hello,
I want to recuperate a result returned by a call to a function of another contract in my contract.
My solidity code is bellow, I have 

```
contract A {
    function verifyUser(address userAddress) public returns (bool) {
        bool verified = false;
        uint id = userId[userAddress];
        if(id != 0){
            verified = true;
        }
         return verified;
    }
}


Contract B {
function verifyUser (uint[] P, address dc, address userAddress) onlyOwner public returns (bool) {
     bool verified=false;
       for (uint i = 0; i<P.length; i++){
            if(P[i] ==1) {
                verified=dc.call(bytes4(keccak256("verifyUser(address)")),userAddress);
            }     
        }        
              return  verified ;
    }
}
```
I tested the function verifyUser of contract B and the result is always true even if the result must be false.
I work with remix  and solidity 0.4.16

**Comment by chriseth** [comment]
Please don't use `dc.call`, but use `A(dc).verifyUser(userAddress)` instead.

**Comment by Aghorb** [comment]
In fact, in my model, the two contracts must be deployed by two different entities. Hence, I think I must use dc.call to call the function of the contract A since in reality I don’t have the ABI of the deployed contract A.

**Comment by chriseth** [comment]
I'm sorry, but this issue tracker is not the right place for such questions. Have you tried http://ethereum.stackexchange.com/ ? Please reopen if you think this is indeed related to the compiler.
