### ISSUE TITLE
Add `hash` as a type alias for `bytes32`?

### ISSUE THREAD

**Issue by karalabe** [ethereum/solidity#451]
We've been working lately on a [Go binding generator](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts) for Solidity contracts and/or EVM ABIs in general and hit an interesting language limitation. Namely that the Ethereum ABI spec and hence Solidity compiler too doesn't support the concept of a `hash` type. This is a bit unfortunate since a `bytes32` cannot be automatically interpreted as a hash since it may be anything.

Given that the [Ethereum Contract ABI](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#types) explicitly specs:

> `address`: equivalent to uint160, except for the assumed interpretation and language typing.

I think it would be rational to also support `hash` for the same reasons: higher level language typing.

Edit: Of course for this to matter, we'd need to spec it at ABI level, not only as a Solidity sugar coating.

**Comment by androlo** [comment]
It used to have `hashX` types but those were removed. https://github.com/ethereum/wiki/wiki/Solidity-Features#conversion-between-string-and-hash-types

**Comment by androlo** [comment]
https://github.com/ethereum/wiki/wiki/Solidity-Features#hashxx-and-stringxx-to-bytesxx

**Comment by axic** [comment]
I think I've read the reasoning somewhere mentioning that there are many different hash widths (including > 256 bits, such as `sha512`) and it would be misleading to use it.

Personally I would like welcome one to be used with sha3/keccak, since it is agreed that is a very core element in Ethereum and is unlikely to change soon.

**Comment by karalabe** [comment]
I can understand the reasoning behind it in that there are multiple hash types so why is 256 special, but given that we even have a VM opcode for it, it can be argued that it's indeed just a bit more special then the rest.

Also @chriseth mentioned internally that `address` is special within the context of Solidity too as it's not just a 20 byte value, but also has some helper fields attached to it. So from this point of view `hash` is indeed not _that_ special.

However the reason I still think it might be worthwhile is to make it clear for dependent code that some particular 32 byte instance has specialized meaning and not just a random blob of bytes. It's kind of like using an `enum` instead of an `int` to return an error status from a C code. Even though they are exactly the same thing, the first one has a tad more connotation and is much more useful when seen in source code than the latter.

**Comment by chriseth** [comment]
I think we should have a broader discussion about this. The ABI is just an extremely low-level encoding specification. We could add another semantical layer on top of the ABI.
