### ISSUE TITLE
Proxy library always throws

### ISSUE THREAD

**Issue by kyriediculous** [ethereum/solidity#4510]
Hello. 

I'm writing a dApp using an upgradeable architecture which I call 'Registered proxy libraries'.
Simply put it's a combination of proxy libraries and contract managers/registries. 

This is how it works
storage-contract ---delegateCall() --> Proxy --delegateCall() --> Library 

In this repository you will find multiple contracts following this architecture: https://github.com/kyriediculous/blockchain-programmable-incentives

People.sol follows the exact same architecture as Timesheet.sol however the timesheet workflow does not work.

Whenever a function is being called on my library through the proxy, the call reverts. This only the case for the timesheet workflow, the people workflow works like a charm. I'm completely confused as to why, as it is completely the same architecture. 

When I change the storage directly it all works (without going through the proxy to the library). When I just use the library and storage contracts in remix it works too. So there is some issue happening with delegating the calls.

By changing the storage i mean using

```
  function isAdmin(address _user) external view returns (bool) {
    return  _timesheet.admins[_user];
  }
```

instead of 
```

  function isAdmin(address _user) external view returns (bool) {
    return  _timesheet.isAdmin(_user);
  }
```

Any ideas? It seems like it's the revert statement in assembly (proxy) causing the issue but I have no idea as to why.. Thanks...

Short version of the code where on isAdmin() remains as funtion as example

```
imesheet (STORAGE) 

    pragma solidity ^0.4.23;
    
    import '../interface/timesheet-interface.sol';
    import '../registry/enabled.sol';
    import '../util/Ownable.sol';
    
    contract Timesheet is Ownable, Enabled {
      using TimesheetInterface for TimesheetInterface.Timesheets;
      TimesheetInterface.Timesheets _timesheet;
    
      function isAdmin(address _user) external view returns (bool) {
        return _timesheet.isAdmin(_user);
      }
    
    }

TimesheetInterface (INTERFACE)

    pragma solidity ^0.4.23;
    
    library TimesheetInterface {
      struct Period {
        uint start;
        uint end;
        bool closed;
        bool processed;
      }
    
      struct Periods {
        Period[] periods;
      }
    
      struct Timesheets {
        mapping (address => Periods) timesheet;
        mapping (address => bool) admins;
      }
    
     
      function isAdmin(Timesheets storage _timesheet, address _user) external view returns (bool);
    }


TimesheetProxy (PROXY) 

    pragma solidity ^0.4.23;
    /**
     * @title Proxy
     * @dev Gives the possibility to delegate any call to a foreign implementation.
     */
     import '../registry/contract-registry.sol';
     import '../registry/enabled.sol';

    contract TimesheetProxy is Enabled {
      /**
      * @dev Fallback function allowing to perform a delegatecall to the given implementation.
      * This function will return whatever the implementation call returns
      */
      function () payable public {
        ContractRegistry contractRegistry = ContractRegistry(CMC);
        address _impl = contractRegistry.getLibrary("timesheet");
        require(_impl != address(0));
    
        assembly {
          let ptr := mload(0x40)
          calldatacopy(ptr, 0, calldatasize)
          let result := delegatecall(gas, _impl, ptr, calldatasize, 0, 0)
          let size := returndatasize
          returndatacopy(ptr, 0, size)
    
          switch result
          case 0 { revert(ptr, size) }
          default { return(ptr, size) }
        }
      }
    }


TimesheetLib (LIBRARY)

    pragma solidity ^0.4.23;
    
    import '../interface/timesheet-interface.sol';
    
    library TimesheetLib {
      event logApprovePeriod(address indexed user, uint start, uint end, bool closed);
    
      function isAdmin(TimesheetInterface.Timesheets storage _timesheet, address _user) external view returns (bool) {
        return _timesheet.admins[_user];
      }
    }
```

Also on stackexchange: https://ethereum.stackexchange.com/questions/53328/proxy-contract-library-reverts-cant-find-out-why-bounty

**Comment by chriseth** [comment]
Most of the time, such behaviour is caused by not using a byzantium EVM in the testnet. Where do you run your smart contracts?

**Comment by kyriediculous** [comment]
I was using ganache 1.1.0 but got the same results using Remix JS VM. I haven't tested with Eth-clique yet.

It works now all of a sudden, I did some minor tweaks nothing breaking.

I went through my entry point contract now (which I did before too but didn't work either) and it seems to work.

Thanks for the always quick replies!

**Comment by kyriediculous** [comment]
Nevermind.. forgot to set the contract manager address. RIP 20 Hours of my life...
