### ISSUE TITLE
Explicit gaps in storage

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4519]
This is a proposal to add explicit gaps in the storage layout of a contract (or perhaps even a struct) to help with upgradable contracts.

The problem is that whenever you want to add new storage members during an upgrade, you can only add them at the very end of the member list. It is even worse if you have two struct variables next to each other, because it basically disallows any modification to the structs.

Since the address space of storage is gigantic, it does not hurt to add a gap of e.g. 2**200 slots every now and then (apart from the increased code size of the offsets).

The syntax could be something like `storageGap(<size>)`, but it should probably be a bit more explicit.

**Comment by chriseth** [comment]
This came out of a discussion with @gnidan.

**Comment by gnidan** [comment]
Ref: #597 is a related discussion

**Comment by frangio** [comment]
OpenZeppelin Contracts has been using the "storage gaps" pattern for some time, but will be moving away from it as it doesn't solve all storage layout issues with upgradeability and it doesn't have the best possible usability. I'd recommend against this feature and instead pursuing something like https://github.com/ethereum/solidity/issues/8353, https://github.com/ethereum/solidity/issues/12513, https://github.com/ethereum/solidity/issues/597.

**Comment by ekpyron** [comment]
I'm indeed closing this in favour of the other more general solutions under consideration.
