### ISSUE TITLE
Tuple Array

### ISSUE THREAD

**Issue by ldcc** [ethereum/solidity#4529]
Can i use tuples as a type with arrays? Like this:
```Solidity
(uint, uint)[] ts = [(uint(1), uint(2)), (3, 4) ...];
```

**Comment by chriseth** [comment]
Tuples are not first-class citizens in Solidity. For now, they can only be used in expressions and for destructuring assignment, but they are not fully-fledged types.

We should clarify this in the documentation.

**Comment by ldcc** [comment]
May have any way to stores data like this and consume gas as less as possible? For instance structures array, whether will consume gas too much?

**Comment by chriseth** [comment]
I'm not sure I understand your question, but indeed, structs are very similar to tuples.

**Comment by lukehutch** [comment]
> I'm not sure I understand your question, but indeed, structs are very similar to tuples.

@chriseth Given how similar tuples are to structs, would it be possible to promote tuples to first-class types, by reusing some of the struct machinery?

**Comment by chriseth** [comment]
Yes, there are proposals along these lines.
