### ISSUE TITLE
Question: Can string be mapping key value?

### ISSUE THREAD

**Issue by KenjiOhtsuka** [ethereum/solidity#4531]
According to [Types page](https://solidity.readthedocs.io/en/latest/types.html),

> Mapping types are declared as `mapping(_KeyType => _ValueType)`. Here `_KeyType` can be almost any type except for a mapping, a dynamically sized array, a contract, an enum and a struct. `_ValueType` can actually be any type, including mappings.

`string` seems not to be able to be mapping key.

But, some codes uses `string` as key.

* https://www.toshblocks.com/solidity/general-value-data-types-solidity/
    `mapping (string => uint) public balances;`
* [integer_overflow_mapping_strkey.sol](https://github.com/trailofbits/manticore/blob/b184f4e91612a83d3bac294d2f5bf32ec2594958/tests/binaries/benchmark/integer_overflow_mapping_strkey.sol)

And in my environment, the following code worked.

```sollidity
pragma solidity ^0.4.24;

contract Proof {
    struct FileDetails {
        uint timestamp;
        string owner;
    }
    mapping (string => FileDetails) files;
    event logFileAddedStatus(
        bool status, uint timestamp, string owner, string fileHash);
    function set(string owner, string fileHash) {
        if (files[fileHash].timestamp == 0) {
            files[fileHash] = FileDetails(block.timestamp, owner);
            logFileAddedStatus(true, block.timestamp, owner, fileHash);
        } else {
            logFileAddedStatus(false, block.timestamp, owner, fileHash);
        }
    }

    function get(string fileHash) returns (uint timestamp, string owner) {
        return (files[fileHash].timestamp, files[fileHash].owner);
    }
}
```

Actually, can `string` be mapping key value?

In [Types page](https://solidity.readthedocs.io/en/latest/types.html) says,

> Mappings can be seen as hash tables which are virtually initialized such that every possible key exists and is mapped to a value whose byte-representation is all zeros

How does string virtual initialization work?

**Comment by chriseth** [comment]
Created an issue to fix the documentation: https://github.com/ethereum/solidity/issues/4532

**Comment by chriseth** [comment]
The zero-value for strings is an empty string, but this is only relevant for the mapping values.

Strings should be usable as mapping keys.

**Comment by KenjiOhtsuka** [comment]
@chriseth 

Thank you for your help.

Another question.
`string` can have too many patterns, so we can create too many mapping key and value pairs.
Can all of them be saved? and where will them be saved? swarm storage?

**Comment by axic** [comment]
A mapping always uses a hash as the key (the input is hashed), so this question exists for every kind of mapping.
