### ISSUE TITLE
Conversion to "bytes" tries to convert to storage pointer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4535]
```
contract C { function f() public pure {
  bytes("abcdefg");
} }
```

Results in `Explicit type conversion not allowed from "literal_string "abcdefg"" to "bytes storage pointer".`

I think it should rather convert to `bytes memory`.

**Comment by PhABC** [comment]
Would you also consider adding support for the following?

```solidity
contract C { 
  function f() public pure {
    bytes32 a;
    bytes(a);
  }
}
```

Also returns ; `Explicit type conversion not allowed from "bytes32" to "bytes storage pointer".`

**Comment by chriseth** [comment]
@PhABC I fear this is out of scope here.
