### ISSUE TITLE
SMT crashes on keccak256 in certain cases

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4538]
https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-solidity/master/contracts/cryptography/MerkleProof.sol crashes with:

```
/Users/alex/Projects/solidity/libsolidity/formal/SMTChecker.cpp(808): Throw in function smt::Expression dev::solidity::SMTChecker::newValue(const dev::solidity::VariableDeclaration &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

Commenting out the `keccak256` fixes it, keeping one as
```
bytes memory a;
keccak256(a);
```
keeps the crash, however having that in a separate contract within an if statement is not causing the problem, there most be some more context.

**Comment by leonardoalt** [comment]
Original file does not crash anymore on develop.

**Comment by axic** [comment]
It crashed two weeks ago, perhaps something fixed it inbetween.

Can we add these failing asserting ones into the test suite so we know when they get fixed?

**Comment by leonardoalt** [comment]
I'm usually adding all of them to `smtCheckerTests`.
Added this one here https://github.com/ethereum/solidity/pull/6237
