### ISSUE TITLE
Why the value must be 0 ?

### ISSUE THREAD

**Issue by sunhe741** [ethereum/solidity#4539]
I use the command to test， when I use --value command , the program cannot get result, however，when I drop the --value command , the vm could return the result.

 
`aleth-vm/aleth-vm --code "608060405260043610603e5763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166366a83a4f81146043575b600080fd5b348015604e57600080fd5b5060556067565b60408051918252519081900360200190f35b34905600a165627a7a7230582057e0f998af753a39292a6690c4d167e101e0d177cfc4e1138f749bf4d4456a6b0029" --input "0x66a83a4f" --value 100
Gas used: 9223372036854775807 (+21272 for transaction, -0 refunded)
Output: 
0 logs.
27 operations in 0.002669 seconds.
Maximum memory usage: 0 bytes
Expensive operations:
  MSTORE x 1 (3 gas)
`

`aleth-vm/aleth-vm --code "608060405260043610603e5763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166366a83a4f81146043575b600080fd5b348015604e57600080fd5b5060556067565b60408051918252519081900360200190f35b34905600a165627a7a7230582057e0f998af753a39292a6690c4d167e101e0d177cfc4e1138f749bf4d4456a6b0029" --input "0x66a83a4f"
Gas used: 183 (+21272 for transaction, -0 refunded)
Output: 0000000000000000000000000000000000000000000000000000000000000000
0 logs.
50 operations in 8.9e-05 seconds.
Maximum memory usage: 0 bytes
Expensive operations:
  MSTORE x 2 (6 gas)
  MLOAD x 2 (6 gas)
`
I debug the evm program and find that the instruction "callvalue"  may be caused the program , but how to resolve the problem?

**Comment by sunhe741** [comment]
could any one help me ?

**Comment by chriseth** [comment]
This could be related to the `payable` modifier.

**Comment by sunhe741** [comment]
why the function should add the payable ?

**Comment by randomnetcat** [comment]
As a safety measure, unless you mark a function as payable, it CANNOT be called with a nonzero value, doing so reverts the entire transaction.

**Comment by sunhe741** [comment]
ok,3q

**Comment by axic** [comment]
I think this is answered.
