### ISSUE TITLE
Run install script in CentOs failed, repo link invalid

### ISSUE THREAD

**Issue by Justme0** [ethereum/solidity#4540]
In scripts/install_deps.sh, `sudo wget http://repo.enetres.net/enetres.repo -O /etc/yum.repos.d/enetres.repo` failed, because http://repo.enetres.net/enetres.repo is invalid.

**Comment by axic** [comment]
Thanks! Can you find a new repo for the updated boost?

**Comment by Justme0** [comment]
No. I downloaded the newest Boost from official website. But I encountered many problems
similar to issue #538 ，so I installed old version Boost 1.54.0, which is ok : )

**Comment by chriseth** [comment]
If we cannot find a new link, let's remove centos from the script.

**Comment by erak** [comment]
@Justme0 We finally created a PR that should fix this issue. Could you verify that it works with the new URL added here: https://github.com/ethereum/solidity/pull/6273? Thanks in advance!
