### ISSUE TITLE
Documentation: Updating solidity in compile from source version

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#455]
There is currently no documentation on updating solidity when compiled from source. Should be an easy bit to describe.

**Comment by bobsummerwill** [comment]
What do you think of the idea of merging the Solidity readthedocs content into http://ethdocs.org, @chriseth?

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/

When we've done the repo re-org, we'll end up with the following repos each of which should be buildable independently, and each of which should have pretty much the same instructions.
- alethzero (until it is killed)
- cpp-ethereum
- mix
- solidity

**Comment by VoR0220** [comment]
I'm for that.

**Comment by chriseth** [comment]
@bobsummerwill could you explain a bit more what you mean by "merging"? The solidity docs are the language reference and I think it should be tightly coupled with solidity - features should be documented in the same commit or PR in which they are implemented. How to build solidity can be a link into the ethdocs page.

**Comment by bobsummerwill** [comment]
Oh - I see, so the readthedocs for solidity are within a sub-folder of the solidity repo itself?    I assumed that there was another repo for them (as we have for homestead docs).

I guess the same argument holds for the cpp-ethereum docs, eh?    They are currently hosted in https://github.com/ethereum/homestead-guide/tree/master/source/ethereum-clients/cpp-ethereum, but with the repo reorganization, it would arguably be better for them to move to https://github.com/ethereum/cpp-ethereum/docs, so they can also be 1-1 updated in parallel with code changes.

Right now we have a mixture of different approaches.
