### ISSUE TITLE
It should be possible to assign built in functions to function types

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4551]
For example this should work:
```
contract C {
  function f() {
     function (uint) view returns (bytes32) _blockhash = blockhash;
  }
}
```

Fails with an error currently:
```
blockhash.sol:3:6: Error: Type function (uint256) view returns (bytes32) is not implicitly convertible to expected type function (uint256) view returns (bytes32).
     function (uint) view returns (bytes32) _blockhash = blockhash;
     ^-----------------------------------------------------------^
```

(This was marked as a bug #2996 previously.)

The reason is that these built in functions have their special type internally, which cannot be represented by function types. While this is not crucial, it could be a nice feature in the future.

**Comment by chriseth** [comment]
I actually don't think it should be possible.

**Comment by cameel** [comment]
I wonder how it would be handled in internal dispatch. Special IDs reserved for these built-in functions?
