### ISSUE TITLE
Discussion: Accessing Comments

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#4559]
I think it would be quite useful to allow access to the comments placed within contracts.

In my understanding comments are mainly just discarded, or parsed as `natspecs` and added to specific AST nodes - `ContractDefinition`, `FunctionDefinition`, `ModifierDefinition`, `EventDefinition` -  the `Statement` is also inherited by `Documented` - but it looks like that the `documentation` information is never used. The `DocStringAnalyser` is responsible for the extraction of the documentation - it will extract the documentation from the AST for `ContractDefinition`, `FunctionDefinition` `ModifierDefinition` and `EventDefinition`.

From my point of view the access to “user-defined” additional data (in this context: comments) would be quite interesting. This information may be used by frameworks, IDE’s and other tools to enable specific features. E.g. generators may use those user informations to generate additional functions/files/features, test-frameworks could be implemented in a way that test-code can be embedded into contracts. IDE’s may use these information to highlight specific information - especially if used with generators or other frameworks this may become quite interesting.

This was also the idea that I had in mind when I created PR #3630. I didn’t wanted to mix the only “documentation” aspect of natspecs with things that may be defined by external tools. 

In contrast to natspecs comments can be placed everywhere in the code. So comments are more generic and may be more useful if accessible to other tools.

It may be important to allow access to the position information of different comments within the source. This will enable nice visualisations within IDE’s - e.g. embedded test-cases may be coloured according to their execution results and would probably help generators. It may be also important to preserve new-lines, to simplify parsing of embedded code, e.g. exact locations of parsing errors can be easily calculated.

What do you think about allowing access to comments placed within contracts? What would be the best way to implement that? Should comments be added to the AST? Or is it better to design a new API / or from the `solc` command line interface point of view a new output command e.g. `—comments`.

**Comment by axic** [comment]
I think #1771 is a relevant issue?

**Comment by aarlt** [comment]
@axic Thx! Seem to be a relevant issue. So should I add the comments to the AST? I just want to ensure - before I do anything - that it makes sense and is useful for others.

**Comment by aarlt** [comment]
@chriseth i had some time to understand the related code a bit better.. my first impression of the code was not fully wrong. it looks like that comments will really just get discarded - but in contrast doc strings will be available per `AST` node that is `Documented`. After there creation the documentation is only accessed through the `DocStringAnalyser` that will just extract `natspec` specific documentation. However, the rest of the already parsed and nicely placed `Documented` parts are not accessed or used. I guess you meant exactly that with #1771. If you provide some additional information where do you want to store the _inline docs_ within the `AST` I could probably help.

I'm somehow not really sure whether the effort for keeping the comments and make them accessible is worth it. What do you think?

**Comment by chriseth** [comment]
Inline-docs with triple-slash were used before to add why3 comments. We might re-enable that in the future, so it would be good if they could be retained in the ast export. The ASTJson converter should be able to put them into the export.

**Comment by axic** [comment]
Some relevant discussions were conducted in #8802 and #8146.

**Comment by cameel** [comment]
We actually have a new issue to address this (#13865) so I'm closing this one.

If there's anything relevant here that is not covered by the new issue, please post it there.
