### ISSUE TITLE
Addition of Maintainers file

### ISSUE THREAD

**Issue by aj07** [ethereum/solidity#4573]
Like Readme, there should be the list of MAINTAINERS file where list of people and their particular domain should be listed. 

example:  https://github.com/gluster/glusterfs/blob/master/MAINTAINERS

**Comment by axic** [comment]
Note that we are following the goal that there is no specific ownership, rather everyone should be familiar with every part of the compiler.

Given the codebase is relatively small, this should be possible as of today. This may change in the future if it grows significantly.
