### ISSUE TITLE
Incorrect InfoFeed example

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#4574]
As discussed in a now closed PR, the text around `infoFeed` in _control-structures.rst_ needs tweaking.

![screen shot 2018-07-06 at 17 11 55](https://user-images.githubusercontent.com/42080/43193104-6bc9713a-8fff-11e8-9815-dd209062448c.jpg)

**Comment by chriseth** [comment]
Can you link the PR comment? Closed PRs are not deleted and can be linked just as open PRs can.

**Comment by ChrisChinchilla** [comment]
@chriseth I could not find it when I last looked, but strangely now I can :/

https://github.com/ethereum/solidity/pull/4420#discussion_r200077162
