### ISSUE TITLE
Inline assembly: properly consider "super" as an unknown identifier as an lvalue

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4575]
`super` as an RValue has the `Identifier not found` error, however `super` as an LValue produces the `Only local variables can be assigned to in inline assembly.` error, which suggests it is available.

Found in #4555.

**Comment by chriseth** [comment]
Would this be a good "help needed" issue of medium difficulty?

**Comment by chriseth** [comment]
clarification: rvalue means: `assembly { let x := super }` lvalue means: `assembly { super := 2 }`

**Comment by chriseth** [comment]
The fix probably needs to go into `bool TypeChecker::visit(InlineAssembly const& _inlineAssembly)`

**Comment by HenryRLee** [comment]
If I do `assembly { what := 2 }`, the actual error is "Variable not found or variable not lvalue."

Should we use the same error for `assembly { super := 2 }`?
