### ISSUE TITLE
Yul: implement continue, break and return in for loop

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4576]
Add "break" and "continue" with the usual semantics to Yul. This needs some changes (and further tests) in the following optimizer steps (might not be exhaustive):

Trivial:
 - ASTCopier (et al.)
 - ASTWalker (et al.)
 - DataFlowAnalyzer
 - RedundantAssignEliminator

The structural simplifier could need some additional rules (remove dead code after unconditional "continue" or "break"), but these might be added later.

**Comment by chriseth** [comment]
"return" should not take any arguments.

We have a collision between the concept of returning from a function and the return opcode.

Brainstorming for renaming one of them:
 - finish
 - break_function
 - leave
 - exit

**Comment by chriseth** [comment]
Split out the dead code removal into its own issue: https://github.com/ethereum/solidity/issues/6328

**Comment by Marenz** [comment]
Couldn't we just reuse `break`?
