### ISSUE TITLE
Apply the style guide to all the code tutorials in the documentation

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4580]

**Comment by axic** [comment]
@ChrisChinchilla if you have interest, you could start with the shortest example and see how it goes.

**Comment by ChrisChinchilla** [comment]
@axic I will, but might take this after finishing some other tasks.

**Comment by ChrisChinchilla** [comment]
I might also look into automating style tests 🤔

**Comment by axic** [comment]
> I might also look into automating style tests 🤔

That would be cool. Probably there is a linter somewhere already.

**Comment by ChrisChinchilla** [comment]
Now in progress

**Comment by Marenz** [comment]
is this done?

**Comment by ChrisChinchilla** [comment]
Nope I am still waiting for this to be merged…

https://github.com/ethereum/solidity/pull/6416
