### ISSUE TITLE
Calling safeWithdrawal() in crowdsale contract failed

### ISSUE THREAD

**Issue by chenweiyj** [ethereum/solidity#4586]
I am using the [crowdsale contract](https://ethereum.org/crowdsale) in the official ethereum site. And I am testing it in Rinkeby network. When the crowdsale is over, `msg.sender` cannot withdraw the ether. The blockchain browser shows the transaction is failed.
[
https://rinkeby.etherscan.io/tx/0x4102c2af42f422cbfe7a45fe52806b4cb418b2ea6f7176932891694cad9b0a55](https://rinkeby.etherscan.io/tx/0x4102c2af42f422cbfe7a45fe52806b4cb418b2ea6f7176932891694cad9b0a55)

I am using solidity 0.4.21, and deploying the contract via ethereum-wallet.

**Comment by axic** [comment]
In the above transaction you are not actually calling `safeWithdrawal()`, just making a regular transaction.

This question is better suited for https://ethereum.stackexchange.com/
