### ISSUE TITLE
Error reason strings in `require()` and `revert()` are expensive. Is that expected behavior?

### ISSUE THREAD

**Issue by chapati23** [ethereum/solidity#4588]
Hey :)

we just upgraded the solidity version for all our contracts to `v0.4.24` and were pretty excited to start adding error reasons to all our `require()`s and `revert()`s.

However, we were pretty shocked to find that in our case this led to an average increase of 10% towards the gas limit.

**Is that expected that error reason strings are that expensive?**

Couldn't find anything in the docs that would have hinted at this tradeoff. Curious to hear some opinions.

### Gas Limit Usage Before Reason Strings
<img width="1130" alt="gas limit usage before reason strings" src="https://user-images.githubusercontent.com/117495/43265853-3bc63e1e-90ea-11e8-8af4-ed8146f99669.png">

### Gas Limit Usage After Reason Strings
<img width="1125" alt="gas limit usage after reason strings" src="https://user-images.githubusercontent.com/117495/43265871-47395006-90ea-11e8-9d60-3dd8e150d843.png">

**Comment by axic** [comment]
Do you mean those are the deployment cost after only adding error messages to `require`? If so, how many and how long those error messages are?

**Comment by chapati23** [comment]
Yes, that's what I meant. I think I'm getting a better understanding of this now.

Can you confirm whether the following assumption is correct: Adding the error string `Not Authorized. This function can only be called by the custodian or owner of this contract` to a `require()` would add 60,000 gas towards the block gas limit. String has 95 bytes, so will need three 32-byte slots from storage => 3 * 20,000 => 60,000?

If that's the case then I think I better understand the WHY now, however, was still a bit surprised as it actually incentivises slightly against using this feature at all. At least in larger contracts that are getting closer to the gas limit.

**Comment by axic** [comment]
It will not be part of storage, but more likely be stored as a combination of push and mstore.

This input:
```
contract C {
  function f(uint a) public pure {
    require(a > 5, "Not Authorized. This function can only be called by the custodian or owner of this contract");
  }
}
```

Is compiled to:
```
    tag_6:
        /* "assert.sol":64:65  5 */
      0x5
        /* "assert.sol":60:61  a */
      dup2
        /* "assert.sol":60:65  a > 5 */
      gt
        /* "assert.sol":52:161  require(a > 5, "Not Authorized. This function can only be called by the custodian or owner of this contract") */
      iszero
      iszero
      tag_8
      jumpi
      mload(0x40)
      0x8c379a000000000000000000000000000000000000000000000000000000000
      dup2
      mstore
      0x4
      add
      dup1
      dup1
      0x20
      add
      dup3
      dup2
      sub
      dup3
      mstore
      0x5b
      dup2
      mstore
      0x20
      add
      dup1
      0x4e6f7420417574686f72697a65642e20546869732066756e6374696f6e206361
      dup2
      mstore
      0x20
      add
      0x6e206f6e6c792062652063616c6c65642062792074686520637573746f646961
      dup2
      mstore
      0x20
      add
      0x6e206f72206f776e6572206f66207468697320636f6e74726163740000000000
      dup2
      mstore
      pop
      0x60
      add
      swap2
      pop
      pop
      mload(0x40)
      dup1
      swap2
      sub
      swap1
      revert
    tag_8:
        /* "assert.sol":15:166  function f(uint a) public pure {... */
      pop
      jump	// out
```

Then deploying this bytecode is of course charged per non-zero byte, of which there are a lot due to the messages.

**Comment by chapati23** [comment]
Ok, thanks. I think a little warning or note in the docs reminding users that error strings can get expensive would be nice but as I have a better understanding of this now, I’ll close this.

Thanks for the explanation @axic

**Comment by axic** [comment]
Will be solved by #4774.

**Comment by jdspugh** [comment]
How about storing require() and revert() messages as part of the ABI to save on-chain space? The ABI can be published on less critical storage systems like Etherscan so the users can still see them.

**Comment by cameel** [comment]
This problem has already been solved. The modern alternative to having string mesages are [custom errors](https://docs.soliditylang.org/en/latest/contracts.html#errors-and-the-revert-statement).

There's also an alternative proposal for an error code system (#9813). The codes could be mapped to error messages specified out of band like you're proposing. There's not much motivation to implement it though given that custom errors solve basically the same problem.

**Comment by jdspugh** [comment]
Thanks for the update. Good to know. I'm using custom errors now. Next phase I imagine will be having a set of standardised custom errors for common use cases like InsufficientBalance so blockchain viewers can easily interpret them even without the source code/ABI.

**Comment by Assawal** [comment]
Sent from my Huawei phone-------- Original message --------From: Jonathan Pugh ***@***.***>Date: Sun, 30 Jan 2022, 09:39To: ethereum/solidity ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [ethereum/solidity] Error reason strings in `require()` and `revert()` are expensive. Is that expected behavior? (#4588)
Thanks for the update. Good to know. I'm using custom errors now. Next phase I imagine will be having a set of standardised custom errors for common use cases like InsufficientBalance so blockchain viewers can easily interpret them even without the source code/ABI.

**Comment by chriseth** [comment]
Just to clarify because it is not clear whether this is part of the ABI: The recommended way to document custom errors (and thus get actual strings) is via natspec.
