### ISSUE TITLE
Solidity compiler has limit of assignments to a mapping oO

### ISSUE THREAD

**Issue by Blackening999** [ethereum/solidity#4591]
Recently, while working with another smart contract we have been surprised in a team how many mappings and mapping assignments there are.

And using method of exclusions - realised that compiler fails if reach a specific limit of performing assignments to a mapping.

Has anyone faced the similar issue?

**Comment by erak** [comment]
@Blackening999 Could you please provide an example that triggers the behaviour you described?

**Comment by mattaereal** [comment]
Hi @Blackening999, the limit itself is on how many assignments are made inside one mapping, or through different mappings?

If you could add some code that'd be wonderful.

**Comment by Blackening999** [comment]
Well, I can't as the code is under NDA. It's easy to reproduce by putting as much assignments as possible and see when it breaks. We also starting thinking of that too complex contracts might not work as well, not just because of number of assignments

**Comment by codeandgraphics** [comment]
I'm working with @Blackening999 on this contract, so this issue in fact is not about limit of assignments, it's about huge contract size, mappings limit is just a symptom.
Seems like this issue can be closed
