### ISSUE TITLE
Add map/filter/reduce/range/all/any to avoid accidental bugs in for loops

### ISSUE THREAD

**Issue by vietlq** [ethereum/solidity#4596]
The `for` loops are too verbose and any user can make mistake when increasing/decreasing counters: https://github.com/makoto/blockparty/issues/175

It would be much better to have `map/filter/reduce/range/all/any` like in Python so people can iterate and apply input in consistent and uniform way that is safe and easy to read.

You may refer to all built-in Python functions here:

https://docs.python.org/2/library/functions.html

**Comment by chriseth** [comment]
While this is a good idea, most of the operations that could benefit from that are rather expensive so it is questionable whether such things would be used much, but as I said, still nice to have.

This probably requires #911 and perhaps even #869 to be really useful.

**Comment by leonardoalt** [comment]
I don't think it'd need https://github.com/ethereum/solidity/issues/869, unless it supports more than arrays., but I think it needs https://github.com/ethereum/solidity/issues/911 with capturing

**Comment by axic** [comment]
We discussed as part of https://twitter.com/nomorebear/status/1254000358361186306, range based loops would have avoided some mistakes. (But also unit testing would avoid them too)

**Comment by Marenz** [comment]
I am absolutely in favor of range-based loops at the very least.
