### ISSUE TITLE
Ability to declare visibility levels inside of struct fields

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#460]
Surely there's a reason for why this is currently not doable, but I would like to know what those reasons are at present and if it's possible to do something about that?

**Comment by chriseth** [comment]
The reason is that for contract-level identifiers, you can actually enforce visibility using the EVM. No such thing is possible for structs and this concept does not even exist in javascript, so it was not introduced.

**Comment by VoR0220** [comment]
actually...apparently you can do something akin to that in JS....https://developer.mozilla.org/en/docs/Web/JavaScript/Closures#Emulating_private_methods_with_closures

What would be the chances of emulating this in Solidity?

**Comment by chriseth** [comment]
This provides the same level of (fake) protection, I don't think we should have that. structs are simple data types that are public and modifyable for all.
