### ISSUE TITLE
Change readthedocs so that the "latest" tag points to the last release

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4610]
Currently it seems to be pointing to "develop".

**Comment by rafialhamd** [comment]
Maybe there should be '**develop**' too, in addition to '**latest**'... so that one could fix things like this!

**Comment by axic** [comment]
There is `develop` on readthedocs already 😉

**Comment by rafialhamd** [comment]
Thanks! It's far below... didn't notice!

**Comment by chriseth** [comment]
I don't see how this can be done. We can just remove `latest` - the "default" version is a different setting and it is set to 0.4.24.

**Comment by ChrisChinchilla** [comment]
It does look like RTD automates most of this, and while it may be possible to reorganise the repository branches and tags to get this working, it's probably a lot of work for a small return (IMO).

https://docs.readthedocs.io/en/stable/versions.html
