### ISSUE TITLE
Addition of checklist item

### ISSUE THREAD

**Issue by aj07** [ethereum/solidity#4613]
In http://solidity.readthedocs.io/en/v0.4.21/contributing.html  there is a pull request section. There is a need to add checklist and  criteria before sending any PR. 

Checklist [this section needs to be added]

    Code compiles correctly
    All tests passing
    Created tests which fail without the change (if possible)
    Extended the README / documentation, if necessary
    Used meaningful commit messages

**Comment by chriseth** [comment]
Please do!
