### ISSUE TITLE
State that data representation of enums is the same as in C

### ISSUE THREAD

**Issue by BrendanChou** [ethereum/solidity#4624]
We should probably not say it explicitly like that but explain that values are assigned subsequent integers starting from zero.

Original issue:
----
Solidity documentation does not guarantee that the underlying integer values are 0,1,2,3... for enum types. See: https://solidity.readthedocs.io/en/v0.4.24/types.html#enums

Please either guarantee these values, or if they are already guaranteed, then note it in the documentation.

Pointed out by https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1057#pullrequestreview-141303390

**Comment by axic** [comment]
I  agree that it would be nice clarifying this. Since values of `enum`s cannot be defined in the syntax, it seems logical that we make commitment (and document that) to how the values are assigned.

Later we could considering overriding the values as a syntactical feature, if desired.
