### ISSUE TITLE
Return after selfdestruct

### ISSUE THREAD

**Issue by u2** [ethereum/solidity#4628]
Hi, I want to return some data after `self-destruct` instruction.
```
pragma solidity ^0.4.18;


contract FakePermissionManagement {
    function setAuth(address _auth) public returns (bool) {
        selfdestruct(_auth);
        return true;
    }
}
```
I have tested in Remix, but it always return false.
In the [docs of solidity](https://solidity.readthedocs.io/en/v0.4.24/assembly.html?highlight=selfdestruct#opcodes), the description as below

> 

selfdestruct(a) | - | F | end execution, destroy current contract and send funds to a
-- | -- | -- | --

So, I think the `return true` will never be reached. So I think the solidity compiler should give some warning about that. Right?

**Comment by axic** [comment]
Thanks! Yes it would be nice to show unreachable code, we have an issue tracking that feature in #2340.

I'm not sure how frequently people try to return something after `selfdestruct`, but I think it would be possible to show a warning in Remix specifically for cases like this, @soad003 ?
