### ISSUE TITLE
Proposal: Increase transfer and send gas limit

### ISSUE THREAD

**Issue by ben-kaufman** [ethereum/solidity#4630]
Currently, ``transfer()`` and ``send`` address functions have a limit of ``2,300 gas units``.
As far as I know, this limit was added to prevent reentrancy attacks.
This limitation should be enough (in general) for some small (gaswise) operations, for example, triggering events.

I believe this limitation is too restrictive and should be raised to around ``3,500 gas units``.

My main concern regarding this limitation is the problem it causes with Proxy contracts.
As the Proxy pattern getting more popular, it has a big disadvantage of using around ``1,000 gas units`` on average, thus, when triggering the fallback function of its logic contract, it has only around ``1,300 gas units`` for the fallback's actual execution.
For my own implementation, I had enough gas to use ``LOG`` with one non-indexed parameter. Everything above that crossed the limit. While other implementation might be able to do a bit more it still won't have the sufficient gas for decent logging.
Raising the limit to cover up for the Proxy costs should allow decent fallback functions for proxies.
I also don't see any reason for the limit to be this low as even with a slightly higher limit it is still not possible to cause state changes in other contracts.

**Comment by axic** [comment]
Since the 2300 gas is added by design of the EVM (when there is a non-zero value transfer), there is nothing the Solidity compiler is doing here.

Note: the compiler adds an extra piece of code to ensure 2300 is sent even when the value being sent is 0.

As you noted, the goal with `transfer` is to only offer value transfer based on the protocol rules and to not facilitate general function execution.

Therefore I suggest to raise this suggestion on https://github.com/etheruem/EIPs

**Comment by axic** [comment]
@ben-kaufman does this answer your question/proposal?

@ChrisChinchilla is the documentation properly describing this caveat of `transfer`?

**Comment by ben-kaufman** [comment]
@axic Yes, thanks.

**Comment by ChrisChinchilla** [comment]
@axic I had a look, and it's mentioned in a few places as being a 'gas stipend', but not really anywhere that it's a limit, which seems important, so I'll create an issue/PR for this.

**Comment by axic** [comment]
Thanks!

**Comment by axic** [comment]
An EIP has been proposed to change this: https://github.com/ethereum/EIPs/issues/1285

**Comment by shanefontaine** [comment]
> Note: the compiler adds an extra piece of code to ensure 2300 is sent even when the value being sent is 0.

@axic is there reasoning behind this decision?

**Comment by CryptoKiddies** [comment]
> > Note: the compiler adds an extra piece of code to ensure 2300 is sent even when the value being sent is 0.
> 
> @axic is there reasoning behind this decision?

+1 the compiler should not be opinionated on this matter, following the restrict first then relax security pattern.
