### ISSUE TITLE
Allow type definitions at global level

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4634]
(there might be a duplicate of this issue)

Currently, all top-level objects have to be contracts, but it would be very helpful to at least allow definitions of structs and enums at global level (although even internal functions might).

This would make it easier to use structs with libraries:

```
struct Balances {
  uint a; uint b;
}
library Balances_lib {
  function f(Balances storage b) internal { ... }
}
using Balances_lib for Balances;
```

Merely importing this file will provide direct access to the struct and functions for it. Allowing global declarations like that is still useful without the `using` directive.

**Comment by axic** [comment]
It is in #4029.

**Comment by chriseth** [comment]
Thanks!
