### ISSUE TITLE
"closed" structs

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4637]
This came out of https://github.com/ethereum/solidity/issues/4636 - it might make sense to declared certain structs to be closed in the sense that any write access to members of the structs can only be performed inside a certain library. This way, auditing the behaviour of such structs can be limited to auditing the library itself. For a token contract, for example, we could have certain functions which modify the balances that have certain guarantees. If the balances cannot be modified anywhere else, it is sufficient to only check the library.

**Comment by ekpyron** [comment]
Sounds like a good idea. It will probably be possible to sneak around this restriction at the EVM/assembly level, but it will probably still be helpful.

**Comment by axic** [comment]
Sounds good, I wonder if we should just add function members on structs for doing so? (No proposal yet.)

I guess adding function members is the C++ way and what we have now is kind of the Rust way.

**Comment by chriseth** [comment]
So we would have something like

```
struct S semantics LibraryName { ... }
```

although we should find a better keyword there :)
```

**Comment by federicobond** [comment]
+1 on the proposal. It would become an "opaque" data structure. right? I vote for overloading the keyword `private` for this use case.

Opaque structs should not allow instantiation via raw struct constructors. Any initialization should be done via an exposed library function.

**Comment by chriseth** [comment]
@federicobond good point about instantiation - you are totally right! Although this might be difficult for storage structs and zero-initialization, especially for structs as mapping values.

As far as the syntax is concerned: Would you propose `struct S private to LibraryName { ... }`?

We could also use `struct S internal in LibraryName { ... } ` or
`struct S { ... } LibraryName implements S`.

`struct S implementedBy LibraryName { ... }`?

**Comment by chriseth** [comment]
Actually it would even make sense for this to implicitly enable `using LibnaryName for StructType`, so perhaps this could be an extension of the `using` directive and not the struct declaration - of course this only becomes useful once we allow `using` at the file level, but then it might be complicated to get the import semantics right....

**Comment by chriseth** [comment]
So in the end, we should perhaps both have `using` and `private to LibraryName` as part of the struct type itself and not local to some scope.

**Comment by spalladino** [comment]
Maybe I'm missing something, but if the struct is to be instantiated and modified only inside a certain library, shouldn't it be defined in that library as well? So, instead of having a `using Struct private to LibraryName`, the struct is defined within the library and must be referred to with a qualified name when used. Something like:

```solidity
library MyLibrary {
  struct MyStruct { ... }
}

contract MyContract {
  using MyLibrary;
  MyLibrary.MyStruct field;
}
```

**Comment by chriseth** [comment]
@spalladino I think that is just very redundant.

**Comment by nventuro** [comment]
This sounds like a very useful feature: see [this comment](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1023#issuecomment-401479456) for a recent instance were OpenZeppelin could've benefited from it.

**Comment by nventuro** [comment]
If the whole purpose of the library is to provide methods to the struct, why give a name to both? I like @axic's suggestion of adding functions directly to the struct (and tagging struct members `private` if desired), though we'd then have the problem of importing it: afaik, the only allowed top-level constructs are libraries and contracts.

**Comment by ekpyron** [comment]
#6920 in combination with this suggests that it might make sense to add some kind of notion of "inheritance for libraries" or "library interfaces", so that different libraries implementing a particular interface can access the struct (to satisfy both use cases it'd of course have to be possible to allow and disallow access via inheritance).

**Comment by nventuro** [comment]
@ekpyron are you suggesting something along the lines of what C++ does with `public`, `protected` and `private`? (brief description [here](https://en.wikipedia.org/wiki/C%2B%2B#Encapsulation))

**Comment by ekpyron** [comment]
@nventuro Yes, something like that - if we extend the proposal in this issue like that, we'd probably reasonably solve the request in #6920 as well using one and the same language concept. So far, however, we don't have library inheritance at all, so we need to decide whether it's worth to introduce it for this purpose.
EDIT: although I'm actually not sure whether the state transition contracts in #6920 should actually be libraries or whether it should be regular contracts.

**Comment by dOrgJelli** [comment]
Does anyone know if an EVM opcode has been proposed to white-list or black-list sections of the executing contract's storage? This would allow (for example) a proxy contract to freeze a struct before loading & running a logic contract.
