### ISSUE TITLE
enums with specified values

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4638]
Currently `enum`s cannot have values specified by the user, they always start from 0 and steadily increase.

Proposal is to support user specified values in the form of:
```
  enum Direction {
    East: 90,
    West: 240,
    North: 0,
    South: 180
  }
```

The colon makes sense because we use this syntax for named arguments already.

I would suggest that this is introduced with strict rules: either all of the items have their value specified or none of them. This avoids the need of special rules (for example what is the value of an unspecified item after a specified one?).

(Sparked by #4624)

**Comment by chriseth** [comment]
This sounds like a complication, but perhaps not an unsafe one.

I would opt to put that in 0.6.0, though.

**Comment by chriseth** [comment]
@christianparpart suggests alternative syntax to use `=`

**Comment by ekpyron** [comment]
I'm actually still not entirely clear about why this is necessarily breaking.

**Comment by cameel** [comment]
We discussed it on the meeting today and the answer was that it's not breaking :) So I'm moving it to non-breaking backlog.

Also, the consensus right now is that we're still lacking a good use case for this. So putting it in the Icebox seems like the right thing to do too.

One minor downside to allowing arbitrary (and especially non-contiguous) values is that the runtime check becomes more expensive. That's only if the values are actually non-contiguous but this might not be obvious to users and they might be choosing values that just look good for one reason or another, not being aware of the extra cost.

**Comment by cameel** [comment]
Actually, looking at the linked Loopring issue, the use case I suggested at the meeting - using values as bit masks - is not as far fetched as I thought. Some developers are trying to use them like that in Solidity (https://github.com/Loopring/protocols/pull/828#discussion_r354903437). This was the code used to work around this:

```solidity
library GuardianType
{
    function None()            internal pure returns (uint) { return      0; }
    function EOA()             internal pure returns (uint) { return 1 << 0; }
    function SelfControlled()  internal pure returns (uint) { return 1 << 1; }
    function Hardware()        internal pure returns (uint) { return 1 << 2; }
    function Device()          internal pure returns (uint) { return 1 << 3; }
    function Service()         internal pure returns (uint) { return 1 << 4; }
    function Family()          internal pure returns (uint) { return 1 << 5; }
    function Friend()          internal pure returns (uint) { return 1 << 6; }
}
```

**Comment by chiro-hiro** [comment]
[EIP-6366](https://github.com/ethereum/EIPs/pull/6366) can be benefited from this feature.
