### ISSUE TITLE
Regarding the solc --bin-runtime for a contract

### ISSUE THREAD

**Issue by norhh** [ethereum/solidity#4643]
I have a question regarding solc. solc doesn't give any byte code for the contract MintableTokenImpl for this [code](https://etherscan.io/address/0x6342eabec28aec4902432d852dcd08d4f6df96ab#code) .All the bytecode of MintableTokenImpl is being placed in ZenomeToken contract  when
 `solc -o out  --bin --bin-runtime --asm --opcodes file.sol` is run, it doesn't seem like MintableTokenImpl is an interface so it seems to be like it is a bug , but i am not sure.

___Expected behaviour:___
The MintableTokenImpl contract's byte code should be shown in that contract's file itself.But i am not sure that was what was expected.

__Versions__
solc version:- 0.4.25-develop.2018.6.21+commit.32f2db78.Linux.g++
os: Ubuntu:- 17.10

**Comment by chriseth** [comment]
`MintableTokenImpl` is indeed abstract. There is an easy way to check which will also give you the reason it is abstract: Add a snippet like the following to your code:
```
contract A {
    function f() public {
        new MintableTokenImpl();
    }
}
```

The compiler will tell you:
```
browser/Untitled12.sol:348:9: TypeError: Trying to create an instance of an abstract contract.
        new MintableTokenImpl();
        ^-------------------^
browser/Untitled12.sol:204:5: Missing implementation:
    function checkOwner() internal;
    ^-----------------------------^
```
