### ISSUE TITLE
SMT: have a cmake option to disable z3 and/or cvc4 even if an installation is found

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4651]
This can be useful mostly in the case when there is an installation issue and the compiler fails to compile, but the user cannot/don't want to uninstall the dependency.

It shouldn't be more than 2-3 lines of cmake code.

**Comment by mattaereal** [comment]
I already did this. I'm doing a PR soon.

**Comment by mattaereal** [comment]
Done!
