### ISSUE TITLE
Proposal to have "external contribution" label on PRs

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4653]
To signal that it is being done by a volunteer contributor and that we should pay more attention at responding in a timely manner.

I think however we should have this written in the contributors guide so that no confusion arises as of why is there such a label.

**Comment by chriseth** [comment]
What about creating a project or project column for that?

**Comment by axic** [comment]
I think a project may be too much overhead (what are the columns? where to move? who moves?).

And if not creating its own project, what project to put them into?

Considering these two questions labels seem to be the least maintenance.

**Comment by axic** [comment]
Agreed on the weekly meeting to go with the label approach first.
