### ISSUE TITLE
Constant variables referenced from inline assembly causes weird error.

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#466]
```
contract C {
    uint constant X = 5;

    function() {
        assembly {
            X
        }
    }
}
```

`Compiler error: Given source file not found.`

Latest browser-solidity. Remove constant and it works.

**Comment by chriseth** [comment]
Ah, the reason for that is the missing source references in the assembly, but there is also a bug in the error reporting routine, because it should at least show the error message.
