### ISSUE TITLE
Link against shared boost in PPAs and add a CI task for testing such builds.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4660]
Came up in #4589.

Maybe we should even switch to using shared libraries by default and add explicit CI tasks for static linking instead. Static linking makes sense for binary releases, but IMHO it should not be the default.

**Comment by chriseth** [comment]
@ekpyron you said yesterday that this might be closed.

**Comment by ekpyron** [comment]
@chriseth Not closed - rather postponed for reconsideration in ``0.5.3`` (resp. put in the backlog - actually I'm moving it now).
The idea is that the neither the new PPA builds (nor any other release build I think) so far still *don't* link to shared boost, but still have the default static linking enabled. However, that's actually bad style for the PPAs, so I'd suggest to change that and then we should have a test run for it. But we said we wanted to have small incremental changes and don't want to change everything at once, so: postponed.

**Comment by ekpyron** [comment]
Changed the scope to also use shared boost in PPA builds.

**Comment by ekpyron** [comment]
I still believe this was the correct and should be changed - still closing it as not important enough :-).
