### ISSUE TITLE
Disallow using storage pointers before they are assigned.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4669]
For example, disallow the following:
`function f() returns (StructType storage b) { b.someMember = 6; return g(); }`

**Comment by chriseth** [comment]
Usage in this context is any reference to the storage pointer unless it is an lvalue, i.e. `g(b)` would also be invalid.

Note that once we have this, we are already half-way towards enforcing `mutable` / `immutable` and it might be rather easy to introduce this in 0.5.1 with a pragma.

**Comment by ekpyron** [comment]
This involves refining the control flow graph to consider the order of execution - currently it only determines whether a statement *is present* inside a block that will be executed, but not in which order a set of statements will be executed.

**Comment by chriseth** [comment]
We might want to extend this to just about any variable. In contrast to other languages, we do have clearly defined defaults, but it would perhaps not hurt to be more explicit, especially for types where the default value is easy to assign and does not make much sense like `address` and `uint`. This might be less of an issue for e.g. memory arrays, though.
