### ISSUE TITLE
Review, document and potentially fix issues listed in solidity-idiosyncrasies repository

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4672]
See: https://github.com/miguelmota/solidity-idiosyncrasies

**Comment by ChrisChinchilla** [comment]
@axic Following on from Gitter conversation, noted, and will look :)

**Comment by axic** [comment]
Some interesting points we may not have well documented:
- ~Using delete on an array leaves a gap; need to shift items manually and update the length property~.
- ~Can't compare two strings; one easy workaround is to compare the sha3 hashes of the strings. {it is keccak256 now}~
- ~bytes is the same byte[] but packed tightly (more expensive). {need to double check}~
- ~There's a limit to how many variables can be in a function; this includes parameter and return variables. The limit is 16 variables, otherwise you get the StackTooDeepException error "Internal compiler error: Stack too deep, try removing local variables.".~
- ~enum variable type get compiled down to an int8; (unless the enum has more than 8 options, in which case it walks up the int type scale)~.
- ~You have to use new keyword for creating variable length in-memory arrays. As opposed to storage arrays, it's not possible to resize memory arrays by assigning to the length member~.
- ~All primitive data types are initialized with default values; there is no "null" data type (like in JavaScript).~
- ~Have to use indexed keyword for events parameters to allow events them to be searchable; it allows you to search for the events using the indexed parameters as filters~.
- ~Only up to three parameters can receive the attribute indexed for event parameters~.
- ~Contracts can't activate themselves; they need a "poke", e.g. a contract can't automatically do something when it reaches a certain block number (like a cron job). There needs to be a call from the outside for the contract to do something; an external poke~.

**Comment by ChrisChinchilla** [comment]
@axic I'll break some of these out to seperate issues / PRs as I approach them.

**Comment by ChrisChinchilla** [comment]
When done, contact repo owner :)

**Comment by ChrisChinchilla** [comment]
Waiting on final PR merges
