### ISSUE TITLE
Unexpected behavior of abi.encodePacked

### ISSUE THREAD

**Issue by MoMannn** [ethereum/solidity#4683]
So what I am trying to do is create a keccak256 of an array of structs. So I used `abi.encodePacked()` to encode my array of structs and everything worked but later when I did it on an single struct and I got an error: `This type cannot be encoded.`

I am using: 

```
pragma solidity ^0.4.24;
pragma experimental ABIEncoderV2;
```

And I have this two structs:

    struct test1 {
        address addr1;
        address addr2;
    }

    struct test2 {
        address addr3;
        test1[] test;
    } 

Now if I do a: `abi.encodePacked()` upon test1 I get an `This type cannot be encoded.` error. 
If I do a: `abi.encodePacked()`upon an array of test1 then I don't get any errors. 
It also works If I do `abi.encodePacked()` upon test2.test. 

Now from my research `abi.encodePacked()` does not work upon structs that is why I get the error but why don't I get the error upon an array of structs? and what is the resulting hash from an array of structs?

**Comment by chriseth** [comment]
This should not be supported at all.
