### ISSUE TITLE
stardard json does not resolve local paths

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4688]
From https://github.com/ethereum/solidity/pull/3918#issuecomment-382069303 :
```
We tried using solc --standard-json and parsing the linkReferences, but ran into issues since that particular mode of solc does not resolve local (same directory) imports, e.g. import "./Test.sol";. Is that a known issue?
```

**Comment by christianparpart** [comment]
@chriseth: I am trying to get into this subject, but I'd appreciate a specific example that breaks. Currently I seem only get "linkerReferences" without any members in the standard JSON.

**Comment by ekpyron** [comment]
I'm not quite sure myself, the following works and does output ``linkReferences``:

```
{
  "language": "Solidity",
  "sources":
  {
    "B.sol":
    {
      "content": "import \"./A.sol\"; contract B { uint[10] m; function g() public returns(uint) { return A.f(m); } }"
    },
    "A.sol":
    {
      "urls": [ "./A.sol" ]
    }
  },
  "settings":
  {
    "outputSelection": {
      "*": {
        "*": [ "evm.bytecode.linkReferences" ]
      }
    }
  }
}
```

With contents of ``A.sol`` in current working directory:
```
library A {
	function f(uint[10] storage m) public returns(uint) {
		m[0]++;
		return m[0];
	}
}
```

And compiled with ``solc --allow-paths . --standard-json``.

Should ``import "./A.sol";`` be resolved, even if it is not specified in the json via an url? I'm not sure that's desirable...

**Comment by chriseth** [comment]
I think the idea was to align `solc` with and without standard-json. It should be easier to call the compiler with standard-json, so that it loads files on its own, if possible (you do not have to determine which files are exactly required, if the compiler also does it).

Isn't the allowed directories mechanism safe enough?

**Comment by ekpyron** [comment]
I wonder if and how changes here would affect the ``soljson.js``/emscripten interface and whether that needs to be considered here.

**Comment by chriseth** [comment]
StandardCompiler has a member `m_readFile`, which is a js callback in the js version (has to be synchronous, that's why it cannot actually read from the filesystem in nodejs) and a C++ lambda function in the `solc` version.

**Comment by chriseth** [comment]
Ok, actually the function that is passed to `CompilerStack` is the one that is used in the end, but the member of StandardCompiler is a copy of it.

**Comment by chriseth** [comment]
So from my source-code only analysis, the same mechanism is in place regardless of whether standard-json is used or not via `solc`, but for standard-json it does not seem to work.

**Comment by christianparpart** [comment]
> StandardCompiler has a member m_readFile, which is a js callback in the js version (has to be synchronous, that's why it cannot actually read from the filesystem in nodejs) and a C++ lambda function in the solc version.

Because everything is asynchronous in NodeJS, so maybe also the disk I/O functions. AFAIR.

**Comment by leonardoalt** [comment]
If files are used as urls in the standard json input format, their directories need to be allowed in the command line, via `--allow-paths <path>`.
