### ISSUE TITLE
Compare output of solc (not via standard json) in bytecodecomparison

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4698]

**Comment by chriseth** [comment]
The emscripten binary is covered. I'm not sure if `standard-json` is useful here, because that is rather an input format and it should never be platform-dependent, or at least it does not have to be tested on that many input files.

**Comment by leonardoalt** [comment]
I think by now we are testing `--standard-json` via the command line tests. Is that enough to close this?

**Comment by chriseth** [comment]
The question is if they are pushed here: https://github.com/ethereum/solidity-test-bytecode/

**Comment by axic** [comment]
@cameel since you worked on this last, do you have an feedback?

**Comment by cameel** [comment]
I actually haven't, I was just going to do any cleanup needed after @ekpyron did the bulk of the work moving it to CircleCI in #10039 but I can check.

**Comment by ekpyron** [comment]
Since I just happened to notice the mention of me ;-):
emscripten is still covered and apart from that I agree with https://github.com/ethereum/solidity/issues/4698#issuecomment-410781114 in that I'm not sure how standard json is supposed to be related to bytecode comparison.
That being said, I did only do the minimal amount of work to get it running again in #10039 - it would be nice to clean up the mechanism a bit. I.e. ``scripts/bytecodecompare/storebytecode.sh`` for the emscripten case is rather horrible - we could actually just run the ``solcjs`` wrapper script from the solc-js repo as ``solc`` to run it with the ``scripts/bytecodecompare/prepare_report.py`` script instead of using this horrible on-the-fly temporary javascript file produced by the script, etc...

**Comment by cameel** [comment]
So the situation looks like this:
- There are 4 targets for which we run the bytecode comparison and generate a report: Linux, Windows, MacOS, emscripten.
- The report includes all `*.sol` files from under `test/` (with some minor exclusions) and test cases from docs.
    - This does not include `*.yul` files so the assembly input is not being tested.
- The SMTChecker pragma is always stripped from the file before compilation (if present).
- It runs the compilation twice for each file, once with and once without the optimizer.
- All tests are executed via Standard JSON. Passing the JSON directly in case of emscripten and using `--standard-json` flag in other cases. I don't see it invoking the compiler via the normal CLI interface at all.
- The only outputs requested are `evm.bytecode.object` and `metadata` so it's only testing the old code generator.

**Comment by cameel** [comment]
@ekpyron Thanks, I actually forgot to ask you earlier what was still left to do with the bytecode comparison so your comment is very helpful. I'll put that in an issue.

**Comment by axic** [comment]
The issue was originally created as prompted by the Zeppelin audit, which was curious whether the the output generated via the standard JSON is compared or not, because the CLI goes through a different path. (Also see #9583).

If bytecode comparison is done via standard JSON (and in the emscripten target it does), then the question becomes: do we use non-standard-JSON output on the CLI targets (linux/macos/win) or not?

**Comment by ekpyron** [comment]
I vote for someone just doing #9583, that would render the question mute and we do have tons of reasons for #9583 already :-).

**Comment by axic** [comment]
> The only outputs requested are evm.bytecode.object and metadata so it's only testing the old code generator.

Once we merge #10147 (and potentially add `viaIR` into standard json too) this becomes a question again. At the very least we should document (even as a simple readme in `scripts/bytecodecompare`) what is happening right now.

**Comment by cameel** [comment]
@axic No, it's not using non-standard-JSON with any target.

Here's the part that executes the compiler in case anyone wants to check directly:
- Linux/Mac/Win: https://github.com/ethereum/solidity/blob/v0.7.4/scripts/bytecodecompare/prepare_report.py#L28-L31 if 
- Emscripten: https://github.com/ethereum/solidity/blob/v0.7.4/scripts/bytecodecompare/storebytecode.sh#L53-L110

**Comment by cameel** [comment]
I'm taking this. I need to add a CLI variant to be able to run the comparison on older binaries (they do not support `--standard-json`).
