### ISSUE TITLE
Setting array.length in a contract storing an msg.sender address creates an infinite loop

### ISSUE THREAD

**Issue by itsnotlupus** [ethereum/solidity#47]
Setting array.length in a contract storing an msg.sender address creates an infinite loop.

Minimal reproducible contract:
```
contract c {
    
    address a;
    
    function d() {
        a = msg.sender;
    }
    
    function test() returns (int) {
        int[] accessList;
        accessList.length = 1;
        return 1;
    }
}
```

Steps:
- create contract c
- call test, see that it returns 1.
- call d.
- call test, again see that it is stuck in an infinite loop.

Additional steps:
- edit `d()` to set `a` to any other value. recompile.
- verify that the infinite loop does not occur.

Version: 0.1.1-34172c3b/RelWithDebInfo-Emscripten/clang/int

**Comment by chriseth** [comment]
This is a common pitfall: https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#pitfalls
Hopefully, the compiler can generate a warning for this soon.
