### ISSUE TITLE
Crash when trying to declare an already declared variable with the same name

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4705]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description

The parser does not detect a previously declared variable when declaring a new one, while using an experimental `pragma`.

## Error in file

Tried to activate a non-inactive variable or multiple inactive variables with the same name.
`libsolidity/analysis/DeclarationContainer.cpp(93)`

## Displayed message
`Throw in function void dev::solidity::DeclarationContainer::activateVariable(const ASTString&)`

## Example code                                                              

```solidity
pragma solidity ^0.4.24;
pragma experimental "v0.5.0";
contract CrashContract {     
       function f() view public {
               int variableDefinedTwice;
               address variableDefinedTwice;
       }
}
```

**Comment by axic** [comment]
Can be reproduced in 0.4.24, but no longer happening in develop:
```
4705.sol:6:16: Error: Identifier already declared.
               address variableDefinedTwice;
               ^--------------------------^
4705.sol:5:16: The previous declaration is here:
               int variableDefinedTwice;
               ^----------------------^
```

The were some scoping cleanups, which probably fixed it.
