### ISSUE TITLE
Crash when accessing empty name variable slot

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4707]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description 
The parser does not detect the usage of a `_slot` syntax on an empty variable name. 

## Error in file
Attempt to resolve empty name
`libsolidity/analysis/DeclarationContainer.cpp(128)`

## Displayed message
`Throw in function std::vector<const dev::solidity::Declaration*> dev::solidity::DeclarationContainer::resolveName(const ASTString&, bool, bool) const`

## Example code
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
   function () internal {
       assembly {
           _slot
       }
   }
}
```

**Comment by axic** [comment]
Still reproducible:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/analysis/DeclarationContainer.cpp(127): Throw in function vector<const dev::solidity::Declaration *> dev::solidity::DeclarationContainer::resolveName(const dev::solidity::ASTString &, bool, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Attempt to resolve empty name.
[dev::tag_comment*] = Attempt to resolve empty name.
```
