### ISSUE TITLE
Crash when type not set for parameter return value

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4708]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
The parser fails to recognize the return variable is missing its type on variable declaration of the type of a nameless function.

## Error in file
Type not set for return parameter.
`libsolidity/analysis/ReferencesResolver.cpp(187)`

## Displayed message
`Throw in function virtual void dev::solidity::ReferencesResolver::endVisit(const dev::solidity::FunctionTypeName&)`

## Example code  
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
       function () returns (variableNameWithoutType) variableName;
}
```
	
## Error in file 2
Type not set for return parameter.
`libsolidity/ast/Types.cpp(2397)`

## Displayed message 2
`Throw in function dev::solidity::FunctionType::FunctionType(const dev::solidity::FunctionTypeName&)`

## Example code 2

```solidity
pragma solidity ^0.4.24;
contract CrashContract {
       function() internal returns (zeppelin)[] x;
}

```

**Comment by axic** [comment]
Confirmed in 0.4.24, but no longer happens on develop:
```
4708.sol:3:29: Error: Identifier not found or not unique.
       function () returns (variableNameWithoutType) variableName;
                            ^---------------------^
```
```
4708_2.sol:3:37: Error: Identifier not found or not unique.
       function() internal returns (zeppelin)[] x;
                                    ^------^
```
