### ISSUE TITLE
Crash when type not set for parameter function value

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4709]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
The parser fails to recognize that a variable is missing its type in the function’s parameters when defining a variable of an array of nameless functions.

## Error in file
Type not set for parameter.
`libsolidity/ast/Types.cpp(2387)`

## Displayed message
`Throw in function dev::solidity::FunctionType::FunctionType(const dev::solidity::FunctionTypeName&)`

## Example code
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
   function(parameterWithoutType) internal returns (uint)[] y;
}

```

**Comment by axic** [comment]
Reproducible in 0.4.24, but no longer happens on develop:
```
4709.sol:3:13: Error: Identifier not found or not unique.
   function(parameterWithoutType) internal returns (uint)[] y;
            ^------------------^
```
