### ISSUE TITLE
Crash when accessing a _slot of a function in assembly block

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4710]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
The visit method fails when accessing the `_slot` of a function inside an assembly block of the same function.

## Error in file
Empty message.
`libsolidity/codegen/ContractCompiler.cpp(534)`

## Displayed message
`Throw in function dev::solidity::ContractCompiler::visit(const dev::solidity::InlineAssembly&)::<lambda(const dev::solidity::assembly::Identifier&, dev::julia::IdentifierContext, dev::julia::AbstractAssembly&)>`

## Example code
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
       function f() pure public {
               assembly {
                       function g() -> x { x := f_slot }
               }
       }
}
```

**Comment by axic** [comment]
This is still failing in develop:
```
/Users/alex/Projects/solidity/libsolidity/codegen/ContractCompiler.cpp(538): Throw in function auto dev::solidity::ContractCompiler::visit(const dev::solidity::InlineAssembly &)::(anonymous class)::operator()(const assembly::Identifier &, julia::IdentifierContext, julia::AbstractAssembly &) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

**Comment by chriseth** [comment]
The fix is to disallow it (`x_slot` should only work if `x` is a storage variable).
