### ISSUE TITLE
Crash when calling a non callable type on a non primitive type double assignment

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4711]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
Compiler crashes when a non callable type (`int`, `uint`, `struct`, etc) is used outside a double assignment involving structs.

## Error in file
Empty message.
`libsolidity/analysis/TypeChecker.cpp(531)`

## Displayed message
`Throw in function void dev::solidity::TypeChecker::checkDoubleStorageAssignment(const dev::solidity::Assignment&)`

## Example code
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
       struct S { }
       S x;
       function f() public {
               (x, x) = 1(x, x);
       }
}
```

**Comment by axic** [comment]
Reproducible in 0.4.24 and still happens in develop:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/analysis/TypeChecker.cpp(510): Throw in function void dev::solidity::TypeChecker::checkDoubleStorageAssignment(const dev::solidity::Assignment &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```
