### ISSUE TITLE
Crash when converting fixed point type using ABIEncoderV2

### ISSUE THREAD

**Issue by mattaereal** [ethereum/solidity#4715]
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
Compiler crashes on the assembly code generation when using `pragma experimental ABIEncoderv2` to encode a fixed point type.

## Error in file
Not yet implemented - FixedPointType.
`libsolidity/codegen/ABIFunctions.cpp(291)`

## Displayed message
Unimplemented feature.
`Throw in function dev::solidity::ABIFunctions::conversionFunction(const dev::solidity::Type&, const dev::solidity::Type&)::<lambda()>`

## Example code

```solidity
pragma solidity ^0.4.24;
pragma experimental ABIEncoderV2;
contract C {
   function f1() public pure returns (bytes) {
       return abi.encode(0.1, 1);
   }
}
```

**Comment by axic** [comment]
Yes, this exists, there are a couple of other places with unimplemented-feature assertions for FixedPoint types and it would be nicer to catch them in the TypeChecker.

**Comment by leonardoalt** [comment]
The same happens without ABIEncoderV2.
