### ISSUE TITLE
'byte' instruction not recognized in inline assembly

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#472]
```
contract C {
    function f(){
        assembly{
            byte(1, 4)
        }
    }
}
```

```
Untitled:4:13: Error: Expected elementary inline assembly operation.
            byte(1, 4)
```

Same with:

```
contract C {
    function f(){
        assembly{
            4 1 byte
        }
    }
}
```

**Comment by axic** [comment]
I was about to report the same.   Workarounded with `and` for the moment - I was only needing the last byte.

**Comment by chriseth** [comment]
Thanks a lot. The reason is that it is a keyword in solidity, so we need a special parsing rule. I added the same for `return` but forgot about `byte`.
