### ISSUE TITLE
Overhaul boost test setup/initialization.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4730]
Came up in #4589.
We seem to use deprecated/obsolete boost features for the test initialization and we may be able to define a custom ``main`` both for shared and static builds.

**Comment by ekpyron** [comment]
A custom ``main`` in static boost seems to require a custom built boost: https://live.boost.org/doc/libs/1_68_0/libs/test/doc/html/boost_test/adv_scenarios/static_lib_customizations/entry_point.html
So it's probably not a good idea.

**Comment by leonardoalt** [comment]
@ekpyron does this change if we stick to new boost?

**Comment by ekpyron** [comment]
@leonardoalt I haven't really looked into it any further, so I'm not sure - someone has to look into the current best practices for boost test initialization both for shared and for static linking and in how far boost is backwards compatible here. Sticking to newer boost will make it easier in any case I guess. But so far our setup, although deprecated, still seems to work.

**Comment by axic** [comment]
@ekpyron is this still relevant?

**Comment by ekpyron** [comment]
I'm pretty sure this is still relevant.

**Comment by axic** [comment]
Ok, this was the issue but wasn't able to find it as it had no reference to `init_unit_test_suite`.

Copying this from #10574:
> It seems to be obsolete: https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/boost_test/adv_scenarios/obsolete_init_func.html
>
>And (global) fixtures is one suggested option: https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/boost_test/tests_organization/fixtures/global.html

**Comment by ekpyron** [comment]
Still relevant, but not worth being tracked in an issue - it's obvious part of general soltest refactoring.
