### ISSUE TITLE
Capped content in the documentation.

### ISSUE THREAD

**Issue by eternauta1337** [ethereum/solidity#4739]
Some UI elements in the documentation are very hard to read because the css styles cap the width of the content area to 800px.

Examples:
* [the list of low level Yul functions](https://solidity.readthedocs.io/en/v0.4.24/julia.html#low-level-functions) 
* [embedded json files](https://solidity.readthedocs.io/en/v0.4.24/using-the-compiler.html#input-description)
* [embedded code snippets](https://solidity.readthedocs.io/en/v0.4.24/using-the-compiler.html#input-description)

Consider removing the 'max-width: 800px;` restriction from the `.wy-nav-content` css class and save people a lot of H scrolling. Specially for the Yul section, which is very often visited for reference.

**Comment by chriseth** [comment]
The last two are still open. I think a solution is just to break long lines - it should also properly compile to pdf.

**Comment by aj07** [comment]
I think its better to divide abhove into 3 issues..

**Comment by ChrisChinchilla** [comment]
Thanks everyone I'll take a look soon and see what I can do :)
