### ISSUE TITLE
Adding `memory allocation` helper to inline assembly

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#474]
Memory can be allocated using the `new` keyword in Solidity, but in the inline assembly part is has to be done by hand.

The example code in the docs for doing this:

```
function getcode(address _addr) returns (bytes o_code) {
                assembly {
                        // retrieve the size of the code, this needs assembly
                        let size := extcodesize(_addr)
                        // allocate output byte array - this could also be done without assembly
                        // by using o_code = new bytes(size)
                        o_code := mload(0x40)
                        // new "memory end" including padding
                        mstore(0x40, add(o_code, and(add(add(size, 0x20), 0x1f), bnot(0x1f))))
                        // store length in memory
                        mstore(o_code, size)
                        // actually retrieve the code, this needs assembly
                        extcodecopy(_addr, add(o_code, 0x20), 0, size)
                }
}
```

I don't want to duplicate such code, so I rather resort to the following code structure (this is based on the sample code):

```
function getcode(address _addr) returns (bytes o_code) {
            uint size;
            assembly {
                size := extcodesize(_addr)
            }

            o_code = new bytes(size);

            assembly {
                extcodecopy(_addr, add(o_code, 0x20), 0, size)
            }
        }
}
```

I think it would make sense having some shortcut for this accessible from assembly. Such as:

```
o_code := $allocate(size)
```

or

```
o_code := __allocate(size)
```

The prefix is to make a distinction between an opcode and the builtin helper.

Maybe it would make sense having macros? :)

**Comment by chriseth** [comment]
I think that using inline assembly only for single instructions is perfectly fine.
If we come up with more examples that cannot be solved that way and also inline functions won't help, we can reconsider adding some kind of macros.

**Comment by axic** [comment]
@chriseth a few more useful macros:

`shl = mul(input, exp(2, bits))`
`shr = div(input, exp(2, bits))`
`memcpy` / `mcopy` to copy between two memory storage locations

**Comment by chriseth** [comment]
Related: declare a contract-local memory management routine

**Comment by axic** [comment]
We could also introduce a version which zeroes out memory: `$allocateclear(size)`
