### ISSUE TITLE
Incorrect return value for byte array constructed using inline assembly

### ISSUE THREAD

**Issue by abandeali1** [ethereum/solidity#4746]
## Description

When manually constructing + returning a byte array, the incorrect value is being returned. 

## Environment

- Compiler version: 0.4.24 (tested with and without ABIEncoderV2)
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Javascript VM
- Operating system: 

## Steps to Reproduce

```
    function abiEncode(uint256 a, uint256 b)
        public
        pure
        returns (bytes memory data)
    {
        assembly {
            data := mload(0x40)  //  point data to free memory slot
            mstore(data, 0x40)  //  write length (64 bytes)
            mstore(add(data, 0x20), a)  //  write `a`
            mstore(add(data, 0x40), b)  //  write `b`
        }
        return data;
    }
```

If we call `abiEncode(1, 2)`, the expected output is `0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002`.

Instead, the output of this function is _always_ `0x0000000000000000000000000000000000000000000000000000000000000020` when called externally.

However, it appears that this function is returning the correct value when called internally.

**Comment by axic** [comment]
You need to increment the free memory pointer, otherwise the compiler can reuse the memory.

Better yet I suggest to allocate memory via Solidity and not inline assembly, such as:
```
data = new bytes(64);
```

**Comment by axic** [comment]
Please comment if that doesn't solve the problem.

**Comment by abandeali1** [comment]
Sorry, I forgot to add that adding `mstore(0x40, add(data, 0x60))` did fix the issue.

I'm wondering where the memory is actually being reused in this example though? Maybe it just needs to be documented better, but it didn't seem like anything should be overwritten here.

**Comment by axic** [comment]
The ABI encoding process (added in by the compiler after your function finishes) will definitely use some memory.

**Comment by wjmelements** [comment]
I want to add that if your data is a struct and you are looking to return it in memory, the syntax seems to be:

```
    function extLoadStruct(address _extContract) public view returns (SomeStruct memory theStruct) {
        assembly {
            extcodecopy(_extContract, theStruct, 50, 736)
        }
    } 
```
