### ISSUE TITLE
Split "movable" into "side-effect-free" and "context-independent"

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4756]
The simplification rule `div(X, 0) -> 0` removes `X` and thus in the yul optimizer, `X` is required to be movable. Movable currently means "side-effect-free" and "context-independent". `calldataload` for example is movable, but `keccak256` is not.

If simplification rules only delete subexpressions (as opposed to moving them or unifying them like in `and(X, X) -> X`), it is sufficient to require context-independentness, and thus the term should probably be more refined and used like that.

**Comment by axic** [comment]
I had some work done on this previously, will try to push it.

**Comment by chriseth** [comment]
If we move to SSA and "three-address-code", this might not be required and could be simplified: As far as the rules are concerned, we can just apply them without caring about "movability". Movability only comes into play if we want to rearrange or delete individual instructions. We can delete an instruction if it is side-effect free and we can rearrange them if they are context-independent. Moreover, if we only have single instructions, we can perform all movement through swapping. Two instructions can be swapped if and only if they do not conflict, i.e. do not both modify or modify and read the same memory or storage slot or blockchain "data" (e.g. two calls).

**Comment by chriseth** [comment]
The current SolYul code generator creates code like `pop(sload(x))`. This can obviously be removed, but since `sload` is not movable, it is not done.

**Comment by chriseth** [comment]
Together with @ekpyron we came up with the following categories:

 - can be removed (`R`) without change in semantics
 - can be duplicated (`D`) without change in semantics
 - can be swappend with instruction `i` (`X_i`) without change in semantics

We grouped the opcodes into the following categories (might not be exhaustive). The R and D properties are listed here, the X properties below.
 - add: R D
 - sload: R D
 - sstore: D
 - mload: R D
 - mstore: D
 - call: 
 - balance: R D
 - stop: D
 - return: D
 - revert with reason: D
 - revert without reason: D

Now the swap properties:

 - add:
    swappable with everyting
 - sload:
    NOT swappable with sstore, call.
    Swappable with everything else
 - sstore:
    NOT swappable with sstore, sload, call, stop, return.
    Swappable with everything else
 - mstore:
    NOT swappable with mload, mstore, call, return, revert with reason
    Swappable with: add, stop, revert without reason, balance, sload, sstore
 - balance:
    NOT swappable with call
    swappable with everything else
 - stop:
    NOT swappable with sstore, call, revert with reason, revert without reason, return
    swappable with: add, stop, sload, balance, mstore, mload
 - return:
    NOT swappable with sstore, call, revert with reason, revert without reason, return, stop, mstore
    swappable with: add, sload, balance, mload
 - revert with reason:
    NOT swappable with mstore, call, revert without reason, stop, return, revert with reason
    swappable with mload, sload, sstore, add, balance
 - revert without reason:
    NOT swappable with revert with reason, stop, return
    swappable with everything else

**Comment by chriseth** [comment]
Additional interesting categories: staticcall, selfdestruct

Also, the family of call opcodes might be further split up into ones that do not read from memory, ones that do not write to memory and ones that do neither.
