### ISSUE TITLE
Document changes between legacy and new JSON AST + add more extensive tests.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4758]
Came up in #4691.

The JSON ASTs seem to be scarcely documented in general. Also the test coverage at the moment is far from extensive.

**Comment by ekpyron** [comment]
To discuss: who needs the legacy AST? Is it still used? Do we want to or can we stage it for removal in 0.7.0?

**Comment by axic** [comment]
> To discuss: who needs the legacy AST? Is it still used? Do we want to or can we stage it for removal in 0.7.0?

Done in 0.8.0! (#9512).

**Comment by axic** [comment]
Do we need to keep this issue open? Should it be renamed to "improve test coverage of JSON AST"?

**Comment by chriseth** [comment]
Import / export tests it well I would say.
