### ISSUE TITLE
Replace -fvisibility-hidden with CMake options

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4759]
See https://stackoverflow.com/questions/17080869/what-is-the-cmake-equivalent-to-gcc-fvisibility-hidden-when-controlling-the-e/31157258#31157258

Came up in https://github.com/ethereum/solidity/pull/4528/files#r208542520

**Comment by ekpyron** [comment]
Not sure whether ``<LANG>_VISIBILITY_PRESET`` will work here. ``<LANG>`` would be ``CXX`` both for emscripten and gcc/clang/MSVC builds, wouldn't it?

**Comment by axic** [comment]
I think it shouldn't be an emscripten specific option. I kind of have the feeling it shouldn't be turned on at all, since we do not have the proper attributes set on exported functions.

**Comment by ekpyron** [comment]
That may be - we should investigate this in more detail - I added this to ``0.5.1``, though, since the current workarounds seem to work and therefore I would say it's not "urgent".

**Comment by axic** [comment]
@chfast can you shed a light if `<LANG>_VISIBILITY_PRESET` works well cmake?

**Comment by chfast** [comment]
Never heard of it, but looks promising. Build with make VERBOSE=1 and see the compiler flags.
