### ISSUE TITLE
Making Multiple Inheritance more idiot proof

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#476]
currently this works:

```
contract O {}
contract A {}
contract B {}
contract K1 is O, A, B {}
contract K2 is O, A {}
contract J is K1, K2 {}
```

but this does not

```
contract O {}
contract A {}
contract B {}
contract K1 is O, A, B {}
contract K2 is A, O {}
contract J is K1, K2 {}
```

Is there any way to make this slightly more idiot proof so that simply flips like this do not fail somebody in their attempts to compile?

**Comment by chriseth** [comment]
Please read up on python's multiple inheritance model and C3 linearization. We could detect whether the order actually is important or not, but that does not have high priority.

**Comment by VoR0220** [comment]
I know it doesn't have high priority, but that's why I'm leaving it here :)

**Comment by aseemydv** [comment]
I too faced that issue , according to the new implementation of Python's MRO, preference to a class while inheriting in a Diamond problem is given in the sequence they are written. 
But I found this not working in case of Solidity, based on the fact that it is supposed to follow the same ideology. So,

contract K2 is O, A {}               <--- This works
contract K2 is A, B {}               <--- This doesn't
