### ISSUE TITLE
Add `address.staticcall(...)`

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4768]

**Comment by axic** [comment]
Oh wow, we didn't had this?

How should this work with `evmVersion`? Do we have that available during the analysis stage?

**Comment by chriseth** [comment]
I think we said that people should use assembly, but I think that it's fine since we changed it to single-bytes-param.

Yes, we have it. My proposal would be to always have the member but issue an error if it is used in the wrong evm version.

**Comment by axic** [comment]
It is fine always having a member, just the error should be issued in the type system and not at codegen.

**Comment by ekpyron** [comment]
~~I unassigned this and moved it back to "Ready to be worked on", since I was held up by other issues and haven't started it yet. If someone wants to take it, feel free, otherwise I'll get back to it later.~~
