### ISSUE TITLE
Problem with running the latest solc on OS X Yosemite: Symbol not found: __ZN4Json5ValueaSERKS0_

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/solidity#477]
```
46-20-235-13:solc admin$ brew install cpp-ethereum
Warning: ethereum/ethereum/cpp-ethereum-1.2.3 already installed
46-20-235-13:solc admin$ solc --version
solc, the solidity compiler commandline interface
Version: 0.3.1-c492d9be/RelWithDebInfo-Darwin/appleclang/JIT linked to libethereum-1.2.3-bb12c30a/RelWithDebInfo-Darwin/appleclang/JIT
46-20-235-13:solc admin$ solc a.sol 
dyld: lazy symbol binding failed: Symbol not found: __ZN4Json5ValueaSERKS0_
  Referenced from: /usr/local/Cellar/cpp-ethereum/1.2.3/lib/libsolidity.dylib
  Expected in: /usr/local/lib/libjsoncpp.dylib

dyld: Symbol not found: __ZN4Json5ValueaSERKS0_
  Referenced from: /usr/local/Cellar/cpp-ethereum/1.2.3/lib/libsolidity.dylib
  Expected in: /usr/local/lib/libjsoncpp.dylib

Trace/BPT trap: 5
```

**Comment by Nashatyrev** [comment]
```
brew uninstall cpp-ethereum
brew install cpp-ethereum
```

gives me the same result

Build jsoncpp from latest master branch - result is the same

Just checked on a clean Yosemite - the same error

**Comment by Nashatyrev** [comment]
On `El Captain` `solc` works perfectly fine after installing with Homebrew. 
In both cases the same `jsoncpp 1.6.5` is used and on both systems there is no such symbol as `__ZN4Json5ValueaSERKS0_` exported by this lib.

**Comment by chriseth** [comment]
@bobsummerwill do you have an idea here?

**Comment by Nashatyrev** [comment]
Took the `libjsoncpp.dylib` from this package https://build.ethdev.com/cpp-binaries-data/release-1.2.3/Ethereum.dmg and, it contains missing symbol:

```
46-20-235-13:solc3 admin$ nm -gU libjsoncpp.dylib | grep Valuea
000000000000e844 T __ZN4Json5ValueaSERKS0_
```

After replacing the lib everything worked fine.

**Comment by VoR0220** [comment]
sounds like a problem with the updated brew.

**Comment by bobsummerwill** [comment]
From Gitter ...

That is really weird, @Nashatyrev! I wonder if there is some pre-processor magic going on? Some one of those DYLIBs has some extra symbols. I know we hit something before, though I think it was with cryptopp, where there was some issue with the minimum target architecture, like building for SSE2 or not, which resulted in different binaries where this kind of thing happened on one OS X version and not others.

**Comment by bruceseymour** [comment]
Where does the libjsoncpp.dylib replacement file go?  I was able to download the dmg and find the libjsoncpp.dylib using 'Show Package Contents' from Finder.  

I'm receiving a Segmentation fault: 11 when using ethminer -G and/or ethminer -C and hopefully this will fix the issue if I can replace the file.

**Comment by chriseth** [comment]
@bobsummerwill is this fixed?

**Comment by bobsummerwill** [comment]
I believe so, yes.
