### ISSUE TITLE
(Inline assembly) assignment using =: fails after tags

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#478]
```
contract Test {
    function f() {
        uint x;
        assembly{
            tag:
               =: x 
        }
    }
}
```

**Comment by chriseth** [comment]
It which way does it fail? This is not valid inline assembly because `tag:` only defines the tag but does not "access" it. What you probably mean is

```
contract Test {
    function f() {
        uint x;
        assembly{
            tag:
               tag =: x 
        }
    }
}
```

**Comment by androlo** [comment]
It says something about expecting an elementary operation. Can't copy the text from browser solidity errors sometimes.

I'm not trying to access the tag, just the item that is on the top of the stack (like anywhere else). Just happens to be after a `tag:`. If I put a `dup1` between the tag and the `=: x` then it will work like normal.

**Comment by chriseth** [comment]
Ok, now I understand you issue.
The problem is that your example is parsed as `tag:=:x`, i.e. as `tag:= : x`, so it is seen as an assignment to a variable called `tag`.
I'm not sure how to handle that right now, but you can work around it by something like `tag: dup1 pop := x`

**Comment by androlo** [comment]
Thanks. Don't really need, just reporting things that looks suspicious.
