### ISSUE TITLE
Assign literal data to `bytes`

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#479]
It would be nice to have the ability assigning arbitrary long data to `bytes` variables, such as:

`bytes memory tmp = 0x1650a750994065226a299be192530fb5575dafe752427f91adb9dadbca968e7edc56db9d3da7550fc2903d2b6a7e0a6452db83855b8a54ff523bdcd4b987640a9939b3f691fae1eac3c0674b1bdb8d4dcf8c2ad003a5ee68bfff34c12ac70081cd817fabc0820d730c7e8f9e4960a7724c8882e65196f6477c85602da607e496f1f5e59f1a346d46ec72ba44cf5b1a562bf4f9c408c2d0c12fb68be0872048700485385414ff76485a0c29d4ed8ccc9594261dc4d54f71ace0878956e918405bd2f41cfd47404c3b63bf4d734d71d72f9df4382790b506f10fb73450b5ad4302b3e232f7deef1d3541c505e3e87b9e24b329a8b95f0ff7be5d4685bafafb84db`

would assign 256 bytes of data to `tmp`.

The question is: should it allocate memory or just check if there's enough space in the allocated?

**Comment by chriseth** [comment]
Memory allocation is not a problem, we already have literal strings and they can be as long as needed.
The problem is that you have a number in your example, not a string. I guess "\x15\x50..." should work, but there might be a bug in browser-solidity that parses it incorrectly.

**Comment by axic** [comment]
There are actually two bugs with escape codes, #480 and https://github.com/chriseth/browser-solidity/issues/132.

When these are fixed, that is an alternative solution, however I think a shorter form would be more useful.  Most apps (including browser-solidity) would allow the user to pass such data in this form.

I do not mind what is the notation, the above I chose because that is:
- how the mentioned tools require it
- and to not collide with ""

Open to suggestions regarding notation.

**Comment by axic** [comment]
Another proposed way is using the backtick:

```
bytes code = `606060405260188060106000396000f360606040523615600d57600d565b60165b6002565b565b00`;
```

**Comment by chriseth** [comment]
What about "abusing" ecmascripts new template literals:

```
bytes code = hex`6060...`?
```

**Comment by axic** [comment]
Having read about that ECMAScript feature, it certainly seems to be an abuse.

Would this work?

```
bytes code = r"60606040";
```

or 

```
bytes code = hex"60606040";
```

If literal ECMAScript style template strings are implemented, could the above be used in a way as below?

```
bytes block1 = hex"60606040";
bytes code = hex`60ff${block1}00`;
```

Additionally it might make sense allowing whitespace (space and maybe tab & new line?), which is removed during parsing.

**Comment by chriseth** [comment]
I think `hex"..."` is a good way to do it. Furthermore, we can use the convention used by other languages to concatenate two literal strings if there is only whitespace between them. The encoding prefix only has to be present for the first such string.

Concerning the template strings: I think it is rather hard to do that at runtime which we would also have to support.

**Comment by stevenroose** [comment]
`hex"..."` would be fine, even though I don't see why the already-existing `0x` notation cannot be extended. Currently `0x000000ff` works for `uint32`s. If they would be allowed to be indefinitely long and also assignable to the `bytes` type, a new notation is not required.

**Comment by chriseth** [comment]
`0x00000ff` is a number, and numbers ignore leading zeros, that is the main reason.
