### ISSUE TITLE
Future: mapping iteration

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [ethereum/solidity#48]
is it possible to iterate over mapping as in Java?also it would be great if I could know size of the mapping.

**Comment by LianaHus** [comment]
Hi Vitaliy,
there is no way to iterate over the mapping.
This discussion in our forum could be helpful for you https://forum.ethereum.org/discussion/1995/iterating-mapping-types .

**Comment by vitaliy-kuzmich** [comment]
ok maybe later would be, thank you.
