### ISSUE TITLE
browser-soliditiy: Escape codes in `bytes` and `string` fail for >0x7f

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#480]
`string memory x = "\x12\x7f";` -> `PUSH32 0x127F000000000000000000000000000000000000000000000000000000000000`

vs

`string memory x = "\x12\x80";` -> `PUSH32 0x12C2800000000000000000000000000000000000000000000000000000000000`

**Comment by chriseth** [comment]
Unable to reproduce in `solc`. Does that happen only for browser-solidity or also for the npm version? My guess would be that when fetching the source, the string `"\x12\x80"` is actually parsed, converted to a binary string (without hex escapes) and then interpreted as utf-8 which fails.

**Comment by axic** [comment]
Actually that might be the reason. I've been using it in the Javascript bindings for solc and it is very likely Javascript does that to escape codes.

**Comment by chriseth** [comment]
Probably related to https://github.com/chriseth/browser-solidity/issues/114

@axic did you use browser-solidity in the browser or plain npm?

**Comment by axic** [comment]
Via npm, it is likely that Javascript itself does it.

I cannot test it in browser-solidity because of https://github.com/chriseth/browser-solidity/issues/132

**Comment by axic** [comment]
This is apparently a bug in Solidity and/or Emscripten as explained in https://github.com/chriseth/browser-solidity/issues/132.

I think this can be closed here. @chriseth?

**Comment by axic** [comment]
#603 explains this issue properly. Closing this in favour of it.

**Comment by axic** [comment]
This `string memory x = "\x12\x80";` -> `PUSH32 0x12C2800000000000000000000000000000000000000000000000000000000000` was caused by Javascript's JSON converter. Perhaps that is a separate bug.
