### ISSUE TITLE
public constant function returns incorrect value every time.

### ISSUE THREAD

**Issue by shadowcodex** [ethereum/solidity#4800]
## Description

Return data is returned incorrectly. The data returned should be the same as the data stored in contract.

## Environment

- Compiler version: All versions
- Framework/IDE (e.g. Truffle or Remix): both & direct web3
- EVM execution environment / backend / blockchain client: blockchain
- Operating system: macOS, Windows, Linux

## Steps to Reproduce

The following code returns `0` every time. Even though it's value has been increased.

```
  function amountFilled(user, hash) public constant returns(uint) {
    sha256(user) // sha breaks it. If you remove a sha function it works
    return dataObject[user][hash];
  }
```

However `dataObject` is also public. And if you inspect the actual data object on the chain it will be a `non-zero` value.

**Comment by chriseth** [comment]
Could you please provide the full minimal source code to trigger this bug? Does it actually return `0` or does the function call fail? Does enabling / disabling the optimizer change it?

Currently, I can think of two causes for this:
 - serious optimizer bug
 - incorrectly initialized test chain (sha256 is a precompiled contract)

**Comment by chriseth** [comment]
Closed due to inactivity. Please reopen if the issue persists of if you have more questions.
