### ISSUE TITLE
Re-enable the ``blockhash`` test for constantinople.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4805]
Came up in #4799.

For constantinople the blockhash opcode seems to always return zero.
This is probably due to us setting the constantinople fork block to zero and resetting the chain to block zero before each test, which seems to break the blockchain contract in aleth (introduced in EIP96). Either our test setup has to be adjusted or aleth should support blockhash in the configuration used for our tests.

Corresponding issue in aleth: https://github.com/ethereum/aleth/issues/5184

**Comment by ekpyron** [comment]
Pre-deploying the blockhash contract by adding it to the pre-defined accounts during genesis in ``RPCSession.cpp`` seems to help, but causes issues with other tests (https://circleci.com/gh/ethereum/solidity/30991).

**Comment by chriseth** [comment]
@ekpyron is this still the case?

**Comment by ekpyron** [comment]
It's not the case anymore, no, but the ``blockhash`` is still disabled for "< constantinople". Since we require newer aleth versions now anyways, we should reenable it. I'll rename this and create a suitable PR that closes this then.

**Comment by chriseth** [comment]
I believe this has been done in https://github.com/ethereum/solidity/pull/6145

**Comment by ekpyron** [comment]
Confirmed: this was done in #6145.
