### ISSUE TITLE
"Static" option in compiler to fold in libraries

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#481]
With library support code can be organised better than solely with inheritance.

Would it possible with an option to treat libraries as parent contracts and therefore include their methods in the contract body?  Similarly how static linking works.

In some cases the library is so small that it could make more sense when statically linked. Maybe a better option is to have an inline modifier for a library?

In the long term everything should be library based and that will open another problem to solve - managing dependency lists, versions of deployed contracts to attach to. All this in order to avoid multiple deployments of the same.

**Comment by chriseth** [comment]
The original plan for libraries also included inheritance. But it comes with several drawbacks, one of them being that virtual functions do not work anymore. We do plan to add an `inline` keyword for library functions, though, so that they are usable on memory types and perform better on value types.

**Comment by axic** [comment]
All of that would be nice, inline library could solve the issue mentioned in #434.

This issue has a slightly different angle though, compiling a "static", single output even if non-inline libraries are used.

As a quick way I think that could be implemented in the compiler that it handles libraries as parent contracts (when this option is turned on) ?

**Comment by chriseth** [comment]
Can you describe a bit more in detail how you think contracts that inherit from libraries should behave? In which way will it be different than inheriting from contracts?

**Comment by axic** [comment]
It was only a suggestion how statically compiling code which relies on libraries could be done without substantial changes: assume the library is a parent contract.  I might be totally wrong, that is my assumption from the outside.

I have no intention to introduce a new type of library/contract.

**Comment by Arachnid** [comment]
+1 on this - for standard library stuff like implementing string operations, or extra ADTs, the overhead of calling another contract is undesirable, and in some cases imposes extra constraints, such as the inability to modify values in place, or to return variable length types. Being able to use the existing "using ... for" syntax with inline calls would be really useful.

**Comment by chriseth** [comment]
I would say that is implemented now, right?

**Comment by frangio** [comment]
@chriseth Could you clarify what feature implements this?
