### ISSUE TITLE
gas price in the transaction data of the semantics tests seems to be ignored

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4814]
Came up in #4799.

In the semantics tests ``eth_gasPrice`` seems to return a fixed value, that is independent of ``m_gasPrice`` (``tx.gasprice`` will be equal to that fixed value not to ``m_gasPrice``).

It seems the gas price in the transaction data is ignored.

This may be a limitation of aleth in test mode.

**Comment by ekpyron** [comment]
Depending on the fix here, it may make sense to adjust the ``gasprice`` semantics test and to check against multiple values of ``m_gasPrice``.

**Comment by chriseth** [comment]
CC @chfast @gumb0 - this might be an issue in aleth.

**Comment by gumb0** [comment]
If it's about `eth_gasPrice` RPC - I think it returns the value used by client by default (if not given explicitly in `eth_sendTransaction` input)
What do you expect it to return?

**Comment by ekpyron** [comment]
We *do* set the ``gasPrice`` field in the transaction data for ``eth_sendTransaction``, but that doesn't seem to have any effect - both ``tx.gasprice`` in solidity code (i.e. in the end the EVM instruction), and ``eth_gasPrice`` will still return a fixed value (probably the default) and not the value we set during ``eth_sendTransaction``.

Haven't spent too much time looking into it any further, though.

**Comment by ekpyron** [comment]
No longer relevant
