### ISSUE TITLE
Use of uninitialized storage return variables is not properly detected

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4828]
```
contract caller {
  uint[] y;
  function test() internal returns (uint[] storage x) {
    f(x);
    x = y;
  }
  function f(uint[] storage a) internal {
    // do bad things with `a`
  }
}
```

**Comment by chriseth** [comment]
Not sure - we might already have an issue about this, still wanted to bring it up.

**Comment by ekpyron** [comment]
That's a duplicate of #4669, which we decided to move to 0.5.1 before.

**Comment by ekpyron** [comment]
I'm still not closing this as duplicate yet, since I guess the idea behind this issue was to discuss it for 0.5.0 again - so I'll leave #4669 in 0.5.1, we can discuss this issue here again for 0.5.0 and then close one as duplicate of the other.

**Comment by chriseth** [comment]
Sorry, no, I did not mean to reopen this for 0.5.0.
