### ISSUE TITLE
Add optional precompilation pass to optimize order of declarations

### ISSUE THREAD

**Issue by wbt** [ethereum/solidity#4830]
## Summary
In the example contract below, reversing the order of declarations of `assetCount` and `assets` costs an extra 1136 gas to deploy (159329 vs 160401).   The expected behavior is that the order of declarations should not matter, or to the extent that it does, the Solidity compiler will automatically choose the order resulting in the lowest gas cost to deploy.  

## Example contract
```
pragma solidity ^0.4.24;
contract Storer {

    struct storedAsset {
        string          asset;
        string          description;
        string          place;
        uint            whenStored;
        bool            secured;
    }

    uint32 public assetCount;
    mapping(uint32 => storedAsset) assets;
    event UpdatedAssetCount(uint32 indexed oldAssetCount, uint32 indexed newAssetCount);

    function newAssets(uint32 newCount) public {
        emit UpdatedAssetCount(assetCount, (assetCount + newCount));
        assetCount += newCount;
    }
   //other functions, events, security, etc. removed to more clearly demonstrate issue
}
```

## Environment
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)
EVM: Ganache v 1.1.0-beta.0
OS: Windows 10 Pro

## Steps to Reproduce
Create a new Truffle project and drop the above into ` contracts/Storer.sol`.    
Copy the below into a numbered deployment file (e.g. `2_deploy.js`).    
Run `truffle migrate --reset` and inspect the output.  Make changes, re-run, and re-inspect.

```
    //I have omitted code that exercises the function `newAssets(uint)`.  
    var Storer = artifacts.require("./Storer.sol");

    module.exports = function(deployer) {
        var storerInstance;
        Storer.new()
        .then(function (data) {
            storerInstance = data;
            return storerInstance.constructor.web3.eth.
            getTransactionReceipt(storerInstance.transactionHash);
        }).then(function (data) {
            console.log("Gas used in contract creation: "+data.gasUsed);
        }).catch(function(err) {
            console.log(err.message);
        });
    };

```

## Additional observations
Note that if the event is removed from the contract, the difference between the two declaration orders is 536 gas (134311 vs 134847).  It is further unexpected that the presence of the event changes the size of the deployment gas cost *difference* between the ordering of two other state variable declarations (which is not expected to exist at all).

The specific naming of struct fields also makes a difference.  For example, changing the name of the boolean field from "secured" to "latched" (both seven characters long) changes the difference in gas cost for that swapped declaration order to 1008 (159329 vs 160337).

The numbers work out differently when using `uint` instead of `uint32`, but the gist of the issue still holds.

**Comment by chriseth** [comment]
The order of state variables determines their slot in storage. For top-level storage variables, these slot numbers are constants and of course such small constants are used all over the place. Because of that, the optimizer can sometimes re-use the same constant of the slot number and other uses while in other cases it cannot. If you swap state variables further down it will probably have a smaller influence than swapping the first two state variables.

I compiled with activated optimizer and compared the resulting assembly. If `assetCount` is first, the code is a little simpler, but there is not really a big difference.

Here is the version with `assets` first:
```
> solc --gas --optimize /tmp/x.sol 
Warning: This is a pre-release compiler version, please do not use it in production.

======= /tmp/x.sol:Storer =======
Gas estimation:
construction:
   117 + 65000 = 65117
external:
   assetCount():	421
   newAssets(uint32):	22195
```

And here with `assetCount` first:
```
> solc --gas --optimize /tmp/x.sol 
Warning: This is a pre-release compiler version, please do not use it in production.

======= /tmp/x.sol:Storer =======
Gas estimation:
construction:
   117 + 64400 = 64517
external:
   assetCount():	421
   newAssets(uint32):	22189
```

The difference in code deploy cost is 600 (note that this gas estimation does not include the transaction costs, which still has to be added and where you pay differently for zero-bytes and non-zero bytes). Since you pay 200 gas per byte in the code, it looks like the version with `assetCount` in the first slot is 3 bytes shorter.

If you remove the event, then there is less code where the difference of the slot being zero or one makes a difference and thus the gas savings are smaller.

The difference concerning `secured` and `latched` can probably be explained as follows: The deployed code always contains a hash of its metadata to allow trustless source verification. Depending on the source code, this hash may have a different number of zero-bytes, even if the "active" code is unchanged. The difference of a zero-byte and a non-zero-byte in transaction cost is 64 gas, which is exactly the difference in cost you are seeing.

**Comment by wbt** [comment]
So an optimal compiler would choose the state variable being referenced most often, and assign that the constant with the fewest nonzero bytes (namely, `0`)?  

In an optimal compiler, would that pattern then continue, with the state variable being referenced n-th most often being assigned the constant with the n-th fewest nonzero bytes?

**Comment by chriseth** [comment]
The compiler cannot change the slot assignments of the variables, because it is part of the storage interface of a contract.

**Comment by wbt** [comment]
As the compiler also generates the application binary interface, it seems like it could alter the order of the variables, but now that I understand better I agree this is likely better done as an optional precompiler optimization step.

**Comment by chriseth** [comment]
So can this be closed?

**Comment by wbt** [comment]
In discussing this Issue with colleagues, they've mentioned that having to optimize storage for these sort of assembly-level considerations (switching the order of declaration of variables, including for more efficient packing) does not seem to be consistent with the image of Solidity as a relatively high-level language.  Given that in smart contracts, these optimizations or lack thereof have measurable and maybe nontrivial costs, there is value in doing them.  

I would like to see a precompilation pass added to the Solidity compiler, on by default but possible to disable with an option when running compilation, which reorders elements to optimize gas usage.  I think this could make Ethereum overall more efficient.  However, this is a relatively low priority issue as it relates to optimization and expands on the compiler's optimization functionality.

**Comment by chriseth** [comment]
I'm sorry, but Solidity is in no way high level. Also, as I said, the ordering of variables in storage is an interface requirement and cannot just be changed by a precompilation pass.

**Comment by wbt** [comment]
>I'm sorry, but Solidity is in no way high level. 

The [official docs](https://solidity.readthedocs.io/) open as follows, emphasis added: _"**Solidity is a** contract-oriented, **high-level language** for implementing smart contracts."_   

Probably as a result, this is how Solidity gets described in a lot of other contexts, and developers perceive it in this way.   

>The ordering of variables in storage is an interface requirement and cannot just be changed by a precompilation pass.  

Where does that requirement come from?  In what use case, other than optimizing gas usage through reordering of elements, would someone programming in Solidity need to have that ordering fixed in compiled code? 

These are Assembly-level efficiency issues that [my colleagues and] I believe should be properly addressed by a compiler.  Further, assembly-level efficiency considerations present a greater direct cost to users in Ethereum than in many general-purpose computing environments, where failure to optimize efficiency may be less costly.  In this case, compiler efficiency is not just a direct cost to user of the code, but also something that impacts the entire Ethereum community because if we could deliver the same functional value at lower gas costs, we can reduce network congestion and thereby reduce costs associated for transacting on or storing the blockchain even in other applications.

**Comment by chriseth** [comment]
Sure, Solidity is a high-level language in the same way as C is a high-level language, but they are both relatively low-level. In C, ordering of struct elements influences alignment and thus efficiency which is more or less the same thing.

The ordering is an interface requirement between contracts and libraries.

I am aware of the influence of gas costs. Still, security and simplicity has a higher value than gas costs.

Furthermore, just because reordering the variables is something you can do in the source code that affects the gas costs it does not mean that this is the best way to save gas when working on the compiler. Please consider using the optimizer if you care about gas costs.

Oh and finally, if 500 gas is much for you, perhaps think about storing less data on chain to begin with.

**Comment by wbt** [comment]
Our main point was that requiring developers to get into Assembly details for code performance, even when using the optimizer in their compilation workflow (`solc --optimize`) does not seem to be consistent with the image of Solidity as a relatively high-level language.  I understand now that in your view, we were wrong to have that image in mind, but it is commonly held and I believe we had valid grounds for it.

The existing optimizer works on the compiled assembly, after compilation.  An additional optimizer could act prior to compilation, doing things like reordering variable declaration to deliver the same functionality but more efficiently.  **This Issue suggests the creation of a new precompilation optimizer for ordering variable (and maybe function) declarations to support more efficient packing and referencing.**

If reordering variable declarations introduces security holes, that would be a bigger issue that would need to be tracked and addressed separately, because developers could easily wind up with insecure orderings by chance.   

I would expect this issue to be low priority relative especially to security bugs and other issues with the "bug" tag or which have a larger potential payoff to improvement.  However, I still believe the proposal has value and wouldn't advocate for it to be closed at this time.  If fixing the ordering of declaration to match source  must be a strict requirement (and not e.g. fixing the ordering to be deterministically predictable from source) this issue can be closed; I do not presently fully understand the source of that requirement or if there might be a better way to work around it. 

Your work in the Ethereum codebase is appreciated; the dismissive comments here, less so.   
I think this discussion could benefit from additional viewpoints from others as well.

**Comment by chriseth** [comment]
I'm sorry if my previous comments were a little rude. The thing is that reordering variables in storage as part of the compilation process is a delicate thing. There have been other proposals to change the storage layout completely especially with regards to upgradability which would also be relevant here (but I don't think there is an issue about that in this repository). Both problems might be solvable by analyzing the code and changing the source code itself prior to compilation, as you suggest. We can keep this open as a basis for discussion.

**Comment by wbt** [comment]
I think it's reasonable to keep this open as discussed above.

**Comment by NunoFilipeSantos** [comment]
Hi @wbt! 👋 This topic has been dormant for more than 4 years now, so it is not unreasonable to actually redirect it to our [forum](https://forum.soliditylang.org/) where these discussions can happen at length.

We do welcome any of these discussions there. 💪 
Thank you for understanding.
