### ISSUE TITLE
Post-constantinople, we should use extcodehash instead of extcodesize

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4834]
Once constantinople is finalized, we should use extcodehash instead of extcodesize to check if the called account exists, because it is cheaper.

**Comment by anurag-git** [comment]
@chriseth , is it as simple as replacing `extcodesize` with `extcodehash`. Please help to produce some details so that I can work on it

**Comment by chriseth** [comment]
Yes, it is very simple, but I think we should wait until constantinople is finalized.

**Comment by axic** [comment]
In theory it can be implemented under the `constantinople` switch, but I'd feel safer committing to this around early October because then the EIPs included in constantinople should be final.

**Comment by Agusx1211** [comment]
Bump!

This may reduce all calls to external contracts by ~300 GAS, because currently after each call the address is checked using extcodesize, which uses 700 GAS, and extcodehash uses only 400 GAS.

> @chriseth , is it as simple as replacing `extcodesize` with `extcodehash`. Please help to produce some details so that I can work on it

It should also be checked that the result of extcodehash is not `c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470` (account with no code).

**Comment by chriseth** [comment]
@Agusx1211 thanks for bringing this up again! Note that the constant `c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470` has a deploy-time cost of more than 8576 gas, so this only amortizes after 20 calls. This should be checked against the `runs` optimizer parameter.

**Comment by chriseth** [comment]
If we want to avoid providing the constant literally, we could use `keccak256(0, 0)`, which is an extra 39 gas and 4-5 bytes of code (which costs 1000 gas to deploy).

**Comment by axic** [comment]
> This may reduce all calls to external contracts by ~300 GAS, because currently after each call the address is checked using extcodesize, which uses 700 GAS, and extcodehash uses only 400 GAS.

This was an obvious pricing mistake and it is rectified by EIP-1884 in the upcoming Istanbul update.

**Comment by chriseth** [comment]
Oh wow, I thought `extcodehash` is cheaper because the size is not directly stored in the trie. So in the end, both opcodes have the same cost?

**Comment by axic** [comment]
Good point though that size is not stored, size should cost more :)

But the issue was balance and codehash should cost equal because both are stored in the account.

**Comment by chriseth** [comment]
So does that mean we can now close this?

**Comment by axic** [comment]
Unless `extcodesize` is repriced, it seems that added cost of checking for empty hash makes this change not very useful. I'd opt for closing now.

**Comment by thegostep** [comment]
Does solidity provide a global for determining if a contract exists or is this assembly technique still best approach?
```solidity
uint256 codeSize;
assembly { codeSize := extcodesize(0x123...) }
bool exists = codeSize > 0;
```

**Comment by chriseth** [comment]
It is the best approach.
