### ISSUE TITLE
About sol-ast parameters of sol-json

### ISSUE THREAD

**Issue by l3m0n** [ethereum/solidity#4839]
I want to get the number of lines of the file code corresponding to ast, But I can't find a way to get the number of lines of this file. What is the meaning of src in ast?

**Comment by l3m0n** [comment]
For example:

```
{
    "id" : 1,
    "literals" : 
    [
        "solidity",
        "^",
        "0.4",
        ".21"
    ],
    "nodeType" : "PragmaDirective",
    "src" : "119:24:0"
}
```

and file code is

```
// Abstract contract for the full ERC 20 Token standard
// https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md
pragma solidity ^0.4.21;
```

So can I know that it is the third line through ast?

**Comment by leonardoalt** [comment]
Hi @l3m0n , the `src` field tells where the source code of that AST node is in the original source file. In your example, the `PragmaDirective` is in position 119 of the Solidity file (in the absolute number of characters), and its size is 24 (`pragma solidity ^0.4.21;`).

**Comment by leonardoalt** [comment]
I'm closing this, please reopen if you have more questions.
