### ISSUE TITLE
Delete array of structs results in an infinite gas usage due to an order of properties

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#484]
Hi. Consider the following contract:

```
contract DeleteTest {
    struct DeleteStruct {
        uint8 _uint;
        uint[] _arr;
    }

    DeleteStruct[] delstr;

    function add() {
        var pos = delstr.length++;
        delstr[pos]._uint = 255;
    }

    function test1_ok() {
        add();
        delete delstr;
    }

    function test2_deadLoop() {
        add();
        add();
        delete delstr;
    }
}
```

Note: if you swap `_uint` and `_arr` it will work alright. Possible explanation is that `_uint` is treated as a `length` for the `_arr`, but it is just a guess.

Explanation would be greatly appreciated! Thanks.

**Comment by VoR0220** [comment]
could be the way it's structured in the EVM...this is interesting. I'm not certain what to label this. @chriseth do you have any ideas?
