### ISSUE TITLE
Solidity private network using another contract function unable

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#4842]
I am using remix to code solidity with voting contract

I have made a voting system in one contract and in the other contract(which is at the other .sol file) there is a function that rewards the winners.

I have tested at the ropsten test network and it worked perfectly. However, in the private network i am having trouble with using external contract function (rewarding the winner function) at the voting system contract

**Comment by leonardoalt** [comment]
Hi @jae123123 ,

Could you please provide more details? What exactly is not working? Are there any errors? What's the compiler version? Could you show a code sample that contains the problem?

**Comment by chriseth** [comment]
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
