### ISSUE TITLE
Option to Opt-out of Metadata Injection

### ISSUE THREAD

**Issue by Latrasis** [ethereum/solidity#4853]
## Abstract
Provide an opt-out input configuration option or a command-line option to omit metadata for a contract.

## Motivation
Some users want to include their own type of metadata or wish to omit any solc metadata due to security concerns.

## Specification
Provide a default setting in `settings.metadata.include` that is `true` by default, and if `false` does not include any metadata.

Update the documentation accordingly in `/using-the-compiler.html#compiler-input-and-output-json-description` section.

## Backwards Compatibility
By default  `settings.metadata.include` is true, which means previous users are not affected.

**Comment by chriseth** [comment]
Could you elaborate on the reasons you would not want metadata? The metadata is a vital security feature for users.

**Comment by Latrasis** [comment]
Hello @chriseth, thank you asking. Our [project](https://beakeros.org) aims to provide its own verification protocol and security model. External Metadata in this case would break some of its guarantees.

**Comment by Latrasis** [comment]
On a different note. As you have stated, that metadata is a _feature_ that solidity provides. If so, it would make sense to be able as a user to opt-out of such a feature.

**Comment by Latrasis** [comment]
@chriseth: Any pointers how to implement this?

**Comment by chriseth** [comment]
I'm sorry, but you won't solve your problems by removing the metadata. Your analysis tool will have to perform a reachability analysis to detect code and non-code, there is no way around it.

**Comment by Latrasis** [comment]
@chriseth: Sorry, what I meant was if you could offer support or at least some advice on how we could implement #4853 in `solc` for us to make PR.

**Comment by chriseth** [comment]
Can you come to https://gitter.im/ethereum/solidity-dev so we can discuss?
