### ISSUE TITLE
[ASSEMBLY] Read struct from storage. Combine it with memory.

### ISSUE THREAD

**Issue by kyriediculous** [ethereum/solidity#4854]
Hi,

I've tried asking on stackexchange, gitter and openzeppelin slack but to no avail yet. 

I'm using a low level delegatecall to forward my calls to a library but I'm not familiar enough with inline assemblyl to make it work. 

The full code can be found in this fiddle: https://ethfiddle.com/sd1ATrDtjy
Additionally the migrations can be found here: https://gist.github.com/kyriediculous/d2286a8a580d28a3903395490b15bcaa

I need to (in this order) :

- load bytes4 sig into _message from memory

- load bounty (STRUCT) into _message from storage 

- load bytes _data into _message

- Delegatecall with the new message

- Get return values 

The contract & library works as proven by the getBounty() function I added. The forwarder is what I'm having trouble with.
- How do I load in the bounty struct from storage? 
- How do I properly split my calldata at the first 4 bytes , copy it to memory and put the bounty struct in between? 

It seems like the struct is unpacked when I call getStorageAt, do I have to repack it? 

```
0x00
0x687474703a2f2f6170692e6269746275636b65742e636f6d2f33303433303430
0xe1bb4acb579f780cbaf21cef9ac3641b8e3fcd69
0x5b7eb10c
0x3334303330340000000000000000000000000000000000000000000000000000
0x012a05f200
0x00
0x00
0x059ce9161d4fb0
0x00
0x00
0x00
0x00
0x00
0x00
0x00
0x00
0x00
```

Please feel free to refer to stackexchange as well: https://ethereum.stackexchange.com/questions/57197/get-return-data-from-delegatecall

Many thanks.

**Comment by leonardoalt** [comment]
I haven't fully checked yet, but I'd suggest that you use `pragma experimental ABIEncoderV2`. Then you can use `abi.encode(bounty)` which is probably easier than doing the whole thing in assembly. You could also use `abi.encodeWithSignature(...)` in case it fits your case.

**Comment by kyriediculous** [comment]
Ah yes, great remark. I haven't though about that. 

Altough I still think writing it in assembly would be  more gas efficient and robusty, which is the whole goal of this endeavour (deployment costs are cut in half, I just need to get the forwarder to work).

**Comment by kyriediculous** [comment]
abi.encode doesn't work. "Item can not be encoded" probably because when referencing it that way it already is encoded.

**Comment by kyriediculous** [comment]
@chriseth , do you have an idea?

**Comment by chriseth** [comment]
Focusing on costs instead of security / clarity turned out to be fatal in several cases.

I'm sorry, but I cannot access ethfiddle because they use some google tracking which my browser cannot handle. Could you post your code to github gist or something like that?

**Comment by kyriediculous** [comment]
Oh I put it in ethfiddle because other folks I asked at OpenZep couldn't access the gist :D 

I've tried multiple things here and there but this gist should give you an idea of what it is I want to accomplish:  https://gist.github.com/kyriediculous/be33b19823324746942aa72930bb8b38 

There's two functions on the proxy contract : getBounty() and forward() 
getBounty() is the traditional way of delegating to libraries, forward() is the way I want to do it.

In order to do that I need to make calldata out of 
1. signature 
2. bounty storage struct 
3. function parameters

You're right about security, doing this in assembly could need some revisions and community audits but I really think the repeated deployment cost decrease is worth it. 

I've found a similar issue on stackexchange as well : https://ethereum.stackexchange.com/questions/13568/how-do-i-use-delegatecall-assembly-with-a-storage-pointer-to-a-struct#comment69160_13568

**Comment by chriseth** [comment]
Ok, this will not be a full answer, but at least allow you to make some progress:

Change
``` 
mstore(add(_message, 4), sload(bounty_slot))
```
to
```
mstore(add(_message, 4), bounty_slot)
```
(you only send over the slot reference to the variable)

In contrast,
```
mstore(add(_message, 36), data)
```
only copies the memory reference, but not the actual data. You need a loop that performs iterated mstores.

Because you are dealing the storage references, I think you still have to use assembly to at least retrieve the storage offset, but then you should be able to use `abi.encode`
```
uint sl;
assembly { sl := bounty_slot }
myLibrary.delegatecall(abi.encodeWithSelector(bytes4(_sig), sl, data))
```

If you provide data like that, your library function has to be `f(Bounty storage, bytes)`.

If you want data to be encoded data, I think you are out of luck, because you have to adjust all the dynamic data offsets inside there (add 0x20) because of the first storage reference.

**Comment by kyriediculous** [comment]
Hi Chris,

Thank you sincerely for your reply.
I haven't revisited this problem since september as I was busy building the application layer for my project. 

Now that it's finished I will explore this further. 

Will update the issue if I find a solution.

**Comment by leonardoalt** [comment]
@kyriediculous I'm closing the issue after @chriseth 's and your answer. Please feel free to reopen and update this issue if you have news.

**Comment by kyriediculous** [comment]
The guys of origin were so kind to share this post by vitalik https://www.reddit.com/r/ethereum/comments/6c1jui/delegatecall_forwarders_how_to_save_5098_on/ 

Which essentially gets rid of the library.
The instances are now just forwarders delegating calls to a master contract with all definitions.

Their example: https://github.com/tyleryasaka/identity-proposals/pull/1

I must have missed something in the delegatecall docs. I assumed it took the context of the calling contract and never the called contract. But it seems here the calling contract takes on the storage definitions of the called contract and has its own storage. 

I guess this means problem solved and loads of time wasted :D
