### ISSUE TITLE
solidity address.balance bug

### ISSUE THREAD

**Issue by Eggsyz** [ethereum/solidity#4857]
Hi
I deployed a smart contract on the Ropsten test network, but I can't request it when I query the local account balance, but I can query other account balances.

contract：
```
contract MetaCoin {
        function getBalance() public view returns(uint) {
                return msg.sender.balance;
        }
}
```
result
115792089237316195423570985008687907853269984665640564039457434007913129639935

**Comment by Eggsyz** [comment]
```
contract MetaCoin {

        function getBalance(address addr) public view returns(uint) {
                return addr.balance;
        }
}
```

**Comment by kyriediculous** [comment]
Both work for me.
This will return the ethereum balance, not the MetaCoin token balance. Keep that in mind.

**Comment by Eggsyz** [comment]
@kyriediculous 
hi
Thank you very much for your reply. 
The above case is just that when I am learning MetaCoin, I can modify the code test to get the Ethereum balance, but I get the Ether Balance to get the above value, and the Ether balance of other accounts is correct. And the same is true for my test results in the test chain. If you have time, you can test it in the test chain or your private chain instead of ganache.

**Comment by kyriediculous** [comment]
https://github.com/ethereum/solidity/issues/2325

**Comment by chriseth** [comment]
Closing as this does not seem to be a compiler or language issue.
