### ISSUE TITLE
Delegate Call Solution For Contract That is Too Big

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#4861]
Here is the problem to solve:
>  You want to have one contract that contains all the functionality for something. But all the functions needed exceeds the 24KB size limit for a single contract. Many of the functions are external public facing and read and write storage variables so using only library functions to solve this won't work. The various functions read and write the same storage variables.

What is the best way to handle this so that one contract is the interface for all functionality?

Below is a solution I have to this problem. I want to know if there are any potential problems with this solution or if the problem can be solved a better way.

## Solution
Create two separate contracts. Implement some of the functions in the main contract and some of the functions in the second contract. Have the main contract delegate calls to the second contract for functions it doesn't have.

Specifically here is how it is implemented:

1. Create a super contract that contains all the storage variables, including maps and arrays and value types such as address, uint256 etc. Also add to this contract implementations of public/internal functions that are used by both the main contract and the second contract.

2. Create a main contract that subclasses the super class just mentioned. Implement some of the functions in this class. Note that no storage variable are defined in this class. All storage variables come from the super class.

3. Implement a fallback function in the main contract that delegates function calls to the second contract for functions the main contract does not have. Here is the implementation of this fallback function:
```solidity
function() external {
    bytes memory data = msg.data;
    assembly {
        let result := delegatecall(gas, sload(delegate_slot), add(data, 0x20), mload(data), 0, 0)
        let size := returndatasize
        let ptr := mload(0x40)
        returndatacopy(ptr, 0, size)
        switch result
        case 0 {revert(ptr, size)}
        default {return (ptr, size)}
    }
}   
```

4. Create a second contract that subclasses the same super class. Implement some of the functions in this class. Note that no storage variable are defined in this class. All storage variables come from the super class.

### Questions

1. Is it true that for this solution to work all the storage variables need to be defined exactly the same and in the same order in both the main contract and the second contract?  

2. Does it work to define a super contract that holds all the storage variables and have both the main contract and second contract subclass it in order to get the same storage variables in the same order?

3. Are there any potential problems with this solution?

4. Could the problem be solved in a better way?

**Comment by n2nco** [comment]
"You want to have one contract that contains all the functionality for something."

"Solution: Create two separate contracts. Implement some of the functions in the main contract and some of the functions in the second contract."

Might argue this line of thinking ^ defies the single responsibility principle. 

One standard approach:
Main Proxy contract as the interface + storage, then delegatecall logic-methods to logic contract(s).

More on this:
https://blog.zeppelinos.org/proxy-patterns/ 
https://blog.zeppelinos.org/upgradeability-using-unstructured-storage/

**Comment by mudgen** [comment]
@n2nco thanks for the ideas and links. They were helpful.

**Comment by spalladino** [comment]
Maybe something like this helps? https://github.com/zeppelinos/labs/blob/master/upgradeability_with_vtable/README.md

I know it includes upgradeability, but it may help nonetheless.

**Comment by mudgen** [comment]
@spalladino Thank you, that is helpful.

**Comment by chriseth** [comment]
@mudgen sorry, but I do not yet understand the initial problem. Why is "reading and writing storage" and "using libraries" contradictory?

**Comment by mudgen** [comment]
@chriseth You are right, I seem to have had an incorrect assumption about using libraries. I worried that I would have to pass too many storage variables as arguments to library functions, or I would have to call library functions multiple times (which use DELEGATECALL) within an external function and I wouldn't want the gas cost of that. But after looking at this again these things don't look like problems. I'm not using that many storage variables and I could probably make one library call for each external function.

I worry that if I tried to fit all the external functions in one contract and used libraries extensively that it would still exceed the 24KB max size of a contract. But I didn't try this so maybe it would fit. Do you think using libraries might be a good approach here?

**Comment by chriseth** [comment]
Yes, certainly. Please try to encapsulate your data into structs and have a few contract-level variables of that struct type and then call library functions with references to these variables.

Please open a new issue if you have specific issues or suggestions.
