### ISSUE TITLE
How to use an array of strings in a mapping?

### ISSUE THREAD

**Issue by Eithcowich** [ethereum/solidity#4862]
I need to store a mapping between a string to items which are 128 bytes long in a `solidity` contract. The problem is that the longest bytes data type is `bytes32`, which is not long enough, and if I try to store my strings in a `string array` I get the following error: 

    This type is only supported in the experimental ABI encoder. Use "pragma experimental abiencoderv2;" to enable this feature

So I cannot use `bytes32` because it's not big enough. I cannot use `bytes` because it's not supported. And I cannot use `string[]` because it's experimental and not recommended in production. 

Any solution? 

This is the contract I'm using, which does not compile in `remix`: 

    pragma solidity ^0.4.24;

    contract SomeData {
    
        struct Data {
            string id;
            string[3] items;
        }

        mapping (string => Data) dataItems;

        function addData(string id, string[3] items) public {
            Data memory data = Data(id, items);
            data.id = id;
            data.items = items;
            dataItems[id] = data;
        }

        function getDataItems(string id) public view returns (string[3]){
            return dataItems[id].items;
        }
    }

**Comment by kyriediculous** [comment]
You can not use string types as keys in a mapping. Take the sha3 hash of the string.

**Comment by leonardoalt** [comment]
@Eithcowich The only parts that do not compile without the pragma experimental are actually the `string[3]` parameters. If you separate it into 3 different strings it actually compiles.

You can use string as key in mapping if the mapping is not public, which is the case here.

**Comment by Eithcowich** [comment]
Thanks Leonardo, yes, there's no problem using a string as the key. The issue with the `string[3]` is that the requirement is actually `string[100]` so it makes no sense to have method signatures with 100 params. 

Sadly the question remains, is there any way at all to have an array of strings in solidity, as the value of a mapping? Any alternative? I mean, the language / EVM cannot be that limited.

**Comment by leonardoalt** [comment]
Oh ok.
Using `mapping (string => string[]) map` is not a problem. What fails to compile then is using `string[]` as a parameter or return. Maybe there's a out around that.

**Comment by Eithcowich** [comment]
From what I can tell you can't return a `string[]` in a function. So no luck there.

**Comment by chriseth** [comment]
@Eithcowich you can use `pragma experimental "ABIEncoderV2";`.

Closing as this is not a language design or compiler issue.
