### ISSUE TITLE
C99 scoping bug with different stack height

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4864]
```
contract scoping {
    function f(uint x) public {
        int data;
        if (x > 7)
            int data2 = 1;
        else
            data = 1;
    }
}
```

Results in 
`InternalCompilerError: I sense a disturbance in the stack: 4 vs 3`

Found by @holiman

**Comment by leonardoalt** [comment]
This happens when single statement `if`s don't use `{...}`, in which case no `Block` is used. The same happens for loops.
Need to keep track of stack size for those AST nodes too.

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/4888

**Comment by holiman** [comment]
Should I restart the fuzzer on the new head now?

**Comment by chriseth** [comment]
Yes, please!
