### ISSUE TITLE
Is it Possible For an Externally Owned Account or Contract to Have a 0 Address?

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#4868]
Is there any chance at all for an externally owned account or a contract to have the 0 address?  Or does the implementation of solidity/evm make it impossible?

**Comment by axic** [comment]
Solidity or the EVM does nothing to ensure this won't happen. The probability is extremely low.

For a more comprehensive answer, better to ask this on https://ethereum.stackexchange.com
