### ISSUE TITLE
Private state variable + external getter with same name should be possible

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#4869]
It's currently not possible to do this:

```solidity
pragma solidity ^0.4.24;

contract Foo {
    uint private value;

    function value() external returns (uint) {
        return value;
    }
}
```

It fails with `DeclarationError: Identifier already declared` referring to the function `value()` and the variable `value`. This is a spurious error, though, because the function is `external` and thus it makes no sense for its name to be in scope. In fact, trying to refer to an `external` function internally raises an `Undeclared identifier` error. 

It should be possible to do this, just as it's possible to have `internal` variable + `external` getter through the use of the `public` state variable visibility.

**Comment by chriseth** [comment]
I would propose to fix that in 0.5.1 (since it is not a new behaviour) and in general add it to the inheritance discussion project.

**Comment by chriseth** [comment]
Added it to the design backlog, but I'm not too confident that this is in line with the explicitness and clarity goals.

**Comment by axic** [comment]
#5173 is also related

**Comment by cameel** [comment]
Somewhat related to #11889.
