### ISSUE TITLE
Parsing fails when import is split in multiple lines

### ISSUE THREAD

**Issue by come-maiz** [ethereum/solidity#4871]
## Description

When I split an import in multiple lines, parsing fails with:

```Cannot read property '2' of null```

## Environment

- Compiler version: Solidity v0.4.23 (solc-js)
- Framework/IDE (e.g. Truffle or Remix): Truffle v4.1.8 (core: 4.1.8)
- EVM execution environment / backend / blockchain client: ganache
- Operating system: Ubuntu 18.04

## Steps to Reproduce

When we break the import line of the following contract, truffle parsing fails. When the import is in a single line, parsing works.

```
pragma solidity ^0.4.24;

import {
  BreakInvariantBounty, 
  Target
} from "../../contracts/bounties/BreakInvariantBounty.sol";

contract InsecureInvariantTargetMock is Target {
  function checkInvariant() public returns(bool) {
    return false;
  }
}


contract InsecureInvariantTargetBounty is BreakInvariantBounty {
  function deployContract() internal returns (address) {
    return new InsecureInvariantTargetMock();
  }
}
```

**Comment by chriseth** [comment]
This sounds like an error from the javascript runtime. Also I could not reproduce it, so I think it is an issue with truffle and not with solidity.

**Comment by come-maiz** [comment]
Sorry, my mistake. I'm moving it to truffle.
