### ISSUE TITLE
Changing a value in one struct changes the value in another

### ISSUE THREAD

**Issue by koirikivi** [ethereum/solidity#4874]
## Description

Declaring two `struct`s (without the memory keyword) and setting a value in another changes the value in the other one.

## Environment

- Compiler version: v0.4.24+commit.e67f0147
- Framework/IDE (e.g. Truffle or Remix): -
- EVM execution environment / backend / blockchain client: -
- Operating system: macOS / Linux / any

## Steps to Reproduce

Test contract:

```
pragma solidity ^0.4.24;

contract Test {
    struct Struct1 {
        uint256 nonce1;
    }
    
    struct Struct2 {
        uint256 nonce2;
    }
    
    event DebugNumber(string msg, uint256 nonce);
    
    function trade() public {
        Struct1 left;
        Struct2 right;
        
        left.nonce1 = 1;
        right.nonce2 = 123;
        
        emit DebugNumber("left nonce", left.nonce1);
    }
}
```

Calling the `trade` function emits the `DebugNumber` log event with `nonce = 123`. Expected behaviour would be to emit it with `nonce = 1`, or throw an error compilation time.

Example transaction on Etherscan: https://kovan.etherscan.io/tx/0x5977386237b845c484bb0ddd29049bd744feb8bd1d03f5deec58985cda16cea6

The compiler shows a warning `Warning: Uninitialized storage pointer. Did you mean '<type> memory right'?`, and adding the `memory` keyword fixes the issue. However, this behaviour still seems fishy to me. Shouldn't the compiler at least throw an error here? When would the current behaviour be desirable?

Thanks to @villesundell for debugging the issue with me and finalizing the test contract.

**Comment by leonardoalt** [comment]
This has been fixed in the latest unreleased version:
The location keyword (`memory` or `storage`) is enforced. If you use `memory` it works fine. If you use `storage` the compiler reports a `DeclarationError` about the uninitialized storage pointer. If you declare storage structs and point to them, it also works fine.
