### ISSUE TITLE
Unnamed function parameters should not be pushed to stack

### ISSUE THREAD

**Issue by rmeissner** [ethereum/solidity#4875]
## Abstract

When defining a method signature it is possible to not give a name to a method parameter. This indicates that this parameter is not used.

## Motivation

 In methods that are marked external this could be used to avoid that unnecessary data is polluting the stack. Also it allows to get around the limit of local variables. 

## Specification

When a method parameter has no name the parameter should not be pushed on the stack. Currently each parameter is pushed on the stack no matter if it is used or not.

```
contract Test {
    function bar(uint256, uint256) external {}
}
```

generates EVM code that calls `calldataload` 2 times, event so neither one is ever used (or assigned a name)

**Comment by chriseth** [comment]
I would defer this to the new optimizer which will be able to re-arrange the stay layout.
