### ISSUE TITLE
How to transfer eth from contract address to external address?

### ISSUE THREAD

**Issue by spursy** [ethereum/solidity#4876]
In my smart contract, I need transfer eth from contract address to external address?

**The followed is my code:**

```
            address ower = msg.sender;
            require(address(this).balance > 0.1 * 10^18 * deleteCount, "Contract address does not exist enough money.");
            address(this).balance -= 0.1 * (10^18);
            ower.transfer(0.1 * 10^18 * deleteCount);
            emit WinCoin(msg.sender, 0.1 * 10 ^ 18);
```

**but I get error message:**

```
Expression has to be an lvalue.
            address(this).balance -= 0.1 * (10^18);
            ^-------------------^
Operator -= not compatible with types uint256 and rational_const 12 / 5
            address(this).balance -= 0.1 * (10^18);
            ^------------------------------------^
```

**Comment by redsquirrel** [comment]
This seems like a question for https://ethereum.stackexchange.com/

**Comment by EricChengBlockChain** [comment]
i think u need to write a function ,which need ur approvment to call and then can transfer ur contract account's coins to other external account .  it means transfer your contract account's coins out cann't be done by itself, only can other's call ur function to transfer it out , but u can set a approvement mapping to keep it safe.

**Comment by chriseth** [comment]
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
