### ISSUE TITLE
InternalCompilerError when inheriting contract doesn't provide constructor arguments

### ISSUE THREAD

**Issue by kdelwat** [ethereum/solidity#4879]
## Description

Compiling a contract fails with an `InternalCompilerError` when:
- The contract instantiates another contract (`Child`), and
- The instantiated contract (`Child`) inherits from a parent contract but does not provide any arguments to its constructor

It might be nicer to detect the problem and return a human-readable error 😄 

## Environment

- Compiler version: Version: 0.4.24+commit.e67f0147.Linux.g++
- Framework/IDE (e.g. Truffle or Remix): `solc`
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 16.04 LTS (Windows Subsystem for Linux)

## Steps to Reproduce

A minimal example of the problem is: 

```sol
pragma solidity 0.4.24;

contract Test {
    function createChild() public {
        Child asset = new Child();
    }
}

contract Parent {
    constructor(address _address) public {}
}

contract Child is Parent {
}
```

Compiling with solc (`solc --overwrite --abi --bin --bin-runtime = -o . Fail.sol`) produces the error:

```
Internal compiler error during compilation:
/tmp/nix-build-solc-0.4.24.drv-0/source/libsolidity/codegen/CompilerContext.cpp(144): Throw in function const dev::eth::Assembly& dev::solidity::CompilerContext::compiledContract(const dev::solidity::ContractDefinition&) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Compiled contract not found.
[dev::tag_comment*] = Compiled contract not found.
```

**Comment by chriseth** [comment]
Thanks for reporting! As we are currently trying to get out version 0.5.0 as soon as possible, I queued the bug for the 0.5.1 version, I hope that's ok for you.
