### ISSUE TITLE
Prefix file:// in standard json input not working

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#4884]
If files are given as urls in the standard json input, the prefix `file://` is not taken into account. Removing `file://` works fine.

Command line:
`solc --allow-paths /home/leonardo/somepath --standard-json < file.json`

File.json:
```
{
  "language": "Solidity",
  "sources":
  {
    "B.sol":
    {
      "urls": [ "file:///home/leonardo/somepath/B.sol" ]
    }
  },
  "settings":
  {
    "outputSelection": {
      "*": {
        "*": [ "evm.bytecode.linkReferences", "metadata" ]
      }
    }
  }
}
```

**Comment by axic** [comment]
Is `file://` a documented feature?

**Comment by leonardoalt** [comment]
It's in the example here: https://solidity.readthedocs.io/en/v0.5.0/using-the-compiler.html#input-description

**Comment by axic** [comment]
Ok, it is a bug then :)

**Comment by isachard** [comment]
@leonardoalt  can I work on this bug?
