### ISSUE TITLE
Pass parameter to soljson from truffle cli

### ISSUE THREAD

**Issue by jaypersanchezshyft** [ethereum/solidity#4898]
Trying to pass parameter to solidity when run from truffle.  I setup the parameter setting from truffle.js.  the content of truffle.js is below.
```
module.exports = {
  solc: {
    bogusparam: {
      enabled: true,
      runs: 200
    }
  },
  networks: {
    ganache: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id
      gas: 3500000
    },
    rinkeby: {
      host: "localhost",
      port: 8545,
      network_id: 4, //rinkeby test network
      gas: 4700000
    },
    live: {
      host: "localhost",
      port: 8545,
      network_id: 1, //official identifier for main net
      gas: 4700000,
      gasPrice: 2000000000   //set gas price go to https://ethgasstation.info/
    }
  }
};
```
below is the bogus parameter for solidity
```
solc: {
    bogusparam: {
      enabled: true,
      runs: 200
    }
```

I don't get a compile error when I run truffle migrate.  But when I change to "-bou
## Environment

- Compiler version: Solidity v0.4.24
- Framework/IDE (e.g. Truffle or Remix): Truffle v4.1.16
- EVM execution environment / backend / blockchain client: N/A
- Operating system: MacOS

## Steps to Reproduce

create a truffle project using truffle init and unbox metacoin.  Add the entry into truffle.js
```
module.exports = {
  solc: {
    bogusparam: {
      enabled: true,
      runs: 200
    }
  },
  networks: {
    ganache: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id
      gas: 3500000
    },
    rinkeby: {
      host: "localhost",
      port: 8545,
      network_id: 4, //rinkeby test network
      gas: 4700000
    },
    live: {
      host: "localhost",
      port: 8545,
      network_id: 1, //official identifier for main net
      gas: 4700000,
      gasPrice: 2000000000   //set gas price go to https://ethgasstation.info/
    }
  }
};
```

from the project directory run truffle command:
truffle migrate --network development

**Comment by chriseth** [comment]
I created https://github.com/ethereum/solidity/issues/4902 to track what I think its the problem here. Please reopen if you are talking about something else.
