### ISSUE TITLE
Base constants and functions not properly handled.

### ISSUE THREAD

**Issue by mxmauro** [ethereum/solidity#4900]
Compiler: `0.4.24+commit.e67f0147.Emscripten.clang`

Hi, let me describe the issue:

I have a function named `depositToken`:

```
function my_test_function(address currency) public view returns (bytes4) {
    TransferController controller = getTransferController(currency);
    return controller.getReceiveSignature();
}
```

`getTransferController` returns an `ERC20TransferController` object derived from `TransferController`.

Inside base class `TransferController` I have:

```
bytes4 public constant RECEIVE_SIGNATURE = bytes4(keccak256("receive(address,address,uint256,address,uint256)"));

function getReceiveSignature() public view returns (bytes4) {
        return bytes4(keccak256("receive(address,address,uint256,address,uint256)"));
}
```

`my_test_function` works as is BUT

1. if `TransferController.getReceiveSignature` is `pure` instead of `view`, the call raises a `revert`.
2. if I replace `controller.getReceiveSignature()` with `controller.RECEIVE_SIGNATURE`, compiler complains because can't handle conversion no matter if I also remove the `constant` keyword of `bytes4` to `bytes4`.

Regards,
Mauro.

(btw: `getReceiveSignature` is used in a `delegatecall`)

**Comment by chriseth** [comment]
Are you able to condense this down to a minimal example (perhaps separate for the two issues)?

**Comment by chriseth** [comment]
Did you use a debugger to find out where exactly the revert is issued?

**Comment by mxmauro** [comment]
@chriseth I'll try. Tried with a similar sample with Remix and cannot reproduce it :(

**Comment by chriseth** [comment]
This might also be related to using an outdated EVM in your setup (i.e. not byzantium-compatible).

**Comment by chriseth** [comment]
Closing for now. Please re-open if you can reproduce the issue.
