### ISSUE TITLE
Consider picking some points from Populus' Solidity Gotchas

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4913]
See: https://populus.readthedocs.io/en/latest/gotchas.html

**Comment by axic** [comment]
Good points to include:
- ~[2] Everything the contract stores in it’s persistent storage costs money, the gas. Try to minimise storage only to what absulutly positively is required for the contract to run. Data like derived calculations, caching, aggregates etc, should be handled on the client.~
- ~[4] The pricing of contract storage is not linear. There is a high initial cost to setting the storage to non zero (touching the storage)~. 
- ~[5] Everything the contracts uses for temporary memory costs money, the gas. The pricing of using memory, the part that is cleared once execution done (think RAM), is not linear either, and cost per the same unit of usage increases sharply once you used a lot of memory. Try to avoid unreasonable memory usage~.
- ~[6] Even when you free storage, the gas you paid for that storage is partially refundble if. Don’t use storage as a temporary store~.
- ~[9] Whenever you just send money to a contract (a transaction with value > 0), even without calling any function, you run the contract’s code~.
- [28] Don’t use rounding for Eth in the contract, since it will cost you the lost money that was rounded. Use the very fine grained Eth units instead.
- ~[44] The contract’s Constructor runs only once when the contract is created, and can’t be called again. The constructor is optional~.
- ~[50] delete does not actually deletes, but assigns the initial value. It’s a special kind of assignment actually. Deleting a local var variable that points to a state variable will except, since the “deleted” variable (the pointer) has no initial value to reset to. {this is not entirely correct}~
- ~[51] Declared variables are implictly initiated to their initial default value at the begining of the function~.

Other points may be useful too, but I think the above may not be well documented.

**Comment by ChrisChinchilla** [comment]
@axic Do you have any idea what might be missing here:

> [6] Even when you free storage, the gas you paid for that storage is partially refundble if. Don’t use storage as a temporary store.

It's the same issue on the their rendered copy, and I'm not sure what important detail is missing.

**Comment by axic** [comment]
What the point is about is that on "deleting" a storage entry, one may receive a refund. This only happens if setting an entire store slot to 0 and it is unlikely to be triggered when handling arrays or structs, because their members are stored in a packed manner.

I am not sure to what extent we have the above explained.

What this point here tries to emphasize that even if this refund mechanism exists, it is advised against to rely on using storage entries for temporary storage. We can debate whether this is a valid point or not.

**Comment by ChrisChinchilla** [comment]
OK, looked through docs and I think this is covered enough.

**Comment by axic** [comment]
> [28] Don’t use rounding for Eth in the contract, since it will cost you the lost money that was rounded. Use the very fine grained Eth units instead.

Was this part handled?

**Comment by chriseth** [comment]
Yes.
