### ISSUE TITLE
[ABI Specification] Boolean example is incorrect

### ISSUE THREAD

**Issue by ignacionr** [ethereum/solidity#4933]
## Description

The ABI documentation introduces the ``` bool ``` data type as a specific use of ``` uint8 ```, but when an example is developed, it is padded to 32 bytes instead of 8.

The problem is on https://github.com/ethereum/solidity/blob/develop/docs/abi-spec.rst#examples (first example shown).

**Comment by chriseth** [comment]
The specification states than `unt8` is padded to 32 bytes, so the same applies to `bool`.

**Comment by ignacionr** [comment]
Hm. It’s disappointing because of the unnecessary bandwidth but understood.
