### ISSUE TITLE
Debug info for Solidity

### ISSUE THREAD

**Issue by liangdzou** [ethereum/solidity#4943]
## Abstract

Do we need debug info for the generated binary somehow? At least, add them for the generated assembly for the case without optimization? This is important for some advanced user to know how the compiler works. Code always explains more clearly than any documents.

## Motivation

Debug info can be used in many ways, e.g. locating the most important codes in ASM for reading, used for other debugging tools.

## Possible implementation

For simplicity, it is better to avoid modifying current binary generation. So, I think it is better to save the information in a json file.

When we generate ASM for an AST node, we mark the line info of the AST node to each generated ASM nodes. This will require us to add some attributes, such as line or column, for ASM nodes, or maybe even for the AST node.

Then, during outputting the binary file, outputs the map from EVM instructions to line infos to a json file. We may also need to pass the line info during optimation, or simply mark the line info as optimized when it cannot find from the map in json file.

When outputting the textual ASM file, we can output its line info after each instruction.

We may also be able to add code info to the generated ASM file. Current implementation actually has some codes in the generated textual ASM file but has very few information.

## Backwards Compatibility

n/a

**Comment by chriseth** [comment]
We have source info and it is retained during most of the optimzation phases: https://solidity.readthedocs.io/en/v0.4.24/miscellaneous.html#source-mappings

**Comment by liangdzou** [comment]
yeah, I just found srcmap from solc. sorry :-(
