### ISSUE TITLE
Yul code generator / transform that can re-use stack slots

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4944]
As a precursor to other optimization techniques, we need a code generator for yul that can handle the load of many local variables (e.g. those generated via transformation to SSA). Currently, variables are assigned to a stack slot in a fixed way from the point on where the variable is declared until the end of the block. This is very helpful for debugging, but can lead to "out of stack" problems or just excessive DUP/SWAP instructions.

As an optional setting, EVMCodeTransform should be able to reuse stack slots of variables which will not be used anymore. The strategy could be as follows:

In each `operator()(Assignment`, the code transform determines the deepest stack slot that is currently used by a variable that will not be referenced anymore. The component will perform a matching `swap` instruction followed by a `pop` and update the internal assignments from variables to slots. Furthermore, after each statement, the transform checks whether the topmost stack element is still in use and pops it if not.

Note that this can only be used for "strict yul", i.e. if `StackAssignment` operations are not allowed (this one can then obviously be skipped).

**Comment by chriseth** [comment]
Perhaps this would be something for you, @liangdzou ?

**Comment by liangdzou** [comment]
Do you mean when there is an assignment then the variable is a new variable according to SSA definition? Then, the corresponding variable can be released by swap the deepest variable and pop. Will try my best to finish it soon. :-)

**Comment by liangdzou** [comment]
From the asm of a simple example, we can see that Solidity updates local variables by calcualte and swap to update. Actually we cannot gerantee that a veraible on the lhs or rhs of a assignment will not be used anymore. We have to do some kind of liveness analysis. @chriseth @ekpyron Is that available in Solidity now? (Correct me if I have misunderstanding here, thanks :-))
```
 72         /* "t.sol":45:50  int x */                                              
 73       0x0                                                                       
 74         /* "t.sol":53:54  6 */                                                  
 75       0x6                                                                       
 76         /* "t.sol":45:54  int x = 6 */                                          
 77       swap1                                                                     
 78       pop                                                                       
 79         /* "t.sol":58:63  int y */                                              
 80       0x0                                                                       
 81         /* "t.sol":66:67  8 */                                                  
 82       0x8                                                                       
 83         /* "t.sol":58:67  int y = 8 */                                          
 84       swap1                                                                     
 85       pop                                                                       
 86         /* "t.sol":75:76  y */                                                  
 87       dup1                                                                      
 88         /* "t.sol":71:76  x = y */                                              
 89       swap2                                                                     
 90       pop                                                                       
 91         /* "t.sol":84:85  7 */                                                  
 92       0x7                                                                       
 93         /* "t.sol":80:85  x = 7 */                                              
 94       swap2                                                                     
 95       pop                                                                       
 96         /* "t.sol":15:89  function f() public pure {... */                      
 97       pop                                                                       
 98       pop                                                                       
```

**Comment by liangdzou** [comment]
Seems the outputed asm and yul (the one defined in libsolidity/inlineasm/AsmData.h) might be different.
I will try to print out yul to take a look.
Btw, do we have an option to print out yul?

**Comment by liangdzou** [comment]
The moveable test seems a solution for the liveness analysis. A variable is dead if the assignment can move to the end of the function and there is no read afterward.

**Comment by liangdzou** [comment]
I have several questions about this issue:
1. the pass "Unused Definition Pruner" will remove useless assignments if it can move to the next assignment for the same variable. Can we regard this requirement as a special case of that? That is, when an assignment can move to the end of the function, we should also remove the assignment. Then, the last reference of a variable will always be a read which is very reasonable according to the common sense. The new pass should be created based on this assumption and then remove the variable by swap pop after the last read. @chriseth @ekpyron what do you think? (I am not sure if I understood the problem here. Forgive me in case that I am wasting your time here :-))
2.  I have not seen UnusedPruner been called anywhere except the test files. Is this supposed to be so? I grepped from the whole source file and it seems not used anywhere. I was planning to insert this pass after the pass UnusedPruner, so, I need to know where is it called.
Thanks for your time and patients. :-)

**Comment by liangdzou** [comment]
@chriseth @ekpyron I think if it is an assignment, it should already be removed by this pass. I think the case should be that the variable can be removed after the last read.

**Comment by liangdzou** [comment]
I have not seen UnusedPruner been called anywhere except the test files. Is this supposed to be so?

**Comment by recmo** [comment]
Optimally converting SSA variables to a stack VM  is a problem that has been bugging me for a while. It seems like something thing that would have been well studied in CS literature. Especially considering the Java VM is stack based and has received a ton of research.

What I found so far is the Treegraph algorithm from "Treegraph-based Instruction Scheduling for Stack-based Virtual Machines" (Park et al. 2011) [paper][paper] [presentation][presentation].

AFAIK their results are optimal in the sense that no SWAPs are performed.

I'm not sure if operator commutativity is taken into account when creating the topological sorts, this could be an interesting extension of the algorithm.

[paper]: https://www.researchgate.net/publication/220369290_Treegraph-based_Instruction_Scheduling_for_Stack-based_Virtual_Machines/fulltext/0ffbba050cf2c250b171f0fe/220369290_Treegraph-based_Instruction_Scheduling_for_Stack-based_Virtual_Machines.pdf?origin=publication_detail
[presentation]: https://pdfs.semanticscholar.org/presentation/1a65/e787b08fe8812797a0557760ae84072ad292.pdf

**Comment by liangdzou** [comment]
@Recmo Cite from the paper, "Instead of saving a multiply-used value in a temporary, our method keeps all values on the stack, which avoids costly store and load instructions."

So, it seems the algorithm avoids load/store from memory. But the work here is to reuse stack slot according to variables' lifetime.

**Comment by recmo** [comment]
That citation is a comparison to a different strategy where variables are allocated memory slots that need to be load/stored from. Solidity doesn't use this strategy so the quote is not relevant here.

The algorithm itself has little to do with load/store elimination, it's all about optimally scheduling operations on a stack machine. The presentation is 

Please see the presentation I linked starting from slide 8.

**Comment by chriseth** [comment]
Ah, that paper indeed seems very relevant here!
Still, I think we should first implement the straightforward way. Created https://github.com/ethereum/solidity/issues/5375 to track the treegraph algorithm.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/5008
