### ISSUE TITLE
Remove libdevcore from solidity

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#495]
If possible, remove any reference to libdevcore from solidity. The following headers are still included:

```
#include <libdevcore/Assertions.h>
#include <libdevcore/CommonData.h>
#include <libdevcore/Common.h>
#include <libdevcore/CommonIO.h>
#include <libdevcore/Exceptions.h>
#include <libdevcore/FixedHash.h>
#include <libdevcore/Hash.h>
#include <libdevcore/SHA3.h>
#include <libdevcore/UndefMacros.h>
```

If this is done, we should check that the solc package in ubuntu does not depend on anything else from the eth world.

**Comment by axic** [comment]
@chriseth @bobsummerwill is this issue still relevant? Probably better to close it.

**Comment by bobsummerwill** [comment]
Nope - the orphaned subset which we now have is approximately the subset which we depend on.
Sure - we can likely trim it down further and tidy it up now that it is severed and refactoring is more tractable.   But essential "done".

Another question, though, is whether this copy should actually be re-namespaced and/or just moved into libsolidity or whatever.
