### ISSUE TITLE
Another look at ``address payable``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4969]
We decided to merge #4911, although there were some open questions, so we should have another look at it at some point, mainly:

- [x] Is the documentation updated sufficiently (related: #4950) #5004 
- [x] What should the behaviour of address and address payable be during overloading and inheritance?
- [x] Should ``ecrecover`` return ``address payable`` instead of ``address``?
- [x] Maybe simplify the ASTJSON test case.
- [x] add a link from ecrecover to address where it is explained how to typecast. #5005

**Comment by ekpyron** [comment]
Since it also concerns ``address payable`` and doesn't really warrant a new issue, I just put it here: I created a PR in https://github.com/davidhq/SublimeEthereum/pull/26, that is merged by now - if I understand correctly, how things work, this should be pulled in with the next release of ``linguist`` and after that syntax highlighting for ``address payable`` should work on github...

**Comment by chriseth** [comment]
Decision in call: address and address payable are two different types, just as uint and uint8 are. Nothing special will be done about inheritance / overloading.

**Comment by chriseth** [comment]
Decision in call: Since `address` can be in principle converted to `address payable`, it is probably safer to just return `address` from ecrecover.

 - [x] add a link from ecrecover to address where it is explained how to typecast. #5005
