### ISSUE TITLE
Implement accessors for mappings with strings as keys

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#498]

**Comment by GETFL** [comment]
Is this feature still under development?

**Comment by chriseth** [comment]
It is not in progress, but still planned.

**Comment by MicahZoltu** [comment]
What is the proper way to signal support/desire for features in this project?  Is adding a 👍 reaction to the original noticed by anyone, or is there a better way to say, "I could really use this feature too"?

**Comment by ekpyron** [comment]
@MicahZoltu I think a comment saying "I could really use this feature too" will probably work best :-). At least I noticed that one and hadn't noticed the :+1: reaction.

**Comment by chriseth** [comment]
Adding to 0.5.5....

**Comment by chriseth** [comment]
(no promises, though ;) )
