### ISSUE TITLE
Korean Docs translation

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#4988]
This issue is to track the progress of the Korean translation of the Solidity documentation.

It includes the GitHub usernames of all involved, and links to any issues or pull requests related to the Korean translation.

All translation efforts in progress from this date are pinned to commit 
https://github.com/ethereum/solidity/commit/1994b51ef3eb8de3617efec9747979c9fb5ed453

## Contributors

Based on comments in pull requests and issues, and other conversations. If you also want to be involved, please comment below.

@kcyang @dongsam @PhyrexTsai @mrblocktw @GoodVincentTu @bartkim0426

## Fork

https://github.com/solidity-korea/solidity-docs-kr

**Comment by Hyuntae-91** [comment]
Hello, @ChrisChinchilla.
I'm interested in translation. Could you please let me know the guideline to Contribute to translation?
I already checked the document, I can't find the guideline for translation.
Thank you.

**Comment by bartkim0426** [comment]
I want to participate in Korean translation.

**Comment by Hyuntae-91** [comment]
Dear, @bartkim0426.
You can check [this link](https://github.com/solidity-korea/solidity-docs-kr).
There are already translation team. 
The work is not going on, but, I think we can participate in there.

**Comment by ChrisChinchilla** [comment]
Great @bartkim0426 we look forward to seeing your contributions, and great to see the progress @Hyuntae-91

**Comment by ChrisChinchilla** [comment]
Hey @kcyang @dongsam @PhyrexTsai @mrblocktw @GoodVincentTu @bartkim0426

just checking in to see if all is well, I can see a few commits in the past few weeks in the fork, so looks like progress is happening. Again, any questions or problems, please let me know :)

**Comment by franzihei** [comment]
We are currently working on a new, hopefully more structured workflow for the Solidity docs translations. I will ping you once this is ready. Closing this issue for now, you can track the progress of the new process etc. in issue #10119.

**Comment by jamesjahng** [comment]
Is there any update with Korean translation team?

It seems like stopped last 3 years ( v 0.5.0 ↑ )
