### ISSUE TITLE
Chinese Docs translation

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#4989]
This issue is to track the progress of the Chinese translation of the Solidity documentation.

It includes the GitHub usernames of all involved, and links to any issues or pull requests related to the Korean translation.

All translation efforts in progress from this date are pinned to commit 
https://github.com/ethereum/solidity/commit/1994b51ef3eb8de3617efec9747979c9fb5ed453

## Contributors

Based on comments in pull requests and issues, and other conversations. If you also want to be involved, please comment below.

@fkysly @zhuangjinxin @hongbinzuo @PhyrexTsai @mrblocktw @GoodVincentTu

## Fork

TBD

**Comment by ChrisChinchilla** [comment]
Hey @fkysly @zhuangjinxin @hongbinzuo @PhyrexTsai @mrblocktw @GoodVincentTu

Just checking in to see how things are going with the Chinese translation? Would be great if you could tell me the fork so we can add it to the list of translations. Any other questions or problems, let me know.

**Comment by franzihei** [comment]
We are currently working on a new, hopefully more structured workflow for the Solidity docs translations. I will ping you once this is ready. Closing this issue for now, you can track the progress of the new process etc. in issue #10119.
