### ISSUE TITLE
Too many indexed arguments compiler error

### ISSUE THREAD

**Issue by sillytuna** [ethereum/solidity#50]
If too many indexed arguments are used in an event, an internal compiler error is reported with a dev tag  of `Too Many indexed arguments` rather than a regular error report.

Additionally, no error is reported if the event isn't referenced but is in the code.

**Comment by LianaHus** [comment]
@sillytuna thanks for report. Could you please provide us the source code that cause the internal compiler error, because there is a check for that and I can't reproduce your problem.

**Comment by sillytuna** [comment]
`event addressAddressBytes32Int(bytes32 indexed id, address indexed addr, address indexed addr2, bytes32 indexed msg, int value, uint gas);`

```
Internal compiler error during compilation:
/build/cpp-ethereum-8d6f4q/cpp-ethereum-0.9.41+1171SNAPSHOT20150819104856trusty/libsolidity/ExpressionCompiler.cpp(579): Throw in function virtual bool dev::solidity::ExpressionCompiler::visit(const dev::solidity::FunctionCall&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = Too many indexed arguments.
```

```
solc --version
Version: 0.1.1-0/Release-Linux/g++/int
```

The report only happened once I tried to raise the event. The bug had been present before use.

(embark was broken for the most recent solc update at the time of the post)
