### ISSUE TITLE
Payable as a parameter in the ABI interface JSON

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#500]
It is planned to have a modifier for functions explicitly enabling or disabling receiving value transfer (transactions where `msg.value != 0`).

If that becomes implemented it would be make sense including that as a flag in the interface JSON, e.g: `"payable": true`

**Comment by axic** [comment]
This has been renamed to `payable`.

**Comment by chriseth** [comment]
We want that for 0.4.0 don't we? If yes, please add the "nextrelease" tag.

**Comment by axic** [comment]
Fixed in #665.
