### ISSUE TITLE
Self-testing documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5000]
When we state some behaviour of Solidity in the documentation and give an example, the example should be verified as part of the CI runs.

Example:

Notet that the uint256 type wraps around at 2**256: ``uint256(2**256-1) + 1 == 0``

This should be automatically translated to
```
contract c {
function f() {
  assert(uint256(2**256-1) + 1 == 0);
}
}
```
and executed to check that it does not throw.

The same should be done with e.g. statements about inheritance, where the template needs to be different, of course.

**Comment by ChrisChinchilla** [comment]
I also have a lot of text linting tools I would love to add too. They are probably simpler after some configuration, and you can define what error threshold 'breaks' a build etc.
