### ISSUE TITLE
Document that pragmas (sometimes?) are preserved across import statements

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5015]
See https://github.com/ethereum/solidity/pull/5009#discussion_r218447324

**Comment by axic** [comment]
I think this have been a false alarm (it doesn't happen anymore), example:

```
pragma experimental SMTChecker;

import "./2nd.sol";

contract D {
  function f(address a) public {
    C(a).f(1);
  }
}
```
```
contract C {
  function f(uint a) public {
    a = a + 1;
  }
}
```

However the pragma section in the documentation could be improved a bit to be more explicitly saying that pragmas are local to the file.

**Comment by ChrisChinchilla** [comment]
OK, @axic can I check a couple of other things while we're discussing `pragma`s that could also do with docs improvements.

1. What prgama is applied if you don't specify one?
2. If I understand you correctly, and this is just to clarify, so every file is compiled with a different pragma version, even if you import a file into another with two different versions for example?
