### ISSUE TITLE
Feature to allow libraries to be added to multiple datatypes without using wildcard

### ISSUE THREAD

**Issue by decanus** [ethereum/solidity#5018]
## Abstract

The goal of this feature is to add the ability to apply a library to multiple data types easily without having to use the wildcard statement.

## Specification

There are 2 possible ways to represent this.

### 1

```solidity
using SafeMath for {
  uint256, 
  uint128
};
```

### 2

```solidity
using SafeMath for uint256, uint128;
```

**Comment by chriseth** [comment]
I like the second option!

**Comment by bshastry** [comment]
I bumped into this issue when using multiple libraries in a contract. Simple repro

```
library X {
  function prng(uint self) internal returns (uint) { return self; }
}
library Y {
  function prng(uint self) internal returns (bool) { return self == 42; }
}
contract C {
  using X for *;
  using Y for *;
  function f() public {
    1337.prng();
  }
}
```

The example above is synthetic. However, one could imagine a scenario where libraries `X` and `Y` provide utilities for more than one type and one would want to use a specific library for a given set of types.

**Comment by chriseth** [comment]
This can probably be fixed together with extending `using for` to free functions: #9211
