### ISSUE TITLE
Extend storage layout documentation

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5023]
The storage layout of mappings and dynamic arrays should be explained in more detail. Also explaining how ``push()`` and ``pop()`` work would be beneficial.

**Comment by chriseth** [comment]
push and pop should be explained in the type section in terms of delete, incrementing length, etc.

**Comment by ChrisChinchilla** [comment]
Can I help here @bit-shift ?

**Comment by erak** [comment]
You could review https://github.com/ethereum/solidity/pull/3834, please 😄
