### ISSUE TITLE
Any documentation on how to compile solc into soljson?

### ISSUE THREAD

**Issue by wuya666** [ethereum/solidity#5028]
There are instructions on how to compile solc and soltest, there are also pre-compiled soljson releases in the solc-bin repository, but I can't seem to find any clear instructions on how to build soljson from the source?

**Comment by chriseth** [comment]
The reason is because it is not that easy. There is the script `scripts/build_emscripten.sh` but it has some quirks. If you are up to it, we would love to have your feedback about it and incorporate it into the documentation.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
