### ISSUE TITLE
Suspected transaction OOG error never thrown and tx never rolled back

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum/solidity#504]
Creating a contract where a suspected transation OOG error occurs but is never thrown and transaction never rolled back.
In our case this results in a bytes32 -> address mapping being populated with an odd Contract address of format [0x74696f6e5f544553540000000000000000000000] which appears to be formed from the post 8 chars of the byte32 key with which we try to create it instead of the contract address itself. Also no OOG error is thrown.
Code sample here:
https://github.com/elenadimitrova/ContractFactory

**Comment by thiagodelgado111** [comment]
Same problem here: https://github.com/thiagodelgado111/ContractFactory, forked from @elenadimitrova's repo

**Comment by chriseth** [comment]
Thanks for the report! Can you reduce it to a smaller example, a single function call and potentially a solidity-only example? First shot: This looks like an encoding problem in web3.js.

**Comment by elenadimitrova** [comment]
Note that the problem appears only when the calling contract is over a certain size. Despite that I've tried to simplify as much as I can, see updated version in git. To see what I mean you can try to remove the unused method `upgradeOrganisation` in `Parent` contract and see the test starts passing, when it is included in the body of the contract (even though it is never called), the test fails.

**Comment by chriseth** [comment]
Could you please describe the problem more? Is it a violation of type safety or rather the fact that a function did not throw although it should have been? Furthermore, the test framework adds additional complexity and abi encoding and decoding functions especially to and from javascript have shown to be buggy in the past.

**Comment by elenadimitrova** [comment]
I tried **not** going through truffle and just using your solidity browser and the same call to parent.createOrganisation() there works while it fails in truffle. Meaning that indeed it is probably an issue in the test framework. I will shift this issue there.
