### ISSUE TITLE
Check: Can view functios call view library functions?

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5042]
Are view functions allowed to call public view functions of libraries? This should not be possible because we cannot use staticcall here, we have to use delegatecall (because of storage access). We would need a combination of staticcall/delegatecall.

**Comment by chriseth** [comment]
Current situation: `delegatecall` is used for view functions in libraries.

I think this is probably fine, becaus library code is usually trusted since libraries cannot be called dynamically. This basically means that the static checker is merely extended to the library.

We should change the documentation, though.

**Comment by ChrisChinchilla** [comment]
Are you working on this @chriseth ? Or want me to do it?
