### ISSUE TITLE
Accessing internal (internal?) function type in contract causes codegen crash

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5055]
Found by solfuzzer.

```
contract C {
    function () internal returns (uint) x;
    constructor() public {
        C.x;
    }
}
```

Error:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/ExpressionCompiler.cpp(1164): Throw in function virtual bool dev::solidity::ExpressionCompiler::visit(const dev::solidity::MemberAccess &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Function not found in member access
[dev::tag_comment*] = Function not found in member access
```

**Comment by anurag-git** [comment]
@axic , would like to take up this issue. Please let me know what do you expect from the fix.

**Comment by anurag-git** [comment]
Also didn't quite understood this code `function () internal returns (uint) x;`. What we are trying to accomplish here.

**Comment by chriseth** [comment]
@anurag-git this is a declaration of a variable that has a function type. `C.x` should work in the same way for state variables of all types. Please don't try to solve this bug unless you fully understands its implications, it might be quite tricky.

**Comment by anurag-git** [comment]
Sure Thanks
