### ISSUE TITLE
Code Snippet in Documentation Contains Bug

### ISSUE THREAD

**Issue by LucasAschenbach** [ethereum/solidity#5062]
If you follow this [link ](https://solidity.readthedocs.io/en/v0.4.25/assembly.html) and scroll down to the second code example for Inline-Assembly you will find a function called `sumPureAsm()` which is supposed to cumulate all elements of a dynamically sized array of the type `uint256`. However, when executing this function the return value is always 0.

This code should fix the issue:
```
function sumPureAsm(uint256[] _data) internal pure returns (uint256 x) {
    assembly {
        let len := mload(_data)
        data := add(_data, 0x20)
        for { let end := add(data, mul(len, 0x20)) } lt(data, end) { data := add(data, 0x20) } {
            x := add(x, mload(data))
        }
    }
}
```
The fix is in line 5 where I multiply `len` with `0x20` before adding it to `data`.

**Comment by chriseth** [comment]
Thanks for the find! Do you want to create a pull request with the fix? https://github.com/ethereum/solidity/edit/v0.4.25/docs/assembly.rst

**Comment by LucasAschenbach** [comment]
Sure!

**Comment by LucasAschenbach** [comment]
The file in the github repository already had the fix when I forked... just the code in the documentation contains the mistake.

**Comment by chriseth** [comment]
Ah I'm sorry, then I didn't pay close enough attention. Thank you anyways!
