### ISSUE TITLE
Consider defaulting to IPFS for metadata hash

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5064]
Now that cloudflare added an ipfs proxy, we might be much better off defaulting to ipfs.

Any opinions?

**Comment by axic** [comment]
Do you have a suggestion for metadata configuration options in standard json?

**Comment by chriseth** [comment]
I thought about just switching, but the config option might be named `metadataCAS: ipfs` (content-addressed-storage)

**Comment by chriseth** [comment]
Added a test file: QmdB5JktqW6LPioJXACMxPqLeB36LtZ4ZN8oE31EkiuAHt

**Comment by chriseth** [comment]
After some failures, we started another ipfs node on the same network, it automatically connected to the first node and got the file. It still was not on the gateway but when I checked 30 minutes later, it appeared on the gateway. So now I think the next test is to wait for some days and re-check if it is still on the gateway.

**Comment by chriseth** [comment]
Added another file which we also retrieved via the cloudflare gateway (to see whether its cache might have longer timeouts): QmXqNvVwR4hhNmwotFkHAosXnsxV8M7AdzxePvg5fXvYX8

**Comment by chriseth** [comment]
The file that was also previously retrieved via cloudflare was available immediately (both on cloudflare and on the "official" gateway). The other file seems to be gone.

**Comment by chriseth** [comment]
File is still present.

**Comment by leonardoalt** [comment]
I guess we now have positive data towards IPFS?

**Comment by chriseth** [comment]
Looks like it...

**Comment by chriseth** [comment]
Still present.

**Comment by chriseth** [comment]
Will do the change in 0.6.0.

**Comment by chriseth** [comment]
Still present.
