### ISSUE TITLE
Remove mention of callstack depth

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5077]
Or updated it to the new 64/63 rule.

Search documentation for "1024".

**Comment by axic** [comment]
I don't think it should be removed since we support `evmVersion` and one can compile for an older chain. It should be just extended to explain the new rules too.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
