### ISSUE TITLE
ABI dispatcher security consideration

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#510]
The dispatcher parses the ABI signature and jumps to the specific tags, then the methods use `calldataload` again to load the specific arguments.  Would it make sense checking for the length of the supplied data with `calldatasize` that it meets the minimum required? Maybe when an optional keyword is used on the contract, like `safe`:

```
safe contract Test {
}
```

In the case of fixed-length types that is a constant number. In the case of dynamic arguments, that would be the minimum length it would take.

**Comment by chriseth** [comment]
Solidity currently works under the assumption that you can shorten the call data if ends in zeros.

**Comment by axic** [comment]
How about `strictabi` or `strictcall` instead of `safe`?

Perhaps it would be placed after the contract name:

```
contract Test strictabi {
}
```

**Comment by chriseth** [comment]
Please explain how this is a security problem. The ABI is defined with the assumption that trailing zeros are ignored or can be omitted. This creates a "malleability" risk when using `msg.data`. On the other hard, `msg.data` provides low-level access and we also have this malleability risk when using non-32-byte-types.
