### ISSUE TITLE
Yul: Investigate potential memory-management optimizations and types

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5107]
Related: https://github.com/ethereum/solidity/issues/4033

@Arachnid recently observed that in `function f(bytes32 a)`, the expression `keccak256(abi.encode(a, a))` is much more expensive than the old `keccak256(a, a)`. We should improve the optimizer to reduce both cases to the same code, which should roughly be `mstore(0, a) mstore(0x20, a) let result := keccak256(0, 0x40)`.

The problem is that `abi.encode` always returns a `bytes`, which has an address in memory and a stored length.  The optimizer should be able to reason about the lifetime of memory objects and all memory operations should be relative to memory ranges which can be moved around by the optimizer.

For that to work, there needs to be an IR-level `allocate` function and every memory access needs to provide the "handle" of the memory object it wants to access. So `abi.encode`, `keccak256` and the function `f` itself should be implemented roughly as follows:

```
function abi_encode_bytes32_bytes32(a, b) -> v {
  v := allocate(0x60)
  mobj_store(v, 0x00, 0x60)
  mobj_store(v, 0x20, a)
  mobj_store(v, 0x40, b)
}
function keccak256_bytes(v) -> h {
  let len := mobj_load(v, 0x00)
  h := mobj_keccak256(v, 0x20, len)
}
function f(a) -> h {
  h := keccak256_bytes(abi_encode_bytes32_bytes32(a, a))
}
```

Since the memory object is passed around in functions, we currently cannot improve that, but of course the optimizer would inline the two function calls as follows:
```
function f(a) -> h {
  let v := allocate(0x60)
  mobj_store(v, 0x00, 0x60)
  mobj_store(v, 0x20, a)
  mobj_store(v, 0x40, b)
  let len := mobj_load(v, 0x00)
  h := mobj_keccak256(v, 0x20, len)
}
```

The combination of `mobj_store(v, 0x00, 0x60)` and `let len := mobj_load(v, 0x00)` can of course be optimized to replace `len` by `0x60`:

```
function f(a) -> h {
  let v := allocate(0x60)
  mobj_store(v, 0x00, 0x60)
  mobj_store(v, 0x20, a)
  mobj_store(v, 0x40, b)
  h := mobj_keccak256(v, 0x20, 0x60)
}
```

And in this code snippet, we can now derive the following facts:

 - `v` is allocated only temporarily, so the "free memory pointer" can be reset at the end of the function
 - since the value written at `v[0]` is never read, and the allocation of `v` is temporary, it does not have to be written
 - this reduces the size of the allocated area and thus the code can be simplified to the following:

```
function f(a) -> h {
  let v := allocate(0x40)
  mobj_store(v, 0x00, a)
  mobj_store(v, 0x20, b)
  h := mobj_keccak256(v, 0x00, 0x40)
}
```

Furthermore:

 - a temporary allocation of 64 bytes can be moved to the scratch space (we might also think about providing additional fixed-size scratch space at other places in the future)

and thus:
```
function f(a) -> h {
  let v := scratch(0x40)
  mobj_store(v, 0x00, a)
  mobj_store(v, 0x20, b)
  h := mobj_keccak256(v, 0x00, 0x40)
}
```

If after memory management optimizations, the `mobj_store` and `allocate` calls are resolved, we end up with the following:
```
function f(a) -> h {
  mstore(0x00, a)
  mstore(0x20, b)
  h := keccak256(0x00, 0x40)
}
```

---

Some routines need memory but cannot provide an upper bound at the point of allocation. The dynamic abi encoding functions are examples. For these, there could be the function `allocateUnbounded()`, which returns a memory object (a first implementation could just return the free memory pointer). There is a corresponding `releaseUnbounded()` function and the following property has to be fulfilled for all valid programs: Any control flow that starts from a point that calls `allocateUnbounded()` will first encounter a terminating builtin or a call to `releaseUnbounded()` before it encounters any other allocation call.

**Comment by chriseth** [comment]
Tasks: formalize this :)

**Comment by liangdzou** [comment]
Sounds interesting, will have a try :-)

**Comment by liangdzou** [comment]
Example:
```
  1 contract C {                                                                                                                                                                                              
  2   function f(bytes32 a) public pure {                                           
  3     keccak256(abi.encode(a, a));                                                
  4   }                                                                             
  5 }
```

Generated code:
```
110     tag_6:                                                                                                                                                                                                
111         /* "t.sol":74:75  a */                                                  
112       dup1                                                                      
113         /* "t.sol":77:78  a */                                                  
114       dup2                                                                      
115         /* "t.sol":63:79  abi.encode(a, a) */                                   
116       add(0x20, mload(0x40))                                                    
117       dup1                                                                      
118       dup4                                                                      
119       dup2                                                                      
120       mstore                                                                    
121       0x20                                                                      
122       add                                                                       
123       dup3                                                                      
124       dup2                                                                      
125       mstore                                                                    
126       0x20                                                                      
127       add                                                                       
128       swap3                                                                     
129       pop                                                                       
130       pop                                                                       
131       pop                                                                       
132       mload(0x40)                                                               
133         /* "--CODEGEN--":49:53   */                                             
134       0x20                                                                      
135         /* "--CODEGEN--":39:46   */                                             
136       dup2                                                                      
137         /* "--CODEGEN--":30:37   */                                             
138       dup4                                                                      
139         /* "--CODEGEN--":26:47   */                                             
140       sub                                                                       
141         /* "--CODEGEN--":22:54   */                                             
142       sub                                                                       
143         /* "--CODEGEN--":13:20   */                                             
144       dup2                                                                      
145         /* "--CODEGEN--":6:55   */                                              
146       mstore                                                                    
147         /* "t.sol":63:79  abi.encode(a, a) */                                   
148       swap1                                                                     
149       0x40                                                                      
150       mstore                                                                    
151         /* "t.sol":53:80  keccak256(abi.encode(a, a)) */                        
152       dup1                                                                      
153       mload                                                                     
154       swap1                                                                     
155       0x20                                                                      
156       add                                                                       
157       keccak256                                                                 
158       pop                                                                       
159         /* "t.sol":15:84  function f(bytes32 a) public pure {... */             
160       pop                                                                       
161       jump  // out
```

The lines 111-150 calcuate abi.encode(a, a) and store it to memory, where the stack changed from "..., a" to "..., a, encode_loc".
The encoded result in memory has 0x60 bytes, and the content is "0x40, a, a".

The lines 152-157 calcualtes the keccak256(encode_loc + 0x20, 0x40)

Observations:
1. the encoded result is only used in function keccak256, therefore, we do not actually need to generate its presentation in memory.
2. the size for the encoded result 0x40 <= scratch size, therefore, we can directly use the scratch size without allocating memory and set the free memory pointer.

Question:
1. Can we do something specifically for the situation when encode appears as an argument of a low-level function (not only for keccak256)?
2. Is it better to avoid mstore at all for this case to operate directly in stack?

**Comment by ekpyron** [comment]
I vote for doing this and for prioritizing this!

**Comment by ekpyron** [comment]
@chriseth You mentioned that we might want to already use memory management functions e.g. in ``abi.encode`` and considered ``allocate_unknown`` and ``resize``, since the encoder doesn't know the length of the encoding in advance. However, I'm not sure whether it has to be more expensive to rewrite the encoder to first determine the length and to only write afterwards. Consider the following:

```
uint256 a = 42;
uint256[] memory b = new uint256[](32);
uint256[] memory c = new uint256[](16);
uint256 d = 23;
abi.encode(a,b,c,d);
```

Now the current encoder would implement ``abi.encode`` here (conceptually and very roughly) like:
```
function encode_now(headStart, a, b_ptr, c_ptr, d) -> tail {
    let sizeofHead := mul(4, 32)
    tail := add(headStart, size_of_current_head)

    mstore(headStart, a)

    mstore(add(headStart, 32), sub(tail, headStart))
    tail := encode_dyn_now(b_ptr, tail)

    mstore(add(headStart, 64), sub(tail, headStart))
    tail := encode_dyn_now(c_ptr, tail)

    mstore(headStart, d)
}
function encode_dyn_now(ptr, tail) -> newTail {
    let length := read_length(ptr)
    newTail := add(tail, add(length, 0x20))
    mstore(tail, length)
    copy(ptr, add(tail, 0x20), length)
}
```

However, we could also do the following instead:
```
function encode_new(a, b_ptr, c_ptr, d) -> result {
  let offset_a := 0
  let length_a := 32
  {
    let offset_b := add(offset_a, length_a)
    let length_b := add(read_length(b_ptr), 32)

    {
      let offset_c := add(offset_b, length_b)
      let num_elems_c := read_length(c_ptr)
      let length_c := add(num_elems_c, 32)

      {
        let offset_d := add(offset_c, length_c)
        let length_d := 32

        {
          let length := add(offset_d, length_d)
          result := allocate(length)
          // actually, not sure how result would be handled stack-wise
          // but theoretically it's no problem at the end of every scope
          // to swap it behind every slot that's no longer used and
          // then pop all those slots and still have result reachable in the end
        }

        // problem: stack is getting deep - d might not be accessible here
        mobj_store(result, offset_d, d)
      }

      mobj_store(result, offset_c, num_elems_c)
      encode_dyn_new(result, add(offset_c, 32), add(c_ptr, 32), num_elems_c)
    }
    mobj_store(result, offset_b, num_elems_b)
    encode_dyn_new(result, add(offset_b, 32), add(b_ptr, 32), num_elems_b)
  }
}
function encode_dyn_new(result, offset, ptr, length)
{
  copy_mobj(ptr, result, offset, length)
}
```
I haven't yet written a complete example with the two different modes and checked what the optimizer would make of it, but my guess is that the latter way of doing things is not inherently more expensive than the former - the main issue is again stack depth (the large number of locals is not necessarily a problem, since they have good lifetime and access behaviour as indicated by the scopes, but the last argument needs to be accessible at the place with the comment above). The number of locals can be further reduced in the example case above and there might be a way to tweak it to be equally good as the current version.

When I get around to, I'll write up compilable versions of the above and compare how the current optimizer deals with them.

**Comment by ekpyron** [comment]
@chriseth noted that my suggestion probably won't work for dynamically sized arrays with dynamically sized base pointers and I tend to agree now (so I'm minimizing above comment).

**Comment by chriseth** [comment]
In a global analysis step, the line `let v := allocate(x)` can be changed to `let v := 0x40` (the free memory pointer) if
 - `v` is not passed to any function except the builtin memory read/write functions and only as the memory object
 - `v` is not used anywhere else (not assigned to, not assigned from, etc).
 - `v` is not a return variable.
 - The function `allocate` nor any user-defined function that calls it is called after `let v := allocate(x)` until `v` goes out of scope.

**Comment by chriseth** [comment]
In a global analysis step, a function `function f(...) -> ... { ... }` can be changed to `function f(...) -> ... { let t := mload(0x40) ... mstore(0x40, t) }` if the following conditions are met:
 - all functions called from `f` meet these conditions
 - the return values of the `allocate` function called in `f`'s body are not stored in memory or storage and are not returned.

(this might be relaxed a little)

**Comment by chriseth** [comment]
Let's start with by adding and using the functions in the yul code generator, ignoring range checks for now.

**Comment by ekpyron** [comment]
More details for the proposed first steps:

Step 1:
---------
Introduce the following Yul util functions, use them in Yul IR generation and the ABI encoder code, and eliminate all acesses of the free memory pointer this way:
  - ``mobj_allocate(size) -> mobj`` - allocates ``size`` bytes by reading from and updating the free memory pointer
  - ``mobj_allocate_unbounded() -> mobj_unbounded`` - just returns the current position of the free memory pointer
  - ``mobj_finalize(mobj_unbounded, size) -> mobj`` - makes a previously unbounded memory object persistent, i.e. write ``add(mobj_unbounded, size)`` (rounded up) to the free memory pointer
  - ``mobj_discard(mobj_unbounded)`` - discards a previously allocated memory object; does nothing (mainly to be used after ``mobj_allocate_unbounded()``, in case the unbounded memory was temporary and is discarded - but we should also try to use it after all allocations; later we can decide, if we really need it or remove it again and rely on static analysis instead; doesn't hurt to have it, the optimizer will remove it anyways).

Step 2:
----------
Introduce the following further Yul util functions:
  - ``mobj_load(mobj, offset) -> value`` - load from memory object. Initially without bounds checks.
  - ``mobj_store(mobj, offset, value)`` - store to memory object. Initially without bounds checks.
  - ``get_scratch_space() -> mobj`` - returns ``0``, used whenever we write to memory offset 0 as scratch space

Try to replace all ``mload``s and ``mstore``s with ``mobj_load`` and ``mobj_store``.
Check how we pass memory offsets to builtins. Potentially define functions like ``keccak_mobj(mobj, offset, size)`` and use them.

At that point we can re-evaluate where we stand and what our usage requirements look like. Next step would be to make memory objects a proper type and promote the functions to builtins - but we need to check how we will be dealing with the length of the object and how we pass memory to things like ``keccak`` or ``call``.
There were some random further notes here: https://hackmd.io/qFJ9LOweQf6QS1_BjIr0rQ
