### ISSUE TITLE
Feature to make fallback cheaper

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#511]
Currently the gas cost of the fallback method depends on the number of methods in the contract. The more methods to check for (i.e. compare the signature against), the more it costs until the fallback is executed.

It could be useful to make the fallback cheaper. Two naive implementation ideas:
a) As the first thing in the dispatcher, if `calldatasize = 0`, then jump to the fallback. Optionally introduce a modifier keyword for this in the contract?

b) Introduce a pre-dispatch method in a contract, which if present, would be executed prior anything else. This gives a lot of flexibility, but also allows a dev to introduce problems.

**Comment by chriseth** [comment]
Version a is already in place.

**Comment by axic** [comment]
I might have used an older version, which didn't do it, albeit tried really old ones now, and all of them seem to use it.

Perhaps I had a weird combination or a compiler error when it was omitted - I do recall having a compiled version lacking `CALLDATASIZE`. Unfortunately haven't got the code to trigger that.
