### ISSUE TITLE
Internal compiler error for call to unimplemented "super" function

### ISSUE THREAD

**Issue by nweller** [ethereum/solidity#5130]
The following contract produces an internal compiler error in various solc versions, including the most recent build in Remix:

    contract a {
        function f() public;
    }
    contract b is a {
        function f() public { super.f(); }
    }

It does compile (but cannot be deployed due to the missing implementation) if I rename a.f().

(This report is part of an ICE Center@ETH Zurich project on automated compiler validation funded by the Ethereum Foundation.)

**Comment by axic** [comment]
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/ContractCompiler.cpp(893): Throw in function void dev::solidity::ContractCompiler::appendModifierOrFunctionCode()
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

**Comment by chriseth** [comment]
What do you mean by "rename a.f()"? Can you post the full changed contract that does compile, please?

**Comment by nweller** [comment]
Sure - I meant that this compiles:

    contract a {
        function f2() public;
    }
    contract b is a {
        function f() public { super.f2(); }  
    }

This just shows that there's apparently some significance to having an implementation of the function in the sub class for the error to occur.

**Comment by chriseth** [comment]
Great, thanks!

**Comment by anurag-git** [comment]
@chriseth , would like to take up this issue. Let me know the strategy to proceed. I hope it is not too tricky.

**Comment by chriseth** [comment]
It might work to just ignore functions that do not have implementations in `ContractType::nativeMembers`.

**Comment by anurag-git** [comment]
@chriseth, Did some analysis, let me know your thoughts
```

contract a {
    function f() public;
}
contract b is a {
   // function f() public { super.f(); }
    function f() public {uint i=0; uint j; j=i;}
}
```
This code compiles after changing the contract as above.  As per the issue  we are trying to call base contract function (which is not implemented) in derived contract, hence the error. Error seems to be expected as per my understanding. 

Below code also **compiles**,
```

contract a {
    //function f() public;
    function f() pure public {
       uint i=0; uint j; j=i;
    }
}
contract b is a {
    function f() pure public { super.f(); }
    //function f() public { super.f(); }
}
```

which basically says that if base contract function is implemented things work fine.

So do we consider this (calling unimplemented base contract function) as valid?  If so, then I can proceed with my analysis to fix this issue.

**Comment by chriseth** [comment]
The initial code should result in an error stating something like `super.f()` is not available.

**Comment by anurag-git** [comment]
@chriseth, I have a solution ready, please help me to write test case so that I can push both changes at once.

**Comment by chriseth** [comment]
@anurag-git the initial code is a good test case. Put it in the `syntaxTests` directory and run `isoltest`. Use the `update` option if it prompts you for an action.

**Comment by dddejan** [comment]
If the `super` is changed to `a` in the original example, the compiler still fails with internal error.

```solidity
contract a {
    function f() public;
}
contract b is a {
    function f() public { a.f(); }
}
```

**Comment by chriseth** [comment]
The issue in the latest comment is tracked in https://github.com/ethereum/solidity/issues/7314
