### ISSUE TITLE
Compilation error in unreachable code

### ISSUE THREAD

**Issue by pieterhartel** [ethereum/solidity#5133]
solc 0.4.24+commit.e67f0147.Darwin.appleclang fails to compile a verified smart contract, such as for example https://etherscan.io/address/0x984f98cbba75b190904d8fca786c26690d1ebc30#code

The problem is that the compiler throws a divide by zero error in the function payOwners (pasted below). But if COMMISSION == 0, the division by 0 will never happen.

--pieter

```
function payOwners() private canPayOwners {
    if (COMMISSION == 0) {
      ownersPayed = true;
      ownerPayout = 0;
      if (numberOfBets[winningOption] > 0) {
        collectionFees = ((oraclizeFees != 0) ? (oraclizeFees / numberOfBets[winningOption] + 1) : 0); 
      }
      return;
    }
    uint losingChunk = totalAmountsBet[1 - winningOption];
    ownerPayout = (losingChunk - oraclizeFees) / COMMISSION; 
```

**Comment by chriseth** [comment]
`COMMISION` is a `constant` that is permanently set to zero. If at all, the error should be that the `else` part is unreachable (which we do not yet detect). I don't think that constants should be used as "parameters" for contracts.

**Comment by chriseth** [comment]
Closing in favour of https://github.com/ethereum/solidity/issues/2340
