### ISSUE TITLE
Source mappings do not point to the correct location

### ISSUE THREAD

**Issue by kaisert** [ethereum/solidity#5135]
## Description

The source mappings gained through `solc --combined-json srcmap-runtime` does not always give the correct translation from instruction offset to source code. 

## Environment

- Compiler version: tested with 0.4.25, 0.4.24, 0.4.11, 0.4.18
- Framework/IDE (e.g. Truffle or Remix): tested locally and on remix
- Operating system: linux

## Steps to Reproduce
Minimal example:
```
contract c {
    int[] a;
    function f() public {
        a.length = 1;
    } 
}
```
When checking to which source code offset the SSTORE instructions correspond to, the source mapping indicates the beginning of the contract. Expected would be `a.length = 1`.

**Comment by chriseth** [comment]
Are you talking about the `8:9:-1` part? Note the `-1` at the end which indicates "unknown file". The reason behind this is that the source for storing the number is an assembly library routine of the compiler whose code is not part of the initial source code.

**Comment by kaisert** [comment]
So when compiling the given example, the complete source mapping is 
```
0:82:0:-;;;;;;;;;;;;;;;;;;;;;;;;30:49;;8:9:-1;5:2;;;30:1;27;20:12;5:2;30:49:0;;;;;;;71:1;60;:12;;;;;:::i;:::-;;30:49::o;0:82::-;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::i;:::-;;;;;:::o;:::-;;;;;;;;;;;;;;;;;;;;;;;;;;;:::o
```

. I am talking about the `0:82::-` part, which points to the given source file (due to `30:49:0` a few entries before)

**Comment by chriseth** [comment]
Ah right, that's a different helper routine, the "array resize routine". Since it can be used from multiple points, the closest source map that can be provided is the whole file.

@yann300 can you give some insights into source map cleanup / filtering that is done in remix for the break points?

**Comment by kaisert** [comment]
So what is the difference between these two helper functions? Or in other words: Why is the first one deemed to be in an unknown file, while the second one references the whole file?

**Comment by chriseth** [comment]
The first one is built using yul, the other one uses the old style code generator. The difference is that yul actually is source code, while the second is just a sequence of opcodes.
