### ISSUE TITLE
Disable codecov on pull requests or fix it

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5143]
codecov produces invalid reports and thus is generally not helpful on pull requests. We should disable it to reduce clutter.

**Comment by lazaridiscom** [comment]
related #4582

(getting again and again pinged by a codecov bot... well! )

**Comment by axic** [comment]
I think this was fixed? Please reopen if not.

**Comment by chriseth** [comment]
The reports are still not useful (the deltas are wrong).
