### ISSUE TITLE
Add optimizer rule that performs `exp(x, k) -> mul(mul(...mul(x, x), ...), x)` if cheaper

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5158]

**Comment by ghallak** [comment]
The cost of the function call is determined by passing it to `CodeCost::codeCost`, isn't that right?

Also, should this work only when the function's arguments are literals (e.g. `exp(2, 3)`)? Or should it work for all expressions including identifiers (e.g. `exp(a, b)`) and function calls (e.g. `exp(a, add(2, b))`)?

**Comment by chriseth** [comment]
The second argument should be a literal, the first can be anything (but should be a variable in yul).

**Comment by frangio** [comment]
`exp(x, k)` costs 60 gas for k < 256.

For k < 9 it is more expensive than using `dup` and `mul` and the compiler should be optimizing it.
