### ISSUE TITLE
Documentation: Clean up main page

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5162]
As suggested by the zeppelin audit, the main page should not contain external links but rather be a landing page that contains the TOC and other things.

Quoting: Consider moving all these links to an independent section, leaving on the main page only the introduction, the links to translations and the description of the next sections, to better guide newcomers into a recommended reading sequence.

**Comment by ChrisChinchilla** [comment]
@chriseth Actually, I had the same thought myself, so will handle :)
