### ISSUE TITLE
Add gas usage tests

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5165]
Especially when we are adding the new backend, gas usage tests should be added to the compiler so that we notice when the gas requirements of certain typical contracts increase through change is the code generator.

**Comment by leonardoalt** [comment]
We have GasTests, which also consider yul and the optimizer.

**Comment by chriseth** [comment]
These are just for the ABI. We should extend them.

**Comment by axic** [comment]
Could be easily done after #10474.

**Comment by axic** [comment]
Fixed by #10474.
