### ISSUE TITLE
Improve "running the tests" section

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5166]
From the zeppelin audit:

 - Make sure that the “Running the compiler tests” guide works on all supported platforms, and state which platforms are supported.
 - Clearly define what output is expected for a 100% successful run of the test suite.
 - ~Provide more information about the particular cpp-ethereum version required for the tests~.

**Comment by ChrisChinchilla** [comment]
@chriseth I already made a start on this, so happy to continue with this feedback.

**Comment by leonardoalt** [comment]
What's missing for this?

**Comment by ChrisChinchilla** [comment]
@leonardoalt Just about to make a PR :)
