### ISSUE TITLE
Some code cleanup

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5168]
From the zeppelin audit:

Some suggestions. This is not mandatory, only perform the changes where it makes sense.

- [x] Use `= default` to define a trivial default constructor.
  - No default c'tors were found in the code
- [x] Use `ClassName x{constrArg}` instead of `ClassName x = ClassName(constrArg)` 
  - After some discussion we decided to make this more a policy for new code and for "fix it when you see it"
- [x] use `emplace_back` instead of `push_back` where it makes sense #5619
-------------
- [x] replace all `NULL` by `nullptr` (not in imported code, but in `Token.h`) #5492`
 - [x] use `empty()` instead of `size() == 0`
 - [ ] Use the same name for all parameters in the declaration and implementation.
 - [x] Use cctype instead of deprecated C++ header `ctype.h`.
 - [x] Use cstdio instead of deprecated C++ header `stdio.h`.
 - [x] When a function is declared with an `override` remove the redundant `virtual`.
 - [ ] Avoid using `static` inside anonymous namespaces, because namespace limits the visibility of definitions to a single translation unit.
 - [x] Use finds with a single character string literals when possible (for example, ‘\n’ instead of “\n”).
 - [ ] Use const references to loop variables that are copied but only used as const references
 - [ ] If a variable is copy-constructed (auto) from a const reference, use `const &`
 - [ ] Remove `std::move` on const and trivially-copyable types.

**Comment by axic** [comment]
>  replace all NULL by nullptr (not in imported code, but in Token.h)

Actually the `NULL` is only used in external C APIs (when using `compileStandard`) and in `Token.h`. I am not convinced these need to be changed.

>  Use finds with a single character string literals when possible (for example, ‘\n’ instead of “\n”).

There seems to be a single instance of this.

**Comment by chriseth** [comment]
I think we could change Token.h to be more C++-like, perhaps even getting rid of the macros and rather doing it in the way it is done in the RuleList https://github.com/ethereum/solidity/blob/develop/libevmasm/RuleList.h#L61

**Comment by chriseth** [comment]
Removing the macro in Token.h would help IDEs properly recognizing the token identifiers.

**Comment by axic** [comment]
> Avoid using static inside anonymous namespaces, because namespace limits the visibility of definitions to a single translation unit.

The single example I could find is in `libsolc` for `static string s_outputBuffer`. Outside of that the CLI code is using it, but it isn't using anonymous namespaces.

**Comment by Mordax** [comment]
Interested in tackling some of these, if that's cool.
