### ISSUE TITLE
strange behaviour connected with pushing uninitialized structure into array

### ISSUE THREAD

**Issue by unegare** [ethereum/solidity#5176]
Solidity version: version:0.4.25+commit.59dbf8f1.Emscripten.clang
env: remix.ethereum.org

```
pragma solidity ^0.4.21;

contract test3 {
struct data {
uint a;
uint b;
}

data[] public arr;

data public globd1;
data public globd2;

function A() public {
data storage d;
globd1 = d;
arr.push(d);
globd2 = arr[arr.length -1];
}

function B() public view returns (uint) {
return arr.length;
}
}
```

for example it was deployed in ropsten at 0xBc9808849940eab12225BD936A4f6eA517c1f00b

Problem: globd1 != globd2, it is true for the pushed element into array.
actually globd1 = (0,0), but globd2 = (arr.length, 0), element in array IS NOT ZERO, but pushed structure was zero;

It seems like a bug, doesn't it ?

**Comment by chriseth** [comment]
Please take a look at the warning from the compiler. This will be an error starting from Solidity 0.5.0.
