### ISSUE TITLE
Yul: Grammar Inconsistent With Given Example

### ISSUE THREAD

**Issue by kyconny** [ethereum/solidity#5194]
## Description

The grammar given in [yul.rst](https://github.com/ethereum/solidity/blob/develop/docs/yul.rst) defines
`Block = '{' Statement* '}'`
`Default = 'default' Block`

However the example code given uses the notation:
`default: { blah }`
notice the presence of the colon that isn't in the grammar.

Either the grammar should change to reflect the example, or the example to reflect the grammar as they are incompatible.

**Comment by chriseth** [comment]
Thanks! Will fix shortly.
