### ISSUE TITLE
Verify target address prior to call

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#520]
For example, running the below in a VM, where Oraclize doesn't exist:

```
import "https://github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract A is usingOraclize {
    function a() returns (uint) {
        return oraclize.getPrice("URL");
    }
}
```

will result in:

```
Result: “0x524f388900000000000000000000000000000000000000000000000000000000”
```

It seems like the method signature stays there.   Probably related to https://github.com/ethereum/solidity/issues/517.

IIRC `call` returns the execution status on the stack, that could be checked.  Perhaps the best option is to clear the return memory area and return 0 only.

Possible future improvement could be a new keyword, such as `safe`, which throws if call failed, i.e.:

```
oraclize.getPrice.safe("URL");
```

would throw if the call failed.

Additionally, safe-mode could also do an `extcodesize` check to verify the existence of the code upfront. Safe-mode is more expensive, but safe 🔒

**Comment by axic** [comment]
Note, some return types will hide this issue. For example `address` will mask the lower 160 bits and effectively show 0.

**Comment by chriseth** [comment]
This is a more general issue: There is no way to tell whether the target contract supports a specific interface (and even if it did, it could cheat). So you should never trust the return values of a contract you do not trust.
So I don't think we should add some kind of 'safe' calling because it would be grossly misleading.

**Comment by axic** [comment]
Probably the name `safe` is misleading and should be something else. I'm not trying to ensure that the called method is what it should be. The goal would be to `throw` in the caller if:
- a) if the callee address has no contract
- b) the callee method throws/OOG happens (e.g. execution error)

**Comment by chriseth** [comment]
Point b is already the case, we can add a if desired.

**Comment by holiman** [comment]
So what are the possible solutions to this problem? 
- Check codesize of callee before `call` ? 
- Don't reuse `mem_in`, but instead a zeroed-out area? 

Anything else ?

**Comment by holiman** [comment]
I'd be in favour of adding something that syntactically looked like this: 
`oraclize.checkExists().getPrice.safe("URL");` i.e having a `checkExists()` on `address` which returns the `address` if there's any code there.

**Comment by holiman** [comment]
Though, this being an edge-case, I think most developers would miss that option anyway.

**Comment by axic** [comment]
@holiman I think it would better using empty memory locations by default, and maybe having an _unsafe_ mode, which turns that off for those who want to save gas.

**Comment by Arachnid** [comment]
> Additionally, safe-mode could also do an extcodesize check to verify the existence of the code upfront.

I think this is a bad idea; knowing code is there doesn't mean the code does what you want. Checking the response length is a better idea. (Edit: But sadly not possible)

**Comment by axic** [comment]
I don't think these are mutually exclusive, they address a different situation.

**Comment by holiman** [comment]
Checking response length? How? The EVM does not provide that, iirc.
