### ISSUE TITLE
Withdrawal pattern clarification

### ISSUE THREAD

**Issue by jabreght** [ethereum/solidity#5200]
## Description

https://solidity.readthedocs.io/en/v0.4.25/common-patterns.html#withdrawal-pattern
In this description I believe you should change the wording for how the game/contract works. I think there is an issue with the current wording. 
      _"In the following contract, if you are usurped as the richest, you will receive the funds of the person 
      who has gone on to become the new richest."_
The wording makes it seem like you receive the money of the richest person as if you are stealing their money. It should reflect that you are receiving the fee(compensation) they paid to become the richest person over you.

This could just be me, but I had to read the kingofethers page to understand what was meant. Just a suggestion 😄

**Comment by chriseth** [comment]
I think the wording can be improved, but you actually get the full amount, not just the fee. What might not be too clear is that once you send money to the contract, the money is gone. Do you have a suggestion about how to improve it?

**Comment by jabreght** [comment]
Oh sorry, I just referred to what the new king payed as being the fee. But yes they would receive all of the money. 

I think stating that "User A starts the game by paying the starting amount to take control of the throne. User B pays to take control of the throne from user A. The funds paid by user B are sent to user A as compensation for having the throne stolen from them."

I believe something along those lines would work.

Edit: Fixed due to @redsquirrel catching the error.

**Comment by redsquirrel** [comment]
“thrown” ~> “throne”

**Comment by jabreght** [comment]
@redsquirrel 
My apologies, and thank you. I spelled the first occurrences correctly, but not the last one oddly enough 😄.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
