### ISSUE TITLE
Investigate staticcall/delegatecall trampoline

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5201]
View library functions are currently called using delegatecall, because there is no delegatecall+staticcall combination. It could be possible to call the current contract using staticcall with a special signature which then forwards to the actual library using deleatecall.

Things to investigate:

 - how much more gas will it cost?
 - which identifier can be used such that there will be no clash with existing function identifiers?

**Comment by Rotemy** [comment]
4 years and nothing? this is needed
