### ISSUE TITLE
Diagram of the Compiler

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5202]
We should create a diagram of the various stages of the compiler and which information is present at which stage and which files are mostly relevant to the various stages.

#### Parser

Source code

 - Scanner

Token stream

 - Parser

non-annotated AST

### Analysis

 - Syntax Checker
 - Docstring analyzer
 - declaration registration
 - imports
 - name and type resolution
 - type checking (first outside code, then inside code)

fully annotated AST

 - post type checker
 - control flow graph
 - static analyzer
 - view pure checker
 - smt checker

### Code generation

 - dependencies
 - creation / runtime
 - missing functions
 - expression compiler

### Optimizer

**Comment by ChrisChinchilla** [comment]
@chriseth I wouldn't mind dusting off my wacom tablet for this :)

**Comment by chriseth** [comment]
As long as the tablet runs proper tools like inkscape... :)

**Comment by chriseth** [comment]
I fear that you need quite some insight into the compiler code, though.

**Comment by chriseth** [comment]
Perhaps you can create a preliminary svg and then we can adjust?

**Comment by christianparpart** [comment]
@ChrisChinchilla depending on *when* you wanna do that, I'd like to scratch the technical part, and then you could make it look nice. I'm on other tickets for the time being though.

**Comment by ChrisChinchilla** [comment]
@chriseth Well…

@christianparpart this is in the 0.5.1 project, so there's no rush. I'm happy to work with you on this :)

**Comment by axic** [comment]
Related #4278.
