### ISSUE TITLE
contract state variable don't print as expected when invoke from another contract

### ISSUE THREAD

**Issue by code-brewer** [ethereum/solidity#5210]
## Description
Contract A has a state variable `owner` , which initialized well to msg.sender .
But this `owner` variable became 0x0 when invoke from another contract function which take address of contract A's instance and convert to A type.

## Environment

- Compiler version: 0.4.25
- Framework/IDE:  Remix
- EVM execution environment :  
    Check 'Auto compile ' and  'Enable Optimization' on Compile tab of Remix IDE;
    Choose 'Javascript vm' on Run tab of Remix IDE;
  
 
## Steps to Reproduce: step is descript among the code comment.

```
pragma solidity 0.4.25;

contract A{ 
         
   address public owner;
 
   event Ret(string flag, address sender, address owner);
      event ConstrutEvt(string flag,  address owner );
      
   function A() public{
       owner = msg.sender;
       emit ConstrutEvt("A", msg.sender);
   }
  
   function doSomething()  public view returns(string flag, address sender, address owner){
            emit Ret("A::doSomething", msg.sender, owner);
            return ("A::doSomething", msg.sender, owner);
   }
}

contract EvilDoer{
// step1:  deploy contract A on remix IDE. 
// and the log show `owner` is a valid address value.

// step2:  deploy contract EvilDoer.

// step3:  on remix IDE run tab, invoke doSomething() use the contract A address as argument. 
// This time the log show that 'owner' is zero. Why ?

    function doSomethingEvil(address instanceAddrOfA) public {
         A contractA = A(instanceAddrOfA);
         contractA.doSomething();  
    }    
}
```

**Comment by chriseth** [comment]
Please do not blindly ignore compiler warnings. The reason for the behaviour is that `owner` is shadowed, as explained in the compiler warnings.
