### ISSUE TITLE
oss-fuzz integration

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5212]
Hello,

I was wondering if there has been a discussion in the past on fuzzing solidity continously with free OSS fuzzing services such as oss-fuzz?

P.S. I tried to compile solidity on Ubuntu 16.04 against clang-8 (latest) but ran into linking errors that I gather is mostly due to ABI updates in libstdc++ (namespaces for commonly used objects such as std::basic_string seem to have changed) that clang++ (the linker) is not able to understand.

Thank you.

**Comment by erak** [comment]
@bshastry We're mainly utilizing AFL (http://lcamtuf.coredump.cx/afl/) for fuzzing. There's also a section in the documentation that explains how to run it: https://solidity.readthedocs.io/en/develop/contributing.html?highlight=solfuzzer#running-the-fuzzer-via-afl.

Could you provide more details about your setup (compiler and library versions, as well as the output)? As far as I can tell, Ubuntu currently ships with Clang 6.0.

**Comment by chriseth** [comment]
Would be happy to see such an integration, but please note that compiler fuzzing will not be able to find any critical issues. It is only able to improve the error reporting functionalities. In the best case, it can find memory issues like null pointer dereferences.

**Comment by bshastry** [comment]
> @bshastry We're mainly utilizing AFL (http://lcamtuf.coredump.cx/afl/) for fuzzing. There's also a section in the documentation that explains how to run it: https://solidity.readthedocs.io/en/develop/contributing.html?highlight=solfuzzer#running-the-fuzzer-via-afl.

Thanks, support for afl-fuzz is definitely a good start. However, a project like solidity can benefit greatly from oss-fuzz for the following reasons:
  - access to multiple fuzzing engines including afl-fuzz
  - trigger on every build
  - automatic issue triage and notification to devs
 
> Could you provide more details about your setup (compiler and library versions, as well as the output)? As far as I can tell, Ubuntu currently ships with Clang 6.0.

The main linking issues that I see at the moment (after having built boost lib dependencies from scratch) are:

```
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const'
undefined reference to 'std::__throw_length_error(char const*)'
undefined reference to 'std::__throw_logic_error(char const*)'
undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
undefined reference to 'std::codecvt<wchar_t, char, __mbstate_t> const& std::use_facet<std::codecvt<wchar_t, char, __mbstate_t> >(std::locale const&)'
undefined reference to 'std::locale::locale(char const*)'
undefined reference to 'std::locale::locale(std::locale const&)'
undefined reference to 'std::locale::operator=(std::locale const&)'
undefined reference to 'std::locale::~locale()'
undefined reference to 'std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

Edit 1:
Compiler: clang
Version: 8
libraries: libboost from upstream master, libc++ and libc++abi from clang/llvm distribution (v8)

Edit 2:
~~The linking errors disappeared magically when I replaced system cmake v3.5 with the latest release.~~
I believer these linking errors happen at the time of linking `lllc`, the lll compiler. All of them stem from the libboost_filesystem library that has been custom built.

**Comment by bshastry** [comment]
> Would be happy to see such an integration, but please note that compiler fuzzing will not be able to find any critical issues. It is only able to improve the error reporting functionalities. In the best case, it can find memory issues like null pointer dereferences.

Thank you for your input. The hope is that were the compiler be fuzzed with malformed solidity programs, assertion failures in the compiler process may be uncovered that may shed light on (compiler writer) assumptions. Of course, the fuzzing also helps uncover memory corruption issues which is also important imho e.g., malformed solidity contracts should not crash the compiler during compilation.
