### ISSUE TITLE
Turkish Docs translation

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#5216]
This issue is to track the progress of the Turkish translation of the Solidity documentation.

It includes the GitHub usernames of all involved, and links to any issues or pull requests related to the Turkish translation.

All translation efforts in progress from this date are pinned to commit 
https://github.com/ethereum/solidity/commit/b2b845d6def4d28215c5d591589555bd8f4ea6ab

## Contributors

Based on comments in pull requests and issues, and other conversations. If you also want to be involved, please comment below.

@altuntasfatih @cagataycali @mevlanaayas @msusur @onursabitsalman @denizozzgur

## Fork

https://github.com/Unichain-turkey/solidity
https://github.com/denizozzgur/Solidity_TR/

**Comment by chriseth** [comment]
Please use a more recent commit to pin to - optimally "today". We did lots of changes especially in those days.

**Comment by ChrisChinchilla** [comment]
@chriseth yeah, this was the one picked when this process started, but I will contact all translators and encourage them to update if they haven't got too far.

**Comment by ChrisChinchilla** [comment]
@altuntasfatih @cagataycali @mevlanaayas @msusur @onursabitsalman As this is a newer issue for you, I'll update the commit we recommend you fork from / rebase to.

**Comment by msusur** [comment]
Done! Cheers 🍺

**Comment by ChrisChinchilla** [comment]
@msusur A quick thought. Can you add the repository to a read the docs build so we can add a rendered link to the main solidity docs?

**Comment by franzihei** [comment]
We are currently working on a new, hopefully more structured workflow for the Solidity docs translations. I will ping you once this is ready. Closing this issue for now, you can track the progress of the new process etc. in issue #10119.
