### ISSUE TITLE
Yul: empty variable declaration propagation

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#5218]
We have empty variable declarations in Yul that are assigned at a later stage. Remove the empty variable instruction and rewrite the first assignment into a variable declaration.

### input:
```
let x
x := rhs
```

### expected output
```
let x := rhs
```

Note that this can only be done if the following conditions are met:
 - the first assignment and the declaration are statements in the same block
 - the variable is not referenced between the declaration and the assignment (including the value of the assignment itself, i.e. replacement cannot be done in the following situattion: `let x x := add(x, 1)`)

**Comment by chriseth** [comment]
Perhaps it might make sense to combine this step with https://github.com/ethereum/solidity/issues/4945 but perhaps not.
