### ISSUE TITLE
[cmake] put libyul code into its own static library

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#5219]
Put the Yul subsystem into its own designated static library.

**Comment by chriseth** [comment]
@christianparpart what is still to be done here?

**Comment by axic** [comment]
I'm closing this as libyul doesn't have a public API yet, so it cannot be considered fully independent. The closest to public API is in `libsolidity/interface/AssemblyStack`.

**Comment by chriseth** [comment]
I don't think it needs a public (read: stable) API to be an independent library.

**Comment by axic** [comment]
Making it into a static library only really makes a difference if it has a public API. It is already a separate library in the build system, with its dependencies duly listed.
