### ISSUE TITLE
Build in Windows

### ISSUE THREAD

**Issue by pipaman** [ethereum/solidity#523]
Hi,
I wanted to use solidity within geth in Windows 10. I tried the compiled version that comes with Ethereum 1.0 but it has an issue mentioned in this thread (https://forum.ethereum.org/discussion/3837/compiler-error-in-greeter-windows).
I'd like to get a new binary of a newer version with this issue fixed. As I didn't find it, I'm trying to compile it by myself but I found the following errors:
- If I compile it standalone, just downloading the package from here I get 'Unknown CMake command "eth_policy"'.
- If I try to compile solc (v 0.1.6) included in Ethereum 1.0 I get 'Cannot open include file: 'pthread.h': No such file or directory [C:\Users\pablo\Desktop\solc-build\webthree-umbrella\solidity\CMakeFiles\CMakeTmp\cmTC_24f2f.vcxproj]'

Any ideas?

Thanks!

**Comment by bobsummerwill** [comment]
Hey @pipaman,

The eth_policy issue might mean that you didn't git clone the webthree-umbrella with --recursive.

Please could you point me to the instructions you used?    We currently have some redundancy between the instructions at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/index.html and those at http://solidity.readthedocs.org/en/latest/installing-solidity.html#building-from-source (though those don't seem to include steps for Windows).

**Comment by pipaman** [comment]
Hi @bobsummerwill,

I did:

git clone --recursive https://github.com/ethereum/webthree-umbrella.git
cmake CMakeLists.txt

> > success

cd solidity
cmake CMakeLists.txt

> > error:   CheckIncludeFile.c
> > C:\Users...\Desktop\solc-build\T2\webthree-umbrella\solidity\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users...\Desktop\solc-build\T2\webthree-umbrella\solidity\CMakeFiles\CMakeTmp\cmTC_3c0e2.vcxproj]

**Comment by bobsummerwill** [comment]
Please could you follow the instructions here and report back?  Thanks!

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html

**Comment by pipaman** [comment]
I get the same error:

> CheckIncludeFile.c
> 
> C:\Users\pablo\Desktop\solc-build\T2\webthree-umbrella\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\pablo\Desktop\solc-build\T2\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_10f3d.vcxproj]
> 
> Done Building Project "C:\Users\pablo\Desktop\solc-build\T2\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_10f3d.vcxproj" (default targets) -- FAILED.
> 
> Build FAILED.

**Comment by bobsummerwill** [comment]
Please could you stick the full log into a gist.github.com file, @pipaman?   Thanks!

**Comment by pipaman** [comment]
You can see it here:
https://gist.github.com/pipaman/fb3560d7edfcad6bcccb357d9455224c

**Comment by bobsummerwill** [comment]
Thanks, and do you have a gist for the cmake run for the solution generation too, please?

**Comment by pipaman** [comment]
Here you are:
https://gist.github.com/pipaman/62c7f4e8fc2c5cef00c377a17355d767

**Comment by bobsummerwill** [comment]
Thanks, @pipaman.   What command-line were you executing for that cmake?

**Comment by pipaman** [comment]
I followed the instructions, this output is for command line:
`....webthree-umbrella\build>cmake ..`

**Comment by bobsummerwill** [comment]
Aha - so that is your problem.   That is doing a "default make" which won't work on Windows.

You need to do `cmake -G "Visual Studio 12 2013 Win64" ..` as per the instructions I sent a few comments back:  http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html

**Comment by pipaman** [comment]
I think the problem is that I have also VS 2015 and it was compiling with that version. Now, I installed VS extension and it works out of the box. Thanks.

**Comment by bobsummerwill** [comment]
Great!   Glad to hear it.
