### ISSUE TITLE
Cant validate this contract in etherscan

### ISSUE THREAD

**Issue by rotcivegaf** [ethereum/solidity#5234]
I have this code:
`contract Foo { function foo(bytes4) public {} }`
I deploy this contract using remix in ropsten net with version:0.4.25+commit.59dbf8f1.Emscripten.clang and enable optimization with runs: 200
[0xed1dd9b9684d52010bd59dd5ece841f5ce23ad29](https://ropsten.etherscan.io/address/0xed1dd9b9684d52010bd59dd5ece841f5ce23ad29)
But when i try verify in etherscan i cant:

```
ByteCode (what we are looking for):
0x608060405234801561001057600080fd5b5060a88061001f6000396000f300608060405260043610603e5763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663580526ee81146043575b600080fd5b348015604e57600080fd5b5060777bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19600435166079565b005b505600{bzzr}
```
VS
```
Your Compiled Bytecode + Constructor Argument if any (what you provided):
0x608060405234801561001057600080fd5b5060ab8061001f6000396000f300608060405260043610603e5763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663580526ee81146043575b600080fd5b348015604e57600080fd5b50607a7fffffffff0000000000000000000000000000000000000000000000000000000060043516607c565b005b505600{bzzr}
```
Note: If i not use the optimization the verify works
Operating system: Ubuntu 18.04.1 LTS

**Comment by chriseth** [comment]
I tried to compile it, too, and it seems that that the difference in bytecode can be achieved by using a different value for the "runs" parameter of the optimizer. Could that be the reason?

**Comment by rotcivegaf** [comment]
The "runs" parameter is 200, now in truffle i get this bytecode:
```608060405234801561001057600080fd5b5060a88061001f6000396000f300608060405260043610603e5763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663580526ee81146043575b600080fd5b348015604e57600080fd5b5060777bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19600435166079565b005b505600a165627a7a7230582019432c544230e25e64419a06a59ec2292f9de419b8c9471a804ff8d0f53822860029```
@supernothing was able to verify this contract in Rinkeby
[https://rinkeby.etherscan.io/address/0xff14a6b72ba7ab75ae0d6b3aa67216cf49fdc551#code](https://rinkeby.etherscan.io/address/0xff14a6b72ba7ab75ae0d6b3aa67216cf49fdc551#code)
I have no balance to prove it, ropsten  is going through a fork, and etherscan dont work

**Comment by chriseth** [comment]
This seems to be the first one (please read about [metadata](https://solidity.readthedocs.io/en/develop/metadata.html)). So can this be closed?

**Comment by axic** [comment]
I think the metadata is cut off in the original comment, it is replaced  with "{bzzr}" by etherscan.

**Comment by rotcivegaf** [comment]
Ropsten etherscan its alive!
And i can verify the contract, [verified contract](https://ropsten.etherscan.io/address/0xa889fc13dbf2338046bcebe8c817ae73bc439271#code)
How fixed the bug? i don't know, but its fixed...

**Comment by rotcivegaf** [comment]
same error again...
![fail_verify](https://user-images.githubusercontent.com/7088778/48241947-b5000d80-e3b7-11e8-8a01-1adfc803224c.png)

![fail_message](https://user-images.githubusercontent.com/7088778/48242072-3a83bd80-e3b8-11e8-86a2-154b83406e3a.png)

[contract on etherscan](https://ropsten.etherscan.io/address/0x3942a383f6524716fcf76f17956de1ac52bd5626)

```
ByteCode (what we are looking for):
0x608060405234801561001057600080fd5b5060bc8061001f6000396000f300608060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063580526ee146044575b600080fd5b348015604f57600080fd5b50608b60048036038101908080357bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19169060200190929190505050608d565b005b505600{bzzr}
```
vs
```
Your Compiled Bytecode + Constructor Argument if any (what you provided):
0x608060405234801561001057600080fd5b5060ab8061001f6000396000f300608060405260043610603e5763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663580526ee81146043575b600080fd5b348015604e57600080fd5b50607a7fffffffff0000000000000000000000000000000000000000000000000000000060043516607c565b005b505600{bzzr}

```

**Comment by chriseth** [comment]
Can you provide more information about how you obtained the version of the bytecode on chain?

**Comment by rotcivegaf** [comment]
I am using the same as before:

> I deploy this contract using remix in ropsten net with version:0.4.25+commit.59dbf8f1.Emscripten.clang and enable optimization with runs: 200

**Comment by chriseth** [comment]
@rotcivegaf if it worked before with the same bytecode and does not anymore, this rather sounds like a bug in etherscan to me, at least this would be the first place to investigate.

**Comment by rotcivegaf** [comment]
@chriseth i think the same as you, but etherscan does not answer my mails

**Comment by leonardoalt** [comment]
This doesn't sound like a Solidity problem.
@rotcivegaf did you manage to contact Etherscan? Can we close the issue?

**Comment by chriseth** [comment]
This might actually be related to a boost version issue: https://github.com/ethereum/solidity/pull/5517

If you are able to re-deploy, please try with 0.5.1.

**Comment by chriseth** [comment]
I'm closing this. If 0.5.1 does not help, please open a new issue with source code so we can try to find the problem.
