### ISSUE TITLE
[Yul] Add more intermediate tests for the optimizer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5237]
Currently, we do not test the following in between the optimizer steps:
 - whether all names are unique
 - whether the code is valid (i.e. all used variables are in scope, etc)

Not having such checks makes sense in production, but we should at least have the option to enable them for testing purposes.

**Comment by axic** [comment]
There are quiet a few tests in `test/libyul/yulOptimizerTests`. Is this issue still unsolved?

**Comment by chriseth** [comment]
We are currently testing steps in isolation and we are testing the full suite. What we are not testing is the items in the descriptoin of the issue.

**Comment by axic** [comment]
We test code validity at every test for a few months. Are you saying there should be a switch which enables code validity testing in every step in the optimizer suite?

**Comment by chriseth** [comment]
Yes.
