### ISSUE TITLE
French Docs translation

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#5250]
This issue is to track the progress of the French translation of the Solidity documentation.

It includes the GitHub usernames of all involved, and links to any issues or pull requests related to the French translation.

All translation efforts in progress from this date are pinned to commit 
https://github.com/ethereum/solidity/commit/b2b845d6def4d28215c5d591589555bd8f4ea6ab

## Contributors

Based on comments in pull requests and issues, and other conversations. If you also want to be involved, please comment below.

@Karocyt @clemlak

## Fork

https://github.com/Karocyt/solidity-fr

**Comment by ChrisChinchilla** [comment]
Thanks again @Karocyt it looks like you used a recent commit to fork form, we are making quite a lot of changes to the English docs at the moment, so please let me know if you have any questions or things you need help with.

**Comment by Karocyt** [comment]
Thanks to you! I'm looking for an internship, so I'm translating and learning at the same time. Expect me to be slower and slower the deeper I get!

What do you expect to see changing that much ?
Even if the layout/wording can change and a few things be rephrased, everything seems reliable and in line with 0.5.0 so far.

**Comment by ChrisChinchilla** [comment]
@Karocyt We are just making lots of small changes, and new features, so hard to say exactly, but any effort in your part is very welcome and I hope to find you more contributors too.

**Comment by clemlak** [comment]
@Karocyt I'd be happy to help you on this task!

**Comment by Karocyt** [comment]
Thanks for your help @clemlak, invite sent, enjoy!
I'm committing every time I start working on a new file, so far going down in the menu. Pick your favorite and come along!
I tend to keep the english keywords (like "stack" or "smart contracts") but try to remind their french counterparts from time to time.
When we'll be done with translating, we might need a "Glossaire" page to sum up the specific english terms that we kept, or we can agree on translating them all, but it looks weird to me, as it should SEO-wise.
You'll need an account on readthedocs too if you want to see it rendered straight away!

**Comment by clemlak** [comment]
Thank you, perfect!

**Comment by ChrisChinchilla** [comment]
Amazing, thanks everyone, contributors updated and please let me know if you have questions.

**Comment by ChrisChinchilla** [comment]
Actually @Karocyt and @clemlak can you email me at chris.ward@ethereum.org? I have some updates I'd like to send all translators :)

**Comment by borowszky** [comment]
Hello everybody

can i also join the french translation contributors team?

**Comment by Karocyt** [comment]
Hi @borowszky
You're more than welcome!

I started this on a v0.5.0 pre-relase and we're now on v0.6.8 so I don't know how accurate it is anymore.
I had a crazy year and couldn't find much time.
I'll check about versioning the doc tomorrow to keep the half-translated state as 0.5.0 and work on a fresher one with you.
The layout seems mostly unchanged so I should be able to easily check/port what I've done so far.

**Comment by borowszky** [comment]
Thank you for your response. 
Will be expecting feedback on this, Am eager to start.

**Comment by Karocyt** [comment]
I migrated to the new layout and kept the English part when anything meaningful had been changed.
I committed on a file by file basis for the ones I did, so the last commit message usually tells you how much is left to do on that particular file.
We're now based on the release v0.6.8 commit [0bbfe45](https://github.com/ethereum/solidity/commit/0bbfe45376768007a38bfd65f8ea449935306037).

I created [this thread](https://github.com/Karocyt/solidity-fr/issues/3) on the French side of things.

**Comment by franzihei** [comment]
We are currently working on a new, hopefully more structured workflow for the Solidity docs translations. I will ping you once this is ready. Closing this issue for now, you can track the progress of the new process etc. in issue #10119.
