### ISSUE TITLE
use of memoization ?

### ISSUE THREAD

**Issue by malisetti** [ethereum/solidity#5261]
From [wikipedia](https://en.wikipedia.org/wiki/Memoization)
In computing, memoization or memoisation is an optimization technique used primarily to speed up computer programs by storing the results of expensive function calls and returning the cached result when the same inputs occur again. 

In general, computing costs gas on EVM. The concepts of memoization may be helpful for ethereum.

**Comment by chriseth** [comment]
Thanks for the hint! We are using memoization for small things and are planning to extend this with the new optimizer. Do you know of any specific situations where this might be helpful or do you have any specific ideas about how to implement it exactly?

**Comment by malisetti** [comment]
I don't have specifics, this is me just hinting but I think the pure functions can be memoized. Another thought is to use a memoize modifier ?

**Comment by chriseth** [comment]
Note that pure functions are only disallowed from making state modifications. They can still have memory arguments which they are allowed to modify.
Even if those memory arguments are immutable: You would still need to check if the function arguments are the same.
Do you think this would have many use cases at the solidity function level?

**Comment by chriseth** [comment]
I will close this until there is an example of a real-world use case, I hope you understand.
