### ISSUE TITLE
Internal compiler error: function type conversion view to non-view

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5279]
## Description

The following solidity contract produces the error: `Invalid error: "InternalCompilerError"`

```
contract C {
    function h() pure external {
    }
    function f() view external returns (bytes4) {
        function ()  external g = this.h;
        return g.selector;
    }
}
// ----
```

## Environment

- Compiler version: latest develop commit
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 16.04

## Steps to Reproduce

```
$ ./solfuzzer < <sol_contract_above>
```

Found by libFuzzer

**Comment by chriseth** [comment]
The assertion in CompilerUtils.cpp:1016 is hit. The following code compiles fine:
```
contract C {
    function h() pure external {
    }
    function f() view external returns (bytes4) {
        function () pure external g = this.h;
        return g.selector;
    }
}
```
So it seems we have to take "view/pure-widening" conversions of function types into account.
