### ISSUE TITLE
[Yul] Structural simplifier

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5290]
There should be a pass that performs various structural simplifications:

 - remove if with empty body (and movable condition)
 - remove if with true condition
 - turn switch into if (we might have an issue about that already)
 - remove for with false condition
 - remove for with empty body and post (move "pre" part)

**Comment by ekpyron** [comment]
The last point ``remove for with empty body and post (move "pre" part)`` is not a valid transformation, though, is it? E.g. for an always true condition such a for should loop until the gas runs out...
In ``remove for with false condition`` on the other hand, we still have to move the ``pre`` part.

And as an extension of the second point (in witch I guess "remove" is "move body"), I'll also remove if's with false condition.

~~Also right now whenever I remove stuff I still put them in blocks - that way the module won't have any dependencies - I could skip those blocks if we make it depend on the disambiguator, though, not sure which of the two is better.~~

I'll probably push a PR with a preliminary version shortly in any case.

**Comment by ekpyron** [comment]
I'll let it depend on the disambiguator - it makes more sense to run it later anyways.

**Comment by chriseth** [comment]
Note that we already have a transformation that unconditionally moves the `pre` part, so you can check whether the pre part is empty instead of actually moving it.
