### ISSUE TITLE
Increase test coverage to 90%

### ISSUE THREAD

**Issue by maraoz** [ethereum/solidity#5297]
## Description
Test coverage is at 88.19% now. Would be nice if someone took it to the arbitrary but satisfying 90%.
Related to https://github.com/ethereum/solidity/issues/5164

**Comment by chriseth** [comment]
I had a look at test coverage this week and concluded that measuring coverage is a good thing, but going by the total percentage is the wrong approach.

The thing is that codecov reports assertions that are not trigged as not covered. We could of course go so far and write unit tests with the sole purpose of triggering these assertions, but I don't think this would be a useful use of our time.

There are also some files and routines that are only part of the code for printing debugging information. It might make sense to write tests for them to see if we need to change those printing routines when some other part of the code is changed.

What is much more useful is to just look through the coverage reports from time to time and check if any production code is not covered by the tests, which I did this week.

**Comment by chriseth** [comment]
I created some more specific coverage-related issues. Closing this.
