### ISSUE TITLE
Aliased imports may not be working

### ISSUE THREAD

**Issue by eternauta1337** [ethereum/solidity#5305]
## Description

Imports with any syntax other than the currently most commonly used one don't seem to be working.
By the most commonly used I mean:
(1) `import "./Child.sol";`

[Solidity's documentation](https://solidity.readthedocs.io/en/v0.4.25/layout-of-source-files.html#importing-other-source-files) presents other possible forms for the import statement:
(2) `import "./Child.sol" as Juno;`
(3) `import * as Juno from "./Child.sol";`
...etc

Either I'm interpreting the documentation incorrectly, or the forms > (1) do not work, yielding errors of some kind (specified below).

## Steps to Reproduce

```solidity
pragma solidity 0.4.25;

contract Child {
    
    function smile() public pure returns (string) {
        return "haha";
    }
}
```

```solidity
pragma solidity 0.4.25;

import "./Child.sol" as Juno;

contract Parent {
    
    Juno public juno;
    
    constructor() public {
        juno = new Juno();
    }
    
    function interact() public view returns (string) {
        return juno.smile();
    }
}
```

I also played a bit with the other forms of the import statement syntax, also with no success, but I found this example to be the most illustrative.

## Environment

I tested this in multiple environments in Manjaro Linux.

**Remix**:
- Browser version: Chromium 70.0.3538.67 Arch Linux
- Compiler version: 0.4.25+commit.59dbf8f1.Emscripten.clang

```
browser/Parent.sol:7:5: TypeError: Name has to refer to a struct, enum or contract.
    Juno public juno;
    ^--^
```

**Solc**:
- Compiler version: 0.4.25+commit.59dbf8f1.Linux.g++
- Command: `solc --bin contracts/Parent.sol`

```
contracts/Parent.sol:7:5: Error: Name has to refer to a struct, enum or contract.
    Juno public juno;
    ^--^
```

**Truffle**:
- Truffle version: 4.1.14
- Solcjs version: 0.4.24

```
TypeError: Error parsing /home/ajs/contracts/contracts/Parent.sol: Cannot read property '2' of null
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/parser.js:171:1
    at Array.map (<anonymous>)
    at Object.parseImports (/home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/parser.js:167:6)
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:302:1
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:79:1
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at next (/home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/~/async/whilst.js:68:1)
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:64:1
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:85:1
    at /home/ajs/.npm-global/lib/node_modules/truffle/build/webpack:/~/async/internal/once.js:12:1
```

**Comment by chriseth** [comment]
@ajsantander note that `Juno` in your example does not represent the contract type `Child` inside the file `child.sol`, but rather the module `Child.sol` itself. I also think that the documentation is rather clear about this. If you have suggestions on how to improve it, I'm all ears!

**Comment by eternauta1337** [comment]
Aha! Yes, using `Juno.Child` works.
Thx ^^

I would simply suggest that this is clarified in the link to the documentation I provided. Perhaps with examples in the imports section?

**Comment by chriseth** [comment]
Created https://github.com/ethereum/solidity/pull/5311
