### ISSUE TITLE
Add normal form SWAP* optimizations

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#5318]
# Test case

Compiler: 0.4.25+commit.59dbf8f1.Emscripten.clang
Optimization: on with default settings in Remix IDE

```solidity
pragma solidity ^0.4.23;

contract Test
{
    function a() payable returns (address) {
        return address(this);
    }
}
```

> 608060405234801561001057600080fd5b5060c08061001f6000396000f300608060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630dbe671f146044575b600080fd5b604a608c565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6000309050905600a165627a7a72305820effc577e00e0dab11af3a8f067f6755dd66ef9191ab577e8ea00920b04f8429e0029

<details>
<summary>Opcodes</summary>
| Loc  | Op           | Data                                                         |
| ---- | ------------ | ------------------------------------------------------------ |
| 0    | PUSH1        | 80                                                           |
| 2    | PUSH1        | 40                                                           |
| 4    | MSTORE       |                                                              |
| 5    | PUSH1        | 04                                                           |
| 7    | CALLDATASIZE |                                                              |
| 8    | LT           |                                                              |
| 9    | PUSH1        | 3f                                                           |
| 11   | JUMPI        |                                                              |
| 12   | PUSH1        | 00                                                           |
| 14   | CALLDATALOAD |                                                              |
| 15   | PUSH29       | 0100000000000000000000000000000000000000000000000000000000   |
| 45   | SWAP1        |                                                              |
| 46   | DIV          |                                                              |
| 47   | PUSH4        | ffffffff                                                     |
| 52   | AND          |                                                              |
| 53   | DUP1         |                                                              |
| 54   | PUSH4        | 0dbe671f                                                     |
| 59   | EQ           |                                                              |
| 60   | PUSH1        | 44                                                           |
| 62   | JUMPI        |                                                              |
| 63   | JUMPDEST     |                                                              |
| 64   | PUSH1        | 00                                                           |
| 66   | DUP1         |                                                              |
| 67   | REVERT       |                                                              |
| 68   | JUMPDEST     |                                                              |
| 69   | PUSH1        | 4a                                                           |
| 71   | PUSH1        | 8c                                                           |
| 73   | JUMP         |                                                              |
| 74   | JUMPDEST     |                                                              |
| 75   | PUSH1        | 40                                                           |
| 77   | MLOAD        |                                                              |
| 78   | DUP1         |                                                              |
| 79   | DUP3         |                                                              |
| 80   | PUSH20       | ffffffffffffffffffffffffffffffffffffffff                     |
| 101  | AND          |                                                              |
| 102  | PUSH20       | ffffffffffffffffffffffffffffffffffffffff                     |
| 123  | AND          |                                                              |
| 124  | DUP2         |                                                              |
| 125  | MSTORE       |                                                              |
| 126  | PUSH1        | 20                                                           |
| 128  | ADD          |                                                              |
| 129  | SWAP2        |                                                              |
| 130  | POP          |                                                              |
| 131  | POP          |                                                              |
| 132  | PUSH1        | 40                                                           |
| 134  | MLOAD        |                                                              |
| 135  | DUP1         |                                                              |
| 136  | SWAP2        |                                                              |
| 137  | SUB          |                                                              |
| 138  | SWAP1        |                                                              |
| 139  | RETURN       |                                                              |
| 140  | JUMPDEST     |                                                              |
| 141  | PUSH1        | 00                                                           |
| 143  | ADDRESS      |                                                              |
| 144  | SWAP1        |                                                              |
| 145  | POP          |                                                              |
| 146  | SWAP1        |                                                              |
| 147  | JUMP         |                                                              |
| 148  | STOP         |                                                              |
| 149  | LOG1         |                                                              |
| 150  | PUSH6        | 627a7a723058                                                 |
| 157  | SHA3         |                                                              |
| 158  | INVALID      |                                                              |
| 159  | INVALID      |                                                              |
| 160  | JUMPI        |                                                              |
| 161  | PUSH31       | 00e0dab11af3a8f067f6755dd66ef9191ab577e8ea00920b04f8429e0029 |
</details>

# Subjects

## Get address

This is:

| Loc  | Op           | Data                                                         |
| ---- | ------------ | ------------------------------------------------------------ |
| 141  | PUSH1        | 00                                                           |
| 143  | ADDRESS      |                                                              |
| 144  | SWAP1        |                                                              |
| 145  | POP          |                                                              |

# Optimizations

## Swaps

This is a huge, low-hanging fruit.

`let SINGLE_OUTPUT = [ADDRESS, ORIGIN, CALLER, CALLVALUE, CALLDATASIZE, CODESIZE, GASPRICE, RETURNDATASIZE, COINBASE, TIMESTAMP, NUMBER, DIFFICULTY, GASLIMIT, PUSH*]`

`let SINGLE_INOUT = [ISZERO, NOT, BALANCE, CALLDATALOAD, EXTCODESIZE, BLOCKHASH, MLOAD, SLOAD] `

then optimize: `(SINGLE_OUTPUT SINGLE_INOUT*) (SINGLE_OUTPUT SINGLE_INOUT*) SWAP1 ➡️ &2 &1`

This one is enough to make a dent. 

If somebody really cared to go further, all of the SWAP*N* can be similarly optimized in this fashion. It requires other `let` variables. Because this is a normal form, every SWAP*N* operation could be optimized using a regex.

## POP

Likewise: `(SINGLE_OUTPUT SINGLE_INOUT*) POP ➡️ (NOTHING)`

# Discussion

I am not sure which optimizations are in scope. So I'm not going to go too far with these. But a normal form to analyze POP, DUP* and SWAP* might be helpful.

**Comment by chriseth** [comment]
Are you sure the existing optimizer ran in your case? I don't get a `pop` when I run it locally:
```
    tag_4:
        /* "/tmp/x.sol":92:96  this */
      address
        /* "/tmp/x.sol":21:104  function a() public payable returns (address) {... */
      swap1
      jump	// out
```

**Comment by fulldecent** [comment]
You're right. I can't reproduce it. Not sure how this is happening on Remix. But will close for now and reopen if I can reproduce on `solc`.
