### ISSUE TITLE
CALLDATA for call is packed differently than for canonical calls

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#5321]
# Test case

Compiler: 0.4.25+commit.59dbf8f1.Emscripten.clang
Optimization: on default for Remix IDE

```solidity
pragma solidity ^0.4.23;

contract Test
{
    function needSu(string somebody) pure public {
        string memory su = "Su";
        assert(keccak256(somebody) == keccak256(su));
    }
    
    function testSolidity() external {
        string memory su = "Su";
        this.needSu(su);
    }
    
    function testCall() external {
        string memory su = "Su";
        bool ret = address(this).call(this.needSu.selector, su);
        assert(ret);
    }
}
```

* Set a breakpoint on `assert()` and run both functions in Remix IDE. Capture the CALLDATA for the inner call.

# Actual outcome

CALLDATA 1: 

**0x57e6193b**000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000025375000000000000000000000000000000000000000000000000000000000000

CALADATA 2:

**0x57e6193b**5375000000000000000000000000000000000000000000000000000000000000

# Expected outcome

Identical call data

# Discussion

Relevant documentation is at https://solidity.readthedocs.io/en/v0.4.25/types.html#members-of-addresses

> These arguments are padded to 32 bytes and concatenated.

I am not exactly sure if this explanation of CALLDATA encoding is accurate. (Is `string` actually an array of bytes, or does it only look that way with ABI encoding?) 

At a minimum, the documentation should be updated to explain how this situation (and also `bytes`) differs from what I'm expecting. At a maximum, the compiler is producing incorrect results.

And, of course, #1505 FTW. That ends the need to use call for 90% of cases.

**Comment by chriseth** [comment]
Note that pre-0.5.0, `call` performed its own encoding ("pad to 32 bytes and concatenate") which was different from ABI encoding. We removed this special case for 0.5.0 and now `call` just takes a `bytes` and passes it on as is without modification.

**Comment by fulldecent** [comment]
Thank you for this detail, very helpful. That new solution surely looks like less baggage. So for the future this look fixed, closing.
