### ISSUE TITLE
Erasing array elements on explicit length change

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#5322]
Today discovered that shrinking array length erases latest elements in loop. This default behavior can lead to many bugs, because many developers consider `length` change as `O(1)` complexity action. So erasing large array can waste a lot of gas also not fit into the Ethereum block.

I think if someone shrinks array, this array very likely could be enlarged in future. Let's not erase latest elements on array length decrease.

Made methods for `O(1)` length change and dirty elements erasement. For example second method could be exposed as smart contract public method for anyone who want to refund some gas.
```Solidity
library DirtyArray {
    function setLength(uint[] storage arr, uint length) internal {
        assembly {
            sstore(arr_slot, length)
        }
    }
    
    function eraseDirty(uint[] storage arr, uint start, uint length) internal {
        for (uint i = start; i < start + length; i++) {
            if (i >= arr.length) {
                uint ptr;
                assembly {
                    ptr := add(keccak256(arr_slot, 0x20), i)
                    if gt(sload(ptr), 0) {
                        sstore(ptr, 0)
                    }
                }
            }
        }
    }
}
```

Or at least add this API for `O(1)` length change:
```Solidity
arr._length = newLength;
```

**Comment by chriseth** [comment]
I don't think it is a good idea to keep storage dirty - there would be no way to clear it without the use of inline assembly. We decided for a different way to solve the underlying issue, though: https://github.com/ethereum/solidity/issues/3515

**Comment by k06a** [comment]
@chriseth I think if someone shrinks array, this array very likely will be enlarged in future. Also, I see the only way for cheap cleanup arrays or mappings to use subcontract.

**Comment by chriseth** [comment]
If you don't mind, I will be closing this. We do not have any plans to keep storage dirty for now for various reasons.
