### ISSUE TITLE
Documentation: Typecasting `int` to `uint` keeps internal representation

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#534]
`int` has a two's complement representation (for negative numbers), e.g. `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff` is `-1`.

Example:

```
int a = -1;
uint b = uint(a); // will equal to 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

Not fully sure what the behaviour should be. From a low level point of view this is correct, from a high level point of view this is wrong - where typecasting to uint would behave like losing the sign (i.e. like `abs`).

**Comment by VoR0220** [comment]
this sounds like it could get expensive from an assembly point of view. This is a good point you make...I'll add it to the features bit.

**Comment by axic** [comment]
I actually spent some time writing an optimised `abs` in assembly - will post when ready.

In terms of rejecting the `uint()` cast when the number is negative that is simple (just check the highest bit for the given intXX). Too bad this only works well compile time as I guess it wouldn't be sane throwing runtime on a typecast :smiley:

At the very least the effect of this typecast should be documented because it might not be trivial or what people expect.

**Comment by VoR0220** [comment]
Agreed.

**Comment by graup** [comment]
I just ran into this problem. From other languages, I was expecting `uint(-127) == 127`. Let's at least make it clear in the docs that this doesn't hold.

@axic  having an optimized `abs` in the standard library would be quite nice, I think!

**Comment by VoR0220** [comment]
@graup agreed on both ends.

**Comment by Denton-L** [comment]
I think this can be closed. It's mentioned [here](http://solidity.readthedocs.io/en/latest/types.html#explicit-conversions).

**Comment by elenadimitrova** [comment]
@axic did you ever get to finish the `abs` implementation?
