### ISSUE TITLE
Internal compiler error: Null type in VariableDeclarationAnnotation

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5340]
## Description

CC #5048 

Contract:
```
library L{struct Nested{n y;}function(function(Nested)external){}}
```

Error:
```
Internal compiler error during compilation:
/home/bhargava/work/github/solidity/libsolidity/ast/Types.cpp(2127): Throw in function virtual bool dev::solidity::StructType::canBeUsedExternally(bool) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what:
[dev::tag_comment*] =
```

## Environment

- Compiler version: latest dev commit
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 16.04

## Steps to Reproduce

```
$ ./solfuzzer < <sol_contract_above>
```

Found by libFuzzer.

**Comment by erak** [comment]
@bshastry Thanks for the report. We'll try to fix it with 0.5.1.

**Comment by axic** [comment]
This seems to be a duplicate of #5048 ?

**Comment by chriseth** [comment]
Duplicate.
