### ISSUE TITLE
Need more precise descriptions about supporting inheritance in Solidity

### ISSUE THREAD

**Issue by sunbeomso** [ethereum/solidity#5345]
I wonder the exact mechanism of copying code that involves "super" keyword for supporting inheritance in Solidity.

I think clarification of this potentially helps the formal verification community.

Below is an example code that elaborates my question.

    contract C { 
        function test() public {  } 
    }

    contract B is C {
        function bbb() public {  }
        function test() public {
           bbb(); 
           super.test(); 
        }
    } 

    contract A is B {
    }

If we deploy the contract ```A``` and calls the function ```A.test()```, then the actual (and desirable) effect is a call sequence of ```bbb()->C.test()``` (where super is replaced with C).

However, _literally_ following the below explanation on inheritance in Solidity docs
> the code from all the base contracts is copied into the created contract.

may produce undesirable behaviors.
For clarification, let me perform the copy process for the example code above:

    contract C { 
        function test() public {  } 
    }

    contract B is C {
        function bbb() public {  }
        function test() public {
           bbb(); 
           super.test(); 
        }
    } 

    contract A is B {
        function bbb() public {  }
        function test() public {
           bbb(); 
           super.test(); 
        }
    }

Again, if we deploy ```A``` and calls ```A.test()```, then we have a call sequence of ```bbb() -> B.test() -> bbb() -> C.test() ```, where the ```super```s in ```A``` and ```B``` are replaced by ```B``` and ```C```, respectively.

Do I have any missing point?

**Comment by chriseth** [comment]
You are right, the exact wording in the documentation is not the best. What is meant there is that the bytecode is made available, not necessarily the source code. Would you be interested in improving the documentation there?

**Comment by sunbeomso** [comment]
Unfortunately, I do not know the exact process or mechanism. This is why I raised the issue. It would be nice if explanations could be accompanied by some concrete examples.

**Comment by chriseth** [comment]
@SunBeomSo would https://github.com/ethereum/solidity/pull/5541increase the understanding? I know it does not add an example, but since the operation cannot be represented as an operation on source code, it is hard to provide an example.
