### ISSUE TITLE
Force `_` to be function body in modifiers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#535]
Functions and modifiers can be a single underscore:

```
function _() {
}
```

or

```
modifier _ {
}
```

is valid.

This is problematic at least in the case someone tries to refer to this method in a modifier, where it clashes with the `_` keyword:

```
function _() {
}

modifier wrong {
  _()
  _
}
```

results in:

```
Untitled1:29:9: Error: Expected token Semicolon got 'Identifier'
        _
        ^
```

I think the single underscore name should be disallowed. Furthermore I think trailing underscores should be too, i.e. `wrongMethod__` should be invalid.

**Comment by VoR0220** [comment]
coming from Go, I think the underscore can be a very valid keyword :). 

You also forgot a semicolon in calling your _(). But perhaps the _ by itself should only be available for use in modifiers. Does that sound like a decent compromise?

**Comment by chriseth** [comment]
Solidity aligns with javascript here: `_` is a perfectly valid identifier. It is a bit unfortunate, that it cannot be used in modifiers, but I think we have to live with that for now.

**Comment by axic** [comment]
As mentioned by @VoR0220 there was a typo in the code.

Here's a complete example:

```
contract A {
    uint public x = 1;
    function _() {
        x = 5;
    }
    modifier test {
        _();
        _
    }
    function b() test returns (uint) {
        return 1;
    }
}
```

This compiles, but the `_()` is not executed from within the modifier.

Calling `b()` will return 1 and not update x. Calling `_()` directly will change x.

**Comment by chriseth** [comment]
@VoR0220 any progress on this? I would like to finish all nextrelease tasks this week. If you do not have time, I can do it.

**Comment by VoR0220** [comment]
@chriseth I am so sorry. I'm really caught up. I can hand it off.

**Comment by chriseth** [comment]
Haha, this is interesting. It turns out that `_` is correctly parsed as a placeholder statement inside modifiers. Let's break it down:

```
    modifier test {
        _();
        _
    }
```

The modifier body consists of a placeholder, an expression statement that only contains an empty tuple and again a placeholder, so the function `_` is not called here.

The question now is: Should we warn when identifiers with the name `_` are declared?

**Comment by axic** [comment]
> The question now is: Should we warn when identifiers with the name _ are declared?

It should be an error condition. Solidity's target is not writing IOCCC submissions.

**Comment by chriseth** [comment]
Another solution might be to change the placeholder statement to `_;` - that would probably also be more consistent and if you have an identifier called `_` you would not use it in this way.

**Comment by redsquirrel** [comment]
I think `_;` is a good idea.

**Comment by VoR0220** [comment]
I agree `_;` is a good idea.

**Comment by axic** [comment]
Shouldn't we consider less cryptic options, such as `body;` ?

**Comment by chriseth** [comment]
@axic we can discuss that for 0.5.0.
