### ISSUE TITLE
Allow public functions overwrite external function (with memory / calldata types)

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5350]
@axic is there a duplicate for this?

**Comment by leonardoalt** [comment]
Duplicate of https://github.com/ethereum/solidity/issues/4832?

**Comment by axic** [comment]
I think so, lets close for now.

**Comment by ekpyron** [comment]
@axic: @leonardoalt already closed #4832 in favor of this one - we should keep at least one of them open ;-).

**Comment by ekpyron** [comment]
Or wait - now #4832 is open again? Confusing :-D. Ok, then I close this again :-).

**Comment by ekpyron** [comment]
Ah Ok - the one leo closed was #4870 - which is also the same issue :-).

**Comment by leonardoalt** [comment]
I closed an old PR that I had with a hack, but kept the old issue with the bug label.
