### ISSUE TITLE
[Yul] Improve stack slot allocation in code generator (and avoid swaps)

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5375]
See if the algorithm presented in https://pdfs.semanticscholar.org/presentation/1a65/e787b08fe8812797a0557760ae84072ad292.pdf is relevant for the yul to evm code generator to avoid swap operations.

**Comment by ekpyron** [comment]
I only had a brief look into the paper, but at a first glance this would probably mean to have an intermediate compilation step to a register based representation? I'm wondering whether one could use some stuff like this: http://compilers.cs.uni-saarland.de/projects/ssara/ - it seems for an SSA representation of a program optimal register allocation is feasible (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.204.2844&rep=rep1&type=pdf) - registers are different than our fixed-size (wrt access) stack, but maybe that's transferrable (to allocating stack slots directly)?

**Comment by chriseth** [comment]
Yeah that's the point - most research on this topic is based on register machines. Since we use the stack both as expression stack and as local variable storage, it is almost the same, but not quite.

For example, currently, we do not optimize the last usage of a stack item:
`let x := 2 mstore(0, x)` is currently translated to `2 dup1 0 mstore pop` while it could be translated to `2 0 mstore`

or a similar but more complicated version (this blurs the line between expression stack and variable storage):

`let x := 2 mstore(x, 0)` is currently translated to `2 0 dup2 mstore pop`, but could be translated to `2 0 swap1 mstore`.

**Comment by recmo** [comment]
The paper and presentation start with a registry based representation. The actual algorithm starts with expression DAGs. I'm not sure what the current internal representation, but expression DAGs are equivalent to SSA when it comes to basic blocks / linear code. They are also a very natural fit for YUL as far as I can tell.

It works by finding an optimal cut-set to turn the expresssion DAG into a set of trees (forest). Each tree is optimally sorted and requires no stack operations. The trees are combined using the minimal set of operations. (Note that in the instructions set of the presentation `DUP` works exclusively on top of the stack and `FETCH` retrieve items down the stack and puts it on top. Some translation to the EVM stack operations is required. The accompanying paper explains this better.)

@chriseth's last example would compile to `0 2 mstore`, as it should. (In this case peephole optimizations would probably catch it, but this is not generally true as the set of instructions that need to be re-order can grow indefinitely).

**Comment by lastperson** [comment]
I guess this is relevant:
```
pragma solidity 0.5.1;

contract StackCleanupTest {
    function _itShouldStop(uint _a) internal pure returns(bool) {
        return _a == 1;
    }
    
    function test() public pure returns(uint, uint, uint, uint, uint, uint, uint, uint) {
        uint a1 = 1;
        bool itShouldStop = (a1 == 1); // will cause 'stack too deep' error.
        if (itShouldStop) {}
        // if (_itShouldStop(a1)) {} // will compile with this.
        uint a2 = 1;
        uint a3 = 1;
        uint a4 = 1;
        uint a5 = 1;
        uint a6 = 1;
        uint a7 = 1;
        uint a8 = 1;
        
        return (a1, a2, a3, a4, a5, a6, a7, a8);
    }
}
```

The question is, why the variable (*itShouldStop* in the example) is not removed from the stack on the last read?
The implication is that temporary variables for improved code readability seem to unnecessary pollute the stack. Current workaround is to introduce a pure function instead of the temporary local variable, though readability will suffer already, especially if this function will be used only once.

**Comment by chriseth** [comment]
@lastperson be my guest https://github.com/ethereum/solidity/blob/develop/libyul/backends/evm/EVMCodeTransform.cpp#L354 ;)
