### ISSUE TITLE
[Yul] Explicit lifetime for YulStringRepository

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#5378]
Although #5377 seems to fix the immediate non-determinism issue we had, I think we should revisit and improve this at some point.

I think it would be cleaner to have the ``YulStringRepository`` be a member to some kind of context class (that doesn't exist at the time of writing) or a local variable somewhere or to give it an explicit lifetime in some other way. There could still be a static pointer (or ``std::weak_ptr``?) to this global object in ``YulStringRepository`` that can be initialized upon creation and uninitialized/set to zero upon destruction of the ``YulStringRepository``. ``YulStringRepository::instance()`` should assert that a ``YulStringRepository`` is currently available and return it, but throw if there is no global ``YulStringRepository`` instead of just creating one.

**Comment by chriseth** [comment]
The big problem is dangling YulStrings whose lifetime extends beyond the lifetime of the repository. I would not want to need to track all of them because that again ruins performance I would say, but your suggestion is certainly better than the current solution. Feel free to try something out!
