### ISSUE TITLE
InternalCompilerError: Requested type not present.

### ISSUE THREAD

**Issue by Eknir** [ethereum/solidity#5385]
## Description

Defining both a mapping (perhaps it also holds for other variable types) and an event with the same name + emitting this event inside a function body leads to an ``InternalCompilerError: Requested type not present.``. No further clarification is given as to why this error is present, which leads wasting of time to find the source of the bug. [Remix](https://remix.ethereum.org) handles the error gracefully by giving an ``Declaration Error: Identifier already declared`` error.
Request: handle this error in the way Remix does, or tell the developer via another way that he should not declare an event and a variable witht he same name.

## Environment

Truffle v4.1.14
Ganache-cli 6.1.4
MacOS Mojave (10.14)

## Steps to Reproduce

Example contract:
```
pragma solidity ^0.4.24;

contract internalCompilerError {
    
      event SOToPO(
        uint256 indexed PONumber,
        uint256 indexed SONumber
    );
    
    mapping(uint256 => uint256) public SOToPO;
    
   function sellerConfirmBefore(
        uint256 PONumber,
        uint256 SONumber
    )
        public
    {
        emit SOToPO(PONumber, SONumber);
    }
}
 ```

* Set up ganache: ``ganache-cli``
* Compile: ``truffle compile``
* Error: ``InternalCompilerError: Requested type not present. Compilation failed. See above. ``
* This is caused by the line ``emit SOToPO(PONumber, SONumber).``

**Comment by chriseth** [comment]
This has already been fixed in 0.5.0.
