### ISSUE TITLE
[DOC] Split files

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5396]
Especially for translation, people reported that it would be better to have more smaller files.

**Comment by ChrisChinchilla** [comment]
This is definitely something I have been thinking about, also fits well into menu restructure conversations.

**Comment by ChrisChinchilla** [comment]
This is in progress, but we need to consider the merging implications of this change.

**Comment by ChrisChinchilla** [comment]
Start when existing docs PRs are all merged (at writing 3) - https://github.com/ethereum/solidity/pulls?q=is%3Aopen+is%3Apr+label%3A"documentation+%3Abook%3A"
