### ISSUE TITLE
can i use in live deployement pragma experimental ABIEncoderV2?

### ISSUE THREAD

**Issue by aihuawu** [ethereum/solidity#5397]
Hi, all:

I really like the feature:
pragma experimental ABIEncoderV2;

Can I use this feature so that I can return a struct?
When can I use this feature?

The compiler gives the warning. That mean I should only use it for development.
That makes no sense to me.

Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental ABIEncoderV2;

**Comment by chriseth** [comment]
The encoder should not cause any security issues (of course we can never be sure). The main reason it is marked experimental is because it causes higher gas usage.

**Comment by Aziiiz** [comment]
except for high gas usage.  Is there another reason for not using pragma experimental ABIEncoderV2 for live development?
