### ISSUE TITLE
Check for callvalue once for all non-payable function in the dispatcher

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5402]
The check for non-empty callvalue is performed for every non-payable function. It makes sense to extract the check and only do it once. This essentially requires the dispatch routine to group the functions by payable and non-payable. These are 8 instructions per function.

**Comment by Marenz** [comment]
We couldn't go the full way and do the check only once for all non-payable functions, but we did enhance it so the check is only done once if all functions are non-payable.
