### ISSUE TITLE
[Yul] Optimize EVM code generation to not jump over functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5405]
If functions are properly grouped, the EVM code generator should add a STOP instruction if only function definitions follow instead of jumping over the function definitions.

**Comment by chriseth** [comment]
The relevant function is `void CodeTransform::operator()(FunctionDefinition const& _function)` - the task is to avoid the line `m_assembly.appendJumpTo(afterFunction, -stackHeightBefore + height);`.

It could be determined inside `void CodeTransform::operator()(Block const& _block)` what the last function in a series of functions is.

Note that it is probably fine to only do in the topmost block and only if it ends in a series of function definitions.

**Comment by vedant1811** [comment]
From what I understand, 

`{ function f() {} function g() {} sstore(0, 1) }`

currently generates:

```
  jump(tag_1)
tag_2:
  jump
tag_1:
  jump(tag_3)
tag_4:
  jump
tag_3:
  0x01
  0x00
  sstore
```
 
Instead, it should be optimised to

```
  jump(tag_1) /* jump to tag_1 directly */
tag_2:
  jump
/* remove tag_1:        - last  output of function definition of f()
   remove  jump(tag_3)  - first output of function definition of g()  */
tag_3:
  jump
tag_1:
  0x01
  0x00
  sstore
```

**Comment by chriseth** [comment]
Exactly, and `tag_1 jump(tag_3)` should be removed entirely.

**Comment by vedant1811** [comment]
I have started working on it: https://github.com/ethereum/solidity/pull/6666

Do you think the approach of adding mutable variables to `struct FunctionDefinition` is the way to go?
