### ISSUE TITLE
Preconditions and postconditions as part of Solidity

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#5421]
Description: TODO

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/4991

**Comment by cameel** [comment]
@leonardoalt We're still planning to do this in some form, right?

**Comment by leonardoalt** [comment]
> @leonardoalt We're still planning to do this in some form, right?

Kinda. I think we moved to the idea of doing this on the natspec level.
