### ISSUE TITLE
[PROJECT] Provide a "src" folder

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#5429]
## Abstract

Provide a "src" folder, in which all relevant sources are moved in

## Motivation

The overall project-structure is currently very clean. An enhancement would be to group the source-code into a "src" folder.

## Specification

- move existent source folders
- possibly exclude the lll code ("alien" src)
- optionally, include a README with a subsystems-overview.

## Backwards Compatibility

- Compatible (for solidity project itself) 
- projects which depend/use solidity source directly need to adapt.

**Comment by axic** [comment]
What is the main benefit of this?

**Comment by ghost** [comment]
> What is the main benefit of this?

* The question "where is the relevant source-code" is immediately answered.
* The root-directory shrinks (and thus it is less overwhelming, especially for newcomers)
* For some more reasons, this is standard-practice in "java" and "C++" projects (never looked the reasons up, I'm used to have a "src" folder...). I can take a quick look though, if you wish.

**Comment by axic** [comment]
There is a big disadvantage though: Github will not display any kind of history for moved files (it is a shortcoming in Github, not git - it can be done on the commandline). And since almost every file has to be moved, that is quite bad.

**Comment by ghost** [comment]
I see, a known issue, see https://github.com/isaacs/github/issues/900

So, the current workaround would be to use the chrome-extension mentioned in https://github.com/isaacs/github/issues/900, and for sure there are local UI tools which display full history.

**Comment by axic** [comment]
I know it is a known issue (I follow the thread) and it has received 0 response from Github for 1.5 years, since it is an unofficial repository.

I'm not yet convinced moving stuff before that is more widely available (how many people search for historical commits on the CLI and not on github?) I think it is more of a detriment, than benefit.

**Comment by ghost** [comment]
Like many things in project-management, it is a matter of setting priorities.

The issue is: what has priority?

a) A clean (quasi)standard project-structure?
b) "bowing" to (one more) defect of github?

For me it would be quite clear: ignore the github nonsense, and go on - e.g. whilst suggesting to the team an local UI tool (NOT cli), for the case historical code-research is needed).

Despite this, I understand your position.

Can you please clarify if you would be ok with moving code into a src folder, once the history-thing is solved (or at least worked-around) ?

**Comment by chriseth** [comment]
I'm pretty sure this has a very bad benefit / cost ratio and propose to close this issue.

**Comment by ghost** [comment]
> I'm pretty sure this has a very bad benefit / cost ratio

... (no comment)

**Comment by leonardoalt** [comment]
Can we close this then?

**Comment by ghost** [comment]
> Can we close this then?

From all issues I've filed here in this project, this one is most possibly the most important one.

But I am now at my limits of "trying to explain the obvious" (thus "no comment").

Please feel free to close this issue.
