### ISSUE TITLE
Update examples on ethereum.org

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5431]
https://ethereum.org contains several Solidity examples that are outdated and need to be updated.

[ ] https://ethereum.org/greeter (PR: https://github.com/ethereum/ethereum-org/pull/919)
[ ] https://ethereum.org/token (PR: https://github.com/ethereum/ethereum-org/pull/920)
[ ] https://ethereum.org/dao (PR: https://github.com/ethereum/ethereum-org/pull/921)
[ ] https://ethereum.org/crowdsale (PR: https://github.com/ethereum/ethereum-org/pull/922)

**Comment by axic** [comment]
Make sure the examples work with both 0.4.x and 0.5.x.

**Comment by chriseth** [comment]
@axic how should that be possible?

**Comment by chriseth** [comment]
Closing because all mentioned PRs are merged.
