### ISSUE TITLE
Run tests on ethereum.org examples

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5432]
In order to make sure that all the examples on https://ethereum.org are compiling, we could add them to our testing pipeline. The majority of them are already stored in separate files (the only exception is https://ethereum.org/greeter) and could be easily picked while running the external tests. 

Todo:
[ ] Move remaining examples from Markdown to separate files
[ ] Clone the ``ethereum-org`` repository and try to compile all contracts contained in ``/solidity``

**Comment by chriseth** [comment]
Probably a good idea! We should also sync up with the people who are maintaining these tutorials (and check if such people actually exist :) ).

**Comment by chriseth** [comment]
The files are here: https://github.com/ethereum/ethereum-org/tree/master/solidity

**Comment by axic** [comment]
The website was replaced with a new one. Closing as it doesn't contain too many examples and is not centered around those.
