### ISSUE TITLE
Constant keyword to be required for initialization outside constructor

### ISSUE THREAD

**Issue by arisAlexis** [ethereum/solidity#5448]
## Abstract

Variable assignments outside of the constructor become defacto constant without the keyword. It is very confusing for developers coming from other languages (almost all). 

## Motivation

Enforce the use of constant keyword otherwise treat the variable as if it was initialized in the constructor.

## Specification

```
    uint public fee=1000000;
    constructor() public {}
    setFee(uint _fee) external onlyOwner {
        fee = _fee;
    }

```

while the above results in a constant variable test that cannot be changed from functions, it should be treated as the following code was written:

```
    uint public test;
    constructor() public {
        test = 100000;
    }
```

**Comment by erak** [comment]
@arisAlexis The example given above allows to reassign a different value in functions. Please consider the following contract:
```
contract C {
    uint public test = 1000000;
    constructor() public {}   
    function f() public { test = 2000;}
}
```
Calling ``test()`` (the auto-generated getter for ``test``) after ``f()`` was called returns ``2000``. You could change the declaration to ``uint constant public test = 1000000;`` which would result in an error when reassigning to it in ``f()``.

**Comment by arisAlexis** [comment]
I am sorry if that was wrong understanding. I deployed the contract described in the issue and the function `setTest(uint _test) onlyOwner { test=_test; }` did not set the new value but when assigned in the constructor it did. If that's not replicable by others feel free to close the issue.

**Comment by leonardoalt** [comment]
Hi @arisAlexis , please note that you didn't post the contract you deployed. Could you post the entire contract so that we can try to replicate your exact steps?

In the snippet you just posted, could the reason for state variable `test` not changing be that you called the function from an account that is not the `owner`?

**Comment by arisAlexis** [comment]
@leonardoalt sorry the contract is for a startup I am working for and the code is not open source currently (although using Ethereum) but effectively I deployed the same contract with the same owner (confirmed by calling the owner public getter (it's an openzeppelin standard contract inherited) and the same function that did not change the variable did change it after I just put the initial value in the constructor and redeployed.

**Comment by leonardoalt** [comment]
@arisAlexis I understand. The problem with that is that we can only imagine the exact contents of the contract and can't replicate exactly the behavior. Could you post a minimized version (just the constructor and the one function and variable) of the contract that still has the error?

**Comment by arisAlexis** [comment]
I updated the specification section and it is exactly the same as the deployed contract at address 0xe1224c7a75d9455ef1054ea0c19f2a66497f4fd7 on rinkeby network and you can see at that address that I sent many transactions from the owner account that were not rejected but didn't change the value. Maybe I am doing something very wrong.

**Comment by leonardoalt** [comment]
I wrote a new piece of code that (I guess) looks similar to what you described:
```
contract C
{
    uint public fee=1000000;
    address public owner;

    modifier onlyOwner {
        require(msg.sender == owner);
        _;
    }
    
    constructor() public {
        owner = msg.sender;
    }
    
    function setFee(uint _fee) external onlyOwner {
        fee = _fee;
    }
}
```
I deployed it and the function works as expected, updating the value of variable `fee`.

I saw on the testnet that the function is called by the same address that created the contract.
Unfortunately I can't do much more without access to the actual code.

**Comment by arisAlexis** [comment]
OK since it's working since I changed it I won't dig into it anymore, I thought it was an implicit conversion from the language and was good to give input. Thanks again :)
