### ISSUE TITLE
Solidity user survey

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5453]
## Abstract
Design and conduct a survey that helps us gain more knowledge about our user base (for example hosted on https://www.limesurvey.org/)

### General questions
- Operating system (Win, macOS, Linux etc.)
- Solidity version
- Installation (from source, Homebrew, Chocolatey etc.)
- Framework usage (Truffle, Embark, etc.)
- Editor (VSCode, Remix, etc.)
- Experience level

### Solidity specific questions
- Most wanted features
- etc.

**Comment by erak** [comment]
@christianparpart referred to the latest [Rust survey](https://blog.rust-lang.org/2018/11/27/Rust-survey-2018.html) as an source of inspiration. I also think that it contains some measures and metrics which could be of interest (e.g. expertise x difficulty of learning language concepts).

**Comment by axic** [comment]
cc @franzihei this might be interesting to you

**Comment by franzihei** [comment]
yes, thank you!

**Comment by franzihei** [comment]
I am working on questions for the survey, which I am collecting [here](https://docs.google.com/spreadsheets/d/1ikNbAj7tfPiRvediwp3kl-vxbBEd8wdl-4hK3xI71IU/edit?usp=sharing). 

I am taking inspiration from the
- [Rust Survey 2019](https://blog.rust-lang.org/2020/04/17/Rust-survey-2019.html) (2020 results not yet published)
- [Go Developer Survey 2019](https://blog.golang.org/survey2019-results) (2020 results not yet published)
- [StakOverflow Dev Survey 2020](https://insights.stackoverflow.com/survey/2020#overview)

Once finished, I will copy the questions into a Google Form questionnaire to have it ready to be shared.

**Comment by franzihei** [comment]
Survey is ready to be proof-read and launched here: https://docs.google.com/forms/d/e/1FAIpQLSdcTPsWxuXmyG74t_zUI4pYQk1Y7mFcz03Owg4wJqrvRh7SsA/viewform

**Comment by chriseth** [comment]
Looks good!

**Comment by franzihei** [comment]
Done and launched here: https://twitter.com/solidity_lang/status/1336708883193208833
