### ISSUE TITLE
Latest Docker images seem to no longer include `/bin`

### ISSUE THREAD

**Issue by juztin** [ethereum/solidity#5460]
## Description

Latest Docker images seem to no longer include `/bin`.

We've been using the upstream `ethereum/solc:stable` as a parent image for compilation / ABI generation, but noticed that the latest push no longer includes `/bin`. 

The file-system on the image has:

```
.dockerenv
dev/
dev/console
dev/pts/
dev/shm/
etc/
etc/hostname
etc/hosts
etc/mtab
etc/resolv.conf
proc/
sys/
usr/
usr/bin/
usr/bin/solc
```

Just wondering if this was intentional, before we go building a `solc` image. The [Dockerfile](https://hub.docker.com/r/ethereum/solc/~/dockerfile/) doesn't appear to have anything that would remove it.

**Comment by chriseth** [comment]
Weird - this might have been caused by an update to the base alpine image. I'm not an expert on docker usage, but strictly, `/bin` is not required for running solidity, so it should not be included in the docker image, or should it?

**Comment by juztin** [comment]
Found it!

The Dockerfile on [DockerHub](https://github.com/ethereum/solidity/blob/3b1741909c7472b892695260b0b8c59a53c2183e/scripts/Dockerfile) was throwing me off. It's using Alpine as the base, which has all of the missing pieces, but commit 754610077680e19a80655ab1dcc0f430a340c232 changed to using a multi-stage build where the resulting image is based on `scratch`, which is empty.

I love the idea of using `scratch` as a base for just the `solc` binary, but is it out of the question for a request to also have a build based on Alpine _(for people wanting to have a base image to work from)_?

Maybe something like:

`ethereum/solc:stable`  <-- current image, using scratch  
`ethereum/solc:alpine`  <-- image based on Alpine, for use with downstream projects

I'd be willing to do the work/submit a PR if it's something you feel would add value _(otherwise this is good to close)_.

Thanks

**Comment by chriseth** [comment]
If you can find a way that has a nice versoning scheme and avoids building twice, then please go ahead!

**Comment by juztin** [comment]
Created #5522 

I left the checklist items around compile/test/README empty, as those shouldn't be affected by the changes.

It creates the following Docker tags:

 - Scratch
    - ethereum/solc:stable
    - ethereum/solc:0.5.1
    - ethereum/solc:nightly
    - ethereum/solc:nightly-0.5.1-bc7cb301e3d71756c8fbefe888aca53433302117
 - Alpine
    - ethereum/solc:stable-alpine
    - ethereum/solc:0.5.1-alpine
    - ethereum/solc:nightly-alpine
    - ethereum/solc:nightly-alpine-0.5.1-bc7cb301e3d71756c8fbefe888aca53433302117
