### ISSUE TITLE
Feature Request: Events in function signatures (or, checked events)

### ISSUE THREAD

**Issue by moodysalem** [ethereum/solidity#5461]
## Abstract

Problem: I am writing an interface with events, and I want to make sure any implementations emit an event upon successful invocation

Solution: Allow me to describe events that should be emitted in the function signature

## Motivation

This will enforce at compile time that a function emits an event or throws, allowing for the interface to be a more complete specification of the contract

The information can be emitted in the ABI, though I don't have a great use case for the client except that partial ABIs can be provided that describe more side effects of the function

## Specification

before
```solidity
interface Registry {
  event LogRegister(address sender, string name, uint256 vendorId);

  function register(string name) external 
    returns (uint256 vendorId);
}
```
after
```solidity
interface Registry {
  event LogRegister(address sender, string name, uint256 vendorId);

  function register(string name) external 
    returns (uint256 vendorId) 
    emits (LogRegister(msg.sender, _, vendorId));
}
```

## Not scoped

This specification doesn't work for a variable number of events to be emitted-that would need some sort of looping syntax which seems too complicated.

## Backwards Compatibility

This is backwards compatible-the optional addition to the function signature just enforces a compile time check of contracts implementing the interface

**Comment by chriseth** [comment]
Sounds like a good extension of the interface concept!

Would someone be willing to write a specification of an existing interface (like ERC20) in this way?

**Comment by erak** [comment]
@chriseth How could such a specification look like? Does that mean one could take e.g. https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md and then change the function signatures such that they follow this concept?

**Comment by chriseth** [comment]
@bit-shift yes, exactly

**Comment by chriseth** [comment]
Discussion in the team resulted in this being too underspecified and probably not be too useful in the end (does the event have to be emitted in all cases? Can you really not change the arguments? ...). Please re-open with a better specification and examples if you want this implemented.
