### ISSUE TITLE
Address payable to address conversion fails for memory arrays.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#5462]
``address [1] memory accounts = [ address(0) ];`` should work, but fails to compile. (Thanks for reporting @yann300).

```
contract C {
  function f() {
    address [1] memory accounts = [ address(0) ];
  }
}
```

````
Error: Type address payable[1] memory is not implicitly convertible to expected type address[1] memory.
 --> 5462.sol:3:5:
  |
3 |     address [1] memory accounts = [ address(0) ];
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````

**Comment by chriseth** [comment]
I think that in general, array types of elementary types that are convertible are not convertible. The reason behind is that the conversion, even if possible, might require actual code for the conversion or different storage layout. For example, even though `unit8` is convertible to `uint16`, a storage array of `uint8[]` is not convertible to `uint16[]`. So if we want to allow the example in the issue, we have to make a more detailed distinction.

**Comment by chriseth** [comment]
Note that `address(0)` is an `address payable`.

**Comment by ekpyron** [comment]
Yes, but in the case of ``address`` and ``address payable`` there won't be any need for a conversion, so we could allow this. In contrast to other base types there is no way to explicitly convert ``address(0)`` to ``address`` (the non-payable kind), so there is no way to initialize a non-payable address array with a constant address - that's an unnecessary limitation that we could fix by making an exception for ``address payable``-arrays and allowing (implicit) conversions to ``address``-arrays.
