### ISSUE TITLE
Latest v0.4.25 version is marked as a nightly

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/solidity#5463]
## Description

The release version of v0.4.25 is declared as a pre-release and contracts don't compile.

## Environment

- Compiler version: v0.4.25
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: OS X, but doing this in `python:3.6` docker image

## Steps to Reproduce

I'm installing the Solidity compiler with the following command:

```bash
git clone --recursive -b release https://github.com/ethereum/solidity
cd ./solidity
git checkout tags/v0.4.25
cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=0 -DSTATIC_LINKING=1
make solc && install -s solc/solc /usr/bin
```

When compiling the following file:

```
pragma solidity ^0.4.25;

contract ReadBool {
    bool public flag;

    function read_bool() public constant returns (bool) {
        return flag;
    }
}
```

`solc` complains with the following error:

```
Warning: This is a pre-release compiler version, please do not use it in production.
E           <stdin>:1:1: Error: Source file requires different compiler version (current compiler is 0.4.25-develop.2018.11.21+commit.59dbf8f1.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
E           pragma solidity ^0.4.25;
E           ^----------------------^
```

As you see the commit matches the release version 0.4.25 as listed [here](https://github.com/ethereum/solidity/releases):

![image](https://user-images.githubusercontent.com/224585/48821089-acd79480-ed0c-11e8-9933-4caab211df97.png)

Any thoughts that could help me resolve this? Appreciate it!

**Comment by chriseth** [comment]
Custom source builds are always tagged as "prerelease", unless a special empty file called "prerelease.txt" is present. This file is included in the tar gz file that is attached to the release, but it is not present in the git source tree. Please use https://github.com/ethereum/solidity/releases/download/v0.4.25/solidity_0.4.25.tar.gz when compiling.
