### ISSUE TITLE
YUL optimizer: Out-of-range exception thrown by FullInliner

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5465]
## Description

The Full Inliner YUL optimization throws a `std::out_of_range` exception for the code below

```
{
{
function f(x) {
			}

		f(180)
	}
}
// 
```

The exception is thrown at `libyul/optimiser/FullInliner.h:82`

```cpp
FunctionDefinition& function(YulString _name) { return *m_functions.at(_name); }
```

- `m_functions` at this point is an empty map from which we are trying to index a key called `_name`
- This leads to the `'std::out_of_range' exception

which is called from

```cpp
bool FullInliner::shallInline(FunctionCall const& _funCall, YulString _callSite)
{
	// No recursive inlining
	if (_funCall.functionName.name == _callSite)
		return false;

	FunctionDefinition& calledFunction = function(_funCall.functionName.name);
...
```

## Environment

- Compiler version: develop commit `d3f66ca0`
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 16.04

## Steps to Reproduce

- Run `yulopti` as shown
- Select `i` (fullinliner) in the interactive step

```
$ yulopti --input-file <yul_code_shown_above>
----------------------
{
{
function f(x) {
                        }

                f(180)
        }
}
// 
(q)quit/(f)flatten/(c)se/propagate var(d)ecls/(x)plit/(j)oin/(g)rouper/(h)oister/
  (e)xpr inline/(i)nline/(s)implify/(u)nusedprune/ss(a) transform/
  (r)edundant assign elim./re(m)aterializer?  i
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

**Comment by ekpyron** [comment]
I can reproduce this and will look into it, thanks for reporting.

**Comment by ekpyron** [comment]
Actually the function inliner requires the function hoister to be run in advance - and if you do that interactively, the exception will not be thrown - so this can probably not be considered a bug in the FullInliner, but we should probably still deal with such dependency issues in yulopti somehow...

EDIT: just double checked with @chriseth and not running the dependencies for optimizer steps should still not result in assertions, so I'll consider it a bug in ``FullInliner`` after all and will see about fixing it there.
