### ISSUE TITLE
Clean up unary +

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5470]
## Abstract
Unary ``+`` was disallowed, but there's still some more clean up necessary.

## Motivation
Usage of unary ``+`` is now handled by the syntax checker, but it's still present in the type system.

## Specification
``SyntaxChecker::visit(UnaryOperation const&)`` reports an error if it detects the usage of unary ``+``. But, e.g. ``IntegerType::unaryOperatorResult()`` still allows using it. This should be cleaned up.

**Comment by axic** [comment]
As long as it is accepted by the parsers I'd say the check belongs to `SyntaxChecker` and nowhere else.

**Comment by erak** [comment]
@axic Yes, that makes sense. I updated the description accordingly.
