### ISSUE TITLE
Upgrade Boost to 1.68 in emscripten

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5475]
Recently we've upgraded our boost dependency to 1.67 in the Emscripten build. This version was used, because the PR was made during summer and 1.67 was the last release then (released in April).

In August 1.68 was released and it seems it may have some relevant fixes:
- Fix bug in cpp_int where incrementing to zero doesn't set the sign correctly.
- Remove erroneous use of std::move, and rely on NVRO instead.
- Fix compatibility issue with GCC-8 caused by the introduction of std::byte.

(Also relevant #4612)

**Comment by axic** [comment]
@ekpyron @chriseth @christianparpart any comments on doing this update?

**Comment by ekpyron** [comment]
@axic In general, we should already be compatible with boost 1.68 - If I recall correctly, there were some minor issues, but they have already been fixed - the archlinux test runs are already testing against boost 1.68 and there are no issues with them that I'd be aware of.
With respect to emscripten I think the next and more important step should be to merge #4441 and after that to consider updating the emscripten version further to the current upstream release. It may be that an updated emscripten version is even required for updating boost to 1.68 - it might also be that we could update boost before updating emscripten any further, we'd have to check.

In any case: personally I'd say merging #4441 is more important and we should focus on that first (and #4441 is basically blocked by the lack of your approval only @axic ;-)) - but updating to boost 1.68 makes a lot of sense as well - I can check whether it'll cause issues this or next week.

**Comment by ekpyron** [comment]
I just checked in #5738: it seems that updating to boost 1.68 for the emscripten build works just fine already on circleci (so we don't need to update emscripten first). I have to brush up #5738 a bit to bring it to a mergeable state, but I don't see a reason for not going ahead with this.

**Comment by chriseth** [comment]
@ekpyron can this be closed?
