### ISSUE TITLE
Remove structural gas estimation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5480]
Structural gas estimation (used by the AST output) provides gas information for each instruction in the source. It is currently the only component that relies on the old control flow graph module and cannot really handle many branches and is also completely broken on some inputs:
```
contract UnreachableSourceVertexTest {
    event Error(string message);

    function erroneous(bool condition, string memory message) public payable {
        if (!condition) {
            error(message);
        }
    }

    function error(string memory message) public payable {
        emit Error(message);
        revert();
    }
}
```

An earlier attempt at removing the control flow graph from structural gas estimation in https://github.com/ethereum/solidity/pull/4058 had the drawback that this reduces the accuracy of structural estimation.

We might want to get rid of structural estimation altogether, until we find a better, probably yul-based method.

**Comment by chriseth** [comment]
It's probably better to remove this module and rely on external components that use better heuristics to show which parts of the source consume a lot of gas.

**Comment by cameel** [comment]
Was it actually a breaking change? It just went into 0.7.3...

**Comment by chriseth** [comment]
No, it was unused.
