### ISSUE TITLE
[SMTChecker] Move Symbolic* to namespace smt

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#5484]

**Comment by axic** [comment]
I'd say move most of the SMT stuff under `smt`.

The `Z3Interface` already is...

**Comment by leonardoalt** [comment]
Yes, the solver interfaces and sorts are already in the `smt` namespace.
I guess `SymbolicVariables` and `SymbolicTypes` could follow.
I'm not sure about `SMTChecker` itself.
