### ISSUE TITLE
Assembly: cannot access variables within modifier

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#549]
Inline assembly within modifiers doesn't seem to be able to access variables:

```
    modifier xy {
        uint a;
        assembly {
            a := 1
        }
    }
```

Error: `Error: Identifier "a" not found, not unique or not lvalue.`

**Comment by axic** [comment]
The problem here is that the variables are not marked `isLocalVariable` when inside modifiers.

**Comment by chriseth** [comment]
Ah nice! So I think the dynamic cast there should be changed to `CallableDeclaration` (this also includes events, but I don't think we will add internal variables or inline assembly to events soon).

**Comment by axic** [comment]
You mean here: https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/TypeChecker.cpp#L618?
