### ISSUE TITLE
Only use AbstractAssembly in AsmCodeGen

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#5495]
AsmCodeGen.cpp uses evmasm::Assembly, even though it is in the yul namespace. The evmasm::Assembly is immediately converted to a subclass of AbstractAssembly via the EthAssemblyAdapter. I think the EthAssemblyAdapter should be moved to e.g. the evmasm namespace (inside libevmasm) and then used from the site that calls AsmCodeGen, so that AsmCodeGen just receives an AbstractAssembly instance.

**Comment by axic** [comment]
This link seems to be broken.

**Comment by christianparpart** [comment]
that's a bug in the github UI. I just clicked a button. will extend that with the proper text (on Monday I guess).

**Comment by chriseth** [comment]
Updated the description.

**Comment by axic** [comment]
@christianparpart `AbstractAssembly` depends on `evmasm::Instruction`. There seems to be a lot of cross-referencing here.

**Comment by axic** [comment]
Lately a few changes were merged to reduce interdependency (mostly to reduce dependency on libevmasm from within libyul), however there is a PR which does the converse, adds dependency on libyul from libevmasm. That would be the first instance, and it is not merged yet.

It seems we cannot remove dependency on libevmasm anytime soon from libyul, so I would argue that making this dependency bidirectional is a bad idea and that this current issue is a bad idea too in the current situation.
