### ISSUE TITLE
Why is the byte cast MSB order and uint is LSB order?

### ISSUE THREAD

**Issue by JamesANZ** [ethereum/solidity#5496]
Been using smart contracts to take uint values and cast them into a large custom length byte variable.

Noticed that when you do a bitshift operation on a byte variable it will take the most significant byte first (strange it itself) but that uint variables will take the least significant byte (normal behaviour)

Why does this happen in solidity? Is this an intended feature or a bug?

**Comment by leonardoalt** [comment]
Hi @James-Sangalli ,
By design `uint` and `bytesX` types pad/truncate on the opposite ends.

**Comment by chriseth** [comment]
@James-Sangalli We do not yet fully understand the issue. Could you provide example code, please?

**Comment by JamesANZ** [comment]
@chriseth doing bitwise operations like so will be reversed in bytes.

e.g. byte(0xeeff >> 8) will grab the first two bytes (ee), 0xeeff >> 8 as a uint will get ff

I see that this is not actually an issue as it is a design decision, was just confused before

**Comment by chriseth** [comment]
If this is really the case, it sounds like a bug. Could you please post complete source code? Currently, I cannot reproduce the uint behaviour you mention.
