### ISSUE TITLE
msg.origin is not available?

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#550]
`msg.sender` seems to refer to the `CALLER` opcode and `msg.origin` (aka `ORIGIN`) is not-existent. Cannot find any reference in the docs regarding it. Is it missing or is named differently?

It can be workarounded with assembly though:

```
    function origin() internal returns (address ret) {
        assembly {
            ret := origin()
        }
    }
```

**Comment by axic** [comment]
Found it! 😃 

Any reason `origin` and `gasprice` are in `tx`, while the rest in the `msg` structure?

**Comment by VoR0220** [comment]
I'm not certain why that was decided. @chriseth can answer that...might be interesting. Closing in the interim.

**Comment by axic** [comment]
Maybe it shouldn't be closed before it is answered? :)

**Comment by VoR0220** [comment]
well it's not really an issue, is it?

**Comment by axic** [comment]
What is considered an _issue_?  Only bugs?

Strictly speaking `msg.origin` is not available.

**Comment by axic** [comment]
Constructively speaking I'm not sure how (if at all) `msg` and `tx` should be split.

From the docs:
- `msg.data`(bytes): complete calldata
- `msg.gas` (uint): remaining gas
- `msg.sender` (address): sender of the message (current call)
- `msg.sig` (bytes4): first four bytes of the calldata (i.e. function identifier)
- `msg.value` (uint): number of wei sent with the message
- `tx.gasprice` (uint): gas price of the transaction
- `tx.origin` (address): sender of the transaction (full call chain)
- `this` (address): address of the current contract

In comparison a transaction has the following fields (let's call this `rawTx`):
- `nonce`
- `gasPrice`
- `gasLimit`
- `recipient address`
- `value`
- `data`
- `r` / `s` / `v` (signature)

The opcodes in the EVM don't fully match these, some are block and some are tx level:
- `gas` gas still available to execution (= `rawTx.gasLimit` minus what was already spent)
- `address` address of the current contract / execution context (= `rawTx.recipient`)
- `caller` call sender (excluding delegatecall)
- `callvalue` wei sent together with the current call (= `rawTx.value`)
- `origin` transaction sender (calculated based on `rawTx.r/s/v`)
- `gasprice` gas price of the transaction (= `rawTx.gasPrice`)
- `blockhash(b)` hash of block nr b - only for last 256 blocks excluding current
- `coinbase` current mining beneficiary
- `timestamp` timestamp of the current block in seconds since the epoch
- `number` current block number
- `difficulty` difficulty of the current block
- `gaslimit` block gas limit of the current block

Based on this we're lacking `nonce` and `gasLimit` from `rawTx` in EVM.

As you see it is not trivial how to (if at all) split `msg` and `tx`.

I guess it is split based on how `CALL` operates. `msg` is the call parameters, while `tx` is the parent transaction.

**Comment by chriseth** [comment]
@axic what is this about, especially the listing in your previous comment?

**Comment by VoR0220** [comment]
@chriseth I think he's asking why is there a split between tx and msg...are they not the same thing?

**Comment by axic** [comment]
I think I've understood the reason behind that: `msg` is the local context as part of the `CALL` recipient, which can be an inter-contract call, while `tx` contains the transaction which initiated the chain. Well, `tx` dones't contain all fields, only those which aren't part of `msg`.

What is still confusing that the naming doesn't really match neither the protocol or EVM naming.

**Comment by chriseth** [comment]
it matches the de-facto standard serpent defined at that time

**Comment by chriseth** [comment]
Is the question answered?
