### ISSUE TITLE
Make include resolution blazing fast

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5505]
There should be an option to perform "include resolution only" - it might be that not selecting any output could already do that, but I think it will still do type checking. It might also be that if any include fails, we do not do anything at all.

Task of this issue:
 - check that truffle (and other framework)'s include resolution is as fast as it gets.

**Comment by sea51930** [comment]
@chriseth 

_從我的 Desire 830，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_
