### ISSUE TITLE
Fedora is not recognized by the `install_deps.sh` script

### ISSUE THREAD

**Issue by corollari** [ethereum/solidity#5512]
## Description

Fedora is not recognized by the `install_deps.sh` script.

## Environment

- Operating system: Fedora 29

## Steps to Reproduce

On a Fedora 29 install, run the following code from the terminal:
```
./scripts/install_deps.sh
```

Output should be:
```
Installing solidity dependencies on Fedora.
...
```

Output is:
```
ERROR - Unsupported or unidentified Linux distro.
See http://solidity.readthedocs.io/en/latest/installing-solidity.html for manual instructions.
If you would like to get your distro working, that would be fantastic.
Drop us a message at https://gitter.im/ethereum/solidity-dev.
```

**Comment by chriseth** [comment]
Thanks for letting us know! Would you be able to extend the script so that it works for Fedora?

**Comment by chriseth** [comment]
Ah sorry, only saw the pull request just now :)
