### ISSUE TITLE
Move examples from ethereum.org to documentation

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5521]
ethereum.org is being re-designed and aims to rather be an information hub than an actual provider in the future. Did I phrase this correctly @alexvandesande? We could move all Solidity examples from there (https://www.ethereum.org/greeter, https://www.ethereum.org/dao and such) to our documentation. I can already identify a few benefits / disadvantages:

Benefits:
- The examples would probably get lost otherwise
- We have the code under control could remove the (unperceived) dependency

Drawbacks:
- Examples would probably not look that fancy ;)

**Comment by ChrisChinchilla** [comment]
Started looking into these, and they need some polish, and maybe changes in approach to make them truly "getting started". If we take them over, we need to consider a couple of things:

- Who will take them over, especially as they involve other projects in addition to Solidity.
- If we do, I think it's best we split each one out to an example, which needs #5396 first

**Comment by axic** [comment]
Since ethereum.org was overhauled none of those examples exist anymore.
