### ISSUE TITLE
Cannot import from parent directory

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#553]
I and another of my coworkers have discovered a bug on OS X for import statements:

I tried this:

```
import "./../contract2.sol";

contract contract3 is contract2 {}
```

and this:

```
import "../contract2.sol";

contract contract3 is contract2 {}
```

and even this:

```
import "..contract2.sol";

contract contract3 is contract2 {}
```

edit: also tried this:

```
import ".././contract2.sol"

contract contract3 is contract2 {}
```

for a contract2.sol file in the directory above the one contract3.sol is currently resting in...refuses to link. Investigating. 

FTR: references to all imports inside of the a working directory work. So do references to directories further down. It's simply an inability to reference imports from a parent directory.

**Comment by chriseth** [comment]
Please also explain how you call the compiler, this is very relevant.

**Comment by VoR0220** [comment]
the compiler is called like such

```
solc contract3.sol
```

from there it should search for the file.
