### ISSUE TITLE
Optimizer: Provide simplification rules as strings

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5542]
Most of the rules like `{{Instruction::SDIV, {X, 1}}, [=]{ return X; }, false}` and `{{Instruction::MOD, {X, 0}}, [=]{ return u256(0); }, true},` can be given as strings:

```
SDIV(X, 1) -> X
MOD(X, 0) -> 0
```

which improves readability but also allows external people to add new rules even to an already existing compiler binary.

This would also allow an automated SMT-backed check that the rule is correct.

One we can check the correctness of these rules, we could even perform an exhaustive search for all correct rules that shorten the code.

**Comment by ekpyron** [comment]
Personally, I'd rather write them as equalities ``SDIV(X, 1) = X`` - in theory it would be cool if the rules were actual syntactically valid yul expressions, that always evaluate to true, if the rule is correct, but unfortunately that'll probably not work all that well in practice... in any case the advantage of an equality is that it makes the proof-objective that needs to be verified for the rule clearer - and it's how e.g. simplification rules would be written in Isabelle.

**Comment by axic** [comment]
Closing this in favour of the discussion in #7520.
