### ISSUE TITLE
It seems currently impossible to override a "function"

### ISSUE THREAD

**Issue by niklasb** [ethereum/solidity#5555]
## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by chriseth** [comment]
Thanks for opening this issue! Could you please provide some example code that you expect to compile correctly but that does not?

**Comment by chriseth** [comment]
I guess this is a duplicate of #5556
