### ISSUE TITLE
Overriding functions with variable getters is not allowed

### ISSUE THREAD

**Issue by niklasb** [ethereum/solidity#5556]
Solidity version: 0.5.0

Interfaces are a very useful concept in Solidity, however there is currently a restriction as to how a function defined in an interface can be implemented in a derived contract. As expected, we can define a function with the same signature:

```
pragma solidity ^0.5.0;
interface X { function test() external returns (uint256); }
contract Y is X {
    function test() public returns (uint256) { return 42; }
}
```

But defining an implicit getter function with the correct signature does not work against reasonable expectations:

```
pragma solidity ^0.5.0;
interface X { function test() external returns (uint256); }
contract Y is X {
    uint256 public test = 42;
}
```

Trying to deploy this contract fails with the error message: "This contract may be abstract, not implement an abstract parent's methods completely or not invoke an inherited contract's constructor correctly". 

This behaviour seems unintended and restricts the usefulness of interfaces in Solidity.

**Comment by chriseth** [comment]
Thanks for reporting! If we are lucky, then this can still be part of the release on Monday.
