### ISSUE TITLE
Add tests for libsoljson

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#556]
The methods are defined in solidity/solc/jsonCompiler.c:

```
extern char const* compileJSON(char const* _input, bool _optimize);
extern char const* compileJSONMulti(char const* _input, bool _optimize);
extern char const* compileJSONCallback(char const* _input, bool _optimize, CStyleReadFileCallback _readCallback);
```

This is the interface used by https://github.com/ethereum/solc-js.

**Comment by chriseth** [comment]
Do you propose to add tests written in C++ to check that the functions above work correctly by building a non-emscripten build and running those tests?
Wouldn't it be better to test the emscripten build directly?

**Comment by axic** [comment]
I think both should be done so issues within either the C++ API or the emscripten process can be spotted:
- C++ tests in the solidity tree for the `jsonCompiler` API should be straightfoward
- Tests for the emscripten build should be done separately - where does that belong to? solc-js? solc-bin?
- And lastly tests for the `solc` npm package wouldn't be a bad thing

**Comment by chriseth** [comment]
The required changes inside this repository have been made - the fuzz tester now tests soljson.
