### ISSUE TITLE
How to transfer ether from account to another account?

### ISSUE THREAD

**Issue by CrisChr** [ethereum/solidity#5564]
## Description

I created a contract in Remix:
![image](https://user-images.githubusercontent.com/38416380/49339043-81d33600-f666-11e8-988a-bcd467d975c6.png)

but when i execute _transferCoin()_ function, error consoled:
![image](https://user-images.githubusercontent.com/38416380/49339096-92d07700-f667-11e8-92ea-440eeba1a34a.png)

I was really confused that I executed _addFund()_ to add amount to the current _msg.sender_, but why can not transfer to another account?

By the way, 
1. what is **msg.value** and how to use it?
2. when transfer ether from account to another account (_not from a contract to another contract_), **msg.sender.transfer(uint)** or **addrss(this).transfer(uint)** or **anothre_account_address.transfer(uint)**? which one?

Thanks

**Comment by axic** [comment]
This question is to better to be asked on https://ethereum.stackexchange.com
