### ISSUE TITLE
[SMTChecker] Run smoothly on Zeppelin ERC20

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#5566]
- [x] Mapping access #5388 
- [x] Bound functions #5309 
- [x] Type conversion from Rational to Address #5717 
- [x] Do not report overflow/underflow if all overflow/underflow paths revert #5999

**Comment by axic** [comment]
Can you post the simplified token code here?

**Comment by leonardoalt** [comment]
At some point I had a PR adding it as an SMTChecker test but since it has division I closed it. Will post it here as a comment.
