### ISSUE TITLE
Compiler feature: Output AST even if there are some errors

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5577]
Is that compatible with standard-json?

**Comment by ekpyron** [comment]
Maybe, more generally, it should be possible to request parsing, analysis and compilation separately via standard json?

**Comment by yxliang01** [comment]
+1

**Comment by chriseth** [comment]
The AST should be generated even if there are missing input files (#5735)

**Comment by chriseth** [comment]
Implemented with "stop after ast".
