### ISSUE TITLE
Segfaults everywhere...end to end tests ceasing to function on smoke test OSX

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#558]
I've been resetting my branch to the latest in origin and for whatever reason it is refusing to work on any contracts I deploy. The end to end tests in the soltest are not working. Big big big problem. Running on OS X El Capitan.

**Comment by bobsummerwill** [comment]
Ouch.   Do you have access to a Windows or Linux box to see if there is a chronic multi-platform failure?
Or a different OS X box?

**Comment by VoR0220** [comment]
Running off my own machine. I could try to docker it up again.

**Comment by VoR0220** [comment]
weird...I put it in the sanitize mode...no seg faults...just horrendously slow.

**Comment by VoR0220** [comment]
...now I've put it back...it works perfectly fine. So strange. Alright. Closing for now.
