### ISSUE TITLE
struct in external function not compile

### ISSUE THREAD

**Issue by aihuawu** [ethereum/solidity#5581]
contract C
 struct A {
    uint256 id;
 }

  function f(A memory a) external {

  }
}
If I change external to public, it compiles.
But it doesn't work for external

**Comment by leonardoalt** [comment]
Hi @aihuawu , thank you for reporting!
Could you please give some more information, for example your compiler version and the error you get?
Note: in Solidity >=0.5.0, parameters of non-value type must have location `calldata` in external functions.
Note 2: you need `pragma experimental ABIEncoderV2` to use structs as a parameter of public/external functions .
Note 3: if I'm not mistaken this is not implemented yet.

**Comment by aihuawu** [comment]
Hi, leonardoalt


pragma solidity ^ 0.4.25;
pragma experimental ABIEncoderV2;
pragma experimental "v0.5.0";

It says it is not implemented.

Unimplemented feature:
/build/solc-8UojSd/solc-0.4.25/libsolidity/codegen/ABIFunctions.cpp(1268): Throw in function std::__cxx11::string dev::solidity::ABIFunctions::abiDecodingFunctionStruct(const dev::solidity::StructType&, bool)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::UnimplementedFeatureError>
std::exception::what: 
[dev::tag_comment*] = 


I am using interface which must be external instead of public. So I can't use public.
It would be nice if it can be implemented.

George Wu

**Comment by aihuawu** [comment]
If it is not implemented, then if I want to pass struct between contract, what should I do?

**Comment by leonardoalt** [comment]
Unfortunately for now you can't receive a `calldata` struct (in an `external` function).

If you are looking for workarounds it's better to ask https://ethereum.stackexchange.com/ or https://gitter.im/ethereum/solidity.

Closing since the requested feature already has an issue: https://github.com/ethereum/solidity/issues/1603

**Comment by leonardoalt** [comment]
@aihuawu Maybe one thing that might help is, in Solidity 0.5.1 you can have a non-implemented interface external function that takes a `calldata` struct (which compiles) and override it in your contract with a public function that takes a `memory` struct.
