### ISSUE TITLE
Emscripten builds are not minimized anymore (solc-bin)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#559]
In [solc-bin](https://github.com/ethereum/solc-bin) starting from soljson-v0.3.2-2016-05-03-aa4dcbb.js the output is not minimized. This means the file size is ~34Mb as opposed to ~7Mb.

Side note: maybe it would make sense enabling _issues_ in the solc-bin repo to file reports like this there.

**Comment by chriseth** [comment]
Fixed now.
