### ISSUE TITLE
Unhelpful error message for abstract contracts

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#5590]
## Description

Hi, I would suggest that the error message for attempting to compile an abstract contract be improved.  When I attempted to compile a contract I had accidentally made abstract, I got an error message me telling me that the compiled contract was not found; I thought this was a bug in `solc` until I realized I had accidentally made my contract abstract!  An error message explicitly mentioning abstract contracts would be more helpful; then I would have known right away that there was an abstract contract involved.

Thank you!

**Comment by erak** [comment]
@haltman-at Thanks for reporting this! I think we could probably warn about abstract contracts being used in the inheritance hierarchy. We would need to discuss that in more detail, though.

**Comment by chriseth** [comment]
The main problem here is that there is no way to tell whether you actually want to compile the contract or if you just want to define it to be used as base contract. Currently, I only see something like an explict `abstract` keyword as a solution.

**Comment by axic** [comment]
We have agreed on implementing #649 for the next breaking release. Closing this issue as it will be solved by that.

**Comment by flymauntains** [comment]
I think because of function's inheritance problem.
The problem generates when contract code is not use all functions of interface.
![Screenshot 2024-06-28 175922](https://github.com/ethereum/solidity/assets/172695995/43d18289-37cf-48ff-b5da-98dd7f845549)
