### ISSUE TITLE
YUL optimizer: Out-of-range exception thrown by VarDeclPropagator

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5597]
## Description

The VarDeclPropagator YUL optimization throws a `std::out_of_range` exception for the code below

```
{
  function f() -> a, b, c {}
  let x, y, z 
  z, x, x := f()
}
// -x }
```

The exception is thrown at `libyul/optimiser/VarDeclPropagator.cpp:121`

```cpp
variables.emplace_back(move(m_lazyInitializedVarDecls.at(varName.name)));
```

- `m_lazyInitializedVarDecls` (maps `YulString` to `TypedName`) at this point is an empty map from which we are trying to index a key called `varName.name`
- This leads to the `'std::out_of_range` exception

The bug is local to `VarDeclPropagator::recreateVariableDeclaration` function which is called within a lambda function called `iterateReplacing` on line 58 of the faulting source file.

## Environment

- Compiler version: develop commit `1e6c368bb`
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 16.04

## Steps to Reproduce

- Run `yulopti` as shown
- Select `d` (vardecl) in the interactive step

```
$ yulopti --input-file <yul_code_shown_above>
----------------------
{
  function f() -> a, b, c {}
  let x, y, z 
  z, x, x := f()
}
// -x }

(q)quit/(f)flatten/(c)se/propagate var(d)ecls/(x)plit/(j)oin/(g)rouper/(h)oister/
  (e)xpr inline/(i)nline/(s)implify/(u)nusedprune/ss(a) transform/
  (r)edundant assign elim./re(m)aterializer/f(o)r-loop-pre-rewriter?  d
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

**Comment by chriseth** [comment]
Closing since the var decl propagator is being removed.
