### ISSUE TITLE
Introduce tx.gasrefund (uint): gas that will be refunded if the transaction is successful

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#560]
Problem explanation is here:
http://ethereum.stackexchange.com/questions/3860/how-to-know-inside-the-contract-function-the-amount-of-gas-that-will-be-refund

**Comment by axic** [comment]
I do not think there is an opcode in the EVM to read the refund counter.

**Comment by chriseth** [comment]
Yes, this is very hard to do because the EVM provides no help there and internal calls could result in refunds, but we have no way to access that.
