### ISSUE TITLE
Natspec in example contracts

### ISSUE THREAD

**Issue by corollari** [ethereum/solidity#5603]
## Description

Is there a reason why the example contracts provided in the documentation don't use NatSpec? I mean, has there been a decision to not use NatSpec on these contracts due to it not being a good fit for these cases or the reason is that simply nobody has written the natspec comments?

As these example contracts are used in other places like the remix IDE (See ethereum/remix-ide#1632 for the downstream issue that led to the creation of this one) it's pretty common for them to end up being the first contract new developers see.

**Comment by chriseth** [comment]
Some of them do, but we might just have been too lazy for some. For others, natspec would clutter and distract from the things people should actually focus on. If you want to add natspec to some examples, please feel free to do so!

**Comment by corollari** [comment]
Thanks! I'll submit a PR adding natspec for some then.
