### ISSUE TITLE
[Yul] Optimizer should take movability of functions into account

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5608]
For builtin functions as well as user-defined, the optimizer should determine whether the function is movable and take that into account in the MovableChecker.

Note that if function calls are moved, the function they reference might be out of scope at the target. This means that the function hoister might be a new requirement for all stages that move calls to user-defined functions.

**Comment by ekpyron** [comment]
Do you think it might make sense to determine movability not only on the level of functions, but on the block and/or statement level instead (a function being movable, if it's body is movable; a block being movable, if all statements are movable)?

**Comment by chriseth** [comment]
We currently do not have a use for that yet, but what might be useful soon is the fact whether a Block modifies storage, especially a branch in an `if`.

**Comment by chriseth** [comment]
Has been implemented in #7251
