### ISSUE TITLE
Allow assignment of overloaded function pointers to function variables

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#5609]
## Abstract

Currently, it's impossible to assign an overloaded function to a function variable; the compiler complains that it cannot resolve the identifier.  This should be allowed, with resolution depending on the type of the variable.

(I know there are several issues on here related to overloading already... I think this is a new one, though!  Not sure whether this was a bug or a feature request, but I decided to put it down as a feature request.  Thank you!)

**Edit**: Sorry, I only realized while writing this that there's a problem here -- the implicit conversion rules for functions are too strict to allow what I want except in case of identical parameter types.  So, this request has a problem.  But, perhaps it could at least be allowed in that restrictive case of identical parameter types.  Thank you!

## Motivation

Here's a simplified example:

```
contract OverloadTest {

  function overloaded(uint x) public {}
  function overloaded(address x) public {}

  function overloadTest() public {
    function (uint) internal over1i;
    function (address) internal over2i;
    function (uint) external over1e;
    function (address) external over2e;
    over1i = overloaded;
    over2i = overloaded;
    over1e = this.overloaded;
    over2e = this.overloaded;
  }
}
```

Attempting to compile this yields the error `TypeError: No matching declaration found after variable lookup.`

## Specification

When an overloaded function name is assigned to a function variable, overload resolution should be invoked here based on the type of the variable that is being assigned to.  That is to say, we consider the input parameter types of the type of the variable, and perform overload resolution on the overloaded function as if it were being called with those types as the types of the input parameters.  The result can then be assigned to the variable (or result in a compile error, if it's incompatible in other ways, such as having incompatible return parameter types).   This should occur both for internal functions and internal function variables, and for external functions and external function variables.  So, in the above example, `over1i` would get the overload for `uint` input, and `over2i` would get the overload for `address` input; and similarly with the external analogues.

For a slightly less trivial example, if one were to write
```
function (uint8) internal over3i;
over3i = overloaded;
```
then `over3i` would be assigned the overload for `uint` input, as that's the overload that would be called if `overloaded` were called on `uint8` input.  **Edit**: Actually, this can't work at present, because the `function (uint) internal` is not presently implicitly convertible to `function (uint8) internal`.  It ought to be, but that's a separate feature request.  Oh well.  I guess only the trivial case can work at the moment.

While if one were to write
```
function (uint) internal (returns uint) over4i;
over4i = overloaded;
```
then a compile error should result, as resolving the overload results in a value of type `function (uint) internal`, which cannot be implicitly converted to type `function (uint) internal (returns uint)`.  (**Edit**: And shouldn't be able to be so converted!)

Further assignments involving a variable that has been assigned to in this way, or other uses of that variable, would then not require any further resolution; it's just the initial overloaded identifier that requires resolution.

Note that the above specification only covers assignments, and not more complicated expressions; but at the moment, if I'm not mistaken, the only things one can do with function values are A. invoke them (overloading resolution is already performed for that), B. store them (I'm asking that it be performed for this too), or C. attach `gas` or `value` to them (which doesn't much change matters, and currently the resulting functions can't be stored anyway).  So, I don't see this limitation as a problem.

## Backwards Compatibility

Since this solution only requires resolving an overload and then storing the result of the resolution in a function variable, in its usual representation, and doesn't require coming up with some new representation for function variables, there should be no backwards-compatibility issues.

**Comment by chriseth** [comment]
I'm sorry, I know this is very useful, but we currently have no place in the language where the type of a right hand side is modified by the type of a left hand side during assignment. Changing that could result in many complications and misunderstandings.

**Comment by haltman-at** [comment]
I see, oh well. Thank you anyway!  Maybe eventually this will become possible, who knows.
