### ISSUE TITLE
Add warning message for Interface and Abstract contract for bytecode as 0x

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#5611]
## Abstract
While compiling abstract contracts as well as interfaces, the bytecode is 0. Can you please add warning message as it is sometimes confusing. If I am using truffle, I have no clue that the bytecode in .JSON file is 0x

## Motivation
This will give developer clear idea about the bytecode is going to be 0x for interface and abstract contract

## Specification
None

## Backwards Compatibility
None

Please describe how you propose to deal with these incompatibilities.
None

**Comment by chriseth** [comment]
The main problem here is that the compiler does not know if you intend to deploy the contract or just use it as an abstract base contract. This can be solved by requiring the abstract keyword ( #649 ). What do you think?

**Comment by chriseth** [comment]
Closing in favour of #649
