### ISSUE TITLE
Assembly output should use PUSHnn (similarly to the opcodes output)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#564]
Both 

```
contract A {
  function a() {
    string memory x = "\x12\x00\x44";
  }
}
```

and 

```
contract A {
  function a() {
    string memory x = "\x00\x12\x00\x44";
  }
}
```

get compiled as `PUSH32 0x1200440000000000000000000000000000000000000000000000000000000000`.

Any number of leading zeroes can be added via escape characters. As evidenced by the AST, the escape character is parsed by solc:

```
                                                {
                                                    "attributes" : 
                                                    {
                                                        "string" : "null",
                                                        "type" : "literal_string \"\u0000\u0012\u0000D\"",
                                                        "value" : "\u0000\u0012\u0000D"
                                                    },
                                                    "name" : "Literal"
                                                }
```

**Comment by axic** [comment]
Retested this with: 0.3.5-6610add6

The actual returned data is correct:

```
Result: "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000040012004400000000000000000000000000000000000000000000000000000000"
Transaction cost: 21920 gas. 
Execution cost: 648 gas.
Decoded: 
    bytes: 0x00120044
```

However the PUSH in the assembly output seems wrong:

```
      PUSH 12004400000000000000000000000000000000000000000000000000000000           string memory x = "\x00\x12\x0...
```

The opcodes section is:

```
PUSH31 0x12004400000000000000000000000000000000000000000000000000000000
```

Conclusion: the assembly output should either use `PUSHnn` or pad to 32 bytes.

**Comment by chriseth** [comment]
The push is correct, there is no semantic difference between `push2 0x0001` and `push1 0x01`, both will push the number 1. If the assembly is the same, then the errors seems to be in the type annotations of the ast, it does not store the native length of the string correctly.

**Comment by axic** [comment]
@chriseth the assembler output has `PUSH` and 31 bytes of data. The length of the value is not clear on the first sight and given those many zeroes, it _looks_ like 32 bytes :)

Perhaps using `PUSH31` should be useful in the assembler output.

**Comment by chriseth** [comment]
The assembler output is not a bytecode output - the actual push instruction that is used is not yet determined before the assembly stage.

So is this actually a bug or not?

**Comment by axic** [comment]
The bytecode is correct. The assembler output (which is for developers only) is confusing. I would just use `PUSHnn` in the `assembler` output similarly to the `opcodes` output.
