### ISSUE TITLE
Feature Request: Yul output

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/solidity#5656]
## Motivation
It would be nice to be able to inspect the IR of a program to see exactly what it does with memory(/calldata/storage) instead of digging through the asm and additionally needing to reason about the stack, jumps, etc.

## Specification
Add a command-line option to `solc` analogous to `--bin` or `--asm`, but which outputs Yul IR (one output file per input file) instead of asm or bytecode.

**Comment by chriseth** [comment]
This is of course planned as soon as the IR is in place. Standard-json already has a field for it.

**Comment by k06a** [comment]
Still planned?

**Comment by chriseth** [comment]
No, already implemented: `solc --ir`
