### ISSUE TITLE
UnimplementedFeatureError when using public structs with ABIEncoderV2 and derived contracts

### ISSUE THREAD

**Issue by coder6423** [ethereum/solidity#5659]
I upgraded from 0.4.25 to 0.5 and run into a new UnimplementedFeatureError:

> Unimplemented feature:
> /solidity/libsolidity/codegen/CompilerUtils.cpp(347): Throw in function void dev::solidity::CompilerUtils::encodeToMemory(const TypePointers&, const TypePointers&, bool, bool, bool)
> Dynamic exception type: boost::exception_detail::clone_impl<langutil::UnimplementedFeatureError>
> std::exception::what: Encoding type "struct Test.TestStruct memory" not yet implemented.
> [dev::tag_comment*] = Encoding type "struct Test.TestStruct memory" not yet implemented.

This issue can be resolved by adding "pragma experimental ABIEncoderV2" to all derived contracts. 
Minimal Example:

```
--- test1.sol
// pragma solidity 0.4.25;
pragma solidity 0.5.1;

pragma experimental ABIEncoderV2;

contract Test {
    struct TestStruct 
    {
        uint a;
    }

    // Compiles fine in 0.4.25, 
    // 0.5.1 makes all derived contracts fail, unless ABIEncoderV2 is in every one of them
    // Making this non-public makes it pass in 0.5.1

    function giveMe() public returns(TestStruct memory){
    }
} 
```
```
--- test-derived.sol
// pragma solidity 0.4.25;
pragma solidity 0.5.1;

// pragma experimental ABIEncoderV2;
// ^ Compiles fine without this line in 0.4.25 
//   Fails in 0.5.1

import "./test1.sol";
contract TestDerived is Test {

}
```
```
--- test-derived2.sol
// pragma solidity 0.4.25;
pragma solidity 0.5.1;

// pragma experimental ABIEncoderV2;
// ^ Compiles fine without this line in 0.4.25 
//   Fails in 0.5.1

import "./test-derived.sol";


contract TestDerived2 is TestDerived {

}
```

Trying to compile any of the derived contracts, yields the error in 0.5.1. Adding the extra ABIEncoderV2 lines to all derived contracts makes it compile again.

**Comment by androlo** [comment]
I've had the exact same issue.

**Comment by zakalwe** [comment]
```
pragma solidity ^0.5.0;
pragma experimental ABIEncoderV2;

contract A {
    struct S {
        bool b;
    }
}

contract B is A {
    function test(S calldata s) external returns (bool);
//    function test2(S calldata s) external returns (bool);
}

contract C is B {
    function test(S calldata s) external returns (bool) {
        return s.b;
    }
}
```

This code suggests there's a bit more to this.  As written, the code generates the UnimplementedFeatureError.  However, if you uncomment the commented line, it compiles!  Something isn't right!

(tried on several 0.5.xx.xx versions)

**Comment by chriseth** [comment]
@zakalwe if you uncomment `test2`, this will make `B` and `C` abstract and thus no code generation will be requested. The error will be visible again as soon as you implement `test2` in a derived contract.

**Comment by leonardoalt** [comment]
This issue was discussed today, and we concluded that the 0.4.25 behavior was the faulty one. The derived contracts want to make use of the V2 encoder in function `giveMe`, so they should also declare `pragma experimental ABIEncoderV2`.

**Comment by chriseth** [comment]
It should not be an "UnimplementedFeatureError" though.

**Comment by glowkeeper** [comment]
I _think_ I'm seeing similar behaviour for a _slightly different_ issue. I'm using ````pragma experimental ABIEncoderV2````, which allows me to take advantage of passing structs in and out of functions.  Ideally, I'd like to do this:

```
struct SomeStruct {
    bool aVar;
    uint8 anotherVar;
    uint8 yetAnotherVar;
    uint8 andYetAnotherVar;
}

mapping(uint8 => bytes32[]) private refToSomeStruct;

function setActivity(uint8 _ref, SomeStruct calldata _param) external {
  refToSomeStruct[_ref] = _param
}
```

However, with the latest version of truffle, I get a rather unhelpful **UnimplementedFeatureError** (with no explanation. However, I note that only the latest release of Solidity, v0.5.4, implements the required ````struct calldata```` behaviour, but truffle is using v0.5.0.

Therefore, my request is twofold. First, is it possible to make **UnimplementedFeatureError** slightly more helpful (so it informs what feature is unimplemented)? Secondly, any chance Truffle could upgrade to v0.5.4?

**Comment by Marenz** [comment]
@glowkeeper that is definitely a different issue. Could you create a new ticket for your issue and provide a test case that produces the UnimplementedFeatureError? (I tried your provided code and didn't get the error)

**Comment by glowkeeper** [comment]
> I tried your provided code and didn't get the error

@Marenz - interesting - that was a contrived example, based on my actual code - just assumed, given the Solidity release docs regarding v0.5.4, that it was the `SomeStruct calldata _param` bit causing the problem - I'll do some more investigation and, if needs be, post accordingly.

Just as a further note, I have this at the top of my Solidity source files:

```
pragma solidity ^0.5.0;
pragma experimental ABIEncoderV2;
```

Do you get the error if you add that?

**Comment by Marenz** [comment]
@glowkeeper I am happy to discuss this more, but please in an dedicated issue for this :). I had the problem that I got compiler errors when assigning to the mapping as the struct wasn't castable to bytes32[].  I did use the experimental pragma.
