### ISSUE TITLE
Documentation issue:  enum in interface example

### ISSUE THREAD

**Issue by Zacharius** [ethereum/solidity#5673]
In the example for Interfaces at https://solidity.readthedocs.io/en/v0.5.1/contracts.html#interfaces an enum is declared along with a version pragma of pragma solidity >=0.4.11 <0.6.0, implying that you could implement enums in interfaces in as early a version as 0.4.11.

Experimentation has shown me that this feature was not implemented until 0.5.0. Furthermore there is nothing in the section about 0.5.0 changes mentioning this new feature. Not that I could find anyway. 

I know this is small but it caused me a good bit of confusion and I would like for others to not have to figure this out on their own in the future. I could happily make the change to the code example but I'm not sure where to make in the change in the section about 0.5.0 changes.

Should I make the change to the code example and then make a pull request?

**Comment by chriseth** [comment]
You are perfectly right! It is in the changelog, but perhaps not in the documentation. Please go ahead and change it!
