### ISSUE TITLE
Metadata should not require compilation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5682]
Related: #3437

**Comment by axic** [comment]
@christianparpart sorry I forgot to assign this, but had the code ready (it is not many changes).

However, there is one question to be decided before going ahead with this: libraries, optimiser settings and "use literal sources in metadata" currently can be changed between analysis and compilation, but are included in the metadata.

Simple solution is to disallow calling any of these after the `AnalysisSuccessful` state.

**Comment by chriseth** [comment]
Sounds good!

**Comment by chriseth** [comment]
Elsewhere you mentioned you are not convinced this is the right direction. What are the downsides?

**Comment by axic** [comment]
Suggestion from @chriseth: only allow changing these settings prior to parsing.
