### ISSUE TITLE
one question about send ether to a address of contract to invoke fallback() function

### ISSUE THREAD

**Issue by zxhubo** [ethereum/solidity#5688]
this code is:
```
pragma solidity ^0.4.24;

contract lib{
      event EventLib(address);
    function test()returns(uint256){
        emit EventLib(msg.sender);
        return 1;
    } 
}
contract Test{   
    event EventTest(address);
    event EventTest1(bool);
    event EventLib(address);
    lib l;
    constructor(address _addr){
        l = lib(_addr);
    }
    function test(){
        emit EventTest(msg.sender);
    }
    function getBalance() returns(uint256){
        return this.balance;
    }
    function ()payable{
        emit EventTest(msg.sender);
        bool b=l.callcode(bytes4(keccak256("test()")));
        EventTest1(b);
    }
}
contract Caller
{
    constructor()payable{}
    function getBalance() returns(uint256){
        return this.balance;
    }
    function invoke(address _addr){
        _addr.call(bytes4(keccak256("test111()")));
    }
    function trans(address _addr){
        _addr.call.value(10)();
    }
}
```
the first,I deploy contract Lib,the second I deploy contract Test,and at last I deploy contract Caller. the if I sending ether to contract Test by invoke trans function of contract Caller,because the address is a contract address,it will invoke the fallback() function with payable. Then the fallback() function will invoke test() function of contract Lib by this code `bool b=l.callcode(bytes4(keccak256("test()")));`,but I found if use 'call' and 'callcode' to invoke test(),the result b is true,but use 'delegatecall' to invoke test(),the result b is false,why? could you help me, tell me the answer .

**Comment by chriseth** [comment]
The reason is that `delegatecall` makes the transferred amount visible to the callee (and also available). So the `test()` function fails because it is not payable. Libraries were made to deal with the peculiarities of delegatecall, so you should not use delegatecall with regular contracts.

**Comment by zxhubo** [comment]
@chriseth 
Ok , you mean if I want to use delegatecall in fallback() function with payable, the test() function must with payable? But, i find it still return false 。
I know the vulnerability of the first attack of parity wallet is that the fallback() function with payable can use delegatcall,the code is 
```
  // gets called when no other function matches
  function() payable {
    // just being sent some cash?
    if (msg.value > 0)
      Deposit(msg.sender, msg.value);
    else if (msg.data.length > 0)
      _walletLibrary.delegatecall(msg.data);
  }
```
The hacker trans ether to the conctract and with msg.data,the _`walletLibrary.delegatecall(msg.data);`will be executed. so is solidity for resolve the vulnerability，forbid delegatecall be executed in the fallback() function with payable ？

**Comment by chriseth** [comment]
If you change `contract lib` to `library lib`, it should work, because the payable check will no longer be there. Note that this voids your (nonexistent) warranty ;)
