### ISSUE TITLE
[Feature Request] Compile Abstract Functions

### ISSUE THREAD

**Issue by maxsam4** [ethereum/solidity#5690]
## Abstract
Currently, Every function must have a body and a smart contract cannot be compiled with just function declarations. This means that the ABI generated will contain only explicitly defined functions. However, delegate proxy pattern through fallback function is now being widely used for upgradability and I only see it becoming more and more relevant.  

Allowing abstract functions to compile will mean that there is no effect on the bytecode but the ABI generated will include that function. For the EVM, it will be no different but for the outside world, it will become more relevant.

## Motivation
ABI is meant to help the outside world interact with the EVM. If 'custom' ABI was allowed to be generated from the official compiler, it will make it easier for front-end developers, tools like etherscan, normal end users etc to interact with the proxied smart contract.

Perhaps add an optional compiler flag that allows compiling with abstract functions (maybe make it default)?
Or maybe add an additional `extendedABI` element in the output JSON when that flag is enabled. In any case, the contracts should compile without an error.

## Specification
If compiler flag `--allowAbstract` is provided, the compiler should compile the smart contract even if it has a function with only declaration and no definition. The output bytecode will be like that function wasn't declared. The output ABI, however, will contain those functions.

## Backwards Compatibility
No issues.

**Comment by chriseth** [comment]
The compiler will already happily output the ABI JSON for abstract contracts. Is this what you request?

**Comment by maxsam4** [comment]
> The compiler will already happily output the ABI JSON for abstract contracts. Is this what you request?

But they don't compile. I want the same contracts to compile also; as if the abstract functions in them don't exist. 

This way the same contract code will be able to be used for deployment and usage, and abstract ABI generation.

**Comment by chriseth** [comment]
What exactly do you mean by "compile"? Which output would you like to get?

**Comment by maxsam4** [comment]
Assume a contract is
```
pragma solidity ^0.5.0;

contract HelloWorld {
    function hello() public;
    function world() public returns(uint256) {
        return 1337;
    }
    function() external {
        //delegate proxy logic
    }
} 
```
It should be compiled to bytecode as if the code was

```
pragma solidity ^0.5.0;

contract HelloWorld {
    //no function without definition
    function world() public returns(uint256) {
        return 1337;
    }
    function() external {
        //delegate proxy logic
    }
} 
```
The ABI, however, should contain mention of `hello()`.

**Comment by chriseth** [comment]
I don't think how this should be possible in general - what do you do if you have a call to `hello()` inside `world`? Also, could you please again explain the use-case? What do you plan to do with the bytecode?

**Comment by maxsam4** [comment]
> I don't think how this should be possible in general - what do you do if you have a call to `hello()` inside `world`? 

That should not compile. For bytecode generation, the source code will be like no function without definition was ever declared. It can be removed in pre-processing.

The main usecase is when fallback function of a proxy contract is kind of used as a dispatcher that calls other smart contracts that contain actual logic/function with delegate calls. For the end user, it's like the proxy contract has all these functions but actually the proxy contract only stores the state but delegates all logic to a different contract(s). This allows for upgradability, infinite contract size at a single address etc.

Most widely used implementation of this is probably https://github.com/zeppelinos/zos/blob/master/packages/lib/contracts/upgradeability/Proxy.sol

I wrote an article discussing this approach among others a few months back https://hackernoon.com/how-to-make-smart-contracts-upgradable-2612e771d5a2
(see Upgradable Storage Proxy Contracts section specifically)

If the requested feature is enabled, we'll be able to make the proxy contract's ABI contain the functions that it actually does (via delegate calls). As the bytecode won't change even if we add/remove function declarations, we'll be able to 'upgrade' these proxies as we add/remove new logic.
