### ISSUE TITLE
[Yul] Cleaner variable names

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5691]
The current output of the optimizer is not really readable.

I think we should 
 - [ ] not use the function name as a prefix for new variable names during inlining
 - [ ] remove `_n` suffixes at the end of the optimizer step if names are still unique

At the end, it might even go over all variable names and re-assign the suffixes starting from 1 - this would also increase stability.

### Requirements (WIP):
* don't add a prefix to names (during inlining)
* adding a single optimizer pass that is run at the very end that takes functions as scopes.
* rename already used names to something that's not taken yet (`nameX` to `nameX_$NUM`), whereas uniqueness is function-local (or global scope, if a global name)

**Comment by ekpyron** [comment]
If we (re)generate readable variable names at the end of each step anyways, might it make sense, instead of generating actual names in the NameDispenser directly, to have a separate "kind" of names (i.e. "generated" names instead of "user-supplied names") that are just a numeric ID that is globally incremented (maybe together with a YulString hint that's only used *after* the step when generating readable names?)?

**Comment by chriseth** [comment]
The main problem I see here is that it has to either be a feature of the AST or a feature of YulString. We tried the second already, not sure if it is worth trying it on the AST...

**Comment by ekpyron** [comment]
Yeah - my point was to consider making it a feature of the AST - I think that should work and in fact work well... but we can skip that discussion for now, resp. decouple it from this issue.

**Comment by chriseth** [comment]
Perhaps to clarify: This issue is about not adding the prefix during inlining and about adding a single optimizer pass that is run at the very end that takes functions as scopes and whenever it finds a variable of the form `<prefix>_<number>`, it renames it to something that is not already taken in the current function and searches the following order: `<prefix>`, `<prefix>_1`, ...
