### ISSUE TITLE
install_deps.sh in cent OS 7.2 work failed

### ISSUE THREAD

**Issue by HaoXuan40404** [ethereum/solidity#5692]
## Description

In install_deps.sh, line 59 (sed -n -e 's/^NAME="\?\([^"]*\)"\?$/\1/p' /etc/os-release) will get CentOS Linux instead of CentOS, so it cant match CentOS.  
I suggest that in line 355， can modified     "           CentOS)" to "           CentOS*)"

## Environment
CentOS 7.2
- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by chriseth** [comment]
Please make the change and create a pull request!

**Comment by axic** [comment]
@HaoXuan40404 do you mean to modify `CentOS)` to `CentOS*)` ?

**Comment by HaoXuan40404** [comment]
> @HaoXuan40404 do you mean to modify `CentOS)` to `CentOS*)` ?

Yes
