### ISSUE TITLE
solc EXC_BAD_ACCESS in Mac OSX 10.11.4

### ISSUE THREAD

**Issue by kjsujesh** [ethereum/solidity#570]
Compiler::compileContract gives EXC_BAD_ACCESS (GPFLT) at 
swap(m_context, m_runtimeContext);

commenting out the line makes solc compile correctly.
But not sure about the implications.
<img width="1423" alt="Execution path" src="https://cloud.githubusercontent.com/assets/17286915/15269023/ffbd9640-19a6-11e6-908a-7e384fa29916.png">

**Comment by VoR0220** [comment]
!!!! Thats where the segfault happens.

**Comment by VoR0220** [comment]
Can you run the soltest binary and see if all tests pass?

**Comment by kjsujesh** [comment]
Nope. The tests fail. Will have to probably initialize the compiler runtime context. Let me see what that would do.

**Comment by VoR0220** [comment]
closing for now as replication. Thanks again @kjsujesh for the useful information.
