### ISSUE TITLE
Recommend to use latest version.

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#5702]
Solidity is released as 0.x software. And I understand this as meaning things will change quickly and old versions will not be supported. This seems to line up with reality.

Please add the statement "you should use the latest released version of Solidity for new projects" in README.md and on the front of the documentation page.

This should be obvious. But I need a reference to cite that as a best practice when telling other people.

Thank you.

- [ ] `git grep 'pragma solidity ^0.4'`

**Comment by chriseth** [comment]
I like the motivation :)

**Comment by fulldecent** [comment]
PR https://github.com/ethereum/solidity/pull/5757

**Comment by nventuro** [comment]
Shouldn't this be closed with https://github.com/ethereum/solidity/pull/5757 merged?

**Comment by chriseth** [comment]
Ah right, thanks!
