### ISSUE TITLE
Fix coverage of TypeChecker.cpp

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5712]
Go through https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp and remove all the red lines.

**Comment by chriseth** [comment]
Note that lines with assertions cannot get test coverage by design, but at least all lines that report an error (`m_errorReporter.typeError(`) should be covered, i.e. green.

**Comment by chriseth** [comment]
Some examples:

 https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L587 - write a test with an event that has a `mapping` parameter.
 https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L589 - write a test with an event that has an internal function pointer as parameter.
 https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L612 - use a pointer to an external function type that takes a mapping or internal function pointer (better to have tests for both) as parameter
 https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L769 - use `return (1, 2)` in a function with `function ... returns (bytes memory, bytes memory)`
 https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L1172 - use `x += y` where `x` is `uint` and `y` is `bytes2`.

**Comment by Marenz** [comment]
I am pretty much done with this. Only thing left is this:

https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L2275

I couldn't find a way to trigger it. @ekpyron said it might be related to 30d9961efb7c0056a2b189b642489bee92048442

I have a suspicion that the case can't happen anymore.. but I don't enough to say for sure.

**Comment by chriseth** [comment]
If you cannot trigger it, please turn it into an assertion.
