### ISSUE TITLE
LLL: Incorrect order of arguments in shift operators

### ISSUE THREAD

**Issue by chfast** [ethereum/solidity#5714]
## Description

The arguments for SHL, SHR, SAR are put in reversed order in the final bytecode.

When you write code like `(SHL 1 2)` it should rather mean `1 << 2` not `2 << 1`. But the output bytecode is `600260011b00`. So the stack has `1` at the top before the `SHL` is executed and in all shift operators in EVM the top stack argument is taken for the shift amount.

This is different from other arithmetic instructions like `DIV`, `SUB`, etc., where the top stack item is the first argument of the operator. This is also probably the reason of the bug.

## Environment

- Compiler version: LLLC, the Lovely Little Language Compiler
Version: 0.5.3-develop.2018.12.20+commit.88255332.Linux.clang

## Steps to Reproduce

```
echo '(SHL 1 2)' > sar.lll && lllc/lllc sar.lll
600260011b00
```

**Comment by chriseth** [comment]
Does this also apply to yul?

**Comment by chriseth** [comment]
The inline assembly documentation states
```

shl(x, y) |   | C | logical shift left y by x bits
shr(x, y) |   | C | logical shift right y by x bits
sar(x, y) |   | C | arithmetic shift right y by x bits

```
And `x` would be on the stack top in the generated code.

**Comment by axic** [comment]
"Duplicate" of #3141.

Note, `(shl 1 1)` is LLL's notation. Just use `(asm shl 1 1)` to get the assembler. Not sure why tests do not only use the assembler.
