### ISSUE TITLE
Problem building with cmake on Windows 10

### ISSUE THREAD

**Issue by gked** [ethereum/solidity#5719]
## Environment

- Compiler version: ### 0.5.3 (unreleased). At least that's what the changelog says
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): cmake
- EVM execution environment / backend / blockchain client: backend
- Operating system: Windows 10 (17763)

## Steps to Reproduce

I was following these steps on how to build Solidity on Windows - [https://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source](https://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source)
- I cloned solidity repo: `git clone --recursive https://github.com/ethereum/solidity.git`
- Tried running scripts\install_deps.bat from the scripts folder in PowerShell. It errored out saying "CMake Error: Error processing file: scripts\install_deps.bat". I got around the problem by running `cmake -P .\install_deps.cmake` which is the only script inside install_deps.bat file. It did some things and finished ( I think) successfully.
- Next, I tried running `cmake --build . --config Release` which is where I hit the dead end because the error is as ambiguous as it can be and I am not getting any relevant hits when searching the web. Error message: "Error: could not load cache". Some of the forums mentioned missing a mysterious cache file. But it is not in the repo and I am not sure where I should be getting it.

Please let me know if I can provide you with any extra information.

UPDATE:
I have just tried to do the same thing using GUI cmake and it looks like it has generated some files, including the cache file :). The build command in the terminal is still not working though as it is complaining about missing project file. "MSBUILD : error MSB1009: Project file does not exist. Switch: ALL_BUILD.vcxproj"
<img width="598" alt="capture" src="https://user-images.githubusercontent.com/12704474/50327414-dddded00-04a3-11e9-946a-2643672c2293.PNG">

At this

**Comment by chriseth** [comment]
Could you please post the full error log of your commandline `cmake` run? Also, which version of visual studio are you using?

**Comment by chriseth** [comment]
Closing for now. Please reopen if you can find the error log.
