### ISSUE TITLE
Storage struct initializer wastes gas

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#5725]
## Description

In solidity docs it recommends:
`
Initialize storage structs with a single assignment: x = MyStruct({a: 1, b: 2});
`

But this is gas inefficient.

https://medium.com/cryptologic/memory-and-storage-in-solidity-4052c788ca86

https://github.com/mix-blockchain/mix-item-store/commit/ab104b1204517f695cd67d81c2ce035deb25872e

Before:
`
PASS testCreate() (gas: 427787)
`

After:
`
PASS testCreate() (gas: 426275)
`

## Environment

- Compiler version: 0.5.0
- Target EVM version (as per compiler settings): Byzantium
- Framework/IDE (e.g. Truffle or Remix): dapp
- EVM execution environment / backend / blockchain client: dapp-test
- Operating system: Linux

**Comment by ethernomad** [comment]
Not using a storage struct initializer saves 504 gas each time itemStore.create is invoked.

**Comment by chriseth** [comment]
Thanks for the issue! We have to wait for the new optimizer (including #5107 ) to make such initializations gas-neutral. Would you prefer the documentation to be changed until we are there?

**Comment by ethernomad** [comment]
Looks like a note has already been added to the docs.
