### ISSUE TITLE
Github Failed to Detect Solidity language in My Project

### ISSUE THREAD

**Issue by vishwaratna** [ethereum/solidity#5726]
I wrote a ethereum Airdropping smart contract and uploaded it on [Github ](https://github.com/vishwaratna/Airdrop_SmartContract) , bt github failed to detect the language of my project.
In screenshot you can see it below.

![screenshot 418](https://user-images.githubusercontent.com/8758168/50539873-a52dca00-0bad-11e9-87e0-192841b0c45a.png)

**How to Fix it??**

**Comment by 3esmit** [comment]
You need a file like this in root of your repo https://github.com/status-im/contracts/blob/bootstrap/.gitattributes

**Comment by erak** [comment]
@3esmit Thanks! @vishwaratna I'll close this issue now. Please also consider consulting https://github.com/github/linguist#using-gitattributes for further advice.
