### ISSUE TITLE
OpenBSD build

### ISSUE THREAD

**Issue by flipchan** [ethereum/solidity#5728]
How do you compile it on openbsd 6.4?
has anyone got this to compile on openbsd?

**Comment by flipchan** [comment]
was able to get it running by: 
```

pkg_add -iv cmake boost z3
git clone --recursive https://github.com/ethereum/solidity.git
cd solidity
mkdir build
cd build
cmake ..
make
make install

ln -s /<path>/solidity/build/solc/solc /usr/local/bin/solc
```

**Comment by flipchan** [comment]
pls add to https://github.com/ethereum/solidity/blob/v0.5.2/docs/installing-solidity.rst

**Comment by axic** [comment]
@flipchan would you be interested to open a PR adding it to the documentation?

**Comment by ChrisChinchilla** [comment]
@flipchan And happy to help you through that PR, but it would be great if you could make a start with it :)

**Comment by flipchan** [comment]
@ChrisChinchilla @axic

Pull request created: https://github.com/ethereum/homestead-guide/pull/465

**Comment by ChrisChinchilla** [comment]
OK, I'll review there @flipchan and then merge the same content into this repo, I'll need to test it all first too, just to double check everything works, though I'm sure it does :)

**Comment by ChrisChinchilla** [comment]
@flipchan `cmake` froze for me around 19%, did you experience this at all? This is a verbose screenshot. I am using a VM though, so who knows…

<img width="640" alt="screen shot 2019-01-21 at 13 55 58" src="https://user-images.githubusercontent.com/42080/51473196-5c1ffe80-1d84-11e9-9b57-6edc87505697.png">

**Comment by axic** [comment]
@flipchan thank you! However I think that repository is painfully outdated. I actually meant updating https://solidity.readthedocs.io/en/v0.5.2/installing-solidity.html which is the file here https://github.com/ethereum/solidity/blob/develop/docs/installing-solidity.rst

**Comment by flipchan** [comment]
@ChrisChinchilla 
sorry for the late reply, stuck at 12%?
are you running openbsd 6.4?

**Comment by flipchan** [comment]
@ChrisChinchilla maybe its the vm that freeze? try running it in tmux and just leaving the vm to run for like an hour
