### ISSUE TITLE
Ignore "File not found" with --ast/--ast-json command

### ISSUE THREAD

**Issue by JoranHonig** [ethereum/solidity#5735]
## Description
I'm working on a tool that does simple operations based on the ast of a single contract. To do this I simply use `solc --json-ast <contract>` which for simple cases is more than fine. 
However, when I start looking at more complicated projects, then they depend on other projects.
Running the command on initializer_contracts/contracts/UpgradeabilityProxy.sol from https://github.com/zeppelinos/labs
```
solc --ast UpgradeabilityProxy.sol 
UpgradeabilityProxy.sol:4:1: Error: Source "openzeppelin-solidity/contracts/AddressUtils.sol" not found: File not found.
import 'openzeppelin-solidity/contracts/AddressUtils.sol';
```
The missing file might ignored here and the AST printed

I'm trying to do a few simple mutations to the target contract, for this purpose it's not necessary that dependencies are available.

As of yet I've not been able to find a way to make ignore the fact that there are missing imports, as such I think it would be useful if an commandline option is added to ignore missing imports.

**Comment by chriseth** [comment]
Thanks for the issue, this is an important feature. I think it should be part of #5577

**Comment by chriseth** [comment]
Please re-open, if you think this deserves to be its own issue.

**Comment by JoranHonig** [comment]
@chriseth No it seems that that issue captures the functionality. 
Thanks for getting back to me!
