### ISSUE TITLE
storage reference elements in memory array

### ISSUE THREAD

**Issue by aihuawu** [ethereum/solidity#5737]
Hi,

I want to collect lots of storage reference into a memory array, then I will do
a for loop to modify the storage.  The array should be in memory, but the elements
should be in storage. It requires something like this:
Person storage [] memory ls; 

It will not compile. is there any workaround for this?
Thanks.

George Wu

**Comment by chriseth** [comment]
This is currently not supported - you have to use things like inline assembly.
This is actually a duplicate: https://github.com/ethereum/solidity/issues/1010
