### ISSUE TITLE
isolate_tests.py error

### ISSUE THREAD

**Issue by xwlin-roy** [ethereum/solidity#5740]
## Description

Hi,
I want to use `isolate_tests.py` to generate testcases, but incountered errors.
The details are below:
scripts:
```
 ../solidity/scripts/isolate_tests.py ../solidity/test/libsolidity/SolidityEndToEndTest.cpp
```

error:

> Traceback (most recent call last):
  File "../solidity/scripts/isolate_tests.py", line 82, in <module>
    extract_and_write(path, path)
  File "../solidity/scripts/isolate_tests.py", line 73, in extract_and_write
    write_cases(f, cases)
  File "../solidity/scripts/isolate_tests.py", line 62, in write_cases
    open('test_%s_%s.sol' % (hashlib.sha256(test).hexdigest(), cleaned_filename), 'wb').write(test)
IOError: [Errno 2] No such file or directory: 'test_6f15df59500dd5457d4d1c5bebf9299e67c299a4d64bd6c591bdda130980a4ac_/../solidity/test/libsolidity/solidityendtoendtest_cpp.sol'

**Comment by chriseth** [comment]
Does it help running it without `..`?

**Comment by xwlin-roy** [comment]
I go to the `SolidityEndtoEndTest.cpp` directory to execute `isolate_test.py`.
It succeed.
Thank you for your reply.
