### ISSUE TITLE
Unstable compiler error “Unknown exception during compilation” appear

### ISSUE THREAD

**Issue by meowent** [ethereum/solidity#5750]
The online compiler gives unstable error message between the same codes and similar scenario.

Remix keeps throwing "Unknown exception during compilation." when the function is doing multiple dynamic returns( three uint[] dynamic array).

But when I size the returning to TWO dynamic arrays, the issue disappeared. And now I have no any clue about the reason behind it. Have switch different pragma solidity version already.

https://stackoverflow.com/questions/54034328/unstable-remix-compiler-error-unknown-exception-during-compilation

**Comment by chriseth** [comment]
It seems this has been fixed with the nightly release of 2019-01-08.
