### ISSUE TITLE
Short-Circuit Booleans Not Implemented

### ISSUE THREAD

**Issue by Denton-L** [ethereum/solidity#576]
Expected result, test() should return 0.
Actual result, test() returns 5.

Test code:

```
contract Test {
    uint asdf = 0;

    function setToFive() returns (bool) {
        asdf = 5;
        return true;
    }

    function test() constant returns (uint) {
        if (true || setToFive()) {}

        return asdf;
    }
}
```

This result was expected because Solidity was designed with JavaScript in mind and JavaScript implements short-circuit evaluation by default using the `||` and `&&`  operators.

**Comment by chriseth** [comment]
Do you get this result when running inside browser-solidity? I'm asking because I cannot reproduce your reported behaviour.

**Comment by Denton-L** [comment]
Yeah, I'm running under browser-solidity. I suppose this is an issue for _that_ repository?

**Comment by Denton-L** [comment]
It works now?????

I may have looked at the wrong value while testing by mistake.
