### ISSUE TITLE
Test code in readme

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#5767]
From https://github.com/ethereum/solidity/pull/5757

Extend the compilation tests in [isolate_tests.py](https://github.com/ethereum/solidity/blob/develop/scripts/isolate_tests.py) to cover [README.md](https://github.com/ethereum/solidity/blob/develop/README.md) -- this will check if it can be compiled with the current version.

**Comment by Faizan711** [comment]
Is this issue still open, if so i would like to be assigned for it.

**Comment by cameel** [comment]
Yes, it's up for the taking, though it's very low priority to be honest. Unless you just specifically want a Python task (the only changes here will be in a Python script), I'd recommend first looking at the issues I recently listed in https://github.com/ethereum/solidity/issues/12332#issuecomment-1310522329 instead.
