### ISSUE TITLE
[Yul] Implicit conversions in variants in Yul AST are easily detrimental.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#5778]
``yul::Statement`` and ``yul::Expression`` are ``boost::variant``s. Therefore they can be implicitly constructed from the variant alternative types. This may be convenient, but in a lot of cases will silently not be what we want.
Consider:
```
class Example: ASTWalker {
public:
    using ASTWalker::operator();
    void visit(Statement const& _statement) override;
    void operator()(Block const& _block);
};
```

Now consider you want to use ``Example`` to visit a ``Block``. Naturally you may write:
```
    Block const* block = ...;
    Example example;
    example.visit(*block);
```

This will work and doesn't look suspicious, but it will perform a deep copy of the block, since it is implicitly converted to ``Statement`` in order to call ``Example::visit``.

I think this is an actual design flaw in the current Yul AST. A possible solution would be to have a thin wrapper deriving from ``boost::variant`` that only has explicit constructors from the variant alternatives (we'd have to check whether ``apply_visitor``, etc., will still work smoothly that way;  and maybe there's a better solution altogether).

**Comment by ekpyron** [comment]
A sufficient solution to this might be to delete all copy constructors and copy assignment operators for the Yul AST Nodes. That way the ``boost::variant`` won't be implicitly copy-constructible from its alternatives either, mitigating the issue. If one wants to copy Yul AST nodes, I guess the right way to do it is to use the ``ASTCopier`` anyways, so I think it makes sense if direct copies are disallowed in general.
EDIT: Deleting constructors will not prevent the ``struct``s from being considered aggregates, so aggregate initialization will still work.

**Comment by ekpyron** [comment]
Related: #5653 and #5694 - using ``unique_ptr``s will already implicitly delete a number of copy-constructors, but it might not be all of them, so it may still make sense to unconditionally explicitly delete all of them (resp. most of them - e.g. for ``Identifier`` copying will still be fine - it may be that in fact all are caught using unique_ptrs, but we should recheck).

**Comment by chriseth** [comment]
Sounds good!

**Comment by axic** [comment]
@ekpyron is this still a valid issue?

**Comment by ekpyron** [comment]
Might still be a thing... most of the cases should be fine by now, though...
