### ISSUE TITLE
How Can I Compile My Contract Source Code on Solidity 0.5.2 .

### ISSUE THREAD

**Issue by aiak0s** [ethereum/solidity#5781]
I would like to compile my solidity source code and get the Bytecode and ABI in my 'output' variable.
This is my compile.js code and it works with Solidity 0.4.17 ;
```
const path = require('path');
const solc = require('solc');
const fs = require('fs-extra');

const buildPath = path.resolve(__dirname, 'build');
fs.removeSync(buildPath);

const campaignPath = path.resolve(__dirname, 'contracts', 'Campaign.sol');
const source = fs.readFileSync(campaignPath, 'utf8');
const output = solc.compile(source, 1).contracts;
console.log(output);
```
But in **Solidity 0.5.2** This " **solc.compile(source, 1).contracts;** " code is not working. I could not find the new syntax of this code. 

Thanks for help.

**Comment by chriseth** [comment]
Please find the documentation here: https://github.com/ethereum/solc-js#example-usage-without-the-import-callback

Please reopen the issue if you have further questions or ask in https://gitter.im/ethereum/solidity

**Comment by samiaMH** [comment]
@aiak0s  u solved this problem ?
