### ISSUE TITLE
Build fail while trying to install legacy version of solidity 0.4.25: "Unable to determine commit hash. Either compile from within git repository or supply a file called commit_hash.txt"

### ISSUE THREAD

**Issue by cbshweta** [ethereum/solidity#5782]
I can see that there is a commit_hash.txt under my source directory and it matches with the hash against the binaries available and yet I get the error. How to resolve this error?

**Comment by chriseth** [comment]
Can you explain the individual steps you are taking to compile? Are you using https://github.com/ethereum/solidity/releases/download/v0.4.25/solidity_0.4.25.tar.gz as source?

**Comment by cbshweta** [comment]
Yes, I have downloaded code from above link. 
Below are the steps I have done:
cd solidity
./scripts/install_deps.sh
mkdir build
cd build
cmake .. && make
Thats when I get the above error.

I then tried to run -
./scripts/build.sh
But I get the same error again.

![image](https://user-images.githubusercontent.com/24472976/51148839-8723c300-1857-11e9-96c0-fd422a37d9c1.png)

**Comment by chriseth** [comment]
Which version of cmake are you using? Oh and might there be a space in the path to your build directory?

**Comment by cbshweta** [comment]
cmake version 3.13.2
I have now upgraded cmake to 3.13.3 and also removed the space on my build path and have run the above commands again.
The error is now gone so I believe one of the above steps did the trick but it is replaced by another error:
![image](https://user-images.githubusercontent.com/24472976/51217999-64121580-1922-11e9-985e-995cd10c59b8.png)
This one seems to be related to Boost version being incompatible as suggested here:
https://github.com/ethereum/solidity/issues/5449

**Comment by chriseth** [comment]
It might be that applying the three small changes [here](https://github.com/ethereum/solidity/compare/v0.4.25...release-0.4) could fix the problem. Sorry for the inconvenience!

**Comment by cbshweta** [comment]
Thanks a lot Chris! Applying the above three changes solved the problem.
