### ISSUE TITLE
Optimisation step: consecutive jumpdest pruner

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5791]
#4959 mentioned a potential new optimisation step:

> P2 — {M consecutive jumpdests} → {jumpdest}, M ≥ 2
> jumpdest marks a valid jump target (i.e., any valid jump operation must jump to a jumpdest). M consecutive jumpdests can be replaced with one because they point to the same operation (i.e., the operation after the final jumpdest). The deployment and invocation of this anti-pattern waste 68 × (𝑀 − 1) units and (𝑀 − 1) units of gas (the execution of a jumpdest needs 1 unit of gas), respectively.

While libevmasm has a step to remove unreferenced `JUMPDEST`s there doesn't seem to be a way to change referenced ones.

A good new step could:
1) search for consecutive `JUMPDEST`s
2) change all the references to the first one

After this step the `UnusedJumpdests` step could prune the ones left.

**Comment by chriseth** [comment]
This might already be implemented through the block deduplicator.
