### ISSUE TITLE
Converting a solidity AST back to solidity Source Code

### ISSUE THREAD

**Issue by tharindu1992** [ethereum/solidity#5802]
Is there a way to convert AST back to Solidity Source code. 

The use case is to mutate the AST and recreate the Solidity Source code for optimization and testing purposes.

**Comment by chriseth** [comment]
Currently, there is no way. There is initial work on re-importing an AST, though, which could be of interest: #2096

**Comment by axic** [comment]
Duplicate of #2165?

**Comment by chriseth** [comment]
I think both issues need to be further clarified :)

**Comment by axic** [comment]
Clarified it a bit there, not sure how much more it can be clarified :)

Closing this here.

**Comment by ryanfalzon** [comment]
Has there been any updates on this? I need to make use of this feature.

**Comment by cameel** [comment]
No, the compiler can parse an AST from JSON but currently does not offer a feature to synthesize code back from that. There are external tools that can do that though. Check out [solc-typed-ast](https://github.com/ConsenSys/solc-typed-ast).

**Comment by cameel** [comment]
BTW, this issue has been closed because it's a duplicate. The feature request is now tracked in #2165. I'm locking this thread - please post any related comments there.
