### ISSUE TITLE
[SMTChecker] Check for overflow/truncation in smaller type conversion

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#5808]

**Comment by axic** [comment]
Wasn't this fixed by #9938?

**Comment by leonardoalt** [comment]
Truncation yes, but it doesn't create create verification targets yet.

**Comment by pgebal** [comment]
Narrowing casts are now explicit in solidity. Due to this reason we decided that verification targets that check truncation are no longer needed.
