### ISSUE TITLE
Optimizer rule that removes masking before shift

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5810]
This should go into the rule list (`libevmasm/RuleList.h`).

During encoding and decoding, we might do things like
`(x && 0xff) << (256-8)` or similar with right shifts.

The masking is redundant here.

We should add optimizer rules that remove the masking in this case. A similar rule could be added for signextend plus shift.

Furthermore, there should be rules for both shift and multiplication with a power of two.

**Comment by axic** [comment]
This can easily be implemented in the RuleList if targeting Constantinople because `SHL` exists as an opcode. Should be also possible to have a rule with `MUL`.

**Comment by axic** [comment]
> `(x && 0xff) << (256-8)` or similar with right shifts.

I think here you mean `(x & 0xff) >> (256 - 8)` to be replaced with `x >> (256 - 8)`.

**Comment by axic** [comment]
@chriseth can you clarify the proposed rule? 

`(x && 0xff) << (256-8)` seems to shift the bottom 8 bits to the top. No masking should be needed here.

When you mean "and similar for shr" do you mean something like: `(x && 0xff0000..000) >> (256 - 8)` ?

**Comment by chriseth** [comment]
Yes, the masking is redundant, and because of that `(x && 0xff) << (256-8)` should be replaced by `x << (256-8)`.

The masks before left shift can of course be extended to the left while the masks before right shift can be extended to the right.

So basically, perhaps as a simplification:

`(A && B) << C` -> `(A << C) && (B << C)` and if `B` and `C` are constants, it should solve itself.

EDIT: Ah, that's actually not the full rule, the shift in `B << C` is actually allowed to shift in ones or zeros, whatever is better.

**Comment by chriseth** [comment]
This might benefit from bit mask tracking.

**Comment by bshastry** [comment]
Does #6160 close this issue? This is flagged as "needs review" in the 0.5.8 project.

**Comment by chriseth** [comment]
Neither this nor #6160 will be included in the 0.5.8 release.

**Comment by axic** [comment]
Also should consider removing masking after shift (e.g. (uint256 >> 248) && 0xff)

**Comment by chriseth** [comment]
This really reminds me of the decompiler project that just has a combined "mask and shift" concept.
