### ISSUE TITLE
reduce gas cost for returning big struct list on deployment

### ISSUE THREAD

**Issue by aihuawu** [ethereum/solidity#5826]
It seems the EVM has a hard gas limit around 6.7M for deployment. So I need to reduce gas.

When I return a big struct list from a contract, it can consume a lot of gas for deployment.
If I have a lot of query functions which return the same kind of struct list, it is obvious they share the
same kind of serialization code for the struct list, is it possible for me to factor those serialization code out? then I can save gas for deployment.

	function f1() 
	public view
	returns(OrderEntry[] memory)
	{
		//.....
	}

	function f2() 
	public view
	returns(OrderEntry[] memory)
	{
		//.....
	}
	// .......

George Wu

**Comment by chriseth** [comment]
This should already be the case (at least in ABIEncoderV2, which you need if you return structs). How do the gas requirements grow when you add more functions that return the same type?

**Comment by aihuawu** [comment]
Thanks. I see.
So it is refactored out for the common type. I have not done accurate experiments.
There is another similar issue:
I return array of struct which is storage reference, so it will be converted to memory, and then be serialized. I am wondering if the storage to memory is also optimized to save deployment gas.

**Comment by chriseth** [comment]
As far as I can tell, it should directly encode from storage. Which optimizations would you expect for the storage to memory copy?

**Comment by aihuawu** [comment]
Currently I must split a big contract to a lot of small contracts.
I am not sure if I am doing the right thing. To deploy a contract, it can't go above the 6.7 M gas.

Each contract has some storage, it must make the storage be accessible to other contracts.
So it has to pass memory struct instead of storage struct. I find this is very expensive for the communications between contracts.  I believe it would be good to do memory copy only once if I have a lot of methods to access other contract's storage.

George Wu

**Comment by chriseth** [comment]
Did you try using libraries and passing actual storage pointers?

**Comment by aihuawu** [comment]
I really don't know how to do that. You mean I can pass storage pointers between contracts.
That should save me a lot of gas.

**Comment by aihuawu** [comment]
Is there a simple example to show me how to access other contract's storage?
It doesn't even compile for public method with storage references.

**Comment by aihuawu** [comment]
You mean pass contract storage reference to library? I am doing that. Just the library can't reduce gas for the contract. Maybe I should deploy library separately. It is a good suggestion. I may try that.
Thanks.

**Comment by chriseth** [comment]
Closing this for now.
