### ISSUE TITLE
Add libFuzzer (oss-fuzz) CI

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5829]
## Abstract

Problem: Issue #5804 introduces libFuzzer test harnesses that are expected to be built by Google's ossfuzz bots. However, a build failure there is perhaps too late.

## Motivation

It would be nice to add/modify a CI job in solidity such that the libFuzzer test harnesses are built alongside and any build errors stall potential PR merges.

By adding libFuzzer specific build steps to a CI job, we can also support regression testing against fuzzer-generated test inputs on a regular basis.

**Comment by axic** [comment]
@bshastry would it make sense prioritizing this as long as it doesn't take too much time to accomplish?

**Comment by bshastry** [comment]
@axic Sounds reasonable to me. Will make a PR once the new CI is ready.
