### ISSUE TITLE
Inconsistency between soljson and solc-js APIs

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5830]
With #4441 we have moved on to a newer version of Emscripten which changes the API of the generated file. solc-js was not prepared for this, the change was merged *after* 0.5.0: https://github.com/ethereum/solc-js/commit/714162eb72d9a532b68d8150f6b21ea8deb73bcd

During today's standup we have discussed that it would be foolish to break compatibility between solc-js 0.5.x and solidty 0.5.x, e.g. every version of solc-js 0.5.x should be able to load any version of solidity 0.5.x.

The way to fix this is to add back the workaround into the generated soljson file:
```
Module.addFunction = Module.Runtime.addFunction;
Module.removeFunction = Module.Runtime.removeFunction;
```

This should be added before the `module.exports=Module;` line.

**Comment by chriseth** [comment]
I don't see `module.exports=Module`, you probably mean `module['exports'] = Module`, but that is done rather at the beginning. I would just add `Module.addFunction = Module.Runtime.addFunction` at the very end. Why would that not work?

**Comment by axic** [comment]
Depends on the version I guess, how `module.exports` is typed.

> Why would that not work?

True, I suppose `Module` is a map, as long as the code is added after `Module` is declared no browser should complain.

**Comment by chriseth** [comment]
Oh and the assignment has to be the other way around: `Module.Runtime = {addFunction: addFunction, removeFunction: removeFunction}`.

**Comment by axic** [comment]
> Oh and the assignment has to be the other way around

Oh, you're correct. One wonders why would they make the API even worse :)
