### ISSUE TITLE
ABIEncoderV2 behaviour

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5844]
On yesterdays standup we've discussed the ideal behaviour of the ABI encoder, which resulted in the following:
- Decoding inputs should validate and reject if a value is out of range (reject here means to revert)
- Encoding outputs should have a dirty bits cleaning, unless it would be ambiguous for the given type (one such type is enums, which cannot be truncated to be in range unambiguously)

The immediate next steps to take:
- ABI encoder should keep asserting on enums
- ABI encoder should keep cleaning booleans
- ABI decoder should revert on out of range for every single type

**Comment by chriseth** [comment]
So the only change (apart from refactoring the Yul code) would be to revert on invalid boolean, integer, bytesXX and address input, right?

**Comment by axic** [comment]
I think so.
