### ISSUE TITLE
[DOCS] Need comprehensive list of function modifiers

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#5856]
## Abstract

The docs need a list on one place of all function modifiers, and a summary of what they do, or link to more details.

## Motivation

In PR #5796 we discussed linking to function modifiers section, which doesn't summarise what's possible.

**Comment by chriseth** [comment]
Note that "function modifier" in the strict sense is just what users can define using `modifier`, although we sometimes also use the name `function modifier` for things like `private` and `external`. Perhaps we should call the built-in ones "qualifiers"?

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
