### ISSUE TITLE
[DOCS] Ensure warnings, notes etc are in logical orders

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#5857]
## Description

In my opinion when there are multiple sequences of notes, warnings etc, warnings should appear on top.

**Comment by Meshugah** [comment]
@ChrisChinchilla Could I work on this? Could you point me in the right direction to get started?

**Comment by ChrisChinchilla** [comment]
@Meshugah Sure, it's relatively simple, but may require making changes in a few different places.

In a few areas of the documentation are groups of notes and warnings, these are `.. note::` and `.. warning::` followed by blocks of text.

In my opinion, the warning notes should always be at the top, followed by the notes, followed by any others (there are some `.. info::` blocks too.

So this task is to go through the docs and reorder them. Depending how many you find, you might need to create multiple PRs, we roughly say after about 7 changes then it's time to break out into multiple PRs.
