### ISSUE TITLE
Solidity 0.5.3 call unexpectedly throws out of gas (OOG)

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#5859]
## Description

Sending 0 ether to contract B unexpectedly throws OOG when forwarding 0 wei from contract to other contract.

## Environment

- Compiler version: soljson-v0.5.3+commit.10d17f24
- Target EVM version (as per compiler settings): Ropsten network
- Framework/IDE (e.g. Truffle or Remix): Remix

## Steps to Reproduce

1. Deploy contract A (https://ropsten.etherscan.io/address/0x440b2c50c024f60f0d4ba41e1e19f289aeccd4b0#code)
2. Deploy contract B with address of A provided to constructor (https://ropsten.etherscan.io/address/0x19edb760524dc921c656dba6553a2f43fdb2b803#code)
3. Send `1 wei` to contract B (https://ropsten.etherscan.io/tx/0xc82b2dc993faac740b7a28a2adeabe0d8dfe5b8582c97670aa86ccb3286a315e)
4. Send `0 wei` to contract B (https://ropsten.etherscan.io/tx/0x34f5034141d0fe9b78e7c7c3548f167214008df5c5fd9ac1fbde9731988e11ae)

```solidity
pragma solidity ^0.5.3;


contract A {
    event E(uint);
    
    function () external payable {
        emit E(gasleft());
    }
}

contract B {
    address payable private _a;
    
    constructor(address payable a) public {
        _a = a;
    }
    
    function () external payable {
        (bool r, bytes memory b) = _a.call.value(msg.value).gas(1000)("");
        require(r);
    }
}
```

**Comment by k06a** [comment]
@zumzoom found interesting point: https://ethereum-magicians.org/t/remediations-for-eip-1283-reentrancy-bug/2434/28

> [Solidity compiler] checks that if the target of the CALL is a contract, and the Call Value is 0, then it adds 2300 to gas given to the call.

**Comment by k06a** [comment]
Do anyone knows if `estimateGas` knows about this trick? Seems it does not.

**Comment by k06a** [comment]
Final conclusions based on disassembly:
1. EVM adds 2300 gas stipend in case you transferring `> 0 wei`
2. Solidity compiler adds 2300 gas to call in case you transferring `== 0 wei`

**Comment by chriseth** [comment]
`estimateGas` ignores external calls because it cannot tell anything about the gas consumption.
