### ISSUE TITLE
[DOCS] Add link to universal mutator in tools section

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5861]
https://github.com/agroce/universalmutator - it seems to support solidity specifically.

**Comment by chriseth** [comment]
Suggested in https://github.com/ethereum/solidity/issues/1172#issuecomment-449480725

**Comment by agroce** [comment]
Yes, it does -- and it's now pretty battle-hardened, having run through 48K or so contracts from etherscan, bugs should mostly be worked out

**Comment by agroce** [comment]
(It now also handles vyper)
