### ISSUE TITLE
Feedback: Solidity "dictionary" to aid fuzz testing

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5863]
Fuzz testing benefits a great deal from dictionaries. A dictionary is a newline separated list of tokens that have special meaning for the program under test. The main benefit of having a dictionary is that, every once in a while, the fuzzer is going to pick an existing dictionary token towards mutation instead of coming up with something random.

For `solidity` @jonathanmetzman scraped the docs (see https://github.com/google/oss-fuzz/pull/2108#pullrequestreview-196077551) to create the following list of "Solidity" keywords. Would love feedback on this and/or suggestions to augment this list with more tokens sourced from elsewhere.

```
"continue"
"delete"
"do"
"else"
"for (a=0;a<2;a++)"
"function"
"if"
"new"
"return"
"switch"
"throw"
"try"
"while"
"pragma solidity ^90.90.0"
"pragma"
"<<"
">>"
"|"
"&"
"^"
"~"
"<="
"<"
"=="
"!="
">="
">"
"+"
"-"
"*"
"/"
"%"
"**"
"fixed "
"unfixed "
"ufixed128x128 "
"fixed128x128 "
"float "
"double "
"balance "
"transfer "
"send "
"true "
"false "
"call "
"callcode "
"delegatecall "
".gas()"
".value()"
"this"
"2e10"
"1.1"
"hex"001122FF""
"bool "
"byte "
"bytes1 "
"bytes2 "
"bytes3 "
"bytes4 "
"bytes5 "
"bytes6 "
"bytes7 "
"bytes8 "
"bytes9 "
"bytes10 "
"bytes11 "
"bytes12 "
"bytes13 "
"bytes14 "
"bytes15 "
"bytes16 "
"bytes17 "
"bytes18 "
"bytes19 "
"bytes20 "
"bytes21 "
"bytes22 "
"bytes23 "
"bytes24 "
"bytes25 "
"bytes26 "
"bytes27 "
"bytes28 "
"bytes29 "
"bytes30 "
"{ "
"} "
"("
")"
"public "
"contract "
"struct "
"returns "
"uint "
"uint256 "
"uint8 "
"int "
"int256 "
"int8 "
"bool "
"return "
"for"
"if"
"constructor "
"internal "
"external "
"pure "
"constant "
"view "
"payable "
"bytes32 "
"library "
"uint[] "
"uint[][5] "
"length "
"push "
"++"
"--"
"storage "
"memory "
"string "
"//"
";"
"block.blockhash("
"block.coinbase("
"block.difficulty("
"block.gaslimit("
"block.number("
"block.timestamp("
"gasleft("
"msg.data("
"msg.gas("
"msg.sender("
"msg.sig("
"msg.value("
"now("
"tx.gasprice("
"tx.origin("
" wei"
" finney"
" szabo"
" ether"
" seconds"
" minutes"
" hours"
" days"
" weeks"
" years"
"abi.encode("
"abi.encodePacked("
"abi.encodeWithSelector("
"abi.encodeWithSignature("
"assert("
"require("
"require("
"revert()"
"revert("
"addmod("
"compute("
"mulmod("
"compute("
"keccak256("
"sha256("
"sha3("
"ripemd160("
"ecrecover("
"this"
"selfdestruct"
"suicide"
"STATICCALL"
"event"
"log1"
"log2"
"log3"
"log4"
"is"
"DELEGATECALL "
"CALLCODE "
"using"
"self"
"console.log("
"anonymous"
"super"
"var"
```

**Comment by axic** [comment]
I suggest to read the keywords from `Token.h`.

**Comment by chriseth** [comment]
Also note that inside strings, we can have non-ascii characters. Not sure if it makes sense to fuzz that, though.

**Comment by bshastry** [comment]
> I suggest to read the keywords from Token.h.

thank you. Here's the list I created from there. It feels like all the building blocks are there, but I'm wondering if we should help the fuzzer a little by putting a few snippets together.

> "^="
"^"
"~"
"<<="
"<<"
"<="
"<"
"=="
"=>"
"="
">="
">>="
">>>="
">>>"
">>"
">"
"|="
"||"
"|"
"-="
"--"
"-"
","
";"
":"
"!="
"!"
"?"
"/="
"/"
"."
""
"("
")"
"["
"]"
"{"
"}"
"*="
"*"
"**"
"&="
"&"
"&&"
"%="
"%"
"+="
"+"
"++"
"abstract"
"address"
"after"
"alias"
"anonymous"
"apply"
"as"
"AS IS"
"assembly"
"auto"
"bool"
"break"
"byte"
"bytes"
"bytesM"
"calldata"
"case"
"catch"
"constant"
"constructor"
"continue"
"contract"
"copyof"
"days"
"default"
"define"
"delete"
"do"
"else"
"emit"
"enum"
"EOS"
"ether"
"event"
"external"
"false"
"final"
"finney"
"fixed"
"fixedMxN"
"for"
"function"
"hex"
"hours"
"if"
"ILLEGAL"
"immutable"
"implements"
"import"
"in"
"indexed"
"inline"
"int"
"interface"
"internal"
"intM"
"is"
"let"
"library"
"LT"
"macro"
"mapping"
"match"
"memory"
"minutes"
"modifier"
"mutable"
"new"
"null"
"of"
"override"
"partial"
"payable"
"pragma"
"private"
"promise"
"public"
"pure"
"reference"
"relocatable"
"return"
"returns"
"sealed"
"seconds"
"sizeof"
"static"
"storage"
"string"
"struct"
"supports"
"switch"
"szabo"
"throw"
"true"
"try"
"type"
"typedef"
"typeof"
"ufixed"
"ufixedMxN"
"uint"
"uintM"
"unchecked"
"using"
"var"
"view"
"weeks"
"wei"
"while"
"x"
"years"

**Comment by bshastry** [comment]
> Also note that inside strings, we can have non-ascii characters. Not sure if it makes sense to fuzz that, though.

@chriseth could you please provide an example of a non-ascii token just so we are on the same page. I'm guessing something like `<<` would qualify as one?

**Comment by jonathanmetzman** [comment]
> > I suggest to read the keywords from Token.h.
> 
> thank you. Here's the list I created from there. It feels like all the building blocks are there, but I'm wondering if we should help the fuzzer a little by putting a few snippets together.
> 
> > "^="
> > "^"
...

FYI there are some differences between the original tokens and these, worth pointing out:

1. The originals had spaces around certain tokens that need to be followed by a space. This makes it more likely that an insertion of the token results in an accepted parse.
2. Instead of saying "ufixedMxN", the original tokens had some examples of what "M" and "N" could be, I think this is more likely to be accepted as well.

Hard to know what the effect of the changes will be for sure. But I'm guessing the original versions are better.

**Comment by axic** [comment]
> "ILLEGAL"
> "LT"
> "x"

Some of these aren't actual keywords.
