### ISSUE TITLE
Build solc with asan for testing on CI

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5868]
Goal is to detected memory leaks in the current test cases.

**Comment by bshastry** [comment]
@axic What needs to be done to get the CI running? Is there an example of a previous CI configuration PR that one could use?

Also, what do you think about having additional CIs for UBSan and MSan to detect undefined behaviors and memory initialization errors?

**Comment by axic** [comment]
@bshastry sounds good I think.
