### ISSUE TITLE
Gas estimator takes a long time on large arrays

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5877]
Found by ossfuzz (12703)

Running `solc --gas` takes >30seconds on my machine.

[clusterfuzz-testcase-minimized-solc_noopt_ossfuzz-5745659351662592.txt](https://github.com/ethereum/solidity/files/2802613/clusterfuzz-testcase-minimized-solc_noopt_ossfuzz-5745659351662592.txt)

**Comment by cameel** [comment]
Closing because we decided to remove the gas estimator from the compiler: #13566.
