### ISSUE TITLE
Memory leak of 2704 bytes across 33 allocation sites

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5880]
## Description

(Found by ossfuzz issue number 12671)

While processing the following Soldity contract, the Solidity compiler leaks 2704 bytes of memory across 33 allocation sites

```
contract test {
    struct s1 {
        uint8 x;
        bool y;
    }
    struct s2 {
        uint32 z;
        s1 s1data;
        mapping(uint8 => s2) recursive;
    }
    s2 data;
    function check() public returns (bool ok) {
        return data.z == 1 && data.s1data.x == 2 &&
            data.s1data.y == true &&
            data.recursive[3].recursive[4].z == 5 &&
            data.recursive[4].recursive[3].z == 6 &&
            data.recursive[0].s1data.y == false &&
            data.recursive[4].z == 9;
    }
    function set() public {
        data.z = 1;
        data.s1data.x = 2;
        data.s1data.y = true;
        data.recursive[3].recursive[4].z = 5;
        data.recursive[4].recursive[3].z = 6;
        data.recursive[0].s1data.y = false;
        data.recursive[4].z = 9;
    }
}
```

## Environment

- Compiler version: Latest develop commit
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 LTS

## Steps to Reproduce

I had to compile the solfuzzer target with ASan first, like so

```
$ mkdir solidity_build
$ cmake -DUSE_Z3=OFF -DUSE_CVC4=OFF -DCMAKE_CXX_FLAGS="-fsanitize=address" ../solidity
$ make solfuzzer -j
```

and then I replayed the contract like so (shown below are the first few lines of a much bigger leak report output by ASan:

```
$ ./solfuzzer <contract.sol>
=================================================================                               ==21302==ERROR: LeakSanitizer: detected memory leaks                                                                                                                                            Indirect leak of 336 byte(s) in 3 object(s) allocated from:                                     
    #0 0x7f45c904b458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)                                                                                               #1 0x561dfa998044 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned long const, std::pair<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>, unsigned int> > > >::allocate(u
nsigned long, void const*) (/home/bhargava/work/github/solidity/build/test/tools/solfuzzer+0xc5d
044)
    #2 0x561dfa982c5f in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsig
ned long const, std::pair<boost::multiprecision::number<boost::multiprecision::backends::cpp_int
_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int
_check_type)0, void>, (boost::multiprecision::expression_template_option)0>, unsigned int> > > >
 >::allocate(std::allocator<std::_Rb_tree_node<std::pair<unsigned long const, std::pair<boost::m
ultiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multi
precision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::mult
iprecision::expression_template_option)0>, unsigned int> > > >&, unsigned long) (/home/bhargava/
work/github/solidity/build/test/tools/solfuzzer+0xc47c5f)
...
```

**Comment by axic** [comment]
Are you sure this log is for the issue 12671?

Ossfuzz has the following trace:
```

#6 0xa3cdd3 in operator[] /usr/local/include/c++/v1/map:1483
--
  | #7 0xa3cdd3 in dev::solidity::StorageOffsets::computeOffsets(std::__1::vector<std::__1::shared_ptr<dev::solidity::Type const>, std::__1::allocator<std::__1::shared_ptr<dev::solidity::Type const> > > const&) solidity/libsolidity/ast/Types.cpp:164
  | #8 0xa40bcb in dev::solidity::MemberList::memberStorageOffset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const solidity/libsolidity/ast/Types.cpp:204:21
  | #9 0xad7e61 in dev::solidity::StructType::storageOffsetsOfMember(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const solidity/libsolidity/ast/Types.cpp:2201:41
  | #10 0xf52651 in dev::solidity::ExpressionCompiler::visit(dev::solidity::MemberAccess const&) solidity/libsolidity/codegen/ExpressionCompiler.cpp:1367:47
```

**Comment by bshastry** [comment]
> Are you sure this log is for the issue 12671?

I'm pretty sure. The thing is leak in each allocation site has it's own stack trace so there should be 33 of them. I just copy pasted a portion of the top stack-trace :)

**Comment by axic** [comment]
The useful stack trace is the one from ossfuzz, though. It shows the code where the leak is created.

**Comment by bshastry** [comment]
iirc there are 33 allocation sites where memory is leaked. My hunch is that each one needs to be fixed separately. Let me report back when I have an update to share on this.

**Comment by axic** [comment]
I'm not sure where you take the number 33, because the report 12671 has no mention of it. Also as far as I can tell without meticulously going through all the stack traces, the majority of it is traced back to the same piece of code mentioned above.

**Comment by chriseth** [comment]
Hunch: This might be due to our mis-use of creating types without make_shared.

**Comment by bshastry** [comment]
> I'm not sure where you take the number 33, because the report 12671 has no mention of it

The reports can be better formatted, the number 33 is right at the bottom of the ASan report on the line that begins with the string "SUMMARY". It reads

> SUMMARY: AddressSanitizer: 2704 byte(s) leaked in 33 allocation(s).

**Comment by bshastry** [comment]
> Hunch: This might be due to our mis-use of creating types without make_shared.

I made some progress in finding out the source of the leaks. There seem to be the following buckets of leaks

> size of leaked object, number of leaked objects, total size (in bytes) of leak, source file, function, line (allocation site)
> 112, 3, 336, libsolidity/ast/Types.cpp, StorageOffsets::computeOffsets, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L164
> 112, 2, 224 bytes (across 2 objects), libsolidity/ast/Types.cpp, StorageOffsets::computeOffsets, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L164
> 80, 2, 160, libsolidity/ast/Types.cpp, Type::fromElementaryTypeName, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L301
> 114, 2, 228, libsolidity/ast/Types.cpp, Type::members, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L413
> 104, 1, 104, libsolidity/analysis/ReferencesResolver.cpp, ReferencesResolver::endVisit, https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/ReferencesResolver.cpp#L234
> 96, 3, 288, libsolidity/ast/Types.cpp, Type::members, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L413
> 96, 3, 288, libsolidity/ast/Types.cpp, StructType::copyForLocation, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L2151
> 80, 3, 240, libsolidity/ast/Types.cpp, MemberList::memberStorageOffset, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L203
> 80, 1, 80, libsolidity/ast/Types.cpp, Type::fromElementaryTypeName, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L301
> 72, 1, 72, libsolidity/ast/Types.cpp, Type::fromElementaryTypeName, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L321
> 48, 5, 240, libsolidity/ast/Types.cpp, Type::members, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L408
> 32, 5, 160, libsolidity/ast/Types.cpp, Type::members, https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L413

All but one leaks are in `libsolidity/ast/Types.cpp`, the exception being `libsolidity/analysis/ReferencesResolver.cpp.`

**Comment by bshastry** [comment]
One pattern of leaks is the leak of objects with shared_ptr references.

I wonder if this is due to some kind of circular refs like, object `A` holds a shared_ptr of `B` and vice versa so that when `A` and `B` are eventually destroyed, the shared_ptr ref counting does not go to zero due to there being a cycle, and the objects are leaked.

**Comment by chriseth** [comment]
Since this is all inside `Types.cpp`, it might be because of invalid calls to `shared_from_this`. The standard says that this will lead to an exception starting from C++17 (undefined behaviour until). Perhaps we could compile with C++17 to check?

**Comment by axic** [comment]
Tried compiling with C++17 and `libsolidity/ast/*` finished without any warnings.

**Comment by chriseth** [comment]
Did you run tests (not sure what "libsolidity/ast/* finished without any warnings" means)? It will only be detected at runtime.

**Comment by axic** [comment]
My message said "compiling". You didn't mention it is a runtime check, some other code won't compile with C++17 without changes, but the `ast` directory does.

**Comment by chriseth** [comment]
ok, thanks!

**Comment by axic** [comment]
Managed to compile, running tests.

**Comment by axic** [comment]
Shows no runtime errors.

**Comment by bshastry** [comment]
One more thing. Leak sanitizer (LSan) tells us that all the reported leaks are `indirect`. Here is the documentation regarding direct and indirect leaks from the LSan page:

> Another useful feature is being able to distinguish between directly leaked blocks (not reachable from anywhere) and indirectly leaked blocks (reachable from other leaked blocks).

This definition is not entirely clear to me, so I consulted the Dr. Memory (another memory error detector; NOT LSan). Here's how Dr. Memory defines direct and indirect leaks

> An indirect leak is a heap object that is reachable by a pointer to its start address, but with all such pointers originating in leaked objects. Leaks can be thought of as trees, with the top-level object the direct leaks and all child objects indirect leaks

Taken these definitions into consideration, I'm wondering why LSan does not tell us the "directly" leaked objects. That would presumably help us debug this better.

Meanwhile, I'm going to experiment a little with LSan options (https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#flags) so that we could get more clarity on the source of the leaks.

**Comment by axic** [comment]
Have working ASan on circleci: https://github.com/ethereum/solidity/tree/asan-clang

It detects (the EndToEnd tests are disabled):
```
SUMMARY: AddressSanitizer: 3880 byte(s) leaked in 49 allocation(s).
```

**Comment by bshastry** [comment]
I replayed the buggy input on solfuzzer via valgrind and it could reproduce the leak as well. Here's the valgrind summary:

> ==8841== HEAP SUMMARY:
==8841==     in use at exit: 2,976 bytes in 33 blocks
==8841==   total heap usage: 224,414 allocs, 224,381 frees, 13,551,143 bytes allocated
==8841==
==8841== Searching for pointers to 33 not-freed blocks
==8841== Checked 149,800 bytes
==8841==
==8841== 2,976 (112 direct, 2,864 indirect) bytes in 1 blocks are definitely lost in loss record 24 of 24

**Comment by axic** [comment]
I think #4517 is one of the earlier reports of this. Since this issue has more detail I suggest we close the other one.

**Comment by bshastry** [comment]
Minor update on this: oss-fuzz is run every day on the latest `develop` commit. However, it keeps tripping on already reported mem leaks, so I'm afraid we won't get new reports until the old ones are fixed.

Alternatively we could ask oss-fuzz to ignore leaks until the present leaks are fixed, but I'd only suggest this as a temporary solution.

**Comment by chriseth** [comment]
Let's ignore leaks.

**Comment by bshastry** [comment]
> Let's ignore leaks.

There is a problem if we decide to ignore leaks that I did not anticipate earlier. If we ignore leaks, Google is going to close previously reported bugs (mem leaks) as fixed. Another problem is that memory leaks (even if ignored) tend to accumulate and drain the fuzzing process out of memory (current memory limit is 2GB per fuzzing process).

Do we want to still go ahead with ignoring leaks?

**Comment by guylando** [comment]
If those are indirect leaks then the problem might not be at the Types.cpp at all (and everything pointed to it just because it is a very commonly used code) and would be useful to first track the direct leak objects and solve them and then re-run the tests to see if there are still indirect leaks.
None of those tools provide a dump of the direct leak objects which use the indirect leaked code?
The gist in https://github.com/ethereum/solidity/issues/4517 contains a reference to one direct leak

**Comment by christianparpart** [comment]
@bshastry After many months, I've been retesting your code snipped and it's fixed now (most likely due to the type system PR with strong ownership from a couple of months ago).

What's left are some "possibly lost" leaks due to Z3 that are, however, totally unrelated to this ticket and we couldn't track them down; so I'm closing this ticket.
