### ISSUE TITLE
The solc snap fails to build on xenial

### ISSUE THREAD

**Issue by come-maiz** [ethereum/solidity#5889]
## Description

Since building the solidity snap requires boost 1.65 (see #4612), the build started to fail (see https://launchpad.net/~elopio/+snap/solc-candidate/+build/438885).

There are multiple solutions, but I think the best would be to build the snap on bionic, which has boost 1.65 and should just work (tm). I am giving this a try right now.

**Comment by come-maiz** [comment]
It worked: https://launchpad.net/~elopio/+snap/solidity/+build/444690

@chriseth you will continue to see failures on build.snapcraft.io though, because that UI only allows to build on xenial. You can disable it until they support bionic, and in the meantime we use launchpad to build and release.

Another important thing is that we missed a beat, 0.5.3 didn't get into the snap store. We should leave this new bionic-based package for a while anyway, so more people get a chance to test it. I think it would be better to just wait and do the next stable snap release with 0.5.4.

**Comment by axic** [comment]
> Another important thing is that we missed a beat, 0.5.3 didn't get into the snap store. 

Can you still push it?

**Comment by come-maiz** [comment]
Yes, I can take the 0.5.3 tag, patch the snapcraft.yaml, build and push it manually. I'm not so comfortable with the patching part. I'm not sure how reproducible the build is so I don't know if people will be able to verify it.
