### ISSUE TITLE
Support calling library functions on literals

### ISSUE THREAD

**Issue by Arachnid** [ethereum/solidity#589]
With the introduction of support for 'internal' library functions, libraries now have a bunch of new uses, including adding new functionality to existing types like `string`. However, while doing `using foo for string` will allow you to call functions defined in `foo` on `string` instances, `"foo".foo()` still fails with an error.

It'd be really good if Solidity could treat literals the same way as variables of the same type, and allow calling library methods on them.

**Comment by VoR0220** [comment]
That might be difficult to pull off given the current architecture.

**Comment by Arachnid** [comment]
In the latest build this mysteriously already works for string literals!

**Comment by VoR0220** [comment]
Close this then?
