### ISSUE TITLE
Compact AST not available for option  --combined-json

### ISSUE THREAD

**Issue by thec00n** [ethereum/solidity#5896]
## Abstract

The compact AST can be generated by running `solc` with the option `--ast-compact-json`. It is currently not possible to include the compact AST in the combined JSON along with other elements from the outputSelection. Only the legacy AST is available e.g. `solc  --pretty-json --combined-json ast foo.sol`

## Specification

For the `--combined-json` option change the attribute `ast` to include the compact AST and introduce the attribute `legacyAST` that includes the legacy AST in the JSON output.

**Comment by chriseth** [comment]
The combined json is considered deprecated (though undocumented, sorry) in favour of standard-json. Are you relying on it heavily?

**Comment by thec00n** [comment]
We use it to generate test cases for the [SWC-registry](https://github.com/SmartContractSecurity/SWC-registry) e.g. `solc --pretty-json --combined-json ast,bin,bin-runtime,srcmap,srcmap-runtime foo.sol >foo.json` so a security analysis tool does not have to compile the test cases and can access AST/bytecode etc. Is there another way to do this with solc?

**Comment by chriseth** [comment]
solc supports standard-json. It is a little less convenient for the commandline but should be easy to use (perhaps easier?) in automated tools.

**Comment by thec00n** [comment]
In this case it be used from the command line. Looking at the Input and Output JSON Description from Solidity we can just create a small wrapper, so it's just as convenient if not more :) I am ok if we close the issue, thanks for the clarification.
