### ISSUE TITLE
Creating a memory array of length 0 generates an infinite loop 

### ISSUE THREAD

**Issue by Arachnid** [ethereum/solidity#590]
The following code produces asm that generates an infinite loop:

```
contract StringsTest {
    function testEmptyArray() {
        new string[](0);
    }
}
```

Even better, it seems to crash browser solidity, rather than simply running out of gas.

**Comment by VoR0220** [comment]
nice

**Comment by axic** [comment]
It was reported to browser-solidity with `uint` arrays a while ago: https://github.com/chriseth/browser-solidity/issues/107

Probably it is not limited to strings, rather to initialising dynamic arrays.

Does the code includes an infinite loop or the VM has a bug?

**Comment by Arachnid** [comment]
I suspect both; I disassembled the contract, and it appears to output a loop that predecrements, checking when it reaches zero. That's definitely wrong, but the VM should run it out of gas, not just hang.

**Comment by axic** [comment]
I don't think it actually hangs, just you have to have nerves to wait until it finishes given the "unlimited" nature of the gas limit: `3000000000`

There's a change to rework the gas handling in browser-solidity, so that should be "fixed" soon-ish.

**Comment by axic** [comment]
browser-solidity is fixed with this PR https://github.com/ethereum/browser-solidity/pull/130
