### ISSUE TITLE
[DOCS] abi.encode/decode are not well documented

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#5902]
It seems to be available since solidity 0.5.x, as linked in https://github.com/ethereum/solidity/pull/4390 but I couldn't find any documentation. I figured out it should be used like this
`abi.decode(data, (T1, T2, ...., Tn))` by reading some comments on https://github.com/ethereum/solidity/issues/3876

As it's not documented, it's also unclear if this feature is "stable" for "production".

abi.encode is mentioned in https://github.com/ethereum/solidity/blob/v0.5.3/docs/types/value-types.rst which I seems to be a odd place to be, being there because of call,delegatecall,staticall wich needs the encode. 

Seems like it should have a dedicated section to the "abi." members and their usage.

**Comment by chriseth** [comment]
@3esmit the "documentation" for all those functions can be found [here](https://solidity.readthedocs.io/en/v0.5.3/miscellaneous.html#global-variables) not sure if it is extensive enough. We should probably at least mention that `abi.decode` reverts if the input data is invalid.

**Comment by 3esmit** [comment]
Oh, indeed is there! Interesting that I used the search in docs website and it don't finds it!
https://solidity.readthedocs.io/en/v0.5.3/search.html?q=decode&check_keywords=yes&area=default

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 It seems the information is actually present in the docs.
