### ISSUE TITLE
Document translation in Japanese?

### ISSUE THREAD

**Issue by akira-19** [ethereum/solidity#5908]
Is there any ongoing translation plans in Japanese?
If not, I'd like to help that.

**Comment by ChrisChinchilla** [comment]
@akira-19 Not at the moment, but we'd love to have some! I am actually about to contact all the ongoing translation efforts to find out how they are doing, so I'll include you in that task very soon.

**Comment by ChrisChinchilla** [comment]
Moved to #5918
