### ISSUE TITLE
Optimizer does not properly re-use stack slots

### ISSUE THREAD

**Issue by aleph-v** [ethereum/solidity#5914]
The following should compile with enabled optimizer:
```
pragma solidity ^0.5.3;

contract fib{
    function calcluation() external returns(uint ret){
        assembly{
            let one := 1 
            let two := 1 
            let three := add(one, two)
            let four := add(three, two)
            let five := add(four, three)
            let six := add(five, four)
            let seven := add(six, five)
            let eight := add(seven, six)
            let nine := add(eight, seven)
            let ten := add(nine, eight)
            let eleven := add(ten, nine)
            let twelve := add(eleven, ten)
            let thirteen := add(twelve, eleven)
            let fourteen := add(thirteen, twelve)
            let fifteen := add(fourteen, thirteen)
            let sixteen := add(fifteen, fourteen) //This line gives us 17 stack varibles so a complilation error
            ret := sixteen
        }
    }
}
```
Original report:

--------

## Abstract
Assembly pops should remove variables from the set of local variables since they free up space on the stack and allow the compiler to know which stack variables are unnecessary. This would allow 'pop' to remove stack depth compiler errors and developers more precisely control the stack.

## Motivation
I have been building a cryptographic library to optimize elliptic curve verification for non solidity curves using solidity assembly. I have been hitting many "Stack depth too deep try removing local variables" and have had to turn to {} followed by blocks of if statements which wouldn't be needed inside of the {}. I know exactly which variables are unnecessary so I would like to be able to make solidity remove them from the local scope. Here's how awkward the code to remove stack depth errors looks in practice https://github.com/pvienhage/ghost-wallet/blob/master/contracts/p256.sol#L156  [not to mention that this extra jumpi is going to add close to 5K gas to my code because it has to be called up to 512 times]     

## Specification
The natural candidate for a keyword which delists a local variable is pop since it should be removing it from the stack anyway. After the implementation of this feature pop wouldn't just remove the variable from the stack but also clear it from the local variable context and thus allow access of a local variable which is in the 17th stack position [or addition of a new local variable]. 

Please note that I don't have any experience with compilers so cannot provide a more detailed technical specification of how this would work with the internals of the compiler, sorry.

## Backwards Compatibility
This should cause little to no issues with backwards compatibility because (1) if variables are getting popped you can't use them again anyway (2) this is a pure assembly feature and very few programs hit the stack depth error in assembly.

**Comment by chriseth** [comment]
Can you provide specific small examples please? We recently improved the stack allocation logic, so what you are proposing might already be implemented.

**Comment by aleph-v** [comment]
```
pragma solidity ^0.5.3;

contract fib{
    function calcluation() external returns(uint ret){
        assembly{
            let one := 1 
            let two := 1 
            let three := add(one, two)
            let four := add(three, two)
            let five := add(four, three)
            let six := add(five, four)
            let seven := add(six, five)
            let eight := add(seven, six)
            let nine := add(eight, seven)
            let ten := add(nine, eight)
            let eleven := add(ten, nine)
            let twelve := add(eleven, ten)
            let thirteen := add(twelve, eleven)
            let fourteen := add(thirteen, twelve)
            let fifteen := add(fourteen, thirteen)
            pop(one) //We are removing local varibles, but no matter how many we remove we still get stack depth errors
            pop(two)
            pop(three)
            pop(four)
            pop(five)
            pop(six)
            let sixteen := add(fifteen, fourteen) //This line gives us 17 stack varibles so a complilation error
            ret := sixteen
        }
    }
}
```

In this case no matter how many local variables we remove we still get stack depth errors.

**Comment by chriseth** [comment]
Hm, this is weird - when you enable the optimizer, the code generator should actually re-use existing stack slots - you do not (and actually should not) use explicit pops.

**Comment by aleph-v** [comment]
I'm not actually using the optimizer, since I've tried it on some of the assembly code I had written and it actually almost doubled the gas usage [which is because it is edge case code]. But I also just tried the code with the optimizer enabled and it still produced a stack depth error.

**Comment by chriseth** [comment]
Sorry for hijacking your feature proposal. We are thinking about explicit scopes for variables, which could be what you want, but I don't think `pop(a)` would be a nice syntax for that.

**Comment by chriseth** [comment]
About the gas usage: Can you share some details? Did you try fiddling with the `--runs` parameter to adjust the tradeoff?

**Comment by aleph-v** [comment]
I was using the {} when I ran into this issue, but having a block based scoping system makes it had to implement some of the behavior I would want because then you can't end the scope inside of an if loop for example so I had to implement pairs of if loops inside and outside of scope. It may not be pop that makes it work but I still want more ability to manage scope.

**Comment by aleph-v** [comment]
Here's how my code reacts to the optimizer:
No optimizer: 324121 gas
50 runs: 595414 
100 runs: 587608
200 runs: 584176
500 runs: 584086
2000 runs: 583309
20000 runs: 317362
200000 runs: 317362
Which means that the optimizer actually only ends up working better for more than 20 thousand runs

**Comment by chriseth** [comment]
Currently, enabling the optimizer should free the stack slot used by a variable as long as it is not used anymore (but it does not). We do not yet provide fine-grained control over the optimizer, so it is just an on/off-switch, but that should soon change. Then, you should be able to only activate storage slot allocation and none of the other optimizations.

**Comment by chriseth** [comment]
Which gas are you measuring? Deploy gas or runtime gas? Can you share the output assembly for the different settings?

**Comment by chriseth** [comment]
Ah I see, you have many big constants. If stored literally, big constants are extremely expensive at deploy time, but cheap at runtime. The `--runs` parameter will instruct the optimizer to select one among 3 or 4 ways to store them, each way has different trade-offs between deploy and runtime costs.

**Comment by aleph-v** [comment]
Ahhh yeah I figured it would be something like that where the cost was coming from somewhere else. I'm going to be using the big constants because I'd like to make the calls cheap for users, but it makes sense why the optimizer would weight for only this deployment.

**Comment by axic** [comment]
I was thinking about this on the weekend and another useful feature we could introduce is constants, to aid the optimiser (`constant x = 0x1234` or `const x = 0x1234`). In the above example that could already save two stack slots.

> We are thinking about explicit scopes for variables, which could be what you want, but I don't think `pop(a)` would be a nice syntax for that.

Instead of `pop` we had `drop` in the Yul design, I think that is more suitable. Though I'm not sure I'd make it an expression (function) or a special statement: `drop x`.
