### ISSUE TITLE
Return statement on functions that are not view or pure do not issue an error

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#5917]
## Description

When a function that has not been marked as view or pure, is declared with a return parameter, it will not return the parameter as it only returns the transaction hash. However, the compiler does not warn the developer about this.

## Environment

- Current version:0.5.3+commit.10d17f24.Emscripten.clang

## Steps to Reproduce

```
pragma solidity ^0.5.3;

contract Clipboard {
    string public content;
    
    constructor(string memory initialContent) public {
        content = initialContent;
    }
    
    function setClipboard(string memory newContent) public returns (string memory) {
        content = newContent;
        return content; //this return does not come
    }
}
```

## Related Issues

I tried to find if this was a duplicate, but couldn't find anyone reporting exactly the same.

**Comment by chriseth** [comment]
Your contract neither has a view nor a pure function. Are you sure this is a bug?

**Comment by zemse** [comment]
The issue that I'm trying to point out is only with functions that modify storage variables. As functions marked as view or pure can be called without doing a transaction and we can see the return value but other functions (that modify storage variables) cannot be directly called, we have to do a transaction to call these functions. Just like the following function:
```
function setClipboard(string memory newContent) public returns (string memory) {
    content = newContent;
    return content;
}
```
If we actually deploy the contract and do a transaction for this function and wait for the output, we only get the transaction hash returned but not the return value. Compiler should give a warning that there is no point in writing return statements for functions that will require a transaction for invoking as transaction hash will be returned instead of variable in return statement.

**Comment by chriseth** [comment]
Ah, now I see. The purpose of return values in functions that require (actually only recommend) a transaction is that they can be called from other contracts.

Also note that you actually can call such functions using `eth_call`, it is just the default to make a transaction.

**Comment by zemse** [comment]
Oh, now I understood the purpose of having the return statement in such functions.
