### ISSUE TITLE
Support nested array arguments

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#594]
- [ ] calldata decoder
- [ ] calldata decoder for memory (passing arguments to base constructor)
- [ ] calldata encoder

**Comment by VoR0220** [comment]
nested array arguments? As in 2D arrays to a function parameter?

**Comment by chriseth** [comment]
Yes.

**Comment by axic** [comment]
This is implemented in 0.4.19:

```
pragma experimental ABIEncoderV2;

contract A {
  function A(uint[][][] x) {}
}

contract C is A {
  function C(uint[][][] x) A(x) {
  }
}
```

**Comment by NextZeus** [comment]
nested arguments only worked with internal function, but not with external function.

**Comment by NextZeus** [comment]
external function can accept bytes array as arguments .
