### ISSUE TITLE
Make sure the life-time of all objects bound in lambdas in ``ABIFunctions`` is guaranteed.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#5948]
``ABIFunctions::tupleEncoder`` and ``ABIFunctions::tupleDecoder`` store lambdas binding references to ``TypePointers``. Those lambdas will only be called much later in ``ContractCompiler::appendMissingFunctions``. This doesn't seem to cause problems so far (it seems all types are still living at that point), but we should consider binding copies of the shared pointers in the lambdas instead to ensure that everything still lives when the lambdas are actually called.

Maybe on a closer look it'll turn out that it's fine as it is, but we should double-check.

**Comment by chriseth** [comment]
I actually stumbled across this myself multiple times, so we should probably document it, I just don't know where.

In my opinion, it is fine, because the lambdas are either evaluated right away or discarded. What is stored for longer is just the result value of the lambda.

**Comment by ekpyron** [comment]
You're right, yes. And I even think it might be fine without further documentation - if we want to document it, I think the documentation of ``ABIFunctions::createFunction`` and  ``ABIFunctions::createExternallyUsedFunction`` in the header would be the right place, but I'm fine with closing this issue.
