### ISSUE TITLE
Properly fix issues with solc-js tests

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5963]
We forced the version of tape to 4.9.2 as a [quick measure](https://github.com/ethereum/solc-js/pull/339) before the release of 0.5.4. It is not clear where the problem lies, so this should be fixed properly.

Also the change in https://github.com/ethereum/solidity/issues/5963 should be reverted or revisited.

**Comment by Marenz** [comment]
#5963 is this issue.. ?

**Comment by chriseth** [comment]
I think it's this: https://github.com/ethereum/solc-js/pull/339

**Comment by chriseth** [comment]
Actually no, I don't really know what was meant to be linked here.
