### ISSUE TITLE
Reorganize syntax test files

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5967]
## Motivation

The current folder structure in `test/libsolidity/syntaxTests` is very inconsistent. We should restructure them.

## Specification

To be discussed.

**Comment by ekpyron** [comment]
We could try creating a nice structure for the semantics tests while extracting - if that works we can later sort the syntax tests into that directory structure (at least if at some point syntax and semantics tests will end up being somewhat merged).

I would prefer ordering by features being tested, but as @chriseth mentioned a lot of tests will match/test multiple features, so we need some kind of order of precedence for this to work... Personally I don't have any kind of complete list of features that are being tested in mind...

We could also split into two general kinds of tests - those testing that something works (without warning) and those who cover all cases under which a particular error/warning should be triggered. While the first kind of tests should be sorted by features, the latter could be sorted by compiler component, file name and even class/function name or line number (well maybe that's too much) in which the error is triggered, as @Marenz suggested.

**Comment by ekpyron** [comment]
We'll fix this iteratively whenever touching/adding tests. Closing the issue.
