### ISSUE TITLE
Compile semantic tests /w --no-ipc given

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#5969]
## Motivation

If the option `--no-ipc` is passed to `soltest` or `isoltest`, the file-based semantic tests should still be compiled (currently, they are not created at all).

## Specification

This requires the `no-ipc` option to be passed down to the semantic test case and needs to be handled there. A warning about this behaviour being triggered is also needed.

**Comment by Marenz** [comment]
ipc has been removed with evmone, closing....
