### ISSUE TITLE
The solc snap fails to build because it needs a newer z3

### ISSUE THREAD

**Issue by come-maiz** [ethereum/solidity#5985]
## Description

The [solc snap is failing to build](https://launchpadlibrarian.net/411054626/buildlog_snap_ubuntu_bionic_arm64_solidity_BUILDING.txt.gz) because it now requires z3 4.6.0 or higher.

This version is not in the ubuntu archive, so we will have to build it from source. PR coming...

**Comment by chriseth** [comment]
Note that you can also use cvc4, this is what we do for the PPA ubuntu release!
