### ISSUE TITLE
InternalCompilerError when upgrading to solidity 0.5.4

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#5997]
The following code works just fine with `solc 0.5.3`

```
pragma solidity ^0.5.3;
pragma experimental ABIEncoderV2;

library ECDSALib
{
	function recover(bytes32 hash, bytes memory sign)
	public pure returns (address)
	{
		bytes32 r;
		bytes32 s;
		uint8   v;
		require(sign.length == 65);
		assembly
		{
			r :=         mload(add(sign, 0x20))
			s :=         mload(add(sign, 0x40))
			v := byte(0, mload(add(sign, 0x60)))
		}
		if (v < 27) v += 27;
		require(v == 27 || v == 28);
		return ecrecover(hash, v, r, s);
	}
}
```

However, when moving to `solc 0.5.4` (other parts of my code could benefit from calldata structs) I get an error:

`InternalCompilerError: Non-padded and in-place encoding can only be combined.`

Apparently its the `ecrecover` call that fails, if I comment it and replace it with `return address(0)` the compilation passes.

**Comment by bshastry** [comment]
Thank you for reporting the bug @Amxx 

Using our libfuzzer setup, a more concise proof-of-bug program is the following

```
pragma experimental ABIEncoderV2;
library E
{
        function r(byte hash) public
        {
                byte r;
                byte s;
                uint8 v;
                ecrecover(hash,v,r,s);
        }
}
```
