### ISSUE TITLE
address of created contract

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#60]
Tutorial has:

```
contract TokenCreator {
  function createToken(bytes32 name) returns (address tokenAddress) {
    // Create a new Token contract and return its address.
    return address(new OwnedToken(name));
  }
```

how does createToken work?  creating a contract requires eth_sendTransaction, but transactions don't have return values...

**Comment by nmushegian** [comment]
Contracts can create contracts. There's an op for it, you give it some code and it returns the address of the new contract. That's what the `new` keyword gets compiled to.

**Comment by ethers** [comment]
thanks @nmushegian   I added short note to wiki
