### ISSUE TITLE
Incorrect topic[0] hash for Events that have Structs

### ISSUE THREAD

**Issue by BrendanChou** [ethereum/solidity#6001]
## Description

When hashing for the topic[0] of an event, solidity uses the name of the struct rather than the canonical type (which is a tuple, at least when calculating hashes for function signatures).

## Environment

- Compiler version: 0.5.4 stable
- Framework/IDE: Truffle

## Steps to Reproduce
Given:
```
pragma experimental ABIEncoderV2;
library LibName {
    struct StructName {
        bytes32 myBytes;
        address myAddress;
    }
}
contract MyContract {
    event Loggy(uint256 indexed myNumber, LibName.StructName myThing);
}
```

`Loggy` has a topic[0] of: `keccak256("Loggy(uint256,LibName.StructName)")`
but it should be: `keccak256("Loggy(uint256,(bytes32,address))")`

Clearly, changing the name of the library or struct should not change the event signature (if the types within the struct have not changed)

Expected behavior is outlined here but is not 100% clear:
https://solidity.readthedocs.io/en/develop/abi-spec.html?highlight=function%20selector#events
The way web3 v1.0.0-beta.37 is currently parsing it is how I've outlined above (as if it were a non-truncated function signature)

**Comment by AntonioJuliano** [comment]
Also as another example, if you have:

```solidity
library LibName {
    struct StructName {
        bytes32 myBytes;
        address myAddress;
    }

    event LogInLibrary(uint256 indexed myNumber, LibName.StructName myThing);

    function fun() internal {
         ...
         emit LogInLibrary(uint256 indexed myNumber, StructName myStruct);
    }
}
```

`LogInLibrary` will have a topic[0] / signature of: `keccak256("LogInLibrary(uint256,LibName.StructName)")` (notice that `LibName.` is still included even though it's not in the solidity code because the struct is defined within that file)

**Comment by chriseth** [comment]
Thanks for the great find! From the examples, it sounds like a library needs to be involved somehow. Is that true?

**Comment by BrendanChou** [comment]
Unsure if the same problem occurs for events defined in contracts

**Comment by chriseth** [comment]
@BrendanChou no worries, it has been fixed already :)
