### ISSUE TITLE
GitHub repo for Solidity fuzzing corpus

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6005]
## Description

At the moment, the ossfuzz build script picks up all solidity/yul test inputs to seed fuzzing. This is sub-optimal because several test inputs are redundant and several others give the fuzzer a hard time e.g., needlessly big source file.

It would be nice if we could have a separate repo for fuzzer test input per fuzzing target. We could have a repo called `ethereum/solidity-fuzzing-corpus` that then contains one corpus directory per fuzzing target. Something like so
  - `solidity_seeds`
  - `yul_seeds`
  - `strict_assembly_seeds`

... and so on and so forth.

What do you think?

**Comment by chriseth** [comment]
Sounds good!

**Comment by bshastry** [comment]
@chriseth great, I don't have the permissions to create repo. Could you please do it for me? Thanks

The repo can be called `solidity_fuzzing_corpus` or something like that.

**Comment by chriseth** [comment]
Created and added you as admin: https://github.com/ethereum/solidity-fuzzing-corpus

**Comment by bshastry** [comment]
Thank you @chriseth !
