### ISSUE TITLE
Find the lost AppVeyor tests.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6007]
AppVeyor doesn't seem to run on our PRs anymore (does anybody have a counterexample?), so we should check why that is.

**Comment by erak** [comment]
AppVeyor does run the the tests, but it doesn't communicate with Github anymore. You're account needs to be linked with the `ethereum-free` one. @chriseth can probably help with the missing permissions.

**Comment by chriseth** [comment]
I think what fixed it was to give @chfast write permission to the solidity repo - his account is linked to the ethereum-free account on appveyor.
