### ISSUE TITLE
Grammar should be more visible in the docs.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6014]
The solidity grammar is extremely well hidden away in
``Solidity In Depth -> Miscellaneous -> Cheatsheet -> Language Grammar``.
I would say it deserves a top-level entry in ``Solidity In Depth`` or *at the very least* in ``Solidity In Depth > Miscellaneous``.

**Comment by axic** [comment]
Fixed by #8505. The antlr grammar is exposed now.

**Comment by ekpyron** [comment]
It's not! This is about moving it to somewhere where it's visible in the docs!

**Comment by axic** [comment]
![Screenshot 2020-05-05 at 11 29 33](https://user-images.githubusercontent.com/20340/81057107-b4203d00-8ec3-11ea-8053-fec213060e49.png)

This is what I see, I would say it is not that hidden.

**Comment by ekpyron** [comment]
Alright, my bad.
