### ISSUE TITLE
[SMTChecker] Simplify AST before SMTChecker

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#6032]
The Solidity AST could be simplified syntactically to make it easier for the SMTChecker.

- [ ] Replace compound assignments by the full expression #6033 
- [ ] Guard the rest of a scope after a return #6031 
- [ ] Unary increment/decrement
- [ ] Remove redundant "tuples" like in `(((x)))`

More ideas?

**Comment by chriseth** [comment]
Remove redundant "tuples" like in `(((x)))`.

**Comment by leonardoalt** [comment]
Moving on to implement these directly in the SMTChecker.
