### ISSUE TITLE
[Yul] Remove gas meter test workaround when we can enable the yul optimizer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6044]
Some checks in the GasMeterTestFramework are skipped when the tests are forced to ABIEncoderV2. This is because without the yul optimizer turned on, the generated code is so complicated that the gas meter cannot estimate the gas anymore. This should not be the case once yul optimizations are activated and these skips should be removed again.

**Comment by cameel** [comment]
Closing because we decided to remove the gas estimator from the compiler: #13566. We will be removing its tests as well.
