### ISSUE TITLE
[SMTChecker] Support conversion from string to bytes

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#6052]

**Comment by axic** [comment]
This raises no complaints, so maybe this is supported?
```
pragma experimental SMTChecker;
contract C {
  function f() public view {
    string memory x = "";
    bytes memory y = bytes(x);
    assert(bytes(x).length == 0);
  }
}
```

Perhaps add it into the smt tests and close this issue.

**Comment by leonardoalt** [comment]
Can you try with values larger than 32 bytes? Or actually with smaller ones as well, but non empty?

**Comment by axic** [comment]
No complaint with `string memory x = "not empty"`, nor with `string memory x = "this is longer than 32 this is longer than 32 this is longer than 32 this is longer than 32";`.

**Comment by leonardoalt** [comment]
But is the assertion about the length still correct?

**Comment by axic** [comment]
Oh, you are right, it doesnt picks it up 😕

**Comment by leonardoalt** [comment]
I think that's rather a problem in the assignment to string though. The conversion to bytes should pick it up if the assignment worked in the first place.

**Comment by leonardoalt** [comment]
Closing because of the last comment.
