### ISSUE TITLE
Cyclic Imports are not possible in 0.5+

### ISSUE THREAD

**Issue by nuevoalex** [ethereum/solidity#6061]
## Description / Steps to Reproduce

Interaction: I have two contracts:

#### `Parent.sol`
```
import 'trading/Child.sol';
contract Parent {
    Child public child;
}
```
#### `Child.sol`
```
import 'reporting/Parent.sol';
contract Child {
    Parent public parent;
}
```

Prior to 0.5 this can be achieved in my code base by using an empty prefix remapping. As that is no longer permitted in 0.5+ I attempted to use a prefix of `ROOT` and added this to my imports. However this results in errors such as:

```
core/source/contracts/reporting/Parent.sol:2:1: DeclarationError: Identifier already declared.
E               contract Parent {
E               ^ (Relevant source part starts here and spans across multiple lines).
E               core/source/contracts/reporting/Parent.sol:1:1: The previous declaration is here:
E               import 'ROOT/trading/Child.sol';
```

I believe this is due to how the files are keyed when doing compilation as indicated in this issue: https://github.com/ethereum/solidity/issues/2665. I can reproduce this on an earlier compiler version by using the prefix in my remappings as well but now that an empty prefix is not allowed I do not believe there is a workaround for this.

Any assistance would be greatly appreciated as this blocks moving the Augur contracts to 0.5.

## Environment

- Compiler version: 0.5.4
- Framework/IDE (e.g. Truffle or Remix): Raw Solc
- Operating system: Ubuntu

**Comment by chriseth** [comment]
Could you provide the full commandline or standard-json input you use for this? Thanks!

**Comment by axic** [comment]
I wonder what is the reason for doing it this way and not by creating interfaces?

**Comment by nuevoalex** [comment]
@axic For the real use case this is actually occurring with interfaces where interface A imports interface B which imports interface A. I'm currently bypassing this in our case by manually skipping those contract interfaces in the compilation step.

@chriseth : Similar to the one in the previous issue 
```
{
    "language": "Solidity",
    "sources": {
        "filename": {
            "urls": [ "/app/src/reporting/Parent.sol" ]
        }
    },
    "settings": {
        "remappings": [ "ROOT=/app/src" ],
        "optimizer": {
            "enabled": True,
            "runs": 200
        },
        "outputSelection": {
            "*": {
                "*": [ 'metadata', 'evm.bytecode', 'evm.sourceMap', 'abi' ]
            }
        }
    },
}
```

**Comment by chriseth** [comment]
@nuevoalex as explained in the previous issue, if you use `"filename": { "urls": [...] }` then the name of the source file is `filename` and not `Parent.sol`. Is this really the full input? I'm asking because it only specifies a single file - is the rest auto-discovered by the compiler?

**Comment by chriseth** [comment]
I was able to reproduce it, and in its basic form, it is fully unrelated to remappings.

If the input is in the following form, it does not work:
```
{
    "language": "Solidity",
    "sources": {
        "filename": {
            "urls": [ "/tmp/a/reporting/Parent.sol" ]
        }
    },
    "settings": {
        "remappings": [ "ROOT=/app/src" ],
        "optimizer": {
            "enabled": true,
            "runs": 200
        },
        "outputSelection": {
            "*": {
                "*": [ "metadata", "evm.bytecode", "evm.sourceMap", "abi" ]
            }
        }
    }
}
```

If you replace the name of the file by its actual name, though, it works:
```
{
    "language": "Solidity",
    "sources": {
        "reporting/Parent.sol": {
            "urls": [ "/tmp/a/reporting/Parent.sol" ]
        }
    },
    "settings": {
        "remappings": [ "ROOT=/app/src" ],
        "optimizer": {
            "enabled": true,
            "runs": 200
        },
        "outputSelection": {
            "*": {
                "*": [ "metadata", "evm.bytecode", "evm.sourceMap", "abi" ]
            }
        }
    }
}
```

In the first form, you tell the compiler that there is a filename called `filename` with some contents (wherever they may come from). This file thin imports "trading/Child.sol" which in turn imports "reporting/Parent.sol". The compiler does not see that this is the same file - because you gave it a different name and because of that loads it as a different file.

**Comment by axic** [comment]
This also raises the question why do we allow importing files through jsonio which are not specified in the `sources` list?

I think every accessible file should be listed and the read callback is used if they are listed by path/url and not by content.

Doing so would make the behaviour of standard json through `solc` and other means similar.

**Comment by chriseth** [comment]
We have to allow auto-discovery because otherwise, tools need to parse the files and discover dependencies themselves. We could require the file name to match, perhaps.

**Comment by Marenz** [comment]
So the fix is to make the compiler aware that even though the name differs, the two files are the same?

**Comment by chriseth** [comment]
I would say the fix is to use the same name for the same file, i.e. "not a bug".

**Comment by Marenz** [comment]
Hmm can we still detect it and at least issue a warning?

**Comment by chriseth** [comment]
You mean if we have two identical files with different names? Not sure if that would not have false positives...
