### ISSUE TITLE
Potentially unreachable code in TypeChecker.cpp

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#6062]
See the red llines in 
 https://codecov.io/gh/ethereum/solidity/src/develop/libsolidity/analysis/TypeChecker.cpp#L2275

I couldn't find a way to trigger it. @ekpyron said it might be related to [30d9961](https://github.com/ethereum/solidity/commit/30d9961efb7c0056a2b189b642489bee92048442)

**Comment by chriseth** [comment]
Please turn them into assertions.

**Comment by axic** [comment]
@Marenz is this issue still open?

**Comment by Marenz** [comment]
this is still open, yes

**Comment by chriseth** [comment]
It's really hard to track down now which were the lines. Closing.
