### ISSUE TITLE
mstore at far away addresses slows down the yul interpreter

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6077]
## Description

The Yul interpreter takes a long time to interpret stores at far-away addresses.

Example
```
{mstore(8888888,4)}
```

Likely cause is the for loop in the second link.

The interpretation of mstore happens here 
https://github.com/ethereum/solidity/blob/46a9ed12da07e626e2cedbf20a8baa357a073758/test/tools/yulInterpreter/EVMInstructionInterpreter.cpp#L272-L275

Here, memory contents are printed out starting from address 0 in steps of 32 bytes. 
https://github.com/ethereum/solidity/blob/46a9ed12da07e626e2cedbf20a8baa357a073758/test/libyul/YulInterpreterTest.cpp#L142-L144

## Solution

We could emulate stores/loads modulo some small prime number. That way, the effective range of the for loop is limited.

**Comment by axic** [comment]
I think it should only dump the modified area with `...` prepended/appended if there is available memory before/after.

**Comment by chriseth** [comment]
I agree - there is a TODO in the code that asks for a "vector with holes" to be used for memory.

**Comment by chriseth** [comment]
If you think that the logging is the problem instead of just storing the memory, we could also just get rid of the dump.

**Comment by bshastry** [comment]
I think #6800 should fix this issue

**Comment by axic** [comment]
@bshastry was this fixed?

**Comment by bshastry** [comment]
This has been fixed.
