### ISSUE TITLE
extcodecopy with large size parameter drains yul interpreter memory

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6078]
## Description

This code
```
{extcodecopy(8888888,88888888,0,88888889)}
```

makes the interpreter allocate a large amount of memory in one chunk and slows it down.

**Comment by chriseth** [comment]
I think this is a duplicate of #6077

**Comment by bshastry** [comment]
@chriseth I don't think so. Disabling memory and storage traces has no effect on this bug.

**Comment by bshastry** [comment]
I think this will be fixed by #6800

**Comment by axic** [comment]
@bshastry was this fixed?

**Comment by bshastry** [comment]
Closing cos fixed
