### ISSUE TITLE
Switch EVM version to petersburg by default

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6084]
Given "Constantinople" should go live 28th of February and 0.5.0 is planned for 5th of March I'd suggest we switch Constantinople on by default to provide gas savings.

**Comment by chriseth** [comment]
Yep, sounds good!

**Comment by axic** [comment]
If agree on #6086 we should actually set it to "Petersburg".

**Comment by chriseth** [comment]
I'm not too sure about that. People probably wonder what is meant by that...

**Comment by axic** [comment]
Depends on #6086.

**Comment by axic** [comment]
Turns out this will break Remix. Either https://github.com/ethereum/remix-ide/issues/1282 or https://github.com/ethereum/remix-ide/issues/1620 needs to be finished, cc @yann300.

I'd however argue we shouldn't revert this change because the feature requests have been out for a year.

**Comment by chriseth** [comment]
Confirmed locally that latest remix works with the compiler and shift instructions work both in the debugger as well as in the VM.
