### ISSUE TITLE
Designating Unused Variables To Avoid Warnings

### ISSUE THREAD

**Issue by AusIV** [ethereum/solidity#6098]
## Abstract

Under certain circumstances, variables must be declared even though there is no use for them. It should be possible to designate these variables as unused to avoid the "Unused local variable" compiler warnings.

## Motivation

Solidity functions can return more than one variable. In a situation where a contract only cares about one of the returned variables, it is still necessary to declare and set the other variables. Because these variables are declared but not used, the compiler raises an Unused local variable warning. Given that I did not specify the interface for the function I'm calling, there's no way for me to avoid this warning.

## Specification

In Go (where unused variables produce an error, rather than a warning), it is allowed to assign an unused variable to `_` to avoid the unused variable error. I would propose that any unused variables assigned to the variable name `_` simply be ignored by the compiler and no warning should be raised.

## Backwards Compatibility

The only potential backward compatibility issue is that in cases where someone declares a variable named `_` intending to use it will no longer get the backward compatibility warning. It shouldn't change the compiled bytecode, just the warnings generated by the compiler.

**Comment by chriseth** [comment]
The recommended way to avoid the warning is to remove the name of the variable and only leave the type. Can you elaborate on why this is not a sufficient solution for you?

**Comment by AusIV** [comment]
I was unaware that's an option. Is it documented somewhere? Googling "solidity unused variable" I don't find that recommendation anywhere.

**Comment by chriseth** [comment]
It is part of the error message itself.

**Comment by AusIV** [comment]
The error message I see is:

```
> project/contracts/Account.sol:72:22: Warning: Unused local variable.
      (bool success, bytes memory _) = batch[i].target.call.value(batch[i].value)(batch[i].data);
                     ^------------^
```

I don't see any clue in here that I could avoid the warning by just specifying the type.

Additionally, if I try not naming the variable, I get:

```
ParserError: Expected identifier but got ')'
      (bool success, bytes) = batch[i].target.call.value(batch[i].value)(batch[i].data);
                          ^
```

**Comment by chriseth** [comment]
Which version of the compiler are you using?

**Comment by AusIV** [comment]
Solidity - 0.5.3 (solc-js)

**Comment by chriseth** [comment]
Oh I'm so sorry, I did not read your description thoroughly enough. You can just use `(bool success,) = ...` in that case. The recommendation is not provided because it is a local variable - which does not have to be declared at all, as opposed to e.g. a function parameter.

**Comment by AusIV** [comment]
Alright, that works. Aside from maybe updating documentation / warnings to make this clearer, this can be closed.

**Comment by chriseth** [comment]
Created https://github.com/ethereum/solidity/issues/6162 to track improvement of the error message. Thanks!

**Comment by decentpay-finance** [comment]
If lets say i have an interface with function that defines all the possible data vailable for custom programmer, there are some use cases that doesnt need some of the parameters. how to address this?

**Comment by cameel** [comment]
@littledogecoin Just omit the name of the parameter. For example this does not generate the warning:

```solidity
interface I {
    function f(uint x, uint y) external pure returns (uint);
}

contract C is I {
    function f(uint, uint y) external pure override returns (uint){
        return y;
    }
}
```

**Comment by SilvioGuedes** [comment]
In my code I don't need to get the return of the call function and I don't need to use the 'success' parameter:

```
... some code
servers[serverId].owner.call{value: value}("");
... more code not using the success parameter
```

How can I remove this warning?

```
 Warning: Return value of low-level calls not used.
   --> project:/src/contracts/solidity/IPFSServerERC721.sol:142:3:
    |
142 |           servers[serverId].owner.call{value: value}("");
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by cameel** [comment]
@oivlisnet You can suppress the warning by doing something with the value. Even just using it in a trivial expression consisting only of parentheses:
```solidity
(servers[serverId].owner.call{value: value}(""));
```
But are you sure you don't care if the call reverts or if it returns any data? 

If you do care but you're just accessing the returndata afterwards in assembly, I'd say the "proper" solution would be to make the call in assembly too.

**Comment by SilvioGuedes** [comment]
@cameel Thanks for the response. 

I'll explain what I'm doing and why it's necessary:

The code is for a smart contract to incentivize IPFS servers to be online and/or pin a file.
To do this, the smart contract needs to send ethers to the server owner and to the other servers when an user "lease" a server.
If the server owner is a **smart contract without a receive or fallback function** and I use a "require" to certify if the payment is successful, the rest of the code will never be executed:

  ```
          uint256 value = msg.value;

		(bool sentEtherOwner1,) = servers[serverId].owner.call{value: (value * OWNER_PERCENT) / 100}("");
		if(sentEtherOwner1){
			value = value - ((value * OWNER_PERCENT) / 100);
		}
		for(uint i = 1;i < totalServers + 1;i++){
			if(servers[i].rating > MIN_RATING){
				(bool sentEtherOthers,) = servers[i].owner.call{value: value / totalServers}("");
				if(sentEtherOthers){
					value = value - (value / totalServers);
				}
			}
		}
		(bool success,) = servers[serverId].owner.call{value: value}("");//<-- the call function

          require(success,"can't send ether to the server");//<-- the require uses the success value

          //the rest of the code will never be executed
```

Did you understand the problem? This method can be used by an attacker.

I'll try to use parentheses. Thanks!!!
