### ISSUE TITLE
Functions Conflict for Unclear Reason

### ISSUE THREAD

**Issue by whitj00** [ethereum/solidity#61]
http://pastebin.com/raw.php?i=T38utWrc fails
http://pastebin.com/raw.php?i=m6SSMJUu works
http://pastebin.com/raw.php?i=4gvT3H16 works

eth.getCode returns 0x for the first one
but returns code for the other two

Is this a stupid mistake on my part or an issue with solidity?

**Comment by whitj00** [comment]
Found the issue, thx

**Comment by jorisbontje** [comment]
Let me guess, out of gas? :fuelpump:

**Comment by whitj00** [comment]
Yup :P
