### ISSUE TITLE
Internal compiler error when optimizing strict assembly containing extcodehash

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6102]
## Description

The solc compiler throws an internal compiler exception stating "invalid assembly/yul code" for the following example

```
$ echo "{if extcodehash(1){}}" | ./solc/solc - --strict-assembly --optimize
Exception in assembler: /home/bhargava/work/github/solidity/libyul/AsmAnalysis.cpp(75): Throw in function static yul::AsmAnalysisInfo yul::AsmAnalyzer::analyzeStrictAssertCorrect(std::shared_ptr<yul::Dialect>, const yul::Block&)
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Invalid assembly/yul code.
[dev::tag_comment*] = Invalid assembly/yul code.
```

Minus the `--optimize` flag the compiler throws this warning.

```
<stdin>:1:5: Warning: The "extcodehash" instruction is not supported by the VM version "byzantiu
m" you are currently compiling for. It will be interpreted as an invalid instruction on this VM.
{if extcodehash(1){}}
    ^------------^        
```

This warning might be worth throwing even when optimization is requested.

Incidentally, the EVM version set while initializing AssemblyStack seems to be disregarded by the optimize() call

This is how AssemblyStack is initialized.

```
AssemblyStack stack(dev::solidity::EVMVersion::constantinople(), AssemblyStack::Language::StrictAssembly);
```

The warning states the EVM version as byzantium instead of constantinople.

## Environment

- Compiler version: `97d3b88f6` commit on develop
- Target EVM version (as per compiler settings): byzantium
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: n/a

## Steps to Reproduce

```
$ echo "{if extcodehash(1){}}" | ./solc/solc - --strict-assembly --optimize
```

**Comment by chriseth** [comment]
Can you check if this has been fixed already by https://github.com/ethereum/solidity/pull/6071 ?

**Comment by bshastry** [comment]
@chriseth I checked, this bug still reproduces on latest develop.
