### ISSUE TITLE
More optimisation rules

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6107]
Some of them from here https://github.com/ethereum/solidity/issues/6075#issuecomment-467270107.

- `lt(x, 0)` -> `0` -- since this cannot ever be true, `slt` can be used for two's complement <0 checks
- `gt(x, 0)` -> `iszero(iszero(x))` -- same here, there's `sgt` for signed comparison
- `gt(x, ~0))` -> `0`
- `and(byte(x, y), 0xff)` -> `byte(x, y)` since byte always returns 8 bits
- `byte(x, a)` where `a >= 32` -> `0`
- `byte(x, 31)` -> `and(x, 0xff)` since the 31st byte is the lowest one
- ~~`addmod(a, x, b)` where `a >= b` -> `b`~~
- ~~`addmod(x, a, b)` where `a >= b` -> `b`~~

There is an optimisation rule to remove masking of 160-bits for opcodes returning an address. I think that list can be extended with `CREATE` and `CREATE2` too.

**Comment by chriseth** [comment]
Can you explain the addmod rules?

**Comment by axic** [comment]
Sorry, confused that, they are invalid.

**Comment by axic** [comment]
> `byte(x, a) where a >= 32 -> 0`

Cannot be efficiently implemented in the RuleList currently.
