### ISSUE TITLE
Null dereference in TypeChecker

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6109]
## Description

(Found by ossfuzz: 	13415)

The following contract

```
contract n{function(){var(x)=();assembly{e(x)}}}
```

triggers a null dereference here

https://github.com/ethereum/solidity/blob/1169004cec0fb256a1023ac6e67b692ccdac22d4/libsolidity/analysis/TypeChecker.cpp#L663

**Comment by axic** [comment]
Minimal example:
```
contract n {
  function(){
    var (x) = ();
    assembly{
      x
    }
  }
}
```

I think it is due the variable resolve for inline assembly doesn't take care of `var` after it has been removed.

In the type checker we have behaviour like this:
```
contract n {
  function(){
    var (x) = ();
    x;
  }
}
```

```
6109.sol:3:5: Error: Different number of components on the left hand side (1) than on the right hand side (0).
    var (x) = ();
    ^----------^
6109.sol:4:5: Error: Declaration referenced before type could be determined.
    x;
    ^
```

**Comment by Marenz** [comment]
The error 

> Error: Declaration referenced before type could be determined

is triggered by checking the type() for nullptr. I initially used the same method to fix this, but @chriseth was worried that there might be many other places where a missing type can cause problems so now we trigger a fatal error if variables are still left without type after the `var` type guessing code (see  PR)
.
