### ISSUE TITLE
Optimized code produces a different trace than original unoptimized code

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6110]
## Description

(Found via differential fuzzing)

This code:

```
{
  let x := 7
  mstore(0, signextend(50, x))
  let y := 255
  mstore(1, signextend(0, y))
}
```

when optimized produces a different trace (via the yul interpreter) than the original unoptimized code

Here are the two traces (trace1 is for unoptimized code and trace2 for optimized code)

```
Trace 1 ==============
Trace:
  MSTORE_AT_SIZE(0, 32) [0000000000000000000000000000000000000000000000000000000000000032]
  MSTORE_AT_SIZE(1, 32) [ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff]
Trace 2 ==============
Trace:
  MSTORE_AT_SIZE(0, 32) [0000000000000000000000000000000000000000000000000000000000000007]
  MSTORE_AT_SIZE(1, 32) [ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff]
```

**Comment by chriseth** [comment]
Do you also have the optimized code?

**Comment by bshastry** [comment]
@chriseth no, how can I print that? Will `solc --strict-assembly --optimize` help?

**Comment by chriseth** [comment]
If the optimizer is deterministic, it should be
```
{
        mstore(0, 7)
        mstore(1, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
    }
```

 - this rather looks like a problem with the interpreter than the optimizer.
