### ISSUE TITLE
Support for multiple constructors per contract

### ISSUE THREAD

**Issue by spalladino** [ethereum/solidity#6116]
## Abstract

Solidity currently supports at most one constructor per contract, without overloading; we would like to lift this restriction.

## Motivation

In the same fashion as Solidity support regular function overloading, it would be most useful if it could support constructor overloading as well. This would allow to have multiple initialization paths for the same contract. 

A simple example would be a contract that manages either Ether or an ERC20, so the constructor could accept an address representing the ERC20 contract, while another constructor accepts no parameters and is used for Ether. This can currently be done by assigning a "special" address to Ether, but having a separate constructor for a separate path would be much cleaner.

A more complex example, and the one that motivated this issue, would be allowing contracts to be initialized either in the constructor or on a separate Initialize function. In some scenarios, such as [when creating a delegating proxy to a contract](https://docs.zeppelinos.org/docs/writing_contracts.html#initializers), or [setting up a contract via CREATE2](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1651), initialization needs to take place on a separate call to the contract - different to the constructor. Having multiple constructors would allow us to have a constructor with all the initialization logic (used when the contract is deployed regularly), and have an empty constructor that leaves room for a separate `initialize` call (used when the contract is a logic contract backing a proxy, or deployed via create2).

## Specification

No changes are needed when a contract has a single constructor. When it has multiple constructors defined, then a small jump table could be added to the initialization code, and the first argument in the appended contract parameters could be the signature of the constructor to call.

## Backwards Compatibility

Contracts with a single constructor are unaffected by this change.

**Comment by chriseth** [comment]
While this sounds like a good feature to have, (and the main reason this has not been implemented so far) I don't see a way how to properly specify which constructor to choose from. As opposed to function calls, we do not have a notion of function selector for the constructor. I don't think backwards compatibility issues can be just ignored by saying that "old-style" contracts are unaffected. This still requires big changes in tooling which could lead to severe consequences if they are not prepared for it.

Also I think that making init functions a language feature should be a separate issue.

**Comment by spalladino** [comment]
> As opposed to function calls, we do not have a notion of function selector for the constructor.

That's exactly part of the idea: a function selector could also be added for ctors, and evaluated only on the initialization bytecode. The selector could be calculated as `bytes4(keccak256("constructor(uint256,uint256)"))` (for example), or even removing the `constructor` keyword from the hash altogether (since all functions checked in that step would be constructors).

> This still requires big changes in tooling which could lead to severe consequences if they are not prepared for it.

I agree with you here. If a library picks up binary from a contract with multiple ctors and fails to inject the selector, I'm not sure what would actually happen. Perhaps an additional check could be inserted to make sure that deployment consistently fails if a contract is attempted to be deployed without the ctor selector? Could this be detected by checking the length of the arguments somehow - ie multiple of 32 bytes + 4 bytes means selector, just multiple of 32 bytes means no selector? (I'm presuming that ctor arguments are padded to 32 bytes here, which may not be the case).

A separate discussion is how much you want to slow down improvements on the language because of the tooling around it.

> Also I think that making init functions a language feature should be a separate issue.

I'd love to see that! Let me know if there is anywhere where that conversation is happening so I can jump in.

**Comment by nventuro** [comment]
@chriseth Is it be possible for the creation code to e.g. tell apart encoded data that is meant for constructors of different arity? I'm not familiar with the internals of how constructor arguments are encoded, but if this were possible, even this limited form of overloading would be extremely useful for developers.

**Comment by axic** [comment]
> A simple example would be a contract that manages either Ether or an ERC20, so the constructor could accept an address representing the ERC20 contract, while another constructor accepts no parameters and is used for Ether. This can currently be done by assigning a "special" address to Ether, but having a separate constructor for a separate path would be much cleaner.

Without reflecting to the rest: I think it is actually a bad pattern to mix "native tokens" with "tokens" in a single system, unless absolutely necessary, because it opens the door to many mistakes. Much more like the idea of "wrapped eth" to separate concerns. As a result I think the use case presented isn't the best one.

**Comment by axic** [comment]
> I don't think backwards compatibility issues can be just ignored by saying that "old-style" contracts are unaffected.

Actually after the ABIEncoderV2 is enabled one could consider adding selector in a backwards compatible way: even constructor arguments will be enforced to be a multiple of 32 bytes. In that case it would be easy to detect if a selector is present (the data isn't a multiple of 32 bytes).

However, the problem of old contracts may be accepted invalid data would remain.

**Comment by spalladino** [comment]
@axic would that mean that if this feature is implemented after the ABIEncoderV2 is enforced, then there would be a safe way to detect whether a constructor selector was included or not, so the contract initialization code could validate if it was properly initialized or not?

**Comment by chriseth** [comment]
@axic in my opinion, that would still lean towards a hack, because the ABI encoding does not really force data pointers to be multiples of 32 bytes - although it is recommended (in the "strict" encoding) and done like that in Solidity.

**Comment by chriseth** [comment]
@spalladino I'm sorry - perhaps my first comment came around a little harsh. My main comment would be that the issue description has a lot of motivation but neither lists potential problems nor provides a solution to them.

**Comment by spalladino** [comment]
@chriseth no need to be sorry at all, and thanks a lot for the clarification!! I agree that the issue misses several potential problems, especially around tooling, but I'm not sure I have the necessary knowledge to assess or come up with solutions for all of them. I'll do my best though and get back to you!
