### ISSUE TITLE
Solc src mappings problems

### ISSUE THREAD

**Issue by norhh** [ethereum/solidity#6119]
## Description
The src-map doesn't seem to be that accurate, In some cases the srcmap points towards comments.
## Environment

- Compiler version: 0.5.0
- Target EVM version (as per compiler settings): byzantium
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: Ubuntu

## Steps to Reproduce
Below is the line_mapping code which prints out the PC and it's corresponding line number
```
import json
from subprocess import PIPE, Popen


def _get_solc_mappings(srcmap, solidity_files):
    """The line mappings function"""
    prev_item = []
    PC = 1
    for item in srcmap:
        mapping = item.split(":")
        mapping += prev_item[len(mapping):]   # if the length is less then previous mapping length then take the previous mapping values of the rest
        for index in range(len(mapping)):
            if mapping[index] == "":          # Fill up all empty values with it's previous values
                mapping[index] = int(prev_item[index])

        offset, length, idx, _ = mapping      # offset:length:file_no:jump format
        offset = int(offset)
        idx = int(idx)
        lineno = (
             solidity_files[idx].encode("utf-8")[0:offset].count("\n".encode("utf-8")) + 1
        )
        prev_item = mapping
        print("PC: {}, line_no: {}".format(PC, lineno))
        PC += 1


def main():
    cmd = ["solc", "--combined-json", "srcmap-runtime", "./BECToken.sol"]
    p = Popen(cmd, stdout=PIPE, stderr=PIPE)

    stdout, stderr = p.communicate()
    ret = p.returncode

    out = stdout.decode("UTF-8")
    json_data = json.loads(out)
    solidity_files = []
    for filename in json_data["sourceList"]:
        with open(filename, "r", encoding="utf-8") as file:
            code = file.read()
            solidity_files.append(code)

    srcmap = json_data["contracts"]['./BECToken.sol:PausableToken']["srcmap-runtime"].split(";")
    _get_solc_mappings(srcmap, solidity_files)


if __name__ == "__main__":
    main()

```
the contract on which it is run is BECToken.sol which can be found here https://raw.githubusercontent.com/ConsenSys/mythril-classic/develop/solidity_examples/BECToken.sol ,
After executing, It can be clearly seen in the output that at some addresses the src is pointed to line numbers 3-4 which are comments. Am I making any mistake here?

**Comment by chriseth** [comment]
The compiler sometimes provides source links to source files internal to the compiler. In that case, the source index is `-1`. Can you check if that is the case? I think `solidity_files[-1]` in python does not generate an error, does it?

**Comment by norhh** [comment]
@chriseth , thanks for the reply, that seems to be the case, Can you mention where that internal file exists in the solidity build? that might be quite helpful

**Comment by chriseth** [comment]
They are not really files, they are just generated source code snippets. So it might be better to just remove these annotations.

**Comment by norhh** [comment]
Cool, thanks :+1:
