### ISSUE TITLE
Semicolon after a parameter will lead to DocstringParsingError

### ISSUE THREAD

**Issue by YannickXiong** [ethereum/solidity#6124]
```
/**
     * @dev    : token transfer
     * @param _from : from adress
     * @param _to   : to address
     * @param _value: token transfer amount
     */
    function _transfer(address _from, address _to, uint256 _value) internal {
       // to do
    }
```
Above code will lead to DocstringParsingError, because solidity takes '_value:' instead of '_value" as a parameter, of course function _transfer doesn't contain such a parameter.

Maybe this is just a trivial problem， however I think optimize it would bring a better coding experience. Thanks.

**Comment by chriseth** [comment]
If you use colons like that, won't they end up in the description string? In any case, the parser should stop before colon, so this is a bug indeed.
