### ISSUE TITLE
Yul traces differ while performing nested subtraction and division

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6126]
## Description

(Found by LPM+libFuzzer)

Here's the yul code whose optimization triggers a different trace than the original

```
{
let a,b := foo(calldataload(0),calldataload(32),calldataload(64),calldataload(96),calldataload(128),calldataload(160),calldataload(192),calldataload(224))
sstore(0, a)
sstore(32, b)
function foo(x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7) -> x_8, x_9
{
x_9 := sub(1,sub(x_9,1))
mstore(sub(1,div(sub(x_9,1),sub(1,sub(x_9,1)))), 1)
}
}
```

The optimized program output by solc for the above program is the following

```
mstore(0x8000000000000000000000000000000000000000000000000000000000000002, 1)
sstore(0, 0)
sstore(32, 2)
```

Here are the two traces

```
Trace 1 ==============
Trace:
  MSTORE_AT_SIZE(1, 32) [0000000000000000000000000000000000000000000000000000000000000001]
  SSTORE(0, 0)
  SSTORE(32, 2)
Trace 2 ==============
Trace:
  MSTORE_AT_SIZE(0x8000000000000000000000000000000000000000000000000000000000000002, 32) [0000000000000000000000000000000000000000000000000000000000000001]
  SSTORE(0, 0)
  SSTORE(32, 2)
```

### Analysis

After first line of code
```
x_9 = 1 - (x_9 - 1) = 2
```

This means the sstores in the two traces are correctly identical. The problem is with the address computed by the mstore operation.

The address computed by the mstore operation is
```
1-(x_9-1)/(1-(x_9 - 1))=1-(1/0) =1
```

Therefore the unoptimized trace is correct. However, the optimized trace is definitely incorrect as can be seen by the `solc` generated output.

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/6129
