### ISSUE TITLE
[DOCS] Remove or reduce ranking of older versions from searches

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#6134]
Frequently search engines searches of solidity docs return results from older docs versions, we should figure out how to prioritise results from the most recent version.

**Comment by elenadimitrova** [comment]
When searching for keywords and include the Solidity version number you're using, search engines returns better results and looking at the Sphinx documentation the most we could do is [show a warning when not looking at the latest version](https://docs.readthedocs.io/en/stable/versions.html#version-warning).

We could be more particular with results in https://ethsear.ch/ perhaps, @jrhea?

**Comment by chriseth** [comment]
Readthedocs already shows the version warning.

**Comment by jrhea** [comment]
> When searching for keywords and include the Solidity version number you're using, search engines returns better results and looking at the Sphinx documentation the most we could do is [show a warning when not looking at the latest version](https://docs.readthedocs.io/en/stable/versions.html#version-warning).
> 
> We could be more particular with results in https://ethsear.ch/ perhaps, @jrhea?

@elenadimitrova sorry i missed this.  how can i help?  i can modify the crawler and seed it with a particular url and blacklist the rest.  would that help?

**Comment by axic** [comment]
> Readthedocs already shows the version warning.

On every page it shows this ([example](https://solidity.readthedocs.io/en/v0.7.3/types.html):
![Screenshot](https://user-images.githubusercontent.com/20340/97463321-88908380-1937-11eb-9d7c-6c14a862102f.png)

I think it is fine to close this issue.
