### ISSUE TITLE
Tuples need to actually return from function calls

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#615]
This should work...but it doesn't.

```
contract c {
    function a() returns (uint, uint, uint) {
        return (1, 2, 3);
    }
    function A() {
        uint a;
        uint b;
        uint c;
        (a, b, c) = a();
    }
}
```

gives: 

```
assignment.sol:9:15: Error: Type is not callable
        (a, b, c) = a();
                    ^-^
assignment.sol:9:15: Error: Type tuple() is not implicitly convertible to expected type tuple(uint256,uint256,uint256).
        (a, b, c) = a();
                    ^-^
```

will need to work on this. @chriseth do you know off hand what is causing this problem so that I could better look at it in the future?

**Comment by chriseth** [comment]
The local variable `a` shadows the function `a`.

**Comment by VoR0220** [comment]
ah poop...was late..wasn't thinking.

**Comment by ilanoh** [comment]
Can you explain it, I get the same issue with msg.sender()

**Comment by jaredstauffer** [comment]
msg.sender is not a function. You cannot use it with the (), that would imply that it is a function. Remove the ().
