### ISSUE TITLE
Change "revert" to "skirrt" [feature request]

### ISSUE THREAD

**Issue by biocrypto730** [ethereum/solidity#6150]
I think it would be cool if solidity could say "skirrt" every time it made an error instead of the saltine-cracker "revert". Compilers like truffle and remix-ide can play a 4-tone MIDI "skirrrt" sound. When i get a revert error i always feel bad because it means i have to debug the EVM. But if my code skirrrted instead, i would at least feel better about it when i had to debug the EVM

**Comment by Skyge** [comment]
@projectoblio It should be, but not now, there are still more important thing to deal, if you would like to do it, all of us will be happy about it.
