### ISSUE TITLE
Internal functions can be passed in library calls

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6151]
A struct containing an internal function can be passed across library calls. This is non-sensical, since the library could then call the internal function whose code is not even available.

Example code:

```
library L {
    struct S {
        function() internal x;
    }

    function f(S storage s) public {
        s.x();
    }
}

contract c{
    L.S s;
    function f() public {
        s.x = f;
        L.f(s);
    }
}
```

**Comment by chriseth** [comment]
Suggestion for resolution: Introduce another category of "internalness" for types which cannot even be passed across library calls.

**Comment by Marenz** [comment]
So, just to understand this right, internal functions in libraries can be called from contracts, but internal functions from contracts are not available to the library? (I was [reading](https://solidity.readthedocs.io/en/v0.5.3/contracts.html#libraries))

**Comment by Marenz** [comment]
After verbal clarification: external or public library functions should not accept parameters of type `function() internal`, wrapped in other types or otherwise.

Alternatively, they may accept it, but are not allowed to actually call it.

**Comment by zero-f1x** [comment]
It is possible to call internal functions of library from contract.
https://docs.soliditylang.org/en/v0.8.11/contracts.html

**Comment by cameel** [comment]
@Alan115-skyhand It is, but this is not the right place to ask support questions. Please try the [#solidity](https://gitter.im/ethereum/solidity) channel on Gitter or ask on https://ethereum.stackexchange.com.
