### ISSUE TITLE
Improve unused local variable error message in tuple declaration.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6162]
The error message for local variable declarations with multiple variables can be improved to suggest to remove the variable from the tuple.

```
> project/contracts/Account.sol:72:22: Warning: Unused local variable.
      (bool success, bytes memory _) = batch[i].target.call.value(batch[i].value)(batch[i].data);
                     ^------------^
```

**Comment by Darshantawte** [comment]
Hello, i am new to open source contributions and would like to start this as my first contribution. As per my understanding of the issue you guys want to  change the Warning message showed in the above code snippet to something like 
WARNING : "Remove unused local variables from tuple".

**Comment by cameel** [comment]
@Darshantawte Yes, but it's important to word it in such a way that the user understands that `(T1 a, T2 b, T3 c)` should be replaced with `(T1 a,, T3 c)`. People might expect `(T1 a, T2, T3 c)` to work instead and not expect the `,,` part to even be allowed.

**Comment by cameel** [comment]
By the way, please note that this is marked as a `good first issue candidate` rather than `good first issue`. I.e. it's one of the issues we'd consider assigning to contributors but it's not decided yet.

In this case however it seems simple enough that I'm just going to mark it as `good first issue`. It's basically just rewording the message and should be straightforward.

**Comment by cameel** [comment]
Also, @chriseth why is something like `(T1 a, T2, T3 c)` not allowed? It seems more intuitive to me - that's how you'd do that in a function definition. It would also remove the only case that's blocking #2991.

**Comment by harshasingamshetty1** [comment]
Hey @cameel , I am new to open source contributions.
May I know if I can take this up ?
