### ISSUE TITLE
Gas calculation for ComputeMethod should take care of shifts in ConstantOptimiser

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6167]
#6073 added support for using shifts in the constant optimiser, however forgot to update the gas estimation.

This doesn't pose any risk, just the possibility that efficient cases will be turned down.

**Comment by chriseth** [comment]
Can you provide some more details, please?

**Comment by Marenz** [comment]
From the chat:

>axic: The ComputeMethod::calculateGas still valvulates it based on EXP. I think it actually may be okay brcause that turns into 0, but does it need to account for the cost of shift?

**Comment by Marenz** [comment]
From the chat:
> chriseth: calculateGas: I don't think so. The exps are just prominent because they have non-constant gas costs. It calls simpleRunGas which just counts the gas for the instructions.

**Comment by Marenz** [comment]
Based on the above statements I assume this issue can be closed. Please reopen if you think this was a mistake.
