### ISSUE TITLE
Add symmetric optimisation rules missing for lt (i.e. swapped gt rules).

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6173]
From https://github.com/ethereum/solidity/pull/6159#discussion_r262088791

**Comment by ekpyron** [comment]
I just changed the title from ``lt(0,x) -> 0`` to ``lt(0,x) -> 1``, but even that's not true... we have to distinguish between x=0 and x>0 after all, don't we?

**Comment by ekpyron** [comment]
``gt(0,x) -> 0`` should work, though.

**Comment by chriseth** [comment]
but that rule already exists...

**Comment by chriseth** [comment]
I'm just saying - we have 3 rules for gt, but only 1 for lt.

**Comment by ekpyron** [comment]
Ok, looking at the ``GT`` rules, I think we should add the following two rules:
- ``lt(0,x) -> iszero(iszero(x))``
- ``lt(~u256(0), x) -> 0``

Then it's symmetrical - in total we'd have:
- ``lt(x,0) -> 0`` (already there)
- ``gt(0,x) -> 0`` (already there)
- ``lt(0,x) -> iszero(iszero(x))`` (to be added)
- ``gt(x,0) -> iszero(iszero(x))`` (already there)
- ``lt(~u256(0), x) -> 0`` (to be added)
- ``gt(x,~u256(0)) -> 0`` (already there)

**Comment by ekpyron** [comment]
Not sure whether it could actually make more sense to generally have ``gt(x,y) -> lt(y,x)`` instead and later change ``SWAP1; LT`` to ``GT`` - not sure that's feasible or in fact simpler, though. [EDIT: bad idea probably - we should have LT and GT rules and the SWAP1; LT/GT -> GT/LT thing should happen separately - probably already happens - nevermind here - yep PeepholeOptimiser does that]
