### ISSUE TITLE
Add a more verbose error message for "stack too deep" errors

### ISSUE THREAD

**Issue by chebykin** [ethereum/solidity#6176]
## Abstract

After merging two branches I have stumbled over `InternalCompilerError: Stack too deep, try removing local variables.`. There is no information about the error location. I'm having around 20 changed contracts to be checked manually.

## Motivation
It would be really great if we had a more verbose error message containing at least a filename.

This issue had been already fixed before, but now it has arisen again.

___
https://github.com/ethereum/solidity/issues/396
https://github.com/ethereum/solidity/issues/1042

**Comment by chriseth** [comment]
Similar to / duplicate of https://github.com/ethereum/solidity/issues/5467

**Comment by chebykin** [comment]
Ok, I see. Closing this one. Thanks!
