### ISSUE TITLE
Uninitialized storage pointer

### ISSUE THREAD

**Issue by blockchain-app12** [ethereum/solidity#6177]
## Description

Pushing values in array, shows array should be initialized as storage. Doing that it shows "Uninitialized storage pointer". Using memory it shows, "Member "push" is not available in uint256[] memory outside of storage". Suggest me the solution for the above?

**Comment by Skyge** [comment]
@osiz-blockchainapp  I am not sure, but I think you defined it like this: 
```
    function push(uint256 num)public {
        uint256[] array;
        array.push(num);
}
``` 
why do you define an array inside the function, maybe you can try to write it outside
```
    uint256[] public array;
    function push(uint256 num)public {
        array.push(num);
}
``` 
BTW, I write this by the version of 0.5.x

**Comment by chriseth** [comment]
@osiz-blockchainapp without example code, we cannot really help you there. The idea is that you have to assign to the local variable at the point where it is declared.

In any case, this question is probably better suited for https://ethereum.stackexchange.com - you will get faster and better replies there.
