### ISSUE TITLE
yulInterpreter: Support object access builtin functions

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6180]
## Abstract

(closes #6165 )

At the moment, Yul object access built in functions are not supported by the yulInterpreter. Specifically, they trigger an assertion (see #6165) at the time function calls are evaluated by the interpreter.

This issue tracks support for the three object access built in functions, namely
  - datacopy
  - datasize
  - dataoffset

## Motivation

TBD

## Specification

TBD

**Comment by chriseth** [comment]
This has been implemented in #6631
