### ISSUE TITLE
Extract Yul tests

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#6205]
* Create `YulSyntaxTest`.
* Port inline syntax tests from `test/libyul/Parser.cpp` into `.yul` files.
* How to do error detection (similar to solidity language)
* See if we can **share** code between solidity syntax tests and this one.
* Move existing yul tests (that are currently part of Solidity) into this one.

**Comment by chriseth** [comment]
It would be good if a "common" component (shared with yulOptimizerTests, yulInterpreterTests, ...) could be extracted such that the only thing we have to implement for each now test is a function that maps input to expectation.
