### ISSUE TITLE
Type deduction for inline arrays

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#621]
The following should compile fine, but it does not:

```
contract c {
    function f() {
        int8[5] memory foo3 = [int8(1), -1, 0, 0, 0];
    }
}
```

**Comment by VoR0220** [comment]
the problem is the left hand side. The left hand side wants the mobile types of the right hand side and so it needs to be a uint8[5]. With that said. How do we want to go about addressing this? Is this where "smart arrays" come into play?

**Comment by VoR0220** [comment]
I lied...that is a strange bug. Error message:

```
vor0220@CaptainNumNutz:~ $ solc array.sol
array.sol:3:30: Error: Unable to deduce common type for array elements.
        int[5] memory foo3 = [int8(1), -1, 0, 0, 0];
                             ^--------------------^
```

**Comment by chriseth** [comment]
Oh yes, sorry, I edited the description to show more precisely what I mean

**Comment by Serozd** [comment]
those lines produce same error: 
`TypeError: Unable to deduce common type for array elements.
      int8[3] memory solutions = [0, -1, 1];`
with ` pragma solidity ^0.4.17;`
the solution to this is to write:
`int8[3] memory solutions = [int8(0), -1, 1];`
