### ISSUE TITLE
Add peephole optimiser to remove double-iszero before jump(i)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6212]
From https://github.com/ethereum/solidity/issues/6075#issuecomment-467536178:

> Not sure if this is the case, but is the sequence
> 
> ```
> iszero
> iszero
> tag_#
> jumpi
> ```
> 
> reducable to simply
> 
> ```
> tag_#
> jumpi
> ```
> 
> since `jumpi` as I understand it already checks for a non-zero value

**Comment by chriseth** [comment]
actually working on this at the moment...
