### ISSUE TITLE
Change regular calldata arrays to only use a single stack slot

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6220]
`msg.data` should be a different type that still occupies two stack slots - or we might also just use `calldatasize` for that as a size.

All other calldata arrays should just be pointers to the position in calldata that stores the length.

**Comment by ekpyron** [comment]
An argument for the type of ``msg.data`` storing the length on the stack would be that then that type could be a general "array view" type that could represent subranges of calldata arrays.

**Comment by ekpyron** [comment]
I'm unassigning this again for now - depending on the progress of ABIEncoderV2 it might be much simpler to only do this change after it is the default.

**Comment by ekpyron** [comment]
Doing this now will be a bit more complicated, since calldata array slices would no longer have the same stack layout as dynamic calldata arrays. Hence somewhat related to https://github.com/ethereum/solidity/issues/7423

**Comment by chriseth** [comment]
@ekpyron are we still set on this?

**Comment by chriseth** [comment]
Ah sorry, this is still useful, I think I was confused.
