### ISSUE TITLE
Merge ``Type::canBeUsedExternally`` and ``Type::interfaceType``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6223]
Noticed this while reviewing #6222.

We require ``canBeUsedExternally(x) == !!interfaceType(x)``, but allow the former to be optimized, i.e. avoid the actual construction of type pointers, which might involve allocations. That's unnecessary maintenance effort and an unnecessary risk of getting it wrong.

I'm not sure this optimization is really necessary, but even if one wants to keep it, it'd still be possible to have only one function, so we should refactor this.

E.g. we could have one virtual function in ``Type``:
``virtual bool Type::canBeUsedExternally(bool _inLibrary, TypePointer *_type = nullptr) const;``

In the case of ``ArrayType`` this could e.g. contain:

```
if (m_arrayKind != ArrayKind::Ordinary) {
  if (_type) {
     *_type = this->copyForLocation(DataLocation::Memory, true);
     solAssert(*_type, "");
  }
  return true;
}
```
This could be further simplified with a helper and/or some template magic.

We could then just implement in Type (non-virtual):
```
TypePointer Type::interfaceType(bool _inLibrary) const {
  TypePointer ret;
  bool success = canBeUsedExternally(_inLibrary, &ret);
  solAssert(success == !!ret, ""); // could be skipped
  return ret;
}
```

Another, maybe better option might be adding a helper type:
```
class FlagOptimizedTypePointer {
public:
  template<typename T>
  FlagOptimizedTypePointer(T&& _typeGetter): m_typeGetter(std::forward<T>(_typeGetter)) {}
  FlagOptimizedTypePointer() = default;
  operator TypePointer() const { return m_typeGetter(); } // might want to cache this in a m_type member and/or directly return {} in case !m_value, etc.
  operator bool() const { return m_value; }
private:
  bool m_value = false;
  std::function<TypePointer()> m_typeGetter = [] -> TypePointer { solAssert(false, ""); };
};
```

and we could just return ``return [&]{ return this->copyForLocation(DataLocation::Memory, true); }`` (and ``return {};`` for false) in the case above.

**Comment by Marenz** [comment]
We could simply measure how much benefit there really is in optimizing before trying all those alternative ways. As in, running a few timing tests

**Comment by ekpyron** [comment]
Yeah - although dynamic memory allocations might have a greater impact on asm.js, so if we want to benchmark, we should take soljson.js into account. Shouldn't be too hard to avoid them efficiently in any case.

**Comment by chriseth** [comment]
After the recent change, we need to descend into the type in every case, so there is not much benefit keeping both functions, actually.

**Comment by ekpyron** [comment]
Right - in ``StructType`` and ``ArrayType``, ``return this->copyForLocation(DataLocation::Memory, true);`` is more expensive than ``return true;``, but that's the only benefit. If it's worth it, one could mitigate that e.g. with the lambda trick above or sth. like that - might be in vain though.

**Comment by ekpyron** [comment]
Maybe we should even cache the interface type in the type or the annotations (and create it on first request only) - I guess if ``canBeUsedExternally`` is used for some check and returns true, most of the time we will need the interface type sooner or later as well anyways - and if we cache it, ``copyForLocation`` would always be run only once. That might be the easiest and cleanest solution.

**Comment by Marenz** [comment]
Could there be a problem that the cache becomes invalid during the compilation steps?

**Comment by ekpyron** [comment]
Not that I'm aware of - both ``interfaceType`` and ``copyForLocation`` should always return the same types given the same arguments I think.

**Comment by Marenz** [comment]
But the typechecker sometimes sets types right? Couldn't that change the result?

**Comment by ekpyron** [comment]
Not sure what you mean - I meant to cache the result of ``interfaceType`` in the type itself, maybe that was unclear?
So something like
```
class Type {
public:
TypePointer interfaceType(bool _inLibrary) const {
    if (!m_cachedInterfaceTypes[_inLibrary ? 1 : 0])
      m_cachedInterfaceTypes[_inLibrary ? 1 : 0] = interfaceTypeImpl(_inLibrary);
    return *m_cachedInterfaceTypes[_inLibrary ? 1 : 0];
}
protected:
virtual TypePointer interfaceTypeImpl(bool /* _inLibrary */) { return {}; /* to be overridden and actually compute the interface type */ }
private:
  mutable boost::optional<TypePointer> m_cachedInterfaceTypes[2]{{},{}};
};
```
Maybe not in ``Type``, but only in ``ReferenceType`` and maybe it's not worth the effort/complexity/additional memory needed for the cache, but it should be fine.

**Comment by Marenz** [comment]
No, I understood that. What I meant where things like this: https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/TypeChecker.cpp#L1159
I feared they might change the result.

**Comment by ekpyron** [comment]
The TypeChecker assigns Types to ASTNodes - but every Type itself is immutable - nothing will change about it once it is created.

**Comment by ekpyron** [comment]
Note that ``_assignment`` in the line you reference is not a type, but an ASTNode that is annotated with a type.

**Comment by Marenz** [comment]
Alright :)
