### ISSUE TITLE
Fuzz SMT Checker

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6226]
## Abstract

At the moment, the SMT checker is not fuzzed. The main blocker appears to be statically building the solc fuzzing binary against an up-to-date z3. See #5652 

## Motivation

Potentially, we could mirror the steps used to build the static solc binary for PPAs.

## Specification

I don't think test harness needs updating. We should reseed the fuzzer with statements that will be picked up by the SMT checker such as `require` and `assert`.

## Backwards Compatibility

NA

**Comment by bshastry** [comment]
@leonardoalt @axic @chriseth 

I have a pending pull request to ossfuzz if you would like to enable SMTChecker fuzzing. The proposed PR builds a static library of upstream z3 and links solidity against it.

**Comment by chriseth** [comment]
statically linking z3 is something we wanted to have anyway. Is it possible to even combine that with the compiler into a single static binary?

**Comment by bshastry** [comment]
Yeah, iirc I was able to build a single binary fuzzing blob that also contained z3. Since z3 is not being fuzzed upstream, it can happen that we catch z3 errors which may or may not be what we want though.

Note to self: Fuzz z3 :-)

**Comment by bshastry** [comment]
Closed via https://github.com/google/oss-fuzz/pull/2835
