### ISSUE TITLE
Reproducible Builds: Store details about the build environment in the compiler.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6228]
We should store all relevant details about the build environment in solc and output it on ``--version`` (or with dedicated new flag; should also be exported in solc-js).
This should for example include:
- Compiler version.
- Boost version.
- For soljson.js Emscripten version.
- Z3 and CVC4 versions plus maybe even their dependencies CLN and GMP in turn.
- All compiler and linker flags affecting the build (i.e. ideally no warning flags)
- All other cmake flags/options affecting the build, if any.
- cmake version (might not be needed)
~~- CPU architecture (might not be needed)~~ (bad idea probably)
~~- OS, OS Version, distribution, if applicable (on linux might attempt to use ``lsb_release`` and to read ``/etc/os-release`` or otherwise report "unknown") (might not be needed)~~ (bad idea probably)
- ...

This would be a step towards reproducible binaries, would help in bug reports and might help us in creating better patched older versions in cases of stuff like the soljson.js-Firefox-rule-list-stack-height-drama.

**Comment by chriseth** [comment]
Wouldn't most of the items make it harder to reproduce the binary? You have to find a matching system...

**Comment by ekpyron** [comment]
With mismatching compiler and dependency versions or flags you will probably get a mismatching binary anyways - if the binary can tell you its build environment, then you at least have a chance to match it... but yes - it's something to think about. Compiler flags regarding warnings e.g. shouldn't affect the binary.

Another option would be to store all this information outside the binary in some metadata file - but if one does that, I'm pretty sure that nobody will keep this metadata file around in the end...

Maybe there's some trick to include this information in an elf section that can be disregarded when comparing binaries... probably too involved, though...

**Comment by ekpyron** [comment]
We just got a Z3 assertion containing `` File: /build/libz3-static-dev-q0RqJn/libz3-static-dev-4.8.8/src/qe/qe_arith.cpp`` in CI - which looks like the static z3 PPA build chooses some weird build directory name and that ends up in our binaries in the end, so if we ever want really nicely reproducible builds, this will come up as a problem.
