### ISSUE TITLE
Prevent build directory from ending up in the compiler binary.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6230]
All source file names are stored in the compiler binary with absolute paths. That makes reproducible builds much more painful (since the build directories must have identical absolute paths).

This is probably due to error reporting, boost exceptions and ``__FILE__``.
We should investigate how much effort it is to have relative paths instead.

(In another project I once had CMake store the character length of ``CMAKE_SOURCE_DIR`` in a preprocessor macro and replaced ``__FILE__`` with ``__FILE__ + SOURCE_PATH_LENGTH``, but that might be difficult to do with boost and there might be a better way in general).

**Comment by ekpyron** [comment]
``-fmacro-prefix-map`` might do the trick for gcc and clang (need to check version requirements)

**Comment by ekpyron** [comment]
@christianparpart Do you happen to know what the situation is with MSVC? Does ``__FILE__`` contain absolute paths and do they end up in our binary there? If so, is there a way to avoid it?

**Comment by chriseth** [comment]
Hm, this is interesting. I actually grepped for a prefix of my build path and could not find it in the binary. Perhaps because it was a stripped release binary?

**Comment by chriseth** [comment]
Ah my bad, paths are even part of the stripped release build.

**Comment by chriseth** [comment]
Didn't we add a compiler setting to prevent this?

**Comment by ekpyron** [comment]
We do use ``-fmacro-prefix-map`` by now, but I never verified that those are the only sources of the build directory bleeding into the binary, I guess that's why the issue isn't closed yet.
It probably makes sense to close it in favour of a general "Reproducible builds" issue.
