### ISSUE TITLE
More aggressively optimise ``and(byte(x,y),c)``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6247]
```{{Instruction::AND, {{Instruction::BYTE, {X, Y}}, {u256(0xff)}}}, [=]() -> Pattern { return {Instruction::BYTE, {X, Y}}; }, false},``` was added in #6159.

I think this can be strengthened to ``and(byte(x,y),c) -> byte(x,y)``, whenever ``(c&0xFF)==0xFF``.

**Comment by ekpyron** [comment]
Maybe better: we can add an additional rule ``and(byte(x,y),c) -> and(byte(x,y),c&0xFF)`` instead. The strengthened rule proposed above will then be a special case of this additional rule plus the already present rule ``and(byte(x,y),0xFF) -> byte(x,y)``.

**Comment by chriseth** [comment]
I think this and many other issues can be summarized under tracking value ranges and bit masks of expressions. I'm not sure whether we should do that as part of the old optimizer, though.

**Comment by chriseth** [comment]
Oh and furthermore: I would also like to have a framework that can optimize the following
```
if eq(x, 0) {
  mstore(mul(y, x), 9)
}
```
into
```
if eq(x, 0) {
  mstore(0, 9)
}
```

This could also be achieved by value tracking. `lt` / `gt` should also be taken into account.

**Comment by ekpyron** [comment]
That'd be nice, yes.

**Comment by chriseth** [comment]
Created an issue: https://github.com/ethereum/solidity/issues/6252
