### ISSUE TITLE
Provide option to remove reason strings from binary

### ISSUE THREAD

**Issue by nventuro** [ethereum/solidity#6251]
## Abstract
I'd like for Solidity to provide an option (e.g. `--strip-reason-strings`) when compiling that resulted in a binary without these strings (as if all `require` statements had no reason, and just the condition).

## Motivation
Revert reason strings are very useful during development and testing, but the extra cost of having them may be undesired in a production environment. This is specially true when using contracts developed by third parties, which may want to make their libraries easy to use, but are forced to impose this overhead to their clients.

Other languages/build systems feature Debug and Release builds, where e.g. debug symbols are stripped, optimizations enabled, binaries compressed, etc. This would be another step in that same direction.

## Specification
Similarly to how optimization is opt-in enabled, a simple boolean option (open to suggestions regarding naming) would suffice here.

## Backwards Compatibility
N/A

**Comment by frangio** [comment]
@chriseth Do you think this is a good idea? How hard would it be to implement it?

**Comment by chriseth** [comment]
Yes, I think it is a good idea. Currently, we do not yet have such options for the compiler in place. As a similar option, we might want to remove asserts that are proven to be true or all asserts from the code.

As far as the implementation is concerned: It would probably go as an option to the standard compiler (we already have the "options" json) and then be distributed in a similar way as the ABIEncoderV2 setting is distributed.

**Comment by chriseth** [comment]
We should also support a "debug mode" where the require expression is used for the reason string (plus maybe filename, line number, etc): https://github.com/ethereum/solidity/issues/7260#issuecomment-531168669

**Comment by chriseth** [comment]
Implemented in #7450
