### ISSUE TITLE
Yul: track value ranges and bit masks of variables

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6252]
The Yul optimizer should track value ranges and bit masks for variables and use them during optimization / expression simplification.

Example: The code
```
if eq(x, 0) { mstore(x, 1) }
```
could be simplified to
```
if eq(x, 0) { mstore(0, 1) }
```

In general, branches restrict value ranges and bit masks of variables, even though this might be hard to track, especially if in the above case, the `eq(x, 0)` is hidden behind another variable.

In the following situations, the value range or bit mask of a variable might be deduced:

 - `lt` in comparison with branches
 - the results of `and` and other bitwise operations
 - the results of shifts
 - the results of opcodes like `address`, `byte`  or `mulmod`

If the value ranges or bit masks are known, we can use them to simplify certain expressions.
For example `if lt(x, 10) { if lt(x, 20) { .. } }` can be simplified to `if lt(x, 10) { if 1 { ... } }`.

Most of the time, the operations that can be optimized are the same that restrict the value ranges or bit masks.

**Comment by chriseth** [comment]
Also, this module should take into account branches that do not finish due to their use of opcodes. Example:

```
if lt(x, 10) { revert(0, 0) }
let y := gt(x, 9)
```
->
```
if lt(x, 10) { revert(0, 0) }
let y := 1
```

**Comment by chriseth** [comment]
Can we optimize the following?
```
if gt(x, 1000) { revert(0, 0) }
let y := calldataload(0)
if gt(y, 1000) { revert(0, 0) }
for {let i := 0} lt(i, x) { i := add(i, 1) }
{
  // The following condition is always true,
  // mainly because we can infer lt(i, x) -> lt(i, add(x, y))
  // since x and y are bounded.
  if lt(i, add(x, y)) { revert(0, 0) }
}
```

**Comment by chriseth** [comment]
The above can be optimized if we track the following information for each expression and variable:
 - list of
   - bit ranges
   - value ranges
   - relations to variables: Y +- c <= . <= Z +- c
     (those have to be cleared whenever Y is reassigned)

It turns out, LLVM does a similar value range tracking.


For each branch, enter the condition. If it is lt/gt/eq where one of the arguments is a variable, add restriction.
if both are expressions: lt(e1, e2) add upper(e1) +1 <= lower(e2) - if there is no overflow.

If a branch is non-continuing, add the negation of the expression to the continuing branch.

With the example above, we get:

```
after line 1:
 x <= 1000
after line 3:
 y <= 1000
inside the for loop: (before we enter the post part)
 i <= x - 1      -   is this a condition for i or for x?
 1 <= x

Then in line 9:
 add(x, y): we check that we have no overflow, because the sum can be at most 2000
   (for each variable, we have a function that returns the smallest constant upper bound)
 so we get the restrictions:
  1 <= add(x, y) <= 2000
  x <= (take constant lower bound for y)
  y + 1 <= (take constant lower bound for x)
 and now we check whether i + 1 <= add(x, y) is a possibility.
 if one of ther upper bounds of i + 1 is less or equal than one of the lower bounds for add(x, y),
 it is always true.
 one of the upper bounds for i + 1 is x
 one of the lower bounds for add(x, y) is x
 -> always true 
```

**Comment by chriseth** [comment]
Another nice challenge (part of the ABI decoder):
```
if iszero(slt(rel_offset_of_tail, sub(sub(calldatasize(), base_ref), sub(<neededLength>, 1)))) { revert(0, 0) }
```

**Comment by chriseth** [comment]
We might need a generic expression structure, for example if we have code like the following:
```
let x := calldataload(0)
let y := add(x, 10)
// at this point, we cannot have any meaningful restriction on the value of y, especially due to overflow
if lt(x, 20) {
  // here we have a restriction on x and thus on y,
  // but if we compute the restriction at the time of assignment,
  // it does not help us here.
}
```

**Comment by chriseth** [comment]
Hm, the above might actually not be a problem, since we can add the constraints `x + 10 <= y <= x + 10`, without evaluating it. The point where we make use of the constraint is where we have to check that it will not cause overflow.

**Comment by chriseth** [comment]
Maybe it would be better to just implement the very restricted special case of
```
if x { revert(0, 0) }
mstore(0, x)
```
to be reduced to
```
if x { revert(0, 0) }
mstore(0, 0)
```

**Comment by chriseth** [comment]
This would actually even allow the "[promised optimization](https://chriseth.github.io/notes/talks/solidity_optimizer_devcon4/#/20)"

**Comment by leonardoalt** [comment]
What about extending the current PR with https://github.com/ethereum/solidity/issues/6252#issuecomment-527141087?

**Comment by chriseth** [comment]
I'm actually not sure if there is so much overlap between the current PR and the idea above.

**Comment by ekpyron** [comment]
Also worth to consider: for a function we could collect all call sites, combine the constraints on the used arguments and optimize the function with those constraints on its arguments.
