### ISSUE TITLE
Throw error if import not used?

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#626]
Currently, the compiler will still compile a file where an import is declared, but the contents of said import are nowhere used in the file. Might we consider throwing an error if they are not used?

**Comment by Denton-L** [comment]
Maybe not an error but a warning?

**Comment by chriseth** [comment]
No, because you might want to import symbols just for the purpose of exporting them again.

**Comment by VoR0220** [comment]
Well why wouldn't you just import the symbols in the needed contract then?

**Comment by chriseth** [comment]
You can create a "package" that exports a selection of symbols from other files. Closing this now, we can discuss further on gitter.
