### ISSUE TITLE
Test ABIEncoderV2 with optimizations against real-world projects that use ABIEncoderV2

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6266]
Part of https://github.com/ethereum/solidity/issues/5956.

**Comment by rainbreak** [comment]
Can make a separate issue for this if appropriate. With the AbiEncoderv2, is the intent to have structs returned from auto-generated getters for public storage?

For example,

```
struct Data {
    uint256 x;
    bytes32 y;
}

mapping (bytes32 => Data) public data;
```

This exposes the getter `function data(bytes32) public view returns (uint256,bytes32)`

Is it possible that it could instead expose `function data(bytes32) public view returns (Data)`?

**Comment by axic** [comment]
@rainbreak please open a new issue for this

**Comment by chriseth** [comment]
We can also forcibly activate ABIEncoderV2 in all external tests.

**Comment by chriseth** [comment]
@erak what is the status here?

**Comment by axic** [comment]
Is this still relevant for 0.6.0?

**Comment by axic** [comment]
Still relevant given we enable it in 0.8.0?

> We can also forcibly activate ABIEncoderV2 in all external tests.

Was this ever done? We'll do it for 0.8.0 at least.
