### ISSUE TITLE
Subranges for calldata arrays.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6267]
Calldata arrays should support accessing subranges e.g. ``msg.data.subrange(4)``, resp. ``msg.data.subrange(4, 4+32)``, etc.

This would fix issue #6012 and has interactions with #6220.

**Comment by chriseth** [comment]
We could restrict that to `bytes calldata` for now.

Would also suggest to use `.slice`.

**Comment by ekpyron** [comment]
I'm fine with ``.slice`` instead of ``.subrange``, but I think it's not necessary to restrict to ``bytes calldata`` - it's straightforward for any base type, even for dynamically encoded arrays.

Should we overload ``.slice``, as in ``array.slice(begin)`` = ``array.slice(begin, array.length - begin)`` or should we let the user do that?

Or more generally: should the signature be ``slice(begin,length_of_slice)`` or ``slice(begin,end)``?

**Comment by ekpyron** [comment]
Done in https://github.com/ethereum/solidity/pull/7340
