### ISSUE TITLE
[DOCS] Add mention that typed YUL is not yet supported

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#6268]
Add a mention to YUL docs that typed YUL is not yet supported, and what versions of YUL are supported.

**Comment by chriseth** [comment]
This is basically what the note on https://solidity.readthedocs.io/en/v0.5.5/yul.html already says, just that `yul` is actually not supported anywhere yet.

**Comment by chriseth** [comment]
And if you want to use the commandline interface, you should use `solc --strict-assembly --optimize` to get an optimized strict assembly compiler.
