### ISSUE TITLE
Authenticated Binaries

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#628]
Currently, the archived binaries of the compiler are only published on github. While this provides a certain protection against manipulation due to the use of git, it is not really in spirit with the decentralisation efforts we are propagating. Also in light of the planned improved [source code verification](https://github.com/ethereum/solidity/issues/611), the following changes are proposed:
- [ ] create a contract on the blockchain that connects
  - compiler version
  - "stability" (nightly snapshot or release)
  - sha3 hash of the binary
  - commit hash of the source code (this will only be partly meaningful until solidity is a fully standalone repository)
- [ ] create a CI job that performs nightly compilations and automatically
  - publishes this meta data to the blockchain
  - pushes the binary onto github
  - pushes the binary into ipfs (and swarm in the future)
- [ ] provide a mechanism usable by a set of developer to revoke/update the CI key

Especially the fact that the sha3 hash of the binary is available to the blockchain will allow contracts to be verified on chain (once we have interactive verification in place), because they can request external entities to execute the binary given by the hash.

**Comment by axic** [comment]
Hash of which binary? Emscripten? Ubuntu yy.mm? OSX?

**Comment by ekpyron** [comment]
When discussing this we should also discuss the ideas in #5627, although I'm not sure whether we should go for signed git commits.

**Comment by ekpyron** [comment]
Something like this would be great, but haven't looked into it much, may very well be infeasible: https://wiki.debian.org/ReproducibleBuilds/

**Comment by lookfirst** [comment]
> I'm not sure whether we should go for signed git commits.

Why?

**Comment by ekpyron** [comment]
From https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work:
>  Everyone Must Sign
>
> Signing tags and commits is great, but if you decide to use this in your normal workflow, you’ll have to make sure that everyone on your team understands how to do so. If you don’t, you’ll end up spending a lot of time helping people figure out how to rewrite their commits with signed versions. Make sure you understand GPG and the benefits of signing things before adopting this as part of your standard workflow.

This wouldn't be a problem for our core team, but we have a lot of external contributions and we probably can't expect all of them to sign their commits. We could look into signing as part of the review process of external contributions (e.g. signing when merging after review), but we'd need to look into how that would affect our workflow (I haven't looked into what that would look like in detail, hence: I'm not sure yet ;-)).

We could also consider not signing ``develop`` commits, but only the merges to the release branch, that might be a feasible option as well.

**Comment by chriseth** [comment]
Signing merges into release could give the impression that the signer reviewed the full changeset before merging...

**Comment by lookfirst** [comment]
I am not a fan of making people jump through additional hoops when contributing code, but this is one area that I think would benefit the development community as a whole. Just like signing a CLA is required for a lot of OSS projects, this is just another step in the development process that encourages people to be responsible.

One would hope that anyone wanting to contribute code to solidity would be able to understand and implement the concepts around basic public key cryptography. Enough so that they could read some [basic documentation](https://help.github.com/articles/signing-commits/) and sign their commits.

At the end of the day, it is your project. I'm just making suggestions on how to help ensure the general trust of it. It isn't like [issues never happen](https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor).

**Comment by lookfirst** [comment]
I am also a little surprised this has been unresolved since 2016. My guess is the initial scope was a bit too large. How about just starting with signing the binaries published on the github releases tab?

**Comment by chriseth** [comment]
I see zero benefit in requiring "random" people to sign their commits - that can be easily faked. It actually has a negative impact because it gives a false impression of security.

You are right, the scope of this initial issue was too large, we should sign the binaries.

**Comment by lookfirst** [comment]
Why does solidity accept contributions from 'random' people?

**Comment by chriseth** [comment]
@lookfirst if you would like to have an interactive discussion about this, I would be very happy to talk to you in gitter.im/ethereum/solidity-dev or in one of our weekly calls (Mondays at 12.00 CET and Wednesdays 150.00 CET, conference link announced in the chanel).
