### ISSUE TITLE
Support optimizer tests that run only on certain versions

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#6286]
E.g. one test might require SHL/SHR instructions which are only available on >= Constantinople

**Comment by Marenz** [comment]
This can be implemented similar to how ["struct yul" tests are implemented](https://github.com/ethereum/solidity/blob/develop/test/libyul/YulOptimizerTest.cpp#L89).
Syntax suggestions:

```
// arch >= constantinople
contract test { .. }
```

Basically you can combine any version string with any comparison: `==`, `>=`, '<=`, `>`, `<`.

Instead of `arch` it could say one of `version`, `evm-version`, `evm`

**Comment by chriseth** [comment]
Perhaps we should just start with evm version names without any comparison operators, which would then mean "at least that version".

**Comment by Marenz** [comment]
So it doesn't get lost, here are the tests that require the feature: https://github.com/ethereum/solidity/tree/test-requiring-constantinople

**Comment by Marenz** [comment]
duplicate of https://github.com/ethereum/solidity/issues/4262

**Comment by Marenz** [comment]
Not exactly a duplicate as the motivation for this issue were optimizer tests

**Comment by chriseth** [comment]
This has been implemented.
