### ISSUE TITLE
Multiple token transfer in exchange site

### ISSUE THREAD

**Issue by blockchain-app12** [ethereum/solidity#6287]
## Description
Hi, I am working on token exchange site. In which I wrote functions for transferring multiple tokens. When I tried to transfer token in my contract it shows gas estimation failed. It's not calling the approve function. If I call approve function of token contract from my contract, it takes msg.sender as my contract address by that it process as my contract address (instead of my wallet address) approving spender address.Kindly go throw the below contract and help finding the solution.

    function transfer(address token, uint256 tokens)public payable                         // deposit perticular token balance to contract address (site address), can depoit multiple token   
    {
        if(Token(token).approve(address(this),tokens))
        {
            dep_token[msg.sender][token] = safeAdd(dep_token[msg.sender][token], tokens);
            Token(token).transferFrom(msg.sender,address(this), tokens);
        }
    }
    
    function token_withdraw(address token, uint256 tokens)public payable                    // withdraw perticular token balance from contract to user    
    {
        dep_token[msg.sender][token] = safeSub(dep_token[msg.sender][token] , tokens) ;   
        Token(token).transfer(msg.sender, tokens);
    }

**Comment by chriseth** [comment]
"gas estimation failed" looks like you are triggering a revert, for example due to an overflow.
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there. If you think this might be a bug in the compiler, please reopen the issue.

**Comment by blockchain-app12** [comment]
My actual question is, with multi token when I call approve function from exchange contract, nor my address and spender get approved. Instead only the exchange address and spender gets approved. 
Its like when I call approve with spender as my contract address, in token contract it takes msg.sender as my contract address.

Help me resolving this.

**Comment by chriseth** [comment]
I'm sorry, but this is really not the right place for such questions.
