### ISSUE TITLE
Still misleading error messages for external function calls.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6299]
The fix of #4307 is somewhat incomplete.

```
contract c {
    function f1() external returns (uint) {}
    // function f2() external returns (uint) {}
    function g() public { f1(); }
}
```
nicely yields (could still be improved, but fine)
```
DeclarationError: Undeclared identifier. "f1" is not (or not yet) visible at this point.
    function g() public { f1(); }
                          ^^
```

On the other hand, the following:
```
contract c {
    function f1() external returns (uint) {}
    function f2() external returns (uint) {}
    function g() public { f1(); }
}
```
yields
```
browser/Untitled.sol:6:27: DeclarationError: Undeclared identifier. Did you mean "f1" or "f2"?
    function g() public { f1(); }
                          ^^
```
Which is pretty weird - before searching for similar identifiers here, we should check whether there is an external function with exactly the same name. Also should "f1" and "f2" (since they are external) in fact be considered viable suggestions here?

In any case: not sure whether there's a duplicate for this, but it may be worth to improve all this somewhat more.

**Comment by ekpyron** [comment]
A simple solution might be to just add ``this.`` to the suggestions, if the type is an external function type. Might be better to distinguish between internal and external types for choosing suggestions in general, though.

**Comment by cameel** [comment]
I think this one should be reclassified as a bug and reopened. It's definitely a defect from user's point of view and even if it does not happen often, I can see it being very confusing to users when it does. This something that should be fixed eventually.

**Comment by ekpyron** [comment]
> I think this one should be reclassified as a bug and reopened. It's definitely a defect from user's point of view and even if it does not happen often, I can see it being very confusing to users when it does. This something that should be fixed eventually.

If it actually annoys users, we can wait for them to rereport it and classify it as a bug then - no need to jump at it ourselves ;-).
