### ISSUE TITLE
Tuple parsing requires all variables to be declared or none.

### ISSUE THREAD

**Issue by shahankhatch** [ethereum/solidity#6302]
## Description

Using the following code (in Remix) reports a syntax error, but doesn't seem like one.
`uint i_tcr=0;
(i_tcr, bool check_v)=tcr.index_get_v(msg.sender);`

Expected ',' but got identifier
(i_tcr, bool check_v)=tcr.index_get_v(msg.sender);
              ^-----^

The syntax error does not appear if both variables are declared beforehand.

`uint i_tcr=0;
bool check_v=false;
(i_tcr, check_v)=tcr.index_get_v(msg.sender);`

## Environment

- Compiler version: soljson-v0.5.4+commit.9549d8ff.js
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: js

**Comment by erak** [comment]
Here's a minimal example that triggers this error:
```
function execute() public returns (uint, uint) {
    return (1, 1);
}
    
function test() public {
    uint a = 0;
    (a, uint b) = execute();
}
```
Whereas this compiles:
```
function test() public {
    uint a = 0;
    uint b = 0;
    (a, b) = execute();
}
```

**Comment by chriseth** [comment]
I fear we cannot change this, because the statement is either a variable declaration or it is an assignment. If we allow mixing it, it gets more complicated.

**Comment by shahankhatch** [comment]
At least the compiler gives an error when a variable shadows a previous variable declaration of the same name. 
Thanks for taking a look!
Closing.
