### ISSUE TITLE
[DOCS] Review and potentially clarify mappings docs

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#6303]

**Comment by ChrisChinchilla** [comment]
Feedback from ETHDenver.

As mappings (or changes to them are newer), this is a task to check if current documentation is clear enough, after feedback from developers. It may be that it's perfectly clear, but just newer so that people I spoke with hadn't read it before.

**Comment by chriseth** [comment]
Can you provide a bit more details?
