### ISSUE TITLE
[DOCS] How does solidity handle ETH refunds

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#6304]

**Comment by ChrisChinchilla** [comment]
Feedback from ETHDenver. Some people were confused as to what happens to unused ETH after contract execution. As this was just feedback, this is more of a task to check if that is really the case or not.

**Comment by chriseth** [comment]
Can you provide a bit more details?

**Comment by axic** [comment]
I'm closing this, but @ChrisChinchilla feel free to explain the issue more and reopen it.
