### ISSUE TITLE
[DOCS] How does solidity use memory in reserved slots

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#6305]

**Comment by ChrisChinchilla** [comment]
Feedback from ETHDenver

**Comment by chriseth** [comment]
Can you provide a bit more details? This is not covered here https://solidity.readthedocs.io/en/v0.5.6/miscellaneous.html#layout-in-memory ?

**Comment by ChrisChinchilla** [comment]
That seems comprehensive to me @chriseth this was mostly a task to check if feedback I received was true or not :)
