### ISSUE TITLE
About solidity compiler 0.4.15 and nightly

### ISSUE THREAD

**Issue by Winterlx** [ethereum/solidity#6327]
## Description
I have a .sol file which the version is "pragma solidity ^0.4.15;" , and i download the 0.4.15 version
 solc here(https://github.com/ethereum/solidity/releases?after=v0.4.16).
Now i get a ERROR:
`MultiSigWallet.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.15-nightly.2017.8.10+commit.8b45bddb.Windows.msvc - note that nightly builds are considered to be strictly less than the released version`
How can i solve it?
(forgive my poor EnglishXD)

**Comment by Skyge** [comment]
Maybe you can download the version 0.4.16 to have a try. By the way, the latest version is Version 0.5.6, you can have a try.

**Comment by Winterlx** [comment]
@Skyge 
Thank you for your reply.
I use 0.4.15 because i found a MultiSignatureWallet.sol which is write in 0.4.15 and I am afraid it will broken if I modify it.
I found a website to generate .abi and .bin file online and get .java file with web3j wrapper.
I have been deployed a smart contract and now I`m testing other function. 
谢谢你的回复~
我用0.4.15是因为我找到的多签钱包的.sol文件是用0.4.15写的，我怕我改了之后用不了了_(:з」∠)_
我找到了一个网站在线编译的 http://chriseth.github.io/browser-solidity/#version=soljson-v0.4.15+commit.bbb8e64f.js&optimize=true 
已经生成.java文件，deploy上去了，正在测试其他功能。

**Comment by chriseth** [comment]
@Winterlx where exactly did you download the version 0.4.16 from?

**Comment by Winterlx** [comment]
@chriseth hello
0.4.16?
I download 0.4.15 at the release page https://github.com/ethereum/solidity/releases?after=v0.4.23

**Comment by chriseth** [comment]
Which of the releases there did you use? Which system are you running?

**Comment by chriseth** [comment]
Did you use one of the provided binaries or did you compile yourself?

**Comment by Winterlx** [comment]
![image](https://user-images.githubusercontent.com/18513073/54678875-f9a76c80-4b40-11e9-869d-396990ccfa20.png)
and I get this error
![image](https://user-images.githubusercontent.com/18513073/54679017-49863380-4b41-11e9-9be8-5e65270d52b9.png)
Thank you for your reply.

**Comment by chriseth** [comment]
It looks like this release has an error then. Could you try 0.4.16? I think you should really use 0.4.25, though.

**Comment by Winterlx** [comment]
I`ll try 0.4.16.
I use 0.4.16 because I have a .sol file programmed with 0.4.15 and I don`t know how to change the .sol file and make it work _(:з」∠)_.
Thank you!

**Comment by axic** [comment]
> I have a .sol file which the version is "pragma solidity ^0.4.15;"

This means it requires at least 0.4.15 but will work with any later 0.4 version.

**Comment by cameel** [comment]
Just for reference, there was actually an issue with 0.4.15 reporting as nightly on Windows. It's been reported in #9545 and we're going to rebuild and update the binary on the release page.
