### ISSUE TITLE
[Yul] Improve error reporting for datasize() & dataoffset() misusage

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#6330]
This is in reference to PR #6322, where we provide better exception diagnostics.

Now, the plan is to properly catch invalid arguments to those assembly functions by catching them earlier, i.e. in the AsmAnalysis.

For that to work, AsmAnalysis needs to know about assembly objects (structure).

Passing an invalid argument should then report to `ErrorReporter` as a `TypeError` (?).

**Comment by axic** [comment]
Can you explain what is the problem here? We seem to have a check in `AsmAnalysis` for finding unknown object cases (errorcode 3517).
