### ISSUE TITLE
Feature: Output AST recovering from all parsing errors to support all tooling

### ISSUE THREAD

**Issue by juanfranblanco** [ethereum/solidity#6342]
There has been many attempts to create different solidity language parsing components and /or AST providers to support solidity tools and IDEs. 

The problem is that all this disparate components are immediately out of date witch each solidity release, which is normally in a weekly basis.

Also different users, use different versions of solidity, so there is not a reliable way to inform a user or provide tooling based on their current version of solidity.

Solc itself provides the AST output after the compilation of a smart contract or contracts, together with any compilation errors. 

If Solc was able to recover from any parsing errors and output the AST in the same way that is done after compilation, tooling could be built on top without any external dependency and with the knowledge that any errors are inline with the current version of solidity itself.

Example of usage or tools that could be built on top.

* Linting (Ethlint / Solium or Solhint) could validate, and fix errors using the same AST parser.
* Language server features
- Auto complete
- Goto definition
- Refactoring (rename function, variable, across smart contracts)
* On the fly smart contract analysis 
* Extra addons

**Comment by chriseth** [comment]
Some simple ways to recover:

Inside parenthesized expression, catch the fatal parser error, search for the next closing parenthesis and continue for there, ignoring everything that was skipped over.

The same can be done at statement level (search for next `;`) and contract level (search for next `}`).

**Comment by rocky** [comment]
Please correct me if I am wrong, but there are a couple of parts to this:

* Recover when there are parse errors
* Output AST information even if it is incomplete.

Let me elaborate on these two. 

@chriseth suggests specific examples that I think fall into of the general method described in [Efficient and Comfortable Error Recovery in Recursive Descent Parsers](https://pdfs.semanticscholar.org/8ec1/6b0f5d9fd4ebb3dd5a5d2ce5c85df382c9c5.pdf?_ga=2.66202926.1641430271.1553456907-1338304767.1553456907).

Here ')' , '}', and ';' are examples of symbols when seen often trigger the completion of a production rule (or production function), such as for an expression, a block statement, or a statement respectively for each of those symbols.

Another kind of recovery, not mentioned above but mentioned in the cited paper, is where there is a token that is expected and missing, for example contract name after the word `contract`. Recovery here just adds that token.

Balancing expediency with a full solution, what I'd propose to do is implement something along the lines of what @chriseth suggests, but doing it more along the lines mentioned in the paper. In doing it this way, some simple errors can be caught and we can see results more quickly, while leaving open the possibility of handling fine-grained or other kinds of situations later. Improving error recovery an be incremental.

Doing a general solution described in the paper would probably require an automated a way to compute these "first" and "follow" sets which would need to be done every time the grammar changes.  On the other hand, extending on the simple "gobble until recovery symbol" idea, one could generalize that approach a little bit more and compute some these "first" and "follow" sets by hand. By starting with the higher level productions (contract, function, compound statement) and working down the the lower-level ones (e.g. statement, assert statement, expression),  error recovery can be added incrementally on a grammar production (or recursive procedure)  basis.

But even if there were some sort of recovery in place, there is second problem to address: even when there _is_ some sort of failure, solc should still spit out any AST information it has, even if incomplete. 

For example: suppose there are two functions and only one of them has an error, let's say the 2nd one, and we just can't recover from it, then at least output AST for the first function can be emitted.

Thoughts?
