### ISSUE TITLE
Problems accessing methods in contracts compiled in Solidity 0.5.5 onwards

### ISSUE THREAD

**Issue by kevinaquick** [ethereum/solidity#6345]
We are running a number of Parity Private Networks running with PoA.

The configuration being
Contracts compileD with differing versions of solcjs  (also used the code compiled on Remix as a double check)
Parity 2.3.7-stable-7d1415a-20190320
Linux Ubuntu 16.04.6

We recently updated the version of Solidity our contracts were compiled under and have found that we can no longer make calls to methods within the Contract. We have investigated this in detail and have found that when contracts are compiled  for solidity versions higher than 0.5.4 we can no longer access the methods in the contract (we progressively compiled contracts from 0.4.x up to 0.5.7 = current stable release).

Having discovered the issue we wrote an extremely basic contract, to test what/ when the problem occurred. An example of the contract being as follows:

pragma solidity ^0.5.5;

contract test {
address public owner = 0x005e6478C5f01671f632d987e1aE862c570B7FB8;
string public name = "Fred";

constructor() public {
}
function getOwner() view public returns (address) {
	return owner;
}

}

We have tried calling the getOwner method via web3 IPC calls using both the most uptodate version of web3 (1.0.0-beta.50) and a much older version - both versions of web3 successfully can call getOwner and receive the returned address value IF the contract is compiled on versions of solidity of 0.5.4 and below, but fail for higher versions. To eliminate the possibility of this being a problem in the web3 code we repeated the experiment, but instead accessing the contract via CURL calls e.g.

curl localhost:55260 -X POST --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"from": "0x00e9415aa2b0a4b37537c5f0e3f5dfc6b0a46aac", "to": "0xb45211274e8644bef6517aca557aa247d99e5a67", "data": "0x893d20e8"}], "id":1}' -H "Content-Type: application/json"

This behaved identically to the web3 i.e. getOwner() could be called successfully as long as the contract was compiled for Solidity 0.5.4 and below. For 0.5.5 to the latest stable release 0.5.7 the following error is generated (from the curl calls although effectively identical to that thrown out by web3):

{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Bad instruction 1c"},"id":1}

SO I think that eliminates web3 etc.

We also have a private Geth chain and we observe identical behaviour here to with contracts compiled for 0.5.5 solidity onwards

**Comment by chriseth** [comment]
Following the hard fork on the Ethereum mainnet that occured shortly before the 0.5.5 release, the default EVM version now is set to "petersburg". If you are running a byzantium testnet, you have to compile with `--evm-version byzantium` or similar in the standard-json settings.

Please reopen if this did not solve the problem.
