### ISSUE TITLE
Examine new Solidity fork called dsolidity

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6354]
https://github.com/dexon-foundation/dsolidity

The only addition they seem to have is support for a new opcode, `RAND`.

**Comment by cameel** [comment]
Seems to have moved to https://github.com/dexon-foundation/ace-mode-dsolidity (or https://github.com/raphaelhuefner/ace-mode-solidity). Also, looks abandoned (no new commits since 2018).

**Comment by axic** [comment]
ace-mode is syntax highlighting tool, so I'd say they just made the repo private or deleted it.

**Comment by cameel** [comment]
Ah, sorry. I should have taken a better look at it before posting :)

Anyway, the repo is gone and the only trace is a stub in their docs: https://dexon-foundation.github.io/wiki/dsolidity.html. All public activity in organization's 42 repositories seems to have stopped a year ago. The [last activity on their gitter channel from nov 2019 is people saying it's dead](https://gitter.im/dexon-foundation/Lobby?at=5da834972d59854e7f1abb84). I think we can close this one.
