### ISSUE TITLE
homebrew provides commits rather than official `solc` versions

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/solidity#6357]
Hi There,

I've noticed that when installing from `brew`, Solidity installs specific commits rather than the official well-formatted versions. For example, right now:

```bash
solc --version
#  Version: 0.5.5+commit.47a71e8f.Darwin.appleclang
````

This in turn, makes the `solc`installations incompatible with libraries like `py-solc-x` which expect to use the official release versions.

**Comment by Pet3ris** [comment]
Yep - ‘py-solc-x’ depended on that exact assumption. I’ve realised they’re probably in the wrong here not ‘solc’ itself and have moved to another wrapper!

**Comment by axic** [comment]
Any non-release (developer version or nightly) would have a tag after a dash (`-`), such as `0.5.7-develop` or `0.5.7-nightly`.

The tags after the `+` sign are just informational.

Can we close this then?

**Comment by Pet3ris** [comment]
Absolutely - thanks a lot.
