### ISSUE TITLE
Yul optimizer: Structural simplifier generates incorrect code while optimizing switch statement with no default statement

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6359]
### Bug report
        
The following code snippet
```
        {
        foo(calldataload(0))
        function foo(x)
        {
            switch x
            case 0 {
            }
            case "" {
                sstore(1, 1)
            }
        }
    }
```
        
triggers an optimization bug.
        
        
        
Trace of unoptimized code
        
        Trace:
Memory dump:
Storage dump:

        
Trace of optimized code
        
        Trace:
  SSTORE(1, 1)
Memory dump:
Storage dump:
  0000000000000000000000000000000000000000000000000000000000000001: 0000000000000000000000000000000000000000000000000000000000000001

### Notes

The bug happens because the following conditions are met
  - Structural simplifier removes case statement with no body in switch statements without a default case statement
  - It then replaces single case switch statement with an equivalent if statement

The problem is that the resulting if statement returns true because an empty string literal evaluates to zero.

The underlying problem seems to be supporting case literals of mixed types (string and uint) that are handled differently in switch statements and if statement (and possibly others).

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): Petersburg
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 18.04

## Steps to Reproduce

One can step through the buggy transformation using the yulopti tool by passing the `t` option (Structural simplifier)

```
$ yulopti --input-file <code.yul>
----------------------
{
  foo(calldataload(0))
  function foo(x)
  {
    switch x
      case 0 {}
      case "" {
        sstore(1, 1)
      }
  }
}

(q)quit/(f)flatten/(c)se/initialize var(d)ecls/(x)plit/(j)oin/(g)rouper/(h)oister/
  (e)xpr inline/(i)nline/(s)implify/varname c(l)eaner/(u)nusedprune/ss(a) transform/
  (r)edundant assign elim./re(m)aterializer/f(o)r-loop-pre-rewriter/
  s(t)ructural simplifier/equi(v)alent function combiner/ssa re(V)erser/? 
  stack com(p)ressor? 
t
 t
----------------------
{
    foo(calldataload(0))
    function foo(x)
    {
        if eq("", x)
        {
            sstore(1, 1)
        }
    }
}
```

**Comment by axic** [comment]
> The underlying problem seems to be supporting case literals of mixed types (string and uint) that are handled differently in switch statements and if statement (and possibly others).

They are not supposed to be mixed, but we do not have type validation implemented yet 😢

**Comment by chriseth** [comment]
Actually we can use `valueOfLiteral`
