### ISSUE TITLE
Change libyul/AssemblyStack to allow warnings to pass through

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6375]
A lot of the testing infrastructure needs to be updated for this.

Once done, the following warning in `StandardCompiler` should be moved to `AssemblyStack`:
> `output["errors"].append(formatError(true, "Warning", "general", "Yul is still experimental. Please use the output with care."));`

**Comment by chriseth** [comment]
This specific warning should not be moved into assembly stack, because it is used internally a lot. We might also not have any real warnings in assembly anymore. Closing for now.
