### ISSUE TITLE
Upgrading from 0.5.2 -> 0.5.5+ causes "InternalCompilerError: Stack too deep when compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack."

### ISSUE THREAD

**Issue by mrwillis** [ethereum/solidity#6392]
## Description

I seem to get an error compiling my contracts. When upgrading to 0.5.5+ I get

> InternalCompilerError: Stack too deep when compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack.

No information other than that. On 0.5.4 I get the error in https://github.com/ethereum/solidity/issues/5997

On 0.5.2 I can compile fine.

The only assembly I have in my code is (openzeppelin ECDSA.sol)

```
        // Divide the signature in r, s and v variables
        // ecrecover takes the signature parameters, and the only way to get them
        // currently is to use assembly.
        // solhint-disable-next-line no-inline-assembly
        assembly {
            r := mload(add(signature, 0x20))
            s := mload(add(signature, 0x40))
            v := byte(0, mload(add(signature, 0x60)))
        }
```

and

```
        assembly {
            // Retrieve the size of the code on target address, this needs assembly .
            codeLength := extcodesize(to)
        }
```

**Comment by chriseth** [comment]
Can you provide a complete source file that triggers the error? This looks like the source of the error is inside the ABI encoder. It might also that Solidity 0.5.7 fixes your issue, it includes a change to the stack allocation inside the optimizer.

**Comment by mrwillis** [comment]
`0.5.7` causes the issue as well. Let me get that for you.

**Comment by mrwillis** [comment]
Having some trouble tracking this down as my project is pretty big with lots of inter-dependencies. Is there a way to enable debugging to at least track down the file and then go from there?

**Comment by chriseth** [comment]
One of your functions has too many parameters or too many return values. I assume you are using ABIEncoderV2. The ABIEncoderV2 code was not meant to be used without yul optimizer, so if you enable that one (which could be quite risky, I have to admit), you could get your code to compile.

**Comment by mrwillis** [comment]
@chriseth Ok i am able to reproduce in this small repo

https://github.com/mrwillis/abiencoderv2-repro

Seems to be related to hashing in one of the libraries.

Just run `truffle compile` and you will see the error.

**Comment by chriseth** [comment]
It compiles fine for me on 0.5.7 with `--optimize-yul`, it does not without the yul optimizer.

**Comment by mrwillis** [comment]
Yeah it does for me as well. What do you recommend? You say it would be quite risky to enable the Yul optimizer as of now. I have seen some projects go for it though.

**Comment by chriseth** [comment]
I think I always said "if you test all code paths, the ABIEncoderV2" should be safe to enable. A rather critical bug turned up months after I made that statement but I actually think nobody used the part of the code the bug is in and if they used it, it was not tested. Following that incident, I'm a bit more cautious now, but the same holds true for the optimizer, too, I would say.

**Comment by mrwillis** [comment]
Got it thanks Chris.
