### ISSUE TITLE
[SMTChecker] Support inheritance

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#6399]
This includes
- `visit(ContractDefinition)` should also visit all public functions of base contracts that are not overridden;
- calls to functions from base classes that are not overridden should be inlined
- since the SMTChecker simulates execution paths, there's no need to start from internal functions.
- visit state vars of base contracts #6562 

Hint: check function `resolveVirtualFunction`

**Comment by chriseth** [comment]
Test case:
```
contract A {
  function f() public { assert(g() == 1); }
  function g() internal returns (uint) { return 1; }
}
contract B is A { function g() internal returns (uint) { return 2; } }
```
