### ISSUE TITLE
Incorrect topic[0] hash for Library events that use a contract's name instead of address type

### ISSUE THREAD

**Issue by BrendanChou** [ethereum/solidity#6435]
Probably related to #6001 

## Description
When hashing for the topic[0] of an event, solidity uses the name of the contract rather than `address`

## Environment
Compiler version: 0.5.7 stable
Framework/IDE: Truffle
Steps to Reproduce
Given:
```
pragma experimental ABIEncoderV2;
import { AnotherContract } from "./AnotherContract.sol";
library LibName {
    event Loggy(uint256 aNumber, AnotherContract anAddress);
    ...
        AnotherContract contractInstance = AnotherContract(someGivenAddress);
        emit Loggy(0, contractInstance);
    ...
}
```
`Loggy` has a `topic[0]` of: `keccak256("Loggy(uint256,AnotherContract)")`
but it should be: `keccak256("Loggy(uint256,address)")`

**The abi seems to contain the correct hash**, but the actual bytecode seems to be wrong

**Comment by chriseth** [comment]
Might need an entry in the bug list.
