### ISSUE TITLE
[Yul] Scope Filler: namesake variable and function fail assertion inside closeScope

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6446]
## Description

In

```
{
  pop(f())
  function f() -> b { let g := mload(0) b := 0 }
  function g() {}
}
```

At the time, the yul Interpreter encounters the close scope `}` of `f()`, it sees both a variable and a function named "g" that are in scope and deletes them both tripping this assertion

https://github.com/ethereum/solidity/blob/7c880a26c021fa949f400c9ce5b02a05756bc2a7/test/tools/yulInterpreter/Interpreter.cpp#L176

because `erased == 2`

**Comment by chriseth** [comment]
This is a bug in the ScopeFiller where it allows shadowing although it should not be legal.
In `ScopeFiller::operator()(Block const&`, it should first register all functions and only actually visit them later.

**Comment by chriseth** [comment]
Will fix it.
