### ISSUE TITLE
[Yul] Optimizer: Remove unused function parameters

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6449]
If a parameter is not used in a function, it can be removed. The same is true for return variables.

Call sites have to be modified accordingly, which will be much simpler if the code is in SSA form prior to this step. Note that we cannot assume SSA form for one specific edge case: If the function is used as the condition of a for loop. If the function's return variable turns out to be unused, we can _almost_ replace the function by the constant zero. The only problem are non-movable function arguments. They would have to be copied to right before the loop and to the end of the post part. Perhaps it is better to fail in this case...

**Comment by sifmelcara** [comment]
Probably off-topic, but is there any reason to not prefer to transform for-loops into while-loop like structures?

For example,
```yul
for { let i := 0:u256 } lt(i, exponent) { i := add(i, 1:u256) }
{
    result := mul(result, base)
}
```
should be equivalent to 
```yul
let i := 0:u256
for { } true { }
{
    if (lt(i, exponent)) { break }
    result := mul(result, base)
    i := add(i, 1:u256)
}
```

By doing this we can avoid handling those SSA-related edge cases

**Comment by ekpyron** [comment]
@sifmelcara Support for ``break``s in ``for`` loops was only added recently, so we didn't have this option until now. It might indeed make sense now and we could consider it - if you want, you can create a separate issue for discussing this (please do so for such discussions) - since it's off topic here, I'll minimize it as not to pollute the issue.

**Comment by chriseth** [comment]
@ekpyron @sifmelcara `breaks` seriously complicate the control flow and it might be that we cannot perform some optimizations we could do otherwise - but that would need to be checked.

**Comment by ekpyron** [comment]
Related discussion: https://github.com/ethereum/solidity/pull/8863/files#r421378666

**Comment by chriseth** [comment]
Summary of the linked discussion:

Implement unused function parameter removal as follows:

If a parameter is unused like in 

```
function f(a,b,c) -> x { x := div(a,b) }
```

Then remove the parameter and create a new "linking" function as follows:

```
function f(a,b) -> x { x := div(a,b) }
function f2(a,b,c) -> x { x := f(a,b) }
```
and replace all references to `f` by `f2`.

Subsequent steps should make sure that `f2` is inlined, which AFAIK is the case unless we have recursion.

The reason we do not convert `f` into a new function with a new name is because we want to retain the original name after inlining.
