### ISSUE TITLE
Fuzz yul optimizer's memory optimization

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6468]
## Abstract

(Depends on #6469 #6808 #6800 #6798 )

This issue tracks fuzzing support for an upcoming version of the yul optimizer that optimizes memory opcodes such as stores (mstore/sstore) and loads (mload/sload).

The main bottleneck is that the current fuzzing setup relies on an exact trace match pre and post optimization. This is no longer guaranteed when memory optimizations are enabled.

Example

```
{
mstore(0,1)
mstore(0,2)
}
```

may be optimized to 
```
{
mstore(0,2)
}
```

## Motivation

One option is to rely on memory and storage dumps from the interpreter state like here (and not on the trace) specifically for fuzzing memory optimizations

https://github.com/ethereum/solidity/blob/8c570f31c55d5bc7d39187022fe4a119a0de09ad/test/tools/yulrun.cpp#L106-L111

But to be able to do that efficiently, we need to first implement memory/storage representation with holes so that printing sparse memory doesn't take forever.

## Specification

See https://github.com/ethereum/solidity/pull/6800/files#r286045434

**Comment by axic** [comment]
@bshastry was this done?

**Comment by bshastry** [comment]
Closing cos fixed
