### ISSUE TITLE
[yul interpreter] Implement memory/storage representation with holes

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6469]
## Abstract

We use a vector to represent EVM memory/storage. Sparse memory stores blow up the size of the vector and make it's printing slow.

Example

```
{ mstore(67889, 1) }
```

resizes the vector to over 64 KB and stores a "1".

When we are printing the contents of memory (main use case being checking equivalence while fuzz testing), this becomes too slow.

## Motivation

TBD

## Specification

TBD

**Comment by ahlamna** [comment]
hi, i am new here

**Comment by ekpyron** [comment]
Maybe we should use some sort of paging? E.g. allocate fixed-size 4K blocks (or smaller) of memory and store them in a map...

**Comment by chriseth** [comment]
Or just use a `std::map`? One problem might be overlapping mload/mstore operations, but I'm actually not sure that is implemented correctly at the moment.

**Comment by bshastry** [comment]
Closed via #7325
