### ISSUE TITLE
Communicate with Etherscan to improve contract verification UX.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#6471]
## Description
At the moment, it appears that solc developers think that `solc --metadata` is the solution for contract verification of complex projects, while the Etherscan devs don't believe it will work in their environment.  Etherscan verification has become a critical piece of the smart contract ecosystem in Ethereum and making it easy for developers to validate complex contracts with Etherscan is important.

It would be nice if the solc developers got in touch with the Etherscan developers and figured out what can be done to make it so it is easy for developers to take standard `solc` output and feed it to Etherscan for validation.

----

Opinion on the UX of the current `--metadata` solution.

My understanding is that at the moment `--metada` spits out some hashes that point to files on Swarm.  However, last I checked swarm is not actually finished yet, I believe development of it has been put on hold, and I don't think many people actually run Swarm nodes.  On top of that, it means that the developer needs to publish to swarm, which means their build system needs access to a synced swarm node which can make building complicated.

It would be much simpler if there was an option to have solc spit out an input JSON that contained _everything_ necessary to reproduce the current build.  This would include inlined sources (post path resolution) so that someone could take this single JSON blob, feed it back into `solc`, and get out the exact bytecode that the first person got out.  Alternatively, `solc` could spit out a bundle that includes all of the necessary input files and input JSON necessary to do a deterministic build.  I very much prefer the single input-json output though, as it is much easier to just paste into a text entry box (even if it is long) than having to move a bundle around.

**Comment by chriseth** [comment]
Our last attempt to simplify verification with etherscan did not go very far, but I can try again.

Note that the fact that solidity uses the swarm hash is disconnected from swarm as a filesystem - it is just one of any possible hash system you can use.

As mentioned on another issue, ["useLiteralContent" for metadata](https://solidity.readthedocs.io/en/develop/using-the-compiler.html#input-description) almost provides what you want, the JSON just has to be re-ordered a little, but I agree, it would be much cooler, if the JSON could just be used as-is.

**Comment by chriseth** [comment]
We might want to start by create a script that codifies what is explained here: https://solidity.readthedocs.io/en/develop/metadata.html#usage-for-source-code-verification

**Comment by MicahZoltu** [comment]
I think it would help _me_ advocate more if I could see/present a shell script or something that shows how to verify contract code given only the compiler output JSON.  At the moment, I don't fully understand how to do contract verification myself, so it is difficult to advocate for others to do it.

Is this the sort of script you are referring to?

**Comment by chriseth** [comment]
@MicahZoltu yes, exactly!

**Comment by chriseth** [comment]
@MicahZoltu etherscan has updated their verification tool. How do you feel about it now? Closing for now, please re-open if you still think this needs work.

**Comment by MicahZoltu** [comment]
I haven't had a chance to try it out (haven't deployed anything recently), but it _looks_ like the situation has been remedied.
