### ISSUE TITLE
Metadata settings should re-produce the original 'useLiteralContents' setting from the compilation input.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6472]
Metadata settings should re-produce the original 'useLiteralContent' setting from the compilation input.

References https://github.com/ethereum/solidity/issues/6471

**Comment by Marenz** [comment]
So, to understand this correctly, the key/value `useLiteralContent` originally specified in the json input should also be output in the json output produced by `--metadata`? just directly at the root level object?
