### ISSUE TITLE
[Yul] Implement Sol->Yul codegen for ERC20 Token

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6478]
We should implement a version of https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol where we do not need the library and using for because we do our own overflow checking.

The following still needs to be implemented:

 - [x] return statement - #6589
 - [x] storage variables - https://github.com/ethereum/solidity/pull/6646
 - [x] member access to storage mapping - https://github.com/ethereum/solidity/pull/6655
 - [x] assignment to member of storage mapping / lvalue - https://github.com/ethereum/solidity/pull/6655
 - [x] require - https://github.com/ethereum/solidity/pull/6639
 - [x] emit - https://github.com/ethereum/solidity/pull/6663
 - [x] `msg.sender` - https://github.com/ethereum/solidity/pull/6662
 - [ ] require with reason

**Comment by SilentCicero** [comment]
@chriseth I've written a raw Yul ERC20 if you want it, also I'm writing a blog post on Yul (introduction to..), how can I get in contact to chat?

**Comment by Marenz** [comment]
@SilentCicero you can join us on gitter: https://gitter.im/ethereum/solidity-dev

**Comment by chriseth** [comment]
We might also complete all of https://github.com/hyperledger-labs/solang#what-is-implemented-so-far
