### ISSUE TITLE
[Yul] Add type conversions for Sol->Yul codegen

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6479]
The Solidity->Yul code generator currently does not implement type conversions even though the ABIFunctions already have most of them implemented.

The `convertType` function should be moved from ABIFunctions to YulUtilityFunctions and should be used in the Sol->Yul codegen.

**Comment by ekpyron** [comment]
As far as I remember, array conversions are missing entirely - I expect that to be the most effort - the rest should be quick.

**Comment by chriseth** [comment]
I would say that array conversions should be done in a different routine anyway, so out of scope of this issue. We considered making that more explicit in Solidity already.

**Comment by Marenz** [comment]
Is the Sol->Yul Code Gen done in `libsolidity/codegen/ir/IRGenerator`? Trying to find out where/how to implement this

**Comment by Marenz** [comment]
Elaborations by @ekpyron :

Basically you want to export ABIFunctions::conversionFunction to the outside (note that those are functions whose generation is deferred, so you have to make sure it's actually there in the end) and then call that from libsolidity/codegen/ir/*.

**Comment by chriseth** [comment]
Implemented in #6521
