### ISSUE TITLE
overloading for implicitly convertible types

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6498]
Might overlap with the inheritance rework for 0.6.0.

@nventuro requested that we allow overloading for implicitly convertible type - either generally or only if the type matches *exactly*. I'm opening this issue to discuss pro's and con's.

Current status:
```
function f(uint16) { ... }
function f(uint256) { ... }
function g() {
  f(0); f(1); f(255); // (1) invalid, ambiguous
  f(256); f(65535); // (2) invalid, ambiguous
  f(65536); // (3) valid, since only convertible to uint256, not to uint16
  f(2^200); // (4) valid
}
```

We could allow both the calls (1) and (2) or only (2) to choose ``f(uint16)`` without error. We could *disallow* (3) since it needs an implicit conversion in the presence of overloading.
We could also disallow *any* of them without explicitly casting the literal to the matching type (e.g. require an explicit cast from RationalNumberType to the matching IntegerType). If we go that way at all, I'd be in favor of this last option.

Technically, this would mean the following during overload resolution:
 - Collect all functions, s.t. *either* the supplied arguments can be implicitly converted to the parameter type *or* the parameter type can be implicitly converted to the type of the supplied argument. ***
 - If there is a unique such function, choose it.
 - Check whether one of the functions list matches the argument types *exactly* (i.e. without even an implicit conversion). If there is such a function, choose it.
 - Otherwise fail.

This would mean that in the example above (1)-(4) would all need explicit casts to the respective ``uintXX`` type (since literals are of ``RationalNumberType``, not ``uintXX`` type). This I would actually see as an advantage. Further we would have the following:
```
function h(uint8 a, uint16 b, uint32 c, uint256 d) {
 f(a); // (5) fail (currently fails)
 f(b); // (6) works (currently fails)
 f(c); // (7) fail (Note that this currently works!)
 f(d); // (8) works (currently works)
}
```

*** We need to consider implicit conversions in both directions to catch case ``7``. One might argue that ``7`` is just fine, but if one wants to prevent it, then we need to check whether checking implicit conversions in both directions prevents overload resolution in cases where it worked before and should continue to work.

**Comment by chriseth** [comment]
Relates to https://github.com/ethereum/solidity/issues/1256

**Comment by chriseth** [comment]
I think it would be best to disallow any overload resolution if the type does not match exactly.

**Comment by nventuro** [comment]
@chriseth so all calls to an overloaded function would require explicit casts, even if an implicit one is available?

Given
```
function f(uint8); // 1
function f(uint256); // 2

function g(uint16); // 3
function g(uint256); // 4

uint8 x;
```

`f(x)` calls 1, `f(uin256(x))` calls 2, `g(x)` fails, and both `g(uin16(x))` and `g(uin256(x))` call 3 and 4 respectively?

**Comment by chriseth** [comment]
@nventuro yes, that's what I mean.

**Comment by frangio** [comment]
I think we should be careful with forcing people to do these casts. It is very easy to do a downcast without realizing, and there is no warning if this could result in overflow.

**Comment by chriseth** [comment]
Indeed, I'm also worried about that. One way around this is as follows:
```
uint16 x = <something that implicitly converts to uint16>;
f(x);
```
