### ISSUE TITLE
Throw instead of STOP on failed CALL

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#650]
Hello. According to https://github.com/ethereum/wiki/wiki/Solidity-Features#detect-failed-calls

```
If a CALL fails, do not just silently continue.
Currently, this issues a STOP but it will throw an exception once we have exceptions.
```

We have exceptions, it's time to throw!

**Comment by chriseth** [comment]
This was a deliberate design decision because `call` is low-level feature and thus it allows you to make a fine-grained choice about whether you want to propagate exceptions or not. This is also the only way to actually catch an exception currently.

**Comment by lastperson** [comment]
@chriseth I've been suspecting such an answer :). Will update the wiki.

**Comment by lastperson** [comment]
Please review: https://github.com/ethereum/wiki/wiki/Solidity-Features#detect-failed-calls

**Comment by chriseth** [comment]
Sorry but I think you misinterpreted that entry in the features list. It was not about the `.call()` function but about the EVM opcode `CALL`. Please revert the change.

Note that the features list is not at all meant as documentation, but rather some kind of changelog for people who are on the cutting edge.

**Comment by lastperson** [comment]
@chriseth ok, changes reverted. But then, current (reverted) example is incorrect, because the code snippet and described behavior is not matching.

**Comment by chriseth** [comment]
The behaviour of the code snippet matches the state of the compiler at the time of writing. As I said, the features list is not meant as documentation.
