### ISSUE TITLE
Compiler meta-data that does not conform to the specs.

### ISSUE THREAD

**Issue by pieterhartel** [ethereum/solidity#6501]
Contract [ChannelManager](https://etherscan.io/address/0xbf2aeab03b82c182599930217272ef0fc5cf662b#code) has compiler meta-data that does not conform to the [specs](https://solidity.readthedocs.io/en/v0.5.7/metadata.html?highlight=bzzr). There are 306 bytes at the end of the bytecode that do not begin with `a165` but with `a265`. What does this mean? If this is an undocumented feature? Some documentation would be appropriate.

Here are the 306 bytes:

`a265627a7a72305820346bdebc5b65e540f2c06b10af9e3b0da5200dccdafe3e47d580b94d094ebdf96c6578706572696d656e74616cf50037000000000000000000000000526d0cd57a8b977d3628f12cdeceab12dd49297c00000000000000000000000000000000000000000000000000000000000151800000000000000000000000006b01c3170ae1efebee1a3159172cb3f7a5ecf9e5`

**Comment by chriseth** [comment]
Thanks for notifying! Indeed, we extended the CBOR mapping a little. The documentation says that you should take a look at the last two bytes, interpret them as a byte length and track back. Then just CBOR-decode the data you found - so the metadata parsers should actually not be made that restrictive.

**Comment by chriseth** [comment]
We should update the documentation to explain the new fields we added and perhaps also explain that new fields might be added any time without prior warning - those fields should be ignored by the parsers. @axic

**Comment by pieterhartel** [comment]
@chriseth thanks for your answer. In the example of the ChannelManager, one first has to remove the constructor arguments, then find the `0037` hex = 55 decimal, and then track back 55 bytes to the `a265`. An update of the documentation would be welcome!
