### ISSUE TITLE
[solc] Failed assertion (unknown magic member) in ExpressionCompiler for call to abi.encode

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6509]
Found by ossfuzz, issue 13693

This input
```
contract C{function f()public{abi.encode;}}
```

asserts here

https://github.com/ethereum/solidity/blob/826f2d908400fee9e0d4f90dc871c9774e5f0e42/libsolidity/codegen/ExpressionCompiler.cpp#L1404

Shouldn't this be a parsing error?

**Comment by chriseth** [comment]
No it should not. I think the problem is that `abi.encoed` is usually called immediately and when it is called, the code generation for the member is skipped. In this case, the fix would be to accept the code but do not generate any bytecode.
