### ISSUE TITLE
Require yul optimizer test expectations to start with ``//``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6511]
Came up in #6486.

Currently the ``//`` at the beginning of test expectations are optional (at least for the yul optimizer tests). Understandably, this can lead to confusion and inconsistency, so we should require expectation lines to start with ``//``. We should also verify that automatic expectation update puts them in, but I guess they do.

**Comment by chriseth** [comment]
The main reason I did not add slashes was that the output can be used as input again without modification. It did not turn out that useful, so it is probably better to unify the format instead and add the slashes.
