### ISSUE TITLE
Add section about project name, logo and license

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#6516]
Official logo: https://github.com/ethereum/solidity/blob/develop/docs/logo.svg

Should briefly highlight our preference about using the name and logo.

**Comment by axic** [comment]
@ChrisChinchilla was this fixed by any chance?

**Comment by ChrisChinchilla** [comment]
@axic Ahh, I was sure this was for me or not, but not done. Where can I find the "guidelines"?

**Comment by axic** [comment]
@franzihei do you want to perhaps look into this?

Basically what we may want to do is something like a "brand" section in the documentation.

**Comment by franzihei** [comment]
Yes, will take this task over!

**Comment by franzihei** [comment]
What I would need to know: 
- Under which license is the logo published? (e.g. some sort of [Creative Commons](https://creativecommons.org/licenses/) license?)
- Was there ever an "official" font connected to the Solidity logo? If yes, which font is it?
- Who created the Solidity logo; was there ever some sort of brand identity defined alongside of it, e.g. specific colors to be used etc.?

@chriseth and @axic?

**Comment by axic** [comment]
This is the earliest commit of the logo in https://github.com/ethereum/browser-solidity:
```
commit 16e7446998a2d012a482070f856d96b37cab8c19 (HEAD)
Author: d11e9 <d11e9@turkd.net>
Date:   Fri Oct 9 17:54:30 2015 +0100

    add missing img
```

I'm not sure who did it.

**Comment by chriseth** [comment]
https://github.com/ethereum/ethereum-org/blob/master/public/images/logos/Ethereum_Visual_Identity_1.0.0.pdf

**Comment by chriseth** [comment]
It was created by Ian Meikle - but I could not find any license anywhere.

**Comment by franzihei** [comment]
Created a doc here. Please review @axic @chriseth --> https://hackmd.io/@franzihei/ryJRP10aL.
If you're ok with it I'll add it to the docs as a section in the `Additional Material` section somewhere here: 

![image](https://user-images.githubusercontent.com/41991517/85273299-afb4e100-b47d-11ea-98b6-6fcc961c0394.png)

**Comment by axic** [comment]
> If you're ok with it I'll add it to the docs as a section in the Additional Material section somewhere here:

I think it makes sense, could call the section "Brand Guide" and place it below "Contribute" ?

**Comment by chriseth** [comment]
The document mentions "cc-by" - is it clear how to properly attribute if you use the logo?

**Comment by franzihei** [comment]
Good question @chriseth. Maybe we don't even need attribution...? If yes, I'll think about a way how attribution could work.
