### ISSUE TITLE
Dockerfile for lllc

### ISSUE THREAD

**Issue by yxliang01** [ethereum/solidity#6518]
## Abstract

There should be a Dockerfile for `lllc`.

## Motivation

Currently, there is docker image for `solc`, but not `lllc` which is also an executable placed in this repository.

## Specification

A new Dockerfile or add a new build target to current Dockerfile at https://github.com/ethereum/solidity/blob/develop/scripts/Dockerfile that is for `lllc`.

**Comment by SilentCicero** [comment]
Would recommend checking out Yul instead of LLLC as they will not continue to maintain that language going forward.

**Comment by yxliang01** [comment]
@SilentCicero Thanks for your comment. However, many current infrastructures(e.g. ethereum/aleth) are still depending on `lllc`. So, I would say it's still worth doing for the time being.

**Comment by chriseth** [comment]
Be warned that lll has always be unspecified and is not very well tested.

**Comment by axic** [comment]
Given our current plan is to sunset and remove lllc (see https://github.com/ethereum/solidity/issues/1230#issuecomment-559116361), I'd argue against creating a docker image.
