### ISSUE TITLE
z3 build failure: z3++.h not a directory

### ISSUE THREAD

**Issue by maurelian** [ethereum/solidity#6523]
## Description

I'm following the instructions on the [latest docs](https://solidity.readthedocs.io/en/develop/) to build from source with the SMTChecker. The build is failing with the following error:

```
[ 41%] Built target yul
Scanning dependencies of target solidity
[ 41%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ConstantEvaluator.cpp.o
cc1plus: error: /usr/include/z3++.h: not a directory [-Werror]
cc1plus: all warnings being treated as errors
libsolidity/CMakeFiles/solidity.dir/build.make:62: recipe for target 'libsolidity/CMakeFiles/solidity.dir/analysis/ConstantEvaluator.cpp.o' failed
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/analysis/ConstantEvaluator.cpp.o] Error 1
CMakeFiles/Makefile2:389: recipe for target 'libsolidity/CMakeFiles/solidity.dir/all' failed
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

## Environment

- Compiler version: `git checkout tags/v0.5.7`
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04.1 LTS

**Comment by maurelian** [comment]
Here's the full output of running `mkdir build`, `cd build`, and `cmake .. && make` https://gist.github.com/maurelian/d728873ad9590818352608797e7a4bb3

**Comment by axic** [comment]
What version of z3 you have installed and where?

**Comment by maurelian** [comment]
```
$ which -as z3
/home/primary/.pyenv/shims/z3
/usr/bin/z3

$ z3 --version
Z3 version 4.8.4 - 64 bit
```

That pyenv shim might be messing stuff up... though I can clearly still call z3 from the command line?

**Comment by maurelian** [comment]
That was it. 
Ensuring that `which z3` returns `/usr/bin/z3` solved my problem.
