### ISSUE TITLE
[Yul] optimizer takes too long on recursive function call within nested (potentially infinite) for loops

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6528]
## Description

(Found by LPM+libFuzzer)

For

```
{
  function foo(x, y) -> z
  {
    for {} x {}
    {
      for {} y {}
      {
        z := foo(x, y)
      }
    }
  }
  let a_0 := foo(calldataload(0),calldataload(32))
}
```

`solc` call to optimize does not finish computation for several minutes (I'm not sure if there is an infinite loop somewhere in the optimizer or if there is some computation that should return but takes too long)

Repro is:
```
$ solc --strict-assembly --optimize <code.yul>
```

Notes
  - While debugging this using `yulopti` fullInliner seemed to be one of the reasons for blowing up the AST size
  - RedundantAssignmentEliminator was seen to take too long to process intermediate ASTs
  - Bounded for loops do not trigger the bug for some reason (this tells me that there is something more than full inlining that causes the underlying problem)

## Environment

- Compiler version: latest develop

**Comment by chriseth** [comment]
The problem here is that the RedundantAssignEliminator has exponential behaviour with the nesting depth of functions. It is probably fine to degrade the efficiency of the RedundantAssignEliminator at a certain for loop nesting depth. The question is how to make it efficient but still correct at that depth.

**Comment by bshastry** [comment]
> It is probably fine to degrade the efficiency of the RedundantAssignEliminator at a certain for loop nesting depth.

Do you mean "at a certain function nesting depth" or "for loop nesting depth"? IIUC, the former is unbounded while the latter is 2 in this case?

Also, shouldn't the optimizer steps reach a fixed point at some point in cases like this where opt(n+1) = opt(n) and bail out at that point? Or is the exponential slowdown in the process of reaching such a fixed point?
