### ISSUE TITLE
[Yul] interpreter: function call before function definition inside for loop init block leads to an assertion failure because the function is not yet registered

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6532]
## Description

The following code snippet

```
{
  for{foo() function foo() {}} 0 {}
  {
  }
}
```

fails this assertion

https://github.com/ethereum/solidity/blob/6b12726f51c25840b3ccb231018fc37e994869e7/test/tools/yulInterpreter/Interpreter.cpp#L191

## Environment

- Compiler version: latest develop commit

## Steps to Reproduce

```
$ ./test/tools/yulrun --input-file <file.yul>
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<langutil::InternalCompilerError>'
  what():  
Aborted (core dumped)
```

**Comment by chriseth** [comment]
We should probably disallow function definitions in the pre block altogether. What do you think?

**Comment by bshastry** [comment]
> We should probably disallow function definitions in the pre block altogether. What do you think?

Sorry, forgot to respond. I agree.
