### ISSUE TITLE
Misleading error when trying to transfer funds > this.balance

### ISSUE THREAD

**Issue by eternauta1337** [ethereum/solidity#6535]
When executing the following code, assuming that `this.balance < msg.value`:

```
msg.sender.transfer(msg.value + 1);
```

The following error is thrown:

```
(revert)
The constructor should be payable if you send value.
```

This may lead developers to strange trains of thought: What constructor? The EOA's constructor (which doesn't make sense)? The sending contract's constructor? Does `msg.sender` need to be casted to `address payable`?

Such a misleading error is thrown whenever `transfer` is used with an amount that is larger than the current contract balance. In such a case, it is expected for the transaction to revert, but not with such an error.

Consider detecting this simple scenario and throwing a more appropriate error message.

The error can be reproduced in Remix with the following gist:
https://gist.github.com/ajsantander/718d3d9b05693a973651460e68d0fe41
(`remix.loadgist(718d3d9b05693a973651460e68d0fe41)`)
Deploy the contract and call it with some value > 0.

The error seems to occur with all versions of Solidity.

**Comment by chriseth** [comment]
This sounds like a bug in remix instead of Solidity.

**Comment by eternauta1337** [comment]
@chriseth indeed, seems like this is a Remix error. 

I tried reproducing the error using Truffle with no success. I just get a generic error:

```
Error: Returned error: VM Exception while processing transaction: revert
```

I will reach out to Remix with the bug. Please close it here.
Thx :tada:
