### ISSUE TITLE
[yul] break-continue statement design

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6541]
## Description

Is the following yul program supposed to be valid?

```
{
  for {{let x for {} x {} { break }}} 1 {} {}
}
```

The `break` is in the `for` loop body scope which itself is nested within a for loop init block.

**Comment by chriseth** [comment]
I think that's fine. `break` cannot be used in pre- or post-blocks, but if you have another for loop inside those blocks, it gets possible again in the body of that for loop.

**Comment by bshastry** [comment]
Okay, thanks. Note to self: we need a stack to track if we are in a loop body to decide if we can place a break/continue there.

**Comment by sifmelcara** [comment]
```
for {} 1 {}
{
  for {} 1 { if sload(0x1234) { break } }
  {
    ...
  }
}
```

So the `break` in the above example actually jumps out of the outer loop? For me it looks a little bit confusing, I would probably assume it jumps out of the inner loop at first glance.

**Comment by chriseth** [comment]
@sifmelcara no, break at that point is disallowed exactly because it might be confusing.

**Comment by bshastry** [comment]
@sifmelcara with latest solc, you get the following error for the code you mentioned

```
tmp_:4:33: Error: Keyword break outside for-loop body is not allowed.
  for {} 1 { if sload(0x1234) { break } }
                                ^---^
tmp_:6:5: Error: Literal, identifier or instruction expected.
    ...
    ^
```

**Comment by sifmelcara** [comment]
Oh you are right.

> Error: Keyword break outside for-loop body is not allowed.

Maybe we can improve this error message by changing it to "break inside for-loop post block is not allowed" or similar. Technically it is still in outer loop's for-loop body.

**Comment by bshastry** [comment]
@sifmelcara We can either issue a generic warning (that whitelists the use of break/continue) or a specific warning (that blacklists the specific use of break/continue)

Examples

### Whitelist

> Error: Keyword break is only permitted in the immediate scope of a for-loop body

### Blacklist

> Error: Keyword break in for-loop post block is not permitted

> Error: Keyword break in for-loop init block is not permitted

My 2 cents
