### ISSUE TITLE
[Yul] Arithmetic operations overflow checking

### ISSUE THREAD

**Issue by totoroXD** [ethereum/solidity#6551]
## Description

Does Yul specification define that arithmetic operation should check overflow?
According to Yul documentation, I only see overflow checking in type conversion functions.

https://github.com/ethereum/solidity/blob/bf43eebea95507f7930b9e5ea3f82d469f4a1498/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L81-L101

**Comment by chriseth** [comment]
The Solidity -> Yul translation is still work in progress and highly experimental. There is no specification.

Which Yul documentation do you refer to?

**Comment by totoroXD** [comment]
https://solidity.readthedocs.io/en/v0.5.6/yul.html

Is there any better document to see decided specifications?
I want to implement those arithmetic operations.

**Comment by leonardoalt** [comment]
@totoroXD in that case this would rather need to be in the Solidity spec, since it's Solidity compilation to Yul that is doing the overflow checks. The Yul operations themselves are still unchecked in that case.

**Comment by totoroXD** [comment]
@leonardoalt Yes, you are correct, and my question was misleading. This should only be implementation issue. Thanks.
In Solidity, overflow checking is specified by safemath; then I think this piece of code needs revision.
