### ISSUE TITLE
[SMTChecker] fails assertion _commonType->category() == Type::Category::Integer 

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6574]
```
pragma experimental SMTChecker;contract test {
    function f() public {
        ufixed a = uint64(1) + ufixed(2);
    }
}
//- ---
// Warning: pure
```

fails this assertion

https://github.com/ethereum/solidity/blob/eac0048176e5a38fe8fc9968d4578aa64ef1f599/libsolidity/formal/SMTChecker.cpp#L1084

**Comment by chriseth** [comment]
@bshastry on an unrelated note: Do you think filtering out comments would increase the efficiency of the fuzzer? Of course, comment parsing also needs to be tested.

**Comment by bshastry** [comment]
@chriseth Indeed, that makes sense

**Comment by bshastry** [comment]
Reopening because the following test case

```
pragma experimental SMTChecker;
contract C {
  fixed[] b;
  function f() internal { b[0] += 1; }
}
```

throws the same exception as in the original report

https://github.com/ethereum/solidity/blob/bf4ef7483c8f6c9f260d2bddda87fc275ae95101/libsolidity/formal/SMTEncoder.cpp#L1244

Please let me know if I should close and reopen a new issue instead.
