### ISSUE TITLE
allow inlining of constant constructor variables

### ISSUE THREAD

**Issue by rainbreak** [ethereum/solidity#6586]
Currently the constructor does not respect the `constant` keyword and occupies storage slots unnecessarily.

```
contract C {
    uint constant x;
    constructor(uint x_) public {
        x = x_;
    }
    function get() public view returns (uint) {
        return x;
    }
}
```

Here, the function `get` will sload `x` from the first storage slot. However `x` could have instead been inlined into the contract code, avoiding using up any slots and avoiding a relatively expensive sload. This would be important in contracts that use delegatecall and wish to avoid any runtime dependence on their own storage.

**Comment by chriseth** [comment]
This code does not compile for me and it actually should not occupy any storage slot. Is this intended as a bug report or a feature request?

**Comment by chriseth** [comment]
This might be a duplicate of https://github.com/ethereum/solidity/issues/3835

**Comment by rainbreak** [comment]
Sorry, yes this is a duplicate. Also of https://github.com/ethereum/solidity/issues/6561
