### ISSUE TITLE
[Yul] optimizer takes too long on recursive function call in switch case statement

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6590]
(Found by libFuzzer + LPM)

```
{
  let a_0, a_1, a_2, a_3
  function foo_0(x_0) -> x_1
  {
    for {} 1 {}
    {
        x_0 := x_0
        switch x_0
          case 1 {
            x_1 := foo_0(x_1)
          }
          default {
            break
          }
    }
  }
  a_0 := foo_0(calldataload(0))
  sstore(0, a_0)
}
```

Somewhat related to #6528 in that the recursive call happens within the scope of a for-loop body. Nonetheless, this input does not slow down the optimizer as much (about 10 seconds) as #6528 (which did not finish in over 20 minutes).

**Comment by chriseth** [comment]
I think the best thing to do here is to either tune the code size metric itself or change the inlining limit in the inliner. It might also be that the non-full inliner (which does not really use the metric) could be the cause of the problem here.

**Comment by chriseth** [comment]
I think the culprit is the code size metric for the full inliner, it does not really take for loops, switches and all that into account.
