### ISSUE TITLE
[Yul] create new exception class for excessive asm errors

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6592]
When AssemblyStack `parseAndAnalyze` API encounters too many (over 256) parsing errors, it throws a `FatalError` exception

https://github.com/ethereum/solidity/blob/eea425a3f6a9754066231f756c3bbd76c246acd4/liblangutil/ErrorReporter.cpp#L109-L115

This is indistinguishable from other `FatalError` throws e.g.,

https://github.com/ethereum/solidity/blob/eea425a3f6a9754066231f756c3bbd76c246acd4/libsolidity/analysis/TypeChecker.cpp#L1027-L1028

Problem: Fuzzing cannot discover truly fatal errors quickly because the `FatalError` due to excessive errors masks them.

Proposed solution: Create a custom Exception object for excessive errors only that can be caught by the fuzzer and not reported as a bug.

**Comment by chriseth** [comment]
FatalError should not be an error condition for the fuzzer, it just means that no further parsing will be done.

**Comment by chriseth** [comment]
Or is this about the protobuf based fuzzer?

**Comment by bshastry** [comment]
> FatalError should not be an error condition for the fuzzer, it just means that no further parsing will be done.

Does this mean we should be catching FatalErrors thrown by `parseAndAnalyze` in the fuzzing harnesses?

> Or is this about the protobuf based fuzzer?

No, this is about the non protobuf based fuzzers that may synthesize random junk on a regular basis, leading to too many parsing errors.

**Comment by chriseth** [comment]
Actually, that FatalError should not leak out of the assembly stack. I'll take a look.

**Comment by chriseth** [comment]
So you are right, it should be an error condition because it should not be leaked.

**Comment by bshastry** [comment]
Here's the current snippet of the Assembly stack API in question

https://github.com/ethereum/solidity/blob/b6bb3ae4821c1ae3c545a07819d8692b15eba6a7/libyul/AssemblyStack.cpp#L72-L84

Should we change it to something like?

```
bool AssemblyStack::parseAndAnalyze(std::string const& _sourceName, std::string const& _source)
{
       bool returnValue = false;
       try
       {
	  m_errors.clear();
   	  m_analysisSuccessful = false;
	  m_scanner = make_shared<Scanner>(CharStream(_source, _sourceName));
	  m_parserResult = ObjectParser(m_errorReporter, languageToDialect(m_language, m_evmVersion)).parse(m_scanner, false);
  	  if (!m_errorReporter.errors().empty())
	  	  returnValue = false;
          else
          {
	    solAssert(m_parserResult, "");
	    solAssert(m_parserResult->code, "");
	    returnValue = analyzeParsed();
          }
     }
     catch (FatalError const&)
     {
         returnValue = false;
     }
  return returnValue;
}
```

**Comment by chriseth** [comment]
Yep, I'm working on it already.
