### ISSUE TITLE
[ossfuzz] Nightly failure due to unparseable test log file

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6601]
## Description

The approach that we take to report a regression failure is to first run the fuzzer against the regression corpus logging its output in the process, and later parsing this log output for errors. The error itself is captured using a simple regular expression.

Problem: Sometimes the log may contain binary characters that are not parseable using a fixed encoding set (e.g., ascii, utf8, iso etc.). Because of this parsing fails.

Proposed solution: Treat the log file as a binary file and stringify unparseable binary characters. Since the regular expression is only concerned with the ascii portion of the log file, the error is correctly captured while at the same time parsing errors do not happen.

**Comment by leonardoalt** [comment]
Would it be possible to detect the encoding and parse correctly?

**Comment by bshastry** [comment]
It may complicate things further. I am not sure we should care about the encoding though because sometimes the fuzzer logs random bytes that may not be captured by a single encoding apriori. The log is essentially a text file which is (sometimes) polluted by random bytes written by the fuzzer
