### ISSUE TITLE
solidity 0.3.1 compile failed

### ISSUE THREAD

**Issue by SnBetter** [ethereum/solidity#6607]
## Description
Sorry for asking a outdated question. I have to compile solidity 0.3.1 beacuse of some reasons. But it is failed beacuse of without dependent repositories what I can't find. The error is like this:

sion@root:/home/dapp/nas/solc-versions/solc-library/solidity/build$ make
[  0%] Built target solidity_BuildInfo.h
Scanning dependencies of target evmasm
[  1%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o
In file included from /home/dapp/nas/solc-versions/solc-library/solidity/libevmasm/Assembly.cpp:22:0:
/home/dapp/nas/solc-versions/solc-library/solidity/libevmasm/Assembly.h:26:31: fatal error: libdevcore/Common.h: No such file or directory
compilation terminated.
libevmasm/CMakeFiles/evmasm.dir/build.make:62: recipe for target 'libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o' failed
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 1
CMakeFiles/Makefile2:127: recipe for target 'libevmasm/CMakeFiles/evmasm.dir/all' failed
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
 
And I checked this error, which  is caused by the missing libdevcore folder, But I can't find the libdevcore folder correspondding version0.3.1. I am appreciate that if anyone could help.

**Comment by chriseth** [comment]
I think back in those days we still used submodules. You might need https://github.com/ethereum/webthree-umbrella/ and other repositories.

**Comment by axic** [comment]
@SnBetter I assume you managed to compile it. Let us know if not.
