### ISSUE TITLE
[Yul] Optimize for loops with "true" condition

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6619]
A for loop whose condition is always true, whose body ends in a `break` statement and which does not contain any other `break` or `continue` statement can be simplified to its body without the `break` statement at the end.

**Comment by bshastry** [comment]
Won't optimizing

```
{
// Runs once 
for {} 1 {} {break}
}
```

to

```
{
// Runs forever
for {} 1 {} {}
}
```

be wrong?

**Comment by bshastry** [comment]
Ah, nevermind. I suppose you meant optimizing it to

```
{{}}
```

which is correct.

**Comment by chriseth** [comment]
Of course, pre also has to be empty.

**Comment by sifmelcara** [comment]
I think a theoretical solution could be to create an optimization phase called `StatementSimplificationRule`, that contains various simplification rules (by pattern matching statements then transform them), including:

1.
```
for { } <cond> { <statements-without-function-decl> }
{  <statements-without-break-continue> break }
```
->
```
if <cond> { <statements-without-break-continue> }
```
2.
```
if true { <body> }
```
->
```
{ <body> }
```
3. Bonus: `DeadCodeEliminator` can be expressed as single rule (prerequisite: function hoister):
```
{
<statements-A>
<terminating-statement>
<statements-without-func-decl>
}
```
->
```
{
<statements-A>
<terminating-statement>
}
```

**Comment by chriseth** [comment]
StructuralSimplifier already implements `2.`. I agree, the for loop simplification does not actually need to check the condition - the simplifications should be able to build on top of each other.

**Comment by chriseth** [comment]
And also yes: Having a pattern language would greatly help in writing down the rules concisely, but I fear that might be rather complicated to do...

**Comment by chriseth** [comment]
Also: `<statements-without-break-continue>` should be `<statements-without-break-continue-referring-to-the-current-loop>` or something like that ;)

**Comment by chriseth** [comment]
I think I'll create a new class that contains all elements of StructuralSimplifier that do not actually need the DataFlowAnalyzer.

**Comment by sifmelcara** [comment]
:+1:

Should keep in mind that if we first apply #6480 to the following code, then it cannot be simplified to `if` by #6719 anymore.
```
for {} add(x, add(y, z)) { mstore(1, 2) break }
```

Not sure what is the best way to deal with this. Maybe simply make #6719 a prerequisite of #6480 (i.e always apply #6719 before applying #6480) is enough?
