### ISSUE TITLE
[ossfuzz] speed up nightly CI

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6624]
## Description

The ossfuzz regression suite comprises a total of 92064 test inputs across 8 different fuzzers. At the moment, the nightly CI runs each of them in a single process sequentially. This can take over an hour, sometimes two.

To speed up, we would have to run tests in parallel across multiple processes.

**Comment by erak** [comment]
We also need to keep in mind that the external tests will be run nightly only very soon. So I think in general it's a good idea to split up all tasks into several jobs and let Circle do the parallelization.

**Comment by chriseth** [comment]
Can you explain again why the ossfuzz regression test input is so big?

**Comment by bshastry** [comment]
@chriseth The corpus contains a minimal set cover of all branches covered by test inputs. The minimal set cover across all fuzzers happens to require these many inputs. Moreover, as more code is added, the number of branches increases and so does the set cover.

What I do is fetch the fuzzer corpora from the google database from time to time and push the set cover to the solidity-fuzzing-repo.

**Comment by bshastry** [comment]
@erak Sounds good, happy to discuss further about how to best do the parallelization.
