### ISSUE TITLE
Cant All Transaction-Related Calls Be Reprogrammed To Return Boolean False When The Stack Limit Is Hit?

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/solidity#663]
Is there some reason that all Web3's and Solidity's built-in transaction-related calls like "send" etc cannot return boolean false if the stack limit is hit? Sorry if I'm missing something, I'm only an interpreted language programmer. It seems to me that idiot-proofing (not being rude, just lacking a better terminology) the entire Web3 / Solidity structure as much as possible is starting to look like a very feasible goal at this point in the game.

**Comment by chriseth** [comment]
It does return false.

**Comment by taoteh1221** [comment]
Sorry, thanks for clarifying. I read an article that seemed to suggest the need for checking the stack limit as opposed to relying on return false.
