### ISSUE TITLE
[CommonIO] readFile and issues management 

### ISSUE THREAD

**Issue by NicolaBernini** [ethereum/solidity#6643]
The File Reading Operation have 2 possible failure reasons

1) File does not exist 

https://github.com/ethereum/solidity/blob/develop/libdevcore/CommonIO.cpp#L49

2) File is empty 

https://github.com/ethereum/solidity/blob/develop/libdevcore/CommonIO.cpp#L55

both are managed just returning an empty (or better, default constructed return type) but would not it be better to raise an exception ? 

Maybe, it could be possible to build an immutable type moving the IO operation (and the related exceptions) in its constructor 

Alternatively, if exceptions are not an option it could be possible to rely on a Maybe Monad ( or Boost Optional in C++ terms :) ) for the return value to discriminate between valid and non valid values in a formal way (without relying on implicit semantic )

**Comment by chriseth** [comment]
Thanks for discovering that!
Throwing an exception is probably a good idea, yes. Of course, all call sites have to be checked if they properly check if the file exists before calling that function.

**Comment by Marenz** [comment]
If all call sites check if the file exists the exception would effectively become an assert because we assume it shouldn't happen? I don't understand the motivation for checking at call site if we throw an exception anyway.

**Comment by chriseth** [comment]
Yes, an assertion is probably better.

**Comment by Marenz** [comment]
My point was more to rely on the exception and handle it properly but we can fully go the other way, too ;)
i just figured it's code redundancy if every caller has to check?

**Comment by chriseth** [comment]
I mean the caller either has to check or be prepared for an exception to be thrown.
