### ISSUE TITLE
[Sol -> Yul]: Add tests for `require()` when used with a string literal

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#6651]
Depends on #6650

**Comment by Marenz** [comment]
@erak is it possible to test for the result `FAILURE` together with `string`? That's what a `require(false, "string")` would return

**Comment by Marenz** [comment]
@chriseth  says: evmc/evmone will support fail-reason strings

**Comment by chriseth** [comment]
Moving to 0.5.12 because of evmone.
