### ISSUE TITLE
[ossfuzz] refactor build system so that fuzzing test harnesses can be built locally

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6653]
## Abstract

At the moment, we rely on the ossfuzz build CI to check if fuzzers build correctly.

Problem: PRs that change fuzzer harness code need to wait until CI run completes to detect compilation issues.

## Motivation

Solution: Change the existing build structure such that harnesses could be built locally, and only the external dependency linkage is left to the ossfuzz build CI.

## Specification

TBD

## Backwards Compatibility

TBD

**Comment by bshastry** [comment]
I'm not sure how to implement this without having to pre-build the external dependencies
- libFuzzer
- libProtobufMutator

@chriseth would you be open to adding this to the list of external dependencies at the cost of increasing SLoC count and build time? The benefit, of course, is we don't have to wait for the ossfuzz CI to finish to know of compilation issues in fuzzer code.

**Comment by chriseth** [comment]
What about extracting the libfuzzer interface code to some point where at least build failures would be visible?

**Comment by bshastry** [comment]
@chriseth That sounds reasonable to me. One way to do that (in my mind) is that all `*_ossfuzz.cpp` files only contain a call to the test harness function that is defined in some utility source file.

```
int LLVMFuzzerTestOneInput()
{
  testHarness();
  return 0;
}
```

and 

```
// should compile without dependencies
FuzzerUtil::testHarness()
{
  ...
}
```

and then we split the ossfuzz build targets into those that depend on external deps and those that don't. Those that don't can then be added to the "default" solidity build. Those that depend on external deps are delegated to the ossfuzz build CI that we currently have.

@chriseth what do you think?

**Comment by chriseth** [comment]
Sounds good!
