### ISSUE TITLE
[ossfuzz] Flaky nightly CI failure

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6667]
## Description

The differential proto fuzzer is consistently failing in the nightly CI. This means that the nightly CI believes there is a difference in traces of unoptimized and optimized yul code.

The failure is seen for

```
{
mstore(1, exp(0xffffffffffffffffffffffffffffffff,exp(0xffffffffffffffffffffffffffffffff,add(1,1))))
}
```

OR

```
{
mstore(exp(0xffffffffffffffffffffffffffffffffffffff,not(1)), 1)
}
```

OR

```
{
mstore(exp(41,not(1)), 1)
}
```

but is not reproducible with clang-9 or clang-6. The CI uses clang-7.

## Environment

- Compiler version: latest develop

**Comment by bshastry** [comment]
For
```
{mstore(exp(3,not(1)), 1)}
```

```
Unoptimized trace
 MSTORE_AT_SIZE(0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab, 32) [0000000000000000000000000000000000000000000000000000000000000001]                                     

Optimized trace
MSTORE_AT_SIZE(0x8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e39, 32) [0000000000000000000000000000000000000000000000000000000000000001]
```

**Comment by bshastry** [comment]
It looks like this function inside the yul interpreter miscomputes the exponentiation

https://github.com/ethereum/solidity/blob/35677019a3216938b76acd6f3ab53899814f8790/test/tools/yulInterpreter/EVMInstructionInterpreter.cpp#L39-L51

Here's how the optimizer computes exponentiation

https://github.com/ethereum/solidity/blob/36c78baa41e283df3327fd01ff4f5f038c4681ee/libevmasm/RuleList.h#L71

**Comment by bshastry** [comment]
Not much progress on this. Have a feeling this may be a boost bug

Ubuntu distro | Boost version | Bug reproduces? |
------------------| --------------------| --------------------|
Bionic  | 1.65 | No |
Cosmic | 1.67 | Yes |
NA (source build) | 1.69 | No |

**Comment by bshastry** [comment]
Note to self: bug no longer reproduces when downgrading CI env from ubuntu cosmic (18.10 uses 1.67 boost) to ubuntu bionic (18.04 uses 1.65 boost).

- boost::multiprecision::powm seems to be bug free
- bug is potentially in one of the mp ops in the hand-written exponentiation function in the yul interpreter

**Comment by chriseth** [comment]
I think this is the change of behaviour from "undefined but buggy" to "defined" in the conversion to smaller type. I'll try to create a fix PR.

**Comment by chriseth** [comment]
PR is here: https://github.com/ethereum/solidity/pull/6680 - can you please check if it fixes the problem?

**Comment by bshastry** [comment]
@chriseth #6880 fixes the problem :)
