### ISSUE TITLE
Isoltest improvements

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#6669]
Came out of a discussion with @chriseth:
- Make `->` optional
- Allow functions to return `FAILURE` with an additional error message
- Add line numbers to parsing errors
- It should be possible to explicitly call functions that do not exist, without letting the test fail
- Ensure that all types can be encoded

**Comment by chriseth** [comment]
The system should detect whether the function you want to call does exist or not.

**Comment by christianparpart** [comment]
Additional TODOs we've noticed during extracting some more tests.
*  keccak256 impl missing
*  storageEmpty equivalent
*  custom Cpp code *replacement* (most likely by hard coding results)
*  custom Cpp code on range *replacement*
*  custom Cpp *replacement*
* (for test strings): support expected return literal "abc\0\xff__"
* Sending ether (e.g.: to the constructor()) must work for test: balance()

**Comment by chriseth** [comment]
I think everything except for the last two do not have to be implemented - the tests can just stay where they are.

**Comment by erak** [comment]
@christianparpart @chriseth Here's a list of PR's adding a lot of the requested features / fixes:
- [x] Make `->` optional: https://github.com/ethereum/solidity/pull/7094
- [x] Add line numbers to parsing errors: https://github.com/ethereum/solidity/pull/7092
- [x] Sending ether with `constructor(), 2 ether`: https://github.com/ethereum/solidity/pull/7093
- [x] Extended string literal support e.g. `"abc\0\xff__"`: https://github.com/ethereum/solidity/pull/7080
- [x] Ensure that all types can be encoded (or fallback): https://github.com/ethereum/solidity/pull/7052 and https://github.com/ethereum/solidity/pull/7091
- [x] Support revert messages: https://github.com/ethereum/solidity/pull/7095
