### ISSUE TITLE
delegatecall.value gives error about value only being available for payable functions.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#6671]
## Description
In the following code, the banana function will not compile, instead erroring with:
> Member "value" is only available for payable functions.

Note that the same method using `call` does not result in a compiler error
```solidity
pragma solidity 0.5.8;

contract Apple {
    function apple(address payable to, uint256 value, bytes calldata data) external returns (bool success, bytes memory result) {
        return to.call.value(value)(data);
    }
    function banana(address payable to, uint256 value, bytes calldata data) external returns (bool success, bytes memory result) {
        return to.delegatecall.value(value)(data); // ERROR
    }
}
```
```
browser/Untitled.sol:8:16: TypeError: Member "value" is only available for payable functions.
        return to.delegatecall.value(value)(data); // ERROR
               ^-------------------^
```

## Environment

- Compiler version: 0.5.8
- Target EVM version (as per compiler settings): default (remix)
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Windows 10 & Unknown (Remix)

## Steps to Reproduce
Try to compile the above code.

**Comment by Marenz** [comment]
I spoke with @ekpyron and from what we gather a `delegatecall` doesn't have a `value()` member and we couldn't even generate code for it. 

Did you maybe mean to use `gas()` instead?

**Comment by MicahZoltu** [comment]
No, gas was not what I intended.  Are delegate calls equivalent to internal calls where the `msg.sender` and `msg.value` are not changed when the call is made?

**Comment by MicahZoltu** [comment]
(for anyone following via email, I had a critical typo in previous comment, I meant to say "gas was not what I intended.  edited comment in GitHub)

**Comment by MicahZoltu** [comment]
Ah, it is like an internal solidity call.  From yellow paper:
> Message-call into this account with an alternative account’s code, but persisting the current values for sender and value.

**Comment by MicahZoltu** [comment]
I closed the issue, but realized the error message could be better.  Reopening so you all can decide if improving the error message is something worth doing.

**Comment by chriseth** [comment]
I agree, the error message could be better. Should be an easy task, though.
