### ISSUE TITLE
[Yul] proto fuzzer: Add support for object access functions

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6685]
## Abstract

This issue tracks support in the proto generator for object access functions, namely
  - datasize
  - dataoffset
  - datacopy

that are now implemented in the yul interpreter (see #6631 ) for the `strictAssemblyForEVMObjects` dialect.

Note to self
  - `strictAssemblyForEVMObjects` is a superset of `strictAssemblyForEVM` that was the fuzzing target previously.

**Comment by bshastry** [comment]
How can we generate meaningful datasize and dataoffset statements?

```
{
let x, y
let x := datasize("a")
}
```

```
$ solc --strict-assembly test.yul
Warning: Yul and its optimizer are still experimental. Please use the output with care.

======= <stdin> (EVM) =======

Pretty printed source:
object "object" {
    code {
        let x, y
        x := datasize("abs")
    }
}

Exception while assembling: /home/bhargava/work/github/solidity/libyul/backends/evm/EVMDialect.cpp(126): Throw in function {anonymous}::createBuiltins(langutil::EVMVersion, bool, bool)::<lambda(const yul::FunctionCall&, yul::AbstractAssembly&, yul::BuiltinContext&, std::function<void()>)>
Dynamic exception type: boost::exception_detail::clone_impl<yul::YulException>
std::exception::what: Could not find assembly object <abs>.
[dev::tag_comment*] = Could not find assembly object <abs>.
```

**Comment by chriseth** [comment]
There is an example at the end of https://solidity.readthedocs.io/en/develop/yul.html
Basically all elements of the objects have names that you can use as strings. Maybe best to just use a fixed template for now.

**Comment by bshastry** [comment]
Depends on #7276

**Comment by bshastry** [comment]
## Abstract

The yul proto fuzzer currently generates code like this

```
object "object0" {
  code {
    let y := dataoffset("object0");
  }
  object "object1" {
    code {
       let x := datasize("object1")
    }
  }
}
```

This issue tracks support for generalizing object access such that any object in scope may be referenced. As an example, it should also be possible to reference "object1" sub-object within "object0" code section.

## Motivation

TBD

## Specification

TBD

## Backwards Compatibility

TBD
