### ISSUE TITLE
Event overloading with dynamic arrays are encoded incorrectly

### ISSUE THREAD

**Issue by businessfriendlyusername** [ethereum/solidity#6695]
When overloading events that return arrays, some of the event parameters seem to go missing. Overloading and arrays seem to be mutually exclusive.

## Environment

- Compiler version: 0.5.6
- Target EVM version (as per compiler settings): unsure
- Framework/IDE (e.g. Truffle or Remix): bug is in both Truffle and Remix
- EVM execution environment / backend / blockchain client: ganache
- Operating system: ubuntu

## Steps to Reproduce

link to stackEx issue with code examples:

https://ethereum.stackexchange.com/questions/70394/is-there-an-issue-using-event-overloading-and-event-logs-that-contain-arrays/70403?noredirect=1#comment85289_70403

**Comment by leonardoalt** [comment]
Minimal example that has the buggy behavior:

```
contract C {
    event E(uint[] x);
    event E(uint x);
  
    function g() public {
        emit E(789);
    }
}
```
The emit issues
```
"from": "0xde6a66562c299052b1cfd24abc1dc639d429e1d6",
		"data": "0x0000000000000000000000000000000000000000000000000000000000000315",
		"topics": [
			"0x002ff0672f372fbe844b353429d4510ea5e43683af134c54f75f789ff57bc0c0"
		]
```
If you comment `event E(uint[] x);` it works.
If you use `ABIEncoderV2` it's also incorrect.
If you use `indexed` it's also incorrect.

This looks similar to https://github.com/ethereum/solidity/issues/4292

**Comment by leonardoalt** [comment]
@businessfriendlyusername thanks for the report!
If you don't mind I'll edit the title of the issue to be a bit more precise.

**Comment by leonardoalt** [comment]
Ok after an initial closer look I don't think it's related to #4292

**Comment by leonardoalt** [comment]
@businessfriendlyusername 
I used your original code
```
contract EventTest {
  event marketCreated(address[] virtualShareAddresses, address market, uint256 indexed endTime, string description, string extraInfo);//categorical
  event marketCreated(address[2] virtualShareAddresses, address market, uint256 indexed endTime, string description, string extraInfo);//binary
  event marketCreated(address[2] virtualShareAddresses, address market, uint256 indexed endTime, string description, string extraInfo, int256 _minPrice, int256 _maxPrice, uint256 _numTicks);//scalar


  function createYesNoMarket(
    uint256 _endTime,
    string memory _description,
    string memory _extraInfo
    ) public payable returns (bool) 

  {
    address[2] memory virtualShareAddresses;
    address newMarket = address(0);
    virtualShareAddresses[0] = address(1);
    virtualShareAddresses[1] = address(2);
    emit marketCreated(virtualShareAddresses, address(newMarket), _endTime, _description, _extraInfo);
    return true;
  }
}
```
Calling the function on Remix with arguments `123, "description", "extraInfo"` I get this:
```
[
	{
		"from": "0xcf804947e5c324c61c4f91c53fa8f14a20447aeb",
		"data": "0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000b6465736372697074696f6e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000096578747261496e666f0000000000000000000000000000000000000000000000",
		"topics": [
			"0x723cfaf3d6cd591c1439c0b9b08b74eaa46598df92bd434a707f33f48fa8bbd8",
			"0x000000000000000000000000000000000000000000000000000000000000007b"
		]
	}
]
```
Notice that the data is correct: `6578747261496e666f` = `extraInfo`.
If I comment the first event out and run with the same parameters the data is shown in a nicer way though.
I also checked the assembly output of the two versions (with and without the first event definition) and they looked the same.
So in the end I don't think this is a bug in the compiler.

**Comment by leonardoalt** [comment]
The real issue seems to be on Remix/Ethers:
https://github.com/ethereum/remix/issues/1125
