### ISSUE TITLE
[Sol->Yul] Unary operators

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#6708]
* [x] Int `++`
* [x] Int `--`
* [x] Int `~`
* [x] bool `!`
* [x] bool `~`
* [x] `delete`
* [x] int `+`
* [x] int `-`
* [ ] ...

**Comment by Marenz** [comment]
From what I can tell, `delete` seems pretty much implemented. Will close this.

**Comment by leonardoalt** [comment]
What about `...`?

**Comment by Marenz** [comment]
I added that at the time as "and any unary operator I didn't think of". I am sure anything I forgot will give us errors in the tests once we switch all..
