### ISSUE TITLE
Move ``YulUtilFunctions::suffixedVariableNameList`` to ``liblangutil``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6710]
There's nothing Yul-specific about ``YulUtilFunctions::suffixedVariableNameList``, so it should be moved to an appropriate (or possibly new) location in ``liblangutil``.

**Comment by ekpyron** [comment]
Note that in its current state #6664 links yul_proto_ossfuzz to libsolidity to be able to use ``suffixedVariableNameList``, so once it is moved we should check whether we can remove that again.

**Comment by djudjuu** [comment]
maybe ```libdevcore``` is more appropriate here, as it already has a ```StringUtils.h```?
