### ISSUE TITLE
Deployment gas estimation is incorrect.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#6724]
## Description
I have a contract that I compiled with `evm.gasEstimates` outputSelection`.  When I try to deploy that transaction, it fails due to out of gas.  If I ask the attached node to estimate gas for the deployment instead, I get a _much_ higher estimate.  The deployment in question does not have any init code, so the deployment should be a fixed cost (not dependent on blockchain state or inputs).

## Environment

- Compiler version: 0.5.8
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix/custom
- EVM execution environment / backend / blockchain client: go-ethereum
- Operating system: Windows 10

## Steps to Reproduce
With `optimizer: { enabled: true }`, the `evm.gasEstimates.creation.totalCost` is `29881`.  However, actually deploying costs `94541`.

```solidity
pragma solidity 0.5.8;

contract Apple {
	function exists() external pure returns (bytes32) {
		return 0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef;
	}
}
```

**Comment by chriseth** [comment]
It might be that the gas estimator does not include the data bytes.

**Comment by axic** [comment]
I'm not sure if this is solved, but we get the following estimates now:

With optimizer:
```
======= 6724.sol:Apple =======
Gas estimation:
construction:
   93 + 39000 = 39093
external:
   exists():    176
```

Without optimizer:
```
======= 6724.sol:Apple =======
Gas estimation:
construction:
   93 + 41200 = 41293
external:
   exists():    197
```

**Comment by MicahZoltu** [comment]
I just tested in Remix with Solidity version 0.6.7 and it appears to estimate correctly, though I think for most users they will lead to confusion

Solidity estimate (optimized):
```json
{
	"Creation": {
		"codeDepositCost": "31800",
		"executionCost": "81",
		"totalCost": "31881"
	},
	"External": {
		"exists()": "176"
	}
}
```
JavaScript EVM:
-- | --
transaction cost | 97157 gas
-- | --
execution cost | 31881 gas

I just did a refresher from https://ethereum.stackexchange.com/a/29560/704 and I'm not sure that it is reasonable for me (as a user) to convert from `execution cost` to `transaction cost` since it requires summing up the calldata bytes I believe.  Can we make the Solidity estimator estimate *transaction cost* as well as *execution cost*?  In almost all cases, transaction cost is what people will care about, since that is what needs to be under the block gas limit and it is what they will have to pay to deploy the contract.

**Comment by chriseth** [comment]
The reason we are not reporting the transaction cost is not just about the calldata cost but also about the fact that the function might be called from another contract. Oh and the transaction cost actually depends on the data sent to the contract because of the zeros :)

We can add transaction cost, though. Especially for the constructor this seems very useful.

**Comment by chriseth** [comment]
Created an issue for that: https://github.com/ethereum/solidity/issues/8920
