### ISSUE TITLE
[YulOpt] Common code motion

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6726]
Code that is common in all branches of the same control flow should be moved prior to the branch point. This might be especially interesting for loop invariant code motion, but could also be useful for if and switch statements.

Example, taken from the SolYul code gen:
```
let selector := shift_right_224_unsigned(calldataload(0))
switch selector
case 0x26121ff0
{
    if callvalue() { revert(0, 0) }
    fun_f_4()
    return(0, 0)
}
case 0xe2179b8e
{
    if callvalue() { revert(0, 0) }
    fun_g_5()
    return(0, 0)
}
default { revert(0, 0) }
```

The `callvalue` check can obviously be done before the switch: The `default` case does not have a callvalue check, but it does revert. This might be a tricky decision depending on the cost of the common code (it might even contain a revert itself!). In contracts in general, there will be payable and non-payable functions and those can be grouped: The switch can be split into one case that does not have the common code and the other case that has the common code:

```
switch x
case 1: ...
case 2: ...
case 3: ...
default {
  <common code>
  switch x
    case 4: ...
    case 5: ...
    case 6: ...
    default: ...
 }
```

**Comment by ekpyron** [comment]
Detecting common code in the branches might be achieved by something similar to the currently abandoned block outliner https://github.com/ethereum/solidity/pull/6720

**Comment by ekpyron** [comment]
The actual case of the current external function dispatch, unfortunately, no longer matches this...
I.e. for a simple contract with two payable functions, I get:
```
            // ...
            if iszero(lt(calldatasize(), 4))
            {
                let selector := shift_right_224_unsigned(calldataload(0))
                switch selector
                case 0x26121ff0
                {
                    // f()
                    if callvalue() { revert(0, 0) }
                    // ...
                    return(...)
                }
                case 0xe2179b8e
                {
                    // g()
                    if callvalue() { revert(0, 0) }
                    // ...
                    return(...)
                }

                default {}
            }
            if iszero(calldatasize()) {  }
            revert(0, 0)
```
After regular optimization, I end up with something like:
```
                if iszero(lt(calldatasize(), 4))
                {
                    let _1 := 0
                    switch shr(224, calldataload(_1))
                    case 0x26121ff0 {
                        if callvalue() { revert(_1, _1) }
                        // ...
                        return(....)
                    }
                    case 0xe2179b8e {
                        if callvalue() { revert(_1, _1) }
                        // ...
                        return(....)
                    }
                }
                revert(0, 0)
```

In order to move out the callvalue check, I need to be aware that the default case of the switch ultimately reverts... but in actuality this is not even a local property to the switch or even the block the switch is contained in!
And that doesn't even touch the problem that I'd need to make sure that ``revert(_1, _1)`` and ``revert(0, 0)`` is the same kind of revert (i.e. emits the same message)...
