### ISSUE TITLE
Commandline tests fail on Release version

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6747]
If the `prerelease.txt` file is present in the repository, the commandline tests fail due to differing metadata hash.

**Comment by ekpyron** [comment]
Weird - I did test that locally and it worked - I'll look into it!

**Comment by ekpyron** [comment]
My guess is that this wasn't related to ``prerelease.txt``, but rather to the tests added in #6606, which generally depended on metadata and failed because of that - locally for me there were no failures apart from these in the presence of ``prerelease.txt``.
