### ISSUE TITLE
Question about JSON outputSelection performance

### ISSUE THREAD

**Issue by cgewecke** [ethereum/solidity#6748]
If I pass a large number of contract sources to solc via JSON I/O but only specify a small number of these as compilation targets (listing them as  outputSelection keys), is that faster than compiling all sources (using `*` as an output selector)? 

Truffle has a profiler which uses this strategy to shorten compilation times but it  seems to perform like `compile all`.

### Reproduction
+ Install [colonyNetwork](https://github.com/JoinColony/colonyNetwork)
```
git clone https://github.com/JoinColony/colonyNetwork.git
cd colonyNetwork
yarn
git submodule update --init
```
+ Comment out `docker: true` in the truffle.js compilers config. (Truffle has a bug with solc docker at the moment causing compilation to hang)

+ Run `time npx truffle compile`, (compiling all contracts takes ~ 2 minutes)
+ Create a new file (Example.sol) in the contracts folder:
```solidity
pragma solidity >=0.5.3;

contract Example {
  constructor() public {}
}
```
+ Run `time npx truffle compile` again (will compile just Example since it's the only change)

The JSON I/O object [truffle passes to solc](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-compile/index.js#L119) for this last step it looks correct. All the sources in the contracts folder are present (so solc can resolve imports if it needs to) and Example is the only target.
```javascript
{
 "language": "Solidity",
 "sources": {
  "/Users/cgewecke/code/colonyNetwork/contracts/Colony.sol": {
   "content": "/*\n... 

     .... etc...  dozens of contracts
   "
  }
 },
 "settings": {
  "evmVersion": "petersburg",
  "optimizer": {
   "enabled": true,
   "runs": 200
  },
  "outputSelection": {
   "/Users/cgewecke/code/colonyNetwork/contracts/Example.sol": {
    "": [
     "legacyAST",
     "ast"
    ],
    "*": [
     "abi",
     "metadata",
     "evm.bytecode.object",
     "evm.bytecode.sourceMap",
     "evm.deployedBytecode.object",
     "evm.deployedBytecode.sourceMap",
     "userdoc",
     "devdoc"
    ]
   }
  }
 }
}
``` 

However compilation still takes two minutes and solc outputs a large number of warnings which suggest that the entire contract set is being processed.

### Environment
`solc version`: 0.5.6
`os`: OSX

**Comment by chriseth** [comment]
You are right, if you use `*`, then all contracts will be compiled, even if you specified only a single file. Thanks for bringing this to our attention!

**Comment by chriseth** [comment]
Note to implementer: The function should be `requestedContractNames` in `StandardCompiler.cpp`, but subsequently called functions could also be relevant.

**Comment by cgewecke** [comment]
@chriseth If I currently had 
```
"Example": [
     "abi",
     "metadata",
     "etc"
```
in the second layer of the outputSelection object would that make it behave the way I was hoping? 

Do I have to do something similar to:
```
"": [
     "legacyAST",
     "ast"
    ],
```
