### ISSUE TITLE
[RFC] Scope of Abiencoderv2 fuzzing

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6749]
## Description

Consider the following test program

```
contract C {
  struct S { uint16 u; int8 v; }
  bool[] x;
  uint16 y;
  S s;
  function f() returns (bool) {
    uint w = 3482374;
    x.length = 3;
    x[0] = true;
    x[1] = false;
    x[2] = true;
    y = 8;
    s.u = 7;
    s.v = -3;
    uint16[2] memory e;
    e[0] = 7;
    e[1] = 20;
    // Some of the arguments are read from the stack / from memory,
    // some from storage.
    (uint a1, uint16 b1, S memory c1, bool[] memory d1, uint16[2] memory e1) = this.g(w, y, s, x, e);
    if (a1 != w) return false;
    if (b1 != y) return false;
    if (c1.u != s.u) return false;
    if (c1.v != s.v) return false;
    if (d1.length != x.length) return false;
    if (d1[0] != x[0]) return false;
    if (d1[1] != x[1]) return false;
    if (d1[2] != x[2]) return false;
    if (e1[0] != e[0]) return false;
    if (e1[1] != e[1]) return false;
    return true;    
  }
  // TODO: We should also mix memory and calldata here.
  function g(uint a, uint16 b, S memory c, bool[] memory d, uint16[2] memory e) returns (uint, uint16, S memory, bool[] memory, uint16[2] memory) {
    return (a, b, c, d, e);
  }
}
```

For the initial fuzzing prototype, I would like to seek feedback on the scope of fuzzing:

Q1. What types (static and dynamic) are permitted?
Static types
  - [ ] signed and unsigned integers
  - [ ] boolean
~~- [ ] fixed point numbers~~
  - [ ] address and address payable types
  - [ ] fixed size bytes
  - [ ] Statically typed fixed-size arrays
  - [ ] Statically typed but dynamically-sized arrays

Dynamic types
  - [ ] structs
  - [ ] enums
  - [ ] Dynamically typed fixed-size arrays
  - [ ] Dynamically typed and sized arrays
  - [ ] Arrays of structs/enums

~~Mappings~~
~~- [ ] key type static value type dynamic~~
~~- [ ] key type static value type static~~
~~- [ ] key type dynamic value type dynamic~~
~~- [ ] key type dynamic value type static~~

Q2. What storage locations are permitted?
  - [ ] memory
  - [ ] storage
  - [ ] calldata (quick question: is calldata an explicit type?)

P.S. I am using [this](https://solidity.readthedocs.io/en/v0.5.8/types.html) as a reference for Solidity types.

**Comment by chriseth** [comment]
Fixed point numbers should be ignored.

Integers have different bit widths (all multiples of 8 between 8 and 256).

I don't think you should differentiate between static and dynamic that much. Arrays come in two flavours:

`<any type>[]` (dynamically-sized array)
`<any type>[k]` (statically-sized array)

Here, `<any type>` is really anything including arrays, structs, elementary types, ...

Same is true for structs, a struct member can be any other type. The only restriction is that you cannot use structs that contain themselves (not even via other structs). Another way to explain this is that if you expand the struct meaning that you name the member types directly and also recursively expand members if they are structs, the expansion has to be finite.

For mappings, only elementary types are supported as keys. This includes `string` and `bytes`, which are dynamically-sized arrays, but not other arrays. The value type can be anything including mappings, arrays, structs, ...

The storage location always applies to a full variable, i.e. you cannot have memory arrays that hold storage arrays or vice-versa. If a mapping occurs anywhere in the type, the whole variable has to be a storage variable and it can only be used in calls to libraries. So perhaps better to omit mappings for not.

Calldata is a storage location that is only relevant for the called function. To the calling function, these types appear as memory types.

**Comment by bshastry** [comment]
@chriseth some more questions about scope:

1. Do we limit the RHS of assignment statements (code above) to literals? Or does it make sense to introduce solidity expressions?

2. Can we limit all variable declarations to inside the scope of `f()` or should contract-wide declarations exist?

**Comment by chriseth** [comment]
Literals are fine, but of course you have to somehow "descend" into complex expressions.

Contract-wide variables are stored in storage, so we at least need some.

**Comment by bshastry** [comment]
> Literals are fine, but of course you have to somehow "descend" into complex expressions.

I'm not sure I understood this point. What do you mean by descending into complex expressions? Do you mean one may have to descend into "A" to initalize its members from "B" in the code snippet below? 

All leaf nodes are still literals, right? 

Also, while assigning literal values to typed variables are casts acceptable? (e.g., bool x = bool(-678))

```
Struct A {
  int8 a;
  bool b;
};

Struct B {
  A c;
};
```

**Comment by bshastry** [comment]
Just noticed #6754 . Do we add a contract constructor function to the scope of abi fuzzing as well?

**Comment by ekpyron** [comment]
Might be good to add constructors - they are pretty much untested so far (they should behave exactly the same, but there were multiple complaints recently, so I'm not so sure anymore).

**Comment by chriseth** [comment]
Yes, all leaf nodes can be initialized through literals, but you might have to construct several levels of arrays and structs to get to the leafs.

You cannot cast integers to bools. It probably makes sense to generate "typed literals". Remember that we do not want to test the construction of these values, that's also why we do not need expressions on the right hand sides.
