### ISSUE TITLE
[Doc] Mention that low-level calls do not have an extcodesize check

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6751]
High-level function calls first check that the called address has code by using `extcodesize`. This works around a peculiar detail of the EVM: Calls to contracts without code succeed silently instead of failing. For low-level calls (members of ``address``), this check is not present and that fact should be documented there.

**Comment by saurik** [comment]
FWIW, I was shocked to learn that this check was happening at all, as it violated my expectation of how the EVM would operate; I'd argue it is potentially even more important to document it on high-level function calls than low-level function calls, as it is a non-trivial amount of gas that is just being thrown away.

**Comment by chriseth** [comment]
Clarified it here: https://github.com/ethereum/solidity/pull/9847

**Comment by cameel** [comment]
We can close this now that #9847 has been merged, right?

EDIT: Ah, no. The PR only clarified the docs for high-level external calls, not low-level ones.
