### ISSUE TITLE
Documentation on best practices to not repeat the DAO hack

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#676]
Look, everyone has been talking about this, and everybody has different ideas for solutions so that Solidity can grow as a language. However, in the meantime, it is imperative that developers know the best practices, what caused this bug to happen, and what absolutely NOT to do. If someone would like to take this documentation challenge on, I'd be more than happy to review your work.

**Comment by redsquirrel** [comment]
I feel like re-writing or re-working the Solidity documentation should be one of the top priorities for the Ethereum community. I'm tempted to take this on.

**Comment by VoR0220** [comment]
Bring it Dave :) I could really use the hand right now. I think we all could.

**Comment by redsquirrel** [comment]
OK, now I've done it. I've applied for a DevGrant to create "A Tour of Solidity" inspired by https://tour.golang.org. God help us.

**Comment by tad88dev** [comment]
What's about Ethereum Security Layer (ESL) ?.

Your smart contract will be deploy with Normal Working Flow Rules (which were you defined). It keep smart contract working on it own role, avoid malicious attack.

- Every smart contract will be compile with Normal Working Flow Rules (NWFR).
- All access, call, execute...which weren't defined in NWFR will be Reject.
- ESL is a built-in layer of EVM.

**Comment by Denton-L** [comment]
I'm willing to help you out with that!

**Comment by VoR0220** [comment]
@Denton-L make it happen ma man. I know how much time you spend in the docs and was waiting for you to jump on here.

**Comment by redsquirrel** [comment]
@Denton-L Awesome. Can you email me? dave.hoover@gmail.com Let's work on the DevGrant proposal together.

**Comment by VoR0220** [comment]
I think this has been properly handled now. Closing.
