### ISSUE TITLE
[SMTChecker] Allocates over 2GB memory bringing down the fuzzer

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6761]
## Description

(Found by nightly CI)

Test input follows

```
pragma experimental SMTChecker;
contract A
{
	uint a;
	function f() public {
		if (a > 1)
		{
- 0;
			g();
	 - 0;
			g();
			for (a=1;a<2;a++) 	g();
				a = a - 1;
			g();
			a = a - 1;
			g(
	);	}
		else
			assert(a == 2);
	}
	function g() public {
		if (a > 0)a - 1;
 tx.gasprice - 0;
			g();
			for (a=0;a<2;a++) 	g();
			a - a - 0; - 1;
 tx.gasprice - 8;
			g();
			for (a=0;a<2;a++) now ;
			a = a -
 5;	assert(a == 0);

	assert(a == 0);
	}
}
//
```

takes over a minute to finish computation and consumes over 2GB memory.

## Environment

- Compiler version: latest develop

**Comment by leonardoalt** [comment]
That's weird, on my local `develop` it takes less than 4 seconds

**Comment by leonardoalt** [comment]
Which SMT solver/version is the fuzzer using?

**Comment by bshastry** [comment]
> Which SMT solver/version is the fuzzer using?

[CVC4 from bionic](https://packages.ubuntu.com/bionic/cvc4)

**Comment by bshastry** [comment]
Flaky: Not able to triage this

**Comment by leonardoalt** [comment]
@bshastry any news here? Can we close it?

**Comment by bshastry** [comment]
@leonardoalt haven't worked on this, will try to reproduce/close in the coming days.

**Comment by leonardoalt** [comment]
@bshastry ping

**Comment by bshastry** [comment]
Sorry this took so long. I am unable to reproduce this with Z3 version 4.8.7. I vote for closing this issue.
