### ISSUE TITLE
[Doc] Improve description of the semantics behind copying arrays

### ISSUE THREAD

**Issue by nventuro** [ethereum/solidity#6763]
As discussed on gitter [here](https://gitter.im/ethereum/solidity?at=5cd9bb7c0f381d0a76add441), the [current documentation](https://solidity.readthedocs.io/en/v0.5.8/control-structures.html?highlight=copy#complications-for-arrays-and-structs) on array copies doesn't go too deep into detail regarding copies of memory arrays, or conversion between array-like types (e.g. `bytes` and `string`).

In particular, I'm not sure about what the expected behaviour is in these two examples:

```solidity
function foo(string memory a) {
      bytes memory bytesA = bytes(a); // is bytesA a reference to the same underlying data?
}
```
```solidity
function bar() returns (string memory) {
       bytes memory tmp = new bytes(40);
       // do stuff on bytes
       return string(tmp); // does this return a copy or a reference? (i.e. is there a way to make this more efficient/less wasteful?)
}
```

**Comment by chriseth** [comment]
Conversions between `bytes` and `string` should mention that no copy is performed. Are assignments well enough clarified?

**Comment by nventuro** [comment]
No, I think the explanation is too terse, even if it may be technically correct: expanding on it a bit should help.

I have another specific question about it: the example states that `g(x)` does not modify state because it creates an independent copy of storage in memory. However, `g` expects a memory array, and is called with a storage array. According to this, shouldn't it be a reference?

>On the other hand, assigning to a local variable creates an independent copy *only* for elementary types, i.e. static types that fit into 32 bytes. If structs or arrays (including bytes and string) are assigned from a state variable to a local variable, the local variable holds a reference to the original state variable

An underlying issue might be that the documentation talks about `state` and `local` variables, but the language also has local `storage` pointers, `memory` variables, etc.

**Comment by chriseth** [comment]
Yep, the cited paragraph should be extended to e.g. `assigning to a local variable with the same data location`
