### ISSUE TITLE
Write a Separate Developer Guide

### ISSUE THREAD

**Issue by rocky** [ethereum/solidity#6769]
## Abstract

There is a bit of lore that developers working on the solidity compiler as well as developers working to interact with solc or the output (EVM, AST) produced by solc.

## Motivation

Some of the information that is in the single documentation is brief because it is felt that the the majority of users this is not of interest. 

However from the developer side information there is sometimes too brief. Therefore I think a _separate_ in-depth document is needed give detailed descriptions of things that are not mentioned (e.g. using ccache or environment setup for emacs/vim/vscode users) or that were once mentioned and now removed for brevity e.g. sourcemaps 

## Specification

- [ ] document  tools like isoltest, ossfuzz
- [ ] document types of AST nodes and fields inside (analogous to [Python's AST](https://docs.python.org/3/library/ast.html?highlight=ast))
- [ ] document environment setup (ccache, emacs/vim/vscode setup tricks)
- [ ] Move things out of main documentation that are more developer oriented
- [ ] documentation on sourcemaps. This was in a earlier documentation and the idea was so cool that it became the basis for how other MythX represents locations internally.
- [ ] how error recovery works (this is new/experimental),

**Comment by chriseth** [comment]
Sounds good! I would consider it unlikely for regular developers to get in contact with ossfuzz, though.

Ccache seems to be important to get documented, but I would say we cannot cover every environment setup out there.

**Comment by rocky** [comment]
> cover every environment setup out there.

Doing _something_ (however incomplete) is always preferable, in my opinion, is better than doing nothing.

**Comment by Meshugah** [comment]
Would this be bounty worthy?
