### ISSUE TITLE
[Compiler Utils] Could the stack too deep assertion be specialized?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6772]
## Description

```
contract C {    bytes32[6**96][][8*40][88444][544407][44][][8*40][884440][88444][544407][444][544407][440][88444][544409556][][8*40][88444][540][88444][544404][54844816][54844810948][5*14409556][][8*40][88444][540][88*40][88444][544404][54844816][548444][544404][54844816][54844810955] public s;
}
```

throws

https://github.com/ethereum/solidity/blob/66cea5abb6d7aa75a4cc397c7062182cf51a60af/libsolidity/codegen/CompilerUtils.cpp#L1232

Would it be possible to throw a more specialized exception here (and other similar places) that can be caught in the fuzzer harness?

## Environment

- Compiler version: latest develop

**Comment by chriseth** [comment]
StackTooDeep could be a sub-class of InternalCompilerError

**Comment by axic** [comment]
@bshastry is this still needed?

**Comment by bshastry** [comment]
@axic yes, this would be helpful. I will create a PR soon
