### ISSUE TITLE
Missing solc-static for 0.4.26

### ISSUE THREAD

**Issue by daanwa** [ethereum/solidity#6781]
## Description
The 0.4.26 release does not contain the ```solc-static-linux``` binary. 

Several of my scripts and apps depend on the ```solc-static-linux``` binary to be present on each release. Of course I can code around this, but for consistency it would be nice to have it include with the 0.4.26 release as well.

**Comment by chriseth** [comment]
We tried, but it proved quite hard to generate this artefact at this point in time.

**Comment by chriseth** [comment]
Please reopen if you have further questions or if it really badly hurts you... :)
