### ISSUE TITLE
Struct containing an array of mappings crash

### ISSUE THREAD

**Issue by dddejan** [ethereum/solidity#6783]
## Description

What happens: compiler crashes.

Expected: user-friendly error, or successful compile.
## Environment

- Compiler version: 0.5.5+commit.47a71e8f.Darwin.appleclang
- Operating system: MacOS 10.12.6

## Steps to Reproduce

```solidity
pragma solidity >=0.5.0;

contract StructsMappingArrays {

  struct A {
    mapping(int=>int)[] m;
  }

  A a1;

  function() external payable {
    A memory ma = A();
    a1.m.length = 3;
    a1 = ma;
    assert(a1.m.length == 3);
  }

}
```

Current output:
```
Internal compiler error during compilation:
/tmp/solidity-20190307-21448-1jpsebx/solidity_0.5.5/libsolidity/ast/Types.cpp(2232): Throw in function u256 dev::solidity::StructType::memoryOffsetOfMember(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Member not found in struct.
[dev::tag_comment*] = Member not found in struct.
```

**Comment by sifmelcara** [comment]
I think the actual problematic code here is `A()`. Am I right?

I can try to fix this issue

**Comment by chriseth** [comment]
Sure, please go ahead! I think the problem is that memory structs ignore members but the code generator nevertheless requests it at some point.
