### ISSUE TITLE
Some documentation problems

### ISSUE THREAD

**Issue by guylando** [ethereum/solidity#6784]
1.
The sentence "A modular approach to building your contracts helps you prevent overflow risks and unexpected tokens." in the following link is weird: https://solidity.readthedocs.io/en/v0.5.8/solidity-by-example.html#modular-contracts
I don't see how contract being modular is related to overflow risks or to "unexpected tokens".
And in general the whole "Modular Contracts" section in that page seems out of place and unclear why it was inserted in that specific page and it does not provide enough explanations.

2. 
`uint32 x = f(); assembly { x := and(x, 0xffffffff) /* now use x */ }` seems wrong, I think it was supposed to be `and(x, 0x000000000)`
https://solidity.readthedocs.io/en/v0.5.8/assembly.html#access-to-external-variables-functions-and-libraries

3.
In https://solidity.readthedocs.io/en/v0.5.8/contracts.html#getter-functions it says in the end of the section "The mapping in the struct is omitted because there is no good way to provide the key for the mapping". But why isn't the following code a way to provide the key for the mapping:
`data[arg1][arg2][arg3].map[arg4]`? for an additional uint arg4 parameter in the function

4.
In https://solidity.readthedocs.io/en/v0.5.8/contracts.html#fallback-function , the "A contract without a payable fallback function can receive Ether.." warning states two ways a contract without fallback function could have received ether. It is missing the third way: pre-funded contract which was sent ether by calculating its address before its creation

**Comment by chriseth** [comment]
1) You are right, it reads weird, we will try to clean it up.

2) The code is correct - how do you expect it works?

3) There is no good way to provide the key as an argument to the function `data`. There of course is a way, but it is not good.

4) We can add that, but strictly, it is not "receiving" ;) Note that a contract can receive ether at its point of creation if the constructor is payable, so that is unrelated to the fallback function being payable or not.

**Comment by guylando** [comment]
2.
If that code is supposed to clear a variable by setting it to 0 then that would be achieved by a binary AND with 0 and not with ones (0xffffffff). The AND with 0xffffffff would have no effect I expect.
3.
The statement is confusing because it points to:
```
function data(uint arg1, bool arg2, uint arg3) public returns (uint a, bytes3 b) {
    a = data[arg1][arg2][arg3].a;
    b = data[arg1][arg2][arg3].b;
}
```
and here there is no problem providing the key:
```
function data(uint arg1, bool arg2, uint arg3, uint arg4) public returns (uint a, bytes3 b, Data c) {
    a = data[arg1][arg2][arg3].a;
    b = data[arg1][arg2][arg3].b;
    c = data[arg1][arg2][arg3].map[arg4];
}
```
4.
Those two ways were presented as an argument to: "It also means that address(this).balance can be higher than the sum of some manual accounting implemented in a contract" so the reader might think those are the only two ways to achieve what is written in the statement.

**Comment by chriseth** [comment]
2) ah! It should probably read `clean` instead of `clear`.

**Comment by guylando** [comment]
@chriseth 2. Isn't doing an AND with 0xffffffff is a NOP and has no effect at all? how is that considered as "clean"? I think I am missing something here.
UPDATE: You mean it cleans (sets to 0) the bits which exist in uint256 and not in uint32 (in that example)?

**Comment by chriseth** [comment]
@guylando Solidity creates code to run on the EVM which is a 256 bit machine. Because of that, a `uint64` is still stored in a 256 bit word and `0xffffffff` does not have all the bits set.

**Comment by guylando** [comment]
I see, well I think maybe adding in the end something like ("Note that 0xffffffff has 32 bits set to 1 and other bits set to 0 and that is why a binary AND with 0xffffffff sets all the top 224 bits to 0") would make it clearer unless you think this should be obvious to the reader. This would serve as another "thing to remember" for the reader (2 birds with one stone).

**Comment by chriseth** [comment]
Yep, I think it makes sense to explain what "cleaning" means.

**Comment by guylando** [comment]
5.
The paragraph 
```
It is possible to request a simple payment verification (SPV) for logs, so if an external entity supplies a contract with such a verification, it can check that the log actually exists inside the blockchain. You have to supply block headers because the contract can only see the last 256 block hashes.
```
in https://solidity.readthedocs.io/en/v0.5.8/contracts.html#events is unclear.
Searching google for "solidity log spv" gave no clue on this paragraph statement and on how to utilize this log verification or how it is related to blockhash.
The only related thing was https://ethereum.stackexchange.com/questions/46726/ethereum-account-model-spv-proofs-possible but it spoke about light client implementation and the connection between this and the contract logs is unclear.
