### ISSUE TITLE
Documentation of default values of data types when variable is initialized

### ISSUE THREAD

**Issue by mabeebam** [ethereum/solidity#679]
Where are default values of data types when variable is initialized documented?
To what default value will `uint myvar;` be initializing? I guess 0 but can I be sure?
I could only find: "In addition to this, if a variable is declared, it will be initialized at the beginning of the function to its default value."
https://github.com/ethereum/solidity/blob/b23c30079283095e54eb9678a88dda95d895dd6e/docs/control-structures.rst#L193

I guess the default values should be clarified somewhere.

**Comment by Denton-L** [comment]
On it.
