### ISSUE TITLE
Internal error when compiling with --ir flag

### ISSUE THREAD

**Issue by jakelang** [ethereum/solidity#6797]
## Description
`solc` seems to crash on the following contract when set to output IR.

## Environment
- Compiler version: 0.5.8 (downloaded from releases)
- Target EVM version (as per compiler settings): EVM (no flag provided)
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: `Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux`

#### Source
test.sol

```
pragma solidity >=0.4.0 <0.7.0;

contract SimpleStorage {
    uint storedData;

    function set(uint x) public {
        storedData = x;
    }

    function get() public view returns (uint) {
        return storedData;
    }
}
```
#### Command 
` ./solc test.sol --ir`
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ir/IRGenerationContext.cpp(47): Throw in function std::__cxx11::string dev::solidity::IRGenerationContext::variableName(const dev::solidity::VariableDeclaration&)
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Unknown variable: storedData
[dev::tag_comment*] = Unknown variable: storedData
```

**Comment by chriseth** [comment]
Thatks for reporting! Until we have fully implemented the new code generator, these errors are to be expected. You might be more lucky with the development version of the compiler.

**Comment by chriseth** [comment]
Also, if you have any suggestions which parts of the language to implement next, please talk to us!
