### ISSUE TITLE
[Testing] Discussion on runtime ASan flags

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6813]
## Description

Currently, we do not use several ASan features for CI-based testing. Some of these (disabled by default) may be useful.

To enable, we will need to export the `ASAN_OPTIONS` variable like so
```
export ASAN_OPTIONS="check_initialization_order=1:detect_stack_use_after_return=1"
```

Each `option=value` is colon separated.

| Runtime flag | Default | Description 
|------------------|------------|----------------
| check_initialization_order | false | If set, attempts to catch initialization order issues.
| detect_stack_use_after_return | false | Enables stack-use-after-return checking at run-time.
|strict_init_order | false | If true, assume that dynamic initializers can never access globals from other modules, even if the latter are already initialized.
| strict_string_checks | false | If true, check that string arguments are properly null-terminated.
| detect_invalid_pointer_pairs | 0 | If non-zero, try to detect operations like <, <=, >, >= and - on invalid pointer pairs (e.g. when pointers belong to different objects). The bigger the value the harder we try.

Full reference: https://github.com/google/sanitizers/wiki/AddressSanitizerFlags#run-time-flags

**Comment by chriseth** [comment]
They all sound useful!
