### ISSUE TITLE
Disable access to uninitialized array in memory

### ISSUE THREAD

**Issue by scucchiero** [ethereum/solidity#6821]
## Description
Attempting to assign to any slot in an uninitialized dynamic array in memory **is not detected by the compiler.**

**This could be potentially used in a honeypot as it looks like legit code and it actually compiles and can be deployed in the blockchain.**

## Environment

- Compiler version: **0.5.8**
- Target EVM version: **default**
- Framework/IDE (e.g. Truffle or Remix): **Remix**
- EVM execution environment / backend / blockchain client: **geth**/**ropsten**/**ganache**

## Steps to Reproduce
The following contract is subject of this bug.
```solidity
pragma solidity >=0.5.8;

contract Test {
    
    function foo() public pure returns (uint256[] memory) {
        //uninitialized memory array
        uint256[] memory arr;
        //assignation to array slot
        arr[3] = 4;
        return arr;
    }
}
```
The execution throws **"error invalid opcode"** as it is trying to access the array out of its bounds. Before initialization, an array's length is 0.

**Comment by chriseth** [comment]
Thanks for opening this issue!

If I understand you correctly, you propose to change the detection of this error condition from runtime to compile-time, right? There are several other error conditions that occur at runtime which we do not detect at compile-time. These include division by zero, modulo by zero, call to an invalid contract, and others.

While in your example it seems like the error would be easy to detect at compile-time, it is not very useful to implement this only for the simple cases. Wit the SMTChecker component, we are working on a feature that would be far more useful than just detecting this simple programming error.

Finally, there are several tools available that can be applied to the bytecode of this smart contract and which would immediately tell you that the function foo will never successfully return.

Please reopen if I misunderstood something or you have further suggestions.
