### ISSUE TITLE
selfdestruct is not working on specific case (e.g. nested library call)

### ISSUE THREAD

**Issue by EcmaXp** [ethereum/solidity#6823]
## Description
Calling selfdestruct is not working well when contract referencing nested library more then 2 level.

## Environment
- Compiler version: version:0.5.8+commit.23d335f2.Emscripten.clang
- Target EVM version (as per compiler settings): compiler default (No optimization)
- Framework/IDE (e.g. Truffle or Remix): remix
- EVM execution environment / backend / blockchain client: remix / mainnet
- Operating system: Windows 10

## Steps to Reproduce
1. Create contract with below code

```
pragma solidity ^0.5.0;

library Hive1 {
    function func() public { }
}

library Hive2 {
    function func() public {
        Hive1.func();
    }
}

contract Bee {
    function func() public {
        Hive2.func();
    }

    function die() public {
        selfdestruct(msg.sender);
    }
}
```

2. Calling Bee.die() does not working well (transaction reverted)

- Contract: https://etherscan.io/address/0xb03e9255f4aff415f458a399eb22d965ee5fd729
- Calling Bee.die(): https://etherscan.io/tx/0x86a10cb649d692faa99b81428c94b5c1fcb42f3374fe81a5f929326aeaf935ce (reverted)

**Comment by chriseth** [comment]
From the call trace in Etherscan, it looks like you called the `die` function on the `Hive1` library instead of the `Bee` contract. Can you please check if that is the case?

**Comment by EcmaXp** [comment]
@chriseth I think it's bug of remix IDE. I'll close the issue.

**Comment by EcmaXp** [comment]
This issue moved to https://github.com/ethereum/remix/issues/1199
