### ISSUE TITLE
[Yul] Helper function to create special numbers

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6828]
We have a lot of code that uses expressions like `(u256(1) << _bits) - 1`. There should be helper functions to generate the largest and smallest numbers of the various signed and unsigned types.

**Comment by axic** [comment]
Is this is a code-generator feature or a language feature? Are talking about introducing min/max basically for types? (#8484)

**Comment by chriseth** [comment]
No, this is about internal functions for yul codegen. I'll close it.
