### ISSUE TITLE
Contract Not Storing Data

### ISSUE THREAD

**Issue by geekybcresearcher** [ethereum/solidity#6832]
## Description
Deployed Contract is not storing the data passed while processing a transaction on compiling the code with specific versions of Solidity. Below listed are the steps perform

## Steps Performed
1. Developed a very basic contract to store greetings data

**Contract Code**
`pragma solidity ^0.5.8;contract GreetContract {    string message;        event LogGreetAdded(address indexed fromAddress, string description, string message);            function setMsg(string memory _msg) public {        emit LogGreetAdded(msg.sender, "This is the log for message",message);        message = _msg;    }        function getMsg() public view returns(string memory _msg){        return message;    }    }`

2. Generated the ABI and Bytecode using Remix
3. Started a geth instance
Geth/v1.9.0-unstable/windows-amd64/go1.10.3

`geth --mine --minerthreads=1 --datadir D:/Ethereum/Repo/Ethereum/Data/Node-0 --networkid 9890 --nodiscover --rpc --rpcport "8001" --port "9001" --rpccorsdomain "*" --nat "any" --rpcapi eth,web3,personal,net,miner --rpcaddr 0.0.0.0 --ws --wsport 7001 --wsorigins '*' --wsapi personal,admin,db,eth,net,web3,miner,shh,txpool,debug --verbosity 2 console`

3. Using below code deployed the contract on Geth instance
```
var greetBytecode = '0x608060405234801561001057600080fd5b50610410806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b5fdeb231461003b578063c4784fd4146100be575b600080fd5b610043610179565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610083578082015181840152602081019050610068565b50505050905090810190601f1680156100b05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b610177600480360360208110156100d457600080fd5b81019080803590602001906401000000008111156100f157600080fd5b82018360208201111561010357600080fd5b8035906020019184600183028401116401000000008311171561012557600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061021b565b005b606060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102115780601f106101e657610100808354040283529160200191610211565b820191906000526020600020905b8154815290600101906020018083116101f457829003601f168201915b5050505050905090565b3373ffffffffffffffffffffffffffffffffffffffff167f2003865f11897ce96fcccf77bdc9cd7b74d8d98b8e79bbe195264c40c407125160006040518080602001806020018381038352601b8152602001807f5468697320697320746865206c6f6720666f72206d65737361676500000000008152506020018381038252848181546001816001161561010002031660029004815260200191508054600181600116156101000203166002900480156103165780601f106102eb57610100808354040283529160200191610316565b820191906000526020600020905b8154815290600101906020018083116102f957829003601f168201915b5050935050505060405180910390a2806000908051906020019061033b92919061033f565b5050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061038057805160ff19168380011785556103ae565b828001600101855582156103ae579182015b828111156103ad578251825591602001919060010190610392565b5b5090506103bb91906103bf565b5090565b6103e191905b808211156103dd5760008160009055506001016103c5565b5090565b9056fea165627a7a72305820275c12ca3f55b8869cf3bbdc9f139dbe2e924464f0a12cdb8e6d83db4851628a0029'
var greetLatestContract = eth.contract([	{		"constant": true,		"inputs": [],		"name": "getMsg",		"outputs": [			{				"name": "_msg",				"type": "string"			}		],		"payable": false,		"stateMutability": "view",		"type": "function"	},	{		"constant": false,		"inputs": [			{				"name": "_msg",				"type": "string"			}		],		"name": "setMsg",		"outputs": [],		"payable": false,		"stateMutability": "nonpayable",		"type": "function"	},	{		"anonymous": false,		"inputs": [			{				"indexed": true,				"name": "fromAddress",				"type": "address"			},			{				"indexed": false,				"name": "description",				"type": "string"			},			{				"indexed": false,				"name": "message",				"type": "string"			}		],		"name": "LogGreetAdded",		"type": "event"	}])

var greetDeploy = {from:eth.coinbase, data:greetBytecode, gas: 2000000}

var greetContractInstance = greetLatestContract.new(greetDeploy)

greetContractInstance.setMsg('Hi Everyone', {from: eth.coinbase, gas: 400000})

greetContractInstance.getMsg()
```

4. Here are the results faced on executing using different compiler versions

**Compiler version**: 
- 0.5.8 - Not Working (Transaction hash returned but null message returned)
- 0.5.6 - Not Working (Transaction hash returned but null message returned)
- 0.5.5 - Not Working (Transaction hash returned but null message returned)
- 0.5.4 - Working (Transaction hash returned and message is also fetched)
- 0.5.3 - Working (Transaction hash returned and message is also fetched)
- 0.5.2 - Working (Transaction hash returned and message is also fetched)
Note: for below versions the contract signatures were modified to support the version. Like the "view" keyword was replaced with "constant"
- 0.4.26 - Working (Transaction hash returned and message is also fetched)
- 0.4.9 - Working (Transaction hash returned and message is also fetched)
- 0.4.8 - Working (Transaction hash returned and message is also fetched)
- Operating system: Windows 10 Enterprise

**Comment by chriseth** [comment]
This is most likely caused by an outdated EVM version. Since 0.5.5, Solidity generates Istanbul-compatible code including shift instructions, which are interpreted as invalid instructions on pre-istanbul EVMs. I cannot tell you why geth would not use that as a default, though...

**Comment by chriseth** [comment]
Please reopen if you have further questions.
