### ISSUE TITLE
[DOCS] Change instances of "exception"

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#6839]
We know try to refer to "exception" in a different way, preferring "revert" or "failing assertion". The issue is to track making those changes where relevant.

As discussed here https://github.com/ethereum/solidity/pull/6567#discussion_r286908561

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
