### ISSUE TITLE
Simple solidity contract, issue with libraries

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#684]
I'm having trouble getting a library to work.  I have run the `linker` to ensure the library address is in the calling contract.  And I have thoroughly read the doco here: http://solidity.readthedocs.io/en/latest/contracts.html#libraries

It compiles fine, but fails during the deploy (due to the library call in the constructor)

From what I understand it should be possible to call library contracts like this.  But the contract fails to deploy (TxReceipt shows all gas used)

I'm compiling on Windows using latest solc, deploying to geth on osx on a private chain.

```
library MyLib {
    function init() {
        log0("Init success");
    }
}

contract MyContract {
    function MyContract() {
        MyLib.init();
    }
}
```

**Comment by slothbag** [comment]
I just tried some of the examples at solidity.readthedocs.io.. 2 wont compile, the 2 that did compile throw errors in geth.. Is there something broken with libraries at the moment?

**Comment by redsquirrel** [comment]
> 2 wont compile, the 2 that did compile throw errors in geth

**Comment by redsquirrel** [comment]
> 2 wont compile, the 2 that did compile throw errors in geth

**Comment by redsquirrel** [comment]
> I have run the linker to ensure the library address is in the calling contract.

So you're deploying the `MyLib` library first? Then getting its address and linking it into `MyContract`'s bytecode?

> 2 wont compile, the 2 that did compile throw errors in geth

Can you show which ones aren't compiling? Can you show the errors?

**Comment by slothbag** [comment]
Yup, deploy MyLib first, grab the address and run `solc test.sol --libraries MyLib:0x1234` and have confirmed that 0x1234 exists in the .bin file

I also just copy & paste the address manually into the bin, same issue.

**Comment by slothbag** [comment]
I'm running this on a private testnet at block 500.. do libraries and the more recent delegatecall work on private chains?

**Comment by slothbag** [comment]
The 4 examples under `Libraries` and `Using For` http://solidity.readthedocs.io/en/latest/contracts.html?highlight=libraries#libraries produce the following errors:

**Libraries**
Example 1

```
test.sol:39:5: Error: Identifier not found or not unique.
    Set.Data knownValues;
    ^------^
```

Example 2:

```
test.sol:47:17: Error: Undeclared identifier.
        var x = bigint.fromUint(7);
                ^----^
```

**Using For**
Example 3: Compiles, deploys but throws when calling register()

Example 4: 

```
test.sol:4:35: Error: Different number of arguments in return statement than in returns declaration.
            if (self[i] == value) return i;
                                  ^------^
test.sol:5:9: Error: Different number of arguments in return statement than in returns declaration.
        return uint(-1);
        ^-------------^
test.sol:20:22: Error: Member "find" not found or not visible after argument-dependent lookup in uint256[] storage ref
        uint index = data.find(_old);
                     ^-------^
```

**Comment by redsquirrel** [comment]
I believe your problem is that geth thinks that it's pre-Homestead. There are a lot of checks in geth for whether it has reached the Homestead block, and I assume some of those checks enable/disable the latest support for libraries. You can configure your private blockchain's `homesteadBlock` in its genesis block like this: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options#init

**Comment by slothbag** [comment]
Ahh great, yeah I thought that it might be something like that.. i'll give that a try

**Comment by slothbag** [comment]
Thats it. Thanks heaps!

**Comment by redsquirrel** [comment]
Regarding the compilation problems, I confirmed via [browser-solidity](https://ethereum.github.io/browser-solidity/) that examples 2 and 4 do not compile. I'm fixing the documentation. Thanks for pointing that out.
