### ISSUE TITLE
[Sol -> Yul] Arrays

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#6842]
* [x] array new
* [x] index access
* *  [x] storage
* * * [x] Adjust IRStorageItem & dependencies to work with dynamic offsets
 * [x] memory
* [x] delete array
* * [x] set to zero
* [x] convert from/to ptr/non-ptr

**Comment by Marenz** [comment]
## Notes
### Index Access & Storage Item
To implement index access the IRStortageItem class its dependencies need to be changed to take a dynamic offset (a string) instead of the current `unsigned` type.
Existing hard-offset functions should stay and dynamic versions should be added so that the abi decoder doesn't have to change.

### setZero
setZero can be implemented in more simpler terms than the current evm code: We will simply push the zero value prepared by the YulUtil function and let LValue `storeValue` do the work

**Comment by axic** [comment]
@Marenz what is left here?

**Comment by Marenz** [comment]
I just checked the remaining unchecked points and it seems they all work

**Comment by Marenz** [comment]
I've added a few more tests in #9347 to validate it
