### ISSUE TITLE
Modify modifier behaviour: "return" should be similar to "break"

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#686]
Currently, a `return` inside a function body (or more deeply nested modifier) ignores the trailing statements in a modifier with the justification that modifiers are pure syntactic modifications.

This leads to the effect that trailing statements are practically useless because they fact whether they are executed or not depends on whether the control flow exited the function via a `return` or just via flowing past the end of the function body.

Because of that and to allow "cleanup operations", if the control flow leaves a function or more deeply nested modifier, it should always continue right after the `_`.

I am currently not aware of any real-world usage of modifiers that would get broken by this change. Please speak up if you think otherwise. :-)

**Comment by nmushegian** [comment]
related (dupe?) https://github.com/ethereum/solidity/issues/49

**Comment by chriseth** [comment]
@nmushegian related, but not a duplicate
