### ISSUE TITLE
can't build on ubuntu 19 disco

### ISSUE THREAD

**Issue by mastereuclid** [ethereum/solidity#6861]
## Description
build fails with a bunch of undefined reference to 'boost::filesystem::path::remove_filename() or
CMakeFiles/solc.dir/CommandLineInterface.cpp.o:CommandLineInterface.cpp:function dev::solidity::CommandLineInterface::parseArguments(int, char**): error: undefined reference to 'boost::program_options::options_description::m_default_line_length'

I cloned the repo, ran the dependencies script, made a build dir, cmake .., make and it fails on linking
[ 57%] Linking CXX executable solc
## Environment

- Compiler version: gcc 8.3.0 or clang++-8 (not sure which one cmake choose)
ld GNU ld (GNU Binutils for Ubuntu) 2.32
boost 1.70.0
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:
ubuntu 19 disco dingo

Any suggestions appreciated.

**Comment by bshastry** [comment]
Hello,

Thanks for your report. It looks like you may not have installed prerequisites required for building solidity from source that are listed here

https://solidity.readthedocs.io/en/latest/installing-solidity.html#prerequisites-all-operating-systems

**Comment by chriseth** [comment]
I am able to build solidity using the following dockerfile:
```
FROM ubuntu:disco

RUN apt update
RUN apt -y install git wget cmake libboost-all-dev g++
RUN git clone https://github.com/ethereum/solidity.git
RUN cd solidity
RUN mkdir solidity/build
RUN cd solidity/build && cmake .. && make solc
```

Can you somehow tell which version of boost you are using?

**Comment by bshastry** [comment]
Sorry, didn't pay attention to "ran the dependencies script" in the original post.

FWIW, the officially supported version of boost (via the libboost-dev-all package) is 1.67.0.1

https://packages.ubuntu.com/disco/libboost-all-dev

**Comment by mastereuclid** [comment]
ok, I probably didn't build and install boost from sources properly. I removed 1.70 re-ran cmake it found the system package version and it built successfully. Thanks for the help!
