### ISSUE TITLE
[yul] optimizer takes several minutes on nested function calls

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6866]
## Description

```
{
let a_0, a_1, a_2, a_3
function foo_noreturn_0()
{
let x_0
extcodecopy(foo_singlereturn_0(foo_singlereturn_0(foo_singlereturn_0(foo_singlereturn_0(1, foo_singlereturn_0(foo_singlereturn_0(codesize(), 1, 1, 1), 1, 1, 1), 1, 1), 1, 1, 1), 1, 1, 1), 1, 1, 1), 1, 1, 1)
}
foo_noreturn_0()
function foo_singlereturn_0(x_0, x_1, x_2, x_3) -> x_4
{
x_4 := addmod(addmod(addmod(x_0, x_0, x_0), x_0, x_0), x_0, x_1)
}
}
```

## Environment

- Compiler version: latest develop

**Comment by chriseth** [comment]
This looks suspiciously similar to the other issue we had some weeks ago...

**Comment by chriseth** [comment]
And it can probably be solved by not inlining functions that are indirectly recursive...

**Comment by bshastry** [comment]
Do we want to flag bugs like this in the future? If not, I can look into limiting recursion depth of protobuf

https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream#recursion-limit

**Comment by sifmelcara** [comment]
In this specific example, multiple `x_0` were replaced by the same expression, so the program need to compute that same expression 6 times.

I think the solution is to avoid application of `ExpressionInliner` when it will duplicate expressions? (not necessarily recursive) i.e only apply `ExpressionInliner` when the argument is a Literal/Identifier or the argument only appears once in the expression.

Actually, is there a case that `ExpressionInliner` must be used? Seems like expression splitter + function inliner + expression joiner can reach the same effect?

**Comment by chriseth** [comment]
Indeed, the expression inliner may be redundant since we now have the step that modifies for loops to pull out the condition.
Still, the expression inliner could be a useful shortcut. It currently does not have a heuristic, which we should add. Duplicating expressions should be avoided, as you said, but it is not a problem if the function call argument is itself a variable.
