### ISSUE TITLE
Scaling contract functionality vs contract size

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#687]
I am building a contract that has many functions, and potentially could grow to hundreds. This contract is a DAO that could be deployed thousands of times.. it would be ideal to be able to deploy the functions as a library (lets say libdao) and have a very simple 1 liner contract that says 'inherit libdao'  and call it (dao).

Currently due to gas limits, I may have to break my library into two libraries, thats ok.. so libdao1 and libdao2.  So now my contract dao would say

```
contract dao {
   inherit libdao1
   inherit libdao2
}
```

Now contract dao should have hundreds of accessible functions that can be called.

However at the moment I have to create a `passthrough` function for every call and pass it to my library.  Which means i'll probably run out of gas after about 30-40 functions (guessing).

Is there a way to scale a contract?

Edit: Public getters are the worst, to define each return variable and have to manually set each one creates a lot of byte code, would be great to move these into a separate library but at the moment the 'passthrough' creates the same declarations and assignments and uses the same amount of gas trying to call the library.

So in an ideal scenario, I would have multiple libraries costing maybe 10-20 million gas all up.. but deploying an instance of the dao contract only costing 50k gas.

Its like a runtime import/inherit statement, rather than a compile time one.

**Comment by slothbag** [comment]
I've also noticed each time a library call is made it links the library address into the byte code each time.  So if you call the same library 10 times it puts the 20 byte address in 10 times.  200 bytes costs a lot of gas.

**Comment by VoR0220** [comment]
so I can solve atleast one of your problems. You don't need to make public getter functions. Your state variable is already a getter function. Just set your state variable to public and then call it like you would a function. That SHOULD reduce your contract overhead.

**Comment by slothbag** [comment]
Thanks VoR0220 for the suggestion.  I tried it out and it only returns ABI generic types.. so all my custom structs don't get returned.

**Comment by chriseth** [comment]
One piece of advice: Don't make such large contracts, they tend to have bugs you did not anticipate.

You might be able to modularize specific functionality of the contract into libraries where it makes sense to group them, and that's exactly what libraries are for.

Furthermore, on your comment about address reuse: Actually pushing an integer constant onto the stack costs the same amount of gas irrespective of its length. Longer numbers are expensive only at deploy time, but not at runtime. The optimizer takes this trade-off into account and lets you specify how often will run it.

**Comment by VoR0220** [comment]
@slothbag you cannot externally return structs currently. We're still working on that.

**Comment by slothbag** [comment]
My focus with this issue was purely on contract size/gas cost to deploy, a 3-4 million gas limit means a contract can only scale to have about 20 functions (with very few lines of code in them) max before you start to reach the limit regardless of using libraries and such.

My additional post about the Library calls, what I mean is if in your base contract you call library A 20 times, when you look at the byte code for the contract there is 20 times "_____LibraryA______" in the byte code, so it has increased the byte size by 400 bytes and gas cost as a result.

**Comment by VoR0220** [comment]
uhhh...that's supposed to be a filler for where your library address is.

**Comment by slothbag** [comment]
Yes I know, my point is there is 20 fillers for the same address.

**Comment by VoR0220** [comment]
right...probably because you call that library 20 times...not a huge deal.

**Comment by chriseth** [comment]
@slothbag you are right, it might be that the optimizer refuses to combine the addresses because they are not plain integers.

**Comment by slothbag** [comment]
its not a huge deal.. but it doesn't take much code to bring a contract up to the gas limit. So using libraries was a way to get around the size limitation, but then each library call generates another 20 more bytes and you start to run into contract size issues again.. 

To get around this issue I tried to store the library address in a variable and use library.delegatecall() instead but I don't know how to calculate the function selector, see my other issue https://github.com/ethereum/solidity/issues/688

Anyway, this issue is more feedback that something that needs to be fixed.  Feel free to close the issue.
