### ISSUE TITLE
Function selector and argument encoding problem

### ISSUE THREAD

**Issue by wangjunbao2018** [ethereum/solidity#6872]
Hi, there,

I get confused when I encode the arguments in the contract from [Solidity](https://solidity.readthedocs.io/en/latest/abi-spec.html#function-selector-and-argument-encoding).

Here is the contract:
```
pragma solidity >=0.4.16 <0.7.0;

contract Foo {
    function bar(bytes3[2] memory) public pure {}
    function baz(uint32 x, bool y) public pure returns (bool r) { r = x > 32 || y; }
    function sam(bytes memory, bool, uint[] memory) public pure {}
}
```

In the document,  it says that  dynamic types should add the offset position, but for `bar(["abc", "def"])`, the result is `0xfce353f661626300000000000000000000000000000000000000000000000000000000006465660000000000000000000000000000000000000000000000000000000000 `, (web3.sha3('bar(bytes3[2])')) + enc("abc") + enc("def"),  why doesn't it add the offset position data?   Is there anyone who can tell me the reason? thx

**Comment by leonardoalt** [comment]
Hi @wangjunbao2018 ,
`bytes3[2]` is not a dynamic type, that's why it's encoded in-place.

**Comment by wangjunbao2018** [comment]
> Hi @wangjunbao2018 ,
> `bytes3[2]` is not a dynamic type, that's why it's encoded in-place.

Thx.  I still don't understand.  

In the official document, it's the definition of "dynamic" blow:

> Definition: The following types are called “dynamic”:
> bytes
> string
> T[] for any T
> T[k] for any dynamic T and any k >= 0
> (T1,...,Tk) if Ti is dynamic for some 1 <= i <= k

`bytes3[3]`  matches T[k],    why isn't  this a dynamic type?

**Comment by leonardoalt** [comment]
The type in question is `bytes3[2]`, a fixed-sized array of base type `bytes3`.
Since it's fixed-sized, it does not match `T[]` (dynamically sized).
It also does not match `T[k] for any dynamic T` because `bytes3` is not dynamic (https://solidity.readthedocs.io/en/v0.5.9/types.html#fixed-size-byte-arrays).

**Comment by wangjunbao2018** [comment]
> The type in question is `bytes3[2]`, a fixed-sized array of base type `bytes3`.
> Since it's fixed-sized, it does not match `T[]` (dynamically sized).
> It also does not match `T[k] for any dynamic T` because `bytes3` is not dynamic (https://solidity.readthedocs.io/en/v0.5.9/types.html#fixed-size-byte-arrays).

Ooooh，I see. thanks a million
