### ISSUE TITLE
Documentation of calculating function signature for library functions with structs

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#688]
In the following contract, how would I calculate the function signature of `function test(MyLib1.mystruct storage ms)` so that I may use it in the delegatecall line `mylib2_address.delegatecall(0x????????, ms);`

```
library MyLib1 {
   struct mystruct {
      uint a;
   }
}
library MyLib2 {
   function test(MyLib1.mystruct storage ms) {
      // do stuff
   }
}
contract MyContract {
   MyLib1.mystruct ms;
   function MyContract() {
      MyLib2.test(ms);
      address mylib2_address = 0x1234;
      mylib2_address.delegatecall(0x????????, ms);
   }
}
```

How

**Comment by chriseth** [comment]
The function signatures are printed if you use `--gas`, but yes, this is a gap in the documentation.

It basically prefixes the struct with identifiers until it reaches global scope (in this case it would be `MyLib1.mystruct`) and adds a storage specifier to storage types. So here it would be:

`test(MyLib1.mystruct storage)`

**Comment by slothbag** [comment]
Thanks @chriseth
