### ISSUE TITLE
[DOCS] Document memory layout of arrays.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6882]
Whereas for calldata arrays the docs specify that all types follow the format defined in the ABI specification, I haven't seen any description of the layout of arrays in memory.

**Comment by chriseth** [comment]
@ekpyron can you provide a rough technical description that can be fleshed out by chris later on?

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale and lacking information, and for that reason we're closing it for now.
