### ISSUE TITLE
[DOCS] Add to list of tools, and configurations to assist in preserving style described in style-guide.rst

### ISSUE THREAD

**Issue by rocky** [ethereum/solidity#6885]
-->

## Abstract

Mention tools and give configurations that will help maintain the current coding style.

## Motivation

[style-guide.rst](https://github.com/ethereum/solidity/blob/develop/docs/style-guide.rst) is pretty specific and detailed now. However there is no mention of tools and configurations of tools that assist in keeping the style the way it should be.  

And it should be noted explicitly that VSCode does this, so someone agnostic to tooling can know to use this tool over some other. 

I know for example `.editorconfig` describes a small part of this. Some environments may need to be told to look at that. 

Even if say VSCode picks this up automatically to set a bunch of its internal configuration parameter, we should write those out in a configuration and make that available explicitly. People who work on other C++ may need to switch back and forth between "standard" coding styles and the style be explicit helps those who work among different C++ projects.

**Comment by chriseth** [comment]
Are you talking about the style of solidity source files or our internal c++ style?

**Comment by rocky** [comment]
I  am talking about your internal C++ style and how to set up different programming environments to make it easy to ensure that the house C++ style is maintained.  For example in Emacs [here](https://www.emacswiki.org/emacs/IndentingC) is a partial list of formatting styles. Quoting from that: 

* “gnu”: The default style for GNU projects
* “k&r”: What Kernighan and Ritchie, the authors of C used in their book
* “bsd”: What BSD developers use, aka “Allman style” after Eric Allman.
* “whitesmith”: Popularized by the examples that came with Whitesmiths C, an early commercial C compiler.
* “stroustrup”: What Stroustrup, the author of C++ used in his book
* “ellemtel”: Popular C++ coding standards as defined by “Programming in C++, Rules and Recommendations,” Erik Nyquist and Mats Henricson, Ellemtel

If for example one of these matches what is used it would be helpful to say that. 

For vim there might be some other set of settings. For vscode another, eclipse another and so on. 

In Python there is [blacken](https://github.com/python/black) which will format automatically. Go has gofmt and rust has something as well. If there are formatting tools that are acceptable that might be mentioned.

**Comment by chriseth** [comment]
We could not yet find a matching style set.

**Comment by rocky** [comment]
If you can find one(s) that is/are _close_ and describe the differences in terms of specific features, that would help greatly. 

The fact that there is no matching style set is all the more reason that describing the variations from some existing style(s) would be helpful. Presumably those are more well known and used since they have been publicized enough to have codified it in style checking code.  Thanks.
