### ISSUE TITLE
Make ``release_ppa.sh`` treat the ``release`` branch specially instead of the ``develop`` branch.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6899]
Currently the ``release_ppa.sh`` script basically treats every branch that's not the ``develop`` branch as ``release`` branch - I think it'd be better and safer to treat every branch the same as a ``develop`` branch and instead treat the ``release`` branch specially.

**Comment by chriseth** [comment]
It might be necessary to also treat tags specially.

**Comment by ekpyron** [comment]
Note that #6884 includes this change, so we need to be careful, if treating tags specially is in fact needed as well.
