### ISSUE TITLE
Consider enabling compiler warnings beyond "-Wall".

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6905]
There's quite a few warning types that are not included in ``-Wall`` - @Marenz stumbled across a case that would have benefited from ``-Wconversion``, which might make sense to follow in general (i.e. effectively disallowing implicit narrowing casts).

So we should evaluate whether we *can* and *should* enable further compiler warnings like ``-Wconversion`` or others. (It might be infeasible, though, in case some of our deps violate the respective warning types)

**Comment by ekpyron** [comment]
I had a quick look - this would require quite a lot of small changes - most of them would end up being reasonable, though, i.e. we do quite some random casting between ``size_t`` und ``unsigned int`` that'd better be avoided...

**Comment by axic** [comment]
Bunch of suggestions:
- `-Wpedantic`
- `-Wshadow`
- `-Wconversion -Wsign-conversion`
- `-WWno-unknown-pragmas`
- `-Wimplicit-fallthrough`

**Comment by axic** [comment]
Agreed in January not to enable shadowing: https://github.com/ethereum/solidity/pull/8013#issuecomment-572046943

`-pedantic -Wno-unknown-pragmas -Wimplicit-fallthrough` was added by #8013

This leaves `-Wconversion -Wsign-conversion` unaddressed.

**Comment by chriseth** [comment]
Let's try them!

**Comment by axic** [comment]
I did try them back in January and they require **a lot** of changes. Someone needs to sit down and fix them one by one :wink:

**Comment by chriseth** [comment]
But they are really useful.

**Comment by chriseth** [comment]
I think it should be done on a file-by-file basis with checks only run locally.

**Comment by mijovic** [comment]
Fixes for `-Wsign-conversion` in #9082

**Comment by axic** [comment]
I tried `-Wconversion` and I think it will detect more issues than `-Wsign-conversion`, but at least they seem very complimentary.

**Comment by axic** [comment]
I did fixes for `-Wconversion` in most of the places except `libevmasm` and `tests`, will push a PR later today.

**Comment by axic** [comment]
In Fizzy we went all-in:
```
add_compile_options(
    -Wcast-qual
    -Wcast-align
    -Wmissing-declarations
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra-semi>
    $<$<COMPILE_LANGUAGE:CXX>:-Wold-style-cast>
)
cable_add_cxx_compiler_flag_if_supported(-Wfinal-dtor-non-final-class)
cable_add_cxx_compiler_flag_if_supported(-Wnewline-eof)
cable_add_cxx_compiler_flag_if_supported(-Wsuggest-destructor-override)
cable_add_cxx_compiler_flag_if_supported(-Wunreachable-code-break)
cable_add_cxx_compiler_flag_if_supported(-Wduplicated-cond)
cable_add_cxx_compiler_flag_if_supported(-Wduplicate-enum)
cable_add_cxx_compiler_flag_if_supported(-Wlogical-op)
cable_add_cxx_compiler_flag_if_supported(-Wno-unknown-attributes)

if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
    option(WEVERYTHING "Enable almost all compiler warnings" OFF)
    if(WEVERYTHING)
        add_compile_options(-Weverything)
        add_compile_options(
            -Wno-c++98-compat
            -Wno-c++98-compat-pedantic
            -Wno-covered-switch-default
            -Wno-double-promotion
            -Wno-float-equal
            -Wno-padded
            -Wno-return-std-move-in-c++11
            -Wno-switch-enum
        )
    endif()
endif()
```

Maybe at some point in the future we can get closer to that in Solidity.
