### ISSUE TITLE
BigEndian support

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6907]
@anujajakhade recently reported test failures in the gitter channel and it turned out they were due to the used system being BigEndian.

We should either *support* BigEndian or, if we can't, generate an error when attempting to build on a BigEndian platform.

Do we have the capacity to support BigEndian? Is there a decent way to simulate BigEndian for us to work on it (I guess none of us have a BigEndian system available)? I guess qemu will work, but it might be horribly slow... It would probably mean to go through the entire code base line by line with endianness in mind... how many systems actually use BigEndian these days?

**Comment by axic** [comment]
I'd say it should be a build failure in cmake.

There are very few systems around today which are BE and I can't recall any widely used system which would be on a desktop.

Lot of RISC designs, such as PowerPC, MIPS and ARM can operate in big endian mode, but don't see any of these mainstream on desktop systems.

**Comment by ekpyron** [comment]
Yes, we should definitely produce an error for now - and I tend to agree that supporting BE might be out of our scope for the time being.

**Comment by ekpyron** [comment]
It turns out that @salamani who reported the boost 1.70 issues is also on a big endian system - maybe it's not that uncommon after all and it might be worth to work towards better support (although we should always clearly mark it experimental in any case).

**Comment by ekpyron** [comment]
I added some unit tests for our keccak implementation in https://github.com/ethereum/solidity/pull/6925, since I expected them to fail on BigEndian and @anujajakhade confirmed that they do. Fixing that alone in a safe way would probably be quite some effort (unless we choose a different and endianness-safe keccak implementation from somewhere as replacement altogether).

Generally, a hard prerequisite for actually supporting BigEndian in solidity would be the ability to even run semantics tests, but currently aleth doesn't support BigEndian at all either I think. (Although we could of course run the test via a network connection to a LittleEndian aleth version, but well...)

So while support for BigEndian would of course be nice and there indeed seems to be *some* demand for it, so far I see too many blockers. @chriseth what do you think?

**Comment by ekpyron** [comment]
@anujajakhade just mentioned that they can provide a BigEndian machine/server on which we could run CI tests.

**Comment by ekpyron** [comment]
aleth doesn't have any plans for supporting big endian systems. However, given the most recent developments regarding https://github.com/ethereum/solidity/issues/2626, we might be able to run the tests against geth in the future as well, though - do they support big endian systems? At a quick search I haven't found any information about that.

**Comment by chriseth** [comment]
I would say this is not a priority for now. I think we are happy to accept external pull requests that improve portability, but it is not on the near-term roadmap for the team itself.

**Comment by axic** [comment]
@chfast would it be easy to add a check in CMake failing if it is run on a big endian system?

**Comment by chfast** [comment]
https://cmake.org/cmake/help/latest/module/TestBigEndian.html

**Comment by axic** [comment]
Is this a special module or part of the main cmake? It is not clear from the docs.

**Comment by chfast** [comment]
It's a CMake module (so you have to include it), but it's available in every CMake installation.

**Comment by axic** [comment]
Damn, it was already added in #6912.

Closing this issue, given cmake will throw a message ("Solidity currently does not support big endian systems."). If in the very unlikely scenario, someone wants to compile on a BE system, they will contact us.

**Comment by ekpyron** [comment]
> If in the very unlikely scenario, someone wants to compile on a BE system, they will contact us.

Well, several people *did* contact us independently - that's we we had this issue ;-)...
