### ISSUE TITLE
Consider updating emscripten 1.38.34 (resp. current version)

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6917]
From 1.38.24:
``Perform JS static allocations at compile time (#7850)``
might be beneficial.

From 1.38.27:
``Remove deprecated Pointer_stringify (use UTF8ToString instead). See #8011``
might be a problem (we used that at some point, I'm not sure we still do).

**Comment by axic** [comment]
> Remove deprecated Pointer_stringify (use UTF8ToString instead). See #8011
> might be a problem (we used that at some point, I'm not sure we still do).

I think we had a workaround in place for a long while, but need to check if we had it since 0.5.0.
