### ISSUE TITLE
Version of library that enforces functional design

### ISSUE THREAD

**Issue by snario** [ethereum/solidity#6920]
It would be very nice for state channel based applications if we could restrict the set of applications to be `library` contracts that define a single data structure and only allow functional methods; that is, methods with a function signature like:

```solidity
struct KnownState { ... }
function functionalMethod(KnownState state, ...) returns (KnownState);
```

Perhaps this could also be a new kind of contract type? Maybe a `data` contract type? Ruby's `class` object seems to be similar to what I am describing by restricting class methods to return the same data type as the object the class is describing.

**Comment by ekpyron** [comment]
I'd say this is somewhat related to https://github.com/ethereum/solidity/issues/4637, although a bit different - might be worth thinking about whether both requests can be satisfied with the same language construct.

**Comment by snario** [comment]
@ekpyron it is quite similar, yeah. Would be happy to go into more detail about the use case if you'd like. Generally, we feel quite confident that this would be very useful for defining state transition logic in state channel applications.

**Comment by ekpyron** [comment]
It might be good to go into some more detail, yes. If only a specific library (or a small set of libraries that is known in advance) should be able to implement such state transitions, then this will probably entirely fall under #4637, right? But you probably want arbitrary new libraries to be able to define new state transitions and just restrict the signature of functions that can use the state?

I'm wondering: is it necessary to actually define a hard syntactic restriction for this? An analysis tool could easily check whether all occurrences of the struct are like this without the need of a new contract type or syntactic errors in solidity itself, couldn't it?

Should the restriction only be for *writing* to the struct? I could imagine something like ``validate(KnownState state)`` or ``outputDebugInformation(KnownState state)`` to still be useful... I assume functions with the ``function(KnownState state) returns (KnownState)`` signature are generally also assumed to only *read* from ``state`` and never to modify it?

Is this meant for ``KnownState`` to be in memory, in storage, in calldata or in any of those?

EDIT: resp. should this apply to internal or external library functions or both? Only for library functions, or for other types of functions as well?

**Comment by snario** [comment]
@ekpyron I think it would only apply to external library functions, probably optionally memory, in storage, or in calldata, but for the case of handling challenges in state channels, likely in calldata.

Also, `state` would be readonly.

Here is an example:

```solidity
library FunctionalCounter {

    struct State {
        uint256 value;
    }

    function add1(State calldata state) external pure returns (State memory) { 
        return State(state.value + 1);
    }

}
```

I think having a syntactic restriction around it would make it very hard for developers to mess up and make the model of having data structures that can be modified only via EVM-compatible state transitions be very clear. 

It would also mean that client software for state channels that want to ensure that state transitions are valid in the applications they're supporting wouldn't need to import any kind of code analysis tools and could rely on the Solidity compiler.

I'm not exactly sure though if that's the right opinion to have here though, maybe having separate pieces of software validating these libraries is the cleaner approach?

**Comment by snario** [comment]
In state channels the state structure we are thinking of that motivates this use case will roughly look like this:

```solidity
struct ChannelState {
    bytes state;
    address stateTransitionLibrary;
    bytes transitionData;
    ...
}
```

Using the `FunctionalCounter` example above, then `s1` might have the `state` being the encoded version of the `uint256` value `1`, the `stateTransitionLibrary` being the address of a `FunctionalCounter` library. Then, `s2` would have `transitionData` being the encoded version of `add1`.

Then the client logic would compute `s2Expected = FunctionalCounter.add1(s1.state)` to get `<State value={2}>` which is what `s2.state` would encode and so if `s2Expected.state == s2.state` then the transition is valid and the party can consider it as a valid state channel update.

**Comment by ekpyron** [comment]
Hm... maybe it would make sense to extend #4637 with some notion of "library interfaces" or "library inheritance"... e.g. (to sketch the rough idea):
```
interface StateTransitionInterface {
  private struct ChannelState {
    bytes state;
    StateTransitionInterface stateTransitionLibrary;
  }
  function stateChange(ChannelState calldata input) external returns (ChannelState);
}
library FunctionalCounter is StateTransitionLibrary {
  function stateChange(StateTransitionInterface.ChannelState calldata input) external returns (StateTransitionInterface.ChannelState) { ... }
}
```
Where ``private struct`` is to be replaced by whatever syntax we'd add for "closed structs" in #4637.
The idea being that only libraries inheriting from ``StateTransitionInterface`` can access ``ChannelState`` and can only do so in the interface functions given in ``StateTransitionInterface``...

Would that work for solving your use case? I'm not entirely sure about it... and I'm wondering what @chriseth's (who is currently on vacation) and @axic's take is on this...

**Comment by ekpyron** [comment]
Another question: is there a reason for the state transition contracts to be libraries in your use case? So do you need to access the callers storage and rely on delegatecall? Or are the state changes likely to be ``view`` or even ``pure`` functions anyways? So could the state transition be an ``interface`` and the "state transition libraries" be regular contracts implementing that interface? Then #4637 could just be extended from libraries to interfaces and we wouldn't need to add library interfaces or inheritance...

**Comment by snario** [comment]
@ekpyron State changes will _only_ be `view` or `pure` functions.

The name thing I'm hoping to achieve is not requiring the implementation to have a single accessor function (e.g., `applyAction(state, action)`) and instead allow developers to just define functions like they would for any regular Solidity contract.

**Comment by ekpyron** [comment]
Ok, in that case a solution involving interfaces will probably be of limited use.
Then I would take a step back :-).

I'm not sure about your original suggestion of restricting the function signatures in which the struct is allowed to occur - would it be enough to introduce a concept like ``immutable`` structs? I.e. a struct that can be constructed, but not modified after being constructed. That way you could construct a new "sane" state, but could not mess with a state by only writing to some of its members. That would basically result in a restriction very similar to what you originally proposed, right?

Additionally, it might be nice to introduce something like an ``address view`` for the ``stateTransitionLibrary`` that only allows ``staticcalls`` and thereby enforces state changes to be ``view`` or ``pure``.

Is that a direction that makes sense to you?

**Comment by snario** [comment]
That satisfies most requirements except for having a guarantee that a function call applied to the old state will return a new state of the same type.
