### ISSUE TITLE
value unchanged when external calldata function call internal memory function

### ISSUE THREAD

**Issue by aihuawu** [ethereum/solidity#6921]
struct A {
     uint val;
}
library lib {
 function f(A calldata a) external{
   g(a);
   // here I expect a.val == 1;
   // but it is still a.val == 0;
   // is this a bug???
 }
 function g(A memory a) internal{
   a.val=1;
 }
}

**Comment by aihuawu** [comment]
It seems the it copy the memory value and so the value is unchanged.

Actually I want to use a deployed library to modify a memory location of the calling routine.
The following library code does not compile.
How can I modify a memory location through a deployed library?

library lib {

struct A {
uint val;
}
function f(A calldata a) external{
a.val=1; // Error: Expression has to be an lvalue.
}
}

**Comment by ekpyron** [comment]
It's not possible to write to calldata (calldata is read-only), so I don't think what you want is possible *without* copying to memory. So
```
function f(A memory a) public {
  g(a);
  assert(a.val == 1);
}
function g(A memory a) internal {
  a.val = 1;
}
```
should work (but involves a ``calldata`` -> ``memory`` copy for every call to ``f``) - but you won't be able to modify an argument in ``calldata`` itself.

So I don't think this is in fact a bug - if you agree, please close the issue.

**Comment by aihuawu** [comment]
@ekpyron 
Thanks.
Can you also answer my second question above?

I have a utility library deployed.  The methods are public or external.
I can't use internal since the master contract size can't go above 6.7M gas.

The utility library is separate and 
it is supposed to be able to modify a storage and memory of the calling contract.
For storage, it is reference, so no problem.
But for memory, it is copied and I am unable to modify it in the utility library.
I need some way to modify the memory of the calling routine in the utility library.
Is it possible?

george wu

**Comment by ekpyron** [comment]
External library functions will be called using ``DELEGATECALL``, which will retain the calling contract's storage, but it's still a proper call, so the library will get it's own memory (and not retain the memory of the caller), so it's not possible to pass a memory reference, resp. modify memory across external library calls. You could e.g. pass it as argument to the library function and return it, but that will, of course, involve copies, but there's no way around that.

**Comment by aihuawu** [comment]
Thank you.
