### ISSUE TITLE
Inconsistent gas costs for simple operations.

### ISSUE THREAD

**Issue by danno-s** [ethereum/solidity#6933]
### Bug
Simple functions that do a single arithmetic operation and assignment, and have no branches in their code can have different gas costs, depending on what functions have been called before.

### Expected behaviour
Functions with no branches in their code, always cost the same amount of gas, independent of previous function executions of the contract.

## Environment

- Compiler version: 0.5.1
- Target EVM version: Constantinople
- Framework/IDE: Truffle
- EVM execution environment / backend / blockchain client: Ganache (Constantinople chain)
- Operating system: Ubuntu 18.04

### Project configuration
Starting from a fresh truffle project, add the following contract `Counter.sol`:

```solidity
pragma solidity ^0.5.1;

contract Counter {
    uint public count;

    constructor() public {
        count = 1;
    }

    function divide(uint8 factor) public returns (uint) {
        count /= factor;
        return count;
    }

    function add(uint8 value) public returns (uint) {
        count += value;
        return count;
    }
}
```

Add a second migration:
```javascript
var Counter = artifacts.require("Counter")

module.exports = function(deployer) {
    deployer.deploy(Counter);
};
```
And edit the compilers object in `truffle-config.js` to the following:

```javascript
compilers: {
  solc: {
    settings: {
      evmVersion: "constantinople"
    }
  }
}
```
Configure ganache to use the Constantinople hardfork, and then deploy using `truffle migrate`.

### Reproduction
After deployment in Ganache, the following commands were executed in the truffle console:
```
let instance = await Counter.deployed()
instance.add(10) // gasUsed: 27187
instance.divide(100) // gasUsed: 13625
insatnce.add(10) // gasUsed: 42817
```
Where the two add calls had drastically different gas costs.

**Comment by sifmelcara** [comment]
I guess it is because when you set a zero value in storage to a non-zero value, you need to pay 20000 gas. But when you set a non-zero value into another non-zero value, you only need to pay 5000 gas.

You can refer to https://github.com/djrtwo/evm-opcode-gas-costs to see the gas cost formulae for 
 the `SSTORE` instruction

**Comment by ekpyron** [comment]
Yep, @sifmelcara is right - and that accounts exactly for the difference in gas costs. So I'm closing this - please reopen in case I'm missing something.
