### ISSUE TITLE
Investigate running soltest against go-ethereum.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6936]
@gumb0 recently remarked that go-ethereum has merged "retesteth" support in https://github.com/ethereum/go-ethereum/pull/19631 and that it should support most or all RPC commands needed for running soltest.

We should check whether that's in fact possible - if it is, it might be nice to have a (nightly or regular) CI run testing against go-ethereum's EVM implementation as well.

**Comment by axic** [comment]
See also #2626.

**Comment by ekpyron** [comment]
Closing this as duplicate of #2626.
