### ISSUE TITLE
[optimizer] Redundant rule in RuleList.h

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6947]
## Description

https://github.com/ethereum/solidity/blob/e78500a1994a8dec7f328d4ad8764e79c80b2faf/libevmasm/RuleList.h#L92

is redundant (and buggy?) because the rule preceeding it is always picked up for any `mulmod` operation.

Buggy because the encoded transformation is not correct `a*b mod c != a*b`

## Environment

- Compiler version: latest develop

**Comment by chriseth** [comment]
Please remove it!
