### ISSUE TITLE
Better support ENS (namehash)

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6956]
This is currently a brainstorming issue. ENS should be better integrated into Solidity, but we probably do not want the compiler to make any name lookups at compilation time. Something like named constants supplied by the compilation driver / framework might be a good middle ground that could also be used for many other purposes.

**Comment by chriseth** [comment]
@arachnid suggested supporting namehash in the form `bytes32 nh = namehash("my.name.eth");`.

**Comment by chriseth** [comment]
The latter might either be specifically implemented in the compiler or it could be generalized to "parameterized constants" of the form `$namespace(arg1, arg2, arg3)`. For each such occurrence, the compiler enquires the compiler driver for the value of that constant and inserts it into the source code.

To ensure deterministic compilation and reproducible builds, a list of all the values for these constants need to be provided as part of the compilation options.

**Comment by axic** [comment]
Why should this get special treatment and not just implement #3878 ?

**Comment by chriseth** [comment]
Because the values of these parameterised constants might be not be pure expressions or might not be implementable in solidity. Namehash is, but it could also be something like `resolveAddressAtCompileTime("my.name.eth")`

**Comment by axic** [comment]
Why would this be needed? Could #1650 be considered as an option for this?

**Comment by Arachnid** [comment]
Namehash isn't really practical to implement in solidity - it requires doing UTS46 normalisation, which requires enormous (for a smart contract) character lookup tables.

**Comment by chriseth** [comment]
At the moment, I do not see an easy way to do this. We either need to support a specific set of macro functions inside the compiler or move this responsibility to the driver. Since the latter would either need a callback mechanism or a multi-pass compilation, both do not seem particularly nice.

**Comment by axic** [comment]
Actually now with having different callback kinds, this could be moved to the callback layer.

**Comment by Arachnid** [comment]
I'd still love to see this implemented.

**Comment by cameel** [comment]
@ekpyron @chriseth @axic Since this is a brainstorming issue and has been open for quite a while, I guess, if there were any more concrete ideas beyond #11436 and #11972, they would have been reported by now.

We should at least decide if we intend to put this somewhere on our future roadmap and actually spend some dedicated research time on this eventually. If not, we should be honest here and close this.
