### ISSUE TITLE
[code generation]: Opcode 0xfe generated by solidity?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6966]
## Description

(Reproducible via remix as well)

```
pragma experimental ABIEncoderV2;

contract C {
    uint256[2][] sa;

    function h(uint256[2][] calldata cd) external returns (bool) {
        if (cd.length != sa.length) return false;
        if (cd[0][0] != 1) return false;
        if (cd[0][1] != 2) return false;
        if (cd[1][0] != 3) return false;
        if (cd[1][1] != 4) return false;
        if (cd[2][0] != 5) return false;
        if (cd[2][1] != 6) return false;
        return true;
    }
    function f() public returns (bool) {
      sa[0][0] = 1;
      sa[0][1] = 2;
      sa[1][0] = 3;
      sa[1][1] = 4;
      sa[2][0] = 5;
      sa[2][1] = 6;
      return this.h(sa);
    }
}
```

I compile this

```
$ solc --bin-runtime test.sol > runtime_code
```

I pass the input `26121ff0` (hash of function `f()`) to the evm for the `runtime_code` obtained via previous step.

```
$ evm --prestate genesis.json --codefile runtime_code --input 26121ff0 run
0x
 error: invalid opcode 0xfe
```

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg
- Operating system: ubuntu 18.04

**Comment by bshastry** [comment]
Labeling it as bug because I have been able to successfully run bytecode generated by the upstream compiler in the past.

**Comment by chriseth** [comment]
This opcode is called the invalid opcode. It is a defined opcode which leads to a forced exception. It is used for e.g. array access out of bounds.

**Comment by bshastry** [comment]
Oh ok. Not able to spot the out-of-bounds access unfortunately.

**Comment by chriseth** [comment]
You never resize `sa`.

**Comment by axic** [comment]
Side note: in [EIP-1803](https://eips.ethereum.org/EIPS/eip-1803) I propose to rename it to `abort` to avoid all this confusion :wink:

**Comment by bshastry** [comment]
Closing this issue, since this is a stupid programming error on my part. I can confirm that I am able to reproduce [the abiv2 bug](https://github.com/ethereum/solidity/pull/6958/files#diff-1ff95bce7da3584881ddab5f4db52dd7) in unpatched solidity with this program

```
pragma experimental ABIEncoderV2;

contract C {
    uint256[2][] sa;

    function h(uint256[2][] calldata cd) external returns (bool) {
        if (cd.length != sa.length) return false;
        if (cd[0][0] != 1) return false;
        if (cd[0][1] != 2) return false;
        if (cd[1][0] != 3) return false;
        if (cd[1][1] != 4) return false;
        if (cd[2][0] != 5) return false;
        if (cd[2][1] != 6) return false;
        return true;
    }
    function f() public returns (bool) {
      sa.length = 3;
      sa[0][0] = 1;
      sa[0][1] = 2;
      sa[1][0] = 3;
      sa[1][1] = 4;
      sa[2][0] = 5;
      sa[2][1] = 6;
      return this.h(sa);
    }
}
```

```
$ solc --bin-runtime test.sol > runtime_code
$ evm --prestate genesis.json --codefile runtime_code --input 26121ff0 run
0x0000000000000000000000000000000000000000000000000000000000000000
```

This should return `0x0000000000000000000000000000000000000000000000000000000000000001` when the bug is fixed.

Note to self: call to `abi.encode` is not necessary. Input values don't matter.
