### ISSUE TITLE
Wrong type used to calculate memory array element offset

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#6969]
## Description

This issue tracks discussion happened at https://github.com/ethereum/solidity/pull/6881#discussion_r289808363 and https://github.com/ethereum/solidity/pull/6965

The following line's `_arrayType.memoryHeadSize()` should be changed to `_arrayType.baseType()->memoryHeadSize()`
https://github.com/ethereum/solidity/blob/ae273ff3bda86df699ab00185e2c409bad128d4a/libsolidity/codegen/ArrayUtils.cpp#L1060

I quickly looked though the implementation of `memoryHeadSize()` in `libsolidity/ast/Types.h` and `libsolidity/ast/Types.cpp`, and looks like it always return 32 (either because it is a reference type or because its `calldataEncodedSize(true)` is 32). But there are two things confuses me:

1.
https://github.com/ethereum/solidity/blob/ae273ff3bda86df699ab00185e2c409bad128d4a/libsolidity/ast/Types.h#L581
Not sure why it want to return 0 when `m_bytes` is 0? (although `m_bytes` cannot be 0 in the first place)

2.
https://github.com/ethereum/solidity/blob/ae273ff3bda86df699ab00185e2c409bad128d4a/libsolidity/ast/Types.cpp#L2781-L2787

Why this strange formulae?

**Comment by chriseth** [comment]
1) `m_bytes` was allowed to be zero in earlier versions.
2) the strange formula rounds to the next multiple of 32 - it might have just been copy-pasted for this special case.
