### ISSUE TITLE
Ensure addr.call.value() is invoked

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#697]
contract Test {
        function Test(){
            msg.sender.call.value(0);
            msg.sender.call.value(0)();
        }
    }

My understanding is the first call doesn't actually do anything. If so, it shouldn't compile

**Comment by chriseth** [comment]
Are you recommending a warning? It is not a compiler error, because you could do things like:

```
contract Test {
  function test() {
    var x = msg.sender.call.value(0);
    x();
  }
}
```

**Comment by redsquirrel** [comment]
I think this would be a good place for a warning, since we're ignoring a return value from a low-level function. Related: #677

**Comment by aakilfernandes** [comment]
@chriseth didn't realize you could store it as a variable. I think a warning would be apt.

**Comment by axic** [comment]
Is it useful storing it is a variable, though?

**Comment by chriseth** [comment]
@axic Solidity should not impose artificial restrictions. It is useful to store functions in variables and the ether amount and gas sent together with a function is part of it.

**Comment by axic** [comment]
So if `msg.sender.call.value(0)` is not assigned to a variable and is not executed, then the compiler should emit a warning.

**Comment by chriseth** [comment]
I don't think this is an issue anymore with the new syntax.
