### ISSUE TITLE
Replace boost::regex by std::regex

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6971]
Solidity still uses boost::regex in some cases although we can already use std::regex. The code should switch to std::regex and the dependency on the boost::regex library should be removed from the cmake files.

**Comment by dantedallag** [comment]
Is this issue still available? I am new to contributing to open source projects and would like to get some experience!

**Comment by chriseth** [comment]
It is available, but it turned out that it is a bit more complicated than just replacing these strings, because boost provides a method that can use a replacement function which the std seems to be lacking.

**Comment by dantedallag** [comment]
ok, awesome. I will still give it a go!

**Comment by dantedallag** [comment]
Hello, so I feel like I am making some progress (it's been taking longer as I am trying to learn more about this project in general and it is really interesting!) As for testing this particular fix on Whiskers, is there a certain test already implemented that I should use to debug/prove it works or will I need to write my own?

**Comment by chriseth** [comment]
That's great news! I don't think you need to add an additional test, the already existing whiskers tests should be enough. Please create a PR as soon as you think it is mostly done, so we can see how it works in the CI.

**Comment by holybubbles** [comment]
Is this still open? like @dantedallag I want to give this a try if it's still open.

**Comment by dantedallag** [comment]
Hey @kennycastro007 give it a try. I got super busy and have not had much time to look at this.

**Comment by kcy1019** [comment]
@chriseth I have created a pull request solving this issue. However, the Windows build CI is failing due to missing `boost::regex` library file. Can you shed some light on where can I remove the library from link targets for the Windows build?

**Comment by kcy1019** [comment]
@chriseth I've made a patch for this issue which passes all the existing tests. Could you review the PR(#7533) when you are free? :)

**Comment by chriseth** [comment]
Implemented in #7533
