### ISSUE TITLE
[Sol->Yul] Overflow and other internal errors should use invalid instead of revert

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6974]
Arithmetic errors are always internal errors and thus should lead to a failing assert instead of a failing require.

What do you think, @leonardoalt @ekpyron  @axic ?

**Comment by leonardoalt** [comment]
I agree that if it's not calldata related it should invalid.

**Comment by chriseth** [comment]
Related to https://github.com/ethereum/solidity/issues/9824

**Comment by chriseth** [comment]
Being done as part of https://github.com/ethereum/solidity/issues/9824 now
