### ISSUE TITLE
Type string memory is not implicitly convertible to expected type struct InsanFactory.User storage ref

### ISSUE THREAD

**Issue by estimatedgasfee** [ethereum/solidity#7017]
pragma solidity >=0.4.0 <0.7.0;

contract InsanFactory{
    
    struct User{
         string name;
         address myaddress;
    }
    mapping(address => User) public userStructs;
     
 
    address[] public userAddress ;
    
    function createUser(string memory name,address myaddress) public{
        userStructs[msg.sender] = name;
        //set user name
        userStructs[msg.sender] = myaddress;
        //address'i degistirdim
        userAddress.push(msg.sender);
        
    }
    function getResult() external view returns(address[] memory){
        return userAddress;
    }
}

when I compile this code I got 2 errors

-first error at line 15 says : Type string memory is not implicitly convertible to expected type struct InsanFactory.User storage ref.

*line 15(userStructs[msg.sender] = name;)

second one at line 17 says:Type address is not implicitly convertible to expected type struct InsanFactory.User storage ref.

*line 17(userStructs[msg.sender] = name;)

what should I do for my error ?

**Comment by chriseth** [comment]
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.

One way to fix this is to use
```
    userStructs[msg.sender].name = name;
    userStructs[msg.sender].myaddress = myaddress;
```

**Comment by rishabjn** [comment]
//This works perfectly

pragma solidity ^0.5.0;
contract Ub{
struct User{
     string name;
     address myaddress;
}
mapping(address => User) public userStructs;
 

address[] public userAddress ;

function createUser(string memory name,address myaddress) public{
    userStructs[msg.sender].name = name;
    //set user name
    userStructs[msg.sender].myaddress = myaddress;
    //address'i degistirdim
    userAddress.push(msg.sender);
    
}
function getResult() external view returns(address[] memory){
    return userAddress;
}
}
