### ISSUE TITLE
[SMTChecker] Questions about verification results

### ISSUE THREAD

**Issue by unboxedtype** [ethereum/solidity#7023]
Trying to get familiar with SMTChecker. I run SMTChecker on the following smart contract,
got some results but having difficulty of properly interpreting them. Please have a look.

```
$ cat forLoop2.sol 
pragma solidity ^0.5.8;
pragma experimental SMTChecker;

contract LoopFor2 {
    uint[100] b;
    uint[100] c;

    constructor() public {
      b[0] = c[0];
    }
    
    function testUnboundedForLoop(uint n) public {
      require (n > 0 && n < 100);
      for (uint i = 0; i < n; i += 1) {
        b[i] = i + 1;
        if (n > 50)
          c[i] = b[i] + 1;
        else
          c[i] = b[i];
      }
      assert (b[0] == c[0]);
    }    
}

```

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.5.8+commit.23d335f2.mod.Linux.g++

```
I receive the following results:
```
$ solc forLoop2.sol
...
 (warning about unsupported checks within a constructor) - skipped
...
forLoop2.sol:15:16: Warning: Underflow (resulting value less than 0) happens here
        b[i] = i + 1;
               ^---^
  for:
  <result> = (- 1)
  b[0] = 8855
  c[0] = 8855
  i = 3
  n = 50

```
I do not understand this underflow warning. If I have i = 2, n = 50, then b[i] will be in 
its expected range of b[i] = i + 1, for all i in [0; 50). Am I wrong here?

The next one is kind of similar:
```
forLoop2.sol:15:16: Warning: Overflow (resulting value larger than 2**256 - 1) happens here
        b[i] = i + 1;
               ^---^
  for:
  <result> = 2**256
  b[0] = 2282
  c[0] = 2282
  i = 3
  n = 50


Note that some information is erased after the execution of loops.
You can re-introduce information using require().

```
Here it warns me about overflow in b[i] = i + 1, but I do not expect overflow to happen 
in the range i = [0; 50)

Here is another one:

```
forLoop2.sol:14:31: Warning: Overflow (resulting value larger than 2**256 - 1) happens here
      for (uint i = 0; i < n; i += 1) {
                             ^----^
  for:
 <result> = (- 1)
  b[0] = 5920
  c[0] = 5920
  i = 3
  n = 50
```

Why it warns me about overflow in the counter here? 

... Some more overflow/underflow warnings of similar type ...

The last one: It seems the checker did not detect the case when n > 50, in this scenario the assertion in the end of the function will not hold. Is it expected behavior?

**Comment by leonardoalt** [comment]
Unfortunately loops are barely implemented at the moment and do issue lots of false positives.
In any case, these even show wrong models and are definitely bugs.
The assertion should also be reported as unsafe.

**Comment by unboxedtype** [comment]
Thanks for clarification!

**Comment by unboxedtype** [comment]
Sorry, I closed it. Should I reopen, or it is known issue and we close this one?

**Comment by leonardoalt** [comment]
Let's keep it open as long as this specific case is buggy

**Comment by leonardoalt** [comment]
I'm back to analyzing this now.
I ran it in my (not yet merged) branch with support to unbounded loops (via the new CHC engine) and the assertion is proven correct IF I remove the code that erases knowledge when an array is assigned. However, in this case we don't need to erase knowledge.

**Comment by leonardoalt** [comment]
Oh, I ran the example with the current `develop` and it seems these bugs were fixed by some PR since then:
```
17:07 $ ./solc/solc loop.sol 
Warning: This is a pre-release compiler version, please do not use it in production.
loop.sol:8:5: Warning: Assertion checker does not yet support constructors.
    constructor() public {
    ^ (Relevant source part starts here and spans across multiple lines).
loop.sol:21:7: Warning: Assertion violation happens here
      assert (b[0] == c[0]);
      ^-------------------^
  for:
  b[0] = 1237
  c[0] = 1236
  i = 2
  n = 1

Callstack: 

Note that some information is erased after the execution of loops.
You can re-introduce information using require().
```
Please note that the current `develop` SMTChecker engine doesn't support loops properly, as I mentioned before. However in  a couple PRs it will.

**Comment by leonardoalt** [comment]
My comment https://github.com/ethereum/solidity/issues/7023#issuecomment-515485192 is wrong:
I actually had changed the code a little bit. The assertion is not safe if `n > 50`.

**Comment by leonardoalt** [comment]
Closing since the reported bug does not exist anymore.
