### ISSUE TITLE
Add centralized documentation for operators and what types they're legal for

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#7029]
## Description

Currently, while Solidity has quite thorough documentation of its builtin functions, its operators are almost entirely undocumented.  While there is some scattershot documentation of particular operators, the only place I can find that documents the operators as a whole is their [precedence table](https://solidity.readthedocs.io/en/v0.5.10/miscellaneous.html#order), buried under miscellaneous.  This table barely describes what the operators do.  Most of them are fairly self-explanatory, mind you, so I don't think *that* much documentation is needed, but a few are not.  Still, I think it would be good to centralize what documentation there is in one easily-findable place.  Maybe it could be added to the page on builtin functions and variables.

So, ideally there would be a big table of operators, but in addition to the precedence and short description, it would also say what types it's legal for, and anything nonobvious about how it works in cases where it's unclear.  Actually I'm not sure if there are any of the latter, but there are definitely some cases where it's not obvious what types a given operator is legal for.  E.g., it's not obvious that `==` is illegal for reference types, or that the bit shift operators can be used to shift a value of type `bytesN`.  So, basically, I'd like a table listing what types a given operator is legal for.

Also, the precedence lists a comma operator, and as best as I can tell this operator doesn't exist?  (Did it exist in some previous version?)

Thank you!

**Comment by chriseth** [comment]
Sounds great!

**Comment by chriseth** [comment]
Indeded, the comma operator does not exist. I think the table was taken from a different language and modified.

**Comment by ChrisChinchilla** [comment]
Thanks @haltman-at I've actually been thinking about this for some time too.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
