### ISSUE TITLE
when "Stack too deep, try using fewer variables" error occurs? 

### ISSUE THREAD

**Issue by stanta** [ethereum/solidity#7039]
Hi, @chriseth, can you explain more about when  this error occurs? 
https://github.com/ethereum/solidity/blob/930ce34953d7b42df95d309386258a322b3ca558/libsolidity/codegen/CompilerUtils.cpp#L435

**Comment by chriseth** [comment]
There are several situations in which this or similar errors occur. Most are related to too many local variables, parameters or return variables in functions. It might also happen if you have expressions that are too deeply nested. Maybe come to https://gitter.im/ethereum/solidity-dev to discuss in more detail.

**Comment by chriseth** [comment]
Closing - please reopen if you have more questions.

**Comment by stanta** [comment]
> expressions that are too deeply nested

what do you mean here?

**Comment by chriseth** [comment]
`(((x+1)*3+2)*4+5)*6+7`

**Comment by stanta** [comment]
We get this error without reference to string in code. How can we locate error?

**Comment by chriseth** [comment]
This problem can only be detected by the compiler at the very end of the compilation process. Because of that, it might even be that there is no related source code because it is a utility function used by many places in the code. We are working on better locating these errors. Until then, you can only try to simplify the code or remove functions to see what makes it compile. Sorry for the inconvenience!

**Comment by agroce** [comment]
@chriseth I assume this example of this:

```
contract C {
        function g() public pure returns (uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint,
                uint
        ) { }
}
```

is just a hard-baked limit/not so hot error (an ICE isn't super-friendly), but not a bug/new bug.  Bit surprised this is the first the fuzzer stumbled on these...

**Comment by chriseth** [comment]
@agroce I'm not sure I get what you are talking about, but it our setup. we usually filter out StackTooDeepErrors in the fuzzer.
