### ISSUE TITLE
bytes20 and address payable implicit conversion

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7043]
## Description

```
pragma solidity >=0.0;
pragma experimental ABIEncoderV2;

contract C {
	bytes20 z;
	function f() public {
		z = 0x1234567812345678123456781234567812345678;
	}
}
```

makes the compiler implicit convert the RHS of the assignment to `address payable` and generate the following error

```
Error: Type address payable is not implicitly convertible to expected type bytes20.
                z = 0x1234567812345678123456781234567812345678;
                    ^----------------------------------------^
```

However, all other fixed byte types work just fine if the RHS contains as many bytes as the type. Why is there this discrepancy for bytes20 only?

**Comment by bshastry** [comment]
I understand that this can be solved using something like
```
z = bytes20(0x1234567812345678123456781234567812345678);
```

but wanted to check if such explicit casting for this edge case is the right way to make the error go away.

**Comment by chriseth** [comment]
This is one way to do it, but you might later encounter an "invalid address checksum" error if your hex literals also contain characters. Maybe it would be better to use
```
z = hex"1234567812abcabc123456781234567812345678";
```
instead.

**Comment by bshastry** [comment]
`0x1234567812345678123456781234567812345678` was just an example. The value itself is derived from a hashing function after applying a mask for the said width. 

> if your hex literals also contain characters.

do you mean non hex digit characters (i.e., not one of 0-9,a-f)?

**Comment by chriseth** [comment]
If you use non-number characters and the literal has a length of 20 bytes, you can run into the address checksum check. If you use `hex"..."`, then you won't have that problem.

**Comment by bshastry** [comment]
> If you use non-number characters and the literal has a length of 20 bytes, you can run into the address checksum check.

does this apply to other fixed width types of 160 bits, such as int160, uint160?

**Comment by chriseth** [comment]
it applies to the literals, not to the types.
