### ISSUE TITLE
Withdrawing Pattern Example

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#705]
Currently, in the security considerations recommendations, there is a suggestion of a pattern to use withdrawal, but there is no documentation of such a pattern in the "common patterns" section. If someone could please put that in, that would be greatly appreciated.

**Comment by Denton-L** [comment]
On it! 😄

**Comment by chriseth** [comment]
This one here might help: http://solidity.readthedocs.io/en/latest/solidity-by-example.html?highlight=withdraw#simple-open-auction
