### ISSUE TITLE
How to get the function signature from contract bytecode

### ISSUE THREAD

**Issue by zhjgit** [ethereum/solidity#7051]
How to get all the function signatures in the contract from the contract bytecode, I already know to get the evm bytecode in solidity：
```
function at(address _addr) public view returns (bytes o_code) {
        assembly {
            let size := extcodesize(_addr)
            o_code := mload(0x40)
            mstore(0x40, add(o_code, and(add(add(size, 0x20), 0x1f), not(0x1f))))
            mstore(o_code, size)
            extcodecopy(_addr, add(o_code, 0x20), 0, size)
        }
    }
```
Or how do I determine if the bytecode contains the function signature I need to call, how to modify the above inline assembly method?

**Comment by zhjgit** [comment]
@chriseth Can you look at this problem for me?

**Comment by sifmelcara** [comment]
Is `solc --hashes` what you want?

**Comment by sifmelcara** [comment]
Oops sorry, I misunderstood your question. So what you want is something like https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md ?

**Comment by zhjgit** [comment]
I don't use the interface, it's just a contract. I get the contract bytecode through the contract address, but when I call the delegatecall method, I need to know if the function signature is included in my contract, otherwise a revort error will occur. @sifmelcara

**Comment by zhjgit** [comment]
`pragma solidity ^0.4.24;

contract Test{
  uint256 public c;
  
  function doit(uint256 a) public{
      c+=a;
  }
}

contract A {
    
   function writeSomething(address addr,uint256 d) public{
       Test test = Test(addr);
      
       //I want to know if there is a doit method for this contract, otherwise I will make a mistake.
       test.doit(d);
   }    
}`
Probably the contract code is like this. To avoid calling the contract incorrectly, you must first check whether the contract contains a method.

**Comment by zhjgit** [comment]
```
pragma solidity ^0.4.24;

contract Test{
  uint256 public c;
  
  function doit(uint256 a) public{
      c+=a;
  }
}

contract A {
    
   function writeSomething(address addr,uint256 d) public{
       Test test = Test(addr);
       // I want to know if there is a doit method for this contract, 
       // otherwise I will make a mistake.
       test.doit(d);
   }    
}
```
Probably the contract code is like this. To avoid calling the contract incorrectly, you must first check whether the contract contains a method.

**Comment by leonardoalt** [comment]
Does it have to be checked on chain? You could also check it off chain before calling `writeSomething` that `addr` has the method.

**Comment by zhjgit** [comment]
@leonardoalt If  check it off the chain, the client needs to call the contract twice. This is not very friendly. I saw the solidity assembly language to get the contract bytecode, which should also get the function that exists in the contract, but I will not assemble the language.

**Comment by chriseth** [comment]
@zhjgit I agree with @leonardoalt: this is very tedious and expensive to do on-chain. Furthermore, which conclusions do you want to draw from function hashes being checked by the target contract? The EVM does not have the concept of functions and even if the target contract checks for a function, it might even revert later on. So there is not even a concept of a function being present, because you cannot distinguish between a revert caused because of a rejection in the function dispatch routine and a revert being caused by a check later in the contract. Both are dynamic conditions.

**Comment by zhjgit** [comment]
```
function check_func_exist(address _contract,bytes4 _interfaceId) public returns(uint256 result){
        //bytes4 sig = bytes4(keccak256("setA(uint256)"));
        assembly {
                let x := mload(0x40)               // Find empty storage location using "free memory pointer"
                mstore(add(x,0x04), _interfaceId)
                result := staticcall(
                                    30000,         // 30k gas
                                    _contract,     // To addr
                                    x,             // Inputs are stored at location x
                                    0x24,          // Inputs are 36 bytes long
                                    x,             // Store output over input (saves space)
                                    0x20)          // Outputs are 32 bytes long
        }
    }
```
[https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md)
I referenced the `noThrowCall` method, but it doesn't work. Can anyone help me modify it to make it work correctly?

**Comment by zhjgit** [comment]
@chriseth ok, However, such a contract often has a revort error. In order to reduce the consumption of gas on the chain, the optimal way is to verify whether the function signature exists under the chain?

**Comment by chriseth** [comment]
@zhjgit I don't think we can properly help you here. My gut feeling is that searching through the dispatch routine's binary bytecode is either error prone or very costly. Furthermore, we do not guarantee that the optimizer might either move it to same completely different location or restructure it in later releases of the compiler. Currently it has a rather regular structure, but it is already turned into a binary search if there are many functions in the contract.

If you have specific questions about the compiler, please ask them in `https://gitter.im/ethereum/solidity-dev`.

**Comment by zhjgit** [comment]
@chriseth ok thanks , I can only do function checking under the chain.
