### ISSUE TITLE
Public field in mappings causing revert in a smart contract deployed by another smart contract

### ISSUE THREAD

**Issue by akhila-raju** [ethereum/solidity#7066]
## Description

Adding `public` to a mapping field in a contract that is deployed from another contract leads to a `RuntimeError: VM Exception while processing transaction: revert` error.

In EmptyContract.spec.ts, a NewContract is deployed first. Then, 
```solidity
 newContract.doDeploy()
```
is called, which creates a new EmptyContract. This test passes when `mapping(address => address) public depositContracts` does not contain the word `public`, and otherwise fails. Below are the dummy files I created to reproduce this issue. See [EVM stack trace](https://gist.github.com/akhila-raju/2d66be1f5e930f3897ba35beeb7d8ad1).

## Environment

- Compiler version: 0.5.0
- Target EVM version (as per compiler settings): ethereumjs-vm 2.6.0
- Framework/IDE (e.g. Truffle or Remix): Waffle
- EVM execution environment / backend / blockchain client: Ganache-core 2.5.6-beta.0
- Operating system: MacOS 10.14

## Steps to Reproduce
Deploy the following contracts and run EmptyContract.spec.ts. Note that this uses ethereum-waffle which is dictating the EVM/ganache version that I'm using.

### EmptyContract.spec.ts
```typescript
import chai = require('chai')
import {
  createMockProvider,
  deployContract,
  getWallets,
  solidity,
} from 'ethereum-waffle'
import * as EmptyContract from '../build/EmptyContract.json'
import * as NewContract from '../build/NewContract.json'


chai.use(solidity)
const { expect } = chai

describe.only('Creates EmptyContract and checks that fields are properly assigned', () => {
  const provider = createMockProvider()
  const [wallet] = getWallets(provider)
  let newContract

  it('it deploys', async () => {
    newContract = await deployContract(wallet, NewContract, [], {
      gasLimit: 6700000,
    })
    await newContract.doDeploy();
  })
})
```

### NewContract.sol
```solidity
import { EmptyContract } from "./EmptyContract.sol";

contract NewContract {
  address public authenticationAddress;
  address public commitmentChain;
  mapping(address => address) public depositContracts;
  mapping (bytes32 => uint256)  exitRedeemableAfter;

  uint public id;

  constructor() public {
  }

  function doDeploy() public {
   new EmptyContract();
  }
}
```

### EmptyContract.sol
```solidity
import { CommitmentChain } from "./CommitmentChain.sol";
import { Deposit } from "./Deposit.sol";


contract EmptyContract {
  address public authenticationAddress;
  address public commitmentChain;
  mapping(address => address) depositContracts;
  // mapping (bytes32 => uint256)  exitRedeemableAfter;

  uint public id;
  // mapping(string => string) public metadata;

  constructor() public {
  }
}
```

**Comment by chriseth** [comment]
Thank you for the bug report! The trace ends with a `STOP` an not with a `REVERT` - are you sure it is the right one?

**Comment by akhila-raju** [comment]
No problem! Yes, that was all that was in the trace. I'm not sure why there isn't a `REVERT`.

**Comment by chriseth** [comment]
@akhila-raju please either provide a trace that really is faulty or try to slim down the Solidity code into a single file, then I can try to reproduce it. Thanks!

**Comment by akhila-raju** [comment]
Sure! Here is a single Solidity file:

```solidity
pragma solidity ^0.5.0;

contract EmptyContract {
  address public authenticationAddress;
  address public commitmentChain;
  mapping(address => address) public depositContracts;
}

contract TestContract {
  mapping(address => address) public depositContracts;
  mapping (bytes32 => uint256) public exitRedeemableAfter;

  function doDeploy() public {
   new EmptyContract();
  }
}
```

**Comment by leonardoalt** [comment]
Hi @akhila-raju ,
What exactly should happen with the code above?
I just tried it on Remix and both contracts are successfully deployed.
Also calling `doDeploy` works fine.
