### ISSUE TITLE
[Yul] add types to dialects, but keep a default type

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7070]
Since eWasm has different types, we have to enable the type system in Yul before eWasm can be completed. To make the code better readable, each Yul dialect will have a default type which does not have to be explicitly mentioned. For eWasm this is u64, for EVM it is u256.

The Yul parser, analyzer and printer should all honour types and the analyzer should also check them (#2324).

It is to be discussed whether `bool` should be introduced as a type in the EVM dialect.

It should also be discussed how dialects deal with types for literals.

- [x] check that default types work both in parser and printer
- [x] perform type checking in analysis phase ( https://github.com/ethereum/solidity/issues/2324 )
- [ ] introduce types in optimizer phases (splitter, etc)
  - [ ] ControlFlowSimplifier::reduceSingleCaseSwitch: introduce typed dialect::equalityFunction and ::discardFunction and use. Same for all uses for makeDiscardCall in that file.
  - [x] ExpressionSplitter::outlineExpression needs to determine the type of the expression
  - [ ] ForLoopOutOfBody needs to select the proper negation function depending on the type.
  - [ ] test that FullInliner properly assigns types for new variables (for parameters and return parameters).
  - [ ] ssa transform needs to determine types for assignments.
  - [ ] VarDeclInitializer has to use `false` for bool variables.

**Comment by bshastry** [comment]
>  For eWasm this is u64, for EVM it is u265.

@chriseth I think you meant `u256`

**Comment by chriseth** [comment]
I think a good step here is to modify the AST right after parsing (or during?) by replacing all empty types by the default type. Likewise, during printing, all default types are replaced by the empty type.

**Comment by chriseth** [comment]
@mijovic something similar to the VarDeclInitializer should be done to `InlineModifier::performInline`, line 201. Maybe it could make sense to make "zeroLiteralForType" a virtual function of Dialect.

Please create a new test similar to `test/libyul/yulOptimizerTests/fullInliner/multi_return.yul`, but with evmTyped as dialect and change one of the return variables of the function to `bool`.
