### ISSUE TITLE
Warn about implicit returns

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#708]
As recent events have shown, we need to make Solidity more difficult to be misused or used in ways that can cause bugs.

Granted the following example is contrived, but we really need to consider if the advantages of returning values implicitly by name is worth it.

```
    function foo() returns (uint r) {
        r = 1;
        if (somethingComplexThatReturnsFalse()) {
            return 2;
        }
    }
```

This may be a valid example, and if this feature is really desired, it would still be helpful to explicitly have `return` somewhere.

```
    /// @dev Computes the winning proposal taking all
    /// previous votes into account.
    function winningProposal() constant
            returns (uint winningProposal)
    {
        uint winningVoteCount = 0;
        for (uint p = 0; p < proposals.length; p++) {
            if (proposals[p].voteCount > winningVoteCount) {
                winningVoteCount = proposals[p].voteCount;
                winningProposal = p;
            }
        }
    }
```

My first thought is just to deprecate and remove this feature.
If it's desired, maybe clearer syntax such as  `[return winningProposal = p;]` is possible and can help.
Before we optimize for say features that might save gas, I think we agree to focus first on safety.

**Comment by chriseth** [comment]
We might add that now that we have tuples.
