### ISSUE TITLE
[semantic test] Report concrete reason of invalid encoding to user

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#7082]
When I was adding new semantic tests, I tried to add a test case that contains `0x140` (which is an illegal literal because hex number needs to have even length, for some reason), and the test framework just says `Literal encoding invalid.`, which is not very helpful and confuses me.

It could be useful if it prints more concrete reasons. Also seems like `TestFileParser::parseABITypeLiteral()` is not properly passing (rethrow) error reason to caller?

I can try to fix this when I get time.

**Comment by ekpyron** [comment]
see also #6298

**Comment by erak** [comment]
@sifmelcara I started fixing this and some other issues with https://github.com/ethereum/solidity/pull/7052. Please feel free to comment :)

I also created https://github.com/ethereum/solidity/pull/7091 which fixes this issue.

**Comment by sifmelcara** [comment]
:+1:  Seems like there is a lot of refactoring going on
