### ISSUE TITLE
[Yul] Construct call graph

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7084]
Construct a call-graph (including bulitin functions) of functions (not a control-flow graph!). This can be used for multiple purposes (maybe even in a single BFS search?):

 - https://github.com/ethereum/solidity/issues/7078
 - https://github.com/ethereum/solidity/issues/6866
 - find unused functions that recursively call each other and thus are not removed by the unused pruner

**Comment by Marenz** [comment]
@sifmelcara is working on this issue

**Comment by Marenz** [comment]
Related: https://github.com/ethereum/solidity/pull/7137

**Comment by chriseth** [comment]
Has been implemented in #7230
