### ISSUE TITLE
Should --error-recovery continue on pragma errors? 

### ISSUE THREAD

**Issue by rocky** [ethereum/solidity#7085]
_Note: there have been edits made to try to improve clarity,_
## Abstract

When `--error-recovery` is given in solc, or the equivalent in StandardCompiler, should we continue parsing the Solidity program instead of terminating compilation? 

## Motivation

The error recovery option is intended to report more information back when there are indeed errors. In my experience, mismatched pragmas are very common. 

(If the answer turns out yes, I can handle this if no one else volunteers.)

## Backwards Compatibility

This should be completely backwards compatible.

**Comment by chriseth** [comment]
Can you please clarify: Continue with which program and beyond what point?

**Comment by rocky** [comment]
Suppose my program is this: 

```soidity
pragma solidity 0.5.0;

contract PublicStorageArray {
    bytes32[] public states = [bytes32(0)];
}
```

and I compile using the a compiler other than 0.5.0. I currently get this: 

```
$ solc --error-recovery bad.sol
bad.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.5.10-develop.2019.6.24+commit.33616699.mod.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.5.0;
^--------------------^
```

Often in the past in an IDE setting,  I copy a Solidity program from somewhere and get something like this. 

Wouldn't it be nice if I got more than this one error message? 

As for continuing, one can just assume the current compiler version. More elaborate would be to assume `>0.5.0` if that has an effect on the parsing.

**Comment by chriseth** [comment]
So is this issue just about the pragma or any fatal error outside of the parser?

**Comment by rocky** [comment]
It is no more than what I wrote. 

I gave a specific situation and use case, and in my experience this has been an often enough annoyance in the past to mention it.

It can be simply fixed by having a lack of pragma or a pragma mismatch not be a fatal error, at least when `--error-recovery` is intended. There may be other ways to address, and that's okay too.  

Please feel free to change the title if that helps.

**Comment by chriseth** [comment]
Yep, sounds good!
