### ISSUE TITLE
Allow compilation starting from a Solc AST

### ISSUE THREAD

**Issue by rocky** [ethereum/solidity#7087]
## Abstract

There may be situations where compiling staring from a solcAST is advantageous. 

## Motivation

Here are two potential use cases. The first which is my main motivation for mentioning is that in IDEs where a program is getting developed the expected pattern is many failed compiles as one is developing the program followed by one last full compile. 

For failed compiles, right now I am turning off all optimization, and disabling all output except the AST. It may even be that adding a command-line switch would make "no output after AST" more explicit. 

In the last full compile though optimization and so on are desired. So there might be a small benefit here, in saving time.

However the other use is to allow other kinds of frontends,  preprocessors, language to work that allow people to experiment with solidity without having to write in C++ and work on the Solidity code base.

## Specification

Will be filled in if this moves forward. 

## Backwards Compatibility

This should be completely backwards compatible.

**Comment by chriseth** [comment]
Duplicate: https://github.com/ethereum/solidity/issues/2096

**Comment by chriseth** [comment]
Please feel free to add your motivation there.

**Comment by rocky** [comment]
Good to see that this is already in the queue. I thought I looked but didn't see it when opening this issue. Sorry. 

> Please feel free to add your motivation there.

What's there is sufficient. And that issue links back to this. So I'm good here.
