### ISSUE TITLE
event SomeEvent(ContractType c)  becomes an invalid log entry if fired.

### ISSUE THREAD

**Issue by ethernian** [ethereum/solidity#709]
### Description:

Consider a conract

```
contract FooFactory {
   event NewFoo(Foo foo);
    function createFoo() returns (Foo foo){
        foo = new Foo();
        NewFoo(foo);
    }
}
```

a call to `createFoo()` creates an entry in log like 

```
{ logIndex: '0x00',
  transactionIndex: '0x0',
  transactionHash: '0xfbfd11df8f5bdeda926b516485737caf139b0f3eff3a74b3dda50bf6147953fb',
  blockHash: '0x4fa25c52f80357761a8c491ff31c3c74b59dd7e9120cb0e1486cdee740a45742',
  blockNumber: '0x65',
  address: '0x667cbea674e29efcb90fd5938a61fc8b226a3722',
  data: '0x0000000000000000000000000194013ad981e20f9bb2cd6d4aecbdf95d4485cb',
  topics: [ '0x09cf5831812c5045f6913dec697b94aaf101ab015f2f3e56356ed092df26becd' ],
  type: 'mined' }
```

the event's topic is a result of computation `web3.sha3('NewFoo(address)')` an not `web3.sha3('NewFoo(Foo)')` as expected. You can also see other differences between these two log entries.

If I declare an even like `event NewFoo(address foo);` in the same contract, it produces a log entry as expected:

```
{ logIndex: 0,
  transactionIndex: 0,
  transactionHash: '0x820cb70909b81c536830e32db5fd70873cc481a2839f218bc818db3842e6b5eb',
  blockHash: '0xe5d61b1022acdc46ad99ab4ee63af96155121e68e84bc0b5f1c45c825746170a',
  blockNumber: 95,
  address: '0xe1ec40eccc040f9e48f34871e6f3c1d30b4cc9e5',
  type: 'mined',
  event: 'NewFoo',
  args: { foo: '0xb2dcf81abf338024afaf870f947d9c1716933e05' } }
```

You can find contract code and a running truffle test here:
https://gist.github.com/dip239/8978f4a8315f005d3c5453555916f520
https://gist.github.com/dip239/d87c0ee4b842fc8ddfc8e3f073f4fd37
### Use Case justification:

I would like to use contract declaration like `event NewFoo(Foo foo);` instead of `event NewFoo(address foo);` in order to generate an ABI for `event NewFoo(Foo foo);` and use the ABI to resolve a promise direct to Contract not to address.

**Comment by chriseth** [comment]
The reason is that contracts are not part of the ABI types. The same transformation also applies to function signatures.

Adding custom types to the ABI might be a possibility to consider, but I am not sure if we want to go down that road. You only get (a mild version of) type safety if the full contract is known to web3.js, and I don't see a nice way to provide that in a general context.

**Comment by ethernian** [comment]
What is a feature and what is a bug here? It is not quit clear to me.

I see the `Foo` type is already used in the ABI of the `FooFactory`, created by solidity compiler.
`[{"constant":false,"inputs":[],"name":"createFoo","outputs":[{"name":"foo","type":"address"}],"type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"foo","type":"Foo"}],"name":"NewFoo","type":"event"}]`
is this a feature and not a bug?

The `FooFactory.createFoo()` call creates an log entry with the topic different from the event signature declared in the ABI. 
Is this a feature and not a bug too?

Even this behaviour is intentional, it contradicts at least to solidity documentation, stating that the topic is a sha3 of event signature (as defined in contract or exposed in ABI).

Additionally it is not quite clear why a json entry `event: 'NewFoo',` is missing. Is this an anonymous event? Does the event become anonymous due to ContractType usage in event's signature?

Personlly I find it usefull if ABI string contains ContractTypes. It makes easier for UI-Engine to render correct UI for address or for the contract at that address. If an event could have any string as a topic, I would prefer to have a topic calculated from the event signatur as defined in contract and exposed in ABI, i.e. as `web3.sha3(NewFoo(Foo))`.  If the topic could be any string, why solidity compiler needs to transform the event signature for the topic calculation?

**Comment by chriseth** [comment]
This needs further investigation, I am actually not sure whether it is a bug or a feature. As far as datatypes are concerned, web3.js should not be able to know what `Foo` might be, at least it is not defined in the ABI, but I certainly see the benefit here. The main problem is that contract names are not globally unique as opposed to all the other type names in the ABI.

**Comment by ethernian** [comment]
I see the problem. Thank you.
Let me know if I could contribute to find a solution.

**Comment by axic** [comment]
Currently this uses `address` both for the event and `createFoo` and it seems to decode properly in remix ide:

```
[
  {
    "type":"function"
    "name":"createFoo",
    "payable":false,
    "constant":false,
    "inputs":[
    ],
    "outputs":[
      {
        "name":"foo",
        "type":"address"
      }
    ],
  },
  {
    "type":"event",
    "name":"NewFoo",
    "anonymous":false,
    "inputs":[
      {
        "indexed":false,
        "name":"foo",
        "type":"address"
      }
    ]
  }
]
```

**Comment by axic** [comment]
Is this still a bug?

**Comment by chriseth** [comment]
I don't think so. Closing.
