### ISSUE TITLE
Deployed library bytecode does not match Evm.DeployedBytecode.Object

### ISSUE THREAD

**Issue by seanyoung** [ethereum/solidity#7101]
The Solidity json compiler output includes the fields Evm.DeployedBytecode.Object. For a library, this fields always begins with PUSH20 00 00 00 00 (etc). 

When the contract is actually deployed, this field is populated with the deploy time address(). So the bytes of Deploy Evm.DeployedBytecode.Object do not match with the actual deployed bytecode.

In burrow we want to enforce that contract cannot be created unless they match the DeployedBytecode. This is not working for libraries.

**Comment by chriseth** [comment]
The bytecode of a library is changed at deploy time - it is documented here: https://solidity.readthedocs.io/en/develop/contracts.html#call-protection-for-libraries

**Comment by chriseth** [comment]
Can you explain at which level you want to enforce the matching bytecode and what the reason behind is? Do you want to prevent people messing around with things in the constructor using inline assembly or is there a technical reason for that?

**Comment by seanyoung** [comment]
For each compiled contract, I'm creating a mapping from deployed codehash to abi (more metadata like contract name/source file in the future).
This is for burrow: https://github.com/hyperledger/burrow/pull/1125
By creating this mapping burrow can know the origin of all contracts in the system, and provide meta data like the abi for each contract. 
In addition, this also prevents contracts from deploying code different that what they said they would.

**Comment by seanyoung** [comment]
With a new EVM opcode this could be fixed.

Alternatively, now that this behaviour is documented, does that mean that it's not broken?

**Comment by chriseth** [comment]
The behaviour is intentional, yes. By the way, you do know about the metadata hash being appended to the deployed bytecode, do you? It is an additional indirection, but it also includes the ABI and other information.

**Comment by seanyoung** [comment]
I know this is intentional, I'm just saying it's a terrible design. Steps for fixing:
- Introduce EVM opcode e.g. DEST which returns the destination address for the transaction (so the outer most callee)
- In library code compare ADDRESS to DEST and if equal, revert
- No hack needed to implement "call protection"

**Comment by seanyoung** [comment]
Using the metadata appended to the transaction is not great. This can easily be modified by users to pretend to be something they are not.

**Comment by chriseth** [comment]
@seanyoung let's please not discuss the design of the EVM here. I agree with you, but it is not the right place.

The metadata can be used to recompile the contract and check that the (construction) bytecode matches the source code. How do you enforce in burrow that the user is not deceived?

**Comment by seanyoung** [comment]
What is the right forum for EVM design discusssion?

**Comment by chriseth** [comment]
I think most discussion nowadays happens here: https://ethereum-magicians.org/

**Comment by chriseth** [comment]
With immutables, this problem gets worse and cannot really be fixed.
