### ISSUE TITLE
Solidity compiler output does not say library or not

### ISSUE THREAD

**Issue by seanyoung** [ethereum/solidity#7102]
There is nothing in the Solidity json output which says whether or not a contract is a library or not. This would be useful to know whether the contract needs runtime ABIs or to work around #7101.

**Comment by chriseth** [comment]
That's a good idea! Do you think this should already belong into the ABI or into e.g. `contracts["sourceFile.sol"]["MyLibrary"]["contractKind"] = "library"`?

**Comment by seanyoung** [comment]
I'd like to see more meta data in the ABIs, like contract name, source file, and contract kind.

**Comment by Marenz** [comment]
So you would like to see something like this?

```
pragma solidity >=0.5.0 <0.7.0;

contract Test {
    constructor() public { b = hex"12345678901234567890123456789012"; }
    event Event(uint indexed a, bytes32 b);
    event Event2(uint indexed a, bytes32 b);
    function foo(uint a) public { emit Event(a, b); }
    bytes32 b;
}
```
would result in the JSON:
```
[{
"type":"event",
"inputs": [{"name":"a","type":"uint256","indexed":true},{"name":"b","type":"bytes32","indexed":false}],
"name":"Event",
"library": "false",
"contractName": "Test",
"sourceFile: "test.sol"
}, {
"type":"event",
"inputs": [{"name":"a","type":"uint256","indexed":true},{"name":"b","type":"bytes32","indexed":false}],
"name":"Event2",
"library": "false",
"contractName": "Test",
"sourceFile: "test.sol"
}, {
"type":"function",
"inputs": [{"name":"a","type":"uint256"}],
"name":"foo",
"outputs": [],
"library": "false",
"contractName": "Test",
"sourceFile: "test.sol"
}]
```

@ekpyron mentions that the `abi` field is very solidity agnostic and maybe shouldn't contain such programming-language specific details.

The alternative would be what @chriseth suggested or to put it in the `metadata` object.

**Comment by seanyoung** [comment]
To be fair this looks messy. Maybe it does belong in the metadata object.

**Comment by Marenz** [comment]
As name and file are already in the json that would mean I simply add a new field containing the library info in the metadata, maybe like this?

`contracts["sourceFile.sol"]["MyLibrary"]["metadata"]["library"] = "true"`

**Comment by ekpyron** [comment]
I think we should stick to ``contractKind`` being ``contract`` or ``library`` - that's what we do in the JSON AST and it's more future-proof.

**Comment by ekpyron** [comment]
We now closed the PR for this, since we think that this information belongs in the json AST (where it already can be found). Otherwise we need a clear criterion for which information from the AST should be replicated in the metadata. If you see any hard disadvantages for referring this to the AST, please comment!
