### ISSUE TITLE
Solidity compiler output does not say what contracts a contract can create 

### ISSUE THREAD

**Issue by seanyoung** [ethereum/solidity#7111]
I'm trying to create a mapping from contract to metadata (via codehash but metadata hash is also possible). It would be useful to know what contracts a contract can create; simply a list of names should suffice.

`contracts["sourceFile.sol"]["MyContract"]["creates"] = [ "foo", "bar" ]`

**Comment by chriseth** [comment]
What is the exact use-case, and how is "a contract creates another contract" defined?

**Comment by seanyoung** [comment]
@chriseth yes, you are right -- this needs further explaining.

Consider this solidity source file:
```
contract A {
	function createB() public returns (B) {
		return new B();
	}

	function createC() public returns (C) {
		return new C();
	}
}

contract B {
	uint public n;
}

contract C {
	uint public k;
}

contract D {
        uint public d;
}
```
Now when I compile this I would like to know that contract A can create B and C (not D), and that B, C, D do not create any contracts.

The reason I would like this so that I can track metadata for contracts. When contract A executes a CREATE/CREATE2 opcode, I can match the bytecode against the Evm.DeployedBytecode.Object from contract B or C, and figure out which contract it has created. In this way burrow can know which contract the created contract is (B or C), and we can serve metadata like ABI for the contract.

At the moment we're collecting all the DeployedBytecode for all the contracts in the output of the solidity  compiler. This is fragile in several ways; for example in the above case we do not know that D can never be created.

Hope that helps please let me know if I should elaborate further. Thanks

**Comment by chriseth** [comment]
At the time of creation, you can take a look at the metadata ("compilationTarget") and it will tell you which contract is just being created. Would that help?

**Comment by seanyoung** [comment]
I would like to know ahead-of-time (compile-time) what contracts could possibly be created. Then I can register the metadata for those contracts before the time of creation, so that the metadata is ready and available for them when the create happens.

**Comment by chriseth** [comment]
If you do that off-chain anyway, why not just register everything that gets compiled?

**Comment by seanyoung** [comment]
First of all,  it would be great to able to restrict contract creation to exactly the set that contract can create, and nothing more. In burrow we CREATE and CREATE2 can fail now if the bytecode does not match: see https://github.com/hyperledger/burrow/blob/3287fd37cc6c77a41a294a365320ffe8857576ea/execution/evm/state.go#L240

Secondly, please bare with me while I go through the issue we are having. Take this soliidity source:

```
library LIB {
	function ans() public returns (uint) {
		return 42;
	}
}

contract C {
	function getAnswer() public returns (uint) {
		return LIB.ans();
	}
}
```
Say we want deploy LIB. When we compile this, we get two entires Evm.DeployedBytecode. We don't know if LIB creates C or not; however C has unresolved symbols. So off-chain when we deploy LIB, we try to resolve the symbols in all the deployedbytecode entries, and fail. So, we can guess that LIB probably does not create C, but it would be nice to that for sure rather than take an educated guess.

**Comment by cameel** [comment]
Does the `contractDependencies` annotation in the AST solve this problem? After  #9565/#10228 it includes all contracts that might be created (though it might also include other contracts whose bytecode had to be embedded in the main contract for other reasons).
