### ISSUE TITLE
Logging state variables in constructor prevents deployment

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#7113]
## Description

Passing a state variable to an event in contact constructor prevents contract deployment.

## Environment

- Compiler version: 0.5.10
- Target EVM version (as per compiler settings): byzantium
- Framework/IDE (e.g. Truffle or Remix): dapp / none
- EVM execution environment / backend / blockchain client: MIX Blockchain
- Operating system: Linux

## Steps to Reproduce

https://github.com/mix-blockchain/mix-account/blob/4dfdbcde79787465c88f6c017326c036ffc74119/src/MixAccount.sol#L81

```
dapp build --extract
```

Then try to deploy MixAccount.bin - it is reverted by the EVM.

Changing that line to
```
emit SetController(msg.sender);
```
fixed the problem.

Triggering code:
```
    address payable controller;

    event SetController(address controller);

    constructor() public {
        // Store the controller.
        controller = msg.sender;
        // Log the event.
        emit SetController(controller);
    }
```

**Comment by chriseth** [comment]
Can you use a debugger to see where exactly it fails? It looks to me like the execution environment you are using does not support the EVM version set in the compiler.

**Comment by ethernomad** [comment]
Can you point me in the direction of how to debug this? It only fails on the blockchain.

When I run the tests in Hevm it works fine: https://dapp.tools/hevm/

Here is the blockchain config:
https://github.com/mix-blockchain/mix-blockchain/blob/master/mix.json
So it is byzantium EVM and I compile the contract for byzantium.

This deployment reversion does not cause a chain split between Geth and Parity.

**Comment by chriseth** [comment]
You can debug it by analyzing the trace. There are multiple debugging tools out there.

**Comment by chriseth** [comment]
Please reopen if you can find more details about the failure.
