### ISSUE TITLE
Make EVMC/EVMONE tests work on appveyor

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7115]

**Comment by chriseth** [comment]
I think we should make the tests work on windows in general and then look at moving from appveyor to circleci.

**Comment by christianparpart** [comment]
@chriseth I think this ticket can be closed as soon as https://github.com/ethereum/solidity/pull/9476 is merged, because it also makes sure EVMONE is being downloaded & used when running soltest.

**Comment by ekpyron** [comment]
True, no longer an issue!
