### ISSUE TITLE
Define side-effect-free-ness

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7118]
We need the concept of side-effect-free-ness for several use-cases:

 - enforce side-effect-free-ness in expressions for invariants and other verification uses
 - warn about side-effect-free expression statements
 - warn about multiple expressions with side-effects in the same statement where the order of execution is not totally obvious

These three concepts of side-effect-free-ness might be different. They are all different from pure-ness, because pure expression can have side-effects on memory.

Also, the concepts of side-effect-free-ness above do not have to mean that the expressions have zero effects on memory: Allocating a new memory array could be considered side-effect-free, but maybe this could be better handled in a lifetime or usage tracking module.

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/2707

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/1380

**Comment by ekpyron** [comment]
Actually, this is also related: https://github.com/ethereum/solidity/issues/2691#issuecomment-517326454 - if we warn about *all* (i.e. also non-pure) side-effect-free statements that workaround won't work anymore. Put differently: is changing the strictest state-mutability another kind of side-effect or not?
