### ISSUE TITLE
[Testing] Discussion about test case checked in for msize optimization

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7125]
## Description

This issue discusses the test case checked in by PR #7106 

https://github.com/ethereum/solidity/blob/a0a0a34a21072a61fc6e1732833fb18fc9bec0f8/test/libyul/yulOptimizerTests/stackCompressor/unusedPrunerWithMSize.yul#L1-L20

This test case does not demonstrate a difference in yul execution traces between unoptimized and optimized versions.

Reproduction:

```
$ cd solidity
// One commit hash before the referenced PR was merged into develop
$ git checkout dd031ed
$ mkdir build && cd build
$ cmake ..
$ make solc yulrun
```

Trace of unoptimized test case is
```
$ yulrun --input-file <path_to_testcase>.yul
Trace:
  EXTCODECOPY(1, 32, 1, 1)
Memory dump:
     0: 0000000000000000000000000000000000000000000000000000000000000001
    20: 6f00000000000000000000000000000000000000000000000000000000000000
Storage dump:
```

Let's optimize the test case using solc
```
$ solc --strict-assembly --optimize <path_to_test_case>.yul
...
    code {
        {
            let _1 := pc()
            let _2 := pc()
            let _3 := pc()
            let _4 := pc()
            let _5 := pc()
            pop(keccak256(1, 2))
            let _6 := not(0)
            mstore(lt(or(gt(1, or(or(gt(or(or(or(gt(or(gt(_6, _5), 1), 
_4), lt(or(1, add(_3, _6)), 1)), _2), 1), 1), gt(not(_1), 1)), 1)), 1),
 1), 1)
            extcodecopy(1, msize(), 1, 1)
        }
    }
...
```

Now, let's trace the optimized yul code above.

```
$ yulrun --input-file <optimized_yul_code>.yul
Trace:
  EXTCODECOPY(1, 32, 1, 1)
Memory dump:
     0: 0000000000000000000000000000000000000000000000000000000000000001
    20: 6f00000000000000000000000000000000000000000000000000000000000000
Storage dump:
```

The two traces match and hence the checked in test case passes on the unpatched version of UnunsedPruner.

**Comment by chriseth** [comment]
OK, I think I can explain this: If you run the full optimizer suite, it will inline the function before it runs the stack compressor. For the bug to be triggered, the `msize` instruction needs to be inside a function and the memory-size-modifying instruction needs to be outside of that function.

The test case, though, directly runs the stack compressor without first running the other steps. Because of that, the test fails without the fix.

If you want, I can still add the full test.

**Comment by bshastry** [comment]
Ah I see. Thanks for the clarification. It may still be nice to add the full test to `test/libyul/yulOptimizerTests/fullSuite` so that we catch potential regressions in the full suite.
