### ISSUE TITLE
[Testing] Implement abiv2 testing with holes for efficiency

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7127]
## Abstract

At the moment, the abiv2 proto converter initializes all array elements and resizes every dynamic dimension.

For larger dimensional arrays, this leads to large test programs some of which take several minutes to execute on evmone.

This issue tracks support in the abiv2 converter for pseudo randomly resizing dynamic array elements and initializing array indices. We gain efficiency at the cost an inextensive check of abiv2 coder.

The hope is that this will still find issues eventually. Arguably, it is better to run quick inextensive tests than potentially exponentially slow extensive tests.

Simple example:

```
// Current version
int8 x[3];
x[0] = 1;
x[1] = 2;
x[2] = 3;

// checks
if (x[0] != 1) return 1;
if (x[1] != 2) return 2;
if (x[2] != 3) return 3;
if (x.length != 3) return 4;

// Future version
// saves four statements but performs inexhaustive check.
x[2] = 3;
if (x[2] != 3) return 1;
if (x.length != 3) return 2;
```

## Motivation

Pseudo-randomly initializing array elements is a simpler problem for which something like the following may be proposed.

We define a constant `k` and define an array index only if the current value of the monotonic counter in the converter is divisble by `k` (i.e., `counter mod k == 0`)

I don't have a solution for pseudo-random resize of dynamic arrays. One issue I am pondering over is how to pseudo randomly resize and initialize and array like this

```
// Dimensions 1,2,4 are dynamic
// Dimensions 3,5 are static
int8 x[][][2][][10];
```

TBD

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 
Closing this issue for the same reason as #7151.
