### ISSUE TITLE
abi.decode to accept types as parameter and output as struct

### ISSUE THREAD

**Issue by thegostep** [ethereum/solidity#7134]
## Abstract

With AbiEncoderV2 around the corner, it would be great to be able to pass in a template of types as a parameter to the abi.decode() function and have it output a struct with the desired shape.

```
function sample(bytes input) public returns (address outputA, uint256 outputB) {
    (outputA, outputB) = abi.decode(input, (address, uint256);
}
```

Becomes

```
template = '(address outputA, uint256 outputB)'

function sample(bytes input, string template) public returns (struct output) {
    output = abi.decode(input, template);
}

output => {
    address outputA;
    uint256 outputB;
}
```

## Motivation

This allows for using abi.encode and abi.decode for encoding arbitrary data without specifying hardcoded types.

## Specification

unknown

## Backwards Compatibility

unknown

**Comment by leonardoalt** [comment]
I like the general idea, but why not simply ask to decode into a struct?
Example:
```
    struct S { uint x; address a; }
    function f(bytes memory data) public {
        (S memory s) = abi.decode(data, (S));
    }
```

**Comment by leonardoalt** [comment]
Answering my own question:
I guess what you're also interested in is passing this template at runtime instead of compile time?
In that case, wouldn't that break/make the ABI ambiguous?

**Comment by thegostep** [comment]
My use case was for creating a registry which serves as a generic factory for arbitrary contracts. I ended up moving away from the generic factory and instead resolved to adding custom factories which can have ABI decoding template in the code.

The ability to decode into a struct would be great. Perhaps providing a template at runtime may be used in other use cases.

**Comment by chriseth** [comment]
If I understand you correctly, this is either about templates or about dynamic types. There is another issue that proposes to implement templates ( https://github.com/ethereum/solidity/issues/869 ) and dynamic types is against the core design of Solidity, so I'm closing this. Please reopen if I misunderstood you.
