### ISSUE TITLE
Member-access to `msg.sender` should be pure

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7135]
As pointed out by @nventuro, the following code may warn about `a()`'s function mutability to be restricted to pure:
```
pragma solidity ^0.5.10;

contract Test {
    function a() internal view returns (address) {
        return msg.sender;
    }

    function b() internal pure returns (bytes memory) {
        return msg.data;
    }
}
```

**Comment by leonardoalt** [comment]
Shouldn't it rather be `view`?

**Comment by leonardoalt** [comment]
Ok I just read the discussion on Gitter.

**Comment by chriseth** [comment]
The `caller` opcode cannot be used in staticcall context. So the behaviour of the view-pure checker is correct. We should document it though, and add a test (with comment).

**Comment by ekpyron** [comment]
But if it can't be used in staticcall context, shouldn't it even be non-view? Also: for me at least in remix using ``msg.sender`` or the ``caller()`` opcode does seem to work during a staticcall...

**Comment by chriseth** [comment]
I got something wrong there, staticcall only disallows CREATE, CREATE2, LOG0, LOG1, LOG2, LOG3, LOG4, SSTORE, SELFDESTRUCT and CALL with a non-zero value.

It is an opcode we consider invalid in pure functions, though.

**Comment by chriseth** [comment]
The PR for the opcodes: https://github.com/ethereum/solidity/pull/2848

Also I really think `msg.sender` should not be pure. Pure means that the result is exactly the same regardless of the environment. The environment is something you cannot easily change and you cannot easily change the sender. This is different from actual function arguments which you can replicate at will.

**Comment by ekpyron** [comment]
Yeah, the only way to justify ``msg.sender`` being ``pure`` would be to consider it an implicit function argument - I'd tend not to do that as well, but I'm not sure what other arguments @nventuro had during the original Gitter discussion...

**Comment by chriseth** [comment]
Please reopen if there is a need for further discussion.

**Comment by nventuro** [comment]
For reference, what I was originally pointing out is that `sender` being `view` and `data` `pure` surprised me: both are transaction parameters, so them having the same mutability (along with e.g. `msg.value`) made a lot of sense in my mind, regardless of whether that's `pure` or `view`.
