### ISSUE TITLE
List candidates for failed overload function resolution.

### ISSUE THREAD

**Issue by thegostep** [ethereum/solidity#7146]
## Description

The following TypeError is produced since the function `burn()` does not have any return values. This error description could be replaced with something like 'require statement expects a reachable value'.

```
TypeError: No matching declaration found after argument-dependent lookup.
        require(ERC20Burnable(_token).burn(amountToBurn), "token transfer failed");
        ^-----^
```

## Environment

- Compiler version: 0.5.10

## Steps to Reproduce

See above

**Comment by chriseth** [comment]
As a fix, we might list all visible candidate functions.
