### ISSUE TITLE
[yul] interpreter fails assertion because of incorrectly erased shadowed variable?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7148]
## Description

Found by ossfuzz: issue 16063

```
{function mr(){let r}{{mr()}function r(){}}}
```

fails 

https://github.com/ethereum/solidity/blob/00accd9daab8acf1e0bd2b0f32af1f2e4ed02d38/test/tools/yulInterpreter/Interpreter.cpp#L200

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg

## Steps to Reproduce

```
$ yulrun --input-file <code.yul>
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<langutil::InternalCompilerError>'
  what():  
Aborted (core dumped)
```

Could be a regression of #6446

**Comment by bshastry** [comment]
Quoting https://github.com/ethereum/solidity/pull/6456#issuecomment-479955970

> Shadowing is disallowed, i.e. you cannot declare an identifier at a point where another identifier with the same name is also visible, even if it is not accessible.
Inside functions, it is not possible to access a variable that was declared outside of that function.

> Visible means "defined in the same block as the function (or a common parent block)". Accessible means "visible and reaching to it does not cross function boundaries".

I think what is happening is that at the time we register variable `r` inside function `mr`, function `r` is incorrectly unregistered. So I think the fix is to register functions not just in the current block but everywhere in the program.

**Comment by bshastry** [comment]
Reduced the buggy test case to the following:

```
{
  function f()
  {
    // Variable declaration does not shadow namesake function declaration
    // because latter not visible here.
    let shadow_id
  }
  {
    // Function named `shadow_id` is in scope now.
    // Before exiting `f()`, we should remove variable named `shadow_id` from current scope.
    // If we do so, we also remove identically named function.
    // See: https://github.com/ethereum/solidity/blob/7c880a26c021fa949f400c9ce5b02a05756bc2a7/test/tools/yulInterpreter/Interpreter.cpp#L175
    f()
    function shadow_id() {}
  }
}
```

I'm not sure whether this is a yul interpreter or an asm parser/analyzer bug. `solc` generates code for the snippet above but yul interpreter fails to run code.

**Comment by Marenz** [comment]
From what I can tell this is a `yulInterpreter` bug.

The problem is that we pass the [scope of the caller to the called function](https://github.com/ethereum/solidity/blob/develop/test/tools/yulInterpreter/Interpreter.cpp#L251) which is wrong. We need to give it the scope of the called function.. not sure yet where to get that from. Looking into that now.
