### ISSUE TITLE
Default fo IPFS for the metadata hash.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7158]
Follow-up of https://github.com/ethereum/solidity/issues/5064

**Comment by leonardoalt** [comment]
What about long instances (`>= 1024 * 256`)?

**Comment by leonardoalt** [comment]
Hm, I guess the metadata won't be larger than that anyway.

**Comment by chriseth** [comment]
We should still try to implement it.

**Comment by leonardoalt** [comment]
Implemented in https://github.com/ethereum/solidity/pull/7377#
