### ISSUE TITLE
Support constant integers for specifying array lengths

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/solidity#716]
```
const uint8 NUM = 5;
uint[NUM] listWithFixedLength;
```

otherwise I have to change that number 5 in all X places in my  sourcecode manually.

To use the existing `constant` keyword as `uint8 constant NUM = 5;` does not help, it results in:

```
Error: Invalid array length, expected integer literal.
```

Is there a different way to achieve the same?

If not, please extend solidity with this small improvement, thanks.

**Comment by drandreaskrueger** [comment]
There was a suggestion how to do it in gitter: [July 12, 2016 4:59 PM](https://gitter.im/ethereum/solidity?at=578505c1064f828707211e8e)

**Comment by chriseth** [comment]
Of course, constant integers should be usable as array lengths. If I remember correctly, we already have a story for that either in pivotal tracker or here in github issues.

**Comment by axic** [comment]
Originally tracked in Pivotaltracker: https://www.pivotaltracker.com/story/show/101777510

**Comment by axic** [comment]
I think `libsolidity/analysis/ConstantEvaluator` should be extended to support `IntegerType`.

**Comment by attente** [comment]
Hi, I'm wondering, does it make any sense to allow using cross-contract constants in this manner? i.e., something akin to:

A.sol:

```pragma solidity ^0.4.19;

contract A {
  uint public constant N = 42;
}
```

B.sol:

```pragma solidity ^0.4.19;

import './A.sol';

contract B {
  uint[A.N] a;
}
```

Thanks!

**Comment by chriseth** [comment]
Yes, there is another issue tracking cross-contract constant references.

**Comment by chriseth** [comment]
Here: https://github.com/ethereum/solidity/issues/1290

**Comment by drandreaskrueger** [comment]
Did I ever say thank you?

Here you go: Thank you! Well done.
