### ISSUE TITLE
[Abiv2 proto fuzzer] Add constructor to test template

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7166]
## Abstract

Presently, the ABIv2 test template does not contain a constructor. This issue tracks support for adding one with the following structure:

```
constructor() {
  // Initialize state variables
}
```

This does not yet test ABI coding with the constructor because the abi proto fuzzer does not yet support ABI encoding itself.

## Motivation

Adding the constructor should be straight forward. We would need to move initializations of state variables to the `constructor` function instead of the `test` function.

**Comment by chriseth** [comment]
What would be the benefit?

**Comment by bshastry** [comment]
@chriseth After thinking about this for a little longer, I don't see any benefit unless the constructor accepts external arguments. If it does, we can test abi coding in the constructor. Actually, my motivation for this was #6754

**Comment by chriseth** [comment]
We should indeed fuzz constructor argument decoding, including passing on arguments to base constructors.
