### ISSUE TITLE
Formal specification of Solidity

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#717]
As the wider community engages, including researchers and academics, a formal spec of Solidity would help them.  Granted many developments are happening so the practical value of this may not be there, and this is a suggestion / reminder.

**Comment by chriseth** [comment]
Are you talking about a formal specification or a formal, machine-readable specification?
A full formal specification might be a side-effect of our current efforts in creating a translator to why3, at least starting from an annotated AST.

**Comment by ethers** [comment]
The former (machine-readable isn't needed).

**Comment by NicolaiSoeborg** [comment]
[grammar.txt](https://github.com/ethereum/solidity/blob/develop/libsolidity/grammar.txt) contains some spec. I have made a PR with a few fixes ([#722](https://github.com/ethereum/solidity/pull/722)), but still have some way to go.

**Comment by chriseth** [comment]
The grammar only provides some kind of formal specification for the mapping from the raw input to the (non-annotated) AST. The why3 translator currently "generates" a specification for the mapping from the annotated AST to the "mathematical meaning" and I think that this specification is much more important. But the grammar.txt file certainly also needs some love. Thanks for the pr, @NicolaiSoeborg !

**Comment by axic** [comment]
There is also a parser by @tcoulter  based on PEG.js: https://github.com/ConsenSys/solidity-parser

It has the definitions here: https://github.com/ConsenSys/solidity-parser/blob/master/solidity.pegjs

**Comment by pirapira** [comment]
I try to list the missing pieces.  For each point I would write an executable code in a proof assistant.
- statics
  - [ ] #892 specify the grammar in BNF
  - [ ] specify the grammar containing multiple Solidity files
  - [ ] specify the contract name lookup rules
  - [ ] specify the function name lookup rules
  - [ ] specify the variable name lookup rules
    - A inherits B and C.  Both B and C inherit D.  Does A contain two state variables for one state variable in D?
  - [ ] specify the modifier name lookup rules
  - [ ] specify the accessibility conditions around inheritance
    - when a variable is not `public` what can read/write it
  - [ ] specify the classification of expressions (expressions that only contain numeric literals and unary/binary operators; expressions without side-effects of what type; expressions with side-effects of what type)
  - [ ] specify the typing rules
  - [ ] specify the modifier application rules as program transformation
- dynamics
  - [ ] specify the control flow (I suggest doing this one just after #892 )
    - Something like `{ [here] a; b }` can transition into `{a; [here] b}` and then `{a; b; [here]}`
  - [ ] specify the execution environment
  - [ ] decide the type of the evaluation of expressions
    - Something like "the input is an expression and an environment, and the output is a value and an environment, or an error"
  - [ ] decide the type of the evaluation of sentences
    - Something like "the input is a sentence and an environment, and the output is an environment, or an error"
  - [ ] decide the type of the evaluation of a function invocation
    - Something like "the input is a function, an environment and arguments, and the output is an environment and return values, or an error"
  - [ ] decide the type of the evaluation of a contract invocation
    - Something like "the input is a message, a block, and an environment with empty volatile parts; and the output is a return byte sequence and an environment, or an error.
  - [ ] specify the evaluation of expressions
  - [ ] specify the evaluation of sentences
  - [ ] specify the evaluation of function invocations
  - [ ] specify the evaluation of contract invocations

After doing these, a Solidity interpreter appears, so we have to test it.
- [ ] test the specification against the Solidity compiler + EVM

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it in favour of #12739 .
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
