### ISSUE TITLE
[DOCS] Italian Translation

### ISSUE THREAD

**Issue by damianoazzolini** [ethereum/solidity#7183]
Hi. I've started to translate the documentation in italian. By now i think i'm somewhere between 60% and 70% of the process. It is possible to add it later to Read the Docs? 
More importantly, if someone italian speaking wants to contribute, there is a file called ``docs/progress.txt`` where i track the state of the translation. Moreover, proofreading is needed.

The translation is in my own fork https://github.com/damianoazzolini/solidity 
The last commit of the english version is 4fa7800

---

This issue is to track the progress of the Italian translation of the Solidity documentation.

It includes the GitHub usernames of all involved, and links to any issues or pull requests related to the Italian translation.

All translation efforts in progress from this date are pinned to commit 
https://github.com/ethereum/solidity/commit/4fa7800

## Contributors

Based on comments in pull requests and issues, and other conversations. If you also want to be involved, please comment below.

@damianoazzolini @V0nMis3s

## Fork

https://github.com/damianoazzolini/solidity

**Comment by ChrisChinchilla** [comment]
Sorry, I missed this @damianoazzolini will sort out adding it now

**Comment by ChrisChinchilla** [comment]
@damianoazzolini I am OK with rendering partial translations with Read the Docs, but would you rather wait?

**Comment by damianoazzolini** [comment]
Ok, however is still a work in progress (i havent't done any progress since the pull request) and would be nice if someone helps and checks possible typos

**Comment by ChrisChinchilla** [comment]
@damianoazzolini Is there a community you/I can post in to try and get some people to review? I can do some, but not sure how many Italian speakers there are in there.

**Comment by damianoazzolini** [comment]
@ChrisChinchilla i'm not aware of a community where i can post it...

**Comment by V0nMis3s** [comment]
@damianoazzolini you should take a look into the "Ethereum Italia Sviluppo" channel on Telegram. 
Btw, I'd be available to help you in completing the Italian translation. Let me know how we can cooperate in this task.

**Comment by damianoazzolini** [comment]
@V0nMis3s awsome! you can create a pull request in my own fork. The file that tracks the progress is  doc/progress.txt. Just simply add the part you want to translate. And it you find someone else, even better!

**Comment by ChrisChinchilla** [comment]
Ok great everyone! I'll list this in the main documentation for now, and please let me know when you get  something ready to be fed into Read the Docs.

**Comment by franzihei** [comment]
We are currently working on a new, hopefully more structured workflow for the Solidity docs translations. I will ping you once this is ready. Closing this issue for now, you can track the progress of the new process etc. in issue #10119.
