### ISSUE TITLE
Docstring bugs or enhancements

### ISSUE THREAD

**Issue by rocky** [ethereum/solidity#7190]
## Description

* Docstring errors don't have locations reported in them.
* We stop at the first docstring error even when we have `--error-recovery`

This misfeature has increased visibility because any docstring generator in an IDE probably trigger this because the parameter names will be filled out but the descriptions are likely to be blank.

## Environment

- Compiler version:0.5.10+commit.5a6ea5b1.Emscripten.clang
- Operating system: ubuntu bionic

## Steps to Reproduce

```solidity
pragma solidity >=0.4.0 <0.7.0;

/** @title Shape calculator. */
contract ShapeCalculator {
    /**
      * @param w
      * @param h
      */
    function rectangle(uint w, uint h) public pure returns (uint s, uint p) {
        s = w * h;
        p = 2 * (w + h);
    }
}
```

compiling produces: 
```
$ solcjs --error-recovery --abi docerr.sol 
DocstringParsingError: No description given for param w
```

I expect something like: 

```
docerr.sol:7:9: DocstringParserError: No description given for param w
       * @param w
                ^
       * @param h 
                ^
docerr.sol:8:9: DocstringParserError: No description given for param h
```

**Comment by rocky** [comment]
If no one else is up for this, I can look at this. (The usual caveats apply though.)

**Comment by axic** [comment]
This is still a problem, no source location is included with most errors in `libsolidity/parsing/DocStringParser.cpp`.

cc @hrkrshnn

**Comment by hrkrshnn** [comment]
@axic There is an issue about including source locations: https://github.com/ethereum/solidity/issues/8247

**Comment by axic** [comment]
Closing this in favour of #8247 then.
