### ISSUE TITLE
Add piet to link list

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7194]
Add https://piet.slock.it/ to the list of tools in docs/index.rst

**Comment by hellraiserinchief** [comment]
Hi, as my first contribution I would like to add this to the documentation. Should I add it below the paragraph where Remix IDE is mentioned. If not then can you point me to where I should add this.

**Comment by chriseth** [comment]
Great! Please add it here: https://solidity.readthedocs.io/en/v0.5.12/resources.html#solidity-tools

**Comment by hellraiserinchief** [comment]
Submitting the PR #7541 
Kindly review

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/7590
