### ISSUE TITLE
[isoltest] Default formatting for returned values should be hexadecimal

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7195]
The following semantic test shows this issue:

```
contract C {
    function f() public returns (T[2] memory) {
        return [T(23, 42, "any"), T(555, 666, "any")];
    }
}
// ----
// f() ->
```
and prints the obtained result using a decimal formatting:
```
  Obtained result:
  // f() -> 32, 64, 224, 23, 42, 96, 3, 44069534601010423606684885868989209141848849940057320670242276538071602167808, 555, 666, 96, 3, 44069534601010423606684885868989209141848849940057320670242276538071602167808

```
It should be hexadecimal:
```
  Obtained result:
  // f() -> 0x20, 0x40, 0xE0, 0x17, 0x2A, 0x60, 0x3, 0x616E790000000000000000000000000000000000000000000000000000000000, 0x22B, 0x29A, 0x60, 0x3, 0x616E790000000000000000000000000000000000000000000000000000000000
```

In conjunction with https://github.com/ethereum/solidity/issues/7028: isoltest could also check, if an alignment can be applied

**Comment by chriseth** [comment]
Maybe just use hex for large values or if the value ends in at least one hex zero nibble?

**Comment by chriseth** [comment]
I think the default formatting should be hex if there are more zeros in the hex output and decimal if there are more zeros in decimal. Unless the number ends it at least two zeros, it should still be decimal.

**Comment by a3d4** [comment]
We could compare [Shannon entropy](https://rosettacode.org/wiki/Entropy) of decimal and hexadecimal representations. So `F0F0` would be preferred to `61680`, for instance.
