### ISSUE TITLE
Properly document ABI decoding (especially V2 wrt padding of bytes)

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7200]
Related (among maybe others) to https://github.com/ethereum/solidity/issues/7180 and https://github.com/ethereum/solidity/pull/7178#discussion_r311959979 and https://github.com/ethereum/solidity/issues/6978.

I think we currently don't enforce ``bytes`` to be padded while decoding. On the other hand we do enforce struct members to be padded in the end.

Should the decoder be *that* strict here? If so we need to fix this and @bshastry can roll back the fuzzing changes ensuring that invalid encoding lengths are in fact shorter than missing padding.

**Comment by ekpyron** [comment]
Gitter discussion: we tend not to enforce padding at the end of ``bytes``.
We should (1) document this behaviour and (2) think about other cases like whether to enforce padding at the end of structs or not (~~EDIT: not sure that applies, since we pad everything to the left anyways, so for struct members padding has to be there anyways~~)

**Comment by ekpyron** [comment]
Ok, so what we currently have and will still allow is unpadded ``bytes``, i.e. for
``function f(bytes calldata x) external`` the byte sequence ``0x00...20 0x00...03 0x42 0x43 0x44`` (where both ```...``` are 30 zero bytes) **is** a valid encoding (and we don't force you to append 29 zeros to it).

But: what about ``bytesXX`` at the end of a tuple and at the end of structs?

So for
``function f(bytes1 x) external``
is ``0x42`` a valid encoding or do we require ``0x4200..``?
Padding could only be skipped for the very last argument in the argument tuple, making it a bit of a hassle *not* to enforce padding here. And here we definitely want to enforce that *if* padding is present that it's zero (which we currently do already I think). Analog for structs:
``struct S { bytes1 x; } function f(S x) external``

It may be a bit inconsistent that way, but I tend to enforce padding for all value types, so even for the last member of a struct or the last argument of a function. But I'd still allow unpadded ``bytes`` arrays...

**Comment by chriseth** [comment]
I think requiring padding to 32-byte value types and not requiring padding for `bytes` and `string` is what would be expected.

**Comment by ekpyron** [comment]
Ok, so I think that's what the code actually does right now anyways - so I'm re-purposing this issue to properly document all this.

**Comment by ekpyron** [comment]
Or actually I'm closing it in favour of https://github.com/ethereum/solidity/issues/6978.
