### ISSUE TITLE
Switch ASAN build to clang (fixing the detected errors).

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7211]
I tried to switch our asan builds to clang in https://github.com/ethereum/solidity/pull/7206, but this triggered asan errors. I think they might be false positives, but we should look into this.
I think it's the same ones as reported in https://github.com/ethereum/solidity/issues/6870.
It's a double free of a ``yul::Block`` that was supposedly allocated by ``Scanner::reset`` (which definitely doesn't allocate ``yul::Block``s).

**Comment by ekpyron** [comment]
Since the results seem to differ we might consider having two runs, one gcc asan and one clang asan run, instead of just switching to clang...

**Comment by ekpyron** [comment]
This will also interact with using the static z3 build in our CI which might cause problems with a clang build due to the OpenMP implementation.

**Comment by axic** [comment]
@ekpyron is this issue still open?

**Comment by ekpyron** [comment]
Probably?

**Comment by cameel** [comment]
This still needs to be done. Unless we think it's not important enough but they we can always just close this issue explicitly.
