### ISSUE TITLE
`Expression has to be an lvalue` message could be more clear

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#7215]
```
contract C {
	function f(uint x) external {
		x = 0;
	}
}

lvalue.sol:5:3: Error: Expression has to be an lvalue.
		x = 0;
```
Here `x` is not an lvalue because it's in calldata.
Even though `external` is there, this might not be super clear to everyone since `uint` is a value type and does not require the keyword `calldata`.

Opening the issue to get a feeling whether the message should be improved.

Brought up by @LianaHus

**Comment by haltman-at** [comment]
I'm confused why this is an error at all; even in a function marked `external`, value types have their values copied to the stack as usual, right?  It's only reference types that have a pointer put on the stack in place of the value, right?  Shouldn't `x` refer to the copy on the stack, not the original calldata copy?

**Comment by ekpyron** [comment]
@haltman-at That's a good point - we could just allow it instead.

**Comment by chriseth** [comment]
That's true - I actually think this has been different in the past.

**Comment by avatar-lavventura** [comment]
Use `pubic` instead of `external` to fix it
