### ISSUE TITLE
Request: isMined(txHash)

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#723]
I'm working on a relay scheme where relayers get paid if a transaction they are relayed is mined. one way to do this would pass 1) a transaction to relay 2) a contract which pays the relayer if and only if the transaction has been mined.

Afaik, 2) is not currently possible.

**Comment by Denton-L** [comment]
I don't think this is possible in Ethereum at the moment without hard-forking and making breaking changes to the EVM.

**Comment by chriseth** [comment]
This is possible by providing Merkle proofs from the transaction hash to the block hash and actually not too complicated, but it is not in scope of a compiler feature.

**Comment by aakilfernandes** [comment]
@chriseth Sounds good. I'm investigating that approach. Would you be able to point me in the direction regarding a formula for proving that? I also opened up a stack exchange question here: http://ethereum.stackexchange.com/questions/7147/given-a-blockhash-how-can-i-prove-a-transaction-with-a-given-hash-has-been-mine/7177#7177
