### ISSUE TITLE
Switch from ``address(_contract)`` to ``_contract.address``?

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7235]
Came up in https://github.com/ethereum/solidity/issues/4994 in which we decided to switch from casts to a member for external function types.

Since ``address`` never was a valid identifier, we could introduce this for contracts as well without having to fear name clashes.

I myself vote against this and would rather stay with casts here, but I'd be fine with switching as well.

**Comment by ekpyron** [comment]
Any reason why you moved this to "In progress" @erak? As far as I'm concerned it's not even decided, whether this should be done or not - so I'm moving it back to Inbox...

**Comment by leonardoalt** [comment]
I vote for `_contract.address`, as I find it cleaner.

**Comment by ekpyron** [comment]
Since ``address`` is a keyword and cannot be used as identifier anyways, I'd in fact be OK with going that way as well.

**Comment by ekpyron** [comment]
Discussion in chat:
If we make ``address`` a member, it might be consistent to e.g. do it for ``balance`` as well, but that would e.g. break state variables named ``balance``...

Is the balance rather a property of a contract or of its address? If the latter, we could argue that ``_contract.address.balance`` is good enough... the main question is whether making an exception by adding this *one* special member to contracts is fine or if it is (quote @chriseth) a "hack".

**Comment by chriseth** [comment]
This still does not look complete enough for me.

**Comment by axic** [comment]
> If we make address a member, it might be consistent to e.g. do it for balance as well, but that would e.g. break state variables named balance...

The main reason we went for `address(contract)` is to avoid any potential conflicts with members of `contract`. FWIW I'd be against using `contract` members, but potentially we could consider extending `type()` or introducing another meta function?

**Comment by ekpyron** [comment]
Using ``address(LibraryName)`` in https://github.com/ethereum/solidity/issues/7274 might be another point in favour of staying with ``address(_contract)``.
Personally, I'd be fine with closing this by leaving things as they are.

**Comment by chriseth** [comment]
I agree. Using `type` also does not really solve it because the address is not really a property of the type.
