### ISSUE TITLE
Add .clang-format to ease following coding style.

### ISSUE THREAD

**Issue by rocky** [ethereum/solidity#7241]
## Abstract

Add .clang-format so that coding style conventions can be more easily followed.

See https://github.com/ethereum/solidity/pull/7240 for a something to start with.

## Motivation

Solidity's C++ coding style seems to be unique. So deviations from that are to be expected, unless tools are in place to gude following coding style.

## Backwards Compatibility

No backwards compatibility issues.

**Comment by chriseth** [comment]
Duplicate: https://github.com/ethereum/solidity/issues/2856
