### ISSUE TITLE
Sourcemaps with file -1

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/solidity#7243]
Hi!

I'm trying to understand when are some source maps mapped to file `-1`. I understand the why, but I'm trying to come up with a list of things that get mapped to `-1`.

I tried to find where in the source code are source maps, but I couldn't.

Is this documented somewhere? Or can you give me some info about them?

Thanks!

**Comment by alcuadrado** [comment]
I kept reading and came to the conclusion that those `-1` come from [here](https://github.com/ethereum/solidity/blob/f5f2bbb274fcbdc1e1f9cc607373059a8d617ee6/libsolidity/interface/CompilerStack.cpp#L1294-L1297), so there's no easy way to find all of them.

I guess most of them come from the append functions and statements from these two files:
1. https://github.com/ethereum/solidity/blob/579bdaddb9784479741a9569be1e89e67482c69e/libsolidity/codegen/CompilerContext.cpp
2. https://github.com/ethereum/solidity/blob/60525dbf5296ad0117823f9f05fdebc8d3fc79c8/libsolidity/codegen/ContractCompiler.cpp

Is this correct, or am I missing something?

**Comment by chriseth** [comment]
These are usually compiler-internal routines which do not have a source equivalent, or at least not a unique one. Those routines might be called from different places, so it does not make much sense to assign it to a certain source file.

If you are debugging a trace, it is safest to assume that the source did not change. If you are looking at the code itself, there is no clear answer to the question.

Please reopen if you still have questions.

**Comment by alcuadrado** [comment]
Thanks for your answer @chriseth! 

I'm trying to create an exhaustive list of those internal routines. I know they are mostly encoded as code, but where can I see them? Are all of them in `libsolidity/codegen`, or is code added somewhere else? 

I'm mostly interested in things that can make the execution of a message fail, but aren't assignable to a particular file.

**Comment by chriseth** [comment]
Yes, most of them should be in libsolidity/codegen. I think all of them are either in ABIFunctions.cpp, YulUtils.cpp or use `callLowLevelFunction` in some way.

**Comment by alcuadrado** [comment]
Thanks! I'll take a look at those.
