### ISSUE TITLE
What I need to verify contract with open-source license?

### ISSUE THREAD

**Issue by rajajwaliya** [ethereum/solidity#7244]
i m deployed contract in etherscan mainnet. i m verify it with open-source license like (MIT, GNU). now the problem were i don't know were to define license in etherscan ?? and etherscan will validate license when we update the token profile ??

contract example :- https://etherscan.io/address/0x230451cc96eb02df59fb2dc99dd1b701fd119329#code

**Comment by chriseth** [comment]
I'm sorry, this looks like an issue with etherscan to me and not the compiler. Please reopen if you think otherwise.
