### ISSUE TITLE
[DOCS] Update linked iterable mapping contract or move it to our repo.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7247]
The mapping part of our "Types" section links to https://github.com/ethereum/dapp-bin/blob/master/library/iterable_mapping.sol for "iterable mappings", but the code is pre-0.5.0, so it won't work against current solc.
@chriseth It looks like you put the file in the dapp-bin repo - do things depend on it there or can it just be updated?
We should either update it there or have a copy of it in our repo and update that version instead.

**Comment by chriseth** [comment]
I think we should create an example in our documentation because it is requested rather often.

**Comment by ChrisChinchilla** [comment]
On it
