### ISSUE TITLE
[CI] Standardize build options for ossfuzz build CI

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7253]
## Description

Currently, the ossfuzz build CI
  - uses a custom cmake toolchain file
  - does not inherit default cmake options (which together with above means that the switch to c++17 was not picked up)
  - does not disable z3/cvc4 which are not required for the existing fuzzers

This issue tracks fix for these inconsistencies.

**Comment by ekpyron** [comment]
Related to this: we should probably have a dedicated clang docker image with all dependencies built with accordingly - that would help with failures as in https://github.com/ethereum/solidity/pull/7252#issuecomment-521260393
