### ISSUE TITLE
Source locations for shadowing via import.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7273]
Came up in https://github.com/ethereum/solidity/pull/7271.
It turns out that for the following in file ``B.sol``:
```
contract C {}
```
when compiling another file containing
```
import {C as msg} from "B.sol";
```
Then this correctly produces a ``This declaration shadows a builtin symbol.``, but it's location is the contract C in B.sol, whereas it should rather be ``msg`` in the import. ``C`` might still occur in a secondary location, but the primary location should be the import.

**Comment by christianparpart** [comment]
It could be trivially be made to:

```
/home/trapni/ethereum/solidity/C.sol:2:1: Warning: This declaration shadows a builtin symbol.
import {C as msg} from "B.sol";
^-----------------------------^
```

Or do we want to have it like so:
```
/home/trapni/ethereum/solidity/C.sol:2:1: Warning: This declaration shadows a builtin symbol.
import {C as msg} from "B.sol";
        ^------^
```

Or:
```
/home/trapni/ethereum/solidity/C.sol:2:1: Warning: This declaration shadows a builtin symbol.
import {C as msg} from "B.sol";
             ^-^
```
?

So first, second or third solution?

**Comment by bshastry** [comment]
I prefer the third solution (underscoring shadowed declaration only)

**Comment by christianparpart** [comment]
That's what I was implementing now anyways. :)
