### ISSUE TITLE
Allow getting address for linked libraries

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#7274]
## Abstract

As best I can tell, there's currently no way in Solidity to get the address of a linked library.  This could be useful e.g. for doing a manual `delegatecall`.  I would like there to be syntax for getting the address of a linked library.

## Motivation

I propose allowing the syntax `address(LibraryName)`, where `LibraryName` is the name of the library, as a means of getting the address of the linked copy of the library `LibraryName`.

Another syntax, such as `LibraryName.address`, would be fine too, but I think the former makes more sense in this case.  It makes sense to convert a library name to an address, since internally it's identified by an address; while writing `LibraryName.address` looks misleadingly like a state variable access (yes, even though libraries can't have state variables).

Then one could do something like this:

```
library Library {
  ...
}

contract Contract {
  ...
  function f() public {
    ...
    (bool result, bytes memory out) = address(Library).delegatecall(...);
    ...
  }
}
```

## Specification

Given an expression `E`, where `E` has type `type(library LibraryName)`, where `LibraryName` is the name of a library, I propose that it should be possible to convert `E` to type `address` by the usual means (i.e., writing `address(E)`), and that this conversion would return the address where the linked copy of `LibraryName` is kept.

## Backwards Compatibility

There should be no backwards compatibility problems.

**Comment by chriseth** [comment]
Discussion resulted in `address(LibraryName)`
