### ISSUE TITLE
Fix external Gnosis test

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7287]
Gnosis-Safe is currently failing and needs to be fixed: https://circleci.com/gh/ethereum/solidity/167286?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by erak** [comment]
Submitted a bug report in the Gnosis-Safe project: https://github.com/gnosis/safe-contracts/issues/125.

**Comment by chriseth** [comment]
Do you know when they started to fail and why? Did this work with the optimizer before or did we just not activate it?

**Comment by erak** [comment]
Can be closed after https://github.com/gnosis/safe-contracts/pull/126 got merged.

**Comment by axic** [comment]
@erak I think this is done?

**Comment by leonardoalt** [comment]
Yes.
