### ISSUE TITLE
Nightly tests should send out notification

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7288]
We're not getting notified in case one of the nightly build steps fails. This is particularly dangerous, since we don't get a notification about failing external tests (which are run nightly).

A quick brainstorming session with @Marenz resulted in a few options that we might have in order to implement a notification system:

1. Automated Gitter message: Hook up a `cURL` call to the `when`-attribute of a Circle step https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute and https://developer.gitter.im/docs/rest-api

2. Create a simple Circle Orb that takes care of sending out a message to Gitter: https://circleci.com/docs/2.0/notifications/#notifications-with-orbs

**Comment by Marenz** [comment]
An issue with option one is that any secret or auth token we'd use to send such a notification to gitter would be openly readable in our repository. I would strongly go with option two here.

A third option could be that we put up our own bridge server that we call with curl and we authenticate the calls using the circle ci ip address range or reverse DNS.. but I suspect option two is easier and more practical. Also the OSS community would probably benefit more as other projects could reuse our Orb for their own setup.

**Comment by Marenz** [comment]
One thought that just came to me: How about instead of notifications we let automatically create an issue in github when the nightly fails?
