### ISSUE TITLE
[yul] scope of functions vs variables

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7289]
## Description

```
{
function foo() {
        let x
        function bar() { foo() x := 1 }
}
}
```

`foo()` is valid inside `bar()` but `x` is not. Is this on purpose?

**Comment by bshastry** [comment]
I guess this is because `foo()`'s scope is tied to its outer scope (globally, in this case) and since `bar()` is in this outer scope, `foo()` is visible inside `bar()`'s body. However, the scope of `x` is tied to `foo()`'s scope which does not cross function boundary.

**Comment by chriseth** [comment]
Indeed, scopes of variables do not cross function boundaries, but functions do (they have to, otherwise you cannot usefully call any function). Do you think this is a problem?

**Comment by bshastry** [comment]
Yeah, I realized I filed an issue too soon :-)

It's not a problem, only requires a refactoring of the yul proto fuzzer in preparation for #7276
