### ISSUE TITLE
Allow spaces in the hex string format

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7290]
Currently hex strings (`bytes tmp = hex"001122";`) cannot have spaces in them.

I am writing a contract right now which has quite a large hex string (237 bytes) with clearly separate parts. Splitting that with spaces would allow easier visual identification and comparison of the parts.

E.g. `bytes tmp = hex"00 11 22";` would be equivalent to the above.

I'd only allow spaces between hex bytes (and not nibbles) and would disallow trailing or leading spaces.

An alternative solutions is to allow underscore instead of space with a similar strictness how underscores are allowed in number literals.

**Comment by erak** [comment]
I'd vote for the alternative solution and allow underscores: `hex"00_11_22"`. That would be then inline with hexadecimal number literals.

**Comment by ekpyron** [comment]
Done in #7374
