### ISSUE TITLE
Allow splitting string literals over multiple lines

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7292]
Many languages support splitting string literals overs multiple lines. Some require a special token between them.

I'd propose that parsing (hex) string literals would allow `"` as the next token and start concatenating the literals. Any whitespace, including new lines, would be allowed between the two `"` tokens.

E.g. `bytes tmp = hex"00112233" "44556677";` would be equivalent to `hex"0011223344556677"`.

**Comment by chriseth** [comment]
Sounds good! I would support that for all kinds of strings.
