### ISSUE TITLE
Opt out of bytecode metadata

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#7295]
I know this has been [discussed before](https://github.com/ethereum/solidity/issues/4853), but I would like to reopen this discussion.

I do not think that users of solc should be at the mercy of compiler developers in this issue. I would reckon that most users are not aware, few care, and only some are against compiler metadata. 

There are many reasons why contract developers might be interested in opting out of the metadata; they may wish to pay less gas, bring less storage weight upon the network, have less code to analyze, or simply be interested just out of aesthetic reasons.

Furthermore, the compiler metadata is only even useful if contract devs actually publish the swarm/ipfs metadata somewhere, which I imagine few do. (I don't have any statistics here, because I don't even know where to look for compiler metadata! etherscan does not have it. I'm not interested in installing swarm at this time to check :)).

**Comment by chriseth** [comment]
Since the experiment did not turn out very positive, I am willing to change my mind about that. We do not have the tooling necessary to complete the use-case, so it is probably better to make this optional. Furthermore, we nowadays have tons of space for compiler options in the standard json input.

**Comment by axic** [comment]
It must be noted that the "metadata" consists of several different fields, the swarm hash being one. Lately ipfs has been added as an option too and more importantly the compiler version is included there.

I'd object removing the compiler version.

**Comment by leonardoalt** [comment]
Implemented in https://github.com/ethereum/solidity/pull/7377#
