### ISSUE TITLE
Public variables's selectors

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/solidity#7299]
Hi,

I need to compute the selectors of the public variable's getters, and [the documentation](https://solidity.readthedocs.io/en/v0.5.11/contracts.html#getter-functions) is not very complete.

Is there any other doc? Or can you point me to where this is done in the compiler?

Thanks!
Patricio

**Comment by alcuadrado** [comment]
I think that all I need is to mimic this logic to get the params' types: https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L2469-L2495

Can you confirm this? Thanks

**Comment by erak** [comment]
@alcuadrado You can do that in Solidity by accessing the `selector` member of the function:
```
contract Test {
    uint public state = 3;
    
    function f(bool _value) public returns (bool) {
        return _value;
    }
    
    function fn_selector_state() public returns (bytes4) {
        return this.state.selector;
    }
    
    function fn_selector_f() public returns (bytes4) {
        return this.f.selector;
    }
}
```
In the compiler, this selector, which is a 4-bytes hash of the function signature (https://solidity.readthedocs.io/en/v0.5.11/abi-spec.html#function-selector) is computed here: https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L3130.

Does this answer your question?

**Comment by alcuadrado** [comment]
Thanks for your answer @erak! I'm afraid I wasn't very clear with my question though, sorry. 

I'm not using this selector in Solidity, but from a program that analyzes solidity code, so I want to somehow compute it myself. While the compiler's standard json output has a `methodIdentifiers` section, it's not clear how to map each of those to the state variable that produced them.

I managed to do it by getting the ast from the standard json outpt, getting the contracts' state variable declarations and applying a typescript version of this logic: https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L2469-L2495
