### ISSUE TITLE
[yul] Why are shadowed variable and function declarations treated differently?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7302]
## Description

Why does solidity treat variable name and function name shadowing differently?

```
{
  {
    // Okay: Shadows namesake variable in outer scope
    let x := 2
  }
  let x := 1
  // Okay: Stores 1 at address 0
  mstore(0, x);
}
```

```
{
  {
    // Not Okay: Shadows namesake function in outer scope
    function foo() {}
  }
  function foo() {}
}
```

**Comment by chriseth** [comment]
The reason is because functions are stored in code while variables are stored on the stack. You do not know if the stack of the scope outside the current function is valid and not even where it is.
