### ISSUE TITLE
Calling non-implemented base contracts when overriding causes internal error

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7314]
If the super is changed to a in the original example, the compiler still fails with internal error.

```
contract a {
    function f() public;
}
contract b is a {
    function f() public { a.f(); }
}
```

reported by @dddejan in https://github.com/ethereum/solidity/issues/5130#issuecomment-523577375

This is a rather specific case - you have to call the non-implemented base function and override the function at the same time.

The way we solved it with `super` in https://github.com/ethereum/solidity/issues/5130 is sub-optimal because it just removes non-implemented functions from the member list. Instead, a specific error should be thrown.

**Comment by dddejan** [comment]
Not 100% sure if it's related. Just in case, I'm adding another interesting ICE case with overrides, might be of interest (or is a separate bug). 

```solidity
pragma solidity >=0.6.0;

abstract contract A {
  function f() public virtual;
}

abstract contract B is A {
  function g() public { A.f(); }
}

contract C is B {
  function f() public override {}
}
```

Currently breaks with 

```console
$ ./solc-static-linux --version; ./solc-static-linux Test.sol 
solc, the solidity compiler commandline interface
Version: 0.6.0+commit.26b70077.Linux.g++
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ContractCompiler.cpp(1253): Throw in function void dev::solidity::ContractCompiler::appendModifierOrFunctionCode()
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```

Interestingly, replacing `A.f();` with `super.f()` will cause a compile error. Not sure if that is intended.
