### ISSUE TITLE
Optimization step: remove unneeded masking in mstore8

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7323]
Replace `mstore8(x, and(y, a)` with `mstore8(x, y)` where `a >= 0xff`.

Note, this would be made obsolete with range tracking where all unneeded masking could be removed.

**Comment by chriseth** [comment]
Note that `bytes memory x; ... x[2] = 3;` is the only place where the code generator uses `mstore8`.

Furthermore, I think the condition is `a & 0xff == 0xff` instead of `a >= 0xff`.

**Comment by axic** [comment]
> Note that bytes memory x; ... x[2] = 3; is the only place where the code generator uses mstore8.

I wrote some hand written code and found this case there.

> Furthermore, I think the condition is a & 0xff == 0xff instead of a >= 0xff.

Yep, correct.
