### ISSUE TITLE
Linking fails for libraries with underscors in their names.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#733]
It appears that the `--link` functionality is unable to handle library names that contain underscores.

``` javascript
// TestContract.sol
library Has_Underscores { function x() {} }


contract C {
    function doit() {
        Has_Underscores.x();
    }
}
```

And trying to compile it...

``` bash
$ solc TestContract.sol --bin | solc --libraries Has_Underscores:0x6c8f2a135f6ed072de4503bd7c4999a1a17f824b --link
Error in binary object file <stdin> at position 200
```

**Comment by VoR0220** [comment]
interesting thing to keep out for....

**Comment by pipermerriam** [comment]
For reference, I'm using the following regex in other code to find link refs.

``` python
DEPENDENCY_RE = re.compile((
    '__'  # Prefixed by double underscore
    '(?P<name>[a-zA-Z_](?:[a-zA-Z0-9_]{0,34}[a-zA-Z0-9])?)'  # capture the name of the dependency
    '_{0,35}'
    '__'  # End with a double underscore
))
```

This will overmatch on certain conditions, but as far as I can tell it works well on anything produced by `solc`

**Comment by chriseth** [comment]
This is a limitation of how you invoke he compiler. The two-step process is just a work-around and also fails for too long library names. The proper way to use the linker is as follows:

```
$ solc TestContract.sol --bin --libraries Has_Underscores:0x6c8f2a135f6ed072de4503bd7c4999a1a17f824b
```

**Comment by axic** [comment]
@pipermerriam [this](https://github.com/ethereum/solc-js/blob/master/wrapper.js#L52) is what I did based on the C code: truncate the name to max. 37 chars and postfix it.

@chriseth even though it is a workaround, shouldn't both invocations truncate it in the same way?

**Comment by chriseth** [comment]
@axic erm, yes, you are right :-)

**Comment by pipermerriam** [comment]
Huzzah!
