### ISSUE TITLE
[YulOpt] Loop-invariant code motion

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#7345]
Some expressions in loop's body/post block can be moved outside the loop.

Prerequisites could be Disambiguator, ForLoopConditionIntoBody, ForLoopInitRewriter, and ExpressionSplitter

Then for each time we encounter a loop in current scope, we check all `VariableDeclaration` inside the loop's body and post block, if the `VariableDeclaration` satisfies the following properties, we can move (hoist) that declaration to current scope (outside the loop).

1. its `value` is `movable`
2. all identifiers in its `value` have its reaching definition outside the loop.

Ideally we want to move all movable declarations in a single application of this optimization pass.

**Comment by sifmelcara** [comment]
@chriseth  Not sure if existing tools can figure out the locations where a variable are assigned?

Let's use the following two pieces of code as example
```
{
  let a := calldataload(0)
  let b := calldataload(0x20)
  if gt(a, 0) { b := mul(b, 2) }
  for {let i := 0} 1 { i := add(i, 1) } {
    if gt(add(i, or(b, 64)), 12345) { break }
    mstore(i, 1)
  }
}
```

```
{
  let a := calldataload(0)
  let b := calldataload(0x20)
  for {let i := 0} 1 { i := add(i, 1) } {
    if gt(add(i, or(b, 64)), 12345) { break }
    mstore(i, 1)
    if gt(a, 0) { b := mul(b, 2) }
  }
}
```

After applying for loop init rewriter and expression splitter, we can start checking which declarations can be moved outside the loop.

In the first piece of code, we will find that we can move `let _9 := or(b, 64)` outside the loop, but we cannot do the same in the second piece of code, because `b` could be reassigned in the loop (i.e `let _9 := or(b, 64)` has a reaching definition that is not outside the loop).

So what I want is a tool that when I traverse to `let _9 := or(b, 64)`, at least I can know if `b` is always not reassigned in the loop.

**Comment by chriseth** [comment]
I believe that applying SSA transform and only moving ssa-variables (i.e. variables that are never assigned to - those can be found using the SSAValueTracker) already leads to effective loop-invariant code motion.

If you apply SSA to the second code, it will still have `let _6 := or(b, _5)` in the loop body, i.e. it references the non-ssa variable and thus cannot be moved.

Now take a look at the following code, which is the second code with the conditional assignment to `b` moved to after the loop:
```
{
  let a := calldataload(0)
  let b := calldataload(0x20)
  for {let i := 0} 1 { i := add(i, 1) } {
    if gt(add(i, or(b, 64)), 12345) { break }
    mstore(i, 1)
  }
  if gt(a, 0) { b := mul(b, 2) }
}
```
If you turn this into SSA, you will see that you get `let _6 := or(b_13, _5)`, where `b_13` is an SSA variable, and thus the statement can be move to before the loop.

So I actually think for such simple loop-invariant code motion, our current framework is sufficient.

It gets more complicated when it comes to moving more intricate statements like `sload(x)` - which also might have a much bigger benefit. There, you need to check whether the statement is "movable relative to" the rest of the loop body. But maybe better to start small :)

**Comment by sifmelcara** [comment]
Hmm.. maybe I missed something, do you mean that we move the variable declaration whenever its RHS only contains variables that are assigned once?

If yes, won't it miss the opportunity to optimize my first piece of code?

**Comment by chriseth** [comment]
Why do you think it will not be able to optimize your first piece of code? It is fine to require certain other components of the optimizer to have run, like the SSA transform - that's what they are for.

**Comment by sifmelcara** [comment]
Because if I load the first piece of code into yulopti and apply `xplit` and `ssa transform` I get the following:

<details>
  <summary>Click to expand</summary>

```
{
    let _1 := 0
    let a := calldataload(_1)
    let _2 := 0x20
    let b_13 := calldataload(_2)
    let b := b_13
    let _3 := 0
    let _4 := gt(a, _3)
    if _4
    {
        let _5 := 2
        let b_14 := mul(b_13, _5)
        b := b_14
    }
    for {
        let i_15 := 0
        let i := i_15
    }
    1
    {
        let _6 := 1
        let i_16 := add(i, _6)
        i := i_16
    }
    {
        let _7 := 12345
        let _8 := 64
        let _9 := or(b, _8)
        let _10 := add(i, _9)
        let _11 := gt(_10, _7)
        if _11 { break }
        let _12 := 1
        mstore(i, _12)
    }
}
```

</details>

I cannot move `let _9 := or(b, _8)` outside the loop because `b` is not a SSA variable

**Comment by chriseth** [comment]
Ah sorry, I thought the first one was not a problem. I think we can solve it by extending the SSA transform: After each joining control flow, statements like `let b_15 := b` are inserted. When this is done, the loop will use `b_15` instead of `b`.

**Comment by sifmelcara** [comment]
I wonder if we want move `comp()` out of the loop in the following cases?
1.
```
{
  for { let i := 0 } 1 {}
  {
    if cond(i)
    {
      mstore(i, comp())
    }
    i := add(i, 1)
  }
}
```
2. Similar to `1.`, but it is `switch` inside the loop, instead of `if`

Sometimes a branch inside a loop would never be executed, make me wonder if we should only promote computations in the immediate scope of loop body/post block?

**Comment by chriseth** [comment]
I think we should be rather conservative here and only move statements at the top level in the loop body. Already moving stuff out of loops might "pessimize" the code because it could be that the loop is run zero times.

**Comment by sifmelcara** [comment]
So I finished the implementation and was writing test cases, and I found that current Rematerializer implementation will move expressions back into the loop which negates the effect of LICM. Maybe Rematerializer should add a rule to not rematerialize value into loop? What do you think?

**Comment by chriseth** [comment]
Can you provide some examples?

**Comment by sifmelcara** [comment]
```
{
  let b := calldataload(0x20)
  for { } 1 { } {
    if gt(b, 123) { break }
  }
}
```
-> loop init rewriter, expression splitter, ssa transformer ->
```
{
    let _1 := 0x20
    let b := calldataload(_1)
    for { } 1 { }
    {
        let _2 := 123
        let _3 := gt(b, _2)
        if _3 { break }
    }
}
```
-> loop invariant code motion ->
```
{
    let _1 := 0x20
    let b := calldataload(_1)
    let _2 := 123
    let _3 := gt(b, _2)
    for { } 1 { }
    { if _3 { break } }
}
```
-> expression joiner ->
```
{
    let b := calldataload(0x20)
    let _3 := gt(b, 123)
    for { } 1 { }
    { if _3 { break } }
}
```
(current state is good, as we successfully moved the expansive computation (`gt`) out of the loop)
-> rematerializer ->
```
{
    let b := calldataload(0x20)
    let _3 := gt(calldataload(0x20), 123)
    for { } 1 { }
    {
        if gt(calldataload(0x20), 123) { break }
    }
}
```
(`gt` moved back into the loop by rematerializer, which is not desired)

**Comment by chriseth** [comment]
Ah, right, I did not remember the full rules of the rematerializer. We could tune it such that when inside a loop, the `refs <= 1` alternative is not valid, i.e.:

```
if ((refs <= 1 && !m_insideLoop) || cost == 0 || (refs <= 5 && cost <= 1) || m_varsToAlwaysRematerialize.count(name))
```
