### ISSUE TITLE
[Sol-Yul] Implement `push()` and `pop()`

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7351]
The following contract cannot be compiled via yul because of an internal compiler error resulting from an assertion (only `length` is implemented).
```
contract C {
    uint[] storageArray;
    function set_get_length(uint256 len) public returns (uint256) {
        for (uint i = 0; i < len; i++)
            storageArray.push(0);
        return storageArray.length;
    }
}
```

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/8308

**Comment by axic** [comment]
This was implemented some time ago.
