### ISSUE TITLE
[Yul] Prune functions that call each other but are otherwise unreferenced

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7352]
Can use the callgraph for this.

**Comment by ghallak** [comment]
Should this be implemented inside `UnusedPruner` class or in a separate class?

I noticed that `UnusedPruner::runUntilStabilisedOnFullAST` keeps running again while the AST is changing, but I'm wondering if that is necessary when pruning functions that only call each other.

**Comment by chriseth** [comment]
It might be better to add another optimizer stage that only deletes functions and does not care about variables.
