### ISSUE TITLE
[abiv2] ABI encoding fuzzer sometimes doesn't crop enough bytes to generate invalid encodings

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7355]
## Description

ossfuzz issue: 16963

The test program located here https://gist.github.com/bshastry/4031b4b00f9f859cfde6c50e444df40e

fails here

https://gist.github.com/bshastry/4031b4b00f9f859cfde6c50e444df40e#file-abiv2_failure-sol-L147-L149

because making a call with invalid (cropped abi encoding) incorrectly succeeds. Still trying to figure out why this happened.

Might be related to #7188 (specifically my implementation of https://github.com/ethereum/solidity/pull/7188#discussion_r312000815).

In the linked test program, the last parameter is a `bool`, so we end up potentially cropping less than 32 bytes. I'm not sure why an invalid encoding in this case (with at least one byte cropped from valid encoding) succeeds

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg
- Framework/IDE (e.g. Truffle or Remix): evmone
- EVM execution environment / backend / blockchain client: evmone

## Steps to Reproduce

I'm afraid this one needs to be reproduced using the abiv2_proto_ossfuzz binary because of [eip-170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md) that Remix faithfully observes.

**Comment by bshastry** [comment]
Trying to minimize the reproducer test case at the moment. Remix seems to hang on "transaction execution" even when a single value is assigned to the bytes array :|

**Comment by ekpyron** [comment]
Ah, well, I know why this fails... I was wrong about the logic for cropping the encoding...

**Comment by ekpyron** [comment]
A simple example will be the following:
``function f(bytes calldata x, bool y)``
An example of an encoding for this for the bytes argument of length 1 and the bool being true is:

```0x40, 1 (that's "true"), 1, 'x'```

So while the ``bool`` argument comes after the ``bytes`` argument in the signature, in fact the encoding of the bytes argument comes after the encoding of the bool argument...
So in this case you again would have to crop at least 32 bytes to get something invalid.

So the logic for cropping at least 1 vs at least 32 bytes needs to be:
"crop at least 32 bytes, if the last **dynamically encoded** argument has bytes or string as base type"

**Comment by ekpyron** [comment]
Hadn't thought about that before, sorry about that :-).

**Comment by chriseth** [comment]
So is this a false alarm?

**Comment by ekpyron** [comment]
Well - it's a bug in the fuzzer :-). I'll change the title.

**Comment by bshastry** [comment]
@ekpyron Sure, no problem. I realize I can't postpone learning how abi encoding works any longer ;-)

**Comment by bshastry** [comment]
Reopening this issue since it seems I didn't fully fix the root cause

Latest test case (bytes, bool[4][4] memory) fails here

https://gist.github.com/bshastry/f1d393a7a5b3abd21c4a1e03a351761d#file-abiv2_failure-sol-L129

**Comment by bshastry** [comment]
Bug is the following:

- statically sized arrays are dynamically encoded only if their base type is `bytes` or `string` (current code considers all arrays to be dynamically encoded)

- dynamically sized arrays are dynamically encoded regardless of base type
