### ISSUE TITLE
[yul] optimizer assertion inside SimplificationRules pattern matcher fails

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7356]
## Description

```
{
 for {} and(create(1,0,0), msize()) {} 
 {
 }
}
```

fails this assertion

https://github.com/ethereum/solidity/blob/049e9500858324472d1bf38d1803bf3625fb2dec/libyul/optimiser/SimplificationRules.cpp#L160

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg

## Steps to Reproduce

```
$ solc --strict-assembly --optimize <code.yul>
Exception in assembler: /home/bhargava/work/github/solidity/libyul/optimiser/SimplificationRules.cpp(160): Throw in function bool yul::Pattern::matches(const yul::Expression &, const yul::Dialect &, const map<yul::YulString, const yul::Expression *> &) const
Dynamic exception type: boost::exception_detail::clone_impl<yul::OptimizerException>
std::exception::what:
[dev::tag_comment*] =
```

**Comment by chriseth** [comment]
This is not dramatic. I think it is caused by the fact that the rules added in RuleList.h:280 do not contain the proper number of arguments for CREATE and CREATE2
