### ISSUE TITLE
Segmentation fault using recursive structs

### ISSUE THREAD

**Issue by asinyagin** [ethereum/solidity#736]
Hi,

I'm getting a segfault on compilation of this contract:

```
contract C {
    struct S {
        S[] arr;
    }

    S s;

    function test() {
        s.arr.length = 10;
    }
}
```

```
root@241b87043bae:~/workspace/example-project/contracts# solc --bin test.sol 
Segmentation fault (core dumped)
root@241b87043bae:~/workspace/example-project/contracts# solc --version
solc, the solidity compiler commandline interface
Version: 0.3.5-0/RelWithDebInfo-Linux/g++/Interpreter
```

**Comment by VoR0220** [comment]
Hmmmm....you can't actually set the length of an array in Solidity currently, atleast like that. But we should either a) allow you to do it or b) throw an error telling you you cannot do it.

**Comment by chriseth** [comment]
The problem seems not to be setting the length of the array but actually using a recursively defined struct in the first place. As it is a dynamic array, it should work in principle, but I'll have to investigate.

**Comment by asinyagin** [comment]
A similar structure might be used for a graph for example. So it would be nice to allow it if it's possible.

**Comment by chriseth** [comment]
The problem here is that code is generate recursively for clearing the array (a struct is cleared by clearing all of its members, an array is cleared by clearing all its elements, ...).

This can be solved by generating a single routine for each type to clear and then re-use it in a loop.
