### ISSUE TITLE
[yul] object data block does not support hex encoded data

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7360]
## Description

```
object "object0" {
code {
{}
}
data "datablock" hex"8000000000001"
}
```

when parsed throws a parsing error

```
$ solc --strict-assembly <code.yul>
...
Error: Expected 'StringLiteral' but got 'ILLEGAL'
data "datablock" hex"8000000000001"
                 ^--------------^
```

But the [specification of yul object](https://solidity.readthedocs.io/en/v0.5.11/yul.html?highlight=dataoffset#specification-of-yul-object) states that data can be either string or hex encoded.

**Comment by chriseth** [comment]
Your hex string has an odd number of characters. :)

**Comment by bshastry** [comment]
> HexLiteral = 'hex' ('"' ([0-9a-fA-F]{2})* '"' | '\'' ([0-9a-fA-F]{2})* '\'')

I should have paid attention to `{2}` :-)
