### ISSUE TITLE
Auto-replace revert strings by shorter identifiers

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7364]
The compiler should auto-replace user-supplied revert strings by (short) identifiers and store the mapping in some metadata.

Related: https://github.com/ethereum/solidity/issues/7260

**Comment by ekpyron** [comment]
So this would happen whenever the revert message is a string literal? And could thereby be prevented by ``revert(string("msg"))``? Or whenever the argument can be compile-time evaluated in general? Or would this even be a new function ``revertFormat`` (given  #7365)?

**Comment by chriseth** [comment]
It would be a compiler switch and yes, it could only be used for string literals.

**Comment by cameel** [comment]
We now have custom errors, which satisfy the goal of having meaningful, recognizable errors without embedding the whole message in the bytecode, so I think we can close this.
