### ISSUE TITLE
Formatted Revert Error Messages

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7365]
Message string plus formatting. Compiler turns string into (short) identifier and supplies additional values (if provided). User interface reconstructs string and formats.

Additional metadata contains the mapping from identifier to format string.

Related: https://github.com/ethereum/solidity/issues/7364

**Comment by cameel** [comment]
While this could still have some uses, even with custom errors (when they store a message string as one of the parameters), I think that the need for this is much less pressing now, and it may not be worth implementing at all. At least not specifically as a measure targeted at errors. It could be a generic mechanism for embedding string templates in metadata but that I think should be considered and designed from ground up, taking into account the new language features that we added in the last 3 years. I'm closing this.
