### ISSUE TITLE
[CLI] Remove old error reporter

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7369]
https://github.com/ethereum/solidity/pull/7368 enables the new error reporter, but keeps the old one as command line option. It should be removed with the next breaking release.

**Comment by chriseth** [comment]
@franzihei is asking truffle if they have any problem with this.

**Comment by franzihei** [comment]
Feedback from Truffle: It shouldn't be too much of a problem for them on their end. They thank us very much for checking with them and giving a heads up on this. :)

**Comment by ekpyron** [comment]
I probably won't get around to finish this this month, so I'm unassigning myself.
I could push the part I have, i.e. removing the command line options itself, but that can be re-done quickly anyways - the main part of this will be to have a look at all other usages of the old error reporter outside the CLI and check if we can and want to replace those by the new one as well (which would be a prerequisite to remove the code entirely).

**Comment by axic** [comment]
StandardCompiler still uses the old one -- should we consider changing that too?
