### ISSUE TITLE
Clean up CMake files in test/ and avoid compiling tests twice

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7370]
~~``test/CMakeList.txt`` itself still uses ``GLOB``s to fetch the sources - that should be changed.~~ [Update: that part's not true anymore]

We need to decide, whether we consider it dangerous that we might miss files and thus not run the tests in it - but we could just still *also* GLOB and create a cmake error, if there is a source file in the glob that's not in the explicit list of sources. [Update: we could still do this, though, if we deem it necessary - I wouldn't say it's too important, though]

Also ``isoltest`` adds most of the sources used by ``soltest`` as well - all of them will needlessly be compiled twice - they should probably end up in something like ``libsoltest``. [Update: this we still need in any case]

**Comment by chriseth** [comment]
We should better split code in proper libraries, too, especially in the test directory.

**Comment by axic** [comment]
> test/CMakeList.txt itself still uses GLOBs to fetch the sources - that should be changed.

I don't see GLOB anymore -- is this issue still valid?

> Also isoltest adds most of the sources used by soltest as well - all of them will needlessly be compiled twice - they should probably end up in something like libsoltest.

This is a valid problem though, right?

**Comment by ekpyron** [comment]
Exactly - we removed the ``GLOB``s, but there's still no ``libsoltest`` or sth like that, i.e. it's still a bit of a mess and stuff is compiled multiple times.
