### ISSUE TITLE
Error: Operator == not compatible with types string memory and string storage 

### ISSUE THREAD

**Issue by mike80439** [ethereum/solidity#741]

**Comment by mike80439** [comment]
---

Error: Operator == not compatible with types string memory and string storage ref
      if(_n == clients[idx].n) {

  function getClientByName(string _n) returns (uint i,bool b,int8 r) {
//    string memory n1 = _n;
    for(uint idx=0; idx<clients.length; idx++) {
//      string memory n2 = clients[idx].n;
      if(_n == clients[idx].n) {
        i = clients[idx].i;
        b = clients[idx].b;
        r = clients[idx].r;
        return;
      }
    }
    throw;

**Comment by chriseth** [comment]
It is not possible to compare strings like that. You have to use a library like the string utils: https://github.com/Arachnid/solidity-stringutils
