### ISSUE TITLE
[yul] optimizer fails assertion in BlockHasher.cpp

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7416]
## Description

```
{
  let x_0
  x_0 := 0
  for {let i_0} lt(i_0,6) {i_0 := add(i_0, 2)} {
    x_0 := x_0
  }
}
```

fails 

https://github.com/ethereum/solidity/blob/b747c26788c60d9d4487329f47b96d20df68dfb4/libyul/optimiser/BlockHasher.cpp#L116

The call to `yul::AsmPrinter()(_varDecl)` before the assertion prints the following

```
let x_0 := x_0_14
```

and the block preceeding it is

```
{
    {
        let x_0_14 := 0
        x_0 := x_0_14
        let x_0_15 := x_0_14
        let x_0 := x_0_14
        let i_0_16 := x_0_14
        let i_0 := x_0_14
        for { }
        1
        {
            let _10 := 2
            let i_0_18 := add(i_0, _10)
            i_0 := i_0_18
        }
        {
            let _11 := 6
            let _12 := lt(i_0, _11)
            let _13 := iszero(_12)
            if _13 { break }
            let x_0_17 := x_0
            x_0 := x_0
        }
    }
}
```

## Environment

- Compiler version: latest develop

## Reproduction

```
$ solc --strict-assembly --optimize <test.yul>
```

**Comment by ekpyron** [comment]
Hm - there's a name collision in ``x_0`` in the block before - so the question is: where is this coming from...

**Comment by ekpyron** [comment]
It's https://github.com/ethereum/solidity/pull/7408 - but I don't see why...

**Comment by ekpyron** [comment]
It's the SSA Reverser when run on ``let x := 0 x := x``... and that pattern seems to actually occur since #7408...

**Comment by ekpyron** [comment]
Yeah - so I see two options - let ``SSAReverser`` deal with this case correctly or require it to be removed by some other step before calling it.

**Comment by ekpyron** [comment]
Nevermind: this was wrong.

~~Actually having~~
```
let x := 0
x := <someExpressionInvolvingX>
```
~~is enough to trigger the bug.~~
