### ISSUE TITLE
[yul] optimizer can now increase execution step count of a program by 2x

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7424]
## Description

We had decided on an upper bound of `N * 1.5` number of execution steps for optimized code (see https://github.com/ethereum/solidity/issues/6476#issuecomment-480237241) that is now exceeded most likely because of #7407 

> Does it make sense to set the bound to some value N when executing the non-optimized version and setting it to N * 1.5 when executing the optimized version? This should make the assumption you name true again in most cases, and the cases where it fails should be inspected manually anyway, because it sounds like the optimizer did a bad job for those.

Opened this issue to discuss this change. My intuition is that break for-loop-condition into `if (iszero(condition)) break` adds an additional step for each loop iteration, so in total optimized code may lead to twice the number of steps.

Example unoptimized code

```
{                   
    for { let i_0 } lt(i_0, 0x60) { i_0 := add(i_0, 0x20) }
    {              
        for { let i_1 } lt(i_1, 0x60) { i_1 := add(i_1, 0x20) }
        {
            for { let i_2 } lt(i_2, 0x60) { i_2 := add(i_2, 0x2

            {
                for { } msize() { }
                { }
            }
        }
    }
}
```

Example optimized code (2x "slower")

```
{
    let i := 0

    for { } 1 { i := add(i, 0x20) }
    {                
        if iszero(lt(i, 0x60)) { break }
        let i_1 := 0 
        for { } 1 { i_1 := add(i_1, 0x20) }
        {            
            if iszero(lt(i_1, 0x60)) { break }
            let i_2 := 0
            for { } 1 { i_2 := add(i_2, 0x20) }
            {
                if iszero(lt(i_2, 0x60)) { break }
                for { } 1 { }
                { if iszero(msize()) { break } }
            }
        }
    }
}
```

One solution is to change these two

https://github.com/ethereum/solidity/blob/34ba617ea6eec0bd4e2e9fd94dcbbb964626955e/test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp#L121

https://github.com/ethereum/solidity/blob/34ba617ea6eec0bd4e2e9fd94dcbbb964626955e/test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp#L104

to

```
(yul::test::yul_fuzzer::yulFuzzerUtil::maxSteps * 2)
```

**Comment by chriseth** [comment]
Will be solved by #7409
