### ISSUE TITLE
Make all examples in docs follow solhint rules and re-enable style checker test in CI

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7436]
We disabled the style checker test in https://github.com/ethereum/solidity/pull/7435 with 0.6.0 because it was not updated to our syntax changes.

**Comment by ChrisChinchilla** [comment]
@chriseth Are all the changes documented somewhere? I should probably also let the teams behind solhint etc know about the changes. Or make a PR to their projects.

**Comment by chriseth** [comment]
They are more or less explained here: https://github.com/ethereum/solidity/blob/develop_060/docs/060-breaking-changes.rst

**Comment by chriseth** [comment]
This is blocked by https://github.com/protofire/solhint/issues/170 (solhint updating to 0.6.0)

**Comment by axic** [comment]
This was only done for the docs, but it would be nice to run it on the tests too.

Can we reenable this?

**Comment by chriseth** [comment]
Please no style enforcement on the tests. This is bad for the syntax tests and also limits us in the semantic tests.

**Comment by axic** [comment]
I meant only for semantic tests, but what does it limit there?

**Comment by chriseth** [comment]
It just takes more time to format it properly.

**Comment by cameel** [comment]
At this point this basically requires going through most examples and doing tediuos style fixes. I even see some crashes (e.g. `RangeError: index parameter must be between >= 0 and <= number of children.`).

I'm going to mark this as `good first issue`, with the goal being to clean up the examples first before we re-enable the job.

For anone who'd like to take it, here's a short snippet that can be executed from repo root to automatically run solhint on all docs snippets:
```bash
mkdir -p solhint/docs-examples/
cp test/.solhintignore test/.solhint.json solhint/
cd solhint/docs-examples/
../../scripts/isolate_tests.py ../../docs/
cd ..
npm install solhint
for snippet in docs-examples/*.sol; do
    npx solhint -f unix $snippet
done
```

We will accept PRs that clean up some or all of what solhint reports.

**Comment by cameel** [comment]
Reopening because we still have that disabled style checker job. We should either clean up the examples or remove the commented out job from CI config.
