### ISSUE TITLE
Timeline for moving ABIV2 out of experimental status?

### ISSUE THREAD

**Issue by coventry** [ethereum/solidity#7441]
The ABIV2 feature allowing structs as parameters is very useful, but inappropriate for production use as long as it's under experimental status. What steps are needed, before the experimental status can be  lifted? It would be helpful to know roughly when the feature might be ready for production use, so developers can decide whether to build contracts with it, or work around it using tuples or encoding/decoding of bytes arguments.

**Comment by chriseth** [comment]
It is part of Solidity 0.6.0 to remove the warning, but we still require a pragma to activate the feature.

You can follow the progress here: https://github.com/ethereum/solidity/projects/22

Items in the "Inbox" column will probably not be part of the release.

**Comment by coventry** [comment]
Thanks, @chriseth.
