### ISSUE TITLE
[solc fuzzer] Add solc fuzzer that generates yul code from solidity code

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7445]
## Description

The code in this directory is not covered at all because we don't have fuzz solidity to yul code generation at the moment

https://github.com/ethereum/solidity/tree/develop/libsolidity/codegen/ir

Issue tracks support for adding one.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
