### ISSUE TITLE
Internal Compiler Error with fixed size array of recursive struct

### ISSUE THREAD

**Issue by hkalodner** [ethereum/solidity#7448]
## Description

Below I describe a fully reproducible internal compiler error in solidity version 0.5.11. This bug looks like a regression since I can't recreate it using 0.5.10.

Compiling the test file below leads to:

```
Internal compiler error during compilation:
/tmp/solidity-20190917-49278-19sfpot/solidity_0.5.11/libsolidity/ast/Types.cpp(2053): Throw in function virtual bool dev::solidity::StructType::isDynamicallyEncoded() const
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what:
[dev::tag_comment*] =
```

In order to verify its reproducibility, I checked that the below code also leads to an InternalCompilerError in remix.

## Environment

- Compiler version: 0.5.11+commit.22be8592.Darwin.appleclang
- Target EVM version (as per compiler settings): 0.5.11
- Framework/IDE (e.g. Truffle or Remix): None (solc command line directly)
- EVM execution environment / backend / blockchain client: N/A (internal compiler error)
- Operating system: Mac

## Steps to Reproduce

Just run with `solc Test.sol`

```solidity
pragma solidity 0.5.11;


contract Test {
    struct RecursiveStruct {
        RecursiveStruct[] vals;
    }

    function func() private pure {
        RecursiveStruct[1] memory  val;  
    }
}
```

**Comment by Marenz** [comment]
I suspect my commit 8e899a0d32de5032ec9986e14cf1161e657bd061 broke this

**Comment by Marenz** [comment]
Note, it's only a regression if you encountered this exact bug before, then it was fixed and then it broke again. Otherwise it's just a "normal" new bug in 0.5.11 ;)

**Comment by Marenz** [comment]
I just checked, it was not my commit that caused this.. still looking

**Comment by Marenz** [comment]
This commit is causing the problem: 15631a7fbe603bb7b1d79eee4894df73c36f32f9

**Comment by hkalodner** [comment]
Thanks for the quick response!
