### ISSUE TITLE
[Sol -> Yul] Implement revert string stripping in YulIRGenerator

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7451]

**Comment by axic** [comment]
@chriseth @mijovic isn't this solved with #10765 given it uses `reasonIfDebug`? Or is this issue more generic to strip any message supplied? If so, why don't we have specific tests for this? Would need a flag in the test format for it 😓

**Comment by mijovic** [comment]
After #10765 only remaining test will be `code_access_padding`

**Comment by mijovic** [comment]
I am not sure what exactly was meant by "revert string stripping", so am not really sure if it will be solved by #10765

**Comment by chriseth** [comment]
Don't we have an option that strips revert strings even if they are user-supplied?
