### ISSUE TITLE
Update external tests to 0.6.0

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7460]
The contracts in external projects we're testing on a nightly basis, need to be updated to the breaking changes of 0.6.0. Since we cannot update the upstream repositories directly, these have been forked:

- [x] https://github.com/erak/colonyNetwork/ (`develop_060`)
- [x] https://github.com/erak/safe-contracts/ (`development_060`)
- [x] https://github.com/erak/openzeppelin-contracts (`master_060`)

The desired workflow would be to create PRs on the forks with every breaking change. After 0.6.0 has been released, we can try to get them merged upstream.

**Comment by axic** [comment]
Update how exactly? :wink:

**Comment by erak** [comment]
@axic I've updated the description ;)

**Comment by erak** [comment]
The only project, that has one issue left, is OpenZeppelin: https://github.com/ethereum/solidity/pull/7784#issuecomment-559974137

**Comment by axic** [comment]
Zeppelin was fixed according to https://github.com/ethereum/solidity/pull/7864#issuecomment-560488775

**Comment by axic** [comment]
@erak isn't this now fully fixed?

**Comment by axic** [comment]
@erak @ekpyron are you upstreaming these fixes?

The natspec updates at least don't require 0.6.0 as a compiler so that would make sense to upstream. And probably the inheritance problem in the test case in zeppelin is not strictly 0.6.0 specific.

**Comment by erak** [comment]
@axic Yeah, I was planning to create PRs in every repo that we forked.
