### ISSUE TITLE
Feature Request: allow reading `length` of the `string` type.

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereum/solidity#7469]
## Abstract

Strings have a length. It is not possible to read `length` of the `string` type. You have to convert it first to a `bytes` type.

## Motivation

It is not intuitive that you have to "convert" the `string` to `bytes` to read length. The only reason I can think of is that it is not intuitive if a character in the string is more than one byte length (e.g. special characters) - should we return the char length or the byte length of the string? (Is this the reason that reading `length` of a string is not possible?)

## Specification

Allow us to read the `length` property of the `string` type.

## Backwards Compatibility

This is backwards compatible.

**Comment by jochem-brouwer** [comment]
In case that this was not included in the first place because of differences between char length and byte length (due to encoding) this feature request can be closed.

**Comment by chriseth** [comment]
Yes, multi-byte characters are the reason for disallowing access to string length.
