### ISSUE TITLE
[Fuzzing] Enable yul optimizer via compiler stack

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7471]
## Description

Is there merit in enabling yul optimizer in compiler stack settings (see https://github.com/ethereum/solidity/pull/7446/files#diff-6705b87d569995601f337962eef489ddR97)

given that we have a standalone yul optimizer fuzzer?

**Comment by chriseth** [comment]
This can be done via `setOptimiserSettings(OptimiserSettings _settings);` or did I misunderstand the question?

**Comment by bshastry** [comment]
Actually, the question is should we do it rather than how to do it. I think the how essentially involves changing the configuration setting.

To rephrase, will be benefit from a fuzzer that compiles solidity via yul? If so, I can reopen https://github.com/ethereum/solidity/pull/7446

**Comment by chriseth** [comment]
I think not yet.
