### ISSUE TITLE
Building from source fails (incomplete type in Z3 CHCInterface)

### ISSUE THREAD

**Issue by zhao-nan** [ethereum/solidity#7481]
## Description

When building the latest version of the compiler from source (as described [here](https://solidity.readthedocs.io/en/latest/installing-solidity.html)), the build fails with the following error message:
```
$ cmake .. && make
...
[ 51%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o
In file included from /home/jonas/tmp/soliditest/solidity/libsolidity/formal/CHC.cpp:21:0:
/home/jonas/tmp/soliditest/solidity/libsolidity/formal/Z3CHCInterface.h:56:17: error: field ‘m_solver’ has incomplete type ‘z3::fixedpoint’
  z3::fixedpoint m_solver;
                 ^~~~~~~~
In file included from /home/jonas/tmp/soliditest/solidity/libsolidity/formal/Z3Interface.h:22:0,
                 from /home/jonas/tmp/soliditest/solidity/libsolidity/formal/Z3CHCInterface.h:25,
                 from /home/jonas/tmp/soliditest/solidity/libsolidity/formal/CHC.cpp:21:
/usr/include/z3++.h:65:11: note: forward declaration of ‘class z3::fixedpoint’
     class fixedpoint;
           ^~~~~~~~~~
libsolidity/CMakeFiles/solidity.dir/build.make:926: recipe for target 'libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o' failed
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o] Error 1
CMakeFiles/Makefile2:389: recipe for target 'libsolidity/CMakeFiles/solidity.dir/all' failed
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

When Z3 is explicitly excluded (`cmake --DUSE_Z3=Off`), building succeeds.

## Environment

- Compiler version: latest (0.5.11)
- Operating system: Ubuntu 18.04 64bit
- Z3 Version: 4.8.5

**Comment by leonardoalt** [comment]
Hi @zhao-nan ,
are you sure about the Z3 version? I've seen this error before on Ubuntu, when people use the stock z3 (which is old).
Since you're on Ubuntu, I assume you have a custom installation of Z3 4.8.5. What could be happening is that you have both versions (stock and custom) installed, and CMake is preferring the old one for some reason.

**Comment by zhao-nan** [comment]
Woops. Yes, you are right. I did not realize the old repo version was also installed.
Thanks for the quick help!
