### ISSUE TITLE
Dockerhub image for 0.4.26

### ISSUE THREAD

**Issue by yudilevi** [ethereum/solidity#7484]
Hi,

Not a feature request per se, but I noticed that dockerhub is missing the 0.4.26 compiler image - would it be possible to add it there?

Thanks!

**Comment by erak** [comment]
@yudilevi Thanks for bringing this up! You're right, `dockerhub` is missing the 0.4.26 release image. I'm not sure if it wasn't planned to have an image or if it wasn't built by accident. I'll check back with the team and keep you posted.

**Comment by chriseth** [comment]
Added the image.

**Comment by yudilevi** [comment]
Awesome, thank you :)
