### ISSUE TITLE
Question: How to get a given variable's representation in EVM state?

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/solidity#7489]
Solidity Team,

I'm wondering if there is a compiler output to get how a given variable is represented in EVM state?

Variables would be any variables in Solidity code from given contract storage variables (where we would just need to know the "keccak index" of each variable) or temporary variables created in the scope of a function which would have locations in memory.

Alternatively, if there is no way to get that output directly from the compiler or ABI, is there a canonical way to determine these across Solidity versions?

**Comment by chriseth** [comment]
We are currently working on generating more debugging data together with the truffle team. The location of variables in storage has been stable for many years now and is documented here: https://solidity.readthedocs.io/en/v0.5.12/miscellaneous.html#layout-of-state-variables-in-storage
