### ISSUE TITLE
Update Z3 to 4.8.6

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7494]
Z3 recently released 4.8.6 - we should update the static Z3 PPA build and might be able to use stronger tests or remove workarounds that way (@leonardoalt ?).
To discuss: do we want to just require the most recent Z3 release to guarantee all tests to pass?

**Comment by axic** [comment]
4.8.6 has issues with some tests.

**Comment by leonardoalt** [comment]
Yes, it looks like some new code is behaving worse.
Me and @ekpyron thought about updating the tests to the worse version anyway, to keep it always compatible with the latest z3. The issues happen to complex array tests.

**Comment by ekpyron** [comment]
Should we go ahead with that? The steps are the following:
- update the cpp-build-deps static PPA build of Z3 to 4.8.6 (I can do that any time, once we definitely decide)
- create a PR that updates the test expectations
- simultanously push a docker image with Z3 4.8.6, rerun tests on that PR and merge it
- rebase everything on top of that

**Comment by ekpyron** [comment]
In case #7464 is merged as it stands, we also need to change the MacOS test run to use the binaries from the build run, instead of rebuilding against Z3 4.8.5 and remove the path workarounds in the scripts it added.

**Comment by ekpyron** [comment]
This is done by now.
