### ISSUE TITLE
Nicely format strings in Yul IR generation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7505]
When generating the Yul intermediate code of Solidity programs, strings are always translated to hex numbers. This prevents readability of IR code. Because of that, the code generator should detect if a string can be represented in printable ascii chars (for safety) and use that instead.

## How to implement:

Add a function `std::string formatAsStringOrNumber(std::string const& _value)` in `libdevcore/CommonData.h` that checks if all characters are safe and outputs a quoted string. If there is an unsafe charater, use `"0x" + h256(_value, h256::AlignLeft).hex();` as it has been used before (you need to include `FixedHash.h` for that).

Now use that function in ABIFunctions.cpp:978 (`ABIFunctions::abiEncodingFunctionStringLiteral`) and :993. The same change can be applied to `YulUtilFunctions::conversionFunctionSpecial`.

## How to test:

Run `solc --ir` on e.g.
```
contract c {
function f() external pure returns (string memory) { return "abcabc"; }
}
```

It should not contain `0x6162636162630000000000000000000000000000000000000000000000000000` anymore but `"abcabc"` instead.

## How to add an automated test

Create a copy of the directory `test/cmdlineTests/standard_ir_requested` such that `input.json` contains code similar to the one above. Run `./test/cmdlineTests.sh` to update the expectation file.

You should additionally create a test inside `test/libsolidity/semanticTests` that ends in

```
// ====
// compileViaYul: also
// ----
// f()
```

This test should check that the contract still works as expected. Please also try string literals longer than 32 bytes.

obsoletes https://github.com/ethereum/solidity/issues/7495

**Comment by secondW4ve** [comment]
Hi. In what namespace should it be added? In "dev" I guess? And also I dont get how to test, could you describe it more detail please?

**Comment by chriseth** [comment]
Yes, in `dev`. How to manually test: Run `solc --ir -` and paste the code provided above. If you create a draft pul request, we can guide you through how to add everything required.

**Comment by tabathap** [comment]
👌

**Comment by secondW4ve** [comment]
@chriseth Hi, I have created draft pull reques, please help me handle this if you have time.

**Comment by jamesthesken** [comment]
Is this on the `develop` branch?

**Comment by secondW4ve** [comment]
Yes

**Comment by jazalewski1** [comment]
Hi, is anyone working on this? I am looking for my first PR.

**Comment by erak** [comment]
Hey @jazalewski1, @secondW4ve is working on this already and their PR is in progress https://github.com/ethereum/solidity/pull/7522. Is Yul of special interest to you? We might have other tasks that could be nice to get started.

**Comment by jazalewski1** [comment]
@erak Ah sorry, I didn't notice. I will look for other issue, thanks.
