### ISSUE TITLE
Build soljson.js with rule list/browser stack height fix for old compiler versions.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7514]
It would be good to apply the rule list split to past compiler versions to be able to verify bytecode generated by old compiler versions in the browser. We considered doing that before, when remix asked for it (see https://github.com/ethereum/remix-ide/issues/1591), but only did one 0.4 release instead, but apparently there's more demand for this.

Unfortunately this will involve some manual effort - we need to make sure that the rule list stays the same, so the split needs to be done or at least verified for each compiler version (or at the very least between versions in which the rule list changes). Also it's unclear how far we want to go back - the entire 0.4 series would be a good start I guess.

We could consider to run bytecode comparison with the historic releases to have at least some assurance that there are no random behaviour changes between the builds.

We have to try to reconstruct which emscripten version was used to compile the respective version and should reuse it, but the respective tag should contain an appropriate CI script, so that part should be easy - best case scenario is that we just need to open a PR for the respective tag and can grab soljson.js as CI artifact, but we need to make sure to end up with a "release" build.

We also need to decide how and where to publish the rebuilds -maybe a separate branch in https://github.com/ethereum/solc-bin?

**Comment by axic** [comment]
Do you mean to rebuild exact old releases or just to make a new release in the 0.3 and 0.4 branches?

**Comment by ekpyron** [comment]
The idea is to rebuild all old releases exactly as they are *except with the rule list split*, so that their emscripten build will work in newer browsers. Only one 0.3/0.4 release won't really help (and we already did one for 0.4) - we need the each exact version to get exact bytecode matches for all contracts out there.

We haven't exactly decided whether we should keep the commit hash the same or not - I think the tendency was to have new commit hashes for the patched releases and let the tooling deal with mismatching metadata hashes. Not sure where these commits would live (i.e. what branch, etc. - e.g. one branch for each past release would be crazy), though, yet.

But yeah - rebuilding won't be enough, we need to patch the rule list separately for every single release (hence it's probably cleaner to use a new commit hash for each patched release).

**Comment by axic** [comment]
> what branch, etc. - e.g. one branch for each past release would be crazy

You don't need to keep the branch if you've tagged them. Tags ensure the references are kept.

**Comment by ekpyron** [comment]
> > what branch, etc. - e.g. one branch for each past release would be crazy
> 
> You don't need to keep the branch if you've tagged them. Tags ensure the references are kept.

Ah nice, yeah, makes sense. So we'd mainly need a naming scheme for the tags - I'd suggest ``v0.4.x-browserfix`` (but I don't really mind the exact naming).

**Comment by ekpyron** [comment]
Done by now. (resp. replaced by wasm builds)
