### ISSUE TITLE
[solc] smt checker repeats warning for unsupported bitwise negation `~` operator

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7518]
## Description

Not sure if this is specific to the smt checker. Code like this

```
pragma experimental SMTChecker;
contract C {
  uint s;
  modifier m(uint a) {
         _;
  }

  function f(uint x) m(x) m(9) m(4) m(s) public view {
    ~~~~~~~~~~~~~~~s;
  }
}
```

Creates an smt warning per bitwise negation operator `~` (there are 15 of them) times number of modifier execution. In this case, at least 13*15 (=195) times.

Eventually, the checker bails out on reaching 256 warnings (I'm not sure how it reasons about the value of m(x) and m(s) and how it reaches 256 warnings), like so

```
Warning: There are more than 256 warnings. Ignoring the rest.
```

**Comment by chriseth** [comment]
I think this behaviour is fine. Does it limit the fuzzer?

**Comment by bshastry** [comment]
@chriseth okay. I think it is fine then. I will close this issue.
