### ISSUE TITLE
JSON input: control the required outputs

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#752]
Would it make sense to have flags control which output options (AST, bytecode, Why3, etc.) are needed in the JSON output (in `JSONCompiler`) similar to how it is done on the commandline?

I think requiring only the needed would speed up the processing. I guess the bytecode/AST/assembler outputs wouldn't make a big difference as they are generated together for EVM, but Why3 is not necessary in all scenarios.

Similarly if WASM/WAST would come along that would be an extra step taking time.

Not sure what kind of speed loss we're talking about at the moment.

**Comment by chriseth** [comment]
Yes, this will be part of this here: https://github.com/ethereum/solidity/pull/712/files
There could also already be an issue about that.

**Comment by axic** [comment]
Great! Couldn't find the relevant issue.

Can you briefly explain here (or over #712) what the proposed way is?  And perhaps refer to this issue in #172 as fixed by.

**Comment by chriseth** [comment]
The idea is that in the future, all behaviour of the compiler is controlled by a single json object (which also includes the source files). The compiler can also _generate_ such a minimal json object to be used for source verification.

Concerning the output selection, I guess the syntax would be something like `outputs=["ast", "bytecode", "runtime-bytecode", "gas"]` - similar to the combined-json options on the commandline. It would also be nice if we could select which contract to compile or that we only want the ast for certain source files and so on.

**Comment by chriseth** [comment]
Do you want to write down a full specification of the json input and output format?

**Comment by axic** [comment]
Closed by #1387.
