### ISSUE TITLE
Entry points (functions) missing in ABI of libraries for Solidity > 0.5.5

### ISSUE THREAD

**Issue by gsalzer** [ethereum/solidity#7527]
## Description

The ABI generated by `solc --abi` misses entry points (functions). This phenomenon seems to start with Solidity 0.5.6

## Environment

- Compiler version: 0.5.6 - 0.5.12
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): command line and Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

## Steps to Reproduce

Consider the library

```
library L {
  function F(uint256) public returns (uint256) {}
}
```
The ABI should contain an entry for `F`, but `solc --abi` for Solidity version > 0.5.5 produces an empty ABI.

When declaring `F` as `pure`, or when using version 0.5.5 or lower, or when replacing `library` by `contract`, the ABI is correct.

**Comment by chriseth** [comment]
It is not possible to call non-view functions of libraries directly - such calls will revert. This is disallowed because it would lead to bugs like one of the parity wallet bugs.
