### ISSUE TITLE
Returning 2 dimensional array with 1 dimension fixed length gives Nested memory array exception

### ISSUE THREAD

**Issue by aditya-skeps** [ethereum/solidity#7535]
Posting my question here since I did not get any response on [stackoverflow](https://stackoverflow.com/q/58350728/11055400) so far.

Q1 -->

Please tell me why this works:

```
pragma solidity ^0.5.0;

contract con1 {
    byte[100][] a;
    bytes32[] b;

    function getArrays () public view returns (byte[100][] memory arr_a, bytes32[] memory arr_b) {
        return (a, b);
    }
}
```
and this does not (without adding the pragma experimental line)

```
pragma solidity ^0.5.0;

contract con1 {
    function getArrays () public view returns (byte[100][] memory arr_a, bytes32[] memory arr_b) {}
}

contract con2 {
    byte[100][] a;
    bytes32[] b;
    con1 iCon1;

    constructor(address _c1) public {
        iCon1 = con1(_c1);
    }

    function getArrays () public view returns (byte[100][] memory arr_a, bytes32[] memory arr_b) {
        return iCon1.getArrays();
    }
}
```
Gives following error:

Dynamic exception type: boost::exception_detail::clone_impl<langutil::UnimplementedFeatureError>
std::exception::what: Nested memory arrays not yet implemented here.
[dev::tag_comment*] = Nested memory arrays not yet implemented here.

Q2 -->

It does compile once I add - pragma experimental ABIEncoderV2;

Please tell me how much of a risk it is to use experimental features for this particular functionality. It's not much, just returning 2d array with 1 fixed length from another contract.

**Comment by chriseth** [comment]
The reason is just as explained in the exception: The feature has not been implemented yet.
About the risk: It is _probably_ fine to use it if you use the latest version of the compiler.

**Comment by aditya-skeps** [comment]
Ok thanks!
