### ISSUE TITLE
Function selector is truncated to the last complete byte if datasize in bits isn’t dividable by 8 (the size of a byte).

### ISSUE THREAD

**Issue by ytrezq** [ethereum/solidity#7536]
Last condition is number of bytes is above 4.
Example :

    0x10d0ffdd0000000000000000000000000000000000000000000e8ef1e96ae38
becomes :

    0x10d0ffd

And when looking at the function selector, it checks against `0x10d0ffda` whereas the last 4 bits of the function selector inside `ᴄᴀʟʟᴅᴀᴛᴀ` are truncated which makes it doesn’t finds any functions matching this selector which makes the payable function is used instead.

**Comment by chriseth** [comment]
Thanks for your bug report! Could you please provide the source code of a contract that has this behaviour and the compiler version and settings used (if that makes a difference)? I am assuming that you mean that the dispatch routine generated by the compiler does not work properly if specific calldata is sent to the smart contract. Is that correct?

**Comment by ytrezq** [comment]
@chriseth : unfortunately, no because this is [vendor hidden](https://etherscan.io/address/0x61edcdf5bb737adffe5043706e7c5bb1f1a56eea#code). I mean it did happen while reverse‑engineering the contract.

I can confirm it exhibits the ᴇᴄrecoverMalformedInput solidity compiler bug, so it shouldn’t be about a recent version.  
As a standalone person, I doubt Gemini would accept handing over their source code or even compiler version if the request comes from me.

But yes, otherwise, you’re correct that the dispatch routine doesn’t work on input which isn’t dividable by the size of a byte because of the division applied to truncate `ᴄᴀʟʟᴅᴀᴛᴀ` to the selector. Perhaps recent compiler also show this behavior, but this has to be tested.

**Comment by chriseth** [comment]
I could not find the selector you mentioned in the bytecode of the linked contract. The dispatch routine seems to always compare against a 4 byte value and also the `PUSH1 0xe0
PUSH1 0x02
EXP
PUSH1 0x00
CALLDATALOAD
DIV` part seems correct.

**Comment by ytrezq** [comment]
@chriseth : oh sorry. Wrong contract. [Indeed](https://etherscan.io/address/0xb3775fb83f7d12a36e0475abdd1fca35c091efbe#code).

**Comment by chriseth** [comment]
In that contract, I can only see a check against `0x10d0ffdd`. Can you please describe the bug in more detail? Which component do you think is affected and how did you encounter the bug? I currently cannot imagine how four bits could be truncated during execution.

**Comment by ytrezq** [comment]
@chriseth : oh yes. Sorry. that’s not the input I used. I edited the original comment.

**Comment by erak** [comment]
@ytrezq Looking at the contract you mentioned I can't find the signature (even less bytes) at all. Just to wrap up: your bug report says that in this contract here: https://etherscan.io/address/0xb3775fb83f7d12a36e0475abdd1fca35c091efbe#code, you'd assume a check against `0x10d0ffdd`, which is `0x10d0ffda` in your case?

**Comment by ytrezq** [comment]
@erak : `0x10d0ffdd` is `calculateTokensReceived(uint256 _ethereumToSpend)`. And the point is truncation isn’t up to a full byte.

I suppose all was said with that comment.

**Comment by chriseth** [comment]
I still can see no mention of `0x10dffd` or `0x10dffda` in the linked bytecode. To investigate this further, we need actual example code that triggers this behaviour.

**Comment by ytrezq** [comment]
@chriseth this doesn t dépends on a specific code and works on all selectors anyway.

**Comment by chriseth** [comment]
@ytrezq we are still struggling with reproducing this issue. Everything is working fine for us. Can you please describe again what you are doing? Maybe the error is not in the compiler but in the way the calldata is formatted by the library you are using?

**Comment by ekpyron** [comment]
Haha, I think I know what is happening:
If you split up the calldata from the OP into blocks of 4 bytes you get:
```
 10d0ffd
d0000000
00000000
00000000
00000000
00000000
0000e8ef
1e96ae38
```

In short: you're missing a zero :-).

**Comment by ekpyron** [comment]
So if you use
```
0x10d0ffdd00000000000000000000000000000000000000000000e8ef1e96ae38
```
instead of
```
0x10d0ffdd0000000000000000000000000000000000000000000e8ef1e96ae38
```
that should fix your issue.

**Comment by ytrezq** [comment]
@ekpyron correct, but the function selector is still `10d0ffdd` (I mean the fu data is still at the correct place in the selector) so it should call the function.
This is because solidity performs a division on input data in order to extract the selector. But in the case the length doesn t end on a byte, there s truncation.

**Comment by ekpyron** [comment]
@ytrezq Here it very much depends on what tool you use to parse this hex string and use it as calldata. To me it seems like that tool parses the hex string as 256-bit integer and then stores it as big endian. So the first four bytes will end up being ``010d0ffd``, which is *not* the correct signature.

Which tools *do* you use for that? To me it seems that this is rather an issue with the tooling than with the solidity compiler.

**Comment by ytrezq** [comment]
I used the remix debugger of etherscan.
For me I thought the ethereum vm behave the same way.

**Comment by ekpyron** [comment]
I'm pretty sure that the division is correct, but that on your input the etherscan debugger will pass ``010d0ffd`` as the first four bytes of calldata and **not** ``10d0ffdd``.

**Comment by chriseth** [comment]
Some tools also silently prefix a `0` if the number of hex digits is odd.

**Comment by ytrezq** [comment]
@chriseth but nothing is prefixed on etherscan.
I just saw `0x10d0ffd` on the stack instead of `0x10d0ffdd` assuming the real vm behave the same way.

**Comment by chriseth** [comment]
@ytrezq then let's try to find out where that stack entry came from. Do you have a transaction that shows the behaviour on etherscan?

**Comment by axic** [comment]
I think this may be more of an issue for Remix. @ytrezq please open an issue on https://github.com/ethereum/remix-ide.

Please provide an example stack trace on Remix so we can reopen this and further discuss, if you think it is a problem in the compiler.
