### ISSUE TITLE
[BLOCKER] Upgrade EVMOne to support Istanbul

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7544]
Before this upgrade, we cannot release 0.5.13 because selfbalance would be untested.

**Comment by Marenz** [comment]
ref https://github.com/ethereum/solidity/pull/7543

**Comment by bshastry** [comment]
Depends on evmc 7.0 release (see https://github.com/ethereum/solidity/issues/7310#issue-486391895)
