### ISSUE TITLE
2 Bugs report in SOLC Compiler found with fuzzing with AFL

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#7546]
In the contract below :

```
pragma experimental ABIEncoderV2;
contract C {
    struct S { uint a; T[222222222222222222222222222] sub; }
    struct T { uint[] x; }
    function f() public returns (uint, S memory) {
    }
}
```

I found this bug report :

Internal compiler error during compilation:
/build/solc/parts/solidity/src/libsolidity/ast/Types.cpp(1852): Throw in function virtual dev::u256 dev::solidity::ArrayType::memoryDataSize() const
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Array size does not fit u256.
[dev::tag_comment*] = Array size does not fit u256.

Also in the contract below :

```
contract test {
    modifier mod() { _; }

    function f() public {
        mod  ;
    }
}
```
the bug report was that :

Internal compiler error during compilation:
/build/solc/parts/solidity/src/libsolidity/codegen/ExpressionCompiler.cpp(1672): Throw in function virtual void dev::solidity::ExpressionCompiler::endVisit(const dev::solidity::Identifier&)
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Identifier type not expected in expression context.
[dev::tag_comment*] = Identifier type not expected in expression context.

## Environment

- Compiler version: 0.5.11+
- Target EVM version (as per compiler settings): 0.5.11+commit.22be8592.Linux.g++
- Framework/IDE (e.g. Truffle or Remix): Remix (i found it from command line, while fuzzing the solc compiler)
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 18.04

**Comment by erak** [comment]
@CHM1993 Thanks for the report! I'm closing this now in favor of two separate issues: https://github.com/ethereum/solidity/issues/7549 and https://github.com/ethereum/solidity/issues/7550.

**Comment by chamitro** [comment]
You are welcome :)
I hope this was useful. But is this a compiler issue ?

**Comment by Marenz** [comment]
> I hope this was useful. But is this a compiler issue ?

And Internal Compiler Error is always a compiler issue :)

**Comment by chamitro** [comment]
So there is a problem in the compiler that is "triggered" by the contracts
that were mentioned, and not a problem in the contracts?

**Comment by Marenz** [comment]
Well, one doesn't exclude the other. There can be invalid code that we don't properly check in the compiler and thus triggers an internal sanity check. The solution is then to add more checks and output a proper, helpful error message. I think both the code examples in this issue are like that.

The first one creates a way to big array for the index data type, we should catch something like that in the compiler and output an error "index too big" or so.
The second one references a function modifier outside the function signature which I believe isn't legal either. Here we need to add a check for that, too.

**Comment by chamitro** [comment]
Thank you for the details.
