### ISSUE TITLE
InternalCompilerError: I sense a disturbance in the stack: 4 vs 5

### ISSUE THREAD

**Issue by chatch** [ethereum/solidity#7558]
## Description

Attempting to compile a contract (https://gist.github.com/chatch/8a7087eb5b55b9b994d52c68d47cb54c) I get "InternalCompilerError: I sense a disturbance in the stack: 4 vs 5".

The contract is the Chainlink LinkToken.sol with changes to make it work with Solidity >= 0.5.0.

Remix Link: https://remix.ethereum.org/#gist=8a7087eb5b55b9b994d52c68d47cb54c&optimize=false&version=soljson-v0.5.12+commit.7709ece9.js

## Environment

- Compiler version: soljson-v0.5.12+commit.7709ece9.js
- Target EVM version (as per compiler settings): 'compiler default'
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: JS
- Operating system: Ubuntu

## Steps to Reproduce

Go to the remix link above which preloads the contract. 
Invoke the compiler and it will fail.

**Comment by chatch** [comment]
I discovered a single line in the contract causing the error: https://gist.github.com/chatch/8a7087eb5b55b9b994d52c68d47cb54c#file-linktoken-sol-L66

If I change this to "linkERC20Basic(this).transfer(_to, _value);" as I have here: https://github.com/chatch/LinkTokenv0.5/commit/2eb88a5774cab74d94323e7abd7cc5d55f7289ba then the code compiles fine.

**Comment by Marenz** [comment]
Smaller test case:
```
pragma solidity >= 0.5.8;


contract linkERC20Basic {
  function transfer(address to, uint256 value) public returns (bool);
}


contract ERC677 is linkERC20Basic {
  function transferAndCall(address to, uint value, bytes memory data) public returns (bool success);
}

contract ERC677Token is ERC677 {
  function transferAndCall(address _to, uint _value, bytes memory _data)
    public
    returns (bool success)
  {
    ERC677(super).transfer(_to, _value);
  }
}

contract linkBasicToken is linkERC20Basic {

  function transfer(address _to, uint256 _value) public returns (bool) {
  }
}

contract LinkToken is linkBasicToken, ERC677Token {
}

```

**Comment by Marenz** [comment]
The problem is related to the use of the keyword `super` vs `this`

**Comment by chatch** [comment]
Hi @Marenz, yes that's right, see my comment above https://github.com/ethereum/solidity/issues/7558#issuecomment-544814691 also.

But the compiler should not throw an InternalCompilerError right?

**Comment by Marenz** [comment]
> Hi @Marenz, yes that's right, see my comment above #7558 (comment) also.

I saw, but it wasn't super clear why the other line worked as you also changed the type you cast to ;)

> But the compiler should not throw an InternalCompilerError right?

Of course, an ICE is always a bug no matter what :)

**Comment by Marenz** [comment]
Even smaller use case:

```
pragma solidity >= 0.5.8;

contract S
{
	int o;
	function foo() public returns (int) { return o = 3; }
}

contract B is S
{
	function fii() public
	{
		o = S(super).foo();
	}
}
```
