### ISSUE TITLE
solc import of dot relative paths ("../File.sol") ignores the dots

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#757]
Originally posted by @ryanreich as https://github.com/ethereum/webthree-umbrella/issues/682 and moved here.

A file such as 

```
import "../File.sol";
```

will raise the `solc` error

```
<stdin>:1:1: Error: Source "File.sol" not found: File not found.
import "../File.sol";
^-------------------^
```

whether or not `../File.sol` actually exists.

**Comment by kidwai** [comment]
I am given the following more conclusive bit of information (again in both scenarios):

```
[ momo : contracts ] $ solc sol/ticker.sol
sol/ticker.sol:1:1: Error: Source "adder.sol" not found: File outside of allowed directories.
import "../adder.sol";
```

**Comment by chriseth** [comment]
This is intentional: solc does not access arbitrary directories in the host filesystem (to prevent things like `import "../../../../../../etc/passwd";`. If you want to allow this, you have to add such a directory to the directory remappings:

```
solc =. sol/ticker.sol
```

**Comment by kidwai** [comment]
Right. Thanks.

**Comment by HaleTom** [comment]
@chriseth @kidwai in which config file does one put this remapping?

(I'm getting this as a `solc` error inside `vim`.)

I couldn't find it in http://solidity.readthedocs.io/    Is there any doco on this remapping?
