### ISSUE TITLE
local variable in solidity

### ISSUE THREAD

**Issue by tharinduvindula** [ethereum/solidity#7571]
## Abstract

can you increase stack size for local variables 
![Capture3](https://user-images.githubusercontent.com/43117293/67542800-22619700-f70c-11e9-9ed1-472389f16525.JPG)

**Comment by erak** [comment]
@tharinduvindula The number of accessible stack elements is a property of the EVM and can't be changed by the compiler. There is a draft EIP that targets this issue though: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-663.md.

Please consider e.g. decreasing the number of parameters and / or return parameters of your function. Most of the times you can work around this limitation by simplifying and modularizing your functions. You can also reach out to https://gitter.im/ethereum/solidity for further advice.

I'll close this issue for now, please feel free to re-open if needed.
