### ISSUE TITLE
Check that we have a test for chainid() and selfbalance() for pre-istanbul VMs

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7577]
## Description

With https://github.com/ethereum/solidity/pull/7539, we make usage of `SELFBALANCE` which will, along with `CHAINID`, be introduced by the istanbul EVM. We need to test pre-instabul VMs once evmone was updated with https://github.com/ethereum/solidity/issues/7544.

## Specification

Additional test cases for the above instructions need to be added. See https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SolidityExpressionCompiler.cpp#L620 for reference.

**Comment by bshastry** [comment]
See https://github.com/ethereum/solidity/pull/7539/files#r335364632

**Comment by chriseth** [comment]
The tests are in test/libsolidity/InlineAssembly.cpp
