### ISSUE TITLE
JSON output: empty fields

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#758]
The JSON output is a bit inconsistent when dealing with missing fields.

For example an abstract contract might not have bytecode and opcodes, in such a case:
- assembly: null
- bytecode: ""
- opcodes: ""
- runtimeBytecode: ""
- srcmap: ""
- srcmap-runtime: ""

In the case when a contract doesn't have an interface (only fallback is implemented):
- interface: "[]\n"

I would think all of these should be null (or the field omitted from JSON) if they are not defined.

**Comment by chriseth** [comment]
I do not agree 100% here. If the contract does not implement any interface functions, its interface should be the empty array. There is also a difference between an empty assembly (empty array) or non-existing assembly (null).

**Comment by axic** [comment]
In what cases do you make a distinction between empty and non-existing assembly?

Should a non-abstract contract ever have an empty `assembly` (it should have the deploy code, while `runtimeAssembly` doesn't)? Isn't that an error condition?

**Comment by axic** [comment]
@chriseth in what cases do we have an empty assembly?

**Comment by chriseth** [comment]
I think in practise we don't but we might extend the optimizer so that it can produce empty assembly for a valid contract.

**Comment by axic** [comment]
Can that be considered a "valid" bytecode though? Obviously it cannot be deployed :smiley:

**Comment by chriseth** [comment]
Of course it can. It is a valid creation bytecode that will create an empty contract. Note that the bytecode `"0x"` is semantically identical to `"0x00"`

**Comment by axic** [comment]
Do you mean that because of the mess RLP is it gets encoded as a single zero byte ?

**Comment by chriseth** [comment]
No, the EVM is defined so that access beyond the end of the bytecode returns zero.

**Comment by axic** [comment]
You might be able to make a `CREATE` call with length 0, but most of the clients are implemented the way that they distinguish a _creation transaction_ as one having no `to` field and a `code` field which is not 0 length. So you wouldn't be able to use the returned empty bytecode field with a transaction.

**Comment by axic** [comment]
Closed by #1387.
