### ISSUE TITLE
[RFC] modeling gas cost in yul interpreter

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7585]
## Description

The yul interpreter has no notion of gas cost because that is left to the underlying EVM implementation if I understand correctly.

However, it may be beneficial to model gas costs to flag instances where the yul optimizer increases gas consumption (one data point for consideration is #7472 )

**Comment by chriseth** [comment]
I would not do this at the current time, since the optimizer is not taking gas costs into account at all.
Furthermore, this is really trade-off between code size and runtime cost, where it is not always clear which route to take.
