### ISSUE TITLE
Constants in Yul (and other Language Features)

### ISSUE THREAD

**Issue by SilentCaesar** [ethereum/solidity#7591]
## Abstract

Yul has become a central part of our optimistic rollups architecture. The ability for us to work directly in memory across runtime with macro like function has been a game changer with serious gas optimization benefits.

We formally request a Yul language feature: Constants.

Currently, Yul is simplistic allowing only `let` statements. We propose the addition of constants for use across Code blocks. We understand Solidity Constants have been introduced in Solidity Assembly. We simply ask this be extended into pure Yul compilation and not just Solidity.

We also propose some other interesting constant like language features, which may in the end be out of scope for the Yul project.

## Motivation

1) Not Available: There currently is no constants in Yul or anything akin to that (other than optimized let statements)
2) Safety: It would allow for safer more structured code without bloating the stack as the compiler would simply fill the constants in during compilation.
3) Language Design: Constants are an arguably essential language feature for any modern programming language. 
4) Readability: Currently Yul is not very readable. When working at a low-level with memory in particular, the last thing you want is to be plugging in raw numbers anywhere as it makes decreases code readability, it's hard enough already, why make it worse.

## Specification Possibilities

In code-block option `const nick := 4`:

```
object "CodeBlockOption" {
  code {
      const nick := 4
      
      log1(0, 0, nick)

      // logs topic 4
  }
}
```

Out of code-block option `const "nick" hex"4"`:

```
object "OutOfCodeBlockOption" {
  code {
      log1(0, 0, nick)

      // logs topic 4
  }
  const "nick" hex"4"
}
```

We would also ask you consider that constants be contract wide in scope, and can be used across all code blocks. We understand this might break isolation or scope paradigms.

Out of code-block global option `const* "nick" hex"4"`:

```
object "OutOfCodeBlockGlobalOption" {
  code {
      log1(0, 0, nick)

      // logs topic 4
  }
  object "SecondObject" {
     code {
        log1(0, 0, nick)

      // logs topic 4
     }
  }
  const* "nick" hex"4"
}
```

## Backwards Compatibility

The proposed language change would not be backward compatible.

## Additional Consideration `Enums`

In addition to this, Enums would also be a great help in Yul and we don't think it would add very much bulk at all. This may be stretching Yul's current paradigm of simplicity, but we are interested to get everyone's thoughts.

```
object "EnumOptions" {
  code {
      enum Colors {
           Red,
           Blue,
           Green
      }
      
      log1(0, 0, Colors.Blue)

      // logs topic 1
  }
}
```

## Additional Consideration `Virtual Memory Structs`

This is our least generalizable and most opinionated language feature we request. We understand this may not be useful for many, but we thought we would submit it for consideration regardless.

Often times, many execution use-cases have 32 byte chunk structures. We propose a way for virtually manage these for better code readability.

Here we specify a virtual memory structure which starts at memory position `0`. 

```
struct32 Colors 0 {
      Red,
      Blue,
      Green
}
```

Here `Red` would be compiled to `mload(0)`, `Blue` would be compiled to `mload(32)`, and `Green` would be compiled to `mload(64)`.

```
object "Struct32Option" {
  code {
      mstore(0, 0xff0000)
      mstore(32, 0x0033cc)
      mstore(64, 0x003300)

      struct32 Colors 0 {
           Red,
           Blue,
           Green
      }
      
      log1(0, 0, Colors.Blue)

      // logs topic 0x0033cc
  }
}
```

A packed virtual struct could also be added and used as follows:

```
object "PackedStructOption" {
  code {
      mstore(0, 0xff00000033cc003300)

      struct Colors 20 { // starts at memory position 20
           Red: 4, // 4 byte length specifier
           Blue: 4,
           Green: 4
      }
      
      log1(0, 0, Colors.Blue)

      // logs topic 0x0033cc
  }
}
```

Here `Colors.Blue` would simply compile to: `div(mload(24), exp(2, sub(256, mul(4, 8))))`

This language feature would greatly reduce code complexity and greatly enhance readability. We understand this is asking a lot from Yul, but we think for memory management these small additions could make an enormous difference.

## Special Thanks

Thank you to the Solidity team for creating low-level Assembly and Yul, it really makes a massive difference in execution sensitive scaling.

**Comment by axic** [comment]
Please see #5928 for a previous discussion.

**Comment by chriseth** [comment]
It's always a pleasure to meet power-users! Maybe it is best to have a call to discuss your needs and our abilities in more details. Can you either come to https://gitter.im/ethereum/solidity-dev or send me a mail at chris@ethereum.org? Thanks!

**Comment by SilentCaesar** [comment]
@axic the full word `constant` is fine, but I prefer `const` which is common among many languages.

@chriseth I'll send you an email. Our current code will be re-factored and most likely sit around 3000 lines of Yul when it's finished. I'd be happy to go over our needs.

I also have some thoughts around writing virtual memory structures to memory:

```
object "PackedStructOptionWithInstantiation" {
  code {
      mstore(0, 0xff00000033cc003300)

      struct Colors { // struct is now a virtual concept
           Red: 3, // 3 byte length specifier (or defined as "24" for "u24")
           Blue: 3,
           Green: 3
      }

      log1(0, 0, Colors(20).Red) // would log topic 0xff0000
      
      Colors(60, { // 60 is now the write position
           Red: 0xff0000, // must be 3 byte or u24 chunk
           Blue: 0x0033cc,
           Green: 0x003300
      })

      log1(0, 0, mload(60)) // would log topic 0xff00000033cc003300
  }
}
```

Example use case with an ecrecover scenario:

```
object "TightPackedECRecover" {
  code {
      // memory at 0: 0x1c613fa3f3118416dafb350a41d8c41d5e295a1b26760d0724f11063096bab24c347f290802fc787ae065ce6f5dedcbdd15537d7b6c7f1ea8c4629214af502e760

      struct Signature {
           v: 1,
           r: 32,
           s: 32
      }

      // here we allow the struct to be passed into `ecrecover`
      // the value actually getting pushed to stack is 0 (i.e. the structs starting memory position), 
      // when used in `ecrecover` however it reacts linguistically like a struct during compilation.
      // We can place a maximum chunk size of 32 bytes per struct property, 
      // so that it plays nicely with other Yul language components like `mstore` for example.

      function ecrecover(sig) -> address {
         mstore(128, sig.v) // Yul picks up this is a virtual struct and allows you to access v, r, s here
         mstore(160, sig.r) // Yul would resolve r to `mload(0 + 1)`
         ....
      }

     // here Signature(0) simply resolves to 0 in the stack

      log1(0, 0, ecrecover(Signature(0))  // would log topic address returned form ecrecover

      // A nice side feature of this would also be accessing struct lengths like so

     log1(0, 0, Signature.r) // would return 32
  }
}
```
