### ISSUE TITLE
solc generating different evm code in OSX than in Ubuntu

### ISSUE THREAD

**Issue by iurimatias** [ethereum/solidity#76]
Deploying the code generated in OSX does not work either (resulting address getCode is 0x0), while the Ubuntu one works fine.

Binary generated in OSX (0.1.2-5c3bfd4b)
606060405260405160208060f68339016040526060805190602001505b806000600050819055505b5060c28060346000396000f360606040526000357c0100000000000000000000000000000000000000000000000000000000900480632a1afcd914604b57806360fe47b114606a5780636d4ce63c14607b576049565b005b6054600450609a565b6040518082815260200191505060405180910390f35b607960048035906020015060a3565b005b608460045060b1565b6040518082815260200191505060405180910390f35b60006000505481565b806000600050819055505b50565b6000600060005054905060bf565b9056

Binary geneated in Ubuntu (0.1.2-0)
606060405260405160208060f78339016040526060805190602001505b806000600050819055505b5060c28060356000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900480632a1afcd914604b57806360fe47b114606a5780636d4ce63c14607b576049565b005b6054600450609a565b6040518082815260200191505060405180910390f35b607960048035906020015060a3565b005b608460045060b1565b6040518082815260200191505060405180910390f35b60006000505481565b806000600050819055505b50565b6000600060005054905060bf565b9056

**Comment by LianaHus** [comment]
https://github.com/ethereum/solidity/issues/17

**Comment by chriseth** [comment]
For the examples above, the compiler versions are different. Ubuntu had 0.1.2-0, OSX had 0.1.2-5c3bfd4b. The commit that caused the change in the bytecode is https://github.com/ethereum/libethereum/commit/6fc2f17cd05652182a8b338b95b399486ed92fc7 .
