### ISSUE TITLE
Stack too deep error

### ISSUE THREAD

**Issue by pavithraviswanathan** [ethereum/solidity#7624]
I am using a structure which holds more than 20 parameters When I use more than 16 parameters in my function, I am getting stack too deep error. I tried passing parameters as an array by using **pragma experimental abiencoderv2** feature which can't be used in a production environment. How to pass more than 16 parameter in a single function  in solidity?

**Comment by leonardoalt** [comment]
Hi @pavithraviswanathan ,
The number of accessible stack elements (16) is a property of the EVM and can't be changed by the compiler. There is a draft EIP that targets this issue though: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-663.md.

Please consider e.g. decreasing the number of parameters and / or return parameters of your function. Most of the times you can work around this limitation by simplifying and modularizing your functions. You can also reach out to https://gitter.im/ethereum/solidity for further advice.

I'll close this issue for now, please feel free to re-open if needed.
