### ISSUE TITLE
library address and method calling

### ISSUE THREAD

**Issue by aihuawu** [ethereum/solidity#7625]
I am wondering why I can pass in a library addres but I can't call it's method.
see below. thanks.

george wu

```
library dog 
{
    function eat() public {}
}
library animal 
{
    struct t
    {
        dog d; // compiler ok
    }
}
contract c 
{
    function eat(dog d) internal
    { // the argument, compiler ok
        d.eat(); // compiler error
    }
}
```

**Comment by chriseth** [comment]
It should not be possible to declare such variables.

**Comment by Marenz** [comment]
@chriseth for clarification: You're saying it should not be possible to declare any variable of type library?

**Comment by chriseth** [comment]
exactly
