### ISSUE TITLE
`Compiled contract not found` error when not requesting output for inherited contract in Standard JSON

### ISSUE THREAD

**Issue by varasev** [ethereum/solidity#7627]
## Description

We have a [repository](https://github.com/poanetwork/posdao-contracts/tree/solc-bug) containing smart contracts and unit tests for them. When we compile the contracts with `truffle` and `solc` v0.5.11 or v0.5.12 (see [truffle's config](https://github.com/poanetwork/posdao-contracts/blob/solc-bug/truffle-config.js#L119-L128)), the `build` directory is created in repo's root directory as expected. After that, when we start unit tests,  we see the following error:

![image](https://user-images.githubusercontent.com/33550681/68204342-cf73c380-ffd8-11e9-9f22-b1023477038b.png)

However, if we remove the `build` directory (`rm -rf build`) and then restart the tests with `npm run test`, they start successfully.

But if we do the same for `solc` v0.5.10 (or v0.5.9), that works fine and the contracts are compiled successfully during the tests even when the `build` directory is not removed.

## Environment

- Compiler version: 0.5.11 or 0.5.12
- Target EVM version (as per compiler settings): constantinople
- Framework/IDE (e.g. Truffle or Remix): truffle 5.0.43
- EVM execution environment / backend / blockchain client: ganache-cli 6.6.0
- Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

To see the error, perform the next steps:

```bash
$ git clone -b solc-bug https://github.com/poanetwork/posdao-contracts
$ cd posdao-contracts
$ npm i
$ npm run compile
$ npm run test
```

To successfully start the same tests with `solc 0.5.10`, perform the next steps:

```bash
$ git clone -b solc-bug https://github.com/poanetwork/posdao-contracts
$ cd posdao-contracts
$ git checkout 3581cf3730f53848572104d95c465bb237d3936e
$ npm i
$ npm run compile
$ npm run test
```

**Comment by erak** [comment]
I was able to reproduce this behaviour and will start investigating.

**Comment by erak** [comment]
I couldn't find the time to dive deeper into debugging. Could someone else have look?

**Comment by chriseth** [comment]
Might be related to https://github.com/ethereum/solidity/issues/9565

**Comment by cameel** [comment]
I can confirm that this error is still happening with the latest versions of solc (0.7.3) and truffle (5.1.47)

I checked Solidity source and the `Compiled contract not found` is a message from one of our assertions, and not something that Truffle adds so it's clearly a bug in the compiler. But it's tricky to trigger. Only happens after Truffle compiles everything and then you change one contract and run `truffle compile` making it recompile just one file.

### Details
I managed to reproduce it after trimming down the contract considerably. Here's the shortest self-contained repro I managed to find so far. Run this in a shell in an empty directory with truffle installed globally:
```bash
truffle init

cat << EOF > contracts/BlockRewardAuRaBase.sol
contract Sacrifice {
    constructor() public payable {}
}

abstract contract BlockRewardAuRaBase {
    function _transferNativeReward() internal {
        new Sacrifice();
    }

    function _distributeTokenRewards() internal virtual;
}
EOF

cat << EOF > contracts/BlockRewardAuRaCoins.sol
import "./BlockRewardAuRaBase.sol";

contract BlockRewardAuRaCoins is BlockRewardAuRaBase {
    function transferReward() public {
        _transferNativeReward();
    }

    function _distributeTokenRewards() internal override {}
}
EOF

cat << EOF > truffle-config.js
module.exports = {
  compilers: {
    solc: {
      version: "0.7.3"
    }
  }
}
EOF

truffle compile
touch contracts/BlockRewardAuRaCoins.sol
truffle compile
```

Output from the last `truffle compile`:
```
Compiling your contracts...
===========================
> Compiling ./contracts/BlockRewardAuRaCoins.sol

CompileError: InternalCompilerError: Compiled contract not found.

Compilation failed. See above.
    at run (/usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:51:1)
Truffle v5.1.47 (core: 5.1.47)
Node v10.22.1
```

**Comment by cameel** [comment]
I managed to reproduce it with `solc` but only via the Standard JSON interface. Does not happen if I run `solc --combined-json srcmap` on the files from the repro above.

I don't see anything specific that would obviously be the cause. Removing parts of the code or putting it all in a single file removes the error. Not requesting output for `BlockRewardAuRaCoins` or requesting something else than the `evm.*` properties removes it too. Requesting `*` instead of `evm.bytecode.sourceMap` also does not trigger the error.

The paths don't seem to really matter. It fails even if I call the files to `A.sol` and `B.sol`. Or if the paths are absolute (Truffle actually uses absolute paths). Removing `./` from the `import` does not make the error go away either. I suspected that it might be affected by the files existing on disk under these paths but apparently not. The result is the same whether they exist or not.

### Repro
```bash
solc --standard-json input.json
```

`input.json`:
```json
{
    "language": "Solidity",
    "sources": {
        "BlockRewardAuRaBase.sol": {
            "content": "
                contract Sacrifice {
                    constructor() public payable {}
                }

                abstract contract BlockRewardAuRaBase {
                    function _transferNativeReward() internal {
                        new Sacrifice();
                    }

                    function _distributeTokenRewards() internal virtual;
                }
            "
        },
        "BlockRewardAuRaCoins.sol": {
            "content": "
                import \"./BlockRewardAuRaBase.sol\";

                contract BlockRewardAuRaCoins is BlockRewardAuRaBase {
                    function transferReward() public {
                        _transferNativeReward();
                    }

                    function _distributeTokenRewards() internal override {}
                }
            "
        }
    },
    "settings": {
        "outputSelection": {
            "BlockRewardAuRaCoins.sol": {
                "BlockRewardAuRaCoins": ["evm.bytecode.sourceMap"]
            }
        }
    }
}
```

Output (passed through `jq` for readability):
```json
{
    "errors": [
        {
            "component": "general",
            "formattedMessage": "InternalCompilerError: Compiled contract not found.\n",
            "message": "Internal compiler error (/solidity/libsolidity/codegen/CompilerContext.cpp:256):Compiled contract not found.",
            "severity": "error",
            "type": "InternalCompilerError"
        }
    ],
    "sources": {
        "BlockRewardAuRaBase.sol": {
            "id": 0
        },
        "BlockRewardAuRaCoins.sol": {
            "id": 1
        }
    }
}
```

Failing assertion:
```c++
shared_ptr<evmasm::Assembly> CompilerContext::compiledContract(ContractDefinition const& _contract) const
{
	auto ret = m_otherCompilers.find(&_contract);
	solAssert(ret != m_otherCompilers.end(), "Compiled contract not found.");
	return ret->second->assemblyPtr();
}
```

**Comment by cameel** [comment]
@chriseth 
> Might be related to #9565

I think it's a different problem with similar symptoms. There is not circular dependency here and the contracts compile fine when not using standard JSON.

Maybe it's a problem with the order in which the contracts are compiled?

**Comment by varasev** [comment]
@cameel As far as I remember, I managed to fix this in our other repo in this commit: https://github.com/xdaichain/stake-token/commit/ad79abbaa4d1f91d73e80cc4b3f1b234a0ca6570#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 - there was the same issue with updating solc v0.5.10 to v0.5.12 - seems updating `ganache-cli`, `truffle`, and `solidity-coverage` solved that, but I'm not sure of the reason.

**Comment by cameel** [comment]
@varasev Thanks for the info. I checked that commit and looks like it didn't really fix the issue, just made it much harder to trigger it. Which is a nice workaround. Great to hear that you found a way to make it work for you.

The issue is the compiler though, not in the JS libraries. It's the move of `mocks/` from `test/` to `contracts/` that really helped. When the mocks were inside `test/` Truffle compiled them separately when you ran `truffle test`. Now that everything is inside `contracts/`, all contracts get compiled together. One of the necessary conditions to trigger this error seems to be partial recompilation so if you compile everything at once, you're fine. I can still trigger it in your repo by forcing Truffle to compile just the mocks:

```bash
git clone https://github.com/xdaichain/stake-token.git
cd stake-token/
git checkout ad79abbaa4d1f91d73e80cc4b3f1b234a0ca6570
npm install
truffle compile
touch contracts/mocks/*
truffle compile
```

Output from the second `truffle compile`:
```
Compiling your contracts...
===========================
> Compiling ./contracts/mocks/BridgeMock.sol
> Compiling ./contracts/mocks/BridgeTokenMock.sol
> Compiling ./contracts/mocks/DistributionMock.sol
> Compiling ./contracts/mocks/ERC677MultiBridgeTokenMock.sol
> Compiling ./contracts/mocks/EmptyContract.sol
> Compiling ./contracts/mocks/MultipleDistributionMock.sol
> Compiling ./contracts/mocks/RecipientMock.sol
> Compiling ./contracts/mocks/TokenMock.sol

CompileError: InternalCompilerError: Compiled contract not found.

Compilation failed. See above.
    at run (/usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:51:1)
Truffle v5.1.47 (core: 5.1.47)
Node v10.22.1
```

**Comment by varasev** [comment]
@cameel Yeah, seems moving `mocks` from `test` to `contracts` helped.
