### ISSUE TITLE
Improve error messages for unsupported calldata arrays in old code generation.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7635]
Given that we closed https://github.com/ethereum/solidity/pull/6983 and https://github.com/ethereum/solidity/pull/6881 and decided not to actually fix https://github.com/ethereum/solidity/issues/6835, we should at least provide a decent error message indicating possible workarounds for the cases that won't be implemented in old code generation.

**Comment by ekpyron** [comment]
https://github.com/ethereum/solidity/issues/8448 falls under this as well.

**Comment by ekpyron** [comment]
To be more precise: things like assigning abiencoderv2-only calldata types to memory or storage should be at least a proper ``unimplemented`` assertion in old codegen and - as far as possible - we should try to make sure that that's all cases like this.

**Comment by ekpyron** [comment]
Looking at which code parts https://github.com/ethereum/solidity/pull/6983/ and https://github.com/ethereum/solidity/pull/6881/ would have touched might help - that may very well pretty much be where we're missing the assertions.

**Comment by Marenz** [comment]
@ekpyron does #7929 also apply to this ticket?

**Comment by ekpyron** [comment]
@Marenz Yep, it does, but as far as I can see it's also addressed by this as well. I'm closing it.
