### ISSUE TITLE
Solidity Voting System Known Bug Blockchain

### ISSUE THREAD

**Issue by kselva1988** [ethereum/solidity#7645]
Recently i have refer the Voting system example in https://solidity.readthedocs.io/en/v0.4.24/solidity-by-example.html . i have some concern, if voting system is based on name and ip address there is an change to do duplicate votes . like changing the IP using VPN software and they can vote again. in case  if we are using SSN, or PAN card then third parties are might have lot information about the peoples and they can able to do the votes instead of actual peoples. do we have any way to short out this

**Comment by bshastry** [comment]
@kselva1988 please note that the solidity by example page is mainly meant to showcase the features of the Solidity programming language, not to propose protocols for specific use cases such as electronic voting. So, I am going to close this issue for now. Feel free to reopen it in case I misunderstood your query.

Perhaps https://github.com/ethereum/EIPs/issues is better suited for the discussion you initiated?
