### ISSUE TITLE
Disallow leading/trailing/consecutive dots in Yul symbols

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7646]
From https://github.com/ethereum/solidity/pull/7641#discussion_r343039367

**Comment by axic** [comment]
@ekpyron @mijovic @hrkrshnn I think you guys worked on Yul objects where dots are used. Maybe we should revive this issue and make a quick decision.

**Comment by ekpyron** [comment]
Can we just disallow *any* dot in Yul identifiers :-)? I don't see a compelling reason for having them and it gets confusing, since apparently we give dots more and more special meaning. So if there's no reason against this, I'd remove dots from normal Yul identifiers in 0.7.

**Comment by mijovic** [comment]
> Can we just disallow _any_ dot in Yul identifiers :-)? I don't see a compelling reason for having them and it gets confusing, since apparently we give dots more and more special meaning. So if there's no reason against this, I'd remove dots from normal Yul identifiers in 0.7.

I completely agree with this. Only if there is some really big reason for leaving dots as part of Yul identifiers we can think of leaving them. I personally don’t see the reason to leave them at all.

**Comment by axic** [comment]
There were some  proposals, such as the builtins (`i64.shl` for wasm) or for user-defined types (#3525), to use dots in their identifiers. I think enum access (#7641) would be a special case (similar to object access) and not an identifier, but a path.

**Comment by ekpyron** [comment]
In general Yul objects are a bit different, since they have their own namespace (haven't they?) and don't collide with anything else anyways, right? I haven't really followed dots in yul objects recently.

Builtins with dots could just be an exception. Same for casts in user-defined types, although we could also just use a solution without dots there. But yeah - I'm not entirely sure.

In any case, the current (non-)solution to https://github.com/ethereum/solidity/pull/7641#discussion_r343032250 is rather hacky and we should come up with something better.
Even though an enum access is a path and not an identifier, it's still the exact same name space - and since there is paths that use dots in that namespace now, we should avoid creating "fake paths" as identifiers...

**Comment by ekpyron** [comment]
Of course the enum stuff only ever applies to solidity yul... but we could think of it as reserving dots generally as reserving parts of the identifier namespace for stuff outside of the yul code itself...

**Comment by axic** [comment]
So that means dots would be allowed for identifiers in the grammar, except for variable declarations (`let`, parameters, return values)?

And the original question from this topic still applies: allow/reject leading/trailing dots? I vote for rejecting them, in any case.

**Comment by ekpyron** [comment]
If we start to generally treat dots as some kind of namespace mechanism, then we should definitely disallow leading and trailing ones, yes.

But on the other hand: if we *don't* start treating dots as some kind of path/namespace mechanism in general, then I don't really see a reason for disallowing leading or trailing ones either actually...

About the grammer: that depends :-). As long as we *don't* introduce anything using dots within yul, so as long as we don't have ``i64.shl`` or use it in user-defined-conversion builtins, I'd say there are actually no dots in the grammar of "standard Yul" - and solidity inline assembly Yul would *add* them to the grammar of a specialized version of inline-assembly Yul...
Or we could go the other way and make identifiers in the standard Yul grammar always explicitly allow paths and distinguish them from "names" in variable declarations, parameters and return values...
But yeah, I realize that I really haven't thought this through entirely, I'm not really sure about it :-).

**Comment by chriseth** [comment]
Dots kind of have to be regular characters for identifiers because of the wasm builtins. If they are regular characters, they should also be allowed at least at the end - we usually only have restrictions about how identifiers can start. What is the benefit of disallowing dots at the ends?

**Comment by axic** [comment]
What is the benefit of having dots at the end? You mention wasm -- that does not requite leading/trailing dots, even if we want to follow that notation. In other notations people use underscores for wasm opcode, i.e. `i32_const`.

**Comment by chriseth** [comment]
The benefit is simplicity. What is the benefit of having `_` at the end?

**Comment by axic** [comment]
> What is the benefit of having _ at the end?

I'm confused. You are advocating of allowing a dot at the end and then drop this question.

I dislike leading/trailing underscores personally, but I don't think underscore and dot can be compared, because dot has a special meaning in many languages, including Solidity, and potentially Yul with allowing enums.

**Comment by chriseth** [comment]
I'm saying that if we allow `.` to be part of identifiers, then we should not make any restriction about where in the identifier it can appear.

**Comment by ekpyron** [comment]
I think it's weird if we allow both arbitrary dots in arbitrary identifiers and at the same time use them for resolving e.g. solidity enums. So at least in solidity inline assembly yul, we should disallow dots in identifiers as long as they don't refer to such a namespace. I don't see much harm in having the wasm prefix namespaces being an exception to this.

**Comment by chriseth** [comment]
Sounds good!

**Comment by chriseth** [comment]
Discussion: Disallow dots in user-defined identifiers in solidity inline assembly (but not in yul in general).

**Comment by axic** [comment]
I would also suggest to ensure we disallow dots followed by dots, e.g. `i64.....add`

**Comment by ekpyron** [comment]
Not a requirement for this issue and just a thought, but we might consider just reserving some identifiers in solidity inline assembly - such as ``abi``. With the dots being reserved we could then at some point consider exposing abi encoding and decoding functions as ``abi.encode.t_uint256`` or something like that...

**Comment by axic** [comment]
Closing this as the original issue was implemented. Created a new issue for the second part (user-defined in inline assembly) to track it: #9345.
