### ISSUE TITLE
Cannot Hash Struct

### ISSUE THREAD

**Issue by Denton-L** [ethereum/solidity#765]
Here's a barebones version of the code I'm attempting to run:

```
contract Broken {
    struct Struct {}

    function getStructHash() returns (bytes32) {
        Struct memory s = Struct();
        return sha3(s);
    }
}
```

I am using browser-solidity on Chromium on Linux and it is throwing me an Uncaught Javascript exception.

**Comment by ethernomad** [comment]
Duplicate: https://github.com/ethereum/solidity/issues/332

**Comment by VoR0220** [comment]
We need to get the new struct refactor so that it's part of the ABI.
