### ISSUE TITLE
[yul] optimizer: Redundant check in expression simplifier?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7659]
## Description

I was curious why https://github.com/ethereum/solidity/blob/ed7be7b9c76c71ea1915a8f70eb42b337dc15c15/libyul/optimiser/ExpressionSimplifier.cpp#L51-L52 was never satisfied (i.e., Expression simplifier never returns early)

So, I spent some time understanding why, with the theory that perhaps some limitation of the test generator was leading to the constraint always being false.

The constraint is the following
```
  if (match->removesNonConstants && !SideEffectsCollector(m_dialect, _expression).movable())
```

which iirc means
  - the expression being visited by the expression simplifier matches a simplification rule that removes non constants (set A)
  - Side effects collector reports the same expression to be not movable (set B)

After spending some time reading optimizer code, I came to the conclusion that the intersection of sets A and B is essentially null and that is the reason for the check never being satisfied by any test generated by the fuzzer.

The way I reasoned about this is by first looking at all instructions that have a "not movable" side-effect. Most of this is documented here:
https://github.com/ethereum/solidity/blob/develop/libevmasm/Instruction.cpp#L179

If a "not movable" instruction contains a simplification rule pattern, we have a non-null intersection of sets A and B. In reality, there is no such instruction that is "not movable" for which we presently have a simplification rule pattern.

Did I get this right? Unless we expect to, one day, have a simplification rule for an unmovable instruction, we can do away with that if statement in the expression simplifier, since it is redundant. What do you think?

**Comment by chriseth** [comment]
Note that the side effects collector is run on the full expression, so what we actually want to determine is if some arguments to the instructions are non-movable. Since the expression simplifier is usually run after the expression splitter, the arguments tend to be variables which are always movable. There is one exception to this: Conditions in for loops cannot be split and thus could have non-movable arguments, but nowadays, we also have the "for loop condition into body" step, which could also prevent this line from being hit.

**Comment by bshastry** [comment]
Ah I see. I can reproduce the branch in question getting covered when ExpressionSimplifier step is run by itself. I can also reproduce the branch not getting covered when expression splitter is run before simplifier; also the case when the expression happens to be a for-loop condition and loop-condition-into-body followed by expression splitter making the branch false in expression simplifier.

Will mark this specific case as impossible to reach as the optimizer suite stands.
