### ISSUE TITLE
Support do {} while(); control structure

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#766]
do {} while (); can avoid code duplication in some situations.

**Comment by roadriverrail** [comment]
Hi there!  I'm new to the Solidity project, but I had a spare night and thought I'd try my hand at making a contribution on this front.  Casual testing suggests it's ok, but solc on the "development" branch crashes for asm and asm-json outputs on my Mac, so I need to switch over to my Linux machine in the morning to keep up the testing.  I also couldn't find a compiler test suite to add some appropriate tests to.

The PR is to hopefully get a conversation started so I can finish that up.

https://github.com/ethereum/solidity/pull/768

**Comment by ethernomad** [comment]
Amazing!

**Comment by roadriverrail** [comment]
I think we can close this one now.

**Comment by axic** [comment]
Implemented by #768.
