### ISSUE TITLE
Please add minimal examples for triggering fixed compiler bugs!

### ISSUE THREAD

**Issue by ytrezq** [ethereum/solidity#7667]
Were’re developing a tool to [test existing old compiler bugs in old smarts contracts where the source code and compiler version used is not known](https://github.com/ConsenSys/mythril/issues/1258#issuecomment-550580363).
We searched the specific issue numbers and/or commit which fixed `OptimizerClearStateOnCodePathJoin`and`OptimizerStateKnowledgeNotResetForJumpdest` but nothing was found leaving without knowing if the code works.

**Comment by chriseth** [comment]
These two bugs are really hard to trigger, I fear I cannot provide you with example code anymore.

**Comment by ytrezq** [comment]
@chriseth : would it be possible to have at least the issue number of the specific commit which fixed them ?

**Comment by Marenz** [comment]
This might be the issue for the first bug: https://github.com/ethereum/solidity/issues/692

**Comment by Marenz** [comment]
And this the second: https://github.com/ethereum/solidity/issues/1416

**Comment by chriseth** [comment]
Thanks, @Marenz  ! There are even examples linked in the issues!

**Comment by ytrezq** [comment]
Might still worth trying to add this into the codebase as finding specific issues proved to be hard.

**Comment by chriseth** [comment]
@ytrezq what do you mean by "add this into the codebase" - adding in which way?

**Comment by ytrezq** [comment]
@chriseth : add it to the files detailing the compiler issue names.

**Comment by axic** [comment]
Would make sense including the issue link in `bugs.json` instead?

**Comment by ytrezq** [comment]
@axic : issues themselves don’t contain the examples required to reproduce the bug most of the time.

**Comment by axic** [comment]
In `bugs.json` we have links to blog posts for major issues. Perhaps it makes sense to link to the github issues where there was no blog post.

Additionally we could introduce a field for `example` which links to some file, but that can easily become a large task because then one needs to provide an example for each of the affected versions of that bug. I think we may not have enough resources to do this, but likely would be accepting such patches!

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).
