### ISSUE TITLE
Consider warning about inline-assembly return

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7668]
... because it can circumvent protection through modifiers ( https://twitter.com/jalex_towle/status/1193578569634590723 ). I think there are only few real-world cases, where people would want that. We can exclude some cases:
 - modifiers that have no code after the `_`
 - functions that are external-only and do not have any "important" code after the inline-assembly block (to be debated)
 - functions that are not called from other functions

**Comment by jalextowle** [comment]
Thanks for adding this! I’ve actually been wanting to contribute to solidity for a while, so I’d be happy to try to help out on this.

**Comment by chriseth** [comment]
@jalextowle great! The first step would be to figure out when exactly to issue the warning, I think.
