### ISSUE TITLE
Pack multiple array items into individual slots

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#767]
If an array item size is e.g. 16 bytes, surely the compiler could generate code to store 2 items in each slot?

**Comment by axic** [comment]
I think that might be already happening?

**Comment by ethernomad** [comment]
Documentation is kind of ambiguous: https://solidity.readthedocs.io/en/latest/miscellaneous.html#layout-of-state-variables-in-storage

**Comment by chriseth** [comment]
It is done in storage but not in memory.

**Comment by ethernomad** [comment]
I think this only happens for arrays with a fixed number of items. State arrays with dynamic length use a full slot for each item as far as I can tell.

**Comment by ethernomad** [comment]
Actually you are right.
