### ISSUE TITLE
[Yul] Do not go through to `instructionInfo(m_instruction).name; tolower` in RuleList.cpp

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7676]

**Comment by christianparpart** [comment]
cleanup Parser::instructions() / Parser::instructionNames() (move to EVMDialect instead).

**Comment by axic** [comment]
> cleanup Parser::instructions() / Parser::instructionNames() (move to EVMDialect instead).

This was done.

@chriseth I think you refer to `libyul/optimiser/SimplifcationRules.cpp` and `Pattern::toExpression` in particular. Why is this a problem btw?

**Comment by chriseth** [comment]
It looks weird. The Builtins-semi-type should just contain the function names directly.

**Comment by axic** [comment]
Besides that almost every single use in the compiler does a first conversion to lower, can't we just keep it in lowercase and uppercase it for the single case (assembly output) needing it?

**Comment by chriseth** [comment]
Sure!
