### ISSUE TITLE
[Build] update evmone to v0.2.0 and clean up docker image

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7698]
## Abstract

evmone v0.2.0 is required to
- ~~istanbul tests (via isoltest that requires shared evmone library)~~
- speed up tests
- ~~abiv2_proto_fuzzer (requires statically built evmone library)~~

Also the docker image that is currently used manually builds intx and ethash manually, creating the problem that these must be manually updated whenever we bump up evmone versions.

This issue tracks support for such an upgrade for our build and test CIs and doing away with manual intx and ethash builds.

## Motivation

- Build and install both static and shared libraries for evmone in the ubuntu 1904 clang docker image that is used for the fuzzer build CI
  - Link the abiv2 proto fuzzer against the `libevmone-standone.a` static library
- In the non clang docker images, build and install only the shared evmone library since these docker images are used by isoltest only and not the fuzzer
- Remove manual installations of intx and ethash from all docker files
- Build and deploy updated docker image

If all goes well, all CIs must pass once these changes are done.

**Comment by axic** [comment]
> evmone v0.2.0 is required to run

0.2.0 is just a speed update. It uses evcm6 so no changes are required.

0.3.0, once released, will be needed for istanbul. It uses evcm7, which requires changes.

**Comment by bshastry** [comment]
> > evmone v0.2.0 is required to run
> 
> 0.2.0 is just a speed update. It uses evcm6 so no changes are required.
> 
> 0.3.0, once released, will be needed for istanbul. It uses evcm7, which requires changes.

Okay, in that case I see two options:

Option 1:

- Merge the fuzzer change portion of this PR (essentially linking against libevmone-standalone instead of the kitchen sink) + upgrade to 0.2.0 and cleanup to `develop`
- Once `v0.3.0` is released, we create another PR with the version of evmone + evmc libs bumped up.

Option 2:

- Wait for evmone `v0.3.0` to be release and update this PR to use `v0.3.0` instead of `v0.2.0` (saves us a PR at the cost of waiting for the release)

What do you think? CC @chriseth

**Comment by bshastry** [comment]
I realize I misunderstood the intention of the original PR: It was for speeding up the underlying evm and not to enable istanbul tests :(

**Comment by axic** [comment]
> It was for speeding up the underlying evm and not to enable istanbul tests :(

My motivation was
- to clear up the scripts by upgrading to 0.2.0,
- learn how to update it before the bigger change of 0.3.0,
- and at the same time make speed gains

**Comment by axic** [comment]
@bshastry I'd really opt for merging this for 0.2.0 as that is a clear update, no EVMC changes required. Supposedly during the process the docker files are cleaned up (using `libevmone-standalone` as depending on exact intx/ethash versions is messy).

Then updating to 0.3.0 should be smoother.

**Comment by bshastry** [comment]
@axic Sounds good to me. Do you want to merge the small fuzzer change (linking against libevmone-standalone) + docker file change (building both shared and static evmone for the clang image and shared only for ubuntu 18.04/19.04 images) into the PR you created or should I do it via the new PR I created? In hindsight, I should have simply edited your branch.

**Comment by axic** [comment]
I'd say just merge yours.
