### ISSUE TITLE
The test t_ubu_asan_constantinople is taking too long

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7703]
It usually takes 30-40 minutes, we should move it to run on the develop-branch only or as part of nightly (or find out if it was faster before and why it get slower).

**Comment by axic** [comment]
Still relevant?

**Comment by chriseth** [comment]
It now takes 3 minutes which makes me wonder if it still does the same thing.

**Comment by cameel** [comment]
Closing since the `asan` runs only in nightly now.
