### ISSUE TITLE
Windows - Add Sockets code-paths and enable Windows unit-tests in Appveyor

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#771]
We have automation of Test-over-IPC for Solidity for macOS and Ubuntu, but we cannot try to build that same automation for Appveyor on Windows yet, because the Solidity tests don't even build for WIndows yet, because we're using UNIX sockets unconditionally.

We're going to need to update that infrastructure within the Solidity tests (should be cut-and-pasting existing code) to get the runtime in a state where we can add the tests.

See:

https://github.com/ethereum/solidity/blob/develop/test/RPCSession.cpp
https://github.com/ethereum/solidity/blob/develop/test/RPCSession.h

And then we can automate it.

**Comment by bobsummerwill** [comment]
See also some IPC path changes happening in `geth`, @winsvega, @chriseth.

https://github.com/ethereum/go-ethereum/pull/2638

**Comment by winsvega** [comment]
I would add to this issue 
1) rework --ipcpath on windows 
2) rework --ipcpath on soltest
3) style and review ipcpath code for soltest

**Comment by winsvega** [comment]
the command to run soltest on windows is 

`.\\soltest.exe -- --ipcpath \\\\.\\pipe\\geth.ipc`

**Comment by axic** [comment]
This was implemented.
