### ISSUE TITLE
Variable error when calling chainid() 

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#7711]
I'm trying to build contracts that are chain aware (for ERC712) using the new `chainid()` introduced in istanbul (which is live on some testnets).

When trying to compile the following contract:
```
contract ChainID {
    function getChainID() external view returns (uint) {
        uint id;
        assembly {
            id := chainid()
        }
        return id;
    }
}
```

using the `--evm-version istanbul` flag I get the following error:

```
ChainID.sol:7:13: Error: Variable not found or variable not lvalue.
            id := chainid()
            ^^
```

(If I omit the `--evm-version` flag I get the expected `The "chainid" instruction is only available for Istanbul-compatible VMs` so don't tell me this issue comes from Istanbul not being enabled ...)

Any clue what I'm doing wrong? Istanbul should be live on mainnet in less then a month (december 4th) so it's high time we can start experimenting with it.

**Comment by mehdik16** [comment]
If you are using truffle, you will need to update the truffle-config.js, section compilers:

replace evmVersion: 'byzantium', by **evmVersion: 'istanbul',**
