### ISSUE TITLE
[soltest] passing value with the ``ether`` keyword as wei in semantics tests is confusing

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7714]
From @axic on gitter:
```
    contract C {
        function f() public payable returns (uint ret) {
            assembly {
                ret := selfbalance()
            }
        }
    }
    // ====
    // EVMVersion: >=istanbul
    // compileViaYul: also

  Expected result:
  // f(), 1 ether -> 1000000000000000000

  Obtained result:
  // f(), 1 ether -> 1
  Warning: The call to "f()" returned 
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]

  Attention: Updates on the test will apply the detected format displayed.
```

Since the syntax has the ``ether`` suffix, we should actually pass ether and not wei. We might actually want to support all denominations correctly.

**Comment by ekpyron** [comment]
This now caused problems for @leonardoalt again as well - we could consider prioritizing it - it should be simple to do - the main problem will be to have an eye on all existing tests using this.

**Comment by leonardoalt** [comment]
We could support only `ether` and `wei`. This way the current tests could simply replace `ether` by `wei`.

**Comment by chriseth** [comment]
Relevant function: `TestFileParser::parseFunctionCallValue`

**Comment by chriseth** [comment]
Assigning to @mijovic
