### ISSUE TITLE
Language feature: allow type alias

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#7728]
# Abstract

Add language construct for creating user-defined names for types.

## Motivation

Because I see somebody writing code like this:

```solidity
struct AgreementParams {
    uint120 ratio;
    uint8 ratioType;
    uint128 countdownLength;
}

...

(
    uint256 ratio,
    uint8 ratioType,
    uint256 agreementCountdown
) = abi.decode(agreementParams, (uint256, uint8, uint256));
```

## Specification

Add a new keyword `typedef` or `alias` to allow new scalar (not enum or struct) types.

Example:

```solidity
contract ABC {
    typedef uint128 TimePeriod;

    struct AgreementParams {
        uint120 ratio;
        uint8 ratioType;
        TimePeriod countdownLength;
    }
}

...

(
    uint256 ratio,
    uint8 ratioType,
    TimePeriod agreementCountdown
) = abi.decode(agreementParams, (uint256, uint8, TimePeriod));
```

This declaration will be visible at the contract top-level (storage declarations), functions (parameters and declarations) and inherited contracts.

This new feature will also be available for interfaces. In the generated ABI it will still use the canonical (e.g. uint) types.

## Backwards Compatibility

This is additive, no BC issues.

**Comment by chriseth** [comment]
Maybe duplicate of https://github.com/ethereum/solidity/issues/1100  or https://github.com/ethereum/solidity/issues/1013

**Comment by fulldecent** [comment]
Very related. That issue addresses typdeffing structs. This handles typedeffing primitive types.

**Comment by fulldecent** [comment]
moving these notes there
