### ISSUE TITLE
Add pragma about open or closed source / license

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7738]
In the effort to increase the link between a contract's address and its ABI / source code, one stepping stone is encouraging developers to publish their source code. Some of the tool writers we have spoken to are reluctant to auto-publish the source code at the point of deployment because the tools are also used for closed-source contracts, on private chains and with testnets.

Furthermore, an interactive deployment process where users have to answer a "publish or not publish" questions is also not an option because he deployment is usually performed by Ci/CD servers.

This leaves us with the option that contract developers have to state their decision before the code is published. One way of enforcing this decision is to add a pragma to the Solidity language that is required and specifies whether or not the source code can be published. We can go so far and even allow users to specify a license, which could be a good measure anyway.

Proposal:

A `pragma license "<license>";` line is required in each source file. The compiler parses the value as a generic string. The only interpretation performed on that string is to check whether it is the string `closed` or `none`, which means that the source code is not to be published.

Example:

```
pragma license "closed";
```

```
pragma license "CC BY-SA 2.0";
```

cc @gnidan

**Comment by leonardoalt** [comment]
From call: instead of making it mandatory, how about only issuing a warning if not there?

**Comment by christianparpart** [comment]
Usually every source code file (regardless of language) has a header file stating copyright, licence, and author.

When I think of this in a more generic way, I'd propose to support:
* zero or more licenses (with: no licence equals an empty string, equals "closed")
* zero or more authors

I'd propose author list (as part of the AST) here for future aggregation by (statistical) tools.

On the other hand, if we force users to add a license to each file, it forces them to think about their license they want to put this code under, which is something I'd personally prefer.

**Comment by chriseth** [comment]
One goal of this is that the license is machine-readable. Is there any standard for names of common software licenses?

**Comment by axic** [comment]
The standard is SPDX: https://spdx.org/licenses/. It also has an expression syntax.

This is the one used by NPM (https://docs.npmjs.com/files/package.json#license) and Cargo (https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) to name a few.

**Comment by franzihei** [comment]
Link to Twitter poll and discussion: https://twitter.com/ethchris/status/1250418075263885313?s=20

**Comment by chriseth** [comment]
Tentative "accept" in discussion call, leaning towards "warning", especially since an error would make it hard to write small examples.

**Comment by chriseth** [comment]
Open questions:
 - is there a specific "closed source" license?
 - what about custom licenses?

We can check what cargo does about that.

**Comment by axic** [comment]
> is there a specific "closed source" license?

"Proprietary"

**Comment by chriseth** [comment]
By @axic : could also use special comment: https://spdx.org/ids-how
