### ISSUE TITLE
Re-enable tests for push(...) via yul

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7749]
In https://github.com/ethereum/solidity/pull/7350 some semantic tests compiled via yul had to be disabled, since `push()` and `pop()` are not yet implemented for all types.

In order to re-enable them, all test cases containing the line `/// TODO enable again after push(..) via yul was implemented.` need to run their checks utilizing the `ALSO_VIA_YUL` macro.

**Comment by ekpyron** [comment]
Was this done entirely within https://github.com/ethereum/solidity/pull/7350 after all now?

**Comment by leonardoalt** [comment]
There's still one missing (re nested arrays)

**Comment by axic** [comment]
@mijovic do you remember by any chance if these were reenabled?

**Comment by chriseth** [comment]
They were not enabled and fail with `Invalid conversion to storage type`.

**Comment by mijovic** [comment]
@axic Some of them were activated with my changes, and some of them not. I can go troughout the tests and create list of items which are left to be done to close this one.

**Comment by chriseth** [comment]
We'll just enable them when missing features are implemented as with all other tests.
