### ISSUE TITLE
CI: Build docs as separate matrix step to make it finish early

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#777]

**Comment by bobsummerwill** [comment]
So I must confess that I don't have the Travis-foo yet to know exactly what you mean there.

I've not seen examples of Matrix being used to do DIFFERENT things - only as a means of parameterizing configurations.

Do you have some example which I could mimic?   Thanks!

**Comment by chriseth** [comment]
I guess you can define an environment variable to specify the thing you want to do and then condition on that during the actual run.

We should also add a similar thing for emscripten.
