### ISSUE TITLE
JSON output: better error reporting

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#778]
I think it would make sense changing the _"error"_ field to a map of:
- severity (warning or error)
- message
- location
  - source file name (or pointer to the source object / identifier)
  - source line

The improvement would be twofold:
- No need to manually trying to assess the severity
- Proper link to the source file

**Comment by chriseth** [comment]
Hm, how is that different from the way it is currently done?

**Comment by axic** [comment]
#1387 provides this layout

**Comment by axic** [comment]
Closed by #1387.
