### ISSUE TITLE
Consider removing bytesRef

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7795]
It is only used in the assembler and pulls in quite a big header (`vector_ref.h`).

**Comment by ekpyron** [comment]
We should switch to C++20 and use https://en.cppreference.com/w/cpp/container/span ;-).
Seriously, though, if we really need something like this and can't just live without it, we could check if we can just pull in one of the header-only implementations mentioned in https://stackoverflow.com/questions/45723819/what-is-a-span-and-when-should-i-use-one and replace it with ``std::span``, whenever using C++20 is actually feasible.

**Comment by axic** [comment]
Since it is only used in `Assembly.cpp` for serialising offsets + push values into the bytecode, I think it would be fine just having some helpers for that in `Assembly.cpp`.

**Comment by axic** [comment]
Unless @chfast has some other good ideas here.

**Comment by axic** [comment]
Fizzy has a simplified implementation for pre-C++20: https://github.com/wasmx/fizzy/pull/404

But I'm sure there is some polyfill project for it already.

**Comment by chfast** [comment]
In C++17 you can use `string_view` for that.
```
using bytes = std::basic_string<uint8_t>;
using bytes_view = std::basic_string_view<uint8_t>;
```

But as I remember correctly, `vector_ref` has additional methods.

**Comment by ekpyron** [comment]
Changing ``bytes`` from a vector to a string might also complicate things elsewhere... but maybe not! Interesting suggestion in any case :-)!

**Comment by axic** [comment]
Linking this discussion here: https://github.com/ethereum/solidity/issues/10738#issuecomment-760186577
