### ISSUE TITLE
[Yul] Extend LoopInvariantCodeMotion so that it can deal with sload and external calls

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7799]
The expensive operations we want to pull out of loops are unfortunately often not movable. This includes sload, extcodesize and others. They can be moved out of the loop, though, as long as they do not interfere with other code that is executed inside the loop.

**Comment by chriseth** [comment]
Can this be closed?

**Comment by hrkrshnn** [comment]
Yes. This is implemented.
