### ISSUE TITLE
"Not yet implemented" error for returning fixed-size arrays

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#78]
```
contract A { function f() constant returns (uint16[5]) { } }
contract B { function f() { A(1).f(); } }
```

**Comment by cyrusadkisson** [comment]
If you change the type to "string" or "bytes" you get an assignment error:

"Type error: Type void is not implicitly convertible to expected type string storage pointer."

contract A { function f() constant returns (string) { } }
contract B { function f() { string anothervar = A(1).f(); } }

contract A { function f() constant returns (bytes) { } }
contract B { function f() { bytes anothervar = A(1).f(); } }

In these two cases, it appears that B thinks a "void" type should be coming back from A, when it's actually either "string" or "bytes". 

EDIT: This probably means that dynamically-sized arrays/bytes can't be passed, different from this issue's main bug. But I'll leave this comment here anyway.

**Comment by LianaHus** [comment]
@fivedogit I think your problem is described here https://github.com/ethereum/solidity/issues/13
