### ISSUE TITLE
Increase the use of ``[[nodiscard]]`` (such as in ``Result``)

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7809]
Ignoring it will silently swallow errors and is never a good idea.

**Comment by tushar-sinha** [comment]
Can I work on this? Please let me know if any additional info can be provided.

**Comment by chriseth** [comment]
I'm not really sure about this...

**Comment by cameel** [comment]
> Can I work on this? Please let me know if any additional info can be provided.

Looks like this might not be the best task to start with after all. Maybe you'd like to try #12253 instead?
