### ISSUE TITLE
Cleanup the scripts folder.

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#7812]
The scripts root folder contains a lot of files, and a lot of logic inside.

The main goal should be to reevaluate if everything inside is still necessary (as of today) and whether or not the script itself could be cleaned up (for example the install_deps-family does a lot, and I doubt it's all still needed like it was written).

Also potentially re-arranging files into groups by subject for a more intuitive way could help understanding what one may need could help.

**Comment by axic** [comment]
Also consider the other set of scripts hidden under `test/`,`test/externalTests` and `.circleci/`.

**Comment by cameel** [comment]
We'll actually be discussing this (along with some other removal/cleanup tasks) on the next design call so it's still very relevant.
