### ISSUE TITLE
Reduce(/eliminate) the dependency on Boost

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#7814]
* Some APIs from boost already went into the standard library.
* for Boost integer we can use the intx library (already seperate ticket)
* with regards to Boost.Ranges we should consider using [ranges-v3](https://github.com/ericniebler/range-v3) that are compatible with C++11/14/17 and is going to be part of C++20, too. (can become a "splitout"-ticket)

**Comment by ekpyron** [comment]
For reference: I suggested a similar approach in https://github.com/ethereum/solidity/issues/7795#issuecomment-558846981, but we might not need it there

**Comment by axic** [comment]
Merged this into #7259.
