### ISSUE TITLE
[Yul] Specify and enforce evaluation order on sub-expressions

### ISSUE THREAD

**Issue by rschumi0** [ethereum/solidity#7820]
## Description

When I did some computations with increments and decrements, I got some unexpected results that might be caused by an issue with the operation order.

## Steps to Reproduce

```
int a = 1; 
int res  = ++a + a; \\ results in 3 

int b = 1;
int res1 = b + ++b; \\ results in 4
```

In these computations I expected the results to be exactly vice versa. 
So I was wondering if this is intended behavior or a bug that should be fixed?

## Environment

- Compiler version: 0.5.13
- Target EVM version (as per compiler settings): default
- Framework/IDE: Truffle and Remix
- Operating system: Win 10 and Ubuntu

**Comment by chriseth** [comment]
"The evaluation order of expressions is not specified (more formally, the order in which the children of one node in the expression tree are evaluated is not specified, but they are of course evaluated before the node itself). It is only guaranteed that statements are executed in order and short-circuiting for boolean expressions is done" ( https://solidity.readthedocs.io/en/v0.5.13/control-structures.html#order-of-evaluation-of-expressions )

We might want to change that in the new code generator, though, and enforce a certain order.

**Comment by rschumi0** [comment]
Thank you for your detailed answer. I really think it would make sense to enforce a certain order for this. 
I just noticed that there are also strange cases with the postfix increment and decrement:
```
int a = 1;
int res = a + a++; \\ results in 3
```

**Comment by chriseth** [comment]
Closing in favour of #7825

**Comment by rschumi0** [comment]
Just to be complete, here are two more cases where I expect the computation order to be an issue:
```
int a = 2;
a *= 1 + a++; //results in 9

int b = 1;
b += ++b; //results in 4
```
