### ISSUE TITLE
[Yul] Extend LoopInvariantCodeMotion to more complex statements

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7821]
Relates to https://github.com/ethereum/solidity/issues/7799

Currently, LoopInvariantCodeMotion only deals with assignments to SSA variables from expressions only containing SSA variables and movable function calls.

We should extend it to any statement that
 - only contains movable code
 - only assigns to variables that are defined inside that statement (if it is a complex block)
 - if variables defined outside that statement are referenced, the have to be ssa variables defined outside the for loop.

**Comment by chriseth** [comment]
In light of https://github.com/ethereum/solidity/issues/7867 this can also be extended to turn
```
for {} c { P... } { B... }
```
into
```
if c {
  movedCode
  for {} c { P'... } { B'... }
}
```
if part of the moved code is not always guaranteed to return (like it contains a potentially infinite loop).

**Comment by sergiuiacob1** [comment]
Hi, did anybody work on this improvement? Is this still valid?
If so, I'd like to work on this as a contribution to Solidity's open source code (i.e. https://github.com/ethereum/solidity/issues/13058)
Could somebody give me more context on this? Or any additional starting point other than the issue description? If not, I might be able to work with only what's in the comments above.
CC @cameel @chriseth
