### ISSUE TITLE
Unit tests - Do multiple runs (so we have the data), but succeed if ANY pass

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#783]
The Solidity unit-tests in TravisCI are running 5 times, to try to flush out elements which are unreliable.

Having more data-points on unreliability is great.    Having our automation failing all the time is not so great.

We should move that iteration into `tests.sh`, and perhaps change the logic to more of a "retries" model, so, perhaps, we try up to 5 times to get a successful unit-test run?

Or, we could just run 5 times whatever happens (so we have the logs and data), but return a success code is ANY of those 5 succeed.

**Comment by chriseth** [comment]
Should be fixed in latest.
