### ISSUE TITLE
Verify that replacing soljson.js in the external zeppelin tests still works correctly.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7846]
https://github.com/ethereum/solidity/pull/7845 let the tests successfully pass again after https://github.com/OpenZeppelin/openzeppelin-contracts/commit/5f92adc2e76fe92d7ab952710ff3fb6d76066a35, but we should have another look at the tests in detail and verify that they correctly replace soljson.js with the version to be tested.

**Comment by erak** [comment]
@ekpyron I think it works as expected. We're verifying after each compilation that the compiler version in the metadata matches the one of the soljson binary. Meaning that the Circle job would fail otherwise.

**Comment by ekpyron** [comment]
Nice and makes sense!

**Comment by erak** [comment]
The removal of the workaround here: https://github.com/ethereum/solidity/pull/7845 is also included for 0.6.0 here https://github.com/ethereum/solidity/pull/7784.
