### ISSUE TITLE
[yul] loop-invariant-code-motion should check if loop may execute at least once before moving loop-invariant in for-body and for-post blocks

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7847]
## Description

Summary: The yul optimiser converts a terminating program into a non terminating program.

Terminating program (because msize() evaluates to zero)

```
{
        for {} msize() {
          function foo_s_0() -> x_1 { for {} caller() {} {} }
          // x_3 is a movable loop invariant because `foo_s_0()` is movable
          let x_3 := foo_s_0()
          mstore(192, x_3)
        }
        {}
}
```

Non terminating program (post optimization)

```
{
    for { } iszero(iszero(caller())) { }
    { }
    for { } 1 { mstore(192, 0) }
    { if iszero(msize()) { break } }
}
```

The optimized program creates an infinite for loop due to a non-zero caller() value. On the other hand, the unoptimized program bails out early because `msize()` is zero at the point of evaluation.

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): istanbul

## Steps to Reproduce

```
$ solc --strict-assembly --optimize <test.yul>
$ yulrun --input-file <test_opt.yul>
```

**Comment by bshastry** [comment]
I have a feeling this is because of #7461 

- `x_3` is moved out of the loop because it is a movable loop invariant
- Then probably expression simplifier plus function in-lining leads to the optimized code

I think the main issue here is that we don't check if loop executes at least once before moving the "movable loop invariant." If the movable loop invariant is in for-init block, it is fine to move it outside the loop because the init part is unconditionally executed. However, if it is either in the for-body or for-post blocks, then we shouldn't move if the loop may never be executed, because moving it without this guarantee is tantamount to adding code that is not intended. In other words, we should perform loop invariant code motion if we are sure that loop executes at least once.

Another approach that we may take is to define infinite loop (a denial of service attack essentially) as a side-effect. If an expression can result in an infinite loop, it is not movable. With this approach, I think we will have to err on the side of caution (meaning that when we cannot decide on for loop termination at compile time, we may have to assume the worse).

**Comment by ekpyron** [comment]
Wow... I hadn't thought about infinite loops.
I totally agree with you @bshastry - I see no other way around this than restricting loop-invariant code motion to only cases in which the loop is definitely executed at least once.

**Comment by ekpyron** [comment]
Otherwise we'd need something like a "might never return" side-effect and require that additionally to ``movable``...
Or well maybe a combination - if we *don't* know that the loop will be executed at all, we additionally require to not have the ``might never return`` side-effect...

**Comment by chriseth** [comment]
Yeah, I considered additional gas costs for the case that the loop is never executed, but I assumed that it's fine because when a loop is used, people usually mean to execute it. I did not consider the fact that movable expressions might not return at all. We also have to take recursive function calls into this group!

I would propose to define such a side-effect (we might also need it elsewhere) and disregard determining whether the loop is executed at all. If the optimizer is able to determine that, then the loop will be removed anyway.

**Comment by chriseth** [comment]
Actually we might want to consider recursive functions and functions containing loops not even movable - because calls to them cannot be removed without changing the semantics.

**Comment by bshastry** [comment]
Just to be sure why are calls to functions containing bounded for loops not movable? Or do you mean if we cannot be sure that a loop is bounded or potentially infinite, we assume the worst?

**Comment by ekpyron** [comment]
As a side remark: @chriseth and me realized that the following will probably have the same problem:
```
function() -> x { for {} caller() {} {} }
let a := f()
let b := sub(a,a)
```
(``sub(a,a)`` will be simplified to zero and ``a`` will be removed as unused)

I think determining whether a loop terminates with finite gas or not in general will be a (probably too) hard problem for the optimizer.

I think @chriseth wants to solve this for now by marking all loops and recursive functions as non-movable for 0.5.14 and then think about how we can improve upon that later.

**Comment by bshastry** [comment]
Ah, nice example.

> I think determining whether a loop terminates with finite gas or not in general will be a (probably too) hard problem for the optimizer.

Yeah, I think it will be impossible unless we interpret code at compile time. For example, the value of `msize()` in the original example is unknown unless we start interpreting code from the very beginning. On top of that, the additional constraint of "bounded with regard to finite gas" would mean the interpreter (which at the moment does not have a notion of gas) will need to do emulate gas costs as well.

> I think @chriseth wants to solve this for now by marking all loops and recursive functions as non-movable for 0.5.14 and then think about how we can improve upon that later.

Sounds good to me. Better to forgo a potential optimization opportunity than give room for potentially incorrect code.

**Comment by ekpyron** [comment]
Well, what we could do is to prove Turing wrong, solve the Halting Problem and use our solution to determine which loops are safe ;-).
What I mean is: all we can hope for is that the optimizer might be able to prove termination with finite gas for some easy cases - but even that would be hard - you'd usually need to "guess" some bound on some variable for which you can prove some monotonicity properties, but I doubt that's feasible at least in the short term...

**Comment by ekpyron** [comment]
We could, however, have some heuristics on the complexity of the loop condition and based upon that rewrite
```
for {} <some_condition> {} { for {} 1 {} {} ...}
```
to
```
if <some_condition> { for {} 1 {} {} }
for {} <some_condition> {} { ... }
```
In some cases the optimizer will be able to remove the ``if`` again in a later step (that's basically determining if the loop will definitely run at least once).
But yeah, the main question there is when we should and when we shouldn't do that, since for complex loop conditions this can actually be more expensive...

**Comment by bshastry** [comment]
> Well, what we could do is to prove Turing wrong, solve the Halting Problem and use our solution to determine which loops are safe ;-).

Haha.... we can even earn up to 1000 USD doing it https://news.ycombinator.com/item?id=376238
