### ISSUE TITLE
Memory handling of the libsolc read callback

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7855]
https://github.com/ethereum/solidity/blob/develop/libsolc/libsolc.h#L37-L40

Currently the read callback returns two optional pointers: data and error. If it does return these pointers, they are memory allocated by the callee (e.g. the code which has the callback implemented) but are freed by the caller (e.g. solidity, which calls the callback).

This works well in the Javascript use case, because in asm.js the Solidity `malloc` function is exposed and the callee allocates memory using the same allocator which will free it.

However in other use cases, such as Rust or Python, the callee may have its own memory allocation function with a different list of allocations and such can't be freed by Solidity `free`.

The solution here would be to let the callee free the pointers. The problem is that the callback can be called multiple times without the main `compile` function returning and hence could amass a large allocation footprint. One option is that each callback invocation in the callee could look for existing allocations and clean them up.

In terms of API change I think we have at least three options:
1) Just ensure that the callee frees memory. This can be implemented in solc-js without issues.
2) Add a flag to `compile` which tells who frees the memory. This option would rather mean adding a `flags` field to `compile` and making this the first flag.
3) Leaving it as is and arguing that other integrations should try to work it around. In Rust I haven't found a clean way yet to allocate memory using libsolc's malloc and obviously memory allocated by Rust's allocator can't be freed by libsolc's malloc.

**Comment by ekpyron** [comment]
Another option would be to split the callback into two - one returning a size, one receiving a buffer allocated by the compiler to which it should write.

**Comment by ekpyron** [comment]
I'm not a fan of adding a flag in any case.

**Comment by axic** [comment]
Few more options suggested:
1) Another callback to free a memory pointer.
2) Another callback to free all memory allocated.
3) Expose `malloc` via another public function.

**Comment by bshastry** [comment]
Summary: We have a lot of options that need further discussion.

**Comment by ekpyron** [comment]
Point in favour of adding a free-callback: That's the only way that the callback can provide file contents by memory mapping files, which is actually the fastest and nicest way for it to load stuff.

**Comment by ekpyron** [comment]
But yeah, the more I'm thinking about it, the more I lean towards just exporting ``malloc`` as ``solidity_alloc`` and be done with it that way.

**Comment by ekpyron** [comment]
Actually I even think that we should change the way ``solidity_free`` works while we're at it.
We should implement it in a way that we at least have a chance to make the interface reentrant in the future - so I think ``solidity_free`` should be the counterpart of ``solidity_alloc`` and take an argument. So ``solidity_compile`` returns a buffer that has to be freed by ``solidity_free``.

**Comment by axic** [comment]
Well we should rename `solidity_free` to `solidity_cleanup`/`solidity_reset` or something like that.

**Comment by ekpyron** [comment]
I think it should be possible to explicitly free whatever ``solidity_compile`` returns and a second call to ``solidity_compile`` shouldn't invalidate the memory the first call returned...

**Comment by ekpyron** [comment]
By the way: the fact that currently the memory returned from ``solidity_compile`` will be invalid after a second call to ``solidity_compile`` isn't even documented... at least not in libsolc.h...

**Comment by axic** [comment]
> I think it should be possible to explicitly free whatever solidity_compile returns and a second call to solidity_compile shouldn't invalidate the memory the first call returned...

That's not a bad idea. However it would mean an extra memory copy for every case, because currently it uses the extensible `std::string` and just exposes its pointer.

**Comment by ekpyron** [comment]
We could do something similar, avoiding copying at the cost of linear complexity of "free" and a few small allocations...
```
static std::list<std::string> allocations;
char const *solidity_compile(...)  {
  return allocations.emplace_back(compile(...)).c_str();
}
void solidity_free(char const* _ptr) {
  for (auto it = allocations.begin(); it != allocations.end(); ++it) {
    if (it->c_str() == _ptr) {
        allocations.erase(it);
        break;
    }
  }
}

**Comment by axic** [comment]
@ekpyron you can't use this `solidity_free` with `solidity_alloc` though.

**Comment by ekpyron** [comment]
Unless we implement
```
char const* solidity_alloc(size_t len) {
  return allocations.emplace_back(std::string(len, 0)).c_str();
}
```

**Comment by ekpyron** [comment]
The alternative is to use ``malloc``/``free``, resp. ``new[] char`` and ``delete[]``, but then we either need to change how ``StandardCompiler::compile`` returns things (bad idea IMO) or we have one copy in the end (which is probably not too bad).

**Comment by axic** [comment]
On the meeting we have agreed on a design based on @ekpyron's suggestion:

- `char *solidity_alloc(size_t len)` - allocates a string and places it into the internal list
- `char *solidity_free(char *ptr)` - frees the string, if the ptr is part of the internal list
- `void solidity_reset()` - frees all the allocations
- `char *solidity_compile(...)` - returns data allocated the same way as `solidity_alloc` works (this also means it must be deallocated explicitly by the caller)
- callbacks must return pointers to the compiler allocated via `solidity_alloc` and the compiler will deallocate these

We can use different names and argue about the types used.

**Comment by ekpyron** [comment]
Just as an additional note: the pointers allocated by the callback are freed internally by the compiler, so the callback provider doesn't have to free them.

**Comment by axic** [comment]
Additional discovery (mostly by @ekpyron) that we could avoid copying strings from the callback to the `CompilerStack` if we internally consider these allocations as `std::string`.

For example here https://github.com/ethereum/solidity/blob/develop/libsolc/libsolc.cpp#L61-L62, instead of creating a copy, we should move the string and remove it from the list of "external allocations".

**Comment by christianparpart** [comment]
NB: My naming proposals are the following:
* `solidity_allocate()` for allocating memory
* `solidity_deallocate()` for deallocating previously allocated memory (not `solidity_free` to not be confused by the old `solidity_free` that we are about to rename)
* `solidity_reset() as rename of old `solidity_free`.
