### ISSUE TITLE
Remove "kill" from examples

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#7858]
We have deprecated "suicide" from the Yellow Paper, so we can remove "kill" from the examples and documentation.

**Comment by chriseth** [comment]
Please feel free to change the examples!

**Comment by chriseth** [comment]
"shutdown"?

**Comment by fulldecent** [comment]
PR coming

**Comment by fulldecent** [comment]
https://github.com/ethereum/solidity/pull/7869
