### ISSUE TITLE
0.6.0 changelog unclear definition of fallback and receive

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#7863]
The changelog currently says:

> The unnamed function commonly referred to as "fallback function" was split up into a new fallback function that is defined using the fallback keyword and a receive ether function defined using the receive keyword. If present, the receive ether function is called whenever the call data is empty. The new fallback function is called when no other function matches. It can be payable in which case it may accept value or non-payable in which case transactions not matching any other function which send value will revert. If you only implement the receive and not the fallback function, calling a non-existing function on your contract in error is not possible anymore. Unless you are following an upgrade or proxy pattern, you should not need to implement the fallback function.

The words "no other function" make this unclear to me. I do not know if "other function" includes "receive" or not.

**Comment by chriseth** [comment]
It does include it. If any function matches, that function is called, otherwise the fallback function is called. The fallback function being called does not mean that its code is executed, sometimes it also reverts (if it is not payable), though.

**Comment by fulldecent** [comment]
Does that mean the fallback function will be executed on an empty call data if the receive function does not exist?

**Comment by chriseth** [comment]
Yes.

**Comment by fulldecent** [comment]
Thank you. Update here --> https://github.com/ethereum/solidity/pull/7888
