### ISSUE TITLE
[Yul] Improve side-effect property of loops and recursive functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7867]
To fix a bug, we set all functions containing loops and recursive function calls to non-movable. The property is a bit more restricted, though:

Calls to such functions cannot be removed or introduced into a control-flow path, but they can be moved around along a non-splitting and non-joining control-flow path and the function itself is "pure" (meaning its result only depends on the arguments), assuming the statements inside the function are all movable.

How shall we cal this property? "alwaysReturns" (for the converse property)?

The `return`, `revert`, ... builtin functions would also fall into this category.

In another issue, we considered the property of "never returning", i.e. not having a continuing control-flow for statements, so these could be combined (-> TerminationFinder).

**Comment by hrkrshnn** [comment]
Can you link the bug?

**Comment by chriseth** [comment]
Not sure if the bug had an issue number. Do you have a question about that?

**Comment by hrkrshnn** [comment]
Maybe a related question, why is the instruction `Instruction::KECCAK256` considered non-movable?

**Comment by chriseth** [comment]
because it reads from memory
