### ISSUE TITLE
Deprecate "Solidity Interface" output

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#787]
- [x] remove interface from binary commandline version
- [x] remove interface from js commandline version: https://github.com/ethereum/solc-js/issues/38

The _Solidity Interface_ as returned in the JSON (or via the `--interface` command line option) is an actual abstract Solidity contract code, like this:

```
contract Token{function name()constant returns(string );function approve(address _spender,uint256 _amount)returns(bool success);function totalSupply()constant returns(uint256 );function transferFrom(address _from,address _to,uint256 _amount)returns(bool success);function decimals()constant returns(uint8 );function standard()constant returns(string );function balanceOf(address _owner)constant returns(uint256 balance);function symbol()constant returns(string );function transfer(address _to,uint256 _amount)returns(bool success);function approveAndCall(address _spender,uint256 _value,bytes _extraData)returns(bool success);function allowance(address _owner,address _spender)constant returns(uint256 remaining);}
```

Would it make sense to have it properly indented in a readable form?

**Comment by chriseth** [comment]
I think we first have to find a proper use-case for this feature.

**Comment by axic** [comment]
I'm not exactly sure.  It seems a better approach that those writing abstract contracts are doing that by hand and only include the needed methods.

I would think the _Solidity Interface_ option would provide a probably unneeded shortcut for that.

Maybe mark it for future removal?

**Comment by chriseth** [comment]
Agree

**Comment by chriseth** [comment]
Please see the new task.

**Comment by chriseth** [comment]
The task in solc-js is not done yet.
