### ISSUE TITLE
Require jsoncpp 0.9.4 as a minimum

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#789]
(Follow up from #760)

0.9.4 is the version which has complete UTF8 support and was released in 2015. Earlier versions could output invalid JSON during compilation.

The latest version is 1.7.4, released a month ago.

**Comment by chriseth** [comment]
What are the versions available on the main platforms we support?

**Comment by axic** [comment]
- homebrew 1.7.4
- ubuntu
  - precise 0.6.0
  - trusty 0.6.0
  - wily 0.10.5
  - xenial 1.7.2

**Comment by bobsummerwill** [comment]
I think the way to approach this, @chriseth, would be to flip to building-from-source in `install_deps.sh` for Ubuntu - as I'm doing for json-rpc-cpp in my cpp-ethereum branch.    Then we're not dependent on PPA at all, and work identically across all versions.    Easy win for other distros too.

I also flipped to build-from-source for CryptoPP in the same place, again because of issues in the old version shipped with Trusty.

I would actually propose that we drop the PPA entirely as a source of external dependencies, and use it (them, when we split cpp-ethereum and solidity PPA) ONLY for publishing our binaries, not for hosting binaries for external packages which aren't new enough by default.

See https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/scripts/install_deps.sh#L389.

CC @chfast.

**Comment by axic** [comment]
jsoncpp recommends to not be used as a library:

> The recommended approach to integrating JsonCpp in your project is to include the amalgamated source (a single .cpp file and two .h files) in your project, and compile and build as you would any other source file. This ensures consistency of compilation flags and ABI compatibility, issues which arise when building shared or static libraries. See the next section for instructions.

Maybe we should include a copy and/or a submodule?

Also:

> 1.y.z is built with C++11.
> 0.y.z can be used with older compilers.

**Comment by bobsummerwill** [comment]
Yes - adding sub-modules for external dependencies is something which I think it a very sensible option for us to consider.

It gives us complete control of versioning and build-options and lets us all avoid all the packaging-system variance madness there is within Linux and the lack-of-packaging system for Windows.

The cost is that for external packages which are large (like Boost, LLVM) this can add a huge amount of time to the build process.   In TravisCI, where we already up against the 48min limit, this might not even be possible.

But yeah - something to try for sure.

**Comment by axic** [comment]
@bobsummerwill would you be able to do this (or point me to how to do it)? I would suggest using version 1.7.4.

**Comment by bobsummerwill** [comment]
Hey @axic,

Sure - but we probably want to hold-fire until we're working in ethereum/cpp-ethereum again.

If you would like to have a dry-run, you could fork https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos, and look at how @chfast uses LLVM within https://github.com/ethereum/evmjit.    It will be like that.

You could either just download the external package (as Pawel does), or in jsoncpp's case, you would probably just add it as a sub-module.

I started doing something very similar for the cross-builds here:

https://github.com/doublethinkco/jsoncpp

Pawel could probably guide you best as the pattern he used there.

**Comment by axic** [comment]
@bobsummerwill Following the recommended way (["amalgamated sources"](https://github.com/open-source-parsers/jsoncpp#generating-amalgamated-source-and-header)) it works pretty flawlessly.

Added it here: https://github.com/ethereum/solidity/tree/internal-jsoncpp

**Comment by axic** [comment]
Adding it as a submodule and compiling via cmake also works flawlessly.

Added it here: https://github.com/ethereum/solidity/tree/submodule-jsoncpp

**Comment by chriseth** [comment]
Sounds great! also jsoncpp is really small, so I'm voting for including it. We should provide a script to do updates.

**Comment by chfast** [comment]
I would like to suggest to use CMake's ExternalProject for that (as a first try). Example for LLVM: https://github.com/ethereum/evmjit/blob/develop/cmake/llvm.cmake#L61-L80. I'm quite happy with that so far.

We will end up with a single cmake script that works for every platform. Upgrade is also very simple, you must change the git tag/URL/SVN commit in the script. No jsoncpp sources have to be pushed to our repo.

The only issue is how to share that between cpp-ethereum and solidity.

I can do it. I started to like CMake programming :). Just wish they had better syntax.

**Comment by chriseth** [comment]
oh my ... wow! Yeah, let's use that!

**Comment by axic** [comment]
@chfast is this implemented for Solidity too? If not, please reopen.
