### ISSUE TITLE
Optimize storage writes for small types by determining that the slot is otherwise unused.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7891]
When types smaller than 32 bytes are written to a storage slot, they are always "ored" into the data already at that slot, which means that we first need to read the data. This reading gets more costly with Istanbul and thus we might consider skipping it if we can determine that the slot is not used by anything else.

The risk is that making this decision could introduce a bug and users might also want to use the rest of the storage slot without solidity being aware.

One example is of course inline assembly, but the other example is contract upgrades that add new storage variables.

**Comment by Marenz** [comment]
@ekpyron will write a proposal for a syntax/annotation based solution

**Comment by ekpyron** [comment]
Related: https://github.com/ethereum/solidity/issues/4519 and https://github.com/ethereum/solidity/issues/597 - they both would solve this - and I'll probably rather write something up for the latter of those two.

**Comment by axic** [comment]
Perhaps it would be better to consider an annotation for "packed" vs. "unpacked" variables and unpacked variables are cheaper to operate on. It would be down to the user then to decide which variables are accessed frequently and make them unpacked, while other variables would benefit from low usage and compactness.

**Comment by ekpyron** [comment]
@axic That was kind of my suggestion in our call, only that I would not just make it ``packed`` and ``unpacked``, but full-blown general storage-layout annotations as in https://github.com/ethereum/solidity/issues/597 :-). Or at least I wanted to explore that option.

**Comment by chriseth** [comment]
It seems this is not too annoying for users after all.
