### ISSUE TITLE
AST Json Export: Don't have null values

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#7897]
@axic [suggested](https://github.com/ethereum/solidity/pull/7153#discussion_r353711057) that json members shouldn't have the `null` value. The alternative would be to skip those members entirely.

**Comment by erak** [comment]
Decision from the call: don't have `null` values.

**Comment by chriseth** [comment]
Do we want this for 0.7.0?

**Comment by Marenz** [comment]
If we have the time, I'd say sure!
