### ISSUE TITLE
EIP170 constraint

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#7913]
For some specified optimization runs the contract binary may become larger than the limit enforced by EIP170. This can result in contracts that cannot be deployed. It may be helpful if there was a flag or option to constrain contract size to 24k (default) or a parameterized limit, if possible. If the constraint cannot be met, it would be ideal to produce the smallest possible contract and emit a warning.

Probably solc should emit a warning if the output size is larger than currently allowed on mainnet.

**Comment by axic** [comment]
I think this may be a duplicate of #2100.

**Comment by wjmelements** [comment]
Thanks, merging
