### ISSUE TITLE
Add solidity@0.5 to homebrew-ethereum

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7915]
There already is `solidity@0.4` (for 0.4.26) and with the release of 0.6.0, `solidity` will move to to that, so the only way to install 0.5.x series would be to include `solidity@0.5` as a package.

**Comment by chriseth** [comment]
Let's do it!

**Comment by axic** [comment]
Suggested course of action: after 0.5.14 is released, just duplicate the file as `solidity@0.5`.

Then we just proceed to update the base file when 0.6.0 is released.

**Comment by axic** [comment]
Sorry @ChrisChinchilla I really wanted to get this done: https://github.com/ethereum/homebrew-ethereum/pull/250
