### ISSUE TITLE
Add solidity highlighting support to rouge

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7920]
[rouge](https://github.com/rouge-ruby/rouge) is a syntax highlighting library written in Ruby. It is used by Jekyll and [used by default by Github Pages](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#syntax-highlighting).

Having this implemented would mean Solidity is properly highlighted on eips.ethereum.org

**Comment by axic** [comment]
Apparently a PR was submitted in 2017 by @veox, but it is still not merged: https://github.com/rouge-ruby/rouge/pull/760

**Comment by chriseth** [comment]
We should at least find a solution to have working syntax hilighting on solidity-blog.

**Comment by axic** [comment]
Merged upstream.
