### ISSUE TITLE
Rename to Ewasm/ewasm

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7932]
Yul and the source through contains various spellings of Ewasm. The preferred spelling is "Ewasm" and we should use "ewasm" for CLI options.

One example, the machine flag for Yul uses "eWasm".

**Comment by axic** [comment]
The only thing needed for 0.6.0 is any public switches in the CLI to use `ewasm`. Everything else is internal refactoring.

**Comment by christianparpart** [comment]
@axic but in JSON it should stay as `ewasm` I suppose, shouldn't it?

**Comment by axic** [comment]
Oh I've started doing this already, sorry haven't assigned myself.

**Comment by christianparpart** [comment]
never mind. looking for something else then (`git reset --hard HEAD`-ing)

**Comment by axic** [comment]
What I did/plan to do (but not before the 0.6.0 release to avoid conflicts):
- rename `EWasmToText` to `TextTransform` (as it has nothing ewasm specific and it is in line with BinaryTransform)
- rename `EWasmAST` to `WasmAST` (likewise, not ewasm specific)
- rename `eWasm`/`EWasm` to `Ewasm` in classes/file names
- ensure all CLI and StandardJSON fields are called `ewasm`

**Comment by axic** [comment]
There doesn't seem to be any CLI option which uses a non-standard capitalisation of ewasm (it was just a typo in the changelog, fixed by #7954). Standard JSON was always using lowercase.

The renaming is not important for 0.6.0, so moving this.
