### ISSUE TITLE
Reenable style checks for docs for 0.6.0

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7944]
Revert #7435.

**Comment by christianparpart** [comment]
We're using an external tool [solhint](https://github.com/protofire/solhint), so new features break our CI.
For reference I'm linking the tracking issue from the other side: https://github.com/protofire/solhint/issues/170.

**Comment by axic** [comment]
I guess this is done :)

**Comment by cameel** [comment]
@axic Looks like it's not done yet.

PR #7962 was just closed, not merged and the check seems to be still disabled on `develop`: https://github.com/ethereum/solidity/blob/804bd8f6dd117b7dec62e179cde663d29a31fc85/.circleci/config.yml#L981

**Comment by cameel** [comment]
I think this is actually a duplicate of #7436.
