### ISSUE TITLE
[Documentation] Document how to build fuzzers via docker

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7948]
## Abstract

Since the fuzzer builds rely on external dependencies (libfuzzer, libprotobuf, libprotobuf-mutator), it is non-trivial to reproduce ossfuzz reported issues locally.

This issue tracks support for documenting fuzzer builds using docker. The reason docker is chosen is because it is platform independent (e.g., @axic would like to run fuzzer tests on Macos).

**Comment by axic** [comment]
There's some documentation (https://github.com/ethereum/solidity/blob/develop/test/tools/ossfuzz/README.md) but it is not comprehensive.

**Comment by Marenz** [comment]
hmm I personally don't like to use docker if I can avoid it. I would prefer generic instructions. But maybe those can be extract from the docker-specific documentatio.

**Comment by bshastry** [comment]
@Marenz I can understand. Docker was suggested to solve dependency issues. For example, a portion of the fuzzer builds depend on a specific version of libprotobuf and libprotobuf-mutator libraries that may not be shipped with distros.

Building deps from source is an option I suppose but I feel people might prefer docker over this if it comes to it. Feel free to suggest alternatives.
