### ISSUE TITLE
Remove LLL from Solidity

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7949]
Reason explained [here](https://github.com/ethereum/solidity/issues/1230#issuecomment-559116361)

TODO:
- [ ] Remove liblll and lllc
- [ ] Remove from documentation
- [ ] Remove tests
- [ ] Remove cmake settings
- [ ] Remove form CI
- [ ] Add link to "assembler" in documentation

Closes #1188
Closes #1230
Closes #1288
Closes #1453
Closes #1478
Closes #2865
Closes #2932
Closes #3141
Closes #4680
Closes #5714

**Comment by gumb0** [comment]
cc @winsvega 

As I understand LLL is still widely used in tests, but it would be great to get rid of it there, too.

I actually suggested to @winsvega to support Yul in tests, or maybe this new "assembler" thing would be better, what do you think?

**Comment by axic** [comment]
Many test cases can't be supported via Yul, because it doesn't allow controlling low-level jumps, jumpdest, etc. That's why the assembler is important.

**Comment by zigguratt** [comment]
Is LLL going to be erased from the repo, or will it find another home somewhere?

**Comment by axic** [comment]
We do not have the resources to maintain LLL here or in a different repository, this is also a main contributing factor for removing it.

Anyone is free to fork this repository prior to the commit removing it. However I would strongly suggest not to do that, but to write a new compiler for LLL outputting the aforementioned assembly language. (It will be [EIP2121](https://github.com/ethereum/EIPs/pull/2121).)

I'd be happy give advice on such a project, but can't contribute more.

**Comment by zigguratt** [comment]
Thanks Alex. I've been exploring other paths similar to what you suggested. I'm concentrating on another project at the moment, but I'm starting to focus my attention back on a Lisp-like language.

**Comment by winsvega** [comment]
I would like to include liblll to retesteth. 
I only need the translator feature that replace expressions into bytecode. 

Yul could also be supported. The thing is that we have around 20k tests with lll and I don't think it is a good idea to rewrite them

**Comment by axic** [comment]
> The thing is that we have around 20k tests with lll and I don't think it is a good idea to rewrite them

My opinion is that it is absolutely a good idea to rewrite them. Many of them were written with a broken version of LLL (before "auto variable allocation" was fixed) and nobody knows if any of them are actually correctly testing what they supposed to test.

**Comment by winsvega** [comment]
> My opinion is that it is absolutely a good idea to rewrite them. 

You have someone willing to do that?

**Comment by gumb0** [comment]
> You have someone willing to do that?

I guess for that someone would need to create a transpiler from LLL to assembly, is that possible?

**Comment by winsvega** [comment]
That is equal to maintenance of lllc. 
Alexs point is to review the test cases manually. And verify post conditions

**Comment by axic** [comment]
I think for the past 3 years it was mentioned a number of times that LLL is unmaintained, yet nobody picked that up to use other languages in the test suite. Nothing will really change with removing LLL from Solidity. LLL will remain just as unmaintained, as it was the past 3 years.

I'm afraid there are many test cases which don't actually test what they supposed to, because they were created with a broken LLL compiler and were never regenerated.

To fix the situation, I think one of these would need to happen:
a) Write a new, more simple, but properly working LLL compiler. Regenerate each test. Manually confirm each test case is well written.
b) Rewrite test cases in a new language.

Both of these are large tasks, but there just isn't any way around it.

**Comment by winsvega** [comment]
Although I didn't check every test presciesly, I still check that post condiftion is verifying the reasonable logic in the tests.  tests has been regenerated before the HF and the post condition checks that the behaviour doesn't change.  the LLL in tests is not that complex. most cases it looks like  
```
{ [[1]] (CALL 0 0 ...)  }
```

recent sophisticated lll tests has a good post condition check. 
I think the amount of tests that don't test what they are supposed to do is quite small. 

I don't think there is really a need to rewrite LLL in tests.  
verify post condition and review the tests - yes. 
more over it is possible to support LLL, YUL and what ever.

**Comment by bobsummerwill** [comment]
@zigguratt As-and-when you do get going on a new Lisp-like language, I would suggest that you join us in Hyperledger Labs where we have nascent efforts around new LLVM-based tooling.

There is an existing project started by Monax which @seanyoung at the helm, which is a Solidity FE and WASM backend - written using LLVM in Rust:

https://github.com/hyperledger-labs/solang

And there is the work by Second State on SOLL, which is in a pretty mature state (live ERC20 contract on ETH and ETC mainnet), which is a Solidity FE, and an eWASM backend - written using LLVM in C++:

https://github.com/second-state/soll

That has optional support for the EVM through the work of @lialan of ETC Core:

https://github.com/etclabscore/evm_llvm

https://medium.com/etclabscore/the-evm-llvm-is-coming-to-ethereum-classic-what-you-need-to-know-c13962f25571

Both Second State and Monax seem keen to work together here, and my hope is that we will be bringing all of these projects together into a single effort in the very near future - so we would have:

- Solidity FE
- EVM or WASM or eWASM backend (and maybe more soon)

And that would then be an EXCELLENT place for further smart contract languages to be built (ie. you would write an LLL front-end which could either just be developed directly within that HL Labs repo, or we would have a modular setup where you could develop your front-end elsewhere and dynamically combine it via some plugin pattern.

**Comment by leonardoalt** [comment]
@bobsummerwill so you're saying you're willing to fix/maintain LLL?

**Comment by zigguratt** [comment]
Thanks for that information, @bobsummerwill! I'll definitely take a look.

**Comment by bobsummerwill** [comment]
@leonardoalt No, I am not saying that.
I do not have the resources to support LLL directly.   I am just offering an alternative future home for Daniel or others, where we can build a plurality of smart contract languages leveraging the maturity of LLVM.

SOLL or Solang ends up as “The Clang”.
And you could have a raft of other front ends, maybe starting with LLL and Vyper (if this made sense for Vyper too).   And then you could add Axlang, Plutus, DAML, LegalTech languages and anything you want.

You would get C++ and Rust “for free” too.

“ Originally implemented for C and C++, the language-agnostic design of LLVM has since spawned a wide variety of front ends: languages with compilers that use LLVM include ActionScript, Ada, C#,[5][6][7] Common Lisp, Crystal, CUDA, D, Delphi, Dylan, Fortran, Graphical G Programming Language,[8] Halide, Haskell, Java bytecode, Julia, Kotlin, Lua, Objective-C, OpenGL Shading Language, Ruby,[9] Rust, Scala,[10] Swift, and Xojo.”

https://en.m.wikipedia.org/wiki/LLVM

**Comment by lialan** [comment]
So, this is a discussion about removing LLL from Solidity compiler, rather than deprecating the LLL IR standard. 

AFAIK, LLL is still used in Vyper to generate EVM binaries. Even though Vyper has its own LLL codegen module, it is not sophisticated. `lllc` could be used in that case to generate better binary code. Would removing LLL from Solidity compiler result in us loosing that kind of opportunity?

**Comment by axic** [comment]
There is no "LLL IR standard". I have tried to create that 3 years by documenting it [here](https://github.com/axic/lll-grammar). What is in the source tree of Solidity is the original LLL compiler. Serpent's (and later Vyper's) was not compatible with it, additionally Vyper's implementation doesn't even use the S-Expressions syntax, but uses brackets instead.

**Comment by lialan** [comment]
> There is no "LLL IR standard". I have tried to create that 3 years by documenting it [here](https://github.com/axic/lll-grammar). What is in the source tree of Solidity is the original LLL compiler. Serpent's (and later Vyper's) was not compatible with it, additionally Vyper's implementation doesn't even use the S-Expressions syntax, but uses brackets instead.

Thanks for the explanation.

**Comment by bobsummerwill** [comment]
FYI ... https://twitter.com/BobSummerwill/status/1217488177482489856

Just a quick question, @axic, @chriseth, @winsvega ... Are there still LLL-generated tests?   If so, how do those work these days?   Or were they replaced with some others means of generating the bytecode in the last couple of years?  Thanks!

**Comment by winsvega** [comment]
Most of the tests use lll in filler files.
I can maintain solidity fork for the lllc

**Comment by bobsummerwill** [comment]
Is that what you are going to do, @winsvega?
What have you been doing to this point?
Or is this only newly problematic as of this merge and you do not have it solved yet?
You will need to maintain those fork and use that fork as-and-when those tests need regenerating?

**Comment by winsvega** [comment]
Yes. I only need lllc to convert opcodes and complex lll statements into bytecode.
