### ISSUE TITLE
Test 0.6.0 prerelease on remix

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7969]

**Comment by chriseth** [comment]
Callbacks do not really work yet.

**Comment by axic** [comment]
> Callbacks do not really work yet.

Are they using the new solc-js (or just a 0.5 release)?!

**Comment by LianaHus** [comment]
we use "solc": "^0.5.13"

**Comment by axic** [comment]
Testing 0.6.0 will not work without using `master` of solc-js.

**Comment by chriseth** [comment]
@LianaHus can you upgrade to master, please?

**Comment by chriseth** [comment]
We were not able to fully test the callbacks in time. Let's see...
