### ISSUE TITLE
re-check documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7970]
- [x] ├── 050-breaking-changes.rst
 - [x] ├── 060-breaking-changes.rst https://github.com/ethereum/solidity/pull/8001
 - [x] ├── abi-spec.rst https://github.com/ethereum/solidity/pull/8002
 - [x] ├── assembly.rst https://github.com/ethereum/solidity/pull/8022
 - [x] ├── bugs.rst
 - [x] ├── common-patterns.rst https://github.com/ethereum/solidity/pull/8011
 - [x] ├── contracts
 - [x] │   ├── abstract-contracts.rst
 - [x] │   ├── constant-state-variables.rst
 - [x] │   ├── creating-contracts.rst
 - [x] │   ├── events.rst
 - [x] │   ├── function-modifiers.rst
 - [x] │   ├── functions.rst
 - [x] │   ├── inheritance.rst
 - [x] │   ├── interfaces.rst
 - [x] │   ├── libraries.rst https://github.com/ethereum/solidity/pull/7980
 - [x] │   ├── using-for.rst https://github.com/ethereum/solidity/pull/7981
 - [x] │   └── visibility-and-getters.rst https://github.com/ethereum/solidity/pull/7982
 - [x] ├── contracts.rst
 - [x] ├── contributing.rst
 - [x] ├── control-structures.rst
 - [x] ├── examples
 - [x] │   ├── blind-auction.rst https://github.com/ethereum/solidity/pull/7988
 - [x] │   ├── micropayment.rst https://github.com/ethereum/solidity/pull/7988
 - [x] │   ├── modular.rst
 - [x] │   ├── safe-remote.rst
 - [x] │   └── voting.rst
 - [x] ├── grammar.txt
 - [x] ├── index.rst
 - [x] ├── installing-solidity.rst
 - [x] ├── introduction-to-smart-contracts.rst
 - [x] ├── layout-of-source-files.rst
 - [x] ├── lll.rst
 - [x] ├── metadata.rst
 - [x] ├── miscellaneous.rst
 - [x] ├── natspec-format.rst
 - [x] ├── resources.rst
 - [x] ├── security-considerations.rst https://github.com/ethereum/solidity/pull/8009
 - [x] ├── solidity-by-example.rst https://github.com/ethereum/solidity/pull/8010
 - [x] ├── solidity-in-depth.rst (only depends on `types` now)
 - [x] ├── structure-of-a-contract.rst (leo)
 - [x] ├── style-guide.rst https://github.com/ethereum/solidity/pull/8005
 - [x] ├── types
 - [x] │   ├── conversion.rst https://github.com/ethereum/solidity/pull/8023
 - [x] │   ├── mapping-types.rst https://github.com/ethereum/solidity/pull/8024
 - [x] │   ├── operators.rst https://github.com/ethereum/solidity/pull/8026
 - [x] │   ├── reference-types.rst
 - [x] │   └── value-types.rst https://github.com/ethereum/solidity/pull/8028
 - [x] ├── types.rst (leo)
 - [x] ├── units-and-global-variables.rst (leo)
 - [x] ├── using-the-compiler.rst (leo)
 - [x] └── yul.rst
 - [x] check that we mention that structs and enums can be defined at global level.

**Comment by ChrisChinchilla** [comment]
When this is done, I'll do a wider review for more flow and consistency, but that doesn't need to stop the release :)

**Comment by chriseth** [comment]
Closing since we have pull requests for everything.
