### ISSUE TITLE
Update version pragmas in documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7979]

**Comment by ChrisChinchilla** [comment]
I'll do this

**Comment by ChrisChinchilla** [comment]
`pragma solidity >=0.6.0 <0.7.0;` I guess? Or bump both? `pragma solidity >=0.6.0 <0.8.0;`

**Comment by chriseth** [comment]
Ah, wanted to discuss hat during the meeting. It should be `>=0.5.0 <0.7.0` if it already works with 0.5.0 (most should), otherwise `^0.6.0`.

**Comment by ChrisChinchilla** [comment]
@chriseth Going through this now, but just as a warning, it might break tests, as `^0.6.0` results in errors for nightly and developer builds of 0.6.0, which are less than 0.6.0, and I think an actual build of it doesn't exist yet as it's not be released… As far as I understand…

**Comment by ChrisChinchilla** [comment]
Done, in the PR above, not sure this is complete. Reading through breaking changes doc and the docs, I can see more places that need updating, but that can probably wait and needn't block release.

**Comment by chriseth** [comment]
It's good that we have the two "_release" test runs and see that they are green.
