### ISSUE TITLE
Include z3 in solc docker image

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7999]

**Comment by leonardoalt** [comment]
When I talked to @gnidan at Devcon he mentioned this would probably be more useful than the solc-js callback

**Comment by axic** [comment]
Is our preference clearly for z3 or cvc4?

**Comment by leonardoalt** [comment]
z3 because it has a Horn solver as well which we use for the CHC engine

**Comment by chriseth** [comment]
Careful: The docker image is also used to build the static binary - we have to see if that is still possible and how large it gets.

**Comment by leonardoalt** [comment]
Since it's a docker image anyway I would guess the size increase won't be meaningful.

**Comment by chriseth** [comment]
The binary is exported to the release page as `solc-static-linux` to be used without docker.

**Comment by yuetloo** [comment]
@chriseth, for your reference, a docker image with solc v0.5.15 and z3 on alpine has a compressed image size of 62.78 MB. 
 
https://hub.docker.com/r/yuetloo/solc_z3

The downloaded image size is 167MB.
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
yuetloo/solc_z3     latest              391701d449f4        13 hours ago        167MB
```

**Comment by axic** [comment]
Is this done? Is this more important now that we have dynamic z3 loading?

**Comment by ekpyron** [comment]
I think not done, but not really affected by dynamic z3 loading either.

**Comment by axic** [comment]
Ah, this is the "release solc image".
