### ISSUE TITLE
Document changes outside language

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#8007]
Came out of https://github.com/ethereum/solidity/pull/8001. Please see comment here: https://github.com/ethereum/solidity/pull/8001#issuecomment-565096251.

We should probably also list changes outside of the language:
- yul optimizer activated together with the legacy optimizer
- abiv2 not considered experimental
- C API changes
- storage layout export
- metadata hash options
- new error reporter

**Comment by christianparpart** [comment]
NB:

* [x] C API changes were already included in https://github.com/ethereum/solidity/pull/7898.
* [x] new error reporter: https://github.com/ethereum/solidity/pull/7368/files#diff-9b8fab691c00b9e5380b19ce882f3271R6

**Comment by erak** [comment]
@christianparpart This is about documenting the changes. As far as I can see, #7898 did not add a section to `060-breacking-changes.rst`.

**Comment by christianparpart** [comment]
Ah, I assumed we talked about Changelog. thx for the tip.

**Comment by chriseth** [comment]
I think the following are breaking enough to list them:

- yul optimizer activated together with the legacy optimizer
- C API changes
- metadata hash options
- new error reporter
