### ISSUE TITLE
Support Hera (next to evmone) in tests for Ewasm

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8016]
See the releases in https://github.com/ewasm/hera

Hera is EVMC compatible (albeit the current release is EVMC 6 while this repo uses 7, but it would be easy to update.)

**Comment by axic** [comment]
@chriseth since you mentioned there's no way currently to test our wasm output: this would be the easiest way.

**Comment by chriseth** [comment]
@axic are there any blockers still to solve?

**Comment by axic** [comment]
There wasn't a blocker back in December, just someone needed to do it. Now there is a block, need to merge EVMC 7 support in Hera (which shouldn't be a big deal, but was not priority as nothing uses it now).
