### ISSUE TITLE
Create a yul linter

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8019]
It would be nice to have some well defined rules and a linter for it. I think the "Yul printer" practically achieves that.

**Comment by mudgen** [comment]
Yes, a linter would be good.

**Comment by axic** [comment]
There was an attempt in #6844 by @christianparpart.

**Comment by chriseth** [comment]
You can actually just use solc for that, it will pretty-print the yul code after parsing.

**Comment by axic** [comment]
Yes, I've mentioned that in the opening comment. This is mostly about defining the rules.
