### ISSUE TITLE
Throw Error on Abstract Contract

### ISSUE THREAD

**Issue by Denton-L** [ethereum/solidity#802]
Currently, libraries are not allowed to inherit from each other. As a result, the following code should throw an error because it does not produce any bytecode and it will also never be inherited from, thereby, it is completely useless.

```
library Abstract {
    function func() returns (uint);
}
```

**Comment by redsquirrel** [comment]
This is not useless. I actually use abstract libraries in https://github.com/ConsenSys/live-libs in order to allow contracts to compile against libraries when the source code is unavailable. (Live Libs generates the abstract source from the stored ABI.)

**Comment by Denton-L** [comment]
Ah, I stand corrected!
