### ISSUE TITLE
Natspec errors do not report the location of the error

### ISSUE THREAD

**Issue by dddejan** [ethereum/solidity#8043]
For contract such as 

```solidity
pragma solidity >=0.5.0;
/// @hey hey hey
contract Test {}
```

The error report is limited to 

```console
$ solc Test.sol 
Error: Doc tag @hey not valid for contracts.
```

This is related to #2137 but seems to be different.

The issue makes it difficult to debug compile errors (e.g., they don't show up in an IDE).

**Comment by Marenz** [comment]
What version did you try this on?

**Comment by Marenz** [comment]
Ah, you mentioned it the other issue: latest 0.5. It seems to work in 0.6.0 though.

**Comment by Marenz** [comment]
Nevermind, also fails on 0.6.0

**Comment by Marenz** [comment]
This will be fixed by https://github.com/ethereum/solidity/pull/7834 so I leave this up to @erak

**Comment by axic** [comment]
```
Error: Documentation tag @hey not valid for contracts.
 --> 8043.sol:2:1:
  |
2 | /// @hey hey hey
  | ^ (Relevant source part starts here and spans across multiple lines).
```

Seems to be correct now as stated by #7834.
