### ISSUE TITLE
If-else does not work when condition involves msg.sender

### ISSUE THREAD

**Issue by C4Q6EB** [ethereum/solidity#8050]
## Description

Contents of `if`/`else` appear disregarded when testing the equality of `msg.sender` and an address.

## Environment

- Compiler version: `0.5.14+commit.01f1aaa4.Darwin.appleclang`
- Target EVM version (as per compiler settings): Istanbul, by default
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: Geth (Clique)
- Operating system: macOS 10.15.1

## Steps to Reproduce

```solidity
event TestEvent(
    bool b
);

function testFunction() public {
    address expected = 0x734C384bf73C3DEe40A5a99D616064a5E4FDbb22;

    if (msg.sender == expected) {
        emit TestEvent(true);
    } else {
        emit TestEvent(false);
    }
}
```

Calling `testFunction` by sending a transaction to the address of the contract gives the following transaction receipt. `'logs': []` is unexpected since an event is emitted in either case of `if`/`else`.

```python
AttributeDict({
    'blockHash': HexBytes('0x3488bb8ccf32f3ba827f4e968f9bd339d7850bcf3769b19a9323b69347509f07'),
    'blockNumber': 11854,
    'contractAddress': None,
    'cumulativeGasUsed': 22404,
    'from': '0x734c384bf73c3dee40a5a99d616064a5e4fdbb22',
    'gasUsed': 22404,
    'logs': [],
    'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
    'status': 0,
    'to': '0x316220802e907fe2937dc44bb7f6eac177a3f6d2',
    'transactionHash': HexBytes('0x7d0afda47cbdab0257e27312da939931b70d030e6c991db4e825c912c7816f71'),
    'transactionIndex': 0
})
```

The problem does not persist when the condition `msg.sender == expected` is replaced with other conditions like `1 == 1` or boolean values like `true`.

However, the problem persists even when the result of the equality test is stored in a boolean variable.

```solidity
event TestEvent(
    bool b
);

function testFunction() public {
    address expected = 0x734C384bf73C3DEe40A5a99D616064a5E4FDbb22;

    bool equal = (msg.sender == expected);

    if (equal) {
        emit TestEvent(true);
    } else {
        emit TestEvent(false);
    }
}
```

Not only are the events not emitted, but other operations performed within the if-else clauses (e.g. variable assignments) are also not executed.

**Comment by bshastry** [comment]
@C4Q6EB Thanks for your report.

Notes: I could not reproduce this via Remix and solc 0.5.14+

```
contract C {
    event TestEvent(
        bool b
    );
    
    function testFunction() public {
        address expected = 0x734C384bf73C3DEe40A5a99D616064a5E4FDbb22;
    
        if (msg.sender == expected) {
            emit TestEvent(true);
        } else {
            emit TestEvent(false);
        }
    }
}
```

The contract above emits a log entry `false` because in the remix environment `msg.sender` is different than the encoded expectation.

Here's the transaction log produced via Remix

```
[
	{
		"from": "0x692a70d2e424a56d2c6c27aa97d1a86395877b3a",
		"topic": "0x691d596d95422129c71f578925682e79de7ea5b43cc614e9df2f6aefde727063",
		"event": "TestEvent",
		"args": {
			"0": false,
			"b": false,
			"length": 1
		}
	}
]
```

**Comment by C4Q6EB** [comment]
Thank you, @bshastry and @Marenz, for your response.

@bshastry, would the results be any different if the contract is deployed on a proof-of-authority network?

This issue surfaced on a private network running the Clique consensus algorithm but has also been reproduced on the developer chain launched with `geth --dev --rpc`.

**Comment by C4Q6EB** [comment]
The problem was resolved by compiling and deploying the contract with Truffle instead of `solc` + Web3. Now it works on both Geth Clique and Parity Aura. Thank you for your time and attention.
