### ISSUE TITLE
Remove old parser error for using "constant" state mutability

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8061]
See https://github.com/ethereum/solidity/blob/develop/libsolidity/parsing/Parser.cpp#L450

**Comment by bshastry** [comment]
One more occurrence in the same file (perhaps for variable decls) here https://github.com/ethereum/solidity/blob/07a56625e4d07610adbbd493e10d2f419dbc5400/libsolidity/parsing/Parser.cpp#L723

**Comment by christianparpart** [comment]
We briefly discussed this in our meeting. We won't remove the `to discuss` label just yet, because maybe @axic want to share some notes.

Summary:
* Makes sense to remove, should also touch VariableDeclaration (wrt. isConstant).

**Comment by axic** [comment]
Are we taking this into 0.7.0 or some future release?

@elenadimitrova can we add this to planning?

**Comment by hrkrshnn** [comment]
@christianparpart Can you clarify "should also touch VariableDeclaration (wrt. isConstant)."?

**Comment by chriseth** [comment]
Closed by https://github.com/ethereum/solidity/pull/9405
