### ISSUE TITLE
More specific error message for division by zero

### ISSUE THREAD

**Issue by rschumi0** [ethereum/solidity#8064]
It would be nice if there could be a more meaningful error message when a division by zero is happening. Right now the message is only: VM error: invalid opcode. 

This can make debugging more troublesome, especially since unexpected zeros can occur easily, e.g., when an overflow happens.

**Comment by chriseth** [comment]
This kind of conflicts with the assert / require dualism. I would say it is a duplicate of https://github.com/ethereum/solidity/issues/1686

**Comment by cameel** [comment]
Do we consider this solved now that we have implemented #9995?

**Comment by axic** [comment]
Yes. It is now up to frameworks to support it, there are some pending issues for that, but it is beyond our control.
