### ISSUE TITLE
A letter to Vitalik 

### ISSUE THREAD

**Issue by simsim314** [ethereum/solidity#8077]
Hello! Please pass this letter to anyone who knows what is crypto currency.

Hello Vitalik! 

I'm Michael Simkin. I'm 1999 international math olympiad  [bronze medalist](https://www.imo-official.org/participant_r.aspx?id=5682)

And I've also solved several open problems in [Conway's game of life](https://www.conwaylife.com/wiki/Michael_Simkin).

I'm sure this means something to you...

I'm from Israel, and I've opened a [headstarter campaign ](https://headstart.co.il/project/55286) (sorry for the hebrew see below). A headstarter campaign for Israeli Tea Party. The first party which is also a facebook group. I write to you just as the face of crypto community so people would enjoy more reading it. Our corrupt government stole my voice using center elimination technique using the fact that center is needed for self organisation. Well no, not any longer not since 2014. What is needed is only a good facebook admin, like myself of course. I need to let people know and teach them make queries of the sort "60M likes on facebook page and we all start to write korekt ingliш" - and if they do they start a new facebook group with this title (that's all). If people know this trick and the admin taught them it, it's all they need to self organize, even on a simple platform as facebook, which already everyone has and just don't know how to use to create free self organization. This is the admin responsibility today to do it on facebook. I wrote Mark that I trust facebook more than my government, and that he is welcome to support me as well on the  [headstart](https://headstart.co.il/project/55286). 

I tell you the same thing. I trust facebook more than my corrupt government. I want to have a voice inside my goverment that says this. I want to have Israeli Tea Party which is facebook party and a group in facebook in the kneset (in the Israeli official goverment). We have the right of self organization as we wish. Obviously I know we need to switch to smart contract based social platform but this in the future. For starters lets have facebook group which is an official Israeli goverment party. 

I need money to register the party and to start the campaign. How would I explain millions of Israelis what is Israeli Libertarianism? What facebook group which is also a party? I don't know - but if I get the money I can start at least the campaign. I can start to pass the message. I can let people know and teach them everything they need to know. 

I will teach people to self organize and restore the lost group. They will need to use Diffie and Hellman encryption to know how to recover from admin lose. This is very simple technique you need to store a communication graph on github, and with P2P  encryption you can open it all to everyone, and send keys to each individual. The only problem is training time or more exactly app spreading time, and this means money in our modern capitalistic society. 

So how does it all works and what I'm selling you. At any given time we have 12 moderators changing each week, from two groups. 6 regular and 6 VIP moderators. Sorted in paying order. My idea is to hold a weekly ceremony, in reality/mixed reality/virtual reality. In which the admin is making its weekly duties but in a covered by press (twitch for example) event. This event consists of 4 parts which ensures group survival and prosperity. 

1. Transfering the moderators. (I sell the moderatory rights for a week or longer to the party supporters).  
2. Training survival technique the group 
3. Letting the top people in the group to represent us in the goverment. Top by simple facebook metrics for now (voted on facebook open poll). The top 3/5/10 commentators of the week, we take for 4 years - and only they vote among themselves who they want to send to represent us in the kneset (israeli goverment). We don't have a very high amount of corruption, and governments like that citizens can self organize and send people to represent them like in any democracy today. 
4. Just p2p communication to increase the signal. Dividing into pairs and making chavrusa meeting for 15 minutes switching pairs. 

This brings me to my headstarting campaign. I hope you get that you don't lose anything if I'm just one crazy person. If you want to choose reality where this happens place few backs to have facebook group which is also an Israeli government party which handles all it's data through facebook. Sorry this is in hebrew. I wasn't imagining writing this letter. Here is the meaning of the pricing: 

I sell the following rights: 
40 shekel ~ 12$ (1 week moderator)
120 shekel ~ 35$ (4 weeks in a raw moderator) 
200 shekel ~ 58$ (1 hour of conversation with the admin covered in the group) 
250 shekels ~ 72$ (VIP moderator for 1 week)
500 shekels ~ 144$ (3 hours in depth conversation with the admin)
800 shekels ~ 230$ (VIP moderator for 4 weeks)
2500 shekels ~ 720$ (hosting the ceremony)

Remember the party representation in the government are Israeli citizens that were the best and brightest of Israeli libertarians a term which is defined by the admin. And enforced by the moderators who's job is to remove the trolls and keep up everyone's topic on average to be Israeli Libertarianism. I'm obviously the first admin. But admins can be easily replaced, by voting for example and by revolts as well. I'm the first admin will teach them this first things. It's basic group survival technique. How do I know there is enough Israeli libertarians at all? Well this is why I need to start the campaign, I need publicity. I know my rights were violated and many people agreed on the facebook page when my goverment took the center of my party and left with nothing. I'm very angry, very angry at my current goverment. I want to change it. I've done my part, I need you to support me. 

I never thought of doing this before, it's a last second thought to survive as the Israeli Tea Party. A jump into cold water. I need 40K$ in 6 days and this is a kickstarter so I do crazy things.

**Comment by Marenz** [comment]
I am not sure what this is about, but I am pretty sure it doesn't belong here. I also doubt Vitalik will read our issue list.
