### ISSUE TITLE
Document REVERT reason encoding in Contract ABI Specification

### ISSUE THREAD

**Issue by livnev** [ethereum/solidity#8080]
## Description

As far as I can tell, the REVERT reason encoding is not canonically defined in any documentation, and is best pieced together from the [solidity PR that introduced it](https://github.com/ethereum/solidity/pull/3364) and [this comment on EIP 838](https://github.com/ethereum/EIPs/issues/838#issuecomment-458919375). Since it is now an important part of the Ethereum Contract ABI, I think it should be specified on the "Contract ABI Specification" page.

**Comment by elenadimitrova** [comment]
The encoding is actually specified in the [`revert` control structures section of the docs](https://solidity.readthedocs.io/en/latest/control-structures.html#revert). Is this not sufficient or is it a matter of moving that description to the "ABI specification" page?

**Comment by livnev** [comment]
> The encoding is actually specified in the [`revert` control structures section of the docs](https://solidity.readthedocs.io/en/latest/control-structures.html#revert). Is this not sufficient or is it a matter of moving that description to the "ABI specification" page?

I couldn't find that documentation before, thank you. I would suggest moving it to the ABI spec page because I think this is part of the Ethereum contract ABI now and afaict the ABI spec page is the "canonical" reference for that...

**Comment by axic** [comment]
I'd argue it is strictly not part of the ABI encoding. It is a specific application of the ABI encoding.

That being said one could link from the ABI encoding part of the documentation or place it as an appendix there.

**Comment by livnev** [comment]
> I'd argue it is strictly not part of the ABI encoding. It is a specific application of the ABI encoding.
> 
> That being said one could link from the ABI encoding part of the documentation or place it as an appendix there.

Fair enough, but it seems like the idea is for this to be a standard, and not just solidity-specific? Also, where does the ABI encoding spec mention putting function selectors in return data?

**Comment by chriseth** [comment]
We might want to have one overview page that describes the structure of calldata and of returndata be, both in the success and in the failure case.
