### ISSUE TITLE
Introduce error instead of warning for functions called "fallback" or "receive"

### ISSUE THREAD

**Issue by nicholashc** [ethereum/solidity#8081]
## Description

The fallback function syntax changes in Solidity 0.6.0 do not reserve `fallback` or `receive` as keywords. Standard functions named `fallback()` and `receive()` can be declared alongside, or instead of, the built-in fallback methods with the same names. Rather than reducing developer error and improving the readability of the code, this can lead to confusing syntax or, at worst, maliciously misleading contracts.

Please consider the following examples:

```javascript
pragma solidity 0.6.0;

/* 
* intended use of the new fallback syntax
*/
contract StandardFallback {

    /*  
    * accepts ether sent with no txData
    */
    receive() external payable {}

    /*
    * refuses ether sent with txData that does not match any function signature in the contract
    */
    fallback() external {}
}


/* 
* confusing or malicious use of fallback syntax
*/
contract ConfusingFallback {

   /* 
   * declares a payable function called "fallback()" that is called with txData 0x552079dc
   * this is NOT the fallback function. no fallback function is declared in this contract.
   * ether sent with empty or non-matching txData is refused (exceptions: `selfdestruct` and `coinbase` rewards)
   */
    function fallback() external payable {}
}


/* 
* standard functions with misleading names in an inherited contract
*/
contract NotFallback {
    function fallback() external virtual {}
    function receive() external virtual {}
}


/*
* malicious contract creates the impression that the fallback function was overridden 
*/
contract ConfusingInheritance is NotFallback {
    
   /* 
   * valid fallback function accepts ether sent with no txData or data that does not match any function sig in the contract
   */
    fallback() external payable {}

   /* 
   * inherited functions are overridden without affecting the contract's fallback functionality
   */
    function fallback() external override {}
    function receive() external override {}
}
```

`function fallback() external payable {}` is a valid function declaration but  _not a_ fallback function. This is confusingly similar to the <0.6.0 syntax of `function() external payable {}`, which is _is a valid_ fallback declaration.

Rather than simply throwing a warning in the compiler when used in standard functions, the `fallback` and `receive` keywords could be disallowed as names for standard functions. This would improve code readability and auditability. It would also prevent a possible fringe case in which a malicious author crafts misleading code that takes advantage of the ambiguous syntax changes in 0.6.0.

## Environment

- Compiler version: version: 0.6.0+commit.26b70077
- Target EVM version: Petersburg
- Optimisations: 200
- Environment: Remix JavaScript VM

**Comment by axic** [comment]
Thanks for highlighting this. I think we should disallow those functions.

**Comment by ekpyron** [comment]
This is rather weird - ``fallback`` and ``receive`` are in fact keywords and I was pretty sure that we had errors for using them as function names - I'll look into it.

**Comment by ekpyron** [comment]
Ah ok, I should have read more carefully - we do indeed have a warning, so the question is whether to have an error instead. I'm adding the "to discuss" label again.

**Comment by Marenz** [comment]
We prefer to keep it a warning until 0.7.0 where we want to re-evaluate the situation, but we also want to hear @axic 's opinion about this

**Comment by nicholashc** [comment]
Thanks for your responses.

I'm curious about the language design philosophy for determining when something should be a Warning vs. an Error. In this case, does the design of the language extend to a potential user of a smart contract who might be reading the verified source code on Etherscan, but not compiling it themselves? Should that type of user be able to make reasonable assumptions about the behaviour of the code? I'm thinking of the many honeypots and other misleading contracts that leverage ambiguous but valid Solidity to mislead potential users (for example, uninitialized storage pointers that long triggered a compiler warning but not an error).

**Comment by ekpyron** [comment]
In this particular case, we don't want to cripple the ability of new contracts to interface with old contracts that define an external function called "receive" or e.g. a Vyper contract that still might define such a function.
In the future we may allow to import functions from ABI specifications which would basically allow renaming in these cases - at which point we probably won't hesitate to make this an error.

**Comment by chriseth** [comment]
I think we should allow such functions with a warning.

**Comment by ekpyron** [comment]
We could be quicker about making this an error, if/when https://github.com/ethereum/solidity/issues/1687  allows backwards compatibility with older contracts and compatibility with other languages.
