### ISSUE TITLE
Incorrect compiler version in the examples provided by https://solidity.readthedocs.io/

### ISSUE THREAD

**Issue by AnonymousMonkey2021** [ethereum/solidity#8099]
## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

While every example mentions that they support ">=0.4.22 <0.7.0;". 
But in fact, a lot of them don't. They only work with compiler versions >= 0.5.0

**Comment by leonardoalt** [comment]
Hi @JackHFeng ,
Not every example mentions that version range. In a quick grep I see
```
pragma solidity >=0.5.0 <0.7.0;
pragma solidity >=0.4.22 <0.7.0;
pragma solidity >=0.4.0 <0.7.0;
pragma solidity ^0.6.0;
pragma solidity >=0.4.99 <0.7.0;
```
and many others.
Can you list which ones specifically are wrong?

**Comment by AnonymousMonkey2021** [comment]
On this page, https://solidity.readthedocs.io/en/v0.6.1/solidity-by-example.html. 
Contracts:
Token
BlindAuction
SimpleAuction
Purchase

0.4.22 didn't work due to the word "payable"
Thanks for the quick reply!!!

**Comment by erak** [comment]
I've written a tiny script which hooks into our doc example extraction, and aims on finding the minimal version and compiling one example with a static build, downloaded from the release page. Does someone maybe takeover? The version extraction from the example itself is still missing, though.

**Comment by chriseth** [comment]
Sounds good!

**Comment by erak** [comment]
This is up for grabs again. Please see: https://github.com/ethereum/solidity/pull/8230.
