### ISSUE TITLE
Add a "name" field to the compiler section in metadata

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8109]
Requested by @ligi

**Comment by axic** [comment]
What name?

**Comment by chriseth** [comment]
The name of the compiler implementation, i.e. "official solc" or "soll".

**Comment by chriseth** [comment]
Although I don't think any of the other compilers use metadata.

**Comment by ligi** [comment]
thought vyper must also support this - but seems it is not the case. Anyway it would make it more robust in the future when other compilers start supporting it. But has low priority - was just noting in the chat that I felt it is missing when writing a parser for the metadata and saw there is a version - but no explicit "version of what"? Only an implicit - "yea it *should* be solc"

**Comment by axic** [comment]
There is the `language` field, isn't it?

**Comment by chriseth** [comment]
We do not have a real use for this now. We can look at this again when other compilers implement metadata and / or standard io.
