### ISSUE TITLE
Investigate missing test run on documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8110]
See https://github.com/ethereum/solidity/pull/7869/files#r364105867

**Comment by erak** [comment]
I'll have a look.

**Comment by erak** [comment]
@chriseth Mmh, that's weird. I can't reproduce it (added some invalid code to the example in `function-modifiers.rst` and ran `cmdlineTests.sh`). The test was extracted successfully and an compilation error occured. The example also does not contain `// Will not compile`...

**Comment by chriseth** [comment]
I thin this has been fixed. The indentation was off.
