### ISSUE TITLE
Run profiler on yul optimizer

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8113]
We should evaluate the performance of the yul optimizer - it got a little sluggish lately.

Maybe related: https://github.com/ethereum/solidity/issues/5401

**Comment by christianparpart** [comment]
Using https://github.com/ethereum/solidity/blob/develop/test/libsolidity/semanticTests/viaYul/erc20.sol for performance testing. That's the second-biggest file we could found that seems to make sense. If someone is having a better .sol file for testing, I'd please tell me. :)

Tool: `valgrind --tool=callgrind solc --ir path/to.sol/file && kcachegrind`

**Comment by axic** [comment]
I guess we are tracking this in #10405.
