### ISSUE TITLE
Grammar for fallback and receive ether functions

### ISSUE THREAD

**Issue by GNSPS** [ethereum/solidity#8116]
## Description

I am unsure if I've missed something but it seems to me after taking a hard look (and taking on the maintenance of the ANTLR parser) that both the fallback and receive ether function definitions are missing from the grammar.

Am I right in assuming this?

**Comment by erak** [comment]
@GNSPS Yes, you're right. The grammar for ``fallback() {}`` and ``receive() {}`` is indeed missing. Would you like to fix it?

**Comment by erak** [comment]
Bringing this up again: https://github.com/ethereum/solidity/issues/3158 :wink:

**Comment by GNSPS** [comment]
Happy to take it on!

**Comment by GNSPS** [comment]
The grammar is also missing a proper definition for constructors.

I see two ways of solving this. The first would be to create a different definition for all the special functions since none of them allow any return parameters. Like so:

```
functionDefinition
  : specialFunctionDefinition
  | simpleFunctionDefinition ;

simpleFunctionDefinition
  : natSpec? 'function' identifier? parameterList modifierList returnParameters? ( ';' | block ) ;

specialFunctionDefinition
  : natSpec? ( 'constructor' | 'fallback' | 'receive') parameterList modifierList block ;

ConstructorKeyword : 'constructor' ;
```

The second would be to not consider them a special case at all and just have a single definition accepting the key words

**Comment by GNSPS** [comment]
The grammar is also missing a proper definition for constructors.

I see two ways of solving this. The first would be to create a different definition for all the special functions since none of them allow any return parameters. Like so:

```
functionDefinition
  : specialFunctionDefinition
  | simpleFunctionDefinition ;

simpleFunctionDefinition
  : natSpec? 'function' identifier? parameterList modifierList returnParameters? ( ';' | block ) ;

specialFunctionDefinition
  : natSpec? ( ConstructorKeyword | FallbackKeyword | ReceiveKeyword ) parameterList modifierList block ;

ConstructorKeyword : 'constructor' ;
FallbackKeyword : 'fallback' ;
ReceiveKeyword : 'receive' ;
```

The second would be to not consider them a special case at all and just have a single definition accepting the extra keywords:

```
functionDefinition
  : natSpec? ( 'function' identifier? |  ConstructorKeyword | FallbackKeyword | ReceiveKeyword ) parameterList modifierList returnParameters? ( ';' | block ) ;

ConstructorKeyword : 'constructor' ;
FallbackKeyword : 'fallback' ;
ReceiveKeyword : 'receive' ;
```

Any preferences, @erak?

(All the above examples are in ANTLR but I'll translate them to the proper syntax once we decide on this)

**Comment by erak** [comment]
I think in the end it's a trade-off between explicitness and compactness (non-redundancy). I'd tend to go with the second option you've sketched, because I have the feeling that compactness overweights explicitness in this case.
