### ISSUE TITLE
 How does solidity send() & transfer() know about contract ether?

### ISSUE THREAD

**Issue by thecircleoflifefree** [ethereum/solidity#8123]
-If a contract wants to hold ether you create a payable function that receives the msg.value.
-To withdraw ether you would specify a function with the intended address destination and amount.

However when I test, the second statement only seems to be true if I use a mapping. On the example below not concerned about security, so this code would not apply to real life.

pragma solidity >=0.5.0 <0.6.0;

contract CheckBehavior {

mapping(address => uint256) _deposits;

 function depo() public payable{

    _deposits[msg.sender]= msg.value;
}

//not working
function withdrawA(uint256 _amt) public {

    msg.sender.transfer(_amt);
}

//not working , I would expect this to work fine as withdrawWithGas()

function withdrawB(address payable payee, uint256 _amt)  public {
     
    payee.transfer(_amt);
}

//Works. My understanding is that the mapping is a security pattern to avoid re-entrancy, as
this keeps track
function withdrawWithGas(address payable payee) public {
    uint256 payment = _deposits[payee];

    _deposits[payee] = 0;

    payee.transfer(payment);

   
}

}

So I’m trying to undestand is that how does solidity know when it is refering about the contract ether itself.

**Comment by chriseth** [comment]
Sorry that I cannot directly help, but this question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
