### ISSUE TITLE
Support contracts and interfaces for mapping keys.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#8128]
## Abstract
Contracts and interfaces should be allowed for mapping keys.
```
interface IApple {}
contract Banana {}
interface ICherry {}

contract Apple {
    mapping(IApple => bool) public apples;
    mapping(Banana => bool) public bananas;
    mapping(address => bool) public cherries;

    constructor(ICherry cherry) public {
        cherries[cherry] = true;
    }
}
```
> ParserError: Expected elementary type name for mapping key type
> `mapping(IApple => bool) public apples;`

> TypeError: Type contract ICherry is not implicitly convertible to expected type address.
> `cherries[cherry] = true;`

## Motivation
When creating a mapping of contract to thing I have to use the elementary types as the mapping key which means `address` in this case.  Unfortunately, since contracts and interfaces do not implicitly cast to `address`, this means every time I use the interface I must cast to address first.  This leads to a lot of unnecessary code, and can sometimes leads to bug as explicit casts are error prone.

## Specification
If a contract or interface is used as a `mapping` key, it should be functionally equivalent as an `address` being used as the mapping key with the exception of type checking when the mapping is indexed.

## Backwards Compatibility
None.

**Comment by chriseth** [comment]
Easy enough!

**Comment by haltman-at** [comment]
Question: Would this *only* apply to contract types, or are other types also going to be allowed as mapping keys that currently aren't (e.g. enums or even function types)?  (Asking as someone who's going to going to have to support the change, not as someone who wants more features for his contracts. :P )

**Comment by ekpyron** [comment]
@haltman-at For reference: the PR we merged now allows contract (resp. interface) types and enums as mapping keys.
