### ISSUE TITLE
[DOCS] Possible DoS with block gas limit on blind auction example contract

### ISSUE THREAD

**Issue by kadenzipfel** [ethereum/solidity#8129]
## Description

It seems that in the docs, in the [blind auction example contract](https://solidity.readthedocs.io/en/latest/solidity-by-example.html#id2), that there is a possible DoS vulnerability. In the `reveal()` function, we loop through the bids in this array: `bids[msg.sender].length`, which doesn't seem to have a limited amount of bids. If the current highest bid is low enough, a griefer with enough funds could make so many bids that the loop costs too much gas to fit in the block, resulting in unexpected effects.

I propose that instead of allowing users to have multiple bids, we accept only one bid per person, and simply replace user's old bid with newly submitted ones.

**Comment by chriseth** [comment]
Thanks for noticing!
Note that these are only the bids set by a specific sender. Still, it could lead to the bid not being revealable. We could loop from the end and require to reveal one bid at a time, but that would make it more expensive and maybe also more complicated.

Other opinions?

**Comment by kadenzipfel** [comment]
Is there any benefit to users having multiple bids? As mentioned, I think users should only be able to have one bid, and if they'd like to change it, they could submit a new one, leading to the old one being deleted and the previous deposit being refunded.

**Comment by chriseth** [comment]
The reason for multiple bids is disguising a real bid among fake bids - I hope this is explained in the text.

**Comment by kadenzipfel** [comment]
If the bid values aren't known then why do real bids have to be disguised? The only benefit I see to that is that you can make an auction look more popular than it actually is. Am I missing something here?

**Comment by chriseth** [comment]
The ether transfer makes the bid values not totally invisible.

**Comment by chriseth** [comment]
I think the solution here is to reveal one bid at a time - especially for an example contract this could be easier.
