### ISSUE TITLE
TypeError too restrictive or inconsistent?

### ISSUE THREAD

**Issue by rschumi0** [ethereum/solidity#8139]
## Description

I noticed that it is possible to add int variables with different bit sizes, but an error is produced if an int_const is added to an int variable with a smaller bit size. Is there a particular reason why the one is allowed, but not the other? Would it be possible to allow both?

```
int8 a = 10;
int16 b = 234;
int c = b + a;   // works 
int c = 234 + a; // Produces a TypeError: Operator + not compatible with 
                 // types int_const 234 and int8. 
                 // In this case, you have to use 234 + int(a) instead.
```

## Environment
- Compiler version: 0.5.13
- Target EVM version (as per compiler settings): default
- Framework/IDE: Truffle and Remix
- Operating system: Ubuntu

**Comment by chriseth** [comment]
The reason is that `234` is treated as a `uint8` instead of an `int8`. Does that make it clearer?

**Comment by chriseth** [comment]
Please reopen if this still needs discussion.
