### ISSUE TITLE
Problem with the contract documentation

### ISSUE THREAD

**Issue by pacifics** [ethereum/solidity#814]
Hi,

I can't compile the contract documentation for our Dao. Without it is ok.

The source is here : https://github.com/pacifics/Dao

Frederic

**Comment by chriseth** [comment]
Please provide more information. Do you get a compiler error? Which compiler do you use?

**Comment by pacifics** [comment]
https://ethereum.github.io/browser-solidity/#version=soljson-latest.js
0.3.5-6610add6/Release-Emscripten/clang/Interpreter

DAO.sol:773:21: Error: Name has to refer to a struct, enum or contract.
                    TokenManager m = new TokenManager(address(this), false, 
                    ^----------^

**Comment by chriseth** [comment]
Sorry, but I'm really not sure if this is the correct place for your build issue. Do you think this might  be a bug in the compiler? If not, please ask for help on gitter or stackexchange.

**Comment by Denton-L** [comment]
I would recommend closing this issue. It seems that https://github.com/pacifics/Dao has been updated recently, presumably to fix this issue.

**Comment by pacifics** [comment]
OK. thank you.
