### ISSUE TITLE
[Yul] Allow or require curly braces surrounding switch cases.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8142]

**Comment by chriseth** [comment]
Discussion: Introducing curly braces would make this the only curly braces that do not contain a list of statements. Also, with simple indentation rules, this would cause double indentation. Finally, it currently "works".

We can revisit the issue when they annoy us.

**Comment by christianparpart** [comment]
my argument *for* curly braces is that it not just improves visual readability, but also helps alot in jumping forth and back in your editor via shortcuts. I personally do that a lot in VIM to jump based on braces.

Not having such a syntactic sugar would just make moving around less convenient.
