### ISSUE TITLE
Recursive datatypes

### ISSUE THREAD

**Issue by dddejan** [ethereum/solidity#8149]
Solidity does not support simple datatype recursion. This makes sense as it would be impossible to do because of the "value" semantics of contract storage: there is no pointers allowed in storage and no optional types. 

Nevertheless, recursive datatypes can be defined through the use of arrays and mappings. This is basically because empty arrays and mappings can be used as a "null" value. Example below.

```solidity
contract A {
    struct Tree {
        int x;
        Tree[] children;
    }
    Tree t;
}
``` 

It could be that this is a deliberate design decision or maybe was just allowed because it works. 

I opened this issue is to better understand the rationale for allowing recursion in datatypes (e.g., true real-world use cases) and to argue that maybe it's better do disallow datatype recursion entirely. 

Let me start with some arguments against recursion:

1. **Clarity of language**. Having a roundabout way in syntax to achieve recursion doesn't feel good.
2. **Ease of reasoning**. Without recursion, storage of the contract has a much nicer structure: seen as an abstract datatype tree, the depth of the contract data is finite. This helps with formal verification (and human understanding) because it is easier to anticipate the locations where a storage pointer can point to.
3. **Semantics**. Combined with deep copy assignments, recursion presents challenges in defining semantics. The following example illustrates this (similar to #736). Although you can compile this and run to see what will happen, it is not clear what the semantics are here?

```solidity
contract A {
    struct S {
        S[] e;
    }
    S s;
    function f() public {
        s.e.push(s);
    }
}
```

**Comment by chriseth** [comment]
The copy semantics are problematic, indeed, but don't you give a very good example for a use-case for the recursive data types as they are currently implemented?

Since I don't think this will lead very far, I'm closing this issue. Please re-open it if you have a specific proposal. If you want to discuss design decisions, then please join our gitter room: https://gitter.im/ethereum/solidity-dev
