### ISSUE TITLE
Assignments involving mappings

### ISSUE THREAD

**Issue by dddejan** [ethereum/solidity#8152]
Assignment gets complicated when the values involved include a mapping. Since mappings cannot be copied, in the context of an assignment they are either disallowed or are silently ignored when deeper inside reference types. This makes for confusing semantics that can lead to strange bugs.

Consider the following example:

```solidity
contract A {
    struct S {
        mapping(int=>int) m;
    }    
    S s1;
    S s2;    
    mapping(int=>int) m1;
    mapping(int=>int) m2;    
    constructor() public {
        s1.m[0] = 1;
        // Assignment 1: compiles OK
        s2 = s1;
        assert(s2.m[0] == 1); // Mapping ignored in copy so this fails
        // Assignment 2: compile error
        m2 = m1;
    }
}
```

Assignment 1 compiles OK, although there is a mapping within the struct S. This mapping is ignored while copying. Assignment 2 is explicitly disallowed by the compiler.

This issue is not about why mappings are not copied (this is an implementation detail), it is to to clarify the rationale for allowing the assignment at all, i.e., why not disallow all assignment that involves a mapping? Or at the very least, should the compiler warn about this behavior? Are there some Solidity coding patterns that require such assignments to be allowed (e.g., for smaller gas cost)?

The current "ignore" semantics make formal verification more complicated since the copying is not uniform and thus needs to be expanded manually into the logic of the verifier to ignore the mappings.

**Comment by leonardoalt** [comment]
We agree with that, and will disallow such behavior in the next breaking release (0.7.0): https://github.com/ethereum/solidity/issues/7739

**Comment by dddejan** [comment]
Excellent! Closing this then and will comment there if I have any follow-up.
