### ISSUE TITLE
[Doc] Mention various signature formats

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#8160]
## Abstract

Hey, I am trying to  standardize `appended compact signatures` in top of what GnosisSafe did (https://github.com/gnosis/safe-contracts/blob/892448e93f6203b530630f20de45d8a55fde7463/contracts/GnosisSafe.sol#L189).

There is interesting things happening in https://github.com/ethereum/EIPs/pull/2126, but it also seems to lack to standardize the signature format.

We have 4 formats I know:
- Contract (EIP1271): dynamic syze;  
- Canonical: 68 bytes size;
- Compact 65 bytes size (v is padded to a single byte); 
- Super compact 64 size (v is embedded in r bitwise https://eips.ethereum.org/EIPS/eip-2098)... 
 I think that maybe would be interesting to solidity have a type `signature` to create a new standard out of all, and we could use something like `function checkSig(signature memory signatures)` 

I think that if anything is done, it should be looked into what GnosisSafe done and how we could improve in solidity for this implementation be more "elegant". 

## Motivation

However I think that this is such common thing that solidity should have it embedded, so it becomes easier for all wallets understand the format of signature (and that is a signature, or multiple supported).

I know ya going to say to use Struct and Libraries, and yes, that's what I would have to use if this don't gets approved.

## Specification

WIP / Brainstorm

Signatures should:
- Dynamic Size;
- Depending on the type, Can be nested, a signature can contain other signatures that themselves can contain other signatures,
- Have type accessible to contracts know what to do;
- Can check against msg.sender
- Can be null (check against application logic) 

## Backwards Compatibility

Could be part of ABIV2Encoder, so its under experimental features.

**Comment by chriseth** [comment]
Damn, you got me on that ("I know ya going to say to use Struct and Libraries, and yes, that's what I would have to use if this don't gets approved.") :)

But to be honest, this just sounds like forcing an ERC by adding a feature to Solidity.

Is there some more complex thing that can rather be done with Solidity than just adding a signature type?

**Comment by 3esmit** [comment]
I tried to solve the problem with library and struct, however its really hard to came with a better solution. 

The problem is that EIP 1271 is a contract call and can have an arbitrary lenght signature, and needs to know the message being signed to be validated.

The best design would be less efficient then what GnosisSafe have because GnosisSafe decodes and verifies in the same loop, while using a library it would first loop to decode, then after loop around to verify.

I found out in Solidity it would be possible a library that:
- contains method to decode signatures into ` struct GenericSignature { SigType sigType; bytes sig; }` 
- which depending on the SigType could be then decoded into `struct ContractSignature { address validator, GenericSigature[] sigs }`

I tried doing with only one struct, but nasting structs is only supported for storage. 

@chriseth I think that now that signatures are maturing as EIP:
- consider pick up into the discussion to embrace a pattern of packed appended signatures natively in solidity; 
- or in case thats too specific, improve libraries to, similar how is done in js, callback for, in this case, validation to happen inside the same decode loop, so we can implement this as library without being a significant waste of gas.
- or, in case I am not seeing the obvious, enlighten me to the right path.

**Comment by ethernian** [comment]
Personally, I would like to see the `appended signatures` natively supported in solidity, because it could be really convenient for generalized Meta-Tx support (which is damn important!).

Nevertheless, I do also understand @chriseth who is reasonably cautious implementing on solidity level (I hope understood him correctly) any ERC which is not widely used, probably incomplete and can change later.

When we later achieve stability and usage numbers for the ERC, then we will surely have a better chance for 'native solidity support'. But now the ERC is expected to provide the proof of stability and completeness, even if made with existing tools and not at the best performance and efficiency.

Does anyone knows a better plan?

**Comment by 3esmit** [comment]
I think would be good for Solidity adopt a signature type, because we have a lot of fragmentation on how signature are dealt with.  

By introducing a signature native type, Solidity won't loose flexibility, because all what is currently being done would be still possible. 
However, this "Signature" type would unify the developers into this solution, as it would support all that is needed for Ethereum Signed Messages, and that are complicated to develop as library, such as nested lookup into the data, as GnosisSafe implemented.

I think is important to repeat that what GnosisSafe did with the `bytes signature` is implemented their own type "Signature", so the suggestion here is to bring something similar of that into Solidity itself. 

Other option would be to support another dynamic type we could use nested lookups in a compact format, I am not updated on ABIv2 Encoder, and that something for this pragma. 

I am looking forward the use of a Library and Struct for Signature aswell @ethernian , so we could use it with ABIv2 Encoder and have what we are asking here. I tried that based on gnosis safe, but no success. Maybe you can try it?

**Comment by 3esmit** [comment]
@ethernian This is where I stopped, this is far from ideal design, but I am trying to abstract things in solidity capabilities...  Also, I am experimenting with differnt things, like using Signature datatype in EIP1271, but maybe you have a better idea... 

I will keep looking around this issue but enough is enough, for now :)...

```solidity
pragma solidity >=0.5.0 <0.7.0;
pragma experimental ABIEncoderV2;

contract EIP1271 {
    bytes4 constant internal EIP1271_MAGIC_VALUE = 0x20c13b0b;
    function isValidSignature(
        bytes memory _data,
        SignatureLib.Signature[] memory _signature)
        public
        view
        returns (bytes4);
}



contract SignatureLib {
    bytes4 constant internal EIP1271_MAGIC_VALUE = 0x20c13b0b;
    enum SigType { EIP1271, Canonical, Compact, EIP2098 }

    struct Signature {
        SigType sigType;
        bytes data;
    }

    struct SigEIP1271 {
        EIP1271 signer;
        Signature[] signatures;
    }

    struct SigCanonical {
        bytes32 r;
        bytes32 s;
        uint8 v;
    }

    struct SigCompact {
        bytes data;
    }

    struct SigEIP2098 {
        bytes32 r;
        bytes32 vs;
    }

    function newSigCompact(bytes memory data) internal pure returns (SigCompact memory) {
        require(data.length == 65);
        return SigCompact(data);
    }

    function newSigEIP1271(bytes memory data) internal pure returns (SigEIP1271 memory) {
        //TODO: conversion
    }
    function newSigCanonical(bytes memory data) internal pure returns (SigCanonical memory) {
        bytes32 r;
        bytes32 s;
        uint8 v;
        assembly {
            r := mload(add(data, 0x20))
            s := mload(add(data, 0x40))
            v := mload(add(data, 0x60))
        }
        return SigCanonical(r,s,v);
    }

    function newSigEIP2098(bytes memory data) internal pure returns (SigEIP2098 memory) {
        require(data.length == 64);
        bytes32 r;
        bytes32 vs;
        assembly {
            r := mload(add(data, 0x20))
            vs := mload(add(data, 0x40))
        }
        return SigEIP2098(r,vs);
    }
    

    function recover(bytes memory message, Signature memory signature) internal pure returns (address) {
        if(signature.sigType == SigType.EIP1271){
            return recover(message, newSigEIP1271(signature.data));
        } else if(signature.sigType == SigType.Canonical){
            return recover(message, newSigCanonical(signature.data));
        } else if(signature.sigType == SigType.Compact){
            return recover(message, newSigCompact(signature.data));
        } else if(signature.sigType == SigType.EIP2098){
            return recover(message, newSigEIP2098(signature.data));
        }
    }

    function recover(bytes memory message, SigEIP1271 memory signature) internal pure returns (address) {
        return EIP1271(signature.signer).isValidSignature(message, signature.signatures) == EIP1271_MAGIC_VALUE ? address(signature.signer) : address(0);
    }

    function recover(bytes memory message, SigEIP2098 memory signature) internal pure returns (address) {
        bytes32 s = signature.vs & 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
        uint8 v = 27 + uint8(uint256(signature.vs) >> 255);
        return ecrecover(keccak256(message), v, signature.r, s);
    }

    function recover(bytes memory message, SigCompact memory signature) internal pure returns (address) {
        if (signature.data.length != 65) {
            return (address(0));
        }

        // Divide the signature in r, s and v variables
        bytes32 r;
        bytes32 s;
        uint8 v;

        // solhint-disable-next-line no-inline-assembly
        assembly {
            r := mload(add(signature, 0x20))
            s := mload(add(signature, 0x40))
            v := byte(0, mload(add(signature, 0x60)))
        }

        if (uint256(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            return address(0);
        }

        if (v != 27 && v != 28) {
            return address(0);
        }

        // If the signature is valid (and not malleable), return the signer address
        return ecrecover(keccak256(message), v, r, s);
    }

    function recover(bytes memory message, SigCanonical memory signature) internal pure returns (address) {
        if (uint256(signature.s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            return address(0);
        }
        if (signature.v != 27 && signature.v != 28) {
            return address(0);
        }
        return ecrecover(keccak256(message), signature.v, signature.r, signature.s);
    }


}

contract MessageLib {
    enum MsgType { EIP191 }
    struct Message {
        bytes data;
        MsgType msgType;
    }

    function getMessageHash(Message memory message) internal view returns (address) {
        return keccak256(message.data);
    }

}
```

**Comment by chriseth** [comment]
Solidity does not want to impose standards by means of adding language features. Also, it should only add features if it cannot be solved with libraries and inline assembly or if that is really cumbersome and error-prone.

Can you solve this with a library?

**Comment by 3esmit** [comment]
@chriseth It hard to solve that, we basically need to create a custom ABI decoder inside the contract for this types of signature.  

We need to do that in the contract level because Solidity don't have it natively. This issue is a suggestion/feature request for having a Signature datatype which, 1. have a dynamic type; 2. can be nested indef....

**Comment by chriseth** [comment]
Can you please explain again why a struct with `bytes` and `abi.decode` would not work?

**Comment by 3esmit** [comment]
> Can you please explain again why a struct with `bytes` and `abi.decode` would not work?

It can't deal with dynamic type.. So I can have decode into a fixed set, but not into a dynamic set.
We need a 


For example, see the code snipped I shared above, to be able to achieve something similar to a dynamic type, this is the best I managed to do in Solidity:
```solidity
    function recover(bytes memory message, Signature memory signature) internal pure returns (address) {
        if(signature.sigType == SigType.EIP1271){
            return recover(message, newSigEIP1271(signature.data));
        } else if(signature.sigType == SigType.Canonical){
            return recover(message, newSigCanonical(signature.data));
        } else if(signature.sigType == SigType.Compact){
            return recover(message, newSigCompact(signature.data));
        } else if(signature.sigType == SigType.EIP2098){
            return recover(message, newSigEIP2098(signature.data));
        }
    }
``` 

where each of sub function would have its own way of initializing. This is a load of work for something that should be a standard, so any wallet can sign to any contract, and any contract that uses this can accept singatures of any other contract.

If this all is left to the developers to decide, we are going to have a bad time on interoperability. 
**I agree with you that Solidity team should not enforce standards**, but maybe we can have at least a suggestion or better tooling for solving this problem? 
Maybe you see an easy fix to this, so perhaps you could give us a tip on how to solve this problem of Multiple Types of Signature (Signatures, Contract Signatures, types of escaping message, etc) and Interoperability. 

Signatures: Can only be from one externally owned account, can have different formats.
Contract Signature: Is composed of multiple Signatures, each signature can be in its own format or be another contract signature with many other signatures.

**Comment by chriseth** [comment]
In my opinion, the community should agree on a standard. I'm neither in favour of enforcing a standard through the compiler nor with hiding complexity inside the compiler.

**Comment by 3esmit** [comment]
I think your points are reasonable, and maybe this is a documentation issue then? 

Where documentation says about ecrecover and signatures in general, it should perhaps mention about ERC-1271 (contract signatures) and how the signatures are being handled (compact representations, canonical format, etc) by web3 developers;

The documentation would not be forcing an standard. but would point out that contracts can't ecrecover, but there is EIP1271 for that, and that signatures can be represented in canonical format (bytes32 r, bytes32  s,  uint8 v) or in a compact format (bytes32, bytes32, byte v), or in EIP2098 compact format (bytes32, bytes32), and link to a forum.

**Comment by chriseth** [comment]
That sounds like a good idea. I think we should also link implementations of that, e.g. the Zeppelin one.
