### ISSUE TITLE
Require abstract for contracts with internal constructors

### ISSUE THREAD

**Issue by nventuro** [ethereum/solidity#8162]
From the [`abstract` documentation](https://solidity.readthedocs.io/en/latest/contracts.html#abstract-contracts), it seems like what the keyword does is mark the contract as non-deployable (i.e. it needs to be inherited from). Because contracts missing function implementations are always non-deployable, they require `abstract`.

If this is the case, shouldn't `abstract` be required also for contracts with `constructor() internal`?

**Comment by chriseth** [comment]
@nventuro a simplification would be to drop the visibility feature for constructors altogether and make contracts `abstract` instead if they are not meant to be deployed without being derived from. Would that work for you?

**Comment by nventuro** [comment]
Yes, that's a great point! I think that's the way to go.

**Comment by chriseth** [comment]
Replaced by https://github.com/ethereum/solidity/issues/8992
