### ISSUE TITLE
Problem with create2 & linked library

### ISSUE THREAD

**Issue by Rafagalanlopez** [ethereum/solidity#8170]
## Description
There seems to be a bug with the **create2** operation: whenever I try to deploy any contract with **linked libraries**, the EVM reverts the operation.
I've double checked that the bytecode I'm deploying is correct; I just took it from the contract's bytecode deployed on rinkeby through truffle previously linking the library to the Smartcontract like so:
``` Javascript
 deployer.deploy(Migrations)
 deployer.deploy(Library)
 deployer.link(Library, Contract)
 deployer.deploy(Contract)
```
( https://rinkeby.etherscan.io/address/0xae5dd2a633e690f3c739352a4aba992cca96f55c#code )

## Environment

- Compiler version: ^0.5.0;
- Target EVM version (as per compiler settings): Istanbul
- Framework/IDE: Remix / Truffle
- EVM execution environment / backend / blockchain client: Rinkeby/Ganache (istanbul), JavaScript EVM (Remix)
- Operating system: Ubuntu

## Steps to Reproduce

Here is an example of one of the contracts & its respective library that I've trying to deploy via create2:

 * Library:
```solidity
pragma solidity ^0.5.0;

library Library {
   struct Data {
       bool boolean;
   }
   
   function set(Data storage self, bool newBoolean) public {
       self.boolean = newBoolean;
   }
}
```
* Contract using the above library:
```solidity
pragma solidity ^0.5.0;

import "./Library.sol";

contract Contract {
   using Library for Library.Data;
   
   Library.Data private Data;
   
   function set(bool newBoolean) public {
       Data.set(newBoolean);
   }
}
```
* Factory contract (Where create2 lives):
```solidity
 pragma solidity ^0.5.0;

contract Factory {
  function deploy(bytes memory code, uint256 salt) public {
    address addr;
    assembly {
      addr := create2(0, add(code, 0x20), mload(code), salt)
      if iszero(extcodesize(addr)) {
        revert(0, "Problem deploying contract")
      }
    }
  }
```
A transaction I made:
https://rinkeby.etherscan.io/tx/0x244e0abcf449801f459637c1cf25e58b2f3f31dfa6daa0848c433072bea3d7ac
As you can see, the failure is a gas overflow but through debugging I found that the **address generated is always 0x0000...** ("addr" variable in the Factory contract), no matter the salt parameter passed on

Here is the deployedBytecode generated by truffle:

0x6080604052348015600f57600080fd5b506004361060285760003560e01c80635f76f6ab14602d575b600080fd5b605860048036036020811015604157600080fd5b81019080803515159060200190929190505050605a565b005b600073__Library_______________________________63a3bfc0db9091836040518363ffffffff1660e01b815260040180838152602001821515151581526020019250505060006040518083038186803b15801560b757600080fd5b505af415801560ca573d6000803e3d6000fd5b505050505056fea265627a7a72315820a5702441820ee9f7ff82b068d1d7979a194d03ed1ab2b21816c114f919ea2d5064736f6c634300050c0032

And once "\__Library_______________________________" is replaced with the actual address of the libary looks like this:

0x6080604052348015600f57600080fd5b506004361060285760003560e01c80635f76f6ab14602d575b600080fd5b605860048036036020811015604157600080fd5b81019080803515159060200190929190505050605a565b005b6000732fbff93bf6d1796957361d72eca36ef6527d4b6363a3bfc0db9091836040518363ffffffff1660e01b815260040180838152602001821515151581526020019250505060006040518083038186803b15801560b757600080fd5b505af415801560ca573d6000803e3d6000fd5b505050505056fea265627a7a72315820a5702441820ee9f7ff82b068d1d7979a194d03ed1ab2b21816c114f919ea2d5064736f6c634300050c0032

**Comment by chriseth** [comment]
Can you explain which value you used for `code` and how you obtained it?

**Comment by chriseth** [comment]
Hm, the etherscan debugger seems to be a bit broken, but it looks like you are not supplying the creation code but the deployed code instead - might that be the problem?

**Comment by Rafagalanlopez** [comment]
Thanks for the quick response!

Yes, it is the deployedBytecode the one I'm using. As far as I know, since the constructor is empty, both bytecodes should be the shame right?. Besides, if the bytecode passed on to the "deploy" function shouln't be the deployedBytecode, how could I deploy a contract with a non-empty contructor?

I updated the issue description to include how the bytecodes(deployed) look like before and after the replacement of the libary's address

Thanks in advance! 😄

**Comment by chriseth** [comment]
The compiler adds more code to the constructor than is visible in the source file. Most essentially, the constructor has to return the deployed bytecode.

Thanks for your patience, my response was anything than quick ;)

**Comment by chriseth** [comment]
I'm very certain now, that you were using the wrong bytecode. Please reopen if you still think this might be a compiler bug.
