### ISSUE TITLE
Legacy Assembly refers to comments in the code

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/solidity#8171]
## Description

On compiling this contract on remix:
```
/**
 * Foobar
 */
 
pragma solidity 0.6.1;

contract C1 {
    function f2() pure external returns (bool) {
        require(false);
        return true;
    }    

    function f1() view external {
        C1(this).f2();
    }
}
```
in compilation details, assembly is pointing comments:

```
.code
  PUSH 80			contract C1 {\n    function f2...
  PUSH 40			contract C1 {\n    function f2...
  MSTORE 			contract C1 {\n    function f2...
  CALLVALUE 			contract C1 {\n    function f2...
  DUP1 			oobar\n */
  ISZERO 			* 
  PUSH [tag] 1			* 
  JUMPI 			* 
  PUSH 0			i
  DUP1 			s
  REVERT 			pragma solid
tag 1			* 
  JUMPDEST 			* 
  POP 			contract C1 {\n    function f2...
```

## Environment

- Compiler version: 0.4.24 & 0.6.1
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix

I think this needs a look.

**Comment by chriseth** [comment]
Legacy assembly is phased out, but this looks like source locations are wrong in general.

**Comment by Aniket-Engg** [comment]
Just to add, This field https://github.com/ethereum/solc-js/blob/master/translate.js#L115 is used here https://github.com/ethereum/remix-ide/blob/master/src/app/tabs/compileTab/contractParser.js#L46 to display that assembly

**Comment by chriseth** [comment]
It turns out that the legacy assembly output does not support multi-file sources.

**Comment by chriseth** [comment]
@Aniket-Engg it turns out that the source reference only has a `start` and `end` field, but no `sourceIndex`. We are fixing this by adding a field `source` - would that work for you?

**Comment by Aniket-Engg** [comment]
@chriseth  cool thanks. I think as per this https://github.com/ethereum/solidity/pull/8337/files#diff-bed45194acea445df8a87c7fefbe0e8cR250 , `source` field provides source index, is it?

**Comment by chriseth** [comment]
Yes, it does.

**Comment by axic** [comment]
> Legacy assembly is phased out, but this looks like source locations are wrong in general.

@chriseth do we want to drop it with 0.7?

**Comment by chriseth** [comment]
I fear we do not yet have a real alternative.

**Comment by axic** [comment]
What is it used for? We also have the pretty printed text, which handles sources properly. Only the JSON assembly monstrosity is problematic.

**Comment by chriseth** [comment]
remix
