### ISSUE TITLE
address(this).balance does not work starting in Solidity 0.5.14

### ISSUE THREAD

**Issue by Droopy78** [ethereum/solidity#8180]
## Description

Starting in Solidity 0.5.14, address(this).balance results in "invalid opcode".

See code below. Can quickly test this in Remix:

Call getContractBalance() --> **does not work**
Call getContractBalance2() --> **works** 

```solidity
pragma solidity ^0.5.14;

contract TestBalance {
    // fallback function
    function () external payable {}
    
    function getContractBalance() public view returns (uint256) {
        return address(this).balance;
    }
    
    function getContractBalance2() public view returns (uint256) {
        return address(uint160(address(this))).balance;
    }
}
```
In Solidity version 0.5.13, both functions above work correctly.

**Comment by axic** [comment]
You need to select Istanbul as EVM version on Remix (for execution). Or change the compilation target on Solidity for something before Istanbul.

**Comment by Droopy78** [comment]
Thank you! Yes this is the reason. I am still using the old Remix interface, which doesn't seem to give the option to switch EVM versions. It's unfortunate it doesn't at least default to the correct EVM version to match the compiled version.

I switched to the new Remix interface and it gives you the option to either use the default EVM version or choose the EVM version. Choosing either "Default" or "Constantinople" works.
