### ISSUE TITLE
Usage of libraries is inherited

### ISSUE THREAD

**Issue by nventuro** [ethereum/solidity#8188]
Today I stumbled with a strange scenario that I did not expect to work, yet it does: contracts that inherit from parents with a `using` statement can also use the same library in that manner.

Consider the following contracts:
```
pragma solidity ^0.5.0;

library Lib {
    function foo(uint256 value) internal returns (uint256) {
        return value + 42;
    }
}

contract A {
    using Lib for uint256;
}

contract B is A {
    function bar(uint256 value) public returns (uint256) {
        return value.foo(); // Usage of Lib
    }
}
```

Note that `B` could even exist on a separate source file, which would make the code all that more cryptic - it's probably not very hard to introduce a backdoor using this mechanism.

Is this behavior intended, or a bug?

**Comment by nventuro** [comment]
From the [documentation](https://solidity.readthedocs.io/en/v0.6.1/contracts.html#using-for):

>The `using A for B;` directive is active only within the current contract, including within all of its functions, and has no effect outside of the contract in which it is used. The directive may only be used inside a contract, not inside any of its functions.

**Comment by chriseth** [comment]
The code explicitly traverses all contracts in the inheritance hierarchy, so it is probably not a bug. "within the current contract" does not explicitly rule out derived contracts for me, although this should certainly be clarified in the documentation.

**Comment by nventuro** [comment]
As a regular user, I was _very_ surprised by that behavior. I'd suggest emitting a warning on such cases, and disallowing it entirely on 0.7.x.

**Comment by chriseth** [comment]
The community feedback form showed a preference for removing inheritance for "using for", so we could include that in the 0.7.0 release.

**Comment by chriseth** [comment]
Accepted in design call.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/9284
