### ISSUE TITLE
JSON AST test extraction broken on Linux

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#8190]
## Description

This was introduced by https://github.com/ethereum/solidity/pull/8187.

On some Linux systems the source extraction, used during JSON AST import and export tests, is broken:
```
ValueError: binary mode doesn't take an encoding argument
.Traceback (most recent call last):
  File "/root/project/scripts/splitSources.py", line 51, in <module>
    lines = open(filePath, mode='rb', encoding='utf8').read().splitlines()
```
Weirdly enough, this does not let the command line test fail: [Circle workflow output](https://circleci.com/gh/ethereum/solidity/247688?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

## Environment

- Compiler version: develop
- Target EVM version (as per compiler settings): -
- Framework/IDE (e.g. Truffle or Remix): -
- EVM execution environment / backend / blockchain client: -
- Operating system: Linux (Ubuntu, Fedora with python 3.7.5)

## Steps to Reproduce

Run `./test/cmdlineTests.sh`

**Comment by cameel** [comment]
> Weirdly enough, this does not let the command line test fail

That's because the Python script is executed by a Bash script and in Bash there's no exception mechanism so an error from a command does not automatically interrupt it. You could change script's shebang to `#!/usr/bin/env bash -e` which would make it end automatically when anything returns non-zero but it won't work properly here because the Python script uses the return value to indicate whether it found multiple source files (0) or not (1).

**Comment by erak** [comment]
@cameel Ah, true. Thanks for the clarification! I'll try to fix the root cause by removing the binary option from the `open()` call.

**Comment by cameel** [comment]
I think it will work just fine no matter whether you decide to remove the binary mode or the `encoding` parameter. I just posted a comment on the chat. Maybe a comment on this issue is a better place for it:

> I think it will work fine unless there are any non-utf-8 files in the repo (I doubt it and you'll notice it when it fails) and as long as no code specifically needs to work on individual bytes rather than whole unicode characters (which may be encoded using multiple bytes). I think it's unlikely since that would be very low level and these scripts seem to do only very light text processing.
>
> But just removing the `encoding` parameter in this particular call seems to work too. Looks like any functions it passes the file content to can deal with both `bytes` and `str` just fine. That makes sense since in Python 2 this code was working with `str` which is the equivalent to what is now `bytes` (the equivalent of the current `str` in the old Python was called `unicode`). So it used to process it byte by byte rather than by whole unicode characters and it didn't matter.
