### ISSUE TITLE
readthedocs build is failing

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8200]
https://readthedocs.org/projects/solidity/builds/10336300/

**Comment by Marenz** [comment]
Related: https://stackoverflow.com/questions/59846065/read-the-docs-build-fails-with-cannot-import-name-packagefinder-from-pip-in

**Comment by erak** [comment]
I followed the guide proposed by @Marenz and it fixed the builds: https://readthedocs.org/projects/solidity/builds/10341484. Closing this now. Please feel free to re-open in case of any new failures.

**Comment by erak** [comment]
Re-opening because it only works when manually re-triggering builds. We need to wait for the updated version of readthedocs: https://github.com/readthedocs/readthedocs.org/issues/6554.

**Comment by chriseth** [comment]
This is working.
