### ISSUE TITLE
readthedocs has a nonexistent future version as the "latest"

### ISSUE THREAD

**Issue by pthariensflame** [ethereum/solidity#8202]
I go to https://solidity.readthedocs.io/en/v0.6.2/index.html and see:
<img width="1124" alt="Screen Shot 2020-01-27 at 1 40 25 PM" src="https://user-images.githubusercontent.com/1847577/73216703-56819500-410b-11ea-95bf-d2bfc58a3d56.png">

**Comment by erak** [comment]
@pthariensflame Thanks for your report. It is a known issue (see https://github.com/ethereum/solidity/issues/8200) and we're working on a fix!

**Comment by erak** [comment]
@pthariensflame Just realized that both issues are somewhat independent from each other. I've fixed the issue you've reported and `latest` now points to `develop` again. But that's probably an old build because of the other issue mentioned.
