### ISSUE TITLE
Bytecode comparison tests are failing.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8209]
It seems that the windows run uses the correct commit hash for the compiler version in the metadata: `0.6.3-nightly.2020.1.28+commit.f6759ce2"`, while all other builds (those on travis) use `"0.6.3-nightly.2020.1.28+commit.6e31c86a"` for the same run.

**Comment by chriseth** [comment]
The problem seems to be that on pull requests, travis runs everything on a potential merge commit - which only exists for travis. Runs on the develop branch result in the same for both windows and travis. Maybe a solution would be to only push to the bytecode comparison directory if we are not running on a pull request, but directly on develop.

**Comment by Marenz** [comment]
Could this maybe solve the problem? https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda

**Comment by Marenz** [comment]
Or maybe another setting in travis.. from what I've read this merge commit building seems to be configurable

**Comment by Marenz** [comment]
If you give me access to the travis part I can investigate a bit

**Comment by chriseth** [comment]
Can be closed if https://travis-ci.org/ethereum/solidity/jobs/645537086?utm_medium=notification&utm_source=github_status does push to the bytecode repository.

**Comment by chriseth** [comment]
It did!
