### ISSUE TITLE
Experimental ABIEncoder fails to pass fixed-size calldata array to internal function

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#8210]
The basic scenario seems to require that an external function pass its fixed-size calldata to an internal function. One workaround is to use a public function instead of an external function.

Originally encountered on 0.5.13. Also happens on 0.5.16 and 0.6.2.

Minimum repro:
```
pragma solidity ^0.5.13;

pragma experimental ABIEncoderV2;

contract Parent {
    function internalFn(bytes[2] memory signatures) internal returns (bytes memory) {
    }
    function externalFn(bytes[2] calldata signatures) external returns (bytes memory) {
        return internalFn(signatures);
    }
}
```

The error is `InternalCompilerError: Variable size and position mismatch.`

This issue seems to be similar to https://github.com/ethereum/solidity/issues/7929.

Curiously, if you instead supply
```
pragma solidity ^0.6.2;

pragma experimental ABIEncoderV2;

contract Parent {
    function internalFn(bytes[2] memory signatures) internal {
    }
    function externalFn(bytes[2] calldata signatures) external {
        internalFn(signatures);
    }
}
```
then the error becomes
```
InternalCompilerError: I sense a disturbance in the stack: 1 vs 2
```

**Comment by wjmelements** [comment]
Also, if the contract has any unimplemented methods, compilation will succeed.

**Comment by chriseth** [comment]
I think we already have an issue about that.

**Comment by chriseth** [comment]
Ah sorry, you already mentioned it!

**Comment by thegostep** [comment]
Also seeing this error with dynamic sized memory arrays.
