### ISSUE TITLE
[Yul Optimizer] Make use of boolean types in the conditional simplifier

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8243]
If the dialect has a bool type, convert `if c { ... }` to `if c { c := true ... }` in the conditional simplifier and similar for `for` loops and maybe other things.

**Comment by chriseth** [comment]
This might be obsolete when we use z3 in the optimizer.

**Comment by hrkrshnn** [comment]
@chriseth Is this still worth implementing?

**Comment by chriseth** [comment]
Currently, this is not too helpful anyway, because we do not use bools in our code generator. I'm moving it to the icebox.
