### ISSUE TITLE
Write codegen tests that trigger currently unreachable reverts

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#8253]
From https://github.com/ethereum/solidity/pull/8178/, many reverts added to the code are never triggered by our tests. We should try to reach all of them.
They can be found via `// TODO add test` in `codegen/*`.

**Comment by axic** [comment]
There are still plenty of such TODOs:
```
./CompilerUtils.cpp:					// TODO add test
./CompilerUtils.cpp:					// TODO add test
./ABIFunctions.cpp:			// TODO add test
./ABIFunctions.cpp:					// TODO add revert test
./ABIFunctions.cpp:		// TODO add test
./ABIFunctions.cpp:		// TODO add test
./ABIFunctions.cpp:		// TODO add test
./ABIFunctions.cpp:		// TODO add test
./ABIFunctions.cpp:			// TODO add test
./ABIFunctions.cpp:				// TODO add test
./ABIFunctions.cpp:				// TODO add test
```

Not sure if there are tests for them, but we should add them so we can see difference in behaviour for the IR.
