### ISSUE TITLE
Empty functions are not optimized away

### ISSUE THREAD

**Issue by nventuro** [ethereum/solidity#8260]
I'd expect calls to `internal` functions with no body to produce no bytecode, but this doesn't seem to be the case (even when optimizations are enabled).

I compiled the following two contracts on Remix using v0.6.2:
```
pragma solidity ^0.6.0;

contract NoEmpty {
    function foo() public view returns (uint256) {
        return address(this).balance;
    }
}

contract Empty {
    function foo() public view returns (uint256) {
        bar();
        return address(this).balance;
    }
    
    function bar() internal view {
        
    }
}
```

With no optimizations, deploying `NoEmpty` takes 90661 gas, while `Empty` uses 92805 gas. Optimizations reduce the cost of both scenarios, but doesn't make them equal: `NoEmpty` takes 88575 gas, while Empty costs 91465 gas (which doesn't even match the performance unoptimized `Empty`).

I'd expect this to be a straightforward optimization, perhaps even achievable by the peephole optimizer, is there some complexity here I'm not considering?

**Comment by nventuro** [comment]
As a side note, I was a bit surprised `bar` didn't raise any warnings, given that it's a `view` function with no return value.

**Comment by chriseth** [comment]
I think we disabled this functionality when we introduced internal function pointers that can be stored in storage - this is especially complicated with regards to construction-time and runtime functions.

The plan (I know, it might be too far off) is that yul will solve this problem easily. The code currently generated for "Empty" is the following:
```
object "Empty_34" {
    code {
        {
            mstore(64, 128)
            let _1 := datasize("Empty_34_deployed")
            codecopy(0, dataoffset("Empty_34_deployed"), _1)
            return(0, _1)
        }
    }
    object "Empty_34_deployed" {
        code {
            {
                mstore(64, 128)
                if iszero(lt(calldatasize(), 4))
                {
                    let _1 := 0
                    if eq(0xc2985578, shr(224, calldataload(_1)))
                    {
                        if callvalue() { revert(_1, _1) }
                        if slt(add(calldatasize(), not(3)), _1) { revert(_1, _1) }
                        let ret := balance(address())
                        mstore(64, 128)
                        mstore(128, ret)
                        return(128, 32)
                    }
                }
                revert(0, 0)
            }
        }
    }
}
```

**Comment by nventuro** [comment]
I'm not well versed in Yul, but that snippet seems to show that the call to `bar` is removed entirely at the Yul stage. Is that correct?

Is there a rough estimate for when we can expect Yul being used as an IR?

**Comment by chriseth** [comment]
Yes, the code of `bar` is removed by the Yul optimizer. Our current estimate is "towards the end of the year".

**Comment by chriseth** [comment]
Since we have a good way forward here, I would close this issue. Please reopen if you think otherwise.
