### ISSUE TITLE
Add mechanism for static/const/immutable selector.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#8262]
## Abstract
There should be a way to reference a function selector from an interface or contract without having to construct it by hand (error prone/complicated) and such that it can be used in constants.

## Specification
Simplest implementation (from a usability standpoint) would be to allow someone to reference an interface function definition with `.selector` in order to get a constant for the byte4.  Caveat here is that overloads become problematic.

Another option would be to provide a syntax for getting the selector from a string, though this is a bit more error prone I suspect.
```
interface Banana {
    function transfer(address,uint256) external returns(bool);
}

contract Apple {
    // simplest UX
    bytes4 constant bananaTransfer1 = Banana.transfer.selector;

    // a bit more complicated to write, but deals with overloads
    bytes4 constant bananaTransfer2 = Banana.transfer(address,uint256).selector;

    // if transfer signature changes on Banana, this will be incorrect with no compiler error
    bytes4 constant bananaTransfer3 = selector(transfer(address,uint256));
}
```

## Backwards Compatibility
The last option would introduce a new keyword that may be problematic.

**Comment by chriseth** [comment]
I am pretty sure that at least the first solution (not supporting overloads) should already be possible, is just missing an implementation.

@ekpyron this should work through our new `FunctionType::Kind::Declaration` model, right?

**Comment by ekpyron** [comment]
The first one is already implemented, yes - but I haven't marked it for use in compile-time constants, that's missing - I'll quickly look into that!

**Comment by MicahZoltu** [comment]
```solidity
interface Banana {
    function transfer(address,uint256) external returns(bool);
}
contract Apple {
    bytes4 bananaTransfer = Banana.transfer.selector;
}
```
```
TypeError: Member "transfer" not found or not visible after argument-dependent lookup in type(contract Banana).
    bytes4 bananaTransfer = Banana.transfer.selector;
                            ^-------------^
```
It doesn't work for me in 0.6.2 even when not constant.

**Comment by ekpyron** [comment]
Hm... curious... are you sure? I have:
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.6.2+commit.bacdbe57.Linux.g++
$ cat test.sol
pragma solidity =0.6.2;
interface Banana {
    function transfer(address,uint256) external returns(bool);
}
contract Apple {
    bytes4 bananaTransfer = Banana.transfer.selector;
}
$ solc test.sol --bin

======= test.sol:Apple =======
Binary:
608060405263a9059cbb60e01b6000806101000a81548163ffffffff021916908360e01c0217905550348015603357600080fd5b50603f8060416000396000f3fe6080604052600080fdfea264697066735822122042d2fa55eea76cf265988d5b84b19c104746380ba35da6cb391a1d3bbd74510064736f6c63430006020033

======= test.sol:Banana =======
Binary:
```
It was introduced with 0.6.2 itself actually...

**Comment by MicahZoltu** [comment]
Ah, no I am not confident.  I was testing using Remix, but when I just went back to test again I noticed that Remix is ignoring my requests to change compiler version.  Once I worked around that, I was able to verify that you are correct and it is present in 0.6.2.  🎉 

That just leaves "overloads" and "works as a compile-time constant" as part of this feature request.  😄
