### ISSUE TITLE
Incorrect use of built-in 0x4 Identity Function

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#827]
According to this comment: https://github.com/ethcore/parity/issues/1819#issuecomment-237303440 solidity sometimes make use of the 0x4 identity function. But does so incorrectly providing too little gas. Is it intended or not? Does it harms the execution in any way?
Note: that failed internal tx's to 0x4 will soon be removed from etherscan.io.

**Comment by axic** [comment]
It seems that the YP defines the gas requirements for the identity precompile as `15` + `3` every 32 bytes of data.

While Solidity uses `3` as a base fee + `15` as a word fee. (https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/CompilerUtils.cpp)

**Comment by axic** [comment]
The actual bug seems to be trying to copy 0 bytes, because in that case the total gas stipend is 3 (15 correctly) and from 1+ bytes on Solidity over-stipends (15_i vs 3_i).

Another bug I see here is that I think identity memcpy shouldn't be called for length 0.

**Comment by axic** [comment]
Also fixed it in #828.

**Comment by chriseth** [comment]
Furthermore, I think the identity function is more expensive than copying manually - we have a story for that.
