### ISSUE TITLE
Refactoring of ReferenceResolver and/or "early Type checker" (e.g. for detecting recursive structs).

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8291]
Related to https://github.com/ethereum/solidity/issues/7779.

We have properties of types that depend on analysis steps, e.g. ``StructType::interfaceType()`` and ``StructType::recursive()`` and therefore also ``canLiveOutsideStorage()`` and ``calldataEncodedSize()``, etc.

We noticed in https://github.com/ethereum/solidity/issues/7779 that this can cause problems, if these members are called too early.

Two possible solutions:
 - Try to determine these properties directly at the time the type is created (passing them in as constructor arguments). This may be feasible by resolving e.g. nested struct members early in ``ReferencesResolver::endVisit(UserDefinedTypeName)``, but it might also not be feasible, since it would need to visit "out of order" in that step (e.g. later struct definitions would need to be visited before their natural visit in the AST visitor, which may or may not be a problem).
 - Add another pass between ``ReferencesResolver`` and ``TypeChecker`` to fill in these information (while asserting in the type checker that the dependent members are not used before this pass is run).

**Comment by chriseth** [comment]
I think it makes sense to inject another stage between the reference resolver and the contract level checker that walks the full ast, but only checks properties of variables and does not descend into expressions.

It basically fills `annotation().type` for declarations, but not for expressions and checks that all types are well-formed. This allows us to terminate before running the contract level checker which would call `interfaceType()` on functions with illegal types. This should also make it possible to show better error messages.

**Comment by chriseth** [comment]
@mijovic started working on this.

**Comment by chriseth** [comment]
@ekpyron This was completed in https://github.com/ethereum/solidity/pull/8665 wasn't it?
