### ISSUE TITLE
[PR] Article about the new inheritance system

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8299]
Part of #8057 

Problems in 0.5.0: All function virtual, not obivous if functions are overridden later in inheritance. Especially due to big inheritance graphs, this can easily happen.

inheritance system itself did not change: still have C3 linearization and super works as it did before.

We added restrictions to force users to be more explicit and reduce the bugs introduced by typos: Functions are not virtual anymore by default. This means a call to a non-virtual function will always execute that function regardless of any other contract in the inheritance hierarchy.

You can only override functions if they are marked virtual. Furthermore, any overriding function must be marked override. If that again should be overridable, it has to be marked virtual in addition to that.

Biggest advantage of the new rules: Multiple inheritance: The same function can be inherited from multiple base classes. In this case, it has to be overridden and the bases have to be listed in the override specifier. Very important: The order here does not matter - specifically it does not change the behaviour of super - this is dictated by the C3 linearization of the inheritance graph which is determined by the order in the `contract C is A, B { ... }`.

Plus: Interfaces can inherit.

**Comment by franzihei** [comment]
Let's try to consolidate all blog related issues in the blog repo. As part of this effort, I'm closing this here and moving the content to https://github.com/ethereum/solidity-blog/issues/38
