### ISSUE TITLE
Forming a byte array inline

### ISSUE THREAD

**Issue by stevenroose** [ethereum/solidity#830]
I'm trying to form a `bytes` inline, but it seems to be impossible.

I tried the following ways:
- `bytes memory data = [1 2 3 4 5]`, which raises `Error: Type uint8[5] memory is not implicitly convertible to expected type bytes storage pointer.` 
- `bytes memory data = [byte(1) 2 3 4 5]`, which raises `Error: Unable to deduce common type for array elements.`
- `bytes memory data = [byte(1) byte(2) byte(3) byte(4) byte(5)]`, which raises `Error: Type bytes1[5] memory is not implicitly convertible to expected type bytes memory.`

**Comment by axic** [comment]
The best current way is: `bytes memory data = "\x01\x02\x03";`

There will be a new format in the future (see #479).

**Comment by stevenroose** [comment]
Closing in favor of #479
