### ISSUE TITLE
[PR] Article about fallback / receive split

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8300]
Part of #8057

**Comment by chriseth** [comment]
Draft: https://github.com/ethereum/solidity/issues/8057#issuecomment-572191897 / https://github.com/ethereum/solidity-blog/pull/1

The article should end up in the ethereum blog, not in solidity-blog. Here is the first article in the series: https://blog.ethereum.org/2020/01/29/solidity-0.6-try-catch/

**Comment by elenadimitrova** [comment]
Done. Will be up on the blog today. [todo add a link when up]

**Comment by chriseth** [comment]
The article will be delayed waiting for a decision from the EF about whether the article series is suitable for the blog or not.

**Comment by chriseth** [comment]
It seems we should use our own. Will move to github.com/ethereum/solidity-blog
