### ISSUE TITLE
[Yul] Allow tuple assignments.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8303]
We needed a lot of infrastructure to nicely support tuples (see https://github.com/ethereum/solidity/pull/8257) that could have been avoided by allowing tuple assignments in Yul.

It could be a simple optimizer pass to split them into separate assignments.

**Comment by chriseth** [comment]
This needs changes in the grammar, the documentation, optimizer and AsmAnalysis. I don't think it is a breaking change. The document needs to define the order of execution and we need tests with side-effects in the components.

**Comment by chriseth** [comment]
To clarify: This is a change to both assignment and variable declaration. It is not a change to `Expression` - am I right?

**Comment by chriseth** [comment]
The AST would be a vector of expressions. Each expression has to evaluate to exactly one value and the number of expressions has to match the number of variables on the left-hand-side. As an exception, if the value is a single function call, it can evaluate to multiple values but their number have to match the number of variables on the left-hand-side.

**Comment by chriseth** [comment]
Re-introducing tuple assignments in the optimizer is probably difficult.

The splitting step has to introduce temporaries when the right-hand-side occurs on the left-hand-side.

**Comment by chriseth** [comment]
One big problem I see is that

`a, b, c := d, e, f, g h, i,j := x, y`

is a bit difficult to parse :)

How would the assignment translate to EVM bytecode? Evaluate the value from right to left, put everything on the stack and then perform the assignment?

**Comment by chriseth** [comment]
Also, can we currently leave out items on the left-hand-side? Then it might even get ambiguous...

**Comment by chriseth** [comment]
Another difficulty is that we usually evaluate function arguments from right to left - would we do the same here, too? If yes, then the values are in reverse with regards to the location of the variables on the stack.

**Comment by axic** [comment]
@ekpyron can you clarify what exactly did you mean here?

**Comment by ekpyron** [comment]
What do you want clarified? The issue is just about allowing general tuple assignments in yul like ``x, y := 1, 2``, so dropping the requirement on the right-hand side to be a function call for these. That would have made major parts of Yul-IR codegen much simpler. But now we worked around most of these issues in IR codegen - and it may be non-trivial to properly specify the semantics of general tuple assignments in Yul (e.g. order of evaluation, etc.)... that's why this is on ice at the moment.

**Comment by axic** [comment]
> What do you want clarified? 

What is exactly needed. We already have partial tuple assignment support, as you say assigning to tuples returned from functions.

Is this about arbitrary tuple assignments? Equal number of items on left and right? Any kind of expression on right hand side? Only variable on left hand side? Lots of questions :wink:

**Comment by ekpyron** [comment]
Yes, it is about arbitary tuple assignments.
- LHS and RHS have equal numbers of items.
- If RHS is a tuple (has more than one item), two options: either function calls are prohibited, or function calls must return a single item.  The more restricted version would already help, the more general one would be even better.

Best for Yul-IR would be the generalization to arbitrary tuples of function calls on the right-hand-side (just flattening all items to a single tuple) - but that might be too weird and more restricted versions would already be enough to simplify Yul-IR codegen greatly.

But as I said, by now I put in the ``IRVariable`` stuff in Yul-IR codegen, so as long as that's sufficient and works well, there's no immediate need anymore - even though this means that major parts of Yul-IR codegen don't actually generate Yul, but have some abstraction generate actual yul in the end, but well...

**Comment by axic** [comment]
C++ generating pseudo-Yul via Whisker templates, which generates psuedo-untyped-somedialect-Yul with IRVariables, which generates some other kind of Yul, and after a few more steps, we may get to Yul supposedly readable for audit.

**Comment by ekpyron** [comment]
> C++ generating pseudo-Yul via Whisker templates, which generates psuedo-untyped-somedialect-Yul with IRVariables, which generates some other kind of Yul, and after a few more steps, we may get to Yul supposedly readable for audit.

Exactly :-). That's why I asked for tuple assignments instead first :-D.

**Comment by ekpyron** [comment]
In case it helps: the main issue in Sol->Yul codegen is that we want to associate Solidity expressions with Yul variables and for example on an assignment of a Solidity variable to a Solidity expression, assign the Yul variables corresponding to the Solidity variable to the Yul variables corresponding to the Solidity expression.

But in nearly any context we have to assume that we might need more than one Yul variable for the Solidity variable or expression, so we can almost never really write ``<var> := <expr>`` and just fill in ``<var>`` and ``<expr>``. Instead we always have to split this up, potentially creating temporaries in the process, on a case-per-case-basis. So in order not to clutter IR generation with all that boiler-plate (even more so because it's easy to get wrong), ``IRVariable`` does this automatically.

But as a result, Yul-IR hardly every actually generates such yul assignments directly, but rather hides that away in having ``IRVariable``s assign to each other - which decreases the readability and usability (it's a hassle to correctly insert complex expressions into Whiskers templates this way, etc.).

That being said, it's not entirely clear what amount of tuple support in Yul would be needed, s.t. we can get rid of something like ``IRVariable`` entirely - there's still the issue of type conversions (which ``IRVariable`` attempts to deal with implicitly - although it has been argued whether that was a good or a bad idea) and Solidity has stuff like nested tuples, etc. (so we'd need to flatten) and even stuff like ``(x, (y, z)) = (f(), g());`` (which we should probably actually disallow).

**Comment by axic** [comment]
Side-comment: if tuples are seriously considered, then we should also consider a tuple syntax on LHS and #9617 for function definitions.

**Comment by chriseth** [comment]
I think we found a good solution in the codegen and maybe all the questions raised above show that this does not have a great cost/benefit ratio.
