### ISSUE TITLE
YulUtilFunctions::allocateMemoryArrayFunction does not zero out the memory

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8308]
The function is only used in the Yul IR, so abi decoding is not affected (it would write the array contents out anyway).

We could have two versions, one that zeroes out and one that does not.

**Comment by leonardoalt** [comment]
If we wanna have two versions, what's the use case for one and the other? Should all current behavior be replaced by the new function that always zeroes?

**Comment by leonardoalt** [comment]
Is there any example that triggers this bug?

**Comment by leonardoalt** [comment]
```
contract C {
    function index(uint256 len, uint256 idx) public returns (uint256)
    {
        uint[] memory array = new uint[](len);
        return array[idx];
    }
}
// ====
// compileViaYul: true
// ----
// index(uint256,uint256): 10, 5 -> 0
```
This test passes.

**Comment by leonardoalt** [comment]
Since the free memory pointer only increases, isn't every allocated chuck already zero by default?
