### ISSUE TITLE
Any Problem with Prepending Variable Names with Dollar Sign '$' ?

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#8312]
I find it useful to prepend all my state variable names with a dollar sign '$'.  In my code this immediately tells me which variables are state variables and which are not and helps avoid name clashes.

Is there any technical problem with prepending state variable names with a dollar sign?

Here is an example:
```
uint256 internal $myFirstStateVariable
mapping(bytes4 => address) internal $mySecondStateVariable;  
```

Also I could not find anywhere documentation for valid characters for variable names in solidity. What are the valid characters for variable names?

I am currently using Solidity 0.6.2

**Comment by chriseth** [comment]
Should be perfectly fine!
