### ISSUE TITLE
[Yul Optimizer] For readability purposes, replace function return variables by the literal 0 until they are assigned for the first time.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8317]
Optimized code often uses the fact that function return variables are initialized to zero before they are assigned to for the first time. While this saves a stack slot, the code is not really readable.

We should replace references to function return variables by zero until they are assigned for the first time (take care of branches and for loops).

Another way to fix this would be to remove the mechanism that the optimizer knows that function return values are zero before they are first assigned.

**Comment by ekpyron** [comment]
Hm... saving a stack slot that way is nice, though, isn't it...?

**Comment by chriseth** [comment]
We could say that removing the slot again is another optimizer pass (just like the peephole optimizer for example).

**Comment by ekpyron** [comment]
Would that pass happen before generating the optimized IR output then or only happen during the translation to bytecode? Because in the former case the gain in readability would be restricted to intermediate steps only and I'm wondering if that'd be worth it...

**Comment by chriseth** [comment]
Of course only in the latter case.
