### ISSUE TITLE
Generalized way to sort sets and vectors of AST nodes for guaranteeing deterministic order.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8319]
We have custom sorting logic at least in ``SMTEncoder::mergeVariables``, in ``ControlFlowGraph::VariableOccurrence``, in ``sortByContract`` in ``OverrideChecker`` in ``OverrideProxy::operator<`` in ``OverrideChecker::CompareByID``, in ``ConstStateVarCircularReferenceChecker::findCycle`` and will probably get a new one in https://github.com/ethereum/solidity/pull/8311.

They are not all exactly the same, but it might still be worth thinking about a generalized solution to some or all of them.

**Comment by chriseth** [comment]
We should add an operator that compares by ID and a callable object that takes ast pointers and compares them.

**Comment by cameel** [comment]
> We should add an operator that compares by ID and a callable object that takes ast pointers and compares them.

We have something like that in `ASTForward.h`:  [`ASTCompareByID`](https://github.com/ethereum/solidity/blob/v0.8.12/libsolidity/ast/ASTForward.h#L104-L121).

But I think that part of the task here would be to have the other, custom, comparators extend it rather than just do it from scratch?

**Comment by ekpyron** [comment]
> We have something like that in `ASTForward.h`: [`ASTCompareByID`](https://github.com/ethereum/solidity/blob/v0.8.12/libsolidity/ast/ASTForward.h#L104-L121).

The issue predates the fact that we have this :-). So the main question now is: is this actually used everywhere it can be used?

My guess would be that it isn't and that ``ASTCompareByID`` would also need smart pointer cases, etc., but I haven't checked.

**Comment by cameel** [comment]
`ASTNode` uses it:
https://github.com/ethereum/solidity/blob/466251b5a0d20a4b532e03ca4884000432690507/libsolidity/ast/AST.h#L74

**Comment by ekpyron** [comment]
We at least still have ``OverrideChecker::CompareByID`` and ``CallGraph::CompareWithID``, so it's not completely unified.
