### ISSUE TITLE
[Sol - Yul] Support built-in functions

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8343]
Example (`keccak256` is supported now, but `abi.encode isn't)
```
contract Hash {
    function f() public pure returns(bytes32) {
        return keccak256(abi.encode(1234));
    }
}
```
- [x] Internal, ///< stack-call using plain JUMP
- [x] External, ///< external call using CALL
- [x] DelegateCall, ///< external call using DELEGATECALL, i.e. not exchanging the storage
- [x] BareCall, ///< CALL without function hash
- [x] BareCallCode, ///< CALLCODE without function hash
- [x] BareDelegateCall, ///< DELEGATECALL without function hash
- [x] BareStaticCall, ///< STATICCALL without function hash
- [x] Creation, ///< external call using CREATE
- [x] Send, ///< CALL, but without data and gas
- [x] Transfer, ///< CALL, but without data and throws on error
- [x]  KECCAK256, ///< KECCAK256
- [x] Selfdestruct, ///< SELFDESTRUCT
- [x] Revert, ///< REVERT
- [x] Revert(string)
- [x] ECRecover, ///< CALL to special contract for ecrecover
- [x] SHA256, ///< CALL to special contract for sha256
- [x] RIPEMD160, ///< CALL to special contract for ripemd160
- [x] Log0,
- [x] Log1,
- [x] Log2,
- [x] Log3,
- [x] Log4,
- [x]  Event, ///< syntactic sugar for LOG*
- [ ] SetGas, ///< modify the default gas value for the function call
- [ ] SetValue, ///< modify the default value transfer for the function call
- [x] BlockHash, ///< BLOCKHASH
- [x] AddMod, ///< ADDMOD
- [x] MulMod, ///< MULMOD
- [x]  ArrayPush, ///< .push() to a dynamically sized array in storage
- [x]  ArrayPop, ///< .pop() from a dynamically sized array in storage
- [x] ByteArrayPush, ///< .push() to a dynamically sized byte array in storage
- [x]  ObjectCreation, ///< array creation using new
- [x]  Assert, ///< assert()
- [x]  Require, ///< require()
- [x] ABIEncode,
- [x] ABIEncodePacked,
- [x] ABIEncodeWithSelector,
- [x] ABIEncodeWithSignature,
- [x] ABIDecode,
- [x] GasLeft, ///< gasleft()
- [x] MetaType, ///< type(...)
- [x] Declaration,

**Comment by axic** [comment]
@chriseth can we prioritise this?

**Comment by chriseth** [comment]
@axic can you make a checkbox list of which functions exactly?

**Comment by axic** [comment]
It seem `keccak256` was added since I've created this issue.

**Comment by axic** [comment]
@chriseth added a list, I think it is correct.

**Comment by mijovic** [comment]
I am working on 
Creation, ///< external call using CREATE

**Comment by mijovic** [comment]
SetGas and SetValue are deprecated and we will not implement them.
Is anyone working on `ABIDecode`?

**Comment by axic** [comment]
@aarlt said he'll look into `ABIDecode`.

**Comment by mijovic** [comment]
All except 
 SetGas, ///< modify the default gas value for the function call
 SetValue, ///< modify the default value transfer for the function call
is implemented, and those two are not planned, closing the issue
