### ISSUE TITLE
[Sol2Yul] codegen for constructors with parameters

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#8350]
See IRGenerator.cpp line 261

```
contract C {
  constructor(int a) public {
  }
}
```

**Comment by ekpyron** [comment]
For this we need to know where the constructor arguments start. Do we have an equivalent for ``CompilerStack::appendProgramSize()`` for Sol2Yul yet?

**Comment by ekpyron** [comment]
Respectively this depends on the state of yul objects and the infrastructure around that... what's the state of that? Maybe we should first specify this a bit (e.g. @mijovic asked about it earlier, but I couldn't tell if this can be done right away).

**Comment by chriseth** [comment]
yul objects are specified and you can use `datasize` for `CompilerStack::appendProgramSize()`.

**Comment by mijovic** [comment]
I started working on this
