### ISSUE TITLE
[Sol2Yul] codegen for Array conversions

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#8352]
`string YulUtilFunctions::conversionFunction(Type const& _from, Type const& _to)` does not implement array conversion when `_from` and `_to` differ in types.

example:

```solidity
pragma solidity >= 0.6.0;

contract C {
    function f(string memory s) public pure returns (bytes memory txt) {
        txt = bytes(s); // IR codegen path not implemented
    }
}
```

**Comment by chriseth** [comment]
Has been fixed in the meantime.
