### ISSUE TITLE
Allow assigning to storage pointer variables from inline assembly

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8361]
References https://github.com/ethereum/solidity/issues/8353#issuecomment-589077551

Restricting access to storage pointer variables but not memory pointer variables is asymmetric. Lifting the restriction would allow some interesting patterns.

**Comment by mudgen** [comment]
Yes, I agree!

**Comment by chriseth** [comment]
Note that only structs, arrays and mappings can be storage pointers, so storage pointers only use `_slot`.

**Comment by mudgen** [comment]
Good to know.
