### ISSUE TITLE
Deprecate `gasleft()`  native method (GAS opcode)

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#8363]
Ethereum plans to remove support to GAS opcode, therefore this should be deprecated from Solidity, so developers get correctly advised to stop using it. 

Contracts should be advised to externalize the parameters, having the msg.sender specifying the gasused in calldata, or whatever is the logic.

Caused by https://github.com/ethereum/EIPs/pull/2489

**Comment by axic** [comment]
I think it is too early to make this decision based on a draft EIP.

**Comment by lopezdp** [comment]
what! I need gasleft() in my life man! Even better would be a way to help me figure out how to get tx.gasprice to work so I can get the actual gasprice in a contract one day! :)

**Comment by Neurone** [comment]
[The pull request for EIP-2489](https://github.com/ethereum/EIPs/pull/2489) was never merged to the main repo and it is now closed. I suggest to close this issue too.
