### ISSUE TITLE
Out of bounds array access

### ISSUE THREAD

**Issue by duytai** [ethereum/solidity#8364]
## Description
```solidity
pragma solidity ^0.6.1;
contract A {
  function main() public {
    uint[3][4] memory balances;
    msg.sender.send(balances[2][3]);
  }
}
```
Compiler returns error: `Out of bounds array access `at `msg.sender.send(balances[2][3])`;
## Environment

- Compiler version: 0.6.1
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Mac 10.15.1

## Steps to Reproduce
Compile with the above source code

**Comment by chriseth** [comment]
Solidity does not have multi-dimensional arrays, it only has arrays of arrays. Because of that, `uint[3]` is an array of size 3, while `uint[3][4]` is an array of size 4 containing arrays of size 3.

**Comment by chriseth** [comment]
Solidity does not have multi-dimensional arrays, it only has arrays of arrays. Because of that, `uint[3]` is an array of size 3, while `uint[3][4]` is an array of size 4 containing arrays of size 3.

**Comment by rschumi0** [comment]
However, even for nested arrays, why do you start with the size of the inside array? When you access it you have to start with the index of the outside array and then continue inwards.

For example, when I had an array with a bit more nesting like this:
`a = [[[[3,1],[5,9]],[[6,8],[4,0]],[[1,9],[6,4]]],[[[0,4],[8,8]],[[10,6],[8,4]],[[2,10],[1,5]]],[[[8,3],[3,4]],[[0,4],[6,1]],[[10,8],[7,1]]]];`
I was quite confused when the definition was like this `uint8[2][2][3][3]` and the access to the elements was in the reverse order (e.g., to the last element `a[2][2][1][1]`).

So why aren't the definition and the access consistent, i.e., by starting both from the outside?

**Comment by chriseth** [comment]
@rschumi0 I hope it is consistent: `T[3]` is always an array of size 3 with inner type `T`, regardless of what `T` is (it can be another array, a struct or a value type). If you have a variable `x` of type `T[3]`, then `x[2]` is always of type `T`, regardless of what `T` is.
