### ISSUE TITLE
ICE in solfuzzer; file is invalid to solc

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8371]
## Description

This contract:
```solidity
import {A} from ".";
```

produces:

```
Testing compiler with optimizer.
Input JSON: {"language":"Solidity","settings":{"evmVersion":"homestead","optimizer":{"enabled":true,"runs":200},"outputSelection":{"*":{"":["*"],"*":["*"]}}},"sources":{"":{"content":"import {A} from \".\";\n"}}}
Output JSON: {"errors":[{"component":"general","formattedMessage":"InternalCompilerError: \n","message":"Internal compiler error (/home/user/solidity/libsolidity/interface/CompilerStack.cpp:1001):","severity":"error","type":"InternalCompilerError"}],"sources":{}}
Invalid error: "InternalCompilerError"
Fuzzer failed on finish.sol
```

when compiled with solfuzzer.  solc just complains about the import.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

## Environment

- Compiler version:  0.6.3-develop.2020.2.10+commit.e8eb1f2d.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by chriseth** [comment]
The assertion is in CompilerStack.cpp:1008
