### ISSUE TITLE
Extend control flow analysis to inline assembly.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8375]
The following code should compile without warning:
```
contract C {
    struct S {
        uint a;
        uint b;
    }

    function data() internal view returns (S storage _data) {
        bytes32 slot = keccak256(abi.encode(uint(1), uint(0)));
        assembly {
            _data_slot := slot
        }
    }
}
```

For this, we need to descend into inline assembly in the control flow builder and handle lvalue and rvalue access to variables differently.

**Comment by mudgen** [comment]
Can this be part of Sprint 3?

Will the ability to use displaced local storage pointers work without error or warning in the next release of solidity?

**Comment by ekpyron** [comment]
I'm looking into it now, so it should be part of the next release.

**Comment by mudgen** [comment]
@ekpyron This great news!  Thank you.
