### ISSUE TITLE
Smart contract always return TransactionReceipt

### ISSUE THREAD

**Issue by NicolaGessa** [ethereum/solidity#8376]
Hello all, I try to write a very simple smart contract, to call from a java program.

The contract is:
 
pragma solidity ^0.6.0;

contract Hello {

  function read() public view returns (string memory) {   
    return "Hello";
  }	

}

the java code to call the smart contract function is
Contract.read().send();

I tried in many ways, using pure , view or external, but I always receive this as result:
TransactionReceipt{transactionHash='.....

and never the string "Hello".

where is the problem? may someone show me a simple example to receive a value in return.
How to write a simple Smart contract to receive from a java program a value , like "Hello". 

thank you so much  
I use 
SOLC: Version: 0.6.3+commit.8dda9521.Linux.g++
Web3J: Version: 4.5.14

**Comment by chriseth** [comment]
This looks like a problem with web3j. It might be due to the fact that we removed the `constant` field after having deprecated it a long time ago. Can you report the issue there? Thanks!

**Comment by NicolaGessa** [comment]
thank you chriseth, 
I see there is  already the same issue in web3j/web3j (without response up to now).
In any case, I tried this code (without constant):

pragma solidity ^0.5.1;

contract Hello {

  function read() public pure returns (string memory) {
    return "Hello";
  }
}

with 
SOLC: Version: 0.5.16+commit.9c3226ce.Linux.g++
Web3J: Version: 4.5.14

and it works.

So really I don't understand if it is a problem of solc or of web3j, since changing the compiler  version I get the correct value with no problem.

**Comment by chriseth** [comment]
The deprecated field was removed in 0.6.0, this explains why it works with 0.5.16.

**Comment by dfsantamaria** [comment]
I'm experiencing the same issue (web3j 4.5.16 and solc 0.6.3) with view methods.

**Comment by chriseth** [comment]
@dfsantamaria please open an issue on the web3j repository

**Comment by dfsantamaria** [comment]
I do.
