### ISSUE TITLE
ICE in ContractCompiler::visit(InlineAssembly &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8386]
## Description

This contract:
```solidity
contract C {
    function f() public pure {}
    constructor() public {
        assembly {
            let x := f
        }
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/codegen/ContractCompiler.cpp(667): Throw in function auto solidity::frontend::ContractCompiler::visit(const solidity::frontend::InlineAssembly &)::(anonymous class)::operator()(const yul::Identifier &, yul::IdentifierContext, yul::AbstractAssembly &) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

## Environment

- Compiler version:  0.6.3-develop.2020.2.10+commit.e8eb1f2d.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by chriseth** [comment]
Inline assembly access to functions should not be possible.
