### ISSUE TITLE
Getters for enum-indexed mappings don't check their arguments

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#8394]
## Description

While normally Solidity prevents out-of-range enums from existing, it's still possible to create them by manually passing them in from outside, as functions don't in general check the validity of enums and booleans passed in from outside.  That's not the problem; I'm assuming that's intentional and not going to be changed anytime soon.

The problem is that getters for public enum-keyed mappings don't do this; these functions should check their arguments and revert if the argument is out of range.  Why do I say this?  Because:

1. Enum-keyed mappings *do* check their argument when accessed inside another function (whether for reading or writing).  But if it's via a getter, then you can read outside the range.  (You can't *set* outside the range, due to the mappings normally checking their arguments, so you'll always get 0, but still.)
2. With bool-keyed mappings (`bool` being the one other type that can be used as a mapping key and which can have out-of-range values passed in from outside), out-of-range values are normalized to `true` when used as a mapping key, and this applies both when the mapping is accessed within another function *and* when it's accessed via a getter.

So, for consistency, accessing an enum-keyed mapping via a getter should work the same as accessing it normally (much as is true for `bool`-keyed mappings, the one other type for which the question is relevant), meaning, it should revert if the key is out of range for enum.

## Environment

- Compiler version: 0.6.3
- Target EVM version (as per compiler settings): whatever the default is
- Framework/IDE (e.g. Truffle or Remix): Truffle
- EVM execution environment / backend / blockchain client: Ganache CLI v6.8.2 (ganache-core: 2.9.2)

## Steps to Reproduce

```
pragma solidity ^0.6.3;

contract EnumKeysTest {
  enum Ternary { Yes, No, MaybeSo }

  mapping(Ternary => string) public enumMap;

  function readFrom(Ternary out) public view returns (string memory) {
    return enumMap[out];
  }
}
```

Calling `readFrom(3)` causes a revert, but calling `enumMap(3)` just returns `''`.

**Comment by chriseth** [comment]
ABIEncoderV2 enabled strict parameter checking, and if you activate it, the code reverts for both functions.

**Comment by haltman-at** [comment]
Oh, I totally didn't realize!  Thanks!  I do think that getters should still always check parameters for consistency, but it's still really nice that ABIEncoderV2 turns on strict parameter checking generally.

**Comment by chriseth** [comment]
So do you think this can be closed?
