### ISSUE TITLE
[solc] Fuzzing: Leak exceptions

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8395]
## Abstract

Currently, the solc fuzzers invoke StandardCompiler's compileSolidity API that does **not** leak exceptions, rather "strigifies" them in the json output.

https://github.com/ethereum/solidity/blob/bb09787bd0bcbcbebf7d47584e58363d332f9d92/libsolidity/interface/StandardCompiler.cpp#L763

The fuzzer harness looks for the string "InternalCompilerException" in the json output, and if found, it throws a runtime exception.

https://github.com/ethereum/solidity/blob/b65a165da19f150fbff39eac08729da72e4216c3/test/tools/fuzzer_common.cpp#L71

One issue with this setup is that the fuzzer believes the underlying problem is the line above (and the stack trace leading up to it), and not the original place in solidity code where the ICE was thrown.

This issue tracks support for a version of `compileSolidity` that the fuzzer could use that **leaks** the original exception so that the fuzzer is informed of a given ICE's uniqueless (via stack trace which the fuzzer uses as a proxy to measure uniqueness).

**Comment by axic** [comment]
Why don't you just use `CompilerStack` directly for this case?
