### ISSUE TITLE
[solc] ICE: thows InvalidOpcode exception in Instruction.h

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8404]
## Description

```
contract K {
  function f() public {
    abi.encode("","","","","","","","","","","","","","","");
  }
}
```

throws 

https://github.com/ethereum/solidity/blob/b65a165da19f150fbff39eac08729da72e4216c3/libevmasm/Instruction.h#L259

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): NA

## Steps to Reproduce

```
$ solc <input.sol>
Exception during compilation: /home/bhargava/work/github/solidity/libevmasm/Instruction.h(259): Throw in function solidity::evmasm::Instruction solidity::evmasm::dupInstruction(unsigned int)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::evmasm::InvalidOpcode>
std::exception::what: InvalidOpcode
[solidity::util::tag_comment*] = Invalid DUP instruction requested (17).
```

**Comment by ekpyron** [comment]
@mijovic will be working on this.

**Comment by ekpyron** [comment]
We'll turn this into a "stack too deep" assertion with https://github.com/ethereum/solidity/pull/8420, because that's basically what this is. Unfortunately, there's no really nice solution to catch these before code generation.

**Comment by ekpyron** [comment]
Not sure if we should keep this open or close it in favour of the general "stack too deep" problem once #8420 is merged...

**Comment by axic** [comment]
Still a problem today, just the assertion is different:
```
/Users/alex/Projects/solidity/libsolidity/codegen/CompilerUtils.cpp(503): Throw in function void solidity::frontend::CompilerUtils::encodeToMemory(const solidity::frontend::TypePointers &, const solidity::frontend::TypePointers &, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Stack too deep(17), try using fewer variables.
[solidity::util::tag_comment*] = Stack too deep(17), try using fewer variables.
```
