### ISSUE TITLE
Pureness of reading storage slots only without accessing storage.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8425]
Currently, within solidity code, any reference to a storage pointer is considered ``view``. However, there if there is actually no access to storage, but merely the storage slot is read, it could be considered ``pure``, e.g.
```
contract C {
    uint256[] s;
    function f() internal pure returns (uint256[] storage c) {
        c = s;
    }
}
```
is currently invalid, but could be valid. This is especially interesting, since we allow assembly access to storage slots in pure functions already, so the following is already allowed:
```
contract C {
    uint256[] s;
    function f() internal pure returns (uint256[] storage c) {
        assembly { c_slot := s_slot }
    }
}
```

**Comment by chriseth** [comment]
Sounds good! Is this breaking?

**Comment by ekpyron** [comment]
It just allows stuff that was disallowed before... we'll get ``mutability can be restricted to pure`` warnings for existing code, but that's only warnings, so non-breaking. Right now no other aspect comes to my mind that could make this breaking.

**Comment by hrkrshnn** [comment]
The first contract issues the following error:

> Error: Expected identifier but got 'storage'
>  --> /tmp/storage.sol:2:12:
>   |
>  |     uint256[] storage s;
>   |                   ^^^^^^^

The [documentation](https://solidity.readthedocs.io/en/v0.6.5/types.html#data-location-and-assignment-behaviour) says:

```
contract C {
    // The data location of x is storage.
    // This is the only place where the
    // data location can be omitted.
    uint[] x;
```
Should it be possible to explicitly write storage in such cases?

**Comment by ekpyron** [comment]
@hrkrshnn I edited the code to avoid the error - I accidentally added a ``storage`` qualifier to the state variables, which is syntactically invalid.
However, the error message you posted looks like there is an issue with reporting the source locations for this error, I'll have a look at that and potentially create a new issue for it.

**Comment by hrkrshnn** [comment]
@ekpyron ok. Please don't bother with my error message, the ^ symbols  are my own, and the location 2:12 is probably wrong.

Here's a verbatim one.
```
Error: Expected identifier but got 'storage'
 --> /tmp/storage.sol:2:15:
  |
2 |     uint256[] storage s;
  |               ^^^^^^^

```

**Comment by ekpyron** [comment]
Ah, ok!

**Comment by ekpyron** [comment]
After discussing some aspects of this with @hrkrshnn I'm actually not sure anymore that this can be done in a reasonable way. We need to distinguish the following:
```
uint256[] s;
function f(uint256[] storage x) internal pure returns (uint256[] storage) {
   return x;
}
function g() internal pure {
   s;
}
function h() internal pure {
   f(s);
}
```

From these:
```
uint256[] s;
function f(uint256[] storage x) internal view returns (uint256[] memory) {
   return x;
}
function g() internal view {
   uint256[] memory c = s;
}
function h(uint256[] memory) internal view {}
function i() internal view {
   h(s);
}
```

I.e. the change between view and pure occurs in implicit type conversions... catching that would make the ViewPureChecker significantly more complex... is there sufficient gain in making the accesses to only the slot pure to justify this? @chriseth

**Comment by chriseth** [comment]
@ekpyron it looks like it is better to postpone this to after the introduction of `copyof`

**Comment by chriseth** [comment]
Is this really in progress?

**Comment by hrkrshnn** [comment]
@chriseth No. I'll put this into icebox.
