### ISSUE TITLE
Natspec tag for delegatecall targets

### ISSUE THREAD

**Issue by montyly** [ethereum/solidity#8430]
Hi,

## Abstract

I have heard that you are looking to improve or change the natspec format, would it be possible to add a contract's tag to inform that the contract is meant to be a `delegatecall` target?

## Motivation
Many contracts are meant to only be a delegatecall target (either through a proxy factory, or for upgradeability). These contracts have specific properties, such as:
-  The state variables need to be initialized outside of the constructor (through an init function)
- Some state variables might never been initialized, are they are initialized in the proxy (ex: `implementation`)

Knowing which contracts are delegatecall targets will help third parties code analyzer (such as [`slither-check-upgradeability`](https://github.com/crytic/slither/wiki/Upgradeability-Checks)) to automatically detect and adjust their checks. Right now we use heuristics in Slither, but they are not robust enough.

Additionally, this information might be useful for blockchain explorer, like etherscan.

## Specification

I am not entirely sure what would be the best way to specify it, maybe a `delegatecall_target` tag:
```solidity
/// @delegatecall_target
contract MyContract {
```

Or a `type` tag, that could be `standard/proxy/upgradeable` or something like that:
```solidity
/// @type proxy
contract MyContract {
```

## Backwards Compatibility

As this will only affect the natspec, I dont see immediate backward compatibility issue

Thanks

**Comment by chriseth** [comment]
While this looks like a good solution for the current state, I would actually prefer to add the "delegateable contract" at the Solidity language level.

**Comment by axic** [comment]
I'm not sure we have progressed in any way, but at least tools like slither could use `@custom:delegatecall_target` as a tag.
