### ISSUE TITLE
Invariants

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#8433]
## Abstract
I want the ability to define invariant assertions on my contract that are automatically checked anytime an externally called non-static function returns.

## Motivation
Writing secure code is hard.  It is much easier to write secure code if you can make some assertions that are guaranteed to always be true.

## Specification
A new `invariant` keyword would be added and would be allowed as a top-level expression on a contract akin to `modifier` and `function`.  Any code specified in the `invariant` block would automatically be executed at the end of the constructor and anytime a non-view/pure function is called by an external caller
```solidity
contract Apple {
    uint256 a = 10;
    uint256 b = 5;
    invariant {
        require(a > b);
    }
    function banana() external {
        ...
        // invariant contents would be executed here automatically, because this function is external
    }
    function cherry() public {
        ...
        // invariant contents would be executed here if this function was called externally, but not if called internally
    }
    function durian() internal {
        ...
        // invariant never called here since this is never called externally
    }
    function eggplant() public view {
        ...
        // invariant never called here because this function is view
    }
}
```

This behavior can be partially simulated with a modifier like:
```solidity
contract Apple {
    modifier invariant() {
        _;
        require(a > b);
    }
}
```
However, this requires the user remember to put it on every external/public non-view function, leave it off of every internal/private/view/pure function, and even if you successfully do that without any mistakes, you cannot (as far as I know) detect from Solidity whether a particular function was called internally or externally (e.g., JUMP vs CALL).  By having a language construct, the compiler can ensure that the invariant code is executed in all of the right places, and not executed when it isn't necessary.

## Backwards Compatibility
I don't think there are any backward compatibility issues here.

**Comment by mudgen** [comment]
Nice idea.

**Comment by leonardoalt** [comment]
@MicahZoltu Please take a look at https://github.com/ethereum/solidity/issues/4991, sounds similar.
In general we agree that this should exist. The main point is deciding on 1) the expressiveness 2) the syntax and 3) code generation.

**Comment by chriseth** [comment]
If I understand it correctly, the scope of this issue is invariants that always generate code and can be written in regular solidity (as opposed to #4991). To do things like computing the sum of all balances, you would need explicit "shadow" variables (which are not really shadow variables because they actually exist in storage).

Could you create some examples where such invariants make sense and can be expressed in Solidity, @MicahZoltu ?

**Comment by MicahZoltu** [comment]
The high level set of examples are anything where Design by Contract makes sense, meaning you have some invariants you want to assert are always true.

```solidity
contract Apple {
	Erc20 tokenA;
	Erc20 tokenB;

	invariant {
		require(tokenA.balanceOf(this) + tokenB.balanceOf(this) == 1000);
	}

	constructor(Erc20 _tokenA, Erc20 _tokenB) {
		tokenA = _tokenA;
		tokenB = _tokenB;
		tokenA.transferFrom(msg.sender, 1000);
	}

	function swapFromA(uint256 amount) public {
		tokenA.transferFrom(msg.sender, amount);
		tokenB.transfer(msg.sender, amount);
	}

	function swapFromB(uint256 amount) public {
		tokenB.transferFrom(msg.sender, amount);
		tokenA.transfer(msg.sender, amount);
	}

	// ... a bunch of other functions that transfer token A and B around in various ways, all of which may have bugs
}
```
This is a pretty simple example, but I think gets the general idea across.  An invariant allows you to specify in code (and validate at runtime!) that some constraint *always* holds true automatically at the end of every external call into the contract.  Often times contracts can become complex and there is room for subtle bugs buried inside the code that cause a constraint that *should* have been upheld to become violated.

In a perfect world, we would have static analysis tools that could make strong guarantees that invariant constraints were never violated, but building a design by contract language that is 100% sound is a *really hard problem*.  Runtime invariant constraints are a poor mans solution to the same problem, where you don't make guarantees at compile time, but instead just ensure that at runtime the constraints are upheld by rolling back any transaction that would result in them being violated at the end of the transaction.

**Comment by chriseth** [comment]
One of my worries is that, if the invariant somehow stops to be true (for example due to a bug in the external erc20 contract in the example above), the contract is blocked forever. Wouldn't it be better to instead move it into a consistent emergency state of some sort?

**Comment by leonardoalt** [comment]
@chriseth why can https://github.com/ethereum/solidity/issues/4991 not be written in regular Solidity? The initial proposal there is similar to this, what changes is the use of `assert` instead of `require` at the end of the functions.

**Comment by leonardoalt** [comment]
> One of my worries is that, if the invariant somehow stops to be true (for example due to a bug in the external erc20 contract in the example above), the contract is blocked forever. Wouldn't it be better to instead move it into a consistent emergency state of some sort?

In that case people would need to be sure about the code of the tokens they're referring to. IMO @MicahZoltu 's idea forces people to design things properly. Of course we can't expect tools to be able to verify those invariant, but being explicit about such a contract invariant might help proving other targets.

**Comment by chriseth** [comment]
@leonardoalt I thought that #4991 also includes things like `sum(balances)`.

If you cannot prove the invariant correct, then I would not want to use it without a way to unlock the contract again. The contract being locked might also be caused by a compiler bug, for example.

**Comment by MicahZoltu** [comment]
@chriseth There are invariants that can be corrected should they not hold, and there are invariants that can be proven via static analysis, and there are invariants that if asserted on every function call can be guaranteed.

For example, an invariant that one storage variable is greater than the other can be asserted on at the end of the constructor, and at the end of every external function call.  We can know that this invariant is guaranteed to hold without looking at any code because no transaction can change it without reverting.

While you are correct, there are *some* invariants that can be dangerous, I think the value add of compiler enforced invariant checking far outweighs the risks.

**Comment by leonardoalt** [comment]
@chriseth In https://github.com/ethereum/solidity/issues/4991 I had in mind things that could also generate code.

I agree with @MicahZoltu
