### ISSUE TITLE
Cannot call unimplemented base function: inconsistency soljs vs solc

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#8434]
I have been translating code from ^0.5.0 to ^0.6.0, and I have been having a few issues with virtual methods that are implemented in modules and then merge together. I tried to reproduce the issue with a minimal code, just to narrow down what I can and cannot do, only to see that I get different compiler outcomes between truffle/waffle on the one hand and remix on the other.

Consider the following code:

	pragma solidity ^0.6.0;
	abstract contract II
	{
	    function a() public virtual view returns(uint256);
	    function b() public virtual view returns(uint256);
	}
	abstract contract I is II
	{
	    function _a() internal view virtual returns(uint256);
	    function _b() internal view virtual returns(uint256);
	}
	abstract contract V is I
	{
	    function a() public override view returns(uint256) { return _a(); }
	    function b() public override view returns(uint256) { return _b(); }
	}
	abstract contract A is I
	{
	    function _a() internal override view returns(uint256) { return 1; }
	}
	abstract contract B is I
	{
	    function _b() internal override view returns(uint256) { return _a()+1; }
	}
	contract AB is II, A, B, V
	{
	}

When compiling it in remix (soljs), with 0.6.3, I get a successfull compilation, and the expected behaviour. However, when trying to compile it with truffle/waffle (solc) I get:

	TypeError: Cannot call unimplemented base function.
    function a() public override view returns(uint256) { return _a(); }
                                                                ^--^
	TypeError: Cannot call unimplemented base function.
    function b() public override view returns(uint256) { return _b(); }
                                                                ^--^
	TypeError: Cannot call unimplemented base function.
    function _b() internal override view returns(uint256) { return _a()+1; }

I would argue that the correct behaviour should be the one in soljs, but at the very least we should all agree that this inconsistency is a problem.

**Comment by ekpyron** [comment]
Oh my... this is a (rather embarrassing) bug that was apparently introduced in 0.6.2. When parsing the pragma, remix will automatically select ``0.6.0``, my guess is that this is why it works there. I can confirm that this is broken for 0.6.2 and 0.6.3.

**Comment by ekpyron** [comment]
Thank you very much for reporting this! I actually can't believe that this has gone unnoticed for this long.
