### ISSUE TITLE
Sample code in documentation for create2 not working

### ISSUE THREAD

**Issue by reiven** [ethereum/solidity#8438]
Hi! 

I found a problem with the sample code included in [create 2](https://solidity.readthedocs.io/en/latest/control-structures.html#salted-contract-creations-create2) sample code.
Looks like the `predictedAddress` function is not working, which makes fail all the process.
I've deployed the exact code to ropsten, verified the source code [here](https://ropsten.etherscan.io/address/0x3e73f9bb40f4855ff88b5c96eb38e7c141c81301) and then calling the `createDSalted` function fails, which reverts the transaction, see [here](https://ropsten.etherscan.io/tx/0x60151dac147277ccb4038ca5461726cfcda5240f95c5caa7666e9e4438b42922)

Then i've divide the `createDSalted` to just deploy the contract, and have a view function to precalculate the address, and i found the problem is the logic in the `predictedAddress` function in the sample, which fails. The divided contract was deployed [here](https://ropsten.etherscan.io/address/0x6db6715e8dc468ad8fc949021889808a4faf314c

I've still cannot resolve the issue in the address precalculation, i'll investigate it later on, but if anyone can find it, great!

**Comment by chriseth** [comment]
I'm sorry, we cropped the address at the wrong end. If you use `address(uint(keccak256(abi.encodePacked(` instead of `address(bytes32(keccak256(abi.encodePacked(` then it should work.

**Comment by reiven** [comment]
Great, thank you @chriseth !
