### ISSUE TITLE
Memory Arrays that Can Grow

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#8440]
## Abstract
Some solidity functions are only meant to be called by off-chain software. Such functions have no gas cost and would benefit from arrays that can grow dynamically, for example by having a push() function. Having this can result in cleaner code. Currently a programmer has to manually write the code to create a bigger array and populate it with the older array.

It is understood that a memory array that can grow would cost gas in functions that are called on-chain. Solidity documentation should very clearly state gas-cost concerns for growing an array.

**Comment by ekpyron** [comment]
This can *almost* be implemented using libraries...
```
library L {
    function push(uint256[] memory x, uint256 y) internal pure returns (uint256[] memory r) {
        r = new uint256[](x.length + 1);
        for (uint256 i = 0; i < x.length; i++)
            r[i] = x[i];
        r[x.length] = y;
    }
}

contract C {
    using L for uint256[];
    function f() public pure returns (uint256[] memory) {
        uint256[] memory x = new uint256[](0);
        x = x.push(42);
        return x;
    }
}
```
So I'm wondering: is this already good enough for this purpose as is? Or *would* it be good enough, if it could really be a "proper" push (whithout the need to reassign as shown in ``x = x.push(42);``)? Or would it be enough, if this could be done generically instead of only per a specific type?

**Comment by mudgen** [comment]
Thank you. I think that is pretty good.  You are right that someone can just implement their own array enlargement functions or use libraries.

Yes, it would be nice if it did not have the assignment and it could be done generically for any type.   I think I am more interested in the memory mapping type in #8439 because that is harder for a user of the language to implement on their own.

**Comment by chriseth** [comment]
I think growing memory arrays have too many hidden surprises. Solidity tries to minimize those (see the latest removal of write-access to `.length` for storage arrays) as much as possible.

We should provide a way to implement user-defined types and algorithms in a generic way, though.
