### ISSUE TITLE
[solc] TypeChecker throws ICE because the check "!!tupleExpression->components()[i]" fails

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8450]
## Description

```
contract C {
  function s() {
    (((((((((((,4),)),)),),))=4)));
  }
}
```

throws

https://github.com/ethereum/solidity/blob/dbe2a5f451c5c2cc0190f859480fb65bc911e92c/libsolidity/analysis/TypeChecker.cpp#L1321

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
Internal compiler error during compilation:
/home/bhargava/work/github/solidity/libsolidity/analysis/TypeChecker.cpp(1321): Throw in function void solidity::frontend::TypeChecker::checkExpressionAssignment(const solidity::frontend::Type &, const solidity::frontend::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

**Comment by chriseth** [comment]
We should not allow nested tuples on the left-hand-side. What might be OK is `(a) = 4` and `((a),) = 4` but not `(((a,),) = 4`.

**Comment by a3d4** [comment]
Similarly, the following code
```
contract C {
  function f() public pure {
    int a;
    (((a,),)) = ((1,2),3);
  }
}
```
causes
```
solAssert(
    tupleExpression->components().size() == types.size() || m_errorReporter.hasErrors(),
    "Array sizes don't match and no errors generated."
);
```

The PR #8550 should fix both.

**Comment by a3d4** [comment]
> 
> 
> We should not allow nested tuples on the left-hand-side. What might be OK is `(a) = 4` and `((a),) = 4` but not `(((a,),) = 4`.

It could be done easily, but for now I allowed `((a,b))=(1,2)`. If I understand correctly, the comment suggests that `((a,b))` on lhs should have `(a,b)` type:

```
 * Examples: (1, 2), (x,), (x), (), [1, 2],
 . . . .
 * The respective types in lvalue context are: 2-tuple, 2-tuple (with wildcard), type of x, 0-tuple
```

**Comment by chriseth** [comment]
The PR looks good. My only comment is that it might be easier to look into the expression instead of wrapping the tuple type into a vector, but I think it would lead to the same result.
