### ISSUE TITLE
Style: single quotes for string literals

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#846]
All the code examples use double quotes for string literals. String literals actually support single quotes too. The style guide currently doesn't any of them.

I think it would make sense to either:
a) remove single quotes from string literals
b) document both options and allow both in the style guide
c) document both options, but recommend double (or single) quotes in the style guide (but more importantly, a consistent use of quotes).

@Denton-L @chriseth what do you think?

**Comment by Denton-L** [comment]
I think option C would make the most sense because it would be the least "breaking".

**Comment by axic** [comment]
We have a breaking release upcoming plus it wasn't even documented. It could be removed if desired.

**Comment by VoR0220** [comment]
What do we do for `'s ? :)

**Comment by axic** [comment]
It is like Javascript, both double and single quotes represent strings.

**Comment by VoR0220** [comment]
no but I mean, what are we going to do about backticks?

**Comment by axic** [comment]
They are currently not part of the lexer.

**Comment by VoR0220** [comment]
Should they be a part of the lexer? Personally I'm fine with leaving single quotes as is...just make sure that single quotes match to single quotes and double quotes to double quotes, etc.

**Comment by axic** [comment]
Ho do you expect bacticks to work if they are not parsed?

**Comment by VoR0220** [comment]
right, I'm saying maybe they should be parsed (this is incredibly off topic though and I'm going to shut up now).

**Comment by chriseth** [comment]
Both string styles are supported because we try to be close to javascript syntax. We can recommend one of them and clean up the documentation.
