### ISSUE TITLE
Test conversion from value-set external function to non-set external function

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8461]
In addition to https://github.com/ethereum/solidity/pull/8414 - add a test with "also Yul" that has:

```
contract C {
  function f() public payable {
    function() external payable x = this.f{value: 7};
  }
}
```

**Comment by hrkrshnn** [comment]
This is supposed to fail right? @chriseth 

> TypeError: (46-94): Type function () payable external is not implicitly convertible to expected type function () payable external.

**Comment by chriseth** [comment]
Yes.
