### ISSUE TITLE
Allow local storage vars unassigned in definition if assigned later

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#8479]
I tested out issue #8375 and it works perfectly.
This is really great!

But I would also really like the following to work:
```Solidity
contract C {
    struct S {
        uint a;
        uint b;
    }

    function data() external {
        bytes32 slot = keccak256(abi.encode(uint(1), uint(0)));
        S storage _data;
        assembly {
            _data_slot := slot
        }
        ... more code
    }
}
```

I would like this to work for certain gas-critical situations where I do not want the gas overhead of a function call, but I still want to assign a local storage pointer.

Can this be done?

**Comment by chriseth** [comment]
Ah, I'm really sorry we missed that!
It turns out that apart from control-flow analysis, we also have a very simple check that disallows storage pointer variable declarations without `= <value>` in the type checker. I think that the control-flow analysis should actually be superior and we might drop this simple check.

**Comment by mudgen** [comment]
Sounds good and no problem. I look forward to this improvement in the next release of Solidity. Keep up the good work!

**Comment by mudgen** [comment]
Also, is there a good reason that a constant can't be used directly in inline assembly?
I would really like to be able to do this:

``` Solidity
contract MyStorageContract {

    // the state variables we care about
    struct MyStorage {
        uint aVar;
        bytes[] myBytes;
        mapping(uint => bytes32) myMap;
    }

    bytes32 constant location = keccak256("com.mycompany.my.storage");

    function myStorage() internal pure returns(MyStorage storage ms) {
        assembly {
            ms_slot := location
        }
    }
}
```

**Comment by chriseth** [comment]
Unfortunately, constants are too complicated for inline assembly because you would have to switch back to the Solidity expression code generator.

**Comment by mudgen** [comment]
Okay, no problem. Thank you for the answer!

**Comment by ekpyron** [comment]
@hrkrshnn will be working on this.
