### ISSUE TITLE
Add type(uint).max or something similar

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8484]

**Comment by chriseth** [comment]
Suggestions: `uint.max`

@axic: Which other members do we want in general?

**Comment by christianparpart** [comment]
Other then `TYPE.max()` I'd suggest `max(TYPE)`.

**Comment by chriseth** [comment]
I'm not a fan of adding more global free functions - especially with such a common name.

**Comment by axic** [comment]
Vyper is also planning this feature: https://github.com/vyperlang/vyper/issues/1923

**Comment by axic** [comment]
I'm probably in favour of `type(uint256).min` given we are using the `type()` builtin for a bunch of relevant things now.

**Comment by chriseth** [comment]
Proposal by @christianparpart : For fixed point types, we could use `type(fixed).epsilon` for the smallest positive value.

**Comment by chriseth** [comment]
Decision in call: Let's have `type(X).min` / `type(X).max` for all integer types.
