### ISSUE TITLE
[Sol->Yul] Libraries with only internal functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8485]
This issue tracks the implementation of libraries that do not need linking.

**Comment by chriseth** [comment]
@cameel you can also work on this

**Comment by chriseth** [comment]
For this, I think we should start adding a builtin function called `linkerSymbol` to EVMDialect, which requires `"literalArguments"` and is in all aspects very similar to `datasize`. Its code generation should just call `linkerSymbol` on the abstract assembly.

As a next step, `void IRGeneratorForStatements::endVisit(Identifier const& _identifier)` can be changed to implement the library case by defining the identifier via the linker symbol (the library's address).

**Comment by chriseth** [comment]
Once we have that, I think we can implement function calls to both internal and non-internal (the more complicated case) library functions. The non-internal case should use `delegatecall` while the internal case should be the same as internal function calls to functions in the same contract.

**Comment by cameel** [comment]
OK. So, just to make sure I understand the high-level requirements here: basically when I'm done, `solc --ir` should be able to generate IR for contracts like `test/libsolidity/semanticTests/libraries/internal_library_function.sol` and other `internal_library_function_*.sol` files?

BTW, could you assign me? It looks like I don't have enough permissions to assign myself.

**Comment by chriseth** [comment]
Yes, but I think the most basic test should be `stub_internal.sol`. At the end, you should be able to add the `compileViaYul: also` setting like that:
```
library L {
    function f(uint256 v) internal returns (uint256) { return v*v; }
}
contract C {
    function g(uint256 v) external returns (uint256) {
        return L.f(v);
    }
}
// ====
// compileViaYul: also
// ----
// g(uint256): 1 -> 1
// g(uint256): 2 -> 4
// g(uint256): 4 -> 16
```

**Comment by cameel** [comment]
@chriseth I need to make the `IRGenerator` generate the code of the internal library functions that get called. 

`IRGenerator` already does this for the contract being compiled:

```
string IRGenerator::generate(ContractDefinition const& _contract)
{
	...
	// TODO it would probably be better to only generate functions when internalDispatch or
	// virtualFunctionName is called - same below.
	for (auto const* contract: _contract.annotation().linearizedBaseContracts)
		for (auto const* fun: contract->definedFunctions())
			generateFunction(*fun);
	t("functions", m_context.functionCollector().requestedFunctions());
	...
```

but its job is simpler because it only needs to find function declarations/definitions.

1) I could do something just as simple for the library calls (i.e. go over all libraries from the same file and add all their functions). But this leaves even more stuff that will need to be removed by the optimizer.
2) I could traverse the AST and find all internal library calls. Seems heavy. I don't think it's good idea.
3) I could call `generateFunction()` in `IRGeneratorForStatements` when I encounter the call. I'm not sure if `IRGenerator` is even designed to allow this or if this will cause problems. I would also have to ensure that functions do not get included multiple times.

What would you suggest doing here?

**Comment by chriseth** [comment]
Ah sorry, I thought we had some kind of function generation queue that works like point 3 in your comment.

Since `m_context.functionCollector().createFunction` is used, functions will only be generated once (as long as we keep a strict scheme for naming the functions).

Just generating code for all libraries in the source tree is too heavy.

I think our best bet is to actually implement it like a queue (as outlined in the TODO in IRGenerator::generate(ContractDefinition):

Instead of generating code for all functions right away, we maintain a queue of Solidity functions that need their code being generated. Whenever such a function is called during code generation and it is not already in the queue, it is added. We terminate when the queue is empty.

Can you do this first as a refactoring on the existing code, ignoring libraries?

**Comment by cameel** [comment]
Thanks. Sure. Handling it in some way is a part of the task anyway so a refactor to fix the `TODO` and  add a mechanism for it is fine with me.

**Comment by cameel** [comment]
@chriseth There are tests called `semanticTests/libraries/library_enum_as_an_expression.sol` and `semanticTests/libraries/library_struct_as_an_expression.sol` in the directory with library tests. They check whether accessing an enum or a struct defined in a library works, but it's just a no-op - they just use the name of the type and don't try to actually do anything with it. I can easily make them pass on top of #8721 by removing some asserts but it seems too easy.  Is that really enough to get it working of is there some substantial functionality missing and just not covered with yul tests?

EDIT: I see you did #8685 today. It's probably related.

**Comment by cameel** [comment]
All my PRs that add the missing functionality have been merged. This is done now.

In the end I did not add `linkerSymbol`. It will be necessary for external library functions but that's outside of the scope of this issue.
