### ISSUE TITLE
New Soltest needs some love

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#849]
The new soltest no longer enables you to separate out your tasks individually if you want to test individual components in os x El Capitan...it gives you a seg fault every time you try. In addition I think it would be nice to whittle down the options given in the binary (however we can do this) by laying out a couple of key flags for us to use during testing (really the only ones I've ever found useful are the pretty print, the individual testing component...and that's about it). Zsh compatibility == super win.

**Comment by chriseth** [comment]
Will probably be fixed by https://github.com/ethereum/solidity/pull/837
Please see if that PR helps or you can improve it.

**Comment by VoR0220** [comment]
Going to test and then see if I can close this.

**Comment by VoR0220** [comment]
still running into problems with running individual endToEndTests.

**Comment by VoR0220** [comment]
It automatically jumps to the assumption that I want to run all of the tests.

**Comment by VoR0220** [comment]
actually nvm, I figured out how this works, you have to isolate it in the first set of arguments, then append -- and then the ipc arg. I think I'll try to make a help screen for that (where would that be located)?
