### ISSUE TITLE
Support EIP 1191 - different address checksums for different chains

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/solidity#8498]
## Description

- Support for different checksum encodings regarding https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md

## Environment

- Compiler version: latest
- Target EVM version (as per compiler settings): any
- Framework/IDE (e.g. Truffle or Remix): any
- EVM execution environment / backend / blockchain client: no Ethereum Main clients
- Operating system: any

## Steps to Reproduce

```solidity
contract X {
    address x = 0x1820a4b7618bde71dce8cdc73aab6c95905fad24;
}
```

Throws
```
SyntaxError: This looks like an address but has an invalid checksum. Correct checksummed address: "0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24". If this is not used as an address, please prepend '00'. For more information please see https://solidity.readthedocs.io/en/develop/types.html#address-literals
    address x = 0x1820a4b7618bde71dce8cdc73aab6c95905fad24;
                ^----------------------------------------^

Compilation failed. See above.
```

**Comment by chriseth** [comment]
Do you have any proposed solution on how to denote addresses of other chains?

**Comment by ilanolkies** [comment]
I’m not sure... sorry

**Comment by ilanolkies** [comment]
What about adding network id to the settings? Where you choose evm version.

**Comment by axic** [comment]
> Do you have any proposed solution on how to denote addresses of other chains?

Please note that currently we have no notion of other chains at all, `EVMVersion` follows "mainnet" versions only.
