### ISSUE TITLE
Introduce "Solidity" alias for emscripten module

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8536]
Transitional issue for https://github.com/ethereum/solidity/issues/8157

**Comment by ekpyron** [comment]
@axic: @chriseth said you were working on this already, so I unassigned myself and assigned you - let me know otherwise, then I can quickly do this.

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
