### ISSUE TITLE
Minimum compiler version checks for > not working

### ISSUE THREAD

**Issue by mijovic** [ethereum/solidity#8537]
## Description

- pragma solidity >0.4.0 doesn't work with script that checks if docs are compiled with minimal version.
- Also new changes will not have released compiler yet, so skip them as there is another test that checks against current version of compiler

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by chriseth** [comment]
This is a blocker for #3835 so I'm taking it into the sprint.

**Comment by mijovic** [comment]
I will fix this
