### ISSUE TITLE
[Inheritance] Error on library functions that are "virtual"

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8540]
## Description

The following should result in a compiler error (the `virtual` keyword is meaningless because libraries cannot be inherited) but is silently ignored.

```
library L {
    function f() internal pure virtual returns (uint) { return 0; }
}
```

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by chriseth** [comment]
Place of implementation is probably bool TypeChecker::visit(FunctionDefinition const& _function)

**Comment by chriseth** [comment]
This is a breaking change, but I guess no real smart contract would have used it anyway.
