### ISSUE TITLE
Refactor checks on Contracts

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8541]
The type checker contains multiple occurrences of
```
		if (noErrors)
			for (Source const* source: m_sourceOrder)
				if (source->ast)
					for (ASTPointer<ASTNode> const& node: source->ast->nodes())
						if (ContractDefinition* contract = dynamic_cast<ContractDefinition*>(node.get()))
```

These should be extracted into some helper "forAllContracts" or something like that, which takes a lambda.

**Comment by Reuvens** [comment]
Hi @chriseth ,
Are you talking about libsolidity/interface/CompilerStack.cpp ? 
I only see 2 occurrences of it, or are you talking globally, if so, where? 

Thanks,
Reuven.

**Comment by chriseth** [comment]
Yeah, you are right, it is probably not too common. Thanks for checking!
