### ISSUE TITLE
Function modifier effect on return value

### ISSUE THREAD

**Issue by mehranshakeri** [ethereum/solidity#8545]
## Description

Having the following code

```
pragma solidity ^0.6.4;

contract TestModifier {

    mapping (address => bool) public authorities;
    mapping (address => address) public authorized;

    modifier onlyAuthorized(address _user) {
        require(authorities[authorized[_user]], "Requires authorization");
        _;
    }

    // returns false as expected
    function getStatus1(address _user) external view returns (bool) {
        return authorities[authorized[_user]];
    }

    // returns true but expect to fail with error
    function getStatus2(address _user) external view onlyAuthorized(_user) returns (bool) {
        return authorities[authorized[_user]];
    }

    // returns true but expect to fail with error
    function getStatus3(address _user) external view onlyAuthorized(_user) returns (bool) {
        return true;
    }
}

```
Given any address as the input to getStatus functions, I expect to see false as the return value for the first one and an error for the other two. However, `getStatus1` returns false and two others return true.

This is happening in the Ropsten test net but everything is correct in Kovan. I didn't try it in the main net though.

Also the thread on [stackexchange](https://ethereum.stackexchange.com/questions/80870/function-modifier-effect-on-return-value?noredirect=1)

## Environment

- Compiler version: v0.6.4+commit.1dca32f3
- Target EVM version (as per compiler settings): Not sure, deployed in Ropsten test net
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: 
- Operating system:

## Steps to Reproduce

Here you have the deployed smart contract in Ropsten with the source code:
https://ropsten.etherscan.io/address/0x4457f104861f09240d09d857987290f928d09a1e

Load the smart contract on Remix for example and try calling functions `getStatus1`, `getStatus2`, `getStatus3` with any valid Ethereum address. e.g. `0x2e2d61Cb7725b5d381879030d308508d26759aDC`

Kovan deployment
https://kovan.etherscan.io/address/0x552748c93a38939f1330629a3016a97accd6d0d9#code

## NodeJS Test

```
const Web3 = require('web3');

const abi = [{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"authorities","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"authorized","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"getStatus1","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"getStatus2","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"getStatus3","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
const address = "0x2e2d61Cb7725b5d381879030d308508d26759aDC";

/************ TESTING Ropsten ***********/
const web3Ropsten = new Web3("https://ropsten.infura.io/v3/17a6aa646dfb46ab880ff2c8aa24cbea");
const contractRopsten = new web3Ropsten.eth.Contract(abi, "0x4457f104861f09240d09d857987290f928d09a1e");

contractRopsten.methods.getStatus1(address).call({}, function(error, result){
    console.log("Ropsten::status1: ", result);
});
contractRopsten.methods.getStatus2(address).call({}, function(error, result){
    console.log("Ropsten::status2: ", result);
});
contractRopsten.methods.getStatus3(address).call({}, function(error, result){
    console.log("Ropsten::status3: ", result);
});

/************ TESTING Kovan ***********/
const web3Kovan = new Web3("https://kovan.infura.io/v3/17a6aa646dfb46ab880ff2c8aa24cbea");
const contractKovan = new web3Kovan.eth.Contract(abi, "0x552748c93a38939f1330629a3016a97accd6d0d9");

contractKovan.methods.getStatus1(address).call({}, function(error, result){
    console.log("Kovan::status1: ", result);
});
contractKovan.methods.getStatus2(address).call({}, function(error, result){
    if (error) {
        console.error("Kovan::status2: ", error.message);
    } else {
        console.log("Kovan::status2: ", result);
    }
});
contractKovan.methods.getStatus3(address).call({}, function(error, result){
    if (error) {
        console.error("Kovan::status3: ", error.message);
    } else {
        console.log("Kovan::status3: ", result);
    }
});

```

**Comment by leonardoalt** [comment]
I tried it on Remix and it goes exactly how you expect. Did you try it there too?

**Comment by mehranshakeri** [comment]
Yes, I'm using Remix. Have you used my smart contract? I expect none of them to return `true`.

**Comment by leonardoalt** [comment]
Yes, they don't. The first one returns `false` and the other two revert.

**Comment by leonardoalt** [comment]
> Yes, I'm using Remix. Have you used my smart contract? I expect none of them to return `true`.

Do you mean on Remix or Ropsten?

**Comment by mehranshakeri** [comment]
> > Yes, I'm using Remix. Have you used my smart contract? I expect none of them to return `true`.
> 
> Do you mean on Remix or Ropsten?

Using Remix to call the smart contract deployed on Ropsten. I have the same issue calling it from my NodeJS backend so I don't think Remix is the issue. I also deployed it on Kovan and it is fine there.

Our first conclusion was that there must be something different between Ropsten and Kovan and first thought was it's most probably the compiler issue.

**Comment by leonardoalt** [comment]
I don't think it's a compiler issue, as the bytecode is the same regardless which chain you're running on. Did you deploy the same bytecode on both chains?

**Comment by mehranshakeri** [comment]
I just tried it with Javascript VM in remix and it's fine but using Ropsten (via meta mask) it returns wrong results.

**Comment by leonardoalt** [comment]
Right, but how was it compiled and deployed?

**Comment by mehranshakeri** [comment]
> I don't think it's a compiler issue, as the bytecode is the same regardless which chain you're running on. Did you deploy the same bytecode on both chains?

Yes, I used Remix for deployment and the same source code. I will try it again now for Kovan and share the results here

**Comment by mehranshakeri** [comment]
> Right, but how was it compiled and deployed?

Remix

**Comment by mehranshakeri** [comment]
> I don't think it's a compiler issue, as the bytecode is the same regardless which chain you're running on. Did you deploy the same bytecode on both chains?

Here is a Kovan deployment with the source code attached:
https://kovan.etherscan.io/address/0x552748c93a38939f1330629a3016a97accd6d0d9#code

**Comment by leonardoalt** [comment]
Bytecodes are the same. Are the testnets running on the same EVM version?

**Comment by mehranshakeri** [comment]
> Bytecodes are the same. Are the testnets running on the same EVM version?

I'm not sure how can I verify that.

**Comment by nikola-matic** [comment]
Given the discussion here, and especially on the linked stackexchange thread, this doesn't seem to be a compiler bug, nor is there a valid repro for the supposed bug, so I'll be closing the issue.
