### ISSUE TITLE
“TypeError” for a simple program causing failure to compile, “Type address is not implicitly convertible to expected type address payable.”

### ISSUE THREAD

**Issue by KyleBenzle** [ethereum/solidity#8546]
## Prerequisites

Truffle v5.1.15 (core: 5.1.15)
Node v10.15.2

## Description

(From Lynda Etheruem course) 

I get this error: 
TypeError: Type address is not implicitly convertible to expected type address payable.
    receiver = _receiver;
               ^-------^

when trying to compile the following:

```

pragma solidity ^0.5.16;

contract ApprovalContract {

  address payable public sender;
  address payable public receiver;
  address constant public approver = 0xd268143B6FBD9BC6533F778052710C962eaAa68C;


  function deposit(address _receiver) external payable {
    require(msg.value > 0);
    sender = msg.sender;
    receiver = _receiver;
  }

    function viewApprover() external pure returns(address) {
    return(approver);
  }

   function approve() external {
    require(msg.sender == approver);
    receiver.transfer(address(this).balance);
  }

}

```

**Comment by chriseth** [comment]
`receiver` is payable, `_receiver` is not. One fix is to change the deposit function to ` function deposit(address payable _receiver) external payable {`
