### ISSUE TITLE
Type Errors: specifying calldata, memory keywords as parameters

### ISSUE THREAD

**Issue by CrackerHax** [ethereum/solidity#8547]
If the compiler already knows what the storage type is supposed to be for a particular variable then why does it even have to be specified in code? Am I the only one who thinks this is a useless "feature"?

    TypeError: Data location must be "calldata" for parameter in external function, but "memory" was given.
    TypeError: Data location must be "memory" for parameter in function, but none was given.

The only exception is when you must choose between memory or storage (which still seems a little dubious).

    TypeError: Data location must be "storage" or "memory" for variable, but none was given.

If it is an expected type then the compiler shouldn't need a keyword here:

    TypeError: Type struct MyStruct memory is not implicitly convertible to expected type struct MyStruct storage pointer.

All this is strange, non-intuitive and redundant. These things should be going on under the hood, not requiring the programmers attention.

**Comment by chriseth** [comment]
This has been an issue in earlier language versions where people would make wrong assumptions about the data location of variables. Furthermore, we plan to allow public functions to accept calldata variables. Furthermore, I personally like the pythonic way of "better explicit than implicit", so this is certainly also a style issue.

I don't understand the last context of the last error message - could you provide an example there?

**Comment by chriseth** [comment]
Nowadays, you can even choose, so I'm closing this. The general idea is to be explicit and not make any assumptions about what alternatives are left after analysis.
