### ISSUE TITLE
Utility methods: broken ownership

### ISSUE THREAD

**Issue by randomnetcat** [ethereum/solidity#8555]
Take the following template in `libsolutil/CommonData.h` as an example:
```cpp
/// Concatenate the contents of a container onto a vector, move variant.
template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U&& _b)
{
	std::move(_b.begin(), _b.end(), std::back_inserter(_a));
	return _a;
}
```

The intent here appears to be able to move out of temporary ranges.

There are some issues with this:

First, `U&&` can deduce to (for instance) `std::vector<T>&` because `U&&` is a forwarding reference. This would result in moving out of elements in an lvalue range, which is not desirable. This can be fixed by constraining on `is_rvalue_reference_v<U&&>`.

However, the deeper issue is that the lifetime of a range does not necessarily correspond to the lifetime of its elements. Consider (using C++20's `span`):
```cpp
std::vector<T> vec = /* somehow initialize */;
std::vector<T> other = /* somehow initialize */;

std::span<T> s = vec;
other += std::move(s); // BUG - calls rvalue reference overload, moves out of elements owned by vec, although they will continue living past this line
```

This is harder to fix - it requires knowledge of the meanings of types.

**Comment by chriseth** [comment]
You are right! I think I actually would expect `other += std::move(s)` to destroy the contents of `vec`.
