### ISSUE TITLE
[SolYul] Check which `revert()`s should be `invalid()`

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#8556]
There are some cases in the code generator where `revert` is used but it should rather be `invalid`.

**Comment by axic** [comment]
@leonardoalt do you have an example case?

**Comment by leonardoalt** [comment]
@axic Should have posted then... don't remember right now. Will take a look. Maybe @chriseth knows what I was talking about?

**Comment by chriseth** [comment]
There are quite some cases - array allocation for example (unless called from abi decoder).
