### ISSUE TITLE
[Test] add ens contracts to external tests

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8557]
https://github.com/ensdomains/ethregistrar

**Comment by chriseth** [comment]
Most of them seem not to be upgraded to 0.6 yet, though, but we should maybe get in contact.

**Comment by cameel** [comment]
Looks like [ethregistrar](https://github.com/ensdomains/ethregistrar), [ens](https://github.com/ensdomains/ens) and possibly some other repos got consolidated into [ens-contracts](https://github.com/ensdomains/ens-contracts) and all of it seems to be on 0.8.4 now.

In that case just switching the ens ext test to this new repo should solve this.
