### ISSUE TITLE
Debugging info for immutables.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8562]
The LinkerObject should contain information about the location of references to and maybe assignments to immutables.

Part of #3835

**Comment by Marenz** [comment]
Is this already done? I see there is 

```
	/// Map from hashes of the identifiers of immutable variables to a list of offsets into the bytecode
	/// that refer to their values.
	std::map<u256, std::vector<size_t>> immutableReferences;
```

in the file

**Comment by Marenz** [comment]
@ekpyron you added that code.. do you know? ^

**Comment by ekpyron** [comment]
@Marenz The information is basically already there, but it still needs to actually be part of the debugging output.

**Comment by Marenz** [comment]
The output should be basically like `linkReferences` is done

**Comment by ekpyron** [comment]
FYI: The ``immutableReferences`` map for now only uses hashes, so we will also probably have to store the full names corresponding to each hash. The output should tell you for each immutable the offsets of all its occurrences.

**Comment by chriseth** [comment]
Just to clarify: The references should be in the runtime bytecode only, and not in the creation bytecode, right?

**Comment by ekpyron** [comment]
Yep

**Comment by chriseth** [comment]
Hm, we should also make both library references and immutable references part of the metadata!

**Comment by ekpyron** [comment]
> Hm, we should also make both library references and immutable references part of the metadata!

I agree, I was actually surprised that the link references aren't already in there.

**Comment by chriseth** [comment]
Implemnted in https://github.com/ethereum/solidity/pull/8581
