### ISSUE TITLE
[solc] More precise error message for private payable functions

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8577]
## Description

```
$ cat input.sol
abstract contract C0 {
        function c0func0() private payable
        {

        }
}

$ solc input.sol
Error: Internal functions cannot be payable.
 --> t:5:2:
  |
5 |     function c0func0() private payable
  |  ^ (Relevant source part starts here and spans across multiple lines).
```

The error message should read `Private functions cannot be payable`

## Environment

- Compiler version: latest develop

**Comment by chriseth** [comment]
A private function is an internal function :)

**Comment by bshastry** [comment]
> A private function is an internal function :)

Ah, now I realize, `private` offers a stronger (stricter) visibility than internal and hence errors flagged for `internal` apply to `private` as well.

However, we could still reword the error message since `private` is a keyword just to be clear :-)

**Comment by axic** [comment]
If we adjust the error message, I suggest to change it from
> Internal functions cannot be payable.

to

> Internal and private functions cannot be payable.

@chriseth @bshastry @ekpyron comments?

**Comment by ekpyron** [comment]
Why not :-).
