### ISSUE TITLE
Install issue with webthree_umbrella.

### ISSUE THREAD

**Issue by simondlr** [ethereum/solidity#86]
Using: https://github.com/ethereum/webthree-umbrella/wiki/building.

```

CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    EthPolicy


CMake Error at CMakeLists.txt:8 (eth_policy):
  Unknown CMake command "eth_policy".


-- Configuring incomplete, errors occurred!

```

**Comment by LefterisJP** [comment]
Which cmake version do you have?
Can you post a bigger log?

**Comment by simondlr** [comment]
There's no bigger log.

```
Simon-2:solidity simon$ mkdir build
Simon-2:solidity simon$ cd build/
Simon-2:build simon$ cmake ..
CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    EthPolicy


CMake Error at CMakeLists.txt:8 (eth_policy):
  Unknown CMake command "eth_policy".


-- Configuring incomplete, errors occurred!
```

cmake 3.3.1.

To clarify, I want to build only Solidity (per those instructions at the top).

**Comment by LefterisJP** [comment]
Hmm only solidity while you have cloned the umbrella project?

The solidity directory you are in, is in the umbrella project or is it a standalone project? Have you built the dependencies?

**Comment by LefterisJP** [comment]
I added an alternate way to build the repos in the wiki. It does not utilize the umbrella project but clones/updates only the repos required for a project in the current directory and then builds them. You can also give that a try if you want to build only solidity:

https://github.com/ethereum/webthree-umbrella/wiki/building

**Comment by simondlr** [comment]
The helpers worked perfectly! Thank you!

**Comment by LefterisJP** [comment]
:+1:

**Comment by simondlr** [comment]
@LefterisJP What happened to the helper instructions?

**Comment by LefterisJP** [comment]
What do you mean @simondlr ? If it's the link then I think it's just the wiki link changed. It should be here: https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building

**Comment by simondlr** [comment]
Ah, thank you @LefterisJP! I didn't think to look under the Linux pages!

**Comment by dipanjan** [comment]
I am facing the same issue as @simondlr while building `solidity-v0.3.5`. Any help would be appreciated.
