### ISSUE TITLE
[solc] ICE: solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp(1193): Throw in function virtual void solidity::frontend::IRGeneratorForStatements::endVisit(const solidity::frontend::Identifier &)

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#8604]
solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp(1193): Throw in function virtual void solidity::frontend::IRGeneratorForStatements::endVisit(const solidity::frontend::Identifier &)

## Description

triggered by:
- test/libsolidity/syntaxTests/tryCatch/returns.sol
- test/libsolidity/syntaxTests/tryCatch/catch_low_level.sol
- test/libsolidity/syntaxTests/tryCatch/catch_error_named.sol
- test/libsolidity/syntaxTests/tryCatch/returns_memory.sol
- test/libsolidity/syntaxTests/tryCatch/two_catch_clauses.sol
- test/libsolidity/semanticTests/tryCatch/nested.sol
- test/libsolidity/semanticTests/tryCatch/structuredAndLowLevel.sol
- test/libsolidity/semanticTests/tryCatch/structured.sol
- test/libsolidity/semanticTests/tryCatch/simple.sol
- test/libsolidity/semanticTests/tryCatch/return_function.sol
- test/libsolidity/semanticTests/tryCatch/lowLevel.sol

## Environment

- current develop

## Steps to Reproduce

```sh
./solc --ir <file>
```

**Comment by chriseth** [comment]
Likely be closed by #8246
