### ISSUE TITLE
[solc] ICE: solidity/libsolidity/codegen/ir/IRVariable.cpp(92): Throw in function std::__1::string solidity::frontend::IRVariable::name() const

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#8606]
solidity/libsolidity/codegen/ir/IRVariable.cpp(92): Throw in function std::__1::string solidity::frontend::IRVariable::name() const

## Description

triggered by:
- test/libsolidity/semanticTests/tryCatch/invalid_error_encoding.sol

## Environment

- current develop

## Steps to Reproduce

```sh
./solc --ir <file>
```

**Comment by axic** [comment]
@aarlt could add minimal examples to each of these issues?

**Comment by chriseth** [comment]
No please don't! Let's just implement it based on the failing tests.
