### ISSUE TITLE
Bug in `abi.decode`

### ISSUE THREAD

**Issue by sobolev-igor** [ethereum/solidity#8615]
## Description

I'm trying to verify signature and parse it using `abi.decode`, not assembly. However, `abi.decode` fails for no reason.

## Environment

- Compiler version: 0.6.4
- Target EVM version (as per compiler settings): istanbul
- Framework/IDE (e.g. Truffle or Remix): any
- EVM execution environment / backend / blockchain client: ganache-cli, remix EVM
- Operating system: macOS

## Steps to Reproduce

```
contract Test {
    function getUserFromSignature(
        bytes memory signature
    )
        public
        returns (address)
    {
        require(signature.length == 65, "Wrong signature length!");
        bytes32 r;
        bytes32 s;
        uint8 v;
        (r, s, v) = abi.decode(signature, (bytes32, bytes32, uint8));
    }
}
```

I'm calling function with `"0x49023da0a11914ff15521e582a11c38150d5d361266161ca481ee3fc55cc5f7c16d77c35a8d4d037bfebda015c8194d09fb85d8f863bf16d9b7b8273fa8f8e851c"`.
I've tried to use `byte`, `bytes1` instead `uint8`, but it fails anyway.
I've tried to debug tx, seems like for some reason it compares `signature.length` with `0x60`, not with `0x41` and thus fails.

**Comment by chriseth** [comment]
ABI encoding always pads to multiple of 32 bytes, that's why it fails.

**Comment by sobolev-igor** [comment]
Hi, @chriseth! Thanks for the quick response.

But if i do `abi.decode(signature, (bytes32, bytes32, bytes32));` it fail also, so the only option is to add 31 bytes of zeroes when calling the function (i.e. to set `signature.length` to 96) and this does not seem the good option...

**Comment by chriseth** [comment]
I'm sorry, but `abi.decode` is meant for abi decoding, not for unpacking binary data. 

This is a perfect task for inline assembly and a random internet search resulted in the following, for example: https://gist.github.com/BjornvdLaan/e41d292339bbdebb831d0b976e1804e8

**Comment by sobolev-igor** [comment]
I've seen the assembly solution, but I do not want to use assembly in my code (but seems like I'll have to).

Thanks anyway!

**Comment by chriseth** [comment]
Assembly is really not that scary and dangerous as most people think. I actually am of the opinion that it is better to have reviewable user-supplied assembly routines than some compiler-internal routines that are much harder to find.

**Comment by axic** [comment]
> Assembly is really not that scary and dangerous as most people think.

This statement was more true when it was introduced. As we transition more over to Yul, the less scary it becomes.
