### ISSUE TITLE
[DOCS] [CHC] Clarification of limitations described in security-considerations.rst

### ISSUE THREAD

**Issue by ericr-aon** [ethereum/solidity#8622]
The Security Considerations document states that "Function calls are currently unsupported" by the CHC engine. Yet we can see that FunctionCall AST nodes are visited and processed if they are internal:

https://github.com/ethereum/solidity/blob/398c51598285dc16ea573fb00ddf8ec0b8500989/libsolidity/formal/CHC.cpp#L450-L480

Should this document be clarified to state that only internal functions are supported at this time? As is, this could be misunderstood to mean that the CHC engine lacks all function call support and is essentially useless right now.

**Comment by leonardoalt** [comment]
Yes, you're right :)
Support to internal function calls was recently added, and this was overlooked, thanks for bringing it up!
