### ISSUE TITLE
[SMTChecker] toZ3Expr throws

### ISSUE THREAD

**Issue by ericr-aon** [ethereum/solidity#8623]
## Description

Using the experimental SMTChecker pragma with a simple contract that defines a storage variable and inherits from another contract results in an error.

## Environment

- Compiler version: 0.6.5-develop.2020.4.1+commit.ff23f165.mod.Darwin.appleclang (with support for Z3)
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: MacOS

## Steps to Reproduce

Compiling the following results in an error:
```
pragma solidity >=0.5.0;
pragma experimental SMTChecker;

contract B {
  function b() public {}
}

contract A is B {
  uint public x;

  function a() public {
    b();
  }
}
```

```
Internal compiler error during compilation:
/[redacted]/libsolidity/formal/Z3Interface.cpp(202): Throw in function z3::expr solidity::frontend::smt::Z3Interface::toZ3Expr(const solidity::frontend::smt::Expression &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Wrong number of arguments (3) passed to function (declare-fun summary_0_function_b__6_7_0 (Int) Bool)
[solidity::util::tag_comment*] = Wrong number of arguments (3) passed to function (declare-fun summary_0_function_b__6_7_0 (Int) Bool)
```

**Comment by leonardoalt** [comment]
Thanks for reporting!
