### ISSUE TITLE
If an immutable state variable is never read, it can't be distinguished from a storage state variable

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#8625]
## Description

If an `immutable` state variable is declared, and set in the constructor, but never read in the deployed contract, the compiler output contains nothing to indicate that this variable is immutable.

Well, OK -- if the `storageLayout` output is used, then one could use that to determine it by checking whether the variable is missing from `storageLayout`.  But, `storageLayout` is experimental and may change in breaking ways in the future, so one shouldn't have to rely on that.

In any case, without using anything experimental, they're indistinguishable.  Details follow.

## Expected result (part 1)

The AST `VariableDeclaration` node type should include an `immutable` field, similar to the existing `constant` field, which indicates whether a variable is `immutable`.

## Actual result (part 1)

No such field exists; an `immutable` variable looks just like an ordinary state variable in the AST.

## Expected result (part 2)

If a variable is declared `immutable` but never read, it should still appear in `immutableReferences`, just with an empty array of references.

## Actual result (part 2)

Instead, it is omitted from `immutableReferences` entirely.

## Environment

- Compiler version: 0.6.5
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle
- Operating system: Linux Mint

## Steps to Reproduce

```solidity
pragma solidity ^0.6.5;

contract ImmutableTest {
  uint immutable it;
  uint ordinary;
  constructor(uint x) public {
    it = x;
  }
}
```

Then check the `ast` and `immutableReferences` in the compiler output; observe that there is nothing that would allow one to distinguish between the immutable variable `it` and the storage variable `ordinary`.

**Comment by chriseth** [comment]
It actually turns out that I implemented the import, but not the export. *facepalm*

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/8628

**Comment by haltman-at** [comment]
Thank you!
