### ISSUE TITLE
Export unlinked objects via json output

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#863]
It should be possible to use unlinked binary objects from the json compiler just as is possible in the C++ interface.

**Comment by VoR0220** [comment]
keeping an eye on this.

**Comment by levino** [comment]
This should be high priority. The current solc-js is unusable.

**Comment by axic** [comment]
Closed by #1387.

**Comment by levino** [comment]
When will this be released?

**Comment by chriseth** [comment]
Sorry, that was closed too early.

**Comment by axic** [comment]
I believe this is fixed with #1639. Please reopen if it isn't.
