### ISSUE TITLE
Provide ecrecover(bytes32 hash, bytes signature) overload

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#864]
The compiler should provide an overload of `ecrecover(bytes32 hash, bytes signature) returns (address)` for the ecrecover function

**Comment by axic** [comment]
Do you mean this https://gist.github.com/axic/5b33912c6f61ae6fd96d6c4a47afde6d?

**Comment by chriseth** [comment]
yes

**Comment by PhABC** [comment]
Sorry for the ping, status on this?
