### ISSUE TITLE
Empty (or with internal functions only) libraries emit bytecode

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8646]
```solidity
interface EmptyInt {
}

abstract contract AbstractContract {
}

library EmptyLib {
}

library OnlyInternalLib {
    function f() private {}
    function g() internal {}
}
```

```
======= emptylib.sol:AbstractContract =======
Binary:


======= emptylib.sol:EmptyInt =======
Binary:


======= emptylib.sol:EmptyLib =======
Binary:
607b6023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202abd1d6e90b4bd6a23e8ff545b61eae21fb24270be211e57587609d3c02b24ff64736f6c637827302e362e352d646576656c6f702e323032302e332e32312b636f6d6d69742e64353562626434610058

======= emptylib.sol:OnlyInternalLib =======
Binary:
607b6023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c2450cc5dcad9892551d1dd6bdcb464e092872ebe5c97bc2c78cc731144236b464736f6c637827302e362e352d646576656c6f702e323032302e332e32312b636f6d6d69742e64353562626434610058
```

The resulting binary for the library only has the constructor and the library-call-safety-switch and nothing else.

It could be confusing for developers to have a binary for library when it is not used. The question they may ask -- "Do I need to deploy this?"

Arguably not emitting a binary could be construed as another edge case, since we do emit an empty binary for empty contracts.

**Comment by chriseth** [comment]
"Do I need to deploy this" - the question should be answered by the deployment tool depending on whether the object has link references or not - not by the nature of the library to be linked to.

If you have a non-empty library but never call any of its public functions then you also do not need to deploy the library.

I would propose to close this issue.

**Comment by axic** [comment]
At the minimum this should be documented.

**Comment by chriseth** [comment]
Empty contracts also generate bytecode. Libraries with only internal functions also generate bytecode. You need to deploy a library when the linker requests it. This could be documented, but linking is not a feature people use nowadays...
