### ISSUE TITLE
cannot upgrade in ubuntu trusty

### ISSUE THREAD

**Issue by simpletechnology** [ethereum/solidity#865]
The following extra packages will be installed:
  solc
The following NEW packages will be installed:
  solc
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
188 not fully installed or removed.
Need to get 0 B/2,042 kB of archives.
After this operation, 15.3 MB of additional disk space will be used.
Do you want to continue? [Y/n](Reading database ... 82505 files and directories currently installed.)
Preparing to unpack .../solc_1%3a0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty_amd64.deb ...
Unpacking solc:amd64 (1:0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty) ...
dpkg: error processing archive /var/cache/apt/archives/solc_1%3a0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libsolidity.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/solc_1%3a0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-172-31-11-220:~$ ^C

**Comment by chriseth** [comment]
Please try if `sudo apt-get remove cpp-ethereum libethereum && sudo apt-get install solc`  helps

**Comment by chriseth** [comment]
Please also see this one here: https://github.com/ethereum/solidity/issues/851

**Comment by simpletechnology** [comment]
i follow that, and now libethereum throws error

ntu1_amd64.deb ...
Unpacking libethereum:amd64 (1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libethereum_1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libsolidity.so', which is also in package solc:amd64 1:0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~xenial
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libethereum_1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-172-31-11-219:~$

**Comment by simpletechnology** [comment]
sudo apt-get remove cpp-ethereum libethereum && sudo apt-get install solc 

does NOT help.

it gives this error;

The following extra packages will be installed:
  solc
The following packages will be REMOVED:
  alethzero cpp-ethereum eth ethkey ethminer ethvm libethereum libethereum-gui
  lllc mix-ide rlp
The following packages will be upgraded:
  solc
1 upgraded, 0 newly installed, 11 to remove and 27 not upgraded.
Need to get 2,044 kB of archives.
After this operation, 10.0 MB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu/ trusty/main solc amd64 1:0.3.6-0ubuntu1~trusty [2,044 kB]
Fetched 2,044 kB in 5s (385 kB/s) 
(Reading database ... 66653 files and directories currently installed.)
Removing cpp-ethereum:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Removing alethzero:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Removing mix-ide:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Removing ethvm:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Removing eth:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Removing ethkey:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Removing ethminer:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
(Reading database ... 66623 files and directories currently installed.)
Preparing to unpack .../solc_1%3a0.3.6-0ubuntu1~trusty_amd64.deb ...
Unpacking solc:amd64 (1:0.3.6-0ubuntu1~trusty) over (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
Replacing files in old package lllc:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/solc_1%3a0.3.6-0ubuntu1~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libsolidity.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-172-31-11-225:~$ ^C

**Comment by simpletechnology** [comment]
solc and libethereum have conflicting packages within them..... this needs to be fixed!

**Comment by simpletechnology** [comment]
cannot install libethereum & solc at the same time. is impossible. it's either install one, or the other!

**Comment by simpletechnology** [comment]
trying to overwrite '/usr/lib/libsolidity.so', which is also in package solc:amd64 1:0.3.6-0ubuntu1~trusty

**Comment by chriseth** [comment]
apt-get did not properly uninstall libethereum before installing solc. Please try

```
apt-get remove libethereum solc cpp-ethereum
```

and then

```
apt-get install solc
```

**Comment by codati** [comment]
hi,
i can't install solc and ethminer ?...

**Comment by chriseth** [comment]
Yes, you cannot have both at the same time, at the moment, sorry for the inconvenience.

**Comment by HaikelBenHmida** [comment]
@chriseth @codati @simpletechnology

Hi,

Try to execute this to resolve the probleme.

  rm /var/lib/dpkg/info/ethkey*
  rm /var/lib/dpkg/info/eth:*
  rm /var/lib/dpkg/info/ethm*
  rm /var/lib/dpkg/info/libeth*
  apt-get -f install

**Comment by francesco13** [comment]
Hi,

Thanks, that worked for me

**Comment by chriseth** [comment]
We just created new packages for the PPA, solidity and lll are no longer part of cpp-ethereum and libethereum and thus should not create a conflict anymore.

**Comment by codati** [comment]
thx fix for me
