### ISSUE TITLE
ICE in solidity::frontend::rootVariableDeclaration(const solidity::frontend::VariableDeclaration &) [Identifier is not referencing a variable declaration]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8653]
## Description

This contract:
```solidity
contract C {
    uint constant a = C;
    uint constant b = a;
    function f() public pure {
        assembly {
            let x := b
        }
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/ASTUtils.cpp(33): Throw in function const solidity::frontend::VariableDeclaration *solidity::frontend::rootVariableDeclaration(const solidity::frontend::VariableDeclaration &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Identifier is not referencing a variable declaration
[solidity::util::tag_comment*] = Identifier is not referencing a variable declaration
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators.  This one took about three weeks starting from a corpus collected from all past runs...

## Environment

- Compiler version:  0.6.3-develop.2020.2.10+commit.e8eb1f2d.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Hello @agroce Thank you very much for reporting this issue. As a general rule, only the latest release (currently `0.6.6`) gets minor bug fixes. Please consult the [security policy](https://github.com/ethereum/solidity/blob/develop/SECURITY.md#supported-versions) for more information.

Can you reproduce this bug on latest develop? If I am not mistaken, I believe this report is a duplicate of https://github.com/ethereum/solidity/issues/8418 that has been fixed by https://github.com/ethereum/solidity/pull/8480.

If this is incorrect, please let us know.

**Comment by agroce** [comment]
Will try, had kept a docker running older fuzzing for afl help + experimental integrity reasons.  I'll grab/compile latest

**Comment by agroce** [comment]
Building.  I'll fuzz latest master a while, too, from fresh corpus

**Comment by agroce** [comment]
Looks fixed.  Is solc, the solidity compiler commandline interface
Version: 0.6.7-develop.2020.4.10+commit.333322eb.Linux.clang

what I should be fuzzing?

**Comment by bshastry** [comment]
> Looks fixed.

Okay, I will close this issue in that case.

> Is solc, the solidity compiler commandline interface
> Version: 0.6.7-develop.2020.4.10+commit.333322eb.Linux.clang
> 
> what I should be fuzzing?

Sounds good :-)
