### ISSUE TITLE
[Inheritance] More precise error message when derived contract implicitly overrides two or more non-virtual base contract functions with identical name and I/O types

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8654]
## Description

```
contract CB1 {
        function foo() public pure returns (uint) { return 0; }
}
contract CB2 {
        function foo() public pure returns (uint) { return 1; }
}
contract C is CB1, CB2 {
}
```

outputs the following error post compilation

```
Error: Derived contract must override function "foo". Two or more base classes define function with same name and parameter types.
 --> t1:7:1:
  |
7 | contract C is CB1, CB2 {
  | ^ (Relevant source part starts here and spans across multiple lines).
Note: Definition in "CB1": 
 --> t1:2:2:
  |
2 | 	function foo() public pure returns (uint) { return 0; }
  | 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Definition in "CB2": 
 --> t1:5:2:
  |
5 | 	function foo() public pure returns (uint) { return 1; }
  | 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Perhaps, we should add that the two base contracts in question `CB1` and `CB2` must virtualize `foo` as well? Because asking the user to override as is does not make sense if the underlying base functions to be overridden are not virtual. Perhaps this is to be understood or read between the lines?

## Environment

- Compiler version: latest develop

**Comment by bshastry** [comment]
Closing because I think this is a duplicate of #8655

**Comment by bshastry** [comment]
Sorry, reopening this because it is a slightly different case (contract functions must be virtualized) so the error message may inform the user for clarity.

**Comment by cameel** [comment]
@bshastry I'd assume making the base function virtual is implied in the suggestion to override. You cannot override a non-virtual function.

Or do you meant that the error message should be different, based on whether the base functions are already virtual or not?
