### ISSUE TITLE
Unexplained "Assembly exception for bytecode"

### ISSUE THREAD

**Issue by mrice32** [ethereum/solidity#8656]
## Description

We made a small change to our code and noticed that the non-optimized compilation began failing. In particular, a `require()` (with message) statement seemed to be triggering the new failure. Our codebase is fairly large, but [here](https://github.com/UMAprotocol/protocol/tree/solidity_compilation_example) is a branch where the issue is present. In particular, [this new line](https://github.com/UMAprotocol/protocol/blob/e527ca542479e79a593cc249da6eac5c8b1c86d5/core/contracts/oracle/implementation/VoteTiming.sol#L21) seemed to cause the problem. Even more surprising, the compilation begins to succeed again when we removed the require message. I've reproduced this error in a much more minimal example below.

## Environment

- Compiler version: 0.6.6
- Target EVM version (as per compiler settings): default for compiler
- Framework/IDE (e.g. Truffle or Remix): Truffle, but we were able to reproduce the example below in remix as well.
- EVM execution environment / backend / blockchain client: N/A -- this is a compilation failure
- Operating system: Mac OS X 10.15.3

## Steps to Reproduce

Compile the below example with optimization off.

```solidity
pragma solidity ^0.6.0;

pragma experimental ABIEncoderV2;


contract Ownable {
    address private _owner;

    modifier onlyOwner() {
        require(msg.sender == _owner, "Ownable: caller is not the owner");
        _;
    }

    function renounceOwnership() public onlyOwner {
        _owner = address(0);
    }
}


library VoteTiming {
    function init(uint phaseLength) internal pure {
        require(phaseLength > 0, "Phase length can not be zero");
    }
}


contract Voting is Ownable {
    constructor(uint _phaseLength) public {
        VoteTiming.init(_phaseLength);
    }
}
```

Please note that the code above is somewhat nonsensical. It has the ABIEncoderV2 pragma despite not needing it (the code that originally had the error *did* need/use ABIEncoderV2). It includes a fairly random assortment of functions that don't really have anything to do with one another. These are just artifacts of stripping out the pieces not necessary to reproduce the error.

If you change almost anything about the example, the compilation begins to succeed:
- Removing either `require` message.
- Removing `ABIEncoderV2`.
- Removing the `onlyOwner` modifier from the `renounceOwnership()` method.

Please let me know if there's any other information you need!

**Comment by Marenz** [comment]
The exact exception here is 
```
assertThrow(m_tagPositionsInBytecode[size_t(i.data())] == size_t(-1), AssemblyException, "Duplicate tag position.");
```

In libevmasm/Assembly.cpp:688

**Comment by Marenz** [comment]
The problem seems to be that we're adding the function `array_storeLengthForEncoding_t_string_memory_ptr_fromStack` twice thus triggering the assert that checks for duplicate tags.

The addition is triggered from two positions in the code:
* libsolidity/codegen/Compiler.cpp:49
* libsolidity/codegen/Compiler.cpp:39
