### ISSUE TITLE
Comments in solidity files not parsed correctly

### ISSUE THREAD

**Issue by pklinger** [ethereum/solidity#8660]
When parsing any solidity contract, that contains a comment (either single line // or multi-line /* */) I am getting the following error:

`{"contracts":{},"errors":[{"component":"general","formattedMessage":"Contract.sol:1:2569: ParserError: Function, variable, struct or modifier declaration expected.\n ... someLastlineOfMySolContract));        _;    }}\n                                        ^\n","message":"Function, variable, struct or modifier declaration expected.","severity":"error","sourceLocation":{"end":2568,"file":"Contract.sol","start":2568},"type":"ParserError"}],"sources":{}}`

When deleting the comments out manually or by regex, I'm not facing this issue anymore.

Can someone reproduce this?

**Comment by leonardoalt** [comment]
Can you give more details about how you're running it? Is it via `solc-js`? Using `--standard-json`?
Without that it's hard to try and reproduce it. Comments work fine for me in general.
