### ISSUE TITLE
[DOC] Some ideas for the readthedocs style

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8661]
We should iterate on our style for readthedocs. The style of the brownie documentation looks nice: https://eth-brownie.readthedocs.io/en/latest/

Two items I especially like about that:
 - second level in the TOC is expanded by default
 - it has a "dark mode"

**Comment by axic** [comment]
I like the TOC, but not a personal fan on dark modes (it hurts my eyes more than white, though I have a the automatic "blue filter" enabled in macOS).

**Comment by chriseth** [comment]
Should have clarified: it has a toggle switch for dark mode. @iamdefinitelyahuman said he will create a PR here :)

**Comment by chriseth** [comment]
Dark mode has been implemented and restructuring the TOC is done in #8715
