### ISSUE TITLE
Running `solidity-upgrade` doesn't print error list 

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum/solidity#8662]
I'm trying out the `solidity-upgrade` tool against the [argent repo](https://github.com/argentlabs/argent-contracts) and having a number of issues:

1. Pragma directive not upgraded, while [documentation suggests it should](https://solidity.readthedocs.io/en/latest/using-the-compiler.html#example)

```
$ solidity-upgrade --verbose base/Owned.sol
...
Error: Source file requires different compiler version (current compiler is 0.6.7-develop.2020.4.14+commit.accd8d76.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
  --> base/Owned.sol:16:1:
   |
16 | pragma solidity ^0.5.4;
   | ^^^^^^^^^^^^^^^^^^^^^^^

Analyzing and upgrading base/Owned.sol.


After upgrade:

Found 2 errors.
Found 0 upgrades.
```

2. Changing the pragma above manually, and rerunning the upgrade now reports one error left but even with `--verbose` flag it is not printed
```
$ solidity-upgrade --verbose base/Owned.sol
..
Analyzing and upgrading base/Owned.sol.

After upgrade:

Found 1 errors.
Found 0 upgrades.
```

3. `--allow-paths` doesn't work. Folder structure as follows:
```
| contracts
      | base
             Managed.sol
             Owned.sol 
```
where `Managed` imports `Owned` and running `solidity-upgrade` in `\contracts`:
```
$ solidity-upgrade --verbose base/Managed.sol --allow-paths base
...
Error: Source "base/Owned.sol" not found: File outside of allowed directories.
  --> base/Managed.sol:17:1:
   |
17 | import "./Owned.sol";
   | ^^^^^^^^^^^^^^^^^^^^^

Analyzing and upgrading base/Managed.sol.


After upgrade:

Found 2 errors.
Found 0 upgrades.
```

**Comment by hrkrshnn** [comment]
For point 2, I think only errors that can be upgraded get printed.

**Comment by elenadimitrova** [comment]
But shouldn't all errors it detects be printed still?

**Comment by hrkrshnn** [comment]
For the final message, i.e., 

```
After upgrade:

Found 2 errors.
Found 0 upgrades.
```

Those error messages will not be printed. This is something that can be easily fixed, though. 

Also, warnings are not printed, but they are included in the count.

My old comment is incorrect. Errors (both upgradable and non-upgradable) will be shown. I believe, in your case the "1 error" is actually a warning.

**Comment by hrkrshnn** [comment]
For 1. I don't see any code for pragma upgrade in `tools/solidityUpgrade/*` Maybe I'm missing something.

**Comment by hrkrshnn** [comment]
About 1. I talked with Erik, it seems that there is no pragma upgrades possible currently. The one in documentation was done manually.

For 3. You probably already know this, `--allow-paths .` should fix your problem. I'll look why `base` doesn't work.
