### ISSUE TITLE
[SMTChecker] Properly handle constants

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8669]
```
pragma experimental SMTChecker;

contract C {
  uint constant GWEI = 1e9;
  function f() public payable {
    uint tmp = msg.value / GWEI;
  }
}
```

results in

```
Warning: Unused local variable.
 --> div.sol:6:5:
  |
6 |     uint tmp = msg.value / GWEI;
  |     ^^^^^^^^

Warning: Division by zero happens here
 --> div.sol:6:16:
  |
6 |     uint tmp = msg.value / GWEI;
  |                ^^^^^^^^^^^^^^^^
Note:   for:
  <result> = 0
  GWEI = 0
  msg.value = 0
  tmp = 0

Note: Callstack: 
Note: 
```

**Comment by leonardoalt** [comment]
The CHC engine actually can handle constants, but it doesn't check for overflow/underflow.

**Comment by leonardoalt** [comment]
@axic what exactly is this issue referring to?
The constants/checks from the initial example are now supported. What is not supported:
```
uint constant x = 2;
uint constant y = x ** 10;
```
The SMTChecker does not apply constant propagation and `y` will not be seen as a constant, but I'm not sure we can/should actually do that.

**Comment by leonardoalt** [comment]
On the other hand, having some support to constant propagation on the `smtutil::Expression` level wouldn't be too hard.

**Comment by leonardoalt** [comment]
I think this would require too much redundant work in the SMTChecker and we shouldn't do it. Solidity should have constant propagation instead.
