### ISSUE TITLE
[SMTChecker] Runtime error: reference binding to to null pointer of type `const char*`

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8674]
## Description

```
pragma experimental SMTChecker;
contract C
{
        uint a;
        function f(uint x) public { f(0); f; }
        function g() public { f(1); f(0); }
}
```

throws the runtime error here

https://github.com/ethereum/solidity/blob/95349b36349818288638521e4156cd1a40d6be77/libsolidity/formal/Z3Interface.cpp#L240

probably because the referenced vector member may have been uninitialized because an earlier for loop that was supposed to initialize the said vector was not taken for some reason

https://github.com/ethereum/solidity/blob/95349b36349818288638521e4156cd1a40d6be77/libsolidity/formal/Z3Interface.cpp#L229-L230

## Environment

- Compiler version: latest develop

**Comment by leonardoalt** [comment]
@bshastry I can't reproduce it. Can you still?

**Comment by bshastry** [comment]
I can only reproduce it via undefined behavior sanitizer i.e., `CXXFLAGS=-fsanitize=undefined`

**Comment by leonardoalt** [comment]
Can you check if https://github.com/ethereum/solidity/pull/8748 fixes it?
