### ISSUE TITLE
Document .gitattributes for syntax highlighting

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8676]
See https://github.com/ethereum/solidity/issues/2681#issuecomment-355277311 ?

Probably as part of the "style guide" section.

Closes #2681.

**Comment by cameel** [comment]
Is this issue still relevant now that the full support for highlighting `.sol` files has been added (see https://github.com/ethereum/solidity/issues/2681#issuecomment-699548802)?

**Comment by axic** [comment]
I think it is useful to have a single line, because `.gitattributes` can be used out of github. The issue has been "solved" for github, which can also be mentioned.

**Comment by NunoFilipeSantos** [comment]
Hi! Looks like this issue was solved.
