### ISSUE TITLE
Remove AppVeyorBot Comments

### ISSUE THREAD

**Issue by Denton-L** [ethereum/solidity#868]
I'm not sure if this is possible but I want to suggest that we disable the AppVeyorBot from commenting on PRs.

I feel that it doesn't really add anything of value because you can check the build status, anyway, by looking at the bottom of the page. In fact, it's more of an annoyance because it just tends to spam the conversation with build statuses which makes having real conversations more difficult.

**Comment by bobsummerwill** [comment]
I quite like it myself, but sure, we can remove it if that's easy enough and if people don't like it.

**Comment by Denton-L** [comment]
Well, I don't want to feel like I'm unilaterally making this decision. How about we leave this issue up for a few days and see if there's any objection to removing them?

**Comment by chriseth** [comment]
Please remove it, it really clutters the pull request page. If you want to know the build status, you can always look at the end of the page.
Also it resets the "all comments read" state of the pull request, which is equally annoying.

**Comment by Denton-L** [comment]
@bobsummerwill, I don't think there's any resistance to this issue. You can probably remove it.

**Comment by bobsummerwill** [comment]
I agree.    It's on the backlog with the hundreds of other issues :-)

If you can manage to work out what tweaks to the `.yml` file are required for that, please do let me know, and/or make a PR!
