### ISSUE TITLE
[evmone] Consistent versions across platforms

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8682]
## Description

Motivated by https://github.com/ethereum/solidity/pull/8651 that upgrades evmone selectively for Windows only. 

In the past, there were multiple PRs for upgrading evmone. Example
  - https://github.com/ethereum/solidity/pull/7655 upgraded evmone to 0.3.0 in all Linux based CIs but not Windows, OSx and Linux test suite
  - https://github.com/ethereum/solidity/pull/7748 upgraded evmone to 0.3.0 for Windows, OSx, and the Linux test suite (but not docker CIs based on Linux)

This situation presents maintenance difficulties because one needs to keep track of which platform uses which version of evmone and in case of Linux which version is used by the test suite (soltest) and upstream Linux test CIs.

@Marenz proposed writing a script that applies version changes in a single PR across all platforms. Perhaps this is better solution than refactoring docker files because the latter only concern CIs but we need a solution that upgrades Windows and OSx dependencies as well.

**Comment by samuelmonday699** [comment]
Hi let me know if you need any help
