### ISSUE TITLE
isoltest: throw failure if input can be compiled via yul (--ir) but was marked as `compileViaYul: false`

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8686]
Idea from https://github.com/ethereum/solidity/pull/8554#issuecomment-614326427

**Comment by axic** [comment]
@ekpyron would this be complicated to add?

**Comment by ekpyron** [comment]
Good idea! And shouldn't be complicated to do at all.

**Comment by mijovic** [comment]
I am working on this
