### ISSUE TITLE
Re-introduce keywords "constant" and "payable" to maintain interoperability with geth console

### ISSUE THREAD

**Issue by gsalzer** [ethereum/solidity#8690]
## Abstract, Motivation, Specification

Please re-introduce `constant` and `payable` as deprecated keywords in the json-ABI (see #4755) and drop them at a later point. These keywords have been dropped in `soldidity 0.6.x`, which breaks the interoperability with the `geth` console in its current versions. For some reason, the `geth` console still uses `web3.js 0.20.1`, which depends on these keywords (see #8065 and [geth#20760](https://github.com/ethereum/go-ethereum/issues/20760)).

## Backwards Compatibility

Re-introducing the keywords does not break anything. On the contrary.

**Comment by axic** [comment]
To me it seems like a better idea updating geth, than re-introducing deprecated features, which took years to get rid of.

**Comment by gsalzer** [comment]
Are we talking of the same thing? I'm referring to the latest version of `geth` that does not work with the latest version(s) of `solidity`. As these are two flagships of the Ethereum ecosystem, this situation should be alarming.

Instead, the `geth` people argue that for the moment they cannot/don't want to get away from web3c 0.x [geth#20760](https://github.com/ethereum/go-ethereum/issues/20760), and the `solidity` people insist that now is the right moment to clean up their code. 

As an outsider it is hard to judge the reasons why `geth` hasn't yet upgraded their web3, but it is even harder to understand why the two keywords had to go before `geth` was prepared to handle it. As someone in the business for 40 years, I can assure you that this policy is harmful to the community, and totally unnecessary. If the `geth` and `solidity` people have troubles communicating with each other, we should work on that before waging a code war.

**Comment by axic** [comment]
I meant updating, aka making changes in, geth so that it works. Web3.js 0.x is a seriously outdated piece of code. The web3.js team has been releasing the 2.x series and the latest stable is 1.2.6. The last release of the 0.x series was in April 2018, which is "decades ago" in this space. See https://github.com/ethereum/web3.js/releases.

I am not even sure why would anyone use the geth console. Can you explain what use cases it has?

Lastly I am not clear what you mean by "troubles communicating" and "waging a code war".

**Comment by axic** [comment]
By carefully reading your issue on geth, I would suggest to give a try using more battle proven means to deploy contracts: truffle, embark or remix.

**Comment by gsalzer** [comment]
"I am not clear what you mean by 'troubles communicating' and 'waging a code war'."
This is my interpretation from the outside of the fact that there are two projects that do not move in sync, both refusing to take responsibility for the incompatibility. I have seen the pattern 'we break backwards compatibility to force others to upgrade' more than once, and it is was hardly ever helpful.

We teach a course on smart contracts. For didactic purposes it is useful to let the students first interact directly with the chain, from the geth console, and then we introduce remix as well as truffle (and maybe other tools in the future). The students try all sort of things, which is basically good, but it causes headaches if the different pieces do not fit together. What I find most painful is that this experience conveys the impression of an immature technology.

Besides us, there are others with the same problem, mostly reporting it as a geth issue. Don't know about their use case.

**Comment by chriseth** [comment]
@alcuadrado is this something you could help with?

**Comment by alcuadrado** [comment]
Let me ask the rest of the team. Will come back with an answer soon.

**Comment by alcuadrado** [comment]
Hey @chriseth. What do you need help with here? We agree with @axic's opinion.

**Comment by chriseth** [comment]
I think this is mostly about geth upgrading web3.js, so I'm closing it.
