### ISSUE TITLE
Windows release for v0.5.16 is a nightly build

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [ethereum/solidity#8697]
## Description
The Windows version provided in the [`v0.5.16` release](https://github.com/ethereum/solidity/releases/tag/v0.5.16) is a nightly build.

```
C:\> solc --version
solc, the solidity compiler commandline interface
Version: 0.5.16-nightly.2020.1.2+commit.9c3226ce.Windows.msve
```

I encountered this in the Brownie CI when a [Windows job failed](https://travis-ci.com/github/iamdefinitelyahuman/brownie/jobs/320612313#L435) while attempting to compile with `v0.5.16`. I have confirmed it locally in a virtual machine.

## Environment

- Compiler version: `0.5.16`
- Operating system: Windows 10 (VirtualBox)

**Comment by chriseth** [comment]
Fixed by recompiling and modifying the release.

**Comment by iamdefinitelyahuman** [comment]
Thanks!
