### ISSUE TITLE
(low-priority) Change lValueRequested to willBeWrittenTo in JSON AST

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#8699]
The PR https://github.com/ethereum/solidity/pull/8644 changes `lValueRequested` to `willBeWrittenTo` in the cpp code. However, the member in JSON AST remains the same. In 0.7.0, apply the change to the JSON AST member.

See https://gitter.im/ethereum/solidity-dev?at=5e8ef6473a85536c431ad992 for context.

**Comment by axic** [comment]
I think we should do this for 0.8, as it is small impact.

**Comment by chriseth** [comment]
I think we should not do it because it is an unnecessary breaking change.
