### ISSUE TITLE
Berlin: make use of subroutines - eip 2315

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8702]
- [ ] add "hasJumpsub" function to the evm version and make it return true for "berlin"
 - [ ] add the jumpsub, beginsub and returnsub opcodes to instructions.cpp (move them around and assign the correct number - do not care about breaking evm1.5).
 - [ ] make sure that jumpsub, beginsub and returnsub cannot be used in yul directly
 - [ ] change the EVMCodeTransform to use jumpsub, beginsub, returnsub for yul functions

Specification: https://eips.ethereum.org/EIPS/eip-2315

**Comment by chriseth** [comment]
Maybe we should remove evm1.5 support altogether with this change.

**Comment by axic** [comment]
This was removed from Berlin, see https://github.com/ethereum/pm/issues/263.
