### ISSUE TITLE
ICE in solidity::frontend::TypeChecker::checkExpressionAssignment(const solidity::frontend::Type &, const solidity::frontend::Expression &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8711]
## Description

This contract:
```solidity
contract C {
    function h() internal pure returns (uint, uint) { return () = h();  }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/analysis/TypeChecker.cpp(1297): Throw in function void solidity::frontend::TypeChecker::checkExpressionAssignment(const solidity::frontend::Type &, const solidity::frontend::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Array sizes don't match and no errors generated.
[solidity::util::tag_comment*] = Array sizes don't match and no errors generated.
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

Looks similar to some closed bugs...

## Environment

- Compiler version:  0.6.7-develop.2020.4.20+commit.41ef1312.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for the bug report @agroce 

I believe this is a duplicate of https://github.com/ethereum/solidity/issues/8277#issuecomment-607936250

Perhaps your input is another way of triggering the ICE.

**Comment by agroce** [comment]
Hmm, yeah, I searched for the line involved, but code churn has presumably moved it.  The inputs are awfully different, though...

**Comment by agroce** [comment]
Ok, the odd thing here is there aren't any arrays around, not even bytes32 or anything, right?

**Comment by chriseth** [comment]
@agroce tuples are a special kind of arrays for the parser.
