### ISSUE TITLE
Ether units: support gwei (and perhaps review the others)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8716]
The [ether units](https://solidity.readthedocs.io/en/latest/units-and-global-variables.html#ether-units) we support:
- wei,
- finney,
- szabo
- ether

`ether` (most used unit) and `wei` (smallest unit) are very useful, but it seems `finney` and `szabo` never picked up too much following, however we are missing `gwei`, which is frequently used for gas calculations.

Would it make sense supporting `gwei` and perhaps dropping `szabo` (and maybe `finney`)?

**Comment by chriseth** [comment]
at some point there was also ada and einstein...

**Comment by axic** [comment]
I missed ada and einstein, but in 2016 this was my collection of "current" units: https://github.com/ethereumjs/ethereumjs-units/blob/master/units.json

(It includes lovelace instead of ada)

**Comment by axic** [comment]
Since `gwei` was added and created a new issue, #9337, to track removal of finney and szabo.
