### ISSUE TITLE
[CLI] Introduce `--ir-bin` to output binary via yul

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8722]
Currently it is rather complicated process to get a binary via Yul:
1. `solc --ir input.sol > input.yul`
2. remove the "IR:" lines
3. `solc --strict-assembly input.yul`

If `--ir-bin` is introduced, we would need to deprecate it when we switch over to Yul completely and at that point `--bin` would use it.

**Comment by chriseth** [comment]
The idea was to make it combersome to prevent people from using it.

I would prefer a solution that just switches the whole pipeline to yul-ir-mode right away.

**Comment by axic** [comment]
>I would prefer a solution that just switches the whole pipeline to yul-ir-mode right away.

That would be ideal but `--ir-bin` seems to be more in line with the "cumbersome" method.

**Comment by chriseth** [comment]
What about ``--experimental-enable-ir``?

**Comment by axic** [comment]
> What about `--experimental-enable-ir`?

What would that do? Switch all the internal pipeline?

**Comment by chriseth** [comment]
Switch into full "compile via yul" mode.
