### ISSUE TITLE
Security advisories

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8725]
We currently maintain a list of bugs in `docs/bugs.json` and are displayed as part of our documentation: https://solidity.readthedocs.io/en/v0.6.6/bugs.html.

We also post a blog entry on blog.ethereum.org and now on solidity.ethereum.org.

Github also has a Security tab:
![Screenshot 2020-04-21 at 12 57 23](https://user-images.githubusercontent.com/20340/79863525-cda78c00-83cf-11ea-9407-fc8c0391c7f6.png)

Proposal:
- Uniquely identify each security issue, such as `SOL-<year>-<number>` or `SOL-<number>`
- Post on solidity.ethereum.org include this identifier
- Perhaps also post on blog.ethereum.org linking to solidity.ethereum.org in case of a serious bug
- Post a link on the Github Security tab

**Comment by Marenz** [comment]
How would such a post to `solidity.ethereum.org` look? Would it just be the bug and description copied from the json file?

Could we automate all the points in your proposal?

**Comment by axic** [comment]
I am not proposing a change to how we announce bugs, here's an example: https://solidity.ethereum.org/2016/11/01/security-alert-solidity-variables-can-overwritten-storage/

I am only proposing that we assign a unique identifier to each bug and also create a link on the Github Security tab.

**Comment by axic** [comment]
These are the fields required by github:

![Screenshot 2020-04-21 at 13 14 19](https://user-images.githubusercontent.com/20340/79864829-06486500-83d2-11ea-9e87-1010de63f555.png)

I am not fully sure we want to make use of this or not, but assigning an identifier to each bug is definitely useful.

**Comment by chriseth** [comment]
Sounds good!

**Comment by axic** [comment]
How about `SSA-<year>-<num>` where SSA stands for "Solidity Security Advisory"? :wink:

**Comment by attritionorg** [comment]
Siemens Security Advisory
Slackware Security Advisory

Both use 'SSA' and come to mind immediately.

**Comment by axic** [comment]
Do you think the original `SOL-<year>-<num>` is better?

Is there a comprehensive collection of these prefixes somewhere?

**Comment by attritionorg** [comment]
Unfortunately no catalog of those prefixes. They also change sometimes over the year for various reasons. Those two were the first to come to mind. I can't think of any current ones that use "SOL-" but that certainly doesn't mean there isn't one. A quick search of our vulnerability database doesn't show any so I think that would be fairly unique and better than SSA.

**Comment by axic** [comment]
While we're at it, we should also add a `published` or `timestamp` field with a date to each entry.

Update: Apparently in the documentation we state `publish` is a field, but we never used it. I'd rather rename that to `published` and start using it.

**Comment by cameel** [comment]
@axic Should we reopen this? Do we still want to do this?

**Comment by axic** [comment]
I think it would make sense doing this, as other github projects using Solidity would get an instant notification.

**Comment by NunoFilipeSantos** [comment]
The argument was: for instant notifications on GitHub, but we never had one published, so right now seems like a distraction for users.

**Comment by axic** [comment]
> but we never had one published, so right now seems like a distraction for users.

The entire point of this issue was to start doing that (i.e. upload every single advisory here), and the perquisite for that was establishing a UID, which was done in #11307.

**Comment by NunoFilipeSantos** [comment]
Ah nice! I can do that list manually in an afternoon so it doesn't take the team's time.
So what's left to be done is just to hide the option from "new issues" to not confuse users.

**Comment by NunoFilipeSantos** [comment]
NVM found a workaround.
