### ISSUE TITLE
ICE in CompilerStack::compileContract(..) [Assembly exception for bytecode]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8727]
## Description

This contract:
```solidity
contract C {
    uint immutable x;
    constructor() public {
        x = 3;
while(1==1)
        C.selector;
    }
    function selector() external view returns(uint) { return x; }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/interface/CompilerStack.cpp(1092): Throw in function void solidity::frontend::CompilerStack::compileContract(const solidity::frontend::ContractDefinition &, map<const solidity::frontend::ContractDefinition *, shared_ptr<const solidity::frontend::Compiler> > &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Assembly exception for bytecode
[solidity::util::tag_comment*] = Assembly exception for bytecode
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

Looks similar to some closed bugs...

## Environment

- Compiler version:  0.6.7-develop.2020.4.20+commit.41ef1312.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by Marenz** [comment]
Couldn't reproduce this with the current `develop` branch, trying out last release version now

**Comment by Marenz** [comment]
Hmm I can't even reproduce this if I use the same commit as specified in the description

**Comment by Marenz** [comment]
To reproduce, specify the `--optimize` flag

**Comment by Marenz** [comment]
So, the actual assert failing here is this one:
```
	assertThrow(
		immutableReferencesBySub.empty(),
		AssemblyException,
		"Some immutables were read from but never assigned."
	);
```

In Assembly.cpp:697

**Comment by axic** [comment]
@Marenz what was the resolution of this? Is @a3d4's #9007 the solution?

**Comment by a3d4** [comment]
@axic 
I believe #9007 is a possible way to fix it. But I'm not completely satisfied, as it looks a bit bulky and disproportional. I'm still looking at alternatives.

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/9007
