### ISSUE TITLE
Add a test about payable constructor in inheritance

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8731]
Do we have a test that checks that a contract can receive ether upon construction if the contract itself does not have a constructor, but it is inheriting from a contract that has a payable constructor?

**Comment by chriseth** [comment]
Is this done? @ekpyron

**Comment by ekpyron** [comment]
I would say so, yes - didn't know about this issue. Even though we ended up *not* allowing to receive ether in the case described in the issue :-).
