### ISSUE TITLE
Run `run_proofs` with Boolector

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#8732]
@yoni206 mentioned that Boolector can solve many of those tests with BV256, so we should try that as well

**Comment by yoni206** [comment]
This shouldn't be hard using `pysmt`, that has a backend for both Boolector and z3 (and others). However, these "no-overflow" operators that you are using would need to be encoded as I don't see them in pysmt.

**Comment by leonardoalt** [comment]
Oh right, that sounds good.
Yea, I think they are z3 specific

**Comment by aniemetz** [comment]
Boolector supports overflow operators, in particular for signed and unsigned addition, multiplication and division. Not via SMT-LIB, but via the API and the BTOR format.

**Comment by yoni206** [comment]
Also supported via the python api of Boolector?

**Comment by aniemetz** [comment]
Yes. 
https://github.com/Boolector/boolector/blob/master/src/api/python/pyboolector.pyx#L1875
https://github.com/Boolector/boolector/blob/master/src/api/python/pyboolector.pyx#L1896
https://github.com/Boolector/boolector/blob/master/src/api/python/pyboolector.pyx#L1896
https://github.com/Boolector/boolector/blob/master/src/api/python/pyboolector.pyx#L1964
https://github.com/Boolector/boolector/blob/master/src/api/python/pyboolector.pyx#L2425

**Comment by samuelmonday699** [comment]
Hello

**Comment by yoni206** [comment]
Hi @leonardoalt, are you still planning on using Boolector (or probably better, bitwuzla) for these benchmarks?

**Comment by leonardoalt** [comment]
> Hi @leonardoalt, are you still planning on using Boolector (or probably better, bitwuzla) for these benchmarks?

Hi Yoni, in general it'd be good, but it's not high priority for us since these benchmarks have low traffic, and it conflicts with capacity.
