### ISSUE TITLE
[Documentation] Add clarification that "nonpayable" abi state does not correspond to any solidity state mutability keyword unlike other mutability states that map one-to-one

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8736]
## Description

Since `nonpayable` mutability is not parseable e.g.,

```
contract I {
        function f() external virtual nonpayable {

        }
}
```

we need to remove reference to it here: https://solidity.readthedocs.io/en/v0.6.6/abi-spec.html?highlight=nonpayable#json

**Comment by axic** [comment]
`stateMutability` in the JSON ABI does not need to be 100% reflected with language keywords. No mutability specifier in Solidity means it is `nonpayable`.

**Comment by bshastry** [comment]
I see. Thank you for the clarification @axic . Perhaps, we should add this clarification to the documentation because it seems like a non-intuitive corner case (all others map 1-1 with solidity keyword)?

**Comment by axic** [comment]
Yes, it would make sense documenting it.
