### ISSUE TITLE
InternalCompilerError: Assembly exception for bytecode

### ISSUE THREAD

**Issue by gitpusha** [ethereum/solidity#8738]
Hi,

I am using:

Framework: `@nomiclabs/buidler` (`npx buidler compile`)
compiler: `solc-js 0.6.6` (via buidler package).

I get the following compiler error when trying to compile this (source code distilled down to smallest unit that causes the compile error):

`InternalCompilerError: Assembly exception for bytecode`

I located the source of the error to the `GelatoUserProxyFactoryDebug.proxyRuntimeCode()`

```solidity
pragma solidity ^0.6.6;

contract GelatoUserProxyDebug {
    address public immutable user;
    address public gelatoCore;

    constructor(address _user, address _gelatoCore) public payable {
        user = _user;
        gelatoCore = _gelatoCore;
    }
}

contract GelatoUserProxyFactoryDebug {
    address public immutable gelatoCore;

    constructor(address _gelatoCore) public { gelatoCore = _gelatoCore; }

    function proxyRuntimeCode() public pure returns(bytes memory) {
        return type(GelatoUserProxyDebug).runtimeCode;
    }
}
```

**Comment by chriseth** [comment]
Might be related to #8656

**Comment by chriseth** [comment]
Actually I do not think it is related to #8656 - but it shows a hole in our immutable analysis: You cannot use `runtimeCode` for contracts that use immutables.

**Comment by chriseth** [comment]
Proposed fix: Create error when using `runtimeCode` on a contract that uses immutables.

**Comment by Marenz** [comment]
I can implement this, but what is the reason you can't use runtimeCode when immutables are involved?
