### ISSUE TITLE
install_deps.sh: alpine detection

### ISSUE THREAD

**Issue by rainbreak** [ethereum/solidity#875]
Two issues with install_deps for detecting Alpine linux:

1) It uses bash. The alpine docker image only has `sh`

2) Alpine doesn't have `lsb_release`. It has '/etc/os-release' instead:

```
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.0
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

I think parsing `os-release` is going to be the solution overall as most big distros now use it, as far as I can tell.

https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by bobsummerwill** [comment]
From what I can see, there is no single simple approach to this which will work for all distros.

A simpler start for Alpine would be to check for `/etc/alpine-release`.

For the `sh` issue, does the bash shebang break anything if you run this script?   Or is it just ignored?

If you could create a PR for these changes (or any changes you can make which work) that would be much appreciated.   You have the test environment, so can validate this easier.

There will be an analogous TODO for cpp-ethereum.

https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/scripts/install_deps.sh

**Comment by bobsummerwill** [comment]
@rainbeam For the sh issue, does the bash shebang break anything if you run this script?
Or is the shebang ignored?

Does `sh ./scripts/install_deps.sh` work?   Barring that runtime detection-issue which will need fixing, or course.

**Comment by rainbreak** [comment]
@bobsummerwill : `sh ./scripts/install_deps.sh` works. `./scripts/install_deps.sh` fails because env can't find bash.

**Comment by bobsummerwill** [comment]
Well that isn't so bad, eh?

So we'll just need to tweak the distro-detection.

**Comment by elasticdotventures** [comment]
🍰 @ http://github.com/elasticdotventures/_b00t_

```bash 
# returns 0 for "true" (not alpine linux), non-zero for false (is alpine linux)
function iz_n0t_🐧🌲_alpine_linux() {
   return $(cat /etc/os-release | grep "NAME=" | grep -ic "Alpine")
}
```

then in /bin/sh you can use:
```
if [ iz_n0t_🐧🌲_alpine_linux ] ; then 
   # normal variant, i.e. ubuntu
else 
  # alpine variant
fi 
```
