### ISSUE TITLE
`abi` function for extracting a selector from calldata stored in memory

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#8751]
Currently I am using this function to decode the selector:

```
    /**
     * @dev get sig of abi encoded call
     * @param _data abi encoded data
     * @return sig (first 4 bytes)
     */
    function abiGetSig(bytes memory _data) private pure returns(bytes4 sig){
        assembly {
            sig := mload(add(_data, 0x20))
        }
    }
``` 

This should be a built in feature of the `abi.` library as `abi.getSig(bytes memory calldata)` or `abi.getSelector(bytes memory calldata)`, or some other way of dealing with calldata incoming through parameters (useful for approveAndCall of MiniMeToken and other).

**Comment by chriseth** [comment]
I would propose: `abi.selector(bytes memory)` and `abi.selector(bytes calldata)`.

**Comment by axic** [comment]
Didn't we had this topic discussed under some other PR?

**Comment by axic** [comment]
I'd however suggest `abi.decodeSelector` to be in line with the API we have.

**Comment by chriseth** [comment]
It is arguable if an actual decoding is performed there...

Although it would revert if the argument is shorter than 4 bytes.

**Comment by axic** [comment]
I'd assume `abi.selector` is a type or a way to create a selector, if I weren't familiar with the API.
