### ISSUE TITLE
Artifacts of generating values to constants remain present in optimized code

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#8758]
Looking through some source code and found this somewhat odd.
In the following contract, compiled with (0.6.6) and the optimizer on,
```
contract A {
  bytes32 public constant a = keccak256(bytes('transfer(address,uint256)'));
  function f() public returns (bytes32) {
    return a;
  }
}
```
when fetching the `constant a` in `f`, while the result of the hashing is correctly precomputed and returned in the function, the bytecode still loads the string `'transfer(address,uint256)'` into memory for no apparent reason. Cf. https://github.com/Uniswap/uniswap-v2-core/pull/64

**Comment by chriseth** [comment]
I'm sorry, but this is a know limitation of the optimizer - it currently has no notion of lifetime for memory objects. A proposal to fix this (at least for the new optimizer) is here: https://github.com/ethereum/solidity/issues/5107

**Comment by MrChico** [comment]
interesting, thanks
