### ISSUE TITLE
[Typechecker] solc ICE because of null TypePointer type

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8760]
```
contract C{function f(){(int c)=++(,);}}
```

throws

https://github.com/ethereum/solidity/blob/c7b4fa34bd307f272cc7a3f6eb06e731b5629ed5/libsolidity/analysis/TypeChecker.cpp#L1088

## Environment

- Compiler version: latest develop

**Comment by chriseth** [comment]
Another tuple error :)
