### ISSUE TITLE
Wasm release appears to be the same file as the emscripten release

### ISSUE THREAD

**Issue by jcaracciolo** [ethereum/solidity#8762]
## Description

While doing research for @NomicLabs about performance benchmark between different releases for the solidity compiler, the **Emscripten** and **Wasm** versions appear to be puling the same numbers. After closer inspection, it seems they are in fact the same file. 

## Steps to Reproduce
```
$ wget -q -O solcjs.js https://solc-bin.ethereum.org/bin/soljson-v0.6.6+commit.6c089d02.js
$ wget -q -O solcjsWasm.js https://solc-bin.ethereum.org/wasm/soljson-v0.6.6+commit.6c089d02.js
$ sha1sum solcjs.js solcjsWasm.js 
44659835febad7e3b907171b11f465988b363c64  solcjs.js
44659835febad7e3b907171b11f465988b363c64  solcjsWasm.js
```

Description of release in https://solc-bin.ethereum.org/bin/list.json
```
 {
      "path": "soljson-v0.6.6+commit.6c089d02.js",
      "version": "0.6.6",
      "build": "commit.6c089d02",
      "longVersion": "0.6.6+commit.6c089d02",
      "keccak256": "0x3c9cfccc78bf352f4c7901d7af76757bd228f93af2634af4cd16b4916c13e44e",
      "urls": [
        "bzzr://ab23bd0e01952ee485f0426c9c4e47fcf6a508bc4919e83be31c0f9ea6e396ca"
      ]
    },
```

Description of release in https://solc-bin.ethereum.org/wasm/list.json
```
{
      "path": "soljson-v0.6.6+commit.6c089d02.js",
      "version": "0.6.6",
      "build": "commit.6c089d02",
      "longVersion": "0.6.6+commit.6c089d02",
      "keccak256": "0x3c9cfccc78bf352f4c7901d7af76757bd228f93af2634af4cd16b4916c13e44e",
      "urls": [
        "bzzr://ab23bd0e01952ee485f0426c9c4e47fcf6a508bc4919e83be31c0f9ea6e396ca"
      ]
    }
```

**Comment by chriseth** [comment]
This is indeed the case. We just flipped a switch in the emscripten build process that creates a javascript file that contains a "binary blob" which is transparently executed via webassembly.

If you want to compare performance, you can only easily do that on a version up to and including 0.6.1. If you take a look at the solc-bin repository, you will find a directory called `wasm` that contains the wasm builds of "older" compilers. Starting from 0.6.2, they are just symlinks to the ones in the `bin` directory.

We did not make a proper performance comparison, but if you use remix, you do notice a considerable difference between 0.6.1 and 0.6.2.

**Comment by axic** [comment]
@chriseth do we have this explained in the documentation btw?

**Comment by chriseth** [comment]
No - we should add something. Also how you can load the compiler in the browser.

**Comment by chriseth** [comment]
Created https://github.com/ethereum/solidity/issues/9015
