### ISSUE TITLE
ABI: fixed-length bytes larger than 32 bytes

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8772]
Currently in the ABI there are two kinds of "bytes" types: fixed-length bytes (1 to 32 bytes, `bytes1` to `bytes32`) and dynamic-length bytes (`bytes`).

There is a reason for this: since the ABI operates on 256-bit width elements, fixed-length bytes can be encoded in-place, while dynamic ones are encoded as an offset in-place and followed by 256-bit aligned data.

However, in many of the use cases, contracts use dynamic bytes *only* because they need a longer than 32-bytes field, but they don't expect that field to be dynamically sized. Therefore they resort to introducing `require` statements to ensure the inputs are of valid size. I expect these use case to increase in numbers with the BLS12-* curves picking up users (since they have larger keys).

Thus here is a proposal to introduce language support for this: `bytes(N)` marks fixed-size, but dynamically encoded fields. The ABI decoder would check and reject input at the time of decoding.

Alternatively we could accept arbitrary length (N) as a keyword `bytesN`, but that I think would introduce too much complexity on the parser.

Question: is the `bytes(N)` syntax too confusing? Any other ideas?

Example use case (syntax 1):
```solidity
interface IDepositContract {
    function deposit(
        bytes(48) calldata pubkey,
        bytes32 withdrawal_credentials,
        bytes(96) calldata signature,
        bytes32 deposit_data_root
    ) external payable;
}
```

Example use case (syntax 2):
```solidity
interface IDepositContract {
    function deposit(
        bytes48 calldata pubkey,
        bytes32 withdrawal_credentials,
        bytes96 calldata signature,
        bytes32 deposit_data_root
    ) external payable;
}
```

Example use case (syntax 3):
```solidity
interface IDepositContract {
    function deposit(
        bytes{length=48} calldata pubkey,
        bytes32 withdrawal_credentials,
        bytes{length=96} calldata signature,
        bytes32 deposit_data_root
    ) external payable;
}
```

This could potentially also help the SMTChecker, at least there would be no need for extra require statements from the user.

**Comment by MrChico** [comment]
I like this proposal and I prefer syntax 2 :)

**Comment by chriseth** [comment]
It would be great if we could stick to the fixed-size array notation, but maybe this is misleading because of the packed encoding.

**Comment by axic** [comment]
The benefit of syntax 3 could show if we introduce `min`/`max` lengths in the future:
```
bytes{length=48} calldata message;
bytes{min=10} calldata message;
bytes{max=100} calldata message;
bytes{min=10, max=100} calldata message;
```

Don't have a use case at hand, but potentially there are use cases.

**Comment by chriseth** [comment]
names of ABI types and how the are named in a language that uses ethereum abi are two different things :)

**Comment by axic** [comment]
> names of ABI types and how the are named in a language that uses ethereum abi are two different things

There is a pretty good correlation right now.

**Comment by ekpyron** [comment]
It'd be cool if this could just be how ``byte[N]`` works (following @chriseth's comment above), but unfortunately we probably can't just break that ... even though I think it unlikely anybody ever uses ``byte[N]`` now, for it being *not* packed...

**Comment by ekpyron** [comment]
Hmmm... or can we break that :-)? We could say that ``bytes1[N]`` is still padded and we could start warning about ``byte[N]`` in 0.6 and changing its semantics in 0.7... actually we could even abandon ``bytes`` in favour of ``byte[]`` that way, then we can be sure people would notice the change :-)... but yeah, not sure...

**Comment by axic** [comment]
I haven't considered breaking changes, hence the above three syntactical options.

If we consider breaking changes it would be nice to overhaul fixed-size arrays.

**Comment by axic** [comment]
If we are making a breaking change we could consider reusing the range/slice syntax:
```
bytes[48] calldata message; // exactly 48 bytes
bytes[10:] calldata message; // minimum 10 bytes
bytes[:100] calldata message; // maximum 100 bytes
bytes[10:100] calldata message; // minimum 10 bytes, maximum 100 bytes
```

Though I still prefer https://github.com/ethereum/solidity/issues/8772#issuecomment-628013973

**Comment by ekpyron** [comment]
Question: would it only be multiples of ``32`` or would there be e.g. ``bytes33`` (in whatever syntax)? If the latter, then how wide would ``bytes33`` actually be? 64 bytes and abi decoding ensures the last 31 to be zero?

Depending on that and *if* we want to go down a breaking path, we could actually even consistently replace bytes1..bytes32 by ``byte[1]...byte[32]``...

**Comment by chriseth** [comment]
Note that @ekpyron  did not suggest a breaking change: `byte` is not a type known to the ABI, only `bytes1` is.

**Comment by chriseth** [comment]
We could use `byte[N]` while it translates to `bytesN` in the abi if `N<=32` and `byte[N]` otherwise.

**Comment by ekpyron** [comment]
It's not breaking the ABI, but it's breaking the syntax, isn't it? Because so far ``byte[N]`` is a synonym to ``bytes1[N]``...

**Comment by chriseth** [comment]
Sure, but breaking changes in Solidity are comparatively easy to do and we could still use `bytes1[N]` in Solidity, although I don't think that anybody would...

**Comment by ekpyron** [comment]
Alright, nice, if we're open to break the current ``byte[N]``syntax  in solidity, then so far I'd vote for doing that! In case we agree on that, there's a few things to iron out, though... should we keep ``bytes1..bytes32``? Do we need that for the ``bytes1[N]`` workaround to get the old behaviour? Could that instead be ``byte[1][N]``? Will we support ``byte[N] x = 0x12...FF`` for ``N > 32`` and with longer literals? Will ``byte[]`` replace ``bytes``? And not sure that's even all questions :-).

**Comment by GNSPS** [comment]
Whoop just discovered this issue and I like the proposal!

And I actually prefer this syntax version: https://github.com/ethereum/solidity/issues/8772#issuecomment-628027956

**Comment by chriseth** [comment]
DId someone analyze in which way fixed-size byte arrays longer than 32 bytes would still "look like" value types or are they reference types?

**Comment by g-r-a-n-t** [comment]
In terms of the ABI, is there a reason for limiting the size of fixed-size byte arrays?

> However, in many of the use cases, contracts use dynamic bytes only because they need a longer than 32-bytes field, but they don't expect that field to be dynamically sized. Therefore they resort to introducing require statements to ensure the inputs are of valid size. I expect these use case to increase in numbers with the BLS12-* curves picking up users (since they have larger keys).

It seems like developers would be better off using fixed-size byte array fields larger than 32 bytes here.

> Alternatively we could accept arbitrary length (N) as a keyword bytesN, but that I think would introduce too much complexity on the parser.

In Fe, we currently [allow for this](https://github.com/ethereum/fe/blob/974efcf59c30c056ea4e65161695866fe2cdb51c/compiler/tests/fixtures/guest_book.fe#L1) and encode the data as a fixed-size value. I actually wasn't aware of the size limitation until very recently. Our tests weren't even failing because the [library](https://github.com/openethereum/ethabi) we're using for encoding/decoding values ignores this part of the spec.

**Comment by axic** [comment]
As part of the [verkleization](https://ethereum-magicians.org/t/proposed-verkle-tree-scheme-for-ethereum-state/5805) storage slots will be laid out differently, to also aid witness design. The change means that the lowest 8-16bits of the storage key (the input to `SLOAD`/`SSTORE`) would not be hashed, and consecutive keys are laid out next to eachother.

It would be nice for contracts to make use of this. Luckily [it seems](https://docs.soliditylang.org/en/v0.8.4/internals/layout_in_storage.html) that value types and static-length arrays would already benefit from this change, as they are consecutively stored. Dynamic types, including `bytes` and `string`, would not benefit.

However the type discussed in this issue could be stored like static arrays and allowing to benefit from this new storage scheme.

**Comment by roshanrags** [comment]
Is this still something you are looking to add?
