### ISSUE TITLE
Error in installing in MacOS 

### ISSUE THREAD

**Issue by saarthak08** [ethereum/solidity#8774]
I tried to upgrade solidity using Homebrew but it shows errors. Earlier when I installed solidity it installed correctly. But when I recently tried to upgrade, it failed. So, I upgraded my MacOS, XCode and all brew packages and uninstalled the older version of solidity and then tried to install solidity@0.6.6 again, but it failed again. 
So then, I tried to install the older version again but it also isn't installing.

Log Errors After: --> `brew install solidity --debug --verbose`

 make install
/usr/local/Cellar/cmake/3.17.1/bin/cmake -S/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 -B/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E cmake_progress_start /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/CMakeFiles /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/solidity_BuildInfo.h.dir/build.make CMakeFiles/solidity_BuildInfo.h.dir/depend
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/jsoncpp-project.dir/build.make CMakeFiles/jsoncpp-project.dir/depend
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 && /usr/local/Cellar/cmake/3.17.1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/CMakeFiles/solidity_BuildInfo.h.dir/DependInfo.cmake --color=
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 && /usr/local/Cellar/cmake/3.17.1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/CMakeFiles/jsoncpp-project.dir/DependInfo.cmake --color=
Scanning dependencies of target jsoncpp-project
Scanning dependencies of target solidity_BuildInfo.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/jsoncpp-project.dir/build.make CMakeFiles/jsoncpp-project.dir/build
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/solidity_BuildInfo.h.dir/build.make CMakeFiles/solidity_BuildInfo.h.dir/build
/usr/local/Cellar/cmake/3.17.1/bin/cmake -DETH_SOURCE_DIR=/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6 -DETH_BUILDINFO_IN=/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/cmake/templates/BuildInfo.h.in -DETH_DST_DIR=/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/include/solidity -DETH_CMAKE_DIR=/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/cmake -DETH_BUILD_TYPE="Release" -DETH_BUILD_OS="Darwin" -DETH_BUILD_COMPILER="appleclang" -DETH_BUILD_PLATFORM="Darwin.appleclang" -DPROJECT_VERSION="0.6.6" -DPROJECT_VERSION_MAJOR="0" -DPROJECT_VERSION_MINOR="6" -DPROJECT_VERSION_PATCH="6" -P /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/cmake/scripts/buildinfo.cmake
[  1%] Creating directories for 'jsoncpp-project'
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-build
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/tmp
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp
[  1%] Built target solidity_BuildInfo.h
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/downloads
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E make_directory /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E touch /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/jsoncpp-project-mkdir
[  1%] Performing download step (download, verify and extract) for 'jsoncpp-project'
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src && /usr/local/Cellar/cmake/3.17.1/bin/cmake -P /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/download-jsoncpp-project.cmake
-- verifying file...
       file='/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/downloads/jsoncpp-1.9.2.tar.gz'
-- File already exists and hash match (skip download):
  file='/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/downloads/jsoncpp-1.9.2.tar.gz'
  SHA256='77a402fb577b2e0e5d0bdc1cf9c65278915cdb25171e3452c68b6da8a561f8f0'
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src && /usr/local/Cellar/cmake/3.17.1/bin/cmake -P /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/verify-jsoncpp-project.cmake
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src && /usr/local/Cellar/cmake/3.17.1/bin/cmake -P /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/extract-jsoncpp-project.cmake
-- extracting...
     src='/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/downloads/jsoncpp-1.9.2.tar.gz'
     dst='/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src && /usr/local/Cellar/cmake/3.17.1/bin/cmake -E touch /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/jsoncpp-project-download
[  1%] No patch step for 'jsoncpp-project'
[  2%] No update step for 'jsoncpp-project'
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E echo_append
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E echo_append
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E touch /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/jsoncpp-project-patch
/usr/local/Cellar/cmake/3.17.1/bin/cmake -E touch /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/jsoncpp-project-update
[  2%] Performing configure step for 'jsoncpp-project'
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-build && /usr/local/Cellar/cmake/3.17.1/bin/cmake -DCMAKE_INSTALL_PREFIX=/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps -DCMAKE_CXX_COMPILER=/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_POSITION_INDEPENDENT_CODE= -DJSONCPP_WITH_TESTS=OFF -DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF "-DCMAKE_CXX_FLAGS= -DJSON_USE_INT64_DOUBLE_CONVERSION" -DCMAKE_BUILD_TYPE=Release "-GUnix Makefiles" /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- JsonCpp Version: 1.9.2
-- Looking for C++ include clocale
-- Looking for C++ include clocale - found
-- Looking for localeconv
-- Looking for localeconv - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of lconv
-- Check size of lconv - done
-- Performing Test HAVE_DECIMAL_POINT
-- Performing Test HAVE_DECIMAL_POINT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-build
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-build && /usr/local/Cellar/cmake/3.17.1/bin/cmake -E touch /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-stamp/jsoncpp-project-configure
[  3%] Performing build step for 'jsoncpp-project'
cd /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project-build && /Applications/Xcode.app/Contents/Developer/usr/bin/make
Scanning dependencies of target jsoncpp_lib
[  8%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_reader.cpp.o
[ 16%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_value.cpp.o
[ 25%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_writer.cpp.o
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_writer.cpp:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_writer.cpp:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
using ::isgreater;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:731:29: note: '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_writer.cpp:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:324:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:760:29: note: '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_writer.cpp:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
make[5]: *** [src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_writer.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_value.cpp:12:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_value.cpp:12:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
using ::isgreater;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:731:29: note: '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_value.cpp:12:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:324:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:760:29: note: '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_value.cpp:12:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/tmp/solidity-20200426-5623-s2cidd/solidity_0.6.6/deps/src/jsoncpp-project/src/lib_json/json_value.cpp:828:44: error: expected unqualified-id
    const auto value_classification = std::fpclassify(value_.real_);
                                           ^
/usr/local/include/math.h:127:5: note: expanded from macro 'fpclassify'
    ( sizeof(x) == sizeof(float)  ? __fpclassifyf((float)(x))            \
    ^
14 errors generated.
make[5]: *** [src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_value.cpp.o] Error 1
make[4]: *** [src/lib_json/CMakeFiles/jsoncpp_lib.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [deps/src/jsoncpp-project-stamp/jsoncpp-project-build] Error 2
make[1]: *** [CMakeFiles/jsoncpp-project.dir/all] Error 2
make: *** [all] Error 2
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
/usr/local/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
BuildError: Failed executing: make install

==> Configuration
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 474ad1d25ce77de5836bfbe9824716667f853797
Core tap last commit: 61 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
/usr/bin/curl --version
Curl: 7.64.1 => /usr/bin/curl
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
Java: 14.0.1, 11.0.2, 1.8.0_252
macOS: 10.15.4-x86_64
CLT: 11.0.33.16
Xcode: 11.4.1
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/icu4c:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/cmake/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/ccache/bin:/usr/local/opt/z3/bin:/usr/bin:/bin:/usr/sbin:/sbin

## I am attaching the logs zip also.

[logs.zip](https://github.com/ethereum/solidity/files/4533914/logs.zip)

**Comment by chriseth** [comment]
Sorry for the late reply - is this still a problem? We are currently working on binary releases for macos, maybe that helps.

**Comment by saarthak08** [comment]
Yes, the same problem still persists. I couldn't install solidity via brew in my system (macOS).

**Comment by saarthak08** [comment]
I tried to install the latest release. It installed successfully.
