### ISSUE TITLE
Allow NatSpec comments for events

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8776]
```solidity
contract ERC20 {
  /// @notice This event is emitted when a transfer occurs.
  /// @param from The source account.
  /// @param to The destination account.
  /// @param amount The amount.
  event Transfer(address from, address to, uint amount);
}
```

Intuitively I would expect the above to produce some NatSpec output, but the compiler produces none. [The spec](https://solidity.readthedocs.io/en/v0.6.6/natspec-format.html) reveals the compiler is correct.

I think events are in a weird position, because they cannot be inspected by contracts and are supposed to be ephemeral, however they are well supported in the language and widely used outside. It would make sense considering NatSpec support, I suggest the tags `@notice`, `@dev` and `@param`.

**Comment by GollyGo** [comment]
/// @ConsentDevelopment

**Comment by hrkrshnn** [comment]
NatSpec for events can be useful when implementing LSP. Something like the following:

![img](https://i.imgur.com/zbX0G57.png)

I also favor implementing NatSpec for events.

**Comment by chriseth** [comment]
Taking this directly into the implementation backlog.
