### ISSUE TITLE
结构体中的结构体数组如何初始化？

### ISSUE THREAD

**Issue by kevin1027sloth** [ethereum/solidity#8781]
我尝试了使用下面的代码：
![image](https://user-images.githubusercontent.com/31197436/80335438-e0fe9f80-8886-11ea-8547-b1aa4cccb1da.png)
但是编辑器有错误提示 ：

> UnimplementedFeatureError: Copying of type struct StructTest.SubObj memory[] memory to storage not yet supported.

但是下面的这种书写却不会出现错误：
![image](https://user-images.githubusercontent.com/31197436/80335610-5e2a1480-8887-11ea-97ae-0e7f5e16c1e3.png)

请问我将如何实现结构体中的结构体数组的初始化？

**Comment by chriseth** [comment]
If this is about the missing feature: You need to copy the individual elements of the struct manually.

**Comment by xiaozhu001** [comment]
@chriseth  你有认真看我的问题描述吗？我问的很清楚，就是想要在结构体中定义一个结构体的数组，那么我如何实例化这个结构体
