### ISSUE TITLE
Provide a way to calculate the salted address of a contract

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8798]
See https://github.com/ethereum/solidity/issues/2136#issuecomment-559196297:
> Since we have type(Holder).creationCode, how about adding type(Holder).calculateSaltedAddress(salt) ?

**Comment by dmihal** [comment]
How about this:

```solidity
type(Holder).calculateAddress{salt: bytes32(0), deployer: address(this)}(param1, param2);
```

**Comment by drortirosh** [comment]
> How about this:
> 
> ```solidity
> type(Holder).calculateAddress{salt: bytes32(0), deployer: address(this)}(param1, param2);
> ```

This would be great to have. 
An alternate format (which requires deployer to be specified):

```solidity
type(Holder).calculateAddress(bytes32(0), address(this),(param1, param2));
```

This syntax more resembles the "encodeCall" syntax.

But either implementation is FAR better to the current WORKAROUND implementation:

```solidity
import "@openzeppelin/contracts/utils/Create2.sol";

return Create2.computeAddress(bytes32(salt), keccak256(abi.encodePacked(
                type(Holder).creationCode,
                abi.encode(param1, param2)
            )), address(this));
```
