### ISSUE TITLE
Trusted/untrusted contract/function

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#8804]
External function calls to another contract are problematic for formal verification tools because even if the called code is known during static analysis, we can't guarantee that the deployed code is exactly that, unless the analyzed contract is the deployer. In the latter case, we could mark the contract/address that was deployed by the analyzed contract as trusted, so FV tools wouldn't have to disregard constraints on state variables when an external call to that contract is made.

**Comment by axic** [comment]
It would be possible to check codehash in the call pre-flight and abort if there's a mismatch.

**Comment by chriseth** [comment]
@leonardoalt can you move this out of the "new issues" column?

**Comment by cameel** [comment]
@leonardoalt Did #11559 cover this?

**Comment by leonardoalt** [comment]
> @leonardoalt Did #11559 cover this?

Ah yes it did.

**Comment by leonardoalt** [comment]
Done in https://github.com/ethereum/solidity/pull/11559
