### ISSUE TITLE
compiler metadata: location of function arguments

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#8812]
To make debugging, analysis and formal verification easier, it would be useful to be able to automatically extract the location of arguments given to functions. 

For value types, this is not very difficult: the arguments will be directly on the stack in reverse order; but for reference types, it is not as straightforward to find this.

Would it be possible to provide this information as compiler metadata? 

Related issue: https://github.com/ethereum/solidity/issues/6485

**Comment by chriseth** [comment]
Would it be fine to add this information to a joint json struct that also contains the storage layout of state variables? Basically some kind of extensible "debug info"?

**Comment by MrChico** [comment]
Yeah, that would be great, I think

**Comment by cameel** [comment]
Now that [ethdebug spec](https://github.com/ethdebug/format) is in progress, I think this should be redirected there.
