### ISSUE TITLE
Release for 0.4.15 executable for windows is in incorrect version

### ISSUE THREAD

**Issue by AnonymousMonkey2021** [ethereum/solidity#8813]
## Description
Download the 0.4.15 executable for windows from the release, it is a nightly build, not the actual stable version. 

## Environment
N/A
- Compiler version: 0.4.15
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Windows

## Steps to Reproduce
 Download and run solc --version

**Comment by cameel** [comment]
Thanks for the report. We're going to rebuild the executable and replace it on the release page.

There's already another report about the same issue: #9545. It's been posted later but contains a bit more info so I'm going to close this one. We can continue the discussion there.
