### ISSUE TITLE
Hex literals don't work in assembly/Yul

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#8816]
## Description

The Yul specification says that there are `hex'...'` literals, but in fact such literals do not work.  Using hex literals will cause a `ParserError: Literal or identifier expected`.  This is true regardless of whether single or double quotes are used.

## Environment

- Compiler version: 0.6.6
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle

## Steps to Reproduce

```solidity
pragma solidity ^0.6.6;

contract HexTest {
  function test() {
    assembly {
      pop(hex"00")
    }
  }
}
```

**Comment by chriseth** [comment]
The main difference between `hex` literals and `0x` literals could be the alignment. If we are set that `0x` literals are numbers and `hex"..."` literals are left-aligned "numebers", then we should add that.

**Comment by haltman-at** [comment]
Yes, that was how I had inferred it to work, given that in Solidity hex literals are essentially a different form of string literals, and in Yul string literals are left-aligned.

**Comment by chriseth** [comment]
Meeting discussion: This is too confusing, we should just disallow such literals in the inner assembly (it is still fine to have it for the data part of yul objects).

**Comment by haltman-at** [comment]
Well, noting that they're mentioned in the documentation, so if they're not being added then they should be removed from there!
