### ISSUE TITLE
Should we add `0x00 0x00` to the end of the bytecode for "no metadata"?

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8819]
In order to make metadata removal / detection consistent, the "no metadata" version of the bytecode should end in two zero bytes (the length of the cbor structure).

**Comment by axic** [comment]
Sounds reasonable to me.

**Comment by chriseth** [comment]
Actually it turns out that we always append a cbor structure that at least contains the compiler version. The compiler option is just to remove the metadata hash.

**Comment by axic** [comment]
I was looking at `CompilerStack` the past minutes trying to figure out where CBOR is turned off. It isn't 😓
