### ISSUE TITLE
Disallow shift by signed types

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8822]
## Description

```
pragma solidity >= 0.0.0;
contract C {
        function f(uint x, int y) internal returns (uint)
        {
            return x << y;
        }
        function g(uint x, int y) internal returns (uint)
        {
            return x >> y;
        }
        function test() public returns (uint)
        {
            uint x = 10;
            int y = -1;
            return f(x, y) + g(x, y);
        }
}
```

compiles just fine but reverts upon execution of `test()`.

However,

```
pragma solidity >= 0.0.0;
contract C {
        function h(uint x, int y) internal returns (uint)
        {
            return x ** y;
        }
        function i(uint x, int y) internal returns (uint)
        {
            return x % y;
        }
        function test() public returns (uint)
        {
            uint x = 10;
            int y = -1;
            return h(x, y) + i(x, y);
        }
}
```

errors on compilation because modulo/exponent cannot be a signed type. This issue tracks support for making compiler behavior consistent i.e., runtime or compile-time error in all cases.

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): NA
- Framework/IDE (e.g. Truffle or Remix): Remix

**Comment by ekpyron** [comment]
@chriseth I remember us talking about this before - there was some reason for allowing signed shift amounts and reverting on negative ones, but I don't really see or remember it anymore...

**Comment by chriseth** [comment]
I don't remember any reason to allow signed shift amounts. Maybe we had to use the same type for both operands in the past - this is not the case anymore. We can make this a breaking change in 0.7.0.
