### ISSUE TITLE
Request: Jump markings on Yul functions

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#8839]
## Abstract

I'd like it if Yul functions had jump markings like Solidity functions do.  This would allow debuggers to distinguish between multiple invocations of the same function.  For Truffle Debugger it would allow me to distinguish local variables from one instance of a function, vs those same variables in a recursive invocation of that function.

## Motivation

While Truffle Debugger doesn't currently support assembly variables, [I have a PR open](https://github.com/trufflesuite/truffle/pull/3018) to make it do so.  However, it has no way to distinguish between local variables in recursive invocations of the same function, which will lead to misidentifying variables if a function is invoked recursively.

There is maybe one argument against this, which is that maybe jump markings should be reserved for Solidity stackframes and not Yul stackframes.  But I am doubtful that this is really a serious problem compared to that of not being able to distinguish Yul stackframes.

## Specification

Jumps into Yul functions should be marked with a jump in, and their returns should be marked with a jump out.

## Backwards Compatibility

I'm unclear on how breaking this change would be.  It could cause problems for anything that assumes that jump markings are *only* for Solidity stackframes and definitely not for Yul stackframes.  I don't know if that's a serious problem.

**Comment by chriseth** [comment]
@yann300 @LianaHus does remix assume that the 'jump into' marking is for Solidity functions only?

**Comment by yann300** [comment]
no it doesn't assume that
