### ISSUE TITLE
[CLI] Various solc improvements

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#8847]
The experience of using `solc` directly from the commandline, relying on flags instead of the "standard-json" for configuration options, can be improved in some areas in my opinion:

- Some options available to the `standard-json` format do not seem to be available as CLI flags. I'm missing in particular source mappings for yul which was introduced only for the json options in https://github.com/ethereum/solidity/pull/8378. It would be nice if feature parity between CLI flags and json opts was pursued as a general rule.

- When constructing a `--combined-json` output, some options generate a quoted json string value (`metadata`, `storage-layout`, `abi`), while others (`ast`), generate a normal, non-quoted json subobject. See screenshot:
<img width="854" alt="Screen Shot 2020-05-05 at 13 47 01" src="https://user-images.githubusercontent.com/8930559/81062826-fdc65300-8ed6-11ea-97b3-900024510687.png">

- This is more of a personal preference / nit, but in builds with only one sourcefile and contract, it could be nice to skip the explaining text and filename for outputs, such the output can be used directly in other contexts or other tools, as in:
```
echo "contract A {uint public x;}" | solc --bin-runtime - > A.txt | evm --code $(<A.txt)
```

**Comment by axic** [comment]
Some, like `metadata`, should be quoted, because the encoding order matters for reproducibility.

The others I am not sure why are quoted, probably they were introduced at different times, but we could change it with 0.7.0.

**Comment by leonardoalt** [comment]
> This is more of a personal preference / nit, but in builds with only one sourcefile and contract, it could be nice to skip the explaining text and filename for outputs, such the output can be used directly in other contexts or other tools, as in:

Totally agree with this

**Comment by axic** [comment]
Split this into three separate issues.
