### ISSUE TITLE
Build and release soljson.js with SMT support.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8851]
It now seems possible to build soljson.js with integrated Z3 support.
The resulting binary seems to work, but is significantly larger, i.e. ~~30MB~~ 19MB instead of 8MB.

We can either build with Z3 by default or - if the increased size is a major concern - publish a second version (maybe marked as experimental) with Z3 enabled.

For the build process, I think it would make sense to finally also create a docker file for the emscripten build that contains prebuilt z3 and boost.

Steps used to produce a working SMT enabled soljson.js:
-------------------

I used the docker image we use for our CI runs as basis: trzeci/emscripten:sdk-tag-1.39.3-64bit

I checked out the 4.8.7 tag of Z3 and applied https://github.com/Z3Prover/z3/commit/e212159f4e941c78fc03239e0884f2f0454f581f to it.
Then I was able to build z3 with emscripten as follows:
```
emconfigure python scripts/mk_make.py --staticlib --staticbin --single-threaded --x86 --prefix=/emsdk_portable/emscripten/sdk/system/
emmake make -C build/ -j8
emmake make -C build/ install
```

Then I changed ``find_package(Z3 4.6.0)`` to ``find_package(Z3)`` in ``libsolidity/CMakeLists.txt`` (providing an up to date native /usr/bin/z3 might make this unnecessary).

Then ``scripts/travis-emscripten/install_deps.sh`` and ``scripts/travis-emscripten/build_emscripten.sh``, should build a soljson.js, but still without Z3 support.

Rerunning cmake in ``emscripten_build`` as ``cmake -DZ3_LIBRARY=/emsdk_portable/emscripten/sdk/system/lib/libz3.a -DZ3_INCLUDE_DIR=/emsdk_portable/emscripten/sdk/system/include`` and rerunning ``make`` builds ``soljson.js`` with Z3 support in ``emscripten_build/libsolc``.

TODO:
--------
- clean up this build process. We can try building using ``emcmake.py`` instead of ``emconfigure``, that way we might get cmake files that will help in ``find_package(Z3)``'s auto-detection.
- pack the Z3 build (and while we're at it the boost build) into a docker image and switch the CI builds to it
- have a look into https://github.com/cpitclaudel/cvc4.js/blob/master/vm/provision.sh and figure out if we can also enable CVC4 and what that means for binary size and if it's worth it.
- decide if the soljson.js builds should have z3 integrated by default or whether we want separate builds
- Check if any compile time options for Z3 are available that could reduce binary size.

**Comment by ekpyron** [comment]
It seems possible to build z3 with
```
emcmake cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=/emsdk_portable/emscripten/sdk/system -DZ3_BUILD_LIBZ3_SHARED=OFF -DZ3_ENABLE_EXAMPLE_TARGETS=OFF -DSINGLE_THREADED=ON /path/to/z3/source
make -j16
make install
```

That has two advantages:
- ``cmake`` will auto-discover Z3 without editing ``libsolidity/CMakeLists.txt`` and without passing ``-DZ3_LIBRARY`` or ``-DZ3_INCLUDE_DIR``.
- Using a ``MinSizeRel`` build the binary size of soljson.js is down to 19MB.

**Comment by axic** [comment]
Can we check the size with CVC4 or with disabling some strategies in Z3?

**Comment by leonardoalt** [comment]
@axic what kind of strategies could be disabled?

**Comment by leonardoalt** [comment]
8mb to 19mb is a substantial % increase, but not that much in absolute terms

**Comment by axic** [comment]
> @axic what kind of strategies could be disabled?

Not sure, you are the expert at z3. I just recall that you mentioned z3 has multiple algorithms and some may be better at certain things but taking longer, than others. Also kind of baffled how could be 10Mb in the first place :wink:

**Comment by leonardoalt** [comment]
I just had a look at the build options, I don't see anything related to removing submodules. I would guess the build mode `MinSizeRel` is our best option.

> Also kind of baffled how could be 10Mb in the first place

Well, I wouldn't be surprised if z3's codebase is larger than Solidity's, so also not really surprised there.

**Comment by ekpyron** [comment]
Regarding CVC4: so far I'm not even sure I'll be able to build it and that it'll work - but I can try and check! But I'd imagine another increase of approximately the same magnitude and since CHC only works for Z3, I'd choose that, if we have to choose only one.

@axic Recently I heard someone talking about wasm supporting dynamic libraries... https://webassembly.org/docs/dynamic-linking/ sounds like it... do you know if that works well and is sufficiently supported by browsers and all? It'd be kind of fancy to be able to plug the solvers in at runtime as needed :-D... but yeah - I wouldn't go for that now, but we could actually think about it for the future...

**Comment by axic** [comment]
Dynamic linking works well both in and outside of the browser, but one has to be careful how to use it and emscripten can complicate matters quite a bit.

There are two choices:
1) Separate memory
2) Shared memory

In the case of separate memory, two wasm instances exist and one can assign an exported function of one as an imported function of the other. However if any of these functions pass a memory reference, then obviously that will point to an invalid area.

In the case of shared memory both instances share the memory space. Again, the instances have to be aware otherwise they will mess up memory for eachother.

Both cases depend heavily on the toolchain/compiler deciding what is best. In our situation if emscripten supports this then we can use it, if not, it will be troublesome.
