### ISSUE TITLE
Implement "basic" modifiers using function calls

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8861]
Basic modifiers of the form `{ some_code; _; }` could be implemented by replacing `some_code` by a function call. This would save quite some bytecode in most of the cases, especially with regards to error messages.

**Comment by yudilevi** [comment]
Optionally you could create a function for each modifier code "block" to optimize it further.
It won't be perfect, for example in the following case:
`if(x) _;`

But it can cover more cases.

**Comment by chriseth** [comment]
Duplicate of https://github.com/ethereum/solidity/issues/6584 :)
