### ISSUE TITLE
Simple peephole optimizer if the main optimizer fails

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#887]
There are quite some situations where the main optimizer fails to operate, which always results in a full basic block being unoptimized. We should add a peephole optimizer to assist in such situations.

**Comment by pirapira** [comment]
@chriseth says `push x; pop` appears often currently.

**Comment by chriseth** [comment]
This optimizer could also use the rules in ExpressionClasses for local simplifications.

**Comment by axic** [comment]
> There are quite some situations where the main optimizer fails to operate

Is this the reason in some cases the optimiser fails to replace `EXP` by `PUSH`? It seems that usually it can replace `2 250 EXP`, but won't take `250 2 EXP`. The rule is with `powm()` so it should handle it.

**Comment by chriseth** [comment]
There is a tradeoff between deploy-time costs and run-time costs. We currently use a crude heuristic and its parameter can be modified using the `--optimize-runs` switch.

**Comment by chriseth** [comment]
We now have a simple such optimizer, but we should still add the rules from ExpressionClasses.cpp.

**Comment by axic** [comment]
@chriseth is this still valid? If yes, I'd still propose to close this and to create a specific issue explaining what needs to be done.

**Comment by chriseth** [comment]
We added the rules to the iulia optimizer, so I think this is as for as we will go.
