### ISSUE TITLE
Confusing error message when trying to assign gasleft to a pointer

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#8875]
## Description
If you try to assign something other than an internal or external function (e.g `gasleft`) to a function pointer the message you get is confusing: "Type X is not implicitly convertible to expected type X." It should just say that this is not allowed.

To fix this we probably just need a special case for it in `FunctionType::isImplicitlyConvertibleTo` and return a nicer message.

## Steps to Reproduce
Input:
```solidity
contract C {
    function foo() public {
        function() internal view returns (uint256) ptr;
        ptr = gasleft;
    }
}
```

Output:
```
Error: Type function () view returns (uint256) is not implicitly convertible to expected type function () view returns (uint256).
--> gasleft_ptr_test.sol:4:15:
  |
4 |         ptr = gasleft;
  |               ^^^^^^^
```

**Comment by chriseth** [comment]
Actually the error message here just says that one function returns a uint while the other does not.

**Comment by axic** [comment]
There's also this old issue on the topic: #4551.

**Comment by cameel** [comment]
@chriseth Right, sorry, I originally tested it on a bigger program and for the issue I modified it to return non-essential parts. Looks like I used the wrong type for the variable. I have update the description now.

**Comment by cameel** [comment]
Another instance of this problem to fix. This time when attempting to get a pointer to a bound library function:

``` solidity
library L {
    function foo(uint256 a, uint256 b) internal pure returns (uint256) {
        return a + b;
    }
}

contract C {
    using L for uint256;

    function bar() public {
        uint256 x;
        function (uint256, uint256) internal pure returns (uint256) ptr = x.foo;
    }
}
```
```
Error: Type function (uint256,uint256) pure returns (uint256) is not implicitly convertible to expected type function (uint256,uint256) pure returns (uint256).
--> internal_library_function_bound_pointer.sol:12:9:
   |
12 |         function (uint256, uint256) internal pure returns (uint256) ptr = x.foo;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
