### ISSUE TITLE
Explicitly define target features and precompiles list

### ISSUE THREAD

**Issue by rumkin** [ethereum/solidity#8880]
## Abstract

Compiler configuration should contain a way to provide a target features and a list of precompiles with corresponding addresses. For now it contains an option `target`, which is a hardfork ID and is using for hardcoded features detection.

The `target` option should accept a path to the feature json file, which contains flags like `supportReturnData`, `hasStaticCall`, `hasChainId`, etc, and a list of precompiles.

## Motivation

Solidity should be a compiler for all Ethereum chains. Other chains could have another feature implementation schedule. So it's making Solidity a mainnet/coredev language and doesn't allow another usages of Ethereum and Solidity. 

### Option `target`

Option target should be:

* one of a hardfork names,
* a path to the features json file conteined FeaturesDescription,
* a features object.

### FeaturesDescription

This object contains `flags` and `precompiles`.

### `FeaturesDescription.flags`

Flags option contains the same options as presented in [EVMVersion.cpp:84](https://github.com/ethereum/solidity/blob/be0775da499415911b6be891e7ab60cc09e676c2/liblangutil/EVMVersion.h#L82):

- `hasReturnData`
- `hasStaticCall`
- `hasBitwiseShifting`
- `hasCreate2`
- `hasExcodeHash`
- `hasChainId`
- `hasSelfBalance`

### `FeaturesDescription.precompiles`

This is a precompiles configuration which is a dictionary which provide precompile name, its interface and an address.

Example:
```
{
  "sha256(bytes)": "0x00...01",
  "ecrecover(uint32, uint32, uint8)": "0x00...02"
}
```

Thus precompiles could contain custom set of functions. What could be helpful to implement and test some features before they lend into solidity itself. Whats therefore could speedup Ethereum development and is helpful for researches, experiments.

## Backwards Compatibility

It's backward compatible feature request.

**Comment by axic** [comment]
While those helpers exists to detect features, there are more aspects to "EVM versions" than just features. One example is gas costs. The gas estimation feature works off mostly versions and not those flags.

Have you run into a case where the current system stops people from being able to use the compiler properly? If so, which chain did it cause a problem with?

**Comment by rumkin** [comment]
I'm working on a project for developers which uses independent chain and in some cases customised/hackable EVM engine for creating testnets and own chains. And developers should be able to upgrade features independently. This is my case.

What's about others' and gas cost. It seems like a common problem to other projects. EthereumJS team is working on a solution to upgrade gas cost and opcodes executables on the fly and it seems reasonable to have common standard for migration. I wish it to be more flexible.

I see the most common problem here is that the whole process of development has several bottlenecks which reduce the final count of developers involved into the process. Every single feature should pass a long chain of discussions before it will lend into the project and other developers could use it. I think it could be improved with customisable compiler to let others touch features faster to analyse caveats and improve the final code before it will be written and merged by the core team.

**Comment by axic** [comment]
Can you give a use case why someone would only enable some features of what has been deployed on mainnet?

**Comment by rumkin** [comment]
Because it could affect your business model or users interests, what can cause unwanted consequences (reduced income or extra expenses on modernisation). For example I don't need create2 ability at all in my chain. Anyway you already did it flexible, but did it implicitly.

But what's the most important for me is custom precompiles to make custom cryptographic curves and hash algorithm be available in the contracts.

**Comment by axic** [comment]
> But what's the most important for me is custom precompiles to make custom cryptographic curves and hash algorithm be available in the contracts.

Only the the homestead precompiles are supported by language constructs (and even those we debate, such as only keeping ecrecover and sha256), everything else is used via assembly statements by third-party libraries. And those two seem pretty core functionality and it seems we are not restricting other uses precompile addresses.

**Comment by rumkin** [comment]
> Only the the homestead precompiles are supported by language constructs (and even those we debate, such as only keeping ecrecover and sha256)

As I know there are about 9 precompiles now: https://github.com/ethereum/go-ethereum/blob/7b189d6f1f7eedf46c6607901af291855b81112b/core/vm/contracts.go#L68 and seems like this count would grow in the future.

> And those two seem pretty core functionality and it seems we are not restricting other uses precompile addresses.

How could I make a call like `ed25519()` to be resolved into a custom address (e.g. `0x0000..0a`)?

**Comment by axic** [comment]
> > Only the the homestead precompiles are supported by language constructs (and even those we debate, such as only keeping ecrecover and sha256)
>
> As I know there are about 9 precompiles now: https://github.com/ethereum/go-ethereum/blob/7b189d6f1f7eedf46c6607901af291855b81112b/core/vm/contracts.go#L68 and seems like this count would grow in the future.

There are countless precompiles in the system, but that doesn't change what I said: the compiler only offers built in support for three of them (`sha256()`, `ecrecover()`,` ripemd160()`). And we are debating to remove `ripemd160()` support from the compiler.

> > And those two seem pretty core functionality and it seems we are not restricting other uses precompile addresses.
>
> How could I make a call like ed25519() to be resolved into a custom address (e.g. 0x0000..0a)?

The same way one can use any of those three not listed above: via inline assembly.

Some examples:
- snark (ecadd/ecmul/ecpairing): https://github.com/ethereum/solidity/blob/develop/test/libsolidity/semanticTests/snark.sol
- blake2: https://github.com/axic/blake2-solidity

**Comment by chriseth** [comment]
As far as fine-grained access to chain configuration options are concerned: The number of EVM versions defined is already a big strain on testing and correctness. I think opening up arbitrary combinations will likely lead to bugs in the compiler.
