### ISSUE TITLE
ICE in const solidity::frontend::TypePointer &solidity::frontend::TypeChecker::type(const solidity::frontend::Expression &) const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8881]
## Description

This contract:
```solidity
contract C {
    function o (int256) public returns (int256) {
	assembly {
	    c:=shl(1,a)
	}
    }

    int constant c=2 szabo+1 seconds+3 finney*3 hours;
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/analysis/TypeChecker.cpp(74): Throw in function const solidity::frontend::TypePointer &solidity::frontend::TypeChecker::type(const solidity::frontend::Expression &) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Type requested but not present.
[solidity::util::tag_comment*] = Type requested but not present.
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer

Looks similar to some closed bugs...

## Environment

- Compiler version:  0.6.8-develop.2020.5.9+commit.4e58c672.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by axic** [comment]
Minimal example:
```
contract C {
  function f() {
    assembly {
      c := shl(1, 2)
    }
  }
  int constant c = 0 + 1;
}
```

The problem is if constant is an expression inline assembly doesn't detect it as a "constant" (probably fails in that part of the code). In the original example the missing `a` reference was not detected, because likely it died at the point of processing `c`.

**Comment by ekpyron** [comment]
May be related to the changes in https://github.com/ethereum/solidity/pull/8665 - not sure, though, might be independent.

**Comment by Marenz** [comment]
And is the goal here to get an error because we modify a constant or should it compile?

**Comment by Marenz** [comment]
It seems to be an order-of-evaluation problem. If I move the `c` line up, it works
