### ISSUE TITLE
Add keccak256 or sha256 as an option to metadata cbor

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8908]
Currently the metadata CBOR can contain link to the metadata JSON as either an IPFS URL or a  Swarm URL.

While both essentially are ways of hashing, they do suggest a certain system to be used, which are subject to change. We have seen this with Swarm, although the CBOR is flexible and this has not caused any issue.

An additional benefit of using IPFS/Swarm is it gives an indication where the JSON should/could be found. However at the same time it can be seen as a statement of commitment to either of those systems.

The proposal here is to introduce a third option: a raw keccak256 or sha256 hash.

Since the JSON contains a keccak256 hash of each source, that may be the more natural choice here.

**Comment by axic** [comment]
@chriseth yetserday on the source-verify meeting there were no real reasons against this.

We did discuss to potentially use multihash as the "url" though.

**Comment by chriseth** [comment]
Without a means of retrieval, the "deploy on chain and publish metadata" workflow is broken or at least needs a centralized component. If we have swarm or ipfs links and someone interested in keeping the data alive keeps it pinned, anyone can retrieve the metadata and sources without having to know "where to go" - they can just follow the link and retrieve the data. If we also allow a hash function that does not come with a canonical means of retrieval, this link is broken and we need a centralized (or "located") repository to store the data.
