### ISSUE TITLE
Allow Libraries to Inherit

### ISSUE THREAD

**Issue by Denton-L** [ethereum/solidity#891]
Currently, libraries are not allowed to inherit or be inherited. I believe that libraries should be allowed to inherit from each other.

A use-case of this would be as follows:

I am currently writing an [implementation of state channels](https://github.com/ledgerlabs/toy-state-channels) and for my `Adjudicator` to check if a `bytes32[]` is newer than a previously submitted one, it has to make a call to `CompareOp`. However, in the case where we're working with nonces, `CompareOp` would be an instance of [`NonceCompareOp`](https://github.com/ledgerlabs/toy-state-channels/blob/master/contracts/NonceCompareOp.sol), which you can see has to inherit but remains stateless.

Since `CompareOp` (and all children) are assumed to be stateless contracts, though, it would be more prudent to have only one instance of each child (as a library). Unfortunately, it is not possible to create inheritable libraries and, thus, I have to write them as contracts.

**Comment by chriseth** [comment]
This was in the original design of libraries, of which only a part is implemented for now. The design document was put on a site that went down in the meantime, but I hope I still have it somewhere.

In general, the complication with libraries inheriting is that you lose the ability to use virtual functions. This is fine as long as you do not allow those functions to be overwritten. contracts and libraries can inherit from each other, and also libraries can have state variables as long as the layout of state variables in storage is preserved when inheriting.

**Comment by Rubilmax** [comment]
This would come very handy to design what we could call higher-order libraries: libraries that define a generic logic, which can be customized based on constants defined within it and overridden down in the inheritance tree

A practical example would be fixed-point math libraries: multiplications, divisions etc can be defined in multiple fixed-point scales (units), but they all share the same abstract fixed-point math logic, and only differ in the scale they apply the operations in

This would require abstract libraries though

**Comment by ekpyron** [comment]
libraries are considered deprecated in general and will be successively replaced by free functions and different mechanisms to share code using delegatecalls (there is some use of libraries in that regard, but it's rather abuse due to the lack of better language constructs).

I guess the goal of reusable code that can be specialized according to specific parameters will ultimately be solved by https://github.com/ethereum/solidity/issues/13776, even though that's quite a way down our roadmap still.

In any case, given that, I'm closing this issue, since inheritance among libraries is not planned.

**Comment by k06a** [comment]
Libraries can’t be inherited and that’s fine, because we can use composition, but we need Generics to be supported to have dynamic compositions…
