### ISSUE TITLE
Access to calldata variables of reference type in inline assembly.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8917]
Came up in https://github.com/ethereum/solidity/issues/1803
We probably need a similar mechanism as for storage slot/offset for this, only with ``_offset`` and ``_length`` (if it's a dynamic array).
Something like the following should pass:
```
contract C {
  function g(uint256[] calldata x, uint256 index) external returns(uint256 val) {
    assembly {
      switch lt(val, x_length)
      case 0 {
         val := 0xFF
      }
      default {
        val := calldataload(add(x_offset, mul(index, 32)))
      }
    }
  }
  function f() public returns (bool) {
    uint256[] memory x = new uint256[](3);
    x[0] = 0x41; x[1] = 0x42; x[2] = 0x43;
    assert(this.g(x,0) == 0x41);
    assert(this.g(x,1) == 0x42);
    assert(this.g(x,2) == 0x43);
    assert(this.g(x,3) == 0xFF);
    return true;
  }
}
// ----
// f() -> true
```

``function f(uint256[3] calldata x) public { assembly { let y := x_length } }`` or ``struct S { ... } function f(S calldata x) public { assembly { let y := x_length } }`` should be TypeErrors (``_length`` is only present for dynamically sized types).
Regarding name collisions the behaviour should be the same as for ``_offset`` and ``_slot`` for ``storage`` variables.

**Comment by ekpyron** [comment]
Decision in chat: we indeed do this as ``_offset`` and ``_length`` now. I'll open a separate language design issue to consider moving those underscore suffices to use dots instead, but for now in 0.6 this should be implemented using underscores first.

**Comment by ekpyron** [comment]
For making this non-breaking: We allow name collisions, i.e. the following is allowed, but issues a warning:
```
function f(uint[] calldata x) {
  assembly {
    let x_offset := 0 // Warning: x_offset shadows the offset of calldata variable x.
    let x_length := 0 // Warning: x_offset shadows the length of calldata variable x.
  }
}
```

With 0.7 this warning should etiher become an error, or the problem will vanish anyways if we go for https://github.com/ethereum/solidity/issues/9169 .

For now I'd say we just allow this as well without even warning about it:
```
uint x_offset; assembly { let y := x_offset }
```

**Comment by haltman-at** [comment]
Since this is finally being done for calldata pointers, how about something similar for external function pointers, with `address` and `selector`?  (Like I suggested earlier. :) ) That being the one other type that takes up two stack slots!

**Comment by chriseth** [comment]
@haltman-at you can access these slots via solidity, so I don't think there is a need to add them to inline assembly.

**Comment by haltman-at** [comment]
Yes, that's read-only though.  Or were these calldata slots going to be read-only as well?

**Comment by chriseth** [comment]
Ah ok, that of course makes sense! You can do a lot of harm with that, though, since the selector should be tied to the type...

**Comment by haltman-at** [comment]
I mean, of course it's dangerous, but I thought that's the point of assembly. :)

**Comment by saurik** [comment]
This isn't done yet, right? Like, as it stands, if I have a "bytes calldata" there isn't a way to figure out where in calldata it is from either Solidity or assembly?

**Comment by nlordell** [comment]
Any reason why `calldata` variables can't work like `memory` ones in assembly, where its value is just its offset in the call data (the analogy with memory variables that they are treated like their memory offset in assembly)?

For example
```solidity
    function foo(bytes calldata bar) external pure returns (uint256 offset, uint256 length, uint256 firstWord) {
        assembly {
            // either:
            offset := add(calldataload(bar /*0x04*/), 4)
            // or (this would imply that `calldata` variables already read their ABI-encoded offset from the calldata:
            offset := bar /*0x24*/
            length := calldataload(offset)
            firstWord := calldataload(add(offset, 32))
        }
    }
```

**Comment by saurik** [comment]
@chriseth Does this new patch support being able to get the calldata offset of a non-dynamic non-array calldata variable, such as (specifically, for my interests) a struct?

**Comment by haltman-at** [comment]
@chriseth Should I open a new issue for my suggestion above about external function pointers?

@saurik While I'm not @chriseth (or even on the Solidity team :P ), I'm pretty sure I can answer your question: You could already do that!  In assembly, that offset is what the variable would contain (as that's what's in the variable's stack slot).  No need for any additional syntax.  Am I mistaken there?

**Comment by saurik** [comment]
@haltman-at OK... touche; I now don't remember what problem I ran into that led me to care about this issue in the first place, but it apparently wasn't "non-dynamic structs" as I just tested that and it worked (and in fact so did dynamic structs). Maybe I had a dynamic array somewhere before (I have long since rearchitected all of my code to work around this issue, so it is hard to remember what I was doing before ;P). Regardless, thanks for the answer, and sorry about the useless question :) / :(.

**Comment by chriseth** [comment]
@haltman-at yes, please create an issue!

**Comment by haltman-at** [comment]
OK, did that as #10358!
