### ISSUE TITLE
Equality comparison for tuples.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#8919]
I'm not sure if we actually urgently need this as a language feature, but I found it rather annoying in writing tests that I can't do:

```
function f() public returns (uint256 a, uint256 b) { ... }
function g() public { assert(f() == (1, 2)); }
```

So I think allowing equality comparisons, i.e. ``==`` and ``!=``, for tuple expressions would be a nice convenience feature. For other operators like ``<`` there's no clear unique definition, so if we want this at all, we should stick to ``==`` and ``!=`` only.

**Comment by cameel** [comment]
@ekpyron Should we close this and make #9598 more general instead? Probably no point having two different issues covering this.

**Comment by ekpyron** [comment]
Resp. as part of general namable tuple types (not sure we actually have a proper issue for those yet). Closing this in any case, since it'll be covered by one separate issue or another.
