### ISSUE TITLE
Specify grammar in BNF

### ISSUE THREAD

**Issue by sri-rang** [ethereum/solidity#892]
Would help in adding support to many IDEs and tools. 

Will this be considered?

**Comment by axic** [comment]
Check out #717.

(There's a simple grammar at https://github.com/ethereum/solidity/blob/develop/libsolidity/grammar.txt)

**Comment by sri-rang** [comment]
I did, and I kind of modified it for making a Jetbrains / IntelliJ plugin.

But I don't trust my conversion to BNF, maybe I can make a PR for that and someone would like to review?

**Comment by VoR0220** [comment]
please do

**Comment by axic** [comment]
@Srirangan if you still have your BNF conversion, can you please submit it?

**Comment by chriseth** [comment]
I think this can be closed.

**Comment by federicobond** [comment]
There is also https://github.com/solidityj/solidity-antlr4, which is not exactly BNF, but it's executable and can be used to make an IntelliJ plugin.

Disclaimer: I am the author.
