### ISSUE TITLE
Gas estimator: Report transaction cost at least for constructor.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8920]
We could call it 'direct transaction cost'  because we do not know what else happens inside the transaction. Transaction cost includes execution cost plus cost for the payload (for the constructor this is the creation code plus constructor arguments, for functions this is function selector plus arguments). Since zero bytes have a different cost, we can assume the arguments to not contain any zeros to get an upper bound.

**Comment by hrkrshnn** [comment]
Is this only about the command line option `--gas`? If yes, should this really be in 'implementation backlog important', since this feature is barely used?

**Comment by cameel** [comment]
@hrkrshnn It's actually used by Remix and I think it's affecting people in practice. For example: https://github.com/ethereum/remix-project/issues/2539.

By the way, for whoever will be implementing this: the description here is pretty light on details so I recommend looking at #6724 for context. Especially at this SE answer linked there: [What is the difference between transaction cost and execution cost in remix?](https://ethereum.stackexchange.com/questions/5812/what-is-the-difference-between-transaction-cost-and-execution-cost-in-remix/29560#29560)

**Comment by hrkrshnn** [comment]
I don't think we should pursue this. The gas estimator cannot compare with an actual execution. For example, the rules for storage gas have become very complicated now, and the gas estimator computes this by "statically" looking at opcodes--we don't account for slots being warm or refunds. We should consider deprecating this.

**Comment by cameel** [comment]
You mean deprecating the whole estimator or just closing this issue?

And yeah, the estimator is not good enough in the current state but Remix is using it and some other projects might be too. The question is if there's a good replacement they could use.

We need to discuss this and make some decision - I'll add this to the agenda for Wednesday.

**Comment by cameel** [comment]
Closing because we decided to remove the gas estimator from the compiler: #13566.
