### ISSUE TITLE
Natspec version/kind

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8922]
It is currently not easy to tell apart userdoc/devdoc and hard to be backward/forward compatible because there is no notion of versioning.

How about introducing two meta fields: `@version` and `@kind`. Since all tags start with non-@ there should be no clash.

Alternatively use the hashmark (#) as a special sign.

`@version` would be 1 for the current version of Natspec.
`@kind` would be `user` for "userdoc" and `developer" for "devdoc".

**Comment by chriseth** [comment]
Can you explain a bit more how `@kind` would be used and why it is needed? `@notice` is the only user doc tag, so it would be kind of redundant.

**Comment by axic** [comment]
My description was hastily done so probably not clear enough, I mean these tags to be include in the JSON and not added by the user.

Currently the following JSON is output:
```
Developer Documentation
{
  "methods": {}
}
User Documentation
{
  "methods":
  {
    "f()":
    {
      "notice": "Some function."
    }
  }
}
```

After the change:
```
Developer Documentation
{
  "@version": 1,
  "@kind": "developer",
  "methods": {}
}
User Documentation
{
  "@version": 1,
  "@kind": "user",
  "methods":
  {
    "f()":
    {
      "notice": "Some function."
    }
  }
}
```

**Comment by chriseth** [comment]
Ok, I see! So the idea is to make the kind of the json structure visible even without context.

**Comment by axic** [comment]
Yes, and also to have a version so that we can make "breaking" changes to natspec.

**Comment by chriseth** [comment]
We should also have a field to specify the templating language / engine that is used for natspec.

**Comment by chriseth** [comment]
@ligi you might be interested in this issue.

**Comment by axic** [comment]
Some further options for version:
- `#version: 1`
- `doc_version: 1`
- `schema: "userdoc/v1"`
- `docschema: "devdoc/v1"`

**Comment by chriseth** [comment]
Decision from call: let's add `version` and `kind`.
