### ISSUE TITLE
macOS - Yosemite, El Capitan and Sierra hanging?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#894]
The Solidity unit tests appear to be hanging when running on OS X Yosemite, OS X El Capitan and macOS Sierra on TravisCI.

See, for example ... https://travis-ci.org/ethereum/solidity/builds/151825303

In this instances (and others), TravisCI aborts because it has received no TTY for 10 minutes.

It is possible that is true, but it seems very unlikely given the timing of the same step which is successful on Ubuntu Trusty and the OS X Mavericks, in 90 seconds and 3 mins respectively.

It looks like all Travis Mac projects are run using VMWare on a 2009 era Mac Pro which normally runs OS X Mavericks, so building/running on Mavericks is way faster, but I doubt that it would be 3/4x slower.

Get get the same issue on Ubuntu sometimes.

For now we will work around this issue by only running unit-tests on Trusty and Mavericks.   We can add the other macOS versions back in when we are able to do so reliably.

Intermittent failures are always worked around with retry functionality (https://github.com/ethereum/solidity/issues/769), but that doesn't help us if we get a hang now a failure.

**Comment by chriseth** [comment]
Closing as we are not doing and not planning to do the multi-platform tests this way.
