### ISSUE TITLE
[SMTChecker] ICE in set<const solidity::frontend::VariableDeclaration *> solidity::frontend::SMTEncoder::touchedVariables(const solidity::frontend::ASTNode &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8947]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract c {
	function f() internal returns (uint) {
	}
		bool b = (f() == 0) && (f() == 0);
	function g() public returns (bool) {
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1646): Throw in function set<const solidity::frontend::VariableDeclaration *> solidity::frontend::SMTEncoder::touchedVariables(const solidity::frontend::ASTNode &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  I threw ALL the .sol files under libsolidity into the corpus, so it's effectively fuzzing the SMTChecker and such now, also, I expect this will turn up some things.

## Environment

- Compiler version:  0.6.8-develop.2020.5.13+commit.1700bdc4.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by agroce** [comment]
declaration of `g` is not needed, but I can't get the duplicated `f() == 0` to go away with a reducer

**Comment by leonardoalt** [comment]
Reducing a bit more:
```
pragma experimental SMTChecker;
contract c {
    function f() internal returns (bool) {}
    bool b = f() && f();
}
```

**Comment by leonardoalt** [comment]
The second `f()` is needed because this is triggered by the code that does short circuiting.

**Comment by agroce** [comment]
I think this is only a partial fix.  Fuzzing latest I get:

```
pragma experimental SMTChecker;
contract c {
	uint x;
	function f() internal returns (uint) {
		x = x + 1;
	}
		bool b = (f() > 0) || (f() > 0);
}
```

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/VariableUsage.cpp(107): Throw in function void solidity::frontend::smt::VariableUsage::checkIdentifier(const solidity::frontend::Identifier &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

(that's with `Version: 0.6.9-develop.2020.5.28+commit.0b216f57.Linux.clang` -- it does fix my original and Leonard's minimized version)

**Comment by agroce** [comment]
@leonardoalt I think this is a partial fix; reopen or should I submit a new issue with the above code?  you've seen the original fix, is this just a variant corner case, or fundamentally different (if similar)?

**Comment by leonardoalt** [comment]
I need to look into it but can't really see why the previous fix wouldn't fix this as well, so reopening.

**Comment by leonardoalt** [comment]
Indeed, this is an effect of the PR that close it initially. That PR missed 2 lines of code that should be fixed by https://github.com/ethereum/solidity/pull/9068.
