### ISSUE TITLE
Invalid JSON file in repository

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#8954]
I'm trying to use the sample JSON files in this repository and found that one of them is not valid JSON. (It contains several objects separated by commas.) Would it be possible to split it into several valid JSON files?

https://github.com/ethereum/solidity/blob/f1af29f14901bf1b08a0df0b01344a4553797fae/test/libsolidity/ASTJSON/documentation.json#L41

**Comment by Marenz** [comment]
We fixed this now to be a proper json array of objects.
As a note, this isn't exactly a sample json file but more a test-expectation. In this case it is a bit "unrealistic" as the compiler would output something different, e.g.:

```
{
	"contracts": {
		"example.sol:C": {},
		"test.sol:Ownable": {}
	},
	"sourceList": ["example.sol", "test.sol"],
	"sources": { "example.sol": /* AST WITH DOC HERE */, "test.sol": /* AST WITH DOC HERE */ 
	},
	"version": "0.6.9-develop.2020.5.19+commit.126c286f.mod.Linux.g++"
}
```
