### ISSUE TITLE
ICE in solidity::yul::CodeGenerator::assemble: [Variable headStart is 2 slot(s) too deep inside the stack.]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8959]
## Description

This contract:
```solidity
pragma experimental ABIEncoderV2;

contract C {
	 function f1 (byte[][] memory, int[] memory, int16, string [] memory, address) public returns (int16[] memory, int16[] memory)
	 {}
	 function f2 (C, address) public returns (byte[] memory, int16[]memory)
	 {}
}
```

produces:

```
Exception during compilation: /home/user/solidity/libyul/backends/evm/AsmCodeGen.cpp(225): Throw in function static void solidity::yul::CodeGenerator::assemble(const solidity::yul::Block &, solidity::yul::AsmAnalysisInfo &, evmasm::Assembly &, langutil::EVMVersion, const solidity::yul::ExternalIdentifierAccess &, bool, bool)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::yul::YulAssertion>
std::exception::what: Stack too deep when compiling inline assembly: Variable headStart is 2 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Stack too deep when compiling inline assembly: Variable headStart is 2 slot(s) too deep inside the stack.
```

when compiled with solc, only with `--optimize`

Similar to #8369 except that happens with or without `--optimize`, and I'm speculating the `headStart` vs `dataEnd` may mean different problems with the assembly, so reporting separately.  The minimized code is sort of different also, the returns of tuples seem to be required here.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.6.8-develop.2020.5.13+commit.1700bdc4.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by wighawag** [comment]
I got a similar compiler issue : `YulException: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.`

The weird thing is that the issue appears after I add natspec doc on events.

Can't share the code right now, and will try to isolate more but maybe that can already help to know that simply adding natspec comment can cause this issue

**Comment by bshastry** [comment]
@agroce Does this issue still reproduce against the latest develop commit `9d6413df8`?

**Comment by agroce** [comment]
Just grabbed latest (probably past that one) and am running, have a few possible new things to report I'm checking, will check this too.  (Backlog of possible new bugs; I had mistyped a directory name in a triage script, and so was seeing last month's fuzz results, noticed eventually the hash was identical on four runs, which is impossible).

**Comment by agroce** [comment]
On 3d96e2b1 I get:

```
user@239d7503a8e2:~/solidity/test$ ../build/solc/solc cs.sol --optimize
Compiler error: Stack too deep when compiling inline assembly: Variable headStart is 2 slot(s) too deep inside the stack.
```

so "looks fixed to me"

**Comment by bshastry** [comment]
Thank you @agroce Marking the issue as closed
