### ISSUE TITLE
yul -> ewasm:  CompileError: WebAssembly.Module(): Compiling function #9 failed: expected 1 elements on the stack for return, found 0

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/solidity#8962]
## Description

I am trying to instantiate a WebAssembly module from the ewasm bytecode produced by `solc` from a `.yul` source and I get:

```
 CompileError: WebAssembly.Module(): Compiling function #9 failed: expected 1 elements on the stack for return, found 0 @+987
```

Full `solc` output: https://gist.github.com/loredanacirstea/cf38ace41b609b629293070cbc172216

Source:
```solidity
object "TestContract" {
    code {
        datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
        return(0, datasize("Runtime"))
    }
    object "Runtime" {
        code {
            let _calldata := 96
            calldatacopy(_calldata, 0, calldatasize())

            mstore(0, div(mload(_calldata), 10))
            return (0, 32)
        }
    }
}
```

The offending code is `div(mload(_calldata), 10)`.
If I replace the `Runtime` code with: 
```
        code {
            let _calldata := 96
            mstore(_calldata, 304)

            mstore(0, div(mload(_calldata), 10))
            return (0, 32)
        }
```
There is no error. So the problem appears when one of the `div` arguments are not known at compile time.

## Environment

- solc `0.6.8+commit.0bbfe453.Darwin.appleclang`
- execution environment: https://github.com/loredanacirstea/ewasm-jsvm, but it should be reproducible in any wasm setup.

## Steps to Reproduce

- compile the above `TestContract` source:
```
solc --strict-assembly --optimize --yul-dialect evm --machine ewasm ./tests/contracts/c.yul
```
- initialize wasm module with the compiled ewasm bytecode
```
const wmodule = new WebAssembly.Module(hexToUint8Array(bytecode));
```

**Comment by chriseth** [comment]
Should be fixed by https://github.com/ethereum/solidity/pull/9018
