### ISSUE TITLE
[SMTChecker] ICE in solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smt::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8963]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C
{
	struct S {
		uint x;
	}
	mapping (uint => S) smap;
	function f(uint y, uint v) public {
if (0==1)
		smap[y] = S(v);
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1481): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smt::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  I threw ALL the .sol files under libsolidity into the corpus, so it's effectively fuzzing the SMTChecker and such now, also, I expect this will turn up some things.

## Environment

- Compiler version:  0.6.8-develop.2020.5.13+commit.1700bdc4.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
This may be a duplicate of #8817

**Comment by leonardoalt** [comment]
> This may be a duplicate of #8817

I just tried it and they're unrelated.
https://github.com/ethereum/solidity/issues/8817 is specific to FP
