### ISSUE TITLE
Implement keccak256 polyfill for ewasm

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/solidity#8965]
Opening this issue to track `keccak256` implementation for ewasm. It was mentioned as being done in this PR's description: https://github.com/ethereum/solidity/pull/8049, but it is not: https://github.com/ethereum/solidity/blob/c1ed5bbb0ff078ff5cfe7287a603b1385e6d6ee9/libyul/backends/wasm/EVMToEwasmTranslator.cpp#L808-L811

**Comment by chriseth** [comment]
@axic is there some implementation we can use?

**Comment by axic** [comment]
I think this could be "esaily" translated to yul: https://github.com/axic/keccak-wasm

Or just include it in text form.

**Comment by chriseth** [comment]
esaily. eaxctly!

**Comment by chriseth** [comment]
We have to implement it in a way such that it does not need additional memory...

**Comment by axic** [comment]
> We have to implement it in a way such that it does not need additional memory...

Will be hard. In the "Ewasm 1.0" design it is suggested a keccak256 precompile would exists, I guess we could do that with EVMHost...

**Comment by cameel** [comment]
@aarlt This looks like the task you're working on right now so I'm adding you as "assigned" and moving to "in progress".

**Comment by NunoFilipeSantos** [comment]
We're closing all wasm issues for now.
