### ISSUE TITLE
yul -> ewasm : for loops are compiled to the first loop iteration only

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/solidity#8966]
## Description

If you compile Yul code with for loops to ewasm, you will only get the first loop iteration. 

## Environment

- Compiler version: `0.6.8+commit.0bbfe453.Darwin.appleclang`

## Steps to Reproduce

Full solc output: https://gist.github.com/loredanacirstea/a3a92e833e213af81ba12b38b36d7eba

```solidity
object "TestWasm11" {
    code {
        datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
        return(0, datasize("Runtime"))
    }
    object "Runtime" {
        code {
            let len := 4
            let result := 5

            for { let i := 1 } lt(i, len) { i := add(i, 1) } {
                result := add(result, i)
            }

            mstore(0, result)
            return (0, 32)
        }
    }
}
```

The result is `6` instead of `11`.

**Comment by chriseth** [comment]
This seems to be a problem with the optimizer - the condition is pulled out of the loop and not updated.

**Comment by chriseth** [comment]
It turns out that the break is actually there, so my current guess is that it is either an error in the polyfill or an error in the (recently added) binary transform.
