### ISSUE TITLE
[Lang Design] Solidity Community Call #0

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#8968]
## What

We want to introduce regular community calls where we discuss a selected language design topic (e.g. controversial feature request) and whether / how to implement it together with the community.

## Open Tasks

- [x] Define topic for Sol Community Call # 0 (fixed point types or SafeMath by default?)
- [x] Define topic owner and prepare discussion points for the call 
- [x] Upload key discussion points in this issue (bullet point agenda)
- [x] Choose date & time
- [x] Send invites via email and communicate via socials
- [x] Set up tech stuff for call, ~~livestream~~ and notes

**Comment by franzihei** [comment]
@chriseth @axic Which topic do we want to discuss in the first call?

**Comment by axic** [comment]
I have no preference over "fixed point types" or "safemath".

**Comment by chriseth** [comment]
Then I would suggest safemath. Discussion points:

 - unchecked area, checked area or specific functions/operators
 - what to do about exp: checking is very expensive
 - checks on explicit type conversions?
 - checks on shift (would assume no)
 - invalid opcode or revert

**Comment by franzihei** [comment]
Chosen date: 3rd of June, 5PM CEST
Franzi to send out invites and create "agenda issue".

**Comment by franzihei** [comment]
New issue is here and email invites will be sent out shortly. https://github.com/ethereum/solidity/issues/9054
