### ISSUE TITLE
Implement project board automation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8969]
Implement automation (maybe through github actions) for the following:
 - newly opened issues should be added to the "Solidity" project board under "new issues"
 - stale issues that are not in the icebox should get a "ping" comment

**Comment by mijovic** [comment]
For adding newly opened issues to "new issues", I think there is already automation which moves all new issues in "Solidity" project to "new issues". We just need to find a way to move newly created issues to "Solidity" project

**Comment by cameel** [comment]
Looks like github docs have some ready to use examples for these:
- [Moving assigned issues on project boards](https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards) + [Adding labels to issues](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues)
- [Closing inactive issues](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues) + [Commenting on an issue when a label is added](https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added)

Looks like they actually rely on third-party github actions.

Also one more idea for what we could do: assigning triage issues (and maybe PRs to review) to random team members. The assigned person has to either deal with it or give it to someone else, but has to do *something*.

**Comment by cameel** [comment]
Another idea: adding PRs labeled `takeover` to the `Takeover column` on the Focus Board.

**Comment by cameel** [comment]
@r0qs We talked with @ekpyron today about next steps here.
- One would be to finalize #13499 but do it only for PRs for now.
- Second, to implement the idea with adding new issues to the board. Since permissions are a problem we'll do it like this:
    - Rename `New Issues` column on the [old board](https://github.com/ethereum/solidity/projects/43) to `Triage` and start adding new issues there for now until we figure out if we can do it for the focus board.
    - Clear the `New Issues` column. As it is now it's not very useful.

**Comment by cameel** [comment]
I cleared the column an renamed it (actually deleted it and created a new one).

Also, I have an idea for how we can work around the board not being able to handle solc-js issues. We could just add notes with links. Not great but better than not being able to manage them at all.

**Comment by cameel** [comment]
As for new boards, looks like PAT seems to be the only way forward and we do want to move on to them if only because github is very likely to deprecate old ones at some point. So once devops creates a custom account for us, we could move on with that.

**Comment by r0qs** [comment]
> * Rename `New Issues` column on the [old board](https://github.com/ethereum/solidity/projects/43) to `Triage` and start adding new issues there for now until we figure out if we can do it for the focus board.

I made a simple workflow to move new issues to triage in the old project board: https://github.com/ethereum/solidity/pull/13528

I saw that you created a `Solidity triage` board. What is the purpose of that board?

> As for new boards, looks like PAT seems to be the only way forward and we do want to move on to them if only because github is very likely to deprecate old ones at some point. So once devops creates a custom account for us, we could move on with that.

Yes, using a PAT with organization permission to the `Solidity Focus` or `Solidity triage` board, we can concentrate all issues on the same board by just adding the automation in both repos. A GH app also works, we only need to install it on both repos, or install the app in the org with permission to both repos.

**Comment by cameel** [comment]
> I saw that you created a Solidity triage board. What is the purpose of that board?

Just a temporary place for me and @ekpyron to keep track of which old issues we have already labeled. For the purpose of this issue you can just ignore it.

**Comment by cameel** [comment]
Just renamed it to avoid confusion with the triage column.

**Comment by cameel** [comment]
We'll probably want to close this in favor of #13615.

**Comment by r0qs** [comment]
Closing in favor of https://github.com/ethereum/solidity/issues/13615
