### ISSUE TITLE
ICE in solidity::frontend::Type::calldataEncodedSize(bool) const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#8974]
## Description

This contract:
```solidity
contract test {
     struct S { uint d;
    mapping(uint8 => uint8)[2] b; }
    function f(S memory _s) internal {
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.h(218): Throw in function virtual unsigned int solidity::frontend::Type::calldataEncodedSize(bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  I threw ALL the .sol files under libsolidity into the corpus, so it's effectively fuzzing the SMTChecker and such now, also, I expect this will turn up some things.

## Environment

- Compiler version:  0.6.9-develop.2020.5.18+commit.142a6b0d.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by chriseth** [comment]
The struct contains a mapping. Might be related to other issues about mappings in memory.

**Comment by hrkrshnn** [comment]
You can reduce this issue to
```solidity
contract test {
    function f(mapping(uint => uint)[2] memory b) internal {
    }
}
```

~~The linked issue won't close this perfectly.~~ The linked PR will fix this.

Here's where the throw comes from.
```cpp
	/// @returns number of bytes used by this type when encoded for CALL. Cannot be used for
	/// dynamically encoded types.
	/// Always returns a value greater than zero and throws if the type cannot be encoded in calldata
	/// (or is dynamically encoded).
	/// If @a _padded then it is assumed that each element is padded to a multiple of 32 bytes.
	virtual unsigned calldataEncodedSize([[maybe_unused]] bool _padded) const { solAssert(false,""); }
```

**Comment by chriseth** [comment]
Closed by https://github.com/ethereum/solidity/pull/9146
