### ISSUE TITLE
InternalCompilerError when passing bytes[] calldata to bytes[] memory

### ISSUE THREAD

**Issue by niklasb** [ethereum/solidity#8981]
## Description

The compiler errors out when passing a `bytes[] calldata` argument to another function that expects a `bytes[] memory` argument.

## Environment

- Compiler version: Solidity - 0.6.8 (solc-js)
- Target EVM version (as per compiler settings): istanbul
- Framework/IDE (e.g. Truffle or Remix): Truffle v5.1.25 (core: 5.1.25)
- EVM execution environment / backend / blockchain client: /
- Operating system: macOS Mojave

## Steps to Reproduce

Compile the following code

```solidity
pragma solidity ^0.6.8;
pragma experimental ABIEncoderV2;

contract Test {
    function foo(bytes[] calldata test) external { bar(test); }
    function bar(bytes[] memory test) internal {}
}
```

The output is: 

```
InternalCompilerError: I sense a disturbance in the stack: 2 vs 3
```

This is reduced from a larger file with the above construct included. With the larger file the error surfaced differently, I assume the compiler segfaulted or crashed:

```
> Compiling ./contracts/Token.sol
Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:616:24)
    at execSync (child_process.js:661:15)
    at Object.compile (/Users/niklas/cashlink/smart-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/Docker.js:19:1)
    at invokeCompiler (/Users/niklas/cashlink/smart-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:257:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at run (/Users/niklas/cashlink/smart-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:29:4
```

I can provide repro for that case as well if required.

**Comment by chriseth** [comment]
I'm pretty sure we already have this bug somewhere else.

**Comment by niklasb** [comment]
ok my search was bad. dupe of #7929

should I close?

**Comment by chriseth** [comment]
Ah thanks! Closing as duplicate.

**Comment by redneckanarchist** [comment]
I Just had this issue following Erc20 and solidity, 
after removing _params, indent override code compiled. 
`  function executeOperation(
        address _reserve,
        uint256 _amount,
        uint256 _fee,
        bytes calldata 
        //function foo (bytes[] calldata params) external { bar(_params); }
        //function bar(bytes[] memory params)
        
    )   
            external
            override
    {`
