### ISSUE TITLE
Enable Yul to Wasm compilation in standard compiler

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8986]
The `compileYul` function should output wasm if a wasm artifact is requested like for solidity. The way to compile yul to wasm is mainly via `AssemblyStack::translate`.

**Comment by axic** [comment]
@chriseth don't we have this enabled already?

**Comment by chriseth** [comment]
You are right! Can you change the documentation accordingly (it still says "not yet supported")?
