### ISSUE TITLE
[codegen] ICE because _targetType != typeOnStack.arrayType();

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8991]
## Description

```
contract C {
  function f(int[] calldata b) external { [b[:]]; }
}
```

throws

https://github.com/ethereum/solidity/blob/678a801daf44b563272ed9c699caac8087dc7ee1/libsolidity/codegen/CompilerUtils.cpp#L1017

## Environment

- Compiler version: latest develop
## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by bshastry** [comment]
This commit https://github.com/ethereum/solidity/commit/309f0fbc8a6c2e13d5e67e8c4d72404a4e8ca1e3
 marks the conversion of calldata arrays to memory arrays an unimplemented feature.

This means the example in this issue no longer reproduces as per the original report but reports "Conversion from calldata slices to memory not yet implemented."

We can do one of two things:
  - Edit this report and make it track "Implement conversion from calldata slices to memory"
  - Create a new issue for this and close this one

@chriseth What do you think?

**Comment by chriseth** [comment]
There are several related unimplemented features with regards to copying from calldata. Maybe we could summarize them and create a single issue? Problems I could see:

 - copying calldata slices to memory or storage
 - copying calldata structs to memory or storage

I could have missed others.

**Comment by axic** [comment]
Still happening, but at least with an indicative message:
```
Unimplemented feature:
/Users/alex/Projects/solidity/libsolidity/codegen/CompilerUtils.cpp(1057): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type &, const solidity::frontend::Type &, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Conversion from calldata slices to memory not yet implemented.
[solidity::util::tag_comment*] = Conversion from calldata slices to memory not yet implemented.
```
