### ISSUE TITLE
Storage of String in memory

### ISSUE THREAD

**Issue by yann300** [ethereum/solidity#90]
with this: 
string pp = "value1";
The DataLocation is indeed Storage, but the content seems to be stored in Memory.

**Comment by chriseth** [comment]
`string pp = "value1";` should not be valid Solidity - the compiler should reject it, but even if it accepts it, it should write to storage.

**Comment by yann300** [comment]
i don't know if this is related, but when I have this: 
function arrayTest(uint[4] h)
{
    uint[4] memory copy = h;
}
the DataLocation of "copy" is not set.
