### ISSUE TITLE
Group compiler warnings and errors output

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum/solidity#9002]
## Abstract

Solidity compiler warnings and errors are output sequentially as they are emitted, making it difficult to read. This impacts is most prominent when working on contract updates between solc versions, example below is a small chunk of the output on the `argent-contracts` repo when I switched part of the contracts from 0.5.4 to 0.6.8. Can you spot the `ParserError`?

![Screenshot 2020-05-21 at 09 49 14](https://user-images.githubusercontent.com/703848/82531685-7c162c80-9b48-11ea-8b1c-f039b7da4957.png)

## Motivation

Instead of outputting compiler messages sequentially in the order produced, it will be very useful for a developer working on them that these are grouped by the type of warning or error.

## Specification

All warnings and errors of a certain type are grouped under a heading with the warning text, listing below the failing instances. For example all  `SPDX license identifier not provided in source file` warnings can be grouped into 1 with that heading, listing below the failing file and line number if applicable. 
To demonstrate with an abbreviated example from above:
```
,/Users/Elena/Source/argent-contracts/contracts/modules/ApprovedTransfer.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/CompoundManager.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/GuardianManager.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/LockManager.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/NftTransfer.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/RecoveryManager.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/SimpleUpgrader.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/TokenExchanger.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
,/Users/Elena/Source/argent-contracts/contracts/modules/TransferManager.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
```
becomes

```
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
    ,/argent-contracts/contracts/modules/ApprovedTransfer.sol: 
    ,/argent-contracts/contracts/modules/CompoundManager.sol
    ,/argent-contracts/contracts/modules/GuardianManager.sol
    ,/argent-contracts/contracts/modules/LockManager.sol
    ,/argent-contracts/contracts/modules/NftTransfer.sol
    ,/argent-contracts/contracts/modules/RecoveryManager.sol
    ,/argent-contracts/contracts/modules/SimpleUpgrader.sol
    ,/argent-contracts/contracts/modules/TokenExchanger.sol
    ,/argent-contracts/contracts/modules/TransferManager.sol
```

Additionally, it maybe useful that error groups are reported at the top, followed by warnings as it is currently rather difficult to spot errors amongst all output. This is especially true when working on migrations where large compiler set of warnings and errors is generated.

**Comment by chriseth** [comment]
This sounds like it could be difficult to implement when considering how IDEs use the compiler (they assume one location per error). I see that this could be useful when using solc in the commandline and when you are not really trying to fix all warnings.

Can you explain what your workflow is and why you would not just fix one reported error / warning after the other?

**Comment by elenadimitrova** [comment]
Now you said this I realise it should really be a feature of the IDE, not the compiler output, but since most devs including myself still use the command line for compilation the mindset is such that it should be provided there. I'll look into integrating this feature in the https://github.com/juanfranblanco/vscode-solidity extension perhaps. Any other ideas are welcome

**Comment by elenadimitrova** [comment]
Logged with IDE instead as it better fits there https://github.com/microsoft/vscode/issues/98819

**Comment by sw7240614** [comment]
That is a lot of word

On Thursday, June 4, 2020, Elena Gesheva <notifications@github.com> wrote:
> Logged with IDE instead as it better fits there microsoft/vscode#98819
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/e1ptrOoonZj0mLlHcGur4v-j5At2-yx6Q1gTUkHhyrpIwbKNmSmdNoPnStgH9bFMfV-Qt67WtWbKe4Qm-u3KLVBZi8JQoW3XK_7Oro1HUWKDKAxEirhr_n8in9f9ciZIUCJH6Ux1ZhRxF8DXxRgMFikkY4_g5Zx8Am1bkOjdZMzUAsK041eGz1iApg6_AkKIblfYvOTUOy-nbSj-RDFyHjesmp7VDRzD6t7i1MfKVQ=s0-d-e1-ft#https://github.com/notifications/beacon/APC5IPYYFUIFUH6WM7RPE7DRU7IJLA5CNFSM4NGTC6DKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEYLCPFA.gif
>

-- 
null
