### ISSUE TITLE
smtCheckerTests got "Test expectation mismatch"

### ISSUE THREAD

**Issue by ssi91** [ethereum/solidity#9005]
## Description

Hi all. I've faced with a problem. Some of the smtCheckerTests got "Test expectation mismatch".
For example:
```bash
solidity/build$ ./test/soltest -t smtCheckerTests/array_members/pop_loop_unsafe
Running 1 test case...
solidity/test/boostTest.cpp:112: error: in "smtCheckerTests/array_members/pop_loop_unsafe": Test expectation mismatch.
Expected result:
  Warning: (150-157): Empty array "pop" detected here.
Obtained result:
  Warning: (135-142): Empty array "pop" might happen here.
  Warning: (150-157): Empty array "pop" might happen here.
```

Most of them are mismatched some warnings, though there are a few where a warning was expected but got `Success`.
I haven't been able to understand yet whether it's a problem related to my laptop or it's global one

## Environment

- Compiler version: Version: 0.6.9-develop.2020.5.21+commit.32bec6b3.mod.Darwin.appleclang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Mac OS X 10.15.3 (19D76)

## Steps to Reproduce

Build and run `soltest`

**Comment by leonardoalt** [comment]
The smtCheckerTests are expected to work with the latest z3 version.
Which version did you compile with?

**Comment by ssi91** [comment]
@leonardoalt `Z3 [version 4.8.7 - 64 bit]`

**Comment by leonardoalt** [comment]
@ssi91 please try with z3 4.8.8, that's the latest version that was recently released, our tests were updated according to that version

**Comment by ssi91** [comment]
> @ssi91 please try with z3 4.8.8, that's the latest version that was recently released, our tests were updated according to that version


@leonardoalt well, it solved the issue. Thanks a lot.

Couldn't find out what a patch version of a library could impact so :)
