### ISSUE TITLE
Strange solfuzzer-only failure

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9009]
## Description

This contract:
```solidity
contract C {
	constructor(uint x) public {
	}
}
abstract contract B is C {
	constructor(uint x) public {
	}
}
contract A is B {
	constructor(uint x) B(x) C(~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x * 2) public {
	}
}
```

produces a very large, complex output ending in `Fuzzer failed...` when compiled with solfuzzer, but passes with solc (with or without --optimize, etc.)

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  I threw ALL the .sol files under libsolidity into the corpus, so it's effectively fuzzing the SMTChecker and such now, also, I expect this will turn up some things.

## Environment

- Compiler version:  0.6.9-develop.2020.5.21+commit.32bec6b3.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
When I tried to reproduce locally, the error originates from a deeply nested call to libjsoncpp's `readValue()` call. It is either from here

https://github.com/open-source-parsers/jsoncpp/blob/c161f4ac69633deb2ed43bc8569cb9b183f63c32/src/lib_json/json_reader.cpp#L157

or from here

https://github.com/open-source-parsers/jsoncpp/blob/c161f4ac69633deb2ed43bc8569cb9b183f63c32/src/lib_json/json_reader.cpp#L1053

My guess is that this has to do with the large number of NOT operations `~` in the call to `C`'s constructor from `A`'s constructor

- When solc parses this, it presumably creates a lot of nested json values
- When this nested json is being parsed during output formatting, `libjsoncpp` runs out of stack space

**Comment by agroce** [comment]
Not really a bug; not sure what even is sensible to do about this other than manual triage it away if it shows up again (it's fairly tough for the fuzzer to construct, I think, so not a huge pain for fuzzing)

**Comment by bshastry** [comment]
@agroce Could we close this issue since it is not a solidity issue?

**Comment by agroce** [comment]
Sure!
