### ISSUE TITLE
[solc] ICE because type cannot be encoded in calldata

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9013]
## Description

```
contract C {
  function f() public pure {
    [type(int)];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/7e1f26270b92762d0de3235adad9890fbbb869dd/libsolidity/ast/Types.h#L218

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by hrkrshnn** [comment]
Possible duplicate of https://github.com/ethereum/solidity/issues/9004

**Comment by bshastry** [comment]
Closing cos duplicate.
