### ISSUE TITLE
Deposit contract wishlist

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9017]
- [x] #8925
- [x] #8922 - @Marenz 
- [x] #8911 - @Marenz 
- [ ] #8908 
- [x] #8776 - @hrkrshnn 
- [x] #8716 
- [x] #7738
- [x] #8853

**Comment by hrkrshnn** [comment]
@axic What about merging dev and user doc?

Both https://github.com/ethereum/solidity/issues/8776 and https://github.com/ethereum/solidity/issues/8922 can use merging.

The new merged doc will also contain the ABI JSON.

**Comment by chriseth** [comment]
If we merge dev doc, user doc and abi json, isn't this just the metadata then? :)

**Comment by axic** [comment]
This is now moot, as the deposit contract is *finalised*.
