### ISSUE TITLE
[SMTChecker] ICE because array push not supported on dynamically sized arrays within structs

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9021]
## Description

```
pragma experimental SMTChecker;
contract C {
  struct S {
    int[] b;
  }
  S s;
  function f() public { s.b.push(); }
}
```

throws

https://github.com/ethereum/solidity/blob/370350da07a158f0a3a68efc5e1f65583e19b57e/libsolidity/formal/SMTEncoder.cpp#L1150

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by leonardoalt** [comment]
Nice, this triggers exactly the `solAssert(false)` I wasn't sure how to trigger, was looking for such cases

**Comment by bshastry** [comment]
Reopening because the following new fuzzer test case throws the same ICE

```
pragma experimental SMTChecker;
contract C {
        int[][] array2d;
        function l() public {
                array2d.push().push();
        }
}
```
