### ISSUE TITLE
Weird source map behaviour for simple failed transfer

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/solidity#9025]
## Description

Source map behaves in an interesting way following a failed transfer.

## Environment

- Compiler version: `0.6.8`
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: JS VM
- Operating system: OS X 10.15.3

## Steps to Reproduce

```solidity
contract TokenSaleChallenge {
    mapping(address => uint256) public balanceOf;
    uint256 constant PRICE_PER_TOKEN = 1 ether;
    uint256 numTokens = 30;

    function test() public returns(uint256) {
        msg.sender.transfer(numTokens * PRICE_PER_TOKEN);
        return 2;
    }
}
```

The source map for this contract behaves in a confusing way after `msg.sender.transfer`, in particular it jumps back to the mapping `balanceOf`. Can reproduce it in Remix by running `test()` function after deployment.

**Comment by chriseth** [comment]
I'm pretty sure this is caused by the source mapping referring to an internal routines. Internal routines are marked by the special source index `-1`. There used to be a bug in remix ignoring this `-1`. I spent some time searching for the issue but could not find it. @yann300 do you maybe know more? Thanks!

**Comment by yann300** [comment]
I think that might be related to https://github.com/ethereum/remix/issues/1477 , we'll be posting a fix soon

**Comment by chriseth** [comment]
Thanks, @yann300 !
