### ISSUE TITLE
[Notes] Community Discussion SafeMath by Default 

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#9054]
# What
The Solidity team would like to discuss language design related questions with the community on a regular basis. This issue is to track the first discussion round's outcomes and can be used for note taking or to facilitate the meeting. 

# When 
The discussion round on SafeMath by Default will take place on **Wednesday, 3rd of June at 5PM CEST**. The link to the video call has been circulated via email.

You can find other time zones [here](https://savvytime.com/converter/ny-new-york-city-to-ca-san-francisco-germany-berlin-singapore-singapore).

# Topic & Discussion Points

**SafeMath by Default**

- unchecked area, checked area or specific functions/operators
- what to do about exp: checking is very expensive
- checks on explicit type conversions?
- checks on shift (would assume no)
- invalid opcode or revert

**Comment by franzihei** [comment]
Thank you for joining everyone! Here are the notes from our first call: https://hackmd.io/6z3-BIIsS227l-8iR5_NzA

**Comment by nventuro** [comment]
There's a point I forgot to bring up, which is iteration. How should users write a `for` loop that has no (uncessary) checked arithmetic?
```
for (uint256 i = 0; i < array.length; ++i) {
  ...
}
```

Given what we've discussed so far, we'd want to use `unchecked`, but this would also make the `for`'s body `unchecked`, forcing users to wrap their body in a function.

```
unchecked {
  for (uint256 i = 0; i < array.length; ++i) {
    foo(array[i]);
  }
}
```

I'm not sure what's the best way to tackle this. Perhaps having some sort of iterator type that has no checks? This isn't unheard of in languages like C++ or Rust where `size_t` and `usize` exist (though for different reasons).

**Comment by axic** [comment]
Could range based loops be an alternative? Then the compiler would be sure no overflow happens.

**Comment by nventuro** [comment]
I believe so, yes. I didn't mention those to try to reduce scope of this.

**Comment by chriseth** [comment]
@nventuro are you talking about the check in `++i`? In the new code generator, the compiler should be able to get rid of it and for the old generator, if it is not possible to optimize that, then the following should work:

```
for (uint256 i = 0; i < array.length; unchecked { ++i } ) {
  ...
}
```
