### ISSUE TITLE
No homebrew release for solidity 0.5.16 or 0.5.17

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#9061]
I cannot install solidity 0.5.16 from homebrew because it was never released.
https://github.com/ethereum/homebrew-ethereum

**Comment by wjmelements** [comment]
I suspect the available versions are enumerated here: https://github.com/ethereum/homebrew-ethereum/commits/master/solidity.rb

**Comment by axic** [comment]
0.5.16 / 0.5.17 were released after 0.6.0 so they can be found here: https://github.com/ethereum/homebrew-ethereum/blob/master/solidity%405.rb (also latest can be installed via `brew install solidity@5`)

**Comment by wjmelements** [comment]
Thank you

**Comment by wjmelements** [comment]
The command to install is

```
brew install "https://raw.githubusercontent.com/ethereum/homebrew-ethereum/master/solidity@5.rb"
```

**Comment by axic** [comment]
```
brew install solidity@5
```
works for me

**Comment by sw7240614** [comment]
Thanks


On Thursday, May 28, 2020, Alex Beregszaszi <notifications@github.com>
wrote:
> brew install solidity@5
>
> works for me
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/uGVUKxibQSUfUnb2ykT9gwAiBp1dkTN01ryYFY-ZUvfBzVz2lSCPLzNip-tYcjR3TR4sIuCtcM4RsymdHNF6FcPZQAgMFONK0VEtnJSBOpkEbnaLrsDyqKxOiTeivXt8hROsJRtDonpvPuimcHrXgjNIXHEBg06BpbgYzQJ9aB2tQfTIVpyyz_-EEedT4EDp8h2CYM9ocGcmk61xstnms_KuIc62mF9bCBnaYw-Y9Q=s0-d-e1-ft#https://github.com/notifications/beacon/APC5IP3FM6UKQDLDERUW4ULRT3WLZA5CNFSM4NNQQLIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEXRX6YQ.gif
>

-- 
null
