### ISSUE TITLE
modules / namespaces / template areas

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9063]
While there is a namespacing mechanism through the way of files (in connection with the various import statements), people from the community voiced the concern that if we allow functions at the file level (#8787), then logical grouping is harder to do and `using A for B` is not as easy.

In connection to the current proposal about how to implement templates (https://github.com/ethereum/solidity/issues/869#issuecomment-624541988), these namespaces could be extended to template areas. A template area would be similar to a template library in https://github.com/ethereum/solidity/issues/869#issuecomment-624541988 in that only functions with internal calling semantics, type definitions and maybe interfaces are allowed - nothing that can or is expected to be deployed at an address.

Syntax:

```
namespace <name>[T1, T2] {
   struct X {
       T1 a;
       T2[] b;
    }
    function f(X calldata, T2) returns (uint) {
        ...
    }
}
```

**Comment by chriseth** [comment]
Some more ideas: https://gist.github.com/chriseth/7f087fc42c4c2d115bc04b8fe6948d69

**Comment by cameel** [comment]
The issue is very outdated. It was related to the C++-template-plan that we dropped in the end. We may end up having some explicit non-file based module thing, but not like described in the issue, so it can be closed.
