### ISSUE TITLE
Disallow override for non-public state variables.

### ISSUE THREAD

**Issue by ddeclerck** [ethereum/solidity#9065]
When a public state variable overrides an external functions, it doesn't seem to check that the overriden function is marked "virtual" (while if we override with a function, then the overriden function MUST be marked "virtual").

The following typechecks without error nor warnings:
```
contract C1 {
  function f() external pure returns(int) { return 42; }
}

contract C is C1 {
   int override f;
}
```

It should report something like "Trying to override non-virtual function."

**Comment by chriseth** [comment]
Note that in the example, `C.f` is not public, and thus cannot even override anything.

**Comment by ekpyron** [comment]
The actual solution here is to disallow ``override`` for state variables that aren't ``public``, right?

**Comment by chriseth** [comment]
Sounds like a plan!
