### ISSUE TITLE
State variables not considered as valid overriding functions in override check when multiple inheritance (Solidity 0.6.8)

### ISSUE THREAD

**Issue by ddeclerck** [ethereum/solidity#9066]
In presence of multiple inheritance, the typechecker seems to ignore state variables that correctly override multiply-defined methods.

The following outputs an error ("Derived contract must override function f"):
```
contract C1 {
  function f() external pure virtual returns(int) { return 42; }
}

contract C2 {
  function f() external pure virtual returns(int) { return 42; }
}

contract C is C1, C2 {
   int override(C1, C2) f;
}
```

**Comment by chriseth** [comment]
Duplicate of #9065 - `C.f` is not public.
