### ISSUE TITLE
ICE in solidity::u256 solidity::frontend::ArrayType::storageSize() [Array too large for storage]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9077]
## Description

This contract:
```solidity
contract C {
    struct X { bytes31 [ 3 ] x1 ;
        }
        uint [ 2 ** 0xFF ] [ 2 ** 0x42 ] s2 ;
        struct S { uint256 [ ] [ 0.425781 ether ] s1 ;
        }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.cpp(1777): Throw in function virtual solidity::u256 solidity::frontend::ArrayType::storageSize() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Array too large for storage.
[solidity::util::tag_comment*] = Array too large for storage.
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer. 

## Environment

- Compiler version:  0.6.9-develop.2020.5.28+commit.0b216f57.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
A single large storage array is sufficient to trigger this bug.

```
contract C { bytes[8**80][114514] i; }
```

**Comment by Marenz** [comment]
duplicate of #9099, closing.
