### ISSUE TITLE
Will ethereum 2.0 support solidity?

### ISSUE THREAD

**Issue by ERC20s** [ethereum/solidity#9081]
I'm building a casino style dapp on ethereum..
I'm hoping to use the random number from the beacon chain for my games..
Anyone know the costs of this?
And if it will work like that?
Oh yeah..
And will eth2.0 support solidity or do i need to something else?

**Comment by chriseth** [comment]
eth2.0 will not support smart contracts in the first phase. Once it is ready for smart contracts, it will of course support Solidity.

Closing as neither bug nor feature proposal for Solidity.
