### ISSUE TITLE
[SMTUtil] ICE via SMTLogicError due to "_n.sort->kind != Kind::Int"

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9087]
## Description

```
pragma experimental SMTChecker;
contract C {
  function f() public {
    (byte("") & (""));
  }
}
```

throws

https://github.com/ethereum/solidity/blob/0a71e415013c8ae712de0c519a22aef2cf1c2119/libsmtutil/SolverInterface.h#L203

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by agroce** [comment]
Ah, yes, didn't see this due to scan for the failure text not present here.  Looks the same to me in symptoms at least, and structure
