### ISSUE TITLE
[solc] ICE because "object too large for storage"

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9099]
## Description

```
contract C {
    bytes1[8**80][1701455] a;
    bytes1[8**80][1701455] b;
}
```

throws

https://github.com/ethereum/solidity/blob/97cb091ada06080bfd8ad9f28413875490b52be0/libsolidity/ast/Types.cpp#L188

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by bshastry** [comment]
At first glance, it seems that the `StorageOffsets::computeOffsets` function maintains a single slot offset variable of type `bigint`. Since slot offset is incremented for every storage variable, it may overflow `U256_MAX`.

**Comment by Marenz** [comment]
This might be a duplicate of https://github.com/ethereum/solidity/issues/9077

**Comment by axic** [comment]
This fixed in develop.
