### ISSUE TITLE
Documentation for reason strings added by `revertStrings`

### ISSUE THREAD

**Issue by fvictorio** [ethereum/solidity#9100]
Is there some place where this is documented?

The motivation here is to see how this could be leveraged by external tools (see https://github.com/nomiclabs/buidler/issues/624 for example).

**Comment by chriseth** [comment]
The compiler should provide strings for all compiler-generated reverts. This mostly concerns abi decoding.

**Comment by chriseth** [comment]
What do you want to know?

**Comment by fvictorio** [comment]
The scope of this errors. Is there a list of those compiler-generated reverts? Or at least some examples to get a better a idea of what they include?

**Comment by chriseth** [comment]
You can search for `revertReasonIfDebug`.

**Comment by chriseth** [comment]
Since this is more a question than a proposal, I'm closing this. The places where reverts happen are documented, but I don't think we should document the exact strings used.
