### ISSUE TITLE
[Sol->Yul] Support exponentiation in constants

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9110]
The following should compile:
```
    uint constant DEPOSIT_CONTRACT_TREE_DEPTH = 32;
    // NOTE: this also ensures `deposit_count` will fit into 64-bits
    uint constant MAX_DEPOSIT_COUNT = 2**DEPOSIT_CONTRACT_TREE_DEPTH - 1;
```
This previously attempted by #8945.

Closes #8853.

**Comment by chriseth** [comment]
I don't think this is different from regular 'exp'.

**Comment by axic** [comment]
It is not, unless we would have constant expressions. Is there a tracking issue for support `exp` in sol-yul?

**Comment by chriseth** [comment]
The value of the constant is just treated as a regular expression: https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L196
