### ISSUE TITLE
Why to copy read-only arguments into the stack?

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#9114]
It seems CALLDATACOPY costs the same as DUP but requires no space in stack reserved for this local variable.

## Abstract

Arguments that are not modified could be accessed directly from call data instead of copying them from stack to stack again and again.

## Motivation

This would reduce stack size and fix a lot of "Stack too deep" issues

**Comment by chriseth** [comment]
I'm not sure I understand. `calldatacopy` copies to memory and not to the stack. It also requires multiple arguments. `calldataload` copies to the stack, but also requires an offset that needs to be potentially computed and pushed. The latest version of Solidity (about to be released in the next days) allows you to use the `calldata` data location for structs and arrays everywhere and could be almost what you are suggesting.

**Comment by k06a** [comment]
@chriseth sorry, I meant CALLDATALOAD for sure. I meant it could be used for integral (<= 32 bytes) types as well.

**Comment by chriseth** [comment]
To be honest, I don't think restricting value types to calldata explicitly is easily doable. You get that by using calldata structs, and it is advisably anyway to group variables into structs when dealing with many function parameters.
