### ISSUE TITLE
Investigate soljson.js memory leaks.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9130]
Creating an empty contract, setting remix to "auto-compile" and keeping to add and remove empty lines to the contract (waiting just long enough for remix to actually start recompiling) apparently seems to let the process memory usage grow without bounds and eventually causes remix to stall e.g. on cursor movement...
I'm experiencing this on recent Archlinux and Firefox 76.0.1.
I'm still figuring out which versions are affected or if it's all of them, but noticed it for 0.6.8 and 0.6.9 already.
This may be an issue in Firefox or in Remix and not in solidity - but we should still try to figure out what's going on there and what platforms and browsers are affected...

**Comment by ekpyron** [comment]
Just confirmed with ``soljson-v0.5.13-nightly.2019.11.6+commit.56a3abcd.js`` - which is *not* a wasm build.

But on the other hand I *don't* have the problem on chromium - not sure that means "not our fault".

**Comment by ekpyron** [comment]
Seems to be related to the remix debugger rather than us... I'm closing this again for now.

**Comment by sw7240614** [comment]
I am sorry


On Thursday, June 4, 2020, Daniel Kirchner <notifications@github.com> wrote:
> Seems to be related to the remix debugger rather than us... I'm closing
this again for now.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/X6arlJZN7E5TmiB8AdpyrQ8DDL-NmdLhSMkx5BbEMhp6N6R0aMxKpcwTDaYVHsrejH7d8agZkOSiqv7gaUFLazkn2QD4w3wS7VdW4cmZACZd_43iTIjHQWYRWOcc9OZGpp3y1JfOsQshUd924Fd92hMFxEga1Pyd25JO9bxiRq3edGtPuIS57ZTc-kp3c289vuiqlDwkB_qPH469-ymtIsrDKDJ613Vq00bDxywQBw=s0-d-e1-ft#https://github.com/notifications/beacon/APC5IP6R6CKQ3B2IC35RF3DRU7M6NA5CNFSM4NS2LPMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEYLHO6I.gif
>

-- 
null
