### ISSUE TITLE
Make actually running SMT queries configurable via standard-json.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9136]
Since soljson.js now includes Z3, any source with the smt pragma will actually run the Z3 queries. That will slow things down and there's no way to prevent it without actually removing the pragma, which changes the source code hash in the metadata the compiler produces.
For example source-verification won't benefit from the SMT warnings - but it will need perfectly matching source code.

So it should be possible to disable the builtin solver via standard-json. Maybe in a similar way in which we have "enabled solvers" in our test runs - or in some other way.

Having this be configurable also makes sense for the ``solc`` - not sure we need a command-line argument as well, but having it there via standard-json as well is at least not a problem.

**Comment by axic** [comment]
Why would anyone have the pragma and not wanting to run the solver?

**Comment by chriseth** [comment]
Would it be a good solution to just make the resource limit configurable? A limit of 0 would switch it off.

**Comment by ekpyron** [comment]
> Why would anyone have the pragma and not wanting to run the solver?

In case someone kept it while deploying and you want to source-verify? Or if Z3 is broken for your example and spins with 100% CPU usage until the resource limit is reached, but you want to still provide a callback that calls cvc4 and solves it immediately?

To me the latter potential situation indicates that it's not exactly the resource limit only - although being able to configure that might be good as well...

**Comment by axic** [comment]
> That will slow things down and there's no way to prevent it without actually removing the pragma, which changes the source code hash in the metadata the compiler produces.

This is now solved with `--model-checker-engine none` (and the same in JSON) after #10036. @ekpyron can we close this?

**Comment by ekpyron** [comment]
Ah yes - last time I saw #10036 it was CLI only, but it looks like it did it for standard-json as well in the end, so yes, this can be closed I think.
