### ISSUE TITLE
Comments starting with multiple stars wrongly recognized as natspec docstring

### ISSUE THREAD

**Issue by sirhill** [ethereum/solidity#9139]
## Description

The following code generate a warning in 0.6.9:
```
/***** STORAGE *****/
MyStruct storage data = MyStruct(0);
```

```
> Compilation warnings encountered:

    /home/node/project/contracts/MyContract.sol:50:18: Warning: Only state variables can have a docstring. This will be disallowed in 0.7.0.
    MyStruct storage data =
                  ^------^
````

The error message might as well be improved and enlight the natspec comments instead.

## Environment

- Compiler version: starting from 0.6.9
- Target EVM version (as per compiler settings): 0.6.9
- Framework/IDE (e.g. Truffle or Remix): truffle

**Comment by interfect** [comment]
I'm having the same problem with headings marked off by runs of slashes. The compiler mistakes them for doc comments. Here's an example:

```
pragma solidity ^0.6.10;

library MacroverseNFTUtils {

    //////////////
    // Code for working on token IDs
    //////////////
    
    // Define the types of tokens that can exist
    uint256 constant TOKEN_TYPE_SECTOR = 0;
}

// SPDX-License-Identifier: UNLICENSED
```

This is raising a warning something like this:

```
contracts/MacroverseNFTUtils.sol:41:5: Warning: Documentation tag on non-public state variables will be disallowed in 0.7.0. You will need to use the @dev tag explicitly.
    //////////////
    ^------------^
```

Do I really have to go through my codebase and redo all my section headings to stop the compiler throwing errors when 0.7 comes out (and a bunch of warnings now)?

**Comment by a3d4** [comment]
@interfect Fix is coming (for both /*** and //// comments).

**Comment by k06a** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/702124/90032384-ff1dcd80-dcc6-11ea-8fc3-a23ad9dfe5cd.png">
