### ISSUE TITLE
SOLC optimizer crash with misleading error message

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#9147]
## Description

SOLC compiler crashes with undescriptive error:
```
Exception during compilation: /solidity/libyul/backends/evm/AsmCodeGen.cpp(225): Throw in function static void solidity::yul::CodeGenerator::assemble(const solidity::yul::Block&, solidity::yul::AsmAnalysisInfo&, solidity::evmasm::Assembly&, solidity::langutil::EVMVersion, const solidity::yul::ExternalIdentifierAccess&, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what: Stack too deep when compiling inline assembly: Variable value1 is 2 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Stack too deep when compiling inline assembly: Variable value1 is 2 slot(s) too deep inside the stack.
```

### Expected Behaviour:
- at a minimum, give source file/method/contract that caused the crash.
   It was very easy to fix the method (and for the sample file below, it was even enough to remove the `pragma experimental` at the top - which I can't in my real project), but without knowing which file to check, it was a very tedious to troubleshoot.
- If possible, fix optimizer (e.g. copy into memory some calldata parameters as needed)

## Environment

- Compiler version: `Version: 0.6.8+commit.0bbfe453.Linux.g++`

- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): solcjs, solc-docker
- Operating system: Mac, Linux

## Steps to Reproduce

`solc --optimize YulOptimizerCrash.sol`
(note that the code passes compilation without `--optimize`)

```
// SPDX-License-Identifier:MIT
pragma solidity ^0.6.2;
pragma experimental ABIEncoderV2;

contract YulOptimizerCrash {

    string public constant GENERIC_PARAMS="param";
    string public constant GENERIC_TYPE="type";

    function registerRequestType(string calldata typeName,string calldata extraParams, string calldata subTypes, string calldata subTypes2) external pure returns(bytes memory){
        string memory comma = bytes(extraParams).length > 0 ? "," : "";

        bytes memory str = abi.encodePacked(
            typeName, "(",
            GENERIC_PARAMS, comma, extraParams, ")",
                subTypes, GENERIC_TYPE, subTypes2
        );

        return str;
    }
}
```

**Comment by chriseth** [comment]
The "stack too deep" error means that you have too many local variables (including parameters). The general recommendation is to use a struct instead of multiple function parameters. I know this is not ideal and the error message could be better.

I'm closing this since we already have other issues about the same problem.

**Comment by drortirosh** [comment]
The issue is not the "stack to deep": it's the error message: it should give the developer a clue where in the source tree to look for.
Without source file (and if possible, method it like number), it's very hard to find the cause and fix it.

**Comment by chriseth** [comment]
@drortirosh Yes, that's what I meant with "error message could be better" - sorry for being sloppy.
