### ISSUE TITLE
Static build for linux

### ISSUE THREAD

**Issue by rainbreak** [ethereum/solidity#915]
It is easy to build a fully static solc binary, which is portable across all linux distributions. I propose that solidity automates this as part of the github release and provides a downloadable static binary.

Implementation example: https://github.com/rainbeam/solidity-static

**Comment by bobsummerwill** [comment]
I am thoroughly in support of this, @rainbeam.

Thanks for the working example :-)

We'll get this in the backlog for me.

**Comment by chriseth** [comment]
@chfast you did some work on static builds recently, did that also help with solidity?

**Comment by chfast** [comment]
I will help with it here, but have not found time yet.

**Comment by rainbreak** [comment]
@chfast @chriseth @bobsummerwill fixed by https://github.com/ethereum/solidity/pull/1796 :smiley:

**Comment by bobsummerwill** [comment]
Awesome!
