### ISSUE TITLE
Documentation update: interfaces can now declare state variables

### ISSUE THREAD

**Issue by shanefontaine** [ethereum/solidity#9152]
The latest [Solidity 0.6.9 docs](https://solidity.readthedocs.io/en/v0.6.9/contracts.html#interfaces) state that:

> Interfaces are similar to abstract contracts, but they cannot have any functions implemented. There are further restrictions:
>  * ...
> * They cannot declare state variables.

It appears this is no longer the case as I am able to now declare state variables in my project, however it is unclear to me when this restriction was lifted.

**I suggest removing that bullet point from the documentation if it is true that this restriction was lifted.**

**Comment by chriseth** [comment]
The restriction has not been lifted - can you provide an example that made you think it has?

**Comment by shanefontaine** [comment]
You are correct. I had switched the order of inheritance which made me falsely believe it was working as expected. Will close now. Thank you.
