### ISSUE TITLE
Using dots instead of underscores for inline assembly ``_slot``, ``_offset``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9169]
Given the discussion in https://github.com/ethereum/solidity/issues/7646, i.e. mainly given the idea to reserve dots for special identifiers in solidity inline assembly yul, we could consider transitioning ``_slot`` and ``_offset`` for storage variables to ``.slot`` and ``.offset`` instead. If yul identifiers with dots cannot be used in inline assembly anyways, unless they refer to something outside in solidity, this would cause less conflicts.
Not sure what we'd do about e.g. with ``enum E { slot, offset }`` - it can't conflict, but might be confusing.
If we do this for storage, we should also do it for calldata, i.e. for https://github.com/ethereum/solidity/issues/8917.

**Comment by ekpyron** [comment]
Related: PR for enums https://github.com/ethereum/solidity/pull/7641

**Comment by cameel** [comment]
In Python name clashes like this are solved by having a special naming convention for built-in properties:
```
value.__slot__
value.__offset__
```
A bit ugly but when you get used to it, it's really apparent that this is not a user-defined field.

**Comment by chriseth** [comment]
This sounds good! I don't think we need a way to avoid conflicts, because identifiers that support such "sub-identifiers" cannot be used without them anyway.

**Comment by chriseth** [comment]
Discussion: Just use `.slot` and `.offset` (and similar for calldata)

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/9285
