### ISSUE TITLE
Meta-Issue: management in Backlogs via Timeouts

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9171]
We wanted to automate the process of moving issues around in the project board if they remain untouched for a certain amount of time.
What exactly should happen?
After two weeks (exact time to be decided) inactivity move everything from the backlogs to the Icebox? Or to something intermediate and then again after a week from there into the icebox?

**Comment by ekpyron** [comment]
Once specified we can implement this using whatever automation tools github provides - if there's no other options github actions should work (apparently https://github.com/ethereum/devops/issues/284 concluded in us being able to use those).

**Comment by ekpyron** [comment]
Ah, I think we said, we move issues directly to the icebox, but post a comment to the issue, s.t. anyone involved gets notified and can move it back, if desired.

**Comment by chriseth** [comment]
Discussion:
 - comment on issues stale for 4 weeks and move them into the icebox
 - add new issues to the "new issues" column of the Solidity project automatically.

**Comment by axic** [comment]
Can we merge this issue into #8969 ?

**Comment by cameel** [comment]
After talking it over with @ekpyron we decided to close it in favor #8969 as suggested here. The issues say basically the same thing.
