### ISSUE TITLE
Solidity Portal

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#9175]
## UPDATE
I moved the current status of the portal from my MVP repo to the official rep. Now the code is here: https://github.com/ethereum/solidity-portal

---

As I mentioned in a couple of team calls, we're thinking about creating a dedicated Solidity portal to have a one-stop shop page with all links and relevant information about the language for the community.

To make the decision and process transparent and easier, I started with a case study looking at how other languages (Rust, Go, C++, JS, Python) handle this. I summarised my findings in [this document](https://docs.google.com/document/d/1TAY1x2pitkLyNtojT_J61SucNMrc61GmdmYsLaesRjg/edit?usp=sharing). You can additionally have a look / get inspired by the [Geth website](https://geth.ethereum.org/).

## What should be on the portal?

I'm in the process of laying it out more clearly, but I'll imagine there to be links to / dedicated sections for: 
- What is Solidity (one-liner and value prop)
- Download section
- Docs and reading 
- Latest news (with blog preview and Twitter feed preview)
- Contributing
- Security, responsible disclosure and bug bounty links
- Links to all social platforms, mailing list etc.
- Tools and external links
- Info on how to use the Solidity brand

## Open Tasks

- [x] Select domain
- [x] Select content we want to display 
- [x] Decide about setup
- [x] Work on layout and design
- [x] [...] and more 

As a next step I'll lay out which content and links I would recommend to put on such a portal and try to sketch the interface so that it's easier to relate. 

Happy about any comments and thoughts!

**Comment by axic** [comment]
Could also revive @erak's [solidity tour](https://github.com/erak/solidity-tour) project. [See in action](https://erak.github.io/solidity-tour).

**Comment by franzihei** [comment]
Here's a [first rough wireframe](https://docs.google.com/presentation/d/1pmxEp6tv4nH8hr4_I-YApPqtDG-Pa2i48uW7KR62ljM/edit?usp=sharing) which shows a structure and a proposal for topics I would add to the first iteration of the language portal.

**Please disregard design, colors and text** - this is only for imagining and deciding on which topics we want to include and how they could roughly be structured.

**Comment by franzihei** [comment]
## Updates
- Decided to go with **soliditylang.org** for now; I registered it already. We also still have solidity.ethereum.org, which could all eventually be merged / redirected into the portal vice-versa (later).
- Agreed on topics & content to go into the MVP portal version 0.1
- Will find a Jekyll theme and place content for a rough prototype next.

**Comment by franzihei** [comment]
## Another Update :)

I've selected a simple landing page template ("hydra") and put in our preliminary content blocks. You can find it here: https://github.com/franzihei/solidity-portal-initial-mvp. 

**Open issues:** 

- [x] Design: We have to align on font, colors used (especially the highlight colors are absolutely not carved in stone, we can change them)
- [x] Adding Solidity logo in big in the header section
- [x] Adding the Solidity compiler preview (so far there's a screenshot as placeholder)
- [x] Adding social icons in the footer for Github and Gitter
- [x] Check whether any content is missing
- [x] Check all texts for accuracy

Once we're happy with the MVP: 

- [x] move it to the solidity-portal repo (and remove the "forked from" stuff)
- [x] get it up and running on soliditylang.org

**Open issues outside of the portal:** 

- [x] Update documentation in the contributing section
- [x] Update documentation with a short "getting started" section which is similar to the [C++ Get Started](https://isocpp.org/get-started) page.

Please have a look @axic @chriseth. :)

Also, for some reason the github page (https://franzihei.github.io/solidity-portal-initial-mvp/) is currently not building but I will look into this tomorrow. You can build the site locally using `jekyll serve`.

Edit: Github pages built works. : )

**Comment by franzihei** [comment]
# Updates

Hey there, it's been a while and I'd like to push the Solidity portal to the next stage. 

~~The current status can be seen here: https://franzihei.github.io/solidity-portal-initial-mvp/ ~~

The current status is here: https://github.com/ethereum/solidity-portal

## Open To Dos and Blockers

- [ ] fix Solidity compiler to look better and consider including different code examples there with a drop down menu (see "Try Go" section here: https://golang.org/)
- [x] merge #9773 before getting the portal life
- [x] move portal to solidity-portal repo
- [x] review all texts for typos and accuracy
- [x] decide on hosting (github pages with custom domain vs. netlify?)
- [x] go live at soliditylang.org

**Who can help with the compiler bits?**

Also, would we, in future, be interested in having a dedicated Solidity playground? Similar to...
- https://play.rust-lang.org/
- https://play.golang.org/

**Comment by axic** [comment]
I think the site looks great!

There's one formatting  issue:
![Screenshot](https://user-images.githubusercontent.com/20340/93447990-fa9e9300-f8ca-11ea-9b2a-630e8247ff87.png)

> decide on hosting (github pages with custom domain vs. netlify?)

I'd just go with github pages and call it a day. If it doesn't work out well we can think about moving it, but that's the easiest path for now.

**Comment by franzihei** [comment]
Moved code / the entire repo

from: https://github.com/franzihei/solidity-portal-initial-mvp
to: https://github.com/ethereum/solidity-portal

I *hope* this worked. 😇 

Edit: I also added Sam (ethereum.org web dev team) to the repo, who might be able to help us with some web dev stuff if needed.

**Comment by franzihei** [comment]
Thanks @chriseth for your work on the solidity compiler! Is it possible to also add different example contracts so that people can play with it a bit or do you think that doesn't make sense at the moment?

**Comment by chriseth** [comment]
We should add some examples, certainly!

**Comment by franzihei** [comment]
"The falcon has landed" - (v0.1 up and running at soliditylang.org) 🦅 🥳
