### ISSUE TITLE
Docs should be updated to build `Release` compiler by default

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/solidity#9194]
## Description

When attempting to build the compiler from source, I follow the instructions, e.g, here: https://solidity.readthedocs.io/en/v0.6.10/installing-solidity.html#command-line-build

```bash
mkdir build
cd build
cmake .. && make
```

It turns out this misses a step that _does_ happen in the next direction given:

```bash
./scripts/build.sh
```

which is to set the build type as `Release` (instead of `Prerelease`).

It would be nice if the docs above were updated to reflect the correct way to configure `cmake` so that the default build is `Release`. I ran into this a few times when working on a recent smart contract and wanted to use the latest version of the compiler:

```solidity
pragma solidity ^0.6.10
// some cool dapp
```

would fail w/ the source build according to the first block of instructions as it outputs a `Prerelease` compiler.

## Environment

NOTE: this is solely (?) a documentation issue.

- Compiler version: v0.6.9 and v0.6.10 but this has likely been around before those versions of the compiler
- Target EVM version (as per compiler settings): ...
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: Geth
- Operating system: macOS

## Steps to Reproduce

See above.

**Comment by chriseth** [comment]
Building directly from the git source code will result in a prerelease version unless special measures are taken. I would recommend to build not from git but using the .tar.gz that is linked on the release page.
