### ISSUE TITLE
ICE in auto solidity::frontend::TypeChecker::visit(const solidity::frontend::InlineAssembly &)::(anonymous class)::operator()(const yul::Identifier &, yul::IdentifierContext, bool) const [FixedPointType not implemented.]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9199]
## Description

This contract:
```solidity
contract A { function f() pure public {
    fixed16x2 c =12345678901234567* 134562324532464.23445233*16*45678901234567890123456789;
        assembly {
            c := sar(0xd0, sar(0x40,  a))
       }
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/analysis/TypeChecker.cpp(719): Throw in function auto solidity::frontend::TypeChecker::visit(const solidity::frontend::InlineAssembly &)::(anonymous class)::operator()(const yul::Identifier &, yul::IdentifierContext, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: FixedPointType not implemented.
[solidity::util::tag_comment*] = FixedPointType not implemented.
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  I threw ALL the .sol files under libsolidity into the corpus, so it's effectively fuzzing the SMTChecker and such now, also, I expect this will turn up some things.

## Environment

- Compiler version:  0.6.11-develop.2020.6.13+commit.08b7d007.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by hrkrshnn** [comment]
We currently don't have proper error messages when fixed point variables are accessed. I think the ICE is okay here.
