### ISSUE TITLE
Get storage location of variable

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#92]
The new "libraries" feature will not be very useful if we cannot give the library information about what is where in storage.

```
contract Example {
    address A;
    function update(Library L) {
        L.get_latest(&A);
    }
}
```

**Comment by chriseth** [comment]
The difference between value- and object-types is a general concept in many programming languages including JavaScript: If you pass an integer to another function, the original integer cannot be modified in the called function. On the other hand, if you pass an object or a struct, the original struct will be modified if the called function modifies individual members.
The same semantics apply to Solidity for storage types in external (i.e. only library) calls and to storage and memory types in internal calls.
The story that will allow internal (e.g. struct) types for library calls is here: https://www.pivotaltracker.com/story/show/101774798

**Comment by nmushegian** [comment]
I think you misunderstood the issue.

Soon libraries will have direct access to storage, right?

Now suppose I use a contract which the library is not aware of, but I want the library to manipulate a storage variable which is statically allocated in the contract.

How is the library supposed to know the storage location of that variable?

**Comment by chriseth** [comment]
If a contract calls a library function and supplies a storage reference variable, the library will be able to use that. It is not as visible anymore because of the bound functions, but here is an example: https://github.com/ethereum/dapp-bin/blob/master/future_solidity/iterable_mapping.sol

**Comment by nmushegian** [comment]
Ok, so do I need to wrap value types into reference types to be able to modify their value in storage via a library?
