### ISSUE TITLE
[Yul -> Ewasm] Code generator produces infinite loops

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9205]
## Description
Yul->Wasm translation produces `for` loops that repeat the initialization code in every iteration. The effect is an infinite loop.

From Yul code like this:
```yul
for { <init> } <condition> { <increment> }
{
    <body>
}
```
we get wasm like this:
```wasm
(loop $loop_label
    <init>
    <condition>
    <body>
    <increment>
    (br $loop_label)
)
```
This is wrong because jumping to `loop_label` repeats the `<init>` block in each iteration. 

## Environment
- Compiler version: `develop` (>= 0.6.10)

## Steps to Reproduce
- Check out `evmc-vms-evm-ewasm` branch from #9143 which allows you to execute wasm tests on [hera](https://github.com/ewasm/hera).
- Build `soltest`
- Put this example in `test/libsolidity/semanticTests/tmp/test.sol`
    ```solidity
    contract test {
        function f(uint x) public pure returns(uint r) {
            for (uint i = 0; i < 5; i++)
            {
                for (uint j = 0; j < 5; j++)
                {
                    x++;
                }
            }
            return x;
        }
    }
    // ====
    // compileToEwasm: also
    // compileViaYul: true
    // ----
    // f(uint256): 0 -> 0x19
    ```
- Run `soltest`:
    ```bash
    soltest --run_test=semanticTests/tmp/* -- --vm <path-to-evmone>/libevmone.so --vm <path-to-hera>/libhera.so —evm-version=byzantium --no-smt --show-messages
    ```
- It hangs.

The test hangs.

**Comment by chriseth** [comment]
I think the assumption here was that the "for loop init rewriter" was used before translation to wasm.

**Comment by chriseth** [comment]
But of course it would be cleaner to just introduce a new block or "pull out" the init part.
