### ISSUE TITLE
[using...for] std::bad_cast exception because user defined type is mistaken for a library

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9217]
## Description

```
library L {
        struct S {}
        function r() {
                S memory x;
                x.d;
        }
        using S for S;
}
```

throws

`std::bad_cast` here

https://github.com/ethereum/solidity/blob/8d3c2ba6d9c911943d65e0e69300bb9428aafa11/libsolidity/ast/Types.cpp#L389-L391

because the referenced declaration is actually a `struct` not a `contractdefinition`

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by bshastry** [comment]
Funnily enough member access `x.d` is needed to trigger the bad cast. A more meaningful example is when the struct actually contains a member called `d` but this is not strictly required to trigger the exception.

**Comment by chriseth** [comment]
I just touched that piece of code in a PR and will take a look.
