### ISSUE TITLE
How does block deduplication work in the compiler?

### ISSUE THREAD

**Issue by ouerum** [ethereum/solidity#9219]
Hello, I wonder how to block deduplication work in the compiler, and where you get the idea to implement block deduplication optimization to reduce the code size of a smart contract. It is hard for me to find papers or blogs about this optimization technique. Thanks for your comments.

**Comment by chriseth** [comment]
The Solidity compiler implements deduplication. It is quite easy: So you basically go through all the pairs of jumpdests and compare the code starting from there. If you find two pairs that compare equal, you exchange all references to labels for one of the jumpdest by the other jumpdest. Then you repeat.

You can of course also keep track of jumpdests that are supposed to be equal while you do the comparison and you can also compare the code in a less strict way.

If you want to know more, please come to our chat room at https://gitter.im/ethereum/solidity-dev - github issues are not very well suited for discussions.
