### ISSUE TITLE
Add SPDX license identifier to the compiler source code

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9220]
Since we advocate for this in Solidity programs, we should bite the bullet and also include it in all the compiler source code 🙊

**Comment by sacgrover** [comment]
Hey,
I would like to work on it. Do you have any more information about it?

**Comment by chriseth** [comment]
@sacgrover thanks for wanting to help out! I think what @axic meant is adding the appropriate
```
// SPDX-License-Identifier: GPL-3.0
```
to all source files of the compiler that are GPL-3-licensed.

**Comment by sacgrover** [comment]
Okay, Thanks. I will dig into it more. Please assign this to me.

**Comment by sacgrover** [comment]
One Question, SPDX-License-Identifier will always be GPL-3.0 or it can have different value?
and when we say source files. Does it mean abis json that get created?

**Comment by chriseth** [comment]
If the license snippet in that file is gpl, then it is gpl. I think we might also have some mit files.
