### ISSUE TITLE
Rewrite Yul grammar in ANTLR

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9222]
And have it also tested like Solidity's.

Should also consider merging the grammar for Yul and "Yul Objects".

Closes #4622.

**Comment by chriseth** [comment]
It is part of the Solidity antlr grammar - can we somehow reuse it?

**Comment by axic** [comment]
I just looked at it, but don't think so. Also the Solidity one is very liberal (supports jump labels) as it tries to parse really old sources too.

I have moved the grammar from `yul.rst` and used the low level stuff from `Solidity.g4`.
