### ISSUE TITLE
ICE when referring to a library via a module name

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9229]
##  Description
The compiler allows importing a Solidity module from within itself. If you do this and try to refer to a library by qualifying it with the name of the module, `StackHeightChecker::check()` fails which results in an internal compiler error.

## Environment
- Compiler version: `develop` (>= 0.6.10)

## Steps to Reproduce
`a.sol`:
``` solidity
import "a.sol" as A;

library L {
    function f() internal pure {}
}

contract C
{
    function test() public pure {
        A.L;
    }
}
```

Result:
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ContractCompiler.cpp(77): Throw in function void {anonymous}::StackHeightChecker::check()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: I sense a disturbance in the stack: 0 vs 1
[solidity::util::tag_comment*] = I sense a disturbance in the stack: 0 vs 1
```
Interestingly the error goes away if you change `A.L` to `A.L.f()`.

**Comment by christianparpart** [comment]
I think it has nothing to do with self referencing, as the following causes the same:

```solidity
// a.sol
library L {
    function f() internal pure {}
}
```

```solidity
// b.sol
import "a.sol" as A;

contract B {
    function test() public pure {
        A.L;
    }
}
