### ISSUE TITLE
Struct member names can shadow type names within the struct

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9231]
##  Description
The compiler allows struct members to have the same name as an existing struct, enum and contract type. This can cause some inconsistent behavior.

For example, this works perfectly fine (using enum as a member type):
```solidity
enum E {a, b, c}
struct T {E T;}
```

But this works too (using enum as a member name):
```solidity
enum E {a, b, c}
struct T {uint E;}
```

On the other hand, you can't do this (using both at the same time):
```solidity
enum E {a, b, c}
struct T {E T; uint E;}
```
```
Error: Name has to refer to a struct, enum or contract.
 --> test.sol:2:11:
  |
2 | struct T {E T; uint E;}
  |           ^
```
The error indicates that the compiler does not see `E` as an enum in this context.

I haven't found any buggy behavior related to this but having a member with the same name as a type might be confusing and might prevent you from using that type inside the struct in the future so I think it might be better not to allow it.

## Environment
- Compiler version: `develop` (>= 0.6.10)

**Comment by chriseth** [comment]
I think we should first fix reference resolution inside a struct to not consider the members at all - there is no way to use unqualified access to a member of a struct. Because of that, I would also be hesitant to disallow user-defined type names as member names.
