### ISSUE TITLE
[SMTChecker] ICE because "lComponents.size() != rComponents.size()"

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9233]
## Description

```
pragma experimental SMTChecker;
contract C {
        function f() public {
                (((,))) = ((2),3);
        }
}
```

throws

https://github.com/ethereum/solidity/blob/b1d22ab2c8de9d5cecf05ec169b2414d1bfa4538/libsolidity/formal/SMTEncoder.cpp#L1460

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by bshastry** [comment]
FWIW syntax of `(((,))) = ((2),3)` seems to be
  - LHS: tuple of tuples of tuples
  - RHS: tuple of tuples

How is this syntactically valid since RHS has one fewer tuple dimension? I'm worried if this is rather a bug in the parser and not SMT Checker.

Edit: The following parses successfully (note: without smt checker pragma)

```
contract C {
        function f() public {
                (((,))) = ((2),3);
        }
}
```

**Comment by leonardoalt** [comment]
I think the way this is interpreted on the LHS is that if you have a tuple of one element, you can discard the outer tuple. This happens to the first 2 levels of the LHS, ending up with a tuple of 2 elements, which fits the RHS.

**Comment by leonardoalt** [comment]
Whether this should be the accepted behavior or not I'm not sure.
