### ISSUE TITLE
ICE in solidity::frontend::CompilerUtils::rotateStackUp(unsigned int) [Stack too deep, try removing local variables.]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9242]
## Description

This contract:
```solidity
pragma experimental ABIEncoderV2;
contract C {
    uint[] public b;    function f2(uint[] memory, string[] memory, uint16, address) public returns ( uint16[] memory,uint[] memory) {}    function f4( string[12] memory,uint32[] memory, address, bytes[2][] memory) public returns (uint[] memory, C, uint16, address, uint16[] memory, address,uint16[210] memory,uint16[200] memory, string[20] memory, C, address, string[] memory, uint32, address, string[] memory, uint16[] memory) {}function f6(uint[31] memory) public returns (string[21] memory ) {}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/codegen/CompilerUtils.cpp(1325): Throw in function void solidity::frontend::CompilerUtils::rotateStackUp(unsigned int)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Stack too deep, try removing local variables.

```
when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  I threw ALL the .sol files under libsolidity into the corpus, so it's effectively fuzzing the SMTChecker and such now, also, I expect this will turn up some things.

Probably not a bug -- that's a bunch of parameters, but hadn't seen this pattern and location of stack depth crash before, in case it matters.

## Environment

- Compiler version:  0.6.11-develop.2020.6.21+commit.b1d22ab2.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by chriseth** [comment]
This is just a regular "stack too deep" error.

**Comment by agroce** [comment]
@chriseth Should I just completely ignore all Stack Too Deep ICEs, in any location?

**Comment by chriseth** [comment]
Yes, I think that would be more useful.

**Comment by hrkrshnn** [comment]
@agroce https://github.com/ethereum/solidity/pull/9281 might be relevant
