### ISSUE TITLE
Derived interface must overide

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#9249]
Here is a minimal example to reproduce the behaviour I'm strugling with:

    pragma solidity ^0.6.0;
    
    interface IA {
        receive() external payable;
    }
    interface IB {
        receive() external payable;
    }
    interface IAB is IA, IB
    {}

What happens:
---

Compilation Error: `TypeError: Derived contract must override function "". Two or more base classes define function with same name and parameter types.`

Why I think this is not the right behaviour
---

If I add implementation of the `receive` methods in contract A and B, and if I had AB inherit from A and from B then I would have to select with implementation to use. However, unlike contracts, interfaces should not care about the actual implementation of the methods they define. 
The fact that this method is part of both interface just means its part of the concatenation. The implementation of the interface has to disambiguate, but not the interface itself.

I believe the code above should be valid, and interface AB should contain the receive method (and only that)

**Comment by chriseth** [comment]
You can override a function without providing an implementation:
```
pragma solidity ^0.6.9;

interface IA {
    receive() external payable;
}
interface IB {
    receive() external payable;
}
interface IAB is IA, IB
{
    receive() external override(IA, IB) payable;
}
```

**Comment by chriseth** [comment]
The reason why the compiler requires you to provide this explicit override is that it wants the developer of an interface to state that the two potentially different functions with the same name and signature coming from the two bases are actually the same thing conceptually and not just named equally.
