### ISSUE TITLE
Allow all unit denominations as identifiers

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#9256]
https://github.com/ethereum/solidity/pull/9230 made me think it would make sense (and make the code more consistent) if we'd allow all unit denominations to be also used as identifiers, as we did with gwei in that PR.

**Comment by chriseth** [comment]
I think that unit denominations should be keywords to avoid confusion. The reason we allowed gwei is to be able to get it in as a non-braking change. We should make it a keyword starting from 0.7.0

**Comment by Marenz** [comment]
Fair enough. Maybe we should make a deprecated warning in that case for gwei as variable name

**Comment by christianparpart** [comment]
Conclusion:

reduce ambiguity of keywords that can *also* be identifiers (to be merged into next breaking release)
