### ISSUE TITLE
Incomplete documentation about compiler metadata

### ISSUE THREAD

**Issue by VersusF** [ethereum/solidity#9262]
## Description

Compiling a contract results is a bytecode with the metadata not matching what declared in the official documentation.

This happens with various 0.5.x versions. The bytecode ends with "0040" instead of "0032" as declared, moreover it differents in the beginning ("a3" instead of "a2") and after the swarm hash there are other bytes containing the word "experimental". The documentation should be updated.

## Environment

- Compiler version: v0.5.17+commit.d19bba13 (Although we discovered for other 0.5.x too)
- Target EVM version (as per compiler settings): Default
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: - 
- Operating system: Linux amd64

## Steps to Reproduce

- Download the source code of contract [0x66718faccc5d6bd88cdf78797f9ecdb8745dae54](https://etherscan.io/address/0x66718faccc5d6bd88cdf78797f9ecdb8745dae54#code)
- Compile it with Remix (Or see the contract bytecode directly on Etherscan)
- The bytecode ends with "0040" instead of "0032" as declared in the [official documentation](https://solidity.readthedocs.io/en/v0.5.17/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode)

The metadata format we discovered is the following:
```
0xa3
0x65 'b' 'z' 'z' 'r' '1' 0x58 0x20 <32 bytes swarm hash>
0x6c 'e' 'x' 'p' 'e' 'r' 'i' 'm' 'e' 'n' 't' 'a' 'l' 0xf5
0x64 's' 'o' 'l' 'c' 0x43 <3 byte version encoding>
0x00 0x40
```

<br>

Thanks in advice

**Comment by leonardoalt** [comment]
The documentation does not represent all possible formats for the metadata, it is an example.
Your case contains `experimental` because it is a flag in the metadata, triggered by the usage of `pragma experimental ABIEncoderV2;`.

**Comment by chriseth** [comment]
Copied from the documentation:
```
The CBOR mapping can also contain other keys, so it is better to fully decode the data instead of relying on it starting with 0xa265. For example, if any experimental features that affect code generation are used, the mapping will also contain "experimental": true.
```

I don't see any way to adapt the documentation to better represent this case.
