### ISSUE TITLE
selfdestruct() and Private functions

### ISSUE THREAD

**Issue by digiblackdranzer** [ethereum/solidity#9264]
Solidity has a compilation rule that private functions cannot be payable, it even throws compile time error stating “TypeError : Private  functions cannot be payable”. However, there is one primitive of Solidity which is payable and bypasses this check. selfdestruct() is a function in contract which is capable of destroying entire contract and transferring amount deposited at contract to some other account (whose address is passed as argument)

Smart Contract : 

```solidity
contract Wallet {   
  mapping (address => uint) public credit;
  address owner;
 
  constructor() public
  {
      owner=msg.sender;
  }
    
  function deposit() public payable {
    credit[msg.sender] += msg.value;
  }
    
  function withdraw(uint amount) public {
    if (credit[msg.sender]>= amount) {
      msg.sender.transfer(amount);
      credit[msg.sender]-=amount;
    }
  }
 
  function checkBalance() public view returns(uint)
  {
      return credit[msg.sender];
  }

  function secretDrain(address x) private
  {
      selfdestruct(x);
  }
 
  function () public
  {
      secretDrain(owner);
  }
 
}
```
Fun thing about this contract is that the private function is not even visible to other account holders in the contract interaction interface so only the contract owner knows about it. A remix interface is attached in image below.
![105](https://user-images.githubusercontent.com/11799579/85879253-a8803100-b7f7-11ea-8074-0e0c00058349.png)

**Comment by leonardoalt** [comment]
@digiblackdranzer I'm not sure I get your point.
`secredDrain` isn't payable, so it can't receive Ether, which is not related to `selfdestruct`.

**Comment by digiblackdranzer** [comment]
I may have got a wrong idea but here's what my understanding is as for now :
1) secretDrain() would be known to only contract owner right ? Since it's a private method it won't be visible to other peers (Inferencing this from remix interface to interact with contract, I mean other peers will be able to see deposit(), credit() etc. as shown in figure but they won't be able to see secretDrain() there).
2) I'm assuming contract owner is malicious here and he can call secretDrain() anytime from either fallback function or some other private function and only contract owner will be aware of this and other peers will come to know about this after the contract is destroyed.

3) So my point was why shouldn't there be access modifier like payable for selfdestruct() as well so as to stop this phenomenon and people won't be able to include selfdestruct() in private functions.

Please help me out if I'm wrong.

P.S : I'm new to Github and Ethereum 😅 . So please bear with me.

**Comment by hrkrshnn** [comment]
> secretDrain() would be known to only contract owner right ? Since it's a private method it won't be visible to other peers (Inferencing this from remix interface to interact with contract, I mean other peers will be able to see deposit(), credit() etc. as shown in figure but they won't be able to see secretDrain() there).

[This](https://ethereum.stackexchange.com/questions/6547/solidity-functions-private-visibility) maybe relevant.

**Comment by digiblackdranzer** [comment]
Oh ok I got it. Thanks for help.
