### ISSUE TITLE
[Breaking] Turn solc ICE due to too many stack variables in assembly into a parsing error?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9279]
## Description

```
contract C {
        function f() public {
                assembly {
                        function n(i1, i2, i3) -> o1, o2, o3, o4, o5, o6, o7, o8, o9, o10, o11, o12, o13, o14 {}
                }
        }
}
```

throws

https://github.com/ethereum/solidity/blob/a1c33249f133823476470f566753eee69cff52cd/libyul/backends/evm/AsmCodeGen.cpp#L221-L225

Could this be turned into a compile-time error instead?

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc <input.sol>
```

**Comment by chriseth** [comment]
What is a compile-time error? We can use `assertThrow` but we cannot detect this situation in the analysis phase because the optimizer might inline the function and the problem could go away.

**Comment by bshastry** [comment]
> What is a compile-time error? We can use `assertThrow` but we cannot detect this situation in the analysis phase because the optimizer might inline the function and the problem could go away.

Yeah, I thought as much. I will close this issue in favour of #9281
