### ISSUE TITLE
`continue` operation not valid inside of ternary operator

### ISSUE THREAD

**Issue by thegostep** [ethereum/solidity#9290]
## Description

`continue` operation not valid inside of ternary operator.

## Environment

- Compiler version: 0.6

## Steps to Reproduce

```solidity
// current
bool valid;
for (uint256 index = 0; index < hashes.length; index++) {
	valid = isValid(hashes[index]);
	if (!valid) {
		return valid;
	}
}
return valid;

// expected
for (uint256 index = 0; index < hashes.length; index++) {
	isValid(hashes[index]) ? continue : return false;
}
```

**Comment by leonardoalt** [comment]
Is `isValid(hashes[index]) ? return false : return false;` actually valid?
I don't think control flow is allowed inside the ternary operator, it needs to be an expression

**Comment by chriseth** [comment]
The ternary operator is at expression level while `continue` and `return` are statements - you cannot use them inside expressions.
