### ISSUE TITLE
[SMTChecker] ICE in solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9296]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C
{
    function i() public returns (uint d) {
	if (0==0)
            (d) = 13;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1712): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

And the parens on (d) are neccessary.

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.6.11-develop.2020.7.2+commit.3d96e2b1.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
May be related to #8817

**Comment by agroce** [comment]
Seems plausible. Depends on whether the need for the `(d)` parens is similar to the presumed need for `c` in your example to be an array index...

**Comment by bshastry** [comment]
Thank you for reporting the issue once again @agroce !
