### ISSUE TITLE
Investigate node-js performance and delays on exiting

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9297]
@frangio first reported that the loading times of soljson.js in node-js increased significantly between 0.6.8 and 0.6.9 (along with the size increase due to adding Z3). This indeed seems to be the case for node 10, which has quite high loading times in general.

We probably don't need to care too much about node 10, which is rather old by now - but node > 10 has an even weirder issue.

Some benchmarks by @frangio https://gist.github.com/frangio/e70e524e3357ea143df77b7d3197c0a7

Apparently neither loading the file, nor compiling it, nor executing it is what actually causes the slow execution. At least I personally would be fine with the increase from 200ms to 600ms there, because it's still "fast enough" - but apparently *exiting* the node-js process causes a significant delay and 2.5 vs 7.3 seconds is really not nice, especially if it looks like it *could* just be ~200ms and the rest is wasted process shutdown time.

**Comment by frangio** [comment]
An interesting point is that manually calling `process.exit()` will exit node without delay.

**Comment by ekpyron** [comment]
Oh, wow, interesting! I did use ``abort()`` and saw that that makes it exit fast, but expected that to only work in such a "disgraceful" way of exiting - I hadn't even considered that ``process.exit()`` might also have that effect :-)!
I'm starting to get the feeling that this might actually primarily be an issue in node itself and we should actually ask them to look into it or at least explain it...

**Comment by ekpyron** [comment]
Pinging @cameel here since he seems to be looking into this as well.

**Comment by ekpyron** [comment]
Looking at this again superficially, I think https://github.com/nodejs/node/issues/36616#issuecomment-757929741 may be responsible for this. The issue is open and active, so we can hope that this will finally be resolved on the node end eventually...

**Comment by ekpyron** [comment]
Actually, these days I do see this issue even *with* explicit ``abort()`` or ``process.exit(0)``...
But I just tried https://github.com/nodejs/node/issues/36616#issuecomment-1014216889 and that does seem to help, i.e.
running with ``node --wasm-dynamic-tiering`` solves the issue for me...

**Comment by ekpyron** [comment]
Given the most recent comment in the linked nodejs issue, it might be worthwhile to double check if this is fixed in the latest node versions.

**Comment by frangio** [comment]
Indeed this seems fixed on Node 18! Seeing this very clearly in the test suite for [solidity-ast](https://github.com/OpenZeppelin/solidity-ast) (`npm test test/solc.js`).

**Comment by ekpyron** [comment]
Closing this as fixed on the node side.
