### ISSUE TITLE
[Testing] Add semantic tests containing a multi assignment inline assembly statement containing the same variable in the LHS more than once

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9301]
TODO:
  - [x] Add yul interpreter test case
  - [x] Add solidity semantic test

**Comment by chriseth** [comment]
For the purposes of the fuzzer, it might make sense to extend the `m_debug` flag in the OptimiserSuite to run the analyzer on the ast after each step (in the `OptimiserSuite::runSequence` function)

**Comment by bshastry** [comment]
> For the purposes of the fuzzer, it might make sense to extend the `m_debug` flag in the OptimiserSuite to run the analyzer on the ast after each step (in the `OptimiserSuite::runSequence` function)

Right now, I'm running analyzer + interpreter after a randomly chosen step on random yul code.

**Comment by chriseth** [comment]
Closing as the underlying issue cannot happen anymore.
