### ISSUE TITLE
[Yul] Disallow the same variable occurring multiple times in the LHS of multi-variable-assignments.

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9303]
Up for discussion: (Related to #9301 which #9302 attempts to "fix")

For context
  - legacy optimizer and yul optimizer behave differently when a single variable reference is reassigned via a multi variable assignment
  - yul interpreter conforms to yul optimizer behavior (both of which diverge from legacy optimizer)

Example

```
// assignment via a call to a
// multi return value function
// assigns the last returned value
contract C {
  function f() public returns (uint o) {
    assembly {
      function f() -> a, b { a := 1 b := 2 }
      o, o := f()
    }
  }
}
// ====
// compileViaYul: also
// ----
// f() -> 0x01
```

passes in non-yul mode but fails in yul mode (actual return is `0x02`)

**Comment by ekpyron** [comment]
Something similar also kind of came up in https://github.com/ethereum/solidity/issues/8303 already, but without solution yet.

**Comment by ekpyron** [comment]
@chriseth on gitter:  it may be that this also depends on whether or not we do stack optimization. In any case, I would certainly disallow mentioning the same variable twice in a multi-variable assignment.

And I agree - disallowing sounds good, moving to implementation backlog.

**Comment by chriseth** [comment]
This has been implemented.
