### ISSUE TITLE
[SMTChecker] ICE in smtutil::Expression solidity::frontend::smt::EncodingContext::newValue(const frontend::VariableDeclaration &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9322]
## Description

This contract:
```solidity
contract Other {
    C c;
    function h() public {
	c.setOwner(address(0));
    }
}
contract State {
    Other o;
    function f() public returns (uint) {
	while(1==1)
	    o.h();
    }
}
contract C {
    address owner;
    function setOwner(address _owner) public {
 	owner = _owner;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/EncodingContext.cpp(108): Throw in function smtutil::Expression solidity::frontend::smt::EncodingContext::newValue(const frontend::VariableDeclaration &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.6.11-develop.2020.7.3+commit.88913132.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by leonardoalt** [comment]
Thanks for reporting @agroce !
Which parens exactly do you mean? I don't see `(d)` in the code

**Comment by agroce** [comment]
oops, copy paste problem, will edit!
