### ISSUE TITLE
Undo code added for parsing unit-test command line options

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#933]
See https://github.com/ethereum/solidity/pull/799#issuecomment-240132888

We can simplify our unit-test application code for solidity.   Both @winsvega and @bobsummerwill were unaware of the idiomatic way of handling Boost unit-test options.

**Comment by winsvega** [comment]
@chriseth   did you already removed this code?

**Comment by chriseth** [comment]
I think I already did most of the required changes, but please check.
