### ISSUE TITLE
Introduce restricted keywords in yul::Dialect

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9330]
Ref: https://github.com/ethereum/solidity/pull/9323#discussion_r450350277

`EVMDialect`  should include all the disabled opcodes as restricted keywords so that they cannot be used as identifiers (to declare functions, for example). Such opcodes include `jump`, `jumpi`, etc.

**Comment by axic** [comment]
This could be considered non-breaking but a "safety motivated" bugfix as well.

**Comment by ekpyron** [comment]
I don't think it can be considered non-breaking - it would be a proper breaking change.
The history was: those instructions were usable in 0.4, then it was disallowed to use them in 0.5 both as instructions and as identifiers, then in 0.6 they were allowed again. I'd find it rather weird to now suddenly disallow them again in 0.7 or even 0.8.

We could just warn about them instead in 0.7 - and if we *really* think they are a problem, make them an error again in 0.8, but I think the concern of them being actually confusing for auditors is rather artificial, so I would personally just do nothing about this.

**Comment by ekpyron** [comment]
Do you have any example of any yul snippet that would *really* be confusing based on those?
Let's take ``jump``.
If you make that a variable ``let jump := 4``, it cannot be called, so no-one could think it actually jumps anywhere.
If you make it a function, the only argument it could get are expressions, not functions, so I don't think that even in
``function jump(x) {} function f() -> r {} jump(f())`` there is much danger of actually considering this to be a jump.

And last but not least: where does it end? The same argument basically holds for ``function Jump(x) {}`` or ``function jumpTo(x) {}`` or ``function JUMP(x) {}`` as well. ``jump`` actually jumping is ancient history in 0.4, so I don't see much difference. And we can't protect people from using bad names.

**Comment by axic** [comment]
> then in 0.6 they were allowed again.

I argue based on git history (the number of clutter found suggests it was hastily merged) that during the introduction of dialects this was forgotten because no good test existed. Because of that I think it is a bugfix.

**Comment by ekpyron** [comment]
I vaguely remember it being a consciously (albeit briefly) discussed decision actually - but I may be wrong about that... not sure it matters too much at this point.
EDIT: the lack of a changelog entry in 0.6.0 is an indication against that, though, that's true :-).

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/9549
