### ISSUE TITLE
Ether units: drop finney and szabo

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9337]
Follow up of #8716.

Pro:
These two units do not seem to be used.

Con:
The current units seem to be spaced out quite nicely:
```
assert(1 wei == 1);
assert(1 gwei == 1e9);
assert(1 szabo == 1e12);
assert(1 finney == 1e15);
assert(1 ether == 1e18);
```

**Comment by chriseth** [comment]
I would approve, but we should ask the community.

**Comment by Marenz** [comment]
Instead of removing we could replace them with
* Szabo -> Microether/ Micro (factor: 12)
* Finney -> Milliether / Milli (factor: 15)

taken from http://eth-converter.com/extended-converter.html

**Comment by axic** [comment]
>  taken from http://eth-converter.com/extended-converter.html

That website seems to base the units on https://github.com/ethereumjs/ethereumjs-units/blob/master/units.json. This was collection of units based from various sources at the time.

I don't think any of those units are used by anyone. I would strong vote against "micro" and "milli" in any case as those can be mistaken for anything.

**Comment by chriseth** [comment]
there is a point for gwei because it is really common for gas prices but for everything else, you could just use things like `1e12`

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/9361
