### ISSUE TITLE
Nightly builds should have correct version number

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#934]
The develop branch should have its minor version incremented immediately following a release (even if the next release will not increment the minor version) and a prerelease string appended:

Current released version (release branch): `0.3.6`
Version number in develop: `0.4.0-nightly.2016.08.19+af2381cd`
Next released version (in merge commit from develop to release): `0.3.7`

Make sure to first modify the routines that parse the version numbers to find "releases" for solc-js.

related: https://github.com/ethereum/solidity/issues/186

To be done:
- [x] properly handle prerelease versions in the version pragma
- [x] include prerelease and build info in `version()` string
- [x] rename archived emscripten binaries

**Comment by chriseth** [comment]
The first step of correctly reporting the version in `--version` and `version()` can already be done without the change to the solc-bin scripts.

**Comment by axic** [comment]
Is this done?

**Comment by chriseth** [comment]
yep!
