### ISSUE TITLE
Disallow dots in user-defined identifiers in inline assembly

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9345]
As a result of the discussion in #7646 we also agreed to disallow dots in user-defined identifiers in inline assembly (e.g. functions or variables with dots) and this allows using identifiers with dots to represent variables originating from Solidity, for example enums or storage variables (`.slot` and `.offset`).

This issue is tracking implementation.

**Comment by chriseth** [comment]
Implemented in #9291
