### ISSUE TITLE
Remove the ripemd160 builtin

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9358]
This was discussed in the past and also briefly mentioned here: https://github.com/ethereum/solidity/issues/8880#issuecomment-626674881

The `ripemd160` builtin has been there since the beginning because, but 1) it never caught any real use; and 2) we do not expose every precompile in the language (for example ecadd/ecmul/ecpairing and blake2b are not exposed).

**Comment by chriseth** [comment]
What about sha256?

**Comment by axic** [comment]
`keccak256` is widely used today, and `sha256` is picking up because of its use in Eth2.0 and other protocols.

**Comment by chriseth** [comment]
maybe group them in a common namespace?

**Comment by axic** [comment]
I considered that we should move all/most of our builtins into new namespaces and have the contract explicitly import them, for example `sha256`, `keccak256`, `ecrecover` under `crypto`:
```
import keccak256 from crypto; // here crypto is an identifier because it is "built in"
```
