### ISSUE TITLE
Disallow subsequent declarations of function call options (e.g. {value=1}{gas=2})

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9363]
This discussion was prompted by #9334.

Subsequent overwriting of the same setting is already disabled, e.g.
```
{value=1}{value=2}
{gas=1}{gas=2}
{salt=0x1234}{salt=0x4567}
```
are all invalid.

**Comment by chriseth** [comment]
Accepted in design discussion round.

**Comment by hrkrshnn** [comment]
solidity-upgrade currently changes `f.value(1).gas(2)` to `f{value: 1}{gas: 2}`. If this is implemented, it might be a good idea to fix it to `f{value: 1, gas: 2}`.

**Comment by axic** [comment]
Even if the compiler accepts multiple option groups, I think `solidity-upgrade` should strive to output a single one.
