### ISSUE TITLE
Drop backwards compatibility from and fix Solidity Antlr grammar

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9369]
Came up in https://github.com/ethereum/solidity/pull/9361.

I only now realized that the grammar is supposed to also parse older solidity versions, which involves adding weird workarounds for breaking changes.

I don't think this is a good idea. It renders the grammar less useful (having workarounds in the category will require similar workarounds for everyone actually using it to parse stuff) and it's an unrealistic goal anyways.

There's several examples for which this currently doesn't work ``uint override;``, ``uint virtual;``, ``function immutable()``, etc.

If anything, we should clearly define which versions it should work against and properly test that.

But I think we should specifically only target the current version of the language.

The only argument against that I heard was wanting to parse the pragma using the grammar first and not wanting to parse twice. I don't think that's a valid argument - the pragma *can* and *should* be parsed independently (it's e.g. just a simple regex to do that) and then I can choose the correct grammar for the right version.

But I may have missed more discussion about this that already has taken place, if so, sorry about that.

**Comment by chriseth** [comment]
I think we should have two grammars: One that is as close as possible to the current version and one that is as relaxed as possible, targeting different use-cases. I think there is already an issue about it, by the way.

**Comment by leonardoalt** [comment]
What use cases would those be?

**Comment by ekpyron** [comment]
I searched for existing issues involving ``grammar`` and ``antlr`` and didn't find anything...

Two grammars would be fine, but what's "as relaxed as possible" - a grammar that's "as relaxed as possible" just treats everything as identifier and does nothing... I don't want to be nitpicking here, but we have to properly define what it should do... e.g. being able to parse 0.5+ would be reasonable. 0.4+ might be desirable (depending on use cases), but would already make things significantly weirder (and thereby the result of using the grammar to parse stuff *less* useful)...

**Comment by ekpyron** [comment]
> What use cases would those be?

That would be an interesting question indeed. If it's only to be able to parse the version pragma, then I'd argue that's not a good use case for a grammar at all - not sure what other use cases there could be?

**Comment by ekpyron** [comment]
To document that here: There's quite a few things wrong with the current grammar in general.
E.g. in inline assembly ``switch return {}`` seems to be fine - identifiers are considered function calls (although this might change in https://github.com/ethereum/solidity/pull/9285), etc.

**Comment by franzihei** [comment]
Also dropping this here in case we need it later wrt use cases: 

The ANTLR grammar is currently used by [Solidity Parser for JavaScript](https://github.com/solidity-parser/parser), which is used by

* [sol2uml](https://github.com/naddison36/sol2uml)
* [Solhint](https://github.com/protofire/solhint/)
* [solidity-coverage](https://github.com/sc-forks/solidity-coverage)
* [prettier-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity/)
* [Buidler](https://github.com/nomiclabs/buidler/)
* [eth-gas-reporter](https://github.com/cgewecke/eth-gas-reporter)

**Comment by ekpyron** [comment]
Another user right here https://github.com/intellij-solidity/intellij-solidity/tree/master/src/main/grammars/ - I just noticed, because that's an IntelliJ plugin I can actually use in CLion myself :-D.
