### ISSUE TITLE
Error compiling on Linux 

### ISSUE THREAD

**Issue by slothbag** [ethereum/solidity#937]
I'm trying to compile on Ubuntu 16.04.01 and its giving the following errors:

```
/usr/bin/ld.gold: error: /usr/local/lib/libjsoncpp.a(json_value.cpp.o): requires unsupported dynamic reloc 11; recompile with -fPIC
```

**Comment by chriseth** [comment]
Which compiler do you use? How exactly did you compile?

**Comment by slothbag** [comment]
Ill have to check when im back at the keyboard.. but I'm just using standard gcc that comes default. Pretty are I just run make solc.

Ill provide specifics soon

**Comment by slothbag** [comment]
Looks like I have cpp 5.4.0 installed.. I assume thats what cmake/make is using under the hood.

I git cloned the repo then cloned, built and installed jsoncpp library, then in the solidity folder

```
mkdir build
cd build
cmake ..
make solc
```

**Comment by chriseth** [comment]
Did you use `scripts/install_deps.sh`?

**Comment by Denton-L** [comment]
When you cloned, did you run `git clone --recursive`? If not, try running `git submodule update --init`.

**Comment by slothbag** [comment]
Thanks for the tips, the git submodule didn't help. I went to do the install_deps script but cant risk breaking other dependencies on this box.. so will leave it.

My goal was to do a windows build from linux.  Is there any plans for a nightly windows solc.exe binary? :)

**Comment by bobsummerwill** [comment]
"My goal was to do a windows build from linux. Is there any plans for a nightly windows solc.exe binary? :)"

^ Not currently, though, but we do hope to get to weekly releases.

**Comment by chriseth** [comment]
"do a windows build from linux" - are you trying a cross-compilation?

**Comment by slothbag** [comment]
Yeah, I just need a recent Windows build.. I thought it would be easy to cross compile from linux.  The OSX build was super easy..  Linux and Windows proving more challenging.

**Comment by bobsummerwill** [comment]
@karalabe has lots of experience with cross-compiling using Dockerfiles.

**Comment by chriseth** [comment]
Should be fixed now, as we link statically to libjsoncpp. closing - please reopen if the bug is still present on develop.

**Comment by slothbag** [comment]
`cmake ..` fails on this line https://github.com/ethereum/solidity/blob/develop/CMakeLists.txt#L16

because the file `deps/jsoncpp.cmake` is not in the repo.

**Comment by axic** [comment]
@slothbag you need to update the `deps` submodule I think

**Comment by slothbag** [comment]
Thanks, got it building on Linux now.  Had to update and build latest Boost also.
