### ISSUE TITLE
[Error reporter] Null pointer dereference due to non existent source location

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9389]
## Description

```
contract T {
	struct X { int[2e22] a; }
	X m_x;
	function i() { var x = m_x; }
}
```

Null deref originates from here:

https://github.com/ethereum/solidity/blob/c90d3a35581db318d745fbc3f2e439ef4f68ed04/liblangutil/ErrorReporter.cpp#L70

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <test.sol>
```

**Comment by axic** [comment]
@ekpyron @chriseth Was this a "duplicate" of #9404?

**Comment by ekpyron** [comment]
Ah, yes, I think so! That would be @chriseth's time machine then :-)! (https://github.com/ethereum/solidity/issues/9396#issuecomment-658079520)

**Comment by ekpyron** [comment]
So I think this was also fixed in https://github.com/ethereum/solidity/pull/9406.
Please reopen if you think I'm wrong.

**Comment by axic** [comment]
This looks like the same example and it indeed passes without crash.
