### ISSUE TITLE
Postfix types - varname: type

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#939]
We should follow TypeScript (and other popular languages) more closely and change variable declarations to `identifier: typename`, this also makes it much easier to distinguish the typename from the identifier.

We can keep the C-style notation as an alternative.

**Comment by axic** [comment]
I think this makes sense if we can nicely encapsulate `constant` and `public` in this (and perhaps storage variables).

i.e.

```
// variables
var name:type;
let name:type;

// constants
const name:type;

// storage
storage name:type;
state name:type;
```

Not sure about public, memory and references?

**Comment by chriseth** [comment]
Question:
- Where to put `constant`, `public`, etc?
- What about storage and memory reference types, will that still be part of the type?

**Comment by axic** [comment]
From Pivotaltracker:
> `<identifier>: <type>` should be a possible variable declaration. If `: <type>` is omitted, this defaults to "inferred" for local variables and "uint" for everything else.
> This might be a problem in some places where the name of the variable may be omitted (parameter lists).
> For a certain time, this should be allowed in parallel to the old way to declare variables.
> We might also use `function x(): retType` for the returns declaration.
> In general, lean towards how TypeScript does it.
