### ISSUE TITLE
Disallow variable declaration using `var` in the parser

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9396]

**Comment by axic** [comment]
Which parser?

**Comment by chriseth** [comment]
The solidity parser.

**Comment by axic** [comment]
We still have `var`?!

**Comment by ekpyron** [comment]
The idea was that while it'll result in an error, that error message will (if possible) tell you which type you can use... I'm actually not sure that it doesn't even make sense to keep it for that purpose even now...

**Comment by axic** [comment]
I prefer to remove parser workarounds in 0.7.0 when we can.

**Comment by ekpyron** [comment]
What I'm saying is that arguably it's a compiler feature, not just the relic of an old parser workaround...

Especially for things like function pointers it can be quite handy to be able to write `var x = f;` or `var x = this.f;` to have the compiler tell you how you have to name the type for those.

If it only was a parser workaround, we should definitely remove it, but I'd argue it's not.

**Comment by ekpyron** [comment]
I'm not saying we necessarily shouldn't remove it - we can decide that we don't need this as a feature, but it's not just some leftover workaround.
By the way: not sure removing it is actually breaking in any way :-).

**Comment by ekpyron** [comment]
https://github.com/ethereum/solidity/issues/9404 actually being a proper segfault which is probably caused by ``var`` speaks for removing all of it fast, though :-).

**Comment by chriseth** [comment]
@ekpyron that issue is actually where I got the idea :)

**Comment by ekpyron** [comment]
> @ekpyron that issue is actually where I got the idea :)

Can I borrow your time machine :-)?
EDIT: but yeah, I thought it probably wasn't a coincidence.

**Comment by chriseth** [comment]
Ah no, it was another bug that is also related to `var`.

**Comment by ekpyron** [comment]
I think they were duplicates.

**Comment by axic** [comment]
> Especially for things like function pointers it can be quite handy to be able to write var x = f; or var x = this.f; to have the compiler tell you how you have to name the type for those.

Apparently the message is displayed is not correct (in all cases):
> // SyntaxError 1719: (105-114): Use of the "var" keyword is disallowed. Use explicit declaration `struct b.c storage pointer d = ...´ instead.

The `pointer` keyword is not valid.

**Comment by ekpyron** [comment]
Yeah, I saw that, too :-). If we want to keep it, we have to fix stuff like that I guess...

**Comment by chriseth** [comment]
You get type suggestions by just assigning it to a random incorrect type.

**Comment by ekpyron** [comment]
Unless that random type happens to be implicitly convertible to the actual type... but yeah... as I said, I'd be fine with dropping it.

**Comment by ekpyron** [comment]
This we could have quickly discussed in the call today as well :-). I'm fine with anything - removing it or fixing its suggestion mechanism.

**Comment by chriseth** [comment]
Implemented in #9428
