### ISSUE TITLE
Reconsider constructor visibility for 0.7

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#9399]
One of the planned changes for 0.7 is "Constructors should not have visibility". This change forces libraries like OpenZeppelin to publish a new release removing constructor visibilities, but since they are required for 0.6 it also requires bumping the pragma to 0.7, which is a breaking change and forces us to release a new major version (or to break semantic versioning, which we strongly prefer not doing). This then forces users to upgrade their OpenZeppelin dependency to the new major version, unless we keep maintaining two majors which is a significant amount of work for us.

The point is that there are a lot of downstream effects from this breaking change, and I think they should be avoided if possible.

The cause of all this trouble is going from "visibility is required" to "visibility is forbidden" in a single version bump. The ideal situation for us is to be able to release a new minor version that can work with both 0.6 and 0.7, and constructor visibilities seem to be the only reason why we would not be able to do that.

My suggestion is to release 0.7 with an intermediate change: "constructor visibility is not required", so that libraries like OpenZeppelin can be used in the newer language version without needing breaking changes.

I'd also mention that adding warnings when constructor visibility is present may be just as bad as requiring their removal. Since warnings can't be disabled (https://github.com/ethereum/solidity/issues/2691), it becomes a major pain for users to constantly see these warnings in their workflow.

Curious to hear your thoughts on this one!

**Comment by chriseth** [comment]
We actually implemented it just as a warning (as long as it is compatible with the "abstractness" of the contract). We can talk about even removing this warning, but I fear that this will only postpone the problem by another Solidity version.

The cleanest solution, in my opinion, would be to maintain one OpenZeppelin library per Solidity version. This would maybe also help us since we are already maintaining a fork of OpenZeppelin - so we could just do the essential updates.

**Comment by frangio** [comment]
Oh I'm glad to hear it's just a warning. Then we should talk about removing the warning.

>I fear that this will only postpone the problem by another Solidity version.

Yes, but that's good! I think this is about giving the ecosystem more time to adapt and reducing the potential fatigue from the tooling introducing incompatibilities too often.

> The cleanest solution, in my opinion, would be to maintain one OpenZeppelin library per Solidity version.

This would be pushing all of the burden on us as maintainers, and it would not be an easy job. Any syntactic breaking change makes backporting patches impossible without manual conflict resolution, which is an easy place to make mistakes and introduce bugs. We can maintain older versions for bug fixes, but releasing new features simultaneously for multiple Solidity versions is not something we're willing to do. This means there would still be potential fatigue for end users.

**Comment by chriseth** [comment]
References https://github.com/ethereum/solidity/issues/8992 https://github.com/ethereum/solidity/issues/4392 https://github.com/ethereum/solidity/issues/8162

**Comment by chriseth** [comment]
Closing after discussion.
