### ISSUE TITLE
Fail to generate why3 source with --formal

### ISSUE THREAD

**Issue by chatch** [ethereum/solidity#943]
Running "solc --formal" against Fund.sol from [this gist](https://gist.github.com/chriseth/c4a53f201cd17fc3dd5f8ddea2aa3ff9) results in an error "Compound assignment not supported". 

formal> solc --version
solc, the solidity compiler commandline interface
Version: 0.3.6-0/None-Linux/g++

formal> solc --formal Fund.sol 
Fund.sol:6:13: Error: Compound assignment not supported.
            shares -= amount; // subtract the amount from the shares
            ^--------------^

My version of solc is the latest in the ethereum ppa.

**Comment by chatch** [comment]
I can workaround this by expanding the assignment to "shares = shares - amount;"

**Comment by chriseth** [comment]
Yes, the gist is an old example, the syntax changed in the meantime. Please use this example: https://chriseth.github.io/notes/talks/formal_ic3_bootcamp/#/7
