### ISSUE TITLE
The maven compiler provides warnings that should not provide

### ISSUE THREAD

**Issue by WillMandrill** [ethereum/solidity#9444]
Hello

I have this contract
```solidity
pragma solidity  >=0.4.0 <0.7.0;

   contract HelloWorld 
   {

   	uint256 public counter;
   
   	function add() external
   {
       counter++;
   }
 
   function subtract() external
   {
       counter--;
   }
   
   function getCounter() public view returns (uint256) 
   {
       return counter;
   }
 
}
```

When I compile it with maven 
```
<dependency>
      <groupId>org.web3j</groupId>
      <artifactId>core</artifactId>
      <version>5.0.0</version>
   </dependency>
    <plugin>
            <groupId>org.web3j</groupId>
            <artifactId>web3j-maven-plugin</artifactId>
            <version>4.5.11</version>
            <executions>
```

The compiler on Eclipse fires this:

`WARNING] Definition of the function counter returns a value but is not defined as a view function. Please ensure it contains the view modifier if you want to read the return value
[WARNING] Definition of the function getCounter returns a value but is not defined as a view function. Please ensure it contains the view modifier if you want to read the return value
[INFO] 	Built Class for contract 'HelloWorld'
[INFO] 
[INFO] --- build-helper-maven-plugin:3.2.0:add-source (add-source) @ java-ethereum ---
[INFO] Source directory: /home/willserrano/eclipse-workspace/java-ethereum/target/generated-sources/contracts added.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS`

It seems awkward, can anybody help?

Thank you

Will

**Comment by chriseth** [comment]
This seems to be a problem with github.com/web3j/web3j - can you report the issue there? Thanks!

On the other hand, Solidity 0.7.0 will properly report state variable getter functions as `view`, so this might also fix it.
