### ISSUE TITLE
Add require(bool,bytes) global function

### ISSUE THREAD

**Issue by junderw** [ethereum/solidity#9454]
It seems like most people throw away returndata when performing calls. ie.

```solidity
(bool result, ) = someAddress.call{ value: msg.value }('');
require(result, 'some message');
```

It would be nice to be able to do something like.

```solidity
(bool result, bytes memory returndata) = someAddress.call{ value: msg.value }('');
require(result, returndata);
```

That way if the contract we're calling has a descriptive error we can just forward that.

**Comment by chriseth** [comment]
This is a good point and we might add it with enabling user-defined error types.

**Comment by junderw** [comment]
Something like this seems easy to understand, as long as the parameters of require line up with the return parameter types and order.

```solidity
require(someAddress.call{ value: msg.value }(''));
```

**Comment by junderw** [comment]
I still think this would be a good idea. If no one has anymore thoughts on the idea, I'll just close this.
