### ISSUE TITLE
Identifying and decoding local variables

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/solidity#9461]
## Introduction

We, Nomic Labs, have been working on identifying which metadata should `solc` emit as part of the compilation process to:

1. Make existing tools less fragile
    - Many tools depend on `solc` implementation details which are not considered part of of the compiler API. This leads to some of them breaking with new `solc` releases, degrading the users' experience and imposing high maintenance costs.
2. Make creating new tools easier
    - Creating tools that analyse Solidity requires knowledge of the internals of the compiler today. Some of them are documented, some of them aren't. This has a very steep learning curve. Having metadata explicitly designed for tool developers would lower it.
3. Make new kinds of tools possible
    - Giving new metadata can unlock the construction of new tools that are now impossible or require too much effort to be viable.
4. Give the compiler more flexibility
    - With better metadata, tools won't have to rely on `solc` compilation details. This will give the compiler more freedom to change things without breaking external tools, as long as the metadata is general enough and up-to-date.

To do this, we analyzed the current situation and gathering feedback from different teams that would benefit from this effort. You can read more about this [here](https://www.notion.so/nomiclabs/Solidity-debugging-symbols-requirements-gathering-128849a840f241388219c56e7e91281d).

Once that data was collected, we presented an initial proposal, which is available in this other [Notion document](https://www.notion.so/nomiclabs/Solidity-debugging-symbols-Initial-proposal-b70fedc2c7914498bd7ed8e27db63883).

So far, most communication was handled on a Telegram group, but I'm creating multiple issues to move it here.

This issue in particular is meant to continue the discussion related to metadata for **local variables**.

## Identifying and decoding local variables

[This document](https://www.notion.so/nomiclabs/Local-variables-symbols-Initial-proposal-7a317eb434204d43b7dc86e250700400) contains all the relevant information of the proposal and has been updated today (2020-07-21), so that also includes answers to all the questions that were made about it so far.

**Comment by alcuadrado** [comment]
The only relevant update so far is that this proposal doesn't take [memory escalation of variables](https://github.com/ethereum/solidity/issues/5766) into account. When/If this new local variables management gets implemented, the metadata will need to be updated accordingly.

**Comment by yann300** [comment]
I am not sure I clearly understand why: `The reason why endBytecodeOffset is an array is because a function might have multiple return statements where a variable scope could end at any moment`
As the dev tool is aware of the scopes (functions) this should be enough to know when variables from a specific scope can be discarded (e.g when the execution goes out of the scope).
or am I missing something here?

**Comment by chriseth** [comment]
Regardless of scopes, note that code belonging to a scope does not have to be contiguous. It likely is, but does not have to be.

**Comment by ekpyron** [comment]
Linking this to https://github.com/ethereum/solidity/issues/13720
