### ISSUE TITLE
Identifying and decoding mapping keys

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/solidity#9462]
## Introduction

We, Nomic Labs, have been working on identifying which metadata should `solc` emit as part of the compilation process to:

1. Make existing tools less fragile
    - Many tools depend on `solc` implementation details which are not considered part of of the compiler API. This leads to some of them breaking with new `solc` releases, degrading the users' experience and imposing high maintenance costs.
2. Make creating new tools easier
    - Creating tools that analyse Solidity requires knowledge of the internals of the compiler today. Some of them are documented, some of them aren't. This has a very steep learning curve. Having metadata explicitly designed for tool developers would lower it.
3. Make new kinds of tools possible
    - Giving new metadata can unlock the construction of new tools that are now impossible or require too much effort to be viable.
4. Give the compiler more flexibility
    - With better metadata, tools won't have to rely on `solc` compilation details. This will give the compiler more freedom to change things without breaking external tools, as long as the metadata is general enough and up-to-date.

To do this, we analyzed the current situation and gathering feedback from different teams that would benefit from this effort. You can read more about this [here](https://www.notion.so/nomiclabs/Solidity-debugging-symbols-requirements-gathering-128849a840f241388219c56e7e91281d).

Once that data was collected, we presented an initial proposal, which is available in this other [Notion document](https://www.notion.so/nomiclabs/Solidity-debugging-symbols-Initial-proposal-b70fedc2c7914498bd7ed8e27db63883).

So far, most communication was handled on a Telegram group, but I'm creating multiple issues to move it here.

This issue in particular is meant to continue the discussion related to metadata for **mapping keys**.

## Identifying and decoding mapping keys

[This document](https://www.notion.so/nomiclabs/Mapping-keys-symbols-Initial-proposal-092be64f8bc14c80a0728f713004c2b8) contains all the relevant information of the proposal and has been updated today (2020-07-21), so that also includes answers to all the questions that were made about it so far.

**Comment by alcuadrado** [comment]
I'm copying this section of the document here so that it doesn't go accidentally ignored.

@chriseth, I believe this contains answers to all the questions posted on the Telegram group.

## Jul 21 Updates

This comment contains answers to different questions about this proposal:

### What does *tracking* mean in this document?

Determining the complete set of mapping keys used by a contract can't be determined statically. In order to do so, you need to identify when they are used and store that information. This is what we call *tracking* a key.

As explained below, identifying the uses of every mapping key, is a complex and recursive task. To be able to identify some mapping keys, you may need to have already identified others, that's the reason for naming this *tracking*.

### What information is needed for each mapping?

To be able to effectively track the mapping keys used by a contract, we need these things:

- Be able to identify when a key is being hashed without false positives.
- We need to know every mapping's key and value types.
- We need to know every slot that identifies a mapping.
- We need to know the layout of the memory buffers that are hashed when computing keys.
    - Currently, this layout is always the same.
- We need to know how each type is represented in the memory buffers that are hashed when computing keys.
    - For example, the `string` representation in these buffers doesn't match its storage representation.
- We need to be able to identify when a dynamic array's size changes.
    - See below to understand why this is needed.

### What would happen if `sha3` instructions get reused by non-mapping-keys code?

**Extended question:** As mentioned by Chris, a future version of the compiler may decide to reuse the same `sha3` instruction for mapping keys and non-mapping-keys code. In theory, it could even decide to emit a single `sha3` instruction. How would this be handled?

**Answer:** As mentioned above, tracking mapping keys requires identifying when a key is being hashed without false positives. We envision two ways of doing this:

- Statically: by somehow indicating that a portion of the bytecode is exclusively used for hashing mapping keys. In our proposal, this means tagging `sha3` operations.
    - Pros:
        - Requires no modification to the bytecodes emitted today, just metadata.
        - Simpler to consume. No need to inspect the runtime state to tell if an instruction belongs to a mapping or not.
    - Cons:
        - It inhibits some optimizations, as a single `sha3` instruction wouldn't be enough for certain programs. Note that two would though, as one can be used for hashing mapping keys, and the other for everything else.
- Dynamically: by emitting code that flags when a `sha3` instruction is being used for a mapping key, for example, by setting a well-known memory address to `true`, or pushing it to the stack.
    - Pros:
        - More flexibility for the compiler to optimize use of `sha3` instructions.
        - May make building certain unrelated optimizations easier, by not requiring tracking the `sha3` metadata.

    - Cons:
        - This approach would slightly increase runtime gas costs.
        - Requires modifications to the bytecodes being emitted.

Getting back to the question, if an optimization of this kind were implemented, a new static or dynamic way of identifying the mapping-related `sha3` instructions should also be implemented.

### Detailed explanation of how the metadata proposed here would be used

The way we envision this being used looks like this:

1. You need to keep track of all the mappings, which can be identified by their slots, during the whole execution of a contract. By tracking here I mean having a list or set of currently existing mappings and their types. By execution of a contract, a single EVM message, not previous ones.

2. Right before the execution starts you need to populate this set of mappings with the ones that are present in the storage layout, and any possible mapping that's accessible from dynamic arrays.

3. Whenever a dynamic array's length slot is written, you need to update the list/set of mappings, adding or removing some of them. The reason for this is that arrays can include mappings and structs containing mappings.

4. When a `sha3` instruction marked as a mapping key computation is executed, you need to inspect the memory to get the slot of the mapping. This slot should belong to a mapping that is already being tracked, so you can get its type and decode the key.

5. If a mapping that contains mappings or structs containing mappings is accessed, the "child" mappings must also be tracked.

### Inline assembly storage allocation

Storage being allocated using inline assembly is out of the scope of this proposal.

A new proposal can be presented for this particular use case of inline assembly, but we don't consider it a high priority, as allocating storage using inline assembly is only done by very advanced users of the language.

### Storage pointers

This proposal doesn't include information about storage pointers/references. Those are included in this other document: [Local variables symbols: Initial proposal](https://www.notion.so/Local-variables-symbols-Initial-proposal-7a317eb434204d43b7dc86e250700400)

**Comment by alcuadrado** [comment]
Any news on this? Does my last comment answer all your questions about the proposal?

**Comment by chriseth** [comment]
Sorry, the unresponsiveness here is a product of the holidays season and the fact that I still cannot fully wrap my head around what you actually want the compiler to export here. You don't need to clarify the motivation or why this is useful. What I'm mainly interested in is why the current information that is exported is not sufficient for what you want to do.

The other problem is that you want to have information at the bytecode level about something that only exists as a concept at the Solidity level. This can be done, but there is always the possibility of information loss between the compilation stages.

Maybe let's start with your "what is needed" items:

 -  Be able to identify when a key is being hashed without false positives.

I assume this means that you want the bytecode offsets of all sha3 opcodes that are used for a mapping index access - is that correct?

 -   We need to know every mapping's key and value types.

This should be possible through the storage layout export

 -    We need to know every slot that identifies a mapping.

If you have mappings of mappings, this is probably impossible.

 -   We need to know the layout of the memory buffers that are hashed when computing keys.
    -    Currently, this layout is always the same.

What do you mean by "layout"? How slot and key are encoded before sha3 is applied? If yes, then I would suggest this to just be implicitly given by the compiler version.

 -    We need to know how each type is represented in the memory buffers that are hashed when computing keys.
  -      For example, the string representation in these buffers doesn't match its storage representation.

I would expected this to be the same as the issue above.

 -    We need to be able to identify when a dynamic array's size changes.
  -      See below to understand why this is needed.

Does this mean that you need to know the bytecode offsets of the `.push()` functions?

**Comment by alcuadrado** [comment]
Thanks for getting back to this, @chriseth !

> Sorry, the unresponsiveness here is a product of the holidays season and the fact that I still cannot fully wrap my head around what you actually want the compiler to export here. You don't need to clarify the motivation or why this is useful. What I'm mainly interested in is why the current information that is exported is not sufficient for what you want to do.

We didn't find a way of identifying which sha3 operations are used for mapping keys that don't, potentially, give false positives. We are, of course, open to other ways of doing this.

> The other problem is that you want to have information at the bytecode level about something that only exists as a concept at the Solidity level. This can be done, but there is always the possibility of information loss between the compilation stages.

I understand this. We are aware of the complications that this may bring, but also believe that for tools to progress solidity-level metadata needs to be associated with the bytecode.

> Maybe let's start with your "what is needed" items:
> 
> * Be able to identify when a key is being hashed without false positives.
> 
> I assume this means that you want the bytecode offsets of all sha3 opcodes that are used for a mapping index access - is that correct?

Correct. As mentioned above, we are open to alternative techniques to identify this.

> * We need to know every mapping's key and value types.
> 
> This should be possible through the storage layout export

It is possible using the storage layout if you are able to identify when mappings of mappings and other complex data structures are modified.

> 
> * We need to know every slot that identifies a mapping.
> 
> If you have mappings of mappings, this is probably impossible.

We believe this is a pretty complex process, but not impossible.
> 
> * We need to know the layout of the memory buffers that are hashed when computing keys.
>   -    Currently, this layout is always the same.

That's great. I think it would be beneficial if this kind of things are still present in the metadata/debugging symbols format, as that gives the compiler the flexibility to change them without breaking the tools.

> 
> What do you mean by "layout"? How slot and key are encoded before sha3 is applied? If yes, then I would suggest this to just be implicitly given by the compiler version.

Yes, we meant that. See the previous response.
> 
> * We need to know how each type is represented in the memory buffers that are hashed when computing keys.
> * ```
>    For example, the string representation in these buffers doesn't match its storage representation.
>   ```
> 
> I would expected this to be the same as the issue above.

Not sure if I understand this comment. Can you clarify? Thanks!

> 
> * We need to be able to identify when a dynamic array's size changes.
> * ```
>    See below to understand why this is needed.
>   ```
> 
> Does this mean that you need to know the bytecode offsets of the `.push()` functions?

@jcaracciolo can you answer this last question? Thanks!

**Comment by jcaracciolo** [comment]
> If you have mappings of mappings, this is probably impossible.

I disagree, since any nested mappings has to be accessed in order (for example in a `mapping(uint => mapping(uint => uint))` in order to access the inner mapping, a sha3 must be done first in the outer mapping to know the resulting slot, where the inner mapping is located. If a process is tracking this along the trace of the transaction is pretty easy to identify that slot as a mapping when it re-appears again in a sha3 instruction as the base of a mapping. With more complex structures (such as nested mappings and arrays and structs) some more calculation has to be done to account for offsets but is pretty straight forward.

> Does this mean that you need to know the bytecode offsets of the .push() functions?

Not necessarily. This depends on the implementation of the tracker. One option is to traverse the layout each time a `sha3` mapping instruction is found in order to check where the slot in the sha3 is coming from. When traversing the layout, you will note the length of a dynamic array every time, so there is no need to even tack it. Another option is to have pre-arranged ranges of slot that the program is remembering to what variables they are associated with, in this case it is needed to update these ranges when a dynamic array size changes, however there is no need for extra metadata here at the moment as you can also save the position of the lengths of dynamic arrays and updated them before computing the slot for the sha3.

**Comment by cameel** [comment]
This looks like something that might be in the scope of the [ethdebug spec](https://github.com/ethdebug/format).

**Comment by alcuadrado** [comment]
> This looks like something that might be in the scope of the [ethdebug spec](https://github.com/ethdebug/format).

+1
