### ISSUE TITLE
[yul] optimisation results in an ICE because object namespace string literal is too long

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9472]
## Description

```
object "t" {
	code {
		datacopy(not(datasize("object2.object3.object4.datablock")), 0, 0)
	}
	object "object2" {
		code{}
		object "object3" {
			code{}
			object "object4" {
				code{}
				data "datablock" ""
			}
		}
	}
}
```

throws

https://github.com/ethereum/solidity/blob/4a478f0fb2d8d4f7bc7fdacfeb20e955d5396ce8/libyul/Utilities.cpp#L103

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc --strict-assembly --optimize test.yul
```

**Comment by chriseth** [comment]
Can you provide a stack trace? This function should not be called for the arguments of `datasize`.

**Comment by bshastry** [comment]
@chriseth Stack trace too long so I created a gist: https://gist.github.com/bshastry/2100b0a89736841f8f5ab835db6fce8b

Seems to be an issue with the stack compressor (https://gist.github.com/bshastry/2100b0a89736841f8f5ab835db6fce8b#file-stacktrace_literal_too_long-txt-L113) but not sure
