### ISSUE TITLE
Refactoring SideEffects

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#9487]
# Refactoring SideEffects

One way to refactor SideEffects is the following:

Have semantic information about whether two YUL-builtins commutes, i.e., `INSTR1` and
`INSTR2` commutes if the two blocks

    {
       ... := INSTR1(...)
       ... := INSTR2(...)
    }

    {
       ... := INSTR2(...)
       ... := INSTR1(...)
    }

are the "same", for all inputs.

We represent this information as a two dimensional boolean matrix, say, `bool[N][N] C`,
with `true` representing that it commutes.

<a id="org1279c8a"></a>

## SideEffects

1.  `movable(instr)`: can be rewritten as `logical_and {C[instr][1], ..., C[instr][N]}`
2.  `invalidatesMemory(instr)`: can be rewritten as `not C[instr][mload]`
3.  `invalidatesStorage(instr)`: can be rewritten as `not C[instr][sload]`
4.  `canBeRemoved` or `sideEffectFree` or `sideEffectFreeIfNoMSize`: TODO: I think the idea
    is that the blockchain state should be the same. A rough way is the following: `INSTR`
    can be removed if it does not affect state, and if it commutes with everything else in
    the code.

<a id="org8f4e53f"></a>

### MovableRelativeTo

To check movability of an expression relative to a block, we collect builtins from the
block and compare if the builtins from the block commutes with the builtins in the
expression.

This is better than the [current implementation](https://github.com/ethereum/solidity/pull/9283) since it can be more fine grained. For
example, `balance` can be moved over `staticall` (the current implementation treats
balance and `returndatasize` in the same group, and therefore prevents moving.)

<a id="orgcd0aefe"></a>

## WASM dialect

All the ideas should carry forward to WASM. In the current implementation, `otherState`
does not make sense for WASM (does it?)

<a id="org7eb9133"></a>

## LoopInvariantCodeMotion

We need a second abstraction on if the following blocks are equivalent:

    {
    ... = INSTR(...)
    }

    {
    ... = INSTR(...)
    ... = INSTR(...) // same arguments and returns as the first one
    }

We could call this as `bool[N] reduction`.

<a id="orgfa6984f"></a>

### Algorithm

An expression can be moved out of the loop-body (provided it's arguments are invariant
during loop execution) if

1.  the expression can be "reduced".
2.  if the expression "commutes" with the rest of the body. (or `movableRelativeTo`)

<a id="org3c1870d"></a>

### Proof that LoopInvariantCodeMotion works

Proof: Unroll the loop, put all the expressions that satisfies "commutativity" to the top.

Now do the repetition reduction. Move those out of the loop block (put them inside an if
statement with same condition as for-loop-block if necessary, e.g. if it writes to memory)

Now roll back the loop.

<a id="orge5951dd"></a>

### Improvements in staticall v/s balance etc.

    for {let i := 10} isZero(i) {i := sub(i, 1)}
    {
    	staticall(1, 1, 0, 10, 0, 10)
    	let bal := selfbalance() // this can be moved with the rules, but not the old rules.
    }

**Comment by chriseth** [comment]
I think it does make sense to slightly group the instructions instead of creating a full NxN matrix. I started a spreadsheet here; 
https://docs.google.com/spreadsheets/d/1usbPvzuWCCqLXWolZ5rAq4UTU5QF7aN4Bnc3N3SI4uU/edit?usp=sharing

What we also have to consider: We will never be able to move something out of a loop that performs any kind of non-idempotent "write" operation. It might be useful to know about any two instructions whether they commute or not, but I currently cannot think of a use-case for that. Furthermore, idempotent write operations sometimes commute depending on their arguments (sstores to different slots), so it could get even more complicated.

**Comment by leonardoalt** [comment]
> invalidatesMemory(instr): can be rewritten as C[instr][mload]
> invalidatesStorage(instr): can be rewritten as C[instr][sload]

@hrkrshnn shouldn't this rather be `\neg C[instr][mload]`?
As in, it invalidates memory if it does *not* commute with `mload`.
Or did I get anything wrong?

**Comment by hrkrshnn** [comment]
@leonardoalt Yes, I'll fix the typo.
