### ISSUE TITLE
Add position keyword for storage variables

### ISSUE THREAD

**Issue by junderw** [ethereum/solidity#9497]
I noticed some contracts add data to storage slots based on the hash of some constant minus 1. Then proceed to create getters and setters that use yul to store that data in the slot.

perhaps:

```solidity
uint256 public position(42) myNumber;
```

instead of a getter/setter than does sstore(42, val) etc.

**Comment by leonardoalt** [comment]
Hi @junderw , your proposal sounds like a syntax suggestion for https://github.com/ethereum/solidity/issues/597

**Comment by junderw** [comment]
Thanks!
