### ISSUE TITLE
[SMTChecker] ICE because arrayVar is null

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9498]
## Description

```
pragma experimental SMTChecker;
contract C {
  function f(bytes calldata x) external {
    x[8][5%5];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/336fe94422a136a1045041308db9c0fcfc569435/libsolidity/formal/SMTEncoder.cpp#L960

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by leonardoalt** [comment]
This also looks weird to me.
`x[8]` has type `byte`, why is it allowed to access the index of a byte?!
