### ISSUE TITLE
[yul] Interpreter ICE while evaluating string literal because object namespace string literal too long

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9499]
## Description

```
object "t" {
	code {
		datacopy(not(datasize("object2.object3.object4.datablock")), 0, 0)
	}
	object "object2" {
		code{}
		object "object3" {
			code{}
			object "object4" {
				code{}
				data "datablock" ""
			}
		}
	}
}
```

throws

https://github.com/ethereum/solidity/blob/4a478f0fb2d8d4f7bc7fdacfeb20e955d5396ce8/libyul/Utilities.cpp#L103

from

https://github.com/ethereum/solidity/blob/7ad27188a057c94efa91e4b4e9c1f26a45011c6e/test/tools/yulInterpreter/Interpreter.cpp#L253

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ yulrun --input-file test.yul
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<solidity::yul::YulAssertion>'
  what():  Literal string too long!
Aborted (core dumped)
```

**Comment by chriseth** [comment]
@bshastry didn't we fix this?

**Comment by bshastry** [comment]
I think the fix was in the stack compressor. However, the interpreter still evaluates string literals via a call to the utility function where the assertion on the length of the string literals is.
