### ISSUE TITLE
[SMTChecker] ICE in solidity::frontend::SMTEncoder::endVisit(const solidity::frontend::IndexAccess &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9505]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract c {
    bytes10[6] data2; // 4 elements need two slots
    function test() public returns (bytes10 r1, bytes10 r2, bytes10 r3) {
        r2 = data2[4][5];
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(960): Throw in function virtual void solidity::frontend::SMTEncoder::endVisit(const solidity::frontend::IndexAccess &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

First detection on day 21 of running four AFL instances!

## Environment

- Compiler version:  0.7.0-develop.2020.7.25+commit.7ad27188.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for reporting this issue!

Note to self: May be a duplicate of #9498
