### ISSUE TITLE
[SMTChecker] ICE due to SMTLogicError because *arraySort->range != *_element.sort

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9506]
## Description

```
pragma experimental SMTChecker;
contract C {
  uint[][] a;
  function f(uint[1] memory x) public {
    a.push(x);
  }
}
```

throws

https://github.com/ethereum/solidity/blob/7ad27188a057c94efa91e4b4e9c1f26a45011c6e/libsmtutil/SolverInterface.h#L152

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc input.sol
```

**Comment by leonardoalt** [comment]
Wait, that looks weird.
@chriseth is it valid to push a static array there?

**Comment by bshastry** [comment]
> Wait, that looks weird.
> @chriseth is it valid to push a static array there?

Yeah, I wasn't sure if this is supposed to be a parser error instead but filed it anyway :)

**Comment by leonardoalt** [comment]
This looks like a dup of https://github.com/ethereum/solidity/issues/9234 (the trimmed version)
