### ISSUE TITLE
[SMTChecker] ICE because of array pop on single element tuple

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9519]
## Description

```
pragma experimental SMTChecker;
contract C {
  int[] a;
  function f() public { (a).pop();}
}
```

throws

https://github.com/ethereum/solidity/blob/da189a667893e49d758f55fb725d9aa689f04913/libsolidity/formal/SMTEncoder.cpp#L1142

Looks like the `pop` version of #9021 

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
libsolidity/formal/SMTEncoder.cpp(1142): Throw in function void solidity::frontend::SMTEncoder::arrayPushPopAssign(const solidity::frontend::Expression &, const smtutil::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

**Comment by leonardoalt** [comment]
`pop` is supported, I bet it's this damn useless tuple

**Comment by chriseth** [comment]
You just need to fix your visitor to go straight through the tuple...

**Comment by leonardoalt** [comment]
I thought it was already doing that, apparently not...
