### ISSUE TITLE
[vs2017 build error]: “solidity/BuildInfo.h”: No such file or directory

### ISSUE THREAD

**Issue by BigGan** [ethereum/solidity#9540]
I follow the install steps to generate "solidity.sln", there is no error. But when I used the VS2017 to open the "solidity.sln" and build it. After building, there are some errors:

ERROR C1083: Cannot open include file: “solidity/BuildInfo.h”: No such file or directory [solidity] [c:\users\test\desktop\solidity-0.5.10\libsolidity\interface\version.cpp] [28]	

Has anyone encountered a similar problem? How was it resolved?

Thanks a lot.

**Comment by leonardoalt** [comment]
@christianparpart any idea?
