### ISSUE TITLE
NatSpec on contracts is not inherited

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9553]
```
/// @notice Hello Interface
interface A {
}

contract C is A {
}
```

results in

```
======= a.sol:A =======
User Documentation
{
  "kind": "user",
  "methods": {},
  "notice": "Hello Interface",
  "version": 1
}

======= a.sol:C =======
User Documentation
{
  "kind": "user",
  "methods": {},
  "version": 1
}
```

Same happens if `A` is a contract.

@Marenz I'm not sure what we've agreed to.

**Comment by chriseth** [comment]
Is `@notice` on contracts meaningful at all? Also, should natspec on contracts (as opposed to functions) be auto-inherited?

**Comment by Marenz** [comment]
`@notice` as it is currently implemented is only inherited on functions. The ticket didn't mention the contract case

**Comment by chriseth** [comment]
I'm torn about whether `@notice` should be valid on contracts, but we can at least inherit the properties.

**Comment by axic** [comment]
Related: https://github.com/ethereum/solidity/issues/10281#issuecomment-801193137
