### ISSUE TITLE
ICE in virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9557]
## Description

This contract:
```solidity
library L {
    function x() internal returns (uint256) {
    }
    constructor() {
	x = L.x;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/AST.cpp(294): Throw in function virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.7.31+commit.f2fa5b5f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by agroce** [comment]
(probably just a separate fix for same issue as #9509

**Comment by agroce** [comment]
Well, similar issue, anyway -- the assignment is necessary, etc.

**Comment by bshastry** [comment]
Thank you for the report @agroce !

**Comment by bshastry** [comment]
The test case could be reduced to the following

```
library L{ constructor() { L.x; } }
```
