### ISSUE TITLE
[yul] ExpressionSimplifier removes non-movable expression

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9558]
## Description

This test passes but it shouldn't because `call()` may change blockchain state (similarly other opcodes that are potentially state changing) and therefore if a contract previously disabled optimizer but at a later point *only* enabled the expression simplifier (not sure if this is a user-facing setting), the end-result will be different.

Please note that full optimization suite retains the `call` in the example below, so this is only a bug if one were to only enable the expression simplifier.

```
{
  pop(byte(0, shr(0x8, call(0, 0, 0, 0, 0, 0, 0))))
}
// ----
// step: expressionSimplifier
//
// { pop(0) }
```

Rule executed is

https://github.com/ethereum/solidity/blob/08791ab0d4cc0c30bebc4076d141e6b96b0d6412/libevmasm/RuleList.h#L582-L587

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ cp test.yul test/libyul/yulOptimizerTests/expressionSimplifier/byte_shr_call.yul
$ isoltest -t yulOptimizerTests/expressionSimplifier/byte_shr_call
Running tests...

yulOptimizerTests/expressionSimplifier/byte_shr_call.yul: OK

Yul Optimizer Test Summary: 1/438 tests successful (437 tests skipped).


Summary: 1/4128 tests successful (4127 tests skipped).
```

**Comment by axic** [comment]
Oh wow 😞
