### ISSUE TITLE
Update Solidity build instructions

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/solidity#956]
_From @bobsummerwill on June 1, 2016 15:16_

At https://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source.

They are out-of-date and out-of-sync with the main instructions, especially WRT to Homebrew.

_Copied from original issue: ethereum/webthree-umbrella#543_

**Comment by bobsummerwill** [comment]
_From @giact on June 4, 2016 19:54_

I tried cleaning up the Ubuntu part a bit: https://github.com/ethereum/solidity/pull/629

There's still some work to do (i.e. re-add the instructions for 14.04).

**Comment by axic** [comment]
@bobsummerwill would you be able to add clear instructions how it needs to be updated and mark it as up-for-grabs?

**Comment by axic** [comment]
I think this is up to date now.
