### ISSUE TITLE
ICE in vector<const solidity::frontend::Declaration *> solidity::frontend::DeclarationContainer::resolveName(const solidity::frontend::ASTString &, bool, bool) const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9560]
## Description

This contract:
```solidity
contract C {
    /// @inheritdoc 
	function g(x, uint c, uint[] memory c) public {
	}
}

```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/analysis/DeclarationContainer.cpp(129): Throw in function vector<const solidity::frontend::Declaration *> solidity::frontend::DeclarationContainer::resolveName(const solidity::frontend::ASTString &, bool, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Attempt to resolve empty name.
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.7.31+commit.f2fa5b5f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for your report once again @agroce !

The test case could be reduced to

```
contract C{
  ///@inheritdoc
  function g() {}
}
```
