### ISSUE TITLE
Replace `bool DeclarationRegistrationHelper::visit(...)` by a more generic visitor like in the Scoper

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9589]
The Scoper now does most of the work of the DeclarationRegistrationHelper - we should remove the asserts in the latter and make its behaviour rely on the ground work done by the Scoper - potentially also using a generic visit function like in the Scoper.

**Comment by ekpyron** [comment]
Will be done as part of https://github.com/ethereum/solidity/issues/13365, closing the issue.
