### ISSUE TITLE
`try`/`catch` for low-level external calls

### ISSUE THREAD

**Issue by adridadou** [ethereum/solidity#9592]
## Description

I'm trying to use the new try / catch feature but it seems that it doesn't recognise address.call to be an external call

## Environment

- Compiler version: 0.7.0
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle and Remix
- EVM execution environment / backend / blockchain client: it's a compilation issue so not relevant
- Operating system: OSX

## Steps to Reproduce

try to compile : 
```
pragma solidity ^0.7.0;


contract TryCatchIssue {
    address payable externalAddress;
    constructor(address payable addr) {
        externalAddress = addr;
    }
    
    
    function callme(bytes calldata data) external {
        try externalAddress.call{value: 100}(data) {
            
        } catch (string memory reason) {
            revert(reason);
        } catch (bytes memory reason) {
            revert();
        }
    }
}
```

I'm expecting to use try / catch but instead I get the error message:
`Try can only be used with external function calls and contract creation calls.`

**Comment by axic** [comment]
I don't remember what was the main requirement, but either we should support `.call`/`.delegatecall`/`.staticall` or report a better error.

**Comment by adridadou** [comment]
yes exactly. I'm trying to retrieve the reason for an error and I have no way if you use .call (or similar calls)

**Comment by ekpyron** [comment]
Low-level calls return a tuple ``(bool, bytes memory)`` - the ``bool`` indicating, if the call failed, the ``bytes memory`` containing the error message as an ABI-encoded call to a function with signature ``Error(string)``. So with low-level calls you are supposed to manually decode the message.
The ``bytes memory`` part will consist of the 4-byte signature of ``Error(string)`` followed by a pointer to the string, which in turn consists of a length and the padded string data.
So for ``revert("abc");`` you can expect the ``bytes memory`` to contain the following:
```
0x08c379a0 -- first 4 bytes of the keccak256 hash of "Error(String)"
0x0000000000000000000000000000000000000000000000000000000000000020 -- relative offset of the string argument
0x0000000000000000000000000000000000000000000000000000000000000003 -- length of the string
0x6162630000000000000000000000000000000000000000000000000000000000 -- padded string "abc"
```

Possibly, we will have a ``try...catch``-like mechanism for low-level calls in the future - or will at least make it easier to decode the error message using ``abi.decode`` with memory array slices. But currently decoding this will involve some manual effort.

**Comment by adridadou** [comment]
ooh that's great news ! Ok I will be using that then.
I would add this to the documentation. In the documentation there is nothing related to the error case and what is returned.

Looking at the return value, it would be nice if there was a way in solidity to handle that without splitting the bytes array

**Comment by ekpyron** [comment]
We'll keep this open for looking into improving the documentation about this.
And hopefully in the future we'll have some mechanisms that makes this easier than having to deal with the raw bytes data.

**Comment by adridadou** [comment]
for anyone getting here and looking for a solution, here is an example on how to do it:
https://ethereum.stackexchange.com/questions/83528/how-can-i-get-the-revert-reason-of-a-call-in-solidity-so-that-i-can-use-it-in-th

**Comment by Skyge** [comment]
So if I want to use `try catch`, I have got to use a specific function name rather than some raw data, right? Such as I should use
```
try IERC20(tokenAddress).transfer(to, amount){} catch {revert();}
```
rather than
```
try tokenAddress.call(transferData){} catch {revert();}
```

**Comment by k06a** [comment]
Good idea!

**Comment by k06a** [comment]
I believe this is still worth implementing
