### ISSUE TITLE
Attempt to build statically linked Windows Binaries

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9594]
Currently our binaries depend on a bunch of msvc*dll's and I think we are currently actually even shipping the wrong ones in the release archives (32-bit instead of 64-bit dlls with 64-bit executables; not sure that'd actually work or people just happen to have the correct dlls installed globally instead). If possible, statically linking might be nicer.

Might work with
https://cmake.org/cmake/help/v3.15/prop_tgt/MSVC_RUNTIME_LIBRARY.html

We need to investigate whether there's any potential issues or disadvantages with this.
Especially, this might have unexpected interactions with whatever version of boost we're linking against.

**Comment by ekpyron** [comment]
If static linking is *not* possible for whatever reason, we should have cmake decide which DLLs to package, i.e. add
https://github.com/ekpyron/solidity/pull/12/files#r467897986
and have whatever CI script packs the release do this based on a cmake install instead of manually copying.

**Comment by chriseth** [comment]
@cameel is this done?

**Comment by cameel** [comment]
Yeah, I think that @ekpyron's #9811 covers that.
