### ISSUE TITLE
Allow assignment of tuple to struct and vice versa

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#9599]
Example:
```
struct Position { int x; int y; }

Position[2] memory pos;
pos[0] = (-1, -1);
pos[1] = (1, 2);

function matches(Position memory _pos) returns (int a, int b)
{
    (a, b) = _pos;
}

function matches2(Position memory _pos) returns (int a, int b)
{
    return _pos;
}
```

**Comment by CryptoKiddies** [comment]
Is this feature still under consideration? It would be convenient to assign a struct directly to variables listed in a LHS tuple.

**Comment by cameel** [comment]
Probably not in the near future. The situation is similar to https://github.com/ethereum/solidity/issues/9598#issuecomment-733721782. We would probably accept PRs but it's not on our roadmap right now.
