### ISSUE TITLE
Allow tuples to fill the function parameters when passed as parameter

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#9600]
Example:

```
contract S
{
    function foo(int _a, int _b) public pure { .. }

    function bar() public returns (int, int) { return (1, 2) }

    function foobar() public {
        foo(bar());
    }   
}
```

**Comment by chriseth** [comment]
This might be convenient but we should really make this clear in the syntax, for example in the way python does it.

**Comment by Marenz** [comment]
For those who don't know how python does it (I had to look it up): 

In Python, you can expand list, tuple, and dictionary (dict), and pass each element to function arguments.

Add * to a list or tuple and ** to a dictionary when calling a function, then elements are passed to arguments.Note the number of asterisks *.

Here, the following contents will be described.

* Expand list and tuple with *
  * With default arguments
  * With variable-length arguments
* Expand the dictionary (dict) with **
  * With default arguments
  * With variable-length arguments

Source: https://note.nkmk.me/en/python-argument-expand/

**Comment by pertsev** [comment]
This feature can be extremely useful for validation. E.g.

```solidity
function isSomethingValid() public view returns (bool, string memory);
require(isSomethingValid);
```

Right now we have to write something like
```solidity
(bool isValid, string reason) = isSomethingValid();
require(isValid, reason);
```

**Comment by chriseth** [comment]
Syntax suggestion:
``require(..isSomethingValid())`
