### ISSUE TITLE
Disallow spaces in the Yul return value arrow ``- >``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9605]
I guess the fact that this is allowed is rather a parsing accident than actually intentional? I only noticed, since there's one semantics test ``test/libsolidity/semanticTests/inlineAssembly/inline_assembly_function_call.sol``, that uses this (I guess due to a typo).

**Comment by axic** [comment]
I actually noticed this while looking at the parser, I think I wanted (or did?) clean it up with #9555.

It requires a scanner improvement though (a specific token for `->`), which would be possible after #9331 is merged.

**Comment by ekpyron** [comment]
Strictly speaking it's a breaking change :-)... but I'd be fine with calling this a bugfix...

**Comment by leonardoalt** [comment]
+1 for bugfix

**Comment by axic** [comment]
I'm also voting for bugfix, the intention clearly wasn't `function f(a, b) -              > x, y {}`.

**Comment by axic** [comment]
Ran all the tests in #9612 with the scanner change enabled for both Yul/Solidity modes and there is no failure in the repository. 

I'd propose we consider adding the token in general and would risk calling it non-breaking :wink:

**Comment by ekpyron** [comment]
+1 for making it a general token

**Comment by ekpyron** [comment]
Also relabeling it, since I think we tend *not* to consider it breaking, which at least I think would be fine.

**Comment by axic** [comment]
@chriseth 1) do you consider this breaking for Yul? 2) do you consider it breaking for Solidity?

**Comment by chriseth** [comment]
I would say disallowing `- >` for yul is a bugfix. The question is whether the required changes in the scanner could be considered breaking for tools.

**Comment by axic** [comment]
As noted in #9612 enabling it unconditionally (for Solidity too) makes no test to break and with @ekpyron we couldn't find a case where it would be valid syntax.

**Comment by chriseth** [comment]
Ok, bugfix it is!

**Comment by axic** [comment]
So are we adding it is a generic keyword/token for both Solidity and Yul scanner modes? I couldn't find a case where this would cause problems.

**Comment by chriseth** [comment]
Yes!
