### ISSUE TITLE
[Not very sure] at line of 404 and 407 in file ContractCompiler.cpp, both asserts are fallback?

### ISSUE THREAD

**Issue by skywormfol** [ethereum/solidity#9608]
## Description

I didn't test, as titled, at line of 404 and 407 in file ContractCompiler.cpp, both asserts are fallback?
https://github.com/ethereum/solidity/blob/e68d16d8e09fafac6f6913d961a0f8e4de5573dd/libsolidity/codegen/ContractCompiler.cpp#L402

They should be different, right? for fallback and etherReceiver?

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by axic** [comment]
That seems to be a bug.
