### ISSUE TITLE
Turn on ABIEncoderV2 by default

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9609]
**Question: should there be a pragma for enabling ABIEncoderV1?**

Should track here what is needed to achieve this: TBA

**Comment by axic** [comment]
I could see us enabling V2 in 0.8.0 but keeping V1 for another major release and only dropping it in 0.9.0.

**Comment by ekpyron** [comment]
Hopefully, we'll have proper fuzzing against the Isabelle implementation soon. It'd be much safer to only default to it, once we can properly fuzz it.

**Comment by chriseth** [comment]
I'm actually not too worried about correctness, I'm more worried about increased gas costs.

**Comment by chriseth** [comment]
We could have a pragma to set the abi coder to v1, and enable v2 by default.

**Comment by axic** [comment]
Could have a pragma like `pragma ABICoder V1` and `pragma ABICoder V2` and we default to V2 if not set?

**Comment by chriseth** [comment]
Discussion:

 - `pragma abicoder v1`
 - `pragma abicoder v2` (default from 0.8)
 - `pragma experimental ABIEncoderV2` generates warning.

Support in 0.7.x already:

 - `pragma abicoder v1`
 - `pragma abicoder v2`

**Comment by axic** [comment]
I really wish we could remove the `pragma experimental ABIEncoderV2`, and not wait until 0.9.0 to do so :wink:

**Comment by chriseth** [comment]
I'll wait with this until some more tests are extracted.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/10336
