### ISSUE TITLE
Disallow "using for" in interfaces.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9611]
There's no use, since "using for" is no longer inherited, is there?
This is strictly speaking a breaking change, but I'd call it a bugfix instead.

**Comment by axic** [comment]
I think this is a bugfix, because interfaces were never supposed to allow `using for`, and if they did, that was freak of life.

See https://solidity.readthedocs.io/en/v0.7.0/contracts.html#interfaces

**Comment by chriseth** [comment]
Sounds good!
