### ISSUE TITLE
Replace "returns" with "->" in function definitions (and other use cases)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9616]
**Warning: this issue is not too much thought out yet.**

While implementing #9605 and making that a feature of `ScannerKind::Yul` I realised that perhaps that token is invalid in the current Solidity language syntax and could unconditionally enable it. This sparked some ideas about how it could be used.

---

1. Replace `returns` with`->`:

```
function approve(uint amount) -> (bool) external pure {}
```

Side comment:
> Perhaps grouping the input and output and then having specifiers follow is more readable. Though one could argue that some specifiers (such as modifiers) logically belong before the output declaration as they are "processed” before the output is returned.

---

2. Use it in function types

```
function (uint, uint) returns (uint)`
```
would be reduced to
```
(uint, uint) -> (uint)
```

@ekpyron pointed out:
> `function (uint, uint) -> (uint) public x;`... is the state variable public or the function type?

---

3. Use it for lambdas:

```
lambda min = (uint, uint) -> (uint) { }
```

**Comment by ekpyron** [comment]
I'm all for that, if we find a solution for the function type ambiguity. We can even do it non-breakingly, if we keep ``returns`` with a deprecated warning. People will probably hate us for it, though, because this would literally break almost every contract out there I guess :-).

**Comment by ekpyron** [comment]
Actually the function type ambiguity may not be related to this that much... we already do have this problem for function types without return values, i.e. we have stuff like ``function() internal internal x;``, etc. - so the arrow wouldn't make this *that* much worse...

**Comment by ekpyron** [comment]
Is this actually breaking or can we transition by allowing both :-)?

**Comment by ekpyron** [comment]
For the record: I let this one run out and be closed intentionally - but in connection with https://github.com/ethereum/solidity/issues/1349 we may actually want to consider this after all, so I'm linking this to that issue.
