### ISSUE TITLE
Clean up Yul testing with regards to dialects

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9620]
As it was found many times (e.g. https://github.com/ethereum/solidity/pull/9619#discussion_r470049441) the current Yul testing is not the best organised.

Problem 1: In `YulSyntaxTests`  the dialect "evm" means evm-with-objects and there is not way to represent evm-without-objects. 

Problem 2: With having too many dialects we end up duplicating the same tests multiple times. Perhaps the dialect settings should be an array of accepted dialects (inclusion list), or an exclusion list. e.g. `dialect: evm, evmTyped, evmWithObjects`

Problem 3: A lot of tests are still present as boost tests.

**Comment by ekpyron** [comment]
Actually, neither the builtin checks nor the dot-stuff should be done in the Yul Scanner or Parser.
Then we could just have one parser, one scanner and one grammar for all of (untyped) yul.
And the differences would only be during analysis, i.e. we have pure yul syntax tests that are merely split as "typed" and "non-typed" and then yul analysis tests, which check that dots are excluded in identifiers and builtins are reserved - and only the latter depend on the dialects.

**Comment by ekpyron** [comment]
Once this is done, we could start testing the inline assembly grammar against the yul parser tests again...
