### ISSUE TITLE
Make `from` a full keyword or a proper "import-mode-only" keyword.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9621]
`from` is a keyword, but it is actually allowed as identifier as well anywhere - the only place where it actually is used as a keyword is in import statements.
We should either:
 - make it a full regular keyword that's diallowed in identifiers
or
 - add another scanner mode for imports and only make "from" a keyword in that mode.

**Comment by chriseth** [comment]
The main argument against making `from` a keyword is that it is a really common variable name.
