### ISSUE TITLE
[solc] ICE because there was an attempt to resolve an empty name

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9623]
## Description

```
contract C {
  ///@inheritdoc .
  t[]i;
}
```

throws

https://github.com/ethereum/solidity/blob/b1fb9da63aa22f65173a7c3a93d06fbe76abba36/libsolidity/analysis/DeclarationContainer.cpp#L129

May be related to https://github.com/ethereum/solidity/issues/9560 that was fixed by https://github.com/ethereum/solidity/pull/9567

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by hrkrshnn** [comment]
https://github.com/ethereum/solidity/pull/9684 should fix this.
