### ISSUE TITLE
Long chain of calls produces "Stack too deep"

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#9624]
## Description

Long chain of calls produces "Stack too deep"

## Environment

- Compiler version: 0.6.12, 0.7.0

## Steps to Reproduce

```solidity
pragma solidity ^0.6.0;

library Math {
    function add(uint256 a, uint256 b) internal pure returns(uint256) {
        return a + b;
    }
}

contract A {
    using Math for uint256;

    function f(uint256 a) public pure returns(uint256) {
        return a.add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a);
    }
}
```
=>
```
CompilerError: Stack too deep, try removing local variables.
```

**Comment by chriseth** [comment]
Thanks for opening this issue, but stack too deep errors unfortunately cannot be eliminated until we have the new code generator.

**Comment by k06a** [comment]
@chriseth it seems like a bug, because this long chained calls are processed somehow strage...

**Comment by chriseth** [comment]
@k06a can you explain what you mean by "processed strange"? What you reported seems to me like a known limitation of the compiler which will be fixed with the new code generator.

**Comment by k06a** [comment]
I mean chained calls could be processed sequentially on single variable, not nested:
```
b = a.add(a);
b = b.add(a);
b = b.add(a);
b = b.add(a);
b = b.add(a);
b = b.add(a);
b = b.add(a);
b = b.add(a);
```

**Comment by chriseth** [comment]
I think the problem here is the fact that bound functions are used and the logic to remove the library address is not that clever. I would like to ask you to be patient until the new code generator is ready which will solve such problems without an issue.

**Comment by LukeSamkharadze** [comment]
Bump, I have the same problem.

**Comment by ekpyron** [comment]
The new code generation pipeline is pretty much stable right now - it's still nominally called ``experimental``, but we'll change that in the upcoming releases - so if it's an option for you, you can try to use the most recent compiler version with ``--experimental-via-ir --optimize`` and it may very well be that the problem is gone with that.

**Comment by LukeSamkharadze** [comment]
How can we specify `--experimental-via-ir --optimize` [here](https://docs.soliditylang.org/en/v0.6.6/using-the-compiler.html#input-description) in settings field?

**Update:**

Look through [latest](https://docs.soliditylang.org/en/v0.8.11/using-the-compiler.html#input-description) docs, option is called `viaIR`
