### ISSUE TITLE
[Yul] Consider optimiser annotations at least in standalone Yul (e.g. "inline"/"noinline")

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9628]
Inspired by the issue in https://github.com/ethereum/solidity/issues/9622

I'm not entirely sure this is a good idea - but Yul will probably be used for highly-optimized low-level implementations. Arguably those will be manually optimised and will just disable the optimiser, but the better the optimiser gets the more valuable it may be even in such use cases. But as demonstrated in https://github.com/ethereum/solidity/issues/9622 there may be cases where the optimiser actually interferes.

While tweaking the optimiser sequence may or may not help here, what might really help would be annotations in Yul that affect optimisations.

In particular two come to mind: ``inline`` and ``noinline``. But there may be more e.g. a ``don't rematerialize across this boundary`` annotation, etc. They would need to be carefully chosen not to interfere with any optimiser step and I'd imagine them always only acting as "hints"...

**Comment by axic** [comment]
Hah, but not constant, right? :wink:

**Comment by axic** [comment]
We could consider generic attributes/hints/decorators. Some potential syntactical options:
```
//@inline
function f() {}

//#inline
function f() {}

function f() hint(inline) {}

function f() attribute(inline) {}

//@const
let x := 1

//#const
let x := 1

let x hint(const) := 1
```

**Comment by ekpyron** [comment]
I'd defer the constant debate back to https://github.com/ethereum/solidity/issues/5928 :-). I still think it would only be syntactical and won't really affect the optimiser, I'll elaborate a bit more on that there and would try to keep this here about decorators in general and try to stick to the inline example, because I think that's the most promising first choice for a thing like this.

Apart from that I think there's three questions:
- Do we think this is beneficial to have at all? Are there conceptual pro's and con's? Independently of *how* this would be done syntactically.
- If we want it, should it be actual proper Yul syntax or comments, what's the pro's and con's of that.
- What would be the precise syntax.

**Comment by ekpyron** [comment]
An example for a conceptual issue would be this:
```
//@inline
function f() { sstore(calldataload(0), calldataload(1)) }
//@noinline
function g() { sstore(calldataload(0), calldataload(1)) }
```

The optimiser will recognize that they're equivalent and unify them... but what does that mean for the hints? It'd probably just be dropped in this case - which is why the annotations are probably better just considered hints and nothing more... and maybe this already means that the concept is inherently flawed, I'm not sure...

**Comment by chriseth** [comment]
If possible, I would like to avoid source code having an effect on the optimizer. Once we do that, we have to consider changes in the inner workings of the optimizer being breaking changes. Furthermore, the whole concept of inlining is exposed to the frontend - we don't even know whether inlining is the right step to take - we are also considering just function specialization without inlining.

**Comment by chriseth** [comment]
Also, can you please summarize the main problem referenced in #9622  ?

**Comment by ekpyron** [comment]
The problem in #9622 was a recursive function that only worked for a limited number of recursive calls due to the 1024 stack slot limit of the EVM. That's something that's hard for the optimiser to recognize (it would need to guess whether a recursion is meant to be deep or only shallow). Before #9622 I'd say that's an artifical problem, but the issue is proof that stuff like that actually happens for people.

So the solution was to reduce the local variables on stack during the recursive function call (up to manually using customly allocated memory frames to store locals, arguments and return values, instead of the stack) - but the optimiser makes that very hard, because it doesn't know what you're trying to achieve and inlines, resp. CSEs variables contrary to the manual stack optimisation.
An easy way to do it would be either
```
function eval() { evalPre() eval() evalPost() }
//@noinline
function evalPre() { }
//@noinline
function evalPost() { }
```
or
```
function eval() {
  {
    // evalPre
  }
  //@cse-guard or @variable-guard
  eval()
  {
    // evalPost
  }
}
```

Where ``evalPre`` and ``evalPost`` manage the arguments, return values and "locals" in memory frames. But the optimiser messes up both - in the first case it inlines (basically arriving at the second case) and in the second case it reuses variables from the top part in the bottom part during CSE, increasing the recursive stack strain. (hence the hints that could prevent this in both cases)

In the end the "solution" was to use ``--yul-optimizations ""`` to enable stack optimization, but not have CSE mess up the intended stack layout (I'm actually not quite sure why the hard-coded post-optimization steps didn't also mess things up, but it happened to work fine in that particular case).  We could argue that this is a very special case which needs manual magic trickery anyways, but yeah - it made me wonder whether fine-tuning the optimiser might make sense, since highly optimised custom complex routines like that are well within the expected use of Yul I guess.

**Comment by ekpyron** [comment]
We could get around making optimiser changes breaking due to this by clearly stating that those are "hints that may or may not have an actual effect" (just as GCC or clang do with hints like this).
But yeah, in general I'm not sure about it either, but it's worth considering IMO.

**Comment by chriseth** [comment]
Ah ok, but in that case, I would say: Whenever there is recursion, it is meant to be deep recursion and thus we should limit the number of local variables on the stack for such functions.

**Comment by axic** [comment]
How about having the ability to disable certain optimisation steps for certain functions? A standard decorator which does that. The compiler would throw an error if it refers to an invalid step.
