### ISSUE TITLE
ICE in virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const [assert]

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9629]
## Description

This contract:
```solidity
contract C {
    constructor() {
		assert(tx.gasprice == msg.value);
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/AST.cpp(294): Throw in function virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.8.7+commit.241a564f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for reporting @agroce !

This looks like a variation of https://github.com/ethereum/solidity/issues/9509 that throws the same exception!

**Comment by bshastry** [comment]
A smaller repro

```
contract C {
  constructor() { (msg.value); }
}
```
