### ISSUE TITLE
Associativity of exponentiation operator is counter-intuitive.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9637]
Solidity parses `a**b**c ` as `(a**b)**c` (like any other binary operator) while the expected grouping could be `a**(b**c))`.

**Comment by ekpyron** [comment]
For the record: the antlr grammar already pretends that this is fixed, so no change to the grammar should be needed.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/10019
