### ISSUE TITLE
Associativity of modulo operator produces an invalid opcode error in require statement.

### ISSUE THREAD

**Issue by gitpushOmnik** [ethereum/solidity#9643]
**DESCRIPTION**

While comparing the **associative** property of **modulo** operator in `require` statement, Solidity throws an invalid opcode error. **Modulo** function is not associative in nature. Nevertheless, while comparing two modulo expression in require statement, an error is generated. 

The error is generated in the below code snippet.
 `require((a%b)%c != d%(e%f));`
   
The code runs fine if I put the parentheses for the first two constants i.e d and e . But the code fails and produces an error if the parentheses are put for last 2 constants e and f.

`require((a%b)%c != (d%e)%f);` works fine.

`require((a%b)%c != d%(e%f));` produces an invalid opcode error.

The function I used to test was 

    function calculate() public {  
        require((a%b)%c != d%(e%f));
    }

Error : 
    `VM error: invalid opcode. invalid opcode The execution might have thrown. Debug the transaction to get more information.`

**ENVIRONMENT**

Framework/IDE : Remix
Operating System : MacOS

**Comment by chriseth** [comment]
Do you have any example values for the variables? Note that the modulo operation results in an invalid opcode if the second operand is zero - might that be the reason?

**Comment by gitpushOmnik** [comment]
No. i didn't assign value zero to any variable. All the variables were assigned a non negative value. I used the following values.

    contract Sample {
    uint a = 3;
    uint b = 4;
    uint c = 2;
    uint d = 3;
    uint e = 4;
    uint f = 2;

    function calculate() public{
        require((a%b)%c != d%(e%f));
    }
    }

**Comment by hrkrshnn** [comment]
`e%f` is 0 here. That explains the `invalid`.

**Comment by gitpushOmnik** [comment]
Oh yes. My bad. Completely missed it.
