### ISSUE TITLE
Implicit conversion from array literals to dynamically-sized arrays

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9645]
Array literals should be implicitly convertible to both statically-sized arrays of the same type and dynamically-sized arrays of the same type. This could be solved by making array literals their own type. This can be done in a similar way as we handle string literals: The code generator delays the actual conversion until the target type is known. Only then do we decide whether we store the length in memory (dynamic array) or not.

This is part of https://github.com/ethereum/solidity/issues/431 - which will probably not be implemented in full.

**Comment by mudgen** [comment]
I want this functionality.   Is it something that will be implemented sometime soon?

**Comment by skyfly200** [comment]
I to really need this!

**Comment by xy137** [comment]
please add this

**Comment by chriseth** [comment]
Closing as duplicate of https://github.com/ethereum/solidity/issues/11879 (which has more comments by now).
