### ISSUE TITLE
Switch Control Structure

### ISSUE THREAD

**Issue by bbzorba** [ethereum/solidity#9647]
Hello,
I am developing a model based on switch control structure in Solidity. In Solidity 0.4.7 switch does not exist but according to Solidity documentation 0.6.7 switch has been added to the language already. Does anyone know why the remix compiler 0.6.7 or higher gives the following error:
Parser Error: Function, variable, struct or modifier declaration expected.
switch (variable)
^---^

**Comment by chriseth** [comment]
`switch` is part of Yul, i.e. inline assembly, but not of Solidity itself.

**Comment by bbzorba** [comment]
So how can I use switch in Yul? Can you please introduce me a code?

**Comment by chriseth** [comment]
Does the example here help: https://solidity.readthedocs.io/en/v0.7.0/yul.html#switch ?

**Comment by bbzorba** [comment]
I used the same but gave the same parser error :/ but thanks for trying.

**Comment by chriseth** [comment]
The error sounds like you are using it in Solidity and not in inline assembly. The following should work when you are compiling it in Solidity mode:
```
contract C {
function f() public pure returns (uint x) {
  assembly {
    switch calldatasize()
    case 0 { x := 1 }
    default { x := 2 }
  }
}
}
```

**Comment by bariszorba** [comment]
Actually you are right and this might work, how can I use it in inline assembly using remix ethereum IDE?

**Comment by bbzorba** [comment]
This method solved my problem. Thanks.
