### ISSUE TITLE
Unable to access state variables using this

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#965]
```
contract Scope {

    uint stateVar = 42;

    function getStateVar() constant returns (uint stateVar) {
        stateVar = this.stateVar;
    }

}
```

```
Untitled2:6:20: Error: Member "stateVar" not found or not visible after argument-dependent lookup in contract Scope
        stateVar = this.stateVar;
                   ^-----------^
```

This compiles, but returns 0:

```
stateVar = Scope.stateVar;
```

**Comment by Denton-L** [comment]
You should change your contract to the following:

```
contract Scope {

    uint stateVar = 42;

    function getStateVar() constant returns (uint _stateVar) {
        _stateVar = stateVar;
    }

}
```

This is because Solidity isn't Java. In Solidity, you can only access contract-level variables directly, as shown above. The consequence of this is that you wouldn't want to name your variables in a way such that you have a name collision between function-level and contract-level variables.

Also, you seem to be misunderstanding the purpose of the `this` keyword. The `this` keyword returns the current contract. This means that calling `this.*` will always produce a blockchain transaction with the target of the transaction being the contract, itself. You cannot use it to modify any contract-level variables like in Java.

**Comment by ethernomad** [comment]
@Denton-L see the previous issue: https://github.com/ethereum/solidity/issues/423

Your recommendation is exactly what I am trying to avoid: it makes the functions signatures really ugly. I would rather do `::stateVar = stateVar`

**Comment by Denton-L** [comment]
You cannot currently do that in Solidity. The current convention is to use underscores to differentiate between the two but, other than that, it's not possible.

**Comment by ethernomad** [comment]
I am well aware that you cannot do that. My point is that I really do not like using the underscores and that I hope a better way can be added to Solidity.

**Comment by chriseth** [comment]
@ethernomad so you are saying that the style is the main issue here? What about the following:

```
contract Scope {
    uint stateVar = 42;
    function getStateVar() constant returns (uint) {
        return stateVar;
    }
}
```

Or this one here:

```
contract Scope {
    uint public stateVar = 42;
}
```

**Comment by ethernomad** [comment]
@chriseth Yes this is really just a cosmetic issue. Your example is certainly better, although I prefer to name return variables.

But what about constructors?

```
contract Scope {

    uint public stateVar;

    function Scope(uint _stateVar) {
        stateVar = _stateVar;
    }
}
```

**Comment by axic** [comment]
The following code should be a compilation error, but it silently goes through:

```
contract Scope {
    uint stateVar = 42;

    function getStateVar() constant returns (uint stateVar) {
        stateVar = Scope.stateVar;
    }
}
```

**Comment by chriseth** [comment]
@axic you can access members of base contracts in that way, it is not an error. Does the contract behave as expected?

**Comment by axic** [comment]
@chriseth in this case it is not a base contract, but self. And it doesn't, returns 0.

**Comment by chriseth** [comment]
@axic ok, created https://github.com/ethereum/solidity/issues/988

**Comment by axic** [comment]
I think using `this` in the constructor should be a straight error: #1057.

**Comment by chriseth** [comment]
This is fixed now: `this.stateVar` correctly creates an error and `this.stateVar` returns 42.
