### ISSUE TITLE
Prevent YUL optimizer from changing certain values to identifiers.

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#9653]
Currently the following YUL code with args:  `--strict-assembly --optimize --ir-optimized`
```
{
    let a := f(mload(1))
    let b := f(a)
    sstore(a, b)
    function f(x) -> y
    {
        if iszero(x) { revert(0, 0)}
        if iszero(add(x, 1)) { revert(0, 0)}
    }
}
```

produces the following result:
## Results

```

Pretty printed source:
object "object" {
    code {
        {
            let a := f(mload(1))
            sstore(a, f(a))
        }
        function f(x) -> y
        {
            if iszero(x) { revert(y, y) }
            if iszero(add(x, 1)) { revert(y, y) }
        }
    }
}
```

The change of `0` to `y` prevents UnusedFunctionParamterPruner from optimizing out the return value.

**Comment by chriseth** [comment]
Some optimizer steps use the fact that return variables are zero initially. On the other hand, such a code can also be the input for the optimizer, so I think we should make sure that after e.g. SSA transform, a literal zero is used instead. Also, input code for the optimizer might assign to function parameters before they are read from. Such parameters should also be marked as unused.

**Comment by hrkrshnn** [comment]
@chriseth Shouldn't `LiteralRematerialiser` be able to do this?

**Comment by hrkrshnn** [comment]
Running `LiteralRematerialiser` right before `UnusedFunctionArgumentPruner` in FullSuite seems to work.

**Comment by axic** [comment]
Was this fixed?

**Comment by chriseth** [comment]
@hrkrshnn I think this was not needed in the end, was it?

**Comment by hrkrshnn** [comment]
Running LiteralRematerialiser before the step was enough. So closing.
