### ISSUE TITLE
[SMTChecker] ICE in void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9654]
## Description

This contract:
```solidity
pragma experimental SMTChecker;
function verify(bytes32[] memory proof) returns (bool) {
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(686): Throw in function void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.8.20+commit.4a720a65.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for reporting the issue!

NTS: Smaller repro

```
pragma experimental SMTChecker;
function f() {}
```

**Comment by bshastry** [comment]
Looks like one of the first free functions related issues.

**Comment by agroce** [comment]
I should really get a better reduction using CReduce going here.  :)

**Comment by leonardoalt** [comment]
> Looks like one of the first free functions related issues.

Yea, I guess we'll start seeing quite a few of those :p

**Comment by axic** [comment]
I think this is simply due to #9636. Can we close this? Added `fuzz-blocker` to #9636.

**Comment by bshastry** [comment]
Sure, closing issue now in favour of #9636
