### ISSUE TITLE
I think this should use `move` instead of `send`.

### ISSUE THREAD

**Issue by PL0948065540** [ethereum/solidity#9657]
I think this should use `move` instead of `send`.

_Originally posted by @axic in https://github.com/ethereum/solidity/issues/4636#issuecomment-409585998_

**Comment by PL0948065540** [comment]
> I think this should use `move` instead of `send`.
> 
> _Originally posted by @axic in [#4636 (comment)](https://github.com/ethereum/solidity/issues/4636#issuecomment-409585998)_

**Comment by hrkrshnn** [comment]
Are you a bot that makes issues?
