### ISSUE TITLE
ICE in size_t solidity::frontend::CompilerContext::immutableMemoryOffset(const solidity::frontend::VariableDeclaration &) const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9658]
## Description

This contract:
```solidity
contract A {
    uint immutable public x = 1;
    function f() public returns (uint256) {
	++x;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/codegen/CompilerContext.cpp(87): Throw in function size_t solidity::frontend::CompilerContext::immutableMemoryOffset(const solidity::frontend::VariableDeclaration &) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Memory offset of unknown immutable queried.
[solidity::util::tag_comment*] = Memory offset of unknown immutable queried.
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.8.20+commit.4a720a65.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by bshastry** [comment]
Thank you for reporting this issue! It looks like a duplicate of #9196 that is to be fixed by #9568

**Comment by agroce** [comment]
Ah, I did a search for the ICE, and it didn't come up, odd.

**Comment by bshastry** [comment]
No worries, sometimes the title is worded differently :-)

Could we close this issue?

**Comment by agroce** [comment]
Sure, if it's a dup
