### ISSUE TITLE
[SMTChecker] std::out_of_range exception because key not found in map

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9667]
## Description

The following multi source test

```
==== Source: A.sol ====
contract A { function f() public {} }
==== Source:====
import "A.sol";
pragma experimental SMTChecker;
contract C is A {}
```

throws the said exception from here:

https://github.com/ethereum/solidity/blob/29b6c1724621e01924c55febab9a9c55807e9ad7/libsolidity/formal/CHC.cpp#L936

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ cp test.sol test/libsolidity/syntaxTests/multiSource/import_smt.sol
$ isoltest -t syntaxTests/multiSource/import_smt
syntaxTests/multiSource/import_smt.sol: Exception during test: map::at
```

**Comment by bshastry** [comment]
I suppose the problem is SMTChecker not being enabled on the imported source, but perhaps this should be a warning or even silently skip verification?

**Comment by leonardoalt** [comment]
I think it's because it only considers a single SourceUnit.
