### ISSUE TITLE
ICE in vector<const solidity::frontend::Declaration *> solidity::frontend::DeclarationContainer::resolveName(const solidity::frontend::ASTString &, bool, bool) const

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9669]
## Description

This contract:
```solidity
contract C {
  ///@inheritdoc .
  function f() {
  }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/analysis/DeclarationContainer.cpp(129): Throw in function vector<const solidity::frontend::Declaration *> solidity::frontend::DeclarationContainer::resolveName(const solidity::frontend::ASTString &, bool, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Attempt to resolve empty name.
[solidity::util::tag_comment*] = Attempt to resolve empty name.
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

Similar to #9560 -- but the . after inheritdoc seems to be the difference

## Environment

- Compiler version:  0.7.1-develop.2020.8.20+commit.4a720a65.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by chriseth** [comment]
I thought this was fixed in develop, but it turns out that the `.` makes a difference. Thanks for reporting! :)
