### ISSUE TITLE
Cmake version (?)

### ISSUE THREAD

**Issue by 0xalizk** [ethereum/solidity#9697]
On the installation page it says [Cmake v 3.9+](https://solidity.readthedocs.io/en/v0.5.12/installing-solidity.html#prerequisites-all-operating-systems) but the latest [Cmake version is v3.18.x](https://cmake.org/download/) .. is this a typo?

**Comment by axic** [comment]
This refers to the minimum requirement of the Solidity build system: https://github.com/ethereum/solidity/blob/develop/CMakeLists.txt#L1

**Comment by 0xalizk** [comment]
There is no such thing as Cmake v3.9 though (?)

**Comment by axic** [comment]
There is: https://cmake.org/cmake/help/latest/release/3.9.html

The documentation also says it requires 3.9 as a **minimum**. You can use 3.18.x.

**Comment by 0xalizk** [comment]
Ah v3.9 = v3.09 .. I get it now thanks.
