### ISSUE TITLE
Allow solidity function type support library-external functions 

### ISSUE THREAD

**Issue by djken2006** [ethereum/solidity#9704]
The following code leads to compilation error:

ArrayUtils.sol:34:32: TypeError: Invalid type for argument in function call. Invalid implicit conversion from function (uint256) pure returns (uint256) to function (uint256) pure external returns (uint256) requested.
        return (arraySum(a, b, LibMath.square), arraySum(a, b, LibMath.cube));
                               ^------------^
```
LibMath.sol
// SPDX-License-Identifier: UNLICENSED

pragma solidity 0.7.0;

library LibMath {
    function square(uint256 x) external pure returns (uint256) {
        return x * x;
    }

    function cube(uint256 x) external pure returns (uint256) {
        return x * x * x;
    }
}

ArrayUtils.sol
// SPDX-License-Identifier: UNLICENSED

pragma solidity 0.7.0;
import "./LibMath.sol";

contract ArrayUtils {
    function arraySum(
        uint256[] memory a,
        uint256[] memory b,
        function(uint256) external pure returns (uint256) f
    ) private pure returns (uint256) {
	require(a.length == b.length);
		
        uint256 sum = 0;
        for (uint256 i = 0; i < a.length; i++) {
            sum += f(a[i]) + f(b[i]);
        }
		
        return sum;
    }

    function test() public pure returns (uint256, uint256) {
        uint256[] memory a = new uint256[](3);
        uint256[] memory b = new uint256[](3);

        a[0] = 1;
        a[1] = 2;
        a[2] = 3;

        b[0] = 4;
        b[1] = 5;
        b[2] = 6;

        return (arraySum(a, b, LibMath.square), arraySum(a, b, LibMath.cube));
    }
}
```

**Comment by chriseth** [comment]
Unfortunately, this is not possible. External function types use the `call` opcode while external library functions use the `delegatecall` opcode. An implicit conversion would be very misleading. Note that calling an external function on every array element is probably not what you want to do anyway because it gets very expensive.
