### ISSUE TITLE
ASTImportTests.sh broken on OS X (readlink: illegal option -- f)

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9712]
## Description
When running command line tests on OS X, `ASTImportTests.sh` fails:
```
readlink: illegal option -- f
```

This does not interrupt the test and is not counted as a failure due to #9711.

## Environment and Steps to Reproduce
I don't have an OS X machine to reproduce it but I saw it happen on Circle CI: https://app.circleci.com/pipelines/github/ethereum/solidity/7779/workflows/f0154452-154a-4d2e-bced-8c2d2c3307e2/jobs/425012/parallel-runs/0/steps/0-104

Here's the relevant part of the output
```
...
test_ff8dae9dd63552890d3ae9b14087dd65e234bba8c6a194abed10cf36b6712c30_security_considerations_rst.sol
Done.
Testing library checksum...
Testing long library names...
Testing linking itself...
Linking completed.
Testing overwriting files...
Testing assemble, yul, strict-assembly and optimize...
Testing standard input...
Testing AST import...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
find: /test/libsolidity/syntaxTests: No such file or directory
Looking at        0 .sol files...
find: /test/libsolidity/syntaxTests: No such file or directory
find: /test/libsolidity/ASTJSON: No such file or directory

SUCCESS: 0 syntaxTests passed, 0 failed, 0 could not be compiled (       0 sources total).
Testing soljson via the fuzzer...
Commandline tests successful.

CircleCI received exit code 0
```

**Comment by axic** [comment]
Yes, `readlink` is a pain, because BSD/UNIX/GNU differ. @ekpyron and I have complained about this on Gitter a few times :)

**Comment by cameel** [comment]
Yeah, I did run into these kinds of errors in the past. `mktemp` is another repeat offender :)
Multi-platform CI actually makes finding this stuff manageable but in this particular case #9711 got in the way making it harder to find...
