### ISSUE TITLE
When an array is in a struct it should be possible to specify the number of bytes used to store the length

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#974]
Array lengths are always stored as a single slot. Often 1 to 3 bytes would be sufficient. It would be great if the maximum length could be specified and the length state be packed into a struct.

Currently this requires a lot of custom coding.

**Comment by chriseth** [comment]
What is the goal you want to achieve here? The array length deliberately occupies a full slot so that offsets of the data area (= sha3 of the length slot) are unique.

**Comment by ethernomad** [comment]
In [this contract](https://github.com/bluedroplet/blobstore-ethereum/blob/master/blobstore.sol) I packed the length of the packedRevisionBlockNumbers mapping (numRevisions) into the struct. If I used the built-in array functionality the struct would be 2 slots instead of 1.

**Comment by chriseth** [comment]
This adds a complication that is only beneficial in very specific cases. Closing.
