### ISSUE TITLE
[SMTChecker] ICE in SMTEncoder::assignment

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9743]
## Description

```
pragma experimental SMTChecker;
contract C {
  int[][] array2d;
  function s() internal returns (int[] storage) {
    array2d.push() = array2d.push();
    return array2d[2];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/f964966090f7e3571e20144fd4aa0b6391aea26e/libsolidity/formal/SMTEncoder.cpp#L1497

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by cameel** [comment]
It started happening in 0.7.2. The failing assertion was introduced in #9670. The PR added support for struct assignments and I think that the fact that assigning to the result of `push()` is another type of assignment that's still not supported was missed.

Simpler repro:
```solidity
pragma experimental SMTChecker;

contract C {
    uint[] b;

    function f() public {
        b.push() = 1;
    }
}
```

### Output on 0.7.1 (for the simpler repro)
```
Warning: Assertion checker does not yet implement such assignments.
 --> /tmp/test2.sol:7:9:
  |
7 |         b.push() = 1;
  |         ^^^^^^^^^^^^
```
