### ISSUE TITLE
Multiple inheritance with base classes having same function name and arguments causes an error

### ISSUE THREAD

**Issue by gitpushOmnik** [ethereum/solidity#9761]
- It seems that Solidity doesn't accept multiple inheritance with base class functions having the same name and same function arguments regardless of whether they're private or public. In support to #9610 

- Suppose i want to apply multiple inheritance using 2 base classes, with both containing a function with the same name and arguments we get a type-error. 

- Now the problem doesn't only rely if both the base classes are present in the same .sol file. A bigger problem is when both base classes are in different .sol files and we try to import both files in the contract containing derived class. It causes ambiguity

-I'm providing an example wherein the base classes are in different files.

File1 : contract1.sol

    pragma solidity >=0.5.0 <0.7.0;
    contract Base1 {
        uint a=4;
        uint b=6;
        function pu() public view returns(uint){
            return a+b;
        }
    }

File2: contract2.sol

    pragma solidity >=0.5.0 <0.7.0;
    contract Base2  {
        uint c=7;
        uint d=8;
        function pu() public view returns(uint){
           return c+d;
        }
    }

Main.sol

    pragma solidity >=0.5.0 <0.7.0;
    import "contract1.sol";
    import "contract2.sol";
    contract derived is Base1,Base2 {
        function ca() public view returns(uint){return Base1.pu();}
    }

    browser/main.sol:6:5: TypeError: Derived contract must override function "pu". Two or more base classes define function 
    with same name and parameter types. contract derived is Base1,Base2 { ^ (Relevant source part starts here and spans 
    across multiple lines). contract1.sol:5:9: Definition in "Base1": function pu() public view returns(uint){ ^ (Relevant source 
    part starts here and spans across multiple lines). contract2.sol:5:9: Definition in "Base2": function pu() public view 
    returns(uint){ ^ (Relevant source part starts here and spans across multiple lines).

I think, above description pretty much explains it.

**Comment by chriseth** [comment]
This is a safety feature introduced with Solidity 0.6. The compiler asks you to tell it that you are aware of the fact that Base2 also defines a function named `pu` and that you want to ignore it. You have to add `override(Base1, Base2)` to the function header. Documentation: https://solidity.readthedocs.io/en/v0.7.1/contracts.html#function-overriding

Please feel free to reopen the issue.

**Comment by gitpushOmnik** [comment]
Thank you @chriseth for clearing things up. I just had one more query. What if the functions that we are overriding are of private visibility. There is no virtual keyword for private functions, right?

**Comment by chriseth** [comment]
Yes, this unfortunately does not work, and I think it would also be confusing. Can you work with functions at file-level instead of private functions inside contracts?

**Comment by gitpushOmnik** [comment]
Yes sure I can. Thanks @chriseth . Also, do you think we could add a specific error statement regarding the prohibition of virtual keyword with private functions. Because if we don't write virtual for public functions, it gives the same error as that for ambiguity with private functions with same name and args. So i suggest we write an error specifically targeted for overriding of private functions(i.e cannot use virtual keyword with private function). It'll be less confusing. Thanks :)
