### ISSUE TITLE
Export used events (and errors) instead of just declared

### ISSUE THREAD

**Issue by dariusdev** [ethereum/solidity#9765]
https://etherscan.io/address/0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e#code
Proxy to https://etherscan.io/address/0x56e7d4520abfecf10b38368b00723d9bd3c21ee1#code 

Contract ABI not include event like: LogTrade, LogSell 

not sure it is Etherscan problem or solidy compiler?

**Comment by chriseth** [comment]
Are you saying that events declared in the library are listed in the library's ABI, but they are not listed in the ABI of the contract that emits the library's events?

If yes, then this is not a bug, but it is probably something we want to think over, especially as we provide more access to elements at the file-level:

We could provide access to errors and events that are used from a function of a contract, even if they are not defined in that contract.

**Comment by dariusdev** [comment]
events declared in the library are **not** listed in **any** ABI. 
At least it looks reviewing code provided by etherscan for addresses : 
https://etherscan.io/address/0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e#code  and
https://etherscan.io/address/0x56e7d4520abfecf10b38368b00723d9bd3c21ee1#code

**Comment by chriseth** [comment]
Remix shows the 'LogTrade' event in the "Events" library in the first code for me. Where are you looking for the events?

**Comment by dariusdev** [comment]
etherscan ABI section 
![image](https://user-images.githubusercontent.com/6444878/92571889-5befb200-f28c-11ea-8e95-04813ebe9a76.png)

**Comment by chriseth** [comment]
That's only the ABI for the contract at that address, not for the library it uses.

**Comment by dariusdev** [comment]
This is the library address: https://etherscan.io/address/0x56e7d4520abfecf10b38368b00723d9bd3c21ee1#code 
And ABI is empty without events.

**Comment by dariusdev** [comment]
If contract is using this library for execution and firing these events - these event should appear  in contracts ABI in my opinion

**Comment by chriseth** [comment]
The library address you mention is for a different library. The `Events` library does not have any code that can be deployed, so it does not have an address. So the events are listed in the ABI for the library, but you cannot retrieve it via Etherscan's interface.

In any case, we should find a way to export the used events as the title of the issue says.

**Comment by hrkrshnn** [comment]
For future reference, this would need https://github.com/ethereum/solidity/pull/10332 for a proper implementation.

The following cases need to be supported:
1. `emit L.Event()` inside a contract function, where `L` is a library.
2. `emit L.Event()` inside a free function that gets called from a contract.
3. `emit Event()` inside an internal library function (almost similar to the free function.)

Relevant: https://matrix.to/#/!poXqlbVpQfXKWGseLY:gitter.im/$KPcOdAbVwm-8MthR8QHgkyIpoIRynETJycsvFq5tCHA?via=gitter.im&via=matrix.org&via=ekpyron.org
