### ISSUE TITLE
output line number for unimplemented feature when compileing solc

### ISSUE THREAD

**Issue by gongbell** [ethereum/solidity#9775]
When we use "solc --ir contract.sol" to compile a contract, it will emit _UnimplementedFeatureError_. 

However, there is no indication in which line of the solidity file the error is. 

Is it possible to hint which line the unimplemented feature exists so we can examine detailed features manually?

**Comment by chriseth** [comment]
Pull request #9776 should implement your feature request. Can you provide some source code so that I can cross-check that it works for your case?

**Comment by Coder2Programmer** [comment]
Of course. There are [three solidity source code](https://drive.google.com/drive/folders/1PMME2dLxRMgx0lNIaMWrFDriZQVGP9t8?usp=sharing) files which emit _UnimplementedFeatureError_ during compilation .

**Comment by chriseth** [comment]
It works for your case!

**Comment by gongbell** [comment]
That is great. Is this patch merged on master branch already? How can we use the fix?
Thank you!

**Comment by chriseth** [comment]
The patch is still pending review, but will hopefully be part of 0.7.2

**Comment by gongbell** [comment]
Thank you!

**Comment by mijovic** [comment]
Issue will be closed when PR is merged. This should still be open until than
