### ISSUE TITLE
[SMTChecker] Support events

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9785]
```
Warning: Assertion checker does not yet implement this type of function call.
  --> uniswap-v2-core/contracts/UniswapV2ERC20.sol:51:14:
   |
51 |         emit Approval(owner, spender, value);
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I don't think the SMT checker needs to do anything with events though, just ignore them and don't emit a warning.

Could also include the low-levels logs, `log0()` to `log4()`.

**Comment by leonardoalt** [comment]
Agree. The arguments should still be visited for side effects.
