### ISSUE TITLE
[SMTChecker] Support selfdestruct

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9786]
Here's an extremely useful piece of code:
```
pragma experimental SMTChecker;

contract C {
  receive() external payable {}

  function f() public {
     selfdestruct(address(this));
     // Code unreachable here
  }
}
```

While this could be just added like #9782, I wonder what is the best approach for the CHC engine. No more code can be executed in the contract afterwards (at least not in the same instance).

**Comment by leonardoalt** [comment]
Yea CHC needs to handle it differently, although it won't be hard to implement.

**Comment by leonardoalt** [comment]
For info:
- `selfdestruct` terminates the current transaction's execution. However, `reverts` in parent internal transactions will undo the destruction.
- after destruction, any call to that contract reverts
- if in trusted mode, balance of contract needs to go to the argument

**Comment by hrkrshnn** [comment]
> after destruction, any call to that contract reverts

not quite
```solidity
contract C {
    function destroy() public {
        selfdestruct(payable(msg.sender));   
    }
    function one() public returns (uint) {
        return 1;
    }
}

contract D {
    C immutable c = new C();
    // will return 1
    function test() external returns (uint) {
        c.destroy();
        return c.one();
    }
}
```

**Comment by leonardoalt** [comment]
Right, should be any new transactions.
Sigh this is gonna be tricky to get right I think.
There's also the case where a contract can be redeployed in that address.

**Comment by leonardoalt** [comment]
Selfdestruct is going to be deprecated anyway so it doesn't make sense to implement this, especially since the implementation is rather complex.
