### ISSUE TITLE
[SMTChecker] Support type conversion of literals (i.e. address(0))

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9789]
Type conversions are not fully implemented and it may take a while until they are fully supported, but the above special case is so common and it should be easy to support, I'd suggest we make an exception here.

**Comment by leonardoalt** [comment]
We could easily support address(constant), address(this)

**Comment by axic** [comment]
Yes, all that would be nice, and they seem to be a low hanging fruit.
