### ISSUE TITLE
Constructor ignores visibility modifier

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#979]
For any of the visibilities (internal, external, private, public):

```
contract Test {
    function Test() internal {
    }
}
```

the following ABI is generated: `[{"inputs":[],"type":"constructor"}]`, and contract deployment works without hiccups.

I think it would make sense rejecting any visibility modifier on the constructor. Are there any cases currently where a non-public constructor is useful? We do not have static methods, so I don't see a way a non-public constructor could be executed.

**Comment by axic** [comment]
Fixing this will also "fix" #422.

**Comment by chriseth** [comment]
A non-public constructor is useful for base classes. We should enforce visibility and make contracts with non-public constructors abstract.

**Comment by chriseth** [comment]
An external constructor does not make much sense. The `external` keyword more or less forces all parameters to be in calldata, although constructor arguments are either in code or in memory. Furthermore, the other purpose of `external` is that such a function cannot be called internally. As constructors cannot really be "called" anyway, I would say it is fine to disallow `external` for constructors.

Therefore, I would say we should only allow `internal` and `public` for constructors.
