### ISSUE TITLE
How to listen for events from contract that created from other contract

### ISSUE THREAD

**Issue by tntdev21** [ethereum/solidity#9792]
How to listen for events from contract that created from other contract

**Comment by hrkrshnn** [comment]
Can you share some sample code on what you are trying to do?

**Comment by tntdev21** [comment]
@hrkrshnn I have 2 contracts:
```

contract Factory {
  function createContract() public {
    new MyContract();
  }
}

contract MyContract {
  event Foo(string _data);

  function willFireEvent() public {
    emit Foo('the data');
  }
}
```
Then create MyContract by making the transaction: `factory.methods.createContract().send()`.
So, when I call `myContract.methods.willFireEvent().send()` method, `Foo` event will be emited.

How to get info about `Foo`?

**Comment by hrkrshnn** [comment]
Perhaps this would be good a question for https://gitter.im/ethereum/solidity. 

One way to achieve this would be to get the address of `new MyContract()` (using another event), create an instance of `MyContract` in the frontend and listen to `MyContract.events.Foo`. But there maybe better ways.

**Comment by tntdev21** [comment]
@hrkrshnn I tried that but no luck. I think there is another way to get `Foo` info.

**Comment by hrkrshnn** [comment]
> I tried that but no luck

What is the issue?

**Comment by tntdev21** [comment]
Using `myContract.events.Foo` watcher ([docs](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#contract-events)), the events doesn't arrive.
Using `myContract.getPastEvents('Foo', options)` ([docs](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#getpastevents)), it return nothing.

**Comment by hrkrshnn** [comment]
Are you sure `myContract` is initialized at the correct address?

Anyway, this doesn't seem to be a solidity issue. Perhaps ask in web3 forums?

**Comment by tntdev21** [comment]
> Are you sure myContract is initialized at the correct address?

Yes.
> Anyway, this doesn't seem to be a solidity issue. Perhaps ask in web3 forums?

Yeah, I'll try this
