### ISSUE TITLE
Support structs, enums and tuples in sha3() and other "accept arbitrary parameters" functions

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#980]
- [ ] support structs
- [ ] support enums
- [ ] support tuples
- [ ] support contracts (encoded as addresses)
- [ ] disallow anything else as part of the type checker

```
contract test {

    struct TestStruct {
        uint a;
    }

    function test() {
        TestStruct memory testing = TestStruct({a: 1});
        sha3(testing);
    }
}
```

(Follow up from #332)

**Comment by chriseth** [comment]
This is most likely a duplicate of https://github.com/ethereum/solidity/issues/595

**Comment by pirapira** [comment]
I added "tuples" in the description because the title says "tuples".

**Comment by chriseth** [comment]
Since we only support `bytes memory` in those functions in the future, and everything else has to use `abi.encode`, this can be closed.

**Comment by krzkaczor** [comment]
If anyone is still wondering how to do this, use `abi.encodePacked`:

```solidity
keccak256(abi.encodePacked(struct.a, struct.b, struct.c));
```
