### ISSUE TITLE
Fix SMOD in ``test/formal/opcodes.py``.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9802]
The opcode implementation of SMOD in ``test/formal/opcodes.py`` uses SMT smod, which is not the same as EVM smod (e.g. ``-7 % 5 == -2`` vs ``-7 % 5 == 3``).
We might also want to check how hard it would be to actually fetch some opcode tests from the ethereum test repository and use them against those opcodes to be sure that our proofs are actually proving against what the EVM does, not what SMT does ;-).

**Comment by axic** [comment]
Alternatively you could consider running/extracting the evmone unit tests instead: https://github.com/ethereum/evmone/tree/master/test/unittests

@chfast hmm, it seems there aren't many tests for SMOD, in fact only div by zero?!

**Comment by chfast** [comment]
I actually don't have a lot of tests for SDIV / SMOD. But see these: https://github.com/chfast/intx/blob/master/test/unittests/test_div.cpp#L342-L375.
