### ISSUE TITLE
Tight packing should take number constants as uint256

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#982]
Unless explicitly typecasted to a shorter type.

I'm not fully sure which is the better behaviour, but I think this is more explicit and less prone to error.

**Comment by chriseth** [comment]
In general, I try to keep everything as uniform as possible. This exception might be useful for some cases, but it still is an exception that has to be explicitly documented.

**Comment by axic** [comment]
Since #2813 there is a warning for this. It could be turned into an error if this is decided on.

**Comment by chriseth** [comment]
I would opt for turning the existing warning into an error for 0.5.0
