### ISSUE TITLE
ICE when passing string literal into a calldata argument

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9821]
## Description
Compiler triggers an assertion saying `I sense a disturbance in the stack: 1 vs 2` when you call a function that expects a calldata `string` or `bytes` argument with a string/unicode/hex literal.

## Steps to Reproduce
```solidity
contract C {
    function g(string calldata _s) public {}

    function f() public {
        g("hello");
    }
}
```
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ContractCompiler.cpp(78): Throw in function void {anonymous}::StackHeightChecker::check()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: I sense a disturbance in the stack: 0 vs 1
[solidity::util::tag_comment*] = I sense a disturbance in the stack: 0 vs 1
```

## Environment

- Compiler version: `develop` (0.7.2-develop.2020.9.16+commit.b08b76ff.mod.Linux.g++)

**Comment by chriseth** [comment]
Might be similar to https://github.com/ethereum/solidity/issues/9803

**Comment by cameel** [comment]
It's indeed similar in that, just like #9803, it lacks a check that would forbid it but that's not the same check. I have actually discovered it while fixing #9803 (I'll create a PR in a moment) and my fix does not prevent this one from happening.

**Comment by cameel** [comment]
Looks like I was wrong. I must have checked it on a stale build without the fix. #9822 actually fixes both of these issues.
