### ISSUE TITLE
More detailed libevmasm and libyul optimiser step descriptions in Standard JSON docs

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9842]
As [discussed on twitter](
https://twitter.com/alexberegszaszi/status/1306681715767865344) auditors are still afraid of the optimiser and currently we only have a [verify brief description hidden within standard json](https://solidity.readthedocs.io/en/v0.7.1/using-the-compiler.html#input-description):
![image](https://user-images.githubusercontent.com/20340/93594968-bedcf980-f9ae-11ea-8237-8cc548fa7180.png)

We should create a section under internals explaining all the libevmasm optimiser steps. Later we should extend it with the libyul steps too.

**Comment by ekpyron** [comment]
The yul steps do have some documentation in  https://github.com/ethereum/solidity/blob/develop/libyul/optimiser/README.md linked from ~~https://github.com/ethereum/solidity/blob/develop/libyul/optimiser/README.md~~  https://solidity.readthedocs.io/en/v0.7.1/internals/optimiser.html (which in itself has some explanations of the libevmasm optimiser, but I haven't really read it and checked how good and extensive it is)...
The documentation of the yul steps is probably out-of-date and incomplete by now as well, though...

EDITED: wrong link

**Comment by axic** [comment]
I'm solely talking about "the documentation" and not files in the repository 😉

**Comment by ekpyron** [comment]
I meant "linked from https://solidity.readthedocs.io/en/v0.7.1/internals/optimiser.html" ;-).

**Comment by ekpyron** [comment]
But yeah - might be good to overhaul that one and not merely link the readme in the repository (which I don't think we've been properly maintaining anyways), but rather to move all of that to "the proper" documentation as well. But it's a good starting point in any case.

**Comment by cameel** [comment]
Is this task complete now? The Yul optimizer steps are now documented. The libevmasm optimizer also has a more detailed description in [Opcode-Based Optimizer Module](https://docs.soliditylang.org/en/latest/internals/optimizer.html#opcode-based-optimizer-module), though I'm not sure if it describes all the steps or just the inliner.

**Comment by axic** [comment]
@cameel I'd argue the documentation is still lacking. Ideally it would provide enough context so that people understand those Standard JSON settings.

**Comment by cameel** [comment]
Ah, so it's specifically about the Standard JSON input docs? Updated the title.

**Comment by axic** [comment]
Well not specifically, but that's the easiest way to explain the connection to each step.
