### ISSUE TITLE
Deleting a struct from the storage is not cheaper than zeroing its fields

### ISSUE THREAD

**Issue by CodeSandwich** [ethereum/solidity#9846]
## Description

When removing from storage a structure, which doesn't fill a single 32 byte word, it's not cheaper to zero out its fields than to delete the whole thing, see "steps to reproduce". This doesn't make sense, because deleting should just store zeros while zeroing a single field requires reading before storing to preserve the content of the rest of the fields.

I've noticed it first while testing a real-world contract compiled with Solidity 0.6.12 running on Buidler EVM, but Remix gas usage estimation on Solidity 0.7.1 aligns closely with it.

This effect disappears when the structure fills the storage cell completely, deleting the whole item becomes much cheaper.

## Environment

- Compiler version: 0.7.1, 0.6.12.
- Target EVM version (as per compiler settings): Istambul
- Framework/IDE (e.g. Truffle or Remix): Remix / Buidler
- EVM execution environment / backend / blockchain client: Remix / Buidler EVM
- Operating system: Web / Linux

## Steps to Reproduce

The gas usages are Remix estimations, but they match what I've noticed in Buidler EVM tests.

When the struct takes up only a fraction of the storage cell:

```solidity
pragma solidity ^0.7.0;

contract WeirdDeleteCostPartial {
    
    struct Data {
        uint32 first;
        uint32 second;
    }
    
    Data private data;
    
    // gas usage: 20984
    function zeroFirst() public {
        data.first = 0;
    }
    
    // gas usage: 20962
    function zeroSecond() public {
        data.second = 0;
    }
    
    // gas usage: 20940
    function zeroBoth() public {
        data.first = 0;
        data.second = 0;
    }
    
    // gas usage: 21006
    function deleteWhole() public {
        delete data;
    }
}
```

When the struct takes up the whole storage cell:

```solidity
pragma solidity ^0.7.0;

contract WeirdDeleteCostFull {
    
    struct Data {
        uint128 first;
        uint128 second;
    }
    
    Data private data;
    
    // gas usage: 20984
    function zeroFirst() public {
        data.first = 0;
    }
    
    // gas usage: 20959
    function zeroSecond() public {
        data.second = 0;
    }
    
    // gas usage: 5128
    function zeroBoth() public {
        data.first = 0;
        data.second = 0;
    }
    
    // gas usage: 5194
    function deleteWhole() public {
        delete data;
    }
}
```

**Comment by chriseth** [comment]
Thanks for opening this issue!

If the optimizer is activated, the compiler actually combines the two functions `deleteWhole` and `zeroBoth` into the following:
```
        /* "/tmp/x.sol":443:526  function zeroBoth() public {... */
    tag_9:
        /* "/tmp/x.sol":493:494  0 */
      0x00
        /* "/tmp/x.sol":480:494  data.first = 0 */
      dup1
      sload
      not(0xffffffffffffffff)
        /* "/tmp/x.sol":504:519  data.second = 0 */
      and
      swap1
      sstore
        /* "/tmp/x.sol":443:526  function zeroBoth() public {... */
      jump	// out
```

The differences in gas cost you see probably stem from the different paths of execution through the dispatch routine.

Note that for security reasons, the compiler does not assume that it can just "overwrite" the rest of the slot. You did not define any variable there but that does not mean that it is unused. It could be used due to an update routine or inline assembly.

Please feel free to reopen if you want to further discuss this.

**Comment by CodeSandwich** [comment]
> the compiler does not assume that it can just "overwrite" the rest of the slot

Aah, now with this constraint that behavior makes perfect sense! But that means that as a simple Solidity coder I'm paying 15K of gas for keeping `delete` a little hacky when it comes to releasing storage. It adds up quickly and as of 2020 mainnet that's real money. I'm not planning to use any hidden fields in my storage, is there a fast track to release it cheaply and reliably? One way that comes to my mind would be to fill up the rest of the slot with a dummy field to prove that Solidity is in full control. Is there a more elegant workaround?

**Comment by chriseth** [comment]
I'm only seeing a difference of 700 gas - where do you get the 15k from?

**Comment by CodeSandwich** [comment]
`WeirdDeleteCostPartial.deleteWhole()` costs 21006 gas while `WeirdDeleteCostFull.deleteWhole` just 5194, it's almost 16K of difference.

**Comment by chriseth** [comment]
Did you activate the optimizer? I'm seeing 23078 / 1806 compared to 22266 / 994. Also please take the storage clearing refund into account - clearing storage that has been zero before has a different cost than clearing storage that was not zero before. The numbers here are with storage that was zero before, as in your example.

**Comment by CodeSandwich** [comment]
Yes, these are numbers with optimizer enabled.

Could you explain, in which cases you're getting 23078, 1806, 22266 and 994 gas costs?

**Comment by chriseth** [comment]
The larger numbers are for the transaction itself (i.e. including the tx and data cost), the smaller numbers just for the execution.
