### ISSUE TITLE
ICE - Assembly exception for bytecode

### ISSUE THREAD

**Issue by wolflo** [ethereum/solidity#9850]
## Description
This contract:

```solidity
pragma experimental ABIEncoderV2;

library Lib {
    function throw1() internal {
        revert("1");
    }
}

contract Foo {
    constructor() public {
        Lib.throw1();
    }
    function throw2() public {
        revert("2");
    }
}
```

throws an internal compiler error:
```
Internal compiler error during compilation:
/solidity/libsolidity/interface/CompilerStack.cpp(1015): Throw in function void dev::solidity::CompilerStack::compileContract(const dev::solidity::ContractDefinition&, std::map<const dev::solidity::ContractDefinition*, std::shared_ptr<const dev::solidity::Compiler> >&)
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what: Assembly exception for bytecode
[dev::tag_comment*] = Assembly exception for bytecode
```
## Environment

- Compiler version: ^0.5.4
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A

## Steps to Reproduce

The contract compiles successfully with any of the following changes:
- remove `pragma experimental ABIEncoderV2;`
- remove either of the revert strings
- move `throw1` from `Lib` into `Foo`

**Comment by axic** [comment]
Doesn't seem to be happening anymore. Tried with 0.7.5/develop and 0.6.8. The problem was reported with `^0.5.4`.
