### ISSUE TITLE
Address with oversized literals

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9859]
```
contract C {
  function f() public pure {
    address a = address(0xffffffffffffffffffffffffffffffffffffffff);
    address b = address(0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF);
    address c = address(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff);
  }
}
```

The first line results in syntax error for missing checksum, the second has the valid checksum, and the last line is just accepted without any complaints. The generated code is identical to #9857.

I think we should disallow oversized literals with addresses, as it does not seem to provide any benefit. I'd argue this is a bug and not a breaking change, as it is not an intended behaviour.

**Comment by hrkrshnn** [comment]
closed via https://github.com/ethereum/solidity/pull/9865
