### ISSUE TITLE
Integers with oversized literals

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9860]
It affects integers just like it affects address (#9859). The following compiles without warnings:
```
contract C {
  function f() pure public returns (uint16) {
    return uint16(0xffffffffff);
  }
}
```

We have explicit type conversion to do truncation. I think the same should apply when we try to implicitly truncate literals -- it should not be allowed. Likewise with #9859, I think is a bug and not a breaking change.

**Comment by chriseth** [comment]
Subsumed in https://github.com/ethereum/solidity/issues/9861 now
