### ISSUE TITLE
Stricter explicit conversions from literals

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9861]
This contract compiles without warnings:
```
contract C {
  function f() pure public returns (uint16) {
    return uint16(-1);
  }
}
```

While we understand this will generate two's complement representation (e.g. `0xffff` for the above), this may be going against the explicitness goal we have. This behaviour is implicit conversion.

An explicit version looks like this:
```
contract C {
  function f() pure public returns (uint16) {
    return uint16(int16(-1));
  }
}
```

This is a similar discussion to #9857.

**Comment by chriseth** [comment]
I read this as an explicit conversion from a literal. Implicit conversion would be `return -1`.

**Comment by leonardoalt** [comment]
But the literal has no type, so the user has to infer what the semantics of the conversion are

**Comment by chriseth** [comment]
The literal does have a type. If everything is fine, no explicit conversion is needed. If you do an explicit conversion, it means the literal does not fit the type.

**Comment by hrkrshnn** [comment]
I think it's a good idea to disallow this conversion. We have `type(X).min` and `type(X).max` which can serve as a replacement for wrapping of integers.

**Comment by axic** [comment]
@chriseth If this were proper *explicit casting*, that includes truncation, then it should allow `uint16(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01)` which is 264-bit wide literal.

**Comment by axic** [comment]
To have more inconsistency we disallow truncating conversions with bytes:
```
Error: Explicit type conversion not allowed from "literal_string "4V"" to "bytes2".
  --> unsigned.sol:10:13:
   |
10 |      return bytes2(hex"123456");
   |             ^^^^^^^^^^^^^^^^^^^
```

**Comment by chriseth** [comment]
Decision from call: Let's try implementing it such that explicit conversions from literals are as strict as implicit conversions and see how much it breaks.

**Comment by hrkrshnn** [comment]
Closed via https://github.com/ethereum/solidity/pull/10108
