### ISSUE TITLE
No compilation error present when attempting to create a 4 dimensional struct array

### ISSUE THREAD

**Issue by jamesdawsonWD** [ethereum/solidity#9874]
## Description

I recieved the following bug today:

```
CompileError: InternalCompilerError:

Compilation failed. See above.
```

I narrowed  down the issue to the following line:

```        
    struct State {
        // ...other struct stufff
        StarSystem.Info[4][7][20][10000] stars;
     }
```

I am not sure if nested arrays can work with structs in this way or if this is valid code at all, but it definitely should have a compilation error message if someone else tries what I have done. Save them an hour or two :) 

## Environment

- Compiler version: 0.6.12
- Target EVM version (as per compiler settings): solc (not sure if this is what you mean?)
- Framework/IDE (e.g. Truffle or Remix): truffle
- EVM execution environment / backend / blockchain client: local dev blockchain
- Operating system: windows

## Steps to Reproduce

I have the following library
```
library StarSystem {

    struct Info {
        uint256 tokenId;
        bool hasFleet;
    }

}
```

My storage Library imports it and when I remove the stars from the state struct everything compiles fine.
```
import {StarSystem} from './StarSystem.sol';
library Storage {

    struct State {
        // ...other struct stufff
        StarSystem.Info[4][7][20][10000] stars;
     }

}
```

I replaced the stars with this nesting mapping and it compiled fine.

```
   mapping(uint8 => mapping(uint8 => mapping(uint8 => mapping(uint32 => StarSystem.Info)))) stars;
```

**Comment by cameel** [comment]
Could you try to create a minimal failing example (.sol file) that has this problem? I tried to reproduce your error with just the snippets you posted but it compiles just fine both on 0.6.2 and on 0.7.1 for me.

If you try to compile the contract directly with `solc`, you should get more details - at least the file name and line number pointing at the place in `solc` source where it failed. In any case, anything that triggers `InternalCompilerError` is definitely a bug in the compiler.

> Target EVM version (as per compiler settings): solc (not sure if this is what you mean?)

See https://solidity.readthedocs.io/en/v0.7.1/using-the-compiler.html#setting-the-evm-version-to-target

But if you didn't set it yourself then you're most likely targetting the default one (`istanbul`).

**Comment by chriseth** [comment]
I think we fixed that when we overhauled the "type too large for storage" check.
