### ISSUE TITLE
TypeError: "send" and "transfer" are only available for objects of type "address payable", not "address". admin.transfer(address(this).balance); in function endSale

### ISSUE THREAD

**Issue by lidiia-eld** [ethereum/solidity#9875]
**Hi, everyone!**
Please, advice me. 
How to fix this error in 'function endSale', when compile smart contract on remix.ethereum.org?

TypeError: "send" and "transfer" are only available for objects of type "address payable", not "address". admin.transfer(address(this).balance);
^------------^

This TypeError has appeared when I have changed old pragma solidity Version 0.4.21 to new pragma solidity >=0.7.1 in the smart contract.

COMPILER v0.7.1+commit.f4a555be and pragma solidity >=0.7.1;
LANGUAGE: Solidity
EVM VERSION: compiler default

**Part of the Code of the smart contract pragma solidity v0.4.21**:

```
    function endSale() public {
      require(msg.sender == admin);
      admin.transfer(address(this).balance);
    } 
      
}
```

_Thank you, for advance!_

**Comment by cakesoft-omkar** [comment]
Basically, there are two types : address v/s address payable

An address payable can receive ether while address cannot. In a nutshell, we can transfer ether to variable defined as address payable while the variable declared as address cannot receive ether.

To make an address payable, you can use the keyword payable before the variable name of an address type to enable it to receive ether.

Hope this helps !

**Comment by gitpushOmnik** [comment]
Basically, there are two types : `address` v/s `address payable`

An `address payable` can receive ether while `address` cannot. In a nutshell, we can transfer ether to variable defined as `address payable` while the variable declared as `address` cannot receive ether.

To make an address payable, you can use the keyword `payable` before the variable name of an address type to enable it to receive ether.

Hope this helps !

**Comment by chriseth** [comment]
To fix it, you can use `msg.sender.transfer(address(this).balance);`

**Comment by lidiia-eld** [comment]
**Hi. Thank you so much!** 
Your solution has fixed my problem with TypeError in smart contract.

> To fix it, you can use `msg.sender.transfer(address(this).balance);`
