### ISSUE TITLE
ICE in function void (anonymous namespace)::StackHeightChecker::check()

### ISSUE THREAD

**Issue by gitpushOmnik** [ethereum/solidity#9879]
## Description

ICE in 

    contract Print {
        function p1(uint x,string calldata sampletxt) public {
        }
        function p2() public {
            p1(1, "Sample");
        }
    }

## Environment

- Compiler version:Latest
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: MacOS

ICE : 

    /Solidity/libsolidity/codegen/ContractCompiler.cpp(81): Throw in function void (anonymous 
    namespace)::StackHeightChecker::check()
    Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
    std::exception::what: I sense a disturbance in the stack: 0 vs 1
    [solidity::util::tag_comment*] = I sense a disturbance in the stack: 0 vs 1

The error shows up in Remix as well.

**Comment by chriseth** [comment]
Thanks for reporting! This has already been fixed in latest develop. The fix will probably be released next week.
