### ISSUE TITLE
InternalCompilerError: Array too large for storage.

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#9884]
Hello all. I am working on a research project where we employ different fuzzing techniques to test the Solidity compiler. It would be a good idea to open an issue for every crash / bug we identify and you can provide us with corresponding feedback.

## Description

The contract below : 

contract C {
    uint[7**90][500] ids;
}

reports an internal compiler error :

Error: Array too large for storage

## Environment

- Compiler version: 0.6.9+
- Target EVM version (as per compiler settings): 0.6.9+commit.22be8592.Linux.g++
- Framework/IDE (e.g. Truffle or Remix): Remix (i found it from command line, while fuzzing the solc compiler with solidity grammar)
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 18.04

## Steps to Reproduce

fuzz solfuzzer with solidity grammar, and Superion.

**Comment by chriseth** [comment]
Thanks for opening this issue! @bshastry you might want to take a look.

The issue looks like something we are currently working on - @a3d4 can you confirm that your pull request fixes this?

**Comment by cameel** [comment]
This seems to have already been fixed somewhere between 0.6.10 and 0.6.12.

On 0.6.9 I get
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/Types.cpp(1777): Throw in function virtual solidity::u256 solidity::frontend::ArrayType::storageSize() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Array too large for storage.
[solidity::util::tag_comment*] = Array too large for storage.
```

But on 0.6.12 and 0.7.1 it's already a compiler error:
```solidity
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> /tmp/test.sol

Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.6.12;"
--> /tmp/test.sol

Error: Contract too large for storage.
 --> /tmp/test.sol:1:1:
  |
1 | contract C {
  | ^ (Relevant source part starts here and spans across multiple lines).

Error: Type too large for storage.
 --> /tmp/test.sol:2:1:
  |
2 | uint[7**90][500] ids;
  | ^^
```

**Comment by chriseth** [comment]
Oh you are right, @cameel ! Why aren't you fuzzing the develop branch, @CHM1993 ?

**Comment by chriseth** [comment]
Closing as the issue itself is fixed, but we can still continue the discussion.

**Comment by chamitro** [comment]
Yeah now we will fuzz 0.7.1. Thanks for the feedback.

**Comment by chamitro** [comment]
I will report every bug/crash I will find. Thanks again!

**Comment by chamitro** [comment]
In our current research we test solc compiler with AFL and Grammar Based
Mutation Fuzzing based in Solidity grammar. I think that it is a good idea
to open an issue for every crash and give us a feedback if it is a real
compiler bug/crash or not. I will inform you for every bug I will find

**Comment by chriseth** [comment]
Great, thanks!

**Comment by bshastry** [comment]
> grammar

Thank you @CHM1993 . Is your fuzzing framework public? Are you planning to make use of afl++ grammar mutator (https://github.com/AFLplusplus/Grammar-Mutator) by any chance?

**Comment by chamitro** [comment]
We will publish our work. Based in Superion paper [1], which extend AFL
with grammar based mutations and trimming, we fuzz solc compilers with
mutations based in contracts AST's. I will take a look in afl++ grammar
mutation.

thanks a lot.

[1] : https://arxiv.org/pdf/1812.01197.pdf

**Comment by chamitro** [comment]
Also I want to ask you about compiler hangs. There seems to be some of them
across the version, that make a contract to take some time to be compiled.
Is there any way to compare the compilation time with other compilers?

Thank you for  your time!

**Comment by bshastry** [comment]
> Is there any way to compare the compilation time with other compilers?

I'm not sure I understand your setup and I'm afraid any answer I give may have limited utility :(
