### ISSUE TITLE
Yul types don't work / documentation is inconsistent

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#9889]
## Description

The Yul documentation states that Yul variable declarations and literals can be annotated with types.  Of course, it also states that currently the only type in the EVM dialect is `u256`, making this not very useful, but still, it's documented as being possible.  Despite this, attempting to do this currently, even with the one type that is supposedly available -- `u256` -- yields a compile error.

There's an additional issue here, in that the documentation also demonstrates types `uint256` and `uint32`, even though these types are not supposed to exist (unless `uint256` is supposed to be an alias for `u256`).

These latter types, that are not supposed to exist, should probably be removed from the examples in documentation (unless `uint256` is added as an alias to `u256`).  Meanwhile either the type `u256` should be added, or the documentation should be updated to no longer assert that it exists.

## Environment

- Compiler version: 0.7.1
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle

## Steps to Reproduce

```solidity
pragma solidity ^0.7.1;
contract AssemblyTest {
  function test() public {
    assembly {
      let x: u256
      pop(3: u256)
    }
  }
}
```

**Comment by ControlCplusControlV** [comment]
I would vote in favor of adding the ability to add types to Yul, as this is very helpful in current L2 efforts as different VM targets and wordsizes rely on different wordsizes, so laying the groundwork for Yul types even if Solidity is defaulting all of them to u256 for the EVM, other L2s may benefit from being able to use u32 or differently sized variables.
