### ISSUE TITLE
Formal Verification: Extend sum theory

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#991]
It should be possible to reason about mappings of uint256 such that "the sum of the mapping values increases by x if x is added to one of the elements".

**Comment by pirapira** [comment]
The property would look like [this](https://github.com/pirapira/token_why3/blob/master/token.mlw#L119) but a tiny bit more general one.

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
