### ISSUE TITLE
Add optimizer rule iszero(eq(x, 0)) -> gt(x, 0)

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9923]
This rule has to be added to RuleList.h

**Comment by hrkrshnn** [comment]
There is a rule that converts `eq(X, 0)` to `iszero(X)` (in `simplificationRuleListPart2`)

So the expression gets first converted into `iszero(iszero(X))`. I think we can write a rule that converts `iszero(iszero(X))` into `gt(x, 0)` (after verifying it.)

**Comment by hrkrshnn** [comment]
I'm not sure if converting `iszero(iszero(X))` to `gt(x, 0)` make sense, gas wise. The former needs one `push`, two `iszero`. The latter needs two `push` and one `gt`. So they cost the same gas.

**Comment by chriseth** [comment]
yes, probably it is cheaper to remove the constant and keep it at `iszero(iszero(x))`

**Comment by hrkrshnn** [comment]
I'm closing this since the current simplification, i.e., `iszero(iszero(x))` is good enough
