### ISSUE TITLE
Migrate bytecode comparison from Travis to CircleCI

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9931]
Related to #9258. Would also probably solve #4044.

Right now the bytecode comparison script runs on TravisCI (https://github.com/ethereum/solidity/blob/v0.7.2/.travis.yml#L208). We want to move away from Travis and move it to CircleCI.

When we move everything off Travis we'll be able to take away its write permissions to `solidity` repo/releases.

**Comment by cameel** [comment]
Notes from the call today:
- Bytecode comparisons are not a part of the release process so they do not introduce a delay there, unlike the binary builds (#9932).
- The biggest issue with having it in Travis is that we can only do the check after the merge to `develop`.
- Apart from just moving it, we also want to change the way it works:
    - The generated bytecode should be an artifact in CircleCI.
    - There should be a job that depends on all the jobs that produce bytecode for specific platforms and compares it. This way we can get rid of the [solidity-test-bytecode](https://github.com/ethereum/solidity-test-bytecode) repo.

**Comment by chriseth** [comment]
Bytecode comparison is on circleci now.

**Comment by cameel** [comment]
Just for future reference, it was implemented in this PR: #10039.
