### ISSUE TITLE
Move release binary builds off Travis

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9932]
Related to #9258.

Our release binaries for MacOS and Windows come from CircleCI now (#9811). The rests is still built on Travis. Together with #9931 this task is a part of the initiative to reduce the number of CI systems that we rely on and that need elevated access privileges to the solidity repo.

The builds should be moved either to CircleCI or Github actions.

**Comment by cameel** [comment]
Notes from the call today:
- Builds for all platforms are already available on CircleCI so we definitely want to move there, no matter whether it's just an intermediate step before Github actions or the final destination.
- Switching to getting the emscripten builds from CircleCI requires no additional work (maybe apart from updating the release checklist).
- Linux binaries on CircleCI are currently not static so we need to have a static build there before we can switch.

**Comment by chriseth** [comment]
Travis has been disabled.
