### ISSUE TITLE
Static page listing binaries available at solc-bin.ethereum.org

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9934]
Part of #9258.

Currently the main page at solc-bin.ethereum.org just serves a raw, unformatted Markdown file. We'd like to have a simple, static HTML page listing all the binaries available in solc-bin.ethereum.org instead. The information should come from the `list.json` files.

The page should list all the details but for readability they should be folded by default. The page should still work without JavaScript though. At worst, everything should be unfolded without JS but it would be best to use a semantic tag like [`<details>`](https://developer.mozilla.org/pl/docs/Web/HTML/Element/details) to make it completely static.

The page should also contain the content of [README.md](https://github.com/ethereum/solc-bin/blob/gh-pages/README.md). We should also expand that file to include more information about the whole setup. In particular, what is the recommended URL to download them from and that they're also available via other means (Swarm, IPFS).

**Comment by cameel** [comment]
Description updated with details from today's call.

**Comment by axic** [comment]
Today we discussed it would be nice to
1. Improve the `update` script to populate the readme with a table of releases with links to each binary (and the github release page) -- which is basically this issue
2. Run a "markdown to html" renderer in `s3-sync.sh` -- which was added by https://github.com/ethereum/solc-bin/pull/85
