### ISSUE TITLE
FixedPointType not implemented.

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#9936]
Hi again, 
I want to report a bug found in solidity 0.7.1 and 0.7.2 compiler :

## Description

The contract below :

contract C {
    function f() public returns (ufixed id) {
        assembly {
            id := chainid()
        }
    }
}

reports an internal compiler error :

FixedPointType not implemented. 

## Environment

- Compiler version: 0.7.1+ and 0.7.2+
- Target EVM version (as per compiler settings): 0.7.1+commit.f4a555be and 0.7.2+commit.51b20bc0
- Framework/IDE (e.g. Truffle or Remix): Remix (i found it from command line, while fuzzing the solc compiler with solidity grammar)
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 16.04, Xenial

## Steps to Reproduce

fuzz solfuzzer with solidity grammar, and Superion

**Comment by hrkrshnn** [comment]
The same as in https://github.com/ethereum/solidity/issues/9944. Closing.
