### ISSUE TITLE
Typecast shouldn't allow width and signedness at the same time

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#9939]
`uint16 x = uint16(int8(-1));`
The value of `x` depends on whether sign or width conversion is applied first, which is confusing.
I'd propose to disallow conversion when both size and sign are different.
In this case the user would be forced to choose and make explicit which comes first:
sign `uint16 x = uint16(uint8(int8(-1)));`
size `uint16 x = uint16(int16(int8(-1)));`

chriseth: As an extension, we should also disallow conversion between address and any integer that is not unsigned 160 bits.

**Comment by chriseth** [comment]
Sounds good!

**Comment by hrkrshnn** [comment]
> We should only convert one of "signedness", width and "kind" at the same time (kind being bytesNN, uint, address)

https://github.com/ethereum/solidity/pull/9865#discussion_r500978863

**Comment by chriseth** [comment]
Implemented in #10223
