### ISSUE TITLE
Incorrect file index in source maps

### ISSUE THREAD

**Issue by nebojsa94** [ethereum/solidity#9940]
https://ropsten.etherscan.io/address/0x2c53dd4d14eeb06756c27052675c9da8704ec636#code

In the Deployed ByteCode Sourcemap section, there is a `7:139:1:-` instruction, but there is only one source file.
I was also able to reproduce this issue in the local environment.

**Comment by chriseth** [comment]
This might be the internal utility file that is generated by the compiler: https://solidity.readthedocs.io/en/develop/using-the-compiler.html You can obtain it under the key `generatedSources`. Some more details: https://solidity.ethereum.org/2020/09/28/solidity-0.7.2-release-announcement/

I'm closing this issue - please feel free to re-open if you think this assessment is wrong.

**Comment by chriseth** [comment]
I just realized that we only explained this new feature in the "using the compiler" section but not in the "source mappings" section. Here is a PR to fix it: https://github.com/ethereum/solidity/pull/9941
