### ISSUE TITLE
Unable to uninstall Solidity using npm in Ubuntu

### ISSUE THREAD

**Issue by anupam-io** [ethereum/solidity#9950]
## Description
I don't what's wrong with my npm or node installations. But now I am unable to remove Solidity in my system. I can't upgrade or change it either. I don't know if it is a problem with npm or solidity.

<pre><font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ npm -v
6.14.8
<font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ node -v
v10.19.0
<font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ solc --version
solc, the solidity compiler commandline interface
Version: 0.5.16+commit.9c3226ce.Linux.g++
</pre>

When I trying to uninstall solidity using ```npm uninstall solc``` this is happening:
<pre><font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ npm uninstall solc
<span style="background-color:#000000"><font color="#E5E5E5">npm</font></span> <span style="background-color:#CDCD00"><font color="#000000">WARN</font></span> anupam@1.0.0 No description
<span style="background-color:#000000"><font color="#E5E5E5">npm</font></span> <span style="background-color:#CDCD00"><font color="#000000">WARN</font></span> anupam@1.0.0 No repository field.

audited 99 packages in 2.136s

2 packages are looking for funding
  run `npm fund` for details

found 1 <b>low</b> severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
</pre>

As suggested above, here is the ```npm fund```:
<pre><font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ npm fund
anupam@1.0.0
+-- https://github.com/sponsors/feross
| `-- safe-buffer@5.2.1
+-- https://www.patreon.com/feross
| `-- safe-buffer@5.2.1
+-- https://feross.org/support
| `-- safe-buffer@5.2.1
`-- https://github.com/sponsors/sindresorhus
  `-- p-limit@2.3.0

</pre>
Other commands suggested ```npm audit``` and ```npm audit fix``` are given below:
<pre><font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ npm audit
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font>                      === npm audit security report ===                       <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font>                                Manual Review                                 <font color="#7F7F7F"> </font>
<font color="#7F7F7F"> </font>            Some vulnerabilities require your attention to resolve            <font color="#7F7F7F"> </font>
<font color="#7F7F7F"> </font>                                                                              <font color="#7F7F7F"> </font>
<font color="#7F7F7F"> </font>         Visit https://go.npm.me/audit-guide for additional guidance          <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font> <b>Low</b>           <font color="#7F7F7F"> </font> <b>Insecure Credential Storage</b>                                  <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font> Package       <font color="#7F7F7F"> </font> web3                                                         <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font> Patched in    <font color="#7F7F7F"> </font> No patch available                                           <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font> Dependency of <font color="#7F7F7F"> </font> web3                                                         <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font> Path          <font color="#7F7F7F"> </font> web3                                                         <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
<font color="#7F7F7F"> </font> More info     <font color="#7F7F7F"> </font> https://npmjs.com/advisories/877                             <font color="#7F7F7F"> </font>
<font color="#7F7F7F">                                                                                </font>
found 1 <b>low</b> severity vulnerability in 99 scanned packages
  1 vulnerability requires manual review. See the full report for details.
<font color="#00CD00"><b>anupam@g3</b></font>:<font color="#0000EE"><b>~</b></font>$ npm audit fix
<span style="background-color:#000000"><font color="#E5E5E5">npm</font></span> <span style="background-color:#CDCD00"><font color="#000000">WARN</font></span> anupam@1.0.0 No description
<span style="background-color:#000000"><font color="#E5E5E5">npm</font></span> <span style="background-color:#CDCD00"><font color="#000000">WARN</font></span> anupam@1.0.0 No repository field.

up to date in 0.357s

2 packages are looking for funding
  run `npm fund` for details

fixed 0 of 1 vulnerability in 99 scanned packages
  1 vulnerability required manual review and could not be updated
</pre>

Please help me. I want to downgrade the version of solidity too.

## Environment

- Compiler version: 0.5.16+commit.9c3226ce.Linux.g++
- Target EVM version (as per compiler settings): -
- Framework/IDE (e.g. Truffle or Remix): -
- EVM execution environment / backend / blockchain client: -
- Operating system: Ubuntu 20.04.1 LTS

**Comment by cameel** [comment]
Hello. I think that the `solc` executable you're running does not come from the [`solc` npm package](https://www.npmjs.com/package/solc) so you won't be able to uninstall it with npm. Your `solc` appears to be the native linux binary, installed either via your system package manager or just placed manually in your path. If you run `which solc` or `type solc` it will show you where the file is installed. If it's not in a `node_modules` directory, it was almost certainly not installed with npm.

The npm package is the JavaScript wrapper for the compiler ([solc-js](https://github.com/ethereum/solc-js)) and it comes with `soljson.js` which is an asm.js/wasm build of the compiler. It does not install the native binary so it must have come from somewhere else.

**Comment by cameel** [comment]
> Please help me. I want to downgrade the version of solidity too.

You can get any version you need directly from https://github.com/ethereum/solc-bin/tree/gh-pages/linux-amd64. They're all static builds so you can just download and run them without worrying about dependencies.

But if you're using a framework like Truffle, Buidler, Brownie, dapp-tools, etc. rather than the compiler directly then the framework is already installing the compiler binary for you and you should downgrade using the mechanism it provides. For example if you're using Truffle, you just need to put the version you want in the configuration and it will download it for you before building your project: https://www.trufflesuite.com/docs/truffle/reference/configuration#solc

**Comment by anupam-io** [comment]
Thanks @cameel .
I figured it out using ```which solc``` and removed the current version through ```snap```.
Installed another version using ```npm install --save solc@0.4.17```

**Comment by cameel** [comment]
Great! Good to hear that it worked out :)
