### ISSUE TITLE
ICE in calldataEncodedSize() when a public library function takes a storage parameter containing a nested maping

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#9957]
## Description

This contract:
```solidity
library Test {
   struct Nested { mapping(uint => uint )[2][] a; } uint y;
    struct X { Nested n; }
    function f(X storage x){}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.h(224): Throw in function virtual unsigned int solidity::frontend::Type::calldataEncodedSize(bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.3-develop.2020.10.2+commit.756e21a8.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by cameel** [comment]
An older one this time. It started crashing the compiler in 0.6.7.

And it's a nice construction. I tried simplifying it but removing pretty much anything makes it report a compiler error instead.

### Errors on 0.6.6
```
Error: No visibility specified. Did you intend to add "public"?
 --> /tmp/test.sol:4:5:
  |
4 |     function f(X storage x){}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Library cannot have non-constant state variables
 --> /tmp/test.sol:2:53:
  |
2 |    struct Nested { mapping(uint => uint )[2][] a; } uint y;
  |                                                     ^^^^^^
```

**Comment by agroce** [comment]
The construction is luck; for Solidity I tend to just run a line-based minimizer on what my custom AFL finds.  Here, I think it only had to remove a single comment line, anyway.

I could go more aggressive on reducing, but they seem small enough to be easy to hand-polish as it is, and I'm storing the line-reduced versions for some investigation of where the interesting code comes from (something beyond line reduction makes that provenance a lot harder to figure out).  If you all would find more reduction helpful, I can install CReduce or something...

**Comment by cameel** [comment]
Getting even smaller examples is always nice but they're already very small an easy to work with. Just the fact that they're self-contained makes them very easy to reproduce and debug. It's much, much easier than when someone submits e.g. a whole Truffle project and gets an error somewhere in the middle of a test run. Basically a perfect repro.

**Comment by cameel** [comment]
Smaller test case found by @hrkrshnn. And this one is valid code so it's not just a cosmetic issue after all.
```solidity
struct Nested { mapping(uint => uint )[2][] a; } 
struct X { Nested n; }
library Test {
    function f(X storage x) public {}
}  
```

**Comment by agroce** [comment]
Oh, nice

**Comment by agroce** [comment]
Too bad there's no way I can think of to take a crashing input and automatically explore around to see if there's a "should compile" variation, when it's not compiling.  But depending on if it is a long-standing or novel bug, I can't see an easy way to even determine if it should compile.

**Comment by a3d4** [comment]
Slightly simplified:
```
struct S { mapping(uint => uint)[2] a; }
library L {
    function f(S storage s) public {}
}
```

**Comment by cameel** [comment]
@agroce Passing it through an external grammar checker might tell you if it looks like a something that could be valid code. Unfortunately our [grammar definition](https://solidity.readthedocs.io/en/latest/grammar.html) is probably not detailed enough for this.

But from practical standpoint, identifying bugs in the first place is the biggest value a fuzzer can add. Once we have a small, self-contained repro, simplifying it further is usually straightforward. Even in cases like in this one where it's less obvious, the person fixing the bug can find better examples fairly easily after digging into the problem.
