### ISSUE TITLE
Optimizer: Investigate if consecutive calls to sstore for same slot will be optimized out to only one

### ISSUE THREAD

**Issue by mijovic** [ethereum/solidity#9964]
When we discussed deleting structs we had to distinct cases for packed and unpacked types and we could possibly remove that distinction ([Comment...](https://github.com/ethereum/solidity/pull/9843#discussion_r499424472)) if optimizer is able to optimizes `sstores`

**Comment by chriseth** [comment]
Duplicate of https://github.com/ethereum/solidity/issues/6728 ?

**Comment by mijovic** [comment]
> Duplicate of #6728 ?

I think it is. We can close this one in favor of #6728
