### ISSUE TITLE
UnimplementedFeatureError in ABIEncoderV1 file when inheriting from ABIEncoderV2 contract

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9970]
Extracted from https://github.com/ethereum/solidity/issues/8379#issuecomment-704342651

## Steps to Reproduce
`a.sol`:
```solidity
pragma experimental ABIEncoderV2;

contract C {
    struct Item {
        uint x;
    }

    function get() external view returns(Item memory) {}
}
```
`b.sol`:
```solidity
import "./a.sol";

contract D is C {}
```
Run it with:
```bash
solc b.sol
```
Output:
```
Unimplemented feature:
/solidity/libsolidity/codegen/CompilerUtils.cpp(420): Throw in function void solidity::frontend::CompilerUtils::encodeToMemory(const TypePointers&, const TypePointers&, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Encoding type "struct C.Item memory" not yet implemented.
[solidity::util::tag_comment*] = Encoding type "struct C.Item memory" not yet implemented.
```

`a.sol` compiles just fine on its own so the feature is not really unimplemented.

## Environment
- Compiler version: 0.7.2+commit.51b20bc0.Linux.g++

**Comment by chriseth** [comment]
My first guess would be that `b.sol`still needs ABIEncoderV2 to be activated.

**Comment by cameel** [comment]
But why? `get()` is completely defined in `a.sol` so it should have the encoder enabled, shouldn't it?

**Comment by chriseth** [comment]
I would say let's do whatever is easier in terms of the implementation.

**Comment by cameel** [comment]
Another one similar to this. This time it's inheriting from a contract that only calls an ABIEncoderV2 function:

`a.sol`:
```solidity
pragma experimental ABIEncoderV2;

struct Data {
    bool flag;
}

contract A {
    function get() public view returns (Data memory) {}
}

contract B {
    function foo() public {
        A(0x00).get();
    }
}
```

`b.sol`:
```solidity
import "./a.sol";

contract C is B {}
```

```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/CompilerUtils.cpp(1440): Throw in function unsigned int solidity::frontend::CompilerUtils::loadFromMemoryHelper(const solidity::frontend::Type&, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

**Comment by cameel** [comment]
And another. V1 contract overriding a modifier inherited from a V2 contract:

**EDIT: Actually, this is just a variation of the case above - just with constrctor rather than a public function - and has nothing to do with the modifiers.**

`a.sol`:
```solidity
pragma experimental ABIEncoderV2;

struct Data {
    bool flag;
}

contract A {
    function get() public view returns (Data memory) {}
}

contract B {
    constructor() validate {
        A(0x00).get();
    }

    modifier validate() virtual {
        _;
    }
}
```

`b.sol`:
```solidity
import "./a.sol";

contract C is B {
    modifier validate() override {
        _;
    }
}
```

```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/CompilerUtils.cpp(1440): Throw in function unsigned int solidity::frontend::CompilerUtils::loadFromMemoryHelper(const solidity::frontend::Type&, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

Also, if I change `B` to inherit from `A`, I hit the `UnimplementedFeatureError` instead:
```
Unimplemented feature:
/solidity/libsolidity/codegen/CompilerUtils.cpp(420): Throw in function void solidity::frontend::CompilerUtils::encodeToMemory(const TypePointers&, const TypePointers&, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Encoding type "struct Data memory" not yet implemented.
[solidity::util::tag_comment*] = Encoding type "struct Data memory" not yet implemented.
```

**Comment by cameel** [comment]
The two test cases in comment above are actually a different thing, more related to #9969 so I'm fixing them there.

@chriseth 
> I would say let's do whatever is easier in terms of the implementation.

Turns out that we already had a check against this case in `ContractLevelChecker` but it was buggy. It was checking the parameters second time instead of going over the return parameters. There is even a test case for that check but it uses ABIEncoderV2 types both for the parameters and for the return value so even without checking the return value the error was still there and the test did not fail.
