### ISSUE TITLE
Document source maps

### ISSUE THREAD

**Issue by mbrock** [ethereum/solidity#998]
Document source maps as described in https://github.com/ethereum/solidity/issues/713
## 

It seems from my cursory investigation that `--combined-json=srcmap` could be useful for my purposes, but I'm having a hard time understanding the code that generates them (`CompilerStack::computeSourceMapping`) and I've found no documentation of the meaning of the `srcmap` strings.

They look like this:

```
0:63:1:-;;;15:46;32:10;:15;;:26;48:9;32:26;;;;;;;;;;;;;;;;;;;;;;15:46;0:63;;;;;;
```

I've gathered that there's one `;` entry per assembly instruction. I think that the comma-separated fields are:
1. source location start index
2. source location length
3. source file index
4. instruction jump type

And that these fields are "compressed" such that for the current entry, only the prefix of fields which are changed from the previous entry are printed.

Some questions:
1. What's the difference between `srcmap` and `srcmap-runtime`?
2. Can I as a `solc` user know the order of source file indices?
3. What is the significance of the instruction jump type?
4. Is there an open source example of using the `srcmap` fields?

Thanks!

**Comment by axic** [comment]
I think they were documented, but can't seem to find that now.

> What's the difference between srcmap and srcmap-runtime?

They map to the `bytecode` vs. `runtime bytecode`. The first one is used to deploy the contract, while the second is the actual contract code after creation.

**Comment by dbrock** [comment]
See https://github.com/ethereum/solidity/issues/713, https://github.com/ethereum/solidity/pull/699 and https://github.com/nexusdev/dapple/pull/282!

**Comment by chriseth** [comment]
They actually are documented: https://github.com/ethereum/solidity/blob/develop/docs/miscellaneous.rst#source-mappings
The question is why the docs do not show up on solidity.readthedocs.io

**Comment by chriseth** [comment]
Ah, they are there: https://solidity.readthedocs.io/en/develop/miscellaneous.html#source-mappings reload did the trick.

**Comment by nfalliere** [comment]
If anyone ends up on this thread, the source mappings doc now has its own page: https://docs.soliditylang.org/en/latest/internals/source_mappings.html

**Comment by PaulRBerg** [comment]
> I've gathered that there's one `;` entry per assembly instruction

Almost correct. If there are `n` assembly instructions, there are `n-1` semicolons.
