### ISSUE TITLE
Erlang parser based on grammar.txt

### ISSUE THREAD

**Issue by walter-weinmann** [ethereum/solidity#999]
Version 1.0.0 of syparse is now available at [Github](https://github.com/walter-weinmann/syparse).

syparse is a production-ready Solidity parser written in pure Erlang. syparse is closely aligned to the Solidity project and in future will be adapted on a regular basis as the Solidity project evolves. The file grammar.txt provides the basis for the definition of the LALR grammar.

Comments and suggestions are welcome.

The following rules are not supported:
- `Statement = ExpressionStatement` - seems to be redundant
- `SimpleStatement = VariableDefinition` - seems to be redundant
- `NumberLiteral = '0x'? [0-9]+ (' ' NumberUnit)?` - the ' ' can not be enforced with my parser tools (leex & yecc)

**Comment by bobsummerwill** [comment]
Good job, Walter!

**Comment by walter-weinmann** [comment]
Done by #1011.
