### ISSUE TITLE
Replace invalid opcode by Panic()

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9995]
The following situations currently create an invalid opcode or a Panic in the future:

 - failing assert()
 - arithmetic overflow in addition, multiplication, exponentation, negation, ...
 - arithmetic underflow in addition, multiplication, exponentation, negation, ...
 - division / modulo by zero
 - array too large (either storage or memory)
 - memory allocation error (too much memory required for something)
 - empty array pop
 - array out of bounds access
 - enum conversion error
 - calling invalid internal function

Note that the old code-generator still contains code that uses "invalid opcode".

Suggestions for how to assign error codes:
 - `0`: generic / unspecified error. Used by `assert()`.
 - `0x11`: arithmetic underflow or overflow
 - `0x12`: division or modulo by zero
 - `0x21`: enum conversion error
 - `0x31`: empty array pop
 - `0x32`: array out of bounds access
 - `0x41`: resource error (too large allocation or too large array)
 - `0x51`: calling invalid internal function

**Comment by chriseth** [comment]
Replaced by a comment in the other issue: https://github.com/ethereum/solidity/issues/9824#issuecomment-705734624

**Comment by ekpyron** [comment]
I wonder whether we should be more generous and at least use 16 bits for it and reserve 256 slots in each category or even more... it's not like we don't have enough space in the uint256...

**Comment by ekpyron** [comment]
Ah, damn, now you moved the discussion :-).
